### ISSUE TITLE
latest goimports panicing

### ISSUE THREAD

**Issue by alexec** [golang/go#39864] opened 2020-06-25 20:25 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/acollins8/Library/Caches/go-build"
GOENV="/Users/acollins8/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/acollins8/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/acollins8/go/src/github.com/argoproj/argo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s0/41b1vy2d6nn42rmgltmbrpdw0000gp/T/go-build552208786=/tmp/go-build -gno-record-gcc-switches -fno-common</pre></details>

### What did you do?

```
2020/06/25 13:21:10 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11cdcc5]

goroutine 1 [running]:
flag.newStringValue(...)
	/usr/local/Cellar/go/1.13.4/libexec/src/flag/flag.go:226
flag.StringVar(...)
	/usr/local/Cellar/go/1.13.4/libexec/src/flag/flag.go:757
main.init.0()
	/Users/acollins8/go/pkg/mod/golang.org/x/tools@v0.0.0-20200625173320-e31c80b82c03/cmd/goimports/goimports.go:51 +0x85
```

### What did you expect to see?

work OK

### What did you see instead?

panic

**Comment by findleyr** [comment] 2020-06-25 20:31
Thanks, this is a dupe of #39862 -- the fix may not have propagated to @latest on proxy.golang.org yet.

**Closed by findleyr** 2020-06-25 20:31 UTC

**Comment by alexec** [comment] 2020-06-25 20:43
https://github.com/argoproj/argo/pull/3311
