### ISSUE TITLE
go/parser: comments to parameters are not processed

### ISSUE THREAD

**Issue by wzshiming** [golang/go#25814] opened 2018-06-11 03:10 UTC
## Comments to parameters are not processed here
https://github.com/golang/go/blob/b74f7321e594e2c4bcdf1b048e755ddc90c4134d/src/go/parser/parser.go#L835

## I think this comment should be processed
``` golang
package main

import (
	"go/ast"
	"go/parser"
	"go/token"

	ffmt "gopkg.in/ffmt.v1"
)

const f = `
package a

func A(
	// Why isn't this a doc on x
	x int , // Why isn't this a comment on x
) {

}
`

func main() {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "_", f, parser.ParseComments)
	if err != nil {
		ffmt.Mark(err)
		return
	}
	for _, v := range f.Decls {
		switch t := v.(type) {
		case *ast.FuncDecl:
			ffmt.P(t)
			//&go/ast.FuncDecl{
			// Doc:  <nil>
			// Recv: <nil>
			// Name: <A>
			// Type: &go/ast.FuncType{
			//  Func:   go/token.Pos(13)
			//  Params: &go/ast.FieldList{
			//   Opening: go/token.Pos(19)
			//   List:    slice[
			//    &go/ast.Field{
			//     Doc:     <nil>
			//     Names:   slice([]*ast.Ident{(*ast.Ident)(0xc042050460)})
			//     Type:    go/ast.Expr(&ast.Ident{NamePos:54, Name:"int", Obj:(*ast.Object)(nil)})
			//     Tag:     <nil>
			//     Comment: <nil>
			//    }
			//   ]
			//   Closing: go/token.Pos(92)
			//  }
			//  Results: <nil>
			// }
			// Body: &go/ast.BlockStmt{
			//  Lbrace: go/token.Pos(94)
			//  List:   slice[ ]
			//  Rbrace: go/token.Pos(97)
			// }
			//}
		}
	}
}
```

**Comment by agnivade** [comment] 2018-06-11 04:27
Indeed, looks like a corner case. @griesemer

**Comment by agnivade** [comment] 2018-06-11 04:52
Wait sorry, if I set the mode to `parser.ParseComments` and print the ast, it indeed prints all the parameters.

```go
func main() {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "_", f, parser.ParseComments)
	if err != nil {
		ffmt.Mark(err)
		return
	}
	ast.Print(fset, f)
}
```

The comments are part of `f.Comments`, not `f.Decls`, as clarified here https://godoc.org/go/ast#File.

```go
for _, v := range f.Comments {
	ffmt.P(v)
}
```

I am not sure whether an `ast.Field` is supposed to have comments in the `Comment` section. Leaving this open until someone can clarify that.

**Comment by wzshiming** [comment] 2018-06-11 05:10
It only exists in File.Comments , not in ast.field
I'm trying to fix it https://github.com/golang/go/pull/25817

**Comment by griesemer** [comment] 2018-06-11 17:03
@wzshiming Unfortunately this is by design (these comments are not shown in godoc, after all). I wouldn't call it "not reasonable", but I agree that it's unfortunate.

Keep in mind that go/ast, go/parser, and friends are among the very first larger Go packages ever written and they show their age. Also, and I'm taking full responsibility for this, only doc comments are directly attached to AST nodes; all the other ones are collected in the File.Comments list and must be "interspersed" by position when printing. It works ok for gofmt but it's a real pain elsewhere. In retrospect that was a bad design decision. We know all about it.

Closing as unfortunate.

**Closed by griesemer** 2018-06-11 17:03 UTC
Labels: NeedsInvestigation
