### ISSUE TITLE
x/website: incorrect time complexity

### ISSUE THREAD

**Issue by mkraft** [golang/go#58982] opened 2023-03-11 12:06 UTC
URL: https://go.dev/doc/effective_go#interfaces

The method `(Sequence).String` is mistakenly said to have a quadratic time complexity but it's actually linear, or O(N).

Relevant quotes:

> Loop is O(N²); will fix that in next example.

and

> It also has complexity O(N²), which is poor.

**Comment by Merovius** [comment] 2023-03-11 16:45
No, the complexity is quadratic - specifically `O(n•(log(n)+m))`, where `n` is the length of the `Sequence` and `m` is the maximum length of the string. `str += fmt.Sprint(elem)` is `O(m)` and it's executed `n` times. Additionally, the slice gets copied (`O(n)`) and sorted (`O(n•log(n))`).

**Comment by Merovius** [comment] 2023-03-11 16:50
Note, specifically, that `s += x` has to a) allocate a buffer of length `len(s)+len(x)`, b) copy over `s` and c) copy over `x`. Which is why it has that complexity.

If the loop used `append` (or `strings.Builder)`, the function would be `O(n•log(n))`, as `append` has amortized constant cost (i.e. you only have to allocate+copy, if the appended thing doesn't fit in the extra capacity reserved).

But string concatenation doesn't have extra capacity - it can't, because otherwise adding two different things to a single string would clobber each other (just like `append` does). So this isn't an "implementation inefficiency" either (well, a sufficiently clever compiler could recognize the loop pattern and optimize it).

**Comment by mvdan** [comment] 2023-03-11 16:58
Closing per the above.

**Closed by mvdan** 2023-03-11 16:58 UTC
Labels: website

**Comment by mkraft** [comment] 2023-03-11 19:24
@Merovius Thank you, I didn't realize that `str += fmt.Sprint(elem)` was `O(m)`. However, the sorting only happens once, so why multiply it by `n` to get `O(n*(log(n)+m))`? Isn't the complexity just `O(n*m)`?

**Comment by Neurostep** [comment] 2023-03-11 20:20
@mkraft sorting in O(n*log n), string concatenation is O(n*m). O(n*log n) + O(n*m) = O(n*(log n + m))

**Comment by Merovius** [comment] 2023-03-11 20:30
@mkraft In part, the issue is that I got confused. The cost is (where `n` is the number of elements, `k` is the maximum length of the strings in the list):

1. `O(n)` for copying (you only copy string header, which is `O(1)`, but you copy `n` of them)
2. `O(n•log(n)•k)` for sorting (you have `O(n•log(n))` string comparisons to sort each takes `O(k)` time)
3. `O(n²•k)` for the looped concatenation (see below).

Part of my confusion was that `k`-factor (I think the `m` I used above isn't helpful). The justification for `O(n²k)` is that `s+=x` is (as I said above) `O(len(s)+len(x))` - and `s` grows successively. So the first loop run is `O(len(s[0]))`, the second is `O(len(s[0])+len(s[1]))`, the third is `O(len(s[0])+len(s[1])+len(s[2])` and so on. `s[i]≤k`, so you get for the entire loop

`O(k+2k+…+n•k) = O(k•(1+2+…+n)) = O(k•n•(n+1)/2) = O(k•n²)`

So, for the entire function, you get `O(n+n•log(n)•k+n²•k)`. You are correct that, asymptotically, `log(n)≤n`, so this simplifies to `O(n²•k)`. I included the `log(n)` for taste, but it indeed doesn't matter for the complexity class.

Anyways, algorithmic complexity is kind of confusing to get right, sometimes. But really, the relevant factor is that every time you go through the loop, you have to re-do all the copying you already did in the past. That's where the quadratic factor comes from.

**Comment by mkraft** [comment] 2023-03-11 21:48
I'm wrapping by head around calculating the cost of the loop part. 

```go
for i, elem := range s {
    if i > 0 {
        str += " "
    }
    str += fmt.Sprint(elem)
}
```

Is it creating a fresh string upon each `+=`? If so, is this the correct cost of the loop if `s` is `"abc"` and `str` starts as `"["`?

```
str starts as "["

loop i = 0
    copy "a" to str in 2 steps; str is now "[b"
loop i = 1
    copy " " to str in 3 steps; str is now "[a "
    copy "b" to str in 4 steps; str is now "[a b"
loop i = 2
    copy " " to str in 5 steps; str is now "[a b "
    copy "c" to str in 6 steps; str is now "[a b c"

str ends as "[a b c"
```
total steps = 6 + 5 + 4 + 3 + 2 = 20

**Comment by Merovius** [comment] 2023-03-12 05:30
That seems correct.

I suggest moving any further questions or discussions to a more appropriate forum, e.g. [reddit](https://www.reddit.com/r/golang/), [golang-nuts](https://groups.google.com/g/golang-nuts) or [slack](https://gophers.slack.com/messages/general/). The issue tracker is not really well-suited or intended for this.
