### ISSUE TITLE
proposal: "go clean -modcache name" to remove single entity "name" from cache

### ISSUE THREAD

**Issue by awmorgan** [golang/go#44989] opened 2021-03-13 16:19 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/billmorgan/Library/Caches/go-build"
GOENV="/Users/billmorgan/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/billmorgan/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/billmorgan/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/billmorgan/gopl.io/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rp/fpc8t1293dn1r6jycrqn0hlw0000gn/T/go-build3348279230=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
Want to have a way to remove a single entity from the mod cache without deleting everything.

### What did you expect to see?
Option for go clean -modcache name that would delete name from the modcache.

### What did you see instead?
Option doesn't exist.

**Comment by tmthrgd** [comment] 2021-03-13 16:40
This is a duplicate of #32976.

**Comment by seankhliao** [comment] 2021-03-13 18:16
Duplicate of #32976

**Closed by seankhliao** 2021-03-13 18:16 UTC
Labels: Proposal
