### ISSUE TITLE
runtime: access violation during cgo call in github.com/mattn/go-sqlite3 on windows 7 64-bit

### ISSUE THREAD

**Issue by azdagron** [golang/go#9356] opened 2014-12-16 22:39 UTC
OS: Windows 7 64-bit
GCC version: gcc (x86_64-posix-seh-rev1, Built by MinGW-W64 project) 4.9.1
Go version: 1.4 (but also happens on 1.2+, didn't check < 1.2)

Description:
when the below program is compiled and run, the go program either panics or crashes outright.

We did some spelunking and from what we can tell, the crash happens when sqlite3 tries to call a kernel32.dll function from its aSyscall array. The function pointer is supposed to point to an import jump table, but instead points to a page close to the jump table that has some garbage in it.  Sampling other function pointers in the aSyscall array show they properly go the the import jump table.

We've used github.com/mattn/go-sqlite3 for quite a while with no issues.  We made some unrelated changes and recompiled our application and suddenly hit the issue.  Recompiling the program without the changes stopped triggering the bug, but once we found the issue we've been able to hit it with smaller programs (see the program below)

We suspect a linker issue, which is why we reported it here.

Repro instructions:
1) go get github.com/mattn/go-sqlite3
2) compile the following go program:
```
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/mattn/go-sqlite3"
)

func main() {
	db, err := sql.Open("sqlite3", "foo.db")
	if err != nil {
		fmt.Printf("unable to open: %s", err)
		return
	}
	rows, err := db.Query(".tables;")
	if err == nil {
		rows.Close()
	}
	db.Close()
}
```

An example of the output:
```
Exception 0xc0000005 0x8 0x646138 0x646138
PC=0x646138
signal arrived during cgo execution

github.com/mattn/go-sqlite3._Cfunc_sqlite3_close_v2(0x8966b8, 0xc000000000)
        github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:182 +0x4a
github.com/mattn/go-sqlite3.(*SQLiteConn).Close(0xc08204a018, 0x0, 0x0)
        c:/work/repro/src/github.com/mattn/go-sqlite3/sqlite3.go:320 +0x44
database/sql.(*driverConn).finalClose(0xc08200e1e0, 0x0, 0x0)
        c:/go/src/database/sql/sql.go:322 +0x125
database/sql.finalCloser.(database/sql.finalClose)┬╖fm(0x0, 0x0)
        c:/go/src/database/sql/sql.go:410 +0x52
database/sql.(*DB).Close(0xc082032000, 0x0, 0x0)
        c:/go/src/database/sql/sql.go:493 +0x3c2
main.main()
        c:/work/repro/src/repro/main.go:15 +0xdd

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1
rax     0x0
rbx     0x3
rcx     0x78
rdx     0x0
rdi     0x896ba8
rsi     0x897560
rbp     0x896970
rsp     0x22fce8
r8      0x5db0c0
r9      0x896ba8
r10     0x18
r11     0x5754e0
r12     0x0
r13     0x0
r14     0x0
r15     0x0
rip     0x646138
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by alexbrainman** [comment] 2015-02-24 04:30
Please check this change https://go-review.googlesource.com/5711 to see if it fixes your problem.

Alex

**Comment by mattn** [comment] 2015-02-24 05:43
I'll try this.

**Comment by mattn** [comment] 2015-02-24 05:49
Seems not fixed.

```
Exception 0xc0000005 0x0 0xffffffff 0x6e70dd
PC=0x6e70dd
signal arrived during cgo execution

github.com/mattn/go-sqlite3._Cfunc_sqlite3_close_v2(0xa63a00, 0x0)
	github.com/mattn/go-sqlite3/_test/_obj_test/_cgo_gotypes.go:248 +0x3a
github.com/mattn/go-sqlite3.(*SQLiteConn).Close(0x118a4290, 0x0, 0x0)
	c:/dev/go/src/github.com/mattn/go-sqlite3/sqlite3.go:318 +0x34
database/sql.(*driverConn).finalClose(0x118863f0, 0x0, 0x0)
	C:/go/src/database/sql/sql.go:327 +0xda
database/sql.(finalCloser).(database/sql.finalClose)-fm(0x0, 0x0)
	C:/go/src/database/sql/sql.go:416 +0x40
database/sql.(*DB).Close(0x1188a1e0, 0x0, 0x0)
	C:/go/src/database/sql/sql.go:499 +0x2c4
github.com/mattn/go-sqlite3.TestCorruptDbErrors(0x1188a180)
	c:/dev/go/src/github.com/mattn/go-sqlite3/error_test.go:50 +0x572
testing.tRunner(0x1188a180, 0x6f9c6c)
	C:/go/src/testing/testing.go:448 +0xa0
created by testing.RunTests
	C:/go/src/testing/testing.go:556 +0x848

goroutine 1 [chan receive]:
testing.RunTests(0x666560, 0x6f9c60, 0x18, 0x18, 0x70fd01)
	C:/go/src/testing/testing.go:557 +0x87a
testing.(*M).Run(0x118862d0, 0x70fae0)
	C:/go/src/testing/testing.go:486 +0x6b
main.main()
	github.com/mattn/go-sqlite3/_test/_testmain.go:100 +0x177

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	c:/go/src/runtime/asm_386.s:2435 +0x1

goroutine 6 [runnable]:
database/sql.(*DB).connectionOpener(0x1188a1e0)
	C:/go/src/database/sql/sql.go:594
created by database/sql.Open
	C:/go/src/database/sql/sql.go:458 +0x271
eax     0x84
ebx     0x3
ecx     0x67615f
edx     0x0
edi     0xa63c88
esi     0xa645c8
ebp     0x12fdd8
esp     0x12fdbc
eip     0x6e70dd
eflags  0x10296
cs      0x1b
fs      0x3b
gs      0x0
```

**Comment by denji** [comment] 2015-02-24 16:06
@mattn This works fine on cgo and gccgo https://github.com/mxk/go-sqlite

**Comment by alexbrainman** [comment] 2015-02-25 01:14
@mattn it works for me.

I applied my change with "git fetch https://go.googlesource.com/go refs/changes/11/5711/1 && git checkout FETCH_HEAD" command. Built Go.

I use gcc (GCC) 4.9.1.

I use beeda4c31194f4cdb15eb89d2f2b4be4474371c4 version of github.com/mattn/go-sqlite3.

I use this http://play.golang.org/p/8govbvHdB2 test program (as per https://github.com/golang/go/issues/9356#issuecomment-67351994).

This is what test program prints:
```
C:\go\path\src\issue9356>go run main.go
exec: <nil>
done.
```
But if I change to current Go tip (9b3ccc082f6bda01727fc98096f7d197bba830db). Same program prints:
```
C:\go\path\src\issue9356>go run main.go
Exception 0xc0000005 0x8 0x66d078 0x66d078
PC=0x66d078
signal arrived during cgo execution

github.com/mattn/go-sqlite3._Cfunc_sqlite3_exec(0x3761b8, 0x376ef0, 0x0, 0x0, 0x0, 0x0)
        github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:374 +0x43
github.com/mattn/go-sqlite3.(*SQLiteConn).exec(0xc082020020, 0x5ed8b0, 0x36, 0x0, 0x0, 0x0, 0x0)
        c:/go/path/src/github.com/mattn/go-sqlite3/sqlite3.go:227 +0xc6
github.com/mattn/go-sqlite3.(*SQLiteConn).Exec(0xc082020020, 0x5ed8b0, 0x36, 0x6a4ab8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/path/src/github.com/mattn/go-sqlite3/sqlite3.go:166 +0x86
database/sql.(*DB).exec(0xc082050000, 0x5ed8b0, 0x36, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/root/src/database/sql/sql.go:868 +0x2bd
database/sql.(*DB).Exec(0xc082050000, 0x5ed8b0, 0x36, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/root/src/database/sql/sql.go:845 +0xc3
main.main()
        C:/go/path/src/issue9356/main.go:28 +0x19d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/root/src/runtime/asm_amd64.s:2470 +0x1

goroutine 4 [runnable]:
database/sql.(*DB).connectionOpener(0xc082050000)
        c:/go/root/src/database/sql/sql.go:594
created by database/sql.Open
        c:/go/root/src/database/sql/sql.go:458 +0x33e
rax     0x0
rbx     0x22f63c
rcx     0x22f63c
rdi     0x22f640
rsi     0x22f638
rbp     0x22f63c
rsp     0x22f5b8
r8      0x76dd0000
r9      0x1b6
r10     0xc0000034
r11     0x8b0158
r12     0x22f638
r13     0x0
r14     0x3772a9
r15     0x22f6f4
rip     0x66d078
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b
exit status 2
```
(make sure you re-install github.com/mattn/go-sqlite3).

Please, provide instructions for me to reproduce what you see there. Thank you.

Alex

**Comment by denji** [comment] 2015-02-25 01:51
On the basis of gcc5 (`gccgo`) work fine refinished.
Problem reproduced on `cgo` (I can't build native code on unix systems that do not use gcc, you might have code sqlite-amalgamation-bound gcc/llvm).

**Comment by alexbrainman** [comment] 2015-02-25 02:21
@denji if you talking to me, I don't understand what you are saying.

Alex

**Comment by mattn** [comment] 2015-02-25 02:34
@alexbrainman did you test with https://github.com/mattn/go-sqlite3/commit/d369cbb7d42232f785f51b3ef4c8b994dae83486 ?

**Comment by alexbrainman** [comment] 2015-02-25 02:52
I didn't test against  mattn/go-sqlite3@d369cbb. Should I? I thought we had conversation about beeda4c31194f4cdb15eb89d2f2b4be4474371c4  all along. You don't expect me to debug / test every change of mattn/go-sqlite3. Do you? Perhaps you should see what has changed between these two version, and decide for yourself what to do.

**Comment by mattn** [comment] 2015-02-25 03:08
As I said in [above](https://github.com/golang/go/issues/9356#issuecomment-67606826), I reverted the commit. This behavior doesn't be reproduced with older amalgamated code.

https://github.com/mattn/go-sqlite3/commit/d369cbb is commit that be possible to reproduce on my environment.

**Comment by alexbrainman** [comment] 2015-02-25 03:33
I tested mattn/go-sqlite3@d369cbb now. It works fine as I have described up above.

Alex

**Comment by mattn** [comment] 2015-02-26 00:05
I could reproduce this on Win7 32bit

```
Exception 0xc0000005 0x0 0xffffffff 0x6cb0dd
PC=0x6cb0dd
signal arrived during cgo execution

github.com/mattn/go-sqlite3._Cfunc_sqlite3_close_v2(0x973a00, 0x0)
        github.com/mattn/go-sqlite3/_test/_obj_test/_cgo_gotypes.go:248 +0x3a
github.com/mattn/go-sqlite3.(*SQLiteConn).Close(0x117b4290, 0x0, 0x0)
        c:/dev/go/src/github.com/mattn/go-sqlite3/sqlite3.go:320 +0x34
database/sql.(*driverConn).finalClose(0x117963f0, 0x0, 0x0)
        c:/go/src/database/sql/sql.go:327 +0xda
database/sql.(finalCloser).(database/sql.finalClose)-fm(0x0, 0x0)
        c:/go/src/database/sql/sql.go:416 +0x40
database/sql.(*DB).Close(0x1179a1e0, 0x0, 0x0)
        c:/go/src/database/sql/sql.go:499 +0x2c4
github.com/mattn/go-sqlite3.TestCorruptDbErrors(0x1179a180)
        c:/dev/go/src/github.com/mattn/go-sqlite3/error_test.go:50 +0x572
testing.tRunner(0x1179a180, 0x6dda6c)
        c:/go/src/testing/testing.go:448 +0xa0
created by testing.RunTests
        c:/go/src/testing/testing.go:556 +0x848

goroutine 1 [chan receive]:
testing.RunTests(0x64cc3c, 0x6dda60, 0x16, 0x16, 0x6f3b01)
        c:/go/src/testing/testing.go:557 +0x87a
testing.(*M).Run(0x117962d0, 0x6f38e0)
        c:/go/src/testing/testing.go:486 +0x6b
main.main()
        github.com/mattn/go-sqlite3/_test/_testmain.go:96 +0x177

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_386.s:2435 +0x1
eax     0x90
ebx     0x3
ecx     0x0
edx     0x0
edi     0x9745c8
esi     0x9745c8
ebp     0x12fdd8
esp     0x12fdbc
eip     0x6cb0dd
eflags  0x10286
cs      0x1b
fs      0x3b
gs      0x0
exit status 2
FAIL    github.com/mattn/go-sqlite3     0.960s
```

**Comment by alexbrainman** [comment] 2015-02-26 05:10
Running http://play.golang.org/p/8govbvHdB2 against d369cbb does not crashes for me on windows-386 even without my change. I use gcc (GCC) 4.8.1 there.

Alex

**Comment by denji** [comment] 2015-02-26 05:21
Here are the problems that I know of in GCC 4.8/4.9.x:
1.) https://kb.isc.org/article/AA-01167
2.) http://gcc.gnu.org/bugzilla/show_bug.cgi?id=56746 and http://gcc.gnu.org/bugzilla/show_bug.cgi?id=53525 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=43052

> 4.8+ CFLAGS=-ftrack-macro-expansion=0 -fno-builtin-memcmp
> 4.9+ CFLAGS=-fno-delete-null-pointer-checks

Can solve the problem or search dereferencing pointer in the code.

**Comment by mattn** [comment] 2015-02-26 10:57
I'm using gcc 4.8.2, so added `-ftrack-macro-expansion=0 -fno-builtin-memcmp` into sqlite3_windows.go, but not solved unfortunatelly. :cry:

**Comment by azdagron** [comment] 2015-02-26 14:57
This changeset fixes the bug with my original repro configuration.

**Comment by minux** [comment] 2015-03-24 05:37
Should be fixed by external linking support, #4069.

**Closed by minux** 2015-03-24 05:37 UTC
Labels: cgo, os-windows, repo-main

**Comment by azdagron** [comment] 2015-11-06 17:51
So this didn't make it into Go1.5 and the CL references 1.6 but doesn't seem to have been merged. Anybody know the status of this?

**Comment by ianlancetaylor** [comment] 2015-11-06 18:19
Somebody needs to review the CL or write a new one.  Alex and I were unable to come to agreement on it.

**Comment by alexbrainman** [comment] 2015-11-06 21:38
What @minux said. go1.5 uses external linker (mingw) to build cgo programs, so you should not see your problem now. The broken code in Go linker still remain, but it is not used any more. I hope it explains the situation.

Alex
