### ISSUE TITLE
proposal: iter: Add Contains

### ISSUE THREAD

**Issue by adamroyjones** [golang/go#68945] opened 2024-08-19 12:53 UTC
### Proposal Details

I propose a tiny, but I think helpful, addition to the iter package.

```go
func Contains[K comparable](seq iter.Seq[K], val K) bool {
	for k := range seq {
		if k == val {
			return true
		}
	}
	return false
}
```

This avoids the need to collect the iter.Seq[K] into a slice.

This could be extended to ContainsFunc.

It could also be extended to Contains2 and Contains2Func, but that may be a bit more strained.

**Comment by seankhliao** [comment] 2024-08-19 13:23
Duplicate of #67453

**Closed by seankhliao** 2024-08-19 13:23 UTC
Labels: Proposal
