### ISSUE TITLE
cmd/compile: DCE before inlining does not remove dead `if`s

### ISSUE THREAD

**Issue by CAFxX** [golang/go#29189] opened 2018-12-12 11:34 UTC
DCE performed before inlining seems to eliminate the body of `if`s where the condition can be proven to always evaluate to `false`, but fails to eliminate the if statement and the condition themselves. So, for example, the following code:
```
// code before if 
if condition_known_to_be_false {
  // code inside if
}
// code after if
```
that should be DCEd (before inlining) to:
```
// code before if
// (if statement has been completely removed)
// code after if
```
but currently DCE transforms it to:
```
// code before if
if condition_known_to_be_false { /* empty body */ }
// code after if
```

Found by going over the output of `GO_GCFLAGS=-m ./make.bash` (the following is just a sample, see https://github.com/golang/go/issues/8421#issuecomment-445734113 for details):

<pre>
src/math/bits/bits.go:283:6: can inline Len as: func(uint) int { <b>if UintSize == 32 {  }</b>; return Len64(uint64(x)) }
src/runtime/cgocall.go:176:14: inlining call to dolockOSThread func() { <b>if GOARCH == "wasm" {  }</b>; _g_ := getg(); _g_.m.lockedg.set(_g_); _g_.lockedm.set(_g_.m) }
src/runtime/stack.go:1277:24: inlining call to stackmapdata func(*stackmap, int32) bitvector { <b>if stackDebug > 0 {  }</b>; return bitvector literal }
src/runtime/malloc.go:1105:6: can inline nextSample as: func() int32 { <b>if GOOS == "plan9" {  }</b>; return fastexprand(MemProfileRate) }
src/go/token/position.go:452:15: inlining call to sync.(*RWMutex).RLock method(*sync.RWMutex) func() { <b>if bool(false) {  }</b>; if atomic.AddInt32(&sync.rw.readerCount, int32(1)) < int32(0) { sync.runtime_SemacquireMutex(&sync.rw.readerSem, bool(false)) }; <b>if bool(false) {  }</b> }
src/runtime/type.go:269:20: inlining call to reflectOffsUnlock func() { <b>if raceenabled {  }</b>; unlock(&reflectOffs.lock) }
</pre>

This is a problem because part of the inlining budget will be consumed by the vestigial `if`s. If DCE before inlining completely removed those `if`s more functions would likely become candidate for inlining.

Likely related to #23521 and possibly to #29095.

**Comment by mvdan** [comment] 2018-12-12 14:57
Are you positive that the `inlining call to` messages show you the nodes as they are being inlined? For example, perhaps it's showing you the original source code minus comments.

I haven't actually checked; I'm simply pointing out that this might be an issue with the `-m` messages and not the DCE or inline passes.

**Comment by josharian** [comment] 2018-12-12 17:19
On my phone but the condition is probably being printed from n.Orig. But there are still extraneous OIF and OLITERAL (“if” and “true”) nodes there.

**Comment by mdempsky** [comment] 2019-04-22 20:03
The inliner has logic for making sure constant if expressions don't cost anything extra:

https://github.com/golang/go/blob/master/src/cmd/compile/internal/gc/inl.go#L396-L401

The diagnostic message might be a little confusing, but I don't think it should be affecting the output binaries at all.

**Comment by mdempsky** [comment] 2019-04-22 20:07
Closing because I think this is working as intended. Please let us know to reopen though if you have evidence that a constant if statement is actually affecting inlining (e.g., either it's affecting budgeting, or somehow affecting the resulting assembly negatively).

**Closed by mdempsky** 2019-04-22 20:07 UTC
Labels: NeedsInvestigation, Performance
