### ISSUE TITLE
Playground produces flaky results when using net/http/httptest.NewServer

### ISSUE THREAD

**Issue by mohira** [golang/go#47936] opened 2021-08-24 13:30 UTC
### What version of Go are you using (`go version`)?
Go1.17(Playground)

```
The playground uses the latest stable release of Go.
The current version is go1.17.
```

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
Playground

### What did you do?

Playground link is here. https://play.golang.org/p/_jGQZY5hldr

```go
package main

import (
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
)

func main() {
	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintln(w, "hello")
	}))

	defer s.Close()
	cli := s.Client()
	res, err := cli.Get(s.URL)

	if err != nil {
		panic(err)
	}

	defer res.Body.Close()
	io.Copy(os.Stdout, res.Body)
}
```

### What did you expect to see?
Playground displays this message.

```
Hello, world!
```

### What did you see instead?
The code exhibits both a success and a error result. It was flaky.
(As we will see later, this was not reproduced in another environment)

#### success case
Playground displayed this message in success case.

```
Hello, world!
```

#### error case
Playground displayed this messages in error case.

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc000122280, 0xc00001a240, {{}, 0x0, {0xc000016090, 0x4}, {0xc0000182e0, 0xf}, 0x0})
	/usr/local/go-faketime/src/net/http/transport.go:1372 +0x5d2
net/http.(*Transport).roundTrip(0xc000122280, 0xc00014e000)
	/usr/local/go-faketime/src/net/http/transport.go:581 +0x774
net/http.(*Transport).RoundTrip(0x30, 0x6e5ca0)
	/usr/local/go-faketime/src/net/http/roundtrip.go:18 +0x19
net/http.send(0xc00014e000, {0x6e5ca0, 0xc000122280}, {0x681800, 0x1, 0x0})
	/usr/local/go-faketime/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc000012d50, 0xc00014e000, {0xc00014e000, 0x24, 0x0})
	/usr/local/go-faketime/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc000012d50, 0xc00014e000)
	/usr/local/go-faketime/src/net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
	/usr/local/go-faketime/src/net/http/client.go:593
net/http.(*Client).Get(0x6e6460, {0xc000016090, 0x7efe7b97c108})
	/usr/local/go-faketime/src/net/http/client.go:480 +0x6a
main.main()
	/tmp/sandbox3023192886/prog.go:18 +0x85

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x7efe54e84eb8, 0x72)
	/usr/local/go-faketime/src/runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc000134000, 0x4, 0x0)
	/usr/local/go-faketime/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go-faketime/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000134000)
	/usr/local/go-faketime/src/internal/poll/fd_unix.go:402 +0x22c
net.(*netFD).accept(0xc000134000)
	/usr/local/go-faketime/src/net/fd_unix.go:173 +0x35
net.(*TCPListener).accept(0xc00000c0c0)
	/usr/local/go-faketime/src/net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).Accept(0xc00000c0c0)
	/usr/local/go-faketime/src/net/tcpsock.go:262 +0x3d
net/http.(*Server).Serve(0xc00014a000, {0x6eb570, 0xc00000c0c0})
	/usr/local/go-faketime/src/net/http/server.go:3001 +0x394
net/http/httptest.(*Server).goServe.func1()
	/usr/local/go-faketime/src/net/http/httptest/server.go:308 +0x6a
created by net/http/httptest.(*Server).goServe
	/usr/local/go-faketime/src/net/http/httptest/server.go:306 +0x6f

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x7efe54e84dd0, 0x77)
	/usr/local/go-faketime/src/runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc000134100, 0x68ac5f, 0x0)
	/usr/local/go-faketime/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitWrite(...)
	/usr/local/go-faketime/src/internal/poll/fd_poll_runtime.go:93
internal/poll.(*FD).WaitWrite(...)
	/usr/local/go-faketime/src/internal/poll/fd_unix.go:529
net.(*netFD).connect(0xc000134100, {0x6ec570, 0xc000018030}, {0xc00008d470, 0x40c974}, {0x6e6020, 0xc000136060})
	/usr/local/go-faketime/src/net/fd_unix.go:142 +0x717
net.(*netFD).dial(0xc000134100, {0x6ec570, 0xc000018030}, {0x6ee4e8, 0x0}, {0x6ee4e8, 0xc000012f90}, 0xc000068660)
	/usr/local/go-faketime/src/net/sock_posix.go:150 +0x379
net.socket({0x6ec570, 0xc000018030}, {0x68ac5f, 0x3}, 0x2, 0x1, 0x0, 0x60, {0x6ee4e8, 0x0}, ...)
	/usr/local/go-faketime/src/net/sock_posix.go:71 +0x2a5
net.internetSocket({0x6ec570, 0xc000018030}, {0x68ac5f, 0x3}, {0x6ee4e8, 0x0}, {0x6ee4e8, 0xc000012f90}, 0xc0000182f0, 0x0, ...)
	/usr/local/go-faketime/src/net/ipsock_posix.go:142 +0xf8
net.(*sysDialer).doDialTCP(0xc000134080, {0x6ec570, 0xc000018030}, 0x0, 0x9)
	/usr/local/go-faketime/src/net/tcpsock_posix.go:66 +0xa5
net.(*sysDialer).dialTCP(0x1, {0x6ec570, 0xc000018030}, 0xc000068758, 0x6045de)
	/usr/local/go-faketime/src/net/tcpsock_posix.go:62 +0x59
net.(*sysDialer).dialSingle(0xc000134080, {0x6ec570, 0xc000018030}, {0x6eaa38, 0xc000012f90})
	/usr/local/go-faketime/src/net/dial.go:583 +0x28b
net.(*sysDialer).dialSerial(0xc000134080, {0x6ec570, 0xc000018030}, {0xc000010cb0, 0x1, 0x68adc1})
	/usr/local/go-faketime/src/net/dial.go:551 +0x312
net.(*Dialer).DialContext(0x890fa0, {0x6ec570, 0xc000018030}, {0x68ac5f, 0xc000068a40}, {0xc0000182e0, 0x118})
	/usr/local/go-faketime/src/net/dial.go:428 +0x736
net/http.(*Transport).dial(0xc000122280, {0x6ec570, 0xc000018030}, {0x68ac5f, 0x30}, {0xc0000182e0, 0x30})
	/usr/local/go-faketime/src/net/http/transport.go:1175 +0xb8
net/http.(*Transport).dialConn(0xc000122280, {0x6ec570, 0xc000018030}, {{}, 0x0, {0xc000016090, 0x4}, {0xc0000182e0, 0xf}, 0x0})
	/usr/local/go-faketime/src/net/http/transport.go:1604 +0x845
net/http.(*Transport).dialConnFor(0x0, 0xc0001142c0)
	/usr/local/go-faketime/src/net/http/transport.go:1446 +0xb0
created by net/http.(*Transport).queueForDial
	/usr/local/go-faketime/src/net/http/transport.go:1415 +0x3d7

Program exited: status 2.
```

### This issue didn't reproduce my local environment
In my local environment, however, The same error was NOT reproduced.

The environment is below.

```
$ go version
go version go1.17 darwin/amd64
```

```
$ go env
GOARCH="amd64"
GOOS="darwin"
GOVERSION="go1.17"
```

Since there were two facts, I think it is because of playground that it happens.

First, `go-faketime` is obviously related the error.
Second, this issue didn't happen in the local environment.

**Comment by seankhliao** [comment] 2021-08-24 14:16
Duplicate of #45855

**Closed by seankhliao** 2021-08-24 14:16 UTC
