### ISSUE TITLE
x/vgo: fix installation instructions on README

### ISSUE THREAD

**Issue by tvmaly** [golang/go#25783] opened 2018-06-07 11:59 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
10.2

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
OSX 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

### What did you do?

go get -u golang.org/x/vgo .

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
 installation of vgo

### What did you see instead?

It hung

### Solution

change documentation to 

go get -u github.com/golang/vgo

**Comment by myitcv** [comment] 2018-06-07 12:09
Please can you retry with:

```
go get -u -v golang.org/x/vgo
```

and post the output? 

Ideally if you could try the make-shift program in https://github.com/golang/go/issues/25565#issuecomment-393046075 that would be more useful still because it will give more granular timings.

Possibly related to https://github.com/golang/go/issues/25565

**Comment by tvmaly** [comment] 2018-06-14 11:37
go get -u -v golang.org/x/vgo
Fetching https://golang.org/x/vgo?go-get=1
Parsing meta tags from https://golang.org/x/vgo?go-get=1 (status code 200)
get "golang.org/x/vgo": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo?go-get=1
golang.org/x/vgo (download)
Fetching https://golang.org/x/vgo/vendor/cmd/go?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go?go-get=1
get "golang.org/x/vgo/vendor/cmd/go": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo?go-get=1
Parsing meta tags from https://golang.org/x/vgo?go-get=1 (status code 200)
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/base?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/base?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/base": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/base?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/base": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/cfg?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/cfg?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/cfg": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/cfg?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/cfg": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/str?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/str?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/str": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/str?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/str": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/bug?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/bug?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/bug": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/bug?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/bug": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/envcmd?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/envcmd?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/envcmd": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/envcmd?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/envcmd": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/cache?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/cache?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/cache": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/cache?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/cache": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/load?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/load?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/load": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/load?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/load": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/modinfo?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/modinfo?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/modinfo": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/modinfo?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/modinfo": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/search?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/search?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/search": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/search?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/search": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/vgo?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/vgo?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/vgo": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/vgo?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/vgo": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/dirhash?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/dirhash?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/dirhash": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/dirhash?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/dirhash": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/imports?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/imports?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/imports": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/imports?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/imports": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/modconv?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/modconv?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/modconv": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/modconv?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/modconv": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/module?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/module?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/module": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/module?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/module": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/semver?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/semver?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/semver": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/semver?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/semver": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/modfetch": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/modfetch": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch/bitbucket?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch/bitbucket?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/modfetch/bitbucket": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch/bitbucket?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/modfetch/bitbucket": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch/codehost?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch/codehost?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/modfetch/codehost": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch/codehost?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/modfetch/codehost": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch/gitrepo?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch/gitrepo?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/modfetch/gitrepo": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch/gitrepo?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/modfetch/gitrepo": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch/github?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch/github?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/modfetch/github": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch/github?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/modfetch/github": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch/googlesource?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch/googlesource?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/modfetch/googlesource": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/modfetch/googlesource?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/modfetch/googlesource": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/modfile?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/modfile?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/modfile": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/modfile?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/modfile": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/web2?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/web2?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/web2": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/web2?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/web2": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/mvs?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/mvs?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/mvs": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/mvs?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/mvs": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/work?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/work?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/work": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/work?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/work": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/internal/buildid?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/internal/buildid?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/internal/buildid": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/internal/buildid?go-get=1
get "golang.org/x/vgo/vendor/cmd/internal/buildid": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/web?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/web?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/web": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/web?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/web": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/internal/browser?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/internal/browser?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/internal/browser": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/internal/browser?go-get=1
get "golang.org/x/vgo/vendor/cmd/internal/browser": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/clean?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/clean?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/clean": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/clean?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/clean": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/doc?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/doc?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/doc": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/doc?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/doc": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/fix?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/fix?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/fix": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/fix?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/fix": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/fmtcmd?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/fmtcmd?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/fmtcmd": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/fmtcmd?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/fmtcmd": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/generate?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/generate?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/generate": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/generate?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/generate": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/get?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/get?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/get": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/get?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/get": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/internal/singleflight?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/internal/singleflight?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/internal/singleflight": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/internal/singleflight?go-get=1
get "golang.org/x/vgo/vendor/internal/singleflight": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/help?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/help?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/help": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/help?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/help": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/list?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/list?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/list": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/list?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/list": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/run?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/run?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/run": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/run?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/run": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/test?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/test?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/test": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/test?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/test": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/cmdflag?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/cmdflag?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/cmdflag": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/cmdflag?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/cmdflag": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/internal/test2json?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/internal/test2json?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/internal/test2json": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/internal/test2json?go-get=1
get "golang.org/x/vgo/vendor/cmd/internal/test2json": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/tool?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/tool?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/tool": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/tool?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/tool": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/version?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/version?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/version": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/version?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/version": verifying non-authoritative meta tag
Fetching https://golang.org/x/vgo/vendor/cmd/go/internal/vet?go-get=1
Parsing meta tags from https://golang.org/x/vgo/vendor/cmd/go/internal/vet?go-get=1 (status code 200)
get "golang.org/x/vgo/vendor/cmd/go/internal/vet": found meta tag get.metaImport{Prefix:"golang.org/x/vgo", VCS:"git", RepoRoot:"https://go.googlesource.com/vgo"} at https://golang.org/x/vgo/vendor/cmd/go/internal/vet?go-get=1
get "golang.org/x/vgo/vendor/cmd/go/internal/vet": verifying non-authoritative meta tag
golang.org/x/vgo/vendor/cmd/go/internal/modinfo
golang.org/x/vgo/vendor/cmd/go/internal/semver
golang.org/x/vgo/vendor/internal/singleflight
golang.org/x/vgo/vendor/cmd/go/internal/str
golang.org/x/vgo/vendor/cmd/go/internal/module
golang.org/x/vgo/vendor/cmd/go/internal/cache
golang.org/x/vgo/vendor/cmd/go/internal/dirhash
golang.org/x/vgo/vendor/cmd/go/internal/cfg
golang.org/x/vgo/vendor/cmd/internal/browser
golang.org/x/vgo/vendor/cmd/internal/test2json
golang.org/x/vgo/vendor/cmd/internal/buildid
golang.org/x/vgo/vendor/cmd/go/internal/modconv
golang.org/x/vgo/vendor/cmd/go/internal/modfile
golang.org/x/vgo/vendor/cmd/go/internal/mvs
golang.org/x/vgo/vendor/cmd/go/internal/base
golang.org/x/vgo/vendor/cmd/go/internal/imports
golang.org/x/vgo/vendor/cmd/go/internal/modfetch/codehost
golang.org/x/vgo/vendor/cmd/go/internal/web
golang.org/x/vgo/vendor/cmd/go/internal/modfetch/gitrepo
golang.org/x/vgo/vendor/cmd/go/internal/cmdflag
golang.org/x/vgo/vendor/cmd/go/internal/search
golang.org/x/vgo/vendor/cmd/go/internal/web2
golang.org/x/vgo/vendor/cmd/go/internal/doc
golang.org/x/vgo/vendor/cmd/go/internal/help
golang.org/x/vgo/vendor/cmd/go/internal/tool
golang.org/x/vgo/vendor/cmd/go/internal/modfetch/github
golang.org/x/vgo/vendor/cmd/go/internal/modfetch/googlesource
golang.org/x/vgo/vendor/cmd/go/internal/modfetch/bitbucket
golang.org/x/vgo/vendor/cmd/go/internal/modfetch
golang.org/x/vgo/vendor/cmd/go/internal/vgo
golang.org/x/vgo/vendor/cmd/go/internal/load
golang.org/x/vgo/vendor/cmd/go/internal/fix
golang.org/x/vgo/vendor/cmd/go/internal/fmtcmd
golang.org/x/vgo/vendor/cmd/go/internal/work
golang.org/x/vgo/vendor/cmd/go/internal/envcmd
golang.org/x/vgo/vendor/cmd/go/internal/version
golang.org/x/vgo/vendor/cmd/go/internal/generate
golang.org/x/vgo/vendor/cmd/go/internal/clean
golang.org/x/vgo/vendor/cmd/go/internal/list
golang.org/x/vgo/vendor/cmd/go/internal/get
golang.org/x/vgo/vendor/cmd/go/internal/run
golang.org/x/vgo/vendor/cmd/go/internal/test
golang.org/x/vgo/vendor/cmd/go/internal/vet
golang.org/x/vgo/vendor/cmd/go/internal/bug
golang.org/x/vgo/vendor/cmd/go
golang.org/x/vgo

**Comment by myitcv** [comment] 2018-06-14 11:48
That looks to have completed successfully. 

Does that command not return?

What is the output from:

```
$(go list -f "{{.Target}}" golang.org/x/vgo) help
```

**Comment by rsc** [comment] 2018-07-06 04:00
This is a duplicate of #25565 - I don't know the cause.
We definitely want to keep using "golang.org/x/vgo" not "github.com/golang/vgo", and  soon enough vgo will be just "go", so I will close this.

**Closed by rsc** 2018-07-06 04:00 UTC
Labels: Documentation, WaitingForInfo
