### ISSUE TITLE
encoding/json: MarshalJSON not called in value contexts for integer types

### ISSUE THREAD

**Issue by schani** [golang/go#23263] opened 2017-12-27 23:19 UTC
This behavior is counterintuitive and requires bookkeeping to figure out which types are in a value context under which circumstances.

### What version of Go are you using (`go version`)?

```
go version go1.9.2 darwin/amd64
```

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/schani/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n9/hkp85g8d1_ddvqjfd9b_2b1h0000gn/T/go-build054789224=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

https://play.golang.org/p/HuQg9qdj4HE

### What did you expect to see?

```
{"map":{"a":"string"},"direct":"string"}
{"map":{"a":"string"},"direct":"string"}
```

### What did you see instead?

```
{"map":{"a":0},"direct":0}
{"map":{"a":0},"direct":"string"}
```

**Comment by dsnet** [comment] 2017-12-27 23:54
The issue is that `MarshalJSON` is defined as a method on the pointer version of the integer. It should probably be the value receiver. Closing as duplicate of #22967

**Closed by dsnet** 2017-12-27 23:54 UTC

**Comment by bradfitz** [comment] 2017-12-28 01:46
Also not that elements in maps aren't addressable so any typical automatic T to *T receiver switch sugar doesn't happen since the map element can't have its pointer addr taken.
