### ISSUE TITLE
all.bash build go failed when GO111MODULE is 'on'

### ISSUE THREAD

**Issue by yougg** [golang/go#27069] opened 2018-08-18 06:46 UTC
### What version of Go are you using (`go version`)?

```bash
# the latest version of master branch
go version devel +714c141c4f Sat Aug 18 03:02:40 2018 +0000 linux/amd64
```

### Does this issue reproduce with the latest release?

```
no
```

### What operating system and processor architecture are you using (`go env`)?

```bash
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/usr/local/go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build732388308=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

```bash
# cd /usr/local/go/

# git branch
* master

# git pull --rebase
Already up to date.
Current branch master is up to date.

# git log | head -20
commit 714c141c4f2db626ea470a27cfd35f86b0c77c07
Author: Russ Cox <rsc@golang.org>
Date:   Fri Aug 17 21:10:19 2018 -0400

    cmd/go: update TestGoGetUpdateWithWildcard expected behavior

    If you run

            go get -u github.com/rsc/foo/bar...

    then the go get command has always worked hard to make sure
    that it applies the wildcard after downloading rsc/foo.
    (If it applied the wildcard only before downloading rsc/foo,
    it would match nothing if you had an empty GOPATH before,
    and you'd still have an empty afterward, which is clearly useless.)

    The goal has always been that if you run the same go get
    command twice, the second command doesn't find anything
    new to do.

# cd /usr/local/go/src/
# export GO111MODULE=on
# ./all.bash
Building Go cmd/dist using /usr/local/go1.10.2.
Building Go toolchain1 using /usr/local/go1.10.2.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
go: cannot determine module path for source directory /usr/local/go (outside GOPATH, no import comments)
go tool dist: FAILED: /usr/local/go/pkg/tool/linux_amd64/go_bootstrap install -gcflags=all= -ldflags=all= -i cmd/asm cmd/cgo cmd/compile cmd/link: exit status 1
```

### What did you expect to see?

```
Building Go cmd/dist using /usr/local/go1.10.2.
Building Go toolchain1 using /usr/local/go1.10.2.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/amd64.

##### Testing packages.
......
......
ALL TESTS PASSED
---
Installed Go for linux/amd64 in /usr/local/go
Installed commands in /usr/local/go/bin
```

### What did you see instead?

```bash
Building Go cmd/dist using /usr/local/go1.10.2.
Building Go toolchain1 using /usr/local/go1.10.2.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
go: cannot determine module path for source directory /usr/local/go (outside GOPATH, no import comments)
go tool dist: FAILED: /usr/local/go/pkg/tool/linux_amd64/go_bootstrap install -gcflags=all= -ldflags=all= -i cmd/asm cmd/cgo cmd/compile cmd/link: exit status 1
```

**Comment by agnivade** [comment] 2018-08-18 07:14
Duplicate of #26996

**Closed by agnivade** 2018-08-18 07:14 UTC
