### ISSUE TITLE
cmd/go: no Module information in list -e output after any error loading package

### ISSUE THREAD

**Issue by myitcv** [golang/go#44287] opened 2021-02-16 14:39 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +0cb3415154 Tue Feb 16 02:07:02 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/myitcv/gostuff/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel +0cb3415154 Tue Feb 16 02:07:02 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/tmp.MFFZzggPNu/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build741706514=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
go list -e -f {{.Module}}

-- blah.go --
package blah

import _ "embed"

//go:embed README.md
var readme string
-- go.mod --
module mod.com

go 1.16
```

### What did you expect to see?

```
mod.com
```

### What did you see instead?

```
<nil>
```

This has implications for users of `go list`, i.e. `go/packages`.

**Comment by jayconrod** [comment] 2021-02-19 16:37
In `cmd/go/internal/load.Package.load`, it looks like we don't populate the `Module` field if there was any error loading the package. For example, if a `blah.c` file is present but the package doesn't use cgo or swig, the `Error` field is populated but the `Module` field is not.

I don't think anything prevents us from populated the `Module` field here.

**Comment by siddhant-deepsource** [comment] 2021-02-19 20:32
Hey @jayconrod , I would like to help out to fix this issue. How should I proceed?

**Comment by sidntrivedi012** [comment] 2021-02-19 20:33
Hey @jayconrod , I would like to help out to fix this issue. How should I proceed? Thanks :)

**Comment by jayconrod** [comment] 2021-02-19 21:32
@sidntrivedi012 Your help is most welcome.

I think this can be fixed in pkg.go by moving [this block](https://github.com/golang/go/blob/9a99515c8f1febe39151a80b2088d0d6fdc55ca2/src/cmd/go/internal/load/pkg.go#L1911) up to [right after we push the import path on the stack](https://github.com/golang/go/blob/9a99515c8f1febe39151a80b2088d0d6fdc55ca2/src/cmd/go/internal/load/pkg.go#L1810).

Please make sure to add a regression test in src/cmd/go/testdata/script. There's a README there that explains the format.

**Comment by supriya-premkumar** [comment] 2021-02-27 18:46
I can take this one up if this in the backlog. @jayconrod  Please feel free to assign this one to me. 🙏🏽

**Comment by sidntrivedi012** [comment] 2021-02-27 19:26
Hey @supriya-premkumar , I got somewhat stuck in the weekdays so couldn't get the bandwidth to work on it. 

I am planning to write a patch for it in this weekend. Will surely comment here to assign it to you if I fail to triage it.

Thanks 😃

**Comment by supriya-premkumar** [comment] 2021-02-27 19:27
> Hey @supriya-premkumar , I got somewhat stuck in the weekdays so couldn't get the bandwidth to work on it.
> 
> I am planning to write a patch for it in this weekend. Will surely comment here to assign it to you if I fail to triage it.
> 
> Thanks 😃

No worries at all. Go for it!

**Closed** 2021-04-28 15:14 UTC
Labels: GoCommand, NeedsFix, help wanted
