### ISSUE TITLE
runtime/trace: TestTraceSymbolize failure on Windows

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#13116] opened 2015-10-31 23:20 UTC
According to build.golang.org, windows-386 is consistently failing with

addr2line: reading C:\Users\WINGOP~1\AppData\Local\Temp\go-build886867138\runtime\trace\_test\trace.test.exe: runtime.pclntab and runtime.epclntab symbols must be in the same section
--- FAIL: TestTraceSymbolize (0.21s)
	trace_stack_test.go:134: failed to symbolize trace: failed to read from addr2line: EOF
FAIL
FAIL	runtime/trace	1.958s

This first report was http://build.golang.org/log/ced968d0310b82a3ea7bdd092d249123efccc159 while testing https://golang.org/cl/16070.

**Comment by alexbrainman** [comment] 2015-11-01 04:53
I cannot reproduce it here. But I will keep trying.

Alex

**Comment by aclements** [comment] 2015-11-01 17:23
I can't imagine how that CL would have directly caused this. It seems more likely this is a compiler/linker bug that this CL happened to tickle. It looks like it resolved itself with the latest commit to master.

I tried to reproduce this on the gomotes, but wasn't able to. @adg, @bradfitz, are there differences between the windows-386-gce builder on the dashboard and the VM created by `gomote create windows-386-gce` that would cause a test that fails reliably on the dashboard to not fail in the gomote VM?

**Comment by rsc** [comment] 2015-12-05 04:44
Closing since we can't seem to reproduce it. If it comes back, we can debug it then.

**Closed by rsc** 2015-12-05 04:44 UTC
Labels: OS-Windows
