### ISSUE TITLE
cmd/compile: internal error: type recorded as live on entry

### ISSUE THREAD

**Issue by bep** [golang/go#15176] opened 2016-04-07 14:48 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

Go tip.

2. What operating system and processor architecture are you using (`go env`)?

OS X and Linux on Travis

3. What did you do?

Build Hugo (https://github.com/spf13/hugo).

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

See https://travis-ci.org/spf13/hugo/builds/121437210

4. What did you expect to see?

All green.

5. What did you see instead?

Build fails on Go tip, both OS X and Linux. 

I tried to see if this is a duplicate of an already reported issue, but it's hard to tell.

There is a test failure that I haven't looked into, but then there are these build failures:

```
19.35s$ go build -race

# github.com/pkg/sftp

../../pkg/sftp/client.go:829: internal error: (*File).WriteTo autotmp_781 (type *[]byte) recorded as live on entry, p.Pc=10248

# github.com/russross/blackfriday

../../russross/blackfriday/html.go:932: internal error: (*Html).ensureUniqueHeaderID autotmp_747 (type *int) recorded as live on entry, p.Pc=15486
```

Not sure when these failures started to happen ...

**Comment by dr2chase** [comment] 2016-04-07 15:22
Reproduces for me:
```
go get -u -v github.com/spf13/hugo
cd $GOPATH/src/github.com/spf13/hugo
go build -race -o hugo main.go
```

**Comment by dr2chase** [comment] 2016-04-07 20:06
Closer to root cause, in ssa.go I added this test and it fired:
```
func (s *state) resolveFwdRef(v *ssa.Value) {
	b := v.Block
	name := v.Aux.(*Node)
	v.Aux = nil
	if b == s.f.Entry {
		// Live variable at start of function.
		if s.canSSA(name) {
			if strings.HasPrefix(name.Sym.Name, "autotmp_") {
				s.Fatalf("Treating auto as if it were arg, func %s, node %v, value %v", b.Func.Name, name, v)
			}
			v.Op = ssa.OpArg
			v.Aux = name
			return
		}
```

**Comment by dr2chase** [comment] 2016-04-07 21:45
Bad code inserted by racewalk, not sure of the details, but the error (access to uninitialized autotmp) appears after racewalk.

**Comment by josharian** [comment] 2016-04-08 13:16
Possible duplicate of #15091.

**Comment by dr2chase** [comment] 2016-04-08 16:32
Is duplicate, and #15091 has a nice test case.

**Closed by dr2chase** 2016-04-08 16:32 UTC

**Comment by dr2chase** [comment] 2016-04-08 22:16
FYI, 15091 is fixed now, so this one should also be fixed. Not sure I did this the proper github way, but figured you'd like to know.

**Comment by bep** [comment] 2016-04-08 23:49
Thanks, I guess I would have known either way  -- as I just watched the red tests go green on all Go versions. Thanks!
