### ISSUE TITLE
cmd/link: malformed mach-o image: segment __DWARF has vmsize < filesize

### ISSUE THREAD

**Issue by bolenzhang** [golang/go#34935] opened 2019-10-16 13:18 UTC
### What version of Go are you using (`go version`)?
why not fix this issue #32673 in the version of go1.13?
<pre>
$ go version
go version go1.13.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zhangliyong/Library/Caches/go-build"
GOENV="/Users/zhangliyong/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zhangliyong/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/zhangliyong/chain/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rz/4wlrcszd55gf6s2j571bhlzr0000gn/T/go-build990418285=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Ran a shell script about golang testing. 

### What did you expect to see?

it works without errors

### What did you see instead?
dyld: malformed mach-o image: segment __DWARF has vmsize < filesize

**Comment by agnivade** [comment] 2019-10-17 04:08
I don't understand. The fix for #32673 was backported to 1.11 and 1.12. That means it is already there in 1.13. Your issue must be something else. Could you provide more details of how to reproduce this ?

**Comment by banishee** [comment] 2019-10-17 10:53
Its not work on the MacOS Catalina.
Try to rollback

**Comment by FUTC-Coding** [comment] 2019-10-21 23:42
I had the same problem, updated go with the newest version from the website and it worked again. Also on MacOS Catalina.

**Comment by joint-song** [comment] 2019-10-22 02:46
I hit this on bazel go test. After run bazel test, It produce an error with msg "dyld: malformed mach-o image: segment __DWARF has vmsize < filesize
Abort trap: 6".

I am not sure it's a problem of go or bazel. It can be reproduced both on Linux and macOS.

**Comment by agnivade** [comment] 2019-10-22 04:01
@joint-song - I am not sure how you are getting this on Linux. This error is very specific to mac.

To all those facing this problem, please ensure you are on the latest 1.13 release, and provide the macOS version and a small reproducer that exhibits this problem. Thanks.

**Comment by joint-song** [comment] 2019-10-23 08:53
> @joint-song - I am not sure how you are getting this on Linux. This error is very specific to mac.
> 
> To all those facing this problem, please ensure you are on the latest 1.13 release, and provide the macOS version and a small reproducer that exhibits this problem. Thanks.

I am sorry. In my case, it should be my fault with code. All tests went through with PASS after one more time rerun. :stuck_out_tongue_winking_eye:

**Comment by adibrastegarnia** [comment] 2019-10-28 15:14
I have the same problem. My go version is 1.12.5 and yesterday, I upgraded my mac os to 10.15. I cannot upgrade to 1.13 at this moment because we are still using 1.12 for a project.

**Comment by adibrastegarnia** [comment] 2019-10-28 16:20
@agnivade 
I don't think it is related to go version. The same error when I upgraded to go 1.13.3 as well on Mac os 10.15.

**Comment by ianlancetaylor** [comment] 2019-10-28 16:48
Somebody please tell us how to reproduce this.  Tell us precisely what you did.  Tell us precisely what happened.  Thanks.

**Comment by adibrastegarnia** [comment] 2019-10-28 18:02
> Somebody please tell us how to reproduce this. Tell us precisely what you did. Tell us precisely what happened. Thanks.

I will do my best to explain but I did lots of things to make it work. 

1- I removed my previous go version by deleting /usr/local/go  and /etc/paths.d/go. 
2- I installed the golang version 1.13.3 by copying it to /usr/local:
` tar -C /usr/local -xzf go$VERSION.$OS-$ARCH.tar.gz`

3- I have these lines in my .bashrc
```
export GOPATH=/Users/adibrastegarnia/go
export PATH=$PATH:/usr/local/go/bin
export GOROOT=/usr/local/go/
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
export GO111MODULE=on
```
When I tried to run source .bashrc that error happened. 

I ended up installing the golang using the pkg installer and it looks normal now. To be honest, I don't know exactly at what conditions that error occurs. 

Thanks,
Adib

**Comment by ianlancetaylor** [comment] 2019-10-28 21:56
If `.bashrc` contains only the `export` statements that you listed, I don't see any possible way that sourcing `.bashrc` could produce the error

    dyld: malformed mach-o image: segment __DWARF has vmsize < filesize

We can only fix this problem if we have a way to reproduce this ourselves.  Thanks.

(Separately, I recommend very strongly that you not set `GOROOT` in your `.bashrc` file.  It is only necessary to set `GOROOT` under special and unusual circumstances.  If some of our documentation recommended that you set `GOROOT`, please let us know, so that we can fix it.  Thanks.)

**Comment by adibrastegarnia** [comment] 2019-10-28 22:32
> If `.bashrc` contains only the `export` statements that you listed, I don't see any possible way that sourcing `.bashrc` could produce the error
> 
> ```
> dyld: malformed mach-o image: segment __DWARF has vmsize < filesize
> ```
> 
> We can only fix this problem if we have a way to reproduce this ourselves. Thanks.
> 
> (Separately, I recommend very strongly that you not set `GOROOT` in your `.bashrc` file. It is only necessary to set `GOROOT` under special and unusual circumstances. If some of our documentation recommended that you set `GOROOT`, please let us know, so that we can fix it. Thanks.)

I also have a auto-completion call for a go program in .bashrc. Thanks for your recommendation, I will consider it.

**Comment by ianlancetaylor** [comment] 2019-10-28 23:21
What program does the auto-completion call try to run?  Exactly how was that program built?  Thanks.

**Comment by adibrastegarnia** [comment] 2019-10-28 23:26
> What program does the auto-completion call try to run? Exactly how was that program built? Thanks.

It just a go program which has a cli using cobra framework.

**Comment by ianlancetaylor** [comment] 2019-10-29 00:04
Thanks, but that doesn't help tell us what we need to know.

We can only fix this problem if we have a way to reproduce this ourselves. Thanks.

**Comment by chaseWillden** [comment] 2019-11-01 19:02
Man I'm getting it too

**Comment by edjroz** [comment] 2019-11-02 04:01
I’m also receiving this error

**Comment by loodvn** [comment] 2019-11-04 10:38
Seems that this was fixed in https://github.com/golang/go/commit/26954bde4443c4bfbfe7608f35584b6b810f3f2c

**Comment by networkimprov** [comment] 2019-11-04 11:48
That commit landed before 1.13 debuted.

**Comment by thanm** [comment] 2019-11-13 19:47
@bolenzhang It would be nice if we could close this bug out -- any more to do / say here?

**Closed** 2019-11-17 04:13 UTC
Labels: NeedsInvestigation, OS-Darwin, WaitingForInfo

**Comment by xt0fer** [comment] 2019-12-18 14:32
I hit this trying to use a executable from this repo: https://github.com/kyleconroy/sqlc.git 
Inside of the project, `cd cmd/sqlc; go build; ./sqlc`
```
dyld: malformed mach-o image: segment __DWARF has vmsize < filesize
Abort trap: 6
```

**Comment by thanm** [comment] 2019-12-18 14:46
Hi @xt0fer , this issue is closed -- if you are still seeing problems, please open a new issue, including details on how to reproduce (go version, etc). As mentioned previously this should have been fixed in Go 1.13.

**Comment by xt0fer** [comment] 2019-12-18 16:33
yeah, I should have mentioned this result was using... 1.13.5

**Comment by networkimprov** [comment] 2019-12-18 16:49
Erm, @thanm the issue closed due to "waiting for info" and @xt0fer just posted a possible reproducer; I think it could be reopened.

**Comment by thanm** [comment] 2019-12-18 18:49
> Erm, @thanm the issue closed due to "waiting for info" and @xt0fer just posted a possible reproducer; I think it could be reopened.

OK, I built a fresh copy of Go from the go1.13 release branch on my macbook, downloaded github.com/kyleconroy/sqlc, did "cd cmd/sqlc; go build; ./sqlc", and I don't see this issue (I just get a usage message). Anything else that I am missing? My machine is running 10.14.6.

**Comment by xt0fer** [comment] 2019-12-18 20:31
Negative; I was (damn `brew`) still managing to compile with 1.12.1 here, when I thought I was using 1.13.5 over there. I was able to compile and run fine via 1.13.5. I believe the issue closed and fixed.

**Comment by thanm** [comment] 2019-12-18 20:53
OK, thanks for confirming that.

**Comment by itsmontoya** [comment] 2020-02-14 17:19
One of my F/E Engineers are receiving this issue on both 1.12.5 and 1.13.8. Should I have him roll back to 1.13.5?

**Comment by thanm** [comment] 2020-02-14 17:27
@itsmontoya the fix for this problem has been in Go1.13 since 1.13.1 -- can you please verify that you are indeed using the correct version? Several other folks have posted similarly and in each case the problem was a stale Go version. Thanks.

**Comment by thanm** [comment] 2020-02-14 17:31
I should add that Go 1.12.5 does  not contain the release for this bug, you will need Go 1.12.7 or later.

**Comment by buihdk** [comment] 2020-04-30 13:42
I still encountered this issue in the Go newest version v1.14.2. I posted an issue here, could someone please check? #38765

**Comment by vuongggggg** [comment] 2020-05-18 06:24
Still got this issue even I have updated my go to 1.12.17 (darwin/amd64)
