### ISSUE TITLE
affected/package: genetic bug in 1.18 beta

### ISSUE THREAD

**Issue by acehow** [golang/go#50385] opened 2021-12-29 14:49 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.18beta
</pre>

### Does this issue reproduce with the latest release?

...

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
windows11
</pre></details>

### What did you do?

this not ok : 
https://go.dev/play/p/Lwe42hNUKje?v=gotip
### What did you expect to see?

run ok, because both types are string alias

### What did you see instead?

./prog.go:21:21: type s1 of m does not match inferred type s2 for P

**Comment by bitfield** [comment] 2021-12-29 15:20
I think this is working as designed. By declaring:

```go
func min[P constraints.Ordered](x, y P) P {
```

you're saying that both `x` and `y` must be the _same_ type P (whatever P turns out to be). And they're not. `m` is of type `s1`, and `n` is of type `s2`, and those are distinct types.

**Comment by seankhliao** [comment] 2021-12-29 15:48
see above, closing as working as intended

**Closed by seankhliao** 2021-12-29 15:48 UTC
