### ISSUE TITLE
website: text/template example fails

### ISSUE THREAD

**Issue by wafture** [golang/go#14418] opened 2016-02-20 00:15 UTC
Hello there,

The main [example](https://golang.org/pkg/text/template/#example_Template) on golang.org seems to be failing due to a lack of whitespace after the else block.

template block:
```
Dear {{.Name}},
{{if .Attended}}
It was a pleasure to see you at the wedding.
{{- else}}

```
failure:
```
panic: template: letter:5: illegal number syntax: "-"

goroutine 1 [running]:
text/template.Must(0x0, 0xfeec0018, 0x1050a1e0, 0x0, 0x0, 0xfeec0018)
	/usr/local/go/src/text/template/helper.go:23 +0x60
main.main()
	/tmp/sandbox410328915/main.go:37 +0x320
```

adding a space works:
```
Dear {{.Name}},
{{if .Attended}}
It was a pleasure to see you at the wedding.
{{- else }}
```

**Comment by ianlancetaylor** [comment] 2016-02-20 00:38
This works with Go 1.6, but not with Go 1.5.  So the problem is that the playground is still running Go 1.5.  But I thought it had been upgraded, so I'm not sure what's going on.  Assigning to @adg.

**Comment by minux** [comment] 2016-02-20 01:28
It's bad output caching. If you add a few spaces to the program, it will
run fine.

I think after upgrading the sandbox, we need to flush the output cache.

**Comment by adg** [comment] 2016-02-26 03:47
The cache has been purged now.

**Closed by adg** 2016-02-26 03:47 UTC
