### ISSUE TITLE
x/mobile: pprof support?

### ISSUE THREAD

**Issue by DmitriyMV** [golang/go#14158] opened 2016-01-30 14:03 UTC
I wonder if that can be achieved. I tried to to use cpu profiler using "net/http/pprof", but without binary it didn't manage to get anything useful for top or list commands. Unpacked apk and used .so as binary but it also didn't help.

Host OS - Windows 8.1. 
Mobile OS - Android 4.4.

Can be anything done about it? Or I am doing something severely wrong?

**Comment by joeblew99** [comment] 2016-01-30 23:07
I was trying the exact same thing tonight.
+1 from me too :)

**Comment by hyangah** [comment] 2016-02-01 17:28
Duplicate of #14043.
(go on android depends on buildmode=c-shared, go on ios depends on buildmode=c-archive)

**Closed by hyangah** 2016-02-01 17:28 UTC
