### ISSUE TITLE
cmd/go: get -u -t fails to update go.mod when "no non-test Go files in path"

### ISSUE THREAD

**Issue by kbalk** [golang/go#45112] opened 2021-03-18 21:48 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Did not test on the latest version.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kbalk/.cache/go-build"
GOENV="/home/kbalk/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/kbalk/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/kbalk/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/kbalk/plus3it/terraform-aws-org-new-account-iam-role/tests/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build005428471=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I have a Go module (`module_test.go`) for testing a Terraform init/plan/apply.  All I have and need in terms of programming is this single `go` file with a package name of `testing`.   I have a `go.mod` file as shown below.  The directory `tardigrade-ci/tests` mentioned in `go.mod` will contain `module_test.go`, `go.mod`, `go.sum` and some Terraform files.

I ran `go get -u -t` to get updated versions in `go.mod`.  In particular, `github.com/stretchr/testify` had released an updated version.

```
module tardigarde-ci/tests

go 1.15

require (
	github.com/gruntwork-io/terratest v0.32.8
	github.com/stretchr/testify v1.6.1
	golang.org/x/net v0.0.0-20201021035429-f5854403a974 // indirect
	golang.org/x/sys v0.0.0-20210119212857-b64e53b001e4 // indirect
)

replace github.com/gruntwork-io/terratest v0.32.8 => github.com/ffernandezcast/terratest v0.28.6-0.20201201084725-13e8a4c156b8
```

### What did you expect to see?
Updated version for `github.com/stretchr/testify`; instead of v1.6.1, expected to see v1.7.0.

### What did you see instead?
`go.mod` file was unchanged.  Will updates to `go.mod` only occur when there are non-test files?

Note:  I also tried running `go clean -modcache`, then running `go get -u -t` and that had no effect.

**Comment by jayconrod** [comment] 2021-03-19 13:08
cc @bcmills @matloob

**Comment by jayconrod** [comment] 2021-03-19 13:09
I thought this might be a duplicate of #33526, but it still reproduces at tip.

**Comment by bcmills** [comment] 2021-03-19 13:50
This invocation is missing the `-d` flag.

`go get -u -t` requests that the `go` command do all of:
1. Fetch and update all of the dependencies of the package named on the command line, or the current package (if no other package is named), along with the dependencies of its test.
2. Build the named package.

This command is failing in step (2), which causes the overall operation to fail. In [CL 255970](https://golang.org/cl/255970) (for #41315), we decided that we should only update the `go.mod` file if the `go get` command overall succeeds.

The `-d` flag explicitly requests to skip step (2). If that is done here, the dependencies of the (named or implicit) test-only package should be updated as requested.

**Comment by kbalk** [comment] 2021-03-19 16:56
I've tried `go get -u -t -d` and `go.mod` is still not updated.

**Comment by jayconrod** [comment] 2021-03-19 17:29
@kbalk Is `go get -u -t -d` still showing an error, or only not updating `go.mod`? If the latter, does the package in the current directory import `github.com/stretchr/testify`?

**Comment by kbalk** [comment] 2021-03-19 17:38
There's no error, but there's no change to `go.mod` (I've since removed the indirects in go.mod):

```
go get -u -t -d tardigrade-ci/tests
go: github.com/russross/blackfriday/v2 upgrade => v2.1.0
go: github.com/stretchr/testify upgrade => v1.7.0
go: github.com/jmespath/go-jmespath upgrade => v0.4.0
go: google.golang.org/appengine upgrade => v1.6.7
go: gopkg.in/yaml.v3 upgrade => v3.0.0-20210107192922-496545a6307b
go: golang.org/x/sys upgrade => v0.0.0-20210319071255-635bc2c9138d
go: github.com/davecgh/go-spew upgrade => v1.1.1
go: github.com/urfave/cli upgrade => v1.22.5
go: github.com/go-sql-driver/mysql upgrade => v1.5.0
go: golang.org/x/net upgrade => v0.0.0-20210316092652-d523dce5a7f4
go: github.com/go-errors/errors upgrade => v1.1.1
go: github.com/google/uuid upgrade => v1.2.0
go: github.com/jinzhu/copier upgrade => v0.2.8
go: github.com/gruntwork-io/terratest upgrade => v0.32.15
go: github.com/aws/aws-sdk-go upgrade => v1.38.0
go: github.com/cpuguy83/go-md2man/v2 upgrade => v2.0.0
go: github.com/boombuler/barcode upgrade => v1.0.1
go: golang.org/x/crypto upgrade => v0.0.0-20210317152858-513c2a44f670
go: github.com/pmezard/go-difflib upgrade => v1.0.0
go: github.com/gruntwork-io/gruntwork-cli upgrade => v0.8.2
go: github.com/pquerna/otp upgrade => v1.3.0
go get: github.com/gruntwork-io/gruntwork-cli@v0.7.0 updating to
	github.com/gruntwork-io/gruntwork-cli@v0.8.2: parsing go.mod:
	module declares its path as: github.com/gruntwork-io/go-commons
	        but was required as: github.com/gruntwork-io/gruntwork-cli
```

**Comment by bcmills** [comment] 2021-03-19 17:45
> ```
> go get: github.com/gruntwork-io/gruntwork-cli@v0.7.0 updating to
> 	github.com/gruntwork-io/gruntwork-cli@v0.8.2: parsing go.mod:
> 	module declares its path as: github.com/gruntwork-io/go-commons
> 	        but was required as: github.com/gruntwork-io/gruntwork-cli
> ```

That is an error, is it not?

**Comment by kbalk** [comment] 2021-03-19 18:03
Yes ... my apologies, I was thinking of a command line error.

**Comment by bcmills** [comment] 2021-03-19 18:18
FWIW, in Go 1.16 the explicit versions on the command line should serve as upper bounds for implicit upgrades. So you could try:

```
$ go get -u -t -d tardigrade-ci/tests github.com/gruntwork-io/gruntwork-cli@v0.7.0
```

**Comment by kbalk** [comment] 2021-03-20 00:00
I have updated to Go 1.16 and I could use your suggestion.  But it would be nice if `go get` supplied the updated version number.

**Comment by jayconrod** [comment] 2021-03-22 16:32
In 1.16, `go get` does supply the updated version. It should look like this:

```
$ go get example.com/mod
go get: upgraded example.com/mod v0.3.0 => v0.4.2
```

It sounds like this is working correctly now, so I'll close this issue but let me know if I missed something.

**Closed by jayconrod** 2021-03-22 16:32 UTC
Labels: NeedsInvestigation, modules

**Comment by kbalk** [comment] 2021-03-22 16:48
The problem still exists and I get a command line warning/error.

```
$ go version
go version go1.16.2 linux/amd64
$ go get tardigrade-ci/tests
go build tardigrade-ci/tests: no non-test Go files in /home/kbalk/plus3it/terraform-aws-org-new-account-iam-role/tests
```

**Comment by jayconrod** [comment] 2021-03-22 18:59
That error is expected for `go get` without the `-d` flag (see [comment](https://github.com/golang/go/issues/45112#issuecomment-802847541)) because `go get` attempts to build the package.

With the `-d` flag, this shouldn't cause an error. The `parsing go.mod` error you posted earlier is caused by something else.

**Comment by kbalk** [comment] 2021-03-22 19:26
So there's currently no way to update go.mod when I just have a test package.  I cannot use dependabot to check for updates.

**Comment by jayconrod** [comment] 2021-03-22 21:05
Use the `-d` flag.
