### ISSUE TITLE
path/filepath: Ext returns file name as extension for hidden files on Linux/Unix

### ISSUE THREAD

**Issue by steffenfritz** [golang/go#66814] opened 2024-04-14 07:51 UTC
### Go version

go version go1.22.2 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/steffen/Library/Caches/go-build'
GOENV='/Users/steffen/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/steffen/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/steffen/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.22.2/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.22.2/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.2'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/steffen/go/src/github.com/steffenfritz/FileTrove/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/rt/mbz5zkp533sgg49fmm6ky3tr0000gn/T/go-build4253382559=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

I used filepath.Ext() to get the file extensions from a list of filenames

https://go.dev/play/p/vvPcsGwcD5p

### What did you see happen?

For files on Linux/Unix that are hidden with a prefix dot and without an extension, e.g. ".hiddenfile", Ext() returns the filename as extension.

### What did you expect to see?

That Ext() returns no extension for files that are prefixed with a dot (".") that don't have an extension.

From my point of view, the condition that the dot is not the first element in the string, is missing.

**Comment by seankhliao** [comment] 2024-04-14 07:56
Duplicate of #24239

**Closed by seankhliao** 2024-04-14 07:56 UTC
