### ISSUE TITLE
Some random package broke all my go programs.

### ISSUE THREAD

**Issue by Harardin** [golang/go#34731] opened 2019-10-07 13:07 UTC
I have an issue can't run a debug can't build anything.

using VS code to write Go

Here is the full error text:

```
go: inconsistent vendoring in C:\Go\src:
        go.mod requires github.com/google/go-cmp v0.3.1 but vendor/modules.txt does not include it.
        run 'go mod tidy; go mod vendor' to sync
```

Here is my code:

```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello from go")
}
```

Tried to use `go get` and `go mod tidy; go mod vendor`

**Comment by bcmills** [comment] 2019-10-07 13:14
It sounds like `C:\Go` is where your Go toolchain and standard library are installed (a.k.a. `GOROOT`). `GOROOT\src` is where the Go standard library lives; put your own code in `GOPATH` (which defaults to `%USERPROFILE%\go`) instead.

**Comment by bcmills** [comment] 2019-10-07 13:14
Duplicate of #34657

**Closed by bcmills** 2019-10-07 13:14 UTC
