### ISSUE TITLE
go install: Flag to override VCS URL

### ISSUE THREAD

**Issue by mcandre** [golang/go#47767] opened 2021-08-18 00:19 UTC
Could `go install` please gain a new flag to optionally override the inferred version control system URL?

That would help more corporate organizations to maintain DevOps-purposed forks of important Go development tools.

For example, to avoid sirupsen / leftpad outages. Or simply to house bugfixes prior to upstream accepting the fixes.

**Comment by seankhliao** [comment] 2021-08-18 10:37
Duplicate of #45980

**Closed by seankhliao** 2021-08-18 10:37 UTC
