### ISSUE TITLE
[bug report] flag provided but not defined: -test.v

### ISSUE THREAD

**Issue by fwhezfwhez** [golang/go#46869] opened 2021-06-22 06:37 UTC
Go 1.13.15 has a bug for package flag. Code below can help reproduce it.

config/init.go
```go
package config

import "flag"
var mode string
func init() {

	flag.StringVar(&mode, "mode", "local", "go run main.go -mode 'local'")
	flag.Parse()
}
```

config/init_test.go
```go
package config

import (
	"fmt"
	"testing"
)

func TestDefault(t *testing.T) {
	fmt.Println(mode)
}
```

output
go 1.12.17  ok
```go
=== RUN   TestDefault
local
--- PASS: TestDefault (0.00s)
PASS
```

go 1.13.15
```go
flag provided but not defined: -test.v
Usage of C:\Users\DELL\AppData\Local\Temp\___TestDefault_in_libgamedataapisrv_config.exe:
  -mode string
    	go run main.go -profPort ':6060' (default "local")
```

**Comment by the-moment** [comment] 2021-06-22 06:42
still hava this in 1.16.3

**Comment by davecheney** [comment] 2021-06-22 06:53
What is the exact command you ran?

**Comment by davecheney** [comment] 2021-06-22 06:54
Sorry, you cannot call flag.Parse in init because it conflicts with the flags that are passed to the test binary. Move flag.parse to your main function

**Comment by agnivade** [comment] 2021-06-22 06:57
What Dave said.

This is expected and documented: https://golang.org/doc/go1.13#testing, https://github.com/golang/go/issues/31859.

Closing.

**Closed by agnivade** 2021-06-22 06:57 UTC

**Comment by the-moment** [comment] 2021-06-22 07:05
> What is the exact command you ran?



> What Dave said.
> 
> This is expected and documented: https://golang.org/doc/go1.13#testing, #31859.
> 
> Closing.

I saw this question,but when will solve this problem.or should I notice that question in any program?

**Comment by the-moment** [comment] 2021-06-22 07:06
> What is the exact command you ran?

go test -v -run + myfun

**Comment by fwhezfwhez** [comment] 2021-06-22 08:00
@the-moment 
Write flag.Parse in main.go, whatever main.go init Func or main.go beginning. It's ok. And don't write flag.Parse in any init Func of other package.

By the way, testing function will auto call flag.Parse(). Style below is ok
```go
package config

import "flag"
var mode string
func init() {
	flag.StringVar(&mode, "mode", "local", "go run main.go -mode 'local'")
}
```
```go
package config

import (
	"fmt"
	"testing"
)

func TestDefault(t *testing.T) {
	fmt.Println(mode)
}
```

```
go test -run ^TestDefault$ -mode hehe
```

Output
```go
hehe
```

As it suggests, `hehe` is output correctly even if I didn't call flag.Parse yet. It, `flag.Parse`, seems just called inside.

**Comment by davecheney** [comment] 2021-06-22 08:07
Thats about it. Because flag.Parse operates on global state it must only be called once. The problem is both your package and, when compiled as a test, the testing package both define _and_ parse flags, there is no way to make it work with flag.Parse called from init. Either:

- flag.Parse is called from your package, in which case the flags defined in the testing package haven't been defined yet so yo get a weird message about flags you didn't define causing the test process to fail.
- or, the testing package's flag.Parse is called and your flags aren't registered so your test blows up because the flags you were expecting aren't defined and cannot be used.

The root problem is the global flag.Parse singleton, but sadly that ship has long sailed. You can work around this by doing one or more of the following:

- Defining your own flag set
- calling flag.Parse in your _main_ function, and no sooner.
