### ISSUE TITLE
go tool compile

### ISSUE THREAD

**Issue by shrirangadgaonkar-okta** [golang/go#55111] opened 2022-09-16 21:41 UTC
### What version of Go are you using (`go version`)?   `1.19.1 darwin/arm64`

<pre>
$ go version
go version go1.19.1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
MacOS on M1

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre>GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/dev/Library/Caches/go-build"
GOENV="/Users/dev/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/dev/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/dev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/dev/go/src/....../go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t9/p9vr0xbx5rz5n4j55dxc4s5w0000gp/T/go-build1811328283=/tmp/go-build -gno-record-gcc-switches -fno-common"</details>

### What did you do?
Build project with debug.

Here is a snippet of the makefile passing gcflags 
```
GOFLAGS := ${GOFLAGS} -mod=vendor
ifneq ($(DEBUG), )
  GOFLAGS :=${GOFLAGS} -gcflags=all="-N -l"
...
...
```

--> $ DEBUG=1 make target

### What did you expect to see?

standard output of files compiling and then soruces getting built.
```
DEBUG=1 make linux
mkdir -p ./build/linux_amd64
GOOS=linux GOARCH=amd64 go build  -mod= -mod=vendor -gcflags=all="-N" -v -o ./build/linux_amd64/diag ./infra/cmd/diag
internal/goarch
internal/unsafeheader
math/bits
internal/goos
unicode/utf8
internal/itoa
internal/goexperiment
...
...
...
```
### What did you see instead?

```
DEBUG=1 make linux
mkdir -p ./build/linux_amd64
GOOS=linux GOARCH=amd64 go build  -mod= -mod=vendor -gcflags=all="-N -l" -v -o ./build/linux_amd64/diag ./infra/cmd/diag
go: parsing $GOFLAGS: unknown flag -l"
```

**Comment by seankhliao** [comment] 2022-09-16 21:48
Duplicate of #26849

**Closed by seankhliao** 2022-09-16 21:48 UTC
