### ISSUE TITLE
Inbuilt matrix support 

### ISSUE THREAD

**Issue by chandrashekarka** [golang/go#16491] opened 2016-07-25 16:31 UTC
I am a PhD student at the institute of mathematical sciences,Chennai,India. I recently started using go for my work and i love the language already. I do most of my work in python using libraries like numpy,scipy,matplotlib,pandas ... Considering that GO is supposed be the C for 21st century shouldn't math library support linear algebra since linear algebra! For this to happen matrix should become an inbuilt data type. At the moment using 2D array instead of a matrix is like using a list of lists in python. Python overcame this because of numpy but since GO is still in its infancy why not make matrix a core datatype ? Once thats done one can provide linear algebra operations as part of math library. I am really excited about GO and i am quite sure that the third party libraries like gonum will mature enough to become numpy for GO but i still feel that if matrix becomes a basic datatype then this will basically provide the best of both C++,fortan and Python,Matlab world and might become the language for scientific computing.

**Comment by dsnet** [comment] 2016-07-25 17:04
Perhaps this is a duplicate of #6282, which is intended for this use case?

**Comment by chandrashekarka** [comment] 2016-07-25 17:46
Thanks for meeting me know. Sorry

**Closed** 2016-07-25 17:45 UTC
