### ISSUE TITLE
x/tools: publish GitHub releases for tools

### ISSUE THREAD

**Issue by katexochen** [golang/go#64886] opened 2023-12-28 15:52 UTC
Currently, only new gopls versions are published as GitHub release under https://github.com/golang/tools/releases. The tool versions are only tagged but not published.
Would it be possible to also get GitHub releases for those versions? Automatic detection of new releases is much better supported on GitHub than for tags, e.g., you cannot watch new tags on a repo to get notification. It would also help with downstream packaging tools/automation.
Thanks and keep GOing! :)

**Comment by dr2chase** [comment] 2023-12-28 18:01
@golang/tools-team

**Comment by findleyr** [comment] 2023-12-28 18:14
CC @golang/release, since this argument could apply to any subrepo, not just tools.

I defer to the release team, but suspect we won't want to do this. Gopls release notes are manually curated and published specifically so that we can explain what changed. x/tools releases are arbitrary, and so the release notes would be pretty meaningless. Therefore the only purpose of creating a release would be to feed automation, as you note. That doesn't seem worth maintaining an extra piece of automation on our side.

**Comment by seankhliao** [comment] 2023-12-28 18:21
see also #13497 #15966 #40768 #45185

**Comment by findleyr** [comment] 2023-12-28 18:28
Thanks @seankhliao. Sounds like we are not opposed to this after all. Closing as a dupe of #15966.

**Closed by findleyr** 2023-12-28 18:28 UTC
Labels: NeedsInvestigation, Tools
