### ISSUE TITLE
Unexpected Syntax Compilation: Direct Interface Method Invocation

### ISSUE THREAD

**Issue by dogancanbakir** [golang/go#66334] opened 2024-03-15 12:19 UTC
### Go version

go version go1.22.1 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/dogancanbakir/Library/Caches/go-build'
GOENV='/Users/dogancanbakir/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/dogancanbakir/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/dogancanbakir/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.22.1/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.22.1/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.1'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/dogancanbakir/Projects/dummy/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/hx/f8qcbgj91795xdrdnb55qkdc0000gn/T/go-build2327627015=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

I encountered a scenario where Go unexpectedly allows and correctly compiles syntax that directly invokes a method on an interface type, passing an instance of a struct that implements this interface as a parameter. I was expecting this to result in a compilation error. However, it compiles and runs as if the method was called directly on the struct instance.

https://go.dev/play/p/Yo74FigCwe1

### What did you see happen?

I encountered a scenario where Go unexpectedly allows and correctly compiles syntax that directly invokes a method on an interface type, passing an instance of a struct that implements this interface as a parameter. I was expecting this to result in a compilation error. However, it compiles and runs as if the method was called directly on the struct instance.

```
7
42

Program exited.
```

### What did you expect to see?

I expect the code to throw a compilation error because of the line `fmt.Println(Op.Exec(multiplication))` tries to call a method directly on an interface type Op. Is this sort of alias for `Op(addition).Exec()`.

cc @HazarBakir

**Comment by aarzilli** [comment] 2024-03-15 13:09
See https://go.dev/ref/spec#Method_expressions in particular:

>  It is legal to derive a function value from a method of an interface type. The resulting function takes an explicit receiver of that interface type. 

I think this is what you are looking for.

**Comment by dogancanbakir** [comment] 2024-03-15 13:38
I was uncertain, but I thought this could be it. Nevertheless, I wanted to bring to your attention whether the syntax is illegal or not. Thank you for clarifying things!

**Comment by seankhliao** [comment] 2024-03-15 14:44
closing as working as intended.

**Closed by seankhliao** 2024-03-15 14:44 UTC

**Comment by randall77** [comment] 2024-03-15 14:50
Yes, that is a (admittedly weird, but correct) method expression.
