### ISSUE TITLE
Compiler does not emit "variable declared and not used" error

### ISSUE THREAD

**Issue by nishanths** [golang/go#19611] opened 2017-03-19 15:20 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.3 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nishanthshanmugham/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d9/pcgk8kl56hl8zg6nz7y345mh0000gn/T/go-build506584398=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?

```
package main

func main() {
    var x bool
    func() {
        x = true
    }()
}
```

https://play.golang.org/p/UvBjcvhFUc

### What did you expect to see?

Expected the compiler to emit a `x declared and not used` error at compile time, like the error in this example: https://play.golang.org/p/axGTIG8vi9

### What did you see instead?

Program compiled and ran successfully.

**Comment by golang101** [comment] 2017-03-19 15:36
compiler will think x is used for such case, another similar case:

	package main

	func main() {
	    var x bool
	    *&x = true
	}

For op's case, compiler will create a function object with has a field stores the address of x. Assign value to x is the same as my case in fact.

**Comment by ALTree** [comment] 2017-03-19 15:45
Thanks for the report. 

This is a duplicate of #3059 (cmd/compile: diagnose unused variable even in closure), so I'm closing this thread in favour of the older one.

**Closed by ALTree** 2017-03-19 15:45 UTC
