### ISSUE TITLE
cmd/go: module mode doesn't work without go.mod

### ISSUE THREAD

**Issue by computermouth** [golang/go#26994] opened 2018-08-15 00:29 UTC
### What version of Go are you using (`go version`)?
```
$ go version
go version go1.10.3 linux/amd64
```

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Debian Stretch
```
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/${USER}/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/${USER}/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build573429602=/tmp/go-build -gno-record-gcc-switches"
```

### What did you expect to see, what did you see instead?
```
$ go build -o bin/thing cmd/hello-world/main.go 
$ vgo build -o bin/thing cmd/hello-world/main.go 
go: cannot determine module path for source directory /home/${USER}/work/tools (outside GOPATH, no import comments)
```

Maybe I'm wrong here, and I've just missed some bit of documentation. But I was originally expecting the following to work:
```
$ vgo build cmd/hello-world/
```

Is there currently no implementation to specify a directory beyond the cwd? As shown above, even the behavior of the old `go build path/to/main.go` no longer works with vgo. Is there a plan for the top level directory or specifying `go.mod`s to build from an outside directory?

**Comment by andybons** [comment] 2018-08-15 16:38
@rsc @bcmills @ianlancetaylor

**Comment by rsc** [comment] 2018-08-18 03:59
We haven't worked out the story for what to do when no go.mod can be found. There will probably need to be a mop-up go.mod somewhere like GOPATH/src/go.mod.

**Comment by myitcv** [comment] 2018-11-14 05:13
Related to #24250 in that `go get` and `go run` working outside of a module are being defined in that issue.

**Comment by bcmills** [comment] 2018-11-14 17:20
`go build some/directory/` can't work without a module definition: the package path is observable at run-time (e.g. using the `reflect` package), and the package path depends on the module path.

`go build some/file.go` can and probably will, since that already synthesizes a fake package (and hence doesn't care about paths). (See the current draft behavior in [CL 148517](https://go-review.googlesource.com/c/go/+/148517/4/src/cmd/go/testdata/script/mod_outside.txt).)

Closing as a duplicate of #24250: it's not precisely the same issue, but shares the same fix.

**Closed by bcmills** 2018-11-14 17:20 UTC
Labels: NeedsInvestigation, modules
