### ISSUE TITLE
reflect: panic from malloc after MakeFunc function returns value that is also stored globally

### ISSUE THREAD

**Issue by RogerChickering** [golang/go#39541] opened 2020-06-12 01:08 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes. I can reproduce with 1.14.4 and also 1.15beta as well as in the go playground.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rchickering/Library/Caches/go-build"
GOENV="/Users/rchickering/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="hq-stash.corp.proofpoint.com"
GONOSUMDB="hq-stash.corp.proofpoint.com"
GOOS="darwin"
GOPATH="/Users/rchickering/go"
GOPRIVATE="hq-stash.corp.proofpoint.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/rchickering/efficacy-ingestor/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4v/bq1k0tjd5gvdl7xkbvdqwtr0ldfw68/T/go-build031420409=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Ran this program:

https://play.golang.org/p/DU16otT2UhO

### What did you expect to see?

Program should run to completion

### What did you see instead?

A panic with the following error on the playground:
<pre>
runtime: nelems=512 nalloc=3 previous allocCount=2 nfreed=65535
fatal error: sweep increased allocation count
runtime: nelems=512 nalloc=3 previous allocCount=2 nfreed=65535
fatal error: sweep increased allocation count
runtime: nelems=512 nalloc=3 previous allocCount=2 nfreed=65535
fatal error: sweep increased allocation count
runtime: nelems=512 nalloc=3 previous allocCount=2 nfreed=65535
fatal error: sweep increased allocation count
runtime: nelems=512 nalloc=3 previous allocCount=2 nfreed=65535
fatal error: sweep increased allocation count
runtime: nelems=512 nalloc=3 previous allocCount=2 nfreed=65535
fatal error: sweep increased allocation count
runtime: nelems=512 nalloc=3 previous allocCount=2 nfreed=65535
fatal error: sweep increased allocation count
runtime: nelems=512 nalloc=11 previous allocCount=9 nfreed=65534
fatal error: sweep increased allocation count

goroutine 981 [running]:
runtime.throw(0x4a80c4, 0x20)
	/usr/local/go-faketime/src/runtime/panic.go:1116 +0x72 fp=0xc000e04ab0 sp=0xc000e04a80 pc=0x42d182
runtime.(*mspan).sweep(0x7f2ad2f87ac0, 0x0, 0x1)
	/usr/local/go-faketime/src/runtime/mgcsweep.go:328 +0x8b8 fp=0xc000e04b90 sp=0xc000e04ab0 pc=0x41f498
runtime.sweepone(0x1)
	/usr/local/go-faketime/src/runtime/mgcsweep.go:136 +0x284 fp=0xc000e04bf8 sp=0xc000e04b90 pc=0x41e974
runtime.deductSweepCredit(0x2000, 0x0)
	/usr/local/go-faketime/src/runtime/mgcsweep.go:437 +0x80 fp=0xc000e04c20 sp=0xc000e04bf8 pc=0x41f5f0
runtime.(*mcentral).cacheSpan(0x559e78, 0x203001)
	/usr/local/go-faketime/src/runtime/mcentral.go:43 +0x60 fp=0xc000e04c68 sp=0xc000e04c20 pc=0x413f40
runtime.(*mcache).refill(0x7f2af9e4b7d0, 0x106)
	/usr/local/go-faketime/src/runtime/mcache.go:138 +0x85 fp=0xc000e04c88 sp=0xc000e04c68 pc=0x413c85
runtime.(*mcache).nextFree(0x7f2af9e4b7d0, 0x6, 0x10, 0x4875e0, 0xc000080380)
	/usr/local/go-faketime/src/runtime/malloc.go:868 +0x87 fp=0xc000e04cc0 sp=0xc000e04c88 pc=0x40ad87
runtime.mallocgc(0x20, 0x488b60, 0xc000877401, 0xc0008bc860)
	/usr/local/go-faketime/src/runtime/malloc.go:1036 +0x793 fp=0xc000e04d60 sp=0xc000e04cc0 pc=0x40b6c3
runtime.newobject(0x488b60, 0x3)
	/usr/local/go-faketime/src/runtime/malloc.go:1165 +0x38 fp=0xc000e04d90 sp=0xc000e04d60 pc=0x40bab8
main.initFuncs.func1(0x55c190, 0x0, 0x0, 0x55c190, 0x10, 0x48f340)
	/tmp/sandbox055973582/prog.go:39 +0x176 fp=0xc000e04e40 sp=0xc000e04d90 pc=0x47ace6
reflect.callReflect(0xc000060210, 0xc000e04fa8, 0xc000e04f90)
	/usr/local/go-faketime/src/reflect/value.go:549 +0x322 fp=0xc000e04f78 sp=0xc000e04e40 pc=0x4723a2
reflect.makeFuncStub(0xc0008bc840, 0xc0008bc840, 0x813, 0x0, 0x459a21, 0xc00000e010, 0xc00002c030, 0x0, 0x0, 0x0, ...)
	/usr/local/go-faketime/src/reflect/asm_amd64.s:20 +0x42 fp=0xc000e04fa8 sp=0xc000e04f78 pc=0x477012
main.main.func1(0xc00000e010, 0xc00002c030)
	/tmp/sandbox055973582/prog.go:56 +0x33 fp=0xc000e04fd0 sp=0xc000e04fa8 pc=0x47ae13
runtime.goexit()
	/usr/local/go-faketime/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000e04fd8 sp=0xc000e04fd0 pc=0x459a21
created by main.main
	/tmp/sandbox055973582/prog.go:54 +0xac

(other stacks removed)
</pre>
On my mac with version 1.14.4 I see:
runtime: pointer 0xc000882020 to unallocated span span.base()=0xc000882000 span.limit=0xc000884000 span.state=0
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

**Comment by davecheney** [comment] 2020-06-12 02:55
Thank you for providing a runnable example, it is greatly apprecaited. Here is what I see running this program on `tip`.
```
runtime: pointer 0xc0005c6020 to unallocated span span.base()=0xc0005c6000 span.limit=0xc0005c8000 span.state=0
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

runtime stack:
runtime.throw(0x10a5ac6, 0x3e)
        /Users/davecheney/go/src/runtime/panic.go:1116 +0x72 fp=0x70000b6a7e78 sp=0x70000b6a7e48 pc=0x102f852
runtime.badPointer(0x9411d50, 0xc0005c6020, 0x0, 0x0)
        /Users/davecheney/go/src/runtime/mbitmap.go:380 +0x235 fp=0x70000b6a7ec0 sp=0x70000b6a7e78 pc=0x1012195
runtime.findObject(0xc0005c6020, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/davecheney/go/src/runtime/mbitmap.go:416 +0x9b fp=0x70000b6a7ef8 sp=0x70000b6a7ec0 pc=0x101225b
runtime.wbBufFlush1(0xc00002e800)
        /Users/davecheney/go/src/runtime/mwbbuf.go:288 +0xa8 fp=0x70000b6a7f50 sp=0x70000b6a7ef8 pc=0x102bc08
runtime.wbBufFlush.func1()
        /Users/davecheney/go/src/runtime/mwbbuf.go:218 +0x3a fp=0x70000b6a7f68 sp=0x70000b6a7f50 pc=0x105985a
runtime.systemstack(0x0)
        /Users/davecheney/go/src/runtime/asm_amd64.s:370 +0x66 fp=0x70000b6a7f70 sp=0x70000b6a7f68 pc=0x105d966
runtime.mstart()
        /Users/davecheney/go/src/runtime/proc.go:1101 fp=0x70000b6a7f78 sp=0x70000b6a7f70 pc=0x1034a00
```

**Comment by davecheney** [comment] 2020-06-12 02:56
I cannot reproduce the issue when setting `GOMAXPROCS=1`

**Comment by ianlancetaylor** [comment] 2020-06-12 04:24
Thanks for the test case.  Interesting failure.

Here is a somewhat reduced test case:

```Go
package main

import (
	"reflect"
	"sync"
)

type I interface {
	M()
}

type A string
func (A) M() {}

type S struct {
	F func() I
}

func sub(args []reflect.Value) []reflect.Value {
	rv := A("a")
	return []reflect.Value{reflect.ValueOf(I(rv))}
}

func main() {
	var s S
	fun := reflect.MakeFunc(reflect.TypeOf(s.F), sub)
	reflect.ValueOf(&s).Elem().Field(0).Set(fun)
	var wg sync.WaitGroup
	for ii := 0; ii < 100; ii++ {
		wg.Add(1)
		go func() {
			for jj := 0; jj < 10000; jj++ {
				s.F().M()
			}
			wg.Done()
		}()
	}
	wg.Wait()
}
```

Interestingly, if `sub` is changed to

```Go
func sub(args []reflect.Value) []reflect.Value {
	return []reflect.Value{reflect.ValueOf(I(A("a")))}
}
```

the program does not panic.  That suggests a compiler bug, though I don't see it.

CC @randall77

**Comment by davecheney** [comment] 2020-06-12 04:51
@ianlancetaylor would you consider assigning this to the 1.15 milestone until the underlying cause is known?

**Comment by ianlancetaylor** [comment] 2020-06-12 17:04
@davecheney I forgot to mention that I tried all the old Go releases and found that this program has never worked.  I think it would be great to fix this in 1.15, but since it's never worked I don't think we should hold up the 1.15 release in order to fix it.

**Comment by randall77** [comment] 2020-06-16 22:42
Simplified a bit more:
```
package main

import "reflect"

func sub(args []reflect.Value) []reflect.Value {
	type A string
	i := A("a")
	return []reflect.Value{reflect.ValueOf(i)}
}

func main() {
	c := make(chan bool, 100)
	for i := 0; i < 100; i++ {
		go func() {
			f := reflect.MakeFunc(reflect.TypeOf((func() interface{})(nil)), sub).Interface().(func() interface{})
			for j := 0; j < 10000; j++ {
				f()
			}
			c <- true
		}()
	}
	for i := 0; i < 100; i++ {
		<-c
	}
}
```
It seems to be triggered when `sub` calls `convTstring`, which is why edits to `sub` like Ian tried cause the bug to go away (because they make the `convTstring` call go away). I can't see anything wrong with `convTstring`, or `sub` for that matter. I think it may just be the extra allocation that triggers a latent bug somewhere. It's not the only allocation in `sub`, though, so I'm not sure why that would matter.

Still investigating.

**Comment by RogerChickering** [comment] 2020-06-17 00:27
Thanks everyone for investigating!

@randall77 in my attempts to work around this issue I found that it can happen without strings, as illustrated by this slight modification to the "simplified a bit more" version:
```
package main

import "reflect"

func sub(args []reflect.Value) []reflect.Value {
	type A int
	i := A(1)
	return []reflect.Value{reflect.ValueOf(i)}
}

func main() {
	c := make(chan bool, 100)
	for i := 0; i < 100; i++ {
		go func() {
			f := reflect.MakeFunc(reflect.TypeOf((func() interface{})(nil)), sub).Interface().(func() interface{})
			for j := 0; j < 10000; j++ {
				f()
			}
			c <- true
		}()
	}
	for i := 0; i < 100; i++ {
		<-c
	}
}
```
In the simplified example, the problem goes away if the variable i in sub is eliminated. However, when I try to work around this issue by returning an integer-based type without an intermediate variable I still see crashes in the program from which the first test case I posted was derived. If I can demonstrate that behavior with a simplified test case I'll add it here.

Thanks!
-Roger

**Comment by randall77** [comment] 2020-06-18 18:17
This looks like it was caused by CL 174531 which went out with go 1.13.
In go 1.12 and earlier, this program fails with
```
panic: reflect: function created by MakeFunc using closure returned wrong type: have main.A for interface {}
```
In 1.13, CL 174531 does that conversion for you. But there's something wrong with that conversion code. My current theory is that a write barrier occurs during the conversion, and that write barrier happens in a place where we can't really handle a write barrier, as data is on the stack in a precarious state.

**Comment by randall77** [comment] 2020-06-18 19:34
I think I understand the bug now. When `sub` is done, `reflect.callReflect` copies its results back to the stack (in the example, the results of the `f` call are unused, but that copy still happens). The copy requires a conversion from type `A` to type `interface{}`. We have a handy function `reflect.assignTo` which does that conversion. That function takes a `target` pointer which is used for scratch space. We pass the eventual destination of the interface, the return stack slot, as that scratch space.
Unfortunately, `reflect.assignTo` writes using a write barrier to that scratch space. But the scratch space is uninitialized, so the write barrier picks up the old, junk, value in the scratch space and puts it in the write barrier buffer. Some time later the mark workers come upon this junk pointer and barf on it.

I think the simple fix is to either not provide scratch space (which will require an allocation) or zero the scratch space first using uintptr writes.

**Comment by randall77** [comment] 2020-06-18 21:34
@gopherbot please open backport issues for 1.14 and 1.13.

**Comment by ianlancetaylor** [comment] 2020-06-18 22:21
Very nice.  Thanks.

**Comment by RogerChickering** [comment] 2020-06-19 00:17
Thanks for the fix @randall77 !!!!!

**Comment by randall77** [comment] 2020-06-19 00:22
@RogerChickering No worries.
It was my bug in the first place :)

**Closed** 2020-06-19 02:12 UTC
Labels: NeedsInvestigation
