### ISSUE TITLE
what the size of the struct si 40?

### ISSUE THREAD

**Issue by ymcvalu** [golang/go#38194] opened 2020-04-01 09:26 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 windows/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
https://play.golang.org/p/LYsw4ncFOe4
```go
func main() {
	fmt.Println(unsafe.Offsetof(C{}.E))
	fmt.Println(unsafe.Sizeof(C{}.E))
	fmt.Println(unsafe.Sizeof(C{}))
}

type C struct {
	A uint32
	B uint64
	C uint64
	D uint64
	E struct{}
}
```

### What did you expect to see?
i think the size of struct C is 32

### What did you see instead?
the size of struct C is 40, but the offset of E is 32, and size of E is 0

**Comment by ALTree** [comment] 2020-04-01 09:48
Trailing zero-sized struct fields are padded because if they weren't `&C.E` would point to an invalid memory location. If you reorder the struct to, for example:

```
type C struct {
	A uint32
	B uint64
	C uint64
	E struct{}
	D uint64
}
```

`Sizeof` will print 32. Closing here, since this is working as intended.

**Closed by ALTree** 2020-04-01 09:48 UTC
