### ISSUE TITLE
os/exec: when NoInheritHandles is set with a handle on Stdout or Stderr, executed command fails

### ISSUE THREAD

**Issue by zhaoya881010** [golang/go#45538] opened 2021-04-13 08:21 UTC
go version 1.16 windows/386

```
	out, err := os.OpenFile("test.out", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0766)
	c := exec.Command("cmd", "/C", "dir")
	c.Stdout = os.Stdout // OK
	//c.Stdout = out // Error
	c.SysProcAttr = &syscall.SysProcAttr{NoInheritHandles: true}
	c.Start()
	c.Wait()
```

if use c.Stdout = out,c.Wait() return error exit status 1

**Comment by mknyszek** [comment] 2021-04-13 16:49
Is the problem here that `NoInheritHandles` is causing some sort of failure in the subprocess because the stdout handle isn't being propagated correctly?

I'm actually not sure what `NoInheritHandles` is supposed to guarantee here; I could see it implying that _no_ handles are passed through at all -- you get a "bare" process in some sense that needs to set things up itself. But, I don't know enough about this to say.

CC @ianlancetaylor @bradfitz via https://dev.golang.org/owners

**Comment by mknyszek** [comment] 2021-04-13 16:50
I think it would be useful to get more information about what the behavior is that you expect in this scenario.

**Comment by mknyszek** [comment] 2021-04-13 16:50
Also, is this `windows/386`? `win32` could technically also mean `windows/arm`.

**Comment by zhaoya881010** [comment] 2021-04-14 00:40
windows/386,i need NoInheritHandles set true and Redirection stdout,stderr to file.

**Comment by networkimprov** [comment] 2021-05-15 21:52
cc @alexbrainman @mattn @zx2c4

**Comment by zx2c4** [comment] 2021-05-15 22:01
This is intended behavior. Everything is working as expected. There is no bug here.

HOWEVER, if what you're looking for is that handles you don't specify aren't accidentally leaked to the child process, that will be the case in Go 1.17.

So: you can probably close this bug, and just wait til 1.17 to get the behavior you desire. I agree 1.16's semantics are worrisome, and understand why you would want this, which is why it's been changed. But for 1.16, that's how it is.

**Comment by zhaoya881010** [comment] 2021-05-20 07:44
@zx2c4 ok，expecting 1.17.

**Comment by qmuntal** [comment] 2023-06-26 14:41
Can confirm this is working as expected, the child process can't write its output to `stdout` if it is not inherited.

**Closed by qmuntal** 2023-06-26 14:41 UTC
Labels: OS-Windows, NeedsInvestigation
