### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by Gituser143** [golang/go#38323] opened 2020-04-09 09:49 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.8 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
The issue is with documentation of functions in the strings package.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build282555768=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Read the package strings documentation on https://golang.org/pkg/strings/ 

### What did you expect to see?
Functions having arguments along with their types. A complete and accurate function definition.

### What did you see instead?
19 functions have a first argument of type string, but do not show the type in the function declaration. These functions are:  
* func Contains(s, substr string) bool
* func ContainsAny(s, chars string) 
* func Count(s, substr string) int
* func EqualFold(s, t string) bool
* func HasPrefix(s, prefix string) bool
* func HasSuffix(s, suffix string) bool
* func Index(s, substr string) int
* func IndexAny(s, chars string) int
* func LastIndex(s, substr string) int
* func LastIndexAny(s, chars string) int
* func Replace(s, old, new string, n int) string
* func ReplaceAll(s, old, new string) string
* func Split(s, sep string) []string
* func SplitAfter(s, sep string) []string
* func SplitAfterN(s, sep string, n int) []string
* func SplitN(s, sep string, n int) []stringfunc ToValidUTF8(s, replacement string) string
* func TrimPrefix(s, prefix string) string
* func TrimSuffix(s, suffix string) string

**Comment by ALTree** [comment] 2020-04-09 10:36
Hi @Gituser143,

this is how type declaration work in Go. When you write:

```
var a, b int
```

both `a` and `b` are of type `int`. C also works this way: `int a, b;` declares both `a` and `b` of type `int`.

Function signatures are the same. `s, substr string` means that both `s` and `substr` are of type `string`. See https://tour.golang.org/basics/5 (and the tour in general) for an introduction to the language.

Closing here, since this is working as intended.

**Closed by ALTree** 2020-04-09 10:36 UTC

**Comment by Gituser143** [comment] 2020-04-09 10:41
Thank you at @ALTree for the clarification! I apologise for my confusion.
