### ISSUE TITLE
cmd/cgo: -godefs: incorrect output when using TAILQ_ENTRY

### ISSUE THREAD

**Issue by yoursunny** [golang/go#37479] opened 2020-02-26 19:52 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64

$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
</pre>

### Does this issue reproduce with the latest release?

Yes, this issue appears since Go 1.14, but did not happen with Go 1.13.8.

### What operating system and processor architecture are you using (`go env`)?

I have Ubuntu 18.04 on a server with Xeon Gold 6240 CPU.

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build148938248=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I am executing `go tool cgo -godefs x.go` command on the following input:

```go
// +build ignore

package demo

/*
#include <stdbool.h>
#include <stdint.h>
#include <sys/queue.h>

typedef struct A A;

typedef TAILQ_ENTRY(A) N;

struct A
{
  N n;
};

typedef struct B
{
  A* a;
} B;
*/
import "C"

type N C.N

type A C.A

type B C.B
```

### What did you expect to see?

I expect to see this output. This was the output from Go 1.13.8.

```go
// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs x.go

package demo

type N struct {
	Next	*A
	Prev	**A
}

type A struct {
	N N
}

type B struct {
	A *A
}
```

### What did you see instead?

I see this output instead. Notice that in `type B`, the variable `A` has type `*_Ctype_struct_A`, instead of the expected type `*A`.

```go
// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs x.go

package demo

type N struct {
	Next	*A
	Prev	**A
}

type A struct {
	N N
}

type B struct {
	A *_Ctype_struct_A
}
```

### Further information

It seems that this problem is correlated to `TAILQ_ENTRY` macro. If `type A` does not contain a variable of a type defined by this macro, the problem does not occur.

If I manually expand the macro into the snippet below, the problem persists.

```c
typedef struct N {
  struct A* tqe_next;
  struct A** tqe_prev;
} N;
// Go 1.14 does not work with this version.
```

However, if I remove `struct` like the snippet below, the problem disappears.

```c
typedef struct N {
  A* tqe_next;
  A** tqe_prev;
} N;
// Go 1.14 works with this version.
```

**Comment by ianlancetaylor** [comment] 2020-02-26 20:06
Standalone test case:

```Go
package demo

/*
typedef struct A A;

typedef struct {
	struct A *next;
	struct A **prev;
} N;

struct A
{
  N n;
};

typedef struct B
{
  A* a;
} B;
*/
import "C"

type N C.N

type A C.A

type B C.B
```

**Comment by ianlancetaylor** [comment] 2020-02-26 20:07
This is caused by https://golang.org/cl/181857 for issue #31891.

CC @letientai299

**Comment by ianlancetaylor** [comment] 2020-02-26 20:13
The `-godefs` option is not actually supported for anything other than its documented purpose of generating files in the syscall package.  I don't mind if somebody sends in a fix for this, but this is not a priority of the Go team.  Sorry.

I'll add that I'm honestly not sure how `-godefs` is expected to work in the presence of a combination of typedefs and direct struct references.

**Closed** 2020-03-30 18:45 UTC
Labels: NeedsInvestigation
