### ISSUE TITLE
net: BenchmarkTCP{4,6}ConcurrentReadWrite failures on freebsd-amd64-race with "read: connection reset by peer"

### ISSUE THREAD

**Issue by bcmills** [golang/go#45214] opened 2021-03-24 15:19 UTC
[2021-03-23T05:12:12-cd26192/freebsd-amd64-race](https://build.golang.org/log/f34e5cb6e8780c6683b5b18c614253e014cde91c)
[2021-03-23T04:23:52-0265b64/freebsd-amd64-race](https://build.golang.org/log/c20c7785f68276a2f1972b9b6a7a6cb6699ba2dd)

(See also #20960.)

CC @bradfitz @ianlancetaylor

These failures are both very recent, so I wonder if something has recently changed in the `net` package or the `freebsd-amd64-race` builders. (CC @golang/release)

**Comment by bcmills** [comment] 2021-03-24 15:20
#19229 also features `connection reset by fail` errors on FreeBSD. I wonder if it's related...

**Comment by ayang64** [comment] 2021-03-25 14:26
which version of freebsd?  i can't reproduce on `FreeBSD kiwi 14.0-CURRENT FreeBSD 14.0-CURRENT #5 main-n245559-d22883d71544: Sun Mar 21 16:51:44 EDT 2021     root@kiwi:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG  amd64`

**Comment by ayang64** [comment] 2021-03-25 14:29
also, are you running freebsd in a virtual machine for tests?

**Comment by bcmills** [comment] 2021-03-25 14:31
Looks like it's FreeBSD 12.0 of some flavor, on a GCE `n1-highcpu-16` VM:
https://github.com/golang/build/blob/d7600ec889c89d486672e9ccd1b30bab50c15047/dashboard/builders.go#L317-L324

@golang/release could probably get you more details.

**Comment by bcmills** [comment] 2021-03-25 14:32
The failure rate is not particularly high, so you may also need a lot of runs to reproduce the failure.

**Comment by ayang64** [comment] 2021-03-25 14:43
okay -- i just ran it on my local machine with `-count 100` without any failures.  i'll continue trying to reproduce and maybe try to isolate the commit that caused it.  i'll also try under 12.0.

**Comment by bcmills** [comment] 2021-03-25 14:46
There's one more in the logs today:
[2021-03-25T00:15:42-80157b5/freebsd-amd64-race](https://build.golang.org/log/6acb77d804f71a76904870d91bd57663c3e9e38e)

That's three in two days, and none that I can find before that. So the regression is probably very recent, whatever it is.

**Comment by bcmills** [comment] 2021-04-15 14:27
[2021-04-15T10:21:10-b1c4cc5/freebsd-amd64-race](https://build.golang.org/log/bf9a1b7b3fcfc1f4fdb7bd09053f0e4c71309931)
[2021-04-13T22:55:30-8c2a8b1/freebsd-amd64-race](https://build.golang.org/log/9082139fe65c966cdf15d77e23ae6d1ec433ef88)
[2021-04-13T13:56:21-13a4e8c/freebsd-amd64-race](https://build.golang.org/log/5377573c03fde7137cde307e38b33fe5379a0e41)
[2021-04-09T23:54:31-554d2c4/freebsd-amd64-race](https://build.golang.org/log/f7c658eff3ccf3b1c36fdf9c2a82f00594b86bbe)
[2021-04-08T15:03:31-283b020/freebsd-amd64-race](https://build.golang.org/log/af6fbb3b9d18b5f9af15ff4404d93ebfea2c9f2f)
[2021-04-08T02:17:22-5159c83/freebsd-amd64-race](https://build.golang.org/log/df7a5333f08b6ae163f0803a7702a4e6c42a65ae)
[2021-04-07T05:19:22-1395432/freebsd-amd64-race](https://build.golang.org/log/47a883e0def1d5bd2a2edd74752c7b68696ecd1e)
[2021-04-06T22:55:58-b084073/freebsd-amd64-race](https://build.golang.org/log/c60f86bc0983bf91471990cabe88e6f634176493)
[2021-04-03T01:45:13-93dcaba/freebsd-amd64-race](https://build.golang.org/log/e4f1aa8c74fd9a6b938dde28d5be5ad4fedcf979)
[2021-03-31T20:09:03-44dd066/freebsd-amd64-race](https://build.golang.org/log/75cf914cce1c3cc9a6ee4ac05e890ac405873704)
[2021-03-30T04:48:27-032ef4b/freebsd-amd64-race](https://build.golang.org/log/b28607db674dd72ce4d4de8ffa3951182d8deaa3)
[2021-03-29T19:16:20-9fbd0f6/freebsd-amd64-race](https://build.golang.org/log/f5402a3c045b08ec285b086dae333232834c3d2f)
[2021-03-29T18:46:32-67d565d/freebsd-amd64-race](https://build.golang.org/log/e935cd48c87287e7797fd5ab64f9dbe020a3e262)
[2021-03-25T19:55:42-7ce3617/freebsd-amd64-race](https://build.golang.org/log/69e5b12695397da88c0558dbedcb722a5bda9b3b)
[2021-03-25T19:21:34-2c8692d/freebsd-amd64-race](https://build.golang.org/log/8da324401ec40883543dde272acfeabd141277d2)
[2021-03-25T00:15:42-80157b5/freebsd-amd64-race](https://build.golang.org/log/6acb77d804f71a76904870d91bd57663c3e9e38e)
[2021-03-23T05:12:12-cd26192/freebsd-amd64-race](https://build.golang.org/log/f34e5cb6e8780c6683b5b18c614253e014cde91c)
[2021-03-23T04:23:52-0265b64/freebsd-amd64-race](https://build.golang.org/log/c20c7785f68276a2f1972b9b6a7a6cb6699ba2dd)

And nothing before that.

Marking as release-blocker for Go 1.17, since this appears to be a regression starting in March.

**Comment by ayang64** [comment] 2021-04-15 15:50
i still can't reproduce using `12.2-RELEASE-p6`.

it looks like a likely culprit is commit `6694a6888` though.

**Comment by ayang64** [comment] 2021-04-15 16:08
maybe grasping at straws but what if you update the test image to the latest release in the freebsd 12 line?

it seems like that'd be a good start.  it looks like you're running 12.0 but the latest production release is 12.2.

**Comment by ayang64** [comment] 2021-04-20 16:42
CC @golang/release

**Comment by toothrot** [comment] 2021-04-22 18:11
We're working on updating the builders soon in #44431. 
/cc @cagedmantis

**Comment by ayang64** [comment] 2021-04-26 15:24
looks like the default builder has been updated to 12.2.  is there a way to see the results?

**Comment by dmitshur** [comment] 2021-04-26 16:52
The new builder will be used in future testing (existing commit with test results are not automatically re-tested at this time), so its results will show up when new commits are pushed, or by explicitly sending a (possibly empty) change and requesting it via `TRY=freebsd-amd64-race` [SlowBot](https://golang.org/wiki/SlowBots) syntax.

**Comment by ayang64** [comment] 2021-05-06 10:55
has this error returned?  it looks like the freebsd builders have been relatively happy lately:

https://build.golang.org/

**Comment by toothrot** [comment] 2021-05-06 18:20
There doesn't seem to be any recent occurrences. Closing this issue.

**Closed by toothrot** 2021-05-06 18:20 UTC
Labels: NeedsInvestigation, OS-FreeBSD, release-blocker
