### ISSUE TITLE
x/build: "fatal error: out of memory" on windows-arm64-11

### ISSUE THREAD

**Issue by bcmills** [golang/go#51019] opened 2022-02-04 20:03 UTC
```
#!watchflakes
post <- builder ~ `^windows-arm64.*` && `fatal error: .*(?:out of memory|cannot allocate memory|The paging file is too small|Insufficient system resources)`
```

`greplogs --dashboard -md -l -e '(?ms)\Awindows-arm64.*^fatal error: out of memory' --since=2021-01-01`

[2022-02-04T14:02:15-25d2ab2-4afcc9f/windows-arm64-11](https://build.golang.org/log/9668eab0a7df64177fa0f413cad04bb327fd3e8c)

We may need to reconfigure the builder to either turn down the build/test parallelism or have more RAM available.

There is only one of these failures in the logs, but OTOH this builder has only ever run `x/tools` 12 times — so that's an 8% failure rate for this repo so far. 😅

(attn @golang/release)

**Comment by heschi** [comment] 2022-02-10 20:25
So far I'm not seeing any recurrences on what I assume is a much higher number of runs. We can keep an eye on it but right now I'm inclined to leave it alone.

**Comment by bcmills** [comment] 2022-02-11 16:23
> So far I'm not seeing any recurrences

Here's one running `x/crypto`:

`greplogs --dashboard -md -l -e '(?ms)\Awindows-arm64.*^fatal error: out of memory' --since=2022-02-05`

[2022-02-10T15:16:21-f4118a5-656d3f4/windows-arm64-11](https://build.golang.org/log/e2a37b4cd515a486b28d88c79882affe2635d209)

**Comment by bcmills** [comment] 2022-02-11 16:41
From the sheer number of packages that failed in each of those logs, I suspect that the parallelism is being set to high. What's the CPU-to-RAM ratio for this builder? (Maybe we could scale down `GOMAXPROCS`?)

**Comment by heschi** [comment] 2022-02-11 17:48
About 12G RAM for 8 cores, which seems pretty plausible to me? There isn't much precedent for tweaking `GOMAXPROCS` but I guess it's worth a try.

...are the crypto tests really that memory hungry though? Smells weird.

**Comment by dmitshur** [comment] 2022-02-11 17:55
[CL 381514](https://go.dev/cl/381514) for #50084 is recent precedent.

**Comment by bcmills** [comment] 2022-02-11 19:42
> are the crypto tests really that memory hungry though? Smells weird.

I agree. It looks like the actual OOM happened while recompiling packages in `std`, so probably more about compiler memory usage than test memory usage per se — but it's not clear to me why those packages would have been stale in the first place. 🤔

**Comment by bcmills** [comment] 2022-02-15 17:57
Unfortunately still OOMing even with GOMAXPROCS=4.

`greplogs --dashboard -md -l -e '(?ms)\Awindows-arm64.*^fatal error: out of memory' --since=2022-02-12`

[2022-02-15T14:54:27-76bd8ea/windows-arm64-11](https://build.golang.org/log/8a3182ac43fa3b762333e26c20de9af5787bdda9)

It's not at all clear to me why this is happening for the `-11` builder but not the `-10` builder — are they running on different host configurations?

**Comment by bcmills** [comment] 2022-02-15 17:59
Oh, hrm. The failure condition in that last one is a bit different — it OOMed during bootstrapping. 🤔

**Comment by bcmills** [comment] 2022-02-22 17:56
Three more OOMs over the weekend: one during bootstrapping in the main repo, and two during `x/tools` builds.

`greplogs --dashboard -md -l -e '(?ms)\Awindows-arm64.*^fatal error: .*(?:out of memory|cannot allocate memory)' --since=2022-02-16`

[2022-02-20T20:58:11-851ecea/windows-arm64-11](https://build.golang.org/log/2882309523ca5a32f9375dcc891d67636e5d3efa)
[2022-02-17T17:37:24-1f3875c-eaf0405/windows-arm64-11](https://build.golang.org/log/5855ba412c62a95c503820636e13bfdd8d0b34c4)
[2022-02-17T17:37:03-fd59bdf-eaf0405/windows-arm64-11](https://build.golang.org/log/579b7f8c1c575b98a6e71ddcf11cacf1dd164a65)

**Comment by bcmills** [comment] 2022-03-17 19:51
Still ongoing:

`greplogs --dashboard -md -l -e '(?ms)\Awindows-arm64.*^fatal error: .*(?:out of memory|cannot allocate memory)' --since=2022-02-23`

[2022-03-15T13:54:34-6799a7a-e475cf2/windows-arm64-11](https://build.golang.org/log/75bf338da59db4ab7b429db898d0e1327ee437af)
[2022-03-14T09:19:01-b769efc-ab0f761/windows-arm64-11](https://build.golang.org/log/c8a1571dd25352dff63165cb0ff2aa8da4c3dedb)
[2022-03-12T23:32:36-842d37e/windows-arm64-11](https://build.golang.org/log/ee5ea5b38927f2270988354072f3fe66d6eb21c3)

**Comment by heschi** [comment] 2022-03-17 19:55
We got bit twice during the release during bootstrap too. But I have no idea what to do about it.

**Comment by heschi** [comment] 2022-04-12 15:21
Yep, same qemu script. My best guess is some kind of OS issue/conflict with the emulator, but I have no idea how to prove or disprove that belief.

**Comment by bcmills** [comment] 2022-04-18 14:48
I wonder if this is somehow related to #49564, in that they both involve unexpected OOM failures on Windows.

**Comment by bcmills** [comment] 2022-04-18 14:49
@golang/release, is there a way to get the runtime to dump the current heap size when it fails with `cannot allocate memory`? It would probably be useful to know whether these OOMs are occurring due to wildly oversized heaps like the ones in #49564.

**Comment by bcmills** [comment] 2022-05-03 18:33
Here's a new (but likely related) failure mode:
```
windows-arm64-11 at a41e37f56a4fc2523ac88a76bf54ba3e45dcf533
…
Building Go cmd/dist using C:\workdir\go1.4
go tool compile: fork/exec C:\workdir\go1.4\pkg\tool\windows_arm64\compile.exe: The paging file is too small for this operation to complete.
```

**Comment by bcmills** [comment] 2022-05-03 18:59
The above failure mode suggests that there is a problem with the builder itself, not (just) #52433, since that failure occurred during bootstrapping using the old and venerable `go1.4` toolchain.

**Comment by bcmills** [comment] 2022-05-16 14:16
`greplogs -l -e '(?ms)\Awindows-arm64.*^fatal error: .*(?:out of memory|cannot allocate memory)' --since=2022-05-10`
[2022-05-16T06:55:54-86c51ed-9956996/windows-arm64-11](https://build.golang.org/log/feb2ec4baf2672f6b02eaccc2c5fa92bc9e16736)
[2022-05-14T23:57:43-335569b/windows-arm64-11](https://build.golang.org/log/16aebaa612353ffe8b6727c0c1bb8b047384f194)
[2022-05-14T23:57:43-0976fa6-335569b/windows-arm64-11](https://build.golang.org/log/3971a28b3229bf8c08e016cb9c90fec726917e59)
[2022-05-14T15:26:27-19156a5/windows-arm64-11](https://build.golang.org/log/3a16079b907c601a9993aa517d6e22c4e9e5b3bb)

**Comment by bcmills** [comment] 2022-06-23 14:45
@qmuntal, this is one of the issues I think should block promoting windows/arm64 to a first class port.

**Comment by bcmills** [comment] 2022-06-23 14:54
(You can find other `windows/arm64` bugs here:
https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen++in%3Atitle+label%3Aarch-arm64+label%3Aos-windows

However, it's not clear to me which of those should be blockers to making `windows/arm64` a first-class port; most of them have been mitigated by adding skips to the affected tests.)

**Comment by qmuntal** [comment] 2022-06-27 09:34
Tracking the new Microsoft-provided `windows/arm64` builder in #53541, which will hopefully fix this issue.

**Comment by dmitshur** [comment] 2022-07-21 21:40
It seems the "fatal error: out of memory" problem hasn't been reported here for a while. One possible explanation is that we've updated the host OS version where the qemu emulator is running (one of the `-11` builders was on a particularly old macOS 11.0, which lines up with https://github.com/golang/go/issues/51019#issuecomment-1096709897).

I'll close this issue optimistically; please feel free to reopen otherwise.

**Comment by dmitshur** [comment] 2022-07-21 22:08
The first page of the build dashboard shows 4 windows-arm64-11 fails that are all memory related, reopening.

**Comment by qmuntal** [comment] 2022-11-24 08:20
> Tracking the new Microsoft-provided `windows/arm64` builder in #53541, which will hopefully fix this issue.

I'm no longer sure this is a builder issue. I'm facing some OOM errors like this one `runtime: VirtualAlloc of 274879168512 bytes failed with errno=1455` while running a test that shouldn't need 274GB to run... There could be a problem in the runtime, will give it a try.

**Comment by qmuntal** [comment] 2024-01-29 15:35
> I'm no longer sure this is a builder issue. I'm facing some OOM errors like this one runtime: VirtualAlloc of 274879168512 bytes failed with errno=1455

I can't reproduce this issue anymore, and there hasn't been any memory-related issues since the windows/arm64 builders were deployed on Azure instead of using qemu on Mac. I propose to close this now.

**Comment by dmitshur** [comment] 2024-01-29 16:41
Thanks. If there's new evidence of this occurring, we can reopen or file a new issue.

**Closed by dmitshur** 2024-01-29 16:41 UTC
Labels: OS-Windows, Builders, NeedsInvestigation, arch-arm64
