### ISSUE TITLE
cmd/go: go test sometimes hangs if interrupted

### ISSUE THREAD

**Issue by karalabe** [golang/go#60220] opened 2023-05-16 08:28 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.20.4 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes, it started happening with 1.20.0, present on all versions since.

### What operating system and processor architecture are you using (`go env`)?

It happens on both linux/amd64 as well as macos/arm64

### What did you do?

Run `go test ./...`, wait for a bit and interrupt with Ctrl+C

### What did you expect to see?

I get control back of my shell.

### What did you see instead?

The shell hangs forever, no control given back.

Doing a SIGABRT produces the following dump:

```
SIGABRT: abort
PC=0x18f263710 m=0 sigcode=0

goroutine 0 [idle]:
runtime.pthread_cond_wait(0x10376c160, 0x10376c120)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/sys_darwin.go:502 +0x20 fp=0x16d063320 sp=0x16d0632f0 pc=0x102def120
runtime.semasleep(0xffffffffffffffff)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/os_darwin.go:66 +0x78 fp=0x16d063380 sp=0x16d063320 pc=0x102dcc828
runtime.notesleep(0x10376bf28)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/lock_sema.go:181 +0xc0 fp=0x16d0633c0 sp=0x16d063380 pc=0x102da6db0
runtime.mPark(...)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:1530
runtime.stopm()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:2334 +0x84 fp=0x16d0633f0 sp=0x16d0633c0 pc=0x102dd65d4
runtime.findRunnable()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:3007 +0xca8 fp=0x16d0634f0 sp=0x16d0633f0 pc=0x102dd80f8
runtime.schedule()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:3360 +0x98 fp=0x16d063530 sp=0x16d0634f0 pc=0x102dd9138
runtime.park_m(0x130?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:3511 +0x110 fp=0x16d063560 sp=0x16d063530 pc=0x102dd9650
runtime.mcall()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:192 +0x54 fp=0x16d063570 sp=0x16d063560 pc=0x102dffb64

goroutine 1 [semacquire, 1 minutes]:
runtime.gopark(0x103775780?, 0x1033ef8e0?, 0xa0?, 0x8?, 0x102da895c?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x140012757b0 sp=0x14001275790 pc=0x102dd2414
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:387
runtime.semacquire1(0x14001cbb8b8, 0x58?, 0x1, 0x0, 0x48?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/sema.go:160 +0x21c fp=0x14001275810 sp=0x140012757b0 pc=0x102de36dc
sync.runtime_Semacquire(0x140000021a0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/sema.go:62 +0x2c fp=0x14001275850 sp=0x14001275810 pc=0x102dfd95c
sync.(*WaitGroup).Wait(0x14001cbb8b0)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/sync/waitgroup.go:116 +0x78 fp=0x14001275870 sp=0x14001275850 pc=0x102e0de88
cmd/go/internal/work.(*Builder).Do(0x140007b1080, {0x103455498, 0x14000026068}, 0x140022d7080)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/cmd/go/internal/work/exec.go:220 +0x418 fp=0x14001275990 sp=0x14001275870 pc=0x1031eb168
cmd/go/internal/test.runTest({0x103455498, 0x14000026068}, 0x140000285d0?, {0x1400001e1d0?, 0x1400010ddd8?, 0x1?})
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/cmd/go/internal/test/test.go:888 +0x1818 fp=0x14001275d60 sp=0x14001275990 pc=0x10324b6c8
main.invoke(0x10375e840, {0x1400001e1c0, 0x2, 0x2})
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/cmd/go/main.go:225 +0x37c fp=0x14001275e40 sp=0x14001275d60 pc=0x1032617fc
main.main()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/cmd/go/main.go:179 +0x7cc fp=0x14001275f70 sp=0x14001275e40 pc=0x10326119c
runtime.main()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:250 +0x248 fp=0x14001275fd0 sp=0x14001275f70 pc=0x102dd1fe8
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14001275fd0 sp=0x14001275fd0 pc=0x102e02044

goroutine 2 [force gc (idle), 1 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000052fa0 sp=0x14000052f80 pc=0x102dd2414
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:387
runtime.forcegchelper()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:305 +0xb8 fp=0x14000052fd0 sp=0x14000052fa0 pc=0x102dd2258
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000052fd0 sp=0x14000052fd0 pc=0x102e02044
created by runtime.init.6
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:293 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000053760 sp=0x14000053740 pc=0x102dd2414
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgcsweep.go:319 +0x110 fp=0x140000537b0 sp=0x14000053760 pc=0x102dbf0e0
runtime.gcenable.func1()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:178 +0x28 fp=0x140000537d0 sp=0x140000537b0 pc=0x102db3b98
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000537d0 sp=0x140000537d0 pc=0x102e02044
created by runtime.gcenable
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:178 +0x74

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x272964?, 0x22bfcc?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000053f50 sp=0x14000053f30 pc=0x102dd2414
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x10376a6a0)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgcscavenge.go:400 +0x5c fp=0x14000053f80 sp=0x14000053f50 pc=0x102dbcefc
runtime.bgscavenge(0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgcscavenge.go:633 +0xac fp=0x14000053fb0 sp=0x14000053f80 pc=0x102dbd4dc
runtime.gcenable.func2()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:179 +0x28 fp=0x14000053fd0 sp=0x14000053fb0 pc=0x102db3b38
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000053fd0 sp=0x14000053fd0 pc=0x102e02044
created by runtime.gcenable
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:179 +0xb8

goroutine 5 [finalizer wait]:
runtime.gopark(0x0?, 0x10344d778?, 0x20?, 0xe0?, 0x2000000020?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000052580 sp=0x14000052560 pc=0x102dd2414
runtime.runfinq()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mfinal.go:193 +0x10c fp=0x140000527d0 sp=0x14000052580 pc=0x102db2c2c
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000527d0 sp=0x140000527d0 pc=0x102e02044
created by runtime.createfing
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mfinal.go:163 +0x84

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x44db5eba1a?, 0x3?, 0x1d?, 0xc1?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000054740 sp=0x14000054720 pc=0x102dd2414
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1275 +0xec fp=0x140000547d0 sp=0x14000054740 pc=0x102db5adc
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000547d0 sp=0x140000547d0 pc=0x102e02044
created by runtime.gcBgMarkStartWorkers
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1199 +0x28

goroutine 17 [GC worker (idle), 1 minutes]:
runtime.gopark(0x1037a16c0?, 0x1?, 0xa0?, 0x2c?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x1400004e740 sp=0x1400004e720 pc=0x102dd2414
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1275 +0xec fp=0x1400004e7d0 sp=0x1400004e740 pc=0x102db5adc
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400004e7d0 sp=0x1400004e7d0 pc=0x102e02044
created by runtime.gcBgMarkStartWorkers
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1199 +0x28

goroutine 33 [GC worker (idle)]:
runtime.gopark(0x44db5e373e?, 0x1?, 0xa2?, 0x66?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000586740 sp=0x14000586720 pc=0x102dd2414
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1275 +0xec fp=0x140005867d0 sp=0x14000586740 pc=0x102db5adc
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140005867d0 sp=0x140005867d0 pc=0x102e02044
created by runtime.gcBgMarkStartWorkers
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1199 +0x28

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x44db5e3356?, 0x3?, 0x17?, 0xa?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000054f40 sp=0x14000054f20 pc=0x102dd2414
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1275 +0xec fp=0x14000054fd0 sp=0x14000054f40 pc=0x102db5adc
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000054fd0 sp=0x14000054fd0 pc=0x102e02044
created by runtime.gcBgMarkStartWorkers
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1199 +0x28

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x44db5e279e?, 0x3?, 0x98?, 0x3?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000586f40 sp=0x14000586f20 pc=0x102dd2414
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1275 +0xec fp=0x14000586fd0 sp=0x14000586f40 pc=0x102db5adc
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000586fd0 sp=0x14000586fd0 pc=0x102e02044
created by runtime.gcBgMarkStartWorkers
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1199 +0x28

goroutine 35 [GC worker (idle), 1 minutes]:
runtime.gopark(0x447a0dc6c5?, 0x3?, 0x75?, 0x35?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000587740 sp=0x14000587720 pc=0x102dd2414
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1275 +0xec fp=0x140005877d0 sp=0x14000587740 pc=0x102db5adc
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140005877d0 sp=0x140005877d0 pc=0x102e02044
created by runtime.gcBgMarkStartWorkers
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1199 +0x28

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x1037a16c0?, 0x1?, 0x95?, 0x82?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000055740 sp=0x14000055720 pc=0x102dd2414
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1275 +0xec fp=0x140000557d0 sp=0x14000055740 pc=0x102db5adc
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000557d0 sp=0x140000557d0 pc=0x102e02044
created by runtime.gcBgMarkStartWorkers
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1199 +0x28

goroutine 18 [GC worker (idle)]:
runtime.gopark(0x44db5e35f1?, 0x3?, 0xcf?, 0x1c?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x1400004ef40 sp=0x1400004ef20 pc=0x102dd2414
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1275 +0xec fp=0x1400004efd0 sp=0x1400004ef40 pc=0x102db5adc
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400004efd0 sp=0x1400004efd0 pc=0x102e02044
created by runtime.gcBgMarkStartWorkers
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1199 +0x28

goroutine 9 [GC worker (idle), 1 minutes]:
runtime.gopark(0x1037a16c0?, 0x3?, 0x53?, 0x8b?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000055f40 sp=0x14000055f20 pc=0x102dd2414
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1275 +0xec fp=0x14000055fd0 sp=0x14000055f40 pc=0x102db5adc
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000055fd0 sp=0x14000055fd0 pc=0x102e02044
created by runtime.gcBgMarkStartWorkers
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1199 +0x28

goroutine 10 [GC worker (idle)]:
runtime.gopark(0x44db5e31df?, 0x1?, 0x63?, 0x27?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000582740 sp=0x14000582720 pc=0x102dd2414
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1275 +0xec fp=0x140005827d0 sp=0x14000582740 pc=0x102db5adc
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140005827d0 sp=0x140005827d0 pc=0x102e02044
created by runtime.gcBgMarkStartWorkers
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1199 +0x28

goroutine 11 [GC worker (idle)]:
runtime.gopark(0x44db5e2feb?, 0x3?, 0x85?, 0xf0?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000582f40 sp=0x14000582f20 pc=0x102dd2414
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1275 +0xec fp=0x14000582fd0 sp=0x14000582f40 pc=0x102db5adc
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000582fd0 sp=0x14000582fd0 pc=0x102e02044
created by runtime.gcBgMarkStartWorkers
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1199 +0x28

goroutine 12 [GC worker (idle)]:
runtime.gopark(0x44db5eb826?, 0x3?, 0xd?, 0x9d?, 0x0?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14000583740 sp=0x14000583720 pc=0x102dd2414
runtime.gcBgMarkWorker()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1275 +0xec fp=0x140005837d0 sp=0x14000583740 pc=0x102db5adc
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140005837d0 sp=0x140005837d0 pc=0x102e02044
created by runtime.gcBgMarkStartWorkers
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/mgc.go:1199 +0x28

goroutine 8813 [chan receive]:
runtime.gopark(0x14000660000?, 0x300000002?, 0x78?, 0xb8?, 0x102dfe90c?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x140020bb820 sp=0x140020bb800 pc=0x102dd2414
runtime.chanrecv(0x14000353d40, 0x0, 0x1)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/chan.go:583 +0x45c fp=0x140020bb8b0 sp=0x140020bb820 pc=0x102da1ebc
runtime.chanrecv1(0x140020bb938?, 0x102dfca34?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/chan.go:442 +0x14 fp=0x140020bb8e0 sp=0x140020bb8b0 pc=0x102da1a24
cmd/go/internal/test.(*runTestActor).Act(0x14000a61680, 0x14000026068?, {0x0?, 0x0?}, 0x14000afa2c0)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/cmd/go/internal/test/test.go:1147 +0x4c fp=0x140020bbd70 sp=0x140020bb8e0 pc=0x10324d47c
cmd/go/internal/work.(*Builder).Do.func2({0x103455498, 0x14000026068}, 0x14000afa2c0)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/cmd/go/internal/work/exec.go:143 +0x64c fp=0x140020bbf00 sp=0x140020bbd70 pc=0x1031ebbcc
cmd/go/internal/work.(*Builder).Do.func3()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/cmd/go/internal/work/exec.go:211 +0x98 fp=0x140020bbfd0 sp=0x140020bbf00 pc=0x1031eb378
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140020bbfd0 sp=0x140020bbfd0 pc=0x102e02044
created by cmd/go/internal/work.(*Builder).Do
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/cmd/go/internal/work/exec.go:197 +0x368

goroutine 9234 [select, 1 minutes, locked to thread]:
runtime.gopark(0x14002cd0fa0?, 0x2?, 0x88?, 0xe?, 0x14002cd0f9c?)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/proc.go:381 +0xe4 fp=0x14002cd0e30 sp=0x14002cd0e10 pc=0x102dd2414
runtime.selectgo(0x14002cd0fa0, 0x14002cd0f98, 0x0?, 0x0, 0x0?, 0x1)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/select.go:327 +0x690 fp=0x14002cd0f50 sp=0x14002cd0e30 pc=0x102de27b0
runtime.ensureSigM.func1()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/signal_unix.go:1000 +0x190 fp=0x14002cd0fd0 sp=0x14002cd0f50 pc=0x102df9770
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14002cd0fd0 sp=0x14002cd0fd0 pc=0x102e02044
created by runtime.ensureSigM
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/signal_unix.go:983 +0xf4

goroutine 9235 [syscall]:
runtime.sigNoteSleep(0xffffffffffffffff)
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/os_darwin.go:123 +0x20 fp=0x14003064f90 sp=0x14003064f50 pc=0x102dcca80
os/signal.signal_recv()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/sigqueue.go:149 +0x2c fp=0x14003064fb0 sp=0x14003064f90 pc=0x102dfe1bc
os/signal.loop()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/os/signal/signal_unix.go:23 +0x1c fp=0x14003064fd0 sp=0x14003064fb0 pc=0x102f32a6c
runtime.goexit()
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14003064fd0 sp=0x14003064fd0 pc=0x102e02044
created by os/signal.Notify.func1.1
	/opt/homebrew/Cellar/go/1.20.4/libexec/src/os/signal/signal.go:151 +0x2c

r0      0x104
r1      0x0
r2      0x5b900
r3      0x0
r4      0x0
r5      0xa0
r6      0x0
r7      0x0
r8      0x16d063208
r9      0x0
r10     0x10376c138
r11     0x120000001202
r12     0x1200
r13     0x0
r14     0x1200
r15     0x120000001200
r16     0x131
r17     0x1ef234ed8
r18     0x0
r19     0x10376c120
r20     0x10376c160
r21     0x1ea70dc20
r22     0x0
r23     0x0
r24     0x5b900
r25     0x5e201
r26     0x5e300
r27     0xffffffffffffffa0
r28     0x10376aba0
r29     0x16d063280
lr      0x18f2a0574
sp      0x16d0631f0
pc      0x18f263710
fault   0x18f263710
```

**Comment by bcmills** [comment] 2023-05-16 13:58
Coincidentally, I filed what I think is exactly the same bug just yesterday. 😅

**Comment by bcmills** [comment] 2023-05-16 13:58
Duplicate of #60203

**Closed by bcmills** 2023-05-16 13:58 UTC
