### ISSUE TITLE
sync: Add Len() method to sync.Map

### ISSUE THREAD

**Issue by kelwang** [golang/go#25112] opened 2018-04-26 18:57 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.10.1

### What did you do?
Try to find a easy way to get the length of sync.Map. Currently, the only way to call the Range func

### What did you expect to see?
func (m *Map) Len() int

**Comment by adamdecaf** [comment] 2018-04-26 18:59
Duplicate of https://github.com/golang/go/issues/22247 ?

**Comment by ianlancetaylor** [comment] 2018-04-26 19:00
Yes, closing as dup.

**Closed by ianlancetaylor** 2018-04-26 19:00 UTC
