### ISSUE TITLE
cmd/pprof: go tool doesn't accept Ctrl-f while pprof does

### ISSUE THREAD

**Issue by ogiekako** [golang/go#37482] opened 2020-02-26 20:48 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/okakeigo/Library/Caches/go-build"
GOENV="/Users/okakeigo/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/okakeigo"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/okakeigo/homebrew/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/okakeigo/homebrew/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s1/qwdmhqf13t9771ccdtlphl6m0000gn/T/go-build512674066=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.14 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.14
uname -v: Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76
lldb --version: lldb-1100.0.30.12
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
gdb --version: GNU gdb (GDB) 8.2.1
</pre></details>

### What did you do?

Run `go tool pprof some_pprof_sample.pb.gz`.

### What did you expect to see?

In the interactive tool, Ctrl-f and Ctrl-b should be usable to move cursor forward and backward.

### What did you see instead?

Ctrl-f doesn't work. Ctrl-b, Ctrl-p, Ctrl-n don't work either.
Arrow keys, Ctlr-a and Ctrl-e work though.

This symptom doesn't happen if I run `pprof some_pprof_sample.pb.gz` instead.

**Comment by hyangah** [comment] 2020-03-06 16:19
Duplicate of #27147

**Closed by hyangah** 2020-03-06 16:19 UTC
Labels: NeedsInvestigation
