### ISSUE TITLE
cmd/list: getting "no matching versions for query 'latest'" and "invalid: go.mod" errors

### ISSUE THREAD

**Issue by Dentrax** [golang/go#46513] opened 2021-06-02 07:47 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/furkan.turkal/Library/Caches/go-build"
GOENV="/Users/furkan.turkal/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/furkan.turkal/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/furkan.turkal/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/furkan.turkal/go/src/config-admission-webhook/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nq/vxjjn3311fg4q263qsxrghpcpzgp66/T/go-build1047240835=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```
$ go list -mod=mod -u -m -json all
```

### What did you expect to see?

It should print out JSON output?

### What did you see instead?

```
go list -m: loading module retractions for github.com/coreos/go-systemd@v0.0.0-20190321100706-95778dfbb74e: no matching versions for query "latest"
go list -m: loading module retractions for gopkg.in/asn1-ber.v1@v1.0.0-20181015200546-f715ec2f112d: version "v1.5.3" invalid: go.mod has non-....v1 module path "github.com/go-asn1-ber/asn1-ber" at revision v1.5.3
go list -m: loading module retractions for gopkg.in/cheggaaa/pb.v1@v1.0.25: version "v1.0.29" invalid: go.mod has non-....v1 module path "github.com/cheggaaa/pb" at revision v1.0.29
go list -m: loading module retractions for gopkg.in/fsnotify.v1@v1.4.7: version "v1.4.9" invalid: go.mod has non-....v1 module path "github.com/fsnotify/fsnotify" at revision v1.4.9
```

<details><summary>My <code>go.mod</code> File</summary><br><pre>
module foo.com/bar/baz

go 1.14

// fixes _ "github.com/spf13/viper/remote" import problem
// replace github.com/ugorji/go/codec v0.0.0-20190204201341-e444a5086c43 => github.com/ugorji/go v1.1.4

require (
	cloud.google.com/go v0.54.0 // indirect
	github.com/aws/aws-sdk-go v1.29.23 // indirect
	github.com/elazarl/goproxy v0.0.0-20200310082302-296d8939dc5a // indirect
	github.com/elazarl/goproxy/ext v0.0.0-20200310082302-296d8939dc5a // indirect
	github.com/fsnotify/fsnotify v1.4.9 // indirect
	github.com/gogo/protobuf v1.3.1 // indirect
	github.com/golang/mock v1.4.4
	github.com/google/gofuzz v1.1.0 // indirect
	github.com/googleapis/gnostic v0.4.0 // indirect
	github.com/gopherjs/gopherjs v0.0.0-20200217142428-fce0ec30dd00 // indirect
	github.com/gruntwork-io/gruntwork-cli v0.6.1 // indirect
	github.com/gruntwork-io/terratest v0.26.5
	github.com/hashicorp/consul/api v1.8.1
	github.com/hashicorp/vault/api v1.0.4
	github.com/imdario/mergo v0.3.8 // indirect
	github.com/jmespath/go-jmespath v0.3.0 // indirect
	github.com/kr/text v0.2.0 // indirect
	github.com/mitchellh/go-homedir v1.1.0
	github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e // indirect
	github.com/pelletier/go-toml v1.6.0 // indirect
	github.com/pkg/errors v0.9.1
	github.com/prometheus/client_golang v1.5.1
	github.com/sirupsen/logrus v1.5.0
	github.com/smartystreets/assertions v1.0.1 // indirect
	github.com/spf13/cast v1.3.1
	github.com/spf13/cobra v1.0.0
	github.com/spf13/jwalterweatherman v1.1.0 // indirect
	github.com/spf13/viper v1.7.1
	github.com/stretchr/testify v1.6.1
	github.com/urfave/cli v1.22.3 // indirect
	golang.org/x/crypto v0.0.0-20200311171314-f7b00557c8c4 // indirect
	gopkg.in/check.v1 v1.0.0-20200227125254-8fa46927fb4f // indirect
	gopkg.in/ini.v1 v1.54.0 // indirect
	gopkg.in/yaml.v2 v2.2.8
	k8s.io/api v0.17.4
	k8s.io/apimachinery v0.17.4
	k8s.io/client-go v0.17.4
	k8s.io/utils v0.0.0-20200229041039-0a110f9eb7ab // indirect
	modernc.org/strutil v1.0.0
	sigs.k8s.io/yaml v1.2.0
)
</pre></details>

**Comment by seankhliao** [comment] 2021-06-02 14:22
Duplicate of #30755

**Closed by seankhliao** 2021-06-02 14:22 UTC
