### ISSUE TITLE
proposal: Go 2: Make functions satisfy interface

### ISSUE THREAD

**Issue by pjebs** [golang/go#35362] opened 2019-11-05 01:45 UTC
If we have an interface which prescribes 1 function, the proposal is for the interface to be satisfied by a closure with the same signature.

An interface:
```
type Rander interface {
    Rand(seed float64) float64
}
```

A function:
```
func Generator(r Rander) {
    ...
}
```

Currently, `r` must be a struct or pointer to a struct. It would be nice to provide as an argument:
```
Generator(func(s float64) float64 {})
```
Obviously this is not backward compatible, since inside Generator may use the `reflect` package and expect `r` to be a struct or pointer to a struct which would be a reasonable assumption under Go1.

I think with this change the benefits are that in many cases you don't have to wrap a function in a struct for the same of making it a struct. This could potentially cleanup code some places.

**Comment by ianlancetaylor** [comment] 2019-11-05 03:23
Duplicate of #21670.

**Closed by ianlancetaylor** 2019-11-05 03:23 UTC
Labels: Proposal
