### ISSUE TITLE
x/vgo: vgo build fails to import dependency

### ISSUE THREAD

**Issue by flicaflow** [golang/go#23956] opened 2018-02-20 20:42 UTC
### What version of Go are you using (`go version`)?
go version go1.10 linux/amd64 vgo:2018-02-20.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
running "vgo build" on a minimal Hello World which imports "gonum.org/v1/plot" https://play.golang.org/p/1VaQDlHOtXP results in following output:

.

### What did you expect to see?
Just a successfull vgo build run

### What did you see instead?
Following output and no dependencies listed in go.mod:
vgo: resolving import "gonum.org/v1/plot"
vgo: finding gonum.org/v1/plot (latest)
vgo: adding gonum.org/v1/plot v0.0.0-20171127212114-feab214a240f
vgo: resolving import "github.com/golang/freetype"
vgo: finding github.com/golang/freetype (latest)
vgo: adding github.com/golang/freetype v0.0.0-20170609003504-e2365dfdc4a0
vgo: resolving import "golang.org/x/image/math/fixed"
vgo: finding golang.org/x/image (latest)
vgo: adding golang.org/x/image v0.0.0-20171214225156-12117c17ca67
vgo: resolving import "github.com/llgcode/draw2d"
vgo: finding github.com/llgcode/draw2d (latest)
vgo: adding github.com/llgcode/draw2d v0.0.0-20180124133339-274031cf2abe
vgo: resolving import "bitbucket.org/zombiezen/gopdf/pdf"
findRepo: XML syntax error on line 11: expected attribute name in element
findRepo: XML syntax error on line 13: expected attribute name in element
findRepo: XML syntax error on line 14: expected attribute name in element
vgo: import "bitbucket.org/flicaflow/vgobug" ->
        import "gonum.org/v1/plot" ->
        import "gonum.org/v1/plot/vg/draw" ->
        import "gonum.org/v1/plot/vg/vgpdf" ->
        import "bitbucket.org/zombiezen/gopdf/pdf": XML syntax error on line 11: expected attribute name in element
vgo: resolving import "github.com/ajstarks/svgo"
vgo: finding github.com/ajstarks/svgo (latest)
vgo: adding github.com/ajstarks/svgo v0.0.0-20171111115224-f9be02f22f2c

### Context
The usual go get gonum.org/v1/plot works flawless and go build produces runnable binaries. Hence I would think that probleme here lies on the side of vgo not beeing able to discover the gopdf/pdf dependency

**Comment by kardianos** [comment] 2018-02-22 18:27
Duplicate of #23950 .

**Closed by kardianos** 2018-02-22 18:27 UTC
