### ISSUE TITLE
package elliptic questions

### ISSUE THREAD

**Issue by hongyuefan** [golang/go#37999] opened 2020-03-22 16:15 UTC
### What version of Go are you using (`go version`)?

go version go1.14.1 windows/amd64

### What operating system and processor architecture are you using (`go env`)?

windows

### What did you do?

hi，its about ScalarMult(x1, y1 *big.Int, k []byte) (x, y *big.Int) ；

for example ：

I have a point on ellipse.  ( x , y ).

1. x1 , y1 :=  ScalarMult( x , y , g) 

2. gm = big.NewInt(0).ModInverse(g, elliptic.Params().P)   //gMod = [g-1 Mod P]
   
    x2,y2 := ScalarMult(x1 , y1 ,  gm)

because   g * gm mod p = 1; so (x2, y2) should equal to (x , y) , but its not.

### What did you expect to see?

i think its should be equal .

**Comment by ALTree** [comment] 2020-03-22 19:57
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-03-22 19:57 UTC
