### ISSUE TITLE
wiki: wrong/outdated instructions on the Ubuntu page

### ISSUE THREAD

**Issue by williambanks** [golang/go#19654] opened 2017-03-22 06:18 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8

### What operating system and processor architecture are you using (`go env`)?
Ubuntu Linux 16.10

### What did you do?
Followed the readme

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Golang 1.8 as a package.

### What did you see instead?
Your instructions appear to be installing LXD PPA repo and then installing golang 1.6 from the universe repository.

>sudo add-apt-repository ppa:ubuntu-lxc/lxd-stable
sudo apt-get update
sudo apt-get install golang

That's just wrong.
The bottom of the page instructions work alright.
But if you have a PPA you should update the instructions and if you don't have a PPA (I couldn't find one), then you should remove those instructions.

Thanks!

**Comment by davecheney** [comment] 2017-03-22 06:26
I checked the readme in the repository and didn't find a reference to a ppa. Can you please link to the instructions you are following.

**Comment by dominikh** [comment] 2017-03-22 06:32
https://github.com/golang/go/wiki/Ubuntu is one such place referencing the lxd-stable PPA.

**Comment by williambanks** [comment] 2017-03-22 06:32
Ohh whoops, sorry I'm just exhausted it's not the README it's a wiki page linked to from the wiki.
https://github.com/golang/go/wiki/Ubuntu

**Comment by davecheney** [comment] 2017-03-22 06:37
That page is all sorts of wrong. My vote would be to delete it, but
@bradfitz abhors broken links. I'm not sure what to suggest to fix it.

I recommend using the tarball from https://golang.org/dl as it is extremely
well tested.

**Comment by josharian** [comment] 2017-03-22 06:48
@davecheney just delete all its contents instead, and leave a note pointing to /dl?

**Comment by williambanks** [comment] 2017-03-22 06:52
Ok so for those of us who want to put 1.8 on using package management in Ubuntu, what are the current options then?

**Comment by williambanks** [comment] 2017-03-22 06:52
Also it's not all wrong, the bottom half is correct and actually rather important info.

**Comment by davecheney** [comment] 2017-03-22 06:59
No, that's the most incorrect, especially the part about setting GOROOT.

**Comment by williambanks** [comment] 2017-03-22 07:02
I have to tell you it appears to be working here.  What part is incorrect because 
$ go version
go version go1.8 linux/amd64

$ echo $GOROOT
/usr/local/go

These seem ok to me.

**Comment by davecheney** [comment] 2017-03-22 07:08
It's outdated advise we're trying hard to erase from the Go community
conciousness.
https://dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really

**Comment by williambanks** [comment] 2017-03-22 07:20
Ok, been awhile since I actually installed it.

**Comment by davecheney** [comment] 2017-03-22 07:28
I think this is probably a duplicate of
https://github.com/golang/go/issues/18580

**Comment by bradfitz** [comment] 2017-03-22 17:09
"Fixed": https://github.com/golang/go/wiki/Ubuntu

**Closed by bradfitz** 2017-03-22 17:09 UTC
Labels: Documentation
