### ISSUE TITLE
x/build: add a Windows ARM32 builder

### ISSUE THREAD

**Issue by zx2c4** [golang/go#46492] opened 2021-06-01 16:52 UTC
Per https://github.com/golang/go/issues/42604#issuecomment-848870326 and https://github.com/golang/go/issues/42604#issuecomment-849186123, my builder will be decommissioned quite soon. This issue is to track spinning up of a builder on Google infrastructure, using the new ARM64 systems to run `GOOS=windows GOARCH=arm GOARM=7`. My builder was just running the 32-bit tests on the normal 64-bit OS. The replacement builder can do the same. There shouldn't be much work to do for this, as it's already been done for #42604.

CC @toothrot @dmitshur @cagedmantis

**Comment by bcmills** [comment] 2021-11-10 19:37
Duplicate of #47019?

**Comment by dmitshur** [comment] 2021-11-25 01:52
Indeed. (I missed the earlier notification.) Closing this one.

**Closed by dmitshur** 2021-11-25 01:52 UTC
Labels: Builders, NeedsInvestigation, new-builder
