### ISSUE TITLE
godoc should format interface types more like other types, displaying methods individually

### ISSUE THREAD

**Issue by cpcallen** [golang/go#20326] opened 2017-05-11 10:36 UTC
In e.g. [the documentation for the `reflect` package](https://golang.org/pkg/reflect/), concrete types like `Value` have their methods listed and documented individually, while interface types like `Type` do not, but force the reader to grovel through the actual source code of interface to find the methods declared on the type.  This is a great inconvenience to the reader, particularly because as a consequence the interface type's methods are not listed in the table of contents.

It seems particularly egregious in cases like `reflect.Type` where the concrete types that fulfil the interface are all unexported, and the user is unlikely to be creating more.  The fact that `Type` is an interface is of no real interest to the reader, and should not affect the format in which the documentation is presented.

**Comment by jimmyfrasche** [comment] 2017-05-11 14:04
duplicate of #5860

**Comment by cpcallen** [comment] 2017-05-11 15:09
Drat, didn't see that, despite searching for it.  Maybe I was looking only for bugs tagged 'documentation', but I guess it really is a bug against godoc functionality rather than documentation...  Sorry!

**Comment by ALTree** [comment] 2017-05-11 20:01
Looks like we can close this (we prefer to avoid duplicate issues and this indeed looks like a dup of #5860). Please comment if I'm missing something and this should stay open. Thanks.

**Closed by ALTree** 2017-05-11 20:01 UTC
