### ISSUE TITLE
time.Format unexpected behavior for fraction of second with comma in layout

### ISSUE THREAD

**Issue by mencnert** [golang/go#48746] opened 2021-10-02 17:41 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.17.1 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tm/.cache/go-build"
GOENV="/home/tm/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/tm/.asdf/installs/golang/1.17.1/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tm/.asdf/installs/golang/1.17.1/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/tm/.asdf/installs/golang/1.17.1/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/tm/.asdf/installs/golang/1.17.1/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/tm/devel/test/sof/timeformat/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build609773379=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

From go version 1.17 time supports comma for Format and Parse but it is not working as expected for Format.

https://github.com/golang/go/blob/8ac5cbe05d61df0a7a7c9a38ff33305d4dcfea32/src/time/format.go#L284

```
t := time.Date(0,1,1,0,0,5,123000000, time.UTC)
t.Format("05,999")
```

### What did you expect to see?

05,123 // with comma

### What did you see instead?

05.123 // with dot

**Comment by seankhliao** [comment] 2021-10-02 18:26
Duplicate of #48037

**Closed by seankhliao** 2021-10-02 18:26 UTC
