### ISSUE TITLE
os: spurious TestDirFS failures due to directory mtime skew on Windows

### ISSUE THREAD

**Issue by bcmills** [golang/go#42637] opened 2020-11-16 16:00 UTC
https://storage.googleapis.com/go-build-log/f31194a9/windows-386-2008_061172ea.log:
```
--- FAIL: TestDirFS (0.35s)
    os_test.go:2690: TestFS found errors:
        testdata/simple: mismatch:
        	entry.Info() = simple IsDir=true Mode=drwxrwxrwx Size=0 ModTime=2020-11-16 02:32:02.0111083 +0000 GMT
        	file.Stat() = simple IsDir=true Mode=drwxrwxrwx Size=0 ModTime=2020-11-16 02:32:02.012085 +0000 GMT
        
FAIL
FAIL	os	2.635s
```

Marking as release-blocker for Go 1.16 because `DirFS` is a new API.

CC @rsc @robpike @alexbrainman @networkimprov @zx2c4

**Comment by ianlancetaylor** [comment] 2020-11-16 17:22
I don't understand why there is a directory `testdata/simple` at all.  Where is that coming from?

**Comment by bcmills** [comment] 2020-11-17 14:11
This failure occurred in a TryBot for [CL 270198](https://golang.org/cl/270198). I had thought the changes in that CL were unrelated to the failure, but apparently they are somehow actually the cause of it.

**Comment by aclements** [comment] 2020-12-22 18:49
Bump. @bcmills , perhaps you could clarify the problem here? IIUC, the CL this failed in added a testdata file, which caused the mod times in the `DirFS` test to disagree. But is this an issue with the API? With its implementation? With the test?

**Comment by bcmills** [comment] 2020-12-22 19:17
Looking at the implementation of the test, it's either a problem with the test itself, with the new `testing/fstest` package, or both.

It appears that `fstest.TestFS` assumes that no file or directory in the given `fs.FS` is changed in any way while the test is running, but then `os.TestDirFS` is running `TestFS` on the directory containing the `os/signal` package. That causes the test for the `os` package to fail if there are any concurrent changes in the `os/signal` package.

I don't know why the directory's `ModTime` was being changed at all in the CL at which this failure was observed; that may be a peripherally-related bug in `go run`.

However, I could quite easily imagine someone running `go test os` while concurrently editing an otherwise-unrelated source file in `os/signal` (such as a test function for that package), and in that situation I could easily envision `os.TestDirFS` spuriously failing.

If `os.TestDirFS` requires the property that the directory it is traversing does not change at all while the test is running, it should either have its own isolated subdirectory of `GOROOT/src/os/testdata`, or it should construct its own temporary directory for the duration of the test and run `fstest.TestFS` on that — not on the `signal` subdirectory.

**Comment by aclements** [comment] 2020-12-22 20:55
> It appears that `fstest.TestFS` assumes that no file or directory in the given `fs.FS` is changed in any way while the test is running

It seems like it would be hard for it *not* to assume this. Maybe it's worth documenting?

> I'm leaning toward this being a problem with `os.TestDirFS` proper.

I agree.

This also doesn't seem especially important, though. Would you object to dropping the release-blocker label?

**Comment by toothrot** [comment] 2021-01-07 19:14
@bcmills Do you still believe this is a release-blocker? Or is a documentation fix sufficient?

**Comment by bcmills** [comment] 2021-01-07 19:45
The test is new in this release. If we're adding new, fragile tests faster than we have time to clean them up, I think that's a serious problem for the overall health of the project.

So I still believe this should be a release-blocker — not because users of the release will notice it, but because it is a source of unplanned technical debt that otherwise has no backpressure.

**Comment by aclements** [comment] 2021-01-07 22:17
Thanks. That still leaves open the question of whether this just needs to be documented. Is it even possible for `fstest.TestFS` to avoid making this assumption? And if it's possible today, do we want to commit to it always being possible in the future? I'm pretty sure the answer to at least one of these is "no", but this is outside my wheelhouse.

**Comment by bcmills** [comment] 2021-01-07 22:23
I think it's probably fine to just document for `fstest.TestFS`, but I think we should also change `os.TestDirFS` to invoke that function on a directory that does not depend on the immutability of the source code for any other package — if for no other reason than to set a better example for users looking for usage examples in the standard library.

**Comment by bcmills** [comment] 2021-01-08 19:48
Failed again in https://storage.googleapis.com/go-build-log/7cac22f9/windows-amd64-2016_ae3be137.log, after the above CL was merged.

Still needs investigation to figure out whether there may be an issue with oversensitivity on Windows.

**Comment by bcmills** [comment] 2021-01-08 20:30
And again in https://storage.googleapis.com/go-build-log/aed5e690/windows-386-2008_9ca18079.log (CL 282712).

**Comment by bcmills** [comment] 2021-01-12 14:32
https://storage.googleapis.com/go-build-log/bbe7e803/windows-amd64-2016_62cda50a.log  (CL 278596)

**Comment by bcmills** [comment] 2021-01-12 15:12
This seems like enough failures to reveal a pattern. The spurious failures tend to be on Windows, and they fail due to the directory mtime varying by around 2ms.

From what I can tell, one of the mtimes comes from the `ftLastWriteTime` field of a [`BY_HANDLE_FILE_INFORMATION`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/ns-fileapi-by_handle_file_information) struct:
https://github.com/golang/go/blob/a505312c89a0468081173da3042de6ac8582a3ba/src/os/types_windows.go#L136-L138

The semantics of that field are documented as:
> For a directory, the structure specifies when the directory is created. If the underlying file system does not support the last write time, this member is zero (0).

The other mtime comes from the corresponding field of a [`WIN32_FIND_DATAW`](https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-win32_find_dataw) struct:
https://github.com/golang/go/blob/a505312c89a0468081173da3042de6ac8582a3ba/src/os/dir_windows.go#L24
https://github.com/golang/go/blob/a505312c89a0468081173da3042de6ac8582a3ba/src/os/dir_windows.go#L43

That field has the same documented semantics — so it's not at all clear to me why this test would be failing.

**Comment by bcmills** [comment] 2021-01-12 15:16
Oddly, the `syscall.win32finddata1` struct being passed to the `FindNextFileW` system call seems to be three fields short: it is missing the `dwFileType`, `dwCreatorType`, and `wFinderFlags` fields from the [`WIN32_FIND_DATAW`](https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-win32_find_dataw) structure.

Is that a secondary bug?

**Comment by bcmills** [comment] 2021-01-14 16:50
CL 283636:
https://storage.googleapis.com/go-build-log/a530ff4a/windows-amd64-2016_3b828049.log
https://storage.googleapis.com/go-build-log/a530ff4a/windows-386-2008_50b085fd.log

CL 283638:
https://storage.googleapis.com/go-build-log/f8f8609f/windows-amd64-2016_d6c1c380.log

I wonder why this test seems to fail in the TryBots so often but never (so far) on the builders..?

**Comment by bcmills** [comment] 2021-01-14 21:48
As expected, fixing the `syscall.win32finddata1` declaration does not fix the test flakes.

**Comment by alexbrainman** [comment] 2021-01-15 07:30
> That field has the same documented semantics — so it's not at all clear to me why this test would be failing.

I run your os.TestDirFS few times, and I cannot reproduce the bug. I am unfamiliar with all new packages, so it is difficult for me to suggest something.

But I noticed that

https://storage.googleapis.com/go-build-log/f31194a9/windows-386-2008_061172ea.log

complains about `testdata/simple` file. And the other 3 failures 

https://storage.googleapis.com/go-build-log/7cac22f9/windows-amd64-2016_ae3be137.log

https://storage.googleapis.com/go-build-log/aed5e690/windows-386-2008_9ca18079.log

https://storage.googleapis.com/go-build-log/bbe7e803/windows-amd64-2016_62cda50a.log

all complain about `dir` file. But i don't see either `testdata/simple` or `dir` directories tested here

```
c:\Users\a\dev\go\src>git diff
diff --git a/src/testing/fstest/testfs.go b/src/testing/fstest/testfs.go
index 2602bdf0cc..5ab8b98522 100644
--- a/src/testing/fstest/testfs.go
+++ b/src/testing/fstest/testfs.go
@@ -414,6 +414,7 @@ func (t *fsTester) checkStat(path string, entry fs.DirEntry)
 {
        }
        fentry = formatInfo(einfo)
        finfo = formatInfo(info)
+       fmt.Printf("%s\n", path)
        if fentry != finfo {
                t.errorf("%s: mismatch:\n\tentry.Info() = %s\n\tfile.Stat() = %s
\n", path, fentry, finfo)
        }

c:\Users\a\dev\go\src>go test -v -run=TestDirFS os
=== RUN   TestDirFS
doc.go
example_test.go
example_unix_test.go
internal
internal/pty
internal/pty/pty.go
sig.s
signal.go
signal_cgo_test.go
signal_linux_test.go
signal_plan9.go
signal_plan9_test.go
signal_test.go
signal_unix.go
signal_windows_test.go
pty
pty/pty.go
--- PASS: TestDirFS (1.08s)
PASS
ok      os      (cached)

c:\Users\a\dev\go\src>
```

Perhaps, if you could explain why failed logs list `testdata/simple` or `dir`, that would be helpful.

Another crazy idea. Perhaps there more than one `dir` directory gets created. So mtime of first and second `dir` directory differs.

Another crazy idea. There is some code that does os.Chdir during the test. Perhaps it interferes with TestDirFS.

Alex

**Comment by alexbrainman** [comment] 2021-01-15 07:47
> Oddly, the [`syscall.win32finddata1`](https://github.com/golang/go/blob/0e85fd7561de869add933801c531bf25dee9561c/src/syscall/types_windows.go#L388-L401) struct being passed to the `FindNextFileW` system call seems to be three fields short: it is missing the `dwFileType`, `dwCreatorType`, and `wFinderFlags` fields from the [`WIN32_FIND_DATAW`](https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-win32_find_dataw) structure.
> 
> Is that a secondary bug?

I don't think syscall.win32finddata1 needs correcting.

I have recent Mingw installed here. And I wrote little C program that uses dwFileType field. And the program fails to compile:

```
$ cat main.c
#include <stdio.h>
#include <windows.h>

int main()
{
        WIN32_FIND_DATA d;

        memset(&d, 0, sizeof(d));
        printf("cAlternateFileName=%s\n", d.cAlternateFileName);
        printf("dwFileType=%d\n", d.dwFileType);

        return 0;
}
$ /usr/bin/x86_64-w64-mingw32-gcc-win32 -o /tmp/a.exe main.c
main.c: In function 'main':
main.c:10:29: error: 'WIN32_FIND_DATA' {aka 'struct _WIN32_FIND_DATAA'} has no member named 'dwFileType'
   10 |  printf("dwFileType=%d\n", d.dwFileType);
      |                             ^
$
```

I also looked into Mingw include directory, and that is what I see in /usr/share/mingw-w64/include/winbase.h:

```C
  typedef struct _WIN32_FIND_DATAW {
    DWORD dwFileAttributes;
    FILETIME ftCreationTime;
    FILETIME ftLastAccessTime;
    FILETIME ftLastWriteTime;
    DWORD nFileSizeHigh;
    DWORD nFileSizeLow;
    DWORD dwReserved0;
    DWORD dwReserved1;
    WCHAR cFileName[MAX_PATH];
    WCHAR cAlternateFileName[14];
#ifdef _MAC
    DWORD dwFileType;
    DWORD dwCreatorType;
    WORD  wFinderFlags;
#endif
  } WIN32_FIND_DATAW, *PWIN32_FIND_DATAW, *LPWIN32_FIND_DATAW;
```

Not sure what _MAC stands for

```
$ grep _MAC * -rw
ddk/wdm.h:#ifdef _MAC
ddk/wdm.h:#endif /* _MAC */
minwinbase.h:#ifdef _MAC
minwinbase.h:#ifdef _MAC
$
```

I also looked in the older version of Mingw that I, probably, used for original code

```
typedef struct _WIN32_FIND_DATAW {
        DWORD dwFileAttributes;
        FILETIME ftCreationTime;
        FILETIME ftLastAccessTime;
        FILETIME ftLastWriteTime;
        DWORD nFileSizeHigh;
        DWORD nFileSizeLow;
#ifdef _WIN32_WCE
    DWORD dwOID;
#else
        DWORD dwReserved0;
        DWORD dwReserved1;
#endif
        WCHAR cFileName[MAX_PATH];
#ifndef _WIN32_WCE
        WCHAR cAlternateFileName[14];
#endif
} WIN32_FIND_DATAW,*PWIN32_FIND_DATAW,*LPWIN32_FIND_DATAW;
```

So I am not sure why https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-win32_find_dataw has these 3 new fields that we don't see.

Perhaps @zx2c4 has some idea.

Alex

**Comment by zx2c4** [comment] 2021-01-15 10:31
A long time ago, a tiny subset of win32 was ported to mac so that Microsoft could port office and other software. I think they even had a MSVC for mac very briefly too. It never flowered into the project you might dream about, but it did manage to clutter up the header files. `wFinderFlags` refers to the... Finder.

This means that @alexbrainman is right and the patch in question is incorrect.

**Comment by bcmills** [comment] 2021-01-15 14:09
@alexbrainman 

> Perhaps, if you could explain why failed logs list `testdata/simple` or `dir`, that would be helpful.

`dir` is [`GOROOT/src/os/testdata/dirfs/dir`](https://github.com/golang/go/tree/master/src/os/testdata/dirfs/dir), added in [CL 282452](https://golang.org/cl/282452).

> Another crazy idea. Perhaps there more than one `dir` directory gets created. So mtime of first and second `dir` directory differs.

Since `dir` is checked into the Go source tree, it seems implausible that it would be deleted and recreated _while the test is running_.

> Another crazy idea. There is some code that does `os.Chdir` during the test. Perhaps it interferes with `TestDirFS`.

Maybe? But that would imply that the `ftLastWriteTime` field contains something other than just “when the directory is created” as documented.

**Comment by egonelbre** [comment] 2021-01-15 14:25
Hmm, maybe this is relevant https://stackoverflow.com/a/36219780/192220?

> The modified date returned by FindNextFile is the cached value stored in the directory entry, not the always updated value stored in the MFT record (inode equivalent). This is for performance reasons, so the information for a whole directory can be obtained with a single read, rather than a read for each file.

**Comment by alexbrainman** [comment] 2021-01-18 09:21
> > Perhaps, if you could explain why failed logs list `testdata/simple` or `dir`, that would be helpful.
> 
> `dir` is [`GOROOT/src/os/testdata/dirfs/dir`](https://github.com/golang/go/tree/master/src/os/testdata/dirfs/dir), added in [CL 282452](https://golang.org/cl/282452).

Yes. I was using old Go commit.

Another idea. Perhaps this documentation is incorrect

https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-win32_find_dataw

> For a directory, the structure specifies when the directory is created.

I just tried this

```
C:\Users\Alex\AppData\Local\Temp\z>mkdir d

C:\Users\Alex\AppData\Local\Temp\z>dir
 Volume in drive C has no label.
 Volume Serial Number is 9012-A870

 Directory of C:\Users\Alex\AppData\Local\Temp\z

18/01/2021  08:04 PM    <DIR>          .
18/01/2021  08:04 PM    <DIR>          ..
18/01/2021  08:04 PM    <DIR>          d
               0 File(s)              0 bytes
               3 Dir(s)  253,536,374,784 bytes free

C:\Users\Alex\AppData\Local\Temp\z>echo abc > d\f

C:\Users\Alex\AppData\Local\Temp\z>dir d
 Volume in drive C has no label.
 Volume Serial Number is 9012-A870

 Directory of C:\Users\Alex\AppData\Local\Temp\z\d

18/01/2021  08:05 PM    <DIR>          .
18/01/2021  08:05 PM    <DIR>          ..
18/01/2021  08:05 PM                 6 f
               1 File(s)              6 bytes
               2 Dir(s)  253,536,174,080 bytes free

C:\Users\Alex\AppData\Local\Temp\z>dir
 Volume in drive C has no label.
 Volume Serial Number is 9012-A870

 Directory of C:\Users\Alex\AppData\Local\Temp\z

18/01/2021  08:04 PM    <DIR>          .
18/01/2021  08:04 PM    <DIR>          ..
18/01/2021  08:05 PM    <DIR>          d
               0 File(s)              0 bytes
               3 Dir(s)  253,535,977,472 bytes free

C:\Users\Alex\AppData\Local\Temp\z>
```

Perhaps directory mtime changes when files are written to it or similar.

And I would not be surprised if directory is written to even when you don't expect it. There are few system programs running on Windows that possible write to random directories. Like antiviruses. Or file indexing programs. They would be especially active around files that are currently touched.

Just another crazy idea.

Alex

**Comment by egonelbre** [comment] 2021-01-18 13:15
Maybe there's a way to setup fsnotify / ReadDirectoryChangesW for that folder to see when/whether something is writing to it?

**Comment by zx2c4** [comment] 2021-01-18 14:13
> Hmm, maybe this is relevant https://stackoverflow.com/a/36219780/192220?
> 
> > The modified date returned by FindNextFile is the cached value stored in the directory entry, not the always updated value stored in the MFT record (inode equivalent). This is for performance reasons, so the information for a whole directory can be obtained with a single read, rather than a read for each file.

This actually seems somewhat plausible. More generally, we're taking timestamps using two different APIs at two different times. I wouldn't be surprised if we're grappling with cache or synchronization issues.

If that's the case, then it's really a matter of deciding how we want to fix this. We could stare at this until we figure out how to introduce a filesystem synchronization point with win32. We could add some retry loops. We could decrease the granularity of the comparison on Windows. We could replace `.Stat` with enumerating timestamps in the parent directory so that the API used is the same.

**Comment by egonelbre** [comment] 2021-01-18 14:38
I found this test that writes to `testdata` folder. https://github.com/golang/go/blob/master/src/os/example_test.go#L237

**Comment by zx2c4** [comment] 2021-01-18 15:25
This fails immediately:

```c
#include <windows.h>
#include <assert.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
        WIN32_FIND_DATAA find_data;
        BY_HANDLE_FILE_INFORMATION file_info;
        DWORD written;
        HANDLE file;

        for (;;) {
                file = CreateFileA("a.txt", GENERIC_WRITE | GENERIC_READ, FILE_SHARE_WRITE | FILE_SHARE_READ, NULL, OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
                WriteFile(file, "hello go!\r\n", 11, &written, NULL);
                GetFileInformationByHandle(file, &file_info);
                FindClose(FindFirstFileA("a.txt", &find_data));
                CloseHandle(file);
                if (memcmp(&file_info.ftLastWriteTime, &find_data.ftLastWriteTime, sizeof(file_info.ftLastWriteTime))) {
                        printf("%llu != %llu\n", *(unsigned long long *)&file_info.ftLastWriteTime, *(unsigned long long *)&find_data.ftLastWriteTime);
                        exit(1);
                }
        }

        return 0;
}
```

Basically, `FindFirstFile` returns information sync'd back by the last `CloseHandle()`, not by the last `WriteFile()`.

Plenty of places in the Go tests write a file and then don't bother closing the handle, but let the garbage collector eventually get to it in the finalizer. So, `FindFirstFile` is returning the old results until this happens.

**Comment by zx2c4** [comment] 2021-01-18 15:52
> Change https://golang.org/cl/284142 mentions this issue: `os: call runtime.GC() before using FindFirstFile on Windows`

This didn't work at all. It looks like nothing else writes to those files anyway, in order to cause the problem.

I wonder if git is being shim'd by Defender that then keeps the file handle open somehow after the process has terminated?

**Comment by zx2c4** [comment] 2021-01-18 16:14
I've found that calling `FlushFileBuffers` after that call to `WriteFile` fixes it -- syncs the mtime back to the mft. We could ostensibly do that from the test. But I wonder if instead we should look to fixing this in the test harness itself. @cagedmantis @dmitshur - Any thoughts about adding some kind of file sync barrier after the git pull?

**Comment by bcmills** [comment] 2021-01-19 17:25
@egonelbre, `ExampleWriteFile` has no `// Output` comment, so it should not actually be executed — search for “Example functions without output comments” in https://tip.golang.org/pkg/testing/#hdr-Examples.

(If it were actually run, that would need to be fixed separately; see #28387 and #30316.)

**Comment by zx2c4** [comment] 2021-01-21 15:54
One way of "fixing" this would be to have `readdir` in `go/src/os/dir_windows.go` not use `newFileStatFromWin32finddata`, but rather do a fresh `os.Stat` on each entry as it enumerates. I'm pretty sure this would fix the problem with the test. But it also would make file enumeration a _lot_ less efficient. The performance boost of the MFT is one of the unique features NTFS has so it'd be a bummer to throw that all out. And why take a performance hit for everybody when we're just trying to fix this one test?

**Comment by bcmills** [comment] 2021-01-21 15:59
@zx2c4, the reproducer in https://github.com/golang/go/issues/42637#issuecomment-762317777 seems to be for a file, but the observed failures in the TryBots are all for directories. That makes me question whether the root cause in the TryBots actually matches the reproducer.

**Comment by zx2c4** [comment] 2021-01-21 16:01
> @zx2c4, the reproducer in [#42637 (comment)](https://github.com/golang/go/issues/42637#issuecomment-762317777) seems to be for a file, but the observed failures in the TryBots are all for directories. That makes me question whether the root cause in the TryBots actually matches the reproducer.

Nice observation! Thanks.

I'll play around and see what the behavior is like for directories.

**Comment by zx2c4** [comment] 2021-01-21 16:28
Alright, here's an analogous example reproducer for directories:

```c
#include <windows.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
	WIN32_FIND_DATAA find_data;
	BY_HANDLE_FILE_INFORMATION file_info;
	DWORD written;
	HANDLE file, dir;

	for (int i = 0;; ++i) {
		DeleteFileA("dir\\a.txt");
		RemoveDirectoryA("dir");
		CreateDirectoryA("dir", NULL);

		file = CreateFileA("dir\\a.txt", GENERIC_WRITE | GENERIC_READ, FILE_SHARE_WRITE | FILE_SHARE_READ, NULL, OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
		WriteFile(file, "hello go!\r\n", 11, &written, NULL); // Updates the mtime of parent directory
		CloseHandle(file);

		dir = CreateFileA("dir", GENERIC_READ | GENERIC_WRITE, FILE_SHARE_READ | FILE_SHARE_WRITE, NULL, OPEN_EXISTING, FILE_FLAG_BACKUP_SEMANTICS, NULL);
		GetFileInformationByHandle(dir, &file_info);

		FindClose(FindFirstFileA("dir", &find_data));

		CloseHandle(dir); // Closing the handle initiates a flush of the mtime. We put this _after_ FindFirstFileA to trigger the bug.
	
		if (memcmp(&file_info.ftLastWriteTime, &find_data.ftLastWriteTime, sizeof(file_info.ftLastWriteTime))) {
			printf("%d - %llu != %llu, diff = %llu\n", i, *(unsigned long long *)&file_info.ftLastWriteTime, *(unsigned long long *)&find_data.ftLastWriteTime, *(unsigned long long *)&file_info.ftLastWriteTime - *(unsigned long long *)&find_data.ftLastWriteTime);
			exit(1);
		}
	}

	return 0;
}
```

And here's the bug being triggered:

![trigger](https://user-images.githubusercontent.com/10643/105380287-ffbf7600-5c0d-11eb-84ac-d06a444bb3b5.gif)

**Comment by zx2c4** [comment] 2021-01-21 16:49
And to dispel the more wild theories about directory mtime, it only seems to impact the innermost directory and does not bubble up the entire tree:

```c
#include <windows.h>
#include <stdio.h>

unsigned long long mtime(const char *path)
{
	BY_HANDLE_FILE_INFORMATION file_info;
	HANDLE dir;

	dir = CreateFileA(path, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_FLAG_BACKUP_SEMANTICS, NULL);
	GetFileInformationByHandle(dir, &file_info);
	CloseHandle(dir);

	return *(unsigned long long *)&file_info.ftLastWriteTime;
}

int main(int argc, char *argv[])
{
	unsigned long long a1, b1, c1, a2, b2, c2;
	HANDLE file;
	DWORD written;

	DeleteFileA("a\\b\\c\\d.txt");
	RemoveDirectoryA("a\\b\\c");
	RemoveDirectoryA("a\\b");
	RemoveDirectoryA("a");
	CreateDirectoryA("a", NULL);
	CreateDirectoryA("a\\b", NULL);
	CreateDirectoryA("a\\b\\c", NULL);

	a1 = mtime("a");
	b1 = mtime("a\\b");
	c1 = mtime("a\\b\\c");

	Sleep(100);

	file = CreateFileA("a\\b\\c\\d.txt", GENERIC_WRITE | GENERIC_READ, FILE_SHARE_WRITE | FILE_SHARE_READ, NULL, OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
	WriteFile(file, "hello go!\r\n", 11, &written, NULL); // Updates the mtime of parent directory
	CloseHandle(file);

	a2 = mtime("a");
	b2 = mtime("a\\b");
	c2 = mtime("a\\b\\c");

	if (a1 != a2)
		printf("a: %llu != %llu, diff = %llu\n", a1, a2, a2 - a1);

	if (b1 != b2)
		printf("a\\b: %llu != %llu, diff = %llu\n", b1, b2, b2 - b1);
	
	if (c1 != c2)
		printf("a\\b\\c: %llu != %llu, diff = %llu\n", c1, c2, c2 - c1);

	return 0;
}
```

This returns:

![image](https://user-images.githubusercontent.com/10643/105383092-08657b80-5c11-11eb-9cc0-b87e89afa8fa.png)

**Comment by ianlancetaylor** [comment] 2021-01-23 00:54
As far as I can tell, this is not happening on the builders at all.  I can't find even one occurrence.  It is only happening on the trybots.  Why would that be?

**Comment by zx2c4** [comment] 2021-01-23 16:24
> As far as I can tell, this is not happening on the builders at all. I can't find even one occurrence. It is only happening on the trybots. Why would that be?

It looks like there are two paths in the builder (CC @dmitshur to confirm/deny) -- one that writes a "snapshot" and one that writes the actual Go source. It looks like these might be coming from very different places. In that case, I wonder if there's an effect on this snippet of the untarring code:

```go
                        if modTime.After(t0) {
                                // Clamp modtimes at system time. See
                                // golang.org/issue/19062 when clock on
                                // buildlet was behind the gitmirror server
                                // doing the git-archive.
                                modTime = t0
                        }
                        if !modTime.IsZero() {
                                if err := os.Chtimes(abs, modTime, modTime); err != nil && !loggedChtimesError {
                                        // benign error. Gerrit doesn't even set the
                                        // modtime in these, and we don't end up relying
                                        // on it anywhere (the gomote push command relies
                                        // on digests only), so this is a little pointless
                                        // for now.
                                        log.Printf("error changing modtime: %v (further Chtimes errors suppressed)", err)
                                        loggedChtimesError = true // once is enough
                                }
                        }
```

Maybe the mtime is 0 for the tarballs sent by the trybots, but not the other ones, and os.Chtimes is helping sync back the timestamp to the MFT a bit sooner.

**Comment by tklauser** [comment] 2021-01-25 12:25
Seen with https://golang.org/cl/285719 on the windows-386-2008 builder two times in a row:

https://storage.googleapis.com/go-build-log/9621fdf4/windows-386-2008_b484a55e.log
https://storage.googleapis.com/go-build-log/9621fdf4/windows-386-2008_7400918c.log

**Closed** 2021-01-25 15:13 UTC
Labels: NeedsInvestigation, OS-Windows, Testing, release-blocker
