### ISSUE TITLE
stringer: internal error: package "strconv" without types was imported from XXX

### ISSUE THREAD

**Issue by WittonBell** [golang/go#64813] opened 2023-12-20 08:17 UTC
### Go version

go version go1.21.4 windows/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\admin\AppData\Local\go-build
set GOENV=C:\Users\admin\AppData\Roaming\go\env  
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\admin\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\admin\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=G:/msys64/mingw64/lib/go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=G:\msys64\mingw64\lib\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.4
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=D:\Server\go.work
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\admin\AppData\Local\Temp\go-build2587774622=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

eitem.go:
```
package enums

//go:generate stringer -type=EItemSource
type EItemSource uint16

const (
	ItemSourceNone EItemSource = 0 + iota

	ItemSourceInit
)
```

run `go generate`, report error when already generated output file:
`
stringer: internal error: package "strconv" without types was imported from "enums"
eitem.go:3: running "stringer": exit status 1
`

so, it is not work fine if run `go generate` multiple times.

I remember old version(maybe go 1.1X) is work fine.

### What did you expect to see?

no error report and output normally.

### What did you see instead?

run `go generate`, report error when already generated output file:
`
stringer: internal error: package "strconv" without types was imported from "enums"
eitem.go:3: running "stringer": exit status 1
`

**Comment by mauri870** [comment] 2023-12-20 11:03
I was unable to reproduce this,  it is a Possible duplicate of https://github.com/golang/go/issues/52710. Can you try the steps provided in the issue and see if it fixes the problem for you? Thanks.

**Comment by WittonBell** [comment] 2023-12-20 13:54
@mauri870 I try `go clean -cache`, `go clean -modcache` and `go install golang.org/x/tools/cmd/stringer@latest`, then work fine.

I used `go install golang.org/x/tools/cmd/stringer` before, maybe not installed the latest version.

By the way, it's maybe better output filename with origin file append `_string`, for example, `XXX.go` output `XXX_string.go` when not specify output filename.

Thanks.

**Comment by mauri870** [comment] 2023-12-20 14:07
You can customize the output file with the `-output option`, per https://pkg.go.dev/golang.org/x/tools/cmd/stringer docs:

> The -type flag accepts a comma-separated list of types so a single run can generate methods for multiple types. The default output file is t_string.go, where t is the lower-cased name of the first type listed. It can be overridden with the -output flag.

I'm glad that fixed the issue for you, I'm closing this as a duplicate of the other issue.

**Comment by mauri870** [comment] 2023-12-20 14:07
Duplicate of https://github.com/golang/go/issues/52710

**Closed by mauri870** 2023-12-20 14:07 UTC
Labels: WaitingForInfo, NeedsInvestigation
