### ISSUE TITLE
x/website:Syntax highlighting in examples

### ISSUE THREAD

**Issue by alexsorinsky** [golang/go#44652] opened 2021-02-26 23:19 UTC
just add this simple pice of code into the site footer template (i believe that it is just one file):

```javascript
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/styles/darcula.min.css" />

<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/highlight.min.js"></script>
<script>
  document.querySelectorAll('pre')
    .forEach(function(el) {
      hljs.highlightBlock(el);
    })
</script>
```

and all the documentation will looks like:
![new](https://i.imgur.com/wPKpxvn.png)

instead of old ugly plain ```<pre>``` formatting:
![old](https://i.imgur.com/Sw0CPra.png)

**Comment by seankhliao** [comment] 2021-02-27 08:56
Duplicate of #13178

**Closed by seankhliao** 2021-02-27 08:56 UTC
