### ISSUE TITLE
x/website: The Go installation docs should mention the option to add $GOBIN to $PATH

### ISSUE THREAD

**Issue by Battlesheepu** [golang/go#66043] opened 2024-03-01 00:47 UTC
### What is the URL of the page with the issue?

https://go.dev/doc/install

### What is your user agent?

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0

### What did you do?

Successfully visited the Go docs for the installation process.

### What did you see happen?

I saw no mention of adding $GOBIN to $PATH, which is assumed for some of the packages from the Go project.

### What did you expect to see?

Many of the commands belonging to packages in the Go project repos (like [pkgsite](https://pkg.go.dev/golang.org/x/pkgsite/cmd/pkgsite), [bent](https://pkg.go.dev/golang.org/x/benchmarks@v0.0.0-20240227171823-6bceba257eed/cmd/bent#section-readme), [govulncheck](https://pkg.go.dev/golang.org/x/vuln#section-readme), among others) seem to assume that users have added  `$GOBIN` to their `$PATH`, providing usage instructions based on just that. 

Thing is, with the exclusion of docs for installing Go from source, I haven't seen this suggested or mentioned neither in the [installation docs](https://go.dev/doc/install) nor in the output of `go help install`.  

I strongly believe that, especially for people starting out with the language, it's not immediately obvious that those commands would be, by default, installed into `$GOBIN` - which, in my opinion, is not terribly problematic, as long as we get some kind of a hint regarding adding `$GOBIN` to the `$PATH`. This would also compliment the package documentation pretty nicely, with things working out of the box when following instructions in the aforementioned packages description.

I did have a short conversation in the [go-nuts Google group](https://groups.google.com/g/golang-nuts/c/DyGxsAV8Vis) about this before deciding to file an issue, so I do hope I'm not the only one that change would make sense to. In terms of the context of that discussion, I think a simple mention of the matter in the installation docs would probably go a long way. 

Thanks in advance!

**Comment by seankhliao** [comment] 2024-03-01 08:18
Duplicate of #44930

**Closed by seankhliao** 2024-03-01 08:18 UTC
Labels: Documentation, pkgsite, website
