### ISSUE TITLE
x/review/git-codereview: includes diff in CL description

### ISSUE THREAD

**Issue by wathiede** [golang/go#9658] opened 2015-01-22 05:57 UTC
Steps to reproduce.
1. Change a file.
2. git checkout -b test-branch
3. git commit -av -m "DO NOT REVIEW test in progress"
4. git codereview mail

See http://golang.org/cl/3174/ for an example.

I'm not doing `git codereview change` anywhere in there and maybe I should be. My lack of reading the directions aside, the tool should tell me if I'm doing the wrong thing.

If skipping the `git codereview change` is expected to work, I think there must be a bug in the auto-create change code path that is slurping the diff into the description.

**Comment by adg** [comment] 2015-01-23 03:34
That's weird. It must be something wrong with the pre-commit hook.

**Comment by cmarcelo** [comment] 2016-02-22 15:52
Couldn't reproduce the issue. Following the same steps I produced

https://go-review.googlesource.com/#/c/19816/

**Comment by ysmolsky** [comment] 2018-11-06 11:51
On a freshly installed repo (for which I did not have hooks) it returned following:
```
% git mail
remote: Processing changes: refs: 1, done
remote: ERROR: commit 4cca701: missing Change-Id in message footer
remote:
remote: Hint: to automatically insert a Change-Id, install the hook:
remote: f=`git rev-parse --git-dir`/hooks/commit-msg ; curl -Lo $f https://gerrit-review.googlesource.com/tools/hooks/commit-msg ; chmod +x $f
remote: and then amend the commit:
remote:   git commit --amend
remote: Finally, push your changes again
remote:
To https://go.googlesource.com/net
 ! [remote rejected] HEAD -> refs/for/master (commit 4cca701: missing Change-Id in message footer)
error: failed to push some refs to 'https://go.googlesource.com/net'
(running: git push -q origin HEAD:refs/for/master)
/Users/thorn/go/bin/git-codereview: exit status 1
```

When I had hooks installed then it produced this CL: https://go-review.googlesource.com/c/net/+/147738

Closing since cannot reproduce.

**Closed by ysmolsky** 2018-11-06 11:51 UTC
