### ISSUE TITLE
net:memory bomb

### ISSUE THREAD

**Issue by MichaelMonashev** [golang/go#19691] opened 2017-03-24 07:05 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8 linux/386

### What operating system and processor architecture are you using (`go env`)?
GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/michael/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_386"
GCCGO="gccgo"
GO386=""
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
Run this code: https://play.golang.org/p/rS6j01aiMf

### What did you expect to see?
Listening for new udp packets.

### What did you see instead?
Memory bomb. The program eats all free memory.

**Comment by davecheney** [comment] 2017-03-24 07:52
I'm sorry your program has an error on line 30. I'm going to close this as working as intended. 

We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.

**Closed by davecheney** 2017-03-24 07:52 UTC
