### ISSUE TITLE
x/build/env/openbsd: add OpenBSD 6.8 builder

### ISSUE THREAD

**Issue by bradfitz** [golang/go#35712] opened 2019-11-20 17:13 UTC
OpenBSD 6.6 is out:

https://www.openbsd.org/66.html

Update our GCE builders. (rather, add a builder)

Pending CL https://go-review.googlesource.com/c/build/+/176237 does most the work (but using pre-release 6.5 instead of 6.6).

Just need to build it, test it (with x/build/cmd/debugnewvm) and configure it if it works.

/cc @cagedmantis @dmitshur @bcmills

**Comment by 4a6f656c** [comment] 2020-01-04 12:32
Only OpenBSD 6.5 and 6.6 are currently supported releases - I'd suggest running builders for both of these versions and retiring the older ones.

**Comment by 4a6f656c** [comment] 2020-05-19 16:25
OpenBSD 6.7 has just been released - 6.6 and 6.7 are now the only currently supported releases. We really need to new builders up and retire the 6.2 and 6.4 builders...

**Comment by cagedmantis** [comment] 2020-05-21 14:12
@4a6f656c Thanks for the reminder. I will follow up on this soon.

**Comment by 4a6f656c** [comment] 2020-10-24 16:21
FWIW OpenBSD 6.8 has recently been released - 6.7 and 6.8 are now the only currently supported releases.

**Comment by dmitshur** [comment] 2020-11-06 16:41
In https://github.com/golang/go/issues/42237#issuecomment-723170549, @4a6f656c kindly offered to help by providing a script that produces a OpenBSD image, but someone with permissions on @golang/release team is needed to review the CLs and push/deploy the builder.

@cagedmantis You're currently assigned on this issue from before, do you still want to work on this and have the bandwidth to take it up? If so, I'll let you coordinate with Joel on the timing you prefer (perhaps the coming weeks, or maybe after Go 1.16 final is out), otherwise please feel free to un-assign so someone else can pick this up when they have an opportunity. Thanks.

**Comment by cagedmantis** [comment] 2020-11-06 16:50
@dmitshur I've removed myself as the assignee. Please feel free to work on this issue if you have the time. I will attempt to work on this issue in the future if time permits.

**Comment by dmitshur** [comment] 2020-11-06 16:56
@4a6f656c If things go well, I should have the bandwidth to review and deploy. If we run into issues that need more investigation, I might defer until after Go 1.16 is out. Please feel free to send a CL to x/build, and be set `KnownIssue` field to 35712 when adding the builder configuration. Thank you.

**Comment by 4a6f656c** [comment] 2020-11-09 16:36
@dmitshur - the script changes have landed and the images built for 386/amd64 work correctly locally. Please let me know if you hit any issues getting these running on GCE.

**Comment by dmitshur** [comment] 2020-11-12 19:09
Here are some failures I ran into while testing a new 64-bit OpenBSD 6.8 builder with `cmd/debugnewvm` on [CL 269577](https://golang.org/cl/269577):

```
$ debugnewvm -run-build=openbsd-amd64-68 -rev=b34b0aaf69349f060d3b03a06f520848964cb7eb
```

From one run:

```
##### ../test
# go run run.go -- fixedbugs/issue6703f.go
compilation succeeded unexpectedly
/tmp/workdir/go/test/fixedbugs/issue6703f.go:18: initialization loop:
	/tmp/workdir/go/test/fixedbugs/issue6703f.go:18: x refers to
	/tmp/workdir/go/test/fixedbugs/issue6703f.go:13: T.m refers to
	/tmp/workdir/go/test/fixedbugs/issue6703f.go:18: x

FAIL	fixedbugs/issue6703f.go	0.105s
2020/11/12 10:12:11 Failed: exit status 1
```

Here's another run:

```
##### ../test
# go run run.go -- fixedbugs/issue17588.go
compilation succeeded unexpectedly
/tmp/workdir/go/test/fixedbugs/issue17588.go:14: T is not a type

FAIL	fixedbugs/issue17588.go	0.166s
2020/11/12 10:33:21 Failed: exit status 1
```

At first glance, given the failures are sporadic, there's a chance this could somehow be related to #42542 (CC @bcmills).

I'll do some more testing, I just wanted to share the immediate results earlier. Specifically, I'll also try with Go 1.15 commits in addition to tip, in case there's a problem there.

**Comment by dmitshur** [comment] 2020-11-12 20:55
A recent tip commit has also passed on another run, so perhaps there's some intermittent problem.

I'll add this builder with a KnownIssue and without TryBots first, then we can decide how to proceed after we have more information from testing this builder on a wider set of commits.

**Comment by dmitshur** [comment] 2020-11-12 22:38
I've remembered all OpenBSD use `noTestDirAndNoReboot` dist test policy, so the existing builders never run the tests that have failed via `debugnewvm` above.

**Comment by dmitshur** [comment] 2020-12-10 20:02
Now that a fix for #42542 is available via syspatch (see https://github.com/golang/go/issues/42542#issuecomment-742594947), I've re-run the scripts in `x/build/env/openbsd-amd64` and `env/openbsd-386`.

The amd64 one was created without an error:

```
syncing disks... done
Archiving disk.raw... (this may take a while)
Done. GCE image is openbsd-amd64-gce.tar.gz.
```

But the 386 one failed at the end with:

```
syncing disks... done
panic: kernel diagnostic assertion "__mp_lock_held(&sched_lock, curcpu()) == 0" failed: file "/usr/src/sys/arch/i386/i386/ipifuncs.c", line 104
Stopped at      db_enter+0x4:   popl    %ebp
    TID    PID    UID     PRFLAGS     PFLAGS  CPU  COMMAND
 322109  26681      0         0x2          0    0K halt
db_enter() at db_enter+0x4
panic(d0bd0f54) at panic+0xd3
__assert(d0c36860,d0bfd1b1,68,d0c65a4e) at __assert+0x19
i386_ipi_halt(f1f31ff8) at i386_ipi_halt+0x72
i386_ipi_handler() at i386_ipi_handler+0x3f
Xipi_untramp() at Xipi_untramp+0xc2
__mp_acquire_count(d0e8c934,1) at __mp_acquire_count+0x7c
mi_switch() at mi_switch+0x2ab
sched_idle(f1f31ff8) at sched_idle+0x168
https://www.openbsd.org/ddb.html describes the minimum info required in bug
reports.  Insufficient info makes it difficult to find and fix bugs.
ddb{1}> 
```

I'm not sure why that is. I'll try it again to find out whether it's reproducible or not.

**Comment by dmitshur** [comment] 2020-12-10 20:15
It succeeded on the second try:

```
[...]
syncing disks... done
Archiving disk.raw... (this may take a while)
Done. GCE image is openbsd-i386-gce.tar.gz.
```

**Comment by dmitshur** [comment] 2020-12-11 05:44
Tested [CL 277115](https://golang.org/cl/277115) with debugnewvm, got "ALL TESTS PASSED" on both amd64 and 386 runs.

I also got this failure once:

```
$ debugnewvm -run-build=openbsd-386-68 -rev=6a64f6dc31b3038187ce9246bdf438be9cc94bae
[...]
go test proxy running at GOPROXY=http://127.0.0.1:47697/mod
--- FAIL: TestScript (0.06s)
    --- FAIL: TestScript/mod_convert_vendor_conf (0.18s)
        script_test.go:213: 
            # We should not create a go.mod file unless the user ran 'go mod init' explicitly.
            # However, we should suggest 'go mod init' if we can find an alternate config file. (0.135s)
            > cd $WORK/test/x
            $WORK/test/x
            > ! go list .
            [stderr]
            go: cannot find main module, but found vendor.conf in $WORK/test
            	to create a module there, run:
            	cd .. && go mod init
            FAIL: testdata/script/mod_convert_vendor_conf.txt:6: unexpected command success
            
FAIL
FAIL	cmd/go	265.828s
```

Going to proceed, since we still have a non-zero KnownIssue, and we'll find out more from the future commits on the build dashboard.

**Comment by dmitshur** [comment] 2020-12-11 06:22
This was the log when building the openbsd-amd64 image:

<details><summary>Full Output</summary><br>

```
env/openbsd-amd64 $ ./make.bash 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  511M  100  511M    0     0  66.9M      0  0:00:07  0:00:07 --:--:-- 69.5M
install.site
etc/installurl
etc/rc.local
etc/sysctl.conf
1+0 records in
1+0 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 0.000382186 s, 10.7 MB/s
Executing 'genisoimage -C 16,261664 -M /dev/fd/3 -l -R -graft-points /6.8/amd64/site68.tgz=site68.tgz /auto_install.conf=auto_install.conf /disklabel.template=disklabel.template /etc/boot.conf=boot.conf /etc/random.seed=random.seed | builtin_dd of=install68-amd64-patched.iso obs=32k seek=16354'
I: -input-charset not specified, using utf-8 (detected in locale settings)
Rock Ridge signatures found
Total translation table size: 0
Total rockridge attributes bytes: 2521
Total directory bytes: 8192
Path table size(bytes): 48
Max brk space used 0
261849 extents written (511 MB)
builtin_dd: 192*2KB out @ average infx1352KBps
install68-amd64-patched.iso: copying volume descriptor(s)
Formatting 'disk.raw', fmt=raw size=10737418240
spawn qemu-system-x86_64 -nographic -smp 2 -drive if=virtio,file=disk.raw,format=raw -cdrom install68-amd64-patched.iso -net nic,model=virtio -net user -boot once=d
>> OpenBSD/amd64 CDBOOT 3.52
boot> 
booting cd0a:/6.8/amd64/bsd.rd: 3822285+1573888+3882232+0+761856 [324353+128+468792+313530]=0xaa3780
entry point at 0xffffffff81001000
Copyright (c) 1982, 1986, 1989, 1991, 1993
	The Regents of the University of California.  All rights reserved.
Copyright (c) 1995-2020 OpenBSD. All rights reserved.  https://www.OpenBSD.org

OpenBSD 6.8 (RAMDISK_CD) #94: Sun Oct  4 18:21:11 MDT 2020
    deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/RAMDISK_CD
real mem = 117301248 (111MB)
avail mem = 109879296 (104MB)
random: good seed from bootblocks
mainbus0 at root
bios0 at mainbus0: SMBIOS rev. 2.8 @ 0xf68c0 (10 entries)
bios0: vendor SeaBIOS version "1.10.2-1" date 04/01/2014
bios0: QEMU Standard PC (i440FX + PIIX, 1996)
acpi0 at bios0: ACPI 1.0
acpi0: tables DSDT FACP APIC HPET
acpimadt0 at acpi0 addr 0xfee00000: PC-AT compat
cpu0 at mainbus0: apid 0 (boot processor)
cpu0: QEMU Virtual CPU version 2.5+, 2302.48 MHz, 06-06-03
cpu0: FPU,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CFLUSH,MMX,FXSR,SSE,SSE2,SSE3,CX16,HV,NXE,LONG,LAHF,SVM
cpu0: 64KB 64b/line 2-way I-cache, 64KB 64b/line 2-way D-cache, 512KB 64b/line 16-way L2 cache
cpu0: ITLB 255 4KB entries direct-mapped, 255 4MB entries direct-mapped
cpu0: DTLB 255 4KB entries direct-mapped, 255 4MB entries direct-mapped
cpu0: apic clock running at 999MHz
cpu at mainbus0: not configured
ioapic0 at mainbus0: apid 0 pa 0xfec00000, version 20, 24 pins
acpiprt0 at acpi0: bus 0 (PCI0)
"ACPI0006" at acpi0 not configured
acpipci0 at acpi0 PCI0
acpicmos0 at acpi0
"PNP0A06" at acpi0 not configured
"PNP0A06" at acpi0 not configured
"PNP0A06" at acpi0 not configured
"QEMU0002" at acpi0 not configured
"ACPI0010" at acpi0 not configured
acpicpu at acpi0 not configured
pci0 at mainbus0 bus 0
pchb0 at pci0 dev 0 function 0 "Intel 82441FX" rev 0x02
"Intel 82371SB ISA" rev 0x00 at pci0 dev 1 function 0 not configured
pciide0 at pci0 dev 1 function 1 "Intel 82371SB IDE" rev 0x00: DMA, channel 0 wired to compatibility, channel 1 wired to compatibility
pciide0: channel 0 disabled (no drives)
atapiscsi0 at pciide0 channel 1 drive 0
scsibus0 at atapiscsi0: 2 targets
cd0 at scsibus0 targ 0 lun 0: <QEMU, QEMU DVD-ROM, 2.5+> removable
cd0(pciide0:1:0): using PIO mode 4, DMA mode 2
"Intel 82371AB Power" rev 0x03 at pci0 dev 1 function 3 not configured
vga1 at pci0 dev 2 function 0 "Bochs VGA" rev 0x02
vga1: aperture needed
wsdisplay1 at vga1 mux 1
wsdisplay1: screen 0 added (80x25, vt100 emulation)
virtio0 at pci0 dev 3 function 0 "Qumranet Virtio Network" rev 0x00
vio0 at virtio0: address 52:54:00:12:34:56
virtio0: msix shared
virtio1 at pci0 dev 4 function 0 "Qumranet Virtio Storage" rev 0x00
vioblk0 at virtio1
scsibus1 at vioblk0: 1 targets
sd0 at scsibus1 targ 0 lun 0: <VirtIO, Block Device, >
sd0: 10240MB, 512 bytes/sector, 20971520 sectors
virtio1: msix shared
isa0 at mainbus0
com0 at isa0 port 0x3f8/8 irq 4: ns16550a, 16 byte fifo
com0: console
pckbc0 at isa0 port 0x60/5 irq 1 irq 12
pckbd0 at pckbc0 (kbd slot)
wskbd0 at pckbd0 mux 1
wskbd0: connecting to wsdisplay1
softraid0 at root
scsibus2 at softraid0: 256 targets
root on rd0a swap on rd0b dump on rd0b
WARNING: CHECK AND RESET THE DATE!
erase ^?, werase ^W, kill ^U, intr ^C, status ^T

Welcome to the OpenBSD/amd64 6.8 installation program.
(I)nstall, (U)pgrade, (A)utoinstall or (S)hell? s
# mount /dev/cd0c /mnt
# cp /mnt/auto_install.conf /mnt/disklabel.template /
# chmod a+r /disklabel.template
# umount /mnt
# exit
erase ^?, werase ^W, kill ^U, intr ^C, status ^T

Welcome to the OpenBSD/amd64 6.8 installation program.
Starting non-interactive mode in 5 seconds...
(I)nstall, (U)pgrade, (A)utoinstall or (S)hell? 
Performing non-interactive install...
Terminal type? [vt220] vt220
System hostname? (short form, e.g. 'foo') buildlet

Available network interfaces are: vio0 vlan0.
Which network interface do you wish to configure? (or 'done') [vio0] vio0
IPv4 address for vio0? (or 'dhcp' or 'none') [dhcp] dhcp
IPv6 address for vio0? (or 'autoconf' or 'none') [none] none
Available network interfaces are: vio0 vlan0.
Which network interface do you wish to configure? (or 'done') [done] done
DNS domain name? (e.g. 'example.com') [my.domain] my.domain
Using DNS nameservers at 10.0.2.3

Password for root account? <provided>
Public ssh key for root account? [none] none
Start sshd(8) by default? [yes] yes
Do you expect to run the X Window System? [yes] no
Change the default console to com0? [yes] yes
Available speeds are: 9600 19200 38400 57600 115200.
Which speed should com0 use? (or 'done') [9600] 115200
Setup a user? (enter a lower-case loginname, or 'no') [no] gopher
Full name for user gopher? [gopher] Gopher Gopherson
Password for user gopher? <provided>
Public ssh key for user gopher [none] none
WARNING: root is targeted by password guessing attacks, pubkeys are safer.
Allow root ssh login? (yes, no, prohibit-password) [no] no
What timezone are you in? ('?' for list) [US/Pacific] US/Pacific

Available disks are: sd0.
Which disk is the root disk? ('?' for details) [sd0] sd0
No valid MBR or GPT.
Use (W)hole disk MBR, whole disk (G)PT or (E)dit? [whole] whole
Setting OpenBSD MBR partition to whole sd0...done.
URL to autopartitioning template for disklabel? [none] file://disklabel.template
Fetching file://disklabel.template
/dev/rsd0a: 9008.0MB in 18448448 sectors of 512 bytes
45 cylinder groups of 202.50MB, 12960 blocks, 25920 inodes each
/dev/sd0a (ba0eff463c430d0a.a) on /mnt type ffs (rw, asynchronous, local)

Let's install the sets!
Location of sets? (cd0 disk http nfs or 'done') [cd0] cd0
Pathname to the sets? (or 'done') [6.8/amd64] 6.8/amd64

Select sets by entering a set name, a file name pattern or 'all'. De-select
sets by prepending a '-', e.g.: '-game*'. Selected sets are labelled '[X]'.
    [X] bsd           [X] base68.tgz    [X] game68.tgz    [X] xfont68.tgz
    [X] bsd.mp        [X] comp68.tgz    [X] xbase68.tgz   [X] xserv68.tgz
    [X] bsd.rd        [X] man68.tgz     [X] xshare68.tgz  [ ] site68.tgz
Set name(s)? (or 'abort' or 'done') [done] +* -x* -game* -man* done
Directory does not contain SHA256.sig. Continue without verification? [no] yes
Installing bsd          100% |**************************| 20375 KB    00:02    
Installing bsd.mp       100% |**************************| 20466 KB    00:02    
Installing bsd.rd       100% |**************************| 10149 KB    00:01    
Installing base68.tgz   100% |**************************|   289 MB    01:47    
Extracting etc.tgz      100% |**************************|   260 KB    00:00    
Installing comp68.tgz   100% |**************************| 74305 KB    00:36    
Installing site68.tgz   100% |**************************|   622       00:00    
Location of sets? (cd0 disk http nfs or 'done') [done] done
Saving configuration files... done.
Making all device nodes... done.
Multiprocessor machine; using bsd.mp instead of bsd.
Relinking to create unique kernel... done.
pgrep: kvm_getprocs() failed
pkill: kvm_getprocs() failed
pkill: kvm_getprocs() failed
pkill: kvm_getprocs() failed
pkill: kvm_getprocs() failed
pkill: kvm_getprocs() failed
pkill: kvm_getprocs() failed
pkill: kvm_getprocs() failed
pkill: kvm_getprocs() failed
Get/Verify syspatch68-001_bgpd.tgz
Installing patch 001_bgpd
Get/Verify syspatch68-002_icmp6.tgz
Installing patch 002_icmp6
Get/Verify syspatch68-003_tmux.tgz
Installing patch 003_tmux
Get/Verify syspatch68-004_wg.tgz
Installing patch 004_wg
Get/Verify syspatch68-005_unwind.tgz
Installing patch 005_unwind
Get/Verify syspatch68-006_rpki.tgz
Installing patch 006_rpki
Get/Verify syspatch68-008_asn1.tgz
Installing patch 008_asn1
Get/Verify syspatch68-009_exit.tgz
Installing patch 009_exit
Relinking to create unique kernel...reorder_kernel: failed -- see /usr/share/relink/kernel/RAMDISK_CD/relink.log
 failed!
!!! "/usr/libexec/reorder_kernel" must be run manually to install the new kernel
quirks-3.440 signed on 2020-12-08T22:58:51Z
Adding quirks-3.440
quirks-3.440 (extracting)
quirks-3.440 (installing)
Adding quirks-3.440
Adding bash-5.0.18:libiconv-1.16p0
bash-5.0.18:libiconv-1.16p0 (extracting)
bash-5.0.18:libiconv-1.16p0 (installing)
ldconfig: /var/run/ld.so.hints: No such file or directory
Adding bash-5.0.18:libiconv-1.16p0
Adding bash-5.0.18:gettext-runtime-0.21
bash-5.0.18:gettext-runtime-0.21 (extracting)
bash-5.0.18:gettext-runtime-0.21 (installing)
Adding bash-5.0.18:gettext-runtime-0.21
Adding bash-5.0.18
bash-5.0.18 (extracting)
bash-5.0.18 (installing)
Shell /usr/local/bin/bash appended to /etc/shells
Adding bash-5.0.18
Adding curl-7.72.0:nghttp2-1.41.0p1
curl-7.72.0:nghttp2-1.41.0p1 (extracting)
curl-7.72.0:nghttp2-1.41.0p1 (installing)
Adding curl-7.72.0:nghttp2-1.41.0p1
Adding curl-7.72.0
curl-7.72.0 (extracting)
curl-7.72.0 (installing)
Adding curl-7.72.0
Adding git-2.28.0:cvsps-2.1p2
git-2.28.0:cvsps-2.1p2 (extracting)
git-2.28.0:cvsps-2.1p2 (installing)
Adding git-2.28.0:cvsps-2.1p2
Adding git-2.28.0:p5-Error-0.17028p0
git-2.28.0:p5-Error-0.17028p0 (extracting)
git-2.28.0:p5-Error-0.17028p0 (installing)
Adding git-2.28.0:p5-Error-0.17028p0
Adding git-2.28.0:p5-Time-TimeDate-2.30p0
git-2.28.0:p5-Time-TimeDate-2.30p0 (extracting)
git-2.28.0:p5-Time-TimeDate-2.30p0 (installing)
Adding git-2.28.0:p5-Time-TimeDate-2.30p0
Adding git-2.28.0:p5-Mail-Tools-2.21p0
git-2.28.0:p5-Mail-Tools-2.21p0 (extracting)
git-2.28.0:p5-Mail-Tools-2.21p0 (installing)
Adding git-2.28.0:p5-Mail-Tools-2.21p0
Adding git-2.28.0
git-2.28.0 (extracting)
git-2.28.0 (skipping)
git-2.28.0 (installing)
Shell /usr/local/bin/git-shell appended to /etc/shells
Adding git-2.28.0
The following new rcscripts were installed: /etc/rc.d/gitdaemon
See rcctl(8) for details.
New and changed readme(s):
	/usr/local/share/doc/pkg-readmes/git
Extracted 85674118 from 85679720

CONGRATULATIONS! Your OpenBSD install has been successfully completed!

When you login to your new system the first time, please read your mail
using the 'mail' command.

syncing disks... done
rebooting...
>> OpenBSD/amd64 BOOT 3.52
boot> 
booting hd0a:/bsd: 14406952+3195920+340000+0+880640 [1002951+128+1138200+86122]=0x14d3488
entry point at 0xffffffff81001000
[ using 3003528 bytes of bsd ELF symbol table ]
Copyright (c) 1982, 1986, 1989, 1991, 1993
	The Regents of the University of California.  All rights reserved.
Copyright (c) 1995-2020 OpenBSD. All rights reserved.  https://www.OpenBSD.org

OpenBSD 6.8 (GENERIC.MP) #98: Sun Oct  4 18:13:26 MDT 2020
    deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP
real mem = 117301248 (111MB)
avail mem = 98861056 (94MB)
random: good seed from bootblocks
mpath0 at root
scsibus0 at mpath0: 256 targets
mainbus0 at root
bios0 at mainbus0: SMBIOS rev. 2.8 @ 0xf68c0 (10 entries)
bios0: vendor SeaBIOS version "1.10.2-1" date 04/01/2014
bios0: QEMU Standard PC (i440FX + PIIX, 1996)
acpi0 at bios0: ACPI 1.0
acpi0: sleep states S3 S4 S5
acpi0: tables DSDT FACP APIC HPET
acpi0: wakeup devices
acpitimer0 at acpi0: 3579545 Hz, 24 bits
acpimadt0 at acpi0 addr 0xfee00000: PC-AT compat
cpu0 at mainbus0: apid 0 (boot processor)
cpu0: QEMU Virtual CPU version 2.5+, 2302.68 MHz, 06-06-03
cpu0: FPU,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CFLUSH,MMX,FXSR,SSE,SSE2,SSE3,CX16,HV,NXE,LONG,LAHF,SVM
cpu0: 64KB 64b/line 2-way I-cache, 64KB 64b/line 2-way D-cache, 512KB 64b/line 16-way L2 cache
cpu0: ITLB 255 4KB entries direct-mapped, 255 4MB entries direct-mapped
cpu0: DTLB 255 4KB entries direct-mapped, 255 4MB entries direct-mapped
cpu0: smt 0, core 0, package 0
mtrr: Pentium Pro MTRR support, 8 var ranges, 88 fixed ranges
cpu0: apic clock running at 999MHz
cpu1 at mainbus0: apid 1 (application processor)
cpu1: QEMU Virtual CPU version 2.5+, 2300.95 MHz, 06-06-03
cpu1: FPU,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CFLUSH,MMX,FXSR,SSE,SSE2,SSE3,CX16,HV,NXE,LONG,LAHF,SVM
cpu1: 64KB 64b/line 2-way I-cache, 64KB 64b/line 2-way D-cache, 512KB 64b/line 16-way L2 cache
cpu1: ITLB 255 4KB entries direct-mapped, 255 4MB entries direct-mapped
cpu1: DTLB 255 4KB entries direct-mapped, 255 4MB entries direct-mapped
cpu1: disabling user TSC (skew=-11185905)
cpu1: smt 0, core 0, package 1
ioapic0 at mainbus0: apid 0 pa 0xfec00000, version 20, 24 pins
acpihpet0 at acpi0: 100000000 Hz
acpiprt0 at acpi0: bus 0 (PCI0)
"ACPI0006" at acpi0 not configured
acpipci0 at acpi0 PCI0
acpicmos0 at acpi0
"PNP0A06" at acpi0 not configured
"PNP0A06" at acpi0 not configured
"PNP0A06" at acpi0 not configured
"QEMU0002" at acpi0 not configured
"ACPI0010" at acpi0 not configured
acpicpu0 at acpi0: C1(@1 halt!)
acpicpu1 at acpi0: C1(@1 halt!)
pci0 at mainbus0 bus 0
pchb0 at pci0 dev 0 function 0 "Intel 82441FX" rev 0x02
pcib0 at pci0 dev 1 function 0 "Intel 82371SB ISA" rev 0x00
pciide0 at pci0 dev 1 function 1 "Intel 82371SB IDE" rev 0x00: DMA, channel 0 wired to compatibility, channel 1 wired to compatibility
pciide0: channel 0 disabled (no drives)
atapiscsi0 at pciide0 channel 1 drive 0
scsibus1 at atapiscsi0: 2 targets
cd0 at scsibus1 targ 0 lun 0: <QEMU, QEMU DVD-ROM, 2.5+> removable
cd0(pciide0:1:0): using PIO mode 4, DMA mode 2
piixpm0 at pci0 dev 1 function 3 "Intel 82371AB Power" rev 0x03: apic 0 int 9
iic0 at piixpm0
vga1 at pci0 dev 2 function 0 "Bochs VGA" rev 0x02
wsdisplay at vga1 not configured
virtio0 at pci0 dev 3 function 0 "Qumranet Virtio Network" rev 0x00
vio0 at virtio0: address 52:54:00:12:34:56
virtio0: msix shared
virtio1 at pci0 dev 4 function 0 "Qumranet Virtio Storage" rev 0x00
vioblk0 at virtio1
scsibus2 at vioblk0: 1 targets
sd0 at scsibus2 targ 0 lun 0: <VirtIO, Block Device, >
sd0: 10240MB, 512 bytes/sector, 20971520 sectors
virtio1: msix shared
isa0 at pcib0
isadma0 at isa0
fdc0 at isa0 port 0x3f0/6 irq 6 drq 2
com0 at isa0 port 0x3f8/8 irq 4: ns16550a, 16 byte fifo
com0: console
pckbc0 at isa0 port 0x60/5 irq 1 irq 12
pckbd0 at pckbc0 (kbd slot)
wskbd0 at pckbd0 mux 1
pms0 at pckbc0 (aux slot)
wsmouse0 at pms0 mux 0
pcppi0 at isa0 port 0x61
spkr0 at pcppi0
lpt0 at isa0 port 0x378/4 irq 7
vmm0 at mainbus0: SVM
vscsi0 at root
scsibus3 at vscsi0: 256 targets
softraid0 at root
scsibus4 at softraid0: 256 targets
root on sd0a (ba0eff463c430d0a.a) swap on sd0b dump on sd0b
Automatic boot in progress: starting file system checks.
/dev/sd0a (ba0eff463c430d0a.a): file system is clean; not checking
pf enabled
hw.smt: 0 -> 1
sysctl: kern.timecounter.hardware: Invalid argument
fd0 at fdc0 drive 1: density unknown
starting network
vio0: 10.0.2.15 lease accepted from 10.0.2.2 (52:55:0a:00:02:02)
reordering libraries: done.
openssl: generating isakmpd/iked RSA keys... done.
ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519 
starting early daemons: syslogd pflogd ntpd.
starting RPC daemons:.
savecore: no core dump
checking quotas: done.
clearing /tmp
kern.securelevel: 0 -> 1
creating runtime link editor directory cache.
preserving editor files.
starting network daemons: sshd smtpd sndiod.
running rc.firsttime
Path to firmware: http://firmware.openbsd.org/firmware/6.8/
Installing: vmm-firmware
Checking for available binary patches...
+ echo Remounting root with softdep,noatime...
Remounting root with softdep,noatime...
+ mount -o softdep,noatime,update /
+ echo starting buildlet script
starting buildlet script
+ netstat -rn
[...]
+ cat /etc/resolv.conf
# Generated by vio0 dhclient
nameserver 10.0.2.3
lookup file bind
+ dig metadata.google.internal
[...]
+ set -e
+ export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
+ /usr/local/bin/curl --fail -H Metadata-Flavor: Google http://metadata.google.internal/computeMetadata/v1/instance/attributes/buildlet-binary-url
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
+ /usr/local/bin/curl -o /buildlet
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
+ echo giving up
giving up
+ sleep 10
starting local daemons: cron.
Thu Dec 10 10:28:16 PST 2020

OpenBSD/amd64 (buildlet.my.domain) (tty00)

login: reorder_kernel: failed -- see /usr/share/relink/kernel/GENERIC.MP/relink.log
syncing disks... done
Archiving disk.raw... (this may take a while)
Done. GCE image is openbsd-amd64-gce.tar.gz.
```

</details>

This part stood out:

```
[...]
pgrep: kvm_getprocs() failed
pkill: kvm_getprocs() failed
pkill: kvm_getprocs() failed
pkill: kvm_getprocs() failed
pkill: kvm_getprocs() failed
pkill: kvm_getprocs() failed
pkill: kvm_getprocs() failed
pkill: kvm_getprocs() failed
pkill: kvm_getprocs() failed
Get/Verify syspatch68-001_bgpd.tgz
Installing patch 001_bgpd
Get/Verify syspatch68-002_icmp6.tgz
Installing patch 002_icmp6
Get/Verify syspatch68-003_tmux.tgz
Installing patch 003_tmux
Get/Verify syspatch68-004_wg.tgz
Installing patch 004_wg
Get/Verify syspatch68-005_unwind.tgz
Installing patch 005_unwind
Get/Verify syspatch68-006_rpki.tgz
Installing patch 006_rpki
Get/Verify syspatch68-008_asn1.tgz
Installing patch 008_asn1
Get/Verify syspatch68-009_exit.tgz
Installing patch 009_exit
Relinking to create unique kernel...reorder_kernel: failed -- see /usr/share/relink/kernel/RAMDISK_CD/relink.log
 failed!
!!! "/usr/libexec/reorder_kernel" must be run manually to install the new kernel
[...]
```

That reads to me like maybe the patches didn't apply successfully, but I'm not familiar with the OpenBSD install process to be sure.

**Comment by dmitshur** [comment] 2020-12-18 06:26
Thanks to @4a6f656c for finding and fixing the problem in [CL 278732](https://golang.org/cl/278732).

I've rebuilt the OpenBSD images and updated the builders in [CL 279134](https://golang.org/cl/279134). Both amd64 and 386 versions passed 1/1 times via debugnewvm. They're deployed now and will be used for all future commits, so let's see how it goes.

**Closed** 2020-12-23 17:04 UTC
Labels: Builders, NeedsFix, OS-OpenBSD, new-builder
