### ISSUE TITLE
x/tools/internal/lsp/debug: index out of range panic

### ISSUE THREAD

**Issue by myitcv** [golang/go#38042] opened 2020-03-24 10:09 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +2e918c3aab Tue Mar 17 06:38:32 2020 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20200324053659-5c746ccfa245
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.1.8-0.20200324053659-5c746ccfa245
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build661671640=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

See in a recent run of `govim` tests.

```
panic: runtime error: index out of range [5] with length 5

goroutine 96 [running]:
golang.org/x/tools/internal/lsp/debug.(*rpcs).ProcessEvent(0xc000297500, 0xe69a00, 0xc0002695f0, 0x6, 0xbf96925102cac0f0, 0xceea8f4, 0x139f7a0, 0x0, 0x0, 0x0, ...)
 /home/runner/gopath/pkg/mod/golang.org/x/tools@v0.0.0-20200324053659-5c746ccfa245/internal/lsp/debug/rpc.go:138 +0x10e7
golang.org/x/tools/internal/lsp/debug.(*exporter).ProcessEvent(0xc0002a4320, 0xe69a00, 0xc0002695f0, 0x6, 0xbf96925102cac0f0, 0xceea8f4, 0x139f7a0, 0x0, 0x0, 0x0, ...)
 /home/runner/gopath/pkg/mod/golang.org/x/tools@v0.0.0-20200324053659-5c746ccfa245/internal/lsp/debug/serve.go:567 +0x51c
golang.org/x/tools/internal/telemetry/event.ProcessEvent(0xe69a00, 0xc0002695f0, 0x6, 0xbf96925102cac0f0, 0xceea8f4, 0x139f7a0, 0x0, 0x0, 0x0, 0x0, ...)
 /home/runner/gopath/pkg/mod/golang.org/x/tools@v0.0.0-20200324053659-5c746ccfa245/internal/telemetry/event/export.go:44 +0xaf
golang.org/x/tools/internal/telemetry/event.Record(0xe69a00, 0xc0002695f0, 0xc000256820, 0x1, 0x1)
 /home/runner/gopath/pkg/mod/golang.org/x/tools@v0.0.0-20200324053659-5c746ccfa245/internal/telemetry/event/metric.go:13 +0x101
golang.org/x/tools/internal/lsp/lsprpc.telemetryHandler.Done(0xe69a00, 0xc0002695f0, 0x0, 0x0)
 /home/runner/gopath/pkg/mod/golang.org/x/tools@v0.0.0-20200324053659-5c746ccfa245/internal/lsp/lsprpc/telemetry.go:70 +0x1c7
golang.org/x/tools/internal/jsonrpc2.(*Conn).Notify.func1(0xc000192f50, 0xc0000f1f60, 0xc0000f1f90)
 /home/runner/gopath/pkg/mod/golang.org/x/tools@v0.0.0-20200324053659-5c746ccfa245/internal/jsonrpc2/jsonrpc2.go:116 +0x92
golang.org/x/tools/internal/jsonrpc2.(*Conn).Notify(0xc000192f50, 0xe69a00, 0xc0001f9a40, 0xd1d691, 0x11, 0xba3280, 0xc0001e8ee0, 0x0, 0x0)
 /home/runner/gopath/pkg/mod/golang.org/x/tools@v0.0.0-20200324053659-5c746ccfa245/internal/jsonrpc2/jsonrpc2.go:123 +0x3f5
golang.org/x/tools/internal/lsp/protocol.(*clientDispatcher).LogMessage(0xc000010700, 0xe6a180, 0xc0001763c0, 0xc0001e8ee0, 0xc0002b4660, 0xbc8180)
 /home/runner/gopath/pkg/mod/golang.org/x/tools@v0.0.0-20200324053659-5c746ccfa245/internal/lsp/protocol/tsclient.go:185 +0x6d
created by golang.org/x/tools/internal/lsp/protocol.LogEvent
 /home/runner/gopath/pkg/mod/golang.org/x/tools@v0.0.0-20200324053659-5c746ccfa245/internal/lsp/protocol/context.go:33 +0x242

```

---

cc @stamblerre @ianthehat 

FYI @leitzler

**Comment by findleyr** [comment] 2020-03-24 15:29
I'll take a look this afternoon.

**Comment by findleyr** [comment] 2020-03-24 19:12
I'm having trouble reproducing locally with the govim tests, but from just looking at the callstack, this looks like a race that might only be a problem in daemon mode: [metric.Int64Data](https://github.com/golang/tools/blob/a5e5fedfe7429586fde86c123b10f1bc23d21a25/internal/telemetry/export/metric/data.go#L29) is not threadsafe, but probably is only accessed synchronously when there is a single govim session.

Will discuss with @ianthehat later today: I think the correct solution is to make metrics threadsafe, but will defer to his vision for the telemetry package.

@myitcv if you have a chance perhaps we could discuss reproducing this locally.

**Comment by findleyr** [comment] 2020-03-25 20:24
I'm able to reliably reproduce this now (about half the time), after https://golang.org/cl/225520.

All the telemetry stuff is in-flux, so I'm going to add a way to disable telemetry exporting entirely when running these tests.

**Comment by findleyr** [comment] 2020-03-30 20:35
I believe this was properly fixed by https://golang.org/cl/226317.  I was unable to repro using my script that previously reproduced the panic.

Closing for now, but please reopen if you are able to reproduce after that CL.

**Closed by findleyr** 2020-03-30 20:35 UTC
Labels: NeedsInvestigation, Tools, gopls
