### ISSUE TITLE
runtime.MSpanList_Insert error in osx

### ISSUE THREAD

**Issue by kimown** [golang/go#18380] opened 2016-12-20 06:33 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.4.2
### What operating system and processor architecture are you using (`go env`)?
osx seierra

### What did you do?
I use [forego](https://github.com/ddollar/forego) to control my task, but the process often exit and throw the error, it seems caused by go.

Here is log info
```
failed MSpanList_Insert 0x72c618 0x3633f07318ef 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0x55a6e8, 0x72c618)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Alloc(0x5572e0, 0x1, 0x1000000001f, 0x161f9)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x55fef8, 0xc2080cae50)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x717000, 0x1f, 0x808014000)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mcache.c:90 +0xa0

goroutine 8 [running]:
runtime.switchtoM()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:198 fp=0xc2080cadc0 sp=0xc2080cadb8
runtime.mallocgc(0x400, 0x293960, 0x1, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:178 +0x849 fp=0xc2080cae70 sp=0xc2080cadc0
runtime.newarray(0x293960, 0x400, 0x50)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:365 +0xc1 fp=0xc2080caea8 sp=0xc2080cae70
runtime.makeslice(0x287020, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/slice.go:32 +0x15c fp=0xc2080caef0 sp=0xc2080caea8
main.(*OutletFactory).LineReader(0xc20802ce80, 0xc2080209e0, 0xc20802cf50, 0x9, 0x0, 0x729430, 0xc2080400b8, 0x0)
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/outlet.go:42 +0xf2 fp=0xc2080cafa0 sp=0xc2080caef0
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080cafa8 sp=0xc2080cafa0
created by main.(*Forego).startProcess
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/start.go:140 +0x6a8

goroutine 1 [chan receive, 88 minutes]:
main.runStart(0x544300, 0xc20800a030, 0x0, 0x0)
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/start.go:256 +0x7ea
main.main()
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/main.go:33 +0x385

goroutine 5 [syscall, 89 minutes]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive, 89 minutes]:
main.(*Forego).monitorInterrupt(0xc208012b60)
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/start.go:88 +0x132
created by main.runStart
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/start.go:217 +0x24b

goroutine 9 [syscall, 88 minutes]:
syscall.Syscall(0x3, 0x5, 0xc2080b4000, 0x1000, 0x20, 0x728c70, 0xc20802d408)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_darwin_amd64.s:20 +0x5
syscall.read(0x5, 0xc2080b4000, 0x1000, 0x1000, 0x37a1a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_darwin_amd64.go:970 +0x6e
syscall.Read(0x5, 0xc2080b4000, 0x1000, 0x1000, 0x4, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc2080400c8, 0xc2080b4000, 0x1000, 0x1000, 0xc208040008, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file_unix.go:191 +0x86
os.(*File).Read(0xc2080400c8, 0xc2080b4000, 0x1000, 0x1000, 0x1c700, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file.go:95 +0x91
bufio.(*Reader).fill(0xc208066600)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc208066600, 0xc20809d800, 0x400, 0x400, 0x400, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:174 +0x26c
main.(*OutletFactory).LineReader(0xc20802ce80, 0xc2080209e0, 0xc20802cf50, 0x9, 0x0, 0x729430, 0xc2080400c8, 0x1)
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/outlet.go:43 +0x133
created by main.(*Forego).startProcess
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/start.go:141 +0x739

goroutine 10 [semacquire, 88 minutes]:
sync.(*WaitGroup).Wait(0xc2080209e0)
	/usr/local/Cellar/go/1.4.2/libexec/src/sync/waitgroup.go:132 +0x169
main.func·004()
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/start.go:158 +0x99
created by main.(*Forego).startProcess
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/start.go:160 +0xcdc

goroutine 11 [select, 88 minutes]:
main.func·006()
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/start.go:170 +0x63a
created by main.(*Forego).startProcess
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/start.go:197 +0xea6

goroutine 12 [syscall]:
syscall.Syscall(0x3, 0x4, 0xc2080b5000, 0x1000, 0xc208391768, 0x1516a, 0x48af2)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_darwin_amd64.s:20 +0x5
syscall.read(0x4, 0xc2080b5000, 0x1000, 0x1000, 0xc208036270, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_darwin_amd64.go:970 +0x6e
syscall.Read(0x4, 0xc2080b5000, 0x1000, 0x1000, 0x20, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc208040060, 0xc2080b5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file_unix.go:191 +0x86
os.(*File).Read(0xc208040060, 0xc2080b5000, 0x1000, 0x1000, 0x1c700, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file.go:95 +0x91
bufio.(*Reader).fill(0xc208066480)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc208066480, 0xc208398c00, 0x400, 0x400, 0x400, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:174 +0x26c
main.(*OutletFactory).LineReader(0xc20802ce80, 0xc208020500, 0xc20802c920, 0x9, 0x1, 0x729430, 0xc208040060, 0x0)
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/outlet.go:43 +0x133
created by main.(*Forego).startProcess
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/start.go:140 +0x6a8

goroutine 13 [syscall]:
syscall.Syscall(0x3, 0x7, 0xc2080a4000, 0x1000, 0x1b, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_darwin_amd64.s:20 +0x5
syscall.read(0x7, 0xc2080a4000, 0x1000, 0x1000, 0x1b, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_darwin_amd64.go:970 +0x6e
syscall.Read(0x7, 0xc2080a4000, 0x1000, 0x1000, 0x1b, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc208040078, 0xc2080a4000, 0x1000, 0x1000, 0x1b, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file_unix.go:191 +0x86
os.(*File).Read(0xc208040078, 0xc2080a4000, 0x1000, 0x1000, 0x1b, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file.go:95 +0x91
bufio.(*Reader).fill(0xc2080664e0)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc2080664e0, 0xc20838b000, 0x400, 0x400, 0x400, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:174 +0x26c
main.(*OutletFactory).LineReader(0xc20802ce80, 0xc208020500, 0xc20802c920, 0x9, 0x1, 0x729430, 0xc208040078, 0x1)
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/outlet.go:43 +0x133
created by main.(*Forego).startProcess
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/start.go:141 +0x739

goroutine 14 [semacquire, 88 minutes]:
sync.(*WaitGroup).Wait(0xc208020500)
	/usr/local/Cellar/go/1.4.2/libexec/src/sync/waitgroup.go:132 +0x169
main.func·004()
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/start.go:158 +0x99
created by main.(*Forego).startProcess
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/start.go:160 +0xcdc

goroutine 15 [select, 88 minutes]:
main.func·006()
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/start.go:170 +0x63a
created by main.(*Forego).startProcess
	/private/tmp/forego20151021-13935-zpvkfm/forego-0.16.1/start.go:197 +0xea6

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "fe"
npm ERR! node v5.9.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! fe@0.0.0 fe: `webpack --config webpack.dll.js && forego start -f Procfile.fe`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the fe@0.0.0 fe script 'webpack --config webpack.dll.js && forego start -f Procfile.fe'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fe package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config webpack.dll.js && forego start -f Procfile.fe
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fe
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fe
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Desktop/fe/npm-debug.log
```

**Comment by davecheney** [comment] 2016-12-20 06:38
Please upgrade to Go 1.7.4 or try one of the 1.8 betas. Version 1.4.2 is no
longer supported.

**Comment by kimown** [comment] 2016-12-20 06:48
@davecheney thanks

**Comment by davecheney** [comment] 2016-12-20 06:54
I just saw that you are using osx. You MUST upgraded to 1.7.4, previous
versions do not work on the version of osx you are using.

**Comment by davecheney** [comment] 2016-12-20 06:55
Marking as closed as I'm pretty confident this is a duplicate of the numerous "go crashes on macOS Sierra"

**Closed by davecheney** 2016-12-20 06:55 UTC

**Comment by mikioh** [comment] 2016-12-20 08:47
See #16570.
