### ISSUE TITLE
cmd/go: mod vendor nukes existing vendor directory

### ISSUE THREAD

**Issue by tamird** [golang/go#44646] opened 2021-02-26 18:32 UTC
Running `go mod vendor` in the presence of a directory called "vendor" is dangerous. In particular, if such a directory contains git repositories, they are unceremoniously deleted. It'd be nice to have a best-effort check in place before performing destructive operations. Perhaps if "vendor" exists but "vendor/modules.txt" does not, the command should issue a warning.

**Comment by seankhliao** [comment] 2021-02-26 18:41
possibly a duplicate of #26366 #44119

**Comment by bcmills** [comment] 2021-03-22 16:47
Duplicate of #44646

**Comment by tamird** [comment] 2021-03-22 21:31
Seems you marked it a duplicate of itself.

**Comment by bcmills** [comment] 2021-03-23 18:55
Oops! Sorry, will fix.

**Comment by bcmills** [comment] 2021-03-23 18:55
Duplicate of #44119

**Closed by bcmills** 2021-03-23 18:55 UTC
Labels: GoCommand, NeedsInvestigation

**Comment by matveynator** [comment] 2022-01-14 14:38
Just nuked my two days work on the module....
Surprize!
