### ISSUE TITLE
encoding/gob: no way to skip marshalling exported struct field, docs unclear that a struct must have minimum one exported field

### ISSUE THREAD

**Issue by willauld** [golang/go#19969] opened 2017-04-14 02:24 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8

### What operating system and processor architecture are you using (`go env`)?
go env

set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\home\auld\godev\
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Use
rs\auld\AppData\Local\Temp\go-build485133467=/tmp/go-build -gno-record-gcc
-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?

The program should transmit its User struct and receive it via a fake network and print the transferred data. Line 15-17 of the below play area program contains three cases. The third case (3) works correctly and transfers all the data as expected. Case two (2) also transfers all the data but based on the documentation I believe only the values associated with exported field should be transferred. Case one (1) does not transfer any data, not even the exported fields from User. 

I believe both case 1 and 2 represent bugs.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

 https://play.golang.org/p/Y7ZPpq9-8v

### What did you expect to see?

Case 1: &{Donald DuckPass []}
Case 2: &{Donald DuckPass [{ 2} { 1}]}
Case 3: &{Donald DuckPass [{1 2} {2 1}]}

### What did you see instead?

Case 1: 2009/11/10 23:00:00 encode error:gob: type main.j has no exported fields
Case 2: &{Donald DuckPass [{1 2} {2 1}]}
Case 3: &{Donald DuckPass [{1 2} {2 1}]}

**Comment by bradfitz** [comment] 2017-04-14 03:14
Dup of #19970?

The docs say:

"Structs encode and decode only exported fields."

I think this is working as intended. Let me know if I don't understand.

**Comment by willauld** [comment] 2017-04-14 16:42
Case 2 encodes/decode j.a which is not exported. This contradicts your quote from the document. 

In Case 1 it is NOT encoding/decoding User.Name, User.Pass which I believe also contradicts the quote. In addition I believe User.List should be encoded even though it would be empty.

**Comment by bradfitz** [comment] 2017-04-15 00:12
Okay, I'll let @robpike decide or document this.

Rob, it seems that @willauld wants to be able to mark a field as not marshalled, and/or document that marshalling a struct with zero exported fields is an error. Currently the docs don't say a struct must have at minimum one exported field.

**Comment by rsc** [comment] 2017-06-05 20:16
ping @robpike

**Comment by robpike** [comment] 2018-06-12 11:36
Duplicate of #5819.

**Closed by robpike** 2018-06-12 11:36 UTC
Labels: Documentation, NeedsDecision
