### ISSUE TITLE
cmd/go: useless error when assembly file doesn't end in newline

### ISSUE THREAD

**Issue by bradfitz** [golang/go#7890] opened 2014-04-28 20:18 UTC
<pre>1) make a foo_amd64.s with only &quot;# hi&quot; in it (no trailing newline)

2) make a foo.go file, package foo

2) go build .

Output is unhelpfully:

$ go build .
# foo
eof in comment

It should say which file at least.</pre>

**Comment by rsc** [comment] 2015-04-20 15:38
I checked that cmd/asm gets this right. cmd/old6a etc will be deleted for the final release, which will solve this.
Therefore, duplicate of #10510.

**Closed by rsc** 2015-04-20 15:38 UTC
