### ISSUE TITLE
cmd/go: go install fails when given source file path

### ISSUE THREAD

**Issue by campoy** [golang/go#8424] opened 2014-07-25 22:36 UTC
<pre>What steps will reproduce the problem?
1. ~/bug.go contains any program compiling successfully (e.g.
<a href="http://play.golang.org/p/RQT4BfIN7h)">http://play.golang.org/p/RQT4BfIN7h)</a>
2. go install ~/bug.go

Reading the documentation of &quot;go install&quot; I expect it to fail because ~/bug.go
is not an import path.

Instead this error message is logged: &quot;go install: no install location for .go
files listed on command line (GOBIN not set)&quot;

In any case there's a documentation in the bug, since there's no mention $GOBIN.

Once the expected behavior clarified I'm happy to try to fix it.</pre>

**Comment by carstn** [comment] 2015-09-14 01:28
The same incorrect error message is outputted when you `go install` some .go file that doesn't contain a `main` package. 

For example, if you run `go install mgorus.go` on github.com/weekface/mgorus, the compiler complains:
`go install: no install location for .go files listed on command line (GOBIN not set)`.
This doesn't describe the correct problem. The problem is that you can install only `main` packages, not that GOBIN is not set (`echo $GOBIN` returns `/Users/carstn/Code/go/bin`).

current go version and os: go1.5 darwin/amd64

**Comment by coltin** [comment] 2015-11-12 20:08
@carstn is correct, I'm seeing the same thing. I tried to install a library with GOBIN set and I get this error message.

$ go version
go version go1.5.1 darwin/amd64

**Comment by bcmills** [comment] 2019-01-23 15:33
#23439 is a duplicate of this, but has quite a bit more discussion. Consolidating into that issue.

**Closed by bcmills** 2019-01-23 15:33 UTC
Labels: Documentation
