### ISSUE TITLE
debug/gosym: pclntab_test failing on plan9/amd64

### ISSUE THREAD

**Issue by joushou** [golang/go#12863] opened 2015-10-07 12:45 UTC
pclntab_test.go calls the assembler and linker:
```
go tool asm -o pclinetest.o pclinetest.asm
go tool link -H linux -E main -o pclinetest pclinetest.o
```

The link fails on plan9 with `entry not text: main` in Entryvalue (cmd/link/internal/ld/lib.go), where the LSym type was 26, translating to SXREF, but was expected to be STEXT.

This is the test that the plan9/amd64 builder is currently failing.

#### Versions
OS: 9front amd64
Go: head of master and 1.5.1

**Comment by ianlancetaylor** [comment] 2015-10-07 14:22
Because go tool link is being invoked with -H linux, it should behave the same no matter what host it is being run on.  That is failing somehow, but I don't know why.  I also don't know how much effort it's worth putting into finding it.

**Comment by 0intro** [comment] 2015-10-07 15:31
By the way, I don't think it's a regression, since the test was disabled before
CL 10633 (June 2, 2015), because of the use of the Bourne shell.
It probably never worked, but I haven't investigated the issue yet.

**Comment by 0intro** [comment] 2016-04-20 02:41
This issue is a duplicate of issue #14536.

**Comment by 0intro** [comment] 2016-04-20 02:41
This issue has been fixed in [CL 19973](https://golang.org/cl/19973).

**Closed by 0intro** 2016-04-20 02:41 UTC
Labels: OS-Plan9
