### ISSUE TITLE
"go tool pprof" should honor proxies

### ISSUE THREAD

**Issue by paulstuart** [golang/go#20371] opened 2017-05-15 22:31 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.5 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/paulstuart/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0h/2vr19bk94859lb28j19mycww0000gn/T/go-build334701572=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
Trying to run "go tool prof $URL" where $URL is a url behind a proxy service
    > go tool pprof $URL

### What did you expect to see?
    Saved profile in <redacted>
    Entering interactive mode (type "help" for commands)
    (pprof)

### What did you see instead?

    Fetching profile from $URL
    http fetch $URL: Get $URL: dial tcp: lookup $URL_HOSTNAME: no such host

### Fix

In src/cmd/internal/pprof/fetch/fetch.go:

    // httpGet is a wrapper around http.Get; it is defined as a variable
    // so it can be redefined during for testing.
    var httpGet = func(url string, timeout time.Duration) (*http.Response, error) {
        client := &http.Client{
                Transport: &http.Transport{
                        ResponseHeaderTimeout: timeout + 5*time.Second,
                        Proxy: http.ProxyFromEnvironment,  // <------ FIX HERE: ADD PROXY SUPPORT
                },
        }
        return client.Get(url)
    }

**Comment by ALTree** [comment] 2017-05-16 07:14
#
Thanks for the report. 

This is a duplicate of #18736 (cmd/pprof: use proxy from environment), which is fixed in the latest go release, so I'm closing this issue.

**Closed by ALTree** 2017-05-16 07:14 UTC
