### ISSUE TITLE
x/tools/gopls: gopls restart needed after changing build tags

### ISSUE THREAD

**Issue by muirdm** [golang/go#54147] opened 2022-07-30 21:52 UTC
With gopls on master (9580c84d5753ec8548a100560e8a2d94aeb99972), starting with:

```
-- foo.go --
package main

func main() {}
-- bar.go --
package main

func main() {}
```

1. Confirm you get "duplicate main" diagnostic
2. Add "//go:build ignore" to one of the files
3. Observe you still see the diagnostic until you restart gopls

**Comment by findleyr** [comment] 2022-08-01 13:54
This is just a bug: changes to build tags should (and probably do) invalidate packages.

The likely nature of this bug is that we don't clear diagnostics when the file is dropped from a package. I will fix this.

**Comment by findleyr** [comment] 2022-08-01 16:53
It looks like this bug is fixed at tip. Bisecting.

**Comment by findleyr** [comment] 2022-08-01 17:05
This was fixed by https://go.dev/cl/417576.  I'll close this with a passing regression test.

But the regtest I wrote is failing in the "experimental" mode. Investigating why...

**Closed** 2022-08-02 14:13 UTC
Labels: gopls, Tools, gopls/metadata
