### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by slnc** [golang/go#52501] opened 2022-04-22 17:05 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/juanalonso/Library/Caches/go-build"
GOENV="/Users/juanalonso/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/juanalonso/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/juanalonso/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.18.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18.1/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/juanalonso/files/juan/juan.al/hugo/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/89/g367mkcn77q3ymjt81cm8ry40000gn/T/go-build3655242153=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
$ git clone https://github.com/slnc/hugo.git
$ cd hugo
$ go mod tidy
```

### What did you expect to see?

`go mod tidy` suceeds and updates `go.sum`.

### What did you see instead?

An error:

```
go: downloading github.com/bep/gitmap v1.2.0
github.com/gohugoio/hugo/hugolib imports
        github.com/bep/gitmap: create zip: testfiles/emoji📚.txt: malformed file path "testfiles/emoji📚.txt": invalid char '📚'
[... rest of the output truncated...]
```

For context on how I got here please see https://github.com/gohugoio/hugo/issues/9810. Use-case: some people using http://obsidian.md/ to manage their digital gardens and Hugo to host them use emojis in filenames to help navigate hundreds of files, but in order to show a "Recently updated notes" feature we need Git commit history for them. I just updated the package that Hugo uses to retrieve that info, gitmap, but now that I'm trying to update Hugo's go.sum, I'm hitting this error.

Is there a reason why characters like that aren't supported? Is there a way to update go.sum manually? gitmap gets updated less frequently than once a year.

**Comment by seankhliao** [comment] 2022-04-22 17:11
Duplicate of #45549

**Closed by seankhliao** 2022-04-22 17:11 UTC
