### ISSUE TITLE
x/net/http/httpproxy: http.ProxyFunc ignoring url.Parse error

### ISSUE THREAD

**Issue by maksim77** [golang/go#46264] opened 2021-05-19 14:16 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.16.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/maksim/Library/Caches/go-build"
GOENV="/Users/maksim/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/maksim/go/pkg/mod"
GONOPROXY=""
GONOSUMDB="gitlab.services.mts.ru/*"
GOOS="darwin"
GOPATH="/Users/maksim/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/maksim/Yandex.Disk/dev/go/proxyTest/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1l/1qn0db_57n97z1pv3lczt9ym0000gn/T/go-build1406398690=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

[Go Playground](https://play.golang.org/p/e22xpEJz6rC)

The `http.ProxyFromEnvironment` function does not return an error if the environment variables contain incorrect values. Worse, it returns \<nil\> / \<nil\>. Because of this, the `http.Client{}` silently ignores the value of the variables defining the proxy.

The problem is that in the package `x/net/http/httpproxy` function `httpproxy.FromEnvironment().ProxyFunc()` simply ignores the errors that the `url.Parse()` returns.

https://github.com/golang/go/blob/658b5e66ecbc41a49e6fb5aa63c5d9c804cf305f/src/vendor/golang.org/x/net/http/httpproxy/proxy.go#L118-L125
https://github.com/golang/go/blob/658b5e66ecbc41a49e6fb5aa63c5d9c804cf305f/src/vendor/golang.org/x/net/http/httpproxy/proxy.go#L208-L215

I see two problems here:

1. `http.ProxyFromEnvironment` is used when building the default client `client := &http.Client{}` and it is not clear how to report an error in this case
2. The value of the environment variable in my example is correct from the point of view of for example curl. The password can contain a percent sign. On the other hand, in URLs, the percentage means something completely different...

### What did you expect to see?
Silently ignoring the error

### What did you see instead?
An error returned explicitly

**Comment by seankhliao** [comment] 2021-05-20 17:40
Duplicate of #38166

**Closed by seankhliao** 2021-05-20 17:40 UTC
