### ISSUE TITLE
cmd/go: go test -coverpkg=./... -race does not rebuild sync/atomic

### ISSUE THREAD

**Issue by hirochachacha** [golang/go#18486] opened 2017-01-01 11:02 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +e776975 Sat Dec 31 18:54:27 2016 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GORACE=""
GOROOT="/home/travis/.gimme/versions/go"
GOTOOLDIR="/home/travis/.gimme/versions/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build901867199=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

1. create an empty package https://github.com/hirochachacha/empty
2. add .travis.yml
```
language: go
go:
    - 1.5
    - 1.6
    - 1.7
    - tip
script:
- go test -coverpkg=./... -race -v
``` 
3. then, I see a build error. https://travis-ci.org/hirochachacha/empty
```
$ go test -coverpkg=./... -race -v
# github.com/hirochachacha/empty
/tmp/go-build559712700/github.com/hirochachacha/empty/_obj/empty.go:3: can't find import: "sync/atomic"
```

### What did you expect to see?
no errors.

### What did you see instead?
an error.

I could not reproduce it on my mac and linux.
However, I can reproduce it on a docker container.
```
docker run -it quay.io/travisci/travis-go /bin/bash
```
and,
```
su - travis
GIMME_OUTPUT=$(gimme tip) && eval "$GIMME_OUTPUT"
export GOPATH=$HOME/gopath
export PATH=$HOME/gopath/bin:$PATH
go get github.com/hirochachacha/empty
cd $HOME/gopath/src/github.com/hirochachacha/empty
go test -coverpkg=./... -race -v
```
I have no clue. It may be travis's issue? or something I am missing.

Thanks.

**Comment by davecheney** [comment] 2017-01-01 11:10
1.7 is go 1.7, not 1.7.4. if you want the latest in the 1.7 series, use
1.7.x. Repeat for other versions.

**Comment by dhananjay92** [comment] 2017-01-01 17:57
`-coverpkg=./...` and `-race` will work alone, but both of the flags together fail.

```shell
$ go test -coverpkg=./... -v
?   	github.com/hirochachacha/empty	[no test files]

$ go test -race -v
?   	github.com/hirochachacha/empty	[no test files]

$ go test -coverpkg=./... -race -v
# github.com/hirochachacha/empty
/tmp/go-build463635544/github.com/hirochachacha/empty/_obj/empty.go:3: can't find import: "sync/atomic"

$ cat /tmp/go-build595576066/github.com/hirochachacha/empty/_obj/empty.go -n
     1	package empty
     2	
     3	import _cover_atomic_ "sync/atomic"
     4	
     5	var _ = _cover_atomic_.AddUint32
     6	
     7	var GoCover_0 = struct {
     8		Count     [0]uint32
     9		Pos       [3 * 0]uint32
    10		NumStmt   [0]uint16
    11	} {
    12		Pos: [3 * 0]uint32{
    13		},
    14		NumStmt: [0]uint16{
    15		},
    16	}
```

I've isolated the issue to,  `cmd/compile` not being able to compile a program importing `sync.atomic` with `-race`. It can compile it without `-race` though.

Smaller repro case,
```shell
$ cat /tmp/p.go 
package p

import _ "sync/atomic"

$ go tool compile -o /dev/null /tmp/p.go 
# ... succeeds ...

$ go tool compile -o /dev/null -race /tmp/p.go 
/tmp/p.go:3: can't find import: "sync/atomic"
```

Looking into why `cmd/compile` fails to compile it with `-race`.

**Comment by davecheney** [comment] 2017-01-01 18:32
Is there a GOROOT/pkg/linux_amd64_race/sync/atomic.a file?

**Comment by dhananjay92** [comment] 2017-01-01 18:40
Nope. And that's the issue. [`findpkg()`](https://github.com/golang/go/blob/655a4e1284dadf3507a13b408d21900008e44221/src/cmd/compile/internal/gc/main.go#L646-L648) is adding `_race` to the import path. I am not sure what the correct behavior should be for std-imports. Should it be importing non-instrumented version of std libs?

**Comment by davecheney** [comment] 2017-01-01 18:41
Yes, only instrument the package under test.

**Comment by dhananjay92** [comment] 2017-01-01 18:59
Okay, thanks. I'll tackle this in 1.9.
Because this is not a regression from 1.7, the fix can probably wait for 1.9.

**Comment by hirochachacha** [comment] 2017-01-01 23:00
I think this is a regression. please see https://travis-ci.org/hirochachacha/empty.

**Comment by hirochachacha** [comment] 2017-01-02 01:27
> I think this is a regression. please see https://travis-ci.org/hirochachacha/empty.

I understand.

`gimme 1.7` download binary package which have "pkg/linux_amd64_race" directory.
`gimme tip` download source  code and run `./make.bash`.

`./make.bash` doesn't create "pkg/$GOOS_$GOARCH_race". (while `./all.bash` create the directory)
So this is not a platform specific issue nor a regression. I can reproduce it on my mac. 

`go test` should create "pkg/$GOOS_$GOARCH" if it is missing?

**Comment by davecheney** [comment] 2017-01-02 02:17
Yeah, thus is a bug, i suspect on 1.7 as well, but we don't notice it
because the released versions of go have the race runtime packages built
ahead of time.

Imo go test cover should add an explicit dependency on sync/atomic which
will cause it to be built in race mode.

It's probably not hard to fix and if a test in cmd/go can be written I
think we should try to close this for 1.8

**Comment by dhananjay92** [comment] 2017-01-03 17:31
> Yes, only instrument the package under test.

I thought about this and it doesn't add up. When compiling with `-race`, it has to import race instrumented versions of all packages. Without that, it wouldn't catch race between a function in user's package and another in std-lib.

/cc @dvyukov, to confirm.

If that's the case, then `cmd/compile` is working as expected; Although, it could give better error message mentioning that it was looking for race/msan instrumented version of the package.

**Comment by davecheney** [comment] 2017-01-03 19:59
Sorry, I was not clear. I should have said "only instrument for test
coverage"

**Comment by dhananjay92** [comment] 2017-01-03 21:24
Ah, okay. Sent out the CL for better error.

After [golang.org/cl/34798](http://golang.org/cl/34798):
```shell
$ compile -o /dev/null -race /tmp/p.go
/tmp/p.go:3: can't find race-instrumented version of import: "fmt"
```

**Closed** 2017-01-04 20:02 UTC
