### ISSUE TITLE
go/constant: stringVal.String truncates final quotation mark

### ISSUE THREAD

**Issue by alandonovan** [golang/go#14261] opened 2016-02-08 19:54 UTC
```
% cat a.go
package main

import (
        "fmt"
        "go/token"
        "go/types"
        "log"
)

func main() {
        fset := token.NewFileSet()
        tv, err := types.Eval(fset, nil, 0, `"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"`)
        if err != nil {
                log.Fatal(err)
        }
        fmt.Println(tv.Value.String())
}
```

```
% go run a.go
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...
```

**Comment by griesemer** [comment] 2016-02-08 22:13
This is working as intended: The output of value.String() may be shortened:
```
	// String returns a short, human-readable form of the value.
	// For numeric values, the result may be an approximation;
	// for String values the result may be a shortened string.
	// Use ExactString for a string representing a value exactly.
	String() string
```
The reason we print a shortened string w/o closing quote (e.g.: "xxxxx...) is so we can tell it apart from an actual (not shortened) string (here: "xxxxx...").

Use ExactString() to get the complete string. (i.e., String() is a short form for human readable output).

**Closed by griesemer** 2016-02-08 22:13 UTC
