### ISSUE TITLE
cmd/vet: TestVet fails with the latest tip version

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#33481] opened 2019-08-05 23:08 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +d1338ec30e Mon Aug 5 19:01:06 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yoshiki.shibata/Library/Caches/go-build"
GOENV="/Users/yoshiki.shibata/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yoshiki.shibata/gocode"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/yoshiki.shibata/tools/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/yoshiki.shibata/tools/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/yoshiki.shibata/tools/go/src/cmd/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g5/3v328m31769f1hylbmcvt6x00000gp/T/go-build195139623=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version devel +d1338ec30e Mon Aug 5 19:01:06 2019 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +d1338ec30e Mon Aug 5 19:01:06 2019 +0000
uname -v: Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G84
lldb --version: lldb-1001.0.13.3
  Swift-5.0
</pre></details>

### What did you do?

I tried to rebuild the latest tip version with `all.bash`

### What did you expect to see?

All tests passed

### What did you see instead?

```
ok  	cmd/trace	0.047s
--- FAIL: TestVet (1.01s)
    --- FAIL: TestVet/unsafeptr (0.26s)
        vet_test.go:153: vet output:
        vet_test.go:154: <nil>
    --- FAIL: TestVet/print (0.26s)
        vet_test.go:162: error check failed: 
            print.go:169: missing error "Warn call has possible formatting directive %s"
            print.go:170: missing error "Warnf call needs 1 arg but has 2 args"
            print.go:171: missing error "Warnf format %r has unknown verb r"
            print.go:172: missing error "Warnf format %#s has unrecognized flag #"
            print.go:173: missing error "Warn2 call has possible formatting directive %s"
            print.go:174: missing error "Warnf2 call needs 1 arg but has 2 args"
            print.go:175: missing error "Warnf2 format %r has unknown verb r"
            print.go:176: missing error "Warnf2 format %#s has unrecognized flag #"
FAIL
FAIL	cmd/vet	6.273s
FAIL
2019/08/06 08:04:40 Failed: exit status 1
```

**Comment by ianlancetaylor** [comment] 2019-08-05 23:21
I'm not seeing any failures on https://build/golang.org.  I can't reproduce the problem myself; for me "all.bash" completes without error, as does `go test cmd/vet`.

Tell us more about your environment.  Are you sure you don't have any local changes?

**Comment by YoshikiShibata** [comment] 2019-08-06 01:13
I deleted the local repository and cloned it gain. And then try `all.bash`:

```
PC089mp:src yoshiki.shibata$ ./all.bash
Building Go cmd/dist using /usr/local/go.
Building Go toolchain1 using /usr/local/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for darwin/amd64.

##### Testing packages.
ok  	archive/tar	0.082s
ok  	archive/zip	0.070s
ok  	bufio	0.081s
ok  	bytes	0.199s
ok  	compress/bzip2	0.087s
ok  	compress/flate	0.469s
ok  	compress/gzip	0.025s
ok  	compress/lzw	0.014s
ok  	compress/zlib	0.083s
ok  	container/heap	0.028s
ok  	container/list	0.026s
ok  	container/ring	0.009s
ok  	context	1.066s
ok  	crypto	0.014s
ok  	crypto/aes	0.036s
ok  	crypto/cipher	0.022s
ok  	crypto/des	0.018s
ok  	crypto/dsa	0.019s
ok  	crypto/ecdsa	0.126s
ok  	crypto/ed25519	0.066s
ok  	crypto/elliptic	0.053s
ok  	crypto/hmac	0.018s
ok  	crypto/internal/subtle	0.019s
ok  	crypto/md5	0.017s
ok  	crypto/rand	0.026s
ok  	crypto/rc4	0.040s
ok  	crypto/rsa	0.152s
ok  	crypto/sha1	0.104s
ok  	crypto/sha256	0.019s
ok  	crypto/sha512	0.038s
ok  	crypto/subtle	0.027s
ok  	crypto/tls	0.901s
ok  	crypto/x509	0.776s
ok  	database/sql	0.581s
ok  	database/sql/driver	0.028s
ok  	debug/dwarf	0.031s
ok  	debug/elf	0.049s
ok  	debug/gosym	0.021s
ok  	debug/macho	0.022s
ok  	debug/pe	0.035s
ok  	debug/plan9obj	0.025s
ok  	encoding/ascii85	0.023s
ok  	encoding/asn1	0.015s
ok  	encoding/base32	0.027s
ok  	encoding/base64	0.019s
ok  	encoding/binary	0.014s
ok  	encoding/csv	0.026s
ok  	encoding/gob	0.037s
ok  	encoding/hex	0.015s
ok  	encoding/json	0.100s
ok  	encoding/pem	0.041s
ok  	encoding/xml	0.041s
ok  	errors	0.020s
ok  	expvar	0.033s
ok  	flag	0.023s
ok  	fmt	0.102s
ok  	go/ast	0.042s
ok  	go/build	0.596s
ok  	go/constant	0.046s
ok  	go/doc	0.067s
ok  	go/format	0.017s
ok  	go/importer	0.183s
ok  	go/internal/gccgoimporter	0.055s
ok  	go/internal/gcimporter	0.617s
ok  	go/internal/srcimporter	0.962s
ok  	go/parser	0.032s
ok  	go/printer	0.254s
ok  	go/scanner	0.086s
ok  	go/token	0.034s
ok  	go/types	0.886s
ok  	hash	0.042s
ok  	hash/adler32	0.150s
ok  	hash/crc32	0.127s
ok  	hash/crc64	0.021s
ok  	hash/fnv	0.017s
ok  	html	0.055s
ok  	html/template	0.043s
ok  	image	0.149s
ok  	image/color	0.029s
ok  	image/draw	0.074s
ok  	image/gif	0.322s
ok  	image/jpeg	0.226s
ok  	image/png	0.062s
ok  	index/suffixarray	0.343s
ok  	internal/cpu	0.274s
ok  	internal/fmtsort	0.020s
ok  	internal/poll	0.050s
ok  	internal/reflectlite	0.053s
ok  	internal/singleflight	0.068s
ok  	internal/trace	0.085s
ok  	internal/xcoff	0.032s
ok  	io	0.087s
ok  	io/ioutil	0.022s
ok  	log	0.025s
ok  	log/syslog	1.281s
ok  	math	0.023s
ok  	math/big	0.251s
ok  	math/bits	0.018s
ok  	math/cmplx	0.036s
ok  	math/rand	0.118s
ok  	mime	0.019s
ok  	mime/multipart	0.203s
ok  	mime/quotedprintable	0.054s
ok  	net	1.991s
ok  	net/http	3.556s
ok  	net/http/cgi	0.838s
ok  	net/http/cookiejar	0.033s
ok  	net/http/fcgi	0.031s
ok  	net/http/httptest	0.046s
ok  	net/http/httptrace	0.028s
ok  	net/http/httputil	0.055s
ok  	net/http/internal	0.039s
ok  	net/http/pprof	2.047s
ok  	net/internal/socktest	0.015s
ok  	net/mail	0.010s
ok  	net/rpc	0.044s
ok  	net/rpc/jsonrpc	0.033s
ok  	net/smtp	0.058s
ok  	net/textproto	0.033s
ok  	net/url	0.209s
ok  	os	0.988s
ok  	os/exec	1.418s
ok  	os/signal	4.938s
ok  	os/user	0.024s
ok  	path	0.018s
ok  	path/filepath	0.092s
ok  	plugin	0.020s
ok  	reflect	0.111s
ok  	regexp	0.069s
ok  	regexp/syntax	0.619s
ok  	runtime	25.822s
ok  	runtime/debug	0.056s
ok  	runtime/internal/atomic	0.021s
ok  	runtime/internal/math	0.019s
ok  	runtime/internal/sys	0.019s
ok  	runtime/pprof	8.626s
ok  	runtime/pprof/internal/profile	0.036s
ok  	runtime/trace	0.562s
ok  	sort	0.098s
ok  	strconv	1.030s
ok  	strings	0.261s
ok  	sync	0.418s
ok  	sync/atomic	0.031s
ok  	syscall	0.152s
ok  	testing	0.067s
ok  	testing/quick	0.044s
ok  	text/scanner	0.025s
ok  	text/tabwriter	0.022s
ok  	text/template	0.073s
ok  	text/template/parse	0.018s
ok  	time	2.636s
ok  	unicode	0.020s
ok  	unicode/utf16	0.013s
ok  	unicode/utf8	0.018s
ok  	cmd/addr2line	2.242s
ok  	cmd/api	0.064s
ok  	cmd/asm/internal/asm	0.572s
ok  	cmd/asm/internal/lex	0.069s
ok  	cmd/compile	0.026s
ok  	cmd/compile/internal/gc	17.359s
ok  	cmd/compile/internal/ssa	0.520s
ok  	cmd/compile/internal/syntax	0.040s
ok  	cmd/compile/internal/test	0.009s [no tests to run]
ok  	cmd/compile/internal/types	0.018s
ok  	cmd/cover	3.424s
ok  	cmd/doc	0.102s
ok  	cmd/fix	0.028s
ok  	cmd/go	79.119s
ok  	cmd/go/internal/auth	0.032s
ok  	cmd/go/internal/cache	0.809s
ok  	cmd/go/internal/dirhash	0.017s
ok  	cmd/go/internal/generate	0.034s
ok  	cmd/go/internal/get	0.058s
ok  	cmd/go/internal/imports	0.079s
ok  	cmd/go/internal/load	0.025s
ok  	cmd/go/internal/lockedfile	0.041s
ok  	cmd/go/internal/lockedfile/internal/filelock	0.057s
ok  	cmd/go/internal/modconv	0.064s
ok  	cmd/go/internal/modfetch	0.146s
ok  	cmd/go/internal/modfetch/codehost	0.014s
ok  	cmd/go/internal/modfile	0.043s
ok  	cmd/go/internal/modload	0.042s
ok  	cmd/go/internal/module	0.019s
ok  	cmd/go/internal/mvs	0.017s
ok  	cmd/go/internal/note	0.056s
ok  	cmd/go/internal/par	0.038s
ok  	cmd/go/internal/renameio	0.497s
ok  	cmd/go/internal/search	0.030s
ok  	cmd/go/internal/semver	0.047s
ok  	cmd/go/internal/sumweb	0.052s
ok  	cmd/go/internal/tlog	1.553s
ok  	cmd/go/internal/txtar	0.023s
ok  	cmd/go/internal/web	0.034s
ok  	cmd/go/internal/work	0.043s
ok  	cmd/gofmt	0.090s
ok  	cmd/internal/buildid	0.209s
ok  	cmd/internal/dwarf	0.019s
ok  	cmd/internal/edit	0.016s
ok  	cmd/internal/goobj	1.540s
ok  	cmd/internal/obj	0.041s
ok  	cmd/internal/obj/arm64	0.285s
ok  	cmd/internal/obj/x86	3.775s
ok  	cmd/internal/objabi	0.038s
ok  	cmd/internal/src	0.016s
ok  	cmd/internal/test2json	0.101s
ok  	cmd/link	4.175s
ok  	cmd/link/internal/ld	10.340s
ok  	cmd/link/internal/sym	0.027s
ok  	cmd/nm	3.896s
ok  	cmd/objdump	3.932s
ok  	cmd/pack	2.128s
ok  	cmd/trace	0.109s
--- FAIL: TestVet (1.05s)
    --- FAIL: TestVet/unsafeptr (0.64s)
        vet_test.go:153: vet output:
        vet_test.go:154: <nil>
    --- FAIL: TestVet/print (0.50s)
        vet_test.go:162: error check failed: 
            print.go:169: missing error "Warn call has possible formatting directive %s"
            print.go:170: missing error "Warnf call needs 1 arg but has 2 args"
            print.go:171: missing error "Warnf format %r has unknown verb r"
            print.go:172: missing error "Warnf format %#s has unrecognized flag #"
            print.go:173: missing error "Warn2 call has possible formatting directive %s"
            print.go:174: missing error "Warnf2 call needs 1 arg but has 2 args"
            print.go:175: missing error "Warnf2 format %r has unknown verb r"
            print.go:176: missing error "Warnf2 format %#s has unrecognized flag #"
FAIL
FAIL	cmd/vet	6.212s
FAIL
2019/08/06 10:05:58 Failed: exit status 1
PC089mp:src yoshiki.shibata$ go version
go version devel +a4c825156d Mon Aug 5 23:12:39 2019 +0000 darwin/amd64
PC089mp:src yoshiki.shibata$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
PC089mp:src yoshiki.shibata$ 
```

**Comment by YoshikiShibata** [comment] 2019-08-06 01:24
`go test cmd/vet` doesn't fail, but `all.bash` fails:

```
PC089mp:src yoshiki.shibata$ pwd
/Users/yoshiki.shibata/tools/go/src
PC089mp:src yoshiki.shibata$ go test cmd/vet
ok  	cmd/vet	9.026s
PC089mp:src yoshiki.shibata$ ./all.bash
Building Go cmd/dist using /usr/local/go.
Building Go toolchain1 using /usr/local/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for darwin/amd64.

##### Testing packages.
ok  	archive/tar	0.066s
ok  	archive/zip	0.050s
ok  	bufio	0.058s
ok  	bytes	0.249s
ok  	compress/bzip2	0.118s
ok  	compress/flate	0.480s
ok  	compress/gzip	0.020s
ok  	compress/lzw	0.027s
ok  	compress/zlib	0.042s
ok  	container/heap	0.044s
ok  	container/list	0.039s
ok  	container/ring	0.038s
ok  	context	1.028s
ok  	crypto	0.063s
ok  	crypto/aes	0.048s
ok  	crypto/cipher	0.040s
ok  	crypto/des	0.024s
ok  	crypto/dsa	0.015s
ok  	crypto/ecdsa	0.127s
ok  	crypto/ed25519	0.076s
ok  	crypto/elliptic	0.131s
ok  	crypto/hmac	0.047s
ok  	crypto/internal/subtle	0.016s
ok  	crypto/md5	0.018s
ok  	crypto/rand	0.037s
ok  	crypto/rc4	0.043s
ok  	crypto/rsa	0.105s
ok  	crypto/sha1	0.033s
ok  	crypto/sha256	0.039s
ok  	crypto/sha512	0.042s
ok  	crypto/subtle	0.024s
ok  	crypto/tls	0.934s
ok  	crypto/x509	0.946s
ok  	database/sql	0.581s
ok  	database/sql/driver	0.022s
ok  	debug/dwarf	0.084s
ok  	debug/elf	0.047s
ok  	debug/gosym	0.045s
ok  	debug/macho	0.045s
ok  	debug/pe	0.036s
ok  	debug/plan9obj	0.024s
ok  	encoding/ascii85	0.032s
ok  	encoding/asn1	0.017s
ok  	encoding/base32	0.025s
ok  	encoding/base64	0.024s
ok  	encoding/binary	0.014s
ok  	encoding/csv	0.018s
ok  	encoding/gob	0.028s
ok  	encoding/hex	0.018s
ok  	encoding/json	0.089s
ok  	encoding/pem	0.053s
ok  	encoding/xml	0.042s
ok  	errors	0.066s
ok  	expvar	0.031s
ok  	flag	0.018s
ok  	fmt	0.151s
ok  	go/ast	0.032s
ok  	go/build	0.458s
ok  	go/constant	0.032s
ok  	go/doc	0.089s
ok  	go/format	0.022s
ok  	go/importer	0.143s
ok  	go/internal/gccgoimporter	0.038s
ok  	go/internal/gcimporter	0.653s
ok  	go/internal/srcimporter	0.991s
ok  	go/parser	0.035s
ok  	go/printer	0.225s
ok  	go/scanner	0.023s
ok  	go/token	0.032s
ok  	go/types	0.596s
ok  	hash	0.020s
ok  	hash/adler32	0.017s
ok  	hash/crc32	0.018s
ok  	hash/crc64	0.018s
ok  	hash/fnv	0.077s
ok  	html	0.025s
ok  	html/template	0.084s
ok  	image	0.104s
ok  	image/color	0.051s
ok  	image/draw	0.065s
ok  	image/gif	0.338s
ok  	image/jpeg	0.352s
ok  	image/png	0.048s
ok  	index/suffixarray	0.206s
ok  	internal/cpu	0.047s
ok  	internal/fmtsort	0.129s
ok  	internal/poll	0.043s
ok  	internal/reflectlite	0.020s
ok  	internal/singleflight	0.028s
ok  	internal/trace	0.046s
ok  	internal/xcoff	0.037s
ok  	io	0.050s
ok  	io/ioutil	0.018s
ok  	log	0.022s
ok  	log/syslog	1.266s
ok  	math	0.023s
ok  	math/big	0.272s
ok  	math/bits	0.028s
ok  	math/cmplx	0.037s
ok  	math/rand	0.193s
ok  	mime	0.032s
ok  	mime/multipart	0.323s
ok  	mime/quotedprintable	0.023s
ok  	net	1.969s
ok  	net/http	3.820s
ok  	net/http/cgi	0.892s
ok  	net/http/cookiejar	0.039s
ok  	net/http/fcgi	0.038s
ok  	net/http/httptest	0.087s
ok  	net/http/httptrace	0.091s
ok  	net/http/httputil	0.080s
ok  	net/http/internal	0.016s
ok  	net/http/pprof	2.049s
ok  	net/internal/socktest	0.009s
ok  	net/mail	0.108s
ok  	net/rpc	0.055s
ok  	net/rpc/jsonrpc	0.033s
ok  	net/smtp	0.035s
ok  	net/textproto	0.017s
ok  	net/url	0.032s
ok  	os	1.068s
ok  	os/exec	2.029s
ok  	os/signal	4.895s
ok  	os/user	0.016s
ok  	path	0.021s
ok  	path/filepath	0.048s
ok  	plugin	0.034s
ok  	reflect	0.098s
ok  	regexp	0.062s
ok  	regexp/syntax	0.803s
ok  	runtime	25.971s
ok  	runtime/debug	0.051s
ok  	runtime/internal/atomic	0.022s
ok  	runtime/internal/math	0.012s
ok  	runtime/internal/sys	0.024s
ok  	runtime/pprof	7.878s
ok  	runtime/pprof/internal/profile	0.016s
ok  	runtime/trace	0.558s
ok  	sort	0.080s
ok  	strconv	1.179s
ok  	strings	0.177s
ok  	sync	0.407s
ok  	sync/atomic	0.071s
ok  	syscall	0.218s
ok  	testing	0.063s
ok  	testing/quick	0.051s
ok  	text/scanner	0.030s
ok  	text/tabwriter	0.033s
ok  	text/template	0.113s
ok  	text/template/parse	0.021s
ok  	time	2.643s
ok  	unicode	0.024s
ok  	unicode/utf16	0.023s
ok  	unicode/utf8	0.014s
ok  	cmd/addr2line	2.688s
ok  	cmd/api	0.041s
ok  	cmd/asm/internal/asm	0.864s
ok  	cmd/asm/internal/lex	0.019s
ok  	cmd/compile	0.012s
ok  	cmd/compile/internal/gc	16.098s
ok  	cmd/compile/internal/ssa	0.483s
ok  	cmd/compile/internal/syntax	0.034s
ok  	cmd/compile/internal/test	0.013s [no tests to run]
ok  	cmd/compile/internal/types	0.012s
ok  	cmd/cover	3.438s
ok  	cmd/doc	0.061s
ok  	cmd/fix	0.051s
ok  	cmd/go	76.016s
ok  	cmd/go/internal/auth	0.030s
ok  	cmd/go/internal/cache	1.015s
ok  	cmd/go/internal/dirhash	0.021s
ok  	cmd/go/internal/generate	0.045s
ok  	cmd/go/internal/get	0.048s
ok  	cmd/go/internal/imports	0.045s
ok  	cmd/go/internal/load	0.109s
ok  	cmd/go/internal/lockedfile	0.051s
ok  	cmd/go/internal/lockedfile/internal/filelock	0.054s
ok  	cmd/go/internal/modconv	0.042s
ok  	cmd/go/internal/modfetch	0.135s
ok  	cmd/go/internal/modfetch/codehost	0.027s
ok  	cmd/go/internal/modfile	0.027s
ok  	cmd/go/internal/modload	0.044s
ok  	cmd/go/internal/module	0.020s
ok  	cmd/go/internal/mvs	0.018s
ok  	cmd/go/internal/note	0.032s
ok  	cmd/go/internal/par	0.029s
ok  	cmd/go/internal/renameio	0.503s
ok  	cmd/go/internal/search	0.037s
ok  	cmd/go/internal/semver	0.015s
ok  	cmd/go/internal/sumweb	0.038s
ok  	cmd/go/internal/tlog	1.293s
ok  	cmd/go/internal/txtar	0.034s
ok  	cmd/go/internal/web	0.068s
ok  	cmd/go/internal/work	0.030s
ok  	cmd/gofmt	0.064s
ok  	cmd/internal/buildid	0.230s
ok  	cmd/internal/dwarf	0.021s
ok  	cmd/internal/edit	0.016s
ok  	cmd/internal/goobj	1.228s
ok  	cmd/internal/obj	0.014s
ok  	cmd/internal/obj/arm64	0.128s
ok  	cmd/internal/obj/x86	3.924s
ok  	cmd/internal/objabi	0.013s
ok  	cmd/internal/src	0.022s
ok  	cmd/internal/test2json	0.137s
ok  	cmd/link	4.831s
ok  	cmd/link/internal/ld	8.936s
ok  	cmd/link/internal/sym	0.018s
ok  	cmd/nm	3.827s
ok  	cmd/objdump	3.429s
ok  	cmd/pack	2.113s
ok  	cmd/trace	0.112s
--- FAIL: TestVet (1.97s)
    --- FAIL: TestVet/unsafeptr (0.49s)
        vet_test.go:153: vet output:
        vet_test.go:154: <nil>
    --- FAIL: TestVet/print (0.74s)
        vet_test.go:162: error check failed: 
            print.go:169: missing error "Warn call has possible formatting directive %s"
            print.go:170: missing error "Warnf call needs 1 arg but has 2 args"
            print.go:171: missing error "Warnf format %r has unknown verb r"
            print.go:172: missing error "Warnf format %#s has unrecognized flag #"
            print.go:173: missing error "Warn2 call has possible formatting directive %s"
            print.go:174: missing error "Warnf2 call needs 1 arg but has 2 args"
            print.go:175: missing error "Warnf2 format %r has unknown verb r"
            print.go:176: missing error "Warnf2 format %#s has unrecognized flag #"
FAIL
FAIL	cmd/vet	6.436s
FAIL
2019/08/06 10:22:45 Failed: exit status 1
PC089mp:src yoshiki.shibata$ go version
go version devel +a4c825156d Mon Aug 5 23:12:39 2019 +0000 darwin/amd64
PC089mp:src yoshiki.shibata$ go test cmd/vet
ok  	cmd/vet	3.259s
PC089mp:src yoshiki.shibata$
```

**Comment by cuonglm** [comment] 2019-08-06 02:34
Duplicated of https://github.com/golang/go/issues/32107

**Comment by bcmills** [comment] 2019-08-07 20:14
Duplicate of #32107

**Closed by bcmills** 2019-08-07 20:14 UTC

**Comment by YoshikiShibata** [comment] 2019-10-14 22:50
This issue has been happening until last week on my MacBook Pro, but disappeared this morning:

<pre>
$ go version
go version devel +90888ed97b Mon Oct 14 21:29:11 2019 +0000 darwin/amd64
</pre>
