### ISSUE TITLE
godoc: playground share button does not work

### ISSUE THREAD

**Issue by jeffallen** [golang/go#21691] opened 2017-08-30 07:53 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

The public golang.org docs.

### What did you do?

Find package documentation with an example. I used: https://golang.org/pkg/crypto/md5/#example_New

Edit the code. (Not really necessary, but it was the use case I was trying to do.)

Click Share to share your edited version of the Example with a colleague.

### What did you expect to see?

My edited example ready to share.

### What did you see instead?

The playground editor on a new page with a shareable URL, but with nothing inside of the editor, not the original example, not my changes, nothing. Zip, zero, nada,

**Comment by jeffallen** [comment] 2017-08-30 08:05
Initial debugging with the javascript console leads me to believe that this is on the server side, because the XHR request to "share" with the right stuff in it went out, and the server answered with a share ID, and the client redirected correctly to that share id, but then the script was not present.

Since it is on the server side, I can't debug further.

**Comment by mvdan** [comment] 2017-08-30 09:02
I can reproduce over here. Not sure if it's godoc, the website, or some infra issue. CC @broady

**Comment by ianlancetaylor** [comment] 2017-08-30 12:51
CC @andybons

**Comment by jeffallen** [comment] 2017-08-30 13:07
A working XHR to /share had cloud trace id 1a7cf94f7a76eabd19c1abca6a88fcde. A failing one was b2112108800be2c2ecf7063a634013bc.

Hope that helps.

**Comment by andybons** [comment] 2017-08-30 17:16
I’ll take a look

**Comment by andybons** [comment] 2017-08-30 21:13
Something is going awry with the proxying of the `/share` endpoint. I’ve attached a simple app engine app that can be used to debug locally.

Assigning to @broady to look further.

<details>
<summary>app.yaml</summary>

```yaml
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
```
</details>
<details>
<summary>main.go</summary>

```go
package shareproxy

import (
	"fmt"
	"net/http"
	"net/http/httputil"
	"net/url"

	"google.golang.org/appengine"
	"google.golang.org/appengine/urlfetch"
)

func init() {
	http.HandleFunc("/", handleIndex)
	http.Handle("/share", &server{})
}

const body = `<!DOCTYPE html>
<div>Hello!</div>
<div><textarea>Enter code here</textarea></div>
<div><button>Share</button></div>
<script>
document.querySelector('button').addEventListener('click', e => {
	e.preventDefault();

	async function fetchAsync () {
		let headers = new Headers({
			'X-AppEngine-Country': 'US',
		});

		let opts = {
			method: 'POST',
			body: document.querySelector('textarea').value,
			headers: headers,
		};
		let response = await fetch('/share', opts);
		let data = await response.text();
		return data;
	}

	fetchAsync()
		.then(data => { console.info(data); })
		.catch(err => { console.error(err.message); });
});
</script>
`

func handleIndex(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprintf(w, "%s", body)
}

type server struct{}

func (s *server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	target, err := url.Parse("https://play.golang.org/")
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	p := httputil.NewSingleHostReverseProxy(target)
	p.Transport = &urlfetch.Transport{Context: appengine.NewContext(r)}
	p.ServeHTTP(w, r)
}
```
</summary>
</details>

**Comment by andybons** [comment] 2017-08-30 21:15
I think we should make `/share` (and `/compile`?) available to golang.org via CORS instead of proxying the request. It seems that it would make things a bit easier to debug and result in less code on the backend.

**Comment by andybons** [comment] 2017-08-31 20:20
Updated my code snippet above and it appears to work just fine. I can get this to reproduce with the godoc command (it just proxies to golang.org/share which exhibits the same behavior) but that doesn't say much.

After patching in https://go-review.googlesource.com/#/c/tools/+/46725/ and adding the following to the share func I still can't reproduce.

```go
func share(w http.ResponseWriter, r *http.Request) {
	if !allowShare(r) {
		http.Error(w, "Forbidden", http.StatusForbidden)
		return
	}
	target, _ := url.Parse(playgroundURL)
	p := httputil.NewSingleHostReverseProxy(target)
	r.Header.Set("X-AppEngine-Country", "US")
	p.Transport = &urlfetch.Transport{
		Context: appengine.NewContext(r),
		AllowInvalidServerCertificate: appengine.IsDevAppServer(),
	}
	p.ServeHTTP(w, r)
}
```

**Comment by jeffallen** [comment] 2017-09-15 07:39
This seems to still be broken, is that because the fix is depending on something, or got forgotten?

**Comment by andybons** [comment] 2017-09-15 15:58
@broady can you take a look? You have extensive experience with the playground/golang.org and I’m out of ideas.

**Comment by agnivade** [comment] 2017-09-28 06:08
Go tip doesn't have the embedded playground editor any more. 
https://tip.golang.org/pkg/crypto/md5/#example_New

It just shows the code and its output. 

So I guess, this issue is not applicable anymore ?

**Closed** 2018-01-05 03:31 UTC

**Comment by andybons** [comment] 2018-01-05 03:56
This was an infuriatingly simple fix that took me a while to track down. Apologies for the wait.

The fix is now live on golang.org.
