### ISSUE TITLE
cmd/vet: redeclaration errors when `GOFLAGS` includes a tag for a different GOOS

### ISSUE THREAD

**Issue by powellnorma** [golang/go#64179] opened 2023-11-15 15:18 UTC
### What version of Go are you using (`go version`)?

<pre>
go1.21.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

main.go:

```go
package main

import "fmt"

func main() {
	fmt.Printf("Hello %s\n")
}
```

```sh
$ go vet main.go  # works fine
# command-line-arguments
./main.go:8:2: fmt.Printf format %s reads arg #1, but call has 0 args

$ GOFLAGS=-tags=windows go vet main.go  # internal warnings, but nothing for main.go
# internal/goos
/usr/local/go/src/internal/goos/zgoos_windows.go:7:7: GOOS redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_linux.go:7:7: other declaration of GOOS
/usr/local/go/src/internal/goos/zgoos_windows.go:9:7: IsAix redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_linux.go:9:7: other declaration of IsAix
/usr/local/go/src/internal/goos/zgoos_windows.go:10:7: IsAndroid redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_linux.go:10:7: other declaration of IsAndroid
/usr/local/go/src/internal/goos/zgoos_windows.go:11:7: IsDarwin redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_linux.go:11:7: other declaration of IsDarwin
/usr/local/go/src/internal/goos/zgoos_windows.go:12:7: IsDragonfly redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_linux.go:12:7: other declaration of IsDragonfly
/usr/local/go/src/internal/goos/zgoos_windows.go:13:7: IsFreebsd redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_linux.go:13:7: other declaration of IsFreebsd
/usr/local/go/src/internal/goos/zgoos_windows.go:14:7: IsHurd redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_linux.go:14:7: other declaration of IsHurd
/usr/local/go/src/internal/goos/zgoos_windows.go:15:7: IsIllumos redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_linux.go:15:7: other declaration of IsIllumos
/usr/local/go/src/internal/goos/zgoos_windows.go:16:7: IsIos redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_linux.go:16:7: other declaration of IsIos
/usr/local/go/src/internal/goos/zgoos_windows.go:17:7: IsJs redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_linux.go:17:7: other declaration of IsJs
/usr/local/go/src/internal/goos/zgoos_windows.go:17:7: too many errors
```

### What did you expect to see?

The same output as before (when no `GOFLAGS` was used)

**Comment by powellnorma** [comment] 2023-11-15 15:20
Just found this one: https://github.com/golang/go/issues/45488 - Are there any workarounds?

**Comment by bcmills** [comment] 2023-11-15 18:21
I'm not sure that this is really a bug in `cmd/vet` per se. `GOFLAGS=-tags=windows` specifies that files with `//go:build windows` should be included in packages, but your GOOS is set to `linux`, so `vet` is trying to analyze packages loaded from files for two different (and mutually exclusive) configurations.

(CC @matloob @timothy-king per https://dev.golang.org/owners)

**Comment by powellnorma** [comment] 2023-11-16 19:01
> don't set tags in GOFLAGS that overlap with GOOS tags?

Ok that helps, thank you - This works as expected: `GOOS=windows go vet main.go`

Fyi I didn't have a specific reason to not use GOOS, I just copied it from https://github.com/golang/go/issues/29202#issuecomment-515170916

Perhaps a warning could be displayed when tags are used that don't match the GOOS?

**Comment by raghvenders** [comment] 2023-11-16 23:53
@bcmills @powellnorma - I have encountered the same issue yesterday go vet -tags=linux # internal/goos
and the same issue happens when you do go vet -tags=arm64 # internal/goarch

```
..\..\golang\go\src\internal\goarch\goarch_arm64.go:8:2: _ArchFamily redeclared in this block
        ..\..\golang\go\src\internal\goarch\goarch_amd64.go:8:2: other declaration of _ArchFamily
..\..\golang\go\src\internal\goarch\goarch_arm64.go:9:2: _DefaultPhysPageSize redeclared in this block
        ..\..\golang\go\src\internal\goarch\goarch_amd64.go:9:2: other declaration of _DefaultPhysPageSize
..\..\golang\go\src\internal\goarch\goarch_arm64.go:10:2: _PCQuantum redeclared in this block
        ..\..\golang\go\src\internal\goarch\goarch_amd64.go:10:2: other declaration of _PCQuantum
..\..\golang\go\src\internal\goarch\goarch_arm64.go:11:2: _MinFrameSize redeclared in this block
        ..\..\golang\go\src\internal\goarch\goarch_amd64.go:11:2: other declaration of _MinFrameSize
..\..\golang\go\src\internal\goarch\goarch_arm64.go:12:2: _StackAlign redeclared in this block
        ..\..\golang\go\src\internal\goarch\goarch_amd64.go:12:2: other declaration of _StackAlign
..\..\golang\go\src\internal\goarch\zgoarch_arm64.go:7:7: GOARCH redeclared in this block
        ..\..\golang\go\src\internal\goarch\zgoarch_amd64.go:7:7: other declaration of GOARCH
..\..\golang\go\src\internal\goarch\zgoarch_arm64.go:9:7: Is386 redeclared in this block
        ..\..\golang\go\src\internal\goarch\zgoarch_amd64.go:9:7: other declaration of Is386
..\..\golang\go\src\internal\goarch\zgoarch_arm64.go:10:7: IsAmd64 redeclared in this block
        ..\..\golang\go\src\internal\goarch\zgoarch_amd64.go:10:7: other declaration of IsAmd64
..\..\golang\go\src\internal\goarch\zgoarch_arm64.go:11:7: IsAmd64p32 redeclared in this block
        ..\..\golang\go\src\internal\goarch\zgoarch_amd64.go:11:7: other declaration of IsAmd64p32
..\..\golang\go\src\internal\goarch\zgoarch_arm64.go:12:7: IsArm redeclared in this block
        ..\..\golang\go\src\internal\goarch\zgoarch_amd64.go:12:7: other declaration of IsArm
..\..\golang\go\src\internal\goarch\zgoarch_arm64.go:12:7: too many errors

```
@matloob @timothy-king - I tried to run vet_test.go -> TestTags -> (c *Cmd) CombinedOutput() -> c.Stderr. is this stack data pushed into error?

**Comment by timothy-king** [comment] 2023-11-17 00:36
> go vet -tags=arm64 # internal/goarch

`GOARCH=arm64 gotip vet` should work as a short term solution. A longer term solution will take some investigation.

**Comment by raghvenders** [comment] 2023-11-20 03:29
Thanks @timothy-king . I have done investigation and started a fix for that. It is not just for vet , impacts for build too. So testing more scenarios and here is the CL - https://go-review.googlesource.com/c/go/+/543675

**Comment by matloob** [comment] 2023-12-11 20:01
I agree with @bcmills that this doesn't seem to be a bug.

**Comment by raghvenders** [comment] 2023-12-11 20:15
It is expected not to include both os files under internal/goos for windows and linux. But it does. This happens for go build too.
So we have to have a way to ignore conflicting env variable values and the same used as flag. This is what I am thinking.

@bcmills  - your thoughts.

**Comment by bcmills** [comment] 2023-12-11 22:35
@raghvenders, we do not expect Go users to set `-tags=windows` explicitly, since that tag is reserved to mean `GOOS=windows`.

(There may be some tools — such as static analyzers — that set it explicitly in `go list` to get additional files, but those tools do not expect to also run the Go compiler in that configuration.)

**Comment by rsc** [comment] 2024-05-28 19:45
This is not a bug, and it is not about go vet. Using `GOOS=linux go build -tags windows runtime` fails as well.
I think we can close this as not a bug.

**Closed by rsc** 2024-05-28 19:45 UTC
Labels: NeedsInvestigation
