### ISSUE TITLE
net: TestWriteTimeoutFluctuation sometimes fails on 32-bit iOS builder

### ISSUE THREAD

**Issue by mikioh** [golang/go#10775] opened 2015-05-11 04:24 UTC
See build dashboard.
http://build.golang.org/log/b02e6aaa2fe497fadf898192d5425e7201569703
http://build.golang.org/log/350de48b4c0e31390ac02f7a1af96c22401a5628
http://build.golang.org/log/58502b25b5c6dc158954ba111690223cb5bc078f
http://build.golang.org/log/2bb42bac80498052be38e335298d05b43d370f1a

No errors at the package API, looks like timeoutTransmitter goroutine is not scheduled well, not sure the reason but seems like it needs further investigation.

```
process continue
Process 580 resuming
--- FAIL: TestWriteTimeoutFluctuation (1.89s)

    timeout_test.go:706: Write took over 1s; expected 0.1s

FAIL

Process 580 exited with status = 1 (0x00000001) 
go_darwin_arm_exec: timeout running tests
```

**Comment by bcmills** [comment] 2021-01-22 14:45
Duplicate of #36108

**Closed by bcmills** 2021-01-22 14:45 UTC
Labels: OS-Darwin
