### ISSUE TITLE
cmd/go: go get no longer creates $GOPATH/pkg dir in 1.10

### ISSUE THREAD

**Issue by asottile** [golang/go#24360] opened 2018-03-12 21:00 UTC
### What version of Go are you using (`go version`)?

```
$ go version
go version go1.10 linux/amd64
```

### Does this issue reproduce with the latest release?

Yes, 1.10 is currently the latest release

### What operating system and processor architecture are you using (`go env`)?

```
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/asottile/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/test/gopath"
GORACE=""
GOROOT="/tmp/test/go"
GOTMPDIR=""
GOTOOLDIR="/tmp/test/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build899975321=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

```bash
rm -rf gopath
mkdir gopath
export GOPATH=$PWD/gopath
go get github.com/golang/example/hello
ls gopath
```

### What did you expect to see?

```console
...
$ ls gopath
bin pkg src
```

### What did you see instead?

(for the other version of go I have installed (1.6.2) I see this)

```console
$ ls gopath
bin  src
```

**Comment by asottile** [comment] 2018-03-12 21:00
Not a big deal -- just I didn't see any mention of this in the changelog (or I missed it!)

**Comment by mvdan** [comment] 2018-03-12 21:48
See the caching changes - cached package builds now reside in $GOCACHE.

**Comment by asottile** [comment] 2018-03-12 21:52
The docs mention the new cache, but are a bit brief about the `pkg` directory: https://tip.golang.org/doc/go1.10#build

**Comment by mvdan** [comment] 2018-03-12 21:57
It's not terribly clear whether or not $GOPATH/pkg is used anymore, so I'm going to reopen for now.

**Comment by shurcooL** [comment] 2018-03-20 18:43
This is related to (or duplicate of) issue #4719.

**Comment by ianlancetaylor** [comment] 2018-03-27 14:39
Running `go get` is documented as fetching the binaries and then running `go install`.  The same change has occurred for `go install`: the `pkg` directory is not created if you install a main package.  This is documented in the release notes for Go 1.10:

> The go install command now installs only the packages and commands listed directly on the command line. For example, go install cmd/gofmt installs the gofmt program but not any of the packages on which it depends. The new build cache makes future commands still run as quickly as if the dependencies had been installed. To force the installation of dependencies, use the new go install -i flag. Installing dependency packages should not be necessary in general, and the very concept of installed packages may disappear in a future release.

Since `go get` is documented to effectively use `go install`, and since `go install` is documented as having changed, I don't think there is anything to do here.

**Closed by ianlancetaylor** 2018-03-27 14:39 UTC
Labels: NeedsInvestigation
