### ISSUE TITLE
cmd/compile: bad line number for "missing type in composite literal"

### ISSUE THREAD

**Issue by josharian** [golang/go#18231] opened 2016-12-07 18:46 UTC
```go
package main

type T struct {
	f map[string]string
}

func main() {
	_ = T{
		f: {
			"a": "b",
		},
	}
}
```

```bash
$ go build x.go 
# command-line-arguments
./x.go:10: missing type in composite literal
```

Line 10 is `"a": "b",`. The missing type is `map[string]string`, and it belongs on line 9 (`f: {`).

Low priority. Possibly will be fixed for free by the fix to #16943.

cc @mdempsky @odeke-em

**Comment by griesemer** [comment] 2016-12-07 18:51
Doesn't look like a regression (same behavior in 1.7, 1.6, and 1.5.). Yes, this should be fixed as part of #16943. Leaving as separate issue so test this case explicitly.

**Comment by griesemer** [comment] 2017-02-08 23:58
Assigning to @mdempsky since he is looking at a more principled setup if line numbers.

**Comment by griesemer** [comment] 2017-02-15 01:06
This is unrelated to #16943. Fix forthcoming.

**Closed** 2017-02-15 01:34 UTC
