### ISSUE TITLE
cmd/go: long test fails (TestAccidentalGitCheckout)

### ISSUE THREAD

**Issue by ysmolsky** [golang/go#24436] opened 2018-03-17 10:01 UTC
### What version of Go are you using (`go version`)?

`go version devel +2767c4e285 Fri Mar 16 21:01:28 2018 +0000 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/thorn/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/thorn/go"
GORACE=""
GOROOT="/Users/thorn/golang"
GOTMPDIR=""
GOTOOLDIR="/Users/thorn/golang/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/km/50gy6_q557v6_7vxbf9b29v00000gn/T/go-build428090470=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

Running ./all.bash does not fail in any of tests: `ALL TESTS PASSED`. 

When I run `go test cmd/go` I get these failed tests:
```
~/golang/src % go test cmd/go
--- FAIL: TestGoBuildDashAInDevBranch (0.30s)
	go_test.go:833: running testgo [install math]
	go_test.go:835: running testgo [build -v -a math]
	go_test.go:835: standard error:
	go_test.go:835: internal/cpu
		math

	go_test.go:836: testgo build -a math in dev branch DID NOT build runtime, but should have
	go_test.go:836: pattern runtime not found in standard error
--- FAIL: TestGoBuildDashAInReleaseBranch (0.47s)
	go_test.go:849: running testgo [install math net/http]
	go_test.go:851: running testgo [install -v -a math]
	go_test.go:851: standard error:
	go_test.go:851: internal/cpu
		math

	go_test.go:852: testgo build -a math in release branch DID NOT build runtime, but should have
	go_test.go:852: pattern runtime not found in standard error
--- FAIL: TestNewReleaseRebuildsStalePackagesInGOPATH (3.13s)
	go_test.go:892: running testgo [install -a p1]
	go_test.go:893: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
	go_test.go:893: standard output:
	go_test.go:893: false:

	go_test.go:902: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
	go_test.go:902: standard output:
	go_test.go:902: false:

	go_test.go:909: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
	go_test.go:909: standard output:
	go_test.go:909: false:

	go_test.go:909: ./testgo list claims p1 is NOT stale, incorrectly, after changing sys.go
--- FAIL: TestBuildIDContainsArchModeEnv (2.62s)
    --- FAIL: TestBuildIDContainsArchModeEnv/386 (1.23s)
    	go_test.go:4716: running testgo [install mycmd]
    	go_test.go:4718: running testgo [list -f {{.Stale}}:{{.StaleReason}} mycmd]
    	go_test.go:4718: standard output:
    	go_test.go:4718: true:stale dependency: runtime

    	go_test.go:4718: wrong reason for Stale=true: "stale dependency: runtime", want "stale dependency: runtime/internal/sys"
    --- FAIL: TestBuildIDContainsArchModeEnv/arm (1.39s)
    	go_test.go:4716: running testgo [install mycmd]
    	go_test.go:4718: running testgo [list -f {{.Stale}}:{{.StaleReason}} mycmd]
    	go_test.go:4718: standard output:
    	go_test.go:4718: true:stale dependency: runtime

    	go_test.go:4718: wrong reason for Stale=true: "stale dependency: runtime", want "stale dependency: runtime/internal/sys"
--- FAIL: TestAccidentalGitCheckout (0.85s)
	go_test.go:1465: running testgo [get -u vcs-test.golang.org/go/test1-svn-git]
	go_test.go:1465: standard error:
	go_test.go:1465: package vcs-test.golang.org/go/test1-svn-git: unrecognized import path "vcs-test.golang.org/go/test1-svn-git" (https fetch: Get https://vcs-test.golang.org/go/test1-svn-git?go-get=1: x509: certificate has expired or is not yet valid)

	go_test.go:1465: testgo failed as expected: exit status 1
	go_test.go:1466: get did not fail for right reason
	go_test.go:1466: pattern src[\\/]vcs-test.* uses git, but parent .*src[\\/]vcs-test.* uses svn not found in standard error
--- FAIL: TestMoveHG (0.37s)
	go_test.go:1272: running testgo [get -d vcs-test.golang.org/go/custom-hg-hello]
	go_test.go:1272: standard error:
	go_test.go:1272: package vcs-test.golang.org/go/custom-hg-hello: unrecognized import path "vcs-test.golang.org/go/custom-hg-hello" (https fetch: Get https://vcs-test.golang.org/go/custom-hg-hello?go-get=1: x509: certificate has expired or is not yet valid)

	go_test.go:1272: go [get -d vcs-test.golang.org/go/custom-hg-hello] failed unexpectedly: exit status 1
FAIL
FAIL	cmd/go	268.072s
```
Also it takes 268 seconds compared to all.bash: `ok  	cmd/go	59.136s`

### What did you expect to see?

No errors.

**Comment by ALTree** [comment] 2018-03-17 10:19
To add another data point, I can reproduce this on tip on linux/amd64.

> Also it takes 268 seconds compared to all.bash: ok cmd/go 59.136s

This is expected because `all.bash` runs the tests using the `-short` flag. Time-consuming tests that are skipped by `all.bash` get executed when you manually run `go test`.

**Comment by ysmolsky** [comment] 2018-03-17 20:36
More about stale dependencies:
```
thorn@t2 ~/go/src % cat p1/p1.go
package p1
import _ "p2"

thorn@t2 ~/go/src % cat p2/p2.go
package p2
const V = "1"

thorn@t2 ~/go/src % go install p1
thorn@t2 ~/go/src % go list -f {{.Stale}}:{{.StaleReason}} p1
true:stale dependency: p2
thorn@t2 ~/go/src % go install -x p1
WORK=/var/folders/km/50gy6_q557v6_7vxbf9b29v00000gn/T/go-build239446833
rm -r $WORK/b001/
```

**Comment by alexd765** [comment] 2018-03-19 20:35
This has been failing for quite some time.

Git bisect points to [76015](https://go-review.googlesource.com/c/go/+/76015)

**Comment by ysmolsky** [comment] 2018-03-20 14:58
ping @rsc

**Comment by ysmolsky** [comment] 2018-03-29 14:53
Doing research regarding `TestGoBuildDashA*` tests. CL 76015 removed dependency on `runtime` package for non-main packages, so that go build -a `math` does not rebuild `runtime` anymore. Also `TestGoBuildDashAInReleaseBranch` tested some hack about preventing rebuilding system packages in release branch. I have not found any need to test that behaviour anymore.

Also I could not find environment variable `"TESTGO_IS_GO_RELEASE` anywhere else except in those two tests. So I assume that it can be removed completely along with `TestGoBuildDashAInReleaseBranch` test b/c there is not need for testing release branch there anymore and we can just have general `TestGoBuildDashA` test.

**Comment by ysmolsky** [comment] 2018-05-20 08:07
The only remaining fix: https://golang.org/cl/103416 

ping @ianlancetaylor @rsc

**Comment by ysmolsky** [comment] 2018-05-31 15:32
TestNewReleaseRebuildsStalePackagesInGOPATH still fails on linux-amd64-longtest:
https://build.golang.org/log/412d4a44a2469e2919309a2ec9b3765d3a1de7a7

I am unable to reproduce this locally on darwin. Any ideas how can I do it?

```
--- FAIL: TestNewReleaseRebuildsStalePackagesInGOPATH (4.60s)
    go_test.go:902: running testgo [install -i p1]
    go_test.go:903: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
    go_test.go:903: standard output:
    go_test.go:903: false:
        
    go_test.go:912: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
    go_test.go:912: standard output:
    go_test.go:912: false:
        
    go_test.go:919: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
    go_test.go:919: standard output:
    go_test.go:919: true:stale dependency: runtime/internal/sys
        
    go_test.go:921: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
    go_test.go:921: standard output:
    go_test.go:921: false:
        
    go_test.go:923: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
    go_test.go:923: standard output:
    go_test.go:923: true:stale dependency: runtime/internal/sys
        
    go_test.go:924: running testgo [install -i p1]
    go_test.go:925: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
    go_test.go:925: standard output:
    go_test.go:925: false:
        
    go_test.go:929: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
    go_test.go:929: standard output:
    go_test.go:929: false:
        
    go_test.go:929: ./testgo list claims p1 is NOT stale, incorrectly, after restoring sys.go
```

**Comment by ianlancetaylor** [comment] 2018-05-31 19:16
I can't recreate the `TestNewReleaseRebuildsStalePackagesInGOPATH` failure when I run the test by itself, but I run simply `go test cmd/go` I do see the failure.

**Comment by ianlancetaylor** [comment] 2018-05-31 19:17
Wait, I think I got confused, sorry.

**Comment by ysmolsky** [comment] 2018-07-13 09:44
Long test from tip passes on my darwin (El Capitan). It still [fails](https://build.golang.org/log/731f5d061895beb868fd85fec7059ed6146284b4) on linux builder:
```
--- FAIL: TestNewReleaseRebuildsStalePackagesInGOPATH (4.65s)
    go_test.go:906: running testgo [install -i p1]
    go_test.go:907: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
    go_test.go:907: standard output:
    go_test.go:907: false:
        
    go_test.go:916: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
    go_test.go:916: standard output:
    go_test.go:916: false:
        
    go_test.go:923: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
    go_test.go:923: standard output:
    go_test.go:923: true:stale dependency: runtime/internal/sys
        
    go_test.go:925: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
    go_test.go:925: standard output:
    go_test.go:925: false:
        
    go_test.go:927: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
    go_test.go:927: standard output:
    go_test.go:927: true:stale dependency: runtime/internal/sys
        
    go_test.go:928: running testgo [install -i p1]
    go_test.go:929: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
    go_test.go:929: standard output:
    go_test.go:929: false:
        
    go_test.go:933: running testgo [list -f {{.Stale}}:{{.StaleReason}} p1]
    go_test.go:933: standard output:
    go_test.go:933: false:
        
    go_test.go:933: ./testgo list claims p1 is NOT stale, incorrectly, after restoring sys.go
go test proxy starting
go test proxy running at GOPROXY=http://127.0.0.1:38065/mod
--- FAIL: TestAccidentalGitCheckout (6.01s)
    go_test.go:1527: running testgo [get -u vcs-test.golang.org/go/test1-svn-git]
    go_test.go:1527: standard error:
    go_test.go:1527: package vcs-test.golang.org/go/test1-svn-git/git-README-only/pkg: directory "/tmp/gotest830344226/src/vcs-test.golang.org/go/test1-svn-git/git-README-only" uses git, but parent "/tmp/gotest830344226/src/vcs-test.golang.org/go/test1-svn-git" uses svn
        
    go_test.go:1527: testgo failed as expected: exit status 1
    go_test.go:1530: running testgo [get -u vcs-test.golang.org/go/test2-svn-git/test2main]
    go_test.go:1530: standard error:
    go_test.go:1530: package vcs-test.golang.org/go/test2-svn-git/test2pkg/pkg: cannot find package "vcs-test.golang.org/go/test2-svn-git/test2pkg/pkg" in any of:
        	/workdir/go/src/vcs-test.golang.org/go/test2-svn-git/test2pkg/pkg (from $GOROOT)
        	/tmp/gotest830344226/src/vcs-test.golang.org/go/test2-svn-git/test2pkg/pkg (from $GOPATH)
        
    go_test.go:1530: testgo failed as expected: exit status 1
    go_test.go:1531: get did not fail for right reason
    go_test.go:1531: pattern src[\\/]vcs-test.* uses git, but parent .*src[\\/]vcs-test.* uses svn not found in standard error
FAIL
FAIL	cmd/go	244.229s
2018/07/13 04:12:40 Failed: exit status 1
```

**Comment by mvdan** [comment] 2018-07-13 14:11
I can reproduce both failures on my Linux laptop - will try to investigate.

**Comment by mvdan** [comment] 2018-07-13 15:56
I think I wrapped my mind around what was happening in the first failure - sent the CL above.

I'm giving up on the second one for now, as I don't know enough about how `go get -u` works when mixing svn and git. Although it seems to me like the vcs-test package has been broken, as now using `go get -u` tries to get the non-existing `test2pkg/pkg` subpackage.

**Comment by ysmolsky** [comment] 2018-07-22 07:52
I have found something about `TestAccidentalGitCheckout`. It fetches repo which has partly-capitalized directory `test2PKG` inside, while the main package imports it using `test2PKG` and `test2pkg`. Apparrently, Linux cannot find the lowercase variant, while it works on MacOS. 

```
% pwd
/Users/thorn/go/src/vcs-test.golang.org/go/test2-svn-git
% tree
.
├── test2PKG
│   ├── p1
│   │   └── p1.go
│   └── pkg
│       └── pkg.go
└── test2main
    └── main.go

% cat test2main/main.go
package main

import _ "vcs-test.golang.org/go/test2-svn-git/test2PKG/p1"
import _ "vcs-test.golang.org/go/test2-svn-git/test2pkg/pkg"

func main() {}
```

**Comment by ysmolsky** [comment] 2018-07-23 07:05
I don't see how to modify those files according to https://github.com/golang/build/blob/master/vcs-test/README.md

Also this bug was already filed: #22983

**Comment by bcmills** [comment] 2018-08-02 17:32
Closing as a dup of #22983. Since that was reported on 1.9.2, it doesn't need to be a release-blocker.

**Closed by bcmills** 2018-08-02 17:32 UTC
Labels: NeedsInvestigation, Testing, release-blocker
