### ISSUE TITLE
net/http: Client should cache 301/308 redirect

### ISSUE THREAD

**Issue by yonderblue** [golang/go#29776] opened 2019-01-17 02:25 UTC
### What version of Go are you using (`go version`)?

go1.11.1

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

linux amd64, android arm

### What did you do?

Used http.Client for multiple calls against a url that returns 301 or 308.

### What did you expect to see?

Second invocation to use a cached response from the first.

### What did you see instead?

The first call before the Location is followed is always made.

Is there any reason this choice was made or has the logic just never been put in?

**Comment by bradfitz** [comment] 2019-01-17 05:37
Never considered either way.

**Comment by rsc** [comment] 2019-05-01 18:22
The http.Client does _no_ caching of responses at all. It's not just 301/308.

What is the context here? Is there a situation where this is causing problems? Also, if you are making the same request repeatedly, why is it problematic to be repeating the redirected call but not problematic to be repeating the final call?

**Comment by odeke-em** [comment] 2019-10-14 07:09
I believe @gaillard filed this issue since `301: Moved Permanently` and `308: Permanent Redirect` both have permanency in them, thus we can assume that those responses will never change, so perhaps we can consider these as cacheable.

**Comment by odeke-em** [comment] 2019-10-14 07:11
The issue though is that what happens if we have uncapped/unlimited response caching and many responses are cached; what if a server responds with refresh deadline/tokens in the 301/308 responses?

**Comment by odeke-em** [comment] 2024-02-26 14:18
@neild @bradfitz what do y'all think about the points that I raised here https://github.com/golang/go/issues/29776#issuecomment-541527066? Or perhaps we can use some sort of bounded cache or perhaps an LRU of fixed size containing domain+code whose keys when being evicted pop from the map[domain+code]->response

**Comment by seankhliao** [comment] 2024-12-02 22:08
closing as working as intended.

**Closed by seankhliao** 2024-12-02 22:08 UTC
Labels: NeedsDecision
