### ISSUE TITLE
affected/package:  M1苹果笔记本，在动态的build plugin时， 在执行 pligun.Open时，报错：plugin was built with a different version of package internal/cpu

### ISSUE THREAD

**Issue by lihaitao2502** [golang/go#56523] opened 2022-11-02 10:43 UTC
M1苹果笔记本，在动态的build plugin时， 在执行 pligun.Open时，报错：plugin was built with a different version of package internal/cpu

**Comment by bcmills** [comment] 2022-11-02 13:24
Duplicate of #27751

**Closed by bcmills** 2022-11-02 13:24 UTC
