### ISSUE TITLE
runtime, os: Go program run in docker pid 1 does not generate core dump

### ISSUE THREAD

**Issue by strrchr** [golang/go#34177] opened 2019-09-08 17:31 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13rc1

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/opt/PyAutoPush/opt/go1.13beta1/gopath"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/opt/PyAutoPush/opt/go1.13beta1/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/PyAutoPush/opt/go1.13beta1/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/opt/PyAutoPush/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build096703828=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
GOTRACEBACK=crash
golang program run in docker pid 1 does not generate core dump

### What did you expect to see?
I want to generate a core dump.

### What did you see instead?
No core dump generated.

**Comment by odeke-em** [comment] 2019-09-08 23:38
Hello @strrchr, thank you for this question and welcome to the Go project!

To make this issue actionable:
a) could you please provide a sample/minimal reproducing program and how you ran it, that you used to come to this conclusion? For example, you could report that it could have been
```go
package main

func main() {
    panic("Bye")
}
```
Please report the source code of what you could use to reproduce the problem.

b) Please list how you are starting the container in your Dockerfile. The step with which you passed in `GOTRACEBACK` when running your dockerize app might show you why it failed e.g. if you used `CMD ["GOTRACEBACK=1", "./proc"]` I believe this doesn't work
c) I've heard about issues with PID 1 ignoring signals unless explicitly coded to do so https://docs.docker.com/v17.12/engine/reference/run/#foreground but I am not a Docker expert
d) Do other process successfully generate the core dump and not just the PID 1 process?

Thank you!

**Comment by strrchr** [comment] 2019-09-09 13:24
Thank you!
Finally, I figure out that it's PID 1 problem.
When go program run as PID 1 and panic, no core dump generated.

**Comment by odeke-em** [comment] 2019-09-09 14:12
Thank you for the confirmation that it is a PID 1 issue that's agnostic of the binary's source. Please examine how to get your binaries running as non-PID 1. I shall close this issue as the issue is related to Docker and not to Go but please don't hesitate to reach out in case of any other issues.

**Closed by odeke-em** 2019-09-09 14:12 UTC
Labels: WaitingForInfo
