### ISSUE TITLE
mail.Address.String() does not take care of non-ASCII name with comma

### ISSUE THREAD

**Issue by cention-sany** [golang/go#12782] opened 2015-09-29 09:54 UTC
1. go version 1.4.2
2. Linux sanydellubuntu 3.19.0-30-generic #33-Ubuntu SMP Mon Sep 21 20:58:04 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
3. See my code below.
4. I expected mail.Address.String() can escape the comma for non-ASCII characters.
5. Comma is output without escape and cause error *mail: no angle-addr* during parsing.

```
package main

import (
	"log"
	"net/mail"
)

func formatEmailAddress(emailaddress, name string) string {
	a := new(mail.Address)
	if "" == emailaddress {
		return ""
	}
	a.Address = emailaddress
	if "" != name {
		a.Name = name
	}
	return a.String()
}

func main() {
	s := formatEmailAddress("test.mail@gmail.com", "naé, mée")
	log.Println(s)
	a, err := mail.ParseAddress(s)
	if nil != err {
		log.Println("error because:", err)
	} else {
		log.Println("name is:", a.Name, "email is:", a.Address)
	}
}
```

**Comment by alexcesaro** [comment] 2015-09-29 10:21
This is a duplicate of #11292. I will fix that bug when [CL 14957](https://go-review.googlesource.com/#/c/14957/2) is merged.

**Comment by adg** [comment] 2015-10-20 23:19
Closing as dupe

**Closed by adg** 2015-10-20 23:19 UTC
