### ISSUE TITLE
gofmt: fails to format when { is below the function name and args

### ISSUE THREAD

**Issue by miguelfrde** [golang/go#48690] opened 2021-09-29 23:19 UTC
### What version of Go are you using (`go version`)?
1.17.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
linux_amd64, but I repro this in the playground.

### What did you do?

This can't be formatted: https://play.golang.org/p/mN2jk-rv3kC
```
package main

import (
	"fmt"
)

func main()
{
	fmt.Println("Hello, playground")
}

```

This can be formatted: https://play.golang.org/p/28MgDcekZ6v

```
package main

import (
	"fmt"
)

func main(){
	fmt.Println("Hello, playground")
}

```

### What did you expect to see?

I expected both to be formatted.

### What did you see instead?

On format: 
```
prog.go:8:1: unexpected semicolon or newline before {
```

On run:

```
./prog.go:7:6: missing function body
./prog.go:8:1: syntax error: unexpected semicolon or newline before {
```

**Comment by ianlancetaylor** [comment] 2021-09-29 23:31
That is how the language works.  `func main()` without the `{` is permitted; it is a function declaration for a function declared in assembler (https://golang.org/ref/spec#Function_declarations).  Therefore, gofmt does not attempt to move the `{` earlier.  See also https://golang.org/ref/spec#Semicolons.  This is working as intended, so closing the issue.

**Closed by ianlancetaylor** 2021-09-29 23:31 UTC
