### ISSUE TITLE
x/net/http/httpproxy: http_proxy breaking changes in 1.16.x

### ISSUE THREAD

**Issue by lz-dc** [golang/go#45227] opened 2021-03-25 06:49 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.16.2
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
All
</pre></details>

### What did you do?

https://play.golang.org/p/cmTZDVvftc5

### What did you expect to see?
The above sample code works fine with go1.15.8

### What did you see instead?
The flow fails to use the proxy.

**Comment by seankhliao** [comment] 2021-03-25 08:01
This is an intentional change as part of #40909 and documented in the [1.16 release notes](https://golang.org/doc/go1.16#net/http):

> The ProxyFromEnvironment function no longer returns the setting of the HTTP_PROXY environment variable for https:// URLs when HTTPS_PROXY is unset.

Closing as working as intended

**Closed by seankhliao** 2021-03-25 08:01 UTC

**Comment by lz-dc** [comment] 2021-03-25 08:17
> This is an intentional change as part of #40909 and documented in the [1.16 release notes](https://golang.org/doc/go1.16#net/http):
> 
> > The ProxyFromEnvironment function no longer returns the setting of the HTTP_PROXY environment variable for https:// URLs when HTTPS_PROXY is unset.
> 
> Closing as working as intended

What was the rational behind this? http/https proxy is not tied to the end-point and enterprise configure http proxy for both non-ssl and ssl end-points.
