### ISSUE TITLE
x/tools/gopls: completion fails for incomplete function literal parameter types

### ISSUE THREAD

**Issue by seh** [golang/go#36479] opened 2020-01-09 15:56 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

The version of _gopls_ is fairly recent, as of this writing:
```
golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/seh/Library/Caches/go-build"
GOENV="/Users/seh/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/seh/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/seh/src/uber/kubernetes/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d5/r0rch5j95zjcjmh12gzb7lfc0000gn/T/go-build161365972=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Using an editor that inserts balanced delimiters—such as a closing parenthesis character after typing an opening parenthesis character—try to complete the function literal parameter type `config` at the cursor position, denoted by `<>` here:
```go
type config struct {
}

type Option func(*config) error

func WithSomeOption(n int) Option {
	return func(c *co<>)
}
```

### What did you expect to see?

_gopls_ would respond to the editor's request for completion there, and supply the identifier `config` as a good option.

### What did you see instead?

_gopls_ stalls for a long while, but never produces any suggestions for completion.

If I delete the closing parenthesis after the `co` above, like this, _gopls_ **does** offer completion suggestions:
```go
func WithSomeOption(n int) Option {
	return func(c *co<>
}
```
Similarly, if I round out more of the function literal, and move the cursor back after "co," _gopls_ will offer completion suggestions:
```go
func WithSomeOption(n int) Option {
	return func(c *co<>) error {
	}
}
```

I can see that in various states of being incomplete, this is not yet valid code. However, given the propensity for editors to help us with balanced delimiter insertion, it would be nice to accommodate completion in this situation.

**Comment by KarthikNayak** [comment] 2021-06-01 16:53
This is no longer an issue, can you can confirm @seh?

See the below screenshot
![2021-06-01-184902_3840x1080_scrot](https://user-images.githubusercontent.com/1786334/120361802-9877a800-c30a-11eb-91c7-01dbfd9bc459.png)

**Comment by seh** [comment] 2021-06-01 17:22
I find that if I start with just the opening parenthesis character like this,
```go
return func(c *co<>
```
then the completion suggestions work as expected. However, if I allow my editor's insertion of balanced delimiters to proceed, such that I start with the closing parenthesis in place,
```go
return func(c *co<>)
```
then completion fails when _gopls_ reports the following error:
> LSP :: Error from the Language Server: analysis ST1006 for package github.com/myorg/myrepo/path/to/package panicked: interface conversion: interface {} is nil, not *buildir.IR (Unknown error)

**Comment by stamblerre** [comment] 2021-06-01 20:33
The staticcheck errors are actually unrelated to the completion results. These are errors logged by `gopls`, but they shouldn't be user-facing. I believe that the Emacs LSP integration shows logged errors to the user, which is something that's likely been reported on their issue tracker (it shouldn't happen). Do you see anything in the logs from the completion request when you trigger the completion at that location?

**Comment by seh** [comment] 2021-06-01 20:49
In the _\*lsp-log\*_ buffer, every time I type a character in the position shown above, I see a message like the following:
```
2021/06/01 16:46:22 imports fixes: AllImportsFixes: /Users/seh/src/path/to/file.go:57:9: expected expression
	file="/Users/seh/src/path/to/file.go"
```
I can't find any other output that seems related.

**Comment by KarthikNayak** [comment] 2021-06-01 20:49
> then the completion suggestions work as expected. However, if I allow my editor's insertion of balanced delimiters to proceed, such that I start with the closing parenthesis in place,
> 
> ```go
> return func(c *co<>)
> ```

Interesting, this is the scenario I tried to reproduce too. You can actually see the closing parenthesis in my image.

**Comment by seh** [comment] 2021-06-01 20:52
This could be due to a bunch of other Emacs packages just being too old. I'm using Aquamacs version 3.5, built atop Emacs version 25.3.50.1, which holds back from being able to update some packages that have declared that they don't work on anything older than Emacs 26.

If you can't reproduce the problem and wish to move on, I can accept that. Aquamacs may finally leap forward again in the coming months, and then all of this might just work itself out.

**Comment by stamblerre** [comment] 2021-06-01 20:56
If you can increase the verbosity of your logs, we can continue troubleshooting: https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capture-logs. However, it is possible that there is some issue with caused by Emacs here. Also, can you please confirm that you are using the latest version of `gopls` (v0.6.11), or you can upgrade by running `GO111MODULE=on go get golang.org/x/tools/gopls`.

**Closed** 2023-01-26 13:30 UTC
Labels: help wanted, WaitingForInfo, NeedsInvestigation, gopls, Tools
