### ISSUE TITLE
x/text: unicode/bidi/core.go:489 Defect type: UNUSED_VALUE

### ISSUE THREAD

**Issue by opohorel** [golang/go#46230] opened 2021-05-18 11:18 UTC
Static analyzer has detected this issue in x/text/unicode/bidi/core.go:489.
As I'm not familiar with golang and x/text, this could be a false positive. 

```
git-lfs-2.13.3/_build/src/github.com/git-lfs/git-lfs/vendor/golang.org/x/text/unicode/bidi/core.go:489: assigned_value: Assigning value "10" to "precedingCharacterType" here, but that stored value is overwritten before it can be used. 

   487|   		} else {
   488|   			if t.in(LRI, RLI, FSI, PDI) {
   489|-> 				precedingCharacterType = ON
   490|   			}
   491|   			precedingCharacterType = t
```

**Comment by davecheney** [comment] 2021-05-18 11:27
Which tool is this?

**Comment by opohorel** [comment] 2021-05-18 11:35
> Which tool is this?

Red Hat Coverity Scan that ran on git-lfs package. It detected an issue in bundled dependency x/text.
The same scan also detected #46231 in x/sync.

**Comment by davecheney** [comment] 2021-05-18 11:56
Please feel free to send a PR.

**Comment by bcmills** [comment] 2021-05-18 17:46
Duplicate of #43623

**Closed by bcmills** 2021-05-18 17:46 UTC
Labels: help wanted
