### ISSUE TITLE
doc: update "Hello world" tutorial's text on what "go install" does

### ISSUE THREAD

**Issue by kapcove** [golang/go#24251] opened 2018-03-05 16:02 UTC
The [hello world tutorial](https://golang.org/doc/code.html) states that

> Whenever the go tool installs a package or binary, it also installs whatever dependencies it has.

This only happens if the `-i` flag is given to the `go install` command. The file hierarchy diagram given in the tutorial lead me to believe that all dependencies would be built and installed with just `go install`. When going through the example I was wondering why the library `stringutil.a` file wasn't being produced when I ran `go install`  from the hello world executable folder, since it imports `stringutil`. 

File `$GOPATH/src/github.com/user/hello/hello.go`:

```
package main

import "github.com/user/stringutil"

func main() {
	// use stringutil
}
```

Shell

```
$ go install github.com/user/hello
# According to docs, should produce $GOPATH/pkg/ARCH/github.com/user/stringutil.a
```

**Comment by bradfitz** [comment] 2018-03-05 17:59
@kapcove, you deleted the issue template, so I don't know which version of Go you're using.

Are you talking about Go 1.10 or Go 1.9?

**Comment by kapcove** [comment] 2018-03-06 04:13
Sorry about that, I'm using Go 1.10 windows/amd64.

**Comment by dmitris** [comment] 2018-03-07 10:35
we need to reflect go1.10 change in the tutorial - https://golang.org/doc/go1.10#build:
>The go install command now installs only the packages and commands listed directly on the command line. For example, go install cmd/gofmt installs the gofmt program but not any of the packages on which it depends. The new build cache makes future commands still run as quickly as if the dependencies had been installed. To force the installation of dependencies, use the new go install -i flag. Installing dependency packages should not be necessary in general, and the very concept of installed packages may disappear in a future release.

**Comment by agnivade** [comment] 2018-05-07 07:31
This is an exact duplicate of https://github.com/golang/go/issues/24506. Both have accompanying CLs, and both of them need review. I am going to close this one in favor of that because https://golang.org/cl/105655 looks slightly more well-structured.

**Closed by agnivade** 2018-05-07 07:31 UTC
Labels: Documentation, help wanted
