### ISSUE TITLE
build: elf.Open failed: open ./bin/trivial: no such file or directory

### ISSUE THREAD

**Issue by jbuberel** [golang/go#11273] opened 2015-06-18 17:33 UTC
Appears to be triggered when GOROOT and/or GOBIN are set and the user executes ./all.bash in the 1.5 tree.

```bash
Script started on Thu 18 Jun 2015 09:43:12 AM PDT
jbuberel@nosajun:~$ which go
/usr/lib/google-golang/bin//go
jbuberel@nosajun:~$ set | grep GO
GOPATH=/usr/local/google/home/jbuberel/gosrc
GOROOT=/usr/lib/google-golang/
jbuberel@nosajun:~$ go version
go version go1.4.2 linux/amd64
jbuberel@nosajun:~$ rm -rf ~/go14 ~/go15
jbuberel@nosajun:~$ mkdir ~/go14 ~/go15
jbuberel@nosajun:~$ git clone https://go.googlesource.com/go ~/go15/
Cloning into 'go15'...
remote: Sending approximately 67.05 MiB ...
Receiving objects: 100% (216483/216483), 67.05 MiB | 13.99 MiB/s, done.
Resolving deltas: 100% (178256/178256), done.
jbuberel@nosajun:~/go15$ git rev-parse HEAD
01187f756e26c80af83ec13b3ebdfe3bcd2d0a46
jbuberel@nosajun:~/go15$ cd src
jbuberel@nosajun:~/go15/src$ ./all.bash 
##### Building Go bootstrap tool.
cmd/dist
ERROR: Cannot find /usr/local/google/home/jbuberel/go1.4/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
./make.bash: line 121: /usr/local/google/home/jbuberel/go1.4/bin/go: No such file or directory
jbuberel@nosajun:~/go15/src$ export GOROOT_BOOTSTRAP=/usr/lib/google-golang/
jbuberel@nosajun:~/go15/src$ set | grep GO
GOPATH=/usr/local/google/home/jbuberel/gosrc
GOROOT=/usr/lib/google-golang/
GOROOT_BOOTSTRAP=/usr/lib/google-golang/
jbuberel@nosajun:~/go15/src$ export GOBIN=/usr/local/google/home/jbuberel/gosrc/bin
jbuberel@nosajun:~/go15/src$ ./all.bash 
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /usr/lib/google-golang/.
bootstrap/internal/obj
bootstrap/asm/internal/flags
bootstrap/compile/internal/big
bootstrap/internal/gcprog
bootstrap/internal/obj/arm
bootstrap/internal/obj/arm64
bootstrap/internal/obj/ppc64
bootstrap/internal/obj/x86
bootstrap/asm/internal/lex
bootstrap/compile/internal/gc
bootstrap/internal/asm
bootstrap/link/internal/ld
bootstrap/old5a
bootstrap/old9a
bootstrap/asm/internal/arch
bootstrap/old6a
bootstrap/asm/internal/asm
bootstrap/asm
bootstrap/old8a
bootstrap/link/internal/amd64
bootstrap/link/internal/arm
bootstrap/link/internal/arm64
bootstrap/link/internal/ppc64
bootstrap/link/internal/x86
bootstrap/link
bootstrap/compile/internal/amd64
bootstrap/compile/internal/arm
bootstrap/compile/internal/arm64
bootstrap/compile/internal/ppc64
bootstrap/compile/internal/x86
bootstrap/compile

##### Building compilers and go_bootstrap for host, linux/amd64.
runtime
errors
sync/atomic
sync
internal/singleflight
io
unicode
unicode/utf8
unicode/utf16
bytes
math
strings
strconv
bufio
sort
container/heap
encoding/base64
syscall
internal/syscall/windows/registry
time
internal/syscall/windows
os
reflect
fmt
encoding
encoding/binary
encoding/json
flag
path/filepath
path
io/ioutil
log
regexp/syntax
regexp
go/token
go/scanner
go/ast
go/parser
os/exec
os/signal
net/url
text/template/parse
text/template
go/doc
go/build
hash
crypto
crypto/sha1
debug/dwarf
debug/elf
cmd/go

##### Building packages and commands for linux/amd64.
runtime
unicode
sync/atomic
errors
unicode/utf8
math
sort
container/list
container/ring
container/heap
crypto/subtle
encoding
sync
unicode/utf16
image/color
runtime/race
cmd/vet/whitelist
io
syscall
internal/singleflight
image/color/palette
hash
crypto/cipher
bytes
strings
hash/crc32
hash/adler32
bufio
text/tabwriter
crypto/hmac
hash/crc64
hash/fnv
path
html
compress/bzip2
time
internal/syscall/unix
math/rand
math/cmplx
strconv
reflect
regexp/syntax
crypto
crypto/aes
crypto/rc4
os
crypto/sha512
crypto/md5
crypto/sha1
crypto/sha256
encoding/base64
encoding/ascii85
encoding/pem
encoding/base32
net/url
regexp
path/filepath
image
os/signal
io/ioutil
os/exec
image/internal/imageutil
image/draw
image/jpeg
cmd/pprof/internal/svg
encoding/binary
fmt
crypto/des
index/suffixarray
flag
log
cmd/internal/rsc.io/arm/armasm
cmd/internal/rsc.io/x86/x86asm
debug/dwarf
debug/gosym
debug/plan9obj
cmd/internal/obj
archive/tar
compress/flate
compress/lzw
debug/elf
debug/macho
debug/pe
archive/zip
compress/gzip
compress/zlib
math/big
encoding/hex
go/token
cmd/internal/goobj
database/sql/driver
database/sql
encoding/csv
cmd/internal/objfile
encoding/gob
go/scanner
encoding/json
go/ast
encoding/xml
cmd/addr2line
crypto/dsa
crypto/elliptic
encoding/asn1
crypto/rand
crypto/rsa
crypto/ecdsa
crypto/x509/pkix
go/parser
go/printer
mime
mime/quotedprintable
net/http/internal
text/template/parse
go/constant
text/scanner
image/gif
image/png
runtime/pprof
go/types
internal/trace
text/template
cmd/cgo
internal/format
testing
go/format
net/internal/socktest
runtime/debug
internal/testenv
testing/iotest
go/doc
html/template
testing/quick
cmd/internal/obj/arm
cmd/internal/obj/arm64
go/build
cmd/internal/obj/ppc64
cmd/internal/obj/x86
cmd/asm/internal/flags
cmd/asm/internal/lex
cmd/compile/internal/big
cmd/internal/gcprog
go/internal/gccgoimporter
go/internal/gcimporter
cmd/api
cmd/cover
cmd/asm/internal/arch
cmd/compile/internal/gc
go/importer
cmd/dist
cmd/asm/internal/asm
runtime/cgo
cmd/asm
net
os/user
cmd/doc
cmd/fix
cmd/gofmt
cmd/internal/asm
cmd/link/internal/ld
cmd/newlink
cmd/nm
cmd/objdump
cmd/old5a
cmd/old6a
crypto/x509
net/textproto
log/syslog
mime/multipart
crypto/tls
net/mail
cmd/link/internal/amd64
cmd/link/internal/arm
cmd/link/internal/arm64
cmd/link/internal/ppc64
cmd/link/internal/x86
cmd/old8a
cmd/old9a
cmd/pack
cmd/link
net/http
net/smtp
cmd/pprof/internal/profile
cmd/pprof/internal/tempfile
cmd/vet
cmd/yacc
cmd/compile/internal/amd64
cmd/compile/internal/arm
cmd/compile/internal/arm64
expvar
net/http/cgi
net/http/cookiejar
net/http/httptest
net/http/httputil
net/http/pprof
net/http/fcgi
net/rpc
cmd/compile/internal/ppc64
cmd/compile/internal/x86
cmd/go
cmd/pprof/internal/plugin
cmd/pprof/internal/symbolz
cmd/pprof/internal/report
net/rpc/jsonrpc
cmd/pprof/internal/fetch
cmd/pprof/internal/symbolizer
cmd/trace
cmd/compile
cmd/pprof/internal/commands
cmd/pprof/internal/driver
cmd/pprof


##### Testing packages.
ok  	archive/tar	0.060s
ok  	archive/zip	0.713s
ok  	bufio	0.176s
ok  	bytes	0.175s
ok  	compress/bzip2	0.187s
ok  	compress/flate	0.882s
ok  	compress/gzip	0.095s
ok  	compress/lzw	0.130s
ok  	compress/zlib	1.919s
ok  	container/heap	0.050s
ok  	container/list	0.035s
ok  	container/ring	0.133s
ok  	crypto/aes	0.058s
ok  	crypto/cipher	0.073s
ok  	crypto/des	0.038s
ok  	crypto/dsa	0.079s
ok  	crypto/ecdsa	0.110s
ok  	crypto/elliptic	0.075s
ok  	crypto/hmac	0.040s
ok  	crypto/md5	0.030s
ok  	crypto/rand	0.059s
ok  	crypto/rc4	0.156s
ok  	crypto/rsa	0.164s
ok  	crypto/sha1	0.043s
ok  	crypto/sha256	0.034s
ok  	crypto/sha512	0.029s
ok  	crypto/subtle	0.043s
ok  	crypto/tls	1.546s
ok  	crypto/x509	2.419s
ok  	database/sql	0.172s
ok  	database/sql/driver	0.061s
ok  	debug/dwarf	0.129s
ok  	debug/elf	0.055s
ok  	debug/gosym	1.783s
ok  	debug/macho	0.048s
ok  	debug/pe	0.086s
ok  	debug/plan9obj	0.064s
ok  	encoding/ascii85	0.086s
ok  	encoding/asn1	0.029s
ok  	encoding/base32	0.058s
ok  	encoding/base64	0.063s
ok  	encoding/binary	0.030s
ok  	encoding/csv	0.064s
ok  	encoding/gob	0.128s
ok  	encoding/hex	0.076s
ok  	encoding/json	0.324s
ok  	encoding/pem	0.159s
ok  	encoding/xml	0.063s
ok  	errors	0.039s
ok  	expvar	0.079s
ok  	flag	0.092s
ok  	fmt	0.315s
ok  	go/ast	0.044s
ok  	go/build	0.259s
ok  	go/constant	0.057s
ok  	go/doc	0.102s
ok  	go/format	0.045s
ok  	go/internal/gccgoimporter	0.059s
ok  	go/internal/gcimporter	0.053s
ok  	go/parser	0.073s
ok  	go/printer	0.598s
ok  	go/scanner	0.039s
ok  	go/token	0.077s
ok  	go/types	2.621s
ok  	hash/adler32	0.063s
ok  	hash/crc32	0.045s
ok  	hash/crc64	0.045s
ok  	hash/fnv	0.075s
ok  	html	0.076s
ok  	html/template	0.098s
ok  	image	0.276s
ok  	image/color	0.315s
ok  	image/draw	0.208s
ok  	image/gif	0.218s
ok  	image/jpeg	0.331s
ok  	image/png	0.091s
ok  	index/suffixarray	0.074s
ok  	internal/singleflight	0.162s
ok  	io	0.117s
ok  	io/ioutil	0.045s
ok  	log	0.081s
ok  	log/syslog	2.096s
ok  	math	0.070s
ok  	math/big	1.093s
ok  	math/cmplx	0.078s
ok  	math/rand	0.326s
ok  	mime	0.066s
ok  	mime/multipart	0.176s
ok  	mime/quotedprintable	0.410s
ok  	net	2.340s
ok  	net/http	4.846s
ok  	net/http/cgi	1.136s
ok  	net/http/cookiejar	0.102s
ok  	net/http/fcgi	0.096s
ok  	net/http/httptest	0.046s
ok  	net/http/httputil	0.072s
ok  	net/http/internal	0.054s
ok  	net/internal/socktest	0.060s
ok  	net/mail	0.074s
ok  	net/rpc	0.139s
ok  	net/rpc/jsonrpc	0.081s
ok  	net/smtp	0.096s
ok  	net/textproto	0.092s
ok  	net/url	0.048s
ok  	os	0.293s
ok  	os/exec	0.460s
ok  	os/signal	3.536s
ok  	os/user	0.047s
ok  	path	0.034s
ok  	path/filepath	0.058s
ok  	reflect	0.192s
ok  	regexp	0.421s
ok  	regexp/syntax	0.663s
ok  	runtime	32.620s
ok  	runtime/debug	0.152s
ok  	runtime/pprof	9.162s
ok  	sort	0.142s
ok  	strconv	0.392s
ok  	strings	0.201s
ok  	sync	0.198s
ok  	sync/atomic	1.049s
ok  	syscall	0.220s
ok  	testing	1.658s
ok  	testing/quick	0.096s
ok  	text/scanner	0.043s
ok  	text/tabwriter	0.087s
ok  	text/template	0.158s
ok  	text/template/parse	0.089s
ok  	time	2.860s
ok  	unicode	0.059s
ok  	unicode/utf16	0.050s
ok  	unicode/utf8	0.052s
ok  	cmd/addr2line	1.715s
ok  	cmd/api	0.058s
ok  	cmd/asm/internal/asm	0.047s
ok  	cmd/asm/internal/lex	0.046s
ok  	cmd/compile/internal/big	2.995s
ok  	cmd/cover	3.731s
ok  	cmd/fix	0.123s
ok  	cmd/go	39.321s
ok  	cmd/gofmt	0.105s
ok  	cmd/internal/goobj	0.021s
ok  	cmd/internal/obj	0.081s
ok  	cmd/internal/obj/x86	0.093s
ok  	cmd/internal/rsc.io/arm/armasm	0.049s
ok  	cmd/internal/rsc.io/x86/x86asm	0.406s
ok  	cmd/newlink	0.089s
ok  	cmd/nm	2.430s
ok  	cmd/objdump	5.372s
ok  	cmd/pack	4.257s
ok  	cmd/pprof/internal/profile	0.062s
ok  	cmd/vet	6.035s

##### GOMAXPROCS=2 runtime -cpu=1,2,4
ok  	runtime	61.466s

##### sync -cpu=10
ok  	sync	0.124s

##### ../misc/cgo/stdio

##### ../misc/cgo/life

##### ../misc/cgo/test
scatter = 0x406380
hello from C
sqrt is: 0
PASS
ok  	_/usr/local/google/home/jbuberel/go15/misc/cgo/test	1.611s
scatter = 0x583dc0
hello from C
sqrt is: 0
PASS
ok  	_/usr/local/google/home/jbuberel/go15/misc/cgo/test	1.625s
scatter = 0x406380
hello from C
sqrt is: 0
PASS
ok  	_/usr/local/google/home/jbuberel/go15/misc/cgo/test	1.628s
PASS
ok  	_/usr/local/google/home/jbuberel/go15/misc/cgo/testtls	0.017s
PASS
ok  	_/usr/local/google/home/jbuberel/go15/misc/cgo/testtls	0.021s
PASS
ok  	_/usr/local/google/home/jbuberel/go15/misc/cgo/testtls	0.021s
PASS
ok  	_/usr/local/google/home/jbuberel/go15/misc/cgo/nocgo	0.017s
PASS
ok  	_/usr/local/google/home/jbuberel/go15/misc/cgo/nocgo	0.016s
PASS
ok  	_/usr/local/google/home/jbuberel/go15/misc/cgo/nocgo	0.018s
scatter = 0x7f8faa855290
hello from C
sqrt is: 0
PASS
ok  	_/usr/local/google/home/jbuberel/go15/misc/cgo/test	1.664s
PASS
ok  	_/usr/local/google/home/jbuberel/go15/misc/cgo/testtls	0.032s
PASS
ok  	_/usr/local/google/home/jbuberel/go15/misc/cgo/nocgo	0.020s

##### Testing race detector
ok  	runtime/race	2.599s
ok  	flag	1.032s
ok  	os/exec	17.858s
ok  	flag	1.038s
ok  	os/exec	17.922s

##### ../misc/cgo/testgodefs

##### ../misc/cgo/testso

##### ../misc/cgo/testsovar

##### ../misc/cgo/testcarchive
PASS
PASS
PASS

##### ../misc/cgo/testcshared
ok

##### ../misc/cgo/testshared
2015/06/18 10:08:42 elf.Open failed: open ./bin/trivial: no such file or directory
exit status 1
FAIL	_/usr/local/google/home/jbuberel/go15/misc/cgo/testshared	5.228s
2015/06/18 10:08:42 Failed: exit status 1
jbuberel@nosajun:~/go15/src$ exit
exit

Script done on Thu 18 Jun 2015 10:13:43 AM PDT

```

**Comment by mwhudson** [comment] 2015-06-18 21:34
Sounds plausible, and my fault.

**Comment by mwhudson** [comment] 2015-06-18 21:48
I can't reproduce the effect of GOROOT (and anyway, don't set GOROOT?).  The test will fail if ../bin/go is not on $PATH, but I don't think it's the only test with that property.  I can add a change to clear GOBIN easily enough.

**Comment by zcalusic** [comment] 2015-06-25 10:04
Have the same issue here ($GOBIN set, testshared fails).

Fixed with oneliner: https://gist.github.com/zcalusic/69008c7b944e3ebcb666

```Diff
diff --git a/misc/cgo/testshared/shared_test.go b/misc/cgo/testshared/shared_test.go
index c36abc3..dd76ffa 100644
--- a/misc/cgo/testshared/shared_test.go
+++ b/misc/cgo/testshared/shared_test.go
@@ -44,6 +44,7 @@ func run(t *testing.T, msg string, args ...string) {
 // goCmd invokes the go tool with the installsuffix set up by TestMain. It calls
 // t.Errorf if the command fails.
 func goCmd(t *testing.T, args ...string) {
+	os.Unsetenv("GOBIN")
 	newargs := []string{args[0], "-installsuffix=" + suffix}
 	if testing.Verbose() {
 		newargs = append(newargs, "-v")
```

**Comment by ianlancetaylor** [comment] 2015-07-12 17:20
I don't think it's worth worrying about a bad setting of GOROOT during a test.

Setting GOBIN, on the other hand, is entirely reasonable, and the test shouldn't fail because GOBIN is set.  I sent CL 12073 for that.

**Closed** 2015-07-12 18:07 UTC

**Comment by jbuberel** [comment] 2015-07-12 19:14
Just verified that running `all.bash` with `GOBIN` set no longer causes the error - thanks for fixing!

**Comment by mwhudson** [comment] 2015-07-12 21:59
Thanks Ian for fixing that, and sorry I never got around to it
