### ISSUE TITLE
Go Parser cannot parse "--" consecutive subtract tokens

### ISSUE THREAD

**Issue by martinomburajr** [golang/go#35069] opened 2019-10-22 05:12 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.13

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH - amd64
GOOS - linux
</pre></details>

### What did you do?
I am trying to use the `parser` package to parse a mathematical string such as this one 
`-3--2`. The parser fails in being able to parse the string and throws the following error `expected 'EOF', found '--'`

Link to [Playground](https://play.golang.org/p/xKbQTpZXqsH)

### What did you expect to see?
Some `go/ast` expression:
```
(Pseudo representation)
ast.BinaryExpr{ X: UnaryExpr{Op: SUB, X:BasicLit{Value: "3"}, Op: SUB, Y: UnaryExpr{Op: SUB, X:BasicLit{Value: "2"}
```

### What did you see instead?
`expected 'EOF', found '--'`

**Comment by ALTree** [comment] 2019-10-22 06:49
This is working as expected. From the spec,[ Lexical Elements](https://golang.org/ref/spec#Lexical_elements) section:

> While breaking the input into tokens, the next token is the longest sequence of characters that form a valid token. 

This means that `--` is parsed as a single token. Fortunately:

> White space [...] is ignored except as it separates tokens that would otherwise combine into a single token. 

So you can use `- -` (with whitespace between the two `-`) to write a subtraction involving an unary minus.

Closing here, since this is not a bug.

**Closed by ALTree** 2019-10-22 06:49 UTC
