### ISSUE TITLE
cmd/compile: failure to reject unused dot import

### ISSUE THREAD

**Issue by mdempsky** [golang/go#22072] opened 2017-09-27 23:17 UTC
cmd/compile accepts this package, but it should be rejected with an error that import "bytes" is unused:

    package p

    import . "bytes"

    var _ = struct{ Buffer int }{Buffer: 0}

**Comment by odeke-em** [comment] 2017-09-28 05:14
@mdempsky am sure you already know but the same applies when we import pretty much any package and have the same symbol matched and used in a struct e.g
```go
import . "bytes"
import . "strconv"
import . "net/http"

var _ = struct {
        Server   int
        Reader   int
        NumError string
}{Reader: 0, NumError: "a", Server: 0}
```

**Comment by mdempsky** [comment] 2017-09-28 05:52
@odeke-em Yep. The problem is that when we're noding the `Buffer: 0` composite literal element, we don't have enough information to know whether it's a struct literal (which means `Buffer` is just a raw symbol) or an array/slice/map literal (where `Buffer` can be a named object, like a const or variable). Currently, we parse it as a named object, and then later take just the name if we realize it's a struct literal.

The problem with this approach is when we access the named object that's been dot imported, we eagerly mark the import as used, even if it turns out later we didn't need the object.

**Comment by odeke-em** [comment] 2017-12-23 11:28
@mdempsky aha, turns out that @griesemer had already reported this bug back in September 2013 with https://github.com/golang/go/issues/6428. How should we handle the dups?

**Comment by griesemer** [comment] 2017-12-24 00:10
Duplicate of #6428.

**Closed by griesemer** 2017-12-24 00:10 UTC
