### ISSUE TITLE
x/pkgsite: Confusing search results

### ISSUE THREAD

**Issue by ardan-bkennedy** [golang/go#41294] opened 2020-09-09 14:19 UTC
I ran the following search on `go.dev` and got the following results.

<img width="986" alt="Screen Shot 2020-09-09 at 10 14 17 AM" src="https://user-images.githubusercontent.com/2280005/92610029-3f9c4700-f285-11ea-9cc0-18cc614c686b.png">

If I add a `\` at the end of the package I am searching, I get the results I need.

<img width="1144" alt="Screen Shot 2020-09-09 at 10 15 09 AM" src="https://user-images.githubusercontent.com/2280005/92610200-6e1a2200-f285-11ea-8dd9-66a05ac9376e.png">

The problem was I was looking for this package

https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/net/http

But when I look at this

https://pkg.go.dev/go.opentelemetry.io/contrib

I don't see any of those subdirectories.

**Comment by jamalc** [comment] 2020-09-09 15:48
The reason go.opentelemetry.io/contrib/instrumentation/net/http is not listed there is because it is a nested module. We plan to address nested modules in the upcoming round of design changes.

Duplicate of golang/go#38596

**Closed by jamalc** 2020-09-09 15:48 UTC
Labels: pkgsite
