### ISSUE TITLE
JSON custom encoderFunc for certain types

### ISSUE THREAD

**Issue by PumpkinSeed** [golang/go#48627] opened 2021-09-25 19:28 UTC
### Feature request

The JSON marshalling of compact types like structs can be unique in some cases, which means we need to have unique encoder implementations. It would be nice to make the encoding/json/encode.go's `newTypeEncoder` function customisable. I mean this function accepts type information and based on that it will return an `encoderFunc`. Somehow if we are able to add custom implementations for different kinds that would make the json encoder more flexible. 

High-level example of my thoughts:

```
// ------------ json package

const (
  StructKind = "struct"
)

type customEncoder interface {
  encode(e *encodeState, v reflect.Value, opts encOpts)
}

func SetEncoder(kind string, impl customEncoder) {
  // TODO
}

// ------------ client impl

json.SetEncoder(json.StructKind, CustomStruct{})

type CustomStruct struct{}

func (CustomStruct) encode(e *encodeState, v reflect.Value, opts encOpts) {
  // TODO
}

```

**Comment by dsnet** [comment] 2021-09-25 20:35
This sounds like a duplicate of #5901?

**Comment by seankhliao** [comment] 2021-09-25 21:16
Duplicate of #5901

**Closed by seankhliao** 2021-09-25 21:16 UTC
