### ISSUE TITLE
x/build/devapp: https://dev.golang.org/reviews page was unavailable on Aug 13, 2021 due to unexpected Gerrit behavior

### ISSUE THREAD

**Issue by rhysh** [golang/go#47695] opened 2021-08-13 20:37 UTC
### What version of Go are you using (`go version`)?

N/A

### Does this issue reproduce with the latest release?

This is a problem with a live website.

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

I opened https://dev.golang.org/ in my browser and clicked the "Open reviews" link.

### What did you expect to see?

A list of Gerrit links

### What did you see instead?

https://dev.golang.org/reviews in Chrome shows an error page referencing "ERR_HTTP2_PROTOCOL_ERROR". Curl also reports a problem:

```
$ curl https://dev.golang.org/reviews
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

**Comment by rhysh** [comment] 2021-08-13 20:54
With HTTP/1.1, it's an empty response (no headers). Maybe a panic before the first write to the body (or WriteHeader). Not specific to http/2.

```
$ curl --http1.1 https://dev.golang.org/reviews
curl: (52) Empty reply from server
```

**Comment by dmitshur** [comment] 2021-08-13 22:17
Thanks for reporting.

I'm not able to reproduce the issue right now (which is 1-2 hours after the report). What about you @rhysh, does it still reproduce for you?

I do see in logs there have been panics. There was an issue with Gerrit (go-review.googlesource.com) that coincides with the time of this report, and it looks like it uncovered some possible panics in `golang.org/x/build/maintner`.

**Comment by rhysh** [comment] 2021-08-13 22:26
Yes, the page loads for me now too. Thanks for investigating!

**Comment by dmitshur** [comment] 2022-01-06 17:29
I've looked into the panic in `golang.org/x/build/maintner`, and it seems the panic cannot happen under normal situations, only if Gerrit is misbehaving somehow. Since it only happened that one time so far, I can't tell if it was a one-off problem that was resolved, or something we need to update the code to anticipate happening again.

I filed #50474 for tracking the problem in `maintner`, and will close this issue since it's resolved.

**Closed by dmitshur** 2022-01-06 17:29 UTC
Labels: Builders, NeedsInvestigation
