### ISSUE TITLE
math: rand: not random. #21771

### ISSUE THREAD

**Issue by jeffkayser2** [golang/go#21774] opened 2017-09-05 20:11 UTC
Please see issue 21771.

If the developers of the original code (Alan A. A. Donovan & Brian W. Kernighan) can forget to call Seed before calling Rand, what is the likelihood that lesser developers will make the same mistake?

**Comment by davecheney** [comment] 2017-09-05 20:48
Duplicate of #21771.

**Closed by davecheney** 2017-09-05 20:48 UTC
