### ISSUE TITLE
website: tip.golang.org godoc browsing is broken

### ISSUE THREAD

**Issue by josharian** [golang/go#19401] opened 2017-03-05 00:57 UTC
https://golang.org/pkg/runtime/ shows docs for package runtime.

https://tip.golang.org/pkg/runtime/ shows an error.

cc @broady (is that right?)

**Comment by shurcooL** [comment] 2017-03-05 04:08
I believe this is because of https://groups.google.com/d/msg/golang-codereviews/tju2mJPjAwI/N8RKEFRvAQAJ. Note that https://tip.golang.org/pkg/ also displays an error.

I've sent [CL 37768](https://golang.org/cl/37768) that fixes the issue, and its commit message contains a detailed explanation of the cause.

**Comment by shurcooL** [comment] 2017-03-05 21:40
https://tip.golang.org/pkg/runtime/ works ok now, this issue can be closed.

**Comment by bradfitz** [comment] 2017-03-05 21:46
@shurcooL, I gave you [github edit access](https://golang.org/wiki/GithubAccess). Feel free to close it yourself. :)

**Comment by shurcooL** [comment] 2017-03-05 22:30
Thanks Brad!

Closing because this issue is resolved.

**Closed by shurcooL** 2017-03-05 22:30 UTC
