### ISSUE TITLE
go mod download can't find module tag v0.0.1

### ISSUE THREAD

**Issue by dwschulze** [golang/go#41484] opened 2020-09-18 19:24 UTC
$ go version
 go1.15.1 linux/amd64

I have a module in github.

I added this to my ~/.gitconfig: `[url "ssh://git@github.com/"]	insteadOf = https://github.com/`

When I try to use the module from my `main` `go mod download` cannot find v0.0.1 of the module even though the tag v0.0.1 exists in github:

```
$ go run main.go
go: github.com/dwschulze/go-module-test-dateutilmod@v0.0.1/go.mod: verifying module: github.com/dwschulze/go-module-test-dateutilmod@v0.0.1/go.mod: reading https://sum.golang.org/lookup/github.com/dwschulze/go-module-test-dateutilmod@v0.0.1: 410 Gone
        server response: not found: github.com/dwschulze/go-module-test-dateutilmod@v0.0.1: invalid version: unknown revision v0.0.1

```

```
$ go mod download  github.com/dwschulze/go-module-test-dateutilmod@v0.0.1
github.com/dwschulze/go-module-test-dateutilmod@v0.0.1/go.mod: verifying module: github.com/dwschulze/go-module-test-dateutilmod@v0.0.1/go.mod: reading https://sum.golang.org/lookup/github.com/dwschulze/go-module-test-dateutilmod@v0.0.1: 410 Gone
	server response: not found: github.com/dwschulze/go-module-test-dateutilmod@v0.0.1: invalid version: unknown revision v0.0.1
```

The tag v0.0.1 exists:

```
$ git clone git@github.com:dwschulze/go-module-test-dateutilmod.git
Cloning into 'go-module-test-dateutilmod'...
...
$ cd go-module-test-dateutilmod/
$ git tag
v0.0.1
```

**Comment by bcmills** [comment] 2020-09-18 19:28
See [`go help module-private`](https://tip.golang.org/cmd/go/#hdr-Module_configuration_for_non_public_modules) or https://golang.org/ref/mod#private-module-proxy-direct.

**Comment by bcmills** [comment] 2020-09-18 19:28
That said, we should give a better error message for this.

**Comment by bcmills** [comment] 2020-09-18 19:28
Duplicate of #25982

**Closed by bcmills** 2020-09-18 19:28 UTC
Labels: WaitingForInfo, modules

**Comment by dwschulze** [comment] 2020-09-19 00:15
I was able to get this to work with `export GOPRIVATE=githib.com`.  So I thought I understood what the problem was and what the solution was.  But then if I delete GOPATH/pkg and do `unset GOPRIVATE` I found that it still works.  It downloads the module into GOPATH/pkg.

But it shouldn't work with GOPRIVATE unset.  What is going on that it works?  Is there a hidden cache somewhere?

**Comment by dwschulze** [comment] 2020-09-19 00:20
I do not believe that this is a duplicate of [#25982](https://github.com/golang/go/issues/25982).  That is an earlier version of go and the issue seems to be credentials for vcs repos, not what `go mod download` does.
