### ISSUE TITLE
cmd/compile: escape analysis does not analyze closure calls

### ISSUE THREAD

**Issue by randall77** [golang/go#7714] opened 2014-04-04 23:56 UTC
<pre>func set(p *int, x int) {
    *p = x
}
func main() {
    var y int
    set(&amp;y, 42)
}

escape analysis works, y is allocated on the stack.

func main() {
    var y int
    func(p *int, x int) {
        *p = x
    }(&amp;y, 42)
}

escape analysis gives up, y is allocated on the heap.  There's no difference between the
two codes except that the set function is declared separately in the first case and
anonymously in the second.</pre>

**Comment by dvyukov** [comment] 2015-02-11 17:33
Similar case from #8615 

    x := 0
    defer func(p *int) {
        *p = 1
    }(&x)

**Comment by pmalek** [comment] 2017-09-03 12:09
What is the current status of this?

Go 1.9 still moves `x` to heap in this snippet:

```
package main

func main() {
	x := 0
	func(p *int) {
		*p = 1
	}(&x)
}
```
build output:
```
go build -gcflags=-m main.go
# command-line-arguments
./main.go:5:2: can inline main.func1
./main.go:7:4: &x escapes to heap
./main.go:4:7: moved to heap: x
./main.go:5:2: main func literal does not escape
./main.go:5:10: main.func1 p does not escape
```

**Comment by randall77** [comment] 2017-09-03 14:41
This has not been fixed. And as far as I know, no one is working on it.
We don't have enough people to get to every optimization idea, unfortunately.

**Comment by openex27** [comment] 2018-04-13 07:04
Dose the current Go1.10 version fix this?

code:

```
package main

func main() {
    var y int
    func(p *int) {
        *p = 1
    }(&y)
}
```

go build -gcflags=-m x.go output:


>  ./x.go:5:5: can inline main.func1
./x.go:7:6: inlining call to main.func1
**./x.go:7:7: main &y does not escape**

**Comment by ianlancetaylor** [comment] 2019-03-29 17:37
I think this is still an issue.  In the simple example it doesn't happen because the call is inlined, but you can see it if you "go build" with `-gcflags=-l` to disable inlining.

**Comment by mdempsky** [comment] 2019-04-16 20:38
These are fixed with -newescape=true, and confirmed with [updated regress tests](https://github.com/golang/go/commit/a9831633be548c039ada30a2fb9d7290c35ac0c0#diff-25d0cb77c73c4bc9d1ebf0c900bd6044).

**Closed by mdempsky** 2019-04-16 20:38 UTC
Labels: NeedsInvestigation, Performance
