### ISSUE TITLE
no required module provides package github.com/rlmcpherson/s3gof3r/gof3r: working directory is not part of a module

### ISSUE THREAD

**Issue by amitoptigo** [golang/go#44362] opened 2021-02-18 05:36 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version : 1.16

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?
x86
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Execute the below command  which was working fine with 1.15.8 but unsuccessful with 1.16.

go get -d github.com/rlmcpherson/s3gof3r/gof3r && CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -v -o /tmp/gof3r github.com/rlmcpherson/s3gof3r/gof3r

After reverting back to 1.15.8 the build was successful.

**Comment by seankhliao** [comment] 2021-02-18 07:36
module mode is now on by default https://golang.org/doc/go1.16#go-command

closing as working as intended

**Closed by seankhliao** 2021-02-18 07:36 UTC

**Comment by rbucker** [comment] 2021-02-25 21:44
not certain but this might be considered a breaking change... unless you document the workaround?
