### ISSUE TITLE
x/tools/gopls: invalidate file "unloadability" when name/imports change

### ISSUE THREAD

**Issue by mjyeaney** [golang/go#40312] opened 2020-07-15 01:30 UTC
See previous report in golang/vscode-go#325 ; Issue is no better on Windows / WSL (see screenshot below). Switching to OSX to continue dev work (rest of team has no issues). Note that memory will NOT climb above this, and at this point autocomplete is non-functioning and will spin CPU with a VS Code message of `Loading...`

![image](https://user-images.githubusercontent.com/1410150/87492675-18285580-c619-11ea-9ee0-1693affcddf2.png)

**Comment by mjyeaney** [comment] 2020-07-22 13:17
Team - any updates here?

**Comment by stamblerre** [comment] 2020-07-22 17:04
Sorry for the delay. I think the issue is likely that some of your files aren't getting correctly mapped to their packages:

```
[Info  - 6:37:42 PM] 2020/07/15 18:37:42 go/packages.Load
	snapshot=0
	directory=/mnt/c/Projects/IL6-Core/test
	query=[./... builtin]
	packages=4

[Info  - 6:37:45 PM] 2020/07/15 18:37:45 go/packages.Load
	snapshot=1
	directory=/mnt/c/Projects/IL6-Core/test
	query=[file=/mnt/c/Projects/IL6-Core/test/terraform/04_vms_mgmt_vm_test.go]
	packages=1

[Info  - 6:37:45 PM] 2020/07/15 18:37:45 go/packages.Load
	snapshot=1
	package_path="command-line-arguments"
	files=[/mnt/c/Projects/IL6-Core/test/terraform/04_vms_mgmt_vm_test.go]

[Info  - 6:37:47 PM] 2020/07/15 18:37:47 go/packages.Load
	snapshot=1
	directory=/mnt/c/Projects/IL6-Core/test
	query=[file=/mnt/c/Projects/IL6-Core/test/terraform/04_vms_mgmt_vm_test.go]
	packages=1

[Info  - 6:37:47 PM] 2020/07/15 18:37:47 go/packages.Load
	snapshot=1
	package_path="command-line-arguments"
	files=[/mnt/c/Projects/IL6-Core/test/terraform/04_vms_mgmt_vm_test.go]
```

I wonder why `/mnt/c/Projects/IL6-Core/test/terraform/04_vms_mgmt_vm_test.go` keeps getting re-loaded. Does it have any build tags? What is the output of `go list -e -json -compiled -test ./...` in the `/mnt/c/Projects/IL6-Core/test/` directory?

**Comment by mjyeaney** [comment] 2020-07-22 18:40
Good catch - yes, all the `*_test.go` files have build tags in them, and when they are removed things start behaving very differently.  For example, linter feedback now begins to display (didn't before), and tasks that normally hang language feedback now work instantly (e.g, renaming a struct name used to "kill" all autosuggest feedback and fill the output with errors like shown above).

The build tags are all of the following format: `// +build 03` (for example...the number is an identifier for the portion of the test pipeline so they can be run independently)

**Comment by stamblerre** [comment] 2020-07-22 20:23
`gopls` currently doesn't support build tags well, so if you're working in a file with build tags, you will need to add additional configuration to get the features to work (https://github.com/golang/go/issues/29202 has more details).

There does seem to be an additional issue here, which is that build tagged files usually get marked as "unloadable" when we cannot find their package, but if you are editing a build tagged file, we will probably keep trying to load it. We should make sure that `gopls` gives up after some number of tries or think of some other workaround.

**Comment by igordcard** [comment] 2020-07-26 17:15
I'm also getting "DocumentSymbols failed: getting file for DocumentSymbols: no ParseGoHandle for" which is preventing all symbols from being loaded from a go file (over SSH remote). This seems to happen on and off as I open go files and can happen to any of them. If symbols don't load for a particular file, they may load later after I open and close a bunch of other files. The best seems to be restart vscode or gopls and then trying to open the file that I want. Also, 1st file opened in vscode seems to always load the symbols just fine, but 2nd file opened always fails (doesn't matter which actual files).

**Comment by stamblerre** [comment] 2020-07-26 17:20
@igordcard: Please take a look at the `gopls` [troubleshooting guide](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#troubleshooting) and open a new issue.

**Comment by stamblerre** [comment] 2020-09-09 03:19
I believe that https://github.com/golang/go/issues/31668 would likely be a good way of guiding the user to solve the problem.
One idea for resolving the CPU usage issue would be to treat "unloadable" as a piece of package metadata. This way, `gopls` wouldn't try to reload it until the metadata was invalidated (package name or imports changed).

**Closed** 2021-06-16 01:55 UTC
Labels: Tools, gopls
