### ISSUE TITLE
viewing differences in vscode git diff reports "undeclared name" errors for the temp files

### ISSUE THREAD

**Issue by dskdas** [golang/go#37082] opened 2020-02-06 12:10 UTC
### What version of Go are you using (`go version`)?

go version go1.13.5 darwin/amd64

golang.org/x/tools/gopls v0.3.1
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=

### Does this issue reproduce with the latest release?

not tried yet

### What operating system and processor architecture are you using (`go env`)?

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/[--]/Library/Caches/go-build"
GOENV="/[--]/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/[--]/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/[--]/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/54/7pghg1bj18q8kzj3xnvb6d480000gn/T/go-build571485278=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

upgrade gopls to latest version
golang.org/x/tools/gopls v0.3.1
    golang.org/x/tools/gopls@v0.3.1 h1:yNTWrf4gc4Or0UecjOas5pzOa3BL0WDDyKDV4Wz5VaM=

open a go project in vscode (with go modules)

make some changes to a file

build and test (no errors)

go to git tab and click on a file to see the diff

### What did you expect to see?

just the diff of the file being changed. did not expect to see any errors in the problems window

### What did you see instead?

was able to see the diff ok.

but noticed that "undeclared name" errors are reported in the PROBLEMS window for a file with name [file-being-diffed].go?path%3d***

the errors do not go away even if i close the diff tab for the file. had to restart vscode

**Comment by heschik** [comment] 2020-02-06 19:54
Duplicate of #33699. Sorry for the trouble.

**Closed by heschik** 2020-02-06 19:54 UTC
