### ISSUE TITLE
Proposal: Add a Go() function to sync.WaitGroup

### ISSUE THREAD

**Issue by pkern** [golang/go#23538] opened 2018-01-24 17:34 UTC
`sync.WaitGroup` offers a flexible way to wait for an arbitrary number of tasks submitted. In `golang.org/x/sync/errgroup` we see a neat method called `Go(func() error)` that spawns a goroutine and makes sure that the internal counters are adjusted appropriately. Would this be a useful addition to `sync.WaitGroup` as well? Essentially it'd be used like this:

```go
var wg sync.WaitGroup
wg.Go(func() { ... })
wg.Wait()
```

Internally the implementation would be very simple:

```go
// Go calls the given function in a goroutine and adds it to the WaitGroup.
func (wg *WaitGroup) Go(f func()) {
	wg.Add(1)
	go func() {
		defer wg.Done()
		f()
	}()
}
```

A fair argument against this would be "just use errgroup", which feels incredibly useful whenever you fan out to multiple goroutines and wait for their result, especially as it deals with cancellation properly. Is there maybe a possibility to put that library into core Go instead?

This was mostly spawned by a code review where a reviewer take issue with the use of an errgroup with no error involved, as all errors were supposed to be ignored, and hence suggesting the use of `sync.WaitGroup` instead.

**Comment by dsnet** [comment] 2018-01-24 17:50
Closing as duplicate of #18022, which proposed the same thing.

**Closed by dsnet** 2018-01-24 17:50 UTC
Labels: Proposal
