### ISSUE TITLE
Deadlock error in documentation example code

### ISSUE THREAD

**Issue by Xianic** [golang/go#41609] opened 2020-09-24 14:43 UTC
### What version of Go are you using (`go version`)?

<pre>
1.14.8
</pre>
(stated on about page of https://play.golang.org )
### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

Whatever the [go playground](https://play.golang.org/) uses. I haven't found a way to exec the go binary to find out, I expect this is intentional.

### What did you do?

Find the documentation for [os/exec.Cmd.StdoutPipe()](https://pkg.go.dev/os/exec#example-Cmd.StdoutPipe) and run the [example code](https://play.golang.org/p/ek7-_Xa_bN3).

### What did you expect to see?

<pre>
Bob is 32 years old
</pre>

### What did you see instead?

<pre>
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f3fdaba8ee8, 0x72, 0x53a0c0)
	/usr/local/go-faketime/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc000084198, 0x72, 0xc00009c001, 0x200, 0x200)
	/usr/local/go-faketime/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go-faketime/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000084180, 0xc00009c000, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go-faketime/src/internal/poll/fd_unix.go:159 +0x1b1
os.(*File).read(...)
	/usr/local/go-faketime/src/os/file_posix.go:31
os.(*File).Read(0xc000082018, 0xc00009c000, 0x200, 0x200, 0xc000066e60, 0x40ce10, 0xc000092160)
	/usr/local/go-faketime/src/os/file.go:116 +0x71
encoding/json.(*Decoder).refill(0xc000092160, 0xc000092160, 0x7f3fdaba04d0)
	/usr/local/go-faketime/src/encoding/json/stream.go:165 +0xeb
encoding/json.(*Decoder).readValue(0xc000092160, 0x0, 0x0, 0x50a2c0)
	/usr/local/go-faketime/src/encoding/json/stream.go:140 +0x1ff
encoding/json.(*Decoder).Decode(0xc000092160, 0x4efae0, 0xc0000980c0, 0x539f60, 0xc000082018)
	/usr/local/go-faketime/src/encoding/json/stream.go:63 +0x79
main.main()
	/tmp/sandbox568913125/prog.go:23 +0x237
</pre>

**Comment by seankhliao** [comment] 2020-09-24 15:22
This is a restriction of the playground running in a sandboxed environment

**Comment by prattmic** [comment] 2020-09-24 15:23
Duplicate of #41202

**Closed by prattmic** 2020-09-24 15:23 UTC
Labels: Documentation
