### ISSUE TITLE
affected/package: http.Client,tls.Config. InsecureSkipVerify: true not work with go1.18

### ISSUE THREAD

**Issue by hongnod** [golang/go#51702] opened 2022-03-16 07:48 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.18 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOHOSTARCH=amd64
set GOHOSTOS=windows</pre></details>

### What did you do?

	client := &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: true, // test server certificate is not trusted.
			},
		},
		Jar: NewJar(),
	}

	req, err := http.NewRequest("GET", "url", nil)
	if err != nil {
		log.Fatal(err)
	}
	get_resp, err := client.Do(req)
	if err != nil {
		log.Fatal(err)
	}

### What did you expect to see?

do request successfully.

### What did you see instead?
tls: server selected unsupported protocol version 301
go 1.17.8 without such problem

**Comment by seankhliao** [comment] 2022-03-16 08:24
https://go.dev/doc/go1.18#tls10

closing as working as intended

**Closed by seankhliao** 2022-03-16 08:24 UTC
