### ISSUE TITLE
cmd/compile: inconsistent behaviors in judging whether or not two types are identical

### ISSUE THREAD

**Issue by dotaheor** [golang/go#24721] opened 2018-04-06 10:04 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.10.1 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What did you do?

```
package m3

import "time"

type t = time.Time
type T = time.Time

type A = struct{t}
type B = struct{T}
```

```
import "m3"
import "time"

type t = time.Time
type T = time.Time

type A = struct{t}
type B = struct{T}

func main() {
   var a, b interface{} = m3.A{}, m3.B{}
   var x, y interface{} = A{}, B{}
   println(a == x) // true
   println(b == y) // true
   
   _ = A(m3.A{}) // cannot convert struct { time.Time } literal (type struct { time.Time }) to type struct { time.Time }
   _ = B(m3.B{}) // ok
   
   println(a == b) // true
   println(x == y) // true
   _ = B(A{})       // cannot convert struct { time.Time } literal (type struct { time.Time }) to type struct { time.Time }
   _ = m3.A(m3.B{}) // cannot convert struct { time.Time } literal (type struct { time.Time }) to type struct { time.Time }
}
```

### What did you expect to see?

No errors, [edit: or all `println` calls, except the second, print `false`].

### What did you see instead?

```
./main.go:18:9: cannot convert struct { time.Time } literal (type struct { time.Time }) to type struct { time.Time }
./main.go:23:9: cannot convert struct { time.Time } literal (type struct { time.Time }) to type struct { time.Time }
./main.go:24:12: cannot convert struct { time.Time } literal (type struct { time.Time }) to type struct { time.Time }
```

**Comment by dotaheor** [comment] 2018-04-06 10:08
btw, should `struct{t}` and `struct{T}` be viewed as the same type?

**Comment by dotaheor** [comment] 2018-04-06 11:57
The following program print the same output for the two types:
```
package main

import "fmt"
import "time"
import "reflect"

type t = time.Time
type T = time.Time

type A = struct{t}
type B = struct{T}

func main() {
	t := reflect.TypeOf(A{}) // the Singer type
	fmt.Println(t, "has", t.NumField(), "fields:")
	for i := 0; i < t.NumField(); i++ {
		fmt.Print("   filed#", i, ": ", t.Field(i).Name, "\n")
	}
	
	/*
	struct { time.Time } has 1 fields:
	filed#0: t
	*/
	
	t = reflect.TypeOf(B{}) // the Singer type
	fmt.Println(t, "has", t.NumField(), "fields:")
	for i := 0; i < t.NumField(); i++ {
		fmt.Print("   filed#", i, ": ", t.Field(i).Name, "\n")
	}
	
	/*
	struct { time.Time } has 1 fields:
	filed#0: t
	*/
}
```

I feel the outputs are wrong, at least the outputs should be `filed#0: Time`.

But I change the type `A` and `B` to non-alias types, then the outputs will be different
(I think the outputs are correct):
```
main.A has 1 fields:
   filed#0: t
main.B has 1 fields:
   filed#0: T
```

**Comment by bcmills** [comment] 2018-04-06 21:29
A simpler repro does not require separate packages: https://play.golang.org/p/_ZimDvvVU0u

The compiler is correct to emit an error, because the fields have different names.
The fact that the error does not include the correct field names is a bug.

**Comment by bcmills** [comment] 2018-04-06 21:32
The fix is presumably to use the name of the field in the error message instead of the name of the underlying type.

**Comment by bcmills** [comment] 2018-04-06 23:16
(CC @griesemer, maybe?)

**Comment by dotaheor** [comment] 2018-04-07 04:36
If the error messages are correct, the problem is bigger:
```
package main

import (
	"fmt"
	"time"
)

type t = time.Time
type T = time.Time

type A = struct{ t }
type B = struct{ T }

func main() {
	var a A
	var b B
	fmt.Println(interface{}(b) == interface{}(a))
	//fmt.Println(b == a)
}
```

**Comment by bcmills** [comment] 2018-04-07 06:34
Huh, that's a neat bug you've found!
(https://play.golang.org/p/LSwVZ_aoNmc)

**Comment by jimmyfrasche** [comment] 2018-04-07 17:32
reduced further https://play.golang.org/p/m6Wv1Hk1U8h

**Comment by griesemer** [comment] 2018-04-09 22:35
1) Two struct types with differently named (corresponding) embedded fields are different types, no even if the embedded field types are identical. So the assignments `a = b` are expected to be reported as invalid at compile time.

2) Because of 1), this shouldn't work, but the issue is that (basically) the same printing code that's used in the error message (and which prints both types as `struct{ int }`) is used to identify those types' symbols, so they get confused.

**Comment by dotaheor** [comment] 2019-12-17 19:55
A similar bug of gc?

```
package main

import "reflect"

type P = struct{int}
type Q = struct{int}
type T = struct {
	P
}
type S = struct {
	Q
}

func main() {
	var t T
	var s S
	
	// gc prints both true (wrong), gccgo prints both false (right). 
	println(reflect.TypeOf(s).ConvertibleTo(reflect.TypeOf(t)))
	println(reflect.TypeOf(t).ConvertibleTo(reflect.TypeOf(s)))
}
```

**Comment by bcmills** [comment] 2019-12-17 20:13
@dotaheor heh, that looks a lot like (declined) #20621!

**Comment by dotaheor** [comment] 2019-12-18 03:27
@bcmills they are not totally the same. The unequalness in this issue is because the field names are different.

**Comment by dmitshur** [comment] 2020-02-19 20:19
This issue is currently labeled as early-in-cycle for Go 1.15. That [time is now](https://groups.google.com/d/msg/golang-dev/y0yM_Xi665Q/mk35pLnjCAAJ), so friendly ping. If it no longer needs to be done early in cycle, that label can be removed.

**Comment by dotaheor** [comment] 2020-03-27 16:07
One more difference between gc and gccgo:
```
package main

import "time"

type T = struct {
	time.Time
}

func main() {
	println(T.Add)
}
```

It compiles ok with gc, but not gccgo.

**Comment by dotaheor** [comment] 2020-03-28 02:07
As the lines `fmt.Printf("%T\n", struct {time.Time}.Add)` also fails to compile with gccgo. I created [a new issue](https://github.com/golang/go/issues/38125) for gccgo.

**Comment by dmitshur** [comment] 2020-08-12 17:36
This issue is currently labeled as early-in-cycle for Go 1.16.
That [time is now](https://groups.google.com/d/msg/golang-dev/qtxOW0x4Rrw/0rB32h12BQAJ), so this is a friendly ping so the issue is looked at again.

**Comment by griesemer** [comment] 2020-12-08 04:29
This didn't make it for Go 1.16. Should try to address for Go 1.17, certainly for 1.18. As already [explained](https://github.com/golang/go/issues/24721#issuecomment-379914801) we need to fix the printing of structs, both for error messages (to make clear what's wrong), and for generating type descriptors.

Probably not too hard to do but the respective code is in `fmt.go` which is mess. Getting it right is subtle. Not worth the risk for 1.16. Eventually we will need to get rid of this code.

**Comment by griesemer** [comment] 2020-12-08 04:43
For reference: `go/types` and `types2` report for the last line of https://play.golang.org/p/m6Wv1Hk1U8h:
```
main.go:14:14: invalid operation: cannot compare a == b (mismatched types struct{int} and struct{T /* = int */})
```

**Comment by griesemer** [comment] 2021-04-20 17:28
Again, given other priorities, this didn't make it for 1.17. Pushing to 1.18.

**Comment by cagedmantis** [comment] 2021-08-12 19:30
This issue is currently labeled as early-in-cycle for Go 1.18.
That [time is now](https://groups.google.com/g/golang-dev/c/g2aGRJQIGzw/m/m7hkf2YiAAAJ), so this is a friendly ping so the issue is looked at again.

**Comment by ianlancetaylor** [comment] 2021-11-10 00:20
@griesemer I assume that we should push this to 1.19?

**Comment by griesemer** [comment] 2021-11-10 00:48
Moved to 1.19.

**Comment by dotaheor** [comment] 2022-01-14 14:32
It looks this bug has been fixed in https://golang.org/cl/378434, for https://github.com/golang/go/issues/50190.

**Comment by griesemer** [comment] 2022-01-25 21:33
@mdempsky Is there anything left to do here?

**Comment by mdempsky** [comment] 2022-01-25 22:03
@dotaheor Thanks for pointing that out.

@griesemer I don't think so. I looked over the failure cases, and I don't think they add anything novel beyond ones we added for #50190. Closing.

**Closed by mdempsky** 2022-01-25 22:03 UTC
Labels: NeedsFix, early-in-cycle
