### ISSUE TITLE
golang.org/project

### ISSUE THREAD

**Issue by wsc1** [golang/go#27851] opened 2018-09-25 11:47 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.11

### Does this issue reproduce with the latest release?
It's on the web page

### What operating system and processor architecture are you using (`go env`)?
don't think it matters

### What did you do?
went to http://golang.org/project/

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
go1.11 listed as one of the releases

### What did you see instead?
The latest release listed is go1.10

**Comment by davecheney** [comment] 2018-09-25 12:06
Are you sure that’s the URL, when I click on that link I get a 404

**Comment by wsc1** [comment] 2018-09-25 12:11
oops.  It's [the project link](http://golang.org/project/)

corrected above.  Same problem appears to exist in any case.

**Comment by davecheney** [comment] 2018-09-25 12:13
Thanks for clarifying 

/cc @andybons

**Comment by agnivade** [comment] 2018-09-25 12:53
Duplicate of https://github.com/golang/go/issues/27206

**Closed by agnivade** 2018-09-25 12:53 UTC
