### ISSUE TITLE
A function is not changing the value of a nil pointer parameter

### ISSUE THREAD

**Issue by DrmagicE** [golang/go#25932] opened 2018-06-17 17:48 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.2

### Does this issue reproduce with the latest release?
Not tested

### What operating system and processor architecture are you using (`go env`)?
windows-amd64

```
package main

import "fmt"

type Node struct {
	i int
	next *Node
}

func newNext (n *Node) {
	if n == nil {
		n = &Node{i:101}
	}
	if n.i == 100 {
		newNext(n.next)
		fmt.Println(n.next)  //why the n.next is still nil ?
	}
}
func main() {

	var n *Node
	n = &Node{i:100}
	newNext(n)

}
```
I am trying to use a recursion function to append new nodes to a linked list.
Why the n.next is sitll nil ? I expect it to be ```&Node{i:101}```

Another test
```
func test (n *Node) {
	n = &Node{i:100}
}

func main() {

	var n *Node
	test(n)
	fmt.Println(n) // n is still nil 
}
```
I think it is more  likely to be a feature than a bug. Can someone tell me why? Thanks a lot!

**Comment by meirf** [comment] 2018-06-17 18:20
Focusing on the second snippet:
The call to `test` passes the value of n which is the node address. `test` does not see the address of n.
n inside test is a local variable which has a copy of the original n's value which is the node address. It can't change the original n's value because it doesn't know the original n's address.
I think what you'd want is [this](https://play.golang.org/p/e5Lr4K-tC48).

Please see https://github.com/golang/go/wiki/Questions and close this issue.

**Comment by agnivade** [comment] 2018-06-17 18:22
You are replacing the entire struct. Hence the value does not persist. You have to set `n.i = 100`. Or do what @meirf has posted.

For further questions, please have a look at [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.

Closing since this is not a bug.

**Closed by agnivade** 2018-06-17 18:22 UTC
