### ISSUE TITLE
gofmt doc, tab width=8

### ISSUE THREAD

**Issue by pierrre** [golang/go#20690] opened 2017-06-15 21:10 UTC
### What version of Go are you using (`go version`)?
Not relevant

### What operating system and processor architecture are you using (`go env`)?
Not relevant

### What did you do?
Go to https://golang.org/cmd/gofmt/

### What did you expect to see?
A tab is just a tab, there is not width.

### What did you see instead?
> It uses tabs (width = 8) for indentation

**Comment by griesemer** [comment] 2017-06-15 21:17
Fixed and duplicate of #19618.

**Comment by griesemer** [comment] 2017-06-15 21:17
https://tip.golang.org/cmd/gofmt/ shows the corrected version.

**Closed by griesemer** 2017-06-15 21:17 UTC

**Comment by pierrre** [comment] 2017-06-15 21:20
Sorry for the duplicate.
