### ISSUE TITLE
net: textproto.CanonicalMIMEHeaderKey WWW-Authenticate

### ISSUE THREAD

**Issue by liril-net** [golang/go#45061] opened 2021-03-16 14:46 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOVERSION="go1.16"
</pre></details>

### What did you do?

https://play.golang.org/p/SF66Aho-RB4

### What did you expect to see?

"WWW-Authenticate" [RFC7235](https://tools.ietf.org/html/rfc7235#section-4.1)

### What did you see instead?

"Www-Authenticate"

**Comment by tmthrgd** [comment] 2021-03-16 15:25
This is a duplicate of #18495 and the various linked issues. HTTP header keys are case insensitive and HTTP/2 isn’t case-preserving at all. This is just how the standard library works.

**Closed** 2021-03-16 15:29 UTC
