### ISSUE TITLE
How go get work on a go module

### ISSUE THREAD

**Issue by nocord** [golang/go#33787] opened 2019-08-22 10:43 UTC
How it knows where from it will download a module

**Comment by ALTree** [comment] 2019-08-22 10:46
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2019-08-22 10:46 UTC

**Comment by nocord** [comment] 2019-08-22 10:59
@ALTree, Do you know the answer?

**Comment by nocord** [comment] 2019-08-22 11:00
@ALTree, Do you know the answer?

**Comment by nocord** [comment] 2019-08-22 11:00
@ALTree, Do you know the answer?

**Comment by ALTree** [comment] 2019-08-22 11:18
@nocord I don't understand what you are asking, so, unfortunately, no, I cannot answer your question. 

When you post your question in one of the places I linked above (and not the github tracker, since it's just for issues, and not for asking questions about the language), I suggest expanding it to make it more clear.
