### ISSUE TITLE
cmd/compile: constants in -S output for arm64 have extra high bits set

### ISSUE THREAD

**Issue by randall77** [golang/go#53551] opened 2022-06-25 20:37 UTC
```
package main

func f(x *int8) bool {
	return *x <= 43
}
```
Compiling this program with `-S` for `arm64` has the line:
```
CMPW	$184683593771, R1
```
It should be
```
CMPW	$43, R1
```
Note that `184683593771 = 43<<32 + 43`.
Go 1.16 is ok, this started in Go 1.17. Bisect points to https://go-review.googlesource.com/c/go/+/289649 . It looks maybe intentional? Not sure, but definitely weird.

The actual machine code looks correct. Builders are passing, and `go tool objdump` shows the right disassembly. It's just the `-S` output that appears broken.

@cherrymui @erifan

**Comment by erifan** [comment] 2022-06-26 01:59
This problem has existed for a long time, but CL 289649 exposed it. The root cause is that we modified this constant operand in `progedit ` by copying the lower 32 bits to the upper 32 bits.

We modify this constant just to determine whether it is a `C_BITCON ` class and to encode it as a `C_BITCON`. So maybe we can do this modification (copy the lower 32 bits to the upper 32 bits) just before these two operations (`con32class `and `bitconEncode `), and assign it to a temporary variable, so that the print result will not be modified.

Thanks for reporting this issue, I'll send a fix.

**Closed** 2022-06-28 21:02 UTC
