### ISSUE TITLE
cmd/go: go test should not report two compilation failures

### ISSUE THREAD

**Issue by rsc** [golang/go#26125] opened 2018-06-29 05:05 UTC
```
$ cat x_test.go
package p

func f() {
	return 1
}
$ go test x_test.go
# command-line-arguments [command-line-arguments.test]
./x_test.go:4:2: too many arguments to return
	have (number)
	want ()
# command-line-arguments
./x_test.go:4:9: no result values expected
vet: typecheck failures
FAIL	command-line-arguments [build failed]
$ 
```

The compiler is failing and the vet is failing. It's annoying (or worse) to print the same errors twice, in slightly different forms.
Go 1.10 did the right thing (perhaps because it ignored vet typecheck errors entirely in go test).
Should fix for Go 1.11.
We may need to start ignoring typecheck errors for one more release anyway, in which case we'd get this for free, but we should put in a real fix too, and a test, or else this will happen again in Go 1.12 or whenever we do re-enable typecheck errors from go vet during go test.

**Comment by jimmyfrasche** [comment] 2018-06-29 05:12
Duplicate of #26100 ?

**Comment by robpike** [comment] 2018-06-29 07:42
It is a duplicate, but this one has an example. I'll close that one.

**Comment by robpike** [comment] 2018-06-29 07:43
My suggestion from 26100 is just to suppress errors from vet until compilation has succeeded.

**Comment by ysmolsky** [comment] 2018-06-30 12:01
Wanted behaviour of vet in the compiler is similar to the way vet is implemented in Playground. There vet check is performed only if the compilation has succeeded. I see this as a good UI.

Playground with vet check is not deployed, thought. @andybons, have you planned the deployment of Playground?

**Comment by andybons** [comment] 2018-06-30 13:53
@ysmolsky let’s discuss playground deployment off this thread :). (short answer: no, but only because I just haven’t gotten to it).

**Comment by ysmolsky** [comment] 2018-07-13 09:38
Anyone working on this?

**Closed** 2018-07-19 19:17 UTC
Labels: NeedsFix, release-blocker
