### ISSUE TITLE
x/tools/present: unexpected display style for subsection

### ISSUE THREAD

**Issue by peggyl** [golang/go#15633] opened 2016-05-10 21:03 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
`go version go1.6.2 darwin/amd64`

2. What operating system and processor architecture are you using (`go env`)?
``` 
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/peggyli/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.2/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?

Create a `.slide` file with the following contents (taken from example on https://godoc.org/golang.org/x/tools/present) and run with the `present` cmd tool:
```
Test Title
Name

* Title of slide or section (must have asterisk)

Some Text

** Subsection

- bullets
- more bullets
- a bullet with

*** Sub-subsection

Some More text

  Preformatted text
  is indented (however you like)
```

4. What did you expect to see?
Expected the `1.1 Subsection` heading to come between `Some text` and the itemized list, like in the file. Tested on recent versions of Chrome, Firefox, Safari to remove possibility of browser-specific issue or rogue extension.

5. What did you see instead?
<img width="1110" alt="screen shot 2016-05-09 at 7 49 39 pm" src="https://cloud.githubusercontent.com/assets/2467815/15162192/8a776c5a-16b6-11e6-8c9c-597df9bda0e4.png">

It's unclear what the expected rendering is; I checked golang/talks and davecheney/presentations, but the subsection level (`**`) doesn't appear to be widely used.

**Comment by adg** [comment] 2016-05-23 21:13
Present's slide view doesn't currently support sub-sections. This issue can be about implementing that support.

**Comment by adg** [comment] 2016-05-27 03:30
Dupe of #6846

**Closed by adg** 2016-05-27 03:30 UTC
