### ISSUE TITLE
wasm: expose functions on instance.exports like rust and emscripten

### ISSUE THREAD

**Issue by lucacasonato** [golang/go#31574] opened 2019-04-19 20:35 UTC
It would be nice to expose exported functions from go modules in the WASM instance.exports like Rust and emscripten does. This would allow for Go to work nicely with ES modules so it doesn't have to rely on assigning anything to the JS global object. This would also make the interface for calling WASM functions more standard and feel more natural in ES modules. 

### Example
```go
// math.go

package math

import "syscall/js"

func Add(i []js.Value) js.Value {
    return js.ValueOf(i[0].Int()+i[1].Int())
}
```
```html
<html>
    <head>
      <meta charset="utf-8">
      <script src="wasm_exec.js"></script>
      <script>
           async function init() {
                const go = new Go();
                let result = await WebAssembly.instantiateStreaming(fetch("main.wasm"), go.importObject)
                console.log(result.instance.exports.Add(1+1))
           }

           init();
       </script>
    </head>
    <body></body>
</html>
```

### How does Rust do this 
https://www.hellorust.com/demos/add/index.html
```rust
// add.rs

#[no_mangle]
pub fn add(a: i32, b: i32) -> i32 {
  return a + b
}
```
```html
<html>
    <head>
      <meta charset="utf-8">
      <script>
            async function init() {
                let result = await WebAssembly.instantiateStreaming(fetch("main.wasm"))
                console.log(result.instance.exports.Add(1+1))
            }
            init();
       </script>
    </head>
    <body></body>
</html>
```

emscripten also has support for instance.exports (https://gist.github.com/kripken/59c67556dc03bb6d57052fedef1e61ab).

Here is some more info on exported functions in WASM: https://developer.mozilla.org/en-US/docs/WebAssembly/Exported_functions

**Comment by agnivade** [comment] 2019-04-20 04:17
Duplicate of https://github.com/golang/go/issues/25612

**Closed by agnivade** 2019-04-20 04:17 UTC
Labels: Arch-Wasm, FeatureRequest, NeedsInvestigation
