### ISSUE TITLE
x/pkgsite: package removal request for xinhari.com/hari

### ISSUE THREAD

**Issue by agus7fauzi** [golang/go#52131] opened 2022-04-03 22:11 UTC
### What is the path of the package that you would like to have removed?
xinhari.com/hari
 
 
 
### Are you the owner of this package?
Yes

 
### What is the reason that you could not retract this package instead?
Due to lack of communication in the team we made a mistake with the first release using v1 which we ended up really regretting, so we decided again to restart the version using v0, but unfortunately when we used v0 we got v1 when running go get xinhari.com/hari and we also thought it would be bad for marketing because of the bad version history. So due to marketing considerations, the issue of v0 not being detected in the latest version because v1 exists and we believe no one has used our version, we sincerely request that our module be removed from pkg.go.dev instead of retracting it, so that we can start over from scratch, thanks.

**Comment by jamalc** [comment] 2022-04-05 13:21
Duplicate of #52130

**Closed by jamalc** 2022-04-05 13:21 UTC
Labels: pkgsite
