### ISSUE TITLE
net: root dns zone lookups not working

### ISSUE THREAD

**Issue by pjediny** [golang/go#46577] opened 2021-06-04 20:34 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 darwin/amd64
</pre>

### What did you do?

Tried to query root zone NS records, to emulate
<pre>
dig -t ns -q .
</pre>

<pre>
func main() {
	r, err := net.LookupNS(".")

	if err != nil {
		fmt.Printf("%v\n", err)
		return
	}
	fmt.Println(len(r), r)
}
</pre>

### What did you expect to see?

List of ns records.

### What did you see instead?

<pre>
lookup .: no such host
</pre>

**Comment by seankhliao** [comment] 2021-06-04 20:38
Duplicate of #45715

**Closed by seankhliao** 2021-06-04 20:38 UTC
