### ISSUE TITLE
crypto/x509: unhandled error 

### ISSUE THREAD

**Issue by walkerxiong** [golang/go#50570] opened 2022-01-12 12:18 UTC
Hi,

I found a unhandled error at [https://github.com/golang/go/blob/master/src/crypto/x509/x509.go#L1310](https://github.com/golang/go/blob/master/src/crypto/x509/x509.go#L1310).

If this error should be ignored, I think the if statement `err != nil` can be eliminated.

**Comment by seankhliao** [comment] 2022-01-12 12:39
Duplicate of #49135

**Closed by seankhliao** 2022-01-12 12:39 UTC
