### ISSUE TITLE
typecasting +Inf to int, should result positive value

### ISSUE THREAD

**Issue by santhosh-tekuri** [golang/go#20517] opened 2017-05-28 10:56 UTC
### What version of Go are you using (`go version`)?
go version go1.8.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?

go program used to test:  https://play.golang.org/p/EdOljzgjr0
~~~go
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(int(math.Inf(+1)), int(math.Inf(-1)))
}
~~~

both -Inf and +Inf result same value when converted into int

for example in java, converting +Inf to int returns Integet.MAX_VALUE which is positive

not sure what is expected behaviour as per go-lang specification

### What did you expect to see?
`2147483647 -2147483648`

### What did you see instead?
`-2147483648 -2147483648`

**Comment by ALTree** [comment] 2017-05-28 12:49
Thanks for the report. 

Yes, this is allowed by the spec:

> In all non-constant conversions involving floating-point or complex values, **if the result type cannot  represent the value the conversion succeeds but the result value is implementation-dependent**. 

Closing this, since it's not a bug.

**Closed** 2017-05-28 12:49 UTC
