### ISSUE TITLE
How to extract the code coverage value from go test -coverprofile=cover.out?

### ISSUE THREAD

**Issue by HaoyuanY** [golang/go#24290] opened 2018-03-07 06:03 UTC
Hi all, I am working on a CI(TFS2015) for our go application and I want to ensure the code quality. For example, when the code coverage of go application is low(less than 60%), the CI will fail the building process. Now I can use the "go test -coverprofile=cover.out" command to get the code coverage value successfully, but I don't know how to extract this value so it can be used in other places, such as a PowerShell script. I tried to read the cover.out file but it didn't have the coverage result. I am wondering how can I extract this value?

**Comment by ALTree** [comment] 2018-03-07 20:21
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2018-03-07 20:21 UTC
