### ISSUE TITLE
gopls: find all references in monorepo

### ISSUE THREAD

**Issue by roopakv** [golang/go#36936] opened 2020-01-31 18:21 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/roopak/Library/Caches/go-build"
GOENV="/Users/roopak/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/roopak/workspace/go/default"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/roopak/workspace/source/hail/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s3/mcr5r_9973z0pznr8vzdkkzw0000gn/T/go-build738208365=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I opened our monorepo in vscode. and opened a go file and tried to findAllReferences. It found 0 references.
<pre>
source/
|---hail (go repo)
       |--- go.mod
       |--- go.sum
       |--- go code...
|--- non go repo
       |--- typescript code
|--- non go repo 2
       |---- other code.
</pre>

If i opened the go directory directly it works.

### What did you expect to see?
References found

### What did you see instead?
no references found.

cc @stamblerre who recently released gopls v0.3.0

**Comment by stamblerre** [comment] 2020-01-31 18:39
Can you please share the output of `gopls -rpc.trace -v references path/to/file.go:<line>:<col>`?

**Comment by stamblerre** [comment] 2020-01-31 18:43
Also, did you open VS Code from the root of your Go module or from the monorepo root? As mentioned in the release notes (https://github.com/golang/go/issues/33030#issuecomment-580827997) and the linked https://github.com/golang/go/issues/36899, you will have to use the module root as your workspace root. You can achieve this in VS Code by adding your module root as another workspace folder (File -> Add Folder to Workspace).

**Comment by roopakv** [comment] 2020-01-31 21:51
@stamblerre I opened the monorepo root.

It works fine if i do the hack you mentioned, or if i open the go mod root. What i filed this issue for is to support monorepos by letting me define which sub folder is the go module root.

Somewhere as a command line flag maybe? I think there will be more people who might run into this.

**Comment by stamblerre** [comment] 2020-01-31 21:54
Yes, I agree that users will run into this issue, which is why we have #36899 to track this. We will post updates there on our progress with this work.

**Comment by stamblerre** [comment] 2020-01-31 21:54
Duplicate of #36899

**Closed by stamblerre** 2020-01-31 21:54 UTC
Labels: gopls
