### ISSUE TITLE
not pi equels pi?!

### ISSUE THREAD

**Issue by Macilias** [golang/go#22870] opened 2017-11-24 13:55 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mniemczyk/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3k/0437mzfx1qxcc3j5p9pqmytm0000gn/T/go-build611048518=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
learned how to compare values in Go with go

If possible, provide a recipe for reproducing the error.
yes

A complete runnable program is good.
```
package main

import (
	"fmt"
)

func main() {

	// This is probably a bug!
	po := 3.141592653589793
	pi := 3.14159265358979323846264338327950288419716939937510582097494459
	if po == pi {
		fmt.Println("this should not be true, but is")
	}
}
```

A link on play.golang.org is best.

### What did you expect to see?
no output -> since po != pi

### What did you see instead?
print out, because go figured po == pi

**Comment by ALTree** [comment] 2017-11-24 14:11
> no output -> since po != pi

This is not correct. The two numbers are indeed equal. Go variables are not arbitrary precision, floats have, in this case, 53 bits of precision. 

The two variables you defined have the same first 53 bits, so they have the same `float64` value, and they are equal.


Since the Go project does not use its bug tracker for general discussion or asking questions about the language, please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions) if you have further questions regarding how numbers work in go. Thanks.

Closing, since this is not a bug.

**Closed by ALTree** 2017-11-24 14:11 UTC

**Comment by Macilias** [comment] 2017-11-24 14:14
ok, got it
