### ISSUE TITLE
go test all includes standard library

### ISSUE THREAD

**Issue by anacrolix** [golang/go#29932] opened 2019-01-25 05:57 UTC
Running go test all in a package with modules enabled also tests the standard library. This can take a very long time. Perhaps there should be a way to skip the standard library, or it should be skipped by default.

**Comment by agnivade** [comment] 2019-01-25 07:36
Duplicate of https://github.com/golang/go/issues/26317.

Please see these comments in particular - https://github.com/golang/go/issues/26317#issuecomment-411758321,  https://github.com/golang/go/issues/26317#issuecomment-411872150

Also see https://github.com/golang/go/issues/29676.

**Closed by agnivade** 2019-01-25 07:36 UTC
