### ISSUE TITLE
proposal: golang.org/x/exp/slices: Add "Merge"

### ISSUE THREAD

**Issue by 6543** [golang/go#61815] opened 2023-08-07 16:05 UTC
As `append(append(append(a, b...), c...), d...)` is way to common :/

I propose a function that gets  **a list of slices of same type** and return *one slice of that type** 

```go
// Merge return a new slice that combines all values of input slices
func Merge[T any](slices ...[]T) []T {
	sl := 0
	for i := range slices {
		sl += len(slices[i])
	}
	result := make([]T, sl)
	cp := 0
	for _, s := range slices {
		if sLen := len(s); sLen != 0 {
			copy(result[cp:], s)
			cp += sLen
		}
	}
	return result
}
```

test:
```go
	resultSS := MergeSlices([]string{}, []string{"a", "b"}, []string{"c"}, nil)
	assert.EqualValues(t, []string{"a", "b", "c"}, resultSS)

	resultIS := MergeSlices([]int{}, []int{1, 2}, []int{4}, nil)
	assert.EqualValues(t, []int{1, 2, 4}, resultIS)
```

**Comment by ericlagergren** [comment] 2023-08-07 16:08
Dupe of https://github.com/golang/go/issues/56353

**Comment by seankhliao** [comment] 2023-08-07 16:09
Duplicate of #56353

**Closed by seankhliao** 2023-08-07 16:09 UTC
Labels: Proposal
