### ISSUE TITLE
cmd/fmt: adjacent closing braces on separate lines have same indentation

### ISSUE THREAD

**Issue by willfaught** [golang/go#23021] opened 2017-12-07 00:07 UTC
#### What did you do?

```go
func main() {
	if a, e := result, (a.F{
			D: &a.D{I: map[s]a.I{
				"2": a.I{I: "2"},
			},
		}, O: []string{"2"}}); !reflect.DeepEqual(a, e) {
		t.Fail()
	}
}
```

https://play.golang.org/p/P6zFZQH2jJ

Press the format button.

#### What did you expect to see?

Nothing changed.

#### What did you see instead?

```go
func main() {
	if a, e := result, (a.F{
		D: &a.D{I: map[s]a.I{
			"2": a.I{I: "2"},
		},
		}, O: []string{"2"}}); !reflect.DeepEqual(a, e) {
		t.Fail()
	}
}
```

The

```go
D: &a.D{I: map[s]a.I{
	"2": a.I{I: "2"},
},
```

part was dedented by one tab. Seeing two adjacent

```
},
},
```

with the same indentation seems wrong.

#### System details

```
go version go1.9.2 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/willfaught/Developer/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_1/ggvd2t1x7hz_185crsb36zlr0000gp/T/go-build489885762=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOROOT/bin/go version: go version go1.9.2 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.9.2
uname -v: Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B1003
lldb --version: lldb-900.0.64
  Swift-4.0
```

**Comment by dsnet** [comment] 2017-12-07 00:15
Is this a duplicate of #16371?

**Comment by mvdan** [comment] 2017-12-07 00:22
Seems like a dup to me.

**Comment by willfaught** [comment] 2017-12-07 04:17
I saw that one, but I wasn’t sure if it was the exact same thing. Feel free to close if so.

**Closed** 2017-12-07 05:07 UTC
Labels: NeedsDecision
