### ISSUE TITLE
cmd/compile: fail to infer type with only one valid solution

### ISSUE THREAD

**Issue by Ludonope** [golang/go#50212] opened 2021-12-16 11:33 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

I'm trying to make some sort of `Nullable` constraint which would indicate if that type can be set to `nil` or not.

Right now I'm only trying to detect pointers and slices.

One way to detect a pointer type (which works) is the following:

```go
type Ptr[T any] interface {
	~*T
}

func SetNil[U any, T Ptr[U]](val T) {
	val = nil
}

func main() {
    a := 0
    SetNil(&a)
}
```

It can also be done with slice type:

```go
type Slice[T any] interface {
	~[]T
}

func SetNil[U any, T Slice[U]](val T) {
	val = nil
}

func main() {
    SetNil([]int{})
}
```

However if I try to combine those into a `Nullable` constraint the type inference breaks for `U`.

https://go.dev/play/p/SbBJnOUeFVP?v=gotip

Providing the types `U` and `T` explicitly works tho.

### What did you expect to see?

I'm expecting the compiler to properly infer `U`and `T` types. As there are multiple options for `T` but only one of them is valid, it should be able to try to deduce `U` just like it does when using the `Ptr[T]` or `Slice[T]` constraint.

### What did you see instead?

```
./prog.go:20:8: cannot infer U (prog.go:15:13)

Go build failed.
```

You should be able to reproduce this with the `go.dev/play` link provided above.

**Comment by cherrymui** [comment] 2021-12-16 20:12
cc @griesemer

**Comment by griesemer** [comment] 2021-12-16 21:12
Constraint type inference requires that there's a [structural type](https://tip.golang.org/ref/spec#Structure_of_interfaces) present in the constraint (the inference part is not yet in the spec, but the generics proposal describes a much). Here we have two types in the constraint and they are different, so there's no structural type.

We're not going to change that for 1.18. Feel free to send out a detailed proposal. Thanks.

Closing as working as intended.

**Closed by griesemer** 2021-12-16 21:12 UTC
Labels: NeedsInvestigation
