### ISSUE TITLE
Constant error returned by RPC does not equal to original

### ISSUE THREAD

**Issue by vonzcy** [golang/go#25812] opened 2018-06-11 00:08 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.10.2 darwin/amd64

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?
I have a couple of error type variables defined globally. For example,

```go
var ErrFileNotExist = errors.New("File does not exist")
```

On server side, this is used as a return value in an RPC, for example,

```go
func (t *Type) F(args *T1, reply *T2) error {
   ...
   // some code here.
   return ErrFileNotExist
}
```
But on client side invoking this RPC and getting the return value, compare it with the global `ErrFileNotExist`, it does not match. That is, 
```go
...
// client set up
e := c.Call(...)
log.Prinln(e) // File does not exist
log.Println(e == ErrFileNotExist)  // false
```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Playground link (RPC cannot run):
https://play.golang.org/p/RFOF_c1DT0F

### What did you expect to see?
Shouldn't the value equality be preserved? It works on local call.

### What did you see instead?
The returned value does not equal to the global ErrFileNotExist by value.

**Comment by meirf** [comment] 2018-06-11 01:42
The error from the rpc call is of type `ServerError` (which wraps the underlying error). The global error is of type `errorString`. So I don't think they can be equal.

**Comment by vonzcy** [comment] 2018-06-11 01:43
@meirf Yeah, I believe so. Is there any workaround?

**Comment by meirf** [comment] 2018-06-11 01:54
Specific to this exact error ""File does not exist" that doesn't seem too exceptional - maybe just include a bool in the reply struct.

More generally, I've seen pattern of a very thin client library for each rpc server. The global error could live in that library. The library could look at the reply and/or error and decide if that library call should return library error.

But I'm not an expert on error best practices. Best to close this issue, read https://godoc.org/github.com/pkg/errors, dave cheney's blogs and ask around in go nuts for more advice.

**Comment by agnivade** [comment] 2018-06-11 04:20
Thanks @meirf for the analysis. Closing as this is not a bug. @vonzcy - please have a look at [Questions](https://github.com/golang/go/wiki/Questions) wiki page for places to ask for advice.

**Closed by agnivade** 2018-06-11 04:20 UTC
