### ISSUE TITLE
embed: embed.file.ModTime() returns zero time

### ISSUE THREAD

**Issue by yffrankwang** [golang/go#46935] opened 2021-06-26 03:02 UTC
The current implementation of embed.file just returns zero time.
~~~
func (f *file) ModTime() time.Time         { return time.Time{} }
~~~

The http file server does not set the http header 'Date', if file's ModTime is zero.
~~~
http.Handle("/static/", http.StripPrefix("/static/", http.FileServer(http.FS(content))))
~~~

Is it possible to set the local file's real modification time to the embed file at compile time?

**Comment by zikaeroh** [comment] 2021-06-26 07:38
See https://github.com/golang/go/issues/44854#issuecomment-792805927.

**Comment by seankhliao** [comment] 2021-06-26 07:52
Duplicate of #44854

**Closed by seankhliao** 2021-06-26 07:52 UTC
