### ISSUE TITLE
Point value of struct with anonymous interface field created by reflect not  AssignableTo the interface type

### ISSUE THREAD

**Issue by xiezhenye** [golang/go#47343] opened 2021-07-22 12:54 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/zhenyexie/Library/Caches/go-build"
GOENV="/Users/zhenyexie/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zhenyexie/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zhenyexie/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zc/tvrbqknd2lq349yxhm1z3cch0000gn/T/go-build350205865=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

run

<pre>
package main

import (
        "reflect"
)

type I1 interface {
        Get() string
}

type P struct {
        I1
}

type s string

func (s s) Get() string {
        return string(s)
}

func main() {
        var a I1
        typ := reflect.TypeOf(&a).Elem()
        pt := reflect.StructOf([]reflect.StructField{
                {
                        Name: typ.Name(),
                        Anonymous: true,
                        Type: typ,
                },
        })
        ptv := reflect.New(pt)
        println(ptv.Type().String())
        println(ptv.Type().AssignableTo(reflect.TypeOf(&a).Elem()))
        // equine to  &struct { I1 }{ s("aaa") }
}

</pre>

### What did you expect to see?
*struct { I1 main.I1 }
false

### What did you see instead?
*struct { I1 main.I1 }
true

**Comment by bcmills** [comment] 2021-07-22 18:22
This looks like a known defect in `reflect.StructOf`. Per https://beta.pkg.go.dev/reflect#StructOf:
> StructOf currently does not generate wrapper methods for embedded fields and panics if passed unexported StructFields. These limitations may be lifted in a future version.

**Comment by xiezhenye** [comment] 2021-07-23 01:22
```go
println(ptv.Type().Elem().AssignableTo(reflect.TypeOf(&a).Elem())) // returns true

a1 := ptv.Elem().Interface()
a = a1.(I1)

a.Get() 
/*
panic: 
unexpected fault address 0x1400000c048
fatal error: fault
[signal SIGBUS: bus error code=0x1 addr=0x1400000c048 pc=0x1400000c048]

*/
```

**Comment by seankhliao** [comment] 2021-07-25 09:39
Duplicate of #15924

**Closed by seankhliao** 2021-07-25 09:39 UTC
