### ISSUE TITLE
cmd/go: ability to list available major versions of a module

### ISSUE THREAD

**Issue by myitcv** [golang/go#26286] opened 2018-07-09 11:16 UTC
Picking up discussion from https://go-review.googlesource.com/c/vgo/+/122075#message-2f083e869e098fd047f0f846690e3c0b8c9dd191:

> What's the workflow where you think that kind of more general query will be important?

There are two that I've come across so far:

* converting a "project" to be vgo-aware, where a dependency imported as, for example, `example.com/blah`, happens to be `v >= 2`. If you're converting a project that does _not_ have a well known dependency manager file that tells vgo the dependency version is, say, `2.4.0`, then you need to discover the latest major version (because that's almost certainly what you want) in order to either adjust import paths or `vgo get ...@vX`
* similarly, the other day I wanted to use `mvdan.cc/sh/syntax`. Now arguably I'm still thinking in terms of "old" Go import paths. No doubt we'll need to add something to godoc.org to list major versions etc, but until we get there I needed to see what major versions were available in order that I could choose the latest. (I think we can ignore the fact that `mvdan.cc/sh/syntax` has itself not been converted to be vgo-aware).

In both cases, especially for custom import paths, this involves a couple of lookups via curl, github etc. Not impossible, but if we had this as part of the vgo command that would help.

**/cc** @rsc @bcmills

**Comment by bcmills** [comment] 2018-07-09 20:10
There is a more general case of the “converting a project” use-case: it is very similar to “upgrading a project to a new major version”.

At some point we may want some sort of mode (`go get -u=major` or `go fix -m`?) that forcibly upgrades imports of a module to a newer major version — for example, by inlining functions in the old version that wrap calls to the new version, or forcibly updating import paths without ensuring that the resulting code actually compiles, or perhaps some other means.

We probably shouldn't actually implement that mode at this point in time, but we can at least consider how `list -m -versions` might interact with it. (If there is a `list` behavior that harmonizes well with all reasonable “forcible upgrade” designs, we could go ahead and implement at least the `list` part.)

**Comment by rsc** [comment] 2018-07-17 17:53
For legacy concerns this is a duplicate of #26238, and the fix for that issue will start showing legacy v2 v3 etc as if they were "versions" of v1.

For non-legacy concerns (you're using x and want to find out that x/v2 exists) I think that's beyond the scope of the go command.

So closing as duplicate / out of scope.

**Closed by rsc** 2018-07-17 17:53 UTC
Labels: NeedsInvestigation, modules

**Comment by vith** [comment] 2019-04-30 19:49
> For non-legacy concerns (you're using x and want to find out that x/v2 exists) I think that's beyond the scope of the go command.

I hope this will be reconsidered. I think major versions being developed and maintained as if they are separate projects is the exception, not the rule.

It wouldn't surprise me if hiding the availability of new major versions from developers who are querying for out of date dependencies contributes to a hesitance to bump major versions at all, even when semver semantics demands it.

**Comment by R-omk** [comment] 2020-03-06 07:44
@bcmills 
So what about the ability to view possible major versions via  `go list -u -m -versions` command?
This would help a lot in finding versions for a variety of testing and building **automation tools** and
this method looks much more preferable than manual tag parsing in a VCS.

**Comment by bcmills** [comment] 2020-03-06 14:17
@R-omk, note that this issue is closed, and we do not normally track closed issues.

Since different major versions have different import paths (and, presumably, incompatible APIs), it does not seem feasible in general to build automation tools that can upgrade across major versions without additional metadata.

(But see #32816 for a related proposal for additional metadata.)
