### ISSUE TITLE
encoding/xml: xml.Unmarshal error

### ISSUE THREAD

**Issue by sam-mix** [golang/go#50131] opened 2021-12-13 11:39 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\m\AppData\Local\go-build
set GOENV=C:\Users\m\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\m\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\m\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\dev\lang\go\1_17_5
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\dev\lang\go\1_17_5\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.5
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\m\AppData\Local\Temp\go-build2685861778=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

[error-code](https://go.dev/play/p/rlyr4MGXKJU?v=gotip)
[right-code](https://go.dev/play/p/87dAtLc2RoI?v=gotip.go?download=true)

### What did you expect to see?
13

### What did you see instead?
0

**Comment by seankhliao** [comment] 2021-12-13 11:52
Duplicate of #11735

**Closed by seankhliao** 2021-12-13 11:52 UTC
