### ISSUE TITLE
cmd/go: leading underscore in folder name causes issues

### ISSUE THREAD

**Issue by carnott-snap** [golang/go#34670] opened 2019-10-02 23:48 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/.local/share/umake/go/go-lang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/.local/share/umake/go/go-lang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build175172522=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```sh
[user@localhost ~]$ mkdir -p /tmp/_test
[user@localhost ~]$ cd /tmp/_test
[user@localhost ~]$ go mod init test # replacing this with a valid routable path has no impact
[user@localhost ~]$ echo 'package test; import _ "gopkg.in/yaml.v2"' > test.go
[user@localhost ~]$ cat go.mod 
module test

go 1.13
[user@localhost ~]$ go build
[user@localhost ~]$ cat go.mod 
module test

go 1.13

require gopkg.in/yaml.v2 v2.2.4
[user@localhost ~]$ go mod tidy
[user@localhost ~]$ cat go.mod
```

### What did you expect to see?
```gomod
// go.mod
module test

go 1.13

require gopkg.in/yaml.v2 v2.2.4
```

### What did you see instead?
It appears that `go mod tidy` either fails, thus removes all existing dependencies:
```gomod
module test

go 1.13
```

**Comment by robpike** [comment] 2019-10-03 04:19
The go command's documentation says, "// Files whose names begin with "_" (including "_test.go") or "." are ignored."
I suspect that's the root of it.

**Comment by carnott-snap** [comment] 2019-10-03 04:27
To confirm, if I have a go module contained within `/home/user/_workspace` is that expected to cause the cause the toolchain concern? My expectation is that in `GOPATH` mode it should, since `go/src/.../_mypackage` is part of the import statement, but in module mode the toolchain should only look down the file tree, right?

**Comment by andybons** [comment] 2019-10-03 16:02
@bcmills @jayconrod

**Comment by bcmills** [comment] 2019-10-03 16:14
@carnott-snap, this should be fixed with a `go` binary built from head. (Please let us know if you find that is not the case.)

**Comment by bcmills** [comment] 2019-10-03 16:14
Duplicate of #28481

**Closed by bcmills** 2019-10-03 16:14 UTC
Labels: NeedsInvestigation
