### ISSUE TITLE
Cross compile linux on Windows gives Access Denied

### ISSUE THREAD

**Issue by ddhawal** [golang/go#39047] opened 2020-05-13 10:12 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.9 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ddhawal\AppData\Local\go-build
set GOEXE=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=linux
set GOPATH=c:\checkout\gitlab
set GOPROXY=direct
set GORACE=
set GOROOT=c:\go
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\checkout\internal\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=C:\Users\dd\AppData\Local\Temp\go-build526978046=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
go build ./...

This is working fine when I change GOOS=windows

### What did you expect to see?
Successful compilation

### What did you see instead?
build github.com/dd/v3/cmd/hvs: cannot load golang.org/x/sys/unix: rename c:\checkout\gitlab\pkg\mod\golang.org\x\sys@v0.0.0-20190412213103-97732733099d.tmp-837266893 c:\checkout\gitlab\pkg\mod\golang.org\x\sys@v0.0.0-20190412213103-97732733099d: Access is denied.

**Comment by networkimprov** [comment] 2020-05-14 11:05
Dup of #36568?

**Comment by bcmills** [comment] 2020-05-14 19:31
Duplicate of #36568

**Closed by bcmills** 2020-05-14 19:31 UTC
