### ISSUE TITLE
Can't call functions of the embedded generic type.

### ISSUE THREAD

**Issue by googollee** [golang/go#46778] opened 2021-06-16 08:53 UTC
### What version of Go are you using (`go version`)?

<pre>
https://go2goplay.golang.org
</pre>

### Does this issue reproduce with the latest release?

No. It reproduces in go2go playground. I think it's the latest dev.go2go branch.

### What operating system and processor architecture are you using (`go env`)?

<details><summary>
https://go2goplay.golang.org
</pre></details>

### What did you do?

https://go2goplay.golang.org/p/yzQf7H3ywV7

```go
package main

type base[T any] struct {}

func (b *base[T]) Func() {}

type Enum struct {
	base[int]
}

func main() {
	e := Enum{}
	e.Func()
}
```

### What did you expect to see?

`e.Func()` should be called succeeded.

### What did you see instead?

Go bulid failed.

```
# _/tmp/sandbox989056293
./prog.go2:13: e.base undefined (type Enum has no field or method base)
```

If I change that line to `e.base.Func()`, the code works.

**Comment by seankhliao** [comment] 2021-06-16 10:24
Duplicate of #44689

**Closed by seankhliao** 2021-06-16 10:24 UTC
