### ISSUE TITLE
debug.Stack() not specific

### ISSUE THREAD

**Issue by fwhezfwhez** [golang/go#27844] opened 2018-09-25 07:01 UTC
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

I want to locate an error stacktrace,however the result is not specific.
here is the example:
https://play.golang.org/p/vE4F-S75Jpl.

#### What did you expect to see?

I want to see where the error starts.
for example  I want to see
```
do sth!
error happen
goroutine 1 [running]:
runtime/debug.Stack(0x1042ffa0, 0x1, 0x1, 0x1040c138)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xc0
main.main()
	/tmp/sandbox838488776/main.go:13 +0x100
main.makeError()
        /tmp/xxxxxxxxxxxxxxxx/main.go:19 + xxxx
```
#### What did you see instead?

But I get:
```
do sth!
error happen
goroutine 1 [running]:
runtime/debug.Stack(0x1042ffa0, 0x1, 0x1, 0x1040c138)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xc0
main.main()
	/tmp/sandbox838488776/main.go:13 +0x100
```

#### System details

```
go version go1.11 windows/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="C:\Users\DELL\AppData\Local\go-build"
GOEXE=".exe"
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="windows"
GOOS="windows"
GOPATH="C:\Users\DELL\go"
GOPROXY=""
GORACE=""
GOROOT="E:\go_1.11"
GOTMPDIR=""
GOTOOLDIR="E:\go_1.11\pkg\tool\windows_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.11 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.11
gdb --version: GNU gdb (GDB) 7.8
```

**Comment by urandom** [comment] 2018-09-25 12:51
Not official, but plenty of tested third party ones. E.g.:
https://github.com/pkg/errors

**Comment by ianlancetaylor** [comment] 2018-09-25 13:46
Closing because this is working as intended.

**Closed by ianlancetaylor** 2018-09-25 13:46 UTC
