### ISSUE TITLE
Special block for functions Annotations

### ISSUE THREAD

**Issue by dangerousvasil** [golang/go#70940] opened 2024-12-20 09:47 UTC
### Go Programming Experience

Intermediate

### Related Idea

- [ ] Has this idea, or one like it, been proposed before?
- [ ] Does this affect error handling?
- [ ] Is this about generics?
- [ ] Is this change backward compatible? Breaking the Go 1 compatibility guarantee is a large cost and requires a large benefit

### Has this idea, or one like it, been proposed before?

no

### Does this affect error handling?

no

### Is this about generics?

no

### Proposal

Some libs use godoc block for change program behavior! 
Create functional optional block for functions like for fields in struct 

example : 
https://github.com/swaggo/gin-swagger
```
// @BasePath /api/v1

// PingExample godoc
// @Summary ping example
// @Schemes
// @Description do ping
// @Tags example
// @Accept json
// @Produce json
// @Success 200 {string} Helloworld
// @Router /example/helloworld [get]
func Helloworld(g *gin.Context)  {
	g.JSON(http.StatusOK,"helloworld")
}
```
turn into 

```
// BlahBlah godoc
// DO ping example
func [
"BasePath" : "/api/v1"
"Accept" : "json"
"Produce" :  "json"
"Router" : "/example/helloworld [get]"
"Schemes" : "https"
] (s *BarBar) BlahBlah(foo string) error {
return nil
}
```

and we separate godoc functional and annotation functions

### Language Spec Changes

optional block annotations after keyword func
```
func **[
@desc: annotation
]** (s *BarBar) BlahBlah(foo string) error {
return nil
}
```

### Informal Change

It was use full for separate additional logic of application and documentations

### Is this change backward compatible?

yes block is optional

**Comment by seankhliao** [comment] 2024-12-20 10:09
Duplicate of #36669

**Closed by seankhliao** 2024-12-20 10:09 UTC
Labels: LanguageChange, Proposal, LanguageChangeReview
