### ISSUE TITLE
x/vgo: vgo fails when have hashicorp's vault as a dependency

### ISSUE THREAD

**Issue by felipeweb** [golang/go#24638] opened 2018-04-02 13:42 UTC
#### What did you do?
vgo build

#### Output

```
vgo: finding google.golang.org/grpc v1.10.0
vgo: finding google.golang.org/genproto v0.0.0-20180306020942-df60624c1e9b
vgo: finding google.golang.org/appengine v1.0.0
vgo: finding golang.org/x/text v0.0.0-20171214130843-f21a4dfb5e38
vgo: finding golang.org/x/oauth2 v0.0.0-20180312235849-7af32f14d0a2
vgo: finding golang.org/x/net v0.0.0-20180313215339-892bf7b0c6e2
vgo: finding github.com/sethgrid/pester v0.0.0-20180227223404-ed9870dad317
vgo: finding github.com/ryanuber/go-glob v0.0.0-20160226084822-572520ed46db
vgo: finding github.com/pkg/errors v0.8.0
vgo: finding github.com/mitchellh/mapstructure v0.0.0-20180220230111-00c29f56e238
vgo: finding github.com/mitchellh/go-homedir v0.0.0-20161203194507-b8bc1bf76747
vgo: finding github.com/kelseyhightower/envconfig v1.3.0
vgo: finding github.com/hashicorp/vault v0.9.5
FindRepo: Get https://appengine?go-get=1: dial tcp: lookup appengine: no such host
FindRepo: Get https://appengine/cloudsql?go-get=1: dial tcp: lookup appengine: no such host
FindRepo: Get https://appengine_internal?go-get=1: dial tcp: lookup appengine_internal: no such host
FindRepo: Get https://appengine_internal/base?go-get=1: dial tcp: lookup appengine_internal: no such host
```

#### System details

```
go version go1.10 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/felipeweb/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/felipeweb/Code/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3c/3d8vk1ls4gggp0mq77yn19qm0000gn/T/go-build084533671=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.10 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.10
uname -v: Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D102
lldb --version: lldb-902.0.79.2
  Swift-4.1
```

**Comment by rsc** [comment] 2018-04-02 15:51
Duplicate of #23967.

**Closed by rsc** 2018-04-02 15:51 UTC
