### ISSUE TITLE
cmd/go: test with coverage unexpect fail

### ISSUE THREAD

**Issue by forsaken628** [golang/go#43242] opened 2020-12-17 09:58 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/michael/Projects/golang/bin"
GOCACHE="/Users/michael/Library/Caches/go-build"
GOENV="/Users/michael/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/michael/Projects/golang/pkg/mod"
GONOPROXY="git.netisdev.com"
GONOSUMDB="git.netisdev.com"
GOOS="darwin"
GOPATH="/Users/michael/Projects/golang"
GOPRIVATE="git.netisdev.com"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go/1.15.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bd/rnhtmc553vvcm_ty8nt2tv4c0000gn/T/go-build535277532=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

run test at dir like this
<pre>
bar
  bar/bar.go
  bar/bar_test.go
nogo
  nogo/nogo_test.go
</pre>

<pre>
go test ./... -coverpkg=./... -coverprofile=out
</pre>

### What did you expect to see?

test pass

### What did you see instead?

<pre>
go build xxx/foo: no non-test Go files in /xxx/nogo
FAIL    xxx/bar [build failed]
ok      xxx/nogo    0.604s  coverage: [no statements] [no tests to run]
FAIL
</pre>

**Comment by mvdan** [comment] 2020-12-17 10:21
What is in your "bar" directory? Please provide clear steps to reproduce this issue.

**Comment by forsaken628** [comment] 2020-12-17 11:05
empty

bar.go
```
package bar
```

bar_test.go
```
package bar
```

**Comment by mvdan** [comment] 2020-12-17 13:44
Okay, here is a full reproducer:

```
$ cat test.txt
go test -v -coverpkg=./... ./...

-- go.mod --
module test
-- bar/bar.go --
package bar
-- bar/bar_test.go --
package bar
-- nogo/nogo_test.go --
package nogo
$ testscript test.txt

> go test -v -coverpkg=./... ./...
[stdout]
FAIL	test/bar [build failed]
testing: warning: no tests to run
PASS
coverage: [no statements]
ok  	test/nogo	(cached)	coverage: [no statements] [no tests to run]
FAIL

[stderr]
go build test/nogo: no non-test Go files in $WORK/nogo

[exit status 1]
FAIL: /tmp/testscript999122747/0/script.txt:1: unexpected go command failure
error running test.txt in /tmp/testscript999122747/0
```

It seems like a bug to me, since `go test ./...` succeeds. Perhaps @bcmills @jayconrod @matloob can chime in.

Also, please add a test to your patch.

**Comment by jayconrod** [comment] 2020-12-17 15:08
Yep, this is a bug. Duplicate of #27333 though.

There are a number of problems with `-coverpkg`, and I'd hesitate to accept a one-off fix. The approach in [CL 164198](https://go-review.googlesource.com/c/go/+/164198) is a little narrower: that just avoids importing empty packages from the generated test main.

In any case, there needs to be a pretty thorough regression test. @forsaken628 if you're interested in writing that, see src/cmd/go/testdata/script/README.

**Closed by jayconrod** 2020-12-17 15:08 UTC
Labels: NeedsInvestigation, WaitingForInfo
