### ISSUE TITLE
x/tools/gopls: handle import aliases automatically

### ISSUE THREAD

**Issue by muirdm** [golang/go#40278] opened 2020-07-17 18:27 UTC
It is annoying when your file needs to import multiple packages with the same name. Tooling often offers no relief from having to manually import and alias the second package. It would be nice if gopls could help by automatically adding package import aliases when possible and appropriate.

I propose we do something like this to start:
1. When loading packages we keep track of package aliases we see in existing imports. We could store the alias counts by containing package to avoid over counting as a package gets re-type checked.
1. When offering unimported package completions, if a candidate package's name is already used by an existing import in the file, automatically include the "best" alias we have seen elsewhere for that package. We probably want to make the aliased unimported package addressable by both the alias and the package name since the user may or may not anticipate the alias.

**Comment by heschik** [comment] 2020-07-17 18:33
Think this is a dupe of https://golang.org/issue/36077#issuecomment-567741352. Though goimports currently only scans the current package and gopls could do more.

**Closed** 2020-07-17 18:38 UTC
Labels: Tools, gopls
