### ISSUE TITLE
cmd/doc: package overview does not show type parameters

### ISSUE THREAD

**Issue by DeedleFake** [golang/go#49280] opened 2021-11-02 06:40 UTC
I took a look around but didn't see a related issue filed already. This might be a known thing as it's still under active development, but as I don't know I figured I'd post this.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-a97c527ac4 Tue Nov 2 05:43:05 2021 +0000 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="$HOME/.cache/go-build"
GOENV="$HOME/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="$HOME/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="$HOME/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="$HOME/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="$HOME/sdk/gotip/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.18-a97c527ac4 Tue Nov 2 05:43:05 2021 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="$HOME/devel/fixd/lynx/backend/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build894289396=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```bash
$ cd "$(mktemp -d)"
$ go mod init example
$ cat << EOF > example.go
package example

func Example[T any](v T) { println(v) }
EOF
$ go doc
```

### What did you expect to see?

```
package example // import "example"

func Example[T any](v T)
```

### What did you see instead?

```
package example // import "example"

func Example(v T)
```

**Comment by seankhliao** [comment] 2021-11-02 07:12
Duplicate of #49210

**Closed by seankhliao** 2021-11-02 07:12 UTC
