### ISSUE TITLE
cmd/vendor/golang.org/x/arch/arm64/arm64asm: tests fail on tip

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#21486] opened 2017-08-17 01:03 UTC
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

Rebuild the lastest tip with all.bash.

#### What did you expect to see?

Build didn't fail.

#### What did you see instead?

```
ok  	cmd/vendor/github.com/google/pprof/internal/binutils	0.183s
ok  	cmd/vendor/github.com/google/pprof/internal/driver	2.079s
ok  	cmd/vendor/github.com/google/pprof/internal/elfexec	0.015s
ok  	cmd/vendor/github.com/google/pprof/internal/graph	0.020s
ok  	cmd/vendor/github.com/google/pprof/internal/report	0.021s
ok  	cmd/vendor/github.com/google/pprof/internal/symbolizer	0.030s
ok  	cmd/vendor/github.com/google/pprof/internal/symbolz	0.017s
ok  	cmd/vendor/github.com/google/pprof/profile	0.111s
ok  	cmd/vendor/github.com/ianlancetaylor/demangle	0.046s
ok  	cmd/vendor/golang.org/x/arch/arm/armasm	0.034s
2017/08/17 07:37:49 exit status 1
FAIL	cmd/vendor/golang.org/x/arch/arm64/arm64asm	0.635s
ok  	cmd/vendor/golang.org/x/arch/ppc64/ppc64asm	0.020s
ok  	cmd/vendor/golang.org/x/arch/x86/x86asm	0.171s
ok  	cmd/vet	3.696s
ok  	cmd/vet/internal/cfg	0.017s
2017/08/17 07:39:02 Failed: exit status 1

real	5m8.927s
user	11m15.372s
sys	2m52.925s
```

#### Does this issue reproduce with the latest release (go1.8.3)?

N/A

#### System details

```
go version devel +78984d3954 Wed Aug 16 22:22:19 2017 +0000 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yoshiki/gocode:/Users/yoshiki/exercises/gpl:/Users/yoshiki/oak"
GORACE=""
GOROOT="/Users/yoshiki/tools/go"
GOTOOLDIR="/Users/yoshiki/tools/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pb/c7_4_d355ng5zfm4r_jg2gg00000gn/T/go-build681318826=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOROOT/bin/go version: go version devel +78984d3954 Wed Aug 16 22:22:19 2017 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel +78984d3954 Wed Aug 16 22:22:19 2017 +0000
uname -v: Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
lldb --version: lldb-370.0.42
  Swift-3.1
```

**Comment by shurcooL** [comment] 2017-08-17 01:48
According to https://build.golang.org/#short, it looks like [CL 49530](https://golang.org/cl/49530) is the first bad commit. /cc @williamweixiao @cherrymui

**Comment by hirochachacha** [comment] 2017-08-17 01:50
Is this reproducible on other platforms? (not darwin/amd64) I'd like to skip tests.

**Comment by cherrymui** [comment] 2017-08-18 17:48
Reopen. ARM64 failure is still not fixed. A revised CL https://golang.org/cl/56810 should handle it.

**Comment by cherrymui** [comment] 2017-08-24 12:32
Fixed in x/arch subrepo. Reopen for vendoring into main repo.

**Comment by cherrymui** [comment] 2017-08-25 14:42
Fixed in CL https://go-review.googlesource.com/c/go/+/56331.

**Closed by cherrymui** 2017-08-25 14:42 UTC

**Comment by mengzhuo** [comment] 2017-12-27 13:28
@cherrymui it's not working on my vps ( Marvell arm64)
based on git commit 46c5856f6dfcc76e00f753387ea3dc276de2b28e
"net: revert CL 82975"
 
```
ok      cmd/vendor/golang.org/x/arch/arm/armasm 0.059s
--- FAIL: TestObjdumpARM64Testdata (3.13s)
        ext_test.go:195: decode(573093da) = "csinv x23, x2, x19, cc", 4, want "csinv x23, x2, x19, cc // cc = lo, ul, last", 4

        ext_test.go:195: decode(5714291e) = "fccmpe s2, s9, #0x7, ne", 4, want "fccmpe s2, s9, #0x7, ne // ne = any", 4

        ext_test.go:195: decode(46bb5c7a) = "ccmp w26, #0x1c, #0x6, lt", 4, want "ccmp w26, #0x1c, #0x6, lt // lt = tstop", 4

        ext_test.go:195: decode(ec579f9a) = "cset x12, mi", 4, want "cset x12, mi // mi = first", 4

        ext_test.go:195: decode(938591da) = "csneg x19, x12, x17, hi", 4, want "csneg x19, x12, x17, hi // hi = pmore", 4

        ext_test.go:195: decode(ed8f7a1e) = "fcsel d13, d31, d26, hi", 4, want "fcsel d13, d31, d26, hi // hi = pmore", 4

        ext_test.go:195: decode(e048533a) = "ccmn w7, #0x13, #0x0, mi", 4, want "ccmn w7, #0x13, #0x0, mi // mi = first", 4

        ext_test.go:195: decode(c8b56a1e) = "fccmp d14, d10, #0x8, lt", 4, want "fccmp d14, d10, #0x8, lt // lt = tstop", 4

        ext_test.go:195: decode(020a567a) = "ccmp w16, #0x16, #0x2, eq", 4, want "ccmp w16, #0x16, #0x2, eq // eq = none", 4

        ext_test.go:195: decode(a6985afa) = "ccmp x5, #0x1a, #0x6, ls", 4, want "ccmp x5, #0x1a, #0x6, ls // ls = plast", 4

        ext_test.go:195: decode(6a938c5a) = "csinv w10, w27, w12, ls", 4, want "csinv w10, w27, w12, ls // ls = plast", 4

        ext_test.go:195: decode(a64f6d1e) = "fcsel d6, d29, d13, mi", 4, want "fcsel d6, d29, d13, mi // mi = first", 4

        ext_test.go:195: decode(471b53fa) = "ccmp x26, #0x13, #0x7, ne", 4, want "ccmp x26, #0x13, #0x7, ne // ne = any", 4

        ext_test.go:195: decode(c415819a) = "csinc x4, x14, x1, ne", 4, want "csinc x4, x14,x1, ne // ne = any", 4

        ext_test.go:195: decode(ea2a5c7a) = "ccmp w23, #0x1c, #0xa, cs", 4, want "ccmp w23, #0x1c, #0xa, cs // cs = hs, nlast", 4

        ext_test.go:195: decode(91209f1a) = "csel w17, w4, wzr, cs", 4, want "csel w17, w4, wzr, cs // cs = hs, nlast", 4

        ext_test.go:195: decode(e4279f1a) = "cset w4, cc", 4, want "cset w4, cc // cc = lo, ul, last", 4

        ext_test.go:195: decode(2b209eda) = "csinv x11, x1, x30, cs", 4, want "csinv x11, x1, x30, cs // cs = hs, nlast", 4

        ext_test.go:195: decode(7d2d271e) = "fcsel s29, s11, s7, cs", 4, want "fcsel s29, s11, s7, cs // cs = hs, nlast", 4

        ext_test.go:195: decode(3e2e7a1e) = "fcsel d30, d17, d26, cs", 4, want "fcsel d30, d17, d26, cs // cs = hs, nlast", 4```

**Comment by cherrymui** [comment] 2017-12-27 13:51
@mengzhuo this is a different failure, see #23237.

**Comment by williamweixiao** [comment] 2017-12-28 11:12
I have port back patch (https://go-review.googlesource.com/c/go/+/85615) from arch repo to golang repo to fix the issue.
