### ISSUE TITLE
nil literal should not be parsed as ast.Ident

### ISSUE THREAD

**Issue by rhysd** [golang/go#28918] opened 2018-11-22 04:43 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rhysd/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rhysd/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xb/352hz3xn31z9zthlfl2pc03m0000gn/T/go-build927957953=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I found `nil` literal is actually `nil` identifier in Go. So it can be replaced by declaring `nil` in outer scope.

https://play.golang.org/p/itEzumDVEGF

```go
package main

import (
	"fmt"
)

var nil error = fmt.Errorf("hello")

func main() {
	_, err := fmt.Println("hey")
	if err != nil {
		println("oops")
	}
}
```

This seems because `nil` in expression is parsed as identifier, not literal. I guess `true` and `false` has the same issue. `golint` and `go vet` does not complain this.

### What did you expect to see?

I expected not to see `oops` in output

### What did you see instead?

I saw `oops` in output

**Comment by josharian** [comment] 2018-11-22 04:50
nil is a predeclared identifier, not a keyword: https://golang.org/ref/spec#Predeclared_identifiers. This was an intentional decision; I don’t anticipate it changing. Going to close this as working as intended. Feel free to ask to re-open if I’ve misunderstood. If you want to discuss the design, I suggest the golang-nuts mailing list. Thanks for taking the time to file an issue.

**Closed by josharian** 2018-11-22 04:50 UTC

**Comment by rhysd** [comment] 2018-11-22 04:55
Thank you for quick reply. I understood it is an intentional desicion. Let me consider to discuss this in ML.
