### ISSUE TITLE
x/text/cmd/gotext: panic when do extract

### ISSUE THREAD

**Issue by okhowang** [golang/go#62697] opened 2023-09-18 06:02 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/okhowang/.cache/go-build"
GOENV="/home/okhowang/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/okhowang/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/okhowang/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB=""
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.7"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2265391320=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
$ go install golang.org/x/text/cmd/gotext@latest
$ gotext extract
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7b8a56]

goroutine 1 [running]:
main.config()
        /home/okhowang/go/pkg/mod/golang.org/x/text@v0.13.0/cmd/gotext/main.go:55 +0xf6
main.main()
        /home/okhowang/go/pkg/mod/golang.org/x/text@v0.13.0/cmd/gotext/main.go:154 +0x2d3
```

### What did you expect to see?

extract message correctly.

### What did you see instead?

go install golang.org/x/text/cmd/gotext@v0.11.0
it seems like `out` was not init when doing `extract` command

**Comment by mauri870** [comment] 2023-09-18 17:35
The same error happens when calling `gotext rewrite`.

**Comment by mauri870** [comment] 2023-09-18 17:35
@gopherbot add needsFix

**Comment by Succo** [comment] 2024-02-06 20:17
Looks like a duplicate of https://github.com/golang/go/issues/60555

**Comment by mauri870** [comment] 2024-05-09 19:08
> Looks like a duplicate of #60555

I don't think they are the same, this issue is related with parsing the command line flags of gotext.

**Comment by mauri870** [comment] 2024-05-09 19:11
This is still present in gotext as v0.15.0.

cc @mpvl per https://dev.golang.org/owners

**Closed** 2024-05-14 20:26 UTC
Labels: NeedsFix
