### ISSUE TITLE
How to monitor OS for AIX and Solaris machines ? Can you please share the input plugins for telegraf to monitor AIX and Solaris physical OS?

### ISSUE THREAD

**Issue by Priya2705** [golang/go#34110] opened 2019-09-05 13:10 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by ALTree** [comment] 2019-09-05 13:18
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2019-09-05 13:18 UTC
