### ISSUE TITLE
spec: Inconsistent math operations: M1 Mac vs. PC

### ISSUE THREAD

**Issue by librariusbabble** [golang/go#45279] opened 2021-03-29 12:23 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.16rc1 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

MacOS 11.2.3 on an M1 Mac Mini

</pre></details>

### What did you do?

I'm doing an exercise for Exercism.io that involves calculating the [wheat and chessboard problem](https://en.wikipedia.org/wiki/Wheat_and_chessboard_problem).  The issue arises when adding up all the grains of wheat on a whole chessboard.  The code I'm using for doing so is

```return uint64(math.Pow(2, 64) - 1)```

### What did you expect to see?

This should return 18,446,744,073,709,551,615.

### What did you see instead?

My mentor, using an x86-based PC, got 9223372036854775808 instead.  This is the equivalent of 2^63.

**Update**: Apple discusses floating-point to int conversions [here](https://developer.apple.com/documentation/apple-silicon/addressing-architectural-differences-in-your-macos-code), and they apparently function differently on Arm.  See specifically the section "Audit Code that Contains Float-to-Int Conversions" towards the bottom.

**Comment by dr2chase** [comment] 2021-03-29 14:59
@griesemer I think this is a duplicate of #19405.

**Comment by randall77** [comment] 2021-03-29 15:26
Definitely a dup of #29468.
The `-1` in your code doesn't do anything. `2^64-1 == 2^64` in floating point. `2^64` is out of range for conversion, hence implementation-dependent.
Try `math.Nextafter(math.Pow(2, 64), 0)` instead.

**Closed by randall77** 2021-03-29 15:26 UTC

**Comment by librariusbabble** [comment] 2021-03-29 15:58
Thanks for the feedback, and I'm glad to know that I wasn't doing something really dumb :)
