### ISSUE TITLE
proposal: gofmt support ./...

### ISSUE THREAD

**Issue by pjebs** [golang/go#55037] opened 2022-09-13 07:50 UTC
`gofmt -s -w ./...` is **not** supported. `gofmt -s -w .` is supported.

It would be very helpful if it can walk the current directory.

**Comment by mvdan** [comment] 2022-09-13 08:58
Note that the tools are separate on purpose; see https://github.com/golang/go/issues/35258 for example. `gofmt` is able to be a separate tool from `cmd/go` precisely because it does not know what Go packages are - it just finds Go files in directories.

I agree that the situation is somewhat confusing to a newcomer, but making the two commands do the same would be even more confusing. At that point, why do we have two commands at all? :)

**Comment by mvdan** [comment] 2022-09-13 09:07
That said, similar questions keep popping up, so maybe `gofmt -h` and `go help fmt` should summarize the situation.

**Comment by pjebs** [comment] 2022-09-13 09:10
Go fmt doesn't support -s so I can't just switch over.

**Comment by jimen0** [comment] 2022-09-13 09:18
> formatting all encountered go files in subdirectories.

Doesn't `gofmt` already do that?

```console
gitpod /tmp $ mkdir -p a/b/c
gitpod /tmp $ echo 'package main;func main(){ println("hello") }' > a/b/c/code.go
gitpod /tmp $ gofmt -w -s -l .
a/b/c/code.go
```

**Comment by mvdan** [comment] 2022-09-13 09:21
> CMD go fmt doesn't support -s so I can't just switch over.

In that case see https://github.com/golang/go/issues/35258, which was exactly that proposal, and rejected. I don't see the point in talking about it again unless there's any new information.

**Comment by pjebs** [comment] 2022-09-13 12:21
@jimen0 I tried it. It doesn't work on mac:

```
 gofmt -s -w ./...
stat ./...: no such file or directory
```

**Comment by mvdan** [comment] 2022-09-13 12:59
You use `.` rather than `./...`, and it will recurse into subdirectories to find Go files.

**Comment by AAlvarez90** [comment] 2022-09-13 13:21
I think this issue is mostly coming from the potential confusion that some tools use `./...` and others `.`.
For example `go test -bench=. ./...`
As a beginner or somehow we doesn't know all the tools available, how do you know which one use `.` and recurse into subdirs and which one need the `./...` ?
Obviously checking each documentation helps, but what if we could have a standard, something that you just know that it will work without checking any docs?

**Comment by mvdan** [comment] 2022-09-13 13:26
There is a standard - practically every command under `go` takes packages. `gofmt` is separate and does not know what packages are by design. If you have something better in mind, please be precise about what you mean.

I think improving the docs is still a good idea, like I said in an earlier comment. Aside from that, I haven't seen a proposal that isn't a duplicate of https://github.com/golang/go/issues/35258.

**Closed** 2022-09-13 14:24 UTC
Labels: Proposal
