### ISSUE TITLE
template.ParseGlob if pattern we can control and we input Regular Expressions  can attack with  a  Dos 

### ISSUE THREAD

**Issue by cor0ps** [golang/go#46835] opened 2021-06-20 09:21 UTC
### What version of Go are you using (`go version`)?

<pre>
mac os:
➜  ~ go version             
go version go1.16.5 darwin/amd64
linux os:
[root@VM-0-5-centos ~]# go version
go version go1.16 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

go version go1.16.5 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
mac os:
➜  ~ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cor0ps/Library/Caches/go-build"
GOENV="/Users/cor0ps/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/cor0ps/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/cor0ps/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v1/0s4bypvs72gb7z5n9thvs1lw0000gn/T/go-build781412766=/tmp/go-build -gno-record-gcc-switches -fno-common"
linux os:
[root@VM-0-5-centos ~]# go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/cor0ps/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/cor0ps/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1359380393=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

mac os:

```
func main() {
	data := []byte("/*d*/*p")
	_, err := template.ParseGlob(string(data))
	if err != nil {
		fmt.Println(err)
	}

}
```

**notice:**

```
/*d*/*p  in mac os  match  /dev/io8logtemp  
```

linux os:

```
package main

import (
        "fmt"
        "html/template"
)

func main() {

        data := []byte("/dev/*6")

        _, err := template.ParseGlob(string(data))
        if err != nil {
                fmt.Println(err)
        }

}
```

`/dev/*6`   in mac os  match  many 

```
[root@VM-0-5-centos cor0ps]# ls -al /dev/*6
crw--w---- 1 root tty 4,  16 Jun 11 11:57 /dev/tty16
crw--w---- 1 root tty 4,  26 Jun 11 11:57 /dev/tty26
crw--w---- 1 root tty 4,  36 Jun 11 11:57 /dev/tty36
crw--w---- 1 root tty 4,  46 Jun 11 11:57 /dev/tty46
crw--w---- 1 root tty 4,  56 Jun 11 11:57 /dev/tty56
crw--w---- 1 root tty 4,   6 Jun 11 11:57 /dev/tty6
crw-rw---- 1 root tty 7,  16 Jun 20 11:48 /dev/vcs16
crw-rw---- 1 root tty 7,  56 Jun 20 16:59 /dev/vcs56
crw-rw---- 1 root tty 7,   6 Jun 11 11:57 /dev/vcs6
crw-rw---- 1 root tty 7, 144 Jun 20 11:48 /dev/vcsa16
crw-rw---- 1 root tty 7, 184 Jun 20 16:59 /dev/vcsa56
crw-rw---- 1 root tty 7, 134 Jun 11 11:57 /dev/vcsa6
```

### What did you expect to see?

程序死循环读取文件了，一直卡在读取文件了，就会造成dos攻击
Program loop read file, has been stuck in the read file, will cause DoS attack。

maybe  i  think  reasons here:
```
/usr/local/go/src/html/template/template.go ---> readFileOS  --->os.ReadFile have  loop function 
```

### What did you see instead?

maybe  check  user  input file and  return  nil

**Comment by seankhliao** [comment] 2021-06-20 09:59
I believe this is working as intended and there is no reason to artificially limit what `ParseGlob` matches.
With user controlled input they can read any number of sensitive files.
If you need to limit it to a subtree you can limit it with `template.ParseFS(os.DirFS(someDirectory), patterns...)`

Closing as I don't think there's anything to do, please reopen if you disagree

**Closed by seankhliao** 2021-06-20 09:59 UTC

**Comment by cor0ps** [comment] 2021-06-20 10:50
> I believe this is working as intended and there is no reason to artificially limit what `ParseGlob` matches.
> With user controlled input they can read any number of sensitive files.
> If you need to limit it to a subtree you can limit it with `template.ParseFS(os.DirFS(someDirectory), patterns...)`
> 
> Closing as I don't think there's anything to do, please reopen if you disagree

maybe i  disagree  with  you ,ParseGlob can read any number of sensitive files,but  if   they  read  /dev/*  files will be  block  and have a  loop  readfile  also the program  is  hanged on  ,I  think  this ParseGlob function  need check.

**Comment by cor0ps** [comment] 2021-06-21 07:24
> I believe this is working as intended and there is no reason to artificially limit what `ParseGlob` matches.
> With user controlled input they can read any number of sensitive files.
> If you need to limit it to a subtree you can limit it with `template.ParseFS(os.DirFS(someDirectory), patterns...)`
> 
> Closing as I don't think there's anything to do, please reopen if you disagree

https://play.golang.org/p/dArYQMl7el6 Update code on https://play.golang.org/    maybe  you can  read this

**Comment by ianlancetaylor** [comment] 2021-06-21 18:58
I don't see how this is any different than `os.Open("/dev/tty6")`.  But we clearly aren't going to forbid that.
