### ISSUE TITLE
container/list list.Remove after list.Init

### ISSUE THREAD

**Issue by yddeng** [golang/go#50152] opened 2021-12-14 05:44 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yidongdeng/Library/Caches/go-build"
GOENV="/Users/yidongdeng/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/yidongdeng/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/yidongdeng/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/Cellar/go/1.16/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jx/5d4pvvqn1w36sbq9yv6j1q8c0000gq/T/go-build3226135015=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```go
func TestList(t *testing.T) {
	l := list.New()
	t.Logf("len:%d list:%v \n", l.Len(), l)
	e1 := l.PushBack(1)
	t.Logf("len:%d list:%v \n", l.Len(), l)
	l.Init()
	t.Logf("len:%d list:%v \n", l.Len(), l)
	l.Remove(e1)
	t.Logf("len:%d list:%v \n", l.Len(), l)
}
```

```
output
len:0 list:&{{0xc00010ec00 0xc00010ec00 <nil> <nil>} 0}
len:1 list:&{{0xc00010ec90 0xc00010ec90 <nil> <nil>} 1}
len:0 list:&{{0xc00010ec00 0xc00010ec00 <nil> <nil>} 0}
len:-1 list:&{{0xc00010ec00 0xc00010ec00 <nil> <nil>} -1}
```

### What did you expect to see?

list l is initialized, then remove element e1 that is belong to l. l.Len is reduced

### What did you see instead?

```go 
// Init initializes or clears list l.
func (l *List) Init() *List {
	l.root.next = &l.root
	l.root.prev = &l.root
	l.len = 0
	return l
}
```
list is initialized, and the elements  cannot continue to execute or affect the list.

**Comment by seankhliao** [comment] 2021-12-14 11:33
Duplicate of #39014

**Closed by seankhliao** 2021-12-14 11:33 UTC
