### ISSUE TITLE
csv ReadAll - Does not process csv file with "CR" as EOL character (without "LF")

### ISSUE THREAD

**Issue by jumpinjan** [golang/go#12207] opened 2015-08-19 19:18 UTC
I have to work with CSV files that only have a carriage return in them.  The csv package Readall method considers the whole file to be one record because it only checks for "LF" (/n) and has no check for "CR" as well.

CSV files can end with just "CR" per these standards:  http://www.digitalpreservation.gov/formats/fdd/fdd000323.shtml

Thank you!

**Comment by ajstarks** [comment] 2015-08-19 22:19
See: https://github.com/golang/go/issues/7897

**Comment by adg** [comment] 2015-08-20 10:08
Dupe of #7897

**Closed by adg** 2015-08-20 10:08 UTC
