### ISSUE TITLE
x/mobile: gomobile init no longer works due to openal-soft and Go changes

### ISSUE THREAD

**Issue by BenLubar** [golang/go#46943] opened 2021-06-27 01:30 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/ben/go/bin"
GOCACHE="/home/ben/.cache/go-build"
GOENV="/home/ben/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ben/.golang-path/pkg/mod"
GONOPROXY="git.lubar.me/*"
GONOSUMDB="git.lubar.me/*"
GOOS="linux"
GOPATH="/home/ben/.golang-path"
GOPATH="/home/ben/.golang-path"
GOPRIVATE="git.lubar.me/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build979802223=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
git clone -b 1.21.1 https://github.com/kcat/openal-soft.git
gomobile init -openal openal-soft
```

### What did you expect to see?

It builds the shared library.

### What did you see instead?

```
gomobile: go install golang.org/x/mobile/cmd/gobind failed: exit status 1
go install: version is required when current directory is not in a module
        Try 'go install golang.org/x/mobile/cmd/gobind@latest' to install the latest version
```

and if I make a go.mod file to avoid that error:

```
gomobile: /usr/bin/cmake /home/ben/src/utils/openal-soft -DCMAKE_TOOLCHAIN_FILE=/home/ben/src/utils/openal-soft/XCompile-Android.txt -DHOST=armv7a-linux-androideabi16 failed: exit status 1
CMake Error at XCompile-Android.txt:16 (MESSAGE):
  Use the toolchain provided by the Android NDK
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:30 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

**Comment by jakubgs** [comment] 2021-09-13 09:10
I've been dealing with these issues in our Android/iOS library we build using `gomobile`: https://github.com/status-im/status-go/pull/2352

**Comment by Lallassu** [comment] 2021-12-28 04:20
I have the same issue. Pointing out ndk tool chain makes it work. But then I only get 32bit library that is incompatible with my arm64 so file. So I then need to modify the cmake file to build 64bit. Then it works but this feels like something is not up to date as it requires changes to gomobile cmd source.

Anyone else solved this in a better and more generic way?

**Comment by myklosbotond** [comment] 2022-01-12 13:01
I tried changing the install line in [`init.go#L81`](https://cs.opensource.google/go/x/mobile/+/858099ff:cmd/gomobile/init.go;l=81) to add the `@latest` suffix and rebuilding the binary from source. It seems to be working in my Dockerfile, but `gomobile version` refuses to cooperate after that.

```patch
diff --git a/init.go b/init.go
index 172d015..234b1c1 100644
--- a/init.go
+++ b/init.go
@@ -78,7 +78,7 @@ func runInit(cmd *command) error {
 	}()

 	// Make sure gobind is up to date.
-	if err := goInstall([]string{"golang.org/x/mobile/cmd/gobind"}, nil); err != nil {
+	if err := goInstall([]string{"golang.org/x/mobile/cmd/gobind@latest"}, nil); err != nil {
 		return err
 	}
```

I ran `gobind` for android and it finished after that.

`gomobile version` gives me this, though:

```
gomobile version unknown: cannot test gomobile binary: exit status 1, no required module provides package golang.org/x/mobile/cmd/gomobile: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

**Comment by Lallassu** [comment] 2022-01-12 13:08
I managed to build OpenAL etc. It required some changes to `gomobile` itself and the toolchain cmake files for the NDK. I've documented my findings on my project that is fully working using `gomobile` and OpenAL. Not sure if it's the best way forward but it solved the issues for me.

https://github.com/Lallassu/bintris

**Comment by myklosbotond** [comment] 2022-03-02 15:13
As I see it, this issue may be a duplicate of #50994 which was closed, and the `@latest` suffix was merged.

**Comment by hajimehoshi** [comment] 2024-10-16 17:02
Let me close this assuming this is duplicated with #50994.

**Closed** 2024-10-16 17:02 UTC
Labels: FrozenDueToAge, mobile, modules
