### ISSUE TITLE
crypto/x509: corporate proxy: certificate signed by unknown authority

### ISSUE THREAD

**Issue by wrschneider** [golang/go#40370] opened 2020-07-23 12:50 UTC
go version: go1.14.6 darwin/amd64

go env excerpts:
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wschnei2/Library/Caches/go-build"
GOENV="/Users/wschnei2/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/wschnei2/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
```

Attempted to do `go install ./awsproviderlint` and failed with x509 error.
Also got same error with `http.Get("https://www.google.com")`

The problem appears to be how Go handles the certificate chains from my corporate proxy that does re-encryption.

The certificate itself does not include the full chain, only the immediate parent.

Go is picking up the system root certificates, which includes the corporate proxy's root CA cert. 

The problem is there is an intermediate cert between the root CA and cert in the chain:

Root->Intermediate 1->Intermediate 2->server cert

The 'intermediate 1' cert is registered in the MacOS System keychain and browsers have no problem with the same sites.

**Comment by ianlancetaylor** [comment] 2020-07-23 22:19
CC @FiloSottile @katiehockman

**Comment by FiloSottile** [comment] 2020-07-24 00:06
Duplicate of #35631. We're going to try fixing this in Go 1.16, if you need a workaround you can set "intermediate 1" as trusted in the keychain.

**Closed by FiloSottile** 2020-07-24 00:06 UTC
Labels: NeedsInvestigation
