### ISSUE TITLE
x/vgo: vgo overwrites version in go.mod file (e.g. v1 by v1.0.0)

### ISSUE THREAD

**Issue by kuba--** [golang/go#24036] opened 2018-02-22 14:23 UTC
### What version of Go are you using (`go version`)?
go version go1.10 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches -fno-common"
```

### What did you do?
```
$ cat go.mod

module "github.com/kuba--/test"

require "gopkg.in/bufio.v1" v1

$ cat test.go

package main // import "github.com/kuba--/test"

import bufio "gopkg.in/bufio.v1"

func main() {
	_ := bufio.NewBufferString("test")
}

$ vgo build

vgo: finding gopkg.in/bufio.v1 v1.0.0
vgo: gopkg.in/bufio.v1 v1.0.0: unexpected status (https://api.github.com/repos/go-bufio/bufio/git/refs/tags/v1.0.0): 404 Not Found
vgo: finding gopkg.in/bufio.v1 v1.0.0
vgo: gopkg.in/bufio.v1 v1.0.0: unexpected status (https://api.github.com/repos/go-bufio/bufio/git/refs/tags/v1.0.0): 404 Not Found
vgo: unexpected status (https://api.github.com/repos/go-bufio/bufio/git/refs/tags/v1.0.0): 404 Not Found

$ cat go.mod

module "github.com/kuba--/test"

require "gopkg.in/bufio.v1" v1.0.0
```

### What did you expect to see?
`vgo` overwrote version (replaced v1 by v1.0.0) that's why got `404` (https://api.github.com/repos/go-bufio/bufio/git/refs/tags/v1.0.0). Link `https://api.github.com/repos/go-bufio/bufio/git/refs/tags/v1` works fine.

**Comment by zeebo** [comment] 2018-02-22 19:28
See also #24024

**Comment by rsc** [comment] 2018-03-30 19:16
Duplicate of #24476.

**Closed by rsc** 2018-03-30 19:16 UTC
