### ISSUE TITLE
x/playground: stdout and stderr not interleaved with defer

### ISSUE THREAD

**Issue by fuzxxl** [golang/go#10279] opened 2015-03-28 12:59 UTC
Consider the following program:

```
package main

import "fmt"

var z = 1

func main() {

    defer increaseZ(10)
    defer fmt.Println("z =", increaseZ(20), "Deferred Value 1")
     defer fmt.Println("z =", increaseZ(30), "Deferred Value 2")

   fmt.Println("z =", z, "Main Value")
}

func increaseZ(y int) int {
    z += y
    println("z =", z, "Inside Increase Function")
    return z
}
```

On my machine (amd64 Linux), this program prints as expected:

```
z = 21 Inside Increase Function
z = 51 Inside Increase Function
z = 51 Main Value
z = 51 Deferred Value 2
z = 21 Deferred Value 1
z = 61 Inside Increase Function
```

whereas [on Playground](http://play.golang.org/p/6yi3bJ83K2), it prints the following incorrect output:

```
z = 21 Inside Increase Function
z = 51 Inside Increase Function
z = 61 Inside Increase Function
z = 51 Main Value
z = 51 Deferred Value 2
z = 21 Deferred Value 1
```

I have no idea what causes this effect but it seems that the first deferred function call is executed before the final `fmt.Println` call in `main`.

**Comment by bradfitz** [comment] 2015-03-28 13:11
Are you sure this isn't just the result of mixing stderr and stdout differently?

Try it using only one print function.

**Comment by fuzxxl** [comment] 2015-03-28 13:28
Yes, indeed. I'm closing this now. Please mark as “invalid.”

**Comment by fuzxxl** [comment] 2015-03-28 13:33
It's still weird that I cannot reproduce this behaviour without deference. Go seems to obey the order in which I output things in other cases.

**Comment by bradfitz** [comment] 2015-03-29 07:22
Reopening with new title.

I think the playground's hooks for intercepting os.Stdout and os.Stderr don't work for the builtin `println` function, because that writes to stderr directly, without going through the playground's hooks.

These work, using only one style of printing:

http://play.golang.org/p/c0XFpaPnh8 -- with println (stderr)
http://play.golang.org/p/M0y2nixfak -- with fmt.Println (stdout)

This is wrong, or at least confusing:

http://play.golang.org/p/L0ys_wO462

/cc @adg (who's on vacation for ~5 more weeks)

**Comment by ysmolsky** [comment] 2018-03-13 08:20
```
package main

import "fmt"

func main() {
	defer println("D")
	defer fmt.Println("C")
	println("A")
	fmt.Println("B")
}
```
This runs correctly on playground:
```
A
B
C
D
```
Same is valid for the program on the top.

/CC @bradfitz

**Comment by ysmolsky** [comment] 2018-03-13 13:09
After running couple of more attempts to break on playground, I can say that this works as designed. We can close it.

**Comment by andybons** [comment] 2018-03-13 17:10
Closing as
http://play.golang.org/p/c0XFpaPnh8 -- with println (stderr)
http://play.golang.org/p/M0y2nixfak -- with fmt.Println (stdout)

and the mixed version http://play.golang.org/p/L0ys_wO462

all have the same output of
```
A
B
C
D
```

**Closed by andybons** 2018-03-13 17:10 UTC
Labels: NeedsInvestigation

**Comment by ysmolsky** [comment] 2018-03-13 19:57
Thanks @andybons !
