### ISSUE TITLE
internal compiler error: cannot handle alias type declaration (issue #25838)

### ISSUE THREAD

**Issue by JellalLeonhardt** [golang/go#37587] opened 2020-03-01 03:41 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOOS="linux"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build410392367=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

[a short program](https://play.golang.org/p/YouevknkdoH)

run it with `go run main.go`

### What did you expect to see?

output `go`

### What did you see instead?
I got  an error:
```
# command-line-arguments
./main.go:5:6: internal compiler error: cannot handle alias type declaration (issue #25838): ListValue

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
```

**Comment by randall77** [comment] 2020-03-01 03:49
Closing as a duplicate of #25838 .
It might be helpful to see if the workarounds described in that issue work for you and report back (on that issue).

**Closed by randall77** 2020-03-01 03:49 UTC
