### ISSUE TITLE
a better itoa

### ISSUE THREAD

**Issue by liuxingbaoyu** [golang/go#30069] opened 2019-02-03 05:45 UTC
As of now, **strconv.Itoa** is defined as
```
func Itoa(i int) string {
	return FormatInt(int64(i), 10)
}
```
For example, **time.Now().Unix()** must use **strconv.FormatInt(time.Now().Unix(), 10)**
I think that use
```
func Itoa(i int64) string {
	return FormatInt(i, 10)
}
```
will be better

**Comment by mvdan** [comment] 2019-02-03 18:43
If you're going to suggest a breaking change in the standard library, you need to include evidence as to why it's necessary, and why the advantages heavily outweigh the disadvantages. You should probably file a proposal instead; see https://github.com/golang/proposal.

Having said that, I'm not sure I see the point of the issue. Simple functions should use simple types; this is also why `len` returns an `int` instead of an `uint`, even though lengths are never negative. If you want to use `int64` as the parameter type, use `FormatInt`, which is more powerful anyway.

I'm going to close this for now, as the issue is lacking evidence and details. Feel free to open a proposal if you still think this is worth pursuing.

**Closed by mvdan** 2019-02-03 18:43 UTC

**Comment by liuxingbaoyu** [comment] 2019-02-04 05:14
> 由于[Go 1兼容性承诺](https://golang.org/doc/go1compat)，我们无法做到这一点。即使你想为Go2改变它，我也不相信造成的不便是值得的。

It turned out to be like this, thanks

**Comment by liuxingbaoyu** [comment] 2019-02-04 05:17
> 如果您打算在标准库中建议一个重大变化，您需要提供有关为什么必要的证据，以及为什么优势大大超过了缺点。您应该提交提案; 请参阅https://github.com/golang/proposal。
> 
> 话虽如此，我不确定我是否明白了问题的关键。简单函数应该使用简单类型; 这也是为什么`len`返回一个`int`而不是一个`uint`，即使长度永远不会消极。如果要将其`int64`用作参数类型，请使用`FormatInt`，无论如何都要更强大。
> 
> 我现在要关闭这个，因为这个问题缺乏证据和细节。如果您仍然认为值得追求，请随意提出建议。

I just think that the parameter type is int64 is more convenient, because int can be automatically converted to int64, but the opposite is not, but after learning about Go 1 compatibility promise, I understand why

**Comment by dominikh** [comment] 2019-02-04 05:46
> because int can be automatically converted to int64

It can't.

**Comment by liuxingbaoyu** [comment] 2019-02-04 05:52
> > 因为int可以自动转换为int64
> 
> 它不能。

In the latest version of golang should be ok
