### ISSUE TITLE
io: Pipe reader loses last line if writer exits as soon as write is finished

### ISSUE THREAD

**Issue by sunchao9** [golang/go#33297] opened 2019-07-26 10:36 UTC
I think this is a bug of `io.Pipe`, I want to use pipe files to write strings to the detached child process, but I find that the pipe reader always lost the last input line, here is the test case:

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes, go1.12.7 is the latest release version

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/home/git/.local/gobin"
GOCACHE="/home/git/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/git/gopath"
GOPROXY=""
GORACE=""
GOROOT="/etc/alternatives/go"
GOTMPDIR=""
GOTOOLDIR="/etc/alternatives/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build257909325=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

<pre>
$ uname -a
Linux SZX1000480217 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -ir                                                                                                                                                                           0
Distributor ID: CentOS
Release:        7.6.1810
</pre>

### What did you do?

I have a `writer.go` and a `reader.sh`, the `writer.go` writes 100 lines to `reader.sh` which is started as a detached process. And I find that the `reader.sh` always lost the last line unless the `writer.go` sleep a while before exit.

```golang
// writer.go
package main
    
import (
    "fmt"
    "io"
    "os/exec"
)   
    
func main() {
    cmd := exec.Command("./reader.sh")
    
    pr, pw := io.Pipe()
    cmd.Stdin = pr
    
    err := cmd.Start()
    if err != nil {
        fmt.Print(err)
        return
    }
    
    n := 100
    for i := 1; i <= n; i++ {
        str := fmt.Sprintf("line %d\n", i)
        fmt.Print("writer: " + str)
        n, err := pw.Write([]byte(str))
        fmt.Printf("result = %d, %v\n", n, err)
    }
    pw.Close()
}
```

```bash
# reader.sh
while read line     
do                  
    echo "$line" >> ./reader.log
done
```

### What did you expect to see?

I expect to see the `reader.sh` will read all the 100 lines from it's Stdin, because it's Stdin is a pipe reader, and the pipe writer received 100 lines from the parent process.

### What did you see instead?

I run the `writer.go` to check if the `reader.sh` could print all the 100 lines, but the `reader.sh` lost the last line, and I tried lots of times, mostly it happens.

```bash
$ go run writer.go
writer: line 1
...
writer: line 98
writer: line 99
writer: line 100
```

and the `reader.log` 's content is like this:

```
writer: line 1
...
writer: line 98
writer: line 99
```

So, I think there is a BUG under some OS platform (I tried the MacOS, `io.Pipe` works find) , **if the pipe writer exit as soon as possible, the pipe reader will lost the last line**. Please check if it is true, thansk a lot.

**Comment by AlexRouSg** [comment] 2019-07-26 11:01
Try adding the following to the end of the program:
```go
if err := cmd.Wait(); err != nil {
	fmt.Print(err)
}
```

**Comment by sunchao9** [comment] 2019-07-26 11:54
> Try adding the following to the end of the program:
> 
> ```go
> if err := cmd.Wait(); err != nil {
> 	fmt.Print(err)
> }
> ```

If add `cmd.Wait()`， then no lines  is lost. But if I want to create some detached sub processes by `cmd.Start`, this problem will happen.

And I also tries some other ways to avoid this:
- call `time.Sleep(time.Second)` in `writer.go` before exit
- call `pw.Write([]byte{})` in `writer.go` before `pw.Close`

The 2 ways above will stop the pipe reader losting the last line, I don't know why.

**Comment by AlexRouSg** [comment] 2019-07-26 12:08
This got nothing to do with `io.Pipe`, `cmd.Start` does not detach the process. So if the program terminates so does the process. The program simply terminates before the process writes the last line.

If your goal is to have a process monitor the output of another program, it is easier to just make it the parent process.

**Comment by sunchao9** [comment] 2019-07-26 12:25
> `cmd.Start` does not detach the process. So if the program terminates so does the child process. The program simply terminates before the child process writes the last line.
> 

Please try the test case, the parent program do not terminate a long running child process  if it just `os.Exit` after `cmd.Start`.

```golang
// parent.go
package main
    
import (
    "fmt"
    "io"
    "os/exec"
)   
    
func main() {
    cmd := exec.Command("./child")
    
    pr, pw := io.Pipe()
    cmd.Stdin = pr
    
    err := cmd.Start()
    if err != nil {
        fmt.Print(err)
        return
    }
    
    n := 100
    for i := 1; i <= n; i++ {
        str := fmt.Sprintf("line %d\n", i)
        pw.Write([]byte(str))
    }
    pw.Close()
}
```

```golang
// child.go
package main

import (
        "bufio"
        "fmt"
        "os"
        "time"
)

func main() {
        f, _ := os.Create("./child.log")
        scanner := bufio.NewScanner(os.Stdin)
        for scanner.Scan() {
                time.Sleep(time.Second)
                fmt.Fprintln(f, scanner.Text())
        }

        f.Close()
}
```

I try this steps:

```bash
$ go build child.go
$ go run parent.go
$ tail -f child.log
```

and will see the child process is still running, and it's PPID is 1.

```
$ ps -o pid,ppid 65729
   PID   PPID
 65729      1
```

**Comment by AlexRouSg** [comment] 2019-07-26 12:35
> Please try the test case, the parent program do not terminate a long running child process if it just os.Exit after cmd.Start.

Ahh, sorry about that.

**Comment by AlexRouSg** [comment] 2019-07-26 12:56
So I found that if you use https://golang.org/pkg/os/exec/#Cmd.StdinPipe instead of creating your own pipes, the child process gets all 100 lines. Can you verify that works on your end too?

**Comment by sunchao9** [comment] 2019-07-26 13:04
> So I found that if you use https://golang.org/pkg/os/exec/#Cmd.StdinPipe instead of creating your own pipes, the child process gets all 100 lines. Can you verify that works on your end too?

I don't know what is the different between the `cmd.StdinPipe` and the `io.Pipe`'s Reader. But It works, thanks a lot.

**Comment by julieqiu** [comment] 2019-07-29 21:54
@sunchao9 - has @AlexRouSg's suggestion addressed this issue?

**Comment by AlexRouSg** [comment] 2019-07-30 00:34
@julieqiu It's not entirely clear why there is or should there be a difference in behavior. I think at a minimum there should be a doc change if the difference is intentional.

**Comment by sunchao9** [comment] 2019-07-30 01:12
> @sunchao9 - has @AlexRouSg's suggestion addressed this issue?

The suggestion could resolve my problem, thanks a lot. And I also agree with @AlexRouSg said, it would be nice if any one who want to use `io.Pipe` like me find a doc change descripting the difference between `io.Pipe`'s reader and `cmd.StdinPipe`.

**Comment by jayconrod** [comment] 2019-07-30 18:21
@sunchao9 Could you confirm with an strace log that the last `write` system call is not being made? Also please edit the issue to follow the issue template. We don't know what version of Go this is, what platform you're on, or anything else. 

I'd be surprised if there's a bug here, since this functionality is pretty close to the metal, and it's been stable for a long time. There's no error handling in this program, and I suspect at least one of the write calls is returning an error which is being ignored.

**Comment by sunchao9** [comment] 2019-07-31 01:36
> @sunchao9 Could you confirm with an strace log that the last `write` system call is not being made? Also please edit the issue to follow the issue template. We don't know what version of Go this is, what platform you're on, or anything else.
> 
> I'd be surprised if there's a bug here, since this functionality is pretty close to the metal, and it's been stable for a long time. There's no error handling in this program, and I suspect at least one of the write calls is returning an error which is being ignored.

Sorry about that, I have updated the issue using the template.

And I add some trace log to check if the `pw.Write` returns error, like this:

```golang
    n := 100
    for i := 1; i <= n; i++ {
        str := fmt.Sprintf("line %d\n", i)
        fmt.Print("writer: " + str)
        n, err := pw.Write([]byte(str))
        fmt.Printf("result = %d, %v\n", n, err)
    }
    pw.Close()
```

and the returns just fine, there is no error happened, but the `reader.sh` always lost the 100th line. But I also tried this morning under MacOS, it does not happen.

**Comment by jayconrod** [comment] 2019-07-31 15:32
@sunchao9 Thanks for adding that info.

I looked into this a little closer, and I think I understand what's going wrong. If you look at the documentation for [io.Pipe](https://godoc.org/io#Pipe), it's an in-memory pipe which basically passes byte slices from a writer to a reader on a channel. It's not a pipe in the UNIX sense; that's [os.Pipe](https://godoc.org/os#Pipe), which returns [*os.File](https://godoc.org/os#File).

The documentation for [os/exec.Cmd](https://godoc.org/os/exec#Cmd) explains the difference in behavior.

```
    // Stdin specifies the process's standard input.
    //
    // If Stdin is nil, the process reads from the null device (os.DevNull).
    //
    // If Stdin is an *os.File, the process's standard input is connected
    // directly to that file.
    //
    // Otherwise, during the execution of the command a separate
    // goroutine reads from Stdin and delivers that data to the command
    // over a pipe. In this case, Wait does not complete until the goroutine
    // stops copying, either because it has reached the end of Stdin
    // (EOF or a read error) or because writing to the pipe returned an error.
```

Because `Stdin` is not an `*os.File`, there is a goroutine that polls `Stdin` and then writes to an actual `*os.File`. The main goroutine races with this goroutine and exits before it has a chance to copy the last message. You must call [os/exec.Cmd.Wait](https://godoc.org/os/exec#Cmd.Wait) to ensure that goroutine is finished. Alternatively, use [os.Pipe](https://godoc.org/os#Pipe) so you have direct access to the pipe. [os/exec.Cmd.StdinPipe](https://godoc.org/os/exec#Cmd.StdinPipe) is a convenient way to do this.

Closing because this is working as designed. Process synchronization is always a little tricky, but there are some useful examples in the `os/exec` package.

**Closed by jayconrod** 2019-07-31 15:32 UTC
Labels: WaitingForInfo
