### ISSUE TITLE
database/sql/driver: TestTxStmtDeadlock very flaky on android-amd64-emu

### ISSUE THREAD

**Issue by mdempsky** [golang/go#46916] opened 2021-06-24 23:05 UTC
This test has been failing a lot for me over the past 4 days on the dev.typeparams branch:

https://storage.googleapis.com/go-build-log/04734dd8/android-amd64-emu_91b417d9.log
https://storage.googleapis.com/go-build-log/2d5720ec/android-amd64-emu_3daa9f0e.log
https://storage.googleapis.com/go-build-log/4eda6e8b/android-amd64-emu_98d25c3d.log
https://storage.googleapis.com/go-build-log/638413de/android-amd64-emu_9ecd75ba.log
https://storage.googleapis.com/go-build-log/7f1c4853/android-amd64-emu_9b30e641.log
https://storage.googleapis.com/go-build-log/970e4e58/android-amd64-emu_0d432260.log
https://storage.googleapis.com/go-build-log/bd75df28/android-amd64-emu_e258f125.log
https://storage.googleapis.com/go-build-log/dcbc3557/android-amd64-emu_e7b625fe.log
https://storage.googleapis.com/go-build-log/f696ac32/android-amd64-emu_f04fc144.log

These failures account for the majority of my unsuccessful trybot runs recently.

/cc @bcmills @kardianos

**Comment by cuonglm** [comment] 2021-06-25 03:16
I can reproduce it locally on Macbook M1:

```
$ go test -race -count=100 -run=TestTxStmtDeadlock
--- FAIL: TestTxStmtDeadlock (0.00s)
    sql_test.go:2851: sql: transaction has already been committed or rolled back
--- FAIL: TestTxStmtDeadlock (0.00s)
    sql_test.go:154: Error closing fakeConn: fakedb: can't close; dangling statement(s)
    sql_test.go:172: error closing DB: fakedb: can't close; dangling statement(s)
FAIL
exit status 1
FAIL	database/sql	0.934s
```

The fix in https://github.com/golang/go/commit/b73cc4b02b3801603b3ce0bcc57cf01d6aa9a4dd seems make the `cancel()` call too early, moving the call after `tx.Prepare` will fix the problem.

**Comment by cuonglm** [comment] 2021-06-25 03:37
@mdempsky oh, it's fixed in https://github.com/golang/go/commit/44f9a3566ce564f9a21b1b92940a520ea241e065, seems we just need to merge master to dev.typeparams

**Comment by mdempsky** [comment] 2021-06-25 04:06
@cuonglm Oh nice, thanks for tracking that down. Do you want to send a merge CL? I'm available to review/approve.

**Comment by cuonglm** [comment] 2021-06-25 04:08
> @cuonglm Oh nice, thanks for tracking that down. Do you want to send a merge CL? I'm available to review/approve.

I'm on it, need to resolving conflicts in internal/buildcfg/exp.go

**Comment by bcmills** [comment] 2021-06-25 17:11
Duplicate of #46852

**Comment by cuonglm** [comment] 2021-06-28 08:22
> @cuonglm Oh nice, thanks for tracking that down. Do you want to send a merge CL? I'm available to review/approve.

https://go-review.googlesource.com/c/go/+/330829 was merged, we can now close this issue.

**Closed by cuonglm** 2021-06-28 08:22 UTC
Labels: NeedsInvestigation, Soon
