### ISSUE TITLE
x/build,cmd/compile: frequent "signal killed" building cmd/compile/internal/ssa on android-arm-corellium builder since 2021-12-07

### ISSUE THREAD

**Issue by bcmills** [golang/go#50084] opened 2021-12-09 23:00 UTC
`greplogs --dashboard -md -l -e '(?ms)\Aandroid-arm.*/compile: signal: killed'`

[2021-12-08T18:06:06-7b7efd7/android-arm-corellium](https://build.golang.org/log/3c9df7b0fcbbe96006aa90ec45bcd90c79d4f674)
[2021-12-08T17:04:27-c759ec2/android-arm-corellium](https://build.golang.org/log/d92ce7c608540b8bbe2623a0f80f44401835a721)
[2021-12-07T21:54:30-cf1ec17/android-arm-corellium](https://build.golang.org/log/d2dd7849ad2d888e8a51170e9aa7eead8e7ac057)
[2021-12-07T17:46:04-4c943ab/android-arm-corellium](https://build.golang.org/log/6407490ba9e0a654da2ec1500b690b08b6f2c99a)
<strong>(Note 2-year gap!)</strong>
[2019-11-14T00:58:33-e77106c/android-arm64-corellium](https://build.golang.org/log/0581282c28d9d9b04cd028a5d0309751b833e097)
[2019-11-13T20:53:39-49e05d4/android-arm64-corellium](https://build.golang.org/log/83b897e861dc63d371eb4a57546a067f139b9f78)
[2019-11-13T19:15:27-7ad2748/android-arm64-corellium](https://build.golang.org/log/3d6f332955e6d74168331807460a00f78f325329)
[2019-06-18T20:32:15-2ba9f7c/android-arm-corellium](https://build.golang.org/log/e46af0980030ae07d0987f71b89df7ad22f9ea94)

**Comment by bcmills** [comment] 2021-12-09 23:02
Release-blocker via #11811 (CC @golang/release).

@changkun and/or @steeve: could you investigate the source of these failures?

**Comment by changkun** [comment] 2021-12-10 02:40
Just a first impression: I haven't touched any android builders yet but only iOS builders, and probably @steeve didn't too for years. If the failures occur later in the past three days, they may likely be caused by newly landed commits.

**Comment by aclements** [comment] 2022-01-04 18:41
Happened a few more times and then stopped:

[2021-12-13T22:45:26-5b9207f/android-arm64-corellium](https://build.golang.org/log/7979d094479b4eec1a23e630400dc3530b8da9ce) (This one got past bootstrap and then failed during test builds)
[2021-12-13T18:41:35-083ef54/android-arm-corellium](https://build.golang.org/log/9cc7a1a00d37fea091a016ede009f4b46eaaf8ac)
[2021-12-13T16:44:13-acc65b4/android-arm-corellium](https://build.golang.org/log/a08a04b83826c6cf28b0be974f2dbeddc40d0079)
[2021-12-13T16:42:31-4b3d8d1/android-arm-corellium](https://build.golang.org/log/177e2945e5fa9f2e4d3cf38dc0ea250d104fac57)

**Comment by aclements** [comment] 2022-01-04 18:42
It seems possible that the cmd/compile/internal/ssa package just got big enough that the build is now getting OOM-killed. The next step here may be to reproduce and look at the syslog.

**Comment by bcmills** [comment] 2022-01-19 15:24
Two more, also building `cmd/compile/internal/ssa`:

`greplogs --dashboard -md -l -e '(?ms)\Aandroid-arm.*/compile: signal: killed' --since=2022-01-04`

[2022-01-18T23:59:40-50869f3/android-arm-corellium](https://build.golang.org/log/f4650a5c4400185cb70e52dfc40f29639605be65)
[2022-01-18T21:43:02-cf5d73e/android-arm-corellium](https://build.golang.org/log/ffe9e8d981e7882120827036e4aafd8d12ff6dc3)

**Comment by ianlancetaylor** [comment] 2022-01-28 01:00
cmd/compile/internal/ssa is the largest and slowest package.  This has to be the OOM killer.

[2022-01-20T01:03:13-e7d5857/android-arm-corellium](https://build.golang.org/log/ae2f35c59f61bd4277f94c5abef96181041a0466)
[2022-01-19T21:46:55-bb7fb8a/android-arm-corellium](https://build.golang.org/log/9761a3d25674d042cf456f36dfdb11581ee1be43)
[2022-01-19T21:14:18-c1296af/android-arm64-corellium](https://build.golang.org/log/67940114d5a4cf643d13b562b9691c99cdbb7c22)
[2022-01-19T20:54:49-1efc581/android-arm-corellium](https://build.golang.org/log/36460a120bc0b6b788e6fe463fcd9622c48ab0a7)
[2022-01-19T16:33:05-3e45eb3/android-arm-corellium](https://build.golang.org/log/b8b6f4d1e6dbbe4bc54910f6bb2eab49220327b1)
[2022-01-19T16:23:21-bec2cc3/android-arm-corellium](https://build.golang.org/log/43160938165941cea6e7d07d517c83ad7ad18b8a)
[2022-01-19T15:34:05-ca33b34/android-arm-corellium](https://build.golang.org/log/f55382ab88f54cdd4186fae2fc70c235a4210a02)

**Closed** 2022-01-28 04:13 UTC
Labels: Builders, OS-Android, NeedsInvestigation, release-blocker, mobile

**Comment by changkun** [comment] 2022-01-28 07:42
I hope we would revert the change. I've been contacting Corellium lately since before Christmas. There are multiple issues (including this) to their environment that needs to be fixed at least from what I have experienced:

1. The devices may be automatically turned off for an unknown reason (their response is under investigation)
2. The devices may be automatically being wiped out for an unknown reason (same response)
3. The VPN connection may not be established due to cert error

The impression is their environment monitor may trigger certain action (when OOM), then the entire device pool will be rescheduled or removed from running status, which causes frequent device missing from the farmer when there is no action being made from the human side.

**Comment by ianlancetaylor** [comment] 2022-01-28 21:44
@changkun Sorry, which change do you think we should revert?

**Comment by changkun** [comment] 2022-02-01 16:37
> @changkun Sorry, which change do you think we should revert?

Not sure what else I could refer to? It looks like there is only one change related to this thread. I was telling a story that the problem could be on the Corellium side based on the recent experience to maintain them. Hence we may not need to set GOMAXPROCS=1 as long as they confirmed and fixed it.

**Comment by aclements** [comment] 2022-02-01 18:18
We'd be happy to be able to revert and run with more parallelism, but at least to me it's not clear how this is related to the Corellium issues you mentioned. From the build logs, this is not a device disappearing or a VPN issue. The compiler is getting a signal and that's successfully being reported up through all.bash and terminating the build. Maybe I'm not understanding what you're saying?

**Comment by ianlancetaylor** [comment] 2022-02-01 18:42
@changkun I'm sorry for being slow to understand.  When I ask a specific question like "what change do you think we should revert" it really helps me a lot if you can simply provide a CL number or a git revision or something.  Please feel free to also explain why it is a stupid question, but please also answer the question.  Many thanks.

I'm going to guess that you mean https://go.dev/cl/381514?  I don't know if that change is helping but I don't understand why reverting it would help either.

My apologies if I'm missing the point.
