### ISSUE TITLE
x/tools/cmd/gopls, maybe gopls should not lint error when same method occurs in different files which adapt different platform

### ISSUE THREAD

**Issue by hujianxin** [golang/go#31653] opened 2019-04-24 11:45 UTC
![image](https://user-images.githubusercontent.com/9526904/56656979-75a94d00-66c9-11e9-91c1-0ba64c3c1694.png)
Like this

**Comment by stamblerre** [comment] 2019-04-24 16:53
Duplicate of #29202.

**Closed by stamblerre** 2019-04-24 16:53 UTC
