### ISSUE TITLE
cmd/go2go: chan X(T) does not parse

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#39670] opened 2020-06-17 22:37 UTC
This initializer for `c1` does not parse, and I'm not sure why.  The initialize for `c2` does work.

```Go
package main

type X(type T) T

var c1 = make(chan X(int))
var c2 = make(chan (X(int)))
```

I get

```
type checking failed for main
foo.go2:5:20: cannot use generic type X(type T) without instantiation
```

**Comment by griesemer** [comment] 2020-06-17 23:08
Note that `chan x(y)` is a [legal type conversion](https://play.golang.org/p/V4IkaXevq8K) `(chan x)(y)`. Even though we are expecting a type here, for the parser `make(chan X(int))` looks like an ordinary function call (it doesn't know anything about `make` being special) and so it expects a (non-type) expression as argument. By that logic, that expression must be a conversion. Hence you need the extra parentheses. If the parser knew to expect a type, the parentheses wouldn't be needed.

I suppose the type-checker could re-associate the expression once it knows we're dealing with the built-in `make` call, but that seems a bit iffy (to me).

Closing as working as intended.

**Closed by griesemer** 2020-06-17 23:08 UTC
Labels: NeedsInvestigation
