### ISSUE TITLE
cmd/compile: get an internal error when deliberately use '%' operator with int and complex

### ISSUE THREAD

**Issue by Sasasu** [golang/go#31110] opened 2019-03-28 13:28 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
> go version go1.12.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
> on goplayground
</pre></details>

### What did you do?
`1i % 1` or `1 % 1i`

https://play.golang.org/p/SOnbQYQweey

### What did you expect to see?
compiler print "use remainder operator between integer and complex value" and exit

or

compiler print "constant %g truncated to real" and exit

### What did you see instead?
internal error

**Comment by josharian** [comment] 2019-03-28 14:24
cc @mdempsky

**Comment by mdempsky** [comment] 2019-03-28 17:48
Duplicate of #31060.

**Closed by mdempsky** 2019-03-28 17:48 UTC
