### ISSUE TITLE
spec: incorrect  initialization order 

### ISSUE THREAD

**Issue by bigwhite** [golang/go#12369] opened 2015-08-27 22:29 UTC
version: go version go1.5 darwin/amd64

There is an example about variable initialization order in the go specs:

```
var (
	a = c + b
	b = f()
	c = f()
	d = 3
)

func f() int {
	d++
	return d
}

```
the spec gives the initialization order is d, b, c, a. but the result of above example is not the same as the order spec gives.

```
package main

import "fmt"

var (
    a = c + b
    b = f()
    c = f()
    d = 3
)

func f() int {
    d++
    return d
}

func main() {
    fmt.Println(a, b, c, d)
}
```
$go run example.go
9 5 4 5

according to the result, the actual init order should be d ,c ,b, a, not the same as the order in spec.

**Comment by ianlancetaylor** [comment] 2015-08-27 22:44
Same as #9094 ?

**Comment by bigwhite** [comment] 2015-08-27 23:14
@ianlancetaylor  Yes, the issue is as same as #9094。I have not found the issue 9094 before.

**Comment by mdempsky** [comment] 2015-08-27 23:15
Closing as duplicate then.

**Closed by mdempsky** 2015-08-27 23:15 UTC

**Comment by griesemer** [comment] 2015-08-27 23:17
Duplicate of #9094.
