### ISSUE TITLE
cmd/go: modules don't support url encoded spaces

### ISSUE THREAD

**Issue by damienfamed75** [golang/go#45930] opened 2021-05-03 18:05 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Go modules do not support the `%` symbol to be used in the import URL. This can appear when companies use spaces in their project names in Azure DevOps or some other git providers.

Yes, I know it's silly to have a space character, but it does happen and can make `%20` in the URL unavoidable without making a new project and sometimes that's not possible.

This is already a pre-existing issue #45549

### What did you expect to see?

I expected the module name to work.

### What did you see instead?

`malformed import path "dev.azure.com/abc/abc%20def/_git/repo-name" invalid character '%'`

### What could be done

Having `%` symbols can be quite ugly in an import in the first place. Perhaps an exception can be made for the `%20` character and can be automatically aliased as a space character when using it in the code itself.

For instance if I have `dev.azure.com/abc/abc%20def/_git/repo-name` and I import it I could put:
```import "dev.azure.com/abc/abc def/_git/repo-name"```

Either way I think it's important for modules to support `%20`

**Comment by seankhliao** [comment] 2021-05-03 18:08
Duplicate of #41540

**Closed by seankhliao** 2021-05-03 18:08 UTC
