### ISSUE TITLE
x/website: golang.org responsive menu bug

### ISSUE THREAD

**Issue by Matt-Yeldalo** [golang/go#48381] opened 2021-09-14 14:27 UTC
### What did you do?
golang.org home page, attempt to open responsive menu.
It works fine when I add the is-active class to the header, so I suspect it's the JS code. In the JS code, the click event for the headerMenuButton relies on the path.indexOf("/doc/") to be true, the home page will never satisfy this condition. The click event is never added.

### What did you expect to see?
The responsive menu.

### What did you see instead?
Nothing.

**Comment by seankhliao** [comment] 2021-09-14 14:53
Duplicate of #47862

**Closed by seankhliao** 2021-09-14 14:53 UTC
