### ISSUE TITLE
cmd/go: no "module requires Go 1.nn" warning when a package is not found

### ISSUE THREAD

**Issue by bradfitz** [golang/go#51778] opened 2022-03-18 04:28 UTC
Tested with both Go 1.17.x and Go 1.18(.0)...

If you have a module with a `go 1.n` directive and try to build with older Go, you get a nice error message ("note: module requires Go 1.18") from `cmd/compile` when the build fails. This is good:

```
$ cat go.mod; echo --; cat *.go
module new-symbol

go 1.18
--
package main

import "unicode/utf8"

func main() {
        _ = utf8.AppendRune
}
$ go version
go version go1.18 linux/amd64
$ go run .
$ ~/sdk/go1.17/bin/go run .
# new-symbol
./new-symbol.go:6:6: undefined: utf8.AppendRune
note: module requires Go 1.18
```

But if the the project is using a new package (say, `net/netip` in a `go 1.18` module) and then a Go 1.17 user tries to build:

```
$ cat go.mod; echo --; cat *.go
module new-pkg

go 1.18
--
package main

import _ "net/netip"

func main() {
}
pkg$ go version
go version go1.18 linux/amd64
$ go run .
$ ~/sdk/go1.17/bin/go run .
new-pkg.go:3:8: package net/netip is not in GOROOT (/home/bradfitz/sdk/go1.17/src/net/netip)
```

... they don't get the nice "note: module requires Go 1.18" hint.

Instead they just think you broke the build and file bug reports against you, even though your `go.mod` says 1.18.

I verified that this bug is still present in 1.18(.0) too:

```
$ cat go.mod; echo --; cat *.go
module new-pkg

go 1.19
--
package main

import _ "some/future"

func main() {
}
$ go version
go version go1.18 linux/amd64
$ go run .
new-pkg.go:3:8: package some/future is not in GOROOT (/home/bradfitz/sdk/go1.18/src/some/future)
```

Filed on request of @ianlancetaylor who realized that it was `cmd/go` that's missing the error.

/cc @bcmills @matloob @nickoneill @josharian

**Comment by bcmills** [comment] 2022-04-05 19:38
Duplicate of #48966

**Closed by bcmills** 2022-04-05 19:38 UTC
Labels: NeedsInvestigation, modules
