### ISSUE TITLE
net: Interface.Flags always 0 on Windows 8

### ISSUE THREAD

**Issue by ffoebel** [golang/go#10530] opened 2015-04-22 08:39 UTC
Go version: 1.4

The following code works on Windows 7:
```go
package main
import "fmt"
import "net"
func main() {
    ifs, _ := net.Interfaces()
    for _, i := range ifs {
        fmt.Println(i.Flags)
    }
}
```
Tried both "run as administrator" and "compatibility mode" to see whether this was a side effect but never saw any flags when running on Windows 8.

**Comment by mattn** [comment] 2015-04-22 08:44
it is fixed in 2015/02/10.
https://go-review.googlesource.com/#/c/3024/

**Comment by mikioh** [comment] 2015-04-22 08:48
Duplicate of #5395.

**Closed by mikioh** 2015-04-22 08:48 UTC

**Comment by oliveagle** [comment] 2015-07-08 08:49
same here.  on windows 2012 R2
go 1.4.2

**Comment by mattn** [comment] 2015-07-08 09:32
The fixes is applied to the tip on repo. So go1.4.2 doesn't have the fix.
