### ISSUE TITLE
cmd/compile: corrupted value

### ISSUE THREAD

**Issue by cznic** [golang/go#20530] opened 2017-05-30 15:51 UTC
### What version of Go are you using (`go version`)?

`go version go1.8.3 linux/amd64`

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jnml"
GORACE=""
GOROOT="/home/jnml/go"
GOTOOLDIR="/home/jnml/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build797922225=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?

```
$ cat bug.go 
package main

var a uint8

func main() {
	b := int8(func() int32 { return -1 }())
	a = uint8(b)
	//println(a)
	if int32(a) != 255 {
		println("got", a, "expected 255")
	}
}
$ go run bug.go
got 255 expected 255
$ 
```
[Playground](https://play.golang.org/p/BMENP1qTaR)

### What did you expect to see?

Nothing

### What did you see instead?

`got 255 expected 255`

### Additional info ###

- Uncommenting line 8 (`//println(a)`) "[fixes](https://play.golang.org/p/t63QdtRdoa)" the problem.

**Comment by mundaym** [comment] 2017-05-30 18:48
I think the problem is these rules:

```
// replace load from same location as preceding store with copy
(MOVBload [off] {sym} ptr (MOVBstore [off2] {sym2} ptr2 x _)) && sym == sym2 && off == off2 && isSamePtr(ptr, ptr2) -> x
(MOVWload [off] {sym} ptr (MOVWstore [off2] {sym2} ptr2 x _)) && sym == sym2 && off == off2 && isSamePtr(ptr, ptr2) -> x
(MOVLload [off] {sym} ptr (MOVLstore [off2] {sym2} ptr2 x _)) && sym == sym2 && off == off2 && isSamePtr(ptr, ptr2) -> x
(MOVQload [off] {sym} ptr (MOVQstore [off2] {sym2} ptr2 x _)) && sym == sym2 && off == off2 && isSamePtr(ptr, ptr2) -> x
```

The MOVBQZX is merged into the MOVBload, which is then replaced with a copy.

(s390x had the same problem which was fixed in 094992e2 ([CL 37154](https://go-review.googlesource.com/#/c/37154/)). That CL hasn't been backported to 1.8.x.)

**Comment by randall77** [comment] 2017-05-30 20:16
This bug exists in 1.7 and 1.8, but not 1.6.
Technically not a 1.8 regression because 1.7 also has the bug.  But nevertheless I'm going to mark for a possible 1.8.4.

**Comment by dr2chase** [comment] 2017-05-30 20:19
And also x86:
```
// replace load from same location as preceding store with copy
(MOVBload [off] {sym} ptr (MOVBstore [off2] {sym2} ptr2 x _)) && sym == sym2 && off == off2 && isSamePtr(ptr, ptr2) -> x
(MOVWload [off] {sym} ptr (MOVWstore [off2] {sym2} ptr2 x _)) && sym == sym2 && off == off2 && isSamePtr(ptr, ptr2) -> x
(MOVLload [off] {sym} ptr (MOVLstore [off2] {sym2} ptr2 x _)) && sym == sym2 && off == off2 && isSamePtr(ptr, ptr2) -> x
```
and ARM:
```
(MOVBload [off] {sym} ptr (MOVBstore [off2] {sym2} ptr2 x _)) && sym == sym2 && off == off2 && isSamePtr(ptr, ptr2) && isSigned(x.Type) -> x
(MOVBUload [off] {sym} ptr (MOVBstore [off2] {sym2} ptr2 x _)) && sym == sym2 && off == off2 && isSamePtr(ptr, ptr2) && !isSigned(x.Type) -> x
(MOVHload [off] {sym} ptr (MOVHstore [off2] {sym2} ptr2 x _)) && sym == sym2 && off == off2 && isSamePtr(ptr, ptr2) && isSigned(x.Type) -> x
(MOVHUload [off] {sym} ptr (MOVHstore [off2] {sym2} ptr2 x _)) && sym == sym2 && off == off2 && isSamePtr(ptr, ptr2) && !isSigned(x.Type) -> x
```

So I'd predict some likely failures in the trybots with my shiny new test. :-)

**Comment by dr2chase** [comment] 2017-05-30 20:47
PPC64 lacks the pattern and the bug also does not reproduce there.
It looks like it ought to fail on ARM but I might need to tweak the test just a bit.

**Comment by josharian** [comment] 2017-05-30 22:09
Reopening for 1.8.4.

**Comment by cherrymui** [comment] 2017-05-31 12:26
A slight variation of the test case can trigger the failure on ARM. The CL fixed it.

```
package main

var a uint8

func main() {
        b := int8(func() uint32 { return 0xffffffff }())
        a = uint8(b)
        if int32(a) != 255 {
                // Failing case prints 'got 255 expected 255'
                println("got", a, "expected 255")
        }
}
```

It also fails on MIPS. CL coming.

**Comment by dr2chase** [comment] 2017-05-31 16:05
What's the 1.8.4 process after reopening?

**Comment by randall77** [comment] 2017-05-31 16:19
Just leave it for now.  When we get to doing a 1.8.4 release, all the CLs attached to 1.8.4 marked bugs will be backported to the release branch.

**Comment by cherrymui** [comment] 2017-09-19 21:14
This is kept open for Go 1.8.4, if there is one.

**Comment by rsc** [comment] 2017-10-13 20:09
CL 37154 OK for Go 1.8.5.
CL 44355 OK for Go 1.8.5.
CL 44430 OK for Go 1.8.5.

**Comment by rsc** [comment] 2017-10-26 21:07
go1.8.5 has been packaged and includes:

  - [CL 37154](https://golang.org/cl/37154) 
  - [CL 44430](https://golang.org/cl/44430) 
  - [CL 70841](https://golang.org/cl/70841) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:07:48 UTC

**Closed by rsc** 2017-10-26 21:07 UTC
Labels: cherry-pick-approved
