### ISSUE TITLE
Install go1.4 on Powerlinux7 ,have errros: `go tool dist: unknown architecture: ppc64`

### ISSUE THREAD

**Issue by goen88** [golang/go#27725] opened 2018-09-18 10:44 UTC
I wanna install go1.4 on Powerlinux7r1 and install errors like "go tool dist: unknown architecture: ppc64"

OS version info 
`
Linux 2.6.32-504.el6.ppc64 #1 SMP Tue Sep 16 01:52:45 EDT 2014 ppc64 ppc64 ppc64 GNU/Linux

LSB Version:	:base-4.0-noarch:base-4.0-ppc64:core-4.0-noarch:core-4.0-ppc64:graphics-4.0-noarch:graphics-4.0-ppc64:printing-4.0-noarch:printing-4.0-ppc64
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.6 (Santiago)
Release:	6.6
Codename:	Santiago
`
I need help , thanks very much

**Comment by agnivade** [comment] 2018-09-18 11:59
Sorry, but you are using 1.4. ppc64 is available from 1.5 onwards. Is there a reason you cannot use 1.11 ?

**Comment by laboger** [comment] 2018-09-18 20:18
If you want to run on power7 you have to use go 1.8 or earlier, but as
noted above, support for ppc64 was not added until go 1.5.

**Comment by goen88** [comment] 2018-09-19 03:49
> Sorry, but you are using 1.4. ppc64 is available from 1.5 onwards. Is there a reason you cannot use 1.11 ?

Thank for you answer !  At first, I wanna install 1.9.2 , give errors below where I install it. And  I try install 1.11 the same errors give
`
ERROR: Cannot find /root/go1.4/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
`
So, I install 1.4 for support 1.9 or 1.11 , but failed .
Could  you tell me what to do next?

**Comment by agnivade** [comment] 2018-09-19 04:12
You don't need to compile the Go source. Just download a release. From the release page, it seems that only releases for ppc64le is available. Then, I would suggest you build the ppc64 Go binaries from a normal amd64 machine and then use those in your target machine.

For further questions, please have a look at [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.

Closing since this is not a bug.

**Closed by agnivade** 2018-09-19 04:12 UTC

**Comment by goen88** [comment] 2018-09-19 04:17
> You don't need to compile the Go source. Just download a release. From the release page, it seems that only releases for ppc64le is available. Then, I would suggest you build the ppc64 Go binaries from a normal amd64 machine and then use those in your target machine.
> 
> For further questions, please have a look at [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.
> 
> Closing since this is not a bug.

Ok, Thanks for you suggest
