### ISSUE TITLE
wasm: http.Get is panicking if used in function

### ISSUE THREAD

**Issue by sebbalex** [golang/go#44612] opened 2021-02-25 15:01 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Fedora 33 x86_64
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sebbalex/.cache/go-build"
GOENV="/home/sebbalex/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/sebbalex/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/sebbalex/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/sebbalex/sdk/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/sebbalex/sdk/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3094439333=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I'm trying to make a simple http get using wasm and I noticed that program behave differently if I call the http.Get inside a function or in main() context.

I attach a complete [gist here](https://gist.github.com/sebbalex/5f9d657a19aeb0e6a433a318f7237455)

### What did you expect to see?
same result in main and function as well

### What did you see instead?
panic.

**Comment by finnbear** [comment] 2021-02-25 16:19
It is counterintuitive but, from the [documentation of `FuncOf`](https://pkg.go.dev/syscall/js#FuncOf):
> Invoking the wrapped Go function from JavaScript will pause the event loop and spawn a new goroutine. Other wrapped functions which are triggered during a call from Go to JavaScript get executed on the same goroutine.

> As a consequence, if one wrapped function blocks, JavaScript's event loop is blocked until that function returns. Hence, calling any async JavaScript API, which requires the event loop, like fetch (http.Client), will cause an immediate deadlock. **Therefore a blocking function should explicitly start a new goroutine.**

**Comment by sebbalex** [comment] 2021-02-25 16:59
yeah @finnbear it's working! thanks for pointing it out! and, yes, it is counterintuitive,
I also found the[ official documentation ](https://github.com/golang/go/wiki/WebAssembly)poorly cared for..

**Comment by sebbalex** [comment] 2021-02-25 17:06
sorry, I tried your suggestion without testing the returning stuff..
wrapping the `simpleGet` content in a goroutine actually worked but if I try to return something (even using channels) I get the same.

```go
func simpleGet(this js.Value, args []js.Value) interface{} {
	ret := make(chan string, 0)

	go func() {
		resp, err := http.Get(myURL)
		if err != nil {
			fmt.Println(err.Error())
		}
		fmt.Println("Resp status: ", resp.Status)
		ret <- resp.Status
	}()

	return <-ret
}
```

returning `nil` doesn't trigger the exception.

**Comment by finnbear** [comment] 2021-02-25 17:20
My channels suggestion is probably not what you actually want, since you can't block on the channel in the `FuncOf` function (as you just found out). I'm not sure what your use case is but maybe you should consider an asynchronous pattern. Rather than returning the result, take a callback as a parameter and call that.

Or, what worked for my very large Go/WebAssembly project is to do all the networking code in native JavaScript using the `fetch` API or a library like `axios`, and pass the data to Go for processing. I recommend highly recommend this approach, but it obviously isn't fully Go.

**Comment by seankhliao** [comment] 2021-02-25 18:41
Closing as working as intended

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Closed by seankhliao** 2021-02-25 18:41 UTC
