### ISSUE TITLE
archive/tar: incorrectly claims huge file size

### ISSUE THREAD

**Issue by dvyukov** [golang/go#12434] opened 2015-09-01 14:26 UTC
The following program crashes:
```go
package main

import (
	"archive/tar"
	"bytes"
	"io"
)

func main() {
	t := tar.NewReader(bytes.NewReader([]byte(data)))
	for {
		hdr, err := t.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return
		}
		if hdr.Size > 1e6 {
			panic("huge claimed file size")
		}
	}
}

var data = "bbb\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"0000640\x000374534\x000011" +
	"610\x0000003700153\x001253" +
	"1147347\x00006462\x000\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x000000000\x00000" +
	"0000\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\xfd\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" +
	"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
```
```
panic: huge claimed file size
```

Since tar is not compressing and input size is 512, this looks bogus.

go version go1.5 linux/amd64

**Comment by dsnet** [comment] 2015-09-08 10:50
I believe tar is working properly here. A check for hdr.Size should occur *after* an attempt to read the data first. In this situation, the header properly encodes a size of 1015915 bytes, but the tar format itself is bad in that it doesn't contain any data after the header. This is an example of a "valid" tar file that is prematurely truncated.

Modifying the example to include a read](https://play.golang.org/p/TtOnnxTZrY), properly returns an io.ErrUnexpectedEOF due to a truncated stream.

Furthermore, if we [modify the example](https://play.golang.org/p/GHPx40d6r2) to include a reader that artificially extends the file to a sufficient length, this reads properly.

I recommend that we close this.

**Comment by ianlancetaylor** [comment] 2015-09-08 18:17
If the package is calling panic, I don't think it's working as intended.

**Comment by dsnet** [comment] 2015-09-08 18:18
The package isn't calling panic, the test code is calling panic.

**Comment by ianlancetaylor** [comment] 2015-09-08 18:20
Whoops, thanks.

Closing.  @dvyukov , feel free to reopen if you disagree.

**Closed by ianlancetaylor** 2015-09-08 18:20 UTC
