### ISSUE TITLE
go modules with _test packages

### ISSUE THREAD

**Issue by wsc1** [golang/go#26820] opened 2018-08-06 08:20 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.11 beta 3

### What operating system and processor architecture are you using (`go env`)?
⎣ ⇨ go1.11beta3 env 
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/scott/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/scott/3p/go"
GOPROXY=""
GORACE=""
GOROOT="/Users/scott/sdk/go1.11beta3"
GOTMPDIR=""
GOTOOLDIR="/Users/scott/sdk/go1.11beta3/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/scott/Dev/gomod/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wv/qs6x44tj2bs8rm7fqw8p79yw0000gn/T/go-build691698606=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
⎣ ⇨ ls 
a.go      a_test.go go.mod
⎡ /Users/scott/Dev/gomod:scott@pavillion1 (18-08-06 10:12:44) ───────────────────── (78618|0)⎤
⎣ ⇨ cat go.mod 
module gomod
⎡ /Users/scott/Dev/gomod:scott@pavillion1 (18-08-06 10:12:50) ───────────────────── (78619|0)⎤
⎣ ⇨ cat a.go
package gomod

func F() int {
	return 111
}
⎡ /Users/scott/Dev/gomod:scott@pavillion1 (18-08-06 10:12:55) ───────────────────── (78620|0)⎤
⎣ ⇨ cat a_test.go 
package gomod_test

import "testing"
import "gomod"

func TestF(t *testing.T) {
	if gomod.F() != 111 {
		t.Error("didn't get 111")
	}
}
⎡ /Users/scott/Dev/gomod:scott@pavillion1 (18-08-06 10:12:59) ───────────────────── (78621|0)⎤
⎣ ⇨ go1.11beta3 test
build gomod_test: cannot find module for path gomod_test

### What did you expect to see?

for go1.11beta3 test to succeed

### What did you see instead?

see above

**Comment by myitcv** [comment] 2018-08-06 08:56
Sounds like a duplicate of https://github.com/golang/go/issues/26722; not in exact nature but underlying cause.

**Closed by myitcv** 2018-08-06 08:56 UTC
