### ISSUE TITLE
encoding/json: Marshal and Encode differ

### ISSUE THREAD

**Issue by masseelch** [golang/go#47063] opened 2021-07-06 12:38 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
O111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/_/.cache/go-build"
GOENV="/home/_/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/_/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/_/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/_/Code/go_pkgs/elk/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3215158634=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Having an app serialize structs with `json.Encode.Encode()` to write the data to an `io.Writer`. Running tests with `json.Marshal` I noticed that the generated data differs: `json.Encoder.Encode()` adds a newline at the end while `json.Marshal` does not. Is this intended? Is this a bug?

[Example](https://play.golang.org/p/f7mn431-qlu)

### What did you expect to see?
They have the same output.

### What did you see instead?
They do not have the same output.

**Comment by mdlayher** [comment] 2021-07-06 12:51
https://golang.org/pkg/encoding/json/#Encoder

The Encoder is meant for writing a stream of JSON values and is documented to add a newline. Closing, I believe this is working as intended.

**Closed by mdlayher** 2021-07-06 12:51 UTC

**Comment by masseelch** [comment] 2021-07-06 12:53
This totally slipped my research. You are correct, I apologize.
