### ISSUE TITLE
x/build/cmd/gerritbot: add magic comment or label to pause Gerritbot on a PR

### ISSUE THREAD

**Issue by bradfitz** [golang/go#35464] opened 2019-11-08 18:37 UTC
When I want to take over a CL in Gerrit, I can forge the author and work in peace.

If I want to take over a CL in Gerrit that originated from Gerritbot, I need to race and get my change +2'ed and submitted before Gerritbot wakes up and overwrites my work.

I'd like to be able to leave a comment or set a label on a GitHub PR to disable Gerritbot for that PR.

/cc @andybons @dmitshur @cagedmantis @bcmills

**Comment by bcmills** [comment] 2019-11-08 19:55
Could GerritBot just compare the timestamp of the last upload with the timestamp of the last PR update? Seems like it should only sync a PR over to Gerrit if the PR contents are newer than the latest Gerrit PatchSet.

**Comment by bradfitz** [comment] 2019-11-08 20:01
That works too, if that's not too difficult.

**Comment by andybons** [comment] 2019-11-08 20:25
Duplicate of #24887

**Closed by andybons** 2019-11-08 20:25 UTC
Labels: Builders, FeatureRequest, NeedsInvestigation
