### ISSUE TITLE
Example in template throws panic 

### ISSUE THREAD

**Issue by adriantam** [golang/go#14381] opened 2016-02-18 14:05 UTC
The example in https://golang.org/pkg/text/template/#example_Template throws panic when attempting to run 

The panic text is 
panic: template: letter:5: illegal number syntax: "-"

goroutine 1 [running]:
text/template.Must(0x0, 0xfeec0018, 0x1050a1e0, 0x0, 0x0, 0xfeec0018)
	/usr/local/go/src/text/template/helper.go:23 +0x60
main.main()
	/tmp/sandbox410328915/main.go:37 +0x320

The example is 
package main

import (
	"log"
	"os"
	"text/template"
)

func main() {
	// Define a template.
	const letter = `
Dear {{.Name}},
{{if .Attended}}
It was a pleasure to see you at the wedding.
{{- else}}
It is a shame you couldn't make it to the wedding.
{{- end}}
{{with .Gift -}}
Thank you for the lovely {{.}}.
{{end}}
Best wishes,
Josie
`

	// Prepare some data to insert into the template.
	type Recipient struct {
		Name, Gift string
		Attended   bool
	}
	var recipients = []Recipient{
		{"Aunt Mildred", "bone china tea set", true},
		{"Uncle John", "moleskin pants", false},
		{"Cousin Rodney", "", false},
	}

	// Create a new template and parse the letter into it.
	t := template.Must(template.New("letter").Parse(letter))

	// Execute the template for each recipient.
	for _, r := range recipients {
		err := t.Execute(os.Stdout, r)
		if err != nil {
			log.Println("executing template:", err)
		}
	}

}

**Comment by B4dM4n** [comment] 2016-02-18 14:38
The problem is the new template syntax added in 1.6.
go-playground is still running on 1.5.1.

**Comment by ianlancetaylor** [comment] 2016-02-18 22:30
Closing in favor of #14393 .

**Closed by ianlancetaylor** 2016-02-18 22:30 UTC
