### ISSUE TITLE
Escape analysis caused unintuitive behavior

### ISSUE THREAD

**Issue by ashi009** [golang/go#27644] opened 2018-09-12 17:34 UTC
#### What did you do?

https://play.golang.org/p/0EKO_Iju5Ol

#### What did you expect to see?

```
b ----- b
b ----- b
```

#### What did you see instead?

```
a ----- b
b ----- b
```

#### Does this issue reproduce with the latest release (go1.11)?

yep.

#### System details

```
go version go1.10.3 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xiaoyi/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xiaoyi/go"
GORACE=""
GOROOT="/Users/xiaoyi/homebrew/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/Users/xiaoyi/homebrew/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cb/j3f4sj8j3yq46t5kqcc5mpj80000gn/T/go-build864956246=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.10.3 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.10.3
uname -v: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
lldb --version: lldb-900.0.64
  Swift-4.0
```

**Comment by randall77** [comment] 2018-09-12 17:43
When you do `[]byte(s)` where `s` is a `string`, the runtime can choose to use a capacity larger than the length of `s`.  In this case that choice depends on escape analysis.  It chooses 0 in your first case and 32 in your second case (print cap(s) in your `Printf`s to see this in action).
Closing, as this is not a bug.

**Closed by randall77** 2018-09-12 17:43 UTC

**Comment by ianlancetaylor** [comment] 2018-09-12 17:45
Related to #24163.
