### ISSUE TITLE
cmd/go: crash in symabis

### ISSUE THREAD

**Issue by rsc** [golang/go#31922] opened 2019-05-08 19:19 UTC
Running "go vet", happened once but real:

```
fatal error: concurrent map writes

goroutine 400 [running]:
runtime.throw(0x16272b3, 0x15)
	/Users/rsc/go/src/runtime/panic.go:714 +0x72 fp=0xc0003971f0 sp=0xc0003971c0 pc=0x102eba2
runtime.mapassign_faststr(0x157dcc0, 0xc0001505d0, 0x1621959, 0xb, 0x1a9b7e0)
	/Users/rsc/go/src/runtime/map_faststr.go:291 +0x3fe fp=0xc000397258 sp=0xc0003971f0 pc=0x1014c4e
cmd/go/internal/load.loadImport(0x0, 0x1621959, 0xb, 0xc00002c280, 0x19, 0xc000344480, 0xc000397598, 0x0, 0x0, 0x0, ...)
	/Users/rsc/go/src/cmd/go/internal/load/pkg.go:506 +0xd3d fp=0xc000397398 sp=0xc000397258 pc=0x1371bfd
cmd/go/internal/load.LoadImport(0x1621959, 0xb, 0xc00002c280, 0x19, 0xc000344480, 0xc000397598, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/rsc/go/src/cmd/go/internal/load/pkg.go:464 +0xaa fp=0xc000397408 sp=0xc000397398 pc=0x1370e9a
cmd/go/internal/load.LoadImportWithFlags(0x1621959, 0xb, 0xc00002c280, 0x19, 0xc000344480, 0xc000397598, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/rsc/go/src/cmd/go/internal/load/pkg.go:1908 +0xa4 fp=0xc000397480 sp=0xc000397408 pc=0x137b444
cmd/go/internal/work.gcToolchain.symabis(0xc00032e6e0, 0xc000298500, 0xc0002de400, 0x8, 0x8, 0x0, 0x0, 0x10101010101, 0x0)
	/Users/rsc/go/src/cmd/go/internal/work/gc.go:324 +0x1d1 fp=0xc000397628 sp=0xc000397480 pc=0x14508d1
cmd/go/internal/work.(*gcToolchain).symabis(0x1a9aa40, 0xc00032e6e0, 0xc000298500, 0xc0002de400, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:1 +0x6f fp=0xc000397680 sp=0xc000397628 pc=0x146a3cf
cmd/go/internal/work.(*Builder).build(0xc00032e6e0, 0xc000298500, 0x0, 0x0)
	/Users/rsc/go/src/cmd/go/internal/work/exec.go:610 +0x12b2 fp=0xc000397ea0 sp=0xc000397680 pc=0x1431742
cmd/go/internal/work.(*Builder).Do.func1(0xc000298500)
	/Users/rsc/go/src/cmd/go/internal/work/exec.go:106 +0x29a fp=0xc000397f28 sp=0xc000397ea0 pc=0x146490a
cmd/go/internal/work.(*Builder).Do.func2(0xc000025a94, 0xc00032e6e0, 0xc0002d6fa0)
	/Users/rsc/go/src/cmd/go/internal/work/exec.go:163 +0x6f fp=0xc000397fc8 sp=0xc000397f28 pc=0x14649af
runtime.goexit()
	/Users/rsc/go/src/runtime/asm_amd64.s:1356 +0x1 fp=0xc000397fd0 sp=0xc000397fc8 pc=0x105b871
created by cmd/go/internal/work.(*Builder).Do
	/Users/rsc/go/src/cmd/go/internal/work/exec.go:150 +0x38e
```

It's not OK for loading to be called during building. Will need to figure out what to do.

/cc @aclements FYI

**Comment by aclements** [comment] 2019-05-08 20:36
Is this the same underlying issue as #31230?

**Comment by bcmills** [comment] 2019-05-09 15:17
Duplicate of #31230

**Closed by bcmills** 2019-05-09 15:17 UTC
Labels: release-blocker
