### ISSUE TITLE
proposal: cmd/go: Is it possible to support replace the standard library in go module?

### ISSUE THREAD

**Issue by win5do** [golang/go#66780] opened 2024-04-11 13:03 UTC
# Proposal Details

## expect

```mod
replace database/sql => ./internal/src/database/sql
```

Doing this now will not cause an error, but it will have no effect.

go version go1.22.0 darwin/arm64

## purpose

The reason for doing this is to insert some code into the std pkg for debugging.

A practical case, I found goroutines leak through `/pprof/goroutine?debug=1` and `/pprof/goroutine?debug=2`.

```log
10 @ 0x104b7a7a8 0x104b44004 0x104b43bc4 0x1054075e8 0x104bb5094
#        0x1054075e7        database/sql.(*Tx).awaitDone+0x37        /opt/homebrew/opt/go/libexec/src/database/sql/sql.go:2202
```

```log
goroutine 638612 [chan receive]:
database/sql.(*Tx).awaitDone(0x14000492000)
        /opt/homebrew/opt/go/libexec/src/database/sql/sql.go:2202 +0x38
created by database/sql.(*DB).beginDC in goroutine 638919
        /opt/homebrew/opt/go/libexec/src/database/sql/sql.go:1915 +0x1ac
```

It is very difficult to find where the transaction is not released in the massive business code, so I want to insert some code in `src/database/sql` to track the parent caller stack.

Will Go provide similar capabilities?

**Comment by seankhliao** [comment] 2024-04-11 13:25
Duplicate of #35283

**Closed by seankhliao** 2024-04-11 13:25 UTC
Labels: Proposal
