### ISSUE TITLE
maps: document that DeleteFunc fails in presence of NaN keys 

### ISSUE THREAD

**Issue by candlerb** [golang/go#63312] opened 2023-09-30 13:57 UTC
### What version of Go are you using (`go version`)?

Playground 1.21: https://go.dev/play/p/-NzVmrPm-ln

### Does this issue reproduce with the latest release?

Yes: https://go.dev/play/p/-NzVmrPm-ln?v=gotip

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

```
package main

import (
	"fmt"
	"maps"
	"math"
)

func build(n int) map[float64]int {
	m := map[float64]int{}
	for i := 0; i < n; i++ {
		m[math.NaN()] = i
		//m[float64(i)] = i
	}
	return m
}

func main() {
	m := build(10)
	for k, v := range m {
		fmt.Printf("%f %d\n", k, v)
	}
	fmt.Printf("-----\n")
	maps.DeleteFunc(m, func(k float64, v int) bool {
		return v == 7
	})
	for k, v := range m {
		fmt.Printf("%f %d\n", k, v)
	}
}
```

(Code based on [this](https://research.swtch.com/randhash) from @rsc)

### What did you expect to see?

One element deleted from the map: the one where DeleteFunc's predicate returns true (v == 7).

### What did you see instead?

No elements are deleted from the map.

However, if I replace `m[math.NaN()] = i` with `m[float64(i)] = i`, so that the map has all distinct non-NaN keys, it works.

**Comment by seankhliao** [comment] 2023-09-30 17:46
I believe this is unfortunate but working as intended.
`clear` is the only way NaN keys can be removed.

**Comment by candlerb** [comment] 2023-09-30 17:55
> `clear` is the only way NaN keys can be removed.

I didn't see this documented either with [maps.DeleteFunc](https://pkg.go.dev/maps#DeleteFunc), or with [map types](https://go.dev/ref/spec#Map_types) or [clear](https://go.dev/ref/spec#Clear). Maybe it should be?

Aside: there's some possibly unfortunate language relating to min/max [here](https://go.dev/ref/spec#Min_and_max): "assuming all NaNs are equal". NaNs are not equal - not even to themselves. But I believe that all NaNs are equivalent or fungible.

**Comment by seankhliao** [comment] 2023-09-30 18:30
The inequality of NaNs come from:

> Two floating-point values are compared as defined by the IEEE-754 standard.

**Comment by candlerb** [comment] 2023-09-30 19:12
Yes I understand that. I was querying the language of the golang spec which says *"assuming all NaNs are equal"*

**Comment by randall77** [comment] 2023-09-30 21:15
We should document this behavior, if nothing else. I'll reopen for that.

It is possible we could let `DeleteFunc` to dive into the runtime to delete entries which have NaN keys. Since `DeleteFunc`  is already released with the current behavior, changing its behavior is a breaking change. Although I think it's pretty easy to justify this as a bug fix, at the same time I'm not seeing any strong reason to fix it, and compatibility argues for keeping the behavior as is.

**Comment by bcmills** [comment] 2023-10-13 17:33
(Compare #20660.)

**Closed** 2024-07-17 23:09 UTC
Labels: Documentation, NeedsFix, FixPending
