### ISSUE TITLE
time: UTC location handling in `time.Unix` differs from expected value

### ISSUE THREAD

**Issue by jalandis** [golang/go#66346] opened 2024-03-15 22:43 UTC
### Go version

go version go1.22.0 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/jalandis/Library/Caches/go-build'
GOENV='/Users/jalandis/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/jalandis/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/jalandis/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.22.0/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.22.0/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/jalandis/workspace/pgx/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/97/3gml51b50nzd14ds52554cj00000gn/T/go-build2890696919=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

Calling `time.Unix()` with env `TZ=UTC` and found the `time.Time` result had a non nil location.

### What did you see happen?

Location is expected to be nil for UTC and this differs from all other handling of time values in the package.  It cause some confusion + required comparison changes for testing.  The dates are equivalent but in an inconsistent format.

### What did you expect to see?

According to notes in `time.go`, I was expecting the location to be `nil`. 

```
	// loc specifies the Location that should be used to
	// determine the minute, hour, month, day, and year
	// that correspond to this Time.
	// The nil location means UTC.
	// All UTC times are represented with loc==nil, never loc==&utcLoc.
	loc *Location
```

The `Unix` function should be using `setLoc` to set location.

**Comment by seankhliao** [comment] 2024-03-15 23:39
Duplicate of #19202 #19486

**Closed by seankhliao** 2024-03-15 23:39 UTC
