### ISSUE TITLE
golang library from python code

### ISSUE THREAD

**Issue by Hedgehogues** [golang/go#38400] opened 2020-04-13 06:05 UTC
I need to import golang-package in python code. I [found](https://medium.com/learning-the-go-programming-language/calling-go-functions-from-other-languages-4c7d8bcc69bf) that this is usually done by compiling a static c-library. Exactly also written in the [docs](https://golang.org/cmd/cgo/#hdr-C_references_to_Go). I also saw that there is a serious [restriction](https://golang.org/cmd/cgo/#hdr-C_references_to_Go) on the import of golang structures. Tell me, how can I get around this problem? My functions operate with golang structures. What to do, I do not really understand

**Comment by ALTree** [comment] 2020-04-13 07:49
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-04-13 07:49 UTC
