### ISSUE TITLE
x/review: flaky mock Gerrit errors on dragonfly-amd64-622 (one NetBSD/FreeBSD)

### ISSUE THREAD

**Issue by prattmic** [golang/go#60796] opened 2023-06-14 20:26 UTC
```
#!watchflakes
post <- `Gerrit response:`
```

Existing failures:

[2023-06-14T17:09:34-d285cae-0a48e5c/dragonfly-amd64-622](https://build.golang.org/log/4a74c114664f9180a854373179b12f05fb319d9e)

```
git-codereview: fetch /a/changes/?o=DETAILED_LABELS&o=CURRENT_REVISION&o=MESSAGES&o=DETAILED_ACCOUNTS&q=change%3Atmp%2Fworkdir%2Ftmp%2Fgit-codereview-test3062096014%2Fgit-origin~main~I123456789: Get "/a/changes/?o=DETAILED_LABELS&o=CURRENT_REVISION&o=MESSAGES&o=DETAILED_ACCOUNTS&q=change%3Atmp%2Fworkdir%2Ftmp%2Fgit-codereview-test3062096014%2Fgit-origin~main~I123456789": unsupported protocol scheme ""
git-codereview: fetch /a/changes/?o=DETAILED_LABELS&o=CURRENT_REVISION&o=MESSAGES&o=DETAILED_ACCOUNTS&q=change%3Atmp%2Fworkdir%2Ftmp%2Fgit-codereview-test3062096014%2Fgit-origin~main~I123456789: Get "/a/changes/?o=DETAILED_LABELS&o=CURRENT_REVISION&o=MESSAGES&o=DETAILED_ACCOUNTS&q=change%3Atmp%2Fworkdir%2Ftmp%2Fgit-codereview-test3062096014%2Fgit-origin~main~I123456789": unsupported protocol scheme ""
git-codereview: fetch /a/changes/?o=DETAILED_LABELS&o=CURRENT_REVISION&o=MESSAGES&o=DETAILED_ACCOUNTS&q=change%3Atmp%2Fworkdir%2Ftmp%2Fgit-codereview-test3062096014%2Fgit-origin~main~I123456789: Get "/a/changes/?o=DETAILED_LABELS&o=CURRENT_REVISION&o=MESSAGES&o=DETAILED_ACCOUNTS&q=change%3Atmp%2Fworkdir%2Ftmp%2Fgit-codereview-test3062096014%2Fgit-origin~main~I123456789": unsupported protocol scheme ""
git-codereview: fetch /a/changes/?o=DETAILED_LABELS&o=CURRENT_REVISION&o=MESSAGES&o=DETAILED_ACCOUNTS&q=change%3Atmp%2Fworkdir%2Ftmp%2Fgit-codereview-test3062096014%2Fgit-origin~main~I123456789: Get "/a/changes/?o=DETAILED_LABELS&o=CURRENT_REVISION&o=MESSAGES&o=DETAILED_ACCOUNTS&q=change%3Atmp%2Fworkdir%2Ftmp%2Fgit-codereview-test3062096014%2Fgit-origin~main~I123456789": unsupported protocol scheme ""
git-codereview: fetch /a/changes/proj~main~I123456789?o=LABELS&o=CURRENT_REVISION: change not found on Gerrit server
Gerrit response:
404 page not found

git-codereview: fetch /a/changes/proj~main~I123456789?o=LABELS&o=CURRENT_REVISION: http://127.0.0.1:58744/a/changes/proj~main~I123456789?o=LABELS&o=CURRENT_REVISION: malformed json response
Gerrit response:
)]}'
XXX
git-codereview: fetch /a/changes/proj~main~I0000001?o=LABELS&o=CURRENT_REVISION: change not found on Gerrit server
Gerrit response:
404 page not found

--- FAIL: TestSubmitMultiple (0.43s)
    submit_test.go:247: git-codereview submit
    submit_test.go:186: git-codereview submit 8424805d8f31e84f2f307f32d71c37360d9fcbcf 8f4ae862b6fe90e35b238e117c6f2114c479836a
    util_test.go:360: died
        stdout:
        stderr:
        git-codereview: submitting 8424805 msg
        git-codereview: change not found on Gerrit server
FAIL
FAIL	golang.org/x/review/git-codereview	55.083s
FAIL
```

[2023-06-01T22:32:26-1970062-7183e77/dragonfly-amd64-622](https://build.golang.org/log/46d23b463156b1d83d5f704cc5215296e10b3fd9)
[2023-06-01T17:13:46-1970062-691b6ca/dragonfly-amd64-622](https://build.golang.org/log/fbe4b2ed14472662dc95ac9294594984ab1fd427)
[2023-04-10T15:50:11-1970062-a3dd959/dragonfly-amd64-622](https://build.golang.org/log/c73f710683cd7d11ff6805c10cf0c9005c54f6c9)
[2023-04-07T20:44:50-1970062-46a49eb/dragonfly-amd64-622](https://build.golang.org/log/1b6d3ea83844b75da4cf9a6bb5ed43c43ea15865)
[2022-12-07T00:25:27-1970062-10bb003/netbsd-386-9_0](https://build.golang.org/log/905d98094fa026b0bffb75a17c68b2b7740e6f33)
[2022-09-06T11:14:09-0c548b8-1c50484/dragonfly-amd64-622](https://build.golang.org/log/034fd7c6ea563c874642d9c3b7a8e9685683b898)
[2022-09-05T21:39:28-0c548b8-4c1ca42/dragonfly-amd64-622](https://build.golang.org/log/497e34ac0f57a198c619576ff1ae6d02fdf4f81c)
[2022-09-03T18:29:30-0c548b8-2392b70/dragonfly-amd64-622](https://build.golang.org/log/cf19a1d67ee8b95f5add6d3d4b3f0a69d07059d7)
[2022-08-12T17:54:26-0c548b8-7f3569c/dragonfly-amd64-622](https://build.golang.org/log/17d3884a76f7b69ae0ace9434ce9be23367ea796)
[2022-08-12T16:22:39-0c548b8-2cf49a7/dragonfly-amd64-622](https://build.golang.org/log/41824561573e081a812bc98e155dc2a12f2a556b)
[2022-06-07T17:44:51-5579f24-69bb7c6/dragonfly-amd64](https://build.golang.org/log/5097d0582cf56cb47c245500a314f361a78c216a)
[2022-06-07T16:07:58-5579f24-d2630aa/freebsd-arm64-dmgk](https://build.golang.org/log/19d03c07e1d249659b6602f28d39dac5fbd5b9f7)

If I understand correctly here, "Gerrit" in these tests is a mock server listening on a localhost port.

cc @golang/dragonfly @golang/freebsd

**Comment by prattmic** [comment] 2023-06-14 20:27
cc @golang/netbsd

**Comment by bcmills** [comment] 2023-06-14 20:47
Duplicate of #49899

**Comment by bcmills** [comment] 2023-06-14 20:47
Duplicate of #56221

**Closed** 2023-06-30 20:32 UTC
Labels: OS-Dragonfly, OS-FreeBSD, OS-NetBSD, NeedsInvestigation
