### ISSUE TITLE
proposal: make error handling simpler 

### ISSUE THREAD

**Issue by mikolajsemeniuk** [golang/go#60251] opened 2023-05-17 09:59 UTC
Currently when we take a look of definition of `append` we would see it is legal to append a `string` to a `byte slice` as a special case as documentation says:
```
The append built-in function appends elements to the end of a slice. If
it has sufficient capacity, the destination is resliced to accommodate the
new elements. If it does not, a new underlying array will be allocated.
Append returns the updated slice. It is therefore necessary to store the
result of append, often in the variable holding the slice itself:

	slice = append(slice, elem1, elem2)
	slice = append(slice, anotherSlice...)

As a special case, it is legal to append a string to a byte slice, like this:

	slice = append([]byte("hello "), "world"...)
```

I would like to have similar feature as special case for `error` type:
```go
type error interface {
	Error() string
}
```

Instead of writing:
```go
if err != nil {
    return err
}
```

We could write:
```go
if err {
    return err
}
```

Which automatically check if `error` type is not `nil` and if yes execute block statement.

**Comment by seankhliao** [comment] 2023-05-17 10:21
Duplicate of #26712

**Closed by seankhliao** 2023-05-17 10:21 UTC
Labels: LanguageChange, v2, Proposal, error-handling
