### ISSUE TITLE
x/pkgsite: consider moving to goldmark to handle issues in READMEs

### ISSUE THREAD

**Issue by hhrutter** [golang/go#39297] opened 2020-05-28 10:41 UTC
### What is the URL of the page with the issue?
 https://pkg.go.dev/mod/github.com/pdfcpu/pdfcpu
 
### What is your user agent?
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

Some images don't show up and there is also a markdown table that's screwed up.

**Comment by julieqiu** [comment] 2020-05-28 14:47
Thanks for the feedback @hhrutter - we'll work on a fix! This is also related to #37194

**Comment by josh-newman** [comment] 2020-08-05 00:07
In case it's helpful, I ran into another case of incorrect table rendering, this time with no images in the table: [correct on Github](https://github.com/xitongsys/parquet-go#type) ([snapshot](http://archive.vn/jIksA#selection-2657.0-3081.3)), [incorrect on pkg.go.dev](https://pkg.go.dev/github.com/xitongsys/parquet-go@v1.5.2?tab=overview) ([snapshot](http://archive.vn/0kX7o#selection-621.0-624.0)).

**Comment by shaqque** [comment] 2020-08-05 04:55
The broken markdown tables for both packages ([pdfcpu](https://pkg.go.dev/mod/github.com/pdfcpu/pdfcpu) and [parquet-go](https://github.com/xitongsys/parquet-go#type)) seem to be caused by incorrectly formatted markdown, at least according to [blackfriday](https://github.com/russross/blackfriday/issues/351) (the external markdown parser pkg.go.dev uses). Note that [Github-flavored-markdown](https://github.github.com/gfm/) (GFM), which Github uses, is not the same as regular markdown.

Specifically, 
1. pdfcpu's table does not does not have a space/newline before the start of the table, causing blackfriday to not detect it as a table. Adding that space allows blackfriday to detect the table correctly. 
   * Reproduction: https://play.golang.org/p/lraQZ-OlRcp
2. parquet-go's table uses 1 hyphen per column in the header row instead of 3, which blackfriday requires (see https://github.com/russross/blackfriday/issues/351). This also appears to violate Github's [documentation for tables](https://docs.github.com/en/github/writing-on-github/organizing-information-with-tables), though the official [Github-flavored-markdown spec](https://github.github.com/gfm/#delimiter-row) doesn't say anything about this despite the examples all having 3 hyphens per column.
   * Reproduction: https://play.golang.org/p/0EhSP25SY31

There is a related discussion on #40203 about blackfriday and GFM. In particular, @zikaeroh suggested
> Unless I'm mistaken, blackfriday isn't actively developed anymore, and many have moved onto goldmark. Hugo, gitea, and even x/tools/present and x/website use goldmark for their markdown support.
> 
> Perhaps it'd be better to move to a markdown library which is actively maintained.

I tried the above cases using [goldmark](https://github.com/yuin/goldmark), and in both cases, the table was identified and rendered properly.
* Reproduction: https://play.golang.org/p/CiJmIbnu6RV. This won't actually run on the playground since the build takes too long.

I think this, along with active maintenance (last commit was 6 days ago) and broader use among other Go projects, makes moving to goldmark a good idea.

**Comment by jamalc** [comment] 2020-11-18 18:48
@hhrutter - this should be fixed. We made the switch to goldmark 😊

**Closed by jamalc** 2020-11-18 18:48 UTC
Labels: NeedsInvestigation, pkgsite
