### ISSUE TITLE
`go tool pprof` is using lot of memory while loading a memory profile file

### ISSUE THREAD

**Issue by nilsocket** [golang/go#26783] opened 2018-08-03 07:25 UTC
### What version of Go are you using (`go version`)?
`go version go1.10.3 linux/amd64`

### Does this issue reproduce with the latest release?
considering this is the present release, yes.

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="linux"
kernel=`4.17.11-arch1`

### What did you do?
Wrote a [mergeSort program](https://play.golang.org/p/gLQfPaEz6ii), which uses a lot of memory (4 to 5GB),
for an input of one hundred million numbers.
Switched on memory profiling, which produced a pprof file of size 12.3MB.
Tried to load with `go tool pprof mem.pprof`.
> I knew there were some mistakes in the above mentioned program.

### What did you expect to see?
I expected `go tool` to not take lot of memory.

### What did you see instead?
`go tool` is taking lot of memory(4 to 5GB), while loading this [mem.pprof](https://drive.google.com/open?id=1q1NZO3XPLK79bmXf619vDYBHJ3ciehya) file.

### Is this reproducible?
Yes, I tried to load the same file in another laptop, which is running `Ubuntu 16.04`, with same go version.
kernel=`4.4.0-131-generic`
Same result.

> Don't load this file if you have less than 6GB of free memory.

**Comment by ysmolsky** [comment] 2018-08-03 07:56
`go tool pprof` just loads the pprof program for you. By itself `go tool` does not take that memory.  `pprof` does that.

I was able to reproduce this on mac 10.11.6, loading that profile took about 4.5GB of  ram.

This issue is not about Go compiler or tools. You have to ask authors of the pprof tool here: https://github.com/google/pprof/issues

**Comment by ianlancetaylor** [comment] 2018-08-03 14:22
Closing because this needs to be addressed in pprof, not in Go.

**Closed by ianlancetaylor** 2018-08-03 14:22 UTC
