### ISSUE TITLE
update https://tip.golang.org/doc/code.html to remove references to GOPATH

### ISSUE THREAD

**Issue by amnonbc** [golang/go#33622] opened 2019-08-13 12:43 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
tip
### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?
na
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
nothing

### What did you expect to see?
module compliant guidelines for code layout

### What did you see instead?
old GOPATH style layout

**Comment by agnivade** [comment] 2019-08-13 14:58
Hello @amnonbc, this is a duplicate of https://github.com/golang/go/issues/28215. And it looks like you have already commented there in the past. I am going to close this in favor of that.

**Closed by agnivade** 2019-08-13 14:58 UTC

**Comment by amnonbc** [comment] 2019-08-13 15:44
:+1:
