### ISSUE TITLE
Anybody else want < and > comparison on interfaces?

### ISSUE THREAD

**Issue by falafflepotatoe** [golang/go#19255] opened 2017-02-23 11:44 UTC
Consider this code.

    func eq(v,v2 interface{}) bool {
      return v==v2
    }
    
    func lt(v,v2 interface{}) bool {
      return v<v2 // invalid operation: v < v2 (operator < not defined on interface)
    }
    func main() {
	fmt.Println(eq(1,1))
    }

i understand the reasoning behind this but it seems not fair.
I was trying to make a laravel-style ORM, that allows for basic queries against datasets. The cool thing here is you can pass a custom function or one of the built in funcs like lessthan, equals, notequals...

    myArrayInts.getIndexes(lt, 2) //fetch the indexes
    myArrayAnimals.get(eq, 'cat') //fetch the values

There could be some coolness done here imo, but interface{} doesnt support < and > operators. So i tried making a wrapper func that uses a IntLt or an Int64Lt  func, etc that wouldnt work, so I tried doing it with reflection and that didnt work either. (But maybe it does? and i did it wrong!) Should this work with reflection?

### What did you expect to see?
Expected to be able to compare two interfaces of the same types

### What did you see instead?
invalid operation: v < v2 (operator < not defined on interface)
invalid operation: v > v2 (operator > not defined on interface)

I understand why its hard to compare them, but not why equals and not equals works but less than doesnt.

Any support for adding this feature? Please give a +1!
Or is it just impossible?

How do they do this in Gorm?

**Comment by mvdan** [comment] 2017-02-23 12:34
This is operator overloading, which is likely to not make its way into Go1 at this point.

**Comment by ALTree** [comment] 2017-02-23 12:41
> why equals and not equals works but less than doesnt.

Because ≤ defines an ordering and it's a much stronger relation than equal/not equal.

You can't define a binary relation ≤ on most types, so what's the point of supporting `<` and `>` on `interface{}` (i.e. on every type)?

> (But maybe it does? and i did it wrong!) Should this work with reflection?

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions like this. We only use the issue tracker for issues and proposals.

**Comment by ianlancetaylor** [comment] 2017-02-23 17:08
This is not a bug report, so I'm going to close it.

**Closed by ianlancetaylor** 2017-02-23 17:08 UTC
