### ISSUE TITLE
cmd/go: pass -arch to GOOS=darwin host compiler, linker

### ISSUE THREAD

**Issue by rsc** [golang/go#43692] opened 2021-01-14 14:20 UTC
See https://github.com/golang/vscode-go/issues/1087.
The root cause is confusion about the Mac toolchain expecting x86 vs arm binaries.
We should be able to fix the confusion by forcing when GOOS=darwin the use of `-arch arm64` or `-arch x86_64` (not sure the second is spelled correctly), to match GOARCH.

This would mean adding the flags in the C compiler invocation and also adding them to the -extld passed to the Go linker.

**Comment by bcmills** [comment] 2021-01-14 14:23
I think this is a duplicate of #43476, or at least very closely related.

**Comment by bcmills** [comment] 2021-01-14 15:13
If I understand https://clang.llvm.org/docs/CrossCompilation.html correctly, we might want to pass the `-arch` and/or `-target` flags to `clang` on all GOOSes (at least when cross-compiling), not just `darwin`.

I suppose `darwin` is somewhat unique in that apparently we can't easily determine whether `clang` thinks it is cross-compiling.

**Comment by rsc** [comment] 2021-01-14 15:34
At this point in the release cycle I'd be much more comfortable only doing it for darwin.
This may be a duplicate of #43476 but I think this bug states the problem more clearly if nothing else.

**Closed** 2021-01-14 21:56 UTC
Labels: NeedsInvestigation, release-blocker
