### ISSUE TITLE
Go indexing server doesn't see the version v0.8.3.1 of github.com/shenwei356/kmcp

### ISSUE THREAD

**Issue by yurivict** [golang/go#54501] opened 2022-08-17 15:47 UTC
### What version of Go are you using (`go version`)?
1.19

**Comment by yurivict** [comment] 2022-08-18 03:31
This URL https://proxy.golang.org/github.com/shenwei356/kmcp/@v/v0.8.3.1.info returns a different version for some reason:
```
{"Version":"v0.8.4-0.20220816044600-3dc30b20c9cf","Time":"2022-08-16T04:46:00Z","Origin":{"VCS":"git","URL":"https://github.com/shenwei356/kmcp","Hash":"3dc30b20c9cf3d166feeeae34013ff8c47697f54"}}
```

**Comment by seankhliao** [comment] 2022-08-18 07:33
Duplicate of #54515

**Closed by seankhliao** 2022-08-18 07:33 UTC
