### ISSUE TITLE
cmd/compile: unused variables not detected when captured by a closure

### ISSUE THREAD

**Issue by mizusato** [golang/go#45054] opened 2021-03-16 09:49 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

This snippet compiles:
<pre>
var a int
var b int
(func() {
	a, b = (func()(int,int){ return 1,1 })()
})()
</pre>

### What did you expect to see?

It should not compile because `a` and `b` are unused variables.
The compiler accepts it silently while `go vet` correctly reports an error.

**Comment by mdempsky** [comment] 2021-03-16 10:02
Duplicate of #3059.

**Closed by mdempsky** 2021-03-16 10:02 UTC
Labels: NeedsInvestigation
