### ISSUE TITLE
x/net/http2: TestTransportPingWhenReading fails on android-386-emu sometimes

### ISSUE THREAD

**Issue by dmitshur** [golang/go#40233] opened 2020-07-15 22:43 UTC
```
panic: Fail in goroutine after TestTransportPingWhenReading/two_pings_in_each_serverResponseInterval has completed

goroutine 14595 [running]:
testing.(*common).Fail(0xc0990500)
	/workdir/go/src/testing/testing.go:613 +0x105
testing.(*common).Error(0xc0990500, 0xc09bbfcc, 0x1, 0x1)
	/workdir/go/src/testing/testing.go:706 +0x62
golang.org/x/net/http2.testTransportPingWhenReading.func2.1(0xc0899a20, 0xc0921800, 0xc0c344a0, 0xc0990500, 0x3b9aca00, 0x0)
	/workdir/gopath/src/golang.org/x/net/http2/transport_test.go:3451 +0x30b
created by golang.org/x/net/http2.testTransportPingWhenReading.func2
	/workdir/gopath/src/golang.org/x/net/http2/transport_test.go:3437 +0x355
exitcode=2FAIL	golang.org/x/net/http2	24.773s
```

Source:

- https://build.golang.org/log/da3430afc1a232dc13e98576050154531ba0ec09 (Go 1.14 + recent x/net commit)
- https://build.golang.org/log/4a5484788c091c8d1bfe2b3923c722c5e548f2ba (Go 1.14 + recent x/net commit)

It may be the builder or the the test. Needs investigation.

/cc @bradfitz @tombergan per [owners](https://dev.golang.org/owners).

**Comment by dmitshur** [comment] 2020-07-15 22:45
Issue #39233 was related, but for Plan 9. /cc @millerresearch @0intro

**Comment by bcmills** [comment] 2020-09-09 18:17
I filed #41299 later but it has more detail, so marking this as a duplicate of that.

**Comment by bcmills** [comment] 2020-09-09 18:17
Duplicate of #41299

**Closed by bcmills** 2020-09-09 18:17 UTC
Labels: NeedsInvestigation
