### ISSUE TITLE
cmd/compile: internal compiler error: method Len on *uint8 not found

### ISSUE THREAD

**Issue by andig** [golang/go#54225] opened 2022-08-03 09:09 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/andig/Library/Caches/go-build"
GOENV="/Users/andig/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/andig/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andig/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/andig/sdk/go1.19"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/andig/sdk/go1.19/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/andig/htdocs/evcc/yorkie/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sv/rs_453y57xj86xsbz3kw1mbc0000gn/T/go-build2796829895=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.19 darwin/arm64
GOROOT/bin/go tool compile -V: compile version go1.19
uname -v: Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101
ProductName:	macOS
ProductVersion:	12.5
BuildVersion:	21G72
lldb --version: lldb-1316.0.9.46
Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
</pre></details>

### What did you do?

Build https://github.com/yorkie-team/yorkie by running

    go build ./...

### What did you expect to see?

Success

### What did you see instead?

```
go1.19 build ./...
go: downloading go.mongodb.org/mongo-driver v1.9.1
go: downloading github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
go: downloading github.com/stretchr/testify v1.7.5
go: downloading github.com/hashicorp/go-immutable-radix v1.3.1
go: downloading go.etcd.io/etcd/client/pkg/v3 v3.5.4
go: downloading github.com/youmark/pkcs8 v0.0.0-20201027041543-1326539a0a0a
go: downloading github.com/coreos/go-semver v0.3.0
go: downloading github.com/go-stack/stack v1.8.1
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/xdg-go/scram v1.1.1
go: downloading github.com/xdg-go/stringprep v1.0.3
go: downloading github.com/coreos/go-systemd/v22 v22.3.2
go: downloading github.com/xdg-go/pbkdf2 v1.0.0
# github.com/yorkie-team/yorkie/pkg/document/json
pkg/document/json/rga_tree_split.go:302:29: internal compiler error: method Len on *uint8 not found
```

The code is in https://github.com/yorkie-team/yorkie/blob/main/pkg/document/json/rga_tree_split.go#L299 which uses generics.

Refs: https://github.com/yorkie-team/yorkie/issues/378

**Comment by cuonglm** [comment] 2022-08-03 09:41
git bisect points to https://go-review.googlesource.com/c/go/+/385274 cc @randall77

**Comment by andig** [comment] 2022-08-03 11:42
It *does* build with `GOEXPERIMENT=unified`

**Comment by dmitshur** [comment] 2022-08-03 15:56
CC @golang/compiler.

**Comment by ssorren** [comment] 2022-08-15 17:18
I'm running into this error as well. The module in question builds fine, but when I try to import it into another project, I hit this error. Trying to come up with a short example, but the module in question is quite large and I'm not sure yet where the issue is.  When the compiler fails with "method [X] on *uint8 not found", X seems to be random. It changes depending on the code-base of the importing module. I will try to get an example going, but it's a bit like blindly poking around with a stick.

It does build with "GOEXPERIMENT=unified". But not sure I'm too comfortable with that flag in a production workflow/ Downgrading to 1.18.x for the time being. Will post an example when I'm able to produce one

**Comment by andig** [comment] 2022-08-15 20:14
@ssorren the link I‘ve posted is public as repro, though large…

**Comment by ssorren** [comment] 2022-08-15 20:40
@andig I get it. My repo is private still. Can't be made public yet. Trying to reproduce in small public example that won't get me fired :) but the error is hard to reproduce consistently

**Comment by mdempsky** [comment] 2022-08-15 21:50
Not fully minimized yet, but at least a standalone repro:

```
package json

type SplayTree[V any] struct{}

func (t *SplayTree[V]) Find(index int) {}

type Value interface {
        Len() int
}

type Node[V Value] struct{}

func (s *Node[V]) contentLen() int {
        var value V
        return value.Len()
}

type Split[V Value] struct{}

func (s *Split[V]) findNodePos(index int) {
        var treeByIndex *SplayTree[*Node[V]]
        treeByIndex.Find(index)
}

type TextValue struct{}

func (t *TextValue) Len() int { return 0 }

var x *Split[*TextValue]
```

**Comment by mdempsky** [comment] 2022-08-15 22:03
Further minimized: https://go.dev/play/p/WU6EOKRqM_V

It seems to be an issue around creating subdictionaries with derived types for the `Two[Node[V]]()` call, and that we're creating the dictionary with the shaped type argument instead of the unshaped one.

**Comment by cuonglm** [comment] 2022-08-27 10:40
This is now fixed at tip, could we close? @mdempsky

**Comment by mdempsky** [comment] 2022-08-27 17:37
@cuonglm Not yet. It's still a regression from 1.18 to 1.19, which deserves a backport fix if we can prepare one that we have confidence in.

**Comment by cuonglm** [comment] 2022-08-31 19:54
> It seems to be an issue around creating subdictionaries with derived types for the Two[Node[V]]() call, and that we're creating the dictionary with the shaped type argument instead of the unshaped one.

Yes, I think it's understandable, because irgen maps all types with the same underlying type to the same shape.

Maybe we should never create method expression closure for shape type, or just relaxing `g.finalizeSyms` to not complain if the method receiver has no methods at all (after calling `types.CalcMethods` on the method expression receiver).

**Comment by subokuma** [comment] 2022-09-20 14:53
Hi @cuonglm 
Thanks,  Is any plan for this fix to be backported in Go 1.19.2 milestone?

**Comment by cuonglm** [comment] 2022-09-20 14:57
> Hi @cuonglm Thanks, Is any plan for this fix to be backported in Go 1.19.2 milestone?

Yes, the backport CL: https://go-review.googlesource.com/c/go/+/429895

Seems we lack of backport issue cc @mdempsky

**Comment by mdempsky** [comment] 2022-09-20 16:56
@gopherbot Please backport to Go 1.19

**Comment by mdempsky** [comment] 2022-09-20 17:07
Fixed at tip by CL 429655.

**Closed by mdempsky** 2022-09-20 17:07 UTC
Labels: NeedsInvestigation, generics, compiler/runtime
