### ISSUE TITLE
cmd/gofmt: last call in fluent API call chain not indented correctly

### ISSUE THREAD

**Issue by willfaught** [golang/go#61331] opened 2023-07-13 04:46 UTC
### What did you do?

Formatted this code in the playground:

```go
func (ChannelReview) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("channel", Channel.Type).
			Unique().
			Required().
			Immutable().
			Ref("reviews").
			Field("channel_id").
			Annotations(entgql.Annotation{
				Skip: entgql.SkipType,
			}),
		edge.To("channel_local_reviews", ChannelLocalReview.Type).
			Annotations(entgql.Annotation{
				RelayConnection: true,
				Skip:            entgql.SkipMutationCreateInput,
			}).Annotations(entsql.Annotation{
			OnDelete: entsql.Cascade,
		}),
	}
}
```

https://go.dev/play/p/gyGabF-mcGX

### What did you expect to see?

```go
func (ChannelReview) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("channel", Channel.Type).
			Unique().
			Required().
			Immutable().
			Ref("reviews").
			Field("channel_id").
			Annotations(entgql.Annotation{
				Skip: entgql.SkipType,
			}),
		edge.To("channel_local_reviews", ChannelLocalReview.Type).
			Annotations(entgql.Annotation{
				RelayConnection: true,
				Skip:            entgql.SkipMutationCreateInput,
			}).Annotations(entsql.Annotation{
				OnDelete: entsql.Cascade, // indentation different
			}), // indentation different
	}
}
```

### What did you see instead?

```go
func (ChannelReview) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("channel", Channel.Type).
			Unique().
			Required().
			Immutable().
			Ref("reviews").
			Field("channel_id").
			Annotations(entgql.Annotation{
				Skip: entgql.SkipType,
			}),
		edge.To("channel_local_reviews", ChannelLocalReview.Type).
			Annotations(entgql.Annotation{
				RelayConnection: true,
				Skip:            entgql.SkipMutationCreateInput,
			}).Annotations(entsql.Annotation{
			OnDelete: entsql.Cascade,
		}),
	}
}
```

**Comment by cherrymui** [comment] 2023-07-13 17:15
As @fzipp pointed out, the playground correctly provides the result of gofmt. That said, that indentation indeed looks a bit weird to me.

cc @griesemer @mvdan

**Comment by willfaught** [comment] 2023-07-13 18:28
Yep, I knew that, but as you said, it looks wrong when you don't do that.

**Comment by seankhliao** [comment] 2023-07-14 18:21
Duplicate of #41889

**Closed by seankhliao** 2023-07-14 18:21 UTC
Labels: NeedsInvestigation
