### ISSUE TITLE
cmd/go: go mod init doesn't recognize GOPROXY 

### ISSUE THREAD

**Issue by yaxinlx** [golang/go#35931] opened 2019-12-02 09:49 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
$ git clone https://github.com/heketi/heketi.git
$ cd heketi
$ go mod init github.com/heketi/heketi
go: creating new go.mod: module github.com/heketi/heketi
go: copying requirements from glide.lock
go: converting glide.lock: stat k8s.io/apiserver@c809cf8581e1e44c6174bf5ab4415e6ee39965ca: unrecognized import path "k8s.io/apiserver" (https fetch: Get https://k8s.io/apiserver?go-get=1: dial tcp 35.201.71.162:443: connect: connection refused)
go: converting glide.lock: stat golang.org/x/text@2910a502d2bf9e43193af9d68ca516529614eed3: unrecognized import path "golang.org/x/text" (https fetch: Get https://golang.org/x/text?go-get=1: dial tcp 216.239.37.1:443: connect: connection refused)
go: converting glide.lock: stat golang.org/x/crypto@d172538b2cfce0c13cee31e647d0367aa8cd2486: unrecognized import path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/crypto?go-get=1: dial tcp 216.239.37.1:443: connect: connection refused)
go: converting glide.lock: stat k8s.io/client-go@3627aeb7d4f6ade38f995d2c923e459146493c7e: unrecognized import path "k8s.io/client-go" (https fetch: Get https://k8s.io/client-go?go-get=1: dial tcp 35.201.71.162:443: connect: connection refused)
...
```
### What did you expect to see?

Use GOPROXY to fetch modules

### What did you see instead?

But not, so many fetching fail.

**Comment by cagedmantis** [comment] 2019-12-02 17:51
This error happens when a custom remote import path has been used and the user can't query the domain. I was able to recreate this issue by bypassing the domain name resolution for k8s.io and golang.org via an edit to a local /etc/hosts file. 
@bcmills @jayconrod

**Comment by oiooj** [comment] 2019-12-03 02:38
Yes, now `ConvertLegacyConfig` not use `GOPROXY`, I think we need fix this.

**Comment by bcmills** [comment] 2019-12-04 17:40
Duplicate of #33767

**Closed by bcmills** 2019-12-04 17:40 UTC
Labels: NeedsFix, modules
