### ISSUE TITLE
Error with println

### ISSUE THREAD

**Issue by dobau** [golang/go#46248] opened 2021-05-18 22:47 UTC
Is this **println** correct in http.Error?

https://github.com/golang/go/blob/eeadce2d871358306f2a95b0cfbe809ea017932a/src/net/http/server.go#L2075-L2080

I am doing some unit tests, and the error messages got with a breakline.

**Comment by seankhliao** [comment] 2021-05-18 23:01
Duplicate of #24530

**Closed by seankhliao** 2021-05-18 23:01 UTC
