### ISSUE TITLE
encoding/json: support unmarshaling []int as []string with ,string tag

### ISSUE THREAD

**Issue by chenjie4255** [golang/go#16784] opened 2016-08-18 07:07 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.7rc6

2. What operating system and processor architecture are you using (`go env`)?
mac

3. What did you do?

I can marshal a int64 to json's string with a tag ```json:",string"````, but it could not support a []int64 to json's string, I try the following code but it fail:

```go
    type s struct {
        IDs []int64 `json:"ids,string"`
    }
    data := []byte(`{"ids":["123", "222"]}`)
    var ret s

    err := json.Unmarshal(data, &ret) // err here....
```

4. What did you expect to see?

a succeeful result.

5. What did you see instead?

a marshal error.

**Comment by odeke-em** [comment] 2016-08-18 07:38
Duplicate of https://github.com/golang/go/issues/15624, which has been marked as a feature request. Closing in favor of the mentioned issue.

**Closed by odeke-em** 2016-08-18 07:38 UTC
