### ISSUE TITLE
x/tools/go/loader: when loading >1 initial package in ImportBinary mode, some dependencies are loaded twice

### ISSUE THREAD

**Issue by rsc** [golang/go#9955] opened 2015-02-21 18:28 UTC
This is breaking a code cleanup tool I am building.

	g% cat /tmp/x.go
	package main
	
	import (
		"fmt"
		"log"
	
		"golang.org/x/tools/go/loader"
	)
	
	func main() {
		var conf loader.Config
		_, err := conf.FromArgs([]string{"cmd/nm", "cmd/pprof", "debug/gosym"}, false)
		if err != nil {
			log.Fatal(err)
		}
		_, err = conf.Load()
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("OK\n")
	}

	g% go run /tmp/x.go
	/Users/rsc/g/go/src/cmd/pprof/pprof.go:196:12: cannot assign pcln (variable of type *debug/gosym.Table) to f.pcln (variable of type *debug/gosym.Table)
	2015/02/21 13:25:20 couldn't load packages due to errors: cmd/pprof
	exit status 1
	g%

**Comment by rsc** [comment] 2015-02-21 18:29
@alandonovan @griesemer Not sure if this is go/loader or go/types. Seems to be confused and thinks there are (at least) two debug/gosym packages.

**Comment by alandonovan** [comment] 2015-02-21 19:01
I can reproduce it although I'm not certain what the cause is yet.

You almost certainly want this:
  conf := loader.Config{SourceImports: true}
which is an effective workaround, and should probably be the default but is not for historical reasons; otherwise it will attempt to load gc's export data for all imported packages, which may or may not be up-to-date.  I suspect because these packages are mains not libraries that export data is rarely installed.

**Comment by alandonovan** [comment] 2015-02-23 21:37
When two or more packages are specified on the command line, and !SourceImports is indicated (i.e. load dependencies from gc export data), and the transitive closure of one initial package A (e.g. cmd/pprof) includes another initial package B (e.g. debug/gosym), then B is created twice: once when loading it from binary to satisfy A, and again from source for B.

This isn't going to be a simple fix and the design is already so complex, and this case wasn't even the intended use, that I'm not certain it's worth fixing.  We could just restrict to a single import when using !SourceImports. (The only tool I know of that ever wants to load gc export data is llgo, and it doesn't load multiple packages at once.)

**Comment by shurcooL** [comment] 2015-04-17 19:28
This can be closed now. It was fixed in https://github.com/golang/tools/commit/9c57c19a58835b00c0e3e283952087842242e49b, but the commit message mistakenly said `Fixes #9955` rather than `Fixes go/golang#9955`.

**Comment by alandonovan** [comment] 2015-04-17 19:36
Oops, thanks.

**Closed by alandonovan** 2015-04-17 19:36 UTC

**Comment by josharian** [comment] 2015-04-17 19:46
FYI, @alandonovan, if you update to the latest version of git-codereview, it'll fix issue references for you when you save the commit message.

**Comment by alandonovan** [comment] 2015-04-17 19:53
On 17 April 2015 at 15:46, Josh Bleecher Snyder <notifications@github.com>
wrote:

> FYI, @alandonovan <https://github.com/alandonovan>, if you update to the
> latest version of git-codereview, it'll fix issue references for you when
> you save the commit message.
>

Ah, that explains it.  Thanks.
