### ISSUE TITLE
x/build/cmd/relnote: respect RELNOTE= in commit messages

### ISSUE THREAD

**Issue by bradfitz** [golang/go#31771] opened 2019-04-30 23:27 UTC
The RELNOTE=xxx part is currently only respected in Gerrit comments, but enough people are writing it in commit messages that we should support it there too.

/cc @dmitshur

**Comment by cespare** [comment] 2019-05-01 00:29
Duplicate of #31665

**Closed by cespare** 2019-05-01 00:29 UTC
Labels: Builders, NeedsFix, help wanted
