### ISSUE TITLE
database/sql: add Queryer interface

### ISSUE THREAD

**Issue by james-lawrence** [golang/go#14674] opened 2016-03-06 20:11 UTC
seems like 90% of the time I'm interacting with a database most of my DB code doesn't care if i'm within a TX or not. often there are queries I'm executing in various places with different contexts, some of which require a transaction, some which don't. But I can't share the code without writing my own Queryer style interface. now granted its only a few lines, but it seems like this is something that should just be in the sql package itself.

I'm happy to do the work, submit the PR etc. just curious if there is any object to adding it and why.

**Comment by bradfitz** [comment] 2016-04-10 00:16
In Go, interfaces are defined only when they're accepted, not when they're provided. You can define your own Querier interface if you need one, no?

**Comment by james-lawrence** [comment] 2016-04-10 00:24
correct but seems like everyone defines it seems kind of silly. but fair point.

**Comment by bradfitz** [comment] 2016-04-10 00:33
Does everybody define it? Got examples? If there's evidence that it's widely used, we can add it.

**Comment by james-lawrence** [comment] 2016-04-10 00:58
off the top of my head:
1) https://github.com/Masterminds/squirrel/blob/e21b13aa472ea70fe2e8172d668d1fee4028d2fd/squirrel.go#L31
2) https://github.com/jmoiron/sqlx/blob/master/sqlx.go#L75
3) https://github.com/knq/xo - generates it for you.
```
// XODB is the common interface for database operations that can be used with
// types from public.
//
// This should work with database/sql.DB and database/sql.Tx.
type XODB interface {
    Exec(string, ...interface{}) (sql.Result, error)
    Query(string, ...interface{}) (*sql.Rows, error)
    QueryRow(string, ...interface{}) *sql.Row
}
```
4) https://bitbucket.org/jatone/genieql (my project) would love to have it available in the runtime, if it isn't added here, I'll just make it something genieql will auto generate the code for people.

I'm sure I could did up more examples potentially. squirrel has a few forks that most likely also use them.

**Comment by bradfitz** [comment] 2016-04-10 03:13
All those interfaces look different, though. It doesn't look like there's necessarily consensus.

I think it's fine if people writing funcs like QueryRowWith (https://github.com/Masterminds/squirrel/blob/master/squirrel.go#L110) define the exact interface they want.

**Comment by james-lawrence** [comment] 2016-04-10 12:37
I disagree, almost all of them roll up to allow you to use TX and DB interchangably, I think the differences are superficial.

**Comment by bradfitz** [comment] 2016-04-10 14:44
Well, we have `testing.TB` already, so there's precedent for something like this. I'm less worried if we define it like that and rather than have N small interfaces, we have 1 larger interface which is the intersection of all TX and DB methods, plus a private method so nobody else can implement that type, preventing types other than TX or DB (like we did with testing.TB).

**Comment by danilobuerger** [comment] 2016-04-10 14:54
A case i frequently run into is if i want to use DB and TX (created from that DB) interchangeably on prepared statements:

```
stmt, err := db.Prepare("SELECT ...")
```

If i want to use that with a TX from `db.Begin`, i will have to pass it through `tx.Stmt`. It would be super nice if such an interface would include `Stmt(stmt *Stmt) *Stmt` so that something like this becomes possible:

```
func Foo(q Querier) {
	q.Stmt(stmt).Query()
}
```

**Comment by james-lawrence** [comment] 2016-04-10 14:59
@danilobuerger Stmt would likely satisify the querier interface.

**Comment by bradfitz** [comment] 2016-04-10 15:11
@james-lawrence, Stmt doesn't take the query. It only takes `args ...interface{}`. 

@danilobuerger, there is only one thing in the `database/sql` package with a `Stmt(stmt *Stmt) *Stmt` method. Why would it go into an interface?

**Comment by james-lawrence** [comment] 2016-04-10 15:13
crap missed that part =)

**Comment by bradfitz** [comment] 2016-04-10 15:15
The fact that Stmt is different from DB and Tx gives me pause. If we add an interface which is the intersection of DB and Tx, it seems to discourage use of prepared statements, if things in the ecosystem start requiring a `Querier` interface.

It almost makes me think the interface should be of `Stmt`'s signature instead, but then we'd need something like a `WithQuery(query string) QueryExecer` method on `DB` and `Tx` instead. (at which point the interface is named `QueryExecer` instead of `Querier` because `Exec` is also in the intersection of methods).

Anybody want to try that route and send a CL?

**Comment by danilobuerger** [comment] 2016-04-10 15:20
@bradfitz sorry, i didn't add that: `Stmt` should be on DB as well in that case. Otherwise it would be cumbersome to use:

```
func Foo(q Querier) {
	s := stmt
	if tx, ok := q.(*sql.Tx); ok {
		s = tx.Stmt(s)
	}
	q.Stmt(s).Query()
}
```

**Comment by james-lawrence** [comment] 2016-04-10 15:58
@bradfitz I'll be happy to take a stab at it and see how it works in practice.

**Comment by kardianos** [comment] 2016-10-08 21:48
We should be careful here. We just defined a bunch of new Context methods and there is debate if Tx should have a nesting Tx or RollbackTo and SavePoint methods. This would strongly flavor such an interface.

**Comment by kardianos** [comment] 2016-11-28 18:56
This is a duplicate of #14468.

**Closed by kardianos** 2016-11-28 18:56 UTC
