### ISSUE TITLE
encoding/json: add Decorder.Buffer(buf []byte) function?

### ISSUE THREAD

**Issue by runner-mei** [golang/go#30864] opened 2019-03-15 14:57 UTC
to fix https://github.com/golang/go/issues/7709 and https://github.com/golang/go/issues/7067, https://github.com/golang/go/issues/9706

add Decorder.Buffer([]byte) function, it like bufio.Buffer(buf []byte, max int)
benefits:
1. set buf size and reduce memory alloc
2. zero copy is possible and as follow:

````go
type InplaceReader int
func (p *InplaceReader) Read([]byte) (int, error) {
	if *p == 0 {
		return 0, io.EOF
	}
	ret := int(*p)
	*p = 0
	return ret, io.EOF
}

......

        n, remoteAddr, err := socket.ReadFromUDP(bs)
        if err != nil {
           return err
        }
	r := InplaceReader(len(bs))
	decoder := json.NewDecoder(&r)
        decoder.UseNumber()   // json.Unmarshal() is unsupport UseNumber
	decoder.Buffer(bs)
        decoder.Decode(&x)
````

**Comment by katiehockman** [comment] 2019-03-19 15:10
It looks like all of those issues were closed as Working As Intended. It is preferable to keep all of the context for an issue and a proposed fix within the context of a single issue, rather than creating a new one.

**Closed by katiehockman** 2019-03-19 15:10 UTC
