### ISSUE TITLE
unable to go get golang.org/x/text/language

### ISSUE THREAD

**Issue by komuw** [golang/go#27796] opened 2018-09-21 14:13 UTC
### What version of Go are you using (`go version`)?
go version go1.11 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```bash
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hey/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hey/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/tmp/mydir/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p5/56z0g6pj6dq0njc1n6wccz4r0000gn/T/go-build190704247=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?
```bash
mkdir -p /tmp/mydir && \
cd /tmp/mydir && \
go mod init mydir && \
export GO111MODULE=on && go get -v -u golang.org/x/text/language
```

### What did you expect to see?
`golang.org/x/text/language` to be downloaded and entry added to `go.mod`

### What did you see instead?
```bash
Fetching https://golang.org/x/text/language?go-get=1
Parsing meta tags from https://golang.org/x/text/language?go-get=1 (status code 200)
get "golang.org/x/text/language": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/language?go-get=1
get "golang.org/x/text/language": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
go: finding golang.org/x/text/language latest
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
get "golang.org/x/text": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text?go-get=1
Fetching https://golang.org/x?go-get=1
Parsing meta tags from https://golang.org/x?go-get=1 (status code 200)
Fetching https://golang.org?go-get=1
Parsing meta tags from https://golang.org?go-get=1 (status code 200)
go get golang.org/x/text/language: no matching versions for query "latest"
```

**Comment by komuw** [comment] 2018-09-21 14:14
@gopherbot please add modules

**Comment by komuw** [comment] 2018-09-21 14:15
The command;  
`export GO111MODULE=on && go get -u github.com/golang/text/language` 
works.

**Comment by bcmills** [comment] 2018-09-22 02:49
Likely a duplicate of #27238. What happens if you run `go clean -modcache`?

**Comment by komuw** [comment] 2018-09-24 09:33
However the following worked:

`sudo rm -rf ~/go/pkg/mod/  && export GO111MODULE=on && go get -v -u golang.org/x/text/language`

**Comment by komuw** [comment] 2018-09-24 09:34
@bcmills thanks for helping. 
I'll leave it upto you whether to leave this open or close it in favor of https://github.com/golang/go/issues/27238

**Comment by bcmills** [comment] 2018-09-25 13:30
Thanks for the info. Let's treat this as a dup of #27238.

**Closed by bcmills** 2018-09-25 13:30 UTC
Labels: NeedsInvestigation, WaitingForInfo, modules
