### ISSUE TITLE
cmd/compile: incorrect and duplicate error for invalid string conversion

### ISSUE THREAD

**Issue by griesemer** [golang/go#21979] opened 2017-09-22 13:12 UTC
https://play.golang.org/p/nqGlIR42-9

produces:

tmp/sandbox179252628/main.go:4:12: cannot convert 1 to type string
tmp/sandbox179252628/main.go:4:12: cannot convert 1 (type float64) to type string

The first error is incorrect (1 can be converted to string, but not 1.0); it's also not necessary. The 2nd error would be sufficient.

**Comment by frikkasoft** [comment] 2017-09-22 15:22
I am interested in contributing to Go - is this a good issue for a first-time contributor?

**Comment by griesemer** [comment] 2017-09-22 19:18
Yes and no. Yes because I suspect the actual fix might be small (a missing check somewhere); no because it requires digging into the compiler internals which can be daunting.

That said, why don't you give it a shot and see how far you get. Send any CLs to me (gri) or mdempsky, please. Thanks.

**Comment by kshvmdn** [comment] 2017-09-22 21:02
Duplicate of #20812? Does this reproduce on tip?

**Comment by frikkasoft** [comment] 2017-09-22 21:07
Thanks, I will take a look at this over the weekend/early next week.

**Comment by odeke-em** [comment] 2017-09-23 00:53
I can conform that @kshvmdn's CL https://go-review.googlesource.com/46912 fixed the double error printing issue
<img width="524" alt="screen shot 2017-09-22 at 6 49 56 pm" src="https://user-images.githubusercontent.com/4898263/30768579-dc14cfb8-9fc6-11e7-91d7-e25cf19bb195.png">

However, there is a change in error message, it now says `1 (type untyped number)` instead of `1` or `1 (type float64)`.

**Comment by kshvmdn** [comment] 2017-09-23 02:51
Thanks for the confirmation, @odeke-em!

Unfortunately, as discussed in the CL, I couldn't seem to find a way of adding more relevant type information to the first error message. Maybe @frikkasoft, @griesemer, or someone else will be able to find a better solution.

**Comment by odeke-em** [comment] 2017-09-23 02:57
@kshvmdn thanks for the CL and fix btw. So in regards to relevant information to that type, perhaps this helper that I added in https://go-review.googlesource.com/c/25156/ could help out with that message https://github.com/golang/go/blob/6872a8e1c9904af5f6c23e42e01b027c8cd1c813/src/cmd/compile/internal/gc/typecheck.go#L2752-L2771

**Comment by kshvmdn** [comment] 2017-09-23 03:18
@odeke-em, cool, I wasn't aware of this function!

So this change:

```diff
--- a/src/cmd/compile/internal/gc/const.go
+++ b/src/cmd/compile/internal/gc/const.go
@@ -408,7 +408,7 @@ func convlit1(n *Node, t *types.Type, explicit bool, reuse canReuseNode) *Node {
 bad:
        if !n.Diag() {
                if !t.Broke() {
-                       yyerror("cannot convert %L to type %v", n, t)
+                       yyerror("cannot convert %v (type %v) to type %v", n, sigrepr(n.Typ()), t)
                }
                n.SetDiag(true)
        }
```

results in the message saying `1 (type number)` instead of `1 (type untyped number)`. Is this preferred or would it be better to include the untyped information?

**Comment by odeke-em** [comment] 2017-09-23 06:09
Thanks for trying it out @kshvmdn, in this case, I'll defer to @mdempsky and @griesemer but IMHO I'd fly with `type number` rather than `type untyped number`

**Comment by griesemer** [comment] 2017-09-25 09:20
My apologies for not checking at tip myself before filing this. That said, the error is still misleading: `string(1)` is valid; `string(1.0)` is not. Ideally the fact that the argument is a floating-point constant shows up in the error message.

**Comment by griesemer** [comment] 2018-05-31 05:40
Inaccurate error message, but we do get an error message. Not urgent.

**Comment by mdempsky** [comment] 2019-09-06 22:55
Reopening this, because I reverted it with CL 193977 (e6ba19f).

To summarize the current standing of the issue, given

    const _ = string(1.0)

we currently report:

    cannot convert 1 (untyped number) to string

Like [@griesemer pointed out](https://github.com/golang/go/issues/21979#issuecomment-331825112), this is a vague and somewhat misleading error message: it's okay to convert untyped integers to string, but not untyped floats. Unfortunately, the error message doesn't disambiguate the two.

CL 191079 attempted to fix this by changing it to report:

    cannot convert 1 (float64) to string

However, this is technically incorrect: 1's type is not float64, but "untyped float constant". (Admittedly though, the difference is probably irrelevant to many Go programmers.)

go/types correctly reports "untyped float constant", and cmd/compile should do the same.

**Closed** 2019-09-09 22:13 UTC
Labels: NeedsFix, help wanted
