### ISSUE TITLE
cmd/go: test -cover should print the total module coverage

### ISSUE THREAD

**Issue by opennota** [golang/go#49917] opened 2021-12-02 10:16 UTC
`go test -cover ./...` only shows package coverages, which makes it impossible to show a meaningful coverage badge on gitlab.com (for example) if the module contains multiple packages.

<pre>
$ go version
go1.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xxx/.cache/go-build"
GOENV="/home/xxx/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/xxx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xxx/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/home/xxx/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/home/xxx/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2605339784=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`go test -cover ./...`

### What did you expect to see?

In addition to the package coverage, also the total module coverage.

### What did you see instead?

Only the coverage by package:

```
ok      gitlab.com/opennota/mt  1.010s  coverage: 59.1% of statements
ok      gitlab.com/opennota/mt/jsonutil 0.003s  coverage: 81.6% of statements
?       gitlab.com/opennota/mt/yandex-util      [no test files]
```

**Comment by seankhliao** [comment] 2021-12-02 10:23
Duplicate of #24570

**Closed by seankhliao** 2021-12-02 10:23 UTC
