### ISSUE TITLE
encoding/gob: data missing while encoding an empty *string

### ISSUE THREAD

**Issue by xtudouh** [golang/go#22287] opened 2017-10-16 09:08 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.3

### Does this issue reproduce with the latest release?
yes
### What operating system and processor architecture are you using (`go env`)?
linux/amd64
### What did you do?
https://play.golang.org/p/3akEQ76r55

### What did you expect to see?
dest.B should be ""
### What did you see instead?
nil

**Comment by cznic** [comment] 2017-10-16 10:01
[Basics](https://golang.org/pkg/encoding/gob/#hdr-Basics)
> ... Pointers are not transmitted, but the things they point to are transmitted; that is, the values are flattened. ...

[Encoding Details](https://golang.org/pkg/encoding/gob/#hdr-Encoding_Details)
> ... If a field has the zero value for its type (except for arrays; see above), it is omitted from the transmission. ...

It is working as intended/documented. (*string -> string, string == "" -> not encoded.)

**Comment by gbbr** [comment] 2017-10-16 13:29
Seems like @cznic is right, this is working as intended. Closing.

**Closed by gbbr** 2017-10-16 13:29 UTC
