### ISSUE TITLE
Go 1.5 periodic big GC pauses

### ISSUE THREAD

**Issue by kolesnevg** [golang/go#12478] opened 2015-09-03 16:08 UTC
Hi go Team, when i used go 1.4 my GC looks http://joxi.ru/Vm6yyL6tLON8rZ
when i use go 1.5 first time GC pauses is really fantastic - less than 1 million ns, but sometimes i see that picture http://joxi.ru/52a11b5CpLww20
i tried profile cpu and memory, but did not see anything strange, could you advice what else i can check to fix that problem.

Thank you

**Comment by hallas** [comment] 2015-09-03 16:24
To fix your problem shouldnt you be looking at the code that caused the GC spike? I don't think 1.5GC is supposed to stop larger garbage collections completely.

**Comment by ianlancetaylor** [comment] 2015-09-03 16:30
CC @RLH @aclements

**Comment by kolesnevg** [comment] 2015-09-03 17:15
@hallas My app is simple web server that gets tasks and process them in external goroutine, i developed it on 1.4 and i did not get so big pauses, but when i just rebuild it with 1.5 i get 10,20-50 sec pauses.
Also at the screenshots application is in "sleep" mode - not process any tasks, and as you can see at moment when GC caused spike application do not allocate new memory, than is why i think may be new GC algoritm has some new rules that i should follow.
Most part data in my app is stored in [][10]int64, most big slice hash 120 000 elements.

(and sorry for my English)

**Comment by hallas** [comment] 2015-09-03 18:07
@kolesnevg Sorry about that I misread your chart :-) I see now. My bad.

**Comment by RLH** [comment] 2015-09-03 18:08
Can you run it with
GODEBUG=gctrace=1 turned on and capture the output? This will let us know
if the GC is the culprit.
Also what is the machine/OS and is anything else going on on the machine.
The only other time I've
seen a situation like this is when the app is inactive and the OS decides
to take all of the apps resources
away leaving the app with very some small part of a single CPU.

**Comment by kolesnevg** [comment] 2015-09-03 19:17
> Can you run it with
> GODEBUG=gctrace=1 turned on and capture the output? This will let us know
> if the GC is the culprit.

I will try, thank you

> Also what is the machine/OS and is anything else going on on the machine.
> The only other time I've
> seen a situation like this is when the app is inactive and the OS decides
> to take all of the apps resources
> away leaving the app with very some small part of a single CPU.

It was five times, first time on my develop laptop 
"14.1.0 Darwin Kernel Version 14.1.0: Tue Jul 14 11:13:11 CEST 201; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64"

and other times on digitalocean vm  
"3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux"

**Comment by RLH** [comment] 2015-09-03 19:51
The other situation where we saw these types of performance graphs was
in fact on a cloud service and we root caused it to cloud service VM
starving the application of resources.

I'd be willing to attribute it to that except for the laptop sighting.
Let's focus on
laptop sighting.

**Comment by kolesnevg** [comment] 2015-09-03 20:23
After 40 minutes work on my laptop http://joxi.ru/bmoooLxfzRzRmy
logs here https://yadi.sk/i/_1efKAP2irdJg
app use GC at start 30-40 sec, and then it rests after line 
"2015/09/03 21:29:21 READY TO WORK :)"

**Comment by bradfitz** [comment] 2015-09-03 20:26
Don't call `runtime.GC()` directly. That does a stop-the-world GC currently.

See the docs: http://golang.org/pkg/runtime/#GC : 

```GC runs a garbage collection and blocks the caller until the garbage collection is complete.
It may also block the entire program.
```

**Comment by RLH** [comment] 2015-09-03 20:30
Do you have any runtime.GC() calls in your code? The comment in the trace
log that says GC Forced indicates that you do. If so try removing them,
they do a stop the world GC which can easily take many seconds.

**Comment by kolesnevg** [comment] 2015-09-03 20:33
No, i do not use it directly
i have this for testing but already 2-3 week it's commented
on this screenshot search results in LiteIDE http://joxi.ru/1A5bbd5uL9d1rE

**Comment by bradfitz** [comment] 2015-09-03 20:35
Where is your code which prints `GC forced`? That's not Go saying that.

**Comment by kolesnevg** [comment] 2015-09-03 20:38
It's not in my project, i searched in my GOPATH and there are no results http://joxi.ru/RmzXX19FEpyVAO

**Comment by kolesnevg** [comment] 2015-09-03 20:40
Also here https://github.com/golang/go/issues/12026 also exists line "GC forced", so it's not my

**Comment by hallas** [comment] 2015-09-03 20:44
https://github.com/golang/go/blob/d57f03730265c4677ab2ec1ad74cf8cbf592f798/src/runtime/proc.go#L155

**Comment by bradfitz** [comment] 2015-09-03 21:03
Oh, sorry, I was searching the wrong tree. Indeed. Those look like `sysmon` GCs.

**Comment by bradfitz** [comment] 2015-09-03 21:05
See #11637

**Comment by RLH** [comment] 2015-09-03 21:10
As Brad mentioned #11637 <https://github.com/golang/go/issues/11637> appears
to be the issue. The GC culprits are firing every 120 seconds which is
further indication that this is the issue.

We are working on it.... Thanks for your help.


On Thu, Sep 3, 2015 at 4:44 PM, Christoffer Hallas <notifications@github.com

**Comment by kolesnevg** [comment] 2015-09-03 21:12
Thank you everybody for answers, and thank you Rick for you work ;)

**Comment by bradfitz** [comment] 2015-09-03 21:15
Closing as dup.

**Closed by bradfitz** 2015-09-03 21:15 UTC
