### ISSUE TITLE
debug/buildinfo: 64kB of buildinfo length is not enough for some huge project

### ISSUE THREAD

**Issue by JasonChen233** [golang/go#62043] opened 2023-08-15 12:48 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.20.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes. The max length is still 64kB

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xxx/.cache/go-build"
GOENV="/home/xxx/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/xxx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xxx/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn|direct"
GOROOT="/opt/tools/go1_20"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/opt/tools/go1_20/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/xxx/go/src/huge_project/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3822352286=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you expect to see?
I expect to get the full buildinfo, incluing the go version and the mod info
<pre>
go version -m huge_project
huge_project: go1.20.5
        path	github.com/huge_project
	mod	github.com/huge_project	(devel)
	dep	AAA	v0.0.1	h1:x23cltx3xSv+bLJFh6F2vJ1hvdpypzBox7qyKlL1aoE=
	dep	BBB	v0.0.1	h1:5e4ybxb+2Ta35MWJWWj5p0OczRIusN229h8TYfjkSdA=
         .....
</pre>
### What did you see instead?
go version command only print version info
<pre>
go version -m huge_project
huge_project: go1.20.5
</pre>

### More information
I tried to debug the go version -m command, and found that in func readRawBuildInfo, the max read length is set to 64kB, 
```
        // src/debug/buildinfo/buildinfo.go:144
        // Read the first 64kB of dataAddr to find the build info blob.
	// On some platforms, the blob will be in its own section, and DataStart
	// returns the address of that section. On others, it's somewhere in the
	// data segment; the linker puts it near the beginning.
	// See cmd/link/internal/ld.Link.buildinfo.
	dataAddr := x.DataStart()
	data, err := x.ReadData(dataAddr, 64*1024)
```
then it ran to this branch
```
        // src/debug/buildinfo/buildinfo.go:144
        if data[15]&2 != 0 {
		vers, data = decodeString(data[32:])
		mod, data = decodeString(data)
	} 
```
and this project has a buildinfo more than 64kB, so decodeString return an empty string.
```
// src/debug/buildinfo/buildinfo.go:228
func decodeString(data []byte) (s string, rest []byte) {
	u, n := binary.Uvarint(data)
	if n <= 0 || u >= uint64(len(data)-n) {
		return "", nil
	}
	return string(data[n : uint64(n)+u]), data[uint64(n)+u:]
}
```
So in the end it only print the version info.

I also tried to change the max length from 64kB to 128kB, and recompiled the go tool, then the go version -m can print out the build info correctly.

Can we change the max length from 64kB to 128kB or 256kB? Is there any risk to do so?

**Comment by seankhliao** [comment] 2023-08-15 13:05
Duplicate of #61644

**Closed by seankhliao** 2023-08-15 13:05 UTC
Labels: NeedsDecision
