### ISSUE TITLE
fmt: Printf arguments escape to heap

### ISSUE THREAD

**Issue by golang101** [golang/go#19720] opened 2017-03-26 13:31 UTC
package main

	import "fmt"

	func main() {
		var a = []int{}
		fmt.Println(a) // a escapes to heap
	}

It looks it is caused by the pp struct in print.go which holds the printed arguments and pp values are referenced by other heap values. This can be avoided.

	type pp struct {
		buf buffer

		// arg holds the current item, as an interface{}.
		arg interface{}

		// value is used instead of arg for reflect values.
		value reflect.Value
		
		...
	}

**Comment by mvdan** [comment] 2017-03-26 14:20
I'm not familiar with the compiler and the `fmt` package enough to say whether this should or could be fixed. But my undesrtanding is that in general you should not use `fmt` in hot paths where an allocation or `interface{}` work is not acceptable.

**Comment by ALTree** [comment] 2017-03-26 14:39
This is #8618 I believe.

**Comment by golang101** [comment] 2017-03-26 15:03
This is not related to interface. Following code doesn't make the input arguments escape.

	package main

	func f(a interface{}){
		switch a.(type) {
		case int:
			println("int")
		case []int:
			println("[]int")
		}
	}

	func main() {
		var x = []int{0, 1, 2}
		
		f(x)
		f(x[0])
	}

**Comment by golang101** [comment] 2017-03-26 15:08
@mvdan, I use log package quite often. The log package warps the fmt functions. So I hope the fix is good to optimize log functions.

**Comment by mvdan** [comment] 2017-03-26 15:27
I'm just surprised to see that the performance of `log` is cause of concern. Or is this just out of curiosity?

**Comment by bradfitz** [comment] 2017-03-26 15:43
I'll keep this open as a long-term meta bug about escape analysis, but small examples are generally more actionable.

**Comment by randall77** [comment] 2017-03-26 16:06
Analyzing `fmt` routines to know that the arguments don't escape is hard.  The callgraph is
```
 Println
 Fprintln
 doPrintln
 printArg
 handleMethods
```
`handleMethods` will call the `Format`, `GoString`, `String`, or `Error` methods on the passed-in type.  Escape analysis doesn't know what those functions will do, so their arguments escape.  That escape propagates all the way up to Println.
```
package main

import "fmt"

type A []int

var sink A

func (a A) String() string {
	sink = a
	return "foo"
}
func main() {
	a := []int{}
	fmt.Println(A(a))
}
```
`a` escapes!

The only way I see to fix this is to have type-dependent escape analysis.  I don't see that happening any time soon.

**Comment by rasky** [comment] 2017-03-26 18:15
`fmt.Sprint()` was being cited as the "final litmus test" for escape analysis by @dvyukov in his document:
https://docs.google.com/document/d/1CxgUBPlx9iJzkz9JWkb6tIpTe5q32QDmz8l0BouG0Cw/preview

**Comment by golang101** [comment] 2017-03-27 02:24
@mvdan 

> I'm just surprised to see that the performance of log is cause of concern. 

yes, sometimes, it is.

Another bad side effect is these functions change what it measure when it participate.
For example, I want to check how much memory is allocated on stacks and heap, but the results of the fmt functions affect the query results.

**Comment by golang101** [comment] 2017-03-27 02:24
@mvdan 

> I'm just surprised to see that the performance of log is cause of concern. 

yes, sometimes, it is.

Another bad side effect is these functions change what they measure when they participate.
For example, I want to check how much memory is allocated on stacks and heap, but the results of the fmt functions affect the query results.

**Comment by bronze1man** [comment] 2017-03-27 07:59
Is it easier to write something like //go:escapesArgToHeap , then put it before the function body?
When you know that something can be escapes heap, I think you can just tell the compiler to do that  with import "unsafe" package.

**Comment by robpike** [comment] 2017-03-27 18:14
I am pretty sure this is a dup of #8618. The counterexample listed above is all in one package, which is a much easier problem. #8618 requires escape analysis across a package boundary.

**Comment by randall77** [comment] 2017-03-28 22:54
Yes, I confirm duplicate of #8618.

**Closed by randall77** 2017-03-28 22:54 UTC
Labels: LongTerm, Performance
