### ISSUE TITLE
sync/WaitGroup: new feature WaitWithTimeout

### ISSUE THREAD

**Issue by gozoro** [golang/go#69285] opened 2024-09-05 12:20 UTC
Hi!
I would like to have a `WaitWithTimeout` function in the standard `sync/WaitGroup` structure.

Example:

```go
package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"
)

func main() {

	wg := &WaitGroupTimeout{}
	ctx, cancel := context.WithCancel(context.Background())

	var gracefulStopChan = make(chan os.Signal, 1)

	signal.Notify(gracefulStopChan, syscall.SIGTERM, syscall.SIGINT)

	go func() {
		sig := <-gracefulStopChan

		log.Printf("Caught sig: %+v\n", sig)
		log.Println("Application graceful shutdown begin...")

		// Shutdown

		cancel()
		if ok := wg.WaitWithTimeout(10 * time.Second); !ok {
			log.Println("Force shutdown by timeout")
		}
		log.Println("Application graceful shutdown finished")
		os.Exit(1)

	}()

	log.Println("APP start")

	wg.Add(1)
	go func() {
		defer wg.Done()
		for {
			select {
			case <-ctx.Done():
				//time.Sleep(4 * time.Second)
				for {
					// failed shutdown process or closes something resource
				}
				log.Println("Break the process 1")
				return
			case <-time.After(1 * time.Second):
				log.Println("Process 1")
			}
		}
	}()

	wg.Add(1)
	go func() {
		defer wg.Done()
		for {
			select {
			case <-ctx.Done():
				time.Sleep(5 * time.Second)
				log.Println("Break the process 2")
				return
			case <-time.After(1 * time.Second):
				log.Println("Process 2")
			}
		}
	}()

	wg.Wait()
}

// I would not like to transfer this code from one project to another
type WaitGroupTimeout struct {
	sync.WaitGroup
}

// WaitWithTimeout returns the value "true" when  the [WaitGroup] counter is zero.
// And returns the value "false" when the wait is completed by timeout.
func (wg *WaitGroupTimeout) WaitWithTimeout(timeout time.Duration) bool {

	timeoutChan := time.After(timeout)
	waitChan := make(chan struct{})

	go func() {

		wg.Wait()
		close(waitChan)
	}()

	select {
	case <-timeoutChan:
		return false
	case <-waitChan:
		return true
	}
}

```

**Comment by seankhliao** [comment] 2024-09-05 12:35
Duplicate of #40916

**Closed by seankhliao** 2024-09-05 12:35 UTC

**Comment by zigo101** [comment] 2024-09-05 15:48
It is easy to do this with an additional `time.Timer`.

**Comment by gozoro** [comment] 2024-09-06 06:20
I do this in one line `wg.WaitWithTimeout(10 * time.Second)`. How to put your `time.Timer` into one function?

**Comment by zigo101** [comment] 2024-09-06 14:53
Certainly, you can't do it in one line.
Programming with channels is fun, why to lose the fun? :D
I mean it is fun to write the code in your first comment.
