### ISSUE TITLE
testing: go test fails with -race and test that calls flag.Parse() (go 1.13)

### ISSUE THREAD

**Issue by thaJeztah** [golang/go#34073] opened 2019-09-04 13:20 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build162773325=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Go 1.13 regression: `go test -race` fails if test calls `flag.Parse()` and additional test-flags are provided

### Steps to reproduce:

```bash
mkdir 113_regression && cd 113_regression

cat > repro_test.go <<EOF
package main

import "flag"
import "testing"

func init() { flag.Parse() }

func TestHello(t *testing.T) {}
EOF
```

On Go 1.12

```bash
go get golang.org/dl/go1.12.9 && go1.12.9 download

go1.12.9 test -race -test.parallel 8

# PASS
# ok  	_/go/113_regression	1.009s
```

On Go 1.13, running the test fails

```bash
go get golang.org/dl/go1.13 && go1.13 download

go1.13 test -race -test.parallel 8

# flag provided but not defined: -test.parallel
# Usage of /tmp/go-build008991056/b001/113_regression.test:
# exit status 2
# FAIL	_/go/113_regression	0.008s
```

The problem looks related to calling `flag.Parse()`. Trying an example on Go 1.13 on a test without `flag.Parse()`

```bash
cat > repro_test.go <<EOF
package main

import "testing"

func TestHello(t *testing.T) {}
EOF


go1.13 test -race -test.parallel 8

# PASS
# ok  	_/go/113_regression	1.009s
```

**Comment by ALTree** [comment] 2019-09-04 13:26
From the release notes:

> Testing flags are now registered in the new Init function, which is invoked by the generated main function for the test. As a result, testing flags are now only registered when running a test binary, and **packages that call flag.Parse during package initialization may cause tests to fail**. 

https://tip.golang.org/doc/go1.13#testing

**Comment by bcmills** [comment] 2019-09-04 14:00
Duplicate of #31859

**Closed by bcmills** 2019-09-04 14:00 UTC
Labels: NeedsInvestigation

**Comment by thaJeztah** [comment] 2019-09-04 14:35
Thanks! Missed that one, and fixed it in my code 👍
