### ISSUE TITLE
proposal: database/sql: allow driver-specific transaction options

### ISSUE THREAD

**Issue by rittneje** [golang/go#29847] opened 2019-01-20 23:07 UTC
Problem: In SQLite, there are three transaction behaviors to choose from when starting a transaction - deferred, immediate, or exclusive. However, there is no way to say which one to use via the existing `Begin` or `BeginTx` methods in the database/sql package. And since this is a SQLite-only concept, it would seem strange to make "transaction behavior" a field of the `sql.TxOptions` struct.

I propose adding a new field for driver-specific transaction options to `sql.TxOptions` (and `driver.TxOptions`).
```go
type TxOptions struct {
    ...
    DriverOptions interface{}
}
```

The user could then supply an options struct from their driver package, as in the following hypothetical example:
```go
tx, err := db.BeginTx(ctx, &sql.TxOptions{
    DriverOptions: &sqlite3.TxOptions{
        Behavior: sqlite3.BeginImmediate,
    },
})
```

From a compatibility standpoint, one potential issue is that existing drivers that already implement `driver.ConnBeginTx` would not know to evaluate this new `DriverOptions` field, so they would allow through potentially invalid input. Then, when that driver gets updated to actually evaluate the new field, it would start returning an error, breaking existing programs. However, it would seem silly for someone to use a driver options struct that isn't supported by their driver package, so this may be an unlikely issue in practice. At worst, yet another optional interface could be added to the database/sql/driver package.

**Comment by kardianos** [comment] 2019-01-21 04:47
Duplicate of https://github.com/golang/go/issues/19981

**Closed by kardianos** 2019-01-21 04:47 UTC
Labels: Proposal
