### ISSUE TITLE
x/website: Broken link on case study page

### ISSUE THREAD

**Issue by fflewddur** [golang/go#55291] opened 2022-09-20 22:25 UTC
https://go.dev/solutions/#case-studies includes a link to https://tech.target.com/infrastructure/2018/06/18/Recommending-GoLang-at-Target.html, which returns a 404. I was unable to find a different URL for this article on Target's tech blog; it may no longer be available. If that's the case, we should remove this link.

**Comment by seankhliao** [comment] 2022-09-20 22:34
Duplicate of #49960

**Closed by seankhliao** 2022-09-20 22:34 UTC
Labels: website
