### ISSUE TITLE
go does not report error for exec.Command when the file does not exist

### ISSUE THREAD

**Issue by dongweigogo** [golang/go#23437] opened 2018-01-13 09:16 UTC
go 1.8.4

In running an exec.Command against files, Go does not report any error when the file does not exist. A simple example as below:

``

        cmd:=exec.Command("grep", "abc", "test.txt")     //actually, "test.txt" does not exist
        so,err1:=cmd.StdoutPipe()
        fmt.Println(err1)
        cmd.Start()
        buf,err2:=ioutil.ReadAll(so)
        fmt.Println(string(buf), err2)
        cmd.Wait()

``
Both err1 and err2 are nil, and no error is shown. It looks like the program runs successfully, but actually not.

**Comment by davecheney** [comment] 2018-01-13 09:23
Go does not report any error because you are ignoring the error from `cmd.Start()` and `cmd.Wait().

I am going to close this issue as this appears to be a request for support, not a bug report. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

**Closed by davecheney** 2018-01-13 09:23 UTC

**Comment by dongweigogo** [comment] 2018-01-13 09:34
@davecheney , well, the cmd.Start() still does not report any error, but cmd.Wait() does. It looks weird, why do we just report it at the begining?

**Comment by as** [comment] 2018-01-13 21:38
If `cmd.Start` doesn't report an error when the file doesn't exist, are there _any_ conditions in which is reports an error?

**Comment by bradfitz** [comment] 2018-01-13 22:49
@as, yes, Start returns an error if the process fails to start. Wait returns an error if the process fails to finish. It doesn't know that `test.txt` is a filename vs any other arbitrary string. It's just an argument to grep, for grep to deal with.

Let's move discussion to golang-nuts.

**Comment by as** [comment] 2018-01-14 01:18
@bradfitz 

My bad, the title of the issue made me think that `file` was referring to the `grep` binary itself.
