### ISSUE TITLE
cmd/go: factor out internal/semver, internal/modfile etc

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#28101] opened 2018-10-09 17:18 UTC
The parsing functionality found in the modfile package is useful to external tools
(for example for tools that wish to edit go.mod files in ways not supported by `go mod edit`, such as [gohack](https://github.com/rogpeppe/gohack)).

The semver functionality found in semver is not quite the same as other semver packages, and is likewise useful for external packages.

There are already at least two repositories containing copies of these packages [1](https://github.com/rogpeppe/go-internal) [2](https://github.com/marwan-at-work/vgop). It would be nice if there was a commonly recognized place for them.

**Comment by rsc** [comment] 2019-04-30 17:12
Closing as duplicate of #31761 (assuming something like that is accepted and implemented).

**Closed** 2019-05-01 11:02 UTC
Labels: FeatureRequest, GoCommand, NeedsInvestigation, modules
