### ISSUE TITLE
test: heapsampling.go is flaky

### ISSUE THREAD

**Issue by bradfitz** [golang/go#13098] opened 2015-10-29 19:43 UTC
heapsampling.go is flaky.

It needs to either be fixed to not be flaky, or be deleted.

/cc @aclements @dr2chase @dvyukov and @rauls5382 (who appears to be the first and only person to ever touch that file when it was added in https://go-review.googlesource.com/14590 for #12620)

**Comment by rauls5382** [comment] 2015-10-29 21:38
I'll take a look. Please assign it to me.

**Comment by bradfitz** [comment] 2015-10-30 02:23
I can't assign you until you're a "member of a team", so I did that. See if you can assign yourself now after accepting. That said, we don't use the "Assignee" all the time. Just saying you're working on it is enough.

**Comment by bradfitz** [comment] 2015-10-30 17:05
Assigned.

**Comment by bradfitz** [comment] 2015-10-30 18:31
Example failure:

https://storage.googleapis.com/go-build-log/0f9f239a/windows-amd64-gce_a28c2438.log
```
# go run run.go -- heapsampling.go
exit status 1
panic: main.alloc want total count > 0 && <= 307200000, got 0

goroutine 1 [running]:
main.checkAllocations(0xc102f5c000, 0x9, 0x3b, 0x5338c0, 0xa, 0x186a0, 0xc08202bef0, 0x3, 0x3)
	C:/workdir/go/test/heapsampling.go:82 +0x578
main.main()
	C:/workdir/go/test/heapsampling.go:34 +0x164
exit status 2

FAIL	heapsampling.go	2.465s
2015/10/29 14:50:56 Failed: exit status 1
```

**Comment by rauls5382** [comment] 2015-11-02 22:20
I don't seem to be able to reproduce this on linux.

In any case, getting a 0 means that no samples were collected in main.alloc , which shouldn't happen with the default sampling rates. We will collect a minimum of 1 sample every ~10MB, and the loop in that function allocates 180MB.

Is it possible that sampling is disabled on this platform, or that the sampling rate has been changed? Or could there be background goroutines allocating memory? How flaky is the testcase, does it fail frequently?

**Comment by bradfitz** [comment] 2015-11-02 22:22
@aclements might have some stats on flakiness and where it occurs.

**Comment by aclements** [comment] 2015-11-02 22:51
Seems to happen just about everywhere except Linux, but always on amd64:

[2015-10-06T07:05:51-3e6334e/openbsd-amd64-gce56](http://build.golang.org/log/fcc29751c221513de9d9b6a645ce0ffc9d8f240b)
[2015-10-10T00:49:00-2d5601d/dragonfly-amd64](http://build.golang.org/log/622c9583b6e4bfda4c8b229538115bc46a82bd6c)
[2015-10-12T22:35:31-8dd52cf/dragonfly-amd64](http://build.golang.org/log/77978e8cc57d7a58ed76a621d66125a1f0961f47)
[2015-10-14T00:46:21-a6f69b3/dragonfly-amd64](http://build.golang.org/log/89359a7670dde5d7c27f200942494f94d6806757)
[2015-10-19T09:58:15-5d88323/dragonfly-amd64](http://build.golang.org/log/9c20053bd47f9166f0456eb1eede2ce8a20f6e5a)
[2015-10-20T15:48:49-7d2c6eb/dragonfly-amd64](http://build.golang.org/log/8ffd10f4920f64d4117e119b015f0d0cd9f60ff8)
[2015-10-20T15:48:49-7d2c6eb/freebsd-amd64-gce93](http://build.golang.org/log/c6d175f682432d5302436470c0308d0479bac687)
[2015-10-20T22:11:11-7628521/freebsd-amd64-gce93](http://build.golang.org/log/8d1788ea388a34d116e81cb4ce06d9ffd5863131)
[2015-10-21T04:21:16-b60c820/dragonfly-amd64](http://build.golang.org/log/1e506754bc30614d41b298b2682134cd6123ebab)
[2015-10-21T16:26:34-a42f668/dragonfly-amd64](http://build.golang.org/log/f71535ec1d0ad8c29ae98328663cb978f3b3c9e4)
[2015-10-21T18:37:45-c279250/windows-amd64-gce](http://build.golang.org/log/6c58cc5feba66cd5df15adf54f06c46a162d7072)
[2015-10-23T17:30:09-3abb844/windows-amd64-gce](http://build.golang.org/log/ef52aebbed1b3ddb17abbb31578004ba89f32720)
[2015-10-23T20:07:52-9238cbd/dragonfly-amd64](http://build.golang.org/log/c939abf58e57f72bdbf2b54b071466415290a269)
[2015-10-28T05:53:28-492a62e/dragonfly-amd64](http://build.golang.org/log/c726fcd133ddcd99f91d26ac2f9d5b5924fb3ee7)
[2015-10-29T16:25:37-ab7e82e/dragonfly-amd64](http://build.golang.org/log/a3baf376900aeea228843b99a9da5e45702b1090)
[2015-10-29T16:25:37-ab7e82e/freebsd-amd64-gce93](http://build.golang.org/log/509fd21de367c0ad8778c490a12dcce74459d7f8)
[2015-10-29T19:44:59-6f8a665/dragonfly-amd64](http://build.golang.org/log/335f661625f274df4101879f0013990d216839d6)
[2015-10-30T18:40:31-ddbc802/freebsd-amd64-gce93](http://build.golang.org/log/3af876cdb42922709111d07ac714eb873752a534)
[2015-10-30T20:35:20-729abfa/dragonfly-amd64](http://build.golang.org/log/ea1959dba0bab3304994b84996930da55ee42460)
[2015-10-30T20:35:20-729abfa/windows-amd64-gce](http://build.golang.org/log/aed17d73dd72153e5c4673416b3b9676f9e707cd)

And, since I've been playing with the statistics of flaky tests, I can tell you that the probability that a commit will fail this test is 6.5% since it started happening. Assuming the failure is Bernoulli (which looks about right, but I don't have my automatic test working yet :), there's better than even odds that the bug was introduced within 10 commits of the first failure, but you have to go back 44 commits to get to 95% odds.

**Comment by rauls5382** [comment] 2015-11-11 22:02
Austin, I've been trying to look into this further but even on a windows
machine I haven't been able to reproduce (after reenabling the testcase).
Would you have any suggestions as to how can I reproduce it for further
investigation? Are there any machines I could access where the problem
reproduces?

Thanks,

Raúl E Silvera | SWE | rsilvera@google.com | *408-789-2846*

**Comment by aclements** [comment] 2015-11-12 14:40
It took an overnight run, but I was able to reproduce this four times in ~150 runs on freebsd-amd64-gce93 for commit ddbc802 (the last known failure) with the following:

```
git checkout ddbc802 && \
VM=$(gomote create freebsd-amd64-gce93) && \
gomote push $VM && \
gomote run $VM ./go/src/make.bash && \
gomote run -e GOPATH=/tmp/workdir/x $VM /bin/sh -c 'PATH=$PWD/go/bin:$PWD/x/bin:$PATH; go get golang.org/x/tools/cmd/stress && cd go/test && stress -failure "main.alloc want" go run run.go'
```

while running the following to keep the VM up

```
while sleep 300 && gomote ping user-austin-freebsd-amd64-gce93-0; do true; done
```

It seems that running heapsampling.go in isolation isn't sufficient. The perturbation caused by the tests running concurrently seems necessary.

I'm going to try adding some more debugging information to the failure and will run it again.

**Comment by aclements** [comment] 2015-11-12 14:56
Note that, even on Linux, we get only 2 to 3 samples from main.alloc, but it seems like the intent is that we should be getting roughly ((1024+512+256) * 100000) / (512 * 1024) = 341.

**Comment by aclements** [comment] 2015-11-12 15:48
Sorry, I was completely misreading my debug output. There are >300 samples from main.alloc on Linux.

**Comment by aclements** [comment] 2015-11-12 16:01
Here's the contents of the memory profile and its symbolization for a failure. It's very interesting that we in fact have samples for the lines in main.alloc, but their byte and object counts are 0.

```
# go run run.go -- heapsampling.go
exit status 1
{0 0 0 0 [4199461 4198675 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} main.alloc:56 main.main:34 runtime.main:137 runtime.goexit:1809
{0 0 0 0 [4199498 4198675 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} main.alloc:57 main.main:34 runtime.main:137 runtime.goexit:1809
{0 0 0 0 [4199420 4198675 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} main.alloc:55 main.main:34 runtime.main:137 runtime.goexit:1809
{768 768 3 3 [4199141 4198444 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} main.allocInterleaved:47 main.main:30 runtime.main:137 runtime.goexit:1809
{2048 2048 4 4 [4199063 4198444 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} main.allocInterleaved:45 main.main:30 runtime.main:137 runtime.goexit:1809
{15360 15360 15 15 [4198981 4198444 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} main.allocInterleaved:43 main.main:30 runtime.main:137 runtime.goexit:1809
{64421888 64421888 983 983 [4198940 4198444 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} main.allocInterleaved:42 main.main:30 runtime.main:137 runtime.goexit:1809
{64421888 64421888 983 983 [4199104 4198444 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} main.allocInterleaved:46 main.main:30 runtime.main:137 runtime.goexit:1809
{62586880 62521344 955 954 [4199022 4198444 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} main.allocInterleaved:44 main.main:30 runtime.main:137 runtime.goexit:1809
panic: main.alloc want total count > 0 && <= 307200000, got 0

goroutine 1 [running]:
main.checkAllocations(0xc822ca6000, 0x9, 0x3b, 0x50a800, 0xa, 0x186a0, 0xc822cbfec0, 0x3, 0x3)
        /tmp/workdir/go/test/heapsampling.go:98 +0x79f
main.main()
        /tmp/workdir/go/test/heapsampling.go:34 +0x1cc
exit status 2

FAIL    heapsampling.go 2.439s
```

**Comment by aclements** [comment] 2015-11-12 16:16
Here's a second sample because I have it, but I don't think there's anything different about it:

```
# go run run.go -- heapsampling.go
exit status 1
{0 0 0 0 [4199498 4198675 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} 
main.alloc:57 main.main:34 runtime.main:137 runtime.goexit:1809
{0 0 0 0 [4199461 4198675 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} 
main.alloc:56 main.main:34 runtime.main:137 runtime.goexit:1809
{0 0 0 0 [4199420 4198675 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} 
main.alloc:55 main.main:34 runtime.main:137 runtime.goexit:1809
{256 256 1 1 [4199141 4198444 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} 
main.allocInterleaved:47 main.main:30 runtime.main:137 runtime.goexit:1809
{6144 6144 12 12 [4199063 4198444 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} 
main.allocInterleaved:45 main.main:30 runtime.main:137 runtime.goexit:1809
{19456 19456 19 19 [4198981 4198444 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} 
main.allocInterleaved:43 main.main:30 runtime.main:137 runtime.goexit:1809
{67960832 67960832 1037 1037 [4198940 4198444 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} 
main.allocInterleaved:42 main.main:30 runtime.main:137 runtime.goexit:1809
{67633152 67567616 1032 1031 [4199104 4198444 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} 
main.allocInterleaved:46 main.main:30 runtime.main:137 runtime.goexit:1809
{71761920 71761920 1095 1095 [4199022 4198444 4368464 4543105 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]} 
main.allocInterleaved:44 main.main:30 runtime.main:137 runtime.goexit:1809
panic: main.alloc want total count > 0 && <= 307200000, got 0

goroutine 1 [running]:
main.checkAllocations(0xc8376c6000, 0x9, 0x3b, 0x50a800, 0xa, 0x186a0, 0xc8376dfec0, 0x3, 0x3)
        /tmp/workdir/go/test/heapsampling.go:98 +0x79f
main.main()
        /tmp/workdir/go/test/heapsampling.go:34 +0x1cc
exit status 2

FAIL    heapsampling.go 7.956s
```

**Comment by aclements** [comment] 2015-11-12 16:34
I've found the cause. The byte and object counts are only updated at a GC, though the buckets are created eagerly. Hence, if a GC happens part way through `allocInterleaved`, but then doesn't happen after we start calling `main.alloc`, we'll see the buckets but they won't contain any counts.

I can reliably reproduce the failure on Linux with `GOGC=10000 go run heapsampling.go`.

One possible solution is to call `runtime.GC()` at the top of the test's `getMemProfileRecords`. I've sent https://go-review.googlesource.com/16846 with this fix.

**Closed** 2015-11-12 16:59 UTC
Labels: Testing
