### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by wsy998** [golang/go#61780] opened 2023-08-05 14:34 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version 

</pre>
go version go1.20.6 windows/amd64
### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\48940\AppData\Local\go-build
set GOENV=C:\Users\48940\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\global\golang\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\global\golang
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\software\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\software\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.6
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\48940\AppData\Local\Temp\go-build3248466755=/tmp/go-build -gno-record-gcc-switches

### What did you expect to see?
I'd like to see the commands actually executed, i.e. escaped.

### What did you see instead?

The output is not the real command, the real command will be spliced by some symbols will be escaped, and this command does not reflect the escape.

**Comment by seankhliao** [comment] 2023-08-05 14:52
Duplicate of #15566

**Closed by seankhliao** 2023-08-05 14:52 UTC
