### ISSUE TITLE
cmd/go: go get golang/x/tools/...: no matching versions for query "latest"

### ISSUE THREAD

**Issue by wsc1** [golang/go#27215] opened 2018-08-25 11:06 UTC
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

go get golang.org/x/tools/...

#### What did you expect to see?

success

#### What did you see instead?
⎣ ⇨ go get -u -v golang.org/x/tools/...
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
get "golang.org/x/tools": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools?go-get=1
go: finding golang.org/x/tools/... latest
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
get "golang.org/x/tools": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools?go-get=1
go: finding golang.org/x/tools latest
Fetching https://golang.org/x?go-get=1
Parsing meta tags from https://golang.org/x?go-get=1 (status code 200)
Fetching https://golang.org?go-get=1
Parsing meta tags from https://golang.org?go-get=1 (status code 200)
go get golang.org/x/tools/...: no matching versions for query "latest"

#### System details

```
go version go1.11 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/scott/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/scott/Dev/zic"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/scott/Dev/zic/src/zikichombo.org/sound/go.mod"
GOROOT/bin/go version: go version go1.11 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.11
uname -v: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
lldb --version: lldb-902.0.79.7
  Swift-4.1
```

**Comment by rkuska** [comment] 2018-08-28 12:32
Same is happening here:

```
$ go get -u github.com/go-critic/go-critic/...                                                                                                                                                                                                                
go: finding github.com/go-critic/go-critic/... latest
go: finding github.com/go-critic/go-critic latest
go get github.com/go-critic/go-critic/...: no matching versions for query "latest"                                                                                                                                                                                                                
$ go version                                  
go version go1.11 darwin/amd64
```

**Comment by bcmills** [comment] 2018-08-28 13:46
I think the `go` tool is ending up interpreting the `/...` as part of the package path instead of a pattern.

Note that in module mode, `...` patterns match packages in *active* modules, so it doesn't really make sense to `go get -u` one of those patterns unless you've already got those packages in your module dependencies. It would be helpful to see the output of `go list golang.org/x/tools/...` or `go list github.com/go-critic/go-critic/...` before you ran `go get -u`.

**Comment by bcmills** [comment] 2018-08-28 13:47
@ivanalejandro0 I would be surprised if an issue fixable by `go clean -modcache` is the same as the one involving `...` patterns.

**Comment by ivanalejandro0** [comment] 2018-08-28 16:55
> @ivanalejandro0 I would be surprised if an issue fixable by go clean -modcache is the same as the one involving ... patterns.

Yeah, I agree.
My problem didn't involve any `...`, but @wsc1 said that with "`GO111MODULE=off` works ok", so I figured it may be worth mentioning.

**Comment by mastertinner** [comment] 2018-09-10 11:44
I can confirm @rkuska's issue with go-critic and have it documented here: https://travis-ci.org/mastertinner/clong

**Comment by thepudds** [comment] 2018-10-07 17:53
I've seen this error in the wild, given some packages include `go get foo/...` in their install instructions.

That said, the official documentation seems to claim that this works.  In particular, `go get golang.org/x/perf/cmd/...` is actually cited as example in the official documentation for 'Module aware go get', but if you try that example from the doc, it fails with error `no matching versions for query "latest"`:

From https://tip.golang.org/cmd/go/#hdr-Module_aware_go_get

> Note that package patterns are allowed and are expanded after resolving the module versions. For example, 'go get golang.org/x/perf/cmd/...' adds the latest golang.org/x/perf and then installs the commands in that latest version.

Here is that example from the doc from scratch:
```
$ mkdir -p /tmp/scratchpad/gogetellipsis
$ cd /tmp/scratchpad/gogetellipsis
$ go mod init example.com/me/hello
$ go get golang.org/x/perf/cmd/...
go: finding golang.org/x/perf/cmd/... latest
go: finding golang.org/x/perf/cmd latest
go: finding golang.org/x/perf latest
go get golang.org/x/perf/cmd/...: no matching versions for query "latest"

```

Not that you can get it to work though if you first do `go get golang.org/x/perf/cmd/benchstat`, and then repeat the exact previously failing command.

Continuing prior example:

```
$ ls $GOPATH/bin/bench* | wc -l
0

# install benchstat first
$ go get golang.org/x/perf/cmd/benchstat
go: finding golang.org/x/perf/cmd/benchstat latest
go: finding golang.org/x/perf/cmd latest
go: finding golang.org/x/perf latest

# previously failing command now works (and also installs benchsave)
$ go get golang.org/x/perf/cmd/...
go: finding golang.org/x/perf latest
go: finding golang.org/x/oauth2 latest
go: finding golang.org/x/oauth2/google latest
go: finding golang.org/x/net/context/ctxhttp latest
go: finding golang.org/x/net/context latest
go: finding golang.org/x/net latest
go: finding cloud.google.com/go/compute/metadata latest
go: finding cloud.google.com/go/compute latest
```

I'm guessing that second example works because `golang.org/x/perf` becomes part of the active modules prior to doing `go get golang.org/x/perf/cmd/...`.

**Comment by bigblind** [comment] 2018-10-26 17:29
Having the same problem with a package providing bindings for v8:

    go get github.com/augustoroman/v8: no matching versions for query "latest"

**Comment by thepudds** [comment] 2018-12-07 10:55
@bcmills any brief thoughts on whether or not this is too big for 1.12 at this point?

Also, it is not clear to me if this is working as designed, vs. a bug.  For example, from my comment above https://github.com/golang/go/issues/27215#issuecomment-427672781: 

> the official documentation seems to claim that this works. In particular, `go get golang.org/x/perf/cmd/...` is actually cited as example in the official documentation for 'Module aware go get', but if you try that example from the doc, it fails with error no matching versions for query "latest"

**Comment by bcmills** [comment] 2018-12-07 15:20
This is still on my radar for 1.12, but depending on the fix will likely slip to 1.13.

**Comment by integrii** [comment] 2018-12-20 09:18
FYI, I am still getting this in 1.12 beta1 and can only make things work if I go back to the gopath.

```
build github.com/Comcast/kuberhealthy/cmd/kuberhealthy: cannot load golang.org/x/crypto/ssh/terminal: cannot find module providing package golang.org/x/crypto/ssh/terminal
```

`go clean -modcache` gives the same error, strangely enough.

`GO111MODULE=off go get -v golang.org/x/crypto/ssh/terminal` works.
`GO111MODULE=on go get -v golang.org/x/crypto/ssh/terminal` does not work with the following error:

```
go get golang.org/x/crypto/ssh/terminal: no matching versions for query "latest"
```

**Comment by subfuzion** [comment] 2019-01-04 03:04
For what it's worth, the following succeeds only *after* the first attempt to get without "..."

```
go get -u golang.org/x/tools
go get -u golang.org/x/tools/...
```

I discovered this when struggling to get go generate to work for go-bindata

```
go get -u github.com/go-bindata/go-bindata
go get -u github.com/go-bindata/go-bindata/...
```

In my case, the first line is necessary for the following to succeed:

```
//go:generate go get github.com/go-bindata/go-bindata
//go:generate go get -u github.com/go-bindata/go-bindata/...
//go:generate go-bindata -pkg $GOPACKAGE -o assets.go -prefix assets/ assets/...
```

Hope this helps anyone else.

**Comment by srinathh** [comment] 2019-02-13 01:07
This breaks the workflow of [installing go from source](https://golang.org/doc/install/source) because [installing additional tools](https://golang.org/doc/install/source#tools) doesn't work if `GO111MODULE=on` has been set. I ran into this when re-installing Go from source and my work around was to turn off the setting first first, install & then turn it back on. While not many folks will run into this, a note should probably be added to the documentation on installing from source noting the issue.

**Comment by mholt** [comment] 2019-03-29 00:21
Commenting to confirm that running `go get` without the `/...` pattern first, then running `go get` _with_ the `/...` pattern works. But I second the earlier comments that this is not in agreement with the documentation.

**Comment by thepudds** [comment] 2019-03-29 01:23
@bcmills @jayconrod Any quick thoughts  on whether a fix for this might be small enough to be a 1.12 back port candidate? 

@mvdan asked a similar question a bit ago in #29363,  which I think might be a duplicate of this one. 

This issue is fairly awkward given the number of readmes out there that use `/...` as part of their installation instructions.  Of course, it might make more sense to wait until 1.13  based on the nature of a fix,  competing priorities, etc.

**Comment by thepudds** [comment] 2019-05-21 21:46
The example I had listed in https://github.com/golang/go/issues/27215#issuecomment-427672781 seems to be fixed in tip now that #29363 is fixed.

Is anyone else seeing an issue here if you try with tip? (`go get golang.org/dl/gotip && gotip download` is a handy way to try with the latest from Go tip).

**Comment by jayconrod** [comment] 2019-05-22 17:23
I think this can be closed after [CL 174099](https://go-review.googlesource.com/c/go/+/174099) and other fixes to `go get` landed. `go get golang.org/x/tools/...` should work now.

Sorry I don't think there was anything in here that could be backported to 1.12. The changes to `go get` semantics were pretty substantial. In general, `go get` in 1.13 in module mode should have similar semantics to `go get` in GOPATH mode.

**Closed by jayconrod** 2019-05-22 17:23 UTC
Labels: WaitingForInfo, modules

**Comment by hexiao04** [comment] 2020-05-18 08:49
so, how to solve this kind of problem?
"no matching versions for query "latest"

**Comment by dmitshur** [comment] 2020-05-18 14:45
@hexiao04 This is an old closed issue. If there is a problem, please file a new issue, and reference this one if you think it's relevant.
