### ISSUE TITLE
Bug with []byte struct field at append slice in for range loop

### ISSUE THREAD

**Issue by jekaspekas** [golang/go#35340] opened 2019-11-04 12:59 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\jekaspekas\AppData\Local\go-build
set GOENV=C:\Users\jekaspekas\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\jekaspekas\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\JEKASP~1\AppData\Local\Temp\go-build176995138=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

[Link on play.golang.org](https://play.golang.org/p/na8Xnq1wVtc)

### What did you expect to see?
<pre>
testList 0: &{F:[4 4] B:[4 4]}
testList 1: &{F:[5 5] B:[5 5]}
testList 2: &{F:[0 0] B:[0 0]}
testList 3: &{F:[1 1] B:[1 1]}
testList 4: &{F:[2 2] B:[2 2]}
testList 5: &{F:[3 3] B:[3 3]}
</pre>

### What did you see instead?
<pre>
testList 0: &{F:[4 4] B:[3 3]}
testList 1: &{F:[5 5] B:[3 3]}
testList 2: &{F:[0 0] B:[3 3]}
testList 3: &{F:[1 1] B:[3 3]}
testList 4: &{F:[2 2] B:[3 3]}
testList 5: &{F:[3 3] B:[3 3]}
</pre>

**Comment by ALTree** [comment] 2019-11-04 15:48
Hi.

This is working as intended. The range variables (in your case, `v`) are not re-allocated at each loop, so if you capture them by pointer (which you are doing, when you store `v[:]`), you'll fill the list with the same element again and again.

To fix this, either iterate on the indices (like in your second loop), or add a `v := v` at the top of the range loop.

I'm closing here, since this is not a bug. If you have further questions, please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions). Thanks!

**Closed by ALTree** 2019-11-04 15:48 UTC
