### ISSUE TITLE
cmd/go/internal/load: -ldflags should be included in buildinfo when -trimpath is set and CGO_ENABLED=0

### ISSUE THREAD

**Issue by capnspacehook** [golang/go#63558] opened 2023-10-15 20:37 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/capnspacehook/.cache/go-build'
GOENV='/home/capnspacehook/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/capnspacehook/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/capnspacehook/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v3'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD=''
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3246179384=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

Built a binary with `CGO_ENABLED=0`, `-trimpath` set and `-ldflags="-s -w -X ..."` set.

### What did you expect to see?

Running `go version -m` on the output binary would include what I set `-ldflags` to at build time.

### What did you see instead?

`-ldflags` was not included in the binarie's build information.

This is somewhat of a regression caused from the fix to https://github.com/golang/go/issues/52372 here: https://github.com/golang/go/blob/bc9dc8d415fc1ecf8d0d63a01dd17b2b60bf4cf3/src/cmd/go/internal/load/pkg.go#L2387-L2398

While I understand the reason this was done, I think `-ldflags` values can always safely be included in binary build information without negatively affecting binary reproducibility if `CGO_ENABLED=0`. In fact it would improve the ease at which others could reproduce pure-Go binaries as more build information would be embedded in binaries when `-trimpath` is set (which is very often for release binaries).

If CGO isn't used, `-extar`, `-extld`, and `-extldflags` shouldn't be set and so including the values of `-ldflags` should be safe without affecting binary reproducibility. If this small change is approved I can take care of this myself.

**Comment by rittneje** [comment] 2023-10-15 21:45
Is this a duplicate of #63432?

**Comment by capnspacehook** [comment] 2023-10-15 22:41
Ah I think it is, thanks.

**Closed** 2023-10-15 22:41 UTC
