### ISSUE TITLE
go run main.go seems not work on v1.21.3

### ISSUE THREAD

**Issue by Guiwoo** [golang/go#64552] opened 2023-12-05 04:30 UTC
### Go version

go version 1.21.3 arm64/darwin

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/guiwoopark/Library/Caches/go-build'
GOENV='/Users/guiwoopark/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/guiwoopark/go/pkg/mod'
GONOPROXY='github.com/a-task/atask_common'
GONOSUMDB='github.com/a-task/atask_common'
GOOS='darwin'
GOPATH='/Users/guiwoopark/go'
GOPRIVATE='github.com/a-task/atask_common'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/guiwoopark/go/go1.21.3'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/guiwoopark/go/go1.21.3/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/h3/v0jyhrkj0hb6c8xctq1psw380000gn/T/go-build1121653416=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

package structure
|- main.go
|- parse.go

[main.go]
package main

func main() {
	timeParse()
}

[parse.go]
package main

import "time"

func timeParse() string {
	t := time.Now()
	return t.Format("2006-01-02")
}

on command line -"go run main.go" - doesn't work "error undefined timeParse"
IDE(GoLand) works well
on command line - "go build" and running compiled file working well both of them

### What did you expect to see?

There's no error if I type on command line "go run main.go"

### What did you see instead?
./main.go:4:2: undefined: timeParse

# command-line-arguments

**Comment by randall77** [comment] 2023-12-05 05:45
Yes, you would have to do `go run main.go parse.go` to make this work. or `go run .` (with a valid `go.mod` file).
Otherwise, how would the build system find `parse.go`?
Closing, as this is working as intended. Reopen if you think otherwise.

**Closed by randall77** 2023-12-05 05:45 UTC

**Comment by Guiwoo** [comment] 2023-12-05 05:49
> Yes, you would have to do `go run main.go parse.go` to make this work. or `go run .` (with a valid `go.mod` file). Otherwise, how would the build system find `parse.go`? Closing, as this is working as intended. Reopen if you think otherwise.

omg what a silly question thanks
