### ISSUE TITLE
proposal: go build static when cgo use libc

### ISSUE THREAD

**Issue by jokemanfire** [golang/go#65297] opened 2024-01-26 07:24 UTC
### Proposal Details

Now I use 'go build ' to compile static program , when the program use cgo(It use some libc fuction), 
I do like this 
`CGO_ENABLED=1 GOOS=linux GOARCH=amd64  CGO_LDFLAGS=“-static” go build -a -v `  
It use libc default , but libc's static link is not static really, it use dynamic library.
May go build point the static flag, It can build static really, use like musl default? 
No need for me to specify like this:
`CGO_ENABLED=1 GOOS=linux GOARCH=amd64 CC=x86_64-linux-musl-gcc CGO_LDFLAGS=“-static” go build -a -v`
It could？

**Comment by seankhliao** [comment] 2024-01-26 08:35
Duplicate of #26492

**Closed by seankhliao** 2024-01-26 08:35 UTC
Labels: Proposal
