### ISSUE TITLE
cmd/go: list errors for import is a program, not an importable package

### ISSUE THREAD

**Issue by andig** [golang/go#61857] opened 2023-08-08 18:53 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/andig/Library/Caches/go-build'
GOENV='/Users/andig/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/andig/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/andig/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/andig/htdocs/evcc/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/sv/rs_453y57xj86xsbz3kw1mbc0000gn/T/go-build977151873=/tmp/go-build -gno-record-gcc-switches -fno-common'
uname -v: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103
ProductName:		macOS
ProductVersion:		13.4.1
ProductVersionExtra:	(c)
BuildVersion:		22F770820d
lldb --version: lldb-1403.0.17.67
Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
</pre></details>

### What did you do?

Install build tools from [`tools.go`](https://github.com/evcc-io/evcc/blob/master/tools.go):

    go install $(go list -f '{{join .Imports " "}}' tools.go)

### What did you expect to see?

No error

### What did you see instead?

`go list` errors:

    tools.go:6:2: import "github.com/dmarkham/enumer" is a program, not an importable package

I realise this might not be a bug per se but it is a change of behavior over go1.20.

**Comment by seankhliao** [comment] 2023-08-08 19:29
note that the `-e` flag is available

**Comment by andig** [comment] 2023-08-08 19:42
Thank you, wasn't even aware of this flag: `-e` works when used with `-f`.

**Comment by bcmills** [comment] 2023-08-08 21:37
Duplicate of #59186

**Closed by bcmills** 2023-08-08 21:37 UTC
Labels: NeedsInvestigation, GoCommand

**Comment by andig** [comment] 2023-08-09 16:57
@bcmills not quite sure why this is marked as duplicate. From what I understand the reasoning is that:
- main packages should never have been allowed by `go list`
- these errors were not consistently reported in the past (and are not reported consistently today or the referenced issue would not be open- although it seems to relate to `-test` only?)
- `-e` allows proceeding anyway to workaround is in place.

Please correct me (only if wrong). Thank you!

**Comment by bcmills** [comment] 2023-08-09 17:15
> - these errors were not consistently reported in the past (and are not reported consistently today or the referenced issue would not be open- although it seems to relate to `-test` only?)

The errors were previously not reported consistently. For some unknown reason, the code changes for `-pgo=auto` in 1.21 cause them to be reported in cases where they were previously not diagnosed.

#59186 is still open because we still don't understand why the errors were previously not reported, and we still don't know whether there are causes where they remain unreported today.

**Comment by nizarennciri** [comment] 2024-01-26 20:45
`
![Screenshot 2024-01-26 212334](https://github.com/golang/go/assets/89226644/c1050db6-37ea-478f-8af4-1c69d25e33a3)
`

**Comment by nizarennciri** [comment] 2024-01-26 21:17
I have the same err and I can fix him ,
