### ISSUE TITLE
Garbage Collection with References Leak

### ISSUE THREAD

**Issue by rphillips** [golang/go#51138] opened 2022-02-10 23:03 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16.13 and 1.17.6
</pre>

### Does this issue reproduce with the latest release?
Yes: 1.17.6

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rphillips/.cache/go-build"
GOENV="/home/rphillips/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/rphillips/work/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rphillips/work/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3509904809=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

[Sample Code on go.dev](https://go.dev/play/p/VVFYA9QPmqQ)
<details>
<summary>Code Snippet</summary>

```golang
package main

import (
	"runtime"
	"testing"
)

func TestReferenceLeakWorks(t *testing.T) {
	type A struct {
		foo int
	}
	type B struct {
		bar *int
	}
	type C struct {
		baz int
	}

	a := &A{foo: 1}
	b := &B{bar: &a.foo}
	c := &C{baz: 2}

	aFinalizerCalled := false
	bFinalizerCalled := false
	cFinalizerCalled := false
	gcCount := 5

	runtime.SetFinalizer(a, func(a *A) {
		t.Log("a finalizer")
		aFinalizerCalled = true
	})

	runtime.SetFinalizer(b, func(b *B) {
		t.Log("b finalizer")
		bFinalizerCalled = true
	})
	runtime.SetFinalizer(c, func(c *C) {
		t.Log("c finalizer")
		cFinalizerCalled = true
	})

	if a.foo != *b.bar {
		t.Error("a.foo should equal *.bar")
	}

	for i := 0; i < gcCount; i++ {
		runtime.GC()
	}

	// double check the contents and mark b.bar as destroyed
	if 1 != *b.bar {
		t.Error("1 should equal *.bar")
	}
	b.bar = nil

	for i := 0; i < gcCount; i++ {
		runtime.GC()
	}

	// mark a as destroyed
	a = nil
	// mark b as destroyed
	b = nil
	// mark c as destroyed
	c = nil

	for i := 0; i < gcCount; i++ {
		runtime.GC()
	}

	if aFinalizerCalled == false {
		t.Error("a finalizer should be called")
	}
	if bFinalizerCalled == false {
		t.Error("b finalizer should be called")
	}
	if cFinalizerCalled == false {
		t.Error("c finalizer should be called")
	}
}

func TestReferenceLeakDoesntWork(t *testing.T) {
	type A struct {
		foo int
	}
	type B struct {
		bar *int
	}

	a := &A{foo: 1}
	b := &B{bar: &a.foo}

	aFinalizerCalled := false
	bFinalizerCalled := false
	gcCount := 5

	runtime.SetFinalizer(a, func(a *A) {
		t.Log("a finalizer")
		aFinalizerCalled = true
	})

	runtime.SetFinalizer(b, func(b *B) {
		t.Log("b finalizer")
		bFinalizerCalled = true
	})

	// double check the contents
	if a.foo != *b.bar {
		t.Error("a.foo should equal *b.bar")
	}

	for i := 0; i < gcCount; i++ {
		runtime.GC()
	}

	// double check the contents and mark b.bar as destroyed
	if 1 != *b.bar {
		t.Error("a.foo should equal *b.bar")
	}
	b.bar = nil

	for i := 0; i < gcCount; i++ {
		runtime.GC()
	}

	// mark a as destroyed
	a = nil
	// mark b as destroyed
	b = nil

	for i := 0; i < gcCount; i++ {
		runtime.GC()
	}

	if aFinalizerCalled == false {
		t.Error("a finalizer should be called")
	}
	if bFinalizerCalled == false {
		t.Error("b finalizer should be called")
	}
}
```
</details>

I am debugging an issue within Kubernetes and the GC appears to be acting strangely due to references. The linked sample contains two functions: `TestReferenceLeakWorks` and `TestReferenceLeakDoesntWork`. The only difference between the two implementations is an additional structure (C) added to `TestReferenceLeakWorks`. The code sets up 2-3 structures with struct (B) including a reference to struct A. I would expect in both test cases to see the A finalizer get called. 

_Note: This issue does not show up in the playground but is reproducible with 1.17.6  and 1.16.13 on x86_64 Linux._

I suspect this is causing a regression within Kubernetes where structures are not being GCed due to the reference being retained.

### What did you expect to see?

I expect in all scenarios that a referenced structure would be GCed.

### What did you see instead?

The 'a' finalizer never gets called in TestReferenceLeakDoesntWork in most cases I have tried. Tuning the GC count does not change the behavior on my machine.

**Comment by cherrymui** [comment] 2022-02-10 23:43
Looks like #46827 . It is not a permanent memory leak, though it is not freed immediately either.

**Comment by rphillips** [comment] 2022-02-10 23:46
Is there a better way to detect if an object can be GCed by the garbage collector?

**Comment by rphillips** [comment] 2022-02-10 23:53
The code I am debugging is creating references to higher level objects, and I suspect the higher level objects are not being GCed.

**Comment by ianlancetaylor** [comment] 2022-02-11 00:37
Issue #46827 is pointing out that it is possible for multiple objects to share a memory allocation, if they are small (total size of all co-located objects 16 bytes or less) and do not contain any pointers.  In the case where the objects share an allocation, they will only be freed when all of them are unreferenced.  So with careful allocation it is possible to have a space leak, but the leak will be less than 16 bytes per leaked object.

It's worth noting that the Go runtime does not guarantee that finalizers will ever be run.  Ideally Go programs should avoid relying on finalizers for correctness.  You can make it more likely that a finalizer will be run by adding a pointer field to the object, even if the pointer is always `nil`.

Closing this issue because this is expected behavior, is not a bug, and there are no current plans to change it.

**Closed by ianlancetaylor** 2022-02-11 00:37 UTC
