### ISSUE TITLE
Inconsistent rounding of floating point

### ISSUE THREAD

**Issue by jeetsang** [golang/go#34815] opened 2019-10-10 09:44 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12.1 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code></summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jitendra/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jitendra/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x8/68sd4h_x0v140qx5jb18mp5c0000gn/T/go-build192220704=/tmp/go-build -gno-record-gcc-switches -fno-common
</pre></details>

### What did you do?
<code>
fmt.Printf("%.1f", 3.85)
fmt.Println()
fmt.Printf("%.1f", 4.85)
</code>

### What did you expect to see?
<code>
3.9

4.9
</code>

### What did you see instead?

<code>
3.9

4.8
</code>

**Comment by ALTree** [comment] 2019-10-10 09:57
The rounding is correct. Neither 3.85 nor 4.85 are exactly representable as IEEE-754 floats, so even if you wrote "3.85" and "4.85" in your code, what you'll really get is the nearest representable float64s, which are:

```
3.850000000000000088817841970012523233890533447265625
4.8499999999999996447286321199499070644378662109375
```

which explains why the first is rounded to .85 and the second to .84.

Closing here, since this is working as intended.

**Closed by ALTree** 2019-10-10 09:57 UTC
