### ISSUE TITLE
cmd/link: assembly files omitted from debug_line section [Debugging]

### ISSUE THREAD

**Issue by aarzilli** [golang/go#25216] opened 2018-05-02 10:44 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

500d79c410f8e9ad762ba318a0a4b05d0d4d1751

### Does this issue reproduce with the latest release?

No

.debug_line does not have any entries for assembly files, this happens because the assembler does not produce pcstmt symbols and writelines needs them.

**Comment by mundaym** [comment] 2018-05-02 10:49
Duplicate of #25191? Might be worth adding your observation there.

**Comment by aarzilli** [comment] 2018-05-02 10:59
@mundaym yes, it does look like a duplicate of that.

**Closed** 2018-05-02 15:59 UTC
