### ISSUE TITLE
x/tools/gopls: stuck on "Setting up workspace: Loading packages..."

### ISSUE THREAD

**Issue by mxpaspa** [golang/go#42255] opened 2020-10-28 15:42 UTC
- go version- 1.15.3
- vs code version 1.50.1
- extension version 0.18.0

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/maxpaspa@ibm.com/Library/Caches/go-build"
GOENV="/Users/maxpaspa@ibm.com/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/maxpaspa@ibm.com/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/maxpaspa@ibm.com/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/maxpaspa@ibm.com/go/src/github.com/redhat-marketplace-operator/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c1/ym_2q3ls1z5gfcylg1dcb_240000gn/T/go-build950413556=/tmp/go-build -gno-record-gcc-switches -fno-c
```

```
    "go.alternateTools": {
        "go-langserver": "gopls"
      },
      "go.languageServerFlags": [
        "serve",
        "-rpc.trace",
        "--debug=localhost:6060",
      ],
      "go.languageServerExperimentalFeatures": {
        "autoComplete": true,
        "documentSymbols": true,
        "findReferences": true,
        "goToDefinition": true,
        "goToTypeDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "rename": true,
        "workspaceSymbols": true,
    },
    "go.formatTool": "goimports",
    "go.autocompleteUnimportedPackages": false,
    "go.buildOnSave": "on",
    "go.vetOnSave": "off",
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
    "go.useLanguageServer": true,
```

### Describe the bug
I upgraded to go 1.15.3, updated golang tools including the Go extension and the extension is stuck on "Loading packages..."

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/18662680/97459892-a0094580-1912-11eb-9328-1496a3b44f9c.png)

**Comment by stamblerre** [comment] 2020-10-28 15:45
Thanks for the report! Can you please share the `gopls` log from when you see this happen? See https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs for instructions on how to capture the log.

**Comment by mxpaspa** [comment] 2020-10-28 15:50
> Thanks for the report! Can you please share the `gopls` log from when you see this happen? See https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs for instructions on how to capture the log.

Thanks for the quick reply. There's nothing in the output inside VS Code. However, I'm serving logs via localhost:6060. Is there anything specific you want there ?

**Comment by stamblerre** [comment] 2020-10-28 20:12
Is there anything more after the `registerCapability`? These requests are part of the `gopls` initialization, so I'd expect to see a bit more here.

**Comment by mxpaspa** [comment] 2020-10-28 20:15
I'm not seeing anything past that: 
![image](https://user-images.githubusercontent.com/18662680/97491663-d48ff800-1938-11eb-9abf-2b5e6fdaa9d1.png)

**Comment by stamblerre** [comment] 2020-10-28 23:04
Thanks for clarifying. A few things to try, suggested by @hyangah:

1) Can you try downgrading your version of the VS Code Go extension to 0.17.x? Does that change anything?
2) Can you try running the "Developer: Open Process Explorer" command to see what `gopls` is doing? You can access the command through the Command Palette (Ctrl + Shift + P).
3) Can you try adding more verbose logging on the `gopls` side? There is a `"verboseOutput"` configuration you can add:

```json5
"gopls": {
     "verboseOutput": true
}
```

4. Can you look in the `gopls` output channel? (Not `gopls (server)`.) These are the client-side logs.

**Comment by mxpaspa** [comment] 2020-10-28 23:16
- here is the output from process explorer:
```
CPU %	Memory (MB)	PID	Name
6	98	1762	code main
4	66	1809	     gpu-process
0	16	1810	     utility
0	66	1851	     shared-process
2	229	1997	     window (/Users/maxpaspa@ibm.com/Library/Application Support/Code/User/settings.json)
0	131	2000	         extensionHost
0	66	2008	             /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=2000
0	49	2013	             electron_node server.js 
0	16	3695	             /Users/maxpaspa@ibm.com/go/bin/gopls -mode=stdio serve -rpc.trace --debug=localhost:6060
99	3441	3699	                 go list -modfile=/var/folders/c1/ym_2q3ls1z5gfcylg1dcb_240000gn/T/go.9a4c4fe73e77b55a9304b88458b00ac8455523fe3e0a9246b1cbcd42034adf7c.443595658.mod -e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin github.com/redhat-marketplace/redhat-marketplace-operator/...
0	49	2001	         watcherService
0	0	3009	         /bin/zsh -l
0	0	3070	             /bin/zsh -l
0	82	3706	     window (Process Explorer)
0	0	3868	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

- I actually tried the previous version of the extension and go, but neither seemed to have an affect.

**Comment by mxpaspa** [comment] 2020-10-28 23:20
am I adding

```
"gopls": {
     "verboseOutput": true
}
```

to settings.json in vscode ? 

In any case there is no output for "gopls"

**Comment by stamblerre** [comment] 2020-10-28 23:29
> am I adding this to settings.json in vscode ?
> 
> ```
> "gopls": {
>      "verboseOutput": true
> }
> ```

Yep, that's correct.

But thanks for the output of the process explorer command. I tried to reproduce with the same repository, and it did take a long time for the packages to be loaded. How long are you waiting before looking at the logs?

**Comment by mxpaspa** [comment] 2020-10-28 23:31
I've let it run for 30 mins minimum and have had it run for up to an an hour. 

How long did it take for you ?

**Comment by stamblerre** [comment] 2020-10-28 23:35
Ah, it only took me a minute or two with a clean module cache. Have you tried "Developer: Reload Window" to try restarting it?

**Comment by mxpaspa** [comment] 2020-10-28 23:47
yea, I've retried restarting the window, a system restart as well...any other ideas ?

**Comment by stamblerre** [comment] 2020-10-28 23:50
One last thing to try might be `go clean -modcache` and then reloading the window.

It does seem like you may have run into something similar to https://github.com/golang/go/issues/42132. I would make sure you kill the `gopls` and `go list` processes above (PIDs 3695 and 3699 from your screenshot above) before reloading.

/cc @heschik

**Comment by mxpaspa** [comment] 2020-10-29 00:11
I tried running the command from process 3699 and it's just never returning, so I think you may be right on the similarity to [:42132](https://github.com/golang/go/issues/42132)
![image](https://user-images.githubusercontent.com/18662680/97509738-7d4e4f80-1959-11eb-9847-e25c55b67e22.png)

**Comment by heschik** [comment] 2020-10-29 16:19
If you can reliably reproduce the problem that's pretty interesting. Please run the command with `-x` and upload the logs. If it hangs for a long time with no output, send it a `SIGQUIT` with `kill -QUIT <pid of "go">` and upload the resulting stack trace too.

cc @bcmills @jayconrod

**Comment by mxpaspa** [comment] 2020-10-29 17:38
@heschik I tried using gopls version 0.5.0 to no avail. `go list ...` still hangs:

With version 0.5.0, the process explorer output
```
CPU %	Memory (MB)	PID	Name
3	98	1574	code main
3	66	1621	     gpu-process
0	16	1623	     utility
0	98	1676	     shared-process
2	246	5276	     window (/Users/maxpaspa@ibm.com/Library/Application Support/Code/User/settings.json)
0	147	5279	         extensionHost
0	82	5287	             /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=5279
0	49	5290	             electron_node server.js 
0	16	6236	             /Users/maxpaspa@ibm.com/go/bin/gopls -mode=stdio serve -rpc.trace --debug=localhost:6060
107	279	6241	                 go list -modfile=/var/folders/c1/ym_2q3ls1z5gfcylg1dcb_240000gn/T/go.9a4c4fe73e77b55a9304b88458b00ac8455523fe3e0a9246b1cbcd42034adf7c.538504595.mod -e -json -compiled=true -test=true -export=false -deps=true -find=false -modfile=/var/folders/c1/ym_2q3ls1z5gfcylg1dcb_240000gn/T/go.9a4c4fe73e77b55a9304b88458b00ac8455523fe3e0a9246b1cbcd42034adf7c.538504595.mod -- ./... builtin
0	49	5280	         watcherService
0	0	5973	         /bin/zsh -l
0	0	6034	             /bin/zsh -l
0	66	6245	     window (Process Explorer)
0	0	6253	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

running comand in terminal: 
`go list -modfile=/var/folders/c1/ym_2q3ls1z5gfcylg1dcb_240000gn/T/go.9a4c4fe73e77b55a9304b88458b00ac8455523fe3e0a9246b1cbcd42034adf7c.538504595.mod -e -json -compiled=true -test=true -export=false -deps=true -find=false -modfile=/var/folders/c1/ym_2q3ls1z5gfcylg1dcb_240000gn/T/go.9a4c4fe73e77b55a9304b88458b00ac8455523fe3e0a9246b1cbcd42034adf7c.538504595.mod -- ./... builtin -x`

killed process of `go list -modfile...`:
```
SIGQUIT: quit
PC=0x7fff6f296882 m=0 sigcode=0

goroutine 0 [idle]:
runtime.pthread_cond_wait(0x19dc0e0, 0x19dc0a0, 0x0)
	/usr/local/Cellar/go/1.15.3/libexec/src/runtime/sys_darwin.go:414 +0x39
runtime.semasleep(0xffffffffffffffff, 0x1040465)
	/usr/local/Cellar/go/1.15.3/libexec/src/runtime/os_darwin.go:63 +0x8d
runtime.notesleep(0x19dbea8)
	/usr/local/Cellar/go/1.15.3/libexec/src/runtime/lock_sema.go:181 +0xe7
runtime.stopm()
	/usr/local/Cellar/go/1.15.3/libexec/src/runtime/proc.go:1910 +0xc5
runtime.findrunnable(0xc000046000, 0x0)
	/usr/local/Cellar/go/1.15.3/libexec/src/runtime/proc.go:2471 +0xa7f
runtime.schedule()
	/usr/local/Cellar/go/1.15.3/libexec/src/runtime/proc.go:2669 +0x2d7
runtime.park_m(0xc000402300)
	/usr/local/Cellar/go/1.15.3/libexec/src/runtime/proc.go:2837 +0x9d
runtime.mcall(0x106a6b6)
	/usr/local/Cellar/go/1.15.3/libexec/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [running]:
	goroutine running on other thread; stack unavailable

rax    0x104
rbx    0x2
rcx    0x7ffeefbff158
rdx    0x8cfc00
rdi    0x19dc0e0
rsi    0x8cfc01008cfd00
rbp    0x7ffeefbff1f0
rsp    0x7ffeefbff158
r8     0x0
r9     0xa0
r10    0x0
r11    0x202
r12    0x19dc0e0
r13    0x16
r14    0x8cfc01008cfd00
r15    0x95a3dc0
rip    0x7fff6f296882
rflags 0x203
cs     0x7
fs     0x0
gs     0x0
```

**Comment by heschik** [comment] 2020-10-29 17:42
Ugh. goroutine 1 is, of course, the one we need. Sorry, but can you run the `go list` command with `GOTRACEBACK=crash` and then kill it again?

Can you check that you don't have any strange symlinks set up, or huge directories inside the module?

**Comment by mxpaspa** [comment] 2020-10-29 17:55
do you run that command with `GOTRACEBACK...` like this ?
```
env GOTRACEBACK=crash go list -modfile=/var/folders ...
```

That gave a long output. Do you want the whole thing ?

**Comment by heschik** [comment] 2020-10-29 18:02
If it succeeded, it's not interesting. That environment setting should allow us to get a full traceback using `kill -QUIT`, but if it doesn't hang there's nothing to see.

**Comment by mxpaspa** [comment] 2020-10-29 18:11
I'm saying when I killed it, it gave a long output...

**Comment by heschik** [comment] 2020-10-29 18:12
Oh. Yes, I want the whole thing, please. Upload it to a gist if it's really huge?

**Comment by mxpaspa** [comment] 2020-10-29 18:18
Take a look: https://gist.github.com/mxpaspa/cac393749787771d5d935d5268875c35

**Comment by mxpaspa** [comment] 2020-10-29 18:25
@heschik I just nuked the repo and cloned again. gopls is working fine now...Sorry if that ruins the test. 

If it starts hanging again, I'll ping you. Thanks for the help.

**Comment by stamblerre** [comment] 2020-10-30 04:25
I'm glad it's working again. It sounds like the deadline suggested in https://github.com/golang/go/issues/42132 might solve the issue of `go list` hanging once, but if it gets into a state where it always hangs, I'm not sure that `gopls` could handle that.

Since things are working again, I'm going to go ahead and close this as a duplicate of https://github.com/golang/go/issues/42132, but please open a new issue if you see this again and can reproduce it.

**Closed by stamblerre** 2020-10-30 04:25 UTC
Labels: Tools, WaitingForInfo, gopls

**Comment by saniales** [comment] 2021-02-26 23:53
> @heschik I just nuked the repo and cloned again. gopls is working fine now...Sorry if that ruins the test.
> 
> If it starts hanging again, I'll ping you. Thanks for the help.

I confirm that this works, people. Do not try to understand this, JUST NUKE AND RECLONE. I wasted 3 hours on this and nobody has a real answer.

just my friendly advice.

**Comment by yury-kozlov** [comment] 2021-04-15 17:13
> > @heschik I just nuked the repo and cloned again. gopls is working fine now...Sorry if that ruins the test.
> > If it starts hanging again, I'll ping you. Thanks for the help.
> 
> I confirm that this works, people. Do not try to understand this, JUST NUKE AND RECLONE. I wasted 3 hours on this and nobody has a real answer.
> 
> just my friendly advice.

Doesn't help. Even when I clone a completely different repo I experience the same issue.

**Comment by stamblerre** [comment] 2021-04-15 21:22
@yury-kozlov: Please see the [Troubleshooting guide](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md) and file an issue if necessary.
