### ISSUE TITLE
io/ioutil: document that TempDir's "prefix" should not contain a slash

### ISSUE THREAD

**Issue by peterstace** [golang/go#10003] opened 2015-02-25 23:05 UTC
What version of Go are you using (go version)?
* go version go1.4.2 windows/amd64

What operating system and processor architecture are you using?
* Windows 7
* AMD64

What did you do?
* Ran the following program using `go run bug.go`. This is a minimal reproduction of the problem -- the real situation occurred when username given by the `os/user` package is embedded within the prefix. On Windows, the username often contains backslashes.

```
package main

import (
	"io/ioutil"
	"log"
)

func main() {
	dir, err := ioutil.TempDir("", `foo\bar`)
	log.Print(dir, err)
}
```

What did you expect to see?
* Any number of things would be fine, e.g.:
* `2015/02/26 10:01:04 C:\Users\petsta\AppData\Local\Temp\foo\bar428871999<nil>`
* `2015/02/26 10:01:04 C:\Users\petsta\AppData\Local\Temp\foo_bar428871999<nil>`
* `2015/02/26 10:01:04 C:\Users\petsta\AppData\Local\Temp\foobar428871999<nil>`

What did you see instead?
* `2015/02/26 09:59:53 mkdir C:\Users\petsta\AppData\Local\Temp\foo\bar288812899: The system cannot find the path specified.`

**Comment by adg** [comment] 2015-02-25 23:09
I think it would fail even if it contained a slash. The prefix is for the file name, not for the path.

**Comment by bradfitz** [comment] 2015-02-25 23:10
> On Windows, the username often contains backslashes.

What does that have to do with this bug?

The documentation for TempDir says nothing about usernames.

Perhaps the documentation of TempDir just needs to say not to put slashes in the prefix.

**Comment by adg** [comment] 2015-02-25 23:11
Maybe it's worth documenting that, but the docs do say the "TempFile creates a new temporary file in the directory dir *with a name beginning with prefix*." A file name shouldn't contain a slash, so the prefix shouldn't contain a slash. Not sure how explicit we should be.

**Comment by davecheney** [comment] 2015-02-25 23:23
> I think it would fail even if it contained a slash. The prefix is for the file name, not for the path.

As well as documenting this we should probably check inside the preamble of the function that the prefix doesn't split according to the native filepath.SplitList and return an error if it does.

**Comment by minux** [comment] 2015-02-25 23:26
On Wed, Feb 25, 2015 at 6:23 PM, Dave Cheney <notifications@github.com>
wrote:

> I think it would fail even if it contained a slash. The prefix is for the
> file name, not for the path.
>
> As well as documenting this we should probably check inside the preamble
> of the function that the prefix doesn't split according to the native
> filepath.SplitList and return an error if it does.
>
If we go to such strength to check for this error, we might be just allow
this use case
by filepath.Split and then MkdirAll.

**Comment by adg** [comment] 2015-02-25 23:31
Yeah, I have actually wanted to do this before.

**Comment by peterstace** [comment] 2015-02-25 23:54
Looking at the documentation again, it looks to me like `ioutil.TempDir` is working as intended (I think the documentation is _probably_ clear enough as well).

**Comment by rsc** [comment] 2015-06-29 14:56
I think this is documented clearly enough and working as intended. If the subdirectory exists I see no reason to reject the call, but I also see no reason to create the subdirectory. It seems fine as is. The original reporter (@peterstace) seems to agree, so closing.

**Closed by rsc** 2015-06-29 14:56 UTC
