### ISSUE TITLE
fmt: scanf behaviour inconsistent with doc specification

### ISSUE THREAD

**Issue by syst3mw0rm** [golang/go#10862] opened 2015-05-15 04:13 UTC
fmt doc says: `Scanf, Fscanf and Sscanf require newlines in the input to match newlines in the format; the other routines treat newlines as spaces.`

The following program spits out error (should not according to doc):
```
package main

import (
	"fmt"
	"log"
)

func main() {
	var a, b int
	_, err := fmt.Sscanf("1\n2", "%d %d", &a, &b)
	if err == nil {
		log.Fatalf("got - %q, expected - %q", err, "unexpected newline")
	}
}

```

on commit https://github.com/golang/go/commit/335e44d265e7b7741b00237f4fcd97a1b80bfd9a

**Comment by robpike** [comment] 2015-06-05 18:08
Duplicate of #9459

**Comment by robpike** [comment] 2015-06-05 21:46
Not a duplicate of #9459, sorry. This is a different issue; fix out for review in https://go-review.googlesource.com/10779

**Closed** 2015-06-12 20:14 UTC
