### ISSUE TITLE
builtin/map: low memory usage

### ISSUE THREAD

**Issue by divinerapier** [golang/go#33112] opened 2019-07-15 08:17 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/fangsihao/Documents/code/go/bin"
GOCACHE="/Users/fangsihao/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/fangsihao/Documents/code/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cn/1_54kmt57s135ygwjyg64p_00000gn/T/go-build225230661=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Test memory usage of map.

### What did you expect to see?

More efficient.

### What did you see instead?

```
$ ./usage2 foo
[foo] entries: 1000000, size: 8000000, heap: 22326928, usage: 0.36

$ ./usage2 bar
[bar] entries: 1000000, size: 8000000, heap: 22325136, usage: 0.36
```

### My Code

``` go
package main

import (
	"fmt"
	"os"
	"runtime"
)

func allocated() uint64 {
	var stats runtime.MemStats
	runtime.GC()
	runtime.ReadMemStats(&stats)
	return stats.Alloc
}

func main() {
	if len(os.Args) == 1 {
		return
	}
	switch os.Args[1] {
	case "foo":
		foo()
	case "bar":
		bar()
	default:
	}
}

func foo() {
	begin := allocated()
	size := 0
	m := make(map[int32]int32)
	for i := 0; i < 1000000; i++ {
		size += 8
		m[int32(i)] = int32(i)
	}
	end := allocated()
	heap := end - begin
	fmt.Printf("[foo] entries: %d, size: %d, heap: %d, usage: %.2f\n", len(m), size, heap, float64(size)/float64(heap))
}

func bar() {
	begin := allocated()
	size := 0
	m := make(map[int32]int32, 1000000)
	for i := 0; i < 1000000; i++ {
		size += 8
		m[int32(i)] = int32(i)
	}
	end := allocated()
	heap := end - begin
	fmt.Printf("[bar] entries: %d, size: %d, heap: %d, usage: %.2f\n", len(m), size, heap, float64(size)/float64(heap))
}
```

### Question

Is there an alternative option to builtin map?

**Comment by randall77** [comment] 2019-07-15 13:43
You would expect a map to require more memory than just the raw data, to allow for a data structure that can do random access.
The current map design should have about a 2x space overhead.  That overhead might be a bit higher for small keys/values, as in your example. Your 0.36 is not surprising.
I'm going to close this issue as working as intended. Without a concrete proposal for how we do better, it isn't actionable.
Feel free to reopen if you have an idea for how to do better.

**Closed by randall77** 2019-07-15 13:43 UTC
