### ISSUE TITLE
x/vgo: unclear error message with gopkg.in

### ISSUE THREAD

**Issue by client9** [golang/go#25121] opened 2018-04-27 05:41 UTC
Doing a `vgo build` on a initial build (no or empty go.mod file) produced an error that is unclear what is being referred to:

```
vgo build

...

vgo: finding github.com/gohugoio/hugo v0.40.1
vgo: parsing downloaded go.mod: go.mod:58: invalid module: gopkg.in/yaml.v2 should be v1, not v2 (v2.2.1)
```

unfortunately I don't know what  or which `go.mod` is being referred to.  None is in the current directory, none is in `gohugoio/hugo` (unless I missed something!)

see also #24099 which talks about `gopkg.in`

```
vgo version
go version go1.10.1 darwin/amd64 vgo:2018-02-20.1
```

but was a fresh `go get -u `as of 2018-04-27

thank you.

n

**Comment by oiooj** [comment] 2018-04-28 07:16
Now module major version use `/` as a separator when parsed modfile, such as `github.com/oiooj/agent/v2`.

Should we add `.` as a separator for compatibility with `gopkg.in` ? such as  `gopkg.in/yaml.v2`  @rsc

**Comment by bcmills** [comment] 2018-04-28 13:43
@oiooj, see golang/vgo@84430ca.

**Comment by ufoscout** [comment] 2018-04-30 16:03
I have the very same issue but I don't understand exactly what is the cause.
Is it because of the convention that the modules from version 2 should be in a "/2" subdirectory?
If yes, shouldn't it only be a "suggested convention"? What happens if I release v2 of a project but I don't want to change the structure of my repository?
I don't see any technical reason why this should be enforced, am I missing something?

**Comment by coyle** [comment] 2018-04-30 19:44
I am getting the same error:

1) Did a fresh `go get -u -v golang.org/x/vgo` as of 3:40est 4/30/2018
2) run `vgo build ./...`
3) vgo: errors parsing go.mod: `invalid module: gopkg.in/yaml.v2 should be v1, not v2 (v2.2.1)`

**Comment by ufoscout** [comment] 2018-05-01 06:32
@bcmills 
> What version of vgo are you seeing that at? The change for gopkg.in versioning is fairly recent.

I did this right now:

```
$ go get -u golang.org/x/vgo

$ vgo version
go version go1.10.1 linux/amd64 vgo:2018-02-20.1

$ vgo build
vgo: finding github.com/gin-contrib/static v0.0.0-20180301030858-73da7037e716
vgo: finding github.com/gin-gonic/gin v1.1.4
vgo: finding github.com/gin-gonic/gin v1.1.4
vgo: parsing downloaded go.mod: go.mod:12: invalid module: gopkg.in/go-playground/validator.v8 should be v1, not v8 (v8.0.0-20160110003959-c193cecd124b)

```

**Comment by klingtnet** [comment] 2018-05-03 13:12
I can confirm the same issue for [go-mgo/mgo](https://github.com/go-mgo/mgo):
```
vgo: parsing downloaded go.mod: go.mod:22: invalid module: gopkg.in/mgo.v2 should be v1, not v2 (v2.0.0-20160818020120-3f83fa500528)
```

**Comment by oiooj** [comment] 2018-05-22 19:28
vgo can not parsed modulepath correctly before. This issue was fixed by CL 112277.

**Comment by client9** [comment] 2018-05-22 19:50
@oiooj 

The ticket is about the vague error message, not the functionality (which does appear to be working now... see #24099 ).  I didn't see any fix for error messages like the following

`vgo: parsing downloaded go.mod: go.mod:58: invalid module: ....`

so it's clear *which* `go.mod` is the problem

**Comment by oiooj** [comment] 2018-05-22 20:06
@client9 Because vgo can not parsed ‘modulepath’ correctly with gopkg.in, so you got the confused error message. No need to fix error message.

**Closed** 2018-06-01 15:45 UTC
Labels: NeedsFix
