### ISSUE TITLE
cmd/bug: gotip bug reports the GOVERSION from the version of go installed in the system

### ISSUE THREAD

**Issue by perillo** [golang/go#45521] opened 2021-04-12 14:31 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.17-16cd770e06 Mon Apr 12 05:12:42 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

This issue reproduces with the current master.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/manlio/.local/bin"
GOCACHE="/home/manlio/.cache/go-build"
GOENV="/home/manlio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE="*.local"
GOMODCACHE="/home/manlio/.local/lib/go/pkg/mod"
GONOPROXY=""
GONOSUMDB="*.local"
GOOS="linux"
GOPATH="/home/manlio/.local/lib/go:/home/manlio/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/manlio/src/contrib/go/go.googlesource.com/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/manlio/src/contrib/go/go.googlesource.com/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/manlio/src/contrib/go/go.googlesource.com/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build830170520=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version devel go1.17-16cd770e06 Mon Apr 12 05:12:42 2021 +0000 linux/amd64
GOROOT/bin/go tool compile -V: compile version devel go1.17-16cd770e06 Mon Apr 12 05:12:42 2021 +0000
uname -sr: Linux 5.11.11-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) release release version 2.33.
gdb --version: GNU gdb (GDB) 10.1
</pre></details>

### What did you do?

`gotip bug`

### What did you expect to see?

The reported `GOVERSION` being `go version devel go1.17-16cd770e06 Mon Apr 12 05:12:42 2021 +0000 linux/amd64`

### What did you see instead?

The reported `GOVERSION` is `go1.16.3`.  This is the version of `go` installed in the system.

`gotip version` reports the correct version.

**Comment by seankhliao** [comment] 2021-04-12 14:37
Duplicate of #43981

**Closed by seankhliao** 2021-04-12 14:37 UTC
