### ISSUE TITLE
cmd/compile: const decl with missing RHS interpreted subtly differently with 1.18

### ISSUE THREAD

**Issue by go101** [golang/go#49157] opened 2021-10-25 23:33 UTC
The current spec says:

> Within a parenthesized const declaration list the expression list may be omitted from any but the first ConstSpec. Such an empty list is equivalent to the textual substitution of the first preceding non-empty expression list and its type if any. Omitting the list of expressions is therefore equivalent to repeating the previous list. 

By the explanation, the following two declarations are equivalent but are not actually (assume they are in local blocks):

```Go
const (
    A = iota
    iota = iota
    B
    C
)
```
```Go
const (
    A = iota
    iota = iota
    B = iota
    C
  )

```

It would be better to change "textual" into "lexical".

**Comment by griesemer** [comment] 2022-06-28 03:03
Looking at this again, it turns out that in Go 1.18 (with the new type checker) we actually get exactly the result as prescribed by the spec. For this [example](https://go.dev/play/p/exqWW_ZVTy-):
```Go
package main

const X = 3

func main() {
	const (
		X = X + X
		Y
	)
	println(X, Y)
}
```
Running with Go 1.18 we get the result 6 and 12, which corresponds exactly to using textually `X + X` for `Y` as the spec prescribes.

Running with 1.17 we get the result 6 and 6, corresponding to a copy of the syntax tree for `X + X` with the variables `X` resolved to the outer `X.

We have two possibilities:

1) The spec is wrong and we have a regression in 1.18.
2) The spec is correct and 1.18 fixed a long-existing bug.

There is a backward-compatibility issue here but this is a pathological situation that is unlikely to occur in correct code in the wild, and since 1.18 is out we have not heard any complaints about this.

Thus I am inclined to go 2) and close this issue.

@ianlancetaylor @robpike @rsc for feedback.

**Comment by griesemer** [comment] 2022-06-28 03:04
Marking as release blocker in case we decided that this needs to be handled as a regression.

**Comment by robpike** [comment] 2022-06-28 04:53
2

**Comment by ianlancetaylor** [comment] 2022-06-28 04:57
Current gccgo prints `6 6`, like Go 1.17.

I'm fine with changing that.

**Closed** 2022-06-28 17:03 UTC
Labels: NeedsDecision, release-blocker

**Comment by griesemer** [comment] 2022-06-28 17:21
@ianlancetaylor Yes, I was planning to do that.
