### ISSUE TITLE
runtime: illegal character U+0023 '#'

### ISSUE THREAD

**Issue by bep** [golang/go#43184] opened 2020-12-14 21:12 UTC
I've seen this in stack traces on test failures both on Windows and MacOS:

```bash
       stack:
          D:/a/godartsass/godartsass/transpiler_test.go:129
            c.Check(result.CSS, qt.Equals, fmt.Sprintf("div {\n  color: #%03d;\n}", num))
          C:/hostedtoolcache/windows/go/1.15.5/x64/src/runtime/asm_amd64.s:1374
            <cannot parse source file: C:/hostedtoolcache/windows/go/1.15.5/x64/src/runtime/asm_amd64.s:5:1: illegal character U+0023 '#'>
```

**Comment by ianlancetaylor** [comment] 2020-12-14 21:34
Are you 100% sure that that message is coming from the Go runtime?  It looks like you are feeding the stack trace into some other program, and the error is coming from that program.

**Comment by bep** [comment] 2020-12-14 21:44
>Are you 100% sure that that message is coming from the Go runtime? 

No I'm not. I just assumed ...

The test framework in question i https://github.com/frankban/quicktest

@frankban or @rogpeppe may know ...

**Comment by rogpeppe** [comment] 2020-12-15 10:07
This looks like an issue with the stack printing code of quicktest indeed. It attempts to print the source to the failed code, including the entire statement where the failure was found, but it assumes that all file names are Go source, which evidently isn't the case here! It should either print the source line without parsing, or (maybe better) just not print the source at all for non-Go files.

I've created https://github.com/frankban/quicktest/issues/86 to track this, and I'll close this issue because the problem isn't to do with the Go runtime itself.

**Closed by rogpeppe** 2020-12-15 10:07 UTC
Labels: WaitingForInfo
