### ISSUE TITLE
gollvm: "at most two relocations per offset are supported" error, during the generation of gen-sysinfo.go

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#42679] opened 2020-11-17 20:16 UTC
I am re-opening this for the third time.

There is still a bug:

https://pipelines.actions.githubusercontent.com/oib3H8xVEpkbM8cVrnJdamNlDcncoD0BGAHRcaZf8LBr47rVSq/_apis/pipelines/1/runs/46/signedlogcontent/3?urlExpires=2020-11-17T20%3A03%3A31.7737280Z&urlSigningMethod=HMACV1&urlSignature=dxHWhVt%2FHIJztgoNkEtN2lwmHVZqWbg8MLVozJV14OY%3D

CC @thanm @cherrymui @ianlancetaylor

**Comment by thanm** [comment] 2020-11-17 20:27
That link doesn't seem to work for me -- I get a page with just

{"count":11,"value":"Uri expired"}

**Comment by advancedwebdeveloper** [comment] 2020-11-17 21:32
Hm, probably I had to share a non-resolved one.

https://github.com/advancedwebdeveloper/clang_test_cpu_features/actions/runs/368658533
https://github.com/advancedwebdeveloper/clang_test_cpu_features/commit/69c1d7b2e4271ee40b2cc1744bdb283d0f9c789d/checks/1413835386/logs - this one should work.
https://github.com/advancedwebdeveloper/clang_test_cpu_features/suites/1517138153/logs

**Comment by thanm** [comment] 2020-11-17 21:37
It looks good to me -- clean build of llvm-goc, the standard libraries, units tests, and clean unit test run. What is the problem?

**Comment by advancedwebdeveloper** [comment] 2020-11-17 23:57
I thought that error disallows to build something for libgo.
What is the cause of that error?
Please elaborate

**Comment by advancedwebdeveloper** [comment] 2020-11-18 00:43
Hm: Clang 9 brought an error:
https://github.com/advancedwebdeveloper/clang_test_cpu_features/commit/dddfcdcde5debe06a08f6b38733b1552c8645bbd/checks/1415489311/logs 
.

>  CMake Error at tools/gollvm/cmake/modules/AddGollvm.cmake:68 (message):
>   C compiler does not support -fsplit-stack
> Call Stack (most recent call first):

**Comment by advancedwebdeveloper** [comment] 2020-11-18 01:27
https://github.com/advancedwebdeveloper/clang_test_cpu_features/commit/1c97f602d6d1cc669ba3ba502bf68e30be5aefd5/checks/1415448433/logs - llvm-godumpspec seams to be involved.

Let me guess: it is related to https://go.googlesource.com/gollvm/+/890acef7d115f5e3855f174aa102c5766809275a , right?

**Comment by thanm** [comment] 2020-11-18 14:21
Yes, this is an llvm-godumpspec problem. No, https://go.googlesource.com/gollvm/+/890acef7d115f5e3855f174aa102c5766809275a is not related, this problem has been around a lot longer than that.

llvm-godumpspec works by reading the DWARF from a C/C++ compiler generated object file, and it uses the LLVM dwarf reading library to do this.  

Turns out I can reproduce the same problem ("error: at most two relocations per offset are supported") just with the existing llvm dwarf dump too. Example:

```
$ ninja llvm-dwarfdump
...
$ cat small.c
#include <sys/time.h>
struct timespec blah;
struct timeval bletch;
$ gcc -g3 -c small.c
$ ./bin/llvm-dwarf-dump small.o
error: At most two relocations per offset are supported
error: At most two relocations per offset are supported
error: At most two relocations per offset are supported
error: At most two relocations per offset are supported
error: At most two relocations per offset are supported
...
$
```

I spent a little while in the debugger looking at this.  It looks like the problem is with the way the reader handles relocations. At this line here: 

https://github.com/llvm/llvm-project/blob/0ec5baa1324d61e79bc21a1307ea52aa43a12352/llvm/lib/DebugInfo/DWARF/DWARFContext.cpp#L1754

it seems to be making the assumption that there is going to be only one debug section of a given name in an object file, which is definitely not true when -g3 is in effect (you get multiple .debug_macro sections).

I'm not sure it's worth pursuing a fix in the LLVM dwarf reader for this. I'll send a CL to use "-g2" instead of "-g3" for the sysinfo.c compile, that should take care of the issue (we don't look at the DWARF macro info in any case).

**Comment by advancedwebdeveloper** [comment] 2020-11-18 14:29
>  USAGE: llvm-godumpspec [options]
>  
>  OPTIONS:
>    --as-secure-log-file-name=<value>       - As secure log file name (initialized from AS_SECURE_LOG_FILE env variable)
>    --asm-macro-max-nesting-depth=<uint>    - The maximum nesting depth allowed for assembly macros.
>    --color                                 - Use colors in output (default=autodetect)
>    --debug-pass=<value>                    - Print PassManager debugging information
>      =Disabled                             -   disable debug output
>      =Arguments                            -   print pass arguments to pass to 'opt'
>      =Structure                            -   print pass structure before run()
>      =Executions                           -   print pass name before it is executed
>      =Details                              -   print pass details when it is executed
>    --disable-ondemand-mds-loading          - Force disable the lazy-loading on-demand of metadata when loading bitcode for importing.
>    --disable-symbolication                 - Disable symbolizing crash backtraces.
>    --dwarf-extended-loc=<value>            - Disable emission of the extended flags in .loc directives.
>      =Default                              -   Default for platform
>      =Enable                               -   Enabled
>      =Disable                              -   Disabled
>    --filter-print-funcs=<function names>   - Only print IR for functions whose name match this for all print-[before|after][-all] and change reporter options
>    -h                                      - Alias for --help
>    --help                                  - Display available options (--help-hidden for more)
>    --help-hidden                           - Display all available options
>    --help-list                             - Display list of available options (--help-list-hidden for more)
>    --help-list-hidden                      - Display list of all available options
>    --import-constants-with-refs            - Import constant global variables with references
>    --import-full-type-definitions          - Import full type definitions for ThinLTO.
>    --info-output-file=<filename>           - File to append -stats and -timer output to
>    --macrotmp=<string>                     - Macros file for *.c file
>    --mark-data-regions                     - Mark code section jump table data regions.
>    --non-global-value-max-name-size=<uint> - Maximum size for the name of non-global values.
>    --object=<string>                       - Object file for *.c file
>    --opt-bisect-limit=<int>                - Maximum optimization to perform
>    --output=<string>                       - Output file to write.
>    --pass-remarks=<pattern>                - Enable optimization remarks from passes whose name match the given regular expression
>    --pass-remarks-analysis=<pattern>       - Enable optimization analysis remarks from passes whose name match the given regular expression
>    --pass-remarks-missed=<pattern>         - Enable missed optimization remarks from passes whose name match the given regular expression
>    --pointersize=<uint>                    - Size of a pointer in bytes for the target architecture of interest. Defaults to host pointer size.
>    --print-after=<value>                   - Print IR after specified passes
>    --print-after-all                       - Print IR after each pass
>    --print-all-options                     - Print all option values after command line parsing
>    --print-before=<value>                  - Print IR before specified passes
>    --print-before-all                      - Print IR before each pass
>    --print-module-scope                    - When printing IR for print-[before|after]{-all} and change reporters, always print a module IR
>    --print-options                         - Print non-default options after command line parsing
>    --print-summary-global-ids              - Print the global id for each value when reading the module summary
>    --propagate-attrs                       - Propagate attributes in index
>    --remarks-section                       - Emit a section containing remark diagnostics metadata. By default, this is enabled for the following formats: yaml-strtab, bitstream.
>    --rng-seed=<seed>                       - Seed for the random number generator
>    --stats                                 - Enable statistics output from program (available with Asserts)
>    --stats-json                            - Display statistics as json data
>    --time-passes                           - Time each pass, printing elapsed time for each on exit
>    --trace                                 - Enable debug trace output.
>    --track-memory                          - Enable -time-passes memory tracking (this may be slow)
>    --use-dbg-addr                          - Use llvm.dbg.addr for all local variables
>    --verify-dom-info                       - Verify dominator info (time consuming)
>    --version                               - Display the version of this program
>    --x86-align-branch=<string>             - Specify types of branches to align (plus separated list of types):
>                                              jcc      indicates conditional jumps
>                                              fused    indicates fused conditional jumps
>                                              jmp      indicates direct unconditional jumps
>                                              call     indicates direct and indirect calls
>                                              ret      indicates rets
>                                              indirect indicates indirect unconditional jumps
> --x86-align-branch-boundary=<uint>      - Control how the assembler should align branches with NOP. If the boundary's size is not 0, it should be a power of 2 and no less than 32. Branches will be aligned to prevent from being across or against the boundary of specified size. The default value 0 does not align branches.
> --x86-asm-syntax=<value>                - Choose style of code to emit from X86 backend:
> =att                                  -   Emit AT&T-style assembly
> =intel                                -   Emit Intel-style assembly
> --x86-branches-within-32B-boundaries    - Align selected instructions to mitigate negative performance impact of Intel's micro code update for errata skx102.  May break assumptions about labels corresponding to particular instructions, and should be used with caution.
> --x86-pad-for-align                     - Pad previous instructions to implement align directives
> --x86-pad-for-branch-align              - Pad previous instructions to implement branch alignment
> --x86-pad-max-prefix-size=<uint>        - Maximum number of prefixes to use for padding

I still think that I should enable tracing.
It would be of help for end-users for other reasons, as well.

**Comment by thanm** [comment] 2020-11-18 14:31
>I still think that I should enable tracing.

If you are talking about "--trace", I don't think that will be helpful.  The trace output is very verbose, and includes a lot of detail that will just confuse users. 

I am preparing a CL that should fix this (get rid of the warning altogether).

**Comment by thanm** [comment] 2020-11-18 15:00
OK, fix submitted. Closing out this issue now...

**Closed by thanm** 2020-11-18 15:00 UTC
Labels: NeedsInvestigation

**Comment by advancedwebdeveloper** [comment] 2020-11-18 15:31
OK, thanks.
Btw I am able to reproduce your simple example, on Ubuntu 20.10, via
> $ llvm-dwarfdump small.o
. Hence the name of the executable - it is a bit different.

https://gist.github.com/advancedwebdeveloper/325f1aa01c86f12680263743343f6bd2 - this is what I am getting.
