### ISSUE TITLE
x/exp/shiny/driver/mtldriver: build failure on darwin-amd64-10_12 builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#34578] opened 2019-09-27 16:28 UTC
The `darwin-amd64-10_12` builder is consistently failing to build `x/exp` (https://build.golang.org/log/dd213135c3b9bf5a7ccbcb8cd459893ebb8c7e38), apparently due to an error in a dependency:

```
# dmitri.shuralyov.com/gpu/mtl
mtl.m:19:23: error: property 'removable' not found on object of type 'id<MTLDevice>'
mtl.m:20:24: error: property 'registryID' not found on object of type 'id<MTLDevice>'
mtl.m:35:39: error: property 'removable' not found on object of type 'id<MTLDevice>'
mtl.m:36:40: error: property 'registryID' not found on object of type 'id<MTLDevice>'
```

As far as I can tell, the failure started at [CL 171025](https://golang.org/cl/171025).

CC @nigeltao

**Comment by dmitshur** [comment] 2019-09-27 16:32
Thanks for the heads up, I'll look into this.

**Comment by dmitshur** [comment] 2019-09-27 16:33
I know where the problem is. The `mtl` package [documentation](https://godoc.org/dmitri.shuralyov.com/gpu/mtl) says:

> Package mtl requires macOS version 10.13 or newer.

But the `darwin-amd64-10_12` builder is macOS version 10.12.

**Comment by dmitshur** [comment] 2019-09-28 15:51
I'd like to fix this by not including exp repo on the `darwin-amd64-10_12` builder:

```diff
 addBuilder(BuildConfig{
 	Name:              "darwin-amd64-10_12",
 	HostType:          "host-darwin-10_12",
 	shouldRunDistTest: macTestPolicy,
-	buildsRepo:        defaultPlusExp,
+	buildsRepo:        default,
 })
```

The exp repo already has other restrictions, such as not being tested against release branches:

```Go
if repo == "exp" {
	// Don't test exp against release branches; it's experimental.
	return false
}
```

macOS 10.12 Sierra was released in 2016, and there have been 2 major releases since (and next month, 10.15 Catalina will be released). It seems reasonable to me to not require code in exp to build with such old operating systems, given it's meant to be experimental.

The exp repo will still have macOS coverage from the 10.14 builder, and it means we'll be using have more macOS builder resources for testing other repos.

**Closed** 2019-09-30 18:37 UTC
Labels: NeedsFix, OS-Darwin
