### ISSUE TITLE
udp bad checksum

### ISSUE THREAD

**Issue by xunleer** [golang/go#23599] opened 2018-01-29 09:36 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8.5/1.9.3 (linux-amd64)

### Does this issue reproduce with the latest release?
yes, 1.9.3 still has this issue

### What operating system and processor architecture are you using (`go env`)?
```bash
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/somebody/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build426968180=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
write a simple UDP client to test:

``` bash
cat client.go
package main
import (
    "fmt"
    "net"
    "bufio"
)

func main() {
    p :=  make([]byte, 2048)
    conn, err := net.Dial("udp", "127.0.0.1:1234")
    if err != nil {
        fmt.Printf("Some error %v", err)
        return
    }
    fmt.Fprintf(conn, "Hi UDP Server, How are you doing?")
    _, err = bufio.NewReader(conn).Read(p)
    if err == nil {
        fmt.Printf("%s\n", p)
    } else {
        fmt.Printf("Some error %v\n", err)
    }
    conn.Close()
}
```

```bash
go run client.go
tcpdump -xxx -vvv -eni lo
```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
The Client send packets with correct checksum

### What did you see instead?

```bash
17:31:06.558648 00:00:00:00:00:00 > 00:00:00:00:00:00, ethertype IPv4 (0x0800), length 103: (tos 0xc0, ttl 64, id 22375, offset 0, flags [none], proto ICMP (1), length 89)
    127.0.0.1 > 127.0.0.1: ICMP 127.0.0.1 udp port search-agent unreachable, length 69
        (tos 0x0, ttl 64, id 22374, offset 0, flags [DF], proto UDP (17), length 61)
    127.0.0.1.22533 > 127.0.0.1.search-agent: [bad udp cksum 0xfe3c -> 0x99b2!] UDP, length 33
        0x0000:  0000 0000 0000 0000 0000 0000 0800 45c0
        0x0010:  0059 5767 0000 4001 247b 7f00 0001 7f00
        0x0020:  0001 0303 96af 0000 0000 4500 003d 5766
        0x0030:  4000 4011 e547 7f00 0001 7f00 0001 5805
        0x0040:  04d2 0029 fe3c 4869 2055 4450 2053 6572
        0x0050:  7665 722c 2048 6f77 2061 7265 2079 6f75
        0x0060:  2064 6f69 6e67 3f
```
seems that the **fe3c** is fixed for the UDP checksum.

**Comment by crvv** [comment] 2018-01-29 10:05
This is not a bug in Go but a feature of the operation system.
Just run `tcpdump -xxx -vvv -eni lo` and you can see a lot of packets with wrong checksum.

http://lkml.iu.edu/hypermail/linux/kernel/0308.1/2205.html

**Comment by xunleer** [comment] 2018-01-29 11:06
this is just a sample, when i sent request to another host, it still has such issue. the checksum is wrong, either.

**Comment by ianlancetaylor** [comment] 2018-01-29 18:24
It is not Go that computes the UDP checksum.  It is the networking layer.  Closing because there is nothing we can change in Go to fix this.

**Closed by ianlancetaylor** 2018-01-29 18:24 UTC

**Comment by crvv** [comment] 2018-01-30 02:05
> this is just a sample, when i sent request to another host, it still has such issue. the checksum is wrong, either.

I think that is another feature of the operating system.

https://wiki.wireshark.org/CaptureSetup/Offloading
