### ISSUE TITLE
Upgrade 1.14 runtime: mlock of signal stack failed

### ISSUE THREAD

**Issue by Icedroid** [golang/go#37496] opened 2020-02-27 03:47 UTC
After upgrade to go 1.14, My program got fatal error.

### What version of Go are you using (`go version`)?

<pre>
$ go 1.14

</pre>

```
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed

runtime stack:
runtime.throw(0x16a2a35, 0xc)
	/usr/local/go/src/runtime/panic.go:1112 +0x72
runtime.mlockGsignal(0xc000602600)
	/usr/local/go/src/runtime/os_linux_x86.go:72 +0x107
runtime.mpreinit(0xc000600700)
	/usr/local/go/src/runtime/os_linux.go:341 +0x78
runtime.mcommoninit(0xc000600700)
	/usr/local/go/src/runtime/proc.go:630 +0x108
runtime.allocm(0xc000069000, 0x173ea58, 0x0)
	/usr/local/go/src/runtime/proc.go:1390 +0x14e
runtime.newm(0x173ea58, 0xc000069000)
	/usr/local/go/src/runtime/proc.go:1704 +0x39
runtime.startm(0x0, 0xc000102901)
	/usr/local/go/src/runtime/proc.go:1869 +0x12a
runtime.wakep(...)
	/usr/local/go/src/runtime/proc.go:1953
runtime.resetspinning()
	/usr/local/go/src/runtime/proc.go:2415 +0x93
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2527 +0x2de
runtime.park_m(0xc0004fc180)
	/usr/local/go/src/runtime/proc.go:2690 +0x9d
runtime.mcall(0x7ffdbba3b908)
	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000340468)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc000340460)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
```

**Comment by agnivade** [comment] 2020-02-27 04:21
Duplicate of https://github.com/golang/go/issues/37436.

**Closed by agnivade** 2020-02-27 04:21 UTC

**Comment by networkimprov** [comment] 2020-02-27 12:49
@Icedroid if you can update your kernel, that should fix it.
