### ISSUE TITLE
compress/gzip: suggestions for doc improvements

### ISSUE THREAD

**Issue by brunetto** [golang/go#11398] opened 2015-06-25 14:11 UTC
Submit here having read the [docs thread on the ML](https://groups.google.com/d/msg/golang-nuts/eV3uNlEFPrc/KeHIjyN2oVEJ).

Reading (for example) [the doc about `NewWriter`](http://golang.org/pkg/compress/gzip/#NewWriter) it is not clear nor trivial to understand how `gzip.NewWriter` could interact with (for example) `bufio.NewWriter`. I found [this gist](https://gist.github.com/mchirico/6147687) that helped me in understanding the right order. 
May be an example like 

```go
package main

import (
	"bufio"
	"compress/gzip"
	"log"
	"os"
)

func main() {
	file, err := os.Create("File.gz")
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	gzipWriter := gzip.NewWriter(file)
	defer gzipWriter.Close()
	defer gzipWriter.Flush()

	writer := bufio.NewWriter(gzipWriter)
	defer writer.Flush()

	writer.WriteString("gzipWriter.go created this file.\n")
}
```

can help.

**Comment by adg** [comment] 2015-06-26 02:11
But that's the wrong order (`buffer -> gzip -> file`). You typically want to buffer writes to the file, not writes to the gzip compressor (it doesn't care how big or small your writes are). Also you shouldn't ignore the errors from `Flush` and `Close`.

What I'm saying is: I agree this should be better documented. I don't think `compress/gzip` is the right place to do it, though.

I think we should add a solid section to the tour about working with the `io` interfaces. Or even a blog post would do.

**Comment by adg** [comment] 2015-06-26 02:13
This is a dupe of #11373

**Closed by adg** 2015-06-26 02:13 UTC

**Comment by brunetto** [comment] 2015-06-26 08:31
Yes, I missed the errors!! Ops!!
But what is the best way to check for the errors with defer???

I thought `gzip` was like a filter, compressing whatever `bufio.Writer` passes when it does it. 
Like an extra layer between the writer and the file object compressing the data. It seems I was wrong, but how can I deal with an application that can write both normal and compressed files depending on the input? If `gzip.Writer` sits on top of `bufio`, I need to change the writer I pass to the function that actually writes when I change the output file type. Or not?

Regarding the docs, my opinion is that some examples should be written both in a tutorial (blog/tour) and in the docs (maybe something shorted/simpler). But this is only my opinion. At least, maybe a link to the tutorial placed in the docs page would help.
