### ISSUE TITLE
go.dev: Displayed README is parent’s, not the current package’s

### ISSUE THREAD

**Issue by clipperhouse** [golang/go#39040] opened 2020-05-13 04:14 UTC
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/clipperhouse/uax29/words?tab=overview
 
### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
 
### Screenshot

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/216057/81770345-09ed7a00-94ae-11ea-90d8-2c30683c4e73.png">
 
### What did you do?
 
Viewed the overview tab for package documentation on pkg.go.dev (URL above)
 
### What did you expect to see?
 
The README for the package `words`
 
### What did you see instead?

The README for the _parent_ package (module) `uax29`

Thanks!

**Comment by julieqiu** [comment] 2020-05-14 16:04
Thanks for the feedback! We are planning to add this feature in an upcoming round of design changes.

Closing as a duplicate of #38513.

**Closed** 2020-05-14 16:04 UTC
Labels: go.dev
