### ISSUE TITLE
x/pkgsite: "/" key should place the cursor on the search bar on the homepage and search page

### ISSUE THREAD

**Issue by jadekler** [golang/go#42819] opened 2020-11-25 00:00 UTC
This is a feature request to add similar behavior as youtube, drive, etc.

**Comment by julieqiu** [comment] 2020-11-30 17:56
This should have already been fixed in https://github.com/golang/go/issues/36805. @jadekler - could you confirm if that is the feature you are requesting?

**Comment by jadekler** [comment] 2020-11-30 19:11
Yes, that is the feature. It appears to have regressed.

**Comment by julieqiu** [comment] 2020-11-30 19:18
The feature works for me on Chrome 86 on macOS (Catalina). Which URL are you looking at and what browser are you using?

**Comment by jadekler** [comment] 2020-11-30 19:27
Ah, it does indeed work on a specific package. Apologies.

However, it does not work on the homepage (pkg.go.dev). Not sure if this bug should be re-purposed to address that specific page?

**Comment by julieqiu** [comment] 2020-11-30 19:28
>  Not sure if this bug should be re-purposed to address that specific page?

Yup! Updated the title.

**Comment by julieqiu** [comment] 2020-12-01 18:35
There's actually already an issue filed for this. Closing as a duplicate of #42704.

**Closed by julieqiu** 2020-12-01 18:35 UTC
Labels: FeatureRequest, NeedsFix, Suggested, help wanted, pkgsite
