### ISSUE TITLE
runtime: tight loops not preempted on wasm

### ISSUE THREAD

**Issue by iansmith** [golang/go#60857] opened 2023-06-17 18:04 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-dbf9bf2 Fri Jun 16 20:47:33 2023 +0000 linux/arm64
</pre>

### Does this issue reproduce with the latest release?
No, not exactly. The above version is "head" of the repo, which is not released yet.  

If running on 1.20 on arm64/darwin, it does not reproduce. Running on the same release but with arm64/darwin it does not reproduce.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre>
This only occurs with `wasm/wasip1` as the GOARCH and GOOS.
</details>

### What did you do?

https://go.dev/play/p/-em2D-ypmWG?v=goprev

The above link works fine on prev release, current release, and dev release in go playground.  The problem only appears when you are on `wasm/wasip1` with 1.21 (head).

The program will not produce any output with either `wasmtime` or `wazero` as the host wasm environment.  If you uncomment the calls to runtime.Gosched() you will see that *one* goroutine is created, so you see one line of output, but not two as you do with go playground.

### What did you expect to see?
What is shown on go playground:
```
in go routine 1
in go routine 2
timeout running program
```

### What did you see instead?
Nothing.

@neelance

**Comment by Nasfame** [comment] 2023-06-18 05:44
I see `in go routine 1` when executing 

```go
package main

import (
	"fmt"
	"runtime"
)

func main() {
	mainBad()
	fmt.Println("end")
}

func mainBad() {
	go func() {
		print("in go routine 1\n")
		for {

		}
	}()
	//uncomment me to see the print above in the output
	runtime.Gosched()
	go func() {
		print("in go routine 2\n")
		for {

		}
	}()
	for {
	}

}
```
I guess  go wasm builds are not optimized to run on multi core processes.

**Comment by Nasfame** [comment] 2023-06-18 05:56
Here is argument - 
Reproducer code - https://go.dev/play/p/1cFQwzBas1D
<img width="579" alt="image" src="https://github.com/golang/go/assets/24226219/c97a122d-74c5-4541-b712-7603b9aca954">

**Comment by bcmills** [comment] 2023-06-20 15:56
See also #36365.

(CC @golang/wasm)

**Comment by mknyszek** [comment] 2023-06-28 19:23
Because Wasm doesn't have threads, there's no way for the runtime to preempt a running goroutine at all. On Wasm, this basically means all yields into the runtime need to be voluntary (channel operation, syscall, memory allocation, etc.).

I'm not sure there's anything we can do here until Wasm supports threads. Closing for now, but let me know if you disagree. Thanks!

**Closed by mknyszek** 2023-06-28 19:23 UTC
Labels: NeedsInvestigation, arch-wasm, compiler/runtime

**Comment by mknyszek** [comment] 2023-06-28 19:27
Others have pointed out to me that it is technically possible for the compiler to insert yield points that say, has the goroutine check itself and how long its been running for on e.g. function entry and loop backedges. But this is likely to be prohibitively expensive on wasm platforms.
