### ISSUE TITLE
x/website: Download Go for Mac undefined (undefined MB)

### ISSUE THREAD

**Issue by darrenparkinson** [golang/go#52322] opened 2022-04-13 08:15 UTC
### What is the URL of the page with the issue?
 
 https://go.dev/doc/install
 
### What is your user agent?
 

 [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
### Screenshot
 

 
 
![image](https://user-images.githubusercontent.com/4262917/163131173-ec9cea4e-1a94-4afe-80ef-f8bfdd4f5803.png)

 
### What did you do?
 

 
 I just want to download Go 1.18 for ARM MacOS
 
### What did you expect to see?
 
 Download button for MacOS which included the file I needed.
 
### What did you see instead?

A download button saying "undefined (undefined MB)"

**Comment by seankhliao** [comment] 2022-04-13 08:26
Duplicate of #52317

**Closed by seankhliao** 2022-04-13 08:26 UTC

**Comment by darrenparkinson** [comment] 2022-04-13 08:28
I don't think this is a duplicate.  Whilst related to https://go.dev/dl, this issue is for https://go.dev/doc/install.  I guess it might get fixed automatically when /dl is fixed?

**Comment by darrenparkinson** [comment] 2022-04-13 08:33
Sure, no problem.  The suggestion [here](https://github.com/golang/go/issues/52317#issuecomment-1097605741) would be useful to provide some information as to why.  Thanks.
