### ISSUE TITLE
encoding/json does not unmarshal my struct properly

### ISSUE THREAD

**Issue by JakubC-projects** [golang/go#63161] opened 2023-09-22 10:43 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.21.1 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/jakubc/.cache/go-build'
GOENV='/home/jakubc/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/jakubc/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/jakubc/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/jakubc/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1641664792=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

https://go.dev/play/p/WpDjZxkzO25

### What did you expect to see?

I expect the `json.Unmarshal` function to succeed and that unmarshalVal would be filled with a value

### What did you see instead?

`json.Unmarshal` returns an error, but it should have worked because `TestType.Prop` does implement the `encoding.TextUnmarshaller` interface

**Comment by seankhliao** [comment] 2023-09-22 11:02
Duplicate of #46516

**Closed by seankhliao** 2023-09-22 11:02 UTC
