### ISSUE TITLE
cmd/go: go clean giving error

### ISSUE THREAD

**Issue by rajender** [golang/go#27310] opened 2018-08-28 15:34 UTC
### What version of Go are you using (`go version`)?
Go1.11

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/backend/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build265255989=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

Ran go clean -modcachce

### What did you expect to see?

Just modcache cleaned. no output.

### What did you see instead?

I see different output in different invocations and an error.

[root@dev backend]# go clean
can't load package: package backend: unknown import path "backend": cannot find module providing package backend
[root@dev backend]# go clean -modcache
can't load package: package backend: unknown import path "backend": cannot find module providing package backend
[root@dev backend]# go clean -modcache
go: finding github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826
go: finding github.com/360EntSecGroup-Skylar/excelize v1.3.0
go: finding github.com/google/uuid v0.0.0-20180827204232-d460ce9f8df2
go: finding github.com/pborman/uuid v0.0.0-20180827223501-4c1ecd6722e8
go: finding github.com/sergi/go-diff v1.0.0
go: finding github.com/stripe/stripe-go v43.0.0+incompatible
go: finding github.com/jtolds/gls v4.2.1+incompatible
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/smartystreets/assertions v0.0.0-20180820201707-7c9eb446e3cf
go: finding github.com/nfnt/resize v0.0.0-20180221191011-83c6a9932646
go: finding github.com/aws/aws-lambda-go v1.6.0
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/aws/aws-sdk-go v1.15.22
go: finding github.com/gopherjs/gopherjs v0.0.0-20180825215210-0210a2f0f73c
go: finding github.com/stretchr/testify v1.2.2
go: finding github.com/smartystreets/goconvey v0.0.0-20180222194500-ef6db91d284a
go: finding googlemaps.github.io/maps v0.0.0-20180819235337-ce25c900cc16
go: finding golang.org/x/net v0.0.0-20180826012351-8a410e7b638d
go: finding golang.org/x/time v0.0.0-20180412165947-fbb02b2291d2
go: finding golang.org/x/text v0.3.0
go: finding github.com/go-ini/ini v1.25.4
go: finding github.com/jmespath/go-jmespath v0.0.0-20160202185014-0b12d6b521d8
can't load package: package backend: unknown import path "backend": cannot find module providing package backend

**Comment by rajender** [comment] 2018-08-28 15:35
@gopherbot add label modules

**Comment by oiooj** [comment] 2018-09-06 15:26
@rajender Could you print your files in `package backend`: 

```
ls ./backend/*
```

**Comment by bcmills** [comment] 2018-11-13 19:01
Closing as a duplicate of #28680.

**Closed by bcmills** 2018-11-13 19:01 UTC
Labels: NeedsInvestigation, modules
