### ISSUE TITLE
x/tools/gopls: editing go.mod breaks workspace load

### ISSUE THREAD

**Issue by seankhliao** [golang/go#41615] opened 2020-09-24 17:31 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 linux/amd64
$ gopls version
golang.org/x/tools/gopls v0.5.0
    golang.org/x/tools/gopls@v0.5.0 h1:XEmO9RylgmaXp33iGrWfCGopVYDGBmLy+KmsIsfIo8Y=
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/arccy/.cache/go-build"
GOENV="/home/arccy/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/arccy/data/xdg/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/arccy/data/xdg/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/arccy/sdk/go1.15.2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/arccy/sdk/go1.15.2/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/arccy/testrepo-161/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build069944845=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

1. `go mod init x`
2. open `go.mod` in editor (neovim + coc.nvim)
3. try to type anything

### What did you expect to see?

no error messages while I type

### What did you see instead?

![2020-09-24-192555](https://user-images.githubusercontent.com/11343221/94178780-d713b380-fe9b-11ea-9c70-6da7334c7623.png)

Apparently due to the broken state of `go.mod` while editing breaking `gopls`'s ability to load workspace information. Continuing to type works except when typing a space where it is interpreted to dismiss the error message first, though I think that's (neo)vim specific behaviour.

**Comment by myitcv** [comment] 2020-09-24 17:51
I also ran into a variant of this whilst resolving merge conflicts in a `go.mod` file.

**Comment by stamblerre** [comment] 2020-12-23 20:30
Duplicate of https://github.com/golang/go/issues/42266

**Comment by stamblerre** [comment] 2020-12-23 20:30
Closing this, as https://github.com/golang/go/issues/42266 will resolve this issue.

**Closed by stamblerre** 2020-12-23 20:30 UTC
Labels: Tools, gopls
