### ISSUE TITLE
Make working with cookies from http.Header struct publicly available

### ISSUE THREAD

**Issue by galecore** [golang/go#46547] opened 2021-06-03 16:03 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
</pre></details>

### What did you do?
I am currently working on a project, in which a custom transport protocol is used. This protocol allows me to get access to http-like request with headers. It's not an actual http.Request object, but I can construct http.Header value from it. I would like to get access to cookies from this constructed http.Header, which is impossible right now - we can only access cookies via http.Request object. 
It doesn't feel right to me and I don't see why you can't get access to parsed cookie values. 
Could you add this functionality in a later release?

I would expect something like 
```
var x http.Header
myCookie := x.Cookie("my-cookie-key")
allCookies := x.Cookies()
```

**Comment by seankhliao** [comment] 2021-06-03 16:16
Duplicate of #25194

Note it's accepted but not implemented

**Closed by seankhliao** 2021-06-03 16:16 UTC
