### ISSUE TITLE
proposal: Go 2: Allow type parameter declaration on methods

### ISSUE THREAD

**Issue by seborama** [golang/go#51824] opened 2022-03-20 09:07 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOVERSION="go1.18"
</pre></details>

### What did you do?

I tried to declare a type parameter on  method (of a receiver that is).

https://go.dev/play/p/mY4wOR2NBmy

> ./prog.go:15:30: syntax error: method must have no type parameters
> ./prog.go:19:30: syntax error: method must have no type parameters
>
> Go build failed.

### What did you expect to see?

Successful compilation.

### What did you see instead?

Go does not support this declaring type parameters against methods as it does against functions.

Admittedly, this is documented [here](https://go.googlesource.com/proposal/+/master/design/43651-type-parameters.md#no-parameterized-methods).

I think it would enrich what can be achieved with type parameters in Go by a degree of magnitude.

**Comment by seankhliao** [comment] 2022-03-20 09:31
Duplicate of #49085

**Closed by seankhliao** 2022-03-20 09:31 UTC
Labels: Proposal
