### ISSUE TITLE
Include cgo source files in go mod vendor

### ISSUE THREAD

**Issue by mcandre** [golang/go#47894] opened 2021-08-22 20:16 UTC
It's really annoying how `go mod vendor` silently drops important native C/C++ source code files used by cgo.

Reminds me of how immature reflect's support for vendoring is.

At the very least, would be helpful for `go mod vendor` to warn the user when cgo files are excluded, so that the user will know why things are breaking. Instead of silently producing a borked vendor tree.

**Comment by seankhliao** [comment] 2021-08-22 20:29
Duplicate of #26366

**Closed by seankhliao** 2021-08-22 20:29 UTC
