### ISSUE TITLE
go fmt/build: syntax error: missing ',' before newline in parameter list

### ISSUE THREAD

**Issue by WhisperingChaos** [golang/go#18691] opened 2017-01-17 19:40 UTC
### What version of Go are you using (`go version`)?
go version go1.7.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build568111197=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
Wanted to format [function parameter list](https://golang.org/ref/spec#Function_types) so each ParameterDecl appears on its own separate line to support commenting of the function's interface and partitioning in situations where parameter list variable and type names exceed limited horizontal screen area.

Positioning the parameter list's closing parenthesis on next line after last ParameterDecl triggers the error.

A coded example at [play.golang.org](https://play.golang.org/p/VAegcjo3lH).

### What did you expect to see?
No reported compiler/formatting error.

### What did you see instead?
The error "syntax error: missing ',' before newline in parameter list"

**Comment by cznic** [comment] 2017-01-17 19:45
This is working as intended by the language specification. It's caused by the [semicolon injection](https://golang.org/ref/spec#Semicolons).

**Comment by ALTree** [comment] 2017-01-17 19:46
Yeah the comma in the last line of the signature is mandatory. Closing, since this is working as intended.

**Closed by ALTree** 2017-01-17 19:46 UTC

**Comment by WhisperingChaos** [comment] 2017-01-17 21:30
@cznic 

Thanks for the  link to semicolon insertion!

I agree, according to its explicitly "encoded definition" provided by your link, semicolon injection actually triggered the syntax error.  However, this encoding is driven by an interpretation of the golang's intent. 

Semicolon injection, according to [Effective Go](https://golang.org/doc/effective_go.html#semicolons), attempts to determine a statement's termination: “_if the newline comes after a token that could end a statement, insert a semicolon_”.  I would suggest that the current encoded definition of a statement's termination is too aggressive and could be altered to accommodate language productions involving lists that are delimited by "begin" and "end" tokens, like "(",")", as a statement can't be considered ending until a list that's a clause of a statement's definition has been processed.

Finally, I do understand that the potential complexity of implementing the above could be a reason why it isn't exempt from the current encoded definition.  However, this is just an assumption of mine and if possible, I would appreciate the reasoning behind the decision, so it could be documented by at least this thread.

Thanks!

**Comment by griesemer** [comment] 2017-01-17 22:04
@WhisperingChaos The semicolon insertion rule is defined by the spec ( https://golang.org/ref/spec#Semicolons ). Effective Go cites repeats the exact same rule, and what you are quoting (“if the newline comes after a token that could end a statement, insert a semicolon”) is a summary intended as a reminder, it's not the "intent". The intent is what the spec defines, and there is no interpretation required in this case.

There have been plenty of discussions about the if's and why's of Go's semicolon insertion rules (see one of the Go's discussion forums). The gist of it is that 1) the existing rules don't require any more than lexical context, that is, semicolons can be inserted w/o complex analysis at the lexical level, 2) the rules are simple, and 3) they work quite well.

What you are suggesting will require (parser) context and make semicolon rules quite a bit more complex for little benefit.

Please direct any further questions to one of Go's discussion forums. Thanks.
