### ISSUE TITLE
cmd/go: line added to go.sum with no change in requirements

### ISSUE THREAD

**Issue by myitcv** [golang/go#36667] opened 2020-01-21 07:37 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +8e0be05ec7 Sun Jan 19 14:04:09 2020 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build872676544=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

A recent commit that was merged for `govim` added a line to `go.sum` when there was no obvious change in requirements:

```
cd $(mktemp -d)
git clone https://github.com/govim/govim
cd govim
git checkout 57e94a35b8939d13fc2ff9d8e2a023db93d1cafa
```

Verify that we are tidy:

```
go mod tidy
git status
```

Compare `go.sum` to the previous commit:

```
git diff HEAD~1 -- go.sum
```

gives:

```diff
diff --git a/go.sum b/go.sum
index 309777f..b382394 100644
--- a/go.sum
+++ b/go.sum
@@ -43,6 +43,7 @@ github.com/stretchr/testify v1.4.0/go.mod h1:j7eGeouHqKxXV5pUuKE4zz7dFj8WfuZ+81P
 golang.org/x/crypto v0.0.0-20181106171534-e4dc69e5b2fd/go.mod h1:6SG95UA2DQfeDnfUPMdvaQW0Q7yPrPDi9nlGo2tz2b4=
 golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2/go.mod h1:djNgcEr1/C05ACkg1iLfiJU5Ep61QUkGW8qpdssI0+w=
 golang.org/x/crypto v0.0.0-20190510104115-cbcb75029529/go.mod h1:yigFU9vqHzYiE8UmvKecakEJjdnWj3jj499lnFckfCI=
+golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550 h1:ObdrDkeb4kJdCP557AjRjq69pTHfNouLtWZG7j9rPN8=
 golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550/go.mod h1:yigFU9vqHzYiE8UmvKecakEJjdnWj3jj499lnFckfCI=
 golang.org/x/mod v0.0.0-20190513183733-4bf6d317e70e h1:JgcxKXxCjrA2tyDP/aNU9K0Ck5Czfk6C7e2tMw7+bSI=
 golang.org/x/mod v0.0.0-20190513183733-4bf6d317e70e/go.mod h1:mXi4GBBbnImb6dmsKGUJ2LatrhH/nqhxcFungHvyanc=
```

But then nothing in the commit itself changes that would, AFAIK, result in a new line in `go.sum`:

https://github.com/govim/govim/commit/57e94a35b8939d13fc2ff9d8e2a023db93d1cafa

Am I missing something obvious here?

Credit to @leitzler for spotting this as part of a review.

### What did you expect to see?

No diff in `go.sum`

### What did you see instead?

Per above

Tentatively marking Go 1.14 in case there is something that needs fixing here.

cc @bcmills @jayconrod

**Comment by bcmills** [comment] 2020-01-22 15:54
Duplicate of #33008

**Closed by bcmills** 2020-01-22 15:54 UTC
Labels: GoCommand, NeedsInvestigation

**Comment by myitcv** [comment] 2020-01-22 15:56
Doh! I even commented on that issue. Thanks @bcmills
