### ISSUE TITLE
mail.ParseAddress incorrectly parses email addresses without Top Level Domains

### ISSUE THREAD

**Issue by grqphical** [golang/go#70059] opened 2024-10-26 03:49 UTC
### Go version

go version go1.23.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/grqphical/.cache/go-build'
GOENV='/home/grqphical/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/grqphical/development/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/grqphical/development/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.0'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/grqphical/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/grqphical/development/go/inference-lab/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3855366447=/tmp/go-build -gno-record-gcc-switches'
GOROOT/bin/go version: go version go1.23.0 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.23.0
uname -sr: Linux 5.15.153.1-microsoft-standard-WSL2
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Debian GLIBC 2.36-9+deb12u7) stable release version 2.36.
```

### What did you do?

https://go.dev/play/p/CWyOyotPGm2

### What did you see happen?

`mail.ParseAddress` returned no error when parsing an email without a TLD

### What did you expect to see?

I expected it to return an error.

Not sure if this is intended behaviour or not. I couldn't find anything concrete online about if the email address specification allows addresses without TLDs

**Comment by gazerro** [comment] 2024-10-26 07:07
Technically, "name@domain" is a valid email address under the RFC 5322. Since the `net/email` package follows the syntax from this RFC, the parser is working as expected here. Although a domain without a TLD might look incomplete, RFC 5322 actually allows it. The rule requiring a TLD comes from RFC 5321, which isn’t part of the package’s validation.

**Comment by seankhliao** [comment] 2024-10-26 08:44
Closing as working as intended.

**Closed by seankhliao** 2024-10-26 08:44 UTC
Labels: FrozenDueToAge
