### ISSUE TITLE
cmd/go: modules with empty go.mod files not diagnosed well

### ISSUE THREAD

**Issue by IngCr3at1on** [golang/go#25272] opened 2018-05-06 16:18 UTC
I can't actually decide if this is a bug or just me doing something wrong....
---

### What version of Go are you using (`go version`)?
`go version go1.10.1 linux/amd64`
`go version go1.10.1 linux/amd64 vgo:2018-02-20.1`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN="/home/ing/ply/go/bin"
GOCACHE="/home/ing/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ing/ply/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build144176356=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

in a working directly create a main:
```
package main // import "github.com/IngCr3at1on/bugexample"

import (
	"github.com/JustAnotherOrganization/l5424"
	"github.com/JustAnotherOrganization/l5424/x5424"
)

func main() {
	log := x5424.New().NewEntry(l5424.FacilityKernel)
	log.Alertln("Foo")
	log.Noticeln("Bar")
}
```
and a go.mod
`touch go.mod`

Or simply pull down `github.com/IngCr3at1on/bugexample`

### What did you expect to see?
The program should compile

### What did you see instead?
```
vgo: resolving import "github.com/JustAnotherOrganization/l5424"
vgo: finding github.com/JustAnotherOrganization/l5424 (latest)
vgo: adding github.com/JustAnotherOrganization/l5424 v0.1.0
vgo: import "github.com/JustAnotherOrganization/l5424/x5424" [/home/ing/ply/go/src/v/github.com/JustAnotherOrganization/l5424@v0.1.0/x5424]: open /home/ing/ply/go/src/v/github.com/JustAnotherOrganization/l5424@v0.1.0/x5424: no such file or directory
```
---

Initially only the tag `v0.1.0` existed; someone in the #vgo channel on Gopher's Slack suggested I add the tag `x5424/v0.1.0` but that doesn't seem to make a difference.

---

It's worth adding that the issue reminds me of https://github.com/golang/go/issues/24605 but I'm not sure if they're the same...

**Comment by davecgh** [comment] 2018-05-26 00:53
We are seeing something that seems very likely to be related since it is a nested package in [dcrd](https://githhub.com/decred/dcrd].  However, rather than not being able to find the error, instead the dependency solver believes the nested module is provided by the parent module despite the parent module not including it as evidenced by looking in `$GOPATH/src/v` to verify.

This can currently be reproduced as of [dcrd commit be318f5a](decred/dcrd@be318f5a699fbea136a0f6aa65f6059a983e6e70) by navigate to the `connmgr` package, clearing the contents of the `go.mod` file, and running `vgo build`.

The following are the results:

```
$ git clone https://github.com/decred/dcrd $GOPATH/src/github.com/decred/dcrd
...
Resolving deltas: 100% (15995/15995), done.

$ cd $GOPATH/src/github.com/decred/dcrd/connmgr
$ git checkout be318f5a
Note: checking out 'be318f5a'.
...

$ rm go.mod*; touch go.mod

$ vgo version
go version go1.10.2 windows/amd64 vgo:2018-02-20.1

$ vgo build
vgo: resolving import "github.com/decred/dcrd/chaincfg"
vgo: finding github.com/decred/dcrd/chaincfg (latest)
vgo: adding github.com/decred/dcrd/chaincfg v1.0.0
vgo: resolving import "github.com/decred/dcrd/wire"
vgo: finding github.com/decred/dcrd/wire (latest)
vgo: adding github.com/decred/dcrd/wire v1.0.0
vgo: resolving import "github.com/decred/slog"
vgo: finding github.com/decred/slog (latest)
vgo: adding github.com/decred/slog v1.0.0
vgo: import "github.com/decred/dcrd/connmgr" ->
        import "github.com/decred/dcrd/chaincfg" ->
        import "github.com/decred/dcrd/chaincfg/chainhash": found in both github.com/decred/dcrd/chaincfg v1.0.0 and github.com/decred/dcrd/chaincfg/chainhash v1.0.0
vgo: downloading github.com/decred/dcrd/wire v1.0.0
vgo: downloading github.com/decred/slog v1.0.0
```

We can verify the `chainhash` module is not part of the `chaincfg v1.0.0` module by looking in GOPATH:

```
$ ls -al "$GOPATH/src/v/github.com/decred/dcrd/chaincfg@v1.0.0"
total 315K
drwxr-xr-x 1 davec None    0 May 25 18:52 ./
drwxr-xr-x 1 davec None    0 May 25 18:52 ../
drwxr-xr-x 1 davec None    0 May 25 18:52 chainec/
-rw-r--r-- 1 davec None 2.5K May 25 18:52 doc.go
-rw-r--r-- 1 davec None 8.8K May 25 18:52 genesis.go
...
```

**Comment by rsc** [comment] 2018-07-10 19:02
@dcrd I think your problem is more like #26250. Fix CL going out today.

@IngCr3at1on, the first problem is that the go.mod files checked into the repo are empty. They need to have a module line, like

	module github.com/JustAnotherOrganization/I5424

and

	module github.com/JustAnotherOrganization/I5424/x5424

I will make this issue track having a good diagnosis of this condition.

Once those go.mod files are updated (and new tags added), then I think you'll be up against #26250. Watch for that issue to be closed.

**Comment by IngCr3at1on** [comment] 2018-07-20 00:36
@rsc I made the changes to the go.mod files that you suggested (and updated my vgo binary) and it would seem I'm still seeing an issue:

```
vgo: resolving import "github.com/JustAnotherOrganization/l5424"
vgo: finding github.com/JustAnotherOrganization/l5424 (latest)
vgo: adding github.com/JustAnotherOrganization/l5424 v1.0.2
vgo: import "github.com/JustAnotherOrganization/l5424/x5424" [/home/ing/ply/go/src/v/github.com/JustAnotherOrganization/l5424@v1.0.2/x5424]: open /home/ing/ply/go/src/v/github.com/JustAnotherOrganization/l5424@v1.0.2/x5424: no such file or directory
```

I updated the original example repo with a more current version (to reflect the other changes to the repos themselves)...

I also have a theory at this point as to the cause of this error (and it may be worth a separate issue) the tags for the 'parent' module vs the 'sub' module have diverged slightly do to different fiddlings.

On the plus side my attempt to "exercise" vgo with this project seems to be going well :smile:

**Comment by iwdgo** [comment] 2024-11-14 14:51
Issue seems incidentally solved by https://github.com/golang/go/issues/45713 which added a more explicit message when go.mod is empty.
```
>go version
go version go1.23.3 darwin/amd64
>mkdir 25272 && cd 25272
>touch go.mod
>go mod tidy
go: error reading go.mod: missing module declaration. To specify the module path:
	go mod edit -module=example.com/mod
```

**Closed** 2024-11-14 16:36 UTC
Labels: NeedsFix, modules
