### ISSUE TITLE
x/tools/cmd/guru: PTA ignores TestMain function

### ISSUE THREAD

**Issue by dominikh** [golang/go#16430] opened 2016-07-19 21:13 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"

3. What did you do?
  - Download https://play.golang.org/p/XwnnNEoCXf
  - Run `guru -scope sandbox/foo pointsto "foo_test.go:#111"`

4. What did you expect to see?
The guru call should find `x` and know that it contains an instance of `t`.

5. What did you see instead?
`guru: pointer analysis did not find expression (dead code?)`

It works fine for the instances of `x` in the other test functions.

/cc @alandonovan

**Comment by alandonovan** [comment] 2016-07-19 21:34
Duplicate of #9553.

**Closed by alandonovan** 2016-07-19 21:34 UTC
