### ISSUE TITLE
net: DNS look up failed after configure DoH in Windows 

### ISSUE THREAD

**Issue by mloeng** [golang/go#60730] opened 2023-06-11 15:48 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
</pre></details>

### What did you do?

After configure DoH follow [Secure DNS Client over HTTPS (DoH)](https://learn.microsoft.com/en-us/windows-server/networking/dns/doh-client-support), DNS lookup with the pure Go resolver failed.
https://go.dev/play/p/EHn7w1bUT26
<pre>
[] lookup google.com on 1.12.12.12:53: read udp 192.168.223.195:60200->1.12.12.12:53: i/o timeout
</pre>
It seems to recognize the server as a plain DNS server.

### What did you expect to see?

DNS lookup succeed.

### What did you see instead?

DNS lookup failed.

**Comment by seankhliao** [comment] 2023-06-11 17:49
Duplicate of #27552

**Closed by seankhliao** 2023-06-11 17:49 UTC
