### ISSUE TITLE
net/http: 411 Length Required despite being set

### ISSUE THREAD

**Issue by wxolp** [golang/go#53101] opened 2022-05-27 02:47 UTC
### What version of Go are you using (`go version`)?

~~~
go version go1.18 windows/amd64
~~~

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

Using this program:

~~~go
package main

import (
   "fmt"
   "io"
   "net/http"
   "strings"
)

func main() {
   req, err := http.NewRequest(
      "POST", "https://gw.cds.amcn.com/auth-orchestration-id/api/v1/unauth",
      io.NopCloser(strings.NewReader("")),
   )
   req.Header = http.Header{
      "Content-Length": {"0"},
      "X-Amcn-Device-Id": {"!"},
      "X-Amcn-Language": {"en"},
      "X-Amcn-Network": {"amcplus"},
      "X-Amcn-Platform": {"web"},
      "X-Amcn-Tenant": {"amcn"},
   }
   req.ContentLength = 0
   res, err := new(http.Transport).RoundTrip(req)
   if err != nil {
      panic(err)
   }
   defer res.Body.Close()
   fmt.Println(res.Status)
}
~~~

### What did you expect to see?

~~~
200 OK
~~~

### What did you see instead?

~~~
411 Length Required
~~~

This is confusing, as I have explicitly told Go what the Content-Length is, twice. If I change the body to `nil` it works, but it seems like the above code should work as is.

**Comment by ZekeLu** [comment] 2022-05-27 04:32
1. Explicitly setting the `Content-Length` does not work because it will be ignored:

    https://github.com/golang/go/blob/fd0ffedae2dd9e202efc2dd7f7937baa08600d26/src/net/http/h2_bundle.go#L8548-L8552
2. Setting `req.ContentLength = 0` does not work either (see line 7851 below):

    https://github.com/golang/go/blob/fd0ffedae2dd9e202efc2dd7f7937baa08600d26/src/net/http/request.go#L197-L199

3. Documents for the `Content-Length` header:

    https://github.com/golang/go/blob/fd0ffedae2dd9e202efc2dd7f7937baa08600d26/src/net/http/request.go#L856-L861
    https://github.com/golang/go/blob/fd0ffedae2dd9e202efc2dd7f7937baa08600d26/src/net/http/http.go#L100-L104

So if you want to post an empty body with the `Content-Length` header be set to `0`, you can choose one of the following bodies:

- `nil`
- `http.NoBody`
- `strings.NewReader("")`
- `bytes.NewReader(nil)`
- `bytes.NewBuffer(nil)`

According the information above, I think it works as intended.

**Comment by wxolp** [comment] 2022-05-27 05:04
I don't think its right, or robust, that only the certain magic inputs that's you've listed are "blessed" and others are not, despite my original example being equally "empty". I think a better use of logic would be something like this:

~~~go
_, err := b.Peek(1)
if err != nil {
   println("empty body")
} else {
   println("body contains data")
}
~~~

https://godocs.io/bufio#Reader.Peek

**Comment by hopehook** [comment] 2022-05-27 06:09
I think the standard library can't get the internal details for the user-defined io.NopCloser, which makes the processing a bit problematic. For example, http.NewRequest is not convenient to determine whether the current body should be Nobody, but strings.Reader can obtain this detail.

**Comment by ZekeLu** [comment] 2022-05-27 06:42
1. The listed input values are documented instead of mystically "blessed" :smile: 
2. In your initially example, you don't need to wrap the reader with `io.NopCloser` because `http.NewRequest` will do it if necessary.

    https://github.com/golang/go/blob/fd0ffedae2dd9e202efc2dd7f7937baa08600d26/src/net/http/request.go#L878-L881
3. The peek example only works when the body is an instance of `bufio.Reader`. Since `bufio.Reader` already been "blessed", no peek is required.

I think it's a surprise for a new comer to find that neither `req.ContentLength = 0` nor `req.Header = http.Header{"Content-Length": {"0"}}` works as expected. But once he/she knows the way to do it, it should be naturally to do it that way. Do you have a real world example that you can not do it this way?

**Comment by seankhliao** [comment] 2022-05-27 08:51
Duplicate of #20257

**Closed by seankhliao** 2022-05-27 08:51 UTC
