### ISSUE TITLE
display database table on a web page using html table to show like a gridview or dataview

### ISSUE THREAD

**Issue by connelevalsam** [golang/go#20920] opened 2017-07-06 09:29 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)? 
1.8

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

### What did you do? https://play.golang.org/p/QqHXewyDTp

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
expected to see the html page executed with range over my struct that has my data's from MySql table.

### What did you see instead?
Seeing a blank html page. In /read route nothing is showing

**Comment by ALTree** [comment] 2017-07-06 09:34
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2017-07-06 09:34 UTC
