### ISSUE TITLE
cmd/go: work around insecure redirects for domains hosted on GitHub Pages

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#32071] opened 2019-05-15 23:18 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +2e4edf4697 Sun May 12 07:14:09 2019 +0000 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rog/.cache/go-build"
GOENV="/home/rog/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rog/src/go"
GOPROXY="direct"
GOROOT="/home/rog/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/home/rog/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/rog/src/work/quicktest/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build245885201=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

     cd $(mktemp -d)
     go mod init m
     go get googlemaps.github.io/maps

### What did you expect to see?

I'd expect the command to succeed. It works on Go 1.12.

### What did you see instead?
```
$ go get googlemaps.github.io/maps
go get googlemaps.github.io/maps: unrecognized import path "googlemaps.github.io/maps" (https fetch: Get http://googlemaps.github.io/maps/?go-get=1: redirected from secure URL https://googlemaps.github.io/maps?go-get=1 to insecure URL http://googlemaps.github.io/maps/?go-get=1)
```

**Comment by FiloSottile** [comment] 2019-05-16 00:48
This is working as intended following #29618. `https://googlemaps.github.io/maps?go-get=1` is serving a redirect to an HTTP link, which is insecure, so requires the `-insecure` flag.

/cc @bcmills who is tracking impact of that change.

**Comment by FiloSottile** [comment] 2019-05-16 00:49
(It would be nice to ask GitHub support why the hell they are doing that, btw.)

**Comment by domesticmouse** [comment] 2019-05-16 11:19
I'm curious what I'm doing wrong here. (I'm the Googler responsible for the Go googlemaps project.)

I set up redirects in https://github.com/googlemaps/googlemaps.github.io/blob/master/maps/index.html to point to https URLs. 

Hints on how I can fix this gladly accepted.

**Comment by bcmills** [comment] 2019-05-16 13:00
There is an interesting clue in https://github.com/isaacs/github/issues/289#issuecomment-430941254:

> GitHub Support wrote:
> > This redirection quirk that you've discovered is a known issue, and relates to trailing slashes and how our redirects work at the moment. Making a request to a URL without a trailing slash will cause redirections to run in this order:
> > 
> > request to original URL
> > 301 to HTTPS version of original URL
> > 301 to HTTP version with added trailing slash
> > 301 to HTTPS version with added trailing slash
> > Always including the trailing slash will allow you to skip the extra redirects:
> > 
> > request to URL with trailing slash
> > 301 to HTTPS version of original URL
> > We have an issue open internally to hopefully improve this situation, but investigations have demonstrates that it is a non-trivial issue to resolve.

**Comment by bcmills** [comment] 2019-05-16 13:13
Reopening to consider workarounds, but I'd really rather GitHub fix their redirects instead.

**Comment by rsc** [comment] 2019-05-16 17:06
If -insecure is not being used and we see https://foo redirect to http://foo/ (that is, the only deltas are `s|https|http|; s|$|/|`) can we quietly put the https back instead of failing?

**Comment by bcmills** [comment] 2019-05-16 17:12
Yep, that seems like a plausible workaround — it's small, doesn't hard-code information specific to GitHub, and doesn't require that we change the initial URL.

**Comment by mastahyeti** [comment] 2019-05-16 18:28
We deployed a fix for this. Let us know if it has resolved the issue you were seeing.

**Comment by FiloSottile** [comment] 2019-05-16 18:35
This is indeed fixed, thank you @mastahyeti!

**Comment by ptoomey3** [comment] 2019-05-16 19:03
Apologies all..we are having to revert the change for now. We are looking into an issue it caused.

**Comment by ptoomey3** [comment] 2019-05-28 15:47
Can you all check this again? A second attempt (without the bug 🤞) was deployed late last week.

**Comment by bcmills** [comment] 2019-05-28 16:03
@ptoomey3, it seems to be working again. Thanks!

```
example.com$ gotip get googlemaps.github.io/maps
go: finding googlemaps.github.io/maps latest
go: downloading googlemaps.github.io/maps v0.0.0-20190514133808-4d12cf0fa845
go: extracting googlemaps.github.io/maps v0.0.0-20190514133808-4d12cf0fa845
go: finding github.com/google/uuid v1.1.1
go: finding golang.org/x/time latest
go: downloading github.com/google/uuid v1.1.1
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: extracting github.com/google/uuid v1.1.1
go: extracting golang.org/x/time v0.0.0-20190308202827-9d24e82272b4

example.com$
```

**Closed by bcmills** 2019-05-28 16:03 UTC
Labels: NeedsFix, release-blocker
