### ISSUE TITLE
x/tools/internal/lsp: conditional compilation not working

### ISSUE THREAD

**Issue by saibing** [golang/go#31179] opened 2019-04-01 06:48 UTC
The origin issue is on here: https://github.com/saibing/bingo/issues/139

@stamblerre

**Comment by stamblerre** [comment] 2019-04-01 11:48
Duplicate of #29202

**Comment by agnivade** [comment] 2019-04-01 11:58
Closing since its a duplicate.

**Closed by agnivade** 2019-04-01 11:58 UTC
