### ISSUE TITLE
Introduce negative indexing for slices

### ISSUE THREAD

**Issue by x0r19x91** [golang/go#41768] opened 2020-10-03 13:42 UTC
Currently we have unsigned indexing.  
Given a slice L, we can index the nth last element as `L[len(L)-n]`  
  
Simpler way would be `L[-n]`

**Comment by seankhliao** [comment] 2020-10-03 14:58
duplicate of #11245 #33359 
related to #16231 #20176

**Comment by mdlayher** [comment] 2020-10-03 15:39
Closing per above.

**Closed by mdlayher** 2020-10-03 15:39 UTC
