### ISSUE TITLE
Stat's mode didn't set right bit for symlinks

### ISSUE THREAD

**Issue by dshemin** [golang/go#48786] opened 2021-10-05 06:48 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dshemin/.cache/go-build"
GOENV="/home/dshemin/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dshemin/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dshemin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/current"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/current/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2039525487=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I try to run this code sample:

```golang
package main

import (
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	dir := os.TempDir()
	file := filepath.Join(dir, "foo")
	link := filepath.Join(dir, "foo_link")

	err := os.WriteFile(file, []byte("bar"), 0644)
	if err != nil {
		panic(err)
	}

	err = os.Symlink(file, link)
	if err != nil {
		panic(err)
	}

	l, err := os.Readlink(link)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Link path: %q\n", l)

	info, err := os.Stat(link)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Is symlink: %d\n", info.Mode() & os.ModeSymlink)
}
```

### What did you expect to see?

```
$ go run main.go 
Link path: "/tmp/foo"
Is symlink: 134217728
```

### What did you see instead?

```
$ go run main.go 
Link path: "/tmp/foo"
Is symlink: 0
```

**Comment by seankhliao** [comment] 2021-10-05 07:47
`Stat` follows links, use `Lstat`.

Closing as working as intended.

**Closed by seankhliao** 2021-10-05 07:47 UTC
