### ISSUE TITLE
Output of %#v is not gofmt clean

### ISSUE THREAD

**Issue by vetinari** [golang/go#16645] opened 2016-08-09 06:27 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.3 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/hhecker/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
The following is used to generate code via `go run example.go > output.go`:
```go
package main

import "fmt"

func main() {
        data := map[string]interface{}{"key": "value"}
        fmt.Printf("package main\n\nvar data = %#v\n", data)
}
```
Running gofmt -d on the output shows 
```
diff output.go gofmt/output.go
--- /tmp/gofmt472599174 2016-08-09 08:24:53.951200879 +0200
+++ /tmp/gofmt828973101 2016-08-09 08:24:53.951200879 +0200
@@ -1,3 +1,3 @@
 package main
 
-var data = map[string]interface {}{"key":"value"}
+var data = map[string]interface{}{"key": "value"}
```
4. What did you expect to see?
Nothing :)

5. What did you see instead?
the above whitespace changes

**Comment by davecheney** [comment] 2016-08-09 06:33
I don't see why every piece of output a go program produces has to be as go
fmt would produce it. We have a tool that can do this for us so we don't
have to nickle and dime every single piece of output.

**Comment by minux** [comment] 2016-08-09 07:36
I agree with Dave. We have go/printer, so if you want gofmtted output, you
could use that. Embedding the full gofmt rule into the fmt package seems
unnecessary.

**Comment by ianlancetaylor** [comment] 2016-08-09 13:07
I agree that the general goal is pointless.  And this specific case is not due to the fmt package at all, but is simply a reproduction of the type string generated by the compiler, which would be somewhat painful to change.  Closing.  Sorry.

**Closed by ianlancetaylor** 2016-08-09 13:07 UTC
