### ISSUE TITLE
runtime: fatal error: missed stack barrier

### ISSUE THREAD

**Issue by b-s-a** [golang/go#18571] opened 2017-01-09 08:54 UTC
A program with pprof enabled (net/http/pprof imported) compiled with Go 1.7.3 panics sometime (one per 2 weeks or rare) with: fatal error: missed stack barrier

OS: Debian 7 x86_64
go version go1.7.3 linux/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.7"
GOTOOLDIR="/usr/lib/go-1.7/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build721289951=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

[log1.txt](https://github.com/golang/go/files/692975/log1.txt)
[log2.txt](https://github.com/golang/go/files/692976/log2.txt)

**Comment by ALTree** [comment] 2017-01-09 09:14
Is the code free of data races (did you try building/running with `-race`)?
Did you by chance test it with the `go1.8beta2`? Does it happen with go1.8?

**Comment by dsnet** [comment] 2017-01-09 09:46
Thanks for the report. Additional question:
* Is there any `unsafe` or `cgo` involved?

**Comment by b-s-a** [comment] 2017-01-09 10:18
There are no any cgo and unsafe imports.
I have not tested with -race, so I do it soon, thank you for it.

**Comment by b-s-a** [comment] 2017-01-09 12:21
I cannot reproduce bug on my machine with go1.7. But I do not want to use go1.8 on production.

-race shows only one place - read/write boolean variable. I have rewrite this part of code, and will test it on production soon...

**Comment by ianlancetaylor** [comment] 2017-01-09 19:12
When you say "I cannot reproduce bug on my machine with go1.7" did you mean to say go1.8?

**Comment by ianlancetaylor** [comment] 2017-01-09 19:13
CC @aclements

**Comment by b-s-a** [comment] 2017-01-09 19:21
I cannot reproduce on my machine, because I cannot load it as production server and cannot wait for weeks...

Currently I suggest to suspend this discussion, because compiler used was 1.5 (I open binary and find go1.5 string in it). debian package system did not use 1.7. So I completely recompile my program and put on production. Currently I will wait for 1 month to reproduce bug. If it is not reproduced, then bug should be closed as invalid.

**Comment by ALTree** [comment] 2017-01-09 19:24
If you were using 1.5 you could be seeing  #12932 (?)

**Comment by b-s-a** [comment] 2017-01-09 19:29
It is very possible, because this bug is reason why I try to use 1.7 which is not present in debian 7, so my installation was incorrect.

**Comment by aclements** [comment] 2017-01-09 21:20
Based on the line numbers in the traceback, I can confirm that this binary was actually built with Go 1.5.1. Since we're no longer supporting Go 1.5, I'm going to close this bug.

It's likely the @ALTree is right and what you're seeing is #12932. That was fixed in Go 1.6 and backported for Go 1.5.2, so upgrading should fix the problem.

**Closed by aclements** 2017-01-09 21:20 UTC
Labels: NeedsInvestigation, WaitingForInfo
