### ISSUE TITLE
cmd/compile: out of fixed registers on 386 when building x/arch/vendor/rsc.io/pdf

### ISSUE THREAD

**Issue by minux** [golang/go#12840] opened 2015-10-05 07:32 UTC
```
# golang.org/x/arch/vendor/rsc.io/pdf
run compiler with -v for register allocation sites
../../gopath/src/golang.org/x/arch/vendor/rsc.io/pdf/page.go:250: internal compiler error: out of fixed registers
```

**Comment by brian-brazil** [comment] 2016-03-29 14:44
We've also run into this with Prometheus on both 1.5.3 and 1.6.0, see https://github.com/prometheus/prometheus/issues/1509

**Comment by beorn7** [comment] 2016-03-29 15:17
In case it helps, the offending code is

```Go
var (
	c []byte
	offset uint16
	bitMask [][]byte
)
// ...
c[offset/8] &^= bitMask[1][offset%8]
```

Breaking the statement into two helps. Both of the below work:

```Go
bm := bitMask[1][offset%8]
c[offset/8] &^= bm
```

```Go
newByte := c[offset/8] &^ bitMask[1][offset%8]
c[offset/8] = newByte
```

**Comment by randall77** [comment] 2016-10-07 16:01
This should be fixed with the new SSA backend.
(Although I can't reproduce the original problem.)

**Closed by randall77** 2016-10-07 16:01 UTC
