### ISSUE TITLE
x/website: https://golang.org/doc/tutorial/call-module-code

### ISSUE THREAD

**Issue by allen0125** [golang/go#46750] opened 2021-06-15 05:20 UTC
### What did you do?
when I read the manual I found this:

$ go mod edit **-replace=example.com**/greetings=../greetings

May be it should be:

$ go mod edit **-replace example.com**/greetings=../greetings

**Comment by tmthrgd** [comment] 2021-06-15 06:14
This is a duplicate of #44924.

**Closed** 2021-06-15 07:01 UTC
