### ISSUE TITLE
cmd/link: bad decoding of R_USEGENERICIFACEMETHOD relocation

### ISSUE THREAD

**Issue by mdempsky** [golang/go#54346] opened 2022-08-09 03:08 UTC
At commit 228f891c90, running the test program below with `go run` fails with "fatal error: unreachable method called. linker bug?".

I think there's something wrong with parsing the R_USEGENERICIFACEMETHOD relocation:

```
$ go build -ldflags=-v=2 bug.go |& grep --text reached.generic | cat -v
reached generic iface method: x^@^@^@^@^@^@^@
```

Presumably the trailing zero bytes then causes it to fail to preserve the `x` method in the itabs.

Note the trailing zero bytes in the method name, which presumably go onto causing the `x` method to get trimmed.

Renaming the method seems to avoid the issue. Though notably, I initially ran into the issue with GOEXPERIMENT=unified and a method named `g`, and assumed it was an issue on my end. So it's not specific to just `x`.

Trimming down the imports also seems to break the failure.

```
package main

import (
	_ "os"
)

func main() {
	foo := Foo[int]{}
	foo.f4()
}

type Foo[T int] struct{}

func (l *Foo[T]) f4() {
	var h G[T] = l
	h.x()
}

func (l *Foo[T]) x() {}

type G[T int] interface {
	x()
}
```

/cc @golang/compiler

**Comment by cherrymui** [comment] 2022-08-09 15:43
I'll take a look.

**Comment by cherrymui** [comment] 2022-08-09 17:35
Is this specific to commit 228f891 ? I cannot reproduce on tip (9c5cae08928a885616f54d8df50a43713b95db7a). Maybe something changed? Or you checked in a CL that works around it? Thanks.

**Comment by cherrymui** [comment] 2022-08-09 18:09
It also doesn't fail with Go 1.19. It fails at 0d9ed0638b, and doesn't fail at e1a8e0e05d.
Maybe it is not a linker bug?

**Comment by cuonglm** [comment] 2022-08-09 18:23
The commit introduces the bug is c3833a55433f4b2981253f64444fe5c3d1bc910a, then it was reverted by commit e1a8e0e05d4959d0b669cb968482a5dcfe0c95f8

**Comment by mdempsky** [comment] 2022-08-09 18:48
> Is this specific to commit https://github.com/golang/go/commit/228f891c905af8c01743085a74b2189f58eecba1 ?

I think it's an issue that's very narrowly reproducible.

Note that at patchset 5 of https://go-review.googlesource.com/c/go/+/421821 (commit 845060b20c5888b7b1c5de1dace845058bff2028, which includes e1a8e0e05d4959d0b669cb968482a5dcfe0c95f8 and ad0287f4960610c01c12ea99da50d7138509c0b0), test/typeparam/issue48042.go is still failing on the trybots. So I don't think it's related to the heap bitmaps changes.

I have a meeting in a second, but I can give fuller repro notes shortly.

**Closed** 2022-08-10 00:52 UTC
Labels: NeedsFix, compiler/runtime
