### ISSUE TITLE
database/sql: Using RawBytes and cancelling query context is inherently racy

### ISSUE THREAD

**Issue by mhr3** [golang/go#53970] opened 2022-07-20 11:48 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
haven't tried 1.19

### What did you do?
something along these lines 🔽 
```
	rows, err := stmt.QueryContext(ctx)
	if err != nil {
		return info, nil, err
	}
	defer rows.Close()

	var data        sql.RawBytes

	for rows.Next() {
		err = rows.Scan(&data)
		if err != nil {
			return info, sel, err
		}

		// if ctx is canceled around this point, rows.Close() will be called and the data can be overwritten, causing a data race
		doWork(data)
	}
```

### What did you expect to see?
No data races, no matter whether the context is cancelled or not.

### What did you see instead?
We noticed this when using lib/pq, but upon looking deeper into it, there's not much lib/pq can do, it just sees a call to driver.Rows.Close(), and can't distinguish whether this is coming from within the iteration goroutine or because of context cancellation.
Therefore it reuses the buffer that was previously passed to Scan's RawBytes param and causes a data race because doWork is still reading the data.

**Comment by seankhliao** [comment] 2022-07-20 12:13
I think this is working as designed:
`sql.RawBytes` is explicitly a reference to database owned memory, and it's the user code's responsibility to ensure it's not used beyond the valid lifetime:

> After a Scan into a RawBytes, the slice is only valid until the next call to Next, Scan, or Close.

**Comment by seankhliao** [comment] 2022-07-20 14:35
The user code passes in a context to control the lifetime, it needs to be aware of the lifetime too.

**Comment by seankhliao** [comment] 2022-07-20 15:28
I'm saying that context needs to be propagated into your doWork and the context deadline followed in there too.

cc @kardianos

**Comment by toothrot** [comment] 2022-07-20 16:59
A better place to ask this kind of question is golang-nuts. See https://golang.org/wiki/Questions.

Closing, as this isn't a bug in Go or the standard library. This is working as intended. Feel free to ask on one of the resources linked in Questions for help.

**Comment by mhr3** [comment] 2022-07-20 23:40
I'm sorry, how is a data race not a bug? I should have replaced the doWork() with a simple:

```
	for rows.Next() {
		err = rows.Scan(&data)
		if err != nil {
			return info, sel, err
		}

		// if ctx is canceled around this point, rows.Close() will be called and the data can be overwritten, causing a data race
		_ = data[0] // <--- possible concurrent read here and write inside driver.Rows.Close()
	}
```

**Comment by stevenh** [comment] 2022-07-25 14:04
As mentioned on golang-nuts, I believe @mhr3 has identified a legitimate issue here, as there is currently no way to use `sql.RawBytes` in code which uses also uses `context`.

**Comment by ianlancetaylor** [comment] 2022-07-25 21:11
CC @kardianos

**Comment by kardianos** [comment] 2022-07-26 14:28
@stevenh

I think you might be correct if calling a query directly from `*DB`. For when a query is cancelled, that connection and associated buffers may be re-used by another connection.

I believe it would be correct that this is not racy if using RawBytes from a Conn or Tx, assuming the application itself is written correctly. Would you agree?

**Comment by stevenh** [comment] 2022-07-26 15:57
To confirm @kardianos does your second case include code like original example?
```go
func doQuery(ctx context.Context, stmt *sql.Stmt) error {
	rows, err := stmt.QueryContext(ctx)
	if err != nil {
		return err
	}
	defer rows.Close()

	var data  sql.RawBytes
	for rows.Next() {
		if err = rows.Scan(&data); err != nil {
			return err
		}

		// This is racey if ctx is cancelled after rows.Scan complete and before
                // we complete due to the close in QueryContext which can free / reuse
                // the driver memory.
		fmt.Println(data)
	}
        return rows.Err()
}
```

**Comment by kardianos** [comment] 2022-07-26 20:08
On that note, it is difficult to use a  Stmt on Tx and maybe not possible to run an existing Stmt on a specific Conn. Given that stmt will pull a random conn from the pool, this will be an issue. We may want to add `*Conn.StmtContext` where it will use a stmt on a specific conn, like you can today with Tx.

**Comment by stevenh** [comment] 2022-07-26 21:02
That may be useful, but I don't believe it's needed to solve this problem.

**Comment by stevenh** [comment] 2022-07-26 21:14
Looks like both [DB.BeginTx](https://pkg.go.dev/database/sql#DB.BeginTx) and [Conn.BeginTx](https://pkg.go.dev/database/sql#Conn.BeginTx) have the same issue as they call go [tx](https://cs.opensource.google/go/go/+/refs/tags/go1.18.4:src/database/sql/sql.go;drc=24dc27a3c084b901ee456637541ea818495888b0;bpv=1;bpt=1;l=1875).[awaitDone](https://cs.opensource.google/go/go/+/refs/tags/go1.18.4:src/database/sql/sql.go;drc=24dc27a3c084b901ee456637541ea818495888b0;bpv=1;bpt=1;l=2184)() which calls close.

**Comment by stevenh** [comment] 2022-09-05 11:04
While that seems like a potential, I suspect it would lead to continued issues because its a fragile API for consumers, relying on knowledge of the buffer type which may not be know depending on how abstractions are constructed.

Instead I would suggest we investigate changing the flow so that close triggered by context calls such as `QueryContext` can only occur before the function returns, if that is even desirable?

After that it should be the callers responsibility, which matches the current docs as I can't find any reference in these methods that tells the uses rows could be closed under the hood except when interaction completes.

**Comment by kardianos** [comment] 2022-09-05 16:36
@stevenh Only canceling while in the QueryContext function is not something I would support.

On SQL DB Servers, query execution context is extremely important. If you have an operation that effectively `select * from TBLongTable;`  the query (in a good DB) will return quickly, but the rows will continue on for a long time. Rows must be able to hook into the same cancellation policy. Furthermore, because the context is passed into the driver, this makes it difficult to not let it be canceled right away.

**Comment by stevenh** [comment] 2022-09-06 20:34
To clarify I wasn't suggesting not cancelling, as you said that wouldn't work, the intent was for us to specifically to not call `Close`.

If consider the following:
```go
func doQuery(ctx context.Context, stmt *sql.Stmt) error {
	rows, err := stmt.QueryContext(ctx)
	if err != nil {
		return err
	}

	defer rows.Close()
       ...
}
```

If `QueryContext` doesn't return an error the user is not expecting `rows.Close()` to be called irrespective of `ctx` being cancelled. If we can ensure that is the case I believe we'll solve the issue at hand.

**Comment by rsc** [comment] 2023-05-19 16:59
Closing as a duplicate of #60304, which has a crisper presentation of the problem. Apologies for not understanding this problem better when it was filed.

**Closed by rsc** 2023-05-19 16:59 UTC
Labels: NeedsInvestigation

**Comment by bradfitz** [comment] 2023-05-19 18:19
Sorry, I should've searched & found this bug before I filed my dup.

**Comment by stevenh** [comment] 2023-05-24 21:19
Great to see this fixed, thanks @bradfitz!
