### ISSUE TITLE
cmd/go: mod download uses global gitconfig, should check project's gitconfig first

### ISSUE THREAD

**Issue by Genert** [golang/go#31802] opened 2019-05-02 12:44 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/genertorg/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/genertorg/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/genertorg/masga/gobase/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tb/3yd9xyqj5cn53csl1k17tmgr0000gn/T/go-build189348569=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

When using "git config  url."git@bitbucket.org:".insteadOf https://bitbucket.org/" within project folder, it would be expected that when getting private package within bitbucket SVN, the project's git configuration should be used instead of global git configuration.

Currently this does not work as GLOBAL git configuration file is used.

### What did you expect to see?
It would be great if the existence of project's gitconfig is checked first and used in that case. Otherwise fall back to global configuration.

### What did you see instead?

Opposite behavior.

**Comment by bcmills** [comment] 2019-05-06 21:45
Duplicate of #31256

**Closed by bcmills** 2019-05-06 21:45 UTC
Labels: NeedsInvestigation
