### ISSUE TITLE
fmt: Scan extra input when switching languages

### ISSUE THREAD

**Issue by Dezmmond** [golang/go#45354] opened 2021-04-02 10:38 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2160470449=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I wrote and tested this program:
<details><summary><code>My program</code> Output</summary><br><pre>
package main

import . "fmt"

func main() {
        var (
		name string
		age int
	)
	Print("Введите имя: ")
	Scanln(&name)
	Print("Введите возраст: ")
	Scanln(&age)

	Println(name, age)
}
</pre></details>

Algorithm:
1. Started the program.
2. In the name input field, I entered the text first in Cyrillic (text: Vuy), then completely erased it, switched the layout from American to Russian with the keyboard shortcut "Alt+Shift" and wrote in Latin (text: Dezm), then pressed the "Enter"button.
3. In the age input field, enter the numbers (88), and then click the "Enter" button.

### What did you expect to see?
In stdout i expected to see: Dezm 88

### What did you see instead?
But i see instead: ВуDezm 88

**Comment by seankhliao** [comment] 2021-04-02 13:59
Can you try it with the following and post the output?
Though I think this is more likely an issue with the terminal and/or input method than with Go.

(cribbed from https://github.com/golang/go/issues/23562#issuecomment-360956261)

```go
package main

import (
	"fmt"
	"os"
)

type myReader struct{}

func (r myReader) Read(p []byte) (n int, err error) {
	n, err = os.Stdin.Read(p)
	fmt.Fprintf(os.Stderr, "DEBUG: %q %v\n", p[:n], err)
	return n, err
}

func main() {
	var (
		name string
		age  int

		input = &myReader{}
	)

	fmt.Print("Введите имя: ")
	fmt.Fscanln(input, &name)

	fmt.Print("Введите возраст: ")
	fmt.Fscanln(input, &age)

	fmt.Println(name, age)
}

```

**Comment by opennota** [comment] 2021-04-03 13:44
I can't reproduce this in Konsole, so I guess the culprit is indeed the issue author's terminal emulator or input method.

**Comment by Dezmmond** [comment] 2021-04-05 07:23
This is my output:

Введите имя: Dezm
DEBUG: "\xd0" <nil>
DEBUG: "\x92" <nil>
DEBUG: "\xd1" <nil>
DEBUG: "\x83" <nil>
DEBUG: "D" <nil>
DEBUG: "e" <nil>
DEBUG: "z" <nil>
DEBUG: "m" <nil>
DEBUG: "\n" <nil>
Введите возраст: 88
DEBUG: "8" <nil>
DEBUG: "8" <nil>
DEBUG: "\n" <nil>
ВуDezm 88

**Comment by seankhliao** [comment] 2021-04-05 07:48
So `fmt` is correctly processing what comes in on STDIN, you'll have to look elsewhere to find why the extra characters are passed to the program.

Closing as this is not a bug with Go

**Closed by seankhliao** 2021-04-05 07:48 UTC
Labels: WaitingForInfo
