### ISSUE TITLE
cmd/go go get module@commit refuses to update package when commit is specified

### ISSUE THREAD

**Issue by andig** [golang/go#47865] opened 2021-08-21 10:15 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/andig/Library/Caches/go-build"
GOENV="/Users/andig/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/andig/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andig/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/andig/htdocs/evcc/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sv/rs_453y57xj86xsbz3kw1mbc0000gn/T/go-build1926757172=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.17 darwin/arm64
GOROOT/bin/go tool compile -V: compile version go1.17
uname -v: Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101
ProductName:	macOS
ProductVersion:	11.5.2
BuildVersion:	20G95
lldb --version: lldb-1205.0.28.2
Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
</pre></details>

### What did you do?

I've transferred a repo and try to get the dependent repos to compile again:

    ❯ go mod tidy
    go: github.com/evcc-io/config@v0.0.0-20210516083211-8b5c1c7bd5b0: parsing go.mod:
        module declares its path as: github.com/andig/evcc-config
                but was required as: github.com/evcc-io/config

    ❯ go get github.com/evcc-io/config
    go: github.com/evcc-io/config@v0.0.0-20210516083211-8b5c1c7bd5b0: parsing go.mod:
        module declares its path as: github.com/andig/evcc-config
                but was required as: github.com/evcc-io/config

    ❯ go get github.com/evcc-io/config@master
    go: github.com/evcc-io/config@v0.0.0-20210516083211-8b5c1c7bd5b0: parsing go.mod:
        module declares its path as: github.com/andig/evcc-config
                but was required as: github.com/evcc-io/config

    ❯ go get github.com/evcc-io/config@4752346

    go: github.com/evcc-io/config@v0.0.0-20210516083211-8b5c1c7bd5b0: parsing go.mod:
        module declares its path as: github.com/andig/evcc-config
                but was required as: github.com/evcc-io/config

### What did you expect to see?

`go get` updates to latest commit `4752346` which has the correct module name

### What did you see instead?

`go get` doesn't fetch latest commit and complains about mismatching module name

**Comment by seankhliao** [comment] 2021-08-21 10:29
Can't reproduce this

```
main » go mod init example
go: creating new go.mod: module example

main » go get -d github.com/evcc-io/config@4752346
go get: added github.com/evcc-io/config v0.0.0-20210821100131-47523461441a
go get: added github.com/spf13/pflag v1.0.5
go get: added gopkg.in/yaml.v2 v2.3.0

main » cat go.mod
module example

go 1.17

require (
	github.com/evcc-io/config v0.0.0-20210821100131-47523461441a // indirect
	github.com/spf13/pflag v1.0.5 // indirect
	gopkg.in/yaml.v2 v2.3.0 // indirect
)
```

**Comment by andig** [comment] 2021-08-21 10:42
I think the reason is that- at time of running go get- the go.mod contained (not sure how it got there):

    	github.com/evcc-io/config v0.0.0-20210516083211-8b5c1c7bd5b0

Instead of updating the package to the correct commit, go mod seems keep in resolving the existing imports first. Maybe it should exclude the import that it tries to update from doing so?

**Comment by seankhliao** [comment] 2021-08-21 10:59
Duplicate of #45527

**Closed by seankhliao** 2021-08-21 10:59 UTC
Labels: WaitingForInfo
