### ISSUE TITLE
import/path: embed failure with files with double quotes, special characters

### ISSUE THREAD

**Issue by ro-ag** [golang/go#65896] opened 2024-02-23 06:58 UTC
### Go version

go version go1.22.0 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/rodox/Library/Caches/go-build'
GOENV='/Users/rodox/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/rodox/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/rodox/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/opt/go/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/opt/go/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/rodox/GolandProjects/arrow-csv/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/hk/qjtmb35x72qd6p05nx11zyp40000gn/T/go-build2708154695=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

I am experiencing an issue with Go's embed package and files that contain double quote characters (") in their names.
The embed package seems to be failing to recognize these files and ends up ignoring them. 

[embed.tar.gz](https://github.com/golang/go/files/14382402/embed.tar.gz)

### What did you see happen?

trying to access the files in the embed.FS object

### What did you expect to see?

the complete list of files once these are embedded

**Comment by seankhliao** [comment] 2024-02-23 12:28
https://pkg.go.dev/embed

> Patterns must not match files outside the package's module, such as ‘.git/*’ or symbolic links. Patterns must not match files whose names include the special punctuation characters " * < > ? ` ' | / \ and :. Matches for empty directories are ignored. After that, each pattern in a //go:embed line must match at least one file or non-empty directory.

Closing as working as intended.

**Closed by seankhliao** 2024-02-23 12:28 UTC
