### ISSUE TITLE
go/types, types2: type inference should unify interface types

### ISSUE THREAD

**Issue by cr7pt0gr4ph7** [golang/go#51593] opened 2022-03-10 16:28 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.19-5a040c5a36 Thu Mar 10 09:12:04 2022 +0000
</pre>

### Does this issue reproduce with the latest release?
Probably also with 1.18rc1, haven't had a chance to test it yet.

### What operating system and processor architecture are you using (`go env`)?
Gotip Playground.

### What did you do?
Experimenting with type inference and anonymous interface types as constraints and/or inference inputs.

```go
package main

type BasicAnon = interface {
	M() int
}

func InferAnon[I interface{ M() R }, R any](arg I) {
}

func main() {
	var a BasicAnon
	InferAnon(a) // crash due to this line
	_ = a
}
```

https://gotipplay.golang.org/p/lJOnm9LexpD

### What did you expect to see?
Either a compiler error, or a successful compilation.

### What did you see instead?
A compiler crash due to an assertion failure in `(*cycleFinder).typ` on this line:

```go
case *Signature:
	// There are no "method types" so we should never see a recv.
	assert(t.recv == nil)
	...
```

The assumption made in the comment is obviously not true with respect to interface method types, for which `(*Signature).Recv()` is set to the declaring interface's type.

**Comment by findleyr** [comment] 2022-03-10 17:17
CC @griesemer

**Comment by griesemer** [comment] 2022-03-10 17:20
Conservatively marking as a release blocker.

**Comment by griesemer** [comment] 2022-03-10 18:06
Slightly simplified reproducer:
```Go
package p

func f[P interface{ m() R }, R any](P) {}

func _() {
	var x interface { m() int }
	f(x)
}
```

**Comment by cr7pt0gr4ph7** [comment] 2022-03-10 18:06
I've been experimenting a bit, and made the following discoveries (using a modified version of `go/types`):

* After disabling the assertion, the example code given above causes the compiler error `cannot infer R`, as should probably be expected.

* But the following code then infers & typechecks without problems, although it ought not to, given my current understanding of the intended behavior of type inference (#41176):

```go
package main

type BasicAnon = interface {
	M() int
}

func InferAnon[I []interface{ M() R }, R any](arg I) {
}

func main() {
	var a []BasicAnon
	InferAnon(a)
	_ = b
}
```

So, it seems that the implementation already kind-of supports type inference via interface methods, probably as an artifact of the unification algorithm mirroring the type equality/assignability algorithm.

**Comment by griesemer** [comment] 2022-03-10 19:19
The assertion is clearly wrong and needs to be removed - we can see signatures of interface methods in that code. The constraint type inference fails at the moment for `R` because there's no "core term" in this case (implementation-wise). I have a 3-line fix but I am not confident yet that it is correct under all circumstances.

In any case, thanks for this bug report. At the very least we will address the crash for 1.18.

**Comment by cr7pt0gr4ph7** [comment] 2022-03-10 21:04
As mentioned above, I'd caution that it seems that the generics type checking code currently is a bit inconsistent in that it allows unification of some constructs (e.g. `[]interface{M() int}` unifies with `[]interface{M() R}` (with `R` unified to `int`), but `interface{M() int}` does not unify with `interface{M() R}`).

How bad this is with respect to the release depends on whether such "structural inference" (for the lack of a better word) for interfaces is intended to be allowed in the future for all cases, or forbidden for all cases. In the former case, one should probably also allow unification of `interface{M() int;N()}` with `interface{M() T}` during constraint type inference.

I've played around a bit at https://github.com/cr7pt0gr4ph7/go-types-experiments and https://gotipplay.golang.org/p/W-HYHRcmIXD and got the extended inference to work quite trivially, but that is definitel out of scope for this issue.

**Comment by griesemer** [comment] 2022-03-10 21:14
The spec section on type inference will eventually need to be refined/rewritten. We're not going to change anything else here besides fixing the crash for 1.18. As long as we are not inferring incorrect types, we're ok. Eventually we would like to infer these "obvious" cases. As a consequence, code that may not be valid now (inference fails) may become valid in the future (which is ok), but hopefully not the other war around (which is not ok).

**Comment by griesemer** [comment] 2022-03-11 05:59
Once this is cherry-picked into the 1.18 release branch, this is not a release blocker anymore and can be marked for Go 1.19.

**Comment by dmitshur** [comment] 2022-03-14 16:25
The cherry-pick commit 8706c09 (CL 391796) has landed on release-branch.go1.18. Per comment above, removing release-blocker and moving to Go1.19 milestone.

**Comment by findleyr** [comment] 2022-11-10 20:02
Moving to 1.21 as it likely requires a proposal.

**Closed** 2023-03-01 21:24 UTC
Labels: NeedsFix, TypeInference
