### ISSUE TITLE
cmd/go: "go version" fails if CWD is deleted

### ISSUE THREAD

**Issue by dotaheor** [golang/go#34499] opened 2019-09-24 15:31 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

true

### What did you do?

```
$ cd /tmp
$ mkdir aaa
$ cd aaa
$ go version
go version go1.13 linux/amd64
$ rmdir ../aaa
$ go version
2019/09/24 11:26:36 cannot determine current directory: getwd: no such file or directory
$ which go
sh: 0: getcwd() failed: No such file or directory
/home/myname/go-sdk/bin/go
```

### What did you expect to see?

`go version` should be unrelated to CWD.

### What did you see instead?

`go version` needs to confirm CWD.

**Comment by mvdan** [comment] 2019-09-24 17:38
How realistic is this scenario? I agree that technically this should work, but in practice `cmd/go` does quite a bit of work at init time, before the `main` function or the `version` command are run. This includes getting the current working directory.

I assume this helps keep the global simpler, as one can rely on `base.Cwd` to be valid. We could move the error check out of init and into each of the uses of `Cwd`, perhaps turning it into a function like `base.Cwd()` that would run `os.Getwd` the first time it's called instead of at init time.

I'm just not convinced that this is worth the effort. For example, do we want to add `cmd/go` tests where the current directory has been removed?

/cc @bcmills @jayconrod

**Comment by bcmills** [comment] 2019-09-24 17:56
I think it would be fine to accept a fix for this, provided that the fix is not too invasive in practice, but I do not plan to fix it myself.

CC @jayconrod

**Comment by AndersonQ** [comment] 2019-09-25 12:49
I was trying to reproduce and investigate, but I cannot. It might be platform/shell specific

###What version of Go are you using (`go version`)?
$ go version
go version go1.13 darwin/amd64

### What did you do?

```
$ cd /tmp
$ mkdir aaa
$ cd aaa
$ go version
go version go1.13 darwin/amd64
$ rmdir ../aaa
$ go version
go version go1.13 darwin/amd64
```

It works on both zsh and bash for me

**Comment by bcmills** [comment] 2019-09-25 13:59
@AndersonQ, note that the original report was on `linux`. The filesystem on `darwin` platforms tends to behave differently.

**Comment by hasitpbhatt** [comment] 2019-09-26 13:10
> I think it would be fine to accept a fix for this, provided that the fix is not too invasive in practice, but I do not plan to fix it myself.

The question here is, do we really want to go for a global singleton route?
Because in principle, Cwd should not be initialized unless it is needed, but adding a singleton will open up lock(multi-threads?), singleton abuse and all sorts of other things.

**Closed** 2021-05-05 01:29 UTC
Labels: GoCommand, NeedsFix, help wanted
