### ISSUE TITLE
website: problem with a redirect from golang.org/cl to go-review.googlesource.com

### ISSUE THREAD

**Issue by cristaloleg** [golang/go#28881] opened 2018-11-20 09:20 UTC
### What did you do?

Opening a link to changes in Go from golang-cls bot on Gophers Slack https://golang.org/cl/150159/

### What did you expect to see?

Be redirected to https://go-review.googlesource.com/c/go/+/150159

### What did you see instead?

'No issue exists with that id (150159)' https://codereview.appspot.com/150159

Interesting thing, that for https://golang.org/cl/92295/ it works fine
and redirects to https://go-review.googlesource.com/c/go/+/92295/

**Comment by agnivade** [comment] 2018-11-20 09:35
Duplicate of https://github.com/golang/go/issues/28836.

The tip is already patched with a fix. It just needs to be deployed.

**Closed by agnivade** 2018-11-20 09:35 UTC
