### ISSUE TITLE
Panic after switch to go 1.22

### ISSUE THREAD

**Issue by Salfeto4ka** [golang/go#65708] opened 2024-02-14 13:50 UTC
### Go version

1.20, 1.22

### Output of `go env` in your module/workspace:

```shell
gcflags='-l=4
ldflags "-w -s
```

### What did you do?

In my service i switch from golang 1.20 to golang 1.22 with code:
`
bytes := []byte(str) // str is empty
v := [bytes[:1]]
`
use conversion from string to bytes with empty string, and after that use [:1] slice create for my []byte slice

### What did you see happen?

Panic after [:1] in slice of bytes, becouse of his capacity = 0, but in go 1.20 after you create a slice of bytes from empty string, slice had created with capacity 32.
Is this expected behavior? 

### What did you expect to see?

expected to not see panic

**Comment by thanm** [comment] 2024-02-14 14:05
Thanks for the report.  This isn't enough detail to be actionable -- could you please post a playground link or more concrete/detailed example with specific code.

**Comment by thanm** [comment] 2024-02-14 15:29
Thanks for the clarification.  I am pretty surprised that the code in question doesn't panic as well for 1.21, the 1.22 behavior looks standard-conforming to me.  Closing this out as not a bug.

**Closed by thanm** 2024-02-14 15:29 UTC

**Comment by Jorropo** [comment] 2024-02-14 15:37
In 1.21 the `[]byte` is handled by `runtime.stringtoslicebyte` which would be called with a 32 byte temporary buffer:
```x86asm
  LEAQ main..autotmp_3+32(SP), AX ; Temporary buffer here
  XORL BX, BX
  XORL CX, CX
  PCDATA $1, $0
  CALL runtime.stringtoslicebyte(SB)
```
And this line of code does a length reslice:
https://github.com/golang/go/blob/1de46564a766f9647b22ebab0f35bccd14291460/src/runtime/string.go#L170
1.21 would have the same behavior as 1.22 if this line of code was:
```go
		b = buf[:len(s):len(s)]
```
On this matter the spec says:
> 3. Converting a value of a string type to a slice of bytes type yields a non-nil slice whose successive elements are the bytes of the string.

Which defines the content of the byte slice from `s[0:len(s)]`, what the capacity should be is not defined as far as I can tell. 1.22's new `string → []byte` optimizations remove the buffer and literally just pass the string as a slice this way `slice{str.data, str.len, str.len}` which looks legal to me as `cap` is not defined.

I think this can be closed as wontfix, I'm turning this into a spec issue for relevant peoples to confirm.

**Comment by Jorropo** [comment] 2024-02-14 15:39
cc @griesemer I'm not sure `spec` doesn't show up on https://dev.golang.org/owners

**Comment by Jorropo** [comment] 2024-02-14 15:40
Ah well reloading the page I see @thanm closed the issue. lgtm

**Comment by bcmills** [comment] 2024-02-22 20:22
Oddly, the 1.22 behavior seems to depend on escape analysis.

If only `runtime.KeepAlive` is used on the slice, the result of the conversion has a nonzero capacity: https://go.dev/play/p/0LVz7-z0RZQ

However, if the slice escapes, it is has a capacity of zero and the reslice operation panics: https://go.dev/play/p/ctBPGIOrjm7

**Comment by Jorropo** [comment] 2024-02-23 00:31
@bcmills I'm pretty sure 1.21 has the same behavior, this is because the 32 bytes stack allocated scratch buffer cannot be used for slices that escape.
