### ISSUE TITLE
x/tools/gopls: v0.4.4 stops working after some period of time

### ISSUE THREAD

**Issue by 404cn** [golang/go#40567] opened 2020-08-04 08:35 UTC
gopls 0.4.4 consumes tons of memory!

And it killed my computer.

**Comment by mvdan** [comment] 2020-08-04 12:12
You should provide some more detail. What Go version? What were you doing? How can the developers reproduce this issue?

**Comment by ainar-g** [comment] 2020-08-04 17:39
<p>Not the OP, but here are some of my measurements.  Opening
<code>staticcheck</code> source code and making a couple of edits, with
<code>v0.4.3</code>:</p>

<pre><code>$ ps -opid,cmd,rss,vsize -p $(pgrep gopls)
    PID CMD                           RSS    VSZ
  98049 gopls serve                 169016 1450036</code></pre>

<p>Same things with <code>v0.4.4</code>:</p>

<p>Also, while we're at it, using <code>strings.Split</code> instead of
<code>net.SplitHostPort</code> should be flagged as well.</p>

<pre><code>$ ps -opid,cmd,rss,vsize -p $(pgrep gopls)
    PID CMD                           RSS    VSZ
  98956 gopls serve                 212648 1451360</code></pre>

<p>I'm opening
<a href="https://github.com/dominikh/go-tools/blob/e6faca53be3c685bf97e827e24e58ec9297f619e/cmd/staticcheck/staticcheck.go"><code>cmd/staticcheck/staticcheck.go</code></a>
on tag <code>2020.1.5</code>, using Vim <code>8.1</code> with the
<code>natebosch/vim-lsc</code> plugin.</p>

**Comment by stamblerre** [comment] 2020-08-05 15:46
@ainar-g: What is your workspace root when you open these files? Is it the module root or a subdirectory?

**Comment by ainar-g** [comment] 2020-08-05 15:54
<p>@stamblerre  That doesn't seem to matter much.  Using the same
<code>staticcheck</code> example, launching Vim
from the <code>cmd/staticcheck</code> subdir:</p>

<pre>$ ps -opid,cmd,rss,vsize -p $(pgrep gopls)
    PID CMD                           RSS    VSZ
 234017 gopls serve                 225928 1519328</pre>

<p>Launching Vim from project root:</p>

<pre>$ ps -opid,cmd,rss,vsize -p $(pgrep gopls)
    PID CMD                           RSS    VSZ
 234276 gopls serve                 228060 1445404</pre>

**Comment by stamblerre** [comment] 2020-08-05 15:58
The reason I ask is that `gopls/v0.4.3` only loaded the packages in the directory you opened in the editor, whereas `v0.4.4` loads the entire module, no matter which directory you open. I'm guessing that might be the cause of the increased memory usage you are seeing.

**Comment by ainar-g** [comment] 2020-08-05 16:04
<p>Can confirm, opening from the module root with <code>v0.4.3</code>
produces the same memory usage, so I guess my question is solved.
Not sure about the OP's though.</p>

**Comment by ilkeraksu** [comment] 2020-08-05 16:12
> The reason I ask is that `gopls/v0.4.3` only loaded the packages in the directory you opened in the editor, whereas `v0.4.4` loads the entire module, no matter which directory you open. I'm guessing that might be the cause of the increased memory usage you are seeing.

we have mono repo and single module.
I only add only sub packages to VS Code as folder.
 
I had to revert to gopls/v0.4.3 due to excessive memory usage. I went up 16 GB from 1,5GB

Any suggestion for mono repo?

**Comment by stamblerre** [comment] 2020-08-05 16:28
@ilkeraksu: Thanks for the report. This is something we didn't really consider when making this change. I think for v0.4.5, we will add a setting that users working in larger modules can configure to limit their workspace scope.

**Comment by stamblerre** [comment] 2020-08-11 01:58
@ilkeraksu: You should now be able to update to `gopls` at master (`GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`) and add the following to your settings:

```json5
"gopls": {
    "expandWorkspaceToModule": false
}
```

**Comment by ilkeraksu** [comment] 2020-08-11 13:17
@stamblerre  Thank you for quick fix.

this setting prevented execessive usage ( otherwise computer went crazy )

Maybe another issue,
But some behaviour changed badly from 0.4.3 to 0.4.4. Intellisense working intermittently , works for 3-4 seconds then stops for a while up to 1-2 minutes then work for 3-4 secods again 


I would like to elaborate our usage for understanding,

* MonoRepo
* Single module, placed in the root
* Lots of apps and packages

```
repo
 + go.mod
 + go.sum
 +-packages
 	+-package01
        + ....
	+-package N
 +-services
 	+-service1
 		+-package01
                + ....
 		+-package N
 	+-service2
 		+-package01
                + ....
 		+-package N
 +-tools
 	+-tool1
 		+-package01
                 + ....
 		+-package N
+ ...
```


Usually we work on 2-3 services at once so 
	Create vscode workspace for main task at hand
	Add related services to workspace
	Add related packages as needed


Of course we have 5-6 utility kind, supporting packages always used (imported) in almost every where ( like errors, logging etc)   
and these packages is not included in workspace

**Comment by stamblerre** [comment] 2020-08-11 15:22
Thanks for the clarification - that makes sense. This new configuration should work for your use case.

I'm not sure what would've changed to cause features to stop working. Can you please attach your `gopls` logs from when you see this happening? Instructions on how to capture them can be found [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs).

**Comment by ilkeraksu** [comment] 2020-08-12 08:08
Hi @stamblerre ,

These are logs when I typed    **dev.P**   expecting complete methods . Typed 1 seconds apart each key.
package "su/pkg/dev" already imported and also included as folder in workspace
I tried to keep try small if you need more I can get more

[2020-08-12-10-56 _gopls.txt](https://github.com/golang/go/files/5061355/2020-08-12-10-56._gopls.txt)

**Comment by stamblerre** [comment] 2020-08-12 15:35
@ilkeraksu: Do you mind providing a log that starts at the time that `gopls` is started? I don't see anything obviously wrong in the log you provided, but there may be errors logged when `gopls` initializes the workspace.

**Comment by ilkeraksu** [comment] 2020-08-13 13:59
Hi @stamblerre ,
Full log attached .
Again intermittently could completed and failed to complete

most of the time I tried **e.E** and  **dev.P** . These packages were already imported.

Hope this helps,
Thank you
[2020-08-13-16-00_gopls.txt.zip](https://github.com/golang/go/files/5069454/2020-08-13-16-00_gopls.txt.zip)

**Comment by stamblerre** [comment] 2020-08-13 22:39
I did find one issue, which will be fixed in https://golang.org/cl/248400, but I didn't notice anything that stood out to me in your logs.

Do you have a repro case possibly? When completion stops working, is it in all cases or only some? Do other features stop working too?

**Comment by ilkeraksu** [comment] 2020-08-14 15:27
Looks like problem arise under stress,
We usually do pair programing, zoom is open and screen shared most of the time. 

with 0.4.3, I don't have this issue 

with 0.4.4, Under CPU and Memory stress. (zooom open) I have problem 
( 8GB RAM, gopls use 1.13 GB Real Mem 1,5 GB swap used, but activity monitor   Memory Pressure is green )

with 0.4.4  no CPU stress, zoom closed, no problem.

When problem happens other features seem to work, like going definition or hover can show func signature 

we may have some kind of timeout problem ( my two cents)

**Comment by stamblerre** [comment] 2020-08-14 17:44
To clarify, when you say `v0.4.4`, do you mean exactly `v0.4.4` or master with `expandWorkspaceToModule` set to false?

**Comment by ilkeraksu** [comment] 2020-08-14 17:51
With 0.4.4 I mean master with expandWorkspaceToModule set to false.

**Comment by stamblerre** [comment] 2020-08-17 02:32
Thanks for clarifying. It might be easier to understand if you can produce a smaller log that demonstrates the issue. @heschik also mentioned that the issue may be related to your Dropbox workspace folder, but if the issue doesn't reproduce with v0.4.3 that might not be a likely explanation. Still, it may be worth checking if you can link the issue back to a specific one of your workspace folders, since there are many.

**Comment by stamblerre** [comment] 2020-09-14 18:03
Closing as this is in the WaitingForInfo state and `gopls/v0.5.0` will be released soon. Please open a new issue if you still have this issue with `gopls/v0.5.0-pre3` (`GO111MODULE=on go get golang.org/x/tools/gopls@v0.5.0-pre3`.

**Closed by stamblerre** 2020-09-14 18:03 UTC
Labels: Tools, WaitingForInfo, gopls
