### ISSUE TITLE
illumos binaries broken when built using golang:1.17 Docker image

### ISSUE THREAD

**Issue by calmh** [golang/go#48262] opened 2021-09-08 20:19 UTC
It appears like the Go Docker image `golang:1.17` is not capable of building illumos/Solaris binaries. I don't understand why that is because it works locally on Mac, and it works in the `golang:1.16` image.

### What version of Go are you using (`go version`)?

<pre>
% docker run -it --rm -v $(pwd):/src/hello -w /src/hello golang:1.17 go version
go version go1.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
% docker run -it --rm -v $(pwd):/src/hello -w /src/hello golang:1.17 go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/src/hello/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2751576647=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Consider a trivial main package:

```
% mkdir hello
% cd hello
% go mod init example.com/hello
% cat > main.go
package main

import "fmt"

func main() { fmt.Println("hello") }
```

*On my Mac* this builds an illumos binary:

```
% go version
go version go1.17 darwin/amd64
% GOOS=illumos GOARCH=amd64 go build
% file hello
hello: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/amd64/ld.so.1, Go BuildID=eJLPJJxCT5s2hSqGiorF/vXHAnExSvn2Xbt_UHq4G/LNjd8vYoT-PfGyPdI8iH/5Y4Js88Tmn8KHz2WoLz2, not stripped
```

*Using Docker* it builds something Linuxy:

```
% docker run -it --rm -v $(pwd):/src/hello -w /src/hello golang:1.17 sh -c 'GOOS=illumos GOARCH=amd64 go build'
% file hello
hello: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=XjMYCX85VbEjh18QC1rv/upntO9Sq8Q2lxbJkw5NW/Vx6W7--kuc7Nm7SHwv8B/wNfvaYltFVcSNcQFTIsf, not stripped
```

(This does not run under illumos because it does not have ld-linux-x86-64.so.2)

Using the *older golang:1.16 image* it works as expected:

```
% docker run -it --rm -v $(pwd):/src/hello -w /src/hello golang:1.16 sh -c 'GOOS=illumos GOARCH=amd64 go build'
% file hello
hello: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/amd64/ld.so.1, Go BuildID=18ozu_ElefHOc7ctdQ1T/r0aSYbgfKqbG_26ONcqf/ZwWdiXIO3vPVhkNK0Ot3/yG8VYroOw_TZ8KFWSISU, not stripped
```

**Comment by seankhliao** [comment] 2021-09-08 20:21
Duplicate of #47760

**Closed by seankhliao** 2021-09-08 20:21 UTC
