### ISSUE TITLE
cmd/compile: ICE from failed assertion

### ISSUE THREAD

**Issue by ThinkChaos** [golang/go#66568] opened 2024-03-27 21:40 UTC
### Go version

Go 1.22 regression (1.21 works)

### Output of `go env` in your module/workspace:

Not relevant, happens on Go playground: https://go.dev/play/p/mJULW_pJBIf

### What did you do?

Compile the following program:

```go
package main

func main() {}

func fail() {
	return

	something := false

loop:
	for {
		if something {
			break loop
		}
	}
}
```

### What did you see happen?

Compiler assert

### What did you expect to see?

No crash

**Comment by randall77** [comment] 2024-03-27 22:01
Closing as a duplicate of #65593.
Fix will be out in the next 1.22 release.

**Closed by randall77** 2024-03-27 22:01 UTC
Labels: compiler/runtime
