### ISSUE TITLE
x/crypto/acme/autocert: no way to generate RSA certificates

### ISSUE THREAD

**Issue by niemeyer** [golang/go#17744] opened 2016-11-02 17:06 UTC
Let's Encrypt supports generation of RSA certificates, and the code can be easily adapted to support them by simply changing the private key generation functions, but there's currently no way to enable that from the outside.

**Comment by bradfitz** [comment] 2016-11-02 17:19
@x1ddos, what's the plan here? Didn't you recently change it away from RSA?

**Comment by x1ddos** [comment] 2016-11-03 15:11
@niemeyer the initial implementation in fact used solely RSA keys. Some code reviewers have been repeatedly suggesting to switch to EC, arguing that most modern clients support EC-based certs now, which I agreed with. I haven't seen a need for RSA since then, except when forced to integrate with a legacy system (which led to things like https://go-review.googlesource.com/27750).

To accommodate broader needs, there was another proposal: generate 2 certs, RSA + EC, and provide the one compatible with what [ClientHelloInfo](https://golang.org/pkg/crypto/tls/#ClientHelloInfo) indicates.

Would that work for your use case?

**Comment by x1ddos** [comment] 2016-11-03 15:13
Ah @bradfitz no, not recently. Well, quite short after autocert was released. For instance, see this: https://go-review.googlesource.com/28851.

**Comment by x1ddos** [comment] 2016-11-03 15:26
@bradfitz sorry, yeah I meant we did switch from RSA to EC :)
(I should slow down when reading)

**Comment by titanous** [comment] 2016-12-15 19:41
This is a duplicate of #17744, but I believe #17744 should be closed as this issue is clearer and has more discussion.

**Comment by bradfitz** [comment] 2016-12-15 19:46
@x1ddos, your two-cert proposal works. Or a simple boolean option for now too. (ForceRSA bool)

But let's do something soonish so more people can use autocert.

**Comment by x1ddos** [comment] 2016-12-15 19:49
Ok! I'll work on tomorrow and send a cl for review.

**Closed** 2016-12-16 17:19 UTC
