### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by ahaoozhang** [golang/go#32890] opened 2019-07-02 08:10 UTC
How to modify the permissions of the package downloaded by gomod？

**Comment by AlexRouSg** [comment] 2019-07-02 08:21
You do it manually the same way you would with any other file/directory.

If you want to delete everything you can use `go clean -modcache`

**Comment by ALTree** [comment] 2019-07-02 08:38
What @AlexRouSg said. They're set to read-only by design (see #27455 for background). Closing here.

**Closed by ALTree** 2019-07-02 08:38 UTC
Labels: Question
