### ISSUE TITLE
cmd/go: cannot fetch gitlab repo using git:// using insteadOf (macOS git 2.19.1)

### ISSUE THREAD

**Issue by denisemauldin** [golang/go#28422] opened 2018-10-26 16:14 UTC
### What version of Go are you using (`go version`)?
go 1.11.1 darwin/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dmauldin/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/dmauldin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_t/sfww_0f53kl1_9x3hj3p5d100000gn/T/go-build553492779=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?  What did you expect to see? What did you see instead?

Installed go and attempted to use `go get` to fetch a gitlab repository via git:// instead of https://

I found this URL: https://github.com/golang/go/issues/6968

I added a git config for my URL.
```
[url "git@gitlab.<myhost>:"]
    insteadOf = https://gitlab.<myhost>/
```

Running `go get gitlab.<myhost>/blah/blah.git` returns `unrecognized import path` with the `https` url still in the `https fetch` (which gets a `connection refused`).  Is `insteadOf` still the correct way to do this as per the linked issue?

**Comment by andybons** [comment] 2018-10-26 16:48
Hi @denisemauldin,
Can you paste the output of `go get -u -v gitlab.<myhost>/path/to/pkg`?

What is the output of `curl https://gitlab.<myhost>/path/to/pkg?go-get=1`?

On gitlab.com, it returns a meta tag for the `go` command regardless of whether the package even exists or whether you're logged in:

```
$ curl https://gitlab.com/andybons/pkg?go-get=1
<html><head><meta name="go-import" content="gitlab.com/andybons/pkg git https://gitlab.com/andybons/pkg.git" /></head></html>
```

With the following settings in my `.gitconfig`, `insteadOf` appears to work for me when I attempt to download a private package of mine at gitlab:
```
[url "git@gitlab.com:"]
	insteadOf = https://gitlab.com/
```

This leads me to believe that git isn't broken (I'm using 2.19.1 as well) But I don't have access to a custom host, so it's difficult for me to diagnose further.

**Comment by denisemauldin** [comment] 2018-10-26 17:03
@andybons  Here's the output for your questions.  Our host is internal/local and does not support https, which is why I'm trying to change git from using https:// to git://.  Thanks.

```
09:56 $ go get -u -v gitlab.myhost/myteam/myproject.git
gitlab.myhost/myteam/myproject.git (download)
github.com/Masterminds/sprig (download)
github.com/Masterminds/semver (download)
github.com/aokoli/goutils (download)
github.com/google/uuid (download)
github.com/huandu/xstrings (download)
github.com/imdario/mergo (download)
Fetching https://golang.org/x/crypto/scrypt?go-get=1
Parsing meta tags from https://golang.org/x/crypto/scrypt?go-get=1 (status code 200)
get "golang.org/x/crypto/scrypt": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/scrypt?go-get=1
get "golang.org/x/crypto/scrypt": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
Fetching https://golang.org/x/crypto/pbkdf2?go-get=1
Parsing meta tags from https://golang.org/x/crypto/pbkdf2?go-get=1 (status code 200)
get "golang.org/x/crypto/pbkdf2": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/pbkdf2?go-get=1
get "golang.org/x/crypto/pbkdf2": verifying non-authoritative meta tag
github.com/aws/aws-xray-sdk-go (download)
github.com/aws/aws-sdk-go (download)
github.com/cihub/seelog (download)
github.com/pkg/errors (download)
github.com/go-chi/render (download)
github.com/gofrs/uuid (download)
Fetching https://gitlab.myhost/myteam/myproject/pkg/task?go-get=1
https fetch failed: Get https://gitlab.myhost/myteam/myproject/pkg/task?go-get=1: dial tcp 10.X.X.X:443: connect: connection refused
gitlab.myhost/myteam/myproject (download)
# cd /Users/dmauldin/go/src/gitlab.myhost/myteam/mypackage; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> updated_docs

package gitlab.myhost/myteam/myproject/pkg/task: exit status 1
```

`What is the output of curl https://gitlab.<myhost>/path/to/pkg?go-get=1?`

Our host does not support https.  `curl: (7) Failed to connect to gitlab.myhost port 443: Connection refused`

**Comment by andybons** [comment] 2018-10-26 18:14
@denisemauldin Thank you for following up with the output. The issue is that your server does not support SSL/TLS (https) so it can't get at the meta tags needed by the `go` command to even use the git:// URL. My advice would be to encourage whomever administrates the local server to enable https://.

I'm sorry that I don't have a better solution for you. More context can be found at https://github.com/golang/go/issues/27254#issuecomment-433112589

Closing out for now. Please comment if you feel this was in error.

**Closed by andybons** 2018-10-26 18:14 UTC
Labels: NeedsInvestigation, WaitingForInfo
