### ISSUE TITLE
x/crypto: chacha20 lacks method to set counter, which is needed for QUIC

### ISSUE THREAD

**Issue by marten-seemann** [golang/go#36862] opened 2020-01-29 10:29 UTC
QUIC uses ChaCha20 for its header protection: https://tools.ietf.org/html/draft-ietf-quic-tls-25#section-5.4.4. In order to calculate the header protection mask, a QUIC implementation needs to be able to set the counter based on the ciphertext:
> The first 4 bytes of the sampled ciphertext are the block counter.

Unfortunately, x/crypto/chacha20 currently doesn't provide an API to manually set the counter, and I therefore have to maintain [a fork](https://github.com/marten-seemann/chacha20/) for my [quic-go](https://github.com/lucas-clemente/quic-go).

I already brought this up in https://github.com/golang/go/issues/24485#issuecomment-528797526, and @FiloSottile suggested adding a `SetCounter` method, but it looks like this issue was closed without exposing this method.

**Comment by FiloSottile** [comment] 2020-01-29 17:32
Duplicate of #35506.

**Closed by FiloSottile** 2020-01-29 17:32 UTC
