### ISSUE TITLE
Possible unexpected assignment when using built-in max function

### ISSUE THREAD

**Issue by aeiou335** [golang/go#64564] opened 2023-12-05 18:50 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.4 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/aeiou335/Library/Caches/go-build'
GOENV='/Users/aeiou335/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/aeiou335/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/aeiou335/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/30/0s1t_qw53q3_8xqtqk1tkp_c0000gn/T/go-build1266853270=/tmp/go-build -gno-record-gcc-switches -fno-common'
uname -v: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
lldb --version: lldb-1300.0.32.4
Swift version 5.5.1-dev
</pre></details>

### What did you do?

Unexpected result using built-in max function when iterating string.

Please refer to the example below.
https://go.dev/play/p/PbMbIOKhdjE

### What did you expect to see?
built-in max function assigned unexpected result

### What did you see instead?
built-in max function should assign correct result

**Comment by mighmi** [comment] 2023-12-05 18:59
I duplicated this with #64565 which offers context and credit to the discovers reddit users /u/YamadaAnna and /u/ar1819 who found it here https://www.reddit.com/r/golang/comments/18be9xl/max_and_assign_issue/ a few hours ago.

**Comment by seankhliao** [comment] 2023-12-05 20:54
Duplicate of #64565

**Closed by seankhliao** 2023-12-05 20:54 UTC
