### ISSUE TITLE
Remember to include CLI Go source files in `go mod vendor` cache

### ISSUE THREAD

**Issue by mcandre** [golang/go#35502] opened 2019-11-11 16:37 UTC
Please don't strip `cmd` paths from `go mod vendor` caches. Altering the source cache makes it that much harder to track tool dependencies and debug Go systems generally.

**Comment by bcmills** [comment] 2019-11-11 17:08
Per https://golang.org/cmd/go/#hdr-Make_vendored_copy_of_dependencies:

> Vendor resets the main module's vendor directory to include all packages needed to build and test all the main module's packages.

CLI `main` packages are not importable, and thus are not “needed to build and test all the main module's packages” (in the sense of `go build` or `go test`). Therefore, they are omitted by design.

**Comment by bcmills** [comment] 2019-11-11 17:10
Duplicate of #29516

**Closed by bcmills** 2019-11-11 17:10 UTC
