### ISSUE TITLE
x/pkgsite: ioutil/Readfile does not run correctly in pkg.go.dev example.

### ISSUE THREAD

**Issue by TimothyStiles** [golang/go#49036] opened 2021-10-18 12:02 UTC
Hello!

I think I've found a bug where example tests won't run properly in `go.pkg.dev` if they use any sort of file io.

### What is the URL of the page with the issue?
https://pkg.go.dev/io/ioutil#example-ReadFile

### What is your user agent?
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0

### Screenshot
![Screen Shot 2021-10-18 at 4 48 05 AM](https://user-images.githubusercontent.com/7042260/137726001-9bbdaa6b-533e-4251-8dc6-c6055e32c5c4.png)

### What did you do?
I tried running this [example](https://pkg.go.dev/io/ioutil#example-ReadFile) from ioutil's docs. It returns the error after hitting the run button but renders the correct output by default.

### What did you expect to see?
I expected to see the file's contents as printed output after hitting the run button

### What did you see instead?
This:
![crop-output](https://user-images.githubusercontent.com/7042260/137741703-0a729702-32ae-4e37-a9dc-791729a0c347.png)

It looks like the example's isolated environment doesn't have the file used in this test example. Which means that tests will run and pass locally and on CI/CD but not on `pkg.go.dev` itself. Is there any way to include the file in this rendered example's environment?

Thanks!
Tim

P.S

Looks like this is also the case for [os.ReadFile](https://pkg.go.dev/os#ReadFile).

**Comment by seankhliao** [comment] 2024-12-04 22:53
Duplicate of #19825

**Closed by seankhliao** 2024-12-04 22:53 UTC
Labels: NeedsInvestigation, FrozenDueToAge, pkgsite
