### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by vinnie8** [golang/go#53312] opened 2022-06-09 15:59 UTC
### What is the URL of the page with the issue?
 
 https://go.dev/doc/tutorial/greetings-multiple-people
 
### What is your user agent?

 [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)

 
![image](https://user-images.githubusercontent.com/28985961/172890900-7e4b7319-950d-4918-be02-d027f8c0d3f9.png)
 
 
### What did you do?
 
I did tutorial and found my program doesn't work
Then i found that important part of code was not highlighted. 

 
Please highlight the tutorial code as shown on screenshot

Thx

**Comment by seankhliao** [comment] 2022-06-09 17:10
Duplicate of #46416

**Closed by seankhliao** 2022-06-09 17:10 UTC
Labels: website
