### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by jghagemann** [golang/go#49711] opened 2021-11-22 00:10 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.17.3

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 20.04 LTS

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Following the "Return greetings for multiple users" tutorial

### What did you expect to see?

In the hello.go example code, lines:
    messages, err := greetings.Hellos(names)
and
    fmt.Println(messages)

Should also be marked as they refer to the newly created slice, otherwise VSCode detects errors

### What did you see instead?
The lines referred to above we're not marked as changes

Apologies if this is so simple that it shouldn't be here, but it was the only way I found to point it out
![Screenshot from 2021-11-21 21-07-50](https://user-images.githubusercontent.com/42047435/142784596-b2d4dafd-95d3-4873-911e-9fb77edce74b.png)

**Comment by seankhliao** [comment] 2021-11-22 05:58
Duplicate of #46416

**Closed by seankhliao** 2021-11-22 05:58 UTC
