### ISSUE TITLE
x/tools/go/packages: allow user to specify go command

### ISSUE THREAD

**Issue by jimmyfrasche** [golang/go#27785] opened 2018-09-20 22:22 UTC
When using an alternate `go` tool, like `goX.XXbetaY`, prototypes like `vgo` was or my alias for the `go` command built from source, `go/packages` will still use `go`.

If it accepted an override from an environment variable like `GOCMD`, it would let many commands based on `go/packages` to seamlessly work with alternate `go` tools and provide a standard for other programs to follow.

cc @alandonovan

**Comment by ianthehat** [comment] 2018-09-21 13:54
I am going to close this as s duplicate of #26845, which is expressed differently but basically the same problem.

**Closed by ianthehat** 2018-09-21 13:54 UTC
Labels: FeatureRequest
