### ISSUE TITLE
x/website: request of "Get rid of BLM header on go.dev and golang.org"

### ISSUE THREAD

**Issue by Pigee** [golang/go#48057] opened 2021-08-30 09:32 UTC
### What is the URL of the page with the issue?
 
 golang.org go.dev
 
### What is your user agent?
 

Chrome
 
 
### What did you do?
 

 wirte go
 
 
### What did you expect to see?
 
 Get rid of BLM header on go.dev and golang.dev
 Gophers do not need a political position
 And do not do it for us.
 
### What did you see instead?

BLM hurts golang

**Comment by seankhliao** [comment] 2021-08-30 09:39
Duplicate of #39850

**Closed by seankhliao** 2021-08-30 09:39 UTC
