### ISSUE TITLE
syscall: SysProcAttr.AmbientCaps fails when creating a new user namespace and creator is not root

### ISSUE THREAD

**Issue by Omnifarious** [golang/go#23152] opened 2017-12-15 21:37 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.9.2

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

Linux - amd64

### What did you do?
	cmd := exec.Command("/bin/sh")
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.SysProcAttr  = &syscall.SysProcAttr{
		Cloneflags : syscall.CLONE_NEWNS | syscall.CLONE_NEWIPC |
		             syscall.CLONE_NEWNET | syscall.CLONE_NEWPID |
                     syscall.CLONE_NEWUSER,
		UidMappings: []syscall.SysProcIDMap {
			{
				ContainerID: os.Getuid(),
				HostID: 	os.Getuid(),
				Size:		1,
			},
		},
		GidMappings: []syscall.SysProcIDMap {
			{
				ContainerID: os.Getgid(),
				HostID: 	os.Getgid(),
				Size:		1,
			},
		},
		AmbientCaps: []uintptr { 8, 21 },
	}
        err := cmd.Start()

I ran this code as a non-root user and the process had no capabilities.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?

I expected the shell started in my new namespace to have certain capabilities.

### What did you see instead?

An error from cmd.Start() when calling prctl(PR_CAP_AMBIENT, PR_CAP_AMBIENT_RAISE, ...) stating that there was an EPERM error.

**Comment by Omnifarious** [comment] 2017-12-15 21:39
I do have a changeset that solves this issue:

https://github.com/Omnifarious/go/commit/5de289af7d366237c4aa3bd3f11a4ffc0bf1e539

**Comment by ianlancetaylor** [comment] 2017-12-15 21:44
CC @stapelberg

**Comment by stapelberg** [comment] 2017-12-15 21:59
I indeed missed this use case when originally introducing the change.

I can confirm that the proposed change does not break things for me, so LGTM from my end.

**Comment by ianlancetaylor** [comment] 2017-12-15 22:18
@Omnifarious Would you be willing to submit the change through the contribution process, which is described at https://golang.org/doc/contribute.html?  Thanks.

**Comment by Omnifarious** [comment] 2017-12-15 22:26
Realistically speaking, there is no way I'll ever take the time to do all of that. This is the only thing I currently anticipate ever contributing to Go. It's about 40 lines of code. It simply adds capabilities that someone wants to be in the ambient set to the inheritable set. I expect, in fact, that I've done it wrong, even though the code works for my particular case.

**Comment by Omnifarious** [comment] 2018-03-13 11:40
So, I had a bunch of time on my hands, and went through the process described there. What do I use for a Change-ID?

**Comment by stapelberg** [comment] 2018-03-13 12:39
Thanks for taking the time.

The change-id will be filled in automatically when you mail out the change.

You can also submit your change as a pull request, which will automatically import it into gerrit.

**Comment by ebfe** [comment] 2018-11-16 23:16
Having this would also alleviate the need for #12125 since it would allow execed process to retain the capabilities needed to do the bind mounts. Is there anything one can do to help moving this forward?

**Closed** 2019-03-08 20:55 UTC
Labels: NeedsInvestigation
