### ISSUE TITLE
cmd/{godoc,vet},testing: godoc disagrees with the docs and vet about validity of example name suffixes

### ISSUE THREAD

**Issue by kortschak** [golang/go#27442] opened 2018-09-01 23:44 UTC
### What version of Go are you using (`go version`)?
```
$ go version
go version go1.11 linux/amd64
```

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
```
~/src/gonum.org/v1/gonum/graph/topo$ go vet
# gonum.org/v1/gonum/graph/topo_test
./2sat_example_test.go:177: ExampleTarjanSCC_2sat refers to unknown field or method: TarjanSCC.2sat
```

However, godoc [renders the 2sat example](https://godoc.org/gonum.org/v1/gonum/graph/topo#example-TarjanSCC--2sat).

### What did you expect to see?
An error from vet and a failure from godoc to render the example.

### What did you see instead?
A vet error but a rendered example.

### What would you like to see?
No error and a rendered example. That is, a relaxation of the [documented](https://golang.org/pkg/testing/#hdr-Examples) requirement for an initial lowercase **letter** in the suffix ("The suffix must start with a lower-case letter.") to allow numeric leading glyphs.

**Comment by agnivade** [comment] 2018-09-02 05:49
The title of the issue suggests that the issue is with godoc. But it seems you want the documented behavior itself to allow numeric characters. In which case, this should be a proposal issue because what you are suggesting is a behavior change. I think allowing numerical characters deviates from our existing language spec, which forces all identifiers to start with a letter (https://tip.golang.org/ref/spec#identifier).

IMO, we should fix godoc to be consistent with the docs and with vet. According to current behavior, godoc should just ignore any examples which do not match the example name rule.

**Comment by dsnet** [comment] 2018-09-02 06:41
The problem is that the [example syntax is fundamentally ambiguous](https://github.com/golang/go/issues/23864#issuecomment-370580696) and ideally all the tools should be consistent about how they resolve that ambiguity. Unfortunately, currently each tool has their own copy of the example parsing logic, and handles this case differently.

I brought up this issue in #23864. Having a unified implementation of example parsing should resolve this problem. Perhaps we close this as a duplicate of that one?

**Comment by kortschak** [comment] 2018-09-02 06:59
I'm happy for this to be closed and subsumed into that. What I would like to be considered though is the rule mentioned above; it does not need to be a lowercase initial, it just needs to not be an uppercase initial.

**Comment by dsnet** [comment] 2018-09-02 07:04
The challenge is that the [logic for `godoc.org` also treats the suffix as anything without an uppercase](https://github.com/golang/tools/blob/a237aba5f578100f4f8419bbda73189b8e6dbae5/godoc/godoc.go#L774-L790) (thus includes numbers), so we'll probably need to update the documentation in the `testing` package to match what has pragmatically been the current state of affairs.

**Closed by dsnet** 2018-09-02 07:04 UTC
Labels: Documentation
