### ISSUE TITLE
x/build: update cloud.google.com/go/errors imports

### ISSUE THREAD

**Issue by adams-sarah** [golang/go#22240] opened 2017-10-12 20:08 UTC
Package was recently deprecated and removed. "errorreporting" is the replacement. May need to modify code to fit new API.
Need to make update-deps too.

**Comment by adams-sarah** [comment] 2017-10-12 20:09
cc @andybons

**Comment by kevinburke** [comment] 2017-10-13 05:25
This is a dupe of #22153.

**Closed** 2017-10-13 18:00 UTC
Labels: Builders
