### ISSUE TITLE
x/website: add clear warning against checking go.work into VCS

### ISSUE THREAD

**Issue by goto1134** [golang/go#62179] opened 2023-08-21 13:16 UTC
Since the original proposal strongly suggests against checking go.work into VCS: 
> go.work files should not be checked into version control repos containing modules so that the go.work file in a module does not end up overriding the configuration a user created themselves outside of the module. The go.work documentation should contain clear warnings about this.
> https://go.googlesource.com/proposal/+/master/design/45713-workspace.md#rationale-the-file

Please add a clear warning against checking `go.work` into VCS to the documentation here: https://go.dev/ref/mod#go-work-file

This issue is inspired by the following Reddit discussion: https://www.reddit.com/r/golang/comments/15v8i06/why_gowork_file_should_not_be_committed/

**Comment by seankhliao** [comment] 2023-08-21 13:48
Duplicate of #53502

**Closed by seankhliao** 2023-08-21 13:48 UTC
Labels: website
