### ISSUE TITLE
proposal: Support conformity like Emerald

### ISSUE THREAD

**Issue by cwmos** [golang/go#63300] opened 2023-09-29 23:49 UTC
### Author background

I would consider myself an intermediate to experienced Go programmer.

I have used a lot of different programming languages. Including the programming language Emerald which this issue is about. That said, I am not an expert in programming languages or Go.

### Proposal
**What is the proposed change?**
In Emerald, there is a very useful concept around *conformity*. If Golang had the same, I believe something like this would compile:

```golang
type a interface {
	aa()
}

type usea interface {
	myMethod(a)
}

type aplusplus interface {
	a
	aapp()
}

type useapluslus interface {
	myMethod(aplusplus)
}

func myFunc(par usea) {
	var _ useapluslus = par
}
```
Currently this fails with a compilation error in the second last line:
```
cannot use par (variable of type usea) as useapluslus value in variable declaration: usea does not implement useapluslus (wrong type for method myMethod)
		have myMethod(a)
		want myMethod(aplusplus)compiler[InvalidIfaceAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#InvalidIfaceAssign)
```
But I don't see why this should not work: The method `myMethod(a)` should be able to receive an argument of type `aplusplus` since that has everything `a` has.

In Emerald there is a similar concept around function return values that would also be useful.

 **Who does this proposal help, and why?**
I think it could be useful in many situations. Concretely, I am working on some code  where I have several different structs like:
```golang
type interface1 interface {
	a1()
}

type struct1 struct {}

func (*struct1) foo(interface1) {}

type interface2 interface {
	a2()
}

type struct2 struct {}

func (*struct2) foo(interface2) {}
```
I would then like to make an interface `struct12` that both struct1 and struct2 match:
```golang
type interface12 interface {
	interface1
	interface2
}

type struct12 interface {
	foo(interface12)
}
```
But they do not..

I did try to use Generics to make something like this work, but that did not seem possible - I think the issue I ran into was basically #48522

**Comment by seankhliao** [comment] 2023-09-30 00:19
Duplicate of #30602

**Closed by seankhliao** 2023-09-30 00:19 UTC
Labels: LanguageChange, v2, Proposal
