### ISSUE TITLE
cmd/trace: TestAnalyzeAnnotationGC flaky

### ISSUE THREAD

**Issue by aclements** [golang/go#24081] opened 2018-02-23 20:05 UTC
TestAnalyzeAnnotationGC has been flaky on Windows and Solaris since it was introduced.

On Windows it fails with:

```
--- FAIL: TestAnalyzeAnnotationGC (0.03s)
	annotations_test.go:243: taskWithGC reported 29.721802ms as overlapping GC time; want (0, 29.2968ms): task 6:	taskWithGC
			start: 16015 end: 30223063 complete: true
			2 goroutines
			2 spans:
				taskWithGC.span1(goid=30)
				taskWithGC.span2(goid=32)
			0 children:
```

On Solaris it fails with:

```
--- FAIL: TestAnalyzeAnnotations (0.00s)
	annotations_test.go:70: failed to analyzeAnnotations: failed to parse trace: failed to open trace file: open : no such file or directory
```

```
$ greplogs -dashboard -E TestAnalyzeAnnotationGC -l | findflakes -paths
First observed cacf812 21 Feb 19:48 2018 (29 commits ago)
Last observed  fceaa2e 23 Feb 16:48 2018 (5 commits ago)
13% chance failure is still happening
33% failure probability (9 of 25 commits)
Likely culprits:
   33% cacf812 cmd/trace: present the GC time in the usertask view
   22% 438a757 cmd/compile/internal: reuse more memory
   15% ac81c5c cmd/compile/internal/ssa: refactor buildLocationLists
   10% e181852 cmd/compile/internal: use sparseSet, optimize isSynthetic
    7% 108efc7 cmd/compile/internal/ssa: shrink commonly-used structs
    4% ebeea20 cmd/compile: use | in the most repetitive ppc64 rules
No known past failures
```

`$ greplogs -dashboard -E TestAnalyzeAnnotationGC -l -md`
[2018-02-21T19:48:35-cacf812/windows-386-2008](https://build.golang.org/log/fb3febc7227f61d9586b2c7076e54984f9b577f6)
[2018-02-21T19:48:35-cacf812/windows-amd64-2016](https://build.golang.org/log/d625e2f6028a233163b990108014c70671113388)
[2018-02-21T20:14:30-3e1ac1b/windows-amd64-2008](https://build.golang.org/log/1fb13acbf9ab229712a4e4ef80d270cd6fe1b97f)
[2018-02-21T20:32:35-ed1959c/windows-amd64-2016](https://build.golang.org/log/4c3f78c86ac657e17347e342fcc2276a1e15462f)
[2018-02-21T21:04:09-e02d6bb/windows-amd64-2012](https://build.golang.org/log/80f21940c0e937f0370f6fd5456b69c83541286b)
[2018-02-22T04:10:07-f4c3072/solaris-amd64-smartosbuildlet](https://build.golang.org/log/9c7c0ff72564251d9079f7f9bb0c366209095f01)
[2018-02-22T15:17:52-ef3ab3f/solaris-amd64-smartosbuildlet](https://build.golang.org/log/3d9dae7995a5f81c9371d664620f70da10244765)
[2018-02-22T16:28:38-2465ae6/windows-386-2008](https://build.golang.org/log/39e7cfd51ed5e6370e5096dc15769821d0558265)
[2018-02-23T13:49:55-9ee78af/windows-386-2008](https://build.golang.org/log/6c4040ec7363198f39fc1f683ee665ee3a92a6b6)
[2018-02-23T16:48:01-fceaa2e/solaris-amd64-smartosbuildlet](https://build.golang.org/log/ca459a03625ad47c6c932d6ecb62fa9756c227b3)
[2018-02-23T16:48:01-fceaa2e/windows-386-2008](https://build.golang.org/log/af8b884c23d3030a844fb6bfd8a555769f5397a9)

/cc @hyangah

**Comment by mvdan** [comment] 2018-02-27 18:41
Another one: https://storage.googleapis.com/go-build-log/95ddc0ea/windows-386-2008_fa97bd6c.log

**Comment by hyangah** [comment] 2018-02-27 23:48
I sent a cl to fix an obvious bug. But the CL doesn't eliminate the flakiness completely. I guess it surfaced  issues with timestamps or trace logging on Windows. I captured a trace from a failed test run on gomote buildlet, where the user code reports 977us for debug.FreeOSMemory call, but the corresponding GCDone-GCStart timestamps report 1.383112ms (also a UI) 

<pre>
$ go tool trace -d TestAnalyzeAnnotationGC.trace.failed  | egrep "GCStart|GCDone"
2018/02/27 18:45:35 Parsing trace...
68810 GCStart p=1000004 g=0 off=403 seq=0
1451922 GCDone p=1 g=0 off=449
</pre>

[TestAnalyzeAnnotationGC.trace.failed.gz](https://github.com/golang/go/files/1765094/TestAnalyzeAnnotationGC.trace.failed.gz)

**Comment by alexbrainman** [comment] 2018-02-28 09:51
> I captured a trace from a failed test run on gomote buildlet, where the user code reports 977us for debug.FreeOSMemory call, but the corresponding GCDone-GCStart timestamps report 1.383112ms (also the UI too)

@hyangah I did not look into this problem. But just a general comment - you cannot sleep for less than 1ms on Windows.

Alex

**Comment by hyangah** [comment] 2018-02-28 20:09
Thanks @alexbrainman 
I think this is related to #8976, #16755. @dvyukov 
Execution tracer uses runtime.cputicks and computes timestamps based on them. The time package measures time based on the monotonic clock value (runtime.nanotime), which returns different value.
I see occasional jumps in the cputicks values in the trace. 

I don't know why we saw this in only windows buildlets so far. Given #16755, I think this can happen in unix systems. 

I will skip this test in -short mode for now. 

Will take a look at the Solaris case separately.

**Comment by hyangah** [comment] 2018-02-28 20:15
Solaris: Indeed duplicate of #16755

https://build.golang.org/log/844551cc3c0f145093b6a58286e7a9f81edccec0

--- FAIL: TestAnalyzeAnnotations (0.00s)
	annotations_test.go:94: failed to trace the program: time stamps out of order
--- FAIL: TestAnalyzeAnnotationTaskTree (0.00s)
	annotations_test.go:159: failed to trace the program: time stamps out of order
--- FAIL: TestAnalyzeAnnotationGC (0.00s)
	annotations_test.go:249: failed to trace the program: time stamps out of order

**Closed** 2018-02-28 22:10 UTC
