### ISSUE TITLE
cmd/compile: Incorrect conversion to string

### ISSUE THREAD

**Issue by momchil-velikov** [golang/go#13793] opened 2015-12-31 16:02 UTC
In the following program:

```go
package main

import "fmt"

func main() {
	const A = 0xfffffffffffffffff // error
	// const A = 0x8000000000000000 // error
	// const A = 0x7fffffffffffffff // ok
	a := string(A)
	for i, r := range a {
		fmt.Printf("%d: %x\n", i, r)
	}
}
```

The compiler issues error message `overflow in int -> string`.

Form the Go Spec https://golang.org/ref/spec#Conversions

> A constant value x can be converted to type T in any of these cases:
> * x is an integer constant and T is a string type. The same rule as for non-constant x applies in this case.

...

> A non-constant value x can be converted to type T in any of these cases:
> * x is an integer or a slice of bytes or runes and T is a string type.

...

> Conversions to and from a string type
> 1. Converting a signed or unsigned integer value to a string type yields a string containing the UTF-8
> representation of the integer. Values outside the range of valid Unicode code points are converted to
>  "\uFFFD".

According to the above, the conversion should succeed, with the resulting string containing the UTF-8 encoding of `0xfffd`. 

`gccgo` does not issue an error and behaves as in the spec.

**Comment by cznic** [comment] 2015-12-31 16:13
I think the problem is that `A` in

```go
const A = 0xfffffffffffffffff
```

is not an integer constant (it's an untyped constant) nor can it be implicitly converted to any predeclared Go integer type. Then the specs part "x is an integer constant ..." does not apply.

**Comment by bradfitz** [comment] 2015-12-31 17:31
This may be a bug in gccgo, not in gc.
/cc @ianlancetaylor

**Comment by ianlancetaylor** [comment] 2015-12-31 19:15
An "integer constant" is not limited to a predeclared Go integer type.  There is no limit to the size of an integer constant.  I think gccgo is technically correct and gc is technically wrong.  gccgo actually has some code to specifically handle this case.

**Comment by griesemer** [comment] 2016-01-04 22:08
The spec doesn't say the argument must be an integer constant (or that is must be representable as an int as the error message appears to suggest) - it just requires an (arbitrary) integer value. It says that values outside the Unicode code point range are converted to 0xfffd which is what should happen here.

I believe cmd/compile is incorrect; it should accept this code w/o error. FWIW, gotype also accepts this code (and - like gccgo - has code to handle this case specifically).

It should be ok to fix cmd/compile as it will not restrict the set of accepted programs (and thus is not an error that we must keep for backward-compatibility).

**Comment by odeke-em** [comment] 2016-07-24 08:14
I believe this issue is a duplicate of https://github.com/golang/go/issues/11330 /cc @dvyukov who reported it first.

**Comment by griesemer** [comment] 2016-08-11 20:09
@odeke-em You are correct. Closing as duplicate of #11330.

**Closed by griesemer** 2016-08-11 20:09 UTC
