### ISSUE TITLE
dns: go's own DNS resolver fails to resolve TXT record for google.com over UDP

### ISSUE THREAD

**Issue by HouzuoGuo** [golang/go#47048] opened 2021-07-03 14:11 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/howard/.cache/go-build"
GOENV="/home/howard/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/howard/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/howard/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/howard/sdk/go1.16.5"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/howard/sdk/go1.16.5/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2804079168=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Run the following code snippet:

<pre>
package main

import (
        "context"
        "fmt"
        "net"
)

func main() {
        udpResolver := &net.Resolver{
                PreferGo: true,
                Dial: func(ctx context.Context, network, address string) (conn net.Conn, e error) {
                        return net.Dial("udp", "8.8.8.8:53")
                },
        }
        tcpResolver := &net.Resolver{
                PreferGo: true,
                Dial: func(ctx context.Context, network, address string) (conn net.Conn, e error) {
                        return net.Dial("tcp", "8.8.8.8:53")
                },
        }
        for _, resolver := range []*net.Resolver{udpResolver, tcpResolver} {
                txtRecords, err := resolver.LookupTXT(context.Background(), "google.com")
                fmt.Println(txtRecords, err)
        }
}
</pre>

And observe the following response:

<pre>
[] lookup google.com on 1.1.1.2:53: no answer from DNS server
[docusign=05958488-4752-4ef2-95eb-aa7ba8a3bd0e v=spf1 include:_spf.google.com ~all google-site-verification=TV9-DBe4R80X4v0M4U_bd_J9cpOJM0nikft0jAgjmsQ facebook-domain-verification=22rm551cu4k0ab0bxsw536tlds4h95 docusign=1b0a6754-49b1-4db5-8540-d2c12664b289 MS=E4A68B9AB2BB9670BCE15412F62916164C0B20BB apple-domain-verification=30afIBcvSuDV2PLX globalsign-smime-dv=CDYX+XFHUw2wml6/Gb8+59BsH31KzUr6c1l2BPvqKX8= google-site-verification=wD8N7i1JTNTkezJ49swvWW48f8_9xveREV4oB-0Hf5o] <nil>

</pre>

### What did you expect to see?

A couple of things:

- Why did go's built-in DNS resolver fail to resolve the TXT records over UDP? `dig` for example does not have trouble with it:
- Why did the built-in DNS resolver appear to fall-back to use nameservers listed in `/etc/resolv.conf` (1.1.1.1:53)? This behaviour is not documented in [net package, Name Resolution](https://golang.org/pkg/net/).

An attempt using dig to resolve the TXT records succeeds:

```
dig @8.8.8.8 google.com txt +notcp

; <<>> DiG 9.16.1-Ubuntu <<>> @8.8.8.8 google.com txt +notcp
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24469
;; flags: qr rd ra; QUERY: 1, ANSWER: 9, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.                    IN      TXT

;; ANSWER SECTION:
google.com.             3430    IN      TXT     "MS=E4A68B9AB2BB9670BCE15412F62916164C0B20BB"
google.com.             3430    IN      TXT     "docusign=1b0a6754-49b1-4db5-8540-d2c12664b289"
google.com.             3430    IN      TXT     "docusign=05958488-4752-4ef2-95eb-aa7ba8a3bd0e"
...
...
```

**Comment by HouzuoGuo** [comment] 2021-07-03 14:14
BTW, the content of `/etc/resolv.conf` is crafted manually, the entire file reads:

```
# Quad9, OpenDNS, CloudFlare primary
nameserver 9.9.9.9
nameserver 208.67.222.222
nameserver 1.1.1.2
```

**Comment by seankhliao** [comment] 2021-07-03 15:17
`dig` reverts to TCP for truncated messages, set `+ignore` to get the actual response for UDP:

```
$ dig TXT google.com @8.8.8.8 +notcp +ignore +noedns

; <<>> DiG 9.16.18 <<>> TXT google.com @8.8.8.8 +notcp +ignore +noedns
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45684
;; flags: qr tc rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;google.com.			IN	TXT

;; Query time: 10 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Jul 03 17:07:24 CEST 2021
;; MSG SIZE  rcvd: 28
```

or use `drill`:

```
$ drill TXT google.com @8.8.8.8
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 65227
;; flags: qr tc rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; google.com.	IN	TXT

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 7 msec
;; SERVER: 8.8.8.8
;; WHEN: Sat Jul  3 17:15:21 2021
;; MSG SIZE  rcvd: 28

;; WARNING: The answer packet was truncated; you might want to
;; query again with TCP (-t argument), or EDNS0 (-b for buffer size)
```

It doesn't revert to `/etc/resolv.conf`, it just uses the address it passed to the Dial function (which you ignored/overrode) #43703

Closing as this is working as intended / duplicate

**Closed by seankhliao** 2021-07-03 15:17 UTC
