### ISSUE TITLE
Proposal: time.MustParse

### ISSUE THREAD

**Issue by SamWhited** [golang/go#15950] opened 2016-06-03 15:48 UTC
I find myself writing something along the lines of:

```
const (
    somelayout = "…"
    sometime = ""…"
    someothertime = "…"
)

t, err := time.Parse(somelayout, sometime)
if err != nil {
    panic(…)
}
```

fairly frequently; mostly as a `MustParse` function in tests, but also occasionally for constants in my actual program.

Having such a function in the standard library right along side the normal `Parse` function (similar to `regex.Compile` and `regex.MustCompile`) would be very handy, especially when writing tests.

Something simple like the following, would do: https://go-review.googlesource.com/#/c/23734/

**Comment by cespare** [comment] 2016-06-03 17:49
Previous discussion in #13328, where it was shot down.

(I still want it, though.)

**Comment by dgryski** [comment] 2016-06-04 05:16
https://github.com/dominikh/go-staticcheck does this.

**Comment by robpike** [comment] 2016-06-04 20:12
Duplicate of #13328, which was closed as not being valuable enough.

**Closed by robpike** 2016-06-04 20:12 UTC

**Comment by ConradIrwin** [comment] 2016-08-10 23:09
just was sad because this was missing
