### ISSUE TITLE
encoding/json: SyntaxError.Offset is wrong when decoding stream

### ISSUE THREAD

**Issue by santhosh-tekuri** [golang/go#44811] opened 2021-03-05 15:04 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes. reproducable on playground with 1.16 version

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/santhosh/Library/Caches/go-build"
GOENV="/Users/santhosh/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/santhosh/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/santhosh/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/santhosh/json/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z6/vfg99x7d2szf54dd2yms9j5r0000gn/T/go-build029684704=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://play.golang.org/p/cPDdjRRl1Rg

### What did you expect to see?
offset: 34

### What did you see instead?
offset: 24

**Comment by networkimprov** [comment] 2021-03-05 18:37
cc @mvdan @dsnet

**Comment by dsnet** [comment] 2021-03-05 19:07
Yep. That looks like a bug.

**Comment by AlexanderYastrebov** [comment] 2021-10-13 20:57
I've found an apparent duplicate https://github.com/golang/go/issues/34543 for which https://go-review.googlesource.com/c/go/+/284078/ attempts to add `dec.scan.bytes++` in every possible place while my take abandons scanner offset tracking altogether.

**Comment by seankhliao** [comment] 2022-08-20 16:42
Duplicate of #34543

**Closed by seankhliao** 2022-08-20 16:42 UTC
Labels: NeedsInvestigation
