### ISSUE TITLE
hello_server.go:30:2: "./helloworld" is relative, but relative import paths are not supported in module mode

### ISSUE THREAD

**Issue by Bhala1987** [golang/go#54335] opened 2022-08-08 13:37 UTC
1. unzip the docs folder & goto \docs\docs directory
[docs.zip](https://github.com/golang/go/files/9282098/docs.zip)

2. ./scripts/runserver.sh
3. Expected: hello server should be up & running, but the actual is error: hello_server.go:30:2: "./helloworld" is relative, but relative import paths are not supported in module mode

$ go version
go version go1.19 windows/amd64

$ protoc --version
libprotoc 3.21.4

$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\b.rajalakshmi\AppData\Local\go-build
set GOENV=C:\Users\b.rajalakshmi\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Program Files\Go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Program Files\Go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\b.rajalakshmi\Documents\Bhala\grpc\docs\docs\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\B73ED~1.RAJ\AppData\Local\Temp\go-build1437050701=/tmp/go-build -gno-record-gcc-switches

**Comment by seankhliao** [comment] 2022-08-08 14:06
The error message says it all.

Closing as working as intended.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Closed by seankhliao** 2022-08-08 14:06 UTC

**Comment by Bhala1987** [comment] 2022-08-08 14:34
@seankhliao , what's the solution?
