### ISSUE TITLE
device is not configured when running in chroot'd folder

### ISSUE THREAD

**Issue by rbucker** [golang/go#37637] opened 2020-03-03 21:20 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.1
</pre>

### Does this issue reproduce with the latest release?

unknown

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rbucker/.cache/go-build"
GOENV="/home/rbucker/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="openbsd"
GONOPROXY=""
GONOSUMDB=""
GOOS="openbsd"
GOPATH="/home/rbucker/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/openbsd_amd64"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build844217065=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I have compiled my project and it runs from the command line ok, however, in the larger scope of the project this executable is executed via os.Command("runme").Output()... and that's running inside an 
 OpenBSD chroot.

### What did you expect to see?

I expected it to tun to completion without errors as it did in the command line

### What did you see instead?

When I triggered my inside app... I received my first error which was ```open /dev/null file or directory not found```.  So I performed a ```MAKEDEV std``` on that machine in the inner most to be chroot'd folder.... then ran my program and received ```open /dev/null device not configured```

I'm currently trying to figure out what is wrong with my `/dev/null` but in the meantime... which devices are required or recommended?

**Comment by dmitshur** [comment] 2020-03-03 22:18
> I have compiled my project and it runs from the command line ok, however, in the larger scope of the project this executable is executed via os.Command("runme").Output()... and that's running inside an
OpenBSD chroot.

Is your project closed source? Do you have a reproducible snippet (a smaller one makes investigation easier, but it doesn't have to be) that can be used to reproduce this issue?

**Comment by rbucker** [comment] 2020-03-05 16:31
Here is a sample....

**_hello.go_**

```
import "fmt"

func main() {
        fmt.Println("Hello, 世界")
}
```

**_check.go_**

```
package main

import (
        "fmt"
        "os/exec"
)

func main() {
        out, err := exec.Command("./hello").Output()
        if err == nil {
                fmt.Printf("OUT: %s\n", out)
        } else {
                fmt.Printf("ERR: %s\n", err)
        }
}
```

To build:

```
go build check.go
go build hello.go
```

test to make certain it runs...

```
./check
```

produces 
```
OUT: Hello, 世界
```

Then.... try to run in chroot

```
sudo chroot -g myid -u myid . ./check
```

and this produces....

```
ERR: open /dev/null: no such file or directory
```

so the problem is that the Output() is trying to open the NULL device and that device does not exist in OpenBSD6.6 chroot.

**Comment by rbucker** [comment] 2020-03-05 16:38
One more note. I created a `dev/null` in my project folder

```
mkdir dev
cd dev
ls -l /dev/null
sudo mknod -m 666 null c 2 2
```

then tried to run it again

```
sudo chroot -g zurvita -u zurvita . ./check
```

this time I got

```
ERR: open /dev/null: device not configured
```

**Comment by rbucker** [comment] 2020-03-05 16:50
LASTLY... it is possible that `nodev` in the `/etc/fstab` is causing this last error.... still researching as it is not convenient to reboot right now.

**Comment by randall77** [comment] 2020-03-05 16:59
You should set stdin, stdout, and stderr of your command.
The spec of `exec.Cmd`'s `Stdin` field says:
```
	// Stdin specifies the process's standard input.
	//
	// If Stdin is nil, the process reads from the null device (os.DevNull).
	Stdin io.Reader
```
Same for `Stdout` and `Stderr`.
You could use, e.g., a `bytes.Buffer` for all of them.

**Comment by ianlancetaylor** [comment] 2020-03-05 17:57
Any OpenBSD system should have a file `/dev/null`.  I don't understand why your system does not have that.  I suggest asking the OpenBSD community.

**Comment by esote** [comment] 2021-12-01 20:56
This appears to be working as intended. Within a chroot either

1. mknod `/dev/null` -- the ENXIO ("device not configured") error is indeed [from the `nodev` mount option](https://github.com/openbsd/src/blob/71b09c7362424ca32145208b6f624a81e24f4ff8/sys/kern/spec_vnops.c#L121) and removing that should fix things
2. or, as @randall77 mentions, use empty buffers to avoid opening `/dev/null`
```
package main

import (
        "io"
        "os/exec"
        "syscall"
        "testing/iotest"
)

func main() {
        syscall.Chroot("/my/dir")
        cmd := exec.Command("/my/cmd")
        cmd.Stdin = iotest.ErrReader(io.EOF)
        cmd.Stdout = io.Discard
        cmd.Stderr = io.Discard
        cmd.Run()
}
```

---

> Any OpenBSD system should have a file `/dev/null`. I don't understand why your system does not have that. I suggest asking the OpenBSD community.

@ianlancetaylor this is specifically within chroot where OpenBSD won't automatically create `/dev/null`

**Comment by ianlancetaylor** [comment] 2021-12-03 01:22
Thanks.  It sounds like this is not a problem in the Go standard library, so closing.

**Closed by ianlancetaylor** 2021-12-03 01:22 UTC
Labels: OS-OpenBSD, WaitingForInfo
