### ISSUE TITLE
database/sql: not allowing values in range [2^64 -1 - 2^63] in sql library for uint64

### ISSUE THREAD

**Issue by sarathsp06** [golang/go#20238] opened 2017-05-04 07:26 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/sarath/go"
GORACE=""
GOROOT="/home/sarath/goroot"
GOTOOLDIR="/home/sarath/goroot/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build602887406=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
Used `database/sql` lib to insert a  a value ( 2^64 - 1 )  as uint64 to a mysql column of type decimal(20,0)

### What did you expect to see?
Successful insertion

### What did you see instead?
Insertion fails with the following error

"uint64 values with high bit set are not supported" 

## Code that generates the error

In drivers/types.go found the code 

```go
if u64 >= 1<<63 {
			return nil, fmt.Errorf("uint64 values with high bit set are not supported")
}
```
Here is the link for the code snippet

[github/golang](https://github.com/golang/go/blob/d7c0de98a96893e5608358f7578c85be7ba12b25/src/database/sql/driver/types.go#L265)

**Comment by sarathsp06** [comment] 2017-05-04 07:28
@bradfitz  could you please help explaining this if it is expected?

**Comment by cznic** [comment] 2017-05-04 13:27
Some DBs do not support unsigned integers. Rejecting uint64 >= 1<<63 prevents them become indistinguishable from int64s < 0. If you need to insert such int64 anyway, you have to explicitly convert in on input to int64 and convert it back to uint64 on output - and take care to never insert a signed integer into the same column.

**Comment by bradfitz** [comment] 2017-05-04 13:32
This dates back to the beginning of the database/sql package where we decided to only support int64 (not uint64) for simplicity:

https://golang.org/pkg/database/sql/driver/#Value

We decided we could re-evaluate it in the future. The future is here.

@kardianos?

**Comment by kardianos** [comment] 2017-05-04 13:39
Cl for go1.9 should enable drivers that want to support it to do so

https://go-review.googlesource.com/c/38533/

**Comment by kardianos** [comment] 2017-05-04 17:51
This is really a duplicate of a number of issues that want to expand the supported types.
Duplicate of #18417 .

It is my plan to allow drivers to support these types starting with go1.9.

**Closed by kardianos** 2017-05-04 17:51 UTC
Labels: FeatureRequest, NeedsDecision
