### ISSUE TITLE
x/tools/gopls: implementation sometimes returns duplicate implementers

### ISSUE THREAD

**Issue by muirdm** [golang/go#35607] opened 2019-11-15 01:28 UTC
For example, when I find implementations of the "matcher" interface in tools/internal/lsp/source/completion.go, I get back:

```
/Users/muir/projects/tools/internal/lsp/fuzzy/matcher.go
38: type Matcher struct {
/Users/muir/projects/tools/internal/lsp/source/completion.go
118: type insensitivePrefixMatcher string
118: type insensitivePrefixMatcher string
103: type matcher interface {
108: type prefixMatcher string
108: type prefixMatcher string
```

Note the "insensitivePrefixMatcher" and "prefixMatcher" duplicates.

**Comment by irajdeep** [comment] 2019-11-25 10:05
@muirdm I would be willing to work on this as my first issue, if one else is working on it.

**Comment by stamblerre** [comment] 2019-11-25 17:54
@irajdeep: Thanks, that'd be great! Please feel free to reach out to me here or on [Gophers Slack](https://invite.slack.golangbridge.org/) if you need any guidance.

**Comment by irajdeep** [comment] 2019-11-25 20:38
Hey folks! I tried to reproduce this issue first, In `vscode` I selected `find all references` for `matcher interface`. In results, I don't seem to get any of the "type(s)" which implement the interface.

<img width="931" alt="Screen Shot 2019-11-25 at 9 35 54 PM" src="https://user-images.githubusercontent.com/7368670/69576110-f3209d00-0fcb-11ea-9e5f-29dd3044f4b6.png">

**Comment by muirdm** [comment] 2019-11-25 22:11
Thanks for looking at this. It still happens for me on master. Below is the request/response log showing the duplicate results. Maybe VSCode is de-duping the results? Otherwise, not sure what is going on.

```
[Trace - 02:07:52 PM] Sending request 'textDocument/implementation - (1224)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/muir/projects/tools/internal/lsp/source/completion.go"
  },
  "position": {
    "line": 102,
    "character": 7
  }
}


[Trace - 02:07:52 PM] Received response 'textDocument/implementation - (1224)' in 14ms.
Result: [
  {
    "range": {
      "end": {
        "character": 12,
        "line": 37
      },
      "start": {
        "character": 5,
        "line": 37
      }
    },
    "uri": "file:///Users/muir/projects/tools/internal/lsp/fuzzy/matcher.go"
  },
  {
    "range": {
      "end": {
        "character": 29,
        "line": 117
      },
      "start": {
        "character": 5,
        "line": 117
      }
    },
    "uri": "file:///Users/muir/projects/tools/internal/lsp/source/completion.go"
  },
  {
    "range": {
      "end": {
        "character": 29,
        "line": 117
      },
      "start": {
        "character": 5,
        "line": 117
      }
    },
    "uri": "file:///Users/muir/projects/tools/internal/lsp/source/completion.go"
  },
  {
    "range": {
      "end": {
        "character": 18,
        "line": 107
      },
      "start": {
        "character": 5,
        "line": 107
      }
    },
    "uri": "file:///Users/muir/projects/tools/internal/lsp/source/completion.go"
  },
  {
    "range": {
      "end": {
        "character": 18,
        "line": 107
      },
      "start": {
        "character": 5,
        "line": 107
      }
    },
    "uri": "file:///Users/muir/projects/tools/internal/lsp/source/completion.go"
  }
]
```

**Comment by stamblerre** [comment] 2019-11-26 07:00
Thanks for investigating, @irajdeep. It's definitely possible that VS Code is de-duping. I actually expect that @ridersofrohan's work on fixing https://github.com/golang/go/issues/35600 will also resolve this issue.

**Comment by irajdeep** [comment] 2019-11-26 17:43
So, I checked the logs of `gopls` and I still can't reproduce it in v0.2.0

```
[Trace - 18:35:27.459 PM] Sending request 'textDocument/implementation - (14)'.
Params: {"textDocument":{"uri":"file:///Users/rdas/go/src/golang.org/x/tools/internal/lsp/source/completion.go"},"position":{"line":102,"character":9}}


[Trace - 18:35:27.461 PM] Received response 'textDocument/implementation - (14)' in 1ms.
Result: [{"uri":"file:///Users/rdas/go/src/golang.org/x/tools/internal/lsp/source/completion.go","range":{"start":{"line":117,"character":5},"end":{"line":117,"character":29}}},{"uri":"file:///Users/rdas/go/src/golang.org/x/tools/internal/lsp/source/completion.go","range":{"start":{"line":107,"character":5},"end":{"line":107,"character":18}}}]

```
I get 2 responses as expected. I suspect some change since v0.2.0 in master might have introduced it?

> I actually expect that @ridersofrohan's work on fixing #35600 will also resolve this issue.

Cool, I will hold off working on this issue until then.

**Comment by ridersofrohan** [comment] 2019-12-12 14:47
Duplicate of [#35600](https://github.com/golang/go/issues/35600). This seems to be resolved with the fix in that issue.

**Closed by ridersofrohan** 2019-12-12 14:47 UTC
Labels: Tools, gopls
