### ISSUE TITLE
'go test -race ...' misses race condition on go1.9.2 linux/amd64

### ISSUE THREAD

**Issue by markcampanelli-wf** [golang/go#23276] opened 2017-12-28 22:47 UTC
### What version of Go are you using (`go version`)?
go1.9.2 darwin/amd64 and go1.9.2 linux/amd64

### Does this issue reproduce with the latest release?
Yes, but only on go1.9.2 linux/amd64, not on go1.9.2 darwin/amd64.

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64 and linux/amd64

### What did you do?

Ran `go test -race ...` with a test that has repeatable race conditions.

### What did you expect to see?
On go1.9.2 darwin/amd64, (i.e., local dev) the race condition appears between the RUN and FAIL lines, and the failure registers in [go2xunit](https://github.com/tebeka/go2xunit) conversion to xUnit. I would expect the same on our CI test runner machine, which is go1.9.2 linux/amd64.

### What did you see instead?
On go1.9.2 linux/amd64, the data race warnings appear after the RUN and PASS lines for the offending test, but before the next test's RUN line. Exit code is zero, indicated no race(s). Subsequently, [go2xunit](https://github.com/tebeka/go2xunit) doesn't pick up any failure OR the WARNING: DATA RACE (even with -fail-on-race flag set).
```bash
=== RUN   TestMyRaceyTest
--- PASS: TestMyRaceyTest (1.01s)
==================
WARNING: DATA RACE
...
==================
WARNING: DATA RACE
...
==================
WARNING: DATA RACE
...
=== RUN TestOtherTest
...
```

**Comment by odeke-em** [comment] 2017-12-28 22:54
@markcampanelli-wf just as per Ocam's razor, did you turn on the `-race` flag for the Travis CI?
<img width="445" alt="screen shot 2017-12-28 at 3 51 35 pm" src="https://user-images.githubusercontent.com/4898263/34425206-150a85c6-ebe7-11e7-8542-87e14eb0bad4.png">

I ask because as in the screenshot above doesn't seem y'all turned on the `-race` flag in https://github.com/tebeka/go2xunit/blob/7c4e1816919ef50bb9cd04b1166421e7abb7c5cd/.travis.yml#L1-L6

Could you help us clarify and perhaps link to a Travis build with the `-race` flag turned on? Thank you.

**Comment by markcampanelli-wf** [comment] 2017-12-28 22:57
Yes sorry:
```
	go test -short -race -v -ldflags -s `go list ./...` | tee "$${ROOT:-/testing}/test_reports/go_test_results.out"
	go2xunit -input "$${ROOT:-/testing}/test_reports/go_test_results.out" -output "$${ROOT:-/testing}/test_reports/go_test_results.xml"
```

**Comment by davecheney** [comment] 2017-12-28 23:11
Data race reports are written to stderr, file descriptor 2, not stdout.
What is likely happening is your report is showing up in the output that
travis captures but not sent to your file

try this

go test -short -race -v ./... 2>&1 | tee
"$${ROOT:-/testing}/test_reports/go_test_results.out"

**Comment by markcampanelli-wf** [comment] 2018-01-02 15:12
While including stderr is indeed wise, this didn't make a difference here.

**Comment by bcmills** [comment] 2018-01-02 17:50
Are you sure the race actually occurs while the test function is running?
A lot of races occur in leaked or “background” goroutines.

An example demonstrating the actual race in question would be helpful either way.

**Comment by markcampanelli-wf** [comment] 2018-01-18 21:14
That is possible, but it was a newly added test when issue started appearing. In any event, we just grep 'WARNING: DATA RACE' now on the captured output and fail on match.

**Comment by ianlancetaylor** [comment] 2018-03-28 21:15
I don't know what is going on here, and it does seem possible hat it could be related to the CI system in some way.  In order to make progress we will need instructions on how to reproduce the problem ourselves.  Thanks.

**Comment by andybons** [comment] 2019-05-14 18:14
Been waiting for info for a while. Closing.

**Closed by andybons** 2019-05-14 18:14 UTC
Labels: NeedsInvestigation, WaitingForInfo
