### ISSUE TITLE
affected/package: net/http

### ISSUE THREAD

**Issue by sywc670** [golang/go#61047] opened 2023-06-28 11:20 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.20.5
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\will\AppData\Local\go-build        
set GOENV=C:\Users\will\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\will\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=github.com/marmotedu/*
set GOOS=windows
set GOPATH=C:\Users\will\go
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64

set GOVCS=
set GOVERSION=go1.20.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\开发\go\goplayground\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\will\AppData\Local\Temp\go-build2922334793=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

run code as proxy
https://go.dev/play/p/XV_LDHcYKeB

make a http request with method CONNECT to any url using env variable http_proxy
http_proxy=192.168.101.11:8080 curl -XCONNECT www.baidu.com  

### What did you expect to see?

r.URL.Host is "www.baidu.com:80"? 

When succeed the proxy should forward the request. Then return 403.

### What did you see instead?

output:
2023/06/28 18:03:01 HTTP隧道服务器已启动，监听端口：8080
2023/06/28 18:03:17 无法连接到目标主机：dial tcp: lookup http: no such host

cause:
r.URL.Host is "http:"
r.URL.Path is "//www.baidu.com/"
So the parse process of CONNECT request may be wrong?

**Comment by seankhliao** [comment] 2023-06-28 11:46
That's curl sending an invalid request.
CONNECT takes the form`CONNECT www.example.com:443 HTTP/1.1` without a scheme

closing as not a bug

**Closed by seankhliao** 2023-06-28 11:46 UTC
