### ISSUE TITLE
Allow go get -u to upgrade replacements

### ISSUE THREAD

**Issue by andig** [golang/go#33456] opened 2019-08-04 14:35 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
❯ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/andig/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/andig/htdocs/go"
GOPROXY="https://proxy.golang.org"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/andig/htdocs/mbmd/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w5/_c0nb6n90fn96tzw04dtc6240000gn/T/go-build121491140=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I'm using a module replacement:

    replace github.com/crabmusket/gosunspec => github.com/andig/gosunspec v0.0.0-20190802074646-9596f4c956e3

Doing 

    go get -u github.com/andig/gosunspec@rollup

does not update the replacement I have in go.mod to the latest commit available. Instead, it adds it as new requirements.

  
### What did you expect to see?

It would be nice if the replacements allowed upgrading too. Currently it doesn't, instead it adds the module to the required modules and I manually need copy the commit across to the replacement line plus remove the added module.

Granted this is probably not too common but would be nice.

**Comment by shivi28** [comment] 2019-08-05 11:33
@andig Do you have `require github.com/crabmusket/gosunspec` in your go.mod file. Please check this [#29299](https://github.com/golang/go/issues/29299) PR for reference. It might be useful for you.

**Comment by andig** [comment] 2019-08-05 12:09
> Do you have require github.com/crabmusket/gosunspec in your go.mod file

Yes, I do (https://github.com/volkszaehler/mbmd/blob/master/go.mod#L4).

I've read both #29299 and #26241 now, it seems they are about not having to write the actual `require` when using `replace`. 
Neither seems to mention the missing upgrade behaviour of `go get -u` with `replace`?

**Comment by bcmills** [comment] 2019-08-05 18:48
Duplicate of #32721

**Closed by bcmills** 2019-08-05 18:48 UTC
