### ISSUE TITLE
proposal: sync/map: use genericity in sync.Map 

### ISSUE THREAD

**Issue by culionbear** [golang/go#52262] opened 2022-04-10 10:01 UTC
go version: go 1.18

hello

Since the advent of generics， Golang is becoming more and more scalable.
I recommend incorporating generics into the sync.Map(sync/map or golang.org/x/sync/map)

**Comment by seankhliao** [comment] 2022-04-10 13:45
Duplicate of #47657

**Closed by seankhliao** 2022-04-10 13:45 UTC
Labels: Proposal
