### ISSUE TITLE
Printing addresses of empty structs affects their values

### ISSUE THREAD

**Issue by willfaught** [golang/go#25699] opened 2018-06-02 01:58 UTC
### What did you do?

https://play.golang.org/p/bpgpOsJz95M

```go
var a, b struct{}
fmt.Println(&a == &b)
//fmt.Println(&a, &b)
fmt.Println(&a == &b)
```

### What did you expect to see?

```
true
true
```

### What did you see instead?

```
false
false
```

If you uncomment the Println line:

```go
var a, b struct{}
fmt.Println(&a == &b)
fmt.Println(&a, &b)
fmt.Println(&a == &b)
```

then you get

```
true
&{} &{}
true
```

as "expected".

**Comment by tenntenn** [comment] 2018-06-02 02:51
https://play.golang.org/p/dozDzpELUvG

**Comment by josharian** [comment] 2018-06-02 02:54
From the spec: “Pointers to distinct zero-size variables may or may not be equal.”

**Comment by willfaught** [comment] 2018-06-02 03:14
It’s unexpected (to me) that it changes based on context.

**Comment by gbbr** [comment] 2018-06-02 03:16
As @josharian already quoted, this is correct. &a and &b represent memory addresses, so they may (or may not) point to the same memory space. 

I’m pretty sure this is working as intended and that accessing these pointers changes their behaviour. Interesting find though!

**Comment by ianlancetaylor** [comment] 2018-06-02 03:51
This is working as documented, so closing.

**Closed by ianlancetaylor** 2018-06-02 03:51 UTC
