### ISSUE TITLE
net/textproto: fails to parse headers without a body

### ISSUE THREAD

**Issue by kayrus** [golang/go#53854] opened 2022-07-13 20:48 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

See example: https://go.dev/play/p/q5lkQ1V0vBa

### What did you expect to see?

I expect that `mail.ReadMessage` will return parsed headers with an empty body.

### What did you see instead?

No body, no headers, just error:

```
2009/11/10 23:00:00 EOF

Program exited.
```

I'm not sure if this behavior aligns with RFC, but I receive emails with zero body from postfix, which should align with RFC.

**Comment by seankhliao** [comment] 2022-07-13 21:06
Duplicate of #33823

**Closed by seankhliao** 2022-07-13 21:06 UTC
