### ISSUE TITLE
affected/package: cgo

### ISSUE THREAD

**Issue by PandyYang** [golang/go#56951] opened 2022-11-28 02:03 UTC
### What version of Go are you using (`go version`)?
```
go1.19.2 linux/amd64
```

### Does this issue reproduce with the latest release?
yes，reproduce in go version go1.19.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
<details>
<summary>
$ go env
</summary>

```
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/goProject/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/goProject"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/goProject/src/NTI-SDK/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1213895951=/tmp/go-build -gno-record-gcc-switches"
```

</details>

### What did you do?  
I just use go unsafe.Pointer to pass context, in order to reuse some config in every api called.  
i pass the context to a function loop(1 million times call).  
here is my example code : [https://go.dev/play/p/DMPrepENpVR](https://go.dev/play/p/DMPrepENpVR)

### What did you expect to see?
The program is normally executed 1000000 times  

### What did you see instead?
 it is break when about 300 to 400 times are executed.  
the error is:  
```

panic: runtime/cgo: misuse of an invalid Handle

goroutine 17 [running, locked to thread]:
runtime/cgo.Handle.Value(...)
	/usr/local/go/src/runtime/cgo/handle.go:124
main.parseHandler(0xc00021b040?)
	/root/goProject/src/NTI-SDK/test/cmd/v3/cmd/main.go:69 +0x138
main.query(0x0?, 0xc000008601?)
	/root/goProject/src/NTI-SDK/test/cmd/v3/cmd/main.go:58 +0x1e
SIGABRT: abort
PC=0x7f05adbe0c01 m=0 sigcode=18446744073709551610
signal arrived during cgo execution
```
There should be no concurrency problem here. According to the receipt of the print, the pointer points to the same address, and the program suddenly shows that the pointer is misuse.  

print msg:
```
...

0xc0001b0e98
310
0xc0001b0e98
311
0xc0001b0e98
312
0xc0001b0e98
313
0xc0001b0e98
314
0xc0001b0e98
315
0xc0001b0e98
316
0xc0001b0e98
317

panic: runtime/cgo: misuse of an invalid Handle

goroutine 17 [running, locked to thread]:
runtime/cgo.Handle.Value(...)
	/usr/local/go/src/runtime/cgo/handle.go:124
main.parseHandler(0xc00021b040?)
	/root/goProject/src/NTI-SDK/test/cmd/v3/cmd/main.go:69 +0x138
main.query(0x0?, 0xc000008601?)
	/root/goProject/src/NTI-SDK/test/cmd/v3/cmd/main.go:58 +0x1e
SIGABRT: abort
PC=0x7f05adbe0c01 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

...
```

**Comment by randall77** [comment] 2022-11-28 02:15
Can you run your program under the race detector?
https://go.dev/doc/articles/race_detector

**Comment by PandyYang** [comment] 2022-11-28 02:24
> Can you run your program under the race detector? https://go.dev/doc/articles/race_detector

I run the command:  
```
GODEBUG=cgocheck=0 go run -race sdk.go
```
but there is no data race found.
```
364
0xc000130ea8
365
panic: runtime/cgo: misuse of an invalid Handle

goroutine 17 [running, locked to thread]:
runtime/cgo.Handle.Value(...)
        /usr/local/go/src/runtime/cgo/handle.go:124
main.parseHandler(0xc0002c23c0?)
        /root/goProject/src/NTI-SDK/test/cmd/v3/cmd/main.go:69 +0x138
main.query(0x0?, 0xc000008601?)
        /root/goProject/src/NTI-SDK/test/cmd/v3/cmd/main.go:58 +0x1e
SIGABRT: abort
PC=0x7fb1cb26ac01 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x46d510, 0xc100065f08)
        /usr/local/go/src/runtime/cgocall.go:158 +0x6e fp=0xc100065ee0 sp=0xc100065ea8 pc=0x41324e
main._Cfunc_query(0xc000130ea8, 0x310b230)
        _cgo_gotypes.go:101 +0x85 fp=0xc100065f08 sp=0xc100065ee0 pc=0x46d105
main.main.func1(0xc000130ea8?)
        /root/goProject/src/NTI-SDK/test/cmd/v3/cli/sdk.go:14 +0x6a fp=0xc100065f50 sp=0xc100065f08 pc=0x46d44a
main.main()
        /root/goProject/src/NTI-SDK/test/cmd/v3/cli/sdk.go:14 +0x67 fp=0xc100065f80 sp=0xc100065f50 pc=0x46d2e7
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc100065fe0 sp=0xc100065f80 pc=0x441b32
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc100065fe8 sp=0xc100065fe0 pc=0x468041

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc100052fb0 sp=0xc100052f90 pc=0x441ef6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:302 +0xad fp=0xc100052fe0 sp=0xc100052fb0 pc=0x441d8d
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc100052fe8 sp=0xc100052fe0 pc=0x468041
created by runtime.init.6
        /usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc100053790 sp=0xc100053770 pc=0x441ef6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc1000537c8 sp=0xc100053790 pc=0x42f8ae
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc1000537e0 sp=0xc1000537c8 pc=0x424786
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc1000537e8 sp=0xc1000537e0 pc=0x468041
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc10002e070?, 0x4cb488?, 0x1?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc100053f70 sp=0xc100053f50 pc=0x441ef6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x72c880)
        /usr/local/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc100053fa0 sp=0xc100053f70 pc=0x42d973
runtime.bgscavenge(0x0?)
        /usr/local/go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc100053fc8 sp=0xc100053fa0 pc=0x42df25
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc100053fe0 sp=0xc100053fc8 pc=0x424726
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc100053fe8 sp=0xc100053fe0 pc=0x468041
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xaa

rax    0x0
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x3589
rsi    0x3589
rbp    0xc00013bc98
rsp    0xc00013bc80
r8     0x7
r9     0x0
r10    0x8
r11    0x246
r12    0x3589
r13    0x0
r14    0xc000008680
r15    0x0
rip    0x7fb1cb26ac01
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
exit status 2
```

**Comment by cherrymui** [comment] 2022-11-28 15:13
It looks like `initSDK`, `query`, `parseHandler` etc. are actually Go functions. Why do you export them to C and call them using cgo calls, instead of calling them directly in Go?

> GODEBUG=cgocheck=0

Does your code work without the check disabled? If not, the code may violate some cgo pointer rules documented at https://pkg.go.dev/cmd/cgo , and "programs that break these rules are likely to fail in unexpected and unpredictable ways."

**Comment by PandyYang** [comment] 2022-11-28 15:46
> It looks like `initSDK`, `query`, `parseHandler` etc. are actually Go functions. Why do you export them to C and call them using cgo calls, instead of calling them directly in Go?
> 
> > GODEBUG=cgocheck=0
> 
> Does your code work without the check disabled? If not, the code may violate some cgo pointer rules documented at https://pkg.go.dev/cmd/cgo , and "programs that break these rules are likely to fail in unexpected and unpredictable ways."
### first question
I made a shared lib in order to allow it to be called by multiple languages. Currently, it is just a test to call it with go. 
### second  
my code can't work without set godebug=cgocheck=0, if not set, the error is  
```
panic: runtime error: cgo result has Go pointer
```  
I am trying to use runtime/cgo.Handle type, hope it is work.

**Comment by cherrymui** [comment] 2022-11-28 16:53
Your current code violates the cgo pointer passing rule, specifically

> A Go function called by C code may not return a Go pointer

`initSDK` returns the address of the handle, which is a Go pointer. So it is expected not to work.

To use Handle, I think you want to either create the Handle in Go code _not_ wrapped in cgo calls, or pass the handle as an integer (`C.uintptr_t`), as the first example on https://pkg.go.dev/runtime/cgo#Handle shows.

Closing as working as intended. Thanks.

**Closed by cherrymui** 2022-11-28 16:53 UTC
