### ISSUE TITLE
cmd/go: wrong createCmd for submodules

### ISSUE THREAD

**Issue by toxeus** [golang/go#12612] opened 2015-09-14 13:49 UTC
The [`createCmd`](https://github.com/golang/go/blob/b9dbb030d5e7d2733e877972568368dc806b7304/src/cmd/go/vcs.go#L125) for the submodules fails. I have clarified [upstream](http://thread.gmane.org/gmane.comp.version-control.git/277630/focus=277825) if this is expected to fail. The result is that it is expected to fail as it is currently in the code. The correct `createCmd` therefore would be:
```go
createCmd: []string{"clone {repo} {dir}", "-C={dir} submodule update --init --recursive"}
```

**Comment by ianlancetaylor** [comment] 2015-09-14 15:48
Can you give us a test case that fails with the current code and works with your suggested patch?

**Comment by toxeus** [comment] 2015-09-14 17:39
On git level the testcase is provided in the git mailing list thread I have linked in my first post. Sorry, I should have stated that clearer.

On go level you can reproduce the failure as follows:
```bash
export GO15VENDOREXPERIMENT=1
go get -d github.com/toxeus/test_for_issue
```
or any other git repo that has submodules.

The error message looks then like this:
```bash
# cd .; git --git-dir=/home/filip/go/src/github.com/toxeus/test_for_issue/.git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'vendor/golang.org/x/crypto'
package github.com/toxeus/test_for_issue: exit status 1
```

**Comment by StephanDollberg** [comment] 2015-09-14 21:32
I think this is a dupe of https://github.com/golang/go/issues/12573

**Closed** 2015-12-17 20:18 UTC
