### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by astrolox** [golang/go#44275] opened 2021-02-15 21:58 UTC
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/cachefly/vfs
 
### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
 
### Screenshot
  
![image](https://user-images.githubusercontent.com/1836629/107996605-ac580200-6fd8-11eb-8dee-805fa2e7e6f5.png)
 
![image](https://user-images.githubusercontent.com/1836629/107996612-af52f280-6fd8-11eb-907c-10a338b6772b.png)
 
### What did you do?
 
Visit the above URL.
 
### What did you expect to see?
 
A HTTP 404 not found error.
 
### What did you see instead?

Obsolete Content.

**Comment by fzipp** [comment] 2021-02-15 22:04
See #43297

**Comment by julieqiu** [comment] 2021-02-16 23:25
Closing as a duplicate of #43297.

**Closed by julieqiu** 2021-02-16 23:25 UTC
Labels: NeedsInvestigation, pkgsite
