### ISSUE TITLE
syscall, os/exec: Support running child process as different user on Windows

### ISSUE THREAD

**Issue by mappu** [golang/go#35653] opened 2019-11-17 22:12 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

n/a

### What operating system and processor architecture are you using (`go env`)?

n/a

### What did you do?

Try to launch a process as a different user. Found `syscall.Credential` can be supplied as a `SysProcAttr` to `exec.Cmd`.

### What did you expect to see?

Ability to launch process as different user, on all supported OSes.

### What did you see instead?

`syscall.Credential` only supports UID/GID and only works on Unix-like systems. There's no option for Windows (based on either `CreateProcessWithLogonW` call, or `LogonUser`/`CreateProcessAsUserW` pair call).

**Comment by acln0** [comment] 2019-11-18 05:04
On Windows, syscall.SysProcAttr is this: https://golang.org/pkg/syscall/?GOOS=windows#SysProcAttr

I think you can load the appropriate DLL for LogonUser (see https://godoc.org/golang.org/x/sys/windows#NewLazyDLL), call the function, which grants a syscall.Token, then use it with SysProcAttr.

**Comment by toothrot** [comment] 2019-11-18 20:59
Thanks @acln0, I think you're right. 

I believe this is a duplicate of #21105. I think the associated CL, golang.org/cl/75253 includes an example of this. I'll close this as a duplicate, but please let me know if I am mistaken.

**Closed by toothrot** 2019-11-18 20:59 UTC
