### ISSUE TITLE
x/tools/gopls: DocumentHighlight does not return correct locations for non-main module packages

### ISSUE THREAD

**Issue by myitcv** [golang/go#43848] opened 2021-01-22 16:12 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +59bfc18e34 Fri Jan 8 22:55:41 2021 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.1.0
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.0.0-20210119222503-fe37c9e135b9
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/myitcv/gostuff/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel +59bfc18e34 Fri Jan 8 22:55:41 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/playground/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2415781078=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Start with the following setup:

```
-- go.mod --
module mod.com

go 1.16

require golang.org/x/tools v0.1.0
-- main.go --
package main

import (
	"fmt"
	"log"

	"golang.org/x/tools/go/packages"
)

func main() {
	log.SetFlags(0)
	cfg := packages.Config{
		Mode: packages.NeedName,
	}
	pkgs, err := packages.Load(&cfg, "time")
	if err != nil {
		log.Fatal(err)
	}
	if packages.PrintErrors(pkgs) > 0 {
		log.Fatal("pkg errors")
	}
	fmt.Printf("%#v\n", pkgs[0])
}

```

Run `go mod tidy` to populate the `go.sum` (not included above for brevity).

Open `main.go`, navigate to the definition of `go/packages.Load`, place the cursor over the `cfg` parameter declaration, then invoke `DocumentHighlight`. You will get a response as follows:

```
gopls.DocumentHighlight() call; params:
&protocol.DocumentHighlightParams{
    TextDocumentPositionParams: protocol.TextDocumentPositionParams{
        TextDocument: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/pkg/mod/golang.org/x/tools@v0.1.0/go/packages/packages.go"},
        Position:     protocol.Position{Line:237, Character:11},
    },
    WorkDoneProgressParams: protocol.WorkDoneProgressParams{},
    PartialResultParams:    protocol.PartialResultParams{},
}
gopls server end =======================
gopls server start =======================
gopls.DocumentHighlight() return; err: <nil>; res:
[]protocol.DocumentHighlight{
    {
        Range: protocol.Range{
            Start: protocol.Position{Line:237, Character:10},
            End:   protocol.Position{Line:237, Character:13},
        },
        Kind: 1,
    },
}
```

I.e. the response only includes the declaration of `cfg`, not its usages.

Performing such a request for an identifier in a main module package works as expected, i.e. all references to the identifier are returned.

### What did you expect to see?

As above.

### What did you see instead?

As above.

---

cc @stamblerre

FYI @leitzler

**Comment by myitcv** [comment] 2021-01-22 16:13
Apologies, forgot to attach the logfiles:

* [gopls.log](https://github.com/golang/go/files/5857067/gopls.log)
* [govim.log](https://github.com/golang/go/files/5857069/govim.log)

**Comment by stamblerre** [comment] 2021-01-22 18:25
Thanks for the report! This sounds like a duplicate of https://github.com/golang/go/issues/43511. OK if I close in favor of that issue?

**Comment by myitcv** [comment] 2021-01-22 18:42
Ah thanks. Yes that's fine (and apologies for not properly searching in the first instance)

**Closed** 2021-01-22 18:42 UTC
Labels: Documentation, NeedsInvestigation, Tools, gopls
