### ISSUE TITLE
testing.M failed to satisfy ut that calls os.Exit(0) twice.

### ISSUE THREAD

**Issue by njuptlzf** [golang/go#45619] opened 2021-04-18 09:44 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
Ubuntu 5.4.0-6ubuntu1~16.04.12)
### What did you do?
Use testing.M to test a case that may return os.Exit(0).
There are **two** cases to call os.Exit(0).

### What did you expect to see?

In the file, all cases are executed, and the execution results of all cases are correctly expressed.

### What did you see instead?
Execute to the first os.Exit(0), ut exits.

**Comment by davecheney** [comment] 2021-04-18 09:49
Can you please include a runnable example to demonstrate the problem. Thank you.

**Comment by njuptlzf** [comment] 2021-04-18 10:13
demo:
```
package test0418

import (
	"log"
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	log.Println("Do stuff BEFORE the tests!")
	m.Run()
	log.Println("Do stuff AFTER the tests!")
}

func TestA(t *testing.T) {
	log.Println("TestA running")
	os.Exit(0)
}

func TestB(t *testing.T) {
	log.Println("TestB running")
	os.Exit(1)
}

func TestC(t *testing.T) {
	log.Println("TestC running")
}
```

run:
```
# go test .
2021/04/18 17:59:08 Do stuff BEFORE the tests!
2021/04/18 17:59:08 TestA running
--- FAIL: TestA (0.00s)
panic: unexpected call to os.Exit(0) during test [recovered]
        panic: unexpected call to os.Exit(0) during test

goroutine 6 [running]:
testing.tRunner.func1.2(0x51e980, 0x5701d8)
        /root/go/go/src/testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc000001380)
        /root/go/go/src/testing/testing.go:1147 +0x4b6
panic(0x51e980, 0x5701d8)
        /root/go/go/src/runtime/panic.go:965 +0x1b9
os.Exit(0x0)
        /root/go/go/src/os/proc.go:68 +0x6d
test.TestA(0xc000001380)
        /home/go_project/test/test0418/testM_test.go:18 +0x6a
testing.tRunner(0xc000001380, 0x5517c8)
        /root/go/go/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
        /root/go/go/src/testing/testing.go:1239 +0x2b3
FAIL    test    0.006s
FAIL
# echo $?
1
```

I expect to execute all possible use cases for os.Exit(int), and if only int==0, the overall success. Because sometimes even calling os.Exit(0) is an expected behavior.
Otherwise, it seems that I can only consider using `mock`?

**Comment by davecheney** [comment] 2021-04-18 10:22
test's shouldn't call os.Exit. If you want to abort the test use t.FailNow()

**Comment by ianlancetaylor** [comment] 2021-04-18 23:17
Closing this issue because this working as intended.  If a test calls `os.Exit`, the test binary will exit, and `go test` will report a failure.

**Closed by ianlancetaylor** 2021-04-18 23:17 UTC
Labels: WaitingForInfo
