### ISSUE TITLE
go.dev: "Report an Issue" link does not work on firefox

### ISSUE THREAD

**Issue by kortschak** [golang/go#37009] opened 2020-02-04 04:04 UTC
The "Report an Issue" and the "Share Feedback" links do not work on Firefox (hence this potentially incorrect structure of this report).

### What is the URL of the page with the issue?

https://pkg.go.dev/

### What is your user agent?

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0

### What did you do?

Click on "Report an Issue".

### What did you expect to see?

A browser response.

### What did you see instead?

No change.

**Comment by ALTree** [comment] 2020-02-04 07:51
Can reproduce on Firefox on windows too. When you click on the button, the console says:

 ```
ReferenceError: userfeedback is not defined [feedback.js:17:3]
 ```

**Comment by mvdan** [comment] 2020-02-04 12:11
I reported this last summer to @julieqiu and @findleyr - this problem made it difficult for me to report feedback too.

However, I think it has been fixed since. The "report an issue" button works for me on Firefox 72.0.2, showing a popup element within the page.

**Comment by mvdan** [comment] 2020-02-04 12:24
I should also clarify that I'm on Linux. Maybe this only reproduces on Windows?

**Comment by kortschak** [comment] 2020-02-04 12:29
I am running linux and it fails here.

**Comment by findleyr** [comment] 2020-02-04 14:37
Thank you for the report -- this appears to be a regression. I am investigating.

**Comment by findleyr** [comment] 2020-02-04 17:53
Ok, I applied a fix on the backend that resolves some feedback reporting issues, and have verified that I can file feedback from Firefox on both Linux and Windows.

However, even before this fix I did not see `ReferenceError: userfeedback is not defined [feedback.js:17:3]`.

@kortschak, do you see the same error in your Firefox console when you try to file feedback?

@ALTree, when you have a chance could you please confirm that you are still seeing this problem?  If so:
- Which version of Firefox are you using?
- Do you see any other errors in your console?
- Are you using any Firefox add-ons that would affect javascript execution?

Thanks!
- Rob

**Comment by kortschak** [comment] 2020-02-04 20:28
Thanks. I see a similar error:

```
ReferenceError: userfeedback is not defined                                                                   site.js:52:5
    sendFeedback https://go.dev/js/site.js:52
```

**Comment by ALTree** [comment] 2020-02-05 07:47
So I tested it with Firefox on Linux on my home connection and it works, but it still doesn't work on the Windows machine I used above (Firefox 72.0.2, no addons).

When I load the page at https://pkg.go.dev, I see these two errors in the console:

```
[utils.js:35:9]
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src").

[pkg.go.dev:21:1]
Loading failed for the <script> with source “https://support.google.com/inapp/api.js”. 
```

Then, when I click on "Report an Issue", this other message appears:

```
[feedback.js:17:3]
ReferenceError: userfeedback is not defined    

    sendFeedback https://pkg.go.dev/static/js/feedback.js?version=2020-02-03t15-29-caa6643937a6319c8059e5a4d2694d02b980e68c:17
```

**Comment by findleyr** [comment] 2020-02-05 22:29
Much appreciated. That Content-Security-Policy error is almost certainly the problem.  It is surprising that I don't get the same error when running Firefox 72.02 on windows -- I don't see any Firefox settings that could make its CSP interpretation *more strict* than my Firefox...

I have merged a CSP change, guarded behind an experiment, that may fix this. Once it is deployed to production (probably early next week) I will ask you to try again. Sorry for the remote debugging, without being able to reproduce this is difficult to diagnose.

**Comment by kortschak** [comment] 2020-02-05 22:49
I have just tried loading the site with advanced tracking protection off and the links work, so the differences are probably explained by differences in this browser setting.

**Comment by findleyr** [comment] 2020-02-06 19:17
(first of all, sorry for the Gopherbot spam -- this issue number was one character off of another that I was looking at)

@kortschak thanks very much for that find. Unfortunately I can't reproduce even after enabling the strictest privacy protections on Firefox 72.02 on Windows. Still, I have hopes that the upcoming CSP change will work (which, for the record, is to enable 'strict-dynamic' for our script-src directive).  I'll follow up here once that is deployed.

**Comment by kortschak** [comment] 2020-02-06 19:53
Thanks. I'll retry when I hear back.

**Comment by kortschak** [comment] 2020-02-10 08:53
For an additional data point. I recently reported a site issue with an e-commerce site where their site is guarded by a Captcha provided by Google. The Captcha does not render on FF with advanced tracking protection on, but does with it off. They were unable to reproduce the issue with it on, but they were using Windows.

I suspect there's something about the js libraries G is using for these widgets, and that the platform FF is running on makes a difference.

**Comment by findleyr** [comment] 2020-02-11 21:25
Thanks for that data point. I've tried FF 72 on Windows, and FF 68 on Linux. I'll try to test a more recent FF on Linux.

Could you try the feedback link here? I have hope that strict-dynamic may fix the problem:
https://pkg.go.dev/?csp-strict-dynamic=true

**Comment by kortschak** [comment] 2020-02-11 21:31
Sorry, that makes no difference.

**Comment by ALTree** [comment] 2020-02-12 13:09
Same here. Visiting https://pkg.go.dev/?csp-strict-dynamic=true I see this when I load the page:

```
Content Security Policy: Ignoring “https://www.gstatic.com” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.googletagmanager.com” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://support.google.com” within script-src: ‘strict-dynamic’ specified
Loading failed for the <script> with source “https://support.google.com/inapp/api.js”.
```

So the last line is the same as before, and then the same error when clicking on the "Report an Issue" button:

```
[feedback.js:17:3]
ReferenceError: userfeedback is not defined
```

**Comment by findleyr** [comment] 2020-03-30 18:23
Thanks again for this report. We have removed the feedback API in favor of our two other feedback channels:
- the Go issue tracker for public feedback
- go-discovery-feedback@google.com for private feedback

So this bug is no longer relevant.

**Closed by findleyr** 2020-03-30 18:23 UTC
Labels: NeedsInvestigation, go.dev
