### ISSUE TITLE
This is caused by the change to make gomobile Android-Q compatible. Can you try to provide the `ApplicationContext` by using the static method `Seq.setContext(Context context)` before getting the assets?

### ISSUE THREAD

**Issue by navneetgulati** [golang/go#42778] opened 2020-11-23 05:16 UTC
This is caused by the change to make gomobile Android-Q compatible. Can you try to provide the `ApplicationContext` by using the static method `Seq.setContext(Context context)` before getting the assets?

_Originally posted by @timcooijmans in https://github.com/golang/go/issues/33254#issuecomment-515405042_

Hey,
I am getting the same error but I am not sure where and how to write the method `Seq.setContext(Context context)`. I cannot find any documentation related to that too. Can you please point me in the right path or point me to the library I have to import in go file before I write this code. I am getting `undeclared name: Seq` when I try to write this without importing anything

**Comment by ALTree** [comment] 2020-11-23 08:21
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-11-23 08:21 UTC
