### ISSUE TITLE
I can't import "cloud.google.com/go/datastore"

### ISSUE THREAD

**Issue by jonathanhecl** [golang/go#35163] opened 2019-10-25 20:04 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
From 1.13.0~

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\gense\AppData\Local\go-build
set GOENV=C:\Users\gense\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\gense\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\gense\AppData\Local\Temp\go-build754728190=/tmp/go-build -gno-record-gcc-switches
GOROOT/bin/go version: go version go1.13.3 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.13.3
gdb --version: GNU gdb (GDB) 7.9.1
</pre></details>

### What did you do?

My source for test:

```
package main

import (
	"fmt"

	"cloud.google.com/go/datastore"
)

var client *datastore.Client

func main() {
	fmt.Println("Work")
}
```

### What did you expect to see?

"Work"

### What did you see instead?

> $ go run main.go

```
# google.golang.org/grpc/internal/transport
..\..\..\..\google.golang.org\grpc\internal\transport\http_util.go:270:23: cannot use hf (type "vendor/golang.org/x/net/http2/hpack".HeaderField) as type
"golang.org/x/net/http2/hpack".HeaderField in argument to d.processHeaderField
..\..\..\..\google.golang.org\grpc\internal\transport\http_util.go:675:23: cannot use "golang.org/x/net/http2/hpack".NewDecoder(http2InitHeaderTableSize,
nil) (type *"golang.org/x/net/http2/hpack".Decoder) as type *"vendor/golang.org/x/net/http2/hpack".Decoder in assignment
```

**Comment by dmitshur** [comment] 2019-10-25 20:27
Hello. This issue tracker is for problems with the Go tools and standard library. The error you're seeing is related to the [cloud.google.com/go/datastore](https://godoc.org/cloud.google.com/go/datastore) package, so you should use its issue tracker located at https://github.com/googleapis/google-cloud-go/issues.

I can't reproduce the problem, the latest version of `cloud.google.com/go/datastore` works without build errors in both module mode and GOPATH mode:

```
$ cd $(mktemp -d)
$ go mod init foo.test
go: creating new go.mod: module foo.test
$ nano main.go
$ go run .
Work
```

If you're using GOPATH mode, perhaps some of your dependencies are old and incompatible. If you're using module mode, please share your `go.mod` file it's possible to know what versions were used.

I'll close this here, but if you continue to have a problem with that package, please feel free to report the issue at its https://github.com/googleapis/google-cloud-go/issues issue tracker. Thanks.

**Closed by dmitshur** 2019-10-25 20:27 UTC

**Comment by jonathanhecl** [comment] 2019-10-25 20:36
I run:

> go mod init
> go mod tidy

```
go: finding cloud.google.com/go/datastore v1.0.0
go: finding cloud.google.com/go v0.47.0
go: downloading cloud.google.com/go/datastore v1.0.0
go: downloading cloud.google.com/go v0.47.0
go: extracting cloud.google.com/go/datastore v1.0.0
go: extracting cloud.google.com/go v0.47.0
go: downloading cloud.google.com/go v0.44.1
go: extracting cloud.google.com/go v0.44.1
go: downloading google.golang.org/grpc v1.21.1
go: downloading google.golang.org/genproto v0.0.0-20190801165951-fa694d86fc64
go: downloading google.golang.org/api v0.8.0
go: downloading github.com/golang/protobuf v1.3.2
go: downloading golang.org/x/tools v0.0.0-20190628153133-6cdbf07be9d0
go: extracting github.com/golang/protobuf v1.3.2
go: downloading golang.org/x/lint v0.0.0-20190409202823-959b441ac422
go: extracting golang.org/x/lint v0.0.0-20190409202823-959b441ac422
go: extracting golang.org/x/tools v0.0.0-20190628153133-6cdbf07be9d0
go: downloading golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: extracting golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: extracting google.golang.org/grpc v1.21.1
go: downloading go.opencensus.io v0.22.0
go: downloading google.golang.org/appengine v1.6.1
go: extracting google.golang.org/appengine v1.6.1
go: downloading golang.org/x/net v0.0.0-20190620200207-3b0461eec859
go: extracting go.opencensus.io v0.22.0
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: extracting github.com/googleapis/gax-go/v2 v2.0.5
go: downloading github.com/jstemmer/go-junit-report v0.0.0-20190106144839-af01ea7f8024
go: extracting google.golang.org/api v0.8.0
go: extracting github.com/jstemmer/go-junit-report v0.0.0-20190106144839-af01ea7f8024
go: extracting golang.org/x/net v0.0.0-20190620200207-3b0461eec859
go: downloading golang.org/x/exp v0.0.0-20190510132918-efd6b22b2522
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading honnef.co/go/tools v0.0.0-20190418001031-e561f6794a2a
go: extracting github.com/hashicorp/golang-lru v0.5.1
go: extracting honnef.co/go/tools v0.0.0-20190418001031-e561f6794a2a
go: downloading golang.org/x/text v0.3.2
go: extracting golang.org/x/exp v0.0.0-20190510132918-efd6b22b2522
go: downloading golang.org/x/sys v0.0.0-20190624142023-c5567b49c5d0
go: extracting google.golang.org/genproto v0.0.0-20190801165951-fa694d86fc64
go: downloading github.com/google/go-cmp v0.3.0
go: downloading github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
go: downloading github.com/google/martian v2.1.0+incompatible
go: downloading github.com/BurntSushi/toml v0.3.1
go: extracting github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
go: extracting github.com/BurntSushi/toml v0.3.1
go: extracting github.com/google/martian v2.1.0+incompatible
go: extracting github.com/google/go-cmp v0.3.0
go: extracting golang.org/x/sys v0.0.0-20190624142023-c5567b49c5d0
go: extracting golang.org/x/text v0.3.2
```

> $ go run main.go

```
go: finding github.com/golang/protobuf v1.3.2
go: finding cloud.google.com/go v0.44.1
go: finding github.com/googleapis/gax-go/v2 v2.0.5
go: finding google.golang.org/grpc v1.21.1
go: finding golang.org/x/net v0.0.0-20190620200207-3b0461eec859
go: finding google.golang.org/genproto v0.0.0-20190801165951-fa694d86fc64
go: finding golang.org/x/text v0.3.2
go: finding google.golang.org/api v0.8.0
go: finding go.opencensus.io v0.22.0
go: finding github.com/hashicorp/golang-lru v0.5.1
go: finding golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
Work
```

Thank you, now with a module it works :)
