### ISSUE TITLE
cmd/go: build failed

### ISSUE THREAD

**Issue by YoshikiShibata** [golang/go#59694] opened 2023-04-18 19:16 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-903a25ae11 Tue Apr 18 18:04:21 2023 +0000 darwin/arm64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/yoshiki/Library/Caches/go-build"
GOENV="/Users/yoshiki/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/yoshiki/gocode/pkg/mod"
GONOPROXY="github.com/x-asia/*"
GONOSUMDB="github.com/x-asia/*"
GOOS="darwin"
GOPATH="/Users/yoshiki/gocode"
GOPRIVATE="github.com/x-asia/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/yoshiki/tools/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/yoshiki/tools/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="devel go1.21-903a25ae11 Tue Apr 18 18:04:21 2023 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/yoshiki/gocode/src/github.com/x-asia/kauche-app/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/st/5c1mhclx0vg11gwfq0j7tfj80000gn/T/go-build498288797=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version devel go1.21-903a25ae11 Tue Apr 18 18:04:21 2023 +0000 darwin/arm64
GOROOT/bin/go tool compile -V: compile version devel go1.21-903a25ae11 Tue Apr 18 18:04:21 2023 +0000
uname -v: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
lldb --version: lldb-1403.0.17.64
Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
</pre></details>

### What did you do?

run all.bash

### What did you expect to see?

Build and testing pass.

### What did you see instead?

```
ok  	cmd/fix	5.731s
vcs-test.golang.org rerouted to http://127.0.0.1:51196
https://vcs-test.golang.org rerouted to https://127.0.0.1:51197
go test proxy running at GOPROXY=http://127.0.0.1:51198/mod
PASS
2023/04/19 04:12:32 unexpected files left in tmpdir: [dsymutil-477ea9]
FAIL	cmd/go	45.766s
```

**Comment by seankhliao** [comment] 2023-04-18 19:42
Duplicate of #59026

**Closed by seankhliao** 2023-04-18 19:42 UTC
