### ISSUE TITLE
x/tools/gopls: references query does not count positional assignments to struct fields

### ISSUE THREAD

**Issue by zhiqiangxu** [golang/go#67808] opened 2024-05-30 23:31 UTC
Here're the steps to reproduce:

1. git clone https://github.com/ethereum-optimism/op-geth
2. git checkout optimism

Open with vscode, then cmd+left click [`disableTxPool`](https://github.com/ethereum-optimism/op-geth/blob/966c43537e49f7936bb57a426079fb0da9baf03b/eth/api_backend.go#L52) field, it doesn't show the assignment to it [here](https://github.com/ethereum-optimism/op-geth/blob/966c43537e49f7936bb57a426079fb0da9baf03b/eth/backend.go#L290).

I guess vscode-go has a bug identifying **positional** assignments to struct field.

**Comment by findleyr** [comment] 2024-06-04 16:38
Thanks. This is a dupe of #66356.

**Closed by findleyr** 2024-06-04 16:38 UTC
Labels: gopls, Tools
