### ISSUE TITLE
x/tools/cmd/gopls times out when checking file with " " in filepath

### ISSUE THREAD

**Issue by JAicewizard** [golang/go#34299] opened 2019-09-14 18:55 UTC
### Does this issue reproduce with the latest release?
yes

### What did you do?
gopls check {path to file} // where abs(path to file) contains a space

### What did you expect to see?

gopls works

### What did you see instead?

timeout for file diagnostics

**Comment by stamblerre** [comment] 2019-09-16 14:31
This sounds like a duplicate of https://github.com/golang/go/issues/34270. I'm going to close this issue and post updates there.

**Closed by stamblerre** 2019-09-16 14:31 UTC
Labels: Tools, gopls
