### ISSUE TITLE
net: TestInterfaces fails on freebsd-arm

### ISSUE THREAD

**Issue by bradfitz** [golang/go#15262] opened 2016-04-12 22:25 UTC
TestInterfaces fails on freebsd-arm:

```
--- FAIL: TestInterfaces (0.00s)
	interface_test.go:74: route ip+net: invalid network interface name
FAIL
FAIL	net	4.727s
```

/cc @mikioh

**Comment by mikioh** [comment] 2016-04-12 23:41
This is a duplicate of #7849.

**Closed by mikioh** 2016-04-12 23:41 UTC
Labels: OS-FreeBSD
