### ISSUE TITLE
'TrimLeft' Has A Bug

### ISSUE THREAD

**Issue by daysleep666** [golang/go#35660] opened 2019-11-18 09:39 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.13.4 darwin/amd64

</pre>

### CODE

```
package main

import (
	"fmt"
	"strings"
)

var PrefixTagSortKey = "v1:ts:"

func main() {
	str := PrefixTagSortKey + "t"
	v := strings.TrimLeft(str, PrefixTagSortKey)
	fmt.Println(v)
}
```

### What operating system and processor architecture are you using (`go env`)?

mac os 

### What did you do?

go run

### What did you expect to see?

t

### What did you see instead?

empty

**Comment by ALTree** [comment] 2019-11-18 09:42
Hi,

The second parameter of `TrimLeft` is **a cutset**, meaning that (from the documentation):

>  all leading Unicode code points contained in cutset removed. 

If the cutset is `"v1:ts:"`, every single `v`,  `1`,  `:`,  `t`, and  `s` character in the string will be cut.

You probably want `TrimPrefix `

> To remove a prefix, use TrimPrefix instead. 

Closing here, since this is working as intended.

**Closed by ALTree** 2019-11-18 09:42 UTC

**Comment by daysleep666** [comment] 2019-11-18 09:44
Thanks your explain.
