### ISSUE TITLE
x/tools/gopls: import errors when using go.work replace directives

### ISSUE THREAD

**Issue by jonbarrow** [golang/go#66425] opened 2024-03-16 23:30 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go version go1.21.3 linux/amd64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```
Build info
----------
golang.org/x/tools/gopls v0.15.2
    golang.org/x/tools/gopls@v0.15.2 h1:4JKt4inO8JaFW3l/Fh9X1k/5JQn+iUOpdc4/Lpi0mOs=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.6.0 h1:ofyhxvXcZhMsU5ulbFiLKl/XBFqE1GSq7atu8tAmTRI=
    golang.org/x/exp/typeparams@v0.0.0-20221212164502-fae10dda9338 h1:2O2DON6y3XMJiQRAS1UWU+54aec2uopH3x7MAiqGW6Y=
    golang.org/x/mod@v0.15.0 h1:SernR4v+D55NyBH2QiEQrlBAnj1ECL6AGrA5+dPaMY8=
    golang.org/x/sync@v0.6.0 h1:5BMeUDZ7vkXGfEr1x9B4bRcTH4lpkTkpdh0T/J+qjbQ=
    golang.org/x/telemetry@v0.0.0-20240209200032-7b892fcb8a78 h1:vcVnuftN4J4UKLRcgetjzfU9FjjgXUUYUc3JhFplgV4=
    golang.org/x/text@v0.14.0 h1:ScX5w1eTa3QqT8oi6+ziP7dTV1S2+ALU0bI+0zXKWiQ=
    golang.org/x/tools@v0.18.1-0.20240311201521-78fbdeb61842 h1:No0LMXYFkp3j4oEsPdtY8LUQz33gu79Rm9DE+izMeGQ=
    golang.org/x/vuln@v1.0.1 h1:KUas02EjQK5LTuIx1OylBQdKKZ9jeugs+HiqO5HormU=
    honnef.co/go/tools@v0.4.6 h1:oFEHCKeID7to/3autwsWfnuv69j3NsfcXbvJKuIcep8=
    mvdan.cc/gofumpt@v0.6.0 h1:G3QvahNDmpD+Aek/bNOLrFR2XC6ZAdo62dZu65gmwGo=
    mvdan.cc/xurls/v2@v2.5.0 h1:lyBNOm8Wo71UknhUs4QTFUNNMyxy2JEIaKKo0RWOh+8=
go: go1.21.3
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
```
1.85.2
8b3775030ed1a69b13e4f4c628c612102e30a681
x64
```

Though this happens on all tried versions, from 1.80 to 1.87

* Check your installed extensions to get the version of the VS Code Go extension
	- `v0.41.2`
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
# Tools Configuration


## Environment

GOBIN: undefined
toolsGopath: 
gopath: /home/jon/go
GOROOT: /usr/local/go
PATH: /home/jon/.local/share/pnpm:/home/jon/software:/home/jon/gems/bin:/opt/devkitpro/tools/bin:/home/jon/.nvm/versions/node/v21.6.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/go/bin:/opt/ghidra:/home/jon/go/bin:/home/jon/software/grpc/cmake/build

## Tools

	go:	/usr/local/go/bin/go: go version go1.21.3 linux/amd64

	gopls:	/home/jon/go/bin/gopls	(version: v0.15.2 built with go: go1.21.3)
	gotests:	/home/jon/go/bin/gotests	(version: v1.6.0 built with go: go1.21.3)
	gomodifytags:	/home/jon/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.21.3)
	impl:	/home/jon/go/bin/impl	(version: v1.1.0 built with go: go1.21.3)
	goplay:	/home/jon/go/bin/goplay	(version: v1.0.0 built with go: go1.21.3)
	dlv:	/home/jon/go/bin/dlv	(version: v1.21.1 built with go: go1.21.3)
	golangci-lint:	/home/jon/go/bin/golangci-lint	(version: (devel) built with go: go1.21.3)

## Go env

Workspace Folder (nex-go-rewrite): /home/jon/pretendo/nex-go-rewrite

	GO111MODULE=''
	GOARCH='amd64'
	GOBIN=''
	GOCACHE='/home/jon/.cache/go-build'
	GOENV='/home/jon/.config/go/env'
	GOEXE=''
	GOEXPERIMENT=''
	GOFLAGS=''
	GOHOSTARCH='amd64'
	GOHOSTOS='linux'
	GOINSECURE=''
	GOMODCACHE='/home/jon/go/pkg/mod'
	GONOPROXY=''
	GONOSUMDB=''
	GOOS='linux'
	GOPATH='/home/jon/go'
	GOPRIVATE=''
	GOPROXY='direct'
	GOROOT='/usr/local/go'
	GOSUMDB='sum.golang.org'
	GOTMPDIR=''
	GOTOOLCHAIN='auto'
	GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
	GOVCS=''
	GOVERSION='go1.21.3'
	GCCGO='gccgo'
	GOAMD64='v1'
	AR='ar'
	CC='gcc'
	CXX='g++'
	CGO_ENABLED='1'
	GOMOD='/home/jon/pretendo/nex-go-rewrite/go.mod'
	GOWORK=''
	CGO_CFLAGS='-O2 -g'
	CGO_CPPFLAGS=''
	CGO_CXXFLAGS='-O2 -g'
	CGO_FFLAGS='-O2 -g'
	CGO_LDFLAGS='-O2 -g'
	PKG_CONFIG='pkg-config'
	GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build371863881=/tmp/go-build -gno-record-gcc-switches'
	
Workspace Folder (nex-protocols-go): /home/jon/pretendo/nex-protocols-go

	GO111MODULE=''
	GOARCH='amd64'
	GOBIN=''
	GOCACHE='/home/jon/.cache/go-build'
	GOENV='/home/jon/.config/go/env'
	GOEXE=''
	GOEXPERIMENT=''
	GOFLAGS=''
	GOHOSTARCH='amd64'
	GOHOSTOS='linux'
	GOINSECURE=''
	GOMODCACHE='/home/jon/go/pkg/mod'
	GONOPROXY=''
	GONOSUMDB=''
	GOOS='linux'
	GOPATH='/home/jon/go'
	GOPRIVATE=''
	GOPROXY='direct'
	GOROOT='/usr/local/go'
	GOSUMDB='sum.golang.org'
	GOTMPDIR=''
	GOTOOLCHAIN='auto'
	GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
	GOVCS=''
	GOVERSION='go1.21.3'
	GCCGO='gccgo'
	GOAMD64='v1'
	AR='ar'
	CC='gcc'
	CXX='g++'
	CGO_ENABLED='1'
	GOMOD='/home/jon/pretendo/nex-protocols-go/go.mod'
	GOWORK='/home/jon/pretendo/nex-protocols-go/go.work'
	CGO_CFLAGS='-O2 -g'
	CGO_CPPFLAGS=''
	CGO_CXXFLAGS='-O2 -g'
	CGO_FFLAGS='-O2 -g'
	CGO_LDFLAGS='-O2 -g'
	PKG_CONFIG='pkg-config'
	GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build152155767=/tmp/go-build -gno-record-gcc-switches'
	
```
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

- `"go.toolsManagement.autoUpdate": true`

### Describe the bug
`replace` directive seems to be ignored in `go.work` file. Failing to load the correct local package. Only occurs in VS Code, `go vet` reports no issues.

This behavior was working up until recently. I do not have an exact time/version this stopped working, as it has been a few days since I touched these modules.

### Steps to reproduce the behavior:
1. Create 2 modules
2. Add both to a VS Code workspace
3. Create a `go.work` in ModuleA
4. Set a `replace` directive in the `go.work` to point to ModuleB
5. ModuleB fails to be loaded in VS Code

### Screenshots or recordings
`go.work` contents:
```
go 1.21

use .

replace (
	github.com/PretendoNetwork/nex-go => ../nex-go-rewrite
)
```

Broken import/wrong package being referenced leading to many errors:
![Screenshot from 2024-03-16 19-23-19](https://github.com/golang/vscode-go/assets/27011796/421e6976-7d6d-4ec7-b4c9-607281bcf738)

The local package does exist:
![Screenshot from 2024-03-16 19-24-37](https://github.com/golang/vscode-go/assets/27011796/e0c1a2c0-575f-4c05-a988-fcba7a11ddbb)

`go vet` command showing no errors (issue is only within VS Code):
![Screenshot from 2024-03-16 19-25-24](https://github.com/golang/vscode-go/assets/27011796/5ccf0d93-82ce-4226-9cfe-a3d6e888ac1e)

**Comment by findleyr** [comment] 2024-03-20 14:04
This appears to be a gopls issue, so I transferred to the Go issue tracker.

One possibility is that, among your workspace folders, there is a folder where these import errors are actually _correct_, i.e. there's a workspace that legitimately can't load this module. In gopls@v0.14.2, we didn't merge diagnostics from multiple workspaces, so it would have been easy to miss such errors.

Since we don't have a simple repro, and your standard workspace setup sounds quite complicated, I think the thing to do is prepare a CL that more clearly identifies which folders are producing a diagnostic. Then we can perhaps narrow down the reproducer. I'll do this, but it might take a week or so as I'm traveling.

I suspect that this issue only affects a very small number of users: only a small fraction of users have multi-root workspaces, and among them only another fraction use multiple go.work files, and among them only a fraction use go.work replace directives (these are quite rare).

CC @adonovan for awareness. Alan: I don't think any action is required on your part unless this appears to be affecting a larger number of users, since @jonbarrow is unblocked by downgrading to gopls@v0.14.2. I want to get to the bottom of this, but it requires some work on my end to help diagnose.

**Comment by findleyr** [comment] 2024-04-01 16:25
@jonbarrow, I wonder if https://go.dev/cl/574718 improves the situation for you. Could you test?

Here's how to install that CL:

```
git clone https://go.googlesource.com/tools
cd tools/gopls
git fetch https://go.googlesource.com/tools refs/changes/18/574718/1 && git checkout FETCH_HEAD
go install
```

Does that version of gopls still have the spurious import errors?

**Comment by jonbarrow** [comment] 2024-04-02 09:10
> @jonbarrow, I wonder if [go.dev/cl/574718](https://go.dev/cl/574718) improves the situation for you. Could you test?
> 
> Here's how to install that CL:
> 
> ```
> git clone https://go.googlesource.com/tools
> cd tools/gopls
> git fetch https://go.googlesource.com/tools refs/changes/18/574718/1 && git checkout FETCH_HEAD
> go install
> ```
> 
> Does that version of gopls still have the spurious import errors?

So far so good! :+1:

**Closed** 2024-04-03 18:28 UTC
Labels: gopls, Tools

**Comment by findleyr** [comment] 2024-04-03 19:16
Thanks for testing. I think this change is safe to make, so I've tentatively marked this as fixed.

It would be good to understand exactly *how* the spurious diagnostics are being produced, but I think it's also safe to simply filter diagnostics to the most relevant builds, as I've done.
