### ISSUE TITLE
flag: ContinueOnError is not continuing

### ISSUE THREAD

**Issue by curlup** [golang/go#16469] opened 2016-07-22 09:41 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.4.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="~/gocode"
GORACE=""
GOROOT="~/code/go"
GOTOOLDIR="~/code/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?
```
fs := flag.NewFlagSet("d", flag.ContinueOnError)
boolPtr := fs.Bool("fork", false, "a bool")
_ = fs.Parse([]string{"-unknown", "--fork"})
````
https://play.golang.org/p/93DWNF-53z

4. What did you expect to see?
`fork: true` because `ContinueOnError` is used

5. What did you see instead?
```
flag provided but not defined: -unknown
Usage of d:
  -fork
    	a bool
fork: false
```
I didn't expect to see `Usage` though

**Comment by martinlindhe** [comment] 2016-07-22 13:49
flag.ContinueOnError says "Return a descriptive error" [1]
Additionally, the 2nd parameter to fs.Bool() is the default value to use. Sinceyou set it to false, that will be the value of *boolPtr [2]

1: https://golang.org/src/flag/flag.go?s=6739:6761#L259
2: https://play.golang.org/p/7QJz9r6lo_

**Comment by ianlancetaylor** [comment] 2016-07-22 13:59
I think this is working as intended.  Certainly we are not going to change the behavior.  If you have a specific suggestion for how to improve the docs, please let us know.  Closing.

**Closed by ianlancetaylor** 2016-07-22 13:59 UTC
