### ISSUE TITLE
go get -mod=readonly updates go.mod

### ISSUE THREAD

**Issue by davecheney** [golang/go#31273] opened 2019-04-05 06:46 UTC
### What version of Go are you using (`go version`)?

<pre>
% go version
go version devel +964fe4b80f Thu Apr 4 00:26:24 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

As part of my `make test` target I run 

```
go get -mod=readonly honnef.co/go/tools/cmd/staticcheck
```

### What did you expect to see?

`go.mod` is not modified 

### What did you see instead?

`go.mod` is modified.

This is a problem because I do not want to record the version of `honnef.co/go/tools/cmd/staticcheck` that was used in my `go.mod` file. I _explicitly_ want to leave this version floating so that i automatically receive updates to that tool. I want to do this because this tool is not part of my project, its part of the tools I use to test my project, when they are updated, I want to receive those updates without `go get` dirtying `go.mod` every time I run my `make check` target

**Comment by cuonglm** [comment] 2019-04-05 07:14
it's expected, as `go get` still be allowed to update go.mod, wven with `-mod=readonly`, from `go help modules`:

> If invoked with -mod=readonly, the go command is disallowed from the implicit
> automatic updating of go.mod described above. Instead, it fails when any changes
> to go.mod are needed. This setting is most useful to check that go.mod does
> not need updates, such as in a continuous integration and testing system.
> The "go get" command remains permitted to update go.mod even with -mod=readonly,
> and the "go mod" commands do not take the -mod flag (or any other build flags).

**Comment by davecheney** [comment] 2019-04-05 07:45
@cuonglm thank you for your reply.

1. go get -mod=readonly does not appear to exit as you described above. The command completes without error.
2. Please consider my use case

> This is a problem because I do not want to record the version of honnef.co/go/tools/cmd/staticcheck that was used in my go.mod file. I explicitly want to leave this version floating so that i automatically receive updates to that tool. I want to do this because this tool is not part of my project, its part of the tools I use to test my project, when they are updated, I want to receive those updates without go get dirtying go.mod every time I run my make check target

Is there a way to achieve this without dirtying my local copy of `go.mod` ?

**Comment by cuonglm** [comment] 2019-04-05 08:05
@davecheney 

> go get -mod=readonly does not appear to exit as you described above. The command completes without error.

It does if you use `go build` instead of `go get`.

> Is there a way to achieve this without dirtying my local copy of go.mod ?

I don't know anyway in current version.

**Comment by davecheney** [comment] 2019-04-05 08:29
Thank you for your reply

Doing a checkout of `go.mod` as part of my development workflow will make it impossible to run `make check` when I have updated other dependant modules. Is there a way to say "don't update go.mod"? Can I change permissions on the file? Will that work?

**Comment by cuonglm** [comment] 2019-04-05 08:40
@davecheney how about disable go modules for that check only:

```
GO111MODULE=off go get -mod=readonly honnef.co/go/tools/cmd/staticcheck
```

**Comment by davecheney** [comment] 2019-04-05 08:43
Thank you. I think that will work, I'll try that.

**Comment by bcmills** [comment] 2019-04-08 12:45
The behavior of `go get` is intentional (see @rsc's comment in https://github.com/golang/go/issues/26850#issuecomment-411903910).

An option specifically for installing tools without affecting `go.mod` is discussed in #30515. If I understand correctly, that is exactly the use-case you describe here, so I'm closing this as a duplicate of #30515, but please do let me know if I've missed something.

**Closed by bcmills** 2019-04-08 12:45 UTC
