### ISSUE TITLE
golang/runtime.SetFinalizer: pointer not at beginning of allocated block

### ISSUE THREAD

**Issue by zyxkad** [golang/go#50814] opened 2022-01-26 00:07 UTC
### What did you do?
See <https://go.dev/play/p/k8-gAXaEIy3>
```golang

package main

import (
	"runtime"
	"unsafe"
)

func main() {

	type T struct{ byte }
	for i := 0; i < 1024; i++ { // i < 1024, or you may let it some bigger
		v := &T{}
		// will panic: fatal error: runtime.SetFinalizer: pointer not at beginning of allocated block
		runtime.SetFinalizer((*interface{})(unsafe.Pointer(v)), func(*interface{}) {
			// just do nothing
		})
	}
}
```

### What did you expect to see?

No thing will happen

### What did you see instead?
A panic like:
```
fatal error: runtime.SetFinalizer: pointer not at beginning of allocated block

goroutine 1 [running]:
runtime.throw({0x4699d4, 0x0})
	/usr/local/go-faketime/src/runtime/panic.go:1198 +0x71 fp=0xc000034670 sp=0xc000034640 pc=0x42c8b1
runtime.SetFinalizer({0x45b4c0, 0xc000096001}, {0x45cdc0, 0x469bd8})
	/usr/local/go-faketime/src/runtime/mfinal.go:383 +0x53b fp=0xc000034748 sp=0xc000034670 pc=0x412e9b
main.main()
	/tmp/sandbox1629265645/prog.go:15 +0x46 fp=0xc000034780 sp=0xc000034748 pc=0x4581a6
runtime.main()
	/usr/local/go-faketime/src/runtime/proc.go:255 +0x213 fp=0xc0000347e0 sp=0xc000034780 pc=0x42eef3
runtime.goexit()
	/usr/local/go-faketime/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000347e8 sp=0xc0000347e0 pc=0x455381
```

**Comment by zyxkad** [comment] 2022-01-26 00:11
Actually, just this will be panic:  
<https://go.dev/play/p/J_FmT9_zsIb>
```golang
package main

import (
	"runtime"
	"unsafe"
)

func main() {
	type T struct{ byte }
	v := &T{}
	runtime.SetFinalizer((*interface{})((unsafe.Pointer)(v)), func(*interface{}) {
		// just do nothing
	})
	v = &T{}
	// will panic: fatal error: runtime.SetFinalizer: pointer not at beginning of allocated block
	runtime.SetFinalizer((*interface{})((unsafe.Pointer)(v)), func(*interface{}) {
		// just do nothing
	})
}
```

**Comment by randall77** [comment] 2022-01-26 00:36
I'm not sure why you are using unsafe there. The cast from `*byte` to `*interface{}` isn't allowed, as the result of that cast points past the allocation. Just do this, and it works:
```
package main

import (
	"runtime"
)

func main() {
	type T struct{ byte }
	v := &T{}
	runtime.SetFinalizer(v, func(*T) {
		// just do nothing
	})
	v = &T{}
	runtime.SetFinalizer(v, func(*T) {
		// just do nothing
	})
}
```

**Comment by zyxkad** [comment] 2022-01-26 00:42
> I'm not sure why you are using unsafe there. The cast from `*byte` to `*interface{}` isn't allowed, as the result of that cast points past the allocation. Just do this, and it works:
> 
> ```
> package main
> 
> import (
> 	"runtime"
> )
> 
> func main() {
> 	type T struct{ byte }
> 	v := &T{}
> 	runtime.SetFinalizer(v, func(*T) {
> 		// just do nothing
> 	})
> 	v = &T{}
> 	runtime.SetFinalizer(v, func(*T) {
> 		// just do nothing
> 	})
> }
> ```

I was trying to build a weakref package, so the full codes is like:
```golang

package weakref

import (
	unsafe "unsafe"
	runtime "runtime"
)

type Pointer = unsafe.Pointer

type WeakRef struct{
	a bool
	p uintptr
}

func NewWeakRef(ptr Pointer)(w *WeakRef){
	if ptr == nil {
		panic("ptr cannot be nil")
	}
	w = &WeakRef{
		a: true,
		p: (uintptr)(ptr),
	}
	runtime.SetFinalizer((*interface{})(ptr), func(*interface{}){
		w.a = false
	})
	return
}

func (w *WeakRef)Ok()(bool){
	return w.a
}

func (w *WeakRef)Value()(Pointer){
	if !w.a {
		return nil
	}
	return (Pointer)(w.p)
}

////////
package weakref_test

import (
	"testing"
	"runtime"
	weakref "github.com/kmcsr/go-weakref"
)

func TestWeakRef(t *testing.T){
	type T struct{ byte }
	for i := 0; i < 1024; i++ {
		v := &T{}
		ref := weakref.NewWeakRef(weakref.Pointer(v))
		t.Log("ref:", ref)
		t.Log("Alive:", ref.Ok())
		if ref.Ok() {
			t.Log("Value:", (*T)(ref.Value()))
		}
		runtime.GC()
		t.Log("=== After GC")
		t.Log("Alive:", ref.Ok())
		if ref.Ok() {
			t.Log("Value:", (*T)(ref.Value()))
		}
	}
}

```

**Comment by randall77** [comment] 2022-01-26 00:46
You can't safely use unsafe to cast `*A` to `*B` if `B` is bigger than `A`. See https://pkg.go.dev/unsafe#Pointer rule 1.
Closing, as this is not a bug. For questions please refer to https://github.com/golang/go/wiki/Questions .

**Closed by randall77** 2022-01-26 00:46 UTC
