### ISSUE TITLE
x/tools/cmd/guru: referrers does not show references from entire GOPATH in windows

### ISSUE THREAD

**Issue by Vigneshr6** [golang/go#24699] opened 2018-04-05 13:05 UTC
### What version of Go are you using (`go version`)?
go 1.9.2

### What operating system and processor architecture are you using (`go env`)?
windows 7 amd64

### What did you do?
I tried to find all the references of a go function from entire GOPATH.
In linux it works as expected.But in windows it shows only the references from the same package.

command:-
`guru -json referrers src\samplepac\sample.go:#3242,#3249`

**Comment by Anaminus** [comment] 2018-05-31 13:07
This line appears to be the culprit:

https://github.com/golang/tools/blob/a5b4c53f6e8bdcafa95a94671bf2d1203365858b/cmd/guru/what.go#L205

The slashes of the import path are not normalized, which causes comparisons fail later on ([here, specifically](https://github.com/golang/tools/blob/a5b4c53f6e8bdcafa95a94671bf2d1203365858b/cmd/guru/referrers.go#L236)). Using `filepath.ToSlash` on `importPath` appears to fix the problem. For example,
```go
importPath = filepath.ToSlash(importPath)
```

**Comment by neclepsio** [comment] 2018-12-18 08:45
I'm affected too. I confirm the change at https://golang.org/cl/151057 fixes the problem.

**Comment by doxxx** [comment] 2019-01-02 00:53
I think this is a dupe of #23318.

**Closed** 2019-02-25 23:45 UTC
Labels: NeedsFix, OS-Windows
