### ISSUE TITLE
 Why isn't that fakedriver in the database/sql package public? 

### ISSUE THREAD

**Issue by donutloop** [golang/go#19216] opened 2017-02-21 12:50 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using ?

1.8

### What operating system and processor architecture are you using (`go env`)?

GOHOSTARCH="amd64"
GOOS="linux"

Why isn't that fakedriver in the database/sql package public? 
In my opinion is that good for mocking out the real database driver.

**Comment by ianlancetaylor** [comment] 2017-02-21 14:31
Different people have different needs from mocks.  The fake driver is not the same as any real driver; it doesn't even speak the same language.  Trying to turn this into something that satisfies everyone will be painful.  Better for each person who needs to mock a database to start with this code and customize as they need.

Closing because this is not a bug report.

**Closed by ianlancetaylor** 2017-02-21 14:31 UTC
