### ISSUE TITLE
proposal: cmd/gofmt allow keeping one line as is in which if block is quite simple especially for `if err != nil { return err; }` 

### ISSUE THREAD

**Issue by hauntedness** [golang/go#53567] opened 2022-06-27 12:23 UTC
Current gofmt will always write an individual line for the if block body. I propose that we could have an one line formatting.
This will benefit the error handling. In case we are viewing code of which couples of errors returned from callee. The current formating has 2x meanless lines, we have to scroll down, we could not see all of the code. This proposal doesn't mean to force one line. People can still stay with the existing format

```go

// current format
func currentFmt() error {
	var err error
	err = task1()
	if err != nil {
		return errors.WithStack(err)
	}
	//...
	err = task2()
	if err != nil {
		return errors.WithStack(err)
	}
	//...
	err = task3()
	if err != nil {
		return errors.WithStack(err)
	}
	//...
	err = task4()
	if err != nil {
		log.Println(err)
		return errors.WithStack(err)
	}
	return nil
}

// proposed format
func proposedFmt() error {
	var err error
	err = task1()
        // if there is a ";" and there is only one line in block, keep it as is
	if err != nil {return errors.WithStack(err);}
        //...
	err = task2()
	if err != nil {return errors.WithStack(err);}
	//...
	err = task3()
	if err != nil {return errors.WithStack(err);}
	//...
	err = task4()
	if err != nil {
		log.Println(err)
		return errors.WithStack(err)
	}
	return nil
}


func task1() error {
	return errors.New("task1 failed")
}
func task2() error {
	return errors.New("task2 failed")
}
func task3() error {
	return errors.New("task3 failed")
}
func task4() error {
	return errors.New("task4 failed")
}

```

**Comment by seankhliao** [comment] 2022-06-27 12:49
Duplicate of #33113

**Closed by seankhliao** 2022-06-27 12:49 UTC
Labels: Proposal
