### ISSUE TITLE
runtime: TestCgoPprof{,PIE} is flaky

### ISSUE THREAD

**Issue by bcmills** [golang/go#37201] opened 2020-02-12 20:08 UTC
[2020-02-12T18:22:50-363bcd0/linux-ppc64le-power9osu](https://build.golang.org/log/1aa4511be96a9122a43eaf00d505ea84ec5e4c66)
[2020-02-07T18:08:01-b806182/linux-amd64-jessie](https://build.golang.org/log/3828f8edcad5e964fcb48d064340ebaa471120c2)

```
--- FAIL: TestCgoPprofPIE (8.17s)
    crash_cgo_test.go:311: [/workdir/go/bin/go tool pprof -traces /workdir/tmp/go-build499031835/testprogcgo_-buildmode=pie.exe /workdir/tmp/prof767840548]:
        File: testprogcgo_-buildmode=pie.exe
        Build ID: 8fb7f17909e63decefe761e095ce9dbd1c97e738
        Type: cpu
        Time: Feb 7, 2020 at 6:35pm (UTC)
        Duration: 200.51ms, Total samples = 0 
        -----------+-------------------------------------------------------
    crash_cgo_test.go:319: cpuHog traceback missing.
    crash_cgo_test.go:311: [/workdir/go/bin/go tool pprof -traces /workdir/tmp/prof767840548]:
        File: testprogcgo_-buildmode=pie.exe
        Build ID: 8fb7f17909e63decefe761e095ce9dbd1c97e738
        Type: cpu
        Time: Feb 7, 2020 at 6:35pm (UTC)
        Duration: 200.51ms, Total samples = 0 
        -----------+-------------------------------------------------------
    crash_cgo_test.go:319: cpuHog traceback missing.
FAIL
FAIL	runtime	33.607s
```

Given the timing of the logs, it's not clear to me whether this is a regression in Go 1.14 or simply an already-flaky test coming to the surface.

CC @mknyszek @aclements @hyangah @ianlancetaylor @mpx

**Comment by mpx** [comment] 2020-02-13 21:49
I suspect the test flaky since it only collects at least 2 cpuHog frames. I'm not familiar with how Pprof decides which samples to include in the profile, but it looks like in some rare cases cpuHog doesn't make the cut. The above log shows 0 samples reported in 200ms. That indicates the test loop exited early with at least 2 samples (since 200ms < 1 second loop timeout).

If so, collecting more samples should significantly reduce the likelihood of a fake.

I'm currently running a large number of tests to see if I can catch the flake. If that works, I should be able to confirm the above patch fixes the problem.

**Comment by mpx** [comment] 2020-02-15 06:03
I couldn't reproduce the flake on an unloaded machine, but I managed to reproduce it after ~13000 on a reasonably heavily loaded machine (lots of IO, CPU load and scheduling keeping the cores 100% busy).

```
--- FAIL: TestCgoPprofPIE (0.22s)
    crash_cgo_test.go:311: [/home/mark/go-dev/bin/go tool pprof -traces /tmp/go-build052039209/testprogcgo_-buildmode=pie.exe /tmp/prof021439459]:
        File: testprogcgo_-buildmode=pie.exe
        Build ID: 57c37c1d4a6f0a6bb608c00c63c35c050438b0c3
        Type: cpu
        Time: Feb 15, 2020 at 4:02am (AEDT)
        Duration: 200.27ms, Total samples = 0 
        -----------+-------------------------------------------------------
    crash_cgo_test.go:319: cpuHog traceback missing.
```

Retrying with the patch now.

**Comment by mpx** [comment] 2020-02-16 04:10
I was unable to reproduce the flake with the patch after ~200000 tests. Without the patch it typically fails within 5000-20000 tests (both tested from +123f7dd3e1).

I had a quick look through the profiling code and I can't see any good reason why frames should be dropped at all for this test. It's not clear to me why "2" frames were originally chosen.

Going in the other direction, waiting for only a single cpuHog frame appears reliable on go1.13.7, but fails easily on go1.14rc1 (usually <100 tests).

Running a bisect now to see where this test started failing intermittently.

**Comment by mpx** [comment] 2020-02-16 06:13
The test is flaky from 177a36a5dc (runtime: implement async scheduler preemption) onwards. The test is reliable with `GODEBUG=asyncpreemptoff=1`. @aclements 

The CGO traceback is definitely called (as noted above, I also confirmed with a trace write separately). There is some bad interaction between signal pre-emption and profiling which causes the sample to be lost.

Perhaps this test should only use a single frame? That would have surfaced the issue much earlier.

**Comment by mpx** [comment] 2020-02-21 03:12
@bcmills @aclements @ianlancetaylor  

It might be worth investigating this issue further before Go 1.14 is released to confirm the damage is limited to loss of some profile samples (and not something more fundamental).

**Comment by ianlancetaylor** [comment] 2020-02-21 03:32
The test doesn't count the number of profiling samples that are taken.  It counts the number of times the `pprofCgoTraceback` function is called.  That function is called any time a signal occurs while executing in non-Go code.  Before we started using signal based preemption, the only signal that would occur in non-Go code was `SIGPROF`.  Now we can also see `SIGURG`.  That is not a bug.  But it means that this test is flaky: if we see two `SIGURG` signals in non-Go code before we see any `SIGPROF` signals in non-Go code, the test will fail.

So I don't think there is a fundamental problem here.  It's a problem with the way that the test is written.  It's not a problem that would happen with real code.

Unfortunately I don't see a simple fix off hand, other than disabling signal based preemption for the test.

**Comment by mpx** [comment] 2020-02-21 04:06
Ah, great. Thanks for confirming it is expected that `pprofCgoTraceback` is called outside of profile samples, I missed that.

I've reverted my change to wait for 10 samples since makes it extremely unlikely that every one of them will not result in a sample. That should effectively deflake the test until a better test is desired/written.

**Comment by ianlancetaylor** [comment] 2020-02-21 14:22
Maybe we should simply disable signal-based preemption when running the test.  The point of the test is just to see that we pick up a stack trace for `SIGPROF`, disabling signal-based preemption doesn't invalidate what we are testing for.

**Comment by mpx** [comment] 2020-03-01 08:38
Sorry, missed that suggestion earlier - much better idea. I've updated the deflake change. Given this flake was only noticed after signal preemption, it should more or less make it disappear again. I haven't been able to reproduce it after disabling preemption.

**Comment by mpx** [comment] 2020-03-08 02:49
FYI, I left this issue open in case this issue should track fixing the test approach and/or runtime.

**Comment by bcmills** [comment] 2020-05-12 15:32
Still flaky after [CL 219417](https://golang.org/cl/219417):
[2020-05-12T15:01:56-a0698a6/linux-amd64-jessie](https://build.golang.org/log/ce82ec304be52250f63ab8308c7b7f3046337b92)

**Comment by danscales** [comment] 2020-05-12 23:27
I also got the failure with a recently rebased changed:

https://storage.googleapis.com/go-build-log/3d4facca/linux-amd64-race_bb62fb2a.log

**Comment by bcmills** [comment] 2020-05-14 19:12
[2020-05-13T11:59:26-810c27e/linux-amd64-race](https://build.golang.org/log/c082cbec6fd207c098f7bb512c31c03030892ecb)

**Comment by bcmills** [comment] 2020-05-21 03:44
Including both TestCgoPprofPIE and TestCgoPprof, it looks like this got quite a bit worse around 2020-05-11:
[2020-05-20T21:52:34-567556d/linux-amd64-fedora](https://build.golang.org/log/f7e500ad2764d2a621bba5830ffb3d8652e220d3)
[2020-05-13T11:59:26-810c27e/linux-amd64-race](https://build.golang.org/log/c082cbec6fd207c098f7bb512c31c03030892ecb)
[2020-05-12T15:01:56-a0698a6/linux-amd64-jessie](https://build.golang.org/log/ce82ec304be52250f63ab8308c7b7f3046337b92)
[2020-05-11T22:38:32-8c1db77/linux-amd64-race](https://build.golang.org/log/7f64983af80e1fa515c67a922c0b1090aa8650bd)
[2020-02-12T18:22:50-363bcd0/linux-ppc64le-power9osu](https://build.golang.org/log/1aa4511be96a9122a43eaf00d505ea84ec5e4c66)
[2020-02-07T18:08:01-b806182/linux-amd64-jessie](https://build.golang.org/log/3828f8edcad5e964fcb48d064340ebaa471120c2)

I've also seen it in quite a few TryBot results recently.

Marking as release-blocker for Go 1.15 due to the likelihood of a regression here.

**Comment by cagedmantis** [comment] 2020-05-21 21:39
@bcmills Can I make this a non-beta1 blocking issue?

**Comment by bcmills** [comment] 2020-05-21 21:47
Yep, that seems fine.

**Comment by odeke-em** [comment] 2020-05-29 10:05
I just got a failure at https://storage.googleapis.com/go-build-log/9b94d0b5/linux-amd64-race_d785929a.log
```shell
--- FAIL: TestCgoPprof (3.47s)
    crash_cgo_test.go:317: [/workdir/go/bin/go tool pprof -traces /workdir/tmp/go-build787198486/testprogcgo_.exe /workdir/tmp/prof847643684]:
        File: testprogcgo_.exe
        Build ID: a25028f2fff69a0864f81c4cca9180f2f354c52b
        Type: cpu
        Time: May 29, 2020 at 10:00am (UTC)
        Duration: 200.66ms, Total samples = 0 
        -----------+-------------------------------------------------------
    crash_cgo_test.go:325: cpuHog traceback missing.
    crash_cgo_test.go:317: [/workdir/go/bin/go tool pprof -traces /workdir/tmp/prof847643684]:
        File: testprogcgo_.exe
        Build ID: a25028f2fff69a0864f81c4cca9180f2f354c52b
        Type: cpu
        Time: May 29, 2020 at 10:00am (UTC)
        Duration: 200.66ms, Total samples = 0 
        -----------+-------------------------------------------------------
    crash_cgo_test.go:325: cpuHog traceback missing.
FAIL
FAIL	runtime	54.956s
FAIL
go tool dist: Failed: exit status 1
```

**Comment by cherrymui** [comment] 2020-05-29 19:26
Could this be similar to #39021 , in that the program gets signaled with SIGWINCH that sent to the the process group, and triggered pprofCgoTraceback to run too early?

**Comment by cherrymui** [comment] 2020-05-29 22:29
I think CL https://golang.org/cl/235557 also fixes this. On my machine it was ~10% failure rate (running runtime test in a loop), after applying that CL it doesn't fail with 100+ iterations.

**Comment by ianlancetaylor** [comment] 2020-06-16 02:49
This hasn't happened since CL 235557 was committed, and findflakes estimates a 0.00% probability that this is still broken.  Closing.

**Closed by ianlancetaylor** 2020-06-16 02:49 UTC
Labels: NeedsInvestigation, release-blocker
