### ISSUE TITLE
make.bash: confusing error if GOROOT contains a test-only package

### ISSUE THREAD

**Issue by alandonovan** [golang/go#27101] opened 2018-08-20 18:38 UTC
```
$ cd ~/goroot/src
$ git sync a034f31
$ cat test/a_test.go
package test_test
import "testing"
func Test(t *testing.T) {}
$ go test ./test
./ok    test    0.012s
$ ./make.bash 
Building Go cmd/dist using ~/go1.6.
Building Go toolchain1 using ~/go1.6.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/amd64.
go tool dist: unexpected stale targets reported by ~/goroot/pkg/tool/linux_amd64/go_bootstrap list -gcflags="" -ldflags="" for [std cmd]:
        STALE test: build ID mismatch
```

I think the error is trying to tell me that `go build ./test` would fail, but it took me a while to figure that out:

```
$ go build ./test
go build test: no non-test Go files in ~/goroot/src/test
```

**Comment by rsc** [comment] 2018-08-20 19:18
In your transcript did you mean to 'cd ~/goroot/src' ?
Otherwise I'm very confused.

**Comment by alandonovan** [comment] 2018-08-20 20:11
Yes, sorry about that. Updated.

**Comment by rsc** [comment] 2018-08-21 02:17
Duplicate of #27097. (Confirmed that my pending fix makes this go away.)

**Closed by rsc** 2018-08-21 02:17 UTC
