### ISSUE TITLE
x/build: linux-amd64-wsl: build failures with proxyconnect tcp: dial tcp 205.185.121.87:54288: i/o timeout

### ISSUE THREAD

**Issue by heschi** [golang/go#54742] opened 2022-08-29 16:25 UTC
[2022-08-27T05:43:59-ed83ed6-a621973/linux-amd64-wsl](https://build.golang.org/log/5e1b8f0b7eef2bd9b1044c97fad7f384e04fec63)
[2022-08-27T05:43:59-ada1728-a621973/linux-amd64-wsl](https://build.golang.org/log/5895e2c9a21d4703b030bec1027bf3e45f4e29e9)
[2022-08-27T05:43:59-a9ba230-a621973/linux-amd64-wsl](https://build.golang.org/log/817ed32d724cf8d1ae37067eb88768c70f54a379)
[2022-08-27T05:43:59-310b0ec-a621973/linux-amd64-wsl](https://build.golang.org/log/ae908627707bfe63673562f306bf37795fc33207)
[2022-08-27T05:43:32-a9ba230-969f48a/linux-amd64-wsl](https://build.golang.org/log/3890ba5e514b360fde68fe9f6b46af3104d32aec)
[2022-08-27T05:43:32-310b0ec-969f48a/linux-amd64-wsl](https://build.golang.org/log/0bff4b0648af4c3ed1bf01493730da9fa49fae92)
[2022-08-27T05:42:03-b0ca10f-a2d2e6e/linux-amd64-wsl](https://build.golang.org/log/5d1ee5ee27eb8bd40f1891648923ac722a274cfa)
[2022-08-27T05:42:03-310b0ec-a2d2e6e/linux-amd64-wsl](https://build.golang.org/log/fe55474180ef5e1b962de44173be67a9ed343fda)
[2022-08-27T02:36:28-83b083e-a094849/linux-amd64-wsl](https://build.golang.org/log/57a78f00552a107f0b84e4a0be2e4d8c82879980)
[2022-08-27T02:36:28-310b0ec-a094849/linux-amd64-wsl](https://build.golang.org/log/103e60de0f27e834a146630fec68c9bac73aaccc)
[2022-08-26T22:52:50-ada1728-333681d/linux-amd64-wsl](https://build.golang.org/log/e74d73b6f50cc9d2f261c57db4054784d95cd84f)
[2022-08-26T18:28:14-717a671-bf812b3/linux-amd64-wsl](https://build.golang.org/log/72f9a41ca227ab6e6840c19d67d3371306fd46c0)
[2022-08-26T18:17:27-74e35dd-3d6ba27/linux-amd64-wsl](https://build.golang.org/log/dca9221eb2a9d1bab29cacaeca6663036693373b)
[2022-08-26T18:13:33-b0ca10f-9e81099/linux-amd64-wsl](https://build.golang.org/log/bb7e7d688e7ef9d30f7f8d88bcaee1118129bb47)
[2022-08-26T18:13:33-062f8c9-9e81099/linux-amd64-wsl](https://build.golang.org/log/930d05771dd69031dd6284dd88680fa0fb8c2d40)
[2022-08-26T18:09:56-a9ba230-62125c9/linux-amd64-wsl](https://build.golang.org/log/adaee333bce8f03b275e72700b40f4c380412506)
[2022-08-26T18:05:21-ada1728-afd792f/linux-amd64-wsl](https://build.golang.org/log/a857ea5881d39e5e0b18da9a4994af3cfa39894e)
[2022-08-26T18:05:21-83b083e-afd792f/linux-amd64-wsl](https://build.golang.org/log/e9b824d9804bca4eb049e4a6a31ae71d6f2711ad)
[2022-08-26T18:03:42-74e35dd-4d13aab/linux-amd64-wsl](https://build.golang.org/log/3b4d3c42686467256859b01b4b40f96121235410)
[2022-08-26T17:48:20-ada1728-296c40d/linux-amd64-wsl](https://build.golang.org/log/8538cca3daca83cde15fc0c75ef8226f464b3ddf)
[2022-08-23T22:25:51-3330412-0765da5/linux-amd64-wsl](https://build.golang.org/log/33323bc842440e54435ab61430e2a871e0c5e210)
[2022-08-23T21:24:14-5ae4b70-60ad3c4/linux-amd64-wsl](https://build.golang.org/log/29e7c858a8b12e3b4e0ba19cbc516d18504ef6c3)
[2022-08-23T20:26:47-5ae4b70-70de482/linux-amd64-wsl](https://build.golang.org/log/a8b0a287245a125dcbc096b1922265de615a09a8)
[2022-08-23T20:23:19-5ae4b70-e7f2e56/linux-amd64-wsl](https://build.golang.org/log/6a92c55b7cf772f1dd8e88a455da0922fc782e8f)
[2022-08-23T18:12:45-145d0c1-c94633d/linux-amd64-wsl](https://build.golang.org/log/0a9ff59fbab14b3839dcb570591ca32abaa53fcc)
[2022-08-23T17:19:32-587a153-4e9183c/linux-amd64-wsl](https://build.golang.org/log/2ab3d594bd62ef21a7618a05f6bc19b547f67107)
[2022-08-22T16:48:36-6faf853-a10da77/linux-amd64-wsl](https://build.golang.org/log/983f16e9e4767b53e8dfaea592e4f5331b67d482)

cc @golang/wsl

**Comment by mengzhuo** [comment] 2022-08-30 04:37
I think it's related to #53722
The proxy.golang.com.cn is flaky? @oiooj

**Comment by bcmills** [comment] 2022-08-31 12:39
Duplicate of #52793

**Closed by bcmills** 2022-08-31 12:39 UTC
Labels: Builders, NeedsInvestigation
