### ISSUE TITLE
cmd/compile: "exec format error" when running newly-built binary on linux-loong64-3a5000

### ISSUE THREAD

**Issue by bcmills** [golang/go#53116] opened 2022-05-27 15:49 UTC
```
#!watchflakes
post <- builder ~ `^linux-loong64` && `exec format error`
```

```
##### ../test
# go run run.go -- linkname.go
fork/exec /tmp/workdir-host-linux-loong64-3a5000/tmp/13900000/a.exe: exec format error

FAIL	linkname.go	0.262s
```

`greplogs -l -e '(?ms)\Alinux-loong64.*exec format error'`
[2022-05-26T20:17:08-ec92580/linux-loong64-3a5000](https://build.golang.org/log/a1a6e8cde9a5280804561239a36ee2e4e0805803)
[2022-05-26T18:56:07-e6d8b05/linux-loong64-3a5000](https://build.golang.org/log/f1cfe209ebc8305edf967db289b2776db563b436)
[2022-05-20T23:05:38-bc2c85a-c3470ca/linux-loong64-3a5000](https://build.golang.org/log/f2016db24887242f47cc3637ac0b9c1c16e4db68)
[2022-05-18T15:15:29-5e4e11f-bc2e961/linux-loong64-3a5000](https://build.golang.org/log/25d427eb623c3228722b9b44d398cd500fb4e625)
[2022-05-02T18:38:26-af99c20/linux-loong64-3a5000](https://build.golang.org/log/c3ff0155810aed16ea8aad72935b1f8f5f8343a0)

(attn @golang/loong64)

**Comment by xen0n** [comment] 2022-05-28 00:57
Can't reproduce locally as well.

@golang/loong64, would you try reproducing in a fresh environment (you could use a Gentoo chroot) and latest kernel?

**Comment by limeidan** [comment] 2022-05-30 11:59
This is an occasional problem, sometimes running all.bash can reproduce it locally, but the cause has not been found out for the time being, need futher investigation.

**Comment by xen0n** [comment] 2022-05-30 12:14
> This is an occasional problem, sometimes running all.bash can reproduce it locally, but the cause has not been found out for the time being, need futher investigation. 

Can you try to somehow save a copy of the faulty executable next time this happens? Might be helpful for debugging.

**Comment by limeidan** [comment] 2022-06-02 13:08
>Can you try to somehow save a copy of the faulty executable next time this happens? Might be helpful for debugging.

FYI.  And we found that the file was malformed lost 16KB of data at its beginning.

[bad-bin-compile.tar.gz](https://github.com/golang/go/files/8824003/bad-bin-compile.tar.gz)

**Comment by xen0n** [comment] 2022-06-15 08:09
Update: problem may be pinpointed, it's likely due to some interesting race involving fallocate and/or mmap. The Loongson team should be working on this shortly, and I'll be helping.

**Comment by abner-chenc** [comment] 2022-06-15 11:44
On some linux/loong64 machines, an "exec format error" error occasionally  occurs when executing the make.bash or all.bash.  Check these executable  files with errors, it is found that the data of 16K(only one pagesize) at  the beginning of the file is  missing. The result of hexdump is as follows:
 
```
   1  0000000 0000 0000 0000 0000 0000 0000 0000 0000
   2  *
   3  0004000 0020 4c00 3d24 1c01 d084 02fc 2064 29c0
   4  0004010 9004 02c0 4064 29c0 4800 576a 0000 0014
   5  0004020 62d3 28c0 8e73 0012 1260 5c00 0025 0015
```
 
This problem is caused by the occasional loss of 16K data at the beginning  of the file after the link process calls the  syscall.Fallocate function for  the second time. However, not all machines can reproduce this error (the file system formats I tested include xfs, ext4, tmfs ).

**Comment by bcmills** [comment] 2023-02-03 20:23
No recent failures reported by `watchflakes`. @golang/loong64 — was this fixed on the builder, or by some mitigation in the compiler or linker, or is there more to do here?

**Comment by xen0n** [comment] 2023-02-04 00:52
> No recent failures reported by `watchflakes`. @golang/loong64 — was this fixed on the builder, or by some mitigation in the compiler or linker, or is there more to do here?

Hi, I've revisited this and it indeed seems to be [fixed by kernel people](https://lore.kernel.org/linux-mm/a5dac112-cf4b-7af-a33-f386e347fd38@google.com/) in v6.1 (it was a folio regression across the board from 5.17 to 6.0), thanks for this investigation, and IMO this issue could be closed as completed. Thanks for the triage.

**Closed** 2023-02-04 00:57 UTC
Labels: NeedsInvestigation, arch-loong64, compiler/runtime
