### ISSUE TITLE
x/tools/gopls: renaming package from "main" to something else produces "package <...>; expected main"

### ISSUE THREAD

**Issue by zikaeroh** [golang/go#36593] opened 2020-01-16 07:03 UTC
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

Made a `package main` file with:

```go
package main

func main() {
	var s someStruct
	_ = s.StringAbove()
	_ = s.StringBelow()
}

type someStruct struct {
	readyChan chan struct{}
}

func (s *someStruct) StringAbove() string {
	return "someStruct"
}


func (s *someStruct) ready() chan struct{} {
	return s.readyChan
}

func (s *someStruct) StringBelow() string {
	return "someStruct"
}
```

Then, replace the whole thing with:

```go
package what
```

As I was testing some other `gopls` thing that I wanted a `_test` for (and no `main`).

#### What did you expect to see?

Things work normally with a new package name.

#### What did you see instead?

An error on the `package` keyword: "package what; expected main"

Logs (at the end): https://gist.github.com/zikaeroh/333988d491995d2516ed768ac78f3d38

#### Build info

```
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.1.8-0.20200116062425-473961ec044c h1:1TIoDnmETx0ZptB3IkN+lN1z/gkfEtlCEjQmD51vhsM=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee h1:WG0RUwxtNT4qqaXX3DPA8zHFNm/D9xaBpxzHt1WcA/E=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20200116062425-473961ec044c h1:D0OxfnjPaEGt7AluXNompYUYGhoY3u6+bValgqfd1vE=
    golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898 h1:/atklqdjdhuosWIl6AIbOeHJjicWYPqR9bpxqxYG2pA=
    honnef.co/go/tools@v0.0.1-2019.2.3 h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```

#### Go info

```
go version go1.13.6 linux/amd64

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jake/.cache/go-build"
GOENV="/home/jake/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jake/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jake/testproj/what/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build747167430=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by zikaeroh** [comment] 2020-01-16 07:04
I should note that the issue seems to have gone away when I wrote more code in the file (and obviously, on restart).

**Comment by ridersofrohan** [comment] 2020-03-02 16:01
This is a duplicate of issue [#32149](https://github.com/golang/go/issues/32149)

**Comment by stamblerre** [comment] 2020-03-02 19:56
Duplicate of #32149

**Comment by stamblerre** [comment] 2020-03-02 19:57
Thanks for noticing that, @ridersofrohan! Closing in favor of other issue, which I've moved to the `gopls/v0.4.0` milestone.

**Closed by stamblerre** 2020-03-02 19:57 UTC
Labels: NeedsInvestigation, Tools, gopls
