### ISSUE TITLE
cmd/cgo: fails to parse object file generated by clang -flto

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#46295] opened 2021-05-20 20:01 UTC
On tip, on linux-amd64, in the misc/swig/callback directory, running this command

    CC=clang CGO_CFLAGS="-g -O2 -flto" CGO_LDFLAGS="-flto" go test -v

fails as follows:

```
# misc/swig/callback
cgo: cannot parse gcc output $WORK/b059//_cgo_.o as ELF, Mach-O, PE, XCOFF object
FAIL	misc/swig/callback [build failed]
```

At least when using clang, cgo has to disable `-flto` when it compiles the object, because cgo is unable to parse the byte code generated by clang.

**Comment by MrQubo** [comment] 2021-05-21 13:08
Same with gcc.

**Comment by MrQubo** [comment] 2021-05-21 13:12
Might be a duplicate of https://github.com/golang/go/issues/43505.

**Closed** 2021-06-01 19:59 UTC
Labels: NeedsFix
