### ISSUE TITLE
time.parse cann ot parse RFC3339 reference string (or any other I tried)

### ISSUE THREAD

**Issue by kscholty** [golang/go#68527] opened 2024-07-20 10:49 UTC
### Go version

go version 1.22.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/user/.cache/go-build'
GOENV='/home/user/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/user/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/user/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/user/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd6
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/user/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-a
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/user/Dokumente/devel/evcc/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
```

### What did you do?

```
t, err := time.Parse(time.RFC3339, time.RFC3339)
if err != nil {
   fmt.Print(err)
} else {
  fmt.Printf("Formatted %s", t.Format(time.RFC3339))
}
```

### What did you see happen?

`parsing time "2006-01-02T15:04:05Z07:00": extra text: "07:00"`

### What did you expect to see?

No error, correctly parsed value in t

Expected output:
`Formatted: 2006-01-02T15:04:05Z07:00`

**Comment by kscholty** [comment] 2024-07-20 10:51
Maybe related to #205555

**Comment by seankhliao** [comment] 2024-07-20 10:57
Duplicate of #9346

**Closed by seankhliao** 2024-07-20 10:57 UTC
