### ISSUE TITLE
proposal: inet: implement sctp protocol

### ISSUE THREAD

**Issue by drv1234** [golang/go#66847] opened 2024-04-16 07:43 UTC
### Proposal Details

hi,
sctp protocol is missing from the core protocols.
There is an project implementing it but it seems will never be fix this critical issue:
https://github.com/ishidawataru/sctp/issues/60

and the implementation does not fit into the golang standard "net" architecture.

Please consider it to implement it as a "supported protocol by default".
Thank you

**Comment by seankhliao** [comment] 2024-04-16 08:34
Duplicate of #22191

**Closed by seankhliao** 2024-04-16 08:34 UTC
Labels: Proposal
