### ISSUE TITLE
encoding/json Marshalled time location inconsistent in GMT

### ISSUE THREAD

**Issue by groob** [golang/go#17885] opened 2016-11-10 22:31 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.3 (but tried tip as well)

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/victor/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/02/k62z5c796fs5gm651jc610v80000gn/T/go-build475244754=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```
### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/gFDhc-65Ft

### What did you expect to see?

When using `json.Marshal` on a time value, I expected the a `myTime.Location()` to always be `Local` when the host timezone is set. 

### What did you see instead?

If my local time is set to GMT, I see `UTC` instead of `Local`. 

using `time.Parse()` as shown in the example seems to work correctly, but when the value is marshaled to/from JSON the output is inconsistent between timezone.

**Comment by groob** [comment] 2016-11-12 16:21
I tried `time.Parse` with `RFC3339` time format, which makes the above clearer: 

```
fmt.Println(time.Now().Format(time.RFC3339))
// Output in EST: 2016-11-12T11:12:37-05:00
// Output in PST: 2016-11-12T08:19:15-08:00
// Output in GMT: 2016-11-12T16:19:40Z
```
using time.Parse with `2016-11-12T16:19:40-00:00` prints `Local` correctly when in GMT.

**Comment by quentinmit** [comment] 2016-11-15 21:19
This is a dupe of #17875; Local and UTC are the same if your timezone is GMT, so encoding/json is working as intended. We make no guarantees about which location object is attached to times, only that a time that is `t.Equal` is returned.

**Closed by quentinmit** 2016-11-15 21:19 UTC
