### ISSUE TITLE
x/pkgsite: Adding syntax highlight support

### ISSUE THREAD

**Issue by laoshaw** [golang/go#54327] opened 2022-08-07 14:30 UTC
Golang is designed for beginner friendly, many many beginners like syntax highlight, in fact nearly all other languages(cppreference, rust, python, javascript,...) are having syntax highlight in their doc and websites, golang remains probably the only main stream language that insists its boring plain text for code contents. Some senior Go developers might dislike syntax highlight, but many of us can not live without it, just like the rest of nearly all other main languages. can you please at least make that an opt-in feature? Thank you.

### What is the URL of the page with the issue?

https://pkg.go.dev/
https://go.dev/tour/welcome/1
run godoc from command line to read doc

### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

### Screenshot

![image](https://user-images.githubusercontent.com/18351761/183295488-9ba005d5-5b75-45b1-9fcc-87a2a75b0daf.png)

### What did you do?

just read documents and use tours of go

### What did you expect to see?

all code snippets should be syntax highlighted

### What did you see instead?

it's plain text

**Comment by seankhliao** [comment] 2022-08-07 14:49
Duplicate of #52198

**Closed by seankhliao** 2022-08-07 14:49 UTC
Labels: pkgsite
