### ISSUE TITLE
cmd/compile: incorrect inlining of function swapping two funcs

### ISSUE THREAD

**Issue by fabe-xx** [golang/go#59108] opened 2023-03-18 07:08 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
It does with 1.19; not with 1.20.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\telic\AppData\Local\go-build
set GOENV=C:\Users\telic\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\telic\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\telic\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.7
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\F2\Texter\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\telic\AppData\Local\Temp\go-build2840717194=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

[See test in playground.](https://go.dev/play/p/NDxk79eBrAx?v=goprev)
By uncommenting the commented-out line in `test()` (introducing two blank variables) you can get the test to pass, presumably by preventing inlining.

### What did you expect to see?

Output "01", indicating first the first, then the second func getting called.

### What did you see instead?

Output "00", indicating the first func instead got called twice.

**Comment by Thoro** [comment] 2023-03-18 10:30
According to the decompilation at https://godbolt.org/z/hacWM8Ejd

The bug is introduced with 1.16, 1.15 still has both functions, starting with 1.16 to 1.19 the inlined b function is optimized away.

**Comment by Thoro** [comment] 2023-03-18 12:22
Fixed for Go1.20 here: 54632

**Comment by seankhliao** [comment] 2023-03-18 12:29
Duplicate of #54632

**Closed by seankhliao** 2023-03-18 12:29 UTC
Labels: compiler/runtime

**Comment by ncruces** [comment] 2023-03-18 17:38
This reproduces against 1.19.
Shouldn't the fix be backported?

**Comment by christophberger** [comment] 2023-03-20 08:50
Curious: Is a fix for Go 1.19.x planned?

**Comment by ianlancetaylor** [comment] 2023-03-20 22:19
@gopherbot Please open backport issue for 1.19

Reportedly this issue occurs in 1.19 as well.
