### ISSUE TITLE
x/tools/internal/lsp: TestLSP/GOPATH failure with "race detected during execution of test"

### ISSUE THREAD

**Issue by dmitshur** [golang/go#54276] opened 2022-08-04 22:58 UTC
```
2022/08/02 19:20:54 New session
	create_session=1
2022/08/02 19:20:56 go/packages.Load #1
[...]
==================
WARNING: DATA RACE
Read at 0x00c0086205a0 by goroutine 34461:
  golang.org/x/tools/internal/lsp/cache.(*snapshot).load()
      /tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/cache/load.go:144 +0x11a6
  golang.org/x/tools/internal/lsp/cache.(*snapshot).loadWorkspace()
      /tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/cache/view.go:710 +0x38b
  golang.org/x/tools/internal/lsp/cache.(*snapshot).initialize()
      /tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/cache/view.go:645 +0x229
  golang.org/x/tools/internal/lsp/cache.(*Session).createView.func4()
      /tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/cache/session.go:268 +0x8d

Previous write at 0x00c0086205a0 by goroutine 34426:
  golang.org/x/tools/internal/lsp/cache.(*View).SetOptions()
[...]
2022/08/02 19:22:47 go/packages.Load #30
	snapshot=1
	package="command-line-arguments"
	files=[/tmp/workdir/go/src/builtin/builtin.go]
2022/08/02 19:22:47 go/packages.Load #30: updating metadata for 1 packages
2022/08/02 19:22:49 no signature help: no signature help within a string literal
	position={49 5}
2022/08/02 19:22:49 no signature help: no signature help within a function declaration
	position={76 2}
--- FAIL: TestLSP (119.09s)
    --- FAIL: TestLSP/GOPATH (48.73s)
        testing.go:1319: race detected during execution of test
    testing.go:1319: race detected during execution of test
FAIL
FAIL	golang.org/x/tools/internal/lsp	119.292s
```

[2022-08-02T18:52:36-0d04f65-4345620/freebsd-amd64-race](https://build.golang.org/log/927c2103551010f213d6fbd0e8afa80897bca0bb)

**Comment by findleyr** [comment] 2022-08-05 13:12
Dupe of #54214.

**Closed by findleyr** 2022-08-05 13:12 UTC
Labels: NeedsInvestigation, gopls, Tools

**Comment by dmitshur** [comment] 2022-08-05 14:31
Thanks and sorry I missed it. I changed the prefix in the title of [#54214](https://github.com/golang/go/issues/54214#event-7136329449) to follow the usual [convention](https://github.com/golang/tools#contributing) so it'll be easier to find.

**Comment by findleyr** [comment] 2022-08-05 14:34
Thanks, don't know what I was thinking with that issue title! (how many issues have I filed...?!)
