### ISSUE TITLE
go1.11beta3 test fails when using a different module for testing

### ISSUE THREAD

**Issue by surajbarkale** [golang/go#26910] opened 2018-08-10 01:09 UTC
### What version of Go are you using (`go version`)?
go version go1.11beta3 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sbark/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sbark/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g3/75bj1c295mj9qykv045hzxqnwcwnf4/T/go-build557749133=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
Create following files in a directory:
1. go.mod
```
module example.com/gomod
```
2. modlib.go
```
package gomod

func Useful() string {
	return "useful"
}
```
3. modlib_test.go
```
package gomod_test

import (
	"testing"

	"example.com/gomod"
)

func TestUseful(t *testing.T) {
	want := "useful"
	if got := gomod.Useful(); got != want {
		t.Errorf("Useful() = %v, want %v", got, want)
	}
}
```
4. Execute tests using `go test -v`

### What did you expect to see?
```
$ go1.11beta2 test -v
=== RUN   TestUseful
--- PASS: TestUseful (0.00s)
PASS
ok  	example.com/gomod	0.005s
```

### What did you see instead?
```
$ go1.11beta3 test -v
build example.com/gomod_test: cannot find module for path example.com/gomod_test
```

**Comment by bcmills** [comment] 2018-08-10 02:52
Similar setup to the issues reported in #26722 and #26279, so closing as a likely duplicate of those.

Please let us know if this isn't fixed at head.

**Closed by bcmills** 2018-08-10 02:52 UTC
