### ISSUE TITLE
cmd/vet: false positive on +build comment if within a string

### ISSUE THREAD

**Issue by andybons** [golang/go#24080] opened 2018-02-23 19:25 UTC
go version go1.10 linux/amd64

When running `go vet` on the following code, it complains that the +build comment is in the wrong place:

```go
package main

const prog = `
// +build foo
package main

func main() {}
`
```

**Comment by robpike** [comment] 2018-02-23 21:38
It's tricky and maybe hard to fix but consider it.
The issue is that vet is _looking_ for things in the wrong places, so it can't use the parser,  yet without parsing the code it's easy to mislead the scanner.

**Comment by andybons** [comment] 2018-02-23 22:39
Thanks, Rob.

**Comment by 0xmohit** [comment] 2018-02-24 13:42
This was reported earlier here: https://github.com/golang/go/issues/13533

**Comment by robpike** [comment] 2018-02-24 21:09
Duplicate of #13533.

That one was closed as too hard to fix for the payoff, which is fair. Closing.

**Closed by robpike** 2018-02-24 21:09 UTC
