### ISSUE TITLE
cmd/gofmt: change in exponent literal notation from 1.12 to 1.13

### ISSUE THREAD

**Issue by liggitt** [golang/go#32580] opened 2019-06-12 19:21 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version devel +6a4b1f745d Wed Jun 12 17:10:31 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/liggitt/Library/Caches/go-build"
GOENV="/Users/liggitt/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/liggitt/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/liggitt/git/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/liggitt/git/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h8/3dzrjpfj76d93vbhc5f2r8tw00kjgb/T/go-build371862376=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Ran `go fmt` on 1.12.
Ran `go fmt` on 1.13.

### What did you expect to see?

Results to be consistent.

### What did you see instead?

Exponent numbers were normalized differently:

1.12: `100E6`
1.13: `100e6`

**Comment by ianlancetaylor** [comment] 2019-06-13 00:08
I think this was an intentional change.

CC @griesemer

**Comment by liggitt** [comment] 2019-06-13 00:15
any rationale or reference for the change? dueling gofmt across releases makes for unhappy CI and contributors. If the benefit is significant, changes make sense, but I'm not seeing it here.

**Comment by griesemer** [comment] 2019-06-13 00:15
Correct. This was done on purpose. We do the same for prefixes, e.g. `0X123` becomes `0x123`. The reason is that now that we allow `0O123`, the form 0o123` is easier to read. We simply make the change everywhere, and didn't stop with exponents either (but we leave hexadecimal digits alone).

Closing as working as intended.

**Closed by griesemer** 2019-06-13 00:15 UTC

**Comment by griesemer** [comment] 2019-06-13 00:21
@liggitt My apologies. With the proliferation of new number formats that are permitted, we (I mean several people in the Go team) felt that it would be good for `gofmt` to enforce a preferred, uniform style of capitalization.

I understand the unhappy CI - but that would be the case for any `gofmt` change, woulnd't it? If there's anything more "substantial" (I don't mean to disqualify your complaint) where this is causing problems, please feel free to re-open.

**Comment by liggitt** [comment] 2019-06-13 00:43
> that would be the case for any gofmt change, woulnd't it?

Yes, though usually the cost is easier to bear given the improved readability. The benefit here wasn't as obvious (we only had exponents in our codebase)

Digging into the change, it looks like this is normalizing where no normalization previously occurred, so the output of 1.13 will still be acceptable to 1.12, which reduces my concern (versions of gofmt flipping opinions about the "right" formatting makes backports to branches built with different go versions painful)

**Comment by griesemer** [comment] 2019-06-13 00:50
Correct. The new `gofmt` is now stricter. It has not changed its opinion.
