### ISSUE TITLE
go get -u to be for a specific revision of a repository?

### ISSUE THREAD

**Issue by wingZero21** [golang/go#22417] opened 2017-10-24 09:30 UTC
### What version of Go are you using (`go version`)?
1.9.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Linux Centos 6.7

This is a question in regards to getting a specific revision of a repository using the go get -u command. There is some reference to go-getter (https://github.com/joewalnes/go-getter) which will update a reference for a local package, however I am not seeing anyway to generate the bin from the go-getter command as this looks to just be updating the source by performing a ```git checkout revisionNO```.

Is there anyway that the go get -u command can be used to pull down a specific revision of a github repository? This would allow for versioning of the external repo's, alternatively if this is not possible is there anyway to compile the bin by downloading the specific revision of the github repository and generated the bin locally.

**Comment by ALTree** [comment] 2017-10-24 09:49
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

> This would allow for versioning of the external repo's

Note that a Go dependency management tool is in development at github.com/golang/dep; it's possible that in future it'll be integrated in the `go` command, but even now you can use it to manage dependencies.

Closing, since this is not a bug.

**Closed by ALTree** 2017-10-24 09:49 UTC
