### ISSUE TITLE
spec: incorrect requirement for the embedded field

### ISSUE THREAD

**Issue by leabit** [golang/go#69460] opened 2024-09-13 23:18 UTC
### What is the URL of the page with the issue?

https://go.dev/ref/spec#Struct_types

### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

### What did you do?

I came across a [discussion](https://github.com/golang/go/issues/66540) about the incorrect terminology used in the specification when referring to promoted methods of the alias to unnamed type, and the [changes](https://go-review.googlesource.com/c/go/+/603958) that were made to address this issue. However, there remains another related problem, and I believe its resolution should also be considered as part of the overall solution. The specification states the following:

> An embedded field must be specified as a **type name T** or as a pointer to a non-interface type name *T, and **T itself may not be a pointer type.**

If the **type name** denotes only defined types everything would be fine, however, it also denotes type alias to the unnamed (undefined) types.

### What did you see happen?

So according to the specification, the following code is invalid since type name `T` is a pointer type:

```
package main

type T = *int

type S struct {
	T
}

func main() {}
```

However, it compiles.

### What did you expect to see?

To not compile (actually to compile, but to correct the specification to properly address this as well).

**Comment by leabit** [comment] 2024-09-13 23:23
Al right, it looks like the same issue was already mentioned in #22005, however, nothing has been done for 7 years

**Comment by seankhliao** [comment] 2024-09-13 23:47
Duplicate of #22005

**Closed by seankhliao** 2024-09-13 23:47 UTC
Labels: pkgsite
