### ISSUE TITLE
Add support for foldingRangeProvider capability

### ISSUE THREAD

**Issue by hartzell** [golang/go#33922] opened 2019-08-29 00:50 UTC
I'm not sure if there's a roadmap/todo list somewhere, but I believe that gopls does not support the foldingRangerProvider capability.

### What version of Go are you using (`go version`)?

And also gopls version...

<pre>
(alice)[17:37:18]src>>go version
go version go1.12.6 darwin/amd64
(alice)[17:41:50]src>>gopls version
golang.org/x/tools/gopls v0.1.2
    golang.org/x/tools/gopls@v0.1.3 h1:CB5ECiPysqZrwxcyRjN+exyZpY0gODTZvNiqQi3lpeo=
</pre>

And also with

<pre>
(alice)[17:44:13]src>>gopls version
golang.org/x/tools/gopls v0.1.3
    golang.org/x/tools/gopls@v0.1.4-0.20190828213141-aed303cbaa74 h1:91EIZYhqSNmBQXxY3ejrrGmRvO4f0P1+q4GmaxLwRw8=
</pre>

### Does this issue reproduce with the latest release?

Yes, both `@latest` and `@master`.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
(alice)[17:44:42]src>>go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hartzell/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hartzell/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.6/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/hartzell/tmp/ft-go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f7/fcb363190nz0jbypndp3nj_m0000gn/T/go-build248990039=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Set up emacs' go-mode to use `lsp-mode` and `lsp-ui-mode` (working as intended), set up `lsp-mode` to invoke `lsp-origami-mode`, and set up `lsp-origami` to set the buffer into `origami-mode`.  Origami-mode is a folding mode that has its own parsers, `lsp-origami` sets it up to use the LSP server instead.

### What did you expect to see?

Folding of the node in question.  This works when I'm using Origami's built-in parsers

### What did you see instead?

```
Capability not supported by the language server: "foldingRangeProvider"
```

**Comment by stamblerre** [comment] 2019-08-29 05:22
Duplicate of https://github.com/golang/go/issues/32987

Closing as a duplicate.

**Closed by stamblerre** 2019-08-29 05:22 UTC
