### ISSUE TITLE
unsafe permissions on bin folder lead to phantom dll hijacking

### ISSUE THREAD

**Issue by lochv** [golang/go#36123] opened 2019-12-13 09:03 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.5
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\vm\AppData\Local\go-build
set GOENV=C:\Users\vm\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\vm\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\root\AppData\Local\Temp\go-build956336706=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
Install golang on Windows 10 with *https://dl.google.com/go/go1.13.5.windows-amd64.msi*, the program auto add *C:\Go\bin* to $PATH. 

### What did you expect to see?
All users can only have permissions: read & execute

### What did you see instead?
Other users can write to *C:\Go\bin* lead to phantom dll hijacking *https://resources.infosecinstitute.com/dll-hijacking-attacks-revisited/#gref*

**Comment by ALTree** [comment] 2019-12-13 09:16
Thanks for the report. This is a duplicate of  #35575, so I'm closing this thread in favour of the older one. Feel free to subscribe to the other thread.

**Closed by ALTree** 2019-12-13 09:16 UTC
