### ISSUE TITLE
encoding/json: json.RawMessage does not works correctly

### ISSUE THREAD

**Issue by gromas** [golang/go#35992] opened 2019-12-05 12:15 UTC
I want to unmarshal JSON to different struct types and I write:

```
	bytes := []byte(`
		{"__type":"instance.started","InstanceId":"a9ff34dd-d20b-4887-99d6-f2f3a68f86a5"}
	`)
	var envelope struct {
		Type string `json:"__type"`
		Json *json.RawMessage
	}

        _ = json.Unmarshal(bytes, &envelope)

	fmt.Println(envelope.Type)
	fmt.Println(envelope.Json)
```

I get empty envelope.Json but must be an byte array (json.RawMessage). 

repro:
https://play.golang.org/p/m6wd44R35FZ

**Comment by ALTree** [comment] 2019-12-05 12:30
Hi, 

matching is based on field names and annotations. 

From the [Json and Go post](https://blog.golang.org/json-and-go):

> For a given JSON key "Foo", Unmarshal will look through the destination struct's fields to find (in order of preference):
>
> - An exported field with a tag of "Foo" (see the Go spec for more on struct tags),
> - An exported field named "Foo", or
> - An exported field named "FOO" or "FoO" or some other case-insensitive match of "Foo".

So you need to change your struct to either

```
	var envelope struct {
		Type string `json:"__type"`
		InstanceId *json.RawMessage
	}
```
or
```
	var envelope struct {
		Type string `json:"__type"`
		Json *json.RawMessage `json:"InstanceId"`
	}
```

Closing here, since this is not a bug.

**Comment by gromas** [comment] 2019-12-05 12:36
Hey! Thank you for answer. InstanceId is sample field. I have over 100 different message types and want to reflect json to different golang structs (I use switch evnvelope.Type ...)

**Comment by ALTree** [comment] 2019-12-05 12:42
Then please post a reproducer that doesn't contain other mistakes that will cause the field to be empty.

**Comment by gromas** [comment] 2019-12-05 13:03
Same problem with marshaling. I marshal {Type, __some_message__} data and get __some_message__ only without __type ))

https://play.golang.org/p/SsgQmtq2yP0

**Comment by toothrot** [comment] 2019-12-05 18:34
Hi @gromas,

Referring to your first example:
```
	bytes := []byte(`
		{"__type":"instance.started","InstanceId":"a9ff34dd-d20b-4887-99d6-f2f3a68f86a5"}
	`)
	
	var envelope struct {
		Type string `json:"__type"`
		Json *json.RawMessage
	}
```

What exactly do you expect to appear in the `Json` struct field?

**Comment by seankhliao** [comment] 2019-12-05 19:04
@gromas 
The go struct structure has to match the json structure, you cannot just dump all the unrecognized fields into a `json.RawMessage`
What you can do is unmarshal twice, once to find the type, second time into a known struct. `json.RawMessage` is for making this more convenient in more deeply nested structs

Your second example you are embedding a `json.RawMessage` whose `MarshalJSON`/`UnmarshalJSON` is being promoted to envelope and overriding the marshal process

**Comment by toothrot** [comment] 2019-12-09 18:54
Thanks @seankhliao. I'm going to close this issue, as it is not clear that this is a bug. @gromas, please see one of the resources on https://golang.org/wiki/Questions for further help using the `encoding/json` package.

**Closed by toothrot** 2019-12-09 18:54 UTC
