### ISSUE TITLE
sync: Map.Store() crash with fatal error: sync: unlock of unlocked mutex

### ISSUE THREAD

**Issue by amezghal** [golang/go#26480] opened 2018-07-19 16:41 UTC
Hi,

For some reason our service crashes with this unrecoverable error:

```
 fatal error: sync: unlock of unlocked mutex
goroutine 866557 [running]: 
runtime.throw(0xc0236c, 0x1e)
	/opt/go1.10.3.linux-amd64/src/runtime/panic.go:616 +0x81 fp=0xc44a9d65c0 sp=0xc44a9d65a0 pc=0x42b191 
sync.throw(0xc0236c, 0x1e)
	/opt/go1.10.3.linux-amd64/src/runtime/panic.go:605 +0x35 fp=0xc44a9d65e0 sp=0xc44a9d65c0 pc=0x42b105 
sync.(*Mutex).Unlock(0xc42522c050)
	/opt/go1.10.3.linux-amd64/src/sync/mutex.go:184 +0xc2 fp=0xc44a9d6608 sp=0xc44a9d65e0 pc=0x46c652 
sync.(*Map).Store(0xc42522c050, 0xabd0c0, 0xc4374e15a0, 0xbabe00, 0xc4305738c0) 
	/opt/go1.10.3.linux-amd64/src/sync/map.go:162
```
we are using sync.Map as intended (filling the map from multiple go routines).

it's very random, and i can't force the crash,  but it happens many times per day.

Thanks

**Comment by randall77** [comment] 2018-07-19 16:53
I can't see how that line could be unlocking an unlocked map.  It is dominated by the lock call.

Any chance you're copying the `Map`?  That might explain your crash.
```
A Map must not be copied after first use.
```

Is there any way you can share the code so we can reproduce this crash?

**Comment by amezghal** [comment] 2018-07-19 17:04
Hi, @randall77 

i am aware of the copying map issue, and i confirm we are not copying the map.

i will provide a mock code

> package shared

import "sync"

type Stats struct {
	items sync.Map
}

type item struct {
	Id    string  `json:"id"`
	Value float64 `json:"value"`
}

func NewStats() *Stats {
	instance := Stats{}
	instance.items = sync.Map{}
	return &Stats{}
}

func (ss *Stats) Add(key string, value item) {
	ss.items.Store(key, value)
}

func (ss *Stats) Flush() {
	ss.items = sync.Map{}
}

what we do is during start up, we create an instance and make it available globally 

> global.StatsManager := NewStats()

and we have a ticker that is called every 10minutes (we collect data and adapat/store in elasticSearch)
Once done, we call the Flush Method the re initiate.

we do not copy the instance,

**Comment by amezghal** [comment] 2018-07-19 17:09
Unless the Flush() method is the issue ?

what are doing is trying to restart over once data is on elastic search,

**Comment by randall77** [comment] 2018-07-19 18:10
Yes, I think `Flush` is the issue.  If there are outstanding map operations currently in progress on `global.StatsManager.items`, you can't do `global.StatsManager.items = sync.Map{}`.  Although technically that doesn't violate the rule "don't copy a map before first use" because the map you're copying hasn't been used yet.  But you're copying onto an in-use `Map`, which is also bad.  It may be worth adding something to the doc, although it seems pretty obvious that's unsafe if you think about it long enough.  @bcmills

**Comment by randall77** [comment] 2018-07-19 18:11
Speaking of which, the race detector should have caught this bug.  Have you tried running with the race detector on?

**Comment by bcmills** [comment] 2018-07-19 18:29
> It may be worth adding something to the doc, although it seems pretty obvious that's unsafe if you think about it long enough.

We have a test that `sync.Map` triggers the `vet` copylock check. If `go vet` didn't catch the assignment, that's arguably a bug in `vet`.
https://github.com/golang/go/blob/9092511cf795dd82713cd328403a106fc3e6870c/src/cmd/vet/testdata/copylock_func.go#L14

**Comment by randall77** [comment] 2018-07-19 19:53
@bcmills I think the vet copylock check isn't triggered when the RHS is a composite literal.  Presumably because copying a zero lock is allowed.
It's the overwriting that's the problem here, not the copying itself.

**Comment by agnivade** [comment] 2018-07-20 04:08
@amezghal - Do you get any errors under the race detector ?

**Comment by amezghal** [comment] 2018-07-25 15:45
Once i have updated the Refresh method i no longer get this error,

**Comment by randall77** [comment] 2018-07-25 20:22
Ok, I'll close this issue then.
(Is `Refresh` the same as `Flush`?)

**Closed by randall77** 2018-07-25 20:22 UTC
Labels: NeedsInvestigation, WaitingForInfo

**Comment by amezghal** [comment] 2018-07-26 09:57
Yes `Refresh` 
re init the sync.Map while it was being excessively updated without synchronisation from other go-routines was the issue.

**Comment by davecheney** [comment] 2018-07-26 10:33
Hello,

Did the race detector spot this problem?

Thanks

**Comment by amezghal** [comment] 2018-07-26 11:01
@davecheney 
I restored the old code and run it with the -race, 

yes the racedetector is reporting the data race, 

thks

**Comment by davecheney** [comment] 2018-07-26 11:04
Thanks for confirming.
