### ISSUE TITLE
go test -args Tips flag provided but not defined: -test.timeout

### ISSUE THREAD

**Issue by lanfengye2008** [golang/go#35444] opened 2019-11-08 00:54 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.13.4 windows/amd64 

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\zibin\AppData\Local\go-build
set GOENV=C:\Users\zibin\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=e:\go
set GOPRIVATE=
set GOPROXY=https://goproxy.io
set GOROOT=d:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=d:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\goProject\hpyx\hpyxBase\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\zibin\AppData\Local\Temp\go-build141868538=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

execute  

go test -args -c e:\go\bin\config.ini

### What did you expect to see?

normal operation go test Result

### What did you see instead?
flag provided but not defined: -test.timeout
Usage of C:\Users\zibin\AppData\Local\Temp\go-build018891410\b001\data.test.exe:
  -config string
        配置文件路径 (default "configBase.ini")
  -log string
        日志文件路径 (default "logs\\logBase.log")
exit status 2
FAIL    hpyx/hpyxBase/data      0.051s

**Comment by dmitshur** [comment] 2019-11-08 01:38
The Go 1.13 release notes mention a change that affects the `testing` package at https://golang.org/doc/go1.13#testing:

<blockquote>Testing flags are now registered in the new <a href="/pkg/testing/#Init"><code>Init</code></a> function, which is invoked by the generated <code>main</code> function for the test. As a result, testing flags are now only registered when running a test binary, and packages that call <code>flag.Parse</code> during package initialization may cause tests to fail.</blockquote>

Closing as there isn't something that needs to be done here. It's also a duplicate of #31859.

**Closed by dmitshur** 2019-11-08 01:38 UTC

**Comment by lanfengye2008** [comment] 2019-12-03 07:01
There are still problems

**Comment by ianlancetaylor** [comment] 2019-12-03 15:27
@lanfengye2008 We can't help you if you don't tell us what is wrong.

**Comment by gonejack** [comment] 2020-03-12 10:29
Don't call flag.Parse() inside you func init()s, this is the solution I found.

**Comment by lanfengye2008** [comment] 2020-03-13 01:09
Thank you very much. I'll test it later
