### ISSUE TITLE
cmd/link: couldn't uses ldflags "-X" on custom type name alias to string: cannot set with -X: not a var of type string

### ISSUE THREAD

**Issue by zhuah** [golang/go#44985] opened 2021-03-13 10:02 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zhuah/Library/Caches/go-build"
GOENV="/Users/zhuah/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zhuah/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zhuah/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/gotip/stable"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/gotip/stable/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8n/mb3y_4bj1xv4q9sdmgjqdx_c0000gn/T/go-build1446698321=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I  defines a variable with custom type name aliased to string
```Go
type ID string

var id ID

func (v ID) Prefix() string { return "xxxx" }
func (v ID) Suffix() string { return "xxxx" }
```
and go build with `-ldflags="-X pkg.id=aaa.bbb"`.

### What did you see instead?
go linker reports error: cannot set with -X: not a var of type string.

the `ID` type may contains complex format, It would be great if the linker supports custom type name, 
so i could define methods on it and get type safety.

currently, i must defines the methods as global functions or create a new variable to wrap the linker variable.
```Go
var linkID string
var id = ID(linkID)
```

**Comment by cherrymui** [comment] 2021-03-15 17:08
Yes, the linker's `-X` flag is only for the built-in string type. As you posted, there is a simple workaround. Closing as work as intended. Thanks.

**Closed by cherrymui** 2021-03-15 17:08 UTC
