### ISSUE TITLE
x/crypto: missing git tags with proper version semantics (vX.X.X)

### ISSUE THREAD

**Issue by qeubar** [golang/go#46580] opened 2021-06-04 21:58 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version 1.16.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vagrant/.cache/go-build"
GOENV="/home/vagrant/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/vagrant/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/vagrant/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/golang1.16/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/golang1.16/lib/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="1.16.4"
GCCGO="gccgo"
AR="ar"
CC="/opt/gcc8/bin/gcc8"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3330331572=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Using the `golang.org/x/crypto` pkg and noticed that it doesn't use the standard Go Modules versioning. Ie, the repository does not have any git tags. 

### What did you expect to see?
Proper git tags (vX.X.X) on `golang.org/x/crypto` so one can easily identify which version of the pkg they are using.

### What did you see instead?
`golang.org/x/crypto` was updated to have a `go.mod` file but never went the full path of adding git tags with proper version semantics.

**Comment by seankhliao** [comment] 2021-06-04 22:17
Duplicate of #21324

**Closed by seankhliao** 2021-06-04 22:17 UTC
