### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by uguremirmustafa** [golang/go#59808] opened 2023-04-24 17:15 UTC
### What is the URL of the page with the issue?
 
 https://go.dev/doc/tutorial/random-greeting
 
### What is your user agent?
 

 
 [Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
### Screenshot
 

 
 
![image](https://user-images.githubusercontent.com/51749393/234067997-5755a1a4-8276-4790-ab96-70b9b2935b30.png)
![image](https://user-images.githubusercontent.com/51749393/234068590-46f65b2b-3d47-4968-a512-1305bd05ca96.png)

 
### What did you expect to see?
 
 I expect to see non-deprecated examples.
 
### What did you see instead?

The example code on the get started guide introduces deprecated code: 

> rand.Seed has been deprecated since Go 1.20 and an alternative has been available since Go 1.0: Programs that call Seed and then expect a specific sequence of results from the global random source (using functions such as Int) can be broken when a dependency changes how much it consumes from the global random source. To avoid such breakages, programs that need a specific result sequence should use NewRand(NewSource(seed)) to obtain a random generator that other packages cannot access.  (SA1019)go-staticcheck

**Comment by seankhliao** [comment] 2023-04-24 17:22
Duplicate of #58958

**Closed by seankhliao** 2023-04-24 17:22 UTC
Labels: website
