### ISSUE TITLE
runtime: running cmd.exec within goroutine sometimes leaves process with 100% CPU

### ISSUE THREAD

**Issue by ostrowr** [golang/go#53863] opened 2022-07-14 05:34 UTC
### What version of Go are you using (`go version`)?
Reproducible on at least 1.18.1 and 1.18.4 on Apple Silicon (M1)

<pre>
go version go1.18.1 darwin/arm64
go version go1.18.4 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/robbie/Library/Caches/go-build"
GOENV="/Users/robbie/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/robbie/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/robbie/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.18.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.18.4/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/my/x46mws81707gx7sxgsjcwc2w0000gn/T/go-build881887791=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
See the repro repo [here](https://github.com/ostrowr/go-init-cpu-hog) for a few scripts that might help you reproduce the issue.

1. Build the below program – `go build -o repro main.go`
2. Run `repro` a bunch of times at once – e.g. `for i in $(seq 500); do "./repro" &; done`
3. run `ps aux | grep repro`
4. Notice that some small percentage of the time, there are leftover processes either called `repro` or `(repro)` that continue to run and hog 100% CPU.

<img width="940" alt="Screen Shot 2022-07-13 at 10 35 38 PM" src="https://user-images.githubusercontent.com/3237869/178907504-f85683d4-8718-4728-96cd-7538d4dea305.png">

This is the smallest reproduction I can find but haven't been able to diagnose what this process is actually doing. `kill -ABRT` is ignored; the only way I can get rid of these hanging processes is with a `kill -9`.

No idea ~if this has to do with running a goroutine in an `init` function and~ whether this is replicable without running `exec.Command` ~or whether this is an `exec.Command` bug independent of `init` semantics.~

```
package main

import (
	"math/rand"
	"os/exec"
	"time"
)

func main() {
	go func() {
		exec.Command("echo").Run()
	}()
	time.Sleep(time.Duration(rand.Intn(20)) * time.Millisecond)
}

```

<details>
  <summary>Old reproduction</summary>
  
```
package main

import (
	"math/rand"
	"os/exec"
	"time"
)

func init() {
	go func() {
		exec.Command("echo").Run() // doesn't have to be `echo`; reproduces with other commands
	}()
}

func main() {
	time.Sleep(time.Duration(rand.Intn(20)) * time.Millisecond)
}
```
</details>

### What did you expect to see?
The process to exit and not take up much CPU

### What did you see instead?
A small percentage of the time, the process remains, either with its own name or its name in parentheses in the process table, hanging and taking up 100% CPU.

**Comment by ostrowr** [comment] 2022-07-14 16:53
> Just to be totally clear, does your reproducer still work if you get rid of any of these things? (Not init, not in a new goroutine at init, not exec.Command?)

This is the smallest repro I could find (i.e. I haven't managed reproduced by deleting any of these things, but it's super nondeterministic so I am not 100% confident that this is actually the minimal repro.)

Haven't been able to get a core dump on lldb/gdb yet; @allanbreyes has been investigating as well.

**Comment by prattmic** [comment] 2022-07-14 18:08
All of this sounds a lot like an issue in the kernel where zombie processes are getting stuck attempting to clean up / exit.

However, it is not at all clear what is special about this Go program that would trigger this. My best guess would be some kind of race between the parent process exiting and the fork+exec of the child.

Does this reproduce if you move the goroutine creation into main?

**Comment by ostrowr** [comment] 2022-07-14 19:03
Interestingly, I haven't been able to reproduce this when running the program many times in a row serially. This doesn't mean it doesn't reproduce that way, but might indicate that there is some sort of race condition in the kernel that doesn't clean up these zombie processes properly when it tries to do a lot at once. 

I.e. running this usually can sometimes reproduce:

`for i in $(seq 500); do "./repro" &; done`

But 

`while true; do "./repro"; done`

never seems to (so far).

**Comment by prattmic** [comment] 2022-07-14 19:55
Ah, great. There is little difference between the last init function and the start of main, so it is good to know that it isn't related.

A few more things to try:

1. Eliminate the race between exec and exit to see if the problem goes away. I'm thinking:

```go
package main

import (
	"math/rand"
	"os/exec"
	"time"
)

func main() {
	c := make(chan struct{}, 1)
	go func() {
		exec.Command("echo").Run()
		c <- struct{}{}
	}()
	time.Sleep(time.Duration(rand.Intn(20)) * time.Millisecond)
	<-c
}
```

2. Try recreating this as a C program with a background thread doing fork+exec and the main thread doing random sleep + exit.

**Comment by ostrowr** [comment] 2022-07-14 20:00
We'll try both of those things when we get a chance. In the meantime, I've narrowed this further: 

```
package main

import (
	"math/rand"
	"os"
	"time"
)

func main() {
	go func() {
		os.StartProcess("echo", []string{}, &os.ProcAttr{})
	}()
	time.Sleep(time.Duration(rand.Intn(20)) * time.Millisecond)
}
```

replicates. I'm feeling like it's unlikely that this is a go bug, but as you worked around a macos bug in https://github.com/golang/go/issues/41702 it might be worth trying to work around this one as well once we get to the root of it.

**Comment by ostrowr** [comment] 2022-07-14 22:15
Confirmed replication in C:

```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <pthread.h>


void *forking_thread(void* arg)
{
    int pid = fork();
    if (pid == 0) execl("/bin/echo", NULL);
    return NULL;
}

int main()
{
    pthread_t thread_id;
    pthread_create(&thread_id, NULL, forking_thread, NULL);
    usleep(20 * 1000);
    exit(0);
}
```

So, this is clearly not a Go bug. Feel free to close this, but if you have ideas w.r.t. a workaround as above, I'm happy to try to help.

Any idea where people have had success reporting macos kernel bugs in the past? Doesn't seem like the other thread got much traction.

**Comment by prattmic** [comment] 2022-07-15 17:38
We do have a lock taken around exec and thread creation to protect against a Linux kernel bug (#19546). As a workaround for this, we could perhaps take this lock prior to exit.

You could give this a try by calling `execLock.rlock()` prior to exit [here](https://cs.opensource.google/go/go/+/master:src/runtime/proc.go;l=272;drc=dc00aed6de101700fd02b30f93789b9e9e1fe9a1;bpv=1;bpt=1) (note that this is only exit when returning from main. os.Exit is a separate path).

**Comment by cherrymui** [comment] 2022-07-19 22:10
What version of macOS are you running on?.

I haven't been able to reproduce it locally. For the C reproducer, how many iterations does it usually take to have a hanging process?

Thanks.

**Comment by ostrowr** [comment] 2022-07-19 23:30
> What version of macOS are you running on?.
> 

12.4, with an M1 Max chip.

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,2
  Chip:	Apple M1 Max
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	32 GB
  System Firmware Version:	7459.121.3
  OS Loader Version:	7459.121.3
```

> I haven't been able to reproduce it locally. For the C reproducer, how many iterations does it usually take to have a hanging process?

Anecdotally it depends on CPU load, but I can consistently get a go repro in under a minute by running the scripts from [here](https://github.com/ostrowr/m1-cpu-hog)  

```
while true; do ./test_race_go; done
```

C repros are less predictable, but that's probably because I didn't include the random jitter; I'll see if adding the randomness helps.

```
while true; do ./test_race_c; done
```

takes at most a couple of minutes to leave a process at 100%.

**Comment by cherrymui** [comment] 2022-07-20 23:49
Thanks @ostrowr ! I can also reproduce on an Intel Mac with macOS 12.4, both the Go and the C version. I'll forward it to Apple.

**Comment by ostrowr** [comment] 2022-07-21 05:14
Great, thanks! For posterity, I submitted this to Apple on the 14th; feedback ID FB10691471 if you want to reference it. 

Haven't taken a look at a workaround in go since it'll likely take me a while to get a dev environment set up but I'll try to make some time this weekend

**Comment by cherrymui** [comment] 2023-01-13 23:59
I couldn't reproduce now with macOS 12.6.4 and 13.1. Maybe it is fixed now?

**Comment by ostrowr** [comment] 2023-01-21 01:43
I haven't been able to reproduce on 13.1 either, but only tried for about 10 runs of ./test_race_go. 

Seems like possibly fixed!

Never did get a response on my Apple feedback.

**Comment by cherrymui** [comment] 2023-06-02 22:08
Thanks. Let's call it fixed. If it is not we can reopen.

**Closed by cherrymui** 2023-06-02 22:08 UTC
Labels: OS-Darwin, NeedsInvestigation, compiler/runtime
