### ISSUE TITLE
encoding/json: UnmarshalTypeError Offset is broken if a nested struct implements UnmarshalJSON

### ISSUE THREAD

**Issue by ajpetersons** [golang/go#43686] opened 2021-01-14 06:29 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/aj/Library/Caches/go-build"
GOENV="/Users/aj/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/aj/go/pkg/mod"
GONOPROXY="*private gitlab URL*"
GONOSUMDB="*private gitlab URL*"
GOOS="darwin"
GOPATH="/Users/aj/go"
GOPRIVATE="*private gitlab URL*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2n/c518mztn5yq_4k20jhf400vc0000gn/T/go-build993004208=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://play.golang.org/p/dJYX2lDwSKb

### What did you expect to see?

json.UnmarshalTypeError.Offset to be the same for nested structs.

### What did you see instead?

`json.UnmarshalTypeError.Offset` is only in the scope of nested struct if the struct implements a UnmarshalJSON method. The `Offset` should start from the beginning of the struct

**Comment by networkimprov** [comment] 2021-02-04 12:07
cc @mvdan

**Comment by mvdan** [comment] 2021-02-04 14:09
Perhaps related to https://github.com/golang/go/issues/34543. I'd suggest to re-run your experiment with that fix first.

**Comment by seankhliao** [comment] 2023-07-19 06:55
Duplicate of #11858

**Closed by seankhliao** 2023-07-19 06:55 UTC
Labels: NeedsInvestigation
