### ISSUE TITLE
[Question]How to connect with HTTP proxy!

### ISSUE THREAD

**Issue by iAmSKU** [golang/go#36408] opened 2020-01-06 13:26 UTC
### What version of Go are you using (`go version`)?

<pre>
go version: go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
NA

### What operating system and processor architecture are you using (`go env`)?
<pre>
linux/amd64
</pre>

### What did you do?
I was using "x/net/proxy" to connect with the "http_proxy".

I have refered following proxy page and corresponding examples:
https://godoc.org/golang.org/x/net/proxy

To get proxy information I have set environment variable "all_proxy" to the the desired proxy "http://192.30.20.10:5000", and performed the tcp connection, but following error raised:

**[Network Error : socks connect tcp 192.30.20.10:5000->mx.eu1.mico.io:8883: read tcp 172.17.0.2:48118->192.30.20.10:5000: read: connection reset by peer]**

I saw a similar proposal for the same, in the another thread:
https://github.com/golang/go/issues/19504 

As per the above threads "http_proxy" support is not available instead of "SOCKS5" proxy is supported. I have tried similar implementation for "http_proxy", but unfortunately it does not worked.

**Please suggest how to use "http_proxy" or "https_proxy" to connect with TCP/TLS?**

### What did you expect to see?
Able to connect to the proxy environment

### What did you see instead?
Unable to connect to the proxy environment, time out/connection reset.

**Comment by ALTree** [comment] 2020-01-06 17:10
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-01-06 17:10 UTC
