### ISSUE TITLE
affected/package: xml/encoding

### ISSUE THREAD

**Issue by larhun** [golang/go#57802] opened 2023-01-15 17:23 UTC
### What version of Go are you using (`go version`)?

<pre>1.19.5</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<pre>windows/amd64</pre>

### What did you do?

After running the snippet "https://go.dev/play/p/r7BVXxvAygX" on the input data 

<pre><code>&lt;a xmlns="x"&gt;&lt;b&gt;y&lt;/b&gt;&lt;/a&gt;</code></pre>

 I get the output data generated by using the <code>Encoder.EncodeToken</code>

<pre><code>&lt;a xmlns="x" xmlns="x"&gt;&lt;b&gt;y&lt;/b&gt;&lt;/a&gt;</code></pre>

that is non-well-formed XML with a duplicated attribute name <code>xmlns</code>. 

### What did you expect to see?

<pre><code>&lt;a xmlns="x"&gt;&lt;b&gt;y&lt;/b&gt;&lt;/a&gt;</code></pre>

### What did you see instead?

<pre><code>&lt;a xmlns="x" xmlns="x"&gt;&lt;b&gt;y&lt;/b&gt;&lt;/a&gt;</code></pre>

Please fix.

**Comment by seankhliao** [comment] 2023-01-16 01:15
Duplicate of #42807

**Closed by seankhliao** 2023-01-16 01:15 UTC
