### ISSUE TITLE
x/pkgsite: Error of the example of slog package

### ISSUE THREAD

**Issue by Tzuyang-Dafon** [golang/go#64829] opened 2023-12-21 03:43 UTC
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/log/slog@go1.21.5#Handler
 
### What is your user agent?
 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
 
 
### Screenshot
 
![image](https://github.com/golang/go/assets/103104204/62c499a8-3582-4138-8722-9a6fb8f91c69)
 
 
### What did you do?
 
Run the example of Example (LevelHandler)

**Comment by seankhliao** [comment] 2023-12-21 08:49
Duplicate of #61885

**Closed by seankhliao** 2023-12-21 08:49 UTC
Labels: pkgsite
