### ISSUE TITLE
x/tools/gopls: highlight deprecated symbols

### ISSUE THREAD

**Issue by ainar-g** [golang/go#40447] opened 2020-07-28 14:24 UTC
<p>I'm using <code>gopls</code> (see version information below) with Vim
(version <code>8.1</code>) and <code>natebosch/vim-lsc</code> (version
<code>632d49bf7a</code>).</p>

<pre>$ gopls version
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.0.0-20200727233628-55644ead90ce h1:IYtWwbxt1Jl45OJO6l9OnkvIlOQlRyaHgIvg+Rm2qNQ=
</pre>

<p>Currently, when I hover over a deprecated symbol, I don't see any
messages about the deprecation in Vim's statusline, and the symbol isn't
highlighted.  I assume, it's because <code>gopls</code> doesn't support
that.  I would like to see those messages.</p>

**Comment by jotdl** [comment] 2020-12-01 17:21
May I have a take on this? I would be happy to support `gopls` :)

Actually, I already started to investigate and think I might found the correct place to implement:
As an additional analyzer under `golang.org/x/tools/go/analysis/passes`.

Do you agree that this is the correct place this needs to be implemented or would you recommend somewhere else?

**Comment by stamblerre** [comment] 2020-12-01 18:23
@jotdl: Absolutely, we'd love to have you contribute! You're right that this would be another analysis pass, though the feature may already be available through Staticcheck (which is off-by-default right now): https://staticcheck.io/docs/checks#SA1019.

LSP also has a diagnostic tag that allows us to mark something as deprecated (https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#diagnostic), so one option might be to enable this particular check by default and set the tag for any of its warnings.

**Comment by jotdl** [comment] 2020-12-01 21:45
Yes, you are absolutely right. 

I didn't know yet that gopls comes with staticcheck. Sorry about that!  

So it seems that in order to solve this, we actually don't need to implement the analysis part itself and could rely on staticcheck instead. 

I did give this a try, but couldn't get it to work. A look into the staticcheck analysis code for deprecation warnings shows that it relies on facts produced by package dependencies ([deprecated.go L59](https://github.com/dominikh/go-tools/blob/9a1fe455724d08fc49829ac1e655fb2a0299d206/analysis/facts/deprecated.go#L59)).

After a bit of debugging I found that we currently don't execute analysis for package dependencies anymore (due #35089 ):

https://github.com/golang/tools/blob/92771a23d8e37f01ee601577de72ab359aee130a/internal/lsp/cache/analysis.go#L114-L117

After reenabling this code the analysis rule works again and then it's just a matter of adding the correct diagnostic tag which should be as easy as (as addition to `Analyze` in `internal/lsp/source/diagnostics.go`):

```go
if e.Category == "SA1019" {
  tags = append(tags, protocol.Deprecated)
}
```

But I am not sure how to proceed in perspective to #35089 . Are there any plans to reenable it?

**Comment by stamblerre** [comment] 2020-12-01 23:05
Thank you for doing all of this investigation, and I'm sorry you had to do so much digging! Re-enabling that logic more correctly is now tracked by https://github.com/golang/go/issues/38278, which will not happen for a while, but it seems like we can probably re-enable it for this case.

The changes you describe seem reasonable to me, so if you'd like to mail them, we'd love to get your contribution! One note is that we will be freezing the `gopls` codebase soon to focus on stability, so your change will likely not be merged until after the Go 1.16 release in February.

**Comment by jotdl** [comment] 2020-12-02 16:06
> Thank you for doing all of this investigation, and I'm sorry you had to do so much digging!

No worries, I didn't expect something different as language servers are usually  quite complicated and it's fun to read through all the code and get an idea of what's happening :)

So just to sum up things:
- We would reactivate the analysis of package dependencies for `SA1019`
- Set the correct diagnostic tag for analysis errors produced by `SA1019`
- Leave it to the user to enable `staticcheck` via `gopls` configuration

Please correct me if I misunderstood something.

I'll try to get a PR up this evening. But I also need to check the contribution guidelines as this would be my first contribution.

**Comment by stamblerre** [comment] 2020-12-06 04:42
Yep, that all sounds correct to me! The contribution guidelines can be found at https://golang.org/doc/contribute.html, and there are some testing-related docs here: https://github.com/golang/tools/tree/master/internal/lsp/tests.

**Comment by jotdl** [comment] 2020-12-09 21:30
I am still on it, but sadly I am currently stuck:

When I enable the analyzation of package dependencies for SA1019 in [analysis.go line 117](https://github.com/golang/tools/blob/92771a23d8e37f01ee601577de72ab359aee130a/internal/lsp/cache/analysis.go#L114-L117) via 
```
if a.Name == "fact_deprecated" { // enable SA1019
   ...
}
```

 running the tests via `go test ./...` get stuck and they never finish. 

It took me a while to figure out which tests are causing this behaviour and it seems like 

- internal/lsp/testdata/analyzer/bad_test
- internal/lsp/testdata/suggestedfix/has_suggested_fix

are the cause of this issue. At least removing them fixes the hanging tests. 

I could already mail the changes. But without fixing the tests I guess the changes are not worth much.

**Comment by stamblerre** [comment] 2020-12-11 17:25
If you'd like to mail the changes, I'd be happy to take a look and see if I can identify the issue.

**Comment by pjweinb** [comment] 2021-03-02 19:20
There doesn't seem to be any standard way of saying that something is deprecated. For instance, io/ioutil just says that there are better alternatives, while net/http uses the word Deprecated.  Is the list the staticcheck uses (https://github.com/dominikh/go-tools/blob/v0.0.1-2020.1.6/deprecated/stdlib.go) hand generated? (last updated for go1.14)

**Comment by jotdl** [comment] 2021-03-02 19:57
@pjweinb There is no "enforced" way of marking something as deprecated, but I think it's widely accepted to use the Deprecated word as documented in https://github.com/golang/go/wiki/Deprecated and the majority of go developers deprecate code as documented there. 

I am not sure if t the staticcheck list you mentioned is written by hand, but it looks to me like it was. I could think of a couple of reasons why they did so, but that's something you would better ask in the staticcheck repository as I sadly don't know a lot about it.

**Comment by jotdl** [comment] 2021-03-02 20:13
@stamblerre I am really sorry that I was unable to push this further during the last two months. As I was unable to test this and just got stuck I felt like it's not worth to push my changes as they are so minimal and even not tested.

Anyways, I'll rebase my changes and check what the current state is. Maybe I can figure out now what needs to be done in order to get the tests running.

**Comment by stamblerre** [comment] 2021-03-02 21:38
@jotdl: No worries--not a problem at all! @pjweinb was just interested in adding deprecated markers to completion or document symbols, which is related but not necessarily overlapping with this issue.

**Comment by pjweinb** [comment] 2021-03-03 14:56
Yes. I apologize for the misunderstanding. My point was about trying to automate the process of finding out what was obsolete, and I thought this would be a good place to remember what I found. Some languages use @deprecated in function documentation, but Go doesn't.

**Comment by eryajf** [comment] 2022-06-20 13:39
I don't know enough information, and now it comes to this question. I want to make sure that this problem still exists.

I use vscode to develop the go language, and I find that it doesn't work when the method is annotated as follows

```
// this is test func
// Deprecated
func TestFunc() {
	fmt.Println("aaa")
}
```

If the previous line next to the deprecated also has a comment, it will not work properly，Add a newline to the deprecated comment and it will work properly

my gopls version is:

```
$ gopls version
golang.org/x/tools/gopls v0.8.4
    golang.org/x/tools/gopls@v0.8.4 h1:zGZsAXAb0LLws/Z+2BCWR17dkPHhIO2GYwYSSkeXX5c=
```

**Comment by ainar-g** [comment] 2022-06-20 13:57
@eryajf, the comment in that code does not conform to the [deprecation notice convention][1].  The deprecation notice must be on in separate paragraph and have a short comment.

[1]: https://github.com/golang/go/wiki/Deprecated

**Comment by eryajf** [comment] 2022-06-20 14:14
> the comment in that code does not conform to the [deprecation notice convention](https://github.com/golang/go/wiki/Deprecated). The deprecation notice must be on in separate paragraph and have a short comment.

So should the correct usage be like this?

```
// this is test func

// Deprecated: this is old func, the new func is NewTestFunc()
func TestFunc() {
	fmt.Println("aaa")
}
```

At this point, the original comment `// this is test func` is cut off from the current method, and it doesn't feel good. Or should I delete this comment?

**Comment by eryajf** [comment] 2022-06-20 14:23
@ainar-g  When I write like this, it doesn't work.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/33259379/174622821-d2b2b505-82ca-4da6-8b69-807769416407.png">

**Comment by eryajf** [comment] 2022-06-20 14:47
@ainar-g 

Maybe it's just vscode's problem. When I use goland, the problem disappears

<img width="557" alt="image" src="https://user-images.githubusercontent.com/33259379/174627089-8bf5233c-194c-4004-b133-a03a691ddcbd.png">

I came here from this question golang/vscode-go/issues/599 . The problem on the other side has been closed, but it doesn't seem to be solved.

**Comment by hyangah** [comment] 2022-06-21 15:28
vscode-go side issue was closed because it's the duplicate of this issue.

**Comment by tooltitude-support** [comment] 2023-02-14 15:28
We are working on a productivity go extension called tooltitude. We recently added the highlighting of deprecated symbols which is what people in this thread were asking for.

You could install the extension from this page:  https://marketplace.visualstudio.com/items?itemName=tooltitudeteam.tooltitude
You could read more about the product on this page: https://www.tooltitude.com/

P.S. We also have other inspections, and more than 20 code actions. We work to augmenting gopls with features which the go team either won't have time to implement or won't implement for other reasons (my understanding that the target project size is very large).

P.P.S. If you are interested in discussing which features you are interested in, feel free to reach out to email address on my profile. Would be happy to talk to users or potential users.

<img width="313" alt="Deprecated" src="https://user-images.githubusercontent.com/123904466/218782474-48e013f4-df0e-41b9-8f5b-e07c31fa95c4.png">

**Comment by hyangah** [comment] 2023-03-10 01:56
`staticcheck`'s [SA1019](https://staticcheck.io/docs/checks#SA1019) already implements it. VS Code Go extension uses `staticcheck` as the default linter, so if the lint running outside gopls is not disabled, users will already see reports like this.

![Screenshot 2023-03-09 at 8 18 42 PM](https://user-images.githubusercontent.com/4999471/224198637-4dd8650f-4754-4d01-afaf-3f5b63c7153e.png)

Gopls also has `staticcheck` integration.  Not sure if the staticcheck embedded in gopls depends on the fact propagation in gopls or not. If it depends on gopls's driver, good news is I think the gopls at master already fixed [the issue](https://github.com/golang/go/issues/40447#issuecomment-736840061). From the gopls built from master, I see SA1019 check working as expected when I enabled `"gopls": { "ui.diagnostics.staticcheck": true }` setting. 

![Screenshot 2023-03-09 at 8 21 40 PM](https://user-images.githubusercontent.com/4999471/224199029-69fa0d69-5b93-46c4-9f8a-5f16c7f3c962.png)

However, some may prefer strikethrough to this squiggle presentation. I played a bit with SA1019 diagnostics in gopls. It looks like if we change SA1019 diagnostics to be mapped to [Diagnostics](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnostic) with severity=hint(4), tags=[Deprecated], this will produce the effect we want:

![Screenshot 2023-03-09 at 8 16 05 PM](https://user-images.githubusercontent.com/4999471/224198672-cea70617-914a-4a65-891a-116648cffd87.png)

The easiest path I see is to enable this is to use [honnef.co/go/tools/analysis/facts/deprecated](https://pkg.go.dev/honnef.co/go/tools@v0.4.2/analysis/facts/deprecated) which already is x/tools/go/analysis.Analyzer. 
Once done, we can disable SA1019 in [the hook setup](https://github.com/golang/tools/blob/dd1e2f66b2420ea0ea114b7e1f9280612604bb57/gopls/internal/hooks/analysis_119.go#L53).

We also need to sort out
 - How/where to set a different severity for diagnostics generated from [x/tools/go/analysis.Diagnostic](https://pkg.go.dev/golang.org/x/tools/go/analysis#Diagnostic).
 - Where to set the protocol.Diagnostic's Tags field.
 - Do we still want to provide an option to report deprecated symbol usages as severity level = Warning or Information? If so, should there be an option?
 
Another minor caveat is staticcheck module requires go1.19+. Not sure if the `deprecated` package can be included in the gopls built with older versions of go if gopls's buildable go version support window is larger.

In addition to this diagnostics that are presented on the callsites, I think it is also cool if we can add deprecation info to
  - DocumentSymbol (so VS Code Document Outline marks deprecated symbols inside the package)
  - WorkspaceSymbols (so workspace symbols can also show deprecated symbol info.

**Comment by dominikh** [comment] 2023-03-10 11:34
>  Not sure if the staticcheck embedded in gopls depends on the fact propagation in gopls or not

It does. 

> Another minor caveat is staticcheck module requires go1.19+. Not sure if the deprecated package can be included in the gopls built with older versions of go if gopls's buildable go version support window is larger.

There is a good chance that the `deprecated` package doesn't need Go 1.19 at the moment, and else I'd be happy to accept patches for that package specifically.

**Comment by hitzhangjie** [comment] 2023-06-11 16:58
3 years passed

**Closed** 2023-07-25 17:43 UTC
Labels: help wanted, FeatureRequest, gopls, Tools

**Comment by hitzhangjie** [comment] 2023-08-10 03:36
How to enable this 'highlight depreated symbols' feature? I installed gopls from the master branch. It still not work as expected.

**Comment by hyangah** [comment] 2023-08-10 03:43
It's enabled by default and the feature is available in the latest release.
Can you provide the example code?

**Comment by hitzhangjie** [comment] 2023-08-10 04:09
@hyangah Here's my example code:
<img width="742" alt="image" src="https://github.com/golang/go/assets/3725760/53579785-1d80-4066-861d-3f3a352f0b54">

**Comment by hyangah** [comment] 2023-08-10 04:47
@hitzhangjie Can you hover over the `package main` and tell us what error is present there? That often indicates the files couldn't be parsed and analyzed correctly for some reason. In that case, secondary analysis like deprecated symbol check  doesn't (or cannot) run.
 
For example, editor setting errors (build tags), or issues related to the module boundary ([doc](https://github.com/golang/tools/blob/master/gopls/doc/workspace.md) are some of the common issues we've seen.

**Comment by hitzhangjie** [comment] 2023-08-10 06:21
@hyangah Sorry for this example. I put the example under a module but I doesn't use go.work.

After I put the main.go, add.go under a new clean project folder, the yellow error message gone, and:
1 )The expected strikethrough still not displayed.
2) but I moved add.go to new a new package (not main), the strikethrough is displayed.

<img width="861" alt="image" src="https://github.com/golang/go/assets/3725760/01cf0211-8ce3-4d6d-8872-0e611e5a9656">

**Comment by hyangah** [comment] 2023-08-10 13:06
Thanks @hitzhangjie 
Yes, the feature marks only deprecated symbols from other packages.
That is intended behavior. The reasoning is that the package owners know what symbols are deprecated already and use of deprecated symbols inside the package often has a reason. One of the pathological cases is, for example, `io/ioutil`. The entire package is deprecated but they won't disappear from the project due to the go1 compatibility policy. Managing tests and part of code that use deprecated symbols is part of normal operation.

**Comment by hitzhangjie** [comment] 2023-08-11 02:01
@hyangah OK. Thanks for the explaination.

**Comment by fantapop** [comment] 2024-03-18 21:19
This is still not quite working for me.  I see the strikethrough in the popup only if the godoc on the function is a single line with "Deprecated: " as a prefix.  If the godoc includes multiple paragraphs, one of which is prefixed with Deprecated, I can see the strikethrough in editor pane but not in the popup.    Does the fact that its working for the editor pane and not the pop-up indicate that this is on the vscode side?

Here are the 2 examples.  You can see what the content is in the popup box:

A single line document string correctly striking through in the popup and the source code:
<img width="555" alt="Screenshot 2024-03-18 at 1 40 02 PM" src="https://github.com/golang/go/assets/6658984/0beb4b90-be6b-4b28-9e82-3cc73a6f1d11">

A multi-paragraph document string only striking through the text in the source code:
<img width="472" alt="Screenshot 2024-03-18 at 1 44 45 PM" src="https://github.com/golang/go/assets/6658984/34d397f7-1d80-4c12-8388-361d966379e0">

**Comment by GOodCoffeeLover** [comment] 2024-04-18 17:46
@hyangah 
Hi, is there any possibilities for creating some feature flag that would enable deprecation marks in same package?

In my case i want it to highlight to colleagues use another private methods because they (method, not colleagues %) ) will be removed in short time, but can't be removed just now for backward compatibility. And visually highlighting this would be better, that if i just say it.

It would be very helpful.

**Comment by mukhinid** [comment] 2025-01-29 14:43
> A multi-paragraph document string only striking through the text in the source code:

For everyone facing the same problem as @fantapop: it works when deprecation notice is in the first line.
