### ISSUE TITLE
x/tools/gopls: sudden errors in unrelated files

### ISSUE THREAD

**Issue by atombender** [golang/go#38730] opened 2020-04-28 19:24 UTC
#### What did you do?
Edited code in a single test file in VSCode.

#### What did you expect to see?
Only my current file should be affected by changes in a test package.

#### What did you see instead?
Suddenly, a large number of unrelated files were marked as having errors. I did not have any of these files open, nor did I change them, nor did (as far as I know) any program on my computer touch them. All the errors in them are spurious; restarting gopls causes them to go away. 

![Screen Shot 2020-04-28 at 15 15 10](https://user-images.githubusercontent.com/50314/80528243-9ef75b80-8963-11ea-9480-c1cfc67bfa23.jpg)

Log: [gopls.log.gz](https://github.com/golang/go/files/4548009/gopls.log.gz). This is from gopls started, so fairly large. Jump to line 14890 to see what looks like the first error.

Note: While I have `GOFLAGS=-tags=...` set, none of the affected files use build tags.

#### Build info

```
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@(devel)
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20191130070609-6e064ea0cf2d => ../
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```

#### Go info

```
go version go1.13.10 darwin/amd64

```

**Comment by stamblerre** [comment] 2020-04-28 19:42
Thanks for the report. This looks like https://github.com/golang/go/issues/38403, which is unfortunate because I had hoped that it was only caused by `-remote`.

Did any of the files with errors depend transitively on the readthrough pacakge?

**Comment by atombender** [comment] 2020-04-28 20:36
Yes, but not all. Also, my last edit to anything in the `readthrough` package was two minutes before this happened. I mostly edited the `readthrough_test` package.

You guys really don't like capitalized sentences in issue titles. 🙂

**Comment by stamblerre** [comment] 2020-04-28 20:45
> Yes, but not all. Also, my last edit to anything in the `readthrough` package was two minutes before this happened. I mostly edited the `readthrough_test` package.

Thanks for clarifying. Tests can still be dependencies (if this is an in-package test, and not an x_test) because other test packages depend on test variants. It's possible that we have another cache invalidation issue with test variants, but I'm not sure how that could've happened since it's been a while since the type-checking code has changed.

I think I will close this issue as a duplicate of #38403 so that we can track everything in one place. Please comment there if you're able to find a consistent repro for this.

> You guys really don't like capitalized sentences in issue titles. 🙂

We tend to follow the same style in issues and commit messages - see https://github.com/golang/go/wiki/CommitMessage.

**Comment by stamblerre** [comment] 2020-04-28 20:45
Duplicate of #38403

**Closed by stamblerre** 2020-04-28 20:45 UTC
Labels: Tools, gopls
