### ISSUE TITLE
proposal: Go 2: Some proposals for circular import

### ISSUE THREAD

**Issue by godcong** [golang/go#57279] opened 2022-12-13 07:17 UTC
### Author background

- **Would you consider yourself a novice, intermediate, or experienced Go programmer?**
 10 year
- **What other languages do you have experience with?**
 20 year for C/C++ & JAVA & PHP
### Related proposals

The problem of circular import has always bothered me.
I have defined an interface, but the interface refers to another package.
Some of the functions implemented in this package refer to this interface.
So I've been thinking. Since the interface does not involve the implementation.
So is it possible to use a separate type to apply to the interface package to prevent the problem of circular import

an example for this like:
```
interface anInterfacePackage

import(
    somepackage "packages"
)

type ANewInterface interface{
    PacageFuncA() somepackage.FuncA
}
```

This must be a separate folder, only `interface packages` are allowed. 
No functional implementations are allowed.
Even if it refers to another package, it tells the compiler that it does not need to import this package anymore.

The interface does not involve implementation so it can be implemented by any struct.
It is the implementation that needs to refer to the specific package.

This allows the interface to be extracted separately, without the need to consider the problem of package conflicts.
Most of the time the role of the interface is not used to solve this problem?

The idea may not be perfect, I hope you discuss it.
A better solution to the circular import problem can be sorted out

**Comment by seankhliao** [comment] 2022-12-13 09:05
Duplicate of #30247

**Closed by seankhliao** 2022-12-13 09:05 UTC
Labels: Proposal
