### ISSUE TITLE
proposal: archive/zip: 

### ISSUE THREAD

**Issue by ram46** [golang/go#50673] opened 2022-01-18 20:11 UTC
Problem:
- Can't find the zip file size while adding files to the zip - no archive file size attribute in the object
- Can't append new files to an existing zip file after it is closed - zipper.Close(). Example Python offers opening a closed zip file and append files to it. 

Proposal:
- Include the append feature to the archive/zip feature.

**Comment by seankhliao** [comment] 2022-01-18 20:21
Duplicate of #15626

**Closed by seankhliao** 2022-01-18 20:21 UTC
Labels: Proposal
