### ISSUE TITLE
cmd/gofmt: does not remove empty line right after open brace

### ISSUE THREAD

**Issue by hmage** [golang/go#28691] opened 2018-11-09 16:30 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hmage/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hmage/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/hmage/work/AdGuardHome/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_8/ft55wrmx5f777hg1hgd8c2yc0000gn/T/go-build001940766=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

In all code examples and documentation in go, there is no empty line right after open brace in start of a function, or a loop, or similar.

Gofmt seems to not enforce this, though, and there are members of my team that insist that if gofmt isn't changing it, then it's official stance of go language, since it does remove it in struct declaration.

I'm opening this issue to seek clarification and if there's any official stance from @ianlancetaylor on empty lines after opening brace, and, hopefully, add enforcing of that into gofmt, since it already does that to structs.

For example here `gofmt` will remove the first empty line:
```go
type filter struct {

	ID  int64
	URL string

	Name     string
	Enabled  bool
	Contents []byte
}
```

But here `gofmt` will not:
```go
func main() {

	fmt.Println("The empty line above this one seems unnecessary")

	fmt.Println("The empty line above this one is fine and shouldn't be touched")
}
```

More examples that can be gofmt'ed are at this link -- https://play.golang.org/p/FkD7WAOU-uL

### What did you expect to see?

Empty lines after opening brace removed, as it's being done with struct definitions.

### What did you see instead?

Only struct definition gets empty line removed after opening brace.

**Comment by ianlancetaylor** [comment] 2018-11-09 17:51
I don't know gofmt removes the blank line in one case but not the other.  I really don't feel strongly either way, except that changing gofmt output at this point is kind of a pain since it causes perfectly fine existing code to suddenly fail gofmt checks.  Leaving for @griesemer .

**Comment by griesemer** [comment] 2018-11-09 18:10
Duplicate of #6996.

**Closed by griesemer** 2018-11-09 18:10 UTC
Labels: NeedsInvestigation
