### ISSUE TITLE
proposal: sync: add SafeLength and DirtyLength.

### ISSUE THREAD

**Issue by sivchari** [golang/go#53903] opened 2022-07-15 14:28 UTC
I propose to add SafeLength and DirtyLength method to sync.Map. Currently, we don't get the length of sync.Map.  For that reason, we can't prepare length and capacity for `map` and `slice`.  sync.Map has two map, `m` contained in readOnly struct and dirty. 

So, SafeLength returns the length of `m`, DirtyLength returns the length of dirty.  If a developer wanna get the length of `m` (i.e. wanna to get the length of immutable struct stored atomically), we'll use SafeLength. Conversely, If a developer wanna to get the length of dirty which contains all values, we'll use DirtyLength.

But, dirty may be initialized. For example, Load and missLocked initialize it. Above the reason, I recommend to use SafeLength, but I also added DirtyLength for every case. If this proposal is accepted, we can execute following code.

```go
package main

import (
	"fmt"
	"sync"
	"time"
)

func main() {
	m := sync.Map{}

	m.Store("Key 1", "Value 1")
	m.Store("Key 2", "Value 2")
	m.Store("Key 3", "Value 3")
	m.Store("Key 4", "Value 4")
	m.Store("Key 5", "Value 5")

	<-time.After(5 * time.Millisecond)

	vals := make([]string, 0, m.SafeLength())

	m.Range(func(key interface{}, value interface{}) bool {
		vals = append(vals, value.(string))
		return true
	})

	fmt.Println(vals)
}
```

**Comment by seankhliao** [comment] 2022-07-15 15:14
Duplicate of #20680

**Closed by seankhliao** 2022-07-15 15:14 UTC
Labels: Proposal
