### ISSUE TITLE
freebsd: cmd/link/internal/loader: panic: runtime error: index out of range [192] with length 3

### ISSUE THREAD

**Issue by zx2c4** [golang/go#50083] opened 2021-12-09 22:31 UTC
https://storage.googleapis.com/go-build-log/bd46cfd5/freebsd-amd64-12_2_d8d540ce.log

Surprising flake on FreeBSD, rather close to beta1.

CC @bcmills

**Comment by bcmills** [comment] 2021-12-09 22:51
> Surprising flake on FreeBSD, rather close to beta1.

Unfortunately not that surprising. 😩

**Comment by bcmills** [comment] 2021-12-09 22:51
Duplicate of #46272

**Closed by bcmills** 2021-12-09 22:51 UTC
