### ISSUE TITLE
net/http: flake in TestHijackAfterCloseNotifier?

### ISSUE THREAD

**Issue by mwhudson** [golang/go#13633] opened 2015-12-16 01:57 UTC
Seen here: http://build.golang.org/log/fb09069fbdc77389a13a2e191d70eb8ce01b84e9 (linux/arm64) but also locally.

**Comment by ianlancetaylor** [comment] 2015-12-16 02:15
CC @bradfitz

**Comment by bradfitz** [comment] 2015-12-16 04:28
I can reproduce at least on Linux/amd64.

Notes:
- 0 to 3 in 2000 runs fails for me.
- creating a dedicated Transport just for this test (e.g. with newClientServerTest) doesn't fix it.
- disabling the CloseNotify calls doesn't fix it.
- closing Response.Bodies doesn't fix it.
- copying the bytes from Response.Body to ioutil.Discard (always zero, always nil io.Copy error) doesn't fix it.
- no races detected
- even a http.Handler of this single line still fails:
```go
   w.Header().Set("X-Addr", r.RemoteAddr)
```

So this has nothing to do with either CloseNotifier, nor Hijack.

There are other tests which use this same pattern of doing two requests and verifying they report the same RemoteAddr as a proxy for determining whether the connection was re-used. One example is `TestHandlerSetsBodyNil_h1` and `_h2`.  It looks identical about I can't get it to flake.

I'm very confused.

**Comment by bradfitz** [comment] 2015-12-16 04:34
Ah, the difference between `TestHijackAfterCloseNotifier` and `TestHandlerSetsBodyNil_h1` is that the latter writes non-zero response bytes. And indeed, that seems to be the cause of the flakiness: if there are zero response bytes and a Content-Length of 0, the Transport sometimes creates a new connection rather than re-using the one it just replied with.

**Comment by bradfitz** [comment] 2015-12-16 17:15
Sent https://go-review.googlesource.com/#/c/17890/1

**Closed** 2015-12-16 17:51 UTC

**Comment by mwhudson** [comment] 2015-12-16 22:40
Thanks for the quick fix :-)
