### ISSUE TITLE
cmd/go: 'go test ./...' not support failfast flag

### ISSUE THREAD

**Issue by liulianjun** [golang/go#50507] opened 2022-01-08 02:03 UTC
when i run `go test  -failfast TestName`，the failfast flgs is working, but when i run `go test -failfast ./...`（the directory contain many package），the failfast not working。

**Comment by bcmills** [comment] 2022-01-10 16:14
Please fill out the complete issue template. What did you do, what did you expect to see, and what did you actually see?

**Comment by bcmills** [comment] 2022-01-10 16:14
#30522 may be related.

**Comment by liulianjun** [comment] 2022-01-11 07:33
> go version: go version go1.16.5 windows/amd64

### What did you do?
the file dir: 
```
pkg
  test
    test1
	 example1_test.go
    test2
	 example2_test.go
```

the example content:
```go
//  example1_test.go
func TestName1(t *testing.T) {
	assert.Fail(t, "the name1 test unit failed.")
}
```

```go
//  example2_test.go
func TestName2(t *testing.T) {
	assert.Fail(t, "the name2 test unit failed.")
}
```

exec the command:  

```shell
# cd pkg/
# go test ./... -failfast
```

### What did you expect to see?
I expect when TestName1 execute failed，TestName2 not execute.


### What did you see instead?
when TestName1 execute failed，TestName2 continue execute.

**Comment by seankhliao** [comment] 2022-02-08 21:09
Duplicate of #33038

**Closed by seankhliao** 2022-02-08 21:09 UTC
Labels: WaitingForInfo, GoCommand
