### ISSUE TITLE
Why http response packet blocked by exec?

### ISSUE THREAD

**Issue by songtianyi** [golang/go#19360] opened 2017-03-02 10:51 UTC
### What version of Go are you using (`go version`)?
go version go1.5.1 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/data/songtianyi/golang/own:/data/songtianyi/golang/go:/data/songtianyi/golang/own/src/dtf-manager/"
GORACE=""
GOROOT="/data/songtianyi/golang/go"
GOTOOLDIR="/data/songtianyi/golang/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
### What did you do?
```go
package main

import (
	"fmt"
	"net/http"
	"os/exec"
)

func Hello(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("Hello!!"))

	out, err := exec.Command("sleep", "10").CombinedOutput()
	fmt.Println(string(out))
	if err != nil {
		fmt.Println(err)
		return
	}
}

func main() {
	http.HandleFunc("/hello", Hello)
	addr := "0.0.0.0:8083"
	if err := http.ListenAndServe(addr, nil); err != nil {
		fmt.Println(err)
		return
	}
}
```
##### steps to replay the wired "bug"
1. build and run the code above
2. execute the following command
```
time curl http://localhost:8083/hello
```
### What did you expect to see?
server response "Hello!!" **immediately**

### What did you see instead?
server response **after** exec exit!! wired!

**Comment by ALTree** [comment] 2017-03-02 12:23
Hi,

the Go project does not use its bug tracker for general discussion or asking questions. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. 

Closing, since this is not a bug, but a question about `http.ResponseWriter` buffering behaviour.

**Closed by ALTree** 2017-03-02 12:23 UTC
