### ISSUE TITLE
x/tools/cmd/gopls: completions do not work for unpersisted imports

### ISSUE THREAD

**Issue by myitcv** [golang/go#31338] opened 2019-04-08 10:44 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.2 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20190406165526-0d5674b3111a
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/home/myitcv/gostuff/src/github.com/myitcv/govim/cmd/govim/.bin"
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPROXY=""
GORACE=""
GOROOT="/home/myitcv/gos"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build127648482=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Considering the following [`govim`](https://github.com/myitcv/govim/tree/master/cmd/govim) [`testscript`](https://godoc.org/github.com/rogpeppe/go-internal/testscript) in which I attempt a completion in a file that does not currently have the relevant import (of `"fmt"`) persisted to disk:

```
vim ex 'e main.go'
vim ex 'call setline(3, \"import \\\"fmt\\\"\")'
vim ex 'call setline(6, \"\\tfmt.Pr\")'
vim ex 'call cursor(6,1)'
vim ex 'call feedkeys(\"A\\<C-X>\\<C-O>\\<C-N>\\<C-N>\\<C-N>\\<ESC>\", \"x\")'
vim ex 'w'
cmp main.go main.go.golden

-- go.mod --
module mod.com

-- main.go --
package main

// import

func main() {
	// fmt.Pr
}

-- main.go.golden --
package main

import "fmt"

func main() {
	fmt.Println
}
```

As with all `govim` buffers, every initial buffer read is sent to `gopls` as a `DidOpen` notification; every subsequent change is sent as a `DidChange`.

### What did you expect to see?

The completion to succeed and hence the test to pass.

### What did you see instead?

```
> cmp main.go main.go.golden
[diff -main.go +main.go.golden]
 package main

 import "fmt"

 func main() {
-       fmt.Pr
+       fmt.Println
 }
-

FAIL: testdata/complete_import_not_on_disk.txt:10: main.go and main.go.golden differ
```

cc @stamblerre @ianthehat

**Comment by stamblerre** [comment] 2019-04-17 03:44
Duplicate of #31467

**Closed** 2019-04-17 03:44 UTC
Labels: NeedsInvestigation, gopls
