### ISSUE TITLE
x/tools/golpls: go mod tidy diagnostic fails with tags in buildFlags

### ISSUE THREAD

**Issue by ian-mi** [golang/go#41804] opened 2020-10-05 21:05 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

Loaded package in gopls with "gopls.buildFlags" set to "-tags=e2e".

### What did you expect to see?

No errors

### What did you see instead?

> 2020/10/05 20:41:16 warning: diagnose go.mod: err: exit status 2: stderr: flag provided but not defined: -tags
> usage: go mod tidy [-v]
> Run 'go help mod tidy' for details.

**Comment by stamblerre** [comment] 2020-10-06 01:43
Duplicate of https://github.com/golang/go/issues/41803

**Closed by stamblerre** 2020-10-06 01:43 UTC
Labels: Tools
