### ISSUE TITLE
Add option to set date and time for time.Now

### ISSUE THREAD

**Issue by ivanjaros** [golang/go#45178] opened 2021-03-23 12:49 UTC
It seems there is no way to globally set time and date so testing with external dependencies that make direct calls to time package is impossible. Hence why some kind of time init option should be added into main so testing can be done on applications(not libraries) that work with time, especially non-present time(ie. cron-like tasks).

**Comment by seankhliao** [comment] 2021-03-23 16:29
Duplicate of #8869

**Closed by seankhliao** 2021-03-23 16:29 UTC

**Comment by ivanjaros** [comment] 2021-03-23 18:55
no change after 7 years gives me the impression that there is no way in hell this will get fixed, ever. great.
