### ISSUE TITLE
go is very if programing...why???

### ISSUE THREAD

**Issue by gojm** [golang/go#42397] opened 2020-11-05 11:34 UTC
`it is not beautiful to solve`

**Comment by ALTree** [comment] 2020-11-05 12:37
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-11-05 12:37 UTC
