### ISSUE TITLE
cmd/go: "go mod tidy" does not remove duplicate lines

### ISSUE THREAD

**Issue by kevinburkemeter** [golang/go#33603] opened 2019-08-12 18:08 UTC
As a result of a bad rebase, I had exactly duplicate lines in my go.sum file:

```
github.com/kr/pretty v0.1.0 h1:L/CwN0zerZDmRFUapSPitk6f+Q3+0za1rQkzVuMiMFI=
github.com/kr/pretty v0.1.0 h1:L/CwN0zerZDmRFUapSPitk6f+Q3+0za1rQkzVuMiMFI=
github.com/kr/pretty v0.1.0/go.mod h1:dAy3ld7l9f0ibDNOQOHHMYYIIbhfbHSm3C4ZsoJORNo=
github.com/kr/pretty v0.1.0/go.mod h1:dAy3ld7l9f0ibDNOQOHHMYYIIbhfbHSm3C4ZsoJORNo=
```

I expected that "go mod tidy" would remove duplicate entries, but each line was left in the resulting file. I'm running Go tip (`go version devel +8b058cfbce Sun Aug 11 15:44:08 2019 +0000 darwin/amd64`)

**Comment by bcmills** [comment] 2019-08-12 18:34
Failure to collapse duplicate lines in general is #28456.

Thanks for the “bad rebase” detail, though — I was having a hard time figuring out how folks were getting into this state!

**Comment by bcmills** [comment] 2019-08-12 18:34
Duplicate of #28456

**Closed by bcmills** 2019-08-12 18:34 UTC
