### ISSUE TITLE
cmd/go: -coverpkg packages imported by all tests, even ones that otherwise do not use it

### ISSUE THREAD

**Issue by ChrisHines** [golang/go#23910] opened 2018-02-18 17:29 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.10 windows/amd64

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

```
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Chris\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Chris\Go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Chris\AppData\Local\Temp\go-build675280250=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

```
>go get github.com/ChrisHines/coverpkgtest

>cd $GOPATH/github.com/ChrisHines/coverpkgtest

>go run main.go
9

>go test ./...
?       github.com/ChrisHines/coverpkgtest      [no test files]
ok      github.com/ChrisHines/coverpkgtest/subdir       (cached)

>go test -coverpkg=./... .
?       github.com/ChrisHines/coverpkgtest      [no test files]

>go test -coverpkg=./... ./subdir
ok      github.com/ChrisHines/coverpkgtest/subdir       0.052s  coverage: 0.0% of statements in ./...

>go test -coverpkg=. ./subdir
warning: no packages being tested depend on matches for pattern .
ok      github.com/ChrisHines/coverpkgtest/subdir       0.057s  coverage: 0.0% of statements in .

>go test -coverpkg=. ./...
?       github.com/ChrisHines/coverpkgtest      [no test files]
panic: open tmpl.txt: The system cannot find the file specified.

goroutine 1 [running]:
text/template.Must(0x0, 0x5c8ba0, 0xc042064390, 0x1)
        C:/Go/src/text/template/helper.go:23 +0x5b
FAIL    github.com/ChrisHines/coverpkgtest/subdir       0.056s

>go test -coverpkg=./... ./...
?       github.com/ChrisHines/coverpkgtest      [no test files]
panic: open tmpl.txt: The system cannot find the file specified.

goroutine 1 [running]:
text/template.Must(0x0, 0x5c8ba0, 0xc042074390, 0x1)
        C:/Go/src/text/template/helper.go:23 +0x5b
FAIL    github.com/ChrisHines/coverpkgtest/subdir       0.055s
```

### What did you expect to see?

I expected the tests to pass regardless of how they are launched by the go tool.

### What did you see instead?

Using `-coverpkg=./...` in combination with the test package pattern `./...` caused a panic for a missing file even though the file exists. It is also confusing that running the tests on individual packages or without `-coverpkg=./...` does not panic.

**Comment by ianlancetaylor** [comment] 2018-03-28 22:54
I think the problem is that cmd/go rewrites tests to import all packages listed in `-coverpkgs`.  It then runs the test for package `subdir` in the `subdir` directory.  In your case the main package is listed in `-coverpkgs`, so the test imports it.  The only thing that is run in the main package is the initializers.  In your program that is what fails: the initializer loads a relative file and can only run in the main package directory, not in the subdirectory.

Not sure what the right fix is.

**Comment by nvartolomei** [comment] 2018-11-28 19:02
Sounds like #27336

**Comment by forsaken628** [comment] 2020-12-18 10:01
test
```
go test -v -coverpkg=./... ./...

-- go.mod --
module test
-- main.go --
package main

import "flag"

func init() { flag.Parse() }
-- bar/bar.go --
package bar
-- bar/bar_test.go --
package bar
```

link
https://golang.org/cl/278892

maybe skip main package without test files

```
Index: src/cmd/go/internal/test/test.go
<+>UTF-8
===================================================================
diff --git a/src/cmd/go/internal/test/test.go b/src/cmd/go/internal/test/test.go
--- a/src/cmd/go/internal/test/test.go	(revision dfaf69eccc66f44e9ca150d062baadf53c574438)
+++ b/src/cmd/go/internal/test/test.go	(revision cfab536ac976f7597165cfac002c80cc6613ad5f)
@@ -731,6 +731,11 @@
 				continue
 			}

+			// Don't call main.init, if no test file.
+			if p.Name == "main" && len(p.TestGoFiles)+len(p.XTestGoFiles) == 0 {
+				continue
+			}
+
 			if haveMatch {
 				testCoverPkgs = append(testCoverPkgs, p)
 			}
```

**Comment by slinkydeveloper** [comment] 2021-05-19 12:36
If you want to try a bigger project to reproduce the issue, clone https://github.com/knative/eventing and run the test with:

```
go test -race -coverpkg=./... ./...
```

**Comment by thanm** [comment] 2023-05-18 13:16
FYI, we've moved away from the model in which all `-coverpkg` packages are force-imported into every test, this was done as part of the coverage redesign in Go 1.20.  This is spawn a few bugs (ex: #58770) but I have a fix out for review that should resolve that (https://go.dev/cl/495452). Closing this bug out, please reopen if needed.

**Closed by thanm** 2023-05-18 13:16 UTC
Labels: NeedsInvestigation, GoCommand
