### ISSUE TITLE
runtime: TestGdbPython fails with GDB 8.2 on FreeBSD

### ISSUE THREAD

**Issue by paulzhol** [golang/go#29455] opened 2018-12-29 17:43 UTC
FreeBSD updated the binary GDB packages to 8.2. The test is now failing on the arm builder (recently updated to FreeBSD 12.0):

Example:
https://build.golang.org/log/f262478ed3c90cf506b7e45e4735624266814b61

```
        BEGIN info goroutines
        * 1 running  syscall.Syscall
          2 waiting  runtime.gopark
          3 waiting  runtime.gopark
          17 runnable runtime.runfinq
        END
```
```
        BEGIN goroutine 1 bt
        No such goroutine:  1
        END
```
```
    runtime-gdb_test.go:277: goroutine 1 bt failed: No such goroutine:  1
FAIL
FAIL	runtime	283.007s
```

**Comment by katiehockman** [comment] 2019-01-02 18:55
Thanks for reporting. This is a duplicate of #28679. Closing this issue.

**Closed by katiehockman** 2019-01-02 18:55 UTC
