### ISSUE TITLE
cmd/go: Add some way to work on offline Go modules

### ISSUE THREAD

**Issue by Keithcat1** [golang/go#40912] opened 2020-08-19 19:54 UTC
Currently, it's hard to work with offline Go modules.
The problem is, I don't have internet at home, so there is no way for me to make a change to the Go module I'm working on, because I can't push it to Github, which means that any projects I'm working on will continue to use the old version of my Go module.
Ideally, there would be a command that, if the current directory was part of a Go module, would update the Go module cash with any new changes / versions to the current Go module.

**Comment by mjgarton** [comment] 2020-08-19 20:05
Perhaps something like this example might help you?

`$ go mod edit -replace foo.com/bar/baz=/home/go/src/foo.com/bar/baz`

This would update your `go.mod` to refer to a local copy of `foo.com/bar/baz` instead of the usual one.

**Comment by bcmills** [comment] 2020-08-20 03:12
To get the modules offline in the first place, presumably you would `git clone` them (or similar).
This then reduces to making multiple interlocking edits to those modules.

**Comment by bcmills** [comment] 2020-08-20 03:13
Duplicate of #27542

**Closed by bcmills** 2020-08-20 03:13 UTC
Labels: modules
