### ISSUE TITLE
wiki: add examples of post-v2 module repositories

### ISSUE THREAD

**Issue by kevinburke** [golang/go#59227] opened 2023-03-24 17:14 UTC
What I would like is for users to reliably be able to download the latest version of my command line binary without having to manually look up whether it is v2, v3, v4, or any version like that, first. However I am struggling to get that to work reliably - go keeps trying to download the latest v1 tag even though the latest tagged release in my library is v4.0.0.

It would really help if each of the two options here: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher linked to a library that implemented the best practice, then users can just copy it. Is there a go.mod at the top level? Does each directory have a go.mod? How would end users reliably download the latest version of the library, how would they download the latest binary, etc.

**Comment by kevinburke** [comment] 2023-03-24 17:26
Looking at this now I think the issue is specifically for people who are trying to release command line binaries. In the wild I am seeing a lot of stuff like this

"We currently do not support go get nor go install as means of installation" https://github.com/cli/cli/issues/4353#issuecomment-924186360

Which seems pretty wild to me honestly. Note if you try to just "go get" this library at the "latest" version, it will happily download a version for you that is multiple years old at this point.

```
$ GO111MODULE=on go get github.com/cli/cli@latest
go: downloading github.com/cli/cli v1.14.0
go: added github.com/cli/cli v1.14.0
```

**Comment by kevinburke** [comment] 2023-03-24 17:31
Maybe a betterment would be if you ask for "go get ...@latest" and it starts downloads something that's not the latest major version, to proceed with the download but warn the user?

**Comment by seankhliao** [comment] 2023-03-24 18:52
Duplicate of #44550

**Closed by seankhliao** 2023-03-24 18:52 UTC
Labels: NeedsInvestigation
