### ISSUE TITLE
x/talks: modernize concurrency.slide onto avoid serving back “unexpected EOF”

### ISSUE THREAD

**Issue by Aju100** [golang/go#43455] opened 2021-01-01 05:10 UTC
Hi opensource contributors,

After learning from the Go Heroku's Waza conference entitled **Concurrency is not parallelism**. I decided to go its slide but the slide link was broken up.
![concurrency](https://user-images.githubusercontent.com/29862610/103433781-62c87900-4c1d-11eb-9e95-e2335103dd3d.png)
![links](https://user-images.githubusercontent.com/29862610/103433782-63f9a600-4c1d-11eb-8e71-2bc45d46db67.png)

I hope a lot of developers went through the video and learned it. But there might be a developer who prefers slides too for learning purposes. Having a proper link with its content can solve this issue. 

Link of the site: [Golang official blog](https://blog.golang.org/waza-talk)

**Comment by ALTree** [comment] 2021-01-01 11:04
Thanks for reporting this. It looks like it's not the link that is broken, but the rendering of presentation itself. If you go here: https://talks.golang.org/2012, these three:

- concurrency.slide
- tutorial.slide
- waza.slide

are all broken.

cc @dmitshur

**Comment by odeke-em** [comment] 2021-01-01 11:09
Hello @Aju100, welcome to the Go project! Happy New Year, and thank you for identifying this problem!

I believe that the problem is that the slides might not use the godoc format, and might be outdated, so perhaps we should modernize them. @robpike, it would be an honor for you to perhaps take a look at concurrency.slide which you created for that iconic talk, otherwise I can take a look and mail the fixes. Also cheers @dmitshur!
Thank you.

**Comment by Aju100** [comment] 2021-01-01 13:45
@odeke-em  thank you

**Comment by robpike** [comment] 2021-01-02 06:53
I believe @rsc has a tool for this.

**Comment by kortschak** [comment] 2021-01-15 07:47
There is a command for this, `present2md`, but there are a couple of problems with it; the [parsing of caption commands is broken in some conditions](#41883) and [comments are not retained](#41883). These will result in incomplete translation of tutorial.slide and waza.slide. There is also a problem dot commands without a previous blank line which won't affect any of the decks listed above.

All of these are addressed in existing CLs:

- https://go-review.googlesource.com/c/tools/+/260897
- https://go-review.googlesource.com/c/tools/+/260898
- https://go-review.googlesource.com/c/tools/+/260899

**Closed** 2021-01-21 14:16 UTC
Labels: NeedsInvestigation

**Comment by kortschak** [comment] 2021-01-21 22:32
@robpike Does this talks server need to be bumped? It is still serving text that is broken, and with titles that come from text that was removed; both of concurrency.slide and tutorial.slide are titled "This is a file." on the 2012 directory view but these lines were removed.

**Comment by dmitshur** [comment] 2021-01-21 22:34
@kortschak That is expected, the talks server needs to be redeployed. There's some work that needs to be done. We'll look into doing it possibly next week.

**Comment by robpike** [comment] 2021-01-21 22:35
"Expected," no. "Unfortunate," yes. The deployment process has rotted, it seems, and needs to be repaired. It will take a few days.
