### ISSUE TITLE
strconv: FormatFloat handles prec differently from the doc with fmt='g'

### ISSUE THREAD

**Issue by musiphil** [golang/go#25082] opened 2018-04-25 19:01 UTC
### What version of Go are you using (`go version`)?
go version go1.10.1 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

### What did you do?
`fmt.Println(strconv.FormatFloat(1.5, 'g', 6, 64))`
https://play.golang.org/p/WRHc89mjuSG

### What did you expect to see?
`1.50000`

https://golang.org/pkg/strconv/#FormatFloat says:
> The precision prec controls the number of digits […]. For 'g' and 'G' it is the total number of digits.

I gave `prec=6`, so the total number of digits should be 6.

### What did you see instead?
`1.5`

The total number of digits is 2.

**Comment by pam4** [comment] 2018-04-25 22:08
It seems to be caused by this part: https://golang.org/src/strconv/ftoa.go?s=5694:5737
```go
if prec > digs.dp {
    prec = digs.nd
}
```
If the requested precision is greater then the number of digits before the decimal point, it is set to the total number of digits.

**Comment by musiphil** [comment] 2018-05-21 18:56
Thanks, and I agree in general.

I've always been mindful of communicating the correct number of significant digits. With `fmt` and `%g` we at least have the `#` flag, but it is very unfortunate that `strconv.FormatFloat` doesn't offer any option.

Ideally, `strconv.FormatFloat` should offer such an option (and maybe support for other flags as well) and [the post-processing in `fmt`](https://golang.org/src/fmt/format.go?s=11265:12166#L483) could be simplified, offering on-par features to the users of `fmt` and `strconv.FormatFloat`. (It may not be easy without modifying the interface of `strconv.FormatFloat`, though.) Without that, I would personally favor fixing the implementation, but that would mean a small change in the behavior of current programs using it, so we may have to fix the documentation instead.

**Comment by ianlancetaylor** [comment] 2018-06-29 01:41
I don't think we should change the code, so marking this as a documentation fix.

**Comment by danicat** [comment] 2018-07-31 21:17
Hi! It seems that no one is working on this right now... have we agreed that this is just a doc change? May I do it?

**Closed** 2018-08-01 01:10 UTC
Labels: Documentation, NeedsFix, help wanted
