### ISSUE TITLE
x/tools/gopls: offer completions for package names

### ISSUE THREAD

**Issue by kzhui125** [golang/go#39715] opened 2020-06-19 06:52 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.3 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.46.0
	- a5d1cc28bb5da32ec67e86cc50f84c67cc690321
	- x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.14.4

When I create a go file in a folder such as "test1"

When I type "pa", I expect "package test" and maybe also "package main" will appear in the list.

But now there is nothing.

This is bad coding experience.

<img width="459" alt="1" src="https://user-images.githubusercontent.com/11925432/85105028-4e51ff80-b23c-11ea-99d5-d7073a36d117.png">

**Comment by stamblerre** [comment] 2020-06-19 18:57
Transferred. I thought we already had an open issue for that, but I guess not.

**Comment by muirdm** [comment] 2020-08-11 03:21
Dupe of #34008?

**Comment by stamblerre** [comment] 2020-08-11 03:56
Yes I think so, thanks. Closing.

**Closed by stamblerre** 2020-08-11 03:56 UTC
Labels: FeatureRequest, Tools, gopls, help wanted
