### ISSUE TITLE
mobile: don't depend on docker data volumes for builds

### ISSUE THREAD

**Issue by rakyll** [golang/go#9372] opened 2014-12-17 23:30 UTC
`docker -v` works only on Linux and silently fails if you run a docker client on a non-Linux machine. It creates confusion for those who are using the following command as instructed as on the README to build their packages.

```
docker run -v $GOPATH/src:/src mobile /bin/bash -c 'cd /src/your/project && ./make.bash'
```

We should copy the package to be built and its dependencies from the host to the container. But, Docker provides no additional tools to help us with this issue.

One alternative is to vendor the dependencies and use ONBUILD ADD to build an app builder image. It will only work if all dependencies are vendored under the Dockerfile's directory, because Docker rejects to add files from outer contexts. https://docs.docker.com/reference/builder/#add

```
FROM mobile:latest

ONBUILD ADD . /src/your/project/

RUN cd /src/your/project/ && ./all.bash
```

Then the user can do a docker cp to retrieve the apk.

**Comment by hyangah** [comment] 2015-02-10 02:45
The doc was updated and the docker file was changed to require the mounted volume to be accessible.
Soon we will not depend on docker image for build as gomobile tool becomes available. 
Duplicate of  golang/go#9508

**Closed by hyangah** 2015-02-10 02:45 UTC
Labels: repo-mobile
