### ISSUE TITLE
x/playground: Add keyboard event listener for commenting 

### ISSUE THREAD

**Issue by 201702083** [golang/go#49817] opened 2021-11-27 11:49 UTC
It's not a big deal. but inconvenient.
It would be nice to have keyboard commands rather than manually commenting them in the playground.

### What did you do?
I tried trigger a keyboard event ( ctrl/cmd + / ) to comment out some code.

### What did you expect to see?

Commented out code

### What did you see instead?

Nothing change.

**Comment by seankhliao** [comment] 2021-11-27 13:54
Duplicate of #39152

**Closed by seankhliao** 2021-11-27 13:54 UTC

**Comment by 201702083** [comment] 2021-11-27 15:09
Oh my bad.
I'm interested in trying to fix this.
I’ll give you pr soon.
