### ISSUE TITLE
cmd/go: replace directive causes build to take 30 seconds

### ISSUE THREAD

**Issue by levblanc** [golang/go#29920] opened 2019-01-24 16:07 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/levblanc/go/bin"
GOCACHE="/Users/levblanc/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/levblanc/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/levblanc/projects/x-crypto-issue/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yk/p1tyzt2n5m38k09cbsgktxhh0000gn/T/go-build141072027=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

- imported `golang.org/x/crypto/bcrypt` in my program

- alias `golang.org/x/crypto@v0.0.0` to `github.com/golang/crypto@latest` with `go mod`

Here is the [repo to reproduce the problem](https://github.com/levblanc/x-crypto-issue).

You can find detailed description and my thoughts in the README file.

### What did you expect to see?
`go run main.go` works as normal.

### What did you see instead?

`go run main.go` takes around 30 seconds to print out the result of my simple program,

while `go run -mod=vendor main.go` works well.

**Comment by bcmills** [comment] 2019-01-24 20:50
Duplicate of #27859.

**Closed by bcmills** 2019-01-24 20:50 UTC
Labels: NeedsInvestigation, modules
