### ISSUE TITLE
encoding/json: Decoding returns error when case-insensitive keys overlap and not all struct fields defined

### ISSUE THREAD

**Issue by sdcoffey** [golang/go#54404] opened 2022-08-11 23:19 UTC
### What version of Go are you using (`go version`)?

<pre>
1.18
</pre>

### Does this issue reproduce with the latest release?

Yes, reproducible with go 1.19

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/steve/Library/Caches/go-build"
GOENV="/Users/steve/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/steve/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/steve/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/steve/yuzu/crypto-stream-source/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/q_/381gr8255wl427x33rzsyvk80000gn/T/go-build2527350202=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### [Go Playground](https://go.dev/play/p/2uSw7XnisQw)

Given this block of JSON (example taken from a Binance websocket payload):
```json
{
  "e": "24hrTicker", 
  "E": 123456789
}
```

encoding/json will return an error while unmarshaling into this struct:
```go
type UnsuccessfulUnmarshal struct {
	TimeStamp int64 `json:"E"`
}
```

but not this struct:
```go
type SuccessfulUnmarshal struct {
	Event     string `json:"e"`
	TimeStamp int64  `json:"E"`
}
```

### What did you expect to see?

No error returned when only some of the fields in the json payload are defined in the destination struct

### What did you see instead?

This error returned:
```
json: cannot unmarshal string into Go struct field UnsuccessfulUnmarshal.E of type int64
```

**Comment by seankhliao** [comment] 2022-08-11 23:53
Duplicate of #14750

**Closed by seankhliao** 2022-08-11 23:53 UTC
