### ISSUE TITLE
net/http: memory leak due to a large number of items in transport.reqCanceler

### ISSUE THREAD

**Issue by huozby** [golang/go#61708] opened 2023-08-02 09:15 UTC
net/http:  memory leak due to a large number of items in transport.reqCanceler

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.10 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/xxx/codes/go/bin"
GOCACHE="/home/xxx/.cache/go-build"
GOENV="/home/xxx/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/xxx/codes/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xxx/codes/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.10"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/xxx/codes/transport-memory-leak/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3608446700=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

When using http.ReverseProxy  to build http ReverseProxy,  We found memory leak in http.Transport in certain case.  

There is a client , proxy and server as bellow, :

```shel
client ----->  proxy -----> server
```

reproduce condition:
1. client concurrently visit proxy（maybe 200+ concurrency）.
2. server receive request head  and return response immediately(server response before receive entired request body).

proxy code:
https://go.dev/play/p/dRzdohisHy5?v=goprev

server code:
https://go.dev/play/p/iyBuNbJWKVi?v=goprev

client code:
https://go.dev/play/p/7gPDzt9vrkw?v=goprev

### What did you expect to see?
http.ReverseProxy  perform well and has no memory leak.

### What did you see instead?
proxy error logs:
```
2023/08/02 10:37:52 httputil: ReverseProxy read error during body copy: read tcp 127.0.0.1:53946->127.0.0.1:9090: use of closed network connection
```

PProf file shows that memory leak in transport:
![image-20230802105027310](https://github.com/golang/go/assets/17507543/6bac824a-542d-4649-bdda-4a7fe944296f)

![image-20230802105545485](https://github.com/golang/go/assets/17507543/268ee649-345a-4ab5-bd79-0b1c382a0ca5)

![image-20230802105601327-1690966447945-3](https://github.com/golang/go/assets/17507543/2cd1a866-8cea-4573-88f6-3486e29201b4)

dlv debug info shows the memory leak is caused by reqCanceler.  1900+ items in the reqCanceller map should be gc  after we stop client, but after a long time, they are still there.
![image-20230802105151992](https://github.com/golang/go/assets/17507543/7940042b-9c48-4988-9b9f-fca95356973d)

![image-20230802105232164](https://github.com/golang/go/assets/17507543/9bda5ced-e60d-43a5-98d7-8f2e1a6ed63d)

a sample request(proxy -> server) diagram of tcpdump.
![image](https://github.com/golang/go/assets/17507543/82c82106-9aa4-4430-8887-47c2ad3be7df)

Source code and some files for further debug:
[transport-memory-leak.zip](https://github.com/golang/go/files/12237902/transport-memory-leak.zip)

**Comment by mauri870** [comment] 2023-08-02 12:08
Issue https://github.com/golang/go/issues/51354 also claims leaks in reqCanceler under certain conditions

If you get the chance try to reproduce the issue with this patch, I believe this is the fix the author of the other issue suggested:

```
diff --git a/src/net/http/transport.go b/src/net/http/transport.go
index c07352b018..d30eb79508 100644
--- a/src/net/http/transport.go
+++ b/src/net/http/transport.go
@@ -2248,7 +2248,7 @@ func (pc *persistConn) readLoop() {
 			}
 		case <-rc.req.Cancel:
 			alive = false
-			pc.t.CancelRequest(rc.req)
+			pc.t.cancelRequest(rc.cancelKey, errRequestCanceled)
 		case <-rc.req.Context().Done():
 			alive = false
 			pc.t.cancelRequest(rc.cancelKey, rc.req.Context().Err())

```

**Comment by AlexanderYastrebov** [comment] 2023-08-02 22:25
I've created #61724 to fix #51354

The test `TestCancelRequestWithBodyWithChannel` I added with such change
```diff
diff --git a/src/net/http/transport.go b/src/net/http/transport.go
index d30eb79508..fb3f9e168d 100644
--- a/src/net/http/transport.go
+++ b/src/net/http/transport.go
@@ -26,6 +26,7 @@ import (
        "net/textproto"
        "net/url"
        "reflect"
+       "runtime"
        "strings"
        "sync"
        "sync/atomic"
@@ -2248,6 +2249,9 @@ func (pc *persistConn) readLoop() {
                        }
                case <-rc.req.Cancel:
                        alive = false
+                       for _, v := range pc.t.reqCanceler {
+                               fmt.Printf(">> %v\n", runtime.FuncForPC(reflect.ValueOf(v).Pointer()).Name())
+                       }
                        pc.t.cancelRequest(rc.cancelKey, errRequestCanceled)
                case <-rc.req.Context().Done():
                        alive = false
```
outputs `>> net/http.(*persistConn).cancelRequest-fm` which matches the description so there are chances it will fix this one as well.

**Comment by hzzzzzb** [comment] 2023-08-03 03:12
@mauri870 @AlexanderYastrebov Thanks a lot for your great work. I test the solution you mentioned above, but it doesn't work. 
The result shows:
![image-20230803104122705](https://github.com/golang/go/assets/17507543/f0b4af57-151b-42d7-9ccb-82fcb7f563db)

![image-20230803104244941](https://github.com/golang/go/assets/17507543/0763516e-7bae-4c88-b51d-cb9d9701169c)

Maybe my case is much more complicated. My team members and I read go net http source code, the memory leak could happen in src/net/http/transport.go:2230. 

```go
		// Before looping back to the top of this function and peeking on
		// the bufio.Reader, wait for the caller goroutine to finish
		// reading the response body. (or for cancellation or death)
		select {
		case bodyEOF := <-waitForBodyRead:
			replaced := pc.t.replaceReqCanceler(rc.cancelKey, nil) // before pc might return to idle pool
			alive = alive &&
				bodyEOF &&
				!pc.sawEOF &&
				pc.wroteRequest() &&
				replaced && tryPutIdleConn(trace)
			if bodyEOF {
				eofc <- struct{}{}
			}
		case <-rc.req.Cancel:
			alive = false
			pc.t.CancelRequest(rc.req)
		case <-rc.req.Context().Done():
			alive = false
			pc.t.cancelRequest(rc.cancelKey, rc.req.Context().Err())
		case <-pc.closech:  // memroy may leak here. pc closed, rc.cancelKey would never be removed.
			alive = false
		}
```

there could be a unexpected case： case bodyEOF := <-waitForBodyRead is still blocked(the caller goroutine is reading the response body.)， pconn is closed by somewhere. Thus, rc.cancelKey would never clean.

pc.closech would be set here:  src/net/http/transport.go:2716 which is called by src/net/http/transport.go:2696. There several callers call pc.close, which one could cause the problem?

we guess that in src/net/http/transport.go:2418 calls pc.close(err).  In a rare case(or special timings),  there is a writeErr(http: invalid Read on closed) , the request body not completely send to server, meanwhile the caller goroutine is reading the response body, pc.close(err) is called(could it be possible?). 

```go
			pc.writeErrCh <- err // to the body reader, which might recycle us
			wr.ch <- err         // to the roundTrip function
			if err != nil {
				pc.close(err)
				return
			}
```

In addition，we found a possible solution to solve this memory leak problem, bu we are not sure the impact(would it impact normal request?). Maybe it is safe to remove rc.cancelKey here,  for pconn has already been closed. 

```go
		// Before looping back to the top of this function and peeking on
		// the bufio.Reader, wait for the caller goroutine to finish
		// reading the response body. (or for cancellation or death)
		select {
		case bodyEOF := <-waitForBodyRead:
			replaced := pc.t.replaceReqCanceler(rc.cancelKey, nil) // before pc might return to idle pool
			alive = alive &&
				bodyEOF &&
				!pc.sawEOF &&
				pc.wroteRequest() &&
				replaced && tryPutIdleConn(trace)
			if bodyEOF {
				eofc <- struct{}{}
			}
		case <-rc.req.Cancel:
			alive = false
			pc.t.CancelRequest(rc.req)
		case <-rc.req.Context().Done():
			alive = false
			pc.t.cancelRequest(rc.cancelKey, rc.req.Context().Err())
		case <-pc.closech: // memroy may leak here. pc closed, rc.cancelKey would never be removed.
			alive = false
                        pc.t.replaceReqCanceler(rc.cancelKey, nil) // remove rc.cancelKey when pconn has been closed
		}
```
In out test, this change indeed help to solve the problem,  but it is really ok or is there other better solutions?

![image-20230803105217512](https://github.com/golang/go/assets/17507543/0f2b63d6-c8f0-4449-90d3-b4724b2abbce)

![image-20230803105254473](https://github.com/golang/go/assets/17507543/4c14adad-8d8c-4a34-8280-79cf679d45ae)

**Comment by hzzzzzb** [comment] 2023-08-03 03:58
> I encountered the same issue while writing a forward HTTP proxy. using transport.DisableKeepAlives = true temporarily resolved the memory leak issue. ![image](https://user-images.githubusercontent.com/47804091/257988447-b26afe5d-dd7f-4625-bb2c-568de8946688.png)

memory leak of transport may has several cause, you could use gcore <pid> to get core dump file of the process. And use dlv core <app_binary> core.<pid> to analyse the memory problem, to find which objects has great numbers and it is unusual.  

In this issues(in my case), I have test the `DisableKeepAlives:     true,` option of http.Transport, the memory still keep growing.

**Comment by AlexanderYastrebov** [comment] 2023-08-03 08:45
@hzzzzzb 
>  In a rare case(or special timings), there is a writeErr(http: invalid Read on closed) , the request body not completely send to server, meanwhile the caller goroutine is reading the response body, pc.close(err) is called(could it be possible?).

I think you are right.
I've modified your proxy to print reqCanceler
```go
func getUnexportedFieldLen(field reflect.Value) int {
	return reflect.NewAt(field.Type(), unsafe.Pointer(field.UnsafeAddr())).Elem().Len()
}

func countReqCanceler(t *http.Transport) int {
	return getUnexportedFieldLen(reflect.ValueOf(t).Elem().FieldByName("reqCanceler"))
}

...
	reverseProxy.ErrorLog = log.New(io.Discard, "", 0)
	var requests atomic.Int64

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		reverseProxy.ServeHTTP(w, r)

		n := requests.Add(1)
		if n%1000 == 0 {
			fmt.Println("proxy: reqCanceler:", countReqCanceler(t))
		}
	})
...
```
and the number grows even with #51354 fix but stops growing with
```go
		case <-pc.closech:
			alive = false
			pc.t.cancelRequest(rc.cancelKey, errRequestCanceled)
                        // pc.t.replaceReqCanceler(rc.cancelKey, nil) // or this
```

I've added a second channel to send close error, it is indeed ErrBodyReadAfterClose, I correlated it to
https://github.com/golang/go/blob/ed8cbaf6ac58120c7171dadaaa091f031712c6d2/src/net/http/transport.go#L2422-L2424
where it calls pc.close 
https://github.com/golang/go/blob/ed8cbaf6ac58120c7171dadaaa091f031712c6d2/src/net/http/transport.go#L2444-L2449

I think the problem could be reverseproxy specific due to the way it works similar to #46866

I could not come up with a reproducer test yet that we'd need to make a proper fix.

> memory leak of transport may has several cause

Indeed, see e.g. #50798 and #43966

**Comment by ianlancetaylor** [comment] 2023-08-04 19:44
CC @neild @bradfitz

**Comment by WenlongWang** [comment] 2023-08-08 10:41
any update on this ?

**Closed** 2024-03-18 19:34 UTC
Labels: NeedsInvestigation
