### ISSUE TITLE
golang can not define func for eisxt list type 

### ISSUE THREAD

**Issue by epowsal** [golang/go#70840] opened 2024-12-14 01:09 UTC
### Go version

go 1.23.1 windows amd64

### Output of `go env` in your module/workspace:

```shell
not need
```

### What did you do?

define func for old code with out change too many

type ints = []int

func (a ints) dd() int {
	return len(a)
}

func TestIntersect1(t *testing.T) {
	a := []int{8, 73, 1, 53, -2, 56, -93}
	b := []int{56, 8, 56, -2, 42, 96, 184}
	fmt.Println(a.dd())
}

or

func (a []int) dd() int {
	return len(a)
}

func TestIntersect1(t *testing.T) {
	a := []int{8, 73, 1, 53, -2, 56, -93}
	b := []int{56, 8, 56, -2, 42, 96, 184}
	fmt.Println(a.dd())
}

### What did you see happen?

error invalid receiver type

### What did you expect to see?

I need this function so much. please add it.

**Comment by seankhliao** [comment] 2024-12-14 01:26
Please do not spam the issue tracker. This is by design.

Duplicate of #70839

**Closed by seankhliao** 2024-12-14 01:26 UTC
