### ISSUE TITLE
callgraph: The result of callgraph, like function entity: some_func_name#1, is it anonymous function? Or others?

### ISSUE THREAD

**Issue by DeWuwo** [golang/go#47571] opened 2021-08-06 07:20 UTC
### What version of Go are you using (`go version`)?
1.16.4
<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by ALTree** [comment] 2021-08-06 07:39
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2021-08-06 07:39 UTC
