### ISSUE TITLE
cmd/go: improve error message for package not found?

### ISSUE THREAD

**Issue by thatreguy** [golang/go#32096] opened 2019-05-17 07:24 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12.4
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 16.04.6/amd64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/.go/src/github.com/firebase/firebase-admin-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build012231754=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

The following is my tree:
snippets/
├── constants
│   └── constants.go
├── libs
│   ├── auth.go
│   ├── db.go
│   ├── init.go
│   ├── messaging.go
│   └── storage.go
└── snippets.go
I was trying to import constants from snippets.go:

`cat snippets.go`
```
package main
import (
	"snippets/constants"
)
.
.
.
```
And did:
`go build -x -v`

### What did you expect to see?
No error or verbose output from go build

### What did you see instead?
Quite unhelpful output:
build firebase.google.com/go/snippets: cannot load snippets/constants: cannot find module providing package snippets/constants

Now for whatever reason my import might have failed, I can understand that. But I would at least like a detailed explanation from go build. (In fact, the same is true to go get, go run etc.)

**Comment by FiloSottile** [comment] 2019-05-17 16:31
I am guessing your module here is called `firebase.google.com/go/snippets`, not `snippets`, so the import should have been `firebase.google.com/go/snippets/constants`. Not sure how `go build` could give a better error message here without guessing.

/cc @bcmills

**Comment by jayconrod** [comment] 2019-05-30 16:59
@thatreguy You said your tree contains a directory `snippets/constants`. Where is this directory in relation to `/root/.go/src/github.com/firebase/firebase-admin-go/go.mod`? How was it created?

This is not something that would work in module mode: the Go command won't search local directories for imports outside of the main module. This worked for manually created `GOPATH` directories, but I'm not sure we can provide good diagnostics for that case.

**Comment by bcmills** [comment] 2019-05-31 16:18
For the particular case where the import path doesn't start with a leading dot, there is no way such a module can exist without using a `replace` directive.

**Comment by bcmills** [comment] 2019-05-31 16:23
Duplicate of #30723

**Closed by bcmills** 2019-05-31 16:23 UTC
Labels: NeedsInvestigation, modules
