### ISSUE TITLE
net/mail: Reading messages with empty bodies returns error (EOF)

### ISSUE THREAD

**Issue by jspy** [golang/go#15632] opened 2016-05-10 19:14 UTC
go version go1.6.1 linux/amd64

Can't read mail messages which are empty. ReadMessage() returns with err = "EOF"

This is due to net/textproto/ReadMIMEHeader -> readContinuedLineSlice() returning an EOF.

Example here:
https://play.golang.org/p/6AYSIRzlwE

Note that mail clients which produce these mail messages are available in the wild, and this specific bug/implementation choice was produced by:

X-Mailer: Apple Mail (2.3124)

A simple fix would probably be to let ReadMIMEHeader in net/textproto/reader.go check if the buffer is empty or not around line 480 instead of just seeing if len(kv) == 0.

**Comment by bradfitz** [comment] 2016-05-10 19:28
I don't think this is a bug. It looks like it's working as intended: the headers are truncated if it doesn't end with a blank line, so it's reporting an error.

Maybe it should return UnexpectedEOF instead of EOF, but not success.

How did you get that input? (Apple Mail, yes, but how did you extract it for the unit test?)

**Comment by bradfitz** [comment] 2016-06-29 21:20
Closing due to lack of reply.

**Closed by bradfitz** 2016-06-29 21:20 UTC
Labels: WaitingForInfo
