### ISSUE TITLE
website: move to App Engine flexible

### ISSUE THREAD

**Issue by broady** [golang/go#21628] opened 2017-08-25 20:56 UTC
Most of the time, the latest version of Go isn't available on GAE. That causes problems, like with #21601.

We should move it to GAE flexible and/or GKE, where we can just run a container and therefore have godoc built by the same version of Go as it is serving docs for.

/cc @bradfitz

**Comment by agnivade** [comment] 2019-02-21 07:29
ping @dmitshur. AFAIU, the latest website runs on GAE flex. https://go.googlesource.com/website/+/refs/heads/master/cmd/golangorg/app.prod.yaml

**Comment by dmitshur** [comment] 2019-02-21 13:59
This issue looks like a forgotten duplicate of #27205. Yes, the website runs on [App Engine Flexible Environment](https://cloud.google.com/appengine/docs/flexible/) as of https://github.com/golang/go/issues/27205#issuecomment-435172401, so this is done.

**Closed by dmitshur** 2019-02-21 13:59 UTC
Labels: Documentation
