### ISSUE TITLE
website: long TTFB wait for /pkg/*

### ISSUE THREAD

**Issue by mark-rushakoff** [golang/go#27057] opened 2018-08-17 18:01 UTC
There was a previous mailing list post at https://groups.google.com/forum/#!topic/golang-nuts/fFEuIHf6NWE about this issue. @broady fixed it once back in June but it's happening again, as @stevenh mentioned about a week ago. 

Just now, with Chrome's network profiler open, when I load https://golang.org/pkg/net/http/, I see waiting TTFB at 5.94s; loading https://golang.org/pkg/encoding/json/ spent 3.62s waiting TTFB. But then if I load another package's documentation in the same tab, it seems to load acceptably fast.  Sometimes other packages in a new tab load quickly, so I don't understand if it's actually intermittent, or if Chrome is doing something that speeds up subsequent connections, or something else altogether.

Is there other information I or anyone else can gather to help with this issue?

**Comment by benhoyt** [comment] 2018-08-27 12:44
I've definitely been noticing this too. I don't know what powers the Go documentation, but it seems to me it could be a very simple and super-fast static site hosted via S3+Cloudfront (or the Google Cloud equivalents).

**Comment by ctrezevant** [comment] 2018-08-30 05:44
I'd imagine the package docs on golang.org are powered by the [godoc](https://github.com/golang/tools/tree/master/godoc) tool's http server, no?

**Comment by andybons** [comment] 2018-08-30 17:44
@ctrezevant that’s correct.

We are hitting OOM errors on GAE Classic. I’m working on the issue. Moving to flex will help with this (https://github.com/golang/go/issues/27205).

**Comment by benhoyt** [comment] 2018-08-30 18:02
Isn't the documentation very static? Seems like the fewer moving parts here the better. Could it be output to HTML once and then hosted on a static store (eg: S3) behind a CDN (eg: Cloudfront)? This would make it really stable and fast.

**Comment by ctrezevant** [comment] 2018-08-30 18:33
@andybons Ok, awesome! 

Also, the other commentors here make a good point- you could realize significant performance gains if you were using static pages for docs right now, though I have another suggestion that would allow you to keep your current godoc workers and leverage some features from GAE/GCP to improve performance.

Since you're already running on GAE (and leveraging GLB, which I'm assuming based on golang.org's response headers), my recommendation would be to leverage the [Cloud CDN integration](https://cloud.google.com/cdn/docs/using-cdn) of Google Load Balancer. This will allow GLB to automatically begin caching common requests from your load balancer, and serve the responses to those from Cloud CDN.  

You can set this up fairly easily from your backend load balancer definition for golang.org, by ticking the “Enable Cloud CDN” box. From then on GLB/CDN should handle all the caching transparently. Ultimately, this configuration would allow you to continue running godoc workers upstream in GAE, but significantly improve performance while reducing load on your actual godoc servers.

The only caveat I can see is that you'd most likely have to make some patches to godoc to ensure that the responses it generates suit the [Cacheability criteria](https://cloud.google.com/cdn/docs/caching) for Cloud CDN (as responses from Godoc currently lack any `Content-Length`, `Transfer-Encoding`, `Cache-Control`, or `Content-Range` headers). However, godoc's web server should really be responding with some caching headers, anyways (or at least an etag!), since these are vital to any caching web infrastructure and I'd imagine are the primary reason that none of Godoc's responses are getting cached (I may open an issue/PR for this at a later time). 

Thanks again!

**Comment by agnivade** [comment] 2018-08-30 18:37
It is not static. 

- There is a search functionality. 
- Template logic which fills up different templates which finally serve the pages.
-  And other routing logic which needs Go code.

The advantage of having everything in a single binary is simplicity. You can locally run godoc very easily. Separating out html and assets, and having a separate binary for business logic is going to unnecessarily complicate things.

**Comment by benhoyt** [comment] 2018-08-30 18:40
Fair enough @agnivade. What about @ctrezevant's suggestion about putting a caching CDN in front for maximum performance?

**Comment by bcmills** [comment] 2018-09-04 19:18
> What about @ctrezevant's suggestion about putting a caching CDN in front for maximum performance?

The usual fix for OOM issues is flow control, not (just) caching.

(Caching helps with overall throughput, which reduces _average_ load, but OOMs are caused by _instantaneous_ load.)

**Comment by broady** [comment] 2018-10-03 01:48
Should be fast again now.

**Closed by broady** 2018-10-03 01:48 UTC
Labels: NeedsFix
