### ISSUE TITLE
proposal: ease importing packages belonging to the same module

### ISSUE THREAD

**Issue by m-kru** [golang/go#62259] opened 2023-08-24 08:57 UTC
Importing packages belonging to the same module is verbose as it requires providing full path with module prefix. In  the case of local modules the prefix is usually short, but in the case of remote modules (for example, the ones placed on github) it is usually long.  What is more, opening a file and determining which imports belong to the same module and which comes from an external dependency takes much more time than it could as one needs to eyeball the module prefixes.

Let me introduce following module structure to ease the reasoning:
```
prj/
├── go.mod
├── internal
│   └── priv
│       └── priv.go
├── main.go
└── pub
    └── pub.go
```
To import `pub` and `priv` packages one needs to type:
```go
import (
	"prj/pub"
	"prj/internal/priv"
)
```
The module is local module, so its prefix is short, but in the case of remote module it would be something like:
```go
import (
	"github.com/organization-name/repo-name/pub"
	"github.com/organization-name/repo-name/internal/priv"
)
```

I can see few alternatives that can ease importing packages belonging to the same module

1. Make go search module directories to find a package if it is not found in other locations. 
In our example a code like this:
```go
import (
	"pub"
	"internal/priv"
)
```
would success instead of returning:
```
main.go:7:2: package internal/priv is not in GOROOT (/usr/local/go/src/internal/priv)
main.go:6:2: package pub is not in GOROOT (/usr/local/go/src/pub)
```

2. Allow adding some prefix to the package path indicating that the package belongs to the same module, for example three dots `...`.
```go
import (
	".../pub"
	".../internal/priv"
)
```

3. At least allow importing internal packages without providing module path. The `internal` directory is already treated in a special way. The following code would compile:
```go
import (
	"prj/pub"
	"internal/priv"
)
```

**Comment by seankhliao** [comment] 2023-08-24 10:28
Duplicate of #20883

**Closed by seankhliao** 2023-08-24 10:28 UTC
Labels: Proposal
