### ISSUE TITLE
cmd/go: list reports packages as stale immediately after their "go get"

### ISSUE THREAD

**Issue by siebenmann** [golang/go#23797] opened 2018-02-12 18:42 UTC
### What version of Go are you using (`go version`)?

``go version devel +c52e27e68d Sun Feb 11 20:41:48 2018 +0000 linux/amd64``

### Does this issue reproduce with the latest release?

This doesn't happen on Go 1.9.4.

### What operating system and processor architecture are you using (`go env`)?

````
GOARCH="amd64"
GOOS="linux"
````

### What did you do?

Here is a simple reproduction, showing a just fetched and built command package being reported as stale due to a stale dependency.

````
$ export GOPATH=/tmp/gp
$ mkdir $GOPATH
$ go get mvdan.cc/sh/cmd/shfmt
$ go list -f '{{.ImportPath}} - {{.Stale}} - {{.StaleReason}}' mvdan.cc/sh/cmd/shfmt
mvdan.cc/sh/cmd/shfmt - true - stale dependency: mvdan.cc/sh/fileutil
````

This appears to happen for anything that has dependencies outside of the core packages, including dependencies to golang.org/x packages.

**Comment by mvdan** [comment] 2018-02-13 09:10
Seems related to whether or not `go install` was called on the dependencies directly:

```
$ go install -v mvdan.cc/sh/cmd/shfmt
$ go list -f '{{.ImportPath}} - {{.Stale}} - {{.StaleReason}}' mvdan.cc/sh/cmd/shfmt
mvdan.cc/sh/cmd/shfmt - true - stale dependency: mvdan.cc/sh/fileutil
$ go install -v mvdan.cc/sh/fileutil
$ go list -f '{{.ImportPath}} - {{.Stale}} - {{.StaleReason}}' mvdan.cc/sh/cmd/shfmt
mvdan.cc/sh/cmd/shfmt - false -
```

**Comment by mvdan** [comment] 2018-02-13 09:12
`go build -v mvdan.cc/sh/fileutil` does not seem to fix it, though.

**Comment by mvdan** [comment] 2018-02-13 09:49
Seems like the `.a` file for the library isn't being written to by `go install` when called on the package that imports the library. But, if `go install` is called directly on the library, it does write the `.a` file.

`useCache` on the library package also returns different results on both of these cases - it's returns true only when `go install` was called on the library directly.

I've tried debugging this further and possible fixes, but I'm not sure how this is supposed to behave. @rsc, thoughts?

**Comment by bradfitz** [comment] 2018-02-13 16:04
I'll actually promote this to Go 1.10 because it involves the new build cache (potentially). I'll let Russ decide whether it's important for 1.10.

**Comment by bradfitz** [comment] 2018-02-14 19:15
We decided in the release meeting to think about this for Go 1.10.1.

**Comment by andybons** [comment] 2018-03-27 21:50
Bumping to 1.10.2 as there doesn't appear to be a fix yet.

**Comment by rsc** [comment] 2018-04-18 19:10
Duplicate of #23818, #24558.

**Closed by rsc** 2018-04-18 19:10 UTC
Labels: NeedsInvestigation
