### ISSUE TITLE
website/doc: documentation for pkg builtin is broken

### ISSUE THREAD

**Issue by caiofilipini** [golang/go#21613] opened 2017-08-25 12:43 UTC
Looks like the docs for the `builtin` package are broken in https://golang.org/pkg/builtin/.

I'm not sure this is the right place for filing this issue, please point me in the right direction if that's the case. I've also skipped most of the questions in the issue template because it isn't related to running `go` itself.

### What did you do?

Tried to browse the documentation for the `builtin` package in https://golang.org/pkg/builtin/.

### What did you expect to see?

The documentation for the builtin package.

### What did you see instead?

```
/src/builtin/builtin.go:88:11: expected type, found '=' (and 1 more errors)
```

Screenshot including the URL:

![screen shot 2017-08-25 at 14 38 17](https://user-images.githubusercontent.com/47155/29714358-253fe496-89a3-11e7-8e9a-dbc309585b67.png)

**Comment by martisch** [comment] 2017-08-25 12:44
Duplicate of #21601.

**Closed by martisch** 2017-08-25 12:44 UTC
Labels: Documentation

**Comment by caiofilipini** [comment] 2017-08-25 13:18
Thanks for checking, @martisch, and sorry for the noise!
