### ISSUE TITLE
container/list: Init followed by Remove (of invalid Element) leads to negative Len

### ISSUE THREAD

**Issue by ktalg** [golang/go#70022] opened 2024-10-24 03:01 UTC
### Go version

go version go1.22.5 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='amd64'

GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'

GOOS='linux'


GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'

GOVCS=''
GOVERSION='go1.22.5'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'

GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1426153306=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

https://go.dev/play/p/OK0kMoF1XR9

```go
func main() {
	l := list.New()
	l.PushBack(1)
	front := l.Front()
	l.Init()
	fmt.Println("list len:", l.Len(), "front is nil:", l.Front() == nil)
	l.Remove(front)
	fmt.Println("list len:", l.Len(), "front is nil:", l.Front() == nil)
}

```

### What did you see happen?

list len: 0 front is nil: true
list len: -1 front is nil: false

### What did you expect to see?

I expected that after reinitializing the list with l.Init(), attempting to remove an element that was previously in the list would either do nothing or result in a runtime error, and the list length would remain at 0.

**Comment by adonovan** [comment] 2024-10-24 17:49
The Init method has an undocumented postcondition: all elements of the list are now invalid.

It could dynamically assert this condition by adding a counter to every element and to the list itself, and making every operation check that they are consistent. But that adds a word to every Element.

Alternatively, the List structure could have all its state in an indirect "listImpl" struct, and each Element could point to this structure instead of the List itself. Init would cause the List to refer to a new listImpl. The cost of this would be only one extra allocation per non-empty List.

**Comment by seankhliao** [comment] 2024-10-24 18:00
Duplicate of #39014

**Closed by seankhliao** 2024-10-24 18:00 UTC
