### ISSUE TITLE
x/tools/gopls: autocomplete - unstoppable import 

### ISSUE THREAD

**Issue by festum** [golang/go#54296] opened 2022-08-05 15:58 UTC
### What version of Go are you using (`go version`)?
<pre>
$ go version
1.19
</pre>

It happens since `1.18.4`

### Does this issue reproduce with the latest release?

Yes

```
gopls version
golang.org/x/tools/gopls v0.9.1
    golang.org/x/tools/gopls@v0.9.1 h1:SigsTL4Hpv3a6b/a7oPCLRv5QUeSM6PZNdta1oKY4B0=
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN="/home/festum/.go/bin"
GOCACHE="/home/festum/.cache/go-build"
GOENV="/home/festum/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/festum/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/festum/.go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/festum/Repo/LeetCode-Go/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3678140175=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Simply using more than one dependency.

### What did you expect to see?

Not freezing vscode

### What did you see instead?

`gopls` keep importing the same packages 

![Peek 2022-08-05 17-43](https://user-images.githubusercontent.com/1211864/183115476-eadf0437-7794-4aa1-865d-dbcc9267a0fe.gif)

**Comment by findleyr** [comment] 2022-08-05 16:35
Woah. I've never seen anything like that before. I'm not sure what mechanism would even cause a loop like that: perhaps some interaction with auto-saving in vs code.

Needless to say, we'd really like to get to the bottom of this. If you could help us investigate it would be extremely helpful.

To start, are you able to capture rpc logs for a minimal repro?
https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information

**Comment by findleyr** [comment] 2022-08-05 16:49
BTW, when I initially read the issue, I thought you said "It happens since 0.8.4" (which is a recent gopls version), but you said It happens since 1.18.4, which is a recent *go* version. Are you sure this started happening when you updated Go? I would be very surprised if that were the case.

**Comment by findleyr** [comment] 2022-08-05 16:56
Could you also please share your vscode settings.json, and whether or not you have any other extensions installed that may format Go files?

**Comment by findleyr** [comment] 2022-08-08 13:25
Putting this in the v0.10.0 milestone as given more information we'd like to fix this bug expediently.

However, since we can't repro it will be very hard for us to fix this without more information.

**Comment by findleyr** [comment] 2022-08-10 19:32
If the issue is resolved by a vscode update, that points to bad interaction of gopls edits with other vs code edits.

Is it reliably reproducible with the older version of vs code?

**Comment by festum** [comment] 2022-08-16 15:10
Yup, still reproducible with older vscode
![Peek 2022-08-16 17-08](https://user-images.githubusercontent.com/1211864/184914442-b2fd7438-54fd-4657-a8b0-4180edbb3bf9.gif)

**Comment by findleyr** [comment] 2022-09-08 16:46
Thanks for confirming. I think this is probably a VS Code issue, as AFAIK there's nothing in gopls that would lead to this behavior. Please reopen if this is reproducible at the latest VS Code version.

**Closed by findleyr** 2022-09-08 16:46 UTC
Labels: WaitingForInfo, gopls, Tools
