### ISSUE TITLE
net/http: flake in TestCancelRequestWhenSharingConnection

### ISSUE THREAD

**Issue by mknyszek** [golang/go#54909] opened 2022-09-06 21:30 UTC
[2022-09-03T18:21:45-a0f0582/windows-arm64-10](https://build.golang.org/log/dafdc74185dddb68c672771658eecf09c79233a7)

CC @neild

**Comment by bcmills** [comment] 2022-09-08 14:39
Given that it's on `windows/arm64`, I suspect a platform bug — there seem to be a lot of issues remaining in the `windows/arm64` network stack (CC @qmuntal).

See also #53584, #51147, #51080; hopefully many of these will be addressed by #53541.

**Comment by bcmills** [comment] 2022-10-26 16:41
Duplicate of #55226

**Comment by bcmills** [comment] 2022-10-26 16:42
(Dup'd to that one even though it is newer because it already has a `watchflakes` pattern.)

**Closed by bcmills** 2022-10-26 16:41 UTC
Labels: OS-Windows, NeedsInvestigation, arch-arm64
