### ISSUE TITLE
plugin: random "unexpected fault address 0x0" error on invoking an exported function 

### ISSUE THREAD

**Issue by vimalk78** [golang/go#19824] opened 2017-04-03 10:34 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
$ go version
go version go1.8 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vimal/gowork"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build007409990=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

created a plugin with `go build -buildmode=plugin`

opened the plugin a go program with `plugin.Open`
searched for a exported function with `plugin.Loopup` and invoked it

```
    s, err := p.Lookup(PLUGIN_METHOD_INIT_NAME)
    if err != nil {
        dlog.Error("find symbol failed")
        return err
    }
    if s == nil {
        dlog.Error("find symbol failed, found nil symbol")
        return fmt.Errorf("found nil symbol")
    }

    initf, ok := s.(func(engine.PluginInit) error)
    if !ok {
        dlog.Error("load plugin failed")
        return fmt.Errorf("function type mismatch")
    }
    initf(engine.PluginInit{          // << it carshes here
        CreateLoggerFunc: func(logp string) api.Logger {
            return log.GetLogger(logp)
        }})

```

### What did you expect to see?

plugin loaded successfully

### What did you see instead?

```
$ ./engine
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x1053ca0]

goroutine 1 [running]:
runtime.throw(0x15a89bf, 0x5)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc42032b6f8 sp=0xc42032b6d8
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc42032b748 sp=0xc42032b6f8
mypackage.(*PluginManager).OpenPlugin(0xc42043e620, 0xc42028e280, 0xc420011128, 0x5)

```
this happens randomly.

prior to this i got error "plugin was built with a different version of xyz package" and plugin failed to load, then i rebuilt the plugin and getting this error.

i should mention that there are another 3 plugins which are being loaded in the same manner.

**Comment by ianlancetaylor** [comment] 2017-04-03 15:56
CC @crawshaw

**Comment by tzneal** [comment] 2017-04-11 23:38
Dupe of #19269

**Comment by tzneal** [comment] 2017-04-17 22:43
Dupe, verified fixed in tip.

**Closed by tzneal** 2017-04-17 22:43 UTC
