### ISSUE TITLE
x/tools/gopls: support insertReplaceEdit results in completion items

### ISSUE THREAD

**Issue by jpap** [golang/go#48769] opened 2021-09-27 23:07 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.17 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```
Build info
----------
golang.org/x/tools/gopls v0.7.2
    golang.org/x/tools/gopls@v0.7.2 h1:kRKKdvA8GOzra8rhSFDClOR7hV/x8v0J0Vm4C/gWq8s=
    github.com/BurntSushi/toml@v0.4.1 h1:GaI7EiDXDRfa8VshkTj7Fym7ha+y8/XxIgD2okUIjLw=
    github.com/google/go-cmp@v0.5.6 h1:BKbKCqvP6I+rmFHt06ZmyQtvB8xAkWdhFyr0ZUNZcxQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.2 h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20210809222454-d867a43fc93e h1:WUoyKPm6nCo1BnNUvPGnFG3T5DUVem42yDJZZ4CNxMA=
    golang.org/x/tools@v0.1.6-0.20210908190839-cf92b39a962c h1:C0nyHiBU2m0cR6hDiUORWqQIt3h37wsp1255QBSSXqY=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.2.0 h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=
    mvdan.cc/gofumpt@v0.1.1 h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
    mvdan.cc/xurls/v2@v2.3.0 h1:59Olnbt67UKpxF1EwVBopJvkSUBmgtb468E4GVWIZ1I=
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.60.2
7f6ab5485bbc008386c4386d08766667e155244e
x64

* Check your installed extensions to get the version of the VS Code Go extension
	- v0.28.1
</details>

### Describe the bug

* When performing an autocomplete, vscode-go replaces the word under the cursor, even though the VSC `editor.suggest.insertMode` setting is set to "insert".
* When `editor.suggest.insertMode` is set to "insert", the word under the cursor should remain in-place, [as demonstrated in this video](https://www.youtube.com/watch?v=QIze0qkugNc&t=1s).

### Example

Let's say I was editing the following line, where `✎` represents the current cursor position:
```
if ✎filepath.Ext(myPath) == ".txt" {
```

I want to change the comparison to lowercase, so I type `strings.` at which time the suggestions dropdown appears.  If I select `ToLower`, then vscode-go will replace it as follows,
```
if strings.ToLower(✎).Ext(myPath) == ".txt" {
```
where it has **replaced** `filepath` with the suggestion.

But because my VSCode `editor.suggest.insertMode` setting is set to "insert", I would have expected,
```
if strings.ToLower(✎)filepath.Ext(myPath) == ".txt" {
```
where the suggestion has been **inserted** at the original cursor position.

#### Bonus points

In the above example, if vscode-go could instead wrap the expression at the cursor, as follows, it would result in even greater productivity:
```
if strings.ToLower(✎filepath.Ext(myPath)) == ".txt" {
```

**Comment by muirdm** [comment] 2021-10-04 15:31
Possible dupe of #40871

**Comment by findleyr** [comment] 2021-10-04 15:49
Thanks @muirdm, I think it makes sense to dedupe to #40871

**Closed by findleyr** 2021-10-04 15:49 UTC
Labels: help wanted, NeedsInvestigation, gopls, Tools
