### ISSUE TITLE
x/website: Effective Go needs to have a preamble re: generics

### ISSUE THREAD

**Issue by griesemer** [golang/go#49937] opened 2021-12-03 02:10 UTC
[Effective Go](https://go.dev/doc/effective_go) needs to be updated with a preamble/disclaimer as it was not written with generics in mind.

cc: @robpike

**Comment by robpike** [comment] 2021-12-03 06:45
It should also mention that is old and dated (and frozen) and has little about libraries and some other emergent best practices. A preamble is probably the right fit here.

**Comment by robpike** [comment] 2021-12-03 21:16
Duplicate of https://github.com/golang/go/issues/48274

**Comment by susugagalala** [comment] 2021-12-05 10:16
The book "The Go Programming Language" needs to be updated.

**Comment by amnonbc** [comment] 2022-01-18 09:01
Effective Go is an excellent resource and should be kept current.

**Comment by ianlancetaylor** [comment] 2022-01-28 00:45
Not doing this per CL 380634.

**Closed by ianlancetaylor** 2022-01-28 00:45 UTC
Labels: Documentation, NeedsFix, release-blocker
