### ISSUE TITLE
x/tools/internal/jsonrpc2_v2: TestIdleTimeout is flaky

### ISSUE THREAD

**Issue by heschi** [golang/go#54752] opened 2022-08-29 18:00 UTC
[2022-08-28T16:04:49-717a671-846c378/freebsd-amd64-12_3](https://build.golang.org/log/e9ce0bb6a86d564a899a8828e59b342c64c2fdb4)
[2022-08-26T20:56:48-717a671-acabf87/plan9-arm](https://build.golang.org/log/72c3880b5a596f66cde216c70781e1048dca71f8)
[2022-08-26T14:32:13-2f38e1d-d7a3fa1/openbsd-386-70](https://build.golang.org/log/056e330f84e640914e6df0c05674e1f0ed915a1e)
[2022-08-25T19:10:01-d35bb19-b9bf824/openbsd-386-68](https://build.golang.org/log/9eccadf748a7aa36af979280a94d226cdec24d9e)
[2022-08-24T22:39:01-db6a62c-ba5deb4/openbsd-amd64-70](https://build.golang.org/log/d8cd87e89cc24fe7bf9d1812b54c36f4ca26eaa4)
[2022-08-24T14:31:08-587a153-f983a93/linux-386-stretch](https://build.golang.org/log/1cd539c7b6beee40cf96b0d3c7a469b1cc1cf5ea)
[2022-08-19T17:28:00-e55fb40-0a1da09/darwin-amd64-12_0](https://build.golang.org/log/98e45b22437fb42d57a74a09c960603d96ae93ac)

cc @ianthehat @findleyr @jba

**Comment by bcmills** [comment] 2022-08-30 12:35
Duplicate of #46047

**Closed by bcmills** 2022-08-30 12:35 UTC
Labels: NeedsFix, Tools
