### ISSUE TITLE
runtime: loop over allp causes a nil pointer dereference crash

### ISSUE THREAD

**Issue by mikioh** [golang/go#23098] opened 2017-12-12 06:11 UTC
See https://build.golang.org/log/ff2e3f95d35cbaec0291bf387a6409c1f71e417f
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8078907]

runtime stack:
runtime.throw(0x8150279, 0x2a)
	/tmp/workdir/go/src/runtime/panic.go:616 +0x6b
runtime.sigpanic()
	/tmp/workdir/go/src/runtime/signal_unix.go:366 +0x230
runtime.runqempty(0x0, 0xffffff01)
	/tmp/workdir/go/src/runtime/proc.go:4638 +0x17
runtime.findrunnable(0x383e6000, 0x0)
	/tmp/workdir/go/src/runtime/proc.go:2342 +0x18d
runtime.schedule()
	/tmp/workdir/go/src/runtime/proc.go:2530 +0x10b
runtime.mstart1(0x0)
	/tmp/workdir/go/src/runtime/proc.go:1232 +0x7a
runtime.mstart()
	/tmp/workdir/go/src/runtime/proc.go:1188 +0x59
```
Seems like there is an exception to the assumption that "none of allp[i] are nil or in state _Pdead." in http://golang.org/cl/45575.

Hej Hej, @aclements

**Comment by ianlancetaylor** [comment] 2018-01-03 23:09
This is probably still happening.

[2017-09-28T21:09:46-a299345/darwin-arm-a1428ios](https://build.golang.org/log/5da06bf75122d01a3e3c3d2801829c6ca43f1965)
[2017-10-11T13:42:27-4477107/darwin-amd64-10_12](https://build.golang.org/log/e9f4fd250aa74c540edb5e75f824d341f9d8a1e1)
[2017-10-20T22:03:07-4e64ee4/freebsd-386-110](https://build.golang.org/log/cec23ebd2d4495ffe7de31ff00466c8cd914a5ba)
[2017-10-26T20:38:48-da95254/darwin-386-10_11](https://build.golang.org/log/c33ee8ca7750868a8ed8299ff76378511cfa51bb)
[2017-11-06T20:17:05-eca28cc/linux-amd64-noopt](https://build.golang.org/log/170f99b56dc1fe4ac54fa9c6c4344dcb50aacb12)
[2017-11-06T20:21:15-fa62ea6/linux-amd64-clang](https://build.golang.org/log/637b23519d0af7c8258cefee6116e33948d14e50)
[2017-11-18T00:33:04-12e2933/freebsd-amd64-gce101](https://build.golang.org/log/1029ec3aab005da48383c44916453c6c78a1730d)
[2017-12-12T04:26:40-ddae7fb/freebsd-386-11_1](https://build.golang.org/log/ff2e3f95d35cbaec0291bf387a6409c1f71e417f)

**Comment by ianlancetaylor** [comment] 2018-01-04 01:00
The failures are all in programs that call `runtime.GOMAXPROCS` to increase the number of P's.  The failures in all cases are in the `// check all runqueues once again` loop in `findrunnable`.  Perhaps of particular interest are three failures running go/test/fixedbugs/issue13160.go, a program that calls `runtime.GOMAXPROCS` once at the start of `main`.  In one of those (https://build.golang.org/log/e9f4fd250aa74c540edb5e75f824d341f9d8a1e1) the failure is in a call to `gopark` calling `schedule`, likely from a blocking channel operation.  The code in that case is apparently running well after the call to `runtime.GOMAXPROCS` has returned.  So somehow `findrunnable` is seeing a `nil` entry in `allp` after `GOMAXPROCS` returns.  Which seems impossible.

**Comment by aclements** [comment] 2018-01-04 15:58
> The failures in all cases are in the // check all runqueues once again loop in findrunnable.

That loop is concerning because it runs (somewhat non-obviously) without a P, so it could be running concurrently with a STW. I'm not sure how that would be a problem in that particular test, since, as you point out, allp should never be changing after the initial `GOMAXPROCS`.

I have a fix, which I will send shortly. I can't reproduce this issue, so it's hard to say if this actually fixes the problem, but it's certainly not a bad thing to fix.

**Comment by ianlancetaylor** [comment] 2018-01-10 23:18
I'm troubled by https://build.golang.org/log/71e1620c62a2255007ea450fc02e9c5d6f5af068 which shows a  crash in a different part of `findrunnable` that refers to `allp`.  In that case we are clearly running with a `p`, and the entry in `allp` is not `nil`, but it still somehow got a nil pointer dereference.

**Comment by ianlancetaylor** [comment] 2018-07-11 16:51
Most and perhaps all the recent occurrences of this problem seem to be on mipsle.

[2018-04-29T03:33:09-13cd006/linux-mipsle](https://build.golang.org/log/35b14f76335fc7d5c4b4ccc728c57113ca48d2a6)
[2018-05-07T13:31:15-7b7a854/linux-mipsle](https://build.golang.org/log/3bfec8fb25ac24523750ae31c5b762c24cf8e9e3)
[2018-05-07T15:12:35-9d72e8c/linux-mipsle](https://build.golang.org/log/cc2fd0e62929eb43aeec8d360b2bc47def094562)
[2018-05-18T13:54:12-8a16c71/linux-mipsle](https://build.golang.org/log/5652220396f3fa87b81961939dfb9b4165f17eb9)
[2018-05-18T16:01:32-db37e16/linux-mipsle](https://build.golang.org/log/a26d9f0b926c91203828d1193f77acd26ec7e20d)
[2018-05-29T17:45:36-db9341a/linux-mipsle](https://build.golang.org/log/37e69ea2cd80d067142853eb48ea031b64b115c4)
[2018-06-05T20:22:07-9be4f31/linux-mipsle](https://build.golang.org/log/ed4a4a8a0172b4594fe183ca914e7939c4ed3a12)
[2018-06-12T15:03:46-43a3cdf/linux-mipsle](https://build.golang.org/log/3b0cecb27a2afc66d2e96e1f6eb78cf447a5acd0)
[2018-06-13T14:55:01-a2f72cc/linux-mipsle](https://build.golang.org/log/790f1d5c6b792ca2b18f09c0af70ac51dab0fbfb)
[2018-06-25T18:59:39-50bd1c4/linux-mipsle](https://build.golang.org/log/392a78329384ef1e69c66ecf95ba420565feae8e)
[2018-06-26T14:39:02-5fad090/linux-mipsle](https://build.golang.org/log/aaaaf04d0a002c246f23b790affd3d1a15bd6609)
[2018-06-27T22:04:08-83092a4/linux-mipsle](https://build.golang.org/log/c4d7a22b8c3953f09cd26f5adf96cdb0e3e17e51)
[2018-06-28T23:01:22-b410ce7/linux-mipsle](https://build.golang.org/log/326c2a482f419e7e5567836a62263798f6ce18b8)
[2018-06-29T21:45:46-cdce824/linux-mipsle](https://build.golang.org/log/3a9965495148946852d64a6ce46212f472970a90)

**Comment by ianlancetaylor** [comment] 2018-07-11 17:00
Several of these seem to be `nil` pointer dereferences:

```
##### ../misc/cgo/test
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x43b498]

runtime stack:
runtime.throw(0x9301d0, 0x2a)
	/data/mipsle/go/src/runtime/panic.go:608 +0x58
runtime.sigpanic()
	/data/mipsle/go/src/runtime/signal_unix.go:374 +0x3b0
runtime.findrunnable(0x1022000, 0x0)
	/data/mipsle/go/src/runtime/proc.go:2349 +0xbc
runtime.schedule()
	/data/mipsle/go/src/runtime/proc.go:2612 +0x154
runtime.park_m(0x1192380)
	/data/mipsle/go/src/runtime/proc.go:2675 +0xb0
```

proc.go:2349 is

    if gp := runqsteal(_p_, allp[enum.position()], stealRunNextG); gp != nil {

It's hard to see a `nil` dereference there.  `runqsteal` is not being inlined.

**Comment by mknyszek** [comment] 2018-12-06 21:16
I grep'd over the logs since June 29th, and I couldn't find any new instances of this bug. That is, specifically `nil` pointer dereferences in findrunnable that happen at the same line (just looked at it myself to check). There was one that looked fishy from plan9-arm, but the dereference was cgo_yield and so seemed unrelated.

I'll bisect to try to figure out what commit "fixed" it for linux-mipsle.

With that said though, should this still be considered a release blocker?

**Comment by mknyszek** [comment] 2018-12-06 22:20
OK! I just took a second, slow look over the logs and I'm pretty confident in my assessment.

I'll close this bug off.

**Closed by mknyszek** 2018-12-06 22:20 UTC
Labels: NeedsFix, release-blocker
