### ISSUE TITLE
affected/package:  net/http

### ISSUE THREAD

**Issue by blessingcharles** [golang/go#53182] opened 2022-06-01 12:53 UTC
### What version of Go are you using (`go version`)?

<pre>
1.18.2
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

1. Provided chunked extension in chunksize according to RFC , most servers like gunicorn, nodejs , actix 
parsed correctly , but golang failed to parse the request and give the following error "Got error while reading body: invalid byte in chunk length" .

[RFC chunked extensions](https://datatracker.ietf.org/doc/html/rfc7230#section-4.1)

##### POC
```bash
echo -ne "GET / HTTP/1.1\r\nHost: localhost\r\nTransfer-encoding: chunked\r\n\r\n2 ; freferf\r\naa\r\n0\r\n\r\n" | nc localhost 8004
```

### What did you expect to see?

1. Correcly parse the chunked extension when present according to RFC

### What did you see instead?
```bash
HTTP/1.1 200 OK
Date: Wed, 01 Jun 2022 12:47:52 GMT
Content-Length: 58
Content-Type: text/plain; charset=utf-8
Connection: close

Got error while reading body: invalid byte in chunk length
```

#### Environment

```Dockerfile
FROM golang
USER root
WORKDIR /go/src/app
COPY server.go /go/src/app/server.go
RUN go mod init
RUN go build .
CMD ["./app"]

```

#### Code used
```golang
package main

import (
	"fmt"
	"io/ioutil"
	"net/http"
	"log"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		
		b, err := ioutil.ReadAll(r.Body)
		if err != nil {
			w.Write([]byte(fmt.Sprintf("Got error while reading body: %v", err)))
			return
		}
		fmt.Printf("Body length: %d Body: %q", len(b), b)
		w.Write([]byte(fmt.Sprintf("Body length: %d Body: %q", len(b), b)))
	})

	fmt.Printf("Server Starting at port 80") 
	if err := http.ListenAndServe(":80", nil) ; err != nil {
		log.Fatal(err)
	}
}
```

**Comment by seankhliao** [comment] 2022-06-01 14:25
That's an invalid request.
The RFC specifies no space between the chunk size and the chunk extension.

Closing as not a bug

**Closed by seankhliao** 2022-06-01 14:25 UTC
