### ISSUE TITLE
x/tools: flaky builds on linux-amd64-wsl

### ISSUE THREAD

**Issue by rsc** [golang/go#55255] opened 2022-09-20 13:19 UTC
```
#!watchflakes
post <- builder == "linux-amd64-wsl" && `\.go:\d+:\d+: .*@v\d.*: unexpected EOF`
```

The linux-amd64-wsl builder uses proxy.golangcn.org as an HTTP/HTTPS proxy, and that seems to be tricking the go command into printing build failures like

    godoc/redirect/redirect.go:22:2: golang.org/x/net@v0.0.0-20211015210444-4f30a5c0130f: unexpected EOF

It's a bit cryptic if nothing else.

**Comment by bcmills** [comment] 2022-09-20 14:32
Duplicate of #54275

**Closed** 2022-09-21 02:19 UTC
Labels: NeedsInvestigation, Tools
