### ISSUE TITLE
affected/package: bufio

### ISSUE THREAD

**Issue by HansVanHerwijnen** [golang/go#51703] opened 2022-03-16 10:11 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.17.6 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

not tested

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\hansvanherwijnen\AppData\Local\go-build
set GOENV=C:\Users\hansvanherwijnen\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=gitlab.resato.com/*
set GOMODCACHE=C:\Users\hansvanherwijnen\go\pkg\mod
set GONOPROXY=gitlab.resato.com
set GONOSUMDB=gitlab.resato.com
set GOOS=windows
set GOPATH=C:\Users\hansvanherwijnen\go
set GOPRIVATE=gitlab.resato.com
set GOMOD=C:\Projecten\SCS\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\HANSVA~1\AppData\Local\Temp\go-build1818901484=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

Reading from a file with bufio n,err := r.Read(buf)

f, err := os.Open("test.zip")  // test.zip must be bigger than the chunk read by bufio, but I don't know the size
r := bufio.NewReader(f)
buf1 := make([]byte,4)
buf2 := make([]byte,35)  // create an odd offset in the bufio reader, but maybe any reading past the bufio-size will cause the problem
n2,err2 := r.Read(buf2)
for {
&nbsp;&nbsp;n1,err1 := r.Read(buf1)
&nbsp;&nbsp;if err1 != nil {
&nbsp;&nbsp;&nbsp;&nbsp;break
&nbsp;&nbsp;}
}

### What did you expect to see?
buf1 containing "full" 32 bit data

### What did you see instead?
When the pre-read buffer is exhausted, r.Read still returns n1 == 4 && err == nil, but buf 1 will contain at least 1 zero value.  
The next read will give the "lost" byte(s)

E.g. expecting {0x12, 0x34, 0x56, 0x78}, getting {0x00, 0x00, 0x00, 0x12} and {0x34, 0x56, 0x78, 0x9A} on the next read

**Comment by seankhliao** [comment] 2022-03-16 13:32
Duplicate of #51095

**Closed by seankhliao** 2022-03-16 13:32 UTC
