### ISSUE TITLE
cmd/compile: switching over channel value incorrectly does not match when the direction is narrower in the case

### ISSUE THREAD

**Issue by Jorropo** [golang/go#67190] opened 2024-05-05 23:07 UTC
### Go version

go version devel go1.23-619b419a4b Sun May 5 00:26:04 2024 +0000 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/tmp/go-build'
GOENV='/home/hugo/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/hugo/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/hugo/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/hugo/k/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/home/hugo/k/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='devel go1.23-619b419a4b Sun May 5 00:26:04 2024 +0000'
GODEBUG=''
GCCGO='/usr/bin/gccgo'
GOAMD64='v3'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build988502288=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

*`@LeaBit` on discord gophers report this behavior:*
```go
package main

import "fmt"

func main() {
	ch1 := make(chan struct{})

	var ch2 <-chan struct{} = ch1

	switch ch1 {
	case ch2:
		fmt.Println("Narrow case: Same!")
	default:
		fmt.Println("Narrow case: Not same!")
	}

	switch ch2 {
	case ch1:
		fmt.Println("Narrow switch: Same!")
	default:
		fmt.Println("Narrow switch: Not same!")
	}

	fmt.Println("Equal:", ch1 == ch2)
}
```

### What did you see happen?

```
Narrow case: Not same!
Narrow switch: Same!
Equal: true
```

### What did you expect to see?

```
Narrow case: Same!
Narrow switch: Same!
Equal: true
```

**Comment by Jorropo** [comment] 2024-05-05 23:09
cc @golang/compiler

**Comment by randall77** [comment] 2024-05-05 23:17
The behavior changed from 1.19 and 1.20.
A bisect would be helpful to track down the cause.

**Comment by Jorropo** [comment] 2024-05-05 23:24
I'll send a fix

**Comment by Jorropo** [comment] 2024-05-06 01:33
Bisect results:
- 833367e98af838a2511ee7e4e19dc8f1da7b8ed7
- rebisecting with `-gcflags=-d=unified` gives a4c5198a3c8befa2f126fd365de4dc09c32b7886

**Comment by Jorropo** [comment] 2024-05-06 01:51
It looks like the any compare behavior is correct:
> Two interface values are equal if they have identical dynamic types and equal dynamic values or if both have value nil.

so TIL `a == b` has different semantics as `any(a) == any(b)`

**Comment by cuonglm** [comment] 2024-05-06 02:19
Possibly duplicate of https://github.com/golang/go/issues/44051

**Comment by Jorropo** [comment] 2024-05-06 02:22
I don't think so, here I'm assuming the behavior seen in #44051 is correct and not a bug yet this is still broken.

**Comment by Jorropo** [comment] 2024-05-06 03:18
Needs more changes in `cmd/walk/switch.go` to achieve what I want, it's tricky, someone else should make sure to do it right.

**Closed** 2024-07-03 18:07 UTC
Labels: help wanted, NeedsFix, compiler/runtime
