### ISSUE TITLE
x/term: inaccessible source at pkg.go.dev

### ISSUE THREAD

**Issue by sh0rez** [golang/go#47263] opened 2021-07-17 11:45 UTC
### What did you do?

Went to https://pkg.go.dev/golang.org/x/term and clicked on the `GetSize` headline to get to the source listing

### What did you expect to see?

Some source code, either on GitHub (https://github.com/golang/term), or somewhere else

### What did you see instead?

Got forwarded to https://cs.opensource.google/go/x/term/+/6886f2df:term.go;l=49, which merely shows a "Permission denied" page:

<img src="https://user-images.githubusercontent.com/26971117/126035790-ccbe662f-7ef1-42b2-8795-452d1289ac5f.png" width=300px />

**Comment by seankhliao** [comment] 2021-07-17 14:47
Duplicate of #47213

**Closed by seankhliao** 2021-07-17 14:47 UTC
