### ISSUE TITLE
cmd/compile: bogus "fallthrough statement out of place"

### ISSUE THREAD

**Issue by dvyukov** [golang/go#13262] opened 2015-11-16 09:57 UTC
cmd/compile fails to compile the following program:
```go
package p

func f() int {
	switch 0 {
	case 0:
		return (int)(""[((func() int)(nil))()])
		fallthrough
	default:
	}
	return 0
}
```
```
2.go:7: fallthrough statement out of place
```

gotype eats it.

go version devel +25a28da Sun Nov 15 23:41:28 2015 +0000 linux/amd64

Found with GoSmith (https://github.com/dvyukov/gosmith).

**Comment by griesemer** [comment] 2015-11-16 21:35
This is a bug with both the existing and the new parser.

**Comment by griesemer** [comment] 2015-11-24 23:48
Slightly simpler case:
```
package p

func f() int {
	switch 0 {
	case 0:
		return (func() int)(nil)()
		fallthrough
	default:
	}
	return 0
}
```

**Comment by ALTree** [comment] 2016-05-08 09:53
Simpler reproducer for posterity in case the patch I mailed won't be merged

```
package p

func f() int {
	var a int
	switch a {
	case 0:
		return func() int { return 1 }()
		fallthrough
	default:
	}
	return 0
}
```

anything that creates an `autotmp_` in the return line goes. gc compiles
```
case 0:
		return func() int { return 1 }()
		fallthrough
```
as
```
autotmp_0 = (func literal)(); return autotmp_0; fallthrough; <node VARKILL>
```

The problem is that the `casebody` function in swt.go, which replaces Op in `OXFALL` nodes (not-yet-processed fallthrough) with `OFALL` (processed fallthrough) always assumes that the node with the `fallthrough` statement will be the last one. In this case, this is false: the last node is the `OVARKILL` one. For this reason the `OXFALL` node won't be marked as `OFALL`, and the `fallthrough` on the second line ends up being reported as spurious.

**Closed** 2016-09-26 15:47 UTC
