### ISSUE TITLE
x/pkgsite: Examples on golang.org/x/exp/xerrors are broken

### ISSUE THREAD

**Issue by 3456091** [golang/go#52109] opened 2022-04-01 17:46 UTC
### What is the URL of the page with the issue?

https://pkg.go.dev/golang.org/x/exp/xerrors

### What is your user agent?

Firefox Nightly

### What did you do?

Tried to run the example for, say, the As method.

### What did you expect to see?

The result of the example.

### What did you see instead?

```
go: finding module for package golang.org/x/exp/xerrors
go: downloading golang.org/x/exp v0.0.0-20220328175248-053ad81199eb
go: finding module for package golang.org/x/exp/xerrors
prog.go:7:2: module golang.org/x/exp@latest found (v0.0.0-20220328175248-053ad81199eb), but does not contain package golang.org/x/exp/xerrors
```

**Comment by jamalc** [comment] 2022-04-01 20:31
Duplicate of #50769

**Closed by jamalc** 2022-04-01 20:31 UTC
Labels: pkgsite
