### ISSUE TITLE
http.ReadResponse Method automatically removes the connection: close request header

### ISSUE THREAD

**Issue by veryWrong** [golang/go#44034] opened 2021-02-01 06:37 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
</pre></details>

### What did you expect to see?
```
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io/ioutil"
	"log"
	"net"
	"net/http"
	"net/textproto"
)

func main() {
	b := []byte(`GET /img/flexible/logo/pc/result.png HTTP/1.1
Host: www.baidu.com
Connection: close
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: image
Referer: https://www.baidu.com/
Accept-Language: zh-CN,zh;q=0.9
dnt: 1

`)
	conn, err := net.Dial("tcp", "www.baidu.com:80")
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()
	_, err = conn.Write(b)
	if err != nil {
		log.Fatal(err)
	}
	res, err := ioutil.ReadAll(conn)
	if err != nil {
		log.Fatal(err)
	}
	r := bufio.NewReader(bytes.NewReader(res))
	tp := textproto.NewReader(r)
	_, _ = tp.ReadLine()
	mimeHeader, err := tp.ReadMIMEHeader()
	if err != nil {
		log.Fatal(err)
	}
	resp, err := http.ReadResponse(bufio.NewReader(bytes.NewReader(res)), nil)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(mimeHeader.Get("Connection") == resp.Header.Get("Connection"))
}

expect :
go run main.go

true
```

### What did you see instead?
go run main.go

false

**Comment by veryWrong** [comment] 2021-02-01 08:14
```
net/http/transfer.go:484
func readTransfer(msg interface{}, r *bufio.Reader) (err error) {
	t := &transferReader{RequestMethod: "GET"}

	// Unify input
	isResponse := false
	switch rr := msg.(type) {
	case *Response:
		t.Header = rr.Header
		t.StatusCode = rr.StatusCode
		t.ProtoMajor = rr.ProtoMajor
		t.ProtoMinor = rr.ProtoMinor
		t.Close = shouldClose(t.ProtoMajor, t.ProtoMinor, t.Header, true)
		isResponse = true
		if rr.Request != nil {
			t.RequestMethod = rr.Request.Method
		}
                ......
```
Why when msg is Response, the last parameter of shouldclose is true?

**Comment by seankhliao** [comment] 2021-02-01 12:19
from Response.Header:
> //... When
    // Header values are duplicated by other fields in this struct (e.g.,
    // ContentLength, TransferEncoding, Trailer), the field values are
    // authoritative.
    //
    // Keys in the map are canonicalized (see CanonicalHeaderKey).
    Header Header

The Response.Close field is authoritative and you should be checking that

closing as working as intended

**Closed by seankhliao** 2021-02-01 12:19 UTC
