### ISSUE TITLE
net/http: apparent deadlocks in TestDisableKeepAliveUpgrade on longtest builders

### ISSUE THREAD

**Issue by bcmills** [golang/go#43073] opened 2020-12-08 15:43 UTC
[2020-12-07T21:01:46-7ad6596/windows-amd64-longtest](https://build.golang.org/log/cf8fea7379e30fadf5f802d44d8d5692152bd0c5)
[2020-12-04T08:49:16-b67b7dd/windows-amd64-longtest](https://build.golang.org/log/d74d29ee5d1abd38da538b7334cfb4bfa01c6cdb)
[2020-12-02T16:43:58-10240b9/windows-amd64-longtest](https://build.golang.org/log/7d7853089533b8db97540a4070e28e351ca77f36)

Marking as release-blocker for Go 1.16: this is a new test, merged Dec. 1 in [CL 213277](https://golang.org/cl/213277) for #36381.

CC @bradfitz @nhooyr @neild @fraenkel @golang/release

**Comment by bcmills** [comment] 2020-12-08 15:45
This regression was partially masked in the builders by #42942.

**Comment by nhooyr** [comment] 2020-12-09 00:59
Hmm, interesting that it only occurs on Windows.

Looks like the `io.ReadFull` on line `6495` is stuck as the peer isn't echoing back the written bytes for some reason.

**Comment by nhooyr** [comment] 2020-12-09 01:04
Nothing stands out, the test may be surfacing an unrelated regression.

**Comment by nhooyr** [comment] 2020-12-09 01:11
Actually I'm going to push up a change that may fix it.

**Comment by nhooyr** [comment] 2020-12-09 01:19
Opened https://github.com/golang/go/pull/43086

**Comment by toothrot** [comment] 2020-12-10 19:10
@bradfitz @neild This is currently blocking beta1. Could you please take a look at the CL when you get a chance?

**Comment by dmitshur** [comment] 2020-12-14 23:06
Thanks for looking into this @nhooyr.

There haven't been instances of this failure since [CL 276375](https://golang.org/cl/276375) was submitted, although given it happened infrequently earlier, that's not a definitive signal.

Do you know if anything more needs to be done for this issue, or is it a matter of waiting for some more data before closing?

I'll add okay-after-beta1 since it doesn't need to block beta 1 in this state.

**Comment by nhooyr** [comment] 2020-12-15 20:40
> Do you know if anything more needs to be done for this issue, or is it a matter of waiting for some more data before closing?

I didn't notice anything else that could cause it so yes I'd agree that it is a matter of waiting for some more data.

**Comment by bcmills** [comment] 2021-01-07 16:12
Still a problem after CL 276375:

[2021-01-04T12:06:08-b01fb2a/linux-386-longtest](https://build.golang.org/log/fc6a753a12be03a439dc2ea63cd1d2fd6f6049a3)
[2020-12-31T02:24:55-95ce805/linux-amd64-longtest](https://build.golang.org/log/64b07324ce81cf2d7784894a2a3d355246993816)
[2020-12-26T19:08:56-1d78139/windows-amd64-longtest](https://build.golang.org/log/c9605a44e2d45bec52e149dd4eaf1da369174f86)
[2020-12-23T14:16:32-98a7303/windows-amd64-longtest](https://build.golang.org/log/14f5136307c0f4bd5238326765bc94054d0da324)
[2020-12-17T16:03:19-2ff33f5/windows-amd64-longtest](https://build.golang.org/log/3b7968c3e952989ada58c9a2dac1f5007f524dd4)
[2020-12-14T20:56:03-dea6d94/linux-amd64-longtest](https://build.golang.org/log/81e3808ba8d64af401ed421b114c325e1dec06d9)
[2020-12-14T20:30:16-2f5b1a3/linux-386-longtest](https://build.golang.org/log/ecd57ccac73bc174a10163a6bb3a9f6d5cd30df2)
[2020-12-14T19:19:09-c81343c/linux-386-longtest](https://build.golang.org/log/ebfd0e1af492c0dfcb4f7178f092ce5eb188713b)

**Comment by nhooyr** [comment] 2021-01-07 23:33
Damn, that's unfortunate. Hope I have some time this weekend to investigate but if not, I think we should just revert my changes & the test and I'll try and reproduce myself first.

**Closed** 2021-01-22 16:24 UTC
Labels: NeedsInvestigation, release-blocker
