### ISSUE TITLE
flag/flag: bool

### ISSUE THREAD

**Issue by 20yyq** [golang/go#62494] opened 2023-09-07 03:15 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/system/test/vcan/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4111172739=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
flag.BoolVar(&ext, "ext1", false, "ext usage bool")
flag.BoolVar(&ext1, "ext2", false, "ext usage bool")
flag.UintVar(&id, "id", 0, "id usage uint")
flag.StringVar(&data1, "data", "", "data usage string")
flag.Parse()
fmt.Println("flag arg ", ext, ext1, flag.Args())
fmt.Println("os.Args ", os.Args)

### What did you expect to see?
root@Eacher:/system/test/vcan# go run test.go -ext1 false -ext2 true -id 123124 -data string
flag arg true false [false -ext2 true -id 123124 -data string]
os.Args [/tmp/go-build11580025/b001/exe/test -ext1 false -ext2 true -id 123124 -data string]

**Comment by seankhliao** [comment] 2023-09-07 11:58
Duplicate of #62491

**Closed by seankhliao** 2023-09-07 11:58 UTC
