### ISSUE TITLE
I can't believe Go doesn't support binary literals.

### ISSUE THREAD

**Issue by htrob** [golang/go#22140] opened 2017-10-05 02:27 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.1 linux/amd64

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
GOOS="linux"
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"

### What did you do?

x :=  0b10000000
fmt.Printf("x: %d\n", x)

Play:
https://play.golang.org/p/dLA_VwSGwf

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
x: 128

### What did you see instead?
tmp/sandbox135869927/main.go:8:8: syntax error: unexpected b10000000 at end of statement

**Comment by bradfitz** [comment] 2017-10-05 02:40
> I can't believe Go doesn't support binary literals.

That's not the most polite way to start a bug report. You're likely to lose many people with such a start.

**Comment by davecheney** [comment] 2017-10-05 02:40
Duplicate of #19308

**Closed by davecheney** 2017-10-05 02:40 UTC
