### ISSUE TITLE
Fix for the Writing Web Applications tutorial

### ISSUE THREAD

**Issue by nivaldogmelo** [golang/go#31311] opened 2019-04-06 20:46 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12.1 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code></summary><br><pre>
$ go env

</pre>GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nivaldogmelo/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/nivaldogmelo/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build083406842=/tmp/go-build -gno-record-gcc-switches" </details>

### What did you do?

At the part 2 of the [Writing Web Applications](https://golang.org/doc/articles/wiki/) tutorial it's not in the instructions the need to import the "log" at the import step for the wiki app. Although the log is used at the
<pre>
func main() {
    http.HandleFunc("/view/", viewHandler)
    log.Fatal(http.ListenAndServe(":8080", nil))
}
</pre>

### What did you expect to see?

<pre>
import (
	"fmt"
	"io/ioutil"
	<b>"net/http"</b>
        <b>"log"</b>
)
</pre>

### What did you see instead?

<pre>
import (
	"fmt"
	"io/ioutil"
	<b>"net/http"</b>
)
</pre>

**Comment by agnivade** [comment] 2019-04-07 03:25
Duplicate of https://github.com/golang/go/issues/25188

**Closed by agnivade** 2019-04-07 03:25 UTC
