### ISSUE TITLE
x/pkgsite: `f` for search doesn't work in Firefox for net/http page

### ISSUE THREAD

**Issue by eliben** [golang/go#44146] opened 2021-02-07 15:16 UTC
### What is the URL of the page with the issue?
 
https://pkg.go.dev/net/http
 
 
### What is your user agent?
 
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0

 
### Screenshot
 
Looks just like the regular page on https://pkg.go.dev/net/http, but with a slightly greyed background. The same greying you get when you search with `f`, except that the actual search dialog does not appear.

 
### What did you do?

* Navigated to https://pkg.go.dev/net/http 
* Pressed `f` on my keyboard

 
### What did you expect to see?

The "Jump to" dialog. 

 
### What did you see instead?

No dialog. Just modal greying of the page background and inability to interact with it.

**Comment by jamalc** [comment] 2021-02-08 15:13
Duplicate of #44077

**Closed by jamalc** 2021-02-08 15:13 UTC
Labels: pkgsite
