### ISSUE TITLE
x/website: go.dev/play share button does not actually give the URL, only redirects

### ISSUE THREAD

**Issue by zikaeroh** [golang/go#49742] opened 2021-11-23 02:24 UTC
### What did you do?

I tried out the new playground, and hit the share button.

### What did you expect to see?

A box appear like the old playground.

### What did you see instead?

The page only redirects (without refresh), giving no indication that something happened or what the URL is to copy.

**Comment by rsc** [comment] 2021-11-24 22:03
Duplicate of #49766.

**Closed by rsc** 2021-11-24 22:03 UTC
Labels: NeedsInvestigation
