### ISSUE TITLE
cmd/compile: internal compiler error importing a recursive type (recursive through a type constraint)

### ISSUE THREAD

**Issue by Karitham** [golang/go#51219] opened 2022-02-16 11:25 UTC
### What version of Go are you using (`go version`)?

<pre>
❯ g version
go version devel go1.18-293ecd8 Tue Feb 15 22:54:38 2022 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

1.18beta1, beta2 & gotip

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
❯ g env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/karitham/.cache/go-build"
GOENV="/home/karitham/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/karitham/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/karitham/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/karitham/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/karitham/sdk/gotip/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.18-293ecd8 Tue Feb 15 22:54:38 2022 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/karitham/corde/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4188918709=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Using type parameters, I get a compiler panic in an assignment.

I have tried extremely hard to provide a better program, but haven't managed to reproduce the bug easily on the playground.

See <https://github.com/Karitham/corde/blob/error/compiler-panic/components/interactions.go#L148-L156> for the whole codebase with the log 

### What did you expect to see?

Either a compile error that makes sense, or my program building (most likely the second one, but I'm not familiar enough with generics yet to expect my code to be 100% valid)

### What did you see instead?

Nonsensical error message and/or compiler panic

**Comment by dmitshur** [comment] 2022-02-16 13:48
CC @ianlancetaylor, @randall77.

**Comment by randall77** [comment] 2022-02-16 16:03
To reproduce:
```
$ git clone https://github.com/Karitham/corde
$ cd corde
$ git checkout 1848bb7405f089e2e68952b015278f94afe3f053
$ cd components
$ go build
# github.com/Karitham/corde/components
./interactions.go:152:11: cannot use bt.Data (variable of type JsonRaw) as type JsonRaw in assignment
```

I think there's some confusion as to what `JsonRaw` is. Inside `UnmarshalJSON`, `JsonRaw` is a type parameter. But in the definition of `_basicT`, `JsonRaw` is a concrete type (a `[]byte`, defined in `json.go`).
So the error is correct, it is just confusing because you have two different types with the same name.

Same as if you did:
```
package main

type T int

var x T

func f() {
	type T float64
	var y T
	x = y
}
```
```
tmp1.go:10:4: cannot use y (type T) as type T in assignment
```
Closing, as this is not a bug. Maybe there would be ways to improve the error messages (include definition line of the type name when it appears more than once in the error message?) but this is currently working as expected.

**Comment by Karitham** [comment] 2022-02-16 16:27
Have you tried removing the assignment, though?

**Comment by Karitham** [comment] 2022-02-16 16:40
To reproduce the panic
```sh
git clone https://github.com/Karitham/corde
cd corde
git checkout ae8ae03a3401df2f1a6a365e81742bf90acfaf94
go test ./...
```
@randall77

**Comment by danscales** [comment] 2022-02-17 03:29
This relates to importing a complex recursive type.  This issue only happens  if the recursion happens through the type constraint.  (In this program, the recursion actually goes through two different type constraints!)

I have the rough fix (small changes to the importers), but creating a minimized test case may take a while.  I believe this is not a release-blocker, because of the unusual situation of recursion through the type constraint.

**Comment by findleyr** [comment] 2022-02-18 18:25
I went to port this fix to x/tools/go/internal/gcimporter, and observed that it doesn't reproduce with the x/tools importer/exporter. @danscales mentioned something similar, that the error was not locally reproducible with the types2 importer. This suggests that there's some inconsistency across the types/import/export APIs. Reopening because we should nail down the root cause.

**Closed** 2022-03-14 21:01 UTC
Labels: NeedsInvestigation
