### ISSUE TITLE
proposal: reflect: reflect.TypeOf(nil).Kind() panics; let's make it return nil

### ISSUE THREAD

**Issue by leozz37** [golang/go#54208] opened 2022-08-02 20:19 UTC
The `Kind()` method of `reflect.TypeOf()` returns the type of a given value, so this snippet panics:

```go
import "reflect"

func main() {
    reflect.TypeOf(nil).Kind()
}

panic: runtime error: invalid memory address or nil pointer dereference
```

When checking the type of a value, may occur that it can be nil, causing the program to crash. Iterating through a slice of interface and having a nil value can be a struggle.

There's many ways to solve this, but my propose is that `reflect.TypeOf(nil).Kind()` should returns `nil`.

I'm not sure this makes sense, but brought the topic to discuss.

**Comment by robpike** [comment] 2022-08-02 21:19
Duplicate of #51649?

**Comment by ianlancetaylor** [comment] 2022-08-02 21:53
Yes, let's fold this into #51649.  Thanks.

**Closed by ianlancetaylor** 2022-08-02 21:53 UTC
Labels: Proposal
