### ISSUE TITLE
x/website: tutorial -replace=old=new doesn't work in powershell

### ISSUE THREAD

**Issue by migberbay** [golang/go#44924] opened 2021-03-10 18:06 UTC
Hi! I was chekcing the intial tutorials for making modules, and [this](https://golang.org/doc/tutorial/call-module-code) site is using the wrong syntax in this line:

$ go mod edit -replace=example.com/greetings=../greetings

and it should be:

$ go mod edit -replace example.com/greetings=../greetings

I'm using the newest version of go at the time, 1.16

**Comment by seankhliao** [comment] 2021-03-10 19:08
Duplicate of #44906

Seems like a powershell issue

**Comment by tmthrgd** [comment] 2021-03-11 02:15
I think this is probably a duplicate of #43179 and an example of the still unfixed PowerShell/PowerShell#6291.

**Comment by ALTree** [comment] 2021-03-11 11:35
I guess the question here is whether we want to change the tutorial to work around the Powershell issue or not.

**Comment by kartikPatidar** [comment] 2021-04-04 08:43
For now we should just change the command to : 
 go mod edit -replace example.com/greetings=../greetings

SO that more beginners don't get stuck on this error.

**Comment by heschi** [comment] 2021-06-23 15:18
Fixed in https://golang.org/cl/330229. (I messed up the CL description.)

**Closed by heschi** 2021-06-23 15:18 UTC
Labels: Documentation, NeedsDecision
