### ISSUE TITLE
cmd/go: static linking only sometimes works on Alpine Linux

### ISSUE THREAD

**Issue by aykevl** [golang/go#38789] opened 2020-05-01 14:40 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +666c9aedd4 Thu Apr 30 17:30:54 2020 +0000 linux/amd64
</pre>

For completeness, also the GCC version:

<pre>
$ gcc --version
gcc (Alpine 9.2.0) 9.2.0
</pre>

### Does this issue reproduce with the latest release?

Yes, it also reproduces with `go version go1.14.2 linux/amd64`, but with the more confusing error message "relocation target ... not defined for ABI0 (but is defined for ABI0)". Possibly related: #33492, #33028.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/root/src/go.master"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/src/go.master/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build487931648=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Run this program:

```go
package main

import "os/user"

func main() {
	user, _ := user.Current()
	println(user.Username)
}
```

With the command `CGO_LDFLAGS="-static" go run main.go`, on Alpine Linux.

For completeness: Alpine Linux 3.11, with Go built from source (tested both the latest release 1.14.2 and the master branch, see above). I removed Go while testing to make sure I didn't accidentally pick the wrong one.

### What did you expect to see?

Run a fully statically linked binary. I know that this can work on Alpine Linux, as I've build a big application this way.

### What did you see instead?

```
# _/root/repro
.dynsym: missing Go type information for global symbol: size 72
os/user(.text): relocation target malloc not defined
os/user(.text): relocation target free not defined
os/user(.text): relocation target getgrgid_r not defined
os/user(.text): relocation target getgrnam_r not defined
os/user(.text): relocation target getpwnam_r not defined
os/user(.text): relocation target getpwuid_r not defined
os/user(.text): relocation target realloc not defined
os/user(.text): relocation target sysconf not defined
runtime/cgo(.text): relocation target stderr not defined
runtime/cgo(.text): relocation target fwrite not defined
runtime/cgo(.text): relocation target vfprintf not defined
runtime/cgo(.text): relocation target fputc not defined
runtime/cgo(.text): relocation target abort not defined
runtime/cgo(.text): relocation target pthread_mutex_lock not defined
runtime/cgo(.text): relocation target pthread_cond_wait not defined
runtime/cgo(.text): relocation target pthread_mutex_unlock not defined
runtime/cgo(.text): relocation target __stack_chk_fail not defined
runtime/cgo(.text): relocation target pthread_cond_broadcast not defined
runtime/cgo(.text): relocation target pthread_create not defined
runtime/cgo(.text): relocation target nanosleep not defined
/root/src/go.master/pkg/tool/linux_amd64/link: too many errors
unexpected fault address 0x7fbc8ab82000
fatal error: fault
```

I found an interesting workaround, which is to use CGo directly in the main package. Somehow this works with `CGO_LDFLAGS="-static"`:

```go
package main

import "os/user"

// #include <stdlib.h>
import "C"

func main() {
	user, _ := user.Current()
	println(user.Username)
	println(C.malloc(1))
}
```

If you wonder why I pass this CGo linker flag to a program that doesn't use CGo, it's because I run many tests in a single command (`go test ./foo ./bar ./baz`). Most use CGo, but some don't - at least not directly.

**Comment by bcmills** [comment] 2020-05-01 14:49
This may be a duplicate of #26492, in that `CGO_LDFLAGS=-static` does not imply “always static” and we don't yet have a flag that _does_ imply that.

CC @jayconrod @matloob

**Comment by bcmills** [comment] 2020-05-01 14:51
@aykevl, can you confirm whether the flags in https://github.com/golang/go/issues/26492#issuecomment-435462350 work for your programs?

**Comment by aykevl** [comment] 2020-05-01 15:02
Right after posting this issue I discovered that there is a `osusergo` build tag, and indeed `CGO_LDFLAGS="-static" go run -tags=osusergo main.go` works.


I tested with `-tags netgo -ldflags '-extldflags "-static"'` but it doesn't fix the issue. However, `-tags 'netgo osusergo' -ldflags '-extldflags "-static"'` works.

**Comment by bcmills** [comment] 2020-05-01 15:04
Thanks for confirming. This does seem like the same issue, then.

**Comment by bcmills** [comment] 2020-05-01 15:04
Duplicate of #26492

**Closed by bcmills** 2020-05-01 15:04 UTC
Labels: GoCommand, NeedsInvestigation, WaitingForInfo
