### ISSUE TITLE
Unsure Golang installed or not 

### ISSUE THREAD

**Issue by DebadityaMalakar** [golang/go#66241] opened 2024-03-11 06:47 UTC
![SS1](https://github.com/golang/go/assets/123065261/ecd88f2c-39ed-4c93-9abc-08742c784a1c)

**Comment by ALTree** [comment] 2024-03-11 10:00
As the error message says, building master or 1.22 (assuming that's what you're doing) requires go1.20.6, while you have go1.18 gccgo. Please install go 1.20 and the re-run all.bash.

Closing here since this is not a bug.

**Closed by ALTree** 2024-03-11 10:00 UTC
