### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Hyejin** [golang/go#70247] opened 2024-11-01 12:43 UTC
gopls version: v0.16.2/go1.22.5
gopls flags: 
update flags: proxy
extension version: 0.42.1
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Fri, 01 Nov 2024 12:43:00 GMT
restart history:
Fri, 01 Nov 2024 12:10:19 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic:   stmt.go:932: assertion failed

goroutine 127 [running]:
go/types.(*Checker).handleBailout(0xc000560200, 0xc0003e5898)
	  check.go:367  0x88
panic({0x151d9e0%3F, 0xc0005fea20%3F})
	  panic.go:770  0x132
go/types.assert(0x0%3F)
	  errors.go:28  0x54
go/types.(*Checker).rangeStmt(0xc000560200, 0x3, 0xc0000e2f60)
	  stmt.go:932  0xe70
go/types.(*Checker).stmt(0xc000560200, 0x0, {0x19a0640, 0xc0000e2f60})
	  stmt.go:827  0xab9
go/types.(*Checker).stmtList(0xc000560200, 0x0, {0xc0002d5dc0%3F, 0x3%3F, 0x4%3F})
	  stmt.go:121  0x85
go/types.(*Checker).funcBody(0xc000560200, 0x199ca58%3F, {0xc0000a72f0%3F, 0xc0005fe970%3F}, 0xc000472240, 0xc0007354d0, {0x0%3F, 0x0%3F})
	  stmt.go:41  0x331
go/types.(*Checker).funcDecl.func1()
	  decl.go:852  0x3a
go/types.(*Checker).processDelayed(0xc000560200, 0x0)
	  check.go:467  0x162
go/types.(*Checker).checkFiles(0xc000560200, {0xc0000761c8, 0x1, 0x1})
	  check.go:411  0x1cc
go/types.(*Checker).Files(...)
	  check.go:372
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).checkPackage(0xc0006943c0, {0x19a18e8, 0xc000734ba0}, 0xc00066c360)
	  check.go:1543  0xa25
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).handleSyntaxPackage(0xc0006943c0, {0x19a18e8, 0xc000734ba0}, 0x0, {0xc000625560, 0x27})
	  check.go:568  0x5e5
golang.org/x/tools/gopls/internal/cache.(*Snapshot).forEachPackageInternal.func2()
	  check.go:418  0x2b
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 140
	  errgroup.go:75  0x96
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 2,
    "TestdataFiles": 0,
    "GoFiles": 1,
    "ModFiles": 1,
    "Dirs": 1
  },
  "GOARCH": "amd64",
  "GOOS": "windows",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.5",
  "GoplsVersion": "v0.16.2",
  "InitialWorkspaceLoadDuration": "549.3944ms",
  "MemStats": {
    "HeapAlloc": 1826848,
    "HeapInUse": 3981312,
    "TotalAlloc": 137487880
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 2,
      "Largest": 106,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.21.12",
        "AllPackages": {
          "Packages": 1,
          "LargestPackage": 1,
          "CompiledGoFiles": 1,
          "Modules": 1
        },
        "WorkspacePackages": {
          "Packages": 1,
          "LargestPackage": 1,
          "CompiledGoFiles": 1,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-11-21 01:45
Duplicate of https://github.com/golang/go/issues/68334. Please upgrade to Go 1.22.6 or later.

**Closed by findleyr** 2024-11-21 01:45 UTC
Labels: gopls, Tools
