### ISSUE TITLE
cmd/compile: interface conversion with generics reports "types from different scopes" [1.18 backport] 

### ISSUE THREAD

**Issue by fractalqb** [golang/go#53883] opened 2022-07-14 16:04 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/USER/.cache/go-build"
GOENV="/home/USER/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/USER/gows/pkg/mod"
GONOPROXY="athome.fractalqb.de"
GONOSUMDB="athome.fractalqb.de"
GOOS="linux"
GOPATH="/home/USER/gows"
GOPRIVATE="athome.fractalqb.de"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/USER/bin/go1.18.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/USER/bin/go1.18.4/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/USER/gows/src/git.fractalqb.de/proto/different-scopes-1.18.3/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build131321195=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
1. Compile this code
```
package main

import (
	"fmt"

	"github.com/fractalqb/change"
	"github.com/fractalqb/change/chgsql"
)

var id change.Val[uint64]

func main() {
	v := chgsql.Nullable[uint64](&id, 0)
	fmt.Println(v)
}
```

2. Run the program
```
$ ./different-scopes
panic: interface conversion: change.Changeable[go.shape.uint64_0] is *change.Val[uint64], not *change.Val[uint64] (types from different scopes)

goroutine 1 [running]:
github.com/fractalqb/change/chgsql.Nullable[...](...)
	/home/USERgows/pkg/mod/github.com/fractalqb/change@v0.4.1/chgsql/type.go:27
main.main()
	/home/USER/gows/src/git.fractalqb.de/proto/different-scopes-1.18.3/main.go:16 +0x2e
```

### What did you expect to see?
When running the program I expect the output to be: `<nil>`

When compiling and running with Go 1.18.2 it works as expected. Please also read my remarks on https://github.com/golang/go/issues/52027

### What did you see instead?
As already mentioned above. Running the Program (compiled with 1.8.4) gives me the output:

```
panic: interface conversion: change.Changeable[go.shape.uint64_0] is *change.Val[uint64], not *change.Val[uint64] (types from different scopes)

goroutine 1 [running]:
github.com/fractalqb/change/chgsql.Nullable[...](...)
	/home/USERgows/pkg/mod/github.com/fractalqb/change@v0.4.1/chgsql/type.go:27
main.main()
	/home/USER/gows/src/git.fractalqb.de/proto/different-scopes-1.18.3/main.go:16 +0x2e
```

**Comment by mknyszek** [comment] 2022-07-14 16:11
CC @golang/compiler

**Comment by dr2chase** [comment] 2022-07-14 17:59
So, works okay at go1.19 tip, does not work with the revert to the cause of #53852.
```
* 2aab162041 (HEAD) Revert "[release-branch.go1.18] cmd/compile: fix missing dict pass for type assertions"
* 460a93b54a [release-branch.go1.18] cmd/compile: fix missing dict pass for type assertions
* 3da88c0bdc [release-branch.go1.18] cmd/compile: fix wrong unsafe.Offsetof evaluation inside generic function
* f0eca661ea [release-branch.go1.18] runtime: store consistent total allocation stats as uint64
* 4068be56ce (tag: go1.18.3) [release-branch.go1.18] go1.18.3
```

**Comment by dr2chase** [comment] 2022-07-14 18:04
This is strengthening the case for "generics backports considered harmful".

**Comment by mdempsky** [comment] 2022-07-14 18:08
Adding yet further questions, I think the assert added in that CL is backwards: `base.Assertf(typ.Kind() == types.TNIL, "unexpected untyped nil")`

But then why are we ending up with a runtime panic, rather than an ICE.

**Comment by ernado** [comment] 2022-07-14 21:38
Same as #53376?

**Comment by ernado** [comment] 2022-07-14 21:45
IMO this should be fixed in go1.18.5 as unfortunate regression, because this works in go1.18.2.

Probably with reverting some backported CL-s that have introduced this between go1.18.2 and go1.18.3.

If not, there is workaround to use 
```go
func f[T a, C A[T]](foo T, bar C)
``` 

Instead of 
```go
func f[T a](foo T, bar A[T])
```

**Closed** 2022-07-27 16:55 UTC
Labels: CherryPickApproved, generics, compiler/runtime
