### ISSUE TITLE
runtime: 0xdeaddeaddeaddead crash

### ISSUE THREAD

**Issue by bradfitz** [golang/go#14667] opened 2016-03-06 02:29 UTC
linux-amd64 trybot crash here, with git parent 783741844b48ebbe6b575369c915bfc1c6e53972:

https://storage.googleapis.com/go-build-log/ea276538/linux-amd64_e00cadd4.log

```
...
ok  	crypto/subtle	0.006s
unexpected fault address 0x0
fatal error: fault
[signal 0x7 code=0x80 addr=0x0 pc=0x55c755]

goroutine 36 [running]:
runtime.throw(0x70f852, 0x5)
	/tmp/workdir/go/src/runtime/panic.go:566 +0x8c fp=0xc8201ed2b0 sp=0xc8201ed298
runtime.sigpanic()
	/tmp/workdir/go/src/runtime/sigpanic_unix.go:21 +0xe8 fp=0xc8201ed300 sp=0xc8201ed2b0
math/big.nat.cmp(0xdeaddeaddeaddead, 0x9, 0x1e, 0xc82007a410, 0x9, 0xa, 0x9)
	/tmp/workdir/go/src/math/big/nat.go:162 +0x45 fp=0xc8201ed308 sp=0xc8201ed300
math/big.nat.div(0x0, 0x0, 0x0, 0xdeaddeaddeaddead, 0x9, 0x1e, 0xdeaddeaddeaddead, 0x9, 0x1e, 0xc82007a410, ...)
	/tmp/workdir/go/src/math/big/nat.go:525 +0x7b fp=0xc8201ed3c8 sp=0xc8201ed308
math/big.(*Int).QuoRem(0xc8201ed4b0, 0xc8203ac200, 0xc82000e920, 0xc8203ac200, 0xc820012840, 0xc82039c920)
	/tmp/workdir/go/src/math/big/int.go:227 +0xaf fp=0xc8201ed478 sp=0xc8201ed3c8
math/big.(*Int).Mod(0xc8203ac200, 0xc8203ac200, 0xc82000e920, 0xc82039c8a0)
	/tmp/workdir/go/src/math/big/int.go:258 +0xcf fp=0xc8201ed4f8 sp=0xc8201ed478
crypto/ecdsa.Verify(0xc8201b1900, 0xc8201b1de0, 0x14, 0x20, 0xc8201b1e00, 0xc8201b1e20, 0x0)
	/tmp/workdir/go/src/crypto/ecdsa/ecdsa.go:259 +0x405 fp=0xc8201ed608 sp=0xc8201ed4f8
crypto/tls.(*ecdheKeyAgreement).processServerKeyExchange(0xc8201aebc0, 0xc820080280, 0xc8201b23c0, 0xc8201de580, 0xc8201f0480, 0xc8201b6c30, 0x0, 0xc8201cec00)
	/tmp/workdir/go/src/crypto/tls/key_agreement.go:366 +0x796 fp=0xc8201ed738 sp=0xc8201ed608
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc8201edc50, 0xc8201cec60, 0x59)
	/tmp/workdir/go/src/crypto/tls/handshake_client.go:318 +0x416 fp=0xc8201edaa0 sp=0xc8201ed738
crypto/tls.(*Conn).clientHandshake(0xc8201cc600, 0x72a778, 0xc8201cc614)
	/tmp/workdir/go/src/crypto/tls/handshake_client.go:209 +0xec9 fp=0xc8201edd00 sp=0xc8201edaa0
crypto/tls.(*Conn).Handshake(0xc8201cc600, 0x0, 0x0)
	/tmp/workdir/go/src/crypto/tls/conn.go:1031 +0x9f fp=0xc8201edd28 sp=0xc8201edd00
crypto/tls.(*Conn).Write(0xc8201cc600, 0xc8201ede70, 0x6, 0x6, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/crypto/tls/conn.go:878 +0xdd fp=0xc8201eddb0 sp=0xc8201edd28
crypto/tls.(*clientTest).run.func1(0xc8201cc600, 0xc82013ecf0, 0xc8201c6b80, 0x7fc10778e7e0, 0xc8201b49a0, 0xc8201ceae0)
	/tmp/workdir/go/src/crypto/tls/handshake_client_test.go:212 +0x8a fp=0xc8201edf60 sp=0xc8201eddb0
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2006 +0x1 fp=0xc8201edf68 sp=0xc8201edf60
created by crypto/tls.(*clientTest).run
	/tmp/workdir/go/src/crypto/tls/handshake_client_test.go:223 +0x210

goroutine 1 [chan receive]:
testing.RunTests(0x72a0e8, 0x83d3e0, 0x41, 0x41, 0xc820080201)
	/tmp/workdir/go/src/testing/testing.go:582 +0x359
testing.(*M).Run(0xc820031f08, 0x404cda)
	/tmp/workdir/go/src/testing/testing.go:515 +0x79
main.main()
	crypto/tls/_test/_testmain.go:184 +0xb4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2006 +0x1

goroutine 35 [semacquire]:
sync.runtime_Syncsemacquire(0xc8201c84c0)
	/tmp/workdir/go/src/runtime/sema.go:241 +0x1a0
sync.(*Cond).Wait(0xc8201c84b0)
	/tmp/workdir/go/src/sync/cond.go:63 +0x69
io.(*pipe).read(0xc8201c8480, 0xc8201055f0, 0x86, 0x86, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/io/pipe.go:52 +0xdc
io.(*PipeReader).Read(0xc8201ca040, 0xc8201055f0, 0x86, 0x86, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/io/pipe.go:134 +0x42
io.ReadAtLeast(0x7fc10778e840, 0xc8201b49b0, 0xc8201055f0, 0x86, 0x86, 0x86, 0x0, 0x0, 0x7fc10778e840)
	/tmp/workdir/go/src/io/io.go:297 +0xa3
io.ReadFull(0x7fc10778e840, 0xc8201b49b0, 0xc8201055f0, 0x86, 0x86, 0x86, 0x0, 0x0)
	/tmp/workdir/go/src/io/io.go:315 +0x4e
crypto/tls.(*clientTest).run(0xc8201c6b80, 0xc82013ecf0, 0x0)
	/tmp/workdir/go/src/crypto/tls/handshake_client_test.go:236 +0x7f0
crypto/tls.runClientTestForVersion(0xc82013ecf0, 0xc820033f00, 0x6f0ee0, 0x7, 0x6f0ce1, 0x5)
	/tmp/workdir/go/src/crypto/tls/handshake_client_test.go:277 +0x245
crypto/tls.runClientTestTLS10(0xc82013ecf0, 0xc820033f00)
	/tmp/workdir/go/src/crypto/tls/handshake_client_test.go:281 +0x55
crypto/tls.TestHandshakeClientECDHEECDSAAES(0xc82013ecf0)
	/tmp/workdir/go/src/crypto/tls/handshake_client_test.go:335 +0xf1
testing.tRunner(0xc82013ecf0, 0x83d488)
	/tmp/workdir/go/src/testing/testing.go:473 +0x7e
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:581 +0x313
FAIL	crypto/tls	0.155s
ok  	crypto/x509	1.621s
...
```

**Comment by mikioh** [comment] 2016-03-07 06:36
Not sure whether this is a duplicate of #14591.

**Comment by randall77** [comment] 2016-03-09 02:56
Pretty sure this is a dup of #14591.  Closing.

**Closed by randall77** 2016-03-09 02:56 UTC
