### ISSUE TITLE
cmd/go: don't cache tests that use testing/quick.Check and friends

### ISSUE THREAD

**Issue by ainar-g** [golang/go#26276] opened 2018-07-08 18:40 UTC
### Does this issue reproduce with the latest release?
    go version devel +b001ffb Sun Jul 8 04:14:45 2018 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ainar/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ainar/go"
GORACE=""
GOROOT="/home/ainar/go/go1.10"
GOTMPDIR=""
GOTOOLDIR="/home/ainar/go/go1.10/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build505661023=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
https://play.golang.org/p/e6SHcVstHOW

```
$ go test foo_test.go
$ go test foo_test.go
$ go test foo_test.go
```

### What did you expect to see?
```
ok  	command-line-arguments	0.002s
ok  	command-line-arguments	0.001s
ok  	command-line-arguments	0.003s
```

### What did you see instead?
```
ok  	command-line-arguments	0.002s
ok  	command-line-arguments	(cached)
ok  	command-line-arguments	(cached)
```

My assumption here is that the people who use `testing/quick` want the tests to run as often as possible to maximise the potential of finding a bug. Caching the first successful result thus seems counterproductive. I know that the official way to disable caching for tests is `-count 1`, but it seems silly to provide a randomised testing package and than have it be almost useless by default.

If the consensus _is_ that the people who use `testing/quick` should just also use `-count 1`, then I think it would be nice to reflect that in the package documentation.

**Comment by rsc** [comment] 2018-08-10 02:29
Duplicate of #23799, essentially, with the same likely answer: no.

**Comment by rsc** [comment] 2018-08-10 02:30
In particular see my response https://github.com/golang/go/issues/23799#issuecomment-411934400.

**Closed by rsc** 2018-08-10 02:29 UTC
Labels: NeedsInvestigation
