### ISSUE TITLE
cmd/tool/pprof: add history

### ISSUE THREAD

**Issue by bogem** [golang/go#17052] opened 2016-09-10 12:30 UTC
I think, it would be great to have a history of commands in `pprof` like in `bash` and navigate them with arrows.
Now, when you tap an arrow top, `pprof` prints these symbols:
![2016-09-10 17 29 24](https://cloud.githubusercontent.com/assets/13235519/18410419/0e05b452-777c-11e6-8b41-07f9faf55f14.png)
But I would like to have a previous command, when I tap an arrow top.
I think, it would be more convenient to the `pprof` with this functionality.

**Comment by valyala** [comment] 2016-09-10 12:41
Duplicate of #14041 ?

**Closed** 2016-09-10 13:22 UTC
