### ISSUE TITLE
net/url: No adequate method exists for encoding a URI component

### ISSUE THREAD

**Issue by alienth** [golang/go#16207] opened 2016-06-29 03:38 UTC
1. What version of Go are you using (`go version`)?
1.6.2

2. What operating system and processor architecture are you using (`go env`)?
linux amd64

3. What did you do?
https://play.golang.org/p/loaa8vvCli
Attempted to use net/url to encode a component of a URI which contained both forward-slashes and whitespace.

4. What did you expect to see?
A method akin to JS `encodeURIcomponent` which would encode the component the way I need.

5. What did you see instead?
No solution, as of yet.

I'm interacting with an API where I need to escape individual URI components. In my specific case, I'm escaping components containing whitespace and forward slashes. As demonstrated above, `net/url` seems to have no method which I can use to accomplish this. Any `url.Parse()` related function will ignore forward slashes, as it should. I also can't rely on something such as `url.QueryParse()`, as query string encoding turns whitespace into `+`.

Would it be possible for `net/url` to add functionality akin to JS's `encodeURIcomponent` to cover cases such as this?

**Comment by alienth** [comment] 2016-06-29 03:45
Closing as this is not a bug, but lack of functionality. Will look at a proposal or something along those lines.

**Comment by alienth** [comment] 2016-06-29 03:51
Closed this initially as the 'Asking Questions' doc suggested that GH Issues are for bugs only. However the [proposals doc](https://github.com/golang/proposal#process) indicates I should create an issue. There is some disagreement there so I'm not sure how I should proceed. If there is a better place for me to raise this issue, please let me know and I'll happily take it there.

**Comment by ianlancetaylor** [comment] 2016-06-29 15:54
We use the issue tracker both for bugs and for proposals.  That is what https://golang.org/wiki/Questions says, so I'm not clear on the disagreement you mention.

**Comment by alienth** [comment] 2016-06-29 17:54
@ianlancetaylor Sorry, misread some instruction on this. Please disregard.

**Comment by quentinmit** [comment] 2016-10-07 20:11
This appears to be a dupe of #13737. Unfortunately, a suitable function does not currently exist.

**Closed by quentinmit** 2016-10-07 20:11 UTC
