### ISSUE TITLE
path/filepath: join function does not allow UNC for pipe

### ISSUE THREAD

**Issue by kayila** [golang/go#23467] opened 2018-01-17 22:51 UTC
The path has to start with `\\.\pipe\` for named pipes on Windows, but `filepath.Join()` removes the leading `\\.`.

### What version of Go are you using (`go version`)?

1.9.1

### Does this issue reproduce with the latest release?

Yes. (1.9.2, as of opening this issue.)

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=".exe"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="windows"
GOPATH="/home/kayila/go"
GORACE=""
GOROOT="/usr/lib/go-1.7"
GOTOOLDIR="/usr/lib/go-1.7/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build187455838=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="0"
```

### What did you do?

```go
package main

import (
	"fmt"
	"path/filepath"
)

func main() {
	fmt.Println(filepath.Join("\\\\.", "pipe", "blah"))
	fmt.Println(filepath.Join("\\\\.\\pipe", "blah"))
}
```

### What did you expect to see?

    \\.\pipe\blah
    \\.\pipe\blah

### What did you see instead?

    \pipe\blah
    \pipe\blah

**Comment by cznic** [comment] 2018-01-18 10:36
If you know, that a named pipe on Windows has a special prefix that intentionally does comply with `filepath.Clean` rules, just use

```go
`\\.\` + filepath.Join("pipe", "blah")
```

ie. don't pass the special prefix to `filepath.Join` that's documented to `Clean` the result.

**Comment by alexbrainman** [comment] 2018-01-20 04:45
@kayila yes path/filepath package does not support pipe names. But it also does not support paths starting with `\\?\` either (which are more common).

https://golang.org/doc/contribute.html if you decide to add missing functionality.

Alex

**Comment by qmuntal** [comment] 2023-05-16 18:27
Can't reproduce in go1.20. Probably fixed by [CL 444280](https://go-review.googlesource.com/c/go/+/444280).

**Closed by qmuntal** 2023-05-16 18:27 UTC
Labels: OS-Windows, NeedsFix
