### ISSUE TITLE
Darwin-Arm from source

### ISSUE THREAD

**Issue by Merith-TK** [golang/go#32818] opened 2019-06-27 21:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="arm"
GOBIN=""
GOCACHE="/home/merith/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="darwin"
GOPATH="/home/merith/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
GOARM="5"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build625899950=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Trying to compile go from source for `darwin arm` using the source code on this repo 
<pre>
[merith@archlinux go]$ git status
HEAD detached at go1.12.6
nothing to commit, working tree clean
</pre>

Host is archlinux
### What did you expect to see?
Success ful compile

### What did you see instead?
These two errors

CGO_ENABLED=0
https://pastebin.com/mh8gBD9e

CGO_ENABLED=1
https://pastebin.com/jgQnCknk

### Additonal notes.
I do think i am missing a huge dependency here for this.

**Comment by andybons** [comment] 2019-06-28 00:48
Duplicate of #16801

**Closed by andybons** 2019-06-28 00:48 UTC

**Comment by Merith-TK** [comment] 2019-06-28 02:10
Thanks, kinda surprised this isnt in faq

**Comment by Merith-TK** [comment] 2019-08-09 22:10
Actually, this is not a dupe

That is for Linux-Arm.
Not Darwin-Arm, 

Two completely separate kernels and environments

**Comment by ianlancetaylor** [comment] 2019-08-09 22:58
It's the same problem, though: you need a cross-compiler.
