### ISSUE TITLE
go list: version query returns invalid version

### ISSUE THREAD

**Issue by BastienFaure** [golang/go#66657] opened 2024-04-03 03:21 UTC
### Go version

go version go1.20.14 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/marauder/.cache/go-build"
GOENV="/home/marauder/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/marauder/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/marauder/.go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.14"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1135361802=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

I tried to install the latest version of `bloodhound/azurehound` but I always ended up with the wrong version of the package installed. I figured I could perform a version query manually to figure out to what tag specifically `latest` did resolve:

```bash
$ go list  -m github.com/bloodhoundad/azurehound@latest
```

### What did you see happen?

The command above returned the following output:
```
github.com/bloodhoundad/azurehound v1.2.4
```

### What did you expect to see?

The repository has many tags higher than `1.2.4`, the latest one being `2.1.8`:
```
$ git ls-remote --tags origin
71f631448e47c50d3e41e898ae03a73597c0bf03	refs/tags/rolling
c31d34892044c782defcd07751ae2c324879d5c5	refs/tags/v1.1.1
27f60cc277db2884e4f64fbbd1a4c4cc37b35350	refs/tags/v1.1.2
820f7948d2b15fffe5c97ea129f6edfe18af4bbc	refs/tags/v1.1.3
dcbf0fc6a88ec0af9e7d91f4f33e84cbe6a6faba	refs/tags/v1.2.0
a6ff55b9561f881fd4fbc74770267cf4876f6b42	refs/tags/v1.2.1
33bb4f0dab469493c8927f164777d614a3675acb	refs/tags/v1.2.2
a942107766d6ad2b2f9954ac9087418245c0e754	refs/tags/v1.2.3
e6f62d1c0ddd4c11bb9531ffcce69073327b599b	refs/tags/v1.2.4
b3a75f370381ed9dc3c2930e206cdd112d3e7622	refs/tags/v1.2.4^{}
60e31176f8b1bb0fc80c44bede30710b4ebed994	refs/tags/v2.0.0
2e39b1ca6d4913a570b9da30b141c917921163f8	refs/tags/v2.0.1
2379ab55f4a5c12ed2cae977ab33a2d59f5a0192	refs/tags/v2.0.2
18e629ecf4cf63f4fea815d4307bb8659e381a9d	refs/tags/v2.0.3
74ccf0fbfeba132f1f10ec2ae3fd535f99305bc2	refs/tags/v2.0.4
8eda432a103d7205937bb1c146a0579aab8106cc	refs/tags/v2.0.5
d2ff1b66bcd343e615255f37ca08fcd018b3b6a4	refs/tags/v2.1.0
c4637f89fba73dbb5d725a695bcdda88efbbe701	refs/tags/v2.1.1
a4a6de574091e4d17fbbaa7479400846a2bf1a3c	refs/tags/v2.1.2
1dd97b0e20c42ebf029c99d290472a6c4fc4d867	refs/tags/v2.1.3
2ffd8e9c749880c602464ac90add8511a934aab1	refs/tags/v2.1.4
06a6d182e2e061df871ebbbd2865f132bbeb633a	refs/tags/v2.1.5
faeb09f8cb6d397a6f97a8f4c61da28441f30c35	refs/tags/v2.1.6
937a90a18b43e32d5e70e4bc9c6009e9ecd78e80	refs/tags/v2.1.7
6889fa8e819e6f39930ebb58bd00e29506e20822	refs/tags/v2.1.8
```

I did noticed the pair of braces around 1.2.4 which might have something to do with that but according to https://go.dev/ref/mod#version-queries, `latest` is supposed to selected the highest release, which should be `2.1.8`, if I didn't miss anything obvious.

**Comment by seankhliao** [comment] 2024-04-03 04:10
Closing as working as intended.
1.2.4 is the highest v1 version.
Go requires major version suffixes for v2+.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Closed by seankhliao** 2024-04-03 04:10 UTC

**Comment by timothy-king** [comment] 2024-04-03 04:19
Try `go list -m github.com/bloodhoundad/azurehound/v2@latest`.

**Comment by BastienFaure** [comment] 2024-04-03 04:49
@seankhliao @timothy-king  thank you for the quick feedback. From my pair of shoes it was a bug, that’s why I opened the issues. TIL
