### ISSUE TITLE
all: port to Windows/arm64

### ISSUE THREAD

**Issue by vielmetti** [golang/go#36439] opened 2020-01-07 21:15 UTC
Opening this issue to track interest and progress in a port to windows/arm64.

This is completely separate from the open issue #26148 (windows/arm32) but might be informed by it.

The specific codebase I'm motivated by for this request is for WireguardVPN, and the specific discussion to reference is https://lists.zx2c4.com/pipermail/wireguard/2020-January/004832.html & surrounding.

**Comment by carlosedp** [comment] 2020-01-11 16:00
What is the best option for hardware to run Windows on arm64? Does it run on a RK3399 SoC board like the Pine64 Pro?

**Comment by vielmetti** [comment] 2020-01-11 21:03
@carlosedp All of the Windows 10 on Arm laptops that I am aware of to date are Qualcomm Snapdragon based. My daily driver laptop is a Lenovo Yoga C630, and there's a relatively new Microsoft Surface Pro X with a faster chip.

It looks like some work to get the boot sequence for rk3399 boards compatible with Windows lives at https://github.com/andreiw/rk3399-edk2 by @andreiw - with liberal warnings of things that still don't work.

**Comment by driver1998** [comment] 2020-01-12 03:10
It can also run on KVM, I actually do my ARM64 dev on a KVM VM on RK3399.

**Comment by clarkezone** [comment] 2020-01-20 18:11
I would love to see an ARM64 version of go for Windows 10 so I can run it natively on the Surface Pro X

**Comment by necrose99** [comment] 2020-02-13 06:49
https://github.com/golang/go/issues/25084 same deal.

**Comment by necrose99** [comment] 2020-02-13 07:25
https://github.com/mitchellh/gox/issues/140 
platform.go and a few hax... latter. 
https://github.com/golang/winstrap 
ahh poohh but did not get an arm64  windows-arm  build of gox... how nice. 
[winstrap-master_windows_arm.zip](https://github.com/golang/go/files/4196958/winstrap-master_windows_arm.zip)

might help...

**Comment by backerman** [comment] 2020-02-21 05:01
> I would love to see an ARM64 version of go for Windows 10 so I can run it natively on the Surface Pro X:
> ![image](https://user-images.githubusercontent.com/1128250/72748928-76461580-3b6d-11ea-9679-5cae244a4888.png)
> 
> Is what I'm currently seeing so it won't even run in emulation on this device or so it would seem.

Did you use the 32- or 64- bit download? The 32-bit x86 version should run in emulation.

**Comment by necrose99** [comment] 2020-02-21 23:21
my windows wants is any golang honeypots and RPI3/4 makes for good decoys/bait... 
/topSec SBC's are less expensive to utilize emulation meh..

**Comment by anaisbetts** [comment] 2020-03-02 05:20
@clarkezone fwiw, the 32-bit x86 version of Go's installer seems to work, at least from my limited testing (I'm not a Go user, I just wanted to build a Go app)

**Comment by bradfitz** [comment] 2020-03-02 15:48
Reposting @anaisbetts's comment from elsewhere:

> So, one thing to know about ARM64 on Windows is, it actually fully emulates x86 (*not* amd64, 32-bit apps oddly enough) for user-space apps - they Just Work (most of the time! kinda!)  
>
> So, with a bit of sleight-of-hand packaging, you can make an "ARM64" release that still mostly has x86 binaries

(I'm not sure what the performance cost of that is, though.)

**Comment by zx2c4** [comment] 2020-05-13 11:36
One reason why windows/arm isn't sufficient is that several important APIs -- such as all of setupapi.dll, for example -- are unavailable in wow mode, which means we need actual arm64 binaries.

It's quite possible to get windows running on arm64 in qemu, by the way.

**Comment by taxilian** [comment] 2020-06-06 22:28
I'd love to see this as well, wanting to build some tools for my surface pro x

**Comment by zx2c4** [comment] 2020-06-07 04:25
@jstarks Any word on this?

**Comment by jstarks** [comment] 2020-06-07 18:50
We (the OS team at Microsoft) would love to see this, too, and we would be open to contributing the code for the port. Unfortunately, we're not in a position to commit to [long-term maintenance](https://github.com/golang/go/wiki/PortingPolicy) of the code or associated builder right now, so we are hesitant to send out any patches.

If Google or the Golang community would be interesting in taking on the ongoing maintenance cost, we would be happy to collaborate on the development.

**Comment by zx2c4** [comment] 2020-06-07 19:49
@jstarks Just like we're (Alex, me, Google employees) are already helping to maintain the other 3 Windows ports (386, amd64, arm), I don't see any reason why we couldn't do the same for arm64. I've got Windows running in QEMU/arm64 now for Wintun development, and that works well.

**Comment by bradfitz** [comment] 2020-06-07 20:08
> @jstarks Just like we (Alex, me, Google employees) are already helping to maintain the other 3 Windows ports (386, amd64, arm), I don't see any reason why we couldn't do the same for arm64.

windows/arm is actually a counterexample. Its builder disappeared and it bit rot. We're not not even sure it works anymore. There have been reports it doesn't.

In any case, @jstarks, the builders are the main issue, more than maintenance. If we have reliable & plentiful builders, the Go team & community can help keep it working. But absent builders it'll just rot.

How does Microsoft test? Does windows/arm{,64} run on Azure perhaps?

**Comment by zx2c4** [comment] 2020-06-07 20:11
> windows/arm is actually a counterexample. Its builder disappeared and it bit rot. We're not not even sure it works anymore. There have been reports it doesn't.

The arm port works. @rozmansi got WireGuard/Wintun ported to it. Unfortunately, WOW has its limitations and we really need arm64 to access the APIs that we need (setupapi.dll, for example).

**Comment by zx2c4** [comment] 2020-06-07 20:16
> How does Microsoft test? Does windows/arm{,64} run on Azure perhaps?

I'd too be interested to learn if Microsoft has some nice solutions for this.

But in case not, @rozmansi and I can probably help getting the QEMU setup via TCG running smoothly in gcloud like the current set of builders. Or if we actually need additional performance, we could look if ec2's arm64 VMs support nested KVM, or grab a ThunderX machine from Scaleway and run KVM over there.

**Comment by bradfitz** [comment] 2020-06-07 20:17
> The arm port works. 

On which branch? Go 1.14 only or even master? (And the fact that we even have to ask is a ridiculous situation to be in.)

**Comment by zx2c4** [comment] 2020-06-07 20:18
> > The arm port works.
> 
> On which branch? Go 1.14 only or even master? (And the fact that we even have to ask is a ridiculous situation to be in.)

Haven't looked at git master in sometime. Could give it a whirl I suppose.

**Comment by bradfitz** [comment] 2020-06-07 20:19
> But in case not, @rozmansi and I can probably help getting the QEMU setup via TCG running smoothly in gcloud like the current set of builders. 

Go is moving towards having all its arm & arm64 builders on Amazon. EC2 has nice ARM instance types nowadays.

If you can get windows/arm and windows/arm64 booting in qemu[/kvm] there, that'd be great. Then it's just a question of Windows licensing, which perhaps @jstarks et al could help with.

**Comment by jstarks** [comment] 2020-06-08 03:28
This sounds promising. I'll check on what options are available and if there are licensing implications.

**Comment by zx2c4** [comment] 2020-06-08 23:39
![image](https://user-images.githubusercontent.com/10643/84090409-f0592880-a9ae-11ea-83a9-5edf84b9a20a.png)

@rozmansi's overall setup works pretty well for me.

**Comment by zx2c4** [comment] 2020-06-09 01:02
And by the way @bradfitz, I can confirm that arm32 still works properly when building little programs using the latest git master.

**Comment by zx2c4** [comment] 2020-06-10 03:56
@jstarks @bradfitz @alexbrainman @aclements @ianlancetaylor @cherrymui - by now you each should have received @rozmansi's VM image and instructions from me. @bradfitz was the one who suggested we get an arm64 builder up and running, but he doesn't work for Google anymore, so I assume he isn't in a position to put coins in the Go builder EC2/GCP machine. I'm not familiar with how the Go team works enough to @ the right person. Can somebody more knowledgeable about processes lay out the next steps?

**Comment by bradfitz** [comment] 2020-06-10 04:00
@cagedmantis, @toothrot and @dmitshur work on builder stuff.

**Comment by zx2c4** [comment] 2020-06-10 04:01
Great, I'll get the VM info over to them too.

**Comment by elachlan** [comment] 2020-07-11 00:53
Has there been any more progress on this?

**Comment by zx2c4** [comment] 2020-07-11 00:56
@jstarks Specifically, were the actions that Google has begun to take w.r.t. getting the arm builders up sufficient to convince your team that contributing the in-progress arm64 port is worth while?

**Comment by cagedmantis** [comment] 2020-07-13 15:16
@elachlan The release team has been working on preparing the next release. Once we get out of [release freeze period](https://github.com/golang/go/wiki/Go-Release-Cycle#june-1--december-1-beta-1-issued) we  hope to be adding the builders.

**Comment by cagedmantis** [comment] 2020-08-24 22:42
@Alovchin91 We are working out the licensing. As soon as it's worked out we can move forward by adding the builders.

**Comment by mirogl** [comment] 2020-09-26 09:27
Hi ,
today I found Go for Windows arm64 - https://github.com/thongtech/go-windows-arm64 
Does this help to unblock the development ?
Thanks

**Comment by ysc3839** [comment] 2020-09-26 10:18
@mirogl Looks like that repo has no changes to source code compared to go 1.15.2. Does it means golang already supported windows arm64?

**Comment by mirogl** [comment] 2020-09-26 10:21
@ysc3839 - I don't know - I just found the repo today and the binary package from this page is running fine on my Surface Pro X  - https://github.com/thongtech/go-windows-arm64/releases/download/1.15.2/go1.15.2.windows-arm64.zip

**Comment by ysc3839** [comment] 2020-09-26 10:38
@mirogl The binary is arm instead of arm64.
```
$ file go.exe
go.ex_: PE32 executable (console) ARMv7 Thumb (stripped to external PDB), for MS Windows
```

An arm64 binary built using MSVC:
```
$ file TestARM64.exe
TestARM64.exe: PE32+ executable (GUI) Aarch64, for MS Windows
```

**Comment by mirogl** [comment] 2020-09-26 10:43
Hi @ysc3839 - thanks - I created an issue with your questions - https://github.com/thongtech/go-windows-arm64/issues/1
Hopefully he will answer them. Sorry for the confusion - just found the repo and was happy it run on my Surface Pro X and I could als build a go project.

**Comment by mirogl** [comment] 2020-09-26 12:41
Hi @ysc3839 - he responded in the issue I linked below - so he just cross compiled it for arm32 with zero changes on the official code.
Thanks for your hint.

**Comment by tlockley** [comment] 2020-11-02 19:29
Hi all, has there been any sort of progress on this? There are a lot of us eagerly waiting for golang to be able to build for ARM64 on Windows.

**Comment by cagedmantis** [comment] 2020-11-02 21:06
@tlockley The Go team is continuing to work with Microsoft in an effort to establish some windows/arm64 builders. We will post an update as soon as we have more news.

**Comment by zx2c4** [comment] 2020-11-24 12:12
> We (the OS team at Microsoft) would love to see this, too, and we would be open to contributing the code for the port. Unfortunately, we're not in a position to commit to [long-term maintenance](https://github.com/golang/go/wiki/PortingPolicy) of the code or associated builder right now, so we are hesitant to send out any patches.
> 
> If Google or the Golang community would be interested in taking on the ongoing maintenance cost, we would be happy to collaborate on the development.

Hi @jstarks - now that we've got an ARM(64) builder, would you be interested in contributing that code?

**Comment by codemodify** [comment] 2020-12-09 15:51
Where to find the the arm64 support for windows / mac and if it is in progress how to contribute ? testing/coding etc

**Comment by zx2c4** [comment] 2020-12-09 15:54
> Where to find the the arm64 support for windows / mac and if it is in progress how to contribute ? testing/coding etc

This bug concerns only windows.

The windows arm64 port has not yet materialized. We're waiting in @jstarks's team.

**Comment by codemodify** [comment] 2020-12-09 16:01
Thank you, I can use a custom build for windows, even a non-official one and help support if needed

**Comment by awakecoding** [comment] 2020-12-18 13:21
+1 for me, not because I am a Go developer, but because the language is used by so many projects out there, including Docker. I would like to get a native build of the Docker CLI for Windows ARM64 usable with a remote host, but I hit a wall when I realized that Go didn't yet support Windows ARM64.

**Comment by rsc** [comment] 2021-02-02 14:24
Hi all. I have the latest Go tree running on a Surface Pro X (windows/arm64).
I will send CLs for inclusion in Go 1.17. 
A little more work is left to support mingw-based cgo,
but all the actual cgo support code works since we use it for system calls.
Profiling works, and I may have fixed profiling on windows/arm (32-bit) as well.

**Comment by zx2c4** [comment] 2021-02-02 14:40
Hi Russ -- holy smokes, nice job! That was fast. Did you see Microsoft's previous efforts, by the way? https://github.com/ms-iot/go/tree/win-arm64

Can't wait to start looking at your CLs. Feel free to mark me as reviewer and I'll read the series.

**Comment by rsc** [comment] 2021-02-02 14:45
@jstarks, the native windows/arm64 mode on the Surface Pro X has been great.
But windows/arm (32-bit) doesn't run right, despite working on @zx2c4's 32-bit builder.
And windows/386 doesn't pass all its tests, due to what appear to be floating-point inaccuracies in the simulation.
I haven't tried windows/amd64 - not sure if I have the update that enabled x64 emulation.

I would really love if I could use the Surface Pro X to test all four Windows architectures.
Is there anyone or any place that I can send details about emulation issues that might result in fixes?
Thanks!

**Comment by rsc** [comment] 2021-02-02 14:45
@zx2c4 I did see that tree, and it was helpful to see which files were likely to need changes. I didn't end up using the code but it was still great to have for reference.

**Comment by zx2c4** [comment] 2021-02-02 14:48
Regarding cgo -- AFAICT, there still isn't a gcc for windows/{arm,arm64}, but there is a mingw clang. https://github.com/mstorsjo/llvm-mingw/releases has reliable builds. I've been using these in production for some time now and found them to actually work a lot better than gcc/mingw in some cases. The linker has a few extra options more akin to MSVC's that is quite nice. Using these with cgo will take a bit of hacking though. The first problem is that it rejects the linker script that we currently pass to gcc as a workaround. I wonder, though, that given the apparent stagnation of gcc on Windows, if we should move the Go windows port to be clang-only for 1.17.

**Comment by zx2c4** [comment] 2021-02-02 14:49
> But windows/arm (32-bit) doesn't run right, despite working on @zx2c4's 32-bit builder.

What kinds of crashes are you getting? What Windows build are you running?

**Comment by rsc** [comment] 2021-02-02 15:05
@zx2c4 if we're going to switch compilers it seems like we should just use MSVC, especially now that you can apparently download the binaries for free from Microsoft. 

And yes, the abort code is wrong but I've fixed that.

**Comment by rsc** [comment] 2021-02-02 15:08
I've uploaded the tree I have (gopherbot should not send so many different messages!)
To try it out:

    git fetch https://go.googlesource.com/go refs/changes/28/288828/1 && git checkout FETCH_HEAD

**Comment by codemodify** [comment] 2021-02-02 16:02
I'm interested to get this working as well, thank you so much @rsc for the huge effort, will play with it and try

**Comment by thanm** [comment] 2021-02-02 16:50
> ... The first problem is that it rejects the linker script that we currently pass to gcc as a workaround. I wonder, though, that given the apparent stagnation of gcc on Windows, if we should move the Go windows port to be clang-only for 1.17.

linker script: FYI, I am pretty sure that problem was fixed this past December with [CL 278932](https://go-review.googlesource.com/c/go/+/278932). There may be other problems, however.

**Comment by jstarks** [comment] 2021-02-02 17:23
@rsc, this is great. Thank you.

I should be able to find someone to help with the ARM32 and x86 issues. If you want to take the details offline, then you can email me and I'll loop in the right people.

For x64 support, build >= 21277 should have it. If you don't want to update the machine to a pre-release build then you can also download a VM image and use Hyper-V.

**Comment by zx2c4** [comment] 2021-02-03 23:24
There are a few patches I need to submit upstream, but I got WireGuard running on windows/arm64, which is a fairly complex Windows apps, with tons of weird win32 things going on. So... it's working!

![image](https://user-images.githubusercontent.com/10643/106822348-48037d00-667f-11eb-92a8-e4f7ea667669.png)

**Comment by zx2c4** [comment] 2021-02-10 15:07
@rsc - I think that series might have broken amd64:

```
runtime: unexpected return pc for runtime.goexit called from 0x0
stack: frame={sp:0xc00007dfe0, fp:0xc00007dfe8} stack=[0xc00007a000,0xc00007e000)
0x000000c00007dee0:  0x010000c00005a058  0x00000164c5f497f0
0x000000c00007def0:  0x0000000000000000  0x0000000000000060
0x000000c00007df00:  0x00000164c5f40108  0x0000000000000060
0x000000c00007df10:  0x000000c00001a060  0x000000c000051f48
0x000000c00007df20:  0x0000000000b48bc0  0x0000000000000000
0x000000c00007df30:  0x000000c000051f78  0x00000000004059e5 <runtime.makechan+0x00000000000001a5>
0x000000c00007df40:  0x0000000000000060  0x0000000000000000
0x000000c00007df50:  0x000000000041b801 <runtime.gcenable+0x0000000000000041>  0x000000c00001a060
0x000000c00007df60:  0x0000000000000000  0x000000000077e780
0x000000c00007df70:  0x000000c00005a000  0x000000c00007dfd0
0x000000c00007df80:  0x000000000043bcc5 <runtime.main+0x0000000000000205>  0x0000000000b11dc0
0x000000c00007df90:  0x0000000000000000  0x000000c00001a060
0x000000c00007dfa0:  0x0000000000000000  0x0101000000000000
0x000000c00007dfb0:  0x0000000000000000  0x000000c00004a000
0x000000c00007dfc0:  0x000000c00007dfae  0x0000000000856e48
0x000000c00007dfd0:  0x0000000000000000  0x000000000046cf61 <runtime.goexit+0x0000000000000001>
0x000000c00007dfe0: <0x0000000000000000 >0x0000000000000000
0x000000c00007dff0:  0x0000000000000000  0x0000000000000000
fatal error: unknown caller pc

runtime stack:
runtime: unexpected return pc for runtime.rt0_go called from 0x52bc53fe
stack: frame={sp:0x31b85ff980, fp:0x31b85ff988} stack=[0x31b8404000,0x31b85ff980)
0x00000031b85ff880:  0x00000000004291ee <runtime.(*mheap).allocSpan+0x000000000000028e>  0x0000000000b5d7a0
0x00000031b85ff890:  0x000000c000074000  0x000000c00004a000
0x00000031b85ff8a0:  0x000000c000051430  0x000000000040e297 <runtime.mallocgc+0x0000000000000617>
0x00000031b85ff8b0:  0x000000c00004a000  0x0000000000000000
0x00000031b85ff8c0:  0x0000000000000000  0x0000000000000000
0x00000031b85ff8d0:  0x0000000000000000  0x0000000000002000
0x00000031b85ff8e0:  0x000000c000061fd8  0x000000c00004aa80
0x00000031b85ff8f0:  0x00000164c5f4b69b  0x00000031b85ff948
0x00000031b85ff900:  0x000000000046341f <runtime.(*mheap).alloc.func1+0x000000000000005f>  0x0000000000b5d7a0
0x00000031b85ff910:  0x0000000000000001  0x0000000000446600 <runtime.releasep+0x0000000000000000>
0x00000031b85ff920:  0x00000164c5f4b638  0x000000c00005a058
0x00000031b85ff930:  0x000000c00004a001  0x0000000000b48a40
0x00000031b85ff940:  0x000000c0000516e0  0x000000c0000514a8
0x00000031b85ff950:  0x000000000046b237 <runtime.morestack+0x0000000000000097>  0x000000000046af8c <runtime.rt0_go+0x000000000000014c>
0x00000031b85ff960:  0x0000000000000000  0x0000000000000000
0x00000031b85ff970:  0x000000000046afe5 <runtime.mstart+0x0000000000000005>  0x000000000046af93 <runtime.rt0_go+0x0000000000000153>
runtime.throw(0x82b535, 0x11)
        runtime/panic.go:1117 +0x79
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc00004a000, 0x0, 0x0, 0x7fffffff, 0x856c98, 0x31b85ff678, 0x0, ...)
        runtime/traceback.go:270 +0x1a85
runtime.copystack(0xc00004a000, 0x4000)
        runtime/stack.go:908 +0x311
runtime.newstack()
        runtime/stack.go:1078 +0x2b6
runtime.morestack()
        runtime/asm_amd64.s:454 +0x97
runtime.rt0_go(0x46af93, 0x52bc53fe, 0x31b85ff9b0, 0x7ff952bc53fe, 0x31b85ff9b0, 0x0, 0x7ff952bc53fe, 0x0, 0x0, 0x0, ...)
        runtime/asm_amd64.s:226 +0x14c
runtime.mstart(0x52bc53fe, 0x31b85ff9b0, 0x7ff952bc53fe, 0x31b85ff9b0, 0x0, 0x7ff952bc53fe, 0x0, 0x0, 0x0, 0x0, ...)
        runtime/asm_amd64.s:256 +0x5
runtime: unexpected return pc for runtime.rt0_go called from 0x52bc53fe
stack: frame={sp:0x31b85ff980, fp:0x31b85ff988} stack=[0x31b8404000,0x31b85ff980)
0x00000031b85ff880:  0x00000000004291ee <runtime.(*mheap).allocSpan+0x000000000000028e>  0x0000000000b5d7a0
0x00000031b85ff890:  0x000000c000074000  0x000000c00004a000
0x00000031b85ff8a0:  0x000000c000051430  0x000000000040e297 <runtime.mallocgc+0x0000000000000617>
0x00000031b85ff8b0:  0x000000c00004a000  0x0000000000000000
0x00000031b85ff8c0:  0x0000000000000000  0x0000000000000000
0x00000031b85ff8d0:  0x0000000000000000  0x0000000000002000
0x00000031b85ff8e0:  0x000000c000061fd8  0x000000c00004aa80
0x00000031b85ff8f0:  0x00000164c5f4b69b  0x00000031b85ff948
0x00000031b85ff900:  0x000000000046341f <runtime.(*mheap).alloc.func1+0x000000000000005f>  0x0000000000b5d7a0
0x00000031b85ff910:  0x0000000000000001  0x0000000000446600 <runtime.releasep+0x0000000000000000>
0x00000031b85ff920:  0x00000164c5f4b638  0x000000c00005a058
0x00000031b85ff930:  0x000000c00004a001  0x0000000000b48a40
0x00000031b85ff940:  0x000000c0000516e0  0x000000c0000514a8
0x00000031b85ff950:  0x000000000046b237 <runtime.morestack+0x0000000000000097>  0x000000000046af8c <runtime.rt0_go+0x000000000000014c>
0x00000031b85ff960:  0x0000000000000000  0x0000000000000000
0x00000031b85ff970:  0x000000000046afe5 <runtime.mstart+0x0000000000000005>  0x000000000046af93 <runtime.rt0_go+0x0000000000000153>
runtime.rt0_go(0x31b85ff9b0, 0x7ff952bc53fe, 0x31b85ff9b0, 0x0, 0x7ff952bc53fe, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        runtime/asm_amd64.s:231 +0x153

goroutine 1 [copystack, locked to thread]:
runtime.heapBitsSetType(0xc0000561b0, 0x10, 0x10, 0x7a0820)
        runtime/mbitmap.go:815 +0xc85 fp=0xc00007d430 sp=0xc00007d428 pc=0x417c85
runtime.mallocgc(0x10, 0x7a0820, 0x1, 0x0)
        runtime/malloc.go:1096 +0x617 fp=0xc00007d4b8 sp=0xc00007d430 pc=0x40e297
runtime.newobject(0x7a0820, 0x0)
        runtime/malloc.go:1177 +0x3f fp=0xc00007d4e8 sp=0xc00007d4b8 pc=0x40e77f
errors.New(...)
        errors/errors.go:59
internal/oserror.init()
        internal/oserror/errors.go:13 +0x38 fp=0xc00007d508 sp=0xc00007d4e8 pc=0x4b2df8
runtime.doInit(0xb0d020)
        runtime/proc.go:6176 +0xfd fp=0xc00007d658 sp=0xc00007d508 pc=0x44915d
runtime.doInit(0xb0f7a0)
        runtime/proc.go:6153 +0x88 fp=0xc00007d7a8 sp=0xc00007d658 pc=0x4490e8
runtime.doInit(0xb10fe0)
        runtime/proc.go:6153 +0x88 fp=0xc00007d8f8 sp=0xc00007d7a8 pc=0x4490e8
runtime.doInit(0xb0faa0)
        runtime/proc.go:6153 +0x88 fp=0xc00007da48 sp=0xc00007d8f8 pc=0x4490e8
runtime.doInit(0xb0f980)
        runtime/proc.go:6153 +0x88 fp=0xc00007db98 sp=0xc00007da48 pc=0x4490e8
runtime.doInit(0xb0f9e0)
        runtime/proc.go:6153 +0x88 fp=0xc00007dce8 sp=0xc00007db98 pc=0x4490e8
runtime.doInit(0xb0fa40)
        runtime/proc.go:6153 +0x88 fp=0xc00007de38 sp=0xc00007dce8 pc=0x4490e8
runtime.doInit(0xb11dc0)
        runtime/proc.go:6153 +0x88 fp=0xc00007df88 sp=0xc00007de38 pc=0x4490e8
runtime.main()
        runtime/proc.go:208 +0x205 fp=0xc00007dfe0 sp=0xc00007df88 pc=0x43bcc5
runtime: unexpected return pc for runtime.goexit called from 0x0
stack: frame={sp:0xc00007dfe0, fp:0xc00007dfe8} stack=[0xc00007a000,0xc00007e000)
0x000000c00007dee0:  0x010000c00005a058  0x00000164c5f497f0
0x000000c00007def0:  0x0000000000000000  0x0000000000000060
0x000000c00007df00:  0x00000164c5f40108  0x0000000000000060
0x000000c00007df10:  0x000000c00001a060  0x000000c000051f48
0x000000c00007df20:  0x0000000000b48bc0  0x0000000000000000
0x000000c00007df30:  0x000000c000051f78  0x00000000004059e5 <runtime.makechan+0x00000000000001a5>
0x000000c00007df40:  0x0000000000000060  0x0000000000000000
0x000000c00007df50:  0x000000000041b801 <runtime.gcenable+0x0000000000000041>  0x000000c00001a060
0x000000c00007df60:  0x0000000000000000  0x000000000077e780
0x000000c00007df70:  0x000000c00005a000  0x000000c00007dfd0
0x000000c00007df80:  0x000000000043bcc5 <runtime.main+0x0000000000000205>  0x0000000000b11dc0
0x000000c00007df90:  0x0000000000000000  0x000000c00001a060
0x000000c00007dfa0:  0x0000000000000000  0x0101000000000000
0x000000c00007dfb0:  0x0000000000000000  0x000000c00004a000
0x000000c00007dfc0:  0x000000c00007dfae  0x0000000000856e48
0x000000c00007dfd0:  0x0000000000000000  0x000000000046cf61 <runtime.goexit+0x0000000000000001>
0x000000c00007dfe0: <0x0000000000000000 >0x0000000000000000
0x000000c00007dff0:  0x0000000000000000  0x0000000000000000
runtime.goexit()
        runtime/asm_amd64.s:1371 +0x1 fp=0xc00007dfe8 sp=0xc00007dfe0 pc=0x46cf61
```

**Comment by zx2c4** [comment] 2021-02-10 15:46
Huh, actually, clearing ~/.cache/go-build fixed the issue? It would appear that adding these new bits to pclntab are somehow not being hashed as part of the caching system?

**Comment by zx2c4** [comment] 2021-02-12 15:27
@rsc - some notes on MSVC vs LLVM for cgo:

- LLVM for Windows was designed to generate object files that are compatible with MSVC.
- LLVM for Windows is bundled with Visual Studio now, and presumably Microsoft uses it internally for Edge, among other things.
- LLVM for Windows allows familiar GNU-style C, keeping cgo snippets easily portable.
- MSVC's C compiler is infamously limited in what it supports.
- LLVM for Windows is a tiny .zip download, easy to integrate into build systems.
- MSVC is a multi-gigabyte clunky ordeal.
- LLVM is open source.
- MSVC is closed source.

That list goes on. Given that, it seems pretty clear that the first steps for cgo support for arm/arm64 (and amd64&386 to make it consistent) would be to get LLVM/Clang running. Then all platforms are pretty much on the same playing field with flavor of C. And we'd still be able to ingest MSVC object files, since LLVM produces the same format.

Later, if somebody is tempted, we could consider calling out to MSVC instead (with its differing/limited options and all those complications). But I suspect there will be little need or desire for that, and that LLVM will be a preferable choice.

**Comment by jstarks** [comment] 2021-02-12 17:09
Presumably a significant advantage of LLVM is that it can run on Linux but target Windows. MSVC cannot do that.

However, if the LLVM invocations were made via the MSVC-compatible drivers (e.g. clang-cl), then it would presumably be easy to choose between the toolchains at runtime. Rust defaults to MSVC for its linker on Windows, but it's straightforward to use the LLVM linker instead, for example.

**Comment by zx2c4** [comment] 2021-02-25 18:16
As of several hours ago, I'm now serving Go ARM64 binaries for WireGuard for Windows -- https://download.wireguard.com/windows-client/. It uses Go 1.16 plus the current related patches, as of today, in git master backported to release-branch.go1.16. There's still one patch missing that isn't yet in master: https://go-review.googlesource.com/c/go/+/289429 . This is a humdrum fix to the linker to support .syso files for resources on windows/arm64 that @rsc reviewed during 1.16 but hasn't been submitted yet.

So far it's been pretty smooth sailing and I haven't gotten any reports of complaints of breakage, and people update fast enough that by now in the day I'd expect to know if something went wrong. So that's promising news. I've also had 24/7 stress tests running on a pair of arm64 boards for the last three weeks and haven't hit any crashes.

If anybody else would like to play around with this toolchain, a precompiled version of my 1.16 backport is available here: https://download.wireguard.com/windows-toolchain/distfiles/. The date will change as it evolves but currently there's `go1.16-linux_amd64_2021-02-25.tar.zst` for building from Linux and `go1.16-windows_amd64_2021-02-25.zip` for building from Windows. `GOOS=windows GOARCH=arm64 go build ...` gets the job done. Those prebuilts are generated with this grotesque script:

```bash
#!/bin/bash
set -e
TMP="$(mktemp -d)"
echo "Work: $TMP"
trap 'cd /; rm -rf "$TMP"; exit' INT TERM EXIT
FILENAME_LINUX="$TMP/$(git describe --tags --abbrev=0)-linux_amd64_$(date +%Y-%m-%d).tar.zst"
FILENAME_WINDOWS="$TMP/$(git describe --tags --abbrev=0)-windows_amd64_$(date +%Y-%m-%d).zip"
mkdir "$TMP/build-windows" "$TMP/build-linux"
git archive --prefix=go/ --format=tar wireguard-windows-patches | bsdtar -C "$TMP/build-windows" -xf -
git archive --prefix=go/ --format=tar wireguard-windows-patches | bsdtar -C "$TMP/build-linux" -xf -
cd "$TMP/build-windows/go/src"
GOROOT_FINAL=c:\\go GOOS=windows GOARCH=amd64 ./make.bash
cd ..
mv bin/windows_amd64/*.exe bin/
rm -rf VERSION.cache test misc src/cmd pkg/{obj,bootstrap,cmd,linux_amd64,windows_amd64} pkg/tool/linux_amd64 pkg_{dynlink,shared,testcshared_shared} api bin/{go,gofmt,windows_amd64}
cd ..
bsdtar -caf "$FILENAME_WINDOWS" go
cd "$TMP/build-linux/go/src"
GOROOT_FINAL=/usr/local/go GOOS=linux GOARCH=amd64 ./make.bash
cd ..
rm -rf VERSION.cache test misc src/cmd pkg/{obj,bootstrap,cmd,linux_amd64} pkg_{dynlink,shared,testcshared_shared} api
cd ..
bsdtar -caf "$FILENAME_LINUX" go
cd ..
rsync -vP "$FILENAME_WINDOWS" "$FILENAME_LINUX" abercrombie.zx2c4.com:/var/www/htdocs/download.wireguard.com/windows-toolchain/distfiles/
```

**Comment by maysupan** [comment] 2021-03-18 04:53
Thank!

**Comment by janftacnik** [comment] 2021-03-24 11:03
Gents,

I understand Go for Windows on ARM is not fully complete, but can somebody publish **real binaries for WOW** instead of building toolchain and very vague instructions how to build binaries on WOW ourselves ? I would love to test it, but those binaries from https://github.com/thongtech/go-windows-arm do not work for me (I have latest prerelease version of WOW, running 64bit X86 binaries with ease). Thank you in advance for any help (or explanation when I very probably missed soemthing).

**Comment by janftacnik** [comment] 2021-03-25 08:20
I want to apologize the author of https://github.com/thongtech/go-windows-arm, it works on real Windows on Arm device but not under virtual WOA on Mac Mini M1. The reason is, that it is 32 bit ! It looks like nobody is eager to post 64 bit Go binaries for Windows on Arm, we have to try to build it ourselves. I apologize for the confusion in my previous post.

**Comment by rsc** [comment] 2021-04-26 19:30
I submitted a stack of CLs to add cgo support to windows/arm64 on Friday evening, ending at b8fed48a9ae7e6229a4fdccf6aae7bc670f61aca. With those, I believe the windows/arm64 support for Go 1.17 is completed.

Closing this issue.

**Closed by rsc** 2021-04-26 19:30 UTC
Labels: NeedsInvestigation, OS-Windows, arch-arm64

**Comment by zx2c4** [comment] 2021-05-05 19:38
> I submitted a stack of CLs to add cgo support to windows/arm64 on Friday evening, ending at [b8fed48](https://github.com/golang/go/commit/b8fed48a9ae7e6229a4fdccf6aae7bc670f61aca). With those, I believe the windows/arm64 support for Go 1.17 is completed.
> 
> Closing this issue.

That's terrific. Thanks for working on that. I'll make a note to test that out in the coming weeks.

Any plans on doing the same for windows/arm? Then there'd be fully deployable capacity across all Windows platforms.

**Comment by jeremyd2019** [comment] 2022-03-21 23:48
Hi,

I have been working with [MSYS2](https://www.msys2.org) on getting packages there built for Windows on ARM64 (using clang's mingw-w64 target like llvm-mingw does).  I am curious if it would be possible to 'bootstrap' an ARM64 package of Go there (and/or if I can contribute to making that work, though I have 0 experience with Go).

Also, I am *very* interested in what options/licensing you figured out for Windows ARM64.  We are currently using a QC710 to build, but I have been trying to figure out some sort of cloud hosting situation...

**Comment by jeremyd2019** [comment] 2022-03-22 06:46
> I am curious if it would be possible to 'bootstrap' an ARM64 package of Go there (and/or if I can contribute to making that work, though I have 0 experience with Go).

Amazingly, it Just Worked.  I'm used to having to fight packages much more to get them to build 😀

**Comment by necrose99** [comment] 2022-04-03 16:14
git clone @ github.com/mh-cbon/go-msi

go mod init github.com/mh-cbon/go-msi  && go mod tidy  &&  gox -osarch="windows/arm64" 

can build on stock win11 ...  go-msi_windows_arm64.exe is produced.  

point being might be able to msi/msix an installer as well ..
