### ISSUE TITLE
Feature request: plugin close

### ISSUE THREAD

**Issue by pjebs** [golang/go#24880] opened 2018-04-16 04:50 UTC
Re: https://golang.org/pkg/plugin/

Currently the plugin package can open a plugin but can not close afterwards.

I am building an application that allows 3rd parties to develop plugins. They can be loaded using the `Open` function.

It would be desirable for the user of the application to be able to `Close` them after they no longer want to use the plugin. That way, unused memory can be freed up.

An example could be an application like an IDE such as sublime text or vscode which allow many plugins to be added and removed. Obviously these programs are not long-running, but there are other use cases where the application should be long-running.

**Comment by AlexRouSg** [comment] 2018-04-16 05:01
dupe of #20461

**Closed** 2018-04-16 05:14 UTC
