### ISSUE TITLE
affected/package: go fmt reformat code generated files (.pb.go)

### ISSUE THREAD

**Issue by trinwin** [golang/go#55157] opened 2022-09-19 21:20 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Unknown

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOOS="darwin"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.19/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sw/7t2y_9r94_5_3_5fgwbg75gm0000gn/T/go-build3258316285=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I ran `go fmt ./...` and it reformatted some comment spacing in my code generated `.pb.go` file

### What did you expect to see?
The command should not format code generated files.

**Comment by cherrymui** [comment] 2022-09-19 21:27
gofmt or the go command does not know which files are generated. It is up to the user (or the project) to decide which file should be formatted, which should not. Also, generated files usually are already well formatted.

Closing as working as intended. Thanks.

**Closed by cherrymui** 2022-09-19 21:27 UTC
