### ISSUE TITLE
Import repositories from  GitHub to GitLab

### ISSUE THREAD

**Issue by senad004** [golang/go#28958] opened 2018-11-26 18:40 UTC
Team,
I am trying to import repositories from GitHub to GitLab using Git URL . but getting below error 
fatal:  Could not read Password for 'https://*****@github.company.com': terminal prompts disabled

Appreciate your help on this.

**Comment by andybons** [comment] 2018-11-26 18:44
Thanks. This is a known issue.
Duplicate of 26232#

**Closed by andybons** 2018-11-26 18:44 UTC

**Comment by senad004** [comment] 2018-11-26 20:03
Hi Can you please help me to share few basic details about this issue?  Issue #26232 is confusing me .

**Comment by andybons** [comment] 2018-11-26 23:03
If you run `go get rsc.io/2fa`, it makes a request to https://rsc.io/2fa?go-get=1 which returns the following:

```
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="go-import" content="rsc.io/2fa git https://github.com/rsc/2fa">
<meta http-equiv="refresh" content="0; url=https://godoc.org/rsc.io/2fa">
</head>
<body>
Redirecting to docs at <a href="https://godoc.org/rsc.io/2fa">godoc.org/rsc.io/2fa</a>...
</body>
</html>
```

It uses the `<meta name="go-import" content="rsc.io/2fa git https://github.com/rsc/2fa">` tag to determine how to get the code per https://golang.org/cmd/go/#hdr-Remote_import_paths

https://rsc.io/2fa?go-get=1 MUST return the meta tag in order for the go command to determine how to retrieve the code. If it's behind any authentication, it will fail since go get doesn't have any concept of authentication (that's what the duped issue is about).
