### ISSUE TITLE
Compressing files greater than 2.5 GB trims data

### ISSUE THREAD

**Issue by mukundrv** [golang/go#19105] opened 2017-02-15 14:37 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.5 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"

### What did you do?
When I am compressing files greater than 2.5 GB , it successfully creates compressed files but when I again unzip the file and check the data, there is difference in the data. I see the contents missing after a particular line.

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

A link on play.golang.org is best.
https://play.golang.org/p/P6CnK22q40

### What did you expect to see?
I would want the whole content to be gzipped

### What did you see instead?
The gzip contains partial content not the full list of lines.

**Comment by mvdan** [comment] 2017-02-15 14:45
Note that the play link isn't a self-contained test, so the issue isn't reproducible. Perhaps use something like an `io.Reader` that just gives 3GB of garbage?

**Comment by mukundrv** [comment] 2017-02-15 15:12
The code was given for reference. I don't think it is possible to upload/create  files in playground

**Comment by mvdan** [comment] 2017-02-15 15:14
You don't need to use files. All you need are readers.

**Comment by vcabbage** [comment] 2017-02-15 16:13
I suspect `_, err = buffer.Read(rawbytes)` is the issue. `Read()` is not guaranteed to fill `rawbytes`.
> The bytes are taken from at most one Read on the underlying Reader, hence n may be less than len(p).

https://golang.org/pkg/bufio/#Reader.Read

You could use [`ioutil.ReadAll`](https://golang.org/pkg/io/ioutil/#ReadAll) to get the bytes from the source file, but it would be more efficient and idiomatic to use the `io.Reader`/`io.Writer` interfaces to stream the gzip operation. Example: https://play.golang.org/p/u6eAphPRrk

I'm going to close this issue as it does not appear to be a bug, but please feel free to reopen if I've assessed this incorrectly. For any questions on how to use `io.Reader`/`io.Writer`, please refer to https://github.com/golang/go/wiki/Questions, where you'll find a number of venues to ask questions.

**Closed by vcabbage** 2017-02-15 16:13 UTC
