### ISSUE TITLE
cmd/compile: accepts invalid function type

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11595] opened 2015-07-04 17:44 UTC
gc successfully compiles the following code:
```go
package a
var f func((i), _ int)
```
both gccgo and gotype reject it saying:
```
error: invalid named/anonymous mix
expected identifier
```
Spec does not allow parenthesis there.
go version devel +be2a3e2 Thu Jul 2 08:29:33 2015 +0000 linux/amd64

**Comment by dvyukov** [comment] 2015-07-04 17:44
@griesemer for spec treatment

**Comment by griesemer** [comment] 2015-07-04 19:42
The spec does allow parentheses around types, but not around parameter names; e.g.: func((int), (float32)) ((int)) is valid.

The example above is incorrect because it mixes parameters with names (_) and w/o names (1st parameter).

**Comment by odeke-em** [comment] 2016-07-24 08:21
I can't seem to reproduce this issue on my setup
<img width="571" alt="screen shot 2016-07-24 at 1 20 29 am" src="https://cloud.githubusercontent.com/assets/4898263/17082719/d9f33eba-513c-11e6-8140-dc998b7e0781.png">

**Comment by odeke-em** [comment] 2016-07-24 08:31
To be clear, the problem still exists on go1.6.2 but on tip (go1.7) but seems fixed
https://play.golang.org/p/QI6Cmo92sN

**Comment by griesemer** [comment] 2016-08-11 23:37
This may have been fixed a while back with https://go-review.googlesource.com/20748 . Closing.

**Closed by griesemer** 2016-08-11 23:37 UTC
