### ISSUE TITLE
golang.org/x/tools/gopls: cannot go install

### ISSUE THREAD

**Issue by slsritchie** [golang/go#55084] opened 2022-09-15 06:37 UTC
### What version of Go are you using (`go version`)?

<pre>
$ /home/ubuntu/go/bin/go version
go version go1.19.1 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ubuntu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/ubuntu/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/ubuntu/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2573396773=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

`/home/ubuntu/go/bin/go install -v -mod=readonly golang.org/x/tools/gopls@latest`

(This is the command vim-go uses when doing `:GoInstallBinaries`)

### What did you expect to see?

Successful exit.

### What did you see instead?

```
golang.org/x/exp/constraints
# golang.org/x/exp/constraints
go/pkg/mod/golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e/constraints/constraints.go:13:2: embedding interface element ~int|~int8|~int16|~int32|~int64 requires go1.18 or later (-lang was set to go1.16; check go.mod)
go/pkg/mod/golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e/constraints/constraints.go:20:2: embedding interface element ~uint|~uint8|~uint16|~uint32|~uint64|~uintptr requires go1.18 or later (-lang was set to go1.16; check go.mod)
go/pkg/mod/golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e/constraints/constraints.go:27:2: embedding interface element Signed|Unsigned requires go1.18 or later (-lang was set to go1.16; check go.mod)
go/pkg/mod/golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e/constraints/constraints.go:34:2: embedding interface element ~float32|~float64 requires go1.18 or later (-lang was set to go1.16; check go.mod)
go/pkg/mod/golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e/constraints/constraints.go:41:2: embedding interface element ~complex64|~complex128 requires go1.18 or later (-lang was set to go1.16; check go.mod)
go/pkg/mod/golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e/constraints/constraints.go:49:2: embedding interface element Integer|Float|~string requires go1.18 or later (-lang was set to go1.16; check go.mod)
golang.org/x/vuln/client
# golang.org/x/vuln/client
go/pkg/mod/golang.org/x/vuln@v0.0.0-20220901221904-62b0186a1058/client/client.go:124:22: function instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
go/pkg/mod/golang.org/x/vuln@v0.0.0-20220901221904-62b0186a1058/client/client.go:141:22: function instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
go/pkg/mod/golang.org/x/vuln@v0.0.0-20220901221904-62b0186a1058/client/client.go:144:20: type parameter requires go1.18 or later (-lang was set to go1.16; check go.mod)
go/pkg/mod/golang.org/x/vuln@v0.0.0-20220901221904-62b0186a1058/client/client.go:144:22: predeclared any requires go1.18 or later (-lang was set to go1.16; check go.mod)
go/pkg/mod/golang.org/x/vuln@v0.0.0-20220901221904-62b0186a1058/client/client.go:257:30: function instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
go/pkg/mod/golang.org/x/vuln@v0.0.0-20220901221904-62b0186a1058/client/client.go:304:21: function instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
go/pkg/mod/golang.org/x/vuln@v0.0.0-20220901221904-62b0186a1058/client/client.go:310:21: function instantiation requires go1.18 or later (-lang was set to go1.16; check go.mod)
go/pkg/mod/golang.org/x/vuln@v0.0.0-20220901221904-62b0186a1058/client/client.go:313:19: type parameter requires go1.18 or later (-lang was set to go1.16; check go.mod)
go/pkg/mod/golang.org/x/vuln@v0.0.0-20220901221904-62b0186a1058/client/client.go:313:21: predeclared any requires go1.18 or later (-lang was set to go1.16; check go.mod)
```

**Comment by seankhliao** [comment] 2022-09-15 07:07
Duplicate of #54908

**Closed by seankhliao** 2022-09-15 07:07 UTC
Labels: gopls
