### ISSUE TITLE
net: Dial("tcp", ":port") fails on Windows

### ISSUE THREAD

**Issue by taylorchu** [golang/go#15216] opened 2016-04-09 23:06 UTC
According to the package [doc](https://golang.org/pkg/net/#Dial), address without host specified should be allowed, e.g. `Dial("tcp", ":80")`. But an error `connectex: The requested address is not valid in its context` is returned on windows 10.

Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?

```
$ go version
go version go1.6 windows/amd64
```

2. What operating system and processor architecture are you using (`go env`)?

```
$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:/Users/taylorchu/go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

3. What did you do?

 http://play.golang.org/p/G8gttmZyvA

4. What did you expect to see?

net.Dial without specifying host should cause no error.

5. What did you see instead?

`connectex: The requested address is not valid in its context.`

**Comment by bradfitz** [comment] 2016-04-09 23:28
Wow, interesting. I didn't know that even worked on Linux!

```
$ cat dial.go 
package main

import (
        "log"
        "net"
)

func main() {
        c, err := net.Dial("tcp", ":8080")
        log.Printf("c, err = %#T, %v", c, err)
}

$ go run dial.go 
2016/04/09 23:27:30 c, err = *net.TCPConn, <nil>
```

So does it mean localhost? Should we keep this working and add tests so we don't regress and it works on Windows? I guess so.

/cc @mikioh @alexbrainman @ianlancetaylor

**Comment by mikioh** [comment] 2016-04-10 00:41
This is a duplicate of #6290. Still not sure whether a wildcard address, "0.0.0.0", "::" or "", means the entire IP addressing space or any available address on the routing instance.

**Closed by mikioh** 2016-04-10 00:41 UTC
Labels: OS-Windows

**Comment by alexbrainman** [comment] 2016-04-10 23:23
What @mikioh said.

Alex

**Comment by muly** [comment] 2017-03-13 23:05
#6290 is marked as closed, but I still see the issue.

**working**
`redis.Dial("tcp", "localhost:6379")`

**NOT working**
`redis.Dial("tcp", ":6379")`
