### ISSUE TITLE
x/text/cmd/gotext: extract extreme slow

### ISSUE THREAD

**Issue by okhowang** [golang/go#66742] opened 2024-04-09 10:48 UTC
### Go version

go version go1.22.1 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=Z:\go-build
set GOENV=C:\Users\okhowang\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=Z:\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=Z:\go
set GOPRIVATE=
set GOPROXY=direct
set GOROOT=C:/Program Files/Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=D:\workspace\golang\text\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\okhowang\AppData\Local\Temp\go-build15672011=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

git clone https://github.com/ory/fosite.git
cd fosite
gotext update -out catalog.go .

### What did you see happen?

gotext update run slowly.

### What did you expect to see?

gotext done in a reasonable duration

**Comment by okhowang** [comment] 2024-04-09 11:15
I try replace loader api to packages api
https://github.com/okhowang/text/commit/639ea0f89acf4d1f2d8439a084ea10bac1a467de
and it seems like faster.

**Comment by seankhliao** [comment] 2024-04-09 16:41
What counts as slow? For me it took 9s:
```sh
$ time gotext update -out catalog.go .
gotext update -out catalog.go .  69.23s user 22.39s system 1035% cpu 8.851 total
```

**Comment by seankhliao** [comment] 2024-04-09 16:43
Duplicate of #49039

**Closed by seankhliao** 2024-04-09 16:43 UTC

**Comment by okhowang** [comment] 2024-04-10 02:39
@seankhliao is gotext accept contribution currently?
