### ISSUE TITLE
x/tools/go/packages: tests spam stderr

### ISSUE THREAD

**Issue by bradfitz** [golang/go#30994] opened 2019-03-21 23:15 UTC
The x/tools/go/packages test spam stderr:

```
bradfitz@go:~/src/golang.org/x/tools/go/packages$ go test -short
{"ImportPath": "","Incomplete": true,"Error": {"Pos": "","Err": "named files must be .go files"}}
PASS
ok      golang.org/x/tools/go/packages  8.202s
```

**Comment by matloob** [comment] 2019-03-22 18:51
Was this fixed in a recent change? I can't reproduce at head...

```
matloob-macbookpro2:tools matloob$ go test -short golang.org/x/tools/go/packages
ok  	golang.org/x/tools/go/packages	15.964s
```

**Comment by bradfitz** [comment] 2019-03-22 19:32
It still repros for me on Linux at tip:

```
bradfitz@go:~/src/golang.org/x/tools/go/packages$ go version
go version devel +d923309a17 Fri Mar 22 17:26:03 2019 +0000 linux/amd64

bradfitz@go:~/src/golang.org/x/tools/go/packages$ go test -short
{"ImportPath": "","Incomplete": true,"Error": {"Pos": "","Err": "named files must be .go files"}}
ok      golang.org/x/tools/go/packages  9.284s

bradfitz@go:~/src/golang.org/x/tools/go/packages$ git rev-parse HEAD
e779aa49e359eb9a328069406fafdb0d559c205d
```

**Closed** 2019-03-22 20:37 UTC
Labels: NeedsFix, Testing, help wanted
