### ISSUE TITLE
x/tools/internal/lsp: How to specify the scope of a gopls search?

### ISSUE THREAD

**Issue by coventry** [golang/go#33588] opened 2019-08-11 23:56 UTC
### What did you do?

I'd like to [use the emacs `lsp-mode` client to find references to a symbol,](https://github.com/emacs-lsp/lsp-mode/issues/967) but its `lsp-find-references` only returns references to the symbol in the current golang package. 

### What did you expect to see?

I'm hoping there's a way to specify a broader scope for the search, so that all references to a symbol in a larger project can be identified, not just the ones which happen to be in the same package as the file I'm currently visiting.

### What did you see instead?

Here is the message `lsp-mode` is sending to `gopls`, on an `lsp-find-references` request:

```json
{
  "jsonrpc": "2.0",
  "method": "textDocument/references",
  "params": {
    "textDocument": {
      "uri": "file:///path/to/file.go"},
    "position": {
      "line": 23,
      "character": 45
    },
    "context": {
      "includeDeclaration": false
    }
  },
  "id": 2777
}
```

`lsp-mode` only seems to be getting back references to the symbol at `file.go:23:45` in the same package as `file.go`'s. Is there a way to expand the search scope?

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

It does with `go get golang.org/x/tools/gopls@latest`, at least.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go  env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ubuntu/go/src/github.com/smartcontractkit/chainlink/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build901014584=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by stamblerre** [comment] 2019-08-12 15:38
Duplicate of https://github.com/golang/go/issues/32869

**Closed by stamblerre** 2019-08-12 15:38 UTC
Labels: gopls

**Comment by coventry** [comment] 2019-08-12 17:54
Thanks for the pointer.
