### ISSUE TITLE
affected/package: go 1.18 mem bug? pooled small map incorrect.

### ISSUE THREAD

**Issue by timandy** [golang/go#52346] opened 2022-04-14 03:58 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 windows/amd64
go version go1.18.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\clxu6\AppData\Local\go-build
set GOENV=C:\Users\clxu6\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=E:\.go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\.go
set GOPRIVATE=
set CGO_ENABLED=1
set GOMOD=E:\gomem\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\clxu6\AppData\Local\Temp\go-build2572864232=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

``` go
package main

import (
	"github.com/stretchr/testify/assert"
	"runtime/debug"
	"sync"
	"testing"
	"unsafe"
)

type ExtendedMap struct {
	labels map[string]string
	flag   int
}

func TestForMap(t *testing.T) {
	const concurrency = 5000
	const loopTimes = 1000
	wg := &sync.WaitGroup{}
	wg.Add(concurrency)
	for i := 0; i < concurrency; i++ {
		go func() {
			var ptr unsafe.Pointer
			for j := 0; j < loopTimes; j++ {
				m := make(map[string]string)
				m["key"] = "value"
				ptr = unsafe.Pointer(&m)

				assert.NotNil(t, ptr)
				_, flag := getEMap(ptr)
				assert.NotEqual(t, 12345678, flag)

				labels := make(map[string]string)
				labels["key"] = "value"
				em := ExtendedMap{labels: labels, flag: 12345678}
				ptr = unsafe.Pointer(&em)
			}
			wg.Done()
		}()
	}
	wg.Wait()
}

func getEMap(ptr unsafe.Pointer) (em *ExtendedMap, flag int) {
	panicOnFault := debug.SetPanicOnFault(true)
	defer func() {
		debug.SetPanicOnFault(panicOnFault)
		recover()
	}()
	em = (*ExtendedMap)(ptr)
	return em, em.flag
}


```

### What did you expect to see?
go 1.18 amd64 test passed

### What did you see instead?

go 1.13-go 1.17 386       test passed
go 1.13-go 1.17 amd64 test passed

go 1.18 386                   test passed

go 1.18 amd64              **test failed**

**Comment by timandy** [comment] 2022-04-14 04:06
`pprof.Do()` make a `new` map and set to g.labels . should not with a flag value `12345678`.

**Comment by randall77** [comment] 2022-04-14 05:04
I don't understand what your code is trying to do. You're not using unsafe according to the [rules governing correct use of unsafe](https://pkg.go.dev/unsafe#Pointer).

```
m := make(map[string]string)
ptr := unsafe.Pointer(&m)
em := (*ExtendedMap)(ptr)
```
The `flag` field of `*em` is junk, because `ExtendedMap` is two words in size, where `m` is only one word in size.
You're probably reading an arbitrary unrelated field of the stack frame.

**Comment by timandy** [comment] 2022-04-14 05:43
@randall77  I just want to make sure the memory is newly created to protect memory privacy.

**Comment by randall77** [comment] 2022-04-14 05:58
> By the way is there a way to check the real type of unsafe.Pointer

Get rid of your `//go:norace` and `//go:nocheckptr` annotations. I think doing that, and running with `-race`, would have found this bug for you.

**Comment by timandy** [comment] 2022-04-14 12:36
> Get rid of your `//go:norace` and `//go:nocheckptr` annotations. I think doing that, and running with `-race`, would have found this bug for you.

@randall77  I removed `//go:norace` and `//go:nocheckptr` annotations only `go1.18-amd64` failed.
I would like to know if the pool technology of map was introduced in go1.18 and how to prohibit this behavior.

**Comment by randall77** [comment] 2022-04-14 15:25
> I would like to know if the pool technology of map was introduced in go1.18 and how to prohibit this behavior.

I don't know what you're talking about.

In any case, I'm going to close this as it is not a bug. Please see https://github.com/golang/go/wiki/Questions for places to ask questions.

**Closed by randall77** 2022-04-14 15:25 UTC
Labels: WaitingForInfo
