### ISSUE TITLE
x/tools/gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by yavuzyurtbegendi** [golang/go#66174] opened 2024-03-07 10:06 UTC
Hi, I have this crash happening,

panic: nil metadata for "github.com/mailru/easyjson/easyjson [command-line-arguments.test]"

goroutine 17198 [running]:
golang.org/x/tools/gopls/internal/cache.(*Snapshot).getPackageHandles.func1(0x1400f59ba40, {0x1400d165900, 0x41})
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/check.go:872 +0x53c
golang.org/x/tools/gopls/internal/cache.(*Snapshot).getPackageHandles.func1(0x0, {0x14008832000, 0x7a})
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/check.go:889 +0x468
golang.org/x/tools/gopls/internal/cache.(*Snapshot).getPackageHandles(0x1400c2d77a0, {0x102f7b168, 0x140140b05d0}, {0x14010965610, 0x1, 0x0?})
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/check.go:899 +0x17c
golang.org/x/tools/gopls/internal/cache.(*Snapshot).forEachPackage(0x102f7b1a0?, {0x102f7b168, 0x140140b0420}, {0x14010965610, 0x1, 0x1}, 0x1028162e0?, 0x1400c2d77e8?)
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/check.go:343 +0x134
golang.org/x/tools/gopls/internal/cache.(*Snapshot).PackageDiagnostics(0x14008832000?, {0x102f7b1a0?, 0x1400b59d400?}, {0x14010965610, 0x1, 0x1})
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/snapshot.go:686 +0x1b0
golang.org/x/tools/gopls/internal/cache.(*Snapshot).orphanedFileDiagnostics(0x1400c2d77a0, {0x102f7b1a0, 0x1400b59d400}, {0x1401dc9bf40, 0x4, 0x10288c630?})
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/snapshot.go:1452 +0x1c8
golang.org/x/tools/gopls/internal/cache.(*Session).OrphanedFileDiagnostics(0x1400043e150, {0x102f7b1a0, 0x1400b59d400})
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/session.go:1165 +0x464
golang.org/x/tools/gopls/internal/server.(*server).diagnoseChangedViews(0x14000374000, {0x102f7b1a0, 0x1400b59d400}, 0x4, 0x140001b4d98?, 0x0)
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/server/diagnostics.go:157 +0x504
golang.org/x/tools/gopls/internal/server.(*server).didModifyFiles.func2()
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/server/text_synchronization.go:269 +0x3c
created by golang.org/x/tools/gopls/internal/server.(*server).didModifyFiles in goroutine 115
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/server/text_synchronization.go:268 +0x4c0
[Error - 11:09:17]

**Comment by findleyr** [comment] 2024-03-08 20:06
Closing as a dupe of #66109. Please reopen if the prerelease does not fix this for you:

```
go install golang.org/x/tools/gopls@v0.15.2-pre.1
```

**Closed by findleyr** 2024-03-08 20:06 UTC
Labels: gopls, Tools
