### ISSUE TITLE
x/dl/version: not setting goroot

### ISSUE THREAD

**Issue by AlexRouSg** [golang/go#30126] opened 2019-02-07 21:38 UTC
### What version of Go are you using (`go version`)?

1.12beta2 but irreverent 

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details>

> set GOARCH=amd64
> set GOBIN=
> set GOCACHE=C:\Users\alexr\AppData\Local\go-build
> set GOEXE=.exe
> set GOFLAGS=
> set GOHOSTARCH=amd64
> set GOHOSTOS=windows
> set GOOS=windows
> set GOPATH=%USERPROFILE%\go
> set GOPROXY=
> set GORACE=
> set GOROOT=C:\Go-tip
> set GOTMPDIR=
> set GOTOOLDIR=C:\Go-tip\pkg\tool\windows_amd64
> set GCCGO=gccgo
> set CC=gcc
> set CXX=g++
> set CGO_ENABLED=1
> set GOMOD=
> set CGO_CFLAGS=-g -O2
> set CGO_CPPFLAGS=
> set CGO_CXXFLAGS=-g -O2
> set CGO_FFLAGS=-g -O2
> set CGO_LDFLAGS=-g -O2
> set PKG_CONFIG=pkg-config
> set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=%USERPROFILE%\AppData\Local\Temp\go-build619042602=/tmp/go-build -gno-record-gcc-switches

</details>

### What did you do?

In an effort to reproduce the issue reported in #30117 
I ran `go get golang.org/dl/gotip` followed by `gotip run .` on the code described in 
https://github.com/golang/go/issues/30117#issuecomment-461323858

### What did you expect to see?

No output

### What did you see instead?

`.\test.go:16:86: syntax error: unexpected semicolon, expecting expression`

Setting GOROOT to the proper path gives the expected result.

**Comment by bcmills** [comment] 2019-02-07 23:30
You may need to run ` go get -u golang.org/dl/gotip && gotip download` to make sure you're on the version of the wrapper that sets it.

**Comment by AlexRouSg** [comment] 2019-02-07 23:38
right... forgot to mention I did `gotip download`

**Comment by bcmills** [comment] 2019-02-08 00:06
Did you run `go get -u`, with the `-u` flag?

**Comment by AlexRouSg** [comment] 2019-02-08 00:16
Never downloaded `gotip` on this machine before so didn't think it mattered. But just to be sure I did ran it with `-u` and no change.

`gotip env` does show GOROOT to be `C:\Go` instead of `%USERPROFILE%\sdk\gotip`

**Comment by mvdan** [comment] 2019-02-08 10:21
Are you setting `GOROOT` directly anywhere on your system?

**Comment by AlexRouSg** [comment] 2019-02-08 10:41
Nope, only set GOPATH nothing more.

**Comment by AlexRouSg** [comment] 2019-02-08 10:44
OHHH the windows installer set GOROOT under system variables and I didn't checked there.

Still one would assume `gotip` to set GOROOT no?

**Comment by mvdan** [comment] 2019-02-08 10:48
In general, Go installations nowadays should not set up GOROOT. It is inferred from the location of the `go` binary you are running.

If you do specify a GOROOT via an env var, it's always used directly. So if your system sets GOROOT, you'll also have to set it up when calling `gotip` or any other binary Go installation.

`gotip` doesn't set GOROOT because it isn't necessary. And presumably, also because users can set their own GOROOT, overriding the default.

So in this case, I'd say this is not a bug; you should either not have GOROOT set up, or you should set it up when calling `gotip`. But I'll leave the issue open for now, in case it's decided that there's something to fix in programs like `gotip`.

**Comment by AlexRouSg** [comment] 2019-02-08 11:02
If it's decided that there's nothing to do here I'm fine with that.

Should I file a new report for the official windows installer setting GOROOT?

**Comment by mvdan** [comment] 2019-02-08 11:07
> Should I file a new report for the official windows installer setting GOROOT?

I'd do that; see https://golang.org/doc/go1.10#goroot. Setting it is usually harmless, but can be confusing when one uses multiple Go versions, like you're trying to do.

**Comment by mvdan** [comment] 2019-02-08 11:38
I've also sent https://go-review.googlesource.com/c/go/+/161758, as I still found pieces of the official documentation which recommeded setting up GOROOT.

**Comment by agnivade** [comment] 2019-02-09 13:34
Looks like this is tracked in the new issue. Closing.

**Closed by agnivade** 2019-02-09 13:34 UTC

**Comment by AlexRouSg** [comment] 2019-02-09 13:38
@agnivade not exactly, they are related yes but quite different.

This issue is about whether x/dl/version should ignore a set GOROOT as the point of x/dl/version is to use a specific Go version.

**Comment by agnivade** [comment] 2019-02-09 18:13
x/dl/version just installs a go distribution. And the Go distribution will always use a GOROOT env var if it is specifically set. I don't think there is any bug here with x/dl/version.
