### ISSUE TITLE
Go and antivirus software don't play nice together

### ISSUE THREAD

**Issue by dianedownie** [golang/go#20301] opened 2017-05-09 20:25 UTC
go version go1.8.1 darwin/amd64 installed with homebrew
Mac OS 10.12.4 x64
CylancePROTECT 2.0.1430.518

During the OSCON Tutorial session on Go CLI, pulling a sample project from github failed with a bdsthread_register error.  Problem was reproducible with clean GOPATH directory.
```
go get -v github.com/spf13/cobra/cobra
# github.com/mitchellh/go-homedir
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x16c3021, 0x21)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/panic.go:596 +0x95 fp=0x7fff5fbff310 sp=0x7fff5fbff2f0
runtime.goenvs()
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/os_darwin.go:108 +0xa0 fp=0x7fff5fbff340 sp=0x7fff5fbff310
runtime.schedinit()
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:486 +0xa1 fp=0x7fff5fbff380 sp=0x7fff5fbff340
runtime.rt0_go(0x7fff5fbff3b8, 0x10, 0x7fff5fbff3b8, 0x0, 0x0, 0x10, 0x7fff5fbff640, 0x7fff5fbff681, 0x7fff5fbff684, 0x7fff5fbff6e9, ...)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:158 +0x183 fp=0x7fff5fbff388 sp=0x7fff5fbff380
....
```
Note
My coworker who installed Go with MacPorts did not reproduce this problem, but has seen it on another MacOS system.

Workaround.
Uninstalling the CylancePROTECT and re-run the command.

**Comment by dianedownie** [comment] 2017-05-09 20:29
Entered at the request of Steve Francia.

**Comment by josharian** [comment] 2017-05-09 20:44
Closing as duplicate of #18171. Please comment if this is incorrect. cc @spf13

**Closed by josharian** 2017-05-09 20:44 UTC
