### ISSUE TITLE
sync/atomic: TestNilDeref flaky failure on windows-386 with runtime fatal error

### ISSUE THREAD

**Issue by cherrymui** [golang/go#70288] opened 2024-11-11 20:11 UTC
```
#!watchflakes
default <- builder ~ `windows-386` && pkg == "sync/atomic" && test == "TestNilDeref"
```

sync/atomic.TestNilDeref has been flaky on windows-386 with runtime fatal error "traceback did not unwind completely" 
```
=== RUN   TestNilDeref
runtime: g388: frame.sp=0x1922f8c top=0x1922ff0
	stack=[0x1922000-0x1923000
fatal error: traceback did not unwind completely

runtime stack:
runtime.throw({0xb0b5fb, 0x23})
	C:/b/s/w/ir/x/w/goroot/src/runtime/panic.go:1084 +0x35 fp=0x21aff5d4 sp=0x21aff5c0 pc=0x9fd5f5
runtime.(*unwinder).finishInternal(0x21aff65c)
	C:/b/s/w/ir/x/w/goroot/src/runtime/traceback.go:566 +0x16d fp=0x21aff5f4 sp=0x21aff5d4 pc=0x9ec57d
...
runtime.gopark(0xb109e4, 0x18122d0, 0x1a, 0xa, 0x0)
	C:/b/s/w/ir/x/w/goroot/src/runtime/proc.go:435 +0xfd fp=0x1896f8c sp=0x1896f78 pc=0x9fd72d
runtime.gcBgMarkWorker(0x188e1c0)
	C:/b/s/w/ir/x/w/goroot/src/runtime/mgc.go:1363 +0xe2 fp=0x1896fe8 sp=0x1896f8c pc=0x9a6aa2
runtime.gcBgMarkStartWorkers.gowrap1()
	C:/b/s/w/ir/x/w/goroot/src/runtime/mgc.go:1279 +0x25 fp=0x1896ff0 sp=0x1896fe8 pc=0x9a69a5
runtime.goexit({})
	C:/b/s/w/ir/x/w/goroot/src/runtime/asm_386.s:1393 +0x1 fp=0x1896ff4 sp=0x1896ff0 pc=0xa02c61
created by runtime.gcBgMarkStartWorkers in goroutine 333
	C:/b/s/w/ir/x/w/goroot/src/runtime/mgc.go:1279 +0x11a
```

It started since today (Nov 11).

https://ci.chromium.org/ui/test/golang/sync%2Fatomic.TestNilDeref?q=V%3Abuilder%3Dgotip-windows-386-test_only+V%3Ago_branch%3Dmaster+V%3Agoarch%3D386+V%3Agoos%3Dwindows+V%3Ahost_goarch%3D386+V%3Ahost_goos%3Dwindows

All other platforms look fine. Only windows-386.

I've seen it on trybot more than once, e.g. https://ci.chromium.org/ui/p/golang/builders/try/gotip-windows-386/b8731553101305354337/test-results?sortby=&groupby=

**Comment by cherrymui** [comment] 2024-11-11 20:14
cc @golang/runtime

**Comment by cherrymui** [comment] 2024-11-12 19:38
cc @golang/windows

**Comment by mknyszek** [comment] 2024-11-12 19:44
The test binary seems to die abruptly. The package tests are marked as failed, but there are JSON lines missing from the full log (https://logs.chromium.org/logs/golang/buildbucket/cr-buildbucket/8731450114802979457/+/u/step/11/log/3). That's also why the test is marked as "aborted": the JSON test parser loses track of what exactly happened.

This also appears to have started yesterday based on the test history: https://ci.chromium.org/ui/test/golang/sync%2Fatomic.TestNilDeref?q=V%3Abuilder%3Dgotip-windows-386-test_only+V%3Ago_branch%3Dmaster+V%3Agoarch%3D386+V%3Agoos%3Dwindows+V%3Ahost_goarch%3D386+V%3Ahost_goos%3Dwindows. Though, there's no obvious culprit.

On Linux, we've seen immediate deaths like this end up being a bad dereference during a signal handler. Does something similar happen for crashes in the exception handler? (At least we have a stack trace here.)

CC @qmuntal who might have additional insights.

**Comment by rsc** [comment] 2024-11-12 21:22
I've reproduced this as early as Go 1.20, with -count=10000. It is a stack unwinding / stack corruption problem.

Here is one error I saw at a later commit:

```
runtime: g1: frame.sp=0x94a6fa4 top=0x94a6ff0
    stack=[0x94a6000-0x94a7000
fatal error: traceback did not unwind completely

...

goroutine 1 [chan receive (scan)]:
runtime.gopark(0x3b8d20, 0x9414570, 0xe, 0x17, 0x2)
    /Users/rsc/go/src/runtime/proc.go:398 +0xfd fp=0x94a6c70 sp=0x94a6c5c pc=0x29e29d
runtime.chanrecv(0x9414540, 0x944fce3, 0x1)
    /Users/rsc/go/src/runtime/chan.go:583 +0x3ad fp=0x94a6cac sp=0x94a6c70 pc=0x265f0d
runtime.chanrecv1(0x9414540, 0x944fce3)
    /Users/rsc/go/src/runtime/chan.go:442 +0x1c fp=0x94a6cc0 sp=0x94a6cac pc=0x265b5c
testing.(*T).Run(0x94e21e0, {0x3abfbd, 0xc}, 0x3b89e0)
    /Users/rsc/go/src/testing/testing.go:1649 +0x3fa fp=0x94a6d24 sp=0x94a6cc0 pc=0x32f8ca
testing.runTests.func1(0x94e21e0)
    /Users/rsc/go/src/testing/testing.go:2054 +0x49 fp=0x94a6d48 sp=0x94a6d24 pc=0x3318e9
testing.tRunner(0x94e21e0, 0x944fdf0)
    /Users/rsc/go/src/testing/testing.go:1595 +0x11e fp=0x94a6d94 sp=0x94a6d48 pc=0x32ea7e
testing.runTests(0x94980c0, {0x4a6e20, 0x4c, 0x4c}, {0xc1c50eb92c798d2c, 0x8bb2fda08d, 0x4a8400})
    /Users/rsc/go/src/testing/testing.go:2052 +0x3a1 fp=0x94a6e04 sp=0x94a6d94 pc=0x331801
testing.(*M).Run(0xf8659c22)
    /Users/rsc/go/src/testing/testing.go:1925 +0x6b6 fp=0x94a6f68 sp=0x94a6e04 pc=0x3301e6
main.main()
    _testmain.go:201 +0x16f fp=0x94a6fa4 sp=0x94a6f68 pc=0x37cedf
sync/atomic_test.TestNilDeref.func59(0x29b680)
    /Users/rsc/go/src/sync/atomic/atomic_test.go:2526 +0x48 fp=0x94a6fb0 sp=0x94a6fa4 pc=0x378b18

...
goroutine 211 [wait for GC cycle]:
runtime.gopark(0x3b8ea4, 0x4a8764, 0x19, 0x14, 0x1)
    /Users/rsc/go/src/runtime/proc.go:398 +0xfd fp=0x94a7cb4 sp=0x94a7ca0 pc=0x29e29d
runtime.goparkunlock(...)
    /Users/rsc/go/src/runtime/proc.go:404
runtime.gcWaitOnMark(0x1dd2)
    /Users/rsc/go/src/runtime/mgc.go:529 +0x5c fp=0x94a7cc8 sp=0x94a7cb4 pc=0x2783ac
runtime.GC()
    /Users/rsc/go/src/runtime/mgc.go:472 +0x6d fp=0x94a7ce8 sp=0x94a7cc8 pc=0x27822d
sync/atomic_test.TestNilDeref.func59.1()
    /Users/rsc/go/src/sync/atomic/atomic_test.go:2522 +0x18 fp=0x94a7cf8 sp=0x94a7ce8 pc=0x37bc38
runtime.deferCallSave(0x94a7d5c, 0x3b8bec)
    /Users/rsc/go/src/runtime/panic.go:798 +0x76 fp=0x94a7d00 sp=0x94a7cf8 pc=0x29ad56
runtime.runOpenDeferFrame(0x9450090)
    /Users/rsc/go/src/runtime/panic.go:771 +0x1b0 fp=0x94a7d28 sp=0x94a7d00 pc=0x29abb0
panic({0x393320, 0x4a2028})
    /Users/rsc/go/src/runtime/panic.go:914 +0x1df fp=0x94a7d7c sp=0x94a7d28 pc=0x29af9f
runtime.panicmem(...)
    /Users/rsc/go/src/runtime/panic.go:261
runtime.sigpanic()
    /Users/rsc/go/src/runtime/signal_windows.go:364 +0x1f3 fp=0x94a7da0 sp=0x94a7d7c pc=0x2b06a3
sync/atomic.(*Int32).Load(...)
    /Users/rsc/go/src/sync/atomic/type.go:74
sync/atomic_test.TestNilDeref.func36()
    /Users/rsc/go/src/sync/atomic/atomic_test.go:2495 +0x15 fp=0x94a7dac sp=0x94a7da0 pc=0x37b725
sync/atomic_test.TestNilDeref.func59(0x94a7dc0)
    /Users/rsc/go/src/sync/atomic/atomic_test.go:2525 +0x3a fp=0x94a7db8 sp=0x94a7dac pc=0x378b0a
sync/atomic_test.TestNilDeref(0x94e22d0)
    /Users/rsc/go/src/sync/atomic/atomic_test.go:2526 +0x2f6 fp=0x94a7f98 sp=0x94a7db8 pc=0x378aa6
testing.tRunner(0x94e22d0, 0x3b89e0)
    /Users/rsc/go/src/testing/testing.go:1595 +0x11e fp=0x94a7fe4 sp=0x94a7f98 pc=0x32ea7e
testing.(*T).Run.func1()
    /Users/rsc/go/src/testing/testing.go:1648 +0x2c fp=0x94a7ff0 sp=0x94a7fe4 pc=0x32fa0c
runtime.goexit()
    /Users/rsc/go/src/runtime/asm_386.s:1363 +0x1 fp=0x94a7ff4 sp=0x94a7ff0 pc=0x2cd341
created by testing.(*T).Run in goroutine 1
    /Users/rsc/go/src/testing/testing.go:1648 +0x3db
FAIL    sync/atomic    15.498s
```

The panic is about not fully unwinding goroutine 1. You can see the traceback printer get it wrong too. main.main should be called from goexit, but it has been "called" from TestNilDeref.func59 instead. This suggests stack corruption near the top of goroutine 1's stack. The top of goroutine 1's stack is the bottom of goroutine 211's stack, which coincidentally (?) is the goroutine that did the nil dereference. func59 is also on that stack, but with a different caller pc (0x378b0a vs 0x378b18). 

At Go 1.20, I got this error:

```
%  GOOS=windows GOARCH=386 go test sync/atomic -run=NilDeref -timeout=1h -count=10000
runtime: g 38: unexpected return pc for runtime.gcBgMarkWorker called from 0x0
stack: frame={sp:0x9892f94, fp:0x9892ff0} stack=[0x9892000,0x9893000)
0x09892f14:  0x00000000  0x00000000  0x0000000f  0x00000010 
0x09892f24:  0x0098a37c <runtime.lock2+0x0000005c>  0xf8659c22  0x00007fff  0x3fd00000 
0x09892f34:  0x00bb5518  0x00000001  0x00000000  0x00000001 
0x09892f44:  0x099823c0  0x09880000  0x00000000  0x009a0da4 <runtime.(*gcControllerState).removeIdleMarkWorker+0x00000054> 
0x09892f54:  0x00bdb3d8  0x00000001  0x0000000c  0x00000000 
0x09892f64:  0x00000000  0x098840f0  0x00000000  0x009b8ca0 <runtime.recovery+0x00000000> 
0x09892f74:  0x00000000  0xf9130e7c  0x00007fff  0x00aca390 
0x09892f84:  0x00000002  0x09a00240  0x099823c0  0x0099845e <runtime.gcBgMarkWorker+0x000000ee> 
0x09892f94: <0x00aca2e8  0x09812318  0xffff141a  0x00a8d97a <sync/atomic_test.TestNilDeref.func59+0x0000004a> 
0x09892fa4:  0x00000000  0x09884b40  0x00000000  0x0010005f 
0x09892fb4:  0x00001fa0  0x002b0023  0x0053002b  0x002b002b 
0x09892fc4:  0x00010246  0x00000000  0x00000000  0x00000000 
0x09892fd4:  0x00000000  0x00000000  0x00000000  0x00000000 
0x09892fe4:  0x00000000  0x00000000 !0x00000000 >0x00000000 
0x09892ff4:  0x00000000  0x00000000  0x00000000 
fatal error: unknown caller pc
```

Again, instead of finding goexit near the top of the stack, we find corruption and a PC in sync/atomic_test.TestNilDeref.func59. 

I wonder whether the Windows fault handler is pushing a larger-than-expected fault descriptor onto the goroutine stack (should it be using the system stack), although func59 is a few frames above the actual fault, so I don't know why the fault descriptor would mention it. 

Definitely _looks_ like stack corruption somehow.

**Comment by rsc** [comment] 2024-11-12 22:00
Here is a failure at Go 1.19.

```
% GOOS=windows GOARCH=386 go test sync/atomic -run=NilDeref -timeout=1h -count=10000
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x1 addr=0x10 pc=0x76837a]

goroutine 38 [running]:
runtime.throw({0x8987fc, 0x2a})
	/Users/rsc/go/src/runtime/panic.go:1047 +0x4d fp=0x11904f70 sp=0x11904f5c pc=0x7898bd
runtime.sigpanic()
	/Users/rsc/go/src/runtime/signal_windows.go:249 +0x23f fp=0x11904f94 sp=0x11904f70 pc=0x79d45f
runtime: g 38: unexpected return pc for runtime.gcBgMarkWorker called from 0x0
stack: frame={sp:0x11904f94, fp:0x11904ff0} stack=[0x11904000,0x11905000)
0x11904f14:  0x00000000  0x00000000  0x00000000  0x00000000 
0x11904f24:  0x00000000  0x00000000  0x00000000  0x00000000 
0x11904f34:  0x11846d80  0x119023c0  0x007b5bb9 <runtime.systemstack+0x00000029>  0x00789bab <runtime.fatalthrow+0x0000006b> 
0x11904f44:  0x11904f48  0x00789bc0 <runtime.fatalthrow.func1+0x00000000>  0x119023c0  0x007898bd <runtime.throw+0x0000004d> 
0x11904f54:  0x11904f5c  0x007898bd <runtime.throw+0x0000004d>  0x00000002  0x007898d0 <runtime.throw.func1+0x00000000> 
0x11904f64:  0x008987fc  0x0000002a  0x0079d45f <runtime.sigpanic+0x0000023f>  0x008987fc 
0x11904f74:  0x0000002a  0x00000000  0x00000000  0x119023c0 
0x11904f84:  0x00000002  0x118466c0  0x119023c0  0x0076837a <runtime.gcBgMarkWorker+0x0000010a> 
0x11904f94: <0x0089b6b4  0x11812288  0xffff1418  0x00000000 
0x11904fa4:  0x00000000  0x00981b40  0x1a05a648  0x0010005f 
0x11904fb4:  0x00001fa0  0x002b0023  0x0053002b  0x002b002b 
0x11904fc4:  0x00010246  0x00000000  0x00000000  0x00000000 
0x11904fd4:  0x00000000  0x00000000  0x00000000  0x00000000 
0x11904fe4:  0x00000000  0x00000000 !0x00000000 >0x00000000 
0x11904ff4:  0x00000000  0x00000000  0x00000000 
runtime.(*muintptr).set(...)
	/Users/rsc/go/src/runtime/runtime2.go:305
runtime.gcBgMarkWorker()
	/Users/rsc/go/src/runtime/mgc.go:1270 +0x10a fp=0x11904ff0 sp=0x11904f94 pc=0x76837a
created by runtime.gcBgMarkStartWorkers
	/Users/rsc/go/src/runtime/mgc.go:1159 +0x25

...

goroutine 19 [wait for GC cycle]:
runtime.gopark(0x89b75c, 0x981d2c, 0x17, 0x14, 0x1)
	/Users/rsc/go/src/runtime/proc.go:363 +0xff fp=0x11861c84 sp=0x11861c70 pc=0x78c3df
runtime.goparkunlock(...)
	/Users/rsc/go/src/runtime/proc.go:369
runtime.gcWaitOnMark(0xb)
	/Users/rsc/go/src/runtime/mgc.go:505 +0x5f fp=0x11861c98 sp=0x11861c84 pc=0x765f4f
runtime.GC()
	/Users/rsc/go/src/runtime/mgc.go:448 +0x6e fp=0x11861cb8 sp=0x11861c98 pc=0x765dbe
sync/atomic_test.TestNilDeref.func59.1()
	/Users/rsc/go/src/sync/atomic/atomic_test.go:2601 +0x1a fp=0x11861cc8 sp=0x11861cb8 pc=0x85f4fa
runtime.deferCallSave(0x11861d38, 0x89b9c0)
	/Users/rsc/go/src/runtime/panic.go:796 +0x72 fp=0x11861cd0 sp=0x11861cc8 pc=0x789102
runtime.runOpenDeferFrame(0x118843c0, 0x118ba090)
	/Users/rsc/go/src/runtime/panic.go:769 +0x1a8 fp=0x11861cfc sp=0x11861cd0 pc=0x788f68
panic({0x878980, 0x97cc48})
	/Users/rsc/go/src/runtime/panic.go:884 +0x1ba fp=0x11861d58 sp=0x11861cfc pc=0x7892fa
runtime.panicmem(...)
	/Users/rsc/go/src/runtime/panic.go:260
runtime.sigpanic()
	/Users/rsc/go/src/runtime/signal_windows.go:255 +0x177 fp=0x11861d7c sp=0x11861d58 pc=0x79d397
runtime/internal/atomic.Cas(0x0, 0x0, 0x0)
	/Users/rsc/go/src/runtime/internal/atomic/atomic_386.s:19 +0xc fp=0x11861d80 sp=0x11861d7c pc=0x7522dc
sync/atomic.CompareAndSwapPointer(0x0, 0x0, 0x0)
	/Users/rsc/go/src/runtime/atomic_pointer.go:76 +0x4a fp=0x11861d9c sp=0x11861d80 pc=0x7b29ca
sync/atomic_test.TestNilDeref.func11()
	/Users/rsc/go/src/sync/atomic/atomic_test.go:2549 +0x31 fp=0x11861db0 sp=0x11861d9c pc=0x85e9b1
sync/atomic_test.TestNilDeref.func59(0x11905dc4)
	/Users/rsc/go/src/sync/atomic/atomic_test.go:2604 +0x3c fp=0x11861dbc sp=0x11861db0 pc=0x85f87c
sync/atomic_test.TestNilDeref(0x118842d0)
	/Users/rsc/go/src/sync/atomic/atomic_test.go:2605 +0x2f8 fp=0x11861f9c sp=0x11861dbc pc=0x85f818
testing.tRunner(0x118842d0, 0x89b9d8)
	/Users/rsc/go/src/testing/testing.go:1446 +0x113 fp=0x11861fe4 sp=0x11861f9c pc=0x814073
testing.(*T).Run.func1()
	/Users/rsc/go/src/testing/testing.go:1493 +0x2e fp=0x11861ff0 sp=0x11861fe4 pc=0x814e6e
runtime.goexit()
	/Users/rsc/go/src/runtime/asm_386.s:1326 +0x1 fp=0x11861ff4 sp=0x11861ff0 pc=0x7b7051
created by testing.(*T).Run
	/Users/rsc/go/src/testing/testing.go:1493 +0x374
```

In this case the test goroutine stack (0x11861c70-0x11861ff0) is not directly above the corrupt stack (0x11904000-0x11905000). However, note that the "argument" to func59 is 0x11905dc4. That appears to be an on-stack closure pointer argument, looking at the generated code for both func59 and TestNilDeref, but the right value for the stack we are on would be 0x11861dc4. That implies the test goroutine stack _used to be_ directly above the corrupt stack but was moved. It looks like the closure pointer argument was not adjusted when the stack moved, because it is dead. But that's very important to know: the stack moved.

I don't see why it would have moved. As I read runtime/stack.go \_FixedStack (the initial stack size) is 4096 bytes, and none of the stack we can see look like they are using anywhere near that. However:

	// StackSystem is a number of additional bytes to add
	// to each stack below the usual guard area for OS-specific
	// purposes like signal handling. Used on Windows, Plan 9,
	// and iOS because they do not use a separate stack.
	_StackSystem = goos.IsWindows*512*goarch.PtrSize + goos.IsPlan9*512 + goos.IsIos*goarch.IsArm64*1024

Perhaps 2kB is not enough signal handling space on windows-386. I think our windows-386 builders are actually 64-bit Windows now. Maybe that matters?

I tried adding some debug prints about the stack during the exceptions. The low bits of the stack pointer we see Go's exception handler running on are around 0x128. It should not go lower after that in Go, and that's still almost 300 bytes of room. That said, this is being called from some DLL, so maybe it went lower _before_ that in the DLL, or even _after_ that as we return back out. It seems too close for comfort either way.

I tried doubling the reserved system stack on 386, simplifying the expression to IsWindows\*4096. I'm waiting on proper statistics but preliminary runs make it look like the problem goes away with the larger system stack.

**Comment by rsc** [comment] 2024-11-12 23:01
At current master the test fails 100/100 times running -count=10.
After I double stackSystem, the test passes 100/100 times with -count=1000.

That is, before, it consistently (100/100) fails at running 10 iterations.
Now it consistently (100/100) succeeds at running 1000 iterations.
I feel confident that it's fixed.

CL 627375 has the stack doubling.

**Comment by dmitshur** [comment] 2024-11-27 20:17
The fix is backported and this shouldn't happen on release branches either, now. Closing again.

**Closed by dmitshur** 2024-11-27 20:17 UTC
Labels: OS-Windows, NeedsFix, arch-386, compiler/runtime, FixPending
