### ISSUE TITLE
proposal: crypto: add key wrap support for AES key wrap for rfc 3394 and  rfc 5649

### ISSUE THREAD

**Issue by rajnikant12345** [golang/go#30128] opened 2019-02-08 08:20 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

NO

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rajni/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rajni/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build598233196=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Symmetric and  Asymmetric keys are need to be exported from a Key Management Solution,  3394 and  rfc 5649 explains a standard for this. 
rfc 3394 is for wrapping block length keys and rfc 5649 is an extension for wrapping secret of any length.
I am proposing to add this support in Golang and add key wrap support for AES key wrap for rfc 3394 and  rfc 5649.

### What did you expect to see?
Support in Go for  rfc 3394 and  rfc 5649.

### What did you see instead?
No support in Go for  rfc 3394 and  rfc 5649.

**Comment by FiloSottile** [comment] 2019-02-08 17:29
Duplicate of #27599

**Closed by FiloSottile** 2019-02-08 17:29 UTC
Labels: Proposal, Proposal-Crypto
