### ISSUE TITLE
x/pkgsite: standard lib symbol available version does not have same behavior across packages

### ISSUE THREAD

**Issue by h9jiang** [golang/go#68265] opened 2024-07-01 19:26 UTC
### What is the URL of the page with the issue?

https://pkg.go.dev/context#Context

### What is your user agent?

N/A

### Screenshot

Standard Library Type:
- From package `crypto` https://pkg.go.dev/crypto#Decrypter
- From package `context` https://pkg.go.dev/context#Context

![image](https://github.com/golang/go/assets/58842577/2843abff-33d5-419a-b0d4-7f3862c3708e)
![image](https://github.com/golang/go/assets/58842577/7e2e354d-a9e1-48ee-94d1-2a216ee5bf70)

Method Library Type: 
- From package `crypto/rsa` https://pkg.go.dev/crypto/rsa#PrivateKey.Decrypt
- From pacakge `go/types` https://pkg.go.dev/go/types#Alias.Obj

![image](https://github.com/golang/go/assets/58842577/2b99f2a1-2fcb-4ae3-bfb4-fb613b5ef76c)
![image](https://github.com/golang/go/assets/58842577/c1317717-9d8c-44f4-8eb4-ef69e631f084)

### What did you do?

N/A

### What did you see happen?

The content `added in go1.5` in the website is not available across all the `pkg.go.dev`. As provided by the screenshot, all four symbols, are introduced in go1.5 but two of them have the `added in go1.5` comment but two of them do not. 

### What did you expect to see?

User should be able to expect the comment to be there for all symbols that is not available starting `1.0` (the original version)

Or very clearly have a version say `1.10`. Any symbol that introduced before 1.10 will be ignored from the `pkg.go.dev` and any symbol that introduced after 1.10 will be there.

**Comment by seankhliao** [comment] 2024-07-01 22:19
Duplicate of #51013

**Closed by seankhliao** 2024-07-01 22:19 UTC
Labels: pkgsite
