### ISSUE TITLE
cmd/go: generate ./... is defeated by submodules

### ISSUE THREAD

**Issue by adonovan** [golang/go#58723] opened 2023-02-24 22:39 UTC
The session below shows a repo containing a root module and a submodule, and a go.work file that uses both. The command `go generate ./...` within the submodule directory causes generators to run, but the command `go generate ./sub/...` from the root directory does nothing---this despite `go list ./sub/...` reporting the packages of the submodule.

```
ex$ cat go.work 
use ./sub
use .

ex$ cat go.mod
module example.com

go 1.19

ex$ ls sub
go.mod	sub.go

ex$ cat sub/go.mod
module example.com/sub

go 1.19

ex$ cat sub/sub.go
//go:generate echo hello

package sub

ex$ (cd sub && go generate ./...)
hello

ex$ go generate ./sub/...
```

I think this is a bug and that `go generate ./sub/...` should cause generators to run on all files of all directories of the packages that would be enumerated by `go list ./sub/...`.

**Comment by bcmills** [comment] 2023-02-24 22:43
Duplicate of #56098

**Closed by bcmills** 2023-02-24 22:43 UTC
