### ISSUE TITLE
x/website: Page "an article on refactoring" isn't rendered properly

### ISSUE THREAD

**Issue by xieyuschen** [golang/go#52003] opened 2022-03-29 08:43 UTC
### What is the URL of the page with the issue?
 
The website link is here: https://go.dev/talks/2016/refactor.article. It's not rendered properly like this.

 
### What is your user agent?
I tried it both on my windows10 and Macos and both of them failed.
 
 
 
### Screenshot
![picture](https://user-images.githubusercontent.com/52945328/160571201-227cd1a0-ba29-49b0-9998-3deb158436f2.png)

 
 
### What did you do?
I visited the release page of [go 1.9](https://go.dev/doc/go1.9#introduction) and clicked the [an article on refactoring](https://go.dev/talks/2016/refactor.article). And then I get the wrong page.
 
 
 
### What did you expect to see?
 The correct page with refactoring acknowledges.
 
 
### What did you see instead?
This one.
![picture](https://user-images.githubusercontent.com/52945328/160571201-227cd1a0-ba29-49b0-9998-3deb158436f2.png)

**Comment by seankhliao** [comment] 2022-03-29 09:47
Duplicate of #51989

**Closed by seankhliao** 2022-03-29 09:47 UTC
