### ISSUE TITLE
How can I use binary-package with `go.mod`

### ISSUE THREAD

**Issue by SmallAiTT** [golang/go#28920] opened 2018-11-22 09:56 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?

I want to use `binary-package` with `go.mod` mod.

**Comment by agnivade** [comment] 2018-11-22 11:49
Hi @SmallAiTT ,

This appears to be a question rather than a Go bug. We do not use the issue tracker for general discussions or questions like these. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

You might want to take a look at the [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.

Closing since this is not a bug.

**Closed by agnivade** 2018-11-22 11:49 UTC

**Comment by myitcv** [comment] 2018-11-22 20:52
Also please note https://github.com/golang/go/issues/28152
