### ISSUE TITLE
mime: jxl images are served with incorrect mimetype

### ISSUE THREAD

**Issue by akmittal** [golang/go#70165] opened 2024-11-02 05:05 UTC
### Go version

go version go1.23.2 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/akmittal/Library/Caches/go-build'
GOENV='/Users/akmittal/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/akmittal/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/akmittal/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.23.2/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.23.2/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.23.2'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/akmittal/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/akmittal/projects/jxl-mime/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/wx/s01xd6j11bqcs00cdnfq45wm0000gn/T/go-build3034666034=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

I served a directory with images using go static server. I am serving 2 files, 1 is `.jpg` another is `.jxl`. A repo with code is here https://github.com/akmittal/jxl-mime

### What did you see happen?

`.jxl` files are not served with the correct mimetype. Which prevents the browser to display images.

### What did you expect to see?

Browser prompts to download image instead of displaying in-browser. `.jxl` is supported file extension as per https://www.iana.org/assignments/media-types/media-types.xhtml#image

**Comment by ianlancetaylor** [comment] 2024-11-02 05:38
We expect your system /etc/mime.types file to have mappings like this.  What type of system are you deploying to?  What do you see in the /etc/mime.types file?

**Comment by akmittal** [comment] 2024-11-02 05:59
@ianlancetaylor Im doing this in my dev machine, Which is Mac OS 15.1

**Comment by seankhliao** [comment] 2024-11-02 11:42
Duplicate of #69530

**Closed by seankhliao** 2024-11-02 11:42 UTC
Labels: FrozenDueToAge
