### ISSUE TITLE
runtime: mayMoreStackPreempt failures

### ISSUE THREAD

**Issue by rsc** [golang/go#55160] opened 2022-09-20 02:34 UTC
#!watchflakes
    default <- section == "maymorestack=mayMoreStackPreempt" || pkg == "runtime:mayMoreStackPreempt"

Intermittent failures in the new mayMoreStackPreempt. This bug will replace #54778 and #55073.

**Comment by rsc** [comment] 2022-09-20 02:39
These were coming in multiple times per day and have now stopped for almost two weeks. Closing.

**Comment by cherrymui** [comment] 2023-01-13 23:23
No more failure for a while. Probably fixed by CL https://golang.org/cl/447495 , which is submitted at Nov. 4, so the time seems to match.

**Comment by prattmic** [comment] 2023-02-14 17:27
cc @aclements 

These timeouts blocked release branch CLs as flakes; we should get them fixed or skipped.

**Comment by aclements** [comment] 2023-02-15 14:26
This reproduces pretty quickly on my linux/amd64 laptop with:

```sh
cd runtime
go test -c
GOFLAGS="-gcflags=runtime=-d=maymorestack=runtime.mayMoreStackPreempt -gcflags=runtime/testdata/...=" stress2 ./runtime.test -test.run=CrashDumpsAllThreads
```

Of course, my usual first step would be to send it a SIGQUIT and see what's happening, but that's exactly what fails in this test. 😛 I haven't debugged yet. gdb may hold answers.

For reference, I initially tried running the testprog directly with the below script before I realized there are various pipes and signals involved in running this test. We might still need to reproduce those, but I'm hoping we can debug this through the test driver.

```sh
cd runtime/testdata/testprog
GOFLAGS="-gcflags=runtime=-d=maymorestack=runtime.mayMoreStackPreempt -gcflags=runtime/testdata/...=" go build
# Expects to write to FD 3 and then get a SIGQUIT
GOTRACEBACK=crash GOGC=off GODEBUG=asyncpreemptoff=1 ./testprog CrashDumpsAllThreads
```

**Comment by aclements** [comment] 2023-02-15 16:55
All of the Ms are just parked in `mPark` in normal places in the scheduler, except one thread that's in the infinite loop in `crashDumpsAllThreadsLoop`. `/proc/PID/status` and `/proc/PID/task/*/status` says there are no signals pending, blocked, or ignored by the process or any of its threads. It's a little suspicious that the blocked mask is 0, and in another Go process I have running it's fffffffc3bfa3a00.

**Comment by aclements** [comment] 2023-02-15 17:36
Ah hah, it's getting stuck before the SIGQUIT is involved. It's actually getting stuck in [this loop](https://cs.opensource.google/go/go/+/master:src/runtime/testdata/testprog/crashdump.go;l=22;drc=02a8e836616cb8eb6d776514c6239095b1328fd2), before the subprocess even indicates to the parent that it's ready for the SIGQUIT.

**Comment by aclements** [comment] 2023-02-15 18:53
Here's a version that works without a patch:

```sh
cd runtime/testdata/testprog
GOFLAGS="-gcflags=runtime=-d=maymorestack=runtime.mayMoreStackPreempt -gcflags=runtime/testdata/...=" go build
GOTRACEBACK=crash GOGC=off GODEBUG=asyncpreemptoff=1 stress2 -timeouts-fail -max-fails=1 -timeout=10s -pass="write to pipe" -max-runs=50000 ./testprog CrashDumpsAllThreads
```

**Comment by aclements** [comment] 2023-02-15 19:04
This isn't new, either. I reproduced in Go 1.18, which was the first release to have mayMoreStack.

**Comment by bcmills** [comment] 2023-04-04 14:47
@golang/runtime, should `TestCrashDumpsAllThreads` be skipped in the `mayMoreStackPreempt` configuration, or is there some other action in progress for this failure?

**Comment by bcmills** [comment] 2023-04-12 15:12
https://storage.googleapis.com/go-build-log/7a497521/linux-amd64-longtest_4c66413d.log (a SlowBot run)

**Comment by dr2chase** [comment] 2023-05-03 20:59
The cause of this flake (using Austin's reproducer above) is maymorestack instrumentation of any one (or more) of:
```
runtime.closechan
runtime.newobject
runtime.mallocgc
runtime.lock2
runtime.makechan
runtime.newproc
runtime.deductAssistCredit
```
beyond that I don't know.  I found these using compiler hash debugging and gossahash (both of these are being renovated/enhanced/replaced in coming weeks).

**Comment by prattmic** [comment] 2023-06-06 22:08
I believe this is a bug in https://go.dev/cl/7314062. (Yes, a 10 year old bug).

The "delicate dance" when a spinning M transitions to non-spinning is supposed to check all sources of work, but it doesn't check the global run queue: https://cs.opensource.google/go/go/+/master:src/runtime/proc.go;l=3084;drc=5b6e6d2b3d4d6877c86471209e249f1b6e36d0ca

gosched / mayMoreStack put the preempted goroutine on the global run queue, increasing the chance of failure (in addition to the extra stress it puts on the scheduler in general). Still, I am surprised this bug could go unnoticed for so long.

With that issue fixed, I can no longer reproduce this hang.

@gopherbot Please open backports to 1.20 and 1.19. This is a hang in the scheduler with no work around.

**Comment by prattmic** [comment] 2023-06-08 19:23
There is actually a second, similar issue: `gosched` (`runtime.Gosched` as well as `morestack` and async preemption) don't call `wakep`. They are submitting runnable work to the scheduler, so they must follow the same protocols for synchronizing with spinning Ms as any other source of work.

**Comment by mknyszek** [comment] 2023-06-30 16:59
Although this bug is causing failures, I think @prattmic decided to wait until Go 1.22 to land the fix? The changes aren't that complex, but the modified parts of the codebase are subtle. The primary failure modes are mitigated (I think? Why did we see a failure on June 16th if the test was skipped with mayMoreStack on June 6th? Oh. Is that a release branch?). We can also choose to backport it later.

**Comment by prattmic** [comment] 2023-06-30 18:29
Correct, the sweet results from my CLs are:

```
                     │ baseline.results │          cl501975.results          │          cl501976.results          │
                     │      sec/op      │   sec/op     vs base               │   sec/op     vs base               │
BiogoIgor                    13.89 ± 0%    13.90 ± 1%       ~ (p=0.523 n=30)    13.92 ± 0%       ~ (p=0.192 n=30)
BiogoKrishna                 11.99 ± 1%    11.95 ± 0%       ~ (p=0.197 n=30)    11.92 ± 1%       ~ (p=0.328 n=30)
BleveIndexBatch100           4.744 ± 1%    4.744 ± 1%       ~ (p=0.775 n=30)    4.755 ± 1%       ~ (p=0.592 n=30)
EtcdPut                     32.99m ± 1%   32.76m ± 1%       ~ (p=0.552 n=30)   33.07m ± 1%       ~ (p=0.843 n=30)
EtcdSTM                     146.7m ± 0%   147.1m ± 0%       ~ (p=0.382 n=30)   147.1m ± 0%       ~ (p=0.254 n=30)
GoBuildKubelet               51.63 ± 0%    51.72 ± 0%  +0.18% (p=0.036 n=30)    51.86 ± 0%  +0.45% (p=0.000 n=30)
GoBuildKubeletLink           7.316 ± 1%    7.317 ± 0%       ~ (p=0.959 n=30)    7.317 ± 0%       ~ (p=0.971 n=30)
GoBuildIstioctl              44.36 ± 1%    44.57 ± 0%  +0.46% (p=0.013 n=30)    44.60 ± 0%  +0.54% (p=0.007 n=30)
GoBuildIstioctlLink          7.789 ± 0%    7.798 ± 0%       ~ (p=0.286 n=30)    7.799 ± 0%       ~ (p=0.562 n=30)
GoBuildFrontend              16.04 ± 0%    16.08 ± 0%  +0.26% (p=0.021 n=30)    16.10 ± 0%  +0.41% (p=0.001 n=30)
GoBuildFrontendLink          1.282 ± 1%    1.272 ± 1%       ~ (p=0.177 n=30)    1.274 ± 1%       ~ (p=0.358 n=30)
GopherLuaKNucleotide         21.87 ± 1%    21.80 ± 1%       ~ (p=0.485 n=30)    21.49 ± 1%  -1.77% (p=0.000 n=30)
MarkdownRenderXHTML         259.5m ± 2%   259.4m ± 1%       ~ (p=0.552 n=30)   263.4m ± 3%       ~ (p=0.843 n=30)
Tile38QueryLoad             511.6µ ± 0%   511.9µ ± 0%       ~ (p=0.562 n=30)   514.5µ ± 0%  +0.55% (p=0.000 n=30)
geomean                      2.087         2.086       -0.06%                   2.090       +0.11%
```

The effect here is pretty small, but has the potential to be bigger for edge-case applications. I'd be more comfortable giving this time to soak during 1.22.

This can cause complete stuckness when `GOMAXPROCS=1` and `GODEBUG=asyncpreemptoff=1`. Avoiding either of those should avoid hangs (though the scheduler may still underutilize GOMAXPROCS) [1].

[1] Technically if async preemption is disabled, then it takes GOMAXPROCS goroutines spinning in an infinite loop to cause stuckness. So GOMAXPROCS=2 could still hang if there are 2 spinning goroutines.

**Comment by prattmic** [comment] 2023-06-30 18:30
https://go.dev/cl/501229 should be skipping this test entirely. I agree it is odd that we got another failure on June 16 (it isn't a release branch). Maybe that GCFLAGS check isn't correct?

**Comment by mknyszek** [comment] 2024-03-13 20:45
The `TestNetpollDeadlock` failures seem like #66275, so I'm inclined to say it's not specific to `mayMoreStack` and close this for now.

**Comment by mknyszek** [comment] 2024-04-08 21:43
I have a revert CL out to fix this.

**Comment by mknyszek** [comment] 2024-04-08 21:58
I think I understand what went wrong here. Looks like the fact that this CL made the tracer more preemptible also made it much more likely that the trace would have a broken tail. The test seems to succeed overall though, because other invariants it checks are completely fine. I think I know how to fix this to re-land it.

**Comment by mknyszek** [comment] 2024-04-08 21:59
Revert landed.

**Comment by mknyszek** [comment] 2024-04-18 23:40
The non-Windows failures are likely just stragglers from the fix. The Windows failures are likely because something is failing to flush (a pipe, in this case...?).

**Comment by matloob** [comment] 2024-05-01 19:03
Should we skip this test on Windows until the flakiness is fixed?

**Comment by mknyszek** [comment] 2024-05-07 21:32
@matloob Ah, sorry for missing this.

I'll send a skip and/or a fix ASAP.

**Comment by mknyszek** [comment] 2024-05-07 21:40
I was able to reproduce. I may be able to find a fix.

**Closed** 2024-05-08 19:05 UTC
Labels: NeedsFix, early-in-cycle, compiler/runtime
