### ISSUE TITLE
cmd/go: go mod tidy error when importing std package in later go version

### ISSUE THREAD

**Issue by mvertes** [golang/go#40067] opened 2020-07-06 08:08 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/marc/.cache/go-build"
GOENV="/home/marc/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/marc/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/marc/sdk/go1.13.12"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/marc/sdk/go1.13.12/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/marc/go/src/github.com/containous/yaegi/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build070856350=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

consider a `sample` module with a following file `sample.go`:

<pre>
// +build go1.14

package sample

include _ "hash/maphash"       // this package exists in go1.14 but not in go1.13
</pre>

and a `go.mod`:

<pre>
module example.com/sample

go 1.12
</pre>

And then in this module, running the following command:
<pre>
go1.13.12 mod tidy
</pre>

### What did you expect to see?
no errors

As `hash/maphash` package is not present in `go1.13` (introduced in `go1.14`), but the `sample.go` files should be skipped by `go1.13` thanks to the build tag `// +build go1.14`

### What did you see instead?
<pre>
github.com/containous/yaegi/stdlib imports
        hash/maphash: malformed module path "hash/maphash": missing dot in first path element
</pre>

I believe that a similar issue occurs in the latest release, maybe with a different error message.

**Comment by jayconrod** [comment] 2020-07-06 15:13
This is mostly working as intended, but the error seems very frustrating.

`go mod tidy` ignores build constraints when deciding what dependencies are needed. If it didn't, it would remove platform-specific dependencies (for example, modules providing packages only imported from files with `// +build windows`). That would be frustrating for teams working in mixed environments. (As an exception, files with the `ignore` tag are still excluded, as are files in `testdata` directories or directories starting with `.` or `_`).

In this case though, `tidy` in 1.13 treats `hash/maphash` as a regular import and reports an error. Since there's no dot in the first path element, and there's no required module that could provide that package, perhaps `tidy` should assume it's a standard package in a future version of Go and ignore it.

cc @bcmills @matloob

**Comment by mpl** [comment] 2020-07-08 13:41
By the way, this problem (as expected) also occurs with `go mod vendor`.

**Comment by bcmills** [comment] 2020-07-17 15:57
I'm not sure that burying the error would be a good idea: we can't in general tell whether the missing `hash/maphash` is a new standard-library package, or a missing dependency that should be slotted in using a `replace` directive.

I would be more comfortable with a more narrowly targeted fix. For example, perhaps we should only ignore plausibly-standard-library imports if they occur in files that would normally be excluded by a `go1.X` build constraint.

**Comment by bcmills** [comment] 2020-07-17 15:59
```txtar
example.com$ go1.13.14 build

example.com$ go1.14.6 build

example.com$ go1.13.14 mod tidy
example.com imports
        hash/maphash: malformed module path "hash/maphash": missing dot in first path element

example.com$ go1.14.6 mod tidy

-- all.go --
package example
-- example114.go --
// +build go1.14

package example

import _ "hash/maphash"
-- go.mod --
module example.com

go 1.14
```

**Comment by bcmills** [comment] 2020-09-18 15:49
I'm planning to add a `-e` flag to `mod tidy` in 1.16. That won't completely cover this use-case (it won't heuristically suppress the errors when the `-e` flag is *not* set), but I think it will mitigate it enough that we can lower the priority of a more tailored fix.

**Comment by zikaeroh** [comment] 2020-11-21 19:35
Hit this in [golang-migrate](https://github.com/golang-migrate/migrate/issues/480), which added an `io/fs` migration driver for 1.16, but then fails to tidy both in the repo itself or in importers:

```
github.com/golang-migrate/migrate/v4/source/iofs imports
	io/fs: package io/fs is not in GOROOT (/usr/lib/go/src/io/fs)
github.com/golang-migrate/migrate/v4/source/iofs tested by
	github.com/golang-migrate/migrate/v4/source/iofs.test imports
	embed: package embed is not in GOROOT (/usr/lib/go/src/embed)
```

```
github.com/hortbot/hortbot/internal/db/migrations imports
	github.com/golang-migrate/migrate/v4/database/postgres tested by
	github.com/golang-migrate/migrate/v4/database/postgres.test imports
	github.com/golang-migrate/migrate/v4/source/file imports
	github.com/golang-migrate/migrate/v4/source/iofs imports
	io/fs: package io/fs is not in GOROOT (/usr/lib/go/src/io/fs)
github.com/hortbot/hortbot/internal/db/migrations imports
	github.com/golang-migrate/migrate/v4/database/postgres tested by
	github.com/golang-migrate/migrate/v4/database/postgres.test imports
	github.com/golang-migrate/migrate/v4/source/file imports
	github.com/golang-migrate/migrate/v4/source/iofs tested by
	github.com/golang-migrate/migrate/v4/source/iofs.test imports
	embed: package embed is not in GOROOT (/usr/lib/go/src/embed)
```

It probably wasn't a big deal when it was only maphash (a bit niche), but this probably is going to become more prevalent given the impact `io/fs` and `embed` are likely to make and the wide range of libs like migration tools / config libraries that are likely to want to use these new packages but also maintain lower minimum Go versions.

**Comment by abursavich** [comment] 2020-12-30 22:34
I recently hit this issue when I was trying to make a [shim](https://github.com/abursavich/fs-shim) to support `io/fs` for another project that will be unable to upgrade to Go 1.16 quickly.

I think the real solution is to decouple the standard library (or as much of it as possible) from the language and tooling releases. This would give the standard library much more flexibility to evolve separately from the language and enable API-breaking v2 changes (probably after generics land).

Obviously, this would require a fully thought-out proposal, but the straw man version off the top of my head... Go 1.x would move to an external stdlib (a snapshot of which would be packaged with the language for self-hosting) and it would replace usages in pre-Go 1.x modules with their external v1 counterparts (e.g. `replace io => golang.org/pkg/io`). A `go fix` rule could update all import paths for modules making the transition.

**Comment by bcmills** [comment] 2021-01-06 19:50
@abursavich, #30241 is a more fleshed-out proposal for standard-library vendoring. Some parts of the standard library (such as `embed`) are tightly coupled to the compiler, linker, and/or runtime, and so those parts necessarily cannot be released as standalone (and independently-upgradable) modules.

The parts of the standard library that are not tightly coupled to the toolchain or runtime could be rewritten as forwarding shims to modules outside the standard library, which could then (under that proposal) be upgraded above — but not downgraded below — the versions required by the standard library.

See #30241 for more detail and discussion on that topic.

**Comment by zikaeroh** [comment] 2021-01-06 22:35
I was thinking about this the other day; would it make sense to add a mechanism to ignore these packages' absence during commands that don't do any compilation (e.g. tidy, get), then once newer versions of Go are released, backport a list of the new packages to the supported releases so that they know that the new packages are "okay"?

Given only the previous two releases are supported and the number of new packages added per release are small, I can see this working reasonably well. I recall a few releases ago (1.9 and 1.10?) where some changes were backported to help with the introduction of modules in 1.11, and I find that similar in intention.

**Comment by tv42** [comment] 2021-01-11 18:35
@bcmills 

> or a missing dependency that should be slotted in using a replace directive.

Wouldn't the standard answer be for such replace directives to also be using leading path segments that don't look like stdlib imports, for exactly this reason?

Anyone outside of stdlib using a dotless import path first segment is just asking for trouble, conflicting with future stdlib additions.

**Comment by bcmills** [comment] 2021-01-11 18:48
> Wouldn't the standard answer be for such replace directives to also be using leading import path segments that don't look like stdlib imports, for exactly this reason?

Yes.

> Anyone outside of stdlib using a dotless import path first segment is just asking for trouble, conflicting with future stdlib additions.

Agreed, but plenty of existing Go code (especially closed-source Go code) is written in that style. At this point I do not want to make the migration to modules more difficult or confusing than it already is for those users.

**Comment by avivataqua** [comment] 2021-02-16 20:51
I've encountered this issue with a somewhat different use case
if anyone can suggest a better solution/work-around for this case, I'd appreciate it
i have a single code base that i compile one with go1.15.6 and once with go1.15.6b5 (dev.boringcrypto branch)
I rely on a build constraint tag to avoid compiling go files that import 'crypto/tls/fipsonly 
mod vendor fails with 'not in GOROOT' for go1.15.6

**Comment by bcmills** [comment] 2021-02-17 15:33
@avivataqua, for now you can run `go mod tidy -e` using Go 1.16.

(Longer term, I think we should probably change `go mod tidy` to automatically suppress errors for missing imports in build-constrained files.)

**Comment by zikaeroh** [comment] 2021-02-18 00:30
This now affects `golang.org/x/tools/godoc/vfs`, as [CL 291669](https://go-review.googlesource.com/c/tools/+/291669) added `io/fs` usage guarded by a build tag to an existing package.

Given:

```go
package main

import (
	"golang.org/x/tools/godoc/vfs"
)

func main() {
	var _ vfs.FileSystem
}
```

And go.mod:

```
module some.tld/vfsthing

go 1.15

require golang.org/x/tools v0.1.1-0.20210217234408-19ff21fbe961
```

`go mod tidy` with Go 1.15 says:

```
some.tld/vfsthing imports
	golang.org/x/tools/godoc/vfs imports
	io/fs: package io/fs is not in GOROOT (/usr/lib/go/src/io/fs)
```

This doesn't affect me personally, but I would sort of expect people to see this in the wild.

While this is caused by this issue, I can open a new issue just for `x/tools/godoc/vfs` if desired, if a new package needs to be created instead, like how mapfs and httpfs exist.

cc @rsc

**Comment by zikaeroh** [comment] 2021-02-19 01:21
And now `x/tools/go/analysis/passes/builtag` depends on the new `go/build/constraint` package via [CL 293834](https://go-review.googlesource.com/c/tools/+/293834), so the tool I wrote to manage my `$GOBIN` via modules fails because it cannot tidy when pulling in `gopls` anymore:

```
	golang.org/x/tools/gopls imports
	golang.org/x/tools/gopls/internal/hooks imports
	golang.org/x/tools/internal/lsp/source imports
	golang.org/x/tools/go/analysis/passes/buildtag imports
	go/build/constraint: package go/build/constraint is not in GOROOT (/usr/lib/go/src/go/build/constraint)
```

(And I'm still waiting for my distribution to get Go 1.16 :frowning_face:)

**Comment by myitcv** [comment] 2021-02-19 13:28
> Longer term, I think we should probably change `go mod tidy` to automatically suppress errors for missing imports in build-constrained files

I did wonder whether the heuristic could be made more specific so that `go mod tidy` does _not_ ignore the `go*` build constraints. 

Suppressing errors for missing imports in build-constrained files "feels" too broad.

**Comment by myitcv** [comment] 2021-02-19 13:29
> for now you can run `go mod tidy -e` using Go 1.16.

The snag here being that `go mod tidy -e` is required for Go 1.15X :)

**Comment by zikaeroh** [comment] 2021-02-19 17:58
> I did wonder whether the heuristic could be made more specific so that `go mod tidy` does _not_ ignore the `go*` build constraints.
> 
> Suppressing errors for missing imports in build-constrained files "feels" too broad.

The approach I suggested in https://github.com/golang/go/issues/40067#issuecomment-755759189 would be more targeted to known new packages, though when I suggested this I didn't realize boringcrypto also had its own special packages too (hopefully that's the end of the line).

**Comment by rsc** [comment] 2021-03-02 18:16
Duplicate of #44649.

**Closed by rsc** 2021-03-02 18:16 UTC
Labels: NeedsDecision, modules
