### ISSUE TITLE
net/http: TestInterruptWithPanic_h2 flakes on ppc64le builder

### ISSUE THREAD

**Issue by mwhudson** [golang/go#17243] opened 2016-09-26 23:52 UTC
The failure looks like this:

```
--- FAIL: TestInterruptWithPanic_h2 (0.01s)
    clientserver_test.go:1158: Get https://127.0.0.1:51367: stream error: stream ID 1; INTERNAL_ERROR
FAIL
FAIL    net/http    13.570s
```

It's happened three times in the last three screens of build.golang.org:

https://build.golang.org/log/969151e16737eda8c8720b1c0c3cb6f0ddbe5025
https://build.golang.org/log/ae7a7294c3d83cc5584aabeec8bb4fe55b9e4832
https://build.golang.org/log/512a378cc11774b203aa0962c9818326eda0cd76

but I have the vague feeling it's been going on for a while.

**Comment by quentinmit** [comment] 2016-10-03 22:38
@aclements Can you run your flake finder tool on this?

**Comment by aclements** [comment] 2016-10-04 00:28
Looks like it's been flaking on more than just PPC:

`$ greplogs -dashboard -e TestInterruptWithPanic_h2 -e INTERNAL_ERROR -l -md`
[2016-04-19T22:04:30-8b20fd0/freebsd-arm-paulzhol](https://build.golang.org/log/9d3f48e0fe2f0dfec444f5d084d90f0bc8fa86ff)
[2016-05-03T00:49:46-499cd33/freebsd-arm-paulzhol](https://build.golang.org/log/53424b22dbd12b871f1e170d86d35de3a7511d12)
[2016-05-06T16:43:51-c81a353/darwin-386-10_10](https://build.golang.org/log/6427c7946ca0d9770e4ff54c8986eb8a901a4fcd)
[2016-05-10T03:55:12-3d82432/linux-amd64-race](https://build.golang.org/log/c06ddfed924950377bc7764cd5276345965113a8)
[2016-05-18T14:18:48-b30fcbc/linux-ppc64le-buildlet](https://build.golang.org/log/413ed0f823134ef78a27e7cd7b10fb38182cc31e)
[2016-06-24T02:21:02-f9d6b90/freebsd-arm-paulzhol](https://build.golang.org/log/30a5284201a6f93045f65da332fcf2d60c03b66e)
[2016-08-09T00:43:25-392bf3a/darwin-amd64-10_9](https://build.golang.org/log/8ba62801109ba87c2cb6464d74fc0ab5b4926bce)
[2016-08-17T23:23:28-6937167/darwin-amd64-10_9](https://build.golang.org/log/9f9d561a669bc9a2f62e2b3d290785d143f87360)
[2016-08-23T14:53:47-03723c9/darwin-amd64-10_8](https://build.golang.org/log/7bb40c090d03cc6327c237a735267a674cd15f4b)
[2016-09-14T16:39:47-2e67514/android-arm64-sdk21](https://build.golang.org/log/a0baa66b59f9159d48f434037bd7e25b9faf09f3)
[2016-09-17T00:34:19-a1bf203/linux-ppc64le-buildlet](https://build.golang.org/log/512a378cc11774b203aa0962c9818326eda0cd76)
[2016-09-25T02:38:11-890c09e/linux-ppc64le-buildlet](https://build.golang.org/log/ae7a7294c3d83cc5584aabeec8bb4fe55b9e4832)
[2016-09-26T22:01:32-d211c2d/linux-ppc64le-buildlet](https://build.golang.org/log/969151e16737eda8c8720b1c0c3cb6f0ddbe5025)

Flake analysis isn't very helpful with this one, I'm afraid:

```
$ greplogs -dashboard -e TestInterruptWithPanic_h2 -e INTERNAL_ERROR -l | findflakes -paths
First observed 8b20fd0 19 Apr 22:04 2016 (1668 commits ago)
Last observed  d211c2d 26 Sep 22:01 2016 (88 commits ago)
51% chance failure is still happening
0.76% failure probability (13 of 1581 commits)
Likely culprits:
    1% 8b20fd0 cmd/compile: transform some Phis into Or8.
    1% 082f464 go/types: trailing semis are ok after valid fallthrough
    1% a4dd6ea runtime: add maxSliceCap
    1% 55ab07c cmd/compile: static composite literals are side-effect free
    1% 3c6e60c cmd/compile: fix isStaticCompositeLiteral
    1% 562d398 go/types: accept trailing empty stmts in terminating stmt lists
    1% 9b6bf20 crypto/aes: de-couple asm and go implementations
    1% 03e216f cmd/compile: re-enable in-place append optimization
    1% b5ddbb9 spec: refine rules about terminating statements
    1% a39950b crypto/aes: delete TestEncryptBlock and TestDecryptBlock
No known past failures
```

**Comment by bradfitz** [comment] 2016-11-11 19:01
I can't reproduce this.

I deflaked this test in 238247eb59cdddeedaa5c5db67734df2cd1049ab but that commit message is misleading. It was only deflaking additions added in https://golang.org/cl/33099 and https://golang.org/cl/33103.

It looks like the original flake code remains unchanged.

In particular, the test handler does this:

```go
        cst := newClientServerTest(t, h2, HandlerFunc(func(w ResponseWriter, r *Request) {
                io.WriteString(w, msg)
                w.(Flusher).Flush()
                panic(panicValue)
        }), func(ts *httptest.Server) {
```

That means the Handler's http2 `HEADERS` frame should be written on the wire before the `RST_STREAM` of error `INTERNAL_ERROR`.

@tombergan, did you fix this by accident when you redid the http2 write scheduler?

Or, can you imagine why we'd schedule a `RST_STREAM` before a `HEADERS`?

**Comment by tombergan** [comment] 2016-11-14 20:40
Here's one hypothesis. sc.resetStream constructs a FrameWriteRequest that doesn't have a stream field:
https://github.com/golang/net/blob/master/http2/server.go#L1081

Both the old and new write schedulers use the stream field to determine which queue gets the FrameWriteRequest:
https://github.com/golang/net/blob/c33d37840d93fc75251f49ab83c5fc8b2faea5e8/http2/writesched.go#L84
https://github.com/golang/net/blob/master/http2/writesched.go#L64

This means RST_STREAM frames will be added to the root queue (for control frames), which is processed before the stream queues. We could have this sequence of events:
1. queue HEADERS (on stream queue)
2. queue RST_STREAM (on root queue -- this is buggy)
3. schedule RST_STREAM (since root has priority)
4. schedule HEADERS

The test will pass if step 3 happens before step 2, but will fail in the above order. Both the old and new write schedulers have this bug -- more precisely, the bug is in sc.resetStream. This bug can explain the flake. However, I can't explain why the test has stopped flaking. Perhaps something changed in the buffering code which made the above order much less likely?

**Comment by bradfitz** [comment] 2016-11-14 21:37
To be clear, I've never been able to reproduce it.

And it hasn't happened many times I don't think.

**Comment by tombergan** [comment] 2016-11-14 22:29
A bit busy today, but I can get to this tomorrow if you don't get there first.

**Comment by bradfitz** [comment] 2016-11-15 00:45
Sent https://go-review.googlesource.com/33238

**Comment by bradfitz** [comment] 2016-11-16 23:42
Apparently https://github.com/golang/net/commit/00ed5e97ea3a5ac46658b98e50259941947cec04 wasn't enough.

I still see a flake:
https://build.golang.org/log/2211304f54d156c6eafdd1ab4e15da8c16a19c1c
```
--- FAIL: TestInterruptWithPanic_nil_h2 (0.02s)
	clientserver_test.go:1191: Get https://127.0.0.1:58409: stream error: stream ID 1; INTERNAL_ERROR
FAIL
FAIL	net/http	3.481s
```

**Comment by bradfitz** [comment] 2016-11-16 23:43
I'm going to deflake this a different way, without fixing the http2 issue for now.

**Comment by bradfitz** [comment] 2016-11-17 00:16
TODO(bradfitz): file bug about the general problem and theory and then close this one.

**Comment by bradfitz** [comment] 2016-11-21 22:20
I'll repurpose this bug about the x/net/http2 behavior.

It seems that even with our fix in https://golang.org/cl/33238 (and bundling it into std), this flaky test persists. Perhaps the problem is now in the Transport instead of the Server.

Investigate for Go 1.9.

**Comment by bradfitz** [comment] 2016-11-21 22:21
That is, if the Transport sees a HEADERS frame on the wire and then "immediately" sees a RST_STREAM, is it possible for the Transport to report an error instead of its RoundTrip returning a non-nil *Response and nil error?

**Comment by bradfitz** [comment] 2016-12-20 20:30
@tombergan, I think between the Transport and Server changes, we might've fixed this one?

**Comment by tombergan** [comment] 2016-12-20 21:54
If it hasn't been flaking, I say close it.

**Closed** 2016-12-20 22:03 UTC
Labels: NeedsInvestigation
