### ISSUE TITLE
net/http: Transport.Clone returns broken transport

### ISSUE THREAD

**Issue by AidanWelch** [golang/go#67284] opened 2024-05-10 13:24 UTC
### Go version

go version go1.22.2 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/aidan/.cache/go-build'
GOENV='/home/aidan/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/aidan/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/aidan/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/snap/go/10585'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/snap/go/10585/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.2'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/aidan/test/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3513958785=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

```go
package main

import (
	"fmt"
	"io"
	"net/http"
)

func main() {
	originalTransport := &http.Transport{}
	clonedTransport := originalTransport.Clone()

	clonedClient := &http.Client{
		Transport: clonedTransport,
	}

	clonedResp, err := clonedClient.Get("https://api.ipify.org")
	if err == nil {
		clonedBodyBuf, _ := io.ReadAll(clonedResp.Body)
		clonedResp.Body.Close()
		fmt.Println("Cloned: ", string(clonedBodyBuf))
	} else {
		fmt.Println(err.Error())
	}
}
```

### What did you see happen?

```
Get "https://api.ipify.org": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00d\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\x7f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"
```

### What did you expect to see?

```
Cloned: [IP Address]
```

**Comment by AidanWelch** [comment] 2024-05-10 13:26
Also, this bug itself seems to be the root cause for https://github.com/golang/go/issues/39302, so maybe renaming that issue would be useful if this will be closed as a duplicate.

**Comment by seankhliao** [comment] 2024-05-11 09:02
Duplicate of #39302

**Closed by seankhliao** 2024-05-11 09:02 UTC
