### ISSUE TITLE
Unable to print math.MaxUint64

### ISSUE THREAD

**Issue by theGreatWhiteShark** [golang/go#36455] opened 2020-01-08 14:42 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
> go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

jupp

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

> 
> GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/X/Library/Caches/go-build"
GOENV="/Users/X/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/X/git/getml/package-pipelines/dependencies/relboost-monitor/Code"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wr/bphy451d5zs7ng1vk0ql8csr0000gn/T/go-build813277185=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

``` go
package main

import (
	"math"
)

func main() {
	println(math.MaxUint64)
}
```

### What did you expect to see?

> +1.844674e+019

### What did you see instead?

> ./minimal_uint64.go:8:9: constant 18446744073709551615 overflows int64

**Comment by Nojus297** [comment] 2020-01-08 14:53
I think you should cast to uint64
`println(uint64(math.MaxUint64))`

**Comment by ALTree** [comment] 2020-01-08 14:54
Hi,

this is  #19621, see that thread for an explanation. Closing here, since this is working as intended.

**Closed by ALTree** 2020-01-08 14:54 UTC
