### ISSUE TITLE
playground: detect and support tests

### ISSUE THREAD

**Issue by bcmills** [golang/go#23571] opened 2018-01-26 19:18 UTC
When I'm code-reviewings tests (or reporting bugs in the `testing` package), I sometimes need to figure out what the actual behavior of the package will be. For example, I might want to check what the subtest name-escaping will do for a given input, or check an interaction between stateful functions (e.g., `Parallel`, `Helper`, `Error`).

Unfortunately, the `testing` package is not amenable to being run outside of a generated test program: it does not appear to provide any supported way to construct a `*testing.T` or `*testing.M`.

It would be nice if the playground itself could detect test programs and treat them as such. Today, it rejects them with `package name must be main`. (https://play.golang.org/p/3J3HRClqeAM)

**Comment by dominikh** [comment] 2018-01-26 19:55
Closing as duplicate of #6511

**Closed by dominikh** 2018-01-26 19:55 UTC
