### ISSUE TITLE
cmd/compile: better error for missed comma

### ISSUE THREAD

**Issue by dvyukov** [golang/go#8401] opened 2014-07-21 18:22 UTC
<pre><a href="http://play.golang.org/p/5iVYdAPl8B">http://play.golang.org/p/5iVYdAPl8B</a>

gc says:
prog.go:12: syntax error: unexpected name, expecting }

gofmt says:
12:18: expected '}', found 'IDENT' Const2 (and 1 more errors)

While what is missed is actually a comma. It's unclear why compiler does not expect a
comma there. It would be nice if the error message would mention comma.</pre>

**Comment by odeke-em** [comment] 2016-07-24 08:58
I believe this issue was fixed by https://go-review.googlesource.com/#/c/17080 and works as intended explaining the missing comma

Please try clicking "Run" or "Format" on the original test program https://play.golang.org/p/5iVYdAPl8B or see  the screenshots below
<img width="639" alt="screen shot 2016-07-24 at 1 54 05 am" src="https://cloud.githubusercontent.com/assets/4898263/17082887/03bc7c2a-5142-11e6-9d7e-be657d6351a7.png">

<img width="656" alt="screen shot 2016-07-24 at 1 53 56 am" src="https://cloud.githubusercontent.com/assets/4898263/17082888/0addfff6-5142-11e6-858e-9845fceed23f.png">

**Comment by odeke-em** [comment] 2016-07-27 12:54
Ping @bradfitz.

**Comment by bradfitz** [comment] 2016-07-27 13:12
Thanks. Closing.

**Closed by bradfitz** 2016-07-27 13:12 UTC
