### ISSUE TITLE
x/pkgsite: Order search results by popularity (`Imported by` field)

### ISSUE THREAD

**Issue by asilverman** [golang/go#46373] opened 2021-05-25 20:05 UTC
As a user of https://pkg.go.dev/, I would like to search for a package and organize/rank the results by the `Imported by` field

### What did you expect to see?

A means to order results so I can easily find the more popularly adopted solution. I would like to be empowered to make the decision of choosing one solution over another based on my own criteria, the system can help me make up my mind by making available ordering based on the fields available. 

By this I am not asking that the results have some default ordering, by default they be unordered. I am asking to be able to do some basic filtering/ordering by some custom criteria based on the available fields.

### What did you see instead?

A list of unordered results with no way to order them.

**Comment by seankhliao** [comment] 2021-05-25 20:36
Duplicate of #39195 #36952

**Closed by seankhliao** 2021-05-25 20:36 UTC
Labels: pkgsite
