### ISSUE TITLE
encoding/json: empty fields in json.UnmarshalTypeError when using struct with UnmarshalJSON

### ISSUE THREAD

**Issue by Keylor42** [golang/go#28076] opened 2018-10-08 15:01 UTC
### What version of Go are you using (`go version`)?
`go1.11.1 linux/amd64`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""`
GOCACHE="/home/tpaulmyer/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/tpaulmyer/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build650471952=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
I tried to unmarshal a wrong type into a struct that has a custom UnmarshalJSON method attached to it and use the fields of the UnmarshalTypeError: https://play.golang.org/p/nNQ2v76VZnz.

### What did you expect to see?
In go 1.10.4, the fields Struct and Field of the UnmarshalTypeError are set.

### What did you see instead?
In go 1.11.1, they are not.

**Comment by iand** [comment] 2018-10-09 00:05
Duplicate of #27464 which is fixed on tip

**Comment by agnivade** [comment] 2018-10-09 03:55
Thanks.

**Closed by agnivade** 2018-10-09 03:55 UTC
