### ISSUE TITLE
go get does not install new packages/binaries when GO111MODULE=on

### ISSUE THREAD

**Issue by pcostanza** [golang/go#28309] opened 2018-10-22 13:17 UTC
### What version of Go are you using (`go version`)?

1.11.1

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

linux, and64

### What did you do?

When GO111MODULE=off,  I can use go get to download and install a program. For example go get github.com/exascience/elprep (one of our repositories) downloads the source code and dependencies into $GOPATH/src/ and installs the main program into $GOPATH/bin/. This works no matter which folder I am doing this from. I don't have to be inside $GOPATH somewhere for this to work, or inside some other development folder.

This is especially nice for end users, because we can provide a very simple instruction with which they can create and install a binary.

When GO111MODULE=on, this doesn't work anymore. Instead, an error message is printed "cannot find main module."

### What did you expect to see?

I believe that either (a) go get should still work as with GO111MODULE=off, or else (b) there should be some other command to allow for simple downloading source code and installing binaries, even when you are not actively developing some code.

For (a) it's probably acceptable if the source code is not downloaded into $GOPATH/src, but into the current folder (like with git clone for example). Maybe a mode that stashes the source code away in some hidden folder and only makes the binary available would also work.

### What did you see instead?

See above.

I'm not 100% sure I'm not missing something. I also tried go install, without good results. We could expand the instructions for end users to call "git clone https://github.com/exascience/elprep.git && cd elprep && go install github.com/exascience/elprep/v4" - but that's less user-friendly. It would then also still be an issue that there is no single command that works for both GO111MODULE=on an =off.

This is not a very urgent issue, since with the default GO111MODULE=auto setting, everything works fine. This is just to create an awareness for a feature that would be missing once you deprecate GOPATH mode.

**Comment by agnivade** [comment] 2018-10-22 15:52
Thanks for raising the issue. It is a duplicate of https://github.com/golang/go/issues/24250. Please have a look into that.

**Closed by agnivade** 2018-10-22 15:52 UTC

**Comment by ypapax** [comment] 2019-06-24 05:31
Thanks, @pcontaza, you saved my day, `GO111MODULE=auto go get` works perfectly
