### ISSUE TITLE
cmd/go: go build fails with permission error inside a temporary directory on Windows

### ISSUE THREAD

**Issue by zhaoyunxing92** [golang/go#42224] opened 2020-10-27 03:12 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\zyx\AppData\Local\go-build
set GOENV=C:\Users\zyx\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\gopath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\gopath
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=D:\software\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\software\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\code\github\go\go-mongo\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\zyx~1\AppData\Local\Temp\go-build500345966=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

go run main.go

### What did you see instead?
open C:\Users\zyx~1\AppData\Local\Temp\go-build933307734\b001\exe\a.out.exe: The process cannot access the file because it is being used by another process.

**Comment by davecheney** [comment] 2020-10-27 03:14
Thank you for raising this issue. Anti virus software often causes problems on windows systems. Would you be able to temporarily disable your AV software and see if that makes a difference?

**Comment by zhaoyunxing92** [comment] 2020-10-27 03:20
> Thank you for raising this issue. Anti virus software often causes problems on windows systems. Would you be able to temporarily disable your AV software and see if that makes a difference?

thank you for your reply,I can't  close it,I wonder if modifying his build directory can be solved

**Comment by davecheney** [comment] 2020-10-27 04:27
As a workaround can you try using `go build` to build the binary, then run the resulting `.exe` and see if that helps?

**Comment by zhaoyunxing92** [comment] 2020-10-27 04:33
> As a workaround can you try using `go build` to build the binary, then run the resulting `.exe` and see if that helps?

the same mistake,whether to change the directory of GOGCCFLAGS can be resolved,but it doesn't seem like it can be changed

**Comment by davecheney** [comment] 2020-10-27 04:35
> the same mistake,

Can you please post the entire output you see. Do not use a screenshot.

> whether to change the directory of GOGCCFLAGS can be resolved,but it doesn't seem like it can be changed

This seems unrelated. Please open a new issue so it can be addressed independently. Thank you

**Comment by zhaoyunxing92** [comment] 2020-10-27 04:55
> > the same mistake,
> 
> Can you please post the entire output you see. Do not use a screenshot.
> 
> > whether to change the directory of GOGCCFLAGS can be resolved,but it doesn't seem like it can be changed
> 
> This seems unrelated. Please open a new issue so it can be addressed independently. Thank you

```shell
12:55 [xyz@docker go-mongo ] (develop) go build main.go
open C:\Users\zyx~1\AppData\Local\Temp\go-build060591562\b001\exe\a.out.exe: The process cannot access the file because it is being used by another process.

```

**Comment by dmitshur** [comment] 2020-10-30 21:45
CC @jayconrod, @matloob, @bcmills.

**Comment by GronkeyKong** [comment] 2022-01-25 12:46
The problem is that if GOTMPDIR is not set, golang will sometimes build in that generic \Temp directory that is dangerous to allow as a generic exception to Kaspersky.

Assuming you've already added your GOPATH as an exception in Kaspersky (for example, "C:\Users\<user>\go"...what worked for me was to 
1) add a new directory (I named mine "tmp" but you could probably name it a number of things) within that path, i.e., "C:\Users\<user>\go\tmp"
2) Set the golang environment variable GOTMPDIR to it...
> go env -w GOTMPDIR="C:\Users\<user>\go\tmp"

And the issue goes away.  But not that I already added "C:\Users\<user>\go" as an exception to Kaspersky.

**Comment by elazarg** [comment] 2023-09-28 08:18
This is the same issue as #29093, and is still reproduced (1.20).

**Comment by bcmills** [comment] 2023-10-12 20:56
As far as I can tell the solution here is to set `GOTMPDIR`.

@elazarg, if you are correctly setting `GOTMPDIR` to a directory should that should be usable, please file a new issue and fill out the complete issue template. This issue is old and appears to be very stale.

**Closed by bcmills** 2023-10-12 20:56 UTC
Labels: OS-Windows, NeedsInvestigation
