### ISSUE TITLE
x/website: incorrect redirect https://blog.golang.org/feed.atom -> https://golang.google.cn/feed.atom

### ISSUE THREAD

**Issue by bugwatcher** [golang/go#47893] opened 2021-08-22 19:26 UTC
### What is the URL of the page with the issue?
 
https://blog.golang.org/feed.atom
 
### What is your user agent?
 
curl

### Screenshot
 
N/A

### What did you do?
 
```
# curl -v https://blog.golang.org/feed.atom
*   Trying 2607:f8b0:400b:80c::2011:443...
* Connected to blog.golang.org (2607:f8b0:400b:80c::2011) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=misc-sni.google.com
*  start date: Jul 26 01:54:16 2021 GMT
*  expire date: Oct 18 01:54:15 2021 GMT
*  subjectAltName: host "blog.golang.org" matched cert's "*.golang.org"
*  issuer: C=US; O=Google Trust Services; CN=GTS CA 1O1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5613c310a560)
> GET /feed.atom HTTP/2
> Host: blog.golang.org
> user-agent: curl/7.74.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 302
< content-type: text/html; charset=utf-8
< location: https://golang.google.cn/feed.atom
< x-cloud-trace-context: 4234c1a044db68dc8c6987ad8c463075
< date: Sun, 22 Aug 2021 19:17:02 GMT
< server: Google Frontend
< content-length: 57
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
<
<a href="https://golang.google.cn/feed.atom">Found</a>.

* Connection #0 to host blog.golang.org left intact
```

### What did you expect to see?
 
```
# curl -v https://blog.golang.org/feed.atom
*   Trying 2a00:1450:400e:802::2011:443...
* TCP_NODELAY set
* Connected to blog.golang.org (2a00:1450:400e:802::2011) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=misc-sni.google.com
*  start date: Jul 26 01:54:16 2021 GMT
*  expire date: Oct 18 01:54:15 2021 GMT
*  subjectAltName: host "blog.golang.org" matched cert's "*.golang.org"
*  issuer: C=US; O=Google Trust Services; CN=GTS CA 1O1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5600bb86f860)
> GET /feed.atom HTTP/2
> Host: blog.golang.org
> user-agent: curl/7.68.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 301
< content-type: text/html; charset=utf-8
< location: https://go.dev/blog/feed.atom
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-cloud-trace-context: 7d929a66861ebdf27a7c0b4fd80485f2
< date: Sun, 22 Aug 2021 19:19:14 GMT
< server: Google Frontend
< content-length: 64
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
<
<a href="https://go.dev/blog/feed.atom">Moved Permanently</a>.

* Connection #0 to host blog.golang.org left intact
``` 
 
### What did you see instead?

Fetching the RSS feed `https://blog.golang.org/feed.atom` from a [Linode VM](https://www.linode.com/) redirects to `https://golang.google.cn/feed.atom` instead of `https://go.dev/blog/feed.atom`.

Do the same operation from a different location, for example Digital Ocean or a Home connection, and you will be redirected to the correct location.

`https://golang.google.cn/feed.atom` returns a 404 Page Not Found.

**Comment by seankhliao** [comment] 2021-08-23 11:11
Duplicate of #47808

**Closed by seankhliao** 2021-08-23 11:11 UTC
