### ISSUE TITLE
golang/fmt: `Println` do not align line head when using raw mode

### ISSUE THREAD

**Issue by zyxkad** [golang/go#50761] opened 2022-01-22 22:41 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)? _(That's not matter)_

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
```golang
package main
import (
  "os"
  "fmt"
  terminal "golang.org/x/crypto/ssh/terminal"
)
func main(){
  fmt.Fprintln(os.Stdout, "hello")
  fmt.Fprintln(os.Stdout, "world")
  terminal.MakeRaw((int)(os.Stdin.Fd()))
  fmt.Fprintln(os.Stdout, "hello")
  fmt.Fprintln(os.Stdout, "world")
}
```

### What did you expect to see?
```
$ go run main.go
hello
world
hello
world
$
```

### What did you see instead?
```
$ go run main.go
hello
world
hello
     world
          $
```

**Comment by zyxkad** [comment] 2022-01-22 22:43
I can use
```golang
fmt.Fprintf(os.Stdout, "%s\r\n", "hello")
fmt.Fprintf(os.Stdout, "%s\r\n", "world")
```
to replace it, but that work's hard, isn't?

**Comment by davecheney** [comment] 2022-01-22 22:56
When a terminal is placed in raw mode all line ending processing is disabled; fmt.Println appends a \n new line character to the end of its output. As you see, the output continues on a new line, the “paper” the tty is printing on was moved up one line. To move the “carriage”, the print head of to the start of the line, \r carriage return is needed. Normally these are handled by the tty driver in the default “cooked” mode.

This is not a bug in Go. Closed as working as intended.

**Closed by davecheney** 2022-01-22 22:56 UTC

**Comment by zyxkad** [comment] 2022-01-23 00:27
> When a terminal is placed in raw mode all line ending processing is disabled; fmt.Println appends a \n new line character to the end of its output. As you see, the output continues on a new line, the “paper” the tty is printing on was moved up one line. To move the “carriage”, the print head of to the start of the line, \r carriage return is needed. Normally these are handled by the tty driver in the default “cooked” mode.
> 
> This is not a bug in Go. Closed as working as intended.

Sorry, I can't make any sense about why you _(or another coder)_ just put LF(\n), and don't put CR(\r)?
```golang
func Println(objs ...interface{}){
	str := fmt.Sprintln(objs...)
	if len(str) > 0 && str[len(str) - 1] == '\n' {
		if len(str) > 1 && str[len(str) - 2] == '\r' {
			io.WriteString(os.Stdout, str)
			return
		}
		io.WriteString(os.Stdout, str[:len(str) - 1])
	}
	os.Stdout.Write(crlf)
}
```
That's my solution now, It's not too long but I'd like to use standard library

**Comment by davecheney** [comment] 2022-01-23 01:34
> Sorry, I can't make any sense about why you (or another coder) just put LF(\n), and don't put CR(\r)?

because the TTY driver knows to convert it to \r\n. When you shift to raw mode, that logic is disabled.
