### ISSUE TITLE
x/text: case folding differs from ICU

### ISSUE THREAD

**Issue by BrannonKing** [golang/go#47755] opened 2021-08-17 17:46 UTC
### What version of Go are you using (`go version`)?
1.16.6

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using?
linux/amd64

### What did you do?

Given this string: "Ꮖ-Ꮩ-Ꭺ-Ꮹ-Ꭼ-Ꮮ", convert it to lower case via `x/text/cases.Fold().Bytes(...)`. This produces a valid but unexpected result (and many common fonts don't contain characters for the output).

### What did you expect to see?

I expected the characters to go through unchanged. That's because x/text/cases claims to comply with Unicode version 13. ICU (I tested v63.2 and v66.1), which include Unicode 13 and below, leave the text unchanged when passed to ICU's `u_strFoldCase`.

**Comment by seankhliao** [comment] 2021-08-17 17:58
Duplicate of #46101

**Closed by seankhliao** 2021-08-17 17:58 UTC
