### ISSUE TITLE
cmd/gofmt new, bad behavior, removes pre-function whitespace readability comment line in 1.19.3

### ISSUE THREAD

**Issue by glycerine** [golang/go#57388] opened 2022-12-18 21:28 UTC
go version go1.19.3 linux/amd64

For the first time I find myself fighting with gofmt, in go version 1.19.3, because there is new, undesirable behavior.

gofmt will now delete my comment lines that I have placed between the func documentation and the actual func
to provide readability improvement by having some whitespace between the comment and the func line.

Please revert to the long established traditional behavior of gofmt that preserved those otherwise empty
comment lines.

example:

~~~
// MyFunc description here, with a following whitespace line to separate dense text.
//
func MyFunc(a, b, c, d string, int etc) {
~~~

gofmt used to leave this, quite properly, alone. But now it removes that line with only //, leaving:

~~~
// MyFunc description here, with a following whitespace line to separate dense text.
func MyFunc(a, b, c, d string, int etc)  {
~~~

which causes my eyes to bug-out when trying to read the function description. I will try
to put the comment back in, but gofmt in 1.19.3 always, nastily, removes it again. I will
revert to an earlier gofmt until this is repaired.

This also has the undesirable side effect of causing alot of capricious comment code changes when gofmt
is run on large directories of go code, causing spurious source code control changes.

**Comment by seankhliao** [comment] 2022-12-18 21:44
Duplicate of #54489

**Closed by seankhliao** 2022-12-18 21:44 UTC
