### ISSUE TITLE
cmd/vet: detect bad types for calls to sort.Slice

### ISSUE THREAD

**Issue by campoy** [golang/go#17923] opened 2016-11-15 04:53 UTC
### What version of Go are you using (`go version`)?
go version devel +866e014 Fri Nov 11 17:07:07 2016 +0000 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?

Given this program:

```go
func main() {
	m := map[string]bool{}
	sort.Slice(m, func(i, j int) bool { return a[i] < a[j] })
}
```

### What did you expect to see?

I'd expect go vet to complain about the type of m not being a slice in the call to sort.Slice.

### What did you see instead?

Panic

**Comment by mvdan** [comment] 2016-11-15 09:53
What panics? Vet or the execution of the program? If it's the latter, maybe a better error would suffice.

**Comment by bradfitz** [comment] 2016-11-15 14:27
sort.Slice panics, as documented.

**Comment by campoy** [comment] 2016-11-15 17:11
Yes, sort.Slice panics, and I think this is a good candidate to be reported by vet.

It's a very simple check, already wrote the code, and there's 0 chance of false positives.

**Comment by robpike** [comment] 2016-11-15 18:06
I don't want to set up a tradition where everything that might panic gets a vet check. That's dangerous.

Also, this feature hasn't even been released yet, which means the 'frequency' metric is unknown now. So it's not going into vet, at least not yet.

**Comment by bradfitz** [comment] 2016-11-15 18:19
> I don't want to set up a tradition where everything that might panic gets a vet check. That's dangerous.

This *will* panic, not *might*.

Why's it dangerous?

**Comment by robpike** [comment] 2016-11-15 21:01
It's a dangerous precedent because vet is being used more and more and if it's going to take on the every possible failure, it may become too expensive to run, or at least require rearchitecture.

Besides, I'm not convinced it should assume the role of catching things that are guaranteed to fail the first time you run the program.

The frequency question still exists. At the moment the problem is purely hypothetical and, I think, unimportant.

**Comment by bradfitz** [comment] 2016-11-15 21:50
So the frequency question is mostly about vet performance? I've never measured it.

**Comment by minux** [comment] 2016-11-15 22:28
I'm more worried about another variant of the 2nd case where the compare
function doesn't close over the slice argument, as this might be a common
kind of copy-paste errors.

**Comment by campoy** [comment] 2016-11-16 06:46
That'd be an interesting check and I'm happy to implement it too.

But after the conversation with @robpike I think it's better to wait to see if people really make those mistakes before adding extra checks.

**Comment by quentinmit** [comment] 2016-11-16 18:38
I'm going to close this for now. We can reopen it (or refile it) if it turns out this is a common mistake.

**Closed by quentinmit** 2016-11-16 18:38 UTC
