### ISSUE TITLE
interface with multiple struct

### ISSUE THREAD

**Issue by tgg-manish** [golang/go#25900] opened 2018-06-15 07:00 UTC
Hi Gophers 

how can i use interface with diffrent-diffrent strcut?
I just want to use interface like struct with field name.So can we use interface as dynamic struct type.
i was used ff := getdata.(SecondType)  fmt.Println(ff.Address) but it is not dynamic.

  Like 

package main

import (
	"fmt"
)

type FirstType struct {
	Name string
	Email string
}

type SecondType struct {
	Address string
	Points float64
}

func main() {
	UseOfInterface(SecondType{Address: "Raj. india", Points: 4.4})
	UseOfInterface(FirstType{Name: "Manish Jangid", Email: "manish101.mj@gmail.com"})
}

func UseOfInterface(getdata interface{}) {
	?
        ?
        ?
        ?

}

**Comment by agnivade** [comment] 2018-06-15 07:11
Hi @tgg-manish .

This appears to be a question rather than a Go bug. We do not use the issue tracker for general discussions or questions like these. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

You might want to take a look at [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions. Thanks.

Closing since this is not a bug.

**Closed by agnivade** 2018-06-15 07:11 UTC
