### ISSUE TITLE
net/http: finishRequest() fails to clean up files generated after modifying request using context

### ISSUE THREAD

**Issue by 10196** [golang/go#67713] opened 2024-05-30 11:03 UTC
### Go version

go1.20.6

### Output of `go env` in your module/workspace:

```shell
Regardless of env
```

### What did you do?

Before executing net/http Request.ParseMultipartForm(), execute request = request.WithContext(ctx). The temporary file */tmp/multipart-* generated afterwards will not be deleted in response.finishRequest().

### What did you see happen?

The temporary file */tmp/multipart-* will remain and will not be deleted.

### What did you expect to see?

No matter what the order of executing Request.ParseMultipartForm and request = request.WithContext(ctx), finishRequest() can always delete the temporary file: */tmp/multipart-*.

**Comment by 10196** [comment] 2024-05-30 12:24
Of course, I know this problem can be solved, for example:
ctx := r.Context()
req := r.WithContext(ctx)
*r = *req

I am more concerned about the fact that there is no description of this problem in the context comments (maybe there is, but I didn't see it?), and why WithContext can't do this automatically?
The previous example combined with the WithContext source code is
r2 := new(Request)
*r2 = *r
r2.ctx = ctx
req = r2
*r = *req

Why not simplify to
r.ctx = ctx

**Comment by mknyszek** [comment] 2024-06-03 15:08
CC @neild

**Comment by seankhliao** [comment] 2024-06-15 09:58
Duplicate of #58809

**Closed by seankhliao** 2024-06-15 09:58 UTC
Labels: NeedsInvestigation
