### ISSUE TITLE
x/tools/gopls: missing error diagnostics for "missing function body"

### ISSUE THREAD

**Issue by myitcv** [golang/go#64089] opened 2023-11-13 00:06 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.3 linux/arm64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.15.1-0.20231110221557-aafa2e00a0d7
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.15.1-0.20231110221557-aafa2e00a0d7
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/home/myitcv/.cache/go-build'
GOENV='/home/myitcv/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/myitcv/gostuff/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/myitcv/gostuff'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/myitcv/gos'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/myitcv/gos/pkg/tool/linux_arm64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build4285289239=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

```
-- main.go --
package main

func main() {
	println("test")
}

func hello()
```

Open `main.go` in a gopls-powered editor.

### What did you expect to see?

An error diagnostic telling me that `func hello()` is missing a function body. Just like that reported by `go run`:

```
$ go run main.go
# command-line-arguments
./main.go:7:6: missing function body
```

### What did you see instead?

No error diagnostic. 

---

cc @findleyr

**Comment by findleyr** [comment] 2023-11-13 13:46
The current behavior is correct (or rather, it's the best we can do). Per the [spec](https://go.dev/ref/spec#Function_declarations), function bodies are optional in go code. The way I think of it is: it's not an error until you try to link, and with `go:linkname` directives (or other linker interventions) we can't know whether or not that function will be linked correctly.

Put differently, if we did this there would be thousands of errors in the Go standard library, and IIUC we have no practical way of identifying which missing function bodies are missing _by accident_.

By contrast, generic functions and `init` functions do require a function body, and gopls correctly reports an error in these cases.

**Comment by findleyr** [comment] 2023-11-13 23:02
Closing as I don't think we can do anything here. Please correct me if I'm wrong.

**Closed by findleyr** 2023-11-13 23:02 UTC
Labels: NeedsInvestigation, gopls, Tools

**Comment by myitcv** [comment] 2023-11-14 05:41
> The current behavior is correct

For some definition of "correct" 😄 

From the perspective of someone writing a Go program using `gopls`, it is not correct if my goal is to have all errors surfaced in my editor. Because the reality is that I cannot otherwise say "I am done with all the errors in my editor, let me now run my program". Perhaps a good analogy here is the `go:embed` directives: if errors related to these directives were not surfaced by `gopls`, then I feel we would be having the same discussion. But they are so we are not, and from my perspective as a user of `gopls` that is "correct". Just as link errors not being surfaced are not present, hence this issue. 

However, this again comes back to the point of "what am I trying to do with `gopls` in this instance". In the case of this issue, I'm trying to get to a state where I can run the main program. I realise that we don't have a mechanism of support the description of such intentions, but again I wouldn't call this "correct". 

So whilst it might internally be "correct" to not report errors in this situation, I'm not sure I agree that it is "correct" from the perspective of a `gopls` user, where the raison d'être of `gopls` is to help me fix my code.

**Comment by findleyr** [comment] 2023-11-14 16:20
> The current behavior is correct (or rather, it's the best we can do)

You removed the parenthetical :)!  It is "correct" according to the spec, and unfortunate that it's the best we can do.

Absent external configuration (such as a build definition), and a lot of additional logic, I don't think there's a way to address this problem. I'd be happy to hear otherwise.

**Comment by adonovan** [comment] 2023-11-14 18:57
Gopls, by design, executes only modular (package-at-a-time) analyses in real time, analogous to a compiler. By contrast, whole program analyses such as the linker or govulncheck aren't executed in real time because they need additional external information--such as which main package(s) to operate on---which means their diagnostics are not a function of a package and its transitive closure. As you can imagine, this makes them prohibitively expensive to compute in real time. You can of course request whole-program analyses explicitly, for example by running a TestABC function, or invoking govulnheck from your go.mod file.
