### ISSUE TITLE
fmt: Scanf not waiting for input

### ISSUE THREAD

**Issue by PaulIRL** [golang/go#48816] opened 2021-10-06 11:09 UTC
### What operating system and processor architecture are you using (`go env`)?
<pre>
go1.17.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
<pre>
https://play.golang.org/p/TDFYs8OyOMZ

When I try to get input with fmt.Scanf (fmt.Scanf("%g",&numberFloat) and fmt.Scanf("%d", &base)), the first Scanf works on my windows machine but the second doesn't wait for input, in golang playground it doesn't wait for any input
</pre>

### What did you expect to see?
Scanf waiting for input

### What did you see instead?
Scanf being ignored

**Comment by PaulIRL** [comment] 2021-10-06 11:11
It seems go playground didn't get all my code
https://pastebin.com/QDTF2Kus here's code for the base changing function, even though it doesn't really matter I think

**Comment by mknyszek** [comment] 2021-10-06 15:35
Judging by the [documentation](https://pkg.go.dev/fmt#Scanf), and comments in #23562, a workaround is to add a newline, so `fmt.Scanf("%d\n", &myInt)`.

That aside, I think this may be a duplicate of #23562. I encourage you to post there. Closing for now.

**Closed by mknyszek** 2021-10-06 15:35 UTC
Labels: NeedsInvestigation
