### ISSUE TITLE
cmd/go: cannot load <package>, disallowed version string ""

### ISSUE THREAD

**Issue by zikaeroh** [golang/go#32636] opened 2019-06-15 20:00 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +06e34e5 Sat Jun 15 14:23:04 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Not in 1.12.5, yes on tip.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jake/nobackup/gotip_home/cache/go-build"
GOENV="/home/jake/nobackup/gotip_home/config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jake/nobackup/gotip_home/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/jake/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/jake/sdk/gotip/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jake/decbug/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build227879872=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`go.mod`:

```
module decbug

go 1.12
```

`main.go`:

```go
package main

import _ "github.com/ericlagergren/decimal"

func main() {}
```

Run `go build`.

### What did you expect to see?

No errors on building, dependencies populated, etc.

### What did you see instead?

`go build` fails with:

```
go: finding github.com/ericlagergren/decimal latest
go: finding github.com/ericlagergren/decimal 
build decbug: cannot load github.com/ericlagergren/decimal: disallowed version string ""
```

Running `go mod tidy` always outputs:

```
go: finding github.com/ericlagergren/decimal latest
go: finding github.com/ericlagergren/decimal 
```

`go build` in 1.12.5 works fine, along with `mod tidy`, etc.

**Comment by Azareal** [comment] 2019-06-15 22:22
```go get github.com/mailru/easyjson/...: disallowed version string ""```
The same thing seems to happen with `go get github.com/mailru/easyjson/...`

Is this deliberate or an accidental break?

**Comment by zikaeroh** [comment] 2019-06-15 22:42
Bisects to [CL 180337](http://golang.org/cl/180337) (4c2ffd26ec3fe2fb9552b5a38c2b731e86a85abf).

**Comment by mvdan** [comment] 2019-06-16 12:26
I have been encountering the same error in the last couple of days on master. I didn't file an issue because I thought I was doing something silly. Using 1.12.6 let me work around the issue when adding new dependencies.

This probably needs more investigation, but for now I'm adding it as a 1.13 release blocker. CC @jayconrod @bcmills

**Comment by eliasnaur** [comment] 2019-06-17 13:18
FWIW, I had a similar same error message and setting GOPROXY=direct fixed the problem. I didn't investigate why.

**Comment by jayconrod** [comment] 2019-06-17 13:40
Reproduced. Will look into this today.

**Comment by cuonglm** [comment] 2019-06-17 14:20
@jayconrod The problem is the empty `""` `current` param passed to `queryProxy`, which causes `module.EncodeVersion` return error.

**Comment by zikaeroh** [comment] 2019-06-17 22:37
The above CL seems to fix the issue in my projects. Thanks!

**Comment by jayconrod** [comment] 2019-06-18 00:20
@zikaeroh Thanks for verifying, and thanks for reporting the issue. The fix is merged now. Sorry for the break.

**Closed** 2019-06-18 00:19 UTC
Labels: NeedsFix, release-blocker
