### ISSUE TITLE
crypto/aes: linux/arm64 Go 1.9 performance is +20X slower than OpenSSL

### ISSUE THREAD

**Issue by williamweixiao** [golang/go#22808] opened 2017-11-19 12:21 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.2 linux/arm64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="arm64"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_arm64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
go test crypto/cipher -bench GCM

### What did you expect to see?
Performance can be on par with OpenSSL (https://blog.cloudflare.com/content/images/2017/11/sym_key_1_core.png)

### What did you see instead?
+20X slower than OpenSSL( https://blog.cloudflare.com/content/images/2017/11/go_sym_key_1_core.png)

**Comment by as** [comment] 2017-11-20 01:34
```
C:\Users\as>go test crypto/cipher -bench GCM
goos: windows
goarch: amd64
pkg: crypto/cipher
BenchmarkAESGCMSeal1K-4          5000000               314 ns/op        3260.87 MB/s
BenchmarkAESGCMOpen1K-4          5000000               276 ns/op        3705.65 MB/s
BenchmarkAESGCMSeal8K-4          1000000              1732 ns/op        4728.25 MB/s
BenchmarkAESGCMOpen8K-4          1000000              1721 ns/op        4758.42 MB/s
PASS
ok      crypto/cipher   7.189s
```

12.5MBps is exactly 100Mbps. This number seems too round to ignore, any thoughts on why it won't exceed the speed of a "fast ethernet" network interface?

**Comment by williamweixiao** [comment] 2017-11-20 07:27
Following is the result I got from some typical arm64 platform:

go  test crypto/cipher -bench GCM
goos: linux
goarch: arm64
pkg: crypto/cipher
BenchmarkAESGCMSeal1K-32           50000             35735 ns/op          28.65 MB/s
BenchmarkAESGCMOpen1K-32           50000             35858 ns/op          28.56 MB/s
BenchmarkAESGCMSeal8K-32            5000            285102 ns/op          28.73 MB/s
BenchmarkAESGCMOpen8K-32            5000            278226 ns/op          29.44 MB/s
PASS
ok      crypto/cipher   7.199s

**Comment by as** [comment] 2017-11-20 09:31
Taking a second look at the results and seeing arm64 instead of amd64, I realize the reason has already been stated in prior discussions: no assembly implementations for the platform. It's probably safe to disregard my previous inquisition.

**Comment by matt2909** [comment] 2017-11-21 13:03
This looks to be a duplicate of #18498

**Comment by titanous** [comment] 2017-11-21 21:14
Duplicate of #18498. Closing.

**Closed by titanous** 2017-11-21 21:14 UTC
Labels: Performance

**Comment by vielmetti** [comment] 2018-06-26 22:15
On arm64, Packet Type 2A / c1.large.arm Cavium ThunderX:

```
ed@ed-2a-bcc-llvm:~$ go test crypto/cipher -bench GCM

goos: linux
goarch: arm64
pkg: crypto/cipher
BenchmarkAESGCMSeal1K-96           20000             68788 ns/op          14.89 MB/s
BenchmarkAESGCMOpen1K-96           20000             68697 ns/op          14.91 MB/s
BenchmarkAESGCMSign8K-96           10000            182114 ns/op          44.98 MB/s
BenchmarkAESGCMSeal8K-96            3000            536359 ns/op          15.27 MB/s
BenchmarkAESGCMOpen8K-96            3000            537432 ns/op          15.24 MB/s
PASS
ok      crypto/cipher   9.404s
ed@ed-2a-bcc-llvm:~$ 
ed@ed-2a-bcc-llvm:~$ go version
go version go1.10.2 linux/arm64
ed@ed-2a-bcc-llvm:~$ ~/go/bin/go1.11beta1 test crypto/cipher -bench GCM
goos: linux
goarch: arm64
pkg: crypto/cipher
BenchmarkAESGCMSeal1K-96           50000             37520 ns/op          27.29 MB/s
BenchmarkAESGCMOpen1K-96           50000             37550 ns/op          27.27 MB/s
BenchmarkAESGCMSign8K-96           10000            172278 ns/op          47.55 MB/s
BenchmarkAESGCMSeal8K-96            5000            289794 ns/op          28.27 MB/s
BenchmarkAESGCMOpen8K-96            5000            288511 ns/op          28.39 MB/s
PASS
ok      crypto/cipher   9.274s
```

1.11beta1 is substantially faster than 1.10.2.
