### ISSUE TITLE
"go tool compile -S main.go > main.s", main.s is empty

### ISSUE THREAD

**Issue by xujintao** [golang/go#30273] opened 2019-02-17 04:17 UTC
go version: 1.11.5
os: ubuntu 18.04

![image](https://user-images.githubusercontent.com/5418373/52908486-bf348080-32b1-11e9-9e85-9519b0f6e73c.png)

I step this doc and run cmd below:
```bash
go tool compile -S main.go > main.s
```
main.s is empty, and the assembly code being output to terminal, not main.s

i expect the assembly code in main.s not terminal.

**Comment by agnivade** [comment] 2019-02-17 06:16
This seems like a setup issue or something specific to your shell. I am not able to reproduce this. In any case, this does not look like a Go bug because the `>` operator does not have anything to do with Go.

You might want to take a look at the [Questions](https://github.com/golang/go/wiki/Questions) wiki page; you will get better help there.

Closing this as I don't see any bug here.

**Closed by agnivade** 2019-02-17 06:16 UTC
