### ISSUE TITLE
bzip2：Add bzip2 encoding implementation

### ISSUE THREAD

**Issue by QiangHeisenberg** [golang/go#40420] opened 2020-07-27 03:58 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?
I am very interested in the field of data compression. I recently read the Go compression library source code. I think this library can have better performance. So, I have submitted some CLs: https://go-review.googlesource.com/q/owner:lziqiang1%2540gmail.com.

In addition, I found that there is no coding implementation of bzip2 in this library. #4828, #58
In my communication with @dsnet, I found that the encoding algorithm requires a very complicated implementation and takes a lot of time.

Dear senior @dsnet, he has written a very good implementation, but he seems to be not satisfied: https://github.com/dsnet/compress/tree/master/bzip2

I have some time to do this job now. I have a few questions that I want to get your confirmation:
1. Accept this change now?
2. If I want to advance this coding integration work, should I submit CL directly or submit a PR to the respected predecessor @dsnet's github?
3. There seems to be a lack of a reliable reviewer. Has this problem been solved? # 58
4. If I want to add this encoding algorithm, how can I do it?

I would be happy to discuss more details with you. If possible, I will spend time trying to help you make the compression library better in the near future. @dsnet，@mdempsky

**Comment by mdempsky** [comment] 2020-07-27 04:36
Probably best to follow-up on #4828 and ask (1) whether there's still interest in having a bzip2 compressor in the standard library, and (2) what's still needed from dsnet/compress to fulfill that interest.

As @dsnet commented on one of the issues, I don't know anything about BWT. If you're familiar with this and bzip2, I think one of the best things you could do is to review the code, report any issues you find (if any), and then offer an overall assessment on #4828.

(I'm going to close this issue because I think it's a duplicate of #4828 and in favor of following up further there.)

**Closed by mdempsky** 2020-07-27 04:36 UTC

**Comment by QiangHeisenberg** [comment] 2020-07-27 05:05
Thank you for your reply and help.
