### ISSUE TITLE
x/pkgsite: Unable to view documentation for specific version of forked module

### ISSUE THREAD

**Issue by sudo-suhas** [golang/go#44958] opened 2021-03-12 07:30 UTC
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/gojek/work@v0.6.0 
 
### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:86.0) Gecko/20100101 Firefox/86.0
  
### Screenshot
 
![image](https://user-images.githubusercontent.com/22251956/110908420-cc0eeb80-8334-11eb-95b3-8bd373562168.png)
 
### What did you do?
 
Tried to open https://pkg.go.dev/github.com/gojek/work@v0.6.0 
 
### What did you expect to see?
 
I expected to see the updated documentation for this fork which has some additional changes. Relevant tag/release - https://github.com/gojek/work/releases/tag/v0.6.0.
 
### What did you see instead?

I was redirected to the documentation of the original source module.

**Comment by mvdan** [comment] 2021-03-12 08:21
https://github.com/gojek/work/blob/master/go.mod still points to `module github.com/gocraft/work`. If you want to do releases in your fork, you need to actually use a different module path.

Closing as working as intended. See https://golang.org/wiki/Questions.

**Closed by mvdan** 2021-03-12 08:21 UTC
Labels: pkgsite

**Comment by sudo-suhas** [comment] 2021-03-13 10:49
We use a `replace` directive to use this fork instead of the original module. And in order to pick up the latest version, a tag/release is needed on the forked module. Please correct me if I am wrong regarding any of this.

Additionally, I _can_ view the documentation for the fork but it is for the older version - https://pkg.go.dev/github.com/gojek/work.

If I need to create a tag for using a `replace` directive, it would have been good to be able to view docs for the same.
