### ISSUE TITLE
x/dashboard: request for updated C compilers on windows builders

### ISSUE THREAD

**Issue by thanm** [golang/go#43195] opened 2020-12-15 16:12 UTC
While working on issue #39326, I noticed that the C compilers we have installed on our windows builders (at least the ones I have used via gomote) are pretty ancient -- GCC 5.

It would be great if we could update the version to something a bit more recent (V10 maybe). Also worth noting that many folks are now using clang instead of gcc on windows -- it would be very helpful if our windows builders had clang installed as well.

**Comment by thanm** [comment] 2020-12-15 16:12
@golang/release

**Comment by ALTree** [comment] 2020-12-15 17:59
This is #35006.

I've been using the toolchain recommended in https://github.com/golang/go/issues/35006#issuecomment-545363716 and it works much better than mingw. It's also completely static and requires no installation.

**Comment by thanm** [comment] 2020-12-15 18:12
@ALTree thanks, that's helpful.   I'll maybe try the musl.cc copy and see if I can make progress with that.

**Comment by thanm** [comment] 2020-12-17 19:12
The toolchain from musl.cc helped a lot -- I was able to develop a fix for my lld bug using that. 

I tried running all.bash on a windows gomote with the musl.cc toolchain (overriding the default gomote toolchain). There were a couple of failures of the form

```
    nm_test.go:121: building test executable failed: exit status 2 # command-line-arguments
        c:/workdir/x86_64-w64-mingw32-native/bin/../lib/gcc/x86_64-w64-mingw32/9.3.1/../../../libmsvcrt.a(/2203): duplicate symbol reference: _unlock_file in both libgcc(.text) and libgcc(.data)
        libgcc(.text): relocation target ___chkstk_ms not defined
        libgcc(.text): relocation target atexit not defined
```

This is with internal linking.  Might be worth poking at those to see if they can be worked around, since other than that it looked good to me.

**Comment by bcmills** [comment] 2022-01-26 16:45
Duplicate of #35006

**Closed by bcmills** 2022-01-26 16:45 UTC
Labels: OS-Windows, Builders, NeedsInvestigation, FeatureRequest
