### ISSUE TITLE
x/pkgsite: go get golang.org/x/pkgsite fails when run from pkgsite root folder 

### ISSUE THREAD

**Issue by jofowler** [golang/go#66702] opened 2024-04-05 18:10 UTC
### What is the URL of the page with the issue?
N/A
 
### What is your user agent?
 N/A
  
### Screenshot
 
![Capture](https://github.com/golang/go/assets/26769714/114b427f-73ac-490e-8947-fa9a518f3ca8)

### What did you do?
Git Cloned pkgsite and tried to use go get to get its dependencies

git clone git@github.com:golang/pkgsite.git ; \
cd pkgsite ; \
pwd ; \
GOPROXY=proxy.golang.org go get golang.org/x/pkgsite ; \
GOPROXY=goproxy.unx.sas.com go get golang.org/x/pkgsite

 

I ran these commands:

git clone git@github.com:golang/pkgsite.git ; \
cd pkgsite ; \
pwd ; \
GOPROXY=proxy.golang.org go get golang.org/x/pkgsite ; \
GOPROXY=goproxy.unx.sas.com go get golang.org/x/pkgsite
  
### What did you expect to see?

I expected pkgsite dependencies to be download to the Go cache.
I tried the default GOPROXY and our company's internal GOPROXY. Both failed.
I have no issues downloading dependencies for other projects.
I can successfully run this 'go get' command from subdirs other than pkgsite as long as they have a go.mod
  
### What did you see instead?
Cloning into 'pkgsite'...
remote: Enumerating objects: 43998, done.
remote: Counting objects: 100% (1707/1707), done.
remote: Compressing objects: 100% (195/195), done.
remote: Total 43998 (delta 1601), reused 1528 (delta 1512), pack-reused 42291
Receiving objects: 100% (43998/43998), 335.00 MiB | 32.82 MiB/s, done.
Resolving deltas: 100% (27755/27755), done.
/home/jafowl/pkgsite
go: golang.org/x/pkgsite: module golang.org/x: reading https://proxy.golang.org/golang.org/x/@v/list: 404 Not Found
        server response: not found: golang.org/x is a known non-module
go: golang.org/x/pkgsite: module golang.org/x: reading https://goproxy.unx.sas.com/golang.org/x/@v/list: 404 Not Found

I know that it is not entirely necessary to do this normally, but the debugger that I use, GoLand insists on doing
a 'go get' on the main module whenever it debugs a project. This fails, so I cannot run the debugger.

**Comment by seankhliao** [comment] 2024-04-05 19:42
`go env` output please

**Comment by jofowler** [comment] 2024-04-05 21:36
My go env output:

jafowl@SAS-PF4SM5YD:~/pkgsite (master) $ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/jafowl/.cache/go-build'
GOENV='/home/jafowl/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/jafowl/go/pkg/mod'
GONOPROXY=''
GONOSUMDB='*.sas.com,sassoftware.io'
GOOS='linux'
GOPATH='/home/jafowl/go'
GOPRIVATE=''
GOPROXY='proxy.golang.org'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/jafowl/pkgsite/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2924646896=/tmp/go-build -gno-record-gcc-switches'

**Comment by seankhliao** [comment] 2024-04-09 17:03
Duplicate of #37700

**Closed by seankhliao** 2024-04-09 17:03 UTC
Labels: pkgsite
