### ISSUE TITLE
cmd/compile: does not match inferred type

### ISSUE THREAD

**Issue by johejo** [golang/go#60460] opened 2023-05-26 15:51 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-f89d575d9e Fri May 26 13:43:41 2023 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

No, tip only.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/mitsuoheijo/.cache/go-build'
GOENV='/home/mitsuoheijo/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/mitsuoheijo/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/mitsuoheijo/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/mitsuoheijo/repos/github.com/golang/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/mitsuoheijo/repos/github.com/golang/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='devel go1.21-f89d575d9e Fri May 26 13:43:41 2023 +0000'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/mitsuoheijo/repos/github.com/johejo/sandbox/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1238354243=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

https://go.dev/play/p/3wuGsYeb_DI

### What did you expect to see?

compile succeeds

### What did you see instead?

```
./prog.go:5:9: type Rules[int] of r does not match inferred type Rules[int] for Rules[T]
./prog.go:7:9: type Rules[string] of r2 does not match inferred type Rules[string] for Rules[T]
./prog.go:21:16: type Rules[T] of s.rules does not match inferred type Rules[T] for Rules[T]
```

Might be related #60377 and https://github.com/golang/go/commit/1dd24d821650a7681c6ee25f0cf99becc93490bd
Same error occurs in https://github.com/zclconf/go-cty with tip.

I couldn't verbalize the title of the issue well. I would appreciate if someone could correct it.

**Comment by ianlancetaylor** [comment] 2023-05-26 16:57
CC @griesemer @findleyr

**Comment by ianlancetaylor** [comment] 2023-05-26 17:00
The test cases compiles and runs with Go 1.20, but not with current HEAD.  It does build with a compiler of a week or two ago.  Also the error messages don't make a great deal of sense.  Marking as a release blocker.

**Comment by griesemer** [comment] 2023-05-26 19:10
Simplified reproducer:
```Go
package p

func _() {
	f(R1{})
	f(R2{})
}

type S[T any] struct {
	rules R[T]
}

func f[T any](rules R[T]) {}

func (s S[T]) _() {
	f(s.rules)
}

type R[T any] interface {
	m(R[T])
}

type R1 struct{}

func (R1) m(R[int]) {}

type R2 struct{}

func (R2) m(R[string]) {}
```
This is related to CL 498315 (submitted yesterday) which addressed issue #60377 (which I believe was a bug).

Thus, I am not convinced that the code here is correct. Will think some more over the next few days.
Reverting CL 498315 will resolve this case, but let's not do it just yet.

**Comment by griesemer** [comment] 2023-05-26 19:14
Reduced to one (representative) error:
```Go
package p

func _() {
	f(R1{})
}

func f[T any](R[T]) {}

type R[T any] interface {
	m(R[T])
}

type R1 struct{}

func (R1) m(R[int]) {}
```

**Comment by griesemer** [comment] 2023-05-26 22:32
Analysis: We're ending up in an end-less recursion because we don't use exact unification when comparing component types (e.g. signature elements in this case).
```
== infer : [T₃](R[T₃]) ➞ [<nil>]
== function parameters: (p.R[T₃])
-- function arguments : [R1{} (value of type p.R1)]
.  p.R[T₃] ≡ p.R1
.  p.R1 ≡ p.R[T₃] (swap)
.  .  p.R1 ≡ interface{m(p.R[T₃])}
.  .  interface{m(p.R[T₃])} ≡ p.R1 (swap)
.  .  .  func(p.R[T₃]) ≡ func(p.R[int])   <<< FIRST OCCURRENCE
.  .  .  .  (p.R[T₃]) ≡ (p.R[int])
.  .  .  .  .  p.R[T₃] ≡ p.R[int]
.  .  .  .  .  p.R[int] ≡ p.R[T₃] (swap)
.  .  .  .  .  .  interface{m(p.R[int])} ≡ interface{m(p.R[T₃])}
.  .  .  .  .  .  .  func(p.R[int]) ≡ func(p.R[T₃])
.  .  .  .  .  .  .  .  (p.R[int]) ≡ (p.R[T₃])
.  .  .  .  .  .  .  .  .  p.R[int] ≡ p.R[T₃]
.  .  .  .  .  .  .  .  .  p.R[T₃] ≡ p.R[int] (swap)
.  .  .  .  .  .  .  .  .  .  interface{m(p.R[T₃])} ≡ interface{m(p.R[int])}
.  .  .  .  .  .  .  .  .  .  .  func(p.R[T₃]) ≡ func(p.R[int])   <<< SEEN ABOVE
```
It would be good to fix the underlying problem here rather than roll back CL 498315.

**Closed** 2023-05-30 20:21 UTC
Labels: NeedsFix, release-blocker, compiler/runtime
