### ISSUE TITLE
go get: returns a 410 Gone for a newly tagged git revision

### ISSUE THREAD

**Issue by kylelemons** [golang/go#47428] opened 2021-07-27 23:04 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
unknown, can't reproduce after clearing module cache

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/kyle.lemons/dev/bin"
GOCACHE="/Users/kyle.lemons/Library/Caches/go-build"
GOENV="/Users/kyle.lemons/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/kyle.lemons/go/pkg/mod"
GONOPROXY="<redacted>"
GONOSUMDB="<redacted>"
GOOS="darwin"
GOPATH="/Users/kyle.lemons/go"
GOPRIVATE="<redacted>"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yv/qqdb78hn4_56y867w_grbwcr0000gp/T/go-build2427558753=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.16.5 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.16.5
uname -v: Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1323
lldb --version: lldb-1200.0.44.2
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
</pre></details>

### What did you do?

Our git repository had some old version tags lying around due to the repository being initially cloned from another; most of these tags don't actually appear in the upstream, but they apparently existed long enough to be indexed:

```
❯ go list -m --versions github.com/reddit/edgecontext
github.com/reddit/edgecontext v0.1.0 v0.1.1 v0.2.0 v0.3.0 v0.4.0 v0.5.0 v0.6.0 v0.7.0 v0.8.0 v0.8.1 v0.9.0 v0.10.0 v0.11.0 v0.11.1 v0.12.0 v0.13.0 v0.14.0 v0.14.1 v0.14.2 v0.14.3 v0.15.0 v0.16.0 v0.16.1 v0.16.2 v0.17.0 v0.17.1 v0.18.0 v0.19.0 v0.21.0 v0.22.0 v0.23.0 v0.23.1 v0.23.2 v0.24.0 v0.24.1 v0.25.0 v0.26.0 v0.27.0 v0.27.1 v0.28.1 v0.28.2 v0.28.3 v0.28.4 v0.28.5 v0.28.6 v0.28.7 v0.29.0 v0.30.0 v0.30.1 v0.30.2 v0.30.3 v0.30.4 v0.30.5 v0.30.6 v0.30.7 v0.30.8 v1.0.0 v1.0.1 v1.0.2 v1.1.0 v1.2.0 v1.2.1 v1.2.2 v1.2.3 v1.2.4 v1.3.0 v1.3.1 v1.3.2 v1.3.3 v1.3.4 v1.3.5 v1.4.0 v1.5.0
```

So, we tagged a new version `v1.6.0`.  Then, I went to fetch it:

```
2021-07-27 15:28:03
❯ cd /tmp
❯ mkdir go
❯ cd go
❯ go mod init test
go: creating new go.mod: module test
❯ go get github.com/reddit/edgecontext@latest
go get: added github.com/reddit/edgecontext v1.5.0
```

Hmm, that's strange.

```
❯ go get github.com/reddit/edgecontext@latest
❯ go get github.com/reddit/edgecontext@v1.6.0
go: downloading github.com/reddit/edgecontext v1.6.0
go get: github.com/reddit/edgecontext@v1.6.0: verifying module: github.com/reddit/edgecontext@v1.6.0: reading https://sum.golang.org/lookup/github.com/reddit/edgecontext@v1.6.0: 410 Gone
	server response: not found: github.com/reddit/edgecontext@v1.6.0: invalid version: unknown revision v1.6.0
❯ GOPROXY=direct go get github.com/reddit/edgecontext@v1.6.0
go: downloading github.com/reddit/edgecontext v1.6.0
go get: github.com/reddit/edgecontext@v1.6.0: verifying module: github.com/reddit/edgecontext@v1.6.0: reading https://sum.golang.org/lookup/github.com/reddit/edgecontext@v1.6.0: 410 Gone
	server response: not found: github.com/reddit/edgecontext@v1.6.0: invalid version: unknown revision v1.6.0
```

At this point I got stuck in this state for quite awhile.  Pulling from direct still runs into the same error.  It looks like the version is present in my module cache, but the checksum didn't make its way to the sumdb:

```
❯ GOPROXY=direct go get -x github.com/reddit/edgecontext@v1.6.0
go: downloading github.com/reddit/edgecontext v1.6.0
mkdir -p /Users/kyle.lemons/go/pkg/mod/cache/vcs # git3 https://github.com/reddit/edgecontext
# lock /Users/kyle.lemons/go/pkg/mod/cache/vcs/5cbb3105c669a3d568e2eb29d58dd149e8fd3d18101345692787b66fc2e3639b.lock# /Users/kyle.lemons/go/pkg/mod/cache/vcs/5cbb3105c669a3d568e2eb29d58dd149e8fd3d18101345692787b66fc2e3639b for git3 https://github.com/reddit/edgecontext
cd /Users/kyle.lemons/go/pkg/mod/cache/vcs/5cbb3105c669a3d568e2eb29d58dd149e8fd3d18101345692787b66fc2e3639b; git tag -l
0.014s # cd /Users/kyle.lemons/go/pkg/mod/cache/vcs/5cbb3105c669a3d568e2eb29d58dd149e8fd3d18101345692787b66fc2e3639b; git tag -l
cd /Users/kyle.lemons/go/pkg/mod/cache/vcs/5cbb3105c669a3d568e2eb29d58dd149e8fd3d18101345692787b66fc2e3639b; git -c log.showsignature=false log -n1 '--format=format:%H %ct %D' refs/tags/v1.6.0 --
0.014s # cd /Users/kyle.lemons/go/pkg/mod/cache/vcs/5cbb3105c669a3d568e2eb29d58dd149e8fd3d18101345692787b66fc2e3639b; git -c log.showsignature=false log -n1 '--format=format:%H %ct %D' refs/tags/v1.6.0 --
cd /Users/kyle.lemons/go/pkg/mod/cache/vcs/5cbb3105c669a3d568e2eb29d58dd149e8fd3d18101345692787b66fc2e3639b; git cat-file blob 42f4ee3d3e330ff70653a99a8ef5e69e88934ed6:go.mod
0.013s # cd /Users/kyle.lemons/go/pkg/mod/cache/vcs/5cbb3105c669a3d568e2eb29d58dd149e8fd3d18101345692787b66fc2e3639b; git cat-file blob 42f4ee3d3e330ff70653a99a8ef5e69e88934ed6:go.mod
cd /Users/kyle.lemons/go/pkg/mod/cache/vcs/5cbb3105c669a3d568e2eb29d58dd149e8fd3d18101345692787b66fc2e3639b; git -c core.autocrlf=input -c core.eol=lf archive --format=zip --prefix=prefix/ 42f4ee3d3e330ff70653a99a8ef5e69e88934ed6
0.026s # cd /Users/kyle.lemons/go/pkg/mod/cache/vcs/5cbb3105c669a3d568e2eb29d58dd149e8fd3d18101345692787b66fc2e3639b; git -c core.autocrlf=input -c core.eol=lf archive --format=zip --prefix=prefix/ 42f4ee3d3e330ff70653a99a8ef5e69e88934ed6
# get https://sum.golang.org/lookup/github.com/reddit/edgecontext@v1.6.0
# get https://sum.golang.org/lookup/github.com/reddit/edgecontext@v1.6.0: 410 Gone (0.362s)
go get: github.com/reddit/edgecontext@v1.6.0: verifying module: github.com/reddit/edgecontext@v1.6.0: reading https://sum.golang.org/lookup/github.com/reddit/edgecontext@v1.6.0: 410 Gone
	server response: not found: github.com/reddit/edgecontext@v1.6.0: invalid version: unknown revision v1.6.0
```

I eventually was able to get it to work, but I had to blow away my module cache:

```
2021-07-27 15:45:45
❯ go clean -modcache

2021-07-27 15:46:51 [command took 56s]
❯ GOPROXY=https://proxy.golang.org go get github.com/reddit/edgecontext@v1.6.0
go: downloading github.com/reddit/edgecontext v1.6.0
go get: upgraded github.com/reddit/edgecontext v1.5.0 => v1.6.0
```

I don't know if it was the minute it took for the modcache to clear or if it took some extra time for the checksum to make it to the module database.

### What did you expect to see?

Pulling a new version through the module cache should not cause errors from the sumdb.

### What did you see instead?

Had to clear module cache (or wait a few minutes) before sumdb would stop reporting "410 Gone".

**Comment by mvdan** [comment] 2021-07-28 08:39
I think you're experiencing https://github.com/golang/go/issues/42809 :)

**Comment by seankhliao** [comment] 2021-07-28 09:32
Duplicate of #42809

**Closed by seankhliao** 2021-07-28 09:32 UTC
