### ISSUE TITLE
./all.bash Fails on ppc64 with CGO_ENABLED=1

### ISSUE THREAD

**Issue by cordong2956** [golang/go#16675] opened 2016-08-11 20:43 UTC
1. What version of Go are you using (`go version`)?

Go Version 1.6.3

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="ppc64"
GOBIN=""
GOEXE=""
GOHOSTARCH="ppc64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/lxd/.gopath"
GORACE=""
GOROOT="/tmp/go-linux-ppc64-bootstrap"
GOTOOLDIR="/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build096935069=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
The goal is to build "Go" on the ppc64 embedded target.

1.) I created a go-linux-ppc64-bootstrap
2.) Scp this on the target to build the Go 1.6.3 tar with "./all.bash

4. What did you expect to see?
I expect this to generate a Go binary within /bin

5. What did you see instead?

I see the following errors:

# cmd/trace
/tmp/go/pkg/tool/linux_ppc64/link: /tmp/go/pkg/linux_ppc64/net.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go/pkg/tool/linux_ppc64/link: /tmp/go/pkg/linux_ppc64/runtime/cgo.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/tool/linux_ppc64/link: too many errors
# cmd/pprof
/tmp/go/pkg/tool/linux_ppc64/link: /tmp/go/pkg/linux_ppc64/net.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go/pkg/tool/linux_ppc64/link: /tmp/go/pkg/linux_ppc64/runtime/cgo.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/tool/linux_ppc64/link: too many errors
# cmd/go
/tmp/go/pkg/tool/linux_ppc64/link: /tmp/go/pkg/linux_ppc64/net.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go/pkg/tool/linux_ppc64/link: /tmp/go/pkg/linux_ppc64/runtime/cgo.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/linux_ppc64/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go/pkg/tool/linux_ppc64/link: too many errors

**Comment by mundaym** [comment] 2016-08-12 22:57
This looks like a duplicate of #13192. Judging from that issue cgo isn't working on ppc64 (big endian) yet unfortunately.

**Closed** 2016-08-12 22:58 UTC
