### ISSUE TITLE
cmd/go: generate silently succeeds on non-existent package

### ISSUE THREAD

**Issue by adonovan** [golang/go#61804] opened 2023-08-07 10:06 UTC
I understand that go generate tries to be robust against many kinds of errors since it is often invoked on a project that won't build, but I don't think it should silently succeed when given the name of a nonexistent package:

```
$ go help generate
...
Generate processes packages in the order given on the command line, one at a time...
For more about specifying packages, see 'go help packages'.

$ go generate ./nonesuch; echo $?
0
```

**Comment by mvdan** [comment] 2023-08-07 14:44
Sounds like a duplicate of https://github.com/golang/go/issues/60079 :) At least I wasn't the only one being puzzled by this for a few minutes.

**Closed by mvdan** 2023-08-07 14:44 UTC
