### ISSUE TITLE
encoding/json: marshal cannot use full-width parentheses in field tags

### ISSUE THREAD

**Issue by shcabin** [golang/go#36545] opened 2020-01-14 11:43 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build026099104=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

https://play.golang.org/p/qDw0gbDz9t_8

### What did you expect to see?

{"（）":""}

### What did you see instead?

{"Others":""}

**Comment by mvdan** [comment] 2020-01-15 05:01
Duplicate of https://github.com/golang/go/issues/22518.

**Closed by mvdan** 2020-01-15 05:01 UTC
