### ISSUE TITLE
sync: bad mutex state on RISC-V

### ISSUE THREAD

**Issue by mknyszek** [golang/go#62100] opened 2023-08-17 16:15 UTC
```
#!watchflakes
post <- log ~ `fatal error: sync:.*mutex` && builder == "linux-riscv64-unmatched"
```

2023-07-31 22:18 linux-riscv64-unmatched go@be0e0b06 cmd/go/internal/par.TestWork ([log](https://build.golang.org/log/ad755a514a4b263bd43a08d7f5af91f6bca342e9))
2023-08-01 13:51 linux-riscv64-unmatched go@91387436 cmd/go/internal/par.TestWork ([log](https://build.golang.org/log/32e8c444c05f239b275e8b98d7d3806436b3db44))
2023-08-02 15:24 linux-riscv64-unmatched go@0f1491de cmd/go/internal/par.TestWork ([log](https://build.golang.org/log/77a099a581806259f751e3943a8ebbe9d6c2d6e7))
2023-08-07 23:13 linux-riscv64-unmatched go@3393155a cmd/go/internal/par.TestWork ([log](https://build.golang.org/log/126dc1e574506a6f2473650b13efa2854e274936))

CC @golang/riscv64

**Comment by bcmills** [comment] 2023-08-23 19:37
Duplicate of #62185

**Closed by bcmills** 2023-08-23 19:37 UTC
Labels: help wanted, NeedsInvestigation, arch-riscv, compiler/runtime
