### ISSUE TITLE
x/tools/gopls: no AST for file after adding and removing file

### ISSUE THREAD

**Issue by inliquid** [golang/go#34218] opened 2019-09-10 20:01 UTC
1. VS Code
2. gopls@master
3. Windows

After adding `model/friends.go` and then removing it, I'm getting this error anytime I want to import `model` package:

```
could not import ***/***/***/pkg/data/model (failed to cache file file:///c:/Users/***/***/***/***/***/***/pkg/data/model/friends.go: no AST for file:///c:/Users/***/***/***/***/***/***/pkg/data/model/friends.go: open c:\Users\***\***\***\***\***\***\pkg\data\model\friends.go: The system cannot find the file specified.)
```

**Comment by stamblerre** [comment] 2019-09-10 20:07
Support for watching changed files is still experimental. Can you reproduce this issue if you add the following to your VSCode settings?

```json5
"gopls": {
    "watchFileChanges": true
}
```

**Comment by inliquid** [comment] 2019-09-10 23:15
I added and removed file from the editor, not externally. Do you mean that `gopls` will not recognize even those changes made with the editor?

**Comment by inliquid** [comment] 2019-09-10 23:17
I checked and got same issue with `"watchFileChanges": true`.

**Comment by pdf** [comment] 2019-10-15 20:52
Possibly related #34678

**Comment by stamblerre** [comment] 2019-12-04 01:02
Duplicate of https://github.com/golang/go/issues/31553

**Closed by stamblerre** 2019-12-04 01:02 UTC
Labels: Tools, gopls
