### ISSUE TITLE
runtime: intermittent "failed to create new OS thread" on Windows since 2022-01-24

### ISSUE THREAD

**Issue by bcmills** [golang/go#52572] opened 2022-04-26 16:24 UTC
```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
runtime: failed to create new OS thread (22)
FAIL	golang.org/x/tools/go/packages	25.671s
```

`greplogs --dashboard -md -l -e '(?ms)\Awindows-.*runtime: failed to create new OS thread'`

[2022-04-26T02:30:39-5bb9a5e-17d7983/windows-amd64-race](https://build.golang.org/log/02a9c90eda96750c77e2b30e7791c1c378d452c7)
[2022-03-21T13:26:21-86b02b3-4aa1efe/windows-arm64-11](https://build.golang.org/log/2c8756cd805e5f98d217eb99a7c7c7ed37684d0a)
[2022-02-04T14:02:15-25d2ab2-4afcc9f/windows-arm64-11](https://build.golang.org/log/9668eab0a7df64177fa0f413cad04bb327fd3e8c)
[2022-01-24T16:55:59-f9df4ea/windows-amd64-2008](https://build.golang.org/log/ef6042fc121ad714c6ed9bc83257798d458a6a31)

Curiously, I don't see any of these errors in the logs before 2022-01-24. 🤔

**Comment by bcmills** [comment] 2022-04-26 16:33
Since most of these failures are in `x/tools`, I wouldn't be entirely surprised if this is actual thread-exhaustion due to the tests running with high parallelism and spawning subprocesses that themselves run with high parallelism. (Some of these failures also correlate with `out of memory` errors from the same test run.)

However the “requested the Runtime to terminate it in an usual way" failure mode in particular looks like a Go runtime bug. Since `windows/amd64` is a [first-class port](https://go.dev/wiki/PortingPolicy#first-class-ports), I'm marking this as a release-blocker at least until we can determine whether it is a regression (attn @golang/runtime).

**Comment by prattmic** [comment] 2022-05-23 21:37
I reproduced this 12 times over the weekend on gomotes, interestingly always in package runtime's TestCgoSignalDeadlock:

```
--- FAIL: TestCgoSignalDeadlock (44.53s)
    crash_test.go:124: running go build -o C:\Users\gopher\AppData\Local\Temp\1\go-build3458167679\testprogcgo.exe 
    crash_cgo_test.go:37: expected "OK\n", but got:
        OK
        
        This application has requested the Runtime to terminate it in an unusual way.
        Please contact the application's support team for more information.
        runtime: failed to create new OS thread (13)
FAIL
FAIL    runtime 418.665s
```

**Comment by prattmic** [comment] 2022-05-23 21:40
I should add that most, but not all, failures include the "This application has requested ..." message, and that none of the failures include any other resource or other test failures in the same run.

**Comment by prattmic** [comment] 2022-05-23 21:56
The tests did seem to take abnormally long to run. That said, the first run (which passed) on a new gomote took 12s to complete (mostly spent building the test binary), so these aren't _that_ far off.

```
--- FAIL: TestCgoSignalDeadlock (4.41s)
--- FAIL: TestCgoSignalDeadlock (23.29s)
--- FAIL: TestCgoSignalDeadlock (26.25s)
--- FAIL: TestCgoSignalDeadlock (41.33s)
--- FAIL: TestCgoSignalDeadlock (43.05s)
--- FAIL: TestCgoSignalDeadlock (35.08s)
--- FAIL: TestCgoSignalDeadlock (27.79s)
--- FAIL: TestCgoSignalDeadlock (21.33s)
--- FAIL: TestCgoSignalDeadlock (37.15s)
--- FAIL: TestCgoSignalDeadlock (36.62s)
--- FAIL: TestCgoSignalDeadlock (5.74s)
--- FAIL: TestCgoSignalDeadlock (44.53s)
```

**Comment by prattmic** [comment] 2022-05-24 14:11
Ah, well the "requested the Runtime to terminate it in an usual way" message is not surprising. The runtime message comes from https://cs.opensource.google/go/go/+/master:src/runtime/cgo/gcc_windows_amd64.c;l=31-32. 

Per the [Microsoft docs](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/k089yyh0(v=vs.90)?redirectedfrom=MSDN), "By default, the abort routine prints the message:

"This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.""

I am now more confused why I sometimes _don't_ get the message, and also why the runtime error is printed after the message, given that the docs say "abort does not flush stream buffers or do atexit/_onexit processing."

**Comment by prattmic** [comment] 2022-05-24 14:17
"runtime: failed to create new OS thread (13)" is errno EACCES. [`_beginthread`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/beginthread-beginthreadex?view=msvc-170) "may return EACCES if there are insufficient resources (such as memory)", which fits well with the out-of-memory errors.

**Comment by prattmic** [comment] 2022-05-24 21:27
I haven't, but it is not a bad idea, as `_beginthread` provides a very clear errno for this failure.

That said, while this is the only error in my repros, all of the failures in Bryan's original comment also have other fatal OOMs in the allocator. So while a retry might make thread creation succeed, the program may die anyways due to another OOM.

It seems like the ultimate problem here might end up being test/builder misconfiguration. i.e., we are running too many high-memory tests in parallel and exhausting all memory on the builder.

**Comment by mknyszek** [comment] 2022-05-25 16:51
Since there's a decent chance this is resource exhaustion on the builders I'm not sure this is going to impede users using the beta, so marking as okay-after-beta1.

**Comment by prattmic** [comment] 2022-06-09 18:18
I haven't been able to reproduce this issue with CL 410355, so closing for now, though of course that CL isn't a hard fix so we'll see if this comes back.

**Closed by prattmic** 2022-06-09 18:18 UTC
Labels: OS-Windows, NeedsInvestigation, release-blocker, okay-after-beta1
