### ISSUE TITLE
MacOS x509.SystemCertPool() returns no certificates in the pool starting at 1.18

### ISSUE THREAD

**Issue by cmcniel** [golang/go#56398] opened 2022-10-24 17:52 UTC
A simple test case that works on 1.17.x and earlier but, returns no certificates in the pool starting with 1.18 forward on MacOS.   On versions prior would expect 100+ certificates in the certpool.  

package main

import (
        "crypto/x509"
        "fmt"
        "log"
)

func main() {
        certs, err := x509.SystemCertPool()
        if err != nil {
                log.Fatal(err)
        }
        fmt.Printf("Num System Certs: %d\n", len(certs.Subjects()))
}

**Comment by seankhliao** [comment] 2022-10-24 18:27
it uses the platform verifier instead.
closing as working as intended.

**Closed by seankhliao** 2022-10-24 18:27 UTC
