### ISSUE TITLE
cmd/go: typo in flag causes panic when running a test file in GOROOT/src

### ISSUE THREAD

**Issue by josharian** [golang/go#35176] opened 2019-10-26 03:03 UTC
At tip:

```
$ go test -timeoout=100h fmt
panic: loadPackageData called with empty package path

goroutine 21 [running]:
cmd/go/internal/load.loadPackageData(0x0, 0x0, 0x0, 0x0, 0xc0000240c4, 0x16, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/josh/go/tip/src/cmd/go/internal/load/pkg.go:648 +0x625
cmd/go/internal/load.(*preload).preloadMatches.func1(0xc000068640, 0x0, 0x0)
	/Users/josh/go/tip/src/cmd/go/internal/load/pkg.go:841 +0x80
created by cmd/go/internal/load.(*preload).preloadMatches
	/Users/josh/go/tip/src/cmd/go/internal/load/pkg.go:839 +0x165
```

Note the typo: `timeoout` instead of `timeout`.

cc @bcmills @jayconrod

**Comment by wade-welles** [comment] 2019-10-27 00:04
Just pulled down the newest master and checked and was unable to reproduce, was this already fixed? I wanted to fix it :D 

```
./go test -timeoout=100h fmt
flag provided but not defined: -timeoout
Usage of /tmp/go-build643614696/b001/go.test:
  -flaky
...
```

**Comment by josharian** [comment] 2019-10-27 02:36
On my phone, but I wonder whether you have to be in dir $GOROOT/src to reproduce.

**Comment by mvdan** [comment] 2019-10-27 11:50
I equally cannot reproduce this on `go version devel +0f559941fb Sat Oct 26 15:17:28 2019 +0000 linux/amd64`. I tried inside GOROOT/src and with various GO111MODULE values. I wonder if I missed any piece of the puzzle.

**Comment by josharian** [comment] 2019-10-28 17:34
Sorry about that. I believe to reproduce you need a test file in GOROOT/src, and then run from that dir. Which means this is pretty low priority. Will re-milestone.

**Comment by jayconrod** [comment] 2019-10-28 22:26
Reproduced with the instructions from the last comment.

It looks like `go test -timeoout fmt` is being interpreted as `go test .` with some arguments to pass to the tests, since `-timeoout` is not a flag that `go test` itself recognizes. So it tries to load the package in the current directory, $GOROOT/src.

The bug is that `modload.ImportPaths` is returning an empty string as one of the import paths. Which is *kind of* correct because normally a package path in `std` is its subdirectory under `$GOROOT/src`, and since there is no subdirectory in this case, we get "".

Maybe we should detect and reject this case specifically? It's such a small corner case though.

**Comment by quantonganh** [comment] 2023-11-03 13:57
Has it been fixed?

```
$ go test -timeoout=100h fmt
GOROOT/src is not an importable package
```

**Comment by bcmills** [comment] 2023-11-03 14:01
Yep, looks like this was fixed in https://go.dev/cl/185345 (March 2020). Thanks for checking!

**Closed by bcmills** 2023-11-03 14:01 UTC
Labels: help wanted, NeedsInvestigation
