### ISSUE TITLE
when /etc/nsswitch.conf doesn't exist , Go's DNS work like an unexpect way

### ISSUE THREAD

**Issue by MemorySpring** [golang/go#40920] opened 2020-08-20 05:48 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.8 linux/amd64
but the problem exist in both 1.12 1.13 1.14 ...
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build381088182=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

in remote DNS server 
a.test.com reslove as   10.10.10.10
in /etc/hosts i hava a record
9.9.9.9 a.test.com

golang app will reslove a.test.com as 10.10.10.10 
however  , `ping`  `curl`  `php app` `java app` and so on will resolve a.test.com as 9.9.9.9

### What did you expect to see?

when /etc/nsswitch.conf doesn't exist ，Go's DNS use file first 
in this , golang app should resolve a.test.com as 9.9.9.9

### What did you see instead?

golang app will reslove a.test.com as 10.10.10.10

**Comment by ianlancetaylor** [comment] 2020-08-20 21:47
The GNU/Linux `man nsswitch.conf` is clear, as is the implementation: if there is no `hosts` line in /etc/nsswitch.conf, the default is `"dns [!UNAVAIL=return] files"`.  And that is what the net package implements.

The behavior you are seeing is not due to the net package handling of /etc/nsswitch.conf.  It's due to how the C `getaddrinfo` function works.  The C function calls `inet_aton` and `inet_pton` before checking either DNS or /etc/hosts.  In other words, the C function is not doing a DNS lookup; it's first checking whether it has an IP address.  If that's the behavior you want, call `net.ParseIP`.

I'm going to close this issue because it is not a bug.

**Closed by ianlancetaylor** 2020-08-20 21:47 UTC
