### ISSUE TITLE
cmd/go: add regression test for 'go build' error in module mode when no 'git' binary is available

### ISSUE THREAD

**Issue by horseboxer** [golang/go#28948] opened 2018-11-26 03:32 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/test/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/test/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/scratchpad/hello/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build952622232=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Followed the quick-start example from the Go 1.11 Wiki page.

Link: [https://github.com/golang/go/wiki/Modules#quick-start-example](https://github.com/golang/go/wiki/Modules#quick-start-example)

### What did you expect to see?
It work

### What did you see instead?
Error after running `go build` the first time.
<pre>
build github.com/you/hello: cannot find module for path rsc.io/quote
</pre>

**Comment by bcmills** [comment] 2018-11-27 03:02
CC @thepudds @myitcv

**Comment by thepudds** [comment] 2018-11-27 03:33
Hmm. I just ran through that "Quick Start Example" by copy/pasting from the wiki, and it seemed to work.

Prep by cleaning slate:
```bash
rm -rf /tmp/scratchpad/hello
```

Commands copied from the wiki:
```bash
mkdir -p /tmp/scratchpad/hello
cd /tmp/scratchpad/hello
go mod init github.com/you/hello
cat <<EOF > hello.go
package main

import (
    "fmt"
    "rsc.io/quote"
)

func main() {
    fmt.Println(quote.Hello())
}
EOF

go build 
./hello
```

Output:
```
Hello, world.
```

And here is the resulting `go.mod`:
```
$ cat go.mod

module github.com/you/hello

require rsc.io/quote v1.5.2
```

@horseboxer In addition to the questions @mvdan asked, what do you see if you do `go get -v rsc.io/quote` from within that directory `/tmp/scratchpad/hello`?

**Comment by thepudds** [comment] 2018-12-09 22:50
@horseboxer just wanted to check in to see if you were able to look at this a bit more? (For example, see the immediately prior comment as well as the suggestions from @mvdan).

Note that `go get -v rsc.io/quote` will likely tell you more information than `go build` alone. For example, it can be that `go build` will give a very general error you saw like `cannot find module for path rsc.io/quote` without any additional detail, but then running `go get -v rsc.io/quote` will often give a more specific error (which can be more helpful than the initial error from `go build`).

**Comment by horseboxer** [comment] 2018-12-19 07:56
Turns out freshly installed Ubuntu VMs don't have git installed :-(. Fixed the user-error and it works now. Sorry to waste your time.

**Comment by mvdan** [comment] 2018-12-19 16:48
I think `cmd/go` should give a better error message here. I can reproduce OP's confusing error with a few commands inside a Docker image:

```
$ cat repro.sh
docker run -i golang:1.11.3-alpine <<-SCRIPT
        export GO111MODULE=on
        git version && { echo "git needs to be missing"; exit 1; }
        mkdir /foo && cd /foo
        go mod init test.tld/foo
        go env GOMOD
        cat >f.go <<-FILE
                package main
                import _ "rsc.io/quote"
                func main() {}
        FILE
        go build
SCRIPT
$ sh repro.sh
/bin/sh: git: not found
go: creating new go.mod: module test.tld/foo
/foo/go.mod
build test.tld/foo: cannot find module for path rsc.io/quote
```

@bcmills note that this only happens with a `package main`. With `package foo`, I get:

```
f.go:5:1: unknown import path "rsc.io/quote": git init --bare in /go/pkg/mod/cache/vcs/4db0c9594744360b0eaa452d2ccfbd45b05dffb9810882957d10d69e61e66382: exec: "git": exec
utable file not found in $PATH
```

**Comment by mvdan** [comment] 2018-12-19 17:09
@bcmills for what it's worth, I can't reproduce the issue on `go version devel +9ed9df6ca2 Wed Dec 19 00:13:22 2018 +0000 linux/amd64`, which should be pretty close to the first beta.

Frustratingly enough, there's no 1.12 docker image at the moment, so I can't be 100% sure. But locally, `PATH=/home/mvdan/tip/bin gotip build` gives a good error, while `PATH=/home/mvdan/tip/bin go1.11.3 build` gives the confusing error. So this might be already fixed in master.

**Comment by bcmills** [comment] 2018-12-19 18:53
@mvdan, thanks for investigating in detail!

My results seem to match yours: I don't know why, but this seems to be fixed in 1.12.

```
$ PATH=~/bin go1.11.4 build .
build golang.org/issue/scratch: cannot find module for path rsc.io/quote

$ PATH=~/bin go1.12beta1 build .
build golang.org/issue/scratch: cannot load rsc.io/quote: git init --bare in /tmp/tmp.BJQhURaAuR/_gopath/pkg/mod/cache/vcs/4db0c9594744360b0eaa452d2ccfbd45b05dffb9810882957d10d69e61e66382: exec: "git": executable file not found in $PATH
```

**Comment by mvdan** [comment] 2018-12-19 19:02
@bcmills perhaps we should add a regression test, particularly since noone seems to know how we fixed this :)

**Comment by bcmills** [comment] 2018-12-19 19:06
A regression test does seem like a good idea.

**Comment by mvdan** [comment] 2018-12-19 19:31
I can submit my reproducer above as a test script by tomorrow.

**Closed** 2018-12-22 09:38 UTC
Labels: GoCommand, NeedsFix, Testing, modules
