### ISSUE TITLE
net/textproto: fails when headers contain invalid headers

### ISSUE THREAD

**Issue by kayrus** [golang/go#53855] opened 2022-07-13 20:59 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

See example: https://go.dev/play/p/OLfq5WlWCMf (with a fake UTF colon)

### What did you expect to see?

I expect that `textproto.ReadMIMEHeader` will return parsed headers, skip failed headers and return an error if any along with parsed headers:

```
Read headers: map[Date:[Mon, 23 Jun 2015 11:40:36 -0400] Subject:[Gophers at Gophercon] To:[Another Gopher <to@example.com>]]
```

### What did you see instead?

I see only first parsed header: `Date:[Mon, 23 Jun 2015 11:40:36 -0400]`

Further headers are not parsed.

See also: https://github.com/golang/go/issues/53854

**Comment by seankhliao** [comment] 2022-07-13 21:09
In general it cannot safely skip malformed headers, since the malformation may affect the parsing of subsequent lines.
This is also consistent with the other go standard library functions that return on first error.

Closing as working as intended

**Closed by seankhliao** 2022-07-13 21:09 UTC
