### ISSUE TITLE
all.bash: attempt to create module cache under /dev/null on linux/amd64

### ISSUE THREAD

**Issue by empijei** [golang/go#30776] opened 2019-03-12 15:59 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/clap/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/clap/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/home/clap/go/contrib/go/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build775917262=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Followed steps in contribution guide.

```sh
git clone https://go.googlesource.com/go
cd go/src
./all.bash
```
The commit I'm working on is `6c527aa58355b936fa173828139a3e245a3ddba6`

### What did you expect to see?
Tests to pass

### What did you see instead?
Some failures:
```
--- FAIL: TestHtmlUnformatted (1.18s)
--- FAIL: TestHtmlUnformatted (1.18s)
    cover_test.go:478: running [/home/clap/go/contrib/go/bin/go test -toolexec=/tmp/gotestcover098158935/toolexec.exe /tmp/gotestcover098158935/cover.exe -covermode=count -coverprofile /tmp/gotestcover098158935/htmlunformatted/htmlunformatted.cov]
    cover_test.go:478: go: failed to create cache directory /dev/null/pkg/mod/cache: mkdir /dev/null: not a directory
    cover_test.go:478: exit status 1
FAIL
FAIL    cmd/cover       2.524s
```

```
--- FAIL: TestVexPCrelative (0.03s)
    issue19518_test.go:78: error exit status 1 output go: failed to create cache directory /dev/null/pkg/mod/cache: mkdir /dev/null: not a directory
FAIL
FAIL    cmd/internal/obj/x86    0.057s
```

```
--- FAIL: TestUnresolved (0.02s)
    link_test.go:176: want:
        main.x: relocation target zero not defined
        main.x: relocation target zero not defined
        main.x: relocation target main.zero not defined
        got:
        go: failed to create cache directory /dev/null/pkg/mod/cache: mkdir /dev/null: not a directory
FAIL
FAIL    cmd/link        1.950s
```

Building with `GOMODULES=off` does not fix the issue.

**Comment by odeke-em** [comment] 2019-03-12 16:14
Kindly paging @bcmills.

**Comment by mvdan** [comment] 2019-03-12 16:31
> GOMODULES=off

I assume you meant GO111MODULE=off?

**Comment by macetw** [comment] 2019-03-12 17:24
I also see this on macos/darwin.
<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/macet/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/macet/work/GOPATH"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9v/6zqn9ncn39x63s0j25sqh7z00000gn/T/go-build584552247=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by bcmills** [comment] 2019-03-12 17:59
I can reproduce these failures. It's strange that they're not also showing up in the TryBots and builders — probably something to do with the environment, but we'll find out.

**Comment by empijei** [comment] 2019-03-12 18:38
> > GOMODULES=off
> 
> I assume you meant GO111MODULE=off?

yup, sorry

**Comment by ceseo** [comment] 2019-03-12 19:40
This seems to be breaking ppc64le/ppc64 as well:
```
##### ../test
# go run run.go -- nosplit.go
incorrect output
BUG
rejected incorrectly:
        main 0

        linker output:
        go: failed to create cache directory /dev/null/pkg/mod/cache: mkdir /dev/null: not a directory

```
Weirdly, these aren't showing up in the Go Build Dashboard.

**Comment by bcmills** [comment] 2019-03-12 20:47
I'm pretty sure this is actually fixed now, but please let me know if it's still broken. 😩

**Closed by bcmills** 2019-03-12 20:47 UTC
Labels: NeedsInvestigation, Soon, modules

**Comment by empijei** [comment] 2019-03-12 21:35
I verified this fixes the issue. If anyone else did the same please +1 this comment.

**Comment by ceseo** [comment] 2019-03-13 01:16
This is fixed on ppc64/ppc64le. Thanks!
