### ISSUE TITLE
go version is slow and creates junk files

### ISSUE THREAD

**Issue by moenodedev** [golang/go#69177] opened 2024-08-30 21:56 UTC
### Go version

go version go1.23.0 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/mike/Library/Caches/go-build'
GOENV='/Users/mike/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/mike/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/mike/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.23.0/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.23.0/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.23.0'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/mike/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
```

### What did you do?

`go version`

### What did you see happen?

A go folder was created with junk files

```
$ find go
go
go/pkg
go/pkg/sumdb
go/pkg/sumdb/sum.golang.org
go/pkg/sumdb/sum.golang.org/latest
go/pkg/mod
go/pkg/mod/cache
go/pkg/mod/cache/download
go/pkg/mod/cache/download/sumdb
go/pkg/mod/cache/download/sumdb/sum.golang.org
go/pkg/mod/cache/download/sumdb/sum.golang.org/lookup
go/pkg/mod/cache/download/sumdb/sum.golang.org/lookup/golang.org
go/pkg/mod/cache/download/sumdb/sum.golang.org/lookup/golang.org/x
go/pkg/mod/cache/download/sumdb/sum.golang.org/lookup/golang.org/x/telemetry
go/pkg/mod/cache/download/sumdb/sum.golang.org/lookup/golang.org/x/telemetry/config@v0.29.0
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/0
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/0/x113
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/0/x113/563
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/0/x114
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/0/x114/749.p
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/0/x114/749.p/11
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/1
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/1/448.p
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/1/448.p/61
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/1/443
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/3
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/3/000.p
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/3/000.p/1
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/2
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/2/001.p
go/pkg/mod/cache/download/sumdb/sum.golang.org/tile/8/2/001.p/192
go/pkg/mod/cache/download/golang.org
go/pkg/mod/cache/download/golang.org/x
go/pkg/mod/cache/download/golang.org/x/telemetry
go/pkg/mod/cache/download/golang.org/x/telemetry/config
go/pkg/mod/cache/download/golang.org/x/telemetry/config/@v
go/pkg/mod/cache/download/golang.org/x/telemetry/config/@v/v0.29.0.ziphash
go/pkg/mod/cache/download/golang.org/x/telemetry/config/@v/v0.29.0.info
go/pkg/mod/cache/download/golang.org/x/telemetry/config/@v/list
go/pkg/mod/cache/download/golang.org/x/telemetry/config/@v/v0.29.0.mod
go/pkg/mod/cache/download/golang.org/x/telemetry/config/@v/v0.29.0.zip
go/pkg/mod/cache/download/golang.org/x/telemetry/config/@v/v0.29.0.lock
go/pkg/mod/golang.org
go/pkg/mod/golang.org/x
go/pkg/mod/golang.org/x/telemetry
go/pkg/mod/golang.org/x/telemetry/config@v0.29.0
go/pkg/mod/golang.org/x/telemetry/config@v0.29.0/go.mod
go/pkg/mod/golang.org/x/telemetry/config@v0.29.0/LICENSE
go/pkg/mod/golang.org/x/telemetry/config@v0.29.0/config.json
go/pkg/mod/golang.org/x/telemetry/config@v0.29.0/doc.go
```

### What did you expect to see?

No filesystem writes

**Comment by moenodedev** [comment] 2024-08-30 22:00
`go version` takes a few seconds on CI and makes network requests

**Comment by seankhliao** [comment] 2024-08-30 22:01
Duplicate of #68946

**Closed by seankhliao** 2024-08-30 22:01 UTC
