### ISSUE TITLE
runtime: building Go on windows/arm64 hits inconsistent test failures

### ISSUE THREAD

**Issue by robkelly** [golang/go#44820] opened 2021-03-05 18:52 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +280c735b07 Fri Mar 5 16:02:44 2021 +0000 windows/arm64

</pre>

### Does this issue reproduce with the latest release?
N/A, cloned from master (280c735b07af9ea313d73049b0031f466e8d1000)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

C:\Users\u\code\go\src>..\bin\go env
set GO111MODULE=
set GOARCH=arm64
set GOBIN=
set GOCACHE=C:\Users\u\AppData\Local\go-build
set GOENV=C:\Users\u\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=arm64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\u\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\u\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\u\code\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\u\code\go\pkg\tool\windows_arm64
set GOVCS=
set GOVERSION=devel +280c735b07 Fri Mar 5 16:02:44 2021 +0000
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\u\code\go\src\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\u\AppData\Local\Temp\go-build4225962944=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
Trying to build Windows arm64 go on a Surface Pro X. 
Cloned latest go source, ran src\all.bat with a bootstrapped version of go cross compiled from my macbook and copied over. First run I hit a test failure of:
<pre>
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
--- FAIL: TestGcLastTime (0.00s)
    gc_test.go:126: bad last GC time: got 1614963630000702600, want [1614963630099702800, 1614963630000702600]
FAIL
FAIL    runtime 21.884s
FAIL
2021/03/05 09:00:48 Failed: exit status 1

</pre>

Running again I hit a different test failure:
<pre>
--- FAIL: TestClientCallsCloseOnlyOnce (21.49s)
    client_test.go:2048: dial tcp 127.0.0.1:57933: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
FAIL
FAIL    net/http        22.909s
</pre>

On the third run everything passed successfully, and I appear to have a working go build.

**Comment by robkelly** [comment] 2021-03-05 18:53
@rsc this is probably of interest to you.

**Comment by tdakkota** [comment] 2021-07-06 08:14
First fail seems related to low time resolution on Windows. 
https://github.com/golang/go/blob/912f0750472dd4f674b69ca1616bfaf377af1805/src/runtime/gc_test.go#L120-L125

There is should be 
```go
t0 >= last || last >= t1 
```
instead of 
```go
t0 > last || last > t1 
```

**Comment by tdakkota** [comment] 2021-07-06 08:20
Similiar failure
https://build.golang.org/log/b9491de2f3352bc70be88748959c5e1a06f5e35f

**Comment by bcmills** [comment] 2021-08-30 18:58
Different tests often fail due to different underlying causes; please file separate issues for test failures that are not obviously correlated.

I've filed the `TestGcLastTime` issue as #48072.

**Comment by bcmills** [comment] 2021-11-08 20:09
The `TestClientCallsCloseOnlyOnce` failure reproduced on the Go builder; filed as #49454.

(Closing this issue as redundant with the two specific ones.)

**Closed by bcmills** 2021-11-08 20:09 UTC
Labels: OS-Windows, NeedsInvestigation, arch-arm64
