### ISSUE TITLE
proxy.golang.org: github.com/retr0h/gilt

### ISSUE THREAD

**Issue by retr0h** [golang/go#65539] opened 2024-02-06 04:08 UTC
Apologies for creating an issue, but I'm not sure where else to turn, and following the [FAQ](https://proxy.golang.org/
).

I'm unable to install my package.  I had renamed the repo from github.com/retr0h/go-gilt to github.com/retr0h/gilt which I am thinking may have something to do with it.  My package seems to be stuck @v1.0.2.

```bash
go: github.com/retr0h/gilt@latest: version constraints conflict:
	github.com/retr0h/gilt@v1.0.2: parsing go.mod:
	module declares its path as: github.com/retr0h/go-gilt
	        but was required as: github.com/retr0h/gilt
```

```
$ curl -sL https://proxy.golang.org/github.com/retr0h/gilt/@latest
{"Version":"v1.0.2","Time":"2023-12-27T21:44:45Z","Origin":{"VCS":"git","URL":"https://github.com/retr0h/gilt","Ref":"refs/tags/v1.0.2","Hash":"c9f7195faa37db6e355890eca82963d34b6fdb55"}}
```

Thank you for your help, and again my apologies if this was the wrong place to post this message.

**Comment by Jorropo** [comment] 2024-02-06 05:08
Looking at the project it only released versions with the updated `go.mod` `module` entry on the `v2` branch.
![image](https://github.com/golang/go/assets/24391983/0ff3fe22-dd81-47ab-bb41-06d6c8352e23)

You should be able to use `github.com/retr0h/go-gilt` to use v1 branch, or add `github.com/retr0h/gilt/v2` for v2 branch.
If neither solves your problem please reopen the issue. I'm closing as it looks like it works as intended.

**Closed by Jorropo** 2024-02-06 05:08 UTC
Labels: proxy.golang.org

**Comment by Jorropo** [comment] 2024-02-06 05:09
Relevant part of the module spec:
> If the module is released at major version 2 or higher, the module path must end with a [major version suffix](https://go.dev/ref/mod#major-version-suffixes) like /v2. This may or may not be part of the subdirectory name. For example, the module with path golang.org/x/repo/sub/v2 could be in the /sub or /sub/v2 subdirectory of the repository golang.org/x/repo.

https://go.dev/ref/mod#module-path

**Comment by Jorropo** [comment] 2024-02-06 05:15
I just realised, I overlooked that `go get github.com/retr0h/gilt/v2@latest` also does not work because the `module` in `go.mod` should also have the `/v2` prefix.

**Comment by retr0h** [comment] 2024-02-06 21:39
> I just realised, I overlooked that `go get github.com/retr0h/gilt/v2@latest` also does not work because the `module` in `go.mod` should also have the `/v2` prefix.

Thank you!
