### ISSUE TITLE
x/tools/gopls: Compiler should support `:` in asm go1.20

### ISSUE THREAD

**Issue by timandy** [golang/go#58314] opened 2023-02-04 02:12 UTC
As you know, go 1.20 auto generated symbols's name is changed(`go.`->`go:` and `type.`->`type:`).

But when I reference these new symbols in asm, the compiler reported error(`illegal or missing addressing mode for symbol type`).

I think the compiler's behavior should be adjusted accordingly.

Thanks for all.

**Comment by suzmue** [comment] 2023-02-07 22:14
Closing as a duplicate of #58244.

There is nothing gopls can do to address this issue.

**Closed by suzmue** 2023-02-07 22:14 UTC
Labels: NeedsInvestigation, gopls, Tools
