### ISSUE TITLE
How to package an executable binary package into the program?

### ISSUE THREAD

**Issue by juchao1989** [golang/go#46601] opened 2021-06-07 01:36 UTC
How to package an executable binary package into the program?
such as:
go code: exec.Command("/bin/bash", "-c","./hello")//hello is an executable binary file
How to pack this 'hello' binary into go for use?
My purpose is not to let users see two executable files, and pack one binary file into another go!
Any solution, please give me ideas, thank you very much

**Comment by jim3ma** [comment] 2021-06-07 02:49
Package embed provides access to files embedded in the running Go program.
FYI
https://golang.org/pkg/embed/

**Comment by juchao1989** [comment] 2021-06-07 05:49
Thanks, I'll try it

**Comment by ALTree** [comment] 2021-06-07 06:45
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2021-06-07 06:45 UTC
