### ISSUE TITLE
x/pkgsite: EJI banner obscures widgets on page

### ISSUE THREAD

**Issue by kortschak** [golang/go#39767] opened 2020-06-23 00:56 UTC
### What is the URL of the page with the issue?

https://pkg.go.dev/

### What is your user agent?
 

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0

 
### Screenshot

![Screenshot from 2020-06-23 10-22-48](https://user-images.githubusercontent.com/275221/85348702-88244e00-b53b-11ea-93d8-f7727ccf7d35.png)

Note the sliver of a button being obscured by the banner.

### What did you do?

Browse to page.

### What did you expect to see?
 
No obstructed page widgets; page moved down to make room for banner.

### What did you see instead?

Image above.

**Comment by ALTree** [comment] 2020-06-23 06:29
No, that's actually how the website looks. On mouseover, a little line appears on the top of the top bar item.

Here's a screenshot without any banner:

![cap](https://user-images.githubusercontent.com/3586803/85368425-86eb2500-b52b-11ea-983b-4f468ffdbfa5.png)

I'm closing here since it's working as intended. Feel free to comment if you think I'm wrong.

**Comment by kortschak** [comment] 2020-06-23 06:33
You're right. Why is that distracting pale blue bar there then? It's just noticeable enough to look wrong.

**Comment by ALTree** [comment] 2020-06-23 06:37
> Why is that distracting pale blue bar there then?

Not a web designer but I think is to mark the element your mouse is hovering. I agree it's a puzzling design choice, usually you do that by underling the words or by shading the whole button area with a different colour. I've never seen it done with a thin coloured line.

**Comment by kortschak** [comment] 2020-06-23 06:41
The issue is that the blue bar is always there and looks like an obstructed widget; I can understand the red bar that shows up with hover.

**Comment by ALTree** [comment] 2020-06-23 09:10
> The issue is that the blue bar is always there (only above "Discover Packages") and looks like an obstructed widget;

Oh, okay. Sorry, I didn't get that. I thought it was the on-hover one. I have no idea why you have a blue line stuck there, I don't see one. I'll re-open.

cc @julieqiu

**Comment by ALTree** [comment] 2020-06-23 09:12
EDIT: actually I see it, on the "discover packages" item only. I think it's there to highlight it, and it's by design. Sorry for the confusion, but I think this is working as intended.

**Closed by ALTree** 2020-06-23 09:12 UTC
Labels: NeedsInvestigation

**Comment by kortschak** [comment] 2020-06-23 09:57
OK. I think it's bad design and probably should be changed; it's distracting and too subtle to actually draw attention to what it might be trying to draw attention to. This issue is not correct for that though and it seems like there's probably little interest in fixing it. If it will be entertained, I'll file an issue, otherwise I will just try to ignore it or continue to use godoc.org.

**Comment by julieqiu** [comment] 2020-06-23 15:40
@kortschak - feel free to file an issue. We can address this with our UX team for the next round of design changes. 

/cc @fflewddur @Joanne881107
