### ISSUE TITLE
x/tools/gopls: change to go.mod file does not trigger recalculation of diagnostics

### ISSUE THREAD

**Issue by myitcv** [golang/go#35820] opened 2019-11-25 12:27 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +6f7b96f6cb Sat Nov 23 11:00:41 2019 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20191113223546-95cb2a1a7eae => github.com/myitcvforks/tools v0.0.0-20191119111301-0222b4b716c6
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.1.8-0.20191115202509-3a792d9c32b2 => github.com/myitcvforks/tools/gopls v0.0.0-20191119111301-0222b4b716c6
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build615579010=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

This is probably related to https://github.com/golang/go/issues/35548 but raising as a separate issue because it's specifically about changing `go.mod` as opposed to configuration.

We have a `govim` test that verifies the setting of the `"env"` value `GOFLAG=-mod=readonly`. It is based on the following setup:

```
-- go.mod --
module mod.com

go 1.13
-- main.go --
package main

import "example.com/blah"

func main() {
	println(blah.Name)
}
```

(`example.com/blah` is a valid module and is accessible FWIW, see later).

We initially verify that the `go.mod` file is not changed by `gopls`. This is fine. We also verify that `main.go` has the following diagnostic:

```
main.go|3 col 8| could not import example.com/blah (no package for import example.com/blah)
```

Also fine.

Then we update `go.mod` from outside the editor using:

```
go get example.com/blah@v1.0.0
```

This change gets notified to `gopls` via `didChange` but the diagnostics for `main.go` are not updated.

### What did you expect to see?

The diagnostics for `main.go` to be updated such that there are no errors.

### What did you see instead?

The diagnostics for `main.go` unchanged.

See the interactions via the `gopls` log file: [fail.log](https://github.com/golang/go/files/3886552/fail.log)

---

cc @stamblerre @matloob

**Comment by stamblerre** [comment] 2019-11-25 23:31
This is a consequence of https://github.com/golang/go/issues/31999. `gopls` doesn't yet track modifications to `go.mod` files. @ridersofrohan will be working on this issue. Closing as a duplicate of https://github.com/golang/go/issues/31999.

**Closed by stamblerre** 2019-11-25 23:31 UTC
Labels: NeedsInvestigation, Tools, gopls
