### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by finnigantime** [golang/go#47208] opened 2021-07-14 20:39 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.16.6 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

yes (website issue)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

n/a

### What did you do?

Go to https://golang.org/doc/tutorial/greetings-multiple-people

### What did you expect to see?

this circled line should also be highlighted as having changed

![Screen Shot 2021-07-14 at 1 35 19 PM](https://user-images.githubusercontent.com/1305608/125689783-b25f9b51-814b-4785-a0ce-548ce66e03e6.png)

### What did you see instead?

![Screen Shot 2021-07-14 at 1 35 19 PM](https://user-images.githubusercontent.com/1305608/125689714-97c97cd1-c67d-4b36-be02-7fd9c21b842d.png)

**Comment by dmitshur** [comment] 2021-07-14 21:12
Thanks for reporting. I suspect this might be a duplicate of #46416.

**Comment by cherrymui** [comment] 2021-07-14 21:49
Yeah, this looks like a dup. Let's move on at #46416. Closing. Thanks.

**Closed by cherrymui** 2021-07-14 21:49 UTC
