### ISSUE TITLE
playground: vet and compile disagree on size of int

### ISSUE THREAD

**Issue by vcabbage** [golang/go#29825] opened 2019-01-18 22:42 UTC
### What version of Go are you using (`go version`)?

I can only reproduce in the Go Playground

### What did you do?

``` go
package main

import (
	"unsafe"
)

type myStruct struct {
	a, b int
}

var _ [8]byte = [unsafe.Sizeof(myStruct{})]byte{}

func main() {}
```
https://play.golang.org/p/asSsu2foRHF

### What did you expect to see?

Successful compile.

### What did you see instead?

```
prog.go:11:5: cannot use [16]byte literal (type [16]byte) as type [8]byte in assignment
```

Attempting to change the declaration to `[16]byte` results in:
```
prog.go:11:5: cannot use [8]byte literal (type [8]byte) as type [16]byte in assignment
```

This doesn't reproduce when compiling for amd64 or 386, so I expect it's specific to nacl.

**Comment by ianlancetaylor** [comment] 2019-01-19 00:59
This is a playground specific problem.  One error is coming from vet.  One is coming from the compiler.  The problem is that vet and the compiler when run on the playground don't agree on the size of `int`.  You can see this more clearly if you change the `main` function to actually print something.  In the case with the vet error, you will see the error, and you will also see the output.

**Comment by vcabbage** [comment] 2019-01-19 01:04
I completely missed that the message was from vet. Thanks!

**Comment by bcmills** [comment] 2019-01-22 17:53
Duplicate of #27885.

**Closed by bcmills** 2019-01-22 17:53 UTC
Labels: NeedsFix
