### ISSUE TITLE
Go 1.12 breaks cgo

### ISSUE THREAD

**Issue by bobrik** [golang/go#28821] opened 2018-11-15 22:23 UTC
### What version of Go are you using (`go version`)?

```
$ ./bin/go version
go version devel +90df37769d Thu Nov 1 21:54:54 2018 +0000 linux/amd64
```

### Does this issue reproduce with the latest release?

Not with go1.11.2, but with tip. I bisected to this commit:

```diff
$ git bisect bad
90df37769d6441ce550443fa7e0c008d38e53455 is the first bad commit
commit 90df37769d6441ce550443fa7e0c008d38e53455
Author: Ian Lance Taylor <iant@golang.org>
Date:   Wed Oct 17 08:04:01 2018 -0700

    cmd/cgo: rewrite pointer checking to use more function literals

    Fixes #14210
    Fixes #25941

    Change-Id: Idde2d032290da3edb742b5b4f6ffeb625f05b494
    Reviewed-on: https://go-review.googlesource.com/c/142884
    Reviewed-by: Brad Fitzpatrick <bradfitz@golang.org>

:040000 040000 be516fb26c8edf35775da611547f78bb0f621953 fe68ed3319823f8a2cc4791ad540be1760ecedbe M	misc
:040000 040000 070fb7b2495736ee045b1b2dc4eec63f5e91254b 5f5253fd04bb6fef472424b3784032e8f6e968e6 M	src
```

Related to: #14210, #25941.

cc @ianlancetaylor

### What operating system and processor architecture are you using (`go env`)?

```
$ ./bin/go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ivan/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GOPROXY=""
GORACE=""
GOROOT="/home/ivan/go"
GOTMPDIR=""
GOTOOLDIR="/home/ivan/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build395867230=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

Run a Travic CI job that builds a CGO package:

* https://travis-ci.org/cloudflare/ebpf_exporter/jobs/455709945

### What did you expect to see?

Successfull compilation like on go1.11.2:

```
https://travis-ci.org/cloudflare/ebpf_exporter/jobs/455709944
```

### What did you see instead?

```
vendor/github.com/iovisor/gobpf/bcc/perf.go:191: cannot use _cgo5 (type int) as type _Ctype_int in argument to _C2func_bpf_open_perf_buffer
```

Code is [here](https://github.com/cloudflare/ebpf_exporter/blob/1fc0e67a43a8/vendor/github.com/iovisor/gobpf/bcc/perf.go#L191-L195):

```go
	reader, err := C.bpf_open_perf_buffer(
		(C.perf_reader_raw_cb)(unsafe.Pointer(C.callback_to_go)),
		nil,
		unsafe.Pointer(uintptr(callbackDataIndex)),
		-1, cpuC, BPF_PERF_READER_PAGE_CNT)
```

**Comment by odeke-em** [comment] 2018-11-15 23:41
Thank you for reporting this issue @bobrik and welcome to the Go project!

This looks like an exact duplicate of #28772 so I'll close it and please report your findings also on that issue. I'll also page our cgo expert @ianlancetaylor

**Closed by odeke-em** 2018-11-15 23:41 UTC
