### ISSUE TITLE
cmd/compile: internal compiler error: Type.Elem UNSAFEPTR

### ISSUE THREAD

**Issue by LastPossum** [golang/go#30254] opened 2019-02-15 14:06 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

It's latest release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/egartman/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/egartman/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mv/gfk793qd08b1kj0qcxt5cf_40000gn/T/go-build087446295=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Ran this test:

```
package main

import (
	"reflect"
	"testing"
	"unsafe"
)

//go:linkname memmove runtime.memmove
func memmove(to, from unsafe.Pointer, n uintptr)

func TestMemmove(t *testing.T) {
	from := []byte{1, 2, 3, 4, 5}
	to := []byte{7, 7, 7, 7, 7}
	want := []byte{7, 1, 2, 3, 7}
	memmove(unsafe.Pointer(&to[1]), unsafe.Pointer(&from[1]), uintptr(3))
	if !reflect.DeepEqual(to, want) {
		t.Fatalf("unexpected %v, want %v", to, want)
	}
}
```

### What did you expect to see?

Test running

### What did you see instead?

<autogenerated>:1: internal compiler error: Type.Elem UNSAFEPTR

**Comment by bcmills** [comment] 2019-02-15 14:07
Does this issue reproduce with `go1.12rc1`?

**Comment by bcmills** [comment] 2019-02-15 14:07
CC @randall77 @griesemer

**Comment by LastPossum** [comment] 2019-02-15 14:34
> Does this issue reproduce with `go1.12rc1`?

No. It works fine.

```
> go version
go version go1.12rc1 darwin/amd64

> go test
--- FAIL: TestMemmove (0.00s)
    memmove_test.go:18: unexpected [7 2 3 4 7], want [7 1 2 3 7]
FAIL
exit status 1
FAIL    testing.fun/unescape    0.005s
```

**Comment by mvdan** [comment] 2019-02-15 14:48
Duplicate of https://github.com/golang/go/issues/30061, it seems. If you'd like it backported to 1.11, leave a comment there.

**Closed by mvdan** 2019-02-15 14:48 UTC
Labels: NeedsInvestigation, WaitingForInfo
