### ISSUE TITLE
slog: Wrapping default handler causes deadlock

### ISSUE THREAD

**Issue by mkch** [golang/go#62424] opened 2023-09-02 02:28 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/me/Library/Caches/go-build'
GOENV='/Users/me/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/me/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/me/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/4v/g652j2zn37lg22crrdwmcqdm0000gn/T/go-build1896165565=/tmp/go-build -gno-record-gcc-switches -fno-common'
</pre></details>

### What did you do?

https://go.dev/play/p/gu5St1Epba_9

### What did you expect to see?
Log message like the following:
`2023/09/02 10:24:00 INFO debug message`

### What did you see instead?
fatal error: all goroutines are asleep - deadlock!

**Comment by panjf2000** [comment] 2023-09-02 03:23
Check out the comment in `slog.SetDefault`
https://github.com/golang/go/blob/83fe0e093d5ceebd8320bfeacd2254a2546b2eb9/src/log/slog/logger.go#L29-L36

**Comment by mkch** [comment] 2023-09-02 04:42
> Check out the comment in `slog.SetDefault`
> https://github.com/golang/go/blob/83fe0e093d5ceebd8320bfeacd2254a2546b2eb9/src/log/slog/logger.go#L29-L36

Sorry, I can't see any relevance.

**Comment by panjf2000** [comment] 2023-09-02 04:51
`slog.SetDefault` can only prevent the deadlock from the loggers that use the exact `defaultHandler`, and it doesn't handle the case you provided (embed the default handler into a struct), I'm not sure whether we should fix this as it seems like a rare case.

/cc @jba

**Comment by mkch** [comment] 2023-09-02 05:50
> `slog.SetDefault` can only prevent the deadlock from the loggers that use the exact `defaultHandler`, and it doesn't handle the case you provided (embed the default handler into a struct), I'm not sure whether we should fix this as it seems like a rare case.
> 
> /cc @jba

Thanks for your clarification. Can I consider this a implementation limitation?
What I really want to do is changing the level of the default Handler. Something lile https://go.dev/play/p/bXoD9C49mNy

**Comment by panjf2000** [comment] 2023-09-02 06:08
Looks like #62418 will work for you once it's accepted and implemented.

**Comment by seankhliao** [comment] 2023-09-02 07:50
Duplicate of #61892

**Closed by seankhliao** 2023-09-02 07:50 UTC
Labels: NeedsDecision
