### ISSUE TITLE
cmd/go: unknown option `unshallow' when running go get

### ISSUE THREAD

**Issue by joegrasse** [golang/go#32905] opened 2019-07-02 19:39 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/386
</pre>

### What operating system and processor architecture are you using (`go env`)?
CentOS 6.10
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="386"
GOBIN=""
GOCACHE="/usr2/shared/graj04/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr2/ps/isp/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_386"
GCCGO="gccgo"
GO386="sse2"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build693494323=/tmp/go-build"
</pre></details>

### What did you do?
go get -u golang.org/x/tools/gopls@latest

### What did you expect to see?
Successful download/install of gopls using modules.

### What did you see instead?
```go: finding golang.org/x/tools v0.0.0-20190628153133-6cdbf07be9d0
go: golang.org/x/tools@v0.0.0-20190628153133-6cdbf07be9d0: git -c protocol.version=0 fetch --unshallow -f https://go.googlesource.com/tools refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /usr2/ps/isp/go/pkg/mod/cache/vcs/b44680b3c3708a854d4c89f55aedda0b223beb8d9e30fba969cefb5bd9c1e843: exit status 129:
        error: unknown option `unshallow'
        usage: git fetch [<options>] [<repository> [<refspec>...]]
           or: git fetch [<options>] <group>
           or: git fetch --multiple [<options>] [(<repository> | <group>)...]
           or: git fetch --all [<options>]

            -v, --verbose         be more verbose
            -q, --quiet           be more quiet
            --all                 fetch from all remotes
            -a, --append          append to .git/FETCH_HEAD instead of overwriting
            --upload-pack <path>  path to upload pack on remote end
            -f, --force           force overwrite of local branch
            -m, --multiple        fetch from multiple remotes
            -t, --tags            fetch all tags and associated objects
            -n                    do not fetch all tags (--no-tags)
            -p, --prune           prune remote-tracking branches no longer on remote
            --recurse-submodules[=<on-demand>]
                                  control recursive fetching of submodules
            --dry-run             dry run
            -k, --keep            keep downloaded pack
            -u, --update-head-ok  allow updating of HEAD ref
            --progress            force progress reporting
            --depth <depth>       deepen history of shallow clone
go get: error loading module requirements
```

Looks like the version of Git that can be installed with CentOS 6.10 doesn't support `unshallow`.

**Comment by bcmills** [comment] 2019-07-02 19:54
Duplicate of #28550

**Comment by bcmills** [comment] 2019-07-02 19:55
As a workaround, note that you can set `GOPROXY=https://proxy.golang.org` to fetch using HTTPS instead of Git.

**Closed by bcmills** 2019-07-02 19:54 UTC

**Comment by thepudds** [comment] 2019-07-03 13:03
@joegrasse Three quick questions for you:

1. How feasible is it to upgrade CentOS versions on your development machines? 

2.  How feasible is it to instead install a more modern version of git on your development machines?  Even if that might not be desirable, is it more feasible than upgrading CentOS itself?

3. Does the GOPROXY workaround work for you?
