### ISSUE TITLE
x/pkgsite: docs not shown for packages with broken licenses

### ISSUE THREAD

**Issue by epelc** [golang/go#39388] opened 2020-06-03 19:46 UTC
I think pkg.dev.go should show go docs regardless of license if the code is available on github or any other site `go get` supports. If it is public there I do not see why docs can not be shown for it in a nice format under fair use laws. Godoc.org shows docs regardless of license and in this case it was due to licensecheck not detecting an apache 2 license correctly for the go sparkpost repo.

### What is the URL of the page with the issue?
 
 pkg.dev.go doesn't show any docs if the license can't be found.
 
### What is your user agent?
 

Google Chrome
Version 83.0.4103.61 (Official Build) (64-bit)
 
 
### Screenshot
 

 
![image](https://user-images.githubusercontent.com/5204642/83681816-f1561880-a5b0-11ea-8bea-e9386b087e83.png)

 
 
### What did you do?
 

 
Go to https://pkg.go.dev/github.com/SparkPost/gosparkpost?tab=overview
 
 
### What did you expect to see?
 
 Docs for the code.
 
### What did you see instead?

A near empty page.

**Comment by robpike** [comment] 2020-06-04 00:10
This behavior is indeed unfortunate, but I believe the issue is that if a license cannot be detected, it's possible that showing the documentation would violate the (undetectable) license. Of course that is unlikely, but caution before enthusiasm.

The right thing to do here might be a clarification in the policy that is linked from the page.

**Comment by epelc** [comment] 2020-06-04 03:40
Was there some specific legal review or takedown request that caused this default change? I would think it’d fall under fair use as the docs site isn’t republishing the entire code, only the api.

Anyways if the legal portion can’t be figured easily maybe a script or links to how to run a local go doc server to view docs for the package could be added to these pages.

Would be interesting if there are any stats on how many packages the license checker fails to detect. Could definitely shed more light on if this is important or not.

**Comment by jba** [comment] 2020-06-04 21:13
There  was an extensive thread on golang-dev about this with an [important post](https://groups.google.com/g/golang-dev/c/mfiPCtJ1BGU/m/qtCrqlrEEwAJ) by Russ Cox. I recommend reading it (the post, not necessarily the entire thread). The relevant part for this issue is

> The rule we've been given to follow is that serving a pretty HTML version of the docs is displaying a modified version of the original, and we can only do that if there's a recognized known-good license that gives us that permission.

Russ's post also discusses why godoc.org doesn't check licenses, and provides stats on license detection.

We're committed to displaying every package that we're allowed to, so if there are specific packages that fail to show despite having what you believe to be a valid license, let us know and we'll try to fix the problems.

**Comment by epelc** [comment] 2020-06-04 21:28
Thanks for the detailed info @jba!

`1,200 modules` does seem like a large enough number to make adding a one liner or short script for running go doc locally and viewing the given package there instead worth it.

I opened an issue the other day with gosparkpost to fix the license detection. https://github.com/SparkPost/gosparkpost/issues/155 Not sure if this is a simple change on their end or a bug with the license checker.

**Comment by epelc** [comment] 2020-06-18 15:11
@julieqiu are you waiting for info from me? I linked the issue in specific repo I encountered license issues on.

I think adding a script to run locally to the error message displayed on repos with bad license would be helpful to solve this.

**Comment by jba** [comment] 2020-06-18 17:08
It's my fault, I didn't follow up on that issue. Will do so today.

Now that we're open-source, anyone can run our license detection code.

**Comment by jba** [comment] 2020-06-18 21:20
They're using variant wording that falls below our detection threshold. I commented on the issue.

**Comment by jba** [comment] 2021-01-17 01:09
https://pkg.go.dev/github.com/SparkPost/gosparkpost is now OK.

**Closed by jba** 2021-01-17 01:09 UTC
Labels: WaitingForInfo, pkgsite
