### ISSUE TITLE
cmd/go: GO15VENDOREXPERIMENT go get errors out when using submodules in /vendor

### ISSUE THREAD

**Issue by StephanDollberg** [golang/go#12573] opened 2015-09-10 18:56 UTC
As per [golang-nuts](https://groups.google.com/forum/#!topic/golang-nuts/XNJ_vfai9Io):

I am trying to get vendoring working with submodules which is supposed to be working according to [s/go15vender](https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit). The building part works fine but the "go get" part doesn't.

To reproduce I created a test [repo](https://github.com/StephanDollberg/govendorsubmodulestest) by doing the following: 
 
Created a test package and added a submodule via:
     
     git submodule add https://github.com/dgrijalva/jwt-go vendor/github.com/dgrijalva/jwt-go

Committed everything.

Now, if I do:

    GO15VENDOREXPERIMENT=1 go get github.com/StephanDollberg/govendorsubmodulestest

I get the error:

```
# cd .; git --git-dir=/$GOPATH/src/github.com/StephanDollberg/govendorsubmodulestest/.git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'vendor/github.com/dgrijalva/jwt-go'
package github.com/StephanDollberg/govendorsubmodulestest: exit status 1
```

The interesting thing is that if I do a go get -u after that it checks out the submodule correctly. Looking at the error and the source of the go command I think it has to do with --git-dir not working together with the submodule command. 

I tested this on Windows, Mac OSX and Linux (all Intel 64bit)  with go 1.5.1 and several git versions (2.3, 2.4, 2.5).

**Comment by kovetskiy** [comment] 2015-09-25 09:33
any progress?

**Comment by StephanDollberg** [comment] 2015-09-25 11:06
Not from my side no. The other dupe is labeled Go 1.6 so I doubt there will be any quick fix for this.

**Comment by kovetskiy** [comment] 2015-09-25 11:10
@StephanDollberg `labeled Go 1.6` where is? I see `Labels None yet`.

**Comment by StephanDollberg** [comment] 2015-09-25 12:02
Yeah, not on this one but on #12612.

**Comment by oschwald** [comment] 2015-09-25 16:30
This is affecting several users of https://github.com/oschwald/geoip2-golang as discussed in https://github.com/oschwald/geoip2-golang/issues/13. I might have to replace my submodule usage, but it would be really nice to get this fixed.

**Comment by StephanDollberg** [comment] 2015-09-25 16:32
Agree with you. Workaround in the time being is to run `go get -u` after the initial `go get`.

**Comment by rsc** [comment] 2015-11-05 01:37
Duplicate of #12612 (which has a suggested fix).

**Closed** 2015-11-05 01:37 UTC
