### ISSUE TITLE
x/pkgsite: unable to update packages

### ISSUE THREAD

**Issue by 89z** [golang/go#46350] opened 2021-05-24 18:26 UTC
I have new tag many hours ago:

https://github.com/89z/youtube/releases/tag/v1.9.8

but I cant get docs to update to newer version:

https://pkg.go.dev/github.com/89z/youtube@v1.9.8

**Comment by 89z** [comment] 2021-05-24 18:45
Looks like it finally loaded

**Comment by 89z** [comment] 2021-05-24 22:36
So the package finally loaded, but now new versions wont load:

https://pkg.go.dev/github.com/89z/xz@v1.0.4

**Comment by 89z** [comment] 2021-05-25 00:00
So the package finally loaded, but now new versions wont load:

https://pkg.go.dev/github.com/89z/xz@v1.0.4

I tried with browser, also with cURL:

~~~
PS C:\> curl.exe -v -X POST https://pkg.go.dev/fetch/github.com/89z/xz@v1.0.4
< HTTP/2 408
< content-type: text/plain; charset=utf-8
< content-security-policy: object-src 'none'; base-uri 'none'; script-src 'unsafe-inline' 'strict-dynamic' https: http: 'sha256-CoGrkqEM1Kjjf5b1bpcnDLl8ZZLAsVX+BoAzZ5+AOmc=' 'sha256-3YbNePu1zD/B/1vcR3xg4CvNdno3XxbHPOPB+s4Sc0U=' 'sha256-karKh1IrXOF1g+uoSxK+k9BuciCwYY/ytGuQVUiRzcM=' 'sha256-CgM7SjnSbDyuIteS+D1CQuSnzyKwL0qtXLU6ZW2hB+g=' 'sha256-dwce5DnVX7uk6fdvvNxQyLTH/cJrTMDK6zzrdKwdwcg=' 'sha256-M35cNZ8vPcaBGw5WTgh0Gn7DLsxkvPbdTFN1pELeevM=' 'sha256-v9+UvX+P27rKraeTl7uAfOWdLmmQU39RskIoqUrU4wo=' 'sha256-4FhQmh9Hu76JzYm35KNNysU2Z7buJwg3cMSHsGwKSCE=' 'sha256-y5EX2GR3tCwSK0/kmqZnsWVeBROA8tA75L+I+woljOE=' 'sha256-r4g06j/B7WYKOSl8cFfvuZOyiYA1tOyrbnxapiSP64g=' 'sha256-nF5UdhqQFxB95DCaw1XdSQCEkIjoMhorTCQ+nQ4+Lq4=' 'sha256-L+G1K2BEWa+o2vPy1pwdabLjINBByPWi1NkRwvASUq8=' 'sha256-hb8VdkRSeBmkNlbshYmBnkYWC/BYHCPiz5s7liRcZNM=' 'sha256-KBdPSv2Ajjw3jsa29qBhRW49nNx3jXxOLZIWX545FCA=' 'sha256-Z9STHpM3Fz5XojcH5dbUK50Igi6qInBbVVaqNpjL/HY='
< x-content-type-options: nosniff
< x-frame-options: deny
< x-cloud-trace-context: e9eb44bfec0f6e12b1d67ff5c9fff92a
< date: Mon, 24 May 2021 23:58:18 GMT
< server: Google Frontend
< content-length: 84
<
We're still working on “github.com/89z/xz@v1.0.4”. Check back in a few minutes!
~~~

**Comment by 89z** [comment] 2021-05-25 00:43
Looks like it finally updated

**Comment by 89z** [comment] 2021-05-25 18:57
Now I am getting an issue where the "latest" version is an old version:

https://pkg.go.dev/github.com/89z/xz

Even though I have pushed two newer versions:

https://pkg.go.dev/github.com/89z/xz?tab=versions

both of the newer versions have been "published" at GitHub:

https://github.com/89z/xz/releases

and one of the newer versions is marked as "Latest release" at GitHub:

https://github.com/89z/xz/releases/tag/v1.1.3

**Comment by 89z** [comment] 2021-05-26 17:48
Now I am getting an issue where the "latest" version is an old version:

https://pkg.go.dev/github.com/89z/unioffice

Even though I have pushed a newer version:

https://pkg.go.dev/github.com/89z/unioffice@v1.0.4

the newer version has been "published" at GitHub:

https://github.com/89z/unioffice/releases

and the newer version is marked as "Latest release" at GitHub:

https://github.com/89z/unioffice/releases/tag/v1.0.4

**Comment by 89z** [comment] 2021-06-04 02:41
https://github.com/golang/go/issues/46527

**Comment by 89z** [comment] 2021-06-04 02:47
https://github.com/golang/go/issues/46350
https://github.com/golang/go/issues/46527
https://github.com/golang/go/issues/46535
https://github.com/golang/go/issues/46538

**Comment by jba** [comment] 2021-06-04 11:45
See referenced issues.

**Comment by FiloSottile** [comment] 2021-06-04 12:57
Duplicate of #46527

**Closed by FiloSottile** 2021-06-04 12:57 UTC
Labels: pkgsite
