### ISSUE TITLE
x/time/rate:  function Limiter.AllowN  generates much more tokens than expected

### ISSUE THREAD

**Issue by jiabiaoreal** [golang/go#56263] opened 2022-10-17 03:41 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.8 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/jiabiao/Library/Caches/go-build"
GOENV="/Users/jiabiao/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jiabiao/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jiabiao/go"
GOPRIVATE=""
GOPROXY=""
GOROOT="/usr/local/go"
GOSUMDB=""
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.8"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r0/1xtsxl1j5kb0yn0_9zn00kh80000gn/T/go-build2026362806=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

run  https://go.dev/play/p/WQ3RvLBPzZv

	l1 := rate.NewLimiter(1, 1)
	l2 := rate.NewLimiter(1, 1)

	count1 := 0
	count2 := 0
	s := time.Now()
	for now := time.Now(); now.Sub(s) < time.Second; now = time.Now() {
		if l1.AllowN(now, 1) {
			count1 += 1
		}
		if l1.AllowN(now.Add(time.Second), 1) {
			count1 += 1
		}

		if l2.AllowN(now.Add(time.Second), 1) {
			count2 += 1
		}
		if l2.AllowN(now.Add(time.Second), 1) {
			count2 += 1
		}

		time.Sleep(1 * time.Millisecond)
	}
	fmt.Printf("count1: %v\ncount2: %v\n", count1, count2)
   

### What did you expect to see?
count1, count2 are closer

### What did you see instead?

count1: 1001
count2: 1

There maybe a bug   in function advance, line 402. 
https://github.com/golang/time/blob/master/rate/rate.go#L402

	if t.Before(last) {
		last = t
	}

should be

	if t.Before(last) {
		t = last
	}

**Comment by ZekeLu** [comment] 2022-10-17 14:33
```diff
if t.Before(last) {
-	last = t
+	t = last
}
```

The suggested change is incorrect because some of the tests will fail if it's applied. This issue can be considered as another instance of #52584, which has a pending fix, https://github.com/golang/time/pull/22 (https://golang.org/cl/406154).

**Comment by seankhliao** [comment] 2022-10-17 14:52
Duplicate of #52584

**Closed by seankhliao** 2022-10-17 14:52 UTC
