### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by Ocxal46** [golang/go#60928] opened 2023-06-21 20:59 UTC
### 

<pre>
$ go version
go1.20.5 darwin/amd64
go1.15 darwin/amd64
go1.19 darwin/amd64

go1.20.5 linux/amd64
go1.15 linux/amd64
go1.19 linux/amd64

</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
I runned the same command both on darwin and debian linux terminals:
I tried with Golang 1.15 , 1.19 and 1.20.5 but the issue is always the same

</pre></details>

### What did you do?

Specifically, I ran and debugged the code on both OS with VS-Code and its Go extension, but trying to perform a Cross compile for Windows always results on a internal redeclaration error.

Here is the program: 
https://go.dev/play/p/ZJlpl2h6zgb

Xcode and linux dependencies were installed as same as GO , GOROOT and GOPATH configurations.
Then run:
$go mod init FW/m
$go mod tidy
$go build -tags "windows amd64" -o bin/app-amd64.exe main.go 

But during the cross compile process, both terminals, on MacOs and Linux show the same result (see log below).

### What did you expect to see?
I'm just trying to compile and test my program, as one of my imported libs is especifically intended to print a PDF on Windows.

### What did you see instead?
redeclaration error: 
# internal/goos
/usr/local/go/src/internal/goos/zgoos_windows.go:7:7: GOOS redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_darwin.go:7:7: other declaration of GOOS
/usr/local/go/src/internal/goos/zgoos_windows.go:9:7: IsAix redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_darwin.go:9:7: other declaration of IsAix
/usr/local/go/src/internal/goos/zgoos_windows.go:10:7: IsAndroid redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_darwin.go:10:7: other declaration of IsAndroid
/usr/local/go/src/internal/goos/zgoos_windows.go:11:7: IsDarwin redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_darwin.go:11:7: other declaration of IsDarwin
/usr/local/go/src/internal/goos/zgoos_windows.go:12:7: IsDragonfly redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_darwin.go:12:7: other declaration of IsDragonfly
/usr/local/go/src/internal/goos/zgoos_windows.go:13:7: IsFreebsd redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_darwin.go:13:7: other declaration of IsFreebsd
/usr/local/go/src/internal/goos/zgoos_windows.go:14:7: IsHurd redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_darwin.go:14:7: other declaration of IsHurd
/usr/local/go/src/internal/goos/zgoos_windows.go:15:7: IsIllumos redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_darwin.go:15:7: other declaration of IsIllumos
/usr/local/go/src/internal/goos/zgoos_windows.go:16:7: IsIos redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_darwin.go:16:7: other declaration of IsIos
/usr/local/go/src/internal/goos/zgoos_windows.go:17:7: IsJs redeclared in this block
	/usr/local/go/src/internal/goos/zgoos_darwin.go:17:7: other declaration of IsJs
/usr/local/go/src/internal/goos/zgoos_windows.go:17:7: too many errors

**Comment by ianlancetaylor** [comment] 2023-06-21 21:38
> go build -tags "windows amd64" -o bin/app-amd64.exe main.go

This is not what you want.  The effect of this is that you are going to build all Windows files and also all files appropriate for the system on which you are running the go command.  That is why you are seeing redeclaration errors.

Was there some documentation that told you to run this?

What you want instead is to set `GOOS` and possibly `GOARCH` in the environment when running the command line.  For example, when running on a Unix system:

    GOOS=windows GOARCH=amd64 go build -o bin/app-amd64.exe main.go

Closing because this is not a bug.  If you have questions about using Go, please see https://go.dev/wiki/Questions.  Thanks.

**Closed by ianlancetaylor** 2023-06-21 21:38 UTC

**Comment by Ocxal46** [comment] 2023-06-22 03:36
The what? None of your comments helped to solve the issue, but I was able to compile from Linux and Mac adding the tag CGO_ENABLED=1 on the build command as the fyne documentation suggested
