### ISSUE TITLE
cmd/link: nil pointer panic during compile for openbsd/mips64

### ISSUE THREAD

**Issue by calmh** [golang/go#58240] opened 2023-02-02 10:03 UTC
Noticed this on Go 1.19.5, after updating a few dependencies to support Go 1.20.

```
% docker run -it --rm golang:1.19.5
root@d0d4ee0380ce:/go# go version
go version go1.19.5 linux/arm64
(issue also happens on linux/amd64)
root@d0d4ee0380ce:/go# git clone -b linkercrash https://github.com/calmh/syncthing.git
(repo clones)
root@d0d4ee0380ce:/go# cd syncthing/
root@d0d4ee0380ce:/go/syncthing# GOOS=openbsd GOARCH=mips64 go build ./cmd/stdiscosrv/
(build happens)
# github.com/syncthing/syncthing/cmd/stdiscosrv
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15447c]

goroutine 1 [running]:
cmd/link/internal/ld.dynrelocsym(0x40000bc000, 0x2510c?)
	/usr/local/go/src/cmd/link/internal/ld/data.go:853 +0x28c
cmd/link/internal/ld.(*dodataState).dynreloc(0x40006b1b00, 0x40000bc000)
	/usr/local/go/src/cmd/link/internal/ld/data.go:871 +0x8c
cmd/link/internal/ld.(*Link).dodata(0x40000bc000, {0x4002380000, 0x4b89f, 0x4b89f})
	/usr/local/go/src/cmd/link/internal/ld/data.go:1498 +0x384
cmd/link/internal/ld.Main(_, {0x8, 0x20, 0x1, 0x1d, 0x1f, 0x0, {0x0, 0x0}, {0x271699, ...}, ...})
	/usr/local/go/src/cmd/link/internal/ld/main.go:336 +0x12f8
main.main()
	/usr/local/go/src/cmd/link/main.go:72 +0xe98
root@d0d4ee0380ce:/go/syncthing#
```

**Comment by mknyszek** [comment] 2023-02-02 15:10
CC @golang/compiler

**Comment by mknyszek** [comment] 2023-02-02 15:10
CC @golang/mips @golang/openbsd

**Comment by cuonglm** [comment] 2023-02-09 09:50
The CL https://go-review.googlesource.com/c/go/+/233523 introduces this behavior cc @thanm 

Pre-CL, that would be a fatal error.

**Comment by thanm** [comment] 2023-02-09 14:00
@calmh looks like this is actually expected behavior given the current state of openbsd + mips64.

What is happening here is that the code in the  golang.org/x/sys repo has moved forward with switching OpenBSD to use libc as opposed to directly syscall invocation.

The app in question has a reachable calll to golang.org/x/sys/unix.mmap, which results in the following chain of dependent functions being pulled in (this is from the linker's -dumpdep flag):

```
golang.org/x/sys/unix.mmap -> golang.org/x/sys/unix.libc_mmap_trampoline_addr
golang.org/x/sys/unix.libc_mmap_trampoline_addr -> libc_mmap_trampoline
libc_mmap_trampoline -> libc_mmap
```

where libc_mmap is of type SDYNIMPORT (meaning that at runtime its definition will be appearing in a shared library).

The problem here is that although `golang.org/x/sys/unix` has moved ahead, the CLs to support this in the Go linker are stalled. See the stack at https://go.dev/cl/415815 and successors.

It's unfortunate that the golang.org/x/sys/unix change was rolled out before things were ready in the Go linker realm, but it appears that's just what was decided by the OpenBSD maintainers.

I will send a CL to change things so that we get an error in this case as opposed to a crash, but until https://go.dev/cl/415815 and friends are merged, folks will see these same sorts of errors.

**Comment by thanm** [comment] 2023-02-09 14:06
@4a6f656c FYI

**Closed** 2023-02-10 14:29 UTC
Labels: help wanted, OS-OpenBSD, NeedsInvestigation, arch-mips, compiler/runtime
