### ISSUE TITLE
cmd/go: ignore unused modules more intelligently. 

### ISSUE THREAD

**Issue by nrvnrvn** [golang/go#41562] opened 2020-09-22 19:10 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nick.revin/Library/Caches/go-build"
GOENV="/Users/nick.revin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/nick.revin/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/nick.revin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zq/pjk9rp297blc98tc4phgv6b80000gp/T/go-build258952378=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Tried to verify and tidy go modules.

The background:
One of the [direct dependencies of the project](https://github.com/amaizfinance/redis-operator/blob/71e4f9cdc176293779e986c5abea2ffbd7e4059c/go.mod#L9) has an indirect dependency of `bitbucket.org/ww/goautoneg` but it turns out that this project has been removed/abandoned recently.

Moreover, [all the dependencies are vendored](https://github.com/amaizfinance/redis-operator/tree/71e4f9cdc176293779e986c5abea2ffbd7e4059c/vendor) and despite the fact that operator-sdk requires a whole chain of its own dependencies the aforementioned `bitbucket.org/ww/goautoneg` is not actually needed or used since I can't find it in the vendor directory.

Thus the project can be built without issues because all the dependency requirements are met but the `go mod` commands are not working since they cannot find the repository with `bitbucket.org/ww/goautoneg`

This issue looks similar to #26602 but the problem is more subtle. While one of the declared indirect dependencies is actually missing we are not using it anyway.

This change https://go-review.googlesource.com/c/go/+/255960/ introduces the `-e` flag to `mod tidy` and `mod vendor` commands

It would be great to allow similar best effort strategy for other `go mod` subcommands. Because currently if some indirect dependency cannot be loaded or resolved none of the commands can be used. They just print out the failing subtree and exit.

### What did you expect to see?
```
$ go mod verify -e
not all modules verified
go: github.com/operator-framework/operator-sdk@v0.10.0 requires
	github.com/operator-framework/operator-lifecycle-manager@v0.0.0-20190128024246-5eb7ae5bdb7a requires
	github.com/operator-framework/operator-registry@v1.0.4 requires
	github.com/operator-framework/operator-lifecycle-manager@v0.0.0-20190105193533-81104ffdc4fb requires
	bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
$ # does best effort package verification ignoring the failing path.

```

### What did you see instead?
```
$ go mod verify
go: github.com/operator-framework/operator-sdk@v0.10.0 requires
	github.com/operator-framework/operator-lifecycle-manager@v0.0.0-20190128024246-5eb7ae5bdb7a requires
	github.com/operator-framework/operator-registry@v1.0.4 requires
	github.com/operator-framework/operator-lifecycle-manager@v0.0.0-20190105193533-81104ffdc4fb requires
	bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
```

**Comment by bcmills** [comment] 2020-09-22 20:13
Duplicate of #36460

**Closed by bcmills** 2020-09-22 20:13 UTC

**Comment by bcmills** [comment] 2020-09-22 20:14
(That issue has been basically my main project for the year, and this example is exactly the kind of use-case we intend to address with it.)
