### ISSUE TITLE
x/playground: invalid output when using slices of length > 1e6 

### ISSUE THREAD

**Issue by Nasfame** [golang/go#64344] opened 2023-11-22 19:09 UTC
### Go version

gotip

### Reproducibility

- [X] Does this issue reproduce with the latest release?

### What operating system and processor architecture are you using (`go env`)?

```shell
nil
```

### What did you do?

https://go.dev/play/p/Rkc3h35UsSm?v=gotip works

https://go.dev/play/p/EMXl5zWnBBM?v=gotip but doesn't

Dups #64339.

### What did you expect to see?

```
last slice 9999999
end
```

### What did you see instead?

```
Program exited.
```

**Comment by seankhliao** [comment] 2023-11-22 19:48
https://gotipplay.golang.org/p/EMXl5zWnBBM?v=gotip

**Comment by seankhliao** [comment] 2023-11-22 19:49
Duplicate of #53307

**Closed by seankhliao** 2023-11-22 19:49 UTC
