### ISSUE TITLE
cmd/go/internal/lockedfile: TestSpuriousEDEADLK flaky on plan9-arm since Oct. 7

### ISSUE THREAD

**Issue by bcmills** [golang/go#41952] opened 2020-10-13 15:16 UTC
I'm not sure whether this is due to a change in the builder or a change in the runtime or standard library, but `lockedfile.TestSpuriousEDEADLK` has been failing sporadically on the `plan9-arm` builder, apparently due to the failure of a `*lockedfile.File` to provide the expected mutual-exclusion when open for writing.

The first such failure occurred at [CL 260137](https://golang.org/cl/260137), but it's not obvious to me how that could be related. (The `plan9-386-0intro` builder started working again around then — do the `-386-0intro` and `-arm` builders share an underlying filesystem?)

CC @millerresearch @fhs @0intro 

```
--- FAIL: TestSpuriousEDEADLK (0.04s)
    lockedfile_test.go:255: Edit B unexpectedly did not block
```

[2020-10-12T18:31:36-8994607/plan9-arm](https://build.golang.org/log/e21dd0c2bf9a9aea21adc0b0a97186b1f03d21fb)
[2020-10-12T18:31:29-112c4d5/plan9-arm](https://build.golang.org/log/7af71f558bf34d218aa83276fbc602ac1d1ba8c5)
[2020-10-12T18:31:10-7b77ff4/plan9-arm](https://build.golang.org/log/8638c13e5d12c645e41af09365d48a9fbdad2c12)
[2020-10-12T18:31:01-5acec48/plan9-arm](https://build.golang.org/log/2289d8e2ca7bdf741ada5ab7ddc1f51ef7677198)
[2020-10-12T16:12:25-349a287/plan9-arm](https://build.golang.org/log/5fcab0cc56d422d9f9d87c018559a3ace89768eb)
[2020-10-10T00:55:54-d317ba5/plan9-arm](https://build.golang.org/log/88c38557cbc17225e59fa1087a78a6a83087240b)
[2020-10-09T02:49:19-2be7788/plan9-arm](https://build.golang.org/log/b84067068ee2219dc649ec11223e2dc47c5a6f06)
[2020-10-09T02:14:32-8f26b57/plan9-arm](https://build.golang.org/log/b33a73e1bd3dca8f192c26e4fd6c94e35f9dbc40)
[2020-10-09T01:09:06-f8df205/plan9-arm](https://build.golang.org/log/868e65556a14ac349a074c3b5e2690c1d447f5f5)
[2020-10-07T20:18:43-3f7b4d1/plan9-arm](https://build.golang.org/log/d4305aa304822746f7a54232ce464bcbd276f0fc)
[2020-10-07T18:56:58-5c1567c/plan9-arm](https://build.golang.org/log/395a134902feb64c46280eb55838b7b405d9f5cf)
[2020-10-07T14:57:54-67edc0e/plan9-arm](https://build.golang.org/log/158cd166e34b29092a7a0bd0a415e8ab666a93a8)

**Comment by 0intro** [comment] 2020-10-13 20:33
While the plan9/386 builder is currently running a local ramfs (an "in memory" file system), I think the plan9/arm builders import their file system from a remote file server, so it may behave differently.

**Comment by millerresearch** [comment] 2020-10-13 21:23
In this test the file being locked is in /tmp, which the plan9_arm builders also mount on ramfs.

**Comment by bcmills** [comment] 2021-11-02 15:48
`greplogs --dashboard -md -l -e 'FAIL: TestSpuriousEDEADLK' --since=2021-01-01`

<details>

[2021-10-04T22:00:19-739328c/plan9-arm](https://build.golang.org/log/2392a8b3505c87a135f728cc60e6c500ea64a0bd)
[2021-09-23T21:59:30-4e308d7/plan9-arm](https://build.golang.org/log/d769cfce58dbd6d69c8b1c93af3ba74777a5dde3)
[2021-09-17T18:51:48-7f36ef0/plan9-arm](https://build.golang.org/log/f8076ed00342d39efda365d59ad4b52f77172e43)
[2021-09-15T00:04:48-cb4e1de/plan9-arm](https://build.golang.org/log/adb42a3088381af9af449c6f2bb2e69e086d2975)
[2021-09-07T22:23:36-a9a01a3/plan9-arm](https://build.golang.org/log/c36805b186d785fa356b4da588b9763a2e89558f)
[2021-09-07T03:56:13-6226020/plan9-arm](https://build.golang.org/log/e64f43a812f6bef50afbce79c86b9ee3c7835591)
[2021-09-02T16:15:00-d01388b/plan9-arm](https://build.golang.org/log/1ead2eed594cc7bbc05375ed6640c5f9f42593ef)
[2021-06-21T16:58:36-16e82be/plan9-arm](https://build.golang.org/log/51014303b14dea184380f802b278e9dc5dadeccf)
[2021-06-21T14:57:47-85a2e24/plan9-arm](https://build.golang.org/log/4ea9dc76ce846bea3c3b1a80d155158454bf6b09)
[2021-06-16T14:23:50-a6a853f/plan9-arm](https://build.golang.org/log/644a0961d90f44c176596f85713c6efa3c71d6e8)
[2021-06-15T20:59:42-d77f4c0/plan9-arm](https://build.golang.org/log/6c46b84a56a2f42e92f43b5c8364f35b925bf126)
[2021-06-07T21:18:03-dc8b558/plan9-arm](https://build.golang.org/log/15a0ce17ff5295d17bb406a8262b9ad3c7905d9f)
[2021-06-04T17:33:24-831f937/plan9-arm](https://build.golang.org/log/5bb41bea2c6472d0bcb7c728e7196f2e5ea66497)
[2021-05-21T23:46:07-f87194c/plan9-arm](https://build.golang.org/log/6084909da8decb09defcc3d9c04c9313f61928b6)
[2021-05-17T16:02:12-b1aff42/plan9-arm](https://build.golang.org/log/311dbc46c4bae39a2dd5a780118ccd5939f358f1)
[2021-05-14T19:27:25-02699f8/plan9-arm](https://build.golang.org/log/071196f8e4690301b1353d3d13714fded7e0fe66)
[2021-02-01T16:54:54-0b6cfea/plan9-arm](https://build.golang.org/log/ac517bfda4546bd0915cff91cddb1ec50ac5934e)
[2021-02-01T15:52:59-26e29aa/plan9-arm](https://build.golang.org/log/6386a6a77a8233ac80746458a79bf27c1667fc9d)
[2021-01-26T00:02:49-cf263e9/plan9-arm](https://build.golang.org/log/570ed0f601c6849ec351a36445c863051665df96)
[2021-01-25T19:40:02-54514c6/plan9-arm](https://build.golang.org/log/adafcb428e4050353471296ba3b77e9f9af43955)
[2021-01-22T23:03:58-25c39e4/plan9-arm](https://build.golang.org/log/309469b986b807b4f94903330cf3604a0f805cda)
[2021-01-22T21:16:10-a2cef9b/plan9-arm](https://build.golang.org/log/97868fa29039de790d3846088d673de4040bc2ef)
[2021-01-22T18:58:08-dab3e5a/plan9-arm](https://build.golang.org/log/01cda00095c7f7b1ed2f74feeb6a70e430fbe392)
[2021-01-22T16:23:59-7ece3a7/plan9-arm](https://build.golang.org/log/de3858add1e46c9c844383c7fff4776c7cd687c2)
[2021-01-21T20:47:45-e2b4f1f/plan9-arm](https://build.golang.org/log/797f6560e0d281bc38e356c51c37b755502abe28)
[2021-01-21T19:15:21-3c2f11b/plan9-arm](https://build.golang.org/log/63fb21e5646e20ada61bc311637614fdb7ae61ab)
[2021-01-21T19:08:04-46e2e2e/plan9-arm](https://build.golang.org/log/7c96e8e4a1d44e8f943c8b3ea678abad168e96a9)
[2021-01-20T22:16:54-ecf4ebf/plan9-arm](https://build.golang.org/log/6a9fd51f19471fb38c16868234b52fd2a54ccb42)
[2021-01-20T17:37:54-6e243ce/plan9-arm](https://build.golang.org/log/60c6aceb2f609ddff7d0940470458c3c9faf7949)
[2021-01-20T14:59:52-be28e5a/plan9-arm](https://build.golang.org/log/2e150def2906b66960e0ed16bed3108a22296b35)
[2021-01-14T21:55:29-eb33002/plan9-arm](https://build.golang.org/log/be0faeee89ab27b8e23163dd75063d0a57cb72aa)
[2021-01-14T17:23:11-d9b79e5/plan9-arm](https://build.golang.org/log/dd81d9e0235fba4f53db13d7a79f1f88c96edc48)
[2021-01-13T23:37:31-7eb31d9/plan9-arm](https://build.golang.org/log/781ba47cc33ceeec482b477286099936adbd84d6)
[2021-01-12T21:39:59-ba76567/plan9-arm](https://build.golang.org/log/390e0b088fcfa1ce68ec406f3f41e9aac22d22d4)
[2021-01-11T21:34:46-81ea89a/plan9-arm](https://build.golang.org/log/2d56e7ea51479ea8eb5bd957bbde2e3f17a50e70)
[2021-01-08T17:08:44-e65c543/plan9-arm](https://build.golang.org/log/56ad3bd2a182b146f907e39c268b6ae12e7874bf)
[2021-01-08T01:33:44-54bd1cc/plan9-arm](https://build.golang.org/log/fbbcb380c11d6c087c66a9ec94c43e9072d915b0)
[2021-01-07T22:28:57-9b55088/plan9-arm](https://build.golang.org/log/3d1bc20f8cf696a5f3d16b2f77320e32f43fc337)
[2021-01-07T18:56:09-7cee66d/plan9-arm](https://build.golang.org/log/485616b330075fd12b238370549194a823e77ab3)
[2021-01-05T20:54:17-1b85e7c/plan9-arm](https://build.golang.org/log/f65069d044e215f32ddd3e311c707e8ee374a20b)

</details>

**Comment by millerresearch** [comment] 2021-11-03 16:44
May be related to #48416 which also involves locking a file on /tmp.

I'll try moving /tmp off ramfs on the plan9-arm builders for a while and see whether the failures stop.

**Comment by millerresearch** [comment] 2022-07-17 09:34
Duplicate of #48416.

**Closed by millerresearch** 2022-07-17 09:34 UTC
Labels: OS-Plan9, NeedsInvestigation
