### ISSUE TITLE
encoding/json: Decoder return errors that are not intuitive

### ISSUE THREAD

**Issue by Aoang** [golang/go#54044] opened 2022-07-25 13:09 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, i guess it's always exist.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Aoang\AppData\Local\go-build
set GOENV=C:\Users\Aoang\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Aoang\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Aoang\go
set GOPRIVATE=
set GOPROXY=direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Aoang\AppData\Local\Temp\go-build933196117=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Test the results of `json.Decoder` in different situations.

[https://go.dev/play/p/sznsNWE0Y4f](https://go.dev/play/p/sznsNWE0Y4f)

### What did you expect to see?

I don't know. But I'm guessing it shouldn't be like this.

### What did you see instead?

```go
package main

import (
	"encoding/json"
	"log"
	"strings"
)

func main() {
	s := Data{}
	log.Println(UseInterface(s))
}

type Data struct{}

func (d Data) I1() {}

type Itr interface{ I1() }

func UseInterface(c Itr) error {
	return json.NewDecoder(strings.NewReader("{}")).Decode(&c)
}
```

Maybe its should be like `json: Unmarshal(non-pointer main.Itr)`.

**Comment by seankhliao** [comment] 2022-07-25 19:26
Duplicate of #26946

**Closed by seankhliao** 2022-07-25 19:26 UTC
