### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by lg430** [golang/go#31336] opened 2019-04-08 07:05 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br>
<pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/work/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/go"
GOPROXY="https://goproxy.io"
GORACE=""
GOROOT="/opt/go/dl/go1.12/go"
GOTMPDIR=""
GOTOOLDIR="/opt/go/dl/go1.12/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build907569483=/tmp/go-build"

</pre>
</details><details>
<summary><code>uname </code> Output</summary><br>
<pre>
$ uname -a
Linux xx.org 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
</pre>
</details>

### What did you do?
go build

### What did you expect to see?
build success

### What did you see instead?
\# hbg_go_houseapp
/opt/go/dl/go1.12.2/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: BFD version 2.20.51.0.2-5.42.el6 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size
/usr/bin/ld: Please report this bug.
collect2: ld return 1

**Comment by agnivade** [comment] 2019-04-08 09:09
Please mention what it is _exactly_ that you did. We need the repro steps or a sample code that we can use to reproduce the issue ourselves.

**Comment by aronatkins** [comment] 2019-04-08 15:13
Given the `hello.go` from #31293 on a CentOS6 system using go-1.12.2:

```
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-618077956/000005.o(.text+0x74): unresolvable H��@�>H��FH��H��H��@�~�F�H��@�~H��8�H��H��0�FH��H��(�FH��H�� �FH��H���FH��H���FH��H��F�fD relocation against symbol `stderr@@GLIBC_2.2.5'
/usr/bin/ld: BFD version 2.20.51.0.2-5.48.el6_10.1 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.

collect2: ld returned 1 exit status
```

```
$ ld -v
GNU ld version 2.20.51.0.2-5.48.el6_10.1 20100205
```

**Comment by agnivade** [comment] 2019-04-08 15:49
So then this is a duplicate of #31293 ?

Your error seems to be slightly different than OP's though. In any case, I am unable to reproduce this in Ubuntu 18.04.

@ianlancetaylor

**Comment by aronatkins** [comment] 2019-04-08 16:01
@agnivade - Both the OP and my errors are from "el6" - ELPA packages for RHEL/CentOS 6. Maybe the slightly different output is caused by "2.20.51.0.2-5.42.el6 20100205" vs "2.20.51.0.2-5.48.el6_10.1 20100205" patches? The reported lineno and function are the same. Maybe the OP left out one line because it had nonascii characters?

I cannot say if this is a complete duplicate of #31293. Feels connected, though.

**Comment by aronatkins** [comment] 2019-04-08 16:16
Here is a `Dockerfile` that reproduces the problem:

```dockerfile
FROM centos:centos6.10

RUN yum -y install gcc

ENV GOLANG_VERSION 1.12.2
ENV GOLANG_DOWNLOAD_SHA256 f28c1fde8f293cc5c83ae8de76373cf76ae9306909564f54e0edcf140ce8fe3f
RUN curl -fsSL "https://golang.org/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz" -o golang.tar.gz \
    && echo "$GOLANG_DOWNLOAD_SHA256  golang.tar.gz" | sha256sum -c - \
    && tar -C /usr/local -xzf golang.tar.gz \
    && rm golang.tar.gz
ENV PATH="$PATH:/usr/local/go/bin"

COPY hello.go hello.go

RUN go build hello.go
```

It expects the following `hello.go` (from #31293):

```golang
package main

// const int x = 42;
import "C"

import "fmt"

func main() {
	fmt.Println(int(C.x))
}
```

Given a directory containing this `Dockerfile` and `hello.go`:

```
$ docker build -t foo .
....
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-843872773/000005.o(.text+0x74): unresolvable H��@�>H��FH��H��H��@�~�F�H��@�~H��8�H��H��0�FH��H��(�FH��H�� �FH��H���FH��H���FH��H��F�fD relocation against symbol `stderr@@GLIBC_2.2.5'
/usr/bin/ld: BFD version 2.20.51.0.2-5.48.el6 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.

collect2: ld returned 1 exit status

The command '/bin/sh -c go build hello.go' returned a non-zero code: 2
```

**Comment by ianlancetaylor** [comment] 2019-04-08 17:27
I'm confident that this is a dup of #31293, so closing.

**Closed by ianlancetaylor** 2019-04-08 17:27 UTC
Labels: WaitingForInfo

**Comment by vansnyder** [comment] 2019-07-31 19:10
Nice that it's closed, but... what's the work around?  I'm not allowed to have the root password.  Eliminating -static seems to work, but what if I need a static executable?

**Comment by vansnyder** [comment] 2019-07-31 19:44
Removing -static works around the BFD error.  I can get a static executable using -Bstatic.  "man ld" says they're the same.  Huh?

**Comment by ianlancetaylor** [comment] 2019-07-31 20:05
@vansnyder Which version of Go are you using?  See #31293 for more details.

**Comment by vansnyder** [comment] 2019-07-31 22:46
On Wed, 2019-07-31 at 13:08 -0700, Ian Lance Taylor wrote:
> @vansnyder Which version of Go are you using? See #31293 for more
> details.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

The problem is in ld.  I'm not using Go.  I found that -static caused
the problem, but I can get a static build using -Bstatic.  The "man"
page says they're equivalent.  Huh?

**Comment by ianlancetaylor** [comment] 2019-07-31 23:44
@vansnyder This is the Go issue tracker, so if you aren't using Go, you are in the wrong place.
