### ISSUE TITLE
net: Resolver does not appear to use its dialer function on Windows

### ISSUE THREAD

**Issue by HouzuoGuo** [golang/go#33621] opened 2019-08-13 12:17 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\howard\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\howard\go
set GOPROXY=
set GORACE=
set GOROOT=c:\go
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\howard\AppData\Local\Temp\go-build943471142=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Run this code snippet
<pre>
package main

import (
	"context"
	"fmt"
	"net"
)

func main() {
	resolver := &net.Resolver{
		PreferGo:     true,
		StrictErrors: true,
		Dial: func(ctx context.Context, network, address string) (conn net.Conn, e error) {
			panic(nil)
		},
	}
	result, err := resolver.LookupHost(context.Background(), "google.com")
	fmt.Println(result, err)
}
</pre>

### What did you expect to see?

A panic, as correctly demonstrated by running the snippet under Linux:
<pre>
panic: nil

goroutine 6 [running]:
main.main.func1(0x53caa0, 0xc00007a300, 0x51a125, 0x3, 0xc0000183f0, 0xe, 0x42aedc, 0xc0000d6ad0, 0xc00007a310, 0xc000001b00)
        /home/howard/main.go:14 +0x29
net.(*Resolver).dial(0xc00000e0a0, 0x53caa0, 0xc00007a300, 0x51a125, 0x3, 0xc0000183f0, 0xe, 0xc0000125c0, 0x0, 0x0, ...)
        /home/howard/go/src/net/lookup_unix.go:67 +0x226
net.(*Resolver).exchange(0xc00000e0a0, 0x53ca60, 0xc0000180e0, 0xc0000183f0, 0xe, 0x632e656c676f6f67, 0x2e6d6f, 0x0, 0x0, 0x0, ...)
        /home/howard/go/src/net/dnsclient_unix.go:144 +0x280
net.(*Resolver).tryOneName(0xc00000e0a0, 0x53ca60, 0xc0000180e0, 0xc00009e140, 0xc000018630, 0xb, 0x1c, 0x0, 0x0, 0x0, ...)
        /home/howard/go/src/net/dnsclient_unix.go:244 +0x325
net.(*Resolver).goLookupIPCNAMEOrder.func1(0xc00000e0a0, 0x53ca60, 0xc0000180e0, 0xc00009e140, 0xc0000125a0, 0xc00007a2a0, 0x1c)
        /home/howard/go/src/net/dnsclient_unix.go:584 +0x90
created by net.(*Resolver).goLookupIPCNAMEOrder
        /home/howard/go/src/net/dnsclient_unix.go:583 +0x285
exit status 2
</pre>

### What did you see instead?

On Windows, the snippet never touched the dialer function and successfully resolves the domain name:

<pre>
[216.58.207.206] <nil>
</pre>

**Comment by tmthrgd** [comment] 2019-08-13 13:49
This is a duplicate of #29621, #33086 and #33097.

The [net package docs](https://golang.org/pkg/net/#hdr-Name_Resolution) currently say:
> "On Windows, the resolver always uses C library functions, such as GetAddrInfo and DnsQuery."

**Comment by HouzuoGuo** [comment] 2019-08-13 18:01
Thanks very much @tmthrgd. To help fellow users of Go, would it be better to note down the restriction in the doc of Dial function in addition to package description?

**Comment by bradfitz** [comment] 2022-04-20 04:04
Closing as a dup of #33097. (and https://github.com/golang/go/issues/29621, https://github.com/golang/go/issues/33086, as @tmthrgd pointed out).

#33097 has a pending approved fix and is about to be submitted. For people finding this in the future, the fix should be in Go 1.19. (Check the release notes when it comes out.)

**Closed by bradfitz** 2022-04-20 04:04 UTC
Labels: OS-Windows, NeedsInvestigation
