### ISSUE TITLE
String concat not working as intended after reading and replacing strings from file.

### ISSUE THREAD

**Issue by Nishan8583** [golang/go#44752] opened 2021-03-03 03:44 UTC
<pre>
go version go1.16 windows/amd64

After reading the contents of a file, and replacing the new line character "\n" with nothing. And I concat the resulting string with some other string, the final string will have initial strings replaced rather then being concated.

```
package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"strings"
)

func main() {
	file, err := os.Open(`names.txt`)
	if err != nil {
		log.Fatal("Could not open file", err)

	}
	defer file.Close()
	reader := bufio.NewReader(file)

	for {
		content, err := reader.ReadString('\n')
		if err != nil {
			break
		}

		content = strings.Replace(content, " ", "", -1)
		content = strings.Replace(content, "\n", "", -1)

		fmt.Println(content + "--")

	}

}
```

If the file had content "lmao" the result should have been "lmao--",
but instead the result is "--mao"

**Comment by randall77** [comment] 2021-03-03 03:59
I cannot reproduce on darwin/amd64 or linux/amd64. Is this something particular with Windows?
Windows newlines are `\r\n`. The replace leaves a naked `\r` - maybe that is the culprit?

**Comment by AlexRouSg** [comment] 2021-03-03 04:34
I can confirm it is due to `\r\n`. 
If you changed the `fmt.Println` to `fmt.Printf("%q\n", content+"--")`
On windows it prints `"lmao\r--"` (assuming file was created with windows line endings)

**Comment by randall77** [comment] 2021-03-03 04:43
Ok, not a bug. Closing.

**Closed by randall77** 2021-03-03 04:43 UTC

**Comment by Nishan8583** [comment] 2021-03-04 02:46
thanks
