### ISSUE TITLE
go work: init adds directories in a format edit can't understand

### ISSUE THREAD

**Issue by zellyn** [golang/go#51619] opened 2022-03-11 19:38 UTC
### What version of Go are you using (`go version`)?

<pre>
go version devel go1.18-a5c0b19 Sun Jan 30 02:29:51 2022 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Not sure

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/zellyn/gh/yaml-edit/.hermit/go/bin"
GOCACHE="/Users/zellyn/Library/Caches/go-build"
GOENV="/Users/zellyn/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zellyn/Development/go/pkg/mod"
GONOPROXY="*.sqcorp.co,github.com/squareup"
GONOSUMDB="*.sqcorp.co,github.com/squareup"
GOOS="darwin"
GOPATH="/Users/zellyn/Development/go"
GOPRIVATE="*.sqcorp.co,github.com/squareup"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/zellyn/Library/Caches/hermit/pkg/go@tip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/zellyn/Library/Caches/hermit/pkg/go@tip/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="devel go1.18-a5c0b19 Sun Jan 30 02:29:51 2022 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK="/Users/zellyn/gh/yaml-edit/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vt/xwmzzrzs3dl3pz9d1yqtrtl80000gn/T/go-build2205153915=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
<pre>
$ go work init
$ cat go.work
go 1.18
$ go work use -r .
$ cat go.work
go 1.18

use (
	go-yaml
	go-yaml/benchmarks
	yfix
)
$ go work edit -dropuse yfix
$ cat go.work
go 1.18

use (
	go-yaml
	go-yaml/benchmarks
	yfix
)
$ sed -i'' -e 's|yfix|./yfix|' go.work 
$ cat go.work
go 1.18

use (
	go-yaml
	go-yaml/benchmarks
	./yfix
)
$ go work edit -dropuse yfix
$ cat go.work
go 1.18

use (
	go-yaml
	go-yaml/benchmarks
)
</pre>

### What did you expect to see?
go work edit could remove directories

### What did you see instead?
It couldn't

**Comment by seankhliao** [comment] 2022-03-11 20:05
Duplicate of #51449

Fixed on tip and release branch

**Closed by seankhliao** 2022-03-11 20:05 UTC
