### ISSUE TITLE
Removal of ++/-- and := operators. 

### ISSUE THREAD

**Issue by teovilo** [golang/go#64304] opened 2023-11-21 05:41 UTC
In order to be consistent Go's philosophy of operator simplicity, the increment/decrement operators (`++` and `--`) and the inference operator (`:=`) must be removed.

The language creators specifically state that operators such the ternary conditional (`?`) were omitted because it can create "unclear" expressions for new programmers. This justification holds true for `++` and `:=` operators which only exist to decrease code verbosity and are not intuitively understood by new programmers. The creators of Python omitted increment/decrement operators for the same reason that the creators of Go omitted the ternary conditional, which creates an outright contradiction of Go's design.

[https://go.dev/doc/faq#Does_Go_have_a_ternary_form](https://go.dev/doc/faq#Does_Go_have_a_ternary_form)

Alternatively, contemporary expressions such as ternary conditionals should be added to the language spec to and abandon the facade that certain expressions were included or omitted for any reason other than opinionated design. Note that ternary conditional expressions don't need to make use of the `?` symbol, instead it can be done with `if...else` as follows: `[on_true] if [expression] else [on_false]` which is very intuitive and is visually consistent with Go's existing syntax.

**Comment by seankhliao** [comment] 2023-11-21 08:02
Duplicate of #64278

**Closed by seankhliao** 2023-11-21 08:02 UTC
Labels: pkgsite
