### ISSUE TITLE
x/build: have more than 1 macOS 12.0 Monterey builder (arm64/amd64)

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#49149] opened 2021-10-25 16:18 UTC
Apple has release macOS 12.0 on October 25, 2021. We plan to provide this builder before Go 1.18 is released. Builders should be added for both the arm64 and amd64 architecture.

@golang/release

**Comment by heschi** [comment] 2021-11-18 23:00
The new build is up and passing using `MallocNanoZone=0`. Only one machine; I'll scale it up tomorrow probably.

**Comment by dmitshur** [comment] 2021-12-02 17:23
Issue #46239 is the cause of the new macOS 12 arm64 builder [consistently failing](https://github.com/golang/go/issues/49926) on the 1.17 release branch. Interestingly, that same test is not failing on tip (and is not being skipped).

**Comment by heschi** [comment] 2021-12-07 19:51
@toothrot -- anything left to do here? @dmitshur says we're not tracking health of this host type yet.

**Comment by dmitshur** [comment] 2021-12-07 20:35
> not tracking health

To expand on this, the "macOS ARM64 (M1 Mac minis)" health item in https://farmer.golang.org/#health is tracking the health of `host-darwin-arm64-12_0-toothrot` (this builder), but not the `host-darwin-arm64-11_0-toothrot` one which ended up staying around. If both continue to exist, it would help to track both. Relevant code is [here](https://cs.opensource.google/go/x/build/+/master:cmd/coordinator/status.go;l=374-377;drc=b2616996cd46cf36ff8055209057e4d9da6117d3).

**Comment by toothrot** [comment] 2021-12-14 19:37
Todo:
- Update the status check
- Remove knownIssue

**Comment by ianlancetaylor** [comment] 2022-01-29 00:28
@golang/release  This is in the 1.18 milestone; time to move to 1.19?  Thanks.

**Comment by dmitshur** [comment] 2022-02-15 18:06
Since this isn't a release-blocker for 1.18 now and the fix will be in x/build, moving to Unreleased milestone.

**Comment by heschi** [comment] 2022-04-27 20:58
@toothrot We've got 3 darwin-arm64 up for each of macOS 11 and 12. Think we can close this issue?

**Closed** 2022-05-13 19:53 UTC
Labels: OS-Darwin, Builders, NeedsFix, new-builder
