### ISSUE TITLE
net/http: does not preserve backslash from FormFile header when Filename contains Chinese

### ISSUE THREAD

**Issue by lianzhao** [golang/go#25888] opened 2018-06-14 12:15 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.4 darwin/amd64

### Does this issue reproduce with the latest release?
Have not tested yet

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/lianzhao/work"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3x/fvc3fcrs5139r6g4k36sxl_40000gn/T/go-build489938146=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?
Sent a form post request to upload a file with MSIE.  Same issue with #15664 
Except that my file name was in Chinese: `C:\新建文件件\中文第二次测试.mp4`

### What did you expect to see?
I expected that `consumeValue` function in `src/mime/mediatype.go` returns `中文第二次测试.mp4`

### What did you see instead?
It returned `C:新建文件件中文第二次测试.mp4`
![image](https://user-images.githubusercontent.com/536786/41411382-38e77dbc-700f-11e8-8ab5-be79846fcc14.png)

**Comment by agnivade** [comment] 2018-06-14 15:23
Can you try with 1.10.3 ?

Also, please post a self-contained example which can be reproduced, so that it is easy for us to investigate. Thanks.

**Comment by opennota** [comment] 2018-06-15 01:35
The problem here is `consumeValue` assuming one-byte encoding: https://github.com/golang/go/blob/c12399fffb6ff9fb947a10e445fdfdc62c697e2c/src/mime/mediatype.go#L283

**Comment by agnivade** [comment] 2018-06-15 03:46
Thanks. Marking as 1.12 because 1.9 also has same behavior. /cc @bradfitz

**Closed** 2018-09-24 16:15 UTC
Labels: NeedsFix
