### ISSUE TITLE
net/http: race in http2Transport

### ISSUE THREAD

**Issue by vadmeste** [golang/go#31192] opened 2019-04-01 20:11 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.1 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vadmeste/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vadmeste/work/gospace"
GOPROXY=""
GORACE=""
GOROOT="/home/vadmeste/work/go"
GOTMPDIR=""
GOTOOLDIR="/home/vadmeste/work/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build457736797=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
1. Generate a self signed certificate:
```
$ openssl req -newkey rsa:2048 -nodes -keyout private.key -x509 -days 365 -out public.crt -subj "/C=US/ST=state/L=location/O=organization/CN=localhost"
```

2. Ask the OS to trust the generated self signed certificate
```
$ # Tested under Ubuntu
$ sudo cp public.crt /usr/local/share/ca-certificates/
$ sudo update-ca-certificates
```

3. Run the following test code: https://play.golang.org/p/mxV6_0TW-Ji
```
$ go run -race testcode.go
```

### What did you expect to see?
No race detector warning

### What did you see instead?

```
WARNING: DATA RACE
Write at 0x00c00180d1b8 by goroutine 17:
  main.main.func2()
      /home/vadmeste/work/go/src/bytes/buffer.go:102 +0x186

Previous write at 0x00c00180d1b8 by goroutine 203:
  bytes.(*Buffer).Read()
      /home/vadmeste/work/go/src/bytes/buffer.go:310 +0x266
  io/ioutil.(*nopCloser).Read()
      <autogenerated>:1 +0x87
  net/http.(*http2clientStream).writeRequestBody()
      /home/vadmeste/work/go/src/net/http/h2_bundle.go:7664 +0x64d
  net/http.(*http2Transport).getBodyWriterState.func1()
      /home/vadmeste/work/go/src/net/http/h2_bundle.go:8878 +0x13d

Goroutine 17 (running) created at:
  main.main()
      /home/vadmeste/x/testcode.go:48 +0x277

Goroutine 203 (running) created at:
  net/http.http2bodyWriterState.scheduleBodyWrite()
      /home/vadmeste/work/go/src/net/http/h2_bundle.go:8925 +0x12f
  net/http.(*http2ClientConn).roundTrip()
      /home/vadmeste/work/go/src/net/http/h2_bundle.go:7465 +0x90f
  net/http.(*http2Transport).RoundTripOpt()
      /home/vadmeste/work/go/src/net/http/h2_bundle.go:6867 +0x23d
  net/http.http2noDialH2RoundTripper.RoundTrip()
      /home/vadmeste/work/go/src/net/http/h2_bundle.go:6829 +0x4c
  net/http.(*Transport).roundTrip()
      /home/vadmeste/work/go/src/net/http/transport.go:430 +0x14d9
  net/http.(*Transport).RoundTrip()
      /home/vadmeste/work/go/src/net/http/roundtrip.go:17 +0x42
  net/http.send()
      /home/vadmeste/work/go/src/net/http/client.go:250 +0x6a9
  net/http.(*Client).send()
      /home/vadmeste/work/go/src/net/http/client.go:174 +0x1cb
  net/http.(*Client).do()
      /home/vadmeste/work/go/src/net/http/client.go:641 +0x4ef
  main.main.func2()
      /home/vadmeste/work/go/src/net/http/client.go:509 +0x4e0
```

**Comment by dgryski** [comment] 2019-04-01 22:34
@bradfitz @tombergan

**Comment by fraenkel** [comment] 2019-04-10 01:10
@bradfitz This might be the same issue with http. There is no guarantee that the bodyWriter is complete when roundtrip exits.

**Comment by odeke-em** [comment] 2019-10-12 03:42
Here is a standalone adapted from @vadmeste's original program but here one doesn't have to manually create certificates but also it is reduced down
```go
package main

import (
	"bytes"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"net/http"
	"net/http/httptest"

	"golang.org/x/net/http2"
)

func main() {
	cst := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Pong")
	}))
	if err := http2.ConfigureServer(cst.Config, new(http2.Server)); err != nil {
		log.Fatalf("Failed to configure http2 server: %v", err)
	}
	cst.TLS = cst.Config.TLSConfig

	tr := &http.Transport{TLSClientConfig: cst.Config.TLSConfig}
	if err := http2.ConfigureTransport(tr); err != nil {
		log.Fatalf("Failed to configure http2 transport: %v", err)
	}
	tr.TLSClientConfig.InsecureSkipVerify = true
	cst.StartTLS()
	defer cst.Close()

	// Then finally create the HTTP client with the HTTP/2 transport.
	client := &http.Client{Transport: tr}

	for i := 0; i < 3; i++ {
		// Fill buf with data
		buf := bytes.NewBuffer(bytes.Repeat([]byte("A"), 128*1024))

		// Make a POST http call and read and discard response
		req, err := http.NewRequest("POST", cst.URL, buf)
		resp, err := client.Do(req)
		if err != nil {
			log.Fatalln(err)
		}
                if _, err := io.Copy(ioutil.Discard, resp.Body); err != nil {
			log.Fatalln(err)
		}
		resp.Body.Close()

		// Accessing buf here causes a RACE WARNING
		buf.Reset()
		fmt.Printf(".")
	}
}
```

**Comment by pmalek** [comment] 2020-06-14 11:27
@fraenkel Modifying @odeke-em 's example to use http like so:

```golang
package main

import (
	"bytes"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"net/http"
	"net/http/httptest"
)

func main() {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Pong")
	}))
	defer srv.Close()

	client := srv.Client()

	for i := 0; i < 100; i++ {
		// Fill buf with data
		buf := bytes.NewBuffer(bytes.Repeat([]byte("A"), 128*1024))

		// Make a POST http call, read and discard response
		req, err := http.NewRequest("POST", srv.URL, buf)
		resp, err := client.Do(req)
		if err != nil {
			log.Fatalln(err)
		}
		if _, err := io.Copy(ioutil.Discard, resp.Body); err != nil {
			log.Fatalln(err)
		}
		resp.Body.Close()

		buf.Reset()
		fmt.Printf(".")
	}
}
```

I do not observe a data race.

The original issue is still present in gotip from `go version devel +bd486c3 Sat Jun 13 16:03:19 2020 +0000 linux/amd64` and in `1.14.2`.

> There is no guarantee that the bodyWriter is complete when roundtrip exits.
I'm wondering what might be the fix for this. Could we make it so that the `bodyWriter` *is* complete when roundtrip exits?

**Comment by odeke-em** [comment] 2020-06-14 11:34
@pmalek <https://github.com/pmalek> unfortunately your modification
 doesn’t create an HTTP/2 server and transport. You either want to have the
long setup version I provided, or if you are using Go1.14, use and
Unstarted httptest.Server and then enable EnableHTTP2 = true and finally
srv.StartTLS() as we do here
https://golang.org/pkg/net/http/httptest/#example_Server_hTTP2

**Comment by pmalek** [comment] 2020-06-14 11:55
@odeke-em My bad. But the TLS is also required to trigger this bug so both `ts.EnableHTTP2 = true` and `ts.StartTLS()` instead of `ts.Start()` in my simplified example will trigger the data race.

**Comment by fraenkel** [comment] 2020-06-14 15:12
It took me a bit to reproduce the issue and then find the statement that covers this situation.

https://golang.org/pkg/net/http/#RoundTripper
`callers wanting to reuse the body for subsequent requests must arrange to wait for the Close call before doing so.`

The body isn't closed until net/http.(*http2clientStream).writeRequestBody() returns.

**Comment by pmalek** [comment] 2020-06-15 13:39
> ...must arrange to wait for the Close call...

That's interesting because as far as I can see there's no way of telling outside of the e.g. `http.Post` or `http.Do` call, whether the `Close` was called and that it returned.

**Comment by fraenkel** [comment] 2020-09-06 22:03
Looking at this further, the issue is when a GOAWAY is sent from the server all outstanding streams are sent a response errClientConnGotGoAway. However, cs.writeRequestBody() may still be executing.
Unfortunately, this isn't the only situation where this occurs.

**Comment by fraenkel** [comment] 2020-09-06 22:41
Good news, its easy to fix. Just have to create a test that always fails.

**Comment by answer1991** [comment] 2020-09-10 05:41
@andybons 

Could you please add this fix to next milestone, as Kubernetes affected.

**Comment by answer1991** [comment] 2020-09-23 09:14
> Could you please add this fix to next milestone, as Kubernetes affected.

@rsc

**Comment by networkimprov** [comment] 2020-09-23 12:36
@odeke-em are you available to review the above CL?

**Comment by networkimprov** [comment] 2020-10-31 09:07
We had a request to backport this, as it impacts Kubernetes, per @answer1991.

**Comment by odeke-em** [comment] 2020-10-31 19:43
@dmitshur what do you think about the requested backport from @answer1991 and @networkimprov per https://github.com/golang/go/issues/31192#issuecomment-719906759?

**Comment by answer1991** [comment] 2020-11-02 02:29
Glad to see the fix merged. 
As Kubernetes now is using golang 1.15.x, it would be fine if we backport the fix to 1.15.

**Comment by dmitshur** [comment] 2020-11-02 14:52
I don't have enough information to know the severity of impact caused by this problem and whether there's a reasonable workaround. We need that information to balance it against the risk of backporting a commit when making a decision.

@answer1991 The process for requesting a backport is described at https://golang.org/wiki/MinorReleases. If after reading it you think this issue should be considered for backporting, please use gopherbot to make a request and provide a brief rationale for it. I know you've said this impacts Kubernetes, but please provide a little more detail about how serious it is. Thanks.

CC @golang/release.

**Comment by answer1991** [comment] 2020-11-12 13:23
Kubernetes team had already announced GOAWAY feature in [Kubernetes v1.19 release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md). However, if Kubernetes enable GOAWAY feature, the client will receive unexpected 500 status code errors which I described at #41234, and there is no workaround. I think backport to golang 1.15 is necessary.

@gopherbot please backport, as Kubernetes is affected and there is no workaround.

**Comment by networkimprov** [comment] 2020-11-12 19:13
@dmitshur @toothrot I think this needs backport to 1.14 as well?

**Comment by dmitshur** [comment] 2020-11-12 20:14
Yep, since the issue affects both Go 1.15 and 1.14, it needs to be considered for backport to both, or neither. (We typically double-check that as part reviewing backport requests, but it's helpful to also catch it earlier.)

**Comment by answer1991** [comment] 2020-11-13 08:54
I don't know why the bot didn't create a cherry-pick to Go 1.14. Because I mentioned 1.15 in my comment? Re-try

**Comment by answer1991** [comment] 2020-11-13 08:55
Kubernetes team had already announced GOAWAY feature in [Kubernetes v1.19 release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md). However, if Kubernetes enable GOAWAY feature, the client will receive unexpected 500 status code errors which I described at #41234, and there is no workaround. I think backport is necessary.

@gopherbot please backport, as Kubernetes is affected and there is no workaround.

**Comment by dmitshur** [comment] 2020-11-13 15:41
Backport issue opened: #42586 (for 1.14).

(Follow up requests are not supported, so they need to be created manually until #25574 is resolved.)

**Comment by answer1991** [comment] 2020-11-13 16:06
thanks!

**Comment by dmitshur** [comment] 2020-11-20 23:14
Reopening as the `net/http` issue isn't fixed in Go 1.16 yet.

This issue got closed because [CL 253259](https://golang.org/cl/253259) was submitted with the verb "Fixes". However that CL was in x/net. The bundled copy of `golang.org/x/net/http2` inside `net/http` still needs to be updated to include the fix.

Doing the bundle update was attempted, but it caused an existing `net/http` test to fail. This is #42498. That issue needs to be resolved.

**Comment by neild** [comment] 2020-12-04 00:49
#42498 has been resolved (I believe), and should no longer block doing the bundle update.

**Comment by answer1991** [comment] 2020-12-04 13:42
Should we backport #42498 too?

**Closed** 2020-12-10 18:28 UTC
Labels: NeedsFix, release-blocker
