### ISSUE TITLE
spec: Clarify difference between absent and empty method set

### ISSUE THREAD

**Issue by rillig** [golang/go#47370] opened 2021-07-24 11:25 UTC
### What did you do?

* Carefully read https://golang.org/ref/spec#Method_sets.

### What did you expect to see?

The spec should say that "each type has a (possibly empty) method set associated with it".

### What did you see instead?

The spec says that a "type may have a method set associated with it". In the same paragraph, it says "Any other type has an empty method set", which suggests that indeed every type has a method set, even if it is empty.

The spec did not clarify what the difference between a type without method set and a type with an empty method set is. I am assuming that there is no such difference, I just want to make sure I understood the spec as intended.

**Comment by nobishino** [comment] 2021-07-24 15:57
I think this is a duplicate of #44318, which is resolved by https://github.com/golang/go/commit/078f08f0ee1eb6cb172fc1f9d53f34c5783e522d. (As of version Feb 19, 2021, this issue should be resolved?)

**Comment by ianlancetaylor** [comment] 2021-07-25 00:12
As far as I can tell this is fixed for 1.17.  Please comment if you disagree.  Thanks.

**Closed by ianlancetaylor** 2021-07-25 00:12 UTC
