### ISSUE TITLE
tour: clarify what "export" means

### ISSUE THREAD

**Issue by getpradeep9** [golang/go#12539] opened 2015-09-08 10:53 UTC
Context: https://tour.golang.org/basics/3

Change the title above to describe your issue and add your feedback here, including code if necessary

hI

I did not understand the description export.Please provide more clear explanation

regards,ppp

**Comment by ericmdantas** [comment] 2015-09-08 11:16
@getpradeep9 it basically says that the language doesn't have something like:
```
public someMethod() {
  // ...
}

private someOtherMethod {
  // ...
}
```

In order to make something visible outside, you'll have to use a capital letter, as in: 
```
SomeMethod() {
 // ...
 // SomeMethod can be seen from outside
}

someOtherMethod {
 // this one can't, it doesn't begin with a capital letter
}
```

**Comment by robpike** [comment] 2015-09-08 15:54
Be careful. Export does not mean the same thing as public. Export is a module concept, while public is (usually) a class concept.

**Comment by bradfitz** [comment] 2015-09-08 15:57
Sure. I changed the bug summary again... "clarify what "export" means"

**Comment by kytrinyx** [comment] 2015-10-06 03:36
This is a duplicate of #12005

**Closed** 2015-10-06 03:49 UTC
Labels: Documentation
