### ISSUE TITLE
x/pkgsite: "other flags" section of `fmt` package documentation is garbled

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#54015] opened 2022-07-23 13:31 UTC
### What is the URL of the page with the issue?

https://pkg.go.dev/fmt#section-sourcefiles

### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0

### Screenshot

![2022-07-23-152957_grim](https://user-images.githubusercontent.com/524812/180607147-bbe979d9-cf3d-44c5-a435-d8b2a8af3c59.png)

### What did you expect to see?

The format flags as listed in the [source documentation](https://cs.opensource.google/go/go/+/refs/tags/go1.18.4:src/fmt/doc.go).

### What did you see instead?

The `-` flag turned into a list indicator, newlines gone.

**Comment by seankhliao** [comment] 2022-07-23 13:35
Duplicate of #53759

**Closed by seankhliao** 2022-07-23 13:35 UTC
Labels: pkgsite
