### ISSUE TITLE
x/tools/internal/imports: update stdlib index after every major Go release

### ISSUE THREAD

**Issue by smasher164** [golang/go#38706] opened 2020-04-27 19:13 UTC
API changes should automatically be detected by x/tools/internal/imports after each major release. After 1.14, they were manually updated as per https://github.com/golang/go/issues/38464. This should be part of the release process (maybe x/build/cmd/releasebot?).

**Comment by heschik** [comment] 2021-02-18 21:42
@golang/release might have something to say about this.

**Comment by dmitshur** [comment] 2021-02-18 21:50
As a first step, let's make this a recurring early-in-cycle release-blocking issue, similar to #40705 and #36905, so that this task isn't missed.

I'll place it in Go 1.17 milestone now, and when [CL 293839](https://golang.org/cl/cl/293839 ) is submitted, it can be moved to Go 1.18.

**Comment by heschik** [comment] 2021-02-18 21:56
Strictly speaking it would probably make it sense to do it shortly before the release, once the API has stabilized. But right after is fine too.

**Comment by dmitshur** [comment] 2021-02-18 22:04
@heschik Yep, that makes sense. The reason I've used this early-in-cycle path for now is the same reason I closed https://github.com/golang/go/issues/27155#issuecomment-779940755: we currently don't have a good system for tracking issues that aren't actionable until very late in a dev cycle. When we do, we can improve this task so it happens late in cycle instead.

**Comment by cagedmantis** [comment] 2021-08-12 19:29
This issue is currently labeled as early-in-cycle for Go 1.18.
That [time is now](https://groups.google.com/g/golang-dev/c/g2aGRJQIGzw/m/m7hkf2YiAAAJ), so this is a friendly ping so the issue is looked at again.

**Comment by findleyr** [comment] 2022-08-10 17:22
I'll do this now.  How do we feel about enforcing this with a test? And if we want to go that route, should the test start failing as soon as new APIs are added to the standard library, or once the standard library is released?

CC @golang/tools-team

**Comment by findleyr** [comment] 2022-08-10 17:27
A better option for automation may be to create a release blocking bug associated with each major Go version.

**Comment by findleyr** [comment] 2022-08-12 14:58
This was done for Go 1.20, so I bumped to the Go1.21 milestone.

Would be better to have separate issues but in the meantime I think this is set up for the next cycle.

**Comment by dmitshur** [comment] 2023-02-02 18:48
[CL 464342](https://go.dev/cl/464342) and [CL 464875](https://go.dev/cl/464875) regenerated the index after the Go 1.20 release.
Moving to the next milestone since this won't need attention until Go 1.21 is out.

Note that relui will be generating these CLs automatically for future releases (implemented in #54377—thanks @dle8!), so it's not necessary to do it manually anymore.

**Comment by heschi** [comment] 2023-02-06 17:40
Seems like we can close the issue now that it's automated. No need to remind ourselves.

**Closed by heschi** 2023-02-06 17:40 UTC
Labels: help wanted, NeedsFix, early-in-cycle, release-blocker, Tools, recurring
