### ISSUE TITLE
x/build: macOS PKG installer doesn't tell where Go is being installed

### ISSUE THREAD

**Issue by dolmen** [golang/go#58496] opened 2023-02-13 17:00 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

Install Go 1.20 using package https://go.dev/dl/go1.20.darwin-amd64.pkg

Screenshots from French install:

<img width="732" alt="Capture d’écran 2023-02-13 à 17 35 38" src="https://user-images.githubusercontent.com/129536/218520639-8ebe8a00-44d6-4e73-b99e-76e27cedb4e3.png">

Note that "Destination" screen (mentioned on the sidebar) is never shown to the user.

<img width="732" alt="Capture d’écran 2023-02-13 à 17 35 46" src="https://user-images.githubusercontent.com/129536/218520664-33402336-fba8-426c-b87c-43d0a23069af.png">

<img width="732" alt="Capture d’écran 2023-02-13 à 17 36 14" src="https://user-images.githubusercontent.com/129536/218520715-93039e0b-529a-484e-9fa1-9c6f5880d653.png">

<img width="732" alt="Capture d’écran 2023-02-13 à 17 36 51" src="https://user-images.githubusercontent.com/129536/218520773-2f5c120b-d8e6-4ffb-9be9-4008ad1e3cd7.png">

### What did you expect to see?

I expect that the installer tells me that Go has been installed into `/usr/local/go` and that I have to _manually_ inject `/usr/local/go/bin` into `$PATH` like described at https://go.dev/doc/install.

### What did you see instead?

As screenshots show, no indication of where Go has been installed.

The information is available at https://go.dev/doc/install though.

**Comment by dolmen** [comment] 2023-02-13 17:02
"gopherbot added this to the Unreleased milestone".

Well 1.20 _has_ been released.

**Comment by prattmic** [comment] 2023-02-14 22:42
cc @golang/release

**Comment by dmitshur** [comment] 2023-02-15 18:04
Thanks for reporting this.

The Go installer on macOS adds the installed `go` and `gofmt` binaries to `PATH` by placing a file containing the "/usr/local/go/bin" path to the /etc/paths.d directory. You should be able to see it by running `cat /etc/paths.d/go`. There is no need to manually modify PATH—it is automatically handled by the installer. You might need to restart the terminal if it was the first time Go was installed on a given Mac.

This is consistent with what's written in macOS tab at https://go.dev/doc/install:

> The package installs the Go distribution to /usr/local/go. The package should put the /usr/local/go/bin directory in your PATH environment variable. You may need to restart any open Terminal sessions for the change to take effect.

Everything seems to be working as intended and as documented, so I'll close this. Please comment if I missed something. Thanks.

**Closed by dmitshur** 2023-02-15 18:04 UTC
Labels: Builders, NeedsInvestigation
