### ISSUE TITLE
x/build/gerrit: Unable to SetReview robot_comments, missing API

### ISSUE THREAD

**Issue by kallisti5** [golang/go#58983] opened 2023-03-11 13:13 UTC
Gerrit offers a "robot_comments" API:
https://gerrit-review.googlesource.com/Documentation/config-robot-comments.html

This doesn't seem to be available in https://pkg.go.dev/golang.org/x/build/gerrit#Client.SetReview however.

As a large usage of the gerrit go module will be automation, it seems odd the REST API for robot_comments isn't available.

**Comment by dmitshur** [comment] 2023-08-14 20:13
Thanks for reporting this. The package comment is now more clear that this package is for the internal needs of the Go project infrastructure, so it's working as intended that it covers a small subset. There are better suited general-purpose Gerrit API clients, e.g., see the top result at https://pkg.go.dev/search?q=gerrit. Closing since we'll get to this only if a need for it comes up, and there's not much use in tracking it until then.

**Closed by dmitshur** 2023-08-14 20:13 UTC
Labels: Builders, NeedsInvestigation, FeatureRequest
