### ISSUE TITLE
x/website: remove search box from golang.org

### ISSUE THREAD

**Issue by rsc** [golang/go#44357] opened 2021-02-18 02:02 UTC
Related to the topic of redirecting golang.org's documentation pages to pkg.go.dev (#44356), I investigated the use of the search box, to see whether we should keep it around. We should not.

Last Friday I downloaded the most recent 2,500 /search URLs from the golang.org App Engine dashboard and went through them. They spanned 28 hours.

97 were for x/ repo redirects for packages named search, leaving 2,403.
201 were for "Nubo Beauty" or "www.nubobeauty.com" [sic], leaving 2,202.
609 more were URLs that had nothing to do with Go (usually somedomain.cn), leaving 1,592.
Those 1,592 make up 0.0158 QPS over 28 hours, or just under 1 QPM.

There are few enough that you can just read through the list of search terms from that 28-hour period, which I did. Overall it is quite reasonable to turn down search on golang.org in favor of people using Google to find general things or to use pkg.go.dev for packages: there's so little traffic and we answer the queries so badly compared to Google or pkg.go.dev. 

It hurts to see people searching for queries like the following, knowing that they got no useful results:

 - 1.16
 - 1.16beta
 - GOPATH
 - k8s.io/api/settings/v1alpha1
 - language and capacity
 - linux installation
 - logical operators
 - mocking struct
 - naming convention
 - remove element from slice
 - sirupsen/logrus
 - string template
 - struct field tag
 - tutorial
 - update go
 - using go modules
 - visual studio code

The saving grace is that hardly anyone is searching at all. But those that are searching would be better served looking for a proper search engine.

Another takeaway for the package discovery site is that once we have the symbols-per-version info, it would be nice to make searches like "x509.Certificate" work. Those come up as well. That's #44142.

**Comment by magical** [comment] 2021-02-20 23:54
This seems to have been committed without any discussion: https://go-review.googlesource.com/c/website/+/292590.

I use the search feature on golang.org to search the Go package documentation and source code.  I'm sympathetic to the argument the search box doesn't do what most users expect it to.  However, removing it leaves those of us who use it for what it actually does left in the lurch (eg https://github.com/golang/go/issues/44142#issuecomment-782767193). What is the migration path for those users?

**Comment by dmitshur** [comment] 2021-02-22 15:39
Fixed by [CL 292590](https://golang.org/cl/292590), closing. (It didn't get closed automatically because the "golang/go" prefix wasn't included.)

@magical The commit message suggests that the migration path is search engines like Google for general information about Go, and pkg.go.dev search for searching for Go packages and symbols. Issue #44142 is tracking improving results for queries like \<pkg\>.\<sym\>, and issue #41369 for prioritizing standard library results higher.

**Closed by dmitshur** 2021-02-22 15:39 UTC
Labels: NeedsFix

**Comment by mholt** [comment] 2021-02-22 18:29
Who moved my cheese?

What do you suggest for code search now? I will probably use Sourcegraph, but [this URL is less convenient](https://sourcegraph.com/github.com/golang/go) and linking to it from the Go website would be much appreciated.

**Comment by rsc** [comment] 2021-02-23 17:18
@mholt, I'd suggest using https://cs.opensource.google/go for Go repo code search.

**Comment by 89z** [comment] 2021-03-07 03:39
https://github.com/golang/go/issues/44835

**Comment by 89z** [comment] 2021-03-07 03:49
@rsc that is a great link, but it really could be more discoverable. For example
its literally not included in any file of any repository owned by Google:

https://github.com/search?type=code&q=org:golang+opensource.google

So it should be added there to start, then further also added to any pages like
this:

https://golang.org/pkg/encoding/json

**Comment by JakeMont** [comment] 2021-03-17 16:23
I'm also disappointed that this was removed without any real discussion. In particular for searching the standard libraries. The fact that Go's own website no longer provides a way to find a standard library function seems unfortunate. Personally, this was the way I typically looked up standard library functions. I'm still having trouble finding an acceptable alternative.

For casual Go users and noobs, the fact that there is no "official" way to locate the "Rename" function may be a stumbling block. 

I'm not totally convinced by the OP's argument that the 'global' search was not useful, but even if that is so, then why not add a search just to the standard library documentation page: https://golang.org/pkg/ ? A good searchable standard library reference seems fundamental to any well maintained language.  

Other languages seem to provide this support:  

- Python: https://docs.python.org/3/library/
- Rust: https://doc.rust-lang.org/std/all.html
- .NET laguages, like C# - https://docs.microsoft.com/en-us/dotnet/api/?view=net-5.0
- Perl - https://perldoc.perl.org/
- Ruby - https://docs.ruby-lang.org/en/2.1.0/standard_library_rdoc.html

etc, etc.

**Comment by seankhliao** [comment] 2021-03-17 16:44
note #44356 would redirect golang.org/pkg to pkg.go.dev

**Comment by 89z** [comment] 2021-03-29 18:32
I found another option. You can just search GitHub like this:

~~~
org:golang Scanf
~~~

The example I just put returned 22 results. Compare with the link @rsc put, where you get 845 results:

https://cs.opensource.google/search?q=Scanf&ss=go

**Comment by mleonhard** [comment] 2021-06-25 07:35
I think this change makes Golang harder to learn and use.  Future Golang users will have to use a web search engine and waste time reading low-quality results from w3schools.com and other SEO sites.

I'm not surprised that it was done.  It follows the standard Google pattern:
1. Neglect fixing usability issues in the tool:
   - #40217
   - #40218
   - #40220
2. Wait until knowledgeable users stop using the tool and it is mostly used ineffectively by new users.
3. Remove the tool because it is "not popular enough".

The root cause is Google's incentive structure.  To earn more money, engineers must ship impactful features.  The organization does not value polishing and maintaining existing tools, even when that work is crucial for long-term profitability of the business.

**Comment by rsc** [comment] 2021-06-25 11:16
This issue tracker is for reporting issues with Go, not issues with Google itself.
