### ISSUE TITLE
x/tools/gopls: "could not import ___" after adding new _test package

### ISSUE THREAD

**Issue by zikaeroh** [golang/go#36635] opened 2020-01-18 23:36 UTC
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

I created a package, added code to it, then added a `_test` package to the same directory.

#### What did you expect to see?

No errors, I can start working on that package.

#### What did you see instead?

On finishing typing my package name, all of the imports in my non-test code had "could not import" errors.

Logs: https://gist.github.com/zikaeroh/6ba035d30a5493e19e8673b47ace4f7c

#### Build info

```
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.1.8-0.20200117220505-0cba7a3a9ee9 h1:nzvuLbmeJ+AcY2QpRizKDzip5dbZHStOlteBZR29PH8=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee h1:WG0RUwxtNT4qqaXX3DPA8zHFNm/D9xaBpxzHt1WcA/E=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20200117220505-0cba7a3a9ee9 h1:KOkk4e2xd5OeCDJGwacvr75ICCbCsShrHiqPEdsA9hg=
    golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898 h1:/atklqdjdhuosWIl6AIbOeHJjicWYPqR9bpxqxYG2pA=
    honnef.co/go/tools@v0.0.1-2019.2.3 h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```

#### Go info

```
go version go1.13.6 linux/amd64

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jake/.cache/go-build"
GOENV="/home/jake/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jake/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jake/zikaeroh/hortbot/hortbot/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build755509892=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by stamblerre** [comment] 2020-01-22 05:36
This sounds exactly like https://github.com/golang/go/issues/35949, so we will have to be careful to not make the same mistakes here. Go 1.14 will have the fix for https://github.com/golang/go/issues/35973, which should help things a little.

**Comment by stamblerre** [comment] 2020-01-23 22:28
This issue is a combination of https://github.com/golang/go/issues/35973 and https://github.com/golang/go/issues/36661. With Go 1.14, the imports no longer disappear, since that fix is available there. The fact that we don't recover from the imports disappearing can be attributed to this fact (https://github.com/golang/go/issues/36661#issuecomment-577472626):

> The problem here is that the initial workspace load finds nothing, and AFAIK we currently have no mechanism for adding packages to the workspace set, so they don't ever end up getting diagnosed in the background.

I will then close this issue and continue work on modifying the workspace packages set on https://github.com/golang/go/issues/36661.

**Comment by stamblerre** [comment] 2020-01-24 01:13
On the further investigation, the issue persists apart from what golang/go#36661 covers. I will keep investigating, but as it already existed in `gopls/v0.2.2`, I will move it out of the `gopls/v0.3.0` milestone.

**Comment by stamblerre** [comment] 2020-01-24 01:33
The main issue here is that [these tests](https://github.com/golang/tools/blob/5ecc1643ff520131a8a2aa1e26f1b4a7da41512c/go/packages/packages114_test.go#L19) in `go/packages` pass, but creating the same file structure in `gopls` fails. To repro (with Go 1.14), create a module containing only a non-test file with some dependency. For example:

```go
package bad

import "fmt"

func hello() {
    fmt.Println("hello")
}
```

Then, create the corresponding test file in VS Code. It will be prepopulated if you create it through the VS Code UI. Running `go/packages` on this file will not give you the same result, as expected in that test.

/cc @heschik

**Comment by heschik** [comment] 2020-01-24 02:03
I believe the problem is that `packages.Load("./...")` does not return the overlay packages.

**Closed** 2020-01-24 20:59 UTC
Labels: Tools, gopls
