### ISSUE TITLE
x/tools/gopls: parse error after cut + paste of same content

### ISSUE THREAD

**Issue by atombender** [golang/go#38865] opened 2020-05-05 03:11 UTC
#### What did you do?
1. Selected entire file in VSCode
2. Cmd-X to cut it
3. Cmd-V to paste it back

#### What did you expect to see?
No errors

#### What did you see instead?
Error reported on last line of file that doesn't go away until I restart gopls:

```expected declaration, found 'package'```

#### Log

[gopls.log](https://github.com/golang/go/files/4578769/gopls.log)

#### Build info

```
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.0.0-20200501005904-d351ea090f9b h1:CAqIXUMd9mH3t2O1DRj2IWu0Zh75A4fWPA+YjJOmXdE=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20200430221153-f26c0dd9827d h1:8emZwJTManptbFnp36i5fbhO/1vUs3rfnh5e3Th8HEQ=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```

#### Go info

```
go version go1.14 darwin/amd64

```

**Comment by stamblerre** [comment] 2020-05-05 03:30
Duplicate of https://github.com/golang/go/issues/38424

**Closed by stamblerre** 2020-05-05 03:30 UTC
Labels: Tools, gopls
