### ISSUE TITLE
output missing, but I'm not sure if it's golang problem

### ISSUE THREAD

**Issue by YuleiXiao** [golang/go#24533] opened 2018-03-26 03:21 UTC
### What version of Go are you using (`go version`)?
go version go1.10 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xiaoyulei/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/mnt/hdd1/work/R"
GORACE=""
GOROOT="/mnt/hdd1/tools/go"
GOTMPDIR=""
GOTOOLDIR="/mnt/hdd1/tools/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build064753655=/tmp/go-build -gno-record-gcc-switches"
```
### What did you do?
In my code, there are two ```Printf```, no others code between them. 
```
fmt.Printf("servers(total: %d):\n %s", len(servers), servers)                                                                                
fmt.Printf("monitors(total: %d):\n %s", len(monitors), monitors) 
```
I redirect the program output and error to a file like```xxxx >a.log 2>&1```. But sometime, I found there is only ```monitors``` output, ```servers``` missing. I am not sure if it is golang problem.

### What did you expect to see?
output not missing

### What did you see instead?
```servers``` missing

**Comment by davecheney** [comment] 2018-03-26 03:47
Is it possible for you to provide a stand alone program that demonstrates the problem?

**Comment by YuleiXiao** [comment] 2018-03-26 05:30
@davecheney This problem doesn't occur every time. About a few days, I can get it from log, but I don't know what condition can reproduce it.

**Comment by mvdan** [comment] 2018-03-26 13:32
@YuleiXiao with so little information, and with no way to reproduce the bug, there's little chance for anyone to figure out whether or not this is a bug in Go at all - let alone fix it.

I would suggest closing this issue and reopening it once you have enough information gathered for us to at least understand what could be going on.

**Comment by andybons** [comment] 2018-03-26 21:02
Closing due to lack of reproduction steps. Please feel free to re-open if you have more info you can share.
Thanks.

**Closed by andybons** 2018-03-26 21:02 UTC
Labels: WaitingForInfo
