### ISSUE TITLE
net: TestDualStackUDPListener fails on dragonfly

### ISSUE THREAD

**Issue by bradfitz** [golang/go#10808] opened 2015-05-13 21:59 UTC
TestDualStackUDPListener still fails on Dragonfly sometimes.

From f6d1009431c4

http://build.golang.org/log/f4bc3bb1b42e2afb646e754f6f2d36ec6a665daf

```
--- FAIL: TestDualStackUDPListener (0.02s)
	listen_test.go:319: skipping udp  test
	listen_test.go:319: skipping udp  test
	listen_test.go:319: skipping udp 0.0.0.0 test
	listen_test.go:319: skipping udp  test
	listen_test.go:319: skipping udp :: test
	listen_test.go:319: skipping udp 0.0.0.0 test
	listen_test.go:319: skipping udp :: test
	listen_test.go:319: skipping udp ::ffff:0.0.0.0 test
	listen_test.go:319: skipping udp :: test
	listen_test.go:319: skipping udp4  test
	listen_test.go:319: skipping udp6  test
	listen_test.go:319: skipping udp4 0.0.0.0 test
	listen_test.go:319: skipping udp6 :: test
	listen_test.go:357: listen udp4 127.0.0.1:50813: bind: address already in use
FAIL
FAIL	net	8.282s
```

**Comment by mikioh** [comment] 2015-05-14 00:45
This is a duplicate of @10764. I'll send a patch soon.

**Closed** 2015-05-14 00:45 UTC
Labels: Testing
