### ISSUE TITLE
x/tools/cmd/godoc: public methods of unexported embedded interfaces not shown.

### ISSUE THREAD

**Issue by cznic** [golang/go#16043] opened 2016-06-12 18:23 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

tip @  3c6b668

2. What operating system and processor architecture are you using (`go env`)?

N/A

3. What did you do?

If possible, provide a recipe for reproducing the error.

```bash
jnml@4670:~/src/tmp$ echo $GOPATH 
/home/jnml
jnml@4670:~/src/tmp$ cat tmp.go 
package foo

type t interface {
	Public()
}

type T interface {
	t
}
jnml@4670:~/src/tmp$ godoc tmp T
```

4. What did you expect to see?

```
use 'godoc cmd/tmp' for documentation on the tmp command 

type T interface {
    Public()
    // contains filtered or unexported methods
}
```

5. What did you see instead?

```
use 'godoc cmd/tmp' for documentation on the tmp command 

type T interface {
    // contains filtered or unexported methods
}
```

----

FTR: Importing the package and calling method `Public` on an instance of `foo.T` compiles just fine.

**Comment by ianlancetaylor** [comment] 2016-06-12 18:39
Same as #2971?

**Comment by ianlancetaylor** [comment] 2016-06-12 18:40
CC @griesemer

**Comment by jimmyfrasche** [comment] 2016-06-12 20:47
related  #6600 #10593 #7823 (contains more related issues, some fixed)

**Comment by griesemer** [comment] 2016-07-07 22:56
@ianlancetaylor Yes, this is a duplicate of #2971. Closing.

**Closed by griesemer** 2016-07-07 22:56 UTC
