### ISSUE TITLE
golang.org/x/tools/internal/typeparams fails to build on Go 1.18, missing definitions

### ISSUE THREAD

**Issue by bLuka** [golang/go#51791] opened 2022-03-18 14:15 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

It does happen with Go 1.18 _and_ golang.org/x/tools `0.1.6`. No issue on Go 1.17, or by using any other golang.org/x/tools versions (tried `0.1.5`, `0.1.7` and `0.1.8`).

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/luka/.cache/go-build"
GOENV="/home/luka/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/luka/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/luka/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/luka/go/pkg/mod/golang.org/x/tools@v0.1.6/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3391519846=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
$ cd ~/go/pkg/mod/golang.org/x/tools@v0.1.6/internal/typeparams/
$ go test ./
</pre>

### What did you expect to see?

Build succeeds

### What did you see instead?

<pre>
# golang.org/x/tools/internal/typeparams
./typeparams_go118.go:78:6: sig.SetTypeParams undefined (type *types.Signature has no field or method SetTypeParams)
./typeparams_go118.go:88:6: sig.SetRecvTypeParams undefined (type *types.Signature has no field or method SetRecvTypeParams)
./typeparams_go118.go:98:15: iface.IsConstraint undefined (type *types.Interface has no field or method IsConstraint)
./typeparams_go118.go:144:7: info.Inferred undefined (type *types.Info has no field or method Inferred)
./typeparams_go118.go:144:42: undefined: types.Inferred
./typeparams_go118.go:155:10: info.Inferred undefined (type *types.Info has no field or method Inferred)
./typeparams_go118.go:158:14: info.Inferred undefined (type *types.Info has no field or method Inferred)
./typeparams_go118.go:171:26: undefined: types.Environment
FAIL    golang.org/x/tools/internal/typeparams [build failed]
FAIL
</pre>

### Additional notes

It seems to be related to #48632, which fixed the cause in new golang.org/x/tools versions (`0.1.7` and beyond), and hide the issue in `0.1.6` behind a build constraint. As Go 1.18 has been released, the same issue seems to appear again.

**Comment by findleyr** [comment] 2022-03-18 14:21
Hi, this is a duplicate of #48632: we accidentally broke the build due to version skew during the 1.18 development cycle.

@bcmills I think we discussed at the time and decided it was not necessary to retract v0.1.6. Do you think the equation changes with 1.18 released?

**Comment by bcmills** [comment] 2022-03-18 14:43
I still don't think we need to retract `v0.1.6`. In general, if a newer patch release exists, then users who encounter bugs in a previous patch release should see if upgrading fixes the problem. (It's not like we can issue a patch on a patch release. 😅)

**Comment by bcmills** [comment] 2022-03-18 14:44
Duplicate of #48632

**Closed by bcmills** 2022-03-18 14:44 UTC
