### ISSUE TITLE
fmt: Provide more examples in godocs

### ISSUE THREAD

**Issue by rwhittington** [golang/go#28238] opened 2018-10-16 19:22 UTC
Most fmt functions do not have examples in godocs (currently, only Stringer)

As I've not contributed to go before, I thought providing examples would be a good starter.

**Comment by ALTree** [comment] 2018-10-16 19:40
A few people recently added several examples; see the tip version of the website:

https://tip.golang.org/pkg/fmt/

These new example may also need some clean-up, as Rob said in #27554.

**Comment by robpike** [comment] 2018-10-16 19:47
Duplicate of #27554, in effect.

**Closed by robpike** 2018-10-16 19:47 UTC
