### ISSUE TITLE
Unnecessary syntax error when creating a key-value pairs using map

### ISSUE THREAD

**Issue by BLasan** [golang/go#40394] opened 2020-07-24 18:16 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/benura/.cache/go-build"
GOENV="/home/benura/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/benura/golib:/home/benura/Desktop/goInitProj"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build490309697=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Used map create some key value pairs. Final key value pair will require a ',' to be finished. Otherwise a syntax error will be prompting on the console. (VS-Code 1.46) This is a bit conflict with other programming languages like javascript when defining key-value pairs. Is it really necessary to add a comma after the last key-value pair with in the map.
`	structMap := map[string]string{
		"name":     "John",
		"age":      "24",
		"location": "Colombo"
	}`

### What did you expect to see?
No syntax error.

### What did you see instead?
![Screenshot from 2020-07-24 23-41-43](https://user-images.githubusercontent.com/43112139/88422178-71f20200-ce07-11ea-87be-9aaebed1f6ed.png)
'}' should be right after the "Colombo" value in order to prevent from having this syntax error.

**Comment by icholy** [comment] 2020-07-24 18:30
You're example compiles fine https://play.golang.org/p/E_BInnwuKc6

**Comment by BLasan** [comment] 2020-07-24 18:35
> Your example compiles fine https://play.golang.org/p/E_BInnwuKc6

Actually what I meant was this ,
![Screenshot from 2020-07-25 00-03-00](https://user-images.githubusercontent.com/43112139/88423981-605e2980-ce0a-11ea-82cf-dbd190c630e7.png)
 
When we end the curly braces like in the attached image, it will pop out a syntax error

**Comment by ianlancetaylor** [comment] 2020-07-24 18:46
When showing code, please use plain text or a playground link, not an image.  Especially not a white-on-black image.  Images are hard to read, and they don't support cut-and-paste of text.  Code is plain text, so show it as plain text.

In this case the problem appears to be a missing comma at the end of the "location" line, just as the error message says.

Closing because this seems to be expected behavior.

**Closed by ianlancetaylor** 2020-07-24 18:46 UTC
