### ISSUE TITLE
x/image/font: rendering texts in Hindi

### ISSUE THREAD

**Issue by MayankFawkes** [golang/go#65048] opened 2024-01-10 12:47 UTC
### go version

`go version go1.21.5 windows/amd64`

### go env

<details>

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\mayan\AppData\Local\go-build
set GOENV=C:\Users\mayan\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\mayan\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\mayan\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\mayan\AppData\Local\Temp\go-build1486266299=/tmp/go-build -gno-record-gcc-switches
```

</details>

### What did you do?

Tried to render hindi font

```go
import (
	"image"
	"image/color"
	"image/png"
	"os"

	"golang.org/x/image/font"
	"golang.org/x/image/font/opentype"
	"golang.org/x/image/math/fixed"
)

func addLabel(img *image.RGBA, x, y int, label string, fontPath string, fontSize float64) {
	col := color.RGBA{200, 100, 0, 255}

	fontData, err := os.ReadFile(fontPath)
	if err != nil {
		panic(err)
	}

	f, err := opentype.Parse(fontData)
	if err != nil {
		panic(err)
	}

	face, err := opentype.NewFace(f, &opentype.FaceOptions{
		Size:    fontSize,
		DPI:     72,
		Hinting: font.HintingNone,
	})

	if err != nil {
		panic(err)
	}

	point := fixed.Point26_6{X: fixed.I(x), Y: fixed.I(y)}

	d := &font.Drawer{
		Dst:  img,
		Src:  image.NewUniform(col),
		Face: face,
		Dot:  point,
	}

	d.DrawString(label)

}

func saveImg() {
	img := image.NewRGBA(image.Rect(0, 0, 300, 100))
	// fontPath := "assets/fonts/Helvetica.ttf"
	// fontSize := 50.0
	// addLabel(img, 20, 50, "Hello Go", fontPath, fontSize)

	fontPath := "assets/fonts/mangal.ttf"
	fontSize := 50.0
	addLabel(img, 20, 50, "नमस्ते", fontPath, fontSize)

	f, err := os.Create("hello-go.png")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	if err := png.Encode(f, img); err != nil {
		panic(err)
	}
}
```

### What did you see happen?

fonts are not being able to render properly. I had the same problem in python and they included libraqm which fixed the issue i wish if we have something for golang too 

### What did you expect to see?

Output

![image](https://github.com/golang/go/assets/43340190/4ecf3fc3-5fb2-4632-aab8-047533ae471d)

Expected 

![image](https://github.com/golang/go/assets/43340190/984122cf-9ea8-41d6-a070-a182b2d1ef6f)

**Comment by dmitshur** [comment] 2024-01-10 16:14
CC @nigeltao.

**Comment by dmitshur** [comment] 2024-01-10 16:24
Thanks for the report. Right now the "What did you see happen?" section has 0 images, but "What did you expect to see?" has 2 images. Is the image under "Output" the one produced by the Go program? It seems to have a background color that I don't see in the Go code. How is the image under "Expected" produced—is it using the same font?

**Comment by MayankFawkes** [comment] 2024-01-10 17:49
@dmitshur Let me clear the output is what go code generated and the exception is i took from google which is how that word should be written, **please don't mind the fonts they are different and sorry for the confusion**

Here is the same word with same fonts

![image](https://github.com/golang/go/assets/43340190/0a6b679b-b134-4814-91ab-01932ade8327)

**Comment by nigeltao** [comment] 2024-01-11 08:24
Duplicate of
https://github.com/golang/go/issues/27281#issuecomment-416799683

> Yeah, text shaping isn't implemented yet. There's no Go equivalent of HarfBuzz yet.
>
> That's certainly a bug I'd like to see fixed, but it'd be a lot of work, and I don't have any free time. Sorry.

**Closed by nigeltao** 2024-01-11 08:24 UTC
Labels: NeedsInvestigation, FeatureRequest

**Comment by benoitkugler** [comment] 2024-01-12 01:10
@MayankFawkes You may want give a try to `go-text/typesetting`, which includes a go port of Harfbuzz  (and `go-text/render` to directly render a text to an image)

**Comment by MayankFawkes** [comment] 2024-01-12 06:29
@benoitkugler i tried for some reason that is not working with hindi text. i tried ``go-text/render`` render_test.go they even have hindi text in it but the out.png is incorrect.

they generated

![image](https://github.com/golang/go/assets/43340190/5b62afc1-8172-4e87-8b4b-365d2e776fa2)

but the correct is

``Hello! ± ज्या``

the first letter

**Comment by benoitkugler** [comment] 2024-01-12 09:56
@MayankFawkes Thank you. You may want to follow the opened issue https://github.com/go-text/render/issues/11

**Comment by MayankFawkes** [comment] 2024-01-12 09:58
Alright thank you
