### ISSUE TITLE
os/exec: parallel Command.Start() can be very slow

### ISSUE THREAD

**Issue by sb10** [golang/go#46388] opened 2021-05-26 08:36 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes (1.16.4).

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/nfs/users/nfs_s/sb10/.cache/go-build"
GOENV="/nfs/users/nfs_s/sb10/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/nfs/users/nfs_s/sb10/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/nfs/users/nfs_s/sb10/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/software/vertres/installs/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/software/vertres/installs/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2872611298=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
$ go run main.go
Serial:
Start 0 took 252.173µs
Start 1 took 221.002µs
Start 2 took 231.627µs
Start 3 took 171.249µs
Start 4 took 223.431µs
Start 5 took 211.772µs
Start 6 took 169.167µs
Start 7 took 203.491µs
Start 8 took 198.665µs
Start 9 took 181.992µs

Parallel (8 cpus, GOMAXPROCS 8):
Start 0 took 282.599µs
Start 1 took 419.762µs
Start 2 took 423.152µs
Start 3 took 834.894µs
Start 9 took 1.081168ms
Start 6 took 2.307089ms
Start 4 took 3.174552ms
Start 8 took 3.222679ms
Start 5 took 7.438996ms
Start 7 took 14.173073ms
</pre>

Where main.go is https://play.golang.org/p/VN5OqF23nDQ

### What did you expect to see?

`exec.Command.Start()` times be consistent between serial and parallel runs.

### What did you see instead?

Parallel `exec.Command.Start()` times can be around 70 times greater than serial ones.

Setting `runtime.GOMAXPROCS()` to greater than or equal to the number of concurrent Start()s doesn't help. Setting it to 1 does reduce the effect, but I still get a few starts in the multiple millisecond range.

A runtime trace seems to suggest this is caused by os.StartProcess taking a global mutex lock, I think as explained here: https://github.com/golang/go/blob/d050238bb653711b47335583c5425c9efec30e4e/src/syscall/exec_unix.go#L20-L65

But I wondered if there's any other way around this for this particular use case?

**Comment by seankhliao** [comment] 2021-05-26 11:44
cc @bradfitz @ianlancetaylor

**Comment by ianlancetaylor** [comment] 2021-05-26 21:41
I think this is a dup of #23558.

**Comment by seankhliao** [comment] 2021-05-27 16:42
Duplicate of #23558

**Closed by seankhliao** 2021-05-27 16:42 UTC
Labels: NeedsInvestigation, Performance
