### ISSUE TITLE
cmd/go: panic: internal error: can't find reason for requirement

### ISSUE THREAD

**Issue by rsc** [golang/go#56662] opened 2022-11-08 22:24 UTC
Reproduction case for an internal error panic in cmd/go.

```
% cd golang.org/x/build
% git change 432398/2
git-codereview: changed to CL 432398/2.
	internal/diff: copy from main repo
% git checkout 'HEAD^' go.mod go.sum
Updated 2 paths from 9c7ed77c
% go get golang.org/x/tools
panic: internal error: can't find reason for requirement on golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc00063f188, 0x11}, {0xc000028f30, 0x22}})
	/Users/rsc/go/src/cmd/go/internal/modget/get.go:1760 +0xd4
cmd/go/internal/modget.(*resolver).updateBuildList(0xc000138000, {0x172fb70, 0xc00002a158}, {0x0, 0x0, 0x0})
	/Users/rsc/go/src/cmd/go/internal/modget/get.go:1765 +0x54c
cmd/go/internal/modget.(*resolver).resolveQueries(0xc000138000, {0x172fb70, 0xc00002a158}, {0xc000014058, 0x1, 0xc0000b5d78?})
	/Users/rsc/go/src/cmd/go/internal/modget/get.go:1243 +0x1a5
cmd/go/internal/modget.runGet({0x172fb70, 0xc00002a158}, 0xc00002c528?, {0xc0000241d0, 0x1, 0x1})
	/Users/rsc/go/src/cmd/go/internal/modget/get.go:314 +0x408
main.invoke(0x1a3e2e0, {0xc0000241c0, 0x2, 0x2})
	/Users/rsc/go/src/cmd/go/main.go:225 +0x3d9
main.main()
	/Users/rsc/go/src/cmd/go/main.go:179 +0x7ce
% 
```

/cc @bcmills

**Comment by bcmills** [comment] 2022-11-09 15:25
This is likely a duplicate of #56494, but assigning to myself to verify that the fix for that also addresses this reproducer.

**Comment by bcmills** [comment] 2023-04-24 13:59
Duplicate of #56494

**Closed by bcmills** 2023-04-24 13:59 UTC
Labels: NeedsInvestigation, GoCommand, modules

**Comment by liuyubo777** [comment] 2023-06-07 06:43
### how can i fix it?
` go get -v -u golang.org/x/tools/cmd/godoc
go: downloading github.com/yuin/goldmark v1.5.4
panic: internal error: can't find reason for requirement on golang.org/x/crypto@v0.0.0-20210711020723-a769d52b0f97

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc000272780, 0x13}, {0xc0001329f0, 0x22}})
        c:/go/src/cmd/go/internal/modget/get.go:1760 +0xd4
cmd/go/internal/modget.(*resolver).updateBuildList(0xc000b9a000, {0xc18328, 0xc00001c070}, {0xc00031b400, 0xe, 0x10})
        c:/go/src/cmd/go/internal/modget/get.go:1765 +0x54c
cmd/go/internal/modget.(*resolver).applyUpgrades(0xc000b9a000, {0xc18328, 0xc00001c070}, {0xc00006fb80?, 0xe, 0xc00009bd70?})
        c:/go/src/cmd/go/internal/modget/get.go:1312 +0x465
cmd/go/internal/modget.runGet({0xc18328, 0xc00001c070}, 0xc000028c78?, {0xc0000a0040, 0x1, 0x4})
        c:/go/src/cmd/go/internal/modget/get.go:351 +0x458
main.invoke(0xf32e40, {0xc0000a0010, 0x4, 0x7})
        c:/go/src/cmd/go/main.go:225 +0x3d9
main.main()
        c:/go/src/cmd/go/main.go:179 +0x7ae`
