### ISSUE TITLE
proxy.golang.org: QOS very bad in Australia

### ISSUE THREAD

**Issue by general-kroll-4-life** [golang/go#57188] opened 2022-12-09 08:00 UTC
Quality of service in Melbourne, Australia is quite poor at the time of writing.  Some requests are served very slowly, others fail with 404.  Indicative sample from `go get -x`:

```
# get https://proxy.golang.org/github.com/mattn/go-runewidth/@v/list: 200 OK (58.567s)
# get https://proxy.golang.org/github.com/mailru/easyjson/@v/list: 200 OK (58.609s)
# get https://proxy.golang.org/github.com/mattn/go-colorable/@v/list: 200 OK (58.590s)
# get https://proxy.golang.org/github.com/jackc/pgservicefile/@latest: 404 Not Found (58.597s)
# get https://proxy.golang.org/github.com/pelletier/go-toml/@v/list
# get https://proxy.golang.org/github.com/mattn/go-isatty/@v/list: 200 OK (58.586s)
```

**Comment by general-kroll-4-life** [comment] 2022-12-09 08:04
FYI this has also affected GH Action runners.  I don't know their physical location.

**Comment by zouchangfu** [comment] 2022-12-09 08:13
@gopherbot 

you can try this 

go env -w GOPROXY=direct
go env -w GOSUMDB=off

**Comment by LeGEC** [comment] 2022-12-09 08:28
related issue: #57185 (this issue is probably a duplicate, with root cause being a problem with proxy.golang.org)

**Comment by seankhliao** [comment] 2022-12-09 08:46
cc @golang/tools-team

**Comment by seankhliao** [comment] 2022-12-09 08:56
Duplicate of #57185

**Closed by seankhliao** 2022-12-09 08:56 UTC
Labels: NeedsInvestigation, proxy.golang.org
