### ISSUE TITLE
x/tools/playground: program does not stop

### ISSUE THREAD

**Issue by Teelevision** [golang/go#41007] opened 2020-08-24 16:09 UTC
### What version of Go are you using (`go version`)?

> The playground uses the latest stable release of Go.
> The current version is go1.14.7.

### Does this issue reproduce with the latest release?

There is as yet insufficient data for a meaningful answer.

### What operating system and processor architecture are you using (`go env`)?

That running on https://play.golang.org/.

### What did you do?

https://play.golang.org/p/kQraatQeinz

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	ticker := time.NewTicker(time.Second)
	for {
		select {
		case <-ticker.C:
			fmt.Print(".")
			break
		}
	}
	fmt.Println("Hello, playground")
}
```

### What did you expect to see?

Program not starting or program running into timeout.

### What did you see instead?

Playground reports a timeout and then does not stop generating output:
```
./prog.go:17:2: unreachable code
Go vet exited.

timeout running program
......................................................[...]
```
Program is still running as of finishing writing this issue. (More than 15 minutes.)

**Comment by prattmic** [comment] 2020-08-24 16:42
cc @toothrot

**Comment by toothrot** [comment] 2020-08-24 21:56
Hey @Teelevision, this is actually part of our faketime simulation of how the program output would look had it been running. As the clock and time advancement has been faked, we simulate delays in our output so it tries to look like what your program would have done.

If you change your code slightly to put the time output by ticker.C, the final message from your program before it was terminated would look similar to this:

```json
# our API response:
{"Message":"2009-11-11 02:42:25 +0000 UTC m=+13345.000000001\n","Kind":"stdout","Delay":1000000000}
```

In this case, you can see that we weren't actually sleeping between loop iterations, and the clock has moved forward quite a lot further than our 5 second timeout! Our javascript UI simulates this in your browser, and calculates how long to sleep between each message based on the `Delay` field.

In any case, this is working as intended, so I will close this issue. As the output states, there was a timeout running your program, it was really killed (I verified locally and in production to be extra sure), but we fake your output so it looks real.

I hope that helps! Please comment if something isn't clear.

**Closed by toothrot** 2020-08-24 21:56 UTC
Labels: NeedsInvestigation, Tools
