### ISSUE TITLE
go/doc: link detection in ToHTML is misbehaving

### ISSUE THREAD

**Issue by Bo0mer** [golang/go#22285] opened 2017-10-16 06:37 UTC
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

Run the following commands on my machine (running macOS):
```bash
$ godoc -http :6060
```
navigated to http://localhost:6060/pkg/golang.org/x/tools/present and did a search for `renee`.

#### What did you expect to see?

Valid link to `https://www.instagram.com/reneefrench` named `Renée French`.

#### What did you see instead?

Invalid link pointing to `https://www.instagram.com/reneefrench/][Ren`.

#### Does this issue reproduce with the latest release (go1.9.1)?

Yes, even on https://godoc.org/golang.org/x/tools/present.

#### System details

```
go version go1.9 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ivan/workspace/Go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ps/1g_475591cv3rf9lkqnyp9qh0000gn/T/go-build145680146=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOROOT/bin/go version: go version go1.9 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.9
uname -v: Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
lldb --version: lldb-900.0.45
  Swift-4.0
```

**Comment by shurcooL** [comment] 2017-10-16 06:47
> #### What did you expect to see?
>
> Valid link to `https://www.instagram.com/reneefrench` named `Renée French`.

I would not expect to see that. It's a \<pre\> block containing the following text:

```
...
.caption _Gopher_ by [[https://www.instagram.com/reneefrench/][Renée French]]
...
```

It's just text. It happens to be in present format. But godoc can't know that it should parse the square brackets and text inside as a link.

The best it could do is link all of `https://www.instagram.com/reneefrench/][Renée French]]` instead of just `https://www.instagram.com/reneefrench/][Ren`, but whether that's better or not is debatable.

Also see https://golang.org/pkg/go/doc/#ToHTML:

> A span of indented lines is converted into a \<pre\> block, with the common indent prefix removed.
>
> URLs in the comment text are converted into links; if the URL also appears in the words map, the link is taken from the map (if the corresponding map value is the empty string, the URL is not converted into a link).

I think this is working as intended (except perhaps the URL matching stopping at the accented letter).

**Comment by ianlancetaylor** [comment] 2017-10-16 19:12
CC @dsnet who has been looking at godoc links.  But I tend to agree that this is working as intended.

**Comment by dsnet** [comment] 2017-10-16 21:10
The logic for URL detection is in `go/doc.ToHTML`. It uses a combination of regexps and special-case logic as a heuristic for what is a URL. In #5043, the logic was adjusted so that URLs can contain parenthesis. It was further adjusted in #18139 to include square brackets.

A reasonable adjustment to the URL heuristic is to forbid the URL from containing an closing parenthesis as the first parenthesis of that form.

Thus, `http://example.com/some_resource[foo]` is valid, but `http://example.com/some_resource]blah` is not valid.

**Comment by shurcooL** [comment] 2018-02-17 04:38
An update on what I said earlier. `]` is not one of the safe characters that can be included in a URL without encoding (according to https://www.ietf.org/rfc/rfc1738.txt). RFC 1738 says it must to be encoded. So, it should be safe to stop detecting a URL at `]` and not consider it to be a part of the URL.

Following the same logic, I'm not sure if `http://example.com/some_resource[foo]` should be detected with the `[foo]` suffix. Perhaps it'd be better to stop before the first `[`? If that was a correctly encoded URL, wouldn't it be written as `http://example.com/some_resource%5Bfoo%5D`?

**Closed** 2018-12-14 00:42 UTC
Labels: NeedsFix
