### ISSUE TITLE
crypto/elliptic: hang in doubleJacobian with Curve P-521

### ISSUE THREAD

**Issue by alwaysbespoke** [golang/go#25054] opened 2018-04-24 16:55 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)? 

1.10.1

### Does this issue reproduce with the latest release? 

Yes

### What operating system and processor architecture are you using (`go env`)? 

Windows 10. Intel

### What did you do?

When running an http request to an https server that requires a P521 Curve the code hangs without throwing an error.

So, try hitting a server with a certificate that requires P521

Please look at the following within elliptical.go...

ScalarMult
addJacobian
doubleJacobian

The code will hang within the ScalarMult loop and it will also hang within the Jacobian processes

### What did you expect to see? 

We need to see a successful key exchange

### What did you see instead?

No key exchange occured

**Comment by FiloSottile** [comment] 2018-04-24 17:05
Can you provide an example server and a code sample?

Also, I assume the architecture is amd64 / x86-64?

Finally, if during a hang you could send a SIGQUIT (Ctrl-\) to get a stack trace and send the output, that would help.

**Comment by alwaysbespoke** [comment] 2018-04-24 17:32
Running some tests, the code always hangs here within ScalarMult

                for bitNum := 0; bitNum < 8; bitNum++ {
			x, y, z = curve.doubleJacobian(x, y, z)
			if byte&0x80 == 0x80 {
				x, y, z = curve.addJacobian(Bx, By, Bz, x, y, z)
			}
			byte <<= 1
		}

**Comment by FiloSottile** [comment] 2018-04-24 17:37
Thanks for the details, if you hit Ctrl-\\ during a hang the traceback might tell us how deep it gets stuck.

**Comment by FiloSottile** [comment] 2018-04-24 17:43
I can't reproduce on go1.10.1 darwin/amd64 with the code below, I will try from a Windows machine. Can you check if just doing `go run` on the file below is enough to cause the hang on your system?

```
// +build ignore

package main

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"os"
)

func main() {
	request, err := http.NewRequest("POST", "https://gosmo.server93.com", bytes.NewBufferString("TEST"))

	request.Header.Set("Content-Type", "application/json")
	request.Header.Set("Accept", "application/json")

	client := &http.Client{}

	response, err := client.Do(request)

	if err != nil {
		fmt.Println(err)
	}

	defer response.Body.Close()

	io.Copy(os.Stdout, response.Body)
}
```

**Comment by alwaysbespoke** [comment] 2018-04-24 17:52
Your code makes it to the serialized output. Then the window exits. I added an infinite loop at the end of main and it still closes.

**Comment by alwaysbespoke** [comment] 2018-04-24 17:57
Looks like it's running now. What do you think the issue was? I'm confused now lol

**Comment by alwaysbespoke** [comment] 2018-04-24 18:51
Diagnosed the problem.

Ok, so if you run P521 it will fail if the http request is made in a separate go routine. If everything is handled in the main function then there is no failure.

Still seems like a problem. Shouldn't hang like that.

**Comment by alwaysbespoke** [comment] 2018-04-24 20:29
Perfect. I'll create it now.

**Comment by alwaysbespoke** [comment] 2018-04-24 20:37
This breaks. If the dialHTTP() is not a routine then it will run.

package main

import (

    "bytes"
    "fmt"
    "net/http"

)

func main() {

    go dialHTTP()

    for{}
}

func dialHTTP() {

    body := `{"username":"Santiago.Samra","password":"San734"}`

    request, err := http.NewRequest("POST", "https://gosmo.server93.com/comGpsGate/api/v.1/applications/4/tokens", bytes.NewBufferString(body))

    request.Header.Set("Content-Type", "application/json")
    request.Header.Set("Accept", "application/json")

    client := &http.Client{}

    response, err := client.Do(request)

    if err != nil {
        fmt.Println(err)
    }

    defer response.Body.Close()

    fmt.Println(response.Body)

}

**Comment by FiloSottile** [comment] 2018-04-24 20:52
I noticed that if you remove the `for {}` loop and replace it with a channel, a `sync.WaitGroup` or with `select {}` (the best way to say "wait forever" without holding resources), this doesn't happen.

What I think is going on is that the `for {}` is spinning and taking all resources, so the other goroutine never gets CPU time. Also, the scheduler makes no promise about the order in which it runs things, so here it "decided" to run the main goroutine instead of the other one, since you never pass the result back. It's in a way similar to #19182.

Can you reproduce it without a `for {}`?

**Comment by bradfitz** [comment] 2018-04-24 22:50
Sounds like a duplicate of #10958 (and #24543, etc)

**Comment by alwaysbespoke** [comment] 2018-04-24 23:34
I'm going to test and post the results.

Also, would you say that "select" is the best wait-forever method in go?

**Comment by alwaysbespoke** [comment] 2018-04-25 03:45
Using the select{} solves the problem entirely. It allows for spinning up goroutines that handle https requests without locking up.

**Comment by FiloSottile** [comment] 2018-04-25 04:09
Closing as a duplicate of #10958

> Also, would you say that "select" is the best wait-forever method in go?

Yep, `select {}` is the appropriate way to block a goroutine forever, but in most cases you'll want to coordinate with a `sync.Group` or channel instead.

**Closed by FiloSottile** 2018-04-25 04:09 UTC
Labels: NeedsInvestigation

**Comment by davecheney** [comment] 2018-04-25 04:27
Deleting the Go statement on the previous line achieves the same thing.
