### ISSUE TITLE
What the meaning about the sentences of the Context section.

### ISSUE THREAD

**Issue by wddpct** [golang/go#27331] opened 2018-08-29 06:42 UTC
[the Context section link](https://github.com/golang/go/wiki/CodeReviewComments#contexts)

I am confused with the flowing sentences.
A function that is never request-specific may use context.Background(), but err on the side of passing a Context even if you think you don't need to. The default case is to pass a Context; only use context.Background() directly if you have a good reason why the alternative is a mistake.

Can someone help to explain it with codes or something?

**Comment by agnivade** [comment] 2018-08-29 06:53
Hi @wddpct ,

This appears to be a question rather than a Go bug. We do not use the issue tracker for general discussions or questions like these. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

You might want to take a look at [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.

Closing since this is not a bug.

**Closed by agnivade** 2018-08-29 06:53 UTC
