### ISSUE TITLE
crypto/boring: rebase dev.boringcrypto.go1.17 to 1.17.1

### ISSUE THREAD

**Issue by derekparker** [golang/go#48520] opened 2021-09-21 17:22 UTC
Hello,

I'm opening this issue simply to request that the dev.boringcrypto.go1.17 branch be updated to 1.17.1 from the rc2 version that it is currently at. This will help unblock any downstream effort which is based on this branch for FIPS reasons.

**Comment by seankhliao** [comment] 2021-09-21 17:25
Duplicate of #48391

**Closed by seankhliao** 2021-09-21 17:25 UTC
