### ISSUE TITLE
archive/zip does not set proper CRC, size and modification date/time

### ISSUE THREAD

**Issue by Fale** [golang/go#28602] opened 2018-11-05 16:35 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fale/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/fale/go"
GOPROXY=""
GORACE=""
GOROOT="/opt/go1.11"
GOTMPDIR=""
GOTOOLDIR="/opt/go1.11/pkg/tool/linux_amd64"
GCCGO="/bin/gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build558580817=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://play.golang.org/p/4_L3bNL6b9n

### What did you expect to see?

those should be set properly:
* modification time (2 bytes offset 10)
* modification date (2 bytes offset 12)
* CRC (4 bytes offset 14)
* compressed size (4 bytes offset 18)
* uncompressed size is (4 bytes offset 22)

### What did you see instead?
All those values are set to 0

**Comment by DemonWav** [comment] 2018-11-05 17:03
I don't believe this is an issue.

Please refer to the [Data descriptor](https://en.wikipedia.org/wiki/Zip_(file_format)#Data_descriptor) section, quoted here:

> If the bit at offset 3 (0x08) of the general-purpose flags field is set, then the CRC-32 and file sizes are not known when the header is written. The fields in the local header are filled with zero, and the CRC-32 and size are appended in a 12-byte structure (optionally preceded by a 4-byte signature) immediately after the compressed data:
>
> Offset | Bytes | Description[24]
> -- | -- | --
> `0` | `0/4` | Optional data descriptor signature = 0x08074b50
> `0/4` | `4` | CRC-32
> `4/8` | `4` | Compressed size
> `8/12` | `4` | Uncompressed size

In the example given, The general-purpose flags field is `0x08`, which indicates that the data descriptor is used instead. This makes sense because the file header is created before any information about the data in the file is given.

In the output from the above example, the data descriptor signature `0x08074b50` is present at offset 58.

**Comment by dsnet** [comment] 2018-11-05 17:30
Closing as "working as intended". @DemonWav is correct that `zip` uses the data descriptor header. This enables the implementation to output zip files in a streaming manner without the need to perform a seek operation back to the front to populate the fields that you are interested in.

Go's usage data descriptors still outputs a valid zip file. The zip format unfortunately gives the illusion that you can parse an archive in a streaming read manner, when that is not a guarantee provided by the format.

**Closed by dsnet** 2018-11-05 17:30 UTC

**Comment by Fale** [comment] 2018-11-05 17:31
sadly there are systems that consider the file as invalid, but I do understand the point and I'll look for a different solution for those cases.

thanks

**Comment by theckman** [comment] 2018-11-05 17:32
@Fale if you can think of a good way to edit the standard library to do what you want, and it doesn't depend on anything special, you could maybe "fork" it and pull it in as a dependency. That may be more work than trying to find another solution.

**Comment by dsnet** [comment] 2018-11-05 17:36
> sadly there are systems that consider the file as invalid, but I do understand the point and I'll look for a different solution for those cases.

Yea, I understand. The situation is unfortunate. Had it been more apparent earlier on that such incorrect parsers were so prevalent, perhaps the Go implementation would have taken a different approach.

However, it can't be changed without unless we buffer the entire file (which is non-performant), or change the API to accept an `io.WriteSeeker`. An API change is unlikely to accepted to support this use-case.

**Comment by Fale** [comment] 2018-11-05 17:39
could it be possible to implement a method to be call at close time that re-reads the buffer and calculate those? I was thinking about implementing something like that. and if this would be a sensible path, this method could be an addition to the api that would not break it (and be callable at programmer will, so no performance hit if not needed)

**Comment by dsnet** [comment] 2018-11-05 17:46
I recommend giving #23301 a read. There was some discussion about APIs and pros/cons for this feature.

**Comment by Fale** [comment] 2018-11-05 17:55
tanks @dsnet  :)
