### ISSUE TITLE
cmd/go: go get (unzip) cannot handle unicode path

### ISSUE THREAD

**Issue by leitzler** [golang/go#32617] opened 2019-06-14 08:47 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes (and tip)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/leitzler/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/leitzler/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/tmp.OCzVOwKWBd/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build567694577=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Tried to fetch a third party dependency that contained a folder/file with unicode chars.

To reproduce I've created [a repo](https://github.com/modsdemo/unicode) that contains a folder & file with a unicode char, in package:
`github.com/modsdemo/unicode/🦡 `

It can be used in a Go program, but can't be fetched using `go get` since `unzip` will fail to extract it:
```
$ cd $(mktemp -d) && go mod init x
$ go get github.com/modsdemo/unicode
go: finding github.com/modsdemo/unicode latest
go: downloading github.com/modsdemo/unicode v0.0.0-20190614083133-991638b734de
go: extracting github.com/modsdemo/unicode v0.0.0-20190614083133-991638b734de
-> unzip /home/leitzler/go/pkg/mod/cache/download/github.com/modsdemo/unicode/@v/v0.0.0-20190614083133-991638b734de.zip: malformed file path "\U0001f9a1/\U0001f9a1.go": invalid char '\U0001f9a1'
package github.com/modsdemo/unicode: unknown import path "github.com/modsdemo/unicode": unzip /home/leitzler/go/pkg/mod/cache/download/github.com/modsdemo/unicode/@v/v0.0.0-20190614083133-991638b734de.zip: malformed file path "\U0001f9a1/\U0001f9a1.go": invalid char '\U0001f9a1'
```

### What did you expect to see?
The dependency fetched

### What did you see instead?
Unzip failing to extract the module zip

**Comment by cuonglm** [comment] 2019-06-14 09:32
See https://github.com/golang/go/blob/55d31e16c12c38d36811bdee65ac1f7772148250/src/cmd/go/internal/module/module.go#L378

**Comment by FiloSottile** [comment] 2019-06-14 18:17
Closing as duplicate of #29101, please let me know if you think that's not correct.

**Closed by FiloSottile** 2019-06-14 18:17 UTC
