### ISSUE TITLE
"internal compiler error: assertion failed" with generic code

### ISSUE THREAD

**Issue by quan-nguyen2** [golang/go#53834] opened 2022-07-13 11:23 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 darwin/arm64
</pre>

it happens with go playground also (with version 1.18)

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
```
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/quannk/Library/Caches/go-build"
GOENV="/Users/quannk/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/quannk/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/quannk/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.18.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.18.4/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/quannk/ad/advertisement/golang/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g3/kggtblcx2y14_mlgh0z6pmzc0000gp/T/go-build531919184=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</pre></details>

### What did you do?

the bug can be reproduced here:

https://go.dev/play/p/Ckg1z8KKEd8

### What did you expect to see?

no error when compile the program

### What did you see instead?

error when compile
```
./prog.go:7:10: internal compiler error: assertion failed
```

**Comment by quan-nguyen2** [comment] 2022-07-13 11:29
this bug is the same with https://github.com/golang/go/issues/53762
but it happens on 1.18.4 as well (1.18.4 is marked as stable version)

**Comment by hopehook** [comment] 2022-07-13 11:59
The patch https://go-review.googlesource.com/c/go/+/416736 can fix this issue also.

**Comment by seankhliao** [comment] 2022-07-13 13:32
Duplicate of #53762

**Closed by seankhliao** 2022-07-13 13:32 UTC
