### ISSUE TITLE
https://go.dev/VERSION does not reflect the latest release

### ISSUE THREAD

**Issue by icemarkom** [golang/go#50107] opened 2021-12-11 16:44 UTC
For 1.17.5 release, https://go.dev/VERSION has not updated to reflect the latest release.

**Comment by seankhliao** [comment] 2021-12-11 16:51
Duplicate of #42744

**Closed by seankhliao** 2021-12-11 16:51 UTC

**Comment by icemarkom** [comment] 2021-12-11 16:52
Oh dear me, embarrassing :-)
