### ISSUE TITLE
Inconsistent Vendoring, Go list failed

### ISSUE THREAD

**Issue by Mohitp98** [golang/go#34818] opened 2019-10-10 12:15 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gslab/.cache/go-build"
GOENV="/home/gslab/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/gslab/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/gslab/terra:/usr/local/go/bin:/home/gslab/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build889549718=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
I'm working on Github Api's with Go, 

Code is as follow ---->
package main

import (
	"context"
	"fmt"
	"os"
	"github.com/google/go-github/github"
	"golang.org/x/oauth2"
)

type Package1 struct {
	FullName    string
	Description string
	ForksCount int
}

func main() {

	ctx := context.Background()
	ts := oauth2.StaticTokenSource(&oauth2.Token{AccessToken: os.Getenv("Github_Token")})

	tc := oauth2.NewClient(ctx, ts)

	client := github.NewClient(tc)

	//list all repos for authenticated user
	repos, _, err := client.Repositories.Get(ctx, "Mohitp98", "Appin2018")
	//fmt.Println(os.Getenv("Github_Token"))

	if err != nil {
		fmt.Printf("Problem occured while getting info %v \n", err)
		os.Exit(1)
	}

	pack := &Package1{
		FullName:    *repos.FullName,
		Description: *repos.Description,
		ForksCount:  *repos.ForksCount,
	
	}

	fmt.Printf("%v\n", pack)
}
 

ERROR --->

go list failed on /usr/local/go/src/runtime: go: inconsistent vendoring in /usr/local/go/src:
	go.mod requires github.com/google/go-github v17.0.0+incompatible but vendor/modules.txt does not include it.
	run 'go mod tidy; go mod vendor' to sync

**Comment by bcmills** [comment] 2019-10-10 12:42
See https://github.com/golang/go/issues/34657#issuecomment-537546118.

Please also ensure that when you file an issue, you run `go env` from the same working directory as the `go` command that produced the error.

**Comment by bcmills** [comment] 2019-10-10 12:43
Duplicate of #34657

**Closed by bcmills** 2019-10-10 12:43 UTC
