### ISSUE TITLE
pkg.go.dev: Comments in examples are not always preserved

### ISSUE THREAD

**Issue by divjotarora** [golang/go#40726] opened 2020-08-12 14:19 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.14.4
</pre>

### What did you do?

I compared this [example](https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo@v1.3.5?tab=doc#example-WithSession) on pkg.go.dev, with the [source code](https://github.com/mongodb/mongo-go-driver/blob/v1.3.5/mongo/crud_examples_test.go#L459).

### What did you expect to see?

I expected to see the comments in the source code present in the example as well.  The same [example](https://godoc.org/go.mongodb.org/mongo-driver/mongo#example-WithSession) on GoDoc has all of the expected comments.

### What did you see instead?

The example on pkg.go.dev only has the first comment, which is also the only comment that's on the same line as other code. The rest of the comments in the source code are on separate lines.

**Comment by jamalc** [comment] 2020-08-12 15:17
Duplicate of #40710

**Closed by jamalc** 2020-08-12 15:17 UTC
