### ISSUE TITLE
x/tools/gopls: avoid including explicit type parameters in completion if they will be inferred

### ISSUE THREAD

**Issue by d-enk** [golang/go#64480] opened 2023-11-30 09:42 UTC
Every time you have to remove them, because in most cases they are not needed

![Peek 2023-11-30 12-41](https://github.com/golang/vscode-go/assets/43112758/781cc6ec-d908-4f8c-a8f1-4555688d8337)

There may already be a way to disable them, but then it is not obvious

**Comment by hyangah** [comment] 2023-12-07 03:17
Duplicate of #51783 

Thanks for finding the previously filed issue. @rogeryk

**Closed by hyangah** 2023-12-07 03:17 UTC
Labels: FeatureRequest, gopls, Tools, gopls/completion
