### ISSUE TITLE
proposal: implement other HTTP methods for http package affected/package: net/http

### ISSUE THREAD

**Issue by araujo88** [golang/go#56166] opened 2022-10-12 00:46 UTC
### Author background
 * **Would you consider yourself a novice, intermediate, or experienced Go programmer?**
   Intermediate
 * **What other languages do you have experience with?**
C, C++, Python, Assembly, Javascript, Java
 
 ### Proposal
 * **What is the proposed change?**
 
Add `Put`, `Delete` and other remaining HTTP methods to the file `net/http/client.go`. Currently it only has GET and POST requests implemented.
 
 * **Please describe as precisely as possible the change to the language.**
 
This would add the remaining HTTP methods (PUT, PATCH, DELETE, OPTIONS, HEAD) while using the http client receiver in the package `net/http`, so the user won't need to implement these methods by hand using `http.NewRequest(method, url, body)`.
 
 * **What would change in the language spec?**
 
 I can return to this question and add details if necessary.
 
 * **Please also describe the change informally, as in a class teaching Go.**
 
This change would include the remaining HTTP methods such as PUT, PATCH, DELETE and so on to the `net/http`. 
 
 * **Is this change backward compatible?**
  Yes.
   
   * Breaking the Go 1 compatibility guarantee is a large cost and requires a large benefit.
     Show example code before and after the change.
   * **Before**
   * **After**
 * **Orthogonality: how does this change interact or overlap with existing features?**
   This has a clear, very specific use case, in which it can be preferred to existing features. It is not usable in any other cases. Thus I think it avoids confusing the use of other features.
 * **Is the goal of this change a performance improvement?**
   No
   
   * **If so, what quantifiable improvement should we expect?**
   * **How would we measure it?**
 
 ### Costs
 * **Would this change make Go easier or harder to learn, and why?**
  Easier, because the user won't have to implement PUT, PATCH, DELETE, etc. HTTP methods by hand.

 * **What is the cost of this proposal? (Every language change has a cost).**
   I believe the cost is minimal.
 * **How many tools (such as vet, gopls, gofmt, goimports, etc.) would be affected?**
   None.
 * **What is the compile time cost?**
   I believe this should be cheap at compile time.
 * **What is the run time cost?**
   I don't believe there is any additional run time cost in the cases where this will be used.
 * **Can you describe a possible implementation?**
 
Example: for a PUT request, the addition in the file `go/src/net/http/client.go` would be:

```
func Put(url, contentType string, body io.Reader) (resp *Response, err error) {
	return DefaultClient.Put(url, contentType, body)
}

func (c *Client) Put(url, contentType string, body io.Reader) (resp *Response, err error) {
	req, err := NewRequest("PUT", url, body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	return c.Do(req)
}

```

 * **Do you have a prototype? (This is not required.)**

**Comment by seankhliao** [comment] 2022-10-12 17:25
Duplicate of #22841

**Closed by seankhliao** 2022-10-12 17:25 UTC
Labels: Proposal
