### ISSUE TITLE
database/sql: no way to protect driver.Connector.Connect(), driver.Conn.Close(), driver.Stmt.Close() from blocking

### ISSUE THREAD

**Issue by georgysavva** [golang/go#38185] opened 2020-03-31 19:30 UTC
I was reading `database/sql` source code, looking into how it manages context when integrating with third party drivers and how context can be used to timeout operations that might block due to network failures. I think I found a few flaws:

1. `sql.DB` calls `driver.Connector.Connect(ctx)` to establish a new connection via the driver, and it does pass a context into it. One of those calls happens inside [db.openNewConnection()](https://github.com/golang/go/blob/5db079d2e5f97952be288c28a3a0690a523efdce/src/database/sql/sql.go#L1140) function, but this function is a part of the background goroutine [db.connectionOpener()](https://github.com/golang/go/blob/5db079d2e5f97952be288c28a3a0690a523efdce/src/database/sql/sql.go#L740) and the context is a background context and it takes the beginning [there](https://github.com/golang/go/blob/5db079d2e5f97952be288c28a3a0690a523efdce/src/database/sql/sql.go#L731). So the driver won't receive a request bounded context from the user (as it would receive in this [call](https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1283)) and the user won't be able to timeout connection establishment via context and the background goroutine `db.connectionOpener()` might block in case of a network error. 
The driver might have an independent `connect_timeout` setting that it will use in `.Connect()` to pass it to `net.Dialer.Timeout`, but it only works for the original connection dial and driver may need to exchange some system messages with the database and those read operations might block if the network is unreliable. A request bounded context with timeout set by the user would solve it. But regardless of the timeout I think it's a bit weird from the driver perspective, that sometimes it receives a background context from `sql` and sometimes it receives request bounded context from the user. 
My actionable here is to always pass a request bounded context from the user into `driver.Connector.Connect(ctx)`.
2. `sql.DB` calls `driver.Conn.Close()` to signal the driver to close the connection, this call might include network operation and in case of a failure will block the caller, some places there `sql` calls `.Close()`:
[here](https://github.com/golang/go/blob/5db079d2e5f97952be288c28a3a0690a523efdce/src/database/sql/sql.go#L1166), [and here](https://github.com/golang/go/blob/5db079d2e5f97952be288c28a3a0690a523efdce/src/database/sql/sql.go#L1374). If the first call blocks, it will block the background goroutine `db.connectionOpener()`, if the second call blocks, it will block the main user goroutine. Another affected place is [.closeDBLocked](https://github.com/golang/go/blob/5db079d2e5f97952be288c28a3a0690a523efdce/src/database/sql/sql.go#L547) function: it sequentially closes all connections in the pool on `db.Close()` and if one of those `Conn.Close()` blocks, it won't be able to close other connections in the pool. 
I think it would be better to close driver connection asynchronously (in a separate gorutine) with a reasonable, default timeout: e.g. 5 seconds. Or the original idea of the `sql` library, that driver itself must ensure that `Conn.Close()` doesn't block?
3. The last thing is `driver.Stmt.Close()`: `sql` doesn't pass context into it and calls it in a lot of places, the most obvious [here](https://github.com/golang/go/blob/5db079d2e5f97952be288c28a3a0690a523efdce/src/database/sql/sql.go#L2698). Driver `Stmt.Close()` call most likely will involves network operations that might block and it will hang the main user goroutine. 
I think `sql` should pass a request bounded context from the user into `Stmt.Close()`, because `Stmt.Close` is a user facing operation and user should be able to timeout it. 

Please let me know If I missing something. 

### What version of Go are you using (`go version`)?

<pre>
go version go1.14 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/georgysavva/Library/Caches/go-build"
GOENV="/Users/georgysavva/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/georgysavva/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="..."
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/gd/lq1x2k352p3d74_5zby2jjbc0000gn/T/go-build959211670=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

**Comment by ianlancetaylor** [comment] 2020-03-31 20:02
CC @kardianos

**Comment by kardianos** [comment] 2020-04-01 00:26
Correct on all counts.

Closing a connection is unlikely to involve a network round-trip. Or rather, I don't know of any that would require that, so I'm less worried about this.

Closing a Stmt will always require a network round trip, unless the entire connection is broken. The hard thing with this is the that the sql package doesn't expose a Stmt object, just a Stmt pool object. Which makes synchronous, context bounded closing harder.

Lastly, yes, the connection opener context improves the situation, but it doesn't address all the cases. I'm not 100% sure we can fix this with the current API, but you could try / make suggestions on how to best address this.

---

Some of these issues are caused by the original API that will be hard to change unless we issue a v2. For somethings, simply better documentation, stating that drivers should include a sane timeout for certain calls would also be an improvement.

**Comment by georgysavva** [comment] 2020-04-01 12:14
If you don't expect `Conn.Close()` to block due to a network operation, I think it should be better reflected in the `driver` documentation. Because I found out, that [pgx](https://github.com/jackc/pgx) postgres driver does include both write and read network operation in `Conn.Close()`: [pgx close](https://github.com/jackc/pgconn/blob/e4f3224f4c6d615b7199c9a606c4e3385efd1f21/pgconn.go#L507). And also [pq](https://github.com/lib/pq) postgres driver, include a write operation (that can also block): [pq close](https://github.com/lib/pq/blob/356e267cd3f45ee1303b7d8765e3583cb949950e/conn.go#L815). 
BTW (as a side question) regardless of separate write and read operations, driver will call the underlying `net.TCPConn.Close()` at least, can this call block? As far as I understand it should send some termination signal to the server? 

Yeah, passing context to `Stmt.Close()` would require a significant change in `sql` code, because of the pool. So I think at least we could add some notes to the documentation, that the driver should use some default timeout for `Stmt.Close()`

Regarding the connection opener, I thought we could pass a request bounded context from the user into `connector.Connect()` the following way:
In [.conn()](https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1233) function, instead of putting just a channel, we bound and put together  both the result channel and the context into `db.connRequests` map. And after, in [.maybeOpenNewConnection()](https://github.com/golang/go/blob/8e6a8d9e282a6f9aeab5635c75c223129f5ab61f/src/database/sql/sql.go#L1119) we retrieve actual `reqKeys` and corresponding contexts from the `db.connRequests` map and send those contexts to `db.openerCh` instead of just an empty struct. And finally, In [.connectionOpener()](https://github.com/golang/go/blob/8e6a8d9e282a6f9aeab5635c75c223129f5ab61f/src/database/sql/sql.go#L1129) we receive the context and can pass it to the `db.connector.Connect(ctx)`.
But I realized the it's wrong. Imagine the following situation:
Process A requests a connection and it has a really short timeout (0.5 seconds), we start opening a connection for it (with context from the process A) and after 0.1 seconds we get a free connection returned to the pool and give it to the process A, so it's no longer waiting and can use the connection. In the meantime process B requests a connection without timeout at all. But right after that, connection opening that we initiated for the process A (with context from the process A) with timeout 0.5, failed with a timeout error and we sending this error to process B [here](https://github.com/golang/go/blob/8e6a8d9e282a6f9aeab5635c75c223129f5ab61f/src/database/sql/sql.go#L1152), because it waits for a result. So in the outcome process B will receive a timeout error in less than 0.5 seconds, without specifying timeout at all.
It appeared to me that this solution doesn't work and to improve the situation `sql` package could improve the docs and state, that `Connector.Connect(ctx)` can be called from a background goroutine with a background context that doesn't have a timeout. And the driver is responsible for making this call timeout and don't block with some configurable setting.

**Comment by georgysavva** [comment] 2020-04-22 08:27
Hi. Any update on this?

**Comment by kardianos** [comment] 2020-04-22 14:54
@georgysavva I could look into updating the docs on the close. I'll also annotate the database/sql/v2 tracking issue.

I'll look into the connection opener. Thanks for the ping.

**Comment by georgysavva** [comment] 2020-04-22 17:26
Thanks for the reply. Waiting for you feedback on connection opener.

**Comment by kardianos** [comment] 2020-04-28 14:37
@georgysavva I agree that the background connection opener makes it difficult to provide a relevant context for all situations. Can you review the above CL to see if it addresses your concerns? If you have a gerrit account, please leave feedback on the CL itself, otherwise feedback here is fine too. Thanks.

**Comment by georgysavva** [comment] 2020-04-28 15:36
LGTM. Thanks!

**Comment by georgysavva** [comment] 2020-04-28 15:38
Sorry, I forgot about the third thing. Stmt.Close() shouldn't we update docs for it as well?

**Comment by kardianos** [comment] 2020-04-28 17:05
Goood point, I'll update in just a bit.

**Comment by kardianos** [comment] 2020-04-28 20:24
@georgysavva I've updated and included Stmt.Close as well.

**Comment by georgysavva** [comment] 2020-04-28 20:36
Thanks!

**Closed** 2020-04-28 20:43 UTC
Labels: NeedsInvestigation
