### ISSUE TITLE
slice: negative indexing doesn't panics

### ISSUE THREAD

**Issue by slavablind91** [golang/go#29629] opened 2019-01-09 12:25 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/slava/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/slava/go"
GOPROXY=""
GORACE=""
GOROOT="/home/slava/go1.11"
GOTMPDIR=""
GOTOOLDIR="/home/slava/go1.11/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build846395121=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I try to test some code like this
<pre>
type stack []int

func (s *stack) last() int {
    return (*s)[len(*s)-1]
}

func Test_last(t *testing.T) {
    s := stack{}
    s.last() // should panics
}
</pre>

### What did you expect to see?

panic

### What did you see instead?

no panic

**Comment by ianlancetaylor** [comment] 2019-01-09 13:51
Please show us a complete standalone example.  If you are using `go test`, use `go test -test.v` to make sure that your test is being run.  Note that a more typical name for a test function would be `TestLast`.

This Go program panics when I run it:

```Go
package main

type stack []int

func (s *stack) last() int {
    return (*s)[len(*s)-1]
}

func last() {
    s := stack{}
    s.last() // should panics
}

func main() {
	last()
}
```

**Comment by bcmills** [comment] 2019-01-09 13:53
Please also test against the most recent patch release: `go1.11.4`, not `go1.11`.

**Comment by mvdan** [comment] 2019-01-09 14:10
If this is fixed in 1.11.4 and tip, it's very likely just a duplicate of https://github.com/golang/go/issues/27289, which was backported into 1.11.1.

**Comment by slavablind91** [comment] 2019-01-09 14:36
I had similar behavior like in #27289.
Now with go 1.11.4 still reproduce this.
In playground this code is panics.

**Comment by ianlancetaylor** [comment] 2019-01-09 14:38
If you are still having this problem, please show us a complete standalone example.  Thanks.

**Comment by slavablind91** [comment] 2019-01-09 14:40
With go 1.11.4 panic occurs

**Comment by ianlancetaylor** [comment] 2019-01-09 14:42
Thanks, so it sounds like this bug has been fixed.

**Comment by mvdan** [comment] 2019-01-09 14:43
Well, then it's clearly a duplicate. Thanks for the follow-up.

**Closed by ianlancetaylor** 2019-01-09 14:42 UTC
Labels: NeedsInvestigation, WaitingForInfo
