### ISSUE TITLE
build: fedora rpm packager incorrectly throws away *_test* instead of *_test.go

### ISSUE THREAD

**Issue by nhorman** [golang/go#19155] opened 2017-02-17 19:06 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go-1.8

### What operating system and processor architecture are you using (`go env`)?
linux x86_64

### What did you do?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/builddir/build/BUILD/openshift-git-45.423f434/_build:/builddir/build/BUILD/openshift-git-45.423f434/_thirdpartyhacks:/builddir/build/BUILDROOT/openshift-3.0.2.0-0.1.git.45.423f434.el7exarch.x86_64/usr/share/gocode:/usr/lib/golang:/usr/share/gocode:/usr/lib/golang"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build897335929=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

If possible, provide a recipe for reproducing the error.
Trying to build openshift, and doing so on a system without root access.  I get the following error:

go install -p 1 -ldflags '-X github.com/openshift/origin/pkg/version.majorFromGit=3 -X github.com/openshift/origin/pkg/version.minorFromGit=0+ -X github.com/openshift/origin/pkg/version.versionFromGit=v3.0.2.0-45-g423f434 -X github.com/openshift/origin/pkg/version.commitFromGit=423f434 -X k8s.io/kubernetes/pkg/version.gitCommit=44c91b1 -X k8s.io/kubernetes/pkg/version.gitVersion=v1.1.0-alpha.0-1605-g44c91b1' github.com/openshift/origin/cmd/openshift
go install vendor/golang_org/x/crypto/chacha20poly1305: open /usr/lib/golang/pkg/linux_amd64/vendor/golang_org/x/crypto/chacha20poly1305.a: permission denied

Its very odd because the chacha20poly1305 package is already installed on the system, and is within GOPATH, so go install should not, by my understanding, try to install that package

### What did you expect to see?
I expected to see chacha20poly1305.a not get installed and the compilation of openshift complete

### What did you see instead?

see above.

**Comment by ianlancetaylor** [comment] 2017-02-17 19:27
Can you show us the output of `go list -f '{{.Stale}} {{.StaleReason}}' vendor/golang_org/x/crypto/chacha20poly1305` ?

**Comment by mikesmitty** [comment] 2017-02-18 19:30
I'm also receiving this error on 1.8, and this is the output from the go list command you posted:

[dev@dev1 httpserver]$ go install httpserver.go
go install vendor/golang_org/x/crypto/chacha20poly1305: open /usr/lib/golang/pkg/linux_amd64/vendor/golang_org/x/crypto/chacha20poly1305.a: permission denied

[dev@dev1 httpserver]$ go list -f '{{.Stale}} {{.StaleReason}}' vendor/golang_org/x/crypto/chacha20poly1305
true build ID mismatch

**Comment by ianlancetaylor** [comment] 2017-02-19 02:27
"build ID mismatch" is not what I expected to see.  That indicates that something really did change in the package, or one of its dependencies, or in the compiler itself, and the package needs to be reinstalled.

But why would this happen for that specific package for two different people?  I have no idea.  I have not been able to recreate the problem myself.  Can anyone recreate it consistently?

**Comment by mikesmitty** [comment] 2017-02-19 03:55
I got the error when trying `go build httpserver.go` on this folder of the following repo:
https://github.com/coreos/go-systemd/tree/master/examples/activation/httpserver

I uninstalled 1.8, went back to 1.7.5 so I could continue working, then reinstalled 1.8 later today, and now it isn't happening anymore. Not sure what happened, but it's fixed for me.

**Comment by mikesmitty** [comment] 2017-02-19 07:30
I've been testing different things to try and nail down what could be causing the issue. I haven't yet been able to reproduce the issue outside of the rpmbuild process, but I did find that the sha1 sums of everything in the `/usr/lib/golang/pkg/linux_amd64/vendor/golang_org/x/crypto` folder match on working and non-working instances.

**Comment by nhorman** [comment] 2017-02-20 12:37
I'll get you the go list -f '{{.Stale}} {{.StaleReason}}'  today.  Please note that I'm building this from an rpm, and the chachapoly library is provided by a dependent package, which may be introducing some problems here (that is to say, golang has decided that, through some set of imports that chachapoly is needed, and even though its provided in GOPATH, its provided by the golang-bin package, and the expectation of the rpm build environment is that golang will link to the library.

**Comment by jcajka** [comment] 2017-02-20 13:07
My observation is that since go1.8 (some )test files are part of the buildid calculation and were not previously. We in Fedora, we ship *_test* files in separate sub-package. With go1.8 and some libs vendored in stdlib we see the errors that nhornman reported, surprisingly not with all stdlib tests though.

To test it on Fedora install golang "dnf install golang" and then "go list -f '{{.Stale}} {{.StaleReason}}' vendor/golang_org/x/crypto/chacha20poly1305", you should see stale package. Afterwards install "dnf install golang-tests" and the stale should be gone. This assumes Fedora rawhide(go1.8). I have double checked that I haven't mistakenly included some non-test files in the tests sub-package, but I haven't noticed any(double/triple check welcomed).

I'm about to investigate further.

**Comment by jcajka** [comment] 2017-02-20 13:10
Oh... and temp workaround for rpmbuild(mock build) should be to build require golang-tests.

**Comment by nhorman** [comment] 2017-02-20 14:09
go list -f '{{.Stale}} {{.StaleReason}}'
true no install target

Not sure if that helps or not...

**Comment by nhorman** [comment] 2017-02-20 14:12
@jcajka , your workaround seems to fix the chacha issue, but it still seems like there is a bigger problem here (or perhaps just a discussion that needs to be had),  when using go install, I'm using go install, I'm unsure why files are attempting to be written to /usr rather than to the local rpm buildroot, as the local buildroot is whats specified first in the GOPATH.  It seems like the current go install behavior is anathema to how rpm (and most packaging systems) operate.  If the answer is that go build needs to be used rather than go install to prevent errant out of buildroot installation, I suppose thats fine, but it would be good to have a conclusion on that

**Comment by ianlancetaylor** [comment] 2017-02-20 18:53
@nhorman The command to run was broken onto two lines above.  You only ran the first line.  Here is the command again, on one line:

    go list -f '{{.Stale}} {{.StaleReason}}' vendor/golang_org/x/crypto/chacha20poly1305

**Comment by ianlancetaylor** [comment] 2017-02-20 18:56
@jcajka The build ID computation is relatively simple and as far as I can tell does not include any test files.  See the function `computeBuildID` in cmd/go/pkg.go (on tip this file has moved to cmd/go/internal/load/pkg.go, but the function is essentially unchanged).  Please let us know what you discover.

**Comment by jcajka** [comment] 2017-02-24 09:40
@ianlancetaylor I have been checking it and I really didn't see a way it failing there(actually 2 weeks ago, but couldn't get back to this until now), then I just again double checked the regexp and saw that chacha's test vectors are in regular source file.

It has been actually fixed in x/crypto by commit 854ae91cdcbf914b499b1d7641d07859f3653481, but as it seems it hasn't been pulled to the vendored version included in stdlib...

So fix should be update/respin of vendored deps.

**Comment by ianlancetaylor** [comment] 2017-02-24 18:21
For the record, the commit referenced in the previous comment is https://golang.org/cl/35875.

**Comment by ianlancetaylor** [comment] 2017-02-24 18:28
@jcajka Thanks for sorting this out.  I will send a CL for tip.

**Comment by ianlancetaylor** [comment] 2017-02-24 18:54
Reopening because we should copy this into the 1.8 release branch.

**Comment by jcajka** [comment] 2017-02-27 15:07
@ianlancetaylor thanks for quick fix, awesome that it will get in to 1.8.1 too :)

**Comment by rsc** [comment] 2017-04-05 15:32
It's not obvious to me that this fix belongs in the Go 1.8.1 branch. The RPM generator here is broken, right? They're excluding `*_test*` from the distribution instead of `*_test.go`. The former is simply incorrect. A file named foo_test_bar.go should _not_ be silently discarded by RPM packaging.

I'm inclined not to cherry-pick this. Fixing the RPM generator will let them issue new RPMs for both Go 1.8 and Go 1.8.1 that works just fine.

Thoughts, @ianlancetaylor?

**Comment by ianlancetaylor** [comment] 2017-04-05 18:34
@rsc You're right.  I looked at the RPM spec file.  I'm fine with not backporting this.

**Closed by ianlancetaylor** 2017-04-05 18:34 UTC
