### ISSUE TITLE
net/mail: q decoding does not support windows-1252 and other encodings

### ISSUE THREAD

**Issue by jmhodges** [golang/go#7140] opened 2014-01-17 08:59 UTC
<pre>I have nice acquitances whose email addresses I would like to parse correctly, but they,
oddly, have chosen to use windows-1252 to encode their email address. In
mail.ParseAddress, any character encodings other than utf-8 and iso-8859-1 are not
handled.

It would be nice to support windows-1252 with a preference towards being able to plug
more charsets in. (Perhaps, with a similar interface as go.text/transform#Transformer.)

Example:

	str := &quot;=?windows-1252?Q?Michael_Bo=DFlet?= &lt;michael.bosslet@example.com&gt;&quot;
	a, err := mail.ParseAddress(str)
	if err != nil {
		log.Fatalf(&quot;%s&quot;, err)
	}
	log.Printf(&quot;%s&quot;, a)

This will crash, unfortunately.</pre>

**Comment by bradfitz** [comment] 2015-03-30 13:46
This seems like a duplicate of #7079

I'm closing this one. Please move any unique comments there.

**Closed by bradfitz** 2015-03-30 13:46 UTC
Labels: accepted, release-none, repo-main
