### ISSUE TITLE
cmd/godoc: golang.org out of date

### ISSUE THREAD

**Issue by willfaught** [golang/go#27284] opened 2018-08-27 18:31 UTC
The current state of golang.org doesn't seem to reflect v1.11. For example, v1.11 isn't listed on https://golang.org/doc/devel/release.html, and the `new concept called "modules"` link in https://golang.org/doc/go1.11#modules doesn't work because the 
https://golang.org/cmd/go/#hdr-Modules__module_versions__and_more header is undefined (but is defined on https://tip.golang.org/cmd/go/#hdr-Modules__module_versions__and_more [tip]).

Not sure the issue title prefix is right.

**Comment by FiloSottile** [comment] 2018-08-27 21:38
Duplicate of #27205

**Closed by FiloSottile** 2018-08-27 21:38 UTC
