### ISSUE TITLE
net: tips all.bash test failed: interface_test.go:74: route ip+net: invalid network interface name

### ISSUE THREAD

**Issue by wheelcomplex** [golang/go#14706] opened 2016-03-08 09:33 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version devel +beabd87 Tue Mar 8 06:02:15 2016 +0000 freebsd/amd64

2. What operating system and processor architecture are you using (`go env`)?

<pre>
GOARCH="amd64"
GOBIN="/home/rhinofly/home/ds/sandspace/go/bin.freebsd-amd64"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOOS="freebsd"
GOPATH="/home/rhinofly/home/ds/sandspace/external/:/home/rhinofly/home/ds/sandspace/golibs/"
GORACE=""
GOROOT="/home/rhinofly/home/ds/sandspace/go"
GOTOOLDIR="/home/rhinofly/home/ds/sandspace/go/pkg/tool/freebsd_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -gno-record-gcc-switches"
CXX="clang++"
CGO_ENABLED="1"
</pre>
<pre>
$ ifconfig -a
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=209b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC>
	ether 66:30:38:38:64:30
	inet 10.236.12.201 netmask 0xffffff00 broadcast 10.236.12.255 
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2 
	inet 127.0.0.1 netmask 0xff000000 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo 
</pre>
<pre>
$ uname -a
FreeBSD rhinofly-devel-800201.localdomain 11.0-CURRENT FreeBSD 11.0-CURRENT #0 r295683: Wed Feb 17 02:07:17 UTC 2016     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
</pre>

3. What did you do?
(Use play.golang.org to provide a runnable example, if possible.)

git clone https://github.com/golang/go.git tips-go && cd tips-go/src && ./all.bash

4. What did you expect to see?

build done without error and warning.

5. What did you see instead?
<pre>
--- FAIL: TestInterfaces (0.00s)
	interface_test.go:74: route ip+net: invalid network interface name
FAIL
FAIL	net	2.240s
</pre>

detail data by fmt.Printf(%v):
<pre>
all interfaces data:
ift=[{1 1500  dc:05:00:00:00:00:00:00:00:ca:9a:3b:00:00:00:00:94:49:13:00:00:00:00:00:00:00:00:00:00:00:00:00:1f:61:0a:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:44:63:57:67:00:00:00:00:08:dc:76:04:00:00:00:00:18:1f:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:06:00:00:00:00:00:00:00:01:00:00:00:00:00:00:00:6b:f0:dc:56:00:00:00:00:3f:f6:05:00:00:00:00:00:38:12:01:00:06:03:06:00 up|broadcast|multicast} {2 16384  00:40:00:00:00:00:00:00:00:00:00:00:00:00:00:00:9d:ac:01:00:00:00:00:00:00:00:00:00:00:00:00:00:9d:ac:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:2b:d2:32:0c:00:00:00:00:2b:d2:32:0c:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:0f:0e:00:00:00:00:00:00:01:00:00:00:00:00:00:00:6a:f0:dc:56:00:00:00:00:5d:8e:08:00:00:00:00:00:38:12:02:00:18:03:00:00 up|loopback|multicast}]

test failed:
ifi={1 1500  dc:05:00:00:00:00:00:00:00:ca:9a:3b:00:00:00:00:94:49:13:00:00:00:00:00:00:00:00:00:00:00:00:00:1f:61:0a:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:44:63:57:67:00:00:00:00:08:dc:76:04:00:00:00:00:18:1f:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:06:00:00:00:00:00:00:00:01:00:00:00:00:00:00:00:6b:f0:dc:56:00:00:00:00:3f:f6:05:00:00:00:00:00:38:12:01:00:06:03:06:00 up|broadcast|multicast}, ifxn-<nil>, err=route ip+net: invalid network interface name
</pre>

**Comment by ianlancetaylor** [comment] 2016-03-08 13:31
CC @mikioh

**Comment by mikioh** [comment] 2016-03-09 00:00
This is a duplicate of  #7849. See https://github.com/golang/go/wiki/FreeBSD.

**Closed by mikioh** 2016-03-09 00:00 UTC
Labels: OS-FreeBSD
