### ISSUE TITLE
proposal: Go 2: Alternative list initialization syntax

### ISSUE THREAD

**Issue by xbt573** [golang/go#58858] opened 2023-03-04 07:26 UTC
### Author background

- **Would you consider yourself a novice, intermediate, or experienced Go programmer?**
Intermediate
- **What other languages do you have experience with?**
Python, C#, JS/TS, Bash

### Related proposals

- **Has this idea, or one like it, been proposed before?**
#47709, #12854
  - **If so, how does this proposal differ?**
  Different syntax :)
- **Does this affect error handling?**
This proposal does not affect error handling
- **Is this about generics?**
No

### Proposal

- **What is the proposed change?**
This proposal adds alternative list initialization syntax to Go:
```go
x := [1, 2, 3]
// [1, 2, 3] == []int{1, 2, 3}
```
- **Who does this proposal help, and why?**
This syntax is easier to read, especially when dealing with matrix
- **Please describe as precisely as possible the change to the language.**
This alternative syntax is translated to old syntax, using type inference, if elements in slice has different types, then it is `[]any`:
```go
x := [1, 2, 3]
// []int{1, 2, 3}

x := [1.0, 2.0, 3.0]
// []float64{1.0, 2.0, 3.0}
//        (or 32 on x86 platforms)

x := [1, "hello", nil]
// []any{1, "hello", nil}
```
- **What would change in the language spec?**
New syntax declaration, new info about this alternative syntax
- **Please also describe the change informally, as in a class teaching Go.**
This syntax is easier to read and write than old
- **Is this change backward compatible?**
Yes, because this syntax translates to classic `[]T{}`
- **Orthogonality: how does this change interact or overlap with existing features?**
I think it doesn't

### Costs

- **Would this change make Go easier or harder to learn, and why?**
Easier, because this syntax is easier to read
- **What is the cost of this proposal? (Every language change has a cost).**
Translating this syntax to classic syntax
- **How many tools (such as vet, gopls, gofmt, goimports, etc.) would be affected?**
gopls, gofmt
- **What is the compile time cost?**
Translating this syntax to classic syntax
- **What is the run time cost?**
None
- **Can you describe a possible implementation?**
No
- **Do you have a prototype? (This is not required.)**
No

**Comment by seankhliao** [comment] 2023-03-04 14:47
Duplicate of #12854

**Closed by seankhliao** 2023-03-04 14:47 UTC
Labels: LanguageChange, v2, Proposal
