### ISSUE TITLE
x/net/html: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tr3ee** [golang/go#27704] opened 2018-09-17 02:05 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.10.3 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GORACE=""
GOTMPDIR=""
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

### What did you do?

```golang
package main

import (
	"strings"

	"golang.org/x/net/html"
)

func main() {
	r := strings.NewReader("<template><tBody><isindex/action=0>")
	html.Parse(r)
}
```

### What did you expect to see?

No panic exit.

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x47fd29]

goroutine 1 [running]:
golang.org/x/net/html.inBodyIM(0xc420118410, 0x4caa68)
        /path/to/gopath/src/golang.org/x/net/html/parse.go:988 +0x1d49
golang.org/x/net/html.inTableIM(0xc420118410, 0xc42014a000)
        /path/to/gopath/src/golang.org/x/net/html/parse.go:1433 +0x20e
golang.org/x/net/html.inTableBodyIM(0xc420118410, 0x0)
        /path/to/gopath/src/golang.org/x/net/html/parse.go:1590 +0x145
golang.org/x/net/html.(*parser).parseCurrentToken(0xc420118410)
        /path/to/gopath/src/golang.org/x/net/html/parse.go:2180 +0x84
golang.org/x/net/html.(*parser).parse(0xc420118410, 0xc42014c000, 0xc420118340)
        /path/to/gopath/src/golang.org/x/net/html/parse.go:2206 +0x5b
golang.org/x/net/html.Parse(0x4d5b00, 0xc42000a0e0, 0xc420110150, 0xc4200dff78, 0xc42001a118)
        /path/to/gopath/src/golang.org/x/net/html/parse.go:2232 +0xdb
main.main()
        /path/to/gopath/src/html/main.go:11 +0x73
exit status 2
```

**Comment by odeke-em** [comment] 2018-09-17 02:16
Hello @tr3ee, thank you for reporting this issue and welcome to Go!

I noticed that you already filed https://github.com/golang/go/issues/27702 with a somewhat similar repro but different crash stacktrace. I believe the common issue in both of them is incomplete tags?
If the issue is the same, would you mind closing this one? A consolidated issue is easier to track but also please provide the content of this bug as a reproducer for that issue. If not, please ignore my comments..

In the meantime, I'll page @nigeltao @namusyaka

**Comment by tr3ee** [comment] 2018-09-17 02:44
Hello @odeke-em , thank you for your reply.

It's ok if you close this, and I will re-edit the content of issue #27702 .

**Comment by tr3ee** [comment] 2018-09-19 07:48
Hello @odeke-em ,
After discussing with the CVE Assignment Team members, I think it's best to reopen this issue, because of [CNA rules counting_decisions](http://cve.mitre.org/cve/cna/rules.html#Appendix_C_counting_decisions)

**Comment by namusyaka** [comment] 2018-09-20 20:48
@tr3ee Thank you for your report!

This isn't same with #27702 so I will fix these issues separately.

**Closed** 2018-09-21 00:04 UTC
Labels: NeedsFix
