### ISSUE TITLE
net: Dial DNS lookups fail on Android

### ISSUE THREAD

**Issue by vinhjaxt** [golang/go#41373] opened 2020-09-14 09:56 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/data/go-vendor/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/data/go-vendor/"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/data/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/data/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build116565155=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Compile and run this file:
```go
package main

import (
	"log"
	"net"
)

func main() {
	_, err := net.Dial("tcp", "echo.opera.com:80")
	log.Println(err)
}
```

`GOOS=linux GOARCH=arm64 go build`

### What did you expect to see?
nil

### What did you see instead?
`dial tcp: lookup echo.opera.com on [::1]:53: read udp [::1]:55154->[::1]:53: read: connection refused`

### The root cause:
File `./go/src/net/dnsconfig_unix.go`
Line: 19
```go
var (
	defaultNS   = []string{"127.0.0.1:53", "[::1]:53"}
	getHostname = os.Hostname // variable for testing
)
```

**Comment by toothrot** [comment] 2020-09-15 18:33
This would appear to be related to #10714 and is a duplicate of #8877. Please discuss there.

**Closed by toothrot** 2020-09-15 18:33 UTC
Labels: OS-Android, mobile
