### ISSUE TITLE
strings.Title incorrectly handles word breaks

### ISSUE THREAD

**Issue by dnjaramba** [golang/go#17176] opened 2016-09-21 08:51 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.7

### What operating system and processor architecture are you using (`go env`)?
Windows 10

### What did you do?
Converting a string to it's title equivalent via strings.Title() returns following unexpected result.
https://play.golang.org/p/uS2k-vIJZJ

### What did you expect to see?
Uncle Jim's Supermarket

### What did you see instead?
Uncle Jim'S Supermarket

**Comment by odeke-em** [comment] 2016-09-21 08:54
Duplicate of https://github.com/golang/go/issues/6801.

**Closed** 2016-09-21 14:55 UTC
