### ISSUE TITLE
x/playground: ExampleNoOutput test is flaky

### ISSUE THREAD

**Issue by andybons** [golang/go#24615] opened 2018-03-30 23:41 UTC
When running the playgrounds within the `Dockerfile`, it sometimes fails with

```
Step 60/62 : RUN /app/playground test
 ---> Running in 8fbf8f5df18a
App (project ID: "") is NOT caching results
2018/03/30 23:30:42 unexpected output: "PASS\ntesting: warning: no tests to run\n", want "testing: warning: no tests to run\nPASS"
```

after updating the test code, it will sometimes fail with:

```
Step 60/62 : RUN /app/playground test
 ---> Running in 411206ccfd4d
App (project ID: "") is NOT caching results
2018/03/30 22:51:30 unexpected output: "testing: warning: no tests to run\nPASS\n", want "PASS\ntesting: warning: no tests to run"
```

The output seems non-deterministic, which is odd.

@ysmolsky

**Comment by ysmolsky** [comment] 2018-03-31 07:15
I am unable to reproduce this. How do you run those tests? When I run `make test` using macOS native Docker I have different step numbers:
```
...golang.org/x/playground (master $=) % git a
* 76d1738 - (HEAD -> master, origin/master, origin/HEAD) playground: support examples as tests

... SKIPPED ...
Step 45/48 : WORKDIR /app
Removing intermediate container 7782ffd5187f
 ---> 87a0a8813a76
Step 46/48 : RUN /go/bin/playground test
 ---> Running in 8188688d1019
App (project ID: "") is NOT caching results
OK
Removing intermediate container 8188688d1019
 ---> 226e01540b07
Step 47/48 : EXPOSE 8080
 ---> Running in d7deedd5a872
Removing intermediate container d7deedd5a872
 ---> cebe18a41b3c
Step 48/48 : ENTRYPOINT ["/go/bin/playground"]
 ---> Running in df745592a4fd
Removing intermediate container df745592a4fd
 ---> 91f5b1decaa6
Successfully built 91f5b1decaa6
Successfully tagged playground:latest
go test
PASS
ok  	golang.org/x/playground	0.018s
```

Does it happen for the commit 76d1738?

**Comment by ysmolsky** [comment] 2018-03-31 12:27
That particular test is the only which expect output of two different kinds in Events slice: `[{"testing: warning: no tests to run\n" "stderr" "0s"} {"PASS\n" "stdout" "0s"}]`

Trying to write to stderr and stdout gives inconsistent output when writing both to `stderr` and `stdout` at the same "playground time":
https://play.golang.org/p/8du1N7eAxmq
https://play.golang.org/p/yky_PWrcZvu

This program produces correct order on local playground.

**Comment by ysmolsky** [comment] 2018-03-31 13:00
And then I got to this function: https://github.com/golang/go/blob/master/src/runtime/sys_nacl_amd64p32.s#L63
```
TEXT runtime·write(SB),NOSPLIT,$16-20
	// If using fake time and writing to stdout or stderr,
	// emit playback header before actual data.
```

https://github.com/golang/go/commit/242050d07f1becd35d5990d7728403ea4eece5c3

ping @minux

**Comment by ysmolsky** [comment] 2018-04-02 08:26
Of course we can resort to just fixing the test and closing the issue. Then spawn another issue for fixing stdout/stderr messed up order.

@andybons, what do you think?

**Closed** 2018-04-13 17:29 UTC
Labels: NeedsInvestigation
