### ISSUE TITLE
fmt: inconsistent behaviour of Scanf & Fscanf

### ISSUE THREAD

**Issue by syst3mw0rm** [golang/go#10864] opened 2015-05-15 04:46 UTC
Following program using Fscanf panics,

http://play.golang.org/p/0vdaUh2hJp
```
panic: unexpected newline

goroutine 1 [running]:
main.main()
	/tmp/sandbox/1.go:19 +0x3af
exit status 2
```
Another similar program using Scanf seems to work fine,

http://play.golang.org/p/rrBjFXuC0a

```
$ go run 2.go < input

$ hexdump input
0000000 31 0a 32 0a                                    
0000004
```

on commit https://github.com/golang/go/commit/335e44d265e7b7741b00237f4fcd97a1b80bfd9a

Am I doing something terribly wrong or there is a legit bug? I've also file one relevant bug - https://github.com/golang/go/issues/10853

**Comment by robpike** [comment] 2015-06-05 18:08
Duplicate of #9459

**Closed by robpike** 2015-06-05 18:08 UTC
