### ISSUE TITLE
x/pkgsite: Business Source License

### ISSUE THREAD

**Issue by itsdevbear** [golang/go#58924] opened 2023-03-08 03:27 UTC
### What is the URL of the page with the issue?
 
[ https://](https://pkg.go.dev/pkg.berachain.dev/polaris/eth)
 
 
### What is your user agent?
 
[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
### Screenshot

 
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/93690142/223612137-5dd89619-c461-4307-a309-050f22c59bb9.png">

 
 
### What did you expect to see?
 
 README and other package info
 
### What did you see instead?

LICENSE restriction.

**Comment by hyangah** [comment] 2023-03-09 17:14
MariaDB Business Source License is not in the list of licenses pkgsite can recognize.

https://pkg.go.dev/license-policy

If you use a package whose license is not detected, please inform the package author. If you are a package author who believes a license for one of your packages should have been detected and was not, please check for discrepancies between your license and the official text.

--

I am not a lawyer so this is not a legal advice.
A heuristic that can be used before proposing to expand the license list is to check https://opensource.org/licenses.

**Comment by itsdevbear** [comment] 2023-03-09 18:03
@hyangah I am the author, looking to get it added.

**Comment by seankhliao** [comment] 2023-03-23 09:05
Closing as a dupe of #59183 which contains more information

**Closed by seankhliao** 2023-03-23 09:05 UTC
Labels: pkgsite, pkgsite/license
