### ISSUE TITLE
database/sql: "rollback due to context cancellation" error consistency

### ISSUE THREAD

**Issue by nvartolomei** [golang/go#28077] opened 2018-10-08 15:27 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.11.1

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

https://play.golang.org/p/Yom8SR66l08

### What did you expect to see?
panic: context canceled

### What did you see instead?
panic: sql: transaction has already been committed or rolled back

There is a "race condition" when context is cancelled and `database/sql` context watcher rollbacks the transaction before the programmer has a chance to do it. If you remove `runtime.Gosched()` call from playground code on line 20, you'll get expected context canceled error.

https://github.com/golang/go/blob/7c3b324d265905eec137d92e3a0a9041cad3679d/src/database/sql/sql.go#L1672

The problem is a usability one, when you see the `sql: transaction has already been committed or rolled back` error it is hard to track down wether it was because the tx was rolled back due to cancellation or there is a bug in the application calling commit/rollback multiple times.

**Comment by kardianos** [comment] 2018-10-09 06:06
I think this is a duplicate issue. But either way I will look at it.

**Comment by kardianos** [comment] 2018-10-27 19:29
This is a duplicate of #25829 .

**Closed by kardianos** 2018-10-27 19:29 UTC
Labels: NeedsInvestigation
