### ISSUE TITLE
runtime: floating point number conversion to int different on silicon

### ISSUE THREAD

**Issue by asdine** [golang/go#47387] opened 2021-07-25 18:45 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.6 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/asdine/Library/Caches/go-build"
GOENV="/Users/asdine/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/asdine/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/asdine/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.16.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.16.6/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/asdine/code/github.com/genjidb/genji/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z3/f6p4jtl563s0z7gth5c_ydlc0000gn/T/go-build1754120130=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Calling `math.Abs(math.MinInt64)` then converting to an int64 doesn't overflow on mac silicon.

```go
package main

import (
	"fmt"
	"math"
)

func main() {
	a := int64(math.MinInt64)

	b := math.Abs(math.MinInt64)

	c := math.Float64bits(b)

	d := int64(b)

	fmt.Println(a, b, c, d)
	// on x86 cpus:
	// -9223372036854775808 9.223372036854776e+18 4890909195324358656 -9223372036854775808

	// on silicon:
	// -9223372036854775808 9.223372036854776e+18 4890909195324358656 9223372036854775807
}
```
https://play.golang.org/p/xAYEJonoDAW
 
I'm not sure if this is a bug or something specific to the Silicon architecture.

### What did you expect to see?

I was expecting the int64 to overflow and be negative. This is important to detect overflows and return a proper error when that happens.

### What did you see instead?

The number doesn't overflow and stays positive

**Comment by randall77** [comment] 2021-07-25 18:54
From the Go spec:

> In all non-constant conversions involving floating-point or complex values, if the result type cannot represent the value the conversion succeeds but the result value is implementation-dependent.

That's the case here. You're converting `1<<63` to `int64` and it doesn't quite fit.

**Comment by ianlancetaylor** [comment] 2021-07-25 23:35
Closing, as this is not a bug.

To detect a representation failure when converting from `float64` to `in64`, convert to `int64` and then back again, and see if you get the same number.

**Closed by ianlancetaylor** 2021-07-25 23:35 UTC
