### ISSUE TITLE
x/pkgsite: searching for 'packages' doesn't find 'go/packages'

### ISSUE THREAD

**Issue by pjweinb** [golang/go#42129] opened 2020-10-21 21:25 UTC
pkg.go.dev 
 
searching for 'packages' gives  a lot of well-known packages, but 'go/packages' would seem more relevant.

**Comment by cespare** [comment] 2020-10-21 22:08
For me, it does appear, but as search result 79:

![packages](https://user-images.githubusercontent.com/318501/96792253-e01a7680-13ae-11eb-916b-d44c0cc4b6aa.png)

(Nobody clicks to page 8, though, so this is effectively the same as not showing up at all.)

Just observing the results it looks like it's fuzzy-matching "packages" to "package" and then matching ~every package that exists due to the word "package" appearing in the package description:

> Package log implements a simple logging package.

> Package fmt implements formatted I/O with functions analogous to C's printf and scanf.

Ideally the fact that the exact search string "packages" matches the package name exactly as well as the last segment of the import path would cause the `go/packages` result to rank much more highly; ideally as the first result.

**Comment by seankhliao** [comment] 2024-12-03 23:26
seems to be worse now, we get a random selection of standard library packages.

**Comment by seankhliao** [comment] 2024-12-29 00:57
Duplicate of #41369

**Closed by seankhliao** 2024-12-29 00:57 UTC
Labels: NeedsInvestigation, pkgsite, pkgsite/search
