### ISSUE TITLE
x/mobile/font: TestLoadFonts fail on darwin

### ISSUE THREAD

**Issue by rakyll** [golang/go#10644] opened 2015-04-30 17:31 UTC
```
--- FAIL: TestLoadFonts (0.01s)
	font_test.go:17: default font: freetype: unsupported TrueType feature: cmap encoding
FAIL
FAIL	golang.org/x/mobile/font	0.065s

```

cc/ @crawshaw @hyangah

**Comment by hyangah** [comment] 2016-07-07 16:38
duplicate of #10136

**Closed by hyangah** 2016-07-07 16:38 UTC
