### ISSUE TITLE
x/tools/cmd/getgo: cannot install Go 1.21

### ISSUE THREAD

**Issue by andrewpollock** [golang/go#63367] opened 2023-10-04 05:39 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.22-20230729-RC00 cl/552016856 +457721cd52 X:fieldtrack,boringcrypto linux/amd64
</pre>

### Does this issue reproduce with the latest release?

I'll go with "yes"

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/usr/local/google/home/apollock/.cache/go-build'
GOENV='/usr/local/google/home/apollock/.config/go/env'
GOEXE=''
GOEXPERIMENT='fieldtrack,boringcrypto'
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/usr/local/google/home/apollock/go/pkg/mod'
GONOPROXY='*.googlesource.com,*.git.corp.google.com'
GONOSUMDB='*.googlesource.com,*.git.corp.google.com'
GOOS='linux'
GOPATH='/usr/local/google/home/apollock/go'
GOPRIVATE='*.googlesource.com,*.git.corp.google.com'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/google-golang'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/google-golang/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22-20230729-RC00 cl/552016856 +457721cd52 X:fieldtrack,boringcrypto'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1830009407=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

Ran https://github.com/google/osv.dev/blob/master/docker/ci/build.sh thusly:

```
./build.sh 20231004
```

### What did you expect to see?

A successful Docker image build

### What did you see instead?

```
+ chmod +x /tmp/installer_linux
+ SHELL=bash
+ /tmp/installer_linux -version 1.21
Welcome to the Go installer!
Downloading Go version go1.21 to /root/.go
This may take a bit of time...
Downloading Go from 404 Not Found failed with HTTP status %!s(MISSING)
The command '/bin/sh -c "/tmp/install_go.sh" "/tmp"' returned a non-zero code: 2
```

Further analysis:

```
$ gsutil ls gs://golang/go1.20.linux*
gs://golang/go1.20.linux-386.tar.gz
gs://golang/go1.20.linux-386.tar.gz.asc
gs://golang/go1.20.linux-386.tar.gz.sha256
gs://golang/go1.20.linux-amd64.tar.gz
gs://golang/go1.20.linux-amd64.tar.gz.asc
gs://golang/go1.20.linux-amd64.tar.gz.sha256
gs://golang/go1.20.linux-arm64.tar.gz
gs://golang/go1.20.linux-arm64.tar.gz.asc
gs://golang/go1.20.linux-arm64.tar.gz.sha256
gs://golang/go1.20.linux-armv6l.tar.gz
gs://golang/go1.20.linux-armv6l.tar.gz.asc
gs://golang/go1.20.linux-armv6l.tar.gz.sha256
gs://golang/go1.20.linux-ppc64le.tar.gz
gs://golang/go1.20.linux-ppc64le.tar.gz.asc
gs://golang/go1.20.linux-ppc64le.tar.gz.sha256
gs://golang/go1.20.linux-s390x.tar.gz
gs://golang/go1.20.linux-s390x.tar.gz.asc
gs://golang/go1.20.linux-s390x.tar.gz.sha256
$ gsutil ls gs://golang/go1.21.linux*
CommandException: One or more URLs matched no objects.
```

**Comment by andrewpollock** [comment] 2023-10-04 05:39
@another-rex discovered that 1.21.1 _is_ installable.

**Comment by go101** [comment] 2023-10-04 06:39
Since Go 1.21, There is not go1.21, only g01.21.0.

**Comment by andrewpollock** [comment] 2023-10-04 07:15
@go101 All I can say is installing go1.21.1 worked... and:

```
$ gsutil ls gs://golang/go1.21.1.linux*
gs://golang/go1.21.1.linux-386.tar.gz
gs://golang/go1.21.1.linux-386.tar.gz.asc
gs://golang/go1.21.1.linux-386.tar.gz.sha256
gs://golang/go1.21.1.linux-amd64.tar.gz
gs://golang/go1.21.1.linux-amd64.tar.gz.asc
gs://golang/go1.21.1.linux-amd64.tar.gz.sha256
gs://golang/go1.21.1.linux-arm64.tar.gz
gs://golang/go1.21.1.linux-arm64.tar.gz.asc
gs://golang/go1.21.1.linux-arm64.tar.gz.sha256
gs://golang/go1.21.1.linux-armv6l.tar.gz
gs://golang/go1.21.1.linux-armv6l.tar.gz.asc
gs://golang/go1.21.1.linux-armv6l.tar.gz.sha256
gs://golang/go1.21.1.linux-loong64.tar.gz
gs://golang/go1.21.1.linux-loong64.tar.gz.asc
gs://golang/go1.21.1.linux-loong64.tar.gz.sha256
gs://golang/go1.21.1.linux-mips.tar.gz
gs://golang/go1.21.1.linux-mips.tar.gz.asc
gs://golang/go1.21.1.linux-mips.tar.gz.sha256
gs://golang/go1.21.1.linux-mips64.tar.gz
gs://golang/go1.21.1.linux-mips64.tar.gz.asc
gs://golang/go1.21.1.linux-mips64.tar.gz.sha256
gs://golang/go1.21.1.linux-mips64le.tar.gz
gs://golang/go1.21.1.linux-mips64le.tar.gz.asc
gs://golang/go1.21.1.linux-mips64le.tar.gz.sha256
gs://golang/go1.21.1.linux-mipsle.tar.gz
gs://golang/go1.21.1.linux-mipsle.tar.gz.asc
gs://golang/go1.21.1.linux-mipsle.tar.gz.sha256
gs://golang/go1.21.1.linux-ppc64.tar.gz
gs://golang/go1.21.1.linux-ppc64.tar.gz.asc
gs://golang/go1.21.1.linux-ppc64.tar.gz.sha256
gs://golang/go1.21.1.linux-ppc64le.tar.gz
gs://golang/go1.21.1.linux-ppc64le.tar.gz.asc
gs://golang/go1.21.1.linux-ppc64le.tar.gz.sha256
gs://golang/go1.21.1.linux-riscv64.tar.gz
gs://golang/go1.21.1.linux-riscv64.tar.gz.asc
gs://golang/go1.21.1.linux-riscv64.tar.gz.sha256
gs://golang/go1.21.1.linux-s390x.tar.gz
gs://golang/go1.21.1.linux-s390x.tar.gz.asc
gs://golang/go1.21.1.linux-s390x.tar.gz.sha256
```

**Comment by seankhliao** [comment] 2023-10-04 12:41
Duplicate of #62112

**Closed by seankhliao** 2023-10-04 12:41 UTC
Labels: Tools

**Comment by go101** [comment] 2023-10-04 15:03
@andrewpollock go1.21.1 certainly works, because that release exists.

@seankhliao this should be different from https://github.com/golang/go/issues/62112
