### ISSUE TITLE
x/vgo: 'vgo vendor' should ignore custom build errors

### ISSUE THREAD

**Issue by marvell** [golang/go#25870] opened 2018-06-13 16:00 UTC
### What version of Go are you using (`go version`)?
`go version go1.10.3 linux/amd64 vgo:2018-02-20.1`

### Does this issue reproduce with the latest release?
Yep.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build906088807=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
`github.com/davecgh/go-spew` added into go.mod file and tried `vgo vendor`.

main.go
```go
package main

import (
	"github.com/davecgh/go-spew/spew"
)

func main() {
	var a = 42
	spew.Dump(a)
}
```

go.mod
```
module main_question

require github.com/davecgh/go-spew v1.1.0
```

### What did you expect to see?
`./vendor` directory with all dependency is created without any errors.

### What did you see instead?
```
vgo: resolving import "github.com/davecgh/go-spew"
vgo: finding github.com/davecgh/go-spew (latest)
vgo: adding github.com/davecgh/go-spew v1.1.0
vgo: finding github.com/davecgh/go-spew v1.1.0
vgo: downloading github.com/davecgh/go-spew v1.1.0
vgo: import "oauth" ->
	import "github.com/davecgh/go-spew" [/go/src/v/github.com/davecgh/go-spew@v1.1.0]: no Go source files
vgo: import "github.com/davecgh/go-spew" [/go/src/v/github.com/davecgh/go-spew@v1.1.0]: no Go source files
```

**Comment by oiooj** [comment] 2018-06-13 16:48
I think your module root is `github.com/davecgh/go-spew/spew`

**Comment by marvell** [comment] 2018-06-13 16:55
Yep, you're right. Anyway the problem is still there.

```
# ls -la
total 12
drwxr-xr-x 4 root root  128 Jun 13 16:54 .
drwxrwxrwx 1 root root 4096 Jun 13 16:54 ..
-rw-r--r-- 1 root root   64 Jun 13 16:53 go.mod
-rw-r--r-- 1 root root  103 Jun 13 16:52 main.go

# vgo build
vgo: finding github.com/davecgh/go-spew v1.1.0
vgo: downloading github.com/davecgh/go-spew v1.1.0

# ls -la
total 2388
drwxr-xr-x 5 root root     160 Jun 13 16:54 .
drwxrwxrwx 1 root root    4096 Jun 13 16:54 ..
-rw-r--r-- 1 root root      64 Jun 13 16:53 go.mod
-rw-r--r-- 1 root root     103 Jun 13 16:52 main.go
-rwxr-xr-x 1 root root 2430716 Jun 13 16:54 main_question

# vgo vendor
vgo: import "github.com/davecgh/go-spew/spew/testdata" [/go/src/v/github.com/davecgh/go-spew@v1.1.0/spew/testdata]: no Go source files

# ls -la
total 2388
drwxr-xr-x 5 root root     160 Jun 13 16:54 .
drwxrwxrwx 1 root root    4096 Jun 13 16:54 ..
-rw-r--r-- 1 root root      64 Jun 13 16:53 go.mod
-rw-r--r-- 1 root root     103 Jun 13 16:52 main.go
-rwxr-xr-x 1 root root 2430716 Jun 13 16:54 main_question
```

**Comment by oiooj** [comment] 2018-06-13 17:07
@marvell Thanks, duplicate of #25871

**Closed by oiooj** 2018-06-13 17:07 UTC
Labels: NeedsInvestigation
