### ISSUE TITLE
spec: switch expressions behave differently for non-comparable type parameters and other non-comparable types

### ISSUE THREAD

**Issue by flimzy** [golang/go#67285] opened 2024-05-10 13:52 UTC
### Go version

1.22.0

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/jonhall/.cache/go-build'
GOENV='/home/jonhall/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/jonhall/go/pkg/mod'
GONOPROXY='gitlab.com/FlashbackSRS/priv,gitlab.com/flimzy/hacker-portfolio'
GONOSUMDB='gitlab.com/FlashbackSRS/priv,gitlab.com/flimzy/hacker-portfolio'
GOOS='linux'
GOPATH='/home/jonhall/go'
GOPRIVATE='gitlab.com/FlashbackSRS/priv,gitlab.com/flimzy/hacker-portfolio'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='/usr/bin/gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/jonhall/src/test/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build4212822218=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I ran this program with `go run .`

```golang
package main

import "fmt"

func main() {
	var x [3]int
	switch x {
	default:
		fmt.Println("default")
	}
}
```

### What did you see happen?

It compiled, and output the following text:

```
default
```

### What did you expect to see?

I expected a compilation error.

The spec [states that](https://go.dev/ref/spec#Expression_switches):

> The switch expression type must be [comparable](https://go.dev/ref/spec#Comparison_operators).

Further it [explains](https://go.dev/ref/spec#Comparison_operators):

> Slice, map, and function types are not comparable. However, as a special case, a slice, map, or function value may be compared to the predeclared identifier `.

Based on this, I would expect a switch expression on an array (for example) to not compile. Note that this following code indeed does not compile, which matches expectations.

```golang
func foo[T any](t T) {
	switch t {
	default:
		fmt.Println("default")
	}
}
````

But as the spec doesn't mention any difference between the "non-comparability" of type parameters, and other non-comparable types, I expected them to behave the same.

**Comment by ALTree** [comment] 2024-05-10 14:01
`[3]int` is an array type, not a slice, and array types *are* comparable. I think this is working as intended, so I'm closing, but feel free to comment if I've misunderstood the issue.

**Closed by ALTree** 2024-05-10 14:01 UTC
