### ISSUE TITLE
net: TestInterfaces fails on FreeBSD 11-CURRENT

### ISSUE THREAD

**Issue by swills** [golang/go#11641] opened 2015-07-09 17:20 UTC
Full error is:

--- FAIL: TestInterfaces (0.00s)
        interface_test.go:74: route ip+net: invalid network interface name

**Comment by mikioh** [comment] 2015-07-09 19:01
Please take a look at  https://github.com/golang/go/blob/master/CONTRIBUTING.md.
Merged into #7849.

**Comment by swills** [comment] 2015-07-09 22:42
What version of Go are you using (go version)?

go version go1.5beta1 freebsd/amd64

What operating system and processor architecture are you using?

FreeBSD amd64

What did you do?

tar -xzvf go1.5beta1.src.tar.gz
cd go/src
env CC=cc GOROOT_BOOTSTRAP=/usr/local/go bash all.bash

What did you expect to see?

Test pass

What did you see instead?

--- FAIL: TestInterfaces (0.00s)
        interface_test.go:74: route ip+net: invalid network interface name
FAIL
FAIL    net     13.270s

**Comment by mikioh** [comment] 2015-07-10 11:08
Thanks. Please let us know your kernel version in next time. The root cause is simply go's routing message parsers still use NET_RT_IFLIST+if_msghdr instead of NET_RT_IFLISTL+if_msghdrl, and seems like the under-development kernel doesn't return correct RTM_IFINFO messages like the following:
```
# cd $GOROOT/src/syscall
# go test -v -run=Route
	route_bsd_test.go:70: 3 0 ifp [6/unspec/4614 t/n/a/s=2/0/152/0]
	route_bsd_test.go:70: 3 0 ifp [6/unspec/4614 t/n/a/s=2/0/152/0]
	route_bsd_test.go:70: 3 0 ifp [24/unspec/0 t/n/a/s=0/0/152/0]
	route_bsd_test.go:70: 3 2 ifp [6/unspec/4614 t/n/a/s=2/0/152/0]
```

**Comment by swills** [comment] 2015-07-10 11:11
Ah, I see. Kernel versions is `FreeBSD 11.0-CURRENT #0 r284988: Wed Jul  1 03:59:20 UTC 2015` I'll see if I can produce a patch.

**Comment by mikioh** [comment] 2015-07-10 11:18
I'm not sure whether FreeBSD net subsystem guys want to drop NET_RT_IFLIST in 11-CURRENT. If so, go's routing message parser will use NET_RT_IFLISTL eventually. According to https://www.freebsd.org/releng/index.html, July 2016 is the current scheduled date. So it may happen in go1.7.

**Comment by l-d-x** [comment] 2015-08-20 00:28
For go1.5 The problem is types_freebsd.go `strucht if_data8` and its output ztypes_freebsd_amd64.go `ifData` do not have matching fields to FreeBSD 11, specifically the position of `ifi_datalen` which is now `uint16_t`. In short, types_freebsd.go needs to be fixed up to support FreeBSD-11.

Earlier versions of `go` uses SizeofIfMsghdr (fixed size):
```go
func (any *anyMessage) parseInterfaceMessage(b []byte) *InterfaceMessage {
	p := (*InterfaceMessage)(unsafe.Pointer(any))
	return &InterfaceMessage{Header: p.Header, Data: b[SizeofIfMsghdr:any.Msglen]}
}
```

where as 1.5 does (referencing p.Header.Data.Datalen)
:
```go
	return &InterfaceMessage{Header: p.Header,
            Data: b[int(unsafe.Offsetof(p.Header.Data))+int(p.Header.Data.Datalen) : any.Msglen]}
```

types_freebsd.go:
```go
// this needs:
#undef ifi_epoch
// and
#undef ifi_lastchange to work also.

struct if_data8 {
        u_char  ifi_type;
        u_char  ifi_physical;
        u_char  ifi_addrlen;
        u_char  ifi_hdrlen;
        u_char  ifi_link_state;
        u_char  ifi_spare_char1;
        u_char  ifi_spare_char2;
        u_char  ifi_datalen;
        u_long  ifi_mtu;
        u_long  ifi_metric;
        u_long  ifi_baudrate;
        u_long  ifi_ipackets;
        u_long  ifi_ierrors;
        u_long  ifi_opackets;
        u_long  ifi_oerrors;
        u_long  ifi_collisions;
        u_long  ifi_ibytes;
        u_long  ifi_obytes;
        u_long  ifi_imcasts;
        u_long  ifi_omcasts;
        u_long  ifi_iqdrops;
        u_long  ifi_noproto;
        u_long  ifi_hwassist;
        time_t  ifi_epoch;
        struct  timeval ifi_lastchange;
};
```

FreeBSD if.h:
```c
struct if_data {
	/* generic interface information */
	uint8_t	ifi_type;		/* ethernet, tokenring, etc */
	uint8_t	ifi_physical;		/* e.g., AUI, Thinnet, 10base-T, etc */
	uint8_t	ifi_addrlen;		/* media address length */
	uint8_t	ifi_hdrlen;		/* media header length */
	uint8_t	ifi_link_state;		/* current link state */
	uint8_t	ifi_vhid;		/* carp vhid */
	uint16_t	ifi_datalen;	/* length of this data struct */
	uint32_t	ifi_mtu;	/* maximum transmission unit */
	uint32_t	ifi_metric;	/* routing metric (external only) */
	uint64_t	ifi_baudrate;	/* linespeed */
	/* volatile statistics */
	uint64_t	ifi_ipackets;	/* packets received on interface */
	uint64_t	ifi_ierrors;	/* input errors on interface */
	uint64_t	ifi_opackets;	/* packets sent on interface */
	uint64_t	ifi_oerrors;	/* output errors on interface */
	uint64_t	ifi_collisions;	/* collisions on csma interfaces */
	uint64_t	ifi_ibytes;	/* total number of octets received */
	uint64_t	ifi_obytes;	/* total number of octets sent */
	uint64_t	ifi_imcasts;	/* packets received via multicast */
	uint64_t	ifi_omcasts;	/* packets sent via multicast */
	uint64_t	ifi_iqdrops;	/* dropped on input */
	uint64_t	ifi_oqdrops;	/* dropped on output */
	uint64_t	ifi_noproto;	/* destined for unsupported protocol */
	uint64_t	ifi_hwassist;	/* HW offload capabilities, see IFCAP */

	/* Unions are here to make sizes MI. */
	union {				/* uptime at attach or stat reset */
		time_t		tt;
		uint64_t	ph;
	} __ifi_epoch;
#define	ifi_epoch	__ifi_epoch.tt
	union {				/* time of last administrative change */
		struct timeval	tv;
		struct {
			uint64_t ph1;
			uint64_t ph2;
		} ph;
	} __ifi_lastchange;
#define	ifi_lastchange	__ifi_lastchange.tv
};
```

**Comment by bradfitz** [comment] 2015-12-05 07:45
This was reverted for breaking the build.

**Comment by mikioh** [comment] 2015-12-05 07:58
This is a duplicate of #7849. Also release-11 branch is not created yet. No need to rush adapting heavily under development kernels because freebee net guys still have a chance to modify abis.

**Closed by mikioh** 2015-12-05 07:58 UTC
Labels: OS-FreeBSD
