### ISSUE TITLE
cmd/godoc: Nested functions on embedded types are only shown 1 level deep.

### ISSUE THREAD

**Issue by klauspost** [golang/go#9762] opened 2015-02-03 20:09 UTC
Test case: http://play.golang.org/p/9oz7e7AKzd

In the example above A embeds b which embeds c. There are public functions on b, which is shown correctly in godoc as belonging to A.  However, it seems like godoc only searches 1 level deep, and functions on c are not shown even though they are valid for calls by the compiler.

Reproducible on 1.4.1 and 1.3.3.

Real life example: [source](https://github.com/klauspost/dawa/blob/master/query.go) / [godoc](https://godoc.org/github.com/klauspost/dawa#PostnrQuery). A specific query type includes "geoJSONQuery" which includes "query", and I would like to have the functions on "query" to show up. I would however prefer not to expose any of the internal types since they aren't useful themselves.

**Comment by griesemer** [comment] 2015-02-05 04:20
Closed as duplicate of #6127.

The problem is that godoc is using a heuristic and doesn't do much searching in the first place.

Doing this correctly in all cases with go/types integration is a significant chunk of work and thus an open issue.

**Closed by griesemer** 2015-02-05 04:20 UTC
