### ISSUE TITLE
x/tools/gopls: add support for multiple concurrent clients

### ISSUE THREAD

**Issue by leitzler** [golang/go#34111] opened 2019-09-05 13:36 UTC
As per discussion on Slack with @ianthehat & @myitcv this is a feature request for gopls to support multiple concurrent clients.

Vim users often have multiple instances of vim running at the same time, and starting/exiting is a natural part of the workflow. Currently there is a 1 to 1 mapping between vim and gopls (at least when using govim as plugin). It would be really useful to be able to share the same cache and avoid waiting for warmup each time.

See https://github.com/myitcv/govim/issues/491 as well as https://github.com/golang/go/issues/32750#issuecomment-528314462 for details.

**Comment by leitzler** [comment] 2019-09-05 13:37
@gopherbot, please add label FeatureRequest

**Comment by ianthehat** [comment] 2019-09-05 15:24
In its default state gopls supports a specific header based JSON stream of the LSP on stdin /stdout. In this mode it only supports a single client as stdin/stdout cannot be multiplexed.

It also has the flags `-listen` and `-remote`, which are designed to allow it to communicate using sockets. `-listen` only applies to the `serve` verb, and causes it to listen for incoming connections rather than stdin/stdout. In this mode it supports multiple clients. The `-remote` flag can be supplied to any verb, and tells it how to talk to a gopls that was started with `serve -listen`. If you use it with `serve` then you have a gopls that listens on stdin/stdout and forwards commands to the remote gopls. The intent is that you use this mode from within an editor to talk to a gopls server.

The protocol spoken between a -remote and -listen gopls is not defined, and never will be, we only support it as a way of intercommunication, not as an API surface. This is because to achieve some of its goals it will have to have significant extensions to the protocol, and may mutate some of the data on the way through. Part of the reason for this is that it should be feasible to have the server run on a separate machine, and it may not have access to the same file system, or it may know the files by different absolute paths etc. These features require a reliable way of translating paths, and also the remote file extension so the true server can ask the intermediary gopls for file contents. It may also be necessary to have some forms of caching and cancelling within the intermediary.

The current state is that we use this mode only for debugging. It only gets fixed when we need to use it to debug a problem, and even then it does not get properly fixed. It does mostly work, but there are things like straight proxying of shutdown message causes the shared server to quit when any of clients does.

There are also design issues still to fix, things like should we support some kind of "discovery" protocol, should we have a mode where we start a server if one is not running but connect to it if it is, when all the clients go away should the server shut down again, how do we manage the cache so we dont explode because of lots of clients over a very long time, how do we prevent one client from starving the others, how do we manage the config and environment of the server correctly etc

**Comment by myitcv** [comment] 2019-09-05 15:37
Thanks for this detail.

> The current state is that we use this mode only for debugging

Understood. 

For editors like Vim, Emacs, etc, where users end up starting multiple instances on the same machine having a single instance of `gopls` will be a big win when it avoiding waiting for (pre-)warming of the imports cache (https://github.com/golang/go/issues/34115). 

Given that, do you have plans to fully support this mode?

**Comment by ianthehat** [comment] 2019-09-05 16:39
Yes, but I have no time to do anything about it right now.
It is also valuable for people that want to run gopls from the command line if it could reuse the cached results already sitting behind their editor, or from a previous command.
Doing this well you really want to have a discovery protocol though, having to specify -remote on every command would be painful.
Ideally I would like to delete the -remote flag in the future and only support a discovery protocol!

**Comment by myitcv** [comment] 2019-09-09 15:16
> Yes, but I have no time to do anything about it right now.

Ok, understood. My question was more geared towards ensuring this is something that is being considered as opposed to not.

**Comment by ianthehat** [comment] 2019-09-09 15:33
I am just being really careful to make sure people do not think I will get round to it any time soon, I don't want someone waiting on it and getting frustrated that I am not doing it!

This is also an area where contributions would be welcome, although it would be a very high touch contribution as I have a lot to say about how it is done :)

**Comment by myitcv** [comment] 2019-09-27 09:44
Just to add another motivating factor behind this change: having a single instance will amortise the additional cost of running `staticcheck` on large code bases each time `gopls` is opened.

**Comment by findleyr** [comment] 2020-01-09 15:06
Just to update, since this was discussed in slack: I'm working on this now, and should have some progress soon.

**Comment by myitcv** [comment] 2020-01-16 13:15
@findleyr is this a `v1.0.0` target of `v0.3.0`? Not chasing... just noting that it being worked on now probably contradicts the current "unplanned" milestone 😄

**Comment by findleyr** [comment] 2020-01-16 14:32
Oh, thanks. Yes, I think this can be added to the v1.0.0 milestone (the v0.3.0 feature set is pretty locked-down at the moment).  I'll confirm with @stamblerre.

**Comment by findleyr** [comment] 2020-01-24 15:07
Update: I've got a number of things working locally, but some of them required significant refactoring that needs to be evaluated before merging. I thought it would be helpful to comment here describing what I'm working on, in case anyone has opinions, questions, or advice.

## Goals

Here's what I’ve identified as the primary goals for the shared gopls implementation:

1. **Ease of use**: from the perspective of an LSP client, using a shared gopls instance should appear identical to using a singleton gopls instance.
2. **Debuggability**: each client session should be isolated in logs and metrics.
3. **Testability**: gopls tests should cover both in-process and remote instances of gopls.

### Ease of use

To connect to a shared gopls instance, we'll use the existing `-remote` flag as specified below. This will cause the gopls process invoked by the editor plugin to operate as a thin client for a separate gopls server process, forwarding LSP messages and recording metrics and logs.

* `-remote="<addr>:<port>"`: connect to a specific shared gopls at that address. If it’s not running, fail.
* `-remote=auto`: connect to the default shared gopls. If it's not running, start it and then connect.
* `-remote=auto:<port>`: connect to a shared gopls instance at `localhost:<port>`, or start it and then connect.
* `-remote=auto:<id>`: discover a shared gopls instance identified by a non-numeric string `<id>`, or start it and then connect

This will allow the following usage patterns:

* Manual management of a shared gopls instance.
* Automatic management of a shared gopls instance.
* Automatic management of a set of shared gopls instances identified by specific ports or IDs. This is a minor extension of the previous use cases, and will allow for scenarios where developers are using different process/mount namespaces in their workflow (thanks @myitcv for the suggestion!)

I'm not married the the `-remote=auto` syntax, but I think the semantics are correct: using a shared instance should be no harder than using a singleton instance.

For future discussion, I'll refer to the thin client gopls process (the one started with the `-remote` flag) as the *forwarder* gopls, and the server gopls process (the one started with the `-listen` flag), as the *shared* gopls. This is to avoid confusion around the words ‘client’ and ‘server’, which now become relative terms.

#### The Server Shutdown Problem

One major problem with starting a shared gopls process automatically is server shutdown: the shared gopls will be a child process of whichever forwarder gopls process started it, and will die when that forwarder process exits. For certain workflows this might be a big problem, for example users who use only short-lived vim processes. I can think of four potential solutions for this:

1. Simply crash all forwarder gopls when the shared gopls exits. This will force the editor plugin to restart the language server, but most editor plugins already do this. This is crude but is the easiest solution to implement.
2. Daemonize the shared gopls process, and have it shut down when there are no more forwarder gopls connected. There are various libraries that could potentially help with this ([example](https://github.com/takama/daemon)), but it is shaping up to be a tricky solution. Not all editors will have the necessary privileges to daemonize a process.
3. Track session information in the forwarder gopls (essentially editor buffer state), and when the shared gopls exits, have the remaining forwarder gopls’ start another one and initializes its session state.
4. The nonsolution: don't allow `--remote=auto` and just force users to start the daemon themselves.

Of these, I don't think (1) or (4) are reasonable solutions in isolation. We can't expect every user to manage their own gopls daemon, and we can't expect every LSP plugin to gracefully handle the LSP server process crashing. Notably VS Code gives up if the language server crashes five times, so if a shared gopls instance is to be used by VS Code, we shouldn’t be intentionally crashing the forwarder.

(1) and (3) both result in the loss of the gopls cache, so after a restart users would have to again pay the initial price of warming the cache. On large projects this can be painful, and since users won't be aware of which forwarder owned the shared gopls, it will be confusing when this happens.  However, I will note that so far while working in x/tools with a shared gopls instance, I hardly notice when it restarts.

(2) would be the ideal solution as it results in the least amount of lost state, but I think it simply won't be possible in many executing environments. I could be wrong though: I need to do more research on daemonization.

My current plan is to start by supporting (1) and (4) so that we can all begin experimenting with using a shared gopls instance, and then work on (2) or (3) (or both, or <*a better idea*>) toward the end of this project.

### Debuggability

I'm lifting the LSP forwarding to the jsonrpc2 layer. What is currently TCP forwarding will instead be two jsonrpc2 connections talking to each other.  This is done both so that we can instrument the forwarder gopls the same way we instrument the shared gopls, and so that we can insert a handshake across the jsonrpc2 stream connecting the forwarder to shared gopls, before starting to forward the LSP. In doing so, we allow the forwarder and shared gopls to exchange information that can be used in debugging. For example, the forwarder gopls can know the location of shared logs or the shared gopls debug port.

Doing this will require some refactoring of the jsonrpc2 API.

### Testability

I'm going to do a bit of refactoring of `internal/lsp/tests` to make it easier to run tests against a remote gopls instance. Once this is done, we should be able to run both the lsp tests *and* cmd tests against a remote (CLI commands will also support `-remote=auto`).

**Comment by findleyr** [comment] 2020-01-24 15:37
@leitzler pointed out on slack: it would be good to also support unix domain sockets as an IPC mechanism between forwarder and shared gopls instance (thanks for the suggestion!).  I agree, but I think we will always need to support TCP as well. One use case that has been discussed is running gopls in docker, in which case exposing a TCP listener is simplest.

For now, I'm going to focus on TCP.  I can add support for unix domain sockets later, or perhaps it would be a good opportunity for others to contribute.

**Comment by myitcv** [comment] 2020-01-26 02:16
@findleyr thanks for awesome write up.

#### Regarding "loss of the gopls cache"

In addition to the cost of re-warming the diagnostics/analysis cache, another pain point is the re-warming of the unimported cache. This can be particularly costly is you have a large module cache. 

#### Regarding option 2

> Daemonize the shared gopls process, and have it shut down when there are no more forwarder gopls connected.

Do we really want to shut it down when there are no more forwarded gopls connected? Because if I open Vim, do some work then quit, the shared gopls will be shutdown. Meaning if I re-open Vim it will need to start from cold again. Which I think defeats the point of what we're trying to solve here, unless I misunderstood? I'd say keep the shared gopls instance running forever and provide a means via a forwarder (a flag, like `-stop` used in conjunction with `-remote`) to stop the shared gopls instance.

#### The option space

Per our Slack chat I completely agree it's worth getting something landed so we can start playing/experimenting. I'm minded to think that option 2 is really the only solution in the medium-long term: if a user is working in an environment where we can't daemonize then I think it's probably fair to start fallback to the current, i.e. non-remote, behaviour. I don't think we'd want to not do something with daemonization simply because we can't support 100% of cases because we will get a huge return for those cases where we can (he says, selfishly 😄)

**Comment by findleyr** [comment] 2020-01-27 21:00
@myitcv thanks for the feedback. I think in your case the better solution might be to explicitly manage the daemon (option 4).  Even if it were possible for gopls to automatically start a daemon (which won't be the case in most environments), it would be bad to silently leave behind a process that consumes so much memory.

It will always be possible to manage the daemon yourself, but it would be great if this isn't necessary for most users to get the benefit of shared state.

**Comment by cunderwood-va** [comment] 2020-01-29 08:34
Could always have the server shut itself down if no clients connect for some (configurable?) amount of time.  If it hangs around idle, odds are the os will slowly page it out in effectively a random order, which easily results in the existing server taking longer to respond (and continuing to be laggy even after the first response) than it would take to fire up a fresh server and reparse the source.  Random seeks on-demand are *far* slower than the sort of streaming (and potentially cached) reads of the source files, despite the solid state drive that most devs will be using;  alas, os's mostly don't even try to prefetch swap-in beyond a tiny amount of read-ahead (which won't necessarily help anyway, given that the process image will have been paged out in an effectively random order).

I'm definitely interested in helping benchmark / trace the sorts of io patterns you'd see; I routinely see similar behaviour just from having several vim windows open to a project that I don't touch for a couple hours while I work on something else.  :)

**Comment by findleyr** [comment] 2020-01-29 14:25
@cunderwood-va that's a really interesting point, that I hadn't considered -- thank you!

When run as a daemon, we could expose the following options:
- An idle connection timeout.  The forwarder gopls should reconnect if it gets activity after its connection has been dropped.
- An option to either shutdown or drop the cache after some time with no connected clients. The cache could be recreated when a client connects.

**Comment by bhcleek** [comment] 2020-01-30 04:17
I prefer the option of a gopls server that shuts down automatically after some period after the last client disconnects. That's how gocode worked to good effect.

**Comment by findleyr** [comment] 2020-02-24 02:53
Thanks again for all the ideas above! Many of them have made it into the implementation.

Quick update: once the above stack of changes goes in (perhaps tomorrow), this should be ready to start testing.  It's pretty feature-complete but I'm sure there are rough edges, particularly on Mac or Windows.  I'll add an additional CL with documentation and follow-up here, but wanted to call out an implementation detail for plugin authors (@myitcv and @leitzler, I know this applies to govim, but can imagine that it applies to many other plugins and editors).

In the new implementation (on posix), you'll be able to do the following:
```
$ gopls -remote="auto"
```

Which will run an LSP forwarder and auto-start (if needed) a shared gopls hosting over a unix domain socket. That shared gopls instance will then automatically shut down after a minute with no connected clients.  Seems ideal, but unfortunately vim's job control by default sends SIGTERM on the plugin process group when exiting (the `"stoponexit"` configuration value), which causes the auto-started shared gopls to terminate.
https://github.com/vim/vim/blob/master/runtime/doc/channel.txt#L967

This is configurable, but then it is incumbent on plugin authors to observe whatever convention we decide upon.

I don't want to ignore SIGTERM, SIGINT, or SIGKILL on the shared gopls instance, but perhaps we could ignore SIGHUP.  Then if e.g. govim were to set `"stoponexit": "hup"`, exiting vim should terminate govim and the gopls forwarder, but leave the shared gopls instance intact.  Any objection to this, or alternative ideas?

**Comment by myitcv** [comment] 2020-02-24 09:07
Thanks @findleyr. As previously discussed, the `-remote=auto` mode sounds like a really good API. 

> That shared gopls instance will then automatically shut down after a minute with no connected clients

Is this configurable in some way? Because I would want the shared instance to stay around indefinitely (perhaps killable via a special flag to `gopls` that would kill a single or all remote instances).

> Seems ideal, but unfortunately vim's job control by default sends SIGTERM on the plugin process group when exiting (the "stoponexit" configuration value), which causes the auto-started shared gopls to terminate.

Apologies, I've probably missed something in the CL chain because I haven't been following particularly closely, but does this imply we are not creating the remote `gopls` instance as a daemon? Because if it is a daemon, doesn't that mean it is detached from the process group of which Vim is the parent, and hence immune from this problem?

**Comment by findleyr** [comment] 2020-02-24 15:55
> Is this timeout period configurable in some way, e.g. 0 meaning infinity?

It is, and 0 means infinity. However, when auto-starting the daemon a timeout of 1m is used:
https://golang.org/cl/220521
The assumption is that it would be bad behavior to leave around a gopls process consuming a large amount of memory -- see @cunderwood-va's comment above for a good argument against this.

> Apologies, I've probably missed something in the CL chain because I haven't been following particularly closely, but does this imply we are not creating the remote gopls instance as a daemon?

Well, we are starting a daemon in some sense of the word. I what I didn't clearly explain was that I was relying on the daemon process being reparented after vim terminates. This is, admittedly, a little hacky.

But (for linux at least), we can probably avoid this hack using setsid/setpgid. I'll experiment with this.

**Comment by myitcv** [comment] 2020-02-24 16:04
@cunderwood-va - I have zero swap on my machine, so presumably the effect in my case would be limited/zero?

**Comment by findleyr** [comment] 2020-02-27 23:10
I've pretty much gotten to the end of the features I wanted to implement, but I don't want to close this issue until I've done more testing in different environments and on different editors.

If anyone is interested in helping to test, there is now some documentation at
https://github.com/golang/tools/blob/master/gopls/doc/daemon.md

I've been using it for a while with Vim (govim) on Linux.

If you run into problems, please feel free to post here or ping me on Slack, and I'll try to fix them ASAP.

**Comment by zikaeroh** [comment] 2020-02-27 23:23
This is very cool. I use VS Code and plan to test this (looking good so far), but one immediate feedback I can give is that this mode makes it more difficult to restart gopls when something strange happens. I have to restart gopls somewhat often when I hit a bug (creating new files, renaming packages, desyncs, etc -- known issues that are already reported). To do this, I can either do a full VS Code reload (which is akin to restarting the editor in-place), or use the vscode-go extensions "restart Go language server" option (preferred)

When running normally, this is effective and does restart the process. But with `-remote=auto`, it doesn't actually restart `gopls` to the same level, which is expected given now all the real work is done elsewhere. I don't know of a solution to this (other than introducing some new signal the editor knows to send to restart something else), though I'll say that it's possible restarting this client will end up being effective anyway since most of the oddity is the non-shared stuff.

Where this gets weird is when I manually try to do this myself by killing the actual `gopls` server; the client instance of `gopls` crashes on the next request. Is there any way to detect the fact that the actual server disappeared and attempt to restart it? Or would this be a bad idea if many clients saw their server disappear and all try to create one?

**Comment by findleyr** [comment] 2020-02-28 00:18
Thanks for testing!

When you restart the client gopls you'll get a new session on the daemon. My guess is that this will fix most of the problems you describe. If it doesn't that would be a bug (of course), and a very interesting one at that. The shared state should just be idempotent, cacheable computations, and should be unlikely to get corrupted.

But your point stands about the lack of an easy solution for restarting everything.  Unfortunately having the sidecar (client) gopls seamlessly restart the daemon won't work, at least not without some significant engineering: when the daemon crashes its loses all of its session state: overlays, file versions, etc.  We need the editor itself to recreate that state.

My hope is that simply restarting the sidecar gopls is sufficient. If it's not, I'll look into implementing a restart protocol.  Any such protocol would inevitably end up crashing all connected clients, though, so ideally this would only be needed in rare cases.

**Comment by zikaeroh** [comment] 2020-02-28 00:24
> My guess is that this will fix most of the problems you describe. 

And arguably, this is better than a full restart anyway (if it works), since a lot of the old data is there, versus the full restart throwing away the bad session data _and_ the definitely-okay memoized stuff. So, I'm happier now than before!

> when the daemon crashes its loses all of its session state: overlays, file versions, etc. We need the editor itself to recreate that state.

That is an excellent point I completely glossed over.

For reference, VS Code's LSP client will gracefully handle its client exiting unexpectedly, but only up to 5 times before it hits a limit and says "I'm not going to start this again, sorry", so there's still some leeway if it comes to killing the true server. Of course, the best case is that there aren't any bugs and I don't have to do this at all. :slightly_smiling_face:

**Comment by findleyr** [comment] 2020-02-28 01:52
> The shared state should just be idempotent, cacheable computations, and should be unlikely to get corrupted.

Sigh, I spoke too soon.  As soon as I wrote that, I started auditing our cache keys to make sure this was the case, and found at least one place where caching might be broken if restarting the client and continuing to edit the same file.  I don't even think it will be that uncommon if you are restarting the client frequently.

I think I never encountered this because my usage generally falls into the pattern of having several long running vim sessions open to different directories, not restarting sessions within the same directory.

I'll try to actually manifest this in my editor tomorrow, write a test, and fix it. In the meantime, beware that there is at least one known bug!

**Comment by zikaeroh** [comment] 2020-02-28 02:21
Another case I thought of is doing `gopls` updates; you have to do a restart to load the new binary, so you do have to go through some shenanigans to make sure it's dead. Can't say I know the right thing there either.

**Comment by leitzler** [comment] 2020-02-28 16:24
Super exited about this, great work!

An initial thought regarding the unix sockets and security. It looks like `gopls` uses whatever unix socket file that happens to match the expected name. Another user on the same system could create one with the expected name and gopls will happily communicate with it.

**Comment by findleyr** [comment] 2020-02-28 16:53
@leitzler that's a great point that I had overlooked, thank you.

My initial thought is just to check that the socket owner is the same as the current user, but I can imagine that not everyone will want this restriction. We could make it configurable, and perhaps also expose configuration for the socket file permissions.  Do you have any alternative suggestions?

**Comment by findleyr** [comment] 2020-02-28 16:57
@zikaeroh when using -auto on unix, the build id of the gopls binary is hashed into the socket path, so if you restart the sidecar with a new binary, the default socket path for that new binary version will be different, and a new daemon will be started.

The old daemon will still run as long as there are connected clients, but in the simple case where you have only one VS Code session, the old daemon will shut down after a minute.

**Comment by leitzler** [comment] 2020-03-01 12:21
Yeah, checking owner & permission was my initial thought as well, and I agree that it probably won't be for everyone. On the other hand, I can't really figure out why you would like someone else owning the socket (or even let anyone else have access to it) so maybe add configuration as a new feature if someone requests it? Then we would have a use case as base for how the configuration should look like.

Also, we probably need to keep in mind how Windows handles owner & permissions of unix socket files. I don't have access to any Windows machines but I wouldn't be surprise if there are differences.

**Comment by leitzler** [comment] 2020-03-01 13:01
Also it's a bit annoying to use this feature with LittleSnitch installed on macOS since the remote always open the debug endpoint on all network interfaces. I get a popup each time from LS that asks if I really want to accept incoming connections to gopls from anywhere :).
It would be nice to keep it on localhost until it is configurable (CL 221697).

**Comment by myitcv** [comment] 2020-03-06 06:57
Just tried this out against `v0.1.8-0.20200305224536-de023d59a5d1`, @findleyr, and it works really well, thank you!

**Comment by myitcv** [comment] 2020-03-06 08:12
Only one request I'd have is that we make the timeout (https://go-review.googlesource.com/c/tools/+/220521) configurable - unless I missed how to make it so?

**Comment by findleyr** [comment] 2020-03-06 18:58
@myitcv you didn't miss anything: that configuration isn't yet exposed. In fact, that's the last change I have planned for this issue, at which point I think we should close this and open new, more specific issues as needed.

I'd put off exposing configuration for the automatic daemon because I wasn't sure of what I wanted to do if the daemon is already running, but with different configuration parameters.

For now I will expose just the following two pieces of configuration:
 `-remote.listen.timeout`  -- the listen.timeout that should be used by an auto-started remote
 `-remote.debug` -- the debug address configured on the remote server

Since neither of these affect serving, I think I'm NOT going to hash them into the daemon path as I do for build ID.  This means that you may ask for `-remote.listen.timeout=0`, but if the daemon is already currently running with the default value of 1m for `-remote.listen.timeout`, it will continue running with that value. You'll need to restart everything to pick up the new configuration.

It will be an error to set either of these flags without also setting `-remote=auto.*`.

I think that keeps things simple for now -- we can always revisit in the future if this causes problems (for example, a race between govim and ALE might cause unpredictable startup configuration).

**Comment by zikaeroh** [comment] 2020-03-10 22:48
One thing I've noticed after doing a couple of `gopls` upgrades with this enabled is that the unused process seems to use CPU when I change my project's files even when no session is attached (e.g. I ask VSC to restart the language server, I get a new `gopls serve` process as the build ID changed, then edit a file while watching `htop`).

Is `gopls` doing some sort of extra file watching? I had thought it was only using LSP's file watcher, but the fact that it's responding to edits for files it doesn't have "open" is strange.

**Comment by zikaeroh** [comment] 2020-03-10 23:47
Another thing I thought of: how does `gopls` in this mode determine which `go` binary to use? I'm guessing it inherits `PATH` from whichever process created it, which might be wrong for future `gopls` invocations. For example, if I have more than one Go version, I might set `PATH` accordingly, or if I'm working on the `go` tree itself, I might set `PATH` to point to that to see how things behave.

**Comment by findleyr** [comment] 2020-03-11 01:00
@zikaeroh that's interesting re:CPU during gopls upgrades. I would not expect that, I'll see if I can reproduce.

The gopls forwarder starts the daemon with the same path as the forwarder itself.  In other words, the sidecar gopls process uses its own path when starting the daemon. We can't use gopls from `PATH` because may LSP clients bundle a pinned gopls binary in their directory.

**Comment by zikaeroh** [comment] 2020-03-11 01:10
I didn't mean which `gopls` binary, I meant which actual `go` binary it'd use via `go/packages`, `go mod tidy`, etc. I start my editor with `code .` which means I get whichever `go` is in `PATH` when I launch which I assume is what `gopls` is using. If the long running `gopls server` is doing the same then if I change which `go` I have in my `PATH`, the server won't see that change.

**Comment by findleyr** [comment] 2020-03-11 03:06
> I didn't mean which gopls binary, I meant which actual go binary it'd use via go/packages

Ah, sorry I misread your comment. You are right, it's possible that a change to the `go` binary path won't affect the daemon. It will have indeed picked up the environment from which it was started.

Perhaps we should hash the `go` binary build ID into the daemon socket path, similarly to how we handle the `gopls` binary.

**Comment by zikaeroh** [comment] 2020-03-11 03:09
Of course, I see this becoming a slippery slope as I think there are other variables like `GOPACKAGESDRIVER` which can affect things too; there's probably a slew of things the existing hashing takes as constant for convenience. Not to say that there isn't a line in the sand you can stop hashing at, of course... 🙂

**Closed** 2020-03-12 19:44 UTC
Labels: Tools, gopls

**Comment by zikaeroh** [comment] 2020-03-12 19:46
Now that this issue is closed, should I be filing new issues for the `go` binary and CPU usage items? Or are you already tracking them somewhere?

**Comment by findleyr** [comment] 2020-03-12 19:46
I'm in the process of filing them now! You're too fast!
