### ISSUE TITLE
Improve "not enough arguments" compiler error

### ISSUE THREAD

**Issue by cgay** [golang/go#18353] opened 2016-12-16 18:38 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7.3

### What operating system and processor architecture are you using (`go env`)?
amd64/linux

### What did you do?
https://play.golang.org/p/7tKmLVSi-r

package main

func foo(a, b string) {
}
func main() {
	foo()
}

### What did you expect to see?
main.go:6: not enough arguments in call to foo(a, b string)

### What did you see instead?
main.go:6: not enough arguments in call to foo

The point being that when working through a large change one may get this error fairly often and it would be nice if the error message would remind us what the actual argument list is so we don't have to go look it up in order to fix the error.

**Comment by odeke-em** [comment] 2016-12-16 18:45
@cgay, this issue is a duplicate of https://github.com/golang/go/issues/4215 that was fixed by CL
https://golang.org/cl/25156 for Go1.8.
If you run the latest, you'll see
```shell
$ go run main.go 
# command-line-arguments
./main.go:6: not enough arguments in call to foo
	have ()
	want (string, string)
$ go version
go version devel +115e9ca Fri Dec 16 01:45:03 2016 +0000 darwin/amd64
```
Please get the latest and we should be good to go.

**Closed by odeke-em** 2016-12-16 18:45 UTC
