### ISSUE TITLE
net/http/httputil: reverse proxy canonicalizes header names

### ISSUE THREAD

**Issue by hryamzik** [golang/go#21868] opened 2017-09-13 19:24 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.8.3

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

any

### What did you do?

Served [ReverseProxy](https://golang.org/pkg/net/http/httputil/#ReverseProxy)

### What did you expect to see?

Response headers unmodified, for example `X-Jenkins-JNLP-Port`

### What did you see instead?

Broken case for headers: `X-Jenkins-Jnlp-Port`

I'm not 100% sure but looks like that causes Jenkins agent connection failures:

```
java.io.IOException: https://myjenkins.net/ is not Jenkins
```

According to RFC 7230 and RFC 7540 HTTP headers are case-insensitive so I'm not sure if that could be treated as a bug but it appears to be painful.

**Comment by mvdan** [comment] 2017-09-13 19:42
This is technically not a bug - as you say, headers are case insensitive - so it should be up to the server to accept the same header with different casing. Have you filed a bug with Jenkins?

In practice, I wonder if it would be worthwhile to make the reverse proxy keep the original cases. Does `net/http` have a history of accomodating to broken software?

**Comment by hryamzik** [comment] 2017-09-13 19:46
@mvdan I didn't fire a bug in Jenkins yet cause I have to prove the issue first. Figuring out if I could modify header with a middleware and set case-sensitive headers at all.

**Comment by tombergan** [comment] 2017-09-14 21:57
Great, sounds like this is an issue in Jenkins, not Go. I'm going to close this.

**Closed by tombergan** 2017-09-14 21:57 UTC
Labels: NeedsDecision

**Comment by hryamzik** [comment] 2017-09-14 22:02
@tombergan I still don't think modifying header names is a good behaviour. I'm sure Jenkins is not the only software to get headers by simple string comparison and debugging this is tricky.

**Comment by tombergan** [comment] 2017-09-14 22:20
Canonicalized header names have been in net/http from the beginning. Any server that relies on case-sensitive names is going to have a [very bad time](http://httpwg.org/specs/rfc7540.html#rfc.section.8.1.2) when they switch to http/2. Case-sensitive names are not going to be supported, sorry.
