### ISSUE TITLE
Failing to build on 'unknown revision' for golang.org/x/tools

### ISSUE THREAD

**Issue by LewisTheobald** [golang/go#34732] opened 2019-10-07 13:33 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/x/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/x/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/x/go/src/x/y/api/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cb/k9pww9k55wz8rgg0m566fkd80000gn/T/go-build446486685=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Updated a module that required us to run `go get -u` to pull in the latest semver.

### What did you expect to see?
Go.mod file be updated with the correct dependency and able to build / run correctly.

### What did you see instead?
<pre>go: golang.org/x/tools@v0.0.0-20191003162220-c56b4b191e2d: unknown revision c56b4b191e2d
go: error loading module requirements</pre>

**Comment by UnacceptableUse** [comment] 2019-10-07 13:37
This is happening to me too

**Comment by bcmills** [comment] 2019-10-07 13:50
@LewisTheobald, `go1.12.1` is not the latest release, or even the latest `go1.12` release: it's at least two security releases behind. (The current releases as the moment are 1.12.10 and 1.13.1.)

**Comment by bcmills** [comment] 2019-10-07 13:52
That said, given the date, it is likely that this commit does indeed no longer exist; `x/tools` was force-pushed to remove an accidental commit of a binary blob.

**Comment by bcmills** [comment] 2019-10-07 13:52
Duplicate of #34688

**Closed by bcmills** 2019-10-07 13:52 UTC

**Comment by bcmills** [comment] 2019-10-07 13:53
Note that Go 1.13 includes improved diagnostics. Upgrading to 1.13.1 may make it much easier to figure out where this dependency is coming from so you can upstream a fix.

**Comment by heschik** [comment] 2019-10-07 17:10
@bcmills -- do you know if a force push leaves `mod/cache/vcs` in a bad state like it would `GOPATH`, or do the bare repos tolerate it better?

**Comment by bcmills** [comment] 2019-10-07 17:34
I haven't tested explicitly, but on the slow path we always `git fetch` all of the refs and heads for the repo.

Assuming that the bad state in `GOPATH` is due to the discontinuity in the `master` branch, I would not expect the same problem to occur in the bare repo in the module cache.
