### ISSUE TITLE
cmd/gofmt: incorrect alignment of map keys when Arabic characters are used

### ISSUE THREAD

**Issue by Carpetsmoker** [golang/go#16170] opened 2016-06-23 23:03 UTC
`gofmt` formats this like so:

	var foo = map[string]string{
		"foo":        "bar",
		"foobar":     "foobar",
		"ﺎﻠﻋَﺮَﺒِﻳﺓ": "foo",
		"foo11":    "bar",
		"foobar11": "foobar",
	}

However, the expected format would be:

	var foo = map[string]string{
		"foo":        "bar",
		"foobar":     "foobar",
		"ﺎﻠﻋَﺮَﺒِﻳﺓ":    "foo",
		"foo11":      "bar",
		"foobar11":   "foobar",
	}

It looks like it formats by byte count, rather than character count (did not investigate yet).

Go 1.6.2 on Linux

**Comment by quentinmit** [comment] 2016-06-23 23:07
Character count is also insufficient, of course, since characters can have different widths. Still, it seems like we ought to be able to do better.

**Comment by griesemer** [comment] 2016-06-23 23:12
gofmt doesn't know about fonts. Without that, it can't do better, and even with fonts knowledge, there's not much it can do since it doesn't control how you view a file (what editor you are using).

gofmt is using text/tabwriter to achieve alignment. This is essentially a duplicate of #8273. There's also the related #12073.

**Closed by griesemer** 2016-06-23 23:12 UTC

**Comment by griesemer** [comment] 2016-06-23 23:23
PS: The issue is not just present for the wider range of Unicode chars, it is really a font issue. There are plenty of people that (would like to) use a proportional font for programming (me included) - after all proportional fonts are used because they increase readability - but gofmt cannot handle those either, even if it's all English.

Since gofmt operates on text files which know nothing about character width on the screen, it must assume that all characters have the same width. At best, it could know which characters are an (integer) multiple of the "unit" width, and then introduce spaces as necessary. However, that would not solve the general problem and unless an editor follows the same formatting, would look just as ugly.

Unfortunate.

**Comment by Carpetsmoker** [comment] 2016-06-23 23:24
> gofmt doesn't know about fonts. Without that, it can't do better, and even with fonts knowledge, there's not much it can do since it doesn't control how you view a file (what editor you are using).

Hm, I would expect the Arabic text in xterm to be monospaced? I don't read Arabic and it's difficult to see, but I have the same problem with Cyrillic characters, which certainly seem monospaced:

```
var foo = map[string]string{
    "foo": "bar",
    "сииииияяяяя": "z",
    "f1": "foobar",
}
```

**Comment by griesemer** [comment] 2016-06-23 23:35
@Carpetsmoker This is a separate issue. Note the formatting of:
```
var foo = map[string]string{
	"foo": "bar",
	"сииииияяяяя": "z",
	"f123": "foobar",
}
```
but:
```
var foo = map[string]string{
	"foo": "bar",
	"сииииияяяяя": "z",
	"f1234":       "foobar",
}
```
There is explicit code in gofmt that computes the length ratio between keys on separate lines. If the ratio between two key lengths becomes too large (or too small, depending which way you divide), the alignment of columns is broken. Here the threshold is crossed between f123 and f1234.

The thinking is that we don't want very long such tables where a single long key (possibly far down and not even on the screen when you look at the source) moves all values to the right. It's a heuristic. Your mileage may vary.

**Comment by griesemer** [comment] 2016-06-23 23:37
@Carpetsmoker PS: You're right, when using a proportional font, alignment as computed by gofmt is useless. At that point, gofmt only standardizes white space at the beginning of a line. Still better than nothing.

**Comment by Carpetsmoker** [comment] 2016-06-23 23:41
> This is a separate issue.

Ah, okay; thanks. It's not a huge issue anyway, but I've encountered this a few times and sometimes it's annoying that you can't manually correct these little things due to `gofmt`'s "all or nothing approach"...

**Comment by griesemer** [comment] 2016-06-23 23:46
@Carpetsmoker And now that you mentioned it, your original example is following the same heuristics. Note that:
```
var foo = map[string]string{
	"foo":        "bar",
	"foobar":     "foobar",
	"ﺎﻠﻋَﺮَﺒِﻳﺓ": "foo",
	"foo11":    "bar",
	"foobar11": "foobar",
}
```
but:
```
var foo = map[string]string{
	"foo":        "bar",
	"foobar":     "foobar",
	"ﺎﻠﻋَﺮَﺒِﻳﺓ": "foo",
	"foo111":     "bar",
	"foobar11":   "foobar",
}
```
(GitHub's issue tracker formats a bit differently, but in Sublime the latter is perfectly aligned.) That is, again, here the foo11 crosses the threshold.

I double-checked the implementation of text/tabwriter, and it uses actual rune (Unicode) count to determine the width of text: see updateWidth in https://golang.org/src/text/tabwriter/tabwriter.go?h=updateWidth#L380.

Thus, this is all working as intended.

**Comment by Carpetsmoker** [comment] 2016-06-24 21:46
Hah, thanks for the clarification @griesemer. As a point of interest, it also seems to be Vim's fault:

![2016-06-24-234356_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1032692/16351406/a73402cc-3a65-11e6-9465-16061690cac8.png)

As you can see, Emacs and Sublime Text work as expected, but Vim doesn't in xterm, lx-terminal, or as gVim...
