### ISSUE TITLE
cmd/go: revert special-case allowing "sync" to import "runtime/internal/atomic"

### ISSUE THREAD

**Issue by hyangah** [golang/go#42196] opened 2020-10-25 13:30 UTC
```
[Trace - 09:15:51.459 AM] Sending request 'textDocument/codeAction - (10)'.
Params: {"textDocument":{"uri":"file:///Users/hakim/go_tip/go/src/sync/pool.go"},"range":{"start":{"line":9,"character":15},"end":{"line":9,"character":40}},"context":{"diagnostics":[{"range":{"start":{"line":9,"character":15},"end":{"line":9,"character":40}},"message":"could not import runtime/internal/atomic (invalid use of internal package runtime/internal/atomic)","severity":1,"source":"compiler"}],"only":["quickfix"]}}
```

* How to reproduce:

  - Sync at tip
  - run ./make.bash
  - Open the `src` folder

I am using vscode with the following setting:
  ```
   {
    "go.goroot": "/Users/hakim/go_tip/go",
    "go.useLanguageServer": true
  }
  ```

Not sure if this is a transient error of go compiler (but `make.bash` didn't complain) or if this is an error caused by editor misconfiguration.

* Additional info
```
~/go_tip/go/src$ go version
go version devel +94887410d4 Sun Oct 25 07:51:58 2020 +0000 darwin/amd64
```
Used gopls v0.5.1, but could reproduce it with v0.5.2-pre.1.

```
[Info  - 9:15:36 AM] 2020/10/25 09:15:35 go env for /Users/hakim/go_tip/go/src
(root /Users/hakim/go_tip/go/src)
(go version go version devel +94887410d4 Sun Oct 25 07:51:58 2020 +0000 darwin/amd64
)
(valid build configuration = true)
(build flags: [])
GOPATH=/Users/hakim/go
GOPROXY=https://proxy.golang.org,direct
GOCACHE=/Users/hakim/Library/Caches/go-build
GOFLAGS=
GOSUMDB=sum.golang.org
GO111MODULE=auto
GONOPROXY=
GOPRIVATE=
GOINSECURE=
GONOSUMDB=
GOROOT=/Users/hakim/go_tip/go
GOMOD=/Users/hakim/go_tip/go/src/go.mod
GOMODCACHE=/Users/hakim/go/pkg/mod
```

**Comment by heschik** [comment] 2020-10-26 17:35
@bcmills is reverting the cmd/go change that makes this work for make.bash.

**Comment by bcmills** [comment] 2020-10-26 18:11
Marking as `release-blocker` for Go 1.16 because this regression was introduced by a change in `cmd/go` in Go 1.16.

**Comment by laboger** [comment] 2020-10-26 18:20
@bcmills What needs to be done for this CL? This was done based on a suggestion from Austin, but obviously not in the preferred way.

**Comment by bcmills** [comment] 2020-10-26 18:23
We definitely need to revert the change in `src/cmd/go/internal/load/pkg.go`, since that's adding the new special case that `gopls` is stumbling over.

It may be possible to rework the code to use `go:linkname` instead of directly importing the `internal` package. (I believe @aclements is looking into that now.) Otherwise, one possible approach might be to move `runtime/internal/atomic` to `internal/atomic` so that it can be imported in keeping with the existing `internal` rules.

**Closed** 2020-10-26 20:16 UTC
Labels: NeedsFix, release-blocker
