### ISSUE TITLE
x/mobile: Gomobile gives error as "no exported names in the package" even though there are exported names

### ISSUE THREAD

**Issue by purva-agarwal** [golang/go#37961] opened 2020-03-20 05:36 UTC
### What version of Go are you using (`go version`)?
```go version go1.13.6 windows/amd64```
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Rohan\AppData\Local\go-build
set GOENV=C:\Users\Rohan\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Projects\GoProjects;
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Rohan\AppData\Local\Temp\go-build891854990=/tmp/go-build -gno-record-gcc-switches```
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
I'm trying to generate android library using gomobile, I have this code given below, I want to generate an android library from it but Gomobile gives me error as it can't find any exported names but I think ```GetKeys``` should be considered  as an exported name

```package whisper

import (
	"context"
	"fmt"
	"log"

	"github.com/ethereum/go-ethereum/whisper/shhclient"
)

func GetKeys() {
	client, err := shhclient.Dial("ws://10.0.2.2:8546")
	if err != nil {
		log.Fatal(err)
	}
	keyID, err := client.NewKeyPair(context.Background())
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(keyID) // 0ec5cfe4e215239756054992dbc2e10f011db1cdfc88b9ba6301e2f9ea1b58d2
	publicKey, err := client.PublicKey(context.Background(), keyID)

	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(publicKey)

}```
<!--
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
-->



### What did you expect to see?
Android library generated

### What did you see instead?
```
gomobile: C:\Users\Rohan\go\bin\gobind.exe -lang=go,java -outdir=C:\Users\Rohan\AppData\Local\Temp\gomobile-work-181241247 github.com/rohankeskar19/whisper failed: exit status 1
no exported names in the package "github.com/rohankeskar19/whisper"
no exported names in the package "github.com/rohankeskar19/whisper"
no exported names in the package "github.com/rohankeskar19/whisper"
no exported names in the package "github.com/rohankeskar19/whisper"
unable to import bind/java: go [-e -json -compiled=true -test=false -export=false -deps=false -find=true -- golang.org/x/mobile/bind/java]: exit status 2: go: finding golang.org/x/mobile latest
# runtime/cgo
gcc_android.c:6:25: fatal error: android/log.h: No such file or directory
 #include <android/log.h>
                         ^
compilation terminated.
```

**Comment by andybons** [comment] 2020-03-23 16:30
@hyangah

**Comment by andybons** [comment] 2020-03-23 16:32
Duplicate of #37960

**Closed by andybons** 2020-03-23 16:32 UTC
Labels: NeedsInvestigation, mobile

**Comment by hanayashiki** [comment] 2020-06-27 10:00
for me, moving the entire project under `$GOPATH/src` solves the problem

**Comment by Guang1234567** [comment] 2020-08-13 13:38
> for me, moving the entire project under `$GOPATH/src` solves the problem

works for me, but why?

**Comment by turtletramp** [comment] 2020-08-13 14:19
I think the error message is confusing because for me the issue was solved by initializing go modules with `go mod init example.com/test`

**Comment by Guang1234567** [comment] 2020-08-14 02:53
@turtletramp 

thanks your reply.

@other

The detail for other newcome `golang-android` learner :

```bash

# make `gomobile` works fine with `go module` mode than the old `$GOPATH` mode.

# 0) 
install   go 1.14

# 1) unset env var for shell
unset GO111MODULE
unset GOMOD 

# 2) set `go module`  to `auto` for the best compatibility
go env -w GO111MODULE=auto

# 3) restart your terminal for safe

# 4) create `go module` configuration file: `go.mod` and `go.sum`
go mod init demo_android_go_mobile

# 5) build your demo go library
gomobile bind -v  -o app/libs/mobile.aar -target=android ./libmobile/src/go/mobile

# 5.1) my project structure

╰─> tree .
.
├── app
│   ├── libs
│   │   ├── mobile-sources.jar
│   │   └── mobile.aar
│   └── src
│       └── java
├── go.mod
├── go.sum
└── libmobile
    └── src
        └── go
            └── mobile
                └── mobile.go

# 5.2) file `mobile.go`

package mobile

import "fmt"

func SayHello() {
      fmt.Println("Hello Mobile")
}

func SayHelloWithParams(name string) {
      fmt.Println("Hello", name)
}

func SayHelloWithParamsAndReturn(name string) string {
      return "Hello" + name
}

func SayHelloWithParamsAndReturnAndException(name string) (string, 
error) {
      return "Hello" + name, fmt.Errorf("some error")
}

```
