### ISSUE TITLE
runtime: reenable bad pointer check in GC

### ISSUE THREAD

**Issue by rsc** [golang/go#10591] opened 2015-04-28 01:41 UTC
runtime/mbitmap.go says:

		// The following ensures that we are rigorous about what data
		// structures hold valid pointers.
		// TODO(rsc): Check if this still happens.
		if false {
			// Still happens sometimes. We don't know why.
			printlock()
			print("runtime:objectstart Span weird: p=", hex(p), " k=", hex(k))
			if s == nil {
				print(" s=nil\n")
			} else {
				print(" s.start=", hex(s.start<<_PageShift), " s.limit=", hex(s.limit), " s.state=", s.state, "\n")
			}
			printunlock()
			throw("objectstart: bad pointer in unexpected span")
		}

This needs to happen for Go 1.5. 
We broke a lot of programs in Go 1.4 by insisting on this
(for good reasons), and we don't want relapses during Go 1.5.

**Comment by aclements** [comment] 2015-06-24 22:31
Duplicate of #9880.

**Closed by aclements** 2015-06-24 22:31 UTC
