### ISSUE TITLE
sql.NullTime did not make it into the 1.12.5 tag

### ISSUE THREAD

**Issue by prolink007** [golang/go#32387] opened 2019-06-02 12:59 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12.5
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
</pre></details>

### What did you do?

Downloaded 1.12.5 through the installer on the go website. Tried using `sql.NullTime` and it is not in 1.12.5. Checked the github commits and tags. Noticed nulltime was added in april and 1.12.5 was tagged in may. The 1.12.5 tag does not contain nulltime.

### What did you expect to see?

I expected to have `sql.NullTime` in 1.12.5.

### What did you see instead?

1.12.5 Does not contain `sql.NullTime`

**Comment by ALTree** [comment] 2019-06-02 14:03
> Noticed nulltime was added in april and 1.12.5 was tagged in may. The 1.12.5 tag does not contain nulltime.

This is not how the Go release process work. Point releases (like 1.12.5) are used exclusively to fix serious issues with the base release (1.12). New features only get released in major releases, every 6 months.

`sql.NullTime` will be in Go 1.13.

Closing here, since this is working as intended.

**Closed by ALTree** 2019-06-02 14:03 UTC
