### ISSUE TITLE
http: TLS handshake error from - keeps filling up the error log

### ISSUE THREAD

**Issue by clarkk** [golang/go#56382] opened 2022-10-23 03:57 UTC
```
# go version
go version go1.19.2 linux/amd64
```

My error log just keeps filling up with random IP addresses trying to connect on to my server

```
2022/10/23 01:05:26 server.go:3230: http: TLS handshake error from xx.xx.xx.xx: read tcp xx.xx.xx.xx:x->xx.xx.xx.xx: read: connection reset by peer
2022/10/23 01:05:26 server.go:3230: http: TLS handshake error from xx.xx.xx.xx: tls: client requested unsupported application protocols ([http/0.9 http/1.0 spdy/1 spdy/2 spdy/3 h2c hq])
2022/10/23 02:58:54 server.go:3230: http: TLS handshake error from xx.xx.xx.xx: EOF
```

**Comment by ZekeLu** [comment] 2022-10-23 04:30
Duplicate of #56183?

**Comment by seankhliao** [comment] 2022-10-23 08:21
Duplicate of #56183

**Closed by seankhliao** 2022-10-23 08:21 UTC
