### ISSUE TITLE
net: can not unmarshal DNS over UDP message which is  more than 512 octets long and indicates TC=0

### ISSUE THREAD

**Issue by netroby** [golang/go#13696] opened 2015-12-21 01:04 UTC
cannot unmarshal DNS message
dial tcp: lookup g-ec4.images-amazon.com on 127.0.0.1:53: cannot unmarshal DNS message
```
$drill g-ec4.images-amazon.com     
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 4883
;; flags: qr rd ra ; QUERY: 1, ANSWER: 12, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; g-ec4.images-amazon.com.	IN	A

;; ANSWER SECTION:
g-ec4.images-amazon.com.	399	IN	CNAME	ec4.images-amazon.chinacache.net.
ec4.images-amazon.chinacache.net.	126	IN	CNAME	joyo-amazon.cncssr.chinacache.net.
joyo-amazon.cncssr.chinacache.net.	1627	IN	CNAME	hpcc-page.cncssr.chinacache.net.
hpcc-page.cncssr.chinacache.net.	60	IN	A	119.188.138.29
hpcc-page.cncssr.chinacache.net.	60	IN	A	119.188.138.24
hpcc-page.cncssr.chinacache.net.	60	IN	A	123.130.123.6
hpcc-page.cncssr.chinacache.net.	60	IN	A	218.58.209.106
hpcc-page.cncssr.chinacache.net.	60	IN	A	218.60.108.135
hpcc-page.cncssr.chinacache.net.	60	IN	A	218.24.17.40
hpcc-page.cncssr.chinacache.net.	60	IN	A	222.163.198.56
hpcc-page.cncssr.chinacache.net.	60	IN	A	221.204.171.42
hpcc-page.cncssr.chinacache.net.	60	IN	A	221.204.23.16

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.1
;; WHEN: Mon Dec 21 08:59:15 2015
;; MSG SIZE  rcvd: 690

```

**Comment by netroby** [comment] 2015-12-21 01:05
the source code to dial a tcp connection
```
c, err = net.Dial(network, addr)
```

**Comment by mikioh** [comment] 2015-12-21 03:26
I think you already have the answer. Please take a look at the output of drill.

> ;; SERVER: 127.0.0.1
> ;; WHEN: Mon Dec 21 08:59:15 2015
> ;; MSG SIZE  rcvd: 690

I suppose that the DNS server your are running should behave like the following:
```
WHILE
        READ QueryMessage from UDP endpoint
        IF QueryMessage exists THEN
                PARSE QueryMessage to extract Header, Questions, OptRR
                IF Header and Questions look fine THEN
                        COMPOSE ResponseMessage with Answers
                        IF ResponseMessageLength <= 512 THEN
                                WRITE ResponseMessage to UDP endpoint
                        ELSE
                                IF OptRR exists THEN
                                        RECOMPOSE ResponseMessage using OptRR
                                        WRITE ResponseMessage to UDP endpoint
                                ELSE
                                        RECOMPOSE ResponseMessage to be <= 512
                                        SET TC in ResponseMessage to 1
                                        WRITE ResponseMessage to UDP endpoint
                                ENDIF
                        ENDIF
                ELSE
                        COMPOSE ResponseMessage with ErrorCode
                        WRITE ResponseMessage to UDP endpoint
                ENDIF
        ENDIF
        READ QueryMessage from TCP endpoint
        IF QueryMessage exists THEN
                Parse QueryMessage to extract Header, Questions, OptRR
                IF Header and Questions look fine THEN
                        COMPOSE ResponseMessage with Answers
                        WRITE ResponseMessage to TCP endpoint
                ELSE
                        COMPOSE ResponseMessage with ErrorCode
                        WRITE ResponseMessage to TCP endpoint
                ENDIF
        ENDIF
ENDWHILE
```
Closing as "working as intended." FWIW, we already have #13356.

**Closed by mikioh** 2015-12-21 03:26 UTC

**Comment by netroby** [comment] 2015-12-21 03:53
Ok, i know you may mark it as working as intended. but how can i resolve the problem? I do not want to reimplement my own net.dial.

**Comment by mikioh** [comment] 2015-12-21 04:09
@netroby,

I think you may follow https://golang.org/wiki/Questions.
