### ISSUE TITLE
cmd/compile: can't use aliased type as underlying type in type parameter

### ISSUE THREAD

**Issue by skdltmxn** [golang/go#68935] opened 2024-08-19 01:39 UTC
### Go version

go version go1.23.0 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/gdpark/Library/Caches/go-build'
GOENV='/Users/gdpark/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/gdpark/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/gdpark/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/opt/go/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/opt/go/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.23.0'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/gdpark/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOARM64='v8.0'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/gdpark/server/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/mz/71qhy0v14w188dvdrjyw499c0000gn/T/go-build1840556302=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

Starting from Go 1.23, I get 'invalid composite literal type T' error.  
Please check the playground link which fails on Go 1.23.

https://go.dev/play/p/smVJSzGiGbn

I think I could not find any hint on this kind of change in release note, or was there?

### What did you see happen?

Got 'invalid composite literal type T' error when building originally working codebase.

### What did you expect to see?

Build should be successful.

**Comment by cuonglm** [comment] 2024-08-19 08:49
@gopherbot please backport this issue to go1.23 release.

This is a bug in compiler type checker without any workaround.

**Comment by timothy-king** [comment] 2024-08-19 17:19
Duplicate of #68903

**Closed by timothy-king** 2024-08-19 17:19 UTC
Labels: NeedsFix, compiler/runtime
