### ISSUE TITLE
docs bug: entirely unclear how to use replace directive in go.mod in production

### ISSUE THREAD

**Issue by ORESoftware** [golang/go#39084] opened 2020-05-15 00:05 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alex/Library/Caches/go-build"
GOENV="/Users/alex/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/alex/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/alex/go/src/github.com/channelmeter/cp-go-api/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qh/l8tr6tfd3gv7fmdg0b5z0p340000gn/T/go-build287184497=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
Put a replace directive in a go.mod file

### What did you expect to see?
I expect it to work in production without modifying the source files

### What did you see instead?
It's unclear how to get it to work in production or how it works if the replace directive is left in the go.mod file.  Are we expected to add/remove the replace directives manually, or will the replace directive be ignored if the replace directive path does not exist? It's unclear and the docs need to be clearer on this imo. 

My goal is to use replace directives in go.mod and leave them there, and have them only be used in development but avoid the need to remove the lines from the go.mod file when pushing git commits to prod.

**Comment by bcmills** [comment] 2020-05-15 15:22
> My goal is to use replace directives in go.mod and leave them there, and have them only be used in development but avoid the need to remove the lines from the go.mod file when pushing git commits to prod.

That is #26640.

**Comment by bcmills** [comment] 2020-05-15 15:22
Duplicate of #26640

**Closed by bcmills** 2020-05-15 15:22 UTC
Labels: Documentation
