### ISSUE TITLE
x/mobile: gomobile init failed

### ISSUE THREAD

**Issue by akzhou** [golang/go#16525] opened 2016-07-28 07:18 UTC
aks-iMac:src ReactNative$ gomobile init
gomobile: go install -p=4 golang.org/x/mobile/gl failed: exit status 2
# golang.org/x/mobile/gl

In file included from ../../TestGoMobile/src/golang.org/x/mobile/gl/work.go:24:
./work.h:20:10: fatal error: 'OpenGL/gl3.h' file not found
# include <OpenGL/gl3.h>

```
     ^
```

1 error generated.

aks-iMac:src ReactNative$ go version
go version go1.6.2 darwin/amd64
aks-iMac:src ReactNative$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ReactNative/Desktop/TestGoMobile"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by JuoCode** [comment] 2017-12-25 12:18
what's the status of this?

**Comment by eliasnaur** [comment] 2018-03-16 12:54
Is this still a problem? I can't reproduce the problem and I don't have OpenGL/gl3.h on my system either.

**Comment by changkun** [comment] 2022-02-19 18:17
Since `gomobile init` seems to work properly, I would close the issue as an outdated status. Feel free to comment out if this is not the case.

**Closed by changkun** 2022-02-19 18:17 UTC
Labels: mobile
