### ISSUE TITLE
cmd/compile: hangs compiling hex fp constant

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11364] opened 2015-06-23 16:42 UTC
```go tool compile``` hangs in karatsuba compiling the following program:
```go
package a
var e = 1<<1p10000000<<3
```

Can we just break off hex exponents (p)? They are not supported by go/types-based frontends and so are non-portable.

go version devel +514014c Thu Jun 18 15:54:35 2015 +0200 linux/amd64

**Comment by griesemer** [comment] 2015-06-23 17:05
Floating-point constants with binary ('p') exponents are not permitted in the source and that has been fixed (issue #9036). E.g.:
```
package p
const _ = 1p10
```
is not accepted anymore:
x.go:2: malformed floating point constant

However, it appears that the numbers are still recognized (and not set to 0 or 1) and then make it through the rest of type-checking/constant evaluation:
```
package p
const _ = 1 << 1p10
```
x.go:2: malformed floating point constant
x.go:2: stupid shift: 1024

The fact that we hang in Karatsuba is known and is effectively (indirectly) a duplicate of #11327. But once we set 'p' exponent values to 0, the hang should disappear.

Assigning to @dr2chase who fixed issue #9036.

**Comment by dr2chase** [comment] 2016-10-21 19:32
This appears to be fixed.  New parser?
```
$ cat > bug11364.go
package a
var e = 1<<1p10000000<<3
$ go tool compilebug11364.go
go tool compile bug11364.go
bug11364.go:2: syntax error: unexpected p10000000 after top level declaration
```
and it wastes no time telling me that.

**Closed by dr2chase** 2016-10-21 19:32 UTC

**Comment by griesemer** [comment] 2016-10-21 20:29
@dr2chase Fixed by you in https://go-review.googlesource.com/c/10450/ I think.
