### ISSUE TITLE
net/http: TestTransportMaxConnsPerHost still flaky

### ISSUE THREAD

**Issue by cuonglm** [golang/go#31982] opened 2019-05-11 18:45 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +83f205fa88 Sun May 12 02:55:19 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cuonglm/.cache/go-build"
GOENV="/home/cuonglm/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/cuonglm/go"
GOPROXY="direct"
GOROOT="/home/cuonglm/sources/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/home/cuonglm/sources/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build766721718=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
From git root repo
$ cd src/net/http
$ go test -run TestTransportMaxConnsPerHost -count=100 -race

### What did you expect to see?

Test passed

### What did you see instead?

```
--- FAIL: TestTransportMaxConnsPerHost (0.07s)
    transport_test.go:661: Too many get connections (http2): 2
    transport_test.go:676: Too many get connections (http2): 3
--- FAIL: TestTransportMaxConnsPerHost (0.03s)
    transport_test.go:661: Too many get connections (http2): 2
    transport_test.go:676: Too many get connections (http2): 3
--- FAIL: TestTransportMaxConnsPerHost (0.08s)
    transport_test.go:661: Too many get connections (http2): 2
    transport_test.go:676: Too many get connections (http2): 3
--- FAIL: TestTransportMaxConnsPerHost (0.06s)
    transport_test.go:661: Too many get connections (http2): 2
    transport_test.go:676: Too many get connections (http2): 3
--- FAIL: TestTransportMaxConnsPerHost (0.03s)
    transport_test.go:661: Too many get connections (http2): 2
    transport_test.go:676: Too many get connections (http2): 3
FAIL
exit status 1
FAIL	net/http	4.433s
```

**Comment by fraenkel** [comment] 2019-05-11 18:56
This is a bit interesting because we get the right number of dials and TLS handshakes but the connection returned is supposed not marked reused.

**Comment by fraenkel** [comment] 2019-05-11 19:14
The problem is that the GotConn for http2 (h2_bundle:6878) is called before we know whether we are creating a new stream (h2_bundle:  7449) which is what determines reuse.

This is not a flaky test but a real bug.

**Comment by fraenkel** [comment] 2019-05-11 19:15
Using the nextStreamID is flawed anyhow. If you allow HTTP, we start at 3 which means its immediately reused.

**Comment by fraenkel** [comment] 2019-05-11 19:27
If we move the GotConn call into getClientConn(h2_bundle:749), we can distinguish between a new connection and a used connection.

**Comment by anakin** [comment] 2019-05-12 10:01
➜  http  go test -run TestTransportMaxConnsPerHost -count=100 -race
PASS
ok  	net/http	1.641s

**Comment by anakin** [comment] 2019-05-12 10:02
by the way,
➜  http go version
go version go1.12.5 darwin/amd64

**Comment by fraenkel** [comment] 2019-05-12 12:52
I submitted a fix which does highlight the issue with http2. I did some other testing and found some of the other ClientTrace calls like TLSHandshakreXXX are missing.

**Comment by bcmills** [comment] 2019-05-14 13:30
The `darwin-amd64-race` builder caught this too:
https://build.golang.org/log/06b60fdfdf4a88e04ae4181d80ddd39db9aaafa0

**Comment by bcmills** [comment] 2019-05-14 13:50
I just got two TryBot flakes in a row on this:
https://storage.googleapis.com/go-build-log/06afa4b7/freebsd-amd64-12_0_63953b9e.log
https://storage.googleapis.com/go-build-log/433caf31/windows-amd64-2016_dcea98e4.log

**Comment by bcmills** [comment] 2019-05-14 13:51
CC @bradfitz

**Comment by bradfitz** [comment] 2019-05-16 19:56
Whoops, I'd forgotten to submit 177037. Done. Hopefully it's better now.

**Comment by bcmills** [comment] 2019-06-14 02:01
In the other direction, it appears that `TestTransportMaxConnsPerHost` occasionally deadlocks: see #32336.

**Comment by rsc** [comment] 2019-06-28 02:59
Closing as duplicate of #32336 now that we understand how severe that one is.

**Closed by rsc** 2019-06-28 02:59 UTC
Labels: NeedsInvestigation, Soon, Testing
