### ISSUE TITLE
Ranging over string of int gives wrong output

### ISSUE THREAD

**Issue by gandharvas** [golang/go#40325] opened 2020-07-21 05:27 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.14.6
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
Windows
</pre></details>

### What did you do?

https://play.golang.org/p/1RVQkIi61nI

### What did you expect to see?
1 2 3 4

### What did you see instead?
49 50 51 52

**Comment by gandharvas** [comment] 2020-07-21 05:28
Can I work on this issue and fix?

**Comment by ianlancetaylor** [comment] 2020-07-21 05:46
This is correct behavior.  The string is Unicode, and the Unicode value for `1` is decimal 49 (https://www.codetable.net/decimal/49).

Compare to https://play.golang.org/p/vOaWa9sdw0e.

Closing because this is not a bug.

**Closed by ianlancetaylor** 2020-07-21 05:46 UTC
