### ISSUE TITLE
net/url: When I used net/url package ,I met a Bug.

### ISSUE THREAD

**Issue by sober-wang** [golang/go#41491] opened 2020-09-19 03:36 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version v1.13.5

</pre>

### Does this issue reproduce with the latest release?

Maybe ,this issue reproduce with the latest release. 

### What did you do?

```go
package main

import (
	"fmt"
	"log"
	"net/url"
)

func main() {
	fmt.Println("vim-go")
	u := "http://admin:FSdf%30g52@192.168.1.1:8888"
	log.Println(u)
	uri, err := url.Parse(u)
	if err != nil {
		fmt.Println("=>", err)
	}
	log.Println(uri)
	URL := uri.String()
	log.Println(URL)
}

```
If you run this code , the `%3` will miss
![image](https://user-images.githubusercontent.com/35804630/93658030-7a169880-fa6a-11ea-83ed-506174e7c074.png)

### What did you expect to see?
I hope the net/url can clear distinction the correct URI, don't miss something.

**Comment by ianlancetaylor** [comment] 2020-09-19 05:11
When you want to show plain text, please just paste plain text.  Please do not paste an image.  Plain text is much easier to read and understand.  Thanks.

In a URL `%30` means ASCII character 0x30, which is `0`.  See, for example, https://en.wikipedia.org/wiki/Percent-encoding .

Closing because this is behaving as intended.

**Closed by ianlancetaylor** 2020-09-19 05:11 UTC
