### ISSUE TITLE
cmd/go: "package command-line-arguments is not a main package" is confusing

### ISSUE THREAD

**Issue by willfaught** [golang/go#64484] opened 2023-11-30 22:23 UTC
### Go version

go version go1.21.4 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/Will/Library/Caches/go-build'
GOENV='/Users/Will/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/Will/Library/Application Support/go/pkg/mod'
GONOPROXY='github.com/FrontRowXP,github.com/frontrowxp'
GONOSUMDB='github.com/FrontRowXP,github.com/frontrowxp'
GOOS='darwin'
GOPATH='/Users/Will/Library/Application Support/go'
GOPRIVATE='github.com/FrontRowXP,github.com/frontrowxp'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/Cellar/go/1.21.4/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/Cellar/go/1.21.4/libexec/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/Will/Developer/work/backend/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/bx/qk0phsxd265fqj512dnnpg080000gn/T/go-build1547774763=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

go run ./cmd/graphql/main.go

### What did you expect to see?

>package is not a main package

### What did you see instead?

>package command-line-arguments is not a main package

I have no idea where "command-line-arguments" came from.

**Comment by seankhliao** [comment] 2023-11-30 23:05
Duplicate of #36043

**Closed by seankhliao** 2023-11-30 23:05 UTC
