### ISSUE TITLE
fmt: all [*]Print[**] functions should not make heap allocations

### ISSUE THREAD

**Issue by go101** [golang/go#63456] opened 2023-10-09 08:31 UTC
Go toolchain 1.21 has made `reflect.ValueOf` not allocate if possible,
so now there should be no obstacles which force the print functions allocate.

(I remembered there is an issue for this, but I couldn't find it now.)

**Comment by mateusz834** [comment] 2023-10-09 09:18
#62653 #8618

**Comment by mvdan** [comment] 2023-10-09 10:16
Closing as a duplicate of that first issue.

**Closed by mvdan** 2023-10-09 10:16 UTC
