### ISSUE TITLE
cmd/go: go mod tidy revoke the modify about go.sum made by go build 

### ISSUE THREAD

**Issue by Sherlock-Holo** [golang/go#29163] opened 2018-12-09 14:46 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sherlock/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/sherlock/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/sherlock/git/recruitment/interview/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build973697242=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
`go mod tidy`  and then `git add .` and then `go build -v` , `go mod tidy` again

### What did you expect to see?
go.sum isn't modified

### What did you see instead?
use `git diff` and found go.sum has been modified. `go mod tidy` again and it revoke the modify which `go build -v` do

**Comment by bcmills** [comment] 2018-12-10 14:45
If it involves a replaced module, this is a duplicate of #27868.

Otherwise, it needs more detail: please provide an exact sequence of commands we can execute to reproduce the problem, including the directory structure and the contents of the `.go` and `go.mod` files.

**Comment by bcmills** [comment] 2018-12-12 01:58
Provisionally closing as a duplicate of #27868. Please let us know if you can reproduce this without replacement modules.

**Closed by bcmills** 2018-12-12 01:58 UTC
Labels: NeedsInvestigation, WaitingForInfo, modules
