### ISSUE TITLE
golang 1.10 httpserver Not compatible java HttpClient 

### ISSUE THREAD

**Issue by gzw13999** [golang/go#24252] opened 2018-03-05 16:44 UTC
### What version of Go are you using (`go version`)?
golang 1.10

### Does this issue reproduce with the latest release?
golang 1.4.3 normal

### What operating system and processor architecture are you using (`go env`)?
windows-amd64

### What did you do?
java HttpClient send request

err := r.ParseMultipartForm(102400)
username =r.FormValue("username")
password = r.FormValue("password")

//The username or password value is empty

### What did you see instead?
The username or password value is empty

JAVA CODE
import java.io.File;
import java.util.concurrent.LinkedBlockingDeque;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

import org.apache.commons.httpclient.HttpClient;
import org.apache.commons.httpclient.methods.PostMethod;
import org.apache.commons.httpclient.methods.multipart.FilePart;
import org.apache.commons.httpclient.methods.multipart.MultipartRequestEntity;
import org.apache.commons.httpclient.methods.multipart.Part;
import org.apache.commons.httpclient.methods.multipart.StringPart;

public class Test {
	static ThreadPoolExecutor taskPool = new ThreadPoolExecutor(10,10, 3000, TimeUnit.MILLISECONDS,
			new LinkedBlockingDeque(), new ThreadPoolExecutor.CallerRunsPolicy());

	public static void main(String[] args) {
		final File f=new File("2.jpg");
		System.out.println(f);
		for(int i=0;i<10;i++){
			taskPool.execute(new Thread(){
				public void run() {
					try {
						HttpClient client=new HttpClient();
						PostMethod method = new PostMethod("http://114.55.0.247/create.json");
						//PostMethod method =new UTF8PostMethod("http://114.55.0.247/create.json");
						Part list[]={
							new StringPart("username", "sssss"),
							new StringPart("password", "1111"),
							new StringPart("typeid", "3040"),
							new StringPart("softid", "ssss"),
							new StringPart("softkey", "ddddddd"),
							new FilePart("image", f)
							
						};
						MultipartRequestEntity entity = new MultipartRequestEntity(list , method.getParams());
						method.setRequestEntity(entity);
						client.executeMethod(method);
						
						byte b[]=method.getResponseBody();
						method.releaseConnection();
						System.out.println(new String(b));
					} catch ( Exception e) {
						e.printStackTrace();
					}  
				}
				
			});
		}
		

	}
}

**Comment by gzw13999** [comment] 2018-03-05 16:49
Add the following format
java HttpClient

POST /create.json HTTP/1.1
User-Agent: Jakarta Commons-HttpClient/3.1-rc1
Host: 114.*.*.*
Content-Length: 3299
Content-Type: multipart/form-data; boundary=K51yWjn2jj_bxElyY__h_uRqHY4oqga2xjfe

--K51yWjn2jj_bxElyY__h_uRqHY4oqga2xjfe
Content-Disposition: form-data; name="username"
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 8bit

sssss
--K51yWjn2jj_bxElyY__h_uRqHY4oqga2xjfe
Content-Disposition: form-data; name="password"
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 8bit

1111
--K51yWjn2jj_bxElyY__h_uRqHY4oqga2xjfe
Content-Disposition: form-data; name="typeid"
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 8bit

3040
--K51yWjn2jj_bxElyY__h_uRqHY4oqga2xjfe
Content-Disposition: form-data; name="softid"
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 8bit

ssss
--K51yWjn2jj_bxElyY__h_uRqHY4oqga2xjfe
Content-Disposition: form-data; name="softkey"
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 8bit

ddddddd
--K51yWjn2jj_bxElyY__h_uRqHY4oqga2xjfe
Content-Disposition: form-data; name="image"; filename="2.jpg"
Content-Type: application/octet-stream; charset=ISO-8859-1
Content-Transfer-Encoding: binary
byte
--K51yWjn2jj_bxElyY__h_uRqHY4oqga2xjfe--

**Comment by bradfitz** [comment] 2018-03-05 17:01
Duplicate of #24041

**Closed by bradfitz** 2018-03-05 17:01 UTC
