### ISSUE TITLE
cmd/go: `go mod why` isn't enlightening for non-build dependencies

### ISSUE THREAD

**Issue by dsymonds** [golang/go#37162] opened 2020-02-11 00:04 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +0377f06168 Tue Dec 17 20:57:06 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Unknown

### What did you do?

Check out a clean copy of `cloud.google.com/go`, and run `go mod why dmitri.shuralyov.com/gpu/mtl` in its main module.

Providing `-m` to the command doesn't change it either.

### What did you expect to see?

I expect to see some list of packages that show the dependency tree.

### What did you see instead?

```
# dmitri.shuralyov.com/gpu/mtl
(main module does not need module dmitri.shuralyov.com/gpu/mtl)
```

/cc @robpike @dmitshur

**Comment by bcmills** [comment] 2020-02-11 02:55
Duplicate of #27900

**Closed by bcmills** 2020-02-11 02:55 UTC
Labels: GoCommand, NeedsInvestigation, modules
