### ISSUE TITLE
net/netip: disagrees with net.ParseIP on v4on6

### ISSUE THREAD

**Issue by anacrolix** [golang/go#50844] opened 2022-01-27 03:57 UTC
`net/netip.Addr` obtained via strings, vs. from slices don't compare as expected.

https://go.dev/play/p/Bsrg-fO6eRk?v=gotip

I think the issue boils down to `net.ParseIP` always essentially returning what `net/netip.Addr` would consider a `v4on6` for IPv4 addresses. The workaround is to bypass net.ParseIP. I'm not sure if it's expected that ip and netip should differ here, and whether it would be breaking compatibility guarantees for ParseIP to return a 4 byte slice for a dotted address string. Perhaps there should be some kind of conversion function/method to smooth the disagreement over?

**Comment by ianlancetaylor** [comment] 2022-01-27 04:10
CC @bradfitz @josharian

**Comment by bradfitz** [comment] 2022-01-27 17:00
This is all by design. Fixing the 4in6 handling of the net package was one of the original motivations of the new package.

If there are any documentation omissions, let us know, but I believe this is all documented (and extensively tested & fuzzed)

**Comment by ianlancetaylor** [comment] 2022-01-29 01:00
Thanks, closing.  Please comment if you disagree.

**Closed by ianlancetaylor** 2022-01-29 01:00 UTC
Labels: NeedsInvestigation

**Comment by Fndroid** [comment] 2022-01-31 12:18
If `netip.ParseAddr` returns ipv6 if we pass a v4in6 address as the argument. Will this behavior break `net.Dial`?

Should we convert it manually?
