### ISSUE TITLE
cmd/compile: floating-point broken on android-arm-corellium builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#36830] opened 2020-01-28 15:12 UTC
```
--- FAIL: TestFloat32 (0.11s)
    rand_test.go:360: Float32() should be in range [0,1). ct: 2274285 f: 0.27337575
FAIL
FAIL	math/rand	0.548s
```

Seems to have started after Jan. 19.

Have there been recent changes in this builder image or configuration? Otherwise, the only major changes over that interval have been @4a6f656c's RISC-V changes.

CC @cagedmantis @dmitshur @toothrot @zenly

[2020-01-28T02:40:44-a858d15/android-arm-corellium](https://build.golang.org/log/3857c5db54a61d32ab48dae06f1e5cf2699a1427)
[2020-01-28T02:39:28-d8e0526/android-arm-corellium](https://build.golang.org/log/812b43dfced317fbfcdb6ec73e98ce80ab7bb733)
[2020-01-27T23:23:00-22f09ce/android-arm-corellium](https://build.golang.org/log/ca60519eb3db20eadcae4e303f39a35d457a35a7)
[2020-01-27T20:45:39-74d366f/android-arm-corellium](https://build.golang.org/log/d61050b56f9c4d0f06f2fbdb96c1dc911ea20a8c)
[2020-01-27T14:34:16-4615b39/android-arm-corellium](https://build.golang.org/log/ebdb8db43691e2165e3326d031d2d31da44eded4)
[2020-01-25T16:34:18-73d2137/android-arm-corellium](https://build.golang.org/log/a3ef854c1c098f6688b8a2b88e6aeb0af223bd4f)
[2020-01-24T19:19:16-e35876e/android-arm-corellium](https://build.golang.org/log/06ee4911ca7d6152ba172b4b3869307be8abd62d)
[2020-01-24T17:36:44-1f9f88b/android-arm-corellium](https://build.golang.org/log/0d190c152a9a9d194f47c6646a67f7cfca7363d8)
[2020-01-23T23:07:10-8d7be1e/android-arm-corellium](https://build.golang.org/log/56897dcb955762d66d7573f83751fe581e3e89de)
[2020-01-23T21:01:12-ace25f8/android-arm-corellium](https://build.golang.org/log/bcdceb7751a52fb06dd1a623c3fd41ff8c6010d4)
[2020-01-23T20:44:44-8453844/android-arm-corellium](https://build.golang.org/log/536c6146617201a2973a026997446b1de7a6fc52)
[2020-01-23T19:11:41-39ea3d0/android-arm-corellium](https://build.golang.org/log/adbe1d8b7fafacc52c7b5add9124d21310f15ba9)
[2020-01-23T16:52:00-64378c2/android-arm-corellium](https://build.golang.org/log/7b96da4fa0b90e4cea55667c399c0162b236605d)
[2020-01-23T07:39:53-9f07cdd/android-arm-corellium](https://build.golang.org/log/6e5962e4fc98c10ca94a06e36638ebd864541a86)
[2020-01-22T18:10:42-895b7c8/android-arm-corellium](https://build.golang.org/log/d27ae1e1a2daaca39e5221aded58422c518a5d17)
[2020-01-22T15:24:05-6718cb6/android-arm-corellium](https://build.golang.org/log/e36005b2277f67873a451894795ab5cfc9ad1580)

**Comment by bcmills** [comment] 2020-01-28 15:17
Actually, I think the whole floating point implementation on this builder is busted.
Is this the only `softfloat` builder we have?

`runtime.TestFloat64`:
[2020-01-27T14:32:54-f652015/android-arm-corellium](https://build.golang.org/log/9a981177e158d14d5e60351c831f83db4843fcd2)
[2020-01-22T16:57:26-fb2e3b8/android-arm-corellium](https://build.golang.org/log/98c1c94f8a4820d34519ccb5845b799335d69e58)

`math/big.TestFloat64Distribution`:
[2020-01-28T02:21:26-8f14f33/android-arm-corellium](https://build.golang.org/log/9107b9cdd17be482e4924dac5afe9ec37d62a156)

`internal/trace.TestMUD{,Tracking}` (which seem to be sensitive to floating-point computations):
[2020-01-27T16:13:58-6fbdfe4/android-arm-corellium](https://build.golang.org/log/ddb59583cb5b2c472fac1bb0cacdddb95eb2f2d5)
[2020-01-26T20:38:34-c333d07/android-arm-corellium](https://build.golang.org/log/efed8bfeeedd7c24574d53e2787c9bc518d7c291)
[2020-01-25T16:31:46-bcd50e4/android-arm-corellium](https://build.golang.org/log/b756270c9a29c70dd5a87b70c9830cd4d3dcfa1d)
[2020-01-25T16:30:26-7f331e0/android-arm-corellium](https://build.golang.org/log/3e5b851fe80a619dd695962016c2d8c43ff5f3cb)
[2020-01-25T05:48:48-69660ed/android-arm-corellium](https://build.golang.org/log/7c83886f77d25888157f701bd860e5afac7b339f)
[2020-01-25T05:48:12-01df660/android-arm-corellium](https://build.golang.org/log/fdfa92dda1c94530b4b8aeb316b27a1e7c5591ec)
[2020-01-25T05:11:20-37981da/android-arm-corellium](https://build.golang.org/log/25e5d09a33e6aa2766400d3cf8eea8ba5b40b05d)
[2020-01-24T23:27:33-64c22b7/android-arm-corellium](https://build.golang.org/log/3ec1c3c09ab43fe46c4f961fe5b0c37d749a88a8)
[2020-01-24T23:27:22-ad3cef1/android-arm-corellium](https://build.golang.org/log/f8d870b04c83a7a6ff17a78436c9d411066f6574)
[2020-01-24T19:47:23-e948d2b/android-arm-corellium](https://build.golang.org/log/e4146c11f7b733544d25fd2954f145804881a99f)
[2020-01-24T19:37:58-67539f6/android-arm-corellium](https://build.golang.org/log/16168587445fe886133b9838452b48a80aa2dbf8)
[2020-01-23T22:31:25-953bc8f/android-arm-corellium](https://build.golang.org/log/d446d76e7021ad0179f167310b4244978ddcc63a)
[2020-01-23T18:03:09-8689ea6/android-arm-corellium](https://build.golang.org/log/0ef3f2cd7f7bce8710dd4964e9ccd4ddbc99029f)
[2020-01-23T14:36:57-82a2f82/android-arm-corellium](https://build.golang.org/log/b419827fa0dde739688a03d3af8fcf8166c500d3)
[2020-01-23T07:33:33-fa610c7/android-arm-corellium](https://build.golang.org/log/26b72404b2688361eeb2a0e8d223b4713398930f)
[2020-01-23T00:22:41-9f1d55c/android-arm-corellium](https://build.golang.org/log/3792df95898b74c823ba346c511e19032b2b0e6b)
[2020-01-22T22:06:30-f9fe783/android-arm-corellium](https://build.golang.org/log/e6ec799ad529a855a273082d70312b4a407a53a2)
[2020-01-22T18:54:48-9b5bd30/android-arm-corellium](https://build.golang.org/log/1d4b5984575f21b063e4cb47b2b62444530bea02)
[2020-01-22T16:56:57-b4f15e7/android-arm-corellium](https://build.golang.org/log/61cea094638e0a661fe925c7ff7a24fb15ddbc90)

**Comment by randall77** [comment] 2020-01-28 18:15
@benshi001 Ben, can you take a look?
As far as I can tell floating-point compares are broken. The values printed in the error messages look correct.

**Comment by randall77** [comment] 2020-01-28 20:42
Seems to be failing for GOARCH=arm GOARM=6. GOARM=7 is also broken. GOARM=5 is fine.
```
$ GOARCH=arm GOARM=6 ../bin/go test -c math/rand
$ gomote push user-khr-android-arm-corellium-0
$ gomote run user-khr-android-arm-corellium-0 go/src/rand.test -test.run=Float32 -test.short -test.v
```

**Comment by randall77** [comment] 2020-01-28 20:44
Here's a simple reproducer:
```
package main

import "fmt"

//go:noinline
func geq(x, y float32) bool {
	return x >= y
}

func main() {
	var x float32 = 3.0
	var y float32 = 4.0
	for i := 0; i < 1e8; i++ {
		if geq(x, y) {
			fmt.Printf("bad at iteration %d\n", i)
		}
	}
}
```
Compile this with GOARCH=arm GOARM=7, copy to builder, and run it. We get:
```
bad at iteration 189792
bad at iteration 251153
bad at iteration 3142582
bad at iteration 8808617
bad at iteration 12425345
bad at iteration 16630084
bad at iteration 16636778
bad at iteration 22789256
bad at iteration 29942954
bad at iteration 32523884
bad at iteration 32766014
bad at iteration 50490757
bad at iteration 60613276
bad at iteration 61778799
bad at iteration 71722383
bad at iteration 72913204
bad at iteration 76562474
bad at iteration 76569282
bad at iteration 79995821
```
Something is seriously wrong with the floating point comparison hardware on this machine.

The code for `geq` is just:
```
TEXT main.geq(SB) /usr/local/google/home/khr/gowork/tmp1.go
  tmp1.go:7             0x9d620                 ed9d0a01                MOVF 0x4(R13), F0       
  tmp1.go:7             0x9d624                 ed9d1a02                MOVF 0x8(R13), F1       
  tmp1.go:7             0x9d628                 eeb40ac1                CMPF F1, F0             
  tmp1.go:7             0x9d62c                 eef1fa10                MOVW FPSCR, APSR_NZCV   
  tmp1.go:7             0x9d630                 e3a00000                MOVW $0, R0             
  tmp1.go:7             0x9d634                 a3a00001                MOVW.GE $1, R0          
  tmp1.go:7             0x9d638                 e5cd000c                MOVB R0, 0xc(R13)       
  tmp1.go:7             0x9d63c                 e28ef000                ADD $0, R14, R15        
```

**Comment by randall77** [comment] 2020-01-28 20:46
... or maybe the OS isn't saving/restoring floating point comparison flags? That would explain the erraticness...

**Comment by randall77** [comment] 2020-01-28 21:02
Seems to be all the comparisons, occasionally.
The error is always consistent. For `==`, it's always a false negative. For all the other comparisons it is always a false positive.
```
package main

import "fmt"

//go:noinline
func geq(x, y float32) bool {
	return x >= y
}

//go:noinline
func leq(x, y float32) bool {
	return x <= y
}

//go:noinline
func gt(x, y float32) bool {
	return x > y
}

//go:noinline
func lt(x, y float32) bool {
	return x < y
}

//go:noinline
func eq(x, y float32) bool {
	return x == y
}

//go:noinline
func ne(x, y float32) bool {
	return x != y
}

func main() {
	for _, t := range []struct {
		name   string
		f      func(float32, float32) bool
		tx, ty float32 // inputs that should result in true
		fx, fy float32 // inputs that should result in false
	}{
		{">=", geq, 4, 3, 3, 4},
		{"<=", leq, 3, 4, 4, 3},
		{">", gt, 4, 3, 3, 4},
		{"<", lt, 3, 4, 4, 3},
		{"==", eq, 3, 3, 3, 4},
		{"!=", ne, 3, 4, 3, 3},
	} {
		for i := 0; i < 2e7; i++ {
			if !t.f(t.tx, t.ty) {
				fmt.Printf("bad %f %s %f, want true: %d\n", t.tx, t.name, t.ty, i)
			}
			if t.f(t.fx, t.fy) {
				fmt.Printf("bad %f %s %f, want false: %d\n", t.fx, t.name, t.fy, i)
			}
		}
	}
}
```
```
bad 3.000000 >= 4.000000, want false: 25635
bad 3.000000 >= 4.000000, want false: 69076
bad 3.000000 >= 4.000000, want false: 4916526
bad 3.000000 >= 4.000000, want false: 9937096
bad 3.000000 >= 4.000000, want false: 12789690
bad 3.000000 >= 4.000000, want false: 19958632
bad 4.000000 <= 3.000000, want false: 462589
bad 4.000000 <= 3.000000, want false: 14222185
bad 4.000000 <= 3.000000, want false: 15495103
bad 3.000000 > 4.000000, want false: 5855504
bad 3.000000 > 4.000000, want false: 7465563
bad 3.000000 > 4.000000, want false: 14899503
bad 3.000000 > 4.000000, want false: 16291141
bad 3.000000 > 4.000000, want false: 16402125
bad 3.000000 > 4.000000, want false: 17907133
bad 4.000000 < 3.000000, want false: 9664194
bad 4.000000 < 3.000000, want false: 13493741
bad 4.000000 < 3.000000, want false: 16757572
bad 3.000000 == 3.000000, want true: 2776863
bad 3.000000 == 3.000000, want true: 6072085
bad 3.000000 == 3.000000, want true: 10121837
bad 3.000000 == 3.000000, want true: 12263554
bad 3.000000 == 3.000000, want true: 15621010
bad 3.000000 == 3.000000, want true: 18710498
bad 3.000000 != 3.000000, want false: 1481130
bad 3.000000 != 3.000000, want false: 1484425
bad 3.000000 != 3.000000, want false: 1487792
bad 3.000000 != 3.000000, want false: 3018792
bad 3.000000 != 3.000000, want false: 19224977
```

**Comment by randall77** [comment] 2020-01-28 21:18
Same behavior for the compare-with-zero instruction, and for float64.

**Comment by cherrymui** [comment] 2020-01-28 22:23
Does it work if we disable async preemption? GODEBUG=asyncpreemptoff=1

**Comment by cherrymui** [comment] 2020-01-28 22:24
GOARM=5 implies softfloat. I don't think android-arm is a softfloat builder. But we do have some softfloat tests that runs everywhere.

The arm5 builder is a softfloat builder (and the only one).

**Comment by randall77** [comment] 2020-01-28 22:34
> Does it work if we disable async preemption? GODEBUG=asyncpreemptoff=1

Still buggy with that set. Same with GOGC=off.

arm64 binaries on the same machine work fine.

**Comment by cherrymui** [comment] 2020-01-28 22:38
Thanks. So it is probably indeed a hardware/OS bug...

**Comment by randall77** [comment] 2020-01-28 22:59
I can reproduce with C.
```
#include <stdio.h>

int geq(double x, double y) {
  return x >= y;
}

double x = 3;
double y = 4;

int main(int argc, char *argv[]) {
  for (int i = 0; i < 100000000; i++) {
    if (geq(x, y)) {
          printf("failed at iteration %d\n", i);
        }
    }
}
```
```
failed at iteration 532580
failed at iteration 19932913
failed at iteration 29020612
failed at iteration 32054460
failed at iteration 67123803
failed at iteration 70001529
failed at iteration 87241841
failed at iteration 89238362
failed at iteration 94347886
```
Note that it fails when compiled with `arm-linux-gnueabihf-gcc` (hard float) and not with `arm-linux-gnueabi-gcc` (soft float).

Anyone know how to contact Corellium and file a bug? Their website is not very helpful.

**Comment by cherrymui** [comment] 2020-01-28 23:08
cc @eliasnaur

**Comment by randall77** [comment] 2020-01-29 00:08
I got in contact with the Corellium folks and they've opened an internal issue for it. Likely it will be fixed in their next release, eta unknown.
I'll remove the 1.14 milestone. There's no more action required by us on this, other than to verify the fix when it is released.

**Comment by randall77** [comment] 2020-02-24 17:46
Looks like this was fixed by an update on Corellium's part on our about 2/17.

**Closed by randall77** 2020-02-24 17:46 UTC
Labels: Builders, OS-Android, WaitingForInfo
