### ISSUE TITLE
cmd/tool/compile: `go build` cannot generate executable file

### ISSUE THREAD

**Issue by hitzhangjie** [golang/go#55853] opened 2022-09-25 01:05 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.19.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zhangjie/Library/Caches/go-build"
GOENV="/Users/zhangjie/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zhangjie/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zhangjie/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/zhangjie/Downloads/image/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0j/mvtnlhyj5j9cyqqq1b27bgg40000gn/T/go-build4139814822=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I create following files under folder image:

file1: go.mod

```
module image

go 1.19
```

file2: 

```
package main

import "fmt"

func main() {
	fmt.Println("hello world")
}
```

Then I run `go build`, then no any error reported, and `echo $?` outputs 0. That said `go build` success, but no any executable generated.

### What did you expect to see?

I think it should generate the executable.

### What did you see instead?

No executable generated. Go compiler doesn't differentiate go inner image package and user-defined image module? If I rename module image to xxx/image, it works as expected.

**Comment by ryicoh** [comment] 2022-09-25 07:04
That's true, but i think it should print errors instead of generate the executable.

**Comment by hitzhangjie** [comment] 2022-09-25 07:20
Good idea. 

Should the standard library or any package in go/src be considered a module?

**Comment by ryicoh** [comment] 2022-09-25 07:51
Yes, and should to throw the error that package name is duplicate.

**Comment by bcmills** [comment] 2022-09-26 14:09
Duplicate of #35270

**Closed by bcmills** 2022-09-26 14:09 UTC
