### ISSUE TITLE
runtime: can't recover

### ISSUE THREAD

**Issue by letian0805** [golang/go#50512] opened 2022-01-08 14:28 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
version go1.16

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```golang
package main

import (
    "fmt"
)

func main(){
    defer func() {
        test()
    }() 
    //defer test()  //if add this line, it will work
    panic("test")
}

func test() {
    if err := recover(); err != nil {
        fmt.Println(err)
    }   
}

```

### What did you expect to see?
recovered

### What did you see instead?
panic: test

goroutine 1 [running]:
main.main()
	/home/letian/work/go/src/test/test.go:11 +0x5b
exit status 2

**Comment by seankhliao** [comment] 2022-01-08 14:47
https://pkg.go.dev/builtin#recover
> Executing a call to recover inside a deferred function (but not any function called by it) stops the panicking sequence by restoring normal execution and retrieves the error value passed to the call of panic.

Closing as working as intended

**Closed by seankhliao** 2022-01-08 14:47 UTC

**Comment by letian0805** [comment] 2022-01-08 15:21
@seankhliao  I know how to use recover. Maybe I didn't express it very clearly. In fact, I'm more wondering why it's designed this way. Since the defer function will be executed no matter what, why must it be designed to require recovery in the top-level function of defer to recover from panic? Sometimes this design makes it look more like a bug.

**Comment by seankhliao** [comment] 2022-01-08 16:02
see the discussion in #34530

**Comment by letian0805** [comment] 2022-01-08 16:09
@seankhliao Thanks!
