### ISSUE TITLE
Simplify `panic(err)` grammer

### ISSUE THREAD

**Issue by baijifeilong** [golang/go#46565] opened 2021-06-04 09:54 UTC
Original code:

```go
package main

import (
	"fmt"
	"strconv"
)

func main() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Printf("PANIC: %v\n", err)
		}
	}()

	if num1, err := strconv.Atoi("111"); err != nil {
		panic(err)
	} else {
		fmt.Println(num1)
	}
	if num2, err := strconv.Atoi("zzz"); err != nil {
		panic(err)
	} else {
		fmt.Println(num2)
	}
	if num3, err := strconv.Atoi("333"); err != nil {
		panic(err)
	} else {
		fmt.Println(num3)
	}
}
```

Simplified code:

```go
package main

import (
	"fmt"
	"strconv"
)

func main() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Printf("PANIC: %v\n", err)
		}
	}()

	num1, ! := strconv.Atoi("111")
	fmt.Println(num1)
	num2, ! := strconv.Atoi("zzz")
	fmt.Println(num2)
	num3, ! := strconv.Atoi("333")
	fmt.Println(num3)
}
```

**Comment by seankhliao** [comment] 2021-06-04 11:09
Duplicate of #22122 and many others

**Closed by seankhliao** 2021-06-04 11:09 UTC
