### ISSUE TITLE
two package using flag but one works

### ISSUE THREAD

**Issue by Nothing-no** [golang/go#41519] opened 2020-09-21 09:17 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version 
go version go1.14.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
i have no try, but i can't find this issue on the Issues

### What operating system and processor architecture are you using (`go env`)?
set GO111MODULE=on
set GOARCH=amd64
...
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
...

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
i want to use two package with two different flag to meet my need, test as follows:
```go
package pk1

import (
	"flag"
	"fmt"
)

var pk1Flag = flag.String("pk1", "hello pk1", "test")

func init() {
	flag.Parse()
	fmt.Println(*pk1Flag)
}

```
```go
package pk2

import (
	"flag"
	"fmt"
)

var pk2Flag = flag.String("pk2", "hello pk2", "test")

func init() {
	flag.Parse()
	fmt.Println(*pk2Flag)
}

```
```go
package main

import (
	_ "flag/pk1"
	_ "flag/pk2"

	"fmt"
)

func main() {
	fmt.Println("main")
}
```
> * when i use: go run ./main.go or go run ./main.go -pk1=hhhhhh; both of them work well
> ```shell
>  go run .\main.go
> hello pk1
> hello pk2
> main
>
> go run .\main.go -pk1=hhhhhh
> hhhhhh
> hello pk2
> main
> ```
> * but when using: go run ./main.go -pk2=hhhh or go run ./main.go -pk1=p1 -pk2=p2; both of them do not work

### What did you expect to see?
```shell
hello pk1
hhhh
main

or

p1
p2
main
```

### What did you see instead?
```shell
flag provided but not defined: -pk2
Usage of ...\exe\main.exe:
  -pk1 string
        test (default "hello pk1")
exit status 2
```

**Comment by ALTree** [comment] 2020-09-21 09:24
Never call `flag.Parse` in `init( )` functions. As you just discovered, that doesn't work. See #33190. Closing here since this is not a bug.

**Closed by ALTree** 2020-09-21 09:24 UTC
