### ISSUE TITLE
cmd/go: lost build action: gccgo stdlib

### ISSUE THREAD

**Issue by bradfitz** [golang/go#32077] opened 2019-05-16 05:22 UTC
The Solaris builder started failing in cmd/go ...

https://build.golang.org/log/9981f2eb1b3856e4f3aadd3d11044635f4e3d7af

```
solaris-amd64-smartosbuildlet at 38431f1044880b936e35034ded19a6a8bc9faa21
...

ok  	cmd/fix	0.062s
go test proxy running at GOPROXY=http://127.0.0.1:55271/mod
go proxy: no archive rsc.io/x v0.1.0: file does not exist
--- FAIL: TestScript (0.00s)
    --- FAIL: TestScript/vendor_complex (17.51s)
        script_test.go:192: 
            # smoke test for complex build configuration (17.234s)
            > go build -o complex.exe complex
            > [exec:gccgo] go build -compiler=gccgo -o complex.exe complex
            [stderr]
            panic: lost build action: gccgo stdlib
            
            goroutine 1 [running]:
            cmd/go/internal/work.(*Builder).CompileAction(0xc00013ac80, 0x0, 0x0, 0xc000390f00, 0xc00039cb40)
            	/tmp/workdir/go/src/cmd/go/internal/work/action.go:418 +0x265
            cmd/go/internal/work.(*Builder).CompileAction.func1(0x97ab20)
            	/tmp/workdir/go/src/cmd/go/internal/work/action.go:383 +0x171
            cmd/go/internal/work.(*Builder).cacheAction(0xc00013ac80, 0xa1aa1d, 0x5, 0xc0001acf00, 0xc0001f5ae0, 0x43826b)
            	/tmp/workdir/go/src/cmd/go/internal/work/action.go:340 +0x9e
            cmd/go/internal/work.(*Builder).CompileAction(0xc00013ac80, 0x0, 0x0, 0xc0001acf00, 0xc0001f5b88)
            	/tmp/workdir/go/src/cmd/go/internal/work/action.go:373 +0xe8
            cmd/go/internal/work.(*Builder).LinkAction.func1(0x97ab20)
            	/tmp/workdir/go/src/cmd/go/internal/work/action.go:496 +0xb2
            cmd/go/internal/work.(*Builder).cacheAction(0xc00013ac80, 0xa1a551, 0x4, 0xc0001acf00, 0xc0001f5c50, 0x0)
            	/tmp/workdir/go/src/cmd/go/internal/work/action.go:340 +0x9e
            cmd/go/internal/work.(*Builder).LinkAction(0xc00013ac80, 0x1, 0x0, 0xc0001acf00, 0x0)
            	/tmp/workdir/go/src/cmd/go/internal/work/action.go:490 +0x85
            cmd/go/internal/work.(*Builder).AutoAction(0xc00013ac80, 0x1, 0x0, 0xc0001acf00, 0x0)
            	/tmp/workdir/go/src/cmd/go/internal/work/action.go:349 +0x9b
            cmd/go/internal/work.runBuild(0xe6f060, 0xc0000e8110, 0x1, 0x1)
            	/tmp/workdir/go/src/cmd/go/internal/work/build.go:386 +0x6c7
            main.main()
            	/tmp/workdir/go/src/cmd/go/main.go:188 +0x57f
            [exit status 2]
            FAIL: testdata/script/vendor_complex.txt:5: unexpected command failure
            
--- FAIL: TestIssue7573 (2.12s)
    go_test.go:3048: running testgo [build -n -compiler gccgo cgoref]
    go_test.go:3048: standard error:
    go_test.go:3048: panic: lost build action: gccgo stdlib
        
        goroutine 1 [running]:
        cmd/go/internal/work.(*Builder).CompileAction(0xc0001a6140, 0x0, 0x0, 0xc00024e500, 0x1)
        	/tmp/workdir/go/src/cmd/go/internal/work/action.go:418 +0x265
        cmd/go/internal/work.(*Builder).CompileAction.func1(0x97ab20)
        	/tmp/workdir/go/src/cmd/go/internal/work/action.go:383 +0x171
        cmd/go/internal/work.(*Builder).cacheAction(0xc0001a6140, 0xa1aa1d, 0x5, 0xc00024c000, 0xc0001c5ae0, 0x43826b)
        	/tmp/workdir/go/src/cmd/go/internal/work/action.go:340 +0x9e
        cmd/go/internal/work.(*Builder).CompileAction(0xc0001a6140, 0x0, 0x0, 0xc00024c000, 0xc0001c5b88)
        	/tmp/workdir/go/src/cmd/go/internal/work/action.go:373 +0xe8
        cmd/go/internal/work.(*Builder).LinkAction.func1(0x97ab20)
        	/tmp/workdir/go/src/cmd/go/internal/work/action.go:496 +0xb2
        cmd/go/internal/work.(*Builder).cacheAction(0xc0001a6140, 0xa1a551, 0x4, 0xc00024c000, 0xc0001c5c50, 0xe31e48)
        	/tmp/workdir/go/src/cmd/go/internal/work/action.go:340 +0x9e
        cmd/go/internal/work.(*Builder).LinkAction(0xc0001a6140, 0x1, 0x0, 0xc00024c000, 0xc00019c930)
        	/tmp/workdir/go/src/cmd/go/internal/work/action.go:490 +0x85
        cmd/go/internal/work.(*Builder).AutoAction(0xc0001a6140, 0x1, 0x0, 0xc00024c000, 0xb007a0)
        	/tmp/workdir/go/src/cmd/go/internal/work/action.go:349 +0x9b
        cmd/go/internal/work.runBuild(0xe6f060, 0xc0000da110, 0x1, 0x1)
        	/tmp/workdir/go/src/cmd/go/internal/work/build.go:386 +0x6c7
        main.main()
        	/tmp/workdir/go/src/cmd/go/main.go:188 +0x57f
        
    go_test.go:3048: go [build -n -compiler gccgo cgoref] failed unexpectedly in /tmp/workdir/go/src/cmd/go: exit status 2
FAIL
2019/05/15 17:13:35 unexpected files left in tmpdir: [go-build169977159]
FAIL	cmd/go	102.478s
```

**Comment by bcmills** [comment] 2019-05-16 10:59
Duplicate of #32060

**Closed by bcmills** 2019-05-16 10:59 UTC
Labels: NeedsInvestigation, OS-Solaris
