### ISSUE TITLE
cmd/compile: extra errors with goto to a not defined label, inside function

### ISSUE THREAD

**Issue by mlowicki** [golang/go#16689] opened 2016-08-14 11:09 UTC
1. What version of Go are you using (`go version`)?

```
go version go1.6.2 darwin/amd64
```

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mlowicki/projects/golang/hello"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?

https://play.golang.org/p/aX9ZT1kspY

4. What did you expect to see?

Error:
prog.go:4: label End not defined

so the same as with:
```
package main

func main() {
    goto End
}
```
which causes "label End not defined" error.

5. What did you see instead?

Two errors:
prog.go:4: label End not defined
prog.go:8: label End·1 not defined

**Comment by ALTree** [comment] 2016-08-14 12:03
Cannot reproduce with go1.7, looks fixed.

**Comment by odeke-em** [comment] 2016-08-18 09:38
I've traced back to 4fffd4569d321feeceb1daf73595155e049bc1c4 on Feb 29th 2016, as the CL that fixed it.

@randall77 could you confirm that this was what fixed this issue, so that we could close it since the issue is now fixed? Thanks.

**Comment by randall77** [comment] 2016-08-18 15:54
I don't know why that CL would have fixed it, it is a merge from master to dev.ssa, not the other way around.
I do agree this looks fixed.
@josharian might remember something about this.

**Closed by randall77** 2016-08-18 15:54 UTC
