### ISSUE TITLE
x/website: "Learn more" link on "Note: By default, the go command downloads" bubble points to wrong place

### ISSUE THREAD

**Issue by nico** [golang/go#43439] opened 2020-12-30 23:20 UTC
On https://golang.org/doc/install?download=go1.16beta1.darwin-arm64.pkg , there's a bubble reading

> Note: By default, the go command downloads and authenticates modules using the Go module mirror and Go checksum database run by Google. Learn more.

"Learn more." links to https://golang.org/dl which downloads again, instead of to a page where I can learn more.

**Comment by toothrot** [comment] 2021-01-05 19:51
https://golang.org/dl has a paragraph at the top of the page about how modules works, and some links to more details.

Visiting golang.org/dl should not trigger a download. I can't reproduce this issue, so I am closing. Please let me know if I am mistaken.

**Closed by toothrot** 2021-01-05 19:51 UTC
