### ISSUE TITLE
cmd/trace: reported goroutines doesn't associate with any goroutine information

### ISSUE THREAD

**Issue by hitzhangjie** [golang/go#54425] opened 2022-08-13 01:42 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
I didn't not try the latest version.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/zhangjie/Library/Caches/go-build"
GOENV="/Users/<username>/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/<username>/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/<username>/go"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4m/2_pn1sln1fzcg2zg_4mh95z80000gn/T/go-build852456570=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

go tool trace trace.out, then view the goroutine analysis, at last there's a N=<?>, 
it reports there's N goroutine created here, but it doesn't contains any goroutine information,missing entry function name.

![image](https://user-images.githubusercontent.com/3725760/184463701-ecd06d52-31cc-40fb-bf93-22962a05666c.png)

### What did you expect to see?

I want to know what does it mean, if detailed description is shown, it may be better understood.

### What did you see instead?

I see N=4 at last, it is not clear, it doesn't contains any function name info.

I read the code src/cmd/trace, it is caused by the GDesc.PC / GDesc.Name is zero value.
But I don't know why this occasion happend? At least here should add more description to let developers know what does it mean.

And, the problem is, not only the template cannot be rendered( the goroutine func entry missing), but also we cannot query these goroutines (missing the link /goroutine?id=0).

**Comment by seankhliao** [comment] 2022-08-13 10:28
Duplicate of #49994

**Closed by seankhliao** 2022-08-13 10:28 UTC
Labels: compiler/runtime
