### ISSUE TITLE
crypto/tls: TestServerHandshakeContextCancellation failures with "Unexpected server handshake error: EOF"

### ISSUE THREAD

**Issue by millerresearch** [golang/go#45299] opened 2021-03-30 10:49 UTC
The crypto/tls test TestServerHandshakeContextCancellation is flaky on plan9-arm, with errors like
```
--- FAIL: TestServerHandshakeContextCancellation (0.01s)
    handshake_server_test.go:1975: Unexpected server handshake error: EOF
    handshake_server_test.go:1985: Server connection was not closed when the context was canceled
FAIL
FAIL	crypto/tls	8.438s
```
Empirically I've found that inserting  a 50 millisecond delay between the `cli.writeRecord` call and the following `cancel` prevents the failure. This suggests there's a race with the server's `conn.HandshakeContext` call.

I don't know whether this is related to #45106 but it seems possible.

**Comment by millerresearch** [comment] 2021-03-30 11:06
Yes, it is related to #45106. I can make the TestClientHandshakeContextCancellation test fail repeatably on plan9-arm too, by runniing it with '-count 100'. There too, I can prevent the race by inserting a delay between the `conn.readClientHello` and the `cancel`.

**Comment by dr2chase** [comment] 2021-03-30 17:49
Would you call this a duplicate of #45106, or not?  Same root cause, isn't it?

**Comment by millerresearch** [comment] 2021-03-30 18:12
Yes, I would say it's the same flaw appearing in two different places.

**Comment by bcmills** [comment] 2021-04-15 17:26
FWIW, this has also reproduced on platforms other than `plan9`:

[2021-04-02T14:40:43-3651eff/freebsd-amd64-11_2](https://build.golang.org/log/065c5f1102ce4608478ce90b074f14c0d9727d11)
[2021-03-30T03:28:19-3394586/openbsd-amd64-68](https://build.golang.org/log/8af21346c8d1e224cad9142e5e33d576acd0014c)
[2021-03-24T21:20:10-179bcd7/darwin-amd64-10_12](https://build.golang.org/log/0aa942c31b687ac40370397564f585dd20940627)
[2020-12-14T20:56:03-dea6d94/linux-amd64-jessie](https://build.golang.org/log/fa30dd70be0d1fb26229d1dd9facb7b9d80342b2)
[2020-12-14T18:06:06-828746e/darwin-amd64-race](https://build.golang.org/log/3ba7af2a2263fb1dc583ac56d0b62bfce6221403)
[2020-11-12T21:21:18-60b1253/android-arm-corellium](https://build.golang.org/log/295c53ac4fd6c717626e96715273fdc3ffe11c27)
[2020-11-09T19:46:24-a2d0147/android-amd64-emu](https://build.golang.org/log/04451f2b35a85ce4fdceeb7eb3ff5a96dd83f1b2)

<details>
<summary><code>plan9</code></summary>

[2021-04-15T16:09:16-5631c4b/plan9-arm](https://build.golang.org/log/7a486c05e9d6b2f3f607c58aa9de8c1862fda194)
[2021-04-15T15:48:19-1d20a36/plan9-arm](https://build.golang.org/log/e10fcea6edca2af6cc122047de2d1025d2ca29d2)
[2021-04-15T10:21:10-b1c4cc5/plan9-arm](https://build.golang.org/log/7a2904b1a6be5a60c6ebbcfef21c05e48149ffd3)
[2021-04-15T09:18:03-61a08fc/plan9-arm](https://build.golang.org/log/072a56aed974bdbc95dd890afcd2da98fd5735a1)
[2021-04-15T08:44:21-0184b44/plan9-arm](https://build.golang.org/log/35b86132bd914a553f435a39f36b4ba75b093fc4)
[2021-04-14T21:58:06-c3931ab/plan9-arm](https://build.golang.org/log/f451f1e4c7ce58ee49acec2633367bf937bd6fbc)
[2021-04-14T19:57:35-1a8f0a7/plan9-arm](https://build.golang.org/log/6369cb5ddf3232ce75cff20dfc190a18ba9b12a5)
[2021-04-14T19:54:26-a89ace1/plan9-arm](https://build.golang.org/log/656e8c6fd3536808c7a6ea981677c53526e24b4a)
[2021-04-14T14:03:55-e9cc31e/plan9-arm](https://build.golang.org/log/ebeeb36c4f56d423f8c8d11dd22bb9cdf1beecf8)
[2021-04-14T03:14:51-728e3dc/plan9-arm](https://build.golang.org/log/41f82590f3a587123a3fad306a4851685c777041)
[2021-04-14T01:28:16-eb433ed/plan9-arm](https://build.golang.org/log/1b429f3f69fd3f66500018d11e28251c585714c6)
[2021-04-14T00:25:33-8dcc071/plan9-arm](https://build.golang.org/log/a9f89045248d388446f984ff1373c1191bdf8c9b)
[2021-04-13T22:55:30-8c2a8b1/plan9-arm](https://build.golang.org/log/bfc1012626964c56b8008fe71bf8e5a3cc0f4194)
[2021-04-13T22:31:20-b4881d9/plan9-arm](https://build.golang.org/log/3b6523b48d053c228b67c03a63b9ea68631614a4)
[2021-04-13T21:18:03-9913f82/plan9-arm](https://build.golang.org/log/09ebc13ae481df7cd75e9c71b352e9d70cfaca3c)
[2021-04-13T13:56:21-13a4e8c/plan9-arm](https://build.golang.org/log/363414b9eb26a49aab0fbf796a625c64f60356c4)
[2021-04-12T17:32:47-8b859be/plan9-arm](https://build.golang.org/log/41066c6edb8d789d179bffdabeb086f93f649dde)
[2021-04-12T17:28:43-5d80f8a/plan9-arm](https://build.golang.org/log/52cd32947217cad38e047e64a2fcba6e45141d62)
[2021-04-12T16:30:17-585b522/plan9-arm](https://build.golang.org/log/6890cee8a4c61a5aae790e8729dd66c479684e64)
[2021-04-12T02:29:32-7beb988/plan9-arm](https://build.golang.org/log/33f16f04dd37f35566e0d1f01ba8d823b695726c)
[2021-04-10T03:38:08-6382ec1/plan9-arm](https://build.golang.org/log/e6fe8ece1a040c7916b43281ba71d8c06d587343)
[2021-04-09T23:54:31-554d2c4/plan9-arm](https://build.golang.org/log/40b933768850d2924a26c7eddb73454480c9b12e)
[2021-04-09T19:11:12-756e2b1/plan9-arm](https://build.golang.org/log/f2103bfd020f5eca57a47b012ec383551759342f)
[2021-04-09T18:49:05-c3faff7/plan9-arm](https://build.golang.org/log/b71f62ada3fbe08f33d651145cda8d9089b6b081)
[2021-04-09T17:56:50-0ad4688/plan9-arm](https://build.golang.org/log/d990ff2c79fea1b28f8e7b266860344b242f961f)
[2021-04-09T14:36:20-77b3269/plan9-arm](https://build.golang.org/log/77e4073bed68a7ee70ed40e76f273213ddf9e75d)
[2021-04-09T00:09:47-19034fa/plan9-arm](https://build.golang.org/log/3e4ca42f6ea2e140554af3ccc30fca2c548fd9bb)
[2021-04-07T13:14:57-b55d900/plan9-arm](https://build.golang.org/log/50b2ab4fae01a0c9069b7bec9382d6002fb82db4)
[2021-04-06T20:22:15-f5efa5a/plan9-arm](https://build.golang.org/log/dbf8ac9b4d4e2f1a89e75361f7b8f968c99e897f)
[2021-04-06T18:01:39-55bac87/plan9-arm](https://build.golang.org/log/d551c328c6470380621b665914409d88798162d0)
[2021-04-05T22:43:42-d446cb7/plan9-arm](https://build.golang.org/log/dd31b0af109307be69d6b161cf57840524067c4b)
[2021-04-05T20:53:42-79b2e14/plan9-arm](https://build.golang.org/log/d0182c9d7c38a03e6ac856abd7175ce0f060be3f)
[2021-04-05T20:39:06-2701515/plan9-arm](https://build.golang.org/log/7fae93d2697711afc359946a9aa7ac2a519a412d)
[2021-04-05T17:42:13-9abedf4/plan9-arm](https://build.golang.org/log/8808cca4c24abbf30143184d4f56e332d4f3082b)
[2021-04-05T16:22:16-a06b08e/plan9-arm](https://build.golang.org/log/9a02d465ef34d970162e88211a896415b6515aec)
[2021-04-05T15:30:15-a4b8241/plan9-arm](https://build.golang.org/log/ad77a84209f018a3c1e6273eb2b76a834e15628a)
[2021-04-04T20:04:37-4230a6e/plan9-arm](https://build.golang.org/log/babb4175f5fc91acc6b463488b4babefaad5cabc)
[2021-04-03T21:06:18-9e7bc80/plan9-arm](https://build.golang.org/log/3d8e078c55b9b70b8ca91680003dfa3f5d99e848)
[2021-04-03T01:45:17-0182113/plan9-arm](https://build.golang.org/log/422ac4d61f73657368a1f12a9b922c7cf43b1b8f)
[2021-04-02T19:45:52-41cf18e/plan9-arm](https://build.golang.org/log/2e2e7accd68befc72ee994174ec8f7c7441715a2)
[2021-04-02T19:27:06-34b87b4/plan9-arm](https://build.golang.org/log/0d0af0a40d7d5a6d69715c18fdd4cc310a77a3d1)
[2021-04-02T12:44:37-a78b12a/plan9-arm](https://build.golang.org/log/122fe59e12bc241f362352f38e0dafcc8331cbb0)
[2021-04-02T05:24:14-aebc0b4/plan9-arm](https://build.golang.org/log/89ed62c1ec8e4ea9a14b4376ec90e85a8437060f)
[2021-04-01T22:35:25-27d3062/plan9-arm](https://build.golang.org/log/2873173608615d390fc36aa23e38ca27ae026206)
[2021-04-01T00:51:26-ec721d9/plan9-arm](https://build.golang.org/log/76dc3bf35f22b4d78a26cd0b1c5a34443247b029)
[2021-04-01T00:51:24-1f29e69/plan9-arm](https://build.golang.org/log/14e31eaa062cb49bdaf41b300604cdac73e8eb66)
[2021-04-01T00:51:23-3304b22/plan9-arm](https://build.golang.org/log/175d1e0076a249d5b63ff24f804ebead59398b30)
[2021-03-31T03:52:40-0e8a72b/plan9-arm](https://build.golang.org/log/9b782e594a53f602a8a89e7cca70bec18de09ef1)
[2021-03-31T00:52:58-6d2a557/plan9-arm](https://build.golang.org/log/7c9c84fe3ef2d35164f8d225dbdceebc63bedcaa)
[2021-03-31T00:52:26-f2717b3/plan9-arm](https://build.golang.org/log/c0d1cf9eeab11fd9edeb2f03f8ed5af3f5fcd8f2)
[2021-03-30T21:20:51-e0ce0af/plan9-arm](https://build.golang.org/log/92a2f0f55ce2dab44f82697718a6c17b43965b49)
[2021-03-30T15:43:47-e4a4161/plan9-arm](https://build.golang.org/log/162bca36a58ba3b8dbb49fdb28be50681ba39d03)
[2021-03-29T06:21:31-d10241f/plan9-arm](https://build.golang.org/log/fdf3a0bc38484496e78df686e8e491ca38f7acb5)
[2021-03-25T17:01:28-82a1e0f/plan9-arm](https://build.golang.org/log/f43b650403abc94b0eaee456d63d381dabebfabe)
[2021-03-25T14:42:40-53941b6/plan9-arm](https://build.golang.org/log/d21b7ecfd3e7b10470f3f4f6780228ccd7662722)
[2021-03-25T13:57:08-9f4d5c9/plan9-arm](https://build.golang.org/log/49873d877a6fe8509511f4f4ea942eea144b3c71)
[2021-03-25T04:21:29-dec3d00/plan9-arm](https://build.golang.org/log/3d034897800c24bd805d2c8afa49fa9c87063cf4)
[2021-03-25T03:19:56-4889afe/plan9-arm](https://build.golang.org/log/07187629460d714a25af279dc1308b8d4eab18e7)
[2021-03-24T21:20:10-179bcd7/plan9-arm](https://build.golang.org/log/84b6f4b7775b88e5e683b01a171ffe9362274c45)
[2021-03-24T16:26:07-6f62f85/plan9-arm](https://build.golang.org/log/c47a603baac59c5197b304df228d342927ca25c9)
[2021-03-24T14:52:14-975b097/plan9-arm](https://build.golang.org/log/626b0b03e183a172a954052aabc7dccc16fad03b)
[2021-03-24T14:20:32-747f426/plan9-arm](https://build.golang.org/log/185be5955bdf0a770b00469a7dc71edbc7bce069)
[2021-03-23T19:05:35-2887ef4/plan9-arm](https://build.golang.org/log/8a82294282e04503348d7ef32811f067f21462cd)
[2021-03-23T05:12:39-f4b9183/plan9-arm](https://build.golang.org/log/7a4ba8388611ab9ea8afb848d0432d18e51cc532)
[2021-03-23T04:23:52-0265b64/plan9-arm](https://build.golang.org/log/521938ec46c9b764a8d1b9d2590c87f91726fe7b)
[2021-03-23T03:49:17-b8371d4/plan9-arm](https://build.golang.org/log/3972c17d774f255d7c2a27b5f2d90da3353817ec)
[2021-03-23T01:36:23-b182ba7/plan9-arm](https://build.golang.org/log/cd183afe085390d5a43ccf3b61ec87247f8e5ee8)
[2021-03-19T17:31:59-4829031/plan9-arm](https://build.golang.org/log/c2aa4cf5d64bf37c911ae57e119d7f2212500b96)
[2021-03-19T14:27:48-196b104/plan9-arm](https://build.golang.org/log/b2d4512ba9fa7a3f1ef4b61fc2d55307b0972b63)
[2021-03-19T01:38:59-9136d95/plan9-arm](https://build.golang.org/log/90e5e919f6848126e5f01a9873545c7726af99db)
[2021-03-19T01:04:37-6704843/plan9-arm](https://build.golang.org/log/2cdc225b57516eb8e617613a64db914f10fec3a7)
[2021-03-18T22:18:32-90b1ed1/plan9-arm](https://build.golang.org/log/651e2e1f4c978574fdeb3a7554eb4af2fa49c7fb)
[2021-03-18T13:31:52-9de49ae/plan9-arm](https://build.golang.org/log/2958babed57a567adb8a2e95bbaa74f86d84ac05)
[2021-03-18T03:42:56-6517844/plan9-arm](https://build.golang.org/log/05ca5901f65a0180ec189a46292e5f0d6e5232b2)
[2021-03-18T01:46:58-f5e6d3e/plan9-arm](https://build.golang.org/log/3dd83382057c32b6b9e7858b45a493b38e2ff8dd)
[2021-03-18T00:23:25-51e4bb2/plan9-arm](https://build.golang.org/log/eaada4c9d9d23aff6a508eda416243b081f03258)
[2021-03-17T19:15:18-5423f60/plan9-arm](https://build.golang.org/log/41e6337f449251db53fc2c63f9570d98d6601afb)
[2021-03-17T17:50:50-8628bf9/plan9-arm](https://build.golang.org/log/33d24b2d03a20f96656592192df41945a3592b50)
[2021-03-17T16:53:00-70d54df/plan9-arm](https://build.golang.org/log/b8ee26850b8c08fb3990d2c31757f541933b7c5d)
[2021-03-17T00:18:28-63b0a0a/plan9-arm](https://build.golang.org/log/ba7980af77d56b35b25ecb1c62a6fe8caf6ab54a)
[2021-03-16T20:46:00-72d98df/plan9-arm](https://build.golang.org/log/f40a41d521edc36cf017e35915638cd31f4342d9)
[2020-12-09T01:34:53-ae9b442/plan9-arm](https://build.golang.org/log/2efff1642a758aad194bd057f649b487fe22c0fb)
[2020-12-07T17:29:52-9c0e2db/plan9-arm](https://build.golang.org/log/8aa4f75af26342eacced7ce59990e01967df6895)
[2020-12-07T07:59:54-c155931/plan9-arm](https://build.golang.org/log/e3cf2fea3913628639c28b0fa51db1c0fb1075ef)
[2020-12-04T08:49:16-b67b7dd/plan9-arm](https://build.golang.org/log/5bd2499cee621b93bca68c09fbe338028bb37175)
[2020-12-01T19:47:12-50b16f9/plan9-arm](https://build.golang.org/log/064ac1f4eccc3c22304caaaec501c37952eddbd2)
[2020-11-28T03:50:50-358d354/plan9-arm](https://build.golang.org/log/7d891a4416e15baefcaa72092bf9a43395c618e3)
[2020-11-24T00:50:11-762eda3/plan9-arm](https://build.golang.org/log/db57a10e35f0e7c6451b0b760bbfc1b335253cf9)
[2020-11-23T19:58:25-48a1a51/plan9-arm](https://build.golang.org/log/8d8c7e077706445eec4cd4fef8a22ac761ef21bf)
[2020-11-21T03:28:08-3f5a975/plan9-arm](https://build.golang.org/log/adf76677762aa01c1a1bc8f5be6d4a38a472a618)
[2020-11-13T23:26:54-4f63e0a/plan9-arm](https://build.golang.org/log/43313f6f6026b078bc1bfd6d7ed1b908f8658138)
[2020-11-10T18:42:47-8f2db14/plan9-arm](https://build.golang.org/log/e3272abeb11cccbb412033f83f7d718c99415303)
[2020-11-10T17:59:22-da3957a/plan9-arm](https://build.golang.org/log/e8f3d6d05c57dbdeba0b48877b8cd526421fbd41)

</details>

**Comment by bcmills** [comment] 2021-04-16 17:34
https://storage.googleapis.com/go-build-log/ad82d489/android-amd64-emu_75ed9332.log (a TryBot)

**Closed** 2021-04-16 19:24 UTC
Labels: NeedsInvestigation
