### ISSUE TITLE
cmd/go: TestScript/mod_pseudo_cache and TestScript/mod_invalid_version fail

### ISSUE THREAD

**Issue by cherrymui** [golang/go#54102] opened 2022-07-27 22:39 UTC
[2022-07-25T20:44:49-24dc27a/linux-amd64-longtest](https://build.golang.org/log/65eebf1d990d97aff0d2ab4871e41963b54b428e)
[2022-07-22T17:25:27-12e00f6/linux-amd64-longtest](https://build.golang.org/log/e4f29accad239f115ef81ba30c75b37eed77202b)
```
go test proxy running at GOPROXY=http://127.0.0.1:44511/mod
--- FAIL: TestScript (0.01s)
    --- FAIL: TestScript/mod_pseudo_cache (10.17s)
        script_test.go:259: 
            # Regression test for golang.org/issue/27171: after resolving an older
            # pseudo-version of a commit, future resolution of that commit by hash should
            # choose the highest appropriate pseudo-version instead of the cached one. (10.171s)
            > go mod download -json golang.org/x/text@v0.0.0-20171215141712-a1b916ed6726
            [stdout]
            {
            	"Path": "golang.org/x/text",
            	"Version": "v0.0.0-20171215141712-a1b916ed6726",
            	"Error": "golang.org/x/text@v0.0.0-20171215141712-a1b916ed6726: unrecognized import path \"golang.org/x/text\": reading https://golang.org/x/text?go-get=1: 500 Internal Server Error"
            }
            [exit status 1]
            FAIL: testdata/script/mod_pseudo_cache.txt:12: unexpected command failure
            
FAIL
FAIL	cmd/go	168.289s
```

Possibly network flakiness on go.googlesource.com ?
cc @bcmills

**Comment by bcmills** [comment] 2022-07-28 16:37
> [2022-07-25T20:44:49-24dc27a/linux-amd64-longtest](https://build.golang.org/log/65eebf1d990d97aff0d2ab4871e41963b54b428e)

That looks like a bug in the `go.googlesource.com` server; possibly another symptom of #52490?

> [2022-07-22T17:25:27-12e00f6/linux-amd64-longtest](https://build.golang.org/log/e4f29accad239f115ef81ba30c75b37eed77202b)

That exactly matches #52851.

**Comment by bcmills** [comment] 2022-07-28 16:37
(Closing as a semi-duplicate of the aforementioned issues.)

**Closed by bcmills** 2022-07-28 16:37 UTC
Labels: NeedsInvestigation, GoCommand
