### ISSUE TITLE
GoFmt make unnecessary white spaces for some statemeents

### ISSUE THREAD

**Issue by crazymi** [golang/go#35229] opened 2019-10-29 09:01 UTC
### What version of Go are you using (`go version`)?
go 1.13.2

### Does this issue reproduce with the latest release?
Yes. (for 1.13.2)

### What operating system and processor architecture are you using (`go env`)?
Note that, I test it in `Go Playground`.

GOOS=nacl
GOARCH=amd64p32

### What did you do?
`GoFmt` make unnecessary white spaces for some statements.

Check this playground for details: https://play.golang.org/p/qnaAwpXKPZ9
I press `Format` button in `Playground`.
```go
	// should not be formatted
	line = line[0:len(line)-1]
```

### What did you expect to see?
```go
	// should not be formatted
	line = line[0:len(line)-1]
```

### What did you see instead?
`GoFmt` change above line as
```
	// should not be formatted
	line = line[0 : len(line)-1]
```

**Comment by ALTree** [comment] 2019-10-29 09:09
> unnecessary white spaces

Well... almost any whitespace is technically "unnecessary"; indentation and spacing are included in source code just to make it more readable.

This is working as intended: goftm inserts spaces on the sides of `:` when the two expressions are composite. So it's `[a:b]`, but  `[a : b+1]`, to better visually group the `b+1` expression, and more clearly demarcate the two : sides.

Closing here, since this is working as intended.

**Closed by ALTree** 2019-10-29 09:09 UTC
