### ISSUE TITLE
x/crypto: build failure at Go master on linux/arm due to segmentation fault

### ISSUE THREAD

**Issue by toothrot** [golang/go#36458] opened 2020-01-08 16:27 UTC
https://build.golang.org/log/506cb75d52fac15580d8f9a4823bec308cfe661b

```
linux-arm at 77c13021dd401945711ff40f16a5040a075fcef9 building crypto at 53104e6ec876ad4e22ad27cce588b01392043c1b

testing in module mode; GOMOD=/workdir/gopath/src/golang.org/x/crypto/go.mod

:: Running /workdir/go/bin/go with args ["/workdir/go/bin/go" "test" "-short" "golang.org/x/crypto/..."] and env ["PATH=/workdir/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" "HOSTNAME=scaleway-prod-45" "GO_BUILDER_ENV=host-linux-arm-scaleway" "META_BUILDLET_BINARY_URL=https://storage.googleapis.com/go-builder-data/buildlet.linux-arm" "GO_BUILD_KEY_PATH=/buildkey/gobuildkey" "GO_BUILD_KEY_DELETE_AFTER_READ=true" "GOROOT_BOOTSTRAP=/workdir/go1.4" "HOME=/root" "USER=root" "GO_STAGE0_NET_DELAY=1.1s" "GO_STAGE0_DL_DELAY=1.2s" "WORKDIR=/workdir" "GO_BUILDER_NAME=linux-arm" "GO_BUILDER_FLAKY_NET=1" "GOROOT_BOOTSTRAP=/usr/local/go" "GOROOT=/workdir/go" "GOPATH=/workdir/gopath" "GOPROXY=http://10.240.0.245:30157" "GOPROXY=https://proxy.golang.org" "TMPDIR=/workdir/tmp" "GOCACHE=/workdir/gocache" "GOROOT_BOOTSTRAP=/usr/local/go"] in dir /workdir/gopath/src/golang.org/x/crypto

go: downloading golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
go: downloading golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: downloading golang.org/x/text v0.3.0
ok  	golang.org/x/crypto/acme	13.676s
ok  	golang.org/x/crypto/acme/autocert	31.477s
?   	golang.org/x/crypto/acme/autocert/internal/acmetest	[no test files]
?   	golang.org/x/crypto/acme/internal/acmeprobe	[no test files]
ok  	golang.org/x/crypto/argon2	1.624s
ok  	golang.org/x/crypto/bcrypt	1.991s
ok  	golang.org/x/crypto/blake2b	0.245s
ok  	golang.org/x/crypto/blake2s	0.208s
ok  	golang.org/x/crypto/blowfish	0.078s
ok  	golang.org/x/crypto/bn256	11.025s
ok  	golang.org/x/crypto/cast5	0.062s
ok  	golang.org/x/crypto/chacha20	0.151s
signal: segmentation fault (core dumped)
FAIL	golang.org/x/crypto/chacha20poly1305	1.715s
ok  	golang.org/x/crypto/cryptobyte	0.037s
?   	golang.org/x/crypto/cryptobyte/asn1	[no test files]
ok  	golang.org/x/crypto/curve25519	1.919s
ok  	golang.org/x/crypto/ed25519	1.877s
?   	golang.org/x/crypto/ed25519/internal/edwards25519	[no test files]
ok  	golang.org/x/crypto/hkdf	0.024s
ok  	golang.org/x/crypto/internal/subtle	0.056s
ok  	golang.org/x/crypto/internal/wycheproof	0.025s
?   	golang.org/x/crypto/internal/wycheproof/internal/dsa	[no test files]
?   	golang.org/x/crypto/internal/wycheproof/internal/ecdsa	[no test files]
ok  	golang.org/x/crypto/md4	0.023s
ok  	golang.org/x/crypto/nacl/auth	0.025s
ok  	golang.org/x/crypto/nacl/box	0.980s
ok  	golang.org/x/crypto/nacl/secretbox	0.029s
ok  	golang.org/x/crypto/nacl/sign	0.054s
ok  	golang.org/x/crypto/ocsp	0.890s
ok  	golang.org/x/crypto/openpgp	183.244s
ok  	golang.org/x/crypto/openpgp/armor	0.060s
ok  	golang.org/x/crypto/openpgp/clearsign	0.699s
ok  	golang.org/x/crypto/openpgp/elgamal	0.179s
?   	golang.org/x/crypto/openpgp/errors	[no test files]
ok  	golang.org/x/crypto/openpgp/packet	2.914s
ok  	golang.org/x/crypto/openpgp/s2k	83.384s
ok  	golang.org/x/crypto/otr	9.136s
ok  	golang.org/x/crypto/pbkdf2	0.352s
ok  	golang.org/x/crypto/pkcs12	0.341s
ok  	golang.org/x/crypto/pkcs12/internal/rc2	0.018s
ok  	golang.org/x/crypto/poly1305	0.075s
ok  	golang.org/x/crypto/ripemd160	0.278s
ok  	golang.org/x/crypto/salsa20	0.042s
ok  	golang.org/x/crypto/salsa20/salsa	0.018s
ok  	golang.org/x/crypto/scrypt	3.781s
ok  	golang.org/x/crypto/sha3	0.610s
ok  	golang.org/x/crypto/ssh	125.503s
ok  	golang.org/x/crypto/ssh/agent	13.184s
ok  	golang.org/x/crypto/ssh/knownhosts	0.035s
ok  	golang.org/x/crypto/ssh/terminal	0.034s
ok  	golang.org/x/crypto/ssh/test	0.904s
ok  	golang.org/x/crypto/tea	0.017s
ok  	golang.org/x/crypto/twofish	0.056s
ok  	golang.org/x/crypto/xtea	0.033s
ok  	golang.org/x/crypto/xts	0.018s
FAIL
```

/cc @katiehockman @FiloSottile

**Comment by FiloSottile** [comment] 2020-01-08 19:30
Duplicate of #35511

**Closed by FiloSottile** 2020-01-08 19:30 UTC
Labels: NeedsInvestigation
