### ISSUE TITLE
cmd/compile: build failed

### ISSUE THREAD

**Issue by cuiweixie** [golang/go#50660] opened 2022-01-17 18:55 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-897b3da2e0 Mon Jan 17 09:23:25 2022 +0000 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

no

### What did you do?

example1 :  
```package main

import (
	"fmt"
)


type I int64

func(i I) Do() int64 {
	return int64(i)
}

type Int interface {
	int32 | int64
}

type Doer[T Int] interface {
	Do() T
}

func Specialize[T Int](v Doer[T]) {
	switch v.(type) {
	case Doer[int32]:
		fmt.Println("int32!")
	case Doer[int64]:
		fmt.Println("int64!")
	}
}

func main() {
	var i Doer[int64]
	i = I(1)
	Specialize[int64](i)
}
```

example2:
```
package main

import (
	"fmt"
)


type I int64

func(i I) Do() int64 {
	return int64(i)
}

type Int interface {
	int32 | int64
}

type Doer[T Int] interface {
	Do() T
}

func Specialize[T Int](v Doer[T]) {
	switch v1 := v.(type) {
	case Doer[int32]:
		var v2 Doer[T]
		v2 = v1
		fmt.Println("int32!", v1)
	case Doer[int64]:
		fmt.Println("int64!")
	}
}

func main() {
	var i Doer[int64]
	i = I(1)
	Specialize[int64](i)
} 
```

### What did you expect to see?

example1:  
go run success!
example2:  
go run success!

### What did you see instead?
example1:  
go run success!
example2:  
```
# command-line-arguments
./main.go:26:8: cannot use v1 (variable of type Doer[int32]) as type Doer[T] in assignment:
        Doer[int32] does not implement Doer[T] (wrong type for Do method)
                have Do() int32 at ./main.go:19:2
                want Do() T
```

**Comment by cuiweixie** [comment] 2022-01-17 19:00
when i try to fix #50658 , i found this will failed to.

**Comment by ianlancetaylor** [comment] 2022-01-17 21:40
CC @griesemer @findleyr 

Probably the same problem as #50658.

**Comment by erifan** [comment] 2022-01-18 01:46
```
var v2 Doer[T]
v2 = v1
```

Should this be a "declared but not used" error ?

**Comment by ianlancetaylor** [comment] 2022-01-18 03:15
@erifan Yes, looks like it.  But that is a separate issue.

**Comment by erifan** [comment] 2022-01-18 03:23
@ianlancetaylor If we rule out this problem, then this issue and #50658 seem to be the same, then we can close this.

**Comment by ianlancetaylor** [comment] 2022-01-18 03:29
The error message here (`cannot use v1 (variable of type Doer[int32]) as type Doer[T] in assignment`) is not the same as the error message in #50658 (`impossible type assertion`).  I would not be surprised if they are the same underlying problem, but let's verify that before we close this issue.  Thanks.

**Comment by cuiweixie** [comment] 2022-01-18 05:43
run example1 success. 
according to #50658 , example1 will failed.
#50658 failed in https://github.com/golang/go/blob/31496cfde50a490639ce0723f75de0f16a8291dd/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/ifaceassert/ifaceassert.go#L98 that cause by go vet.
but this issue failed in  cmd/compile.

**Comment by findleyr** [comment] 2022-01-19 23:35
This is a different issue from #50658. In the line `v2 = v1`, `v2` is a `Doer[T]`, and `v1` is a `Doer[int32]`. The type checker does not infer that `T` must be an `int32` inside this case.

I don't think this is valid code with the current spec. Shouldn't it be:
```
	case Doer[int32]:
		var v2 Doer[int32]
		v2 = v1
		fmt.Println("int32!", v1)
```
?

**Comment by ianlancetaylor** [comment] 2022-01-20 00:11
Ah, you're right.  Sorry for misunderstanding.  This is not a bug.

**Closed by ianlancetaylor** 2022-01-20 00:11 UTC
Labels: NeedsInvestigation, release-blocker

**Comment by erifan** [comment] 2022-01-20 02:40
> The type checker does not infer that `T` must be an `int32` inside this case.
> 
Although this is not valid code according to the current spec, but it is clear that the value of T can be inferred under this case statement. So I think it might be more convenient if we make this code valid. Maybe not comparable, but the interface can do it, see https://go.dev/play/p/KqfF-6ElUnR

**Comment by findleyr** [comment] 2022-01-20 02:59
> it is clear that the value of T can be inferred under this case statement.

While it may be obvious in this case, I think if we were to write down a specification for this feature we'd find that there are many less obvious corner cases, and the resulting behavior may be surprising to users (in short, we'd have to do some sort of unification with types in type lists for type switch cases).  My intuition is that it is better to just do the substitution explicitly where necessary, as in writing out `var v2 Doer[int32]` here.
