### ISSUE TITLE
x/tools/go/loader: program with nested interfaces works in Go but not with the loader

### ISSUE THREAD

**Issue by matthewmueller** [golang/go#22866] opened 2017-11-24 06:17 UTC
This took me awhile to boil down, but the link below is the smallest possible program that illustrates this bug. The program models the DOM, which has lots of interconnected interfaces. 

The weird part is that it works with `go run`, so it seems there must be some case missing in the loader. 

I noticed some other open issues around cgo and vendoring – this program doesn't use cgo or vendoring, it's just Go code with some interfaces.

Runnable example: https://github.com/matthewmueller/deep-interface-bug

Thanks in advance for your help!

---

**UPDATE:** I tried to make a callgraph visualization to help illustrate the problem better, but it uses the loader, which can't compile this program 😅 

---

### What version of Go are you using (`go version`)?

`go version go1.9 darwin/amd64`

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

```
GOOS="darwin"
GOARCH="amd64"
```

### What did you do?

Runnable example at: https://github.com/matthewmueller/deep-interface-bug

### What did you expect to see?

A loaded program

### What did you see instead?

> invalid operation: html (variable of type github.com/matthewmueller/deep-interface-bug/window.HTMLElement) has no field or method DispatchEvent

**Comment by matthewmueller** [comment] 2017-12-04 09:00
FWIW, here's the file that doesn't work:

**window.go**

```go
package window

// EventTarget interface
type EventTarget interface {
	DispatchEvent() Event
}

// Node interface
type Node interface {
	EventTarget

	ParentElement() HTMLElement
}

// Element interface
type Element interface {
	Node
}

// HTMLElement interface
type HTMLElement interface {
	Element
}

// Event interface
type Event interface {
	SrcElement() Element
}
```

**input.go**

```go
```

**Comment by ianlancetaylor** [comment] 2017-12-05 20:45
This is probably a dup of #18395.

CC @griesemer

**Comment by griesemer** [comment] 2017-12-05 21:00
@matthewmueller Could you please run your code using the latest (tip) version of go/types and report back if you see the same error? If it is indeed a duplicate of #18395 go/types will now complain with a respective error.

**Comment by griesemer** [comment] 2017-12-05 21:15
@matthewmueller I just confirmed myself that this is indeed a duplicate of #18395. A fix is in the works, but unfortunately it's too late to get that into Go 1.10. For:
```
package p

// EventTarget interface
type EventTarget interface {
	DispatchEvent() Event
}

// Node interface
type Node interface {
	EventTarget

	ParentElement() HTMLElement
}

// Element interface
type Element interface {
	Node
}

// HTMLElement interface
type HTMLElement interface {
	Element
}

// Event interface
type Event interface {
	SrcElement() Element
}

var _ = HTMLElement.DispatchEvent
```
gotype reports:
```
$ gotype x.go
x.go:22:2: internal error: incomplete embedded interface Element (issue #18395)
x.go:30:9: invalid operation: HTMLElement (type) has no field or method DispatchEvent
```
As a temporary work-around in this case you could manually inline the methods that the Element interface embeds via the Node type. This is always possible to do manually, and in fact the fix for go/types is to just do this automatically. But it's a larger fix which is why it's not going to make it anymore this round. Sorry.

Closing as duplicate of #18395.

**Closed by griesemer** 2017-12-05 21:15 UTC
Labels: WaitingForInfo

**Comment by matthewmueller** [comment] 2017-12-06 04:53
Thanks for the response and workaround!

@griesemer I'll definitely give this a shot. It will definitely blow up the file sizes a lot because the DOM interface are huge – hopefully that doesn't slow down the compiler.

**Comment by griesemer** [comment] 2017-12-06 06:05
@matthewmueller Inlining all methods manually will always work but you may not have to go to that extreme to avoid the issue. You may be able to factor our a significant subset of the methods into a new interface that you then can embed.

Again, a fix is in the works ( https://go-review.googlesource.com/c/go/+/79575 ) and you could try the patch, but it's not the final version quite yet.

**Comment by matthewmueller** [comment] 2017-12-15 14:19
Thanks for the comments, I'm not sure factoring out by hand is an option because the DOM APIs are pretty massive and I'm not idea where all the cycles lie.

> Again, a fix is in the works ( https://go-review.googlesource.com/c/go/+/79575 ) and you could try the patch, but it's not the final version quite yet.

Would this require a fork to Go itself or could I bring this in as a library?

**Comment by griesemer** [comment] 2017-12-15 16:56
@matthewmueller You can just apply that patch (  https://go-review.googlesource.com/c/go/+/79575 ) to go/types (it's only affecting go/types) and use the updated library.

DOM implementation: Sure, let us know how to get it.
