### ISSUE TITLE
Compiler: I compiled it using "-s -w" build flag. but information still present in the binary

### ISSUE THREAD

**Issue by kusattapan1** [golang/go#51826] opened 2022-03-20 09:21 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kusattapan/.cache/go-build"
GOENV="/home/kusattapan/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/kusattapan/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/kusattapan/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/kusattapan"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build411400481=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you expect to see?
Only machine code, like c.
I don't like to include my information in the binary. 

### What did you see instead?
I passed build flag "-s -w" to compile it.  However all my sensitive informations (All function names Variable names Package names my pc username C:\Users\xxx) are present in the binary.

**Comment by seankhliao** [comment] 2022-03-20 09:34
Without it you wouldn't have things like reflect or stacktraces
see also #50501

closing as working as intended

**Closed by seankhliao** 2022-03-20 09:34 UTC

**Comment by kusattapan1** [comment] 2022-03-20 09:35
ok thank you.

**Comment by go101** [comment] 2022-03-20 16:04
reflect doesn't need such info.

@kusattapan1 Have you tired `-trimpath`?

**Comment by kusattapan1** [comment] 2022-03-20 19:27
v2 beta

I didn't know there was such function!

> reflect doesn't need and stacktraces doesn't require such info.
> 
> @kusattapan1 Have you tired `-trimpath`?

I didn't know there was such function! thank you. Apart from pc name function names and variable names are still present in my binary. Is there any way to remove it?

**Comment by go101** [comment] 2022-03-21 00:01
There is a project for this: https://github.com/burrowers/garble
I never tried it.

**Comment by kusattapan1** [comment] 2022-03-21 15:29
> There is a project for this: https://github.com/burrowers/garble I never tried it.

It worked for me. thank you! wish native golang had such a feature...
