### ISSUE TITLE
go test ./... -v  No output

### ISSUE THREAD

**Issue by summer-boythink** [golang/go#69220] opened 2024-09-03 02:42 UTC
### Go version

go version go1.23.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/snap/go/10698'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/snap/go/10698/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.0'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/root/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/root/go_code/goleveldb/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1971124972=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

go test ./... -v

### What did you see happen?

When I was testing [goleveldb](https://github.com/syndtr/goleveldb.git), I used `cd leveldb` first, then allowed `go test . -v` the console would output the text of the test, but I used `go test ./... -v` , the test text will not appear immediately, only when I use `ctrl+c`, the test text will appear immediately

### What did you expect to see?

`go test ./... -v` will also output in the console

**Comment by seankhliao** [comment] 2024-09-03 05:54
Duplicate of #46959

**Closed by seankhliao** 2024-09-03 05:54 UTC
