### ISSUE TITLE
x/pkgsite: direct links with fragments broken on Safari

### ISSUE THREAD

**Issue by peterbourgon** [golang/go#45350] opened 2021-04-02 00:38 UTC
### What is the URL of the page with the issue?

Any URL to any package docs that includes a link to a specific item via a fragment. [Here is an example](https://pkg.go.dev/github.com/carlmjohnson/flagext#ParseEnv).
 
 ### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15 
 
### Screenshot

Here is what happens in Chrome, which is correct:
 
![chrome](https://user-images.githubusercontent.com/114509/113367483-61ae0180-935c-11eb-933c-4567b245fe17.png)

Here is what happens in Safari, which is not:

![safari](https://user-images.githubusercontent.com/114509/113367507-6e325a00-935c-11eb-9616-2b1dec3d0da0.png)

**Comment by jamalc** [comment] 2021-04-02 15:23
Duplicate of #43999

**Closed by jamalc** 2021-04-02 15:24 UTC
Labels: pkgsite
