### ISSUE TITLE
x/pkgsite: example for errors.As prints full source code of errors/example_test.go

### ISSUE THREAD

**Issue by masiulaniec** [golang/go#39006] opened 2020-05-11 17:22 UTC
When expanding the example https://pkg.go.dev/errors?tab=doc#example-As I see the text:

```
package errors_test

import (
	"errors"
	"fmt"
	"os"
	"reflect"
	"testing"
)

func TestIs(t *testing.T) {
	err1 := errors.New("1")
	erra := wrapped{"wrap 2", err1}
	errb := wrapped{"wrap 3", erra}
...
```

instead of the expected:

```
if _, err := os.Open("non-existing"); err != nil {
	var pathError *os.PathError
	if errors.As(err, &pathError) {
		fmt.Println("Failed at path:", pathError.Path)
	} else {
		fmt.Println(err)
	}
}
```

**Comment by D1CED** [comment] 2020-05-11 18:14
It's likely a duplicate of 38409.
Backport is on the way.

**Closed** 2020-06-22 13:29 UTC
Labels: NeedsFix, go.dev
