### ISSUE TITLE
cmd/go: running gcc failed when compiling to Android

### ISSUE THREAD

**Issue by hajsf** [golang/go#40993] opened 2020-08-23 14:58 UTC
I tried to solve [40988#](https://github.com/golang/go/issues/40988) by compiling the file at Ubuntu WSL, Ubuntu inside Windows 10.

I got go installed and running:
```bash
$ go version
go version go1.15 linux/amd64
```
I got gcc installed and running
![image](https://user-images.githubusercontent.com/46838626/90981474-e4bade00-e569-11ea-8fd4-4be52f1adb1b.png)

While compiling the same code, I got the below error:
```bash
output:

# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-178415548/go.o:(.data+0x0): undefined reference to `x_cgo_callers'
/tmp/go-link-178415548/go.o:(.data+0x8): undefined reference to `x_cgo_init'
/tmp/go-link-178415548/go.o:(.data+0x10): undefined reference to `x_cgo_mmap'
/tmp/go-link-178415548/go.o:(.data+0x18): undefined reference to `x_cgo_munmap'
/tmp/go-link-178415548/go.o:(.data+0x20): undefined reference to `x_cgo_notify_runtime_init_done'
/tmp/go-link-178415548/go.o:(.data+0x28): undefined reference to `x_cgo_sigaction'
/tmp/go-link-178415548/go.o:(.data+0x30): undefined reference to `x_cgo_thread_start'
/tmp/go-link-178415548/go.o:(.data+0x38): undefined reference to `x_cgo_setenv'
/tmp/go-link-178415548/go.o:(.data+0x40): undefined reference to `x_cgo_unsetenv'
/tmp/go-link-178415548/go.o:(.data+0x48): undefined reference to `_cgo_yield'
collect2: error: ld returned 1 exit status
```
![image](https://user-images.githubusercontent.com/46838626/90981520-37949580-e56a-11ea-9344-0cc2e9fb0fce.png)

**Comment by ianlancetaylor** [comment] 2020-08-23 18:07
Please show us text as plain text, not as an image.  Thanks.

First, you need to set `CGO_ENABLED=1`.  But that won't be enough: in order to cross-compile a Go program that uses C code, you need to have a C cross-compiler.  Go cross-compiles automatically, but C does not.

Closing because this is not a bug.  We don't use the issue tracker for questions.  You will get better and faster help using a forum.  Please see https://golang.org/wiki/Questions.  Thanks.

**Closed by ianlancetaylor** 2020-08-23 18:07 UTC
