### ISSUE TITLE
problem with golang recursive performance

### ISSUE THREAD

**Issue by pennkao** [golang/go#27076] opened 2018-08-19 03:40 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.10

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you see instead?
go:
package main
func fib(n int64) int64 {
	if n <= 2 {
		return 1
	}
	return fib(n-1) + fib(n-2)
}
func main() {
	println(fib(45))
}
java:
public class Bench1 {
	static long fib(long n) {
		return n <= 2 ? 1 : fib(n - 1) + fib(n - 2);
	}
	public static void main(String[] args) {
		System.out.println(fib(45));
	}
}

java:3.1s
go:5.2s

**Comment by davecheney** [comment] 2018-08-19 03:46
Can you please provide some instructions for how to build both examples and how to reproduce your benchmarks. Thank you.

**Comment by ianlancetaylor** [comment] 2018-08-19 04:09
Your program calls `fib` 2,269,806,339 times.  I don't think you are measuring a problem with recursive calls, I think you are measuring the effectiveness of the JIT of the JVM you are using.  Looking at it another way, Go function calls do have a certain overhead, because of the use of growable stacks.  Java function calls, after using a JIT, do not need to have that overhead.

I'm going to close this issue because I don't think there is anything we can do here.  If you have specific suggestions about places where Go's code generation could be improved, please let us know.  Examples like this don't help us make anything better.

**Closed by ianlancetaylor** 2018-08-19 04:09 UTC
Labels: WaitingForInfo
