### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by bliugithub** [golang/go#54493] opened 2022-08-17 05:18 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?

in golang.google.cn home page 
try Go code  output wrong PI   3.1413926535917907  /  the rignt is 3.141 5926 5358 9793 2384 6264 3

// Concurrent computation of pi.
// See https://goo.gl/la6Kli.
//
// This demonstrates Go's ability to handle
// large numbers of concurrent processes.
// It is an unreasonable way to calculate pi.
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(pi(5000))
}

// pi launches n goroutines to compute an
// approximation of pi.
func pi(n int) float64 {
	ch := make(chan float64)
	for k := 0; k < n; k++ {
		go term(ch, float64(k))
	}
	f := 0.0
	for k := 0; k < n; k++ {
		f += <-ch
	}
	return f
}

func term(ch chan float64, k float64) {
	ch <- 4 * math.Pow(-1, k) / (2*k + 1)
}

**Comment by ZekeLu** [comment] 2022-08-17 05:21
duplicate of #53598

**Comment by seankhliao** [comment] 2022-08-17 07:31
Duplicate of #53598

**Closed by seankhliao** 2022-08-17 07:31 UTC
