### ISSUE TITLE
x/website: Incorrect tar instructions for Linux download

### ISSUE THREAD

**Issue by jgeiger-trane** [golang/go#41528] opened 2020-09-21 14:57 UTC
It seems that the code to generate the CLI for the file that was downloaded is wrong and using a possibly hard coded version number.

When a user downloads the file, the instructions should return the instructions to install/unpack the file.

### What did you do?

Downloaded Go 1.15.2

https://golang.org/doc/install?download=go1.15.2.linux-amd64.tar.gz

### What did you expect to see?

tar -C /usr/local -xzf go1.15.2.linux-amd64.tar.gz

### What did you see instead?

tar -C /usr/local -xzf go1.14.3.linux-amd64.tar.gz

![image](https://user-images.githubusercontent.com/71138684/93782681-174b0b80-fbe8-11ea-8e96-f6bb783f4e18.png)

**Comment by AlexRouSg** [comment] 2020-09-21 16:00
Already fixed (but looks like not deployed) in #41232

**Comment by ipriver** [comment] 2020-09-21 16:31
I'm not sure how CI/CD works for different regions for the website, but the next day my fix got approved-merged it has been deployed and I've seen it working. 
Currently, everything is ok for me in chrome/firefox/safari. Just in case, have you tried clearing the cache in your browser?

**Comment by ipriver** [comment] 2020-09-21 16:51
NVM, looks like your issue is valid and it's not because of the deployment. 
Previously I used Win/macOS for the development and missed it. Now I was able to reproduce it on my Linux VM and it looks like the script is not executed when the page loads the Linux tab.
Gonna work on that, thanks @jgeiger-trane

**Comment by ipriver** [comment] 2020-09-21 19:46
Created an issue golang/go#41537 which is the reason why Linux instructions aren't updating.
And created a PR that should solve it.

**Comment by dmitshur** [comment] 2020-09-22 15:40
Thanks for looking into this @ipriver. The underlying problem is a problem in the OS detection code.

Let's close this as duplicate of #41232, and use #41537 to track this issue.

**Closed by dmitshur** 2020-09-22 15:40 UTC
Labels: NeedsFix
