### ISSUE TITLE
encoding/gob: does not overwrite zero values of structures

### ISSUE THREAD

**Issue by afunix** [golang/go#22862] opened 2017-11-24 01:00 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/cqx874/projects/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/84/h3xfrt592ss8j1199p0sg4bc0000gn/T/go-build983167319=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
I have a stream generated by `GobEncoder` which is being read in a cycle by `GobDecoder`.

Documentation states:
```
        // GobDecode overwrites the receiver, which must be a pointer,
        // with the value represented by the byte slice, which was written
        // by GobEncode, usually for the same concrete type.
```

However if any field in the structure being received is zero, it won't be populated by `GobDecorer.Decode()`.

Example: https://play.golang.org/p/ifu1Bj2j_v

### What did you expect to see?
decoded: {10}
decoded: {0}
decoded: {20}

### What did you see instead?
decoded: {10}
decoded: {10}
decoded: {20}

**Comment by robpike** [comment] 2017-11-24 02:14
Working as intended. Duplicate of #21929

**Closed by robpike** 2017-11-24 02:14 UTC
Labels: NeedsInvestigation

**Comment by afunix** [comment] 2017-11-24 12:35
Can you please at least update documentation, so this design is more obvious?
I spent 3 hours reading through encoding/gob code and binary data it generates to find out this behaviour.
