### ISSUE TITLE
Cant get modules :  x509: failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by HijenHEK** [golang/go#54030] opened 2022-07-24 19:03 UTC
### Reproduce example 

<pre>
go get -u github.com/gin-gonic/gin     
</pre>

### output

<pre>
go: module github.com/gin-gonic/gin: Get "https://proxy.golang.org/github.com/gin-gonic/gin/@v/list": x509: failed to load system roots and no roots provided; readdirent /dev/null: not a directory
</pre>

### version of go

<pre>
$ go version
go1.18.4 linux/amd64
</pre>

### OS

<pre>
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
</pre>

### operating system and processor architecture

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="~/.cache/go-build"
GOENV="~/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="~/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="~/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="~/Documents/dev/go/go-drive/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3397368680=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by seankhliao** [comment] 2022-07-24 19:22
full output of `env` on your system please

**Comment by HijenHEK** [comment] 2022-07-24 20:20
> full output of `env` on your system please
@seankhliao  it's there, hit the triangle ,
Thanks for the reply

**Comment by seankhliao** [comment] 2022-07-24 20:48
The `env` command, not `go env`

**Comment by HijenHEK** [comment] 2022-07-24 20:50
sorry mate i got it ,

<details><summary><code>env</code> Output</summary><br><pre>
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
LC_TIME=ar_TN.UTF-8
USER=user
XDG_SESSION_TYPE=wayland
SHLVL=1
HOME=/home/user
DESKTOP_SESSION=ubuntu
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/hyper.desktop
GTK_MODULES=gail:atk-bridge
GNOME_SHELL_SESSION_MODE=ubuntu
LC_MONETARY=ar_TN.UTF-8
SSL_CERT_FILE=[path-to-certificate-file]
MANAGERPID=75185
SYSTEMD_EXEC_PID=75339
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
GIO_LAUNCHED_DESKTOP_FILE_PID=76805
IM_CONFIG_PHASE=1
WAYLAND_DISPLAY=wayland-0
LOGNAME=user
_=/usr/bin/env
JOURNAL_STREAM=8:37638
XDG_SESSION_CLASS=user
USERNAME=user
DOTNET_ROOT=/snap/dotnet-sdk/current
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
PATH=/usr/local/go/bin:/home/user/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/user/.dotnet/:/usr/lib/python2.7:/usr/lib/python2.7
SESSION_MANAGER=local/len:@/tmp/.ICE-unix/78318,unix/len:/tmp/.ICE-unix/78318
INVOCATION_ID=87a0fx622e21416e9b390441dda2c401
LC_ADDRESS=ar_TN.UTF-8
XDG_RUNTIME_DIR=/run/user/1000
XDG_MENU_PREFIX=gnome-
GNOME_SETUP_DISPLAY=:1
SSL_CERT_DIR=/dev/null
DISPLAY=:0
LC_TELEPHONE=ar_TN.UTF-8
XDG_CURRENT_DESKTOP=Unity
XDG_SESSION_DESKTOP=ubuntu
XMODIFIERS=@im=ibus
XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.M8FPP1
SSH_AGENT_LAUNCHER=gnome-keyring
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
LC_NAME=ar_TN.UTF-8
SHELL=/bin/bash
QT_ACCESSIBILITY=1
GDMSESSION=ubuntu
LC_MEASUREMENT=ar_TN.UTF-8
LC_IDENTIFICATION=ar_TN.UTF-8
GJS_DEBUG_OUTPUT=stderr
QT_IM_MODULE=ibus
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
LC_NUMERIC=ar_TN.UTF-8
LC_PAPER=ar_TN.UTF-8
CHROME_DESKTOP=Hyper.desktop
ORIGINAL_XDG_CURRENT_DESKTOP=ubuntu:GNOME
GDK_BACKEND=x11
TERM=xterm-256color
COLORTERM=truecolor
TERM_PROGRAM=Hyper
TERM_PROGRAM_VERSION=3.2.3
OLDPWD=/home/user/Documents/dev/main
STARSHIP_SHELL=zsh
STARSHIP_SESSION_KEY=2324926439538188
LANG=en_US.UTF-8
</pre></details>

**Comment by seankhliao** [comment] 2022-07-24 20:52
Go will read certificates from the environment if specified.

```
SSL_CERT_DIR=/dev/null
```

Closing as working as intended.

**Closed by seankhliao** 2022-07-24 20:52 UTC
