### ISSUE TITLE
net/http, x/net/http2: client loses the request body when retrying after HTTP2 server close connection gracefully(GOAWAY)

### ISSUE THREAD

**Issue by answer1991** [golang/go#39086] opened 2020-05-15 03:34 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
YES, I run the reproduce code in golang docker container with latest image(golang:1.14.2-buster), still occur this bug.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/Joe/Library/Caches/go-build"
GOENV="/Users/Joe/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/Joe/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/Joe/go/src/golang.org/x/net/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vk/bngnkbgj09v1cn56dsbrvs540000gn/T/go-build201607743=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. Set up a HTTP2 server with a handler which will send GOAWAY frame
2. Use a HTTP client to request HTTP2 server in multi goroutine in concurrency
3. HTTP client may got a 500 HTTP response code with error `request declared a Content-Length of N but only wrote 0 bytes`

Example codes in Go Playground: https://play.golang.org/p/8eiVRYqRyc6

### Already known after I debug

1. [HTTP2 RoundTrip](https://github.com/golang/net/blob/master/http2/transport.go#L434) received the request which body has no content, after I re-set req.body = `req.GetBody()` in HTTP2 RoundTrip, the bug will not occur again. codes like:
```go
// RoundTripOpt is like RoundTrip, but takes options.
func (t *Transport) RoundTripOpt(req *http.Request, opt RoundTripOpt) (*http.Response, error) {
	if !(req.URL.Scheme == "https" || (req.URL.Scheme == "http" && t.AllowHTTP)) {
		return nil, errors.New("http2: unsupported scheme")
	}

	if req.GetBody != nil {
		var ierr error
		req.Body, ierr = req.GetBody()
		if ierr != nil {
			return nil, ierr
		}
	}
```

2. Based 1., the higher RoundTrip(golang net/http RoundTrip) lost request body when retry, BUT I found the the RoundTrip has re-wind body when re-try:
https://github.com/golang/go/blob/881d5405402d6e8c54f83eed6216a9ed29778006/src/net/http/transport.go#L586-L596

### What did you expect to see?

HTTP client should not got error after received GOAWAY when re-try the request

**Comment by answer1991** [comment] 2020-05-15 03:36
cc @bradfitz 

Need your help, I had already debug with many days but did not found the root cause.

**Comment by lavalamp** [comment] 2020-05-15 19:11
I ran the reproducer locally and reproduced it.

**Comment by fraenkel** [comment] 2020-05-16 13:07
I haven't found where the issue is but I do know we are reusing a req.Body on the http2 transport side. What I have determined is that we read the data once and then we reuse the body which has no more data.

**Comment by answer1991** [comment] 2020-05-16 17:20
> we are reusing a req.Body on the http2 transport side

I found http2 transport entrypoint get the request which has no data, and base that I think we are reusing a req.Body on http transport but not http2 transport.  I test with adding the following codes in [http2 transport entrypoint](https://github.com/golang/net/blob/master/http2/transport.go#L434) and got panic:

```go
// RoundTripOpt is like RoundTrip, but takes options.
func (t *Transport) RoundTripOpt(req *http.Request, opt RoundTripOpt) (*http.Response, error) {
	if !(req.URL.Scheme == "https" || (req.URL.Scheme == "http" && t.AllowHTTP)) {
		return nil, errors.New("http2: unsupported scheme")
	}

	// check request body has data, panic if it's no data
	if req.Body != nil || req.GetBody != nil {
		body, err := ioutil.ReadAll(req.Body)
		if err != nil {
			return nil, err
		}

		if len(body) == 0 {
			panic("http2 roundtrip get a requst which body has no data")
		}

		var ierr error
		req.Body, ierr = req.GetBody()
		if ierr != nil {
			return nil, ierr
		}
	}
```

**Comment by fraenkel** [comment] 2020-05-17 03:22
I found the issue and I have a solution but I need to better understand the flow.
The failure occurs in the http transport when the altRT.RoundTrip is taken. Later on a second RoundTrip occurs, but a new request & body wasn't created.

**Comment by fraenkel** [comment] 2020-05-17 12:36
Took a bit of time but I figured out the problem.
An http2 request is attempted via altRT.RoundTrip. The first attempt writes the body but fails because the connection gets a GOAWAY. The http2 side retries but gets a no cached connection error which bubbles up as a ErrSkipAltProtocol.
The http side takes over and tries again but this time the body is already read.

Given we never reset the body in the existing request, I am not certain how to solve this other than no returning the ErrSkipAltProtocol if we have already written the body.

**Comment by bradfitz** [comment] 2020-05-17 16:58
(There was work in this area recently in ea1437a8cdf6bb3c2d2447833a5d06dbd75f7ae4 for #34978 and #35113 but I haven't read this bug or those ones enough to know whether they're related.)

**Comment by fraenkel** [comment] 2020-05-17 17:50
@bradfitz It doesn't look like it. Its a corner case that has always been broken.
Retrying on the http2 side and then returning an ErrSkipAltProtocol after a failed attempt seems odd.
I just don't know how to fix the implicit constraint that a req's body is only read once given we are allowing the http side to use a request that has already been processed.
One answer would be to always make a new request if the altRT path is taken since we can't tell what if anything has been touched.

**Comment by fraenkel** [comment] 2020-05-18 00:52
I do have a fix that returns `Get "https://127.0.0.1:45927/put/0": http2: Transport received Server's graceful shutdown GOAWAY` rather than the `status code: 500, body: request declared a Content-Length of 5 but only wrote 0 bytes`. Normally one might see `http2: no cached connection was available` but that would normally be replaced by the ErrSkipAltProtocol.
The other option would be to always create a new request to allow this request to be reused later if necessary.

**Comment by answer1991** [comment] 2020-05-18 03:10
I misunderstood that http2 request will never take altRT.RoundTrip before.

What about we fix [http roundtrip altRT.RoundTrip](https://github.com/golang/go/blob/2b70ffe9307c0992e28513ba25081d767b5937b2/src/net/http/transport.go#L514) error process like:

```go
	if altRT := t.alternateRoundTripper(req); altRT != nil {
		if resp, err := altRT.RoundTrip(req); err != ErrSkipAltProtocol {
			return resp, err
		}

		if req.GetBody != nil {
			var ierr error
			req.Body, ierr = req.GetBody()
			if ierr != nil {
				return nil, ierr
			}
		}
	}
```

**Comment by answer1991** [comment] 2020-05-18 03:13
> I do have a fix that returns Get "https://127.0.0.1:45927/put/0": http2: Transport received Server's graceful shutdown GOAWAY rather than the status code: 500, body: request declared a Content-Length of 5 but only wrote 0 bytes. 

I don't think return an error is acceptable.

**Comment by answer1991** [comment] 2020-05-18 09:34
I think I had figured out what happening:

1. Alternate RoundTrip is configured "https" with golang.org/x/net/http2 by us.
2. http2 RoundTrip("https" Alternate RoundTrip) has sent request body but received a HTTP2 GOAWAY frame, and then failed re-try to get connection from connection pool. The error is wrapper as `ErrSkipAltProtocol`.
3. Then http RoundTrip take over request, and we do not re-set request body here:

https://github.com/golang/go/blob/bb59a1360a9e6c2d32a59461da56e9bc3a5703ef/src/net/http/transport.go#L514-L518

And I think https://github.com/golang/go/issues/39086#issuecomment-629921722 would be a good solution.

**Comment by bcmills** [comment] 2020-05-19 18:01
Is this a duplicate of #32441?

**Comment by fraenkel** [comment] 2020-05-19 18:52
@bcmills yes it is.

**Comment by bcmills** [comment] 2020-05-19 19:56
Duplicate of  #32441

**Closed by bcmills** 2020-05-19 19:56 UTC
Labels: NeedsInvestigation, WaitingForInfo

**Comment by answer1991** [comment] 2020-05-20 02:32
Thanks @fraenkel @bcmills
