### ISSUE TITLE
x/tools/gopls: panic with latest master

### ISSUE THREAD

**Issue by primalmotion** [golang/go#36024] opened 2019-12-06 19:50 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

it happens with latest master. it works on 660eba4da30b912b1dd4b8279a97ff2a6ea1da25

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN="/Users/tonio/Documents/Aporeto/workspace/code/go/bin"
GOCACHE="/Users/tonio/Library/Caches/go-build"
GOENV="/Users/tonio/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY="go.aporeto.io,github.com/aporeto-inc"
GONOSUMDB="go.aporeto.io,github.com/aporeto-inc"
GOOS="darwin"
GOPATH="/Users/tonio/Documents/Aporeto/workspace/code/go"
GOPRIVATE="go.aporeto.io,github.com/aporeto-inc"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/tonio/Documents/Aporeto/workspace/code/go/src/golang.org/x/tools/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hc/3p6xvgw97kl124_y5p18kk6m0000gn/T/go-build289374822=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

nothing. just loading VSCode

### What did you expect to see?

it should work

### What did you see instead?

It panics

```
failed to load snapshot: no packages found for query ./...
	directory = file:///Users/tonio/Documents/Aporeto/workspace/code/javascript/junon
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x15939b5]

goroutine 77997 [running]:
golang.org/x/tools/internal/lsp/cache.(*snapshot).View(0x0, 0xc0591700b0, 0x1848240)
	/Users/tonio/Documents/Aporeto/workspace/code/go/src/golang.org/x/tools/internal/lsp/cache/snapshot.go:61 +0x5
golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshot(0xc000234120, 0x1851c20, 0x0)
	/Users/tonio/Documents/Aporeto/workspace/code/go/src/golang.org/x/tools/internal/lsp/diagnostics.go:20 +0x69
created by golang.org/x/tools/internal/lsp.(*Server).addFolders
	/Users/tonio/Documents/Aporeto/workspace/code/go/src/golang.org/x/tools/internal/lsp/general.go:173 +0x600
```

**Comment by heschik** [comment] 2019-12-06 20:11
Closing as duplicate of #36020. Thanks for the report!

**Closed by heschik** 2019-12-06 20:11 UTC
Labels: Tools, gopls
