### ISSUE TITLE
20201231 user time.AddDate(0,-1,0), result is 20201201

### ISSUE THREAD

**Issue by zhaobingchun** [golang/go#43457] opened 2021-01-01 14:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
source code
<pre>
func main() {
	date := time.Date(2020, 12, 31, 0, 0, 0, 0, time.Local)
	t := date.AddDate(0, -1, 0)
	fmt.Println("t:", t)
	strMonth := t.Format("200601")
	fmt.Println("month:", strMonth)
}
</pre>
result
<pre>
t: 2020-12-01 00:00:00 +0800 CST
month: 202012
</pre>
area: china

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by AlexRouSg** [comment] 2021-01-01 14:53
https://golang.org/pkg/time/#Time.AddDate

> AddDate normalizes its result in the same way that Date does, so, for example, adding one month to October 31 yields December 1, the normalized form for November 31.

20201231 - 1 month = 20201131 
20201131 does not exist -> 20201201

**Comment by ALTree** [comment] 2021-01-01 15:01
What @AlexRouSg said. Closing here since this is working as intended.

**Closed by ALTree** 2021-01-01 15:01 UTC
