### ISSUE TITLE
runtime/trace: missing cpu samples

### ISSUE THREAD

**Issue by felixge** [golang/go#58877] opened 2023-03-05 10:13 UTC
The tracer seems to be dropping CPU samples in a way that might not be explained by https://github.com/golang/go/issues/52674. At least I'm surprised by the pattern. cc @rhysh 

### What version of Go are you using (`go version`)?

<pre>
go version go1.20.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ubuntu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/ubuntu/sdk/go1.20.1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/ubuntu/sdk/go1.20.1/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2440112406=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Run the benchmarks in encoding/json while capturing a trace with CPU samples.

```
go test -run '^$' -bench . -cpuprofile trace.pprof -trace json.trace encoding/json
```

You can download the files above here: [Google Drive](https://drive.google.com/drive/folders/113DgIxBEszcakVJc8u07cz1EXNaDdIe8?usp=sharing)

### What did you expect to see?

The trace should contain lots of CPU samples throughout the trace, especially while all the Ps are execution goroutines.

### What did you see instead?

There are several seconds where all Ps are execution goroutines, but no CPU samples are being recorded.

![CleanShot 2023-03-05 at 10 46 51@2x](https://user-images.githubusercontent.com/15000/222953332-e4be556c-88b1-4130-a04e-a413eaa7991d.png)

I noticed this while implementing [traceutils flamescope](https://github.com/felixge/traceutils#flamescope) which also clearly shows this pattern:

![CleanShot 2023-03-05 at 10 41 27@2x](https://user-images.githubusercontent.com/15000/222953144-75dc295a-a7a8-447c-874e-faf6fa78023e.png)

As far as I can tell the trace should contain `126,873` samples, but it only contains `105,756` samples.

```
$ go tool pprof -top json.pprof | grep Total
Duration: 76.34s, Total samples = 1268.73s (1662.02%)

$ traceutils breakdown count json.trace | grep CPU
| EventCPUSample         |   105756 | 0.30%   |
```

**Comment by rhysh** [comment] 2023-03-05 17:37
Thanks @felixge . What part of the behavior you see is inconsistent with #52674?

Are you able to reproduce the problem with a smaller output file?

Is the pattern consistent across different runs?

Have you looked at the delta between the CPU profile and the execution trace's CPUSample events to see which kinds of samples are missing from the trace? I don't think this one will be fruitful; between 700 and 800 ms, the benchmark is running `BenchmarkCodeEncoder` so I'd expect the content of the samples to be the same, which is evidence against the samples' content somehow causing them to be dropped.

I see no CPUSample events between 0.878 seconds and 7.773 seconds, so it's even a bit worse than your screenshot shows. The additional-row spans on Proc 0 near 5.5 seconds are MARK ASSIST, SWEEP, and STW.

The execution trace includes 2094 CPUSample events leading up to the gap at 0.878–7.773 seconds. Spot-checking several of those, they seem to have very deep call stacks, often at or near the 64-frame limit. It seems likely that this is filling the `profBuf` that we use for the execution tracer's CPU profile samples, as described in #52674 (a bit more than 1900 samples).

```
$ go tool trace -d ~/Downloads/json.trace | grep CPUSample > /tmp/cpuse

$ cat /tmp/cpuse | awk '{print int($1/100e6),$1/1e6}' | grep -C 4 '^8 ' | tail
7 717.821
7 717.823
7 717.824
7 721.825
8 877.786
77 7773.8
77 7773.8
77 7773.8
77 7773.81

$ cat /tmp/cpuse | awk '{if ($1<1e9) {print $0}}' | wc -l 
    2094
```

**Comment by felixge** [comment] 2023-03-05 18:17
> Thanks @felixge . What part of the behavior you see is inconsistent with #52674?

My understanding of #52674 is that samples could be dropped if trace buffers are not being flushed often enough. I could imagine this to happen here, but I wouldn't expect the problem to last for so many seconds.

Beyond that I have no strong reason to believe this is not caused by #52674 . If that's the root cause, then this issue could be seen as a "real world" example of the problem.

> Are you able to reproduce the problem with a smaller output file?

No, but I haven't tried very hard.

> Is the pattern consistent across different runs?

Yeah, it seems pretty consistent between runs for me.

> Have you looked at the delta between the CPU profile and the execution trace's CPUSample events to see which kinds of samples are missing from the trace?

I haven't. Is there a way to extract a CPU pprof from a trace?

> I don't think this one will be fruitful; between 700 and 800 ms, the benchmark is running `BenchmarkCodeEncoder` so I'd expect the content of the samples to be the same, which is evidence against the samples' content somehow causing them to be dropped.

Makes sense.

> I see no CPUSample events between 0.878 seconds and 7.773 seconds, so it's even a bit worse than your screenshot shows. The additional-row spans on Proc 0 near 5.5 seconds are MARK ASSIST, SWEEP, and STW.

Ack.

> The execution trace includes 2094 CPUSample events leading up to the gap at 0.878–7.773 seconds. Spot-checking several of those, they seem to have very deep call stacks, often at or near the 64-frame limit.

Yeah, some benchmarks are definitely creating very deep stacks. But we'd expect those to be truncated, not dropped, if they exceed the 64 frame limit, right?

> It seems likely that this is filling the `profBuf` that we use for the execution tracer's CPU profile samples, as described in #52674 (a bit more than 1900 samples).

Ok, maybe that's what's happening after all.

> ```
> $ go tool trace -d ~/Downloads/json.trace | grep CPUSample > /tmp/cpuse
> ```

TIL about `-d` 🙈 - thanks 🙇.

> ```
> $ cat /tmp/cpuse | awk '{print int($1/100e6),$1/1e6}' | grep -C 4 '^8 ' | tail
> 7 717.821
> 7 717.823
> 7 717.824
> 7 721.825
> 8 877.786
> 77 7773.8
> 77 7773.8
> 77 7773.8
> 77 7773.81
> 
> $ cat /tmp/cpuse | awk '{if ($1<1e9) {print $0}}' | wc -l 
>     2094
> ```

Nice analysis. So based on this, you think this is probably caused by https://github.com/golang/go/issues/52674 - right?

**Comment by danp** [comment] 2023-03-05 20:32
Out of curiosity I added a `println("empty")` here:

https://github.com/golang/go/blob/b94dc384cabf75e7e8703265cd80f5324f84b642/src/runtime/trace.go#L846

And seem to get one or more consistently during BenchmarkMarshalBytes. Examples:

```
BenchmarkMarshalBytes/32
empty
BenchmarkMarshalBytes/32-8       	13310040	        91.08 ns/op

BenchmarkMarshalBytes/32
empty
BenchmarkMarshalBytes/32-8       	13002902	        88.95 ns/op

BenchmarkMarshalBytes/32
empty
empty
empty
BenchmarkMarshalBytes/32-8       	13341460	        86.97 ns/op
```

That's pretty early on in the run for me. I tried running the whole set of benchmarks once or twice but didn't see it pop up for any others.

**Comment by cagedmantis** [comment] 2023-03-06 16:20
cc @golang/runtime @mknyszek @prattmic @dvyukov

**Comment by mknyszek** [comment] 2023-03-15 19:11
Should this be deduplicated with #52674?

**Comment by felixge** [comment] 2023-03-15 20:08
> Should this be deduplicated with #52674?

Yes. Based on the discussion above, I think we can close this one as a dupe and maybe update the description of https://github.com/golang/go/issues/52674 to link to this issue for a concrete example?

**Comment by mknyszek** [comment] 2023-03-15 20:39
SGTM! Closing as duplicate of #52674.

**Closed by mknyszek** 2023-03-15 20:39 UTC
Labels: NeedsInvestigation, compiler/runtime
