### ISSUE TITLE
crypto/tls.Conn.Close can block indefinitely

### ISSUE THREAD

**Issue by yahe** [golang/go#41340] opened 2020-09-11 13:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
macOS 10.14.6 (18G6020)

### What did you do?
Call `Close()` on a `tls.Conn`

### What did you expect to see?
The call to `Close()` to not block, or documentation on the observed behavior

### What did you see instead?
Rarely, `Close()` hangs indefinitely unless I also set a write deadline on the connection.

It's understandable as the TLS conn tries to **send** a close alert before closing the connection, but it's not clearly stated in the docs, and I wrongly assumed `tls.Conn` to have the same behavior as the underlying connection. As far as I can tell `tls.Conn` is the only type to implement the `net.Conn` interface in the std library to require a wrote deadline not to let `Close` block indefinitely. Afaict `Read` has the same "issue" in that it automagically performs the handshake first, with the aggravating factor that having to set a **write** deadline not to let `Read` block is even more unintuitive.

**Comment by networkimprov** [comment] 2020-09-11 22:12
This is #31224, which has been passed over in the last two releases :-(

**Comment by davecheney** [comment] 2020-09-12 00:24
Duplicate of #31224

**Closed by davecheney** 2020-09-12 00:24 UTC
