### ISSUE TITLE
breaking change in go 1.9 about time marshal/unmarshal

### ISSUE THREAD

**Issue by yiminc** [golang/go#22251] opened 2017-10-13 17:34 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
> go version
go version go1.9.1 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
> go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yiminc/gocode"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f6/2zwvng355csd30gym37w1yph0000gn/T/go-build213006030=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
Marshal and Unmarshal a time.Time instance, they become different.
The use case is we use testify to setup mock expectation with a time as expected parameter. Then the tested code internally would do a marshal/unmarshal, and pass the value to the mock call. But the mock call would fail because the expectation does not met. The testify uses reflect.DeepEqual to compare if the parameters are match or not.

However, if you marshal/unmarshal a zero time, then before == after.

https://play.golang.org/p/dX_knLlRY-

This used to work fine with go 1.8

### What did you expect to see?
a time instance after marshal/unmarshal (on same machine) should not change.

### What did you see instead?
a time instance after marshal/unmarshal (on same machine) are different.

**Comment by artyom** [comment] 2017-10-13 17:43
Possible duplicate of #20876, please see its discussion.

**Comment by ianlancetaylor** [comment] 2017-10-13 17:45
This is expected behavior.  You should not in general use `reflect.DeepEqual` to compare `time.Time` values.  You should use `time.Equal` instead.  The time package docs say:

```
// Note that the Go == operator compares not just the time instant but
// also the Location and the monotonic clock reading. See the
// documentation for the Time type for a discussion of equality
// testing for Time values.
```

This discussion of `==` applies to `reflect.DeepEqual` instead.

It is true that this became less likely to work in Go 1.9, due to the introduction of monotonic time values.  But it was never fully safe even before Go 1.9, due to the way that timezones are handled.

Closing because this isn't going to change.

**Closed by ianlancetaylor** 2017-10-13 17:45 UTC

**Comment by yiminc** [comment] 2017-10-13 17:57
Understand DeepEqual behavior. The question is more about why the time are changed after marshal/unmarshal.

**Comment by ianlancetaylor** [comment] 2017-10-13 18:16
I assume because of the monotonic time values.  See the "Monotonic Clock" section at https://golang.org/pkg/time.

**Comment by yiminc** [comment] 2017-10-13 20:32
Don't understand why do we need to change the monotonic clock over marshal/unmarshal process?

**Comment by ianlancetaylor** [comment] 2017-10-13 20:41
The monotonic time is meaningless in a different process, so we don't marshal it at all.

**Comment by calvn** [comment] 2018-04-02 17:39
Interestingly, time comparison with `==` or `reflect.DeepEqual` after using `time.Truncate(0)` seem to work on MacOS, but not in linux/Go Playground. I haven't figured out why yet, but thought it might be useful to report this behavior.

```
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cleung/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/cleung/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1x/c_x5s2h90mzdyx4bzz3_dsx80000gn/T/go-build019210901=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

Updated Go Playground using `time.Truncate(0)` https://play.golang.org/p/XWurzn_3NTZ:
```
********************
BEFORE: 0001-01-01 00:00:00 +0000 UTC
AFTER : 0001-01-01 00:00:00 +0000 UTC
BEFORE.Equals(AFTER) : true
BEFORE == AFTER : true
BEFORE DeepEqual AFTER : true
********************
BEFORE: 2009-11-10 23:00:00 +0000 UTC
AFTER : 2009-11-10 23:00:00 +0000 UTC
BEFORE.Equals(AFTER) : true
BEFORE == AFTER : false
BEFORE DeepEqual AFTER : false

Program exited.
```


MacOS locally: 
```
$ go run main.go
********************
BEFORE: 0001-01-01 00:00:00 +0000 UTC
AFTER : 0001-01-01 00:00:00 +0000 UTC
BEFORE.Equals(AFTER) : true
BEFORE == AFTER : true
BEFORE DeepEqual AFTER : true
********************
BEFORE: 2018-04-02 12:56:10.065154507 -0400 EDT
AFTER : 2018-04-02 12:56:10.065154507 -0400 EDT
BEFORE.Equals(AFTER) : true
BEFORE == AFTER : true
BEFORE DeepEqual AFTER : true
```

**Comment by alexandrestein** [comment] 2018-09-06 11:32
@calvn I have a similar behavior with Arch Linux. `Go` is installed via default package manage `pacman`.
```
go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/alexandre/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/alexandre/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build737376362=/tmp/go-build -gno-record-gcc-switches"
```
If I run the same code inside a Docker it behave as Playground.
