### ISSUE TITLE
x/pkgsite: Update docs to explicitly allow mixed reciever types.

### ISSUE THREAD

**Issue by DevX86** [golang/go#56941] opened 2022-11-25 19:17 UTC
Please see https://github.com/golang/go/issues/56939

I am looking to amend the FAQ [method on values or pointers](https://go.dev/doc/faq#method_on_values_or_pointers) as it is currently leading to confusion and resulting in warnings being added to IDEs for valid use cases.

Specifically this section:
> Next is consistency. If some of the methods of the type must have pointer receivers, the rest should too, so the method set is consistent regardless of how the type is used. See the section on [method sets](https://go.dev/doc/faq#different_method_sets) for details.

When there are multiple valid use cases for mixed receiver types. Many developers and IDEs such as JetBrains' GoLand, view FAQs as standards, and thus issued warnings within their linter for mixed-type receivers based upon this. Not only are there confirmed valid use cases for mixed-type receivers but in some cases like the one outlined in https://github.com/golang/go/issues/56939, it should even be considered a best practice for developers especially new ones to provide safety against nil pointer receivers which there is also no explicit documentation nor recommendation on.

Is it possible to clarify this within the docs / FAQs, elaborate on these valid use cases, and remove the recommendation and perceived standard of having unilateral pointer or value receivers on types?

![IMG_0568](https://user-images.githubusercontent.com/87235892/204043795-3d11368c-fd2a-4401-93c9-035a0d94d8f2.png)

**Comment by seankhliao** [comment] 2022-11-25 20:18
The previous paragraphs already explain why you might want to choose one over the other. It is, as it says, purely a recommendation for consistency.

If you have an issue with your IDE, please file an issue with them.

Duplicate of #56939

**Closed by seankhliao** 2022-11-25 20:18 UTC
Labels: pkgsite
