### ISSUE TITLE
cmd/link: OSX 10.11 go/cgo binary corrupted by codesign

### ISSUE THREAD

**Issue by gazed** [golang/go#12950] opened 2015-10-15 17:49 UTC
1: go version go1.5.1 darwin/amd64
2: OSX 10.11 MacPro6,1Quad-Core Intel Xeon E5
3: Minimal program to create an invalid go binary on OSX using codesign tool.
```go
package main

import "C" // Delete this line and codesign'd binary works.

func main() {
    println("Hello OSX.")
}
```
```
~/code/src/ttt: go build
~/code/src/ttt: ./ttt
Hello OSX.
~/code/src/ttt: codesign -s "Developer ID Application: Name" ttt
~/code/src/ttt: ./ttt
Killed: 9
```
4: The program should run successfully after code signing. This used to work prior to OSX 10.11. 
5: All of my OSX Go products depend on Cgo. Still looking for a workaround.
Possibly related to issue #12700

**Comment by ianlancetaylor** [comment] 2015-10-15 18:02
This is peculiar since it's the opposite of what I would expect.  When you have the import "C" line there, the final program should be produced by the Darwin linker.  I don't know why codesign would break a progrma produced by the Darwin linker.

Please run the failing commands again, but use "go build -ldflags=-v".  Thanks.

**Comment by gazed** [comment] 2015-10-15 18:04
```
~/code/src/ttt: go build -ldflags=-v
# ttt
HEADER = -H1 -T0x2000 -D0x0 -R0x1000
searching for runtime.a in $WORK/runtime.a
searching for runtime.a in /usr/local/go/pkg/darwin_amd64/runtime.a
 0.00 deadcode
 0.01 pclntab=165294 bytes, funcdata total 34936 bytes
 0.01 dodata
 0.01 symsize = 0
 0.01 symsize = 0
 0.01 reloc
 0.02 reloc
 0.02 asmb
 0.02 codeblk
 0.03 datblk
 0.03 dwarf
 0.03 symsize = 0
 0.05 dwarf pass 2.
 0.06 sym
 0.06 headr
host link: "clang" "-m64" "-gdwarf-2" "-Wl,-no_pie,-headerpad,1144" "-Wl,-pagezero_size,4000000" "-o" "/var/folders/_d/8n_wrc4n32d1rgx80bn6hsl80000gn/T/go-build588937113/ttt/_obj/exe/a.out" "-Qunused-arguments" "/var/folders/_d/8n_wrc4n32d1rgx80bn6hsl80000gn/T/go-link-219552470/000000.o" "/var/folders/_d/8n_wrc4n32d1rgx80bn6hsl80000gn/T/go-link-219552470/000001.o" "/var/folders/_d/8n_wrc4n32d1rgx80bn6hsl80000gn/T/go-link-219552470/go.o" "-g" "-O2" "-g" "-O2" "-lpthread"
 0.12 cpu time
23064 symbols
17716 liveness data
~/code/src/ttt: ./ttt
Hello OSX.
~/code/src/ttt: codesign -s "Developer ID Application: Name" ttt
~/code/src/ttt: ./ttt
Killed: 9
```

**Comment by gazed** [comment] 2015-10-15 18:15
This problem does not seem occur when code-signing with some simple Obj-C binaries produced by clang. I've tried one from Xcode and one from the command line.

**Comment by rakyll** [comment] 2015-10-15 21:41
Looks like a duplicate of https://github.com/golang/go/issues/11887. The issue is the DWARF information in the binary. A workaround is to use `-ldflags=-s` until the issue is resolved.

**Closed** 2015-10-15 21:46 UTC
Labels: OS-Darwin
