### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by rthille** [golang/go#59993] opened 2023-05-04 23:05 UTC
### What is the URL of the page with the issue?
 https://go.dev/dl/
 
 
### What is your user agent?
 

 [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
### Screenshot
 

 N/A
 
 
### What did you do?
 

Visit:  https://go.dev/dl/ Look for info about https://go.dev/dl/?mode=json :-)

I was looking for a way to get a (more :-) machine readable version of https://go.dev/dl/ and resorted to tracking down the source to the site and found https://go.googlesource.com/website/+/refs/heads/master/internal/dl/dl.go#18 and that documents: https://go.dev/dl/?mode=json

However, it'd be really nice if there was text on the HTML version of the page which led a user/developer to that URL for the machine-readable (JSON) version of the page.

 
### What did you expect to see?
A link to the machine readable version of the page. 
 
 
### What did you see instead?
No information about how to find the machine readable version of the page.

**Comment by seankhliao** [comment] 2023-05-04 23:38
Duplicate of #34864

**Closed by seankhliao** 2023-05-04 23:38 UTC
Labels: website
