### ISSUE TITLE
js ArrayBuffer  --> go []uint8

### ISSUE THREAD

**Issue by WesternSun** [golang/go#28668] opened 2018-11-08 16:49 UTC
go1.11

how to carry a js ArrayBuffer to []uint8 in golang（ webassembly ?

**Comment by WesternSun** [comment] 2018-11-08 16:50
go webassembly

**Comment by agnivade** [comment] 2018-11-09 04:20
Hi @WesternSun ,

This appears to be a question rather than a Go bug. We do not use the issue tracker for general discussions or questions like these. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

For further questions, please have a look at [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.

Closing since this is not a bug.

**Closed by agnivade** 2018-11-09 04:20 UTC

**Comment by komuw** [comment] 2018-11-09 09:20
hi @agnivade .

This proposal by @bradfitz : https://github.com/golang/go/issues/23745 that allows questions on the issue tracker was accepted. 
Has it not been implemented yet?

**Comment by agnivade** [comment] 2018-11-09 09:57
The implementation details hasn't been hashed out yet. Hence it is still an open issue. We are yet to decide on what the exact process is going to be.
