### ISSUE TITLE
net/http: TimeoutHandler with header argument

### ISSUE THREAD

**Issue by BentCoder** [golang/go#46721] opened 2021-06-12 21:19 UTC
Hi,

Is it possible to add `headers` argument to `http.TimeoutHandler` method as well?

For instance currently I am using it like below but the header defaults to `text/html; charset=utf-8` :(

```go
http.TimeoutHandler(
    handler,
    timeout,
    `{"code":"service_unavailable","message":"The server cannot handle the request"}`,
)
```

If I gave chance to set the message, would have given chance to set the header too.

Thanks

**Comment by seankhliao** [comment] 2021-06-12 21:40
Duplicate of #22821

**Closed by seankhliao** 2021-06-12 21:40 UTC
Labels: FeatureRequest, NeedsInvestigation
