### ISSUE TITLE
cmd/go: go install -a <pkg> attempts to rebuild the stdlib

### ISSUE THREAD

**Issue by natefinch** [golang/go#22469] opened 2017-10-27 15:33 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.9.2 OSX

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
macOS 10.12.6

$ go version
go version go1.9.2 darwin/amd64
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jake/Projects/Labs/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h2/whwtkkx168n8333397n69m2r0000gn/T/go-build684654678=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config

### What did you do?

go install -a -ldflags=-X "github.com/magefile/mage/mage.timestamp=2017-10-27T09:39:17-05:00" -X "github.com/magefile/mage/mage.commitHash=accd8ef" -X "github.com/magefile/mage/mage.gitTag=v2.0.1-3-gaccd8ef" github.com/magefile/mage

go install runtime/internal/sys: open /usr/local/go/pkg/darwin_amd64/runtime/internal/sys.a: permission denied

## Thoughts

I see a lot of comments about this specific problem in old issues.  It seems like go install -a is trying to rebuild the standard library on machines with a goroot that is not in a user-editable directory.

My build script uses `go install -a` because `go install` will no-op if you have already built the code without any changes, but in this case, my install script is building with ldflags, so the binary that is being output will be different than it would be without the ldflags, even though nothing has changed on disk.

`go install -a` should be smart enough not to rebuild the stdlib.

**Comment by mvdan** [comment] 2017-10-27 15:54
> `go install -a` should be smart enough not to rebuild the stdlib.

To clarify - do you mean on all cases, or just on those where `$GOROOT` is not writeable?

**Comment by natefinch** [comment] 2017-10-27 16:12
Only where the goroot is not writeable (notably the case on many machines that get installed via OS package managers).  Works fine with a writeable home directory (such as on my machine where I built from source)

**Comment by whoisjake** [comment] 2017-10-27 17:34
For myself, I found this issue using the official macOS pkg file for Go 1.9.2

**Comment by crawshaw** [comment] 2017-10-27 18:22
Is this a change in 1.9.2, or has it always been so? (I would expect `go install -a` to reinstall the stdlib.)

Does `go build -i` do what you need?

**Comment by natefinch** [comment] 2017-10-27 18:31
I've seen similar bug reports going back 4 years, so it's not new, AFAICT.

-a rebuilding and reinstalling the stdlib may be expected, depending on your assumptions, but it's still going to Just Not Work in a very large number of cases... and is almost assuredly not what most people intend when they type `go install -a`

-i is not the right functionality. That installs dependencies, not the binary itself.

I have a fix for my specific use case, by effectively copying what `go install -a` does using `go build`.... but I'd prefer to use the tool that already (theoretically) does what I want, aside from this issue with -a not doing what I think it should.

**Comment by ianlancetaylor** [comment] 2017-10-27 23:49
This is working as intended.  See the long comment starting at https://golang.org/src/cmd/go/internal/load/pkg.go#L1213 .

The need to use `-a` to change `-X` flags should be fixed in 1.10.

Closing because the current behavior is intentional.

**Closed by ianlancetaylor** 2017-10-27 23:49 UTC

**Comment by natefinch** [comment] 2017-10-30 14:18
@ianlancetaylor I think that any flag which is guaranteed to fail a large percentage of the time (not sure what the stats are on go installs... but maybe 50% or more?) is a mistake, whether or not it's working as intended.  Intending that a flag will fail with an obscure error is bad UX.

Ideally, IMO, the flag should not rebuild the stdlib.  At a minimum, the error message should be cleaned up to make it more clear what's going on, and that this is expected.

**Comment by cznic** [comment] 2017-10-30 14:32
It fails about 0% of time on a developer machine with Go installed from source. What should replace the -a flag on those machines?

**Comment by natefinch** [comment] 2017-10-30 14:37
If I want to rebuild the stdlib, I'd go to my go source tree and re-run make.bash.  But I've only wanted/needed to to do that exactly once in the past 5 years (outside of explicitly changing go versions).

**Comment by cznic** [comment] 2017-10-30 17:54
make.bash takes longer to run.

> But I've only wanted/needed to to do that exactly once in the past 5 years (outside of explicitly changing go versions

If one works on a patch of the compiler and/or stdlib, -a can be useful. I understand your experience differs, but you should consider that other people are doing different things as well and taking away useful features they use is not really an option.

**Comment by ianlancetaylor** [comment] 2017-10-30 18:50
@natefinch The `-a` option has a purpose and is useful.  I understand that it didn't solve your problem, and indeed your problem (`-X` does not trigger a rebuild when it should) is a bug (#18369).  I understand that you thought `-a` would fix your problem and are disappointed that it doesn't.  But it was never intended to fix your problem.  That situation is unfortunate but this issue is still not a bug that we are going to fix.

**Comment by natefinch** [comment] 2017-11-04 04:20
Thanks, Russ. I read the post on golang-dev and it looks awesome. Can't
wait to see it in action.
