### ISSUE TITLE
cmd/compile: 1.18 produces different type descriptor for identical struct in different packages

### ISSUE THREAD

**Issue by pfi79** [golang/go#52856] opened 2022-05-11 19:53 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17.10 and 1.18.1
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/......./Library/Caches/go-build"
GOENV="/Users/......./Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/......./go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/......./go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/....../go/src/github.com/......./qqqqq/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6v/kmxqr0yn61588pbz646cfdyc0000gq/T/go-build1526426409=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

[go 1.18](https://go.dev/play/p/-U9HaXTB0aU)
[go 1.17](https://go.dev/play/p/-U9HaXTB0aU?v=goprev)

### What did you expect to see?
identical behaviour

### What did you see instead?
different behavior

If the change in behavior is normal, please show the comit in which it has changed

**Comment by dmitshur** [comment] 2022-05-11 21:15
A possibly minified repro (with `struct { int }`): https://go.dev/play/p/F_PIyGVxd0E.

**Comment by ianlancetaylor** [comment] 2022-05-11 23:06
Although both values have type `struct { int }`, in 1.18 the type descriptors for the two values are different.  In 1.17 they are the same.  This appears to be a bug in 1.18.  I don't see any difference in the field values of the descriptors, we seem to just have two different identical descriptors.

CC @randall77 @cherrymui

**Comment by ianlancetaylor** [comment] 2022-05-11 23:07
@gopherbot Please open a backport for 1.18.

This should be fixed in a 1.18 minor release.  The bug does not exist in earlier releases.

**Comment by cherrymui** [comment] 2022-05-11 23:34
The spec says https://go.dev/ref/spec#Type_identity

> Two struct types are identical if they have the same sequence of fields, and if corresponding fields have the same names, and identical types, and identical tags. [Non-exported](https://go.dev/ref/spec#Exported_identifiers) field names from different packages are always different.

Here the field name (`int`) is non-exported. I would think the new behavior is actually correct.

The embedding makes it an interesting case. I guess one could argue that the field name for both types is from the `builtin` package, therefore same? If it were non-embedded type (like `struct { x int }` or even `struct { int int }`), it would be clearly different, and the compiler always emits different type descriptors.

**Comment by ianlancetaylor** [comment] 2022-05-12 00:20
Thanks.  You're right: with 1.18 the `Field(0).StructField.PkgPath` field is different for the two types.  With 1.17 it's `main` for both.

I guess this may be technically correct.  Anybody want to argue otherwise?

CC @griesemer @mdempsky

**Comment by mdempsky** [comment] 2022-05-12 00:26
I agree the 1.18 behavior is correct. `struct { int }` denotes different types when it appears in different packages, because the field names are non-exported and therefore different.

**Comment by mdempsky** [comment] 2022-05-12 00:31
FWIW, I suspect https://go-review.googlesource.com/c/go/+/378434/ is the CL that introduced the changed (fixed) behavior here.

**Comment by griesemer** [comment] 2022-05-12 00:42
I'd also say the 1.18 behavior is correct. The name of an embedded field is simply the (unqualified) name of the embedded type, there's no knowledge of that name coming from a built-in (predeclared) type. The usual export rules apply. The behavior for `struct{int}` should be the same as for `struct{int int}` with respect to `DeepEqual`.

**Comment by pfi79** [comment] 2022-05-12 05:46
Great. Thank you very much. 

If nothing needs to be changed, the issue can be closed.

**Comment by mdempsky** [comment] 2022-05-12 06:08
Working as intended.

**Closed by mdempsky** 2022-05-12 06:08 UTC
Labels: NeedsInvestigation, release-blocker

**Comment by pfi79** [comment] 2022-05-12 06:12
To finally clarify the question

If you replace the example with one like this, it is true everywhere.

> func T() interface{} {
> 	return struct{ X int }{123}
> }

And if you replace the example with one like this, it is false everywhere.

> type Q struct{ I int }
> 
> func T() interface{} {
> 	return Q{123}
> }

Is this behavior correct?

**Comment by mdempsky** [comment] 2022-05-12 07:08
@pfi79 The code at https://go.dev/play/p/aAwW6Hhyous appears to behaving correctly, yes.

**Comment by C0rWin** [comment] 2022-05-12 07:57
> Working as intended.

I have to say it's a little bit unexpected, while I understand why it should be true speaking of unexported fields, IMO with embedding, it is not that obvious, and breaking backwards compatibility.

**Comment by mdempsky** [comment] 2022-05-12 08:37
@C0rWin I'm sorry for surprise.
