### ISSUE TITLE
cmd/go: 1.11beta2 cannot find module providing package

### ISSUE THREAD

**Issue by udhos** [golang/go#26695] opened 2018-07-30 15:28 UTC
### What version of Go are you using (`go version`)?

go version go1.11beta2 linux/amd64

### Does this issue reproduce with the latest release?

Yes, it affects go1.11beta2.

### What operating system and processor architecture are you using (`go env`)?

```
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lab/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lab/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build934050422=/tmp/go-build -gno-record-gcc-switches"

```
### What did you do?

Tried to build a trivial application 'modapp' which depends on specific package 'lib' from trivial module 'modlib'. The repository is tagged as 'modlib/v1.0.0'.

I have posted full description of the issue on Stackoverflow: https://stackoverflow.com/questions/51560387/how-to-import-specific-package-from-go-module

A quick way to reproduce is:

    # 1) install go1.11beta2
    # 2) run:
    git clone https://github.com/udhos/modhello
    cd modhello/modlib
    go list -m all
    cd ../modapp
    go install

I have been told the git version may be important:

```
$ git --version
git version 2.18.0
```

### What did you expect to see?

modapp should have been compiled and installed as ~/go/bin/modapp without errors.

However I may well be doing something wrong.

### What did you see instead?

```
go install
go: finding github.com/udhos/modhello/modlib/lib latest
go: finding github.com/udhos/modhello latest
go: import "github.com/udhos/modhello/modapp" ->
        import "github.com/udhos/modhello/modlib/lib": cannot find module providing package github.com/udhos/modhello/modlib/lib
```

**Comment by marwan-at-work** [comment] 2018-07-30 17:26
@udhos Did you run these steps before pushing your repo to github? Right now, your repo works fine and it does not reproduce the error when following the steps above.

This is likely because `modapp` requires `modlib` as an "independent dependency" because you have multiple go.mod files in the same repo. Therefore, when you first try to run `go install` inside `modapp`, Go tries to fetch `modlib` from upstream (which you may not have pushed to github at that point) and therefore it cannot find it. 

Having one `go.mod` per repo would solve this.

**Comment by udhos** [comment] 2018-07-30 17:39
Yes, I tested the steps to reproduce it before opening the issue.
I wonder if there could be anything cached somewhere persistently causing the issue for me.

```
lab@ubu1:~/eraseme$ rm -rf modhello/
lab@ubu1:~/eraseme$ git clone https://github.com/udhos/modhello
Cloning into 'modhello'...
remote: Counting objects: 70, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 70 (delta 23), reused 59 (delta 16), pack-reused 0
Unpacking objects: 100% (70/70), done.
lab@ubu1:~/eraseme$ cd modhello/modapp
lab@ubu1:~/eraseme/modhello/modapp$ go install
go: finding github.com/udhos/modhello/modlib/lib latest
go: finding github.com/udhos/modhello latest
go: import "github.com/udhos/modhello/modapp" ->
        import "github.com/udhos/modhello/modlib/lib": cannot find module providing package github.com/udhos/modhello/modlib/lib
lab@ubu1:~/eraseme/modhello/modapp$
```

**Comment by udhos** [comment] 2018-07-30 18:01
> Having one go.mod per repo would solve this.

When I hit this issue, I was actually trying to figure out how to host two distinct modules at the same git repository while also importing a specific package from a module.

I mean:
1) Multiple modules hosted at single repo.
2) Multiple packages hosted at single module.

As far as I can tell, such a layout is supported, right?

**Comment by udhos** [comment] 2018-07-30 18:10
@marwan-at-work I have just tested the steps with a new user and it indeed worked as expected... So I guess there is something cached in the homedir of the old user...

**Comment by sillyousu** [comment] 2018-07-31 09:01
I can reproduce with @rsc 's  [A Tour of Versioned Go](https://research.swtch.com/vgo-tour)

```
[supei@localhost hello]$ cat go.mod
module github.com/you/hello
[supei@localhost hello]$ cat hello.go
package main // import "github.com/you/hello"

import (
        "fmt"

        "rsc.io/quote"
)

func main() {
        fmt.Println(quote.Hello())
}
[supei@localhost hello]$ go1.11beta2 build
go: finding rsc.io/quote v1.5.2
go: import "github.com/you/hello" ->
        import "rsc.io/quote": cannot find module providing package rsc.io/quote
[supei@localhost hello]$ go ^C
[supei@localhost hello]$ go1.11beta2  env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/supei/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/supei/gohome"
GOPROXY=""
GORACE=""
GOROOT="/home/supei/sdk/go1.11beta2"
GOTMPDIR=""
GOTOOLDIR="/home/supei/sdk/go1.11beta2/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/supei/hello/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build093482810=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by sillyousu** [comment] 2018-07-31 09:17
I believe this bug is fixed in https://github.com/golang/go/commit/90066bf06a9b10b3b222a289934b93723bb788d6

**Comment by bcmills** [comment] 2018-08-02 22:01
This seems to work for me (with git 2.18.0, which suggests that @sillyousu's theory is correct).

```
modapp$ go list -m all
go: finding github.com/udhos/modhello/modlib v1.0.0
github.com/udhos/modhello/modapp
github.com/udhos/modhello/modlib v1.0.0

modapp$ go build .
go: downloading github.com/udhos/modhello/modlib v1.0.0

modapp$
```

**Comment by bcmills** [comment] 2018-08-02 22:02
(But please do let us know if it's still broken at head, or at go1.11beta3 whenever that comes out.)

**Closed by bcmills** 2018-08-02 22:01 UTC
Labels: NeedsInvestigation, modules

**Comment by udhos** [comment] 2018-08-02 22:07
I don't think it's a git issue, because I am running git 2.18.0 as well.
I think it is some Go caching issue, because it affects one user but not other newer user, both on the same system. Both users share system-wide go 1.11beta2 and git 2.18.0.

**Comment by bcmills** [comment] 2018-08-02 22:11
You may need to run `go clean -modcache` to clear out cached data from before the fix.

**Comment by udhos** [comment] 2018-08-02 22:48
`go clean -modcache` did fix it! Thanks!
