### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by froucoux** [golang/go#61790] opened 2023-08-06 08:12 UTC
### What is the URL of the page with the issue?
 
 
 https://go.dev/doc/tutorial/random-greeting

 
### What did you do?
  
 Following the tutorial
 
### What did you expect to see?
 
Given that instruction in the tutorial :
"Add an init function to seed the rand package with the current time. Go executes init functions automatically at program startup, after global variables have been initialized. For more about init functions, see [Effective Go](https://go.dev/doc/effective_go.html#init)."

I expect an init function in the source code.
 
### What did you see instead?

The init function is not present in the source code (and the rand.seed function is deprecated).)

**Comment by seankhliao** [comment] 2023-08-06 08:48
Duplicate of #60627

**Closed by seankhliao** 2023-08-06 08:48 UTC
Labels: website
