### ISSUE TITLE
go work: go mod verify fails inside a workspace 

### ISSUE THREAD

**Issue by KenxinKun** [golang/go#57735] opened 2023-01-11 14:26 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, I upgraded to `1.19.5` and obtained the same behaviour.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/borja/Library/Caches/go-build"
GOENV="/Users/borja/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/borja/go/pkg/mod"
GONOPROXY="go.buf.build,buf.build/gen/go"
GONOSUMDB="github.com/90poe,go.buf.build,buf.build/gen/go"
GOOS="darwin"
GOPATH="/Users/borja/go"
GOPRIVATE="go.buf.build,buf.build/gen/go"
GOPROXY="https://proxy.golang.org,https://athens-mod-proxy.development.devopenocean.studio"
GOROOT="/usr/local/Cellar/go/1.19.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.19.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK="/Users/borja/code/go-work-verify/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xz/7t52h1015dj_14pj_hv7ymkw0000gp/T/go-build1416415029=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I created a Go workspace and added a couple of modules to it, then attempted to run `go mod verify` on any of the modules and the workspace itself.

Minimal reproduction: https://github.com/KenxinKun/go-workspace-mod-verify
Just run `make all` to reproduce or directly `go mod verify`.

### What did you expect to see?

A successful return from `go mod verify`

### What did you see instead?

The command failed with the error:

<pre>
$ go mod verify
mod2 : missing ziphash: open hash: no such file or directory
make: *** [workspace-verify] Error 1
</pre>

### Attempted fixes

I tried following the recommendations in https://github.com/ignite/cli/issues/137 to run `go clean -modcache`, but I still obtained the same behaviour.

**Comment by KenxinKun** [comment] 2023-01-11 14:34
Also looks like a duplicate of: https://github.com/golang/go/issues/54372 :)

**Comment by bcmills** [comment] 2023-01-11 14:34
Duplicate of #54372

**Closed by bcmills** 2023-01-11 14:34 UTC
