### ISSUE TITLE
net/http/httputil: DumpRequestOut error when POST responds with 301 

### ISSUE THREAD

**Issue by VeNoMouS** [golang/go#47161] opened 2021-07-13 11:14 UTC
There appears to be a bug with `httputil.DumpRequestOut` ... with `body` set to `true` and doing a POST request and if the server responds with a 301 ... it errors out...

The error that you get is `http: ContentLength=2265 with Body length 0` from `transfer.go` in `writeBuf`

```go
	if !t.ResponseToHEAD && t.ContentLength != -1 && t.ContentLength != ncopy {
		return fmt.Errorf("http: ContentLength=%d with Body length %d",
			t.ContentLength, ncopy)
	}
```

If you remove the `DumpRequestOut` , everything works fine...

**Comment by seankhliao** [comment] 2021-07-13 22:56
I can't reproduce this with 

```go
func main() {
	r := bufio.NewReader(strings.NewReader("xxx")) // skip http.NewRequest setting Request.GetBody
	req, err := http.NewRequest("POST", "http://localhost:8080/redirect", r)
	if err != nil {
		log.Fatal(err)
	}

	dump, err := httputil.DumpRequestOut(req, true)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(string(dump))
	_, err = http.DefaultClient.Do(req)
	if err != nil {
		log.Fatal(err)
	}
}

```

**Comment by VeNoMouS** [comment] 2021-07-14 23:04
I was doing this via a .do(req) the problem with dumprequestout , you have to do it after the .do as cookies etc arent added in prior to the .do

**Comment by seankhliao** [comment] 2021-07-14 23:21
Request bodies are `io.Reader`s, they can only be read once and in your case, when the request is made. 

Closing as this is working was intended

**Closed by seankhliao** 2021-07-14 23:21 UTC
Labels: WaitingForInfo
