### ISSUE TITLE
cmd/go: get -u can fail once and then succeed

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#14450] opened 2016-02-21 20:44 UTC
Noticed by accident.  After running go get for an invalid directory, the first `go get -u` fails, and the second succeeds.  The `internal error` lines at the end are #14444.  This issue is about the fact that the two runs of `go get -u .../` fail in different ways.

I haven't looked into it.

    > mkdir /tmp/gopath2
    > GOPATH=/tmp/gopath2 go get golang.org/x/tools/cmd/imports   # does not exist
    package golang.org/x/tools/cmd/imports: cannot find package "golang.org/x/tools/cmd/imports" in any of:
    	/home/iant/go/src/golang.org/x/tools/cmd/imports (from $GOROOT)
    	/tmp/gopath2/src/golang.org/x/tools/cmd/imports (from $GOPATH)
    > GOPATH=/tmp/gopath2 go get -u .../
    /tmp/gopath2/src/golang.org/x/net/html/charset/charset.go:20:2: cannot find package "golang.org/x/text/encoding" in any of:
    	/home/iant/go/src/golang.org/x/text/encoding (from $GOROOT)
    	/tmp/gopath2/src/golang.org/x/text/encoding (from $GOPATH)
        /tmp/gopath2/src/golang.org/x/net/html/charset/charset.go:21:2: cannot find package "golang.org/x/text/encoding/charmap" in any of:
    	/home/iant/go/src/golang.org/x/text/encoding/charmap (from $GOROOT)
    	/tmp/gopath2/src/golang.org/x/text/encoding/charmap (from $GOPATH)
    /tmp/gopath2/src/golang.org/x/net/html/charset/charset.go:22:2: cannot find package "golang.org/x/text/encoding/htmlindex" in any of:
    	/home/iant/go/src/golang.org/x/text/encoding/htmlindex (from $GOROOT)
    	/tmp/gopath2/src/golang.org/x/text/encoding/htmlindex (from $GOPATH)
    /tmp/gopath2/src/golang.org/x/net/html/charset/charset.go:23:2: cannot find package "golang.org/x/text/transform" in any of:
    	/home/iant/go/src/golang.org/x/text/transform (from $GOROOT)
    	/tmp/gopath2/src/golang.org/x/text/transform (from $GOPATH)
    /tmp/gopath2/src/golang.org/x/net/http2/h2i/h2i.go:38:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
    	/home/iant/go/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
    	/tmp/gopath2/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)
    > GOPATH=/tmp/gopath2 go get -u .../
    internal error: duplicate loads of unsafe
    internal error: duplicate loads of runtime/internal/sys
    internal error: duplicate loads of runtime/internal/atomic
    many other internal errors

**Comment by mahendrakariya** [comment] 2016-02-23 06:01
I can reproduce this even on Go 1.5.2
```
$ go version
go version go1.5.2 darwin/amd64
```

**Comment by ianlancetaylor** [comment] 2016-02-24 01:30
Thanks, if this fails with 1.5, adjusting milestone to 1.7.

**Comment by mahendrakariya** [comment] 2016-02-24 02:09
Looks like my earlier comment got accidently deleted. So adding it again.

I was able to reproduce this issue in Go 1.5 on darwin/amd64.

**Comment by tmwh** [comment] 2016-02-25 02:51
This issue is repeatable with existing package too:

```
> mkdir /tmp/gopath2
> GOPATH=/tmp/gopath2 go get golang.org/x/tools/cmd/bundle
> GOPATH=/tmp/gopath2 go get -u .../

/tmp/gopath2/src/golang.org/x/net/html/charset/charset.go:20:2: cannot find package "golang.org/x/text/encoding" in any of:
	/home/tmwh/go/src/golang.org/x/text/encoding (from $GOROOT)
	/tmp/gopath2/src/golang.org/x/text/encoding (from $GOPATH)
/tmp/gopath2/src/golang.org/x/net/html/charset/charset.go:21:2: cannot find package "golang.org/x/text/encoding/charmap" in any of:
	/home/tmwh/go/src/golang.org/x/text/encoding/charmap (from $GOROOT)
	/tmp/gopath2/src/golang.org/x/text/encoding/charmap (from $GOPATH)
/tmp/gopath2/src/golang.org/x/net/html/charset/charset.go:22:2: cannot find package "golang.org/x/text/encoding/htmlindex" in any of:
	/home/tmwh/go/src/golang.org/x/text/encoding/htmlindex (from $GOROOT)
	/tmp/gopath2/src/golang.org/x/text/encoding/htmlindex (from $GOPATH)
/tmp/gopath2/src/golang.org/x/net/html/charset/charset.go:23:2: cannot find package "golang.org/x/text/transform" in any of:
	/home/tmwh/go/src/golang.org/x/text/transform (from $GOROOT)
	/tmp/gopath2/src/golang.org/x/text/transform (from $GOPATH)
/tmp/gopath2/src/golang.org/x/net/http2/h2i/h2i.go:38:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
	/home/tmwh/go/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
	/tmp/gopath2/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)
```

It happens because `golang.org/x/tools/cmd/html2article` depends on `golang.org/x/net/html` and after `golang.org/x/net/html` is successfully downloaded we are trying to import all packages (`.../`) from its repository. It contains `golang.org/x/net/html/charset` which is not imported in any other packages. That's why its imports (`golang.org/x/text/encoding`, `golang.org/x/text/encoding/charmap`, `golang.org/x/text/encoding/htmlindex`...) were not downloaded. 

I've created the minimal packages structure for reproducing this:
https://github.com/tmwh/go-get-issue-14450
https://github.com/tmwh/go-get-issue-14450-b-dependency
https://github.com/tmwh/go-get-issue-14450-d-dependency

I've come up with 2 possible solutions for this problem
- Don't try to import packages that were not downloaded
- Download all packages that are matching the passed path even if they were downloaded as part of the other packages' repository.

The first one was smaller, so I've decided to submit it https://go-review.googlesource.com/19892 I can submit the second solution too, if it is the way you would like to solve that.

**Comment by quentinmit** [comment] 2016-05-26 18:41
Ping @rsc. I'm not sure if there's discussion elsewhere that I'm not seeing, but it seems like there's a straightforward fix for this waiting for your review in CL 19892. I'll refrain from punting to Go1.8 for now until I hear back from you.

**Comment by rsc** [comment] 2016-05-27 01:46
Not going to get to this for Go 1.7, sorry.

**Closed** 2016-10-05 23:53 UTC
Labels: NeedsFix
