### ISSUE TITLE
Gotip generics test build fail

### ISSUE THREAD

**Issue by cretz** [golang/go#47933] opened 2021-08-24 11:36 UTC
### What version of Go are you using (`go version`)?

<pre>
$ gotip version
go version devel go1.18-8eeb1bff1d Tue Aug 24 00:01:29 2021 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

No (generics related)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ gotip env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\chad.retz\AppData\Local\go-build
set GOENV=C:\Users\chad.retz\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\chad.retz\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\chad.retz\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\chad.retz\sdk\gotip
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\chad.retz\sdk\gotip\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=devel go1.18-8eeb1bff1d Tue Aug 24 00:01:29 2021 +0000
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=c:\work\nonsp\go2\fut\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\CHAD~1.RET\AppData\Local\Temp\go-build3121634206=/tmp/go-build -gno-record-gcc-switches</pre></details>

### What did you do?

go.mod:

```
module github.com/cretz/fut

go 1.18
```

fut.go:

```go
package fut

import (
	"context"
)

// Do not check the second two values if the channel not done.
type Fut[Out any] func(context.Context) (<-chan struct{}, Out, error)

var alwaysDone = make(chan struct{})

func init() { close(alwaysDone) }

func Fixed[Out any](v Out) Fut[Out] {
	return func(context.Context) (<-chan struct{}, Out, error) {
		return alwaysDone, v, nil
	}
}

func Wait[Out any](ctx context.Context, f Fut[Out]) (out Out, err error) {
	if ctx.Err() != nil {
		err = ctx.Err()
		return
	}
	done, out, err := f(ctx)
	select {
	case <-ctx.Done():
		return out, ctx.Err()
	case <-done:
		return out, err
	}
}
```

fut_test.go:

```go
package fut_test

import (
	"context"
	"fmt"

	"github.com/cretz/fut"
)

func ExampleThen() {
	f1 := fut.Fixed("Hello")
	fmt.Println(fut.Wait(context.TODO(), f1))
}
```

Run:

```
$ gotip test
# github.com/cretz/fut_test
vet.exe: .\fut_test.go:7:2: could not import github.com/cretz/fut (cannot import "github.com/cretz/fut" (unexpected parameterized function/method), possibly version skew - reinstall package)
FAIL    github.com/cretz/fut [build failed]
```

### What did you expect to see?

Successful test build and run.

### What did you see instead?

```
# github.com/cretz/fut_test
vet.exe: .\fut_test.go:7:2: could not import github.com/cretz/fut (cannot import "github.com/cretz/fut" (unexpected parameterized function/method), possibly version skew - reinstall package)
FAIL    github.com/cretz/fut [build failed]
```

I have done clean, used `-a`, etc. Also does not build binary even if what's in test is in main. Sorry if known issue, could not find.

**Comment by seankhliao** [comment] 2021-08-24 11:43
Duplicate of #47915

**Closed by seankhliao** 2021-08-24 11:43 UTC
