### ISSUE TITLE
affected/package: text/template

### ISSUE THREAD

**Issue by Manborough** [golang/go#52939] opened 2022-05-17 01:07 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.18.1

</pre>

### Does this issue reproduce with the latest release?

I haven't tested in 1.18.2, release notes don't indicate any changes to text/template.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users//Library/Caches/go-build"
GOENV="/Users//Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users//go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users//go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users..."
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vv/st_jtr1n419181tj6lh9ryvw0000gn/T/go-build701183218=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

https://go.dev/play/p/BMFTpmZLvaY

### What did you expect to see?

" The greater and less than signs, consider < >"

### What did you see instead?

" The greater and less than signs, consider &lt; >"

EDIT: Github is formatted the escaped character it looks like this & lt ; but all together.

### Description

It appears that the text/template library is escaping/altering the less than symbol. I wasn't able to find any documentation that suggests this is the intended behaviour, and the greater than symbol returns as expected.

**Comment by ianlancetaylor** [comment] 2022-05-17 01:17
You are using the html/template package.  It is escaping the `<` character as `&lt;`.  That is working as expected.

If you do use the text/template package, it will not change the `<` character.

Closing because this is working as intended.

**Closed by ianlancetaylor** 2022-05-17 01:17 UTC
