### ISSUE TITLE
cmd/gofmt: wrong indentation when chaining methods in var block

### ISSUE THREAD

**Issue by masseelch** [golang/go#63823] opened 2023-10-30 15:45 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/***/.cache/go-build'
GOENV='/home/***/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/***/go/pkg/mod'
GONOPROXY=***
GONOSUMDB=***
GOOS='linux'
GOPATH='/home/***/go'
GOPRIVATE=***
GOPROXY='https://goproxy.cn,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD=***
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3477416207=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

When chaining methods, indentation is wrong inside a `var` block if the variable names have different lengths:

```go
func main() {
	var (
		a = foo.Bar.
			Do().
			This().
			Again()
		longerVar = foo.Bar.
				Do().
				This().
				Again()
	)
}
```

[Playground](https://go.dev/play/p/9tlqvnMYAWd)

What I would expect the code to be formatted like:

```go
func main() {
	var (
		a = foo.Bar.
			Do().
			This().
			Again()
		longerVar = foo.Bar.
			Do().
			This().
			Again()
	)
}
```

This is especially confusing, since `go fmt` will format to what I'd expect, if the declarations weren't enclosed in a `var` block: 

```go
func main() {
	a := foo.Bar.
		Do().
		This().
		Again()
	longerVar := foo.Bar.
		Do().
		This().
		Again()
}
```

[Playground](https://go.dev/play/p/9A2_itRtYIF)

I found one (somehow) related issue: #32480

**Comment by cherrymui** [comment] 2023-10-30 15:54
@masseelch What indentation do you expect? Thanks.

**Comment by masseelch** [comment] 2023-10-30 15:57
> @masseelch What indentation do you expect? Thanks.

I updated the issue description.

**Comment by masseelch** [comment] 2023-10-30 16:17
> Thanks. So you're expecting one tab indentation regardless of the length of the variable name?
> 
> cc @griesemer @mvdan

Yes. This only happens in a `var` block, if you compare it to the same variables, without the var block, it works as I expect: [Playground](https://go.dev/play/p/9A2_itRtYIF).

**Comment by seankhliao** [comment] 2023-10-30 17:01
Duplicate of #45491

**Closed by seankhliao** 2023-10-30 17:01 UTC
Labels: NeedsInvestigation
