### ISSUE TITLE
time: add weekday helper functions

### ISSUE THREAD

**Issue by Vitucho** [golang/go#25469] opened 2018-05-20 15:40 UTC
Perhaps in future editions it would be nice to have a convenient function to get the following (or previous) week day of a given one.

## Current Behaviour
As a client of time.Util library, for a given day if i rqquire to calculate the following one
```
today := time.Now()
tomorrow := today.Add(time.Duration(24) * time.Hour) // adds a day duration
tomorrowWeekDay := tomorrow.WeekDay()
```

## Motivation
the` func (t Time) Weekday() Weekday` does non-linear calculations (i do take a look at the code and see the logic behind and it is not trivial, and the order of the function could match a binary search  "O(log n)" as the `func (l *Location) lookup(sec int64) (name string, offset int, isDST bool, start, end int64)` may be called during the process (look for `l.lookup(sec)` in [time.Time source file](https://golang.org/src/time/time.go))  that could be simplified **in the context of iterating through weekdays in a circular fashion** (either forward or backward).

## Possible Solution

```
// Gets the next week day, following golang time.WeekDay values convention
func next(day time.Weekday) time.Weekday {
	return time.Weekday((int(day) + 1) % 7)
}
```
The above was my implementation that works on my project. 
As the language specs forbids: i can't use WeekDay as type receiver, thus, extending and binding the functionality to the concrete type; so i resort to write my own utility func.

## Additional Test Code
```
func TestNextWeekDayWorks(t *testing.T) {
	// an entire loop over the week is enought to prove it works as it cover all posible values
	sunday := time.Sunday
	monday := getNextAndAssert(t, sunday, time.Monday)
	tuesday := getNextAndAssert(t, monday, time.Tuesday)
	wednesday := getNextAndAssert(t, tuesday, time.Wednesday)
	thursday := getNextAndAssert(t, wednesday, time.Thursday)
	friday := getNextAndAssert(t, thursday, time.Friday)
	saturday := getNextAndAssert(t, friday, time.Saturday)
	getNextAndAssert(t, saturday, time.Sunday)
}

func getNextAndAssert(t *testing.T, currentDay time.Weekday, expectedNextDay time.Weekday) (calculatedNextDay time.Weekday) {
	calculatedNextDay = next(currentDay)
	if calculatedNextDay != expectedNextDay {
		t.Errorf("Not equals.\nCalculated is: '%v', while expected is: '%v'", calculatedNextDay, expectedNextDay)
	}
	return
}
```

## Context
My motivation arises for two reasons: 

1. by beign working with medical agendas that have plenty of relative time intervals (e.g: per day of week availability), and when the times comes to calculate the actual availabilties in a given lapse of time (**that are consecutive days**) i do find proper to work with `time.WeekDay` type in order to retrieve the relative availability information for the correspondent day.
2. I would like to think that other persons already face or faced this scenario, i mean: to face the need of sequentially iterate over week days starting from a given absolute time.
3. Need to be aware of golang convetion changes for days in a week concrete integer values.

I would love to receive some feedback about this including other professional's point of views.
Thanks and hope you find useful something of what i have just share.

**Comment by cznic** [comment] 2018-05-20 18:17
The behavior I infer from the "Possible Solution" is simple modular arithmetic and it's directly supported by the language with no need for conversions: https://play.golang.org/p/v6XOucCpgUW.

Also, I don't see enough value in having the two special cases, `prev` and `next`, explicitly handled by extra functions/methods of the `time` package.

**Comment by Vitucho** [comment] 2018-05-21 05:25
anyway, my intentions were only to cooperate. I will appreciate a "thanks" regardless if the golang team decide to include it or not.

**Comment by Vitucho** [comment] 2018-05-21 05:29
func prevWeekday(d time.Weekday) time.Weekday { return (d - 1) % 7 }
func nextWeekday(d time.Weekday) time.Weekday { return (d + 1) % 7 }

and please, you want to every person write these two functions over and over again?

**Comment by Vitucho** [comment] 2018-05-21 05:30
is not my way of feel how we must avoid to rebuild the whell

**Comment by Vitucho** [comment] 2018-05-21 05:44
as a system analyst professional i urge you to think that we rely on abstractions in order build bigger system... nextWeekday and prevWeekday are part of those abstractions... after all, to implement a function like that in golang i have study before the golang convention for weekdays values and take me time, i only want to spare some time to other. Just try to stay focus on our natural task cznic, build abstrations, the right ones.

**Comment by cznic** [comment] 2018-05-21 15:18
FTR

```go
today := time.Now()
tomorrow := today.Add(time.Duration(24) * time.Hour) // adds a day duration
tomorrowWeekDay := tomorrow.WeekDay()
```
is not a correct solution of the problem.

**Comment by Vitucho** [comment] 2018-05-21 15:36
i believe it works fine (and it does in prod) https://play.golang.org/p/lxbPySc8amm... i encourage you to explain why this is not a correct solution.

**Comment by cznic** [comment] 2018-05-21 16:51
The duration between weekday changes is not fixed at 24 hours in the general case.

**Comment by bcmills** [comment] 2018-05-21 17:10
See also https://github.com/golang/go/issues/19700.

**Comment by bcmills** [comment] 2018-05-21 17:26
As @cznic notes, you can already iterate over weekday constants using the usual mathematical operators, and the expression `(d + 1) % 7` is not much boilerplate at all: you don't even need a function to abstract over it. For the general case, the combination of [`(time.Time).AddDate`](https://tip.golang.org/pkg/time/#Time.AddDate) and [`(time.Time).Weekday`](https://tip.golang.org/pkg/time/#Time.Weekday) also allow for iteration by arbitrary numbers of days.

For the specific problem of iterating over sequential days, this proposal doesn't seem to carry its weight: it would add API surface for trivial mathematical operations. For less-trivial use-cases, #19700 proposes a more comprehensive API. I'm closing this issue as a duplicate of that one.

**Closed by bcmills** 2018-05-21 17:26 UTC

**Comment by Vitucho** [comment] 2018-05-21 17:34
bcmills i don't see your point as valid, i would strive to implement it as part of the library (for the reason i put as motivation) but anyway thanks you both (also cznic) for the reading and the feedback.

**Comment by ianlancetaylor** [comment] 2018-05-25 00:43
New API always carries a cost.  If we add a `Next` method to `time.Weekday`, we have to document it and maintain it.  We also probably have to add a `Prev` method.  The code is easy to write yourself, so as bcmills says this doesn't seem to carry its weight.

**Comment by Vitucho** [comment] 2018-05-28 12:44
thanks for the reply ianlancetaylor. Allow me to highlight a previous question

> ¿do you want every person (in evey project) write these two pair of functions?

```
func prevWeekday(d time.Weekday) time.Weekday { return (d - 1) % 7 }
func nextWeekday(d time.Weekday) time.Weekday { return (d + 1) % 7 }
```

I mean, i know that is very light work to do, but as far i stated this could be a problem to more than one client of the library, so, the question i would make myself as client of the library is _¿why delegate the weigth to each client instead of putting it in a single place (like the "time" library) and once for all?_. 
I know is work to do and impacts on augmenting the complexity (just a bit, ok! is a bit and is annoying perhaps you may say) of the library; so that is why at first place my proposal was formally expressed among with a helpful (i hope) snippet of code. To recap: The "complexity exists, and it shall be encapsulated in a layer. Is not an easy matter, it can has  a lot of discussion, going and backs, it depends on the work team.

**Comment by cznic** [comment] 2018-05-28 13:30
Encapsulation of complex expression and/or logic often makes sense. Encapsulating trivial expressions (two operators, single non-constant operand) not so much.

There is probably a lot if similar one-liners out there. Never will they all end in the stdlib, so someone must decide where to draw the line.

**Comment by Vitucho** [comment] 2018-05-28 18:35
So we all recognize that the complexity exists and is fact (regardless the level of complexity). 
If we put this in  "client"/"server" terms: as *a client* you understand that i would strive for the "server" to implement it (and releases me from the _burden_ that it takes), and i know that this is work for you by relieving me from do it. Allow me to add that i have already make the work, so you can imagine that this doens't release me from anything at this time, but i understand, and very weel, of the importance of this decision.

I see that neither any of my motivations (explained in the **Motivations** and **Context** Sections) is not enough to promote this "issue/request" to a "nice to have feature". I have interest of knowing what do you think of each of one of them, without any rush to answer, of course.

I do not know with how many work you have to deal with day by day, but for a start i will assume that is a lot. So I don't want to be annoying with this, and, if i'm about to be it,  please excuse me. Thanks

**Comment by ianlancetaylor** [comment] 2018-05-28 18:59
I think I would summarize your motivations and contents as saying that these new methods would be useful.  I agree.  Nobody would propose ideas that aren't useful.

From my perspective, every change has both a benefit and a cost.  We make changes where the benefit is larger than the cost.  You've discussed the benefit.  The various replies to you above discuss the cost.

In other words, we agree about the benefits you've mentioned.  Where we disagree is whether the benefits are worth the cost.

**Comment by Vitucho** [comment] 2018-05-28 21:12
And let me add that I believe that you guys are the ones that know the ** tradeoff ** of this, i mean, the ** cost ** and the ** benefits **. I guess don't need me to say anything else.

Thanks ian, for your feedback, it was very useful to me in order to understand more what is really the _matter_ here, and therefore the _thing_ that, perhaps, may be put on the table for discussion someday.
