### ISSUE TITLE
cmd/go: `go mod verify` seems to be confused by go.work files

### ISSUE THREAD

**Issue by pjweinb** [golang/go#65825] opened 2024-02-20 20:16 UTC
### Go version

go version go1.22-20240109-RC01 cl/597041403 +dcbe772469 X:fieldtrack,boringcrypto linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/usr/local/google/home/pjw/.cache/go-build'
GOENV='/usr/local/google/home/pjw/.config/go/env'
GOEXE=''
GOEXPERIMENT='loopvar'
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/usr/local/google/home/pjw/gostuff/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/usr/local/google/home/pjw/gostuff'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/google-golang'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/google-golang/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22-20240109-RC01 cl/597041403 +dcbe772469 X:fieldtrack,boringcrypto'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/usr/local/google/home/pjw/tools/go.mod'
GOWORK='/usr/local/google/home/pjw/tools/go.work'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2060330091=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Download the x/tools repository. Create a go.work file: go work init . ./gopls
Run go mod verify and get
golang.org/x/tools/gopls : missing ziphash: open hash: no such file or directory

### What did you see happen?

Got an error message.

### What did you expect to see?

If the go.work file is removed, then go mod verify says "all modules verified", which is what one would expect.

**Comment by bcmills** [comment] 2024-02-20 20:33
Duplicate of #62663

**Closed by bcmills** 2024-02-20 20:33 UTC
Labels: GoCommand, modules
