### ISSUE TITLE
os/signal: TestSignalTrace failures on linux-ppc64* with "timeout … waiting for hangup"

### ISSUE THREAD

**Issue by bcmills** [golang/go#45773] opened 2021-04-26 14:21 UTC
[2021-04-23T21:48:37-9cc3469/linux-ppc64le-buildlet](https://build.golang.org/log/332a71f151830bd58ed7009cff4c61975a34817f)
[2021-04-23T21:43:10-bf92160/linux-ppc64-buildlet](https://build.golang.org/log/355bee4aee0c4e1ef780304857b744360ddd57a8)
[2021-04-23T21:43:08-a25d1d4/linux-ppc64-buildlet](https://build.golang.org/log/170aa4cf219ed25d63a19d6e291d06d4f63c38f1)
[2021-04-22T22:01:47-7405968/linux-ppc64-buildlet](https://build.golang.org/log/0a846084f85dd4f951a6d5e6852809d37a8db78f)
[2021-04-22T21:23:59-f7afdfd/linux-ppc64-buildlet](https://build.golang.org/log/507f6b22273d3c3a4f71ae8067bbc9e1d89ba875)
[2021-04-22T21:23:59-f7afdfd/linux-ppc64le-buildlet](https://build.golang.org/log/62b4155665c63aea6fb213e75e73d67188da7f08)
[2021-04-22T04:04:47-ece5935/linux-ppc64-buildlet](https://build.golang.org/log/8537395b1b39eea557e4e753cf394a3d2f8d8124)
[2021-04-21T23:21:55-7bedd47/linux-ppc64-buildlet](https://build.golang.org/log/b79aefa858668d4e782196052ed03e5a2ff53721)
[2021-04-21T21:25:26-7e97e4e/linux-ppc64-buildlet](https://build.golang.org/log/af020e820c4b20d921d6cae1363756047d6551fd)

```
--- FAIL: TestSignalTrace (0.43s)
    signal_test.go:880: timeout after 200ms waiting for hangup
FAIL
FAIL	os/signal	6.243s
```

CC @ianlancetaylor @laboger @ceseo

**Comment by laboger** [comment] 2021-04-26 15:24
Interesting that these started after https://go-review.googlesource.com/c/go/+/305149/ was merged.

FYI  replace @pmur for @ceseo for notification of ppc64x issues. Thanks.

**Comment by pmur** [comment] 2021-04-26 19:16
I tested this on an older POWER8/Ubuntu 16/ppc64le machine. I see this failure before and after this patch (I backported the test with it). Notably, the failing test was added in this commit. This test seems to hiccup on the failing machine, taking 6-7x or longer on some runs.

I can't reproduce on most other P8/P9 machines though.

**Comment by bcmills** [comment] 2021-04-28 13:28
Marking as release-blocker for Go 1.17 because this test is new as of 1.17.

(CC @golang/release)

**Comment by bcmills** [comment] 2021-04-28 13:29
[2021-04-28T12:51:42-f68878f/linux-ppc64-buildlet](https://build.golang.org/log/acda616d11bffadcd89086618376da18e53b5342)
[2021-04-27T21:16:55-30002e6/linux-ppc64le-buildlet](https://build.golang.org/log/6a4f9e72a92623dd1ef62a0d30c62545ab078281)
[2021-04-27T19:18:02-8ab7064/linux-ppc64-buildlet](https://build.golang.org/log/fc64dbf7c863ba56396da88aac0160d7579e401e)
[2021-04-27T17:03:53-074a49b/linux-ppc64-buildlet](https://build.golang.org/log/82c692e8a393399804f1030c613af5c2fc3926ab)
[2021-04-27T02:39:52-434e12f/linux-ppc64le-buildlet](https://build.golang.org/log/84780e0df8c7637e596680c9384eb6ffb5646861)
[2021-04-26T21:35:26-be28caf/linux-ppc64-buildlet](https://build.golang.org/log/84a57783929d4c9f0a31450beb1215ce90823eed)
[2021-04-26T21:35:26-be28caf/linux-ppc64le-buildlet](https://build.golang.org/log/d1a0ec9d4077a895915e3fb82b6ed76dccedb2d3)

**Closed** 2021-05-04 17:38 UTC
Labels: NeedsInvestigation, arch-ppc64x, okay-after-beta1, release-blocker
