### ISSUE TITLE
go clean -i -r breaks go vet vet: import failed: can't find import: fmt

### ISSUE THREAD

**Issue by mmatczuk** [golang/go#19129] opened 2017-02-16 21:27 UTC
After running `go clean -i -r ./...` `go vet` breaks, please find the steps to reproduce below

    mmatczuk:gotest$ tar xzf ~/downloads/go1.7.5.linux-amd64.tar.gz 
    mmatczuk:gotest$ mkdir gopath
    mmatczuk:gotest$ export GOROOT=$PWD/go
    mmatczuk:gotest$ export GOPATH=$PWD/gopath
    mmatczuk:gotest$ export PATH=$GOROOT/bin:$PATH
    mmatczuk:gotest$ go version
    go version go1.7.5 linux/amd64
    mmatczuk:gotest$ go get github.com/mmatczuk/go-http-tunnel/...
    mmatczuk:gotest$ cd gopath/src/github.com/mmatczuk/go-http-tunnel/
    mmatczuk:go-http-tunnel$ go vet ./...
    mmatczuk:go-http-tunnel$ go clean -i -r ./...
    mmatczuk:go-http-tunnel$ go vet ./...
    vet: import failed: can't find import: fmt
    vet: import failed: can't find import: fmt
    exit status 1
    vet: import failed: can't find import: fmt
    vet: import failed: can't find import: fmt
    exit status 1
    vet: import failed: can't find import: fmt
    vet: import failed: can't find import: fmt
    exit status 1
    vet: import failed: can't find import: fmt
    vet: import failed: can't find import: fmt
    exit status 1
    vet: import failed: can't find import: fmt
    vet: import failed: can't find import: fmt
    exit status 1
    vet: import failed: can't find import: fmt
    vet: import failed: can't find import: fmt
    exit status 1
    vet: import failed: can't find import: fmt
    vet: import failed: can't find import: fmt
    exit status 1
    vet: import failed: can't find import: fmt
    vet: import failed: can't find import: fmt
    exit status 1
    vet: import failed: can't find import: fmt
    vet: import failed: can't find import: fmt
    exit status 1
    mmatczuk:go-http-tunnel$ go install ./...
    mmatczuk:go-http-tunnel$ 

cc: @griesemer

**Comment by griesemer** [comment] 2017-02-16 21:45
Duplicate of #11415.

**Closed by griesemer** 2017-02-16 21:45 UTC
