### ISSUE TITLE
Implicit type conversion failure

### ISSUE THREAD

**Issue by utpal74** [golang/go#67788] opened 2024-06-03 14:25 UTC
### Go version

go version go1.22.3 windows/amd64

### Output of `go env` in your module/workspace:

```shell
Set GO111MODULE=
set GOARCH=amd64
set GOBIN=C:\Users\utpal\go\bin
set GOCACHE=C:\Users\utpal\AppData\Local\go-build
set GOENV=C:\Users\utpal\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\utpal\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\utpal\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\utpal\go\src\learn-go-with-tests\wallet\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\utpal\AppData\Local\Temp\go-build3300580940=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

Checkout the main function where Deposit method call accepts direct int value rather than Explicitly converted value. 

```
package main

import "fmt"

type Bitcoin int

type Wallet struct {
	balance Bitcoin
}

func (w *Wallet) Deposit(amount Bitcoin) {
	w.balance = amount
}

func main() {
	w := Wallet{}
	w.Deposit(100)
	fmt.Println(w.balance)
}
```

### What did you see happen?

Code runs fine.

### What did you expect to see?

I didn't expect the above code to compile, since implicit type conversion is not a feature of Go , but in this case how come this is working.

**Comment by mknyszek** [comment] 2024-06-03 15:23
Untyped integer constants like `100` are [assignable](https://go.dev/ref/spec#Assignability) to types that have an integral underlying type. There's not really an implicit conversion here in the way other languages define them, and it's certainly not unsafe in the same way. Untyped integer constants have effectively infinite precision, but you'll get a compile error if you try to assign an untyped integer constant into a value whose type can't fit the number (for example, `uint8(257)` will fail at build time).

I believe this is all working as intended. Closing this issue.

**Closed by mknyszek** 2024-06-03 15:23 UTC
