### ISSUE TITLE
proposal: net: separate net.Dialer Resolver into a Interface

### ISSUE THREAD

**Issue by Jack-Kingdom** [golang/go#65275] opened 2024-01-25 08:21 UTC
### Proposal Details

Resolver in net.Dialer is a struct, I found its hard to custom dns request for doh (dns over https) or dot (dns over tls).

<img width="544" alt="Screen Shot 2024-01-25 at 4 11 51 PM" src="https://github.com/golang/go/assets/10584772/6e9df109-6c27-4672-8ce2-915f5f2723e6">

<img width="664" alt="Screen Shot 2024-01-25 at 4 15 16 PM" src="https://github.com/golang/go/assets/10584772/b34eb3ef-5dd7-4554-92a0-ebf886a911d6">

We can wrap Resolver into a interface, so that everyone could implement their own dns handle procedure

**Comment by mateusz834** [comment] 2024-01-25 08:59
What API changes are you proposing here?

**Comment by seankhliao** [comment] 2024-01-25 10:39
Duplicate of #12503

**Closed by seankhliao** 2024-01-25 10:39 UTC
Labels: Proposal, WaitingForInfo
