### ISSUE TITLE
Go 1.13: flag provided but not defined: -test.timeout

### ISSUE THREAD

**Issue by eclipseo** [golang/go#33475] opened 2019-08-05 17:56 UTC
Following https://github.com/golang/go/issues/28147, I'm encountering this error with  github.com/karlseguin/ccache on 1.13 beta 1:

```
Testing    in: /builddir/build/BUILD/ccache-2.0.3/_build/src
         PATH: /builddir/build/BUILD/ccache-2.0.3/_build/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
       GOPATH: /builddir/build/BUILD/ccache-2.0.3/_build:/usr/share/gocode
  GO111MODULE: off
      command: go test -buildmode pie -compiler gc -ldflags "-X github.com/karlseguin/ccache/version=2.0.3 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '"
      testing: github.com/karlseguin/ccache
github.com/karlseguin/ccache
flag provided but not defined: -test.timeout
Usage of /tmp/go-build949920696/b001/ccache.test:
  -m string
    	Regular expression selecting which tests to run
  -vv
    	Regular expression selecting which tests to run
exit status 2
FAIL	github.com/karlseguin/ccache	0.007s
```

I'm not sure how to tackle this, is it an issue with ccache tests or from Go itself?

**Comment by agnivade** [comment] 2019-08-05 18:05
It is likely https://github.com/golang/go/issues/31859. Somewhere in the code, it is calling flag.Parse inside an init() function.

**Comment by bcmills** [comment] 2019-08-05 18:58
@eclipseo, please confirm whether the panic is occurring during package initialization.

**Comment by eclipseo** [comment] 2019-08-05 19:01
I don't see any Init function or flag.Parse in  github.com/karlseguin/ccache

**Comment by bcmills** [comment] 2019-08-05 19:16
Yep, that looks like it. Presumably you'll want to send a PR to fix that dependency (or drop your program's use of it) for 1.13.

**Comment by bcmills** [comment] 2019-08-05 19:16
Duplicate of #31859

**Comment by eclipseo** [comment] 2019-08-05 19:17
Ok, thanks for the help!

**Closed by bcmills** 2019-08-05 19:16 UTC
Labels: WaitingForInfo

**Comment by ORESoftware** [comment] 2020-04-30 23:19
Why would it break in an init() func but not when it's parsed after that?

**Comment by ianlancetaylor** [comment] 2020-05-01 01:29
@ORESoftware This issue is closed.  Also I'm not sure what you are asking.  See the third paragraph in https://golang.org/doc/go1.13#testing.

**Comment by ORESoftware** [comment] 2020-05-01 02:21
see @agnivade comment above dude

**Comment by ianlancetaylor** [comment] 2020-05-01 04:44
@ORESoftware For questions about Go please use a forum: https://golang.org/wiki/Questions.  Thanks.

The answer to your question is, as described at the linked issue #31859, that the testing package defines its flags in `testing.Init`, which will not be run before an `init` function in some other package.  So if an `init` function calls `flag.Parse`, that flag parser will not see the flags used by the testing package.
