### ISSUE TITLE
cmd/compile: regression in TestIntendedInlining on ppc64x, others

### ISSUE THREAD

**Issue by laboger** [golang/go#22239] opened 2017-10-12 20:02 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go tip

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
ppc64le & ppc64

### What did you do?
Noticed consistent failures on the golang.org/build page for ppc64le, ppc64

### What did you expect to see?
No failures

### What did you see instead?
ok  	cmd/compile	4.918s
--- FAIL: TestIntendedInlining (5.03s)
	inl_test.go:210: runtime.nextFreeFast was not inlined: function too complex: cost 113 exceeds budget 80
FAIL
FAIL	cmd/compile/internal/gc	17.646s
2017/10/11 23:22:15 Failed: exit status 1

This started with commit a509cae.

**Comment by randall77** [comment] 2017-10-12 20:05
@mdempsky

**Comment by mdempsky** [comment] 2017-10-12 20:08
The ppc64 failures should be fixed by 53bbddd52724e439c751f445675f3eff5068d523.

The mips64 failures still need to be dealt with though. I think by updating TestIntendedInlining to expect nextFreeFast to not be inlinable on mips64.

**Comment by mvdan** [comment] 2017-10-13 22:04
Likely that we forgot about this nextFreeFast edge case. Is this arch one of those builders that isn't a trybot?

**Comment by mdempsky** [comment] 2017-10-13 22:08
@mvdan Correct, MIPS64 is not a trybot architecture.

The problem is nextFreeFast really is too expensive to inline on MIPS64, because we don't have an optimized version of Ctz64 on that arch. However, because of #19261, we weren't correctly accounting for how expensive Ctz64 is, so we were inlining nextFreeFast anyway.

**Comment by laboger** [comment] 2018-04-05 14:37
This problem is fixed on ppc64x. Not sure how to test mips64x or if that is what you are asking me to investigate. If someone can verify that the mips64x works, I can close it.

**Comment by bcmills** [comment] 2022-03-31 17:28
Is there anything remaining to be done for this issue?

**Closed** 2022-05-01 17:32 UTC
Labels: WaitingForInfo, NeedsInvestigation
