### ISSUE TITLE
pkg.go.dev and index.golang.org have different incorrect versions of the same Go project

### ISSUE THREAD

**Issue by yurivict** [golang/go#46494] opened 2021-06-01 17:35 UTC
* pkg.go.dev shows ```v4.2.3```
* https://index.golang.org/index?limit=1&since=2021-05-28T01:21:42.994935Z returns ```v1.6.1-0.20210527214455```
* Real latest version on https://github.com/concourse/concourse/tags is ```v7.3.1```.

Your own servers (pkg.go.dev and index.golang.org) have to be in agreement. You should have some mechanism to sync these.
GitHub has API to read tag information, so this information can be synced with GitHub.

**Comment by seankhliao** [comment] 2021-06-01 18:00
`+incompatible` is for repos that have not adopted modules (no `go.mod`) The last version this was true for github.com/concourse/concourse is `v4.2.3`
concourse is using modules (`go.mod`) but not versioning in accordance with policy, so the version numbers are [pseudoversions](https://golang.org/ref/mod#pseudo-versions)

pkg.go.dev will only list valid versions, though every pseudoversion is also available if you consttuct the url

closing as this is working as intended

**Closed by seankhliao** 2021-06-01 18:00 UTC

**Comment by yurivict** [comment] 2021-06-01 18:54
> concourse is using modules (go.mod) but not versioning in accordance with policy

What is a problem with their version ```v7.3.1``` ?
