### ISSUE TITLE
go fmt doesn't strip unnecessary parens in make(chan (type))

### ISSUE THREAD

**Issue by smcquay** [golang/go#15807] opened 2016-05-24 00:24 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

`go version go1.6.2 darwin/amd64`

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sm/src/sc"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?

https://play.golang.org/p/cvrTuLUU54

When I run `go fmt` it doesn't remove the superfluous parentheses. A grep of the go source shows that having parens doesn't come up much.

4. What did you expect to see?

When I run `go fmt` I expect it to strip the unnecessary parens.

5. What did you see instead?

parens are left in place.

**Comment by griesemer** [comment] 2016-05-24 00:41
Working as intended.

gofmt deliberately makes no attempt to remove unnecessary parentheses except for reducing multiple parentheses to 1. While in this case it might make sense to reduce it to 0, sometimes an author puts in parentheses deliberately to emphasize nesting. gofmt cannot reasonably make that style decision.

For instance, `(((x + y)))` is simplified to `(x + y)`, but `z := (x + y)` is not further simplified. There's no difference between parentheses around expressions and parentheses around types.

Code like this is extremely uncommon (unless machine-generated perhaps, but then it's also easy to fix on the generator side); and this is the first such complaint in years. Closing.

**Closed by griesemer** 2016-05-24 00:41 UTC

**Comment by minux** [comment] 2016-05-24 01:33
Without -s, gofmt is only supposed to change whitespaces. (I'm not saying
that -s should do this rewrite though.)
