### ISSUE TITLE
runtime: TestDebugCallGC failure on android-amd64-emu

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#35352] opened 2019-11-04 20:21 UTC
https://storage.googleapis.com/go-build-log/aaaad0ee/android-amd64-emu_238d82c2.log from the https://golang.org/cl/205059 TryBot. No hits on greplogs.

```
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
--- FAIL: TestDebugCallGC (0.02s)
    debug_test.go:172: retry _Grunnable
FAIL
exitcode=1FAIL	runtime	73.299s
FAIL
2019/11/04 05:53:44 Failed: exit status 1
2019/11/04 05:53:44 FAILED
```

/cc @eliasnaur

**Comment by FiloSottile** [comment] 2019-11-04 20:21
Also https://storage.googleapis.com/go-build-log/bfb25f4b/android-amd64-emu_ba30e609.log

**Comment by eliasnaur** [comment] 2019-11-04 20:25
Seems like something @aclements would know about. I don't, unfortunately.

**Comment by ianlancetaylor** [comment] 2019-11-05 00:12
https://storage.googleapis.com/go-build-log/b60dc56b/android-amd64-emu_688cd004.log

**Comment by bcmills** [comment] 2019-11-08 16:17
Duplicate of #32985

**Closed by bcmills** 2019-11-08 16:17 UTC
Labels: NeedsInvestigation, OS-Android
