### ISSUE TITLE
increment operation returns wrong result

### ISSUE THREAD

**Issue by janardhan1993** [golang/go#21722] opened 2017-09-01 01:06 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8 linux/amd64

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/janardhan/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build483155133=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
https://play.golang.org/p/ac24AwKKTs

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Count should get incremented by 1

### What did you see instead?
It gets incremented by 2

**Comment by davecheney** [comment] 2017-09-01 01:24
Your program could print 1 or 2. This is not a bug in Go so I am going to close this ticket.

We don't the issue tracker to ask questions. Please see https://golang.org/wiki/Questions for good places to ask. Thanks.

**Closed by davecheney** 2017-09-01 01:24 UTC

**Comment by janardhan1993** [comment] 2017-09-01 06:02
@davecheney: But count gets incremented by 2 every time. I see 2,4,6,8,10. Isn't it a bug in go. From 1.8.1 i see 1,2,3,4,5

**Comment by dominikh** [comment] 2017-09-01 06:23
It can't, but this is a bug in an old version of Go, that was fixed in Go 1.8.1.
