### ISSUE TITLE
affected/package: go fmt command

### ISSUE THREAD

**Issue by ordnko** [golang/go#54310] opened 2022-08-05 23:38 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Oleg.Rudenko\AppData\Local\go-build
set GOENV=C:\Users\Oleg.Rudenko\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\Users\Oleg\go\pkg\mod
set GONOPROXY=git.acronis.com
set GONOSUMDB=git.acronis.com
set GOOS=windows
set GOPATH=D:\Users\Oleg\go
set GOPRIVATE=git.acronis.com
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=C:\cygwin64\bin\x86_64-w64-mingw32-gcc.exe
set CXX=C:\cygwin64\bin\x86_64-w64-mingw32-g++.exe
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2 -s
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\OLEG~1.RUD\AppData\Local\Temp\go-build2258273291=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I formatted golang source file using `go fmt` command. In particular, the following code snippet:
```go
// SetUpRESTAPI sets up REST API over HTTP.
//
// Parameters:
//   options are the REST API initialization options.
func SetUpRESTAPI(options RESTAPIOptions) error {
...
```

### What did you expect to see?
I expected the command does not change this code.

### What did you see instead?
```go
// SetUpRESTAPI sets up REST API over HTTP.
//
// Parameters:
//
//	options are the REST API initialization options.
func SetUpRESTAPI(options RESTAPIOptions) error {
...
```
There are two problems:
1. Extra `//` line was inserted between parameter list header and the first (and in this case the only) parameter description.
2. Spaces between `//` and the parameter description were replaced with tab.

This problem was not observed with `gofmt` from go1.18.

**Comment by seankhliao** [comment] 2022-08-06 00:03
This is part of the new enhanced doc comments, see https://go.dev/doc/comment#code

Closing as working as intended.

**Closed by seankhliao** 2022-08-06 00:03 UTC
