### ISSUE TITLE
proxy.golang.org: invalid pseudo-version: does not match version-control timestamp

### ISSUE THREAD

**Issue by DazWilkin** [golang/go#33530] opened 2019-08-07 18:49 UTC
### What version of Go are you using (`go version`)?

I'm using a build server ([Google Cloud Build](https://cloud.google.com/cloud-build/)) and `golang:1.12.7-buster`

### Does this issue reproduce with the latest release?

Yes, confident that it's proxy related

### What did you do?

For the purposes of testing, artificially constrained:
go.mod:
```
module ${MODULE}

go 1.12

require (
	github.com/google/trillian v1.3.0
)
```

### What did you expect to see?

Successful build; this happens if I set the build's `GOPROXY=direct`

### What did you see instead?

Failed build; this happens if I set the build's `GOPROXY=https://proxy.golang.org` and
```
google.golang.org/genproto@v0.0.0-20170818100345-ee236bd376b0: unexpected status (https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20170818100345-ee236bd376b0.info): 410 Gone
mvdan.cc/unparam@v0.0.0-20190124213536-fbb59629db34: unexpected status (https://proxy.golang.org/mvdan.cc/unparam/@v/v0.0.0-20190124213536-fbb59629db34.info): 410 Gone
github.com/golangci/ineffassign@v0.0.0-20180808204949-42439a7714cc: unexpected status (https://proxy.golang.org/github.com/golangci/ineffassign/@v/v0.0.0-20180808204949-42439a7714cc.info): 410 Gone
github.com/golangci/gosec@v0.0.0-20180901114220-66fb7fc33547: unexpected status (https://proxy.golang.org/github.com/golangci/gosec/@v/v0.0.0-20180901114220-66fb7fc33547.info): 410 Gone
github.com/golangci/go-tools@v0.0.0-20180109140146-af6baa5dc196: unexpected status (https://proxy.golang.org/github.com/golangci/go-tools/@v/v0.0.0-20180109140146-af6baa5dc196.info): 410 Gone
github.com/golangci/errcheck@v0.0.0-20181003203344-ef45e06d44b6: unexpected status (https://proxy.golang.org/github.com/golangci/errcheck/@v/v0.0.0-20181003203344-ef45e06d44b6.info): 410 Gone
github.com/golangci/lint-1@v0.0.0-20180610141402-ee948d087217: unexpected status (https://proxy.golang.org/github.com/golangci/lint-1/@v/v0.0.0-20180610141402-ee948d087217.info): 410 Gone
github.com/go-critic/go-critic@v0.0.0-20181204210945-1df300866540: unexpected status (https://proxy.golang.org/github.com/go-critic/go-critic/@v/v0.0.0-20181204210945-1df300866540.info): 410 Gone
github.com/russross/blackfriday/v2@v2.0.1+incompatible: unexpected status (https://proxy.golang.org/github.com/russross/blackfriday/v2/@v/v2.0.1+incompatible.info): 410 Gone
github.com/golangci/gofmt@v0.0.0-20181105071733-0b8337e80d98: unexpected status (https://proxy.golang.org/github.com/golangci/gofmt/@v/v0.0.0-20181105071733-0b8337e80d98.info): 410 Gone
```
Which appear to (all) be:
```
invalid pseudo-version: does not match version-control timestamp
```
This may indeed be accurate but my solution is to avoid using the proxy :-(

**Comment by bcmills** [comment] 2019-08-07 19:05
See https://tip.golang.org/doc/go1.13#version-validation for workarounds.

**Comment by bcmills** [comment] 2019-08-07 19:06
Duplicate of #32805

**Closed by bcmills** 2019-08-07 19:06 UTC
