### ISSUE TITLE
cmd/link, reflect: regression in reflect.Method output

### ISSUE THREAD

**Issue by dsnet** [golang/go#15724] opened 2016-05-18 00:30 UTC
Commit 44d3f89e99b954d88ab802212182a7c123ac774a caused a regression in the reflect package where-by some of the fields of the reflect.Method would be nil or invalid.

Consider the following program:
```go
type Foo interface{}
type Bar struct{}

func (s *Bar) getFoo() Foo { return nil }

func main() {
	t := reflect.ValueOf(&Bar{}).Type()
	fmt.Println(t.Method(0))
}
```

On `go1.6`, this would print:
`{getFoo main func(*main.Bar) main.Foo <func(*main.Bar) main.Foo Value> 0}`

After 44d3f89e99b954d88ab802212182a7c123ac774a, this would print:
`{getFoo main <nil> <invalid Value> 0}`

/cc @crawshaw @randall77 @ianlancetaylor

**Comment by randall77** [comment] 2016-05-18 00:42
@mdempsky

**Comment by crawshaw** [comment] 2016-05-18 12:05
This looks like a duplicate of #15673.

**Closed by crawshaw** 2016-05-18 12:05 UTC
