### ISSUE TITLE
x/pkgsite: cs.opensource.google does not offer ZIP download

### ISSUE THREAD

**Issue by 4cq2** [golang/go#60699] opened 2023-06-08 23:28 UTC
### What is the URL of the page with the issue?

https://pkg.go.dev/golang.org/x/tools
 
### What is your user agent?
 
Mozilla Firefox
 
### What did you do?

if you visit the page, you are presented with this URL:

https://cs.opensource.google/go/x/tools

### What did you expect to see?
 
A link to download ZIP or TAR.GZ
 
### What did you see instead?

for the life of me, I cannot see a method to actually download the repository source code. With GitHub, its very easy. You go here:

https://github.com/golang/tools

click Code, Download ZIP, and you get this:

https://github.com/golang/tools/archive/refs/heads/master.zip

does the `opensource.google` site really not have a way to download the source code? I think `opensource.google` should have a method to do this (if it doesnt already) or the documentation should point to GitHub instead.

**Comment by seankhliao** [comment] 2023-06-08 23:44
The site is linked for code searching, the source repositories are the ones from go.googlesource.com

Closing as working as intended.

**Closed by seankhliao** 2023-06-08 23:44 UTC
Labels: pkgsite
