### ISSUE TITLE
proposal: io: add LimitWriter

### ISSUE THREAD

**Issue by carlmjohnson** [golang/go#54548] opened 2022-08-19 14:35 UTC
In #51115, a proposal to add an error field to `io.LimitedReader` was accepted, but then the change was reverted when it turned out to have some tricky corner cases around the last byte.

As a new proposal, which may or may not supersede the change to `io.LimitedReader`, I suggest adding an `io.LimitWriter` function with approximately this implementation:

```go
func LimitWriter(w io.Writer, limit int64, err error) io.Writer {
	return &limitedWriter{w, limit, err}
}

type limitedWriter struct {
	w io.Writer
	n int64
	e error
}

func (lw *limitedWriter) Write(p []byte) (int, error) {
	if lw.n < 1 {
		return 0, lw.e
	}
	if lw.n < int64(len(p)) {
		p = p[:lw.n]
	}
	n, err := lw.w.Write(p)
	lw.n -= int64(n)
	return n, err
}
```

**Comment by seankhliao** [comment] 2022-08-19 14:39
Duplicate of #54111

**Closed by seankhliao** 2022-08-19 14:39 UTC
Labels: Proposal
