### ISSUE TITLE
cmd/compile: spurious "cannot use _ as value" error

### ISSUE THREAD

**Issue by adonovan** [golang/go#15481] opened 2016-04-28 18:31 UTC
go version devel +af125a5 Thu Apr 28 17:56:28 2016 +0000 linux/amd64

https://play.golang.org/p/O_WijGjKJ7

**Comment by rsc** [comment] 2016-05-17 13:40
It has been this way since as far back as Go 1.2. Doesn't matter for Go 1.7, and arguably low enough priority not for Go 1.8 either.

**Comment by odeke-em** [comment] 2016-11-23 09:56
Interestingly a permutation of the code in the bug report
https://play.golang.org/p/hz5ePuCDlF
```go
package main

type m map[string]string

var _ = map[string]string{}       // ok
var _ = map[string]string{"": ""} // ok

func main() {
	var _ = map[string]string{}           // ok
	var _ = map[string]bool{}             // ok
	var _ = map[string]string{"a": "A"}   // error: cannot use _ as value
	var _ = map[string]bool{"true": true} // error: cannot use _ as value
}
```

might allude to where the bug is:
+ only within a function/closure
+ objects of the same type whose left hand hand side identifier is `_`.

Sorry for the noise, was just marking bugs I wanna take a stab at for Go1.9.

**Comment by shurcooL** [comment] 2017-05-24 21:39
I ran into this as well in #20484.

This also affects struct literals:

```Go
package main

var _ = int(5)           // ok
var _ = struct{ int }{}  // ok
var _ = struct{ int }{5} // ok

func main() {
	_ = int(5)               // ok
	_ = struct{ int }{}      // ok
	_ = struct{ int }{5}     // ok
	var _ = int(5)           // ok
	var _ = struct{ int }{}  // ok
	var _ = struct{ int }{5} // cannot use _ as value
}
```

https://play.golang.org/p/xpsxF1WC8z

The common theme seems to be that it cannot be in package scope, it has to be a `var _ =` rather than `_ =`, and the composite literal must be not empty.

**Comment by griesemer** [comment] 2017-06-08 22:05
Moving to 1.10. There are work-arounds if this is important (perhaps in tests) and it has been like this for a long time. Should be fixed a part of the front-end rewrite.

**Comment by ainar-g** [comment] 2017-10-02 23:01
Another interesting example I've found:

```go
var a = map[float64]int{math.NaN(): 42} // Works.
var _ = map[float64]int{42: 42}         // Works.
var _ = map[float64]int{math.NaN(): 42} // Error.
```

**Comment by smasher164** [comment] 2017-12-31 20:35
Is the following behavior correct in the context of a type in a function declaration?
```Go
package main

func fn(v _) {} // cannot use _ as value

func main() {}
```

**Comment by ianlancetaylor** [comment] 2018-01-02 03:52
@smasher164 Yes, the error message is fairly bad.  It would be nice to get a better error message here.  I'm not sure it's quite the same as the other cases in this issue, but it's similar.

**Comment by griesemer** [comment] 2018-06-04 22:40
Too late for 1.11.

**Comment by griesemer** [comment] 2018-09-05 22:56
Simpler reproducer:
```Go
package p

type E struct {
	f func()
}

var _ = E{func() {}}
```

**Comment by go101** [comment] 2018-10-28 01:51
This is okay.
```golang
var _ = map[bool]int{"aaa" != "": 1, false: 0}
```

This is not.
```golang
var _ = map[bool]int{"aaa"[:] != "": 1, false: 0}
```

**Comment by griesemer** [comment] 2022-03-18 04:14
These errors are gone with Go 1.18. Closing.

**Closed by griesemer** 2022-03-18 04:14 UTC
Labels: NeedsFix, early-in-cycle
