### ISSUE TITLE
x/tools/goimports BUG: extra blank line after formatting

### ISSUE THREAD

**Issue by ban11111** [golang/go#53997] opened 2022-07-22 11:12 UTC
### What version of Go Tool are you using (`go tool version`)?

<pre>
 golang.org/x/tools  v0.1.11
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?
for example, when there are:
```golang
import (
    "golang.org/x/tools/imports"
    "testing"
    "fmt"

    "github.com/xx/yy"
    "github.com/aa/bb"
)
```
simply run goimports formating the file

### What did you expect to see?
after formatting:
```golang
import (
    "fmt
    "testing"

    "github.com/xx/yy"
    "github.com/aa/bb"
    "golang.org/x/tools/imports"
)
```

### What did you see instead?
after formatting:
```golang
import (
    "fmt
    "testing"

    "golang.org/x/tools/imports"

    "github.com/xx/yy"
    "github.com/aa/bb"
)
```

**Comment by rsc** [comment] 2022-07-22 14:43
I don't believe this is a bug. There is no rule that imports should only have at most two blocks. Goimports moves non-std imports out of the std section, but it does not (nor should it) presume that they belong in some other existing section. Instead it creates a new one.

**Comment by seankhliao** [comment] 2022-07-22 20:39
Duplicate of #20818

**Closed by seankhliao** 2022-07-22 20:39 UTC
Labels: NeedsInvestigation, Tools
