### ISSUE TITLE
cmd/compile: failed to build github.com/hashicorp/cap/oidc due to internal compiler error: unexpected Defn:

### ISSUE THREAD

**Issue by johejo** [golang/go#45743] opened 2021-04-24 06:17 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.17-e7db792fc5 Fri Apr 23 22:31:20 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

No, gotip only.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/johejo/.cache/go-build"
GOENV="/home/johejo/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/johejo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/johejo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/johejo/ghq/github.com/golang/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/johejo/ghq/github.com/golang/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.17-e7db792fc5 Fri Apr 23 22:31:20 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/johejo/ghq/github.com/hashicorp/cap/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1677903244=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
git clone https://github.com/hashicorp/cap.git
cd cap/
gotip build ./...
```

### What did you expect to see?

Build succeds

### What did you see instead?

<details>

```
# github.com/hashicorp/cap/oidc
oidc/options.go:35:9: internal compiler error: unexpected Defn:
.   TYPESW Used # options.go:34
.   TYPESW-Tag
.   .   NONAME-oidc.v # options.go:34
.   .   NAME-oidc.o tc(1) Class:PPARAM Offset:0 OnStack Used INTER-interface {} # options.go:30

goroutine 1 [running]:
runtime/debug.Stack()
        /home/johejo/ghq/github.com/golang/go/src/runtime/debug/stack.go:24 +0x65
cmd/compile/internal/base.FatalfAt({0x44c754, 0x0}, {0xd2be1a, 0xd136e0}, {0xc0007de650, 0xc0007de660, 0x1})
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/base/print.go:227 +0x157
cmd/compile/internal/inline.(*inlsubst).clovar(0xc000115860, 0x0)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:1198 +0x3c8
cmd/compile/internal/inline.(*inlsubst).closure(0xc000115860, 0xc00066afa0)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:1257 +0x465
cmd/compile/internal/inline.(*inlsubst).node(0xc000115860, {0xe87a90, 0xc00066afa0})
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:1417 +0x3e5
cmd/compile/internal/ir.(*ConvExpr).editChildren(0xc000744000, 0xc00078c5b0)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/ir/node_gen.go:445 +0x58
cmd/compile/internal/ir.EditChildren(...)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/ir/visit.go:185
cmd/compile/internal/inline.(*inlsubst).node(0xc000115860, {0xe87db0, 0xc00066af00})
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:1423 +0xacc
cmd/compile/internal/inline.(*inlsubst).list(0xc00066ae60, {0xc000683260, 0x1, 0xc0007dee50})
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:1133 +0xbe
cmd/compile/internal/inline.(*inlsubst).node(0xc000115860, {0xe89138, 0xc00066ae60})
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:1379 +0xdd0
cmd/compile/internal/inline.(*inlsubst).list(0xc00010f440, {0xc0006831d0, 0x1, 0xc0001466e0})
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:1133 +0xbe
cmd/compile/internal/inline.mkinlcall(0xe88c88, 0xc0003ac680, 0x5adaca, 0xc0006f54a0, 0x5c0e69)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:1012 +0x21e8
cmd/compile/internal/inline.inlnode({0xe87838, 0xc00062fef0}, 0xe87450, 0xc0006361e0, 0x0)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:654 +0x586
cmd/compile/internal/inline.InlineCalls.func1({0xe87838, 0xc00062fef0})
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:541 +0x31
cmd/compile/internal/ir.editNodes({0xc000449a40, 0x3, 0xc00063a000}, 0xc000498540)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/ir/node_gen.go:1449 +0x74
cmd/compile/internal/ir.(*CallExpr).editChildren(0xc00063a000, 0xc000498540)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/ir/node_gen.go:276 +0xb4
cmd/compile/internal/ir.EditChildren(...)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/ir/visit.go:185
cmd/compile/internal/inline.inlnode({0xe87838, 0xc00063a000}, 0x6325a0, 0xc000636be0, 0xc000406d00)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:620 +0x2ac
cmd/compile/internal/inline.InlineCalls.func1({0xe87838, 0xc00063a000})
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:541 +0x31
cmd/compile/internal/ir.editNodes({0xc000060f60, 0x1, 0xc000633020}, 0xc000498540)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/ir/node_gen.go:1449 +0x74
cmd/compile/internal/ir.(*AssignListStmt).editChildren(0xc000633020, 0xc000633020)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/ir/node_gen.go:108 +0x6e
cmd/compile/internal/ir.EditChildren(...)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/ir/visit.go:185
cmd/compile/internal/inline.inlnode({0xe872c0, 0xc000633020}, 0x30, 0x7ffacd6e8c10, 0x20)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:620 +0x2ac
cmd/compile/internal/inline.InlineCalls.func1({0xe872c0, 0xc000633020})
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:541 +0x31
cmd/compile/internal/ir.editNodes({0xc0000aae00, 0x1f, 0xcc6a40}, 0xc000498540)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/ir/node_gen.go:1449 +0x74
cmd/compile/internal/ir.(*Func).editChildren(0xe89138, 0xc000636c30)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/ir/func.go:152 +0x2e
cmd/compile/internal/ir.EditChildren(...)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/ir/visit.go:185
cmd/compile/internal/inline.InlineCalls(0xc000490e60)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:543 +0xf2
cmd/compile/internal/inline.InlinePackage.func1({0xc000490e60, 0x1, 0xc000147e40}, 0x0)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:71 +0x46
cmd/compile/internal/ir.(*bottomUpVisitor).visit(0xc0005ac3f0, 0xc0005b0c60)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/ir/scc.go:128 +0x2e8
cmd/compile/internal/ir.VisitFuncsBottomUp({0xc000790000, 0x122, 0xb}, 0xd4e478)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/ir/scc.go:60 +0x105
cmd/compile/internal/inline.InlinePackage()
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/inline/inl.go:58 +0x33
cmd/compile/internal/gc.Main(0xd4e348)
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/internal/gc/main.go:229 +0xc1b
main.main()
        /home/johejo/ghq/github.com/golang/go/src/cmd/compile/main.go:55 +0xdd
```
</details>

**Comment by johejo** [comment] 2021-04-24 06:29
Minimal reproduction

```go
package main

type opt func(interface{})

type a struct {
	s0 []string
	s1 []string
	f  func() t
}

type b struct {
	s0 []string
	s1 []string
	f  func() t
}

type t struct {
	wall uint64
	ext  int64
	t    *t
}

func fn(f func() t) opt {
	return func(o interface{}) {
		switch v := o.(type) {
		case *a:
			v.f = f
		case *b:
			v.f = f
		}
	}
}

func test(opt) {}

func main() {
	test(fn(func() t { return t{} }))
}
```

**Comment by ALTree** [comment] 2021-04-24 07:18
Thanks for reporting this, and for the minimized reproducer. 

I've bisected this to d310b2a6b8a66eeb5953b1e682cf27669c8a08c2.

cc @cuonglm @mdempsky

**Comment by mdempsky** [comment] 2021-04-24 09:24
Thanks for the test case and bisection. This was already incorrectly handled before d310b21, but that commit added additional internal checks which are failing on this test case.

It looks like we need to extend the AssignStmt/AssignListStmt rewriting to also handle SwitchStmt+TypeSwitchGuard. I uploaded a partial fix for this at golang.org/cl/313289, but I'm suspicious because it's finding switch variables with `Defn == nil`. That makes me suspect there are still more cases where variables within closures aren't being cloned correctly.

/cc @danscales

**Comment by danscales** [comment] 2021-04-26 05:10
@mdempsky  I think that the non-setting of Defn is unrelated to closures.  The nil value for Defn is happening for functions without any closures (for example, when inlining os.underlyingError).  I debugged it a bit, and see that Defn is not being set at all in inlvar(), even if the input node var_ has var_.Defn set.  So, when the name nodes for the per-case variables (named 'err' in the example of os.underlyingError) in the Dcl list are copied during inlining via inlvar, they are not getting their Defn set.  Not quite sure why this isn't causing problems, or whether this glitch was a result of the big re-factoring.

**Comment by cuonglm** [comment] 2021-04-26 05:21
@danscales is that also the reason we have the `case nil: // ok` for `Defn` in `clovar`?

**Comment by danscales** [comment] 2021-04-26 15:35
@cuonglm, Besides the possible bug in inlvar(), I think nameNode.Defn can be legitimately nil for param name nodes.

**Comment by cuonglm** [comment] 2021-04-26 15:49
@danscales Hmm, I see for param name nodes, we always set it Defn in `inlParam`, what did I miss?

I see inlvar behavior seems correct, we don't want new node Defn point to the same Defn with old node, we want it point to the right node in inlined form (that's https://github.com/golang/go/commit/d310b2a6b8a66eeb5953b1e682cf27669c8a08c2 for).

**Comment by danscales** [comment] 2021-04-26 16:29
Yes, but for parameters of normal functions (i.e. not in the process of being inlined), nameNode.Defn is not set (because there is no assignment to refer back to for a function input parameter).

**Comment by mdempsky** [comment] 2021-04-26 17:13
`Defn` can be legitimately nil for some variables, but it should always be set for variables declared in a type switch. It looks like this may be a preexisting issue with inlining, that `inlvar` just leaves `Defn` nil and it doesn't always get filled in later. That's really iffy to me, but it hasn't caused obvious problems, and it's probably too late to try to fix for this dev cycle.

Probably it's enough for now to just change `clovar` to recognize that `*ir.TypeSwitchGuard` is a valid type that `n.Defn` might have and leave `m.Defn` nil like we were doing before.

**Closed** 2021-04-26 21:28 UTC
Labels: NeedsInvestigation, release-blocker
