### ISSUE TITLE
fmt: Fscanf fails to read an integer from a special file

### ISSUE THREAD

**Issue by opennota** [golang/go#54938] opened 2022-09-07 16:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xxx/.cache/go-build"
GOENV="/home/xxx/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/xxx/gocode/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xxx/gocode"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/home/xxx/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/home/xxx/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3607947791=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

https://go.dev/play/p/Kodf5klMoFG

### What did you expect to see?

`cat /proc/sys/fs/pipe-max-size` outputs `1048576`, so I expected this number.

### What did you see instead?

`1`

When it's a regular file with the same content (the number + a newline), `Fscanf` works fine (`dd if=/proc/sys/fs/pipe-max-size of=pipe-max-size`, then use `os.Open("pipe-max-size")` on line 10.)

`ioutil.ReadAll` also reads all the data.

**Comment by seankhliao** [comment] 2022-09-07 16:53
Duplicate of #29399

**Closed by seankhliao** 2022-09-07 16:53 UTC
