### ISSUE TITLE
x/website: tutorial package version reference out of date 

### ISSUE THREAD

**Issue by ilcylic** [golang/go#52582] opened 2022-04-26 23:58 UTC
### What is the URL of the page with the issue?
 
 https://go.dev/doc/tutorial/getting-started
 
### What is your user agent?
 

 
 N/A
 
### Screenshot
 

 
 N/A
 
### What did you do?
 

 
 Read the page.
 
### What did you expect to see?
 
 I don't know.  But the message below in section 1.2 says "if you see rsc.io/quote/v3, ignore it for now" which... technically remains a possibly valid order, but given that there's a v4, I'm wondering if this needs updating.  At least to "ignore v3 *and* v4 for now" if those are the correct instructions.
 
### What did you see instead?

 This is the segment of the page (section 1.2 under "**Call code in an external package**") that led to my question.

```
1.) Make your printed message a little more interesting with a function from an external module.

    1.) Visit pkg.go.dev and [search for a "quote" package](https://pkg.go.dev/search?q=quote).
    2.) Locate and click the rsc.io/quote package in search results (if you see rsc.io/quote/v3, ignore it for now).
    3.) In the Documentation section, under Index, note the list of functions you can call from your code. You'll use the Go function.
    4.) At the top of this page, note that package quote is included in the rsc.io/quote module.
```

**Comment by seankhliao** [comment] 2022-04-29 14:54
Duplicate of #51188

**Closed by seankhliao** 2022-04-29 14:54 UTC
