### ISSUE TITLE
storing go.mod file not in the root of the repo

### ISSUE THREAD

**Issue by arthurvaverko-kaltura** [golang/go#40299] opened 2020-07-20 07:51 UTC
usgin golang 1.14

we are generating multiplelibraries in multiple languages so the repo structure is 

.gitignore
README.md
generate\csharp ...
generated\go\libname
generated\go\libname\go.mod

the go mod file is not on root looks like this 
```go
module github.com/user/repo/generated/go/libname

go 1.14
```

the repo is tagged with a version `v1.0` for example
when trying to get the specific version if fails and gets the latest commit instead 
I figured its because there is no mod file in the root of the repo and the module system looks for it to match the tag of the repo.

any way to overcome this ? without moving the mod file to the root of the repo ? or separating the go code into its own repository ? 

Stackoverflow link:https://stackoverflow.com/questions/62990985/storing-go-mod-file-not-in-the-root-of-the

**Comment by ALTree** [comment] 2020-07-20 08:11
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-07-20 08:11 UTC
