### ISSUE TITLE
x/vgo: XML errors

### ISSUE THREAD

**Issue by thockin** [golang/go#24025] opened 2018-02-22 01:03 UTC
### What version of Go are you using (`go version`)?

```
$ vgo version
go version go1.10rc2 linux/amd64 vgo:2018-02-20.1
```

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

AMD64 Linux

### What did you do?

`vgo list` on Kubernetes

### What did you expect to see?

Lots of messages

### What did you see instead?

Mixed in among the messages were many of these:

```
vgo: resolving import "bitbucket.org/ww/goautoneg"
findRepo: XML syntax error on line 13: expected attribute name in element
findRepo: XML syntax error on line 14: expected attribute name in element
vgo: import "k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/negotiation" ->
	import "bitbucket.org/ww/goautoneg": XML syntax error on line 13: expected attribute name in element
```

**Comment by jasontconnell** [comment] 2018-02-22 06:42
In reviewing the code, it would appear the early vgo tool is only supporting github repos at the time.

**Comment by flicaflow** [comment] 2018-02-22 08:10
This is a duplicate of this #23956 
@jasontconnell I confirmed your assumption by implementing a stub for bitbucket.
@rsc Do you have a bitbucket implementation in the pipeline should I give it a shot, it would have to wait for the weekend though.

**Comment by kardianos** [comment] 2018-02-22 17:48
This is a duplicate. There is an active CL at https://golang.org/cl/95578 .

**Closed by kardianos** 2018-02-22 17:48 UTC
