### ISSUE TITLE
Go doesn't respect main module when building from outside the module

### ISSUE THREAD

**Issue by frioux** [golang/go#34314] opened 2019-09-16 02:23 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go1.13 version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/frew/.cache/go-build"
GOENV="/home/frew/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/frew/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org"
GOROOT="/home/frew/sdk/go1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/frew/sdk/go1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/frew/sdk/go1.13/src/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/run/shm/go-build335230439=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I installed a binary with go get (`GO111MODULE=on go1.13 get github.com/frioux/leatherman@latest`).

### What did you expect to see?

I expected to have a nice, versioned binary (surfaced by both `go version -m <binary>` and `leatherman version`).

### What did you see instead?

I got a nice versioned binary but (at least) my go mod replace directive was ignored, resulting in a broken tool (`echo "foo: 1" | leatherman yaml2json` works if the replace was honored.)

If I build from a checkout (ie clone the repo and do `go build .`) I get a *working* binary, but the version info just says "devel".

It seems possible that I am doing something wrong here, but I can't see what `go get` for a module in this mode could mean, then?

**Comment by mvdan** [comment] 2019-09-16 08:24
`go get` ignores replace directives from "non-main" modules by design. I can't find the exact piece of docs that documents this, but for example see https://github.com/golang/go/wiki/Modules#gomod.

As for how to make `go get` respect replace directives, I think your best bet is https://github.com/golang/go/issues/30515.

**Comment by frioux** [comment] 2019-09-16 21:15
Thanks for the quick reply, I appreciate that!  I suspect you're right about #30515, but I'm confused because I would expect `github.com/frioux/leatherman` to *be* the main module.  There is no higher level go.mod, and in the main module metadata go seems to imply this too: (note second and third lines)

```
/home/frew/go/bin/leatherman: go1.13
        path    github.com/frioux/leatherman
        mod     github.com/frioux/leatherman    v0.0.0-20190916033958-a314813580a4      h1:8jQfc7KnAZ2KbaDvUVe/UP3OuBdwnYNQ5JaHJb5dEPo=
        dep     github.com/BurntSushi/toml      v0.3.1  h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
        dep     github.com/PuerkitoBio/goquery  v1.5.0  h1:uGvmFXOA73IKluu/F84Xd1tt/z07GYm8X49XKHP7EJk=
        dep     github.com/andybalholm/cascadia v1.0.0  h1:hOCXnnZ5A+3eVDX8pvgl4kofXv2ELss0bKcqRySc45o=
        dep     github.com/erikdubbelboer/gspt  v0.0.0-20190125194910-e68493906b83      h1:ngHdSomn2MyugZYKHiycad2xERwIrmMlET7A0lC0UU4=
        dep     github.com/fsnotify/fsnotify    v1.4.7  h1:IXs+QLmnXW2CcXuY+8Mzv/fWEsPGWxqefPtCP5CnV9I=
        dep     github.com/headzoo/surf v1.0.0  h1:d2h9ftKeQYj7tKqAjQtAA0lJVkO8cTxvzdXLynmNnHM=
        dep     github.com/icza/backscanner     v0.0.0-20180226082541-a77511ef4f0f      h1:EEBVjzvzsiUwgWio/3WB2kYx7DtC3QVJKuK6XejFghE=
        dep     github.com/mattn/go-sqlite3     v1.11.0 h1:LDdKkqtYlom37fkvqs8rMPFKAMe8+SgjbwZ6ex1/A/Q=
        dep     github.com/mmcdole/gofeed       v1.0.0-beta2    h1:CjQ0ADhAwNSb08zknAkGOEYqr8zfZKfrzgk9BxpWP2E=
        dep     github.com/mmcdole/goxpp        v0.0.0-20181012175147-0068e33feabf      h1:sWGE2v+hO0Nd4yFU/S/mDBM5plIU8v/Qhfz41hkDIAI=
        dep     github.com/pierrec/lz4/v3       v3.1.0  h1:o0BbsyBT/FweNrbKhfrCC01BJQWiEiwuAEaMdzzW4Og=
        dep     golang.org/x/net        v0.0.0-20190827160401-ba9fcec4b297      h1:k7pJ2yAPLPgbskkFdhRCsA77k2fySZ1zf2zCjvQCiIM=
        dep     golang.org/x/sys        v0.0.0-20190904005037-43c01164e931      h1:+WYfosiOJzB4BjsISl1Rv4ZLUy+VYcF+u+0Y9jcerv8=
        dep     golang.org/x/text       v0.3.2  h1:tW2bmiBqwgJj/UpqtC8EpXEZVYOwU0yG4iWbprSVAcs=
        dep     gopkg.in/yaml.v2        v2.2.2  h1:ZCJp+EgiOT7lHqUV2J862kp8Qj64Jo6az82+3Td9dZw=
```

Am I interpreting this wrong?

**Comment by mvdan** [comment] 2019-09-16 21:46
The "main module" is the module under your current directory. So a `go get` of a module when you're not already inside it ignores the replace directives when it runs the build. This is what the issue I linked above is about, partly.

Perhaps @bcmills @jayconrod can help clarify or point at the canonical docs for this.

**Comment by jayconrod** [comment] 2019-09-17 13:57
Closing because I think #30515 is the same issue.

As @mvdan says, the main module is determined by the `go.mod` enclosing the current working directory. In your example, it looks like that's `$GOROOT/src/go.mod`. The main module does not have a version, so at the moment, the best way to install a *versioned* binary is switching to a directory not covered by `go.mod`, then running `go get`. So for example:

```
(cd ~; GO111MODULE=on go get github.com/frioux/leatherman)
```

`replace` and `exclude` directives only apply within the main module. So there's no way to have a versioned main module with `replace` and `exclude` at the same time.

(This is obviously a pain for a lot of people, so I'm hoping to come up with a solution for #30515 this cycle.)

**Closed by jayconrod** 2019-09-17 13:57 UTC
Labels: modules

**Comment by frioux** [comment] 2019-09-17 14:34
Thank you!

--
