### ISSUE TITLE
Which go methods, functions, structs are bound by gomobile bind command

### ISSUE THREAD

**Issue by FatChou** [golang/go#28610] opened 2018-11-06 07:24 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/qeeyou/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/qeeyou/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dz/s6p42lmd62x7d7sk4h06h1z40000gn/T/go-build434811796=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

use gomobile bind --target=ios /xx/xxproject/

### What did you expect to see?

I want to know,Which go function, method, struct to objective c will be bound to the gomobile bind command? Is there a flag to tell the gomobile bind command, xx methods, functions need to be bound

**Comment by agnivade** [comment] 2018-11-06 08:17
Hi @FatChou,

This appears to be a question rather than a Go bug. We do not use the issue tracker for general discussions or questions like these. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

For further questions, please have a look at [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.

Closing since this is not a bug.

**Closed by agnivade** 2018-11-06 08:17 UTC
