### ISSUE TITLE
reflect: DeepEqual() returns incorrect result when comparing named channel types

### ISSUE THREAD

**Issue by nevkontakte** [golang/go#63886] opened 2023-11-01 20:36 UTC
### What version of Go are you using (`go version`)?

1.21.3 (playground)

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

N/A (play.go.dev)

### What did you do?

https://go.dev/play/p/HsbSFqyS1d7

### What did you expect to see?

```
reflect.DeepEqual true
== true
```

From [DeepEqual ](https://pkg.go.dev/reflect#DeepEqual) documentation:

> Other values - numbers, bools, strings, and channels - are deeply equal if they are equal using Go's == operator.

From [Go spec](https://go.dev/ref/spec#Comparison_operators):

> Channel types are comparable. Two channel values are equal if they were created by the same call to [make](https://go.dev/ref/spec#Making_slices_maps_and_channels) or if both have value nil.

The bug is in this line: https://cs.opensource.google/go/go/+/refs/tags/go1.21.3:src/reflect/deepequal.go;l=234-236;drc=be4fe08b57b3365f3f5db2e2def296904557442d. DeepEquals return false if two values have different types, however for channels (at least according to the spec) don't need to be of the same type to be equal, they only need to share the same underlying type.

### What did you see instead?

```
reflect.DeepEqual false
== true
```

**Comment by cherrymui** [comment] 2023-11-02 00:14
DeepEqual's documentation mentioned "Values of distinct types are never deeply equal" (in the first paragraph). A named channel type and an unnamed channel type are distinct types, so those values are never equal. The "Other values" case is under "Two values of identical type are deeply equal if one of the following cases applies", which does not apply here.

Closing as this works as intended. Thanks.

**Closed by cherrymui** 2023-11-02 00:14 UTC
Labels: compiler/runtime

**Comment by nevkontakte** [comment] 2023-11-02 14:23
I suppose that's fair, but confusing that deep equality is not the same as regular equality for the type. Does that mean that the regular comparison of channels should also be type-dependent?

**Comment by cherrymui** [comment] 2023-11-02 14:53
`any(ch1) == any(ch2)` is false, which is comparing them as interface values. `DeepEqual` operates on `reflect.Value`s, which are created from interfaces, so there is at least some consistency. Usually for non-interface types, only values of the same type can be compared. Unfortunately channel comparison works differently. But I don't think we can change that now.
