### ISSUE TITLE
cmd/go: go get: no matching versions for query when branch starts with v\d

### ISSUE THREAD

**Issue by switchupcb** [golang/go#57122] opened 2022-12-06 20:35 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go 1.19
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOPROXY=https://proxy.golang.org,direct
</pre></details>

### What did you do?

https://go.dev/ref/mod#version-queries

The following works (tag-specifier).
```
go get github.com/switchupcb/dasgo@v0.10.1
```

The following doesn't work (branch-specifier).
```
go get github.com/switchupcb/dasgo@v10
go: github.com/switchupcb/dasgo@v10: no matching versions for query "v10"
```

The following works (branch-specifier).
```
go get github.com/switchupcb/dasgo@main
```
There is no "main" branch, however the `main` branch represents a branch named `v10`.

### What did you expect to see?

`go get` works with the `v10` branch-specifier.

### What did you see instead?

`no matching versions for query "v10" `

**Comment by seankhliao** [comment] 2022-12-06 20:37
Duplicate of #29731

**Closed by seankhliao** 2022-12-06 20:37 UTC
