### ISSUE TITLE
proposal: slices: add Map function

### ISSUE THREAD

**Issue by haoxins** [golang/go#61191] opened 2023-07-06 12:30 UTC
It would be nice to have a simple, generic way to map a slice to another.
I have already seen it in the associated drafts, such as https://github.com/golang/proposal/blob/master/design/go2draft-contracts.md#defined-aggregate-types,
but it is not included in the `slices` package introduced in Go 1.21.

Is there any particular reason not to do this?

**Comment by seankhliao** [comment] 2023-07-06 12:43
Duplicate of #58881

**Closed by seankhliao** 2023-07-06 12:43 UTC
Labels: Proposal
