### ISSUE TITLE
go/types,x/tools/go/packages: types.Implements() fails for interfaces with named types

### ISSUE THREAD

**Issue by momilo** [golang/go#61412] opened 2023-07-18 14:08 UTC
### Problem summary
It seems like the function `types.Implements` will fail if the `Interface` provided contains methods returning custom types (even if everything is defined in the exact same package).

Sample minimal code can be found here:
- https://go.dev/play/p/I3UPHwUkMFb
- Note: it is not runnable on `go.dev/play` (go executable is not directly available), needs to be copy-pasted. 

### Details
Specifically, given the below which compiles fine (note the assertion that the struct "something" implements both interfaces):
```
type MyInterface interface {
	ID() ID
	Description() string
}

type MySimplerInterface interface {
	Description() string
}

type something struct{}

var _ MyInterface = &something{}
var _ MySimplerInterface = &something{}
...

```

the check `types.Implements(types.NewPointer(typesObj.Type()), interfaceSearched)` will return true only for MySimplerInterface, where the types details have been loaded using `go/packages` 

### What version of Go are you using (`go version`)?
go1.20.5

### What operating system and processor architecture are you using (`go env`)?
darwin / arm64

**Comment by bcmills** [comment] 2023-07-18 15:07
(attn @griesemer @findleyr)

**Comment by griesemer** [comment] 2023-07-18 19:50
This is working as expected.

Note that `types.Implements` is the same function that the compiler is using (it's an auto-generated copy of it), so it's unlikely that `types.Implements` fails when using it as a library function when the compiler accepts the equivalent source.

[Here](https://go.dev/play/p/wdveHozPp2g) is your example, a bit further simplified so I could see what's going on (in general when sending a repro case, please minimize by removing all unnecessary code - it greatly helps us diagnosing problems).

The problem is that you are loading the same packages twice (`interfacePks` and `searchedPks`). User-defined types, in this case, the type `ID` gets a different "identity" in different loads. As a consequence, the type `ID` used in the interface method doesn't match the type `ID` in the struct method and then `Implements` fails. The problem goes away if you use say `string` in case of `ID` (not a user-defined type), or if you correct the code and load the packages only once. You can see in the [simplified example](https://go.dev/play/p/wdveHozPp2g) (line 50, 51) that loading the packages only once solves the issue.

The type-identity properties should be better documented. I filed #61418.

Closing as working as intended.

**Closed by griesemer** 2023-07-18 19:50 UTC
Labels: Tools

**Comment by momilo** [comment] 2023-07-19 09:28
Thank you for the quick reply. That is not ideal (e.g. the interface could be defined in a completely different place than the code I am trying to analyse against it, without a common root - sure, one can force the existence of the common root programmatically), but I understand it is the limitation of the current toolset.

Thank you once again for your help!
