### ISSUE TITLE
why panic in src/database/sql/sql.go:2209?

### ISSUE THREAD

**Issue by oggyunao** [golang/go#66614] opened 2024-03-30 07:49 UTC
### Go version

go version 1.20.0

### Output of `go env` in your module/workspace:

```shell
NA
```

### What did you do?

use [github.com/dtm-labs/client](https://github.com/dtm-labs/dtm) 

### What did you see happen?

panic stack：
........
/usr/local/go/src/runtime/panic.go:884 +0x213 database/sql.(*Tx).grabConn(0x0, {0x15c40c8, 0xc00004e030})
/usr/local/go/src/database/sql/sql.go:2209 +0x52 database/sql.(*Tx).ExecContext(0x0, {0x15c40c8, 0xc00004e030}, {0xc0004c0230, 0x6e}, {0xc000ecd7a0, 0x6, 0x6})
/usr/local/go/src/database/sql/sql.go:2467 +0x51\ndatabase/sql.(*Tx).Exec(0x11d1c40?, {0xc0004c0230?, 0x13862c0?}, {0xc000ecd7a0?, 0x10?, 0x116e9a0?})
/usr/local/go/src/database/sql/sql.go:2480 +0x45 github.com/dtm-labs/client/dtmcli/dtmimp.DBExec({0x13862c0, 0x5}, {0x15bcc58, 0x0}, {0xc0004c0230, 0x6e}, {0xc000ecd7a0, 0x6, 0x6})
/go/pkg/mod/github.com/dtm-labs/client@v1.17.3/dtmcli/dtmimp/utils.go:211 +0x157\ngithub.com/dtm-labs/client/dtmcli/dtmimp.InsertBarrier({0x15bcc58, 0x0}, {0xc000e55128, 0x4}, {0xc00005a378, 0x16}, {0xc000dcf5de, 0x2}, {0xc000e55146, 0x6}, ...)
/go/pkg/mod/github.com/dtm-labs/client@v1.17.3/dtmcli/dtmimp/utils.go:292 +0x377\ngithub.com/dtm-labs/client/dtmcli.(*BranchBarrier).Call(0xc0001f5b20, 0x0, 0xc0016ab050)
/go/pkg/mod/github.com/dtm-labs/client@v1.17.3/dtmcli/barrier.go:77 +0x468\noasis/app/ams/amsbalanceinfrastructure/internal/data.(*Data).BarrierInTx(0xc00071adc0, {0x15c4138, 0xc000349bc0}, {0xc000053e86, 0x6}, 0xc0016ca340)
.......

can somebody help me?

### What did you expect to see?

NA

**Comment by ALTree** [comment] 2024-03-30 08:34
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here. If it turns out to be a bug in the go standard library, feel free to comment and we'll reopen. Thanks.

**Closed by ALTree** 2024-03-30 08:34 UTC

**Comment by oggyunao** [comment] 2024-03-30 08:39
panic in go standard library, bug or question? i think it is bug...please reopen it

> Hi,
> 
> the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.
> 
> Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions.
> 
> Closing here. If it turns out to be a bug in the go standard library, feel free to comment and we'll reopen. Thanks.

**Comment by ALTree** [comment] 2024-03-30 08:47
A panic can be caused by internal structures corruption caused by a race condition or use of the `unsafe` package. Also a few standard library functions panic on bad inputs.

1) try to run your code after building with the `-race` flag. Does it print any warning?
2) try to run your program after setting `GODEBUG=cgocheck=2`. Does it print any error?
3) Update to the latest go version (1.20 is not) and retry.

In any case a panic like this cannot be investigated if you don't post a reproducer.

**Comment by ALTree** [comment] 2024-03-30 08:49
Also see #43445 (which is almost a copy past of this report, down to the number of "......." used to shorten the stack trace).
