### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by opsanatoliy** [golang/go#63700] opened 2023-10-23 12:40 UTC
gopls version: v0.13.2 (go1.21.0)
gopls flags: 
update flags: proxy
extension version: 0.39.1
go version: 1.21.3
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Mon, 23 Oct 2023 12:40:27 GMT
restart history:
Mon, 23 Oct 2023 12:08:39 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100ff9084]

goroutine 897 [running]:
golang.org/x/tools/gopls/internal/lsp/cache.localPackageKey({{0x140005245d0, 0x17}, {0x140005245d0, 0x17}, {0x140004e4ab0, 0x5}, {0x140003fe000, 0x1, 0x1}, {0x140003fe020, ...}, ...})
	  check.go:1402  0x554
golang.org/x/tools/gopls/internal/lsp/cache.(*packageHandleBuilder).buildPackageHandle(0x1400139a060, {0x10155dcc0, 0x140000e11d0}, 0x140000e0820)
	  check.go:1090  0x234
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).getPackageHandles.func2.1()
	  check.go:891  0xb0
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:75  0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1033
	  errgroup.go:72  0x98
[Error - 14:40:21] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by adonovan** [comment] 2023-10-23 22:26
Closing as a duplicate of https://github.com/golang/go/issues/63701 in gopls, for which a fix is pending.

**Closed by adonovan** 2023-10-23 22:26 UTC
Labels: gopls, Tools

**Comment by findleyr** [comment] 2023-10-26 15:27
Hi, can you please report if you are using a `GOPACKAGESDRIVER`? (`echo $GOPACKAGESDRIVER`)?

**Comment by opsanatoliy** [comment] 2023-10-26 15:48
> echo $GOPACKAGESDRIVER

I am not

**Comment by findleyr** [comment] 2023-10-26 21:23
This should be fixed in v0.14.1-pre.1 (on v0.14.0 there is a workspace error message instead of a panic).

```
go install golang.org/x/tools/gopls@v0.14.1-pre.1
```

Could anyone here please try that out to confirm? With your confirmation, we will release v0.14.1 tomorrow.

**Comment by bcspragu** [comment] 2023-12-21 03:29
I just ran into this on `v0.14.2`, and I am using `GOPACKAGESDRIVER`:

```
$ gopls version
golang.org/x/tools/gopls v0.14.2
    golang.org/x/tools/gopls@v0.14.2 h1:sIw6vjZiuQ9S7s0auUUkHlWgsCkKZFWDHmrge8LYsnc=
```

Cleaned up from my editor (Helix):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbe7dcb]

goroutine 2862 [running]:

golang.org/x/tools/gopls/internal/lsp/cache.localPackageKey({{0xc000522930, 0x21}, {0xc00046fcb0, 0x6}, {0xc00046fc78, 0x6}, {0xc003c00180, 0x1, 0x1}, {0xc003c001a0, ...}, ...})
	<home>/.local/share/go/pkg/mod/golang.org/x/tools/gopls@v0.13.2/internal/lsp/cache/check.go:1402 +0x6eb
golang.org/x/tools/gopls/internal/lsp/cache.(*packageHandleBuilder).buildPackageHandle(0xc0005a2750, {0x1162f80, 0xc000b4abe0}, 0xc00044e3c0)
	<home>/.local/share/go/pkg/mod/golang.org/x/tools/gopls@v0.13.2/internal/lsp/cache/check.go:1090 +0x2be
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).getPackageHandles.func2.1()
	<home>/.local/share/go/pkg/mod/golang.org/x/tools/gopls@v0.13.2/internal/lsp/cache/check.go:891 +0xd7
golang.org/x/sync/errgroup.(*Group).Go.func1()
	<home>/.local/share/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 2800
	<home>/.local/share/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x96
```

**Comment by adonovan** [comment] 2023-12-28 01:52
Hi @bcspragu, the filename in that stack trace shows gopls@v0.13.2, so I suspect you are not running the executable you intended to, and the source at that line corresponds to the bug that was fixed, as mentioned above.

Please try reinstalling gopls@latest, and check the version of the gopls command on the $PATH. Do let us know if the problem recurs after that.

**Comment by bcspragu** [comment] 2023-12-28 22:20
Oof yeah apologies for the noise, looks like I just forgot to reload my shell to pick up my `$PATH` changes, which would have preferred the local `0.14.2` binary over the older system-wide one I had.
