### ISSUE TITLE
release: Go 1.7.3 fails to install on El Capitan

### ISSUE THREAD

**Issue by jferrer21** [golang/go#17531] opened 2016-10-20 18:48 UTC
Please answer these questions before submitting your issue. Thanks!
### What version of Go are you using (`go version`)?

1.7.0
### What operating system and processor architecture are you using (`go env`)?

OSX El Capitan
10.11.6
### What did you do?

Download and open go1.7.3.darwin-amd64.pkg
### What did you see instead?

Warning message:  "The installation failed.  The installer encountered an error that caused the installation to fail.  Contact the software manufacturer for assistance."

**Comment by quentinmit** [comment] 2016-10-20 19:17
I'm not able to replicate this on 10.12.1.

@jferrer21 Can you please attach the log from your installer? When the install fails, you can choose `Window->Installer Log` and then hit the Save button in the toolbar to get a text file of the log. Thanks!

**Comment by jferrer21** [comment] 2016-10-20 19:23
Hi Quentin,

Below is the log.

Oct 20 11:37:22 Rebels-Mac-Pro Installer[436]: Installation checks succeeded with warnings.
Oct 20 11:37:22 Rebels-Mac-Pro Installer[436]: Installation check warning.  Previous Installation Detected. A previous installation of Go exists at /usr/local/go. This installer will remove the previous installation prior to installing. Please back up any data before proceeding..
Oct 20 11:37:35 Rebels-Mac-Pro installd[284]: PackageKit: ----- Begin install -----
Oct 20 11:37:38 Rebels-Mac-Pro installd[284]: PackageKit: Install Failed: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={NSFilePath=/private/tmp/PKInstallSandbox.XXXXXX} {
	    NSFilePath = "/private/tmp/PKInstallSandbox.XXXXXX";
	}
Oct 20 11:37:38 Rebels-Mac-Pro Installer[436]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Oct 20 11:37:38 Rebels-Mac-Pro Installer[436]: Displaying 'Install Failed' UI.
Oct 20 11:37:38 Rebels-Mac-Pro Installer[436]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
Oct 20 12:19:55 Rebels-Mac-Pro Installer[436]: Installation checks succeeded with warnings.
Oct 20 12:19:55 Rebels-Mac-Pro Installer[436]: Installation check warning.  Previous Installation Detected. A previous installation of Go exists at /usr/local/go. This installer will remove the previous installation prior to installing. Please back up any data before proceeding..
Oct 20 12:20:01 Rebels-Mac-Pro installd[284]: PackageKit: ----- Begin install -----
Oct 20 12:20:04 Rebels-Mac-Pro installd[284]: PackageKit: Install Failed: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={NSFilePath=/private/tmp/PKInstallSandbox.XXXXXX} {
	    NSFilePath = "/private/tmp/PKInstallSandbox.XXXXXX";
	}
Oct 20 12:20:04 Rebels-Mac-Pro Installer[436]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Oct 20 12:20:04 Rebels-Mac-Pro Installer[436]: Displaying 'Install Failed' UI.
Oct 20 12:20:04 Rebels-Mac-Pro Installer[436]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

**Comment by inhies** [comment] 2016-10-24 04:25
I had no issues installing the .pkg on 10.11.6

**Comment by Kreeblah** [comment] 2016-10-27 05:15
I'm having the same issue with 1.7.3 with the same error message on 10.11.6.  I was upgrading from 1.7.1, however now even trying a reinstall of 1.7.1 results in the same error.

**Comment by bradfitz** [comment] 2016-12-02 18:05
/cc @broady, if this means anything to you.

I assume this might still affect some users for Go 1.8.

**Comment by broady** [comment] 2016-12-04 00:22
Doesn't mean anything to me.

@jferrer21 @Kreeblah  - did this happen for previous installers, too? Like 1.7.1?

Does it happen with 1.6.4 (released this week)?

**Comment by rsc** [comment] 2016-12-05 19:47
I found these:

https://forums.virtualbox.org/viewtopic.php?f=8&t=80023
http://superuser.com/questions/1133065/unable-to-write-to-tmp-osx-unable-to-correct-permissions-operation-not-permitt#comment1629612_1133065

This suggests that sometimes the package installer gets messed up by the /tmp -> private/tmp symlink being lost or not having the right permissions or something. It's not clear whether this is the problem for this report.

The superuser.com link has some commands for "repair_packages" that sound promising.

**Comment by Kreeblah** [comment] 2016-12-05 19:54
@broady I actually can't replicate it now, even on the versions that were failing before.  I'm still on 10.11.6, so I'm not sure what changed.

**Comment by bradfitz** [comment] 2017-06-07 20:50
Can anybody reproduce this?

**Comment by agnivade** [comment] 2018-11-07 07:06
This should have had a "WaitingForInfo" label. Given that we are way past supporting 1.7.x and it's been more than a year since anybody has commented on the issue, I will go ahead and close this.

@jferrer21 - If you still face similar issues with 1.10.x or 1.11.x, please do feel free to open a new issue.

**Closed by agnivade** 2018-11-07 07:06 UTC
Labels: NeedsInvestigation, OS-Darwin, help wanted
