### ISSUE TITLE
unrecognized printf flag for verb 'd': '#'

### ISSUE THREAD

**Issue by cclauss** [golang/go#20190] opened 2017-05-01 09:32 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
 go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?
https://play.golang.org/p/PZwl9m01ba

### What did you expect to see?
No errors on go vet

### What did you see instead?
go vet --> unrecognized printf flag for verb 'd': '#'

**Comment by davecheney** [comment] 2017-05-01 10:18
I believe this is correct, `%d` does not support the `#` modifier.

From the `fmt` package documentation
```
#	alternate format: add leading 0 for octal (%#o), 0x for hex (%#x);
	0X for hex (%#X); suppress 0x for %p (%#p);
	for %q, print a raw (backquoted) string if strconv.CanBackquote
	returns true;
```

I am going to close this issue as working as intended as it does not appear to be a bug in Go or in vet.

**Closed by davecheney** 2017-05-01 10:18 UTC
