### ISSUE TITLE
x/mobile: Executing an example fails on Windows

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#14492] opened 2016-02-24 16:00 UTC
```
[~/go/src/golang.org/x/mobile/example/basic]
$ go run main.go
# golang.org/x/mobile/app
..\..\app\shiny.go:42: w.Events undefined (type screen.Window has no field or method Events)
```

**Comment by rakyll** [comment] 2016-02-24 18:34
Duplicate of https://github.com/golang/go/issues/14401.

**Closed by rakyll** 2016-02-24 18:34 UTC
