### ISSUE TITLE
x/tools/gopls: autoimport doesn't work properly in VS Code when using CRLF line endings

### ISSUE THREAD

**Issue by preslavmihaylov** [golang/go#47200] opened 2021-07-14 16:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\pmiha\AppData\Local\go-build
set GOENV=C:\Users\pmiha\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\pmiha\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\pmiha\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\pmiha\Programming\learn-programming-with-go\02_data-types-and-variables\examples\15_shorthand_operations\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\pmiha\AppData\Local\Temp\go-build4014282860=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
go mod init example
touch main.go

Write this via Visual Studio Code:
```go
package main

import "fmt"

func main() {
	math.Sqrt(9)
	fmt.Println("hello")
}
```

Save

### What did you expect to see?
```go
package main

import (
	"fmt"
	"math"
)

func main() {
	math.Sqrt(9)
	fmt.Println("hello")
}

```

### What did you see instead?
```go
package main

import (
	"fmt"	"math"
)

func main() {
	math.Sqrt(9)
	fmt.Println("hello")
}
```

**Comment by hyangah** [comment] 2021-07-14 21:28
@preslavmihaylov Thanks for filing the issue. We need more info here:

* Output of `gopls -v version`
* Is it CRLF file? If so, can you try LF to see if the problem still occurs?
* Can you please follow the instruction https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information and collect the gopls trace?

**Comment by preslavmihaylov** [comment] 2021-07-15 05:03
gopls version output:
<details><summary>gopls version output</summary>
```
Build info
----------
golang.org/x/tools/gopls v0.7.0
    golang.org/x/tools/gopls@v0.7.0 h1:JQBHW81Gsyim6iDjUwGoPeSpXrSqwen3isPJLfDfaYU=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.5 h1:Khx7svrCpmxxtHBq5j2mp/xVjsi8hQMfNLvJFAlrGgU=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.2 h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20210510120138-977fb7262007 h1:gG67DSER+11cZvqIMb8S8bt0vZtiN6xWYARwirrOSfE=
    golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c h1:Pv9gNyJFYVdpUAVZYJ1BDSU4eGgXQ+0f3DIGAdolO5s=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=      
    honnef.co/go/tools@v0.2.0 h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=
    mvdan.cc/gofumpt@v0.1.1 h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
```
</details>

The file type was indeed `CRLF`, when I changed it to `LF`, the problem stopped occuring.

**Comment by hyangah** [comment] 2021-07-16 17:41
Duplicate of #46791

**Closed by hyangah** 2021-07-16 17:41 UTC
Labels: Tools, gopls
