### ISSUE TITLE
x/net/ipv6: OS X 10.8 kernel panic during tests

### ISSUE THREAD

**Issue by bradfitz** [golang/go#17015] opened 2016-09-07 15:11 UTC
Something in the golang.org/x/net/ipv6 tests causes a kernel panic on OS X 10.8, which confuses the build coordinator, because the VM keeps disappearing during the tests, so it tries forever.

Fix it on both sides:
- skip the test on OS X 10.8
- fix the builder to note tests which kill their machine

/cc @mikioh

**Comment by bradfitz** [comment] 2016-09-07 15:20
I'm still trying to narrow down where the kernel panic occurs.

I recorded a video, which ends in this frame at least showing the tests which are okay:

<img width="725" alt="screen shot 2016-09-07 at 8 18 25 am" src="https://cloud.githubusercontent.com/assets/2621/18317741/c3832f5e-74d3-11e6-9df6-2450b7736dfc.png">

I tried adding a `t.Skip` to the top of `TestUDPMultiplePacketConn...` but it then crashed even earlier, right when I ran the test binary, without me seeing any output of the successful tests (that is, I didn't even see the contents of the screenshot above).

**Comment by mikioh** [comment] 2016-09-07 15:52
As is usual with IP protocol stack development on BSD variants, it's a crash caused by mbuf corruption because almost all the ip-level options manipulates it. Probably we need to disable a few options on OS X 10.8 by tweaking init function in ipv6/sys_darwin.go.

**Comment by mikioh** [comment] 2016-09-07 16:11
Still haven't had a look at https://github.com/opensource-apple/xnu.git carefully, but perhaps OS X 10.8 is the interim release of the transition from RFC 2292 to RFC 3542. The following disables RFC 3542-related options on OS X 10.8 or below.
```
diff --git a/ipv6/sys_darwin.go b/ipv6/sys_darwin.go
index c263f08..6764d5b 100644
--- a/ipv6/sys_darwin.go
+++ b/ipv6/sys_darwin.go
@@ -49,7 +49,7 @@ func init() {
        // introduced in OS X 10.7 (Darwin 11.0.0). But it looks like
        // those features require OS X 10.8 (Darwin 12.0.0) and above.
        // See http://support.apple.com/kb/HT1633.
-       if i > 2 || i == 2 && osver[0] >= '1' && osver[1] >= '2' {
+       if i > 2 || i == 2 && osver[0] >= '1' && osver[1] >= '3' {
                ctlOpts[ctlTrafficClass].name = sysIPV6_TCLASS
                ctlOpts[ctlTrafficClass].length = 4
                ctlOpts[ctlTrafficClass].marshal = marshalTrafficClass
```

**Comment by bradfitz** [comment] 2016-09-07 16:48
Maybe once I finish the OS X VMWare integration, I can just get you `x/build/cmd/gomote` access to 10.8 VMs and you can try.

**Comment by mikioh** [comment] 2016-09-14 08:53
Will submit CL 28999 once I've confirmed that it gets worked on OS X 10.8 using gomote. Ping me when the CI stuff has landed.

**Comment by mikioh** [comment] 2016-09-25 01:29
@bradfitz,

Can I have an access to OS X 10.8 bot using gomote?

**Comment by mikioh** [comment] 2016-11-14 01:08
Submitting and see what happens after waiting for two months there is no response.

**Closed** 2016-11-16 07:52 UTC
Labels: Builders, Testing
