### ISSUE TITLE
cmd/go: git remote did not send all necessary objects

### ISSUE THREAD

**Issue by chmking** [golang/go#31426] opened 2019-04-11 21:54 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
11-Apr-2019 15:41:48 | GOARCH="amd64"
11-Apr-2019 15:41:48 | GOBIN=""
11-Apr-2019 15:41:48 | GOCACHE="/root/.cache/go-build"
11-Apr-2019 15:41:48 | GOEXE=""
11-Apr-2019 15:41:48 | GOFLAGS=""
11-Apr-2019 15:41:48 | GOHOSTARCH="amd64"
11-Apr-2019 15:41:48 | GOHOSTOS="linux"
11-Apr-2019 15:41:48 | GOOS="linux"
11-Apr-2019 15:41:48 | GOPATH="/go"
11-Apr-2019 15:41:48 | GOPROXY=""
11-Apr-2019 15:41:48 | GORACE=""
11-Apr-2019 15:41:48 | GOROOT="/usr/local/go"
11-Apr-2019 15:41:48 | GOTMPDIR=""
11-Apr-2019 15:41:48 | GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
11-Apr-2019 15:41:48 | GCCGO="gccgo"
11-Apr-2019 15:41:48 | CC="gcc"
11-Apr-2019 15:41:48 | CXX="g++"
11-Apr-2019 15:41:48 | CGO_ENABLED="1"
11-Apr-2019 15:41:48 | GOMOD="<project-build-dir>/go.mod"
11-Apr-2019 15:41:48 | CGO_CFLAGS="-g -O2"
11-Apr-2019 15:41:48 | CGO_CPPFLAGS=""
11-Apr-2019 15:41:48 | CGO_CXXFLAGS="-g -O2"
11-Apr-2019 15:41:48 | CGO_FFLAGS="-g -O2"
11-Apr-2019 15:41:48 | CGO_LDFLAGS="-g -O2"
11-Apr-2019 15:41:48 | PKG_CONFIG="pkg-config"
11-Apr-2019 15:41:48 | GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build539064595=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Running `go get -v` on CI machine.

### What did you expect to see?

go modules downloaded

### What did you see instead?

```
11-Apr-2019 15:43:27 | go: google.golang.org/api@v0.0.0-20181021000519-a2651947f503: git -c protocol.version=0 fetch --unshallow -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/9e62a95b0409d58bc0130bae299bdffbc7b7e74f3abe1ecf897474cc474b8bc0: exit status 1:
11-Apr-2019 15:43:27 | fatal: bad object c7964aab01c00a07d0cc6216a78a5570459cebfd
11-Apr-2019 15:43:27 | error: https://code.googlesource.com/google-api-go-client did not send all necessary objects
```
```
11-Apr-2019 15:36:34 | go: google.golang.org/api@v0.0.0-20190116000637-07f56c9e3ab5: git -c protocol.version=0 fetch --unshallow -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/9e62a95b0409d58bc0130bae299bdffbc7b7e74f3abe1ecf897474cc474b8bc0: exit status 1:
11-Apr-2019 15:36:34 | fatal: bad object c7964aab01c00a07d0cc6216a78a5570459cebfd
11-Apr-2019 15:36:34 | error: https://code.googlesource.com/google-api-go-client did not send all necessary objects
```

### go mod why output

`go mod why -m google.golang.org/api`

```
# google.golang.org/api
<project>
cloud.google.com/go/storage
google.golang.org/api/googleapi
```

This is not the first issue I've seen with `https://code.googlesource.com/google-api-go-client` How are we meant to resolve these issues?

**Comment by heschik** [comment] 2019-04-11 23:28
Dupe of #31399. Using a different version might help.

**Closed by heschik** 2019-04-11 23:28 UTC
