### ISSUE TITLE
cmd/go: add vet check for json/xml omitempty struct tags on non-basic types

### ISSUE THREAD

**Issue by andig** [golang/go#63539] opened 2023-10-14 08:55 UTC
It's easy to make the mistake of adding `omitempty` struct tags like this (example from https://github.com/golang/oauth2/blob/master/token.go#L50C2-L50C44.):

    Expiry time.Time `json:"expiry,omitempty"`

Currently, this does nothing. With [encoding/json/v2](https://github.com/golang/go/discussions/63397) it might become `omitzero`. 

I suggest to add a vet check flagging `omitempty` as error when added on ~~`time.Time`~~ non-basic types according to encoding/json's `isEmptyValue` (https://github.com/golang/go/pull/63533/files#diff-01d931f6d3bbaef911876952770a164229fe8d659b9007f4be9fc1ea12d20abeR306).

**Comment by seankhliao** [comment] 2023-10-14 12:16
Duplicate of #51261

**Closed by seankhliao** 2023-10-14 12:16 UTC
Labels: Proposal
