### ISSUE TITLE
encoding/json: marshaling can drop .0 for floats

### ISSUE THREAD

**Issue by 0x0elliot** [golang/go#63514] opened 2023-10-12 10:28 UTC
### What version of Go are you using (`go version`)? 1.19

<pre>
$ go version
1.19
</pre>

### What did you do?

This bug led to this: https://github.com/opensearch-project/opensearch-go/issues/386

Here is the go.dev/play package: https://go.dev/play/p/lw648QN2w6Y
<img width="813" alt="Screenshot 2023-10-12 at 3 56 00 PM" src="https://github.com/golang/go/assets/60684641/3a7cc825-6ee0-4b73-9a8d-d52b0651aefb">

### What did you expect to see?
It is however formatted to be: `{"float_value":5}`

This can cause weird type errors that would become hard to find. Let's fix this.

### What did you see instead?
Expected the JSON to be formatted to: `{"float_value":5.00}` (since the value at hand is float)

I want to solve this issue myself. It looks like an easy fix. Please point me to the right direction so that I can close this myself for the next issue.

**Comment by 0x0elliot** [comment] 2023-10-12 10:42
I will try debugging this and following up:

https://github.com/golang/go/blob/eb832afb2310b71db420943d91625552748ae5e6/src/encoding/json/encode.go#L159

**Comment by seankhliao** [comment] 2023-10-12 11:06
cc @mvdan @dsnet

**Comment by seankhliao** [comment] 2023-10-12 11:13
Duplicate of #42246

**Closed by seankhliao** 2023-10-12 11:13 UTC

**Comment by 0x0elliot** [comment] 2023-10-12 11:31
i disagree with the decisions there. it's important to maintain the .0's with the json.Marshal method because of the reason that JSON is used very prominently with systems that don't necessarily deal with types the same way.

as i showed earlier, this leads to weird outcomes. types are not dealt with similarly everywhere, and it's nice for the library to acknowledge and help with that. what do you think? @seankhliao

**Comment by seankhliao** [comment] 2023-10-12 11:54
as the comments in the linked issue mention, we've decided to align with how JavaScript handles numbers https://github.com/golang/go/issues/42246#issuecomment-720893932

**Comment by mvdan** [comment] 2023-10-12 12:06
Like @seankhliao says, there are ways to precisely control how JSON numbers will be encoding and decoding to JSON, e.g. https://pkg.go.dev/encoding/json#Number or a custom marshaler/unmarshaler.

Also note that your original example seems a bit confusing. The float64 value `5.00` does not have two trailing zeros "as a string". You can notice that, for example, `5.0 == 5.000` is true, because they are both exactly the same float64 value, and not strings.
