### ISSUE TITLE
x/tools/gopls: directoryFilters are mishandled when descending the workspace root to find a go.mod file

### ISSUE THREAD

**Issue by wtlangford** [golang/go#45340] opened 2021-04-01 19:05 UTC
#### What did you do?
Configured gopls in vscode as follows:
```json
"gopls": {
  "build.directoryFilters": [
    "-some/dir",
    "+some/dir/moduleroot"
  ]
}
```
Where `some/dir/moduleroot` contains a go.mod.

#### What did you expect to see?
gopls detects the go.mod file in `some/dir/moduleroot` and uses it.

#### What did you see instead?
gopls did not detect the go.mod file and was unable to resolve any imports.

#### Build info

```
golang.org/x/tools/gopls v0.6.9
    golang.org/x/tools/gopls@v0.6.9 h1:LBBcE2y3Tb4bp79JVLWCQBbvYCFEs5ADGWsQDoSLk1Q=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.4 h1:L8R9j+yAqZuZjsqh/z+F1NCffTKKLShY6zXTItVIZ8M=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.1 h1:Kvvh58BN8Y9/lBi7hTekvtMpm07eUZ0ck5pRHpsMWrY=
    golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9 h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=
    golang.org/x/sys@v0.0.0-20210124154548-22da62e12c0c h1:VwygUrnw9jn88c4u8GD3rZQbqrP/tgas88tPUbBxQrk=
    golang.org/x/tools@v0.1.1-0.20210319172145-bda8f5cee399 h1:O5bm8buX/OaamnfcBrkjn0SPUIU30jFmaS8lP+ikkxs=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.1.1 h1:EVDuO03OCZwpV2t/tLLxPmPiomagMoBOgfPt0FM+4IY=
    mvdan.cc/gofumpt@v0.1.0 h1:hsVv+Y9UsZ/mFZTxJZuHVI6shSQCtzZ11h1JEFPAZLw=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
```

**Comment by heschi** [comment] 2021-04-01 19:48
I believe I made a stupid mistake in `findModules`: we don't recurse into a directory that is filtered out, which means that cases exactly like this one won't work. For now it'd probably be easier to recurse unconditionally, but that's unfortunate if the filter is (e.g.) `node_modules`.

**Comment by wtlangford** [comment] 2021-04-01 19:55
You could also potentially look to see if there are any later `+` entries that have the `-` entry as a prefix and only recurse in that case.

**Comment by findleyr** [comment] 2022-07-01 16:43
I believe at this point this is a dupe of https://github.com/golang/go/issues/52970: modules can be excluded using `go.work` files, but we need to reconcile this with the directoryFilters setting.

**Closed by findleyr** 2022-07-01 16:43 UTC
Labels: gopls, Tools, gopls/workspace
