### ISSUE TITLE
cmd/compile: unexpected error referring to blank field in struct composite literal

### ISSUE THREAD

**Issue by griesemer** [golang/go#18089] opened 2016-11-29 00:38 UTC
https://play.golang.org/p/mJtCue1M24 is a valid program that compiles and runs in the playground.

However, it fails at tip (go version devel +8a2c34e Tue Nov 29 00:24:22 2016 +0000 darwin/amd64):
```
$ go run x.go
# command-line-arguments
./x.go:9: cannot refer to blank field or method

```
This is a regression from 1.7 and needs to be fixed for 1.8.

**Comment by mdempsky** [comment] 2016-11-29 03:18
Bisecting identifies c39918a04991387f14cab1204f54fafab81bc105 as the source of regression. (cc @aclements @randall77 for FYI, since this seems like a somewhat surprising/unintended consequence of that CL)

It's worth noting that

    _ = T{1, 1}

used to fail too, as did:

    x := T{0, 0}
    _ = x

So while failing to compile `_ = T{0, 0}` is technically a compiler bug and regression, it doesn't seem like a release blocker to me, as it doesn't seem indicative of any more severe correctness issues. Unless anyone objects, I think we can safely punt it to 1.9.

Also, for #17728, I'm interested in moving the logic for decomposing composite-literal assignments into SSA, which I expect will address these issues.

**Comment by odeke-em** [comment] 2017-04-29 09:21
@griesemer and @mdempsky, this issue seems fixed on tip by commit 3e119404372fd0d47de1458802b68522f593bf36 and CL https://go-review.googlesource.com/c/34988/

```shell
$ go version
go version devel +11eaf42 Sat Apr 29 04:15:49 2017 +0000 darwin/amd64
$ cat main.go 
package main

type T struct {
	x int
	_ int
}

func main() {
	_ = T{0, 0}
}
$ go run main.go 
```

**Comment by odeke-em** [comment] 2017-04-29 09:24
PS: It works alright on the playground and was fixed already for Go1.8; that CL got in on January 9th 2017.

**Comment by josharian** [comment] 2017-04-29 13:42
I'm puzzled both by how the first commit could have broke this and how the second commit could have fixed it. CL 38006, for example, seems more relevant.

In any case, @odeke-em, want to send a CL adding this code as a test case and mark it as fixing this issue?

**Comment by odeke-em** [comment] 2017-04-29 17:46
My thoughts exactly @josharian: I started by examining before and after
that commit, but it was already fixed.

Sounds like a plan, let me mail the test case.

**Closed** 2017-04-29 20:33 UTC
