### ISSUE TITLE
cmd/dist: "moved GOROOT" test failing on plan9/386 builder

### ISSUE THREAD

**Issue by 0intro** [golang/go#21016] opened 2017-07-15 09:32 UTC
CL [48550](https://golang.org/cl/48550) added "moved GOROOT" test, which is failing on the plan9/386 builder. The plan9/386 builder is running as a buildlet on GCE, while the other builders are old-style builders.
```
##### moved GOROOT
go: cannot find GOROOT directory: /tmp/workdir/go
```

See https://build.golang.org/log/6fc6155f74eeff35e8a05ce78ab0531a4f9018bf

**Comment by 0intro** [comment] 2017-07-15 09:43
The test is passing on the old-style builders because the GO_BUILDER_NAME environment variable hasn't been set on these builders, so the "moved GOROOT" test is skipped.

**Comment by ianlancetaylor** [comment] 2017-07-15 13:25
I will disable the test, but ideally someone with a plan9 environment should figure out why it is failing.  The error suggests that on Plan 9 the default GOROOT is overriding the one computed on the basis of where the cmd/go executable is found.

**Comment by 0intro** [comment] 2017-07-15 13:39
Thanks. I'm currently investigating the issue on my side.

**Comment by 0intro** [comment] 2017-07-15 16:45
I think I figured out the issue.

In [findGOROOT](https://github.com/golang/go/blob/2a2a283418b3ba4914520b5a7235c9b48049d1c0/src/cmd/go/internal/cfg/cfg.go#L97), the [os.Executable](https://github.com/golang/go/blob/2a2a283418b3ba4914520b5a7235c9b48049d1c0/src/os/executable_plan9.go) function returns `/bin/go`. This is not the command being executed by [exec.Command](https://github.com/golang/go/blob/2a2a283418b3ba4914520b5a7235c9b48049d1c0/src/cmd/dist/test.go#L454) (`/tmp/workdir_moved/bin/go`), but since I did `bind -a /tmp/workdir/bin /bin`, this is also a valid path for the go tool (returned by `fd2path` on `/proc/<pid>/text`). However, it's not possible to recover the GOROOT from this path.

Since the go tool is called directly from the tests, it should be accessible from the `$path` environment variable. On Plan 9, `$path` usually only contains "/bin" and "." and the directories containing binaries are bound to the /bin directory.

**Comment by rsc** [comment] 2017-11-29 19:32
I think it would be hard to argue that os.Executable is misbehaving here. /bin/go was run, and it returned /bin/go. findGOROOT is just making assumptions about program lookup that only hold on non-Plan 9 systems. It seems like findGOROOT just fundamentally can't work on Plan 9. Of course if the default builds used some canonical path like /sys/go or even /go, then users who want a different Go could bind their Go onto the canonical path. That might be the way forward if we want to support semi-movable GOROOTs on Plan 9. But I'm going to close this issue - the test failing - as working as intended.

**Closed by rsc** 2017-11-29 19:32 UTC
Labels: Builders, OS-Plan9, Testing
