### ISSUE TITLE
How does one repro gobot test failures?

### ISSUE THREAD

**Issue by jadekler** [golang/go#43599] opened 2021-01-08 17:33 UTC
re: https://go-review.googlesource.com/c/exp/+/263178

Here, gobot is failing on:

```
Failed on windows-amd64-2016: https://storage.googleapis.com/go-build-log/4fd94558/windows-amd64-2016_7476d61d.log
Failed on linux-amd64: https://storage.googleapis.com/go-build-log/4fd94558/linux-amd64_ab816ec1.log
Failed on linux-amd64-race: https://storage.googleapis.com/go-build-log/4fd94558/linux-amd64-race_589bd1d8.log
Failed on windows-386-2008: https://storage.googleapis.com/go-build-log/4fd94558/windows-386-2008_4cb3fdbb.log
```

I'm unable to repro these locally (linux-rodete), nor on my windows desktop, nor on https://hub.docker.com/r/amd64/docker/.

How does one go about trying to test these types of failures? Is there some set of docker images that are reliable, or common practices, a doc that I could read, etc?

**Comment by ALTree** [comment] 2021-01-08 18:15
The trybots run on the builders. The builders are not generally directly accessible, but there's a tool called [gomote](https://github.com/golang/go/wiki/Gomote) that can be used to access to the builders infrastructure, which can be useful to debug issues that you cannot reproduce elsewhere. 

Another option is to look for the exact builder configuration of the trybots that are failing, here: https://github.com/golang/build/tree/master/env and try to replicate it locally.

**Comment by cagedmantis** [comment] 2021-01-13 20:53
Closing this as @ALTree has provided an answer.

**Closed by cagedmantis** 2021-01-13 20:53 UTC
