### ISSUE TITLE
cmd/gofmt: inconsistent indentation in var block

### ISSUE THREAD

**Issue by charlesvdv** [golang/go#45491] opened 2021-04-10 13:15 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/charles/.go/bin"
GOCACHE="/home/charles/.cache/go-build"
GOENV="/home/charles/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/charles/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/charles/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3438103609=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

See this [go playground link](https://play.golang.org/p/TgBHfHJ4-Bs)

### What did you expect to see?

```go
package main

var (
	someLoooonnnnnnngName = NewBuilder().
		WithB(
			NewB().
				WithC(),
		).
		Build()

	short = NewBuilder().
		WithB(
			NewB().
				WithC(),
		).
		Build()
)

var yetAnotherLooooonnnnnnngName = NewBuilder().
	WithB(
		NewB().
			WithC(),
	).
	Build()
```

### What did you see instead?

diff: 

```diff
5c5
< 		WithB(
---
> 				WithB(
```

full file: 

```go
package main

var (
	someLoooonnnnnnngName = NewBuilder().
				WithB(                                            // <- Wrong indentation here
			NewB().
				WithC(),
		).
		Build()

	short = NewBuilder().
		WithB(
			NewB().
				WithC(),
		).
		Build()
)

var yetAnotherLooooonnnnnnngName = NewBuilder().
	WithB(
		NewB().
			WithC(),
	).
	Build()

```

**Comment by seankhliao** [comment] 2021-04-11 11:44
possibly duplicate of #41889 ?

**Comment by ianlancetaylor** [comment] 2021-04-12 22:09
This behavior is intentional.  See #644, #7335, #10392, #22852.

**Closed by ianlancetaylor** 2021-04-12 22:09 UTC
Labels: NeedsInvestigation
