### ISSUE TITLE
debug/elf:  unexpected EOF when read data of  bss section

### ISSUE THREAD

**Issue by qingyunha** [golang/go#46414] opened 2021-05-27 09:03 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY=""
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build669194945=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
```go
package main

import (
	"debug/elf"
)

func main() {
	f, _ := elf.Open("/bin/ls")
	for _, s := range f.Sections {
		if s.Name == ".bss" {
			if _, err := s.Data(); err != nil {
				panic(err)
			}
		}
	}
}
```

### What did you expect to see?
no panic

### What did you see instead?
panic: unexpected EOF

**Comment by qingyunha** [comment] 2021-05-27 09:07
elf(5) says `A section of type SHT_NOBITS may have a  nonzero size, but it occupies no space in the file.`  
https://github.com/golang/go/blob/3075ffc93e962792ddf43b2a528ef19b1577ffb7/src/debug/elf/file.go#L371 The above code not handle this case.

**Comment by seankhliao** [comment] 2021-05-27 16:57
Duplicate of #18667

**Closed by seankhliao** 2021-05-27 16:57 UTC
Labels: NeedsInvestigation
