### ISSUE TITLE
go/mod: add the repository url to go.mod file

### ISSUE THREAD

**Issue by nocord** [golang/go#33785] opened 2019-08-22 10:32 UTC
What is the import path of a go module. 
How can i get a module from github or other website?
I don't understand. Please explain. 
The wiki needs explanation

**Comment by ALTree** [comment] 2019-08-22 10:46
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2019-08-22 10:46 UTC

**Comment by ALTree** [comment] 2019-08-22 11:19
@nocord no : ) but the post I see above is a pre-written reply we use to redirect people to places where they can ask questions.
