### ISSUE TITLE
website: builtin documentation

### ISSUE THREAD

**Issue by ptman** [golang/go#21607] opened 2017-08-25 09:05 UTC
I'm not sure if this is the right place to report, but I saw other tickets with "website" in the subject

### What version of Go are you using (`go version`)?

The website talks about 1.9

### Does this issue reproduce with the latest release?

1.9 is latest

### What did you do?

Go to https://golang.org/pkg/builtin/

### What did you expect to see?

Documentation

### What did you see instead?

/src/builtin/builtin.go:88:11: expected type, found '=' (and 1 more errors)

**Comment by griesemer** [comment] 2017-08-25 10:07
Duplicate of #21601 .

**Closed by griesemer** 2017-08-25 10:07 UTC
Labels: Documentation
