### ISSUE TITLE
Installation error of 1.21.0 on Linux: wrong permissions after uncompress tar file.

### ISSUE THREAD

**Issue by riccardo1991** [golang/go#62479] opened 2023-09-06 15:48 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
The suggested [command](https://go.dev/doc/install) for installing Go is not working with 1.21.0.
```sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz```

Tar generates a folder with 750 permissions:
```
$ ls -la /usr/local 
...
drwxr-x--- 10 root 4096 sept.  6 17:39 go
...
```
So a chmod 755 -R is neecessary.

With 1.20.7 no problems:
```
$ sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.20.7.linux-amd64.tar.gz 

$ ls -la /usr/local 
...
drwxr-xr-x 10 root 4096 juil. 26 23:43 go
...
```

### What did you expect to see?
`/usr/local/go` with 755 permissions.

### What did you see instead?
`/usr/local/go` with 750 permissions.

**Comment by riccardo1991** [comment] 2023-09-06 15:56
Ok, I saw 1.21.1 was released very same moment I have created the issue.
With 1.21.1, no problems.

**Comment by seankhliao** [comment] 2023-09-06 17:39
Duplicate of #61862

**Closed by seankhliao** 2023-09-06 17:39 UTC
