### ISSUE TITLE
why bounds out of range isn't a compiler error instead of a runtime error

### ISSUE THREAD

**Issue by nocord** [golang/go#33697] opened 2019-08-17 15:56 UTC

**Comment by ALTree** [comment] 2019-08-17 18:15
Because, in general, some array indices are not known at compile time.

Pleate note that the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Closing here, since this is not a bug.

**Closed by ALTree** 2019-08-17 18:15 UTC

**Comment by nocord** [comment] 2019-08-18 08:19
But it causes bug

**Comment by ALTree** [comment] 2019-08-18 13:45
Well, yes... you can check if the index is `<len(array)` and handle that case in your program so it doesn't panic when it happens.
