### ISSUE TITLE
cmd/compile: out of fixed registers on amd64 and arm

### ISSUE THREAD

**Issue by dvyukov** [golang/go#10088] opened 2015-03-05 07:38 UTC
go version devel +7be32d0 Wed Mar 4 18:24:53 2015 +0000 linux/amd64

The following program crashes compiler with "internal compiler error: out of fixed registers" on amd64 and arm but not on 386.

```go
package main
func main() {
	type X struct {
		f int
	}
	var x X
	var xx []X
	var s0 []int
	var s1 []func()
	var s2 [][][]int
	var s3 [][]int
	var s4 [][]int16
	s1[xx[int(s4[0][s0[s3[s0[s2[s3[s0[s0[s0[x.f]]-1]+1][0]-1][0][0]]-1][0]]+1])].f-1]()	
}
```

**Comment by rsc** [comment] 2015-05-19 17:46
There is basically no benefit to trying to fix this at this point in the cycle, and it might introduce real bugs. Also, since this code is basically in maintenance mode pending Keith's new SSA-based code generation, it's not clear we should spend any time fixing corner cases like this at all. Removed milestone.

**Comment by odeke-em** [comment] 2016-08-12 04:07
Duplicate of https://github.com/golang/go/issues/8355? cc @griesemer.

**Comment by griesemer** [comment] 2016-08-12 17:19
@odeke-em Sure. Closing as duplicate of #8355.

**Closed by griesemer** 2016-08-12 17:19 UTC
