### ISSUE TITLE
[][]byte + append

### ISSUE THREAD

**Issue by imkos** [golang/go#25001] opened 2018-04-23 06:18 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10.1

```go
var (
	b_test_val = []byte(`00000000000000000000000000000000000000000000
11111111111111111111111111111111111111111111
22222222222222222222222222222222222222222222
33333333333333333333333333333333333333333333
44444444444444444444444444444444444444444444
55555555555555555555555555555555555555555555
66666666666666666666666666666666666666666666
77777777777777777777777777777777777777777777
88888888888888888888888888888888888888888888
99999999999999999999999999999999999999999999`)
)

func main() {
	buf_r := bufio.NewReader(bytes.NewReader(b_test_val))
	bill_lines := make([][]byte, 0)
	for {
		b_line, _, err := buf_r.ReadLine()
		if err != nil {
			if err == io.EOF {
				break
			}
			continue
		}
		//fmt.Println("b_line:", string(b_line))
		bill_lines = append(bill_lines, b_line)
		/*
			for i := 0; i < len(bill_lines); i++ {
				fmt.Println("line no:", len(bill_lines), string(bill_lines[i]))
			}
		*/
	}
	for i := 0; i < len(bill_lines); i++ {
		fmt.Println(string(bill_lines[i]))
	}
}
```

### What did you expect to see?
```
00000000000000000000000000000000000000000000
11111111111111111111111111111111111111111111
22222222222222222222222222222222222222222222
33333333333333333333333333333333333333333333
44444444444444444444444444444444444444444444
55555555555555555555555555555555555555555555
66666666666666666666666666666666666666666666
77777777777777777777777777777777777777777777
88888888888888888888888888888888888888888888
99999999999999999999999999999999999999999999
```

### What did you see instead?

```
99999999999999999999999999999999999999999999
11111111111111111111111111111111111111111111
22222222222222222222222222222222222222222222
33333333333333333333333333333333333333333333
44444444444444444444444444444444444444444444
55555555555555555555555555555555555555555555
66666666666666666666666666666666666666666666
77777777777777777777777777777777777777777777
88888888888888888888888888888888888888888888
99999999999999999999999999999999999999999999
```

**Comment by AlexRouSg** [comment] 2018-04-23 07:35
https://golang.org/pkg/bufio/#Reader.ReadLine

> The returned buffer is only valid until the next call to ReadLine.

You need to make a copy of the returned `[]byte` if you want to store it. e.g. `bill_lines = append(bill_lines, append([]byte(nil), b_line...))`

**Comment by ALTree** [comment] 2018-04-23 07:39
Exactly. There's a reason the doc says:

> // ReadLine is a low-level line-reading primitive. Most callers should use
> // ReadBytes('\n') or ReadString('\n') instead or use a Scanner.

`ReadLine` is easy to misuse. Closing this, since it's not a bug.

**Closed by ALTree** 2018-04-23 07:39 UTC

**Comment by imkos** [comment] 2018-04-23 08:48
@ALTree , I don't understand what you mean.
```
func main() {
	buf_r := bufio.NewReader(bytes.NewReader(b_test_val))
	bill_lines := make([]string, 0)
	for {
		b_line, _, err := buf_r.ReadLine()
		if err != nil {
			if err == io.EOF {
				break
			}
			continue
		}
		fmt.Println("b_line:", string(b_line))
		bill_lines = append(bill_lines, string(b_line))
		/*
			for i := 0; i < len(bill_lines); i++ {
				fmt.Println("line no:", len(bill_lines), string(bill_lines[i]))
			}
		*/
	}
	for i := 0; i < len(bill_lines); i++ {
		fmt.Println(bill_lines[i])
	}
}
```
This little code snippet is fine.

> fmt.Println("b_line:", string(b_line))

**Comment by davecheney** [comment] 2018-04-23 09:05
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.
