### ISSUE TITLE
affected/package: internal compiler error: assertion failed

### ISSUE THREAD

**Issue by CarstenLeue** [golang/go#54165] opened 2022-08-01 10:55 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

compile a small go file

```go
package weird

type Weird[A any] interface {
}

type weird struct {
}

func MakeWeird[A any]() Weird[A] {
	return weird{}
}

func IsWeird[A any](data Weird[A]) bool {
	switch data.(type) {
	case weird:
		return true
	default:
		return false
	}
}

```

### What did you expect to see?

successful compile

### What did you see instead?

```
.\weird\weird.go:10:14: internal compiler error: assertion failed
```

**Comment by seankhliao** [comment] 2022-08-01 11:00
Doesn't repro on tip

**Comment by seankhliao** [comment] 2022-08-01 11:00
Duplicate of #53762

**Closed by seankhliao** 2022-08-01 11:00 UTC
