### ISSUE TITLE
runtime: SIGILL in dispatch_semaphore_wait

### ISSUE THREAD

**Issue by bcmills** [golang/go#32690] opened 2019-06-19 16:03 UTC
This probably shares the same underlying cause as #32655, but the symptom is different enough that we may want to track/test it independently.

The symptom is a `SIGILL` signal while compiling the `syscall` test, observed on the `darwin-amd64-race` builder (https://build.golang.org/log/085d8d50e32c489b492c845555a1019f765f4985):

```
# syscall [syscall.test]
SIGILL: illegal instruction
PC=0x7fff9b6e32f4 m=7 sigcode=1

goroutine 0 [idle]:
runtime.dispatch_semaphore_wait(0x50000f0, 0xffffffffffffffff, 0x0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/runtime/sys_darwin.go:351 +0x39
runtime.semasleep(0xffffffffffffffff, 0x104a18c)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/runtime/os_darwin.go:37 +0x41
runtime.notesleep(0xc000091648)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/runtime/lock_sema.go:173 +0xde
runtime.stopm()
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/runtime/proc.go:1928 +0xc0
runtime.findrunnable(0xc00002f900, 0x0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/runtime/proc.go:2391 +0x53f
runtime.schedule()
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/runtime/proc.go:2524 +0x2be
runtime.park_m(0xc000000a80)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/runtime/proc.go:2610 +0x9d
runtime.mcall(0x80000)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [runnable]:
cmd/compile/internal/gc.dclname(0xc000827980, 0xc00008cc00)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/cmd/compile/internal/gc/dcl.go:226 +0x82
cmd/compile/internal/gc.(*noder).declName(0xc000344bd0, 0xc000593680, 0xc00081ac98)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/cmd/compile/internal/gc/noder.go:460 +0x89
cmd/compile/internal/gc.(*noder).declNames(0xc000344bd0, 0xc0003e2e70, 0x1, 0x1, 0xc00069a5f0, 0xc00081ac01, 0x100883b)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/cmd/compile/internal/gc/noder.go:454 +0x7e
cmd/compile/internal/gc.(*noder).constDecl(0xc000344bd0, 0xc00058cf50, 0xc00034d578, 0x31902000000016, 0xc00058cf50, 0x1)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/cmd/compile/internal/gc/noder.go:383 +0x9c
cmd/compile/internal/gc.(*noder).decls(0xc000344bd0, 0xc0005ba000, 0x4ed, 0x500, 0x0, 0x0, 0xc00034d610)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/cmd/compile/internal/gc/noder.go:295 +0x44a
cmd/compile/internal/gc.(*noder).node(0xc000344bd0)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/cmd/compile/internal/gc/noder.go:244 +0xcc
cmd/compile/internal/gc.parseFiles(0xc000098160, 0x1a, 0x1a, 0x2)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/cmd/compile/internal/gc/noder.go:62 +0x326
cmd/compile/internal/gc.Main(0x1a553e8)
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/cmd/compile/internal/gc/main.go:512 +0x2549
main.main()
	/private/var/folders/dx/k53rs1s93538b4x20g46cj_w0000gn/T/workdir/go/src/cmd/compile/main.go:51 +0xac

rax    0x31
rbx    0x50000f0
rcx    0x7fff9b70376b
rdx    0x700001e4ec90
rdi    0x1f03
rsi    0xffffffffffffffff
rbp    0x700001e4ec30
rsp    0x700001e4ec00
r8     0xc000091500
r9     0x3
r10    0x700001e4ecf0
r11    0x246
r12    0xffffffffffffffff
r13    0x24021f0
r14    0x5000128
r15    0x0
rip    0x7fff9b6e32f4
rflags 0x10216
cs     0x2b
fs     0x0
gs     0x0
FAIL	syscall [build failed]
```

CC @eliasnaur @ianlancetaylor

**Comment by bcmills** [comment] 2019-06-19 16:18
Upon further reading, I think the symptom is the same too; the failure rate is just different.

**Comment by bcmills** [comment] 2019-06-19 16:18
Duplicate of #32655.

**Comment by aclements** [comment] 2019-06-25 18:00
#32655 was closed. Should this be closed, too?

**Comment by ianlancetaylor** [comment] 2019-06-25 18:18
This may now be a duplicate of #31264.  I'm not sure.

**Comment by ianlancetaylor** [comment] 2019-06-25 18:18
Or, not, probably not.  We can close this for now and reopen if something changes.

**Closed by ianlancetaylor** 2019-06-25 18:18 UTC
Labels: NeedsInvestigation, OS-Darwin, release-blocker
