### ISSUE TITLE
Imported package functions completion inside a defer and/or go func(){...}() fails.

### ISSUE THREAD

**Issue by byblix** [golang/go#32018] opened 2019-05-14 08:24 UTC
<pre>
go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
<details><summary>
<code>Click here to see</code> 
</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/simonblixenkrone/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/simonblixenkrone/dev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/simonblixenkrone/dev/gocode/basic-server/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b1/53jz_b9j1rb0nhhzmv4kwbk80000gn/T/go-build791443395=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I.e: I have an imported package "log", that returns different types of logging (Error, Info, Print etc). Inside a `defer` or `go func()` function, the autocompletion is completely broken. This applies to any imported package function, but not own functions defined in the workspace. Outside go func it works perfect.

### What did you expect to see?
Function auto-completion.

### What did you see instead?
Global variables. See images 1 and 2.

![1](https://user-images.githubusercontent.com/7870735/57682579-767f3000-7632-11e9-9df4-b379d1ef02a6.png)
![2](https://user-images.githubusercontent.com/7870735/57682580-767f3000-7632-11e9-9515-62dec27bd55a.png)

**Comment by stamblerre** [comment] 2019-05-14 17:04
Duplicate of https://github.com/golang/go/issues/29313

**Closed by stamblerre** 2019-05-14 17:04 UTC
