### ISSUE TITLE
proposal: Go 2: why generics does not support in a method

### ISSUE THREAD

**Issue by imsoul** [golang/go#54830] opened 2022-09-02 02:41 UTC
I want to make a handler like this:

```

type Handle func()

type UserMsgId int32
type GameMsgId int32

const (
	UserLogin UserMsgId = 1
	UserInfo  UserMsgId = 2
)

const (
	GameInfo GameMsgId = 2
)

type Handler struct {
	myHandler map[int32]Handle
}

func (h *Handler) Register[T UserMsgId | GameMsgId](msgid T, f func()) {
	h.myHandler[int32(msgid)] = f
}
```

but the method `Register` does not support generics parameter.

**Comment by griesemer** [comment] 2022-09-02 02:54
Duplicate of #49085.

**Closed by griesemer** 2022-09-02 02:54 UTC
Labels: Proposal
