### ISSUE TITLE
Cannot apply function from method expression

### ISSUE THREAD

**Issue by iporsut** [golang/go#23917] opened 2018-02-19 04:12 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
- go version go1.10 darwin/amd64

### Does this issue reproduce with the latest release?
- Yes.

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/username/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/username/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9k/pvfwqqzn6fqbpwghhrcjkm480000gn/T/go-build409818854=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

I try to appry method expression function from this code example

```go
package main

import (
	"fmt"
	"io"
	"log"
	"os"
)

func main() {
	var b []byte = make([]byte, 100)

	v := struct{ io.Reader }{os.Stdin}
	f := struct{ io.Reader }.Read
	n, err := f(v, b)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(n)
}
```

### What did you expect to see?

```
> go run temp.go 
0x1090c50
Hello
6
```

### What did you see instead?
```
# command-line-arguments
go.struct { io.Reader }.Read·f: relocation target go.struct { io.Reader }.Read not defined
go.struct { io.Reader }.Read·f: undefined: "go.struct { io.Reader }.Read"
```

But when I add `fmt.Println(f)` like this

```go
package main

import (
	"fmt"
	"io"
	"log"
	"os"
)

func main() {
	var b []byte = make([]byte, 100)

	v := struct{ io.Reader }{os.Stdin}
	f := struct{ io.Reader }.Read
	fmt.Println(f)
	n, err := f(v, b)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(n)
}
```

I can run with expected result.

**Comment by dominikh** [comment] 2018-02-19 04:14
This looks like a duplicate of https://github.com/golang/go/issues/22444 to me.

**Closed by dominikh** 2018-02-19 04:14 UTC
