### ISSUE TITLE
flag provided but not defined: -s

### ISSUE THREAD

**Issue by jordimassaguerpla** [golang/go#25648] opened 2018-05-30 18:44 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.10.2

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

openSUSE linux, Tumbleweed release, amd64

### What did you do?

I am trying to build a go program that used to be built with:

go install -s -v -p 4 -x -buildmode=pie github.com/coreos/etcd/cmd/etcd

### What did you expect to see?

No errors.

### What did you see instead?

flag provided but not defined: -s
usage: install [-i] [build flags] [packages]
Run 'go help install' for details.

I've been searching the docs and code and cannot find what "-s" used to do. I can remove the "-s" but then I cannot build the go program with go1.9, plus I don't know what "-s" was for.

Looking at the build log, seems "-s" is building on a local directory, as if I remove that flag when building with go1.9, I get the output

 go install -v -p 4 -x -buildmode=pie -ldflags=-s github.com/coreos/etcd/cmd/etcd
WORK=/tmp/go-build320550077
runtime/internal/sys
mkdir -p $WORK/runtime/internal/sys/_obj/
mkdir -p $WORK/runtime/internal/
cd /usr/lib64/go/1.9/src/runtime/internal/sys
/usr/lib64/go/1.9/pkg/tool/linux_amd64/compile -o $WORK/runtime/internal/sys.a -trimpath $WORK -shared -goversion go1.9.4 -p runtime/internal/sys -std -+ -complete -installsuffix shared -buildid a23af1a6e370d46dfa4361e29e6e9702fb0415d5 -D _/usr/lib64/go/1.9/src/runtime/internal/sys -I $WORK -pack ./arch.go ./arch_amd64.go ./intrinsics.go ./stubs.go ./sys.go ./zgoarch_amd64.go ./zgoos_linux.go ./zversion.go
mkdir -p /usr/lib64/go/1.9/pkg/linux_amd64_shared/runtime/internal/
go install runtime/internal/sys: mkdir /usr/lib64/go/1.9/pkg/linux_amd64_shared: permission denied

but if I use "-s", you see after the go install call:

go install -s -v -p 4 -x -buildmode=pie github.com/coreos/etcd/cmd/etcd
WORK=/tmp/go-build546320097                                            
runtime/internal/sys                                                   
mkdir -p $WORK/runtime/internal/sys/_obj/                              
mkdir -p $WORK/runtime/internal/                                       
cd /usr/lib64/go/1.9/src/runtime/internal/sys                          
/usr/lib64/go/1.9/pkg/tool/linux_amd64/compile -o $WORK/runtime/internal/sys.a -trimpath $WORK -shared -goversion go1.9.4 -p runtime/internal/sys -std -+ -complete -installsuffix shared -buildid a23af1a6e370d46dfa4361e29e6e9702fb0415d5 -D _/usr/lib64/go/1.9/src/runtime/internal/sys -I $WORK -pack ./arch.go ./arch_amd64.go ./intrinsics.go ./stubs.go ./sys.go ./zgoarch_amd64.go ./zgoos_linux.go ./zversion.go
runtime/internal/atomic                                                
mkdir -p $WORK/runtime/internal/atomic/_obj/           

What's "-s" for?
How can I have the same behaviour with go1.10?

**Comment by mvdan** [comment] 2018-05-30 18:52
I think you want `-ldflags=-s`, not just `-s`. That `-s` flag is just a linker flag, not a `go build` or `go install` flag.

**Comment by mvdan** [comment] 2018-05-30 19:22
I'm not sure - I'm merely pointing out that his two examples above are mixing `-ldflags=-s` and `-s`, which is what I believe is leading to confusion.

**Comment by ianlancetaylor** [comment] 2018-05-30 20:57
I don't see a Go bug here, so closing.  Please comment if you disagree.

**Closed by ianlancetaylor** 2018-05-30 20:57 UTC

**Comment by moio** [comment] 2018-05-31 05:44
@ianlancetaylor what I do not really understand is, why this did work with go 1.9. I believe this is the reason why @jordimassaguerpla opened this issue - because it could be a regression.

**Comment by AlexRouSg** [comment] 2018-05-31 05:59
@moio I downloaded go 1.9 linux amd64 (the exact version he is using) and tried his exact command `go install -s -v -p 4 -x -buildmode=pie` on a hello world program and it errored out.

**Comment by moio** [comment] 2018-05-31 06:04
Found the problem - it was an openSUSE specific patch. Sorry everyone for the noise.
