### ISSUE TITLE
affected/package: panic.go

### ISSUE THREAD

**Issue by bruceshao** [golang/go#60881] opened 2023-06-20 07:34 UTC
<pre>
$ go1.18
</pre>

```go
func main() {
	defer A1()
	defer A2()
	panic("panicA")
}

func A1() {
	p := recover()
	fmt.Println(p)
	panic("panicA1")
}

func A2() {
	defer B1()
	panic("panicA2")
}

func B1() {
	p := recover()
	fmt.Println(p)
	panic("panicB1")
}
```

Its output is:
```shell
panicA2
panicB1
panic: panicA
        panic: panicA2 [recovered]
        panic: panicB1 [recovered]
        panic: panicA1

```

but when I comment out the `panic("panicA1")`, its output is:
```shell
panicA2
panicB1
```

This result is incomprehensible, because we only recovered twice, but panic three times, at least one panic needs to be printed.

**Comment by Nasfame** [comment] 2023-06-20 07:46
I guess its fixed in go1.19+ - https://go.dev/play/p/-12zctgRQTs?v=gotip

**Comment by seankhliao** [comment] 2023-06-20 08:00
see above, we no longer support 1.18

**Closed by seankhliao** 2023-06-20 08:01 UTC

**Comment by bruceshao** [comment] 2023-06-20 09:37
> I guess its fixed in go1.19+ - https://go.dev/play/p/-12zctgRQTs?v=gotip

sorry, I tested it on version 1.19, when I comment out the panic("panicA1"), its output is still:

```shell
panicA2
panicB1
```

I commented out `panic("panicA1")`, not `panic("panicA2")`

**Comment by Nasfame** [comment] 2023-06-20 09:50
@bruceshao just share the playground link along with expected and actual output.

**Comment by Nasfame** [comment] 2023-06-20 10:11
@bruceshao I get u r point - next time just share the playground link for the reproducer.

I created a similar idea - it works https://go.dev/play/p/YYbvfFzknoc

Your code - https://go.dev/play/p/vfThWcf3s2Y?v=gotip

- panic: A [recovered] is missing in the stderr

**Comment by Nasfame** [comment] 2023-06-20 10:25
@bruceshao I get u r point - next time just share the playground link for the reproducer.

In this case, Min Reproducer - https://go.dev/play/p/DdcW1gHLcVO

I don't see any issues - since the all panics are recovered there is not need of panic trace in `std.err`.

**Comment by bruceshao** [comment] 2023-06-21 02:14
@Nasfame  ths. 
In your example the output is fine because there are two panic operations and two recover operations.
Look at this one below:
```go
func main() {
	defer A1()
	defer A2()
	panic("panicA")
}

func A1() {
	p := recover()
	fmt.Println(p)
	//panic("panicA1")
}

func A2() {
	defer B1()
	panic("panicA2")
}

func B1() {
	p := recover()
	fmt.Println(p)
	panic("panicB1")
}
```
In the above code, there are three panic operations, but there are only two recovers, which should require panic output.But the result is as follows:
```
panicA2
panicB1
```
I suspect that it should be related to the defer function being called inside the defer function, but I don't know the specific relationship.

After I uncomment the x in your code, the execution result is printed with `panic(1)` information, which is as expected.

@seankhliao hope to explain in detail
