### ISSUE TITLE
 src/cmd/gofmt: -r adds odd newlines when pattern matching

### ISSUE THREAD

**Issue by rski** [golang/go#57575] opened 2023-01-04 14:25 UTC
Just like https://github.com/golang/go/issues/57574, except I can't get a minimized repro, sorry! Closest I can offer is what it kind of looks like in the codebase I'm working, but I can't get it to happen with the snippet from #57574.

Basically, with an input like

```
func anotherLayer() error {
	return layer(
		func() error {
			return errorWithOneArg1(func() error {
				// This comment is erased, but let's pretend the other bug is fixed
				return errors.New("abc")
			}, 30)
		}, "test")
}
```
I got 
```

func anotherLayer() error {
	return layer(
		func() error {
			return errorWithOneArg1(func() error {
				// This comment is erased, but let's pretend the other bug is fixed
				return errors.New("abc")
			}, 30)
		}, 

			"test")
}
```

I can repro it every time in the code I am actually working on but again, no minimized repro, apologies. I might try again to get one soon.

**Comment by rsc** [comment] 2023-01-04 17:15
This is a duplicate of #57575. The newline is being printed to adjust the line numbering, which is out of sync because of the missing comment.

**Closed by rsc** 2023-01-04 17:15 UTC
