### ISSUE TITLE
sync: RWMutex.RLock failed return panic

### ISSUE THREAD

**Issue by Mr1X** [golang/go#47004] opened 2021-07-01 05:20 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.13.12 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://mirrors.aliyun.com/goproxy/"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build239103222=/tmp/go-build"
</pre></details>

### What did you do?

<pre>
type TradeTimeCal struct {
	remoteURI     string
	cLock         sync.RWMutex
}

func NewTradeTimeCal(remoteURI string, updateHour int) *TradeTimeCal {
	newone := &TradeTimeCal{
		remoteURI:  remoteURI,
		updateHour: updateHour,
	}
	return newone
}

func (this *TradeTimeCal) IsTradingday(exchangid, tradeday string) bool {
	this.cLock.RLock()
        // do something
	this.cLock.RUnlock()
	if !ok {
		return false
	}
	return true
}
</pre>

### What did you expect to see?

when I call the function IsTradingday，i want RLock success every time

### What did you see instead?

when I call the function IsTradingday, it return panic accidental，Not necessarily

<pre>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc00edb]
goroutine 57 [running]:
sync.(*RWMutex).RLock(...)
	/usr/local/go/src/sync/rwmutex.go:48
jcqts/tradetimesdk.(*TradeTimeCal).IsTradingday(0x0, 0xc00037a390, 0xa, 0xc11622c430, 0x8, 0xc11622c430)
	/tradetimesdk/tradetimesdk.go:114 +0x2b
</pre>

**Comment by davecheney** [comment] 2021-07-01 08:55
This looks like memory corruption. Have you tried running your program under the race detector? See https://blog.golang.org/race-detector .

**Comment by dmitshur** [comment] 2021-07-01 20:52
Is this a problem you're able to reproduce, or was this just a single occurrence? If you're able to reproduce, does it still happen with a newer Go version (1.16 or 1.15)?

**Comment by Mr1X** [comment] 2021-07-02 01:21
> Is this a problem you're able to reproduce, or was this just a single occurrence? If you're able to reproduce, does it still happen with a newer Go version (1.16 or 1.15)?

I'm trying to upgrade the go version in production, thank you

**Comment by Mr1X** [comment] 2021-07-02 01:27
> This looks like memory corruption. Have you tried running your program under the race detector? See https://blog.golang.org/race-detector .

I'll try upgrade go version and run program under the race detector. Thank you

**Comment by BenLubar** [comment] 2021-07-20 04:56
The stack trace shows the first argument to IsTradingDay being 0x0, so `this.cLock` is dereferencing a nil pointer.

**Comment by davecheney** [comment] 2021-07-20 05:07
Closing as answered.

**Closed by davecheney** 2021-07-20 05:07 UTC
Labels: NeedsInvestigation, WaitingForInfo
