### ISSUE TITLE
Virus detected in Go 1.16 for Windows amd64? Bitdefender detected Go\pkg\tool\windows_amd64\asm.exe is infected with Gen:Variant.Bulz.341449

### ISSUE THREAD

**Issue by jdavidzapatab** [golang/go#44323] opened 2021-02-17 06:08 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes. In fact it happened only with the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\jdavi\AppData\Local\go-build
set GOENV=C:\Users\jdavi\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\jdavi\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\jdavi\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\jdavi\AppData\Local\Temp\go-build625648704=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

Using Golang IDE I tried building a little WebAssembly project. The IDE's build command uses GOOS=js GOARCH=wasm. The IDE's build output says:

<pre>
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\jdavi\go #gosetup
"C:\Program Files\Go\bin\go.exe" build -o C:\Users\jdavi\code\tests\LocalIP\dist\localip.wasm C:\Users\jdavi\code\tests\LocalIP\main.go #gosetup
go tool asm: fork/exec C:\Program Files\Go\pkg\tool\windows_amd64\asm.exe: Access is denied.

Compilation finished with exit code 1
</pre>

and immediately after my Bitdefender antivirus reported me:
<pre>
The file C:\Program Files\Go\pkg\tool\windows_amd64\asm.exe is infected with Gen:Variant.Bulz.341449 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.
</pre>

### What did you expect to see?
I expected a successful build, as it was happening on the previous version.

### What did you see instead?
![2021-02-17 00_52_29](https://user-images.githubusercontent.com/763974/108162929-1c8b8400-70bc-11eb-9829-79be1702eb24.png)

### Extra notes

I was working correctly a few hours ago with the previous version of Go (1.15.8) with the same project. All I did was download and install Go 1.16 using the official download link from the official website, and then tried re-building the same project.

**Comment by AlexRouSg** [comment] 2021-02-17 06:18
https://golang.org/doc/faq#virus

> This is a common occurrence, especially on Windows machines, and is almost always a false positive. Commercial virus scanning programs are often confused by the structure of Go binaries, which they don't see as often as those compiled from other languages.

**Comment by davecheney** [comment] 2021-02-17 06:27
I'm going to close this as it is very likely a false positive. Please comment here if you believe that this is not correct.

**Closed by davecheney** 2021-02-17 06:27 UTC

**Comment by jdavidzapatab** [comment] 2021-02-17 06:37
> I'm going to close this as it is very likely a false positive. Please comment here if you believe that this is not correct.

Just added that specific file `C:\Program Files\Go\pkg\tool\windows_amd64\asm.exe` to the Antivirus exceptions, and it is working correctly now.

Thanks.

**Comment by SubEdict** [comment] 2021-04-02 12:00
This is how it's looks on Windows 10 Defender after update to Elementum 0.1.74:

Detected: **Trojan:Win32/Zpevdo.B**
Details: This program is dangerous and executes commands from an attacker.
Affected items: file:
file: C:\Users\me\AppData\Roaming\Kodi\addons\plugin.video.elementum\resources\bin\windows_x64\elementum.exe
file: C:\Users\me\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.elementum\bin\windows_x64\elementum.exe

**Comment by IndustrialPerformanceDude** [comment] 2021-04-26 12:33
Hi Guys.
Started to use pyinstaller this morning.
While it was creating my dist and build folders, BitDefender Total Security stopped some processes and redirected some files and the dist folder to its "quarantine" folder.

In the "Warnings" tab, inside BitDefender, I get the message :
Infected file detected
an hour ago
Feature:
Antivirus
The file C:\Users\BPM Inc\Documents\BPM_VSCode\dist\Setup.exe is infected with Gen:Variant.Bulz.445003 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

From which I can "ReStore" the files and folders.
But it doesn't feel great.

So I opened a ticket at BitDefender Support to have a confirmed way to reconfigure the antivirus to let my stuff what it is supposed to do.

VS Code version : 1.55.2
Python version : 3.9.4150.0
pyinstaller version : 4.3
windows 10 20H2 (all software have been reinstalled after 20H2 update)

Note:
If I didn't post at the right place, tell me and I will move it.
But right now, this thread is the only Gen:Variant.Bulz subject.

**Comment by ianlancetaylor** [comment] 2021-04-26 22:42
@IndustrialPerformanceDude It's OK to post here but the Go project is not going to be taking any action on this.

**Comment by IndustrialPerformanceDude** [comment] 2021-04-27 16:05
Thanks for the response, ianlancetaylor.
So should I start another thread somewhere else on GitHub ?
Because if I don't receive any support from the website community, it doesn't do any good to anybody.
Do you have a suggestion ?
Should I start a thread about pyinstaller ?

**Comment by ianlancetaylor** [comment] 2021-04-27 19:30
@IndustrialPerformanceDude The Go project uses the issue tracker for identifying and fixing problems.  If you are looking for support, you will get better and faster answers if you use a forum.  See https://golang.org/wiki/Questions.

**Comment by AndrewWPhillips** [comment] 2022-04-11 02:24
> ...So should I start another thread somewhere else on GitHub ?
Unless pyinstaller is written in Go (which I doubt) then this is definitely the wrong place.  Even then I suspect this is a false positive (like the OP's issue, though the OP *was* using a .exe generated by Go), so probably just taken up with BitDefender.
