### ISSUE TITLE
x/mobile: Unable to build basic sample with stripped NDK

### ISSUE THREAD

**Issue by nikolay-turpitko** [golang/go#16261] opened 2016-07-04 06:58 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

        go version go1.6.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

        GOARCH="amd64"
        GOBIN=""
        GOEXE=""
        GOHOSTARCH="amd64"
        GOHOSTOS="linux"
        GOOS="linux"
        GOPATH="/home/nick/go"
        GORACE=""
        GOROOT="/home/nick/.local/share/umake/go/go-lang"
        GOTOOLDIR="/home/nick/.local/share/umake/go/go-lang/pkg/tool/linux_amd64"
        GO15VENDOREXPERIMENT="1"
        CC="gcc"
        GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
        CXX="g++"
        CGO_ENABLED="1"

        Ubuntu 16.04 LTS
        4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

        $ go get golang.org/x/mobile/cmd/gomobile
        $ gomobile init
        $ go get -d golang.org/x/mobile/example/basic
        $ gomobile build -target=android golang.org/x/mobile/example/basic

4. What did you expect to see?

Build should complete without error messages.

5. What did you see instead?

        gomobile: /home/nick/go/pkg/gomobile/android-ndk-r12/x86/bin/i686-linux-android-nm /tmp/gomobile-work-840948909/lib/x86/libbasic.so: fork/exec /home/nick/go/pkg/gomobile/android-ndk-r12/x86/bin/i686-linux-android-nm: no such file or directory

**Comment:** there is no such a file indeed. But when I changed mobile/cmd/gomobile/init.go line 31 (`var useStrippedNDK = true`) to `var useStrippedNDK = false`, re-compiled, re-init and re-build sample, it was able to build it. And indeed `i686-linux-android-nm` is now in place.

**Comment by hyangah** [comment] 2016-07-07 15:31
duplicate of #16268

**Closed by hyangah** 2016-07-07 15:31 UTC
