### ISSUE TITLE
go/format: leading spaces aren't inserted for comments on first pass

### ISSUE THREAD

**Issue by lfolger** [golang/go#63642] opened 2023-10-20 12:36 UTC
### What version of Go are you using (`go version`)?

go1.21 (discovered on tip)

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Whatever play.go.dev is using.

### What did you do?

```
package main

import (
	"fmt"
	"go/format"

	"github.com/google/go-cmp/cmp"
)

var in = []byte(`package main
		//some comment
		var x string`)

func main() {
	first_format, err := format.Source(in)
	if err != nil {
		fmt.Println(err)
		return
	}
	second_format, err := format.Source(first_format)
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println(cmp.Diff(string(first_format), string(second_format)))
}
```

https://go.dev/play/p/b4foaIeTooZ

### What did you expect to see?

I expected no diff between formatting the file once and formatting the input twice.

### What did you see instead?

The first formatting removed the identation but does not add a space between `//` and `some comment`.
The second formatting adds a space between `//` and `some comment`.
As far as I can tell go/format.Source only adds spaces between `//` and the comment text if these comment is not indented.

**Comment by seankhliao** [comment] 2023-10-20 12:42
cc @griesemer @mvdan 

see also #62559

**Comment by mknyszek** [comment] 2023-11-01 19:09
Should we close this as a duplicate of https://github.com/golang/go/issues/62559?

**Comment by mknyszek** [comment] 2023-11-01 19:09
Optimistically closing, let me know if we should reopen.

**Closed by mknyszek** 2023-11-01 19:09 UTC
Labels: NeedsInvestigation, Tools, compiler/runtime
