### ISSUE TITLE
encoding/json: Unmarshal into struct field or a map does not validate invalid json.Number

### ISSUE THREAD

**Issue by brenol** [golang/go#14702] opened 2016-03-08 03:30 UTC
1. What version of Go are you using (`go version`)?
   go1.6 linux/amd64
2. What operating system and processor architecture are you using (`go env`)?
   linux/amd64
3. What did you do?
   (Use play.golang.org to provide a runnable example, if possible.)
   http://play.golang.org/p/8QZq-0vRch
4. What did you expect to see?
   Unmarshal did not accept a invalid JSON as a json.Number, instead, it should raise an error
5. What did you see instead?
   Unmarshal accepted a invalid JSON as a json.Number and did not raise an error
#10281 is the one that actually fixed this issue, however, shouldn't unmarshal should also raise an error? Right now only Marshalling is an raising a error.

@edit
I actually did some further testing and it only happens when Unmarshalling into a struct field, as can be seen in the updated snippet above.

@edit2
It also happens when using map[string]json.Number and I have updated the test case accordingly.

**Comment by erikdubbelboer** [comment] 2016-10-16 08:49
This could be fixed by adding the following lines after https://github.com/golang/go/blob/0cc400f0e7e73e1ee870d803b8faf1904c0c9ec3/src/encoding/json/decode.go#L915
```go
if v.Type() == numberType && !isValidNumber(string(s)) {
	d.error(fmt.Errorf("json: invalid number literal, trying to unmarshal %q into Number", item))
}
```

The question is if we really want this as it would kinda break how it currently works. People who currently abuse `json.Number` should switch to `json.RawMessage`. I'm not sure if this is seen as breaking the Go 1 API.

If you thing this would be good to patch I can create a change in gerrit.

**Comment by bradfitz** [comment] 2016-11-04 05:55
Sorry, this was stuck in the "Unplanned" limbo state which we have since stopped using.

I don't believe anybody has looked at this. I'll leave the decision on the bug to @rsc.

**Comment by rsc** [comment] 2017-11-22 03:09
Leaving for the next round of JSON work.

**Closed** 2019-09-16 21:57 UTC
Labels: NeedsDecision

**Comment by mvrhov** [comment] 2020-02-18 08:54
This change just broke the decoding of `"field":""` which previously worked and the use of json.Number was on purpose. I don't have the option to change the json input I'm getting.

**Comment by odeke-em** [comment] 2020-02-18 10:47
Miha, could you please provide a minimal reproduction that doesn’t work and
we can use that for a test case and perhaps for if/when we make a revert?
Thank you.

**Comment by erikdubbelboer** [comment] 2020-02-18 13:46
@odeke-em I guess this is the code @mvrhov is trying to use: https://play.golang.org/p/glvZxWT2to8

@mvrhov If you want to support broken input like that you'll have to use [json.RawMessage](https://golang.org/pkg/encoding/json/#RawMessage) like this: https://play.golang.org/p/iL5Q62g0Lkm

**Comment by mvdan** [comment] 2020-02-20 09:23
Please continue the discussion in #37308. If you have a sample of the real scenario that broke for you, please add it there.
