### ISSUE TITLE
cmd/go: second parameter of replace is a network package, it behavior needs to be like require

### ISSUE THREAD

**Issue by yesuu** [golang/go#26648] opened 2018-07-27 17:19 UTC
### What version of Go are you using (`go version`)?

    go version go1.11beta2 linux/amd64
    go version devel +6b9c782f9f Wed Aug 1 00:57:00 2018 +0000 linux/amd64

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

this is `go.mod`:

    module project/deploy

    require (
	    github.com/gin-gonic/gin v1.1.4
	    golang.org/x/net/context v0.0.0 // indirect
    )

    replace (
	    golang.org/x/net/context => github.com/golang/net/context v0.0.0-20180724234803-3673e40ba22
    )

execute the command `go build`:

    go: finding github.com/golang/net/context v0.0.0-20180724234803-3673e40ba225
    go: github.com/golang/net/context@v0.0.0-20180724234803-3673e40ba225: missing github.com/golang/net/context/go.mod at revision 3673e40ba225
    go: error loading module requirements

if the version of the second parameter is write as `v0.0.0`:

    module project/deploy

    require (
	    github.com/gin-gonic/gin v1.1.4
	    golang.org/x/net/context v0.0.0 // indirect
    )

    replace (
	    golang.org/x/net/context => github.com/golang/net/context v0.0.0
    )

it's actually trying to find `v0.0.0`:

    go: finding github.com/golang/net/context v0.0.0
    go: github.com/golang/net/context@v0.0.0: unknown revision context/v0.0.0
    go: error loading module requirements

As the title says, it's a bug.

**Comment by yesuu** [comment] 2018-08-02 00:06
When retesting this problem, I found out if:

    module project/deploy
    require (
        github.com/gin-gonic/gin/binding v0.0.0-20180720165255-220e8d34538f
    )

the `go build` output:

    go: finding github.com/gin-gonic/gin/binding v0.0.0-20180720165255-220e8d34538f
    go: github.com/gin-gonic/gin/binding@v0.0.0-20180720165255-220e8d34538f: missing github.com/gin-gonic/gin/binding/go.mod at revision 220e8d34538f
    go: error loading module requirements

Obviously the second parameter of replace is same with the behavior of require.

The real problem is `go.mod` only supports module and don't support package. Because if I write module path, it works fine:

    module project/deploy
    require (
        github.com/gin-gonic/gin v0.0.0-20180720165255-220e8d34538f
    )

even if I import `github.com/gin-gonic/gin/binding`, it still use the module path `github.com/gin-gonic/gin`.

**Comment by ianlancetaylor** [comment] 2018-08-03 16:26
CC @bcmills

**Comment by bcmills** [comment] 2018-08-03 16:38
`github.com/golang/net/context` is a package path, not a module path. (The corresponding module path is just `github.com/golang/net`.)

If you use `go get` to construct the `go.mod` file rather than writing it by hand, you should find that `go get github.com/golang/net/context@v0.0.0-20180724234803-3673e40ba22` actually resolves that to a `go.mod` line like:

```
require github.com/golang/net v0.0.0-20180724234803-3673e40ba22
```
(#26602 notwithstanding)

The same is true for your `replace` directive: it must use module paths, not package paths.
```
replace (
	golang.org/x/net => github.com/golang/net v0.0.0-20180724234803-3673e40ba22
)
```

**Comment by bcmills** [comment] 2018-08-03 16:41
The fact that we attempt a network fetch despite the replacement is #26241.

With the issue of module path vs. package path cleared up, I believe that this issue is a duplicate of that one. Please let me know if there are any remaining issues reported here that I've missed.

**Closed by bcmills** 2018-08-03 16:41 UTC
Labels: NeedsInvestigation, modules
