### ISSUE TITLE
cmd/go2go: += operation causes problems over string and int

### ISSUE THREAD

**Issue by james-antill** [golang/go#39641] opened 2020-06-17 06:56 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

https://go2goplay.golang.org/ as of 2020-06-17 06:53 UTC

### What did you do?

https://go2goplay.golang.org/p/y9j7WlgNHWy

### What did you expect to see?

If you change Adder to be just int or just string, then everything works, only when both are used at once does it fail.

### What did you see instead?

invalid operation: operator + not defined for ret (variable of type T)

**Comment by mattn** [comment] 2020-06-17 06:59
Same issue https://github.com/golang/go/issues/39623 ?

**Comment by davecheney** [comment] 2020-06-17 07:13
Duplicate of #39623

**Closed by davecheney** 2020-06-17 07:13 UTC
