### ISSUE TITLE
x/mobile: no current JVM

### ISSUE THREAD

**Issue by CanRui-Wu** [golang/go#33254] opened 2019-07-24 06:30 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code></summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wucanrui/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wucanrui/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0_/j6m36l9s0psg9xm5ggt2_b680000gp/T/go-build347025139=/tmp/go-build -gno-record-gcc-switches -fno-common" 
</pre></details>

### What did you do?
go get -u golang.org/x/mobile/cmd/...
cd $GOPATH/bin
mv gomobile /usr/local/bin
mv gobind /usr/local/bin
gomobile bind -target=android -v testpkg
gomobile bind -target=android -v ***(mypackage)

### What did you expect to see?
Everything is ok.

### What did you see instead?
I successfully build two aar files(testpkg.aar  ***.aar).

 However, both testpkg.aar and ***.aar make the app crash when using asset.Open with the log "I/GoLog: asset: no current JVM".

With API 29, the log before crash is "A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 5481 (mygoapplication), pid 4382 (mygoapplication)". 

I have tested in android simulator(API 24,28,29) and real device(API 28).  

Besides, I did not use (vendor, mod , dev) to manage my package. All I did is to use "go get" and "gomobile bind".

**Comment by timcooijmans** [comment] 2019-07-26 10:42
This is caused by the change to make gomobile Android-Q compatible. Can you try to provide the `ApplicationContext` bij using thet static method `Seq.setContext(Context context)` before getting the assets?

**Comment by CanRui-Wu** [comment] 2019-07-29 13:51
> This is caused by the change to make gomobile Android-Q compatible. Can you try to provide the `ApplicationContext` by using the static method `Seq.setContext(Context context)` before getting the assets?

Thank you. I add Seq.setContext(getApplicationContext()) and it works. Do I have to set the context in my app? Why this cannot automatic done by gomobile?

**Comment by timcooijmans** [comment] 2019-07-29 14:25
Yes you have to set the context (at least) once in your app or library (for example in the `Application.onCreate()`-method.

There is no (allowed) method to get the `ApplicationContext` as a library (such as a gobind-based library). The only option is for the application to provide a reference on initialization. 
Previously gomobile used reflection to statically get the `ApplicationContext` by using a non-published method. However this method is blacklisted in Android-Q causing warnings and exceptions.

**Comment by CanRui-Wu** [comment] 2019-07-29 15:04
> Yes you have to set the context (at least) once in your app or library (for example in the `Application.onCreate()`-method.
> 
> There is no (allowed) method to get the `ApplicationContext` as a library (such as a gobind-based library). The only option is to let the application provide a reference on initialization of the library. This is now implemented in `Seq.setContext(Context context)`.
> Previously gomobile used reflection to statically get the `ApplicationContext` by using a non-published method. However this method is blacklisted in Android-Q causing warnings and exceptions.

Thank you very much for detail instruction. BTW, I find the file 'bind_iosapp.go' do not handle the assets subdirectory. Then, I get an error 'no such file or directory' when I still use asset.Open api in IOS. How can I use asset in IOS by using golang?

**Comment by timcooijmans** [comment] 2019-07-29 16:36
I'm sorry I'm not familiar with the `asset` package on iOS. Please open another issue describing your issue (try to provide an example reproducing the problem) and close this ticket as this issue is resolved.

**Closed** 2019-07-29 16:43 UTC
Labels: mobile
