### ISSUE TITLE
io/ioutil: ReadDir fails to list directory for bare drive path

### ISSUE THREAD

**Issue by adminck** [golang/go#45514] opened 2021-04-12 09:55 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=F:\go\GOPATH
set GOPRIVATE=
set GOPROXY=https://goproxy.io
set GOROOT=F:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=F:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADM
INI~1\AppData\Local\Temp\go-build731386154=/tmp/go-build -gno-record-gcc-switche
s
</pre></details>

### What did you do?
Create new program from scratch, write，build:
<pre>
func main() {
	rd, _ := ioutil.ReadDir("f:")
	for _, fi := range rd {
		fmt.Println(fi.Name())
	}
}
</pre>
File running path “F:\\test\”
### What did you expect to see?

Output f root directory file list

### What did you see instead?
Output “F:\\test\” directory file list

**Comment by adminck** [comment] 2021-04-12 10:03
For Windows API FindFirstFile, if the parameter is the program running drive letter and there is no "\" after the drive letter, the list of files in the program running directory will be output.  recommended  "os\file_windows.go " Adding "\" in 115 line splicing path

**Comment by mknyszek** [comment] 2021-04-12 17:41
CC @griesemer @ianlancetaylor @bradfitz via https://dev.golang.org/owners. We don't actually seem to have granular owners for `io` subpackages. Also @rsc who deprecated all of `ioutil`.

@adminck have you tried using `os.ReadDir` instead? The documentation states that that's the better option (and more correct option) these days.

**Comment by mknyszek** [comment] 2021-04-12 17:42
Of course, if this is broken in some new way, we should fix it.

**Comment by slrz** [comment] 2021-04-12 21:55
> For Windows API FindFirstFile, if the parameter is the program running drive letter and there is no "\" after the drive letter, the list of files in the program running directory will be output.

Isn't this the intended behaviour? Windows keeps a separate working directory per drive letter and I presume this is how to access it?

**Comment by opennota** [comment] 2021-04-14 06:00
Works as intended. Run `cd c:\Users` and then `dir c:` in the `cmd` shell. It won't list the contents of the root directory.

**Comment by seankhliao** [comment] 2021-04-14 06:53
Closing as working as intended

**Closed by seankhliao** 2021-04-14 06:53 UTC
Labels: NeedsInvestigation, OS-Windows
