### ISSUE TITLE
 how can i read a file as fast as impossible

### ISSUE THREAD

**Issue by justkeepsimple** [golang/go#41472] opened 2020-09-18 10:04 UTC
### What version of Go are you using (`go version`)?
1.14.7

### What did you do?

bytes := make([]byte, writesBytes)
file.ReadAt(bytes, acf.NextLba)

i used this method to read a file, but i want to read the file like this
`ssize_t pread64(int fildes, void *buf, size_t nbyte, off64_t offset);`

i don't care about the content of the file 
i hope i can read a file as fast as impossible
so, how can i do

**Comment by ALTree** [comment] 2020-09-18 10:05
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-09-18 10:05 UTC
