### ISSUE TITLE
cmd/vet: build tags in raw string literals should be ignored

### ISSUE THREAD

**Issue by 0xmohit** [golang/go#13533] opened 2015-12-08 09:41 UTC
`main.go`:

``` go
package main
const foo = `
//+build ignore
`
```

Running `vet` produces:

```
main.go:3: +build comment must appear before package clause and be followed by a blank line
```

This also contributes to noise in the vet output for core, e.g. 

```
./src/crypto/x509/root_darwin_arm_gen.go:181: +build comment must appear before package clause and be followed by a blank line
./src/crypto/x509/root_darwin_arm_gen.go:182: +build comment must appear before package clause and be followed by a blank line
./src/crypto/x509/root_darwin_arm_gen.go:183: +build comment must appear before package clause and be followed by a blank line
```

**Comment by cznic** [comment] 2015-12-08 10:29
Build tags detection by the go build system is by design line oriented to avoid unnecessary parsing. The vet tool does the same thing, which seems correct to me.

**Comment by ianlancetaylor** [comment] 2015-12-08 13:35
@cznic That is a fair point, but in this case the other tools are not going to recognize the +build comment, which is what cmd/vet is saying anyhow.  In a case like this it seems worth skipping raw string literals if not too complicated.

**Comment by tmthrgd** [comment] 2017-04-10 23:31
This bug is actually a duplicate of #12269, I guess no one spotted that. That bug was closed by @robpike with the given reason "Not worth the trouble to fix."

I've hit this bug myself ([here](https://github.com/tmthrgd/go-bindata/blob/eea405957029908d3e235f8d1c8749213bd1985f/header.go#L71) - tmthrgd/go-bindata#4), it's nothing all too major of course. Although it would be nice if go vet wasn't throwing up this false positive.

Is there any chance this bug might get fixed or is it still "not worth the trouble"?

**Comment by ianlancetaylor** [comment] 2017-04-10 23:58
Yes, it's probably not worth doing.  Closing.

**Comment by josharian** [comment] 2018-03-13 15:23
Now that vet is on by default, and we are aiming for 100% accuracy on such checks, and we’ve gotten a handful of dups of this recently, I think we should consider fixing this. Yes, parsing is more expensive than line-oriented searches, but compared to the rest of vet, which does full typechecking, I doubt it matters much, particularly since we only need parse up to the package clause.

**Comment by josharian** [comment] 2018-03-13 15:37
Scratch the comment about only parsing to the package clause.  Still shouldn’t be too expensive.

**Comment by griesemer** [comment] 2018-03-13 16:53
Only lexing (scanning) is needed, no parsing.

**Comment by robpike** [comment] 2018-03-13 22:28
I would think the right fix is a complete rewrite of the module that looks at the comment-decorated parse tree, which we have. The parse will honor valid build comments but disregard bad ones, which would still be present as comments in the tree.

**Closed** 2018-05-29 17:02 UTC
Labels: NeedsDecision
