### ISSUE TITLE
How to completely remove package from mod cache?

### ISSUE THREAD

**Issue by kolkov** [golang/go#34934] opened 2019-10-16 12:52 UTC
I could not find in the documentation how to remove the package completely from the system. Can I only clear the system cache completely, or am I wrong?
Thanks!

**Comment by ALTree** [comment] 2019-10-16 13:08
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2019-10-16 13:08 UTC

**Comment by kolkov** [comment] 2019-10-16 13:29
Well, I don’t know, I don’t know, for me personally this is a bug, since such an opportunity is not provided for in the package management system.
