### ISSUE TITLE
cmd/go: "cannot find module providing package" with Go 1.12 and Git 2.21.0

### ISSUE THREAD

**Issue by Phillip-Gabler** [golang/go#31143] opened 2019-03-29 15:56 UTC
### What version of Go are you using (`go version`)?
go version go1.12.1 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN="/home/pgable000/GoWorkspace/bin"
GOCACHE="/home/pgable000/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pgable000/GoWorkspace"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pgable000/GoWorkspace/src/github.enterprise.com/pgable000/program/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build454419636=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

ALSO -- git version 2.21.0, and
GO111MODULE=on

### What did you do?

"go build" an executable using modules in a private (enterprise) github repository.

Module included as:

package main

import (
	"fmt"
	ecs "github.enterprise.com/pgable000/<module name>"
	"net/url"
)

Module and program using module exist in directory tree as

/home/pgable000/GoWorkspace/src/github.enterprise.com/pgable000/module_name
/home/pgable000/GoWorkspace/src/github.enterprise.com/pgable000/program_name

Both the module and program have go.mod files

Here is a simple test.go that demonstrates the problem I am having:

package main

import (
	"fmt"
	ecs "github.enterprise.com/pgable000/elasticCommonSchema"
)

func main() {
	fmt.Println(ecs.DefaultMapping)
}

"go build" produces:

[pgable000@elk-es-wc-01 test]$ go build
build github.enterprise.com/pgable000/test: cannot load github.enterprise.com/pgable000/elasticCommonSchema: cannot find module providing package github.enterprise.com/pgable000/elasticCommonSchema

### What did you expect to see?
I expected an error-free build.

### What did you see instead?
build program_name: cannot load github.enterprise.com/pgable000/module_name: cannot find module providing package github.enterprise.com/pgable000/module_name

.gitconfig:

[user]
        name = Phillip Gabler
        email = phillip_gabler@enterprise.com

[url "ssh://git@github.enterprise.com"]
        insteadOf = https://github.enterprise.com

**Comment by Phillip-Gabler** [comment] 2019-03-29 15:58
The above omitted my `<enterprise>` where the ".."s are shown./ Sorry

**Comment by bcmills** [comment] 2019-03-29 16:31
Were there other errors printed before the `cannot load` message?
What happens if you run `curl -L https://github.enterprise.com/pgable000/module_name?go-get=1`?

I suspect this is a duplicate of #26232, but without more detail it's hard to be certain.

**Comment by Phillip-Gabler** [comment] 2019-03-29 16:43
This is the complete output of the "go build" command:

[pgable000@elk-es-wc-01 test]$ go build
build github.enterprise.com/pgable000/test: cannot load github.enterprise.com/pgable000/elasticCommonSchema: cannot find module providing package github.enterprise.com/pgable000/elasticCommonSchema

When I run:

curl -L https://github.enterprise.com/pgable000/elasticCommonSchema?go-get=1

I get:

[pgable000@elk-es-wc-01 elasticCommonSchema]$ curl -L https://github.enterprise.com/pgable000/elasticCommonSchema?go-get=1

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">



  <title>Go remote import path metadata</title>
  <meta name="go-import" content="github.enterprise.com/pgable000/elasticCommonSchema git https://github.enterprise.com/pgable000/elasticCommonSchema.git">



  <link rel="mask-icon" href="https://github.enterprise.com/pinned-octocat.svg" color="#000000">
  <link rel="icon" type="image/x-icon" class="js-site-favicon" href="https://github.enterprise.com/favicon-ent.ico">

<meta name="theme-color" content="#1e2327">



  <link rel="manifest" href="/manifest.json" crossOrigin="use-credentials">

  </head>

  <body>
    
  

  </body>
</html>

Is this what you expected?

**Comment by Phillip-Gabler** [comment] 2019-03-29 18:10
FWIW, I can't build on Windows, either.

**Comment by bcmills** [comment] 2019-04-01 21:23
So does the repository hosted at `https://github.enterprise.com/pgable000/elasticCommonSchema.git` exist and contain `.go` source files at the root?

(What happens if you run:
```
git clone https://github.enterprise.com/pgable000/elasticCommonSchema.git && cd elasticCommonSchema && ls *.go
```
?)

**Comment by marco-m** [comment] 2019-05-22 19:48
@Phillip-Gabler ping

**Comment by SUMUKHA-PK** [comment] 2019-06-07 16:29
Is there an update on this?

**Comment by bcmills** [comment] 2019-06-07 16:35
@SUMUKHA-PK, this issue is labeled `WaitingForInfo`. Absent the requested clarification, it is safe to assume that there is no update.

**Closed** 2019-07-07 16:35 UTC
Labels: WaitingForInfo, modules
