### ISSUE TITLE
 internal compiler error: binaryOp: bad operation

### ISSUE THREAD

**Issue by hexaflex** [golang/go#31325] opened 2019-04-07 12:46 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.12.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\hf\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\code\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\hf\AppData\Local\Temp\go-build639447286=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

https://play.golang.org/p/CAilBT0YfzY

### What did you expect to see?

An error message indicating the operation is not supported on floating point values.

### What did you see instead?

<code>
std\lib.go:80:10: internal compiler error: binaryOp: bad operation: 2.3 ^ 2

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
</code>

**Comment by cuonglm** [comment] 2019-04-07 12:55
Duplicate of https://github.com/golang/go/issues/31060, already fixed in tip

**Closed** 2019-04-07 12:56 UTC
