### ISSUE TITLE
sync: Add a method to WaitGroup to simplify Add, Done, go func()

### ISSUE THREAD

**Issue by darkfeline** [golang/go#44473] opened 2021-02-21 08:14 UTC
When using `sync.WaitGroup`, very often it is used like so:

``` go
var wg sync.WaitGroup
wg.Add(1)
go func() {
    defer wg.Done()
    // Some code
}()
```

Of course, this is not the only use case, but it is by far the most common.  It would be convenient to add a method used like:

``` go
var wg sync.WaitGroup
wg.Run(func() {
    // Some code
})
```

``` go

func (wg *sync.WaitGroup) Run(f func()) {
    wg.Add(1)
    go func() {
        defer wg.Done()
        f()
    }()
}
```
```

**Comment by seankhliao** [comment] 2021-02-21 08:24
Duplicate of #39863

**Closed by seankhliao** 2021-02-21 08:24 UTC
