### ISSUE TITLE
cmd/go: mod vendor command skip failed dependencies

### ISSUE THREAD

**Issue by chapsuk** [golang/go#28447] opened 2018-10-28 12:26 UTC
```
≻ go version
go version go1.11.1 darwin/amd64
≻ go env
GOARCH="amd64"
GOBIN="/Users/chapsuk/go/bin"
GOCACHE="/Users/chapsuk/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/chapsuk/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1n/44fppc_x3bg_pbk4cl4gc4wc0000gn/T/go-build389417477=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
### What did you do?

1. Let's imitate connection problems, in real world package source can be unreachable:

```bash
echo "127.0.0.1 	mellium.im" >> /etc/hosts
```

2. Use sample
```go
package main

import (
	"fmt"
	"mellium.im/sasl"
)

func main() {
	fmt.Printf("%v", sasl.ErrAuthn)
}
```

3. Try vendor it

```bash
$ env GO111MODULE=on go mod vendor -v
Fetching https://mellium.im/sasl?go-get=1
https fetch failed: Get https://mellium.im/sasl?go-get=1: dial tcp 127.0.0.1:443: connect: connection refused
Fetching https://mellium.im?go-get=1
https fetch failed: Get https://mellium.im?go-get=1: dial tcp 127.0.0.1:443: connect: connection refused
go: no dependencies to vendor
```

### What did you expect to see?

Error result code:
```
$ echo $?
1
```

### What did you see instead?

Success result code:
```
$ echo $?
0
```

**Comment by bcmills** [comment] 2018-11-16 15:21
Duplicate of #27063.

**Closed by bcmills** 2018-11-16 15:21 UTC
Labels: NeedsInvestigation, modules
