### ISSUE TITLE
cmd/go2go: plus operation is not allowed to string and int

### ISSUE THREAD

**Issue by vearutop** [golang/go#39647] opened 2020-06-17 11:39 UTC
### What version of Go are you using (`go version`)?

https://go2goplay.golang.org/
<pre>
$ go version
devel +ad307489d4 Tue Jun 16 05:49:35 2020 +0000
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

https://go2goplay.golang.org/
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

https://go2goplay.golang.org/p/eJ9uY08prqs
```go
package main

import (
	"fmt"
)

type Plussable interface {
	type string, int
}

func Print(type T Plussable)(s1 T, s2 T) T {
	return s1 + s2
}
func main() {
	fmt.Print(Print("Hello, ", "playground\n"))
}
```

### What did you expect to see?

```
Hello, playground
```

### What did you see instead?

```
type checking failed for main
prog.go2:12:9: invalid operation: operator + not defined for s1 (variable of type T)
```

If I remove `int` from enumeration it works ok, also it works well if I remove `string` and add few more `int*`.

**Comment by martisch** [comment] 2020-06-17 12:15
Duplicate of: #39623

**Closed by martisch** 2020-06-17 12:15 UTC
