### ISSUE TITLE
runtime: SIGSEGV and "unexpected return pc for runtime.recordForPanic" on freebsd-amd64-race

### ISSUE THREAD

**Issue by bcmills** [golang/go#46182] opened 2021-05-15 02:13 UTC
[2021-05-14T16:42:01-3d324f1/freebsd-amd64-race](https://build.golang.org/log/380dc766e932609e9626438c711ef0abcee8f313)

```
unexpected fault address 0x100198
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100198 pc=0x41020a]

goroutine 391 [running]:
runtime.throw({0xebd59f, 0x5})
	/tmp/workdir/go/src/runtime/panic.go:1198 +0x74 fp=0x7fffdd9ead30 sp=0x7fffdd9ead00 pc=0x480274
runtime.sigpanic()
	/tmp/workdir/go/src/runtime/signal_unix.go:742 +0x3cf fp=0x7fffdd9ead90 sp=0x7fffdd9ead30 pc=0x49a30f
runtime: unexpected return pc for runtime.recordForPanic called from 0x2
stack: frame={sp:0x7fffdd9ead90, fp:0x7fffdd9eadc8} stack=[0xc000892000,0xc000894000)

runtime.recordForPanic({0xebc878, 0x3, 0x3})
	/tmp/workdir/go/src/runtime/print.go:54 +0x48 fp=0x7fffdd9eadc8 sp=0x7fffdd9ead90 pc=0x481c48
created by testing.(*T).Run
	/tmp/workdir/go/src/testing/testing.go:1289 +0x78e
```

CC @prattmic @cherrymui @danscales @randall77

**Comment by mknyszek** [comment] 2021-05-19 17:56
Closing as a duplicate of #46272.

**Closed by mknyszek** 2021-05-19 17:56 UTC
Labels: NeedsInvestigation, OS-FreeBSD
