### ISSUE TITLE
cmd/vet: incorrect error on a MarshalXML method

### ISSUE THREAD

**Issue by thinkerou** [golang/go#28792] opened 2018-11-14 12:30 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +6d620fc42e Wed Nov 14 00:22:40 2018 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
No, only go master branch.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

My code:

<pre>
// MarshalXML allows type H to be used with xml.Marshal.
func (h H) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name = xml.Name{
		Space: "",
		Local: "map",
	}
	if err := e.EncodeToken(start); err != nil {
		return err
	}
	for key, value := range h {
		elem := xml.StartElement{
			Name: xml.Name{Space: "", Local: key},
			Attr: []xml.Attr{},
		}
		if err := e.EncodeElement(value, elem); err != nil {
			return err
		}
	}

	return e.EncodeToken(xml.EndElement{Name: start.Name})
}
</pre>

### What did you expect to see?
correctly run on go master.

### What did you see instead?
<pre>
15.41s$ make vet
go vet github.com/gin-gonic/gin github.com/gin-gonic/gin/binding github.com/gin-gonic/gin/ginS github.com/gin-gonic/gin/internal/json github.com/gin-gonic/gin/render
# github.com/gin-gonic/gin
./utils.go:56: method MarshalXML(e *encoding/xml.Encoder, start encoding/xml.StartElement) error should have signature MarshalXML(*xml.Encoder, xml.StartElement) error
# github.com/gin-gonic/gin/render
render/render_test.go:221: method MarshalXML(e *encoding/xml.Encoder, start encoding/xml.StartElement) error should have signature MarshalXML(*xml.Encoder, xml.StartElement) error
make: *** [vet] Error 2
The command "make vet" exited with 2.
</pre>

**Comment by mvdan** [comment] 2018-11-14 13:02
A CL of mine touching this code was merged yesterday, so that's probably the cause. Will look into it in a bit.

**Comment by thinkerou** [comment] 2018-11-14 13:14
@mvdan thanks your reply, waiting.

**Closed** 2018-11-19 13:04 UTC
Labels: NeedsInvestigation

**Comment by thinkerou** [comment] 2018-11-19 14:12
hi @mvdan still have the below error info:
```
go vet github.com/gin-gonic/gin github.com/gin-gonic/gin/binding github.com/gin-gonic/gin/ginS github.com/gin-gonic/gin/internal/json github.com/gin-gonic/gin/render
# github.com/gin-gonic/gin
./utils.go:56:12: method MarshalXML(e *xml.Encoder, start xml.StartElement) error should have signature MarshalXML(*xml.Encoder, xml.StartElement) error
# github.com/gin-gonic/gin/render
render/render_test.go:221:17: method MarshalXML(e *xml.Encoder, start xml.StartElement) error should have signature MarshalXML(*xml.Encoder, xml.StartElement) error
make: *** [vet] Error 2
```

**Comment by thinkerou** [comment] 2018-11-19 14:29
@mvdan got it, thanks!
