### ISSUE TITLE
testing/iotest: ErrTimeout fails os.IsTimeout

### ISSUE THREAD

**Issue by dolmen** [golang/go#37263] opened 2020-02-17 11:19 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.7
</pre>

### Does this issue reproduce with the latest release?

Yes.

https://play.golang.org/p/T4bwPszSzM0

### What did you do?

```go
package main

import (
	"fmt"
	"os"
	"testing/iotest"
)

func main() {
	fmt.Println(os.IsTimeout(iotest.ErrTimeout))
}

```

### What did you expect to see?

`true`

### What did you see instead?

`false`

**Comment by changkun** [comment] 2020-02-17 12:29
This result is consistent since the day that @ianlancetaylor  introduces `os.IsTimeout` in Go 1.10.
However `iotest.ErrTimeout` lives way longer than `io.IsTimeout`.

The question is whether the Go team will recognize this as expected behavior or a bug that should be fixed.

**Comment by dolmen** [comment] 2020-02-17 20:09
I think that `iotest.TimeoutReader` is just useless for writing I/O tests if `iotest.ErrTimeout` isn't matched by `os.IsTimeout`.

Making it match is just switching `ErrTimeout` from being built from `errors.New` to using a specific type that has a `Timeout` method.

```go
type errTimeout struct{}

func (errTimeout) Error() string {
    return "timeout"
}

func (errTimeout) Timeout() bool {
    return true
}

var ErrTimeout error = errTimeout{}
```

I can provide this as a CL.

**Comment by toothrot** [comment] 2020-02-18 17:49
Also /cc-ing @mpvl @josharian as owners of testing

Just for some context, `os.ErrTimeout` was removed in #33411. There's also some discussion that seems related in #30322.

**Comment by rsc** [comment] 2020-10-20 00:38
os.IsTimeout does what it does and won't be changing. The comments need to be updated to mark it as deprecated - use errors.Is instead. Fixing the doc comments is #41122 .

**Closed by rsc** 2020-10-20 00:38 UTC
Labels: NeedsDecision
