### ISSUE TITLE
go/types: gotype requires installed packages

### ISSUE THREAD

**Issue by the42** [golang/go#14918] opened 2016-03-22 20:12 UTC
go1.6 gotype seems to be unaware of vendoring

1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/john/src/gocode"
GORACE=""
GOROOT="/home/john/opt/go"
GOTOOLDIR="/home/john/opt/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
john@ebola:~/src/gocode/src/github.com/the42/bevaddress$ gotype bevaddress.go 

The tree is
john@ebola:~/src/gocode/src/github.com/the42/bevaddress$ tree -d
.
├── Godeps
└── vendor
    └── github.com
        ├── gorilla
        │   └── websocket
        └── lib
            └── pq
                └── oid

8 directories

4. What did you expect to see?
no error (go build works)

5. What did you see instead?
bevaddress.go:9:2: could not import github.com/gorilla/websocket (can't find import: github.com/the42/bevaddress/vendor/github.com/gorilla/websocket)
bevaddress.go:10:4: could not import github.com/lib/pq (can't find import: github.com/the42/bevaddress/vendor/github.com/lib/pq)
bevaddress.go:18:16: undeclared name: websocket

**Comment by bcomnes** [comment] 2016-03-27 04:12
@the42 It was recommended to me to run `go install` or `go build -i` after vending code or running for the first time.  This builds out the vendor code into `$GOPATH/pkg/{packagePath}/vendor/...` and then gotype stops complaining. I guess its similar to an `npm i` step.

**Comment by the42** [comment] 2016-03-28 17:22
@bcomnes what remains is whether your recommendation is the way it should be or if it's a bug. I _think_ it's a bug.

**Comment by griesemer** [comment] 2016-03-28 17:31
Related to #11415. gotype is simply an app that invokes go/types. go/types doesn't build dependencies, it simply type-checks on package and relies on compiled versions of imported packages. If those don't exist (are not installed), go/types cannot find them.

Eventually, go/importer needs to support importing from source.

**Comment by bcomnes** [comment] 2016-03-28 17:54
@the42 `¯\_(ツ)_/¯` 
@griesemer Thanks for the background.  :+1:

**Comment by griesemer** [comment] 2016-10-05 23:14
I'm going to close this as duplicate of #11415, and in turn mark that one for Go1.8.

**Closed by griesemer** 2016-10-05 23:14 UTC
Labels: Vendoring
