### ISSUE TITLE
Extraneous 'go.exe~' file after updating Go on Windows

### ISSUE THREAD

**Issue by marigonzes** [golang/go#25225] opened 2018-05-02 17:03 UTC
### What version of Go are you using (`go version`)?
go version go1.10.1 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOCACHE=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=... -gno-record-gcc-switches

### What did you do?
I downloaded the Windows installer for the 1.10.2 version (go1.10.2.windows-amd64.msi) and installed it. While installing, it asked me if I wanted it to uninstall the previous version first, and I agreed.

### What did you expect to see?
The C:\Go\bin folder only contains one go.exe file.

### What did you see instead?
The C:\Go\bin folder contains two go.exe files, and one of them has the name 'go.exe~'.

**Comment by ALTree** [comment] 2018-05-02 17:33
Thanks for the report. I believe this is a dup of #23894.

**Comment by andybons** [comment] 2018-05-03 01:48
Duplicate of #23894

**Closed by andybons** 2018-05-03 01:48 UTC
