### ISSUE TITLE
XML unmarshalling fails if a field has `&` character in it.

### ISSUE THREAD

**Issue by karanjmu92** [golang/go#45721] opened 2021-04-23 11:04 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### Sample code for the unmarshalling of an XML field with `&` character.

```
package main
import (
	"encoding/xml"
	"fmt"
)

const xmlstr = `<UserXML><Username>karan</Username><Password>&karan#8yw</Password></UserXML>`

type UserXML struct{
	Username string
	Password string
}

func main() {
    var user *UserXML
	xml.Unmarshal([]byte(xmlstr),&user)
	fmt.Println(user.Password)
}

```

### What did you do?

I ran the above program and saw that the xml umarshalling fails for & and it prints nothing.

### What did you expect to see?

If a user has a password and it has & character in it, xml parser should be able to unmarshal that password.

### What did you see instead?
It fails to unmarshal the & character in the password field.

**Comment by ZekeLu** [comment] 2021-04-23 11:27
That's not a valid XML. `&` should be escaped as `&amp;` in XML.

**Comment by seankhliao** [comment] 2021-04-23 11:38
Closing as working as intended

For questions please refer to https://github.com/golang/go/wiki/Questions

**Closed by seankhliao** 2021-04-23 11:38 UTC

**Comment by karanjmu92** [comment] 2021-04-23 11:42
Thanks for clearing this out.
