### ISSUE TITLE
go fmt request / proposal : align parameters in function/method declaration 

### ISSUE THREAD

**Issue by ludz-lim** [golang/go#64803] opened 2023-12-19 16:19 UTC
The following is a valid golang code that is already formatted by ```go fmt``` (go 1.20)

```golang
func (w *WorkerType) Init(
	accountNumberChunk []string,
	serializeParam types.SerializeUnzippedFoldersParamType,
	workerId int,
) {
       // code goes here
}
```

I wonder if the request to make ```go fmt``` generate the following code similar to the alignment in struct definition reasonable

```golang
func (w *WorkerType) Init(
	accountNumberChunk []string,
	serializeParam     types.SerializeUnzippedFoldersParamType,
	workerId           int,
) {
       // code goes here
}
```

or if the there are comments to the parameters

```golang
func (w *WorkerType) Init(
	accountNumberChunk []string,                                 // subset of account numbers
	serializeParam     types.SerializeUnzippedFoldersParamType,  // serialization configuration
	workerId           int,                                      // worker id
) {
       // code goes here
}
```

This would make it consistent with way  ```go fmt``` handle struct definition.

Thank you.

**Comment by seankhliao** [comment] 2023-12-19 17:50
Duplicate of #33507

**Closed by seankhliao** 2023-12-19 17:50 UTC
