### ISSUE TITLE
net/http: Transport crash in tryPutIdleConn

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19605] opened 2017-03-18 17:30 UTC
Test flake in trybot run of https://go-review.googlesource.com/c/38351/

https://storage.googleapis.com/go-build-log/7db6e167/linux-amd64-race_2fc40adc.log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x428943]

goroutine 136 [running]:
net/http.(*Transport).tryPutIdleConn(0xc42032c5a0, 0xc42033fb00, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/transport.go:688 +0x29a
net/http.(*persistConn).readLoop.func2(0x0, 0xc420386201)
	/tmp/workdir/go/src/net/http/transport.go:1490 +0x6f
net/http.(*persistConn).readLoop(0xc42033fb00)
	/tmp/workdir/go/src/net/http/transport.go:1587 +0x1549
created by net/http.(*Transport).dialConn
	/tmp/workdir/go/src/net/http/transport.go:1168 +0xbf5
FAIL	net/http	0.207s
```

**Comment by bradfitz** [comment] 2017-03-18 17:31
Maybe CL 38351 is to blame? But in case it's not, filing this.

**Comment by mvdan** [comment] 2017-03-18 17:33
Likely caused by the CL - the runtime channel code it touches has `raceenabled` in there, so it could be that I simply broke `-race`. I'll look into this tomorrow.

**Comment by mvdan** [comment] 2017-03-18 17:37
Yeah, I can reproduce the crash via `go test -race net/http`. Closing as it's a regression in the CL, not a flake already present in tip.

**Closed by mvdan** 2017-03-18 17:37 UTC
Labels: HelpWanted, NeedsInvestigation, Testing
