### ISSUE TITLE
x/pkgsite: module version in pkg.go.dev still hasn't updated over a year after github version update

### ISSUE THREAD

**Issue by stacybird** [golang/go#65949] opened 2024-02-27 01:57 UTC
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/okta/okta-jwt-verifier-golang

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

### Screenshot

<img width="1133" alt="image" src="https://github.com/golang/go/assets/1613352/3efbc330-b179-45d3-9880-cf2435f3f10f">
<img width="797" alt="image" src="https://github.com/golang/go/assets/1613352/523202a3-f991-47c4-be8f-4a0c04033722">

### What did you do?

Okta has released several versions on GitHub since the last update.  I tried all three methods listed under [adding a package](https://pkg.go.dev/about#adding-a-package) to get it to update on the [pkg site](https://pkg.go.dev/github.com/okta/okta-jwt-verifier-golang), no dice.

### What did you see happen?

Still on [Version: v1.3.1](https://pkg.go.dev/github.com/okta/okta-jwt-verifier-golang?tab=versions) after over a year.

### What did you expect to see?

The version number and updated information for v2 and later on the [pkg site](https://pkg.go.dev/github.com/okta/okta-jwt-verifier-golang) 
[Latest versions on GitHub](https://github.com/okta/okta-jwt-verifier-golang/tags)

**Comment by seankhliao** [comment] 2024-02-27 02:01
go treats different major versions as independent modules. the banner at the top indicates there's a newer major version.

closing as working as intended

**Closed by seankhliao** 2024-02-27 02:01 UTC
Labels: pkgsite
