### ISSUE TITLE
go build -tags broken

### ISSUE THREAD

**Issue by fengttt** [golang/go#39188] opened 2020-05-21 09:01 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.14.2

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Linux, amd64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

It seems go build -tags is broken.   In the following, I have three simple files, a.go, b.go, main.go
go build builds fine, go build -tags xxxdbg builds fine, but go build -tags -xxxopt fail (CHK redefined)

```
[ftian@localhost tmp]$ cat *.go
// +build xxxdbg
// -- this is a.go
package main

func CHK(err error) {
	if err != nil {
		panic(err)
	}
}
// +build xxxopt
// -- this is b.go
package main

func CHK(err error) {
}

// -- this is main.go
package main


import (
	"fmt"
)

func main() {
	CHK(fmt.Errorf("This is an error."));
}
```

### What did you expect to see?
go build -tags xxxdbg builds OK.
go build -tags xxxopt builds OK.
go build FAIL, CHK not defined

### What did you see instead?
go build -tags xxxdbg builds OK
go build -tags xxxopt fails, CHK redeclared
go build build OK

**Comment by fengttt** [comment] 2020-05-21 09:07
Regardless, I expect -tags xxxopt and -tags xxxdbg behave the same -- either both succeed, or both fail.

**Comment by davecheney** [comment] 2020-05-21 09:59
(~/src) % go vet a.go
# command-line-arguments
./a.go:1:1: +build comment must appear before package clause and be followed by a blank line

**Comment by bcmills** [comment] 2020-05-21 15:54
Duplicate of #37803

**Closed by bcmills** 2020-05-21 15:54 UTC
