### ISSUE TITLE
dl: allow user to set root directory

### ISSUE THREAD

**Issue by perillo** [golang/go#29940] opened 2019-01-25 19:19 UTC
Currently the executable downloaded by `go get github.com/golang/dl/goX` installs `go` in the `~/sdk` directory.

It would be nice if, using a `-root` flag, the user can choose the directory where `go` should be installed (e.g. `/opt` on an UNIX system).

**Comment by agnivade** [comment] 2019-01-25 19:44
Duplicate of https://github.com/golang/go/issues/26520.

**Closed by agnivade** 2019-01-25 19:44 UTC

**Comment by perillo** [comment] 2019-01-25 21:42
@agnivade, sorry for having missed issue #26520.

However, the https://github.com/golang/dl/blob/master/README.md says that the label to use is `dl:`, but the label of issue #26520 is `x/dl:`.

**Comment by agnivade** [comment] 2019-01-26 03:53
Yeah, the repo was under `x` but moved to `dl`. Sometimes, the prefixes are not exactly what they should be.
