### ISSUE TITLE
wiki: contribution cycle diagram has a borked SVG under dark mode

### ISSUE THREAD

**Issue by Jorropo** [golang/go#65059] opened 2024-01-11 08:45 UTC
See https://go.dev/wiki/Go-Release-Cycle
![Screenshot from 2024-01-11 09-43-09](https://github.com/golang/go/assets/24391983/8bcb1178-bb35-4ae2-888e-b01f5f0718eb)

This is failing identically both in chromium and firefox.

Trying to open the svg in it's own page give funny results:
![Screenshot from 2024-01-11 09-43-57](https://github.com/golang/go/assets/24391983/8a77a023-9d3d-4346-93aa-8bb78e660d1d)
(again chromium and firefox failing in the same way)

**Comment by Jorropo** [comment] 2024-01-11 08:47
Idk where to find or fix this svg, so here is an issue instead. I don't know where to report wiki issues so :crossed_fingers: this is correct.

**Comment by mauri870** [comment] 2024-01-11 11:10
I remember seeing this diagram not so long ago and it was in the right shape. Here is  one from the wayback machine https://web.archive.org/web/20231209042740/https://github.com/golang/go/wiki/Go-Release-Cycle

**Comment by mauri870** [comment] 2024-01-11 11:13
Probably related with the migration of the wiki to go.dev #61940

**Comment by mauri870** [comment] 2024-01-11 11:16
Actual markdown page in x/wiki shows the svg is fine, might have to do with it blending in with the website background colors

https://github.com/golang/wiki/blob/master/Go-Release-Cycle.md

**Comment by mauri870** [comment] 2024-01-11 11:19
No x/wiki at https://dev.golang.org/owners, so I'm pinging the website folks. We might want to add x/wiki to the owners file

/cc @golang/tools-team

**Comment by hyangah** [comment] 2024-01-11 19:06
What version/os of the firefox and chromium? I assume you could reproduce it without any extensions, right?
My firefox 121.0.1  on mac seems to work fine in both dark/non-dark modes.

**Comment by Jorropo** [comment] 2024-01-11 19:23
My chromium has nothing installed,
Using arch linux
Firefox and Chromium are updated to the latest release (121.0.1 for ff)
I have dark mode enabled in gnome
And the browsers are set to track the system's preference.

**Comment by Jorropo** [comment] 2024-01-11 19:27
Disabling « Dark Style » option in Gnome and restarting the browser fixes it.

**Comment by dagood** [comment] 2024-01-16 22:19
Also repros for me on Windows 11.

* Microsoft Edge for Business Version 120.0.2210.133 (Official build) (64-bit)
* Firefox 121.0.1 (64-bit)

If I toggle off this rule in my inspector, it looks great with browser dark theme + website dark mode:

![image](https://github.com/golang/go/assets/12819531/aa9b2123-1e8d-4a01-88c5-23295f05e08d)

![image](https://github.com/golang/go/assets/12819531/cd1f791d-7f2f-4a61-aa5a-85e1e7706663)

However, it seems to me that the intent was probably to make the svg always have a white background and always have black text/outlines. A dark browser theme just makes the svg's text/outlines white unexpectedly.

**Comment by Jorropo** [comment] 2024-01-16 22:27
I can repro your fix. It seems to me this rule is spurious. Will send CL.

**Comment by dagood** [comment] 2024-01-16 22:38
Hmm, sorry, I'm actually not sure it's that simple: even if I disable the rule, if I have my browser theme dark and set the website to its light theme, then the text is white-on-white. (Because the page background itself is white, and my browser's dark theme is still somehow forcing the svg text to be white.)

**Comment by dagood** [comment] 2024-01-16 22:49
Ah, the svg actually contains this css internally:

```css
text {
	fill: black;
}
line, path {
	stroke: black;
	fill: none;
}
@media (prefers-color-scheme: dark) {
	text {
		fill: white;
	}
	line, path {
		stroke: white;
	}
}
```

Don't know how to counteract that from the outside (if possible) but I imagine it would be easy to snip from the svg?

**Comment by mauri870** [comment] 2024-01-24 09:48
If this turns out difficult to handle, can't we add a color to the svg background instead of keeping it transparent? This way independently of the page background color the text should still be readable. Downside is that we'll see the image borders.

**Comment by adonovan** [comment] 2024-01-24 15:21
> If this turns out difficult to handle, can't we add a color to the svg background instead of keeping it transparent? This way independently of the page background color the text should still be readable. Downside is that we'll see the image borders.

I agree, this is a simple and robust solution. And if you can be bothered to make the border line a double stripe of black and white then it will be visible on both modes.

There have been attempts to make transparent vector images that look good in both modes (e.g. https://forum.obsidian.md/t/auto-adaptive-images-for-dark-light-theme/13494), essentially by using mid-grey as the primary ink, but to my eyes they end up looking low-contrast in both modes.

I do wonder what the designers who originated "dark mode" had in mind as a plan for transparent images. Surely adaptive CSS cannot be the answer.

**Comment by Jorropo** [comment] 2024-01-24 15:43
FWIW my browser recognize the black on black and invert the strokes to white.
That sounds like an awfully fragile solution but so is most things on the web isn't it ?

**Comment by hyangah** [comment] 2024-01-27 18:05
Thanks all. I removed the dark theme setting from the svg image (and also checked in the svg file to the wiki repo).

Can you please check if this makes any improvement?

From my testing with system dark mode

Before: 

<img width="300" alt="Screenshot 2024-01-27 at 12 52 51 PM" src="https://github.com/golang/go/assets/4999471/82734f99-caa2-49e4-8acd-faff3d070cd0">

After:
<img width="300" alt="Screenshot 2024-01-27 at 1 03 20 PM" src="https://github.com/golang/go/assets/4999471/79d06e08-50eb-4b23-ba5a-43baa9d1eeee">

**Comment by mauri870** [comment] 2024-01-28 14:28
I just checked it again in Firefox and Chrome and it is much better now! The text is readable in both dark and light modes. Thank you @hyangah  for addressing this issue!

Additionally, there is a new [Contributing page](https://go.dev/wiki/Contributing)  providing detailed instructions on reporting wiki-related issues.

I am closing this issue as completed. Thanks to all those involved!

**Closed by mauri870** 2024-01-28 14:28 UTC
Labels: help wanted, NeedsFix, website
