### ISSUE TITLE
cmd/go: go get in module mode does not initialize git submodules

### ISSUE THREAD

**Issue by BenLubar** [golang/go#26716] opened 2018-07-31 16:19 UTC
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```
# In a directory outside of $GOPATH:
go mod -init -module example.invalid/gapstone-test
go get github.com/benlubar/gapstone@go-get
```

#### What did you expect to see?

Successful completion of the command.

#### What did you see instead?

```
go: finding github.com/benlubar/gapstone go-get
go: downloading github.com/benlubar/gapstone v0.0.0-20180731154137-aefb8fb9d854
# github.com/benlubar/gapstone
..\..\..\go\src\mod\github.com\benlubar\gapstone@v0.0.0-20180731154137-aefb8fb9d854\arm64_constants.go:19:32: fatal error: capstone/capstone.h: No such file or directory
 // #include <capstone/capstone.h>
                                ^
compilation terminated.
```

#### Does this issue reproduce with the latest release (go1.10.3)?

No. Go 1.10.3 correctly initializes the git submodule, as does go1.11beta2 when not using go.mod.

#### System details

```
go version go1.11beta2 windows/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="C:\Users\Owner\AppData\Local\go-build"
GOEXE=".exe"
GOHOSTARCH="amd64"
GOHOSTOS="windows"
GOOS="windows"
GOPATH="C:\Users\Owner\go"
GOPROXY=""
GORACE=""
GOROOT="C:\tools\go"
GOTMPDIR=""
GOTOOLDIR="C:\tools\go\pkg\tool\windows_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="C:\Users\Owner\Source\Repos\gapstone-test\go.mod"
GOROOT/bin/go version: go version go1.11beta2 windows/amd64
GOROOT/bin/go tool compile -V: compile version go1.11beta2
gdb --version: GNU gdb (GDB) 7.10.1
```

**Comment by myitcv** [comment] 2018-07-31 16:26
Git submodules are not going to be supported per https://github.com/golang/go/issues/24094#issuecomment-377559768

Leaving this issue open however for the cgo issue 

cc @ianlancetaylor

**Comment by ianlancetaylor** [comment] 2018-07-31 22:28
The go tool is working as intended in rejecting cgo file names that contain `!`.  For 1.11 this is documented at https://tip.golang.org/cmd/cgo.  Closing as I don't think there is anything we are going to do here; please comment if you disagree.

**Comment by myitcv** [comment] 2018-08-01 07:25
@ianlancetaylor I think the `!` is as a result of https://go-review.googlesource.com/c/go/+/124378

So cc-ed you just to ensure everything is working as intended post that?

**Comment by ianlancetaylor** [comment] 2018-08-01 17:52
@myitcv Thanks for pointing that out.

**Closed** 2018-08-01 19:59 UTC
Labels: NeedsFix, modules, release-blocker
