### ISSUE TITLE
bug with 1.11.5

### ISSUE THREAD

**Issue by github-of-dl** [golang/go#35303] opened 2019-11-01 07:43 UTC
### What version of Go are you using (`go version`)?
go version go1.11.5 linux/amd64

### Does this issue reproduce with the latest release?
no

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/x/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/x/.local/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build781833409=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
```

package main

import (
	"log"
)

func main() {
	p := 50
	n := 100
	for n > p {
		n = n - p
		log.Println("before", n, p)
		if n < p {
			log.Print("in if", n, p)
		}
	}
}

```

### What did you expect to see?
2019/11/01 15:39:56 before 50 50

### What did you see instead?
2019/11/01 15:39:56 before 50 50
2019/11/01 15:39:56 in if50 50

**Comment by rajender** [comment] 2019-11-01 08:55
This issue NOT exists in go1.11.13. Looks like it fixed in some release go1.11.6-go1.11.13.

**Comment by mvdan** [comment] 2019-11-01 09:56
Why are you using 1.11.5? That's not the latest release in the 1.11.x series.

You should also use 1.13.x or at least 1.12.x, if you can. 1.11.x doesn't even receive security updates anymore, so it's entirely unmaintained. See https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance.

**Comment by github-of-dl** [comment] 2019-11-01 09:57
> 
> 
> This issue NOT exists in go1.11.13. Looks like it fixed in some release between go1.11.6-go1.11.13.

Thanks for the reply. I was shocked by this bug. I wonder if it was fixed or it just became harder to reproduce?

**Comment by ALTree** [comment] 2019-11-01 09:58
Thanks for reporting this.

I can reproduce this on 1.11.5, but not on 1.11.6; so it appears that this is already fixed (possibly by [CL 156019](https://go-review.googlesource.com/c/go/+/156019), which was backported in the 1.11 release and published as 1.11.6).

I believe there is nothing more to do here, and you can fix the issue by upgrading to 1.11.13 (if you want to stay on 1.11), or even better, to go 1.13.1. 

Closing here.

**Closed by ALTree** 2019-11-01 09:58 UTC
Labels: WaitingForInfo

**Comment by github-of-dl** [comment] 2019-11-01 10:00
> 
> 
> Why are you using 1.11.5? That's not the latest release in the 1.11.x series.
> 
> You should also use 1.13.x or at least 1.12.x, if you can. 1.11.x doesn't even receive security updates anymore, so it's entirely unmaintained. See https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance.

1.11.5 is the latest version in Centos 7.2. Now I'm trying to upgrade golang to 1.31.1

**Comment by ALTree** [comment] 2019-11-01 10:02
> 1.11.5 is the latest version in Centos 7.2

Well, that's unfortunate. Go1.11 had a fair amount of point releases that fixed some serious issues (like this one you re-discovered), so at least using the latest (1.11.13) is strongly suggested.
