### ISSUE TITLE
Add install script for Unix-like OS

### ISSUE THREAD

**Issue by anjmao** [golang/go#37207] opened 2020-02-13 11:35 UTC
Installing Go on Unix-like OS seems to be too complicated. If you follow Getting Started install guide this is that you get.

```
Linux, macOS, and FreeBSD tarballs
Download the archive and extract it into /usr/local, creating a Go tree in /usr/local/go. For example:

tar -C /usr/local -xzf go$VERSION.$OS-$ARCH.tar.gz
Choose the archive file appropriate for your installation. For instance, if you are installing Go version 1.2.1 for 64-bit x86 on Linux, the archive you want is called go1.2.1.linux-amd64.tar.gz.

(Typically these commands must be run as root or through sudo.)

Add /usr/local/go/bin to the PATH environment variable. You can do this by adding this line to your /etc/profile (for a system-wide installation) or $HOME/.profile:

export PATH=$PATH:/usr/local/go/bin
Note: changes made to a profile file may not apply until the next time you log into your computer. To apply the changes immediately, just run the shell commands directly or execute them from the profile using a command such as source $HOME/.profile.
```

Why not make install script which does all of this manual work. This is how I imagine new users should be able to install Go.

```sh
curl --proto '=https' --tlsv1.2 -sSf https://sh.golang.org | sh
```

**Comment by bontibon** [comment] 2020-02-13 15:24
I believe this is a duplicate of #23381.

**Comment by ALTree** [comment] 2020-02-13 15:52
Indeed. Closing here as a dup of #23381.

**Closed by ALTree** 2020-02-13 15:52 UTC
