### ISSUE TITLE
net/http: TestNoSniffExpectRequestBody_h2 failures with "NO_ERROR"

### ISSUE THREAD

**Issue by bcmills** [golang/go#49730] opened 2021-11-22 20:03 UTC
`greplogs --dashboard -md -l -e 'FAIL: TestNoSniffExpectRequestBody_h2'`

[2021-11-22T19:43:16-8f559bc/linux-386-stretch](https://build.golang.org/log/f676c2bfc0de5a33ff4cffc2c448c4f58f732049)
[2021-11-14T17:38:42-5337e53/openbsd-386-68](https://build.golang.org/log/c4250a185d38fb54f24b5a6f94799d32587f4299)
[2021-10-15T20:34:15-1b072b3/freebsd-arm-paulzhol](https://build.golang.org/log/86fc8e0b00847b9d85d4ea22cf9aac51af202d15)
[2021-10-13T04:00:15-e8f99da/dragonfly-amd64](https://build.golang.org/log/818ce73812a54ea6bba1d3cfc5b96b7ac4866332)
<strong>Note: 1-year break here!</strong>
[2020-10-30T16:27:42-676ad56/solaris-amd64-oraclerel](https://build.golang.org/log/31e246fddf623ad295677b7e25c590d8a17596a6)
[2020-10-30T00:47:37-e62adb1/aix-ppc64](https://build.golang.org/log/bf1a823b221cdff72b6c9a70a9bbd1a0e73515b7)
[2020-10-30T00:23:50-faa4426/aix-ppc64](https://build.golang.org/log/b6eb2e57d585d89bed3da9eb1b5f79afb52614bd)
[2020-10-30T00:13:25-60f42ea/solaris-amd64-oraclerel](https://build.golang.org/log/fc24b67131c25ae351e904030c273146b38425ec)

It's not obvious to me, but given the similarity of the failure mode I suspect that perhaps bundling in the fix for #49645 will also fix this..?

CC @neild

**Comment by bcmills** [comment] 2021-11-22 20:04
(Marking as release-blocker for 1.18 because the 1-year gap in failures makes me suspect a 1.18 regression.)

**Comment by heschi** [comment] 2021-11-24 17:11
Do we think this should block the beta?

**Comment by neild** [comment] 2021-12-01 18:43
The more recent failures are different from the ones a year ago. There isn't enough evidence in the test output to be sure, but I think the recent failures are caused by the test taking more than 10 seconds to run; the test makes a request with `ExpectContinueTimeout` set to 10 seconds and fails if it it runs over that timeout. Probably just a slow builder.

**Comment by neild** [comment] 2021-12-01 19:34
Oh, I had the timeline backwards. The *old* failures are from the 10s timeout being exceeded, the new failures are something different.

**Comment by toothrot** [comment] 2021-12-13 17:51
Friendly check-in here, this is one of the last two issues blocking the beta of 1.18. Has there been an update recently?

**Comment by neild** [comment] 2021-12-13 18:06
Looking now, but I believe this is present in 1.17.5 and does not need to block the 1.18 beta. (Should be fixed before rc1, though.)

**Comment by toothrot** [comment] 2021-12-13 18:59
Thanks! I removed the label. We'll consider it a release-blocker for RC1.

**Comment by cagedmantis** [comment] 2022-01-07 17:35
Checking in on this as a release-blocking issue. Are there any updates?

**Closed** 2022-01-14 18:02 UTC
Labels: NeedsInvestigation, release-blocker

**Comment by bcmills** [comment] 2022-01-14 18:05
Agreed: this does not appeared to have recurred since the backports for that fix were merged. Thanks!

`greplogs --dashboard -md -l -e 'FAIL: TestNoSniffExpectRequestBody_h2' --since=2021-12-02`

[no results]
