### ISSUE TITLE
crypto/des: invalid key size 64  

### ISSUE THREAD

**Issue by xingcuntian** [golang/go#21142] opened 2017-07-24 08:23 UTC
crypto/des: invalid key size 64  

Key length 64 bit how to encrypt through des?

**Comment by ALTree** [comment] 2017-07-24 08:34
DES requires keysize = 8 and tripleDES requires keysize  = 24. Every other key size will raise a `KeySizeError`.

Plese note that the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2017-07-24 08:34 UTC
