### ISSUE TITLE
go/cmd: test output changes with `-bench=.`, `-fuzz=.`, etc.

### ISSUE THREAD

**Issue by smoyer64** [golang/go#57671] opened 2023-01-07 14:56 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.19.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/smoyer1/.cache/go-build"
GOENV="/home/smoyer1/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/smoyer1/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/smoyer1/go:/usr/share/go-tools"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/smoyer1/.asdf/installs/golang/1.19.4/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/smoyer1/.asdf/installs/golang/1.19.4/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/smoyer1/git/git-bug/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2844214839=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I don't think I'd classify this as a bug but in my opinion, it does represent undesirable behavior.  Running the following test under different conditions result in different outcomes, which may represent a difference in the actual characters emitted to the output:

<pre>
import (
	"os"
	"testing"

	"github.com/fatih/color"
	"github.com/mattn/go-isatty"
	"golang.org/x/sys/unix"
)

func TestGetTermios(t *testing.T) {
	t.Log("Stdout FD:", os.Stdout.Fd())
	termios, err := unix.IoctlGetTermios(int(os.Stdout.Fd()), unix.TCGETS)
	t.Log("Termios:", termios)
	t.Log("Termios error:", err != nil)
	t.Log("Is a TTY:", isatty.IsTerminal(os.Stdout.Fd()))
	t.Log("Supports color:", !color.NoColor)
}
</pre>

### What did you expect to see?

The same output to `stdout` regardless of the command that ran the test.

### What did you see instead?

Assuming this test is placed in a sub-package, the outcome of this test is as follows:

- (PASS): `go test -v -bench=. ./...`
- (PASS): `cd pkg/output && go test -v`
- (FAIL): 'go test -v ./...`
- (FAIL): `go test -v ./pkg/output`

This behavior is caused by the code at https://github.com/golang/go/blob/f721fa3be9bb52524f97b409606f9423437535e8/src/cmd/go/internal/test/test.go#L1180-L1208 and as noted in the comment, has been around longer since at least Go 1.5 (since the special case was added at that point).  I'm not arguing that there's a need for the buffering in some cases and that it's safe to write directly to `stdout` in other cases but rather that the test environment should remain consistent regardless of how the test is launched.

Since there's the need for buffering in some cases, it's impossible for `stdout` to always be a `*unix.Termios`.  I'd argue that (during tests), `stdout` should therefore NEVER be a `*unix.Termios`.

**Comment by seankhliao** [comment] 2023-01-07 15:03
Duplicate of #34877

**Closed by seankhliao** 2023-01-07 15:03 UTC

**Comment by smoyer64** [comment] 2023-01-07 15:37
I swear I searched high and low for an existing issue that described this problem - thanks for linking/triaging my issue!
