### ISSUE TITLE
proposal: methods with default implementations for interfaces

### ISSUE THREAD

**Issue by rekby** [golang/go#66068] opened 2024-03-01 21:35 UTC
### Proposal Details

Add possibility of implementation method for interface.
It make able to:
1. Extend interface without break compatibility by implement default behaviour.
3. Implement functional around interface. For example interface iterator with default implementation methods Skip, Limit, etc:

## Example of default implementation:
```go
type Task interface {
	Execute()
}

func (t Task) ExecuteMeasure() time.Duration {
	start := time.Now()
	t.Execute()
	return time.Since(start)
}

type Impl struct{}

func (_ Impl) Execute() {
	time.Sleep(time.Second)
}
```

It mean: Impl is implemented interface Task. I can call Execute from both types: Impl and Task. But I can call ExecuteMeasure only for Task only: 

```go
	var a Impl
	var b Task = a
	b.ExecuteMeasure()
```

## Example of functional implementation around interface 
```go
type Iterator[T any] interface {
	Next() (T, error)
}

func (i Iterator[T]) Skip(count int) (int, error) {
	for i := 0; i < count; i++ {
		if _, err := i.Next(); err != nil {
			return i, err
		}
	}
	return count, nil
}

func (i Iterator[T]) Limit() Iterator[T] {
	...
}
```

**Comment by gophun** [comment] 2024-03-01 21:42
#16254

**Comment by seankhliao** [comment] 2024-03-01 21:45
Duplicate of #16254

**Closed by seankhliao** 2024-03-01 21:45 UTC
Labels: Proposal
