### ISSUE TITLE
x/tools/gopls: can't add new file to existing package

### ISSUE THREAD

**Issue by muirdm** [golang/go#35605] opened 2019-11-15 01:07 UTC
On master (4191b8cbba092238a318a71cdff48b20b4e1e5d8) when I add a new file to an existing package I get `no ParseGoHandle for file://...` when I try to use gopls functionality in the new file.

Note that in my editor the new file comes pre-populated with the package name based on the file's directory name (i.e. the bug only reproduces if the initial "didOpen" message already contains the "package foo" line). If I subsequently edit the package name then the file gets loaded normally.

Below is an RPC trace starting from opening the new file through the first "no ParseGoHandle" error:

```
[Trace - 05:01:19 PM] Sending notification 'textDocument/didOpen'.
Params: {
  "textDocument": {
    "uri": "file:///Users/muir/scratch/foo/bar.go",
    "languageId": "go",
    "version": 0,
    "text": "\npackage foo\n"
  }
}


[Trace - 05:01:19 PM] Received notification 'window/logMessage'.
Params: {
  "message": "2019/11/14 17:01:19 go/packages.Load\n\tpackages = 1",
  "type": 3
}


[Trace - 05:01:19 PM] Received notification 'window/logMessage'.
Params: {
  "message": "2019/11/14 17:01:19 go/packages.Load\n\tpackage = foo\n\tfiles = [/Users/muir/scratch/foo/foo.go /Users/muir/scratch/foo/bar.go]",
  "type": 3
}


[Trace - 05:01:19 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
  "diagnostics": [],
  "uri": "file:///Users/muir/scratch/foo/foo.go"
}


[Trace - 05:01:23 PM] Sending notification 'textDocument/didChange'.
Params: {
  "textDocument": {
    "uri": "file:///Users/muir/scratch/foo/bar.go",
    "version": 1
  },
  "contentChanges": [
    {
      "range": {
        "start": {
          "line": 1,
          "character": 11
        },
        "end": {
          "line": 1,
          "character": 11
        }
      },
      "rangeLength": 0,
      "text": "\n"
    }
  ]
}


[Trace - 05:01:23 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
  "diagnostics": [],
  "uri": "file:///Users/muir/scratch/foo/foo.go"
}


[Trace - 05:01:23 PM] Sending request 'textDocument/signatureHelp - (568)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/muir/scratch/foo/bar.go"
  },
  "position": {
    "line": 2,
    "character": 0
  }
}


[Trace - 05:01:23 PM] Received response 'textDocument/signatureHelp - (568)' in 6ms.
Result: null


[Trace - 05:01:23 PM] Received notification 'window/logMessage'.
Params: {
  "message": "2019/11/14 17:01:23 no signature help\n\tAt = {2 0}\n\tFailure = no ParseGoHandle for file:///Users/muir/scratch/foo/bar.go",
  "type": 3
}
```

**Comment by stamblerre** [comment] 2019-12-04 23:55
Thanks for the report. This sounds a lot like https://github.com/golang/go/issues/35949, so I will close this as a duplicate.

**Comment by stamblerre** [comment] 2019-12-04 23:55
Duplicate of https://github.com/golang/go/issues/35949

**Closed by stamblerre** 2019-12-04 23:55 UTC
Labels: Tools, gopls
