### ISSUE TITLE
feature: Allow underscore for numerical constants

### ISSUE THREAD

**Issue by pjebs** [golang/go#31990] opened 2019-05-13 03:44 UTC
Swift allows writing underscores for numerical constants to help read large numbers more easily.

Go should allow it too:

```
t := 1000000000000
OR
t := 1_000_000_000_000 // Much easier to read number
```

**Comment by jimmyfrasche** [comment] 2019-05-13 03:48
Good news: duplicate of #28493

**Closed by jimmyfrasche** 2019-05-13 03:48 UTC
