### ISSUE TITLE
cmd/compile: false positive error about recursive type aliases

### ISSUE THREAD

**Issue by mdempsky** [golang/go#23055] opened 2017-12-08 08:32 UTC
cmd/compile erroneously emits an "invalid recursive type alias" error for:

    package p

    type a struct { b }
    type b = c
    type c struct { *b }

Related: #18640

**Comment by JicLotus** [comment] 2017-12-10 20:47
Hi, i want to take this issue.

**Comment by mdempsky** [comment] 2017-12-11 19:28
@JicLotus Thanks for volunteering. If you'd like to work on this, feel free. I do want to caution though that this is likely to be a fairly subtle and involved part of the compiler.

The problem is that we recursively evaluate type declarations as needed. I think we'll need to undo this and instead evaluate type declarations in a two pass algorithm:

  1. Set up a TFORW type for each package scoped declared type and associate the Sym with that type.
  2. Resolve each type declaration and assign the TFORW type's underlying type.

I'm suspecting we'll also have to split constant evaluation into a separate pass too. I briefly touched on this idea in https://github.com/golang/go/issues/13890#issuecomment-212115681. But it might be possible to fix this issue without doing that.

**Comment by JicLotus** [comment] 2017-12-11 21:48
Great @mdempsky

**Comment by griesemer** [comment] 2018-05-31 05:28
I'm going to close this one as it is fundamentally a duplicate of #18640 (which has been reopened); see [here](https://github.com/golang/go/issues/18640#issuecomment-387904672).

**Closed by griesemer** 2018-05-31 05:28 UTC
Labels: NeedsFix
