### ISSUE TITLE
fmt.Print affect rand.Intn ?

### ISSUE THREAD

**Issue by iquanxin** [golang/go#48461] opened 2021-09-18 16:10 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.17 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Ma\AppData\Local\go-build
set GOENV=C:\Users\Ma\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Ma\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Ma\go
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=D:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\Golang\windowgui\autoupgrade\rando\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Ma\AppData\Local\Temp\go-build3754657819=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Generate random characters
<pre>
<code>
package main

import (
	"fmt"
	"math/rand"
	"time"
)

const chars = "0123456789abcdef"

func main() {
	for i := 0; i < 5; i++ {
		fmt.Println(">>>>", RandStr(32))
	}
}

func RandStr(strlen int) string {
	// r := rand.New(rand.NewSource(time.Now().UnixNano()))
	rand.Seed(time.Now().UnixNano())
	result := make([]byte, strlen)
	for i := range result {
		num := rand.Intn(len(chars))
		// fmt.Printf("%d ", num)     // When using fmt.Printf("%d ", num),  I get the result i want
		result[i] = chars[num]
	}
	return string(result)
}
</code>
</pre>

### What did you expect to see?
<pre>
<code>
>>>> 078669cdc3ffc0d263a9896c5cf16406
>>>> ba65e0a0749465bd0346e036b1526abf
>>>> 426b200d36c94a37481468901568a8f6
>>>> 91a8a4628e7cac86c93c5009c4fc653f
>>>> a78b5b5b41c4fde043fedb2f62712dc2
</code>
</pre>

### What did you see instead?
<pre>
<code>
>>>> a80448b50d5dff275f08942c03bb5b39
>>>> a80448b50d5dff275f08942c03bb5b39
>>>> 5a3d9fefd4593b5592f6259688c6fb6d
>>>> 5a3d9fefd4593b5592f6259688c6fb6d
>>>> 5a3d9fefd4593b5592f6259688c6fb6d
</code>
</pre>

**Comment by seankhliao** [comment] 2021-09-18 16:19
Can you print out the value of `time.Now().UnixNano()` used? Windows has a low timer resolution and time is a poor fit for seeding rand

**Comment by iquanxin** [comment] 2021-09-18 16:24
![image](https://user-images.githubusercontent.com/16774470/133895582-dfb19023-1243-467c-8fe2-19f49492807f.png)

**Comment by iquanxin** [comment] 2021-09-18 16:25
> Can you print out the value of `time.Now().UnixNano()` used? Windows has a low timer resolution and time is a poor fit for seeding rand
![image](https://user-images.githubusercontent.com/16774470/133895610-fa97a9c0-4ed6-449e-94cd-18e3f8cc5784.png)

**Comment by iquanxin** [comment] 2021-09-18 16:28
using fmt.Printf(" ") output
![image](https://user-images.githubusercontent.com/16774470/133895682-146d6d24-f087-4fe5-9aae-b5e82033e43d.png)

**Comment by seankhliao** [comment] 2021-09-18 16:31
Adding the `fmt` call just slows down the loop so it uses a different time seed each time

Closing as not a bug

**Closed by seankhliao** 2021-09-18 16:31 UTC

**Comment by iquanxin** [comment] 2021-09-18 16:33
I know，thanks

**Comment by mpx** [comment] 2021-09-18 16:34
Separately, you shouldn't re-seed on every call to `RandStr` - this would also avoid the problem you are seeing.
