### ISSUE TITLE
cmd/go: confusing cache behavior for GOSSAFUNC

### ISSUE THREAD

**Issue by cherrymui** [golang/go#37335] opened 2020-02-20 16:59 UTC
### What version of Go are you using (`go version`)?

tip (631b49886c)

### Does this issue reproduce with the latest release?

Yes

### What did you do?

I generated a ssa.html using GOSSAFUNC, and somehow lost it, e.g. overwritten by another one. I try to generate it again.

```
$ GOSSAFUNC=F go build p.go
# command-line-arguments
dumped SSA to ./ssa.html

$ ls ssa.html 
ssa.html

$ rm ssa.html                  # somehow I lost it, e.g. overwritten by another one

$ GOSSAFUNC=F go build p.go    # try to generate it again
# command-line-arguments
dumped SSA to ./ssa.html

$ ls ssa.html
ls: ssa.html: No such file or directory
```

The second time, the build is cached, along with its stdout, which said ssa.html is generated. But the html is not cached and not regenerated. This is confusing. To actually regenerate the html I have to make a trivial change to the source file. It would be nice if I don't have to do it this way.

cc @rsc @bcmills

**Comment by josharian** [comment] 2020-02-20 17:02
Possibly related: https://github.com/golang/go/issues/31290

**Comment by bcmills** [comment] 2020-02-20 17:47
Yes: specifically, see https://github.com/golang/go/issues/31290#issuecomment-482094899.

**Comment by bcmills** [comment] 2020-02-20 17:47
Duplicate of #31290

**Closed by bcmills** 2020-02-20 17:47 UTC
