### ISSUE TITLE
cmd/go: `go list cmd` fails to resolve imports with Go Modules on

### ISSUE THREAD

**Issue by TaylorCFrey** [golang/go#31389] opened 2019-04-10 14:58 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
I'm able to reproduce this in the golang:1.12.3 docker image from hub.docker.com. This is also reproduced on my local dev machine as well.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go version go1.12.3 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.12.3 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.12.3
uname -sr: Linux 4.15.0-46-generic
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Debian GLIBC 2.24-11+deb9u4) stable release version 2.24, by Roland McGrath et al.
</pre></details>

### What did you do?

A tool I use in my automation pipeline ultimately calls `go list cmd` among other calls. This results in an error when `go modules` are enabled.

I've been using docker images for clean environments to reproduce
```sh
$ docker pull golang:1.12.3
$ docker run -it --name golang golang:1.12.3
```

Attempt to list `cmd` packages
```sh
$ cd $GOPATH # not necessary. Can be outside of the $GOPATH as well
$ GO111MODULE=on go list cmd
```

### What did you expect to see?

```sh
$ GO111MODULE=on go list cmd
cmd/addr2line
cmd/api
cmd/asm
cmd/asm/internal/arch
cmd/asm/internal/asm
cmd/asm/internal/flags
cmd/asm/internal/lex
cmd/buildid
cmd/cgo
# ... continues w/o error
```

<details><summary><code>GO111MODULE=on go list cmd</code> Full Output</summary><br><pre>
$ GO111MODULE=off go list cmd # turn off Go Modules for demonstration
cmd/addr2line
cmd/api
cmd/asm
cmd/asm/internal/arch
cmd/asm/internal/asm
cmd/asm/internal/flags
cmd/asm/internal/lex
cmd/buildid
cmd/cgo
cmd/compile
cmd/compile/internal/amd64
cmd/compile/internal/arm
cmd/compile/internal/arm64
cmd/compile/internal/gc
cmd/compile/internal/mips
cmd/compile/internal/mips64
cmd/compile/internal/ppc64
cmd/compile/internal/s390x
cmd/compile/internal/ssa
cmd/compile/internal/syntax
cmd/compile/internal/test
cmd/compile/internal/types
cmd/compile/internal/wasm
cmd/compile/internal/x86
cmd/cover
cmd/dist
cmd/doc
cmd/fix
cmd/go
cmd/go/internal/base
cmd/go/internal/bug
cmd/go/internal/cache
cmd/go/internal/cfg
cmd/go/internal/clean
cmd/go/internal/cmdflag
cmd/go/internal/dirhash
cmd/go/internal/doc
cmd/go/internal/envcmd
cmd/go/internal/fix
cmd/go/internal/fmtcmd
cmd/go/internal/generate
cmd/go/internal/get
cmd/go/internal/help
cmd/go/internal/imports
cmd/go/internal/list
cmd/go/internal/load
cmd/go/internal/lockedfile
cmd/go/internal/lockedfile/internal/filelock
cmd/go/internal/modcmd
cmd/go/internal/modconv
cmd/go/internal/modfetch
cmd/go/internal/modfetch/codehost
cmd/go/internal/modfile
cmd/go/internal/modget
cmd/go/internal/modinfo
cmd/go/internal/modload
cmd/go/internal/module
cmd/go/internal/mvs
cmd/go/internal/par
cmd/go/internal/renameio
cmd/go/internal/run
cmd/go/internal/search
cmd/go/internal/semver
cmd/go/internal/str
cmd/go/internal/test
cmd/go/internal/tool
cmd/go/internal/txtar
cmd/go/internal/version
cmd/go/internal/vet
cmd/go/internal/web
cmd/go/internal/web2
cmd/go/internal/webtest
cmd/go/internal/work
cmd/gofmt
cmd/internal/bio
cmd/internal/browser
cmd/internal/buildid
cmd/internal/dwarf
cmd/internal/edit
cmd/internal/gcprog
cmd/internal/goobj
cmd/internal/obj
cmd/internal/obj/arm
cmd/internal/obj/arm64
cmd/internal/obj/mips
cmd/internal/obj/ppc64
cmd/internal/obj/s390x
cmd/internal/obj/wasm
cmd/internal/obj/x86
cmd/internal/objabi
cmd/internal/objfile
cmd/internal/src
cmd/internal/sys
cmd/internal/test2json
cmd/link
cmd/link/internal/amd64
cmd/link/internal/arm
cmd/link/internal/arm64
cmd/link/internal/ld
cmd/link/internal/loadelf
cmd/link/internal/loadmacho
cmd/link/internal/loadpe
cmd/link/internal/loadxcoff
cmd/link/internal/mips
cmd/link/internal/mips64
cmd/link/internal/objfile
cmd/link/internal/ppc64
cmd/link/internal/s390x
cmd/link/internal/sym
cmd/link/internal/wasm
cmd/link/internal/x86
cmd/nm
cmd/objdump
cmd/pack
cmd/pprof
cmd/test2json
cmd/trace
cmd/vendor/github.com/google/pprof/driver
cmd/vendor/github.com/google/pprof/internal/binutils
cmd/vendor/github.com/google/pprof/internal/driver
cmd/vendor/github.com/google/pprof/internal/elfexec
cmd/vendor/github.com/google/pprof/internal/graph
cmd/vendor/github.com/google/pprof/internal/measurement
cmd/vendor/github.com/google/pprof/internal/plugin
cmd/vendor/github.com/google/pprof/internal/proftest
cmd/vendor/github.com/google/pprof/internal/report
cmd/vendor/github.com/google/pprof/internal/symbolizer
cmd/vendor/github.com/google/pprof/internal/symbolz
cmd/vendor/github.com/google/pprof/internal/transport
cmd/vendor/github.com/google/pprof/profile
cmd/vendor/github.com/google/pprof/third_party/d3
cmd/vendor/github.com/google/pprof/third_party/d3flamegraph
cmd/vendor/github.com/google/pprof/third_party/svgpan
cmd/vendor/github.com/ianlancetaylor/demangle
cmd/vendor/golang.org/x/arch/arm/armasm
cmd/vendor/golang.org/x/arch/arm64/arm64asm
cmd/vendor/golang.org/x/arch/ppc64/ppc64asm
cmd/vendor/golang.org/x/arch/x86/x86asm
cmd/vendor/golang.org/x/crypto/ssh/terminal
cmd/vendor/golang.org/x/sys/unix
cmd/vendor/golang.org/x/sys/windows
cmd/vendor/golang.org/x/sys/windows/registry
cmd/vendor/golang.org/x/tools/go/analysis
cmd/vendor/golang.org/x/tools/go/analysis/internal/analysisflags
cmd/vendor/golang.org/x/tools/go/analysis/internal/facts
cmd/vendor/golang.org/x/tools/go/analysis/passes/asmdecl
cmd/vendor/golang.org/x/tools/go/analysis/passes/assign
cmd/vendor/golang.org/x/tools/go/analysis/passes/atomic
cmd/vendor/golang.org/x/tools/go/analysis/passes/bools
cmd/vendor/golang.org/x/tools/go/analysis/passes/buildtag
cmd/vendor/golang.org/x/tools/go/analysis/passes/cgocall
cmd/vendor/golang.org/x/tools/go/analysis/passes/composite
cmd/vendor/golang.org/x/tools/go/analysis/passes/copylock
cmd/vendor/golang.org/x/tools/go/analysis/passes/ctrlflow
cmd/vendor/golang.org/x/tools/go/analysis/passes/httpresponse
cmd/vendor/golang.org/x/tools/go/analysis/passes/inspect
cmd/vendor/golang.org/x/tools/go/analysis/passes/internal/analysisutil
cmd/vendor/golang.org/x/tools/go/analysis/passes/loopclosure
cmd/vendor/golang.org/x/tools/go/analysis/passes/lostcancel
cmd/vendor/golang.org/x/tools/go/analysis/passes/nilfunc
cmd/vendor/golang.org/x/tools/go/analysis/passes/pkgfact
cmd/vendor/golang.org/x/tools/go/analysis/passes/printf
cmd/vendor/golang.org/x/tools/go/analysis/passes/shift
cmd/vendor/golang.org/x/tools/go/analysis/passes/stdmethods
cmd/vendor/golang.org/x/tools/go/analysis/passes/structtag
cmd/vendor/golang.org/x/tools/go/analysis/passes/tests
cmd/vendor/golang.org/x/tools/go/analysis/passes/unmarshal
cmd/vendor/golang.org/x/tools/go/analysis/passes/unreachable
cmd/vendor/golang.org/x/tools/go/analysis/passes/unsafeptr
cmd/vendor/golang.org/x/tools/go/analysis/passes/unusedresult
cmd/vendor/golang.org/x/tools/go/analysis/unitchecker
cmd/vendor/golang.org/x/tools/go/ast/astutil
cmd/vendor/golang.org/x/tools/go/ast/inspector
cmd/vendor/golang.org/x/tools/go/cfg
cmd/vendor/golang.org/x/tools/go/types/objectpath
cmd/vendor/golang.org/x/tools/go/types/typeutil
cmd/vet
</pre></details>

### What did you see instead?

```sh
$ GO111MODULE=on go list cmd 
# if the first time, performs finds / downloads / and extracts for a few packages
go: finding github.com/ianlancetaylor/demangle latest
go: downloading github.com/ianlancetaylor/demangle v0.0.0-20181102032728-5e5cf60278f6
go: extracting github.com/ianlancetaylor/demangle v0.0.0-20181102032728-5e5cf60278f6

# then begins to return errors in resolving some packages
can't load package: /usr/local/go/src/cmd/internal/objfile/disasm.go:24:2: non-standard import "golang.org/x/arch/arm/armasm" in standard package "cmd/internal/objfile"
can't load package: /usr/local/go/src/cmd/pprof/pprof.go:28:2: non-standard import "github.com/google/pprof/driver" in standard package "cmd/pprof"
can't load package: /usr/local/go/src/cmd/trace/pprof.go:24:2: non-standard import "github.com/google/pprof/profile" in standard package "cmd/trace"
can't load package: /usr/local/go/src/cmd/vendor/github.com/google/pprof/driver/driver.go:26:2: non-standard import "github.com/google/pprof/profile" in standard package "cmd/vendor/github.com/google/pprof/driver"

# followed by mostly successful package listings
cmd/addr2line
cmd/api
cmd/asm
cmd/asm/internal/arch
cmd/asm/internal/asm
cmd/asm/internal/flags
cmd/asm/internal/lex
# continues until the end ultimately returning status code 1
```

<details><summary><code>GO111MODULE=on go list cmd</code> Full Output</summary><br><pre>
$ GO111MODULE=on go list cmd 
go: finding github.com/ianlancetaylor/demangle latest
go: finding github.com/google/pprof/third_party/d3 latest
go: finding github.com/google/pprof/internal/report latest
go: finding github.com/google/pprof/internal/measurement latest
go: finding github.com/google/pprof/internal/symbolz latest
go: finding github.com/google/pprof/internal/binutils latest
go: finding github.com/google/pprof/internal/symbolizer latest
go: finding golang.org/x/arch/x86/x86asm latest
go: finding golang.org/x/arch/ppc64/ppc64asm latest
go: finding golang.org/x/tools/go/types/objectpath latest
go: downloading github.com/ianlancetaylor/demangle v0.0.0-20181102032728-5e5cf60278f6
go: extracting github.com/ianlancetaylor/demangle v0.0.0-20181102032728-5e5cf60278f6
go: finding golang.org/x/tools/go/analysis/passes/internal/analysisutil latest
go: finding golang.org/x/arch/x86 latest
go: finding golang.org/x/arch/ppc64 latest
go: finding golang.org/x/arch latest
go: downloading golang.org/x/arch v0.0.0-20190312162104-788fe5ffcd8c
go: extracting golang.org/x/arch v0.0.0-20190312162104-788fe5ffcd8c
go: finding github.com/google/pprof/third_party/d3flamegraph latest
go: finding golang.org/x/arch/arm64/arm64asm latest
go: finding github.com/google/pprof/third_party latest
go: finding github.com/google/pprof latest
go: finding github.com/google/pprof/internal latest
go: finding golang.org/x/arch/arm64 latest
go: finding github.com/google/pprof/profile latest
go: downloading github.com/google/pprof v0.0.0-20190404155422-f8f10df84213
go: extracting github.com/google/pprof v0.0.0-20190404155422-f8f10df84213
go: finding github.com/google/pprof/third_party/svgpan latest
go: finding github.com/google/pprof/driver latest
go: finding github.com/google/pprof/internal/plugin latest
go: finding github.com/google/pprof/internal/transport latest
go: finding github.com/google/pprof/internal/graph latest
go: finding golang.org/x/arch/arm/armasm latest
go: finding golang.org/x/tools/go/analysis/internal/facts latest
go: finding golang.org/x/tools/go/cfg latest
go: finding golang.org/x/tools/go/analysis/internal/analysisflags latest
go: finding golang.org/x/tools/go/analysis/passes/inspect latest
go: finding golang.org/x/tools/go/analysis latest
go: finding golang.org/x/arch/arm latest
go: finding golang.org/x/tools/go/types/typeutil latest
go: finding golang.org/x/sys/unix latest
go: finding golang.org/x/crypto/ssh/terminal latest
go: finding golang.org/x/tools/go/types latest
go: finding golang.org/x/tools/go/analysis/passes/internal latest
go: finding golang.org/x/tools/go/analysis/internal latest
go: finding golang.org/x/tools/go latest
go: finding golang.org/x/tools/go/analysis/passes latest
go: finding golang.org/x/tools latest
go: downloading golang.org/x/tools v0.0.0-20190410135722-7e5bf9270d70
go: finding golang.org/x/sys latest
go: downloading golang.org/x/sys v0.0.0-20190405154228-4b34438f7a67
go: finding golang.org/x/crypto/ssh latest
go: finding golang.org/x/crypto latest
go: downloading golang.org/x/crypto v0.0.0-20190404164418-38d8ce5564a5
go: extracting golang.org/x/tools v0.0.0-20190410135722-7e5bf9270d70
go: finding github.com/google/pprof/internal/elfexec latest
go: finding github.com/google/pprof/internal/driver latest
go: finding golang.org/x/tools/go/ast/astutil latest
go: finding golang.org/x/tools/go/analysis/passes/bools latest
go: finding golang.org/x/tools/go/analysis/passes/stdmethods latest
go: finding golang.org/x/tools/go/analysis/unitchecker latest
go: finding golang.org/x/tools/go/analysis/passes/buildtag latest
go: finding golang.org/x/tools/go/analysis/passes/shift latest
go: finding golang.org/x/tools/go/analysis/passes/copylock latest
go: finding golang.org/x/tools/go/analysis/passes/cgocall latest
go: finding golang.org/x/tools/go/ast latest
go: finding golang.org/x/tools/go/analysis/passes/unsafeptr latest
go: finding golang.org/x/tools/go/analysis/passes/unusedresult latest
go: finding golang.org/x/tools/go/analysis/passes/unmarshal latest
go: finding golang.org/x/tools/go/analysis/passes/printf latest
go: finding golang.org/x/tools/go/analysis/passes/structtag latest
go: finding golang.org/x/tools/go/analysis/passes/lostcancel latest
go: finding golang.org/x/tools/go/analysis/passes/atomic latest
go: finding golang.org/x/tools/go/ast/inspector latest
go: finding golang.org/x/tools/go/analysis/passes/loopclosure latest
go: finding golang.org/x/tools/go/analysis/passes/httpresponse latest
go: finding golang.org/x/tools/go/analysis/passes/composite latest
go: finding golang.org/x/tools/go/analysis/passes/unreachable latest
go: finding golang.org/x/tools/go/analysis/passes/asmdecl latest
go: finding golang.org/x/tools/go/analysis/passes/assign latest
go: finding golang.org/x/tools/go/analysis/passes/nilfunc latest
go: finding golang.org/x/tools/go/analysis/passes/ctrlflow latest
go: extracting golang.org/x/crypto v0.0.0-20190404164418-38d8ce5564a5
go: finding golang.org/x/tools/go/analysis/passes/tests latest
go: extracting golang.org/x/sys v0.0.0-20190405154228-4b34438f7a67
go: finding golang.org/x/sys v0.0.0-20190403152447-81d4e9dc473e
go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a
go: finding rsc.io/pdf v0.1.1
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
can't load package: /usr/local/go/src/cmd/internal/objfile/disasm.go:24:2: non-standard import "golang.org/x/arch/arm/armasm" in standard package "cmd/internal/objfile"
can't load package: /usr/local/go/src/cmd/pprof/pprof.go:28:2: non-standard import "github.com/google/pprof/driver" in standard package "cmd/pprof"
can't load package: /usr/local/go/src/cmd/trace/pprof.go:24:2: non-standard import "github.com/google/pprof/profile" in standard package "cmd/trace"
can't load package: /usr/local/go/src/cmd/vendor/github.com/google/pprof/driver/driver.go:26:2: non-standard import "github.com/google/pprof/profile" in standard package "cmd/vendor/github.com/google/pprof/driver"
can't load package: /usr/local/go/src/cmd/vendor/github.com/google/pprof/internal/binutils/disasm.go:24:2: non-standard import "github.com/ianlancetaylor/demangle" in standard package "cmd/vendor/github.com/google/pprof/internal/binutils"
can't load package: /usr/local/go/src/cmd/vendor/github.com/google/pprof/internal/driver/driver.go:30:2: non-standard import "github.com/google/pprof/profile" in standard package "cmd/vendor/github.com/google/pprof/internal/driver"
can't load package: /usr/local/go/src/cmd/vendor/github.com/google/pprof/internal/graph/graph.go:27:2: non-standard import "github.com/google/pprof/profile" in standard package "cmd/vendor/github.com/google/pprof/internal/graph"
can't load package: /usr/local/go/src/cmd/vendor/github.com/google/pprof/internal/measurement/measurement.go:24:2: non-standard import "github.com/google/pprof/profile" in standard package "cmd/vendor/github.com/google/pprof/internal/measurement"
can't load package: /usr/local/go/src/cmd/vendor/github.com/google/pprof/internal/plugin/plugin.go:24:2: non-standard import "github.com/google/pprof/profile" in standard package "cmd/vendor/github.com/google/pprof/internal/plugin"
can't load package: /usr/local/go/src/cmd/vendor/github.com/google/pprof/internal/report/report.go:33:2: non-standard import "github.com/google/pprof/profile" in standard package "cmd/vendor/github.com/google/pprof/internal/report"
can't load package: /usr/local/go/src/cmd/vendor/github.com/google/pprof/internal/symbolizer/symbolizer.go:31:2: non-standard import "github.com/google/pprof/profile" in standard package "cmd/vendor/github.com/google/pprof/internal/symbolizer"
can't load package: /usr/local/go/src/cmd/vendor/github.com/google/pprof/internal/symbolz/symbolz.go:30:2: non-standard import "github.com/google/pprof/profile" in standard package "cmd/vendor/github.com/google/pprof/internal/symbolz"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/crypto/ssh/terminal/util.go:20:2: non-standard import "golang.org/x/sys/unix" in standard package "cmd/vendor/golang.org/x/crypto/ssh/terminal"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/internal/analysisflags/flags.go:22:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/internal/analysisflags"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/internal/facts/facts.go:50:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/internal/facts"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/asmdecl/asmdecl.go:21:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/asmdecl"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/assign/assign.go:16:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/assign"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/atomic/atomic.go:14:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/atomic"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/bools/bools.go:14:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/bools"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/buildtag/buildtag.go:15:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/buildtag"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/cgocall/cgocall.go:21:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/cgocall"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/composite/composite.go:14:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/composite"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/copylock/copylock.go:16:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/copylock"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/ctrlflow/ctrlflow.go:17:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/ctrlflow"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/httpresponse/httpresponse.go:13:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/httpresponse"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/inspect/inspect.go:31:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/inspect"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/loopclosure/loopclosure.go:12:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/loopclosure"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/lostcancel/lostcancel.go:14:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/lostcancel"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/nilfunc/nilfunc.go:14:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/nilfunc"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/pkgfact/pkgfact.go:35:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/pkgfact"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/printf/printf.go:22:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/printf"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/shift/shift.go:20:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/shift"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/stdmethods/stdmethods.go:15:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/stdmethods"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/structtag/structtag.go:19:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/structtag"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/tests/tests.go:16:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/tests"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/unmarshal/unmarshal.go:13:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/unmarshal"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/unreachable/unreachable.go:15:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/unreachable"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/unsafeptr/unsafeptr.go:14:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/unsafeptr"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/passes/unusedresult/unusedresult.go:16:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/passes/unusedresult"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/analysis/unitchecker/unitchecker.go:50:2: non-standard import "golang.org/x/tools/go/analysis" in standard package "cmd/vendor/golang.org/x/tools/go/analysis/unitchecker"
can't load package: /usr/local/go/src/cmd/vendor/golang.org/x/tools/go/types/typeutil/callee.go:11:2: non-standard import "golang.org/x/tools/go/ast/astutil" in standard package "cmd/vendor/golang.org/x/tools/go/types/typeutil"
can't load package: /usr/local/go/src/cmd/vet/main.go:6:2: non-standard import "golang.org/x/tools/go/analysis/passes/asmdecl" in standard package "cmd/vet"
cmd/addr2line
cmd/api
cmd/asm
cmd/asm/internal/arch
cmd/asm/internal/asm
cmd/asm/internal/flags
cmd/asm/internal/lex
cmd/buildid
cmd/cgo
cmd/compile
cmd/compile/internal/amd64
cmd/compile/internal/arm
cmd/compile/internal/arm64
cmd/compile/internal/gc
cmd/compile/internal/mips
cmd/compile/internal/mips64
cmd/compile/internal/ppc64
cmd/compile/internal/s390x
cmd/compile/internal/ssa
cmd/compile/internal/syntax
cmd/compile/internal/test
cmd/compile/internal/types
cmd/compile/internal/wasm
cmd/compile/internal/x86
cmd/cover
cmd/dist
cmd/doc
cmd/fix
cmd/go
cmd/go/internal/base
cmd/go/internal/bug
cmd/go/internal/cache
cmd/go/internal/cfg
cmd/go/internal/clean
cmd/go/internal/cmdflag
cmd/go/internal/dirhash
cmd/go/internal/doc
cmd/go/internal/envcmd
cmd/go/internal/fix
cmd/go/internal/fmtcmd
cmd/go/internal/generate
cmd/go/internal/get
cmd/go/internal/help
cmd/go/internal/imports
cmd/go/internal/list
cmd/go/internal/load
cmd/go/internal/lockedfile
cmd/go/internal/lockedfile/internal/filelock
cmd/go/internal/modcmd
cmd/go/internal/modconv
cmd/go/internal/modfetch
cmd/go/internal/modfetch/codehost
cmd/go/internal/modfile
cmd/go/internal/modget
cmd/go/internal/modinfo
cmd/go/internal/modload
cmd/go/internal/module
cmd/go/internal/mvs
cmd/go/internal/par
cmd/go/internal/renameio
cmd/go/internal/run
cmd/go/internal/search
cmd/go/internal/semver
cmd/go/internal/str
cmd/go/internal/test
cmd/go/internal/tool
cmd/go/internal/txtar
cmd/go/internal/version
cmd/go/internal/vet
cmd/go/internal/web
cmd/go/internal/web2
cmd/go/internal/webtest
cmd/go/internal/work
cmd/gofmt
cmd/internal/bio
cmd/internal/browser
cmd/internal/buildid
cmd/internal/dwarf
cmd/internal/edit
cmd/internal/gcprog
cmd/internal/goobj
cmd/internal/obj
cmd/internal/obj/arm
cmd/internal/obj/arm64
cmd/internal/obj/mips
cmd/internal/obj/ppc64
cmd/internal/obj/s390x
cmd/internal/obj/wasm
cmd/internal/obj/x86
cmd/internal/objabi
cmd/internal/src
cmd/internal/sys
cmd/internal/test2json
cmd/link
cmd/link/internal/amd64
cmd/link/internal/arm
cmd/link/internal/arm64
cmd/link/internal/ld
cmd/link/internal/loadelf
cmd/link/internal/loadmacho
cmd/link/internal/loadpe
cmd/link/internal/loadxcoff
cmd/link/internal/mips
cmd/link/internal/mips64
cmd/link/internal/objfile
cmd/link/internal/ppc64
cmd/link/internal/s390x
cmd/link/internal/sym
cmd/link/internal/wasm
cmd/link/internal/x86
cmd/nm
cmd/objdump
cmd/pack
cmd/test2json
cmd/vendor/github.com/google/pprof/internal/elfexec
cmd/vendor/github.com/google/pprof/internal/proftest
cmd/vendor/github.com/google/pprof/internal/transport
cmd/vendor/github.com/google/pprof/profile
cmd/vendor/github.com/google/pprof/third_party/d3
cmd/vendor/github.com/google/pprof/third_party/d3flamegraph
cmd/vendor/github.com/google/pprof/third_party/svgpan
cmd/vendor/github.com/ianlancetaylor/demangle
cmd/vendor/golang.org/x/arch/arm/armasm
cmd/vendor/golang.org/x/arch/arm64/arm64asm
cmd/vendor/golang.org/x/arch/ppc64/ppc64asm
cmd/vendor/golang.org/x/arch/x86/x86asm
cmd/vendor/golang.org/x/sys/unix
cmd/vendor/golang.org/x/sys/windows
cmd/vendor/golang.org/x/sys/windows/registry
cmd/vendor/golang.org/x/tools/go/analysis
cmd/vendor/golang.org/x/tools/go/analysis/passes/internal/analysisutil
cmd/vendor/golang.org/x/tools/go/ast/astutil
cmd/vendor/golang.org/x/tools/go/ast/inspector
cmd/vendor/golang.org/x/tools/go/cfg
cmd/vendor/golang.org/x/tools/go/types/objectpath
</pre></details>

**Comment by bcmills** [comment] 2019-04-10 18:55
Duplicate of #26924

**Closed** 2019-04-10 18:55 UTC
