### ISSUE TITLE
cmd/go: "The system cannot find the path specified" error during go get

### ISSUE THREAD

**Issue by MrSpock** [golang/go#24968] opened 2018-04-20 09:45 UTC
Hi,

After upgrade to go1.10 I can't download packages. I've tried few of them.

### What version of Go are you using (`go version`)?
PS C:\Users\spock\go\src\github.com\mrspock> go version
go version go1.10.1 windows/amd64

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
```
PS C:\Users\spock\go\src\github.com\mrspock> go env| Select-String GOHOST

set GOHOSTARCH=amd64
set GOHOSTOS=windows
```

### What did you do?
Example command:

```
PS C:\Users\spock\go\src\github.com\mrspock> pwd

Path
----
C:\Users\spock\go\src\github.com\mrspock
```

```
go get github.com/mrspock/godocsis
package github.com/mrspock/godocsis: mkdir C:\Users\spock\go\src\github.com\mrspock\: The system cannot find the path specified.
```

I've tried with package where top directory doent' exist. Error is the same.
```
PS C:\Users\spock\go\src\github.com\mrspock> go get github.com/jrallison/go-workers
package github.com/jrallison/go-workers: mkdir C:\Users\spock\go\src\github.com: The system cannot find the path specified.
PS C:\Users\spock\go\src\github.com\mrspock>
```
### What did you expect to see?
Proper package install

**Comment by davecheney** [comment] 2018-04-20 09:46
Is OneDrive involved in any way>

**Comment by MrSpock** [comment] 2018-04-20 10:32
Yes.
src is on OneDrive.

**Comment by ianlancetaylor** [comment] 2018-04-20 12:50
What does `go env GOPATH` print?

**Comment by davecheney** [comment] 2018-04-23 04:38
Please search the issue tracker for recently closed issues involving one drive. This has been addressed in the last month or so.

**Comment by mattn** [comment] 2018-04-24 05:03
@MrSpock If your problem is same as https://github.com/golang/go/issues/22579, please close this.

**Comment by davecheney** [comment] 2018-05-04 09:40
Duplicate of #22579

**Closed** 2018-05-04 09:39 UTC
Labels: NeedsInvestigation, OS-Windows
