### ISSUE TITLE
cmd/link: vanadium installation Error: combining dwarf failed: Unknown load command 0x32 (50) 

### ISSUE THREAD

**Issue by Yiqing2018** [golang/go#29539] opened 2019-01-03 22:49 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.11.4 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/yiqingliu/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yiqingliu/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zj/m3r07q5x7xzg89lrpp16vxkw0000gn/T/go-build723821650=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I followed the instruction to install Vanadium  https://vanadium.github.io/installation/
os
```
MacOS Mojave version 10.14.2
```
curl
```
curl 7.60.0 (x86_64-apple-darwin13.4.0) libcurl/7.60.0 OpenSSL/1.0.2o zlib/1.2.11
Release-Date: 2018-05-16
```
git
```
git version 2.17.2 (Apple Git-113)
 ```
Error info:   
```
Block 'installVanadiumBinaries' (9/9 in test) of content/installation/step-by-step.md
# v.io/x/ref/services/agent/v23agentd
/Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: /Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)

# v.io/x/ref/lib/discovery/plugins/ble/corebluetooth
vanadium/release/go/src/v.io/x/ref/lib/discovery/plugins/ble/corebluetooth/CBAdvertisingDriver.m:213:10: warning: 'CBPeripheralManagerStatePoweredOn' is deprecated: first deprecated in macOS 10.13 - Use CBManagerState instead [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreBluetooth.framework/Headers/CBPeripheralManager.h:55:28: note: 'CBPeripheralManagerState' has been explicitly marked deprecated here
......

# v.io/x/ref/services/syncbase/syncbased
/Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: /Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)

# v.io/x/ref/services/syncbase/bridge/cgo
/Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: /Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)
```
I tried to install earlier version of Go, still got the same error.  

### What did you expect to see?

```
# Install specific tools needed for the tutorials.
jiri go install v.io/x/ref/cmd/... v.io/x/ref/services/agent/... v.io/x/ref/services/mounttable/... v.io/x/ref/services/syncbase/...
```
runs with no error

### What did you see instead?
above error msg

**Comment by ianlancetaylor** [comment] 2019-01-03 23:57
Are you sure you are using 1.11.4?  This looks exactly like #25908 which should be fixed in 1.11.4 and in 1.12beta1.

**Comment by Yiqing2018** [comment] 2019-01-04 00:18
> Are you sure you are using 1.11.4? This looks exactly like #25908 which should be fixed in 1.11.4 and in 1.12beta1.

Yes, I just installed Go on my computer, it is the latest version 1.11.4
$ go version
go version go1.11.4 darwin/amd64

**Comment by ianlancetaylor** [comment] 2019-01-04 00:20
Huh.  I have no explanation.  That specific error message should be impossible in 1.11.4.

**Comment by wwwennn** [comment] 2019-01-04 00:23
I followed the same Vanadium page and met the same problem here. I installed several different versions of Go by pkg and homebrew.

**Comment by cherrymui** [comment] 2019-01-04 01:40
> Error info:
> ```
>  Block 'installVanadiumBinaries' (9/9 in test) of content/installation/step-by-step.md
> # v.io/x/ref/services/agent/v23agentd
> /Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: /Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)
> 
> # v.io/x/ref/lib/discovery/plugins/ble/corebluetooth
> vanadium/release/go/src/v.io/x/ref/lib/discovery/plugins/ble/corebluetooth/CBAdvertisingDriver.m:213:10: warning: 'CBPeripheralManagerStatePoweredOn' is deprecated: first deprecated in macOS 10.13 - Use CBManagerState instead [-Wdeprecated-declarations]
> /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreBluetooth.framework/Headers/CBPeripheralManager.h:55:28: note: 'CBPeripheralManagerState' has been explicitly marked deprecated here
> ......
> 
> # v.io/x/ref/services/syncbase/syncbased
> /Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: /Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)
> 
> # v.io/x/ref/services/syncbase/bridge/cgo
> /Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: /Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)
> ```

Apparently this seems like it is running Go 1.8.3?

I don't know about jiri, but could you try `jiri go version` to see what version of Go is used by jiri?

**Comment by Yiqing2018** [comment] 2019-01-04 01:47
> > Error info:
> > ```
> >  Block 'installVanadiumBinaries' (9/9 in test) of content/installation/step-by-step.md
> > # v.io/x/ref/services/agent/v23agentd
> > /Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: /Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)
> > 
> > # v.io/x/ref/lib/discovery/plugins/ble/corebluetooth
> > vanadium/release/go/src/v.io/x/ref/lib/discovery/plugins/ble/corebluetooth/CBAdvertisingDriver.m:213:10: warning: 'CBPeripheralManagerStatePoweredOn' is deprecated: first deprecated in macOS 10.13 - Use CBManagerState instead [-Wdeprecated-declarations]
> > /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreBluetooth.framework/Headers/CBPeripheralManager.h:55:28: note: 'CBPeripheralManagerState' has been explicitly marked deprecated here
> > ......
> > 
> > # v.io/x/ref/services/syncbase/syncbased
> > /Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: /Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)
> > 
> > # v.io/x/ref/services/syncbase/bridge/cgo
> > /Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: /Users/username/vanadium/.jiri_root/profiles/v23/go/shared/1.8.3/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)
> > ```
> 
> Apparently this seems like it is running Go 1.8.3?
> 
> I don't know about jiri, but could you try `jiri go version` to see what version of Go is used by jiri?

Thx! i will try

**Comment by ALTree** [comment] 2019-07-03 14:22
Likely a dup of #25908 caused by the tool using an old Go installation, no one ever reported this again; I suspect we can close here.

**Closed by ALTree** 2019-07-03 14:22 UTC
Labels: NeedsInvestigation, OS-Darwin
