### ISSUE TITLE
x/tools/go/imports: some tests failing on FreeBSD

### ISSUE THREAD

**Issue by alandonovan** [golang/go#28132] opened 2018-10-10 18:35 UTC
This log was produced by the builder:
```
2018/10/10 18:26:55 goimports: scanning directory /tmp/workdir/go/src: open /tmp/workdir/go/src/cmd/compile/internal/ssa/testdata : no such file or directory
2018/10/10 18:26:55 goimports: scanning directory /tmp/workdir/go/src: open /tmp/workdir/go/src/cmd/compile/internal/ssa/testdata : no such file or directory
2018/10/10 18:26:55 goimports: scanning directory /tmp/workdir/go/src: open /tmp/workdir/go/src/math/randamd6fD: no such file or directory
--- FAIL: TestFindImportInternal (0.01s)
    fix_test.go:1443: findImportGoPath("race", Acquire ...) = "", false; want "internal/race", false
2018/10/10 18:26:55 goimports: scanning directory /tmp/workdir/go/src: open /tmp/workdir/go/src/math/randamd6fD: no such file or directory
--- FAIL: TestProcessVendor (0.03s)
    fix_test.go:1536: Process("/tmp/workdir/go/src/math/x.go") did not add expected hpack import "golang_org/x/net/http2/hpack"; got:
        package http
        
        import "strings"
        
        func f() { strings.NewReader(); hpack.HuffmanDecode() }
2018/10/10 18:26:55 goimports: scanning directory /tmp/workdir/go/src: open /tmp/workdir/go/src/runtime/testdata.go: no such file or directory
2018/10/10 18:26:55 goimports: scanning directory /tmp/workdir/go/src: open /tmp/workdir/go/src/runtime/msan	: no such file or directory
2018/10/10 18:26:55 goimports: scanning directory /tmp/workdir/go/src: open /tmp/workdir/go/src/cmd/compile/internal/ssa/testdata : no such file or directory
2018/10/10 18:26:55 goimports: scanning directory /tmp/workdir/go/src: open /tmp/workdir/go/src/cmd/compile/internal/ssa/testdata : no such file or directory
2018/10/10 18:26:55 goimports: scanning directory /tmp/workdir/go/src: open /tmp/workdir/go/src/cmd/compile/internal/ssa/testdata : no such file or directory
2018/10/10 18:26:55 goimports: scanning directory /tmp/workdir/go/src: open /tmp/workdir/go/src/cmd/compile/internal/ssa/testdata : no such file or directory
2018/10/10 18:26:55 goimports: scanning directory /tmp/workdir/go/src: open /tmp/workdir/go/src/runtime/msan	: no such file or directory
2018/10/10 18:26:55 goimports: scanning directory /tmp/workdir/go/src: open /tmp/workdir/go/src/net/testdatamail: no such file or directory
2018/10/10 18:26:55 goimports: scanning directory /tmp/workdir/go/src: open /tmp/workdir/go/src/cmd/compile/internal/ssa/testdata : no such file or directory
FAIL
FAIL	golang.org/x/tools/imports	0.509s
```

Will suppress test for now.  The task of this issue is to fix and reenable the test.

**Comment by heschik** [comment] 2018-10-10 20:18
Dupe of #28131.

**Closed by heschik** 2018-10-10 20:18 UTC
