### ISSUE TITLE
How do I update the module-dependent version of go？

### ISSUE THREAD

**Issue by JokerDevops** [golang/go#37548] opened 2020-02-28 07:44 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jinxiaozhang/Library/Caches/go-build"
GOENV="/Users/jinxiaozhang/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="github.com/JokerDevops/supervisorctl-cli.go"
GONOSUMDB="github.com/JokerDevops/supervisorctl-cli.go"
GOOS="darwin"
GOPATH="/Users/jinxiaozhang/go"
GOPRIVATE="github.com/JokerDevops/supervisorctl-cli.go"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_q/wjnpyt252pd8vgfy5mrmqkt80000gp/T/go-build642781873=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
```
go get github.com/thedevsaddam/gojsonq@v2.5.0
```

### What did you expect to see?
```
Download the module version I need correctly
```

### What did you see instead?
```
go get github.com/thedevsaddam/gojsonq@v2.5.0: github.com/thedevsaddam/gojsonq@v2.5.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

**Comment by ALTree** [comment] 2020-02-28 10:14
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-02-28 10:14 UTC

**Comment by thepudds** [comment] 2020-02-28 22:23
@JokerDevops you could try:

`go get github.com/thedevsaddam/gojsonq/v2@v2.5.0`

Note the `/v2` before the @.
