### ISSUE TITLE
time: optimize Parse for RFC3339 and RFC3339Nano

### ISSUE THREAD

**Issue by amarjeetanandsingh** [golang/go#54561] opened 2022-08-20 06:20 UTC
Optimize Time.Parse for https://github.com/golang/go/issues/54093

**Comment by dsnet** [comment] 2022-08-20 17:57
Closing as duplicate of #54093. I don't think we need to create a new issue for every change we make. The CL can just reference #54093.

**Closed by dsnet** 2022-08-20 17:57 UTC
Labels: Performance, NeedsFix
