### ISSUE TITLE
database/sql.(*DB).conn: slice bounds out of range [:824640893215] with capacity 0

### ISSUE THREAD

**Issue by juliusmh** [golang/go#41938] opened 2020-10-12 15:05 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
The problem occurs only sometimes, so reproducing is hard. The error happens on the latest released version.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xyz/.cache/go-build"
GOENV="/home//xyz/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home//xyz/go/pkg/mod"
GONOPROXY="github.com/xyz"
GONOSUMDB="github.com/xyz"
GOOS="linux"
GOPATH="/home/juliusmh/go/"
GOPRIVATE="github.com/grid-x"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build786391877=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
We're using `sql/database.DB.PingContext(...)` to check connectivity status to a postgres database in a handler, which is invoked in a goroutine. Sometimes the call crashes with an error that is beyond my understanding.

```go
// It's standard use I would guess:
// db is of type *sql.DB
// we're connected to a postgres DB using sqlx, we use "github.com/lib/pq"
db.SetMaxOpenConns(30)
db.SetMaxIdleConns(15)
db.SetConnMaxLifetime(30*time.Minute)
db.SetConnMaxIdleTime(5*time.Minute)
go func(){
    ctx, cancel := context.WithTimeout(context.Background, 4*time.Second)
    err := db.PingContext(ctx)
    cancel()
    if err != nil { ... }
}
```

### What did you expect to see?
I want to either receive an error, or nil. Got panic instead.

### What did you see instead?
<pre>
10:34:30.092 panic: runtime error: slice bounds out of range [:824640893215] with capacity 0
10:34:30.092 goroutine 152927555 [running]:
10:34:30.092 database/sql.(*DB).conn(0xc00000eb08, 0x1b856e0, 0xc00111b680, 0x1, 0x261b140, 0x0, 0xc000e93ea8)
10:34:30.092 	/usr/local/go/src/database/sql/sql.go:1209 +0xfb2
10:34:30.092 database/sql.(*DB).PingContext(0xc00000eb08, 0x1b856e0, 0xc00111b680, 0x0, 0xc001cc237f)
10:34:30.092 	/usr/local/go/src/database/sql/sql.go:799 +0x90
10:34:30.092 github.com/xyz/foo/pkg/bar.(*FooBar).Status(0xc0007c75f0, 0x1b856e0, 0xc00111b680, 0x100000001, 0x0, 0xc00008a060, 0x0)
</pre>

**Comment by davecheney** [comment] 2020-10-12 20:51
This could be memory corruption. Have you tried running your program under the race detector? See https://blog.golang.org/race-detector .

**Comment by ALTree** [comment] 2021-06-18 08:16
It seems likely this was caused by memory corruption or a data race, and we don't have a reproducer, so there's not much to investigate here. The issue can also be no longer reproduced by the reporter, so I'm closing the issue.

**Closed by ALTree** 2021-06-18 08:16 UTC
Labels: WaitingForInfo
