### ISSUE TITLE
net/http/httptest: does not support standard TLS client requests

### ISSUE THREAD

**Issue by lmtyler** [golang/go#37527] opened 2020-02-27 23:21 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.8 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
attempting to use httptest to mock a http response with a client request

### What did you expect to see?
Successful client response

### What did you see instead?
Get https://127.0.0.1:65088: x509: certificate signed by unknown authority

[This TLS Fails](https://play.golang.org/p/-5OrA3Jh8lc)
[This TLS Works](https://play.golang.org/p/N4b8QnW4yfK)

You must set InsecureSkipVerify: true for it to work, which I am not able to do
[this TLS works but not ok](https://play.golang.org/p/-5OrA3Jh8lc)

[NON TLS Succeeded](https://play.golang.org/p/OCZ_pthtQOC)

**Comment by cagedmantis** [comment] 2020-02-28 20:20
@lmtyler Have you considered using [NewTLSServer](https://golang.org/pkg/net/http/httptest/#NewTLSServer) instead? This is working as intended. I'm going to close this issue. If you think I closed it in error, please comment below.

**Closed by cagedmantis** 2020-02-28 20:20 UTC

**Comment by lmtyler** [comment] 2020-02-28 20:37
That produces the same results

I was able to figure out how to get around it
`	cert, err := x509.ParseCertificate(ts.TLS.Certificates[0].Certificate[0])
	if err != nil {
		t.Fatal(err)
	}

	var buf bytes.Buffer
	if err := pem.Encode(&buf, &pem.Block{Type: "CERTIFICATE", Bytes: cert.Raw}); err != nil {
		t.Fatalf("Yikes!  %v", err)
	}
`
I believe this should be added to documentation or better yet a method added to get the certificate as a PEM file

**Comment by kendalharland** [comment] 2020-03-06 23:32
This seems similar to https://github.com/golang/go/issues/18411 which was closed, but apparently the issue has not been resolved
