### ISSUE TITLE
x/tools/gopls: too many memory usage

### ISSUE THREAD

**Issue by tianhongw** [golang/go#37759] opened 2020-03-09 14:10 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes
<pre>
$ gopls version
golang.org/x/tools/gopls v0.3.3
    golang.org/x/tools/gopls@v0.3.3 h1:mTFqRDJQmpSsgDDWvbtGnSva1z9uX2XcDszSWa6DhBQ=
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre>GO111MODULE="auto"
GOARCH="amd64"
GOBIN="/Users/wutianhong/go/bin"
GOCACHE="/Users/wutianhong/Library/Caches/go-build"
GOENV="/Users/wutianhong/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/wutianhong/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dj/qmfvb5s5595grm_pn25n40100000gn/T/go-build406632642=/tmp/go-build -gno-record-gcc-switches -fno-common"</details>

### What did you do?

- os: MacOs 10.14.6
- editor: Emacs 26.3
- go project: a large project with 12k+ go files

**emacs config**
<img width="587" alt="Screen Shot 2020-03-09 at 21 59 59" src="https://user-images.githubusercontent.com/12781396/76219963-9fbc1d00-6251-11ea-94fb-75750c3d3255.png">

### What did you expect to see?
less memory usage instead of 8.53GB

### What did you see instead?
<img width="579" alt="Screen Shot 2020-03-09 at 18 58 22" src="https://user-images.githubusercontent.com/12781396/76218358-14da2300-624f-11ea-8fbf-43e892139811.png">

**heap profile**
[pprof.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/golang/go/files/4307012/pprof.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)

Ref: #36943

**Comment by stamblerre** [comment] 2020-03-09 17:39
Thanks for reporting this issue and for providing the heap profile! I took a look at it, and this seems to be the same issue as https://github.com/golang/go/issues/37670. Unfortunately, my responseis the same as @heschik's in the issue (https://github.com/golang/go/issues/37670#issuecomment-595403687):

> Thanks.
> 
> Unfortunately I don't have good news for you. Everything you've posted points to expected behavior -- I don't see any signs of a memory leak or work pileup. It looks like the monorepo is simply too large to work with all at once.
> 
> If you're only interested in one folder, you can start VS Code in that folder. If you're interested in multiple, you can add them piecemeal to your workspace, but note that most `gopls` features, e.g. find references, will only work within one folder.

We'll work on an approach for improving this in `gopls/v1.0.0`.

**Comment by tianhongw** [comment] 2020-03-10 04:40
> Thanks for reporting this issue and for providing the heap profile! I took a look at it, and this seems to be the same issue as #37670. Unfortunately, my response is the same as @heschik's in the issue ([#37670 (comment)](https://github.com/golang/go/issues/37670#issuecomment-595403687)):
> 
> > Thanks.
> > Unfortunately I don't have good news for you. Everything you've posted points to expected behavior -- I don't see any signs of a memory leak or work pileup. It looks like the monorepo is simply too large to work with all at once.
> > If you're only interested in one folder, you can start VS Code in that folder. If you're interested in multiple, you can add them piecemeal to your workspace, but note that most `gopls` features, e.g. find references, will only work within one folder.
> 
> We'll work on an approach for improving this in `gopls/v1.0.0`.

Thanks for your reply!  Should i keep this issue open?

**Comment by stamblerre** [comment] 2020-03-11 03:19
Thanks for following up. I think this issue can be closed and marked as a duplicate of #37670..

**Comment by stamblerre** [comment] 2020-03-11 03:19
Duplicate of #37670

**Closed by stamblerre** 2020-03-11 03:19 UTC
Labels: Tools, gopls
