### ISSUE TITLE
cmd/go: go clean -modcache should not download modules

### ISSUE THREAD

**Issue by perillo** [golang/go#36798] opened 2020-01-27 14:37 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/manlio/.local/bin"
GOCACHE="/home/manlio/.cache/go-build"
GOENV="/home/manlio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="github.com/perillo"
GONOSUMDB="github.com/perillo"
GOOS="linux"
GOPATH="/home/manlio/.local/lib/go:/home/manlio/src/go"
GOPRIVATE="github.com/perillo"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/manlio/sdk/go1.14beta1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/manlio/sdk/go1.14beta1/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build740722259=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.14beta1 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.14beta1
uname -sr: Linux 5.4.15-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.30.
gdb --version: GNU gdb (GDB) 8.3.1
</pre></details>

### What did you do?

From inside an empty module (a directory with a `go.mod` file but no `.go` source files:

`go clean -modcache -n github.com/perillo/i3workon`

### What did you expect to see?

I was expecting to see only the commands used to remove the module cache.

### What did you see instead?

```
go: downloading github.com/perillo/i3workon v0.3.0
go: downloading golang.org/x/tools v0.0.0-20200115044656-831fdb1e1868
cd /home/manlio/.local/lib/go/pkg/mod/github.com/perillo/i3workon@v0.3.0
rm -f i3workon@v0.3.0 i3workon@v0.3.0.exe i3workon@v0.3.0.test i3workon@v0.3.0.test.exe main main.exe
rm -rf /home/manlio/.local/lib/go/pkg/mod
```

`go clean` is downloading the module, since it is not present in the cache, and then removing it.

There is also something strange with the commands `go clean` is using.
If, in the end, it is going to remove the entire `$GOPATH/pkg/mod` directory, what's the use of first trying to remove the specified package first?

I also don't really understand what 
```
rm -f i3workon@v0.3.0 i3workon@v0.3.0.exe i3workon@v0.3.0.test i3workon@v0.3.0.test.exe main main.exe
```
is trying to do.
These files do not exist.

**Comment by perillo** [comment] 2020-01-27 14:54
After having seen the output of `go clean -modcache -n -r github.com/perillo/iworkon`, it seems that the `go clean` command thinks that its cleaning a newly built go distribution.

**Comment by perillo** [comment] 2020-01-27 15:03
I think `go clean -modcache -n <modpath>` should only remove all the versions of `<modpath>` from the module cache, instead of cleaning the entire module cache.

**Comment by bcmills** [comment] 2020-01-27 16:02
`go clean` is unfortunately pretty overloaded. (See https://tip.golang.org/cmd/go/#hdr-Remove_object_files_and_cached_files for the full details.)

#28835 proposes a `-m` flag to tell `go clean` to remove only the requested module, which is semantically different from the meaning of package arguments to `go clean` today.

CC @jayconrod @matloob

**Comment by bcmills** [comment] 2020-01-27 16:03
#32976 is a more focused request for module arguments to `go clean`.

**Comment by bcmills** [comment] 2020-01-27 16:03
Duplicate of #32977

**Closed by bcmills** 2020-01-27 16:03 UTC
Labels: NeedsInvestigation, modules
