### ISSUE TITLE
x/build:  windows-arm64 builders are missing

### ISSUE THREAD

**Issue by thanm** [golang/go#51546] opened 2022-03-08 15:05 UTC
Looks as though the windows/arm64 builders are sick / MIA.  

farmer.golang.org reports:

```
Reverse pool by host type (in use / total)
...
host-windows-arm64-mini: 0/0 (6 missing)
host-windows-arm64-zx2c4: 0/0 (1 missing)
host-windows11-arm64-mini: 0/0 (1 missing)
```

Looks like no builder activity on recent CLs:

![wbuilders](https://user-images.githubusercontent.com/12280172/157264427-c5dbebb9-4ec4-45b7-824f-4236432b75cb.png)

I went back through the status page and it looks like windows-arm64-zx2c4 has been out for quite some time. Last CL to have a windows-arm64 run was [this one](https://go-review.googlesource.com/c/go/+/373363?forceReload=true) on March 4th .

**Comment by cagedmantis** [comment] 2022-03-08 15:06
cc @golang/release

**Comment by dmitshur** [comment] 2022-03-10 21:08
The builder images have been updated so they're no longer getting stuck, and they're back on farmer.golang.org (along with the corrected expected count—it's currently 5 windows-arm64-11 and 2 windows-arm64-10 builders):

```
Reverse pool by host type (in use / total)
[...]
• host-windows-arm64-mini: 2/2
• host-windows11-arm64-mini: 5/5
```

(These builders briefly disconnect in between builds, so it is normal that some are missing at points in time. As long as they reconnect within a few mins, it's working as intended.)

This is resolved, so closing.

**Closed** 2022-03-10 21:10 UTC
Labels: OS-Windows, Builders, release-blocker, Soon, arch-arm64
