### ISSUE TITLE
cmd/compile: generate closure for go/defer builtin calls

### ISSUE THREAD

**Issue by unixpickle** [golang/go#19710] opened 2017-03-25 15:32 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

Go 1.8.
Also happens on play.golang.org.

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?

Evaluate this code:

```go
package main

import "fmt"

func main() {
	fmt.Println("should be 0:", len(foobar()))
}

func foobar() map[int]bool {
	m := map[int]bool{}
	for i := 0; i < 3; i++ {
		m[i] = true
		defer delete(m, i)
	}
	return m
}
```

### What did you expect to see?

```
should be 0: 0
```

### What did you see instead?

```
should be 0: 2
```

The `defer` statement is supposed to freeze its arguments the instant it is evaluated, but it does not when used with `delete`. Compare to this program, which works correctly:

```go
package main

import "fmt"

func main() {
	fmt.Println("should be 0:", len(foobar()))
}

func foobar() map[int]bool {
	m := map[int]bool{}
	for i := 0; i < 3; i++ {
		m[i] = true
		defer myDelete(m, i)
	}
	return m
}

func myDelete(m map[int]bool, k int) {
	delete(m, k)
}
```

**Comment by mattn** [comment] 2017-03-25 15:46
This is my interesting. Why you use defer delete?

**Comment by unixpickle** [comment] 2017-03-25 15:49
@mattn I have a map that I occasionally add temporary values to (for intermediate computations). I was trying to use defer+delete to remove those temporary entries automatically.

**Comment by bradfitz** [comment] 2017-03-25 16:26
Good news and bad news:

Bad news is this has been broken forever. (I tested Go 1.5, Go 1.6, Go 1.7, and Go 1.8) Because it's not a regression and has been fixed forever, it doesn't qualify for a Go 1.8.1 cherry-pick.

Good news is that it's fixed at tip (what will be Go 1.9).

I haven't bisected to see where it was fixed and whether it was intentional. If it was fixed by accident, it likely still lacks a test.

/cc @griesemer @randall77 @mdempsky @josharian

**Comment by josharian** [comment] 2017-03-25 16:54
Probably fixed by the order.go changes for mapdelete_fast*. Yes, needs a test. Should double-check go delete(x), and defer/delete of the other built-in functions.

**Comment by cespare** [comment] 2017-03-25 16:54
A bisect points at 5d6b7fcaa1444f6c17d519c9ce7bc0771bfd96ec (CL [38172](https://go-review.googlesource.com/c/38172/))

> runtime: add mapdelete_fast*

**Comment by josharian** [comment] 2017-03-25 17:59
order.go, walk.go, and ssa.go are scattered with special handling of go/defer of built-in functions. I wonder whether instead we should just do a very early rewrite of

```go
defer builtin(a, b, c)
```

to

```go
defer func(a T, b T, c T) {
  builtin(a, b, c)
}(a, b, c)
```

That would probably also simplify instrumentation of such cases, which are also the topic of scattered special handling.

**Comment by randall77** [comment] 2017-03-25 18:15
@josharian I was thinking the same thing.

**Comment by josharian** [comment] 2017-05-15 17:36
I think we should add a test for 1.9 and and leave the closurization of deferred built-ins for 1.10. (That will also enable us to simplify other things, like not lowering OPANIC in walk.go.)

I'll send a test CL.

**Comment by josharian** [comment] 2017-05-19 23:56
Note to self: walkprintfunc does this now for `defer println(...)`. It also has a minor naming bug: `lookupN("print·%d", walkprintfunc_prgen)` generates names like `"".print·%d1·f`. :P

**Comment by cuonglm** [comment] 2020-10-22 15:34
This is fixed at tip, we can close this now cc @mdempsky

**Closed** 2020-10-22 17:03 UTC
Labels: NeedsFix
