### ISSUE TITLE
cmd/go: support -buildmode=c-shared on freebsd/amd64

### ISSUE THREAD

**Issue by whatest000** [golang/go#22078] opened 2017-09-28 11:26 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.8.3 freebsd/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOOS="freebsd"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build225258924=/tmp/go-build -gno-record-gcc-switches"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
build a .so file for my c program
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by ianlancetaylor** [comment] 2017-09-28 16:51
Would you be interested in looking into this?  It may already work, it may just need to be enabled in cmd/go and cmd/link.

**Comment by whatest000** [comment] 2017-09-29 15:53
i am interested, what should i do?

**Comment by ianlancetaylor** [comment] 2017-09-29 17:04
@whatest000 Thanks.  Edit cmd/go/internal/work/build.go and cmd/link/internal/ld/config.go to permit c-shared on the three FreeBSD targets (freebsd-386, freebsd-amd64, freebsd-arm).  Edit cmd/dist/test.go (*tester).supportedBuildMode to say that c-shared is supported on those targets.  Run all.bash.  See what fails.

**Comment by DamjanJovanovic** [comment] 2017-12-12 13:40
The relevant code in cmd/go/internal/work/build.go was moved. My bisection revealed it's now in src/cmd/go/internal/work/init.go as of commit 36323e4313f281ef209055b279f449feb5fcfa39 on 6 November 2017.

**Comment by DamjanJovanovic** [comment] 2018-07-13 18:08
--buildmode=c-shard works in the latest Git. It was fixed by:

commit 88129f0cb2438b555fd1dc74c707408251902b4e
Author: Tim Wright <tenortim@gmail.com>
Date:   Tue Feb 13 19:00:17 2018 -0800

    all: enable c-shared/c-archive support for freebsd/amd64
    
    Fixes #14327
    Much of the code is based on the linux/amd64 code that implements these
    build modes, and code is shared where possible.
    
    Change-Id: Ia510f2023768c0edbc863aebc585929ec593b332
    Reviewed-on: https://go-review.googlesource.com/93875
    Run-TryBot: Ian Lance Taylor <iant@golang.org>
    TryBot-Result: Gobot Gobot <gobot@golang.org>
    Reviewed-by: Ian Lance Taylor <iant@golang.org>

**Comment by DamjanJovanovic** [comment] 2018-07-13 18:09
And this bug is a duplicate of #14327.

**Comment by ianlancetaylor** [comment] 2018-07-13 18:22
Thanks, closing.

**Closed by ianlancetaylor** 2018-07-13 18:22 UTC
Labels: OS-FreeBSD
