### ISSUE TITLE
x/tools/cmd/gopls: "build cache is required, but could not be located: GOCACHE is not defined and $HOME is not defined" 

### ISSUE THREAD

**Issue by 23doors** [golang/go#32238] opened 2019-05-24 21:48 UTC
#### What did you do?
Open go file in VSCode configured for using gopls language server.

#### What did you expect to see?
No errors and working gopls.

#### What did you see instead?
Error on my package statement:

```
[Error - 11:39:40 PM] unable to check package for file:///<removed>.go: go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]: exit status 1: build cache is required, but could not be located: GOCACHE is not defined and $HOME is not defined
```

#### Build info

Installed gopls through:
```
go get -u golang.org/x/tools/cmd/gopls
```

This used to work a few days ago so I tested different commits and it seems that:
2c78df6d2ceec2cde4b7bff46c9b42cd05742fe1 is the most recent one that works (no errors). And next one: https://github.com/golang/tools/commit/7927dbab1be7d178ed14189b31e26c604b8baba8 causes it to break.

#### Go info
```
go version go1.12.5 darwin/amd64
```

**Comment by zchee** [comment] 2019-05-27 20:22
@23doors
Just set `"gopls.env": {"GOPATH": "your gopath", "GOCACHE": "your gocache"}` to your `settings.json` (`settings.json` is correct name? I forgot. I don't usually use vscode, I'm Neovim user)

Also, Now typing iPhone. might be invalid json syntax, sorry.

**Comment by 23doors** [comment] 2019-05-27 21:39
@zchee this fixed it, thank you! But on 2c78df6d2ceec2cde4b7bff46c9b42cd05742fe1 I wasn't required to set it, so this seems like a regression or a vscode-go issue. Also, I used same GOPATH and GOCACHE as from `go env` output.

**Comment by zchee** [comment] 2019-05-27 22:18
@23doors 
yes, maybe caused by any regression or vscode-go issue.

> Also, I used same GOPATH and GOCACHE as from go env output.

It means set `settings.json` to same values from `go env`, right?
If so, your seeting is correct. seems to didn't parses `go env` values caused by any bugs.

Unfortunately, I don't know which is buggy, because I first lauch vscode yesterday lol
I found this workaround when debugging this issue:
https://github.com/golang/go/issues/29202#issuecomment-495926430

**Comment by bcmills** [comment] 2019-05-28 18:00
CC @stamblerre @ianthehat

**Comment by stamblerre** [comment] 2019-05-28 19:48
Can you provide a `gopls` log with redacted filenames? It can be found by going to "View: Debug Console" -> "Output" -> "Tasks" -> "gopls". At the very least, the top of your log would be helpful because it prints out your environment information. There error message you provided is surprising because we never run any `go list` command that looks like that.

**Comment by 23doors** [comment] 2019-05-28 20:05
@stamblerre here it is, redacted file names and removed duplicate messages:
```
[Info  - 10:03:05 PM] #### Build info

no module information, gopls not built in module mode


#### Go info

go version go1.12.5 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/V/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/V/Go"
GOPROXY="https://proxy.golang.org"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2 -w"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pd/hq5jjzqd6wq07z6xcrc1875m0000gr/T/go-build712859041=/tmp/go-build -gno-record-gcc-switches -fno-common"

[Error - 10:03:05 PM] unable to check package for file:///Users/V/Projects/redacted.go: go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]: exit status 1: build cache is required, but could not be located: GOCACHE is not defined and $HOME is not defined

[Error - 10:03:06 PM] failed to deliver diagnostic for file:///Users/V/Projects/redacted/go%20%5Blist%20-f%20%7B%7Bcontext.GOARCH%7D%7D%20%7B%7Bcontext.Compiler%7D%7D%20--%20unsafe%5D: unsupported file extension: .Compiler}} -- unsafe]
[Error - 10:03:06 PM] unable to check package for file:///Users/V/Projects/redacted.go: go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]: exit status 1: build cache is required, but could not be located: GOCACHE is not defined and $HOME is not defined

[Error - 10:03:06 PM] Request textDocument/codeAction failed.
  Message: no file information for file:///Users/V/Projects/redacted.go
  Code: 0 
[Error - 10:03:06 PM] unable to check package for file:///Users/V/Projects/redacted.go: go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]: exit status 1: build cache is required, but could not be located: GOCACHE is not defined and $HOME is not defined

[Error - 10:03:06 PM] Request textDocument/documentLink failed.
  Message: no AST for file:///Users/V/Projects/redacted.go
  Code: 0 
[Error - 10:03:06 PM] unable to check package for file:///Users/V/Projects/redacted.go: go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]: exit status 1: build cache is required, but could not be located: GOCACHE is not defined and $HOME is not defined

[Error - 10:03:06 PM] Request textDocument/hover failed.
  Message: no AST for file:///Users/V/Projects/redacted.go
  Code: 0 
```

**Comment by stamblerre** [comment] 2019-05-28 21:57
Thank you for sharing! I was actually just able to reproduce this error, so I will be investigating it ASAP.

**Comment by stamblerre** [comment] 2019-05-29 01:05
This should be fixed with https://golang.org/cl/179221.

**Closed by stamblerre** 2019-05-29 01:05 UTC
Labels: NeedsInvestigation, gopls
