### ISSUE TITLE
runtime/race: setting cap_net_bind_service or cap_net_raw capabilities disables halt_on_error

### ISSUE THREAD

**Issue by ainar-g** [golang/go#59434] opened 2023-04-04 16:58 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ainar/.cache/go-build"
GOENV="/home/ainar/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ainar/go/pkg/mod"
GONOPROXY="REMOVED"
GONOSUMDB="REMOVED"
GOOS="linux"
GOPATH="/home/ainar/go"
GOPRIVATE="REMOVED"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/ainar/go/go1.20"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/ainar/go/go1.20/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/home/ainar/dev/tmp/go/tmp/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2426973317=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	for i := 0; i < 100; i++ {
		go f(&i)
	}

	time.Sleep(1 * time.Second)

	fmt.Println("the end")
}

func f(p *int) {
	fmt.Println(*p)
}
```

```sh
GORACE='atexit_sleep_ms=0 halt_on_error=1'
export GORACE

go build --race -o tmp_with_setcap
sudo setcap 'cap_net_bind_service+ep' ./tmp_with_setcap
./tmp_with_setcap

go build --race -o tmp_no_setcap
./tmp_no_setcap
```

### What did you expect to see?

Neither of these two reaching `the end`.

### What did you see instead?

The last one correctly terminates; the one with `setcap` doesn't and reaches `the end`.

**Comment by ianlancetaylor** [comment] 2023-04-04 19:32
CC @dvyukov

**Comment by dvyukov** [comment] 2023-04-05 07:24
The issues is much wider. I've filed https://github.com/google/sanitizers/issues/1640. Let's move the discussion there.

**Comment by mknyszek** [comment] 2023-04-05 19:17
In triage now, we're thinking we'll close it for now as a duplicate of https://github.com/google/sanitizers/issues/1640. Feel free to reopen if that's not the case. Thanks.

**Closed by mknyszek** 2023-04-05 19:17 UTC
Labels: RaceDetector, NeedsInvestigation, compiler/runtime
