### ISSUE TITLE
affected/package:  sort

### ISSUE THREAD

**Issue by jason-costello** [golang/go#54652] opened 2022-08-24 16:26 UTC
### What version of Go are you using (`go version`)?
1.19
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jcostello/Library/Caches/go-build"
GOENV="/Users/jcostello/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jcostello/go/pkg/mod"
GONOPROXY="github.com/GannettDigital/*"
GONOSUMDB="github.com/GannettDigital/*"
GOOS="darwin"
GOPATH="/Users/jcostello/go"
GOPRIVATE="github.com/GannettDigital/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.19/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.19/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jcostello/go/src/github.com/GannettDigital/XXXXXX/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?

With no change in code, the output between the two versions is different.

1.18:   https://go.dev/play/p/K5yqRlREPSM?v=goprev
1.19:   https://go.dev/play/p/K5yqRlREPSM

### What did you expect to see?
sort.Slice() producing the same output regardless of version.

### What did you see instead?
sort.Slice() producing  output in `1.19` that is in a different order than the output generated by sort.Slice() in `1.18`.

**Comment by seankhliao** [comment] 2022-08-24 16:56
Your comparison function doesn't satisfy the requirements for total ordering.

In any case, Sort makes no guarantee of stability, within or between versions.
As long as the final output is a sorted order, it is considered correct.

Closing as not a bug

**Closed by seankhliao** 2022-08-24 16:56 UTC

**Comment by ianlancetaylor** [comment] 2022-08-24 19:45
Note that the 1.19 release notes mention that the sort algorithm was rewritten.
