### ISSUE TITLE
cmd/go: regression compiling "const X = string(rune(31))"

### ISSUE THREAD

**Issue by mark-rushakoff** [golang/go#34563] opened 2019-09-26 23:10 UTC
Given this file:

```go
package stringrune

const X = string(rune(31))
```

It compiled successfully with `go build` on go 1.12, but at tip it failed with:

```
const initializer string(rune(31)) is not a constant
```

So I used git bisect to determine that 581526ce963f54b01eef95d2a76ecb6fc08ed91c (cmd/compile: rewrite untyped constant conversion logic) was the Go commit where it stopped compiling.

I skimmed through the spec and I wasn't able to quickly determine whether the current or previous behavior was conformant.

This particular line exists in the wild, in influxdb: https://github.com/influxdata/influxdb/blob/99ef5fb3e44400bcc49383035ab7c81bd7be4979/services/continuous_querier/service.go#L28. I have no context on why it was written like that instead of a string literal `"\x1f"`.

/cc @mdempsky @griesemer

**Comment by griesemer** [comment] 2019-09-26 23:19
Probably a simple oversight. Assigning to @mdempsky as he's recently changed this code. Release blocker because it's a regression.

**Comment by mdempsky** [comment] 2019-09-26 23:54
The issue is evconst wasn't performing constant folding for integer->string conversions.

This used to not be a problem because convertlit1 would internally handle constant folding for explicit conversions, but 581526c changed convertlit1 to short-circuit if the operand is already typed, expecting that evconst would handle this instead.

**Comment by mdempsky** [comment] 2019-09-26 23:54
Fixed. Thanks for the report!

**Closed** 2019-09-26 23:55 UTC
Labels: release-blocker

**Comment by av86743** [comment] 2019-09-27 06:34
@mdempsky

Notice that [your test](https://go-review.googlesource.com/c/go/+/197677/2/test/const.go) does not actually validate against original problem (constant initializer not recognized as a constant.)

**Comment by mdempsky** [comment] 2019-09-27 06:59
@av86743 What do you mean? I added two new (blank) constant declarations.

Did you maybe miss the `const` keyword on line 13? Or am I missing something?

**Comment by av86743** [comment] 2019-09-27 07:28
@mdempsky My mistake. Apologies.

**Comment by mdempsky** [comment] 2019-09-27 08:08
@av86743 No problem. Thanks for confirming. :)
