### ISSUE TITLE
Solution to the problem of restful 204

### ISSUE THREAD

**Issue by fabianpallares** [golang/go#16961] opened 2016-09-01 23:01 UTC
[Text translated by google]

Yesterday I made a consultation here . I asked him siquiente :

I have the following problem : I want to process a function that returns the 204 HTTP status code and function never finishes .

This resource , need absolutely return nothing in the body of the message , but return at the head need a key ( token ) .

By doing this, the service hangs .
The issue is that I have a function called " Retornar" , which resolves these issues me automatically. The function is as follows :

    // Responder el resultado de la consulta
    // Retornar el resultado restful por HTTP
    func Responder(w http.ResponseWriter, token string, respuesta interface{}) {
        estadoHttp := Estado_200_Ok // int 200

        // Verificar Si el valor a retornar es de tipo recursos.Error
        // o es de un tipo de estructura del negocio.
        err, esError := respuesta.(*Error)
        if esError {
            estadoHttp = err.EstadoHttp
        } else {
            if respuesta == nil {
                estadoHttp = Estado_204_SinContenido // 204
            }
        }

        // Si el token tiene un valor, retornarlo en el campo
        // "authorization" del Header del mensaje.
        if token != "" {
            w.Header().Set("authorization", token)
        }

        // Valores de retorno del mensaje por defecto:
        // Retorno en JSON y conjunto de caracteres UTF-8
        w.Header().Set("Content-Type", "application/json; charset=UTF-8") //***ERROR***
        w.Header().Set("Access-Control-Allow-Origin", "*")
        w.WriteHeader(estadoHttp)

        // Escribir en el body siempre y cuando no sea vacío
        if respuesta != nil {
            if err := json.NewEncoder(w).Encode(respuesta); err != nil {
                panic(err)
            }
        }
    }

I thank the people who answered me , but I did not solve the problem , the appeal was hanged.
The solution is very simple, remove the line (for error is processed ) :

    w.Header().Set("Content-Type", "application/json; charset=UTF-8")

Since " Content- Type" refers to the message body . Consequently , the service was frozen !

Conclusion : If you want to return a status code 204 ( cin content in the body ) but containing fields in the header , as in the case of "Authorization " , never place :

    w.Header().Set("Content-Type", "application/json; charset=UTF-8")

### What version of Go are you using (`go version`)?
1.6.3

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Solutionated

### What did you see instead?
Solutionated

**Comment by bradfitz** [comment] 2016-09-02 00:19
Same issue from @fabianpallares in a different form: #16941

I still don't see the problem. I don't see the Handler get frozen. This code does your "***ERRROR***" line and sends a 204, but doesn't freeze:

https://play.golang.org/p/Awlpdc9DOo

I think you'll need to provide a complete demo showing the problem, not just a snippet of code. I see that https://plus.google.com/communities/105964860738231827761 was a recommended Spanish forum in the other bug. Perhaps that community can work with you to create a stand-alone reproduction case and then a new bug can be filed if an actual bug is identified.

I'm going to close this since I don't see how to help.

**Closed by bradfitz** 2016-09-02 00:19 UTC
