### ISSUE TITLE
go.dev: Package URL for docs should end with package name

### ISSUE THREAD

**Issue by prashantv** [golang/go#40550] opened 2020-08-03 16:01 UTC
This is a UX issue related to how pkg.go.dev works as compared to godoc.org. Here are the API documentation URLs for the zap package,
 * godoc: https://godoc.org/go.uber.org/zap
 * pkg.go.dev: https://pkg.go.dev/go.uber.org/zap?tab=doc

If I delete the `?tab=doc`, it will end up redirecting with the URL parameter added.

Often, a user may want to navigate the package structure using the URL, e.g., Modifying `/zap` to `/zap/zaptest`. To do this with godoc, it was easy as the package name was the last element. With pkg.go.dev, it requires scanning (or deleting) `?tab=doc` before being able to make the modification, making the experience more painful.

Since the default go `pkg.go.dev/<package>` is the documentation page, can we also avoid adding the `?tab=doc` suffix to the URL?

**Comment by mvdan** [comment] 2020-08-03 16:43
I personally agree, but this is a duplicate of https://github.com/golang/go/issues/37351, which already has had some activity :) You can give your thumbs up there.

**Closed by mvdan** 2020-08-03 16:43 UTC
Labels: Documentation, go.dev
