### ISSUE TITLE
proposal: time.ParseDuration(): add time unit for days e.g. `d`

### ISSUE THREAD

**Issue by amurchick** [golang/go#51751] opened 2022-03-17 11:05 UTC
## What
On this moment valid time units in `time.ParseDuration()` are "ns", "us" (or "µs"), "ms", "s", "m", "h".

But sometimes you need to specify duration in days.

## Why
Often in config files (for example `yaml`) definition of time intervals is used.

Sometimes such intervals go beyond the border of the day (24h).

Please agree that this:
```yaml
dbMaxAge: 31d
```

is much more human-readable than:
```yaml
dbMaxAge: 744h
```

**Comment by seankhliao** [comment] 2022-03-17 11:24
Duplicate of #51010

**Closed by seankhliao** 2022-03-17 11:24 UTC
Labels: Proposal
