### ISSUE TITLE
cmd/go: Build fails when build with -trimpath due to lack of gcc

### ISSUE THREAD

**Issue by narqo** [golang/go#37158] opened 2020-02-10 19:10 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, in both 1.13 and 1.14rc1

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build998143923=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

When one builds a Go binary inside Docker container (`golang:1.13.7-alpine3.10`) adding `-trimpath` to the build command, fails the build if a C compiler wasn't pre-installed.

Dockerfile:

```
FROM golang:1.13.7-alpine3.10
ENV GO111MODULE=off
COPY . /go/src/github.com/<goproject>
WORKDIR /go/src/github.com/<goproject>
RUN go build -trimpath -o gobin ./<main.go>
```

The same code, with the same docker image, but w/o `-trimpath` builds successfully.

### What did you expect to see?
Expected, that `go build -trimpath` will have the same behaviour as one with no flag.

### What did you see instead?
Build fails, requiring gcc.

```
# runtime/cgo
exec: "gcc": executable file not found in $PATH
```

As was pointed out by @ianlancetaylor for a similar question on go-nuts [1], this is (likely) due to `runtime/cgo` needs to be rebuilt in order to trim the paths.

I believe, there isn't any documentation or a note, describing this, so the change in go build's behaviour is surprising for a user.

[1]: https://groups.google.com/d/msg/golang-nuts/dsqLZi2mEog/8pcaXIrABAAJ

**Comment by bcmills** [comment] 2020-02-10 20:32
> Expected, that `go build -trimpath` will have the same behaviour as one with no flag.

If the behavior were _exactly_ the same, then there would be no need for the flag. 😅

----

I think the issue you are describing boils down to: _the Go release should ship with a standard library built with `-trimpath`_.

I don't know how feasible that is, but I suspect that it is tantamount to saying that _the `-trimpath` flag should be enabled by default:_ otherwise, users who invoke `go build` without `-trimpath` would run into the same problem that you are running into _with_ `-trimpath`.

(I think I actually agree that `-trimpath` should be the default, but it's not a trivial change, and should probably have a separate proposal. See also #24904.)

CC @jayconrod @matloob @cagedmantis @toothrot @dmitshur

**Comment by jayconrod** [comment] 2020-02-10 20:32
Related #33840, #27303, #26988.

**Comment by seankhliao** [comment] 2024-12-03 18:55
Duplicate of #47257

**Closed by seankhliao** 2024-12-03 18:55 UTC
Labels: NeedsInvestigation, FrozenDueToAge
