### ISSUE TITLE
cmd/go: buld -ldflags -X does not work if a package path ends with "/"

### ISSUE THREAD

**Issue by rockmenjack** [golang/go#24469] opened 2018-03-21 08:07 UTC
### What version of Go are you using (`go version`)?
go version go1.10 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

### What did you do?
create a very simple pakcage, try to append version number during compile time

src/dummy/main.go
```go
package main

import "fmt"

var (
	version = "NONE"
)

func main() {
	fmt.Printf("Version is %s\n", version)
}
```

### What did you expect to see?
since below command will run without any error:
`go build -o bin/dummy -ldflags "-X main.version=1" dummy/` <- with / 
it shall produce the same binary as by:
`go build -o bin/dummy -ldflags "-X main.version=1" dummy`  <- without /

### What did you see instead?
The "with /" case, version is not set by `-ldflags "-X main.version=1"`

**Comment by 0xmohit** [comment] 2018-03-21 17:54
This appears to be the same issue as reported in #24456.

**Comment by andybons** [comment] 2018-03-21 23:13
Duplicate of #24456

**Closed by andybons** 2018-03-21 23:13 UTC
