### ISSUE TITLE
cmd/go: go build doesn't build module if name is used by standard library and stops without warning/error.

### ISSUE THREAD

**Issue by Omkar76** [golang/go#42721] opened 2020-11-19 10:09 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes, with go1.15.3

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/onkar/.cache/go-build"
GOENV="/home/onkar/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/onkar/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/onkar/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/mnt/data/go/logging/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build208606108=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I created a new `go.mod` file by running ` go mod init log`. here `log` is module name.
then after writing some code in main package, I tried to build by executing `go build` at root of my module.
That did nothing. No binary was built. After searching on internet for a while I found that module names without a dot in first component are reserved for standard library.

### What did you expect to see?
I expected a warning message saying that 'log' is name of a standard library module and should not be used 
Or
warning message like - module names should contain dot in first component.

### What did you see instead?
The go build stopped without building module with no error / warnings.

**Comment by bcmills** [comment] 2020-11-19 14:43
Duplicate of #39285

**Closed by bcmills** 2020-11-19 14:43 UTC
