### ISSUE TITLE
strings.Split an empty string should get a zero length slice, but the return slice's len is 1

### ISSUE THREAD

**Issue by widon1104** [golang/go#35130] opened 2019-10-24 08:59 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
widon@widon-PC:~$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/widon/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/widon/go"
GOPROXY=""
GORACE=""
GOROOT="/home/widon/soft/golang/go"
GOTMPDIR=""
GOTOOLDIR="/home/widon/soft/golang/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build437062802=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
2 lines of code:

**ret := strings.Split("", " ")   
fmt.Println(len(ret), ret)**

run this code get:
`1 []`

### What did you expect to see?
strings.Split an empty string should get a zero length slice

### What did you see instead?
the return slice's len is 1

**Comment by ALTree** [comment] 2019-10-24 09:21
Thanks for the report. This is working as documented. 

The doc for `Split` says:

> If s does not contain sep and sep is not empty, Split returns a slice of length 1 whose only element is s. 

Since `s` (in your case, `""`) does not contain `sep` (in your case, `" "`), the returned slice has length 1 and it has `s` (i.e.,  `""`), inside.

Closing here, since this is working as intended.

**Closed by ALTree** 2019-10-24 09:21 UTC
