### ISSUE TITLE
way to recursively include all files in embed

### ISSUE THREAD

**Issue by quinn-freshly** [golang/go#46360] opened 2021-05-25 04:33 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
//go:embed dir/*
//go:embed dir/**

### What did you expect to see?
all files included. 

### What did you see instead?
most files are included, except for deeply nested files with an underscore at the beginning of the filename.

**Comment by seankhliao** [comment] 2021-05-25 06:46
Duplicate of #43854

**Closed by seankhliao** 2021-05-25 06:46 UTC
