### ISSUE TITLE
go/doc/comment: Unrendered link syntax in Printer.DocLinkBaseURL doc

### ISSUE THREAD

**Issue by willfaught** [golang/go#61241] opened 2023-07-09 05:54 UTC
Expected:

```go
type Printer struct {
...
	// DocLinkBaseURL is used when DocLinkURL is nil,
	// passed to DocLink.DefaultURL to construct a DocLink's URL.
	// See that method's documentation for details.
	DocLinkBaseURL [string](https://pkg.go.dev/builtin#string)
```

(with "DocLink.DefaultURL" being a hyperlink on web, and plain text in terminal)

Actual:

```go
type Printer struct {
...
	// DocLinkBaseURL is used when DocLinkURL is nil,
	// passed to [DocLink.DefaultURL] to construct a DocLink's URL.
	// See that method's documentation for details.
	DocLinkBaseURL [string](https://pkg.go.dev/builtin#string)
```

See https://pkg.go.dev/go/doc/comment#Printer.

**Comment by seankhliao** [comment] 2023-07-09 07:42
Duplicate of #39963

**Closed by seankhliao** 2023-07-09 07:42 UTC
