### ISSUE TITLE
cmd/compile: different results from runtime.Caller

### ISSUE THREAD

**Issue by spirin** [golang/go#67668] opened 2024-05-27 19:45 UTC
### Go version

go1.21.3

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/username/Library/Caches/go-build'
GOENV='/Users/username/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/username/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/username/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.3'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/username/project/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/_t/33qxzy9s2kq868ctfg5yxws00000gn/T/go-build196945374=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

Short example for playground:

```go
package main

import (
	"errors"
	"fmt"
	"runtime"
)

func Wrap(err error) error {
	pc, _, _, ok := runtime.Caller(1)
	details := runtime.FuncForPC(pc)
	if ok && details != nil {
		return fmt.Errorf("%s: %w", details.Name(), err)
	}
	return err
}

var errTest = errors.New("test")

type testObj struct{}

func (testObj) Fn1() error {
	return func() error {
		return Wrap(errTest)
	}()
}

func (testObj) Fn2() error {
	return func() error {
		return Wrap(errors.New("test"))
	}()
}

func main() {
	obj := testObj{}
	fmt.Println(obj.Fn1())
	fmt.Println(obj.Fn2())
}
```

### What did you see happen?

different results:

```
main.main.testObj.Fn1.func1: test
main.testObj.Fn2.func1: test
```

### What did you expect to see?

same results

**Comment by spirin** [comment] 2024-05-27 19:52
go playground https://go.dev/play/p/NtxAspZ03df

**Comment by ianlancetaylor** [comment] 2024-05-27 20:27
CC @golang/compiler

**Comment by go101** [comment] 2024-05-28 16:22
Looks relating to inline, with the `//go:noinline` directive for `Fn1`, the outputs are the same.

```Go
//go:noinline
func (testObj) Fn1() error {
	return func() error {
		return Wrap(errTest)
	}()
}

func (testObj) Fn2() error {
	return func() error {
		return Wrap(errors.New("test"))
	}()
}
````

**Comment by dr2chase** [comment] 2024-05-28 19:18
This looks like a duplicate of #60324.

**Comment by mknyszek** [comment] 2024-05-29 20:44
Closing as duplicate of #60324.

**Closed by mknyszek** 2024-05-29 20:44 UTC
Labels: compiler/runtime
