### ISSUE TITLE
database/sql: sqlboiler-using project fails with cancellation errors after context/RawBytes CL when many tests run

### ISSUE THREAD

**Issue by zikaeroh** [golang/go#60932] opened 2023-06-22 00:35 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.21-b1f1fb2950 Wed Jun 21 18:32:13 2023 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

On tip.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/zikaeroh/.cache/go-build'
GOENV='/home/zikaeroh/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/zikaeroh/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/zikaeroh/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/zikaeroh/sdk/gotip'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/home/zikaeroh/sdk/gotip/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='devel go1.21-b1f1fb2950 Wed Jun 21 18:32:13 2023 +0000'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/zikaeroh/hortbot/hortbot/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1489328331=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

I really have to apologize, I don't yet have a reproduction that's more minimal than my actual project. Testing this "only" requires `docker` running locally.

- https://github.com/hortbot/hortbot
- `go test ./internal/bot`

### What did you expect to see?

Tests pass.

### What did you see instead?

After [CL 497675](https://go.dev/cl/497675) (I bisected to be sure), my tests appear to fail, with sqlboiler calls returning errors that mention context cancellation. Something like:

```
context canceled
error from rows in bind
github.com/volatiletech/sqlboiler/v4/queries.(*Query).Bind
	/home/zikaeroh/go/pkg/mod/github.com/volatiletech/sqlboiler/v4@v4.14.2/queries/reflect.go:154
github.com/hortbot/hortbot/internal/bot.handleSession
	/home/zikaeroh/hortbot/hortbot/internal/bot/handle.go:367
github.com/hortbot/hortbot/internal/bot.(*Bot).handlePrivMsg.func1
	/home/zikaeroh/hortbot/hortbot/internal/bot/handle.go:166
github.com/hortbot/hortbot/internal/pkg/dbx.Transact.func2
	/home/zikaeroh/hortbot/hortbot/internal/pkg/dbx/dbx.go:58
github.com/hortbot/hortbot/internal/pkg/dbx.Transact
	/home/zikaeroh/hortbot/hortbot/internal/pkg/dbx/dbx.go:63
github.com/hortbot/hortbot/internal/bot.(*Bot).handlePrivMsg
	/home/zikaeroh/hortbot/hortbot/internal/bot/handle.go:160
github.com/hortbot/hortbot/internal/bot.(*Bot).handle
	/home/zikaeroh/hortbot/hortbot/internal/bot/handle.go:103
github.com/hortbot/hortbot/internal/bot.(*Bot).Handle
	/home/zikaeroh/hortbot/hortbot/internal/bot/handle.go:70
github.com/hortbot/hortbot/internal/bot/btest.(*scriptTester).handle.(*scriptTester).handleM.func3
	/home/zikaeroh/hortbot/hortbot/internal/bot/btest/irc.go:57
github.com/hortbot/hortbot/internal/bot/btest.(*scriptTester).test
	/home/zikaeroh/hortbot/hortbot/internal/bot/btest/script_tester.go:207
github.com/hortbot/hortbot/internal/bot/btest.RunScript
	/home/zikaeroh/hortbot/hortbot/internal/bot/btest/script_tester.go:49
github.com/hortbot/hortbot/internal/bot_test.TestScripts.func1
	/home/zikaeroh/hortbot/hortbot/internal/bot/script_test.go:43
testing.tRunner
	/home/zikaeroh/go/src/testing/testing.go:1595
runtime.goexit
	/home/zikaeroh/go/src/runtime/asm_amd64.s:1650
```

It's not one specific test either; it only happens when I run enough tests, e.g. run the whole thing. E.g., `go test -run "TestScripts/quotes/add" ./internal/bot` will pass, but `gotip test ./internal/bot` will fail. `TestScripts/quotes` _sometimes_ fails.

I have tested with `-race` and don't see any races reported. Passing `-parallel 1` also does not change things. I have also changed my postgres driver to another one, and see the same behavior.

Again, apologies for such a big repro; I'm not quite sure where to start minimizing this.

cc @bradfitz 

ref #60304 #53970

**Comment by dmitshur** [comment] 2023-06-22 14:56
Also CC @kardianos, @kevinburke via [owners](https://dev.golang.org/owners).

**Comment by dmitshur** [comment] 2023-06-22 14:58
Tentatively marking as a release-blocker since this is caused by a CL new in Go 1.21, and needs investigation. The release-blocker label can be removed if investigation shows this doesn't need to block the release.

**Comment by zikaeroh** [comment] 2023-06-22 19:22
Some further investigation:

If I wholesale replace my context with `context.Background()`, the errors don't happen. This to me implies that the libraries I'm calling are not introducing their own cancel/deadline/timeout. However, this is confusing because when I use my typical context, `ctx.Err()` before and after a failing query are both `nil`, so my context can't have been cancelled.

**Comment by zikaeroh** [comment] 2023-06-22 19:44
Hm, so I have a theory (which I need to test):

- sqlboiler's `queries.Bind` function makes a query: https://github.com/volatiletech/sqlboiler/blob/4dd76363f68e73f9bd52ca984446db69a2282981/queries/reflect.go#L136
- At some point `(*Rows).awaitDone` is run; this is run via `go rs.awaitDone()`, so it's sitting there waiting for the context(s) to stop.
- The rows are read out successfully by `Bind`.
- `Bind` closes the rows. This calls `rs.cancel`
- Now, that `awaitDone` goroutine may wake up because one of the contexts it's waiting on was cancelled.
- `Bind` checks `rows.Err`, and depending on whether or not `awaitDone` set an error, this function returns a spurious cancellation error.

**Comment by zikaeroh** [comment] 2023-06-22 22:25
Yeah, I think that the above is correct; I modified `database/sql` to check what was happening and it's the error from `rs.contextDone`. I also noted that the docs say:

```
// Close closes the Rows, preventing further enumeration. If Next is called
// and returns false and there are no further result sets,
// the Rows are closed automatically and it will suffice to check the
// result of Err. Close is idempotent and does not affect the result of Err.

// Err returns the error, if any, that was encountered during iteration.
// Err may be called after an explicit or implicit Close.
```

Which implies that close should not be affecting `Err` at all, though that is unfortunately what the CL ended up doing.

I'm not totally sure if `rs.cancel`'s eventual error is intended to be propagated outward; if the intent is just to ensure that the `awaitDone` goroutine exits, maybe the "right" thing to do is to pass in a third context to `awaitDone` solely for that purpose which doesn't set `rs.contextDone`.

Testing out that fix locally does the trick, fixing my repro and still passing the existing `database/sql` tests.

**Comment by zikaeroh** [comment] 2023-06-23 00:25
I have mailed a CL which I believe fixes the issue. Happy to take feedback or have my CL superceded by a better one!

**Comment by cagedmantis** [comment] 2023-06-28 16:27
This has a CL and needs a review? This is a release blocker.

/cc @bradfitz @rsc

**Closed** 2023-07-05 17:12 UTC
Labels: NeedsFix, release-blocker
