### ISSUE TITLE
x/tools/gopls: import diagnostic range breaks on dashes

### ISSUE THREAD

**Issue by muirdm** [golang/go#40466] opened 2020-07-29 05:06 UTC
Import diagnostics have the wrong range for package paths that contain dashes:

![Screen Shot 2020-07-28 at 10 05 02 PM](https://user-images.githubusercontent.com/11356572/88758884-66ac1880-d11e-11ea-83e2-3cfacb3aa061.png)

```
[Trace - 10:04:54 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
  "diagnostics": [
    {
      "message": "\"github.com/go-playground/locales/en_US\" imported but not used",
      "source": "compiler",
      "severity": 1,
      "range": {
        "end": {
          "character": 21,
          "line": 2
        },
        "start": {
          "character": 7,
          "line": 2
        }
      }
    }
  ],
  "version": 531,
  "uri": "file:///Users/muir/scratch/foo/foo.go"
}
```

**Comment by stamblerre** [comment] 2020-07-29 05:27
Thanks for the report! Duplicate of https://github.com/golang/go/issues/37936, I'm afraid.

**Closed by stamblerre** 2020-07-29 05:27 UTC
Labels: Tools, gopls
