### ISSUE TITLE
x/website:build fail  macos12.0

### ISSUE THREAD

**Issue by j2501987804** [golang/go#47614] opened 2021-08-10 10:08 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/41771911/128848878-ca549ba4-ddbc-46d2-ad31-bd3dc23c061c.png">

**Comment by seankhliao** [comment] 2021-08-10 10:30
Duplicate of #47269

**Closed by seankhliao** 2021-08-10 10:30 UTC
