### ISSUE TITLE
x/pkgsite: cs.opensource.google gives "permission denied"

### ISSUE THREAD

**Issue by xubiod** [golang/go#56171] opened 2022-10-12 02:32 UTC
### What is the URL of the page with the issue?
 
 Any page of the standard library's documentation. Just for an example here though I will use https://pkg.go.dev/fmt#section-sourcefiles
 
### What is your user agent?
 

 
 `[Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)`
 
### Screenshot
 

 
![image](https://user-images.githubusercontent.com/7144210/195234982-2b21698a-5d30-47a6-80ac-51accd31bb48.png)

 
### What did you do?
 

 
 Clicking on any source file, in the instance of the screenshot I clicked on `format.go`.
 
### What did you expect to see?
 
 The source file of `format.go`.
 
### What did you see instead?

An error from cs.opensource.google.

### The fix

After doing my own investigation, I figured out that linking to cs.opensource.google/go is indeed not correct anymore (in fact, even the root of cs.opensource.google does not load anything). It should now point to [go.googlesource.com/go](https://go.googlesource.com/go) to link to the standard library source.

**Comment by mvdan** [comment] 2022-10-12 09:48
Perhaps this was a temporary error. https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/fmt/doc.go works fine for me, for example.

**Comment by mvdan** [comment] 2022-10-12 13:23
That's very weird. cc @golang/pkgsite to see who could help on the infra side.

**Comment by jamalc** [comment] 2022-10-12 14:22
Similar reports in #47213, #48956, and #53006. Have you tried loading the page with extensions disabled?

**Comment by xubiod** [comment] 2022-10-12 14:39
I can access it on my iPhone without issue; as right now I cannot access my regular computer. I still find it strange that the link I provided in the ticket (go.googlesource.com) works regardless however.

**Comment by xubiod** [comment] 2022-10-12 19:51
Without extensions it loads fine, but in my opinion it's still somewhat of an issue and inconvenient to specifically go that route.

**Comment by seankhliao** [comment] 2022-10-12 20:00
Duplicate of ##47213

**Closed by seankhliao** 2022-10-12 20:00 UTC
Labels: WaitingForInfo, pkgsite

**Comment by tarndt** [comment] 2022-11-05 03:57
I ran into this same problem and had to disable the "DuckDuckGo Privacy Essentials extension" for this page to work (which probably means its doing something it shouldn't be).

**Comment by chmike** [comment] 2023-09-20 18:49
I have the same issue since a long time now. Since I stumbled on it again today, I displayed the javascript console and see this error:

```
Error: Kc`/v1/landingPages/current`{"error":{"code":403,"message":"Requests from referer https://grimoireoss-pa.clients6.google.com/batch?%24ct=multipart%2Fmixed%3B%20boundary%3Dbatch276518100238619142 are blocked.","status":"PERMISSION_DENIED","details":[{"@type":"[type.googleapis.com/google.rpc.ErrorInfo](chrome://devtools/content/webconsole/type.googleapis.com/google.rpc.ErrorInfo)","reason":"API_KEY_HTTP_REFERRER_BLOCKED","domain":"googleapis.com","metadata":{"service":"grimoireoss-pa.googleapis.com","consumer":"projects/102538029536"}}]}}
```
This problem was fixed by disabling the Smart Referer extension module for Firefox. The extension removes the referrer link in request headers. It is possible in theory to add whitelist entries, but it doesn't seam to work. It's not clear why. I assume, it expect a .com domain name. 

There is also a CORS issue, but the error message is in French:

```
Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://play.google.com/log?authuser=0. Raison : échec de la requête CORS. Code d’état : (null)
```
