### ISSUE TITLE
encoding/csv: leading byte order mark

### ISSUE THREAD

**Issue by Sggoodman** [golang/go#48270] opened 2021-09-09 06:28 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.7 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=D:\EnvScience\go\bin
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\EnvScience\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\EnvScience\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\SoftWare\GO1.16.7
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\SoftWare\GO1.16.7\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.7
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\WorkSpace\zaoan\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build3887569683=/tmp/go
-build -gno-record-gcc-switches

</pre></details>

### What did you do?

I read a CSV file and take the first item of the returned value after reading. The value obtained from the first item in the string array is printed with a space in front, but there is no space in the CSV file and there is only one item in the array, so I need string cutting to get my actual data

### What did you expect to see?

What I want to get should be specific and actual data, rather than adding a space in front, which leads to the wrong result when I judge by length, but the string array obtained by readall is correct, and what my compiler sees in debugging is also free of spaces, which makes me feel strange. Then I print the read value with spaces, But I use readall to traverse the printed value without spaces.

### What did you see instead?

read遍历的结果 和 readall遍历得到的数组内容不一致

**Comment by Sggoodman** [comment] 2021-09-09 08:57
I found that there is only a length problem in the first line, just like a Chinese space character

**Comment by Sggoodman** [comment] 2021-09-09 08:58
Both read and readall will lead to this result, so I can only give up the first row of data

**Comment by helbing** [comment] 2021-09-09 09:08
You may need to provide test cases and test data.

**Comment by thanm** [comment] 2021-09-09 17:18
As @helbing mentioned, it would be great if you could attach a test case and test data that will reproduce the problem. Thanks.

**Comment by Sggoodman** [comment] 2021-09-10 03:26
![image](https://user-images.githubusercontent.com/52983084/132794725-d1e9e1f0-f0dd-41b7-b21d-496c740230f8.png)

**Comment by Sggoodman** [comment] 2021-09-10 03:27
Shouldn't it be the same, and the length should be 6?

**Comment by Sggoodman** [comment] 2021-09-10 03:30
I found that sometimes he had problems, sometimes he didn't have problems

The most likely problem is to create a new EXCEL and then add data. After saving as CSV, the program will get the results shown in the figure above

**Comment by seankhliao** [comment] 2021-09-10 05:30
Please upload a copy of your csv
also, screen are hard to read

**Comment by helbing** [comment] 2021-09-10 05:30
This may be a problem of [BOM](https://en.wikipedia.org/wiki/Byte_order_mark). When you save a file encoded in UTF-8 through Windows Notepad, it will insert three invisible characters (0xEF 0xBB 0xBF, or BOM) at the beginning of the file.

**Comment by Sggoodman** [comment] 2021-09-10 06:02
> This may be a problem of [BOM](https://en.wikipedia.org/wiki/Byte_order_mark). When you save a file encoded in UTF-8 through Windows Notepad, it will insert three invisible characters (0xEF 0xBB 0xBF, or BOM) at the beginning of the file.

That should be the case. How should I handle it properly?

**Comment by Sggoodman** [comment] 2021-09-10 06:05
> Please upload a copy of your csv
> also, screen are hard to read

Thank you very much. I'll find a way to deal with it myself


> This may be a problem of [BOM](https://en.wikipedia.org/wiki/Byte_order_mark). When you save a file encoded in UTF-8 through Windows Notepad, it will insert three invisible characters (0xEF 0xBB 0xBF, or BOM) at the beginning of the file.

Thank you very much. I'll find a way to deal with it myself

**Comment by seankhliao** [comment] 2021-09-10 06:15
Duplicate of #33887

**Closed by seankhliao** 2021-09-10 06:15 UTC
Labels: WaitingForInfo
