### ISSUE TITLE
affected/package: cmd/go

### ISSUE THREAD

**Issue by dustyhorizon** [golang/go#52532] opened 2022-04-24 19:49 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
</pre></details>

### What did you do?

`go list -m -json` produces invalid JSON output whilst in workspace mode.

The issue is found to be at https://github.com/golang/go/blob/96c8cc7fea94dca8c9e23d9653157e960f2ff472/src/cmd/go/internal/list/list.go#L545 where `mods` will be iterated and dumped as JSON to stdout which does not produce a properly formatted JSON object.

A potential fix would be to assemble a slice of objects before marshalling to stdout.

### What did you expect to see?

```
$ go list -m -json

{
        "Path": "github.com/x/y",
        "Main": true,
        "Dir": "/Users/kennethtan/Documents/Github/x/y,
        "GoMod": "/Users/kennethtan/Documents/Github/x/y/go.mod",
        "GoVersion": "1.18"
},
{
        "Path": "github.com/x/z",
        "Main": true,
        "Dir": "/Users/kennethtan/Documents/Github/x/z,
        "GoMod": "/Users/kennethtan/Documents/Github/x/z/go.mod",
        "GoVersion": "1.18"
}
```

### What did you see instead?

```
$ go list -m -json

{
        "Path": "github.com/x/y",
        "Main": true,
        "Dir": "/Users/kennethtan/Documents/Github/x/y,
        "GoMod": "/Users/kennethtan/Documents/Github/x/y/go.mod",
        "GoVersion": "1.18"
}
{
        "Path": "github.com/x/z",
        "Main": true,
        "Dir": "/Users/kennethtan/Documents/Github/x/z,
        "GoMod": "/Users/kennethtan/Documents/Github/x/z/go.mod",
        "GoVersion": "1.18"
}
```

**Comment by seankhliao** [comment] 2022-04-24 20:18
Duplicate of #27655

**Closed by seankhliao** 2022-04-24 20:18 UTC
