### ISSUE TITLE
the variable can't be modified in gourtine!

### ISSUE THREAD

**Issue by daysleep666** [golang/go#46947] opened 2021-06-27 14:18 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
i don't know

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mac/Library/Caches/go-build"
GOENV="/Users/mac/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Volumes/BOOTCAMP/GOPATH/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Volumes/BOOTCAMP/GOPATH"
GOPRIVATE=""
GOPROXY="http://10.80.32.177:443,https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c0/wl6bky8x3934ktlkf37vf4vw0000gn/T/go-build3603727607=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

i don't understand why the variable 'a' is always 0

<pre>
package main

import (
	"fmt"
	"time"
)

func main() {
	a := 0
	go func() {
		for {
			a++
		}
	}()
	time.Sleep(time.Second)
	fmt.Println(a)
}

</pre>

### What did you expect to see?

the variable 'a' is not zero

### What did you see instead?

ZERO!!!!ALWAYS!!!!

**Comment by daysleep666** [comment] 2021-06-27 14:21
The results of the compilation are also very strange.
Where's the compilation instruction INCQ?

<pre>
TEXT "".main(SB) gofile../Volumes/BOOTCAMP/GOPATH/src/tmp/main.go
  main.go:8		0xf81			65488b0c2500000000		MOVQ GS:0, CX		[3:3]R_USEIFACE:type.int [5:9]R_TLS_LE	
  main.go:8		0xf8a			488d4424e8			LEAQ -0x18(SP), AX	
  main.go:8		0xf8f			483b4110			CMPQ 0x10(CX), AX	
  main.go:8		0xf93			0f8656010000			JBE 0x10ef		
  main.go:8		0xf99			4881ec98000000			SUBQ $0x98, SP		
  main.go:8		0xfa0			4889ac2490000000		MOVQ BP, 0x90(SP)	
  main.go:8		0xfa8			488dac2490000000		LEAQ 0x90(SP), BP	
  main.go:9		0xfb0			488d0500000000			LEAQ 0(IP), AX		[3:7]R_PCREL:type.int	
  main.go:9		0xfb7			48890424			MOVQ AX, 0(SP)		
  main.go:9		0xfbb			e800000000			CALL 0xfc0		[1:5]R_CALL:runtime.newobject<1>	
  main.go:9		0xfc0			488b442408			MOVQ 0x8(SP), AX	
  main.go:9		0xfc5			4889442460			MOVQ AX, 0x60(SP)	
  main.go:9		0xfca			48c70000000000			MOVQ $0x0, 0(AX)	
  main.go:10		0xfd1			488d0500000000			LEAQ 0(IP), AX		[3:7]R_PCREL:type.int	
  main.go:10		0xfd8			48890424			MOVQ AX, 0(SP)		
  main.go:10		0xfdc			0f1f440000			NOPL 0(AX)(AX*1)	
  main.go:10		0xfe1			e800000000			CALL 0xfe6		[1:5]R_CALL:runtime.newobject<1>	
  main.go:10		0xfe6			488b442408			MOVQ 0x8(SP), AX	
  main.go:10		0xfeb			4889442458			MOVQ AX, 0x58(SP)	
  main.go:10		0xff0			48c70000000000			MOVQ $0x0, 0(AX)	
  main.go:11		0xff7			488b442460			MOVQ 0x60(SP), AX	
  main.go:19		0xffc			4889442448			MOVQ AX, 0x48(SP)	
  main.go:11		0x1001			488b442458			MOVQ 0x58(SP), AX	
  main.go:19		0x1006			4889442440			MOVQ AX, 0x40(SP)	
  main.go:11		0x100b			488b4c2448			MOVQ 0x48(SP), CX	
  main.go:11		0x1010			c7042410000000			MOVL $0x10, 0(SP)	
  main.go:11		0x1017			488d1500000000			LEAQ 0(IP), DX		[3:7]R_PCREL:"".main.func1·f	
  main.go:11		0x101e			4889542408			MOVQ DX, 0x8(SP)	
  main.go:11		0x1023			48894c2410			MOVQ CX, 0x10(SP)	
  main.go:11		0x1028			4889442418			MOVQ AX, 0x18(SP)	
  main.go:11		0x102d			e800000000			CALL 0x1032		[1:5]R_CALL:runtime.newproc<1>	
  main.go:20		0x1032			48c7042400ca9a3b		MOVQ $0x3b9aca00, 0(SP)	
  main.go:20		0x103a			e800000000			CALL 0x103f		[1:5]R_CALL:time.Sleep	
  main.go:21		0x103f			0f57c0				XORPS X0, X0		
  main.go:21		0x1042			0f11442468			MOVUPS X0, 0x68(SP)	
  main.go:21		0x1047			488d442468			LEAQ 0x68(SP), AX	
  main.go:21		0x104c			4889442438			MOVQ AX, 0x38(SP)	
  main.go:21		0x1051			488b442460			MOVQ 0x60(SP), AX	
  main.go:21		0x1056			488b00				MOVQ 0(AX), AX		
  main.go:21		0x1059			4889442430			MOVQ AX, 0x30(SP)	
  main.go:21		0x105e			48890424			MOVQ AX, 0(SP)		
  main.go:21		0x1062			e800000000			CALL 0x1067		[1:5]R_CALL:runtime.convT64<1>	
  main.go:21		0x1067			488b442408			MOVQ 0x8(SP), AX	
  main.go:21		0x106c			4889442450			MOVQ AX, 0x50(SP)	
  main.go:21		0x1071			488b4c2438			MOVQ 0x38(SP), CX	
  main.go:21		0x1076			8401				TESTB AL, 0(CX)		
  main.go:21		0x1078			488d1500000000			LEAQ 0(IP), DX		[3:7]R_PCREL:type.int	
  main.go:21		0x107f			488911				MOVQ DX, 0(CX)		
  main.go:21		0x1082			488d7908			LEAQ 0x8(CX), DI	
  main.go:21		0x1086			833d0000000000			CMPL $0x0, 0(IP)	[2:6]R_PCREL:runtime.writeBarrier+-1	
  main.go:21		0x108d			7402				JE 0x1091		
  main.go:21		0x108f			eb57				JMP 0x10e8		
  main.go:21		0x1091			48894108			MOVQ AX, 0x8(CX)	
  main.go:21		0x1095			eb00				JMP 0x1097		
  main.go:21		0x1097			488b442438			MOVQ 0x38(SP), AX	
  main.go:21		0x109c			8400				TESTB AL, 0(AX)		
  main.go:21		0x109e			eb00				JMP 0x10a0		
  main.go:21		0x10a0			4889442478			MOVQ AX, 0x78(SP)	
  main.go:21		0x10a5			48c784248000000001000000	MOVQ $0x1, 0x80(SP)	
  main.go:21		0x10b1			48c784248800000001000000	MOVQ $0x1, 0x88(SP)	
  main.go:21		0x10bd			48890424			MOVQ AX, 0(SP)		
  main.go:21		0x10c1			48c744240801000000		MOVQ $0x1, 0x8(SP)	
  main.go:21		0x10ca			48c744241001000000		MOVQ $0x1, 0x10(SP)	
  main.go:21		0x10d3			e800000000			CALL 0x10d8		[1:5]R_CALL:fmt.Println	
  main.go:22		0x10d8			488bac2490000000		MOVQ 0x90(SP), BP	
  main.go:22		0x10e0			4881c498000000			ADDQ $0x98, SP		
  main.go:22		0x10e7			c3				RET			
  main.go:21		0x10e8			e800000000			CALL 0x10ed		[1:5]R_CALL:runtime.gcWriteBarrier	
  main.go:21		0x10ed			eba8				JMP 0x1097		
  main.go:8		0x10ef			e800000000			CALL 0x10f4		[1:5]R_CALL:runtime.morestack_noctxt	
  main.go:8		0x10f4			e988feffff			JMP "".main(SB)		

TEXT "".main.func1(SB) gofile../Volumes/BOOTCAMP/GOPATH/src/tmp/main.go
  main.go:12		0x10f9			eb00			JMP 0x10fb		
  main.go:13		0x10fb			eb00			JMP 0x10fd		
  main.go:17		0x10fd			eb00			JMP 0x10ff		
  main.go:13		0x10ff			ebfa			JMP 0x10fb		

</pre>

**Comment by daysleep666** [comment] 2021-06-27 14:34
> ### What version of Go are you using (`go version`)?
> $ go version
> go version go1.16.5 darwin/amd64
> ### Does this issue reproduce with the latest release?
> i don't know
> 
> ### What operating system and processor architecture are you using (`go env`)?
> `go env` Output
> ### What did you do?
> i don't understand why the variable 'a' is always 0
> 
> package main
> 
> import (
> 	"fmt"
> 	"time"
> )
> 
> func main() {
> 	a := 0
> 	go func() {
> 		for {
> 			a++
> 		}
> 	}()
> 	time.Sleep(time.Second)
> 	fmt.Println(a)
> }
> 
> ### What did you expect to see?
> the variable 'a' is not zero
> 
> ### What did you see instead?
> ZERO!!!!ALWAYS!!!!

**Comment by randall77** [comment] 2021-06-27 15:00
Your program has a race in it. You're trying to communicate between two goroutines without any kind of synchronization. As a result the compiler happily optimizes away the increment.

See https://github.com/golang/go/issues/15635

Closing, this is not a bug in Go.

**Closed** 2021-06-27 15:09 UTC

**Comment by daysleep666** [comment] 2021-06-28 05:59
> Your program has a race in it. You're trying to communicate between two goroutines without any kind of synchronization. As a result the compiler happily optimizes away the increment.
> 
> See #15635
> 
> Closing, this is not a bug in Go.

thanks for your help!
