### ISSUE TITLE
net/http: NewRequestWithContext links to wrong NewRequest

### ISSUE THREAD

**Issue by bradfitz** [golang/go#70875] opened 2024-12-16 23:29 UTC
https://pkg.go.dev/net/http#NewRequestWithContext links to the wrong `NewRequest` func:

> either use the [NewRequest](https://pkg.go.dev/net/http#NewRequest) function in the net/http/httptest package

It should link to `httptest.NewRequest` instead.

/cc @neild

**Comment by seankhliao** [comment] 2024-12-17 00:21
Duplicate of #70874

**Closed by seankhliao** 2024-12-17 00:21 UTC
Labels: Documentation, FrozenDueToAge
