### ISSUE TITLE
How to use shared library which build from go build -builmode=shared -linkshared directoryname

### ISSUE THREAD

**Issue by Yadavdeepak007** [golang/go#41605] opened 2020-09-24 09:59 UTC
I created main.go , in main i called a function Sample() .
package main
func main(){
// call Sample
}
i have created Test directory in goworkspace/src .in Test i have have test.go file.
//test.go 
package Test
import "fmt"
func Sample(){
fmt.Println("call Sample function")
}
I created .so file of Test directory by using go build -builmode=shared -linkshared Test. This command create libTest.so file in goworkspace/pkg/linux_amd64_dynlink. i want to use Sample function inside the main.
how can i link this shared library with my main function and call Sample function.
 
Go version - 1.15.1 linux/amd64

**Comment by ALTree** [comment] 2020-09-24 10:09
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-09-24 10:09 UTC
