### ISSUE TITLE
cmd/compile: println(^uint(0)) fails to compile

### ISSUE THREAD

**Issue by mmacdermaid** [golang/go#21887] opened 2017-09-14 16:45 UTC
#### What did you do?
https://play.golang.org/p/bIg5Wj5I4Q

In local builds
````
println(^uint(0))
````
Is a compile error
````
constant 18446744073709551615 overflows int64
````

In local tests and builds it prints -1

````
func TestOverflow(t *testing.T) {
	asd := ^uint(0)
	println(asd)
}
````

````
go test -test.run TestOverflow
-1
````

#### What did you expect to see?
4294967295

#### What did you see instead?
-1

#### System details

```
go version go1.9 linux/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mmacdermaid/git/go"
GORACE=""
GOROOT="/home/mmacdermaid/goinstall/go"
GOTOOLDIR="/home/mmacdermaid/goinstall/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build297215887=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOROOT/bin/go version: go version go1.9 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.9
uname -sr: Linux 4.4.0-57-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.23-0ubuntu9) stable release version 2.23, by Roland McGrath et al.
gdb --version: GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
```

**Comment by ianlancetaylor** [comment] 2017-09-14 17:10
I think the problem is specific to `println(^uint(0))`.  This fails:

```
package main

func main() {
	println(^uint(0))
}
```

Replacing `println` with `fmt.Println` works fine.

**Comment by davecheney** [comment] 2017-09-14 22:08
Use fmt.Println, the built-in println is a debugging feature which has
limited ability to print complex things.

**Comment by mmacdermaid** [comment] 2017-09-15 03:50
:+1: Good to know it's just println().  I can confirm using fmt.Println() over here correctly prints the right results.

**Comment by davecheney** [comment] 2017-09-15 03:54
I'm going to close this as there doesn't seem to be an issue. `println` isn't really part of the language spec, it's just a vestigial part of the bootstrapping process. 

https://golang.org/ref/spec#Bootstrapping

**Comment by odeke-em** [comment] 2017-09-17 19:18
Reopening this as there is a proper/code fix that @anfernee has up for review.

**Closed** 2017-09-26 04:09 UTC
Labels: NeedsFix
