### ISSUE TITLE
x/tools/gopls: panic because no snapshot assigned for files

### ISSUE THREAD

**Issue by dgallion1** [golang/go#42890] opened 2020-11-30 17:11 UTC
gopls version: v0.5.3
gopls flags: -rpc.trace

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: no snapshot assigned for files [file:///C:/work1/dev/server/goMods/dirReplicator/structs.go file:///C:/work1/dev/server/goMods/pkgInterface/pkgCtx.go file:///C:/work1/dev/server/goMods/pullPrinters/jobColumns.go file:///C:/work1/dev/server/goMods/pullPrinters/machineColumns.go file:///C:/work1/dev/server/goMods/pullPrinters/modi.go file:///C:/work1/dev/server/goMods/qc/qcRec.go file:///C:/work1/dev/server/goMods/dirReplicator/replicator.go file:///C:/work1/dev/server/goMods/jobServerLib/createTestJob.go file:///C:/work1/dev/server/goMods/qc/init.go file:///C:/work1/dev/server/goMods/dirReplicator/watcher.go file:///C:/work1/dev/server/goMods/pullPrinters/genXlsx.go file:///C:/work1/dev/server/goMods/csvData/database.go file:///C:/work1/dev/server/goMods/jobServerLib/announce.go file:///C:/work1/dev/server/goMods/jobServerLib/generated.go file:///C:/work1/dev/server/goMods/jobServerLib/jobHandlers.go file:///C:/work1/dev/server/goMods/jobServerLib/models_gen.go file:///C:/work1/dev/server/goMods/jobServerLib/myResolvers.go file:///C:/work1/dev/server/goMods/jobServerLib/resolver.go file:///C:/work1/dev/server/goMods/jobServerLib/top.go file:///C:/work1/dev/server/goMods/qc/handler.go file:///C:/work1/dev/server/goMods/pullPrinters/net.go]

goroutine 3772 [running]:
golang.org/x/tools/internal/lsp.(*Server).didModifyFiles(0xc0002a4000, 0xd51880, 0xc0049d4c00, 0xc013a43500, 0x19, 0x21, 0x2, 0x0, 0x0)
	  text_synchronization.go:234  0xe8b
golang.org/x/tools/internal/lsp.(*Server).didChangeWatchedFiles(0xc0002a4000, 0xd51880, 0xc0049d4c00, 0xc001ea3160, 0x0, 0xc000db82c0)
	  text_synchronization.go:142  0x20f
golang.org/x/tools/internal/lsp.(*Server).DidChangeWatchedFiles(0xc0002a4000, 0xd51880, 0xc0049d4c00, 0xc001ea3160, 0xc001ea3160, 0x0)
	  server_gen.go:44  0x50
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xd51880, 0xc0049d4c00, 0xd66100, 0xc0002a4000, 0xc00e2fc720, 0x2bdbaff7ec0, 0xc0049d4ba0, 0x0, 0xd3f060, 0xc00151f970)
	  tsserver.go:147  0x4fa7
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xd51880, 0xc0049d4c00, 0xc00e2fc720, 0x2bdbaff7ec0, 0xc0049d4ba0, 0x47046471d, 0x11aac80)
	  protocol.go:63  0xc7
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xd51880, 0xc0049d4c00, 0xc00e2fc720, 0x2bdbaff7ec0, 0xc0049d4ba0, 0x0, 0x0)
	  lsprpc.go:559  0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xd51880, 0xc0049d4c00, 0xc0062df1a0, 0x2bdbaff7ec0, 0xc0049d4ba0, 0xc000c8cdd0, 0xd)
	  handler.go:35  0xda
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00553b6e0, 0xc0049d5680, 0xc0009260d0, 0xd51880, 0xc0049d4c00, 0xc0062df1a0, 0x2bdbaff7ec0, 0xc0049d4ba0)
	  handler.go:103  0x8d
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x179
[Error - 12:10:38 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by heschik** [comment] 2020-11-30 21:18
Staring at the code for a while, I believe this happens when `viewOf` returns a view for which `relevantChange` is false. We are then somewhat trapped: the generated file check wants a view to be assigned, but there's no new snapshot to diagnose. I'm not sure enough of the details to build a repro easily.

**Comment by stamblerre** [comment] 2020-11-30 23:50
This looks like the check later on [text_synchronization.go:234](https://github.com/golang/tools/blob/ae6603bdc3c4d025cb6c000c3b8dd778b1355266/internal/lsp/text_synchronization.go#L234), which I would've guessed would be addressed by this check in [`(*session).DidModifyFiles`](https://github.com/golang/tools/blob/ae6603bdc3c4d025cb6c000c3b8dd778b1355266/internal/lsp/cache/session.go#L446). I'll continue investigating.

**Comment by stamblerre** [comment] 2020-12-03 02:37
@dgallion1: Would you be able to share the workspace set-up that led to you encountering this issue? We have some guesses about how to mitigate the issue, but it would be best if we could reproduce it. A log would also be helpful: https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs.

**Comment by dgallion1** [comment] 2020-12-03 12:49
Added: "go.languageServerFlags": [ "-rpc.trace" ],
The original workspace is gone. I removed directories in an effort to keep gopls working.
It stops constantly throughout the day.
We use HG but the npm directories all init with GIT
Here's a workspace that's close:
{
	"folders": [
		{
			"path": "dev\\server\\goMods\\util"
		},
		{
			"path": "dev\\server\\goMods\\DMM"
		},
		{
			"path": "dev\\webServer\\npm"
		},
		{
			"path": "dev\\server\\goMods\\jobServer\\slicerQ"
		},
		{
			"path": "dev\\server\\goMods\\jobServer"
		},
		{
			"path": "dev\\server\\goMods"  <<<--- There are many go.mod directories below this.
		}
	],
	"settings": {
		"python.pythonPath": "C:\\Anaconda3\\python.exe"
	}
}

**Comment by stamblerre** [comment] 2020-12-06 01:48
Thank you for explaining the details of the workspace, but it's still difficult to reproduce the problem without a log. Would you be able to provide one if you encounter this again? (https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs)

**Comment by dgallion1** [comment] 2020-12-06 12:14
Added: "go.languageServerFlags": [ "-rpc.trace" ]
So next time I see a panic there will be logs and I'll make the effort to send them.

**Closed** 2020-12-08 23:31 UTC
Labels: Tools, WaitingForInfo, gopls
