### ISSUE TITLE
checksum mismatch for oleiade/reflections 

### ISSUE THREAD

**Issue by TisonKun** [golang/go#44454] opened 2021-02-20 14:43 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tison/Library/Caches/go-build"
GOENV="/Users/tison/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/tison/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tison/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9l/3mt1mtsj7wggzd6290w9l4bc0000gn/T/go-build3680097322=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
$ git clone --recursive https://github.com/pingcap/tidb.git  # under $GOPATH/src/github.com/pingcap
$ cd tidb
$ go mod tidy
```

### What did you expect to see?

normally get clean go mod 

### What did you see instead?

```
verifying github.com/oleiade/reflections@v1.0.0/go.mod: checksum mismatch
	downloaded: h1:rdFxbxq4QXVZWj0F+e9jqjDkc7dbp97vkRixKo2JR60=
	go.sum:     h1:RbATFBbKYkVdqmSFtx13Bb/tVhR0lgOBXunWTZKeL4w=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

SEE ALSO https://www.gitmemory.com/issue/ory/fosite/553/755224188

**Comment by seankhliao** [comment] 2021-02-20 16:51
It looks like they moved their tags https://github.com/oleiade/reflections/issues/14
the checksum error is correct.

goproxy.io appears to have cached the new version, while proxy.golang.org has the original version

Closing as it's not a bug in Go

**Closed by seankhliao** 2021-02-20 16:51 UTC
