### ISSUE TITLE
net/http: readCookies cannot parser Cookie with continuous semicolon

### ISSUE THREAD

**Issue by hidu** [golang/go#53026] opened 2022-05-23 07:16 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.17.10
</pre>

### Does this issue reproduce with the latest release?
No

All version below go1.18 can reproduce it

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
req, _ := http.NewRequest("get", "http://www.example.com/", nil)

req.Header["Cookie"] = []string{"a=va;;b=vb"}  // Cookie with continuous semicolon

fmt.Println(req.Cookie("a")) // a=va <nil>
fmt.Println(req.Cookie("b")) //  http: named cookie not present
```
https://go.dev/play/p/mAtdHmwFPtM?v=goprev

### What did you expect to see?
same as go1.18 's result:
```
a=va <nil>
b=vb <nil>
```

### What did you see instead?
```
a=va <nil>
 http: named cookie not present
```

### How to Fix
https://github.com/golang/go/blob/085c61ae517110168841be0afeb8f883d66fe95a/src/net/http/cookie.go#L259

fix it：
```go
if splitIndex := strings.Index(line, ";"); splitIndex >= 0 {
```

**Comment by seankhliao** [comment] 2022-05-23 08:28
Duplicate of #43299

**Closed by seankhliao** 2022-05-23 08:28 UTC

**Comment by hidu** [comment] 2022-05-23 08:54
@seankhliao 

in this case，go1.18 has different result with go1.17

go1.18 works fine, so go1.18 has bug?

**Comment by seankhliao** [comment] 2022-05-23 09:05
maybe, looks like the change was made switching to `strings.Cut`

cc @neild and @rsc who made the change

**Comment by hidu** [comment] 2022-05-23 11:13
The result was always changing in  different version.
 The Cookie also from Android APP, like https://github.com/golang/go/issues/39087#issuecomment-631279349
