### ISSUE TITLE
cmd/compile: unused variable is not caught if it's assigned in a function closure

### ISSUE THREAD

**Issue by songgao** [golang/go#16289] opened 2016-07-07 21:09 UTC
1. What version of Go are you using (`go version`)?

```
go version go1.6.2 linux/amd64
```

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN="/home/songgao/gopath/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/songgao/gopath"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

3. What did you do?

```
songgao at Song-ThinkPad in /tmp 
$ cat main.go
package main

func main() {
	var a int
	a = 2
}

songgao at Song-ThinkPad in /tmp 
$ go run main.go
# command-line-arguments
./main.go:4: a declared and not used

songgao at Song-ThinkPad in /tmp 
$ vim main.go

songgao at Song-ThinkPad in /tmp 
$ cat main.go
package main

func main() {
	var a int
	func() {
		a = 2
	}()
}

songgao at Song-ThinkPad in /tmp 
$ go run main.go

songgao at Song-ThinkPad in /tmp 
$ echo $?
0
```

4. What did you expect to see?

The declared but unused variable gets caught even if it's assigned in a function closure.

5. What did you see instead?

Not caught.

P.S. Interestingly, the same error was successfully caught by `:GoRename` command (which uses `gorename`) in vim.

**Comment by bradfitz** [comment] 2016-07-07 21:12
Technically this isn't a violation of the spec, which only says:

> Implementation restriction: A compiler may make it illegal to declare a variable inside a function body if the variable is never used.

But I agree it'd be nice if our various tools had consistent behavior.

**Comment by griesemer** [comment] 2016-07-07 22:31
Duplicate of #3059.

**Comment by griesemer** [comment] 2016-07-07 22:31
gorename uses go/types which correctly (in my mind) reports this as an error.

**Closed by griesemer** 2016-07-07 22:31 UTC
