### ISSUE TITLE
cmd/go: allow to specify modules to delete with 'go clean -modcache'

### ISSUE THREAD

**Issue by hyangah** [golang/go#32976] opened 2019-07-08 14:25 UTC
`go clean -modcache` causes cleaning of the entire module download cache. 

<pre>
$ go1.13beta1 help clean
...
The -modcache flag causes clean to remove the entire module
download cache, including unpacked source code of versioned
dependencies.
...
</pre>
This is useful when the module cache contains problematic modules 
(e.g. module version that is different sum hash from what sum.golang.org has, etc) .
But, redownloading everything is sometimes costly. 
It would be nice if users can have controls over what modules to delete.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.13beta1
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

linux/amd64

**Comment by seankhliao** [comment] 2022-06-15 16:53
Duplicate of #28835

**Closed by seankhliao** 2022-06-15 16:53 UTC
Labels: NeedsInvestigation, FeatureRequest, modules
