### ISSUE TITLE
proposal: encoding/json: support json path in struct tag

### ISSUE THREAD

**Issue by felipearomani** [golang/go#66116] opened 2024-03-05 14:32 UTC
### Proposal Details

Add the opportunity to use [JSON Path](https://github.com/json-path/JsonPath) syntax in the struct JSON tag.

Given the following JSON:

```json
{
  "id": 123,
  "type": "test_type",
  "company": {
    "id": 456,
    "name": "my company"
  }
}
```

If I want to unmarshal only the company data, I should create the entire struct of the message to reach the inner struct:

```go
type Message struct {
	Company struct{
		Id int `json:"id"`
		Name string `json:"name"`
	} `json:"company"`
}
```

It is boring when we have deeper nested JSONs with 2, 3, or 4 nested levels.

My propose is to allow the use `JSON Path` directly in struct tags like:

```go
type Company struct {
    ID int `json:"$.company.id"`
    Name int  `json:"$.company.name"`
}
```

It's simple, explicit and helps us not create unnecessary nested structs for complex JSONs, letting us get only the necessary information.

**Comment by seankhliao** [comment] 2024-03-05 15:32
Duplicate of #27366

**Closed by seankhliao** 2024-03-05 15:32 UTC
Labels: Proposal
