### ISSUE TITLE
cmd/compile: //go:build file version ignored when using generic function from package "slices" in Go 1.21

### ISSUE THREAD

**Issue by corhere** [golang/go#66064] opened 2024-03-01 19:19 UTC
### Go version

go version go1.21.7 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.7'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/go/src/repro/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build936666295=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

https://go.dev/play/p/-yiceeveEDz?v=goprev

<details><summary>Details</summary>
<p>

```
//go:build go1.21

package main

import "slices"

func main() {
	_ = slices.Clone([]string{})
}
-- go.mod --
module play.ground

go 1.16
```

</p>
</details> 

### What did you see happen?

Go 1.21:
```
embedding interface element ~[]string requires go1.18 or later (-lang was set to go1.16; check go.mod)

Go build failed.
```

Go 1.22:
```

Program exited.
```

### What did you expect to see?

I expect the program to type-check successfully on Go 1.21, same as it does with Go 1.22.

This issue is making it impossible to use packages in non-module repositories which use the `slices` or `maps` packages with Go modules as the synthesized go.mod file has an implied language version of go1.16.

- Likely related to https://github.com/golang/go/issues/64759

**Comment by Jorropo** [comment] 2024-03-02 05:13
Does this has anything to do with `slices` ?
I mean, in general I don't think we adapt `-lang` based on build tags.

That looks like a Go 2 proposal to me.

**Comment by go101** [comment] 2024-03-02 06:23
The priority of `//go:build` should be higher than the `go` directive in go,mod file. So both should compile and run okay.

It is true that this is a "slices" unrelated problem.

**Comment by thediveo** [comment] 2024-03-03 13:23
> That looks like a Go 2 proposal to me.

Why? I lack the insight, so please help me out. 

In any case, I've run into this because of Docker dependencies. What basically happens is that there are always non-mod indirect dependencies. If the Go 1 toolchain breaks than this is a severe issue when not being able to use the existing code.

**Comment by mknyszek** [comment] 2024-03-06 21:52
CC @bcmills and @matloob maybe?

**Comment by bcmills** [comment] 2024-03-07 22:08
This looks like a `cmd/compile` issue to me: it's not clear to me whether this is working as designed, but at the very least the error message should be clearer. The user code isn't explicitly embedding the type anywhere.

**Comment by bcmills** [comment] 2024-03-07 22:11
Actually, was respecting per-file Go versions a feature itself added in 1.22?

**Comment by mknyszek** [comment] 2024-03-07 22:22
CC @golang/compiler

**Comment by griesemer** [comment] 2024-03-08 00:10
The error is coming from the type checker. Go 1.21 did introduce the ability to upgrade the language version per file, so I would expect this to work. Investigating.

**Comment by griesemer** [comment] 2024-03-11 21:18
Related to #64759 which addressed another aspect of the same problem.

**Comment by griesemer** [comment] 2024-03-11 22:05
Analysis: During type-checking, the method
```Go
func (t *Interface) Empty() bool { return t.typeSet().IsAll() }
```
is invoked which calls `Interface.typeSet`. That function determines the type set and in order to do so, checks language version compatibility in some cases (here for the _implicitly_ embedded interface element `~[]string`). To check the version correctly, we need to know the respective file, and in order to know the file, we need to know the position of the embedding. There's no explicit position provided to the type set computation, and we don't appear to have a (stored) embedding position in this case and then the version check fails in Go 1.21. The same problem exists in Go 1.22, but the version check has changed (`Checker.allowVersion`) and in fact has a separate bug, which hides this issue in Go 1.22.

**Comment by griesemer** [comment] 2024-03-11 22:06
cc: @findleyr for visibility

**Comment by griesemer** [comment] 2024-03-12 21:15
Closing as fixed in the 1.21 branch.

**Comment by cherrymui** [comment] 2024-03-13 19:10
Reopened. CL reverted. Will re-submit later. Thanks.

**Closed** 2024-03-14 23:13 UTC
Labels: NeedsInvestigation, compiler/runtime

**Comment by cherrymui** [comment] 2024-03-15 00:19
@gopherbot please backport this to Go 1.21 release. This causes build failure for valid Go code. We'll re-apply CL 571075.

**Comment by thanm** [comment] 2024-03-26 19:19
Hi @griesemer what is the status of this bug with respect to fixes on the release branches?  Are there any CLs that need to be submitted? Saw comment by @cherrymui about how there was a revert, so wanted to check (wearing my release interrupts hat). Thanks.

**Comment by thanm** [comment] 2024-03-26 19:44
Thanks. I will look into it then...
