### ISSUE TITLE
x/tools/gopls: Cannot refer to a file with a prefix from a file without a test prefix

### ISSUE THREAD

**Issue by komem3** [golang/go#57297] opened 2022-12-14 00:53 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mikuni-k/.cache/go-build"
GOENV="/home/mikuni-k/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mikuni-k/go/pkg/mod"
GOOS="linux"
GOPATH="/home/mikuni-k/go"
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3315974857=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I created two files that a file with `_test` prefix in the package name without `_test` prefix in the extension and a file with `_test` prefix in the package name with `_test` prefix in the extension.

- sample_test.go
```go
// sample_test.go
package sample_test

import "testing"

const data = "hello world"

func TestSample(t *testing.T) {
	t.Log(helloWorld())
}
```

- sample.go
```go
// sample.go
package sample_test

const d = data // gopls reports error

func helloWorld() string {
	return d
}

```

### What did you expect to see?

Build and test succeed, but gopls reports an error referencing a test file from a test package with no test prefix in the file extension.

### What did you see instead?

The test file can be referenced from the test package even if it does not have the test prefix in the extension.

**Comment by findleyr** [comment] 2022-12-14 17:54
Hi, thank you for the issue.  I'm not sure what you mean by "Build and test succeed", because they don't succeed for me. I may be missing something.

```
> go build .
# issue.mod
./sample.go:3:11: undefined: data
> ls
go.mod  sample.go  sample_test.go
> cat sample.go
package sample_test

const d = data // gopls reports error

func helloWorld() string {
        return d
}
> cat sample_test.go
package sample_test

import "testing"

const data = "hello world"

func TestSample(t *testing.T) {
        t.Log(helloWorld())
}
```

How exactly are you running build and test?

**Comment by komem3** [comment] 2022-12-14 23:25
@findleyr 
Sorry. I didn't import this package in my environment, I was using it only for testing, so I didn't do any build.
When I tried, the build failed, but the test was successful.

should not I create test package without `_test` in the extension?

**Comment by findleyr** [comment] 2022-12-15 00:04
@komem3 yes, all test files should go a file ending in _test.go.

Closing as this is working as intended.

**Closed by findleyr** 2022-12-15 00:04 UTC
Labels: WaitingForInfo, gopls, Tools
