### ISSUE TITLE
Regression in comparing empty struct reflect value with reflect.Zero values

### ISSUE THREAD

**Issue by cezarsa** [golang/go#45129] opened 2021-03-19 15:19 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go1.16.2 version
go version go1.16.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, this looks like a regression and only happens on the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go1.16.2 env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cezarsa/Library/Caches/go-build"
GOENV="/Users/cezarsa/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/cezarsa/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/cezarsa/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/cezarsa/sdk/go1.16.2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/cezarsa/sdk/go1.16.2/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/18/22s9w_gd21979c67k0p0p7t00000gn/T/go-build1622944766=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

The code in https://play.golang.org/p/-v8S5gJncD1 prints `false` for go 1.16+ but it prints `true` for every other go version tested since 1.12.

### What did you expect to see?

Go 1.16 should also return `true` when comparing an empty struct value with a value returned from reflect.Zero() for the same struct.

### What did you see instead?

With `main.go` containing the code from the go playground linked above:

```
$ go1.16.2 run main.go
false                   # This is the problem
$ go1.15.10 run main.go
true
$ go1.14.15 run main.go
true
$ go1.13.14 run main.go
true
$ go1.12.17 run main.go
true
```

**Comment by randall77** [comment] 2021-03-19 15:25
Duplicate of #43993 ?

Kind of the opposite in behavior, but the same underlying cause (and proposed fix).

**Comment by ianlancetaylor** [comment] 2021-03-19 17:29
Closing as dup of #43993.

**Closed by ianlancetaylor** 2021-03-19 17:29 UTC
