### ISSUE TITLE
text/tabwriter: AlignRight does not pad or align right-most column

### ISSUE THREAD

**Issue by spenczar** [golang/go#14412] opened 2016-02-19 16:16 UTC
### What did you do?
I wrote a few lines to a tabwriter with AlignRight and with padding:
```
package main

import (
        "fmt"
        "os"
        "text/tabwriter"
)

func main() {
        flags := tabwriter.AlignRight | tabwriter.Debug
        w := tabwriter.NewWriter(os.Stderr, 0, 0, 1, '.', flags)
        fmt.Fprintln(w, "a\tb\tc")
        fmt.Fprintln(w, "aa\tbb\tcc")
        w.Flush()
}

```
### What did you expect to see?
All three columns aligned right, padded with the padding rune:
```
..a|..b|..c
.aa|.bb|.cc
```

### What did you see instead?
The first two columns work, but the right-most column is left aligned and without padding:
```
..a|..b|c
.aa|.bb|cc
```

Go 1.5.3 and tip (9aa630faa868fde13af74e5b22ddba89a635d837) both exhibit this on linux/amd64.

A real-world example of output that might help show what this ends up doing:
```
                         codec  bytes  encode ns  append nsdecode ns
  simpleproto.SimpleProtoCodec   1255       6596       106810584
```
Pretty hard to read that last column.

**Comment by ianlancetaylor** [comment] 2016-02-19 18:11
CC @griesemer

**Comment by griesemer** [comment] 2016-02-19 22:21
Note the documentation in the tabwriter package:

A Writer is a filter that inserts padding around tab-**delimited** columns in its input to align them in the output. (https://golang.org/pkg/text/tabwriter/)

If you **delimit** (rather than separate) the colums with tabs it does what you want:
```
package main

import (
        "fmt"
        "os"
        "text/tabwriter"
)

func main() {
        flags := tabwriter.AlignRight | tabwriter.Debug
        w := tabwriter.NewWriter(os.Stderr, 0, 0, 1, '.', flags)
        fmt.Fprintln(w, "a\tb\tc\t")     // <<<<<< delimiting tab at end
        fmt.Fprintln(w, "aa\tbb\tcc\t")  // <<<<<< delimiting tab at end
        w.Flush()
}
```
And the output is:
```
..a|..b|..c|
.aa|.bb|.cc|
```

This is working as intended. Closing.

**Closed by griesemer** 2016-02-19 22:21 UTC

**Comment by spenczar** [comment] 2016-02-22 15:47
@griesemer, thank you for clarifying. Perhaps this needs a documentation update, since the tabwriter documentation says this:

> The Writer treats incoming bytes as UTF-8 encoded text consisting of cells terminated by (horizontal or vertical) tabs or line breaks (newline or formfeed characters). Cells in adjacent lines constitute a column.

Cells can be terminated by line breaks; I'd think that the line breaks after the right-most column in my example code would have led tabwriter to interpret that last column as align-able.

Should the documentation be updated to say that the cells can only be terminated by horizontal or vertical tabs? I might still be misinterpreting.

**Comment by griesemer** [comment] 2016-02-23 18:57
@spenczar Fair enough. But then read further:
```
Note that cells are tab-terminated, not tab-separated: trailing non-tab text at the end of a line does not form a column cell.
```
This is emphasized twice. That said, I agree that this does appear to contradict the former sentence. I'll update the doc.

**Comment by spenczar** [comment] 2016-02-24 17:13
Thank you - I really appreciate the work on docs, boring as it may be. The examples make this sparklingly clear now.
