### ISSUE TITLE
cmd/cover: -coverpkg causes init methods to be run for non-imported packages

### ISSUE THREAD

**Issue by benmoss** [golang/go#46212] opened 2021-05-17 19:21 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cesium/.cache/go-build"
GOENV="/home/cesium/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/cesium/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/cesium/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/cesium/workspace/foo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build292183072=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Very similar to #21283, but I think the distinction here is that if you run:
```
go test ./... -coverpkg all
```
or 
```
go test ./... -coverpkg foo/qux
```

you get `init` calls from the qux package happening in the `foo` test suite, when `qux` is not imported. Without `coverpkg` this package does not get imported.

I have made a repro with more information in the README here: https://github.com/benmoss/go-coverpkg-inits

### What did you expect to see?
The qux package init function should only be run during tests that import it.

### What did you see instead?
It is executed even when it is not imported.

**Comment by benmoss** [comment] 2021-05-17 19:29
You can also use the repro from #21283, https://github.com/AZavorotnii/go-coverpkg-initissue

```
$ go test -coverpkg all -v
foo.
main.
main main.
foo Foo.
testing: warning: no tests to run
PASS
coverage: 13.8% of statements in all
ok      go-coverpkg-initissue   0.001s
```

```
go test -coverpkg all -v ./...
foo.
main.
bar.  <-- here is issue
main main.
foo Foo.
testing: warning: no tests to run
PASS
coverage: 14.3% of statements in all
ok      go-coverpkg-initissue   (cached)        coverage: 14.3% of statements in all [no tests to run]
?       go-coverpkg-initissue/bar       [no test files]
?       go-coverpkg-initissue/foo       [no test files]
```

**Comment by dmitshur** [comment] 2021-05-18 01:10
Not sure if the problem is in cmd/cover or how cmd/go uses it, but it looks more like the latter. CC @matloob, @jayconrod, @matloob.

**Comment by jayconrod** [comment] 2021-05-18 13:35
This is a consequence of the go command linking all packages with coverage instrumentation into the test binary, even if they wouldn't be linked otherwise.

I'll close this as a duplicate of #23910, which is the root problem.

**Closed by jayconrod** 2021-05-18 13:35 UTC
Labels: NeedsInvestigation
