### ISSUE TITLE
net/Ip: net.ParseIP does not parse IP v6 Loopback address

### ISSUE THREAD

**Issue by jokaorgua** [golang/go#52358] opened 2022-04-14 14:30 UTC
issue https://github.com/golang/go/issues/34205 is still active for golang 1.18 but I can not re-open it. This bug still needs a fix

**Comment by seankhliao** [comment] 2022-04-14 14:43
That's not an IP address, that's a host:port pair

Closing as not a bug

**Closed by seankhliao** 2022-04-14 14:43 UTC

**Comment by jokaorgua** [comment] 2022-04-14 14:45
@seankhliao 
this is ipv6 loopback returned by http.Request. is this a bug in http.Request ?

**Comment by seankhliao** [comment] 2022-04-14 16:27
no, `http.Request` doesn't say is just an IP

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
