### ISSUE TITLE
runtime: GC freeing goroutines memory but then taking it again

### ISSUE THREAD

**Issue by siritinga** [golang/go#8832] opened 2014-09-29 07:08 UTC
<pre>I'm seen this in tip version:
go version devel +9472d0e26c23 Sun Sep 28 08:27:05 2014 -0700 linux/amd64

Using this simple program:
<a href="http://play.golang.org/p/ircvbhPy3u">http://play.golang.org/p/ircvbhPy3u</a>

There is a related issue here:
<a href="https://golang.org/issue/8287">https://golang.org/issue/8287</a>

It will immediately use 250 MB of RES memory. After about 10 minutes, the scavenger will
free 205 MB, showing about 45MB of RES. Ignoring that there are still 45 MB used, the
real problem is that after that point, the RES memory will increase slowly until it uses
250MB of RES again!

This is what &quot;ps u&quot; shows every 10 seconds:

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
user     22626  2.5  3.1 261336 258096 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  1.6  3.1 261336 258164 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  1.0  3.1 261336 258164 pts/4   Sl+  08:34   0:00 ./tmp
[...] 9 minutes later... 
user     22626  0.0  3.2 261336 258792 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  0.0  3.2 261336 258792 pts/4   Sl+  08:34   0:00 ./tmp
[Here the scavenger frees the memory]
user     22626  0.0  0.6 261336 48776 pts/4    Sl+  08:34   0:00 ./tmp
user     22626  0.0  0.6 261336 48776 pts/4    Sl+  08:34   0:00 ./tmp
user     22626  0.0  0.6 261336 48776 pts/4    Sl+  08:34   0:00 ./tmp
user     22626  0.0  0.6 261336 48776 pts/4    Sl+  08:34   0:00 ./tmp
user     22626  0.0  0.6 261336 48776 pts/4    Sl+  08:34   0:00 ./tmp
user     22626  0.0  0.6 261336 48776 pts/4    Sl+  08:34   0:00 ./tmp
user     22626  0.0  0.6 261336 48776 pts/4    Sl+  08:34   0:00 ./tmp
user     22626  0.0  0.6 261336 48776 pts/4    Sl+  08:34   0:00 ./tmp
user     22626  0.0  0.6 261336 48776 pts/4    Sl+  08:34   0:00 ./tmp
user     22626  0.0  0.6 261336 48776 pts/4    Sl+  08:34   0:00 ./tmp
user     22626  0.0  0.6 261336 48776 pts/4    Sl+  08:34   0:00 ./tmp
user     22626  0.0  0.6 261336 48776 pts/4    Sl+  08:34   0:00 ./tmp
[from here, the memory is increased little by little]
user     22626  0.0  0.6 261336 50384 pts/4    Sl+  08:34   0:00 ./tmp
user     22626  0.0  0.8 261336 64736 pts/4    Sl+  08:34   0:00 ./tmp
user     22626  0.0  0.9 261336 79096 pts/4    Sl+  08:34   0:00 ./tmp
user     22626  0.0  1.1 261336 93472 pts/4    Sl+  08:34   0:00 ./tmp
user     22626  0.0  1.3 261336 107840 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  0.0  1.5 261336 122216 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  0.0  1.6 261336 136600 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  0.0  1.8 261336 151000 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  0.0  2.0 261336 165336 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  0.0  2.2 261336 179744 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  0.0  2.4 261336 194080 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  0.0  2.5 261336 208512 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  0.0  2.7 261336 222848 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  0.0  2.9 261336 237184 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  0.0  3.0 261336 249728 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  0.0  3.1 261336 255520 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  0.0  3.1 261336 255520 pts/4   Sl+  08:34   0:00 ./tmp
user     22626  0.0  3.1 261336 255520 pts/4   Sl+  08:34   0:00 ./tmp
[remains here, it is not freed again and not detected by the GC]</pre>

**Comment by ricktian1226** [comment] 2015-02-09 07:04
When will this issue be fixed? It happens on our production project too.

**Comment by bradfitz** [comment] 2015-02-09 07:11
It's targeted for Go 1.5. Any updates will occur on this thread.

**Comment by RLH** [comment] 2015-02-09 17:45
I'm trying to get a sense of the use case here. You have 100,000 goroutines, could you indicate
which of the following are true, say for 99,000 of the goroutines.
1) Each go routine gets input from
a. A channel
b. A socket
c. shared immutable memory
d. shared mutable memory
e. no input, only output.
2) Each go routine provides output to
a. A channel
b. A socket
c. shared memory that it mutates
    1. with pointers to freshly allocated data structures
    2. no freshly allocated memory is referenced after the goroutine ends

I ask this since the answers will help dictate the best solution. An optimal solution for a goroutine
that just does a 10 second noop might be to just elide the goroutine, which is probably not what you want.

**Comment by randall77** [comment] 2015-02-09 19:21
I don't see the behavior the OP sees at tip.  The RSS drops to 46MB and stays there.
Probably something changed between September and now.

go version devel +f8176f8 Mon Feb 9 18:20:28 2015 +0000 linux/amd64
(one line per minute)
khr      13203  0.2  1.5 260856 255968 pts/1   Sl+  10:46   0:00 ./issue8832
khr      13203  0.2  1.5 260856 255972 pts/1   Sl+  10:46   0:00 ./issue8832
khr      13203  0.1  1.5 260856 255972 pts/1   Sl+  10:46   0:00 ./issue8832
khr      13203  0.1  1.5 260856 255972 pts/1   Sl+  10:46   0:00 ./issue8832
khr      13203  0.1  1.5 260856 255972 pts/1   Sl+  10:46   0:00 ./issue8832
khr      13203  0.1  1.5 260856 255980 pts/1   Sl+  10:46   0:00 ./issue8832
khr      13203  0.0  1.5 260856 255980 pts/1   Sl+  10:46   0:00 ./issue8832
khr      13203  0.0  1.5 260856 255980 pts/1   Sl+  10:46   0:00 ./issue8832
khr      13203  0.0  0.2 260856 46144 pts/1    Sl+  10:46   0:00 ./issue8832
khr      13203  0.0  0.2 260856 46144 pts/1    Sl+  10:46   0:00 ./issue8832
khr      13203  0.0  0.2 260856 46144 pts/1    Sl+  10:46   0:00 ./issue8832
khr      13203  0.0  0.2 260856 46144 pts/1    Sl+  10:46   0:00 ./issue8832
khr      13203  0.0  0.2 260856 46144 pts/1    Sl+  10:46   0:00 ./issue8832
khr      13203  0.0  0.2 260856 46144 pts/1    Sl+  10:46   0:00 ./issue8832
khr      13203  0.0  0.2 260856 46144 pts/1    Sl+  10:46   0:00 ./issue8832
khr      13203  0.0  0.2 260856 46144 pts/1    Sl+  10:46   0:00 ./issue8832
khr      13203  0.0  0.2 260856 46144 pts/1    Sl+  10:46   0:00 ./issue8832
khr      13203  0.0  0.2 260856 46144 pts/1    Sl+  10:46   0:00 ./issue8832
khr      13203  0.0  0.2 260856 46144 pts/1    Sl+  10:46   0:00 ./issue8832

**Comment by siritinga** [comment] 2015-02-09 20:16
It is still there. Slower, but I see it going up to 56 MB before I stopped it, in about half an hour.

**Comment by randall77** [comment] 2015-02-10 00:49
So it is, if you wait long enough (for me, 16 minutes after the free) it starts growing.  Very strange.  The runtime doesn't allocate a single MSpan during that time, so I'm inclined to think this is a bug in linux/madvise.  But I haven't been able to reproduce it outside the Go runtime.  I'll keep looking.

**Comment by minux** [comment] 2015-02-10 00:53
Could it because somehow our GC tries to scan or otherwise
read freed MSpans?

**Comment by randall77** [comment] 2015-02-10 00:59
I suppose it is possible, but I don't see how that doesn't happen in the first 16 minutes and then starts happening thereafter.  Lots of GCs happen in that window.

**Comment by randall77** [comment] 2015-02-10 15:08
I replaced the madvise call with munmap.  It fixed the problem and the program never crashed.  That tells us that the runtime never touches those pages after it is done with them, and that the bug is probably in madvise.  Or munmap is buggy as well...

**Comment by dvyukov** [comment] 2015-02-10 15:34
Have you changed sysUsed? How?

**Comment by randall77** [comment] 2015-02-10 19:01
No, I have not changed sysUsed.  If the program tried to use any sysUnused page again, it would fault.  Can't be checked in, of course, but it's fine for debugging this problem.

**Comment by randall77** [comment] 2015-02-11 00:01
I do not see this bug on my home Ubuntu box

$ uname -a
Linux linux 3.8.0-44-generic #66~precise1-Ubuntu SMP Tue Jul 15 04:01:04 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Might be something os-specific.  siritinga, what's your machine running?

**Comment by randall77** [comment] 2015-02-11 07:15
On an amazon ec2 instance (c4.xlarge, Ubuntu Server 14.04 LTS), the memory comes back really fast, about 4 minutes after it gets madvised:

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
ubuntu    7236  1.6  3.3 260856 257244 pts/0   Sl   04:03   0:00 ./issue8832
ubuntu    7236  0.4  3.3 260856 257244 pts/0   Sl   04:03   0:00 ./issue8832
ubuntu    7236  0.3  3.3 260856 257448 pts/0   Sl   04:03   0:00 ./issue8832
ubuntu    7236  0.2  3.3 260856 258800 pts/0   Sl   04:03   0:00 ./issue8832
ubuntu    7236  0.2  3.3 260856 258800 pts/0   Sl   04:03   0:00 ./issue8832
ubuntu    7236  0.1  3.3 260856 258800 pts/0   Sl   04:03   0:00 ./issue8832
ubuntu    7236  0.1  3.3 260856 258808 pts/0   Sl   04:03   0:00 ./issue8832
ubuntu    7236  0.1  3.3 260856 258808 pts/0   Sl   04:03   0:00 ./issue8832
ubuntu    7236  0.1  3.3 260856 258808 pts/0   Sl   04:03   0:00 ./issue8832
ubuntu    7236  0.1  0.8 260856 63296 pts/0    Sl   04:03   0:00 ./issue8832
ubuntu    7236  0.1  1.9 260856 147696 pts/0   Sl   04:03   0:00 ./issue8832
ubuntu    7236  0.1  2.8 260856 216064 pts/0   Sl   04:03   0:00 ./issue8832
ubuntu    7236  0.1  3.3 260856 255576 pts/0   Sl   04:03   0:00 ./issue8832
ubuntu    7236  0.1  3.3 260856 255576 pts/0   Sl   04:03   0:00 ./issue8832
ubuntu    7236  0.1  3.3 260856 255576 pts/0   Sl   04:03   0:00 ./issue8832

Linux ip-172-30-0-129 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Still don't know what is going on.

**Comment by siritinga** [comment] 2015-02-11 08:22
I don't have access right now to the computer where I did the test to check the kernel version, but it is a Ubuntu 14.04 TLS 64 bits with the latests updates applied.

**Comment by randall77** [comment] 2015-02-11 21:18
I have successfully reproduced this outside of Go.  I hacked the runtime to log every time it does an mmap, munmap, or madvise.  A little C program replays the log and exhibits the same behavior.

Part of the problem may be the number of madvise calls.  There are over 4000 of them in this example.  The resulting heap has lots of 1 page in-use spans interspersed with small (1-10 pages typically) not-in-use spans.  I'm not sure why our in-use pages are so scattered.  I'll look into that, it is not the root cause of this bug but may be contributing.

I'll see if I can send the extracted example to linux folks.

**Comment by randall77** [comment] 2015-02-11 21:25
[replay.c](http://keithandkatie.com/downloads/replay.c)
[memlog](http://keithandkatie.com/downloads/memlog)

gcc replay.c -o replay
./replay memlog

It runs the log and then prints RSS once a second.  Watch it grow, kind of like a chia pet.

**Comment by davecheney** [comment] 2015-02-11 21:30
Testing on my system (ubuntu linux 14.04.1) fails to grow at all, stupid
chia pet.

Dumb question, is swap disabled on the systems that you see this behaviour
on?

**Comment by ianlancetaylor** [comment] 2015-02-11 21:37
Nice repro.  Wacky, but nice.

I guess we can leave this issue open until we hear back from the kernel folks to see whether there is something we can do to avoid the odd behaviour.

**Comment by randall77** [comment] 2015-02-11 22:43
Both.  Swap is disabled on the ec2 instance where this happens quickest.  It also happens on my laptop where swap is enabled, although it takes a lot longer (2 min vs. 45 min).

**Comment by randall77** [comment] 2015-02-12 00:39
Kernel bug report: https://bugzilla.kernel.org/show_bug.cgi?id=93111

**Comment by randall77** [comment] 2015-02-23 22:14
Patch is out to work around the kernel bug.  The other part of this issue is why our heap is so fragmented in the first place.  It deserves its own issue, #9869.

**Closed** 2015-02-25 21:18 UTC
Labels: kernel-bug, os-linux, repo-main
