### ISSUE TITLE
x/build: timeout on LUCI netbsd-arm64 builder

### ISSUE THREAD

**Issue by cherrymui** [golang/go#65313] opened 2024-01-26 19:46 UTC
```
#!watchflakes
post <- builder ~ `(gotip|go1\.\d\d)-netbsd-arm64` && (`test timed out` || `SIGQUIT` || `context deadline exceeded` || status == "ABORT")
```

It mostly times out on the tools repo.

**Comment by bcmills** [comment] 2024-02-21 22:24
Duplicate of #65845

**Closed by bcmills** 2024-02-21 22:24 UTC
Labels: Builders, NeedsInvestigation
