### ISSUE TITLE
encoding/asn1: document that Unmarshal drops trailing elements

### ISSUE THREAD

**Issue by AbstractSyntaxNotator** [golang/go#38545] opened 2020-04-20 21:04 UTC
### What version of Go are you using (`go version`)?
go1.14

### Does this issue reproduce with the latest release?
Yes, on [Go playground](https://play.golang.org/p/86UNo9JNSGM) the current version is 1.14.2 

### What did you do?

As shown in the following [Go playground snippet](https://play.golang.org/p/86UNo9JNSGM), I define 2 structs:
```
type AB struct {
	A, B int
}

type ABC struct {
	A, B, C int
}
```
and then I first feed the smaller struct (AB) instance into the larger one (ABC):
```
	abBytes, _ := asn1.Marshal(AB{A: 1, B: 2})

	abc := ABC{}
	asn1.Unmarshal(abBytes, &abc)
```

 then I assign the third field of the larger instance (ABC) and marshal the larger instance (ABC) to bytes

```
	abc.C = 3
	abcBytes, _ := asn1.Marshal(abc)
```

Followed by pouring the bytes from the larger instance (ABC) into an empty smaller instance (AB):

```
	ab := AB{}
	rest, err := asn1.Unmarshal(abcBytes, &ab)
	fmt.Println(rest, err) // [] <nil>

	fmt.Println(ab) // {1 2}

	fmt.Println(hex.EncodeToString(abBytes))  // 3006020101020102
	fmt.Println(hex.EncodeToString(abcBytes)) // 3009020101020102020103
```

### What did you expect to see?
I expected the rest not to be empty! I should get a hint that there were trailing bytes, should I not?
```
	rest, err := asn1.Unmarshal(abcBytes, &ab)
	fmt.Println(rest, err) // [] <nil>
```

### What did you see instead?
The rest is empty and no error was returned.

Needless to say, some applications might be... sensitive to this kind of behavior.

**Comment by ianlancetaylor** [comment] 2020-04-20 22:03
For better or for worse, that is how the encoding/asn1 package works.  There is a comment in the source code:

```Go
		// We allow extra bytes at the end of the SEQUENCE because
		// adding elements to the end has been used in X.509 as the
		// version numbers have increased.
```

I don't think we can change that now.

CC @agl @FiloSottile

**Comment by yacovm** [comment] 2020-04-20 22:09
This comment snippet is not from the [go-doc](https://golang.org/src/encoding/asn1/asn1.go?s=30565:30631#L1072) but [buried deep within the code](https://golang.org/src/encoding/asn1/asn1.go?s=30565:30631#L950).
Also I've noticed the return parameters (namely the **rest []byte**) are not documented.

**Comment by AbstractSyntaxNotator** [comment] 2020-04-20 22:14
> I don't think we can change that now.

That's fine, I guess people would have to live with that, however: 

- These comments you quoted are not from the go-doc but [buried deep within the code](https://golang.org/src/encoding/asn1/asn1.go?s=30565:30631#L950).
- The [go-doc](https://golang.org/src/encoding/asn1/asn1.go?s=30565:30631#L1072) doesn't say anything about when rest is not empty, can we change that?

**Comment by ianlancetaylor** [comment] 2020-04-20 22:36
Yes, we can certainly change the documentation.  Want to send a patch?

**Comment by AbstractSyntaxNotator** [comment] 2020-04-20 22:43
I think it's best if someone else does it.

I have no knowledge of ASN1 and I also opened this throwaway user just for reporting this.

**Comment by FiloSottile** [comment] 2020-04-21 06:30
This is indeed intended behavior, although something that surprised me at some point, too. Adding elements to SEQUENCEs is how ASN.1 is extended. If you want to check there's no extra elements, you should use golang.org/x/crypto/cryptobyte instead (and we do here and there for things like signature parsing).

**Comment by abemotion** [comment] 2020-04-23 07:24
rest is needed? initOffset is always zero and json.Unmarshal returns only error.
https://golang.org/src/encoding/asn1/asn1.go?s=30565:30631#L1082

```
func Unmarshal(b []byte, val interface{}) (rest []byte, err error) {
	return UnmarshalWithParams(b, val, "")
}
```

```
func UnmarshalWithParams(b []byte, val interface{}, params string) (rest []byte, err error) {
	v := reflect.ValueOf(val).Elem()
	offset, err := parseField(v, b, 0, parseFieldParameters(params))
	if err != nil {
		return nil, err
	}
	return b[offset:], nil
}
```

```
func parseField(v reflect.Value, bytes []byte, initOffset int, params fieldParameters) (offset int, err error)
```

**Comment by katiehockman** [comment] 2020-05-12 20:28
Marking this as a duplicate of https://github.com/golang/go/issues/35680, which is addressed in https://golang.org/cl/233537.

**Closed by katiehockman** 2020-05-12 20:28 UTC
Labels: Documentation, NeedsFix
