### ISSUE TITLE
archive/tar: io.copy hangs when using io.pipe and tarReader

### ISSUE THREAD

**Issue by jquick** [golang/go#53110] opened 2022-05-27 14:58 UTC
### What version of Go are you using (`go version`)?

go version go1.18.2 darwin/arm64
go version go1.17.6 darwin/arm64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
❯ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN="/Users/jared.quick/go/bin"
GOCACHE="/Users/jared.quick/Library/Caches/go-build"
GOENV="/Users/jared.quick/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jared.quick/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jared.quick/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.18.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.18.2/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jared.quick/dev/test_pipes/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yq/hv1ztnz90dg3kw91rn3m_gym0000gq/T/go-build3766060246=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>
(was also tested on a amd64 machine)

### What did you do?

In this little example I show 3 cases:
1) Reading a raw tar file using a io.pipe - works
2) Reading via tarReader a tar file using bytes.buffer - works
3) Reading via tarReader a tar file using io.pipe - does not work

https://go.dev/play/p/cDqxssuAaT2

### What did you expect to see?

The io.pipe to close after fully reading the file to EOF when using tarReader and io.pipe.

### What did you see instead?

The io.copy hangs indefinitely after the EOF is reached and the pipe is empty.

**Comment by Jorropo** [comment] 2022-05-28 02:56
This sounds good to me.
Your code seems wrong.
```diff
// reading tarReader bytes using a io.pipe from file
func doesNotWork() error {
 	pr, pw := io.Pipe()
 	errC := make(chan error, 1)
 	go func() {
-		defer func() { _ = pw.Close() }()
 		errC <- readTar(DummyTar, pw)
 	}()

 	tarR := tar.NewReader(pr)
 	bArray := make([]byte, 1)
 	for {
 		_, err := tarR.Read(bArray)
 		if err == io.EOF {
 			fmt.Println("EOF reached!")
 			break
 		} else if err != nil {
 			return err
 		}
 	}
+	pw.Close()
 	<-errC
 	fmt.Println("doesNotWork finished successfully")
 	return nil
 }
```
This works.

As far I can tell, reading the file from `tarR` doesn't fully exhaust the underlying reader which is happening because `(*tar.Reader).Read` send `io.EOF` based on the tar metadata length, not the underlying reader sending EOF.
First copying the data into a buffer would have the same effect.
Calling `tarR.Next()` also fix it by exhausting the underlying reader.

**Comment by jquick** [comment] 2022-05-28 12:42
@[Jorropo](https://github.com/Jorropo) Thanks for your help with this! You're right, I found 512 bytes in the pipe reader that needed to be drained after the tar `io.EOF` was reached. You can use `pr.Read()` or `tarR.Next()` after the tar `io.EOF` to fully flush the pipe and then the `io.copy` will close as expected.

It is still is a little odd to me that `tarR.Read()` will not flush the underline reader anymore after EOF but `tarR.Next()` will. I can add another `tarR.Next()` in my code after fully reading the tar to fix this but it seems a little confusing. I wonder if there is any merit to auto draining the underline reader when `tar.Reader` hits the `io.EOF` header.

**Comment by seankhliao** [comment] 2022-05-28 12:58
This is an incorrect use of `archive/tar.Reader`
`Next()` has to be called to read any part, including the first. It's expected to be called until it reaches `io.EOF`
 This is less obvious in your example because it uses 0 sized files as input.

Closing as not a bug

**Closed by seankhliao** 2022-05-28 12:58 UTC

**Comment by jquick** [comment] 2022-05-28 13:28
For anyone that may come across this. I still see this issue rarely with some tar files (will try to upload an example) while explicitly using `tar.Next()` until it reaches `io.EOF`. The only work around I have found is to drain the pipe reader manually after. `tar.Next()` will just keep returning `io.EOF` even if there are bytes still in the pipe.
