### ISSUE TITLE
x/tools/gopls: fix autocompletion of structs in slices

### ISSUE THREAD

**Issue by WOo0W** [golang/go#33211] opened 2019-07-22 03:12 UTC
### go version
<pre>
go version go1.12.5 windows/amd64
</pre>

### gopls version

<pre>
version v0.1.3, built in $GOPATH mode
</pre>
On VSCode:
This seems OK (ctrl + space):
![image](https://user-images.githubusercontent.com/24245520/61603501-5e4e1180-ac70-11e9-8ddc-40c593c2f8cc.png)

After deleted `&cli.Command` before `Name:`, press ctrl + space:
![image](https://user-images.githubusercontent.com/24245520/61603513-6c9c2d80-ac70-11e9-980d-888566b75230.png)

It will not show the completions of the struct. It should show completions like the first one.

**Comment by stamblerre** [comment] 2019-07-22 16:45
Thank you for reporting this issue. We will investigate.

**Comment by ajjensen13** [comment] 2019-08-29 03:19
Hey! I'm looking for a good way to start contributing to the Go project. I spent a little time looking into this issue. It appears that the root of the issue is that it is a slice of pointers, which confuses the code in completion.go:enclosingCompositeLiteral(). The suggestions work correctly if it is a slice of structs (not pointers to structs).

I'll try to put together a fix for this unless someone does first.

**Closed** 2019-08-30 17:14 UTC
Labels: NeedsInvestigation, gopls, help wanted
