### ISSUE TITLE
net/http: ResponseWriter doesn't overwrite content-type after WriteHeader is called.

### ISSUE THREAD

**Issue by GordonJiang** [golang/go#17083] opened 2016-09-13 00:45 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.7

### What operating system and processor architecture are you using (`go env`)?
ubuntu, amd64

### What did you do?
in a http server handler, 
first call w.WriteHeader(http.StatusOK)
then call w.Header().Set("Content-Type", "application/json")
then w.Write(somedata compressed by gzip)

### What did you expect to see?
The Content-Type in response message captured by troubleshooting tool of chrome/firefox becomes application/x-gzip

### What did you see instead?
The Content-Type should be application/json as I set.

On the other hand, if I change the order. call w.Header().Set("Content-Type", "application/json") ahead of the w.WriteHeader(http.StatusOK), the Content-Type keeps what it is. Seems setting status ahead of write content-type trigger the logic to DetectContentType automatically. It's overwrite whatever content-type I set later.
Because of that, gzip content can't be parsed in firefox. Of course, I worked around it by changing the code to set content-type first. But it apparently a trap since there is no doc saying you should always set content-type before set status by WriteHeader.

**Comment by odeke-em** [comment] 2016-09-13 01:15
@GordonJiang this behavior is documented in https://golang.org/pkg/net/http/#ResponseWriter
<img width="799" alt="screen shot 2016-09-12 at 6 11 46 pm" src="https://cloud.githubusercontent.com/assets/4898263/18458269/97d936b0-7914-11e6-8b5f-8e3e2857c83a.png">

as the documentation for property Header(). 

Closing this issue unless someone else thinks we should do more.
/cc @bradfitz.

**Closed** 2016-09-13 01:16 UTC

**Comment by minux** [comment] 2016-09-13 02:43
Working as intended.

WriteHeader is supposed to write (all) the headers, so when it's called, it
will write the current Content-Type. Later update to the Header map won't
affect header that has already been written.
