### ISSUE TITLE
os: Test*EOF flaky

### ISSUE THREAD

**Issue by bcmills** [golang/go#35275] opened 2019-10-31 15:11 UTC
`darwin-amd64-10_14` (https://build.golang.org/log/e527731127351d19a8868d360bd6b534590f69f0):
```
--- FAIL: TestFifoEOF (60.05s)
    fifo_test.go:100: line 0
    fifo_test.go:100: line 1
    fifo_test.go:100: line 2
    fifo_test.go:108: timed out waiting for read
    fifo_test.go:86: error closing reader: close /var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/tmp/TestFifoEOF585114092/fifo: file already closed
FAIL
FAIL	os	60.911s
```

May relate to #25877 (CC @ianlancetaylor).

**Comment by bcmills** [comment] 2019-10-31 17:01
A very similar failure in `TestPipeEOF` on `aix-ppc64` (https://build.golang.org/log/836b814bee1107744a77bf2767d3f240586f6028):

```
--- FAIL: TestPipeEOF (1.01s)
    pipe_test.go:378: line 0
    pipe_test.go:378: line 1
    pipe_test.go:386: timed out waiting for read
    pipe_test.go:378: line 2
    pipe_test.go:375: read |0: file already closed
    pipe_test.go:364: error closing reader: close |0: file already closed
FAIL
FAIL	os	1.941s
```

**Comment by mknyszek** [comment] 2019-11-01 21:45
Seen on trybots (`windows-386-2008`), and I'm 99% it's not related to those changes: https://storage.googleapis.com/go-build-log/5064a99f/windows-386-2008_ac9f4654.log

```
--- FAIL: TestPipeEOF (1.00s)
    pipe_test.go:378: line 0
    pipe_test.go:378: line 1
    pipe_test.go:378: line 2
    pipe_test.go:386: timed out waiting for read
    pipe_test.go:375: read |0: file already closed
    pipe_test.go:364: error closing reader: close |0: file already closed
FAIL
FAIL	os	3.570s
```

**Comment by ianlancetaylor** [comment] 2019-11-01 21:54
So far, the `TestFifoEOF` error is happening only on Darwin.  The `TestPipeEOF` error has not yet been seen on Darwin.  Though I agree they look quite similar.

[2019-10-30T21:43:57-6becb03/darwin-arm-mg912baios](https://build.golang.org/log/2e8bdc70ea59d85dfe24d7a6a32f476a182747cc)
[2019-10-31T09:49:57-1085560/darwin-amd64-10_14](https://build.golang.org/log/e527731127351d19a8868d360bd6b534590f69f0)
[2019-10-31T09:49:57-1085560/darwin-arm64-corellium](https://build.golang.org/log/2d6232a5baf8762145bb40229798d40411c7f9df)
[2019-10-31T17:21:56-48c0cef/darwin-386-10_14](https://build.golang.org/log/3384d985ae54dd9814df9a6f384ff8e615fdef1a)

**Comment by mknyszek** [comment] 2019-11-01 22:17
@ianlancetaylor I saw a `TestFifoEOF` error on a `linux/amd64` trybot just now: https://storage.googleapis.com/go-build-log/22734f54/linux-amd64_a7c99ff2.log

```
--- FAIL: TestFifoEOF (1.01s)
    fifo_test.go:108: timed out waiting for read
    fifo_test.go:100: line 0
    fifo_test.go:97: read /workdir/tmp/TestFifoEOF684921827/fifo: file already closed
    fifo_test.go:86: error closing reader: close /workdir/tmp/TestFifoEOF684921827/fifo: file already closed
    fifo_test.go:66: error writing to fifo: write /workdir/tmp/TestFifoEOF684921827/fifo: broken pipe
FAIL
FAIL	os	1.601s
```

**Comment by ianlancetaylor** [comment] 2019-11-01 22:41
Thanks.  I haven't had any luck reproducing this.

**Comment by ianlancetaylor** [comment] 2019-11-01 22:43
There is certainly a chance that this will be fixed by https://golang.org/cl/204800, but it's hard to know for sure.

**Comment by FiloSottile** [comment] 2019-11-04 19:45
https://storage.googleapis.com/go-build-log/52250b89/windows-386-2008_e048933d.log

```
--- FAIL: TestPipeEOF (1.00s)
    pipe_test.go:378: line 0
    pipe_test.go:378: line 1
    pipe_test.go:378: line 2
    pipe_test.go:386: timed out waiting for read
    pipe_test.go:364: error closing reader: close |0: file already closed
```

From the https://golang.org/cl/204377 TryBot.

**Comment by ianlancetaylor** [comment] 2019-11-04 19:48
CL 204800 is still awaiting review.

**Comment by ianlancetaylor** [comment] 2019-11-06 05:16
This hasn't happened since https://golang.org/cl/204800 was committed.  It is almost certainly fixed.

**Closed by ianlancetaylor** 2019-11-06 05:16 UTC
Labels: NeedsInvestigation, release-blocker
