### ISSUE TITLE
go/format: format.Node internal error (1:13: expected ';', found '-')

### ISSUE THREAD

**Issue by bronze1man** [golang/go#30950] opened 2019-03-20 12:42 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
may be, It reproduce in https://play.golang.org/

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/a/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/a/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m9/qtbxkp6s3p96fk54rln7qhj80000gp/T/go-build885997839=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

https://play.golang.org/p/yGvWuAzSUTB

```go
package main

import (
	"bytes"
	"go/format"
	"fmt"
	"go/token"
	"go/parser"
)

func main(){
	fs:=token.NewFileSet()
	f,err:=parser.ParseFile(fs,"1.go",`package main

import (
	"fmt"
	"strconv"
)
func main(){
	fmt.Println(strconv.Itoa(1))
}`,parser.AllErrors)
	if err!=nil{
		panic(err)
	}
	f.Name.Name = "main-go"
	_buf:=&bytes.Buffer{}
	err=format.Node(_buf,fs,f)
	if err!=nil{
		panic(err)
	}
	fmt.Println(_buf.String())
}
```

### What did you expect to see?
Some good formated error says that the  bad package name.

### What did you see instead?
```
format.Node internal error (1:13: expected ';', found '-')
```

**Comment by ianlancetaylor** [comment] 2019-03-20 13:50
CC @griesemer

**Comment by griesemer** [comment] 2019-03-20 14:59
The reason is that the program in question explicitly changes the package name from `main` to `main-go`, and `main-go` is not a valid identifier.

One might expect the formatter not to care, but (as an implementation detail) it currently parses the source a 2nd time, at which point the parser complains.

Generally, the various `go/*` libraries may behave in undefined ways if the source or the AST is incorrect. Here, a valid AST is explicitly made incorrect. Don't do that.

Working as intended. Closing.

**Closed by griesemer** 2019-03-20 14:59 UTC
Labels: NeedsInvestigation
