### ISSUE TITLE
mobile: gomobile (tip) bind prefix not working

### ISSUE THREAD

**Issue by gwik** [golang/go#25126] opened 2018-04-27 13:35 UTC
### What version of Go are you using (`go version`)?
```
go version devel +e656aebb5b Fri Apr 27 10:04:48 2018 +0000 darwin/amd64
```

### Does this issue reproduce with the latest release?

n/a, on tip.

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/aamand/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="<redacted gopath>/Dev/go"
GORACE=""
GOROOT="/Users/aamand/gotip"
GOTMPDIR=""
GOTOOLDIR="/Users/aamand/gotip/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cd/_7rcv5812531s2lswhn6kp680000gp/T/go-build281736624=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

Build on darwin with `gomobile bind` the prefix option (for objc) causing an error:

```
CGO_CFLAGS_ALLOW=".*" \
	CGO_LDFLAGS_ALLOW=".*" \
	CGO_CFLAGS_DISALLOW="-fplugin.*" \
	CGO_LDFLAGS_DISALLOW="-fplugin.*" \
	gomobile bind \
		-v \
		-i \
		-target=ios/arm64 \
		-tags=lldb \
		-o=<redacted gopath>/Dev/go/src/<redacted package>/build/Zenlygocore.framework \
		-ldflags="-X \"<redacted package>/coreversion.coreVersion=1.12.0-alpha.2757+053d02c0\"" \
		-prefix=Zenly_ \
		<redacted package>/zenlygocore
```

### What did you expect to see?

Should compile.

### What did you see instead?
```
Zenlygocore_darwin.m:9:10: fatal error: 'Zenly_Zenlygocore.objc.h' file not found
WORK=/var/folders/cd/_7rcv5812531s2lswhn6kp680000gp/T/gomobile-work-369133126
gomobile: darwin-arm64: go build -tags lldb ios -v -i -ldflags -X "<redacted package>/coreversion.coreVersion=1.12.0-alpha.2757+053d02c0" -work -buildmode=c-archive -o /var/folders/cd/_7rcv5812531s2lswhn6kp680000gp/T/gomobile-work-369133126/zenlygocore-arm64.a gobind failed: exit status 2
```

It seems in doesn't expect the prefix in the header file name:
```
find /var/folders/cd/_7rcv5812531s2lswhn6kp680000gp/T/gomobile-work-369133126 -name '*.objc.h'
/var/folders/cd/_7rcv5812531s2lswhn6kp680000gp/T/gomobile-work-369133126/src/gobind/Zenlygocore.objc.h
/var/folders/cd/_7rcv5812531s2lswhn6kp680000gp/T/gomobile-work-369133126/src/gobind/Universe.objc.h
```

cc @eliasnaur

**Comment by eliasnaur** [comment] 2018-04-27 13:45
Do you have a self-contained reproducer, perhaps simply the hello example? There is a test for a custom prefix so I'm surprised this broke.

**Comment by AlexRouSg** [comment] 2018-04-27 14:03
@eliasnaur dupe of #24986 which uses the gomobile bind example and also on ios

**Comment by bcmills** [comment] 2018-04-27 16:55
Closing as duplicate.

**Closed by bcmills** 2018-04-27 16:55 UTC
