### ISSUE TITLE
go/importer: API lacks necessary features of (deprecated) golang.org/x/tools/go/importer

### ISSUE THREAD

**Issue by alandonovan** [golang/go#13222] opened 2015-11-12 22:00 UTC
A number of users have asked how they can load type information from the export data section of a .a file produced by the Go compiler.  Although you can use the standard go/importer package to find (relative to $GOPATH) and load a .a file, it provides no way to load a file that lives elsewhere.  In contrast, the old API separated the operations of FindPkg and Import.  

The new package should provide these features too, as users are currently forced to fork either the deprecated x/tools package or the standard go/internal/gcimporter package.

**Comment by griesemer** [comment] 2017-06-16 22:12
Too late for 1.9.

**Comment by griesemer** [comment] 2017-08-15 13:04
@alandonovan Isn't this a duplicate of #13847?

**Comment by alandonovan** [comment] 2017-08-15 19:37
Yes, that issue could subsume this one.

The Lookup function isn't fully specified yet.  Either it should return the name of a .a file for a given package, or it should return a reader for the specific exportdata section within the file.  The latter is more flexible but puts the burden of parsing .a files onto the client.  I suspect some clients will continue to need the full generality of the golang.org/x/tools/gcexportdata API.

**Comment by griesemer** [comment] 2017-08-16 09:48
Closed as duplicate of #13847.

**Closed by griesemer** 2017-08-16 09:48 UTC
