### ISSUE TITLE
proxy.golang.org: randomly seeing '410 Gone' 

### ISSUE THREAD

**Issue by myitcv** [golang/go#33346] opened 2019-07-29 12:48 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13beta1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build625318406=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://github.com/myitcv/govim/blob/0404c34fe3a519a751240a40088e2c0f73f2a2fa/go.mod relies on `github.com/fsnotify/fsnotify v1.4.7`. In the last few Travis CI builds I've seen the following:

```
github.com/fsnotify/fsnotify@v1.4.7: github.com/fsnotify/fsnotify@v1.4.7: reading https://proxy.golang.org/github.com/fsnotify/fsnotify/@v/v1.4.7.zip: 410 Gone
```

However, this has not happened in all builds, hence the problem seems intermittent. 

### What did you expect to see?

No error; because `github.com/fsnotify/fsnotify v1.4.7` is available in proxy.golang.org.

### What did you see instead?

As above

cc @katiehockman @heschik

**Comment by bcmills** [comment] 2019-07-29 17:11
CC @hyangah

**Comment by hyangah** [comment] 2019-07-29 17:38
Thanks a lot for reporting the problem. 

We confirmed this is an internal network issue. Now mitigation is in place and we are working on long term fix to detect and prevent this kind of issues.
Let us know if you are still seeing the problem.

This is happening with such a low probability so it would be hard to detect the problem without timely user report. @myitcv We greatly appreciate your diligence reporting the problems!

**Comment by elithrar** [comment] 2019-07-30 03:52
I'm also seeing this - let me know what I can provide to be useful.

```sh
go: github.com/gogo/protobuf@v0.0.0-20190410021324-65acae22fc9: unexpected status (https://proxy.golang.org/github.com/gogo/protobuf/@v/v0.0.0-20190410021324-65acae22fc9.info): 410 Gone
go: error loading module requirements
```

`go.mod` at that commit: https://github.com/elithrar/admission-control/blob/60a0949c5aca7309cfa3cb9de97fa9b0b53bb5ed/go.mod
CI job with `go mod download` output: https://app.circleci.com/jobs/github/elithrar/admission-control/179/parallel-runs/0/steps/0-103

**Comment by heschik** [comment] 2019-07-30 04:26
There are a lot of reasons that `proxy.golang.org` returns 410; usually if you look at the link it'll tell you why. In this case:

```
not found: github.com/gogo/protobuf@v0.0.0-20190410021324-65acae22fc9: invalid pseudo-version: revision is shorter than canonical (65acae22fc9d)
```

This is an error new in 1.13, which is what `proxy.golang.org` runs. See "Version Validation" in https://tip.golang.org/doc/go1.13 for suggestions on how to fix it. Essentially, just delete everything but the hash and let the `go` command create the pseudoversion.

I'm going to close this bug, since the original issue is resolved.

**Closed by heschik** 2019-07-30 04:26 UTC
Labels: NeedsInvestigation, modules

**Comment by cezarsa** [comment] 2019-08-06 18:38
Sorry for commenting on a closed issue but I'm seeing the same problem as originally reported happening right now.

I'm getting intermittent errors in my CI build when using the proxy, example in https://travis-ci.org/tsuru/cadvisor-events-exporter/jobs/568492488:

```
go: gotest.tools@v2.3.0+incompatible: unexpected status
(https://proxy.golang.org/gotest.tools/@v/v2.3.0+incompatible.info): 410 Gone
```

If I wait a while or try again a few times the request is usually successful again. I tried curling this url a few times locally but was unable to reproduce the error, it always returns 200:
```
$ curl https://proxy.golang.org/gotest.tools/@v/v2.3.0+incompatible.info
{"Version":"v2.3.0+incompatible","Time":"2018-12-23T23:00:14Z"}
```

**Comment by katiehockman** [comment] 2019-08-06 18:52
We just removed a bunch of module versions from the proxy.golang.org module mirror which are newly invalid in 1.13.

If you go to https://proxy.golang.org/gotest.tools/@v/v2.3.0+incompatible.info, you'll see this error:
`not found: gotest.tools@v2.3.0+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required`

gotest.tools at version v2.3.0+incompatible is one of the versions we removed, which is why you're seeing the 410. Even though it is intermittently succeeding now, that is probably because your CI system is hitting our frontend cache, which holds info files like this for some time. Likely it will fail consistently for you with in a few hours.
