### ISSUE TITLE
all: better support for cpu feature detection

### ISSUE THREAD

**Issue by martisch** [golang/go#19739] opened 2017-03-28 12:27 UTC
Currently there are different approaches to make code aware if a x86/x64 cpu supports e.g.  SSE4, AVX2 BMI or POPCNT in the go std lib.

It seems likely that in the future only more packages will make decisions based on cpu features and more features will be introduced.

## Current State
Sometimes the detection functionality of the runtime is used which uses priviliged access only the standard library has due to the possibility of having package specific code in the runtime. In other cases the cpu feature detection code is duplicated in multiple packages or relies on being in sync with how the internal runtime variables are named that contain information if the cpu feature is supported.

### priviliged
The package that needs the check has its own function put into the runtime:
- strings·supportAVX2 in runtime/asm_amd64.s.

### duplicated detection code
Using CPUID directly and saving the result of the check in a package local variable:
- hasSSE4 in math/floor_amd64.s
- haveSSE41, haveSSE42, ieeeCLMUL in hash/crc32/crc32_amd64.s
....

### depending on runtime internals 
Using the runtime·support_XXX flags directly in asm code:
- crypto/sha1 , crypto/sha256, crypto/sha512
- bytes

## Possible replacement
A seperate cpu feature detection package could be provided in std lib that initializes exported bool variables once. These could be package scope or in a architecture specific structure to have a name space for different platforms.
* can be used the same way by the std lib and other go packages. (runtime can still use its own code internally to not create a dependency)
* only needs to run CPUID once to populate feature variables (or a structure)
* provides a uniform way to determine cpu feature support with consistent naming
* avoids code duplication

Addtionally the package could be extended in the future to support reading the CPU Vendor, name and family which could be used to print debug info or can be used by benchmark tools.

A possible problem is that if variables are used other packages could modify them which might not be expected by other users of the cpu feature package. A function could be provided that returns a copy of a protected internal feature flag structure which then can be used to make decisions once at the initialization of a package that wants to setup cpu feature specific code.

This ticket is meant to discuss if there is enough support to change the current situation and possible approaches to improve and make cpu feature checking more uniform and/or accessible.

I like to volunteer to work on a concrete proposal and implementation after the first round of feedback or just help clean up the std lib to converge on a more unified approach.

/cc @randall77 @griesemer @mdempsky @josharian

**Comment by rsc** [comment] 2017-03-28 12:55
> It seems likely that in the future only more packages will make decisions based on cpu features and more features will be introduced.

I like the current situation because it keeps this from proliferating too badly. That said, it would be fine to factor into an internal/cpufeature package too, provided (1) is remains unavailable outside the standard library, and (2) it remains a tiny amount of code.

**Comment by mundaym** [comment] 2017-03-28 15:40
@minux suggested something similar in https://github.com/golang/go/issues/15403.

**Comment by rsc** [comment] 2017-03-28 15:56
Duplicate of #15403, thanks @mundaym.

**Comment by martisch** [comment] 2017-03-28 15:57
@mundaym thanks for the pointer, totally missed that, will continue there.

**Closed by rsc** 2017-03-28 15:56 UTC
