### ISSUE TITLE
vendor spec: package visibility

### ISSUE THREAD

**Issue by dsnet** [golang/go#14031] opened 2016-01-20 05:56 UTC
*Copying from golang-dev*

The [vendor specification](https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit) doesn't seem to speak much about the visibility of the vendored packages. Thus, should vendor be treated in similar ways to internal?

As it currently is, the following program compiles under go1.6beta2 (with the vendor experiment on):
```go
package main

import "vendor/golang.org/x/net/http2/hpack"

func main() {
	hpack.NewEncoder(nil)
}
```

Is this expected behavior? It seems kind of odd that I can import hpack as part of the "standard" library.

This is related to #13961 and #13929.

**Comment by mdempsky** [comment] 2016-01-21 18:56
https://golang.org/s/go15vendor says "The short form must always be used: no import path can contain “/vendor/” explicitly."  That seems to clearly disallow importing "vendor/golang.org/x/net/http2/hpack" to me.

**Comment by dsnet** [comment] 2016-01-21 18:56
Do you think that maybe this should be thought about for Go1.6? Personally, this issue doesn't affect me, but if we release Go1.6 with GO15VENDOREXPERIMENT enabled by default, then it will probably be harder to change specification related things in Go1.7 when the impact becomes wider.

**Comment by dsnet** [comment] 2016-01-21 18:58
@mdempsky, you're right. I think that does make it pretty clear that vendor should not be visible then.

**Comment by cespare** [comment] 2016-01-21 19:34
This really seems like a bug that should be fixed for 1.6.

Note that it happens with non-stdlib vendored packages as well, so moving vendor to internal in the stdlib for 1.6 doesn't hide the issue completely.

**Comment by bradfitz** [comment] 2016-01-21 19:36
Over to @rsc...

**Comment by cespare** [comment] 2016-01-21 19:54
I think this only happens when you use `go run` (or `go build x.go`), and not when building a real package.

**Comment by conslo** [comment] 2016-01-21 20:51
I can confirm @cespare on this, I can build or run the file directly, but I can't build it like a package:
![image](https://cloud.githubusercontent.com/assets/450860/12494181/ab91491c-c03d-11e5-9cc7-8bbda959a03a.png)
(this is on OSX, with 1.6beta2)

**Comment by rsc** [comment] 2016-01-24 04:48
Thanks for the report. 
Duplicate of #12217, fixed by https://golang.org/cl/18645 shortly after Go 1.6 beta 2 was issued.

**Closed by rsc** 2016-01-24 04:48 UTC
