### ISSUE TITLE
x/net/nettest: TestTestConn/UnixPipe failures on darwin/amd64

### ISSUE THREAD

**Issue by dmitshur** [golang/go#54272] opened 2022-08-04 22:42 UTC
```
--- FAIL: TestTestConn (0.53s)
    --- FAIL: TestTestConn/UnixPipe (0.13s)
        --- FAIL: TestTestConn/UnixPipe/BasicIO (0.00s)
            conntest.go:32: unable to make pipe: listen unix /var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-amd64-10_15/tmp/go-nettest2510121687: bind: invalid argument
        --- FAIL: TestTestConn/UnixPipe/PingPong (0.00s)
            conntest.go:33: unable to make pipe: listen unix /var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-amd64-10_15/tmp/go-nettest2705750332: bind: invalid argument
        --- FAIL: TestTestConn/UnixPipe/RacyRead (0.00s)
            conntest.go:34: unable to make pipe: listen unix /var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-amd64-10_15/tmp/go-nettest1491539286: bind: invalid argument
        --- FAIL: TestTestConn/UnixPipe/RacyWrite (0.00s)
            conntest.go:35: unable to make pipe: listen unix /var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-amd64-10_15/tmp/go-nettest2701222275: bind: invalid argument
        --- FAIL: TestTestConn/UnixPipe/WriteTimeout (0.00s)
            conntest.go:37: unable to make pipe: listen unix /var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-amd64-10_15/tmp/go-nettest1157205681: bind: invalid argument
        --- FAIL: TestTestConn/UnixPipe/PastTimeout (0.00s)
            conntest.go:38: unable to make pipe: listen unix /var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-amd64-10_15/tmp/go-nettest3192360749: bind: invalid argument
        --- FAIL: TestTestConn/UnixPipe/FutureTimeout (0.00s)
            conntest.go:40: unable to make pipe: listen unix /var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-amd64-10_15/tmp/go-nettest1770402664: bind: invalid argument
        --- FAIL: TestTestConn/UnixPipe/CloseTimeout (0.00s)
            conntest.go:41: unable to make pipe: listen unix /var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-amd64-10_15/tmp/go-nettest4168269121: bind: invalid argument
        --- FAIL: TestTestConn/UnixPipe/ConcurrentMethods (0.00s)
            conntest.go:42: unable to make pipe: listen unix /var/folders/kh/5zzynz152r94t18yzstnrwx80000gn/T/workdir-host-darwin-amd64-10_15/tmp/go-nettest188536879: bind: invalid argument
FAIL
FAIL	golang.org/x/net/nettest	0.872s
```

- [2022-08-03T19:52:27-0bcc04d-f28fa95/darwin-amd64-10_14](https://build.golang.org/log/39fe6394f749b428ed2a1fc0cbc320543fb83241)
- [2022-08-03T19:52:27-0bcc04d-f28fa95/darwin-amd64-10_15](https://build.golang.org/log/c07c10a95670de656f2d1041d556008c9bb14af4)

**Comment by bcmills** [comment] 2022-10-04 19:38
Duplicate of #54416

**Closed by bcmills** 2022-10-04 19:38 UTC
Labels: NeedsInvestigation
