### ISSUE TITLE
runtime: fatal error: unexpected signal during runtime execution inside gcmarkwb_m

### ISSUE THREAD

**Issue by davecheney** [golang/go#10664] opened 2015-05-01 23:22 UTC
Spotted on the dashboard, from freebsd-386, http://build.golang.org/log/57659ae3bfad2299f82348b400aa9528ad20d8f6

```
fatal error: unexpected signal during runtime execution
[signal 0xa code=0xc addr=0x2832e000 pc=0x8054f6b]

runtime stack:
runtime.throw(0x8249428, 0x2a)
	/tmp/buildlet-scatch781387312/go/src/runtime/panic.go:543 +0x79
runtime.sigpanic()
	/tmp/buildlet-scatch781387312/go/src/runtime/sigpanic_unix.go:12 +0x50
runtime.gcmarkwb_m(0x3841459c, 0x583ef960)
	/tmp/buildlet-scatch781387312/go/src/runtime/mbarrier.go:73 +0xab
runtime.writebarrierptr_nostore1.func1()
	/tmp/buildlet-scatch781387312/go/src/runtime/mbarrier.go:100 +0x111
runtime.systemstack(0x38421f60)
	/tmp/buildlet-scatch781387312/go/src/runtime/asm_386.s:283 +0x77
runtime.writebarrierptr_nostore1(0x3841459c, 0x583ef960)
	/tmp/buildlet-scatch781387312/go/src/runtime/mbarrier.go:101 +0x50
runtime.writebarrierptr(0x3841459c, 0x583ef960)
	/tmp/buildlet-scatch781387312/go/src/runtime/mbarrier.go:124 +0x5b
runtime.acquirep(0x41a8b400)
	/tmp/buildlet-scatch781387312/go/src/runtime/proc1.go:2793 +0x6e
runtime.stoplockedm()
	/tmp/buildlet-scatch781387312/go/src/runtime/proc1.go:1286 +0x11e
runtime.schedule()
	/tmp/buildlet-scatch781387312/go/src/runtime/proc1.go:1577 +0x5d
runtime.goschedImpl(0x383ef080)
	/tmp/buildlet-scatch781387312/go/src/runtime/proc1.go:1700 +0xf1
runtime.gosched_m(0x383ef080)
	/tmp/buildlet-scatch781387312/go/src/runtime/proc1.go:1708 +0x33
runtime.mcall(0x38421fec)
	/tmp/buildlet-scatch781387312/go/src/runtime/asm_386.s:210 +0x43

goroutine 62 [runnable, locked to thread]:
runtime.Gosched()
	/tmp/buildlet-scatch781387312/go/src/runtime/proc.go:166 +0x10 fp=0x3840afd0 sp=0x3840afc8
runtime/pprof_test.TestTraceStress.func4(0x41a9d140)
	/tmp/buildlet-scatch781387312/go/src/runtime/pprof/trace_test.go:141 +0x8f fp=0x3840afe8 sp=0x3840afd0
runtime.goexit()
	/tmp/buildlet-scatch781387312/go/src/runtime/asm_386.s:1636 +0x1 fp=0x3840afec sp=0x3840afe8
created by runtime/pprof_test.TestTraceStress
	/tmp/buildlet-scatch781387312/go/src/runtime/pprof/trace_test.go:144 +0x36f

goroutine 1 [chan receive]:
testing.RunTests(0x8263e28, 0x82fe260, 0xe, 0xe, 0x583ef001)
	/tmp/buildlet-scatch781387312/go/src/testing/testing.go:561 +0x875
testing.(*M).Run(0x41ab1f9c, 0x20)
	/tmp/buildlet-scatch781387312/go/src/testing/testing.go:490 +0x65
main.main()
	runtime/pprof/_test/_testmain.go:82 +0xfd

goroutine 58 [runnable]:
runtime/pprof_test.TestTraceStress(0x38403f20)
	/tmp/buildlet-scatch781387312/go/src/runtime/pprof/trace_test.go:149 +0x3ad
testing.tRunner(0x38403f20, 0x82fe2e4)
	/tmp/buildlet-scatch781387312/go/src/testing/testing.go:452 +0x8c
created by testing.RunTests
	/tmp/buildlet-scatch781387312/go/src/testing/testing.go:560 +0x843

goroutine 60 [syscall]:
syscall.Syscall(0x5, 0x3840a7cf, 0x1, 0x1, 0x83024e0, 0x83024e0, 0x80857da)
	/tmp/buildlet-scatch781387312/go/src/syscall/asm_freebsd_386.s:20 +0x5
syscall.read(0x5, 0x3840a7cf, 0x1, 0x1, 0x3f064070, 0x0, 0x0)
	/tmp/buildlet-scatch781387312/go/src/syscall/zsyscall_freebsd_386.go:890 +0x50
syscall.Read(0x5, 0x3840a7cf, 0x1, 0x1, 0x3844f500, 0x0, 0x0)
	/tmp/buildlet-scatch781387312/go/src/syscall/syscall_unix.go:160 +0x46
os.(*File).read(0x38412620, 0x3840a7cf, 0x1, 0x1, 0x3f064070, 0x0, 0x0)
	/tmp/buildlet-scatch781387312/go/src/os/file_unix.go:211 +0x6c
os.(*File).Read(0x38412620, 0x3840a7cf, 0x1, 0x1, 0x0, 0x0, 0x0)
	/tmp/buildlet-scatch781387312/go/src/os/file.go:95 +0x6c
runtime/pprof_test.TestTraceStress.func3(0x38412620, 0x41a9d140, 0x3846f5c0)
	/tmp/buildlet-scatch781387312/go/src/runtime/pprof/trace_test.go:120 +0x55
created by runtime/pprof_test.TestTraceStress
	/tmp/buildlet-scatch781387312/go/src/runtime/pprof/trace_test.go:123 +0x1fb

goroutine 41 [select (no cases)]:
runtime/pprof_test.TestTraceSymbolize.func1()
	/tmp/buildlet-scatch781387312/go/src/runtime/pprof/trace_stack_test.go:38 +0x18
created by runtime/pprof_test.TestTraceSymbolize
	/tmp/buildlet-scatch781387312/go/src/runtime/pprof/trace_stack_test.go:39 +0x174

goroutine 42 [chan send (nil chan)]:
runtime/pprof_test.TestTraceSymbolize.func2()
	/tmp/buildlet-scatch781387312/go/src/runtime/pprof/trace_stack_test.go:42 +0x38
created by runtime/pprof_test.TestTraceSymbolize
	/tmp/buildlet-scatch781387312/go/src/runtime/pprof/trace_stack_test.go:43 +0x189

goroutine 43 [chan receive (nil chan)]:
runtime/pprof_test.TestTraceSymbolize.func3()
	/tmp/buildlet-scatch781387312/go/src/runtime/pprof/trace_stack_test.go:46 +0x30
created by runtime/pprof_test.TestTraceSymbolize
	/tmp/buildlet-scatch781387312/go/src/runtime/pprof/trace_stack_test.go:47 +0x19e

goroutine 61 [trace reader (blocked)]:
runtime.ReadTrace(0x0, 0x0, 0x0)
	/tmp/buildlet-scatch781387312/go/src/runtime/trace.go:318 +0x1bf
runtime/pprof.StartTrace.func1(0x584ff998, 0x38403f80)
	/tmp/buildlet-scatch781387312/go/src/runtime/pprof/pprof.go:629 +0x1b
created by runtime/pprof.StartTrace
	/tmp/buildlet-scatch781387312/go/src/runtime/pprof/pprof.go:635 +0x6a

goroutine 59 [chan receive]:
runtime/pprof_test.TestTraceStress.func1(0x41a9d140, 0x3846f5c0)
	/tmp/buildlet-scatch781387312/go/src/runtime/pprof/trace_test.go:104 +0x32
created by runtime/pprof_test.TestTraceStress
	/tmp/buildlet-scatch781387312/go/src/runtime/pprof/trace_test.go:106 +0x9d
FAIL	runtime/pprof	7.180s
```

**Comment by davecheney** [comment] 2015-05-01 23:23
Also, from a windows-386 builder, http://build.golang.org/log/d9c3269c44d466785b429058b7aca08577ee00cf

```
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0x1ef1120 pc=0x40dce1]

runtime stack:
runtime.throw(0x60e588, 0x2a)
	C:/workdir/go/src/runtime/panic.go:543 +0x7f
runtime.sigpanic()
	C:/workdir/go/src/runtime/signal_windows.go:157 +0x5c
runtime.gcmarkwb_m(0x3284000c, 0x32840218)
	C:/workdir/go/src/runtime/mbarrier.go:73 +0xb1
runtime.writebarrierptr_nostore1.func1()
	C:/workdir/go/src/runtime/mbarrier.go:100 +0x117
runtime.systemstack(0x3283fe14)
	C:/workdir/go/src/runtime/asm_386.s:283 +0x81
runtime.writebarrierptr_nostore1(0x3284000c, 0x32840218)
	C:/workdir/go/src/runtime/mbarrier.go:101 +0x56
runtime.writebarrierptr(0x3284000c, 0x32840218)
	C:/workdir/go/src/runtime/mbarrier.go:124 +0x5b
runtime.traceEvent(0x6, 0xffffffff, 0x0, 0x0, 0x0)
	C:/workdir/go/src/runtime/trace.go:507 +0x5c3
runtime.traceProcStop(0x1b65b400)
	C:/workdir/go/src/runtime/trace.go:741 +0x69
runtime.releasep(0xffffffff)
	C:/workdir/go/src/runtime/proc1.go:2834 +0x95
runtime.startlockedm(0x11fc4f20)
	C:/workdir/go/src/runtime/proc1.go:1305 +0x82
runtime.schedule()
	C:/workdir/go/src/runtime/proc1.go:1633 +0x234
runtime.park_m(0x11fc4210)
	C:/workdir/go/src/runtime/proc1.go:1685 +0x166
runtime.mcall(0x0)
	C:/workdir/go/src/runtime/asm_386.s:210 +0x47

goroutine 1 [chan receive]:
testing.RunTests(0x628f5c, 0x6c42e0, 0xe, 0xe, 0x2f0001)
	C:/workdir/go/src/testing/testing.go:561 +0x87b
testing.(*M).Run(0x12438f9c, 0x20)
	C:/workdir/go/src/testing/testing.go:490 +0x6b
main.main()
	runtime/pprof/_test/_testmain.go:82 +0x103

goroutine 58 [runnable]:
runtime/pprof_test.TestTraceStress(0x11ff7f80)
	C:/workdir/go/src/runtime/pprof/trace_test.go:149 +0x3b3
testing.tRunner(0x11ff7f80, 0x6c4364)
	C:/workdir/go/src/testing/testing.go:452 +0x92
created by testing.RunTests
	C:/workdir/go/src/testing/testing.go:560 +0x849

goroutine 59 [chan receive]:
runtime/pprof_test.TestTraceStress.func1(0x1242bc00, 0x1b66b2a0)
	C:/workdir/go/src/runtime/pprof/trace_test.go:104 +0x38
created by runtime/pprof_test.TestTraceStress
	C:/workdir/go/src/runtime/pprof/trace_test.go:106 +0xa3

goroutine 41 [select (no cases)]:
runtime/pprof_test.TestTraceSymbolize.func1()
	C:/workdir/go/src/runtime/pprof/trace_stack_test.go:38 +0x1e
created by runtime/pprof_test.TestTraceSymbolize
	C:/workdir/go/src/runtime/pprof/trace_stack_test.go:39 +0x17a

goroutine 42 [chan send (nil chan)]:
runtime/pprof_test.TestTraceSymbolize.func2()
	C:/workdir/go/src/runtime/pprof/trace_stack_test.go:42 +0x3e
created by runtime/pprof_test.TestTraceSymbolize
	C:/workdir/go/src/runtime/pprof/trace_stack_test.go:43 +0x18f

goroutine 43 [chan receive (nil chan)]:
runtime/pprof_test.TestTraceSymbolize.func3()
	C:/workdir/go/src/runtime/pprof/trace_stack_test.go:46 +0x36
created by runtime/pprof_test.TestTraceSymbolize
	C:/workdir/go/src/runtime/pprof/trace_stack_test.go:47 +0x1a4

goroutine 62 [runnable, locked to thread]:
runtime.Gosched()
	C:/workdir/go/src/runtime/proc.go:166 +0x10
runtime/pprof_test.TestTraceStress.func4(0x1242bc00)
	C:/workdir/go/src/runtime/pprof/trace_test.go:141 +0xa1
created by runtime/pprof_test.TestTraceStress
	C:/workdir/go/src/runtime/pprof/trace_test.go:144 +0x375

goroutine 61 [trace reader (blocked)]:
runtime.ReadTrace(0x0, 0x0, 0x0)
	C:/workdir/go/src/runtime/trace.go:318 +0x1d1
runtime/pprof.StartTrace.func1(0x32080d18, 0x1b616000)
	C:/workdir/go/src/runtime/pprof/pprof.go:629 +0x21
created by runtime/pprof.StartTrace
	C:/workdir/go/src/runtime/pprof/pprof.go:635 +0x70

goroutine 60 [syscall, locked to thread]:
syscall.Syscall6(0x755c3e93, 0x5, 0x184, 0x12435fcf, 0x1, 0x12435f38, 0x0, 0x0, 0x0, 0x40bd91, ...)
	C:/workdir/go/src/runtime/syscall_windows.go:139 +0x4b
syscall.ReadFile(0x184, 0x12435fcf, 0x1, 0x1, 0x12435f38, 0x0, 0x0, 0x0)
	C:/workdir/go/src/syscall/zsyscall_windows.go:283 +0xa0
syscall.Read(0x184, 0x12435fcf, 0x1, 0x1, 0x9a, 0x0, 0x0)
	C:/workdir/go/src/syscall/syscall_windows.go:286 +0x64
os.(*File).read(0x11fce668, 0x12435fcf, 0x1, 0x1, 0x0, 0x0, 0x0)
	C:/workdir/go/src/os/file_windows.go:300 +0x106
os.(*File).Read(0x11fce668, 0x12435fcf, 0x1, 0x1, 0xfde8, 0x0, 0x0)
	C:/workdir/go/src/os/file.go:95 +0x72
runtime/pprof_test.TestTraceStress.func3(0x11fce668, 0x1242bc00, 0x1b66b2a0)
	C:/workdir/go/src/runtime/pprof/trace_test.go:120 +0x5b
created by runtime/pprof_test.TestTraceStress
	C:/workdir/go/src/runtime/pprof/trace_test.go:123 +0x201
FAIL	runtime/pprof	7.707s
```

**Comment by mikioh** [comment] 2015-05-02 05:35
#10212 and #10564?

**Comment by rsc** [comment] 2015-06-08 06:15
Duplicate of #10212.

**Closed by rsc** 2015-06-08 06:15 UTC
Labels: OS-FreeBSD
