### ISSUE TITLE
all.bash fails on master on Mac OS

### ISSUE THREAD

**Issue by MichelHollands** [golang/go#36392] opened 2020-01-05 10:25 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
It happens on master.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mholland/Library/Caches/go-build"
GOENV="/Users/mholland/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mholland/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mholland/git/go/src/cmd/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ft/dg1pz2zj0mb9bqbhp3r1q77r0000gq/T/go-build705702634=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Ran ./all.bash in the go/src directory.
The test 'TestIssue33979' fails:

<pre>
ok  	cmd/internal/src	0.009s
ok  	cmd/internal/test2json	0.083s
--- FAIL: TestIssue33979 (0.51s)
    link_test.go:250: got:
        main(__TEXT/__text): relocation target undefined not defined
        want:
        main(.text): relocation target undefined not defined
FAIL
FAIL	cmd/link	4.131s
ok  	cmd/link/internal/ld	7.899s
ok  	cmd/link/internal/sym	0.008s
</pre>

The problem seems to be introduced in commit 8adc1e00aa1a92a85b9d6f3526419d49dd7859dd . For the previous commit all the tests pass.

### What did you expect to see?
All tests to pass

### What did you see instead?
See above.

**Comment by agnivade** [comment] 2020-01-05 14:08
Duplicate of https://github.com/golang/go/issues/36389.

**Closed by agnivade** 2020-01-05 14:08 UTC
