### ISSUE TITLE
x/tools/gopls: no diagnostics received for initially empty files (sometimes)

### ISSUE THREAD

**Issue by myitcv** [golang/go#39646] opened 2020-06-17 11:19 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +d286e61b67 Mon Jun 15 23:29:23 2020 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20200617042924-7f3f4b10a808
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.0.0-20200617042924-7f3f4b10a808
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/myitcv/gostuff/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build538522998=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`govim` has a test that verifies we receive expected diagnostics in the case where files are initially empty on disk, but subsequently get populated with content in the editor.

https://github.com/govim/govim/blob/e2a1802131f331832d667736aa27f023636f0c3a/cmd/govim/testdata/scenario_default/quickfix_empty_files.txt

Recently (apologies, I can't be any more specific than saying "in the last 2-3 weeks) we have started to see, and continue to see, a small number of flakes in this test. 

In a normal run of this test we expect a set of diagnostics; when we see these flakes, we don't see any diagnostics.

Here is a `gopls` log file from a _passing_ test run. Notice the `DidChange` notifications, as well as the `PublishDiagnostics` notifications: [gopls.log](https://github.com/golang/go/files/4792091/gopls.log)

And here is the `gopls` log from a _failing_ test run. Notice the `DidChange` notifications, but no `PublishDiagnostics` notifications: [gopls.log](https://github.com/golang/go/files/4792100/gopls.log)

### What did you expect to see?

A consistently passing test.

### What did you see instead?

Flakes as described above.

---

cc @stamblerre @findleyr 

FYI @leitzler

**Comment by myitcv** [comment] 2020-06-25 09:27
FYI we're still seeing ~1 failure per day in the `govim` `gopls@master` build runs.

**Comment by stamblerre** [comment] 2020-06-25 22:39
Thanks for the report! I am going to convert this into a gopls regression test and see if I can reproduce the issue.

**Comment by stamblerre** [comment] 2020-06-26 00:14
I tried to reproduce the test as carefully as possible in my CL, but I haven't been able to trigger the failure. The issue is that the new files are getting treated like `command-line-arguments` packages, which should only happen when they are empty. I wonder if we will see similar flakes on the builders.

In the logs, `command-line-arguments` in the packages.Load at snapshot 3, which is the point at which `p/p.go` should be in a good state. I don't see any packages.Load results for snapshot 1, which is when you might expect a `command-line-arguments` result. One more thing to try would be adding an analogous go/packages test.

**Comment by myitcv** [comment] 2020-07-30 04:01
We've just seen this again using 6467de6f59a7. Same situation as described before, logs as follows:

* [fail.log](https://github.com/golang/go/files/4998687/fail.log)
* [pass.log](https://github.com/golang/go/files/4998688/pass.log)

**Comment by stamblerre** [comment] 2020-09-09 03:50
@myitcv: Sorry for the delay on this. Are you still seeing this with `gopls` at master?

**Comment by myitcv** [comment] 2020-09-10 07:52
@stamblerre - I've just submitted https://github.com/govim/govim/commit/c8c4a6f83808a8b9fab26293c3ed508da6b39d77 to verify.

**Comment by myitcv** [comment] 2020-09-10 09:57
This appears to still be flakey using 44a2922940c2: we had two flakes in https://github.com/govim/govim/actions/runs/247768908

**Comment by stamblerre** [comment] 2020-09-10 14:24
Is there a way to see the `gopls` logs associated with these failures?

**Comment by stamblerre** [comment] 2020-09-10 14:27
Note to self--from the earlier logs, the pass case has packages.Loads at snapshots 0, 6, and 12, whereas fail also has a load at snapshot 3. The regression test currently loads at 0, 3, 6, 9, and 12.

**Comment by leitzler** [comment] 2020-09-10 17:50
> Is there a way to see the `gopls` logs associated with these failures?

They are available in the artifacts, for example (looking at the run Paul linked above) the artifact file:
* ubuntu-latest_go1.13.12_vim_v8.2.0931.zip

With the failed test found in the archive as:
Test `TestScripts/scenario_default/quickfix_empty_files` =>
Log `govim/cmd/govim/scenario_default/script-quickfix_empty_files/_tmp/gopls.log`

**Comment by stamblerre** [comment] 2020-11-11 21:51
I expect that these test failures were caused by the go/packages overlay support, but there is now native support for overlays in 1.16.

@leitzler, @myitcv: Do you know if this test is fixed with Go 1.16?

**Comment by myitcv** [comment] 2020-11-12 08:03
We will setup a tip instance in our build matrix and try it out.

**Comment by stamblerre** [comment] 2021-02-10 21:41
Closing this issue, as there hasn't been any activity on it for several months.
@myitcv: Please reopen this if it still remains a problem.

**Closed by stamblerre** 2021-02-10 21:41 UTC
Labels: Tools, WaitingForInfo, gopls
