### ISSUE TITLE
context: Clarify desired key type

### ISSUE THREAD

**Issue by mcandre** [golang/go#30408] opened 2019-02-26 16:29 UTC
Hi, I am trying to resolve some interesting linter warnings around context key types. For some reason, ordinary strings are being discouraged as context key types, e.g. by `golint`.

One specific recommendation online is to use `interface{}` instead. Is this a good idea?

```go
var EmailClientKey interface{} = "email_client"
```

Could we use the Go type system to make this easier for the user? Perhaps alias `interface{}` as a `ContextKey` type, and require in the `Context` API methods that the keys are passed in with the `ContextKey` type.

**Comment by mvdan** [comment] 2019-02-26 18:25
Duplicate of https://github.com/golang/go/issues/17826? If you think the documentation is lacking, please point out what is missing.

**Comment by bcmills** [comment] 2019-02-27 17:51
The current documentation says: 
> The provided key must be comparable and should not be of type string or any other built-in type to avoid collisions between packages using context.

So using a string value is clearly out, even if you assign it to a variable of type `interface{}`

**Comment by bcmills** [comment] 2019-02-27 19:42
> Perhaps alias `interface{}` as a `ContextKey` type, and require in the `Context` API methods that the keys are passed in with the `ContextKey` type.

Aliasing anything to `interface{}` makes it exactly as weak as `interface{}` from a type perspective: anything is assignable to it, so anything can be passed as it.

**Comment by bcmills** [comment] 2019-02-27 19:43
Closing as a dup of #17826.

**Closed by bcmills** 2019-02-27 19:43 UTC

**Comment by mcandre** [comment] 2019-03-02 18:12
In that case, have the compiler reject string keys for context API calls
