### ISSUE TITLE
x/review/git-codereview: failures with "invalid pending output" due to missing Gerrit metadata

### ISSUE THREAD

**Issue by bcmills** [golang/go#50576] opened 2022-01-12 16:48 UTC
The `x/review/git-codereview` tests for the `pending` command occasionally fail due to missing Gerrit metadata for some of the CLs, particularly on slower builders. Looks like at least a missed error check, since the error that causes the truncated metadata is not present in the logs.

`greplogs --dashboard -md -l -e 'invalid pending output' --since=2020-01-01`

<details>

[2022-01-12T15:53:47-b04b288-6e8b7e4/netbsd-386-9_0-n2](https://build.golang.org/log/dfb5a2e12569592290c88eb27cdbfe725eacfc3b)
```
    pending_test.go:396: invalid pending output:
        work REVHASH..REVHASH (current branch)
        + REVHASH v14
        + REVHASH v13
        + REVHASH v12
        + REVHASH v11
        + REVHASH v10
        + REVHASH v9
        + REVHASH v8
        + REVHASH v7
        + REVHASH v6
        + REVHASH v5
        + REVHASH v4
        + REVHASH v3
        + REVHASH v2
        + REVHASH v1
        + REVHASH msg
        
        
        want:
        work REVHASH..REVHASH (current branch, all mailed)
        + REVHASH v14 (CL 1234 -2 +1, mailed)
        + REVHASH v13 (CL 1234 -2 +1, mailed)
        + REVHASH v12 (CL 1234 -2 +1, mailed)
        + REVHASH v11 (CL 1234 -2 +1, mailed)
        + REVHASH v10 (CL 1234 -2 +1, mailed)
        + REVHASH v9 (CL 1234 -2 +1, mailed)
        + REVHASH v8 (CL 1234 -2 +1, mailed)
        + REVHASH v7 (CL 1234 -2 +1, mailed)
        + REVHASH v6 (CL 1234 -2 +1, mailed)
        + REVHASH v5 (CL 1234 -2 +1, mailed)
        + REVHASH v4 (CL 1234 -2 +1, mailed)
        + REVHASH v3 (CL 1234 -2 +1, mailed)
        + REVHASH v2 (CL 1234 -2 +1, mailed)
        + REVHASH v1 (CL 1234 -2 +1, mailed)
        + REVHASH msg (CL 1234 -2 +1, mailed, submitted)
```

[2021-12-07T20:14:56-b8ead20-b37a539/solaris-amd64-oraclerel](https://build.golang.org/log/b7b5d3c15d24b18edb8800486050c1c9b3ff42a8)
```
    pending_test.go:396: invalid pending output:
        work REVHASH..REVHASH (current branch)
        + REVHASH v14 (CL 1234 -2 +1, mailed)
        + REVHASH v13 (CL 1234 -2 +1, mailed)
        + REVHASH v12 (CL 1234 -2 +1, mailed)
        + REVHASH v11 (CL 1234 -2 +1, mailed)
        + REVHASH v10 (CL 1234 -2 +1, mailed)
        + REVHASH v9 (CL 1234 -2 +1, mailed)
        + REVHASH v8 (CL 1234 -2 +1, mailed)
        + REVHASH v7 (CL 1234 -2 +1, mailed)
        + REVHASH v6 (CL 1234 -2 +1, mailed)
        + REVHASH v5 (CL 1234 -2 +1, mailed)
        + REVHASH v4
        + REVHASH v3
        + REVHASH v2
        + REVHASH v1
        + REVHASH msg (CL 1234 -2 +1, submitted)
        
        
        want:
        work REVHASH..REVHASH (current branch, all mailed)
        + REVHASH v14 (CL 1234 -2 +1, mailed)
        + REVHASH v13 (CL 1234 -2 +1, mailed)
        + REVHASH v12 (CL 1234 -2 +1, mailed)
        + REVHASH v11 (CL 1234 -2 +1, mailed)
        + REVHASH v10 (CL 1234 -2 +1, mailed)
        + REVHASH v9 (CL 1234 -2 +1, mailed)
        + REVHASH v8 (CL 1234 -2 +1, mailed)
        + REVHASH v7 (CL 1234 -2 +1, mailed)
        + REVHASH v6 (CL 1234 -2 +1, mailed)
        + REVHASH v5 (CL 1234 -2 +1, mailed)
        + REVHASH v4 (CL 1234 -2 +1, mailed)
        + REVHASH v3 (CL 1234 -2 +1, mailed)
        + REVHASH v2 (CL 1234 -2 +1, mailed)
        + REVHASH v1 (CL 1234 -2 +1, mailed)
        + REVHASH msg (CL 1234 -2 +1, mailed, submitted)
```

[2021-11-05T21:18:28-39ade5b-4c7cafd/dragonfly-amd64](https://build.golang.org/log/7aa4d403919c4fdd3c97352f1e1b794dc01ea039)
```
    pending_test.go:396: invalid pending output:
        work REVHASH..REVHASH (current branch)
        + REVHASH v14
        + REVHASH v13
        + REVHASH v12
        + REVHASH v11
        + REVHASH v10
        + REVHASH v9
        + REVHASH v8
        + REVHASH v7
        + REVHASH v6
        + REVHASH v5
        + REVHASH v4
        + REVHASH v3
        + REVHASH v2
        + REVHASH v1
        + REVHASH msg (CL 1234 -2 +1, mailed, submitted)
        
        
        want:
        work REVHASH..REVHASH (current branch, all mailed)
        + REVHASH v14 (CL 1234 -2 +1, mailed)
        + REVHASH v13 (CL 1234 -2 +1, mailed)
        + REVHASH v12 (CL 1234 -2 +1, mailed)
        + REVHASH v11 (CL 1234 -2 +1, mailed)
        + REVHASH v10 (CL 1234 -2 +1, mailed)
        + REVHASH v9 (CL 1234 -2 +1, mailed)
        + REVHASH v8 (CL 1234 -2 +1, mailed)
        + REVHASH v7 (CL 1234 -2 +1, mailed)
        + REVHASH v6 (CL 1234 -2 +1, mailed)
        + REVHASH v5 (CL 1234 -2 +1, mailed)
        + REVHASH v4 (CL 1234 -2 +1, mailed)
        + REVHASH v3 (CL 1234 -2 +1, mailed)
        + REVHASH v2 (CL 1234 -2 +1, mailed)
        + REVHASH v1 (CL 1234 -2 +1, mailed)
        + REVHASH msg (CL 1234 -2 +1, mailed, submitted)
```

[2021-10-06T23:01:01-39ade5b-4ffa2f1/dragonfly-amd64](https://build.golang.org/log/aabecb83762910a5195c365df9f703f30142a2d8)
```
    pending_test.go:260: invalid pending output:
        work REVHASH..REVHASH (current branch, 1 behind)
        + REVHASH
        	msg
        
        	Change-Id: I123456789
        
        	Files in this change:
        		file
        
        
        want:
        work REVHASH..REVHASH (current branch, all mailed, all submitted, 1 behind)
        + REVHASH http://127.0.0.1:PORT/1234 (mailed, submitted)
        	msg
        
        	Change-Id: I123456789
        
        	Code-Review:
        		+1 Grace Emlin
        		-2 George Opher
        	Other-Label:
        		+2 The Owner
        	Files in this change:
        		file
```

</details>

**Comment by bcmills** [comment] 2022-04-07 18:33
`greplogs --dashboard -md -l -e 'invalid pending output' --since=2022-01-13`

[2022-01-21T00:39:55-b04b288-32636cd/netbsd-386-9_0](https://build.golang.org/log/bed2e6f5c790addb870f8b5e798a892aedd0c3cd)

**Comment by bcmills** [comment] 2022-04-07 18:35
Marking as release-blocker via #11811.

Although this hasn't failed on any first-class ports yet, the diversity of ports on which it has occurred (NetBSD, Dragonfly, and Solaris so far) suggests that it is not a platform-specific failure mode.

**Comment by rsc** [comment] 2022-04-11 18:09
That test is using a fake Gerrit server (type gerritServer).
The map it serves from is protected by a sync.Mutex.

The fake server does run on a real localhost network port.
I wonder if we are seeing the effect of flaky network dialing.
I can try dialing a second time if the first one fails, but is that a good fix?

**Comment by bcmills** [comment] 2022-04-22 14:48
#49899 may be related; one of those failures also triggered the new logging. (See https://github.com/golang/go/issues/49899#issuecomment-1106590393.)

**Comment by mknyszek** [comment] 2022-05-18 16:17
@rsc What are the next steps here? This is still a release blocker because it's causing builder failures.

**Comment by bcmills** [comment] 2022-06-01 18:37
`greplogs -l -e 'invalid pending output' --since=2022-04-15`
[2022-05-10T21:56:21-ae62a0b-bda9da8/netbsd-amd64-9_0](https://build.golang.org/log/2bdbb8808abf067775bb758a3071df58977c04d4)
[2022-05-06T21:07:37-ae62a0b-ac39dbd/dragonfly-amd64](https://build.golang.org/log/c5161a3244fc3f26cf0d973a37d59e1227386173)

**Comment by rsc** [comment] 2022-06-01 20:43
I updated my fetchlogs and greplogs and did 

```
fetchlogs -n 1000 -repo review
fetchlogs -n 1000 
greplogs -l -e 'invalid pending output' 
```

and am not getting any hits. I'm holding it wrong, but how?

**Comment by bcmills** [comment] 2022-06-01 21:11
Yep, that one matches #49899, which may or may not share a root cause (not obvious to me either way).

**Comment by rsc** [comment] 2022-06-01 23:01
Losing the connection would explain both 'malformed json response' and 'connection reset by peer', so probably these are the same root cause. Of course why a localhost connection would get cut is a mystery.

Looks like the affected systems are dragonfly, netbsd, openbsd, solaris. It's possible the minor BSDs are hitting some common problem that FreeBSD has since fixed (either on the Go side or in the OS). But it's weird to see Solaris in that list. My understanding is that Solaris has a SVR4-derived networking stack, which would be totally different code. Looking forward to seeing the malformed bodies.

**Comment by rsc** [comment] 2022-06-15 17:03
FWIW I did a fetchlogs / greplogs 'git-codereview: fetch' and don't see any new failures in the last two weeks. Also nothing on https://build.golang.org/?repo=golang.org%2fx%2freview. Will have to keep waiting.

**Comment by ianlancetaylor** [comment] 2022-06-24 20:04
Rolling forward to 1.20.  Please comment if you disagree.  Thanks.

**Comment by dmitshur** [comment] 2022-07-15 20:16
I think we're willing to wait a bit longer here, reopening.

**Comment by rsc** [comment] 2022-10-13 21:30
I think this stopped happening, but a variant just happened on #56221. Closing this as a duplicate of #56221.

**Closed by rsc** 2022-10-13 21:30 UTC
Labels: WaitingForInfo, NeedsInvestigation
