### ISSUE TITLE
golang/time: is not detecting timezone changes.

### ISSUE THREAD

**Issue by elbertcastaneda** [golang/go#59941] opened 2023-05-03 04:29 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\user\AppData\Local\go-build
set GOENV=C:\Users\user\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\user\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\user\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.3
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\user\AppData\Local\Temp\go-build3797996638=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

When we change the time-zone or deactivate "Adjust for daylight saving time automatically" in Windows `go` doesn't detect the change in the system Date time with `time.Now()` function.

![golang-timezone-changing-bug](https://user-images.githubusercontent.com/3514681/235832316-743cb4a4-9a59-4641-ac73-47e7ba259625.gif)

### What did you expect to see?

We should see the correct Date and time when we change the timezone or deactivate "Adjust for daylight saving time automatically"

### What did you see instead?

The old date and time the change is not detected by golang.

Note: When we changed the time or date manually the change is detected correctly (as expected with the timezone change or with the change triggered by deactivate "Adjust for daylight saving time automatically")

**Comment by seankhliao** [comment] 2023-05-03 07:43
Duplicate of #28020

**Closed by seankhliao** 2023-05-03 07:43 UTC
