### ISSUE TITLE
x/pkgsite: doc strings on struct fields do not display in Safari

### ISSUE THREAD

**Issue by cpuguy83** [golang/go#45572] opened 2021-04-14 20:46 UTC
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/cpuguy83/dockercfg
 
### What is your user agent?
 

 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
 
### Screenshot
 

 
 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/799078/114776531-6c3aa480-9d27-11eb-85d8-a5f8a59aaa82.png">

Data is present just not showing:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/799078/114776609-85435580-9d27-11eb-9ee9-83b8bda21aae.png">

 
### What did you do?
 

 
Add a doc string to a struct field

e.g.

```
type Foo struct {
  // COMMENT HERE
  Foo string
}
```
 
### What did you expect to see?
 
The comment should show in the doc site.
 
### What did you see instead?

There is whitespace for the comment and the comment data is there, the actual comment does not show up, though.

This is the same on both pkg.go.dev and godoc.org

**Comment by ImJasonH** [comment] 2021-04-14 20:51
FWIW I see this using an older Safari (and on latest Chrome for macOS):

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
```

<img width="755" alt="Screen Shot 2021-04-14 at 4 49 16 PM" src="https://user-images.githubusercontent.com/210737/114777166-5c2fbe80-9d41-11eb-95b2-ca86cc8cff34.png">

**Comment by julieqiu** [comment] 2021-04-14 21:12
I am also unable to reproduce this issue with the same user agent:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
```
![image](https://user-images.githubusercontent.com/5943521/114779468-2cce8100-9d44-11eb-8b2e-9491131d5a67.png)

**Comment by cpuguy83** [comment] 2021-04-14 22:20
Interesting... 

I swear I saw this on iOS as well a little while back, but cannot repro it there anymore.
Knowing this I started messing with addons... 
Turned off an ad blocker (1Blocker) and the problem went away.

**Comment by artyom** [comment] 2021-04-15 17:41
Somewhat relevant: few days ago I almost opened an issue about [http.Cookie](https://golang.org/pkg/net/http/#Cookie) type header not showing up on Safari (the `<h2 id="Cookie">...` node was not rendering at all), but once I loaded the page with content blockers disabled, it rendered fine. I used [Wipr](https://apps.apple.com/ru/app/wipr/id1320666476?l=en&mt=12).

**Comment by julieqiu** [comment] 2021-04-15 17:43
Thanks all for investigating! Closing this issue since there isn't anything actionable on our end.

**Closed by julieqiu** 2021-04-15 17:43 UTC
Labels: NeedsInvestigation, pkgsite
