### ISSUE TITLE
Declared and not used error

### ISSUE THREAD

**Issue by Tusshu** [golang/go#24003] opened 2018-02-21 16:08 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.10 windows/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
Windows 7 Professional
Service Pack 1

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
I get "found declared and not used"
On line 27 I have declared  var found = "no" and later used it in for loop.
If I comment var declaration, I get "undefined found" error where found is used in for loop.
first used bool instead of string but did not work.

Tried on MAC High Sierra with same results

[vartest.txt](https://github.com/golang/go/files/1744659/vartest.txt)

**Comment by dominikh** [comment] 2018-02-21 16:18
Working as intended. The variable is only ever assigned to, never read from. That does not constitute "used".

For asking questions about Go, please see https://github.com/golang/go/wiki/Questions

**Closed by dominikh** 2018-02-21 16:18 UTC
