### ISSUE TITLE
cmd/go: go list -m error is confusing when go.mod lacks module directive

### ISSUE THREAD

**Issue by perillo** [golang/go#37264] opened 2020-02-17 14:31 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14rc1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/manlio/.local/bin"
GOCACHE="/home/manlio/.cache/go-build"
GOENV="/home/manlio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/manlio/.local/lib/go:/home/manlio/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/manlio/sdk/go1.14rc1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/manlio/sdk/go1.14rc1/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build648332856=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.14rc1 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.14rc1
uname -sr: Linux 5.5.4-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.31.
gdb --version: GNU gdb (GDB) 9.1
</pre></details>

### What did you do?

Inside the `HOME` directory:
```
$ go list -m -json
{
	"Path": "command-line-arguments",
	"Main": true
}
```

But if I add a `go.mod` file in a parent directory:
```
$ sudo touch ../go.mod
$ go list -m -json
go: cannot determine module path for source directory /home (outside GOPATH, module path must be specified)

Example usage:
	'go mod init example.com/m' to initialize a v0 or v1 module
	'go mod init example.com/m/v2' to initialize a v2 module

Run 'go help mod init' for more information.
```

This is confusing for two reasons:

 1. My `HOME` directory is also outside `GOPATH
 2. `go list -m` returns the usage message for `go mod init`, and this may confuse newcomers

**Comment by jayconrod** [comment] 2020-02-18 16:21
This is almost the same issue as #35070. The problem is that `go list` is failing to load the `go.mod` file because it doesn't contain a `module` directive. It appears that it's trying to *add* the `module` directive and is failing to infer the module path.

Instead, we should reject a `go.mod` file without a `module` directive with a clear message. This is based on @rsc's comment in [CL 211597](https://go-review.googlesource.com/c/go/+/211597).

Tentatively tagging both issues for 1.15. I expect they will both be fixed by [CL 211597](https://go-review.googlesource.com/c/go/+/211597).

cc @matloob

**Comment by ianlancetaylor** [comment] 2020-06-16 02:51
The CL is marked wait-release, so rolling this issue forward to 1.16.

**Comment by jayconrod** [comment] 2021-01-07 16:51
The error message now looks like this:

```
$ go list -m
go: no module declaration in go.mod. To specify the module path:
	go mod edit -module=example.com/mod
```

**Closed by jayconrod** 2021-01-07 16:51 UTC
Labels: GoCommand, NeedsFix, modules
