### ISSUE TITLE
go module go build -v replace not work

### ISSUE THREAD

**Issue by dapengjun** [golang/go#29317] opened 2018-12-18 05:58 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.4 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
go build -v download from golang/x/net not github.com/golang/net

![1545112538 1](https://user-images.githubusercontent.com/9162928/50134775-a537eb00-02cc-11e9-9ade-6ef499873103.jpg)

![1545112611 1](https://user-images.githubusercontent.com/9162928/50134807-d6182000-02cc-11e9-9ef8-ea27166d997d.jpg)

### What did you expect to see?
go build download from github.com/golang/net

### What did you see instead?
go build download from golang/x/net

**Comment by agnivade** [comment] 2018-12-18 08:33
Duplicate of https://github.com/golang/go/issues/27859 which is fixed in master. Please feel to try with the 1.12 beta which should be out soon.

**Closed by agnivade** 2018-12-18 08:33 UTC
