### ISSUE TITLE
Kubernetes scheduler unit test registry_test Failures with master go

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [golang/go#45697] opened 2021-04-22 11:46 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.17-5daefc5363 Thu Apr 22 01:40:02 2021 +0000 linux/ppc64le
</pre>

### Does this issue reproduce with the latest release?
No

### What operating system and processor architecture are you using (`go env`)?
Linux ppc64le

### What did you do?
Ran kubernetes unit test `pkg/scheduler/framework/runtime/registry_test.go` with golang in master branch.

### What did you expect to see?
The tests should Pass as with stable go
```
[root@rajalakshmi1-workspace kubernetes]# go version
go version go1.16 linux/ppc64le
[root@rajalakshmi1-workspace kubernetes]# make test KUBE_RACE=-race WHAT=./pkg/scheduler/framework/runtime/ 2>&1 | tee pss.log
+++ [0422 09:55:38] Running tests without code coverage
ok      k8s.io/kubernetes/pkg/scheduler/framework/runtime       0.190s
[root@rajalakshmi1-workspace kubernetes]#
```

### What did you see instead?
The following error:
```
--- FAIL: TestMerge (0.00s)
    --- FAIL: TestMerge/valid_Merge (0.00s)
        registry_test.go:158: Merge(). Expected map[pluginFactory1:0x11607ea0 pluginFactory2:0x11607ed0]. Got map[pluginFactory1:0x11607e40 pluginFactory2:0x11607e70] instead.
    --- FAIL: TestMerge/Merge_duplicate_factories (0.00s)
        registry_test.go:158: Merge(). Expected map[pluginFactory1:0x11607f60]. Got map[pluginFactory1:0x11607f00] instead.
--- FAIL: TestRegister (0.00s)
    --- FAIL: TestRegister/valid_Register (0.00s)
        registry_test.go:207: Register(). Expected map[pluginFactory1:0x11607fc0]. Got map[pluginFactory1:0x11607f90] instead.
    --- FAIL: TestRegister/Register_duplicate_factories (0.00s)
        registry_test.go:207: Register(). Expected map[pluginFactory1:0x11608050]. Got map[pluginFactory1:0x11607ff0] instead.
--- FAIL: TestUnregister (0.00s)
    --- FAIL: TestUnregister/valid_Unregister (0.00s)
        registry_test.go:252: Unregister(). Expected map[pluginFactory2:0x116080e0]. Got map[pluginFactory2:0x116080b0] instead.
```
[fail.log](https://github.com/golang/go/files/6357947/fail.log)

**Comment by Rajalakshmi-Girish** [comment] 2021-04-22 11:50
@laboger ^^

**Comment by laboger** [comment] 2021-04-23 13:10
@Rajalakshmi-Girish please provide information on when this last passed and if this is power8 or 9.

@pmur

**Comment by laboger** [comment] 2021-04-23 18:26
This started failing with commit 84825599dc all: merge branch dev.regabi (d3cd4830ad) into master.
@cherrymui 

Interestingly, the errors shown above will happen when I run this one test:
```
make clean
make test KUBE_RACE=-race WHAT=./pkg/scheduler/framework/runtime/ 2>&1 | tee pss.log
```
But if I do 
```
make clean
make
```
It ICEs. But I'm guessing that was probably fixed.

To set up
```
mkdir ~/k8
export GOPATH=~/k8
mkdir -p ~/k8/src/k8s.io && cd ~/k8/src/k8s.io
git clone https://github.com/kubernetes/kubernetes.git
cd kubernetes
```

**Comment by cherrymui** [comment] 2021-04-24 00:50
If I understand correctly what the test does, there are a few problems:

1. The test seems to compare reflect.Value using == operator
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/runtime/registry_test.go#L79
which is not supposed to work
https://tip.golang.org/pkg/reflect/#Value
```
To compare two Values, compare the results of the Interface method. Using == on two Values does not compare the underlying values they represent.
```

2. And it appears to compare func values
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/runtime/registry.go#L29
which is not expected to work either. Func values are incomparable. It is true that you could get the PC through reflection but it is still not expected to be compared. PCs can change due to inlining, wrappers, etc., depending on the compiler's details, which is subject to change.

I think this is working as intended. Closing. Thanks.

**Closed by cherrymui** 2021-04-24 00:50 UTC
