### ISSUE TITLE
x/tools/go/analysis: Unexpected pass.Files when func have param like context.Context and Analyzer set FactTypes

### ISSUE THREAD

**Issue by didebughu** [golang/go#64093] opened 2023-11-13 09:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.21.4
</pre>

### Does this issue reproduce with the latest release?

yep

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

myanalyzer.go
<pre>
var Analyzer = &analysis.Analyzer{
	Name:      "checkctx",
	Doc:       Doc,
	FactTypes: []analysis.Fact{new(ctxFact)},
	Requires:  []*analysis.Analyzer{buildssa.Analyzer},
	Run:       run,
}

func run(pass *analysis.Pass) (interface{}, error) {

	for _, f := range pass.Files {
		fmt.Println(f.Name.Name)
	}
}
</pre>
example.go
<pre>
package mypackage

import (
	"context"
)

func myfunc(ctx context.Context) {
}
</pre>

### What did you expect to see?

pass.Files only contain the files of package

### What did you see instead?

output:
<pre>
...........
abi
abi
abi
runtime
runtime
syscall
syscall
syscall
syscall
syscall
syscall
.........
syscall
syscall
syscall
syscall
syscall
syscall
syscall
syscall
syscall
time
time
time
time
time
time
time
time
time
time
context
example
</pre>

**Comment by timothy-king** [comment] 2023-11-15 22:38
Conceptually, an `analysis.Pass` is a pair `(*analysis.Analyzer, *packages.Package)`. When you turn facts on for `myanalyzer.Analyzer`, a pass `(myanalyzer.Analyzer, mypackage)` also requires a pass for each dependency of `mypackage`. In this case, this includes `(myanalyzer.Analyzer, context)`. That pass then also requires `myanalyzer.Analyzer` be run on the [transitive] dependencies of context. I am assuming you are running a `{single,multi}checker` from the commandline line. If so, one would expect to see printed the package name * number of files in the package for each of the dependencies of context. I believe you are seeing the output of all of these passes in stdout. That is what the above looks like to me. 

Closing this as WAI for now. Please reopen if I missed something.

(If you are seeing one pass with all of these files, that would be a bug. More detailed reproducer would help.)
(If you run via the unitchecker, this would be slightly different as an on disk cache is used.)

**Closed by timothy-king** 2023-11-15 22:38 UTC
Labels: Tools

**Comment by didebughu** [comment] 2023-11-17 06:34
thank you very much.
