### ISSUE TITLE
x/build/cmd/gerritbot: don't ask author to do the review

### ISSUE THREAD

**Issue by robpike** [golang/go#27788] opened 2018-09-21 01:05 UTC
Not sure if I have the right component here, but I just sent a couple of CLs regarding fmt, and "Gobot" asked me and only me to review them.

**Comment by dmitshur** [comment] 2018-09-21 03:14
Thanks for the report; this is a duplicate of #27533. /cc @andybons

**Closed by dmitshur** 2018-09-21 03:14 UTC
Labels: Builders
