### ISSUE TITLE
cmd/go: a go get invocation produces an "invalid version: unknown revision" loop

### ISSUE THREAD

**Issue by anacrolix** [golang/go#55898] opened 2022-09-28 00:29 UTC
This issue occurs in Go 1.18, and 1.19, and several other versions I've tried. To reproduce:

```
cd `mktemp -d`
go mod init hello
go get github.com/anacrolix/torrent
```

This gives:

    go: github.com/anacrolix/dht/v2@v2.15.2-0.20220123034220-0538803801cb: invalid version: unknown revision 0538803801cb

I know this revision is missing, it likely disappeared in a rebase or something, and may finally have been flushed from the Google proxy. Both the `github.com/anacrolix/torrent` and `github.com/anacrolix/dht/v2` modules depend on each other (but there are no circular package dependencies or it wouldn't compile). I believe they depend on versions that trickle down to the revision that is missing above, but it's not possible to break this cycle. In recent versions I've made both modules depend on versions of each other that shouldn't depend on older versions that trickle down but it doesn't work. You can try my latest attempt to break this cycle via `go get github.com/anacrolix/torrent@unknown-dht-version` using the reproduce steps above.

The downstream issue is https://github.com/anacrolix/torrent/issues/776.

**Comment by anacrolix** [comment] 2022-09-28 01:15
Go 1.16 helpfully produces more output:
```
go get: github.com/anacrolix/torrent@v1.40.1 updating to
	github.com/anacrolix/torrent@v1.47.0 requires
	github.com/anacrolix/dht/v2@v2.19.0 requires
	github.com/anacrolix/torrent@v1.46.0 requires
	github.com/anacrolix/dht/v2@v2.16.2-0.20220311024416-dd658f18fd51 requires
	github.com/anacrolix/torrent@v1.41.1-0.20220309095723-02b6ee995497 requires
	github.com/anacrolix/dht/v2@v2.15.2-0.20220123034220-0538803801cb: invalid version: unknown revision 0538803801cb
```

**Comment by dmitshur** [comment] 2022-09-28 13:51
CC @bcmills, @matloob.

**Comment by bcmills** [comment] 2022-09-28 15:55
Duplicate of #48024

**Comment by bcmills** [comment] 2022-09-28 15:57
Closing as duplicate.

(I'll give some specific guidance on how to resolve the problem on https://github.com/anacrolix/torrent/issues/776 later today — I don't mean to leave you in the lurch!)

**Closed by bcmills** 2022-09-28 15:57 UTC
Labels: NeedsInvestigation, GoCommand

**Comment by anacrolix** [comment] 2022-09-29 23:54
This issue has mutated into https://github.com/golang/go/issues/55955.
