### ISSUE TITLE
runtime: NumGoroutine is 2 in main when using -linkshared

### ISSUE THREAD

**Issue by mwhudson** [golang/go#16631] opened 2016-08-07 22:56 UTC
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?

go version devel +219ca60 Sat Aug 6 19:30:57 2016 +0000 linux/amd64
1. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/opensource/gopath"
GORACE=""
GOROOT="/opt/opensource/go"
GOTOOLDIR="/opt/opensource/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build374916367=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
1. What did you do?

go run run.go -linkshared goprint.go
1. What did you expect to see?

no output but the process exiting cleanly
1. What did you see instead?

it hangs

**Comment by mwhudson** [comment] 2016-08-08 00:07
I'd previously said that this happened with 1.6 but it doesn't, this is a regression (sadface).

**Comment by mwhudson** [comment] 2016-08-08 01:17
Ah so the good news is that this is because the test is a bit silly (in a way that it is not in 1.6). And this is the real 'problem':

```
$ cat numgoroutine.go
package main

import "runtime"

func main() {
	println(runtime.NumGoroutine())
}
$ go run numgoroutine.go 
1
$ go run -linkshared numgoroutine.go 
2
```

This difference is present in 1.6 so not a regression. I'll either try to figure out what's going on or just fix the test in early 1.8.

**Comment by quentinmit** [comment] 2016-08-08 19:31
@mwhudson Do we need to skip the test in 1.7?

**Comment by mwhudson** [comment] 2016-08-08 21:31
It's not run by default, so I'd say no.

**Comment by aclements** [comment] 2017-06-06 21:05
@mwhudson, I probably just don't know what I'm doing here, but when I tried to reproduce this I get:

```sh
$ go run -linkshared main.go
# command-line-arguments
/home/austin/go.dev/pkg/tool/linux_amd64/link: cannot implicitly include runtime/cgo in a shared library
```

I tried `go install -linkshared runtime` first, but it didn't help.

**Comment by mwhudson** [comment] 2017-06-06 21:09
@aclements you need to run go install -buildmode=shared std first

**Comment by mwhudson** [comment] 2017-06-06 21:13
Although the -linshared is probably irrelevant, it happens just when linking externally:

```
$ go run -ldflags='-linkmode=external' numgoroutine.go
2
```

**Comment by aclements** [comment] 2017-06-06 21:14
Thanks.

It looks like the "second" goroutine is the spare M used by cgo callbacks. So this will appear whenever cgo is used.

Perhaps that should be marked as a system goroutine until it's actually used...

**Closed** 2017-06-07 02:14 UTC
Labels: NeedsFix
