### ISSUE TITLE
strings.trim() is a bug?????

### ISSUE THREAD

**Issue by NoviceHuang** [golang/go#36315] opened 2019-12-30 10:15 UTC
func strTrim () {
	str := "wrong repayment time. "
	resp := strings.Trim(str, "rpc error: code ")
	fmt.Println(resp)
}

output: wrong repayment time. 

BUT

func strTrim () {
	str := "wrong repayment time. "
	resp := strings.Trim(str, "rpc error: code = Unknown desc =")
	fmt.Println(resp)
}

output:g repayment time.

What is it? why?????

**Comment by obeyda** [comment] 2019-12-30 10:28
https://play.golang.org/p/C_SuAmJkyH0

**Comment by obeyda** [comment] 2019-12-30 11:12
Let's work it out:
a) when trying to trim the left side with`s="wrong repayment time. "` and  `Cutset="rpc error: code "`:
   1. the first character is a `w`, does `Cutset` contains a `w`? **no**, so return;

b) when trying to trim the left side with`s="wrong repayment time. "` and  `Cutset="rpc error: code = Unknown desc ="`:
  1. the 1st character is a `w`, does `Cutset` contains a `w`? **yes**, so continue;
  1. the 2nd character is a `r`, does `Cutset` contains a `w`? **yes**, so continue;
  1. the 3rd character is a `o`, does `Cutset` contains a `w`? **yes**, so continue;
  1. the 4th character is a `n`, does `Cutset` contains a `w`? **yes**, so continue;
  1. the 5th character is a `g`, does `Cutset` contains a `w`? **no**, so return;


this is not *exactly* how it's implemented, the `Trim()` func basically calls [indexFunc](https://golang.org/src/strings/strings.go?s=19022:19281#L772) to trim the left side, 
by reading the source code you'll have a better understanding on how it's working and handling different ascii/non-ascii runes.

**Comment by mseshachalam** [comment] 2019-12-30 11:12
https://play.golang.org/p/fm4KMPuYOgH 

The second argument to [string.Trim](https://golang.org/pkg/strings/#Trim) is a set(cut set)

**Comment by ALTree** [comment] 2019-12-30 11:35
As it was explained above, this is working as intended. You can use [TrimSuffix](https://golang.org/pkg/strings/#TrimSuffix) for trimming whole substrings. Closing here, since this is not a bug and your question has been answered.

**Closed by ALTree** 2019-12-30 11:35 UTC

**Comment by kedadiannao220** [comment] 2020-04-01 05:48
> https://play.golang.org/p/C_SuAmJkyH0
> Let's work it out:
> a) when trying to trim the left side with`s="wrong repayment time. "` and `Cutset="rpc error: code "`:
> 
> 1. the first character is a `w`, does `Cutset` contains a `w`? **no**, so return;
> 
> b) when trying to trim the left side with`s="wrong repayment time. "` and `Cutset="rpc error: code = Unknown desc ="`:
> 
> 1. the 1st character is a `w`, does `Cutset` contains a `w`? **yes**, so continue;
> 2. the 2nd character is a `r`, does `Cutset` contains a `w`? **yes**, so continue;
> 3. the 3rd character is a `o`, does `Cutset` contains a `w`? **yes**, so continue;
> 4. the 4th character is a `n`, does `Cutset` contains a `w`? **yes**, so continue;
> 5. the 5th character is a `g`, does `Cutset` contains a `w`? **no**, so return;
> 
> this is not _exactly_ how it's implemented, the `Trim()` func basically calls [indexFunc](https://golang.org/src/strings/strings.go?s=19022:19281#L772) to trim the left side,
> by reading the source code you'll have a better understanding on how it's working and handling different ascii/non-ascii runes.

is it should be

> 
> 1. the 1st character is a `w`, does `Cutset` contains a `w`? **yes**, so continue;
> 2. the 2nd character is a `r`, does `Cutset` contains a `r`? **yes**, so continue;
> 3. the 3rd character is a `o`, does `Cutset` contains a `o`? **yes**, so continue;
> 4. the 4th character is a `n`, does `Cutset` contains a `n`? **yes**, so continue;
> 5. the 5th character is a `g`, does `Cutset` contains a `g`? **no**, so return;


???
