### ISSUE TITLE
runtime: crash in gcInstallStackBarrier

### ISSUE THREAD

**Issue by rsc** [golang/go#11057] opened 2015-06-04 02:10 UTC
Seen once:

    ##### GOMAXPROCS=2 runtime -cpu=1,2,4
    --- FAIL: TestGcSys (0.04s)
    	crash_test.go:92: building source: exit status 2
    		panic: runtime error: slice bounds out of range
    		fatal error: panic on system stack
    
    		runtime stack:
    		runtime.throw(0x98c770, 0x15)
    			/tmp/buildlet-scatch328051143/src/runtime/panic.go:527 +0x96
    		runtime.gopanic(0x897800, 0xc208010180)
    			/tmp/buildlet-scatch328051143/src/runtime/panic.go:354 +0xbc
    		runtime.panicslice()
    			/tmp/buildlet-scatch328051143/src/runtime/panic.go:18 +0x50
    		runtime.gcInstallStackBarrier(0xc2080d5e40, 0x7f4ec90bcb50)
    			/tmp/buildlet-scatch328051143/src/runtime/mgcmark.go:510 +0xb1
    		runtime.scanstack.func1(0x7f4ec90bcb50, 0x0, 0x1)
    			/tmp/buildlet-scatch328051143/src/runtime/mgcmark.go:365 +0xa2
    		runtime.gentraceback(0x62cd25, 0xc2080429b8, 0x0, 0xc2080d5e40, 0x0, 0x0, 0x7fffffff, 0x7f4ec90bcc68, 0x0, 0x0, ...)
    			/tmp/buildlet-scatch328051143/src/runtime/traceback.go:336 +0xa81
    		runtime.scanstack(0xc2080d5e40)
    			/tmp/buildlet-scatch328051143/src/runtime/mgcmark.go:380 +0x351
    		runtime.gcphasework(0xc2080d5e40)
    			/tmp/buildlet-scatch328051143/src/runtime/mgcmark.go:273 +0x70
    		runtime.stopg(0xc2080d5e40, 0x3)
    			/tmp/buildlet-scatch328051143/src/runtime/proc1.go:395 +0x91
    		runtime.markroot(0xc208018000, 0xe)
    			/tmp/buildlet-scatch328051143/src/runtime/mgcmark.go:138 +0x1f2
    		runtime.parfordo(0xc208018000)
    			/tmp/buildlet-scatch328051143/src/runtime/parfor.go:95 +0x12d
    		runtime.gcscan_m()
    			/tmp/buildlet-scatch328051143/src/runtime/mgcmark.go:37 +0xe1
    		runtime.gc.func1()
    			/tmp/buildlet-scatch328051143/src/runtime/mgc.go:843 +0x5f
    		runtime.systemstack(0xc20801a000)
    			/tmp/buildlet-scatch328051143/src/runtime/asm_amd64.s:262 +0x7c
    		runtime.mstart()
    			/tmp/buildlet-scatch328051143/src/runtime/proc1.go:656
    
    		goroutine 7 [garbage collection scan]:
    		runtime.systemstack_switch()
    			/tmp/buildlet-scatch328051143/src/runtime/asm_amd64.s:216 fp=0xc2080244e8 sp=0xc2080244e0
    		runtime.gc(0x0)
    			/tmp/buildlet-scatch328051143/src/runtime/mgc.go:855 +0x1dc fp=0xc208024790 sp=0xc2080244e8
    		runtime.backgroundgc()
    			/tmp/buildlet-scatch328051143/src/runtime/mgc.go:775 +0x40 fp=0xc2080247c0 sp=0xc208024790
    		runtime.goexit()
    			/tmp/buildlet-scatch328051143/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc2080247c8 sp=0xc2080247c0
    		created by runtime.startGC
    			/tmp/buildlet-scatch328051143/src/runtime/mgc.go:748 +0x14a
    
    		goroutine 1 [semacquire]:
    		sync.runtime_Semacquire(0xc2085de110)
    			/tmp/buildlet-scatch328051143/src/runtime/sema.go:43 +0x2d
    		sync.(*WaitGroup).Wait(0xc2086007c0)
    			/tmp/buildlet-scatch328051143/src/sync/waitgroup.go:132 +0x15d
    		main.(*builder).do(0xc20812fa40, 0xc208552270)
    			/tmp/buildlet-scatch328051143/src/cmd/go/build.go:1153 +0x3c9
    		main.runBuild(0xb986e0, 0xc20800a230, 0x0, 0x0)
    			/tmp/buildlet-scatch328051143/src/cmd/go/build.go:441 +0x51f
    		main.main()
    			/tmp/buildlet-scatch328051143/src/cmd/go/main.go:177 +0x750
    
    		goroutine 17 [syscall, locked to thread]:
    		runtime.goexit()
    			/tmp/buildlet-scatch328051143/src/runtime/asm_amd64.s:1700 +0x1
    
    		goroutine 5 [syscall]:
    		os/signal.loop()
    			/tmp/buildlet-scatch328051143/src/os/signal/signal_unix.go:22 +0x1f
    		created by os/signal.init.1
    			/tmp/buildlet-scatch328051143/src/os/signal/signal_unix.go:28 +0x3e
    
    		goroutine 18 [select]:
    		main.(*builder).do.func2(0xc2086007c0, 0xc20812fa40, 0xc2086007a0)
    			/tmp/buildlet-scatch328051143/src/cmd/go/build.go:1134 +0x1d1
    		created by main.(*builder).do
    			/tmp/buildlet-scatch328051143/src/cmd/go/build.go:1150 +0x3a1
    
    		goroutine 19 [syscall]:
    		syscall.Syscall(0x0, 0x6, 0xc208042a80, 0x8, 0x0, 0x8, 0x0)
    			/tmp/buildlet-scatch328051143/src/syscall/asm_linux_amd64.s:18 +0x5
    		syscall.readlen(0x6, 0xc208042a80, 0x8, 0x11, 0x0, 0x0)
    			/tmp/buildlet-scatch328051143/src/syscall/zsyscall_linux_amd64.go:1085 +0x53
    		syscall.forkExec(0xc208604480, 0x3a, 0xc208528400, 0x10, 0x10, 0xc208042c50, 0x1b61, 0x0, 0x0)
    			/tmp/buildlet-scatch328051143/src/syscall/exec_unix.go:200 +0x56a
    		syscall.StartProcess(0xc208604480, 0x3a, 0xc208528400, 0x10, 0x10, 0xc208042c50, 0x1, 0x4, 0x0, 0x0)
    			/tmp/buildlet-scatch328051143/src/syscall/exec_unix.go:238 +0x6e
    		os.startProcess(0xc208604480, 0x3a, 0xc208528400, 0x10, 0x10, 0xc208042e88, 0x910360, 0x0, 0x0)
    			/tmp/buildlet-scatch328051143/src/os/exec_posix.go:45 +0x33f
    		os.StartProcess(0xc208604480, 0x3a, 0xc208528400, 0x10, 0x10, 0xc208042e88, 0x0, 0x0, 0x0)
    			/tmp/buildlet-scatch328051143/src/os/doc.go:24 +0x6c
    		os/exec.(*Cmd).Start(0xc208574140, 0x0, 0x0)
    			/tmp/buildlet-scatch328051143/src/os/exec/exec.go:319 +0x76a
    		os/exec.(*Cmd).Run(0xc208574140, 0x0, 0x0)
    			/tmp/buildlet-scatch328051143/src/os/exec/exec.go:246 +0x34
    		main.(*builder).runOut(0xc20812fa40, 0xc208121340, 0x16, 0xc2081212c0, 0x17, 0x0, 0x0, 0x0, 0xc20860a000, 0xd, ...)
    			/tmp/buildlet-scatch328051143/src/cmd/go/build.go:1924 +0x334
    		main.gcToolchain.gc(0xc20812fa40, 0xc208136000, 0xc2085f7200, 0x30, 0xc208604300, 0x34, 0xc208184500, 0xc2086008c0, 0x2, 0x2, ...)
    			/tmp/buildlet-scatch328051143/src/cmd/go/build.go:2171 +0xfe2
    		main.(*gcToolchain).gc(0xbc5318, 0xc20812fa40, 0xc208136000, 0xc2085f7200, 0x30, 0xc208604300, 0x34, 0x0, 0xc2086008c0, 0x2, ...)
    			<autogenerated>:3 +0x191
    		main.(*builder).build(0xc20812fa40, 0xc208552270, 0x0, 0x0)
    			/tmp/buildlet-scatch328051143/src/cmd/go/build.go:1320 +0x253e
    		main.(*builder).do.func1(0xc208552270)
    			/tmp/buildlet-scatch328051143/src/cmd/go/build.go:1087 +0x3bc
    		main.(*builder).do.func2(0xc2086007c0, 0xc20812fa40, 0xc2086007a0)
    			/tmp/buildlet-scatch328051143/src/cmd/go/build.go:1144 +0x158
    		created by main.(*builder).do
    			/tmp/buildlet-scatch328051143/src/cmd/go/build.go:1150 +0x3a1
    FAIL
    FAIL	runtime	34.358s
    2015/06/03 20:57:17 Failed: exit status 1
    Error running run: exit status 1
    *** FAILED ***
    $

**Comment by aclements** [comment] 2015-06-04 02:13
Duplicate of #11049.

**Closed by aclements** 2015-06-04 02:13 UTC
