### ISSUE TITLE
net/http/request: distinguish request target and host header when using proxy 

### ISSUE THREAD

**Issue by kidkidkid** [golang/go#43588] opened 2021-01-08 10:00 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>
go version go1.14.6 darwin/amd64
### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?

According to RFC 7230, absoluteURI should be passed when using proxy. When i set Host header, the host in absoluteURI is rewrote by the header, which is not acceptable. For example, using curl as follows:
<pre>
curl -H '{Host:A}' http://B/some/page -x {proxy}
</pre>
When capturing the traffic, we could get packet like this: 
<pre>
GET http://B/some/page HTTP 1.1\r\n
HOST A\r\n
</pre>
While using http.Proxy in Go, i can set host by setting request.Host, but it cannot preserve original Host in absoluteURI. 
<pre>
u, _ := url.Parse(""proxy)
transport := &http.Transport{}
transport.Proxy = http.ProxyURL(u)
cli := &http.Client{Transport: transport}
req,  _ := http.NewRequest("GET", "http://B/some/page", nil)
req.Host="A"
cli.Do(req)
</pre>
Packet captured is like this:
<pre>
GET http://A/some/page.com 1.1\r\n
HOST A\r\n
</pre>
Sometimes Host header can be used to verify the request, and Host is not equal with host domain in such case. I know proxy should rewrite Host according to RFC, but i think it's acceptable to distinguish host header and host in absoluteURI.
### What did you see instead?
Maybe the user defined host won't rewrite the host in absoluteURI.
https://github.com/golang/go/blob/master/src/net/http/request.go#L585

**Comment by seankhliao** [comment] 2021-09-13 18:16
Duplicate of #16265

**Closed by seankhliao** 2021-09-13 18:16 UTC
Labels: NeedsInvestigation
