### ISSUE TITLE
net/http: data race when response is returned before the full request's body is written

### ISSUE THREAD

**Issue by VirrageS** [golang/go#30597] opened 2019-03-05 13:20 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/januszm/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/januszm/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build489382708=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Run following script with: `go run -race concept.go`

```go
package main

import (
	"crypto/rand"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"sync"
	"time"
)

const (
	addr1 = "localhost:8060"
	addr2 = "localhost:8061"
)

type customReader struct {
	iter int
	size int
}

func (r *customReader) Read(b []byte) (int, error) {
	maxRead := r.size - r.iter
	if maxRead == 0 {
		return 0, io.EOF
	}
	if maxRead > len(b) {
		maxRead = len(b)
	}
	n, err := rand.Read(b[:maxRead])
	r.iter += maxRead
	return n, err
}

func (r *customReader) Close() error {
	// Uncomment this for even more races :((
	// r.iter = 0
	return nil
}

func (r *customReader) Reset() {
	r.iter = 0
}

func second(w http.ResponseWriter, r *http.Request) {
	ioutil.ReadAll(r.Body)
}

func first(w http.ResponseWriter, r *http.Request) {
	http.Redirect(w, r, "http://"+addr2+"/second", http.StatusTemporaryRedirect)
}

func main() {
	mux1 := http.NewServeMux()
	mux1.HandleFunc("/first", first)
	srv1 := http.Server{
		Addr:    addr1,
		Handler: mux1,
	}
	go func() {
		err := srv1.ListenAndServe()
		fmt.Printf("err: %v", err)
	}()

	mux2 := http.NewServeMux()
	mux2.HandleFunc("/second", second)
	srv2 := http.Server{
		Addr:    addr2,
		Handler: mux2,
	}
	go func() {
		err := srv2.ListenAndServe()
		fmt.Printf("err: %v", err)
	}()

	time.Sleep(time.Second)
	client := http.DefaultClient

	wg := &sync.WaitGroup{}
	for i := 0; i < 1000; i++ {
		reader := &customReader{size: 900000}
		wg.Add(1)
		go func(r *customReader) {
			for {
				req, err := http.NewRequest(http.MethodPut, "http://"+addr1+"/first", r)
				if err != nil {
					fmt.Printf("%v", err)
				}
				req.GetBody = func() (io.ReadCloser, error) {
					return &customReader{size: 900000}, nil
				}

				if resp, err := client.Do(req); err != nil {
					// fmt.Printf("error: %v", err)
				} else if resp.StatusCode >= http.StatusBadRequest {
					// fmt.Printf("status code: %d", resp.StatusCode)
				}

				// Reset reader and try to reuse it in next request
				r.Reset()
			}

			wg.Done()
		}(reader)
	}

	wg.Wait() // infinite wait

	srv1.Close()
	srv2.Close()
}
```

### What did you expect to see?

No races

### What did you see instead?

Races:
```
==================
WARNING: DATA RACE
Write at 0x00c0003e00a0 by goroutine 87:
  main.main.func3()
      /home/januszm/concept.go:43 +0x55

Previous write at 0x00c0003e00a0 by goroutine 3899:
  [failed to restore the stack]

Goroutine 87 (running) created at:
  main.main()
      /home/januszm/concept.go:91 +0x3b0

Goroutine 3899 (finished) created at:
  net/http.(*Transport).dialConn()
      /usr/local/go/src/net/http/transport.go:1358 +0xb89
  net/http.(*Transport).getConn.func4()
      /usr/local/go/src/net/http/transport.go:1015 +0xd0
==================
==================
WARNING: DATA RACE
Write at 0x00c0002ca750 by goroutine 488:
  main.main.func3()
      /home/januszm/concept.go:43 +0x55

Previous write at 0x00c0002ca750 by goroutine 1951:
  main.(*customReader).Read()
      /home/januszm/concept.go:33 +0x156
  net/http.transferBodyReader.Read()
      /usr/local/go/src/net/http/transfer.go:62 +0x77
  io.copyBuffer()
      /usr/local/go/src/io/io.go:402 +0x143
  net/http.(*transferWriter).writeBody()
      /usr/local/go/src/io/io.go:364 +0x76e
  net/http.(*Request).write()
      /usr/local/go/src/net/http/request.go:655 +0x7c3
  net/http.(*persistConn).writeLoop()
      /usr/local/go/src/net/http/transport.go:1961 +0x321

Goroutine 488 (running) created at:
  main.main()
      /home/januszm/concept.go:91 +0x3b0

Goroutine 1951 (running) created at:
  net/http.(*Transport).dialConn()
      /usr/local/go/src/net/http/transport.go:1358 +0xb89
  net/http.(*Transport).getConn.func4()
      /usr/local/go/src/net/http/transport.go:1015 +0xd0
==================
==================
WARNING: DATA RACE
Write at 0x00c0002ca780 by goroutine 491:
  main.main.func3()
      /home/januszm/concept.go:43 +0x55

Previous write at 0x00c0002ca780 by goroutine 3360:
  ??()
      -:0 +0xffffffffffffffff
  fmt.(*fmt).fmtInteger()
      /usr/local/go/src/fmt/format.go:307 +0x441
  fmt.(*pp).fmtInteger()
      /usr/local/go/src/fmt/print.go:386 +0x297
  fmt.(*pp).printArg()
      /usr/local/go/src/fmt/print.go:662 +0xf13
  fmt.(*pp).doPrintf()
      /usr/local/go/src/fmt/print.go:1016 +0x315
  fmt.Fprintf()
      /usr/local/go/src/fmt/print.go:199 +0x7f
  net/http/internal.(*chunkedWriter).Write()
      /usr/local/go/src/net/http/internal/chunked.go:203 +0xd8
  io.copyBuffer()
      /usr/local/go/src/io/io.go:404 +0x282
  net/http.(*transferWriter).writeBody()
      /usr/local/go/src/io/io.go:364 +0x76e
  net/http.(*Request).write()
      /usr/local/go/src/net/http/request.go:655 +0x7c3
  net/http.(*persistConn).writeLoop()
      /usr/local/go/src/net/http/transport.go:1961 +0x321

Goroutine 491 (running) created at:
  main.main()
      /home/januszm/concept.go:91 +0x3b0
==================
```

**Comment by mvdan** [comment] 2019-03-05 13:40
Are you positive that the race is in net/http and not your use of it? If you're not sure, have you tried asking on one of the [forums](https://github.com/golang/go/wiki/Questions) for help?

**Comment by VirrageS** [comment] 2019-03-05 14:11
No, I'm not positive and I haven't ask on the forums. Though, there is nothing said in `(c *Client) Do` about this case so I concluded that this is unexpected

I will try to post on forums to ensure that this is not my fault. If it is, it would mean that one cannot change fields in `Close` method which are also used `Read` in reader which seems odd. As a result we couldn't be able use `*File` as `ReadCloser` in `Body` for redirected requests since it does modify (on `Close`) descriptor which `Read` is using.

**Comment by orian** [comment] 2019-03-06 00:16
https://groups.google.com/forum/#!topic/golang-nuts/1rst28pnlt8

The problem is not `net/http` but simultaneous use of a `reader := &customReader{...}` variable in 1000 goroutines. I believe it could be closed.

**Comment by VirrageS** [comment] 2019-03-06 06:38
I'm sorry but could you point out where I use it simultaneously? I create new(!) reader for each goroutine.

If you want, you can remove this goroutine staff and have single infinite `for` loop. The code will still have a races but you probably need to run it for a little bit longer time to see them
<details><summary>Single thread race</summary>

```go
package main

import (
	"crypto/rand"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"sync"
	"time"
)

const (
	addr1 = "localhost:8060"
	addr2 = "localhost:8061"
)

type customReader struct {
	iter int
	size int
}

func (r *customReader) Read(b []byte) (int, error) {
	maxRead := r.size - r.iter
	if maxRead == 0 {
		return 0, io.EOF
	}
	if maxRead > len(b) {
		maxRead = len(b)
	}
	n, err := rand.Read(b[:maxRead])
	r.iter += maxRead
	return n, err
}

func (r *customReader) Close() error {
	// Uncomment this for even more races :((
	// r.iter = 0
	return nil
}

func (r *customReader) Reset() {
	r.iter = 0
}

func second(w http.ResponseWriter, r *http.Request) {
	ioutil.ReadAll(r.Body)
}

func first(w http.ResponseWriter, r *http.Request) {
	http.Redirect(w, r, "http://"+addr2+"/second", http.StatusTemporaryRedirect)
}

func main() {
	mux1 := http.NewServeMux()
	mux1.HandleFunc("/first", first)
	srv1 := http.Server{
		Addr:    addr1,
		Handler: mux1,
	}
	go func() {
		err := srv1.ListenAndServe()
		fmt.Printf("err: %v", err)
	}()

	mux2 := http.NewServeMux()
	mux2.HandleFunc("/second", second)
	srv2 := http.Server{
		Addr:    addr2,
		Handler: mux2,
	}
	go func() {
		err := srv2.ListenAndServe()
		fmt.Printf("err: %v", err)
	}()

	time.Sleep(time.Second)
	client := http.DefaultClient

	reader := &customReader{size: 900000}
	for {
		req, err := http.NewRequest(http.MethodPut, "http://"+addr1+"/first", r)
		if err != nil {
			fmt.Printf("%v", err)
		}
		req.GetBody = func() (io.ReadCloser, error) {
			return &customReader{size: 900000}, nil
		}

		if resp, err := client.Do(req); err != nil {
			// fmt.Printf("error: %v", err)
		} else if resp.StatusCode >= http.StatusBadRequest {
			// fmt.Printf("status code: %d", resp.StatusCode)
		}

		// Reset reader and try to reuse it in next request
		r.Reset()
	}

	srv1.Close()
	srv2.Close()
}
```
</details>

**Comment by fraenkel** [comment] 2019-03-06 14:29
The problem is with your reader. iter is being updated in multiple goroutines, via Read() and Reset(). The underlying http transport is not guaranteed to use a single goroutine to handle your request/response.

Although on my machine, I never got a data race detection, but call me lucky in this case.

**Comment by VirrageS** [comment] 2019-03-06 15:53
> The problem is with your reader. iter is being updated in multiple goroutines, via Read() and Reset().

But how is that possible? `Reset` is called AFTER `client.Do` so I would expect all `Read`s/`Write`s or whatever, are done and I can still use my reader. Is that bad assumption? If so, the `client.Do` documentation should state that it is not safe to use reader (`req.Body`) after `client.Do`.

> The underlying http transport is not guaranteed to use a single goroutine to handle your request/response.

And I don't expect it to use single goroutine. It can use two or million of goroutines. I don't care as long as it does it safely. If safety is on my (user) side then I would expect that 99.9% implementations that use readers in `req.Body` are unsafe and prone to races since they do not use locks or any synchronization mechanism.

**Comment by orian** [comment] 2019-03-06 23:25
I'm sorry for incorrect claim. I've run your code in debugger, as far as I understand there is a goroutine per connection writing/reading data. The communication between the routines is done over channel and I believe that `client.Do` will never return before everything is done.

The relevant code responsible for processing request/response is in transport: https://github.com/golang/go/blame/master/src/net/http/transport.go#L2164

@bradfitz done a lot of changes in transport and probably can tell you more, especially confirm or deny my implicit assumption about the `client.Do`.

**Comment by bradfitz** [comment] 2019-03-06 23:39
You haven't closed your Response.Body, so the Transport is still handling (thus, owning) the request when you Reset its Body.

**Comment by orian** [comment] 2019-03-06 23:58
Closing Response.Body doesn't solve the problem.

Brad, I've read the code in transport.go. There's a `select` on L2177. I cannot find a sync mechanism in place between writing request / reading response. 
I believe that in the above code the exact case described in comment on L2156 happens:
```
// Write the request concurrently with waiting for a response,
// in case the server decides to reply before reading our full
// request body.
```
and the `case` on L2205 is executed causing to return before the writeLoop fails.

Because @VirrageS is reusing the io.Reader the race detector finds the data race, but this indeed is either a bug or undocumented behaviour.

**Comment by VirrageS** [comment] 2019-03-11 11:31
@bradfitz: as @orian mentioned, adding `resp.Body.Close()` does not solve the problem. Races are still possible (and reproducible) between `Read` and `Close`/`Reset`.

**Comment by fraenkel** [comment] 2019-04-10 00:57
@bradfitz I believe the issue may be that there is no guarantee that the writeLoop is finished. The writeLoopDone channel is only checked on a broken connection.
Just a hunch.

**Comment by orian** [comment] 2019-07-08 22:13
I've verified. The issue is reproducible in 1.12.6.

The `io.Copy` function, causing the `writeLoop` to take keep the `req.Body` resource:
https://github.com/golang/go/blob/2012227b01020eb505cf1dbe719b1fa74ed8c5f4/src/net/http/transfer.go#L358 

was encapsulated: 
https://github.com/golang/go/blob/88548d0211ba64896fa76a5d1818e4422847a879/src/net/http/transfer.go#L348

However, the `io.Copy` cannot be easily interrupted and therefore causing race condition.

I've checked `writeLoopDone`, this is per connection variable and I think it should not be modified when a response is returned before the full request's body has been written.

The solutions I see are: 
  1. Document the current behaviour and leave as it is.
  2. Block until the `writeLoop` finish writing the `Request.Body`. (I've implemented it using per request channel to block a return from `roundTrip`).
  3. Same as 2. but with extra mechanism to interrupt the `writeLoop` from copying all `Body` data.

I'm happy to contribute the fix, but someone must make decision

**Comment by VirrageS** [comment] 2019-07-09 20:48
@orian Thanks for looking into this issue!

Another thing that worried me a little in `writeBody` function is that reader passed in request is wrapped into this `internal.NewChunkedWriter`. This becomes an issue when the reader implements `WriteTo` method and can be sent without extra buffering (`io.Copy` should catch that). But since `internal.NewChunkedWriter` does not implement this it will only use the `Read` method. And also eg. we are streaming something through single request the problem is that we will use default 32KB buffer, provided in `io.Copy` implementation and there is no way to make it bigger or smaller what could potentially have impact on performance.

But this probably needs another issue and separate discussion.

**Comment by orian** [comment] 2019-07-10 08:49
@andybons could you change the bug name to "net/http: datarace when response is returned before the full request's body is written" or something similar?

**Comment by VirrageS** [comment] 2019-10-16 18:54
Was there any decision made regarding this issue?

**Comment by ianlancetaylor** [comment] 2019-10-16 20:11
Ping @bradfitz regarding https://github.com/golang/go/issues/30597#issuecomment-509411481 .

**Comment by jszroberto** [comment] 2019-10-22 10:11
this is also happening when trying to use the DumpRequestOut: https://golang.org/pkg/net/http/httputil/#DumpRequestOut

**Comment by VirrageS** [comment] 2019-11-16 17:23
ping @bradfitz

**Comment by vearutop** [comment] 2019-11-27 14:07
I've just ran into this issue while testing `http.Handler` concurrently with `http.DefaultTransport` and `httptest.Server`, is there a workaround?

I've tried `(&http.Transport{}).RoundTrip(req)`, but apparently it still uses same shared loop internally as race was detected.

**Comment by VirrageS** [comment] 2020-02-23 20:22
Is there any progress on this issue?

**Comment by vitaminniy** [comment] 2020-10-21 07:58
The issue is reproducible in go 1.14.6 and go 1.15.3.

**Comment by VirrageS** [comment] 2020-10-21 08:10
The default `RoundTripper` implementation explains why the races may appear:
```
	// RoundTrip should not modify the request, except for
	// consuming and closing the Request's Body. RoundTrip may
	// read fields of the request in a separate goroutine. Callers
	// should not mutate or reuse the request until the Response's
	// Body has been closed.
	//
	// RoundTrip must always close the body, including on errors,
	// but depending on the implementation may do so in a separate
	// goroutine even after RoundTrip returns. This means that
	// callers wanting to reuse the body for subsequent requests
	// must arrange to wait for the Close call before doing so.
```

It's non-intuitive to add special code that would make sure that we wait until the body can be reused but I guess we shouldn't expect any changes in std library to make this easier.

**Closed** 2022-05-11 10:51 UTC
Labels: NeedsInvestigation

**Comment by VirrageS** [comment] 2022-05-11 13:58
Nope, it was intentional. I should have left the comment.

In the documentation there are no guarantees on when the `Request.Body` is closed (see: https://pkg.go.dev/net/http#Client.Do). So I guess it kind of works as expected. I can re-open issue if needed, but I don't think there is any interest in changing the current behavior.
