### ISSUE TITLE
cmd/go2go: type checking failed in test mode

### ISSUE THREAD

**Issue by changkun** [golang/go#40998] opened 2020-08-24 07:24 UTC
### Example 1: 

```go
// a.go2
package p

type S [type T] struct {}

// errors_test.go2
package p

import "testing"

func TestFoo(t *testing.T) {}
```

```
$ go tool go2go test
type checking failed for p
errors_test.go2:1:1: inconsistent use of () or [] for type parameters
```

Workaround: Rename the test file name from `errors_test.go2` to `a_test.go2` will get a PASS.

### Example 2:

```go
// a.go2
package p

// a_test.go2
package p

import "testing"
type S [type T] struct {}
func TestFoo(t *testing.T) {}
```

```
$ go tool go2go test
type checking failed for p
a_test.go2:1:1: inconsistent use of () or [] for type parameters
```

Workaround: Delete `a.go2` will get a PASS.

**Comment by fzipp** [comment] 2020-08-24 09:49
Duplicate of #40806

**Comment by cagedmantis** [comment] 2020-08-24 18:01
This seems to have reported in #40806. I'm going to close this issue. Please let me know if you think this was closed in error.

**Closed by cagedmantis** 2020-08-24 18:01 UTC
