### ISSUE TITLE
How to Prevent Windows Defender from Scanning During Builds ???

### ISSUE THREAD

**Issue by nicholasimon** [golang/go#43427] opened 2020-12-30 04:32 UTC
This is not exactly an issue as in a problem with GO however it would be great if anyone could tell me what Exclusions to add to Windows Defender to prevent it scanning every single build. I am sure it is adding on hours to my life, with countless unnecessary seconds being added every time I type in go build.

I have tried excluding 

c:\go\ 
c:\go\bin\go.exe
projects\ (folder for all my projects)

However this has not worked as Windows Defender is still scanning every single file created when I build.

What other folders/files must I add to the Exclusions list for it not to scan when I build?

### What version of Go are you using (`go version`)?

<pre>
$ go version 1.15.6

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\nicholasimon\AppData\Local\go-build
set GOENV=C:\Users\nicholasimon\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\nicholasimon\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\nicholasimon\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\NICHOL~1\AppData\Local\Temp\go-build685456542=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Type in go build -i

### What did you expect to see?

Works fine, but too slow as Windows Defender scans every build

**Comment by bokunodev** [comment] 2020-12-30 05:09
set win difenderto exclude this directory
```Bash
$GOPATH
$GOCACHE
$GOMODCACHE
$GOROOT
```

**Comment by ALTree** [comment] 2020-12-30 10:35
Sorry, but we only use the github issue tracker for *bugs* in Go. Even questions about Go are offtopic, so generic questions about Windows or nosy Windows programs are offtopic too.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions about Go (not sure on the other hand what's a good place to ask questions about your Windows Antivirus).

Closing here, since this is not a bug.

**Closed by ALTree** 2020-12-30 10:35 UTC
