### ISSUE TITLE
/x/mobile Windows emulation support

### ISSUE THREAD

**Issue by ip** [golang/go#12209] opened 2015-08-19 21:05 UTC
@crawshaw @hyangah @rakyll @nigeltao
As Go is high-performant system-level programming language, that also gained fast garbage collector in latest 1.5 release, it can become a perfect choice for game development. There are many OpenGL ES 2 emulation layers for Windows, for example Google's open-source [ANGLE](code.google.com/p/angleproject/), [AMD library](http://developer.amd.com/tools-and-sdks/graphics-development/amd-opengl-es-sdk/) and others. It would be great if `golang.org/x/mobile/...` packages were implemented for this OS aside of Mac OS X, as it is probably most popular operating system among game developers. This would be big step to Go promotion, because it would enable large gamedev community to easily develop (cross-platform) games in Go.

Yes, now one can build apps and launch them on real device, but such workflow is unusable because of very long build time (compile -> zip -> sign -> upload to device -> wait until installation complete). All game engines and frameworks use this scheme with desktop emulation.

I personally ask for this because I chose Go as language for developing my Android game, but after investigation I decided to work on my own OpenGL binding and other mobile code. Hope this will be considered. Thanks

**Comment by crawshaw** [comment] 2015-08-19 21:41
Hi @ip. I would very much like to support windows. I have been putting it off as we have had higher priority work, but now that the big ticket gomobile work is done I intend to have a look. In fact, the windows-related code being contributed under x/exp/shiny may make this easier.

I can't promise when it will get done unfortunately, as there are a couple of other interrupt tasks that take higher priority, but it is something I would very much like to do.

This issue is a duplicate of #9306, so I'm going to close it. Please follow along there.

**Closed by crawshaw** 2015-08-19 21:41 UTC

**Comment by ip** [comment] 2015-08-19 22:41
@crawshaw Ok, thanks for giving a hint.
