### ISSUE TITLE
cmd/go: `go run` doesn't recognize semantic-versioned import path for main package

### ISSUE THREAD

**Issue by hajimehoshi** [golang/go#24676] opened 2018-04-04 02:10 UTC
### What version of Go are you using (`go version`)?

`go version go1.10 darwin/amd64`

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hajimehoshi/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hajimehoshi/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/go-build743754165=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

Create a main package with version 2 (go.mod), like

```
$ cat $GOPATH/src/github.com/hajimehoshi/vgotest/main.go
package main

func main() {
        println("Hello")
}

$ cat $GOPATH/src/github.com/hajimehoshi/vgotest/go.mod

module "github.com/hajimehoshi/vgotest/v2"
```

### What did you expect to see?

`vgo run main.go` at `$GOPATH/src/github.com/hajimehoshi/vgotest` succeeds.

### What did you see instead?

Error message: 

```
build github.com/hajimehoshi/vgotest: cannot find module for path github.com/hajimehoshi/vgotest
```

### Additional information

Instead of specifying a file, specifying a package path (https://github.com/golang/go/issues/22726) might solve this?

**Comment by bcmills** [comment] 2018-04-04 18:28
Duplicate of #24667?

**Comment by hajimehoshi** [comment] 2018-05-27 13:48
As https://github.com/golang/go/issues/22726 is solved, is this issue automatically solved?

**Comment by rsc** [comment] 2018-07-17 17:46
This seems to be working now. I'm not exactly sure when we fixed it. Sorry for the long delay.

```
$ cat go.mod
module github.com/hajimehoshi/vgotest/v2
$ cat main.go
package main
func main() { println("hello") }
$ GO111MODULE=on go run main.go
hello
$ GO111MODULE=on go run .
hello
$ 
```

**Closed by rsc** 2018-07-17 17:46 UTC
Labels: NeedsInvestigation, modules

**Comment by hajimehoshi** [comment] 2018-07-17 17:55
Thank you for confirming!
