### ISSUE TITLE
why nil is not nil , is a bug?

### ISSUE THREAD

**Issue by tslearn** [golang/go#33965] opened 2019-08-30 07:02 UTC
### What version of Go are you using (`go version`)?
go version go1.12.7 darwin/amd64

### The problem
```golang
type customError struct {

}

func (p *customError) Error() string {
  return "custom error"
}

func getNilCustomError() *customError {
  return nil
}

func TestWebSocketClient_basic(t *testing.T) {
  err1 := getNilCustomError()
  fmt.Println(err1 == nil)     // ok is true

  err2 := error(nil)
  err2 = getNilCustomError()
  fmt.Println(err2 == nil)   // OMG is false
}
```

why err2 is not nil

**Comment by mattn** [comment] 2019-08-30 07:07
This is typed nil. Please see https://golang.org/doc/faq#nil_error

**Comment by ALTree** [comment] 2019-08-30 07:48
what @mattn said : )  Closing here, since this is not a bug.

**Closed by ALTree** 2019-08-30 07:48 UTC
