### ISSUE TITLE
fmt.Sprintf: verb %q returns a surjective function

### ISSUE THREAD

**Issue by mkshr31** [golang/go#40175] opened 2020-07-12 14:14 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mk/.cache/go-build"
GOENV="/home/mk/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mk/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build089759562=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
)

func main() {
	const i int = 55555
	const j int = 55556
	
	u := fmt.Sprintf("%+q", i)
	v := fmt.Sprintf("%+q", j)
	
	fmt.Println(i, j, i == j, u, v, u == v)
}
```

For readability I use `%+q` instead of `%q`. The behavior is the same.

https://play.golang.org/p/Mrx55HYohK_u

### What did you expect to see?

`55555 55556 false %!q(int=+55555) %!q(int=+55556) false`

### What did you see instead?

`55555 55556 false '\ufffd' '\ufffd' true`

The behavior is strongly dependent on the input values.

According to documentation, the verb `%q` produces "a single-quoted character literal safely escaped with Go syntax.".
1. It is not clear for which input values %q returns an escaped Unicode character `\u[0-9a-f]+`, `\U[0-9a-f]+`, or "a single-quoted character literal safely escaped with Go syntax.".
2. It is not reasonable that different input values (`i <> j`) have the same output (`u == v`).

**Comment by martisch** [comment] 2020-07-12 14:54
1. It seems to me the property that for any Integer input (%q is listed for Integers) "a single quoted character literal" is produced. '\ufffd' seems to be a single quoted character literal containing a single Unicode character.

2.  I think its reasonable for different input values to have the same output because not all integers can be reasonably mapped to different valid unicode characters.

**Comment by ianlancetaylor** [comment] 2020-07-12 20:38
Yes, I think this is a duplicate of #14569.  Let's discuss there.  Please comment if you disagree.

**Closed by ianlancetaylor** 2020-07-12 20:38 UTC
