### ISSUE TITLE
x/text/cmd/gotext: dir flag in gotext is useless

### ISSUE THREAD

**Issue by toby3d** [golang/go#28097] opened 2018-10-09 13:53 UTC
### What version of Go are you using (`go version`)?
```bash
go version go1.13.5 linux/amd64
```

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```bash
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/toby3d/go/bin"
GOCACHE="/home/toby3d/.cache/go-build"
GOENV="/home/toby3d/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/toby3d/go"
GOPRIVATE="github.com/toby3d"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build372653986=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
I try generate locales strings in other folder.

`go:generate` tag contains in `/cmd/myapp/main.go` and I use flag `-dir=./../../` for generating locales string in root of project directory `/locales/...`:

```go
//go:generate gotext -dir=./../../ -srclang=en update -out=locales_gen.go -lang=en,ru
package main
...
```

### What did you expect to see?
`gotext` use `-dir` flag and generate locales strings on specific path (for my case - in project root directory).

### What did you see instead?
`gotext` creates folder with strings in `main.go` directory: `/cmd/myapp/locales/...`.

Seems like what `-dir` flag just not used (`deadcode`): 
https://github.com/golang/text/blob/905a57155faa8230500121607930ebb9dd8e139c/cmd/gotext/main.go#L40

**Comment by agnivade** [comment] 2019-11-11 06:37
@mpvl

**Comment by toby3d** [comment] 2019-12-24 04:45
Still reproduced. In addition, the tool cannot be used if the module system is enabled.

**Comment by toby3d** [comment] 2021-08-03 12:27
Any updates?

**Comment by seankhliao** [comment] 2023-07-21 18:23
Duplicate of #61507

**Closed by seankhliao** 2023-07-21 18:23 UTC
Labels: NeedsInvestigation
