### ISSUE TITLE
x/sys/windows: grpc compile tip: "undefined: unix.GetsockoptLinger unix.GetsockoptTimeval"

### ISSUE THREAD

**Issue by zerodistance00** [golang/go#27195] opened 2018-08-24 07:46 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.9.3

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\MyConfiguration\tkk48036\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

### What did you do?
grpc-go practice.

### What did you expect to see?
compile succuss

### What did you see instead?
compile failed

**Comment by agnivade** [comment] 2018-08-24 08:31
This looks like a grpc issue rather than a Go compiler issue. Can you provide more details on why you think this is an issue with Go ?

`grpc-go practice` is not enough details for us to debug the issue.

Thank you.

**Comment by mikioh** [comment] 2018-08-24 08:55
Your application for Windows probably uses golang.org/x/sys/unix package but the package supports Unix variants only. If you need the equivalent of socket manipulation functions for Windows, please edit the title appropriately.

**Comment by robpike** [comment] 2018-08-25 22:55
I think I've seen this one before, and it means your GRPC installation is out of date.  Try updating it.

**Comment by zerodistance00** [comment] 2018-08-27 15:43
grpc-go ‘s bug it uses the func that you didnot have i add the funcs myself and it’s ok now

在 2018-08-24 16:32:58，"Agniva De Sarker" <notifications@github.com> 写道：


This looks like a grpc issue rather than a Go compiler issue. Can you provide more details on why you think this is an issue with Go ?

grpc-go practice is not enough details for us to debug the issue.

Thank you.

**Comment by agnivade** [comment] 2018-08-27 17:48
From what I could understand from your response, looks like the issue is resolved. Closing it now.

Please comment if I have misunderstood.

**Closed by agnivade** 2018-08-27 17:48 UTC
Labels: WaitingForInfo
