### ISSUE TITLE
proposal: math/rand: add NewLockedSource

### ISSUE THREAD

**Issue by ZYunH** [golang/go#34947] opened 2019-10-17 07:03 UTC
May be we could add a new API called NewLockedSource in math/rand, unlike NewSource, it is safe for concurrent use by multiple goroutines. This API makes it easy to crate a concurrent-safe *math.Rand like the globalRand in math/rand.

**Comment by ZYunH** [comment] 2019-10-17 07:06
A pull request here #34876 
This is a proposal now.

**Comment by josharian** [comment] 2019-10-17 19:31
This is a duplicate of #24121.

**Closed** 2019-10-17 19:31 UTC
Labels: Proposal
