### ISSUE TITLE
slices.DeleteFunc modifies input argument

### ISSUE THREAD

**Issue by stephanwesten** [golang/go#66141] opened 2024-03-06 18:54 UTC
### Go version

1.22

### Output of `go env` in your module/workspace:

```shell
see the playground https://go.dev/play/p/SHQNvGFEKDV
```

### What did you do?

see the playground https://go.dev/play/p/SHQNvGFEKDV

### What did you see happen?

I expected slices.DeleteFunc to keep the input argument unmodified. 

You could argue that this is my fault as you can read the doc in such a way that the input argument is modified:
DeleteFunc removes any elements from s for which del returns true, returning the modified slice. DeleteFunc zeroes the elements between the new length and the original length.

However if the input argument is modified, what is the point of returning the modified slice? If nothing would be returned, I would have immediately understood the behaviour.

With better understanding, I re-read the docs. The docs imply that the modified slice that is returned is the same as s. However this is not the case. The length of the returned value is not the same as the example shows.

I would have preferred a more functional approach, keep things immutable as much as possible.

### What did you expect to see?

see above

**Comment by mknyszek** [comment] 2024-03-06 19:24
> However if the input argument is modified, what is the point of returning the modified slice? If nothing would be returned, I would have immediately understood the behaviour.

The point of returning a new slice is that the length may change: https://go.dev/play/p/sQJry0QkIs_o.

FWIW, the behavior this function has is consistent with, for example, append, which may also modify the underlying slice (if you reslice it to its capacity). I'm not sure there's anything actionable here, except for perhaps modifying the documentation.

CC @ianlancetaylor @eliben via https://dev.golang.org/owners, but there may be nothing else to do here. If so, feel free to close the issue. Thanks.

**Comment by seankhliao** [comment] 2024-03-06 19:34
Duplicate of #64329

**Closed by seankhliao** 2024-03-06 19:34 UTC
Labels: Documentation, NeedsInvestigation

**Comment by stephanwesten** [comment] 2024-03-06 20:25
I just do not understand how the current behaviour is useful. I can give examples if the input argument would stay unmodified. Why would someone would like to have two different results? (i.e. returned value and modified input). What is the use-case behind this?

**Comment by randall77** [comment] 2024-03-06 21:40
> I just do not understand how the current behaviour is useful. I can give examples if the input argument would stay unmodified. However, why would someone would like to have two different results? (i.e. returned value and modified input).

It is not so much two different results as reusing the storage of the input for the output.
```
s := []string{"a", "b", "c"}
s = strings.Delete(s, 1, 2)
// s now ["a","c"]. All references to the original slice are gone.
```
It is not really intended that the modified input be used again. In almost all cases you would be overwriting the input slice reference (just like you normally do with `append`).

> I would have preferred a more functional approach, keep things immutable as much as possible.

That's not really how Go is designed. Mutability is pretty core to how slices work. If you want immutable deletion, do `slices.DeleteFunc(slices.Clone(s), ...)`.

**Comment by stephanwesten** [comment] 2024-03-07 22:04
Thanks for your answer. I also understand that my feedback won't change the implementation. Anyway, fwiiw:

The analogy with append() is imo not 100% correct. Append will not change it first argument as shown by this test:

```
func Test_append(t *testing.T) {
	s := []string{"a"}
	r := append(s, "b")
	require.Equal(t, []string{"a"}, s)
	require.Equal(t, []string{"a", "b"}, r)
}
```
So from my pod the symmetry is broken. DeleteFunc() should behave as append(). Or it should not return a value but the caller should continue with the first argument. 

I find the argument "It is not really intended that the modified input be used again" awkward. The current implementation is turning a perfect valid variable into something not to be used... That is definitely a source for bugs and confusion. 

My suggestion is to add the above recommendation that input argument should not be used in subsequent code to the documentation.


PS there is a tiny typo in comment's code above; should be slices.Delete()

**Comment by mknyszek** [comment] 2024-03-07 22:15
> The analogy with append() is imo not 100% correct. Append will not change it first argument as shown by this test:

It may change the contents of the first argument though, you just have to look at the slice's capacity to observe it because it's growing the slice. See https://go.dev/play/p/e80ZaeGuxYo.
