### ISSUE TITLE
go/types, types2: Simple generic code makes compiler loop forever

### ISSUE THREAD

**Issue by aDotInTheVoid** [golang/go#48671] opened 2021-09-28 15:38 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-534dfb2 Tue Sep 28 03:21:58 2021 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

No, requires generics

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nixon/Library/Caches/go-build"
GOENV="/Users/nixon/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/nixon/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/nixon/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/nixon/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/nixon/sdk/gotip/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="devel go1.18-534dfb2 Tue Sep 28 03:21:58 2021 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/nixon/dev/go/gnom/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/14/bhp6wfld6f9gyw31rw492_p40000gn/T/go-build1866204895=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version devel go1.18-534dfb2 Tue Sep 28 03:21:58 2021 +0000 darwin/amd64
GOROOT/bin/go tool compile -V: compile version devel go1.18-534dfb2 Tue Sep 28 03:21:58 2021 +0000
uname -v: Darwin Kernel Version 19.6.0: Tue Aug 24 20:28:00 PDT 2021; root:xnu-6153.141.40~1/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1417
lldb --version: lldb-1103.0.22.10
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
</pre></details>

### What did you do?

```go
package slow

type Maker[T any] func() T

func (m Maker[T]) Culprit() Maker[[]T] {
	return nil
}
```

### What did you expect to see?

Program compiles sucessfully

### What did you see instead?

Compiller loops forever. I stoped it after 9 mins.

### Other potentialy usefull things

```go
package slow

type Maker[T any] func() T

func (m Maker[T]) Culprit() Maker[T] {
	return nil
}
```

both compiles fine

**Comment by findleyr** [comment] 2021-09-28 15:52
This is an infinite recursion in the type checker.

CC @griesemer

**Comment by findleyr** [comment] 2021-09-28 16:04
Thank you for the report.

Simpler reproducer:
```
type N[T any] N[*T]
```
We recurse while expanding N[*T].

This can probably be duped to #48098, though it is important to note that we must also detect this recursion through method declarations.

**Comment by findleyr** [comment] 2021-09-28 16:14
Closing as a dupe of #48098

**Closed by findleyr** 2021-09-28 16:14 UTC
Labels: NeedsInvestigation, release-blocker
