### ISSUE TITLE
cmd/go: import paths ending with '+' are rejected (affects executable like g++ or clang++)

### ISSUE THREAD

**Issue by ianamason** [golang/go#44776] opened 2021-03-03 23:26 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

It seems to be caused by the latest release.  Everything works fine and dandy in 1.15

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/home/vagrant/.cache/go-build"
GOENV="/home/vagrant/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/vagrant/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/vagrant/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/vagrant/gllvm/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4236193755=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

So I maintain a tool set for building LLVM bitcode for any reasonable project.

https://github.com/SRI-CSL/gllvm

It consists of several executables, two of which are compiler wrappers.
One wraps clang, and is called `gclang`
The other wraps clang++ and is called `gclang++`

The executables live in:
```
vagrant@ubuntu-focal:~/gllvm$ tree cmd
cmd
├── gclang
│   └── main.go
├── gclang++
│   └── main.go
├── get-bc
│   └── main.go
├── gparse
│   └── main.go
└── gsanity-check
    └── main.go

5 directories, 5 files
```

People used to install them  via:
```
go get github.com/SRI-CSL/gllvm/cmd/...
```

### What did you expect to see?

This used to work just fine.

### What did you see instead?

Now we get:

```
 go get github.com/SRI-CSL/gllvm/cmd/...
github.com/SRI-CSL/gllvm/cmd/gclang++: malformed import path "github.com/SRI-CSL/gllvm/cmd/gclang++": invalid char '+'
```

I understand that modules are in my future and that this may be related.  But when I try make a module
file:
```
vagrant@ubuntu-focal:~/gllvm$ go mod init github.com/SRI-CSL/gllvm
go: creating new go.mod: module github.com/SRI-CSL/gllvm
go: to add module requirements and sums:
	go mod tidy
vagrant@ubuntu-focal:~/gllvm$ go mod tidy
github.com/SRI-CSL/gllvm/cmd/gclang++: malformed import path "github.com/SRI-CSL/gllvm/cmd/gclang++": invalid char '+'
vagrant@ubuntu-focal:~/gllvm$
```

I am fearing that go no longer tolerates '+' in the name of an executable. Maybe by accident?

**Comment by AlexRouSg** [comment] 2021-03-04 03:06
1.16 made module mode enabled by default and modules are by designed more restrictive in what characters could be used for package/module names/paths.

> A module path must satisfy the following requirements:
> 
> - The path must consist of one or more path elements separated by slashes (/, U+002F). It must not begin or end with a slash.
> - Each path element is a non-empty string made of up ASCII letters, ASCII digits, and limited ASCII punctuation (-, ., _, and ~).
> - A path element may not begin or end with a dot (., U+002E).
> - The element prefix up to the first dot must not be a reserved file name on Windows, regardless of case (CON, com1, NuL, and so on).

https://golang.org/ref/mod#go-mod-file-ident

**Comment by diamondburned** [comment] 2021-03-04 05:16
Why would this restriction apply to import paths (not module names), let alone a package main that isn't imported anywhere at all?

**Comment by AlexRouSg** [comment] 2021-03-04 05:59
Import paths are another name for package paths, a package main will still have a package path, in this case is `github.com/SRI-CSL/gllvm/cmd/gclang++`, even tho it is not importable. 

As for why it would apply to import paths, I guess I should've linked the below instead. Which basically says the same requirements but for import paths.
https://pkg.go.dev/golang.org/x/mod/module#CheckImportPath

**Comment by bcmills** [comment] 2021-03-04 19:08
This may be related to #43985.

**Comment by bcmills** [comment] 2021-03-09 16:49
See previously #31376, particularly https://github.com/golang/go/issues/31376#issuecomment-635529423.

@jayconrod, @matloob, and I discussed this with @rsc, and we're planning to give this the same treatment as #43985: allow `+` in package import paths, but not in module paths.

Because module paths need to be encoded as URLs for module proxies, and `+` is a [reserved character](https://tools.ietf.org/html/rfc3986#section-2.2) in URLs, in order to allow `+` in a module path we would have to give some more thought to how and whether that character should interact with the proxy URL encoding.

In contrast, the `+` character does not appear to be reserved or otherwise have a special meaning on any filesystem we currently support. (Notably, it is not one of the [reserved characters on Windows](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions).) So it seems safe to unpack into the module cache on disk, and therefore safe to allow as a package import path within a module.

**Comment by bcmills** [comment] 2021-03-09 17:05
@gopherbot, please backport to Go 1.16.

Go 1.16 added previously-missing path validation paths and enabled module mode by default, both of which made this check much more likely to be triggered.

I don't think this needs to be backported to Go 1.15. In 1.15, the `go` command had a bug that caused these paths not to be diagnosed if they are already present in some module in the build list. That bug was incidentally fixed in [CL 258298](https://golang.org/cl/258298) for Go 1.16. (This issue was exposed by the combination of fixing that bug and enabling module mode by default in Go 1.16.)

**Comment by ianamason** [comment] 2021-03-09 17:27
That sounds like good news for my toolset. Sounds like in the next minor release I will be able
to use the go tool to create a module file for my toolset, and move on without changing the name of the executable, and subsequent user outrage :-)

Right?

**Comment by bcmills** [comment] 2021-03-09 22:26
> Sounds like in the next minor release I will be able
> to use the go tool to create a module file for my toolset, and move on without changing the name of the executable, and subsequent user outrage

Yep, that's the plan at the moment! (We try to minimize user outrage to the extent that that is feasible. 🙂)

**Closed** 2021-03-10 03:09 UTC
Labels: GoCommand, NeedsFix
