### ISSUE TITLE
x/tools/gopls:textedit calculation wrong  and dochighlight wrong

### ISSUE THREAD

**Issue by taigacute** [golang/go#33075] opened 2019-07-12 12:43 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.12.7
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pendragon/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/pendragon/workstation"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ct/5f1j4fl91mz_sdsl_3ksr5ph0000gp/T/go-build325873838=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. create two function
2. use these function with `go`
3.got error completion
![image](https://user-images.githubusercontent.com/41671631/61128723-4db9d080-a4e5-11e9-98b4-acb3302c0242.png)
4. check the document of function by coc.nvim ,dont get any highlight,the doc should markdown.
![image](https://user-images.githubusercontent.com/41671631/61129024-17c91c00-a4e6-11e9-8bb3-67061f523755.png)

### What did you expect to see?
`go recevier()`

### Log
check the lsp log.  response from server
![image](https://user-images.githubusercontent.com/41671631/61128794-7a6de800-a4e5-11e9-8acd-d5f9308708f5.png)
client
![image](https://user-images.githubusercontent.com/41671631/61128804-822d8c80-a4e5-11e9-897f-f4d16a997dac.png)

full log
[gopls.log](https://github.com/golang/go/files/3386442/gopls.log)

**Comment by stamblerre** [comment] 2019-07-12 18:37
Duplicate of https://github.com/golang/go/issues/29313

**Closed by stamblerre** 2019-07-12 18:37 UTC
Labels: gopls
