### ISSUE TITLE
affected/package: vcs: 1.18 requires a new minimum git version

### ISSUE THREAD

**Issue by howardjohn** [golang/go#51467] opened 2022-03-04 00:38 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.18rc1
</pre>

### Does this issue reproduce with the latest release?

Yes, it is a regression in 1.18rc1 from 1.17

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/gobin"
GOCACHE="/gocache"
GOENV="/home/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18rc1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/work/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3992160965=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

`go mod tidy`

### What did you expect to see?

Success

### What did you see instead?

```
[0mtest/envoye2e/stackdriver_plugin/cmd/main.go:1: : error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping. (typecheck)
// Copyright 2019 Istio Authors
```

The weird thing is this seems semi-inconsistent. It fails 100% of the time in our CI after updating to go 1.18, but running locally its inconsistent. Sometimes I can run it 100 times in a row with the same issue, while other times it works 10000 times in a row. I cannot explain this - possibly a cache...?

### Root cause

The root cause seems to be https://github.com/golang/go/commit/b1a53ece68d. I think an approach similar to https://github.com/golang/go/commit/90066bf06a9b10b3b222a289934b93723bb788d6 can be used and is more compatible. I will send a fix myself if I am able to get the contribution setup for Go working.

**Comment by seankhliao** [comment] 2022-03-04 00:41
Duplicate of #51253

**Closed by seankhliao** 2022-03-04 00:41 UTC
