### ISSUE TITLE
proposal: exp/slices: Support aggregations with CompactFunc

### ISSUE THREAD

**Issue by salvacorts** [golang/go#64554] opened 2023-12-05 11:45 UTC
### Proposal Details

Would be great to support aggregating duplicated items in a sorted slice using [slices.CompactFunc][1]  if the items are pointers.

For example, given this struct:
```go
type user struct {
	id     string
	scores int
}
```
And a sorted slice of users (by id), I’d like to compact users by removing duplicates and summing up scores. Would be nice to be able to use CompactFunc as follows:

```go
compacted := slices.CompactFunc(users, func(next, prev *user) bool {
  if prev.getID() == next.getID() {
    return true
  }
  return false
})
```

To avoid changing `CompactFunc`, we can introduce a new function `CompactAggregate` with the following signature:
```go
func CompactAggregate[S ~[]E, E any](s S, eqAgg func(*E, *E) bool) S {
```
I've created this draft PR to demo it: https://github.com/golang/exp/pull/68

[1]: https://go.googlesource.com/exp/+/refs/heads/master/slices/slices.go#369

**Comment by seankhliao** [comment] 2023-12-05 13:00
I don't think we guaranteed the comparisons used in a way that would be useful for aggregation
I believe this is a duplicate of previously declined fold proposals

**Closed by seankhliao** 2023-12-05 13:00 UTC
Labels: Proposal
