### ISSUE TITLE
x/tools/go/packages: all "no Go files in" errors get assigned to single package as a single error

### ISSUE THREAD

**Issue by dominikh** [golang/go#32755] opened 2019-06-24 18:26 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 linux/amd64
go version devel +c11f6c4929 Fri Jun 21 21:24:47 2019 +0000 linux/amd64
</pre>

### What did you do?
https://play.golang.org/p/Y0ANYGkISpa

### What did you expect to see?
Two packages, sandbox/empty1 and sandbox/empty2, each with one error

### What did you see instead?
One package, sandbox/empty2, with one error but whose error message contains two errors for two separate packages.

```
$ go run foo.go
2019/06/24 20:22:59 sandbox/empty2
2019/06/24 20:22:59 1
2019/06/24 20:22:59 packages.Error{Pos:"", Msg:"go build sandbox/empty2: no Go files in /home/dominikh/prj/src/sandbox/empty2\ngo build sandbox/empty1: no Go files in /home/dominikh/prj/src/sandbox/empty1", Kind:0}
```

/cc @matloob

**Comment by dominikh** [comment] 2019-06-24 18:29
The `Mode` can be further reduced to `packages.NeedImports | packages.NeedExportsFile` and still reproduce the bug.

The underlying `go list` call seems to behave correctly:

```
$ go list -e -json -compiled=false -test=false -export=true -deps=false -find=false -- sandbox/foo
go build sandbox/empty2: no Go files in /home/dominikh/prj/src/sandbox/empty2
go build sandbox/empty1: no Go files in /home/dominikh/prj/src/sandbox/empty1
{
	"Dir": "/home/dominikh/prj/src/sandbox/foo",
	"ImportPath": "sandbox/foo",
	"Name": "pkg",
	"Target": "/home/dominikh/prj/pkg/linux_amd64/sandbox/foo.a",
	"Root": "/home/dominikh/prj/",
	"Match": [
		"sandbox/foo"
	],
	"Incomplete": true,
	"GoFiles": [
		"foo.go"
	],
	"Imports": [
		"sandbox/empty1",
		"sandbox/empty2"
	],
	"Deps": [
		"sandbox/empty1",
		"sandbox/empty2"
	],
	"DepsErrors": [
		{
			"ImportStack": [
				"sandbox/foo",
				"sandbox/empty1"
			],
			"Pos": "/home/dominikh/prj/src/sandbox/foo/foo.go:3:8",
			"Err": "no Go files in /home/dominikh/prj/src/sandbox/empty1"
		},
		{
			"ImportStack": [
				"sandbox/foo",
				"sandbox/empty2"
			],
			"Pos": "/home/dominikh/prj/src/sandbox/foo/foo.go:4:8",
			"Err": "no Go files in /home/dominikh/prj/src/sandbox/empty2"
		}
	]
}
```

though the extra output on stderr is noteworthy.

**Comment by dominikh** [comment] 2019-06-24 18:59
Worse yet, if we attempt to load a healthy package in addition to `sandbox/foo` – e.g. `packages.Load(cfg, "sandbox/foo", "strconv")` – then the healthy package will not be returned by packages.Load. We still only get exactly one package, `sandbox/empty2`, with exactly one packages.Error.

**Comment by sauyon** [comment] 2019-07-02 09:26
I'm reasonably sure that this is caused by [this special case](https://github.com/golang/tools/blob/fb37f6ba82613749b0b522aa509da78361849fc3/go/packages/golist.go#L802) in the golist driver.

This might be a bug on the older go1.1 version which I assume is supported (?) but doesn't seem to be an issue on my version (go1.12.6).

Either way, I think the correct way to correct this is to add special JSON nodes to `stdout`, then, when parsing, remove them if there is already a node for them.

**Comment by matloob** [comment] 2019-10-30 00:47
This seems to have been fixed on head. Please reopen if not.

Running with the same gopath layout on Go 1.13 with GO111MODULE=off, and the following test code:
```
package main

import (
	"log"

	"golang.org/x/tools/go/packages"
)

func main() {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedImports | packages.NeedDeps | packages.NeedExportsFile | packages.NeedFiles | packages.NeedCompiledGoFiles | packages.NeedTypesSizes,
	}
	pkgs, err := packages.Load(cfg, "sandbox/foo")
	if err != nil {
		log.Println(err)
	}
	for _, pkg := range pkgs {
		log.Println(pkg)
		for _, err := range pkg.Errors {
			log.Printf("%#v", err)
		}
		for _, pkg := range pkg.Imports {
			log.Println(pkg)
			for _, err := range pkg.Errors {
				log.Printf("%#v", err)
			}
		}
	}
}
```

produces the following output for me:
```
2019/10/29 20:47:05 sandbox/foo
2019/10/29 20:47:05 sandbox/empty2
2019/10/29 20:47:05 packages.Error{Pos:"src/sandbox/foo/foo.go:4:8", Msg:"no Go files in /Users/matloob/Desktop/gopath/src/sandbox/empty2", Kind:0}
2019/10/29 20:47:05 sandbox/empty1
2019/10/29 20:47:05 packages.Error{Pos:"src/sandbox/foo/foo.go:3:8", Msg:"no Go files in /Users/matloob/Desktop/gopath/src/sandbox/empty1", Kind:0}
```

**Closed by matloob** 2019-10-30 00:47 UTC
Labels: NeedsInvestigation, Tools
