### ISSUE TITLE
net: net.LookupNS fails to give correct results on subdomain lookups

### ISSUE THREAD

**Issue by devilHorns13** [golang/go#52639] opened 2022-05-01 11:41 UTC
### What version of Go are you using?
<pre>
go1.19-dd97871282 Thu Apr 14 18:00:13 2022 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/user/go-linux-amd64-bootstrap/bin"
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/go-linux-amd64-bootstrap"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/go-linux-amd64-bootstrap/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.19-dd97871282 Thu Apr 14 18:00:13 2022 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2021158862=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Tried to get the NS record behind `images.google.com`
https://go.dev/play/p/SW4nHobmka1?v=gotip

### What did you expect to see?
The correct NS records for the corresponding domain name

### What did you see instead?
<pre>lookup images.google.com on 1.1.1.1:53: no such host</pre>

The result conflict with, e.g., what I see on [dns.google](https://dns.google/resolve?name=images.google.com&type=NS)

**Comment by DasSkelett** [comment] 2022-05-01 12:40
`images.google.com.` is CNAMEd to `images.l.google.com.`, which doesn't have any NS records. Usually you only find NS records at the root of a zone and as "delegation" in the parent zone of a domain.
Your dns.google link also confirms this by showing only the SOA record in the response.

The `no such host` error message is a bit misleading because it isn't an NXDOMAIN, yeah, "no such record" would fit better.
But an error being returned is correct, because there is no NS record for this subdomain.

**Comment by seankhliao** [comment] 2022-05-01 13:00
See above
Closing as not a bug

**Closed by seankhliao** 2022-05-01 13:00 UTC
