### ISSUE TITLE
x/website: unusual zoom on MacOS Chrome viewing go.dev

### ISSUE THREAD

**Issue by drornir** [golang/go#49815] opened 2021-11-27 09:44 UTC
### What is the URL of the page with the issue?
 
 go.dev
 
### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
  
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/12601664/143676125-c85df86f-c216-45ba-8177-56ee06b98d1c.png)
 
 
 
### What did you do?
 
browsed to golang.org 
 
### What did you expect to see?
 
 the old design, or any design that has a normal desktop-friendly UI
 
### What did you see instead?

This huge, mobile-first design, on my 13" laptop

If you have to do it for marketing purposes, I get it, but put a link at the header for an actual developers-friendly site.

**Comment by fzipp** [comment] 2021-11-27 10:38
I have a 13" laptop as well, but the proportions don't look like that. I suspect that you have an older generation MacBook Air with a lower screen resolution, and the style sheets falsely switch to mobile mode. This probably can be fixed by improving the CSS media queries.

**Comment by seankhliao** [comment] 2021-11-27 10:46
That screenshot looks like 250% scaling on your side.
@drornir is there anything affecting the scaling on your browser?

For reference 100% (on a 1080p resolution screen) looks like:
![2021-11-27-114118](https://user-images.githubusercontent.com/11343221/143677845-fc95e238-7242-42eb-a5cc-b88232eeb92a.png)

**Comment by rsc** [comment] 2021-11-30 18:44
I can't reproduce this either. @drornir, if you can help us reproduce it, we'd be happy to fix that. But there's only one web site now. See https://go.dev/blog/tidy-web for more. Will leave open for a few days in hope of getting a repro case.

**Closed** 2021-12-27 10:56 UTC
Labels: WaitingForInfo
