### ISSUE TITLE
net/http: error messages are not introspectable

### ISSUE THREAD

**Issue by lavalamp** [golang/go#9383] opened 2014-12-18 21:02 UTC
I just reviewed a PR with the line `case err.Error() == "http: can't write HTTP request on broken connection"`. That's brittle code, and it's hard to test in a way that ensures it stays in sync with any changes to the error message wording in net/http--but there's no way to improve upon it given the errors the http package emits.

Possible improments:
- net/http could predeclare its errors
- or make a custom error type

Any mechanism is fine as long as it lets the compiler check that people are referring to the error they intend to.

(I realize this is probably low priority.)

**Comment by rsc** [comment] 2015-06-29 04:24
Too late for Go 1.5.

**Comment by bradfitz** [comment] 2018-07-24 00:01
Closing as duplicate of #9405 (which has more detail & discussion).

**Closed by bradfitz** 2018-07-24 00:01 UTC
