### ISSUE TITLE
x/tools/cmd/ssadump: doesn't compile

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19550] opened 2017-03-14 21:39 UTC
The x/tools build is broken across the board:

https://build.golang.org/log/5caa4ff768a880d6f306a9546cb060eb5e592c29 etc:
```
# golang.org/x/tools/cmd/ssadump
2017/03/14 14:27:21 duplicate symbol golang.org/x/tools/go/ssa.(*BuilderMode).String (types 1 and 1) in main and $WORK/golang.org/x/tools/go/ssa.a(_go_.o)
```

**Comment by ianlancetaylor** [comment] 2017-03-14 21:49
I think that this was broken by https://golang.org/cl/38139 and I think that the fix is in https://golang.org/cl/38156.

**Comment by ianlancetaylor** [comment] 2017-03-14 21:49
CC @dr2chase @philhofer

**Comment by philhofer** [comment] 2017-03-14 22:06
Confirmed dupe of #19548.

**Comment by josharian** [comment] 2017-03-14 22:10
Closing as dup.

**Closed by josharian** 2017-03-14 22:10 UTC
Labels: NeedsFix
