### ISSUE TITLE
proposal: text/template: Template.Scan

### ISSUE THREAD

**Issue by 3052** [golang/go#66707] opened 2024-04-06 19:23 UTC
### Proposal Details

currently you can implement `fmt.Fprintf` like this:

~~~go
package main

import (
   "io"
   "os"
   "text/template"
)

func fprintf(w io.Writer, format string, a any) error {
   text, err := new(template.Template).Parse(format)
   if err != nil {
      return err
   }
   return text.Execute(w, a)
}

func main() {
   var a struct {
      Hello string
      World string
   }
   a.Hello = "hello"
   a.World = "world"
   fprintf(os.Stdout, "http://example.com/{{.Hello}}/{{.World}}", a)
}
~~~

but you cannot do the opposite. ideally some method like this would exist:

~~~go
func (t *Template) Scan(rd io.Reader, data any) error
~~~

then you could implement `fmt.Fscanf`:

~~~go
package main

import (
   "io"
   "os"
   "text/template"
)

func fscanf(r io.Reader, format string, a any) error {
   text, err := new(template.Template).Parse(format)
   if err != nil {
      return err
   }
   return text.Scan(r, a)
}

func main() {
   r := strings.NewReader("http://example.com/hello/world")
   var a struct {
      Hello string
      World string
   }
   fscanf(r, "http://example.com/{{.Hello}}/{{.World}}", &a)
}
~~~

**Comment by rittneje** [comment] 2024-04-06 20:18
I think this is a duplicate of #52473.

**Closed** 2024-04-06 20:29 UTC
Labels: Proposal
