### ISSUE TITLE
proxy.golang.org: cache not expiring

### ISSUE THREAD

**Issue by denysvitali** [golang/go#44230] opened 2021-02-12 13:49 UTC
### What version of Go are you using (`go version`)?

Not relevant

### What did you do?

Pushed a new release of https://github.com/swisscom/mssql-always-encrypted (v0.1.2), checked https://sum.golang.org/lookup/github.com/swisscom/mssql-always-encrypted@v0.1.2: the release is not there.

After > 5 min the cache still hasn't refreshed and I still get a 410.

Drafting a new release doesn't work either: I've tagged version `v0.1.3` to check if the problem was on my side but apparently even that version doesn't work :(

### What did you expect to see?

200 OK + checksum

### What did you see instead?

410 Gone

```
not found: github.com/swisscom/mssql-always-encrypted@v0.1.2: invalid version: unknown revision v0.1.2
```

---

Is the sum server having problem connecting to GitHub maybe? I'm not sure if it's just me: https://index.golang.org/index?since=2021-02-12T13:45:00.0Z

**Comment by denysvitali** [comment] 2021-02-12 13:54
After waiting another 5 minutes, the cache expired and now it's working 😁

**Comment by bcmills** [comment] 2021-02-12 17:54
Duplicate of #38065

**Closed by bcmills** 2021-02-12 17:54 UTC
