### ISSUE TITLE
runtime: spanBytesAlloc underflow on windows 32bit

### ISSUE THREAD

**Issue by botvs** [golang/go#18043] opened 2016-11-25 01:36 UTC
![bug](https://cloud.githubusercontent.com/assets/3872209/20612217/75ae53d2-b2f2-11e6-93e9-3f3a120c5229.png)

this happened in windows 32 bit some times, never happen in linux 64 bit,
Very difficult to reproduce.

**Comment by botvs** [comment] 2016-11-25 01:38
go version is 1.7.3

**Comment by aclements** [comment] 2016-12-01 16:32
@botvs, thanks for the report. I think I know what's going on. You mentioned that this is "very difficult to reproduce", which suggests that you have at least been able to reproduce it. If I sent you a patch to add some additional debugging to the runtime to confirm my suspicion, how hard do you think it would be for you to test?

**Comment by aclements** [comment] 2016-12-01 16:34
As for what I think it going on: if mcentral.cacheSpan is preempted by mark termination between the call to deductSweepCredit and the call to reimbuseSweepCredit, then mheap_.spanBytesAlloc will be zeroed and reimbuseSweepCredit will underflow. Probably the right fix is for reimbuseSweepCredit to check if we're still in the same GC cycle as the deductSweepCredit it's supposed to be balanced with and just do nothing if we're not.

**Comment by aclements** [comment] 2016-12-01 20:27
On the other hand, mcentral.cacheSpan happens while g.m.locks != 0, so it's not, in fact, preemptible.

**Comment by aclements** [comment] 2016-12-01 21:32
Another plausible but incorrect theory is that mheap_.spanBytesAlloc wasn't 8-byte aligned, since 1.7.3's runtime/internal/atomic.Xadd64 didn't check this (it does on master), but it appears it is in fact aligned. (And I'm pretty sure Xadd64 genuinely doesn't require alignment on 386 like the other 64-bit atomics do, though that's hard to confirm.)

**Comment by botvs** [comment] 2016-12-02 01:05
I'm sorry, I just saw this. How to patch it ?

**Comment by aclements** [comment] 2016-12-02 19:05
@botvs, are you set up to compile your own Go toolchain? If not, that's the first step to patching. If so, I can upload a change to the code review tool and you can patch that in pretty easily. I'll have to figure out exactly what debug info I want, though, since none of my theories so far have actually panned out.

**Comment by aclements** [comment] 2016-12-13 18:59
@botvs, ping.

**Comment by nathanjackson** [comment] 2016-12-14 18:51
Hello, I am facing the exact same issue in Go 1.6.3 installed from the Fedora EPEL on CentOS 7.3.1611 64-bit. Any chance your patch might fix it? Its really not clear where the issue is coming from on my end.

**Comment by aclements** [comment] 2016-12-14 18:55
@nathanjackson, can you post more details, such as the error and stack trace?

I don't have a patch to fix this yet because I don't know what the problem is and haven't been able to reproduce this locally. If I made a patch against Go 1.6.3 to add more debugging information, would you be able to apply it and reproduce the issue?

**Comment by nathanjackson** [comment] 2016-12-14 18:57
@aclements I should be able to do that. I'll see what I can gather and post.

If it helps at all, setting `GODEBUG` to `gcstoptheworld=2` prevents the crash.

**Comment by nathanjackson** [comment] 2016-12-14 19:41
@aclements Is there any way I can e-mail you my stack trace? I don't think I can post it publicly.

**Comment by aclements** [comment] 2016-12-14 20:47
@nathanjackson, you can email it to austin <at> google.com. Or feel free to redact it. I really only need to see the frames in package runtime.

**Comment by nathanjackson** [comment] 2016-12-14 21:39
Alright, so I have to get approval in order to send the stack trace unfortunately. However, I can say it looks nearly identical to the above stack trace from OP's screenshot.

**Comment by aclements** [comment] 2016-12-20 03:58
@botvs or @nathanjackson, if either of you could try to reproduce this with https://go-review.googlesource.com/34612 applied to your Go tree, it could really help me figure this out. It's based on current master, but I'm pretty sure you can cherry-pick it cleanly to any 1.7 checkout using the following command: `git fetch https://go.googlesource.com/go refs/changes/12/34612/1 && git cherry-pick FETCH_HEAD`

**Comment by nathanjackson** [comment] 2016-12-20 14:00
@aclements You should have an e-mail.

I will see what I can do with your patch. Something interesting that I found on my end, if I use 1.7.3 or better, the error does go away, but one of three things happens, randomly.

1. The program executes completes without error.
2. Panic with a leftover defer error.
3. Deadlock, the program seems to just stop executing.

All of these issues go away with `GODEBUG=gcstoptheworld=1`.

**Comment by aclements** [comment] 2017-01-09 17:02
@nathanjackson, thanks for the traceback. Does your application use unsafe, cgo, or fail in `-race` mode? I ask because the original report shows a reasonable argument to `reimburseSweepCredit` (even though it then crashes because the global state is wrong), but your traceback shows a huge argument to `reimbuseSweepCredit`, which suggests a different root cause in which the span state (or possibly the stack) got corrupted. Incorrect use of unsafe, cgo, or having races could also cause the other failures you're seeing.

**Comment by nathanjackson** [comment] 2017-01-10 14:10
@aclements Sorry for not getting back with you sooner. I looked into this issue and it turns out that one of the libraries I was using was incorrectly using cgo\unsafe. Writing my own interface around the C library corrected the issue in 1.6.3 and 1.7.4. Thank you for your help.

**Comment by aclements** [comment] 2017-01-10 15:36
@nathanjackson, no worries. Sorry for taking so long to look at your traceback. Thanks for the update!

**Comment by aclements** [comment] 2017-01-10 15:40
@botvs, were you able to try the [patch](https://go-review.googlesource.com/34612) that I posted? Also, does your application use unsafe, cgo, or fail in `-race` mode (I should have asked this at the beginning).

**Comment by aclements** [comment] 2017-01-17 19:26
Moving to Go 1.9. Hopefully we'll get some more diagnostics from Go 1.8.

**Closed** 2017-04-21 17:42 UTC
Labels: NeedsInvestigation
