### ISSUE TITLE
x/tools/gopls/test: TestCommandLine/GOPATH/Renames/b_Goodbye failure with `apply unified gave wrong result`

### ISSUE THREAD

**Issue by bcmills** [golang/go#54601] opened 2022-08-22 16:55 UTC
```
            --- FAIL: TestCommandLine/GOPATH/Renames/b_Goodbye (0.28s)
                rename.go:24: rename failed with /ramdisk8GB/workdir-host-aix-ppc64-osuosl/tmp/TestCommandLine_GOPATH3623923662/lsp/src/golang.org/x/tools/internal/lsp/rename/b/b.go:20:6-11 Goodbye
…
                format.go:84: apply unified gave wrong result for /ramdisk8GB/workdir-host-aix-ppc64-osuosl/tmp/TestCommandLine_GOPATH3623923662/lsp/src/golang.org/x/tools/internal/lsp/rename/b/b.go expected:
                    b.go:
                    package b
```

`greplogs -l -e 'apply unified gave wrong result' --since=2022-02-01`
[2022-08-11T14:11:53-3807419-2340d37/aix-ppc64](https://build.golang.org/log/f0a9431ec5e31d6a5912a147811dfb0885f25886)

**Comment by findleyr** [comment] 2023-03-28 16:16
CC @pjweinb @adonovan : is this a dupe of our previous bug in ApplyUnified, which I think is fixed?

**Comment by adonovan** [comment] 2023-05-10 19:35
> is this a dupe of our previous bug in ApplyUnified, which I think is fixed?

Perhaps? In any case, this failure hasn't been observed in the builder or otherwise for 6 months. Closing.

**Closed by adonovan** 2023-05-10 19:35 UTC
Labels: gopls, Tools
