### ISSUE TITLE
proposal: path/filepath: pattern alternatives

### ISSUE THREAD

**Issue by VanoDevium** [golang/go#53270] opened 2022-06-07 16:40 UTC
It would be very cool to add the ability to use alternatives in the glob and match patterns.

Syntax of alternatives can be any:
- `(alt1|alt2|alt3)`
- `(alt1,alt2,alt3)`
- `{alt1|alt2|alt3}`
- `{alt1,alt2,alt3}`

Please look at code example:
```go
package main

import (
	"fmt"
	"path/filepath"
)

func main() {
	fmt.Println(filepath.Match("/home/dir/*.(txt,pdf)", "/home/dir/resume.txt"))
	fmt.Println(filepath.Match("/home/dir/*.(txt,pdf)", "/home/dir/resume.png"))
}
```

Output:
```sh
true <nil>
false <nil>
```

> I apologize if I'm suggesting something that has already been suggested. As it seemed to me, I looked for references, but did not find.

**Comment by seankhliao** [comment] 2022-06-07 17:05
Duplicate of #32745

**Closed by seankhliao** 2022-06-07 17:05 UTC
Labels: Proposal
