### ISSUE TITLE
x/tools/go/analysis/passes/fieldalignment: runtime error: index out of range

### ISSUE THREAD

**Issue by napei** [golang/go#43465] opened 2021-01-02 03:16 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
 Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\natty\AppData\Local\go-build
set GOENV=C:\Users\natty\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\natty\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\natty\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\natty\Desktop\ent\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\natty\AppData\Local\Temp\go-build202576274=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Enabled the following config in vscode inside `settings.json`

```json
  "gopls": {
    "analyses": {
      "fieldalignment": true
    },
    "usePlaceholders": true,
    "staticcheck": true
  },
```

`gopls` log: https://pastebin.com/raw/QmedfAZM

Log with trace enabled (not much different): https://pastebin.com/raw/6Zpm0VUw

### What did you expect to see?

No errors, and fieldalignment should pick up on the following test struct 

```go
type test struct {
	field1 bool
	field2 float64
	field3 int32
}
```

### What did you see instead?

Field alignment doesn't run when looking at source code inside a sub-folder/another package. When I add the above struct to a file in the root directory of the project, fieldalignment works fine, with hints on the struct.

**Comment by stamblerre** [comment] 2021-01-05 19:12
/cc @leitzler for the panic

> Field alignment doesn't run when looking at source code inside a sub-folder/another package. When I add the above struct to a file in the root directory of the project, fieldalignment works fine, with hints on the struct.

Can you give a repro example? Analysis only runs on packages with open files, so it's possible that's what you're seeing.

**Comment by leitzler** [comment] 2021-01-05 22:17
Yes, a repro would be helpful. This might be fixed already by CL 278372 that is merged to master but not 0.6.x.

**Comment by napei** [comment] 2021-01-06 01:57
I made a repro here https://github.com/napei/alignment-test
I noticed in a simple package with a main file and a sub package it works fine, but in this repro it doesn't.

A file to open for testing this would be `./ent/test.go`, it's all generated code from ent which I use a lot, but I would assume it's all able to be linted without panicking.

This is typical of the codebase I'm working in at the moment, but that has about 40 more files in it.

**Comment by napei** [comment] 2021-01-06 02:00
> Analysis only runs on packages with open files, so it's possible that's what you're seeing.

I have specifically disabled file previews in vscode for that reason. I don't know why they thought that was a good feature 😄 

```json
"workbench.editor.enablePreviewFromQuickOpen": false,
"workbench.editor.enablePreview": false,
```

**Comment by napei** [comment] 2021-01-06 02:05
Oh interesting. When I embed a struct it panics.

<details>
<summary>Panic</summary>

```go
type test struct {
	field1 bool
	field3 float64
	field2 int32
}


type Test struct {
	test `json:"-"`
	ID int `json:"id,omitempty"`
	Field1 bool `json:"field1,omitempty"`
	Field2 float64 `json:"field2,omitempty"`
	Field3 int32 `json:"field3,omitempty"`
}
```
</details>

<details>
<summary>No Panic</summary>

```go
type test struct {
	field1 bool
	field3 float64
	field2 int32
}


type Test struct {
	ID int `json:"id,omitempty"`
	Field1 bool `json:"field1,omitempty"`
	Field2 float64 `json:"field2,omitempty"`
	Field3 int32 `json:"field3,omitempty"`
}
```
</details>

**Comment by leitzler** [comment] 2021-01-06 20:08
I tried your repro with CL 278372 applied and I'm not able to reproduce it.

**Comment by stamblerre** [comment] 2021-01-06 20:11
OK, so sounds like this is fixed at master. @napei, ok to close?

**Comment by napei** [comment] 2021-01-06 20:17
Sure. I'll wait for a release 🙂

**Closed** 2021-01-06 20:27 UTC
Labels: NeedsInvestigation, Tools
