### ISSUE TITLE
os/exec: No stderr is shown in the os/exec error

### ISSUE THREAD

**Issue by finn-ball** [golang/go#44270] opened 2021-02-15 15:27 UTC
### What version of Go are you using (`go version`)?
go version go1.15.7 linux/amd64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/finn/.cache/go-build"
GOENV="/home/finn/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/finn/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/finn/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build623746363=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

This doesn't run on the playground. Run this, for example, in a non-git directory.

The docs imply we should be able to see at least some of the stderr:
https://golang.org/src/os/exec/exec.go?s=6278:6323#L461

```
package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	if err := execute(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

// Simple git execution.
func execute() error {
	cmd := exec.Command("git", "status")

	if err := cmd.Start(); err != nil {
		return err
	}

	if err := cmd.Wait(); err != nil {
		if e, ok := err.(*exec.ExitError); ok {
			fmt.Println(e)
			fmt.Println(string(e.Stderr))
		}
		return err
	}

	return nil
}
```

### What did you expect to see?
The stderr.

### What did you see instead?
Nothing.

**Comment by seankhliao** [comment] 2021-02-15 20:14
The doc for `os/exec.ExitError.Stderr` says (emphasis added):

> 	// Stderr holds a subset of the standard error output from the
>	// **Cmd.Output** method if standard error was not otherwise being
>	// collected.

No other methods are documented to store Stderr

Closing as working as intended

**Closed by seankhliao** 2021-02-15 20:14 UTC
Labels: NeedsInvestigation
