### ISSUE TITLE
x/mobile: `gomobile bind` on M1 panics when building for iOS if the Android NDK is installed

### ISSUE THREAD

**Issue by iamcalledrob** [golang/go#47296] opened 2021-07-20 01:05 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/rob/Library/Caches/go-build"
GOENV="/Users/rob/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/rob/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/rob/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/rob/Code/push/xplat/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3l/mj1p0_6x3dnb850mkd9ph8b00000gn/T/go-build3886656969=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I ran `gomobile bind -target ios` on an Apple Silicon mac with the Android NDK installed (and therefore `ANDROID_NDK_HOME` exported to my path).

### What did you expect to see?
The bind command execute and build for iOS.

### What did you see instead?
```
panic: unsupported GOARCH: arm64

goroutine 1 [running]:
main.archNDK(...)
	/Users/rob/go/pkg/mod/golang.org/x/mobile@v0.0.0-20210716004757-34ab1303b554/cmd/gomobile/env.go:298
main.(*ndkToolchain).Path(0x140000a3bc0, 0x140000180d1, 0x2f, 0x10506e3c2, 0x5, 0x0, 0x140000a39f8)
```

There seem to be 2 compounding issues leading to this:
1. `archNDK()` panics when run on arm64. (Ideally, the NDK could be invoked using Rosetta if the GOARCH is arm64)
2. env.go attempts to set up the Android cross-compiler (invoking `archNDK()`) even when the gomobile target is iOS.

This leads to the issue that simply having the NDK installed causes a panic—even when building for iOS only.

**Comment by AlexRouSg** [comment] 2021-07-20 03:22
Looks like a duplicate of #46464

**Comment by seankhliao** [comment] 2021-07-20 19:53
Duplicate of #46464

**Closed by seankhliao** 2021-07-20 19:53 UTC
Labels: mobile
