### ISSUE TITLE
proposal: affected/package: make(chan (int, error))

### ISSUE THREAD

**Issue by martindrlik** [golang/go#57146] opened 2022-12-07 19:21 UTC
Hello guys, I would like to discuss if there is some other way to send and receive multiple values via channel. For instance, I would like to send and receive int and error. Normally, I would create struct. Maybe we can make it more concise like `(int, error)`

```go
ch := make(chan (int, error))
// sending
...
ch <- (0, nil)
ch <- func() (int, error) {...}()
...
f := func() (int, error) {...}
ch <- f()
...
// receiving
result, err := <-ch
func(n int, err error) {...}(<-ch)
```

What do you think? Sorry if there is already existing proposal or if there is some conclusion already.

**Comment by seankhliao** [comment] 2022-12-07 19:34
Duplicate of #41148

**Closed by seankhliao** 2022-12-07 19:34 UTC
Labels: Proposal
