### ISSUE TITLE
Zero value of time.Time does not remain equal under JSON marshal/unmarshal

### ISSUE THREAD

**Issue by daishi** [golang/go#12141] opened 2015-08-13 21:22 UTC
Please see:

  http://play.golang.org/p/VXUScwoGAH

I can see and understand why the final equality test returns false, but at the same time given that the default timezone is Z, would nevertheless expect the result to be true.

**Comment by cespare** [comment] 2015-08-13 21:30
The locations aren't the same, as you can see from your printouts.

This is why `Time.Equal` exists. See http://play.golang.org/p/fEfW-7nfZV.

**Comment by daishi** [comment] 2015-08-13 22:19
I think you are missing my point. The time.Time documentation specifically says:

  The zero value of type Time is January 1, year 1, 00:00:00.000000000 UTC.

therefore one would reasonably expect a zero-value time.Time (as constructed by time.Time{}) to compare equal to the one in which the timezone is explicitly UTC rather than nil.

**Comment by cespare** [comment] 2015-08-13 22:28
Here are some other quotes from the time docs:

> Note that the Go == operator compares not just the time instant but also the Location. Therefore, Time values should not be used as map or database keys without first guaranteeing that the identical Location has been set for all values, which can be achieved through use of the UTC or Local method.

and

> Two times can be equal even if they are in different locations. For example, 6:00 +0200 CEST and 4:00 UTC are Equal. This comparison is different from using t == u, which also compares the locations.

This issue is more or less a duplicate of #10089.

**Comment by ianlancetaylor** [comment] 2015-08-13 23:02
Yes, working as expected.

**Closed by ianlancetaylor** 2015-08-13 23:02 UTC
