### ISSUE TITLE
proposal: builtin: add min() and max() functions as builtins

### ISSUE THREAD

**Issue by p7r0x7** [golang/go#54182] opened 2022-08-01 18:32 UTC
I've noticed a lot of packages (especially standard ones) use these functions when they probably should be sharing the function globally rather than building it for each individual package that uses them. Yes, I'm aware this would break a lot of existing code so this can't be in Go1, but maybe it can be added somewhere as standard?

**Comment by seankhliao** [comment] 2022-08-01 18:50
No need for them to be builtins, they can be library functions

**Comment by seankhliao** [comment] 2022-08-01 18:50
Duplicate of #50019

**Closed by seankhliao** 2022-08-01 18:50 UTC
Labels: Proposal
