### ISSUE TITLE
cmd/go: unable to install sub-module with buildmode=shared with go modules but $GOPATH works

### ISSUE THREAD

**Issue by affanshahid** [golang/go#37034] opened 2020-02-05 05:05 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/project/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build808455707=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I am trying to compile a project with `-buildmode=shared`. My project has the following file structure:
```
go.mod
main.go
util
   /util.go
```

My `go.mod` file:
```
module example.com/affan/project

go 1.13
```

and my `main.go` simply imports `example.com/affan/project/util` and runs some code. Now following [this stackoverflow link](https://stackoverflow.com/questions/1757090/shared-library-in-go) I am trying to compile my project in a way such that my main binary links to an `.so` of `example.com/affan/project/util`.

### What did you expect to see?
I expected it to compile a binary and link to an `so` file of my sub-package

### What did you see instead?
When I run `go install -buildmode=shared -linkshared example.com/affan/project/util`, I get the following:

```
panic: runtime error: slice bounds out of range [:-2]

goroutine 1 [running]:
cmd/go/internal/load.(*Package).load(0xc000096900, 0xc0001359f0, 0xc000045180, 0x0, 0x0)
        /usr/local/go/src/cmd/go/internal/load/pkg.go:1491 +0x36db
cmd/go/internal/load.loadImport(0xc000280200, 0x7fff3c03febc, 0x1e, 0xc000024024, 0xd, 0x0, 0xc0001359f0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/cmd/go/internal/load/pkg.go:511 +0xdf2
cmd/go/internal/load.PackagesAndErrors(0xc000020090, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/cmd/go/internal/load/pkg.go:1982 +0x398
cmd/go/internal/load.PackagesForBuild(0xc000020090, 0x1, 0x1, 0x9b9a00, 0x0, 0x0)
        /usr/local/go/src/cmd/go/internal/load/pkg.go:2028 +0x5d
cmd/go/internal/work.runInstall(0xea4340, 0xc000020090, 0x1, 0x1)
        /usr/local/go/src/cmd/go/internal/work/build.go:483 +0x44
main.main()
        /usr/local/go/src/cmd/go/main.go:189 +0x57f
```

I thought maybe I'm not specifying the path correctly so I tried. `./util` as the final argument as well, but it had the same result.

### It works with $GOPATH
I removed `go.mod` and copied everything to under `$GOPATH/src` with the correct paths. After that running the commands from the above link works perfectly, I get a binary linked to an `.so` of my util package just as I expect. So this is definitely something to do with go-modules (or maybe me doing something wrong?)

**Comment by odeke-em** [comment] 2020-02-05 17:37
Thank you for this report @affanshahid and welcome to the Go project!

Interesting bug report and crash! Kindly paging @jayconrod @bcmills 
In the meantime @affanshahid, could you please try with Go1.14 beta as per https://golang.org/dl/#unstable and see if the problem persists?

**Comment by bcmills** [comment] 2020-02-05 17:54
Duplicate of #35759

**Closed by bcmills** 2020-02-05 17:54 UTC
Labels: NeedsInvestigation

**Comment by odeke-em** [comment] 2020-02-05 18:02
@bcmills thanks for the follow-up! Shall we then recommend that the user expect it the fix in Go1.14?
