### ISSUE TITLE
math: math.E returns incorrect result

### ISSUE THREAD

**Issue by EvilRedHorse** [golang/go#66198] opened 2024-03-08 17:14 UTC
### Go version

go version go1.20.11 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.11"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4055892220=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

Attempted to print e with 64 significant digits. 

command:
```fmt.Printf(("%"+"."+"64"+"f"), math.E)```

### What did you see happen?

output:
2.7182818284590450907955982984276488423347473144531250000000000000

precision:
inaccurate past 15 digits of precision

### What did you expect to see?

command:
```echo "scale=64;e(1)" | bc -l```

output: 
2.7182818284590452353602874713526624977572470936999595749669676277

precision:
accurate to requested 64 significant digits.

relates to:
#9545 #9546 #25270

**Comment by mknyszek** [comment] 2024-03-08 17:48
I'm pretty sure when you go to print it, the constant is converted from an untyped float into a float64, and a float64 actually has anywhere near 64 decimal digits of precision.

https://pkg.go.dev/math/big#Float on the other hand may be able to do what you want. For example, https://go.dev/play/p/XysLL10W6GL. (I copied the constant from the `math` package, which only has 62 digits after the decimal point, but you could add and represent more.)

I'm not sure there's anything actionable here. This seems working as intended.

CC @griesemer but closing for now.

**Closed by mknyszek** 2024-03-08 17:48 UTC

**Comment by EvilRedHorse** [comment] 2024-03-08 18:02
e is inaccurate to the requested 64 significant digits.
The example you give does not use math.E instead you have directly input/output a float.
Why would math/big package be needed?

**Comment by ianlancetaylor** [comment] 2024-03-08 22:44
The Go `float64` type, which is what your example is using, is not accurate to 64 decimal digits.

See https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html for more background.

**Comment by EvilRedHorse** [comment] 2024-03-09 17:47
1. So a **float64** can *represent* 64 digits but only be *precise* to a **double**.

2. *math/big* is required to be more precise.

3. *flag* does not have a *math/big* **float**.

relates to:
#45751 
> "Based on the discussion this proposal will clearly not be accepted, so closing. Please comment if you disagree. Thanks."

Therefore using "out of the box" golang math/flag you are limited to 15 significant digits.

**Comment by ianlancetaylor** [comment] 2024-03-09 22:25
Fortunately the flag package is extensible.
