### ISSUE TITLE
cmd/go: project depending on project using modules not building: "error loading module requirements"

### ISSUE THREAD

**Issue by sab84** [golang/go#31929] opened 2019-05-09 01:38 UTC
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.12.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/me/localrepo"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/me/golangrepo/content-config/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0d/wcqqd_f523b517dqn0ghdwqc1qjkyx/T/go-build771363169=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I have a project "a", which uses modules, that has dependency on code that is another project "b" which uses modules. 

go.mod line # 1 in project "b": 
`module <private_gitlab_repo>/<group>/<subgroup>/<project "b" name>`

import statement in project "a": 
`"<private_gitlab_repo>/<group>/<subgroup>/<project "b" name>.git/internal/parser"`

### What did you expect to see?
go build should complete correctly

### What did you see instead?
`
go: <private_gitlab_repo>/<group>/<subgroup>/<project "b" name>.git@v0.0.0-20190508223317-420ea8aa2597: parsing go.mod: unexpected module path "<private_gitlab_repo>/<group>/<subgroup>/<project "b" name>"
go: error loading module requirements
`

What am I doing wrong ?

**Comment by beoran** [comment] 2019-05-09 06:15
I think you don't need the `.git` in the `import` statement.

**Comment by sab84** [comment] 2019-05-09 18:15
@beoran , that didn't work either. 

`build <private_gitlab_repo>/<group>/<subgroup>/<project "a">: cannot load <private_gitlab_repo>/<group>/<subgroup>/<project "b">/internal/parser: cannot find module providing package <private_gitlab_repo>/<group>/<subgroup>/<project "b">/internal/parser`

**Comment by sab84** [comment] 2019-05-09 18:17
Also, I am able to depend on other internal project with the ".git" in the import statement and the go build command correctly updated the mod file with the project reference. The only difference is that this third project is not using modules.

**Comment by andybons** [comment] 2019-05-13 19:17
@jayconrod @bcmills

**Comment by bcmills** [comment] 2019-05-13 19:52
The path-mismatch error is due to the lack of `.git` suffix in the `module` directive.
The `cannot find module providing package` error is #26232.

This looks like a duplicate of #26232. In the interim, you should be able to work around it using:

```
replace <private_gitlab_repo>/<group>/<subgroup>/a v0.0.0-20190508223317-420ea8aa2597 => <private_gitlab_repo>/<group>/<subgroup>/a.git v0.0.0-20190508223317-420ea8aa2597
```

**Comment by bcmills** [comment] 2019-05-13 19:55
Actually, for GitLab specifically this is #29888.

**Comment by bcmills** [comment] 2019-05-13 19:55
Duplicate of #29888

**Closed by bcmills** 2019-05-13 19:55 UTC
Labels: NeedsInvestigation, modules
