### ISSUE TITLE
x/dl: download returns a forbidden error

### ISSUE THREAD

**Issue by maraino** [golang/go#45603] opened 2021-04-16 20:17 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

macOS / linux (amd64)

### What did you do?

```sh
$ go get golang.org/dl/go1.16.3
$ go1.16.3 download
go1.16.3: download failed: server returned Forbidden checking size of https://storage.googleapis.com/golang/go1.16.3.darwin-amd64.tar.gz
```

You can see a similar error with any other version or OS.

### What did you expect to see?

The download to work and go1.16.3 installed

### What did you see instead?
```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.
</Details>
</Error>
```

**Comment by smasher164** [comment] 2021-04-16 20:48
I see the same behavior on all the other Go versions as well. 

/cc @cagedmantis @dmitshur @toothrot

**Comment by cagedmantis** [comment] 2021-04-16 20:54
I've been able to reproduce this. We are investigating.

**Comment by FiloSottile** [comment] 2021-04-16 21:25
This was due to a failed configuration change and should be fixed now, my apologies.

**Closed by FiloSottile** 2021-04-16 21:25 UTC
Labels: NeedsFix
