### ISSUE TITLE
encoding/json: embedded *struct implementing UnmarshalJSON is nil and panics on Unmarshal

### ISSUE THREAD

**Issue by sabey** [golang/go#36716] opened 2020-01-23 21:36 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jackson/.cache/go-build"
GOENV="/home/jackson/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jackson/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build498302187=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
https://play.golang.org/p/DZoQ9ro3jv7
my parent struct inherits `UnmarshalJSON(data []byte) error` from the embedded struct

https://github.com/golang/go/blob/master/src/encoding/json/decode.go#L492
in the `indirect()` function
`if u, ok := v.Interface().(Unmarshaler); ok {` is true, but since the embedded struct is not allocated it will cause a nil pointer exception

```
encoding/json.(*decodeState).object(0xc0002ccd10, 0x5e9bc0, 0xc000132f98, 0x16, 0xc0002ccd38, 0xc0003abe7b)
/usr/local/go/src/encoding/json/decode.go:667 +0x220b
```

### What did you expect to see?
`&{&{}}`

### What did you see instead?
`&{<nil>}`

Unmarshal should allocate the embedded struct so that we can call UnmarshalJSON()
this would only be relevant if there were only 1 embedded struct which implements UnmarshalJSON

**Comment by toothrot** [comment] 2020-01-23 22:27
Thanks for the thoughtful issue report. This is a duplicate of #30148. Feel free to discuss there if you have more to contribute.

**Closed by toothrot** 2020-01-23 22:27 UTC
