### ISSUE TITLE
plugin package segfaulting on macOS

### ISSUE THREAD

**Issue by andreiamatuni** [golang/go#17816] opened 2016-11-06 03:26 UTC
### What version of Go are you using (`go version`)?
go version devel +2b445c7 Sat Nov 5 23:59:04 2016 +0000 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/andrei/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/HEAD-2b445c7/libexec"
GOTOOLDIR="/usr/local/Cellar/go/HEAD-2b445c7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8q/gmgztx313w55mrr0cqfy0ksw0000gn/T/go-build177985919=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?

compiled the example code from here: https://tip.golang.org/pkg/plugin/

I have a single file called test.go (in directory testlib) which contains:

```
package main

// // No C code needed.
import "C"

import "fmt"

var V int

func F() { fmt.Println("Hello, number %d", V) }
```

built this with ```go build -buildmode=plugin```

this results in a file called testlib.so

I have a seperate file, in another directory called main.go which contains:

```
package main

import "plugin"

func main() {

	p, err := plugin.Open("testlib.so")
	if err != nil {
		panic(err)
	}
	v, err := p.Lookup("V")
	if err != nil {
		panic(err)
	}
	f, err := p.Lookup("F")
	if err != nil {
		panic(err)
	}
	*v.(*int) = 7
	f.(func())() // prints "Hello, number 7"
}
```

### What did you expect to see?

```"Hello, number 7"```

### What did you see instead?
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x4545cfb]

goroutine 1 [running]:
runtime.throw(0x407161b, 0x2a)
	/usr/local/Cellar/go/HEAD-2b445c7/libexec/src/runtime/panic.go:596 +0x95 fp=0xc420049c50 sp=0xc420049c30
runtime.sigpanic()
	/usr/local/Cellar/go/HEAD-2b445c7/libexec/src/runtime/signal_unix.go:253 +0x2db fp=0xc420049ca0 sp=0xc420049c50
invalid spdelta  0x404df30 0x4545cfb 0x28654 -1
(0x40be44000, 0xc42009a00000, 0x400)
	?:0 +0x4f7dcb fp=0xc420049ca7 sp=0xc420049ca0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/HEAD-2b445c7/libexec/src/runtime/asm_amd64.s:2184 +0x1
```

**Comment by 0xmohit** [comment] 2016-11-06 03:41
Duplicate of #17804.

**Closed** 2016-11-06 04:10 UTC
