### ISSUE TITLE
cmd/go: add tests describing 'go run' behavior with GO111MODULE=on

### ISSUE THREAD

**Issue by myitcv** [golang/go#26709] opened 2018-07-31 13:08 UTC
Please answer these questions before submitting your issue. Thanks!

This _might_ be a duplicate of/covered by the solution to #26639, but I wanted to create a separate issue for `go run` because that could be considered to be a particularly special case amongst the various commands.

### What version of Go are you using (`go version`)?

```
go version devel +b294fe9b0a Tue Jul 31 02:04:53 2018 +0000 linux/amd64
```

### Does this issue reproduce with the latest release?

n/a: testing with tip.

### What operating system and processor architecture are you using (`go env`)?

Not available directly because of #26639, but:

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPROXY=""
GORACE=""
GOROOT="/home/myitcv/gos"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build675792232=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

```
export GO111MODULE=on
cd $(mktemp -d)
cat <<EOD > run.go
package main

import "fmt"

func main() {
        fmt.Println("Hello, world!")
}
EOD
go run run.go
```

### What did you expect to see?

If my assumption that a `go.mod` _shouldn't_ be required is correct, zero exit code and:

```
Hello, world!
```

### What did you see instead?

Non-zero exit code and:

```
go: cannot find main module root; see 'go help modules'
```

**/cc** @rsc @bcmills

**Comment by myitcv** [comment] 2018-08-01 06:51
Problem remains in:

```
go version devel +6b9c782f9f Wed Aug 1 00:57:00 2018 +0000 linux/amd64
```

**Comment by bcmills** [comment] 2018-08-01 18:41
I think this is intended behavior.

If `run.go` only imports standard-library packages, then I guess you could argue that it shouldn't require a `go.mod` file, but certainly if it imports anything from other modules we need to know what versions of those modules to use.

It seems awkward to have to look at the set of imports to determine whether we need a module definition: I'd rather we require it unconditionally.

**Comment by myitcv** [comment] 2018-08-01 18:46
Actually, I don't know why I thought this should work. You're quite right; if I can create an arbitrary `.go` file, I can trivially create an arbitrary `go.mod` file in the same directory, for example.

I'd be happy for this to be closed unless you think there's actually something to decide?

**Comment by bcmills** [comment] 2018-08-01 20:37
I'm not sure, but we can certainly add some tests to `cmd/go/testdata/script` to describe what happens for that situation.

**Comment by myitcv** [comment] 2018-08-06 16:58
Confirmed that the repro in https://github.com/golang/go/issues/26709#issuecomment-409692199 is solved by https://go-review.googlesource.com/c/go/+/127796 (the fix for #26722)

Will leave this open for, as @bcmills suggests, adding such a test case.

**Comment by natefinch** [comment] 2018-09-12 21:00
Please don't make `go run` require a go.mod.  if anything, it should generate a temporary go.mod automatically and then throw it away.

**Comment by bcmills** [comment] 2018-09-12 21:27
> Please don't make `go run` require a go.mod.

I would expect `go run pkg@version` to work with or without one (using the same mechanism as for #24250).

It's less clear to me whether `go run` in general should work outside a module. If the solution to #24250 is some sort of per-user fallback `go.mod` then `go run` should clearly use that, but if we resolve #24250 in some other way then I'm not so confident. (So maybe that's an argument for the per-user fallback approach?)

**Comment by rsc** [comment] 2018-11-28 18:39
@bcmills, is this fixed by the "in-memory empty go.mod" behavior we added?

**Comment by bcmills** [comment] 2018-12-04 16:01
Yes, `go run` is now tested (and works outside of a module).

**Closed by bcmills** 2018-12-04 16:01 UTC
Labels: NeedsDecision, Testing, modules
