### ISSUE TITLE
make.bash: drop bash as a build dependency

### ISSUE THREAD

**Issue by mcandre** [golang/go#41698] opened 2020-09-29 18:58 UTC
The bash build scripts can be rewritten in terms of pure POSIX sh, simplifying the bootstrap development environment.

**Comment by ALTree** [comment] 2020-09-29 19:13
Would this solve any actual problem? I don't think I've ever seen anyone complaining about `make.bash` being a bash script in the last 6 years.

**Comment by ianlancetaylor** [comment] 2020-09-29 19:47
In practice we can only do this if there is some way to write a test to ensure that we never regress back to using bash-isms.  I don't know how to write such a test but perhaps there is some way.

(I also agree that I don't see why this is a problem in practice.)

**Comment by beoran** [comment] 2020-09-30 04:37
This can be checked easily using shellcheck https://github.com/koalaman/shellcheck, or chechbashisms https://linux.die.net/man/1/checkbashisms. The former has the additional benefit of detecting common errors in the shell script.

**Comment by apparluk** [comment] 2020-09-30 05:51
If the OP is referring to, _e.g._, using the Almquist shell.

ash (Kenneth Almquist's ash shell)

A lightweight (92K) Bourne compatible shell.  Great for machines with
low memory, but does not provide all the extras of shells like bash,
tcsh, and zsh.  Runs most shell scripts compatible with the Bourne
shell.  Note that under Linux, most scripts seem to use at least some
bash-specific syntax.  The Slackware setup scripts are a notable
exception, since ash is the shell used on the install disks.  NetBSD
uses ash as its /bin/sh.

**Comment by davecheney** [comment] 2020-09-30 06:02
What’s the driver for this? The resource usage of various shells compared to the 1.3gb of ram needed to compile some of the internal packages in the compiler.

**Comment by mvdan** [comment] 2020-09-30 13:26
While I generally agree that it's nice to be portable, I also don't see why Bash would be a problem today if it hasn't been a problem for the past decade.

There are also a dozen other bash scripts scattered across the repository, such as `src/all.bash` and `src/iostest.bash`. Translating all of them would be quite a bit of work and surely introduce a number of bugs, even if we're careful.

**Comment by apparluk** [comment] 2020-09-30 17:07
https://golang.org/cl/114176
cmd/vet: eliminate use of Perl in tests

The ticket associated with the above had substantive content favourable to pursue that merge.

I suggest closing.

**Comment by mvdan** [comment] 2020-10-11 18:32
A heads up for others wanting to contribute to this thread; it's very unlikely that the author will actually provide any more information here, see https://github.com/golang/go/issues/41739#issuecomment-703303783. Unless you support this change, it's probably not worth your time to reply.

**Comment by beoran** [comment] 2020-10-12 08:01
I actually support this change together with introducing shellcheck, but seeing that this has been working as is for years, and that there are more urgent priorities, I don't mind if this issue is postponed or closed  either.

**Comment by timkuijsten** [comment] 2020-10-14 05:07
Just had my first experience with Go, which was nice. The one thing that surprised me a little bit was that bash was required to build. On OpenBSD the standard shell is a hardened ksh. bash is avoided everywhere in base so I had to install that, no biggie, but the question I would phrase in the spirit of portability and reducing dependencies is "why require more if technically all you need is POSIX shell"? I'm wondering if such a change would be desirable, aside from the question who's going to make it happen.

**Comment by ianlancetaylor** [comment] 2020-10-14 05:47
I don't think the suggested change is very important but I think it would be fine if someone wants to work on it and has some way to prevent backsliding.  (I don't think the packages mentioned above are going to be useful in that regard--we certainly don't want the Go build to depend on them: that would be worse than depending on bash.  But if someone can come up with a workable approach, great.)

**Comment by illiliti** [comment] 2020-10-14 17:55
Patch that allows building go without bash - https://github.com/kisslinux/community/blob/d99595e575a471698032dbad0cd2c9977d6b0c79/community/go/patches/posix-build.patch . As you see, there is no huge dependency on bash and everything can be implemented in POSIX shell

**Comment by ianlancetaylor** [comment] 2020-10-14 18:29
Thanks.  Now, how do we prevent backsliding?

**Comment by beoran** [comment] 2020-10-14 18:37
Perhaps a test runner that runs shellcheck or checkbashisms? This is more
of a test, and less a build requirement.

Op wo 14 okt. 2020 20:29 schreef Ian Lance Taylor <notifications@github.com

**Comment by feld** [comment] 2020-10-14 19:48
> Thanks. Now, how do we prevent backsliding?

One CI/CD host that isn't Linux

**Comment by periish** [comment] 2020-10-14 19:51
Note that some shells implement common bashisms; dash implements == in test(iirc), for instance.

**Comment by nu8** [comment] 2020-10-14 22:16
I think this is a good idea - I am will to support this if someone I willing to merge it. I have Shell experience:

https://stackoverflow.com/users/1002260

**Comment by timkuijsten** [comment] 2020-10-14 22:30
FWIW, I've started a separate discussion to get some feedback from a community I'm familiar with, in order to prevent being a loud and chatty newbie overhere before getting to the point. ;-) For anyone interested: https://lobste.rs/s/lzc7ac/make_bash_drop_bash_as_build_dependency

**Comment by khm** [comment] 2020-10-15 07:54
Duplicate of #3235

**Closed** 2020-10-29 19:48 UTC
Labels: NeedsInvestigation, WaitingForInfo
