### ISSUE TITLE
cmd/compile: unexpected amd64 error

### ISSUE THREAD

**Issue by beenshi** [golang/go#32701] opened 2019-06-20 02:33 UTC
Some simple code went wrong (only) on amd64.

The following go code 

	func main() {
		b := []byte{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}
		temp := make([]byte, 4)
		for i := int64(0);i<4; i ++ {
			temp[0] = b[i*4 + 2]
			temp[1] = b[i*4 + 3]
			temp[2] = b[i*4 + 0]
			temp[3] = b[i*4 + 1]
			n := binary.BigEndian.Uint32(temp)
			fmt.Printf("%x\n", n)
		}
	}

is expected to print

	3040102
	7080506
	b0c090a
	f100d0e

That is true on arm/arm64/386, but false on amd64.

	apuser@tj07598pcu:~/Desktop$ GOARCH=arm go run main.go 
	3040102
	7080506
	b0c090a
	f100d0e
	apuser@tj07598pcu:~/Desktop$ GOARCH=386 go run main.go 
	3040102
	7080506
	b0c090a
	f100d0e
	apuser@tj07598pcu:~/Desktop$ GOARCH=amd64 go run main.go 
	3040000
	7080102
	b0c0506
	f10090a
	apuser@tj07598pcu:~/Desktop$ GOARCH=arm64 go run main.go 
	3040102
	7080506
	b0c090a	
	f100d0e
	apuser@tj07598pcu:~/Desktop$ go version
	go version devel +71a6a44428 Wed Jun 19 23:17:25 2019 +0000 linux/amd64

**Comment by sheepbao** [comment] 2019-06-20 02:38
the same code!
```
go version
go version go1.12.5 darwin/amd64

go run main.go              
3040000
7080102
b0c0506
f10090a

go run -gcflags '-N' main.go
3040102
7080506
b0c090a
f100d0e
```

**Comment by av86743** [comment] 2019-06-20 09:13
@beenshi: What do you use to run arm/arm64 transparently on linux/amd64?

> That is true on arm/arm64/386, but false on amd64.
> 
> ```
> apuser@tj07598pcu:~/Desktop$ GOARCH=arm go run main.go 
> 3040102
> 7080506
> b0c090a
> f100d0e
> apuser@tj07598pcu:~/Desktop$ GOARCH=386 go run main.go 
> 3040102
> 7080506
> b0c090a
> f100d0e
> apuser@tj07598pcu:~/Desktop$ GOARCH=amd64 go run main.go 
> 3040000
> 7080102
> b0c0506
> f10090a
> apuser@tj07598pcu:~/Desktop$ GOARCH=arm64 go run main.go 
> 3040102
> 7080506
> b0c090a	
> f100d0e
> apuser@tj07598pcu:~/Desktop$ go version
> go version devel +71a6a44428 Wed Jun 19 23:17:25 2019 +0000 linux/amd64
> ```

**Comment by beenshi** [comment] 2019-06-20 09:37
@av86743 

ubuntu 18.04
apt-get install qemu -y

**Comment by cherrymui** [comment] 2019-06-20 15:48
Seems a dup of #32680?

**Comment by cherrymui** [comment] 2019-06-20 15:57
cc @dr2chase

**Comment by dr2chase** [comment] 2019-06-20 16:05
Dupe of  #32680. (It at least shares the same fix.)

**Closed by dr2chase** 2019-06-20 16:05 UTC
