### ISSUE TITLE
x/net:tls.dial with socks5 proxy 

### ISSUE THREAD

**Issue by M4rcellxD** [golang/go#24434] opened 2018-03-17 03:41 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 

### Does this issue reproduce with the latest release?
----

### What operating system and processor architecture are you using (`go env`)?
windows/amd64

### What did you do?
----
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
----

### What did you see instead?
----

### My problem
i want to use socks5 proxy with tls.dial because i am writing a chat application that should use an socks5 proxy and tls/ssl encryption and i think its current not easily possible to do that thanks for any help maybe i don't get it @the moment how i can do it

**Comment by ALTree** [comment] 2018-03-17 11:18
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2018-03-17 11:18 UTC
