### ISSUE TITLE
runtime: `TestVDSO` failures

### ISSUE THREAD

**Issue by mknyszek** [golang/go#62105] opened 2023-08-17 16:33 UTC
```
#!watchflakes
post <- test == "TestVDSO"
```

2023-08-07 19:31 linux-arm64-longtest go@d367ec6a runtime.TestVDSO ([log](https://build.golang.org/log/33ffcead408d16bc2d88fd73e1129ac1d9f8f847))
2023-08-07 21:16 darwin-amd64-longtest go@008ab9ad runtime.TestVDSO ([log](https://build.golang.org/log/3ce891428f1219c2499c6838d4a584b67f66778f))
2023-08-07 19:31 linux-arm64-longtest go@d367ec6a runtime.TestVDSO ([log](https://build.golang.org/log/33ffcead408d16bc2d88fd73e1129ac1d9f8f847))

**Comment by bcmills** [comment] 2023-08-21 15:44
Note that the `linux-s390x-ibm` failure was a timeout (#60413), not corruption like the other two.

**Comment by bcmills** [comment] 2023-08-21 15:48
I think this is a duplicate of #62101, and probably fixed by https://go.dev/cl/516856.

**Closed** 2023-08-21 16:09 UTC
Labels: NeedsInvestigation, compiler/runtime
