### ISSUE TITLE
godoc no work in go module

### ISSUE THREAD

**Issue by hhiew** [golang/go#34032] opened 2019-09-03 05:44 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.9 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\shanwei\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\gopath
set GOPROXY=https://mirrors.aliyun.com/goproxy/
set GORACE=
set GOROOT=D:\Go
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=e:\go_mod_team\chrent_erp\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\shanwei\AppData\Local\Temp\go-build311701150=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I run godoc  in console!

### What did you expect to see?

Other packages loading for team's package

### What did you see instead?
Other packages loading for go path,no loading team's package

**Comment by agnivade** [comment] 2019-09-03 06:13
Thank you for filing the issue @hhiew. It is a duplicate of https://github.com/golang/go/issues/33655. Please feel free to subscribe to that. Thanks.

**Closed by agnivade** 2019-09-03 06:13 UTC
