### ISSUE TITLE
go/types: "missing return" error should be "unreachable statement"

### ISSUE THREAD

**Issue by BigET** [golang/go#65794] opened 2024-02-19 16:33 UTC
### Go version

go version go1.22rc2 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/biget/.cache/go-build'
GOENV='/home/biget/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/edi/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/edi/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/lib/go-1.22'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/lib/go-1.22/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22rc2'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/user/1300/go-build1494716450=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

The following function should either compile without problem or give a "unreachable code", but it gives "missing return".
```
func bad_return(x bool) int8 {
	switch x {
	case true:
		return 1
		break
	default:
		return 0
	}
}
```

It might has something to do with the order of validation.

If I add a return to the end of the function, then I get "unreachable code".

Here is the same function in the [playground](https://go.dev/play/p/H37q1Y7RPWR)

### What did you see happen?

./prog.go:15:1: missing return

### What did you expect to see?

./prog.go:11:3: unreachable code

**Comment by findleyr** [comment] 2024-02-19 23:43
The error about unreachable code is a vet check, not a type checker error.
The type checker implements a rather strict definition of terminating statements, specified [here](https://go.dev/ref/spec#Terminating_statements). Per that specification, the type checker is correct.

We could improve this, but I'm not sure it's a common enough mistake, nor confusing enough, to warrant the immediate attention implied by my assignment. I'm moving this into the backlog, though I'll discuss with @griesemer in our next meeting.

**Comment by griesemer** [comment] 2024-02-20 20:56
The reported error is correct per the spec. I don't think we should do anything here.

I note that the program with an additional `return` at the end actually [runs in the playground](https://go.dev/play/p/J1asR3inJlY), even with the "unreachable code" error.

**Comment by findleyr** [comment] 2024-02-29 19:18
Agreed, closing this as working as intended.

**Closed by findleyr** 2024-02-29 19:18 UTC
Labels: NeedsDecision
