### ISSUE TITLE
x/tools/cmd/goimports: MergeLine panic on weird input

### ISSUE THREAD

**Issue by josharian** [golang/go#20229] opened 2017-05-03 23:57 UTC
```go
package m
import("t"
"g"
"_"
"s")
```

Run goimports on that. Result:

```
panic: illegal line number

goroutine 1 [running]:
go/token.(*File).MergeLine(0xc420054ba0, 0x5)
	/Users/josh/go/tip/src/go/token/position.go:149 +0x145
golang.org/x/tools/go/ast/astutil.DeleteNamedImport(0xc4200132c0, 0xc42001ad80, 0x0, 0x0, 0xc420011241, 0x1, 0x100ea01)
	/Users/josh/src/golang.org/x/tools/go/ast/astutil/imports.go:267 +0xc3e
golang.org/x/tools/imports.fixImports(0xc4200132c0, 0xc42001ad80, 0x7fff5fbff9ea, 0x4, 0x21, 0x600, 0x1321770, 0xc42001ad80, 0x0)
	/Users/josh/src/golang.org/x/tools/imports/fix.go:207 +0x5d3
golang.org/x/tools/imports.Process(0x7fff5fbff9ea, 0x4, 0xc420168000, 0x21, 0x600, 0x1321770, 0x0, 0x4, 0xc420041da8, 0x0, ...)
	/Users/josh/src/golang.org/x/tools/imports/imports.go:58 +0x718
main.processFile(0x7fff5fbff9ea, 0x4, 0x0, 0x0, 0x1322660, 0xc42000c018, 0x1, 0x0, 0x0)
	/Users/josh/src/golang.org/x/tools/cmd/goimports/goimports.go:136 +0x139
main.gofmtMain()
	/Users/josh/src/golang.org/x/tools/cmd/goimports/goimports.go:273 +0x1fa
main.main()
	/Users/josh/src/golang.org/x/tools/cmd/goimports/goimports.go:189 +0x32
```

Discovered (accidentally) by go-fuzz.

Low priority, but probably an easy fix.

cc @bradfitz

**Comment by fatih** [comment] 2017-05-28 22:47
The problem is inside astutil pkg (the `DeleteNamedImport` function) and can be reproduced by adding a case to tests. It's because it tries to merge a line by assuming the last line of an import declaration is always in form of: 

```
import (
"foo"
)
```

However in this case it's:

```
import (
"foo")
```

After removing `foo`, we need to check that it's safe to merge. I have a fix for this, should I open a CL directly or do I need to claim this issue before I can open the CL (according to the [Contribution Guide](https://golang.org/doc/contribute.html#Design))?

**Comment by josharian** [comment] 2017-05-28 23:10
Just mail a CL. I'm happy to review.

**Closed** 2017-05-29 01:35 UTC
Labels: HelpWanted, NeedsFix
