### ISSUE TITLE
fix base64

### ISSUE THREAD

**Issue by koggle** [golang/go#28185] opened 2018-10-13 09:18 UTC
https://github.com/golang/go/pull/28184

**Comment by koggle** [comment] 2018-10-13 14:42
fmt.Println(base64.RawStdEncoding.DecodeString("ABCD"))
	fmt.Println(base64.RawStdEncoding.DecodeString("ABC"))
	fmt.Println(base64.RawStdEncoding.DecodeString("AB"))
	fmt.Println(base64.RawStdEncoding.DecodeString("A"))

	fmt.Println(base64.RawStdEncoding.DecodeString("ABC="))
	fmt.Println(base64.RawStdEncoding.DecodeString("AB=="))

	fmt.Println(base64.RawStdEncoding.DecodeString("ABC?"))
	fmt.Println(base64.RawStdEncoding.DecodeString("AB?"))

//fixed
[0 16 131] <nil>
[0 16] illegal base64 data at input byte 2
[0] illegal base64 data at input byte 1
[] illegal base64 data at input byte 0
[0 16] illegal base64 data at input byte 3
[0] illegal base64 data at input byte 2
[0 16] illegal base64 data at input byte 3
[0] illegal base64 data at input byte 2



//bug
[0 16 131] <nil>
[0 16] <nil>
[0] <nil>
[] illegal base64 data at input byte 0
[] illegal base64 data at input byte 3
[] illegal base64 data at input byte 2
[] illegal base64 data at input byte 3
[] illegal base64 data at input byte 2

**Comment by koggle** [comment] 2018-10-13 14:46
// fix bug, if we don't know the code is padding or nopading

**Comment by mvdan** [comment] 2018-10-14 14:39
To fix a bug, you first need to describe exactly what the bug is and how to reproduce it. Please follow the issue template to do that.

**Comment by koggle** [comment] 2018-10-15 03:37
fix the decodeQuantum and DecodedLen
my code link
https://play.golang.org/p/PRDLxcL5qcL

**Comment by koggle** [comment] 2018-10-15 03:56
https://play.golang.org/p/rRkszDP-6gS

**Comment by ianlancetaylor** [comment] 2018-10-15 04:13
Please tell us what the problem is.  Tell us exactly what you did, exactly what happened, and what you expected to have happen instead.  Thanks.

**Comment by koggle** [comment] 2018-10-15 05:48
@mattn   @ianlancetaylor  @mvdan 
Base64 is not a strict encoding format, it is just a storage format, so I think it is compatible in the decoding phase. The padding is only in the encoding process, and the padding process should ignore the padding.

**Comment by koggle** [comment] 2018-10-15 06:17
For example, I have two connections: aa://1234abc and aa://1234abc= This is not generated by me, it is someone else's, in fact, the content is the same. I need StdEncoding and RawStdEncoding for decoding, which seems very succinct. When you encounter this kind of aa://1234abc?, RawStdEncoding can't solve it at all.

**Comment by mvdan** [comment] 2018-10-15 07:39
This issue is still not following the clear steps outlined in the [issue template](https://github.com/golang/go/blob/master/.github/ISSUE_TEMPLATE). We're not getting any closer to that format, so I'm going to close this issue for now.

@koggle if you think there is a bug in the base64 package, please open a new issue and follow the template, clearly describing the bug and how to reproduce it.

**Closed by mvdan** 2018-10-15 07:39 UTC
Labels: WaitingForInfo

**Comment by mattn** [comment] 2018-10-15 07:51
Do you expect strict encoder? Then please use `RawStdEncoding.Strict().DecodeString(s)`.
