### ISSUE TITLE
cmd/doc: does not generate docs for generic functions that return []T

### ISSUE THREAD

**Issue by ahxxm** [golang/go#48485] opened 2021-09-20 12:32 UTC
### What version of Go are you using (`go version`)?

<pre>
$ gotip version
`devel go1.18-a83a558 Mon Sep 20 00:13:47 2021 +0000`
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

linux amd64

### What did you do?

I wrote a generic function(inside package), run `gotip doc -all -c -u [package-name]`

### What did you expect to see?

expect to see the function signature in output, like `func Intersection[T comparable](slices... []T) []T`

### What did you see instead?

functions that return `[]T` are not printed, others like `func Some[T any](slice []T, pred func(T) bool) bool` are printed

I tried dig into the doc generator, found that
- these functions are now [considered](https://github.com/golang/go/blob/a83a558/src/go/doc/reader.go#L416) to be `factory functions of T`, their associations go `typ.funcs.set` branch instead of `r.funcs.set`
- `cleanupTypes()` [deleted](https://github.com/golang/go/blob/a83a558/src/go/doc/reader.go#L726) T from r.types because it has no definition
- then T is not [included](https://github.com/golang/go/blob/a83a558/src/cmd/doc/pkg.go#L177) in `docPkg.Types`, thus no results are printed

with following ~immature hack~ diff those functions will be printed:
```diff
@@ -429,8 +436,9 @@ func (r *reader) readFunc(fun *ast.FuncDecl) {
                 }
                 // If there is exactly one result type,
                 // associate the function with that type.
-                if numResultTypes == 1 {
+                if numResultTypes == 1 && typ.decl != nil {
```

**Comment by mvdan** [comment] 2021-09-22 17:21
With the suggested change, is the result that the generic function isn't considered a constructor, and is thus rendered as a regular top-level function?

That seems fine to me - if it returns a generic slice type, it's not like we can attach it to any specific type.

Want to send a PR? It should include a test.

**Comment by ahxxm** [comment] 2021-09-27 13:44
@mvdan yup, they are rendered as regular top-level functions

I submitted a PR, is this test case ok..?

**Comment by mvdan** [comment] 2021-09-27 13:59
Thanks! I've left you a review on Gerrit. See https://github.com/golang/go/wiki/GerritBot.

**Comment by jba** [comment] 2022-03-04 15:21
Duplicate of #49477, which was fixed.

**Closed by jba** 2022-03-04 15:21 UTC
Labels: NeedsInvestigation
