### ISSUE TITLE
cmd/compile: return LITERAL on INDEXMAP when map and key are LITERALs

### ISSUE THREAD

**Issue by Segflow** [golang/go#35763] opened 2019-11-21 22:34 UTC
Given
```go
package main
const (
	key = "literalKey"
)
func main() {
	v := map[string]string{
		"literalKey": "v1",
		"anotherkey": "v2",
	}[key]
	_ = v
}
```

When compiled, the compiler will add the different map initialisations methods and assign the different values, then call `mapaccess1`. 

I believe this should not be the case when the map is an OMAPLIT and the key is a LITERAL defined in the map. 

The compiler at compile-time can detect this and change the INDEXMAP operation to LITERAL.

The above code should be similar to this one:
```
package main
const (
	key = "literalKey"
)
func main() {
	v := "v1"
	_ = v
}
```
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

**Comment by mdempsky** [comment] 2020-04-29 04:21
This is a duplicate of #10848.

**Closed by mdempsky** 2020-04-29 04:21 UTC
Labels: NeedsInvestigation
