### ISSUE TITLE
proposal: affected/package: 

### ISSUE THREAD

**Issue by nicolas-andersen** [golang/go#61421] opened 2023-07-18 20:28 UTC
Seeing as Go is a tiny bit more open minded, going from "GOPATH is the best and only way and it will always be this way absolutely totally" to soon removing it entirely, I'm taking my chances.

A lot of people find no value in this error. Furthermore, many people find it as a hinderance, a bad part of the compiler and the language.

And since the way to get rid of it is simply to _ = variable, which changes nothing in the behavior of the compiled program, this error helps solve nothing related to the running of the program. It's just an annoying reminder of "you forgot to explicitly ignore the variable before you debug and then make actual use of it later anyway like it always happens".

Therefore, according to the FAQ's reasoning: "And if it's not worth fixing, it's not worth mentioning.", Go should stop mentioning this.

And just in case, to address the potential question of "But what about people who find this useful?".

Other languages deal with this easily using linters. That way, people who find an use in this error can keep it, while not impeding both the productivity and joy of many others.

**Comment by seankhliao** [comment] 2023-07-18 21:01
Duplicate of #43729

**Closed by seankhliao** 2023-07-18 21:01 UTC
Labels: Proposal
