### ISSUE TITLE
cmd/compile: type..eq function not generated

### ISSUE THREAD

**Issue by dotaheor** [golang/go#24747] opened 2018-04-07 08:47 UTC
### What version of Go are you using (`go version`)?

go version go1.10.1 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What did you do?

```
package main

func main() {
	type T struct {
		a interface{}
		b int
	}
	
	var t T
	var z = [3]T{1: t}
	_ = z == z
}
```

### What did you expect to see?

no errors

### What did you see instead?

weird outputs, not like normal error messages.

```
type..eq.[3]main.T·1: call to external function
main.main: relocation target type..eq.[3]main.T·1 not defined
main.main: undefined: "type..eq.[3]main.T·1"
```

btw, gccgo is ok to compile this program.

**Comment by dotaheor** [comment] 2018-04-07 08:56
1.7 and 1.8 are ok. Not ok since 1.9.0.

**Comment by ALTree** [comment] 2018-04-07 10:09
Since it's not clear from the report: to trigger the error, `go run` has to be used on the reproducer. The error is not printed when building, or when directly running a binary produced by `go build`.

Anyway, I've bisected this to 87065a3c13f373072c1db81dbf3832f0b9e17492 ( cmd/go: don't generate DWARF in the compiler if the linker will discard it).

cc @josharian

**Comment by josharian** [comment] 2018-04-07 13:53
Sounds very similar to https://github.com/golang/go/issues/22444. cc also @mdempsky

**Comment by dotaheor** [comment] 2018-04-07 15:27
Sorry, I miss-typed `main` as `f`.
So the problem is gone if there is a main function.
Which makes it not so serious.

**Comment by josharian** [comment] 2018-04-07 20:00
@dotaheor the error message for package main with no func main is entirely unrelated to this issue. I thought there was already a (very old) issue suggesting a better error message when this happens, but I can't find it.

**Comment by josharian** [comment] 2018-04-07 20:03
I believe that this is a duplicate of #23546.

**Comment by mvdan** [comment] 2018-04-07 20:33
I was about to point out this being a duplicate too. The errors and programs are too similar for this to be a coincidence.

**Comment by ALTree** [comment] 2018-04-08 09:30
Closing as a dup of #23546.

**Closed by ALTree** 2018-04-08 09:30 UTC
Labels: NeedsInvestigation
