### ISSUE TITLE
x/net/webdav: `MOVE` interprets lack of `Overwrite` header incorrectly

### ISSUE THREAD

**Issue by caldwell** [golang/go#67939] opened 2024-06-12 00:41 UTC
### Go version

go version go1.22.4 linux/amd64

### Output of `go env` in your module/workspace:

```shell
not applicable
```

### What did you do?

I'm using a client that issues a `MOVE` but doesn't include an `Overwrite` header to [a Go web server that uses the x/net/webdav code](https://github.com/mholt/caddy-webdav/blob/master/webdav.go#L28).

### What did you see happen?

The Go WebDAV server responds with a 412 HTTP status code and "file already exists" as the error. This is incorrect. 

### What did you expect to see?

I would expect to see a 200 HTTP status code and for the destination file to be overwritten.

It appears that [this line of code is incorrect](https://github.com/golang/net/blob/66e838c6fbf5387ecedc26ce490b5f4d6864a854/webdav/webdav.go#L393) ([google link](https://cs.opensource.google/go/x/net/+/refs/tags/v0.26.0:webdav/webdav.go;drc=ac9987996285eb37e5176356621eec4f5c9b8e83;l=393)).

It's passing `true` to the `overwrite` argument of `moveFiles` only if the `Overwrite` header is `T`, but the [WebDAV RFC section 10.6  states](http://www.webdav.org/specs/rfc4918.html#rfc.section.10.6):

> If the overwrite header is not included in a COPY or MOVE request, then the resource MUST treat the request as if it has an overwrite header of value "T".

Interestingly, the `COPY` code just a few lines before [checks for this correctly](https://github.com/golang/net/blob/66e838c6fbf5387ecedc26ce490b5f4d6864a854/webdav/webdav.go#L376) ([google link](https://cs.opensource.google/go/x/net/+/refs/tags/v0.26.0:webdav/webdav.go;drc=ac9987996285eb37e5176356621eec4f5c9b8e83;l=376)).

**Comment by prattmic** [comment] 2024-06-12 13:22
cc @neild @ianlancetaylor

**Comment by rsc** [comment] 2024-06-12 16:47
Looks like a duplicate of #66059?

**Comment by seankhliao** [comment] 2024-06-15 09:47
Duplicate of #66059

**Closed by seankhliao** 2024-06-15 09:47 UTC
Labels: NeedsInvestigation
