### ISSUE TITLE
cmd/pprof: can't specify pprof symbolz endpoint

### ISSUE THREAD

**Issue by anacrolix** [golang/go#22483] opened 2017-10-29 02:53 UTC
There's no option with `go tool pprof` to specify the endpoint for the symbols. The current method to derive it from the profile path isn't very flexible, such as when the `debug/pprof` endpoints are wrapped into a deeper path, for example `/some/wrapping/path/debug/pprof/`. In this case, pprof determines that the symbols will be at `/symbolz`, when in fact they should be at `/some/wrapping/path/debug/pprof/symbol`.

**Comment by ianlancetaylor** [comment] 2017-10-31 03:57
CC @matloob @rahulchaudhry

**Comment by hyangah** [comment] 2017-11-06 19:51
@anacrolix Given that your PR in google/pprof was merged, is it sufficient if the vendor'ed pprof source is updated? If not, please file an issue to google/pprof.

https://golang.org/cl/75870 update the vendored pprof source recently and should include the PR.

BTW, in what case you will need symbol lookup? My understanding is that go runtime pprof outputs already include symbol info, so pprof would not require extra symbol lookups in most cases. Otherwise, something is not working as intended.

**Comment by anacrolix** [comment] 2017-11-07 03:19
It does appear the fixes were merged in aec345d638fa624f08b7d758e9e173897edc80e8.

Some of the pprof endpoints seem to require the symbols endpoint too. I don't know why this is the case, it appears to be some kind of optimization.

**Closed** 2017-11-07 03:23 UTC
Labels: FeatureRequest, NeedsInvestigation
