### ISSUE TITLE
time: time.now () uses the time zone to modify the problem

### ISSUE THREAD

**Issue by xlango** [golang/go#65228] opened 2024-01-23 08:01 UTC
### Go version

go1.21.5 linux amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.5'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1322244283=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

time.now () Obtains the current time of the linux system

### What did you see happen?

After the time zone of the golang program running in the linux environment is modified, the time zone obtained by using time.now () in the golang program is still the time zone before the modification, and the time zone of the golang program must be updated again. How to solve this problem?

### What did you expect to see?

After updating the time zone of the linux system, the golang program automatically refreshes without restarting

**Comment by seankhliao** [comment] 2024-01-23 08:42
Duplicate of #28020

**Closed by seankhliao** 2024-01-23 08:42 UTC
