### ISSUE TITLE
x/crypto/acme: Update to ACME v2

### ISSUE THREAD

**Issue by titanous** [golang/go#23342] opened 2018-01-05 03:03 UTC
Let's Encrypt has a [staging endpoint](https://community.letsencrypt.org/t/staging-endpoint-for-acme-v2/49605) up for ACME v2 (aka IETF ACME, will be published as an RFC soon). I'm going to start rewriting/updating the client to support the new API, with the thought that we can just replace the previous implementation when Let's Encrypt launches their production v2 endpoint next month.

The package documentation explicitly states there are no stability guarantees and there are effectively no other public ACME servers, so I don't think there's any reason to keep the old implementation around. I will avoid making any changes to public APIs unless necessary.

/cc @x1ddos

**Comment by bradfitz** [comment] 2018-01-05 03:34
Sounds good.

It's more important that the x/crypto/acme/autocert package not change at all. If x/crypto/acme has to change a bit, I'm fine with that.

Thanks!

**Comment by x1ddos** [comment] 2018-01-05 19:35
This is a duplicate of #21081. Let's use the original issue.

**Comment by mvdan** [comment] 2018-01-05 19:38
Thanks for pointing that out.

**Comment by x1ddos** [comment] 2018-01-05 19:40
@titanous I think there might actually be other ACME-compatible servers but even if there aren't any, I know for a fact there exist non-public implementations. I'd like to keep v1 working.

**Closed** 2019-05-07 00:28 UTC
Labels: FrozenDueToAge, NeedsFix
