### ISSUE TITLE
cmd/vet:  printf analysis missing support for %O

### ISSUE THREAD

**Issue by perillo** [golang/go#36385] opened 2020-01-04 16:07 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN="/home/manlio/.local/bin"
GOCACHE="/home/manlio/.cache/go-build"
GOENV="/home/manlio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/manlio/.local/lib/go:/home/manlio/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build809721096=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.13.5 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.13.5
uname -sr: Linux 5.4.6-arch3-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.30.
gdb --version: GNU gdb (GDB) 8.3.1
</pre></details>

### What did you do?

https://play.golang.org/p/unIQ7japybX

### What did you expect to see?

The output of the program
```
0o755
```

Ideally, `go vet`  should report that the constant  `0755` is suspicious, and should suggest to rewrite it as `0o755`.

### What did you see instead?

The error reported by `go vet`
```
Printf format %O has unknown verb O
```

**Comment by robpike** [comment] 2020-01-04 21:14
Indeed, 	golang.org/x/tools/go/analysis/passes/printf/printf.go is missing the 'O' verb.

**Comment by toothrot** [comment] 2020-01-07 18:16
This seems like a duplicate of #29986. I will close this issue in favor of that one. Please let me know if I am mistaken.

**Closed by toothrot** 2020-01-07 18:16 UTC
