### ISSUE TITLE
encoding/xml: No way of creating self terminating nodes with MarshalXML

### ISSUE THREAD

**Issue by nemith** [golang/go#6896] opened 2013-12-05 06:19 UTC
<pre>What steps will reproduce the problem?
If possible, include a link to a program on play.golang.org.
1. <a href="http://play.golang.org/p/o20RjaRdtQ">http://play.golang.org/p/o20RjaRdtQ</a>
2.
3.

What is the expected output?

It would be preferable to get
&lt;RPCElementTarget&gt;&lt;running/&gt;&lt;/RPCElementTarget&gt;

What do you see instead?

There is no way to do self terminating elements.  The best we can do is to do a start
and end element with no chardata.  This does not work for my application.  The closest
output is:
&lt;RPCElementTarget&gt;&lt;running&gt;&lt;/running&gt;&lt;/RPCElementTarget&gt;

Which compiler are you using (5g, 6g, 8g, gccgo)?
6g

Which operating system are you using?
OS X 10.9

Which version are you using?  (run 'go version')
go version go1.2 darwin/amd64

Please provide any additional information below.</pre>

**Comment by SamWhited** [comment] 2017-10-02 21:04
Duplicate of #21399 (this issue is older, but someone has a change against the new issue, so I'm closing this one). Thanks!

**Closed by SamWhited** 2017-10-02 21:04 UTC
