### ISSUE TITLE
cmd/go,internal/goroot: `testdata` is surprisingly treated as a standard-library package

### ISSUE THREAD

**Issue by adonovan** [golang/go#65406] opened 2024-01-31 16:22 UTC
This marker test (of hover) fails spuriously because the name of the package is incorrect:
```
-- go.mod --
module testdata

go 1.18

-- p.go --
package p

type P struct{}

var p P //@hover("P", "P", P)

-- @P --
[`p.P` on pkg.go.dev](https://pkg.go.dev/testdata/p.go#P)
```

The actual value is `command-line-arguments/var/folders/fy/dn6v01n16zjdwsqy_8qfbbxr000_9w/T/Testhoverembed.txt4282490610/001/work`, not `testdata`. I think this is a bug in the metadata. Moving p.go to a subdirectory p fixes the problem. Renaming testdata to example.com ~~makes no difference~~ is an effective workaround.

**Comment by findleyr** [comment] 2024-01-31 16:32
Looks like this is due to the special name `testdata`. Any other module name works.

**Comment by findleyr** [comment] 2024-01-31 16:39
@bcmills @matloob I think this behavior may be a bug, or should be documented at https://go.dev/ref/mod, which appears to mention only testdata _directories_, not module names. It's particularly surprising that e.g. `module foo.com/testdata` seems to work. It's really just the module name `testdata` that does not work.

Repurposing this issue to mitigate the surprise.

**Comment by seankhliao** [comment] 2024-01-31 18:16
supposedly almost all undotted names are considered reserved #37641 ?

**Comment by findleyr** [comment] 2024-01-31 18:23
@seankhliao yes, if that were uniformly enforced I think that would be a fine solution. But any other undotted name works in this case -- `testdata` is unique.

**Comment by adonovan** [comment] 2024-01-31 19:06
I assigned it to myself for the gopls CL above; reassigning to bcmills for the go command behavior.

**Comment by bcmills** [comment] 2024-01-31 19:35
The `go list` behavior looks correct to me:
```
$ go version
go version devel go1.23-d278d5bb Fri Jan 26 04:31:42 2024 +0000 linux/amd64

$ go mod init testdata
go: creating new go.mod: module testdata

$ cat > main.go
package main

func main() {}

$ go list .
ambiguous import: found package testdata in multiple modules:
        testdata (/tmp/tmp.tYGTQN1PjH)
         (/usr/local/google/home/bcmills/sdk/gotip/src/testdata)
```

@adonovan, can you give more concrete steps to reproduce the behavior seen in the marker tests?

**Comment by bcmills** [comment] 2024-01-31 19:39
Hmm. I guess in theory this shouldn't be ambiguous, because the `testdata` directory in the Go standard library doesn't include any `.go` source files:
https://cs.opensource.google/go/go/+/master:src/testdata/

So I think this is arguably a bug in `internal/goroot.IsStandardPackage`, which (as an optimization) only checks for the existence of the directory, not source files within that directory. (That is in contrast to the logic for resolving modules, which requires at least one `.go` source file to be present in order to locate a package.)

**Comment by adonovan** [comment] 2024-01-31 20:37
This session reduces the problem to the two of package.Load calls made by gopls.

First we use the name `testdata.com`:
```
$ cd /tmp/xx
$ cat go.mod
$ echo "module testdata.com" > go.mod
$ echo "package p" > p.go
$ gopackages $(pwd)/... builtin
Go package "testdata.com":
	package p
	has no exported type info
	file /tmp/xx/p.go

Go package "builtin":
	package builtin
	has no exported type info
	file /Users/adonovan/w/goroot/src/builtin/builtin.go
	import "cmp"

$ gopackages file=$(pwd)/p.go
Go package "command-line-arguments":
	package p
	has no exported type info
	file /tmp/xx/p.go
```
Now we use `testdata`:
```
$ echo "module testdata" > go.mod
$ gopackages $(pwd)/... builtin
Go package "testdata":
	package 
	has no exported type info
	-: ambiguous import: found package testdata in multiple modules:
	testdata (/tmp/xx)
	 (/Users/adonovan/w/goroot/src/testdata)

Go package "builtin":
	package builtin
	has no exported type info
	file /Users/adonovan/w/goroot/src/builtin/builtin.go
	import "cmp"

$ gopackages file=$(pwd)/p.go
Go package "command-line-arguments":
	package p
	has no exported type info
	file /tmp/xx/p.go
```

The difference is that the dir/...  query  in the second case matches the testdata directory in the standard library, making it ambiguous. This causes gopls to issue the second query using file=, which creates the ad hoc package.

So this reduces to:
```
$ go list testdata
ambiguous import: found package testdata in multiple modules:
	testdata (/tmp/xx)
	 (/Users/adonovan/w/goroot/src/testdata)
```
So the question is: is testdata really a standard package?

The same behavior occurs when the go.mod name conflicts with any other standard library directory name, such as `encoding` or `fmt`, even if it has no .go files, like `testdata` or `text`. Is that a bug? Not sure.

**Comment by matloob** [comment] 2024-02-05 15:47
@bcmills. Do you think we should change IsStandardImportPath (and the moduleindex variant of it) to check to see that there's at least one .go file in the directory?

**Comment by bcmills** [comment] 2024-02-05 16:14
We probably should, yeah. We can probably get rid of the call to `os.Stat` and use `ReadDir` instead, although it may be somewhat more expensive. I wonder if we should also cache the results using a `sync.Map`. 🤔

**Comment by matloob** [comment] 2024-02-05 17:24
Usually we're using the module index, so we probably won't hit the goroot.IsStandardPackage function so caching it probably wouldn't make a big difference.

**Comment by bcmills** [comment] 2024-02-05 19:27
Oh! I just remembered https://go.dev/cl/504063, which seems very closely related.

I wonder if it would be less error-prone for future maintenance to establish the invariant that `modindex.GetPackage` always returns a non-nil error for a directory that does not contain a Go package, similar to `go/build.ImportDir`.

**Closed** 2024-02-08 18:17 UTC
Labels: NeedsFix, GoCommand, Tools
