### ISSUE TITLE
x/tools/cmd/eg: invalid double expansion

### ISSUE THREAD

**Issue by crawshaw** [golang/go#10937] opened 2015-05-22 20:05 UTC
```
$ cat $GOPATH/src/p/p.go
package p

type S struct{ R int }

type T struct{ *S }

func F(t T) int { return t.R }
```

```
$ cat template.go
package p

import "p"

func before(t p.T) int { return t.R }
func after(t p.T) int  { return t.S.R }
```

Run with `eg -t template.go junk` produces:

```
package p

type S struct{ R int }

type T struct{ *S }

func F(t T) int { return t.S.S.R }
```

One too many .S.

**Comment by josharian** [comment] 2015-05-22 23:46
Dup of #10252? (Sorry about that the lousy title on that bug.)

Incidentally, my workaround for this so far has been to use a very distinctive string for `S`, run eg, use `gofmt -r` to convert `.S.S` to `.S`, and then use `gorename` to make `.S` be the string I originally wanted.

**Comment by Ripounet** [comment] 2015-07-19 20:41
Yes this looks like a dupe of #10252.

I noticed the same problem each time the "after" matches the "before" pattern, e.g. :
```
func before(str string) string { return strings.ToLower(str) }
func after(str string) string  { return strings.ToLower("[" + str + "]") }
```
-> brackets added twice instead of once.

**Comment by stamblerre** [comment] 2020-04-14 03:55
Duplicate of #10252

**Closed by stamblerre** 2020-04-14 03:55 UTC
Labels: Tools
