### ISSUE TITLE
internal/poll: TestSplicePipePool failures with "at least one pipe is still open" on linux-arm

### ISSUE THREAD

**Issue by bcmills** [golang/go#48066] opened 2021-08-30 15:27 UTC
```
$ greplogs --dashboard -md -l -e (?m)FAIL: TestSplicePipePool.*\n.*at least one pipe is still open --since=2021-04-27
```
[2021-08-26T22:37:54-967a801/android-arm-corellium](https://build.golang.org/log/4d0a547624075df9a0cba11ba0f8abd04c678449)
[2021-08-26T20:39:56-af80af2/android-arm-corellium](https://build.golang.org/log/e9704bc2625393b90904e86d3dfa57fb11be700d)
[2021-08-24T22:23:12-54cdef1/android-arm-corellium](https://build.golang.org/log/2485091e0a0b7646d7018040996f64f4af95545c)
[2021-08-22T13:11:50-96d816c/android-arm-corellium](https://build.golang.org/log/6864745f389d5b6c4ea905fbeff6c3e49c228b9f)
[2021-08-17T16:22:15-cf12b0d/android-arm-corellium](https://build.golang.org/log/1ed43df1178f9b0be2106befaa5d4adb9ab74349)
[2021-08-11T22:07:50-dea23e9/android-arm-corellium](https://build.golang.org/log/9cc87d476da690eb3b01d14aafbc668799f6294c)
[2021-05-26T22:41:55-0fbecec/linux-arm-scaleway](https://build.golang.org/log/96c8f83ad37270e8a151936e2cbac1d946a7de59)
[2021-04-29T13:24:00-eb3fe28/linux-arm-scaleway](https://build.golang.org/log/a1c03a8f86807bf28f726d8f379199a0996d8410)

See previously #45782, #45059 (@panjf2000 @ianlancetaylor @bradfitz).

**Comment by bcmills** [comment] 2021-08-30 15:37
This test was added for Go 1.17 (March 9, in [CL 271537](https://golang.org/cl/271537) for #42740), so these failures represent at least a regression in test flakiness in the current release (CC @golang/release). A rollback of the flaky test in [CL 308089](https://golang.org/cl/308089) was abandoned in favor of an attempt to fix the test in [CL 308329](https://golang.org/cl/308329).

The failure rate seems to have been partially obscured by the low rate of changes during the Go 1.17 code freeze. 

It is not clear to me whether the test failures represent a defect in the test itself or an incomplete fix for #42740. Since this flakiness is new as of Go 1.17, I think a fix for it should at least block the next release.

**Comment by panjf2000** [comment] 2021-08-30 17:05
Given that at least one pipe was not closed in the test, it could only be either that the finalizers for each pipe didn't work properly on some platforms, or that the `CloseFunc` in `destroyPipe()` failed when finalizers were executed.

If it is the latter mentioned above, then this issue has been there since the day `splice` was implemented, otherwise, the problematic issue will goes to the former: `runtime.SetFinalizer()` and we have to figure out why it was not working as expected.

**Comment by bcmills** [comment] 2021-08-30 19:19
Per https://pkg.go.dev/runtime#SetFinalizer (emphasis mine):
> The finalizer is scheduled to run at some arbitrary time after the program can no longer reach the object to which obj points. **There is no guarantee that finalizers will run before a program exits, so typically they are useful only for releasing non-memory resources associated with an object during a long-running program.**

If the test depends on a finalizer actually executing, it is depending on a property of the runtime that is not guaranteed to hold — it should probably have extra scrutiny from the runtime team.

**Comment by panjf2000** [comment] 2021-08-31 01:05
It seems to have been working well on https://github.com/golang/go/blob/go1.17/src/sync/pool_test.go#L100-L135 with `runtime.SetFinalizer`. Is there any chance that some `poll.splicePipe`'s were allocated on stack instead of heap, so the garbage collector did not take effect in this case.

**Comment by bcmills** [comment] 2021-09-01 15:38
1. Is it possible that `F_GETPIPE_SZ` somehow succeeds on a file descriptor for a pipe that was actually destroyed? (Perhaps the FD is somehow reused for another, unrelated file for which `F_GETPIPE_SZ` succeeds, or some bug in the kernel affecting ARM processors causes a spurious 0-return?)

2. Is it possible that the `destroyPipe` call in the finalizer is actually failing to destroy the pipe? I notice that it makes [two calls to `CloseFunc`](https://cs.opensource.google/go/go/+/master:src/internal/poll/splice_linux.go;l=240-241;drc=8b859be9c3fd1068b659afa1db76dadb210c63de), which returns an `error`, but does not check whether those errors are non-nil.

3. Is it possible that the finalizer is failing to run entirely? (Would it make sense to modify the test to count or examine the finalizer calls independently from the status of the FDs, perhaps by allowing the test to inject an atomic-counter-update into the finalizer?)

**Comment by panjf2000** [comment] 2021-09-02 01:09
I want to debug and reproduce this test failure on those platforms, but I don't have any of those machines with ARM processors on hand now, is there a way for me to run the test on machines of golang build farm without interfering with the routine builds?

**Comment by panjf2000** [comment] 2021-09-02 03:43
> 1. Is it possible that `F_GETPIPE_SZ` somehow succeeds on a file descriptor for a pipe that was actually destroyed? (Perhaps the FD is somehow reused for another, unrelated file for which `F_GETPIPE_SZ` succeeds, or some bug in the kernel affecting ARM processors causes a spurious 0-return?)
> 2. Is it possible that the `destroyPipe` call in the finalizer is actually failing to destroy the pipe? I notice that it makes [two calls to `CloseFunc`](https://cs.opensource.google/go/go/+/master:src/internal/poll/splice_linux.go;l=240-241;drc=8b859be9c3fd1068b659afa1db76dadb210c63de), which returns an `error`, but does not check whether those errors are non-nil.
> 3. Is it possible that the finalizer is failing to run entirely? (Would it make sense to modify the test to count or examine the finalizer calls independently from the status of the FDs, perhaps by allowing the test to inject an atomic-counter-update into the finalizer?)

Another thought about improving test code is to leverage epoll to monitor all pipe fds and when we receive the sufficient amount (equal to the amount of pipes) of `POLLERR/EPOLLERR`, then it's legitimate to mark this test as successful.

**Comment by panjf2000** [comment] 2021-09-02 03:56
Besides, I just found a related discussion at #26049

**Comment by toothrot** [comment] 2021-09-08 19:36
Just a note on the original issue: the scaleway builders no longer exist, as Scaleway dropped ARM support.

@panjf2000 We aren't granting new access to our builders at this time. 

It looks like it also failed today on `linux-386-jessie`: https://build.golang.org/log/e4fcae576822945ee58df39050d0db1b2a8a7b8d, for which we have a public image: `gcr.io/symbolic-datum-552/linux-x86-jessie:latest`

The only other special thing about that builder is the following environment variables, which can also be seen in the linked logs:
```
			"GOARCH=386",
			"GOHOSTARCH=386",
			"GO_DISABLE_OUTBOUND_NETWORK=1",
```

**Comment by panjf2000** [comment] 2021-09-14 02:40
It appears that all finalizers occasionally failed to execute on the android platform for some unknown reasons, take a look at this [test log](https://build.golang.org/log/97a34a7442f30fc4634dcbc6ebe5c70e906dbccf), where none of the finalizers executed.

**Comment by ianlancetaylor** [comment] 2021-09-15 01:06
I think you are misreading the log.  Of the various descriptors to check, only descriptor `8` is still open.

This makes me wonder whether descriptor `8` has been opened by some other thread, as in #25628.  This could in fact be the same issue as that one.  According to the internal/testenv package, android-arm always uses external linking.  That doesn't explain the linux-arm failure, though.

**Comment by panjf2000** [comment] 2021-09-15 02:53
> I think you are misreading the log. Of the various descriptors to check, only descriptor `8` is still open.
> 
> This makes me wonder whether descriptor `8` has been opened by some other thread, as in #25628. This could in fact be the same issue as that one. According to the internal/testenv package, android-arm always uses external linking. That doesn't explain the linux-arm failure, though.

I did misread the log and sorry about that, it was the minimum fd that was still alive, which makes it stands a good chance of being reused inside the process, I will submit a CL to improve the `splice_linux_test.go`, it would be rational for this test to ignore those fds reopened by other threads.

**Closed** 2021-09-17 19:33 UTC
Labels: NeedsInvestigation, release-blocker
