### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by nurali-techie** [golang/go#33145] opened 2019-07-17 02:53 UTC
### What version of Go are you using (`go version`)?
NA

### Does this issue reproduce with the latest release?
NA

### What operating system and processor architecture are you using (`go env`)?
NA

### What did you do?
Visit https://golang.org/

### What did you expect to see?
Previously, I used to see latest release version of Go.  Now with new theme of website, I cannot see it.  It's really easy+useful to see latest_released_version of Go on home page (https://golang.org/).  Now, to find it out, I need to do in two step.

First, visit home page
Second, click "Download Go"

### What did you see instead?
I see below four links:
Copyright | Terms of Service | Privacy Policy | Report a website issue

---
Request to show latest_version of Go on Home page with new theme.

**Comment by agnivade** [comment] 2019-07-17 03:22
Duplicate of https://github.com/golang/go/issues/33083.

Btw, it is not advisable to depend on the website's Go version to know about the latest release of Go. A new version of Go can get released, but the website might take time to get redeployed using the new version.

A better way is to parse https://golang.org/dl/?mode=json if you are looking to do this via code. But #33083 is still there for those who depend on seeing the version in the home page.

**Closed by agnivade** 2019-07-17 03:22 UTC

**Comment by nurali-techie** [comment] 2019-07-17 03:51
@agnivade thanks for the info and bringing to my attention that it's Go version with which this website is built with.

From user POV, what version https://golang.org/ is built with is less useful or concerned.  Even if it's used with Go or some other lang/tech, I as a user don't bother.

I as a user of Go Language, visit https://golang.org/ and I want to know what is the latest release version of Go and it would be good if I find it out from home page.

Generally, I visit https://golang.org/ to check if new blog has come and at the same time see if latest version of Go is released.  All I expect to see on home page.

**Comment by agnivade** [comment] 2019-07-17 04:16
I see. Then you are requesting something which has never been there. I would request you to open a new issue since it is a different topic, and best tracked in a new thread. Thank you.
