### ISSUE TITLE
cmd/compile: internal compiler error: missing reader for "sync/atomic".LoadPointer

### ISSUE THREAD

**Issue by thesyncim** [golang/go#51857] opened 2022-03-22 00:11 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/thesyncim/Library/Caches/go-build"
GOENV="/Users/thesyncim/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/thesyncim/go/pkg/mod"
GONOPROXY="github.com/GetStream"
GONOSUMDB="github.com/GetStream"
GOOS="darwin"
GOPATH="/Users/thesyncim/go"
GOPRIVATE="github.com/GetStream"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/thesyncim/skipset/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m3/yrklg3ys4xv28m70sb1x8fcw0000gn/T/go-build1309898556=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

```
go build -gcflags=-d=unified=1 github.com/thesyncim/skipset
```

### What did you expect to see?
No error
### What did you see instead?

```
➜  skipset git:(master) go build -gcflags=-d=unified=1 github.com/thesyncim/skipset
# github.com/thesyncim/skipset
./util.go:34:2: internal compiler error: missing reader for "sync/atomic".LoadPointer
```

**Comment by thesyncim** [comment] 2022-03-22 00:12
cc @mdempsky

**Comment by thesyncim** [comment] 2022-03-22 00:19
it seems to work fine with `GOEXPERIMENT=unified`
```
➜  skipset git:(master) GOEXPERIMENT=unified go build -gcflags=-d=unified=1 github.com/thesyncim/skipset
➜  skipset git:(master)
```

**Comment by cuonglm** [comment] 2022-03-22 16:19
You have to use `-gcflags=all=-d=unified` to make all packages compiled with unified IR, or using `GOEXPERIMENT=unified go build` without any further compiler flags.

Closing since when this works as intended.

**Closed by cuonglm** 2022-03-22 16:19 UTC
Labels: NeedsInvestigation
