### ISSUE TITLE
text/template and html/template: SIGSEGV when {{}} or similar invalid interpolation used

### ISSUE THREAD

**Issue by protamail** [golang/go#65222] opened 2024-01-23 00:19 UTC
### Go version

go version go1.20.12 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/op/.cache/go-build"
GOENV="/home/op/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/op/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/op/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.12"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build959387719=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

main.go:
```
package main
  
import (
    "text/template"
    "os"
)

func main() {
    tmpl, _ := template.New("tmpl").Parse("{{x}}")
    tmpl.Execute(os.Stdout, "")
}
```

### What did you see happen?

$ go run main.go
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4f01ac]

goroutine 1 [running]:
text/template.errRecover(0xc00004fea8)
        /usr/lib/golang/src/text/template/exec.go:170 +0x165
panic({0x511940, 0x616660})
        /usr/lib/golang/src/runtime/panic.go:884 +0x213
text/template.(*Template).execute(0x0, {0x5587d8?, 0xc000012018?}, {0x50b360?, 0x557db0?})
        /usr/lib/golang/src/text/template/exec.go:221 +0x22c
text/template.(*Template).Execute(...)
        /usr/lib/golang/src/text/template/exec.go:207
main.main()
        /home/op/src/main.go:10 +0x12b
exit status 2

### What did you expect to see?

An error message about syntax problem

**Comment by cherrymui** [comment] 2024-01-23 01:03
> tmpl, _ := template.New("tmpl").Parse("{{x}}")

It is expected to check error on `Parse`. In this case, it returns a non-nil error, and `tmpl` is nil, so it panics at next line.

Closing as working as intended. Thanks.

**Closed by cherrymui** 2024-01-23 01:03 UTC
