### ISSUE TITLE
cmd/go: panic when computing Shlib path for a test-only package

### ISSUE THREAD

**Issue by bcmills** [golang/go#35759] opened 2019-11-21 20:18 UTC
I discovered a panic while investigating #30316.

```
~/go/misc/cgo/testshared$ go version
go version devel +b3a35e026f Thu Nov 21 09:17:51 2019 -0500 linux/amd64

~/go/misc/cgo$ go list -f '{{.Shlib}}' -buildmode=shared -linkshared runtime sync/atomic .
can't load package: package .: no Go files in /usr/local/google/home/bcmills/go/misc/cgo
/usr/local/google/home/bcmills/go/pkg/linux_amd64_dynlink/libruntime,sync-atomic.so
/usr/local/google/home/bcmills/go/pkg/linux_amd64_dynlink/libruntime,sync-atomic.so

~/go/misc/cgo$ go list -f '{{.Shlib}}' -buildmode=shared -linkshared runtime sync/atomic ./testshared
panic: runtime error: slice bounds out of range [:-2]

goroutine 1 [running]:
cmd/go/internal/load.(*Package).load(0xc00009a480, 0xc0001bd390, 0xc000200700, 0x0, 0x0)
        /usr/local/google/home/bcmills/go/src/cmd/go/internal/load/pkg.go:1588 +0x3675
cmd/go/internal/load.loadImport(0xc0000a4270, 0xc0000b4600, 0x13, 0xc00002a064, 0x2a, 0x0, 0xc0001bd390, 0x0, 0x0, 0x0, ...)
        /usr/local/google/home/bcmills/go/src/cmd/go/internal/load/pkg.go:577 +0xef7
cmd/go/internal/load.PackagesAndErrors(0xc0000200f0, 0x3, 0x3, 0x0, 0x0, 0x0)
        /usr/local/google/home/bcmills/go/src/cmd/go/internal/load/pkg.go:2079 +0x387
cmd/go/internal/load.Packages(0xc0000200f0, 0x3, 0x3, 0xc00017ee40, 0x0, 0x0)
        /usr/local/google/home/bcmills/go/src/cmd/go/internal/load/pkg.go:2035 +0x5a
cmd/go/internal/list.runList(0xeaec20, 0xc0000200f0, 0x3, 0x3)
        /usr/local/google/home/bcmills/go/src/cmd/go/internal/list/list.go:441 +0x231e
main.main()
        /usr/local/google/home/bcmills/go/src/cmd/go/main.go:189 +0x569
```

CC @ianlancetaylor @jayconrod

**Comment by jayconrod** [comment] 2019-11-21 20:52
Possible duplicate of #34347

**Comment by bcmills** [comment] 2019-11-21 20:52
Ooh, nice find!

**Closed** 2019-11-22 19:04 UTC
Labels: NeedsFix
