### ISSUE TITLE
runtime: cgo can't set new environment variables for Go

### ISSUE THREAD

**Issue by rakeshlacework** [golang/go#44108] opened 2021-02-04 17:31 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/works/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/works"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go-1.15.6"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go-1.15.6/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build987882216=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

1. Set environment variable before invoking the executable
2. Overwrite and add new environment variable in cgo constructor
3. print them in main

Here is the source code (also on playground does not work https://play.golang.org/p/knyUM81kREi)

```
vm: 17:11:38 ~/go/src/clear_env$ cat main.go
package main
/*
#cgo CFLAGS: -Werror -I/usr/include
#cgo LDFLAGS: -L/usr/lib64/ -L/usr/lib/x86_64-linux-gnu/ -ldl
#include <stdio.h>
#include <stdlib.h>
__attribute__((constructor)) void setup_env(void) {
	clearenv();
	setenv("EXISTING_VAR", "newValue", 1);
	setenv("NEW_VAR", "newValue", 1);
}
void print_env(void) {
	printf("C> PATH='%s'\n", getenv("PATH"));
	printf("C> EXISTING_VAR='%s'\n", getenv("EXISTING_VAR"));
	printf("C> NEW_VAR='%s'\n", getenv("NEW_VAR"));
}
*/
import "C"
import (
	"fmt"
	"os"
)
func main() {
	fmt.Printf("GO> PATH='%v'\n", os.Getenv("PATH"))
	fmt.Printf("GO> EXISTING_VAR='%v'\n", os.Getenv("EXISTING_VAR"))
	fmt.Printf("GO> NEW_VAR='%v'\n", os.Getenv("NEW_VAR"))
	C.print_env()
}
```

### What did you expect to see?
<pre>
vm: 17:11:42 ~/go/src/clear_env$ EXISTING_VAR="oldValue" ./main
GO> PATH='/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin'
GO> EXISTING_VAR='newValue'
GO> NEW_VAR='newValue'
C> PATH='/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin'
C> EXISTING_VAR='newValue'
C> NEW_VAR='newValue'
</pre>

### What did you see instead?
<pre>
vm: 17:11:42 ~/go/src/clear_env$ EXISTING_VAR="oldValue" ./main
GO> PATH='/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin'
GO> EXISTING_VAR='oldValue'
GO> NEW_VAR=''
C> PATH='(null)'
C> EXISTING_VAR='newValue'
C> NEW_VAR='newValue'
</pre>

**Comment by seankhliao** [comment] 2021-02-04 18:35
given that `__attribute__((constructor))` is 1. a gcc compiler extension 2. only run when it is loaded, I don't see why it should run before main in go

**Comment by deepak-lacework** [comment] 2021-02-04 19:12
@seankhliao I don't think the problem is with `__attribute__((constructor))` not running before Go main (or C main). Here's a slightly different code that illustrates the problem better. Notice that Go reports the new value for`EXISTING_VAR` but old value for `NEW_VAR` while C/libc reports new values for both.

```
package main
/*
#cgo CFLAGS: -Werror -I/usr/include
#cgo LDFLAGS: -L/usr/lib64/ -L/usr/lib/x86_64-linux-gnu/ -ldl
#include <stdio.h>
#include <stdlib.h>
__attribute__((constructor)) void setup_env(void) {
	setenv("EXISTING_VAR", "newValue", 1);
	setenv("NEW_VAR", "newValue", 1);
}
void print_env(void) {
	printf("C> EXISTING_VAR='%s'\n", getenv("EXISTING_VAR"));
	printf("C> NEW_VAR='%s'\n", getenv("NEW_VAR"));
}
*/
import "C"
import (
	"fmt"
	"os"
)
func main() {
	fmt.Printf("GO> EXISTING_VAR='%v'\n", os.Getenv("EXISTING_VAR"))
	fmt.Printf("GO> NEW_VAR='%v'\n", os.Getenv("NEW_VAR"))
	C.print_env()
}
```
Here’s how to run the code to repro the issue. Notice the missing value for NEW_VAR when accessed via Go’s os package.
```
$ EXISTING_VAR="oldValue" ./main
GO> EXISTING_VAR='newValue'
GO> NEW_VAR=''
C> EXISTING_VAR='newValue'
C> NEW_VAR='newValue'
```

**Comment by seankhliao** [comment] 2021-02-04 19:37
I see, I think it's related to #27693 but not sure if it's the same issue

**Comment by deepak-lacework** [comment] 2021-02-04 20:02
I agree, this is similar to https://github.com/golang/go/issues/27693. The only difference is that in https://github.com/golang/go/issues/27693, C.setenv after Go runtime is setup while in this case it is being called before Go runtime is setup. It is ok to not support the former because C.setenv isn't thread-safe.

Looking at the Go runtime setup code, it gets the environment from the arguments to C main. If instead Go runtime setup code get the environment from `char **environ` in libc, it should see the changes made to the environment by any preceding C code.

**Comment by ianlancetaylor** [comment] 2021-02-05 01:51
I think it's OK for us to just say that the behavior here is implementation defined.  Especially when we start considering the behavior with `-buildmode=c-archive`, there is no perfect solution here.

For what it's worth, this is what I see for the first program:

```
GO> EXISTING_VAR=''
GO> NEW_VAR=''
C> PATH='(null)'
C> EXISTING_VAR='newValue'
C> NEW_VAR='newValue'
```

**Comment by deepak-lacework** [comment] 2021-02-05 02:47
Thanks @ianlancetaylor.
Yes, I see the same output as you from the first program.

**Comment by seankhliao** [comment] 2022-08-20 16:26
Closing as working as intended

**Closed by seankhliao** 2022-08-20 16:26 UTC
Labels: NeedsInvestigation, compiler/runtime
