### ISSUE TITLE
x/mobile: cmd/gomobile bind reports an error and cannot be executed

### ISSUE THREAD

**Issue by v3u3i87** [golang/go#43136] opened 2020-12-11 10:02 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary>
<code>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/q/Library/Caches/go-build"
GOENV="/Users/q/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/q/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/q/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sc/0b0pydt90bv3vn17vpz6029h0000gn/T/go-build735052660=/tmp/go-build -gno-record-gcc-switches -fno-common"
</code>

</summary><br><pre>
$ go env

</pre></details>

### What did you do?

gomobile bind -target=ios hello

```text
gomobile: darwin-arm64: go build -tags ios -buildmode=c-archive -o /var/folders/sc/0b0pydt90bv3vn17vpz6029h0000gn/T/gomobile-work-029196412/hello-arm64.a ./gobind failed: exit status 1
go build runtime/cgo: invalid flag in go:cgo_ldflag: -fembed-bitcode
```

### What did you expect to see?

I hope it can be compiled successfully, but cannot be compiled successfully now

### What did you see instead?

**Comment by odeke-em** [comment] 2020-12-11 12:52
Thank you @v3u3i87 for the question and welcome to the Go project!

Kindly cc-ing @eliasnaur @hyangah to take a look.

**Comment by eliasnaur** [comment] 2020-12-11 13:44
Could be a duplicate of https://github.com/golang/go/issues/42567. Can you try Go 1.15.6?

**Comment by v3u3i87** [comment] 2020-12-11 14:29
> Could be a duplicate of #42567. Can you try Go 1.15.6?
@eliasnaur 
ok,Thank you

**Comment by toothrot** [comment] 2020-12-11 16:39
Closing as a dupe of #42565. Please comment if the latest released version of Go does not work.

**Closed by toothrot** 2020-12-11 16:39 UTC
Labels: mobile
