### ISSUE TITLE
runtime: cannot run go file using qemu-arm when I disable core 0 in docker 

### ISSUE THREAD

**Issue by eastson** [golang/go#37945] opened 2020-03-19 07:30 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/arm
</pre>

### Does this issue reproduce with the latest release?
Yes. I have tested it with g1.14.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="arm"
GOBIN=""
GOCACHE="/home/quickbuild/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/quickbuild/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="7"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build242285369=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

package main
func main(){
        for i:=0; i<1000; i++ {
                println("Hello world")
        }
}

### What did you expect to see?
Hello world
Hello world
Hello world
... (997 times more)

### What did you see instead?
**<one of the fail logs>**
bash-3.2# go run test.go 
fatal error: schedule: holding locks
panic during panic
SIGILL: illegal instruction
PC=0xc9ec4c m=3 sigcode=2

goroutine 122 [runnable]:
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault (core dumped)
bash-3.2# 

Hello!
I figure out that sometimes simple go application is not working.
I am using docker + qemu-arm + go( for armv7l).

These are version info below.

_root@VDBS1535:~# docker -v
Docker version 17.09.1-ce, build 19e2cf6_

_bash-3.2# qemu-arm --version
qemu-arm version 2.7.0, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers_

This issue is come only when I disable core 0 using a command below. 
please check "--cpuset-cpus=1-55" option.

_sudo docker run --privileged -d -i -t --cpuset-cpus=1-55 --mount type=bind,source="/home/dw83kim/mnt",destination="/mnt" --network host --name="ubuntu_core1" ubuntu:xenial-20200212_

**Comment by bcmills** [comment] 2020-03-19 14:36
We currently lack a QEMU builder (#1508), and per http://golang.org/wiki/PortingPolicy, supported platforms require builders. Therefore, the QEMU platform is not supported.

Also note that QEMU has known bugs that may cause Go programs to fail (#33746).

Please let us know if the issue is reproducible using a supported OS on a physical ARM platform.

**Comment by eastson** [comment] 2020-04-01 11:30
Hello guys 

Thanks for your rapid reply.

I took long time to  test.
Fortunately the issue is fixed.

Please check it below.
https://bugs.launchpad.net/qemu/+bug/1868055

Thanks!

**Comment by ALTree** [comment] 2021-06-18 08:06
Fixed, closing.

**Closed by ALTree** 2021-06-18 08:06 UTC
Labels: WaitingForInfo
