### ISSUE TITLE
cmd/go: can not output ssa.html file after remove it manually with GOSSAFUNC flag set

### ISSUE THREAD

**Issue by feilengcui008** [golang/go#40465] opened 2020-07-29 03:34 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes，with the latest release go1.14.6

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/tanhongfei/me/workspace/src/go/bin"
GOCACHE="/home/tanhongfei/.cache/go-build"
GOENV="/home/tanhongfei/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tanhongfei/me/workspace/src/go:/home/tanhongfei/me/workspace/go/src/k8s.io/kubernetes/staging"
GOPRIVATE=""
GOPROXY="https://goproxy.cn/"
GOROOT="/home/tanhongfei/me/software/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/tanhongfei/me/software/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build390604943=/tmp/go-build"
</pre></details>

### What did you do?

1. generate ssa.html file with command `env GOSSAFUNC=test go build main.go` for the following code：
```
package main
import (
    "fmt"
)
func test() {
    fmt.Println("hello, world!")
}
func main() {
    test()
}
```

2. remove ssa.html

3. run `env GOSSAFUNC=test go build main.go` again

extra infomation：
`env GOSSAFUNC=test go run/install main.go` has the same problem.
`env GOSSAFUNC=test go build/run/install -a main.go` will work correctly with "-a" flag
`env GOSSAFUNC=test go tool compile main.go` will work correctly
I guess it is related to the cache mechanism of "go" command, using "go tool compile" or with "-a" flag(force rebuild) will work correctly.

### What did you expect to see?
generate ssa.html file again in the current directory

### What did you see instead?
output with the following message, but no ssa.html file is generated in the current directory
```
# command-line-arguments
dumped SSA to ./ssa.html
```

**Comment by cuonglm** [comment] 2020-07-29 03:44
I think this is duplicated of https://github.com/golang/go/issues/31290

**Comment by cagedmantis** [comment] 2020-07-29 21:04
This does indeed seem like a duplicate of #31290. Please feel free to contribute and follow-up with that issue. If you think this issue was closed in error, please respond.

**Closed by cagedmantis** 2020-07-29 21:04 UTC
