### ISSUE TITLE
cmd/cgo: cgo pointer checking issue with struct fields

### ISSUE THREAD

**Issue by egonelbre** [golang/go#25941] opened 2018-06-18 13:18 UTC
Issue: go 1.10.2 and current go tip (b7d9e6e149567bb94d6bb87a9ab09c60055ac4e8).
Machine: darwin/amd64

When you use a pointer inside to another struct with pointers when calling C then CGO check fails with "panic: runtime error: cgo argument has Go pointer to Go pointer".

Possibly related to https://github.com/golang/go/issues/14210

Code to reproduce:

```
package main

// void exampleCall(void *p) {}
import "C"
import "unsafe"

type Data struct {
	Map          map[int32]int32
	InternalData InternalData
}
type InternalData struct{ X, Y, Z float32 }

func main() {
	data := &Data{}
	data.Map = make(map[int32]int32)
	C.exampleCall(unsafe.Pointer(&data.InternalData))
}
```

**Comment by ianlancetaylor** [comment] 2018-06-18 18:15
This is a bug that should be fixed some day.  The problem is that the conversion to `unsafe.Pointer` breaks the cgo pointer check.  It no longer knows the type of the value, so it examines the entire memory area.

**Comment by egonelbre** [comment] 2018-06-20 06:33
I was examining / thinking how to fix it. What if it were to unwrap `unsafe.Pointer` part for the `cgoCheckPointer`?

So, instead of generating:

```
func (_cgo0 unsafe.Pointer) {
    _cgoCheckPointer(_cgo0)
    C.f(_cgo0)
}(unsafe.Pointer(p))
```

It would generate:
```
func (_cgo0 ptype) {
    _cgoCheckPointer(_cgo0)
    C.f(unsafe.Pointer(_cgo0))
}(p)
```

The same goes for the `needsPointerCheck` - i.e. ignore the outermost cast.

Thoughts?

**Comment by egonelbre** [comment] 2018-06-20 06:38
Probably only in cases when ptype itself is a pointer. Because it still would need to check `unsafe.Pointer(uintptr(p))` and similar.

**Closed** 2018-11-01 21:55 UTC
Labels: NeedsFix, help wanted
