### ISSUE TITLE
reflect: reflect.StructOf makes incorrect type with embedded interface

### ISSUE THREAD

**Issue by g7r** [golang/go#61434] opened 2023-07-19 04:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sz/.cache/go-build"
GOENV="/home/sz/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/sz/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/sz/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.6"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2006396805=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Consider the following code: https://go.dev/play/p/WuzpUlzKido and https://go.dev/play/p/zgAX3grM8rT

It makes a new struct type using `reflect.TypeOf` with a single embedded interface field. Then it makes an instance of the type and tries to invoke the method of the interface on that type.

### What did you expect to see?

Output:
```
A.M1 invoked
```

### What did you see instead?

It panicked.

**Comment by seankhliao** [comment] 2023-07-19 06:22
Duplicate of #15924

**Closed by seankhliao** 2023-07-19 06:22 UTC
Labels: compiler/runtime

**Comment by seankhliao** [comment] 2023-07-19 06:28
Duplicate of #38783
