### ISSUE TITLE
cmd/go: case-insensitive import collision with vgo build ./...

### ISSUE THREAD

**Issue by adam-hanna** [golang/go#26208] opened 2018-07-03 21:53 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```bash
$ go version
go version go1.10.3 linux/amd64

$ vgo version
go version go1.10.3 linux/amd64 vgo:2018-02-20.1
```

### Does this issue reproduce with the latest release?
Have not tried 1.11beta1

### What operating system and processor architecture are you using (`go env`)?
```bash
$ go env
GOARCH="amd64"
GOBIN="/home/adam/go/bin"
GOCACHE="/home/adam/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/adam/go"
GORACE=""
GOROOT="/home/adam/.gvm/gos/go1.10.3"
GOTMPDIR=""
GOTOOLDIR="/home/adam/.gvm/gos/go1.10.3/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build321160569=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
```bash
$ vgo build ./...
...
...
../../../mod/github.com/docker/go-events@v0.0.0-20170721190031-9461782956ad/broadcast.go:7:2: case-insensitive import collision: "github.com/sirupsen/logrus" and "github.com/Sirupsen/logrus"
```

[A simple, demo repo to reproduce can be found, here.](https://github.com/adam-hanna/vgo-bug)

[Stackoverflow, here.](https://stackoverflow.com/questions/51109529/vgo-case-insensitive-import-collision/51109877#51109877)

I've also tried modifying my go.mod file with
```
exclude github.com/Sirupsen/logrus v1.0.5

require (
    ...
    github.com/sirupsen/logrus v1.0.5
    ...
)
```
AND
```
replace github.com/Sirupsen/logrus v1.0.5 => github.com/sirupsen/logrus v1.0.5
```

### What did you expect to see?
Successful build

### What did you see instead?
```bash
../../../mod/github.com/docker/go-events@v0.0.0-20170721190031-9461782956ad/broadcast.go:7:2: case-insensitive import collision: "github.com/sirupsen/logrus" and "github.com/Sirupsen/logrus"
```

**Comment by bcmills** [comment] 2018-07-04 12:31
`vgo` tends to choose an old version of `docker/docker` due to the vgo requirement for semantic import versioning. (The latest `docker` tags are for `v17`, but without a versioned import path vgo stops at `v1`.)

That's probably giving you some transitive dependency that uses a bad import path for `logrus`.

What happens if you explicitly `vgo get github.com/docker/docker@v17.05.0-ce`?

**Comment by adam-hanna** [comment] 2018-07-05 01:50
Hi @bcmills, thanks for the suggestion, but I got the same error

**Comment by pwaller** [comment] 2018-07-10 13:00
I'm also hitting this in another project @bcmills - one with a very long list of dependencies, including docker and some other large things. It's unclear where the problem comes from, or how to determine it.

I have also reproduced @adam's experience.

**Comment by bcmills** [comment] 2018-07-10 21:18
When we stop automatically picking old versions of things (#26238) it should pretty much go away. Let's revisit once that is fixed.

**Comment by filewalkwithme** [comment] 2018-08-01 21:18
#26238 was merged. Is this issue still happening?

**Comment by adam-hanna** [comment] 2018-08-01 21:56
@filewalkwithme trying to install from source to check, now. Having some issues but will update you with progress, soon.

**Comment by adam-hanna** [comment] 2018-08-01 22:41
@filewalkwithme same problem, unfortunately.

```bash
$ go version
go version devel +859a944ee2 Wed Aug 1 21:45:11 2018 +0000 linux/amd64

$ git clone git@github.com:adam-hanna/vgo-bug.git && cd vgo-bug
$ go build .
go build .
/home/adam/go/pkg/mod/github.com/docker/go-events@v0.0.0-20170721190031-9461782956ad/broadcast.go:7:2: case-insensitive import collision: "github.com/sirupsen/logrus" and "github.com/Sirupsen/logrus"
```

**Comment by adam-hanna** [comment] 2018-08-10 05:08
@rsc Thanks for the help!

Unless I'm mistaken, the example repo is using the most recent release of docker ([v17.03.2-ce](https://github.com/moby/moby/releases)). The git hash of which is f5ec1e2936dcbe7b5001c2b817188b095c700c27

In [go.mod, line #15](https://github.com/adam-hanna/vgo-bug/blob/master/go.mod#L15):
```go
require(
...
github.com/docker/docker v0.0.0-20170601211448-f5ec1e2936dc
...
)
```

You can see that that is in fact the latest git hash.

Would it be possible to at least consider adding support for:

```
replace github.com/Sirupsen/logrus v1.0.5 => github.com/sirupsen/logrus v1.0.5
```

??

Thank!

**Comment by voutasaurus** [comment] 2018-08-22 23:50
It may be worth looking at the corpus to see which major packages vendor an old docker version (pre July 2017). If the responsibility lies with the package maintainers themselves then starting the outreach sooner rather than later will give those package maintainers more time to anticipate the issue.

Also maybe I'm reading this wrong but is there any temporary workaround for those project maintainers who themselves are depending on a package that in turn depends on an old version of docker except for "don't use go mod for dependency management"?

**Comment by voutasaurus** [comment] 2018-08-23 16:52
FYI I did this in a repo which depends on github.com/hyperledger/fabric which depends on an old version of docker as a workaround and the error went away:
```
go mod init
go get github.com/docker/docker@v0.0.0-20180422163414-57142e89befe
go test ./...
```

No manual editing of go.mod required. Tested in fresh golang:rc container.

I'm not sure if github.com/hyperledger/fabric will actually work with docker@v0.0.0-20180422163414-57142e89befe but at least the go tooling will work.

**Comment by thepudds** [comment] 2019-01-16 14:31
More recent discussion (along with worked examples of good techniques to resolve properly) in: 
* https://github.com/golang/go/issues/28489#issuecomment-434616301 
* https://github.com/golang/go/issues/28489#issuecomment-454795390

**Comment by bcmills** [comment] 2019-01-18 19:00
> Would it be possible to consider adding support for:
>
> ```
> replace github.com/Sirupsen/logrus v1.0.5 => github.com/sirupsen/logrus v1.0.5
> ```

That will likely be allowed once #26904 is addressed. Closing this issue as subsumed by that one.

**Closed by bcmills** 2019-01-18 19:00 UTC
Labels: NeedsInvestigation, modules
