### ISSUE TITLE
cmd/go: spurious linefeed + backspace (\r\u0008) characters in go test -json output on Windows

### ISSUE THREAD

**Issue by shueybubbles** [golang/go#51207] opened 2022-02-15 15:27 UTC
On Windows 10 I see unexpected output in one of our tests. I do not see this extra output on Linux.
Perhaps there's some obscure bug in our code but we don't have anything that obviously emits such a strange combination as `\r\u0008`.

### What version of Go are you using (`go version`)?

<pre>
go version go1.17.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
<PII redacted>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.1
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\git\go-sqlcmd\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
</pre></details>

### What did you do?

```
git clone https://github.com/microsoft/go-sqlcmd
set SQLCMDSERVER=mysqlservername
go test -json ./...

```

### What did you expect to see?
```
{"Time":"2022-02-15T15:16:17.355648516Z","Action":"output","Package":"github.com/microsoft/go-sqlcmd/cmd/sqlcmd","Test":"TestQueryAndExit","Output":"--- PASS: TestQueryAndExit (0.71s)\n"}

```

### What did you see instead?
```
{"Time":"2022-02-15T10:03:01.7125903-05:00","Action":"output","Package":"github.com/microsoft/go-sqlcmd/cmd/sqlcmd","Test":"TestQueryAndExit","Output":"\r\u0008\r\u0008\r\u0008--- PASS: TestQueryAndExit (0.62s)\n"}
```

**Comment by bcmills** [comment] 2022-02-15 18:56
`\u0008` is `BACKSPACE`. I 

However, at first glance this looks like a variation on #26325 / #33419. Probably something else in the test is writing to the test's `stdout` or `stderr`, and because the extra output doesn't occur at a newline boundary, `cmd/test2json` isn't able to parse past it.

**Comment by bcmills** [comment] 2022-02-15 18:56
Duplicate of #26325

**Closed by bcmills** 2022-02-15 18:56 UTC
Labels: OS-Windows, NeedsInvestigation

**Comment by bcmills** [comment] 2022-02-15 20:27
> FWIW it's not just in the json, the backspace characters are encoded in plain text when not using -json.

That's exactly what I'm saying. The `testing` package (and `go test`) does not inject those characters in the text itself, so they must be coming from some other package linked into the test binary.

You could try compiling the test and setting a debugger breakpoint to figure out what is writing those bytes. Perhaps they're coming from a subprocess (via `os/exec`) that has been set to forward its own `stdout` and/or `stderr`?
