### ISSUE TITLE
Go regularization problem

### ISSUE THREAD

**Issue by yupor5** [golang/go#70551] opened 2024-11-25 02:57 UTC
{"match": "\"EventID\":\"(?!462[4-7]\"|4634\"|464[7-8]\"|467[3-4]\"|4688\"|469[89]\"|470[0-5]\"|4719\"|472[02-9]\"|473[0-578]\"|474[0-9]\"|475[0-9]\"|476[0-9]\"|477[0-9]\"|478[0-1]\"|4794\"|479[89]\"|480[0-3]\"|514[02-5]\"|515[0-9]\"|5168\"|537[6-7]\"|641[69]\"|642[0-4]\"|7031\"|7034\"|7036\"|7040\"|7045\")\\d*\"","example": [
      "{\"Computer\":\"DESKTOP-02VFIOJ\",\"EventData\":{\"Data_SubjectUserName\":\"wonder\",\"Data_ProcessId\":\"0x1fd4\",\"Data_HandleId\":\"0x858\",\"Data_ObjectServer\":\"Security\",\"Data_AccessMask\":\"0x1\",\"Data_SubjectUserSid\":\"S-1-5-21-2510928271-3594568744-4108095923-1001\",\"Data_SubjectDomainName\":\"DESKTOP-02VFIOJ\",\"Data_ObjectType\":\"Key\",\"Data_ObjectName\":\"\\\\REGISTRY\\\\MACHINE\\\\SOFTWARE\\\\Classes\\\\CLSID\\\\{41945702-8302-44A6-9445-AC98E8AFA086}\\\\Patterns\\\\8\",\"Data_SubjectLogonId\":\"0x137ee86\",\"Data_AccessList\":\"%%4432\",\"Data_ProcessName\":\"C:\\\\Windows\\\\System32\\\\RuntimeBroker.exe\",\"Data_ResourceAttributes\":\"-\"},\"Source\":\"Microsoft-Windows-Security-Auditing\",\"OpcodeText\":\"信息\",\"Opcode\":\"0\",\"Keywords\":\"审核成功\",\"EventID\":\"4663\",\"UserData\":{},\"Channel\":\"Security\",\"Message\":\"试图访问对象。\",\"timestamp\":\"2021-11-08T11:54:58.1151745+08:00\",\"ProcessName\":\"System\",\"UserID\":\"\",\"TaskText\":\"Registry\",\"LevelText\":\"信息\",\"Level\":\"0\",\"Task\":\"12801\"}"
    ]}  This regularization prompt is reporting an error. I tested this regularization using Perl and found no problem. However, this is a bug,
![image](https://github.com/user-attachments/assets/88b60416-ca19-45dc-a97b-10b7db3862b4)And go language prompts
![image](https://github.com/user-attachments/assets/5a9b8f96-2952-43f6-ade4-f71b05d62a18)

**Comment by seankhliao** [comment] 2024-11-25 02:58
Duplicate of #70437

**Comment by seankhliao** [comment] 2024-11-25 02:59
we have no intention of supporting the same regex as perl

**Closed by seankhliao** 2024-11-25 02:58 UTC
Labels: FrozenDueToAge

**Comment by yupor5** [comment] 2024-11-25 03:02
You have already supported Perl, only stating that there are some errors

**Comment by ianlancetaylor** [comment] 2024-11-25 20:31
We do not support everything that Perl supports.  See https://swtch.com/~rsc/regexp/regexp1.html for why Go regular expressions do not support ?!.
