### ISSUE TITLE
Passing variable as argument in exec.Command() returns error

### ISSUE THREAD

**Issue by jufracaqui** [golang/go#22320] opened 2017-10-18 12:48 UTC
### What version of Go are you using (`go version`)?
1.9.1
### Does this issue reproduce with the latest release?
Yes
### What operating system and processor architecture are you using (`go env`)?
windows/amd64
### What did you do?
Passing a variable as an argument for a command instead of passing a string directly
### What did you expect to see?
Command output
### What did you see instead?
Error: exit status 1

----------

When I execute this code and write "version" in the console as a parameter  I get an **exit status 1**

```
package main

import (
    "bufio"
    "fmt"
    "log"
    "os"
    "os/exec"
)

func main() {
    reader := bufio.NewReader(os.Stdin)
    fmt.Print("Enter go parameter: ")
    parameter, _ := reader.ReadString('\n')

    args := []string{parameter}
    out, err := exec.Command("go", args...).Output()
    if err != nil {
        log.Fatal(err)
    }

    fmt.Println(string(out))
}
```

But if I write the following instead of using the user input it works like a charm and I get the output of the command.

`args := []string{"version"}`

**This problem doesn't only apply to go commands.**

**Comment by ianlancetaylor** [comment] 2017-10-18 14:03
`ReadString` returns a string that includes the delimiter, so you are running the equivalent of

    go `version
    `

Closing because this is not a bug in Go.  If you have questions about how to use Go please use a forum; see https://golang.org/wiki/Questions.

**Closed by ianlancetaylor** 2017-10-18 14:03 UTC
