### ISSUE TITLE
fmt.Println: print string array get wrong format.

### ISSUE THREAD

**Issue by changrui** [golang/go#52368] opened 2022-04-15 07:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15.5
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
**Windows 11 x64**
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
fmt.Println(str array)

### What did you expect to see?
**["a c" "b" "c"]**

### What did you see instead?
**[a c b c]**

**Comment by heavenisme** [comment] 2022-04-15 07:24
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by seankhliao** [comment] 2022-04-15 07:34
> For compound objects, the elements are printed using these rules, recursively
> ...
> array, slice:       [elem0 elem1 ...]

the behavior is consistent with
documentation how fmt prints strings in general (unquoted).

closing as not a bug

**Closed by seankhliao** 2022-04-15 07:34 UTC
