### ISSUE TITLE
time: time.String() defines format only in comment, with no matching Parse string

### ISSUE THREAD

**Issue by mattyw** [golang/go#9596] opened 2015-01-15 04:52 UTC
The documentation for time.String() shows the format used to convert time into a string: http://golang.org/pkg/time/#Time.String.

This string appears to be different to the const formats already defined in the time package, so if I wanted to naively (not using time.Format) convert a time -> string -> time I'd need to copy the format from the docs into my code and use it in a call to time.Parse.

In addition this format string is used a few times in http://golang.org/src/time/format_test.go as a literal string.

Isn't this format string a good candidate to be placed in the consts?

**Comment by rogpeppe** [comment] 2015-01-15 10:04
+1
I've considered raising this an an issue before.
Too late now, but I wish time.String() produced RFC3339,
the same format used by default in the marshaling methods.

**Comment by martisch** [comment] 2015-01-15 12:13
https://github.com/golang/go/blob/master/src/time/format.go#L400

We cant change it currently but we could use a const here and add it to the format consts that are exported. That would not change the output and give others access to the format string. If later a incompatible change is possible we can define that new const as RFC3339.

What would be a good name for it? StdDate?

**Comment by rogpeppe** [comment] 2015-01-15 12:51
I suggested TimeString as a possibility. I did consider Std, but it's not really "standard".

**Comment by martisch** [comment] 2015-01-15 13:23
Since it is already in the time package. time.FormatString sounds better to me.

**Comment by nightlyone** [comment] 2015-01-15 13:28
What about "time.Go" since we have already "time.Ruby" and this would resonate.

**Comment by martisch** [comment] 2015-01-15 13:44
We have "time.RubyDate" so then it would rather be "time.GoDate" however this sounds more like its special to me and not so much the default.

**Comment by dominikh** [comment] 2015-01-15 19:59
This is a duplicate of issue #6587

**Comment by ianlancetaylor** [comment] 2015-01-15 20:20
So it is, and that issue was closed as working as intended.  So, closing.

**Closed by ianlancetaylor** 2015-01-15 20:20 UTC
