### ISSUE TITLE
net: Misleading error "no such host" when running out of file descriptiors

### ISSUE THREAD

**Issue by polarina** [golang/go#56192] opened 2022-10-13 10:52 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mce-gabrielp/.cache/go-build"
GOENV="/home/mce-gabrielp/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mce-gabrielp/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mce-gabrielp/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build969251111=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Given the following program:
```go
package main

import "net/http"

func main() {
	for {
		_, err := http.DefaultClient.Get("https://google.com")
		if err != nil {
			panic(err)
		}
	}
}
```
Then build and execute as follows:
```
$ go build main.go 
$ bash -c 'ulimit -n 6 && ./main'
```

We initially encountered this bug in a production program (where, due to our bug, a request got repeated in a loop without closing the response body) with far more gracious ulimit. This is not a fringe case limited to setting the ulimit haphazardly low.

### What did you expect to see?

```
panic: Get "https://google.com": dial tcp: lookup google.com: too many open files
```

### What did you see instead?

```
panic: Get "https://google.com": dial tcp: lookup google.com: no such host
```

**Comment by mateusz834** [comment] 2022-10-16 14:29
It only happens on cgo resolver, using the go resolver it returns a correct error: `lookup google.com on [::1]:53: dial udp [::1]:53: socket: too many open files`

**Comment by nightlyone** [comment] 2022-10-18 07:39
@mateusz834 could you please mention which libc and version of it you are using?

https://dev.to/0xbf/how-to-get-glibc-version-c-lang-26he describes how to do that for glibc.

**Comment by mateusz834** [comment] 2022-10-18 08:04
@nightlyone `(GNU libc) 2.36`

**Comment by mateusz834** [comment] 2022-10-23 18:33
As discussed in [CL 443255](https://go-review.googlesource.com/c/go/+/443255#message-18a302cb3b3f90ab376f05bb9062005620d73886) this is caused by a glibc bug. I filled a bug report here: https://sourceware.org/bugzilla/show_bug.cgi?id=29717

**Comment by mateusz834** [comment] 2022-10-23 18:39
For now it can be workarounded by forcing the go resolver, or using different libc (musl).

**Comment by bcmills** [comment] 2023-01-31 16:58
Duplicate of #18588

**Closed by bcmills** 2023-01-31 16:58 UTC
Labels: NeedsInvestigation
