### ISSUE TITLE
json: Package is somehow able to manipulate a []byte later in the program

### ISSUE THREAD

**Issue by MarkRosemaker** [golang/go#50415] opened 2022-01-03 17:49 UTC
### What version of Go are you using (`go version`)?

go version go1.17.5 darwin/amd64

### Does this issue reproduce with the latest release?

Yes, I tested it on my machine and playground (both release and dev branch): https://go.dev/play/p/pWLdlyHGO_F

### What operating system and processor architecture are you using (`go env`)?

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mark/Library/Caches/go-build"
GOENV="/Users/mark/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mark/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/mark/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rw/2cbtm9v95bz86c0ktyjwj2_80000gn/T/go-build4287955123=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?

Please see: https://go.dev/play/p/pWLdlyHGO_F

### What did you expect to see?

```
{"FooFooFooFoo":"123456789"}
{"FooFooFooFoo":"123456789"}

Program exited.
```

### What did you see instead?

```
{"FooFooFooFoo":"123456789"}
{"msg":"MY MESSAGE"}456789"}

Program exited.
```

**Comment by dsnet** [comment] 2022-01-03 18:25
This example seems to violate one of the [documented behaviors of `io.Writer`, which says](https://pkg.go.dev/io#Writer):
> Implementations must not retain p.

In the provided example, `writeRecorder` retains the input buffer on line 45.

**Comment by seankhliao** [comment] 2022-01-03 18:38
Closing as not a bug

For questions please refer to https://github.com/golang/go/wiki/Questions

**Closed by seankhliao** 2022-01-03 18:38 UTC

**Comment by MarkRosemaker** [comment] 2022-01-03 19:17
Ah, I see. Thank you for the quick help!
