### ISSUE TITLE
cmd/compile: odd type error reported on the wrong line

### ISSUE THREAD

**Issue by aarzilli** [golang/go#49441] opened 2021-11-08 14:03 UTC
This code:

```
package main

type pointerToT[T any, PT pointerToT[T, PT]] interface{
	*T
}

func F[T any, PT pointerToT[T, PT]](n, nn PT) {
}
```

compiles just fine, however adding a new function definition, calling F:

```
package main

type pointerToT[T any, PT pointerToT[T, PT]] interface{
	*T
}

func F[T any, PT pointerToT[T, PT]](n, nn PT) {
}

func WrapF[A any, PA pointerToT[A, PA]](n, nn PA) {
	F(n, nn)
}
```

Causes the error: `./buggy.go:7:15: PT does not match *T` on the line declaring `F`. It's weird that declaring a function would cause a different function to no longer typecheck correctly, I think this error was meant to be reported on the call to F.
It's also unclear what the problem is, shouldn't the type inference work correctly? Manually instantiating F as `F[A, PA](n, nn)` makes the error go away.

**Comment by hanchaoqun** [comment] 2021-11-10 01:29
I guess it's the type inference has a bug, since the PT , PA , *T can be inferred from each other, and this code should work with no error. Seems both of the nify and index does not dereference pointer for TypeParam
https://github.com/golang/go/blob/cc14fcac2bc1d452841336b9aeee3b1d47880f37/src/cmd/compile/internal/types2/unify.go#L154
https://github.com/golang/go/blob/cc14fcac2bc1d452841336b9aeee3b1d47880f37/src/cmd/compile/internal/types2/unify.go#L250

**Comment by hanchaoqun** [comment] 2021-11-10 04:21
https://github.com/golang/go/blob/cc14fcac2bc1d452841336b9aeee3b1d47880f37/src/cmd/compile/internal/types2/unify.go#L454

bug here , when x = PA , y = *T,  the *T is the a single defined type in the constraint, PA should look into it's constraint too.

**Comment by Jason7602** [comment] 2021-11-10 05:25
If we just change the above code to this way,  it doesn't  needs a dictionary to Call F and have no error message. Cause it can infered the PA is type of *T from the first parameter.
```go
package main

type pointer[T any, PT pointer[T, PT]] interface{
*T
}

func F[T any, PT pointer[T, PT]](n T, nn PT) {
}

func WrapF[A any, PA pointer[A, PA]](n A, nn PA) {
	F(n, nn) 
}
```
But if the both parameter Type is PT, it seems that the compile do not to infer if it haven't a dictionary to call F and cause such error message, actually it can infered, cause `PA` is the type of `pointerToT`,  to this extent, may @hanchaoqun did the right analysis. 
But I not sure whethe this is a call constraint and it should have been add a dictionary to call functions in this scenario.

**Comment by hanchaoqun** [comment] 2021-11-10 07:32
Ah...type looping through the type parameter list is not allowed since https://go-review.googlesource.com/c/go/+/361922
, the error changed:
<pre>
$ go tool compile ../test/typeparam/issue49441.go
../test/typeparam/issue49441.go:9:6: invalid recursive type pointerToT
        ../test/typeparam/issue49441.go:9:6: pointerToT refers to
        ../test/typeparam/issue49441.go:9:6: pointerToT
../test/typeparam/issue49441.go:17:3: cannot infer T (../test/typeparam/issue49441.go:13:8)
</pre>
So, this is not a bug ?

**Comment by aarzilli** [comment] 2021-11-10 08:01
The type inference bug is no longer a bug, unless someone can reproduce it without using a type cycle. The wrong line number for the error is a duplicate of #45985.

**Comment by hanchaoqun** [comment] 2021-11-10 08:05
I think it still a bug in the following code : 
<pre>
package main

type pointerToT[T any] interface{
*T
}

func F[T any, PT pointerToT[T]](n, nn PT) {
}

func WrapF[A any, PA pointerToT[A]](n, nn PA) {
	F(n, nn)
}
</pre>

error: "PT does not match *T"

**Comment by hanchaoqun** [comment] 2021-11-13 10:11
@dr2chase I make another reproducer, which compile error also occurs (should work with no error), and seems this kind of generic parameter constrained to be a pointer is very commonly used in container libraries such as "iterator" "list" etc. Maybe need should be labeled as release-blocker?

<pre>
package main

type pointerToT[T any] interface {
        *T
}

func innerFunc[T any, PT pointerToT[T]](ptr PT) {
}

func ExportFunc[A any, PA pointerToT[A]](ptr PA) {
        innerFunc(ptr)
}

</pre>

<pre>
$ go build crash.go
# command-line-arguments
./crash.go:13:23: PT does not match *T
</pre>

**Comment by griesemer** [comment] 2021-11-13 23:34
I agree that the error message is confusing. I disagree that the [last example](https://github.com/golang/go/issues/49441#issuecomment-967990885) should work without error, at least with the current implementation. Here's a slightly stripped-down version:

```Go
func f[T any, PT *T](x PT) {}

func _[T any, PT *T](x PT) {
        f(x)
}
```

Note that `x` is of type `PT` which is _not_ a pointer type, it's a type parameter. At the moment, we do not look inside type parameter constraints when attempting type inference. Note that:

```Go
func f[T any, PT *T](x PT) {}

func _[T any](x *T) {
        f(x)
}
```

works fine, so I am not sure why the `PT` type argument is needed in the first place.

**Comment by griesemer** [comment] 2021-11-13 23:43
At this point this issue it about a confusingly placed error message. For:
```Go
package p

func f[T any, P *T](x P) {}

func _[P *int](x P) {
        f(x)
}
```
we get the error:
```
testdata/manual.go2:3:15: P does not match *T
```
which is confusing.

I agree that https://go-review.googlesource.com/c/go/+/362634/ (thanks!) provides a better error position, but the error is still confusing.

I will file a separate issue for "deep inference" where we look inside a type parameter.

**Comment by griesemer** [comment] 2021-11-13 23:48
Actually, just noticing the reference #45985 as duplicate (for the incorrect position of the error), so closing.

**Closed by griesemer** 2021-11-13 23:48 UTC
Labels: NeedsInvestigation, generics
