### ISSUE TITLE
proposal: encoding/json: Struct omitempty

### ISSUE THREAD

**Issue by PumpkinSeed** [golang/go#58489] opened 2023-02-13 13:18 UTC
**Problem**

The current json package can't handle non-pointer struct encoding alongside with omitempty tag. This means we need to add the structs as pointers. Many of the proposals have been submitted. This is the main ticket dealing with this problem: https://github.com/golang/go/issues/11939

I tried to go to an other direction in this proposal, because the major problem with the IsZero, that it's not backward compatible. 

**Possible solution**

I think we need to use the `encOpts` located in the `json/encode.go`. By using it we can setup a solution which can handle this problem and just like the `SetIndent`, it can be called over the Encoder struct. 

One possible example can be the `SetOmitemptyOnIsZero(b bool)`, which omitting the value if the IsZero function of the given struct returns true. (Note, the naming conventions isn't good, it's just something for showing the idea.)

Implementation details: https://github.com/PumpkinSeed/go-json-proposal/pull/1/files

**Comment by seankhliao** [comment] 2023-02-13 15:53
Duplicate of #19763

**Closed by seankhliao** 2023-02-13 15:53 UTC
Labels: Proposal
