### ISSUE TITLE
net: windows TestDialTimeout flake

### ISSUE THREAD

**Issue by bradfitz** [golang/go#11474] opened 2015-06-29 19:47 UTC
Noticed this flake:
http://build.golang.org/log/de2ea0b431bc216003fd8762e62bbd46b3511fca

```
...
ok  	math/rand	5.305s
ok  	mime	1.365s
ok  	mime/multipart	2.470s
ok  	mime/quotedprintable	3.075s
--- FAIL: TestDialTimeout (0.00s)
	timeout_test.go:82: #3: dial tcp 127.0.0.1:0: connectex: The requested address is not valid in its context.
FAIL
FAIL	net	21.902s
ok  	net/http	10.666s
ok  	net/http/cgi	6.718s
ok  	net/http/cookiejar	1.583s
...
```

/cc @alexbrainman @mikioh

**Comment by alexbrainman** [comment] 2015-07-02 07:18
I run the test 100 times. It never breaks. The error is WSAEADDRNOTAVAIL.

Alex

**Comment by bradfitz** [comment] 2015-07-02 16:08
Did you run all the net tests, or just that one? Maybe there are interactions with other tests in the package.

**Comment by alexbrainman** [comment] 2015-07-03 08:01
I run "go test -short" in a loop now. No errors.

Alex

**Comment by rsc** [comment] 2015-07-15 03:12
Closing. If it happens again, reopen.

**Closed by rsc** 2015-07-15 03:12 UTC
Labels: OS-Windows, Testing

**Comment by mikioh** [comment] 2015-08-01 03:29
This is a duplicate of #11872.
