### ISSUE TITLE
x/build: android subrepo builds need to sync data files

### ISSUE THREAD

**Issue by mikioh** [golang/go#11452] opened 2015-06-29 01:32 UTC
See http://build.golang.org/log/ec8be097b936c5cf78f7d984ae62d39451ba6dff

```
go_android_exec: adb shell mkdir -p /data/local/tmp/charset.test-1846
go_android_exec: adb push /tmp/go-build720098852/golang.org/x/net/html/charset/_test/charset.test /data/local/tmp/charset.test-1846/charset.test-1846-tmp
1465 KB/s (3495200 bytes in 2.329s)
go_android_exec: adb shell cp '/data/local/tmp/charset.test-1846/charset.test-1846-tmp' '/data/local/tmp/charset.test-1846/charset.test-1846'
go_android_exec: adb shell rm '/data/local/tmp/charset.test-1846/charset.test-1846-tmp'
go_android_exec: adb shell export TMPDIR="/data/local/tmp/charset.test-1846"; export GOROOT="/data/local/tmp/goroot"; export GOPATH="/data/local/tmp/gopath"; cd "/data/local/tmp/gopath/src/golang.org/x/net/html/charset"; '/data/local/tmp/charset.test-1846/charset.test-1846' -test.short=true; echo -n exitcode=$?
/system/bin/sh: cd: /data/local/tmp/gopath/src/golang.org/x/net/html/charset: No such file or directory
```

**Comment by rsc** [comment] 2015-06-29 04:10
@crawshaw but pretty sure this is working as intended.

**Comment by crawshaw** [comment] 2015-06-29 11:02
go_android_exec is working as intended. But this could work, with some android-specific handling is needed in the sub-repository builder. In particular, the logic from go/src/androidtest.bash needs to be replicated.

**Comment by bradfitz** [comment] 2019-03-08 22:59
@eliasnaur, I think this is all done? Leaving for you to confirm and link CLs and close.

**Comment by eliasnaur** [comment] 2019-03-08 23:25
Fixed by the CL mentioned above, 165797.

**Comment by eliasnaur** [comment] 2019-03-08 23:25
Could use your +2 :)

**Closed** 2019-03-08 23:32 UTC
Labels: Builders, OS-Android
