### ISSUE TITLE
fmt: cannot read "\n" using a rune or byte

### ISSUE THREAD

**Issue by quark-zju** [golang/go#12537] opened 2015-09-08 05:42 UTC
It was okay in previous Go versions.

```
package main

import "fmt"

func main() {
	var c rune
	n, e := fmt.Sscanf("\n", "%c", &c)
	fmt.Println(n, e)
	// Go 1.5: 0 unexpected newline
	// Go 1.2, 1.3, 1.4: 1 <nil>
}
```

**Comment by robpike** [comment] 2015-09-08 14:21
This is fixed at tip. Duplicate of #12275

**Closed by robpike** 2015-09-08 14:21 UTC
