### ISSUE TITLE
cmd/vet: incorrectly flags an array as too small when initialized with a constant assigned from unsafe.Sizeof literal

### ISSUE THREAD

**Issue by jonbodner** [golang/go#60734] opened 2023-06-12 04:09 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 darwin/arm64
</pre>

(also shows up on Go playground)

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/jon/Library/Caches/go-build"
GOENV="/Users/jon/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jon/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jon/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jon/projects/vet_bug/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hj/mr53lrfj1bqf4hg62wqkp4000000gn/T/go-build3455060576=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
package main

import (
	"fmt"
	"unsafe"
)

type Data struct {
	Value  uint32   // 4 bytes
	Label  [10]byte // 10 bytes
	Active bool     // 1 byte
	// padded with 1 byte to make it align
}

func (d Data) String() string {
	return fmt.Sprintf(`{Value:%d, Label:%s, Active: %v}`, d.Value, string(d.Label[:]), d.Active)
}

const (
	dataSize = unsafe.Sizeof(Data{})
	dataSizeLiteral = 16
)

func main() {
	fmt.Println(dataSize)
	// use a literal value for array size: no go vet error
	incomingData2 := [16]byte{0, 132, 95, 237, 80, 104, 111, 110, 101, 0, 0, 0, 0, 0, 1, 0}
	fmt.Println(incomingData2)

	// use a constant based on unsafe.Sizeof for array size: ERROR INCORRECTLY REPORTED BY GO VET
	incomingData := [dataSize]byte{0, 132, 95, 237, 80, 104, 111, 110, 101, 0, 0, 0, 0, 0, 1, 0}
	fmt.Println(incomingData)

	// double check that the values aren't different
	fmt.Println(incomingData == incomingData2)
	fmt.Println(dataSize == 16)

	// constant has literal value: no go vet error
        incomingData3 := [dataSizeLiteral]byte{0, 132, 95, 237, 80, 104, 111, 110, 101, 0, 0, 0, 0, 0, 1, 0}
        fmt.Println(incomingData3)
}
```

run `go vet` on this code.

(also can find it at https://go.dev/play/p/q6r-qRpAGFa )

### What did you expect to see?

I expected no `go vet` warning.

### What did you see instead?

I get the following message from `go vet`:

```
$ go vet main.go
# command-line-arguments
vet: ./main.go:31:92: index 15 is out of bounds (>= 15)
```

**Comment by ianlancetaylor** [comment] 2023-06-12 05:29
Related to #60431.

**Comment by prattmic** [comment] 2023-06-13 19:24
cc @matloob @timothy-king

**Comment by timothy-king** [comment] 2023-06-14 20:16
This looks like it a type-checking failure and a likely duplicate of https://github.com/golang/go/issues/60734 . Let's come back to this after the other issue has been addressed.

**Comment by cuonglm** [comment] 2023-06-16 03:17
> This looks like it a type-checking failure and a likely duplicate of #60734 . Let's come back to this after the other issue has been addressed.

It's duplicated, I'm leaning to close this one in favor of #60734

**Closed** 2023-08-16 21:01 UTC
Labels: NeedsFix, Tools
