### ISSUE TITLE
x/tools/cmd/godoc: add UI to change GOOS or GOARCH

### ISSUE THREAD

**Issue by nhooyr** [golang/go#22178] opened 2017-10-08 19:13 UTC
In a recent reddit [post](https://www.reddit.com/r/golang/comments/752pkm/golangs_syscall_documentation_allows_you_to_set/) a user submitted a tip regarding how to view the syscall package docs for different a GOOS and GOARCH.

They noticed that if you append a query to the URL such as `?GOOS=darwin&GOARCH=mips64le`, you can control the GOOS and GOARCH of the displayed docs.

This definitely works but it is hard to use and discover. It would be nice if this feature had some UI element so that a user could just select the GOOS and GOARCH from a list and have the docs for that GOOS and GOARCH.

**Comment by rakyll** [comment] 2017-10-08 20:15
Duplicate of https://github.com/golang/gddo/issues/188.

**Comment by rakyll** [comment] 2017-10-08 20:17
Reopening because the request also requires a tracking issue for x/tools/cmd/godoc.

**Comment by seankhliao** [comment] 2024-12-02 17:48
done in pkgsite, godoc is deprecated.

**Closed by seankhliao** 2024-12-02 17:48 UTC
Labels: FeatureRequest, Tools
