### ISSUE TITLE
go/build: confusing error message 'found packages'

### ISSUE THREAD

**Issue by rillig** [golang/go#57414] opened 2022-12-20 21:57 UTC
### What version of Go are you using (`go version`)?
go version go1.19.4 windows/amd64

### What did you do?

~~~bash
echo 'package pkgname_test' > file1_test.go
echo 'package pkgname_test' > file2.go
go test
~~~

### What did you expect to see?
file2.go:1:9: only test files may declare a package ending in '_test'

### What did you see instead?
found packages pkgname (file1_test.go) and pkgname_test (file2.go)

That error message was confusing because `file1_test.go` does not declare the package `pkgname`.
The documentation of `MultiplePackageError.Files` says:
> corresponding files: Files[i] declares package Packages[i]

I discovered this constellation while fixing https://github.com/rillig/gobco so that it can handle a mixture of black box and white box tests in the same directory.

**Comment by seankhliao** [comment] 2022-12-20 22:33
Duplicate of #24895

**Closed by seankhliao** 2022-12-20 22:33 UTC
