### ISSUE TITLE
database/sql: TestPendingConnsAfterErr flaky on darwin/arm64

### ISSUE THREAD

**Issue by eliasnaur** [golang/go#15684] opened 2016-05-14 07:41 UTC
darwin/arm64 regularly fails with:

--- FAIL: TestPendingConnsAfterErr (0.01s)

```
sql_test.go:147: 1 connections still open after closing DB
```

FAIL

Process 279 exited with status = 1 (0x00000001) 
go_darwin_arm_exec: exited (test completion: exit status 253)
FAIL    database/sql    29.053s

Some builder logs:
https://build.golang.org/log/c3fae67a950cd6415bf39ccece80799814852c80
https://build.golang.org/log/fcb2c8b603b28d81ec5ab6ccba4bd12b4da28bce

**Comment by eliasnaur** [comment] 2016-05-25 11:08
Here's a similar recent trace from freebsd/arm:

https://build.golang.org/log/372776e543edae8bfda51d2ec70146a943eb71b6

**Comment by bradfitz** [comment] 2016-08-19 21:43
Happened again at https://storage.googleapis.com/go-build-log/44200ef6/freebsd-386-gce101_566a8190.log via https://golang.org/cl/27200 trybot failure

**Comment by bradfitz** [comment] 2016-10-22 17:22
@kardianos, maybe you can take a look at this too? (if you don't have enough on your plate)

But I figure all this stuff is currently more in your head than mine.

**Comment by kardianos** [comment] 2016-10-31 15:01
@bradfitz I'll look into this shortly. Thanks.

**Comment by kardianos** [comment] 2016-11-19 23:57
I'm able to reproduce this. By adding the following:
```
+++ b/src/database/sql/sql_test.go
@@ -1509,6 +1509,7 @@ func TestPendingConnsAfterErr(t *testing.T) {
        unblock := make(chan struct{})
        setHookOpenErr(func() error {
                <-unblock // block until all connections are in flight
+               runtime.Gosched()
                return errOffline
        })
```
It reliably fails with `	sql_test.go:148: 1 connections still open after closing DB`. However adding `runtime.Gosched()` to the last line of the func allows the test to pass again (this is all on a std linux amd64 laptop).

By assumption is that we are seeing the failures on slower machines that have slightly different scheduler patterns due to load. I'll look into updating the test soon.

**Closed** 2016-11-22 23:36 UTC
Labels: NeedsInvestigation, Testing
