### ISSUE TITLE
os/user `User.Current()` fails on Linux user accounts created by systemd-homed

### ISSUE THREAD

**Issue by ananthb** [golang/go#57454] opened 2022-12-24 16:51 UTC
`User.Current()` returns an `unknown user id 60237` error because users created by systemd-homed don't exist in /etc/passwd.

**Comment by wizardishungry** [comment] 2022-12-24 17:05
Relates to: https://github.com/golang/go/issues/38810

**Comment by seankhliao** [comment] 2022-12-24 17:23
Duplicate of #38810

**Closed by seankhliao** 2022-12-24 17:23 UTC
