### ISSUE TITLE
cmd/go: `go get -u golang.org/x/lint/golint` fails in module mode

### ISSUE THREAD

**Issue by ainar-g** [golang/go#26380] opened 2018-07-14 00:25 UTC
```
$ mkdir /tmp/foo && cd /tmp/foo
$ echo 'package foo // import "foo"' > main.go
$ go mod -init
$ go get -u golang.org/x/lint/golint
go get golang.org/x/lint/golint: missing module for import: golang.org/x/lint@v0.0.0-20180702182130-06c8688daad7 provides golang.org/x/lint/golint
```

When I first saw this message, I thought it complained about the fact that I didn't import `golang.org/x/lint/golint` anywhere in my code. A better error message for such cases would be something like

```
golang.org/x/lint/golint is a part of golang.org/x/lint module; use go get golang.org/x/lint@v0.0.0-20180702182130-06c8688daad7
```

Or, even better, if the go tool knows the module I am trying to add, why not just add it?

**Comment by bcmills** [comment] 2018-07-16 16:15
> if the go tool knows the module I am trying to add, why not just add it?

That is intended to work as of https://golang.org/cl/122396. The fact that it doesn't is #25917, and I think this issue is a duplicate of that one. (Please reopen if it is not.)

**Comment by llimllib** [comment] 2018-08-03 20:12
Another example that led me here, and which I'll leave here in case it helps somebody google or test:

```
$ go get golang.org/x/tools/cmd/goimports
go: finding golang.org/x/tools/cmd/goimports latest
go: finding golang.org/x/tools/cmd latest
go: finding golang.org/x/tools latest
go: downloading golang.org/x/tools v0.0.0-20180803180156-3c07937fe18c
go get golang.org/x/tools/cmd/goimports: missing module for import: golang.org/x/tools@v0.0.0-20180803180156-3c07937fe18c provides golang.org/x/tools/cmd/goimports
```

**Comment by bcmills** [comment] 2018-08-03 23:28
Thanks. I'm pretty sure this is another symptom of the root cause described in https://github.com/golang/go/issues/26602#issuecomment-410395277.

**Comment by myitcv** [comment] 2018-08-07 11:59
@thepudds as discussed on Slack, that scenario is also a symptom of https://github.com/golang/go/issues/26602#issuecomment-410395277; just confirmed that it's fixed by https://go-review.googlesource.com/c/go/+/128136

**Comment by bcmills** [comment] 2018-08-07 22:20
Yep, I think at this point we can be pretty confident this is a dup of #26602.

**Closed by bcmills** 2018-08-07 22:20 UTC
Labels: modules
