### ISSUE TITLE
main: reference to nonexistent package fmt

### ISSUE THREAD

**Issue by vt-alt** [golang/go#48565] opened 2021-09-23 00:49 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/src/.cache/go-build"
GOENV="/usr/src/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=" -mod=vendor"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/usr/src/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/usr/src/RPM/BUILD/github-cli-1.5.0/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/usr/src/tmp/go-build4106274379=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

We (in ALT Linux) have package post-processing (brp) which runs `strip` on all `.a` archives. This later breaks `go build` with errors like:
```
builder@x86_64:~/RPM/BUILD/github-cli-1.5.0$ go build -o script/build script/build.go
# command-line-arguments
2021/09/23 00:37:21 main: reference to nonexistent package fmt
```

After some investigations we found that `strip` adds `/` terminator to the file names in `.a`, it's [standard for sysv/GNU `ar`](https://en.wikipedia.org/wiki/Ar_(Unix)#File_header). But, this addition of terminator breaks build later, making processed package `nonexistent`.

### You can reproduce strip step with
```
root@x86_64:/usr/lib/golang/pkg/linux_amd64# strip -p -R '.gnu.lto_*' -R '.gnu.debuglto_*' -N '__gnu_lto_v1' -- fmt.a
```
It will output (harmless) warnings, but should not change archive except by adding `/` to the file names.

Of course we will skip stripping step for these libraries for `go` package. But, it would be beneficial if Go `link` supported `.a` content file names with `/` terminator.

**Comment by vt-alt** [comment] 2021-09-23 03:39
Maybe simpler and more detailed way to reproduce for `fmt.a`:

We have modules in `/usr/lib/golang/pkg/linux_amd64`. And we will use `objcopy` as this is same as `strip` and should not change anything, just copy file back onto itself using `binutils` code.
```
root@x86_64:/usr/lib/golang/pkg/linux_amd64# cp -a fmt.a fmt.a~
root@x86_64:/usr/lib/golang/pkg/linux_amd64# objcopy fmt.a
objcopy: fmt.a(__.PKGDEF): Unable to recognise the format of file: file format not recognized
objcopy: fmt.a(_go_.o): Unable to recognise the format of file: file format not recognized
```
These warnings are normal, `objcopy` just copied everything. Now bype-by-byte compare of source (from the backup copy) and copied files:
```
root@x86_64:/usr/lib/golang/pkg/linux_amd64# cmp -bl fmt.a~ fmt.a
    18  40       57 /
 13045  40       57 /
727582   0 ^@    12 ^J
```
`727582` is the trailing byte. `40` (in oct) to `57` is '/' terminator appended to the filename:
```
root@x86_64:/usr/lib/golang/pkg/linux_amd64# xxd fmt.a~ | head -2
00000000: 213c 6172 6368 3e0a 5f5f 2e50 4b47 4445  !<arch>.__.PKGDE
00000010: 4620 2020 2020 2020 3020 2020 2020 2020  F       0
root@x86_64:/usr/lib/golang/pkg/linux_amd64# xxd fmt.a | head -2
00000000: 213c 6172 6368 3e0a 5f5f 2e50 4b47 4445  !<arch>.__.PKGDE
00000010: 462f 2020 2020 2020 3020 2020 2020 2020  F/      0
```
This is normal for `ar`, actual filename is not changed:
```
root@x86_64:/usr/lib/golang/pkg/linux_amd64# ar tv fmt.a
rw-r--r-- 0/0  12970 Jan  1 00:00 1970 __.PKGDEF
rw-r--r-- 0/0 714483 Jan  1 00:00 1970 _go_.o
```
But, isn't normal for `go tool pack`:
```
root@x86_64:/usr/lib/golang/pkg/linux_amd64# go tool pack tv fmt.a~
-rw-r--r--      0/0             12970 Jan  1 00:00 1970 __.PKGDEF
-rw-r--r--      0/0            714483 Jan  1 00:00 1970 _go_.o
root@x86_64:/usr/lib/golang/pkg/linux_amd64# go tool pack tv fmt.a
panic: runtime error: slice bounds out of range [:-210]

goroutine 1 [running]:
cmd/internal/archive.(*objReader).skip(0xc000156000, 0xffffffffffffff2e)
    /usr/lib/golang/src/cmd/internal/archive/archive.go:219 +0x145
cmd/internal/archive.(*objReader).parseObject(0xc000156000, 0xc000136040, 0x32aa)
    /usr/lib/golang/src/cmd/internal/archive/archive.go:432 +0x48a
cmd/internal/archive.(*objReader).parseArchive(0xc000156000, 0x1)
    /usr/lib/golang/src/cmd/internal/archive/archive.go:371 +0x565
cmd/internal/archive.Parse(0xc000132018, 0x5)
    /usr/lib/golang/src/cmd/internal/archive/archive.go:261 +0x265
main.openArchive({0x7ffd9f36b601, 0x4c2f64}, 0x0, {0xc000120150, 0x0, 0x0})
    /usr/lib/golang/src/cmd/pack/pack.go:130 +0xeb
main.main()
    /usr/lib/golang/src/cmd/pack/pack.go:53 +0x27f

```

**Comment by cherrymui** [comment] 2021-09-23 16:47
Files like fmt.a are not ELF archive/object files and are not intended to be read/write by anything other than the Go toolchain itself. Using GNU strip or objcopy on them are not going to work.

If you like, you could probably just delete those files (see https://github.com/golang/go/issues/47257).

Closing as working as intended. Thanks.

**Closed by cherrymui** 2021-09-23 16:47 UTC
