### ISSUE TITLE
`go run` repeatedly reports dependency find when run out of GOPATH with modules on

### ISSUE THREAD

**Issue by ucirello** [golang/go#34828] opened 2019-10-10 17:06 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/TheUser/Library/Caches/go-build"
GOENV="/Users/TheUser/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/TheUser/src/strongdm"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_l/9yb78fmx0jzb8khycvrzw3qw0000gn/T/go-build257911427=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Tried to run this piece of code out of the `GOPATH` with `GO111MODULE=on` 

<details><summary>main.go</summary><br>
<pre>
$ cat main.go
package main

import (
    "github.com/chzyer/readline"
)

func main() {
	_ = readline.New
}
</pre>
</details>

### What did you expect to see?

```
$ go run main.go
$
```

### What did you see instead?

```
$ go run main.go
go: finding github.com/chzyer/readline latest
$
```

--- 

A couple of extra facts:
1. It doesn't happen with `github.com/davecgh/go-spew/spew`
2. It does happen with `github.com/chzyer/readline`
3. It does report the download efforts after `go clean -modcache`

**Comment by bcmills** [comment] 2019-10-10 17:25
This interaction is at the intersection of #32027 and #33284.

#32027 will address it (in 1.14) by making the unresolved import an explicit error, instead of trying to resolve it.

The difference between `github.com/chzyer/readline` and `github.com/davecgh/go-spew/spew` is that the latter has explicit tags, and the `finding` message happens to only occur on the path that downloads a branch.

#33284 would make the two modules consistent by always logging the dependency change for both.

**Comment by bcmills** [comment] 2019-10-10 17:25
Duplicate of #32027

**Closed by bcmills** 2019-10-10 17:25 UTC
