### ISSUE TITLE
go test ./... does not detect tests in submodules of multimodule projects

### ISSUE THREAD

**Issue by cyrusv** [golang/go#59476] opened 2023-04-07 01:12 UTC
### What version of Go are you using (`go version`)?

1.20.1

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

amd64

### What did you do?
`go test ./...` documentation specifies that it will find all subpackages. Documentation leads to believe that all test files will be executed. However, test files in a submodule of a multi-module project are ignored.

This is especially shocking when your CICD is counting on `go test ./...`, and you add a v2 submodule.

###
People work around it like this: https://stackoverflow.com/questions/61163306/running-go-test-in-parent-directory-of-multiple-go-modules

Either this is a bug that should be fixed (happy to open a PR with some guidance), or the documentation should be updated to specify the expected behavior in submodule/multimodule case.

**Comment by seankhliao** [comment] 2023-04-07 05:54
Duplicate of #27957

**Closed by seankhliao** 2023-04-07 05:54 UTC
