### ISSUE TITLE
cmd/cgo: sometimes when passing a struct to C containing a go pointer to a struct field, the entire go struct is checked for go pointers instead of just the field

### ISSUE THREAD

**Issue by AlexRouSg** [golang/go#63460] opened 2023-10-09 10:55 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=~\AppData\Local\go-build
set GOENV=~\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=~\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=~\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\alexr\AppData\Local\Temp\go-build886793640=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```go
package main

/*
 typedef struct foo_t *foo;

 typedef struct {
	foo* pfoo;
 }info;

 void test(info i) {}
*/
import "C"

type foo struct {
	cFoo C.foo
	bar  []interface{}
}

func main() {
	f := foo{bar: []interface{}{0}}
	info := C.info{&f.cFoo}
	C.test(info)
}
```

### What did you expect to see?
Code compiles and runs with no output

### What did you see instead?
```
panic: runtime error: cgo argument has Go pointer to unpinned Go pointer
```

Notes:
Not setting the field `bar: []interface{}{0}` or changing function call to look like `C.test(&f.cFoo)` does not trigger this

**Comment by dmitshur** [comment] 2023-10-09 22:50
CC @golang/runtime.

**Comment by ianlancetaylor** [comment] 2023-10-09 23:20
This is similar to #14210.  The cgo tool is not smart enough to pull apart what you are doing in your Go code.  It loses the `&f.cFoo` and just checks the entire allocation to which the pointer points.

It would be nice to fix if somebody can figure out how.  But nobody is working on this.

**Comment by AlexRouSg** [comment] 2023-10-10 15:31
That's fair and I have no expectation/need of this getting fixed anytime soon since the workaround is just to add a `c := f.cFoo`
However, would it be a good idea to at a minimum point this out in the doc as a known limitation that may or may not get fixed in the future?

**Comment by bcmills** [comment] 2023-10-13 16:41
Is this a duplicate of #28606?

**Comment by ianlancetaylor** [comment] 2023-10-13 18:54
Thanks, I thought there was an open issue but I couldn't find it.  Marking as a dup since it's essentially the same problem.

**Closed by ianlancetaylor** 2023-10-13 18:54 UTC
Labels: NeedsInvestigation, compiler/runtime
