### ISSUE TITLE
x/tools/gopls: support window/showMessage request

### ISSUE THREAD

**Issue by jadekler** [golang/go#33198] opened 2019-07-19 23:15 UTC
Sometimes gopls takes a few seconds to process what's happening. I don't have a concrete example - it just seems to sometimes take 100ms to do something, and other times it takes 5s.

It would be great if gopls would fail fast with an error message that popped up in vscode, and that I could adjust what that threshold should be.

Having fast feedback is almost always more important to me than eventual correctness.

**Comment by stamblerre** [comment] 2019-07-21 17:44
What features are you finding that take 5s? We are working on correcting this behavior, so ultimately it shouldn't be necessary. The only way for `gopls` to send error messages that pop up in VSCode is via the diagnostics messages (the same way that `gopls` shows errors in your code).

**Comment by jadekler** [comment] 2019-07-22 14:15
> What features are you finding that take 5s?

I'm afraid I'm a bit unintelligent about gopls vis-a-vis separating "it works" into features heh. So, not sure. General use, though, I suppose?

> The only way for gopls to send error messages that pop up in VSCode is via the diagnostics messages (the same way that gopls shows errors in your code).

Ah, gotcha. That seems limiting, so maybe this request is not feasible?

> We are working on correcting this behavior, so ultimately it shouldn't be necessary.

Gotcha. Is there a different issue I should track, and close this one?

**Comment by stamblerre** [comment] 2019-07-22 18:35
We've heard reports of imports taking too long, which is why I ask. I guess we could also make use of the https://microsoft.github.io/language-server-protocol/specification#window_showMessage LSP request, so I guess we could change this issue to be that.

**Comment by stamblerre** [comment] 2019-08-06 18:50
This issue is really a duplicate of https://github.com/golang/go/issues/31668. Closing in favor of that issue.

**Closed** 2019-08-06 21:51 UTC
Labels: gopls
