### ISSUE TITLE
x/tools/gopls: sometimes documentation on hover is not shown

### ISSUE THREAD

**Issue by inliquid** [golang/go#46158] opened 2021-05-13 17:27 UTC
1. VS Code
2. go1.16.4
3. gopls@master

For example in case of `(*url.URL).Query()`:

![изображение](https://user-images.githubusercontent.com/6797881/118162416-6240ba00-b429-11eb-89d6-573b6e69a0e5.png)

![изображение](https://user-images.githubusercontent.com/6797881/118162436-6a98f500-b429-11eb-94b6-f3ff82c4f3a3.png)

**Comment by findleyr** [comment] 2021-05-14 00:22
Thanks for the report. Which gopls commit did you build at? I thought this might be related to recent work on AST trimming, but can't reproduce at tip.

Are you able to repro? If so, can you please capture RPC logs, as described here?
https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information

**Comment by inliquid** [comment] 2021-05-14 10:59
It was built with `go install` run from the gopls repo.

Unfortunately I can't reproduce it now, it had been in that state for a while, but after restart of VS Code, I can see documentation for this particular function. I'll watch over it and let you know if this repeats.

**Comment by ShoshinNikita** [comment] 2021-05-14 17:27
I faced a similar issue. But in my case fields of a struct have disappeared. The first commit with this issue is golang/tools@cd1d0887dc8cfcfb844340a5fce628c61da00a20. Note that this behavior is inconsistent (see screenshots) 

**Steps to reproduce**

```go
package main

import (
	"github.com/go-pg/pg/v10/orm"
)

func main() {
	orm.NewQuery(nil, nil)
	(&orm.Query{}).New()
}
```

1. Go to Definition of `orm.NewQuery`
2. Hover on the return value
3. `Query` has ho fields

And

1. Go to Definition of method `(*orm.Query).New`
2. Hover on `Query` in the line `clone := &Query{`
3. `Query` has fields, but they are poorly formatted

**gopls@09ab05b (master)**

| 1 | 2 |
| - | - |
| ![image](https://user-images.githubusercontent.com/30220965/118304368-443d8d00-b4ef-11eb-801e-196814d9e182.png) | ![image](https://user-images.githubusercontent.com/30220965/118305860-3e48ab80-b4f1-11eb-8cd1-44e8b60b25d5.png) |

**gopls@v0.6.11**

| 1 | 2 |
| - | - |
| ![image](https://user-images.githubusercontent.com/30220965/118304514-6d5e1d80-b4ef-11eb-8948-1805482ba985.png) | ![image](https://user-images.githubusercontent.com/30220965/118305923-515b7b80-b4f1-11eb-9206-43c9761ce2d1.png) |

**Comment by findleyr** [comment] 2021-05-17 14:38
FWIW, I think these are separate issues.

@ShoshinNikita you issue seems to clearly be a result of AST trimming. I am not so sure about the original issue.  Keeping this as a single issue until I understand it better.

**Comment by findleyr** [comment] 2021-05-18 13:04
The CL above should fix the issue reported by @ShoshinNikita, but I'm still not sure what's going on in the original issue: none of the AST trimming should have dropped comments.

So I think we should leave this issue open for a little while in case the problem reoccurs and we can capture logs. Unassigning in the meantime.

**Comment by stamblerre** [comment] 2021-05-21 17:48
@inliquid: Have you encountered this again, after the CL above? If not, let's close this issue as I think it has been resolved.

**Comment by inliquid** [comment] 2021-05-21 19:12
@stamblerre no, haven't seen this so far.

**Comment by ShoshinNikita** [comment] 2021-06-08 19:46
@findleyr At first, I decided the issue I reported is not completely fixed. But then I understood it is the intended result of AST trimming. Is that correct?

Exported function `ast.FilterFile`:

![image](https://user-images.githubusercontent.com/30220965/121246577-ff1c3900-c8a9-11eb-98a2-48d8cb11f9c7.png)

Unexported function `ast.filterFile`:

![image](https://user-images.githubusercontent.com/30220965/121246618-093e3780-c8aa-11eb-9f13-759e7fb42f88.png)

**Comment by findleyr** [comment] 2021-06-09 14:31
Thanks for catching that. This must be an edge case that doesn't trigger re-parsing, for some reason.

I'll look into it.

**Comment by findleyr** [comment] 2021-07-09 18:41
The issue is that in the case of filterFile, we're not finding the hovered declaration at all. The patch of CL 320550 was really too shallow: we need a mechanism for specifying *exactly* what information is needed to fulfill the hover request, and this mechanism should go through the gopls cache.

I'm experimenting with this now, but it will likely turn out not to be a small change.

**Comment by ShoshinNikita** [comment] 2022-02-06 13:09
@findleyr I think I found a regression introduced in the last CL (https://golang.org/cl/333690):

1. Open the following code

	```go
	package main

	import "go/ast"

	func main() {
		var l *ast.BasicLit
		_ = l.Value
	}
	```

2. Hover on `Value` - there's **no** comment

	<img src="https://user-images.githubusercontent.com/30220965/152681565-7053277c-9ec1-488c-9b56-21082426cb0a.png" width="350">

3. Press `Ctrl + Space` 2 times (trigger suggestions and toggle details) - there's a comment

	<img src="https://user-images.githubusercontent.com/30220965/152681578-c8909789-8fde-40d0-a04a-a5d3cf04e9a2.png" width="350">

4. Go to `Value` definition and trigger hover - there's a comment

	<img src="https://user-images.githubusercontent.com/30220965/152681591-fe16f6e2-0170-4f92-969d-771b399eb26c.png" width="350">

**Note:** it's happening only with packages from std lib and other modules

***

Updated `TestHoverUnexported` to reproduce this issue:

<details>
<summary>code</summary>

```go
func TestHoverUnexported(t *testing.T) {
	const proxy = `
-- golang.org/x/structs@v1.0.0/go.mod --
module golang.org/x/structs

go 1.12

-- golang.org/x/structs@v1.0.0/types.go --
package structs

type Mixed struct {
	// Exported comment
	Exported   int
	unexported string
}

func printMixed(m Mixed) {
	println(m)
}
`
	const mod = `
-- go.mod --
module mod.com

go 1.12

require golang.org/x/structs v1.0.0
-- go.sum --
golang.org/x/structs v1.0.0 h1:Ito/a7hBYZaNKShFrZKjfBA/SIPvmBrcPCBWPx5QeKk=
golang.org/x/structs v1.0.0/go.mod h1:47gkSIdo5AaQaWJS0upVORsxfEr1LL1MWv9dmYF3iq4=
-- main.go --
package main

import "golang.org/x/structs"

func main() {
	var m structs.Mixed
	_ = m.Exported
}
`

	// TODO: use a nested workspace folder here.
	WithOptions(
		ProxyFiles(proxy),
	).Run(t, mod, func(t *testing.T, env *Env) {
		env.OpenFile("main.go")
		mixedPos := env.RegexpSearch("main.go", "Mixed")
		got, _ := env.Hover("main.go", mixedPos)
		if !strings.Contains(got.Value, "unexported") {
			t.Errorf("Workspace hover: missing expected field 'unexported'. Got:\n%q", got.Value)
		}

		cacheFile, _ := env.GoToDefinition("main.go", mixedPos)
		argPos := env.RegexpSearch(cacheFile, "printMixed.*(Mixed)")
		got, _ = env.Hover(cacheFile, argPos)
		if !strings.Contains(got.Value, "unexported") {
			t.Errorf("Non-workspace hover: missing expected field 'unexported'. Got:\n%q", got.Value)
		}

		exportedFieldPos := env.RegexpSearch("main.go", "Exported")
		got, _ = env.Hover("main.go", exportedFieldPos)
		if !strings.Contains(got.Value, "comment") {
			t.Errorf("Workspace hover: missing comment for field 'Exported'. Got:\n%q", got.Value)
		}
	})
}
```
</details>

***

The regression is caused by this code:

```go
// Always use the full declaration here if we have it, because the
// dependent code doesn't rely on pointer identity. This is fragile.
if d, _ := fullDecl.(*ast.GenDecl); d != nil {
	node = d
}
```

We can't find a comment (see function `findFieldComment`) because fields of `fullDecl` have completely different token positions. For example:

1. We try to find a comment for field with pos `2318327`
2. `node` before update: `&ast.GenDecl{Doc:(*ast.CommentGroup)(0xc002ba5c50), TokPos:2317438, Tok:84, ...}`
3. `node` after update: `&ast.GenDecl{Doc:(*ast.CommentGroup)(0xc00d5d7cf8), TokPos:36467060, Tok:84, ...}`
4. Fields of "new" `node` has the following positions: `36467816`, `36467859`, `36467949`

**Comment by findleyr** [comment] 2022-02-09 21:33
@ShoshinNikita thank you for that investigation!

Moving this to v0.8.0.

**Closed** 2022-02-17 17:37 UTC
Labels: gopls, Tools
