### ISSUE TITLE
crypto/rand `Read` example error

### ISSUE THREAD

**Issue by adams-sarah** [golang/go#13138] opened 2015-11-03 21:41 UTC
https://golang.org/pkg/crypto/rand/
The last example, `Read` prints an error upon running.

I don't see anything wrong with the example code, though I don't play with this package much.

out:
`error: read /dev/urandom: Invalid argument`

Screenshot:
<img width="787" alt="screen shot 2015-11-03 at 1 33 19 pm" src="https://cloud.githubusercontent.com/assets/2741356/10922467/1eea9f72-8230-11e5-8761-638888c0d51a.png">

Wish I could be more help :/

Sarah

**Comment by rakyll** [comment] 2015-11-03 22:06
It is a playground restriction. Duplicate of https://github.com/golang/go/issues/5096.

The same call must work fine on your own machine.

**Closed by rakyll** 2015-11-03 22:06 UTC

**Comment by adg** [comment] 2015-11-03 22:09
This is related to issue #5096

**Comment by adams-sarah** [comment] 2015-11-03 22:11
ah, thx @rakyll . yep it works fine on my box
