### ISSUE TITLE
higher-order functions built in to slice

### ISSUE THREAD

**Issue by huoy** [golang/go#14173] opened 2016-02-01 09:19 UTC
I've been using Go for about 9 months and over that time I've come to like the explicitness of most of the language's semantics. But I feel that the language lacks some convenient ways to handle slices as you will find in most other languages. I feel that adding HOFs such as map/filter/reduce would make code less verbose when handling slices without compromising on explicitness or type-safety.

The current idiom for doing a map operation is something like:

```go
s0 := []int{1,2,3}
s1 := make([]int, 3)

for i := range s0 {
    s1[i] = s0[i] * 2
}
```

While this is a trivial case, and I could have just mutated `s0` in this case, it is clearly very imperative and verbose compared to what it could be.

I propose an alternative:

```go
s0 := []int{1,2,3}
s1 := s0.map(func(x int) int {
    return x * 2
})
```

In this case the function passed to map has two properties of interest. The argument which would need to be the slice's Kind (type-checked at compile time), and the return type which could be any type. The one caveat is that the type of the resulting slice will need to be inferred from the type returned from the function. 

For example:

```go
s0 := []int{1,2,3}
s1 := s0.map(func(x int) float32 {
    return float32(x) / 2
})
```

where `s1` would have type `[]float32`.

I feel like this seemingly low-hanging fruit would be a step in the right direction in terms of making the language more enjoyable to use with its lack of generics.

**Comment by mrcrilly** [comment] 2016-02-01 10:14
I like the idea you've proposed, but what I personally like about the for-loop syntax is the readability of it. 

When I look at the examples you've cited, I feel the for-loop syntax is easier to read. I'm also of the opinion that if the `map()` functionality you've prosed yields the same run time code/performance, then it's extra work for not a lot of gain. In fact it would simply be adding fluff to the language that's not needed.

Another thing to consider is whether or not you want your language's grammar to include several different way of doing the same job. I know I don't. I like the fact that a for-loop is the de facto means of looping over a slice.

Finally, when I compare your for-loop example to the `map()` examples you've provided, I feel as though I'm looking at a comparison between C like syntax and JavaScript like syntax - I simply cannot stand the in-line function syntax (heavily) present in JavaScript and in your example.

**Comment by huoy** [comment] 2016-02-01 10:31
>When I look at the examples you've cited, I feel the for-loop syntax is easier to read.

I have a feeling that the reason for that is because of the example's triviality. In my experience the map functionality helps "declare" what you're doing, by making it even more explicit the operation you're trying to achieve. In this case a mapping from one set to another.

>In fact it would simply be adding fluff to the language that's not needed.

I'm not sure how you define `fluff`, and it surely isn't "needed", but in the same vein I presume you came from C to Go for more than just the concurrency model. C is clunky and primitive. Adding convenience is pretty much the nature of PL advancements. All the way up from assembly.

>Another thing to consider is whether or not you want your language's grammar to include several different ways of doing the same job. I know I don't. 

Go has foregone that already :) See short and long declarations, `new`, etc. Not to say we should keep adding kludge, though this proposal doesn't actually add any additional grammar to my knowledge. 

>Finally, when I compare your for-loop example to the map() examples you've provided, I feel as though I'm looking at a comparison between C like syntax and JavaScript like syntax - I simply cannot stand the in-line function syntax (heavily) present in JavaScript and in your example.

That is an opinion I don't think I could change, however it's more than just javascript that has higher-order functions. See erlang, scala, haskell, etc.

**Comment by mrcrilly** [comment] 2016-02-01 10:59
> That is an opinion I don't think I could change, ...

Likewise.

**Comment by RLH** [comment] 2016-02-01 13:16
This approach risks reinforcing sequential programming patterns that are
less and less suitable for our more and more parallel hardware. If Go
decides to do this then it should treat the  functions
reduce/scan/scatter/map/combine/filter as parallel combinators.  "for" can
be used to express sequential execution.

Of course this is not as simple as it sounds since it puts restrictions on
the closures such as the need to be associative, idempotent, and so forth.
How or even if that needs to be mechanically enforced would have to be
worked out.  Perhaps Go will someday tackle this and it would be a shame if
these keywords and approaches had to deal with a sequential legacy suitably
expressed with for.

I haven't seen any compelling use cases to support adding parallel
combinators to Go 1.7 nor am I proposing it. It would be a lot of work. I
just don't want to foreclose on a future proposal by adding a sequential
semantic legacy today.

**Comment by bradfitz** [comment] 2016-02-01 17:40
Go is not accepting language change proposals at this time (Go 1.x is frozen), and this is also a duplicate of what many people have wanted for a hypothetical Go2. If a Go2 happens, there are many overlapping proposals with this, but part of Go2 would be reconciling all such proposals into something coherent.

**Closed by bradfitz** 2016-02-01 17:40 UTC

**Comment by bitdivine** [comment] 2016-07-01 13:28
+1 even if in the amusingly named Go 2 :-)
