### ISSUE TITLE
strings: strings.Builder with sync.Pool case memory leak 

### ISSUE THREAD

**Issue by szyhf** [golang/go#34463] opened 2019-09-23 00:53 UTC
### What version of Go are you using (`go version`)?

Tried both 1.13.0 and 1.12.9.

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

In docker image `alpine:3.8`, build cmd is `GOOS=linux GOARCH=amd64 go build` on macOS `10.14.6`

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Using a `sync.Pool` to reuse strings.Builder.

https://play.golang.org/p/TkWbxGu4PRJ

I use strings.Builder to build sql, and exec the `sql-str` every times, but I found that the memory will increase slowly, then I called `pprof/heap` and found that the `strings.(*Builder).WriteString` inuse a lot of memory and looks never released.

![QQ20190923-085002](https://user-images.githubusercontent.com/14870120/65397050-2d5c9b00-dddf-11e9-898a-ac406372a285.png)

### What did you expect to see?

The memory not increase unexpectedly

### What did you see instead?

The memory not increase unexpectedly

Really thanks for help!

**Comment by ianlancetaylor** [comment] 2019-09-23 02:07
Please show us more of the program.  The memory profile you show is exactly what I would expect if your program never releases the strings built with `strings.Builder`.

That said, while there may be a bug here somewhere, it does not make sense to put `strings.Builder` values into a `sync.Pool`.  Allocating a new `strings.Builder` costs nothing.  This is not a case where you should be using a `sync.Pool`.

**Comment by szyhf** [comment] 2019-09-23 03:32
> Please show us more of the program. The memory profile you show is exactly what I would expect if your program never releases the strings built with `strings.Builder`.
> 
> That said, while there may be a bug here somewhere, it does not make sense to put `strings.Builder` values into a `sync.Pool`. Allocating a new `strings.Builder` costs nothing. This is not a case where you should be using a `sync.Pool`.

---

Thanks for help.

Yes, you are right, when I read the detail code of `strings.Builder` I recognized that it's different from `bytes.Buffer`, so I remove the `sync.Pool` of `strings.Builder` hours ago and upgrade our prod application and hope if it help.

---

We are using `https://github.com/astaxie/beego/tree/develop/orm` to exec sql, the var `ormer` in demo is `orm.Ormer` config as `mysql`, and I skip the init of it.

The main target of the function is to build a sql like `insert into test_tbl (id,dr) values (1,'2'),(2,'3'),...(x,'y') on duplicate key update dr=values(dr);`

The demo of our function is here: https://play.golang.org/p/o0cEeZ7o7xl

The function is called every 3min by a time.Ticker.

The memory increase really slow, the memory monitor of previous 7 days is blow:

![QQ20190923-112925](https://user-images.githubusercontent.com/14870120/65400549-74558b00-ddf5-11e9-83dc-d83cb8cb88b9.png)

This case me to read heap to looking for what is leaking.

Thanks again~

**Comment by martisch** [comment] 2019-09-23 03:35
Closing as this looks to be resolved and working as intended.

**Closed by martisch** 2019-09-23 03:35 UTC
Labels: WaitingForInfo

**Comment by szyhf** [comment] 2019-09-24 09:58
> Closing as this looks to be resolved and working as intended.

@martisch

I've remove the `sync.Pool` yesterday, and use `new(strings.Builder)` every called. But the leaking is still there, slow but continuous.

![QQ20190924-175638](https://user-images.githubusercontent.com/14870120/65502118-c6310a80-def4-11e9-9c90-4b3a9aa43c44.png)

**Comment by szyhf** [comment] 2019-09-27 01:50
Hi, @martisch @ianlancetaylor 

I've tried some solution and I think I found the leaking code, but I don't know why(I think it's a bug).

First solution, I remove the usage of `sync.Pool`, I create a new `strings.Builder`  every time, and the leaking is still slow but continues.

```golang
// Key code of first solution
sb := new(strings.Builder)

// full code writing ref: https://play.golang.org/p/o0cEeZ7o7xl
// sb.WriteString(...)
// sb.WriteRune(...)

_, err := ormer.Raw(strings.TrimSuffix(sb.String(), ","), sqlParamList...).Exec()
```

The second solution worked and the memory is not leaking.

```golang
// Key code of second solution

sb := new(strings.Builder)

// full code writing ref: https://play.golang.org/p/o0cEeZ7o7xl
// sb.WriteString(...)
// sb.WriteRune(...)

sql := sb.String()
sql = strings.TrimSuffix(sql, ",")
sb.Reset()
sb = nil
_, err := ormer.Raw(sql, sqlParamList...).Exec()
```

Here is the memory usage curve: 

![QQ20190927-093834](https://user-images.githubusercontent.com/14870120/65735670-ce629300-e10a-11e9-944d-353bcff4557f.png)

I don't really understand why the first solution will case the `strings.Builder` not release the memory ?

Here is the heap of first solution:

![QQ20190924-175638](https://user-images.githubusercontent.com/14870120/65735972-fdc5cf80-e10b-11e9-8cb1-a7b1cd71f255.png)

Here is the heap of second solution:

![QQ20190927-095021](https://user-images.githubusercontent.com/14870120/65736037-3cf42080-e10c-11e9-8855-86b18f95a823.png)

**Comment by ianlancetaylor** [comment] 2019-09-27 03:16
How are you measuring memory use?

**Comment by szyhf** [comment] 2019-09-27 03:56
The curve is provide by monitor-agent of `Aliyun ECS(Elastic Compute Service)`, is the memory usage of the `ECS`. 

The ECS only run the `app-server` on docker , and I've use [htop](https://github.com/hishamhm/htop) via ssh to check the memory of the process, the memory is really high-load on the `app-server`.

---

About our usage: 

We are running a same app-server for different customers on different `ECS`, some has a lot users and some are not.

Firstly, I found the memory keep high-load on a `app-server` with lots users, and I found the memory usage going up unusual by curve, than I tried pprof for heap and found the `strings.Builder`.WriteString() keeps a lot of memory.

Cause of our `business needs`, I can't test the solution on that server, I use a much smaller server with less users to test the `first solution` and `second solution`. 

The smaller server has the some leaking too, but less users makes it much more slowly, the heap shows that the leaking is on `strings.Builder` too.

---

Thanks for help, let me know If any other information I can provide,.

**Comment by szyhf** [comment] 2019-09-28 23:15
Hi, @martisch @ianlancetaylor, here is the additional information:

I tried another code in another server:

```
sql := sb.String()
sql = strings.TrimSuffix(sql, ",")
_, err := ormer.Raw(sql, sqlParamList...).Exec()
```
Just a little different of the `second solution`, and the leak is shown again.

Here is the heap:

![QQ20190929-071127](https://user-images.githubusercontent.com/14870120/65823408-633ecb00-e288-11e9-8345-5298603c48f6.png)

And here is the heap for `second solution` running till now ( no leaking and stable):

![QQ20190929-071422](https://user-images.githubusercontent.com/14870120/65823431-caf51600-e288-11e9-8246-570ba474e719.png)

**Comment by szyhf** [comment] 2019-09-29 11:13
Really sorry that I made a mistake that set `sb = nil` of the `second solution` case the server panic and auto-restart, that case the memory stable and not sure to solve problem, I'm running the fix server and waiting for new heap ……

**Comment by szyhf** [comment] 2019-10-08 02:30
Just reset `strings.Builder` can not solve it.
