### ISSUE TITLE
access: approvers access for FreeBSD related changes

### ISSUE THREAD

**Issue by dmgk** [golang/go#55008] opened 2022-09-11 20:13 UTC
Hi,

I'd like to request an `approvers` access for FreeBSD related CLs on Gerrit, https://go-review.googlesource.com/#/admin/groups/1005,members. My Gerrit email is `dgoutnik@gmail.com`, I'm one of the @golang/freebsd port maintainers.

cc @golang/release

Thanks!

**Comment by mengzhuo** [comment] 2022-09-12 02:54
cc @golang/release

**Comment by paulzhol** [comment] 2022-10-13 19:08
Polite ping.. @dmgk is the FreeBSD Ports [maintainer](https://docs.freebsd.org/en/articles/contributors/#staff-committers
) for [Go](https://wiki.freebsd.org/DmitriGoutnik).
Is the `NeedsDecision` label attached still makes sense? Or somehow blocking this?

**Comment by cagedmantis** [comment] 2022-10-13 19:12
@paulzhol I will be resolving this issue shortly. The issue is not currently blocked.

**Comment by cagedmantis** [comment] 2022-10-13 19:32
Hi Dmitri,

Thank you for contributing to the Go project and helping out so much with the FreeBSD ports. I've discussed this request with the team (/cc @golang/release), and we agreed to grant you access. You are in the may-start-trybots and approvers groups now.

Please be familiar with the rules for voting and submitting changes as described at https://golang.org/wiki/GerritAccess#approver-access-approvers. If you're unsure or have any questions, please don't hesitate to ask us.

Additionally, as described at https://golang.org/wiki/GerritAccess#trybot-access-may-start-trybots, please be sure to at least skim CLs before starting a trybot run.

Thank you again for contributing, your help is greatly appreciated!

**Closed by cagedmantis** 2022-10-13 19:32 UTC
Labels: NeedsDecision

**Comment by dmgk** [comment] 2022-10-13 19:36
Thanks!
