### ISSUE TITLE
x/vgo: import "github.com/Azure/azure-sdk-for-go": module source tree too big

### ISSUE THREAD

**Issue by davidwalter0** [golang/go#25470] opened 2018-05-20 17:32 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version
go version go1.10.2 linux/amd64
```
### Does this issue reproduce with the latest release?
```
Yes
```

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/david/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build297679675=/tmp/go-build -gno-record-gcc-switches"
```
### What did you do?
```
vgo get github.com/Azure/azure-sdk-for-go@v16.2.0
```
If possible, provide a recipe for reproducing the error.
```
vgo get github.com/Azure/azure-sdk-for-go@v16.2.0
vgo: downloading github.com/Azure/azure-sdk-for-go v0.0.0-20180503200013-52423c14f13e
vgo: import "github.com/Azure/azure-sdk-for-go": module source tree too big
```

A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
``` 
vgo: resolving import "github.com/Azure/azure-sdk-for-go"
vgo: finding github.com/Azure/azure-sdk-for-go 
vgo: adding github.com/Azure/azure-sdk-for-go
```
### What did you see instead?
```
vgo get github.com/Azure/azure-sdk-for-go@v16.2.0
vgo: downloading github.com/Azure/azure-sdk-for-go v0.0.0-20180503200013-52423c14f13e
vgo: import "github.com/Azure/azure-sdk-for-go": module source tree too big
```

**Comment by kardianos** [comment] 2018-05-20 18:46
This looks like a duplicate (or perhaps a variant) of #25424 .

**Comment by kardianos** [comment] 2018-05-20 20:56
The total files in the azure sdk is > 100MiB , mostly in the services directory. Some of this size appears to be caused by versioning service APIs by date, so probably a lot of duplicate code.

The question this raises is: should there be a max module size? If so, what should this max size be? Can it be overridden (say from an env var)?

**Comment by ncw** [comment] 2018-05-31 10:31
Is there a workaround for this?  Unfortunately I've hit this brick wall in my first vgo adventure (with rclone)!

**Comment by kardianos** [comment] 2018-05-31 12:50
Right now I think the work around is to go get vgo, then adjust the 100 MiB limit to be higher. 

@rsc What do you think should be done here? The options I see are to:

 * Make the limit higher and require packages to fall within it.
 * Keep the limit as-is, require the packages to pull down external resources or in Azure's case, actually version their API calls into separate modules.
 * Allow this limit to be set based on amount of RAM available.
 * Allow this limit to be overridden by an environment variable or similar.

**Comment by oiooj** [comment] 2018-06-06 02:11
Fixed by rsc.

**Closed by oiooj** 2018-06-06 02:11 UTC

**Comment by ncw** [comment] 2018-06-06 08:47
@oiooj do we have a commit or a CL so we can examine the fix?

**Comment by oiooj** [comment] 2018-06-06 09:05
@ncw , The change is  [CL 116355](https://go-review.googlesource.com/c/vgo/+/116355).
