### ISSUE TITLE
net/http: Incorrect comment for MethodPatch in method.go

### ISSUE THREAD

**Issue by mqy** [golang/go#15727] opened 2016-05-18 08:24 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go 1.6.2

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOOS="darwin"

3. What did you do?

N/A

4. What did you expect to see?

incorrect comment for MethodPatch in net/http/method.go: "// RFC **5741**" should be "// RFC **5789**".
see [rfc5789](http://tools.ietf.org/html/rfc5789)

5. What did you see instead?

N/A

**Comment by mikioh** [comment] 2016-05-18 08:27
This is a duplicate of #15546.

**Closed by mikioh** 2016-05-18 08:27 UTC
