### ISSUE TITLE
Go2 proposal: Assign pointer of a value without "home variable"

### ISSUE THREAD

**Issue by Thor-x86** [golang/go#42690] opened 2020-11-18 05:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/athaariq/.cache/go-build"
GOENV="/home/athaariq/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/athaariq/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/athaariq/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build269520216=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I wrote [a golang library](https://github.com/Thor-x86/nullable#readme) that allows nil or not-nil state, which is very useful for JSON and SQL.

### What did you expect to see?

It should be written like this:

```go
myNullableString := nullable.NewString(&"Hello Gophers!")
```

### What did you see instead?

However, the compiler throws an error. People at community say that it is impossible to do such thing because every value must have "home variable". This is the workaround:

```go
myString := "Hello Gophers!"
myNullableString := nullable.NewString(&myString)
```

The problem is compactness of source code. I felt like coding in C++ rather than Go.

Using SQL's scan method is actually possible, but there is no pre-compile error in case of wrong assignment, which is dangerous.

If there is no solution for allowing both nil and not-nil value with homogenous type, please consider to mark this issue as proposal. Thank you!

**Comment by randall77** [comment] 2020-11-18 06:01
Duplicate of #9097.

**Closed by randall77** 2020-11-18 06:01 UTC
