### ISSUE TITLE
why go init func not run

### ISSUE THREAD

**Issue by viphxin** [golang/go#20700] opened 2017-06-16 10:16 UTC
my project is use go1.5. and everything is ok, when i ran it in go1.8.1 and i found there is a module init func not run. and I want to kown what situations can display that。。waiting for you reply and thanks

Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

**Comment by viphxin** [comment] 2017-06-16 10:17
OS is macos sierra

**Comment by ALTree** [comment] 2017-06-16 10:35
Hi,

the Go project does not use its bug tracker for general discussion or asking questions. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Also please post your code when you ask for help in one of those places, it'll help people understanding what's the problem. It's really hard to help without having the code you're running.

Closing, since this is not a bug.

**Closed by ALTree** 2017-06-16 10:35 UTC
