### ISSUE TITLE
internal/bytealg: SIGILL on s390x

### ISSUE THREAD

**Issue by richatbawag** [golang/go#41552] opened 2020-09-22 12:57 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.2 linux/s390x
</pre>

### Does this issue reproduce with the latest release?

Yes (currently this is the latest release)

### What operating system and processor architecture are you using (`go env`)?

Linux Ubuntu 18.04.5 LTS, s390x

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go version go1.15.2 linux/s390x
GO111MODULE=""
GOARCH="s390x"
GOBIN=""
GOCACHE="/home/P004995/.cache/go-build"
GOENV="/home/P004995/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="s390x"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/P004995/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/P004995/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/P004995/repos/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/P004995/repos/go/pkg/tool/linux_s390x"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -march=z196 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build060162936=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
cd src
./all.bash
</pre>
[go_1.15.2_build_form_source_tests_fail_s390x.txt](https://github.com/golang/go/files/5261524/go_1.15.2_build_form_source_tests_fail_s390x.txt)

### What did you expect to see?

<pre>
ALL TESTS PASSED
exit status 0
</pre>

### What did you see instead?

<pre>
FAIL
go tool dist: Failed: exit status 1
</pre>

**Comment by ianlancetaylor** [comment] 2020-09-22 17:55
CC @mundaym

**Comment by mundaym** [comment] 2020-09-22 18:23
Thanks for the bug report @richatbawag. A few requests:

1. Can you post the output of the command `cat /proc/cpuinfo`?
2. Is this a real machine or a qemu emulated machine?
3. Can you try again with the following environment variable set: `GODEBUG="cpu.vx=off,cpu.vxe=off"`?

The illegal instruction is pointing at an LGR instruction, but that is very unlikely to be accurate. Most likely the error is coming from the instruction before, a VLL instruction. We should only be trying to execute that if the vector facility is installed, but maybe the logic is slightly wrong.

**Comment by richatbawag** [comment] 2020-09-23 08:41
> 1. Can you post the output of the command `cat /proc/cpuinfo`?

<pre>
vendor_id       : IBM/S390
# processors    : 2
bogomips per cpu: 24038.00
max thread id   : 0
features	: esan3 zarch stfle msa ldisp eimm dfp etf3eh highgprs sie 
facilities      : 0 1 2 3 4 6 7 10 12 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 30 31 32 33 34 35 36 37 40 41 42 43 44 45 46 47 48 49 50 51 52 53 55 57 74 75 76 77 80 81 82 128 168
cache0          : level=1 type=Data scope=Private size=128K line_size=256 associativity=8
cache1          : level=1 type=Instruction scope=Private size=128K line_size=256 associativity=8
cache2          : level=2 type=Data scope=Private size=4096K line_size=256 associativity=8
cache3          : level=2 type=Instruction scope=Private size=4096K line_size=256 associativity=8
cache4          : level=3 type=Unified scope=Shared size=262144K line_size=256 associativity=32
cache5          : level=4 type=Unified scope=Shared size=983040K line_size=256 associativity=60
processor 0: version = FF,  identification = 0008F8,  machine = 2964
processor 1: version = FF,  identification = 0008F8,  machine = 2964

cpu number      : 0
cpu MHz dynamic : 5200
cpu MHz static  : 5200

cpu number      : 1
cpu MHz dynamic : 5200
cpu MHz static  : 5200
</pre>

> 2. Is this a real machine or a qemu emulated machine?

A real machine, no qemu

> 3. Can you try again with the following environment variable set: `GODEBUG="cpu.vx=off,cpu.vxe=off"`?

Fails again.
[go_1.15.2_build_form_source_tests_fail_s390x_cpuvxoff.txt](https://github.com/golang/go/files/5266739/go_1.15.2_build_form_source_tests_fail_s390x_cpuvxoff.txt)

go1.14.9 works
go1.15 fails too

**Comment by mundaym** [comment] 2020-09-23 09:58
Thanks for the information. Looks like you are running a z13 with the vector facility disabled. 

I think I know what the issue is. [CL 156998](https://golang.org/cl/156998) added calls to `bytealg.IndexString` that do not first check that the input string is shorter than `bytealg.MaxLen` (as required by the documentation for `bytealg.IndexString`. `bytealg.MaxLen` is 0 on s390x when the vector facility is unavailable and so `bytealg.IndexString` should not be called. Technically the generic implementation that was added in that CL should not be called either since generic platforms never set `MaxLen` to something other than 0.

Requiring callers to check `MaxLen` is probably asking for trouble. We might want to scrap it as part of the fix for this. I'll take a look and see if I can come up with a robust patch.

/cc @ianlancetaylor @randall77

**Closed** 2020-09-23 19:56 UTC
Labels: NeedsInvestigation, arch-s390x

**Comment by mundaym** [comment] 2020-09-23 19:59
@gopherbot Please create backport issue for Go 1.15. This bug means that `bytes.IndexAny` and `bytes.LastIndexAny` cause an illegal instruction exception on s390x machines without the vector facility. There is no workaround.
