### ISSUE TITLE
runtime: "out of memory" in heapsampling.go on 386 and wasm since 2021-11-05

### ISSUE THREAD

**Issue by bcmills** [golang/go#49564] opened 2021-11-12 20:44 UTC
`greplogs --dashboard -md -l -e FAIL\\s+heapsampling\\.go --since=2021-01-01`

[2021-11-12T18:57:22-b1b6d92/windows-386-2008](https://build.golang.org/log/b0ed35dd53e6d30333eaa6f3cb45e9555be60956)
[2021-11-12T16:58:34-95d0657/windows-386-2008](https://build.golang.org/log/a09adbd92d478c19da5ca0768efa5de3d916c92e)
[2021-11-05T20:59:43-dbd3cf8/windows-386-2008](https://build.golang.org/log/9d822efb197fea171c8bb3768fe4fdb7a06bc744)
[2021-11-05T18:20:07-53bab19/windows-386-2008](https://build.golang.org/log/eeb12d86ef477785e9e0f4bcf8ae40dc7435edca)
[2021-11-05T17:46:59-e48e4b4/windows-386-2008](https://build.golang.org/log/82e30e04b7552b07e6ed5862b63bb0231ab3f3c1)
[2021-11-05T15:52:40-a0d661a/windows-386-2008](https://build.golang.org/log/036e7d85b6fba44e10a5457cf1e5264ebde53fae)

(CC @bufflig)

**Comment by aclements** [comment] 2021-12-01 21:00
We haven't seen any more of these failures.

Our working hypothesis is that these were related to the new pacer. That landed 2021-11-04. In all of these failures, the heap is around 1.7 GB when it fails, which is way bigger than we'd expect from this test. Based on printing MemStats.Sys at the end of this test, the largest memory footprint I've seen on my linux/amd64 laptop is 120 MB.

**Comment by mknyszek** [comment] 2021-12-01 23:16
I want to amend @aclements' a little bit just to say that we've seen these large memory footprints (I think around 113 MiB?) with the old pacer too (`GOEXPERIMENT=nopacerredesign`). It's still possible this uptick was somehow related to the new pacer, but it's less likely to be solely related to that, I think.

**Comment by toothrot** [comment] 2021-12-08 17:23
Checking on this as a release blocker. Is this still occurring @bufflig?

**Comment by bcmills** [comment] 2021-12-08 17:26
Still no more failures in the logs. Maybe this was a bad interaction with some other `runtime` test that has since been fixed?

`greplogs --dashboard -md -l -e FAIL\\s+heapsampling\\.go --since=2021-11-13`

**Comment by cherrymui** [comment] 2021-12-15 18:39
Seems still no new failure since 2021-11-12.

**Comment by aclements** [comment] 2021-12-15 18:48
It's unfortunate that we don't know what caused this, but at this point I think we can close this issue. We'll reopen it if the issue returns.

**Comment by bcmills** [comment] 2022-02-16 14:12
> We'll reopen it if the issue returns.

`greplogs --dashboard -md -l -e FAIL\\s+heapsampling\\.go --since=2021-12-15`

[2022-02-15T21:18:59-08ed488/windows-386-2008](https://build.golang.org/log/4ac048061eb4228bbad5940bf66a15ccbe395405)

Given the timing (and the relative rarity since the last failure), retargeting to Go 1.19.

**Comment by bcmills** [comment] 2022-03-02 21:33
Another one this week:

`greplogs --dashboard -md -l -e FAIL\\s+heapsampling\\.go --since=2022-02-16`

[2022-03-02T20:02:12-fc5b64e/windows-386-2012](https://build.golang.org/log/967c19342c5ecebac154c36582bc84187661a4c2)

**Comment by bcmills** [comment] 2022-04-18 14:47
@golang/runtime, this release-blocking issue needs an owner now that it is no longer assigned to Jeremy.

(This is a recurring test regression on a [first class port](https://go.dev/wiki/PortingPolicy#first-class-ports).)

**Comment by mknyszek** [comment] 2022-04-18 16:16
I've been investigating heap overrun issues in a test I wrote for #48409 that appear to be similar to #37331.

So far, I've discovered that any test that allocates in a loop can somewhat easily overrun the heap in an unbounded manner due to an OS scheduler preemption (even on undersubscribed systems) during mark termination. I believe I have sufficient evidence to narrow it down to an OS scheduler preemption at this point, too. I've been trying to obtain a scheduler trace and prove it for certain. It reproduces more readily on VMs, but those traces seem to be busted. I can reproduce on a dedicated machine as well, but not while tracing is active. (I ran it continuously over the weekend trying to obtain a trace -- no dice... on Linux, anyway.)

This bug frankly looks a lot like those cases, and is consistent with previous behavior I've observed when investigating this bug (with smaller spikes).

**Comment by mknyszek** [comment] 2022-04-18 16:23
FWIW, the best mitigation I have come up with now is to slow down how fast the program is allocating by inserting `Gosched` calls and writing to the allocated memory. I could apply this mitigation to `heapsampling.go` but it means a slower test. I could also reduce the number of iterations it does as well to try to make up for that.

**Comment by prattmic** [comment] 2022-04-18 17:26
Would it be OK to reduce the size of allocations in that test (maybe just on 32-bit systems)?

Based on my back-of-the-envelope calculation, each `allocInterleaved` call in [testInterleavedAllocations](https://cs.opensource.google/go/go/+/master:test/heapsampling.go;l=47;drc=2dd066d4a7ab6eb7828cbba8cb29158dcaedcc78) allocates ~1GB. Only ~50KB is live at a time, but it seems like a slow GC has a pretty good chance of blowing the address space limit.

**Comment by alexbrainman** [comment] 2022-04-18 20:59
@mknyszek 

> It reproduces more readily on VMs, but those traces seem to be busted. I can reproduce on a dedicated machine as well, but not while tracing is active.

There is new code that allows you to create Windows dumps when you `set GOTRACEBACK=crash` - see [CL 307372](https://go-review.googlesource.com/c/go/+/307372/) commit message for how to use new feature. Maybe you could use `delve` or `windbg` to see the state of crashed test process.

Alex

**Comment by bcmills** [comment] 2022-05-09 17:16
`greplogs -l -e FAIL\\s+heapsampling\\.go --since=2022-03-03`
[2022-05-06T17:41:30-091e913/windows-386-2008](https://build.golang.org/log/d655bcf6d51b48b82f76192c773528f3f5d4638d)
[2022-05-05T18:48:01-53647a1/windows-386-2008](https://build.golang.org/log/ba4f6b4346c26bdceb88de2dc13fcadbf0c475e9)
[2022-04-22T22:38:00-7c68097/windows-386-2008](https://build.golang.org/log/25b8669c0fc65630fae694131f8879015eef302c)
[2022-04-14T22:52:29-cc43e19/windows-386-2008](https://build.golang.org/log/b19f5bad38381e1cc5e2ae4056305e558a423576)
[2022-04-04T19:04:21-d17c573/windows-386-2008](https://build.golang.org/log/493c415edd4adb69564165b0850cd4d39cba03ad)
[2022-03-31T19:13:25-c5c66d7/windows-386-2008](https://build.golang.org/log/91c5ab987e036350f9be0ea5b4a39ed03be8e883)
[2022-03-28T16:44:09-a208aa7/windows-386-2008](https://build.golang.org/log/128c897fa862dcee98bbfe18a2eacbb7c1c772b2)
[2022-03-17T08:43:51-c379c3d/windows-386-2008](https://build.golang.org/log/c571b878814c17dcd5c8bef91f7e21d82a77c7f4)
[2022-03-14T09:19:01-ab0f761/windows-386-2008](https://build.golang.org/log/5f0e52f17654a95a4050b5fda38ab0bf1b6edc64)

**Comment by bcmills** [comment] 2022-05-11 15:37
Curiously, also on `js-wasm` of all places‽ 🤯 

`greplogs -l -e FAIL\\s+heapsampling\\.go --since=2022-05-06`
[2022-05-10T20:52:34-e0f9977/js-wasm](https://build.golang.org/log/df5ca56442e80cc03381ac12138fe8de3aa3f487)
[2022-05-06T17:41:30-091e913/windows-386-2008](https://build.golang.org/log/d655bcf6d51b48b82f76192c773528f3f5d4638d)

**Comment by bcmills** [comment] 2022-05-12 12:42
A different `386` platform this time!

`greplogs -l -e FAIL\\s+heapsampling\\.go --since=2022-05-11`
[2022-05-11T23:39:27-ec5bdef/freebsd-386-12_3](https://build.golang.org/log/8a5c1c609efbe21a44c63a842a3f40abcfa32cf8)

**Comment by mknyszek** [comment] 2022-05-23 18:49
Looking back over this, I think the only thing to do here is to slow down the allocation rate of this test. If it remains an issue after that, we should consider just skipping the test on some platforms. I hope (🤞 ) that the js/wasm issues are resolved by the fixes to the GC CPU limiter.

**Closed** 2022-05-27 21:36 UTC
Labels: NeedsInvestigation, release-blocker, arch-wasm, okay-after-beta1, arch-386
