### ISSUE TITLE
nacl: use get_random_bytes syscall instead of SRPC

### ISSUE THREAD

**Issue by jamesr** [golang/go#9870] opened 2015-02-13 22:40 UTC
Native Client has a get_random_bytes syscall supported since pepper_39 that can be used to generate random bytes:

https://code.google.com/p/chromium/codesearch#chromium/src/native_client/src/trusted/service_runtime/include/bits/nacl_syscalls.h&sq=package:chromium&type=cs&l=128&rcl=1423805234

The nacl IRT calls it thusly:

https://code.google.com/p/chromium/codesearch#chromium/src/native_client/src/untrusted/irt/irt_random.c&sq=package:chromium&type=cs&q=get_random_bytes&l=20

If we're OK with depending on this (which means running on sel_ldrs from pepper_39 or newer) then we can call this directly instead of going through SRPC to look up the SecureRandom service.  It appears that this is the only use of srpc in go, so we could additionally remove the SRPC support entirely as newer nacl features are not exported in this manner.

**Comment by davecheney** [comment] 2015-02-13 22:47
I think this is a good idea. I'm almost certain that the nacl/arm builder
needs pepper_39 at least, so this isn't a big imposition.

**Comment by jamesr** [comment] 2015-02-13 23:00
Great! Do you know if the other builders require something that new?

**Comment by davecheney** [comment] 2015-02-13 23:08
I had a quick look at the scripts which generate the base vm image for the
linux-nacl-{386,amd64} builders but it wasn't clear

https://github.com/golang/build/blob/master/env/linux-x86-nacl/scripts/build-go-builder.sh

@bradfiz which pepper version were those components taken from ?

As for the nacl/arm build, that runs on a dev board on my desk, I can
adjust it as necessary.

**Comment by jamesr** [comment] 2015-02-13 23:09
I wrote a patch: https://go-review.googlesource.com/#/c/4860/ but gerrit gold me somebody already did this: https://go-review.googlesource.com/#/c/1755/1 (probably better)

**Comment by jamesr** [comment] 2015-02-13 23:10
And this issue is a dupe of issue 9261 (which I didn't find since it doesn't have the os-nativeclient label).

**Comment by minux** [comment] 2015-02-13 23:43
Yes, it's a dupe of #9261.

**Closed by minux** 2015-02-13 23:43 UTC
