### ISSUE TITLE
liblink: incompatible type signatures for utfrune

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9698] opened 2015-01-27 01:46 UTC
On the dev.cc branch, the plan9-386-gcepartial builder is broken with:

```
qtoken: incompatible type signatures 9b47f185(/tmp/buildlet-scatch427100321/go/pkg/obj/plan9_386/lib9.a(utfrune)) and c54741c6(/386/lib/libc.a(tokenize)) for utfrune
go tool dist: FAILED: 8l -o /tmp/buildlet-scatch427100321/go/pkg/tool/plan9_386/8a /tmp/go-tool-dist-168419734/lex.8 /tmp/go-tool-dist-168419734/y.tab.8 /tmp/buildlet-scatch427100321/go/pkg/obj/plan9_386/liblink.a /tmp/buildlet-scatch427100321/go/pkg/obj/plan9_386/libbio.a /tmp/buildlet-scatch427100321/go/pkg/obj/plan9_386/lib9.a
```

**Comment by 0intro** [comment] 2015-01-27 06:45
There was a similar issue on the master branch, after CL 2994:

```
cmd/8l
qtoken: incompatible type signatures 9b47f185(/tmp/gobuilder/plan9-386-ducolombier-34bc85f6f3b0/go/pkg/obj/plan9_386/lib9.a(utfrune)) and c54741c6(/386/lib/libc.a(tokenize)) for utfrune

go tool dist: FAILED: 8l -o /tmp/gobuilder/plan9-386-ducolombier-34bc85f6f3b0/go/pkg/tool/plan9_386/8l /tmp/go-tool-dist-254852261/data.8 /tmp/go-tool-dist-254852261/decodesym.8 /tmp/go-tool-dist-254852261/dwarf.8 /tmp/go-tool-dist-254852261/elf.8 /tmp/go-tool-dist-254852261/go.8 /tmp/go-tool-dist-254852261/ldelf.8 /tmp/go-tool-dist-254852261/ldmacho.8 /tmp/go-tool-dist-254852261/ldpe.8 /tmp/go-tool-dist-254852261/lib.8 /tmp/go-tool-dist-254852261/macho.8 /tmp/go-tool-dist-254852261/pcln.8 /tmp/go-tool-dist-254852261/pe.8 /tmp/go-tool-dist-254852261/pobj.8 /tmp/go-tool-dist-254852261/symtab.8 /tmp/go-tool-dist-254852261/asm.8 /tmp/go-tool-dist-254852261/list.8 /tmp/go-tool-dist-254852261/obj.8 /tmp/gobuilder/plan9-386-ducolombier-34bc85f6f3b0/go/pkg/obj/plan9_386/liblink.a /tmp/gobuilder/plan9-386-ducolombier-34bc85f6f3b0/go/pkg/obj/plan9_386/libbio.a /tmp/gobuilder/plan9-386-ducolombier-34bc85f6f3b0/go/pkg/obj/plan9_386/lib9.a
```

This issue was fixed by enabling tokenize in the lib9 (CL 3330),
so the liblink used both getfields and tokenize from the lib9,
which depend on the same utfrune definition.

However, here, enabling tokenize in lib9 doesn't fix the issue.
The linker is still erroneously grabbing tokenize from the Plan 9 libc.

**Comment by 0intro** [comment] 2015-01-27 07:05
So far, this is the only failure on the dev.cc branch. I can confirm
it by disabling the signature checking (-T option) in the compiler.

Also, after enabling tokenize in lib9, the same failure happens
on 8a instead of 8l (the next tool to be built).

```
cmd/8a
qtoken: incompatible type signatures 9b47f185(/usr/go/pkg/obj/plan9_386/lib9.a(utfrune)) and c54741c6(/386/lib/libc.a(tokenize)) for utfrune
go tool dist: FAILED: 8l -o /usr/go/pkg/tool/plan9_386/8a /tmp/go-tool-dist-832569276/lex.8 /tmp/go-tool-dist-832569276/y.tab.8 /usr/go/pkg/obj/plan9_386/liblink.a /usr/go/pkg/obj/plan9_386/libbio.a /usr/go/pkg/obj/plan9_386/lib9.a
```

**Comment by 0intro** [comment] 2015-02-23 22:04
This issue is fixed in [CL 5652](https://go-review.googlesource.com/#/c/5652), since the C tools aren't build anymore.

**Closed by 0intro** 2015-02-23 22:04 UTC
