### ISSUE TITLE
go modules:the pkg uses two different module paths 

### ISSUE THREAD

**Issue by Smityz** [golang/go#32462] opened 2019-06-06 13:06 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/data/home/***/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/data/home/***/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data/home/***/***/***/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build015182643=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

go.mod:
replace (
        bou.ke/monkey => github.com/bouk/monkey v1.0.0
        go.uber.org/multierr => github.com/uber-go/multierr v1.1.0
        go.uber.org/zap => github.com/uber-go/zap v1.9.1
        golang.org/x/crypto => github.com/golang/crypto v0.0.0-20190422183909-d864b10871cd
        golang.org/x/lint => github.com/golang/lint v0.0.0-20190409202823-959b441ac422
        golang.org/x/net => github.com/golang/net v0.0.0-20190420063019-afa5a82059c6
        golang.org/x/sync => github.com/golang/sync v0.0.0-20190423024810-112230192c58
        golang.org/x/sys => github.com/golang/sys v0.0.0-20190422165155-953cdadca894
        golang.org/x/text => github.com/golang/text v0.3.0
        golang.org/x/tools => github.com/golang/tools v0.0.0-20190422233926-fe54fb35175b
        google.golang.org/appengine => github.com/golang/appengine v1.6.0
        google.golang.org/genproto => github.com/google/go-genproto v0.0.0-20190418145605-e7d98fc518a7
        google.golang.org/grpc => github.com/grpc/grpc-go v1.20.1
        gopkg.in/alecthomas/kingpin.v2 => github.com/alecthomas/kingpin v2.2.6+incompatible
        gopkg.in/check.v1 => github.com/go-check/check v0.0.0-20180628173108-788fd7840127
        gopkg.in/fsnotify.v1 => github.com/fsnotify/fsnotify v1.4.8-0.20190312181446-1485a34d5d57
        gopkg.in/go-playground/assert.v1 => github.com/go-playground/assert v1.2.1
        gopkg.in/go-playground/validator.v8 => github.com/go-playground/validator v8.18.2+incompatible
        gopkg.in/ini.v1 => github.com/go-ini/ini v1.42.0
        gopkg.in/tomb.v1 => github.com/go-tomb/tomb v0.0.0-20141024135613-dd632973f1e7
        gopkg.in/yaml.v2 => github.com/go-yaml/yaml v0.0.0-20181115110504-51d6538a90f8
)
And then
$ vend
$ go build -mod=vendor
go: github.com/golang/appengine@v1.6.0 used for two different module paths (github.com/golang/appengine and google.golang.org/appengine)
go: github.com/go-ini/ini@v1.42.0 used for two different module paths (github.com/go-ini/ini and gopkg.in/ini.v1)

### What did you expect to see?
compile success

### What did you see instead?
compile failed

**Comment by bcmills** [comment] 2019-06-06 14:01
Duplicate of #26904

**Closed by bcmills** 2019-06-06 14:01 UTC
