### ISSUE TITLE
gofmt: inconsistent formatting of string concat 

### ISSUE THREAD

**Issue by exi** [golang/go#12917] opened 2015-10-13 09:20 UTC
Hi, i'm running gofmt on every save and observed something odd after running it on my code:

```go
package test

func F1(s string, path string, config Config) string {
        r2 := regexp.MustCompile("http://(asset-[^.].)" + replaceString)
        return s
}

func F2(s string, path string, config Config) string {
        r := regexp.MustCompile("https?://([^ '\"]*)bla.foo")
        s = r.ReplaceAllString(s, "http://${1}"+replaceString)
        return s
}
```

Why is there a space around "+" in the first func and no space around "+" in the second?

**Comment by dominikh** [comment] 2015-10-13 09:39
Duplicate of the duplicates of #12720

**Comment by ianlancetaylor** [comment] 2015-10-13 13:44
We use the issue tracker for bug reports and tracking.  Please ask questions on the golang-nuts mailing list or on http://forum.golangbridge.org.  Thanks.

**Closed by ianlancetaylor** 2015-10-13 13:44 UTC
