### ISSUE TITLE
cmd/compile: "F is not a generic type" when F is a recursive generic interface

### ISSUE THREAD

**Issue by 4ad** [golang/go#47836] opened 2021-08-20 12:32 UTC
On tip (e9e0d1ef70) with `-gcflags=-G=3`

Repro:
```
package p

type F[t F[t]] interface {}
```

Compiler rejects it with:

```
go build -gcflags=-G=3 j.go
# command-line-arguments
./j.go:3:10: F is not a generic type
```

However, it accepts this:

```
package p

type F[t F] interface {}
```

But that has other problems, see #47837.

**Comment by mknyszek** [comment] 2021-08-20 13:33
CC @ianlancetaylor @griesemer

**Comment by tdakkota** [comment] 2021-08-20 13:33
Seems like duplicate of https://github.com/golang/go/issues/47796

**Comment by 4ad** [comment] 2021-08-20 13:34
Yep, seems like a dupe. In fact, I was trying to write that exact `Eq` when I found this.

**Comment by mknyszek** [comment] 2021-08-20 13:39
Closing as duplicate of #47796.

**Closed by mknyszek** 2021-08-20 13:39 UTC
Labels: NeedsInvestigation
