### ISSUE TITLE
encoding/json: unmarshal malformed json doesn't produce an error

### ISSUE THREAD

**Issue by 4xoc** [golang/go#16899] opened 2016-08-27 08:27 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.7

2. What operating system and processor architecture are you using (`go env`)?
linux/amd64 (Arch Linux)
kernel: 4.7.1-1-ARCH

3. What did you do?
Simply reading a file containing JSON data where in one string a backslash '\' is present. At this point it is not meant to escape anything but simply represents malformed JSON. Below an example of what I've done.

foo.json `{"foo":"b\ar"}`

```
func LoadConfig() int {
  config struct {
    Foo string
  }
  
  file, err := os.Open("foo.json")
  if err != nil {
  	return 1
  }

  decoder := json.NewDecoder(file)
  err = decoder.Decode(config)
  if err != nil {
  	return 2
  }
  
  return 0
}
```

4. What did you expect to see?
Unmarshal returning a non-nil error describing malformed JSON.

5. What did you see instead?
No value of the target struct is set by unmarshal.

From my understanding this should produce an error as not just a single field wasn't read but the whole file.

**Comment by odeke-em** [comment] 2016-08-27 13:03
Hello there @4xoc.

For starters I've fixed up a bit of your example to make it a runnable go program but it correctly reports that we have an invalid character 'a' in string
<img width="669" alt="screen shot 2016-08-27 at 5 58 18 am" src="https://cloud.githubusercontent.com/assets/4898263/18027535/5db78410-6c1b-11e6-9cd4-ec4e0e9871b9.png">

I see in your code
```go
if err != nil {
    return 2
  }
```

Perhaps you aren't catching that status code of 2 in whichever caller is invoking LoadConfig()?

And, yes if it encounters an error it won't set the properties, so please check your errors/status codes.


To test it out without having to make a file; just to make the code sample easily reproducible on the playground at https://play.golang.org/p/W91r6xm-t9 or inlined. As you'll see, we can successfully catch and print the error

```go
package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

func main() {
	fmt.Println(LoadConfig())
}

func LoadConfig() error {
	type config struct {
		Foo string
	}

	r := strings.NewReader(`{"foo":"b\ar"}`)
	decoder := json.NewDecoder(r)
	cf := new(config)
	if err := decoder.Decode(cf); err != nil {
		return err
	}

	return nil
}
```

I am marking this as not a bug. If you think otherwise, please let me know.

**Closed** 2016-08-27 13:04 UTC

**Comment by 4xoc** [comment] 2016-08-27 13:11
Thanks @odeke-em, I found a problem in my code connected to the `return 2` you pointed out and that was indeed the problem.
