### ISSUE TITLE
proxy.golang.org: new tag not abatable after 2 hours

### ISSUE THREAD

**Issue by emil110778** [golang/go#57193] opened 2022-12-09 10:46 UTC
Hi, I tray to update version of my module, bug I have a problem
I push tag with new version, but 2 hours ago a recive:
```
go: downloading github.com/binance-converter/backend-api v0.0.9
go: github.com/binance-converter/backend-api@v0.0.9: verifying module: github.com/binance-converter/backend-api@v0.0.9: reading https://sum.golang.org/lookup/github.com/binance-converter/backend-api@v0.0.9: 404 Not Found
        server response: not found: fetch timed out
```

Previous releases is avalable

**Comment by apptut** [comment] 2022-12-09 10:49
I have the same problem today

**Comment by seankhliao** [comment] 2022-12-09 10:53
Duplicate of #57185

**Closed by seankhliao** 2022-12-09 10:53 UTC
Labels: proxy.golang.org
