### ISSUE TITLE
x/build/cmd/release: official windows installer not working with version 1.15

### ISSUE THREAD

**Issue by terryjiang2020** [golang/go#40967] opened 2020-08-21 21:43 UTC
### What version of Go are you using (`go version`)?

1.15
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

WIndows 10 64 bit

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

Download link: https://golang.org/dl/

I downloaded the installer named 'go1.15.windows-amd64' from the official website and tried to install it by simply double click it.

### What did you expect to see?

An installer with a guide to help me install it. 

### What did you see instead?

It shows 'Prepare to install' for about half a second then the window disappears, and the Windows told me it is still running somewhere when I thought the installation is failed and tried to delete the installer. After several hours or minutes, another window pop up telling me the installation is not responding and ask me whether I want to cancel or retry. Either way, that window will disappear again without notifying me of what is happening. 

Tried redownloading but it's still the same. 1.14.7 also has the same issue on my machine.

**Comment by cagedmantis** [comment] 2020-08-25 21:26
@terryjiang2020 We have been unable to reproduce this issue. Do you have another Windows 10 64 bit machine you can test the installer on? Can you try @alexrousg suggestion and download the zip file and expand it?

**Comment by terryjiang2020** [comment] 2020-08-25 22:06
Hi there, strangely, today I simply double clicked it again and it works perfectly without I making any change to the system (including disabling anti-virus or anything else).

**Comment by terryjiang2020** [comment] 2020-08-25 22:07
The same go1.15.windows-amd64.msi file btw, I didn't even re-download it. It simply works.

**Comment by davecheney** [comment] 2020-08-25 23:23
Thanks for confirming. I'm going to close this issue for the moment. Please comment if this reoccurs.

_note_: if you are having difficulties installing a version of Go other than 1.15 in the month of august, please open a new issue as the version of Go and or windows will have changed in the interim.

**Closed by davecheney** 2020-08-25 23:23 UTC
Labels: Builders, WaitingForInfo
