### ISSUE TITLE
No debug information when only the initializer of a custom type is used

### ISSUE THREAD

**Issue by hideoutcute** [golang/go#49305] opened 2021-11-02 22:13 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.16.8
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
darwin/amd64
</pre></details>

### What did you do?
```
package main

import "fmt"

type myString string

func myFunc(val interface{}) {
	fmt.Println(val) // breakpoint here and inspect val
}

func main() {
	myFunc(myString("myString string"))
}
```

### What did you expect to see?
Able to see the value of the local variable 'val' at the break point

### What did you see instead?

```
(unreadable interface type "main.myString" not found for 0xc00007df70: no type entry found, use 'types' for a list of valid types)
```

BUT if the initializer assigns the value to an variable first and then pass to the function then everything works normal.
```
func myFunc(val interface{}) {
	fmt.Println(val) // breakpoint here and inspect val
}

func main() {
	val := myString("myString string") // assign it to an variable first
	myFunc(val)
}
```

**Comment by randall77** [comment] 2021-11-02 22:19
What debugger are you using?
Are you compiling with optimizations off (-N -l)?
Can you show us the exact commands that lead to that error message?

**Comment by aarzilli** [comment] 2021-11-03 10:50
This is a duplicate of https://github.com/golang/go/issues/46670

**Comment by thanm** [comment] 2021-11-03 13:50
Thanks for raising this issue.  This is indeed a duplicate of #46670.  Closing, please re-open if needed,

**Comment by thanm** [comment] 2021-11-03 13:50
Dup of #46670

**Closed by thanm** 2021-11-03 13:50 UTC
Labels: WaitingForInfo
