### ISSUE TITLE
How to use union template types

### ISSUE THREAD

**Issue by Carsten-Leue** [golang/go#49544] opened 2021-11-12 11:05 UTC
### What version of Go are you using (`go version`)?

<pre>
$ gotip version
go version devel go1.18-7bed3c7 Fri Nov 12 00:16:15 2021 +0000 windows/amd64
</pre>

I am trying to use templates to define an "option" pattern like so:

```
const NONE_TAG = "none"

type Some [T any] struct {
	tag   string
	value T
}

type None struct {
	tag   string
}

var none = None{tag: NONE_TAG}

func is_none[T Some[any] | None](val T) bool {
	return val.tag == NONE_TAG
}

```

This is failing with:

```
.\main.go:32:13: val.tag undefined (type bound for T has no method tag)
```
But `T` does have a constraint that guarantees the existence of the `tag` field. How would I achieve the desired effect?

**Comment by rogpeppe** [comment] 2021-11-12 17:43
I believe this is a duplicate of https://github.com/golang/go/issues/48522.

For your particular issue (making an `Option` type), you could do something like [this](https://gotipplay.golang.org/p/o5zg1eL39Fr):

```
type Option[T any] struct {
	x  T
	ok bool
}

func (opt Option[T]) IsNone() bool {
	return !opt.ok
}

func (opt Option[T]) IsSome(x *T) bool {
	if opt.ok {
		*x = opt.x
		return true
	}
	return false
}

func None[T any]() Option[T] {
	return Option[T]{}
}

func Some[T any](x T) Option[T] {
	return Option[T]{
		x:  x,
		ok: true,
	}
}
```

**Closed by rogpeppe** 2021-11-12 17:43 UTC
