### ISSUE TITLE
go.dev: some packages on godoc.org are not accessible on pkg.go.dev

### ISSUE THREAD

**Issue by firelizzard18** [golang/go#36931] opened 2020-01-31 16:11 UTC
In response to [Next steps for pkg.go.dev](https://blog.golang.org/pkg.go.dev-2020):
>## Redirecting godoc.org requests to pkg.go.dev
>To minimize confusion about which site to use, later this year we are planning to redirect traffic from godoc.org to the corresponding page on pkg.go.dev. We need your help to ensure that pkg.go.dev addresses all of our users needs.

Some packages that are documented on godoc.org are not accessible on pkg.go.dev. For example, `github.com/go-stomp/stomp` has documentation on [godoc.org](https://godoc.org/github.com/go-stomp/stomp) but [pkg.go.dev](https://pkg.go.dev/github.com/go-stomp/stomp?tab=overview) shows "displayed due to license restrictions."

I understand the reasoning behind pkg.go.dev's license restrictions, but as long as they are in place, godoc.org meets a need that pkg.go.dev does not.

**Comment by jba** [comment] 2020-01-31 20:37
We understand your point. But here is another way to look at it: pkg.go.dev will help drive proper licensing for the Go ecosystem.

I know you were just using go-stomp/stomp as an example, but I filed https://github.com/go-stomp/stomp/issues/71 against it anyway.

**Comment by firelizzard18** [comment] 2020-02-01 00:52
I understand the motivation, but it's not realistic to expect every useful Go package to update itself, and forking or recreating a package just to 'fix' the license is a waste of time.

**Comment by rsc** [comment] 2020-02-24 21:27
Closing as a duplicate of #36985.

**Closed by rsc** 2020-02-24 21:27 UTC
Labels: NeedsInvestigation, go.dev

**Comment by firelizzard18** [comment] 2020-02-25 00:02
This issue is not "other ways for `pkg.go.dev` to recognize a license". This issue is "please don't shutdown or permanently redirect godoc.org". The closure of #36985 in no way solves the issue of unmaintained projects with idiosyncratic licenses being inaccessible from `pkg.go.dev`.

**Comment by rsc** [comment] 2020-02-25 17:37
For what it's worth, go-stomp is not an "unmaintained project with an idiosyncratic license". It appears we were not properly recognizing the short Apache 2.0 header before, and now we are. I see that v2.0.5 has a newer license file, but v2.0.4 from a year ago is now displayed on pkg.go.dev just fine:

https://pkg.go.dev/github.com/go-stomp/stomp@v2.0.4+incompatible?tab=doc
