### ISSUE TITLE
cmd/go: build failure on amd64 Linux with an error in TestTwoGopathShlibsGccgo from CL 69831  onward

### ISSUE THREAD

**Issue by siebenmann** [golang/go#22224] opened 2017-10-12 01:31 UTC
### What version of Go are you using (`go version`)?

The latest git tip I've tested this on is `go version devel +926373ea79 Thu Oct 12 00:11:33 2017 +0000 linux/amd64`.

### What operating system and processor architecture are you using (`go env`)?

````
GOARCH="amd64"
GOOS="linux"
````

Specifically I'm on Fedora 26. Since this test appears to use gccgo, it may be relevant that my reported (system) gccgo version is `gccgo (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)`.

### What did you do?

Trying to do `./all.bash` build now fails in TestTwoGopathShlibsGccgo:

````
[....]
##### ../misc/cgo/testcshared
PASS

##### ../misc/cgo/testshared
--- FAIL: TestTwoGopathShlibsGccgo (0.68s)
        shared_test.go:371: /tmpfs/testshared953842952/pkg/gccgo_linux_amd64_5577006791947779410_fPIC/shlibs/libdep2.so is not linked to anything matching libdepBase\.so
FAIL
exit status 1
FAIL    _/tmp/go/misc/cgo/testshared    13.913s
2017/10/11 20:36:31 Failed: exit status 1

##### ../misc/cgo/testplugin
PASS
something
[...]
````

Git bisection says that this started happening at commit 4e8be99590, 'cmd/go: clean up compile vs link vs shared library actions'. I hacked in some instrumentation and it appears that libdep2.so here is only linked to libgo.so.11, libgcc_s.so.1, libc.so.6, and ld-linux-x86-64.so.2.

**Comment by ianlancetaylor** [comment] 2017-10-12 04:08
CC @rsc @mwhudson

**Comment by rsc** [comment] 2017-10-12 13:55
Sorry about this. The test is being skipped on my Linux box because "gccgo too old". I will update my Linux distribution.

**Comment by rsc** [comment] 2017-10-12 19:31
I have a new Linux and new gccgo and can reproduce the problem. Will fix, thanks.

**Comment by laboger** [comment] 2017-10-18 21:32
This is failing on ppc64le as well, as long as your machine has gccgo and it is new enough.

I can see in the verbose output that the link for libdep2.so is different than before. I don't think this test is expecting libdepBase.a to be linked in.

/usr/bin/gccgo -o $WORK/b021/libdep2.so -Wl,-( -Wl,--whole-archive /tmp/testshared785817683/pkg/gccgo_linux_ppc64le_5577006791947779410_fPIC/libdep2.a **/tmp/testshared785817683/pkg/gccgo_linux_ppc64le_5577006791947779410_fPIC/libdepBase.a** -Wl,--no-whole-archive -Wl,-) -zdefs -shared -nostdlib -lgo -lgcc_s -lgcc -lc -fPIC

On Ubuntu 16.04 with gccgo 6, there is an additional failure.

--- FAIL: TestGoPathShlibGccgo (2.83s)
	shared_test.go:371: ./bin/exe is not linked to anything matching libdepBase\.so
--- FAIL: TestTwoGopathShlibsGccgo (1.10s)
	shared_test.go:371: /tmp/testshared302107344/pkg/gccgo_linux_ppc64le_5577006791947779410_fPIC/shlibs/libdep2.so is not linked to anything matching libdepBase\.so
	shared_test.go:371: ./bin/exe2 is not linked to anything matching libdep2
	shared_test.go:371: ./bin/exe2 is not linked to anything matching libdepBase\.so
FAIL

**Comment by rsc** [comment] 2017-10-19 03:03
Sorry, my fix for this was preempted by the point release work. If you want to add a skip to the test pointing at this issue, that's fine.

**Closed** 2018-01-12 05:26 UTC
Labels: NeedsInvestigation, release-blocker
