### ISSUE TITLE
x/website: "Writing Web Applications" Link in Go documentation is broken

### ISSUE THREAD

**Issue by rajeshksv** [golang/go#44409] opened 2021-02-19 04:12 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
NA
</pre>

### Does this issue reproduce with the latest release?
NA

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
NA
</pre></details>

### What did you do?

1. Go to https://golang.org/doc
2. Click on "Writing Web Applications"
3. It redirects to "https://golang.org/doc/articles/wiki/" where it simply says 
"open REDACTED: file does not exist"

### What did you expect to see?
I expected a sample web application

### What did you see instead?
Some random error message
"open REDACTED: file does not exist"

**Comment by seankhliao** [comment] 2021-02-19 07:43
Duplicate of #44314

**Closed by seankhliao** 2021-02-19 07:43 UTC
Labels: Documentation
