### ISSUE TITLE
cmd/go: go test cannot find module path in module root directory

### ISSUE THREAD

**Issue by suzmue** [golang/go#26722] opened 2018-07-31 17:50 UTC
### What version of Go are you using (`go version`)?
go version devel +ecec63c8a1 Tue Jul 31 16:34:38 2018 +0000 darwin/amd64

###  Does this issue reproduce with the latest release?
testing with tip (issue does not reproduce in go1.11beta2)

### What operating system and processor architecture are you using (`go env`)?
```
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/suzmue/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/suzmue/go"
GOPROXY=""
GORACE=""
GOROOT="/Users/suzmue/tipgo/go"
GOTMPDIR=""
GOTOOLDIR="/Users/suzmue/tipgo/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/suzmue/myproject/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c4/982kvfgd4jz6_6sdlzzk2nj400fkl_/T/go-build226914824=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
### What did you do?
Files in directory a: 
a/a.go:
`package a`
a/a_test.go:
`package a; import "testing"; func Test(t *testing.T){}`
a/go.mod:
`module github.com/user/a`

```
$ cd a/
$ go test
```

### What did you expect to see?
```
PASS
ok  	github.com/user/a	0.017s
```

### What did you see instead?
```
build github.com/user/a (test): cannot find module for path github.com/user/a (test)
```

### Additional notes
`go test` works as expected in any subdirectories of a.

**Comment by matloob** [comment] 2018-08-01 14:49
I can reproduce this on tip.

**Comment by suzmue** [comment] 2018-08-01 14:50
cc @bcmills

**Comment by bcmills** [comment] 2018-08-01 14:58
I suspect that this is the same underlying problem as https://github.com/golang/go/issues/26602.

**Comment by mfridman** [comment] 2018-08-01 15:30
@suzmue I can repro as well. I did notice `./...` works, e.g., 

```
# go version devel +6b9c782f9f Wed Aug 1 00:57:00 2018 +0000 darwin/amd64

GO111MODULE=on go run main.go
build main: cannot find module for path main

GO111MODULE=on go run ./...
2018/08/01 11:14:49 failed decodeResp: Failed: Invalid Access Code / Password
exit status 1
```

Maybe the same is true for test. Should be fixed though.

**Comment by rogpeppe** [comment] 2018-08-03 12:45
I bisected - it seems that https://go-review.googlesource.com/125836 (commit b294fe9b0a9a0b9032cb2ecf9924e4c90f8de0ac) introduced this problem.

**Comment by bcmills** [comment] 2018-08-03 14:13
@rogpeppe, thanks for bisecting. In my experience debugging similar issues this week, these kinds of problems are very sensitive to the state of the module cache: did you clear the module and build caches at each commit?

(Just wondering how confident I should be in the bisection result.)

**Comment by rogpeppe** [comment] 2018-08-03 14:21
@bcmills I just tried again with clean module and build caches and I got the same results. I might be missing something though.

**Comment by bcmills** [comment] 2018-08-03 14:22
Nope, you've probably got it right. I suspect an off-by-one error (a trailing slash).

**Comment by rogpeppe** [comment] 2018-08-03 14:27
That is: 68170aa677b9fc70ce3d0fc152354e0a7e63c8cf succeeds consistently;
b294fe9b0a9a0b9032cb2ecf9924e4c90f8de0ac fails.

FWIW I've been using gopkg.in/macaroon.v2 for testing.
Reproduce by:

     cd /tmp
     git clone git@github.com:go-macaroon/macaroon
     cd macaroon
     go test

After downloading the deps, I get:

    build gopkg.in/macaroon.v2 (test): cannot find module for path gopkg.in/macaroon.v2 (test)

**Comment by bcmills** [comment] 2018-08-03 14:33
I added @suzmue's repro steps as a script test and it fails. (Thanks for the great minimal test case!)

I'll try macaroon too once it's fixed, just to be sure.

**Comment by bcmills** [comment] 2018-08-03 14:50
Think I've found the problem. The `ImportStack` is not “a stack of import paths”, it is “a stack of import paths, sometimes with the suffix " (test)". We can't resolve an import for a module path with a " (test)" suffix, because that's not a valid import path.

http://thecodelesscode.com/case/84

**Comment by bcmills** [comment] 2018-08-03 15:45
Hmm, `macaroon` still doesn't work.

```
$ git clone git@github.com:go-macaroon/macaroon
[…]
$ cd macaroon

macaroon$ go test
go: finding github.com/frankban/quicktest v1.0.0
go: finding github.com/google/go-cmp v0.2.0
go: finding golang.org/x/crypto v0.0.0-20180723164146-c126467f60eb
go: finding github.com/kr/pretty v0.1.0
go: finding github.com/kr/text v0.1.0
go: finding github.com/kr/pty v1.1.1
go: downloading golang.org/x/crypto v0.0.0-20180723164146-c126467f60eb
go: downloading github.com/frankban/quicktest v1.0.0
go: downloading github.com/google/go-cmp v0.2.0
go: downloading github.com/kr/pretty v0.1.0
go: downloading github.com/kr/text v0.1.0
build gopkg.in/macaroon.v2_test: cannot find module for path gopkg.in/macaroon.v2_test
```

**Comment by bcmills** [comment] 2018-08-03 19:02
Ok, think I've got it this time.

```
$ cd $(mktemp -d)
$ git clone git@github.com:go-macaroon/macaroon
$ cd macaroon/
macaroon$ go test
PASS
ok      gopkg.in/macaroon.v2    0.046s
```

**Comment by anacrolix** [comment] 2018-08-06 08:30
I'm seeing this too, github.com/anacrolix/dht.

**Closed** 2018-08-07 14:20 UTC
Labels: NeedsInvestigation, modules, release-blocker

**Comment by bcmills** [comment] 2018-08-07 22:02
Should be fixed at head. Please let me know if you're still seeing these symptoms.

**Comment by anacrolix** [comment] 2018-08-08 00:51
Yes that's fixed it.

**Comment by sinyang** [comment] 2018-08-19 13:59
Any idea when this will be pushed to vgo? 
I just stumbled across using these tools for golang versioning and am playing with vgo. This issue is still present there. However, it goes away when I manually copy the changed files from https://github.com/golang/go/commit/79faf9246e978628373999801279038a2ebc21ad into my local vgo sources.
