### ISSUE TITLE
syscall: failure with "go tool compile: fork/exec C:\workdir\...\compile.exe: The parameter is incorrect."

### ISSUE THREAD

**Issue by alexbrainman** [golang/go#44662] opened 2021-02-27 04:04 UTC
I just noticed that 

https://github.com/golang/go/issues/44011

broken `windows amd64 longtest` builder

https://build.golang.org/log/7cbab654e1a01035642ac138de3d6cf3fe18ef82

```
ok  	net/mail	0.031s
ok  	net/rpc	0.058s
ok  	net/rpc/jsonrpc	0.049s
go tool compile: fork/exec C:\workdir\go\pkg\tool\windows_amd64\compile.exe: The parameter is incorrect.

go tool dist: FAILED: go list -gcflags=all= -ldflags=all= -f={{if .Stale}}	STALE {{.ImportPath}}: {{.StaleReason}}{{end}} std: exit status 1
```

and

`windows arm zx2c4` builder

https://build.golang.org/log/d5a457cd180589d602604d652e58832c7450fdea

```
ok  	compress/lzw	0.292s
ok  	compress/zlib	1.534s
go tool asm: fork/exec C:\workdir\go\pkg\tool\windows_arm\asm.exe: The parameter is incorrect.

go tool dist: FAILED: go list -gcflags=all= -ldflags=all= -f={{if .Stale}}	STALE {{.ImportPath}}: {{.StaleReason}}{{end}} std: exit status 1
```

Also other windows builders occasionally fail with strange errors.

https://build.golang.org/log/24e5d44bab19e14cee7ae4fca7702a6ca7e6cfa9

https://build.golang.org/log/33671e9cd3fa7c4249e15146caedb07d8d0336de

https://build.golang.org/log/4e96b5675f64045114f2db4d16416af17d001b29

I don't even know how to debug this.

/cc @zx2c4 

Alex

**Comment by zx2c4** [comment] 2021-02-27 11:00
I'll look into it. It might be that stricter fd inheritance is unearthing subtle races that were there before but went unnoticed.

**Comment by alexbrainman** [comment] 2021-02-27 20:12
@zx2c4 unrelated to this issue, but I sent you

https://go-review.googlesource.com/c/sys/+/297269

for a review.

Apparently, it is possible that you did not receive email about my CL

https://groups.google.com/g/golang-dev/c/qjRiFX1xjAg

We don't want you to miss chance to review my changes again. Do we? :=)

Alex

**Comment by zx2c4** [comment] 2021-02-27 21:25
> Apparently, it is possible that you did not receive email about my CL

I did miss the email due to the Gerrit problem, but I've been manually checking Gerrit, so I actually reviewed that and left 5 comments several hours ago.

**Comment by alexbrainman** [comment] 2021-02-27 21:31
> I did miss the email due to the Gerrit problem, but I've been manually checking Gerrit, so I actually reviewed that and left 5 comments several hours ago.

Cool. I won't do any work on Gerrit today to avoid missing some messages. I solely rely on my email to keep tabs on things.

Alex

**Comment by zx2c4** [comment] 2021-02-28 12:08
I've posted a fix for this issue: https://go-review.googlesource.com/c/go/+/297391

**Comment by bcmills** [comment] 2021-03-02 04:39
Is there any ETA on when the `windows-amd64-longtest` builder will be fixed, or perhaps something that we can roll back to stem the failures until a proper fix can land?

We have a tendency to break the Windows tests in `cmd/go` changes, so we rely heavily on `windows-amd64-longtest` in particular as a SlowBot. With it being as flaky as it currently seems to be, I'm worried that we're going to introduce some other regression without noticing.

**Comment by zx2c4** [comment] 2021-03-02 07:47
I wrote a fix immediately but nobody reviews it, despite me sending direct emails.

https://go-review.googlesource.com/c/go/+/297389
https://go-review.googlesource.com/c/sys/+/297331

**Comment by alexbrainman** [comment] 2021-03-02 07:54
> Is there any ETA on when the `windows-amd64-longtest` builder will be fixed

I am not working on this issue. @zx2c4 is.

As far as I know. Jason proposed 2 solutions

https://go-review.googlesource.com/c/go/+/297391/

and

https://go-review.googlesource.com/c/go/+/297389/

I also proposed another way to solve this problem - see my "Just a crazy idea." comment on

https://go-review.googlesource.com/c/go/+/297391/

Someone need to help Jason to choose correct solution here. Perhaps Ian or Austin or Cherry. Someone who is familiar with gc and unsafe package rules. I will let you decide who to ping.

Jason included you and Ian in his CLs. But I suspect you did not receive correspondent emails from Gerrit. So, probably, best to keep communications here.

Thank you.

Alex

**Comment by zx2c4** [comment] 2021-03-02 07:57
I abandoned one solution in favor of the other: https://go-review.googlesource.com/c/go/+/297389 Please review that. It comes with a test case too.

**Comment by zx2c4** [comment] 2021-03-02 10:06
Indeed it looks like Gerrit still isn't sending notifications. So, time for a Github bomb, ugh:

@ianlancetaylor @bradfitz @cherrymui @aclements @bcmills Could one or all of you please +2 https://go-review.googlesource.com/c/go/+/297389 and https://go-review.googlesource.com/c/sys/+/297331 so that we can make the builders happy again?

**Comment by bcmills** [comment] 2021-03-02 16:16
I took a look, but I don't understand how that approach can be correct over the long term. IIRC the Go runtime is technically allowed to relocate any allocation whenever that allocation is not an argument to an active C library or system call, so any pointer that will be retained by the syscall really needs to be allocated outside of the Go heap.

**Comment by zx2c4** [comment] 2021-03-02 16:18
If the GC relocates things, then it'd of course relocate references to the object too, necessarily. In that case, changing the pointers inside that structure would be fine to do.

**Comment by bcmills** [comment] 2021-03-02 16:30
Ah, so the Windows library call is guaranteed not to store the pointers in fields that aren't visible to the runtime as pointers?

**Comment by zx2c4** [comment] 2021-03-02 16:31
You don't really get many guarantees, but the two general behaviors are: store a pointer in a struct, or allocate memory and copy the information. I assumed it was the latter. But it turned out to be the former, hence this issue.

**Comment by zx2c4** [comment] 2021-03-02 16:45
@bcmills I've addressed your comments on https://go-review.googlesource.com/c/go/+/297389 and applied them equally to https://go-review.googlesource.com/c/sys/+/297331 as well. Thanks for your review. Hopefully we can get this merged.

**Comment by zx2c4** [comment] 2021-03-02 20:09
@ianlancetaylor @mdempsky Thanks for the review. Gerrit notifications are still busted, so letting you know here:

https://go-review.googlesource.com/c/go/+/297389 and https://go-review.googlesource.com/c/sys/+/297331 have been updated to reflect your comments.

**Comment by zx2c4** [comment] 2021-03-02 20:39
@mdempsky Thanks for review #2. As Gerrit notifications are still busted, so letting you know here again.

https://go-review.googlesource.com/c/go/+/297389 and https://go-review.googlesource.com/c/sys/+/297331 have been updated to reflect your comments.

**Comment by mdempsky** [comment] 2021-03-02 20:46
@zx2c4 Thanks, +1'd.

**Comment by zx2c4** [comment] 2021-03-02 20:59
Great. @ianlancetaylor @bradfitz Submission time?

**Comment by alexbrainman** [comment] 2021-03-03 07:06
I left some comments on https://go-review.googlesource.com/c/go/+/297389

Alex

**Comment by zx2c4** [comment] 2021-03-03 07:25
Replied. Can we _please_ get this merged? We're now in v10 and the tree is still broken, and I'm 99% sure I've addressed concerns every which way and added every comment that somebody thought I should add, and so forth.

**Comment by alexbrainman** [comment] 2021-03-03 07:43
I left more comments at https://go-review.googlesource.com/c/go/+/297389

Alex

**Comment by zx2c4** [comment] 2021-03-03 07:50
@alexbrainman Yup, and replied.

**Comment by alexbrainman** [comment] 2021-03-03 08:35
I replied at https://go-review.googlesource.com/c/go/+/297389

Alex

**Closed** 2021-03-04 19:59 UTC
Labels: NeedsInvestigation, OS-Windows, Soon, release-blocker

**Comment by Roman-Jordan** [comment] 2021-12-07 21:21
go 1.17, sometimes I get The parameter is incorrect, and others the expected output.. I guess it depends on the weather from what I can tell. 

```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("test")
}
```
I run, `go run [myapp]` sometimes it works great, others, it does not.. What is confusing me... Is Why? What parameter? Why does it work sometimes after rebooting and others not.. I have no idea.. Is this a common problem.. Not sure.. but, if you have any pointers that would be nice.. In the mean time.. I will just develop in not GO, into I get a better understanding of what is causing the dice roll..

**Comment by aclements** [comment] 2021-12-07 21:46
@Roman-Jordan , we avoid reusing closed issues. Could you open a new issue, including details of your environment? Thanks.
