### ISSUE TITLE
proposal: official way to detect if code running under test

### ISSUE THREAD

**Issue by pjebs** [golang/go#56897] opened 2022-11-22 05:25 UTC
There are times when we need to do know if code is being run under tests (i.e. `go test `).

There are a few solutions here: https://stackoverflow.com/questions/14249217/how-do-i-know-im-running-within-go-test
https://medium.com/picus-security-engineering/how-to-know-if-a-golang-app-is-executed-with-go-test-66487ccd71b6

Some way the solutions originally worked and then stopped as the Go version changed.
Others say it worked. Others way it doesn't.

It would be good if there was an official way to know.

**Comment by seankhliao** [comment] 2022-11-22 07:45
Duplicate of #14668

**Closed by seankhliao** 2022-11-22 07:45 UTC
Labels: Proposal
