### ISSUE TITLE
cmd/go: "mod tidy" tries to require the latest version of a replacement module

### ISSUE THREAD

**Issue by developStorm** [golang/go#70137] opened 2024-10-31 09:09 UTC
### Go version

go version go1.21.1 darwin/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='~/Library/Caches/go-build'
GOENV='~/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='~/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='~/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/Cellar/go/1.21.1/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/Cellar/go/1.21.1/libexec/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='.../zdns/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/tmp/go-build0000000=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

Bump version for zmap/dns in this replace line to `v1.1.63`, then run `go mod tidy`

https://github.com/zmap/zdns/pull/468/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R20

### What did you see happen?

> go mod tidy
go: github.com/zmap/dns@v1.1.63 used for two different module paths (github.com/miekg/dns and github.com/zmap/dns)

### What did you expect to see?

`go mod tidy` executes without errors.

The issue arises when `tidy` attempts to pull the latest version of the replacement target module (`zmap/dns` in this case) and includes it as an indirect requirement. When the replace target version is the latest version, the indirect require that tidy tries to add caused the above error. 

Adjusting the `replace` directive to a non-latest version - e.g., `replace github.com/miekg/dns => github.com/zmap/dns v1.1.62-zdns` as what we have in the referenced PR now - allows `tidy` to complete without errors. However, `tidy` will try to introduce an indirect requirement for `v1.1.63` (latest), which I believe is also undesirable, as I specifically requested a version that is not the latest in the `replace` directive. 

I expected `go mod tidy` to respect whatever version specified in `replace`, and does not attempt to introduce the latest version as an indirect require.

**Comment by cagedmantis** [comment] 2024-10-31 15:54
cc [@matloob](https://github.com/matloob) [@samthanawalla](https://github.com/samthanawalla)

**Comment by seankhliao** [comment] 2024-10-31 18:01
Duplicate of #26904

**Closed by seankhliao** 2024-10-31 18:01 UTC
Labels: NeedsInvestigation, GoCommand

**Comment by developStorm** [comment] 2024-10-31 18:29
Hi @seankhliao, thanks for reviewing this issue. Could you clarify why this is considered a duplicate of #26904? In #26904, the user module involved both the upstream and fork1, aiming to use fork2 as a replacement for both, with neither upstream nor fork1 containing a `go.mod`.

In this case, however, we only have the upstream and a single fork. The project initially used only the upstream, and our intention is to replace it with our fork directly. We aren’t aiming to use both upstream and our fork simultaneously - though `go mod tidy` seems to attempt that, which is central to the issue here. FWIW, both the upstream repo and our fork have a valid `go.mod` and declare their module path.

**Comment by seankhliao** [comment] 2024-10-31 18:35
Replace replaces source code, but doesn't rewrite import paths. meikg/dns is replaced by zmap/zdns, but this replaced version of meikg/dns has imports that require zmap/zdns, that's are where your indirect dependency comes from.

**Comment by seankhliao** [comment] 2024-10-31 19:07
Sorry, zmap/dns depends on zmap/dns (itself).
When used as a replace target, zmap/dns is used as meikg/dns but still depends on zmap/dns, e.g. here https://github.com/zmap/dns/blob/master/dnsutil/util.go#L11

**Comment by developStorm** [comment] 2024-10-31 19:13
Ah, I see what's going on now—thank you so much for your help! I don’t believe we actually use the `dnsutil` package. Do you have any recommendations for preventing this package from being imported on the user module side or from being exported on the forked `zmap/dns` side, so we can avoid that self-require? Or is our only option to remove the package from the source tree in our fork altogether?
