### ISSUE TITLE
go.dev: add information on Go version of standard library symbols

### ISSUE THREAD

**Issue by Fenthick** [golang/go#38586] opened 2020-04-22 08:45 UTC
### What is the URL of the page with the issue?
 Any standard library package page, e.g. [https://pkg.go.dev/net/http?tab=doc#Request.Clone](https://pkg.go.dev/net/http?tab=doc#Request.Clone)

### What is your user agent?
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0
 
### Screenshot
![image](https://user-images.githubusercontent.com/15718596/79960242-77952000-8485-11ea-8e46-d95bb7ec69bc.png)

### What did you do?
I navigated to the Request.Clone() method introduced in Go 1.13.
 
### What did you expect to see?
Information in which Go version the method was introduced. Such information is available at [https://golang.org/pkg/net/http/#Request.Clone](https://golang.org/pkg/net/http/#Request.Clone):
![image](https://user-images.githubusercontent.com/15718596/79960262-7cf26a80-8485-11ea-9d66-5ee4430d7f5b.png)

### What did you see instead?
No information in which Go version the method was introduced.

**Comment by Fenthick** [comment] 2020-04-22 09:24
The same situation with fields of types, e.g. https://pkg.go.dev/net/http?tab=doc#Transport.ForceAttemptHTTP2 has no `Go 1.13` label.

**Comment by julieqiu** [comment] 2020-04-22 19:04
This is similar to #37102. Also related: 37819

**Comment by dmitshur** [comment] 2020-04-22 21:47
> This is similar to #37102.

@julieqiu Should we close this as a duplicate of #37102, or is there something different about this issue?

**Comment by julieqiu** [comment] 2020-04-23 01:45
I think it makes sense to close this as a duplicate. @Fenthick feel free to comment on #37102 with anything else.

**Closed by julieqiu** 2020-04-23 01:45 UTC
Labels: FeatureRequest, NeedsInvestigation, UX, go.dev
