### ISSUE TITLE
go present: javascript error on page

### ISSUE THREAD

**Issue by eldondev** [golang/go#9995] opened 2015-02-25 07:25 UTC
reproducible when -play=false
For contribution guidelines:
* On go version go1.4.2 linux/amd64 
* having run `go get golang.org/x/tools/cmd/present`
* I ran `bin/present -play=false -http 0.0.0.0:8888` and navigated to the page in chromium v. 41
* where I expected to be able to page through my presentation. 
* Instead, I got the following javascript error: `Uncaught ReferenceError: $ is not defined`

**Comment by eldondev** [comment] 2015-02-25 07:26
See also https://github.com/golang/tools/pull/4

**Comment by adg** [comment] 2015-02-25 07:29
Dupe of #9878

**Closed by adg** 2015-02-25 07:29 UTC
