### ISSUE TITLE
cmd/compile: cannot create a type alias for a type constraint

### ISSUE THREAD

**Issue by ray-harris** [golang/go#51929] opened 2022-03-24 21:25 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ray/Library/Caches/go-build"
GOENV="/Users/ray/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ray/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ray/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/ray/.gimme/versions/go1.18.darwin.amd64"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/ray/.gimme/versions/go1.18.darwin.amd64/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cd/c35rv7yn5s3104f8dwqk3tqh0000gn/T/go-build4225907508=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

main.go
```
package main

import (
	"fmt"

	"golang.org/x/exp/constraints"
)

type Float = constraints.Float

func main() {
	fmt.Println("should compile")
}
```

Run
```
go run main.go
```

### What did you expect to see?

"should compile"

### What did you see instead?

```
# command-line-arguments
./main.go:9:14: interface contains type constraints
```

If this is expected behavior, the language spec should be updated to indicate that you can't alias a type constraint.

**Comment by seankhliao** [comment] 2022-03-24 21:42
Duplicate of #51616

**Closed by seankhliao** 2022-03-24 21:42 UTC
