### ISSUE TITLE
x/build: update for new distribution archive builds

### ISSUE THREAD

**Issue by rsc** [golang/go#58659] opened 2023-02-23 14:39 UTC
For #24904, I have mailed [CL 470676](https://go.dev/cl/470676), which adds a new `make.bash -distpack` flag that generates distribution archives.

On the release infrastructure side, x/build needs to start using `make.bash -distpack` in Go 1.21 and later to produce the distribution archives (including the source archives), instead of the code it currently uses to generate them. The `-distpack` mode also writes the module files that we need to serve for GOTOOLCHAIN support (#57001). Those need to start being served from go.dev/dl like the other archives. 

When writing a VERSION file for Go 1.21 or later, the file should be of the form

	goX.Y.Z
	time 2022-02-23T12:34:56Z

That time stamp is used as the modification time in the archives (for reproducibility). This means something in the x/build metadata will have to record the time to use for each release and then write that time into the VERSION file.	

The reproducibility work enables building distribution archives on any kind of machine. In particular it should be possible to build everything on an appropriately trusted+locked down linux/amd64 system. You use `GOOS=goos GOARCH=goarch ./make.bash -distpack`.

Note that if we move the generation of the linux/arm distribution archives to linux/amd64, we need to set `GOARM=6` as well, to mimic the environment on linux-arm-aws. So `GOOS=linux GOARCH=arm GOARM=6 ./make.bash -distpack`.

It doesn't matter what goos/goarch is used to generate the source archives (you get the same result on every system, as one would expect), but it does need to be generated by `make.bash -distpack` for reproducibility.

Once the release infrastructure is updated, we should issue a go1.21alpha1 (built from a master branch is fine, no need for a release branch) to exercise the infrastructure and to test that external users can reproduce the archives (#57120).

/cc @golang/release

**Comment by rsc** [comment] 2023-02-23 16:39
One question is how to test that things stay reproducible.

One possible answer would be to use the trusted Linux machine as source of truth but then _also_ build everything on Windows and require getting bit-for-bit identical outputs before blessing those files as part of the release. The Windows machine does not have to be as trusted since it is only a sanity check on the trusted builder. The two OSes Windows and Linux should be sufficiently different to serve as a good check.

**Comment by heschi** [comment] 2023-03-03 21:07
@rsc once the CL is merged we'll prioritize this. Looking forward to it.

**Comment by heschi** [comment] 2023-04-24 16:40
The bulk of this is done; it would be good to do the reproducibility testing described in https://github.com/golang/go/issues/58659#issuecomment-1442089388.

**Comment by heschi** [comment] 2023-04-25 19:25
Oh, I also intended to prefetch the module files from the module proxy to make sure that automatic toolchain updates started working immediately.

**Closed** 2023-05-01 20:48 UTC
Labels: Builders, NeedsFix, early-in-cycle, release-blocker
