### ISSUE TITLE
affected/package: core

### ISSUE THREAD

**Issue by fahrettinEmre** [golang/go#51970] opened 2022-03-26 20:29 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.17.1

</pre>

### Does this issue reproduce with the latest release?

ı dont' know.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
amd64 , darwin
macOs Montery 12.3

### What did you do?
ı try to decrease integer in for loop and print the value of int.
code example:

package main
import "fmt"
func main(){
var i int32 = -1
	for {
		i += i
		fmt.Printf("%d,", i)

	}
}

### What did you expect to see?

ı expected output is -2,-4,-8 etc.

### What did you see instead?

0,0,0,0,0,0,00,0,0,0,0,0,0...

when ı used the time.Sleep(time.Second) , it work what  i expected.

**Comment by Quaqmre** [comment] 2022-03-26 20:31
I have same issue ,

**Comment by randall77** [comment] 2022-03-26 20:34
This is not a bug. You do get -2,-4,-8, etc. Just that once you get to -2^63, the subsequent numbers are 0. An there are a lot of them.
Replace `,` with `\n` and pipe the result through `head`, you'll see them at the start of the sequence.
Closing, as this is not a bug.

**Closed by randall77** 2022-03-26 20:34 UTC
