### ISSUE TITLE
cmd/go: go test cache unaffected by GODEBUG value

### ISSUE THREAD

**Issue by findleyr** [golang/go#65436] opened 2024-02-01 20:30 UTC
As we work on getting x/tools tests passing with `GODEBUG=gotypesalias=1` in #65294, I noticed that GODEBUG is not included in the test cache key. It probably should be.

```
[gopls]> go test -count=1 ./doc
ok      golang.org/x/tools/gopls/doc    1.912s
[gopls]> GODEBUG=gotypesalias=1 go test ./doc
ok      golang.org/x/tools/gopls/doc    (cached)
[gopls]> GODEBUG=gotypesalias=1 go test -count=1 ./doc
--- FAIL: TestGenerated (1.71s)
    generate_test.go:26: documentation needs updating. Run: cd gopls && go generate
FAIL
FAIL    golang.org/x/tools/gopls/doc    1.774s
FAIL
```

CC @bcmills @matloob

**Comment by bcmills** [comment] 2024-02-01 20:52
Adding `GODEBUG` to the test cache key seems appropriate — every Go program depends on `GODEBUG` via the `runtime` package, and it is likely that the runtime parses that variable in a way that is not visible to the test log.

**Comment by bcmills** [comment] 2024-02-01 22:25
Duplicate of #51561

**Comment by bcmills** [comment] 2024-02-01 22:28
Hmm, no. #51561 is about the build output, not the test output. Reopening.

**Comment by bcmills** [comment] 2024-02-01 22:29
Other environment variables go into the test-output cache key here:
https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/test/test.go;l=1869-1870;drc=e076c1b897b30648db794b66fd10929fe9a9852e

`GODEBUG` is probably not being recorded their because it is parsed directly by the `runtime` package without going through the usual `os.Getenv` hooks. We should probably add it to the cache key explicitly.

**Comment by samthanawalla** [comment] 2024-02-27 21:51
A little confused here, -count=1 disables test caching explictly. ([link](https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/test/test.go;l=1693;drc=f8b4653500744da567767b641378193638d4fcf8;bpv=0;bpt=1#:~:text=The%20idiomatic%20way%20to%20disable,explicitly%20is%20to%20use%20%2Dcount%3D1))
This is the current behavior:

$go clean -cache

$GODEBUG=gotypesalias=1 go test ./doc
> runtime
../../go/src/runtime/runtime2.go:993:6: internal compiler error: assertion failed
FAIL

$ go test ./doc
>ok      golang.org/x/tools/gopls/doc    4.267s

$ GODEBUG=gotypesalias=1 go test ./doc
>ok      golang.org/x/tools/gopls/doc    (cached)

$ go test -count=1 ./doc
>ok      golang.org/x/tools/gopls/doc    4.281s

$ GODEBUG=gotypesalias=1 go test -count=1 ./doc
>--- FAIL: TestGenerated (3.88s)
    generate_test.go:26: documentation needs updating. Run: cd gopls && go generate
FAIL
FAIL    golang.org/x/tools/gopls/doc    3.955s
FAIL

It seems to me something fishy is going on with the first line: GODEBUG=gotypesalias=1 go test ./doc fails but then succeeds using the cached test with GODEBUG=gotypesalias=1 omitted.

Are we expecting GODEBUG=gotypesalias=1 go test ./doc to fail initially?

**Comment by bcmills** [comment] 2024-02-27 22:41
> Do we want `GODEBUG=gotypesalias=1 go test ./doc` to not use the cached result from `go test ./doc`?

Yep, exactly. The mismatched `GODEBUG` setting should cause the cache key for the new test run not to match the prior run.

**Comment by rsc** [comment] 2024-03-09 01:17
Sorry if you were working on this @samthanawalla. I ran into this problem myself and had to fix it to make progress debugging something else. I didn't see this issue until after I'd written the CL.

**Closed** 2024-03-09 22:24 UTC
Labels: NeedsFix, GoCommand
