### ISSUE TITLE
cmd/go: go toolchain version switch doesn't work when only language version is set in go.mod

### ISSUE THREAD

**Issue by hyangah** [golang/go#65580] opened 2024-02-07 17:58 UTC
### Go version

go 1.21.4

### Output of `go env` in your module/workspace:

```shell
$ GOTOOLCHAIN=auto go env
go: downloading go1.22 (darwin/amd64)
go: download go1.22 for darwin/amd64: toolchain not available
```

### What did you do?

Had a project created with a go built from tip during 1.22 dev cycle. 
The go.mod file has language version, but not toolchain version yet.

```
$ cat go.mod
module example.com/bug

go 1.22
```

### What did you see happen?

Since go1.22.0 is released, I expected the go command to pick up go1.22.0 when version switching is needed.
Instead, most go commands failed in the module since there is no toolchain named `go1.22`. 

### What did you expect to see?

```
~/bug$ go version
go version go1.21.4 darwin/amd64
~/bug$ GOTOOLCHAIN=auto go env
go: downloading go1.22 (darwin/amd64)
go: download go1.22 for darwin/amd64: toolchain not available
~/bug$ GOTOOLCHAIN=auto go version
go: downloading go1.22 (darwin/amd64)
go: download go1.22 for darwin/amd64: toolchain not available
~/bug$ GOTOOLCHAIN=auto go mod tidy
go: downloading go1.22 (darwin/amd64)
go: download go1.22 for darwin/amd64: toolchain not available
~/bug$ GOTOOLCHAIN=auto go mod tidy -go=1.21.4
go: downloading go1.22 (darwin/amd64)
go: download go1.22 for darwin/amd64: toolchain not available
~/bug$ GOTOOLCHAIN=auto go get go@latest
go: downloading go1.22 (darwin/amd64)
go: download go1.22 for darwin/amd64: toolchain not available
~/bug$ GOTOOLCHAIN=auto go get toolchain@latest
go: downloading go1.22 (darwin/amd64)
go: download go1.22 for darwin/amd64: toolchain not available
~/bug$ GOTOOLCHAIN=auto go build
go: downloading go1.22 (darwin/amd64)
go: download go1.22 for darwin/amd64: toolchain not available
~/bug$ GOTOOLCHAIN=auto go build ./...
go: downloading go1.22 (darwin/amd64)
go: download go1.22 for darwin/amd64: toolchain not available
```

**Comment by seankhliao** [comment] 2024-02-07 18:34
Duplicate of #62278

**Closed by seankhliao** 2024-02-07 18:34 UTC

**Comment by hyangah** [comment] 2024-02-07 19:26
@fzipp `go 1.22` is a valid syntax. 
@seankhliao Thanks for the pointer to the issue. The spec allows a language version and when the toolchain is available to handle the language version, we need to do better (given all the confusion and noise in #62278).
