### ISSUE TITLE
sync: add example for Cond

### ISSUE THREAD

**Issue by kevinburke** [golang/go#24952] opened 2018-04-19 19:20 UTC
It would be nice to have a complete example for the Cond struct - signaling or broadcasting from one goroutine, and receiving it in another one.

**Comment by ianlancetaylor** [comment] 2018-04-19 19:29
It's been tried before.  I'm pretty ambivalent.  The problem is that Go has better mechanisms for every simple use of a `sync.Cond`.  To get any benefit from a `sync.Cond` you need a relatively complex use case that is difficult to show in an example.  Personally I'm reluctant to write an example showing a simple use case of `sync.Cond`, because that implies that it would be a good choice for that simple use case, which I believe is not the case.

**Comment by bcmills** [comment] 2018-04-19 19:44
Duplicate of #20491.

**Closed by bcmills** 2018-04-19 19:44 UTC
Labels: Documentation

**Comment by kevinburke** [comment] 2018-04-19 20:59
OK
