### ISSUE TITLE
go/internal/gcimporter: support vendoring

### ISSUE THREAD

**Issue by alandonovan** [golang/go#13756] opened 2015-12-28 21:02 UTC
The Go 1.5. vendoring feature means that a package importer is now logically a function of two variables: the import path, and additionally the directory in which the import declaration appears.

The `go/types` `TestStdlib` test currently fails because the default importer does not support vendoring (and cannot without an API change).

**Comment by griesemer** [comment] 2016-01-06 19:26
Duplicate of #13688.

**Closed by griesemer** 2016-01-06 19:26 UTC

**Comment by rsc** [comment] 2016-01-06 19:34
@alandonovan, if I invert the flag, this gets fixed automatically, right?

**Comment by alandonovan** [comment] 2016-01-06 20:10
No.  The problem here is that vendoring makes the interpretation of an import path a function of two parameters, and the `go/types.Importer` interface exposes only one.  Ideally, we would add a `srcDir string` parameter to the interface's method, and its implementations would plumb this value through to `(*build.Context).Import`.  That, of course, would be an incompatible API change, though I suspect there are few if any clients that define their own Importer types.

(It's possible that flipping the flag causes the tests to pass, but it wouldn't solve the general problem.)
