### ISSUE TITLE
x/build/cmd/gomote: OpenBSD workdir is owned by root

### ISSUE THREAD

**Issue by aclements** [golang/go#23636] opened 2018-01-31 16:10 UTC
`/tmp/workdir` on the openbsd-386-60 gomote (and probably the other openbsd gomotes, but I didn't check) is owned by root and not writable by user gopher. `gomote push` is able to write the Go tree there, but it's all owned by root, so if you then `gomote ssh` and run `make.bash` it will fail because you're logged in as gopher and can't write to the Go tree.

The work-around is to `cp -R /tmp/workdir/go $HOME/go` and build from gopher's home directory.

/cc @bradfitz @andybons

**Comment by bradfitz** [comment] 2018-01-31 16:45
I think the actual problem is that `gomote ssh` is using a different username on the system than how the builders are configured. It should be sshing in as root instead of gopher I bet.

**Comment by FiloSottile** [comment] 2018-02-08 21:49
Duplicate of #23043

**Closed** 2018-02-08 21:50 UTC
Labels: Builders
