### ISSUE TITLE
net/http/httputil: DumpRequest and others misrepresent requests

### ISSUE THREAD

**Issue by wxolp** [golang/go#54011] opened 2022-07-22 22:58 UTC
### What version of Go are you using (`go version`)?

~~~
go version go1.18 windows/amd64
~~~

### What did you do?

Using this program:

~~~go
package main

import (
   "net/http"
   "net/http/httputil"
   "os"
)

func main() {
   req, err := http.NewRequest("", "https://example.com/hello", nil)
   if err != nil {
      panic(err)
   }
   req.URL.Host = "github.com"
   buf, err := httputil.DumpRequestOut(req, false)
   if err != nil {
      panic(err)
   }
   os.Stdout.Write(buf)
   req.Write(os.Stdout)
   res, err := new(http.Transport).RoundTrip(req)
   if err != nil {
      panic(err)
   }
   defer res.Body.Close()
   buf, err = httputil.DumpResponse(res, false)
   if err != nil {
      panic(err)
   }
   os.Stdout.Write(buf)
}
~~~

### What did you expect to see?

The printed requests should match the printed response, at least in spirit.

### What did you see instead?

~~~
GET /hello HTTP/1.1
Host: example.com
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip

GET /hello HTTP/1.1
Host: example.com
User-Agent: Go-http-client/1.1

HTTP/2.0 301 Moved Permanently
Location: https://github.com/hello
Content-Length: 0
~~~

The requests say `example.com`, but the response shows the request actually went to `github.com`. Whats strange also is that the program takes the original URL:

https://example.com/hello

and changes it to:

https://github.com/hello

then for some reason you get a redirect to the same URL:

https://github.com/hello

**Comment by wxolp** [comment] 2022-07-23 14:33
I was wrong - all code is returning `example.com`. I was confused because request returns 404, but all the net/http code appears to be correct after all

**Comment by seankhliao** [comment] 2022-07-23 17:19
> 	// For client requests, the URL's Host specifies the server to
	// connect to, while the Request's Host field optionally
	// specifies the Host header value to send in the HTTP
	// request.

The client connects to github.com while sending a host header of example.com

Closing as not a bug.

**Closed by seankhliao** 2022-07-23 17:19 UTC

**Comment by wxolp** [comment] 2022-07-23 18:38
I think I figured it out. I was trying to create a new Request without having to re-parse the URL, but it looks like you can just parse the new part:

~~~go
package main

import (
   "fmt"
   "net/http"
)

func main() {
   base, err := http.NewRequest("GET", "http://example.com", nil)
   if err != nil {
      panic(err)
   }
   ref, err := http.NewRequest("GET", "/hello", nil)
   if err != nil {
      panic(err)
   }
   ref.URL = base.URL.ResolveReference(ref.URL)
   res, err := new(http.Transport).RoundTrip(ref)
   if err != nil {
      panic(err)
   }
   defer res.Body.Close()
   fmt.Println(res.Status)
}
~~~
