### ISSUE TITLE
test: locklinear.go failures with "lockmany: too slow"

### ISSUE THREAD

**Issue by bcmills** [golang/go#32986] opened 2019-07-08 19:20 UTC
From the `illumos-amd64-joyent` builder, in https://build.golang.org/log/b60463ada3a04bbfdb7f714e54d819176e60a833:

```
##### ../test
# go run run.go -- locklinear.go
exit status 1
panic: lockmany: too slow: 1000 ops: 22.164624ms; 2000 ops: 433.387975ms

1000 42.726699ms 2000 43.00828ms (1.0X)
1000 13.237367ms 2000 40.902635ms (3.1X)
1000 9.373097ms 2000 39.993182ms (4.3X)
1000 5.415665ms 2000 29.961344ms (5.5X)
1000 22.164624ms 2000 433.387975ms (19.6X)


goroutine 1 [running]:
main.checkLinear(0x4d8124, 0x8, 0x3e8, 0x4df5f0)
	/tmp/workdir-host-illumos-amd64-joyent/go/test/locklinear.go:73 +0x590
main.main()
	/tmp/workdir-host-illumos-amd64-joyent/go/test/locklinear.go:134 +0x79
exit status 2

FAIL	locklinear.go	11.857s
```

See previously #19276.

**Comment by rsc** [comment] 2019-10-08 15:19
Is the machine just overloaded?

**Comment by rsc** [comment] 2019-10-08 15:23
The timings for 1000 ops being all over the map - 42ms, 13ms, 9ms, 5ms, 22ms - is a sign that the machine is just overloaded. Maybe if the test can't even get something consistent for 1000 ops it should just skip itself.

**Comment by bcmills** [comment] 2021-01-07 16:45
This turns out not to be builder-specific — it has failed on a number of slowish builders.
Either the test is making unwarranted assumptions, or there is a deeper problem in the behavior under test.

[2021-01-06T18:41:54-4c668b2/linux-ppc64-buildlet](https://build.golang.org/log/87f649fdeeadc174629e75f5093ee8a73e33e42a)
[2020-01-07T18:46:29-52a9210/linux-arm](https://build.golang.org/log/bbafb04b96cc0be5fdfb3f25687043c12866fe5a)
[2019-10-17T16:30:15-2449444/solaris-amd64-oraclerel](https://build.golang.org/log/424447e80445199805945d899fe8fbffe5d31551)
[2019-10-05T10:39:30-11b3368/illumos-amd64-joyent](https://build.golang.org/log/d3aca1d198ef66f7a053c525794522f8a83f8ff4)
[2019-10-03T18:18:14-5fe3b49/solaris-amd64-oraclerel](https://build.golang.org/log/7056cb841e6b91f41babc77ecfaf338720c67b1c)
[2019-09-11T00:56:39-8ef6d6a/solaris-amd64-oraclerel](https://build.golang.org/log/bffc9a3acd08a736aefe46172cdc0426a7e602b5)
[2019-08-28T20:42:48-9859f6b/solaris-amd64-smartosbuildlet](https://build.golang.org/log/62c7e53570884cdd74be5b23a04ec783f3949a62)
[2019-07-23T12:39:03-e8c7e63/illumos-amd64-joyent](https://build.golang.org/log/ed84425c220c1b940286e35f3e417537f4e302b4)
[2019-07-08T13:20:23-ddc8439/illumos-amd64-joyent](https://build.golang.org/log/b60463ada3a04bbfdb7f714e54d819176e60a833)
[2019-06-26T19:11:12-4047f01/solaris-amd64-smartosbuildlet](https://build.golang.org/log/781081b48ffc38be48bebcdcc49a953dc3189366)
[2019-05-09T18:02:19-c514071/solaris-amd64-smartosbuildlet](https://build.golang.org/log/5d6c0947fcdec9b4f754af4d8184220d69c8eafe)

**Comment by bcmills** [comment] 2021-01-07 16:46
CC @aclements

**Comment by bcmills** [comment] 2021-04-23 02:28
[2021-04-22T21:23:59-f7afdfd/windows-386-2008](https://build.golang.org/log/104753f9b8bbb0e580494df9bdfedfa1e4a5f4fd)
[2021-04-12T15:17:33-117b1c8/illumos-amd64](https://build.golang.org/log/dd79bc5b5b6705c9adbb1f17f4bb99506bbaa9f8)
[2021-03-13T11:26:35-83e79c7/linux-arm](https://build.golang.org/log/a514079111db7581ae0b6135d951607f9054101d)

**Comment by bcmills** [comment] 2022-01-12 14:50
`greplogs --dashboard -md -l -e 'lockmany: too slow' --since=2021-04-23`

[2021-09-22T15:46:33-5ee32ff/solaris-amd64-oraclerel](https://build.golang.org/log/2238672032e1b42571fa9361a63e27014e6be8b5)
[2021-06-04T17:21:49-3a9d906/illumos-amd64](https://build.golang.org/log/46ebd34fd735fcfcaad497bf6c3974033c6a2d22)

**Comment by aclements** [comment] 2022-01-14 17:55
I did a large number of all.bash runs on FreeBSD for other purposes, but got a fair number of locklinear failures in the process.

On freebsd-amd64-12_2 10 of 898 runs failed in locklinear (1.1%). On freebsd-amd64-12_3, 6 of 912 runs failed in locklinear (0.66%). Those are fairly different rates given the number of runs, which I find a little surprising, but I think give us a sense of the ambient failure rate of this test when it's run in the context of everything else all.bash does.

**Comment by bcmills** [comment] 2022-02-15 16:17
Given that this test won't be run by users as part of `go test all` I don't think this needs to block the Go 1.18 release, but since it seems to affect first-class ports I do think we should either fix it or skip / remove it for 1.19.

(That is: we should make a decision as to whether the test is important enough to deflake. If it is, we should deflake it; otherwise, we should suppress the flakes.)

**Comment by heschi** [comment] 2022-05-11 16:08
cc @golang/runtime

**Comment by mknyszek** [comment] 2022-05-27 20:26
I think the test *is* useful, i.e. verifying that the asymptotic behavior of contended `Mutex`es. Currently, when it does fail, it has to fail the check at least 5 times in a row, which at face value seems like a high bar.

Looking more closely at the test it already has a few workarounds for flakiness that appear to have been added in the few months after it was landed. There's an inherent flakiness to this kind of test, especially since it calls `runtime.Gosched`.

One thing that jumps out at me, though, is that the test doesn't ever block to clean up goroutines after each attempt, so theoretically it's possible that one failure could exacerbate subsequent ones if the problem is transient oversubscription (especially given the `runtime.Gosched` calls; the test creates 1000 or 2000 goroutines each time it tries). 5 is still a lot of consecutive failures for that to be the only culprit though.

Another thing that seems kind of suspicious is that `lockone` generates contention on `locks[1]` and `locks[offset]`, but `lockmany` generates contention on `locks[1]` and `locks[0]`. `offset` is 251 which matches the size of the runtime's semaphore table. This table is indexed by the lock's 8-byte word address. Based on this information, neither `locks[offset]` nor `locks[0]` collide with `locks[1]`, which is likely intentional. However, `locks[0]` and `locks[1]` are definitely in the same cache line, whereas `locks[1]` and `locks[offset]` are not, and given that `offset` is prime, it's very unlikely that there's some kind of false sharing going on. Meanwhile, `locks[0]` and `locks[1]` absolutely do share a cache line so the lock fast path will contend in cache coherency. Note that this test uses `RWMutex` values which are 24 bytes in size. (This might be an oversight? The test doesn't use the read-lock functionality at all, meanwhile a `Mutex` is exactly 8 bytes in size.)

Maybe it's possible that on these slow platforms there's some kind of cache coherency breakdown? It's hard for me to tell whether the `0` vs. `offset` is intentional. There aren't any comments in the review (https://go-review.googlesource.com/c/go/+/37103) pointing out the difference, the commit message doesn't discuss it, and the test file itself doesn't have any explanation.

I'm inclined to do two things to make this test more robust:
1. Block on cleanup after obtaining the time-to-run data. Maybe also exclude the setup time from the timing call (just to narrow the scope of the test a bit more).
2. Use `offset` instead of `0` in `lockmany`.

And then we wait to see if it fails again. Does this seem reasonable? If we don't want to perturb things too much, we can just do (2).

**Comment by mknyszek** [comment] 2022-06-01 17:27
It occurs to me that I never stated this plainly: I don't think this failure represents a real regression. I think it's very clear from all my runs that the invariant it intends to check is generally upheld, and I also don't see some significant regression here in terms of how often it's upheld. What I understand this issue to be about is a flaky test and trying to make it less flaky.

**Comment by bcmills** [comment] 2022-06-01 18:09
> What I understand this issue to be about is a flaky test and trying to make it less flaky.

I agree, and I think the current labels (`okay-after-beta1`, `Testing`) also reflect that.

But I also think we do need to make a decision about what information the test is providing. If these `lockmany: too slow` failures aren't providing us with information about a regression, then I don't want to see them in TryBot runs or post-commit test runs, and I don't think users who run `all.bash` will want to see them either. (Note that our [installing from source](https://go.dev/doc/install/source#install) instructions currently instruct users to run `all.bash`.)

So I do think the action here is to decide: (a) is the information provided by the test worth the cost to deflake? and (b) if so, how should we deflake it? (If the answer to (a) is “no”, then we can just delete it instead. 😅)

**Comment by bcmills** [comment] 2022-06-01 18:19
Looking at the test body and the most recent `windows/386` failure in the comments, I see:
```
# go run run.go -G=3 locklinear.go
exit status 2
panic: lockmany: too slow: 1000 ops: 6.836ms; 2000 ops: 403.3203ms

1000 8.7891ms 2000 32.2265ms (3.7X)
1000 21.4844ms 2000 32.2266ms (1.5X)
1000 24.414ms 2000 10.7422ms (0.4X)
1000 19.5313ms 2000 14.6484ms (0.7X)
1000 18.5547ms 2000 16.6016ms (0.9X)
1000 7.8125ms 2000 41.9921ms (5.4X)
1000 4.8829ms 2000 26.3671ms (5.4X)
1000 6.836ms 2000 403.3203ms (59.0X)
```

That looks like this arbitrary-timeout cutoff:
https://cs.opensource.google/go/go/+/master:test/locklinear.go;l=68;drc=97677273532cf1a4e8b181c242d89c0be8c92bb6

In addition to that cutoff, there is the N=5 consecutive-failure cutoff (which results in failure), and an additional “5 inversions means too noisy” cutoff (https://cs.opensource.google/go/go/+/master:test/locklinear.go;l=54-57;drc=97677273532cf1a4e8b181c242d89c0be8c92bb6).

But the test doesn't actually increase `n` for the failures before the fifth one, so it seems to me that the test isn't reducing its own noise and _is_ failing if it happens to get a single unusually-slow run on the fifth-or-later attempt.

So I wonder: would it make sense to increase `n` on every failure instead of just the 5th-or-later (to start raising the signal-to-noise ratio earlier), and perhaps also remove or substantially increase the arbitrary 400ms cutoff (to avoid failing the test if there is a single outlier)?

**Comment by aclements** [comment] 2022-06-08 19:02
@mknyszek , I think you've got the right idea with a t-test here. In particular, don't have any retries, and instead just collect several samples from both the less and more contended scenarios to build up two distributions, and then make a decision based on those distributions. I haven't looked at your code closely, but your commit message describes what I think is the right approach.

I do worry that picking a P-value threshold is effectively picking how flaky we're willing to allow this test to be, but nevertheless I think this is worth a shot. It's at least a lot more principled.

Repeating the significance test if it fails sort of defeats the purpose of a significance test, so I don't think we should do that.

Increasing n might help to smooth out the results, but that's basically just baking in a mean over a larger sample period. In general, statistical analysis should do better if we give it more samples with less pre-filtering, so it has as much information as possible.

**Closed** 2022-06-13 20:16 UTC
Labels: Testing, NeedsInvestigation, release-blocker
