### ISSUE TITLE
Boolean literal are allowed to be used as variable names

### ISSUE THREAD

**Issue by Raghav-196** [golang/go#36627] opened 2020-01-17 13:12 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Not sure

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/raghav/.cache/go-build"
GOENV="/home/raghav/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/raghav/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build172516599=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
package main

import "fmt"

var true = false

func main() {
	if true == false {
		fmt.Println("foo!!")
	}

	if true {
		fmt.Println("bar!!")
	}
}

</pre>

### What did you expect to see?

Compilation Error

### What did you see instead?

Output: 
<pre>
foo!!
</pre>

**Comment by Raghav-196** [comment] 2020-01-17 13:17
I'm completely new to Golang and was just trying the pattern matching support in this language, but accidentally ended up with this.
So I don't even know that whether this is a bug or intentional behaviour, and in case it is then what is the use case.

**Comment by bontibon** [comment] 2020-01-17 13:40
Not an issue. See #18193.

**Comment by ALTree** [comment] 2020-01-17 14:17
As @bontibon said, this is working as intended. Closing here.

**Closed by ALTree** 2020-01-17 14:17 UTC
