### ISSUE TITLE
cmd/go: running `go generate` with go tool with _same_ GOROOT fails

### ISSUE THREAD

**Issue by Dentrax** [golang/go#43369] opened 2020-12-24 14:44 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, commit: b116404444addc69b5ec987a2a64b92d4956eab0

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/furkan/Library/Caches/go-build"
GOENV="/Users/furkan/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/furkan/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/furkan/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/Cellar/go/1.15.5/libexec"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nq/vxjjn3311fg4q263qsxrghpcpzgp66/T/go-build556373901=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. Clone the fresh Go repo (`$ pwd #/Users/furkan.turkal/go/src/goroot`)
2. `$ cd src/cmd/compile/internal/gc`
3. Edit `syntax.go` to add a new AST node type `OFOOBAR`
4. Run `$ go generate`

### What did you expect to see?

Expected `op_string.go` to be updated with the new node type.

`$ go generate syntax.go`

No errors, but the generated `op_string.go` does not have the new node type.

### What did you see instead?

Expected the new node type to appear in `op_string.go` after running `$ go generate`

Ref: #32724
CC: @bcmills @ianlancetaylor

**Comment by Dentrax** [comment] 2020-12-24 14:57
A _workaround?_ to fix this problem is:

```bash
$ cd ./src
$ ./make.bash
$ ../bin/go generate -v . # this usage not works at all
$ ../bin/go generate ./cmd/compile/internal/gc/syntax.go # this works well
```

**Comment by mengzhuo** [comment] 2020-12-25 03:39
`go generate` without filename will using `go list` which depends on GOROOT.
You can overwrite GOROOT to your Go source path than generate

`GOROOT=$HOME/goroot ../bin/go generate`

CC @matloob 
Should we make an exception on Go source path?

**Comment by dmitshur** [comment] 2020-12-30 17:11
I see you mentioned #32724, but how is this issue different from that one? I see the title is different, but the steps in "What did you do?" seem to be the same.

Also, what does `which go` print?

**Comment by dmitshur** [comment] 2020-12-30 17:13
Could it be that you're running into #42563 and `/Users/furkan/go/src/goroot/bin` isn't in your $PATH?

**Comment by Dentrax** [comment] 2021-01-07 06:28
`which go` prints `/usr/local/bin/go`, in `go env` i see: `GOROOT="/usr/local/Cellar/go/1.15.5/libexec"` and `GOPATH="/Users/furkan/go"`

`PATH=:/Users/furkan/go/bin:/usr/local/go/bin:`

I tried with `/Users/furkan/go/src/goroot/bin/go generate` and nothing changed. I do not know exactly what part I missed.  @dmitshur

**Comment by jayconrod** [comment] 2021-01-08 21:50
If `go env GOROOT` is showing a different directory than the development `GOROOT` directory you're running in, then this is a duplicate of #32724. I'll close this issue.

Some things that might be going wrong:

* Your `PATH` shouldn't start or end with `:`.
* Your `PATH` should include `$GOROOT/bin`. In this case, that sounds like `/Users/furkan/go/src/goroot/bin`.
* Don't put `GOROOT` inside `GOPATH`. Put it somewhere else like `/Users/furkan/goroot`.

**Closed by jayconrod** 2021-01-08 21:50 UTC
Labels: GoCommand, NeedsInvestigation, WaitingForInfo
