### ISSUE TITLE
'go get' fails with panic

### ISSUE THREAD

**Issue by unifyproxy** [golang/go#34975] opened 2019-10-18 01:32 UTC
### What version of Go are you using (`go version`)?

<pre>
➜  ~ go version
go version go1.13.1 linux/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
➜  ~ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jason/.cache/go-build"
GOENV="/home/jason/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jason/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build122295695=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
➜  ~ go get github.com/v2ray/v2ray-core
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x889f7d]

goroutine 1 [running]:
cmd/go/internal/get.metaImportsForPrefix.func2(0x0, 0x0, 0xb27d40, 0xc00012ccf0)
	/usr/lib/go/src/cmd/go/internal/get/vcs.go:907 +0x29d
internal/singleflight.(*Group).doCall(0xeaaf80, 0xc000348140, 0xc000192280, 0xe, 0xc00015d2f8)
	/usr/lib/go/src/internal/singleflight/singleflight.go:95 +0x2e
internal/singleflight.(*Group).Do(0xeaaf80, 0xc000192280, 0xe, 0xc00015d2f8, 0x0, 0xc00012c7e0, 0x0, 0x0, 0xc000026ba1)
	/usr/lib/go/src/internal/singleflight/singleflight.go:63 +0x1ba
cmd/go/internal/get.metaImportsForPrefix(0xc000192280, 0xe, 0x0, 0x0, 0x15, 0xc000192280, 0xe, 0xc00019228f, 0x3, 0xc000192293)
	/usr/lib/go/src/cmd/go/internal/get/vcs.go:893 +0xf1
cmd/go/internal/get.repoRootForImportDynamic(0xc000026ba1, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/cmd/go/internal/get/vcs.go:827 +0x665
cmd/go/internal/get.RepoRootForImportPath(0xc000026ba1, 0x15, 0x0, 0x0, 0xffffffffffffffff, 0xc00015d6c0, 0xc00015d838)
	/usr/lib/go/src/cmd/go/internal/get/vcs.go:662 +0x345
cmd/go/internal/get.downloadPackage(0xc0003ad200, 0xc0000f3290, 0xc000026ba1)
	/usr/lib/go/src/cmd/go/internal/get/get.go:448 +0x1568
cmd/go/internal/get.download(0xc000026ba1, 0x15, 0xc0000aa900, 0xc00015dd78, 0x0)
	/usr/lib/go/src/cmd/go/internal/get/get.go:275 +0xd26
cmd/go/internal/get.download(0x7fff559805d9, 0x1b, 0x0, 0xc00015dd78, 0x0)
	/usr/lib/go/src/cmd/go/internal/get/get.go:371 +0x718
cmd/go/internal/get.runGet(0xea2a60, 0xc0000201a0, 0x1, 0x1)
	/usr/lib/go/src/cmd/go/internal/get/get.go:162 +0x170
main.main()
	/usr/lib/go/src/cmd/go/main.go:189 +0x57f

```

**Comment by lsytj0413** [comment] 2019-10-18 01:54
see https://github.com/golang/go/issues/34049

**Comment by agnivade** [comment] 2019-10-18 03:55
Duplicate of https://github.com/golang/go/issues/34049.

**Closed by agnivade** 2019-10-18 03:55 UTC
