### ISSUE TITLE
x/tools/internal/lsp: we should respect the contentFormat capabilities

### ISSUE THREAD

**Issue by ianthehat** [golang/go#31238] opened 2019-04-03 20:15 UTC
At the moment things like hover always send back markdown content, even if the client cannot support them.
This came up when implementing the `gopls query definition` command line, which wants the hover in plain text and has to strip off the markdown formatting by hand.

**Comment by stamblerre** [comment] 2019-04-17 03:50
Duplicate of #31078

**Closed by stamblerre** 2019-04-17 03:50 UTC
Labels: FeatureRequest, gopls
