### ISSUE TITLE
x/build: broken builder (FAILED: not a Git repo)

### ISSUE THREAD

**Issue by tzneal** [golang/go#20036] opened 2017-04-19 12:17 UTC
A change I made that was merged into master ( dc44441) , resulted in a failed build on darwin-amd64-10_8 that I had never seen before:

https://build.golang.org/log/2004e9acdc91c824ee11d884315616232d1f46c8

```
darwin-amd64-10_8 at dc444418d919b72f7744a521cc898252f3f355df

:: Running /var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/make.bash with args ["/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src/make.bash"] and env ["TERM_PROGRAM=Apple_Terminal" "TERM=xterm-256color" "SHELL=/bin/bash" "TMPDIR=/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/" "Apple_PubSub_Socket_Render=/tmp/launch-Ou6u40/Render" "TERM_PROGRAM_VERSION=309" "TERM_SESSION_ID=4A55C283-E1E7-4589-A535-377B9747351C" "USER=gopher" "COMMAND_MODE=unix2003" "SSH_AUTH_SOCK=/tmp/launch-Am5hb1/Listeners" "__CF_USER_TEXT_ENCODING=0x1F5:0:0" "Apple_Ubiquity_Message=/tmp/launch-YmFHRu/Apple_Ubiquity_Message" "PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin" "GO_BUILDER_ENV=macstadium_vm" "PWD=/Users/gopher" "LANG=en_US.UTF-8" "SHLVL=3" "HOME=/Users/gopher" "LOGNAME=gopher" "SECURITYSESSIONID=186a4" "_=./buildlet" "GOROOT_BOOTSTRAP=/Users/gopher/go1.4" "WORKDIR=/var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir" "GO_BUILDER_NAME=darwin-amd64-10_8" "GOBIN="] in dir /var/folders/_m/7l4dhkzx3rg5v97tqbz5wkmr0000gn/T/workdir/go/src

##### Building Go bootstrap tool.
cmd/dist

go tool dist: FAILED: not a Git repo; must put a VERSION file in $GOROOT

build failed: make script failed: exit status 2
```

/cc @bradfitz

**Comment by bradfitz** [comment] 2017-04-19 15:24
Uh, bizarre. Never seen that. The build system does write a dummy VERSION file in $GOROOT before each build starts. Maybe it failed and we didn't catch an error? Maybe the filesystem crapped itself? No clue.

**Comment by zhexuany** [comment] 2017-04-19 16:31
Seems to me this was caused by the failure of `isGitRepo` in build.go https://github.com/golang/go/blob/master/src/cmd/dist/build.go#L309

I did compelling on my machine: everything is passed.

**Comment by bradfitz** [comment] 2017-04-19 16:36
@zhexuany, yes, that's where the error came from, but it shouldn't have gotten that far. It should've stopped at the VERSION check a few lines up from there.

**Comment by zhexuany** [comment] 2017-04-19 16:44
@bradfitz I second your opinion. I reset commit history on  `dc44441`. And then execute `./make.bash`. Everything works just fine. `findgoversion()` should return before even execute `isGitRepo()`. I am trying setting `goroot` to a git repo and see what is the result.

**Comment by bradfitz** [comment] 2017-12-06 22:56
I'm going to close this since we've never seen it again. Also, I'm changing the Macs to nuke themselves every build, so if this was filesystem corruption over time, that won't be an issue anymore.

**Closed by bradfitz** 2017-12-06 22:56 UTC
Labels: Builders, HelpWanted, NeedsInvestigation
