### ISSUE TITLE
runtime: SIGABRT during IP lookup on macOS 11.0 Beta (20A5374g)

### ISSUE THREAD

**Issue by blixt** [golang/go#41572] opened 2020-09-23 10:44 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
Version: go version go1.15.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=“”
GOARCH=“amd64"
GOBIN=“”
GOCACHE=“/Users/animify/Library/Caches/go-build”
GOENV=“/Users/animify/Library/Application Support/go/env”
GOEXE=“”
GOFLAGS=“”
GOHOSTARCH=“amd64"
GOHOSTOS=“darwin”
GOINSECURE=“”
GOMODCACHE=“/Users/animify/go/pkg/mod”
GONOPROXY=“”
GONOSUMDB=“”
GOOS=“darwin”
GOPATH=“/Users/animify/go”
GOPRIVATE=“”
GOPROXY=“https://proxy.golang.org,direct”
GOROOT=“/usr/local/go”
GOSUMDB=“sum.golang.org”
GOTMPDIR=“”
GOTOOLDIR=“/usr/local/go/pkg/tool/darwin_amd64”
GCCGO=“gccgo”
AR=“ar”
CC=“clang”
CXX=“clang++”
CGO_ENABLED=“1"
GOMOD=“”
CGO_CFLAGS=“-g -O2"
CGO_CPPFLAGS=“”
CGO_CXXFLAGS=“-g -O2"
CGO_FFLAGS=“-g -O2”
CGO_LDFLAGS=“-g -O2"
PKG_CONFIG=“pkg-config”
GOGCCFLAGS=“-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3n/xfnz6_0939390qhfbp_blkym0000gn/T/go-build514944282=/tmp/go-build -gno-record-gcc-switches -fno-common”
</pre></details>

### What did you do?

The code is performing an HTTPS request using the standard HTTP library and immediately crashes with `SIGABRT`.

### What did you expect to see?

Executable runs successfully.

### What did you see instead?

Expand section below to see the full output.

<details><summary>Full session / trace output</summary><br><pre>
$ make dev-server
cd src/server && GOPRIVATE=github.com/framer go get
cd src/server && go build -race -o /Users/animify/Documents/GitHub/FramerWeb/FramerWeb-dev
./FramerWeb-dev
DBG[2020-09-23T09:22:10Z] [registryassets] Enqueued request for framer@latest
DBG[2020-09-23T09:22:10Z] [registryassets] Requesting package info from https://registry.yarnpkg.com/framer (needsSession: false)...
objc[23954]: Attempt to use unknown class 0x7fff82290c48.
SIGABRT: abort
PC=0x7fff202707a2 m=3 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff202707a2
stack: frame={sp:0x70000d635d88, fp:0x0} stack=[0x70000d5b7350,0x70000d636f50)
000070000d635c88:  0000000000000002  00000000036d9410
000070000d635c98:  00000000036d9410  00000000036d5000
000070000d635ca8:  00000000036db208  000070000d635d10
000070000d635cb8:  00007fff204d2706  000070000d635cf0
000070000d635cc8:  f687c000c0001002  00007fff8229ffff
000070000d635cd8:  0000000000000030  0000000400000000
000070000d635ce8:  000000000000002d  000000000000002d
000070000d635cf8:  0000000000000000  00000000036d5000
000070000d635d08:  00007fff822bd000  000070000d635d40
000070000d635d18:  00007fff204d2584  00007fff204d254d
000070000d635d28:  000000000000002d  0000000000000001
000070000d635d38:  00007fff822bd000  000070000d635d80
000070000d635d48:  00007fff204ecdfe  000000000000002c
000070000d635d58:  000000000000002d  00007ffffffffff8
000070000d635d68:  0000000000000003  0000600002c00000
000070000d635d78:  0000000000000000  000070000d635db0
000070000d635d88: <00007fff202721e9  0000000000000000
000070000d635d98:  000000200d635df0  0000600002c00000
000070000d635da8:  000070000d635df0  00007ffffffffff8
000070000d635db8:  0000000000000003  0000000000000080
000070000d635dc8:  0000000000000001  000070000d635de0
000070000d635dd8:  00007fff20272199  000070000d635e20
000070000d635de8:  00007fff202d8b6a  0000600002c00080
000070000d635df8:  0000000000000000  0000600002c00000
000070000d635e08:  0000600003304000  00007fff82290c48
000070000d635e18:  0000000080080001  000070000d635f00
000070000d635e28:  00007fff202d8af8  0000003000000010
000070000d635e38:  000070000d635f10  000070000d635e50
000070000d635e48:  0000000000000000  0000000000000000
000070000d635e58:  00007fff82290c48  00007fff82290c48
000070000d635e68:  0000000000000001  00000000ffffffff
000070000d635e78:  00000000000007fb  0000000000000000
runtime: unknown pc 0x7fff202707a2
stack: frame={sp:0x70000d635d88, fp:0x0} stack=[0x70000d5b7350,0x70000d636f50)
000070000d635c88:  0000000000000002  00000000036d9410
000070000d635c98:  00000000036d9410  00000000036d5000
000070000d635ca8:  00000000036db208  000070000d635d10
000070000d635cb8:  00007fff204d2706  000070000d635cf0
000070000d635cc8:  f687c000c0001002  00007fff8229ffff
000070000d635cd8:  0000000000000030  0000000400000000
000070000d635ce8:  000000000000002d  000000000000002d
000070000d635cf8:  0000000000000000  00000000036d5000
000070000d635d08:  00007fff822bd000  000070000d635d40
000070000d635d18:  00007fff204d2584  00007fff204d254d
000070000d635d28:  000000000000002d  0000000000000001
000070000d635d38:  00007fff822bd000  000070000d635d80
000070000d635d48:  00007fff204ecdfe  000000000000002c
000070000d635d58:  000000000000002d  00007ffffffffff8
000070000d635d68:  0000000000000003  0000600002c00000
000070000d635d78:  0000000000000000  000070000d635db0
000070000d635d88: <00007fff202721e9  0000000000000000
000070000d635d98:  000000200d635df0  0000600002c00000
000070000d635da8:  000070000d635df0  00007ffffffffff8
000070000d635db8:  0000000000000003  0000000000000080
000070000d635dc8:  0000000000000001  000070000d635de0
000070000d635dd8:  00007fff20272199  000070000d635e20
000070000d635de8:  00007fff202d8b6a  0000600002c00080
000070000d635df8:  0000000000000000  0000600002c00000
000070000d635e08:  0000600003304000  00007fff82290c48
000070000d635e18:  0000000080080001  000070000d635f00
000070000d635e28:  00007fff202d8af8  0000003000000010
000070000d635e38:  000070000d635f10  000070000d635e50
000070000d635e48:  0000000000000000  0000000000000000
000070000d635e58:  00007fff82290c48  00007fff82290c48
000070000d635e68:  0000000000000001  00000000ffffffff
000070000d635e78:  00000000000007fb  0000000000000000

goroutine 59 [syscall]:
runtime.cgocall(0x1001140, 0xc000590ce8, 0xc0000b81d8)
        /usr/local/go/src/runtime/cgocall.go:133 +0x7a fp=0xc000590cb8 sp=0xc000590c80 pc=0x10458da
net._C2func_getaddrinfo(0xc000456d20, 0x0, 0xc00025df20, 0xc0000b81d8, 0xc000000000, 0x0, 0x0)
        _cgo_gotypes.go:100 +0x73 fp=0xc000590ce8 sp=0xc000590cb8 pc=0x13f9ef3
net.cgoLookupIPCNAME.func1(0xc000456d20, 0x15, 0x15, 0xc00025df20, 0xc0000b81d8, 0x13fec9f, 0x2409120, 0xc00046d740)
        /usr/local/go/src/net/cgo_unix.go:161 +0xd3 fp=0xc000590d48 sp=0xc000590ce8 pc=0x14010f3
net.cgoLookupIPCNAME(0x2153e5e, 0x3, 0xc000382ca0, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/cgo_unix.go:161 +0x259 fp=0xc000590f18 sp=0xc000590d48 pc=0x13fbe79
net.cgoIPLookup(0xc0000a9680, 0x2153e5e, 0x3, 0xc000382ca0, 0x14)
        /usr/local/go/src/net/cgo_unix.go:218 +0x7d fp=0xc000590fb8 sp=0xc000590f18 pc=0x13fc95d
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000590fc0 sp=0xc000590fb8 pc=0x10b3a81
created by net.cgoLookupIP
        /usr/local/go/src/net/cgo_unix.go:228 +0xde

goroutine 1 [chan receive, locked to thread]:
text/template/parse.(*lexer).nextItem(...)
        /usr/local/go/src/text/template/parse/lex.go:195
text/template/parse.(*Tree).peek(...)
        /usr/local/go/src/text/template/parse/parse.go:95
text/template/parse.(*Tree).parse(0xc00040c000)
        /usr/local/go/src/text/template/parse/parse.go:272 +0x1407
text/template/parse.(*Tree).Parse(0xc00040c000, 0xc000400000, 0x374, 0x0, 0x0, 0x0, 0x0, 0xc000404060, 0xc00040a000, 0x2, ...)
        /usr/local/go/src/text/template/parse/parse.go:225 +0x38a
text/template/parse.Parse(0xc000456c0a, 0xa, 0xc000400000, 0x374, 0x0, 0x0, 0x0, 0x0, 0xc00040a000, 0x2, ...)
        /usr/local/go/src/text/template/parse/parse.go:55 +0x1ea
text/template.(*Template).Parse(0xc000402000, 0xc000400000, 0x374, 0xc0000a6550, 0xc00049fb28, 0x108a80a)
        /usr/local/go/src/text/template/template.go:201 +0xb29
html/template.(*Template).Parse(0xc000404000, 0xc000400000, 0x374, 0x0, 0x0, 0x0)
        /usr/local/go/src/html/template/template.go:189 +0xd4
html/template.parseFiles(0xc00025d6e0, 0xc0000c1a00, 0x5, 0x8, 0x8, 0x0, 0x0)
        /usr/local/go/src/html/template/template.go:435 +0x20f
html/template.parseGlob(0xc00025d6e0, 0x2161a28, 0x10, 0x7, 0xc00049feb0, 0x0)
        /usr/local/go/src/html/template/template.go:482 +0x194
html/template.(*Template).ParseGlob(...)
        /usr/local/go/src/html/template/template.go:467
github.com/framer/FramerWeb/framer.init.0()
        /Users/animify/Documents/GitHub/FramerWeb/src/server/framer/templates.go:37 +0x448

goroutine 18 [select]:
github.com/patrickmn/go-cache.(*janitor).Run(0xc0002b5430, 0xc00046cec0)
        /Users/animify/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0x15e
created by github.com/patrickmn/go-cache.runJanitor
        /Users/animify/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0x106

goroutine 19 [select]:
github.com/patrickmn/go-cache.(*janitor).Run(0xc0002b5440, 0xc00046cf00)
        /Users/animify/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0x15e
created by github.com/patrickmn/go-cache.runJanitor
        /Users/animify/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0x106

goroutine 13 [select]:
net/http.(*Transport).getConn(0x2a19f40, 0xc00046d6c0, 0x0, 0xc0001a8d80, 0x5, 0xc000382ca0, 0x18, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:1347 +0x9be
net/http.(*Transport).roundTrip(0x2a19f40, 0xc0000fe700, 0x10b5142, 0x108b3b4, 0x203000)
        /usr/local/go/src/net/http/transport.go:569 +0xaa5
net/http.(*Transport).RoundTrip(0x2a19f40, 0xc0000fe700, 0x2a19f40, 0x0, 0x0)
        /usr/local/go/src/net/http/roundtrip.go:17 +0x47
net/http.send(0xc0000fe700, 0x23f2820, 0x2a19f40, 0x0, 0x0, 0x0, 0x1092660, 0x0, 0xc0000f74a8, 0x1092845)
        /usr/local/go/src/net/http/client.go:252 +0x6db
net/http.(*Client).send(0xc00038c2d0, 0xc0000fe700, 0x0, 0x0, 0x0, 0xc0000ea048, 0x0, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:176 +0x1d6
net/http.(*Client).do(0xc00038c2d0, 0xc0000fe700, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:718 +0x2d8
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:586
github.com/framer/FramerWeb/registryassets.doJSON(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000fe700, 0x1f8be60, 0xc0000e3d20, 0x0, ...)
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/json.go:12 +0xd4
github.com/framer/FramerWeb/registryassets.manager.Start.func1(0xc0000a9140, 0xa, 0xc0000a90e0, 0xc00003c2a0, 0xc00025d230, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:111 +0x81f
created by github.com/framer/FramerWeb/registryassets.manager.Start
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:71 +0x145

goroutine 14 [chan receive]:
github.com/framer/FramerWeb/registryassets.manager.Start.func2(0xc0000a9140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0xc0000a90e0, 0xc00003c2a0)
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:195 +0x91
created by github.com/framer/FramerWeb/registryassets.manager.Start
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:194 +0x1e9

goroutine 15 [chan receive]:
github.com/framer/FramerWeb/registryassets.manager.Start.func2(0xc0000a9140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0xc0000a90e0, 0xc00003c2a0)
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:195 +0x91
created by github.com/framer/FramerWeb/registryassets.manager.Start
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:194 +0x1e9

goroutine 16 [chan receive]:
github.com/framer/FramerWeb/registryassets.manager.Start.func2(0xc0000a9140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0xc0000a90e0, 0xc00003c2a0)
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:195 +0x91
created by github.com/framer/FramerWeb/registryassets.manager.Start
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:194 +0x1e9

goroutine 50 [chan receive]:
github.com/framer/FramerWeb/registryassets.manager.Start.func2(0xc0000a9140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0xc0000a90e0, 0xc00003c2a0)
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:195 +0x91
created by github.com/framer/FramerWeb/registryassets.manager.Start
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:194 +0x1e9

goroutine 51 [chan receive]:
github.com/framer/FramerWeb/registryassets.manager.Start.func2(0xc0000a9140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0xc0000a90e0, 0xc00003c2a0)
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:195 +0x91
created by github.com/framer/FramerWeb/registryassets.manager.Start
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:194 +0x1e9

goroutine 52 [chan receive]:
github.com/framer/FramerWeb/registryassets.manager.Start.func2(0xc0000a9140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0xc0000a90e0, 0xc00003c2a0)
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:195 +0x91
created by github.com/framer/FramerWeb/registryassets.manager.Start
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:194 +0x1e9

goroutine 53 [chan receive]:
github.com/framer/FramerWeb/registryassets.manager.Start.func2(0xc0000a9140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0xc0000a90e0, 0xc00003c2a0)
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:195 +0x91
created by github.com/framer/FramerWeb/registryassets.manager.Start
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:194 +0x1e9

goroutine 54 [chan receive]:
github.com/framer/FramerWeb/registryassets.manager.Start.func2(0xc0000a9140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0xc0000a90e0, 0xc00003c2a0)
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:195 +0x91
created by github.com/framer/FramerWeb/registryassets.manager.Start
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:194 +0x1e9

goroutine 55 [chan receive]:
github.com/framer/FramerWeb/registryassets.manager.Start.func2(0xc0000a9140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0xc0000a90e0, 0xc00003c2a0)
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:195 +0x91
created by github.com/framer/FramerWeb/registryassets.manager.Start
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:194 +0x1e9

goroutine 56 [chan receive]:
github.com/framer/FramerWeb/registryassets.manager.Start.func2(0xc0000a9140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0xc0000a90e0, 0xc00003c2a0)
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:195 +0x91
created by github.com/framer/FramerWeb/registryassets.manager.Start
        /Users/animify/Documents/GitHub/FramerWeb/src/server/registryassets/manager.go:194 +0x1e9

goroutine 41 [select]:
net.(*Resolver).lookupIPAddr(0x2a262a0, 0x24091a0, 0xc000124d20, 0x2153e5e, 0x3, 0xc000382ca0, 0x14, 0x1bb, 0x0, 0x0, ...)
        /usr/local/go/src/net/lookup.go:299 +0x8cc
net.(*Resolver).internetAddrList(0x2a262a0, 0x24091a0, 0xc000124d20, 0x2153e5e, 0x3, 0xc000382ca0, 0x18, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/ipsock.go:280 +0x6dc
net.(*Resolver).resolveAddrList(0x2a262a0, 0x24091a0, 0xc000124d20, 0x21544fa, 0x4, 0x2153e5e, 0x3, 0xc000382ca0, 0x18, 0x0, ...)
        /usr/local/go/src/net/dial.go:221 +0x5af
net.(*Dialer).DialContext(0xc0001241e0, 0x24091a0, 0xc000124d20, 0x2153e5e, 0x3, 0xc000382ca0, 0x18, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dial.go:403 +0x319
net/http.(*Transport).dial(0x2a19f40, 0x2409160, 0xc0000360a8, 0x2153e5e, 0x3, 0xc000382ca0, 0x18, 0x0, 0x108a945, 0x100db50, ...)
        /usr/local/go/src/net/http/transport.go:1141 +0x335
net/http.(*Transport).dialConn(0x2a19f40, 0x2409160, 0xc0000360a8, 0x0, 0xc0001a8d80, 0x5, 0xc000382ca0, 0x18, 0x0, 0xc00038e900, ...)
        /usr/local/go/src/net/http/transport.go:1575 +0x2b3f
net/http.(*Transport).dialConnFor(0x2a19f40, 0xc0000ee370)
        /usr/local/go/src/net/http/transport.go:1421 +0x152
created by net/http.(*Transport).queueForDial
        /usr/local/go/src/net/http/transport.go:1390 +0x6b0

goroutine 42 [select]:
net.cgoLookupIP(0x2409120, 0xc00046d740, 0x2153e5e, 0x3, 0xc000382ca0, 0x14, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/cgo_unix.go:229 +0x1e9
net.(*Resolver).lookupIP(0x2a262a0, 0x2409120, 0xc00046d740, 0x2153e5e, 0x3, 0xc000382ca0, 0x14, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/lookup_unix.go:96 +0x217
net.glob..func1(0x2409120, 0xc00046d740, 0xc0000e3dc0, 0x2153e5e, 0x3, 0xc000382ca0, 0x14, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/hook.go:23 +0x9f
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/lookup.go:293 +0x162
internal/singleflight.(*Group).doCall(0x2a262b0, 0xc0001440f0, 0xc000382cc0, 0x18, 0xc00046d780)
        /usr/local/go/src/internal/singleflight/singleflight.go:95 +0x52
created by internal/singleflight.(*Group).DoChan
        /usr/local/go/src/internal/singleflight/singleflight.go:88 +0x4be

goroutine 82 [runnable]:
text/template/parse.(*lexer).run(0xc000410000)
        /usr/local/go/src/text/template/parse/lex.go:228
created by text/template/parse.lex
        /usr/local/go/src/text/template/parse/lex.go:223 +0x318

rax    0x2000209
rbx    0x80
rcx    0x70000d635d88
rdx    0x0
rdi    0x8
rsi    0x1
rbp    0x70000d635dd0
rsp    0x70000d635d88
r8     0x600002c00000
r9     0x80
r10    0x0
r11    0x246
r12    0x0
r13    0x0
r14    0x1
r15    0x8
rip    0x7fff202707a2
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
make: *** [dev-server] Error 2
</pre></details>

**Comment by blixt** [comment] 2020-09-23 11:05
Attempting to reproduce this issue with single HTTP requests or multiple goroutines with same/separate HTTP clients has not been fruitful, so the issue seems to be more intricate than just making DNS lookups.

**Comment by ianlancetaylor** [comment] 2020-09-24 00:29
This looks like the C function `getaddrinfo` called the C function `abort`.

Can you run the program under a C debugger and try to figure out what `getaddrinfo` is doing?

**Comment by cyclops3590** [comment] 2020-09-28 19:21
Just adding info in case it helps.  I'm on Beta 8 of 11.0 and it gave me the same runtime error while trying to resolve "localhost".

**Comment by aclements** [comment] 2020-12-08 18:58
Is this still an issue now that macOS 11 is out of beta?

**Comment by blixt** [comment] 2020-12-09 09:41
I have not seen this issue again in stable Big Sur.

**Comment by aclements** [comment] 2020-12-10 02:38
Thanks for following up. I'll close the issue in that case.

**Closed by aclements** 2020-12-10 02:38 UTC
Labels: NeedsInvestigation, WaitingForInfo

**Comment by hongalex** [comment] 2021-09-21 22:30
This seems to be an issue again for the macos Monterey beta, the error/stracktrace seems to be the same as @blixt originally provided.

**Comment by kidoman** [comment] 2021-12-01 23:26
Can confirm. This is happening with Go 1.17.2, on Mac OS X 12.0.1 on a M1 Pro SoC.

**Comment by aclements** [comment] 2021-12-02 01:34
Does the issue still happen with MacOS Monterey if you set the environment variable MallocNanoZone=0? There's a known issue with -race on MacOS 12 (#49138).

**Comment by Integralist** [comment] 2021-12-17 11:51
I also had this issue when the code encounters a `net.LookupAddr` and found (as suggested above) setting `MallocNanoZone=0` fixed the issue for me using `go version go1.17 darwin/amd64` on macOS Monterey.

**Comment by pavbis** [comment] 2022-01-12 22:10
> Just adding info in case it helps. I'm on Beta 8 of 11.0 and it gave me the same runtime error while trying to resolve "localhost". Switched to "127.0.0.1" and error went away

thanks! Switching to localhost helps in my case :) **macOS Monterey 12.1**

**Comment by rquinlivan** [comment] 2022-02-24 15:17
> Does the issue still happen with MacOS Monterey if you set the environment variable MallocNanoZone=0? There's a known issue with -race on MacOS 12 (#49138).

I recently upgraded to Monterey and began seeing this problem, and I can confirm that setting this variable fixed the issue for me.

**Comment by rupeshlangarkar** [comment] 2022-04-06 16:36
> Does the issue still happen with MacOS Monterey if you set the environment variable MallocNanoZone=0? There's a known issue with -race on MacOS 12 (#49138).

Thanks! I was facing similar issue and setting the environment variable MallocNanoZone=0 fixed it for me.

**Comment by tiagoppay** [comment] 2022-04-25 12:46
facing the same problem here, after upgrade macos to  macOS Monterrey 12.3.1
fixed with env MallocNanoZone=0
Thanks!!!

> I also had this issue when the code is compiled with `-race` and encounters a `net.LookupAddr` and found (as suggested above) setting `MallocNanoZone=0` fixed the issue for me using `go version go1.17 darwin/amd64` on macOS Monterey.
