### ISSUE TITLE
Windows arm64 missing function body

### ISSUE THREAD

**Issue by mcandre** [golang/go#47871] opened 2021-08-21 16:03 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/andrew/.cache/go-build"
GOENV="/home/andrew/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/andrew/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/andrew/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/andrew/.gvm/gos/go1.17"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/andrew/.gvm/gos/go1.17/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/andrew/go/src/github.com/mcandre/gus/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1711081068=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Source: https://github.com/mcandre/gus/tree/ff3398ce9c54491977a2ec0492444dc4b370c216

Trace:

```console
$ GOOS=windows GOARCH=arm64 go build cmd/gus/main.go
# golang.org/x/sys/windows
vendor/golang.org/x/sys/windows/dll_windows.go:24:6: missing function body
vendor/golang.org/x/sys/windows/dll_windows.go:25:6: missing function body
vendor/golang.org/x/sys/windows/zsyscall_windows.go:2533:38: undefined: WSAData
vendor/golang.org/x/sys/windows/zsyscall_windows.go:2773:51: undefined: Servent
vendor/golang.org/x/sys/windows/zsyscall_windows.go:2787:50: undefined: Servent
```

### What did you expect to see?

The Windows arm64 port successfully build.

### What did you see instead?

An error complaining about missing function bodies for Windows arm64.

Note that the 32-bit Windows arm _does_ include the function bodies.

```console
$ GOOS=windows GOARCH=arm go build cmd/gus/main.go
$ ls main.exe
main.exe
```

**Comment by seankhliao** [comment] 2021-08-21 16:08
Duplicate of #47870

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Closed by seankhliao** 2021-08-21 16:08 UTC
