### ISSUE TITLE
cmd/compile: unusual line numbers associated with generated code

### ISSUE THREAD

**Issue by griesemer** [golang/go#15453] opened 2016-04-26 18:01 UTC
The assembly listing of go/internal/gcimporter shows some unusual (wrong?) line numbers associated with the generated code. In the code for the method `importer.obj` we see references to gcimporter.go, even though there is no code here that should be coming from that file (also no inlining).
Here a snippet compiled with -ssa=0:

```
    0x01d1 00465 (/Users/gri/go/src/go/internal/gcimporter/bimport.go:193)  CMPB    runtime.writeBarrier(SB), $0
    0x01d8 00472 (/Users/gri/go/src/go/internal/gcimporter/bimport.go:193)  JNE $0, 551
    0x01da 00474 (/Users/gri/go/src/go/internal/gcimporter/bimport.go:193)  MOVQ    BP, 48(AX)
    0x01de 00478 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:935)   NOP
    0x01de 00478 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:935)   MOVL    $0, 56(AX)
    0x01e5 00485 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:935)   NOP
    0x01e5 00485 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:935)   MOVQ    $0, 64(AX)
    0x01ed 00493 (/Users/gri/go/src/go/internal/gcimporter/bimport.go:193)  MOVQ    "".p+488(FP), BX
    0x01f5 00501 (/Users/gri/go/src/go/internal/gcimporter/bimport.go:193)  MOVQ    BX, (SP)
    0x01f9 00505 (/Users/gri/go/src/go/internal/gcimporter/bimport.go:193)  LEAQ    go.itab.*go/types.Func,go/types.
```

Here a snippet compiled with ssa enabled:

```
    0x0154 00340 (/Users/gri/go/src/go/internal/gcimporter/bimport.go:185)  MOVQ    "".typ·5.data+176(SP), CX
    0x015c 00348 (/Users/gri/go/src/go/internal/gcimporter/bimport.go:185)  MOVQ    CX, 48(AX)
    0x0160 00352 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVL    $0, 56(AX)
    0x0167 00359 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVQ    $0, 64(AX)
    0x016f 00367 (/Users/gri/go/src/go/internal/gcimporter/bimport.go:185)  MOVQ    "".p+280(FP), CX
    0x0177 00375 (/Users/gri/go/src/go/internal/gcimporter/bimport.go:185)  MOVQ    CX, (SP)
```

And here a snippet compiled using the binary export format:

```
    0x00e2 00226 (/Users/gri/go/src/go/internal/gcimporter/bimport.go:185)  XORPS   X0, X0
    0x00e5 00229 (/Users/gri/go/src/go/internal/gcimporter/bimport.go:185)  DUFFZERO    $277
    0x00ea 00234 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVQ    $0, (AX)
    0x00f1 00241 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVQ    $0, 8(AX)
    0x00f9 00249 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVL    runtime.writeBarrier(SB), CX
    0x00ff 00255 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   LEAQ    16(AX), DX
    0x0103 00259 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   TESTB   CL, CL
    0x0105 00261 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   JNE $0, 474
    0x010b 00267 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVQ    go/types.pkg·3+200(SP), CX
    0x0113 00275 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVQ    CX, 16(AX)
    0x0117 00279 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVQ    "".name·4.len+80(SP), CX
    0x011c 00284 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVQ    CX, 32(AX)
    0x0120 00288 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVL    runtime.writeBarrier(SB), CX
    0x0126 00294 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   LEAQ    24(AX), DX
    0x012a 00298 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   TESTB   CL, CL
    0x012c 00300 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   JNE $0, 442
    0x0132 00306 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVQ    "".name·4.ptr+232(SP), CX
    0x013a 00314 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVQ    CX, 24(AX)
    0x013e 00318 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVQ    "".typ·5.itab+152(SP), CX
    0x0146 00326 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVQ    CX, 40(AX)
    0x014a 00330 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVL    runtime.writeBarrier(SB), CX
    0x0150 00336 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   TESTB   CL, CL
    0x0152 00338 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   JNE $0, 409
    0x0154 00340 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVQ    "".typ·5.data+176(SP), CX
    0x015c 00348 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVQ    CX, 48(AX)
    0x0160 00352 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVL    $0, 56(AX)
    0x0167 00359 (/Users/gri/go/src/go/internal/gcimporter/gcimporter.go:882)   MOVQ    $0, 64(AX)
    0x016f 00367 (/Users/gri/go/src/go/internal/gcimporter/bimport.go:185)  MOVQ    "".p+280(FP), CX
    0x0177 00375 (/Users/gri/go/src/go/internal/gcimporter/bimport.go:185)  MOVQ    CX, (SP)
```

The issue appears independent of ssa and independent of the export format chosen, but it somewhat affected by both. This may be all correct but needs an explanation, or there may be an issue and we should fix it.

**Comment by mdempsky** [comment] 2016-04-26 23:25
Happens with Go 1.6 too.

**Comment by mdempsky** [comment] 2016-04-27 00:34
Here's at least my current understanding of the issue.  Still investigating a fix.

When we inline a function call, we clone the function body and reassign all of the line numbers for the cloned Nodes to the function call site.  This is implemented by `(*inlsubst).node` and `setlno` in `inl.go`, respectively.

The problem is `setlno` renumbers some nodes that weren't cloned by `(*inlsubst).node`.

For example, in the `go/internal/gcimporter` case @griesemer pointed out above, there are a few call sites for this inlineable `go/types` function:

    func NewVar(pos token.Pos, pkg *Package, name string, typ Type) *Var {
        return &Var{object: object{nil, pos, pkg, name, typ, 0, token.NoPos}}
    }

`(*inlsubst).node` decides to reuse the `OLITERAL` nodes that represent 0 and token.NoPos, but then `setlno` still renumbers them.  This causes all of the inlined calls then to end up using the last call site's line number for these nodes.

**Comment by mdempsky** [comment] 2016-04-27 01:15
Minimized repro case:

    package p
    
    var A, B interface{}
    
    func F() {
        A = New()
        B = New()
    }
    
    type S struct {
        x uint32
    }
    
    func New() *S {
        return &S{0}
    }

Compile with `go tool compile -S -ssa=0 repro.go` and see:

        0x0017 00023 (repro.go:6)       LEAQ    type."".S(SB), BX
        0x001e 00030 (repro.go:6)       MOVQ    BX, (SP)
        0x0022 00034 (repro.go:6)       PCDATA  $0, $0
        0x0022 00034 (repro.go:6)       CALL    runtime.newobject(SB)
        0x0027 00039 (repro.go:6)       MOVQ    8(SP), CX
        0x002c 00044 (repro.go:7)       NOP
        0x002c 00044 (repro.go:7)       MOVL    $0, (CX)
        0x0032 00050 (repro.go:6)       LEAQ    type.*"".S(SB), BX
        0x0039 00057 (repro.go:6)       MOVQ    BX, "".autotmp_6+16(SP)
        0x003e 00062 (repro.go:6)       MOVQ    BX, "".A(SB)
        0x0045 00069 (repro.go:6)       MOVQ    CX, "".autotmp_6+24(SP)
        0x004a 00074 (repro.go:6)       CMPB    runtime.writeBarrier(SB), $0
        0x0051 00081 (repro.go:6)       JNE     $0, 185
        0x0053 00083 (repro.go:6)       MOVQ    CX, "".A+8(SB)
        0x005a 00090 (repro.go:6)       NOP

The lines for `repro.go:7` should be `repro.go:6`.

**Comment by mdempsky** [comment] 2016-04-28 00:16
Elaborating a bit more, the problem is that sinit.go uses the OLITERAL Node's line number when desugaring OSTRUCTLIT Nodes into sequences of OAS Nodes. Two possible fixes I have in mind:

1. Change inl.go to clone OLITERAL Nodes. This is simple and I've already experimentally confirmed it works, but I'm worried it will increases memory usage due to having to clone every constant value within inlined function bodies.

2. Change sinit.go to use a different source for the OAS Nodes' line numbers. Maybe the enclosing OKEY Nodes? Skimming go/printer's source, I think canonical gofmt'ing should always place OKEYs on the same line as the values anyway, though someone might manually write something like:

        p := &s{
            x:
                1,
        }

  and the generated `p.x = 1` assignment statement's line association would move from `1,` to `x:`.

Option 2 seems preferable since it shouldn't negatively impact gofmt'd code, and it still does something reasonable for non-gofmt'd code.

**Comment by griesemer** [comment] 2016-04-28 05:25
Fix 1) seems the more correct fix, isn't it? We could see how many more nodes are created over the course of make.bash and take it from there.

Alternatively, could we do something like `wrapname` (parser.go:1496)?

**Comment by mdempsky** [comment] 2016-05-02 20:43
Fix 1 seems most correct to me, I'm just concerned about the compilation overhead.

Instrumenting the compiler to count the number of OLITERAL Nodes that may need copying due to inlining, it looks like maybe it would be okay. Compiling net/http would require duplicating an extra 1400 Nodes. Most other packages need closer to the order of 100 to 200.  gc requires 7000.

Another option (3) is to revert golang.org/cl/11672 (55203c7d), which seems to be the CL that introduced the unusual line numbers.

**Comment by rsc** [comment] 2016-05-17 13:41
Let's leave for Go 1.8.

**Closed** 2017-03-03 21:29 UTC
Labels: NeedsFix
