### ISSUE TITLE
x/pkgsite: requesting new versions of existing modules causes "oops" errors and 404s

### ISSUE THREAD

**Issue by mvdan** [golang/go#46535] opened 2021-06-03 09:41 UTC
For example, https://pkg.go.dev/github.com/ipld/go-ipld-prime@v0.10.0 is a 404 and when I request it via the UI, I just get:

> Oops! Something went wrong. 

Refreshing just gets me back to the start. This version has been published and requested for hours, so it's not a caching thing.

Someone else has been experiencing the exact same issue on Slack with other modules:

https://pkg.go.dev/modernc.org/qbe@v0.0.6

https://pkg.go.dev/modernc.org/scannertest@v1.0.0

So it seems like pkgsite's backend is having some errors pulling in new versions. CC @jba @julieqiu 

I also wonder if the pages could give just a little bit more detail. It's hard to tell what kind of bug this is if all I get is an "oops".

**Comment by seankhliao** [comment] 2021-06-03 10:21
dup of the pinned #46527 ?

**Comment by jba** [comment] 2021-06-03 10:24
Yes, we continue to have delays. The pinned issue will have progress reports.

**Comment by mvdan** [comment] 2021-06-03 10:28
I saw that issue but I assumed this was unrelated, since you said "new modules" in that thread and these are not new modules.

**Comment by jba** [comment] 2021-06-03 11:04
Sorry, new module versions.

**Comment by 89z** [comment] 2021-06-04 02:47
https://github.com/golang/go/issues/46350
https://github.com/golang/go/issues/46527

https://github.com/golang/go/issues/46535
https://github.com/golang/go/issues/46538

**Comment by 89z** [comment] 2021-06-04 02:52
Looks like this has been an issue since at least https://github.com/golang/go/issues/45703 (April 2021), @julieqiu any comment?

**Comment by FiloSottile** [comment] 2021-06-04 12:58
Duplicate of #46527

**Closed by FiloSottile** 2021-06-04 12:58 UTC
Labels: NeedsFix, pkgsite
