### ISSUE TITLE
cmd/compile: compiler crashes on programs with 1<<30 array key

### ISSUE THREAD

**Issue by dotaheor** [golang/go#23780] opened 2018-02-11 18:19 UTC
### What version of Go are you using (`go version`)?

go version go1.9.3 **linux/amd64**

### Does this issue reproduce with the latest release?

yes

### What did you do?

a.go:
```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, playground")
	const k uint64 = 1 << 30
	_ = []int{k:1}
}}
```

go build a.go

### What did you expect to see?

produce a binary in one second.

### What did you see instead?

computer becomes lagging, almost hanging.
I must press CTRL-C for several times to stop the building.

**Comment by cznic** [comment] 2018-02-11 18:43
I can reproduce the issue with `go version go1.9.3 linux/amd64` when replacing the final `}}` with `}` to make the code syntactically valid.

**Comment by dotaheor** [comment] 2018-02-11 18:57
The hang may be caused by my computer (8G memory) has not enough memory.

If I change the slice element type to `byte`, it fails to compile with the following error:
```
./a.go:10:15: prepwrite: bad off=1073741824 siz=1 s="".statictmp_1
```

**Comment by agnivade** [comment] 2018-02-11 19:00
You are trying to create a slice of 1073741824 integers. Which would mean you are trying to get 1073741824 * 8 bytes = 8TB of memory approximately.

**Comment by dotaheor** [comment] 2018-02-11 19:15
Yes. But I think the hang should occur at run time, instead of compile time.

**Comment by ALTree** [comment] 2018-02-11 19:40
The second issue you reported (the fact that with `byte` the compiler just prints 

```
./a.go:10:15: prepwrite: bad off=1073741824 siz=1 s="".statictmp_1
```
) looks more serious.

I suspect it would do the same thing with `int64` on a machine with enough memory.

**Comment by ALTree** [comment] 2018-02-11 19:46
I changed the issue title to highlight the actual crash you reported here, since I believe is more interesting that your machine getting slow on the `int64` array.

**Comment by agnivade** [comment] 2018-02-11 20:02
I think it is to do with the way the slice is being initialized. `[]int{k:1}` creates a slice of 0,0,...1. But if you change the code to `make([]int, k)` everything works fine. Frankly, I have never seen syntax like this - `[]int{k:1}`.

**Comment by cznic** [comment] 2018-02-12 09:48
FTR: `foo := []T{n:1}` makes foo with `n+1` elements in contrast to `foo := make([]t, n)`.

Note to the compiler guys: I guess the compiler tries to be nice wrt to initialization time and puts the images for composite literals in the text and/or data segments - triggering this issue. If that's the case I think the solution would be to detect when the composite literal is very sparse/mostly zero-values and perform instead a run time all-zero value creation and initialization of the non zero-valued items only all in code.

**Comment by griesemer** [comment] 2018-05-03 16:48
@cznic Yes, the compiler could probably be a bit smarter here - on the other hand, perhaps one shouldn't write code like this. But I agree that the compiler shouldn't just appear to be hanging.

To summarize:

1) $ go tool compile x.go
x.go:4:22: prepwrite: bad off=1073741824 siz=1 s="".statictmp_0
for x.go:
```
package p

func f() {
	_ = []byte{1 << 30: 0}
}
```

2) $ go tool compile x.go
x.go:4:21: prepwrite: bad off=8589934592 siz=8 s="".statictmp_0
for x.go (same as above, but `int` instead of `byte`):
```
package p

func f() {
	_ = []int{1 << 30: 0}
}
```

3) There's no issue with:
```
package p

var X = []int{1 << 30: 0}
```

**Comment by griesemer** [comment] 2018-06-13 23:15
Not urgent. Moving to 1.12.

**Comment by randall77** [comment] 2018-11-26 22:00
Related to #27447

**Closed** 2018-11-26 22:51 UTC
Labels: NeedsInvestigation
