### ISSUE TITLE
x/build: different old install path does not remove the distribution for mac installer

### ISSUE THREAD

**Issue by tjamaranhao** [golang/go#35883] opened 2019-11-27 22:21 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 darwin/amd64
</pre>
<pre>
$ /usr/local/go/bin/go version
go version go1.13.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tjamaranhao/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tjamaranhao/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

</pre></details>

<details><summary><code>/usr/local/go/bin/go env</code> Output</summary><br><pre>
$ /usr/local/go/bin/go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tjamaranhao/Library/Caches/go-build"
GOENV="/Users/tjamaranhao/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tjamaranhao/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

</pre></details>

### What did you do?
I downloaded go 1.11.5 months ago and had it installed on my machine.

Then now, I'm taking a Go training and decided to upgrade my go to the most recent version 1.13.4.

Downloaded the installation file for Mac
Executed the package
It popped up a msg saying it identified a previous version and was going o uninstall it
Moved on and finished the installation.

Then when I ran **go version**, it returned it was still on version 1.11.5.
Then I ran **where go** command and it returned:
$ where go
/usr/local/bin/go
/usr/local/go/bin/go

That's when I realized it change the installation path. Now I have both versions on my computer

### What did you expect to see?
I expected the installer to uninstall 1.11.5 and leave only 1.13.4

### What did you see instead?
The main installation remain pointing to 1.11.5, so I'll need to manually uninstall it now.

**Comment by agnivade** [comment] 2019-11-28 03:39
It doesn't look like your previous installation was done by the standard installer. So I guess it detected a `go` binary in the PATH but it failed to remove it because it was installed in a different location. I would recommend to always use the same installer.

/cc @dmitshur in case the removal message can be improved.

**Comment by tjamaranhao** [comment] 2019-12-17 20:46
> It doesn't look like your previous installation was done by the standard installer. So I guess it detected a `go` binary in the PATH but it failed to remove it because it was installed in a different location. I would recommend to always use the same installer.
> 
> /cc @dmitshur in case the removal message can be improved.

Downloaded both versions from golang.org.

**Comment by dmitshur** [comment] 2019-12-17 21:29
Can you run `go env GOROOT` and `/usr/local/go/bin/go env GOROOT`?

From the `go env` output in the original issue:

```
GOROOT="/usr/local/Cellar/go/1.11.5/libexec"
```

It looks like Go 1.11.5 was installed via Homebrew, while Go 1.13.4 was installed with the macOS installer from golang.org/dl. The installer does remove previous versions of Go installed via the same means, but it can't take such action for versions of Go installed via other means (such as from Homebrew).

**Comment by tjamaranhao** [comment] 2019-12-17 21:35
Thx for the prompt response. But in fact I ended up removing 1.11 from my computer.... sorry about that.. I could swear both came from golang installer.... but honestly I don't remember if I installed it from homebrew or from golang since that was months ago....

But if the issue is not reproduceable using both installers, then you may close this issue... in the end... that was a dated version

**Comment by dmitshur** [comment] 2019-12-17 21:47
No problem and thanks for reporting this.

I believe the macOS installer correctly removes previous versions of Go that were installed using the same installer, so there's no issue there.

I don't think it's in scope for the macOS installer to be aware of other types of installers. If we continue to see problems related to that, we can reconsider this based on that data.

I'll close this since we can't reproduce this particular instance, and I'm not seeing actionable steps to take for now.

**Closed by dmitshur** 2019-12-17 21:47 UTC
Labels: WaitingForInfo
