### ISSUE TITLE
cmd/go: vet checks do not run when compiling tests to output a binary

### ISSUE THREAD

**Issue by dlsniper** [golang/go#26451] opened 2018-07-18 20:36 UTC
### What version of Go are you using (`go version`)?
go version go1.10.3 linux/amd64
go version go1.11beta1 windows/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
OS/ARCH independent

### What did you do?
Using a simple broken build tag such as this, place the code in a ` demo_test.go ` file:
```go
//+build hello
package demo

import "testing"

type Demo struct {
	Field string
}

func NewDemo(v string) *Demo {
	return &Demo{
		Field: v,
	}
}

func TestDemo(t *testing.T) {
	v := NewDemo("hello world")
	t.Log(v)
}
```

Run ` go test -c -o binary.name `.

### What did you expect to see?
I expect to see the following error:
```
.\file_test.go:1: +build comment must appear before package clause and be followed by a
blank line%!(EXTRA []interface {}=[])
````

### What did you see instead?
Compilation and running tests from the test binary via ` binary.name -test.v ` works without issues.

This behavior is inconsistent and leads to issues when a user compiles the test binary to run it after. I would expect the test binary to be prevented from being created by the same ` vet ` checks.

**Comment by ianlancetaylor** [comment] 2018-07-18 21:20
Marking as Go 1.12 since the behavior is not new.

CC @rsc @bcmills

**Comment by dlsniper** [comment] 2018-07-19 06:55
I think that the formatting error was fixed in the latest master but I'm still using 1.11 Beta 1. I'll revisit this for Beta 2 / RC 1.

**Comment by ysmolsky** [comment] 2018-07-19 09:55
I cannot reproduce this on `go version devel +d278f09333 Thu Jul 19 05:40:37 2018 +0000 darwin/amd64`
```bash
...go/src/demo % cat demo.go
//+build hello
package demo

import "testing"

type Demo struct {
	Field string
}

func NewDemo(v string) *Demo {
	return &Demo{
		Field: v,
	}
}

func TestDemo(t *testing.T) {
	v := NewDemo("hello world")
	t.Log(v)
}
...go/src/demo % go test -c -o test.bin
# demo
./demo.go:1: +build comment must appear before package clause and be followed by a blank line
...go/src/demo % ls
demo.go
```

**Comment by dlsniper** [comment] 2018-07-19 12:54
This still seems to be an issue both on Windows and Linux using:
- go version devel +d278f09333 Thu Jul 19 05:40:37 2018 +0000 windows/amd64
- go version devel +d278f09333 Thu Jul 19 05:40:37 2018 +0000 linux/amd64

See the image below:
![image](https://user-images.githubusercontent.com/607868/42943606-e4b1be10-8b6b-11e8-9e0e-4e2247a4d2d7.png)

**Comment by dlsniper** [comment] 2018-07-19 12:57
@ysmolsky this is probably because the code was in a non `_test.go` file? In my case it was in such a file.

**Comment by ysmolsky** [comment] 2018-07-19 13:00
Right. I am sorry! Here we go:
```
...go/src/demo % mv demo.go demo_test.go
...go/src/demo % go test -c -o test.bin
...go/src/demo % go test
# demo
./demo_test.go:1: +build comment must appear before package clause and be followed by a blank line
FAIL	demo [build failed]
```
Reproduced.

**Closed** 2018-07-20 20:00 UTC
Labels: NeedsFix, help wanted

**Comment by iWdGo** [comment] 2018-10-21 14:43
Issue cannot be reproduced when using `go 1.11.1`

**Comment by dlsniper** [comment] 2018-10-22 09:01
The issue is still present in Go 1.11.1. Place the code exactly as it's written in a ` _test.go` file and the problem should be reproduced.
