### ISSUE TITLE
wasm: program allocs too much memory

### ISSUE THREAD

**Issue by 5kbpers** [golang/go#35390] opened 2019-11-06 09:01 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/5kbpers/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/5kbpers/go-linux-amd64-bootstrap"
GOPROXY=""
GORACE=""
GOROOT="/home/5kbpers/go-linux-amd64-bootstrap"
GOTMPDIR=""
GOTOOLDIR="/home/5kbpers/go-linux-amd64-bootstrap/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build234335217=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Hello! I compiled the following program to WASM: 
```golang
package main

import (
    "fmt"
    "time"
)

func main() {
    for {
        fmt.Println("Hello, WebAssembly!")
        time.Sleep(time.Millisecond * 500)
    }
}
```
After opening it with my browser (Chrome 78.0.3904.70), take a memory snapshot, that shows it allocs about 1GB memory:
![image](https://user-images.githubusercontent.com/20279863/68282736-2b137f00-00b5-11ea-98c4-8242eb3d2763.png)
I found a related issue https://github.com/golang/go/issues/27462, adjust the preallocated memory to 64MB:
```golang
// writeMemorySec writes the section that declares linear memories. Currently one linear memory is being used.
func writeMemorySec(ctxt *ld.Link) {
	sizeOffset := writeSecHeader(ctxt, sectionMemory)

	// Linear memory always starts at address zero.
	// The unit of the sizes is "WebAssembly page size", which is 64Ki.
	// The minimum is currently set to 1GB, which is a lot.
	// More memory can be requested with the grow_memory instruction,
	// but this operation currently is rather slow, so we avoid it for now.
	// TODO(neelance): Use lower initial memory size.
	writeUleb128(ctxt.Out, 1)       // number of memories
	ctxt.Out.WriteByte(0x00)        // no maximum memory size
	writeUleb128(ctxt.Out, 1024) // minimum (initial) memory size

	writeSecSize(ctxt, sizeOffset)
}
``` 
But the allocated memory is still very high (about 780MB):
![image](https://user-images.githubusercontent.com/20279863/68283368-62cef680-00b6-11ea-8f56-a2b0e6e6e96e.png)

### What did you expect to see?
The allocated memory should approximately be 64MB after adjusting the preallocated memory.

### What did you see instead?
The allocated memory is too much higher than expected.

**Comment by ALTree** [comment] 2019-11-06 10:16
> What version of Go are you using (go version)?
>
> go version go1.12.13 linux/amd64

#27462 was fixed for Go1.13 so please try with that version.

**Comment by tmthrgd** [comment] 2019-11-06 11:04
Isn’t this likely a duplicate of #35111 (which is fixed on tip)?

**Comment by ALTree** [comment] 2019-11-06 11:18
How so? #35111 is a memory leak (the memory starts low and keeps increasing), on this one OP immediately sees that the wasm program takes 1GB of RAM.

The "wasm programs start with 1GB of RAM taken" issue is #27462 , which I linked above.

**Comment by 5kbpers** [comment] 2019-11-06 13:20
@ALTree Go1.13 works to this, thank you!
BTW, I'm curious about why it still allocates 780MB memory after the initial size was adjusted to 64MB.

**Comment by ALTree** [comment] 2019-11-06 14:27
@5kbpers 

> Go1.13 works to this, thank you!

Nice, I'll close this issue then.

> BTW, I'm curious about why it still allocates 780MB memory after the initial size was adjusted to 64MB.

You mean the patch you posted above that you manually applied? I'm not sure, it's likely that it just wasn't enough to fix the issue or possibly you did not build the patched toolchain correctly so it didn't pick up your change.

**Closed by ALTree** 2019-11-06 14:27 UTC
Labels: WaitingForInfo
