### ISSUE TITLE
cmd/go: go mod vendor looses executable bit in vendored files

### ISSUE THREAD

**Issue by thaJeztah** [golang/go#45231] opened 2021-03-25 12:35 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/go/repro/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1216370537=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

While migrating a project from GoDeps to go modules, I noticed that some vendored files changed their permissions from `0755` to `0655`. Looking for the source of truth, I looked at the files in the upstream repository, which showed that `0755` was the correct permission.

To reproduce:

```bash
mkdir repro && cd repro

cat > foo.go <<'EOF'
package repro

import "golang.org/x/sys/unix"

_ = unix.R_OK
EOF

go mod init repro && go mod tidy
# go: finding golang.org/x/sys/unix latest
# go: finding golang.org/x/sys latest
# go: downloading golang.org/x/sys v0.0.0-20210324051608-47abb6519492

go mod vendor
ls -la vendor/golang.org/x/sys/unix/mkall.sh
# -rw-r--r--    1 root     root          8528 Mar 25 12:07 vendor/golang.org/x/sys/unix/mkall.sh
```

Verifying the file permissions in the upstream source repository;

```bash
git clone https://github.com/golang/sys.git golang-sys
ls -la golang-sys/unix/mkall.sh
# -rwxr-xr-x    1 root     root          8528 Mar 25 12:09 golang-sys/unix/mkall.sh
```

### What did you expect to see?

In this case, these files (shell and perl scripts) may not be needed in the vendor directory, but since they are included, file mode should be preserved.

### What did you see instead?

Files having the incorrect mode.

**Comment by ALTree** [comment] 2021-03-25 13:02
I believe this is a dup of #34965, which was closed as Working As Intended; see in particular https://github.com/golang/go/issues/34965#issuecomment-546053393 by Russ.

**Comment by thaJeztah** [comment] 2021-03-25 13:33
Ah, thanks! I tried searching, but only found the ones about permissions in the go module cache.

> We defined the Go module representation to be absolutely least common denominator across systems for portability. The Go module zip file is for dependencies that need to be downloaded and built by the go command. It is not meant to support anything more. By design, there are no permission bits, nor special files like symlinks, nor modification times. 

I'm not sure if I agree with the choice here; IMO files should either be included (verbatim copy), or _not included_. Including files but discarding information that may have been set _on purpose_ feels tricky.

That said; for the example at hand here (some script files), I could see that excluding those files could make sense.

**Comment by bcmills** [comment] 2021-03-25 14:54
Duplicate of #34965

**Closed by bcmills** 2021-03-25 14:54 UTC
