### ISSUE TITLE
compress/gzip: Enforce that reader implements `io.ByteReader` with multistream disabled.

### ISSUE THREAD

**Issue by Shaptic** [golang/go#53491] opened 2022-06-21 19:15 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
n/a

### What did you do?
If you pass an `*os.File` (which implements `io.Reader`) to `gzip.Reader` and disable multi-stream (`.Multistream(false)`), the `.Reset(r)` call will return EOF after the first gzip stream despite there being more streams in the file.

https://go.dev/play/p/NEdhYQNfKds

Notice that we wrote two chunks to the file (named "hello" and "world") but only one was read (the first, "hello").

### What did you expect to see?
One of two things:
 - a read of every gzip stream in the file
 - an error indicating that the reader does not implement `io.ByteReader`

### What did you see instead?
Only the first stream is read.

This behavior is very [subtly](https://pkg.go.dev/compress/gzip#Reader.Multistream) noted in the documentation:

> The underlying reader must implement io.ByteReader in order to be left positioned just after the gzip stream.

However, a runtime check and error for interface compatibility would be far more intuitive.

**Comment by ianlancetaylor** [comment] 2022-06-21 19:18
CC @dsnet

**Comment by dsnet** [comment] 2022-06-23 17:38
I believe this is working as intended.

Regarding documentation, I'm not sure I agree that this is "subtle". The documented requirement for `io.ByteWriter` appears with `Reader.Multistream` which must be called to engage in multistream mode. Had it only been somewhere (e.g., on `NewWriter`), I can imagine that being subtle.

Regarding a change in semantics, we can't do that. One of the valid use-cases for `Reader.Multistream` is to read each individual GZIP file while holding onto the same `Reader`. In this situation, the internal buffering of `Reader` doesn't matter since we're not throwing it away and reconstructing it anew.

**Comment by dsnet** [comment] 2022-07-14 19:36
Closing as there's nothing actionable to do.

**Closed by dsnet** 2022-07-14 19:36 UTC
Labels: NeedsInvestigation
