### ISSUE TITLE
go tool pprof doesn't warn when improperly used

### ISSUE THREAD

**Issue by mattetti** [golang/go#19859] opened 2017-04-05 22:40 UTC
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
I profiled by code and tests then I tried to analyze the pprof results.

```bash
go test -bench=. -cpuprofile cpu.prof
```

```bash
go tool pprof cpu.prof
Entering interactive mode (type "help" for commands)
(pprof) top10
2.25s of 2.25s total (  100%)
      flat  flat%   sum%        cum   cum%
     2.25s   100%   100%      2.25s   100%  
(pprof)
```

#### What did you expect to see?

The top 10 call sites.

#### What did you see instead?

Only 1 entry.

This is because I forgot to add the .test binary to the list of arguments. I also had the same issue using my standalone binary. While I understand it's a user error, as discussed with @rakyll I would be greatly appreciated if `go tool pprof` could warn me that I'm missing an argument.

#### System details

```
go version go1.8 darwin/amd64
GOARCH="amd64"
GOBIN="/Users/mattetti/Code/golang/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mattetti/Code/golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4p/sfb8dphs3hgb62k1_6dl09vh0000gn/T/go-build759645982=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L /Users/mattetti/Code/golang/src/<hidden>"
GOROOT/bin/go version: go version go1.8 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.8 X:framepointer
uname -v: Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
lldb --version: lldb-360.1.70
```

**Comment by cespare** [comment] 2017-04-05 22:43
Duplicate of #10863.

Also sounds like this will be fixed in a better way in the future by including all the necessary symbols in the profile (so the binary will not be needed).

**Comment by davecheney** [comment] 2017-04-05 22:43
Possibily a duplicate of #10863

**Closed by cespare** 2017-04-05 22:43 UTC
