### ISSUE TITLE
cmd/go: illegal instruction on armv6l (Raspberry Pi zero)

### ISSUE THREAD

**Issue by maddoglee** [golang/go#62367] opened 2023-08-30 04:46 UTC
### What is the URL of the page with the issue?

https://go.dev/dl/

### What is your user agent?

Your user agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

### What did you do?

I tried to install [go1.21.0.linux-armv6l.tar.gz](https://go.dev/dl/go1.21.0.linux-armv6l.tar.gz) on a Raspberry Pi Zero and found that I got Illegal Instruction errors. I installed version 1.20.7 the same way and it worked, so there must be something wrong with the 1.21.0 file. 

### What did you expect to see?

go version

### What did you see instead?

Illegal Instruction

**Comment by mengzhuo** [comment] 2023-08-30 07:17
Since all release will be tested on raspberry pi, it should be ok to run go command.
Could you provide more information such as output of:
`uname -a`
`go env`
same as other bug report?

**Comment by seankhliao** [comment] 2023-08-30 07:32
Duplicate of #62164

**Closed by seankhliao** 2023-08-30 07:32 UTC
