### ISSUE TITLE
strings.Split traverse the string twice when split?

### ISSUE THREAD

**Issue by wttang** [golang/go#13920] opened 2016-01-12 09:52 UTC
go 1.5.2 linux x86

in src/strings/strings.go genSplit
when n < 0, called by strings.Split n=-1
first count sep, traversed once
then do split, traversed once more, it sees low efficiency.

if we could estimate N, use strings.SplitN is ok, but if we couldn't get N ?

**Comment by minux** [comment] 2016-01-12 10:30
How could we estimate N without much
memory overhead?

**Comment by ianlancetaylor** [comment] 2016-01-12 14:53
I don't see an actionable bug report here, so closing.  If you want to discuss this, please use one of the forums; see https://golang.org/wiki/Questions .  Thanks.

**Closed by ianlancetaylor** 2016-01-12 14:53 UTC

**Comment by wttang** [comment] 2016-01-13 01:24
use a slice with estimated N as a hint, but if there is more splits than N, the slice will automatic grow, this seems more reasonable?

**Comment by minux** [comment] 2016-01-13 01:44
The problem is how to estimate N. Too small an
estimate, and you will end up reallocate the slice
a few times and incur much bigger overhead, and
too big an estimate you will just waste memory.

The minimum and maximum is different enough that
I don't think we can estimate N accurately without
traversing the string once.

Anyway, if you think you can do better, perhaps
you should write an implementation that only
traverse the string once and do some benchmark
to show it's superior than the current implementation.
It's better than arguing here without any concrete
benchmark numbers.
