### ISSUE TITLE
cmd/go: go mod vendor ignore workspace 

### ISSUE THREAD

**Issue by fishy** [golang/go#54452] opened 2022-08-15 02:29 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fishy/.cache/go-build"
GOENV="/home/fishy/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/fishy/.gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/fishy/.gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.19"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.19/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/fishy/work/url2epub/cloudrun/go.mod"
GOWORK="/home/fishy/work/url2epub/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2972466680=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
$ git clone https://github.com/fishy/url2epub -b v0.4.0
$ cd url2epub/cloudrun
$ go mod vendor
```

### What did you expect to see?

go files under `cloudrun/vendor/go.yhsif.com/url2epub` should be the same as the top level because I have this `go.work` at the top level:

```
$ cat go.work
go 1.19

use (
        .
        ./cloudrun
        ./debug
        ./rmapi/debug
)
```

### What did you see instead?

`url2epub/cloudrun/vendor/go.yhsif.com/url2epub` is actually vendored at `v0.3.1`, as specified in `cloudrun/go.mod`.

**Comment by seankhliao** [comment] 2022-08-15 08:41
Duplicate of #53904

**Closed by seankhliao** 2022-08-15 08:41 UTC
