### ISSUE TITLE
x/pkgsite: unable to request for new version of 'go-persian-calendar' documentation

### ISSUE THREAD

**Issue by yaa110** [golang/go#46538] opened 2021-06-03 12:26 UTC
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/yaa110/go-persian-calendar@v1.0.2
 
 
### What is your user agent?
 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36

 
 
 
### Screenshot
 

 
 
![Screenshot from 2021-06-03 16-53-41](https://user-images.githubusercontent.com/3187511/120644263-5f674100-c48c-11eb-8e83-50f594fbac08.png)

 
### What did you do?
 

 
- Goto https://pkg.go.dev/github.com/yaa110/go-persian-calendar@v1.0.2
- Click on `Request ...` button
 
 
### What did you expect to see?
 
I expected to get the documentation of new version of `go-persian-calendar`
 
### What did you see instead?

Oops! Something went wrong

**Comment by seankhliao** [comment] 2021-06-03 12:27
Duplicate of #46527

**Closed by seankhliao** 2021-06-03 12:27 UTC
Labels: pkgsite

**Comment by 89z** [comment] 2021-06-04 02:48
https://github.com/golang/go/issues/46350
https://github.com/golang/go/issues/46527
https://github.com/golang/go/issues/46535

https://github.com/golang/go/issues/46538
