### ISSUE TITLE
gofmt inserting spaces in docstring, breaking swagger doc generation

### ISSUE THREAD

**Issue by nicolaigj** [golang/go#54369] opened 2022-08-10 11:43 UTC
Go version
```
go version go1.19 linux/amd64
```

After I updated to go 1.19, I'm now experiencing that gofmt inserts spaces in swagger yml docstrings that I have above my HTTP handler functions for swagger doc generation. 

### Steps to reproduce
1. Write a docstring with swagger yml to a http handler
2. Run gofmt on the file
3. gofmt has added spaces to the docstring that breaks swagger doc generation

### Concrete example
**Step 1**
This example is a valid docstring that swagger generates it's specification from. 
```go
// swagger:operation GET /users Users getUsers
// ---
// summary: Get Users
// description: Retrieves all Users if no parameters was given.
// parameters:
// - name: q
//   in: query
//   description: search for string fields on user and organization name
//   type: string
//   required: false
// <------- Rest of docstring omitted
func GetUsers(w http.ResponseWriter, r *http.Request) { // code omitted }
```
**Step 2**
Run gofmt
```gofmt -w main.go```

**Step 3**
The resulting file is now:
```go
// swagger:operation GET /users Users getUsers
// ---
// summary: Get Users
// description: Retrieves all Users if no parameters was given.
// parameters:
//   - name: q <--- In this line and the four below, spaces are added to the beginning of the line
//     in: query 
//     description: search for string fields on user and organization name 
//     type: string 
//     required: false 
// <------- Rest of docstring omitted
func GetUsers(w http.ResponseWriter, r *http.Request) { // code omitted }
```
Running swagger generation now returns error
```bash
> swagger generate spec -o ./spec.yaml --scan-models
operation (getUsers): yaml: line 18: did not find expected key
```
### Playground reproduction
This is also reproducible in this go playground: https://go.dev/play/p/VZGgSm13yrV?v=goprev

1. Click link
2. Press "Format", code is unchanged
3. Switch go version to 1.19
4. Press "Format"
5. gofmt inserts spaces as described. 

Was this change intended? Will it be fixed, or do we have to do work arounds?

**Comment by nicolaigj** [comment] 2022-08-10 11:45
Sorry about not using template, when I click "New issue", while not being logged in, I was sent directly to an empty issue after login. If you want me to recreate with template I can do that.

**Comment by seankhliao** [comment] 2022-08-10 15:00
Doesn't reproduce, `swagger generate spec -o spec.yaml` works for both the formatted code, and if the yaml is indented as a code block:

```
package main

import "net/http"

// swagger:operation GET /users Users getUsers
// ---
//
//	summary: Get Users
//	description: Retrieves all Users if no parameters was given.
//	parameters:
//	  - name: q
//	    in: query
//	    description: search for string fields on user and organization name
//	    type: string
//	    required: false
func GetUsers(w http.ResponseWriter, r *http.Request) {}
```

Closing as working as intended.

**Closed by seankhliao** 2022-08-10 15:00 UTC

**Comment by rodrigc** [comment] 2022-08-18 00:38
I ran into the same problem in my code and asked about it here: https://groups.google.com/g/golang-nuts/c/sY7QFzfSMT4

**Comment by pmalhaire** [comment] 2022-10-17 15:28
I may have missed why this issue is closed I reproduced it too.

**Comment by rodrigc** [comment] 2022-10-17 16:41
@pmalhaire The discussion at https://groups.google.com/g/golang-nuts/c/sY7QFzfSMT4 was that the go toolchain is free to indent code (even in comments) however it wants, and tools like go-swagger should not assume that gofmt will `not` reformat the comments.

@pmalhaire you can try go-swagger release https://github.com/go-swagger/go-swagger/releases/tag/v0.30.0 or higher, and see if the go1.19 fixes in there help you.  The other thing you may want to try is to shift the swagger comments around so that they are not in the godoc comments and not reformatted.

**Comment by pmalhaire** [comment] 2022-10-18 05:52
@rodrigc thank you for this detailed answer

I'll follow the go-swagger fix then

For those facing the issue the simpliest way for now is to use go1.18.X 1.18.5 and go-swagger 0.30.0 built from the repo for darwin arm64 and using the 0.30.0 release for Linux.
