### ISSUE TITLE
affected/package: net net.Interfaces()/net.InterfaceAddrs() return empty result on DragonflyBSD 6

### ISSUE THREAD

**Issue by missdeer** [golang/go#52388] opened 2022-04-17 03:00 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xy/Library/Caches/go-build"
GOENV="/Users/xy/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xy/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xy/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/xy/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/xy/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xy/Development/ddnsclient/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t0/v0smhfqj01xfstvdmsg84rn00000gp/T/go-build3079142592=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

source code: https://go.dev/play/p/rQkzi4SuNDs
build with command line:
```
env GOOS=dragonfly GOARCH=amd64 go build -ldflags="-s"
```
run the output on DragonflyBSD 6 which has `uname -a` output like below:
```
$ uname -a
DragonFly DragonflyBSD6-on-pve.ismisv.com 6.0-RELEASE DragonFly v6.0.1-RELEASE #3: Mon Oct 11 23:59:07 EDT 2021     root@www.shiningsilence.com:/usr/obj/home/justin/release/6_0/sys/X86_64_GENERIC  x86_64
```

### What did you expect to see?

Something like below:
```
get interface addresses: 1 [127.0.0.1/8]
get interfaces: 1 [{1 65522 lo  up|loopback}]
```

### What did you see instead?

Something like below:
```
get interface addresses: 0[]
get interfaces: 0 []
```

**Comment by seankhliao** [comment] 2022-04-17 14:05
Duplicate of #46674 (net calls x/net/route).

**Closed by seankhliao** 2022-04-17 14:05 UTC
