### ISSUE TITLE
cmd/go: get hangs indefinitely for go get -x -u ./...

### ISSUE THREAD

**Issue by dpanic** [golang/go#60145] opened 2023-05-12 09:26 UTC
### What version of Go are you using (`go version`)?
<pre>
go version go1.20.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/dpanic/go/bin"
GOCACHE="/home/dpanic/.cache/go-build"
GOENV="/home/dpanic/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dpanic/go/pkg/mod"
GONOPROXY="*.internal.mycompany.com"
GONOSUMDB="*.internal.mycompany.com"
GOOS="linux"
GOPATH="/home/dpanic/go"
GOPRIVATE="*.internal.mycompany.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1976099889=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

go get -u ./...

### What did you expect to see?
Finished go mod update

### What did you see instead?
Stuck process

![image](https://github.com/golang/go/assets/346557/65458b80-c487-47aa-a378-49b5fa7dd449)

**Comment by seankhliao** [comment] 2023-05-12 09:59
please provide a repo that reproduces the issue

**Comment by dpanic** [comment] 2023-05-12 10:37
> please provide a repo that reproduces the issue

Here is replica of that repo https://github.com/dpanic/broken

I can't share original repo because of the NDA.

Let's say that:
- on new go.mod I don't have problem
- on old go.mod I have problem, and I have different go.sum (which could be okay)

I added go.mod.broken_one and go.sum.broken_one from the repo I can't share

**Comment by seankhliao** [comment] 2023-05-12 14:40
cc @bcmills @matloob

**Comment by bcmills** [comment] 2023-05-12 16:03
@dpanic, there is a known severe bug in `go get` (#55955). Could you try patching in https://go.dev/cl/471595 and see if that fixes your case too?

**Comment by bcmills** [comment] 2023-05-12 16:06
Also, how long was the process stuck, and were there any open connections to `proxy.golang.org` or running `git` commands at the time?

**Comment by dpanic** [comment] 2023-05-14 20:22
> Also, how long was the process stuck, and were there any open connections to `proxy.golang.org` or running `git` commands at the time?

I let it run for 6h ... I did strace on process (I can do it again and share with you output if needed, it was constantly doing something, looked like dead loop to me). 

No connections to proxy.golang.org at the time of process being stuck, nor before. No git commands either.
<img width="1350" alt="image" src="https://github.com/golang/go/assets/346557/78336221-68c8-43c8-ab81-d9848f58c58a">

**Comment by dpanic** [comment] 2023-05-14 20:38
> https://go.dev/cl/471595



> @dpanic, there is a known severe bug in `go get` (#55955). Could you try patching in https://go.dev/cl/471595 and see if that fixes your case too?

@bcmills tried, git clone than git checkout to branch which already has patch applied. compiled Go from scratch.

Something wrong with this version...Maybe I did something wrong, IDK.
<img width="833" alt="image" src="https://github.com/golang/go/assets/346557/ab029a5e-ad4c-4955-a171-79db44cc7f5b">

**Comment by bcmills** [comment] 2023-05-15 14:04
The `missing GOSUMDB` error comes from here:
https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/modfetch/sumdb.go;l=80;drc=f229e7031a6efb2f23241b5da000c3b3203081d6

That suggests that the environment in which you are running `go get` does not match the `go env` output from the original issue report: that `go env` shows `GOSUMDB="sum.golang.org"`, which should take the `knownGOSUMDB` path here:
https://cs.opensource.google/go/go/+/master:src/cmd/go/internal/modfetch/sumdb.go;l=75-77;drc=f229e7031a6efb2f23241b5da000c3b3203081d6

**Comment by dpanic** [comment] 2023-05-15 20:00
@bcmills tnx, works when I set GOSUMDV:
```GOSUMDB="sum.golang.org" /home/dpanic/Downloads/go/bin/go get -x -u ./...```

This version of Go resolved my issue!

Thanks

**Comment by seankhliao** [comment] 2023-05-15 20:07
Duplicate of #55955

**Closed by seankhliao** 2023-05-15 20:07 UTC
Labels: NeedsInvestigation, GoCommand, modules
