### ISSUE TITLE
SHA256 not supported

### ISSUE THREAD

**Issue by neochine** [golang/go#69812] opened 2024-10-08 14:37 UTC
### Go version

go version go1.23.2 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/opt/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/opt/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.2'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/root/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2975773539=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

go install [codeberg.org/neochine/gonix@latest](http://codeberg.org/neochine/gonix@latest)
warning: GOPATH set to GOROOT (/opt/go) has no effect
go: [codeberg.org/neochine/gonix@latest](http://codeberg.org/neochine/gonix@latest): [codeberg.org/neochine/gonix@v0.0.1](http://codeberg.org/neochine/gonix@v0.0.1): invalid version: git fetch -f origin refs/heads/:refs/heads/ refs/tags/:refs/tags/ in /opt/go/pkg/mod/cache/vcs/ccc416ebf798b6d69afbb3ffa29b6559b233b8aac716cdb17a6ad00f5566b67c: exit status 128:
fatal: mismatched algorithms: client sha1; server sha256

### What did you see happen?

Error

### What did you expect to see?

Install successfully. Re initialized project with sha1 and now its installable, since project initilazed with git init --object-format=sha256 is not

### Reproduction
git clone https://codeberg.org/Neochine/gonix/
cd gonix
rm .git -r
Create sha256 repo using codeberg
git init --object-format=sha256
git add . && git commit -m "Gonix"
git remote add origin yourlink
git push -u origin master
git tag v0.0.1
git push origin v0.0.1
go install codeberg.org/yourusername/gonix@latest

**Comment by seankhliao** [comment] 2024-10-08 15:47
Duplicate of #68359

**Closed by seankhliao** 2024-10-08 15:47 UTC
