### ISSUE TITLE
reflect: structs with embedded members are unconstructable

### ISSUE THREAD

**Issue by infogulch** [golang/go#65144] opened 2024-01-18 02:36 UTC
### Go version

gotip

### What did you do?

I'm trying to create a struct with `reflect` that is equal to an existing struct that has embedded/anonymous fields.

### What did you see happen?

I found that it is not possible to use `reflect` to create a struct with embedded/anonymous members.

Generally, it *is* possible to create a struct with reflect *if* all the fields are named, but not in this case where the fields are unnamed (embedded).

I created a playground snippet which I hope clearly demonstrates the issue, as well as what I expect to happen under normal circumstances:

https://go.dev/play/p/BmUv11ZJkay?v=gotip

### What did you expect to see?

I expect it to be possible to build a struct with reflect that can be compared as equal to any existing struct with public members.

**Comment by seankhliao** [comment] 2024-01-18 08:54
Duplicate of #24781

**Closed by seankhliao** 2024-01-18 08:54 UTC
Labels: compiler/runtime
