### ISSUE TITLE
cmd/go: tidy and vendor do not record dependencies of '// +build ignore' go:generate sources

### ISSUE THREAD

**Issue by angelofdeauth** [golang/go#38061] opened 2020-03-25 07:48 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/aescaler/.cache/go-build"
GOENV="/home/aescaler/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/aescaler/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build295363184=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Create a package with dependencies built from `go:generate` tags
```
//go:generate go run generator.go
```

Attempt to use `go mod vendor` and `go mod tidy`

https://github.com/angelofdeauth/xnotify/

under `pkg/box`:

generate.go script called using preprocessor tags in box.go

Since generate.go is not using `package box`, `go mod tidy` and `go mod vendor` do not correctly resolve its imports. 

### What did you expect to see?

`go mod vendor` and `go mod tidy` correctly resolve imports of build-time dependencies.

### What did you see instead?

imports are not correctly resolved, added to go.mod or vendor/modules.txt, or downloaded to the vendor folder.

**Comment by seankhliao** [comment] 2020-03-25 14:45
Does go throw an error? Is there a specific import that should be added but isn't?

**Comment by bcmills** [comment] 2020-03-25 15:09
You are using the word “correctly”, but it isn't at all obvious to me that the observed behavior is “incorrect”. Can you describe what you expected to see and what you did see in terms of the actual dependencies used?

**Comment by angelofdeauth** [comment] 2020-03-25 15:22
> You are using the word “correctly”, but it isn't at all obvious to me that the observed behavior is “incorrect”. Can you describe what you expected to see and what you did see in terms of the actual dependencies used?

https://github.com/angelofdeauth/xnotify/blob/master/pkg/box/generator.go is a script that is run at build time using `go generate`, and is called from https://github.com/angelofdeauth/xnotify/blob/master/pkg/box/box.go using the `//go:generate` preprocessor tags. 
`generator.go` uses `package main` as it isn't compiled as part of the module/package and is instead just a one-off which generates a file that is included in the module/package.

Without this line: https://github.com/angelofdeauth/xnotify/blob/4263fb794911e4bf6e6350ff262b593ae07843b6/pkg/box/hack.go#L11 , `go mod vendor` and `go mod tidy` do not recognize `"github.com/gobuffalo/here"` as a project dependency at all, and there is no dependency listed in my `go.mod`, `vendor/modules.txt` or files in `vendor/{{importname}}`. 
This is a problem, as when I try to run `go generate`, it fails stating that the dependency is not found in the current module.

**Comment by angelofdeauth** [comment] 2020-03-25 15:38
I just realized, it's actually the `//+build ignore` directive in `generator.go` https://github.com/angelofdeauth/xnotify/blob/4263fb794911e4bf6e6350ff262b593ae07843b6/pkg/box/generator.go#L9 that's causing this. I would argue the intended behaviour here is still valid, as `generator.go` should not be built into the final executable, but the tooling functionality does not reflect that ability.

**Comment by bcmills** [comment] 2020-03-25 15:47
If you don't want the file to be ignored, use a build constraint other than `ignore`.

(`// +build tools` is common: see http://golang.org/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module.)

**Comment by bcmills** [comment] 2020-03-25 15:48
Or, I suppose, if you want the dependency to be resolved dynamically instead of a specific version, set `GOFLAGS=-mod=mod` or pass `-mod=mod` explicitly on the `go:generate` command line.

**Comment by bcmills** [comment] 2020-03-25 15:55
Duplicate of #29598

**Closed by bcmills** 2020-03-25 15:55 UTC
Labels: NeedsInvestigation, modules

**Comment by angelofdeauth** [comment] 2020-03-25 17:53
Awesome, thanks for the link @bcmills . I've looked at the docs on golang.org, they're less descriptive. This is much more clear.
