### ISSUE TITLE
plugin: Open : ` invalid ELF header` with non-main package

### ISSUE THREAD

**Issue by wiless** [golang/go#19882] opened 2017-04-07 21:40 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build619068367=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### What did you do?
```
package plugme

import "fmt"

func Run() {
	fmt.Print("Hello, I am running..")
}
```
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
https://play.golang.org/p/nLF1o0CejJ 

Seems that when we call the `plugin.Open()` it expects that the functions are defined with the same `main` package.  Usually, when the built `abcd.so` plugin is built and shipped we may not know the package name.

### What did you expect to see?
```
Hello, I am running..
```

### What did you see instead?
```
panic: plugin.Open: /root/go/src/github.com/wiless/plugin.so: invalid ELF header

goroutine 1 [running]:
main.main()
	/root/go/src/github.com/wiless/main.go:10 +0x1e6
```

**Comment by ianlancetaylor** [comment] 2017-04-07 23:10
How precisely did you build the plugin?

**Comment by wiless** [comment] 2017-04-07 23:15
`go build -buildmode=plugin -o plugin.so`

**Comment by ianlancetaylor** [comment] 2017-04-07 23:20
What is the output of `readelf -h /root/go/src/github.com/wiless/plugin.so`?

**Comment by wiless** [comment] 2017-04-08 06:23
```

File: plugin.so(__.PKGDEF       )
readelf: Error: Not an ELF file - it has the wrong magic bytes at the start

File: plugin.so(_go_.o          )
readelf: Error: Not an ELF file - it has the wrong magic bytes at the start
```

**Comment by ianlancetaylor** [comment] 2017-04-08 14:04
That is what I would expect for a file built without `-buildmode=plugin`.

Oh, I see what you mean.  If you use `-buildmode=plugin` but you don't build a main package, you get an object that can go into a plugin, but you don't get an actual plugin.  That is a meaningful thing to do, but can be confusing.  Hmmm.

**Comment by ianlancetaylor** [comment] 2017-04-08 14:05
CC @crawshaw

**Comment by tzneal** [comment] 2017-04-13 21:08
Duplicate of #19023

**Comment by tzneal** [comment] 2017-04-21 19:44
Duplicate of #19023, which is the older issue.

**Closed by tzneal** 2017-04-21 19:44 UTC
Labels: WaitingForInfo
