### ISSUE TITLE
proposal: bytes: Buffer should implement io.Seeker

### ISSUE THREAD

**Issue by ZaniaDeveloper** [golang/go#21899] opened 2017-09-15 05:59 UTC
Hello,

It'd be interesting that the type `bytes.Buffer` implements interface `io.Seeker`
I think that it can be used several time if not i can't see how do it simplier than copy `byte.Buffer` source file and add the missing method.

How do you think about it?

**Comment by dsnet** [comment] 2017-09-15 06:47
Marking this as duplicate of #21592, which has also mentioned why adding `Buffer.Seek` is problematic.

**Closed by dsnet** 2017-09-15 06:47 UTC
Labels: Proposal
