### ISSUE TITLE
encoding/csv: reader wrongly parses quoted trailing quotes and merges neighboring items

### ISSUE THREAD

**Issue by teghnet** [golang/go#65661] opened 2024-02-11 18:58 UTC
### Go version

go version go1.22.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/.cache/go-build'
GOENV='/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/go/go1.22.0'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/go/go1.22.0/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/projects/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3421635005=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I was parsing a simple CSV file.

see: https://go.dev/play/p/0oemKdT4_dg

The easiest way to show the problem is in a test.
This test in `src/encoding/csv/reader_test.go` should pass
```go
{
	Name:       "QuotedLazyQuotes",
	Input:      `§"a "word"",§"1"2",§a",§"b`,
	Output:     [][]string{{`a "word"`, `1"2`, `a"`, `b`}},
	LazyQuotes: true,
}
```

### What did you see happen?

The result was wrong. I got a single cell with the comma inside.

### What did you expect to see?

We should be seeing 2 separate cells.

**Comment by seankhliao** [comment] 2024-02-11 23:40
Duplicate of #56329

**Closed by seankhliao** 2024-02-11 23:40 UTC

**Comment by teghnet** [comment] 2024-02-13 00:53
Thanks. Didn't find that other reported issue.
