### ISSUE TITLE
x/tools/go/analysis/passes/printf: false positive breaks tests in package

### ISSUE THREAD

**Issue by mark-pictor-csec** [golang/go#69831] opened 2024-10-09 21:52 UTC
### Go version

go1.23, go1.22, tip

### Output of `go env` in your module/workspace:

```shell
N/A (repro in playground)
```

### What did you do?

I wrote a function which takes optional args of type `any`; if the first optional arg is of type `string`, it is passed to `fmt.Sprintf` as the format. 

The vet check believes I'm incorrectly providing a format specifier; until I found a way to defeat the check, it prevented any tests within the package from running.

https://go.dev/play/p/b6AupyJEr6s

printf analyzer documentation is [available on pkg.go.dev](https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/printf)

### What did you see happen?

The printf checker produces a false positive, and there doesn't seem to be a way to disable it. I was unable to run any tests in the affected package until I found a way to defeat the checker.

### What did you expect to see?

`go test` and the playground compile and execute the code.

**Comment by zigo101** [comment] 2024-10-10 10:04
It is strange that vet message

```
play.PrintIdx call has possible Printf formatting directive %d
```

 is caused by the 

```
			x = fmt.Sprint(extra...)
```

line instead of the

```
			x = fmt.Sprintf(f, extra[1:]...)
```

line.

**Comment by timothy-king** [comment] 2024-10-10 15:09
cc @adonovan

**Comment by mark-pictor-csec** [comment] 2024-10-11 17:32
Commenting out lines 32 and 33 does cause the check to pass, which I was not at all expecting. Thanks for the hint!

**Comment by mark-pictor-csec** [comment] 2024-10-11 17:43
This seems like something that's pretty unlikely to be hit, and difficult to fix. Feel free to close it if you want.

**Comment by adonovan** [comment] 2024-10-11 19:00
To be clear, commenting out L32-33 doesn't really improve the function, as it still exhibits "conditionally printf-like" behavior. It would better if it was either always print-like or always printf-like, as these are well understood paradigms for most Go programmers, and the vet tool will enforce the correct discipline. For example:

```go
// printf-like:

func PrintfIdx(s string, n int, format string, args ...any) {
	if len(s) == 0 {
		return
	}
	x := fmt.Sprintf(format, args...)
	fmt.Fprintf(os.Stderr, "\n%q  %s\n %*s  (%d)\n", s, x, n+1, "^", n)
}

PrintfIdx("", 0, "%s", 123) // <-- vet will point out the mismatch between %s and 123


// print-like:

func PrintIdx(s string, n int, args ...any) {
	if len(s) == 0 {
		return
	}
	x := fmt.Sprint(args...)
	fmt.Fprintf(os.Stderr, "\n%q  %s\n %*s  (%d)\n", s, x, n+1, "^", n)
}

PrintIdx("", 0, "%s", 123) // <-- vet will point out that the first argument looks like an unwanted format string.
```

**Comment by adonovan** [comment] 2024-10-11 19:00
Working as intended; closing.

**Closed by adonovan** 2024-10-11 19:00 UTC
Labels: NeedsInvestigation, Tools
