### ISSUE TITLE
path/filepath: endless loop in EvalSymlinks because it resolves a link to the same path it asked for

### ISSUE THREAD

**Issue by ericwj** [golang/go#40176] opened 2020-07-12 14:30 UTC
### What version of Go are you using (`go version`)?
1.14.4

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Windows

### What did you do?
```PowerShell
$vhd = New-VHD -Path Test.vhdx -SizeBytes 3MB -Fixed
$vhd | Mount-VHD
$vhd = Get-VHD Test.vhdx # refresh IsAttached etc
$vhd | Get-Disk | Initialize-Disk -PartitionStyle GPT
$part = $vhd | Get-Disk | New-Partition -UseMaximumSize -AssignDriveLetter:$false
$vol = $part | Format-Volume -FileSystem NTFS
mkdir Test
$part | Add-PartitionAccessPath -AccessPath "$PWD\Test"
```

```
package main

import ("path/filepath"; "fmt")

func main() {
   p, err := filepath.EvalSymlinks("Test")
   if err != nil { panic(err) }
   fmt.Println(p)
}
```

### What did you expect to see?
"$PWD\Test"

### What did you see instead?
EvalSymlinks: too many links

**Comment by ericwj** [comment] 2020-07-12 14:31
#39786

The code path is not using go API surface to do path math or using private internal code paths that go API surface uses and gets it wrong.

**Comment by networkimprov** [comment] 2020-07-12 17:32
Pls put the code in a block bracketed by ` ``` ` lines

**Comment by networkimprov** [comment] 2020-07-14 06:42
@gopherbot add OS-Windows

cc @alexbrainman

**Comment by alexbrainman** [comment] 2020-07-19 05:44
@ericwj thank you for creating this issue. I think this issue is a duplicate of #39786. Same reproduction steps as per @networkimprov (see https://github.com/golang/go/issues/39786#issuecomment-657197399). No?

Alex

**Comment by ericwj** [comment] 2020-07-19 06:05
Not really, the code paths are different. This one fails for links to a target volume that does have a DOS device name (C:\EmptyDir) while the other one only fails for links to a target volume that doesn't.

I think the confusion is that the other issue was filed with the error that occurs here, while in the description it sais that the situation had been that there was no DOS device name. But then you don't get the 'too many links' error.

**Comment by alexbrainman** [comment] 2020-07-19 08:13
> Not really,

If this is not a dup of #39786. I am happy to investigate this separately. But I cannot run your steps. See https://github.com/golang/go/issues/39786#issuecomment-660606258 for details.

Alex

**Comment by qmuntal** [comment] 2022-11-29 09:03
This failure mode can be reproduced without Hyper-V with the following code snippet:

```go
package main

import (
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	err := os.Symlink("./self", "./self")
	if err != nil {
		panic(err)
	}
	p, err := filepath.EvalSymlinks("./self")
	if err != nil {
		panic(err)
	}
	fmt.Println(p)
}
```

**Comment by neild** [comment] 2022-11-30 15:17
In the example of `ln -s self self` (producing a symlink from `self` to itself), the current behavior is correct: The target of the link cannot be resolved, because there is an infinite cycle of links. We can see this without involving Go at all:

```
$ ln self self
$ ls -l self
lrwxr-xr-x  1 dneil  wheel  4 Nov 30 10:15 self -> self
$ cat self
cat: self: Too many levels of symbolic links
```

I'm not familiar with the Windows filesystem operations in the original example in this issue, so I'm not certain what the correct behavior there is.

**Comment by neild** [comment] 2022-11-30 15:57
The equivalent to what `ls -l self` is doing is `os.Lstat`.

`filepath.EvalSymlinks` evaluates all symlinks within a path, returning an equivalent path that contains no symlinks. In the case of a link cycle, there is no such path and `EvalSymlinks` returns an error.

**Comment by qmuntal** [comment] 2022-12-01 13:16
> filepath.EvalSymlinks evaluates all symlinks within a path, returning an equivalent path that contains no symlinks. In the case of a link cycle, there is no such path and EvalSymlinks returns an error.

My bad, I thought `EvalSymlinks` was another thing. Then I don't know how to reproduce this issue without using a virtual hard drive.

**Closed** 2024-03-04 19:00 UTC
Labels: OS-Windows, NeedsInvestigation
