### ISSUE TITLE
x/tools/gopls: Doesn't auto-complete package statements for new files

### ISSUE THREAD

**Issue by segevfiner** [golang/go#40713] opened 2020-08-12 08:50 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.7 darwin/amd64
</pre>

<pre>
# gopls version
golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=
</pre>

VS Code version v1.47.3
vscode-go v0.16.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/segev/Library/Caches/go-build"
GOENV="/Users/segev/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/segev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.7/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b_/c6yh0ksn63d1yy192x2p9f4c0000gn/T/go-build425202633=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. Add a new file to a package that already has files. (Using Go modules)
2. Try to auto-complete `pack` or some similar prefix at the start of the file.
3. You get no completions.

(Using gopls with vscode-go)

### What did you expect to see?
I expect to see a complete for a package statement with the name of the package, saving me the need to type it out.

### What did you see instead?
I get no such completion.

I would also expect it to provide package statement completion for the first file in a new package, guessing what should be the package name based on the import path.

**Comment by stamblerre** [comment] 2020-08-12 14:40
Duplicate of https://github.com/golang/go/issues/34008

**Closed by stamblerre** 2020-08-12 14:40 UTC
Labels: Tools, gopls
