### ISSUE TITLE
go.dev: docker/docker/client majorly out of date

### ISSUE THREAD

**Issue by stevenh** [golang/go#38799] opened 2020-05-01 20:33 UTC
### What is the URL of the page with the issue?
 https://pkg.go.dev/github.com/docker/docker/client?tab=doc
 
 
### What is your user agent?
 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 
 
### Screenshot

![image](https://user-images.githubusercontent.com/104239/80839435-25759c80-8bf3-11ea-9c7d-831a155e11fe.png)

### What did you do?
 
Load the page
 
### What did you expect to see?
 
 Up to date docs
 
### What did you see instead?

Docs from the 2017 version where as godoc.org seems correct and has the NewClientWithOpts constructor e.g.
https://godoc.org/github.com/docker/docker/client#NewClientWithOpts

**Comment by myitcv** [comment] 2020-05-01 20:36
Related to/dup of https://github.com/golang/go/issues/36811

**Comment by julieqiu** [comment] 2020-05-02 16:11
Thanks for the feedback, @stevenh!

pkg.go.dev shows the "latest" version of a module, which is defined in https://golang.org/cmd/go/#hdr-Module_queries as the `latest available tagged version, or else the underlying source repository's latest untagged revision`.

In this case, the latest version of github.com/docker/docker is `v1.13.1`. You can confirm this by visiting
https://proxy.golang.org/github.com/docker/docker/@latest, which at this moment returns the following:
```
{
"Version": "v1.13.1",
"Time": "2017-02-08T05:58:41Z"
}
```
You can visit https://golang.org/cmd/go/#hdr-Module_proxy_protocol for details on the `@latest` endpoint.

In contrast, godoc.org shows the version of documentation at master, since it does not support modules. 

As @myitcv mentioned, we are working on providing better support for viewing documentation at master for pkg.go.dev (#36811). In the meantime, you can use [this workaround](https://github.com/golang/go/issues/36811#issuecomment-579404726) to view the documentation at master for godoc.org/github.com/docker/docker/client.

Closing as a duplicate of #36811.

**Closed by julieqiu** 2020-05-02 16:11 UTC
Labels: go.dev
