### ISSUE TITLE
Go mod command throws an unexpected error

### ISSUE THREAD

**Issue by kartikPatidar** [golang/go#45356] opened 2021-04-02 15:10 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
not sure

### What operating system and processor architecture are you using (`go env`)?
OS : Windows 10
64-bit
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\lenovo\AppData\Local\go-build
set GOENV=C:\Users\lenovo\AppData\Roaming\go\env  
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\lenovo\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\lenovo\go
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.2
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\development\Go\secondHello\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\lenovo\AppData\Local\Temp\go-build865099555=/tmp/go-build -gno-record-gcc-switches
PS E:\development\Go\secondHello> go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\lenovo\AppData\Local\go-build
set GOENV=C:\Users\lenovo\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\lenovo\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\lenovo\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.2
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\development\Go\secondHello\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\lenovo\AppData\Local\Temp\go-build4022022924=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

I was following this official tutorial : https://golang.org/doc/tutorial/call-module-code
I ran the following command : go mod edit -replace=example.com/greetings=../greetings
got the following error: go mod edit -replace=example.com/greetings=../greetings

the command works fine when used without "=" sign : go mod edit -replace example.com/greetings=../greetings

### What did you expect to see?
the command should add the following line in go.mod file :
replace example.com/greetings => ../greetings

### What did you see instead?
got the following error: go mod edit -replace=example.com/greetings=../greetings

**Comment by kartikPatidar** [comment] 2021-04-02 15:13
I created this PR : [https://github.com/golang/website/pull/46]
but got to know that the command should work both ways.

**Comment by seankhliao** [comment] 2021-04-02 15:14
Duplicate of #44924

**Closed by seankhliao** 2021-04-02 15:14 UTC
