### ISSUE TITLE
net/http: content type detection does not work correctly for some documents that start with HTML comments

### ISSUE THREAD

**Issue by guliyevemil1** [golang/go#25771] opened 2018-06-07 03:45 UTC
Some website documents start with "".

None of these cases are detected correctly because "<!--" htmlSig is treated like a regular HTML tag when in reality behaves slightly differently.

### What version of Go are you using (`go version`)?

❯ go version
go version go1.10.2 darwin/amd64

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

❯ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?

```
package main

import (
	"fmt"
	"net/http"
)

func main() {
	fmt.Println(http.DetectContentType([]byte(`<!--[if !IE]> This has been served from cache <![endif]--><html><body>Hello,world</body></html>`)))
	fmt.Println(http.DetectContentType([]byte(`<!-- [if !IE]> This has been served from cache <![endif]--><html><body>Hello,world</body></html>`)))
}
```

https://play.golang.org/p/f6-N3OA9FGU

### What did you expect to see?

text/html; charset=utf-8
text/html; charset=utf-8

### What did you see instead?

text/plain; charset=utf-8
text/html; charset=utf-8

**Comment by agnivade** [comment] 2018-06-07 04:16
We follow the algorithm laid out at  http://mimesniff.spec.whatwg.org/. According to [it](https://mimesniff.spec.whatwg.org/#identifying-a-resource-with-an-unknown-mime-type), the string `<!--` must be followed by a tag-terminating byte. A [tag terminating byte](https://mimesniff.spec.whatwg.org/#tag-terminating-byte) is either a space or closing angle bracket.

So this is working as intended. If you want this changed, I would suggest raising an issue at https://github.com/whatwg/mimesniff.

**Closed by agnivade** 2018-06-07 04:16 UTC
Labels: Documentation
