### ISSUE TITLE
net/http/httputil: ReverseProxy does not set host header correctly

### ISSUE THREAD

**Issue by broady** [golang/go#28168] opened 2018-10-12 04:05 UTC
The HTTP/2 client prefers Request.Host over Request.URL.Host:

https://github.com/golang/go/blob/a0d6420d8be2ae7164797051ec74fa2a2df466a1/src/net/http/h2_bundle.go#L7947-L7954

ReverseProxy's default Director only sets Request.URL.Host, and not Request.Host, so the request would get proxied to the same host, rather than the proxy target. This resulted in an infinite loop on golang.org (see Issue #28134).

https://github.com/golang/go/blob/a0d6420d8be2ae7164797051ec74fa2a2df466a1/src/net/http/httputil/reverseproxy.go#L105-L121

**Comment by bradfitz** [comment] 2018-10-12 05:19
It's preferring the req.Host first per the docs on net/http.Request.Host:

```go
        // For client requests Host optionally overrides the Host
        // header to send. If empty, the Request.Write method uses
        // the value of URL.Host. Host may contain an international
        // domain name.
        Host string
```

I worry it might not be safe to change this without breaking other people. (There's the usual forward-proxy vs reverse-proxy distinction that people often bring up, too, which is kinda related here.) But if we have different behavior already whether we use HTTP/1 vs HTTP/2 to the backend, then I could see changing it.

**Comment by ahmetb** [comment] 2019-03-30 00:21
I also hit this! It applies to both http/1 and http/2 based on my experimentation.

I refactored both `Director` and `Transport` (http.RoundTripper) to set the `Host` header, yet the local hostname of my server leaks to the backend and therefore my program doesn't function correctly.

I basically rewrite the `/get` request to send to `https://httpbin.org/get` while setting the `Host: httpbin.org` and `Scheme = "https"`. The echoed response shows that the `Host` header remained as `localhost:8080`.

I also asked this at https://stackoverflow.com/questions/55426924/go-httputil-reverseproxy-not-overriding-the-host-authority-header, my minimal repro below:

```
package main

import (
    "log"
    "net/http"
    "net/http/httputil"
)

func main() {
    proxy := &httputil.ReverseProxy{
        Transport: roundTripper(rt),
        Director: func(req *http.Request) {
            req.URL.Scheme = "https"
            req.URL.Host = "nghttp2.org"
            req.URL.Path = "/httpbin" + req.URL.Path
            req.Header.Set("Host", "nghttp2.org") // <--- I set it here first
        },
    }
    log.Fatal(http.ListenAndServe(":8080", proxy))
}

func rt(req *http.Request) (*http.Response, error) {
    log.Printf("request received. url=%s", req.URL)
    req.Header.Set("Host", "nghttp2.org") // <--- I set it here as well
    defer log.Printf("request complete. url=%s", req.URL)

    return http.DefaultTransport.RoundTrip(req)
}


// roundTripper makes func signature a http.RoundTripper
type roundTripper func(*http.Request) (*http.Response, error)

func (f roundTripper) RoundTrip(req *http.Request) (*http.Response, error) { return f(req) }
```

**Comment by uucckk** [comment] 2019-04-25 01:56
Goang's access to nginx through proxy can not correctly orientate the website, is it solved at present?

If it's solved, you can tell me which version, or solve it by other means.thinks.

**Comment by ahmetb** [comment] 2019-04-25 04:26
Turns out I needed to set `req.Host` field instead and that solved it for me above.
https://stackoverflow.com/questions/55426924/go-httputil-reverseproxy-not-overriding-the-host-header

**Comment by TheDiveO** [comment] 2019-07-09 22:02
Lost 1h searching for my downstream server returning 403 when going through the `httputil.ReverseProxy` with the stock `Director`, while `curl` worked as expected. Finally, I found this bug report and I can confirm that it is necessary to set `req.Host` to `req.URL.Host` for the reverse proxy to work and not cause endless recursion.

At least, the implementation of `Director` in `NewReverseProxyForSingleHost` should be fixed and properly documented.

**Comment by stevenh** [comment] 2020-03-06 21:37
Confirmed this had me digging for some time too.

**Comment by docmerlin** [comment] 2020-05-15 18:40
Welp, we just ran into this.

**Comment by domdom82** [comment] 2020-12-21 13:07
Ran into the same issue in almost 2021 now. Fixed it by manually adding
```
req.Host = targetURL.Host
```
in the director function.. but why do I have to do this!?

**Closed** 2022-08-16 20:02 UTC
Labels: NeedsFix
