### ISSUE TITLE
cmd/go: don't warn about "no non-test Go files" when building/installing wildcard

### ISSUE THREAD

**Issue by clintmod** [golang/go#22409] opened 2017-10-23 23:09 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.9.1 darwin/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/clint/code/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/clint/code/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tr/j87dsghd3fsdh1m98b76fjrw0000gn/T/go-build293369783=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
- `cd $GOPATH`
- `go get github.com/clintmod/goBuildBug`
- `cd $GOPATH/src/github.com/clintmod/goBuildBug`
- `go install ./...`

### What did you expect to see?
The build to succeed.

### What did you see instead?
go build github.com/clintmod/goBuildBug/tests: no non-test Go files in github.com/clintmod/goBuildBug/tests

**Comment by davecheney** [comment] 2017-10-23 23:24
> cd $GOPATH/github.com/clintmod/goBuildBug

^ this is the wrong path, did you mean

`cd $GOPATH/src/github.com/clintmod/goBuildBug`

**Comment by clintmod** [comment] 2017-10-23 23:31
@davecheney yep… fixed

**Comment by gbbr** [comment] 2017-10-24 10:42
> yep… fixed

Based on the above reply by the OP. I assume this can now be closed.

**Comment by clintmod** [comment] 2017-10-24 11:44
can we reopen?
I was correcting the bad path in the steps to repro… the expected behavior is that the build should not fail because there are only test files in the dir.

**Comment by gbbr** [comment] 2017-10-24 11:50
Sure, I've just assumed based on your answer that it was fixed. Please close it yourself if it all works out.

**Comment by iand** [comment] 2017-11-13 14:50
Duplicate of https://github.com/golang/go/issues/8279

**Comment by ianlancetaylor** [comment] 2018-03-29 18:48
I think it's clear that `go instasll github.com/clintmod/goBuildBug/tests` should fail with the "no non-test Go files" error.  So I think what you are saying is that you expect `go install ./...` to succeed even if some of the packages named by `./...` can not be built.  I've updated the issue title accordingly.  I don't know whether this is a good idea or not.  The current approach is easy to understand.

**Comment by karalabe** [comment] 2018-04-18 11:30
Just to add my 2c, I've hit this exact issue just now.

My use case is that I'm doing some code generation in a CI build step, and as a last sanity check I try to build a huge repository to make sure that all dependencies (for the generated code too) are correctly vendored in. The simplest way is to do `go install ./...`, however this fails the CI build step, since there's a folder which only contains tests.

I fully agree that a warning for this scenario is nice. But does it really make sense to fail the entire process for it? I'd expect `./...` to build what make sense, and skip what doesn't.

**Comment by powerman** [comment] 2018-04-20 04:56
Same here, also in CI for caching deps:
```
+ CGO_ENABLED=0
+ go install -v -installsuffix static all
github.com/go-playground/form/benchmarks
go build github.com/go-playground/form/benchmarks: no non-test Go files in /go/src/github.com/go-playground/form/benchmarks
```

**Comment by agnivade** [comment] 2018-04-20 05:50
@powerman - You are directly trying to install the `benchmarks` package. That will always fail. 

This issue is about trying to install/build a repo with a `./..` and not fail the entire step because an internal folder contains only `_test` files.

This can be solved with a simple workaround of adding any dummy file with a non `_test` suffix in the same package. Just have a ignore.go file with a one-liner `package tests`, and everything works.

In general, our approach towards warnings have been to avoid them in the first place by fixing them. And if it cannot be fixed, throw an error. So, I am not sure whether we should throw a warning. Even if the above workaround is not feasible in some cases, you can always do a `go list` and install the packages separately.

**Comment by powerman** [comment] 2018-04-20 06:53
> You are directly trying to install the benchmarks package.

No, I'm not. It's `go install all` trying to install that package, not me. All I want is to compile and cache all already downloaded packages in a docker image, which will be later used as base image for building my projects in CI - to avoid re-compiling most of my project's dependencies to speedup CI build. Thus I use `go install all` - is there any better way to do this? `./...` doesn't differs much from `all` in this sense - reason why I use `all` is to rebuild also stdlib (to get stdlib cached both with and without `CGO_ENABLED=0`, because some projects supports it and worth using with alpine docker image while others do not).

> This can be solved with a simple workaround of adding any dummy file with a non _test suffix

Sure, but it's not my package - it just one of often used dependencies.

**Comment by agnivade** [comment] 2018-04-20 09:50
Ah that's right. It is `all` which is doing it. But `all` applies to all packages under GOPATH. I would guess you know the dependencies needed by your app ? You can just `go get` those. And use that docker image in your CI. Or am I missing something here ?

> Sure, but it's not my package - it just one of often used dependencies.

Yep, I mentioned this above. In that case, you have to install the sub-packages separately.

Maybe @ianlancetaylor has a better solution.

**Comment by powerman** [comment] 2018-04-20 10:03
> I would guess you know the dependencies needed by your app?

More or less. It's a base image shared between several projects with different dependencies, so it include most common ones.

> You can just go get those. And use that docker image in your CI.

I do go get those. And everything is fine, so far.

> Or am I missing something here?

Probably this issue happens because after I did go get I wanna rebuild all these packages plus stdlib once again, this time with `CGO_ENABLED=0`, so I run this: `CGO_ENABLED=0 go install -v -installsuffix static all` … and it usually fails, for one reason or another, because it tries to install every downloaded package, and not just ones which was installed by go get. So when it fails I run `go get -v -t all`, then go install again… and repeat that few times until success. :smile:

Probably only way to avoid these issues is give up on using `all` - just run same go get twice, with and without `CGO_ENABLED=0`, plus also run `CGO_ENABLED=0 go install -v -installsuffix static std`.

But all of this just means `all` target is currently mostly useless.

**Comment by clintmod** [comment] 2018-04-27 18:30
@ianlancetaylor
> I think it's clear that go install github.com/clintmod/goBuildBug/tests should fail with the "no non-test Go files" error.

Why is it clear? If there's nothing to do then it should do nothing and exit 0. It's fine to print a warning but why should it exit non-zero?

**Comment by ianlancetaylor** [comment] 2018-04-27 18:54
@clintmod I think it should fail because the command explicitly requests installing a specific package that can not be installed.  I don't consider this a case where there is nothing to be done.  I consider it a case where the user requested an action that is impossible.

**Closed** 2018-06-29 03:42 UTC
Labels: NeedsDecision
