### ISSUE TITLE
runtime: SIGSEGV in (*fixalloc).alloc on freebsd-amd64-12_2 builder

### ISSUE THREAD

**Issue by bcmills** [golang/go#46103] opened 2021-05-11 13:48 UTC
```
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x84d3bbb40 pc=0x41f5fb]

runtime stack:
runtime.throw({0x67f3aa, 0x2a})
	/tmp/workdir/go/src/runtime/panic.go:1198 +0x74 fp=0x7fffdebf3cf8 sp=0x7fffdebf3cc8 pc=0x43ef14
runtime.sigpanic()
	/tmp/workdir/go/src/runtime/signal_unix.go:719 +0x4a5 fp=0x7fffdebf3d58 sp=0x7fffdebf3cf8 pc=0x457645
runtime.(*fixalloc).alloc(0x845510)
	/tmp/workdir/go/src/runtime/mfixalloc.go:72 +0x3b fp=0x7fffdebf3d98 sp=0x7fffdebf3d58 pc=0x41f5fb
runtime.allocmcache.func1()
	/tmp/workdir/go/src/runtime/mcache.go:88 +0x48 fp=0x7fffdebf3dc0 sp=0x7fffdebf3d98 pc=0x41b0c8
runtime.allocmcache()
	/tmp/workdir/go/src/runtime/mcache.go:86 +0x58 fp=0x7fffdebf3df8 sp=0x7fffdebf3dc0 pc=0x41b018
runtime.(*p).init(0xc00016e800, 0x10)
	/tmp/workdir/go/src/runtime/proc.go:4835 +0x114 fp=0x7fffdebf3e18 sp=0x7fffdebf3df8 pc=0x44c9b4
runtime.procresize(0x64)
	/tmp/workdir/go/src/runtime/proc.go:5011 +0x3a9 fp=0x7fffdebf3ec8 sp=0x7fffdebf3e18 pc=0x44d2a9
runtime.startTheWorldWithSema(0x0)
	/tmp/workdir/go/src/runtime/proc.go:1256 +0xa5 fp=0x7fffdebf3f28 sp=0x7fffdebf3ec8 pc=0x4447e5
runtime.startTheWorld.func1()
	/tmp/workdir/go/src/runtime/proc.go:1093 +0x26 fp=0x7fffdebf3f48 sp=0x7fffdebf3f28 pc=0x4751a6
runtime.systemstack()
	/tmp/workdir/go/src/runtime/asm_amd64.s:383 +0x49 fp=0x7fffdebf3f50 sp=0x7fffdebf3f48 pc=0x479d69
```

[2021-05-10T23:42:56-5c48951/freebsd-amd64-12_2](https://build.golang.org/log/7fa9b56e1c97e9ea8383cec8230e9a377b8d3ddd)

CC @mknyszek @prattmic

**Comment by prattmic** [comment] 2021-05-11 14:49
FWIW, on a `freebsd-amd64-12_2` gomote, I'm seeing all `fixallocs` between approximately `0x800000000` and `0x830000000`, which is fairly close to the crash address, though I didn't see any as high as `0x840000000`

**Comment by mknyszek** [comment] 2021-05-19 17:56
Closing as a duplicate of #46272.

**Closed** 2021-05-19 17:56 UTC
Labels: NeedsInvestigation
