### ISSUE TITLE
x/vgo: can't get 1.1.5(not v1.1.5) format version

### ISSUE THREAD

**Issue by thinkerou** [golang/go#27024] opened 2018-08-16 09:56 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```shell
➜  gin git:(up-version) ✗ go version
go version go1.10.3 darwin/amd64
```

### Does this issue reproduce with the latest release?

```shell
➜  gin git:(up-version) ✗ go version
go version go1.10.3 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```shell
➜  gin git:(up-version) ✗ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tianou/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tianou/GoProjects"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zp/p4s985f95z75jkk5p88h_khm0000gn/T/go-build074914822=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?

get 1.1.5 vesion

### What did you see instead?

I have `vendor.json` which includes the follow content:

```shell
                ......
		{
			"checksumSHA1": "WqeEgS7pqqkwK8mlrAZmDgtWJMY=",
			"path": "github.com/json-iterator/go",
			"revision": "1624edc4454b8682399def8740d46db5e4362ba4",
			"revisionTime": "2018-08-06T06:07:27Z",
			"version": "1.1.5",
			"versionExact": "1.1.5"
		},
                 ......
```

when I run `vgo mod init`, I get the follow content:

```shell
...
	github.com/golang/protobuf v1.1.0
	github.com/json-iterator/go v0.0.0-20180806060727-1624edc4454b
	github.com/mattn/go-isatty v0.0.3
...
```

So, I not get `1.1.5` vesion

**Comment by agnivade** [comment] 2018-08-16 10:04
Hi @thinkerou,

You have not filled the complete issue template. There are no clear reproducible steps for us to debug the issue. We do not know the version of vgo and from where the `vendor.json` is coming from.

But it seems like it is an issue with vgo. Since vgo is now merged with the main branch, all development has occurred there. I would request you to try with the 1.11rc1 build and report back with _full_ instructions if you still see an issue.

I will close this issue now. Thank you.

**Closed by agnivade** 2018-08-16 10:04 UTC
