### ISSUE TITLE
playground response 403 status

### ISSUE THREAD

**Issue by tomheng** [golang/go#17143] opened 2016-09-18 05:18 UTC
Please answer these questions before submitting your issue. Thanks!

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

open https://play.golang.org/p/N0A7ph_xkj

### What did you expect to see?

200 ok

### What did you see instead?

403 Forbidden

play.golang.org domain resolved to 216.239.37.1

**Comment by minux** [comment] 2016-09-18 05:25
Can't reproduce here (I manually connected to the IP provided with openssl
and entered the request manually.)

**Comment by sillyousu** [comment] 2016-09-18 05:34
https://go-review.googlesource.com/#/c/14190/

>playground: block share functionality from specific countries
>This will permit us to serve *.golang.org to Chinese users.

**Comment by odeke-em** [comment] 2016-09-18 06:13
Perhaps this is a duplicate of https://github.com/golang/go/issues/16115?

**Comment by tomheng** [comment] 2016-09-18 08:34
very depressed. I could not access playground even dialing with a proxy.

**Comment by bradfitz** [comment] 2016-09-18 16:20
Sorry. This isn't our choice. We can't host user-generated content in China.

**Closed by bradfitz** 2016-09-18 16:20 UTC
