### ISSUE TITLE
x/playground: multiple files not working

### ISSUE THREAD

**Issue by Nasfame** [golang/go#63581] opened 2023-10-17 02:17 UTC
### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

https://go.dev/play/p/CZQ-NVJIFxh?v=gotip

### What did you expect to see?

Working fine

### What did you see instead?

open template.txt: no such file or directory

**Comment by bcmills** [comment] 2023-10-17 02:48
Duplicate of #38294

**Closed by bcmills** 2023-10-17 02:48 UTC
