### ISSUE TITLE
net/url: Parse+String does not round trip magnet URLs

### ISSUE THREAD

**Issue by rsc** [golang/go#20054] opened 2017-04-20 17:35 UTC
I received a private email with a report that Go inserts // in magnet URLs.
That appears to mean https://en.wikipedia.org/wiki/Magnet_URI_scheme.
Round-tripping the example from that wikipedia page:

	package main
	
	import (
		"fmt"
		"net/url"
	)
	
	func main() {
		fmt.Println(url.Parse(`magnet:?xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88a&dn`))
	}

prints

	magnet://?xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88a&dn <nil>

https://play.golang.org/p/OQKMvDyTD-

It does seem like the leading // should not be there. However, I don't know how much this matters, nor how invasive this would be to fix, nor whether the // insertion is correct for any other schemes (in particular, http and https).

/cc @bradfitz

**Comment by bradfitz** [comment] 2017-04-20 17:52
We don't special case `mailto:` so it'd be nice to not special case `magnet:`.

But perhaps we could tweak our heuristics for `URL.String`'s Opaque-vs-`://` forms.

**Comment by rsc** [comment] 2017-04-20 17:59
Hmm, so `mailto:rsc?subject=hi` round-trips but `mailto:?subject=hi` turns into `mailto://?subject=hi`.

**Comment by dsnet** [comment] 2017-04-20 18:02
Part of the problem is that we parse the Opaque field out as the empty string. When we try to round trip, we notice that the Opaque field is empty and assume it a hierarchical URL, which it is not. Perhaps, we should add a `ForceOpaque bool` field?

**Comment by rsc** [comment] 2017-04-20 19:19
I would rather not add a new bool. 

If `u.User == nil && u.Host=="" && u.Path==""`, can we print that part as an empty string instead of as `//`?

**Comment by johnnyluo** [comment] 2017-07-15 18:29
I am interested to work on this one

**Comment by odeke-em** [comment] 2017-07-19 19:20
Moving this to Go1.10 as per the CL update and given how deep we are in the freeze Go1.9.

**Comment by johnnyluo** [comment] 2017-08-29 01:45
@dsnet @odeke-em could you guys please help to run trybot on  CL https://golang.org/cl/49050, the previous trybot failed , however it is nothing to do with my change.

**Comment by odeke-em** [comment] 2017-08-29 01:54
Thanks for the ping @johnnyluo, I've ran the trybot.

**Closed** 2017-08-31 01:46 UTC
