### ISSUE TITLE
pre-modules `go get` replacement needed, as it won't work outside of existsing module with modules enabled

### ISSUE THREAD

**Issue by sirkon** [golang/go#27380] opened 2018-08-30 18:50 UTC
So, I am currently using official build (that tgz file) for Linux with export GO111MODULE=on. And I am having troubles building binaries in a old way outside of any existing module:

```
$ go get golang.org/x/tools/cmd/goimports
go: cannot find main module; see 'go help modules'
```

As you see, I am trying to download and build goimports and then put the binary into $GOPATH/bin with this go get call. Thus, we are having obvious usability downgrade. Everything is OK when I do this inside some existing module, BTW.

I believe there should be some kind of replacement. It is clear go get is not the best place for this sort of functionality after go modules enabled. I guess there should be a new command specially for this case.

**Comment by agnivade** [comment] 2018-08-31 05:05
Simply upgrading to 1.11 does not cause this issue. Explicitly setting `GO111MODULE=on` does. So that means you are explicitly telling the go command to work in module mode.

In any case, this is a duplicate of https://github.com/golang/go/issues/24250.

**Closed by agnivade** 2018-08-31 05:05 UTC

**Comment by carlca** [comment] 2018-09-02 08:54
I have come up with what is a partial solution. It is a shell script which simulates the `go get` action. The idea is that one copies the `git clone` url from `github.com` and then runs `gog.sh [⌘]v`. Of course, with Github.com you can copy the `git clone` url with just a couple of keystrokes. One can then run `go run`, `go build` or `go install` as usual. 

The contents of `gog.sh` can be found at https://gist.github.com/carlca/e97eccd545f2465f1e2a0c42356e6ffd. 

I use an alias to save me even more keystrokes, `alias gog='gog.sh'`!

**Comment by sirkon** [comment] 2018-09-02 09:42
Translation into `git clone` is a bit too sophisticated IMO, I would rather go with something like

```sh
tmpDir=`mktemp`
cd $tmpDir
go mod init tmp/for/tool
go get $1
```

It creates temporary directory, cd into it, initializes a module within, perform `go get` which downloads, compiles and installs that damn binary :)

**Comment by ctd1500** [comment] 2018-09-02 10:43
The actual "workaround" is very simple: set `GO111MODULE=auto`, or simply leave `GO111MODULE` unset and `go get` works just as it always has.

**Comment by sirkon** [comment] 2018-09-02 10:55
```
GO111MODULE=off go get …
```
is harder than
```
<exec name> …
```
