### ISSUE TITLE
x/tools/present: presenter notes do not work: Uncaught ReferenceError: getDestSlideKey is not defined

### ISSUE THREAD

**Issue by flowchartsman** [golang/go#32904] opened 2019-07-02 19:36 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/awalker/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/awalker/go"
GOPROXY=""
GORACE=""
GOROOT="/Users/awalker/opt/go"
GOTMPDIR=""
GOTOOLDIR="/Users/awalker/opt/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cf/y_tt0zms6nx39x08k23y5zsr0000gn/T/go-build767986455=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
The error in the issue title is displayed on the JS console when attempting to view a presentation which has notes. If I hit 'N', the window opens, but no notes are displayed.

### What did you expect to see?
Notes displayed.

### What did you see instead?
No notes.

Reversion to the `checkout release-branch.go1.11` fixed the issue. In addition, [only two references to `getDestSlideKey` were found in the code](https://github.com/golang/tools/search?q=getDestSlideKey&unscoped_q=getDestSlideKey), but no definition could be located.  Reversion or incomplete checkin, perhaps?

**Comment by bcmills** [comment] 2019-07-02 20:00
Probably a side-effect of [CL 178659](https://golang.org/cl/178659) for #24688.

CC @andybons @danicat

**Comment by bcmills** [comment] 2019-07-02 20:02
Duplicate of #32902

**Closed by bcmills** 2019-07-02 20:02 UTC
Labels: NeedsInvestigation, help wanted
