### ISSUE TITLE
 CGO_ENABLED=0 not working on latest golang image

### ISSUE THREAD

**Issue by Pim-Infuzed** [golang/go#60869] opened 2023-06-19 15:20 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.20.5

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ I use the golang image (latest) that bitbucket 

</pre></details>

### What did you do?

I build an image in bitbucket for linux amd64 to be used on various linux distributions.
This was all fine uptill and including 14th june.
Today on the 19th of june I did the same again and now get the CGO problem of release 1.20.

### What did you expect to see?

I didn't expect to have any problem when starting the freshly build app on a different linux, but I did:
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ...(my app)... )
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ...(my app)... )

I googled and set an CGO_ENABLED=0 environment property when building, expecting this to solve my problem. 

### What did you see instead?

I still got from the build (in the latest golang image 1.20.5 provided by bitbucket):
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ...(my app)... )
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ...(my app)... )

**Comment by seankhliao** [comment] 2023-06-19 15:37
that would indicate your executable wasn't built with cgo disabled, please include a reproducer with code and Dockerfile

note that the docker images aren't maintained by the go team

**Comment by Pim-Infuzed** [comment] 2023-06-19 17:21
my bitbucket pipeline code:

`        script:
          - source bitbucket-go-env.sh
          - BUILD=`date -u +%d-%m-%Y`
          - GOOS="linux"
          - GOARCH="amd64"
          - CGO_ENABLED="0"
          - cd $BITBUCKET_CLONE_DIR/src/main/go
          - go version
          - go env
          - go get -u
          - go build -ldflags="-X 'main.version=$APP_VERSION' -X 'main.build=$BUILD'" -o $BITBUCKET_CLONE_DIR/build/managed-grid-agent .
          - ls $BITBUCKET_CLONE_DIR
`

And here what go env outputs:
`go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/opt/atlassian/pipelines/agent/build/src/main/go/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2395635197=/tmp/go-build -gno-record-gcc-switches"`

**Comment by seankhliao** [comment] 2023-06-19 17:37
as seen from your `go env` output, `CGO_ENABLED="0"` wasn't taking effect.
I believe this is from misconfiguration in your bitbucket script, just having key=value is unlikely to persist the setting.

closing as not a bug in Go.

**Closed by seankhliao** 2023-06-19 17:37 UTC
Labels: WaitingForInfo

**Comment by Pim-Infuzed** [comment] 2023-06-19 18:04
@seankhliao that's pretty presumptuous.
I guess I have to stick with 1.19.10 for now because of this crude change.

**Comment by gnojus** [comment] 2023-06-19 20:57
@Pim-Infuzed I believe you are missing `export` in front of your commands setting the env variables.

**Comment by Pim-Infuzed** [comment] 2023-06-22 18:03
@gnojus funny how this is sometimes required.
