### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by mercer08** [golang/go#45671] opened 2021-04-21 13:21 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\mercer\AppData\Local\go-build
set GOENV=C:\Users\mercer\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\mercer\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\mercer\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\code\goprojects\sample1\hello\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\mercer\AppData\Local\Temp\go-build2538918209=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

well, i am new startar to golang, and i'm following offcial website documentation to write my first sample code
when i edit the example.com/hello module to use my local example.com/greetings module. write code in powershell just like below, and it doesn't work
```
go mod edit -replace=example.com/greetings=../greetings
```
and also,i get code from stackoverflow like below, it works
```
$ go mod edit -replace example.com/greetings=../greetings
```

### What did you expect to see?

change path like expected, And for windows developer, maybe need some tips to overcome this

### What did you see instead?
```
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

**Comment by seankhliao** [comment] 2021-04-21 13:29
Duplicate of #44924

**Closed by seankhliao** 2021-04-21 13:29 UTC
