### ISSUE TITLE
runtime: SIGSEGV in misc/cgo/testshared on s390x since CL 358674

### ISSUE THREAD

**Issue by bcmills** [golang/go#49386] opened 2021-11-05 14:37 UTC
`greplogs --dashboard -md -l -e '(?ms)\Alinux-s390x.*FAIL: TestGopathShlib.*signal SIGSEGV'`

[2021-11-05T07:00:05-6fefb7f/linux-s390x-ibm](https://build.golang.org/log/1080af66ab5ca0ecb5d9472d4b59ba0cddedb951)
[2021-11-05T05:30:39-b68c02e/linux-s390x-ibm](https://build.golang.org/log/69b18930b5198286569b6343943bca7b22e9d124)
[2021-11-05T05:29:10-3b5add5/linux-s390x-ibm](https://build.golang.org/log/6c4decd1b56fa226bad06cf0e29c01a67466f763)
[2021-11-05T04:20:33-0a5ca24/linux-s390x-ibm](https://build.golang.org/log/5be32a0f002d7afbf6fdf29ad745ce3381d602fb)
[2021-11-05T00:52:09-bd580a0/linux-s390x-ibm](https://build.golang.org/log/eb78b36e2fc94a5a627bf9a826c4e0064f86ef7d)
[2021-11-05T00:52:08-35c7234/linux-s390x-ibm](https://build.golang.org/log/af3e4962b8c61554f3d01ec856d0ead041a930cd)
[2021-11-05T00:52:06-3839b60/linux-s390x-ibm](https://build.golang.org/log/ece2ea0ba4895d351c58b5bc6a990b2389c09223)
[2021-11-05T00:52:04-1c4cfd8/linux-s390x-ibm](https://build.golang.org/log/359fae067a46d561529659ff094f228472a24a6e)
[2021-11-04T23:56:29-0e5f287/linux-s390x-ibm](https://build.golang.org/log/e17c23eb2d604239d63b4bd6e63d46aed118fa1d)
[2021-11-04T23:35:26-256a8fc/linux-s390x-ibm](https://build.golang.org/log/12aa35fc7d93626b02fb86e9796e02e5ceec5bd1)
[2021-11-04T21:53:05-76c48e9/linux-s390x-ibm](https://build.golang.org/log/740fc4c4383823cbaa4ebef810e5d3c50f578492)
[2021-11-04T21:52:51-1e0c3b2/linux-s390x-ibm](https://build.golang.org/log/600be70d0d3f7482dc8663dc1e68c48837912def)
[2021-11-04T21:52:36-8ad0a7e/linux-s390x-ibm](https://build.golang.org/log/b8daebd34af7eb48b624956253206f706ac4f8e3)
[2021-11-04T21:52:06-37634ee/linux-s390x-ibm](https://build.golang.org/log/01f23200d208e813b83dc694dface3acb3f78135)
[2021-11-04T21:50:21-bfd74fd/linux-s390x-ibm](https://build.golang.org/log/f270d27049462abe27979e7c60259d5ce0eb64d7)
[2021-11-04T21:41:49-156abe5/linux-s390x-ibm](https://build.golang.org/log/9b7d9bd34b70933b9158e8a70ea1d8d07c62328d)
[2021-11-04T21:40:51-2c32f29/linux-s390x-ibm](https://build.golang.org/log/2c64b1898e1dd2e625977799c64f2b2c0b8fa50b)
[2021-11-04T21:33:23-71fc881/linux-s390x-ibm](https://build.golang.org/log/adc339ae16e7f7bd06019baa9bdd4755370826c9)
[2021-11-04T20:43:07-8248152/linux-s390x-ibm](https://build.golang.org/log/2cf8ab8c13686b6d629b697af5297f7cae723eff)
[2021-11-04T20:42:35-1f9dce7/linux-s390x-ibm](https://build.golang.org/log/e4c75e082923f033b1ff3ef67678f6ee7f9812d1)
[2021-11-04T20:31:02-978e39e/linux-s390x-ibm](https://build.golang.org/log/85a6a60a71ea86d3c935d11da6009f323a25e4d1)
[2021-11-04T20:24:01-99699d1/linux-s390x-ibm](https://build.golang.org/log/1f62abc5ae2fc91394f3255d14e3a88c783ced60)
[2021-11-04T20:01:22-6d1fffa/linux-s390x-ibm](https://build.golang.org/log/adfafc39a2f6aa0d7ad04bbdaecf0d8ba7a52ae8)
[2021-11-04T20:01:11-fc5e8cd/linux-s390x-ibm](https://build.golang.org/log/0678cf906ece808e2a9188cf6a3af407ad9e96e0)
[2021-11-04T20:01:10-9b2dd1f/linux-s390x-ibm](https://build.golang.org/log/ce32e240117c7f2d8c5834ec3271874cedb64791)
[2021-11-04T20:00:54-961aab2/linux-s390x-ibm](https://build.golang.org/log/572225a410663c1fd50aace194bc4854e73bd0c5)

**Comment by bcmills** [comment] 2021-11-05 14:38
This is a regression with a fairly clear root cause, so marking as release-blocker for Go 1.18.

**Comment by jonathan-albrecht-ibm** [comment] 2021-11-09 15:49
@mknyszek, I started debugging this yesterday to see if I can help in any way. I'm still trying to make sense of it but it seems to be related to the writeBarrier checks that are enabled when the GODEBUG flag `cgocheck=2` is set.

I can reproduce the same failure on go1.17.3 on s390x in the misc/cgo/testshared TestGopathShlib test by running:
```sh
go test -c
GODEBUG=cgocheck=2 ./testshared.test -test.run TestGopathShlib
```
I ran `./testshared.test  -test.v -testwork -test.run TestGopathShlib` to keep the `exe` file created by the test and tried to debug it but there are no debug symbols. I was able to inspect the memory for the `runtime.writeBarrier` struct that is referenced in the `os.newFile` function that causes the segfault. At least I think so, please let me know if I got any of the stuff below wrong.
```sh
(gdb) x/40ni $pc                                                                                                            
=> 0x2aa00093f48 <os.newFile+24>:       lg      %r0,80(%r15)
<... skip some lines ...>
   0x2aa00093fca <os.newFile+154>:      lgrl    %r11,0x2aa00112bf8
   0x2aa00093fd0 <os.newFile+160>:      llgf    %r2,0(%r11)
   0x2aa00093fd6 <os.newFile+166>:      cijne   %r2,0,0x2aa00093fec <os.newFile+188>
   0x2aa00093fdc <os.newFile+172>:      lg      %r4,88(%r15)
   0x2aa00093fe2 <os.newFile+178>:      stg     %r4,56(%r1)
   0x2aa00093fe8 <os.newFile+184>:      j       0x2aa00093ffe <os.newFile+206>
   0x2aa00093fec <os.newFile+188>:      aghik   %r2,%r1,56
   0x2aa00093ff2 <os.newFile+194>:      lg      %r3,88(%r15)
   0x2aa00093ff8 <os.newFile+200>:      brasl   %r14,0x2aa00066610 <runtime.gcWriteBarrier@plt>
   0x2aa00093ffe <os.newFile+206>:      llgc    %r4,63(%r15)
(gdb) b *0x2aa00093fd0
Breakpoint 2 at 0x2aa00093fd0
(gdb) c
Continuing.

Thread 1 "exe" hit Breakpoint 2, 0x000002aa00093fd0 in os.newFile ()
(gdb) info reg $r11
r11            0x3fffdf32220       4398012113440
(gdb) x/16xb 0x3fffdf32220
0x3fffdf32220 <runtime.writeBarrier>:   0x01    0x00    0x00    0x00    0x00    0x01    0x00    0x00
0x3fffdf32228 <runtime.writeBarrier+8>: 0x00    0x00    0x00    0x00    0x00    0x00    0x00    0x00
```
and then continuing will generate the segfault. IIUC, the two `0x01` bytes are the `runtime.writeBarrier.enabled` and `runtime.writeBarrier.cgo` fields.

If I do the same with `GODEBUG=cgocheck=0 gdb ./gopath/bin/exe` the `runtime.writeBarrier` looks like:
```sh
(gdb)  x/16xb 0x3fffdf32220
0x3fffdf32220 <runtime.writeBarrier>:   0x00    0x00    0x00    0x00    0x00    0x00    0x00    0x00
0x3fffdf32228 <runtime.writeBarrier+8>: 0x00    0x00    0x00    0x00    0x00    0x00    0x00    0x00
```
and no segfault.

But if I do the same with a build from the source checked out at  961aab26bffece299f1528b44d260ea0a921ac56 where the s390x builder started failing using `GODEBUG=cgocheck=0 gdb ./gopath/bin/exe`, it appears the `runtime.writeBarrier.enabled` and `runtime.writeBarrier.cgo` fields are `true`:

```sh
(gdb) x/16xb  0x3fffdf66220
0x3fffdf66220 <runtime.writeBarrier>:   0x01    0x00    0x00    0x00    0x01    0x00    0x00    0x00
0x3fffdf66228 <runtime.writeBarrier+8>: 0x00    0x00    0x00    0x00    0x00    0x00    0x00    0x00
```

If I break at the beginning of the `os.newFile` function and wait a bit then continue to after `$r11` is loaded, I usually find that the `runtime.writeBarrier.enabled` and `runtime.writeBarrier.cgo` fields have been flipped back to false and then no segfault.

So I think there is a bug on s390x with `cgocheck=2` that's been around for a while and its been exposed by some kind of issue with the `runtime.writeBarrier` fields being set or being visible. I'll keep looking but I'm not sure I'll be able to get much farther. Happy to help in any way I can though.

**Comment by mknyszek** [comment] 2021-11-09 16:19
@jonathan-albrecht-ibm Thanks for looking into it and for the detailed analysis! It confirms my suspicions.

The `runtime.writeBarrier` fields are likely just set because a GC is actively happening. This is related to 961aab26bffece299f1528b44d260ea0a921ac56 because that enabled the new pacer, which lowers the minimum heap size, so a whole bunch of tests started executing GCs that didn't before. Write barriers are now on, so if one is triggered where it's not safe to do so, it can cause a crash (usually because the executing code doesn't have a valid P, in Go scheduler terminology).

I suspect the `cgocheck` mode is failing for exactly the same reason: it's enabling write barriers in more places, and a write barrier is happening where it's not safe to do so. However, it's also almost certainly correct to have the write barrier on in `os.newFile` here, so I suspect there's something about the execution environment of the code that makes it not safe to do regular Go things.

**Comment by jonathan-albrecht-ibm** [comment] 2021-11-09 17:21
Thanks for the explanation @mknyszek. That helps clear things up a bit. I'll continue looking at it but will likely be slow going.

Note that s390x trial vms are available at https://linuxone.cloud.marist.edu/ if anyone is interested.

**Comment by jonathan-albrecht-ibm** [comment] 2021-11-11 00:57
From stepping through the code, I think the PLT symbol code (not sure what to call it) might be clobbering some registers. I found the source at `src/cmd/link/internal/s390x/asm.go` in the `addpltsym` function generates those instructions so I'm going to look at that next.

**Comment by jeremyfaller** [comment] 2021-11-12 20:45
This builder seems to have gone away. @cherrymui has some ideas on quick tests to help diagnose. 

Moving this to OK after Beta1.

**Comment by jonathan-albrecht-ibm** [comment] 2021-11-12 22:17
I had a look at the builders and they look ok. Would they have been disabled after some number of failures?

Glad to hear @cherrymui has some ideas on testing. Let me know if I can help with that. 

My guess is that register R1 and maybe others are being clobbered by the branch to `runtime.gcWriteBarrier@plt` so I'm trying to understand the code that sets up that call. Here is some debug info in case it helps:
```
<...SKIP SOME LINES...>
<R1 == 0xc000218000>
   0x2aa00078888 <os.newFile+200>: brasl %r14,0x2aa00047ea8 <runtime.gcWriteBarrier@plt>
<R1 == 0x3fffde16f90>
   0x2aa0007888e <os.newFile+206>: llgc %r4,63(%r15)
   0x2aa00078894 <os.newFile+212>: stc %r4,81(%r1)        <=== SEGFAULT HERE
```
where inside `runtime.gcWriteBarrier@plt` it looked like:
```
<R1 == 0xc000218000>
   0x2aa00047ea8 <runtime.gcWriteBarrier@plt>:  larl    %r1,0x2aa000f2e68 <runtime.gcWriteBarrier@got.plt>
<R1 == 0x2aa000f2e68>
   0x2aa00047eae <runtime.gcWriteBarrier@plt+6>:        lg      %r1,0(%r1)
<R1 == 0x3fffde16f90>
   0x2aa00047eb4 <runtime.gcWriteBarrier@plt+12>:       br      %r1
   0x2aa00047eb6 <runtime.gcWriteBarrier@plt+14>:       basr    %r1,%r0
   0x2aa00047eb8 <runtime.gcWriteBarrier@plt+16>:       lgf     %r1,12(%r1)
   0x2aa00047ebe <runtime.gcWriteBarrier@plt+22>:       jg      0x2aa00046e08
   0x2aa00047ec4 <runtime.gcWriteBarrier@plt+28>:       .long   0x00000c60
```

**Comment by cherrymui** [comment] 2021-11-13 00:57
@jonathan-albrecht-ibm Could you test if CL https://go-review.googlesource.com/c/go/+/363698 helps? Thanks!

(I cannot test it myself as the builder disappears.)

**Comment by jonathan-albrecht-ibm** [comment] 2021-11-13 20:33
Thanks @cherrymui, it looks good. I ran `all.bash` and all of the tests pass. I also ran:
```
cd ../misc/cgo/testshared/
~/src/goroot-r1-fix/bin/go test -c
GODEBUG=cgocheck=2 ./testshared.test
```
and that also passes.

**Comment by cherrymui** [comment] 2021-11-15 15:35
@jonathan-albrecht-ibm thanks!

**Comment by cherrymui** [comment] 2021-11-15 19:21
Fixed by the CL above.

**Closed by cherrymui** 2021-11-15 19:21 UTC
Labels: NeedsInvestigation, release-blocker, arch-s390x, okay-after-beta1
