### ISSUE TITLE
cmg/go: go get fails on cgo packages (or packages that import such packages indirectly).

### ISSUE THREAD

**Issue by shurcooL** [golang/go#11749] opened 2015-07-17 05:58 UTC
### What version of Go are you using (go version)?

`go version go1.5beta2 darwin/amd64`

### What operating system and processor architecture are you using?

OS X 10.10.4 (64-bit)

### What did you do?

```
go get -u github.com/shurcooL/go-get-issue-cgo
```

### What did you expect to see?

No output, successful go get (fetch, build and install).

What did you see instead?

```
package github.com/shurcooL/go-get-issue-cgo
	imports C: unrecognized import path "C"
```

## Likely Cause

I haven't verified it, but I am quite certain (it's very likely) this is a regression caused by the code change in https://go-review.googlesource.com/#/c/12192/.

After writing up this report, I've realized this issue is a duplicate of https://github.com/golang/go/issues/11738 and can be closed right away (filing just in case some additional information here is helpful).

**Comment by adg** [comment] 2015-07-17 05:59
Dupe of #11738

**Closed by adg** 2015-07-17 05:59 UTC
