### ISSUE TITLE
Possible bug in reflection!?

### ISSUE THREAD

**Issue by Pymann** [golang/go#46217] opened 2021-05-17 21:54 UTC
I have this:
```
type Who struct {
    Alter int
    Name string
    *Copy
}

type Copy struct {
    From, To string
}
```
and this function:
```

func FillAnyStructFromMap(u interface{}, j map[string]interface{}) {

    s := reflect.ValueOf(u).Elem()
	typeV := s.Type()

	for i := 0; i < typeV.NumField(); i++ {

		fieldname := typeV.Field(i).Name //struct_tag is per default http

        if jvalue, ok := j[fieldname]; ok {
            field := s.Field(i)
            jrvalue := reflect.ValueOf(jvalue)
            switch  (field.Type().Kind()) {
                case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
                    field.SetInt(int64(jrvalue.Float()))
                case reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
                    field.SetUint(uint64(jrvalue.Float()))
                case reflect.Ptr:
                    fmt.Printf("2\n")
                    pto := field.Elem()
                    //pto.Set(reflect.New(pto.Type()))
                    inter := pto.Interface()
                    FillAnyStructFromMap(&inter, j)
                    field.Set(reflect.ValueOf(&inter))
                    //field.Set(new_value)
                case reflect.Struct:
                    fmt.Printf("1\n")
                case reflect.Interface:
                    fmt.Printf("3\n")
                case reflect.Invalid:
                    fmt.Printf("4\n")
                default:
                    field.Set(jrvalue)
            }

        }
    }
}
```

And I'm trying with this json:
```
{
    "Name": "noname",
    "Alter": 12,
    "From": "hiho",
    "To": "Bla"
}
```

But reflect does not recognize the *Copy field in the Who-struct ?!!??!?!?!?!?!?

```
    f, err := os.Open("var.json")
    if err != nil {
        panic(err)
    }
    defer f.Close()
    var build map[string]interface{}
	decoder := json.NewDecoder(f)
	err = decoder.Decode(&build)
	if err != nil {
		panic(err)
	}
    wer := Who{}

    FillAnyStructFromMap(&wer, build)

    fmt.Printf("%#v\n", wer)
```

### What version of Go are you using (`go version`)?

<pre>
go version go1.16.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nikolai/.cache/go-build"
GOENV="/home/nikolai/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/nikolai/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/nikolai/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3720612746=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

**Comment by dmitshur** [comment] 2021-05-18 01:20
`*Copy` is an embedded field, and the `reflect` package should allow accessing it. If not, that would be indeed be a bug.

It's likely there's a problem with how `reflect` is used in the snippet you shared. It would need to be reduced to a smaller reproduce case before we can start investigating `reflect` itself.

Please take a look at https://golang.org/wiki/Questions for a list of better places to ask for help with something like this.

**Comment by AlexRouSg** [comment] 2021-05-18 03:03
@Pymann The issue is that reflect gives you the fields `After, Name, Copy`, but your code is expecting `After, Name, From, To`
I have edited your example with a few prints to make it clearer https://play.golang.org/p/8FeU5F6SIRb

**Comment by dmitshur** [comment] 2021-05-18 03:44
Thanks for investigating @AlexRouSg. I'll close this issue since it isn't a bug in Go.

**Closed by dmitshur** 2021-05-18 03:44 UTC
Labels: WaitingForInfo

**Comment by Pymann** [comment] 2021-05-18 19:08
Yes, problem is, that Copy isnt in the map at all ... sometimes I should reflect better ^^
