### ISSUE TITLE
x/net/proxy: provide DialContext

### ISSUE THREAD

**Issue by chowey** [golang/go#17759] opened 2016-11-03 04:14 UTC
With go1.7, the `net` package now provides a DialContext function. This is the recommended way to use `http.Transport`.

`x/net/proxy` should do the same so we can use it when creating our `http.Transport`s for use with SOCKS proxies.

**Comment by bradfitz** [comment] 2016-11-08 18:27
I don't remember that code, but sounds reasonable.

**Comment by artyom** [comment] 2016-12-22 10:14
I need this as well so I can try to implement context support for cancelation in this package.

I'd like to discuss API changes before doing any implementation. My conservative proposal (hopefully completely backwards-compatible) is to leave [Dialer][] interface unchanged and introduce new interface:

	type ContextDialer interface {
		Dialer
		DialContext(ctx context.Context, network, address string) (net.Conn, error)
	}

Then all functions of this package that take Dialer argument and return Dialer may be changed to return ContextDialer type instead **and** do type assertion on passed Dialer argument value to check whether it implements ContextDialer.

As example, [FromURL][] signature would change from:

	func FromURL(u *url.URL, forward proxy.Dialer) (proxy.Dialer, error)

to

	func FromURL(u *url.URL, forward proxy.Dialer) (proxy.ContextDialer, error)

[Dialer]: https://godoc.org/golang.org/x/net/proxy#Dialer
[FromURL]: https://godoc.org/golang.org/x/net/proxy#FromURL

**Comment by Fardinak** [comment] 2017-03-23 20:56
Possible duplicate of #19354.
This seems to be covered by the issue above, which is in the Go1.9 milestone and also in review at https://golang.org/cl/37641.

/cc @bradfitz

**Comment by mjgarton** [comment] 2018-04-23 19:43
https://go-review.googlesource.com/c/net/+/37641

**Closed** 2019-05-02 18:39 UTC
