### ISSUE TITLE
proposal: Generics apply to struct methods

### ISSUE THREAD

**Issue by michaelhenry** [golang/go#55006] opened 2022-09-11 16:30 UTC
Something like this:

```go
type Store struct {}

func (s *Store) Get[model any](key string) (*model, error) {
  ...
}

```
Currently, having a generic inside a struct function can throw a syntax error like:
```bash
syntax error: method must have no type parameters
```

Though my current workaround with this is by creating a generic function that accepts a pointer of the struct, but it would better if generics can be accepted inside struct functions and not only on `struct[T]`. and I think with this, a lot of APIs can be totally simplified.

```go

func Get[model any](store *Store, key string)(*model, error) {
   ...
}
```
Any particular reason, why we can't allow this? or any plan in the future? 

Thanks

**Comment by seankhliao** [comment] 2022-09-11 18:22
Duplicate of #49085

**Closed by seankhliao** 2022-09-11 18:22 UTC
Labels: Proposal
