### ISSUE TITLE
cmd/go: go install -buildmode=plugin creates shared object with wrong file name

### ISSUE THREAD

**Issue by zephyrtronium** [golang/go#33571] opened 2019-08-09 21:38 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/zephyrtronium/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/zephyrtronium/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build282654314=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
~/mygo/plugintest$ printf 'package main\n\nvar String = "Hello, world!"\n' >plugin.go
~/mygo/plugintest$ go install -buildmode=plugin -x
```

### What did you expect to see?

A shared object named `plugintest.so` in `/home/zephyrtronium/go/pkg/linux_amd64_dynlink/github.com/zephyrtronium/`.

### What did you see instead?

A shared object named `plugintest.a` in the same directory.

I confirmed that the plugin loads correctly using the `plugin` package, it's just named `.a` instead of `.so`. The output from `go install -buildmode=plugin -x` includes `mv $WORK/b001/exe/a.out.so /home/zephyrtronium/go/pkg/linux_amd64_dynlink/github.com/zephyrtronium/plugintest.a`, versus `go build -buildmode=plugin -n` having `mv $WORK/b001/exe/a.out.so plugintest.so`.

**Comment by bcmills** [comment] 2019-08-12 16:59
CC @jayconrod @ianlancetaylor @crawshaw

**Comment by quantonganh** [comment] 2023-11-03 14:43
I guess this has been fixed:

```
$ go install -buildmode=plugin -x
...

mv $WORK/b001/exe/a.out.so plugintest.so
rm -rf $WORK/b001/
```

**Comment by bcmills** [comment] 2023-11-03 14:53
Huh. I'm not sure what would have fixed it, but given the lack of comments since 2019 I suspect you're correct. 🙃

(Maybe it could have been https://go.dev/cl/197544?)

At any rate: closing as “no longer reproducible”. @quantonganh, thanks for checking this!

**Closed by bcmills** 2023-11-03 14:53 UTC
Labels: help wanted, NeedsInvestigation, GoCommand
