### ISSUE TITLE
http

### ISSUE THREAD

**Issue by iampsl** [golang/go#50309] opened 2021-12-22 09:48 UTC
http timeout not work

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.4 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you see instead?

package main

import (
	"fmt"
	"io/ioutil"
	"net/http"
	"time"
)

func httpGetHtml2(url string) ([]byte, error) {
	tmpClient := &http.Client{Timeout: 10 * time.Second}
	resp, err := tmpClient.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	return ioutil.ReadAll(resp.Body)

}

func main() {
	fmt.Println(httpGetHtml2("http://162.14.22.35:9300"))
}

**Comment by seankhliao** [comment] 2021-12-22 09:54
Closing as not a bug report

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by iampsl** [comment] 2021-12-22 09:54
I have received email from you!
Thank You!

**Closed by seankhliao** 2021-12-22 09:54 UTC
