### ISSUE TITLE
gollvm: assertion with -enable-gc=1

### ISSUE THREAD

**Issue by alexanius** [golang/go#56096] opened 2022-10-07 14:19 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 gollvm LLVM 15.0.0git 20221003 (experimental) linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/amarkin/.cache/go-build"
GOENV="/home/amarkin/.config/go/env"
GOEXE=""
GOEXPERIMENT="fieldtrack,regabiwrappers"
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/amarkin/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/amarkin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/amarkin/repos/gollvm_trunk/installed-debug"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/amarkin/repos/gollvm_trunk/installed-debug/tools"
GOVCS=""
GOVERSION="go1.18 gollvm LLVM 15.0.0git 20221003 (experimental)"
GCCGO="/home/amarkin/repos/gollvm_trunk/installed-debug/bin/llvm-goc"
GOAMD64="v1"
AR="ar"
CC="/usr/bin/cc"
CXX="/usr/bin/c++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2192610697=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
</pre></details>

### What did you do?

<details><summary><code>Code</code></summary><br><pre>
$ cat t.go
package main

import "sync"
import "runtime"
import "strings"
import "strconv"

func goid() int {
        var buf [64]byte
        n := runtime.Stack(buf[:], false)
        idField := strings.Fields(strings.TrimPrefix(string(buf[:n]), "goroutine "))[0]
        id, err := strconv.Atoi(idField)
        if err != nil {
                println("cannot get goroutine id: %v", err)
        }
        return id
}

func main() {
  var wg sync.WaitGroup
  for i := 0 ; i < 30 ; i++ {
    wg.Add(1)
    go func() {
      println("goid", goid())
      defer wg.Done()
      t := 0
      for i := 0 ; i < 1e8 ; i++ {
        t += 2
      }
      println("total: ", t, goid())
    }()
  }
  wg.Wait()
}</pre></details>

<pre>
$ LD_LIBRARY_PATH="/home/amarkin/repos/gollvm_trunk/installed-debug/lib64" /home/amarkin/repos/gollvm_trunk/installed-debug/bin/go build  -gccgoflags "-enable-gc=1" t.go
# command-line-arguments
llvm-goc: /home/amarkin/repos/gollvm_trunk/llvm/lib/IR/Constants.cpp:2016: static llvm::Constant* llvm::ConstantExpr::getCast(unsigned int, llvm::Constant*, llvm::Type*, bool): Assertion `CastInst::castIsValid(opc, C, Ty) && "Invalid constantexpr cast!"' failed.
 #0 0x0000563971008f6c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/amarkin/repos/gollvm_trunk/llvm/lib/Support/Unix/Signals.inc:565:22
 #1 0x0000563971009027 PrintStackTraceSignalHandler(void*) /home/amarkin/repos/gollvm_trunk/llvm/lib/Support/Unix/Signals.inc:632:1
 #2 0x0000563971006ca2 llvm::sys::RunSignalHandlers() /home/amarkin/repos/gollvm_trunk/llvm/lib/Support/Signals.cpp:97:20
 #3 0x00005639710088c3 SignalHandler(int) /home/amarkin/repos/gollvm_trunk/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007f5ed4d22420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #5 0x00007f5ed47ba00b raise /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #6 0x00007f5ed4799859 abort /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:81:7
 #7 0x00007f5ed4799729 get_sysdep_segment_value /build/glibc-SzIz7B/glibc-2.31/intl/loadmsgcat.c:509:8
 #8 0x00007f5ed4799729 _nl_load_domain /build/glibc-SzIz7B/glibc-2.31/intl/loadmsgcat.c:970:34
 #9 0x00007f5ed47aafd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
#10 0x0000563970b08261 llvm::ConstantExpr::getCast(unsigned int, llvm::Constant*, llvm::Type*, bool) /home/amarkin/repos/gollvm_trunk/llvm/lib/IR/Constants.cpp:2016:3
#11 0x0000563970c28226 llvm::ConstantFolder::CreateCast(llvm::Instruction::CastOps, llvm::Constant*, llvm::Type*) const /home/amarkin/repos/gollvm_trunk/llvm/include/llvm/IR/ConstantFolder.h:206:3
#12 0x000056396e635fa9 llvm::IRBuilderBase::CreateCast(llvm::Instruction::CastOps, llvm::Value*, llvm::Type*, llvm::Twine const&) /home/amarkin/repos/gollvm_trunk/llvm/include/llvm/IR/IRBuilder.h:2005:20
#13 0x000056396e635f18 llvm::IRBuilderBase::CreateBitCast(llvm::Value*, llvm::Type*, llvm::Twine const&) /home/amarkin/repos/gollvm_trunk/llvm/include/llvm/IR/IRBuilder.h:1966:3
#14 0x000056396e7302ca Llvm_backend::convertForAssignment(Btype*, llvm::Value*, llvm::Type*, BlockLIRBuilder*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/bridge/go-llvm-materialize.cpp:1663:50
#15 0x000056396e622598 Llvm_backend::genStore(BlockLIRBuilder*, Btype*, bool, llvm::Type*, llvm::Value*, llvm::Value*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/bridge/go-llvm.cpp:880:36
#16 0x000056396e62322b Llvm_backend::genStructInit(llvm::StructType*, Bexpression*, llvm::Value*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/bridge/go-llvm.cpp:1020:13
#17 0x000056396e6235c0 Llvm_backend::resolveCompositeInit(Bexpression*, llvm::Value*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/bridge/go-llvm.cpp:1053:25
#18 0x000056396e62763d Llvm_backend::makeInitStatement(Bfunction*, Bvariable*, Bexpression*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/bridge/go-llvm.cpp:1826:34
#19 0x000056396e6274fc Llvm_backend::init_statement(Bfunction*, Bvariable*, Bexpression*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/bridge/go-llvm.cpp:1807:48
#20 0x000056396e629f3d Llvm_backend::temporary_variable(Bfunction*, Bblock*, Btype*, Bexpression*, unsigned int, Location, Bstatement**) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/bridge/go-llvm.cpp:2377:24
#21 0x000056396e6d2500 Heap_expression::do_get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/expressions.cc:17677:37
#22 0x000056396e69bd5d Expression::get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/expressions.cc:649:38
#23 0x000056396e69e05d Func_expression::do_get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/expressions.cc:1575:51
#24 0x000056396e69bd5d Expression::get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/expressions.cc:649:38
#25 0x000056396e5ab8b2 Temporary_statement::do_get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/statements.cc:632:37
#26 0x000056396e5aa30f Statement::get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/statements.cc:189:38
#27 0x000056396e530227 Block::get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/gogo.cc:7114:44
#28 0x000056396e5b00c7 Block_statement::do_get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/statements.cc:2245:45
#29 0x000056396e5aa30f Statement::get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/statements.cc:189:38
#30 0x000056396e530227 Block::get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/gogo.cc:7114:44
#31 0x000056396e5b00c7 Block_statement::do_get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/statements.cc:2245:45
#32 0x000056396e5aa30f Statement::get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/statements.cc:189:38
#33 0x000056396e530227 Block::get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/gogo.cc:7114:44
#34 0x000056396e5b00c7 Block_statement::do_get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/statements.cc:2245:45
#35 0x000056396e5aa30f Statement::get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/statements.cc:189:38
#36 0x000056396e530227 Block::get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/gogo.cc:7114:44
#37 0x000056396e5b00c7 Block_statement::do_get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/statements.cc:2245:45
#38 0x000056396e5aa30f Statement::get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/statements.cc:189:38
#39 0x000056396e530227 Block::get_backend(Translate_context*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/gogo.cc:7114:44
#40 0x000056396e52e484 Function::build(Gogo*, Named_object*) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/gogo.cc:6649:53
#41 0x000056396e5359a1 Named_object::get_backend(Gogo*, std::vector<Bexpression*, std::allocator<Bexpression*> >&, std::vector<Btype*, std::allocator<Btype*> >&, std::vector<Bfunction*, std::allocator<Bfunction*> >&) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/gogo.cc:8900:7
#42 0x000056396e51e2fb Gogo::write_globals() /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/gogo.cc:1560:24
#43 0x000056396e5164ea go_write_globals() /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/gofrontend/go/go.cc:201:32
#44 0x000056396e4f8cec gollvm::driver::CompileGoImpl::invokeFrontEnd() /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/driver/CompileGo.cpp:751:7
#45 0x000056396e4f63a6 gollvm::driver::CompileGoImpl::performAction(gollvm::driver::Compilation&, gollvm::driver::Action const&, llvm::SmallVector<gollvm::driver::Artifact*, 3u> const&, gollvm::driver::Artifact const&) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/driver/CompileGo.cpp:193:7
#46 0x000056396e4f9bc0 gollvm::driver::CompileGo::performAction(gollvm::driver::Compilation&, gollvm::driver::Action const&, llvm::SmallVector<gollvm::driver::Artifact*, 3u> const&, gollvm::driver::Artifact const&) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/driver/CompileGo.cpp:966:1
#47 0x000056396e4e92e0 gollvm::driver::Driver::processAction(gollvm::driver::Action*, gollvm::driver::Compilation&, bool) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/driver/Driver.cpp:707:11
#48 0x000056396e4e94a5 gollvm::driver::Driver::processActions(gollvm::driver::Compilation&) /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/driver/Driver.cpp:730:9
#49 0x000056396e4dcb5d main /home/amarkin/repos/gollvm_trunk/llvm/tools/gollvm/driver-main/llvm-goc.cpp:228:7
#50 0x00007f5ed479b083 __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:342:3
#51 0x000056396e4dbf6e _start (/home/amarkin/repos/gollvm_trunk/installed-debug/bin/llvm-goc+0x8e3f6e)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/amarkin/repos/gollvm_trunk/installed-debug/bin/llvm-goc -c -O2 -g -m64 -fdebug-prefix-map=/tmp/go-build425409048=/tmp/go-build -gno-record-gcc-switches -fgo-relative-import-path=_/home/amarkin/tests/test3 -o $WORK/b001/_go_.o -I $WORK/b001/_importcfgroot_ -enable-gc=1 ./t.go
</pre>

### What did you expect to see?

Successful compilation

### What did you see instead?

Stack dump

**Comment by cherrymui** [comment] 2022-10-07 20:44
Duplicate of #52956

**Closed by cherrymui** 2022-10-07 20:44 UTC
