### ISSUE TITLE
x/tools/gopls: experimentalWorkspaceModule does not work for the standard library

### ISSUE THREAD

**Issue by findleyr** [golang/go#48384] opened 2021-09-14 15:40 UTC
Reminder issue: the `experimentalWorkspaceModule` setting does not behave correctly for std and cmd. We should (1) document this, and (2) investigate.

Moving this to v0.7.3 for at least improving the documentation.

CC @stamblerre

**Comment by heschi** [comment] 2021-09-14 17:54
Dupe of https://golang.org/issue/45890?

**Comment by stamblerre** [comment] 2021-09-14 19:36
Yep, closing and moving the other issue to v0.7.3 milestone.

**Closed by stamblerre** 2021-09-14 19:36 UTC
Labels: gopls, Tools
