### ISSUE TITLE
how to list all the files in a website

### ISSUE THREAD

**Issue by deepnum** [golang/go#35493] opened 2019-11-10 19:03 UTC

**Comment by ALTree** [comment] 2019-11-10 19:05
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2019-11-10 19:05 UTC
