### ISSUE TITLE
x/tools/godoc: does not print comments accompanying variable literals

### ISSUE THREAD

**Issue by stapelberg** [golang/go#29775] opened 2019-01-16 19:22 UTC
Take the following example code:
```go
package exported

var IPs = []string{
"127.0.0.1", // localhost

// IPv6 localhost
"::1",
}
```

…and render it using godoc:

```
% go get -u golang.org/x/tools/cmd/godoc
% go get -u github.com/stapelberg/godoc-exported
% godoc -http=localhost:6060
% google-chrome http://localhost:6060/pkg/github.com/stapelberg/godoc-exported/
```

You’ll see:

![2019-01-16-202035_703x617_scrot](https://user-images.githubusercontent.com/55506/51273168-54e7a200-19cc-11e9-8845-ac4ddef1cd44.png)

I.e., the comments are not printed.

I’m guessing this is a consequence of `go/ast`’s comment handling being tricky. I tried taking a stab at it, but couldn’t get very far, so I figured I’d file a bug and see if someone more familiar with the code can advise what needs to be done here.

**Comment by stapelberg** [comment] 2019-01-16 19:22
This also affects godoc.org: https://godoc.org/github.com/stapelberg/godoc-exported

**Comment by agnivade** [comment] 2019-01-17 07:44
I think this has been raised before in the past, but I couldn't find an exact issue for this. Maybe https://github.com/golang/go/issues/20744 ?

@griesemer

**Comment by seankhliao** [comment] 2024-12-02 22:09
Duplicate of #6917

**Closed by seankhliao** 2024-12-02 22:09 UTC
Labels: NeedsInvestigation, FrozenDueToAge, Tools
