### ISSUE TITLE
go test -v should print logs as they're executed, not at the end

### ISSUE THREAD

**Issue by jadekler** [golang/go#24262] opened 2018-03-06 00:33 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.10 darwin/amd64

### What did you do?

`go test -v` with some code that hangs.

### What did you expect to see?

Logs.

### What did you see instead?

Nothing. In the case where my code hangs forever, I don't get any test logs because logs are only printed in the success/fail case. Ctrl+C means I never get logs.

Furthermore, `-v` not showing logs means I get no sense of timing in test runs.

It's a real bummer to mass replace t.Log with fmt.Println, get my tests fixed, and then mass replace fmt.Println with t.Log.

**Comment by andybons** [comment] 2018-03-06 00:59
Duplicate of #23213

**Closed by andybons** 2018-03-06 00:59 UTC

**Comment by jadekler** [comment] 2018-03-06 01:21
👍  thanks!
