### ISSUE TITLE
cmd/go2go: problem with unnamed function parameter

### ISSUE THREAD

**Issue by aitva** [golang/go#39656] opened 2020-06-17 16:28 UTC
### What version of Go are you using (`go version`)?

I have been experimenting with https://go2goplay.golang.org

### What did you do?

I built a program using generic and unnamed function parameter.

```go
type Endpoint(type A, B) func(context.Context, A) (B, error)

type Middleware(type A, B) func(Endpoint(A, B)) Endpoint(A, B)

func Chain(type A, B)(middlewares ...Middleware(A, B)) Middleware(A, B) {
	return func(next Endpoint(A, B)) Endpoint(A, B) {
		for i := len(middlewares) - 1; i > 0; i-- {
			next = middlewares[i](next)
		}
		return next
	}
}
```

https://go2goplay.golang.org/p/d5Ta-AEHDQo

### What did you expect to see?

A successful build. 

### What did you see instead?

A build error:

```
prog.go2:9:43: expected ')', found ',' (and 1 more errors)
```

It can be fixed by adding a name to the `Middleware` parameter:

```go
type Middleware(type A, B) func(next Endpoint(A, B)) Endpoint(A, B)
```

But then it fails in the `Chain` function with: 

```
prog.go2:13:3: expected operand, found 'for' (and 3 more errors)
```

Here is a link to a working version with all the unnamed parameter named : https://go2goplay.golang.org/p/oY8ggQsH3M5

**Comment by andybons** [comment] 2020-06-17 16:31
@ianlancetaylor @griesemer

**Comment by benjaminjkraft** [comment] 2020-06-17 18:31
I think the first part of this is one of the parsing ambiguities [described in the design draft](https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md#using-generic-types-as-unnamed-function-parameter-types), and then the second is #39654 (a new but related parsing ambiguity).

**Comment by griesemer** [comment] 2020-06-17 19:48
This is indeed the parsing ambiguity described already; [this code](https://go2goplay.golang.org/p/4FNW1_NY1O_6) works. Again, there's only this one issue here (once in the parameter list of the `Middleware` function, and once in the result of the `Chain` function.

Closing is working as intended.

Again, please know that we're likely going to change this as this ambiguity is biting a lot of people.

**Closed by griesemer** 2020-06-17 19:48 UTC
Labels: NeedsInvestigation
