### ISSUE TITLE
net/http: Client.Do hangs (in Linux Daemon) when exported via Cgo shared library

### ISSUE THREAD

**Issue by avnileshshinde** [golang/go#47077] opened 2021-07-07 07:13 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
version go1.16.4 linux/386
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="386"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOINSECURE="golang.org,googlesource.com"
GOMODCACHE="/home/nilesh/golang/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/nilesh/golang"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_386"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
GO386="sse2"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/nilesh/SVN/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build718813889=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
See Go definition of CheckConnection() function given below. I exported CheckConnection Go function as C function in .so file using following command. 
`go build -o mygolib.so -buildmode=c-shared mygolib.go`

Then using generated .SO and .h, called exported Go function from my C test program. Below is the command I used to compile and build my C test program.

`gcc -o testclient testclient.c ./mygolib.so`

With this testclient program in C I am able to get the response from myClient. However when I included this .so and .h file in our existing Linux service (in C only),I am unable to make http request. Below is my Go function. Call gets blocked at below line, does not timeout or gives any error. testclient and linux service is on same machine. However from testclient function returns me the response but from linux service call gets hang.

`res,err := myClient.Do(req)`

```
//export CheckConnection
func CheckConnection() {

reqUrl,_ := url.Parse("https://www.google.com/")

req := &http.Request{
Method: "GET",
URL: reqUrl,
Header: map[string][]string{
"Content-type": {"application/json; charset=UTF-8" },
},
}

 var myClient = &http.Client{
  Timeout: time.Second * 10,
 }

res,err := myClient.Do(req)
if err!= nil {
log.Fatal("Error ",err)
}

data,_ := ioutil.ReadAll(res.Body)
res.Body.Close()

log.Print("Resp code ",res.StatusCode)
log,Print("Data ",data)
}
```

### What did you expect to see?
`res,err := myClient.Do(req)`
Above call should either return me the response string or timeout error.

### What did you see instead?
Call gets hand on below code line -
`res,err := myClient.Do(req)`

**Comment by mknyszek** [comment] 2021-07-07 15:29
Since you say that this only seems to go wrong in your service, it's hard for us to take steps toward resolving it.

If you could create a small reproducer that demonstrates the problem, that would be really helpful.

CC @neild via https://dev.golang.org/owners

**Comment by avnileshshinde** [comment] 2021-07-07 16:07
Sure, I will try to reproduce it with sample. But meanwhile if you could provide me some pointers around what area/parameters could can cause such kind of issues, so that I can check the service behavior from my end. Reproducing this issue with sample service may take some time.

**Comment by avnileshshinde** [comment] 2021-07-26 13:13
Hello, Here is the sample code with which issue is reproducible.
The goclient.c is the program which tries to run as daemon on CentOS 7.  In this program, there are two calls to CheckConnection() function. One from main() and other from daemon process. Call from main gets succeeded where as call from daemon process hangs.

[Sample.zip](https://github.com/golang/go/files/6878420/Sample.zip)

**Comment by avnileshshinde** [comment] 2021-07-28 05:28
> 
> 
> Since you say that this only seems to go wrong in your service, it's hard for us to take steps toward resolving it.
> 
> If you could create a small reproducer that demonstrates the problem, that would be really helpful.
> 
> CC @neild via https://dev.golang.org/owners

**Comment by avnileshshinde** [comment] 2021-07-28 05:31
> 
> 
> Since you say that this only seems to go wrong in your service, it's hard for us to take steps toward resolving it.
> 
> If you could create a small reproducer that demonstrates the problem, that would be really helpful.
> 
> CC @neild via https://dev.golang.org/owners

Hi @mknyszek 

I am able to reproduce this issue with sample code. I have attached same to this incident. Could you please look at this?

Regards,
Nilesh

**Closed** 2021-07-30 05:37 UTC
Labels: NeedsInvestigation, WaitingForInfo
