### ISSUE TITLE
go build failed

### ISSUE THREAD

**Issue by oikomi** [golang/go#13052] opened 2015-10-26 11:16 UTC
hi @all

go build failed, what does it mean?

```shell
[miaohong]$ go build

# _/tmp/mh/php/agent

/usr/bin/ld: unrecognized option '--build-id=none'

/usr/bin/ld: use the --help option for usage information

collect2: ld returned 1 exit status



system info

[miaohong01$ go version
go version go1.5.1 linux/amd64

[miaohong]$ gcc --version
gcc (GCC) 3.4.5 20051201 (Red Hat 3.4.5-2)

Copyright (C) 2004 Free Software Foundation, Inc.

This is free software; see the source for copying conditions.  There is NO


warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[miaohong]$ uname -ar
Linux cp01-rdqa04-dev110.cp01 2.6.32_1-17-0-0 #1 SMP Mon Aug 24 11:14:27 CST 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ALTree** [comment] 2015-10-26 12:08
Old Rhel version? I suspect this is related to #9520

**Comment by ianlancetaylor** [comment] 2015-10-26 16:36
My reply on the mailing list:

Given that you are using a version of GCC that is more than ten years old, I would guess that the problem is that you are also using a very old version of the GNU binutils.  When the go tool uses cgo on systems that use the GNU binutils, it passes --build-id=none to disable the generation of a build ID.  This has worked for the GNU binutils for a long time, but it may not work for your very old version.

The choices I see would to update your GNU binutils, edit the go tool to remove the --build-id=none, or put a shell script on your PATH named ld that removes the --build=none option and then invoke the real ld.

Closing because I don't think there is anything for us to do.

**Closed by ianlancetaylor** 2015-10-26 16:36 UTC

**Comment by oikomi** [comment] 2015-10-27 02:33
I have remove all the cgo code, build pass. Thanks !
