### ISSUE TITLE
net/http: ServeMux benchmark regression

### ISSUE THREAD

**Issue by Quasilyte** [golang/go#25383] opened 2018-05-14 12:31 UTC
There is notable difference in Go1.10.2 and tip BenchmarkServeMux results:
```
name        old time/op    new time/op    delta
ServeMux-4     127µs ± 1%     156µs ± 1%  +23.04%  (p=0.008 n=5+5)

On other machine:
ServeMux-4       143µs ±11%      165µs ± 7%    +15.44%  (p=0.008 n=5+5)

And another machine:
ServeMux-8    85.1µs ± 3%    95.0µs ± 6%  +11.61%  (p=0.008 n=5+5)
```
The most significant impact comes from additional synchronization added in 2fd1b523952727b91e5eca76ff1f8b8af8746f7a. The commit message lacks benchmarks info, so I think it's worthwhile to report regression anyway and decide whether it can be addressed or not (we can't just remove locking if it's needed there, but there can be other options).

There are other causes of slowdown as commit right behind 2fd1b523952727b91e5eca76ff1f8b8af8746f7a is still slower (but the delta is more tolerable):
```
name        old time/op    new time/op    delta
ServeMux-4     127µs ± 1%     135µs ± 1%  +6.43%  (p=0.008 n=5+5)
```

**Comment by mvdan** [comment] 2018-05-14 14:52
It seems like the commit you're pointing to was a race bugfix, so it's not the type of performance regression that can be easily fixed or reverted. Do you have any ideas on how to get the numbers back to 1.10 levels?

**Comment by Quasilyte** [comment] 2018-05-14 14:59
@mvdan, I'm not familiar with `net/http` at all, so I can't really propose any solution or evaluate submitted one. This is why I've added this to description:

> The commit message lacks benchmarks info, so I think it's worthwhile to report regression anyway and decide whether it can be addressed or not (we can't just remove locking if it's needed there, but there can be other options).

I've reported it for completeness as it showed pretty high delta.
It's better to know the impact than not.
Usually, it's better when CLs that affects performance in this way includes benchstat info, but this one didn't, hence here is the missing link,

**Comment by OneOfOne** [comment] 2018-05-14 16:06
@mvdan it's the defer, some `goto` hackary should make it pretty close to the old numbers. 

If that's acceptable, I can push a PR sometime this week.

**Comment by bradfitz** [comment] 2018-06-06 01:48
@odeke-em, want to post an update on this now that 116378 is submitted? Or bump to Go 1.12 or Unplanned?

**Comment by odeke-em** [comment] 2018-06-10 23:34
@bradfitz thanks for the ping.

So after CL 116378, we still have that regression from the newly introduced defer. I think we meant 116378 for #25482 instead :)

CL 113996 removes the defer that is the subject of this issue but it doesn't seem like you like its approach

**Comment by agnivade** [comment] 2018-11-06 12:02
@odeke-em - Just wanted to check on this. I just re-ran the benchmarks from the current tip 510eea2dfcabbc8916c7c59aa37046269ad29497 and 1.10.2

```
name        old time/op    new time/op    delta
ServeMux-4    85.5µs ± 1%    78.4µs ± 1%   -8.26%  (p=0.008 n=5+5)

name        old alloc/op   new alloc/op   delta
ServeMux-4    19.9kB ± 0%    17.3kB ± 0%  -13.18%  (p=0.008 n=5+5)

name        old allocs/op  new allocs/op  delta
ServeMux-4       540 ± 0%       360 ± 0%  -33.33%  (p=0.008 n=5+5)
```

It seems we have a measurable improvement. Is there still anything else you would like to do on this ?

**Comment by odeke-em** [comment] 2018-11-10 06:11
Thank you for the reminder @agnivade!

@carl-mastrangelo's nice CL https://go-review.googlesource.com/c/144937 aka commit massively levelled the ground so we are good now https://github.com/golang/go/commit/1645dfa23fbb1d1bab258d1c458f08d9f2741295 -- I had an almost similar change with longest prefix matching by sorting by length but didn't get the wins in his CL, cool stuff @carl-mastrangelo!

With that I am going to close this issue, @bradfitz or anyone else please feel free to reopen or bump to Unplanned.

**Comment by odeke-em** [comment] 2018-11-13 18:56
> I appreciate the call out, but I don't believe my change fixed this. I sent out https://go-review.googlesource.com/c/go/+/149377 which brings the latency down to the pre-lock levels.

@carl-mastrangelo, thanks for the humility! For clarity, I should have spelled out that this issue was combated by a collective of fixes:

Owner|CL
---|---
@Quasilyte|https://go-review.googlesource.com/c/go/+/113235
@bradfitz|https://go-review.googlesource.com/c/go/+/116378/
@carl-mastrangelo| https://go-review.googlesource.com/c/go/+/149377
Myself|https://go-review.googlesource.com/c/go/+/113996/

and others that I might not have seen, which have brought the levels down to as @agnivade reported in https://github.com/golang/go/issues/25383#issuecomment-436229373

**Comment by agnivade** [comment] 2018-11-13 19:06
The issue originally was a regression in performance, which is fixed (even improved) now. Although, changes were made in other areas, but it eventually improved performance. I think this issue can be closed, because the regression does not exist any more.

Otherwise, we should re-title it to "net/http: remove mutex locks in ServeMux" because that is what this should be about.

**Comment by odeke-em** [comment] 2018-11-13 19:21
I replied before I noticed that @bradfitz reopened it. @carl-mastrangelo was just stating that he didn't think his CL fixed this issue but I explained why I mentioned his CL and how it contributed to bringing the regressions down in  https://github.com/golang/go/issues/25383#issuecomment-438393572.

@bradfitz could you please reconsider closing this issue as it was about a regression that has been erased as mentioned in https://github.com/golang/go/issues/25383#issuecomment-438393572 but also just by @agnivade in https://github.com/golang/go/issues/25383#issuecomment-438397052?

**Comment by bradfitz** [comment] 2018-11-13 19:41
Sure. Carl, file a new bug if you want to track lock removal.

**Closed by bradfitz** 2018-11-13 19:41 UTC
Labels: Performance, help wanted
