### ISSUE TITLE
cmd/go: modules: use of internal package not allowed with gopkg.in

### ISSUE THREAD

**Issue by stapelberg** [golang/go#26496] opened 2018-07-20 06:01 UTC
I have read https://github.com/golang/go/issues/26446, but I think the usage of gopkg.in might make things different enough that a separate issue is warranted.

### What version of Go are you using (`go version`)?

go version go1.11beta2 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/michael/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/michael/go"
GOPROXY=""
GORACE=""
GOROOT="/home/michael/sdk/go1.11beta2"
GOTMPDIR=""
GOTOOLDIR="/home/michael/sdk/go1.11beta2/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/benchmark/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build494706699=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

```
/tmp % git clone https://github.com/robustirc/benchmark
Cloning into 'benchmark'...
remote: Counting objects: 6682, done.
remote: Total 6682 (delta 0), reused 0 (delta 0), pack-reused 6682
Receiving objects: 100% (6682/6682), 14.06 MiB | 12.49 MiB/s, done.
Resolving deltas: 100% (1893/1893), done.
/tmp % cd benchmark
/tmp/benchmark master % go mod -init
go: creating new go.mod: module github.com/robustirc/benchmark
go: copying requirements from Gopkg.lock
/tmp/benchmark master % go build cmd/throughput/throughput.go 
/home/michael/go/src/mod/github.com/sorcix/irc@v1.1.3/message.go:11:2: use of internal package gopkg.in/sorcix/irc.v1/internal not allowed
```

**Comment by oiooj** [comment] 2018-07-20 06:52
Duplicate of #23970. Actually, it's the same issue, feel free to reopen it if have any question.

**Closed by oiooj** 2018-07-20 06:52 UTC
Labels: modules

**Comment by stapelberg** [comment] 2018-07-20 06:55
Are you sure about this? As I said, I have read the other issues, but in my case, the package is not using an “internal” package outside of the repository, it’s _inside_ the same repository, but not recognized as such due to gopkg.in being in the mix.

**Comment by oiooj** [comment] 2018-07-20 18:49
A dep of your project have a "internal" package, `gopkg.in/sorcix/irc.v1/internal`

**Comment by stapelberg** [comment] 2018-07-21 08:47
Yes, but #23970 is about _cross-module_ internal imports, which is not the case here. The package in question is `gopkg.in/sorcix/irc.v1`, which imports `gopkg.in/sorcix/irc.v1/internal`.

The import is within the same module, but the problem is that the gopkg.in path is translated, I think.
