### ISSUE TITLE
Compiler appears to branch inconsistently when pointers to empty structs are in scope.

### ISSUE THREAD

**Issue by dzrtc** [golang/go#38934] opened 2020-05-07 21:12 UTC
### What version of Go are you using (`go version`)?

go version go1.14.2 darwin/amd64

### Does this issue reproduce with the latest release?

unknown

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dzrtc/Library/Caches/go-build"
GOENV="/Users/dzrtc/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOOS="darwin"
GOPATH="/Users/dzrtc/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yj/w5qqzhlj0ngb6961d_lkfc000000gp/T/go-build039474580=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Program A is a subset of Program B that contains a branch that is taken when run as Program B, but is not taken when run as Program A.

Program A (branch not taken)
https://play.golang.org/p/Wc0od6uOS5A

Program B (branch taken)
https://play.golang.org/p/CAjManYolUe

### What did you expect to see?

Programs A and B should output the same results, but do not.  Based on my understanding of Go, I expected the branch to never be taken.

### What did you see instead?

Program A produces no output, whereas Program B produces output.

Note, these issues disappear when a field is introduced into the structs.

**Comment by ALTree** [comment] 2020-05-07 21:16
Hi,

please see https://golang.org/ref/spec#Size_and_alignment_guarantees, in particular:

> A struct or array type has size zero if it contains no fields (or elements, respectively) that have a size greater than zero. **Two distinct zero-size variables may have the same address in memory.**

Stress on *may have*. The compiler is allowed (but not required) to assign the same address in memory to two zero-sized variables. In the first program it does that, while in the second they are assigned different location since they're being used in an `interface{}` map.

Closing here, since this is working as intended (and allowed by the Go specification).

**Closed by ALTree** 2020-05-07 21:16 UTC
