### ISSUE TITLE
x/tools/cmd/gopls: Modifications outside of editor ignored

### ISSUE THREAD

**Issue by atombender** [golang/go#32436] opened 2019-06-04 22:27 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 darwin/amd64
</pre>

Using revision `8aaa148` of `tools`.

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alex/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alex/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/alex/Projects/Transparensee/enclosure-core/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qs/wpmg19r12_9_nz7pvvs2_82r0000gn/T/go-build840369688=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. I ran a `go generate` command, which generates Go files. In this case, the generated code previously defined a struct with a field `NeighborhoodUIDs`; the generate run renamed this to `NeighborhoodUids`.
2. In VSCode, I now wanted to edit other files referencing this struct in order to update all the calling code that uses this field.
3. Gopls insists that `NeighborhoodUids` is incorrect and that the old name is correct.

This implies that Gopls is not correctly monitoring the files on disk. It's only taking into account the changes I make through the editor.

![Screen Shot 2019-06-04 at 18 20 14](https://user-images.githubusercontent.com/50314/58917744-98ca1200-86f5-11e9-9a38-1ad02d04d44b.jpg)

### What did you expect to see?

Gopls should always reflect the current state of files on disk, not just edits made in the editor that uses Gopls.

### What did you see instead?

See above.

[gopls.log.zip](https://github.com/golang/go/files/3254688/gopls.log.zip)

**Comment by stamblerre** [comment] 2019-06-05 03:33
Thanks for the detailed report! Closing this as a duplicate of #31553

**Closed by stamblerre** 2019-06-05 03:33 UTC
Labels: gopls
