### ISSUE TITLE
cmd/go: can't build plugin package when module is named `plugin`

### ISSUE THREAD

**Issue by titpetric** [golang/go#58321] opened 2023-02-04 14:29 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version 1.19.5
</pre>

### Does this issue reproduce with the latest release?

/

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/1.19.5/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go/1.19.5"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/root/.goenv/versions/1.19.5"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/.goenv/versions/1.19.5/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/plugin-compiler/plugin/go.mod"
GOWORK="/root/plugin-compiler/go.work"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2071767594=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

1. created a workspace,
2. checked out anything really,
3. created a plugin/ folder,
4. after adding both folders to the workspace, I tried adding a module for plugin/

```
root@carbon:~/plugin-compiler/plugin# go mod init plugin 
go: creating new go.mod: module plugin
go: to add module requirements and sums:
	go mod tidy
root@carbon:~/plugin-compiler/plugin# go mod tidy
go: warning: "all" matched no packages
```

5. tried adding code for plugin.go (works with go run plugin.go)

```
package main

import (
	"net/http"
)

func InternalServerError(rw http.ResponseWriter, r *http.Request) {
	rw.WriteHeader(http.StatusInternalServerError)
}

func main(){}
```

6. tried tidy and a compile

```
# go mod tidy
go: warning: "all" matched no packages
```

```
# go build -buildmode=plugin .
-buildmode=plugin requires exactly one main package
```

### What did you expect to see?

Successfully built plugin.

### What did you see instead?

Complaints about having one main package:

```
# go list -m 
plugin
github.com/TykTechnologies/tyk
```

**Comment by bcmills** [comment] 2023-02-06 21:34
The problem is the module path: `go mod init plugin` gives the package an import path of `plugin`, which collides with the standard-library [`plugin` package](https://pkg.go.dev/plugin).

Go 1.20 at least gives a somewhat more helpful error message:
```
$ go1.19.5 mod tidy
go: warning: "all" matched no packages

$ go1.20 mod tidy
plugin: ambiguous import: found package plugin in multiple modules:
        plugin (/tmp/tmp.EDj1P18TNO)
         (/usr/local/google/home/bcmills/sdk/go1.20/src/plugin)
```

**Comment by bcmills** [comment] 2023-02-06 21:35
Duplicate of #39285

**Closed by bcmills** 2023-02-06 21:35 UTC
Labels: GoCommand

**Comment by bcmills** [comment] 2023-02-06 21:38
Duplicate of #35270

**Comment by titpetric** [comment] 2023-02-07 19:48
@bcmills called it! Thank you very much.
