### ISSUE TITLE
encoding/base64: RawStdEncoding DecodedLen off by 1 for lengths not divisible by 3

### ISSUE THREAD

**Issue by johndoughnut** [golang/go#16687] opened 2016-08-13 21:26 UTC
1. What version of Go are you using (`go version`)?
go version go1.6.2 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\dev\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
Test decodeLen(encodedLen(x)) != x for various values of x. Only multiples of 3 produce consistent results.

See https://play.golang.org/p/l7lcBKVxDU

It is probably mistaken, e.g.:
encodedLen(1) => 2, ok since you must have 2 6-bit units to accomodate 8 bytes.
decodedLen(2) => should be 1; since you cannot extract 2 full bytes from 12 bits. In actuality, DecodedLen() returns 2.

Correcting this behavior may be bad for backward compatibility.
I suggest alternately to amend the documentation.

**Comment by cespare** [comment] 2016-08-14 00:39
This is a duplicate of #14803, which was fixed in 87151c82b68023e4224b016a6a66ead2c4b8ece7.

That is, this is fixed in Go 1.7, which should be released shortly.

**Comment by josharian** [comment] 2016-08-14 01:00
Thanks, @cespare :)

**Closed by josharian** 2016-08-14 01:00 UTC
