### ISSUE TITLE
x/website: The "Call your code from another module" tutorial has a typo in a command

### ISSUE THREAD

**Issue by kova98** [golang/go#46861] opened 2021-06-21 19:39 UTC
In the [Call your code from another module](https://golang.org/doc/tutorial/call-module-code) tutorial, a command in step 5.1. has a typo:

`$ go mod edit -replace=example.com/greetings=../greetings`

should be 

`$ go mod edit -replace example.com/greetings=../greetings`

**Comment by bcmills** [comment] 2021-06-21 20:45
CC @stevetraut @jayconrod

**Comment by bcmills** [comment] 2021-06-21 20:46
@kova98, are you sure it's a typo? I would expect both of those forms to work equivalently.

**Comment by kova98** [comment] 2021-06-21 20:50
@bcmills I assumed it was a typo. The first command outputs the following error:

`go mod: -replace=: need old[@v]=new[@w] (missing =)`

I am using Powershell.

**Comment by bcmills** [comment] 2021-06-21 21:02
That's a Powershell bug (https://github.com/PowerShell/PowerShell/issues/6291).

**Comment by bcmills** [comment] 2021-06-21 21:02
Duplicate of #44924

**Closed by bcmills** 2021-06-21 21:02 UTC
Labels: Documentation
