### ISSUE TITLE
cmd/go: go.mod should not includes main dependencies, even if they are tagged as indirect

### ISSUE THREAD

**Issue by go101** [golang/go#32137] opened 2019-05-19 03:52 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

`go get` a main package in a modules based project.

### What did you expect to see?

The got main package should not be added as a dependency in go.mod.

### What did you see instead?

The got main package is added as an indirect dependency in go.mod.

**Comment by bcmills** [comment] 2019-05-20 14:42
Duplicate of #30515

**Closed by bcmills** 2019-05-20 14:42 UTC
Labels: modules
