### ISSUE TITLE
cgo: program calling function defined in .dll causes panic

### ISSUE THREAD

**Issue by linuxxiaoyu** [golang/go#30675] opened 2019-03-08 09:48 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
 go version go1.12 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
 Yes

### What operating system and processor architecture are you using (`go env`)?
 Win10
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
dll:
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\a\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\a\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set GO386=sse2
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\a\AppData\Local\Temp\go-build535263530=/tmp/go-build -gno-record-gcc-switches

exe:
GOROOT=c:\go
#GOBIN=
GOARCH=386
GOOS=windows
CGO_ENABLED=1

PATH=c:\mingw32\bin;%GOROOT%\bin;%PATH%

LITEIDE_GDB=gdb
LITEIDE_MAKE=mingw32-make
LITEIDE_TERM=%COMSPEC%
LITEIDE_TERMARGS=
LITEIDE_EXEC=%COMSPEC%
LITEIDE_EXECOPT=/C
</pre></details>

### What did you do?
dll.go:
```
package main

import (
	"C"
	"fmt"
)

//export SayHi
func SayHi() {
	fmt.Println("Hi, I'm go dll")
}

func main() {
}
```

exe.go:
```
package main

import (
	"syscall"
)

func main() {
	/*
		cDll := syscall.MustLoadDLL("C:\\dll\\c.dll")
		f1 := cDll.MustFindProc("SayHi")
		f1.Call()
	*/

	goDll := syscall.MustLoadDLL("C:\\dll\\go.dll")
	f2 := goDll.MustFindProc("SayHi")
	f2.Call()
}
```

I build dll.go:
```
set CGO_ENABLED=1
set GOARCH=386
go build -buildmode=c-shared -o go.dll main.go
```
then put go.dll to C:\dll\go.dll
then I build exe.go and run exe.exe

### What did you expect to see?

```
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x68450151]

goroutine 1 [running, locked to thread]:
runtime.throw(0x684fcf6b, 0x2a)
	c:/go/src/runtime/panic.go:617 +0x64 fp=0x11030c28 sp=0x11030c14 pc=0x684662c4
runtime.sigpanic()
	c:/go/src/runtime/signal_windows.go:227 +0x22d fp=0x11030c3c sp=0x11030c28 pc=0x6847502d
runtime.heapBitsSetType(0x1104a008, 0x8, 0x8, 0x684ecfe0)
	c:/go/src/runtime/mbitmap.go:991 +0x7b1 fp=0x11030cf4 sp=0x11030c3c pc=0x68450151
runtime.mallocgc(0x8, 0x684ecfe0, 0x1102a001, 0x11048100)
	c:/go/src/runtime/malloc.go:969 +0x455 fp=0x11030d48 sp=0x11030cf4 pc=0x68449b55
runtime.growslice(0x684ecfe0, 0x0, 0x0, 0x0, 0x1, 0x2000, 0x800, 0x800)
	c:/go/src/runtime/slice.go:181 +0x181 fp=0x11030d90 sp=0x11030d48 pc=0x684754e1
sync.(*Pool).pinSlow(0x684cbb80, 0x0)
	c:/go/src/sync/pool.go:208 +0x16e fp=0x11030dc0 sp=0x11030d90 pc=0x6848d94e
sync.(*Pool).pin(0x684cbb80, 0x800)
	c:/go/src/sync/pool.go:191 +0x59 fp=0x11030dd0 sp=0x11030dc0 pc=0x6848d7c9
sync.(*Pool).Get(0x684cbb80, 0x44, 0x40824f)
	c:/go/src/sync/pool.go:128 +0x25 fp=0x11030df0 sp=0x11030dd0 pc=0x6848d555
fmt.newPrinter(0x3fffffff)
	c:/go/src/fmt/print.go:134 +0x23 fp=0x11030e00 sp=0x11030df0 pc=0x684b7d83
fmt.Fprintln(0x6850ddb0, 0x0, 0x11030e50, 0x1, 0x1, 0x1, 0x1104e040, 0x68469268)
	c:/go/src/fmt/print.go:264 +0x1e fp=0x11030e30 sp=0x11030e00 pc=0x684b80ce
fmt.Println(...)
	c:/go/src/fmt/print.go:275
main.SayHi(...)
	C:/dll/main.go:10
main._cgoexpwrap_d1dd78daa182_SayHi()
	_cgo_gotypes.go:45 +0x6b fp=0x11030e5c sp=0x11030e30 pc=0x684bd69b
runtime.call16(0x0, 0x19fe48, 0x19fe9b, 0x0, 0x0)
	c:/go/src/runtime/asm_386.s:565 +0x30 fp=0x11030e70 sp=0x11030e5c pc=0x68486ee0
runtime.cgocallbackg1(0x0)
	c:/go/src/runtime/cgocall.go:314 +0x14f fp=0x11030ea8 sp=0x11030e70 pc=0x68443bef
runtime.cgocallbackg(0x0)
	c:/go/src/runtime/cgocall.go:191 +0x9e fp=0x11030ed8 sp=0x11030ea8 pc=0x68443a1e
runtime: unexpected return pc for runtime.cgocallback_gofunc called from 0x4427d6
stack: frame={sp:0x11030ed8, fp:0x11030ee8} stack=[0x11030000,0x11031000)
11030e58:  68486ee0 <runtime.call16+48>  00000004  110480e0  00000000 
11030e68:  11030e74  68443bef <runtime.cgocallbackg1+335>  00000000  0019fe48 
11030e78:  0019fe9b  00000000  00000000  1102a048 
11030e88:  00000002  6846d884 <runtime.exitsyscall+372>  0102a000  00000003 
11030e98:  00000002  1102a000  1102a000  68443a1e <runtime.cgocallbackg+158> 
11030ea8:  00000000  00000002  00403178  684bd720 
11030eb8:  00000000  11030f20  684bd720  684bd720 
11030ec8:  00000000  11030eec  1102a000  6848806e <runtime.cgocallback_gofunc+126> 
11030ed8: <00000000  004b1140  00443660 !004427d6 
11030ee8: >00403197  00443660  004b12d4  110480c0 
11030ef8:  00000008  004b1140  0043665b  00443660 
11030f08:  004b12d4  00000002  004b1140  00446fa9 
11030f18:  684bd720  00000000  00000000  00000000 
11030f28:  00000000  00000000  00000000  00000000 
11030f38:  0045e4e0  00000001  11050040  00446e90 
11030f48:  0045e4e0  11050040  684bd720  00000000 
11030f58:  00000006  00000000  00000000  0045cec0 
runtime.cgocallback_gofunc(0x403197, 0x443660, 0x4b12d4, 0x110480c0)
	c:/go/src/runtime/asm_386.s:806 +0x7e fp=0x11030ee8 sp=0x11030ed8 pc=0x6848806e

goroutine 1 [runnable, locked to thread]:
syscall.NewLazyDLL(0x684f6e27, 0xc, 0x684f6e27)
	c:/go/src/syscall/dll_windows.go:245 +0x23
syscall.init.ializers()
	c:/go/src/syscall/zsyscall_windows.go:38 +0x43
```

### What did you see instead?
Hi, I'm go dll
[issue.zip](https://github.com/golang/go/files/2945241/issue.zip)

**Comment by andybons** [comment] 2019-03-08 18:39
It seems that what you expected to see and what you actually saw are reversed?

@ianlancetaylor @alexbrainman

**Comment by alexbrainman** [comment] 2019-03-08 23:41
@linuxxiaoyu I suspect your issue is a duplicate of #22192. Am I wrong?

Alex

**Comment by linuxxiaoyu** [comment] 2019-03-11 02:18
> @linuxxiaoyu I suspect your issue is a duplicate of #22192. Am I wrong?
> 
> Alex

I think you are right, it  is a duplicate of #22192.

**Closed** 2019-03-11 02:19 UTC
Labels: NeedsInvestigation, OS-Windows
