### ISSUE TITLE
runtime: bad context can be passed to cgo traceback function from SWIG calls to _cgo_panic

### ISSUE THREAD

**Issue by prattmic** [golang/go#47995] opened 2021-08-26 19:37 UTC
`crosscall2` [documents](https://cs.opensource.google/go/go/+/master:src/runtime/cgo/callbacks.go;l=9-37;drc=master) an odd case: though it takes a fourth context argument, SWIG (for historical cases) calls it with only three arguments when calling `_cgo_panic`, leaving the context argument uninitialized.

Normally this is not an issue, as the context would not be used during a panic. However, some rare cases, such as a memory profiling sample in allocation, could trigger a stack trace. At this point, we'll pass the uninitialized context to the cgo traceback function (assuming `runtime.SetCgoTraceback` was called). This function may then crash or otherwise do something wrong with it.

This is easiest to reproduce by setting `runtime.MemProfileRate = 1`.

This is broken at least as far back as Go 1.16, but probably much longer.

**Comment by toothrot** [comment] 2021-09-08 16:24
@prattmic Checking in on this issue as we are reviewing backports. Any update on the status?

**Comment by prattmic** [comment] 2021-09-08 20:28
I've been on vacation, so the CL hasn't made much progress. Getting back to it now.

**Comment by ianlancetaylor** [comment] 2021-09-14 22:29
It doesn't help right away, but I'm planning to change SWIG so that instead of using `crosscall2`, it emits code like this in the generated Go file:

```Go
//go:linkname runtime_cgo_panic_internal runtime._cgo_panic_internal
func runtime_cgo_panic_internal(p *byte)

//export cgo_panic__voidtest_ac12e6cc23abb799
func cgo_panic__voidtest_ac12e6cc23abb799(p *byte) {
	runtime_cgo_panic_internal(p)
}
```

and this in the generated C/C++ file:

```C
extern
#ifdef __cplusplus
  "C"
#endif
  void cgo_panic__voidtest_ac12e6cc23abb799(const char*);
static void _swig_gopanic(const char *p) {
  cgo_panic__voidtest_ac12e6cc23abb799(p);
}
```

The effect of this will be that future versions of SWIG will not use `crosscall2`, but they will depend on `runtime._cgo_panic_internal`.

Does that seem reasonable?

**Comment by aclements** [comment] 2021-09-15 14:25
@ianlancetaylor , that seems reasonable to me. Is there a reason SWIG can't just call `panic` from the Go code? Is it just that we really want to be able to use `gostringnocopy` rather than, say, `C.GoString`, which does a heap allocation?

**Comment by ianlancetaylor** [comment] 2021-09-15 16:58
Yeah, I've thought about this more, and I think SWIG should just do it all itself.

My hesitation there is that it's hard to avoid adding this exported function to every SWIG generated file, and since it is exported it will be kept in the binary.  The result for a program that uses SWIG for several different libraries is duplication of the panic code.  But it may be possible to only emit the exported function if the code actually calls `_swig_gopanic`.  It's not trivial because there are many different ways that SWIG can call that function.

**Comment by ianlancetaylor** [comment] 2021-09-16 00:58
OK, SWIG versions newer than 4.1.0 no longer call `crosscall2`.

I'm going to close this issue: the problem is really that SWIG was using an undocumented and unsupported API, and people who encounter the problem described here can now upgrade to a newer version of SWIG.

**Closed by ianlancetaylor** 2021-09-16 00:58 UTC
Labels: NeedsFix
