### ISSUE TITLE
cmd/compile: nil pointer dereference for receivers has wrong line number

### ISSUE THREAD

**Issue by dhowden** [golang/go#16462] opened 2016-07-22 00:24 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.6.3 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

3. What did you do?

https://play.golang.org/p/qNwU6hT1YS

Force nil-pointer dereference on receiver in method.   The nil-dereference is reported as happening on the method call - line 25 - rather than on the actual deference which is inside the method (line 12).

4. What did you expect to see?

0
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0xffffffff addr=0x0 pc=0x20146]

goroutine 1 [running]:
panic(0x13f4a0, 0x1040a038)
	/usr/local/go/src/runtime/panic.go:481 +0x700
main.main()
	/tmp/sandbox599323765/main.go:12 +0xe6

5. What did you see instead?

0
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0xffffffff addr=0x0 pc=0x20146]

goroutine 1 [running]:
panic(0x13f4a0, 0x1040a038)
	/usr/local/go/src/runtime/panic.go:481 +0x700
main.main()
	/tmp/sandbox599323765/main.go:25 +0xe6

**Comment by dominikh** [comment] 2016-07-22 01:02
This is a duplicate of #10152 and caused by inlining.

**Comment by davecheney** [comment] 2016-07-22 03:14
What happens if you disable inlining? -gcflags=-N

**Comment by dhowden** [comment] 2016-07-22 04:37
@davecheney Still incorrect with inlining disabled.

    $ go build -gcflags=-N example.go
    $ ./example
    0
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x0 pc=0x231f]
    
    goroutine 1 [running]:
    panic(0xda980, 0xc82000a0f0)
    	/usr/local/go/src/runtime/panic.go:481 +0x3e6
    main.main()
    	example.go:25 +0x26f

**Comment by dominikh** [comment] 2016-07-22 04:41
`-N` does not disable inlining, `-l` does.

**Comment by dhowden** [comment] 2016-07-22 04:43
Yeah, sorry.  Just seen that too.  With inlining disabled it shows the correct position.

    $ go build -gcflags="-N -l" example.go
    $ ./example
    0
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x0 pc=0x205d]
    
    goroutine 1 [running]:
    panic(0xda920, 0xc82000a0f0)
    	/usr/local/go/src/runtime/panic.go:481 +0x3e6
    main.(*Example).Value(0x0, 0x0)
    	example.go:12 +0x1d
    main.main()
    	example.go:25 +0x12a

**Comment by davecheney** [comment] 2016-07-22 04:49
My mistake, I thought -N was a superset of -l. Show's how much I've used
that flag.

**Comment by quentinmit** [comment] 2016-07-29 21:01
Closing as dupe of #10152, please comment if you think it's not.

**Closed by quentinmit** 2016-07-29 21:01 UTC
