### ISSUE TITLE
x/tools/gopls: adds import for package not required by module dependencies

### ISSUE THREAD

**Issue by artyom** [golang/go#37285] opened 2020-02-18 15:43 UTC
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

See <https://play.golang.org/p/tNlNNlBk6lx> for the full listing.

Edit a module that requires `github.com/aws/aws-sdk-go` module, refer to some package symbols from that module with an empty "import" section:

	sess, err := session.NewSession()
	if err != nil {
		return err
	}
	svc := cloudwatchlogs.New(sess)

Save file in VSCode to trigger automatic import fixes with gopls.

#### What did you expect to see?

Import section populated with packages from dependencies:

	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/cloudwatchlogs"

#### What did you see instead?

Import section incorrectly populated with package that's not listed in dependencies (second line):

	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/awslabs/fargatecli/cloudwatchlogs"

#### Build info

```
golang.org/x/tools/gopls v0.3.2
    golang.org/x/tools/gopls@v0.3.2 h1:eP1aj1AvT6ynElQH6KP0mmOT2gnWa1gYclHL4wGUbMo=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee h1:WG0RUwxtNT4qqaXX3DPA8zHFNm/D9xaBpxzHt1WcA/E=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20200212213342-7a21e308cf6c h1:D2X+P0Z6ychko7xn2jvd38yxQfdU0eksO4AHfd8AWFI=
    golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898 h1:/atklqdjdhuosWIl6AIbOeHJjicWYPqR9bpxqxYG2pA=
    honnef.co/go/tools@v0.0.1-2019.2.3 h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=
```

#### Go info

```
go version go1.14rc1 darwin/amd64

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/artyom/Library/Caches/go-build"
GOENV="/Users/artyom/Library/Application Support/go/env"
GOEXE=""
GOFLAGS="-ldflags=-w -trimpath"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/artyom/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/artyom/Library/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/artyom/Library/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/artyom/Downloads/gopls-bug/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lb/3rk8rqs53czgb4v35w_342xc0000gn/T/go-build534508186=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by stamblerre** [comment] 2020-02-18 17:23
Thanks for reporting!

/cc @heschik for `goimports`

**Comment by heschik** [comment] 2020-02-18 17:31
Duplicate of #36077, I'm afraid. If you use autocomplete, rather than organize-on-save, it will find the right package. We might be in a position to make some progress now, I'll think about it when I get a chance.

**Closed by heschik** 2020-02-18 17:31 UTC
Labels: Tools, gopls
