### ISSUE TITLE
fmt: unexpected newline error

### ISSUE THREAD

**Issue by syst3mw0rm** [golang/go#10853] opened 2015-05-14 11:21 UTC
The following program crashes with panic:

```
package main

import (
    "fmt"
    "bytes"
)

func main() {
    var a, b int
    r := bytes.NewReader([]byte{'1', '\n', '2'})

    _, err := fmt.Fscanf(r, "%d", &a)
    if err != nil {
        panic(err)
    }

    _, err = fmt.Fscanf(r, "%d", &b)
    if err != nil {
        panic(err)
    }
}
```

```
panic: unexpected newline

goroutine 1 [running]:
main.main()
	/tmp/f.go:19 +0x33d
exit status 2
```

on commit https://github.com/golang/go/commit/b83b01110090c41fc24750ecabf0b87c5fbff233

**Comment by c9s** [comment] 2015-05-29 16:29
I think this behavior is correct. if you run the program with go1.4.2, the result is the same: `unexpected newline`

```
/usr/local/go/bin/go version
go version go1.4.2 darwin/amd64

/usr/local/go/bin/go run test.go
panic: unexpected newline

goroutine 1 [running]:
main.main()
	/Users/c9s/go/test.go:19 +0x3e0

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/local/go/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/local/go/src/runtime/malloc.go:712
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
```

**Comment by robpike** [comment] 2015-06-05 18:03
Working as intended. The first call to Fscanf reads the '1'. The second call expects another integer but instead encounters a newline. It's not well explained in the documentation (and that will be addressed, so I'm leaving this bug open for now), but if there is no newline in the pattern, scanning stops at a newline.

**Comment by robpike** [comment] 2015-06-05 18:07
Duplicate of #9459

**Closed by robpike** 2015-06-05 18:07 UTC

**Comment by syst3mw0rm** [comment] 2015-06-09 02:19
It's not exactly duplicate of #9459

Explicitly mentioning about behaviour being different than corresponding C routines well explains it in documentation - CL10779.
