### ISSUE TITLE
strings.TrimRight works not the same

### ISSUE THREAD

**Issue by 756445638** [golang/go#24891] opened 2018-04-17 08:19 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.8.5 windows/amd64
### Does this issue reproduce with the latest release?
no 

### What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\backstage\newest\hmi-server\code\gopath;D:\golib
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\yuyang\AppData\Local\Temp\go-build583116219=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

### What did you do?
package main

import (
	"fmt"
	"strings"
)

func main() {
	fmt.Println(strings.TrimRight("opc.tcp://188.0.0.181:4840", ":4840"))
	fmt.Println(strings.TrimRight("opc.tcp://188.0.0.182:4840", ":4840"))
	fmt.Println(strings.TrimRight("opc.tcp://188.0.0.183:4840", ":4840"))
	fmt.Println(strings.TrimRight("opc.tcp://188.0.0.184:4840", ":4840"))
	fmt.Println(strings.TrimRight("opc.tcp://188.0.0.185:4840", ":4840"))
	fmt.Println(strings.TrimRight("opc.tcp://188.0.0.186:4840", ":4840"))
}

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
opc.tcp://188.0.0.181
opc.tcp://188.0.0.182
opc.tcp://188.0.0.183
opc.tcp://188.0.0.184
opc.tcp://188.0.0.185
opc.tcp://188.0.0.186

### What did you see instead?

opc.tcp://188.0.0.181
opc.tcp://188.0.0.182
opc.tcp://188.0.0.183
opc.tcp://188.0.0.1
opc.tcp://188.0.0.185
opc.tcp://188.0.0.186

**Comment by ALTree** [comment] 2018-04-17 08:25
In `TrimRight`, the second parameter is a cut**set**: `TrimRight(s string, cutset string)`, i.e. a set of individual characters to be trimmed.

Passing ":4840" doesn't mean "trim right at `:4840`", it means "trim alls `:`, `4`, `8`, and `0` from the right". That's why for `188.0.0.184` the last `4` also gets trimmed.

Working as intended, closing this.

**Closed by ALTree** 2018-04-17 08:25 UTC
