### ISSUE TITLE
x/text: panic in regionGroupDist

### ISSUE THREAD

**Issue by sethvargo** [golang/go#43834] opened 2021-01-21 22:01 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes and HEAD too

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sethvargo/Library/Caches/go-build"
GOENV="/Users/sethvargo/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/sethvargo/Development/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sethvargo/Development/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/sethvargo/Development/text/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cs/jc9pj94x493gb8jr49ys7cnc00gy5b/T/go-build275332944=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Attempted to ParseAcceptLanguage a non-existent language `us-zz`. There's a failing test as a PR at https://github.com/golang/text/pull/17.

### What did you expect to see?

Not a panic.

### What did you see instead?

A panic.

```text
panic: runtime error: index out of range [357] with length 357 [recovered]
	panic: runtime error: index out of range [357] with length 357

goroutine 357 [running]:
testing.tRunner.func1.1(0x138cec0, 0xc000494c60)
	/usr/local/Cellar/go/1.15.6/libexec/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc0004c7380)
	/usr/local/Cellar/go/1.15.6/libexec/src/testing/testing.go:1075 +0x41a
panic(0x138cec0, 0xc000494c60)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:969 +0x1b9
golang.org/x/text/language.regionGroupDist(0x139005a00cf0165, 0x141b400)
	/Users/sethvargo/Development/text/language/match.go:676 +0x13b
golang.org/x/text/language.TestRegionGroups(0xc0004c7380)
	/Users/sethvargo/Development/text/language/match_test.go:178 +0x467
testing.tRunner(0xc0004c7380, 0x13cac60)
	/usr/local/Cellar/go/1.15.6/libexec/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/Cellar/go/1.15.6/libexec/src/testing/testing.go:1168 +0x2b3
FAIL	golang.org/x/text/language	0.138s
FAIL
```

This is especially concerning since some people pass user-provided data to canonicalize (e.g. the `Accept-Lang` header).

**Comment by seankhliao** [comment] 2021-01-21 22:09
The function is [`MustParse`](https://godoc.org/golang.org/x/text/language#MustParse) which panics intentionally:
> MustParse is like Parse, but panics if the given BCP 47 tag cannot be parsed. It simplifies safe initialization of Tag values.

closing as working as intended, please comment/reopen if you disagree

**Comment by sethvargo** [comment] 2021-01-21 22:21
@seankhliao the function being called is [`Matcher.Match`](https://github.com/golang/text/blob/master/language/match.go#L53) (interface). That function makes no mention of `MustParse`, and note that `ParseAcceptLanguage` successfully parsed the language, but calling `matcher.Match` causes the panic.

Also note that the panic is not "failed to parse", it's an index out of bounds exception...

**Comment by sethvargo** [comment] 2021-01-21 22:26
@seankhliao also note there's no direct calls to `MustParse` or a `panic` anywhere in those functions. Furthermore, calling `MustParse` with the language "us-zz" does **not** panic: https://play.golang.org/p/A3M_rOYffT-

This is a bug, please re-open.

**Comment by jeremyfaller** [comment] 2021-01-21 22:28
Reopening for evaluation.

**Comment by seankhliao** [comment] 2021-01-21 22:29
I see, but is there a way to trigger it from the exposed api?

**Comment by sethvargo** [comment] 2021-01-21 22:35
Yes, that's what led me to file a bug. It's currently impacting a production service: https://github.com/google/exposure-notifications-verification-server/blob/79e397e0f917c78f1d3fe388beeb25e14928095f/internal/i18n/i18n.go#L93

**Comment by seankhliao** [comment] 2021-01-21 22:42
right, reproducer using public api:

```go
package main

import (
	"fmt"

	"golang.org/x/text/language"
)

func main() {
	desired, _, err := language.ParseAcceptLanguage("en-ZZ")
	fmt.Println(desired, err)

	matcher := language.NewMatcher([]language.Tag{language.English})
	t, i, c := matcher.Match(desired...)
	fmt.Println(t, i, c)
}

```

**Comment by jeremyfaller** [comment] 2021-01-21 22:48
CC: @mpvl

This was handed off by the COVID project. Any chance this can get a bump in priority for a fix? They have a workaround using `recover()`, but my understanding is that it's kinda kludgy.

**Closed** 2021-03-30 05:48 UTC
Labels: NeedsFix
