### ISSUE TITLE
Should we return mutiple ModSqrt

### ISSUE THREAD

**Issue by zyfrank** [golang/go#32645] opened 2019-06-17 02:33 UTC
https://github.com/golang/go/blob/ead895688def46f4c74c2a4c7ee560fc46663000/src/math/big/int.go#L935
As we know, an element of Fp may have several ModSqrt,    for example 4 of F5 has two ModSqrt: 2, 3,   maybe we should return all these ModSqrt

**Comment by randall77** [comment] 2019-06-17 03:08
When ModSqrt returns z, then -z is the other root. It seems not a lot of work to compute yourself.
We can't change the semantics of ModSqrt because of the Go 1 compatibility guarantee. We'd have to introduce another function.

**Comment by zyfrank** [comment] 2019-06-17 03:22
Yes, you are right, client can compute another root.  Here another question is  if ModSqrt  always return the smaller one?

**Comment by av86743** [comment] 2019-06-17 06:18
"Smaller" presumes that Fp is ordered.  Which finite fields are not. As we know.

**Comment by zyfrank** [comment] 2019-06-17 11:20
what I mean is, between 0~p-1, will ModSqrt  always return smaller one (In element 4 of F5, return 2 instead of 3) for different p, so in some meaning, the return value is determined

**Comment by randall77** [comment] 2019-06-17 13:49
Why do you want the return value to be determined?

**Comment by av86743** [comment] 2019-06-17 17:14
> what I mean is, between 0~p-1, will ModSqrt always return smaller one (In element 4 of F5, return 2 instead of 3) for different p, so in some meaning, the return value is determined

@zyfrank Looking at the code for special cases of ModSqrt (just above the ModSqrt itself) or the corresponding theorem, it is not obvious that it calculates the smallest root in Np.  Likely it is not true.  Try ModSqrt for some small values of p and see whether ModSqrt will always give you a smallest root.

**Comment by bmkessler** [comment] 2019-06-17 18:32
I'm not sure the current behavior, but if you want to guarantee that the root z is the "smaller" one (less than or equal to p/2), you can do that fairly easily.

```
if z.Cmp(new(big.Int).Rsh(p, 1)) > 0 {
  z.Sub(p, z)
}
```

Where p/2 can be stored and reused for repeat calculations.

**Comment by katiehockman** [comment] 2019-06-17 19:49
As @randall77 mentioned, the semantics of ModSqrt won't change. As this seems more like a question thread, and not a bug or a proposal, I'm going to close this issue. For questions about Go, see https://golang.org/wiki/Questions.

**Closed by katiehockman** 2019-06-17 19:49 UTC
Labels: Question
