### ISSUE TITLE
x/tools/gopls: code lens for interfaces implemented by methods

### ISSUE THREAD

**Issue by guettli** [golang/go#58024] opened 2023-01-26 15:36 UTC
**Is your feature request related to a problem? Please describe.**

If I am looking at existing Go code, I would like to see immediately if this method was
implemented to satisify an interface.

For example like this screenshot from a different IDE:

![image](https://user-images.githubusercontent.com/414336/214878152-cabc8bff-c8ac-4cce-b246-77a7522d6d59.png)

the red up-arrow symbol on the left side shows that this method implements an interface.

It would be great to have these indicators next to the line number in vscode.

**Describe alternatives you've considered**

I thought about alternatives, but having a small indictor next to the line number is the only solution I have found.

Related discusssion: https://github.com/golang/vscode-go/discussions/1735

**Comment by findleyr** [comment] 2023-01-26 21:35
@hyangah points out that this is a dupe of #56695.

**Closed by findleyr** 2023-01-26 21:35 UTC
Labels: FeatureRequest, gopls, Tools
