### ISSUE TITLE
cmd/pprof: web/weblist visualization failure caused by incorrect web browser invocation is hard to debug

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#25853] opened 2018-06-12 20:40 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10.3

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOOS="darwin"

### What did you do?

Running a simple profiler with the following two lines of code: 

```golang
pprof.StartCPUProfile(os.Stdout)
defer pprof.StopCPUProfile()
```

Create a file with output such as `cpu.prof` and run `pprof cpu.prof` 

In the CLI, run `web` to open up a webpage 
or run `weblist <function-name>`

### What did you expect to see?
A web page with the profile svg or html correctly displayed. 

### What did you see instead?

```
FATAL[0000] couldn't read file: /Users/xxx/go/src/github.com/marwan-at-work/xxx/var/folders/n4/35bgdnkd6vlgqrdzbyl0x1ycmhcndx/T/pprof002.svg error=open /Users/xxx/go/src/github.com/marwan-at-work/xxx/var/folders/n4/35bgdnkd6vlgqrdzbyl0x1ycmhcndx/T/pprof002.svg: no such file or directory
pprof: exit status 1
```

Noting that the file (pprof002.svg) actually does exist under `/var/folders/n4/35bgdnkd6vlgqrdzbyl0x1ycmhcndx/T/pprof002.svg ` but not `/Users/xxx/go/src/github.com/marwan-at-work/xxx/var/folders/n4/35bgdnkd6vlgqrdzbyl0x1ycmhcndx/T/pprof002.svg`

**Comment by ysmolsky** [comment] 2018-06-13 09:13
There must be something in your program which produces some side effect resulting in this. Maybe your program writes into stdout/stderr. Can you paste your program?

**Comment by marwan-at-work** [comment] 2018-06-13 18:35
@ysmolsky it turns out I had a `chrome` binary that had nothing to do with Google Chrome and it was executing that one instead. But this makes me realize that the `chrome` command for MacOS is incorrect because AFAIK the Chrome command is this: `/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`. 

The reason this has been working for most people on Mac, I assume, is because of the last command `/usr/bin/open` which opens the svg file directly when a user types `web` in the pprof cli. However this could open the svg file in an editor instead of a browser depending on what your default application for the .svg extension. 

My suggestion is to add the real Chrome path mentioned above as one of the mac os commands to run. Probably in line 343 for reference: https://github.com/google/pprof/blob/master/internal/driver/commands.go#L340-L343

Happy to hear your thoughts and submit a pr unless you see something incorrect about my assumptions above. Thanks

**Comment by ysmolsky** [comment] 2018-06-13 20:49
@marwan-at-work 
I am sorry, but adding a specific path to the specific Chrome does not sound right. The right approach is to relay on system command which open file by associatio setup in user OS. The way it works right now. You might want to fix your OS so that `/usr/bin/open` chooses the right application for SVG file.

**Comment by marwan-at-work** [comment] 2018-06-13 20:59
@ysmolsky I agree with the specific path to Chrome (although this is the default binary path for every macOS chrome browser).

Furthermore, I personally have never seen `chrome` or `google-chrome` as binaries in PATH on a MacOS before. I could be wrong of course. But having them might just be more confusing if someone actually has a `chrome` binary that's unrelated to the browser. 

I wonder if there's a way to warn the user so they wouldn't spend 3-5 hours like I did being confused as to why "chrome" wasn't working with pprof. Maybe just default to `/usr/bin/open`? 

Thanks!

**Comment by ysmolsky** [comment] 2018-06-13 22:11
One thing that I have noticed is that pprof does not report an error when the first found vizualizers have returned an error:
```
% cat $(which chrome)
#!/bin/sh
echo ERROR
exit 1
% go tool pprof prof.prof
Main binary filename not available.
Type: cpu
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) web
(pprof)
```

That means that I cannot reproduce your problem. Also did you run `go tool pprof` or `pprof`?..

Wait a second. The `pprof` code you linked to above is not in Go project. You might want to address it there.

Ping @hyangah for some ideas.

**Comment by marwan-at-work** [comment] 2018-06-14 00:36
@ysmolsky the error that i got was actually from the "random" `chrome` binary that I had so it's becoming irrelevant to the findings that followed :) Maybe I should update the issue title and description? Let me know, thanks!

**Comment by hyangah** [comment] 2018-06-14 16:21
I filed a new issue in google/pprof. That's a better place for the discussion.
@marwan-at-work  Did the failure from your chrome command cause the pprof CLI to exit as well?

**Comment by hyangah** [comment] 2018-06-14 18:04
Good. Thanks for the update. I will close this bug for now.

**Closed by hyangah** 2018-06-14 18:04 UTC
Labels: WaitingForInfo
