### ISSUE TITLE
go/doc: methods on type error are shown in docs

### ISSUE THREAD

**Issue by tv42** [golang/go#9860] opened 2015-02-13 01:03 UTC
Something in this source is making godoc.org do weird things: http://godoc.org/github.com/alphazero/contextual

First guess would be this: https://github.com/alphazero/contextual/blob/1d18e8ac42a5e6e2e65dc02f44b93e48c8170bce/contextual.go#L30

```go
type error struct {
	msg string
}
```

Here's the index as it shows up right now:

```
Index
Constants
func ChildContext(p *context) (c *context, e Error)
func (e error) Error() string
func (e error) Is(errmsg string) bool
func NewContext() *context
type Component
func NewComponent() Component
type Container
type Context
type Contextual
type Error
```

Now, that source is silly but this still sounds like a bug in godoc.org.

**Comment by tv42** [comment] 2015-02-13 01:06
Migrated to https://github.com/golang/gddo/issues/244, sorry for the noise.

**Comment by adg** [comment] 2015-02-13 01:09
If you declare a type named `error` (a bad idea) then godoc shows its methods:
```
~/src/test $ cat test.go
package test

type error struct{}

func (error) F() {}
$ godoc test
PACKAGE DOCUMENTATION

package test
    import "test"

FUNCTIONS

func (error) F()
```

**Comment by garyburd** [comment] 2015-02-13 01:11
The issue is in the go/doc package.

**Comment by josharian** [comment] 2015-02-18 00:19
@adg sorry for being slow, but why is this not working as intended?

**Comment by adg** [comment] 2015-02-18 00:21
@josharian the package-level `error` type is not exported, so its methods should not be visible in the package docs.

**Comment by larzconwell** [comment] 2016-03-12 18:16
I made an easy fix for this. go/doc simply drops any methods defined on locally-declared predeclared types, since the types are never exported its methods should never be visible(unless AllDecls is given, of course).

**Comment by rsc** [comment] 2016-05-17 13:58
@griesemer, I added you as a reviewer to CL 20610. Please make a decision for Go 1.7. Thanks.

**Closed** 2016-10-06 00:36 UTC
