### ISSUE TITLE
Add Unwrappable interface to errors package

### ISSUE THREAD

**Issue by gerobinson** [golang/go#49607] opened 2021-11-16 11:40 UTC
I think it would be great if there was an `Unwrappable` interface in the `errors` package to show that it's possible to unwrap structured errors without having to refer to the source code for [Unwrap](https://cs.opensource.google/go/go/+/refs/tags/go1.17.3:src/errors/wrap.go;l=14).

For example, can I unwrap `MyError` if I add a receiver `Unwrap() error`?

```
type MyError struct {
    Err        error
    StatusCode int
}

func (e MyError) Unwrap() error {
    return e.Err
}
```

**Comment by seankhliao** [comment] 2021-11-16 11:44
Duplicate of #35306

**Closed by seankhliao** 2021-11-16 11:44 UTC
