### ISSUE TITLE
The binary size is growing. 1.9 vs 1.8

### ISSUE THREAD

**Issue by deepch** [golang/go#21653] opened 2017-08-28 00:45 UTC
I'm trying to make small applications for IP cameras. But with each version the size is bigger and bigger.

go version go1.9 darwin/amd64 vs  1.8

i test make 

`export GOPATH=/Users/deepweb/Desktop/work/ipeye/ivs/
#linux
GOOS=linux GOARCH=mipsle go build -ldflags="-s -w" -o ./build/cloud_linux_mipsle.run *.go
./bin/goupx ./build/cloud_linux_mipsle.run

GOOS=linux GOARCH=mips go build -ldflags="-s -w" -o ./build/cloud_linux_mips.run *.go
./bin/goupx ./build/cloud_linux_mips.run

GOOS=linux GOARCH=mips64 go build -ldflags="-s -w" -o ./build/cloud_linux_mips64.run *.go

GOOS=linux GOARCH=mips64le go build -ldflags="-s -w" -o ./build/cloud_linux_mips64le.run *.go

GOOS=linux GOARCH=arm GOARM=5 go build -ldflags="-s -w" -o ./build/cloud_linux_arm_v5.run *.go
./bin/goupx ./build/cloud_linux_arm_v5.run

GOOS=linux GOARCH=arm GOARM=6 go build -ldflags="-s -w" -o ./build/cloud_linux_arm_v6.run *.go
./bin/goupx ./build/cloud_linux_arm_v6.run

GOOS=linux GOARCH=arm GOARM=7 go build -ldflags="-s -w" -o ./build/cloud_linux_arm_v7.run *.go
./bin/goupx ./build/cloud_linux_arm_v7.run

GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o ./build/cloud_linux_amd64.run *.go
./bin/goupx ./build/cloud_linux_amd64.run

GOOS=linux GOARCH=386 go build -ldflags="-s -w" -o ./build/cloud_linux_386.run *.go
./bin/goupx ./build/cloud_linux_386.run

GOOS=linux GOARCH=ppc64 go build -ldflags="-s -w" -o ./build/cloud_linux_ppc64.run *.go

GOOS=linux GOARCH=ppc64 go build -ldflags="-s -w" -o ./build/cloud_linux_ppc64le.run *.go

#android
#GOOS=android GOARCH=arm go build  -o ./build/cloud_android_arm.run *.go
#./bin/goupx ./build/cloud_android_arm.run
#freebsd
GOOS=freebsd GOARCH=amd64 go build -ldflags="-s -w" -o ./build/cloud_freebsd_amd64.run *.go
GOOS=freebsd GOARCH=386 go build -ldflags="-s -w" -o ./build/cloud_freebsd_386.run *.go
./bin/goupx ./build/cloud_freebsd_386.run
GOOS=freebsd GOARCH=arm go build -ldflags="-s -w" -o ./build/cloud_freebsd_arm.run *.go
#windows
GOOS=windows GOARCH=386 go build -ldflags="-s -w" -o ./build/cloud_windows_386.exe *.go
GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o ./build/cloud_windows_amd64.exe *.go
#max os x
GOOS=darwin GOARCH=386 go build -ldflags="-s -w" -o ./build/cloud_darwin_386.run *.go
GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o ./build/cloud_darwin_amd64.run *.go
#dragonfly
GOOS=dragonfly GOARCH=amd64 go build -ldflags="-s -w" -o ./build/cloud_dragonfly_amd64.run *.go

#netbsd
GOOS=netbsd GOARCH=386 go build -ldflags="-s -w" -o ./build/cloud_netbsd_386.run *.go
GOOS=netbsd GOARCH=amd64 go build -ldflags="-s -w" -o ./build/cloud_netbsd_amd64.run *.go
GOOS=netbsd GOARCH=arm go build -ldflags="-s -w" -o ./build/cloud_netbsd_arm.run *.go

#netbsd
GOOS=openbsd GOARCH=386 go build -ldflags="-s -w" -o ./build/cloud_openbsd_386.run *.go
GOOS=openbsd GOARCH=amd64 go build -ldflags="-s -w" -o ./build/cloud_openbsd_amd64.run *.go
GOOS=openbsd GOARCH=arm go build -ldflags="-s -w" -o ./build/cloud_openbsd_arm.run *.go

#plan9
GOOS=plan9 GOARCH=386 go build -ldflags="-s -w" -o ./build/cloud_plan9_386.run *.go
GOOS=plan9 GOARCH=amd64 go build -ldflags="-s -w" -o ./build/cloud_plan9_amd64.run *.go
#solaris
GOOS=solaris GOARCH=amd64 go build -ldflags="-s -w" -o ./build/cloud_solaris_amd64.run *.go
`
and result On the left 1.9 on the right 1.8.3 

![2017-08-28 3 40 06](https://user-images.githubusercontent.com/7899955/29755583-0567da1e-8ba3-11e7-8969-cdf40d5a34c4.png)

Perhaps it is not significant for many but for devices where little memory is important.

Maybe go1.9 there are some keys that would be smaller.

**Comment by mvdan** [comment] 2017-08-28 07:25
Duplicate of #6853, which we use as an umbrella issue for this. Unfortunately, that issue is locked so I can't tell you to place your data points in a comment if you wish to. I'll just link to this issue from there and close this one.

**Closed** 2017-08-28 07:25 UTC

**Comment by warmchang** [comment] 2018-04-20 14:09
mark.
