### ISSUE TITLE
Mime for JS files: When does TypeByExtension return application/javascript or text/javascript?

### ISSUE THREAD

**Issue by tushardas** [golang/go#47912] opened 2021-08-23 13:31 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.3 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
</pre></details>

### What did you do?
I'm using mime package to determine the content type for a .js file
https://play.golang.org/p/qc95mVBT6fJ

### What did you expect to see?
My expectation is it should output the same value in local terminal as well as Github actions(where my tests are run)

Also, we have had this tests from long now and the output used to be `application/javascript` always. Have started seeing `text/javascript; charset=utf-8` today(23-Aug) only

### What did you see instead?
In playground and in Github Actions(where my tests are run), the output is `text/javascript; charset=utf-8`
Whereas in my local terminal the output for the same is `application/javascript`

**Comment by seankhliao** [comment] 2021-08-23 14:01
Duplicate of #32350

**Closed by seankhliao** 2021-08-23 14:01 UTC
