### ISSUE TITLE
cmd/compile: "missing function body" error when using the //go:linkname compiler directive

### ISSUE THREAD

**Issue by bigfg** [golang/go#23408] opened 2018-01-11 11:43 UTC
For example let's say (hypothetically) that I wanted to call the strhash function defined in the runtime package, I could do:

`package key

import "unsafe"

//go:linkname strhash runtime.strhash
func strhash(a unsafe.Pointer, h uintptr) uintptr

func hash(s string) uintptr {
    return strhash(unsafe.Pointer(&s), 0)
}`

this case came from: https://github.com/golang/go/issues/15006

actually, I try to fix this with:
flag.BoolVar(&completeFlag, "complete", true, "compiling complete package")

But it doesn't seem to work.

**Comment by davecheney** [comment] 2018-01-11 12:01
Place an empty .s file in the same package to stimulate the go tool to elide the -complete flag.

**Comment by crvv** [comment] 2018-01-12 02:17
This looks like a duplicate of https://github.com/golang/go/issues/23311

**Comment by davecheney** [comment] 2018-01-12 03:17
Closing as answered.

**Closed by davecheney** 2018-01-12 03:17 UTC
