### ISSUE TITLE
proposal: Go 2: map behavior

### ISSUE THREAD

**Issue by TamyGit** [golang/go#57471] opened 2022-12-27 08:11 UTC
### Proposal
map supports two return values.
```
var m = map[string]string {"1": "one", "2": "two"}
v := m["1"]
v, ok := m["1"]
```
Why is it going to be error in a function?
```
func get(key string) (string, bool) {
	//return m[key] // Error
	v, ok := m[key]
	return v, ok
}
```
I feel it is not right behavior.

**Comment by seankhliao** [comment] 2022-12-27 08:22
Duplicate of #6230

**Closed by seankhliao** 2022-12-27 08:22 UTC
Labels: Proposal
