### ISSUE TITLE
runtime: frequent SIGSEGV in clock_gettime_trampoline on openbsd-386

### ISSUE THREAD

**Issue by bcmills** [golang/go#49532] opened 2021-11-11 19:56 UTC
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf1 pc=0x80a3000]

runtime stack:
runtime.throw({0x816ebe4, 0x2a})
	/tmp/workdir/go/src/runtime/panic.go:992 +0x64
runtime.sigpanic()
	/tmp/workdir/go/src/runtime/signal_unix.go:781 +0x22b
runtime.clock_gettime_trampoline()
	/tmp/workdir/go/src/runtime/sys_openbsd_386.s:524 +0x20

goroutine 8 [running]:
runtime.systemstack_switch()
	/tmp/workdir/go/src/runtime/asm_386.s:337 fp=0x72c2b768 sp=0x72c2b764 pc=0x80a0ba0
runtime.libcCall(0x80a2fe0, 0x72c2b794)
	/tmp/workdir/go/src/runtime/sys_libc.go:48 +0x5a fp=0x72c2b77c sp=0x72c2b768 pc=0x809386a
runtime.nanotime1()
	/tmp/workdir/go/src/runtime/sys_openbsd2.go:161 +0x51 fp=0x72c2b7a0 sp=0x72c2b77c pc=0x8093d71
runtime.nanotime(...)
	/tmp/workdir/go/src/runtime/time_nofake.go:19
runtime.gcBgMarkWorker()
	/tmp/workdir/go/src/runtime/mgc.go:1245 +0x13d fp=0x72c2b7f0 sp=0x72c2b7a0 pc=0x805e65d
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_386.s:1311 +0x1 fp=0x72c2b7f4 sp=0x72c2b7f0 pc=0x80a1ee1
created by runtime.gcBgMarkStartWorkers
	/tmp/workdir/go/src/runtime/mgc.go:1122 +0x1f
```

`greplogs --dashboard -md -l -e \(\?ms\)\\Aopenbsd-.\*clock_gettime_trampoline`

<details>

[2021-11-11T16:17:21-666fc17/openbsd-386-68](https://build.golang.org/log/e86656a0c993047c4fbb2967066726899e6d041e)
[2021-11-11T04:02:33-3949faf/openbsd-386-68](https://build.golang.org/log/477cc46a4c5434a0b1a70f6ed5634c87c808f256)
[2021-11-10T21:53:03-229b909/openbsd-386-68](https://build.golang.org/log/b23491d1d330a1a8ba26164cce44bd83c1949276)
[2021-11-10T17:15:54-8a3be15/openbsd-386-68](https://build.golang.org/log/25e16ed8600c1b5c04d7d157a53d82fdf99bd2ba)
[2021-11-10T05:08:25-17980df/openbsd-386-68](https://build.golang.org/log/7dc495dd2c1b8e98171a5f37aaf1335344d41f6d)
[2021-11-10T02:26:41-02d7eab/openbsd-386-68](https://build.golang.org/log/4f53bcb8b3c40d3903582098a94de650e90e24f1)
[2021-11-10T00:45:37-ec86bb5/openbsd-386-68](https://build.golang.org/log/260e501e7a4e667a29319bc1d2c166a6cccca3e8)
[2021-11-09T21:58:03-805b4d5/openbsd-386-68](https://build.golang.org/log/6f407da615cc47fc566375be960f702c3dc5b040)
[2021-11-09T00:08:09-bee0c73/openbsd-386-68](https://build.golang.org/log/c190dd9266e61ab8f9c5a333b4eb1ee9989c9f3d)
[2021-11-08T17:46:34-2e210b4/openbsd-386-68](https://build.golang.org/log/a225ba7a02ac95589b462f52070d5a2e2f8724dc)
[2021-11-06T19:41:14-cfb3dc7/openbsd-386-68](https://build.golang.org/log/9b173aed8129b24017b6bacfee2a07c30f71bcf7)
[2021-11-06T16:43:43-3544082/openbsd-386-68](https://build.golang.org/log/59c510a457f9bc7f60d27a2eb7ae44cc619bdcb5)
[2021-11-05T22:55:56-e83a204/openbsd-386-68](https://build.golang.org/log/789920b757b927c6c67a16a7b22ce70862ab25f2)
[2021-11-05T21:34:10-bb53fd7/openbsd-386-68](https://build.golang.org/log/7c2b56ffa5ebe1a9fdb4a1c174e85d0065df1b60)
[2021-11-05T21:28:34-90462df/openbsd-386-68](https://build.golang.org/log/a5c24b80a4099561502065335447ef0c3389e154)
[2021-11-05T21:27:34-7aed6dd/openbsd-386-68](https://build.golang.org/log/2a16fd34f4b1894bcf7da07ee5a8e7d5d9022551)
[2021-11-05T21:27:19-58ec925/openbsd-386-68](https://build.golang.org/log/cb18b7094e5f039db77426064348aad0c972c766)
[2021-11-05T00:52:04-1c4cfd8/openbsd-386-68](https://build.golang.org/log/89d4095483378315c511909b20c8f72154345fb5)
[2021-11-04T23:56:29-0e5f287/openbsd-386-68](https://build.golang.org/log/d9d08e7961f6071c89c1c28f6860086e0cbc4ece)
[2021-11-04T21:41:49-156abe5/openbsd-386-68](https://build.golang.org/log/1957cf8f6fc9a87c6d0c9f12fc58e2bbe089a2e1)
[2021-11-04T20:01:10-9b2dd1f/openbsd-386-68](https://build.golang.org/log/20f6ad75dcc6a9e89200349e243c60d48186a20d)
[2021-11-04T20:00:54-961aab2/openbsd-386-68](https://build.golang.org/log/51fbdc43dd7ec7dc83d7f4bedd4ebbd15509bcdd)
[2021-10-06T22:28:59-d477ef3-b18ba59/openbsd-386-64](https://build.golang.org/log/ca668c3e2c90a8cd78ce5c90baf01b3ecb1899ea)
[2021-09-30T20:30:12-1c35f2a-c035d82/openbsd-386-64](https://build.golang.org/log/374194f7011a69837e0e92cd557b0b08f248fb33)
[2021-09-29T20:06:10-1c35f2a-5930cff/openbsd-386-64](https://build.golang.org/log/d31c4f52a8f3593b2d0fc9da566a3acd77bab13d)
[2021-09-27T22:22:35-ba6b94c-cd4d592/openbsd-386-64](https://build.golang.org/log/ba06269e60eed37cd74e6369e9c7d3b3feb981ed)
[2021-09-21T13:18:09-fe076c8-39e08c6/openbsd-386-64](https://build.golang.org/log/e2ec0b543036fdbf38af30ecc388cbd4ad21f135)
[2021-09-09T00:10:46-076821b-e30a090/openbsd-386-64](https://build.golang.org/log/465848ff0504a038e0903090b7cc2e8d6c30bbe1)
[2021-08-30T02:40:46-3e0d083-56c3856/openbsd-386-64](https://build.golang.org/log/245ff3c68a7c42fde60b0b15fc7474e9de1765d9)
[2021-08-16T12:54:44-a55d515-c88e3ff/openbsd-386-64](https://build.golang.org/log/7af9447fd9ee88f58e91a8c79d9c6aaf2ced629e)
[2021-07-14T17:25:06-5061c41-60ddf42/openbsd-386-64](https://build.golang.org/log/cff1d441674a8da6dae5babbc4b48fef1ed8aa1d)
[2021-06-21T20:53:11-d25f906-761edf7/openbsd-386-64](https://build.golang.org/log/7b8608c1d6c3a6766c5c25aaecc72caf1fd590bf)
[2021-06-08T20:19:02-689f4c7/openbsd-386-68](https://build.golang.org/log/91d79b4c03a6b9e1ec9195427a29b523b5188177)
[2021-06-08T20:19:02-689f4c7/openbsd-amd64-64](https://build.golang.org/log/3279e53243fc3e258b5847a34adeb89331723188)
[2021-06-03T16:41:39-4abb1e2-e0d029f/openbsd-386-64](https://build.golang.org/log/0325d2220b26f3d77290205bc5fddf0f26654cdf)
[2021-06-02T21:39:28-384c392-dd7ba3b/openbsd-386-64](https://build.golang.org/log/2eff8336d65d87020b4487d4e22109e8a8dcee57)
[2021-05-12T20:59:48-8287d5d-6db7480/openbsd-386-64](https://build.golang.org/log/7c50055fbf3a7327c95749e44331d98e0da6b4c0)
[2021-05-10T23:42:56-79d39ff-5c48951/openbsd-386-64](https://build.golang.org/log/481f94feb6da370cc850c2a7fc0d0e131f4f425b)
[2021-05-08T17:03:18-f05e912-b38b1b2/openbsd-386-64](https://build.golang.org/log/66cb2b2d507fd386767c6333e9e6d201802e2035)
[2021-05-07T02:17:32-c0140e8-d2b0311/openbsd-386-64](https://build.golang.org/log/a730ad6965b3c8991edab90322885bd313f6b422)
[2021-05-05T21:37:16-1949673-cf73f1a/openbsd-386-64](https://build.golang.org/log/b9ad3709d40784cc9750a3137ef1114cc6f2158f)

</details>

**Comment by bcmills** [comment] 2021-11-11 20:07
This looks like a fairly old bug, but the failure rate varies. It seems to have gone from “a couple per week” to “several per day” around 2021-11-04.

**Comment by bcmills** [comment] 2021-11-11 20:38
I wonder if this is related to #47629.

@4a6f656c, any ideas?

**Comment by cherrymui** [comment] 2021-11-11 23:37
> /tmp/workdir/go/src/runtime/sys_openbsd_386.s:524

That line intentionally faults when clock_gettime syscall fails. Why the syscall could fail? And why it is nondeterministic?

**Comment by jeremyfaller** [comment] 2021-11-12 20:50
Investigations lead us to believe this is okay after Beta1 because this has been happening for some time, seems to be confined to this platform, and isn't a first-class port.

**Comment by prattmic** [comment] 2021-11-16 22:58
Just a shot in the dark, but does anyone know if openbsd's libc requires any particular alignment on SP? runtime·clock_gettime_trampoline doesn't do any alignment, so I wonder if that is tripping up a check in libc or the kernel.

**Comment by cherrymui** [comment] 2021-11-16 23:18
I thought about that. I don't know. But we also don't align the SP in other syscall trampolines, whereas it always fails here. Also, if that's the case, I'd expect it fails much more deterministically.

**Comment by 4a6f656c** [comment] 2021-11-18 18:40
I would have to double check, but I do not believe there are alignment requirements beyond those normally required by the hardware architecture itself (it is also trivial to write test code to verify this) - `clock_gettime(2)` should rarely/never fail and is only documented as returning EINVAL (invalid clock which is highly unlikely given how we call in) and EFAULT (bad memory). It is also worth noting that there is timekeep memory that can avoid libc from having to make an actual syscall, although if this was involved we'd probably be seeing faults within libc itself.

I suspect the underlying issue is some form of memory corruption given we're seeing other failures like faulting on unlock:

  https://build.golang.org/log/3e594f9d7a015c79ab62629337b14a2e21a86e9d

Additionally, the openbsd-386-68 builder had been passing fairly consistently during the development cycle and things seem to have turned red around early November (although in limited testing I've not been able to trigger failures myself).

**Comment by prattmic** [comment] 2021-11-18 19:15
> I would have to double check, but I do not believe there are alignment requirements beyond those normally required by the hardware architecture itself (it is also trivial to write test code to verify this) - clock_gettime(2) should rarely/never fail and is only documented as returning EINVAL (invalid clock which is highly unlikely given how we call in) and EFAULT (bad memory). It is also worth noting that there is timekeep memory that can avoid libc from having to make an actual syscall, although if this was involved we'd probably be seeing faults within libc itself.

I also clicked through the source in libc and the kernel and did not notice anything particularly noteworthy. No explicit alignment checks, no odd error paths beyond the ones @4a6f656c mentioned. The only thing of note is that it appeared that on 386, libc may really need to make a system call. I didn't see the fast path getting set up for 386 like it does for amd64, though I may well have missed it.

**Comment by 4a6f656c** [comment] 2021-11-19 08:34
> > I would have to double check, but I do not believe there are alignment requirements beyond those normally required by the hardware architecture itself (it is also trivial to write test code to verify this) - clock_gettime(2) should rarely/never fail and is only documented as returning EINVAL (invalid clock which is highly unlikely given how we call in) and EFAULT (bad memory). It is also worth noting that there is timekeep memory that can avoid libc from having to make an actual syscall, although if this was involved we'd probably be seeing faults within libc itself.
> 
> I also clicked through the source in libc and the kernel and did not notice anything particularly noteworthy. No explicit alignment checks, no odd error paths beyond the ones @4a6f656c mentioned. The only thing of note is that it appeared that on 386, libc may really need to make a system call. I didn't see the fast path getting set up for 386 like it does for amd64, though I may well have missed it.

Ah, no you're correct - I neglected to recall that `_tc_get_timecount` is not set on OpenBSD i386, which means we're always calling the `clock_gettime(2)` syscall. That means that we're almost certainly failing due to EFAULT (`ktrace` would confirm if we can get a reproducible test case).

**Comment by cherrymui** [comment] 2021-11-23 22:04
It seems the failure only occurs on openbsd-386-68 builder, not -70 or -70-n1 builders.

**Comment by cherrymui** [comment] 2021-11-24 16:53
It is also interesting that all failures seem to come from the cmd/dist binary, not anything else.

**Comment by aclements** [comment] 2021-12-06 16:41
It's possible I made this worse. I haven't seen any clock_gettime failures since my CL went in, but we did get a new ["stopm holding p"](https://build.golang.org/log/5a1455eb7da8e15517fdd41d34327650735da98f) with, unfortunately, no useful backtrace, which we haven't seen before.

**Comment by cherrymui** [comment] 2021-12-15 18:38
Seems this hasn't occurred since @aclements 's CL...

**Comment by ianlancetaylor** [comment] 2022-01-29 00:35
For better or for worse, this is no longer happening, so closing.

**Closed by ianlancetaylor** 2022-01-29 00:35 UTC
Labels: OS-OpenBSD, NeedsInvestigation
