### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by Zalizer** [golang/go#61652] opened 2023-07-29 18:23 UTC
### What is the URL of the page with the issue?
 https://go.dev/doc/tutorial/random-greeting
 
### What is your user agent?
 Firefox
 
### Screenshot
 Add an init function to seed the rand package with the current time. Go executes init functions automatically at program startup, after global variables have been initialized. For more about init functions, see [Effective Go](https://go.dev/doc/effective_go.html#init).
 
### What did you do?
Perform the tutorial :)
 
### What did you expect to see?
Descriptions matching the code.
 
### What did you see instead?
Reference to old "init" code, which I guess got removed after Go 1.20, when not needed anymore.
https://pkg.go.dev/math/rand#Seed

**Comment by seankhliao** [comment] 2023-07-29 18:57
Duplicate of #60627

**Closed by seankhliao** 2023-07-29 18:57 UTC
Labels: website
