### ISSUE TITLE
proposal: http/server.go: log from logger of server field

### ISSUE THREAD

**Issue by Spuxy** [golang/go#65026] opened 2024-01-08 21:43 UTC
## Background

Available to log, that client has sent too big header.

## Proposal

access `*log.Logger` from value `server` of type `*Server`, to be able for developer to get info when some client could not http handshake
https://github.com/golang/go/blob/b702e0438ae9577dcc642ba7696a89799c86c8b7/src/net/http/server.go#L1973-L1982
	

## API changes

Minimal ? The `*log.Logger` is already implemented when its not passed into `server`, then its default logger or user can pass his `user-defined` struct

## Benefits

Better metrics and information about connections to go app

**Comment by AlexanderYastrebov** [comment] 2024-01-11 02:11
Looks like duplicate of https://github.com/golang/go/issues/56028

**Closed** 2024-01-11 11:20 UTC
Labels: Proposal
