### ISSUE TITLE
x/tools/gopls: variable in third party package is not highlighted

### ISSUE THREAD

**Issue by normal-cock** [golang/go#43511] opened 2021-01-05 08:53 UTC
### What version of Go are you using (`go version`)?

```
$ go version
go version go1.14 darwin/amd64

$ gopls version
golang.org/x/tools/gopls v0.6.0
    golang.org/x/tools/gopls@v0.6.1 h1:vD171EDBkyUVyp9B45IYXklV/VEfbHgX0FKw0Q0dO30=
```

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
</pre></details>

### What did you do?

nothing

### What did you expect to see?

Code in **my package**:
![image](https://user-images.githubusercontent.com/2618306/93707530-27200c80-fb62-11ea-8176-16fba0e68caa.png)

### What did you see instead?

Code in **third party package**:
![image](https://user-images.githubusercontent.com/2618306/103625359-d77d1980-4f75-11eb-9bc4-816e9b3fd175.png)

Gopls(server) logs when I move cursor in `format` variable:
```
[Trace - 16:51:31.825 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2021/01/05 16:51:31 background refresh finished after 26.412396992s\n"}


[Info  - 4:51:31 PM] 2021/01/05 16:51:31 background refresh finished after 26.412396992s

[Trace - 16:51:35.547 PM] Sending request 'textDocument/hover - (26)'.
Params: {"textDocument":{"uri":"file:///~/.gvm/gos/go1.14/src/fmt/print.go"},"position":{"line":216,"character":15}}


[Trace - 16:51:35.548 PM] Received response 'textDocument/hover - (26)' in 0ms.
Result: {"contents":{"kind":"markdown","value":"```go\nvar format string\n```"},"range":{"start":{"line":216,"character":13},"end":{"line":216,"character":19}}}


[Trace - 16:51:35.749 PM] Sending request 'textDocument/hover - (27)'.
Params: {"textDocument":{"uri":"file:///~/.gvm/gos/go1.14/src/fmt/print.go"},"position":{"line":216,"character":14}}


[Trace - 16:51:35.749 PM] Received response 'textDocument/hover - (27)' in 0ms.
Result: {"contents":{"kind":"markdown","value":"```go\nvar format string\n```"},"range":{"start":{"line":216,"character":13},"end":{"line":216,"character":19}}}


[Trace - 16:51:35.887 PM] Sending request 'textDocument/documentHighlight - (28)'.
Params: {"textDocument":{"uri":"file:///~/.gvm/gos/go1.14/src/fmt/print.go"},"position":{"line":216,"character":15}}


[Trace - 16:51:35.888 PM] Received response 'textDocument/documentHighlight - (28)' in 0ms.
Result: [{"range":{"start":{"line":216,"character":13},"end":{"line":216,"character":19}},"kind":1}]


[Trace - 16:51:36.122 PM] Sending request 'textDocument/codeAction - (29)'.
Params: {"textDocument":{"uri":"file:///~/.gvm/gos/go1.14/src/fmt/print.go"},"range":{"start":{"line":216,"character":15},"end":{"line":216,"character":15}},"context":{"diagnostics":[]}}


[Trace - 16:51:36.126 PM] Received response 'textDocument/codeAction - (29)' in 4ms.
Result: null
```

**Comment by normal-cock** [comment] 2021-01-18 03:44
Will this issue be fixed in `gopls/v1.0.0`? @stamblerre

**Comment by stamblerre** [comment] 2021-01-19 05:34
We are not yet sure when v1.0.0 will be released, but we will address it before that version. When the issue is resolved, it will be closed and moved to the milestone of the release for which it was actually fixed.

**Comment by ShoshinNikita** [comment] 2021-03-29 12:54
I could find the cause of this behavior. [`Highlight()`](https://github.com/golang/tools/blob/4c8e4a8bc6d0eb3d45b7af277237dd820590d310/internal/lsp/source/highlight.go#L21) function calls [`GetParsedFile()`](https://github.com/golang/tools/blob/4c8e4a8bc6d0eb3d45b7af277237dd820590d310/internal/lsp/source/util.go#L78) that requests a package with `TypecheckWorkspace` mode:

```go
// TypecheckFull means to use ParseFull.
TypecheckFull

// TypecheckWorkspace means to use ParseFull for workspace packages, and
// ParseExported for others.
TypecheckWorkspace

...

// ParseExported specifies that the public symbols are needed, but things like
// private symbols and function bodies are not.
// This mode is used for things where a package is being consumed only as a
// dependency.
ParseExported

// ParseFull specifies the full AST is needed.
// This is used for files of direct interest where the entire contents must
// be considered.
ParseFull
```

So, `*ast.File` for std and third-party packages doesn't have function bodies. I can see several options here:

- Use `TypecheckFull` mode in `GetParsedFile()`. As far as I can tell, only `Highlight()` function requires the full AST. So, it is not a good idea
- Pass a typecheck mode to `GetParsedFile`. It will give more control, but the function will become less convenient
- Use a special version of `GetParsedFile()` with `TypecheckFull` mode for `Highlight()`

Related issue: #40809 (cc @heschi)

Side note: `ParseExported` has a misleading name and a comment because `*ast.File` still has unexported symbols. [`trimAST`](https://github.com/golang/tools/blob/4c8e4a8bc6d0eb3d45b7af277237dd820590d310/internal/lsp/cache/parse.go#L337), which is called in this mode, doesn't remove private symbols

**Comment by stamblerre** [comment] 2021-03-29 19:31
Thanks for investigating this! I think it would be fine to reuse the content of GetParsedFile directly in the highlight code--it's not much logic, so I don't think it deserves a second helper. What do you think?

**Closed** 2021-04-05 22:17 UTC
Labels: Tools, gopls
