### ISSUE TITLE
How to expose a function with arguments for WebAssembly wasm generation? 

### ISSUE THREAD

**Issue by thstart** [golang/go#41715] opened 2020-09-30 20:16 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.15.2
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOOS="darw"
</pre></details>

### What did you do?
package main

import "C"

//export Sum
func Sum(a, b int) int {
	return a + b
}

func main() {
	// We need the main function to make possible
	// CGO compiler to compile the package as C shared library
}

### What did you expect to see?

I want to expose the Sum function which accepts arguments in order to use it 
in a non browser environment.

Currently there is no way to do that mucous only main() is exposed.

**Comment by agnivade** [comment] 2020-10-01 04:17
Please see https://github.com/golang/go/issues/25612, https://github.com/golang/go/issues/38248.

I will close this as a duplicate of those issues.

**Closed by agnivade** 2020-10-01 04:17 UTC

**Comment by thstart** [comment] 2020-10-01 04:29
> Please see #25612, #38248.
> 
> I will close this as a duplicate of those issues.

Thank you. I looked at the two links and looks like they are closed. 
Could you please tell me what are the plans?
I have a real case - where to explain it with more details?

**Comment by agnivade** [comment] 2020-10-01 14:16
As of now, it's very difficult to achieve this without a major change as outlined in #38248. I think once wasi support arrives, this will be available.

You are welcome to comment on those issues if you have any suggestions.
