### ISSUE TITLE
cmd/go: go list and rooted paths

### ISSUE THREAD

**Issue by perillo** [golang/go#14177] opened 2016-02-01 19:11 UTC
go help packages says:

```
An import path that is a rooted path or that begins with
a . or .. element is interpreted as a file system path and
denotes the package in that directory.
```

The way I interpret it is that

```
go list /home/manlio/go/github/perillo/goprint
```

should list the goprint package; however go list reports an error:

```
can't load package: package /home/manlio/go/src/github.com/perillo/goprint: import "/home/manlio/go/src/github.com/perillo/goprint": cannot import absolute path
```

**Comment by robpike** [comment] 2016-02-01 20:37
I don't think the problem is wordsmithing, it's that the go tool doesn't accept absolute paths.

**Comment by adg** [comment] 2016-02-08 04:29
Yeah agree, it's a go tool bug.

**Comment by yaegashi** [comment] 2016-04-17 23:28
I'm searching for the reason why [go tool doesn't accept absolute (rooted?) import paths](https://github.com/golang/go/blob/release-branch.go1.6/src/go/build/build.go#L564).  So far I couldn't find any rationale for that behavior, and just found this issue.  Is this actually a bug of go tool?  It affects other actions like install, build, etc.

```
$ tree $GOPATH
/home/yaegashi/go
└── src
    └── hello
        └── hello.go

2 directories, 1 file
$ cd $GOPATH
$ rm -rf bin && go install -v ./src/hello             
hello
$ rm -rf bin && go install -v ./src/...
hello
$ rm -rf bin && go install -v $GOPATH/src/hello
can't load package: package /home/yaegashi/go/src/hello: import "/home/yaegashi/go/src/hello": cannot import absolute path
$ rm -rf bin && go install -v $GOPATH/src/...
warning: "/home/yaegashi/go/src/..." matched no packages
```

**Comment by adg** [comment] 2016-04-18 05:34
Well, import declarations in files cannot use rooted paths, and the go tool takes import paths on the command line, so that is at least consistent.

**Comment by jeffreydwalter** [comment] 2017-08-07 19:59
Is this going to get fixed? 

```
$ go list ./src/blah/pkg/...
blah/pkg/test0
blah/pkg/test1
blah/pkg/test2

🍺  [673] jeff_walter@Thunderbolt:~/Code/stash/agent
$ go list src/blah/pkg/...
warning: "src/blah/pkg/..." matched no packages
```
kinda sucks.

**Comment by ianlancetaylor** [comment] 2017-08-07 23:28
@jeffreydwalter I think that is a different problem.  `go list` will look for packages in `GOPATH` unless explicitly told otherwise.

**Comment by jeffreydwalter** [comment] 2017-08-08 01:19
@ianlancetaylor, I don't really follow.

How does `$GOPATH` come into play in my example?

./foo/... is a relative path, just like foo/..., isn't it? I assume the issue is that the path that starts with . is being treated as a relative path and the one without is not, but that seems wrong to me.

`ls ./foo/` and `ls foo/` are functionally equivalent (both relative paths) in shell parlance, I guess I expect that `go list` would treat them the same.

**Comment by dominikh** [comment] 2017-08-08 04:19
`go` is not `ls`. The arguments to `go list` are package paths, which may be relative (starting with a `./`), or absolute. Absolute paths are looked up in GOPATH. Package paths are not POSIX paths.

**Comment by jeffreydwalter** [comment] 2017-08-08 17:13
@dominikh, thanks for the explanation. I just read the `go help packages` documentation and what you're saying now makes sense, although I'd still argue that the `go help list` and `go list` documentation should make it more clear, instead of burying it in `go help packages`.

**Comment by matloob** [comment] 2018-07-30 16:36
cc @bcmills 

I vote for fixing this rather than changing the documentation. My conception of go list is not that it takes package paths on the command line, but patterns that resolve to package paths. For instance, ./foo/... is not a package path but a pattern that resolves to all the subpackages of foo. Similarly, in my model at least, an absolute path should resolve to the package in the given directory.

Of course that package should either be contained in GOPATH, GOROOT, or in the transitive set of modules depended on by the current module.

**Comment by matloob** [comment] 2018-07-30 16:37
cc @suzmue Thanks!

**Comment by rsc** [comment] 2018-07-31 03:08
Fixed by golang.org/cl/126715.

**Closed** 2018-08-01 00:36 UTC
Labels: Documentation
