### ISSUE TITLE
filepath.Abs returns different values when passed "." 

### ISSUE THREAD

**Issue by hbt** [golang/go#41670] opened 2020-09-28 10:34 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version go version go1.14.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/hassen/.cache/go-build"
GOENV="/home/hassen/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/hassen/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/hassen/goroot"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/hassen/goroot/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build324432177=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

calling `filepath.Abs` returns different values based on whether the program is ran in terminal or in CI/CD system because it sometimes uses Getenv("PWD") OR does syscall.Getwd

https://play.golang.org/p/lvU1dF0dFcE

### What did you expect to see?

I expect the filepath.Abs to return the same value and be consistent and either always call syscall.Getwd or always use PWD

### What did you see instead?

Different values. View https://play.golang.org/p/lvU1dF0dFcE example

**Comment by ianlancetaylor** [comment] 2020-09-28 23:24
The way it works is that if the environment variable `PWD` is set, and it names the same directory as the current directory, then we use the value in `PWD`.  This generally gives a better result when using a Unix shell.  If `PWD` is not set, then we call the `getcwd` system call.  If you need some sort of canonicalized path that is independent of `PWD`, use `filepath.EvalSymlinks`.

Closing because this is working as intended.

**Closed by ianlancetaylor** 2020-09-28 23:24 UTC

**Comment by hbt** [comment] 2020-09-28 23:54
I already worked around it by evaluating the symlinks but I wouldn't call this "working as intended."

having the api rely on both `PWD` and `getcwd` is wrong. 
`os.Chdir` doesn't change `PWD` and vice-versa. Which is fine.

The API should pick one lookup method though.

Instead we had a program that passes the test suite but failed in production because the golang API used the PWD environment variable in production and `getcwd` in the test suite.

**Comment by ianlancetaylor** [comment] 2020-09-28 23:59
I don't agree that there is an obvious right answer here.  The approach that Go takes is the one that most Unix shells take, and it produces appropriate results when a user uses `cd` to get to a directory and then runs a Go program that uses that directory.
