### ISSUE TITLE
go/get: archive does not contain symlinks

### ISSUE THREAD

**Issue by wojciech-sneller** [golang/go#58626] opened 2023-02-21 21:21 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

First of all, I'm not sure if it's a correct place to submit the issue, feel free to move it/redirect to the proper project.

In our project we use symlinks in a few places:

```bash
~/github$ git clone https://github.com/SnellerInc/sneller.git
Cloning into 'sneller'...
...
~/github$ find sneller/ -type l
sneller/vm/bc_constant.h
sneller/vm/avx512.h
sneller/vm/bc_imm_amd64.h
```

When the project is pulled via dependencies, these links are
not present. This simple package is sufficient to reproduce
the problem locally:

```
$ cat go.mod
module main

go 1.20

require (
    github.com/SnellerInc/sneller v0.0.0-20230125001655-1dc041dde43b
)

$ cat main.go
package main

import (
    "fmt"
    "github.com/SnellerInc/sneller/vm"
)

func main() { fmt.Printf("vm.PageSize = %d\n", vm.PageSize) }
```

During compilation we'll see the error:

```
$ go build
# github.com/SnellerInc/sneller/sorting
../go/pkg/mod/github.com/!sneller!inc/sneller@v0.0.0-20230125001655-1dc041dde43b/sorting/counting_sort.s:18: #include: open /usr/local/go/pkg/vm/bc_imm_amd64.h: no such file or directory
```

I checked that the archive file downloaded by `go get` does not
contain the link, only the linked file:

```
~$ unzip -l ~/go/pkg/mod/cache/download/github.com/\!sneller\!inc/sneller/\@v/v0.0.0-20230125001655-1dc041dde43b.zip | grep bc_imm
     5452  1980-00-00 00:00   github.com/SnellerInc/sneller@v0.0.0-20230125001655-1dc041dde43b/internal/asmutils/bc_imm_amd64.h
```

For comparison, the archive downloaded directly from github contains
both --  the file and the link:

```
~$ unzip -l ~/sneller-master.zip | grep bc_imm
     5452  2023-01-25 01:16   sneller-master/internal/asmutils/bc_imm_amd64.h
       35  2023-01-25 01:16   sneller-master/vm/bc_imm_amd64.h
```

**Comment by seankhliao** [comment] 2023-02-22 02:09
Duplicate of #44482

**Closed by seankhliao** 2023-02-22 02:09 UTC
