### ISSUE TITLE
my primary key is bigint but sql.LastInsertId return int64

### ISSUE THREAD

**Issue by smithyj** [golang/go#52118] opened 2022-04-02 17:35 UTC
https://github.com/golang/go/blob/8a816d5efcc842ae92f0193aa9c1d433bd66ef31/src/database/sql/driver/driver.go#L527

my primary key is `unsigned bigint` but `sql.LastInsertId()` return `int64`, should be return `uint64`

**Comment by seankhliao** [comment] 2022-04-02 17:38
Duplicate of #19055

**Closed by seankhliao** 2022-04-02 17:38 UTC
