### ISSUE TITLE
HTTP Request dont follow 301 redirection correctly

### ISSUE THREAD

**Issue by kxcode** [golang/go#46834] opened 2021-06-20 04:02 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_y/p_9gwggn59z5y1r2f9pcjwl00000gn/T/go-build1205067775=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
myresp, e2 := http.Get("http://facebook.com:80/")
if e!=nil{
    fmt.Println(e.Error())
}else{
    bytes,_ := ioutil.ReadAll(myresp.Body)
    fmt.Println(string(bytes))
}

myresp2, e2 := http.Get("http://facebook.com/")
if e2!=nil{
    fmt.Println(e2.Error())
}else{
    bytes2,_ := ioutil.ReadAll(myresp2.Body)
    fmt.Println(string(bytes2))
}
```

### What did you expect to see?

facebook.com on port 80 response a 301 redirection to https://facebook.com/
golang should follow to https://facebook.com/

### What did you see instead?

if we requests http://facebook.com:80/
golang followed to https://facebook.com:80/ not correctly

if we requests to http://facebook.com/
golang followed to https://facebook.com/ correctly

**Comment by seankhliao** [comment] 2021-06-20 09:39
This is facebook returning an invalid `Location` header:

```
» nc facebook.com 80
GET / HTTP/1.1
Host: facebook.com:80

HTTP/1.1 301 Moved Permanently
Location: https://facebook.com:80/
Content-Type: text/html; charset="utf-8"
X-FB-Debug: neNf+egzn8Oz9wA5M1ZeWqKYbEgoG8lBQxwZQlZtOViDbvzwbsvJ1gEjCh+NET8OZu6KouLOS2I9BQ0en1J5vA==
Date: Sun, 20 Jun 2021 09:37:51 GMT
Priority: u=3,i
Alt-Svc: h3-29=":443"; ma=3600,h3-27=":443"; ma=3600
Connection: keep-alive
Content-Length: 0

^C
```

Closing as it's not a bug in Go

**Closed by seankhliao** 2021-06-20 09:39 UTC
