### ISSUE TITLE
time: RFC3339 format parsing is both too lax and too strict

### ISSUE THREAD

**Issue by oschwald** [golang/go#20869] opened 2017-06-30 20:17 UTC
As of Go 1.8.3, the RFC3339 format has several inconsistencies with the actual RFC when parsing a string:

1. One digit hours are incorrectly allowed, e.g., `2017-04-09T0:38:00.00Z`. I assume this is because there is no `stdZeroHour` similar to `stdZeroHour12` ("03").
2. The format is case sensitive. The RFC says:

>       NOTE: Per [ABNF] and ISO8601, the "T" and "Z" characters in this
>      syntax may alternatively be lower case "t" or "z" respectively.
>
>      This date/time format may be used in some environments or contexts
>      that distinguish between the upper- and lower-case letters 'A'-'Z'
>      and 'a'-'z' (e.g. XML).  Specifications that use this format in
>      such environments MAY further limit the date/time syntax so that
>      the letters 'T' and 'Z' used in the date/time syntax must always
>      be upper case.  Applications that generate this format SHOULD use
>      upper case letters.

Also, it does not parse leap seconds, which are explicitly allowed under the standard, but that seems more like an intentional design decision.

In reporting this, I am assuming the omission of RFC3339 from the comment:

> RFC822, RFC822Z, RFC1123, and RFC1123Z are useful for formatting; when used with time.Parse they do not accept all the time formats permitted by the RFCs.

suggests that you should be able to parse all time formats permitted by it.

**Comment by kennygrant** [comment] 2017-10-29 10:15
See also #11128

**Comment by rsc** [comment] 2017-11-22 03:47
Given that generators should generate T and Z, not t and z, I'm not particularly inclined to try to fix this.

**Comment by seankhliao** [comment] 2022-11-15 19:50
Duplicate of #54580

**Closed by seankhliao** 2022-11-15 19:50 UTC
Labels: NeedsInvestigation
