### ISSUE TITLE
x/tools/gopls: incorrect placeholders for aliased types

### ISSUE THREAD

**Issue by ChrisHines** [golang/go#33500] opened 2019-08-06 20:34 UTC
### What version of Go are you using (`go version`)?

<pre>
golang.org/x/tools/gopls v0.1.3
    golang.org/x/tools/gopls@v0.1.4-0.20190806194950-6743d4095d4b h1:2RQrzcrEYVmfqqLlivm/WQAKgrN3esjyGgkI4UhN/a0=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20190723021737-8bb11ff117ca h1:SqwJrz6xPBlCUltcEHz2/p01HRPR+VGD+aYLikk8uas=

Go info
-------
go version go1.12.7 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/chines209/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/chines209/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zs/qv8flyxx1zl_nmdkklb5p15sz6zd1t/T/go-build867357531=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

I declared a function type struct field. The function has a parameter and return value with a type that is an exported alias of a type in an internal package my code doesn't have access to. For example:

```go
import "golang.org/x/net/ipv4"

type mockAppender struct {
	appendMessages func(now time.Time, ms []ipv4.Message) ([]ipv4.Message, bool)
	stopped        func()
}
```

I then declare type literals for `mockAppender` in VSCode with the `gopls.usePlaceholders` option enabled.

### What did you expect to see?

When I type a struct literal for the above type and add the `appendMessages` field, I expect the generated placeholder to reference types my code has access to, specifically:

```go
ma := mockAppender{
	appendMessages: // placeholder -> func(now time.Time, ms []ipv4.Message) ([]ipv4.Message, bool, StepTime),
}
```

### What did you see instead?

A placeholder that referenced types from a package my code cannot import that is type that `ipv4.Message` aliases. Specifically:

```go
ma := mockAppender{
	appendMessages: // placeholder -> func(now time.Time, ms []socket.Message) ([]socket.Message, bool, StepTime),
}
```

**Comment by stamblerre** [comment] 2019-08-08 21:11
Thanks for filing this issue! This is lower priority for us, so while I will try to fix this when I get a chance, if anyone else is interested in contributing a fix for this, please go ahead!

**Comment by wangfenjin** [comment] 2019-10-15 09:48
Hi @stamblerre ,

I'm interested to look into this issue.

I think the problem is related to types.TypeString() function in this line [completion_format.go](https://github.com/golang/tools/blob/18e3458ac98b4126ac324c8056a0f2d826c6688a/internal/lsp/source/completion_format.go#L35)

Am I in the right direction? Thanks.

**Comment by stamblerre** [comment] 2019-10-15 16:55
@wangfenjin: The placeholders for a function are actually determined in the `functionCallSnippet` function in [completion_snippet.go](https://github.com/golang/tools/blob/18e3458ac98b4126ac324c8056a0f2d826c6688a/internal/lsp/source/completion_snippet.go#L56). I would suggest getting started here by adding a test case and running the `gopls` tests. Examples of the completion snippet tests can be found [here](https://github.com/golang/tools/blob/18e3458ac98b4126ac324c8056a0f2d826c6688a/internal/lsp/testdata/snippets/snippets.go.in).

**Comment by wangfenjin** [comment] 2019-10-16 05:50
Hi @stamblerre ,

After some investment, I find it's a placeholder for struct field which determined by [structFieldSnippet](https://github.com/golang/tools/blob/18e3458ac98b4126ac324c8056a0f2d826c6688a/internal/lsp/source/completion_snippet.go#L14), which in turn relies on types.TypeString(). I think I should fix this in golang/go package.

**Comment by wangfenjin** [comment] 2019-10-16 09:12
Hi @stamblerre ,

Seems it's intended to return the underlining type for alias, please refer to [types/decl.go](https://github.com/golang/go/blob/03bb3e9ad13ef49afbed7e422d21ef6eb00389c1/src/go/types/decl.go#L532). I think we can't change the logic here.

Do you have any suggestions?

**Comment by stamblerre** [comment] 2019-10-16 17:09
Ah I see, thanks for investigating this. Looks like there's no way for us to to get back the alias information from the `go/types` package. An alternative solution would be for us to always use the file's AST when constructing the placeholders. That would mean replacing the logic that uses `types.TypeString`. This would be similar to the logic that gets the item's documentation (see https://github.com/golang/tools/blob/9c6d90b5a7d0c5de88404edf63ae60750868bf0a/internal/lsp/source/completion_format.go#L119).

**Closed** 2019-11-25 01:12 UTC
Labels: gopls, help wanted
