### ISSUE TITLE
runtime: finalizer did not run

### ISSUE THREAD

**Issue by cherrymui** [golang/go#19805] opened 2017-03-31 12:46 UTC
After CL https://go-review.googlesource.com/c/37520/ checked in, there are a couple of failures on the build dashboard. The failures are mostly related to finalizers, but may also include others like wrong number of goroutines. For example:
```
--- FAIL: TestStackGrowth (20.69s)
	stack_test.go:114: finalizer did not run
--- FAIL: TestEmptySlice (4.06s)
	mfinal_test.go:185: finalizer of next object in memory didn't run
--- FAIL: TestEmptyString (4.06s)
	mfinal_test.go:217: finalizer of next string in memory didn't run
--- FAIL: TestNumGoroutine (0.05s)
	proc_test.go:382: NumGoroutine=10, but found 11 goroutines in stack dump: goroutine 127528 [running]:
```

The failure is sporadic.

linux-mips64le:
https://build.golang.org/log/0b5c6130c6b1662e36a7956577ec677c1b80d7d4
https://build.golang.org/log/bbd7a380874739987ab10150d325ba55123f0ad6
freebsd-arm:
https://build.golang.org/log/e06e99f7bb6d15834d3ced9cd62f490666a3531a
https://build.golang.org/log/2c63f9ced656ef095edabe6178298749fbac5cd1
plan9-386:
https://build.golang.org/log/c69f2dd74ebf3c7a571ca902bb66fde0f9a4bb81

The linux-mips64le builder is single core. I wonder whether the other two builders are also single core. Not sure whether this is related.

cc @aclements

**Comment by aclements** [comment] 2017-03-31 15:37
I think freebsd-arm is unrelated to CL 37520. It's been failing pretty regularly since mid-January (fdde7ba).

The other two look real. My hunch is that TestNumGoroutine is a cascade from the others. I don't have a hunch why the first three are failing.

No luck so far reproducing with `GOMAXPROCS=2 numactl -C 0 stress -p 1 ./runtime.test -test.cpu=1,2,4 -test.short` on linux/amd64. @cherrymui, is there a way I can access the linux/mips64le machine?

**Comment by cherrymui** [comment] 2017-03-31 16:40
@aclements, unfortunately my home router's port forwarding stopped working a few months ago... Maybe I can bring the machine on Monday. Let me know if any command I can try locally in the meantime.

**Comment by aclements** [comment] 2017-03-31 19:21
@cherrymui, it would be useful if you could run `GOMAXPROCS=2 numactl -C 0 stress -p 1 ./runtime.test -test.cpu=1,2,4 -test.short` just to see if that reproduces it. If it does, I can put together some debug patches.

**Comment by cherrymui** [comment] 2017-03-31 19:35
Ok, I'll try it this evening.

**Comment by benshi001** [comment] 2017-04-24 09:47
This bug also rises randomly on my raspberry pi 2. I have to set
line 114 of src/runtime/stack_test.go from
case <-time.After(20 * time.Second):
to
case <-time.After(30 * time.Second):

to avoid it.

**Comment by eliasnaur** [comment] 2017-04-27 18:32
This one happens frequently on the android/arm builder:

https://build.golang.org/log/c22a2ed235e51df8991d0439881eb626d8053ec9

I can reproduce it fairly quickly with

GOOS=android GOARCH=arm go test -short -cpu=1,2,4 runtime

is there anything I can do to help?

**Comment by eliasnaur** [comment] 2017-04-27 18:59
Increasing the timeout in stack_test.go:114 to 30 seconds or checking out 44ed88a5a768a54c1880c58f3438bf2fa8639c4c (the parent of CL 37520) both make the problem go away.

**Comment by aclements** [comment] 2017-06-08 16:00
Closing as a dup of #19381. (But there's useful discussion here, which I've linked to and summarized from that issue.)

**Closed by aclements** 2017-06-08 16:00 UTC
Labels: NeedsFix, Testing
