### ISSUE TITLE
Support Generic Method in Non-Generic Struct

### ISSUE THREAD

**Issue by mehdihadeli** [golang/go#55917] opened 2022-09-28 10:25 UTC
Hi,
Please consider adding `generic method` to the `non-generic struct`. This feature is convenient for developing flexible struct methods.
So many languages like C# and Java have had this feature for a long time and I think it is handy.

**Comment by D1CED** [comment] 2022-09-28 15:16
This is a more limited version of #49085. So, Dup?

**Comment by seankhliao** [comment] 2022-09-28 16:19
Duplicate of #49085

**Closed by seankhliao** 2022-09-28 16:19 UTC
Labels: NeedsInvestigation, FeatureRequest, generics
