### ISSUE TITLE
usechain 

### ISSUE THREAD

**Issue by akashjain96** [golang/go#28862] opened 2018-11-19 06:30 UTC
I am trying to build use chain but having link.exe issue ,
Can anyone help me with it?

**Comment by akashjain96** [comment] 2018-11-19 06:31
![image](https://user-images.githubusercontent.com/43955371/48689989-c84e7c80-ebf2-11e8-9980-d1eea9083093.png)
this is the screenshot

**Comment by agnivade** [comment] 2018-11-19 06:33
Hi @akashjain96,

This does not seem to be an issue with Go, rather possibly with the usechain library.

In any case, we do not use the issue tracker for general discussions or questions like these. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

You might want to take a look at the [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.

Closing since this is not a bug.

**Closed by agnivade** 2018-11-19 06:33 UTC

**Comment by akashjain96** [comment] 2018-11-19 06:39
okay @agnivade 
thank you
