### ISSUE TITLE
runtime: update SetFinalizer docs to cover cases of package level data

### ISSUE THREAD

**Issue by yaxinlx** [golang/go#17311] opened 2016-10-01 19:19 UTC
### What version of Go are you using (`go version`)?

go1.7.1 linux/amd64

### What did you see instead?

see this discussion for details: https://groups.google.com/forum/#!topic/golang-dev/JAgv8kBTgk4

summary: 
1. in the latest implementation, there is not restrictions for the argument obj.
2. the docs should present that calling SetFinalizer for a package level data is meaningless.

**Comment by minux** [comment] 2016-10-01 23:40
The existing docs is fine as is.

"The argument obj must be a pointer to an object allocated by
calling new, by taking the address of a composite literal, or by
taking the address of a local variable."

This means no other pointers are accepted, which includes
package level variables.

**Comment by yaxinlx** [comment] 2016-10-02 02:50
@minux, "This means no other pointers are accepted, which includes package level variables."
This is not the fact.

**Comment by minux** [comment] 2016-10-02 03:18
You confused the differences between documented behavior
and actual implemented behavior.

The documented behavior is almost always a strict subset of
actual implemented behavior, i.e. the code implements some
unspecified behavior. In general it's not wise to depend on
those unspecified behaviors.

For this particular case, the documentation says you can't use
package level variables, but the implementation doesn't enforce
this, so you can actually set finalizer on package level variables,
but as this is not documented to be valid, it's not guaranteed to
stay valid for future Go versions.

The current docs is the correct one, and there is no need to
complicate it further (esp. the current docs already enumerates
all valid cases, there is no need to explicitly say excluded cases
are invalid).

**Comment by yaxinlx** [comment] 2016-10-02 03:37
But if the document doesn't forbid package level pointers to objects allocated by calling new and by taking the address of composite literals, why it forbids general package level pointers?

**Comment by yaxinlx** [comment] 2016-10-02 03:46
If the document has no problems, can I file an issue for the compiler implementation?
After all, older compiler versions will create panic when argument obj is a pointer to package level data.

Whatever, the docs for SetFinalizer should be more detailed.

**Comment by minux** [comment] 2016-10-02 04:00
I tried some of the previous releases for setting finalizer on
package level variable. OK means no panic.

go version go1
runtime.SetFinalizer: pointer not at beginning of allocated block
go version go1.1.2 linux/amd64
runtime.SetFinalizer: pointer not at beginning of allocated block
go version go1.2.1 linux/amd64
runtime.SetFinalizer: pointer not at beginning of allocated block
go version go1.2.2 linux/amd64
runtime.SetFinalizer: pointer not at beginning of allocated block
go version go1.3 linux/amd64
OK
go version go1.3.3 linux/amd64
OK
go version go1.4 linux/amd64
OK
go version go1.4.1 linux/amd64
OK
go version go1.4.3 linux/amd64
OK
go version go1.5 linux/amd64
OK
go version go1.5.3 linux/amd64
OK
go version go1.6 linux/amd64
OK
go version go1.7.1 linux/amd64
OK

As you can see, this is not regression. The previous panic is actually
not because it's checking that the pointer is not on heap, it's because
it fails to find the beginning of allocated object on the heap. I don't
think we need to change the runtime to panic now as it used to panic
only by coincidence and the panic doesn't explain the real reason
anyway.

**Comment by yaxinlx** [comment] 2016-10-02 04:15
Good explanation, ok, I don't insist on change the docs any more.
But I think put a warning to using pointers to package level data in docs will be perfect.

**Comment by aclements** [comment] 2016-10-03 15:51
There is a slight bug in the documentation. As written, it technically guarantees that SetFinalizer will panic if passed a pointer to a package-level variable. That clearly isn't the case. In fact, this claim is nonsense even if you ignore package-level variables, since we can't tell the difference between passing, say, a pointer to a composite literal and a pointer to its first element. So we should change this to say that it "*may* abort the program."

However, I'm inclined to change the *guarantee* here as well (and also the docs) to accept pointers to package-level variables just to simplify the API and its specification. I can't see how this would unduly constrain future implementations. @RLH?

**Comment by quentinmit** [comment] 2016-10-11 21:29
@aclements @RLH Can we close this issue now?

**Comment by aclements** [comment] 2016-10-12 18:44
@RLH and I chatted about whether to guarantee that SetFinalizer won't panic if passed a package-level variable. Neither of us have strong feelings about this either way, but the existing non-guarantee is more permissive for the implementation of finalizers and lets us change our minds later if there's more evidence. Further, it's important in general that SetFinalizer only be called for the beginning of an object, but we can't check that for package-level data, so we're leaning towards not trying to make any guarantees about pointers to package-level variables.

Hence, we're going to leave the documentation alone unless there's more compelling evidence for specifying this than the documentation being more restrictive than the implementation.

**Closed by aclements** 2016-10-12 18:44 UTC
Labels: Documentation, NeedsFix

**Comment by yaxinlx** [comment] 2016-10-13 07:37
@aclements, @RLH, 

the original title of this issue is "Make the SetFinalizer docs perfect".
I just feel the docs is some verbose.

For example, in the tip version, the docs says:

> The argument obj must be a pointer to an object allocated by calling
> new, by taking the address of a composite literal, or by taking the
> address of a local variable.

So I think the following SetFinalizer callings for a, b, c will be always safe in later go versions:

	package main

	import (
		"runtime"
	)

	func callback1(*[]int) {}
	func callback2(*int) {}

	var a = &[]int{}
	var b = new(int)

	func main() {
		v := 123
		c := &v
		
		runtime.SetFinalizer(a, callback1)
		runtime.SetFinalizer(b, callback2)
		runtime.SetFinalizer(c, callback2)
		
		// ...
		
		// ....
	}

However, the docs then says this:

> It is not guaranteed that a finalizer will run for objects allocated
> in initializers for package-level variables. Such objects may be
> linker-allocated, not heap-allocated.

Now, I can't confirm if the SetFinalizer callings for a, b will be always safe or not.

**Comment by aclements** [comment] 2016-10-13 16:06
@yaxinlx, maybe I don't understand what you mean by SetFinalizer being "safe". To me, SetFinalizer is "safe" in situations it guarantees won't panic. But your second quote from the documentation doesn't say anything about SetFinalizer panicking. It just says the finalizer may not run for a or b (which is true in general, since finalizers are *never* guaranteed to be run).

**Comment by yaxinlx** [comment] 2016-10-14 03:11
The complaint for the docs is I don't understand what the "must" mean in the first quote.
"must be xxx to possibly trigger a finalizer calling", "must be xxx to avoid paniking in later go versions"?

Thanks for your explanation. By your explanation, I think "must" means "must be xxx to avoid paniking in later go versions".

**Comment by aclements** [comment] 2016-10-14 14:13
> The complaint for the docs is I don't understand what the "must" mean in the first quote.
"must be xxx to possibly trigger a finalizer calling", "must be xxx to avoid paniking in later go versions"?

Either may be true. The point is that this is an intentionally *underspecified* contract between SetFinalizer and the caller of SetFinalizer. "The argument obj must be a pointer to an object allocated by calling new, by taking the address of a composite literal, or by taking the address of a local variable." means it's the caller's responsibility to pass an obj that satisfies these requirements. If the caller does something else, the behavior of SetFinalizer is *unspecified*. It may panic (a possibility suggested by the last sentence in that paragraph). It may do nothing (in which case the finalizer will never run). It may reboot your computer (though that would be rude). Who knows? And, as you point out, it may behave differently in other versions of Go or other implementations of Go (e.g., gccgo, GopherJS).
