### ISSUE TITLE
net/http: test spams stderr

### ISSUE THREAD

**Issue by bradfitz** [golang/go#24831] opened 2018-04-12 17:10 UTC
Running `go test` on a package should be quiet and not spam to stderr.

But:

```
$ go test -short
2018/04/12 17:09:17 http: WriteHeader called with X-Content-Type-Options:nosniff but no Content-Type
2018/04/12 17:09:17 http: TLS handshake error from 127.0.0.1:55706: remote error: tls: bad certificate
PASS
ok      net/http        4.034s
```

The first log line was added in 1a677e03c827b7b1ab2008be2a8f340fb072531c (/cc mikesamuel).

I haven't looked into the second.

Help fixing these would be great. Thanks!

**Comment by odeke-em** [comment] 2018-04-12 19:49
Thank you for this report @bradfitz 

For further investigation, I'll kindly page:
1) /cc @mikesamuel -- @bradfitz you forgot the @ :)
2) Looks like a regression from c529141d72d83d563a9cf5cdf366dc9b6993121e /cc @mikedanese @FiloSottile @agl

**Comment by mikesamuel** [comment] 2018-04-12 19:57
Sorry.  The first one's my fault.  I'll look into it.  The second looks unlikely to be caused by what I did to cause the first.

**Comment by odeke-em** [comment] 2018-04-12 20:01
@mikesamuel no worries :) In deed, the second one was caused by a different commit
> Looks like a regression from c529141 /cc @mikedanese @FiloSottile @agl

**Comment by mikedanese** [comment] 2018-04-13 17:54
Haven't looked deeply into this yet. @odeke-em can you give me a hint on what lead you to https://github.com/golang/go/commit/c529141d72d83d563a9cf5cdf366dc9b6993121e?

**Comment by odeke-em** [comment] 2018-04-16 23:48
Sorry for the late reply @mikedanese, I've been travelling and was away from my computer for a bit. I went through the history https://github.com/golang/go/commits/master/src/crypto and commits before and after yours after some bisection using some hacked up bash script to do binary searches, recompile the Go tree and then find regressions(but it isn't yet complete so not yet releasing it ;))

@mikedanese you can try to confirm it yourself, the commit before yours 8a1519249fb482c9ae0831913d7a963e052cb97a  didn't produce that result but yours c529141d72d83d563a9cf5cdf366dc9b6993121e did and so did the commit after yours 0b37f05d8dc17a52a9ac1fc827075cd36fe977bb
<img width="1080" alt="screen shot 2018-04-16 at 7 45 57 pm" src="https://user-images.githubusercontent.com/4898263/38840720-040b5a8e-41af-11e8-852f-1a4f05458d2d.png">

**Comment by mikedanese** [comment] 2018-04-17 00:41
From my previous comment, I've ruled out https://github.com/golang/go/commit/c529141d72d83d563a9cf5cdf366dc9b6993121e. You can confirm this by reverting that change, running tests, and still seeing the error output. The test added in https://github.com/golang/go/commit/2638001e12fe91736c6872cdd818fecc36d98c5e is creating the output, and has been creating the output since it was merged.

**Comment by odeke-em** [comment] 2018-04-17 02:44
@mikedanese thank you for the thorough investigation, I was just following changes in `crypto`, my apologies for the spurious git blame.

In that case /cc @pquerna and @FiloSottile.

**Closed** 2018-04-18 18:02 UTC
Labels: NeedsFix, Testing
