### ISSUE TITLE
runtime/cgo: error: implicit declaration of function 'setresuid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

### ISSUE THREAD

**Issue by aohanhongzhi** [golang/go#49341] opened 2021-11-04 07:34 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.17.1 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

no
![image](https://user-images.githubusercontent.com/37319319/140273939-7d4f5b9a-680d-4d74-a4fb-f41e196d525c.png)

![image](https://user-images.githubusercontent.com/37319319/140274176-2cfcc982-8be5-49ae-b3e1-79e314ace562.png)

![image](https://user-images.githubusercontent.com/37319319/140274234-94b1dee3-7b04-4da2-9a05-d990e6a6e9a5.png)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

go version go1.17.1 darwin/amd64
eric@mbp1990 Open-IM-Server % go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/eric/Library/Caches/go-build"
GOENV="/Users/eric/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/eric/Project/Go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/eric/Project/Go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/opt/eric/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/eric/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/eric/Project/Go/Open-IM-Server/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t3/zwgjqd4s4p557rcrzl_834hr0000gp/T/go-build3631056783=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

build a project  with its script 

https://github.com/OpenIMSDK/Open-IM-Server.git

![image](https://user-images.githubusercontent.com/37319319/140274383-4f8d03e9-ce12-447c-85aa-2e1085fb484b.png)

### What did you expect to see?

build success

### What did you see instead?

no

**Comment by aohanhongzhi** [comment] 2021-11-04 07:35
![image](https://user-images.githubusercontent.com/37319319/140274664-d7f322a0-82f4-48e9-9621-d57edfd223eb.png)

**Comment by seankhliao** [comment] 2021-11-04 12:24
This looks like an error in the build script only supporting linux. For CGo a proper C toolchain needs to be setup for cross compilation.

Closing as not a bug in Go

**Closed by seankhliao** 2021-11-04 12:24 UTC
Labels: NeedsInvestigation
