### ISSUE TITLE
cmd/go: unclear when packages have missing test coverage with 1.22

### ISSUE THREAD

**Issue by rashokkumartce** [golang/go#65262] opened 2024-01-24 17:57 UTC
### Go version

go1.22rc1 darwin/amd64

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

Created a go file with a couple of interfaces with some method signatures and a variable declaration only

### What did you see happen?

[no test files]

### What did you expect to see?

coverage: 0.0% of statements

**Comment by Jorropo** [comment] 2024-01-24 18:25
Can you show the output of `tree` in your project ?

**Comment by rashokkumartce** [comment] 2024-01-25 07:15
[Go1.22_Issues.docx](https://github.com/golang/go/files/14047993/Go1.22_Issues.docx)
Please check the file for the detailed information

**Comment by mvdan** [comment] 2024-01-25 11:38
A word document is not a good way to show what you're doing.

Did you try to search past issues about this? For example https://github.com/golang/go/issues/24570, but in particular https://github.com/golang/go/issues/25492. It seems to me like this is working as expected.

I'm going to close this as a duplicate of https://github.com/golang/go/issues/25492 for now.

**Comment by mvdan** [comment] 2024-01-25 14:53
That seems to be from https://go-review.googlesource.com/c/go/+/495447, which is for https://github.com/golang/go/issues/24570, one of the earlier issues I linked. This seems to be working as intended; the author here doesn't mention any declared functions with bodies, so there aren't any lines to be covered. Although it's hard to tell because they haven't been very clear about what they are actually doing.

cc @thanm, perhaps the release notes should be made clearer. I'll reopen the issue for that purpose.

**Comment by ChrisHines** [comment] 2024-01-25 14:57
The end result may turn out to be working-as-intended, but we weren't sure.

**Comment by rashokkumartce** [comment] 2024-01-29 11:30
Here is the sample code that is giving the [no test files] as coverage result

```
sampleInterface.go

package main

import "sync"

type shape interface {
	area(wc *sync.WaitGroup)
	volume()
}

var x = 4
```


Upon executing the following command
`$ go test -count=1 -coverprofile cover.out` 
and i'm getting the following result printed
`?       mydomain.com    [no test files]`

The package just contains the interface and we are trying to execute the command against the package, we are getting the above said result
[sampleinterface.go.zip](https://github.com/golang/go/files/14083684/sampleinterface.go.zip)

**Comment by thanm** [comment] 2024-02-05 16:56
@rashokkumartce thanks for posting the code in question.

As @mvdan mentioned earlier, this Go file doesn't contain any executable statements, so we can't really meaningfully express a code coverage percentage for it.   Code coverage is (at some abstract level)  N / M, where N is the number of statement lines executed when the tests are run, and M is the number of statement lines defined.  For this case M is zero, which renders the N/M ration invalid.

If were were to report "mymod/mypack coverage: 0.0% of statements" for this package, this would imply (incorrectly) that the package does contain some executable code and the tests for the package don't trigger the execution of that code, which is definitely not the case for this package.

I'll send a CL to tweak the release notes.

**Closed** 2024-02-06 16:00 UTC
Labels: Documentation, NeedsFix
