### ISSUE TITLE
cmd/pprof: wsl cpu profiles are empty

### ISSUE THREAD

**Issue by stevenh** [golang/go#32824] opened 2019-06-28 08:00 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN="/data/go/bin"
GOCACHE="/home/steveh/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/data/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/steveh/go-redis-proxy/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build093919717=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Ran benchmarks to get cpu profiles:
<pre>
go test -cpuprofile cpu.prof -bench .
go tool pprof cpu.prof
</pre>

### What did you expect to see?
A non empty profile

### What did you see instead?
An empty profile or at an error if the profile failed.

Running the exact same test on a BSD host resulted in the expected profile data so I suspect its related to running in the Ubuntu shell under WSL

**Comment by ALTree** [comment] 2019-06-28 09:13
Thanks for the report. 

This is a duplicate of ##22366 (runtime/pprof: takes zero samples in BashOnWindows (WSL)), so I'm closing this thread in favour of the older one.

**Closed by ALTree** 2019-06-28 09:13 UTC
