### ISSUE TITLE
cmd/go: add go mod download to download modules

### ISSUE THREAD

**Issue by sgnn7** [golang/go#26610] opened 2018-07-25 20:34 UTC
### What version of Go are you using (`go version`)?
go1.11beta2

### Does this issue reproduce with the latest release?
Yes (`1.11beta2`)

### What operating system and processor architecture are you using (`go env`)?
amd64 - linux

### What did you do?
Copying just `go.mod` into an empty directory should allow `go mod -vendor` (or maybe even `go mod -sync`) to download the dependencies regardless of having any other files within the directory. Without this, you cannot use something like Docker to cache the dependencies independent of the codebase itself.

```
$ docker run -it --rm golang:1.11beta2-alpine /bin/sh
/go # apk add -u git
/go # mkdir /foo
/go # cd /foo

/foo # echo "module github.com/sgnn7/test
> 
> require (
>         cloud.google.com/go v0.25.0 // indirect
> )
> " > go.mod

/foo # cat go.mod
module github.com/sgnn7/test

require (
        cloud.google.com/go v0.25.0 // indirect
)

/foo # go mod -vendor
go: finding cloud.google.com/go v0.25.0
go: no dependencies to vendor

/foo # go mod -sync
/foo # # Nothing
```

### What did you expect to see?
`go mod` should have downloaded `go.mod` dependencies based on `go.mod` content regardless if there's code in the repo or not.

### What did you see instead?
Neither `go mod -vendor` nor `go mod -sync` downloaded anything.

**Comment by bcmills** [comment] 2018-07-25 22:18
> Without this, you cannot use something like Docker to cache the dependencies independent of the codebase itself.

Can you include some more detail about your use-case? (Why is that a thing you want to do?)

**Comment by sgnn7** [comment] 2018-07-25 22:49
@bcmills Sure. 

Let's say that you have your code build a Docker image on every git change (most pipelines do this and is probably the biggest use case).
- With `dep` you could create a Docker layer of cached dependencies by just copying `Gopkg.*` and fetching the dependencies after which you then copy the full repo and build the project (see [here](https://github.com/golang/dep/issues/796) for the original issue for `dep` on this). This meant that unless you changed the Gopkg files, no dependency re-download was ever needed, making builds with non-dependency changes quick and efficient.
- With current `go mod`, you cannot just copy `go.mod` and `go.sum` and then run `go mod -vendor` to get this feature parity since it just doesn't download anything without Go files in the repo, forcing the Docker layer to be cache-busted on the smallest of changes in the repo (e.g. README), causing re-download of all dependencies every time which is both slow and extremely inefficient.

**Comment by sgnn7** [comment] 2018-07-26 00:54
@rsc Hmm.. I'll give that a try. Is there a reason why this isn't a base `go mod` command?

**Comment by sgnn7** [comment] 2018-07-26 17:25
@rsc: Your cache warming suggestion doesn't work out of the box. The fixed version is below:
```
go list -e $(go list -m all 2>/dev/null)
```

IMO, If this seems like something that should be used often, it probably needs to get into the main CLI. As a sidenote to this hack, `go list` has no distinction in docs as to why it is the only one that can download modules vs `-sync` and `-vendor`.

**Comment by rsc** [comment] 2018-07-29 06:12
All the commands downloads modules as needed.
sync and vendor are defined to chase down only the package-granularity dependencies of the packages in the main module.
If there are no packages in the main module, they chase down nothing.
List on the other hand can be asked directly about dependency packages,
and answering requires downloading them to look at the code.
It's certainly not a direct answer, but it should work.

That said, it seems to me that `go get -d -m` asks for exactly this
operation and fails to deliver it (the -d is ignored with -m).
We should fix that.

**Comment by moretea** [comment] 2018-07-30 11:52
I got pretty close with https://github.com/golang/go/issues/26610#issuecomment-408172520. To make this work for now, I am using the following Dockerfile:

```Dockerfile
FROM golang as builder
RUN go get -u golang.org/x/vgo
WORKDIR /go/src/github.com/$ORG/$REPO

# Populate the module cache based on the go.{mod,sum} files.
COPY go.mod .
COPY go.sum .
RUN vgo list -e $(vgo list -f '{{.Path}}' -m all)

# Build all binaries, with -getmode=local, this will _not_ fetch packages over the network.
COPY . .
RUN vgo install -getmode=local ./...

# Runtime image
FROM alpine AS base
COPY --from=builder /go/bin/$PROG /bin/$PROG
ENTRYPOINT ["/bin/$PROG"]
```

**Comment by shanna** [comment] 2018-07-31 10:36
@moretea This takes care of caching downloads but if I add `-v` to the go install/build the dependencies are being built each pass still so build/install times can still be very slow if you have a lot of dependencies (firebase, grpc, kubernetes etc).

**Comment by sgnn7** [comment] 2018-07-31 16:03
Small update for those that are using the `go list` to fetch the packages: https://github.com/golang/go/pull/26631 PR by @marwan-at-work should remove the need to pipe `stderr` to `/dev/null` once it gets into the releases.

**Comment by marwan-at-work** [comment] 2018-07-31 18:12
@sgnn7 the CL was closed by @myitcv, not sure if it needs to be re-opened. But my own use case for having that CL is resolved by just using stdout. 
Thanks

**Comment by sgnn7** [comment] 2018-07-31 18:17
@marwan-at-work I don't know why that issue would be abandoned 😢. Maybe it's because the v1.11 GA release date is tomorrow?

As for using stdout, that's what the interim fix uses but it would be nice not to need `2>/dev/null` in it to separate stdout from stderr.

**Comment by myitcv** [comment] 2018-07-31 18:42
@marwan-at-work I closed the CL based on our discussion, yes. Did I prematurely close it? Was there something I missed?

@sgnn7 as things stand, stdout is defined to contain the JSON output; stderr informational messages, with the exit code ultimately used to then determine success or otherwise (with the caveat that `-e` can alter the handling of erroneous packages, per `go help list`) of the list operation.

Does that help to clarify things?

**Comment by marwan-at-work** [comment] 2018-07-31 18:49
@myitcv CL being closed is good on my side :) Just wanted to ping you about @sgnn7's use case. 
Thanks

**Comment by sgnn7** [comment] 2018-07-31 18:58
@myitcv Makes sense though I wouldn't say that it increases simplicity/usability cases (compared to most other *nix tooling).  Either way, this issue is not for that discussion and thank you for the clarification. 👍

**Comment by rsc** [comment] 2018-08-07 18:50
I started looking at go get -d -m but it's a weird combination to redefine.
Instead I am going to add a 'go mod download' that does what you want.
So you could run

	go mod download

to warm a Docker image cache.

**Comment by marwan-at-work** [comment] 2018-08-07 18:55
@rsc will this new subcommand take care of this issue? https://github.com/golang/go/issues/26577
Most notably, `go mod download` would not download dependencies except just the targeted import path.

Would love to help in any way.

Thanks!

**Closed** 2018-08-10 00:02 UTC
Labels: NeedsFix, modules

**Comment by zangbuild** [comment] 2018-12-28 16:35
There is a caveat here, you must have a main package in the directory with go.mod for `go mod download`.

**Comment by mattwilliamson** [comment] 2018-12-28 16:40
There is a caveat here, you must have a main package in the directory with go.mod for go mod download.

**Comment by marwan-at-work** [comment] 2018-12-28 16:41
@zangbuild no longer the case with go1.12, there's already a beta out if you want to give it a shot.

**Comment by mattwilliamson** [comment] 2018-12-28 16:43
Nice. I will try when I can.

**Comment by mbana** [comment] 2019-02-25 11:34
Does `go mod download` also build (and install) the packages?

**Comment by marwan-at-work** [comment] 2019-02-25 15:31
@mbana `go mod download` just downloads content for a module, it does not build and install the package nor does it fetch its dependencies.

**Comment by mcluseau** [comment] 2019-03-04 03:49
Hi, related question: is there a `go mod download-from-vendor` for those already having everything in their vendor directory? Thanks!

**Comment by bcmills** [comment] 2019-03-05 03:50
@mcluseau, the `vendor` directory stores individual packages, not complete modules. It is not a suitable input to the module cache.

**Comment by mcluseau** [comment] 2019-03-18 04:37
So just to follow up, the best way I've found considering that is to use a Go proxy (athens) and the following `Dockerfile`:

```dockerfile
from golang:1.12.1-alpine3.9 as build
run apk add --update git

env CGO_ENABLED=0
arg GOPROXY

workdir /src
add go.mod go.sum ./
run go mod download

add . ./
run go test ./...
run go install . ./cmd/...

from alpine:3.9
#entrypoint ...
copy --from=build /go/bin/ /bin/
```

**Comment by c0b** [comment] 2019-07-01 09:48
is `go mod download` designed to pre-download all go.mod defined dependencies? I found a case might be a bug of it, because I have a similar case want to pre-download as cache and build go code later,
while, in my case, I found `go mod download` indeed download many dependencies but not all of them,
the later `go build ...` command still try downloading some last dependencies,

```console
$ go mod download
....
$ go build ...
go: finding github.com/alecthomas/template latest
go: downloading github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
go: finding github.com/alecthomas/units latest
go: downloading github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
go: extracting github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
go: extracting github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
```

I'm not sure does this mean `go mod download` failed to parse a complete list of dependencies? leaked a few to `go build` command,  should be filed as a `go mod` bug?   here is using `FROM golang:1.12-alpine AS builder`

**Comment by bcmills** [comment] 2019-07-12 20:05
@c0b, if all dependencies are declared (that is, if `go mod tidy` is a no-op), then `go mod download` is intended to download all needed dependencies.

If you find that is not the case, please open a new issue with steps to reproduce (ideally using `go1.13beta1` or newer).

**Comment by ORESoftware** [comment] 2020-04-30 00:47
So yeah `go mod download` needs a verbose option, please
https://github.com/golang/go/issues/38756

```
go mod download --verbose
```

or 

```
go mod -v download
```

whatever, o/w I am just watching the command hang there forever, hoping that nothing is wrong. some feedback would be nice, like with `go install -v`
