### ISSUE TITLE
net: TestNottemporaryRead is flaky (timeout on freebsd-amd64)

### ISSUE THREAD

**Issue by hyangah** [golang/go#25481] opened 2018-05-21 19:32 UTC
The most recent failures was on freebsd-amd64-11_1 builder

https://build.golang.org/log/8bc01b82490b2f817f762df81b2fe2f1bb84af12  (commit d2c68bb)

<pre>
panic: test timed out after 3m0s

goroutine 48700 [running]:
testing.(*M).startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:1296 +0xfd
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:172 +0x44
...
goroutine 5347 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x800860f90, 0x72, 0xc00030adb8)
	/tmp/workdir/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000198718, 0x72, 0xffffffffffffff00, 0x6b66a0, 0x7b64d8)
	/tmp/workdir/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000198718, 0xc00030af00, 0x1, 0x1)
	/tmp/workdir/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000198700, 0xc00030af17, 0x1, 0x1, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/internal/poll/fd_unix.go:163 +0x179
net.(*netFD).Read(0xc000198700, 0xc00030af17, 0x1, 0x1, 0xc0000f8038, 0xc00030aed8, 0x551f26)
	/tmp/workdir/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000f8038, 0xc00030af17, 0x1, 0x1, 0x0, 0x0, 0xc00030af48)
	/tmp/workdir/go/src/net/net.go:176 +0x68
net.TestNotTemporaryRead.func2(0xc0000f8038, 0x6b96b8, 0xc0000f8038)
	/tmp/workdir/go/src/net/net_test.go:531 +0x5b
net.withTCPConnPair.func1(0x6b7c60, 0xc00048a020, 0xc0004f5c80, 0x693ce0)
	/tmp/workdir/go/src/net/net_test.go:437 +0xa2
created by net.withTCPConnPair
	/tmp/workdir/go/src/net/net_test.go:430 +0x141
</pre>

https://storage.googleapis.com/go-build-log/9f071c69/freebsd-amd64-11_1_8eef53cd.log
is another instance from trybot run (again on freebsd-amd64-11_1)

**Comment by tklauser** [comment] 2018-05-22 13:28
This looks like a duplicate of #25289

**Closed** 2018-05-22 15:31 UTC
