### ISSUE TITLE
path/filepath:  Clean() has different outcome on 1.19.6 vs 1.20.1 Windows builds

### ISSUE THREAD

**Issue by aldas** [golang/go#58597] opened 2023-02-19 17:53 UTC
### What version of Go are you using (`go version`)?

I am trying latest 1.19.6 and 1.20.1 on Windows 10.

go1.19.6.windows-amd64.msi
revision number: {E9FE7DE3-5CBC-4BDA-B441-DAFD925BC99E}
created: 13.02.2023  19:47

go1.20.1.windows-amd64.msi
revision number: {D5176384-A024-4BFA-959B-A81AF822C0AB}
created: 13.02.2023 19:46

Windows 10 Pro (version 22H2)

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Following test that uses filepath.Clean is giving me different results on different Go versions. I understand that recently https://go-review.googlesource.com/c/go/+/468115 + related problems were fixed. but I would assume even then the result would be same for both of the releases.

```go
func TestFilePath_Clean(t *testing.T) {
	var testCases = []struct {
		when   string
		expect string
	}{
		{
			when:   `/../../secret.txt`,
			expect: `\secret.txt`, // same on go1.19.6 windows/amd64 and go1.20.1 windows/amd64
		},
		{
			when: `//../../secret.txt`,
			//expect: `\secret.txt`, //  go1.19.6 windows/amd64
			expect: `\\..\..\secret.txt`, //  go1.20.1 windows/amd64
		},
		{
			when: `//..\..\secret.txt`,
			//expect: `\secret.txt`, //  go1.19.6 windows/amd64
			expect: `\\..\..\secret.txt`, //  go1.20.1 windows/amd64
		},
	}

	for _, tc := range testCases {
		t.Run(tc.when, func(t *testing.T) {
			p := filepath.Clean(tc.when)
			if tc.expect != p {
				t.Fatalf("%v != %v", p, tc.expect)
			}
		})
	}
}
```

### What did you expect to see?

I expect 1.19.6 and 1.20.1 have same result. what ever it right.

### What did you see instead?

Result for 1.20.1 is different from 1.19.6

**Comment by antichris** [comment] 2023-02-19 19:14
Note that `\\` is a [UNC network path](https://en.wikipedia.org/wiki/Path_(computing)#UNC) prefix. See #56336.

**Comment by ianlancetaylor** [comment] 2023-02-21 05:18
CC @neild Should there be something in the release notes for this?  Thanks.

**Comment by antichris** [comment] 2023-02-21 07:12
Looks like this is a duplicate of #58348, and can probably be closed as such. The discussion could continue there.

**Comment by thanm** [comment] 2023-02-21 16:19
dup of  #58348.

**Closed by thanm** 2023-02-21 16:19 UTC
