### ISSUE TITLE
net/http/pprof: durationExceedsWriteTimeout check doesn't consider ResponseController.SetWriteDeadline

### ISSUE THREAD

**Issue by sentriz** [golang/go#64516] opened 2023-12-02 17:40 UTC
### Go version

go version go1.21.4 linux/amd64

### What operating system and processor architecture are you using (`go env`)?

<details>
<summary><code>$ go env</code></summary>

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/senan/.cache/go-build'
GOENV='/home/senan/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/senan/.local/share/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/senan/.local/share/go'
GOPRIVATE=''
GOPROXY='direct'
GOROOT='/usr/lib/go'
GOSUMDB='off'
GOTMPDIR=''
GOTOOLCHAIN='local+path'
GOTOOLDIR='/usr/lib/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1962473061=/tmp/go-build -gno-record-gcc-switches'
```

</details>

### What did you do?

curling the following program with 

`curl "http://localhost:8080/debug/pprof/profile?seconds=10"`

(10 seconds being longer than the 1 second global WriteTimeout, but before than the deadline set by SetWriteDeadline)

https://go.dev/play/p/zWTDhWFutKP

```go
package main

import (
	"fmt"
	"net/http"
	"net/http/pprof"
	"time"
)

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/debug/pprof/profile", func(w http.ResponseWriter, r *http.Request) {
		rc := http.NewResponseController(w)
		rc.SetWriteDeadline(time.Time{}) // no deadline
		pprof.Profile(w, r)
	})

	server := http.Server{
		Addr:         ":8080",
		WriteTimeout: 1 * time.Second, // 1 second timeout
		Handler:      mux,
	}

	fmt.Println(server.ListenAndServe())
}
```

### What did you expect to see?

the request succeeds  

### What did you see instead?

HTTP 400 with ["profile duration exceeds server's WriteTimeout"](https://cs.opensource.google/go/go/+/refs/tags/go1.21.4:src/net/http/pprof/pprof.go;l=117-120)

this makes it hard to expose custom pprof handlers with global server write timeouts

**Comment by seankhliao** [comment] 2023-12-02 18:24
Duplicate of #62358

**Closed by seankhliao** 2023-12-02 18:24 UTC
Labels: compiler/runtime
