### ISSUE TITLE
implementation of min/max does not match specification

### ISSUE THREAD

**Issue by msackman** [golang/go#61031] opened 2023-06-27 15:06 UTC
### What version of Go are you using (`go version`)?

dev tip - as of playground today

### What operating system and processor architecture are you using (`go env`)?

https://go.dev/play/p/0anvpbIRZ2I?v=gotip

### What did you do?

The spec at https://tip.golang.org/ref/spec#Min_and_max states:

> The same type rules as for [operators](https://tip.golang.org/ref/spec#Operators) apply: for [ordered](https://tip.golang.org/ref/spec#Comparison_operators) arguments x and y, min(x, y) is valid if x + y is valid, and the type of min(x, y) is the type of x + y (and similarly for max). If all arguments are constant, the result is constant.

The following example shows the implementation does not match the spec:

```go
package main

import "fmt"

func main() {
	var y int = max(7.1, 10)
	var x int = 7.1 + 10
	fmt.Println(x, y)
}
```

### What did you expect to see?

The type checker should have errored on the line with `var y int = max(7.1, 10)` because, as the spec says, `7.1 + 10` yields a float, which cannot unify with an int - the declared type of `y`.

### What did you see instead?

The type checker errors on the following line instead (`var x int = 7.1 + 10`), telling me that `7.1 + 10` yields a float, which cannot unify with an int - the declared type of `x`. Consequently it is clear that the type checker has found no error with the preceding line, which is a bug.

**Comment by cuonglm** [comment] 2023-06-27 15:14
I think this is working as intended. `max(7.1, 10)` yield an int, because `y` is declared as int.

On the other hand, `7.1 + 10` yield an untyped float, which couldn't be assigned to an int.

**Comment by msackman** [comment] 2023-06-27 15:18
If that's the case then I believe the spec will need to be updated. My interpretation of the spec is that min/max should behave _exactly_ as `+` behaves.

**Comment by cuonglm** [comment] 2023-06-27 15:22
> If that's the case then I believe the spec will need to be updated. My interpretation of the spec is that min/max should behave _exactly_ as `+` behaves.

It does behave the same to me. For example, max(7.1, 10) yield 10 as an untyped float, so `10.0`. This untyped float constant can be used as value to assign to an int.

**Comment by msackman** [comment] 2023-06-27 15:28
Ok, I understand your point, thank you.

But I think this is potentially very dangerous, because it means that if you have a number of consts throughout your codebase, and you happen to change one number then it means the *type* of an expression could change. Consider:

https://go.dev/play/p/zApEDV5vf5I?v=gotip

```go
const x = 10
const y = 9.1

func main() {
	var z int = max(x, y)
	fmt.Println(z)
}
```

Now let's say some future edit changes that `const y = 9.1` to `const y = 12.2`. The type checker now fails at the `max`. The idea that changing a const *value* and *not* its type, could change the type of an expression, seems very very weird to me. Is there any other feature of Go where this happens?

**Comment by cuonglm** [comment] 2023-06-27 15:32
> Ok, I understand your point, thank you.
> 
> 
> 
> But I think this is potentially very dangerous, because it means that if you have a number of consts throughout your codebase, and you happen to change one number then it means the *type* of an expression could change. Consider:
> 
> 
> 
> https://go.dev/play/p/zApEDV5vf5I?v=gotip
> 
> 
> 
> ```go
> 
> const x = 10
> 
> const y = 9.1
> 
> 
> 
> func main() {
> 
> 	var z int = max(x, y)
> 
> 	fmt.Println(z)
> 
> }
> 
> ```
> 
> 
> 
> Now let's say some future edit changes that `const y = 9.1` to `const y = 12.2`. The type checker now fails at the `max`. The idea that changing a const *value* and *not* its type, could change the type of an expression, seems very very weird to me. Is there any other feature of Go where this happens?

This is how untyped constant work. I'm not sure what you mean, the type is never changed. It always yield an untyped float64 constant. It's just that 10.0 can be used as int, but 12.2 is not.

**Closed** 2023-06-27 15:32 UTC
