### ISSUE TITLE
go/test: Testable examples 

### ISSUE THREAD

**Issue by thomascoquet** [golang/go#50737] opened 2022-01-21 09:31 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18beta1 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/thomascoquet/.cache/go-build"
GOENV="/home/thomascoquet/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/thomascoquet/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/thomascoquet/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/thomascoquet/sdk/go1.18beta1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/thomascoquet/sdk/go1.18beta1/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18beta1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/thomascoquet/Work/nd/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1691419429=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```go
func ExampleTest() {
	w := tabwriter.NewWriter(os.Stdout, 6, 2, 2, ' ', 0)
	fmt.Fprintln(w, "a\tb\tc\t")
	fmt.Fprintln(w, "aa\tbb\tcc\t")
	fmt.Fprintln(w, "aaa\tbbb\tccc\t")
	w.Flush()

	// Output:
	// a     b     c
	// aa    bb    cc
	// aaa   bbb   ccc
}
```

### What did you expect to see?

No error.

### What did you see instead?
```go
--- FAIL: ExampleTest (0.00s)
got:
a     b     c     
aa    bb    cc    
aaa   bbb   ccc
want:
a     b     c
aa    bb    cc
aaa   bbb   ccc
FAIL
```

### Reason

`gofmt` strips trailing whitespaces in comments. Therefore it is impossible to have a proper match if gofmt is applied.

I suggest to remove trailing whitespaces as well before comparing both (comment and stdout).

**Comment by mvdan** [comment] 2022-01-21 09:57
Duplicate of https://github.com/golang/go/issues/26460, which is open.

**Closed by mvdan** 2022-01-21 09:57 UTC
