### ISSUE TITLE
https://github.com/educlos/testrail/ - unable to add case in testrail + template_id mandatory parameter is missing

### ISSUE THREAD

**Issue by yamunadevins** [golang/go#31654] opened 2019-04-24 12:09 UTC
go version
go1.11.5 windows/amd64

Does this issue reproduce with the latest release?
yes

unable to add a case in testrail
i passed section id, title ,string ,text, type id, priority id
package testrail_addcase

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"testing"

	"github.com/educlos/testrail"
)

func TestMain(m *testing.M) {
	fmt.Printf("calling testrail client connection")
	m.Run()
}

func TestUpdateResult(t *testing.T) {

	f, err := os.Open("config.json") // config.json has the json content
	if err != nil {
		log.Fatal(err)
	}
	bb, err := ioutil.ReadAll(f)
	if err != nil {
		log.Fatal(err)
	}
	doc := make(map[string]interface{})
	if err = json.Unmarshal(bb, &doc); err != nil {
		log.Fatal(err)
	}
	log.Printf("full json: %s", string(bb))
	url := os.Getenv("TESTRAIL_URL")
	if url == "" {
		url = doc["URL"].(string)
	}
	username := os.Getenv("TESTRAIL_USERNAME")
	password := os.Getenv("TESTRAIL_TOKEN")
	if username == "" {
		username = doc["USERNAME"].(string)
	}
	if password == "" {
		password = doc["PASSWORD"].(string)
	}
	fmt.Println("Creating connection to testrail")
	client := testrail.NewClient(url, username, password)
	sectionID := int(doc["SECTIONID"].(float64))
	milestoneID := int(doc["MILESTONEID"].(float64))
	typeID := int(doc["TYPEID"].(float64))
	priorityID := int(doc["PRIORITYID"].(float64))
	suiteID := int(doc["SUITEID"].(float64))
	title := doc["TITLE"].(string)
	text := doc["TEXT"].(string)
	string := doc["STRING"].(string)
	addcase := testrail.SendableCase{}
	addcase.Title = title
	addcase.MilestoneID = milestoneID
	addcase.TypeID = typeID
	addcase.PriorityID = priorityID
	addcase.Text = text
	addcase.String = string
	addcase.TemplateID = 1
	casetype := []testrail.CaseType{}
	priorities := []testrail.Priority{}
	sections := []testrail.Section{}
	projects := []testrail.Project{}
	casetype, _ = client.GetCaseTypes()
	priorities, _ = client.GetPriorities()
	projects, _ = client.GetProjects()
	sections, _ = client.GetSections(55, suiteID)
	fmt.Printf("%+v\n", casetype)
	fmt.Println("*******************************************")
	fmt.Printf("%+v\n", priorities)
	fmt.Println("*******************************************")
	fmt.Printf("%+v\n", addcase)
	fmt.Println("*******************************************")
	fmt.Printf("%+v\n", projects)
	fmt.Println("*******************************************")
	fmt.Printf("%+v\n", sections)
	fmt.Println("*******************************************")

	Case, error := client.AddCase(sectionID, addcase)
	if error != nil && err != nil {
		fmt.Println(error)
		t.Error("TestUpdateResult failed")
	}
	fmt.Println(Case)
}

Regards,
Yamuna

**Comment by thanm** [comment] 2019-04-24 15:41
It is unclear to me what the nature of the problem is -- is this a failure to build, or an error issued at runtime? Please give more details on exactly what you did, what happened, and what you expected instead. Thanks.

**Comment by yamunadevins** [comment] 2019-04-29 07:18
@thanm I am trying to add a case, it is returning success but not adding the case, i have uploaded the code as above what i have passed as parameters

**Comment by thanm** [comment] 2019-04-29 18:19
How are you invoking your new test? What's the name of the new test file?

It's hard to diagnose the problem without these sorts of specifics.

The normal convention when writing testing code for Go packages:

- all test code is in file whose names end in "_test.go"
- if a file contains tests that exercise non-exported things in the package "xyz", then that file uses "package xyz"
- if a file contains tests that only interact with the public parts of package "xyz", then that file uses "package xyz_test"

The code you gave uses "package package testrail_addcase", which is neither "testrail" nor "testrail_test".

**Comment by thanm** [comment] 2019-05-02 15:23
@yamunadevins is this still a problem?

**Comment by thanm** [comment] 2019-05-03 13:50
Closing out this issue, please reopen if needed.

**Closed by thanm** 2019-05-03 13:50 UTC
Labels: WaitingForInfo
