### ISSUE TITLE
proxy.golang.org: non-ascii paths not supported

### ISSUE THREAD

**Issue by carnott-snap** [golang/go#37835] opened 2020-03-13 00:52 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/.local/share/umake/go/go-lang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/.local/share/umake/go/go-lang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build606606876=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```go
package main

import _ "example.com/aаa"
```
```sh
go mod tidy
```
### What did you expect to see?
```
go: finding module for package example.com/aаa
main imports
        example.com/aаa: cannot find module providing package example.com/aаa: unrecognized import path "example.com/aаa": reading https://example.com/a%D0%B0a?go-get=1: 404 Not Found

```

### What did you see instead?
```
go: finding module for package example.com/aаa
main imports
        example.com/aаa: malformed module path "example.com/aаa": invalid char 'а'
```

**Comment by bcmills** [comment] 2020-03-13 13:18
I would argue that we should _never_ accept the particular path `example.com/aаa`: it is indistinguishable from a [homograph attack](https://en.wikipedia.org/wiki/IDN_homograph_attack).

For other unicode paths, see #29101.

**Comment by bcmills** [comment] 2020-03-13 13:18
Duplicate of #29101

**Closed by bcmills** 2020-03-13 13:18 UTC
