### ISSUE TITLE
x/net/trace: init registers an endpoint on the http.DefaultServeMux, causing a panic if vendored in some cases

### ISSUE THREAD

**Issue by jadekler** [golang/go#24137] opened 2018-02-26 19:23 UTC
[x/net registers an endpoint in the http global](https://github.com/golang/net/blob/cbe0f9307d0156177f9dd5dc85da1a31abc5f2fb/trace/trace.go#L112-L117). When this package is imported multiple times (because other packages I use import it) causes:

```
panic: http: multiple registrations for /debug/requests
```

**Comment by dgryski** [comment] 2018-02-26 19:35
Duplicate of https://github.com/golang/go/issues/20478

**Comment by jadekler** [comment] 2018-02-26 20:16
Thanks @dgryski. I'll leave this open unless maintainers decide to close, since it remains an issue.

**Comment by andybons** [comment] 2018-03-26 21:34
Duplicate of #20478

**Comment by jadekler** [comment] 2018-03-27 05:42
@andybons @davecheney Can I have some clarification on why #20478 is closed and locked? The thread is extremely unsatisfactory. This is an issue which causes unwanted panics when I import several packages (as in, it's not my program's fault) - this feels *strongly* like something that should be discussed, or at least something that should have guidance for how to deal with.

**Comment by bradfitz** [comment] 2018-07-31 16:59
To some extent this problem should go away with Go modules in Go 1.11 and later, as we won't have duplicate copies of packages loaded and fighting with each other.

In some way the panic from ServeMux duplicate registration is almost a feature in that it alerts you that you've loaded two copies of x/net/trace when you almost certainly want just one in your program.

**Comment by bradfitz** [comment] 2018-07-31 19:36
> It's still an issue if one were to have two versions of /x/net in their program (say if they were incrementally upgrading in a very large project).

Like I said above, in that case the panic is a feature: it told you accidentally introduced a copy.

**Comment by jadekler** [comment] 2018-07-31 20:57
I wish I had thought ahead enough to document a repro, so that we had something concrete to discuss :(

> In some way the panic from ServeMux duplicate registration is almost a feature in that it alerts you that you've loaded two copies of x/net/trace when you almost certainly want just one in your program.

Is it possible for one of my deps to have a vendored copy of x/net/trace, and meanwhile I directly depend on x/net/trace? This seems the most likely way that this occurred. Although this is probably not ideal, it seems like something that should probably work fine instead of causing a panic.

**Comment by bradfitz** [comment] 2018-07-31 21:01
> Although this is probably not ideal, it seems like something that should probably work fine instead of causing a panic.

It's less than ideal: it means some of your traces are in one global variable and some of them are in another global variable.

(the x/net/trace activeTraces package global)

You really want just one copy in your entire program.

**Comment by jadekler** [comment] 2018-07-31 21:26
Ah, that makes sense. How about this: in order to aid debugging of the problem, I can add a couple lines of documentation in the init that describes this situation. Is that acceptable? Minimally I think it'd be good for folks to understand _why_ it's a bad thing if that panic occurs.

**Comment by bradfitz** [comment] 2018-07-31 22:08
Whose init? If it's just a comment in the code, who will ever see it?

Ideally we'd instead make x/net/trace detect this situation (recovering the ServeMux panic?) and re-panic with a more helpful panic. ("You have two independent copies of golang.org/x/net/trace in your binary, trying to maintain separate state. That doesn't work. Boom.")

**Comment by jadekler** [comment] 2018-08-01 01:40
https://go-review.googlesource.com/c/net/+/127121 ?

**Comment by e-nikolov** [comment] 2018-08-01 09:12
In the case of Go plugins, it makes sense for each plugin to use its own vendored version of the x/net/trace package. If they are not vendored, Go will realize that they are the same package, and will require that they be the same exact version. Otherwise you get an error saying that the plugin was built with a different version of x/net/trace and loading it will fail. If they are both vendored Go will think that the two packages are different because one is loaded from .../plugin1/vendor/x/net/trace and the other one from .../plugin2/vendor/x/net/trace. In this case, the init() will be executed twice and the panic will occur. The only workaround I have seen is to reinitialize the http.DefaultServeMux before loading each plugin.

**Comment by bradfitz** [comment] 2018-08-01 16:25
I think plugins just can't use separate copies of packages which are supposed to maintain global state.

You should redesign your plugin boundaries and instead create one x/net/trace and arrang to pass what's needed to your plugin at runtime instead.

**Closed** 2018-08-01 23:40 UTC

**Comment by e-nikolov** [comment] 2018-08-02 08:44
I don't think it's easy to control the dependencies that plugins have. Those could be made and built by third parties and if we'd have to provide a list of "banned" dependencies, it wouldn't be ideal.

**Comment by bradfitz** [comment] 2018-08-02 14:46
@e-nikolov, if you're consuming plugins, you set the rules. As I said before: 

> You should redesign your plugin boundaries and instead create one x/net/trace and arrange to pass what's needed to your plugin at runtime instead.

**Comment by e-nikolov** [comment] 2018-08-02 15:29
This might be approaching off-topic, but in my particular case, plugins are used to receive messages via some medium (i.e. http, grpc, amqp) and then pass them on to the base application. Some such plugins receive messages over GRPC, which imports x/net/trace and results in a panic due to the issue outlined here. 

Are you suggesting that we should be initializing all possible mediums in the base application and then supplying them to the plugins? I don't think this is workable since the base application has no way to anticipate all possible mediums and those are chosen by the plugins themselves.

I hope I am not being too annoying, I am just trying to understand the approach you suggested.

**Comment by gotoxu** [comment] 2018-10-30 03:37
I support @e-nikolov's point of view. Plugins are usually developed and maintained by third parties, limiting the dependencies that plugins can use is not a good idea. 

Moreover, there is still a situation. I encountered a problem when developing the [hyperledger fabric](https://github.com/hyperledger/fabric) system chaincode plugin. The chaincode relies on some packages of the fabric, and these packages depend on x/net/trace. If I develop plugin in a standalone project, and vendored dependencies in my project, Go will think I use two different packages. so system will be panic when the fabric loads my plugin. 

If I want to solve this problem, I have to put the source code of the plugin into the fabric project, so that plugin and fabric will use the same vendor's x/net/trace package. This is not a good development style, right?

**Comment by santsai** [comment] 2019-01-10 06:14
This fix here https://github.com/golang/net/commit/f4c29de78a2a91c00474a2e689954305c350adf9 can introduce false positive panic when another package have a `init` that does `http.HandleFunc("/", mainHandler)` and runs before `x/net/trace`'s `init`.

This is due to `http.DefaultServeMux.Handler` does most specific match and not exact match. Changing https://github.com/golang/net/blob/be1c187aa6c66b9daa1d9461c228d17e9dd2cab7/trace/trace.go#L116 	`if pat != "" {` to `if pat == "/debug/requests" {` can fix this.

**Comment by bradfitz** [comment] 2019-01-10 19:12
@santsai, thanks.  I sent https://go-review.googlesource.com/c/net/+/157378 .... feel free to review there.
