### ISSUE TITLE
x/build: add openbsd/arm builder

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#25498] opened 2018-05-22 14:56 UTC
@4a6f656c used to maintain one but it doesn't seem to be running anymore.

Cloud arm32 is hard to find, so this might end up being a Raspberry Pi on my desk.

**Comment by 4a6f656c** [comment] 2018-12-11 15:23
I've resurrected the openbsd/arm builder and should be able to continue running it for the foreseeable future (or until another option is found).

**Comment by bcmills** [comment] 2019-05-06 13:39
I see that the builder is running, but it seems not to have enough memory to complete the tests reliably. Basically all of the runs are failing with `fatal error: runtime: out of memory`.

Is it possible to add more RAM to the builder, or perhaps configure it with some swap to deal with bigger tests?

Examples:
https://build.golang.org/log/17984e5b3a059c1882855a2c8774fdb7d8ecfad6
https://build.golang.org/log/5233126dc3a18b78a2fee33288f378485eeb66ac
https://build.golang.org/log/ce51b2eebed1b20dc6be028224d613fda8bcc216

**Comment by 4a6f656c** [comment] 2019-06-30 14:02
@bcmills - the platform is limited to 1GB of data size and this was a regression from Go 1.12, which was fixed via issue #27739.

**Comment by bcmills** [comment] 2019-08-30 18:05
@4a6f656c, please disable the `openbsd-arm` builder until it can be converted to use `cmd/buildlet`.

The old-style builders are no longer supported (https://github.com/golang/go/issues/21191#issuecomment-497344063), and we can't easily fix configuration issues with them (such as #32838).

**Comment by 4a6f656c** [comment] 2020-01-04 12:59
@bcmills @dmitshur - a replacement openbsd-arm builder (host-openbsd-arm-joelsing) is running with `cmd/buildlet`, however is repeatedly failing in the coordinator (server side) with a `writeSnapshot: failed to write snapshot to GCS` timeout... I presume that my somewhat limited upstream bandwidth, combined with being a long way away (network wise), means that the time limit is insufficient to complete the upload. Could you please investigate?

**Comment by bcmills** [comment] 2020-01-06 14:28
(CC @toothrot, @cagedmantis)

**Comment by 4a6f656c** [comment] 2020-01-31 02:55
@bcmills @toothrot @cagedmantis - I've turned the buildlet off since it has just been spinning its wheels for the last month. Please let me know when I should try again.

**Comment by dmitshur** [comment] 2020-04-13 22:08
@4a6f656c Thanks for working on this and sorry about the delay. A few questions to better understand the `writeSnapshot` issue that's blocking you from proceeding.

Have you considered the [SkipSnapshot](https://github.com/golang/go/issues/25498#issuecomment-570783627) configuration option for this builder? Do you know what the effect of using it on your builder would be?

The `writeSnapshot` timeout was increased from 1 minute to 5 minutes 3 years ago in [CL 37468](https://golang.org/cl/37468), with a comment noting that most operations should happen in well under a minute. Do you have information about the upstream speed of your builder, so we can estimate if increasing that timeout slightly would be sufficient, or if we need to approach this differently.

**Comment by 4a6f656c** [comment] 2020-04-14 15:49
@dmitshur - ah, I was not aware of SkipSnapshot - that does in fact look like it would solve the issue, not sure if sharded tests are an issue here (for openbsd/arm and openbsd/arm64 they would seem unlikely, not sure for linux/riscv64). The upstream network is ~1Mbps, the bigger issue is likely the RTT from .au to .us.

I'll raise a CL...

**Comment by 4a6f656c** [comment] 2020-04-15 04:40
@dmitshur - could you please let me know when that change is deployed and I'll try restarting the openbsd/arm builder.

**Comment by dmitshur** [comment] 2020-04-15 12:49
@4a6f656c Sure. It's deployed now.

**Comment by 4a6f656c** [comment] 2020-04-16 15:51
@dmitshur - thanks, we're now up and running, although I've just mailed another CL to reduce the amount of work the builder is trying to do.

**Comment by 4a6f656c** [comment] 2020-04-20 17:05
@dmitshur - any chance of getting the last change deployed (openbsd/arm currently has 873 builds queued)?

**Comment by dmitshur** [comment] 2020-04-20 17:20
Yes, it will be deployed at the nearest opportunity, likely today.

**Comment by 4a6f656c** [comment] 2020-04-20 17:31
@dmitshur - thanks!

**Comment by andybons** [comment] 2020-05-27 17:39
@4a6f656c the `openbsd-arm-jsing` builder has been failing [builds](https://build.golang.org) for a bit now. Can you take a look?

**Comment by 4a6f656c** [comment] 2020-05-30 08:03
@andybons the builder was upgraded to OpenBSD 6.7 - builds resumed functioning after https://go-review.googlesource.com/c/go/+/234381 was landed. There are still a handful of intermittent failures which I need to look at - most of these are likely related to the fact that it is a slow non-MP platform.

**Comment by 4a6f656c** [comment] 2020-08-20 18:35
@andybons @dmitshur - I presume this can now be closed?

**Comment by dmitshur** [comment] 2020-08-20 19:09
A builder for `linux/arm` has been added and it's live, so let's close this. Thank you Joel!

**Closed by dmitshur** 2020-08-20 19:09 UTC
Labels: Builders, FeatureRequest, new-builder
