### ISSUE TITLE
cmd/go: go build fails in module mode when all source files are symlinks

### ISSUE THREAD

**Issue by y3llowcake** [golang/go#31703] opened 2019-04-26 22:11 UTC
### What version of Go are you using (`go version`)?

<pre>
% go version
go version go1.12.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
% go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cy/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/cy/go"
GOPROXY=""
GORACE=""
GOROOT="/home/cy/go/go1.12.2"
GOTMPDIR=""
GOTOOLDIR="/home/cy/go/go1.12.2/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/cy/tmp/gobuildsymlinks/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build527931708=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

When I have a directory that contains only symlinks to .go source files, and I am in module mode, go build fails.

Not using module mode, or adding a single non-symlink file as a workaround, fixes the issue.

<pre>
% ls -laR
.:
total 16
drwxrwxr-x  4 cy cy 4096 Apr 26 15:01 .
drwxrwxr-x 38 cy cy 4096 Apr 26 14:58 ..
drwxrwxr-x  2 cy cy 4096 Apr 26 14:59 real
drwxrwxr-x  2 cy cy 4096 Apr 26 15:00 sym

./real:
total 12
drwxrwxr-x 2 cy cy 4096 Apr 26 14:59 .
drwxrwxr-x 4 cy cy 4096 Apr 26 15:01 ..
-rw-rw-r-- 1 cy cy   66 Apr 26 14:59 main.go

./sym:
total 8
drwxrwxr-x 2 cy cy 4096 Apr 26 15:00 .
drwxrwxr-x 4 cy cy 4096 Apr 26 15:01 ..
lrwxrwxrwx 1 cy cy   15 Apr 26 15:00 main.go -> ../real/main.go

% go build -o /dev/null ./sym

% go mod init gobuildsymlinks
go: creating new go.mod: module gobuildsymlinks

% go build -o /dev/null ./sym
build gobuildsymlinks/sym: cannot load gobuildsymlinks/sym: no Go source files

% echo "package main" >> ./sym/hack.go

% go build -o /dev/null ./sym  
</pre>

### What did you expect to see?

`go build` successfully produces a binary.

### What did you see instead?

fails with: `cannot load <package>: no Go source files`

**Comment by y3llowcake** [comment] 2019-04-27 17:57
I did not correctly test with the latest release, looks like it was fixed in https://github.com/golang/go/commit/3726d91d680b20d147f5b0b6222232d10930d121

**Comment by y3llowcake** [comment] 2019-04-27 18:04
Reopening now that I've confirmed this reproduces in the latest release (go1.12.4), but is fixed at HEAD.

Would it be possible to cherrypick this fix into a minor release?

**Comment by katiehockman** [comment] 2019-04-30 16:47
Closing as a duplicate of #28107, but will request the cherrypick (backport) from that issue.

**Closed by katiehockman** 2019-04-30 16:47 UTC
Labels: modules
