### ISSUE TITLE
strings: Undocumented behavior of strings.FieldsFunc

### ISSUE THREAD

**Issue by elwinar** [golang/go#12351] opened 2015-08-26 21:30 UTC
I just remarked by reading the source of the [`strings.FieldsFunc`](http://golang.org/src/strings/strings.go?s=7834:7868#L321) that the method will also remove empty fields from its return value. For example, see the following [playground](http://play.golang.org/p/JbR62zX3en).

Seeing that the used algorithm isn't the same than the one for the splits, I wonder if it is an undocumented feature or a bug ?

**Comment by ianlancetaylor** [comment] 2015-08-27 00:51
The behaviour of FieldsFunc seems to match the documentation.  It splits the string at each run of code points satisfying the function.  This is different from the documentation of Split, which returns substrings separated by sep--not a run of sep, just sep.  So I think this is working as intended.

I'm going to close this issue, but please feel free to reopen if you disagree.

**Closed by ianlancetaylor** 2015-08-27 00:51 UTC

**Comment by elwinar** [comment] 2015-08-27 07:44
Oh, I didn't saw the `run` part of the documentation. My bad.
