### ISSUE TITLE
x/pkgsite: sub-repositories are missing from https://pkg.go.dev/golang.org/x

### ISSUE THREAD

**Issue by AGWA** [golang/go#58883] opened 2023-03-05 21:12 UTC
### What is the URL of the page with the issue?

https://pkg.go.dev/golang.org/x

### What did you expect to see?

Links to:
* https://pkg.go.dev/golang.org/x/mod
* https://pkg.go.dev/golang.org/x/oauth2
* https://pkg.go.dev/golang.org/x/term
* https://pkg.go.dev/golang.org/x/vuln

### What did you see instead?

No links to these sub-repositories.

**Comment by seankhliao** [comment] 2023-03-06 01:11
Duplicate of #56482

**Closed by seankhliao** 2023-03-06 01:11 UTC
Labels: pkgsite
