### ISSUE TITLE
x/website: command wrong on website tutorial need retire the '=' after -replace

### ISSUE THREAD

**Issue by denpufa** [golang/go#46722] opened 2021-06-12 22:58 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?

Yes,

### What operating system and processor architecture are you using (`go env`)?
It's not a problem with Go code.
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
I use the command 
<pre>
$ go mod edit -replace=example.com/greetings=../greetings
</pre>

### What did you expect to see?

nothing on prompt command after runing the comand

### What did you see instead?
<pre>
go mod: -replace=example: need old[@v]=new[@w] (missing =)
</pre>

**Comment by seankhliao** [comment] 2021-06-12 23:18
Duplicate of #44924

**Closed by seankhliao** 2021-06-12 23:18 UTC
