### ISSUE TITLE
net/http: DetectContentType does not detect image/svg+xml

### ISSUE THREAD

**Issue by brabiega** [golang/go#47492] opened 2021-08-01 19:11 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build996188498=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
Get some svg document (e.g. create new one with Inkscape), save it as example.svg

```
package main

import "fmt"
import "net/http"
import "io/ioutil"

func main() {
    body, _ := ioutil.ReadFile("example.svg")
    res := http.DetectContentType(body)
    fmt.Println(res)
}

```

### What did you expect to see?
`image/svg+xml; charset=utf-8`

### What did you see instead?
`text/xml; charset=utf-8`

Standalone SVG documents aren't properly recognized.
https://www.w3.org/TR/SVG2/conform.html#DocumentConformanceClasses

Example of SVG document
```
root@machine:~# head -n 10 example.svg 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:xlink="http://www.w3.org/1999/xlink"
```

**Comment by seankhliao** [comment] 2021-08-01 19:23
Duplicate of #15888

**Closed by seankhliao** 2021-08-01 19:23 UTC

**Comment by brabiega** [comment] 2021-08-02 06:48
Hello,
So.. this issue is not solved. Content type is detected incorrectly.
At least a word of comment in the documentation that this method is not reliable and may not work as expected?

**Comment by seankhliao** [comment] 2021-08-02 20:44
The documentation is clear in that it only returns those defined by https://mimesniff.spec.whatwg.org/
