### ISSUE TITLE
net/http - HTTP Response body missing data

### ISSUE THREAD

**Issue by D3vil0per** [golang/go#51605] opened 2022-03-11 00:04 UTC
### What version of Go are you using (`go version`)? 

<pre>
$ go version
go version go1.17.8 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ uname -a
Linux pwnbox-base 5.14.0-2parrot1-amd64 #1 SMP Debian 5.14.6-2parrot1 (2021-09-25) x86_64 GNU/Linux
</pre></details>

### What did you do?

Noted that for some websites (for example Wordpress Login pages), when net/http is used for performing a HTTP request, the HTTP response body lacks of some information. For example, by running the following GO script for performing a HTTP POST request to a public Wordpress-based website:
```golang
package main

import (
    "bytes"
    "encoding/json"
    "fmt"
    "io/ioutil"
    "net/http"
)

func main() {
    reqBody, err := json.Marshal(map[string]string{
        "log": "admin",
        "pwd": "tedsdad",
        "wp-submit": "Log In",
        "redirect_to": "http://www.rangelagos.com/wp-admin/",
        "testcookie": "1",
    })
    if err != nil {
        print(err)
    }
    resp, err := http.Post("http://www.rangelagos.com/wp-login.php",
        "application/json", bytes.NewBuffer(reqBody))
    if err != nil {
        print(err)
    }
    defer resp.Body.Close()
    body, err := ioutil.ReadAll(resp.Body)
    if err != nil {
        print(err)
    }
    fmt.Println(string(body))
}
```
I get this HTTP response body:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
<head>
        <title>RangeLagos &rsaquo; Log In</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel='stylesheet' href='http://www.rangelagos.com/wp-admin/css/login.css?ver=20081210' type='text/css' media='all' />
<link rel='stylesheet' href='http://www.rangelagos.com/wp-admin/css/colors-fresh.css?ver=20081210' type='text/css' media='all' />
</head>
<body class="login">

<div id="login"><h1><a href="http://wordpress.org/" title="Powered by WordPress">RangeLagos</a></h1>

<form name="loginform" id="loginform" action="http://www.rangelagos.com/wp-login.php" method="post">
        <p>
                <label>Username<br />
                <input type="text" name="log" id="user_login" class="input" value="" size="20" tabindex="10" /></label>
        </p>
        <p>
                <label>Password<br />
                <input type="password" name="pwd" id="user_pass" class="input" value="" size="20" tabindex="20" /></label>
        </p>
        <p class="forgetmenot"><label><input name="rememberme" type="checkbox" id="rememberme" value="forever" tabindex="90" /> Remember Me</label></p>
        <p class="submit">
                <input type="submit" name="wp-submit" id="wp-submit" value="Log In" tabindex="100" />
                <input type="hidden" name="redirect_to" value="http://www.rangelagos.com/wp-admin/" />
                <input type="hidden" name="testcookie" value="1" />
        </p>
</form>

<p id="nav">
<a href="http://www.rangelagos.com/wp-login.php?action=lostpassword" title="Password Lost and Found">Lost your password?</a>
</p>

</div>

<p id="backtoblog"><a href="http://www.rangelagos.com/" title="Are you lost?">&larr; Back to RangeLagos</a></p>

<script type="text/javascript">
try{document.getElementById('user_login').focus();}catch(e){}
</script>
</body>
</html>
```
that lacks of the following data at row 12: 
```html
<div id="login_error">  <strong>ERROR</strong>: Invalid username.<br />
</div>
```

Indeed, if I perform the HTTP POST request by cURL command:
```
curl 'http://www.rangelagos.com/wp-login.php' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: http://www.rangelagos.com' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: http://www.rangelagos.com/wp-login.php' -H 'Cookie: xLanguage_=en; wordpress_test_cookie=WP+Cookie+check' -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-GPC: 1' --data-raw 'log=admin&pwd=dsads&wp-submit=Log+In&redirect_to=http%3A%2F%2Fwww.rangelagos.com%2Fwp-admin%2F&testcookie=1'
```
I get the right HTTP response body containing also the piece of html above:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
<head>
        <title>RangeLagos &rsaquo; Log In</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel='stylesheet' href='http://www.rangelagos.com/wp-admin/css/login.css?ver=20081210' type='text/css' media='all' />
<link rel='stylesheet' href='http://www.rangelagos.com/wp-admin/css/colors-fresh.css?ver=20081210' type='text/css' media='all' />
</head>
<body class="login">

<div id="login"><h1><a href="http://wordpress.org/" title="Powered by WordPress">RangeLagos</a></h1>
<div id="login_error">  <strong>ERROR</strong>: Invalid username.<br />
</div>

<form name="loginform" id="loginform" action="http://www.rangelagos.com/wp-login.php" method="post">
        <p>
                <label>Username<br />
                <input type="text" name="log" id="user_login" class="input" value="admin" size="20" tabindex="10" /></label>
        </p>
        <p>
                <label>Password<br />
                <input type="password" name="pwd" id="user_pass" class="input" value="" size="20" tabindex="20" /></label>
        </p>
        <p class="forgetmenot"><label><input name="rememberme" type="checkbox" id="rememberme" value="forever" tabindex="90" /> Remember Me</label></p>
        <p class="submit">
                <input type="submit" name="wp-submit" id="wp-submit" value="Log In" tabindex="100" />
                <input type="hidden" name="redirect_to" value="http://www.rangelagos.com/wp-admin/" />
                <input type="hidden" name="testcookie" value="1" />
        </p>
</form>

<p id="nav">
<a href="http://www.rangelagos.com/wp-login.php?action=lostpassword" title="Password Lost and Found">Lost your password?</a>
</p>

</div>

<p id="backtoblog"><a href="http://www.rangelagos.com/" title="Are you lost?">&larr; Back to RangeLagos</a></p>

<script type="text/javascript">
try{document.getElementById('user_login').focus();}catch(e){}
</script>
</body>
</html>
```
Noted that this issue affect also websites not based on Wordpress. If you confirm the issue, please, could you fix it?

Thank you

**Comment by cuiweixie** [comment] 2022-03-11 00:48
same as https://github.com/golang/go/issues/51606?

**Comment by seankhliao** [comment] 2022-03-11 01:12
Duplicate of #51606

**Closed by seankhliao** 2022-03-11 01:12 UTC
