### ISSUE TITLE
Reading large files into memory consume more memory than expected

### ISSUE THREAD

**Issue by carlfn** [golang/go#16269] opened 2016-07-05 16:25 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6.2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
OS X Version 10.11.1 (15B42)

3. What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

I have a binary file that I read into a byte array. Binary file is 2Gb. When it's loaded into mem, the process mem usage is over 6GB. After about 5 minutes, the mem usage drops down. Wrote a simple app to reproduce and can do so each time.
```
package main

import (
    "flag"
    "fmt"
    "io/ioutil"
    "os"
    "os/signal"
    "runtime"
)

var fileToRead = flag.String("filetoread", "", "file to load into mem")

func main() {
    flag.Parse()

    arr, err := func() ([]byte, error) {
        file, err := os.Open(*fileToRead)
        if err != nil {
            panic(err)
        }
        defer file.Close()

        return ioutil.ReadAll(file)
    }()
    if err != nil {
        panic(err)
    }

    fmt.Printf("Read %d bytes", len(arr))

    exitChan := make(chan os.Signal)
    signal.Notify(exitChan, os.Interrupt)
    <-exitChan
}
```

4. What did you expect to see?
I would expect the mem usage to be similar to the size of the byte array allocated

5. What did you see instead?
When loading a 3GB file, I saw 6.5GB of memory use that stayed that way for 5-10 minutes. Added runtime.GC() after the printf statement with no affect. If I call debug.FreeOSMemory(), the memory is released after a few seconds.

**Comment by RLH** [comment] 2016-07-05 17:17
You can expect the Go GC to use 2X live memory which is what you are
seeing. You can run your program with GODEBUG=gctrace=1 if you want to
monitor the runtime's target heap size.  See https://golang.org/pkg/runtime/
for a more details.

**Comment by bradfitz** [comment] 2016-07-05 17:37
If the provided code is the only code, though, it's a little surprising: the `io/ioutil.ReadFile` function stats the file size and allocates the exact needed `[]byte` size. I'm not sure who would allocating the other 3.5GB of memory.

Or is there more code involved?

**Comment by fraenkel** [comment] 2016-07-05 18:01
Why not use ReadFile? It will pre-allocate the buffer based on the file size.

**Comment by carlfn** [comment] 2016-07-05 19:11
@bradfitz That code above reproduces as is.  Take any big binary file and read it in and you will see the mem usage spike in activity monitor.

**Comment by carlfn** [comment] 2016-07-05 19:14
@fraenkel ReadFile produces the exact same results.

**Comment by RLH** [comment] 2016-07-05 20:29
As far as the GC is concerned things are working as expected on my machine.
You create a 3 Gig data structure and the GC reserves a heap that is 2X
that or 6Gig. If you turn on GODEBUG=gctrace=1 do you see something
different?


rlh@rlh0:~/work/code/readfilebug$ GODEBUG=gctrace=1 ./issue16269
-filetoread=./x3Gig.txt
fileToRead= ./x3Gig.txt
gc 1 @0.004s 1%: 0.12+1.2+0.30 ms clock, 0.25+0/0.14/1.3+0.61 ms cpu,
4->4->2 MB, 5 MB goal, 12 P
gc 2 @0.006s 3%: 0.067+1.7+0.34 ms clock, 0.47+0/0.10/1.8+2.4 ms cpu,
6->6->4 MB, 7 MB goal, 12 P
gc 3 @0.009s 4%: 0.022+1.4+0.21 ms clock, 0.20+0/0.083/1.4+1.9 ms cpu,
12->12->8 MB, 13 MB goal, 12 P
gc 4 @0.011s 5%: 0.034+2.2+0.22 ms clock, 0.38+0/0.064/2.2+2.5 ms cpu,
24->24->16 MB, 25 MB goal, 12 P
gc 5 @0.016s 4%: 0.011+4.0+0.25 ms clock, 0.13+0/0.083/4.0+3.0 ms cpu,
48->48->32 MB, 49 MB goal, 12 P
gc 6 @0.025s 4%: 0.012+7.1+0.29 ms clock, 0.15+0/0.048/7.2+3.5 ms cpu,
96->96->64 MB, 97 MB goal, 12 P
gc 7 @0.041s 2%: 0.012+13+0.24 ms clock, 0.15+0/0.044/13+2.9 ms cpu,
192->192->128 MB, 193 MB goal, 12 P
gc 8 @0.072s 1%: 0.016+29+0.29 ms clock, 0.19+0/0.081/29+3.5 ms cpu,
384->384->256 MB, 385 MB goal, 12 P
gc 9 @0.135s 1%: 0.014+54+0.30 ms clock, 0.17+0/0.035/54+3.6 ms cpu,
768->768->512 MB, 769 MB goal, 12 P
gc 10 @0.259s 0%: 0.015+275+0.23 ms clock, 0.18+0/0.050/275+2.8 ms cpu,
1536->1536->1024 MB, 1537 MB goal, 12 P
gc 11 @0.947s 0%: 0.018+486+0.31 ms clock, 0.21+0/0.044/486+3.8 ms cpu,
3072->3072->2048 MB, 3073 MB goal, 12 P
gc 12 @1.931s 0%: 0.015+1183+0.28 ms clock, 0.18+0/0.056/1183+3.3 ms cpu,
6144->6144->4096 MB, 6145 MB goal, 12 P
Read 3209978043 bytes

^Crlh@rlh0:~/work/code/readfilebug$ ls -al x3Gig.txt
-rw-r----- 1 rlh eng 3209978043 Jul  5 16:09 x3Gig.txt

**Comment by carlfn** [comment] 2016-07-05 21:15
@RLH Thanks for looking into it.  My output is similar.  Is there a doc that I can read that explains the reasoning behind this?

```
gc 1 @0.009s 0%: 0.093+0.74+0.054 ms clock, 0.18+0/0.030/0.83+0.10 ms cpu, 4->4->2 MB, 5 MB goal, 4 P
gc 2 @0.011s 1%: 0.006+1.4+0.043 ms clock, 0.026+0/0.079/1.4+0.17 ms cpu, 6->6->4 MB, 7 MB goal, 4 P
gc 3 @0.015s 1%: 0.008+2.2+0.045 ms clock, 0.034+0/0.006/2.2+0.18 ms cpu, 12->12->8 MB, 13 MB goal, 4 P
gc 4 @0.027s 0%: 0.024+7.2+0.10 ms clock, 0.099+0/0/7.4+0.43 ms cpu, 24->24->16 MB, 25 MB goal, 4 P
gc 5 @0.052s 0%: 0.010+29+0.11 ms clock, 0.043+0/0/29+0.47 ms cpu, 48->48->32 MB, 49 MB goal, 4 P
gc 6 @0.126s 0%: 0.007+52+0.61 ms clock, 0.031+0/0.061/52+2.4 ms cpu, 96->96->64 MB, 97 MB goal, 4 P
gc 7 @0.279s 0%: 0.26+108+0.41 ms clock, 1.0+0/0.064/0.35+1.6 ms cpu, 192->192->192 MB, 193 MB goal, 4 P
gc 8 @0.601s 0%: 0.42+169+0.32 ms clock, 1.7+0/0.24/0.28+1.3 ms cpu, 448->448->384 MB, 449 MB goal, 4 P
gc 9 @1.332s 0%: 0.011+590+0.25 ms clock, 0.044+0/0.083/590+1.0 ms cpu, 896->896->512 MB, 897 MB goal, 4 P
gc 10 @2.798s 0%: 0.010+1355+0.12 ms clock, 0.041+0/0.10/1355+0.51 ms cpu, 1536->1536->1024 MB, 1537 MB goal, 4 P
gc 11 @6.184s 0%: 0.022+3382+4.4 ms clock, 0.089+0/24/19+17 ms cpu, 3072->3072->3072 MB, 3073 MB goal, 4 P
gc 12 @15.310s 0%: 0.17+25433+0.87 ms clock, 0.68+0/1.8/3.9+3.4 ms cpu, 7168->7168->6144 MB, 7169 MB goal, 4 P
Read 2776534696 bytes
```

**Comment by RLH** [comment] 2016-07-06 00:00
The blog from last August  https://blog.golang.org/go15gc  and this talk
from Gophercon https://www.youtube.com/watch?v=aiv1JOfMjm0  should answer
most of your questions.

**Comment by bradfitz** [comment] 2016-07-06 20:21
Sounds like this is working as intended. Closing.

**Closed by bradfitz** 2016-07-06 20:21 UTC
