### ISSUE TITLE
math: MaxUint64 doesn't return correct result but an error?

### ISSUE THREAD

**Issue by IIvyPy** [golang/go#38723] opened 2020-04-28 13:41 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go@1.12

</pre>

### What operating system and processor architecture are you using (`go env`)?

<pre>
$ amd64

</pre></details>

### What did you do?

<pre>
I just use the const in math packge: math.MaxUint64
</pre>

### What did you expect to see?

<pre>
18446744073709551615
</pre>

### What did you see instead?
<pre>
./main.go:169:29: constant 18446744073709551615 overflows uint
</pre>

**Comment by randall77** [comment] 2020-04-28 15:48
Show us your code. This code works fine:
```
package main

import "math"

func main() {
	var x uint = math.MaxUint64
	_ = x
}
```
The definition of `MaxUint64` as `1<<64-1` has no issues with overflow. It is a [constant expression](https://golang.org/ref/spec#Constants), which in Go is evaluated with arbitrary precision/range.

**Comment by IIvyPy** [comment] 2020-04-29 01:51
> Show us your code. This code works fine:
> 
> ```
> package main
> 
> import "math"
> 
> func main() {
> 	var x uint = math.MaxUint64
> 	_ = x
> }
> ```
> 
> The definition of `MaxUint64` as `1<<64-1` has no issues with overflow. It is a [constant expression](https://golang.org/ref/spec#Constants), which in Go is evaluated with arbitrary precision/range.

> Your code works well. 
> Here is my code.

```
package main

import "math"
func main() {
 	x := math.MaxUint64
	fmt.Println(x)
 }
```

**Comment by zhangfannie** [comment] 2020-04-29 03:06
Is this related to untyped constant?  The untyped constant math.MaxUint64 cannot infer the type from x that has no type. So it is given the default type int, so it overflows.

**Comment by bmkessler** [comment] 2020-04-29 03:54
Yes, the second example is due to the type inference with the untyped constant.
```go
x := math.MaxUint64
```
infers that `x` is an `int` and it overflows.

Also, the first example
```go
var x uint = math.MaxUint64
```
still overflows on any architecture where `uint` is 32-bit, e.g. arm.

If you want to assign `math.MaxUint64` to a variable you need to store it in a `uint64`

**Comment by randall77** [comment] 2020-04-29 15:27
Closing, this is working as intended.
As @bmkessler says, explicitly type your variable instead of using `:=`.

**Closed by randall77** 2020-04-29 15:27 UTC
Labels: WaitingForInfo

**Comment by ianlancetaylor** [comment] 2020-04-30 02:29
See also #19621, #23086, #23087, #23163.
