### ISSUE TITLE
runtime: TestStackGrowth "finalizer did not run" flakes

### ISSUE THREAD

**Issue by bradfitz** [golang/go#19381] opened 2017-03-03 15:38 UTC
@broady noticed TestStackGrowth "finalizer did not run" on freebsd-386 in https://github.com/golang/go/issues/18598#issuecomment-271679680

I just cleared all the Solaris builds from the dashboard and rebuilt them with 4x the CPU and they're now happy, except for:

https://build.golang.org/log/84bc7b4f864592e44e7964d8892ef2d9752f2754
```
--- FAIL: TestStackGrowth (49.50s)
	stack_test.go:114: finalizer did not run
FAIL
FAIL	runtime	102.054s
```

**Comment by aclements** [comment] 2017-06-07 16:16
Seems to have migrated to freebsd/arm. It's happening quite often:

`$ greplogs -dashboard -md -E "finalizer did not run" -l | tail -n 10`
[2017-06-05T19:55:31-6a42568/freebsd-arm-paulzhol](https://build.golang.org/log/3d1f54c3064f1000a74385495a4eec55d5b4f3d0)
[2017-06-05T19:56:34-51711d1/freebsd-arm-paulzhol](https://build.golang.org/log/068409061b68afeba3bc04a450bfafa2d4460794)
[2017-06-05T19:59:33-555d1e3/freebsd-arm-paulzhol](https://build.golang.org/log/a65cf98d1e0eabe51109912ce6f05e468a1c8684)
[2017-06-05T19:59:33-555d1e3/linux-arm-arm5spacemonkey](https://build.golang.org/log/b2726a2f396b389193acea30ddacd56f12fec429)
[2017-06-05T19:59:49-b1af539/freebsd-arm-paulzhol](https://build.golang.org/log/95ee27689c87364efd3e832e3454331af32cfc99)
[2017-06-05T22:42:48-2d86f49/freebsd-arm-paulzhol](https://build.golang.org/log/3b1db91bc42625dfc7e0b0f099286f95c554edb6)
[2017-06-05T22:42:48-2d86f49/linux-mips64](https://build.golang.org/log/4f3b511c6c2f6a90707aef54a5c355aa26eeca1e)
[2017-06-06T15:48:54-3a27f28/freebsd-arm-paulzhol](https://build.golang.org/log/638be20c8c0743659f282f707a250eed8dca6f86)
[2017-06-06T19:50:00-3c1914f/freebsd-arm-paulzhol](https://build.golang.org/log/05b16c6a82954cd77b5e594804552c314d341785)
[2017-06-06T20:20:41-a838191/freebsd-arm-paulzhol](https://build.golang.org/log/e12b915a25a66bfce591b840df82c2660f16a3f9)

It happens with some regularity on linux-arm-arm5spacemonkey, which has a gomote.

I haven't been able to reproduce the failure yet, though I have noticed that TestStackGrowth takes ~2.9 seconds to run on linux-arm-arm5spacemonkey, compared to 0.1 seconds on my laptop.

**Comment by aclements** [comment] 2017-06-07 16:29
> TestStackGrowth takes ~2.9 seconds to run on linux-arm-arm5spacemonkey, compared to 0.1 seconds on my laptop.

This appears to be because TestStackGrowth GC's ~770 times, but on linux-arm each GC scans an 8 MB heap, while on my linux/amd64 laptop the heap is under 1 MB.

**Comment by aclements** [comment] 2017-06-07 17:34
> This appears to be because TestStackGrowth GC's ~770 times, but on linux-arm each GC scans an 8 MB heap, while on my linux/amd64 laptop the heap is under 1 MB.

I believe this is a red herring. The 8MB comes from `numerators` in `vlop_arm_test.go`, but it's all non-scannable anyway. Adding `// +build ignore` to this file doesn't speed up TestStackGrowth.

**Comment by aclements** [comment] 2017-06-08 16:00
There's some useful discussion of this problem at #19805 (which I'm closing as a dup). @eliasnaur summarized it as:

> Increasing the timeout in stack_test.go:114 to 30 seconds or checking out 44ed88a (the parent of CL 37520) both make the problem go away.

CL 37520 made `runtime.GC` concurrent. It's odd that this would matter, since the test is effectively single-threaded (spread across a few synchronized goroutines). It's possible this is just slightly slower than STW GC and the ~770 GCs done between triggering the finalizer and passing the test take too long on slow hardware. Or it's possible this somehow perturbed finalizers, so the single forced GC cycle that's supposed to start the finalizer doesn't.

**Comment by aclements** [comment] 2017-06-09 14:10
Looking at the few builds on freebsd/arm since 45138 went in, all but one of them only say "finalizer did not run", which means the finalizer did start and it's just taking a long time to run.

**Comment by aclements** [comment] 2017-06-09 14:18
@eliasnaur, since you can reproduce this, could I get you to do a test for me on android/arm? Could you check out 44ed88a and run the runtime test with -v to get the run time of TestStackGrowth? I'd like to know how long TestStackGrowth took before CL 37520 to get a sense for whether it was just below the threshold before or if there was a more serious regression.

**Comment by eliasnaur** [comment] 2017-06-10 08:34
Of course. I ran `GOOS=android GOARCH=arm ../bin/go test -short -v runtime` and got (among others):

--- PASS: TestStackGrowth (3.43s)

If there's anything else you need, please ping me again.

**Comment by aclements** [comment] 2017-07-10 18:33
@eliasnaur, can you reproduce this if you just comment out the `t.Parallel()` at the top of `TestStackGrowth`?

**Comment by aclements** [comment] 2017-07-10 20:10
For my own record, this is what I've been using to try (unsuccessfully) to reproduce this:

```sh
VM=$(gomote create android-arm-wiko-fever)
gomote push $VM
gomote run $VM /bin/sh -c '
PATH=$PATH:$PWD/go/bin && 
cd go/src &&
./make.bash &&
cd runtime &&
go test -c &&
adb shell mkdir -p /data/local/tmp/goroot &&
adb push runtime.test /data/local/tmp/goroot/runtime.test'
gomote run $VM /bin/sh -c 'adb shell /data/local/tmp/goroot/runtime.test -test.short -test.cpu=1,2,4 -test.v' |& tee /tmp/x
```

I did notice once that on -cpu 4, TestStackGrowth took ~25 seconds (but did not timeout). The builder has been really uncooperative, though, so I've only managed to run that once.

**Comment by eliasnaur** [comment] 2017-07-11 10:54
Initially I couldn't reproduce the problem on tip nor on the version from my https://github.com/golang/go/issues/19805#issuecomment-297800640 comment. Then I remembered that the Android builder had a problem around the same time where stuck Go test processes would slowly clog up the device resources, slowing it down and triggering timing sensitive tests such as TestStackGrowth.

So, in summary: I can not reproduce the problem on a freshly rebooted device but I can reproduce the problem if I run CPU-heavy processes on it in parallel with the Go tests.

To answer your question, commenting out t.Parallel does help, even on a loaded device: 6 consecutive successful runs without t.Parallel and with t.Parallel the tests failed on the first run thereafter.

I since modified the android builder to reboot before every build, so I'm not sure there is more to do on this. If not, I'm sorry to have led you on a wild goose chase.

**Comment by aclements** [comment] 2017-07-11 13:25
> To answer your question, commenting out t.Parallel does help, even on a loaded device: 6 consecutive successful runs without t.Parallel and with t.Parallel the tests failed on the first run thereafter.

Thanks!

I think this all makes sense. The test started failing when I made `runtime.GC()` concurrent *because* it's a parallel test: before I made that change all of the expensive things in that test were STW so it wasn't *really* parallel, but after that change it was fighting with all of the other tests. Since concurrent GC claims 25% of the CPU, it probably started taking ~4 times longer to run.

> I since modified the android builder to reboot before every build, so I'm not sure there is more to do on this. If not, I'm sorry to have led you on a wild goose chase.

Not at all. It's still failing pretty regularly on the dashboard and it sounds like we now have a solution.

**Comment by aclements** [comment] 2017-07-17 18:59
This dropped from happening to a third of the commits to not happening at all with 286599f.

Thanks for the help @eliasnaur!

```
First observed d3f5e36 07 Mar 03:26 2017 (1482 commits ago)
Last observed  58ae050 11 Jul 14:01 2017 (53 commits ago)
0.00% chance failure is still happening
36% failure probability (515 of 1430 commits)
```

**Comment by bradfitz** [comment] 2017-12-01 19:11
@aclements, this is back.

Here's a NetBSD one: https://build.golang.org/log/7b248c375b767afdaa5d716c075734fed740af6d

Did any recent change to `runtime.GC()` affect this test?

```go
        // in finalizer                                                                                                                                                                   
        wg.Add(1)
        go func() {
                defer wg.Done()
                done := make(chan bool)
                var started uint32
                go func() {
                        s := new(string)
                        SetFinalizer(s, func(ss *string) {
                                atomic.StoreUint32(&started, 1)
                                growStack()
                                done <- true
                        })
                        s = nil
                        done <- true
                }()
                <-done
                GC()
                select {
                case <-done:
                case <-time.After(20 * time.Second):
                        if atomic.LoadUint32(&started) == 0 {
                                t.Log("finalizer did not start")
                        }
                        t.Error("finalizer did not run")
                        return
                }
        }()
        wg.Wait()
```

If `GC` blocks until finalizers are all done, should the `done` channel be buffered?

**Comment by aclements** [comment] 2017-12-01 20:09
Finalizers are still run asynchronously. `runtime.GC` doesn't block for them.

I will note that the failure indicates that the finalizer did *start*, it's just not done yet. Maybe we should add some debugging that prints how long the finalizer has been running for and how much progress it's made so we can tell whether it's just taking a long time or if it started really late.

Here are the recent failures:

[2017-09-22T20:07:52-f2ab41b/linux-386-clang](https://build.golang.org/log/88230fbf411d8658d438d3fda4521e26667c1a8d)
[2017-09-22T20:08:03-eb32dbc/linux-386-clang](https://build.golang.org/log/52fabf05858d73eaf389b7d95ee4a5cf986ed5e0)
[2017-09-22T20:08:16-0c01487/linux-386-clang](https://build.golang.org/log/3a38198d58e4848a0128565184f356af63a2dc19)
[2017-09-27T13:48:21-90fdc45/freebsd-arm-paulzhol](https://build.golang.org/log/3b3c973525f15dae842e068e98d180ea23e609a3)
[2017-10-06T06:49:40-07e36af/linux-mips64](https://build.golang.org/log/65aa31a595c23e0f2aa4c4a1f3d890d5e7ea78e3)
[2017-10-10T01:02:27-bb0bfd0/linux-mips](https://build.golang.org/log/81d9e5c608e36d1b14693071ef2124f35b535f0f)
[2017-11-21T19:13:52-2951f90/freebsd-arm-paulzhol](https://build.golang.org/log/91f7c774a2e3271e171e16e673d2123b511ba156)
[2017-11-23T16:45:24-b72678f/solaris-amd64-oraclerel](https://build.golang.org/log/950e64c1f75806dc347345c203b215b99bb87dd8)
[2017-12-01T01:16:45-7e394a2/netbsd-amd64-8branch](https://build.golang.org/log/024eb0ca81a226d794ccaa4b7aeedc487621c9a8)
[2017-12-01T07:09:54-f22cf71/netbsd-amd64-8branch](https://build.golang.org/log/7b248c375b767afdaa5d716c075734fed740af6d)

Are these builders just slow/overloaded?

**Comment by bradfitz** [comment] 2017-12-01 20:44
@aclements, the arm and mips builders might be slow, but shouldn't be overloaded. No clue about solaris. But netbsd-amd64 is a fresh isolated VM per build, and linux-386-clang is a fresh kubernetes pod per build. It shouldn't be oversubscribed or anything.

**Comment by ianlancetaylor** [comment] 2018-07-08 23:56
All the recent occurrences seem to be on emulators:

[2018-06-19T16:35:58-f125052/android-386-emulator](https://build.golang.org/log/c04616f17adde96ff72fb09d4177615e790826d3)
[2018-06-19T17:52:23-707ca18/android-amd64-emulator](https://build.golang.org/log/d341dae2f38b83d439ad258bc075d65939b8780c)
[2018-06-19T20:59:10-c6e455b/android-amd64-emulator](https://build.golang.org/log/7b5df13eea784a043501bcce04b61e69319a94cb)
[2018-06-19T21:36:56-500293d/android-amd64-emulator](https://build.golang.org/log/863140e6789638372445f95be8884bae4da4e9ce)
[2018-06-20T16:04:33-578e066/android-386-emulator](https://build.golang.org/log/413ac0498df5140db492d6823ef348ad45d90b42)
[2018-06-20T16:55:30-3ca5b7c/android-386-emulator](https://build.golang.org/log/d9206eb51c6ae33a05e27d715e25c2440594ebb8)
[2018-06-20T17:17:37-dd0e7a9/android-amd64-emulator](https://build.golang.org/log/a265e54962166a38fa25744d21dc93038b43a45e)
[2018-06-21T22:13:34-24fb2e0/android-amd64-emulator](https://build.golang.org/log/53f78a8557a984484a633042dc620508a5d6d255)
[2018-06-22T00:28:25-4991bc6/android-386-emulator](https://build.golang.org/log/5a5b73dbb20e00f1ad70f29e030e3d14c349df1d)
[2018-06-22T08:05:11-bedfa4e/android-amd64-emulator](https://build.golang.org/log/7227d8cfe4dc5a018a3faac7c2dfee59146ca947)

**Comment by ianlancetaylor** [comment] 2018-07-09 00:00
Spot checking a few I see things like

```
stack_test.go:135: finalizer started 21.053487s ago and finished 210 iterations
    stack_test.go:137: first growStack took 25.316309s
    stack_test.go:138: finalizer did not run
```

```
--- FAIL: TestStackGrowth (58.21s)
    stack_test.go:135: finalizer started 22.339328s ago and finished 242 iterations
    stack_test.go:137: first growStack took 14.320874s
    stack_test.go:138: finalizer did not run
```

The "first growStack" numbers suggest that 20 seconds is simply not enough given ordinary variation, at least not on an emulator.

But I don't know why the test no longer fails on ordinary systems.  It seems to have stopped failing after CL 81556, but I don't know why.

**Comment by n2vi** [comment] 2021-06-18 17:38
go1.17beta1 on OpenBSD6.9 amd64 (4GB NUQkit)

--- FAIL: TestStackGrowth (76.54s)
    stack_test.go:151: finalizer started 20.079434621s ago and finished 186 iterations
    stack_test.go:153: first growStack took 38.964539746s
    stack_test.go:154: finalizer did not run

This failed for me on two out of two tries. It worked fine on a larger memory OpenBSD machine.
If you're still tweaking things and want me to run tests, happy to do so.
Otherwise, I'm content to ignore and just use the new go; I haven't noticed any other problems.

**Comment by bcmills** [comment] 2022-01-12 14:45
Curiously, this seems not to have failed on the Go post-submit builders in literally years, but @thanm observed it on the new `freebsd-amd64-12_3` builders (https://github.com/golang/go/issues/49967#issuecomment-1011060070).

`greplogs --dashboard -md -l -e 'FAIL: TestStackGrowth' --since=2019-01-01`

[no results]

**Closed** 2022-01-19 16:24 UTC
Labels: Testing, NeedsInvestigation
