### ISSUE TITLE
cmd/go: mod vendor does not preserve execute permission for scripts

### ISSUE THREAD

**Issue by aanm** [golang/go#34965] opened 2019-10-17 20:08 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.1
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="linux"
</pre></details>

### What did you do?

main.go
```golang
package main

func main() {
        fmt.Println("hello go")
}
```
tools.go
```golang
// +build tools

package main

import (
        _ "k8s.io/code-generator"
)
```
go.mod
```
module aanm/go-test/test

go 1.13

require k8s.io/code-generator v0.0.0-00010101000000-000000000000

replace (
        k8s.io/code-generator => k8s.io/kubernetes/staging/src/k8s.io/code-generator v0.0.0-20191012044237-c97fe5036ef3
        k8s.io/kubernetes => k8s.io/kubernetes v1.16.2
)
```

run 
```
$ go mod tidy
$ go mod vendor
```

### What did you expect to see?
the file permissions of `generate-groups.sh` to be kept the same as the original file.
```bash
$ # original repo in the same tag v1.16.2
$ ls -la k8s.io/kubernetesstaging/src/k8s.io/code-generator/generate-groups.sh 
-rwx------. 1 aanm aanm 3837 Apr 25 12:25 staging/src/k8s.io/code-generator/generate-groups.sh
```

### What did you see instead?

```bash
$ ls -la vendor/k8s.io/code-generator/generate-groups.sh 
-rw-------. 1 aanm aanm 3837 Oct 17 21:59 vendor/k8s.io/code-generator/generate-groups.sh
```

**Comment by bcmills** [comment] 2019-10-18 13:03
This issue is probably the same root cause as reported in https://github.com/golang/go/issues/31481#issuecomment-500394654, but (per https://github.com/golang/go/issues/31481#issuecomment-502123143) let's keep this issue open to track that particular detail.

**Comment by rsc** [comment] 2019-10-24 18:50
We defined the Go module representation to be absolutely least common denominator across systems for portability. The Go module zip file is for dependencies that need to be downloaded and built by the go command. It is not meant to support anything more. By design, there are no permission bits, nor special files like symlinks, nor modification times. I still believe this is the right decision. We can go arbitrarily far in "preserving" file metadata, and the result would still miss some kinds of metadata and fail to recreate other metadata on some subset of systems (symlinks, odd file modification times, etc).

Tests that need special files (anything beyond files containing bytes) can write them to a temporary directory and configure them as they wish.

Install scripts can be invoked as `bash ./script` (or `cat script | bash`) instead of `./script`.

I don't believe this decision was wrong. But even if it were, it is a fundamental design decision made years ago that would be very hard to change now - it would invalidate all the checksums (if this extra information is important enough to preserve it would have to be checksummed too). It would have to be _very_ wrong to be worth the pain of correcting.

**Comment by jayconrod** [comment] 2019-10-24 20:14
Closing this as working as intended. Thanks for clarifying!

**Closed by jayconrod** 2019-10-24 20:14 UTC
Labels: NeedsInvestigation, modules
