### ISSUE TITLE
database/sql: Rows.Scan does not use the %w verb when wrapping errors

### ISSUE THREAD

**Issue by sfllaw** [golang/go#38099] opened 2020-03-26 22:44 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/slaw/.cache/go-build"
GOENV="/home/slaw/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/slaw/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build400385127=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.13.4 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.13.4
uname -sr: Linux 5.3.0-40-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.30-0ubuntu2.1) stable release version 2.30.
gdb --version: GNU gdb (Ubuntu 8.3-0ubuntu1) 8.3
</pre></details>

### What did you do?

[database/sql.Rows.Scan](https://pkg.go.dev/database/sql/?tab=doc#Rows.Scan) does not use the [%w verb](https://pkg.go.dev/fmt/?tab=doc#Errorf) when wrapping errors: https://github.com/golang/go/blob/8cb865c9197f0f383b0bde48e37faea7b7a2451d/src/database/sql/sql.go#L3078

Here is a motivating example involving a custom type that implements [database/sql.Scanner](https://pkg.go.dev/database/sql/?tab=doc#Scanner):

``` go
package main

import (
	"database/sql"
	"errors"
	"fmt"

	_ "github.com/mattn/go-sqlite3"
)

var ErrInvalid = errors.New("not an ASCII string")

type ASCII []byte

func (a ASCII) Scan(src interface{}) error {
	// Elide code that parses src into a.
	return ErrInvalid
}

func main() {
	db, err := sql.Open("sqlite3", ":memory:")
	if err != nil {
		panic(err)
	}
	defer db.Close()

	var a ASCII
	if err := db.QueryRow(`SELECT "世界"`).Scan(&a); err != nil {
		if !errors.Is(err, ErrInvalid) {
			panic(fmt.Errorf("unexpected error: %w", err))
		}
		fmt.Printf("err is ErrInvalid: %v\n", err)
	}
}
```

### What did you expect to see?

``` console
sfllaw@nyancat:~/go-sql-error-bug$ go run -trimpath main.go
err is ErrInvalid: sql: Scan error on column index 0, name "\"世界\"": not an ASCII string

```

### What did you see instead?

``` console
sfllaw@nyancat:~/go-sql-error-bug$ go run -trimpath main.go
panic: unexpected error: sql: Scan error on column index 0, name "\"世界\"": not an ASCII string

goroutine 1 [running]:
main.main()
	github.com/sfllaw/go-sql-error-bug@/main.go:30 +0x2f0
exit status 2
```

**Comment by andybons** [comment] 2020-03-27 20:33
Now that 1.12 is no longer supported, I think we can make this change. What do you think, @jba?

**Comment by jba** [comment] 2020-03-27 21:33
I'm for it. But this is technically breaking change, since anyone since 1.13 who was doing `errors.Is` on one of these errors could now get a different result. I don't know if that's an OK sort of change.

**Comment by andybons** [comment] 2020-03-28 19:19
Hm. I’m not a fan of breaking changes. Will follow up. This needs more investigation.

**Comment by neild** [comment] 2020-03-29 01:25
I don’t think this is a breaking change. It’s a behavioral change, and any behavioral change is of course subject to Hyrum’s Law, but I don’t believe this changes the documented properties of the package’s errors.

**Comment by sfllaw** [comment] 2020-03-29 11:46
@jba @andybons: I’m not sure how this would be interpreted as a breaking change. Because `fmt.Errorf` returns an `*errors.errorString`, the only real way to test for equality would be to call its `Error` method, which will result in the exact same string because of how the `%w` verb is defined.

If developers _are_ currently using `errors.Is` to check for a wrapped `sql.Scanner` error, then their code is currently broken because it will never be true. With the introduction of `errors.Is` and `errors.As`, I was surprised to find that this error was _not_ wrapped. I argue that changing the `fmt.Errorf` call to use `%w` is actually a non-breaking change, because this code has never worked with `Is` or `As`.

Someone might argue that these errors shouldn’t be wrapped because they might argue that this is exposing the internal details of the `Scan` method: [Errors and package APIs](https://blog.golang.org/go1.13-errors#TOC_5.). That doesn’t hold water, since the caller of `rows.Scan` knows which pointers are being passed in and therefore expects that there might be certain errors while scanning. If the errors are repackaged without wrapping, then the caller can only examine the `Error` string heuristicly.

**Comment by muhlemmer** [comment] 2020-08-10 14:44
I'm agreeing with @sfllaw's conclusion. `errors.Is` and `errors.As` can't be used against the returned error. Only string level equality can ben tested. If existing code is using string level equality testing, it won't break by switching to the `%w` verb:

````
var pgErr = errors.New("playground")

func main() {
	strErr := fmt.Errorf("Hello, %v", pgErr)
	if strings.Contains(strErr.Error(), pgErr.Error()) {
		fmt.Println(strErr)
	}
	
	wrpErr := fmt.Errorf("Hello, %w", pgErr)
	if strings.Contains(wrpErr.Error(), pgErr.Error()) {
		fmt.Println(wrpErr)
	}
	
	if errors.Is(wrpErr, pgErr) {
		fmt.Println(wrpErr)
	}
}
````

https://play.golang.org/p/uxpnS97ASZf

One of the affected use cases would be implementers of the [`sql.Scanner`](https://golang.org/pkg/database/sql/#Scanner) interface, like myself and the OP:

````
var (
	errEmptyJSON = errors.New("JSON result empty")
	errAssert    = errors.New("JSON assertion error")
	errParser    = errors.New("JSON parse error")
)

// Scan implements sql.Scanner
func (s *jsonScanner) Scan(v interface{}) (err error) {
	if v == nil {
		return errEmptyJSON
	}

	js, ok := v.([]byte)
	if !ok {
		return errAssert
	}

	if s.Value, err = s.p.ParseBytes(js); err != nil {
		return errParser
	}

	return nil
}
````

Using the above pattern, I would expect to can do something like:


````
       	var js jsonScanner

	err = rt.Tx.QueryRowContext(rt.Ctx, query, args...).Scan(&js)
	switch {
	case err == nil:
	case errors.Is(err, errEmptyJSON):
		return []*shop.Article{}, nil
	default:
		return nil, status.Error(codes.Internal, errDB)
	}
````

**Comment by andybons** [comment] 2020-08-10 15:00
@neild @jba what do y’all think? Should we do this early in the 1.16 cycle and see what breaks?

**Comment by neild** [comment] 2020-08-10 17:14
I think we should do this.

I expect that this will break some tests using `reflect.DeepEqual` on errors returned by `Rows.Scan`. This is fine, but is best to do early in cycle.

I don't expect any breakage from code using `errors.Is`, since as @sfllaw and others note this would never have worked in the first place. Even if such code exists, I do not believe this change is a violation of the compatibility guarantee since it makes no backwards-incompatible changes to the documented properties of `database/sql`'s errors.

**Comment by andybons** [comment] 2020-08-10 22:48
sgtm. marking as early-in-cycle

**Comment by dmitshur** [comment] 2020-08-12 17:39
This issue is currently labeled as early-in-cycle for Go 1.16.
That [time is now](https://groups.google.com/d/msg/golang-dev/qtxOW0x4Rrw/0rB32h12BQAJ), so this is a friendly ping so the issue is looked at again.

**Comment by muhlemmer** [comment] 2020-08-13 08:14
I'm working now on a CL, should submit in the next hour or so.

**Comment by sfllaw** [comment] 2020-08-13 09:26
@muhlemmer Suggestion: we should document how the Scanner's error propagates through the stack.

**Comment by muhlemmer** [comment] 2020-08-13 10:19
Ok, I will adapt the documentation and amend the change later today. 

On 13 August 2020 12:26:23 EEST, Simon Law <notifications@github.com> wrote:
>@muhlemmer Suggestion: we should document how the Scanner's error
>propagates through the stack.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/golang/go/issues/38099#issuecomment-673369218

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Closed** 2020-08-14 17:47 UTC
Labels: NeedsFix, early-in-cycle
