### ISSUE TITLE
x/pkgsite: stale go-source meta tag information

### ISSUE THREAD

**Issue by myitcv** [golang/go#47335] opened 2021-07-22 07:21 UTC
### What is the URL of the page with the issue?

https://pkg.go.dev/cuelang.org/go/cue#Attribute

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
</pre>

### Screenshot

n/a

### What did you do?

Clicked on the `Attribute` identifier to jump to the source code.

### What did you expect to see?

To navigate to the GitHub-based source code browser, specifically https://github.com/cue-lang/cue/blob/master/cue/attribute.go#L113. 

### What did you see instead?

A broken GerritHub link at https://review.gerrithub.io/cue-lang/cue/+/master/cue/attribute.go.

The `go-source` meta tag has been updated for `cuelang.org/go`, but I'm unclear of the period of cache refresh for such meta tags, or how to trigger/force a refresh:

```
$ curl -s https://cuelang.org/go/cue?go-get=1 | grep go-source
<meta name="go-source" content="cuelang.org/go https://github.com/cue-lang/cue https://github.com/cue-lang/cue/blob/master{/dir} https://github.com/cue-lang/cue/blob/master{/dir}/{file}#L{line}">
```

**Comment by julieqiu** [comment] 2021-07-22 12:56
I manually refreshed the source links for https://pkg.go.dev/cuelang.org/go. Closing as a duplicate of #46203.

**Closed by julieqiu** 2021-07-22 12:56 UTC
Labels: NeedsInvestigation, pkgsite

**Comment by myitcv** [comment] 2021-07-22 16:01
Oops, sorry, missed the dup. Thanks for fixing, @julieqiu!
