### ISSUE TITLE
crypto/x509: Mac without CGO is very slow, times out with large numbers of certs

### ISSUE THREAD

**Issue by deitch** [golang/go#38215] opened 2020-04-02 11:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTOS="darwin"

</pre></details>

### What did you do?

1. Run on a mac with a large but not unreasonable number of certificates. 
1. Try to connect to https endpoint with a binary compiled with `CGO_ENABLED=0`
1. Set a connection timeout of a few seconds
1. Watch the connection time out

Even without a timeout, the initial response can take many seconds. The default mac has ~22 certificates and it can take 3-4 seconds. Any corporate system with more certs can take many multiples. 

### What did you expect to see?

Reasonable return times

### What did you see instead?

Long waits and timeouts.

### Lots More Detail

I spent quite some time tracking it down. When compiling with `CGO_ENABLED=1`, which is fine, although may require more tools installed and, critically, makes cross-compiling and some CI nearly impossible, the lookup time is roughly well below O(n). When compiling with `CGO_ENABLED=0`, which is desired when possible, every cert in the system increases the time to verify the server cert.

The core code issue is in [root_darwin.go](https://github.com/golang/go/blob/master/src/crypto/x509/root_darwin.go), and specifically [execSecurityRoots()](https://github.com/golang/go/blob/master/src/crypto/x509/root_darwin.go#L55).

It does the following (simplified):

1. gets the root certs via exec'ing `/usr/bin/security` with appropriate args
1. checks each of the root certs by exec'ing `/usr/bin/security` on it with appropriate args

The above is, essentially, O(n), and rises linearly with the number of certs. The comments [here](https://github.com/golang/go/blob/master/src/crypto/x509/root_darwin.go#L49-L54) indicate that it should be optimized to reasonably close to with `CGO`, but I haven't found that to be the case. I have had several runs where 160 certs and a timeout of 5 seconds would, well, time out. 

I created a repo with a program which recreates it. It also includes directions and output from my mac. In my case, it was 244ms for CGO and 1.7s for no CGO. I worked with someone who had ~160 certs (not unreasonable); it took well over 5 seconds.

[repo here](https://github.com/deitch/golang-mac-x509-test)

**Comment by deitch** [comment] 2020-04-02 11:23
cc @justincormack @thaJeztah

**Comment by deitch** [comment] 2020-04-02 11:28
Aha. Just came across #32604 (and am not at all surprised to find @zx2c4 on it :-) )

**Comment by deitch** [comment] 2020-04-02 11:28
Is this a duplicate? In this case, it isn't just about optimization, but about real issues that arise because of that.

**Comment by deitch** [comment] 2020-04-02 12:29
I actually am unsure what the logic is doing and why it is necessary. As far as I can tell, it does the following:

1. Get the ID of all the [user certs for the current user](https://github.com/golang/go/blob/801cd7c84d42dcf18256416524aa0d31d6305830/src/crypto/x509/root_darwin.go#L281) and [admin certs](https://github.com/golang/go/blob/801cd7c84d42dcf18256416524aa0d31d6305830/src/crypto/x509/root_darwin.go#L284) that have non-default trust policies, and save them
1. Get all of the [certs](https://github.com/golang/go/blob/801cd7c84d42dcf18256416524aa0d31d6305830/src/crypto/x509/root_darwin.go#L131) and [system certs](https://github.com/golang/go/blob/801cd7c84d42dcf18256416524aa0d31d6305830/src/crypto/x509/root_darwin.go#L138) across, well, everywhere
1. For each of those many certs:
    * if it is a system cert, keep it
    * if it is a user or admin cert and in the list of "certs with policies", [verify it against the "ssl" policy](https://github.com/golang/go/blob/801cd7c84d42dcf18256416524aa0d31d6305830/src/crypto/x509/root_darwin.go#L201); if it passes, keep it - **this is the part that takes a lot of time and grows linearly**
1. return the ones that passed

The part that surprise me is:

* is there not a single call (exec or system call) that just says, "give me all of the valid root certs for ssl"?
* is there a way to just get that info from the output of `/usr/bin/security trust-settings-export`?

In the end, we just return the system certs and all of those from the two `trust-settings-export` calls that pass to be used for ssl.

**Comment by FiloSottile** [comment] 2020-04-02 18:12
Yeah, the nocgo fallback is absolutely not great. The policy logic is extremely complex and we've gotten it wrong a few times before. The APIs don't help us.

The two options here are:

1. run `trust-settings-export`, parse XML, apply similar but not identical logic to the cgo one to evaluate the policies;
2. figure out how to call into Security.framework without cgo.

I'd rather keep only one copy of this logic, so I want to try (2) before (1). So yeah, duplicate of #32604, but I appreciate the detailed user impact report, it helps with prioritization.

**Closed by FiloSottile** 2020-04-02 18:12 UTC

**Comment by deitch** [comment] 2020-04-02 18:18
> I'd rather keep only one copy of this logic

I agree. Given the material impact it can have on end-users, and it doesn't look like option 2 is happening too soon (I am very happy to be wrong), can we consider some optimization to the nocgo fallback to carry us through?

Also, is it worth documenting somewhere reasonably prominent, maybe in `net/http` and/or `crypto/x509`? You don't want to know how long I spent digging into it, trying to understand why I had issues with user on macbook A and not on macbook B. :-(
I figure I am not the only one.

> So yeah, duplicate of #32604, but I appreciate the detailed user impact report, it helps with prioritization

No problem. :-)

**Comment by FiloSottile** [comment] 2020-04-02 18:21
> it doesn't look like option 2 is happening too soon (I am very happy to be wrong)

Let me see what I can do =)

It really is a bad and inconsistent experience, sorry about that.

**Comment by deitch** [comment] 2020-04-02 18:24
I can try and give a hand. I am not sure if I captured the logic and options correctly [here](https://github.com/golang/go/issues/38215#issuecomment-607815948)

**Comment by FiloSottile** [comment] 2020-04-02 18:28
We'd basically drop the nocgo code and port the cgo one to hardcoded references to Security.framework. The hard part is in what the linker needs to do for that, so I reached out to the cmd/link owners. I'll keep #32604 up to date!

**Comment by deitch** [comment] 2020-04-02 18:37
Thanks. I subscribed to that one. 

If it really is hard, perhaps we can just do what you suggested and parse the xml, buy is some breathing room?

**Comment by FiloSottile** [comment] 2020-04-02 18:50
We'll see. I would really regret depending on encoding/xml in crypto/x509 and rewriting all that logic.

**Comment by deitch** [comment] 2020-04-16 07:20
FWIW, I ran the gotip version that @FiloSottile put up in the link. It passed all tests, and the time is effectively identical to cgo. Also had someone whose cert store is quite large and it took up to 10s before with nocgo. With this patch, 1.3s. Much better!
