### ISSUE TITLE
Proposal: Have replace statements in a separate file instead of go.mod

### ISSUE THREAD

**Issue by metakeule** [golang/go#38775] opened 2020-04-30 18:09 UTC
Since this proposal is pretty simple, I skip the lengthy proposal steps.

**The problem:** When developing on different dependend packages in different repositories, we use `replace` statements inside `go.mod`. Since `go.mod` is checked into the repository, when publishing the package, the replace statements have to be removed to that the cloning user doesn't get them.

**The solution:** If the replace statements were inside a separate file, the developers could simply not check them into the repository. Also some other person working on local modified dependencies could add his own overrides without messing with repository files.

**Proposed file name:** `overrides.mod` or `local.mod` or  `go.local` or whatever

For compatibility reasons, the replace statements inside go.mod could stay and behave just as today, but would be superceeded by a corresponding entry in `overrides.mod`.

**Comment by myitcv** [comment] 2020-04-30 18:22
Related to/dup of https://github.com/golang/go/issues/26640

**Comment by bcmills** [comment] 2020-05-01 02:33
Duplicate of #26640

**Closed by bcmills** 2020-05-01 02:33 UTC
Labels: Proposal
