### ISSUE TITLE
affected/package: testing

### ISSUE THREAD

**Issue by domenicomastrangelo** [golang/go#57215] opened 2022-12-09 19:29 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

1.19.1

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dome/.cache/go-build"
GOENV="/home/dome/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dome/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dome/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dome/go_poc/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3529259481=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Created an application with a function and a test for that function

### What did you expect to see?

The test fails and the correct file at line x is opened for debugging the origin of the error

### What did you see instead?

Testing the application, if the error occurrs in an imported library, the editor of choice (in my case VIM v9) tries to open the file in the wrong path.

###  POC

```
package main

import "github.com/gofiber/fiber/v2"

func main() {
}

func Example(c *fiber.Ctx) error {
	c.Write([]byte("Hello, World!"))

	return nil
}
```

```
package main

import (
	"encoding/json"
	"io"
	"net/http/httptest"
	"testing"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/utils"
)

func TestMain(t *testing.T) {

	app := fiber.New()

	app.Get("/", Example)

	req := httptest.NewRequest("GET", "/", nil)
	res, err := app.Test(req)

	body, err := io.ReadAll(res.Body)
	utils.AssertEqual(t, nil, err)

	var data interface{}
	err = json.Unmarshal(body, &data)

	utils.AssertEqual(t, nil, err)
}
```

### Change proposal

The function "decorate" of testing/testing.go contains this part:

```
func (c *common) decorate(s string, skip int) string {
	frame := c.frameSkip(skip)
	file := frame.File
	line := frame.Line
	if file != "" {
		// Truncate file name at last file name separator.
		if index := strings.LastIndex(file, "/"); index >= 0 {
			file = file[index+1:]
		} else if index = strings.LastIndex(file, "\\"); index >= 0 {
			file = file[index+1:]
		}
	} else {
		file = "???"
	}
        .....
```

I suggest updating it to

```
func (c *common) decorate(s string, skip int) string {
	frame := c.frameSkip(skip)
	file := frame.File
	line := frame.Line
	if file == "" {
		file = "???"
	}
        ...
```

This way the file pointed out in the test error message will be complete of the full path and the editor will be able to open it correctly

### EDIT

Added PR

https://github.com/golang/go/pull/57216

**Comment by seankhliao** [comment] 2022-12-09 21:06
Duplicate of #47399

**Closed by seankhliao** 2022-12-09 21:06 UTC
