### ISSUE TITLE
cmd/doc: support output of full documentation for a package or identifier

### ISSUE THREAD

**Issue by mpx** [golang/go#25595] opened 2018-05-27 16:01 UTC
Removal of CLI support in `godoc` is being considered in #25443. Support for full package documentation is the main reason I continue to use `godoc` (otherwise I use `go doc`).

Please consider adding support to output full package documentation in `go doc`. This would make it much easier to review all the documentation at once to get a proper understanding of a package, as well as arbitrary searches within the full package text.

Perhaps implement a `-v` flag that outputs full documentation for a package or identifier (similar to `godoc`).

**Comment by meirf** [comment] 2018-05-27 16:28
Duplicate of https://github.com/golang/go/issues/18807 ?

**Comment by rsc** [comment] 2018-06-11 20:45
@robpike, any ideas for some flag to 'go doc' to mean 'print everything like godoc does'? The overall idea is that eventually we could deprecated 'godoc' for command-line queries completely.

**Comment by rsc** [comment] 2018-06-11 20:45
Maybe `go doc -all`

**Comment by robpike** [comment] 2018-06-24 04:23
A "-all" flag sounds good for the next release.

**Comment by lukmdo** [comment] 2018-08-02 14:41
> go version go1.10.3

`go doc`  already has 
> -u	show unexported symbols as well as exported

**Comment by agnivade** [comment] 2018-10-11 06:13
Marking this as release blocker, now that godoc CLI support is removed. Folks will be miffed if we just point them to a `go doc` which is not feature equivalent with `godoc`. 

This was also raised in a golang-nuts [thread](https://groups.google.com/forum/#!searchin/golang-nuts/godoc$201.12%7Csort:date/golang-nuts/SSv5vhCi2zs/vS3wB03RBAAJ), so ensuring this gets looked at.

**Closed** 2018-10-31 00:34 UTC
Labels: FeatureRequest, NeedsFix, release-blocker
