### ISSUE TITLE
panic: JavaScript error: Permission denied to access object WebAssembly

### ISSUE THREAD

**Issue by mariantatarau90** [golang/go#29184] opened 2018-12-12 07:46 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
I don't know

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/marian/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/marian/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/q2/5580lrgn561btt8jlzgrzb8h0000gp/T/go-build251665520=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I try to run main example of wasm from https://github.com/golang/go/blob/master/misc/wasm/wasm_exec.html. First get me some error but i found that is a issue in mac and i change the code with

const go = new Go();
fetch(wasmPath).then((response) => {
    return response.arrayBuffer();
}).then((bytes) => {
    return WebAssembly.instantiate(bytes, go.importObject);
}).then((result) => {
   go.run(result.instance);
}).catch((err) => {
    console.log("err", err)
});
 And seems to work
### What did you expect to see?

> Hello, WebAssembly!

### What did you see instead?

> Hello, WebAssembly!
> panic: JavaScript error: Permission denied to access object
> goroutine 1 [running]:
> syscall/js.Value.New(0x7ff8000300000011, 0xc048b30, 0x3, 0x3, 0x0)
> 	/usr/local/Cellar/go/1.11.2/libexec/src/syscall/js/js.go:313 +0x7
> syscall/js.typedArrayOf(0x114c0, 0xc00a080, 0x114c0)
> 	/usr/local/Cellar/go/1.11.2/libexec/src/syscall/js/typedarray.go:78 +0x3d
> syscall/js.TypedArrayOf(0x114c0, 0xc00a080, 0x114c0)
> 	/usr/local/Cellar/go/1.11.2/libexec/src/syscall/js/typedarray.go:50 +0x2
> syscall.Write(0x1, 0xc04c000, 0x14, 0x20, 0x76, 0x0, 0x0)
> 	/usr/local/Cellar/go/1.11.2/libexec/src/syscall/fs_js.go:396 +0x7
> internal/poll.(*FD).Write(0xc02e0c0, 0xc04c000, 0x14, 0x20, 0x0, 0x0, 0x0)
> 	/usr/local/Cellar/go/1.11.2/libexec/src/internal/poll/fd_unix.go:268 +0x19
> os.(*File).write(0xc00c020, 0xc04c000, 0x14, 0x20, 0x3b8e0, 0x76, 0x0)
> 	/usr/local/Cellar/go/1.11.2/libexec/src/os/file_unix.go:266 +0x4
> os.(*File).Write(0xc00c020, 0xc04c000, 0x14, 0x20, 0x14e720, 0x0, 0x1286a0)
> 	/usr/local/Cellar/go/1.11.2/libexec/src/os/file.go:145 +0x7
> fmt.Fprintln(0x3bf00, 0xc00c020, 0xc024788, 0x1, 0x1, 0x1a2e0, 0x14e30001, 0xc00e1e0)
> 	/usr/local/Cellar/go/1.11.2/libexec/src/fmt/print.go:255 +0x6
> fmt.Println(0xc024788, 0x1, 0x1, 0x2e28e, 0x0, 0x0)
> 	/usr/local/Cellar/go/1.11.2/libexec/src/fmt/print.go:264 +0x2

Attention: I try to run webassembly in a firefox extension!

Any idea about this issue? sorry for my bad english

**Comment by agnivade** [comment] 2018-12-12 08:34
The first error is probably to do with the "application/wasm" type. Your webserver needs to set this mime type when serving the .wasm file.

What is the wasm_exec.js you are using ? Is that from master or 1.11.2 ? You should always use wasm_exec.js corresponding to your Go version.

Can you show us the code that you are compiling ?

Does the code work when you are _not_ running inside the extension ? Does the extension have appropriate permissions necessary for it to run ?

**Comment by mariantatarau90** [comment] 2018-12-12 08:52
Hi @agnivade,
I'm sure that i use correct version of wasm_exec because i had already this issue and i solve it.
I compile only a "Hello word". 
```
package main

import "fmt"

func main() {
	fmt.Println("Hello, WebAssembly!")
}
```
Yes when i'm not in extension works fine. Yes i think the permission are correctly, i read this doc https://github.com/WebAssembly/content-security-policy/blob/master/proposals/CSP.md#behavior-of-current-implementations

**Comment by agnivade** [comment] 2018-12-12 09:34
Can you tell us the extension so that we can try to reproduce this at our side ? 

Btw the CSP is set by the web server. If it works without the extension, then CSP should not be an issue.

**Comment by neelance** [comment] 2018-12-22 18:04
The stack trace suggests that the `new Uint8Array(...)` fails with the error `Permission denied to access object`. This is indeed strange, but it rather looks like a bug in the permission handling of content scripts in Firefox than an issue on Go's end. You should file an issue with the Firefox project.

**Comment by neelance** [comment] 2019-01-06 16:34
Closing this since it seems to be an issue with Firefox, not Go.

**Closed by neelance** 2019-01-06 16:34 UTC
Labels: Arch-Wasm, NeedsInvestigation
