### ISSUE TITLE
all: C++ like footgun when taking references in a loop

### ISSUE THREAD

**Issue by VinTarZ** [golang/go#60173] opened 2023-05-13 08:59 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.20
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
windows, linux, go playground
</pre></details>

### What did you do?

https://go.dev/play/p/GLz7hZHR_RT

### What did you expect to see?

https://go.dev/play/p/E0E20KO4gGw

### What did you see instead?

C++ like footgun

**Comment by seankhliao** [comment] 2023-05-13 09:04
Duplicate of #60078

**Closed by seankhliao** 2023-05-13 09:04 UTC
