### ISSUE TITLE
x/website: Broken link on "tidy-web" post

### ISSUE THREAD

**Issue by kzrl** [golang/go#48109] opened 2021-09-01 06:31 UTC
### What is the URL of the page with the issue?
 https://go.dev/blog/tidy-web
 
 
### What is your user agent?

 
 Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 
### Screenshot
![broken_link](https://user-images.githubusercontent.com/738027/131622870-edf869ec-6670-41ca-a583-7ed7bd650a59.png)

 
 
### What did you do?
Clicked the link, got a 404 page.

 
### What did you expect to see?
 https://go.dev
 
 
### What did you see instead?
a link to "/blog/blog/go.dev"

**Comment by seankhliao** [comment] 2021-09-01 06:53
Duplicate of #47975

**Closed by seankhliao** 2021-09-01 06:53 UTC
