### ISSUE TITLE
cmd/cgo: inconsistent definitions for C.uint

### ISSUE THREAD

**Issue by navytux** [golang/go#26743] opened 2018-08-01 12:10 UTC
Please answer these questions before submitting your issue. Thanks!

#### What did you do?

I was trying to rebuild my software with gotip and got the following error:

```
# github.com/DataDog/czlib
cgo: inconsistent definitions for C.uint
FAIL    lab.nexedi.com/kirr/neo/go/zodb/btree [build failed]
```

The build is working with Go1.10 and earlier releases.

#### What did you expect to see?

Builds ok.

#### What did you see instead?

The build for github.com/DataDog/czlib fails with `cgo: inconsistent definitions for C.uint` error. I've extracted the minimal reproducer:

`fastzlib.h`:
```
#ifndef _A_XXX_H
#define _A_XXX_H

typedef unsigned int uint;
void c_compress2(char *input, uint length);

#endif
```

`fastzlib.c`:
```
#include "fastzlib.h"

void c_compress2(char *input, uint length) {
        return;
}
```

`fastzlib.go`:
```
package czlib

/*
#include "fastzlib.h"
*/
import "C"

func Compress(input []byte) {
        C.c_compress2(nil, C.uint(len(input)))
}
```
`zstream.go`  (EDIT: originally posted `fastzlib.go` content here by mistake):
```
package czlib
  
/*
void zstream_set_in_buf(char *strm, void *buf, unsigned int len) {
        return;
}
*/
import "C"

func setInBuf(buf []byte, size int) {
        C.zstream_set_in_buf(nil, nil, C.uint(size))
}
```

#### Does this issue reproduce with the latest release (go1.10.3)?

No, it is a regression:

```
kirr@deco:~/src/neo/src/github.com/DataDog/czlib/a$ gotip build
# github.com/DataDog/czlib/a
cgo: inconsistent definitions for C.uint
kirr@deco:~/src/neo/src/github.com/DataDog/czlib/a$ go build
kirr@deco:~/src/neo/src/github.com/DataDog/czlib/a$ echo $?
0
```
```
kirr@deco:~/src/neo/src/github.com/DataDog/czlib/a$ gotip version
go version devel +6b9c782f9f Wed Aug 1 00:57:00 2018 +0000 linux/amd64
kirr@deco:~/src/neo/src/github.com/DataDog/czlib/a$ go version
go version go1.10.3 linux/amd64
```

#### System details

```
go version devel +6b9c782f9f Wed Aug 1 00:57:00 2018 +0000 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kirr/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kirr/go"
GOPROXY=""
GORACE=""
GOROOT="/home/kirr/src/tools/go/gotip"
GOTMPDIR=""
GOTOOLDIR="/home/kirr/src/tools/go/gotip/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version devel +6b9c782f9f Wed Aug 1 00:57:00 2018 +0000 linux/amd64
GOROOT/bin/go tool compile -V: compile version devel +6b9c782f9f Wed Aug 1 00:57:00 2018 +0000
uname -sr: Linux 4.17.0-1-amd64
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (buster)
Release:	testing
Codename:	buster
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Debian GLIBC 2.27-5) stable release version 2.27.
gdb --version: GNU gdb (Debian 8.1-4) 8.1
```

**Comment by ianlancetaylor** [comment] 2018-08-01 13:51
CC @randall77

**Comment by ianlancetaylor** [comment] 2018-08-01 13:51
What does `gcc --version` print?

**Comment by ianlancetaylor** [comment] 2018-08-01 13:55
Thanks for the reproduction case.  Unfortunately it doesn't build:

```
> go build
# _/tmp/x/src/a
./zstream.go:8:6: Compress redeclared in this block
	previous declaration at ./fastzlib.go:8:23
```

When I change the name of `Compress` in one of the files it builds without error using GCC 7.3.0.

**Comment by ianlancetaylor** [comment] 2018-08-01 14:30
Can you see if your issue is fixed on tip now that CL 127156 is committed?

**Comment by navytux** [comment] 2018-08-01 18:38
Thanks for feedback. My gcc is:

```
kirr@deco:~$ gcc --version
gcc (Debian 8.2.0-1) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The sample indeed does not build, after I tried downloading it afresh from here in another directory. I turned out I've made a copy-paste error. Here is correct `zstream.go` which should have been pasted in the first place:

`zstream.go`:
```
package czlib
  
/*
void zstream_set_in_buf(char *strm, void *buf, unsigned int len) {
        return;
}
*/
import "C"

func setInBuf(buf []byte, size int) {
        C.zstream_set_in_buf(nil, nil, C.uint(size))
}
```

(appologize for the pasting mistake on my side).

The problem persists with CL 127156 applied:


```
kirr@deco:~/tmp/trashme/bug$ gotip version
go version devel +b8669ef1ce Wed Aug 1 14:29:58 2018 +0000 linux/amd64
```

```
kirr@deco:~/tmp/trashme/bug$ gotip build
# _/home/kirr/tmp/trashme/bug
cgo: inconsistent definitions for C.uint
```

**Comment by navytux** [comment] 2018-08-01 18:40
I've edited original issue description and put zstream.go content into there.

**Comment by ianlancetaylor** [comment] 2018-08-01 18:46
Thanks, I can recreate the problem now.

**Comment by navytux** [comment] 2018-08-01 18:49
Thanks, good.

**Comment by ianlancetaylor** [comment] 2018-08-01 18:51
I think it's because cgo has its own definition of `uint` in `nameToC`, and the header file has `typedef unsigned int uint;`. 

Shorter repro:

a.go:

```Go
package a

// typedef unsigned int uint;
// int C1(uint x) { return x; }
import "C"

var V1 = C.C1(0)
```

b.go:

```Go
package a

import "C"

var V2 C.uint
```

**Closed** 2018-08-01 20:42 UTC
Labels: NeedsInvestigation, release-blocker

**Comment by navytux** [comment] 2018-08-02 11:38
Thanks for the fix.
