### ISSUE TITLE
proposal: Review the use of CanonicalMIME on http.Header

### ISSUE THREAD

**Issue by pho** [golang/go#45704] opened 2021-04-22 16:27 UTC
The [`Set()` ](https://golang.org/src/net/http/header.go?s=997:1035#L26) method of a `http.Header` transforms the key using textproto.CanonicalMIMEHeaderKey, so `accept-encoding` turns into `Accept-Encoding` and such, which looks way better to a human eye, but its not needed since the [HTTP RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) specifies that the field names are case-insensitive. 
This canonical transformation does not match the [IANA Permanent Message Header Field Names](https://www.iana.org/assignments/message-headers/message-headers.xhtml) either, which is not enforced for the same reason as before, but seems like a good reference for "correct" key names

I am aware that the comment on (http.Header).Set() already says that non-canonical headers can be added accessing the underlying map directly, but this whole transformation sounds kinda arbitrary to me since its not needed and is not following the IANA names either, so I was wondering if this is something that could be removed and left to the linter for speedup or maybe tuned to match the IANA listing (which would be more complex and would need maintenance)

Disclaimer: I ended up here because of a (bad) server which is expecting the `Sec-WebSocket-*` headers written as such, and rejecting the CanonicalMIME version of it :(

**Comment by seankhliao** [comment] 2021-04-22 18:32
Duplicate of #18495

**Closed by seankhliao** 2021-04-22 18:32 UTC
Labels: Proposal
