### ISSUE TITLE
cmd/compile: trying to call init() from a different file should give a more specific error message

### ISSUE THREAD

**Issue by eric-smithson** [golang/go#23963] opened 2018-02-20 21:55 UTC
### What version of Go are you using (`go version`)?
go1.8.3 linux/amd64

### Does this issue reproduce with the latest release?
I don't know.

### What operating system and processor architecture are you using (`go env`)?
amd64

### What did you do?
I tried to call an `init()` function from a different go file but within the same package.

### What did you expect to see?
I expected more specific feedback about what I did wrong.

### What did you see instead?
It just told me that init() wasn't defined. Which was very confusing because I had other lowercase functions I was able to call package-wide no problem. I now know that lowercase `init()` is a special function but it wasn't obvious from the error message.

**Comment by eric-smithson** [comment] 2018-02-20 21:58
Also if someone could be inclined to tell me how to fix this I'd like to try fixing this myself. 😛

**Comment by bradfitz** [comment] 2018-02-20 22:19
Seems like a reasonable request, especially as Go tries to have nice error messages.

I don't see that two files are relevant to this bug, though. It seems to have the same error message regardless of file:

```
bradfitz@gdev:~/src/issue23963$ cat file1.go 
package foo
 
func init() {
}
 
func one() {
        init()
}
bradfitz@gdev:~/src/issue23963$ cat file2.go 
package foo
 
func f() {
        init()
}
bradfitz@gdev:~/src/issue23963$ go build
# issue23963
./file1.go:7:2: undefined: init
./file2.go:4:2: undefined: init
```

/cc @griesemer @mdempsky @odeke-em

**Comment by griesemer** [comment] 2018-02-20 22:53
Not related to calling from a different file. The same error appears when calling from the same file. Also, not entirely trivial to fix nicely. Also, duplicate of #8481. Closing in favor of #8481.

**Closed by griesemer** 2018-02-20 22:53 UTC
Labels: NeedsFix, help wanted
