### ISSUE TITLE
cmd/compile: stack allocate string and slice headers when passed through non-escaping interfaces

### ISSUE THREAD

**Issue by dsnet** [golang/go#23676] opened 2018-02-03 00:17 UTC
Consider the following snippet:
```go
func NewA(x ...interface{}) error {
	if len(x) > 0 {
		return errors.New(x[0].(string))
	}
	return nil
}
func NewB(s ...string) error {
	if len(s) > 0 {
		return errors.New(s[0])
	}
	return nil
}

var sink error

func BenchmarkA(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		var s = "hello"
		sink = NewA(s)
	}
}

func BenchmarkB(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		var s = "hello"
		sink = NewB(s)
	}
}
```

Running benchmarks on this, you find:
```
BenchmarkA-8   	20000000	        84.3 ns/op	      32 B/op	       2 allocs/op
BenchmarkB-8   	30000000	        42.9 ns/op	      16 B/op	       1 allocs/op
```

Version A is more costly by 1 extra allocation. This occurs because calling `NewA` has a hidden call to `runtime.convT2Estring` where the string header is allocated on the heap.

However, I contend that the compiler should be able to prove that this is unnecessary. The call to `NewA` is concrete, and so the compiler should able to prove that a string header passed into the variadic interfaces neither escaped nor is modified. When crafting the interface header, it should be able to directly point to the string header on the stack.

\cc @randall77 @neild

**Comment by randall77** [comment] 2018-02-03 06:26
@dr2chase

**Comment by cherrymui** [comment] 2018-02-04 23:56
> the compiler should able to prove that a string header passed into the variadic interfaces neither escaped nor is modified.

The escape analysis does not track whether things are modified. So it cannot make an interface with its data field directly pointing to s.

That said, it is possible to have it point to a copy of s on stack. However, currently the escape analysis doesn't distinguish the interface and its underlying value, i.e. `x[0].(string)` escaping is seen as `x[0]` escaping, which causes the string header allocated on heap.

**Comment by dsnet** [comment] 2018-02-05 20:24
If the caller knew that that the last use of the string was the function call itself, then it wouldn't even need to make a copy on the stack.

**Comment by rogpeppe** [comment] 2020-05-20 06:37
Isn't this issue a duplicate of #8618 ?

**Comment by go101** [comment] 2021-09-30 08:45
It looks this is a problem of inlining:
```Go
package main

import "testing"

//go:noinline
func NewA(x ...interface{}) string {
	if len(x) == 0 {
		return ""
	}
	return x[0].(string)
}

//go:noinline
func NewB(x []interface{}) string {
	if len(x) == 0 {
		return ""
	}
	return x[0].(string)
}

//go:noinline
func NewC(x ...interface{}) string {
	return NewB(x)
}

var sink string

func BenchmarkA(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		var s = "hello"
		sink = NewA(s)
	}
}

func BenchmarkB(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		var s = "hello"
		sink = NewB([]interface{}{s})
	}
}

func BenchmarkC(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		var s = "hello"
		sink = NewC(s)
	}
}
```

Output:
```
BenchmarkA-4   	278548590	         4.154 ns/op	       0 B/op	       0 allocs/op
BenchmarkB-4   	280900167	         4.201 ns/op	       0 B/op	       0 allocs/op
BenchmarkC-4   	211030160	         5.666 ns/op	       0 B/op	       0 allocs/op
```

After removing the `//go:noinline` directive lines, the output become:
```
BenchmarkA-4   	26151573	       101.1 ns/op	      16 B/op	       1 allocs/op
BenchmarkB-4   	418234288	         2.631 ns/op	       0 B/op	       0 allocs/op
BenchmarkC-4   	27927691	       118.6 ns/op	      16 B/op	       1 allocs/op
```

**Comment by go101** [comment] 2021-09-30 08:57
And this is not a string specified problem:
```
package main

import "testing"

func NewA(x ...interface{}) int {
	if len(x) == 0 {
		return 0
	}
	return x[0].(int)
}

func NewB(x []interface{}) int {
	if len(x) == 0 {
		return 0
	}
	return x[0].(int)
}

func NewC(x ...interface{}) int {
	return NewB(x)
}

var sink int

func BenchmarkA(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		var s int = 99999
		sink = NewA(s)
	}
}

func BenchmarkB(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		var s int = 99999
		sink = NewB([]interface{}{s})
	}
}

func BenchmarkC(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		var s int = 99999
		sink = NewC(s)
	}
}
```

The output:
```
BenchmarkA-4   	60167695	        49.68 ns/op	       8 B/op	       1 allocs/op
BenchmarkB-4   	629795134	         1.882 ns/op	       0 B/op	       0 allocs/op
BenchmarkC-4   	51212834	        43.10 ns/op	       8 B/op	       1 allocs/op
```

**Comment by go101** [comment] 2021-09-30 09:01
The smallest case:
```Go
package main

import "testing"

func NewA(x ...interface{}) int {
	return 0
}

func NewB(x []interface{}) int {
	return 0
}

var sink int

func BenchmarkA(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		var s int = 99999
		sink = NewA(s)
	}
}

func BenchmarkB(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		var s int = 99999
		sink = NewB([]interface{}{s})
	}
}
```

**Comment by tdakkota** [comment] 2021-09-30 09:20
>  if the value 99999 is changed to a value between [0, 255]

It seems a optimization introduced by [CL 216401](https://go-review.googlesource.com/c/go/+/216401).

**Comment by go101** [comment] 2021-11-01 16:57
It looks this has been fixed on tip.

**Comment by leitzler** [comment] 2022-11-15 11:00
@dsnet this can be closed, right?

**Comment by dsnet** [comment] 2022-11-15 23:38
Correct. Confirmed that it is fixed.

**Closed** 2022-11-15 23:38 UTC
Labels: Performance, NeedsFix, compiler/runtime
