### ISSUE TITLE
Inconsistency in Comparing Two error Values

### ISSUE THREAD

**Issue by Bistutu** [golang/go#63798] opened 2023-10-28 06:51 UTC
### I've defined a custom error type, and now I want to compare the two.

Sample 1:
```go
package main

import (
	"errors"
	"fmt"
)

func main() {
	m := &myError{}
	n := &myError{}
	fmt.Println(m == n)    // false
}

type myError struct {
}

func (m *myError) Error() string {
	return "myError"
}
```
When I use the above code, the output for `m==n` is false, which I believe I understand because the two pointers point to different addresses in memory.

Sample 2:
```go
func main() {
	m := &myError{}
	n := &myError{}
	fmt.Println(m == n)    // true
	fmt.Println(errors.Is(m, n))    // true
}
```

However, when I add the line `fmt.Println(errors.Is(m, n))` to the code, both lines astonishingly print true. This is bewildering and I think this might be a BUG.

**Comment by Swiftie13st** [comment] 2023-10-28 07:43
Same as this
```go
package main

import (
	"fmt"
)

type A struct {
}

func main() {
	a := &A{}
	b := &A{}
	c := &A{}

	fmt.Println(a == b, b == c) // true false
	fmt.Println(a, b)          
}
```

**Comment by seankhliao** [comment] 2023-10-28 09:46
Duplicate of #23440

**Closed by seankhliao** 2023-10-28 09:46 UTC
