### ISSUE TITLE
database/sql: add extra locking when calling driver

### ISSUE THREAD

**Issue by blinsay** [golang/go#21117] opened 2017-07-21 20:31 UTC
### What version of Go are you using (`go version`)?

`go version go1.8.3 darwin/amd64`

### What did you do?

Unlike `Conn` or `Stmt` there's no guidance on `Tx` indicating how the stdlib uses implementations. This seems to cause bugs in driver implementations, as a `Tx` is expected to handle concurrent calls from multiple goroutines unlike most of the other interfaces in the package.

This came up as I was debugging [a panic inside of lib/pq](https://github.com/lib/pq/issues/614) and discovered it was a data race due to the authors not assuming that their `Tx` would have to deal with calls from multiple goroutines (the repro is [here](https://gist.github.com/blinsay/044f39176eeab7f3020d1b527df5bdd7). It slowly adjusts timeouts to try and make the Context time out as results are coming back). Out of curiosity, I looked at `go-sql-driver/mysql` and the lack of a race there seems like a happy accident - the Context expiring occasionally causes [an internal error to bubble up](https://github.com/go-sql-driver/mysql/blob/a825be04c652d01442384e9dcdf2cdc3f1eda67f/packets.go#L441-L443), since the authors appear to aggressively check their invariants.

I'm not sure whether this is a documentation problem or if there's something database/sql could do to make life easier for driver implementors.

**Comment by chrispassas** [comment] 2017-08-30 03:38
In my case I have a pool of database connections. I open a transaction and run queries. If I use BeginTx() I get an crash panic overtime.

Part of why I need a transaction is so I can use postgresql statement_timeout. The only way to use it with a connection pool is to use a transaction.

If I just use Begin() without context it never crashes. In my case though I need to be able to cancel the transaction if conditions are met in another goroutine.

**Comment by blinsay** [comment] 2017-08-30 04:05
Hey y'all,

It looks like libs are still tossing out `panic`s in Go 1.9. The underlying problem with the way the stdlib and the drivers are misunderstanding each other seems like it's still there. [This comment](https://github.com/lib/pq/issues/614#issuecomment-325872980) has some more info (race detector output, panic traces, and a reliable repro) on how lib/pq and `database/sql` interact to panic.

**Comment by kardianos** [comment] 2017-08-31 17:25
This might not be a documentation issue but a driver issue.
row.Next locks on closemu, but doesn't lock on the driver connection lock. If DB.Next operations also locked on the dc, then we would probably correct this issue. Could someone apply the following diff locally and see if it fixes it? I need to do a fuller evaluation of what is going on as well.

In database/sql/sql.go
```
diff --git a/src/database/sql/sql.go b/src/database/sql/sql.go
index c609fe4..4f2c9f9 100644
--- a/src/database/sql/sql.go
+++ b/src/database/sql/sql.go
@@ -2454,6 +2454,9 @@ func (rs *Rows) nextLocked() (doClose, ok bool) {
        if rs.lastcols == nil {
                rs.lastcols = make([]driver.Value, len(rs.rowsi.Columns()))
        }
+       rs.dc.Lock()
+       defer rs.dc.Unlock()
+
        rs.lasterr = rs.rowsi.Next(rs.lastcols)
        if rs.lasterr != nil {
                // Close the connection if there is a driver error.
@@ -2503,6 +2506,8 @@ func (rs *Rows) NextResultSet() bool {
                doClose = true
                return false
        }
+       rs.dc.Lock()
+       defer rs.dc.Unlock()
        rs.lasterr = nextResultSet.NextResultSet()
        if rs.lasterr != nil {
                doClose = true
```

I need to do a full evaluation of this solution. But you could try it out and see if the issue goes away.

**Comment by blinsay** [comment] 2017-09-01 01:39
I applied the patch and that seems to fix the panic and satisfy the race detector!

Now that the log lines aren't mostly race detector output/panic stacktrace I've started noticing that quite a lot of the errors that come back are `sql.ErrNoRows`. That seems surprising to me.

Here's some sample data after running [the repro](https://gist.github.com/blinsay/044f39176eeab7f3020d1b527df5bdd7) for a few minutes:

```
$ ~/oss/go/bin/go run -race repro.go &> repro.log

# wait a while, grab some coffee

$ grep -E -o "error=.*" < repro.log | sort | uniq -c
  46 error="context deadline exceeded"
   1 error="driver: bad connection"
3017 error="pq: canceling statement due to user request"
  42 error="sql: Rows are closed"
1369 error="sql: no rows in result set"
```

**Comment by kardianos** [comment] 2017-09-01 15:31
@blinsay Good catch. Next step will be to determine why it is reporting no rows sometimes. I suspect it may be driver issue of returning the wrong error (NoRows rather then ctx.Error), but I haven't looked.

**Comment by chrispassas** [comment] 2017-09-25 15:09
Once fixed can this be released in go 1.9.1 or 1.9.2? This is causing me problems in my application and waiting 6 months for a fix would be painful.

Thank you

**Comment by chrispassas** [comment] 2017-10-02 13:17
I'm not that familiar with the Go release process. This issue appears to be fixed but sitting in Code Review. What comes next? Is there any hope of getting this in a 1.9.x release?

https://go-review.googlesource.com/c/go/+/65731

**Comment by ianlancetaylor** [comment] 2017-10-03 00:59
I've marked this for consideration for a 1.9 release.

**Comment by rsc** [comment] 2017-10-13 18:39
Every time we touch the locking in database/sql it seems like we introduce a deadlock. What is the condition under which the problem being fixed happens? Are we sure that the expected benefit here outweighs the very real chance of introducing a deadlock in some other case?

**Comment by rsc** [comment] 2017-10-13 18:40
Also, is this a regression from Go 1.8? If not, then we really should leave it alone and let the ordinary Go 1.10 testing happen.

**Comment by kardianos** [comment] 2017-10-13 19:03
@rsc I don't believe this is a regression from go1.8.

The benefit is it prevents real races in real programs.

In this case the risk of deadlock seems non-existent. Unlike previous issues, this just using the existing locking in *driverConn as it is meant to be used, locking for the short period of time around driver connection calls. The only way this could introduce a deadlock is if a driver calls some public sql API referencing the same connection from within the driver.Next, which would be a blatant driver issue.

I offer no opinion on when it should be released.

**Comment by chrispassas** [comment] 2017-10-13 19:32
This problem is affecting our production application. A 1.9.2 fix would be appreciated.

**Comment by blinsay** [comment] 2017-10-13 20:07
> What is the condition under which the problem being fixed happens? 

@rsc the panic seems like it happens when a Context is cancelled as a query is returning results. I hit it organically while introducing a context.Context to some Postgres queries so that they could respect http.Request deadlines. With reasonable timeouts, we hit the panic every couple hours.

**Comment by chrispassas** [comment] 2017-10-13 20:11
In my case I hit the panic every minute. I can’t use context at all because of how frequently it panics.

**Comment by rsc** [comment] 2017-10-19 03:08
@blinsay and @chrispassas and anyone else seeing these crashes: I am assuming you are using Linux. Can you please try https://golang-release-staging.storage.googleapis.com/go1.9.2/go1.9.2rc2.linux-amd64.tar.gz and see if the problem disappears? Thank you.

**Comment by chrispassas** [comment] 2017-10-19 03:38
@rsc I just tried with 1.9.1 and can reproduce the crash reliably in a few seconds.

Using 1.9.2rc2 I've let it run for a few minutes 3 times with 0 crashes.

**Comment by rsc** [comment] 2017-10-19 03:41
@chrispassas, thanks very much. Based on that, I'm comfortable with including that fix in the final Go 1.9.2.

**Comment by chrispassas** [comment] 2017-10-19 03:43
@rsc Thank you, I'm looking forward to having it!

**Comment by rsc** [comment] 2017-10-19 23:54
OK, I am going to approve the cherry-pick to Go 1.9.2 over in #22314 and leave this bug open to track additional locking fixes in Go 1.10.

**Comment by cespare** [comment] 2017-12-21 05:03
I'm reopening this because the commit that auto-closed it was reverted afterwards by 292366e7162a030cade7b177eb4ad55bd887d25f

> Reason for revert: Fails to fix all the locking issues.

AFAICT this issue has not been addressed for 1.10. Feel free to close if that's not correct. (I was brought here by some serious Tx+context races/crashes in both 1.9.2 and 1.10beta1.)

**Comment by chrispassas** [comment] 2017-12-21 05:07
The fix that went into version 1.9.2 did fix the crashes for QueryContext. If I use ExecContext and PrepareContext I do get crashes fairly often. It looked like right after 1.9.2 was tagged they went back and fixed the muteness for 1.10.

If I can get some time this week I'll do some test with 1.10 beta 1 to see if it still crashes.

**Comment by kardianos** [comment] 2017-12-21 17:37
The fix for this did get in shortly after that revert. Yes, please verify @chrispassas , but as far as I know this is fixed.

**Comment by cespare** [comment] 2017-12-21 18:47
@kardianos can you please link the fix here?

**Comment by kardianos** [comment] 2017-12-21 19:18
https://github.com/golang/go/commit/1126d1483f0397648905fcd4590ae45352cabd69
https://golang.org/cl/71433

**Comment by cespare** [comment] 2017-12-22 18:02
@kardianos thanks, I missed that.

After running my crashing code with on tip + CL 85175 (for #23208) I don't see any issues.

I'm going to re-close this as we don't seem to have any reason to believe that there's still a locking issue here. We can revisit if @chrispassas finds something.

**Closed by cespare** 2017-12-22 18:02 UTC
Labels: NeedsDecision

**Comment by chrispassas** [comment] 2017-12-22 20:02
I have tested version 1.9.2 and QueryContext is good but ExecContext will trigger a depending how often your calling it.

I still need to test that 1.10-beta1 ExecContext is OK.
