### ISSUE TITLE
x/tools/cmd/goimports: mishandles named imports used under original name

### ISSUE THREAD

**Issue by josharian** [golang/go#11259] opened 2015-06-17 17:39 UTC
http://play.golang.org/p/gmQEUKYxrG

```go
package main

import (
	"fmt"
	t "time"
)

func main() {
	fmt.Println("Hello, playground")
	time.Sleep(time.Second)
}
```

Run through imports, results in:

```go
package main

import "fmt"

func main() {
	fmt.Println("Hello, playground")
	time.Sleep(time.Second)
}
```

Note that the named time import has been removed but not reinserted without the name. The resulting code does not compile. Running through goimports again fixes things.

Low priority corner case.

**Comment by hectorj** [comment] 2015-11-23 08:04
Seems like a duplicate of #8149, no?

**Comment by bradfitz** [comment] 2015-11-23 16:44
Yeah, looks like it.

**Closed by bradfitz** 2015-11-23 16:44 UTC
