### ISSUE TITLE
x/tools/cmd/godoc: playground "Pop out" link on home page is broken

### ISSUE THREAD

**Issue by alandonovan** [golang/go#28793] opened 2018-11-14 14:22 UTC
Using Chrome on Linux/X11, visit https://golang.org/.
Click the Pop-out button above the Playground. Nothing happens.
Click the browser' Reload button.
A modal dialog appears, saying "golang.org says server error, try again"

**Comment by opennota** [comment] 2018-11-15 01:50
Chromium is affected too.

**Comment by andybons** [comment] 2018-11-30 18:58
Duplicate of #28816

**Closed by andybons** 2018-11-30 18:58 UTC
Labels: NeedsInvestigation

**Comment by opennota** [comment] 2018-12-01 06:53
> #28793
> Duplicate of #28816

I think it's the other way around.

**Comment by broady** [comment] 2018-12-06 05:08
Dupe of #28134.
