### ISSUE TITLE
x/website: error in documentation example

### ISSUE THREAD

**Issue by ckharide** [golang/go#41168] opened 2020-09-01 22:17 UTC
### What version of Go are you using (`go version`)? 1.15

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)? MAC OS

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see? The file hello.go has a wrong reference to the greeting variable. 
Please look at this file in https://golang.org/doc/tutorial/call-module-code. 

### What did you see instead?  

package main

import (
    "fmt"
    "example.com/greetings"
)

func main() {
    // Get a greeting message and print it.
    message := greetings.Hello("Gladys")
    fmt.Println(greeting) /* This should be message */ => it yields compilation error "./hello.go:12:17: undefined: greeting"
}

Please change it to 

func main() {
    // Get a greeting message and print it.
    message := greetings.Hello("Gladys")
    fmt.Println(message)
}

**Comment by ianlancetaylor** [comment] 2020-09-01 22:47
I think this needs to be fixed in golang.org/x/website/content/static/doc/tutorial.

**Comment by dmitshur** [comment] 2020-09-02 00:17
Thanks for reporting. This is a duplicate of #41150 and there’s a fix already sent out.

**Closed by dmitshur** 2020-09-02 00:17 UTC
Labels: Documentation, help wanted
