### ISSUE TITLE
syscall: Getdirentries on freebsd 11 is broken

### ISSUE THREAD

**Issue by randall77** [golang/go#31416] opened 2019-04-11 16:20 UTC
`Getdirentries` on freebsd 11 will silently drop files from the directory listing.

It converts old, smaller records into new, bigger records. It tries to account for the size increase by calling the syscall with a smaller buffer (1/4 the size).  But it also has a lower bound on the minimum size, so the syscall buffer may in fact be no smaller than the original buffer. As a result, when copying from the syscall buffer to the output buffer, there may not be room for all the listed files. The code silently drops the files that don't fit.

The patch below will at least panic in that situation. The freebsd port needs to be fixed somehow. The new test `TestDirentRepeat` tickles this bug.
```
diff --git a/src/syscall/syscall_freebsd.go b/src/syscall/syscall_freebsd.go
index 87a27b1ff7..8fdb9cb144 100644
--- a/src/syscall/syscall_freebsd.go
+++ b/src/syscall/syscall_freebsd.go
@@ -392,6 +392,11 @@ func convertFromDirents11(buf []byte, old []byte) int {
                dstPos += int(dstDirent.Reclen)
                srcPos += int(srcDirent.Reclen)
        }
+       if srcPos < len(old) {
+               // We have old entries, but can't fit them in the new entry buffer.
+               // Bad!
+               panic("leftover entries")
+       }
 
        return dstPos
 }
```

@paulzhol 

Split off from #31403

**Comment by bcmills** [comment] 2019-04-11 19:30
The `freebsd` builders are still red, so if this can't be fixed soon, please at least send a CL to skip the test on the affected builders.

**Comment by ayang64** [comment] 2022-01-07 19:55
Since FreeBSD 11.x was removed from our list of builds, can we close this issue and remove the skipped portion of the test?  I couldn't reproduce under FreeBSD 14.

**Comment by bcmills** [comment] 2022-01-07 20:02
Since the tree is frozen, a change to unskip the test at this point wouldn't get very many runs before the release, which would make it more likely that we miss a test regression if it turns out not to be fixed after all.

Let's aim to remove the skip when the tree opens for 1.19, so that we can have the whole 1.19 cycle to verify that it is actually fixed.

**Comment by tklauser** [comment] 2022-05-18 07:34
There don't seem to be any reports about `TestDirentRepeat` failing on any of the freebsd builder since https://go.dev/cl/393618 re-enabling the test was submitted 2 months ago. Closing this issue.

**Closed by tklauser** 2022-05-18 07:34 UTC
Labels: Testing, OS-FreeBSD, NeedsFix, early-in-cycle
