### ISSUE TITLE
Documentation go build does not mention 'testdata' folder

### ISSUE THREAD

**Issue by stephanwesten** [golang/go#36306] opened 2019-12-29 09:41 UTC
### What version of Go are you using (`go version`)?
n/a

### Does this issue reproduce with the latest release?
n/a

### What did you do?
Navigate to https://golang.org/cmd/go/#hdr-Compile_packages_and_dependencies. It says: 

> When compiling packages, build ignores files that end in '_test.go'. 

### What did you expect to see?
I expected to see the 'testdata' folder be mentioned as well.

(it took me quite a while before I knew that this magic string existed)

### What did you see instead?
see above

**Comment by mvdan** [comment] 2019-12-29 13:16
This is documented in `go help packages`, which is mentioned in the page you link.

I think it's best to keep information in a single place, to keep it organised. If you think `go help packages` isn't easy enough to find, do you have any suggestions about that?

/cc @bcmills @jayconrod

**Comment by stephanwesten** [comment] 2019-12-29 20:49
yes, you make a fair point. I would be fine closing this issue.

WRT 'go help'. I forgot about this. I vaguely remember something like this when starting with go, but I never looked back. Stackoverflow / google is what I and most devs will do. 
Although i like the idea of go help - I question whether the investment is worth the effort. Especially for developers that use an IDE. And as you say, information should be in a single place; so probably the .org page would be my preferred choice.

**Comment by cagedmantis** [comment] 2019-12-30 17:20
Thank you @stephanwesten for your contribution. Through the comments listed above, it seems like you are happy with the current documentation scheme. I'm going to close this issue and mark it it as "working as intended." Please feel free to open it again or comment if you feel otherwise.

**Closed by cagedmantis** 2019-12-30 17:20 UTC
Labels: Documentation
