### ISSUE TITLE
io/ioutil: WriteFile example errors when run on the Go Playground

### ISSUE THREAD

**Issue by mntlty** [golang/go#40623] opened 2020-08-06 17:56 UTC
### What version of Go are you using (`go version`)?

latest

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

Go Playground https://play.golang.org/

### What did you do?

run example at https://golang.org/pkg/io/ioutil/#WriteFile which links to https://play.golang.org/p/bIP2HMSXz1u

### What did you expect to see?

no error

### What did you see instead?

error: `open testdata/hello: no such file or directory

### Suggested Fixes
`WriteFile` does not create a directory, and the code example tries to write to the non-existent directory `testdata`. Possible solution are either to create this directory in the example code or change the argument to `WriteFile` to just include the file name

**Comment by tpaschalis** [comment] 2020-08-06 19:22
You're right! In the background, [`ioutil.WriteFile`](https://github.com/golang/go/blob/b371f189dfdfb2454a20ec276de55fe884d6ff9f/src/io/ioutil/ioutil.go#L79) uses `os.OpenFile`, and has been doing so [since 2011](https://github.com/golang/go/commit/8a90fd3c72e7853a39ba348c0cd278b2d11ea610).

I think that we could indeed change the example.  
My 2¢ would be to add a couple of lines that create a directory (possibly not the `testdata` directory since it holds a special meaning in Go), so that a) users see that they need to create the directory, and b) users see that they can use WriteFile in sudirectories.

I'm not sure about documenting this behavior though since we don't explicitly mention anything about directories there.

**Comment by dmitshur** [comment] 2020-08-07 21:54
The testdata directory exists [on disk](https://github.com/golang/go/tree/master/src/io/ioutil/testdata). However, the example doesn’t have an // Output comment, so it’s only meant to be compiled and displayed in documentation, but not executed:

```
$ go test -v -run ExampleWriteFile io/ioutil
testing: warning: no tests to run
```

It doesn’t work on the Go Playground because the testdata directory isn’t available in that environment. But given there isn’t an // Output comment, maybe there shouldn’t be a button to run it on the website.

**Comment by mntlty** [comment] 2020-08-07 22:37
@dmitshur the issue isn't really about the playground but that the example as written doesn't work without other steps that are not included here, like "must have this directory before running this code"

**Comment by AlexanderYastrebov** [comment] 2021-10-19 18:51
Seems like duplicate of https://github.com/golang/go/issues/32916 fixed by https://golang.org/cl/284452

**Closed** 2021-11-17 00:29 UTC
Labels: NeedsInvestigation
