### ISSUE TITLE
github.com/icinga/icingadb/cmd/icingadb (../pkg/com/bulker.go:30:16: internal compiler error: assertion failed)

### ISSUE THREAD

**Issue by sebastic** [golang/go#53916] opened 2022-07-16 14:23 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, icingadb 1.0.0 builds successfully with 1.18.3, but fails consistently with 1.18.4.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/build/icingadb-1.0.0/_build/go-build"
GOENV="/nonexistent/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/build/icingadb-1.0.0/_build/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/build/icingadb-1.0.0/_build"
GOPRIVATE=""
GOPROXY="off"
GOROOT="/usr/lib/go-1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/build/icingadb-1.0.0/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2 -ffile-prefix-map=/build/icingadb-1.0.0=. -fstack-protector-strong -Wformat -Werror=format-security"
CGO_CPPFLAGS="-Wdate-time -D_FORTIFY_SOURCE=2"
CGO_CXXFLAGS="-g -O2 -ffile-prefix-map=/build/icingadb-1.0.0=. -fstack-protector-strong -Wformat -Werror=format-security"
CGO_FFLAGS="-g -O2 -ffile-prefix-map=/build/icingadb-1.0.0=. -fstack-protector-strong"
CGO_LDFLAGS="-Wl,-z,relro"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3661572628=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Rebuilt the icingadb (1.0.0-1) Debian package with golang-1.18 (1.18.4-1)

### What did you expect to see?

No internal compiler error.

### What did you see instead?

```
# github.com/icinga/icingadb/pkg/com
../pkg/com/bulker.go:30:16: internal compiler error: assertion failed

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

```
        cd _build && go install -trimpath -v -p 3 github.com/icinga/icingadb/cmd/icingadb
internal/unsafeheader
internal/goarch
internal/cpu
internal/abi
internal/goexperiment
internal/goos
runtime/internal/atomic
runtime/internal/math
runtime/internal/sys
internal/bytealg
runtime/internal/syscall
internal/race
sync/atomic
internal/itoa
math/bits
unicode/utf8
runtime
math
unicode
container/list
crypto/internal/subtle
crypto/subtle
unicode/utf16
vendor/golang.org/x/crypto/cryptobyte/asn1
internal/nettrace
vendor/golang.org/x/crypto/internal/subtle
github.com/dgryski/go-rendezvous
encoding
golang.org/x/xerrors/internal
golang.org/x/sys/internal/unsafeheader
github.com/icinga/icingadb/pkg/contracts
github.com/lib/pq/oid
internal/reflectlite
runtime/metrics
sync
math/rand
internal/testlog
internal/singleflight
runtime/cgo
github.com/go-redis/redis/v8/internal/rand
errors
sort
internal/oserror
syscall
strconv
reflect
time
context
io
internal/syscall/unix
internal/poll
internal/fmtsort
internal/syscall/execenv
path
hash
crypto
io/fs
encoding/binary
bytes
os
crypto/sha1
crypto/cipher
crypto/elliptic/internal/fiat
fmt
crypto/aes
crypto/des
strings
embed
crypto/elliptic/internal/nistec
crypto/internal/randutil
crypto/sha512
bufio
math/big
crypto/ed25519/internal/edwards25519/field
crypto/hmac
crypto/md5
crypto/ed25519/internal/edwards25519
crypto/rc4
crypto/sha256
encoding/hex
encoding/base64
internal/godebug
vendor/golang.org/x/net/dns/dnsmessage
encoding/pem
internal/intern
net/netip
net/url
crypto/rand
encoding/asn1
crypto/elliptic
crypto/ed25519
crypto/rsa
vendor/golang.org/x/crypto/cryptobyte
crypto/dsa
crypto/x509/pkix
path/filepath
net
crypto/ecdsa
vendor/golang.org/x/crypto/chacha20
vendor/golang.org/x/crypto/internal/poly1305
io/ioutil
vendor/golang.org/x/sys/cpu
vendor/golang.org/x/crypto/curve25519/internal/field
vendor/golang.org/x/crypto/chacha20poly1305
vendor/golang.org/x/crypto/curve25519
vendor/golang.org/x/crypto/hkdf
github.com/cespare/xxhash/v2
github.com/go-redis/redis/v8/internal/util
log
github.com/go-redis/redis/v8/internal/hashtag
github.com/go-redis/redis/v8/internal
github.com/go-redis/redis/v8/internal/hscan
github.com/go-redis/redis/v8/internal/proto
encoding/json
runtime/debug
github.com/icinga/icingadb/pkg/version
github.com/pkg/errors
database/sql/driver
github.com/icinga/icingadb/internal
github.com/creasty/defaults
database/sql
github.com/goccy/go-yaml/token
golang.org/x/xerrors
github.com/goccy/go-yaml/ast
golang.org/x/sys/unix
github.com/goccy/go-yaml/scanner
crypto/x509
github.com/go-redis/redis/v8/internal/pool
github.com/goccy/go-yaml/lexer
github.com/icinga/icingadb/pkg/backoff
golang.org/x/sync/errgroup
github.com/icinga/icingadb/pkg/com
# github.com/icinga/icingadb/pkg/com
../pkg/com/bulker.go:30:16: internal compiler error: assertion failed

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
github.com/lib/pq/scram
os/user
github.com/mattn/go-isatty
github.com/mattn/go-colorable
github.com/fatih/color
crypto/tls
github.com/goccy/go-yaml/printer
github.com/goccy/go-yaml/internal/errors
github.com/goccy/go-yaml/parser
github.com/goccy/go-yaml
regexp/syntax
golang.org/x/exp/utf8string
github.com/google/uuid
github.com/ssgreg/journald
github.com/go-redis/redis/v8
github.com/go-sql-driver/mysql
regexp
github.com/lib/pq
flag
go.uber.org/atomic
go.uber.org/multierr
go.uber.org/zap/buffer
go.uber.org/zap/internal/bufferpool
go.uber.org/zap/internal/color
go.uber.org/zap/internal/exit
go.uber.org/zap/zapcore
github.com/icinga/icingadb/pkg/utils
github.com/icinga/icingadb/pkg/common
github.com/icinga/icingadb/pkg/types
github.com/icinga/icingadb/pkg/icingaredis/v1
compress/flate
hash/crc32
vendor/golang.org/x/text/transform
compress/gzip
vendor/golang.org/x/text/unicode/bidi
vendor/golang.org/x/text/unicode/norm
vendor/golang.org/x/text/secure/bidirule
net/textproto
vendor/golang.org/x/net/http2/hpack
mime
vendor/golang.org/x/net/idna
mime/quotedprintable
mime/multipart
vendor/golang.org/x/net/http/httpguts
vendor/golang.org/x/net/http/httpproxy
net/http/httptrace
net/http/internal
net/http/internal/ascii
github.com/icinga/icingadb/pkg/periodic
net/http
golang.org/x/sync/semaphore
github.com/icinga/icingadb/pkg/retry
github.com/jmoiron/sqlx/reflectx
github.com/jmoiron/sqlx
github.com/icinga/icingadb/pkg/flatten
github.com/icinga/icingadb/pkg/icingadb/objectpacker
github.com/icinga/icingadb/pkg/structify
github.com/jessevdk/go-flags
github.com/okzk/sdnotify
os/signal
go.uber.org/zap
github.com/icinga/icingadb/pkg/logging
dh_auto_build: error: cd _build && go install -trimpath -v -p 3 github.com/icinga/icingadb/cmd/icingadb returned exit code 2
```

**Comment by sebastic** [comment] 2022-07-17 08:56
Bisecting the commits between go1.18.3 (4068be56ce) and go1.18.4 (88a06f40df) narrow done to: 460a93b54af4a0305f6007e44e41e6160a6469d8
```
460a93b54af4a0305f6007e44e41e6160a6469d8 is the first bad commit
commit 460a93b54af4a0305f6007e44e41e6160a6469d8
Author: Cuong Manh Le <cuong.manhle.vn@gmail.com>
Date:   Sat Jun 11 01:33:11 2022 +0700

    [release-branch.go1.18] cmd/compile: fix missing dict pass for type assertions
    
    For type assertions, if either src or dst type has shape, we must
    convert them to dynamic type assertions.
    
    Fixes #53357
    
    Change-Id: Ia3362fa67c011febcbdb5b26f856d081b5c366de
    Reviewed-on: https://go-review.googlesource.com/c/go/+/411617
    Run-TryBot: Cuong Manh Le <cuong.manhle.vn@gmail.com>
    TryBot-Result: Gopher Robot <gobot@golang.org>
    Reviewed-by: Matthew Dempsky <mdempsky@google.com>
    Reviewed-by: Cherry Mui <cherryyz@google.com>
    Reviewed-by: Keith Randall <khr@golang.org>
    Reviewed-on: https://go-review.googlesource.com/c/go/+/411934
    Reviewed-by: Keith Randall <khr@google.com>

 src/cmd/compile/internal/noder/stencil.go |  4 +--
 test/typeparam/issue53309.go              | 42 +++++++++++++++++++++++++++++++
 2 files changed, 44 insertions(+), 2 deletions(-)
 create mode 100644 test/typeparam/issue53309.go
```

**Comment by mvdan** [comment] 2022-07-17 21:12
cc @cuonglm @mdempsky @cherrymui @randall77

**Comment by dmgk** [comment] 2022-07-17 22:18
Looks like a duplicate of https://github.com/golang/go/issues/53852

**Comment by cuonglm** [comment] 2022-07-18 01:24
Close as duplicated of #53852

**Closed** 2022-07-18 01:24 UTC
