### ISSUE TITLE
x/net/context/ctxhttp: race condition preventing response from being closed

### ISSUE THREAD

**Issue by rs** [golang/go#14065] opened 2016-01-22 01:19 UTC
The `ctxhttp.Do` method contains a race condition when the context is cancelled before the `client.Do` performed in a go routine returns. The `http.Response` is discarded, leaving its `Body` opened and thus leading to sockets left in `CLOSE_WAIT` state.

To reproduce the issue, run this on Linux (can't reproduce on osx, I'm not sure why):

```go
package main

import (
	"fmt"

	"golang.org/x/net/context"
	"golang.org/x/net/context/ctxhttp"
)

func main() {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	resp, err := ctxhttp.Get(ctx, nil, "http://httpbin.org/get")
	fmt.Printf("%v, %v\n", resp, err)
	<-make(chan struct{})
}
```

The output is:

```
<nil>, context canceled
```

As the `res` is `nil`, I have no way for the caller to close the `resp.Body`.

Then look at `netstat -lan | grep CLOSE_WAIT`, you will see a new socket lying down forever.

**Comment by bradfitz** [comment] 2016-01-22 01:39
Which version of Go? ctxhttp operated differently depending on the Go version.

**Comment by bradfitz** [comment] 2016-01-22 01:42
Never mind, I see the problem.

**Comment by broady** [comment] 2016-01-22 01:52
I seem to recall seeing some workaround code for <=1.4. @jacobsa ?

**Comment by bradfitz** [comment] 2016-01-22 01:53
@broady, @okdave, I'm sending a fix. Polishing a test now.

**Comment by broady** [comment] 2016-01-22 01:53
Dupe of #13293.

**Comment by bradfitz** [comment] 2016-01-22 01:59
I'm not sure it is.

**Comment by bradfitz** [comment] 2016-01-22 02:15
Sent https://go-review.googlesource.com/18802

**Closed** 2016-01-26 03:35 UTC
