### ISSUE TITLE
x/mobile/bind: speed up build times

### ISSUE THREAD

**Issue by scisci** [golang/go#13163] opened 2015-11-05 17:17 UTC
I'm building a fairly large library for ios which is working great. Its about 20MB for each architecture. 

However, the build times are really starting to take their toll. They are now taking around 5 minutes to build which is tough for productivity. It would be great to be able to speed up these time by perhaps caching some of the build data. 

I'm not sure of the process but it seems for every build, bind generates a new random temporary folder for all the files, where perhaps, it could use a cached folder and reuse previously built object files?

**Comment by hyangah** [comment] 2015-11-05 17:26
does it make any difference if you use -i option?
the -i option will not help with objective-c code incremental build (similar hack may be necessary as described in android/java issue #12819), but for go code build it might.

/cc @crawshaw

**Comment by rakyll** [comment] 2015-11-05 17:58
Should we mark this as a duplicate of https://github.com/golang/go/issues/12819?

gomobile needs incremental builds. And it optimally needs to reuse aar or framework files, not just the output of the Go compilation.

**Comment by scisci** [comment] 2015-11-06 02:06
Yep, didn't see that other issue.

**Comment by hyangah** [comment] 2015-11-06 17:29
Closing it. Duplicate of #12819.

**Closed by hyangah** 2015-11-06 17:29 UTC

**Comment by petejkim** [comment] 2016-07-29 08:14
What is this `-i` option?

**Comment by crawshaw** [comment] 2016-07-29 14:59
@petejkim for details on asking questions please see https://golang.org/wiki/Questions. Old closed issues is not the place. (Also, look at the output of ```go help build```.)

**Comment by petejkim** [comment] 2016-07-29 16:47
@crawshaw Sorry about that. I just saw that the docs mention "The build flags -a, -i, -n, -x, -gcflags, -ldflags, -tags, and -work are shared with the build command. For documentation, see 'go help build'.".
