### ISSUE TITLE
go build creates binary named "command-line-arguments"

### ISSUE THREAD

**Issue by kdeberk** [golang/go#34716] opened 2019-10-06 08:19 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dberk/.cache/go-build"
GOENV="/home/dberk/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dberk/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build727171168=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
> mkdir helloworld
> write an example hello world program in helloworld/helloworld.go
> go build helloworld/helloworld.go
</pre>

### What did you expect to see?
A binary in helloworld named helloworld

### What did you see instead?
A binary named "command-line-arguments"
<pre>
[dberk learninggo :)]$ go build helloworld/helloworld.go
[dberk learninggo :)]$ ls helloworld/
command-line-arguments  helloworld.go
[dberk learninggo :)]$ ./helloworld/command-line-arguments
Hello, World!
</pre>

If I execute go build directly from that directory, the name is correct
<pre>
[dberk helloworld :)]$ go build helloworld.go
[dberk helloworld :)]$ ls
command-line-arguments  helloworld  helloworld.go
[dberk helloworld :)]$ md5sum helloworld
8fcbdb0c84650e49878bda0d9e96ddc4  helloworld
[dberk helloworld :)]$ md5sum command-line-arguments
8fcbdb0c84650e49878bda0d9e96ddc4  command-line-arguments
</pre>

**Comment by cuonglm** [comment] 2019-10-06 08:46
seems duplicate of https://github.com/golang/go/issues/34535

**Comment by kdeberk** [comment] 2019-10-06 09:05
Indeed, that seems to refer to the same issue. I tried to look for `command-line-arguments` on google and github but it seems that the dashes are stripped from `command-line-arguments` before the search is executed and that just returns a whole lot of results not directly related to my issue.

**Comment by ALTree** [comment] 2019-10-06 09:06
Since this appears to be 1) a known issue and 2) already solved on tip, I think we can close the issue.

**Closed by ALTree** 2019-10-06 09:06 UTC
