### ISSUE TITLE
cmd/go: modules generates read-only files

### ISSUE THREAD

**Issue by MartinKosicky** [golang/go#33516] opened 2019-08-07 10:02 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.12.7 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
This is the newest version stable

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/martin/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/martin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build696676537=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

When using go modules (go build, go install whatever) all files are downloaded into GOPATH. Problem is that these files are created with read-only mode. This makes quite complications for example on jenkins pipeline, where I build a single job  (some go module), pull things from git, builds, makes services, deploy, etc...
At the end of job I want to remove the workspace (or jenkins does). It has problems because the files are created in readonly mode. I cannot use some global path for GOPATH because in jenkins jobs my organization gives me access only to some sandbox (some folder), and I can't move anywhere else.

### What did you expect to see?
I would expect that these files are not created in read only mode, or that I have an ability to disable this feature.

### What did you see instead?
I couldn't remove the files with rm-rf, nor could the jenkins

I overcome this issue by invoking chmod a+w -R $GOPATH   after invoking all go installs go builds etc...  but it's complicated if the commands fail suddenly I have to make bash script traps to do this.

**Comment by ALTree** [comment] 2019-08-07 10:12
Hi, 
this is a dup of #27161, #27455, and #28137. 

Does running `go clean -modcache` fixes your issue?

**Comment by MartinKosicky** [comment] 2019-08-07 16:21
Well... this is not something I can not over come. I wanted to report this as possible improvement that you would not create files in read only mode (not sure how this helps anyone). Of course I can do go clean -modcache as I can do chmod a+w -R $GOPATH.  The thing is I don't want to do any additional commands.

**Comment by agnivade** [comment] 2019-08-07 16:31
Please see https://github.com/golang/go/issues/27161#issuecomment-433102620 as a reason for this.

A general improvement to this is tracked at https://github.com/golang/go/issues/31481. It seems like you need this in your CI. Does https://github.com/golang/go/issues/31481 suffice your usecase ?

**Comment by MartinKosicky** [comment] 2019-08-12 11:05
Well if you care about me/or people that actually use your app then no it doesnt suffice. Nor i dont believe in some corner case why making files readonly. Non major language does it and in golang you say its the best option and that its intended. If you want this thing to be not only working but also user friendly (assembler also work) then you shoul reconsider previous intentions and wonder if they are valid or if it can be done without sacraficing UX

**Comment by agnivade** [comment] 2019-08-12 11:49
@bcmills @rsc

**Comment by bcmills** [comment] 2019-08-12 19:09
Duplicate of #31481

**Closed by bcmills** 2019-08-12 19:09 UTC
Labels: WaitingForInfo
