### ISSUE TITLE
go/types: "duplicate case in expression switch" error could be formatted better (perhaps)

### ISSUE THREAD

**Issue by mvdan** [golang/go#26357] opened 2018-07-12 20:57 UTC
```
$ go version
go version devel +3df1f00bfc Thu Jul 12 08:22:37 2018 +0000 linux/amd64
$ cd src/go/types
$ go build gotype.go
$ cat f.go
package p

func f(r rune) {
        switch r {
        case 'a':
        case 'a':
        }
}
$ ./gotype f.go
f.go:6:7: duplicate case 'a' (constant 97 of type rune) in expression switch
f.go:5:7:       previous case
```

Haven't digged into why this error appears to be broken.

/cc @griesemer

**Comment by mvdan** [comment] 2018-07-12 21:00
Forgot to mention - the compiler gets this right, as expected:

```
$ go build f.go
# command-line-arguments
./f.go:6:2: duplicate case 'a' (value 97) in switch
        previous case at ./f.go:5:7
```

**Comment by ianlancetaylor** [comment] 2018-07-12 21:43
Sorry, I don't understand what you are after here.  The go/types error does say "previous case" at `f.go:5:7`.  What should it do instead?

**Comment by mvdan** [comment] 2018-07-12 21:57
Oh, the position is at the left. I completely missed that, even after reading the error multiple times.

Maybe that's just me, or maybe the error could be made clearer. I definitely find the compiler's version easier to understand.

**Comment by ianlancetaylor** [comment] 2018-07-12 22:07
The advantage of putting the position at the left is that it works well with tools, such as editors, which can cycle through the locations.  Maybe we can improve the "previous case" text to make that clearer.

**Comment by griesemer** [comment] 2018-08-08 23:27
What @ianlancetaylor said.

**Comment by ALTree** [comment] 2020-09-14 11:45
Current error message is

```
test.go:6:7: duplicate case 'a' (value 97) in switch
        previous case at test.go:5:7
```

So the 2nd line has been clarified, but the position is no longer of the left.

**Comment by griesemer** [comment] 2020-09-25 17:42
I think this ok as is. The 2nd line is really just clarifying the error, it's not another error. Closing as working as intended.

**Closed by griesemer** 2020-09-25 17:42 UTC
Labels: NeedsDecision
