### ISSUE TITLE
Adding floats shows unwanted / wrong precision

### ISSUE THREAD

**Issue by factors-prateek** [golang/go#39546] opened 2020-06-12 07:34 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Not sure.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/prateek/Library/Caches/go-build"
GOENV="/Users/prateek/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/prateek/Documents/workspace/factors/backend"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3l/wp0dvd6901q1l1bn_z8bzm1h0000gp/T/go-build389574889=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
```
package main

import "fmt"

func main() {
    a, b := 2.2, 2.2
    fmt.Println(a + b)

    a, b = 2.2, 2.3
    fmt.Println(a + b)

    a, b = 2.2, 4.4
    fmt.Println(a + b)

    a, b = 1.1, 2.2
    fmt.Println(a + b)
}
```

### What did you expect to see?
```
4.4
4.5
6.6
3.3
```

### What did you see instead?
```
4.4
4.5
6.6000000000000005
3.3000000000000003
```

**Comment by ALTree** [comment] 2020-06-12 08:50
`Println` shows `6.6000000000000005` because it's closer to the actual value of `2.2 + 4.4` in IEEE-754 float64 arithmetic. If you want to truncate the value, use `%f`, e.g.

```
a, b := 2.2, 4.4
fmt.Printf("%.2f", a + b)    // prints 6.60
```

Closing here, since this is working as intended.

**Closed by ALTree** 2020-06-12 08:50 UTC
