### ISSUE TITLE
x/pkgsite: Old tag appearing as latest

### ISSUE THREAD

**Issue by craicoverflow** [golang/go#46390] opened 2021-05-26 10:01 UTC
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/redhat-developer/app-services-sdk-go
 
 
### What is your user agent?
 

Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
 
 
 
### Screenshot
 
![image](https://user-images.githubusercontent.com/11743717/119641134-3eaa4600-be11-11eb-9472-5fb16c3b2777.png)
 
 
### What did you expect to see?

- v0.1.2 should be the latest version. 
- `apis` and `kafka` packages should not be there
 
 
### What did you see instead?

- v0.1.1 is the latest version
- `apis` and `kafka` packages listed as directories.

This likely happened because of these packages being deleted. This project is still in early development and thus we had to change the folder structure and delete somethings. Is there something that can be done to remove these?

**Comment by bcmills** [comment] 2021-05-27 13:48
It appears that someone moved or otherwise changed the tags in that repository.
Using a `go` command installed from https://golang.org/dl, I see:
```
$ export GOPROXY=direct

$ go1.16.4 get -d github.com/redhat-developer/app-services-sdk-go@v0.1.0
go: downloading github.com/redhat-developer/app-services-sdk-go v0.1.0
go get: github.com/redhat-developer/app-services-sdk-go@v0.1.0: verifying module: checksum mismatch
        downloaded: h1:CTtOQF56Byqzif+XOwD877tjSQygBxs3C/S4s5k/RX8=
        sum.golang.org: h1:HmEhUCF4ohSOghuC9YmYgx7QS4nMkRABmsbEcgx4zuA=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

$ go1.16.4 get -d github.com/redhat-developer/app-services-sdk-go@v0.1.1
go: downloading github.com/redhat-developer/app-services-sdk-go v0.1.1
go get: github.com/redhat-developer/app-services-sdk-go@v0.1.1: verifying module: checksum mismatch
        downloaded: h1:+2GtV3ouUy+Cnls+JZPRkk5Hlo9mUgQ+goXdInElyrM=
        sum.golang.org: h1:wa0XmeJ/5zS/rftq8N7UZyjQHgT1laAA/xXH99rtOC8=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

That suggests to me that whoever is using that repo is probably bypassing both the Go module proxy and the Go checksum server. Requests to the checksum server are what cause packages to be included in the index (https://index.golang.org), and the index is how `pkg.go.dev` finds out about new versions — if nobody tells the Go servers about new versions, then (by design!) they won't be indexed on `pkg.go.dev`.

I seem to recall that the Fedora fork of the `go` command [intentionally bypasses the Go servers by default](https://bugzilla.redhat.com/show_bug.cgi?id=1794110). Is it possible that the developers and users of `github.com/redhat-developer` are using the Fedora fork instead of an unmodified distribution of the Go toolchain?

To avoid these kinds of problems, I recommend that you use Go binaries distributed and supported by the Go project (or built from unmodified source) to develop your module.

**Comment by jba** [comment] 2021-06-01 13:52
Regarding v0.1.2 specifically, we don't show it because it contains no Go code. It looks like you've moved all the packages into sub-modules. That's fine, but it means there's nothing for us to show. (We have to ignore module zips with no Go files, because nothing else in the pipeline does any checking. For example, the module proxy can (and probably does) contain zips of pure Javascript or Python or whatever.)

You could add a `doc.go` file to the top-level module that contains some documentation. That trivial package should be enough for us to display a page, with links to the sub-modules in the Directories section. Your `doc.go` file could hold information common to all the project's packages. For a similar case, see https://pkg.go.dev/cloud.google.com/go@v0.82.0#section-documentation, although that top-level module does have some other packages in it.

**Comment by craicoverflow** [comment] 2021-06-01 14:18
> It appears that someone moved or otherwise changed the tags in that repository.
> Using a `go` command installed from [golang.org/dl](https://golang.org/dl), I see:
> 
> ```
> $ export GOPROXY=direct
> 
> $ go1.16.4 get -d github.com/redhat-developer/app-services-sdk-go@v0.1.0
> go: downloading github.com/redhat-developer/app-services-sdk-go v0.1.0
> go get: github.com/redhat-developer/app-services-sdk-go@v0.1.0: verifying module: checksum mismatch
>         downloaded: h1:CTtOQF56Byqzif+XOwD877tjSQygBxs3C/S4s5k/RX8=
>         sum.golang.org: h1:HmEhUCF4ohSOghuC9YmYgx7QS4nMkRABmsbEcgx4zuA=
> 
> SECURITY ERROR
> This download does NOT match the one reported by the checksum server.
> The bits may have been replaced on the origin server, or an attacker may
> have intercepted the download attempt.
> 
> For more information, see 'go help module-auth'.
> 
> $ go1.16.4 get -d github.com/redhat-developer/app-services-sdk-go@v0.1.1
> go: downloading github.com/redhat-developer/app-services-sdk-go v0.1.1
> go get: github.com/redhat-developer/app-services-sdk-go@v0.1.1: verifying module: checksum mismatch
>         downloaded: h1:+2GtV3ouUy+Cnls+JZPRkk5Hlo9mUgQ+goXdInElyrM=
>         sum.golang.org: h1:wa0XmeJ/5zS/rftq8N7UZyjQHgT1laAA/xXH99rtOC8=
> 
> SECURITY ERROR
> This download does NOT match the one reported by the checksum server.
> The bits may have been replaced on the origin server, or an attacker may
> have intercepted the download attempt.
> 
> For more information, see 'go help module-auth'.
> ```
> 
> That suggests to me that whoever is using that repo is probably bypassing both the Go module proxy ([proxy.golang.org](https://proxy.golang.org)) and the Go checksum server ([sum.golang.org](https://sum.golang.org)). Requests to the proxy and/or checksum server are what cause packages to be included in the index ([index.golang.org](https://index.golang.org)), and the index is how `pkg.go.dev` finds out about new versions — if nobody tells the Go servers about new versions, then (by design!) they won't be indexed on `pkg.go.dev`.
> 
> I seem to recall that the Fedora fork of the `go` command [intentionally bypasses the Go servers by default](https://bugzilla.redhat.com/show_bug.cgi?id=1794110). Is it possible that the developers and users of `github.com/redhat-developer` are using the Fedora fork instead of an unmodified distribution of the Go toolchain and forgetting to enable the proxy and checksum server?
> 
> To avoid these kinds of problems, I recommend that you use Go binaries distributed and supported by the Go project (or built from unmodified source) to develop your module.

Thanks for the info - I was using the Fedora fork and have changed it now1

**Comment by craicoverflow** [comment] 2021-06-01 14:19
> Regarding v0.1.2 specifically, we don't show it because it contains no Go code. It looks like you've moved all the packages into sub-modules. That's fine, but it means there's nothing for us to show. (We have to ignore module zips with no Go files, because nothing else in the pipeline does any checking. For example, the module proxy can (and probably does) contain zips of pure Javascript or Python or whatever.)
> 
> You could add a `doc.go` file to the top-level module that contains some documentation. That trivial package should be enough for us to display a page, with links to the sub-modules in the Directories section. Your `doc.go` file could hold information common to all the project's packages. For a similar case, see [pkg.go.dev/cloud.google.com/go@v0.82.0#section-documentation](https://pkg.go.dev/cloud.google.com/go@v0.82.0#section-documentation), although that top-level module does have some other packages in it.

Thanks! That makes sense.

**Comment by julieqiu** [comment] 2021-06-15 16:02
It doesn't seem like there's anything actionable on our end, so closing this issue.

**Closed by julieqiu** 2021-06-15 16:02 UTC
Labels: NeedsInvestigation, pkgsite
