### ISSUE TITLE
cmd/go: install cannot find non-module version when module proxy doesn't implement @latest

### ISSUE THREAD

**Issue by mikesep** [golang/go#44594] opened 2021-02-24 22:44 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
...
GOARCH="amd64"
...
GOOS="darwin"
...
</pre></details>

### What did you do?

`go install golang.org/x/lint/golint@latest`

### What did you expect to see?

Successful installation.

### What did you see instead?

```console
$ go install golang.org/x/lint/golint@latest
go install golang.org/x/lint/golint@latest: no matching versions for query "latest"
```

### Description

I'm having trouble getting Go 1.15/1.16 to fetch a non-module package version when a module proxy that doesn't support `$base/$module/@latest` is in the list.

Querying my local module proxy for `$goproxy/golang.org/x/lint/@v/list` returns 200 OK with an empty response body. This is the same as `https://proxy.golang.org/golang.org/x/lint/@v/list` -- in fact, my local proxy is relaying the request to `proxy.golang.org`.

My local module proxy doesn't support `$goproxy/golang.org/x/lint/@latest` and returns 404 Not Found. `proxy.golang.org` returns 200 OK with a JSON body containing a pseudo-version.

The problem is that `go` doesn't seem to be moving on to try `direct` in my list of proxies. Per https://golang.org/ref/mod#goproxy-protocol, `$base/$module/@latest` isn't required to be implemented, but this combination of (list=>200, latest=>404) doesn't seem to be working with the current code.

### Investigation so far

I've traced things through in a local build of go1.16 and found that execution is getting to the call to `p.latest()` on line 376: https://github.com/golang/go/blob/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8/src/cmd/go/internal/modfetch/proxy.go#L370-L377

This call is a bit strange to me -- if querying `@latest` fails, it seems to be trying `@v/list` again, which it already did in an earlier call to `proxyRepo.Versions()`. I'm curious to know if it serves a purpose.

Even if I bypass the call to `p.latest()` in a local build and `return nil, err` right before that, I think it's going to https://github.com/golang/go/blob/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8/src/cmd/go/internal/modload/query.go#L227-L236 which doesn't return an `ErrNotExist` and instead falls through to the end: https://github.com/golang/go/blob/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8/src/cmd/go/internal/modload/query.go#L246

Since `NoMatchingVersionError` is not an `ErrNotExist`, `modfetch.TryProxies` sees this as an error and does not fail over to the next proxy in the list:
https://github.com/golang/go/blob/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8/src/cmd/go/internal/modfetch/proxy.go#L179-L181

I *think* my analysis here is right, but I'm not entirely sure of what all the surrounding code is doing, so I'm having trouble telling if Go is doing something wrong or I'm falling into a subtle but expected behavior.

My current idea for a fix would be to replace `p.latest` with simply returning the error *and* to return earlier in `modload.queryProxy` if `repo.Latest()` returns `ErrNotExist`. I haven't started testing this yet, and I'm putting in this Issue in hopes that someone can to let me know if this sounds right before I start going too far down the wrong path. Thanks!

**Comment by mikesep** [comment] 2021-02-24 22:46
See also: [CL 183845](https://go-review.googlesource.com/c/go/+/183845) "cmd/go/internal/modfetch: halt proxy fallback if the proxy returns a non-404/410 response for @latest"

**Comment by bcmills** [comment] 2021-02-25 16:36
@jayconrod and @hyangah might have more insight, but I think this is probably working as designed (and as documented).

Since the `@latest` endpoint returns code 404, the `go` command interprets that as “`@latest` is not implemented”, and treats `@v/list` as authoritative. `@v/list` returns code 200, which confirms that the returned list (which is empty) is indeed authoritative.

I think that if you want `go get` to work with `@latest` (as opposed to a specific version), then you need one of three things:
* The proxy can implement the `@latest` endpoint.
* The proxy can return status 404 or 410 for `@v/list` when no tagged versions are present.
* The proxy can return its supported pseudo-versions in the `@v/list` results. (In Go 1.13 and later, `cmd/go` will filter them appropriately to produce the correct `@latest`; see #32715.)

**Comment by mikesep** [comment] 2021-02-25 16:55
Thanks for taking a look @bcmills. Previously, we were proxying `gocenter.io`, which includes pseudo-versions in `@v/list`, so we saw a change in behavior when we moved to `proxy.golang.org`. Obviously proxying only _some_ of the underlying module proxy's implementation can cause confusion and is not ideal. I'll look into whether we can change the local proxy to `@latest` requests.

**Comment by jayconrod** [comment] 2021-03-10 22:17
Sorry for the slow response. This seems like an edge case, but I think I agree with @bcmills: this is working as intended.

I basically think of `@v/list` and `@latest` as parts of the same thing, even though they're two separate requests. If a proxy implements them (returning 200 for `@v/list` at least), the go command treats that as authoritative and won't fall back to other proxies, even if there are no matching versions.

Closing this issue, but happy to discuss further, here or on Slack.

**Closed by jayconrod** 2021-03-10 22:17 UTC
Labels: NeedsInvestigation, WaitingForInfo
