### ISSUE TITLE
bash: /usr/bin/go: No such file or directory on Debian 9.4 after installing from apt repo

### ISSUE THREAD

**Issue by maniac0s** [golang/go#25100] opened 2018-04-26 08:36 UTC
The apt package of anything but golang-1.7 doesn't work. Golang-1.7 installs properly, golang-1.8 doesn't. Is the package in the repo wrong/incomplete?

Debian claims for golang-1.8
"This package is a metapackage that, when installed, guarantees that (most of) a full Go development environment is installed." https://packages.debian.org/stretch/golang-1.8
But that's obviously not true.

### What version of Go are you using (`go version`)?

1.8

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

Linux test-server 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

### What did you do?

Installed go on debian stable using apt install golang-1.8

apt install golang-1.8 golang-1.8-go
Reading package lists... Done
Building dependency tree       
Reading state information... Done
golang-1.8 is already the newest version (1.8.1-1).
golang-1.8-go is already the newest version (1.8.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

### What did you expect to see?

Go getting properly installed.

### What did you see instead?

Go not found

**Comment by ALTree** [comment] 2018-04-26 09:44
Hi,

we don't build or distribute the .deb packages for Go. I suggest raising an issue on the debian tracker.

Closing here, since there's nothing we can do.

**Closed by ALTree** 2018-04-26 09:44 UTC

**Comment by agnivade** [comment] 2018-04-26 09:47
Hi,

This appears to be an issue with the debian package of golang and not a bug in the Go language. The issue tracker is only used to track bugs in the Go language and proposals.

Have a look at the [questions](https://github.com/golang/go/wiki/Questions) wiki page for other places to ask general questions such as these. You might also want to try to directly install the Go binary distribution mentioned here https://golang.org/doc/install. Thanks.

Closing since this is not a bug.

**Comment by agnivade** [comment] 2018-04-26 09:48
Our responses crossed. :)
