### ISSUE TITLE
affected/package: spec website

### ISSUE THREAD

**Issue by guettli** [golang/go#53749] opened 2022-07-08 10:52 UTC
### What did you do?

I want to send someone the hyperlink to the specification of `select`

### What did you expect to see?

I saw a long page (this is fine), but I found no way to create a hyperlink to "select".

Via chrome devtools I found this hyperlink: https://go.dev/ref/spec#Select_statements

But this is not straight forward.

For example the Python docs have a way to create hyperlinks into this page:

![image](https://user-images.githubusercontent.com/414336/177978735-c9b8afa8-713e-4828-b329-7f1a2499a563.png)

It would be great, if this would be possible for the golang spec, too.

**Comment by seankhliao** [comment] 2022-07-08 11:36
Duplicate of #50210

**Closed by seankhliao** 2022-07-08 11:36 UTC
