### ISSUE TITLE
encoding/json: Unmarshal and special character tag

### ISSUE THREAD

**Issue by cdeadlock** [golang/go#10677] opened 2015-05-03 20:21 UTC
The below json demarshalling code will not detect the @rid field.

I can not tell what I am doing wrong here, is the @ symbol some kind of utf problem?

```
type TargetsResult struct{
  Result Targets "json: 'result'" 
}
type Targets []struct{
  Rid string "json: '@rid'"
  Toclaim string "json: 'toClaim'"
}

func TestJsonTarget(t *testing.T){
  //t.Skip()
  input := "{\"result\": [	{\"@rid\": \"#5:0\", \"toClaim\": \"testcode\"},{\"@rid\": \"#5:2\", \"toClaim\": \"second\"},{\"@rid\": \"#5:1\"}]}"
  var results TargetsResult
  if err := json.Unmarshal([]byte(input), &results); err != nil{
    fmt.Print(err) 
  }
  fmt.Print(results.Result)
}
```

```
Output:
[{ testcode} { second} { }]
```

If I unmarshal the same sample into the ugly 
```
type TargetsResult map[string][]map[string]interface{}
```
I can access it with
```
results["result"][0]["@rid"].(string)
```

Besides this test where the input is a go string (a rune?) I also tested the actual result coming from an http REST response where the header specifically says utf8.

**Comment by mdempsky** [comment] 2015-05-03 20:47
If you use `` `json:"@rid"` `` instead, it works: http://play.golang.org/p/TcmPNuwFsd

I can't explain why `"json: 'toClaim'"` works though.  It seems like that's actually a bug.

**Comment by mdempsky** [comment] 2015-05-03 20:51
Oh, right, the other tags weren't actually working.  It's just that your struct fields were already named "Result" and "Toclaim".

Closing since it seems to be working as intended.

**Closed by mdempsky** 2015-05-03 20:51 UTC

**Comment by cdeadlock** [comment] 2015-05-03 23:06
Yes it appears I was confused by the super specific requirements for the struct tags:

You can not use single quote to make strings (' same key as double quote), only back-quote (` same key as tilde) this gives compilations errors

You can not have a space between the json: and the double quoted tag "@rid" (no compilation errors, it just does not use it during demarshalling)
go version go1.2.1 linux/amd64

Thanks for the help
