### ISSUE TITLE
proposal: Go 2: error return with ?

### ISSUE THREAD

**Issue by mllcms** [golang/go#66190] opened 2024-03-08 12:29 UTC
### Proposal Details

Wrapping the error in `Err()` alone gives it a flag that enables catching the error and using specific APIs such as `.panic` and `.?`

```go
func fn1() (int, string, Err(error)) {

}

func fn2() (Err(error)) {
	// Throw an error
	n,s := fn1()?
	// Throw panic
	n,s := fn1().panic()
	// Deal with it again
	n,s := fn1() Err(err) {
		fmt.Println("fn2 error: ", err)
		return xxx
	}
}
```

**Comment by seankhliao** [comment] 2024-03-08 13:04
Duplicate of #39451

**Closed by seankhliao** 2024-03-08 13:04 UTC
Labels: LanguageChange, v2, Proposal, error-handling
