### ISSUE TITLE
go list creates read-only module cache

### ISSUE THREAD

**Issue by nim-nim** [golang/go#30502] opened 2019-03-01 11:00 UTC
```console
$ go version
go version go1.12 linux/amd64
$ rm -fr ~/go/
$ go list -json ./...
go: finding …
go: downloading …
go: extracting …
$ rm -fr ~/go/
rm: cannot remove '…/go/pkg/mod/…': Permission denied
…
$ ls -l ~/go/pkg/mod/*/*
total …
…/go/pkg/mod/…/…/:
dr-x------. …
…
$ chmod u+w -R ~/go/
$ rm -fr ~/go/
$
```
`go list` should not create files that the user can not remove without permission surgery, that's user-hostile behaviour.

**Comment by ALTree** [comment] 2019-03-01 11:25
Thanks for reporting this.

This is a dup of #27161 and  #27455. In particular, note (from these issues):

> Use $ go clean -modcache

Final decision was not to make the cache writable: https://github.com/golang/go/issues/27161#issuecomment-433102849. Rationale was given on both of the issues I liked above.

Closing here, since it's a dup and the cache is working as intended.

**Closed by ALTree** 2019-03-01 11:25 UTC

**Comment by nim-nim** [comment] 2019-03-01 11:37
Well, that's nasty annoying behaviour, that go maintainers find reasonable only because they are go maintainers, and would not accept in other programs.

**Comment by ALTree** [comment] 2019-03-01 13:19
I'm not sure I understand why this is so problematic.

As is explained in the issues I linked, the go commands require the cache to be in a consistent state, and the cache directories are made not writable to avoid accidental (and deliberate) corruption of the cache structure (for example when using `rm` on it). This shouldn't be an issue, since there's a specific command (`go clean -modcache`) that knows *how* to clean out the cache without causing issues for the other go tools.

Why can't you use `go clean -modcache` to act (destructively) on the cache?

**Comment by nim-nim** [comment] 2019-03-01 13:41
Having a situation, where apps starts creating files that can not be managed by regular system utilities with their usual options, requiring the use of app-specific commands, that may not even be available on-system anymore (because cache files are kept on-disk when commands are removed), is management hell (for humans and automated housekeeping utilities).

Just list all the files in your home directory and ask yourself if you want to learn one app-specific command per app creator for basic housekeeping like removing stale/cache files.

Besides, `rm` has clear simple unsurprising semantics, while  `go clean -modcache` is too clever by half and has been known to have unexpected side effects.

**Comment by nim-nim** [comment] 2019-03-01 13:48
(and I understand the wish to force projects that got used to do very weird and brittle stuff in their unit tests to clean up their act, but creating read-only files by default is not a good way to do it)
