### ISSUE TITLE
cmd/go: try next proxy if dial proxy failed

### ISSUE THREAD

**Issue by oiooj** [golang/go#32253] opened 2019-05-26 07:18 UTC
if we got dial error when using the proxy lists, we should try next proxy. Now only 404 and 410 will try next proxy.

```
Get https://proxy.golang.org: dial tcp 172.217.24.14:80: i/o timeout
```
We can wrap dial op error as a `no exist error` to implement it.

As default lists `https://proxy.golang.org,direct`, if some users can't access `https://proxy.golang.org`, they will fall back to `direct`, maybe we should custom the `timeout` para, maybe not.

/cc @rsc @bcmills

**Comment by hyangah** [comment] 2019-05-28 16:08
My personal preference is not to try the next proxy if the first proxy fails or isn't reachable - so the user knows the failure situation and chooses to explicitly opt out to the next proxy or gets alerted. 

If we fallback to the next proxy silently in case the first proxy fails to responds, it can lead to unexpected leakage of private module paths. There could be other security implication but I will let @FiloSottile chime in.

**Comment by FiloSottile** [comment] 2019-05-28 16:19
I can see a pretty bad scenario like

```
GOPROXY=http://proxy.internal,https://proxy.untrusted.example
GONOSUMDB=company.internal/foo
```

Since GONOSUMDB is not scoped per proxy, this would let the fallback proxy provide arbitrary answers for company.internal/foo if http://proxy.internal is unreachable. That's pretty much unacceptable.

**Comment by bcmills** [comment] 2019-05-28 17:37
https://github.com/golang/go/issues/31913#issuecomment-490507980 also applies to this failure mode.

(We know that the current proxy behavior is not ideal for users in China, but that's tracked separately in #31755.)

**Comment by bcmills** [comment] 2019-05-28 17:37
Duplicate of #31913

**Closed by bcmills** 2019-05-28 17:37 UTC
Labels: FeatureRequest, modules
