### ISSUE TITLE
runtime/trace: failure with SIGSEGV (and no other output) on linux-ppc64-buildlet

### ISSUE THREAD

**Issue by bcmills** [golang/go#55074] opened 2022-09-14 15:23 UTC
```
signal: segmentation fault (core dumped)
FAIL	runtime/trace	2.104s
```

`greplogs -l -e 'signal: segmentation fault \(core dumped\)\nFAIL\s+runtime/trace' --since=2022-01-01`
[2022-09-06T15:49:30-c35bc69/linux-ppc64-buildlet](https://build.golang.org/log/02fcc00351c6300fea2c466a5c22869caf71a7a8)

(CC @golang/runtime @golang/ppc64)

**Comment by bcmills** [comment] 2022-09-19 14:56
Hmm, the fault in `gentraceback` suggests a possible connection to #50144, although that could also be an independent bug with a similar failure mode. 🤔

**Comment by pmur** [comment] 2022-09-19 15:33
At the point of failure, I see that, `gp.m == nil` caused the fault in `if flags&_TraceJumpStack != 0 && gp == gp.m.g0 && gp.m.curg != nil `.

**Comment by pmur** [comment] 2022-09-19 16:00
@cherrymui, this is 2 commits prior to that patch.

Though, if `gp.m` is nil, won't this still segfault when executing `gp == gp.m.g0`?

**Comment by prattmic** [comment] 2022-09-19 16:16
That check is guarding on the previous loop. i.e., in the previous loop `gp.m.curg.m == nil`. Once we set `gp = gp.m.curg`, then then next iteration will crash on `gp.m.g0`.

**Comment by pmur** [comment] 2022-09-19 20:56
I am not able to reproduce this with CL 428655. I think this has been fixed by CL 428656.

**Closed by pmur** 2022-09-19 20:56 UTC
Labels: NeedsInvestigation, arch-ppc64x, compiler/runtime
