### ISSUE TITLE
https://pkg.go.dev/encoding/base64 needs aa EncodeString() function

### ISSUE THREAD

**Issue by andrewhodel** [golang/go#51292] opened 2022-02-21 08:16 UTC
The DecodeString() method cannot be removed, but an EncodeString() method should be added as it will not break forward compatibility and conform to a standard naming structure and module offering.

https://pkg.go.dev/encoding/base64

**Comment by davecheney** [comment] 2022-02-21 08:59
Duplicate of https://github.com/golang/go/issues/51290

**Closed by davecheney** 2022-02-21 08:59 UTC
Labels: Proposal
