### ISSUE TITLE
cmd/go: add build -json, to report build failures in JSON

### ISSUE THREAD

**Issue by zolotov** [golang/go#23037] opened 2017-12-07 18:25 UTC
If I run `go test` on a directory and one of the packages is failed to run, I won't get any json output for it.
It would be great to have at least a single package-fail json-message.

**Comment by ianlancetaylor** [comment] 2017-12-07 18:27
In general the go tool does not support multiple packages in a single directory.

Can you give a small complete example?

**Comment by zolotov** [comment] 2017-12-07 18:31
- dir/compilablePackage/foo_test.go
- dir/nonCompilablePackage/foo_test.go

run `cd dir && go test ./...`

**Comment by ianlancetaylor** [comment] 2017-12-15 21:40
Thanks.  For future reference, when I ask for a small complete example, it really helps a lot if you can give a complete example, which means the exact files and the exact commands.  Otherwise I have to guess what you mean when you say "nonCompilablePackage", and experience tells me that I often guess wrong.

Here is a complete example that may show the problem:

src/p1/p1.go

```Go
package p1

func F() {}
```

src/p1/p1_test.go

```Go
package p1

import "testing"

func TestF(t *testing.T) {
	F()
	t.Log("F")
}
```

src/p2/p2.go:

```Go
package p2

func F() {}

this file will not compile
```

src/p2/p2_test.go:

```Go
package p2

import "testing"

func TestF(t *testing.T) {
	F()
	t.Log("F")
}
```

    go test -json ./...

```
# p2
src/p2/p2.go:5:1: syntax error: non-declaration statement outside function body
{"Time":"2017-12-15T13:38:12.885932037-08:00","Action":"run","Package":"p1","Test":"TestF"}
{"Time":"2017-12-15T13:38:12.886027694-08:00","Action":"output","Package":"p1","Test":"TestF","Output":"=== RUN   TestF\n"}
{"Time":"2017-12-15T13:38:12.88604052-08:00","Action":"output","Package":"p1","Test":"TestF","Output":"--- PASS: TestF (0.00s)\n"}
{"Time":"2017-12-15T13:38:12.886047376-08:00","Action":"output","Package":"p1","Test":"TestF","Output":"\tp1_test.go:7: F\n"}
{"Time":"2017-12-15T13:38:12.886054374-08:00","Action":"pass","Package":"p1","Test":"TestF","Elapsed":0}
{"Time":"2017-12-15T13:38:12.88607203-08:00","Action":"output","Package":"p1","Output":"PASS\n"}
{"Time":"2017-12-15T13:38:12.886112826-08:00","Action":"output","Package":"p1","Output":"ok  \tp1\t0.009s\n"}
{"Time":"2017-12-15T13:38:12.886135226-08:00","Action":"pass","Package":"p1","Elapsed":0.009}
FAIL	p2 [build failed]
```

If I understand you correctly, you are saying that you would like to have JSON output that reports that we were unable to build package `p2`.  Is that correct?

CC @rsc

**Comment by zolotov** [comment] 2017-12-15 22:15
Yes, that's correct.

**Comment by rsc** [comment] 2018-01-04 18:14
You're asking for go build -json. We are only adding go test -json in this release. Maybe in a future release we could add go build -json and make go test imply that flag. Sorry.

**Comment by magik6k** [comment] 2019-05-14 15:59
@rsc It seems like the `FAIL	p2 [build failed]` line is emitted by `go test` and not `go build`, so this shouldn't require `go build -json`

**Comment by aclements** [comment] 2023-09-20 17:51
I've filed a concrete proposal for `go build -json`: https://github.com/golang/go/issues/62067 (There are a lot of cross-references above, so I figured I should call this out explicitly.)

**Comment by bcmills** [comment] 2023-11-28 21:36
Duplicate of #62067

**Closed by bcmills** 2023-11-28 21:36 UTC
Labels: NeedsInvestigation, FeatureRequest, GoCommand
