### ISSUE TITLE
x/website: "How to Write Go Code" fails on go 1.16

### ISSUE THREAD

**Issue by shamrin** [golang/go#44456] opened 2021-02-20 15:44 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/user/src/swanbase/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n1/gz5vlp814xsdfq0ncffzgqcc0000gq/T/go-build3415797913=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I was following the guide at https://golang.org/doc/code. It says:

> When you run commands like `go install`, `go build`, or `go run`, the `go` command will automatically download the remote module and record its version in your `go.mod` file

However, the example failed:

```
$ go install example.com/user/hello
hello.go:6:2: no required module provides package github.com/google/go-cmp/cmp; to add it:
        go get github.com/google/go-cmp/cmp
```

### What did you expect to see?

I expected the behaviour to match the guide.

### What did you see instead?

An error. I've solved it by running `go mod tidy`. (By the way, it would be nice if `go install` output would mention `go mod tidy` too.)

**Comment by fzipp** [comment] 2021-02-20 15:50
I also reported this in https://github.com/golang/go/issues/44241#issuecomment-778652755

**Comment by seankhliao** [comment] 2021-02-20 16:03
Duplicate of #44241

**Closed by seankhliao** 2021-02-20 16:03 UTC
