### ISSUE TITLE
x/pkgsite: not finding version of package after requesting it

### ISSUE THREAD

**Issue by kortschak** [golang/go#41173] opened 2020-09-02 03:51 UTC
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/github.com/rgonomic/rgo/sexp
 
### What is your user agent?
 

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0
 
### What did you do?
 

Navigate to https://pkg.go.dev/github.com/rgonomic/rgo/sexp
 
 
### What did you expect to see?
 
Something equivalent to this https://godoc.org/github.com/rgonomic/rgo/sexp
 
### What did you see instead?

After asking go.dev to get the package as it is newly written,

`"github.com/rgonomic/rgo/sexp" could not be found.`

go get fails also to get the recent version of the repo, so this is likely the cause.

**Comment by dmitshur** [comment] 2020-09-02 22:23
I'm unable to reproduce the issue at this time. Perhaps it's been resolved by now.

> go get fails also to get the recent version of the repo, so this is likely the cause.

Do you remember what the error was?

/cc @julieqiu @jba @jamalc per [owners](https://dev.golang.org/owners).

**Comment by kortschak** [comment] 2020-09-02 23:09
It didn't find it. The go get error resolved. Maybe it was just cache lag? The version has now appeared.

**Comment by julieqiu** [comment] 2020-09-03 15:24
Closing this issue since it seems to be resolved.

Feel free to file another issue if this comes up again.

**Closed by julieqiu** 2020-09-03 15:24 UTC
Labels: NeedsInvestigation, pkgsite
