### ISSUE TITLE
gofmt reorders inline argument comments

### ISSUE THREAD

**Issue by improbablejan** [golang/go#19341] opened 2017-03-01 09:00 UTC
### What version of Go are you using (`go version`)?
```
go version
go version go1.8 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?
```
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
```

### What did you do?

I ran gofmt on
```go
func foo(a string, b string) {
  foo(a, /* blah */ b)
}
```

### What did you expect to see?
I expected the inline comment to stay with the second argument, as that's what it's commenting. I would expect the content to either be unchanged or reformatted to
```go
func foo(a string, b string) {
  foo(a, b /* blah */)
}
```

### What did you see instead?

```go
func foo(a string, b string) {
	foo(a /* blah */, b)
}
```

**Comment by ALTree** [comment] 2017-03-01 09:21
Thanks for the report. 

This is a duplicate of #13113, so I'm closing this one in favour of the older thread.

**Closed by ALTree** 2017-03-01 09:21 UTC

**Comment by improbablejan** [comment] 2017-03-01 09:24
Thanks, I tried searching for the issue but couldn't find it.
