### ISSUE TITLE
proposal: errors: add AsTarget(error)

### ISSUE THREAD

**Issue by mkielar** [golang/go#64629] opened 2023-12-09 14:51 UTC
### Proposal Details

# Proposal details
Add following function to `errors` package:
```go
func AsTarget[T error](err T) **T {
    var p1 = &err
    var p2 = &p1
    return p2
}
```

# Rationale
Currently, when using `errors.As`, one has to do some acrobatics to create a double pointer to the type of error they want to test. This usually leads to following constructs:

```go
type MyErr struct{}
func (e *MyError) Error() string {return "foo"}

... 
var myErr *MyErr // this is bloat
if errors.As(err, &myErr) {
    ...
}
```
Everytime one wants to use `errors.As` they have to first define a variable, and then use that variable. With `AsTarget` in place, this would be a bit simpler:
```
...
if errors.As(err, AsTarget(MyErr)) {
    ...
}
```

I'm very new to go, and I don't really understand the reasons why `errors.As` couldn't just accept a zero-instance of a type. But since it is what it is, would you consider adding `AsTarget` to the standard library?

**Comment by seankhliao** [comment] 2023-12-09 14:55
Duplicate of #51945

**Closed by seankhliao** 2023-12-09 14:55 UTC
Labels: Proposal
