### ISSUE TITLE
cmd/go: go fmt doesn't work in symlinked directory

### ISSUE THREAD

**Issue by tedu** [golang/go#30336] opened 2019-02-20 23:28 UTC
go version go1.11.4 openbsd/amd64

go fmt does not work when used in a symlinked directory.

I have some source buried under gopath, with symlinks for easy access.
This mostly works, but go fmt gets confused.
```
mkdir -p go/src/a/b/c/d/issueX
ln -s go/src/a/b/c/d/issueX
cd issueX
echo "package main" > main.go
echo "func main() {}" >> main.go

go fmt
stat ../go/src/a/b/c/d/issueX/main.go: no such file or directory
exit status 2
```
Something has gone wrong here with the combination of $PWD, getcwd, and path creation. go fmt has successfully found the file it wants to format, but constructs a path that doesn't work.

I found this issue about symlinks out of gopath, with a comment from rsc suggesting a symlink into gopath, which I read to mean this should work. https://github.com/golang/go/issues/17451

Note that go build and go install both work fine.

Given a filename (go fmt *.go), it works. It's only "auto-finding" that screws up.

**Comment by bcmills** [comment] 2019-03-04 15:34
How deep is the actual working directory in your example?
(Could this be another symptom of #30520?)

**Comment by tedu** [comment] 2019-03-06 05:25
The example above was run from /home/tedu.

**Comment by bcmills** [comment] 2020-12-21 19:50
#32725 is technically a duplicate of this issue, but that copy currently has more detail so I'm going to mark them the other way 'round.

**Comment by bcmills** [comment] 2020-12-21 19:50
Duplicate of #32725.

**Closed by bcmills** 2020-12-21 19:50 UTC
Labels: NeedsInvestigation
