### ISSUE TITLE
cmd/go: `go mod tidy` failed in workspace mode

### ISSUE THREAD

**Issue by maxsxu** [golang/go#52962] opened 2022-05-18 13:23 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/max/Library/Caches/go-build"
GOENV="/Users/max/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/max/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/max/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tx/5c8vkq6x2k1f5nqvbj271qyc0000gn/T/go-build15601913=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Reproduction steps:

1. Clone test project `git clone https://github.com/maxsxu/go-workspace`
2. Run `cd server && go mod tidy`

The project structure:

```
go-workspace         
├── commons
│   ├── pkg
│   │   └── util.go
│   └── go.mod
├── server
│   ├── go.mod
│   └── main.go
└── go.work
```

The `commons/go.mod` file:

```
module atmax.io/go-workspace/commons

go 1.18
```

The `server/go.mod` file:

```
module atmax.io/go-workspace/server

go 1.18
```

The `go mod tidy` failed with below errors:

```
➜  server  go mod tidy    
go: finding module for package atmax.io/go-workspace/commons/pkg
atmax.io/go-workspace/server imports
        atmax.io/go-workspace/commons/pkg: cannot find module providing package atmax.io/go-workspace/commons/pkg: unrecognized import path "atmax.io/go-workspace/commons/pkg": reading https://atmax.io/go-workspace/commons/pkg?go-get=1: 404 Not Found
```

### What did you expect to see?

The `go mod tidy` should not try to find modules which have been declared in `go.work`.

### What did you see instead?
The `go mod tidy` try to find modules which have been declared in `go.work`, and these modules cannot be found in internet, which causes failed.

But the `go run` command works well.

**Comment by seankhliao** [comment] 2022-05-18 13:26
Duplicate of #50750

**Closed by seankhliao** 2022-05-18 13:26 UTC
