### ISSUE TITLE
affected/package: 1.18 Generics when using interfaces as constraints

### ISSUE THREAD

**Issue by tomasweigenast** [golang/go#51408] opened 2022-03-01 15:52 UTC
<pre>
Go version:
go version go1.18beta1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
No if the latest release is 1.17.

### What operating system and processor architecture are you using (`go env`)?
Windows 11 - AMD x64

### What did you do?

When creating interfaces like the following:
```go
type RepositoryEncodable interface {
	ToRepository() RepositorySnapshot
	FromRepository(input RepositorySnapshot) error
}
```

And implemented in any struct like this:
```go
func (r Race) ToRepository() repository.RepositorySnapshot {
	// Some code
}

// Here I need a pointer to race because I work with struct's properties
func (r *Race) FromRepository(input repository.RepositorySnapshot) error {
	// Some code
	return nil
}

```

If I try to use generic constraints in a method, for example:
```go
func ReadToNStructFrom[S RepositoryEncodable](s RepositorySnapshot, fieldName string, dest *Nullable[S]) error {}
```
When I try to call the method using `Race` as `S` type param, it reports the following **compile time** error:
```
"data/models/ordering".Race does not implement repository.RepositoryEncodable: wrong method signature
	got  func (*"data/models/ordering".Race).FromRepository(input repository.RepositorySnapshot) error
	want func (repository.RepositoryEncodable).FromRepository(input repository.RepositorySnapshot) error 
```

But if I remove the `*Race` pointer from this method:
```go
func (r Race) FromRepository(input repository.RepositorySnapshot) error {
	// Some code
	return nil
}
```

No compile time error is shown.

### What did you expect to see?
I expect to see no compile time error.

### What did you see instead?
A compile time error shown above.

**Comment by findleyr** [comment] 2022-03-01 16:38
Hi, would it be possible for you to provide the full definition of the types involved, perhaps in a playground example?(play.golang.org -> choose 'Go dev branch' in the dropdown next to Run)

CC @griesemer

**Comment by findleyr** [comment] 2022-03-01 17:01
@tomasweigenast the FromRepository method has a pointer receiver, which means it is only available to on values with pointer type. I believe this error message has been improved since the beta1: https://go.dev/play/p/_ZPAC8Pk_xx?v=gotip

Could you please try your code with the [Go 1.18 release candidate](https://groups.google.com/g/golang-announce/c/QHL1fTc352o/m/5sE6moURBwAJ)?

**Comment by griesemer** [comment] 2022-03-01 17:06
Even if the error message is not great, at this point this will have to wait for 1.19 assuming everything else (but the error message) is behaving as expected.

In any case, if you can provide a minimal, self-contained example that is always best, as it will make it much easier for us to actually take action. Thanks.

**Comment by findleyr** [comment] 2022-03-01 17:12
@griesemer I think this has already been addressed since beta1. Marking this as WaitingForInfo. Barring something I'm missing, I think we can close this.

**Comment by ianlancetaylor** [comment] 2022-03-01 17:44
I agree.  I don't see anything to do here on tip.  Please comment if you disagree.

**Closed by ianlancetaylor** 2022-03-01 17:44 UTC
Labels: WaitingForInfo

**Comment by tomasweigenast** [comment] 2022-03-01 19:01
> Even if the error message is not great, at this point this will have to wait for 1.19 assuming everything else (but the error message) is behaving as expected.
> 
> In any case, if you can provide a minimal, self-contained example (ideally single file, or at least playground link) hat is always best, as it will make it much easier for us to actually take action. Thanks.

Can you provide a link to see what is coming for Go 1.19?



> @griesemer I think this has already been addressed since beta1. Marking this as WaitingForInfo. Barring something I'm missing, I think we can close this.
There is nothing can I do to make this work?

**Comment by ianlancetaylor** [comment] 2022-03-01 20:20
> Can you provide a link to see what is coming for Go 1.19?

Things may change, but currently there are no features currently planned for 1.19.  Work will be focused on fixing bugs, improving error messages, and speeding up compiling and execution time.

> There is nothing can I do to make this work?

People have tried to explain above that the problem is that a pointer method is only available on the pointer type.  There is nothing you can do to change that.  I don't know what the larger problem is.  You may have to specify type arguments explicitly, using the pointer type.  Or you may have to pass a pointer.  Or it may help to take a look at https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#pointer-method-example.  I don't know.  Sorry.

**Comment by tomasweigenast** [comment] 2022-03-01 20:30
What I did is to change method's signature trying to avoid using generics. Thank to everyone.
