### ISSUE TITLE
syscall: darwin arm{,64} libSystem syscalls are not compliant with the App Store submissions 

### ISSUE THREAD

**Issue by s-s** [golang/go#28984] opened 2018-11-28 09:29 UTC
### What version of Go are you using (`go version`)?
go version devel +bf870f3d54 Tue Nov 27 18:04:27 2018 +0300 darwin/amd64

### Does this issue reproduce with the latest release?
Only master branch affected, go 1.11.2 and 1.10.5 are fine (as they use bare Syscall functions).

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="off"
GOEXE=""
GOFLAGS="-ldflags=-s -ldflags=-w"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="<...>/.build"
GOPROXY=""
GORACE=""
GOROOT="<...>/go"
GOTMPDIR=""
GOTOOLDIR="<...>/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build998597890=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

Actually, I'm using gomobile, so GOARCHs are arm, arm64 (and 386, amd64 for simulator).

### What did you do?
I'm building an iOS framework using gomobile and Go from master branch. Then I submit an app with this framework to the App Store Connect. After submission some (unknown) post processing happens on Apple's side.

### What did you expect to see?
Binary should be processed successfully. (It is for go 1.11.2 and 1.10.5)

### What did you see instead?
Binary is rejected for "Non-public API usage" - The app references non-public symbols: ___getdirentries64, _fstat64, _lstat64, _stat64

This happens because of these changes: a3b01440fef3d2833909f6651455924a1c86d192, c9762b8a7ec852d96ea040c28c5f65b1104ec844 in master branch

PS: I've solved it by patching syscall/mksyscall.pl - reverting back bare Syscall usage for mentioned symbols and generating updated zsyscall_darwin_{arm,arm64,386,amd64}.{go,s} using syscall/mksyscall.pl and syscall/mkasm_darwin.go.

**Comment by ianlancetaylor** [comment] 2018-11-28 13:54
CC @randall77 @eliasnaur

**Comment by eliasnaur** [comment] 2018-11-28 15:44
According to the macOS stat(2) man page, platforms released after widening inodes to 64-bit do not have the *64 variants available, and the non-postfixed system calls are already 64-bit compliant:

"Platforms that were released after these updates only have the newer variants available to them.  These platforms have the macro _DARWIN_FEATURE_ONLY_64_BIT_INODE defined."

I checked with a simple Xcode project that _DARWIN_FEATURE_ONLY_64_BIT_INODE is indeed defined for iOS builds, but not for macOS builds.

The fix for fstat, lstat, stat seems to be to drop the "64" postfix on iOS.

Getdirentries is more complicated. According to its man page, 

"As of Mac OS X 10.6, getdirentries() is deprecated, and it is recommended that applications use readdir(3) rather than using
     getdirentries() directly.  Due to limitations with the system call, getdirentries() will not work with 64-bit inodes; in order to use
     getdirentries(), _DARWIN_NO_64_BIT_INODE must be defined.  See stat(2) for more information on _DARWIN_NO_64_BIT_INODE and its other
     effects."

Since _DARWIN_NO_64_BIT_INODE must be defined to access getdirentries, and since iOS has _DARWIN_FEATURE_ONLY_64_BIT_INODE defined, it is likely that getdirentries is not (supposed to be) available on iOS in any form.

So it seems getdirentries have to be replaced, at least on iOS. I don't know whether that's realistic. Perhaps getdirentries could be removed from package syscall on iOS altogether, even though it breaks the Go compatibility guarantee.

**Comment by eliasnaur** [comment] 2018-11-29 12:45
I worked a bit on this; removing the "64" postfixes was easy, but getdirentries are a central system call for directory listing, and I couldn't think of a straightforward replacement for it. I'm leaving this for more capable hands.

**Comment by ianlancetaylor** [comment] 2018-11-29 21:11
@eliasnaur Want to send the fixes you have?  After we get those in, changing `syscall.ReadDirent` to not use `Getdirentries` on Darwin should be doable.  I'm not too concerned about mobile programs calling `syscall.Getdirentries` directly.

**Comment by eliasnaur** [comment] 2018-12-13 20:33
@s-s, can you please verify that the issue is fixed in go tip (or the beta release that is imminent)?

**Comment by s-s** [comment] 2018-12-14 09:59
@eliasnaur, checked with tip version - everything is ok now! Thank you!
PS: `go version devel +38e7177c94 Fri Dec 14 05:48:18 2018 +0000 darwin/amd64`

**Comment by zx2c4** [comment] 2019-09-19 05:21
@eliasnaur does this need a corresponding commit in x/sys?

**Comment by eliasnaur** [comment] 2019-09-19 08:10
Do you mean

**Closed** 2019-09-19 08:10 UTC
Labels: NeedsInvestigation, OS-Darwin, release-blocker

**Comment by zx2c4** [comment] 2019-09-19 10:09
@eliasnaur That CL is for iOS-only, right? The syscall change later got ported to macOS (x86, amd64) too, due to similar appstore restrictions there. But I don't see a corresponding x/sys change for macOS.

**Comment by eliasnaur** [comment] 2019-09-19 11:22
On Thu Sep 19, 2019 at 3:12 AM Jason A. Donenfeld wrote:
> @eliasnaur That CL is for iOS-only, right? The syscall change later got ported to macOS (x86, amd64) too, due to similar appstore restrictions there. But I don't see a corresponding x/sys change for macOS.
> 

I see. Then yes, I suppose a x/sys port is needed.
