### ISSUE TITLE
encoding/json: RawMessage marshals as base64

### ISSUE THREAD

**Issue by niemeyer** [golang/go#14493] opened 2016-02-24 18:16 UTC
The encoding/json package marshals RawMessage properly or incorrectly as base64 based on whether its container is marshaled by value or as a pointer, which is extremely subtle and trivial to get wrong silently.

It also consistently fails to marshal the RawMessage value properly when used as a map value type.

Sample code demonstrating these problems:

https://play.golang.org/p/bHuvfyb7qB

**Comment by niemeyer** [comment] 2016-02-24 18:19
Updated the example to show the proper and improper marshalings.

**Comment by niemeyer** [comment] 2016-02-24 18:28
Updated again to cover the fact the same misbehavior happens when using it as a map value type, whether the map itself is handed as a pointer or not.

**Comment by cespare** [comment] 2016-02-24 18:58
What change are you suggesting? Documentation?

**Comment by cespare** [comment] 2016-02-24 19:02
When I write custom Marshaler/Unmarshaler types, I tend to use a pointer receiver only for Unmarshal and a value receiver for Marshal, to make this kind of mistake easier for the user to avoid. I think that the usage issue trumps consistency of pointer receivers in that case.

But it's too late to change json.RawMessage now.

**Comment by niemeyer** [comment] 2016-02-24 19:31
The bug should be fixed. The misbehavior is obvious, and undocumented/undesired in every case where it happens.

**Comment by cespare** [comment] 2016-02-24 20:04
What does "fixed" mean? Change Marshal to use a pointer receiver? Special-case json.RawMessage in the encoder?

**Comment by niemeyer** [comment] 2016-02-24 21:12
Fixed means making the output match most people's expectation, rather than silently having surprising undesired side-effects that break actual programs at runtime based on unperceived (and unintended) reasoning.

**Comment by bradfitz** [comment] 2016-04-10 00:04
Has anybody prepared the fix so we know how invasive it'd be?

**Comment by rogpeppe** [comment] 2016-04-10 16:24
Would it actually be an API-breaking change to declare MarshalJSON on the
value type? I can't think of any way that it could be at the moment (I've
been thinking I'd proposing that very change for a while now)

**Comment by bradfitz** [comment] 2016-04-10 17:05
@rogpeppe, that wouldn't work:

```
$ go install .
# encoding/json
./stream.go:237: method redeclared: RawMessage.MarshalJSON
        method(*RawMessage) func() ([]byte, error)
        method(RawMessage) func() ([]byte, error)
```

**Comment by bradfitz** [comment] 2016-04-10 17:19
I went to fix this (see https://golang.org/cl/21811) but it breaks the test for issue #6458 which seems to explicitly lock-in this behavior:

```
--- FAIL: TestIssue6458 (0.00s)
        encode_test.go:437: Marshal(x) = `{"M":"foo"}`; want `{"M":"ImZvbyI="}`
FAIL
exit status 1
FAIL    encoding/json   1.474s
```

From test:

```go
func TestIssue6458(t *testing.T) {
        type Foo struct {
                M RawMessage
        }
        x := Foo{RawMessage(`"foo"`)}

        b, err := Marshal(&x)
        if err != nil {
                t.Fatal(err)
        }
        if want := `{"M":"foo"}`; string(b) != want {
                t.Errorf("Marshal(&x) = %#q; want %#q", b, want)
        }

        b, err = Marshal(x)
        if err != nil {
                t.Fatal(err)
        }

        if want := `{"M":"ImZvbyI="}`; string(b) != want {
                t.Errorf("Marshal(x) = %#q; want %#q", b, want)
        }
}
```

I don't really like that behavior, but I'm not sure whether we can change it.

@rsc?

**Comment by rogpeppe** [comment] 2016-04-10 18:44
The value method would cover the pointer type too because that's how Go
methods work.

However as that issue demonstrates, it could indeed change behaviour where
code is currently expecting a RawMessage to marshal as a []byte, and that's
probably incompatible enough that we wouldn't want to change it.

What a pity.

**Comment by dominikh** [comment] 2016-04-10 18:54
It would also change the signature of the function from `MarshalJSON(*json.RawMessage)` to `MarshalJSON(json.RawMessage)`. Changing any of the types in a function declaration is a backwards incompatible change.

**Comment by cespare** [comment] 2016-04-10 20:22
The options I see are (1) warnings in the documentation and (2) RawMessage2.

**Comment by extemporalgenome** [comment] 2016-04-12 21:24
Could we not make this vet territory? Passing anything containing a non-addressable RawMessage (directly or transitively) into any of the json decoding functions is clearly a mistake (since if they _want_ that behavior, they can just use a normal `[]byte`)

**Comment by rogpeppe** [comment] 2016-04-13 13:38
dominikh: Yes, you're right, I hadn't thought about method expressions.

extemporalgenome: I don't think so. Vet often can't see the
types that are passed in to json encoding/decoding functions.

In my particular case, I wanted to round-trip map[string]json.RawMessage;
as it is I use map[string]*json.RawMessage but that doesn't seem ideal.

To be honest, the implementation of json.RawMessage is so trivial
that it's not a problem to reimplement with Marshal declared on the
value type, but that's still not ideal.

**Comment by rsc** [comment] 2016-04-13 18:13
I think this is an instance of "just lock down the current behavior and move on". The fix is to use *RawMessage, right?

**Comment by cespare** [comment] 2016-04-13 20:20
I just noticed that this is actually a duplicate of #6528. Though maybe that one should be closed in favor of this one, which has a lot more discussion.

**Comment by bigdrum** [comment] 2016-09-09 04:58
For me, the fix is defining my own RawMessage and have a custom linter to ban the use of json.RawMessage. Not too bad.

**Comment by mlitvin** [comment] 2016-09-21 15:04
I just spent few hours chasing this issue. Admittedly I didn't look in the issue database, but my guess is that others are likely not to do it as well.

May I suggest at least a warning in the RawMessage documentation?

**Comment by faddat** [comment] 2016-10-05 16:15
hm.  You know..... Json.RawMessage -- what can I say, the DX does not love me.  I have some stuff as a RawMessage, and cannot make it as a string, try as I might.  Anything to make these conversions easier, takes a load off my shoulders that's for sure.

**Comment by rsc** [comment] 2016-10-24 20:32
Despite my comment from 2013 on #6528 and my comment here from April 2016, today I am having a very hard time stomaching the current behavior. 

It's hard to see this as anything other than a bug we should fix. The whole reason RawMessage exists is to marshal its raw content. If it's not doing that, it seems like we should fix it. Yes, it might break people expecting something else, but those people can use plain []byte.

The difference in Gustavo's program https://play.golang.org/p/bHuvfyb7qB between Marshal(color1) and Marshal(&color1) further convinces me that we should fix RawMessage. It already "does the right thing" when it appears in an addressable context.

I think we can overrule the test case added in #6458, at least tentatively, and see whether any justifiable real code breaks.

Let's fix this (change RawMessage.Marshal to be a value method) and see if we can make it stick.

Leaving for @quentinmit.

**Comment by bradfitz** [comment] 2016-10-24 20:38
I already had a CL for this (above). I can just resurrect it.

**Comment by bradfitz** [comment] 2016-10-24 20:53
Updated https://go-review.googlesource.com/c/21811/

**Closed** 2016-10-26 21:05 UTC
Labels: NeedsFix
