### ISSUE TITLE
plugin: reject plugins built with a different version of the toolchain

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#17832] opened 2016-11-07 19:40 UTC
We should explicitly reject an attempt to open a plugin that was created by a different version of the Go toolchain.  We have no reliable way to make that work, as the internal runtime package interface changes between versions.  (I didn't see an explicit check for this--I may have missed one.)

**Comment by wendigo** [comment] 2016-11-14 13:32
Hi,

I've cherry picked this change and built tip and now every time I get mismatch for the "runtime" package on macOS: `could not open plugin: plugin.Open: plugin was built with a different version of package runtime`

**Comment by crawshaw** [comment] 2016-11-14 14:31
What version of macOS?
Are you seeing that output from all.bash?

**Comment by wendigo** [comment] 2016-11-14 18:19
./all.bash is fine - all tests passes.
OS X 10.11.6

I will provide more information tomorrow (I'm away from my computer right now)

**Comment by wendigo** [comment] 2016-11-15 10:58
Ok, I've been able to distill minimal reproducible test case from my case.

It turns out that plugin fails to load when loaded from test (via `go test`) with an error: `plugin.Open: plugin was built with a different version of package runtime`

I've created repository https://github.com/wendigo/go-plugin-33161 showing this behaviour.

Hope this helps :)

**Comment by wendigo** [comment] 2016-11-15 11:02
I've tested it on newest tip version (b687d6a7886fe7ffea0e36072c2a882c8c485838) with cherry-picked change #33161. ./all.bash is ok (no failing tests).

```
~ go version
go version devel +9d63294 Tue Nov 15 11:31:54 2016 +0100 darwin/amd64

~ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mateusz.gajewski/Desktop/Projects/"
GORACE=""
GOROOT="/Users/mateusz.gajewski/Desktop/go"
GOTOOLDIR="/Users/mateusz.gajewski/Desktop/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/43/1y0rrqr55zq3f8cj5wpkt1kmhc7r33/T/go-build349051862=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by crawshaw** [comment] 2016-11-15 16:08
I believe in-package tests are a particularly gnarly corner-case, and so I've punted it to #17928. (I don't believe that needs to be fixed for 1.8.)

**Comment by quentinmit** [comment] 2016-11-16 18:21
@crawshaw The fix for this seems to have caused the linux-amd64-noopt builder to start failing. Can you please take a look?

**Comment by crawshaw** [comment] 2016-11-16 18:34
Can't we handle this on the new bug we have for this: #17937?

I'll try to find some time this weekend.

**Closed by crawshaw** 2016-11-16 18:34 UTC
Labels: NeedsFix

**Comment by quentinmit** [comment] 2016-11-16 19:18
Absolutely, I didn't see the new bug. Thanks.
