### ISSUE TITLE
go build should remove semantic versioning when determing file name

### ISSUE THREAD

**Issue by FireFart** [golang/go#29643] opened 2019-01-09 22:18 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

Tested with
```
docker run --rm -v $(pwd):/app -it golang:1.11.4 /bin/bash
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/firefart/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/firefart/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build670649339=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

main.go
```golang
package main

import "fmt"

func main() {
  fmt.Println("Test")
}
```

go.mod
```
module github.com/user/project/v3
```

According to https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher we have to add the `/v3/` for versions bigger than two which has been done here. After a `go build` or `go build ./...` the build finishes but produces a binary named `v3` instead of `project`

### What did you expect to see?

the name extracted from go.mod should have semantic versions stripped. In this case the binary name should be `project`

### What did you see instead?

the binary is built as `v3`

**Comment by bcmills** [comment] 2019-01-11 20:28
Duplicate of #27283.

**Closed by bcmills** 2019-01-11 20:28 UTC
Labels: FeatureRequest
