### ISSUE TITLE
cmd/link: sigsegv linking some reflection using code

### ISSUE THREAD

**Issue by mwhudson** [golang/go#18250] opened 2016-12-08 19:15 UTC
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```
mwhudson@aeglos:/opt/opensource/go-test-cases$ cat checkstuff.go
package main

import (
	"fmt"
	"reflect"
)

type C struct {
}

func F(c *C) *C {
	return nil
}

func main() {
	var c *C
	fmt.Println(reflect.TypeOf(F).Out(0) == reflect.TypeOf(c))
}
mwhudson@aeglos:/opt/opensource/go-test-cases$ go run -linkshared checkstuff.go
```

#### What did you expect to see?

true

#### What did you see instead?

```
# command-line-arguments
go.plugin.tabs: unreachable sym in relocation: type..2nM11zSk
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5275cb]

goroutine 1 [running]:
cmd/link/internal/ld.relocsym(0xc420072820, 0xc4204d1cc8)
	/opt/opensource/go/src/cmd/link/internal/ld/data.go:600 +0x10bb
cmd/link/internal/ld.(*Link).reloc(0xc420072820)
	/opt/opensource/go/src/cmd/link/internal/ld/data.go:736 +0xc8
cmd/link/internal/ld.Main()
	/opt/opensource/go/src/cmd/link/internal/ld/main.go:207 +0x949
main.main()
	/opt/opensource/go/src/cmd/link/main.go:58 +0xdb
```

#### Does this issue reproduce with the latest release (go1.7.4)?

Go 1.7 says "false", which is also wrong.

#### System details

```
go version devel +d4b46aa Thu Dec 8 01:36:44 2016 +0000 linux/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/opensource/gopath"
GORACE=""
GOROOT="/opt/opensource/go"
GOTOOLDIR="/opt/opensource/go/pkg/tool/linux_amd64"
GCCGO="/usr/bin/gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build977155483=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
GOROOT/bin/go version: go version devel +d4b46aa Thu Dec 8 01:36:44 2016 +0000 linux/amd64
GOROOT/bin/go tool compile -V: compile version devel +d4b46aa Thu Dec 8 01:36:44 2016 +0000 X:framepointer
uname -sr: Linux 4.4.0-47-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
/lib/x86_64-linux-gnu/libc.so.6: GNU C Library (Ubuntu GLIBC 2.23-0ubuntu4) stable release version 2.23, by Roland McGrath et al.
gdb --version: GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
```

**Comment by mwhudson** [comment] 2016-12-08 19:16
Paging @crawshaw

**Comment by crawshaw** [comment] 2016-12-08 19:38
Looks like go.plugin.tabs is being marked as reachable in non-plugins. I can fix that easily enough, which will restore the (incorrect) behavior of 1.7.4. CL soonish.

**Comment by mwhudson** [comment] 2016-12-08 19:43
Yeah, I'd just blundered my way to that -- it's being marked reachable while laying out the moduledata, which is way too late. I guess the ptab should only be written to the moduledata if it is reachable?

**Comment by crawshaw** [comment] 2016-12-08 19:51
When -buildmode=plugin it's marked as reachable much earlier, that marking in symtab.go is actually redundant. The problem is it's being used when in other buildmodes.

**Comment by mwhudson** [comment] 2016-12-08 19:52
Oh heh we have competing fixes, mine is https://go-review.googlesource.com/c/34170/, I'm not especially attached to it though.

**Comment by mwhudson** [comment] 2016-12-08 19:52
(although having the test is worthwhile)

**Closed** 2016-12-08 20:02 UTC

**Comment by mwhudson** [comment] 2016-12-08 20:05
I filed https://github.com/golang/go/issues/18252 for the problem that is also present in 1.7.4. Not going to get to that today.
