### ISSUE TITLE
buffer.String() returns "<nil>" instead of ""

### ISSUE THREAD

**Issue by amandahla** [golang/go#30135] opened 2019-02-08 17:18 UTC
### What version of Go are you using (`go version`)?
go version go1.11.5 linux/amd64

### What did you do?
I get information from an external command so at some point I read StdoutPipe into a bytes.Buffer like this:
```
buf := new(bytes.Buffer)
... lines of code ...
sizeFromBuffer := buf.String()
if sizeFromBuffer == "<nil>" {
		sizeFromBuffer = "0"
}
```

I noticed that String() function returns a "`<nil>`" instead a zero value string like "".

This way, I need to check and set a zero (or it could be a "") myself.

Reference:

https://golang.org/src/bytes/buffer.go?s=2482:2514#L51

Wouldn't be more appropriate to return "" ?

**Comment by bontibon** [comment] 2019-02-08 17:44
That can't be the code you're using. `<nil>` is only printed when the receiver is nil. For example:

```go
var buf *bytes.Buffer
buf.String() // <nil>
```

**Comment by amandahla** [comment] 2019-02-08 18:17
But return a "" would be the proper way, right?

**Comment by mvdan** [comment] 2019-02-08 21:51
Please include a complete program that reproduces your problem on play.golang.org. A copy-pasted snippet is not enough, as those are usually not easy to run.

And like @bontibon said, this is likely just because you're using a nil `*bytes.Buffer`. If you want it to return an empty string, use a non-nil buffer.

**Comment by networkimprov** [comment] 2019-02-09 09:13
https://play.golang.org/p/XgKoU2SAC4y

Shouldn't a nil receiver panic? `<nil>` is a perfectly ordinary string :-)

**Comment by mvdan** [comment] 2019-02-09 09:41
It's not required that calling methods on nil receivers panic. Plenty of types have special behavior when methods are called on nil, such as bytes.Buffer.

If you don't want to deal with the special `<nil>` string output, just don't use nil buffers.

And like @bontibon said, we can't change this behavior, as that would break programs.

**Comment by networkimprov** [comment] 2019-02-09 10:38
> If you don't want to deal with the special `<nil>` string output, just don't use nil buffers.

You meant "don't use buffer pointers" since the above means "just don't make mistakes" :-)

**Comment by ianlancetaylor** [comment] 2019-02-09 22:17
Closing because there doesn't seem to be anything to do.  Please comment if you disagree.

**Closed by ianlancetaylor** 2019-02-09 22:17 UTC
Labels: WaitingForInfo

**Comment by networkimprov** [comment] 2019-02-09 22:49
Making `(*bytes.Buffer)(nil).String()` panic might alert ppl to latent bugs. 

Why would anyone check the .String() result for `"<nil>"` rather than check the pointer?

**Comment by ianlancetaylor** [comment] 2019-02-09 22:55
I don't know why the code works that way, but it has worked that way since before the first open source release.  We would need a really really good reason to change it now.

**Comment by go101** [comment] 2019-02-09 23:31
Generally, the `String` method is used to implement the `Stringer` interface. Here, it is also used to return the string representation of the current buffered bytes. Maybe there should be two methods at the beginning.

**Comment by amandahla** [comment] 2019-02-11 11:08
I believe that if you saw something wrong or that it could be improved, you should try to fix it...I understand that it could break thinks and that it's a old code that always existed like this, but this is not a good reason to ignore it and leave it that way, right?

Maybe it could be fixed in Go 2... :-)

**Comment by mvdan** [comment] 2019-02-11 11:14
It doesn't seem like there's anything worthwhile fixing. If you want to avoid `<nil>` strings, just do:

```
if buf != nil {
    output = buf.String()
}
```

**Comment by ianlancetaylor** [comment] 2019-02-11 20:51
@amandahla One of the features of Go is to be as backward compatible as possible, as described at https://golang.org/doc/go1compat.  That doesn't mean that we can't change anything, but it means that when changing something we have to weigh the cost.  We can't make a change simply because it will be an improvement.  The improvement is a benefit, but the change is a cost.  We have to compare the benefit and the cost when deciding what to do.

In this case, to me, the benefit seems quite small.  And the cost is very hard to determine, but is clearly non-zero.  So given a small benefit and an indeterminate cost, my bias is always going to be to not make the change.

**Comment by networkimprov** [comment] 2019-02-11 21:58
@ianlancetaylor you need to make yourself a keyboard macro to insert that text -- or a wiki page and macro to insert link :-)

@amandahla did you do any searches among the issues or google groups or the web generally to see if others have raised the issue? That's the best way to make a case for benefit.
