### ISSUE TITLE
Unexpected behavior of len()

### ISSUE THREAD

**Issue by davecb** [golang/go#50917] opened 2022-01-30 22:46 UTC
I was surprised to discover that passing a nil pointer to a struct containing a empty array of *float to len() is handled by len as if I had passed it a non-nil pointer to an empty array.

```
func main() {
	var a AuctionData

	available, value := a.GetFirstBid()
	log.Printf("available = %v value = %f\n", available, value)
}

type AuctionData struct {
	bids []*float64
}

func (a *AuctionData) GetFirstBid() (bool, float64) {
	if len(a.bids) == 0 { // this is where the bug is triggered
		// no bid was made
		return false, 0
	}
	// otherwise return the first bid in the array.
	return true, *a.bids[0]
}
```

I know len is a built-in, and in addition is designed to report the len of a nil pointer as zero, but my mental model of len(a.bids) was that 
* a.bids would be loaded
* followed by with a test against zero and a panic if a.bids was zero
* followed by the evaluation of a+offset to get the address of the []bids, and
* the address of the []bids would be "passed to" len(), and
* len would return the len of the []bids

That it did not panic was a real surprise. 

It was also a disappointment, as if it would have panicked I would have realized that there was an error on the codepath that called getFirstBid. I eventually found it, and a bad unit test that was hiding it, but mostly by dumb luck.  I found the len() anomaly because the bug was in the line before the call to getFirstBid, and I was stepping through it with the debugger (;-))

Gentlepersons (gentlegophers?), do you think it should return zero, panic before it reaches len() or do some third thing?

Code and assembler attached
[lenbug.asm.gz](https://github.com/golang/go/files/7967086/lenbug.asm.gz)
[lenbug.go.gz](https://github.com/golang/go/files/7967088/lenbug.go.gz)
.

**Comment by seankhliao** [comment] 2022-01-30 22:54
Go slices aren't C arrays.
Closing working as intended.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Closed by seankhliao** 2022-01-30 22:54 UTC
