### ISSUE TITLE
affected/package: gccgo go build -compiler=gccgo  main.go have error main.go:3:8: package plugin is not in GOROOT (/usr/local/go/src/plugin)

### ISSUE THREAD

**Issue by ChenJhua** [golang/go#50400] opened 2021-12-31 09:54 UTC
### What version of Go are you using (`go version`)?
I installed gccgo according to "https://go.dev/doc/install/gccgo#Using_gccgo"

<pre>
$ go version
go version go1.16 linux/amd64

$ /data/cjh/goplugin_gccgo # gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/11.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-11.2.0/configure --enable-languages=c,c++,go --disable-multilib
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.0 (GCC) 
$ /data/cjh/goplugin_gccgo # gccgo --version
gccgo (GCC) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY="code.sangfor.org"
GONOSUMDB="code.sangfor.org"
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE="code.sangfor.org"
GOPROXY="http://mirrors.sangfor.org/nexus/repository/go-proxy,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="/usr/local/gccgo/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD="/data/cjh/goplugin_gccgo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build705235373=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I want to use gccgo to compile golang code
```
$ /data/cjh/goplugin_gccgo # cat myplugin1.go
package main
import "fmt"
func Hello() {
    fmt.Println("Hello, World! I am plugin 1")
}
$ /data/cjh/goplugin_gccgo # cat main.go
package main
import "fmt"
import "plugin"
func main() {
	//      加载 myplugin 库
        fmt.Println("p1")
	p2, err := plugin.Open("./myplugin1.so")
	if err != nil {
		fmt.Println(err)
	}
	// fmt.Println("p2")
	//      取得 Hello 函数
	//fn2, err := p2.Lookup("plugin/unnamed-d17d18a2010d6f936435c3a64c1d0329e9a8755e.Hello")
	fn2, err := p2.Lookup("Hello")
	if err != nil {
		fmt.Println(err)
	}
	//      调用函数
	fn2.(func())()
	
}
```

### What did you expect to see?
success

### What did you see instead?
```
$ /data/cjh/goplugin_gccgo # go build -compiler=gccgo  main.go
main.go:3:8: package plugin is not in GOROOT (/usr/local/go/src/plugin)
$ /data/cjh/goplugin_gccgo # ll /usr/local/go/src/plugin
total 16
-rw-r--r-- 1 root root 4060 Feb 17  2021 plugin_dlopen.go
-rw-r--r-- 1 root root 2054 Feb 17  2021 plugin.go
-rw-r--r-- 1 root root  439 Feb 17  2021 plugin_stubs.go
-rw-r--r-- 1 root root  402 Feb 17  2021 plugin_test.go
```

**Comment by seankhliao** [comment] 2021-12-31 10:36
Duplicate of #36403

**Closed by seankhliao** 2021-12-31 10:36 UTC

**Comment by ChenJhua** [comment] 2022-01-03 09:23
> Duplicate of #36403
Do you have plans to optimize the plugin module or support the plugin mode of gccgo. If so, please tell me, can you? thanks

**Comment by ianlancetaylor** [comment] 2022-01-03 17:35
I am not aware of anybody working on plugin support for gccgo.
