### ISSUE TITLE
Is there a driver for hp vertica database?

### ISSUE THREAD

**Issue by g3gurung** [golang/go#20667] opened 2017-06-14 12:19 UTC
I am trying **vertica database** with **GO** for the first time ever so any help is highly appreciated.

**Comment by ALTree** [comment] 2017-06-14 12:40
Hi,

the Go project does not use its bug tracker for general discussion or asking questions. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2017-06-14 12:40 UTC
