### ISSUE TITLE
src/net: net.InterfaceAddrs may return error due to a race condition when interface is deleted

### ISSUE THREAD

**Issue by orange30** [golang/go#70767] opened 2024-12-11 03:39 UTC
### Go version

all the version

### Output of `go env` in your module/workspace:

```shell
go version go1.23.3 linux/amd64
[root@VM-137-208-tencentos golang_bin]# go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.woa.com+643d7a06+Ac5f5VOC4N8NUXdmhbm8pZSXIWfhek5JSmWdWrq7pLX4'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.3'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/root/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3294369079=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

kube-proxy: net.InterfaceAddrs may return error due to a race condition, causing the Nodeport Service to be inaccessible
https://github.com/kubernetes/kubernetes/issues/129146

1, syncProxyRules->GetNodeIPs->net.InterfaceAddrs()->interfaceAddrTable(which is in interface_linux.go for Linux)->syscall.NetlinkRIB(syscall.RTM_GETADDR, syscall.AF_UNSPEC) is called.
2. Then an interface is delete by CNI.
3. Then interfaceAddrTable(which is in interface_linux.go) call interfaceTable(which is in interface_linux.go)->syscall.NetlinkRIB(syscall.RTM_GETLINK, syscall.AF_UNSPEC)
The key point is that, RTM_GETADDR's return have the delete interface, but the RTM_GETLINK's return donot have the deleted interface.
4. Then in interfaceAddrTable->addrTable will return err.
<img width="809" alt="Clipboard_Screenshot_1733888177" src="https://github.com/user-attachments/assets/5d264995-b9b8-446c-9446-bdaf8aff66ba">
5. Then the syncProxyRules will not write correct forward configuration because the GetNodeIPs's return donot have any ip.

### What did you see happen?

net.InterfaceAddrs should not return err and nil when this is a lot interface on the linux operating system.

### What did you expect to see?

net.InterfaceAddrs should return correct addr the exist on the linux operating system.

**Comment by seankhliao** [comment] 2024-12-11 04:03
Duplicate of #51934

**Closed by seankhliao** 2024-12-11 04:03 UTC
Labels: FrozenDueToAge

**Comment by orange30** [comment] 2024-12-11 04:12
@seankhliao 
1. This issue analyzes the cause of the problem.
2. The PR for this problem: https://github.com/golang/go/pull/70768
