### ISSUE TITLE
cmd/go: go get cannot create zip

### ISSUE THREAD

**Issue by uhthomas** [golang/go#54384] opened 2022-08-10 23:59 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.19
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/nix/store/wc4py67prnfb5izkvwjpn4v53vzi1amk-go-1.19/share/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/nix/store/wc4py67prnfb5izkvwjpn4v53vzi1amk-go-1.19/share/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3183675079=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
go get -d github.com/sourcegraph/sourcegraph@f659e61
```

### What did you expect to see?

A successful download.

### What did you see instead?

```
root@b64f345f7401:/# go get -d github.com/sourcegraph/sourcegraph@f659e61
go: downloading github.com/sourcegraph/sourcegraph v0.0.0-20220805202456-f659e618d762
go: github.com/sourcegraph/sourcegraph@f659e61: create zip: internal/search/query/testdata/TestParseStandard/patterns_are_literal_and_slash-delimited_patterns_/.../_are_regexp.golden: malformed file path "internal/search/query/testdata/TestParseStandard/patterns_are_literal_and_slash-delimited_patterns_/.../_are_regexp.golden": invalid path element "..."
```

---

The problem file: https://github.com/sourcegraph/sourcegraph/tree/6cf24568ac2c070f96ab9fed5470a2d26f088315/internal/search/query/testdata/TestParseStandard/patterns_are_literal_and_slash-delimited_patterns_/...

Although weird, I don't see anything "wrong" with this. A directory named "..." is fine with Linux and fine with Go's `archive/tar` package.

**Comment by uhthomas** [comment] 2022-08-11 00:04
Sort of related? #45549

**Comment by mengzhuo** [comment] 2022-08-11 01:51
cc @bcmills @matloob

**Comment by seankhliao** [comment] 2022-08-11 22:18
Duplicate of #45549

**Closed by seankhliao** 2022-08-11 22:18 UTC
Labels: NeedsDecision
