### ISSUE TITLE
affected/package: regexp 

### ISSUE THREAD

**Issue by karisawa** [golang/go#51157] opened 2022-02-12 01:01 UTC
### What version of Go are you using (`go version`)?

<pre>
go1.17.6
</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
plan9/amd64
</pre></details>

### What did you do?
go doc regexp Match

### What did you expect to see?
package regexp // import "regexp"

func (re *Regexp) Match(b []byte) bool 
    Match reports whether the byte slice b
    contains any match of the regular expression re.
func Match(pattern string, b []byte) (matched bool, err error)
    Match reports whether the byte slice b contains any match of the regular
    expression pattern. More complicated queries need to use Compile and the
    full Regexp interface.

### What did you see instead?
package regexp // import "regexp"

func Match(pattern string, b []byte) (matched bool, err error)
    Match reports whether the byte slice b contains any match of the regular
    expression pattern. More complicated queries need to use Compile and the
    full Regexp interface.

### Note that
hebe% go doc bufio ReadString
package bufio // import "bufio"

func (b *Reader) ReadString(delim byte) (string, error)
    ReadString reads until the first occurrence of delim in the input, returning
    a string containing the data up to and including the delimiter. If
    ReadString encounters an error before finding a delimiter, it returns the
    data read before the error and the error itself (often io.EOF). ReadString
    returns err != nil if and only if the returned data does not end in delim.
    For simple uses, a Scanner may be more convenient.

hebe%

**Comment by davecheney** [comment] 2022-02-12 01:31
@karisawa thank you for raising this issue. I’m having trouble understanding the problem you are reporting. Would you be able to restate it in one or two sentences that describe what you were not able to to, or what you are trying to do?

**Comment by robpike** [comment] 2022-02-12 08:17
It's working as intended and as documented.

**Comment by beoran** [comment] 2022-02-12 08:31
The regexp package has a function Match and a type Regexp with a method Match. This is a feature of Go language, not a bug. 

The documentation of regexp.Match already says: Match reports whether the byte slice b contains any match of the regular expression pattern. More complicated queries need to use Compile and the full Regexp interface. What is unclear about that?

**Comment by seankhliao** [comment] 2022-02-12 11:07
`go doc regexp regexp.match`

Closing as working as intended

**Closed by seankhliao** 2022-02-12 11:07 UTC
