### ISSUE TITLE
go1.10 errors_test.go use errors_test with errors.go

### ISSUE THREAD

**Issue by xtudouh** [golang/go#33166] opened 2019-07-18 05:54 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version 
go1.10 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/shawn/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/shawn/Workspaces"
GORACE=""
GOROOT="/usr/local/go1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build983462816=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you expect to see?
go files in errors package all use errors as package

### What did you see instead?
errors.go use errors package, but test files use errors_test package

**Comment by bcmills** [comment] 2019-07-18 14:18
Duplicate of #25223

**Closed by bcmills** 2019-07-18 14:18 UTC
