### ISSUE TITLE
time: MST parsing issues

### ISSUE THREAD

**Issue by pjebs** [golang/go#39588] opened 2020-06-15 03:49 UTC
Go 1.14

```go
localTime := time.Now().Local().Format("2006-01-02T15:04:05Z07:00MST")
// localTime = "2020-06-15T13:47:58+10:00Australian Eastern Standard Time"

time.Parse("2006-01-02T15:04:05Z07:00MST", localTime)
// error = parsing time "2020-06-15T13:44:58+10:00Australian Eastern Standard Time" as "2006-01-02T15:04:05Z07:00MST": cannot parse "Australian Eastern Standard Time" as "MST"
```

https://play.golang.org/p/dfC-Z1frms5

Should the operation above be the inverse and hence return the original value back instead of producing an error?

**Comment by ianlancetaylor** [comment] 2020-06-15 04:36
Perhaps it should be an inverse, but unfortunately it isn't, and it never has been.  When printing, `MST` can print the full name of a time zone, as it does here.  When parsing, `MST` can only match a three to five letter code such as `AEST`.

Closing because this is expected behavior.

**Closed by ianlancetaylor** 2020-06-15 04:36 UTC
