### ISSUE TITLE
runtime/pprof: failures with SIGSEGV on linux-amd64-longtest

### ISSUE THREAD

**Issue by bcmills** [golang/go#54976] opened 2022-09-09 14:40 UTC
```
#!watchflakes
post <- pkg == "runtime/pprof" && `signal: segmentation fault`
```

From a SlowBot on https://go.dev/cl/428716 (https://storage.googleapis.com/go-build-log/38af0500/linux-amd64-longtest_88ed84a0.log):
```
signal: segmentation fault (core dumped)
FAIL	runtime/pprof	48.544s
```

There is also one of these in a very recent dashboard log:
`greplogs -l -e 'signal: segmentation fault .*\nFAIL\s+runtime/pprof' --since=2022-01-01`
[2022-09-06T15:44:28-32f68b5/linux-amd64-longtest](https://build.golang.org/log/1283b943d375f0517b37729f39ee6aa378aea5f0)

**Comment by bcmills** [comment] 2022-09-09 14:41
Marking as release-blocker at least until we can determine whether this is a Go 1.20 regression.

**Comment by aclements** [comment] 2022-09-21 16:12
Duplicate of #54885

**Closed by aclements** 2022-09-21 16:12 UTC
Labels: NeedsInvestigation, compiler/runtime
