### ISSUE TITLE
cmd/compile,runtime: found pointer to free object on linux-amd64-noopt

### ISSUE THREAD

**Issue by mknyszek** [golang/go#54907] opened 2022-09-06 21:17 UTC
[2022-09-02T20:14:40-3e11e61/linux-amd64-noopt](https://build.golang.org/log/b42c44f119bf5b24297bb66b54803e19c5750c89)
[2022-09-02T19:22:26-0fda8b1/linux-amd64-noopt](https://build.golang.org/log/1d3db4054eafde08de1ce5d2b5a8f585bbedc295)

Since I only saw this failure mode on the noopt builders, I figure it's some kind of compiler/runtime interaction.

CC @golang/compiler @golang/runtime

**Comment by bcmills** [comment] 2022-09-06 21:25
`greplogs -l -e '\nfatal error: found pointer to free object' --since=2022-08-01 --omit=js-wasm\|plan9-arm`
[2022-09-02T20:14:40-3e11e61/linux-amd64-noopt](https://build.golang.org/log/b42c44f119bf5b24297bb66b54803e19c5750c89)
[2022-09-02T19:22:26-0fda8b1/linux-amd64-noopt](https://build.golang.org/log/1d3db4054eafde08de1ce5d2b5a8f585bbedc295)
[2022-08-22T11:49:45-761db3e/linux-amd64-noopt](https://build.golang.org/log/7b1e52a4ff70b1f83f44e712af3377d1209f63e2)
[2022-08-09T16:09:24-e1a8e0e/solaris-amd64-oraclerel](https://build.golang.org/log/9b244a2dc6c2bb5764c003ef327bc62bedfeed42)

**Comment by bcmills** [comment] 2022-09-14 14:20
`greplogs -l -e '\nfatal error: found pointer to free object' --since=2022-09-06 --omit=js-wasm\|plan9-arm\|openbsd`
[2022-09-08T14:33:43-c263fa0/linux-amd64-noopt](https://build.golang.org/log/f9c238705e47a800f8b0295f80d2374171046242)
[2022-09-07T01:48:31-ba1ef54/linux-amd64-noopt](https://build.golang.org/log/5b1bee3dbd2be6b801297aca537d0339f4b4de9c)

**Comment by bcmills** [comment] 2022-09-14 14:21
Marking as release-blocker because this very much looks to be a Go 1.20 regression.

**Closed** 2022-09-19 21:58 UTC
Labels: NeedsInvestigation, release-blocker, compiler/runtime
