### ISSUE TITLE
runtime: test/fixedbugs/issue11656.go fails on many systems

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#11910] opened 2015-07-28 16:35 UTC
The test case fixedbugs/issue11656.go fails on a several 386 systems, on arm64, and on Windows.  I think we know why it fails on Windows, but why does it fail on the other systems?  We should fix it or at least find out why.

**Comment by mdempsky** [comment] 2015-07-28 17:21
I'll investigate for openbsd/386.

**Comment by mdempsky** [comment] 2015-07-28 21:34
Someone please sanity check this for me:

  1. I've removed lines 7 through 23 of test/fixedbugs/issue11656.go to get rid of the +build lines.
  2. Within test, if I run "go run run.go -- fixedbugs/issue11656.go" I reproduce the "cannot find main.f on stack" error.
  3. But if I just run "go run fixedbugs/issue11656.go" it runs without errors.
  4. I've even tried minimal run.go clones like below and it still runs without error:

    func main() {
        var buf bytes.Buffer
        cmd := exec.Command("go", "run", "fixedbugs/issue11656.go")
        cmd.Stdout = &buf
        cmd.Stderr = &buf
        fmt.Println(cmd.Run())
        fmt.Println(buf.String())
    }

Is there anything intentionally special about test/run.go that could affect test process behavior?

**Comment by mdempsky** [comment] 2015-07-28 21:51
Apparently the failure is sensitive to the size of the environment, and run.go was setting GOOS and GOARCH.  I found I can repro the issue with:

    go build fixedbugs/issue11656.go
    XXOS=openbsd XXARCH=386 ./issue11656

**Comment by mdempsky** [comment] 2015-07-28 22:00
Manually playing around with different environment variables and values, some combinations instead produce this failure:

    SIGILL: illegal instruction
    PC=0x1832fea5 m=0
    
    goroutine 1 [running]:
    
    eax    0x0
    ebx    0x1832fea4
    ecx    0x183000d0
    edx    0x1832fea4
    edi    0x1831009d
    esi    0x1832ffa5
    ebp    0x0
    esp    0x1832fe9c
    eip    0x1832fea5
    eflags 0x10246
    cs     0x2b
    fs     0x5b
    gs     0x63

**Comment by mdempsky** [comment] 2015-07-28 23:39
The varying success/failures is because

    56		var f struct {
    57			x uintptr
    58		}
    59		f.x = uintptr(unsafe.Pointer(&f))
    60		fn := *(*func())(unsafe.Pointer(&f))
    61		fn()

sets x to some memory address and then treats it as an instruction sequence.  Unsurprisingly, an arbitrary memory address is not always a valid instruction sequence, so sometimes it results in SIGILL.  Varying the environment affects the behavior because that affects what memory address x will be set to.

Repro'ing the "cannot find main.f on stack" error, I found it was from executing this instruction sequence:

    0:   a4                      movsb  %ds:(%esi),%es:(%edi)
    1:   5e                      pop    %esi
    2:   33 18                   xor    (%eax),%ebx

It triggers a SIGSEGV on the last instruction (PC=0x18335ea6) because %eax is 0x0.  I suspect the previous pop instruction is causing CL 12026's stack unwinding heuristic to fail.

I know historically OpenBSD on i386 has not utilized PAE, so it doesn't provide per-page no-execute control, hence why the target instructions actually matter for it.

**Comment by mdempsky** [comment] 2015-07-28 23:47
@minux Do you know whether the netbsd-386-minux builder supports PAE? If not, I think that would explain the netbsd/386 failures too.

**Comment by ianlancetaylor** [comment] 2015-07-29 22:30
Thanks for digging into it.  What if we change it to

func f(n int) {
	if n > 0 {
		f(n - 1)
	}
	var f struct {
		x uintptr
	}

	// We want to force an illegal instruction, to get a crash
	// at a PC value != 0.
	// Not all systems make the data section non-executable.
	ill := make([]byte, 64)
	switch runtime.GOARCH {
	case "386", "amd64":
		binary.LittleEndian.PutUint16(ill, 0x0b0f) // ud2
	case "arm":
		binary.LittleEndian.PutUint32(ill, 0xe7f000f0) // no name, but permanently undefined
	case "arm64":
		binary.LittleEndian.PutUint32(ill, 0xd4207d00) // brk #1000
	case "ppc64":
		binary.BigEndian.PutUint32(ill, 0x7fe00008) // trap
	case "ppc64le":
		binary.LittleEndian.PutUint32(ill, 0x7fe00008) // trap
	default:
		// Just leave it as 0 and hope for the best.	
	}

	f.x = uintptr(unsafe.Pointer(&ill[0]))
	fn := *(*func())(unsafe.Pointer(&f))
	fn()
}

?  Perhaps that will give more consistent results.

**Comment by 4a6f656c** [comment] 2015-09-27 18:29
This test also fails on openbsd/arm, in similar ways to what it does on openbsd/386 (and presumably for the same reasons). The alternative proposed by @ianlancetaylor makes it pass reliably.

**Comment by rsc** [comment] 2015-11-24 16:51
Fixed by CL 15058 as far as I can tell.

**Closed by rsc** 2015-11-24 16:51 UTC
