### ISSUE TITLE
x/website: golang.org won't responsively render the mobile menu.

### ISSUE THREAD

**Issue by cdvillard** [golang/go#48031] opened 2021-08-28 03:17 UTC
### What version of Go are you using (`go version`)?
N/A

### Does this issue reproduce with the latest release?
N/A

### What operating system and processor architecture are you using (`go env`)?
N/A

### What did you do?
Visiting golang.org in a viewport that forces the mobile menu to render, I couldn't actually open the navigation when clicking the hamburger menu icon. This happened on both Vivaldi on Android and Brave on MacOS Catalina.

### What did you expect to see?
The site navigation rendering, at the very least.

### What did you see instead?
Nothing rendered.

**Comment by fzipp** [comment] 2021-08-28 05:20
Looks like a duplicate of #47862

**Comment by seankhliao** [comment] 2021-08-28 09:20
Duplicate of #47862

**Closed by seankhliao** 2021-08-28 09:20 UTC
