### ISSUE TITLE
confuse with "go vet error is not a type"

### ISSUE THREAD

**Issue by wangcheng711** [golang/go#33668] opened 2019-08-15 14:26 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### What did you do?
the sample code:

```go
package main

import (
	"log"
	"os"
)

func main() {
	file, error := os.Open("hs.json")
	if error != nil {
		log.Println("open file ", error)
		return
	}
	defer file.Close()
	h := func(string) error {
		return nil
	}
	h("hello")

}
```

### What did you see instead?
i am beginner with golang, the go vet output is 'error is not a type'. so, it can be confusing to fix problem

**Comment by bcmills** [comment] 2019-08-15 14:35
Go has a flat namespace: variable names and and type-names can (and do) shadow each other.

Here, you have declared a local variable `error` (on line 9), and it shadows the declaration of the built-in type `error`.

**Comment by bcmills** [comment] 2019-08-15 14:37
Duplicate of #33567

**Closed by bcmills** 2019-08-15 14:37 UTC
