### ISSUE TITLE
cmd/go: malformed file path error not bubbled up

### ISSUE THREAD

**Issue by padurean** [golang/go#34539] opened 2019-09-25 21:11 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ogg/Library/Caches/go-build"
GOENV="/Users/ogg/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ogg/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7c/2189p7097pzgjmhz046qms940000gn/T/go-build760274827=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

<pre>
$ export GO111MODULE=on
$ go mod init
$ go get github.com/rubanbydesign/rest
    go: finding github.com/rubanbydesign/rest latest
    go get github.com/rubanbydesign/rest: no matching versions for query "upgrade"
</pre>

### What did you expect to see?
success (i.e. no error)

### What did you see instead?
<pre>
go get github.com/rubanbydesign/rest: no matching versions for query "upgrade"
</pre>

**NOTE:** With export `GO111MODULE=off` `go get github.com/rubanbydesign/rest` succeeds.

**Comment by agnivade** [comment] 2019-09-26 05:52
Wow, the real error message is way hidden.

First off, normal `go get` doesn't show anything:

```
$go get -v github.com/rubanbydesign/rest
go: finding github.com/rubanbydesign/rest latest
go get github.com/rubanbydesign/rest: no matching versions for query "upgrade"
```

Let's try with no proxy:

```
$GOPROXY=direct go get -v github.com/rubanbydesign/rest
go: finding github.com/rubanbydesign/rest latest
go: downloading github.com/rubanbydesign/rest v0.0.0-20190925204409-a9714d13f578
verifying github.com/rubanbydesign/rest@v0.0.0-20190925204409-a9714d13f578: github.com/rubanbydesign/rest@v0.0.0-20190925204409-a9714d13f578: reading https://sum.golang.org/lookup/github.com/rubanbydesign/rest@v0.0.0-20190925204409-a9714d13f578: 410 Gone
```

Hmm .. okay the commit is lost somehow or something bad happened ? The github repo looks fine. Let's try with no sumdb:

```
$GOPROXY=direct GOSUMDB=off go get -v github.com/rubanbydesign/rest
go: finding github.com/rubanbydesign/rest latest
go: downloading github.com/rubanbydesign/rest v0.0.0-20190925204409-a9714d13f578
go: extracting github.com/rubanbydesign/rest v0.0.0-20190925204409-a9714d13f578
-> unzip /home/agniva/play/go/pkg/mod/cache/download/github.com/rubanbydesign/rest/@v/v0.0.0-20190925204409-a9714d13f578.zip: malformed file path "user_test.go'": invalid char '\''
go get github.com/rubanbydesign/rest: unzip /home/agniva/play/go/pkg/mod/cache/download/github.com/rubanbydesign/rest/@v/v0.0.0-20190925204409-a9714d13f578.zip: malformed file path "user_test.go'": invalid char '\''
```

Aha ! So it's because of a trailing `'` in `user_test.go'`. But the previous commands have __no__ indication whatsoever.

@bcmills @jayconrod - Is there some open issue which somehow tracks bubbling up this error message in the default go get ?

**Comment by padurean** [comment] 2019-09-26 08:03
@agnivade 😲 Wow! That was a nasty little one. I've removed that `user_test.go'` file as it was just garbage anyway (it had no content) and now `go get` succeeds. Thank you very much! Of course, the bubbling up of the error message is still a nice-to-have fix 🙂

**Comment by jayconrod** [comment] 2019-09-26 13:49
@agnivade Wow, that's pretty obscure. We should definitely surface that better. In general, errors where we aren't able to produce a module zip aren't well reported.

**Comment by jayconrod** [comment] 2019-10-01 20:02
It looks like this is already mitigated at tip, so I'll close this as a duplicate of #30748.

```
verifying github.com/rubanbydesign/rest@v0.0.0-20190925204409-a9714d13f578/go.mod: github.com/rubanbydesign/rest@v0.0.0-20190925204409-a9714d13f578/go.mod: reading https://sum.golang.org/lookup/github.com/rubanbydesign/rest@v0.0.0-20190925204409-a9714d13f578: 410 Gone
	server response: not found: unzip /tmp/gopath/pkg/mod/cache/download/github.com/rubanbydesign/rest/@v/v0.0.0-20190925204409-a9714d13f578.zip: malformed file path "user_test.go'": invalid char '\''
```

Internally, the go command is successfully creating a module zip file, but it fails validation when we try to extract it. I don't believe there's any case where we create a zip file without extracting it, so while it may be a good idea to add some validation to the zip creation code, it wouldn't have any visible change.

**Closed by jayconrod** 2019-10-01 20:02 UTC
Labels: NeedsInvestigation

**Comment by Aisuko** [comment] 2020-04-08 06:23
Is there any update? I hit the same issue suddenly

```
 ~/go  go version
go version go1.14.1 darwin/amd64

 ✘  ~/go   GO111MODULE=on go get -v github.com/securego/gosec/cmd/gosec
go get github.com/securego/gosec/cmd/gosec: no matching versions for query "upgrade"
 ✘  ~/go  GO111MODULE=off go get -v github.com/securego/gosec/cmd/gosec
get "golang.org/x/tools/go/packages": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at //golang.org/x/tools/go/packages?go-get=1
get "golang.org/x/tools/go/packages": verifying non-authoritative meta tag
golang.org/x/tools (download)
get "golang.org/x/xerrors": found meta tag get.metaImport{Prefix:"golang.org/x/xerrors", VCS:"git", RepoRoot:"https://go.googlesource.com/xerrors"} at //golang.org/x/xerrors?go-get=1
golang.org/x/xerrors (download)
golang.org/x/xerrors/internal
github.com/nbutton23/zxcvbn-go/match
github.com/nbutton23/zxcvbn-go/utils/math
golang.org/x/tools/internal/telemetry/event
golang.org/x/xerrors
gopkg.in/yaml.v2
golang.org/x/tools/go/internal/gcimporter
github.com/nbutton23/zxcvbn-go/data
golang.org/x/tools/internal/gocommand
golang.org/x/tools/go/internal/packagesdriver
golang.org/x/tools/internal/packagesinternal
github.com/nbutton23/zxcvbn-go/adjacency
github.com/nbutton23/zxcvbn-go/frequency
github.com/nbutton23/zxcvbn-go/entropy
github.com/nbutton23/zxcvbn-go/scoring
github.com/nbutton23/zxcvbn-go/matching
github.com/nbutton23/zxcvbn-go
golang.org/x/tools/go/gcexportdata
golang.org/x/tools/go/packages
github.com/securego/gosec
github.com/securego/gosec/output
github.com/securego/gosec/rules
github.com/securego/gosec/cmd/gosec
 ~/go  GO111MODULE=off go get -v github.com/securego/gosec/cmd/gosec;
```
