### ISSUE TITLE
io: TeeReader does not write out necessary fully

### ISSUE THREAD

**Issue by mitar** [golang/go#50491] opened 2022-01-07 12:57 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mitar/.cache/go-build"
GOENV="/home/mitar/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mitar/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mitar/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="/usr/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2708945409=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I was looking at the code of `TeeReader`'s `Read` function and I saw:

```golang
func (t *teeReader) Read(p []byte) (n int, err error) {
	n, err = t.r.Read(p)
	if n > 0 {
		if n, err := t.w.Write(p[:n]); err != nil {
			return n, err
		}
	}
	return
}
```

### What did you expect to see?

That writes will always succeed fully or an error would be returned.

### What did you see instead?

* That `Write` is called only once, so if `Write` writes less than `n` bytes, some bytes are lost and not written out.
* If there is an error during `Write` the number of bytes written is returned to the reader, not the bytes read.

### Possible solution

```golang
func (t *teeReader) Read(p []byte) (n int, err error) {
	n, err = t.r.Read(p)
	for written := 0; written < n; {
		m, err := t.w.Write(p[written:n])
		if err != nil {
			return n, err
		}
		written += m
	}
	return
}
```

Maybe some logic to detect too many empty write attempts should be added there (so if `Write` keeps returning 0 for `m`).

**Comment by seankhliao** [comment] 2022-01-07 13:32
From https://pkg.go.dev/io#Writer
> Write must return a non-nil error if it returns n < len(p)

Write is not allowed to succeed if it's short

Closing as working as intended.

**Closed by seankhliao** 2022-01-07 13:32 UTC

**Comment by mitar** [comment] 2022-01-07 15:46
Interesting. I missed that. Thanks.

But the second point still holds: on error the number of written bytes is returned to the **reader** and not the number of read bytes. I think that should be fixed.

**Comment by seankhliao** [comment] 2022-01-07 16:19
> Any error encountered while writing is reported as a read error.

So the number reported should match the write error

**Comment by mitar** [comment] 2022-01-07 21:45
I would disagree. If reader wants to know where to resume reading after a failure, this is not possible.
