### ISSUE TITLE
Why is this enforced?

### ISSUE THREAD

**Issue by LeanderGangso** [golang/go#60590] opened 2023-06-04 01:32 UTC
https://github.com/golang/go/blob/ce8146ed3361f584ba79427ac6c6d6fe9c297bea/src/net/textproto/reader.go#L632

Just spent way too long figuring out that the reason my api calls to a third party server didn't work was because their server don't recognize the canonical header, but need the capitalization.

Feel like the is an ugly sideeffekt of add().

**Comment by seankhliao** [comment] 2023-06-04 01:53
Duplicate of #5022

**Closed by seankhliao** 2023-06-04 01:53 UTC

**Comment by seankhliao** [comment] 2023-06-04 01:57
Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions
