### ISSUE TITLE
spec: method set of an interface type

### ISSUE THREAD

**Issue by ddaa2000** [golang/go#52321] opened 2022-04-13 06:52 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version 
go version go1.18.1 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ddaa\AppData\Local\go-build
set GOENV=C:\Users\ddaa\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\ddaa\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ddaa\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Users\ddaa\sdk\go1.18.1
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\ddaa\sdk\go1.18.1\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ddaa\AppData\Local\Temp\go-build2786407386=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
[https://go.dev/play/p/uxVambYMVlf](https://go.dev/play/p/uxVambYMVlf)

### What did you expect to see?
In the latest language specification, for method set:
The method set of an interface type is the intersection of the method sets of each type in the interface's type set (the resulting method set is usually just the set of declared methods in the interface).

However, the description "the intersection of the method sets of each type in the interface's type set" is not precies enough. Actually, the method set is only determined by "the set of declared methods in the interface". Even if all the types in the type constraints have a specific method A, if the method A is not included in the "the set of declared methods in the interface", A is still not included in the method set of the interface.

Could we change the documentation to have better definitions on type sets and a method sets?

 ### What did you see instead?

**Comment by seankhliao** [comment] 2022-04-13 08:28
cc @griesemer @ianlancetaylor

**Comment by seankhliao** [comment] 2022-04-13 12:36
Duplicate of #51183

**Closed by seankhliao** 2022-04-13 12:36 UTC
Labels: NeedsInvestigation
