### ISSUE TITLE
spec: can't use blank variable in type switch

### ISSUE THREAD

**Issue by ellisonch** [golang/go#10036] opened 2015-02-28 20:02 UTC
I often want to use a blank variable in a type switch when I'm building scaffolding.  For example:

```.go
package main

import "fmt"

type foo interface { }
type bar struct { }
type baz struct { }

func main() {
	var aFoo foo
	aFoo = bar{}

	switch _ := aFoo.(type) {
		case bar: fmt.Printf("It's a bar!")
		case baz: fmt.Printf("It's a baz!")
		default: fmt.Printf("It's none of these things!")
	}
}
```

I'd like to write this, then go in and fill in some details.  However, trying to run the above results in the following error message:
```
.\blank.go:13: invalid variable name _ in type switch
```

It really wants a variable.  The problem is, I don't want to use a variable yet in my switch, which results in me having to change the code to look like this:
```.go
switch n := aFoo.(type) {
	case bar: 
		_ = n
		fmt.Printf("It's a bar!")
```
just to get the compiler error to go away.

I also tried using `_ =` instead of `_ :=`, and that doesn't work either.

It would be nice if the blank variable were allowed in the type switch.

$ go version
go version go1.4.1 windows/amd64

**Comment by sbinet** [comment] 2015-02-28 20:06
this works:

```go
    switch aFoo.(type) {
        case bar: fmt.Printf("It's a bar!")
        case baz: fmt.Printf("It's a baz!")
        default: fmt.Printf("It's none of these things!")
    }
```
quite nicely (5 characters less, even!)

http://play.golang.org/p/WIB-KQR4Jp

**Comment by bradfitz** [comment] 2015-03-01 17:20
This is consistent with what the spec says:

```
TypeSwitchStmt  = "switch" [ SimpleStmt ";" ] TypeSwitchGuard "{" { TypeCaseClause } "}" .
TypeSwitchGuard = [ identifier ":=" ] PrimaryExpr "." "(" "type" ")" .
```

And "The TypeSwitchGuard may include a short variable declaration" which says, a short variable declaration uses the syntax:

```
ShortVarDecl = IdentifierList ":=" ExpressionList .
```

and "and at least one of the non-blank variables is new".

I'll let @griesemer close this as working-as-intended or decide whether type switches should support blank identifiers somehow.

**Comment by griesemer** [comment] 2015-03-01 20:01
This is working as intended. @sbinet suggestion is the perfect answer for this problem.

Perhaps you're thrown off by the "customized error message": Short variable declarations of the form:

_ := expr

are not permitted and the error is "no new variables on left side of :=". But here it is "invalid variable name _ in switch", indicating that the two situations are not handled by the same check. But the effect is the same, in both cases an invalid program is rejected.

**Closed by griesemer** 2015-03-01 20:01 UTC
