### ISSUE TITLE
x/website: golang.org missing go-import metadata

### ISSUE THREAD

**Issue by hongtaiwang** [golang/go#47906] opened 2021-08-23 08:43 UTC
### What is the URL of the page with the issue?

all packages under  "golang.org/x/..."
 
### What is your user agent?
 

using dep ensure
 
 
### What did you do?
 

 curl -L -s golang.org/x/crypto | grep -i go-import

also when using `dep ensure`
 
 
### What did you expect to see?
 ```
$curl -L -s golang.org/x/crypto | grep -i go-import
<meta name="go-import" content="golang.org/x/crypto git https://go.googlesource.com/crypto"> 
```
 
 
### What did you see instead?
missing go-import metadata

**Comment by seankhliao** [comment] 2021-08-23 10:50
Duplicate of #47905

**Closed by seankhliao** 2021-08-23 10:50 UTC
