### ISSUE TITLE
x/vgo: fails to resolve etcd clientv3 dependency

### ISSUE THREAD

**Issue by mcluseau** [golang/go#26075] opened 2018-06-27 05:26 UTC
### What version of Go are you using (`go version`)?

go version go1.10.2 linux/amd64

### Does this issue reproduce with the latest release?

yes, tried the latest vgo

### What operating system and processor architecture are you using (`go env`)?

GOOS="linux"
GOARCH="amd64"

### What did you do?

`main.go`:
```go
package main

import (
	"fmt"

	"github.com/coreos/etcd/clientv3"
)

func main() {
	fmt.Printf("%+v\n", clientv3.Config{})
}
```

`Dockerfile`:
```
from golang:1.10.2-alpine
run apk update && apk add git
run go get golang.org/x/vgo
add main.go /go/src/test-vgo/
run cd /go/src/test-vgo && touch go.mod && vgo mod -vendor
```

### What did you expect to see?

vgo picking the real latest version of `github.com/coreos/etcd` and resolving the dependencies.

### What did you see instead?

```
Step 5/5 : RUN cd /go/src/test-vgo && touch go.mod && vgo mod -vendor
 ---> Running in 2f29131c6f09
vgo: resolving import "github.com/coreos/etcd/clientv3"
vgo: finding github.com/coreos/etcd/clientv3 latest
vgo: finding github.com/coreos/etcd (latest)
vgo: adding github.com/coreos/etcd v0.5.0-alpha.5
[...]
vgo: import "test-vgo" ->
	import "github.com/coreos/etcd/clientv3" [/go/src/mod/github.com/coreos/etcd@v0.5.0-alpha.5/clientv3]: open /go/src/mod/github.com/coreos/etcd@v0.5.0-alpha.5/clientv3: no such file or directory
vgo: import "github.com/coreos/etcd/clientv3" [/go/src/mod/github.com/coreos/etcd@v0.5.0-alpha.5/clientv3]: open /go/src/mod/github.com/coreos/etcd@v0.5.0-alpha.5/clientv3: no such file or directory
```

**Comment by rsc** [comment] 2018-07-06 03:58
Duplicate of #26238.

**Closed by rsc** 2018-07-06 03:58 UTC
Labels: NeedsInvestigation
