### ISSUE TITLE
Module proxy returning blank page

### ISSUE THREAD

**Issue by icholy** [golang/go#42302] opened 2020-10-30 20:03 UTC
### What did you do?

Tried to list the available versions of a module:

https://proxy.golang.org/github.com/coreos/go-systemd/@v/list

### What did you expect to see?

~~A list of versions as displayed in the pkgsite: https://pkg.go.dev/mod/github.com/coreos/go-systemd?tab=versions~~

A list of `+incompatible` versions prior to v21

### What did you see instead?

A blank page.

**Comment by heschik** [comment] 2020-10-30 20:08
There are no tagged v0 or v1 versions of go-systemd. The versions of, for example, v22, are available at https://proxy.golang.org/github.com/coreos/go-systemd/v22/@v/list.

This is how the proxy protocol works; there is no easy way to discover what major versions of a given module exist.

**Comment by icholy** [comment] 2020-10-30 20:09
@heschik shouldn't the v2-v20 versions be listed with `+incompatible`?

**Comment by heschik** [comment] 2020-10-30 20:13
No. They are appropriately tagged and named in their `go.mod` files, so they aren't `+incompatible`.

Everything you're describing is working as intended, and the Go project doesn't use the issue tracker for questions, so I'm going to close this issue. See https://github.com/golang/go/wiki/Questions for where to ask further. #modules on the Gophers Slack would be a good place.

**Closed by heschik** 2020-10-30 20:13 UTC

**Comment by icholy** [comment] 2020-10-30 20:17
@heschik v1-v20 do not contain a go.mod file.

**Comment by heschik** [comment] 2020-10-30 20:24
My mistake. There is no tagged major version 20; there is a tag `v20` but that is an invalid semver tag and ignored by the Go command. Still working as intended, though.

**Comment by icholy** [comment] 2020-10-30 20:38
I see. I was under the impression that the tag format wasn't as strict. Sorry for the noise!
