### ISSUE TITLE
x/mobile/bind: gobind does not generate exported symbols which are in embedded structure

### ISSUE THREAD

**Issue by ttyh061** [golang/go#13811] opened 2016-01-04 12:21 UTC
Given A and B type as below, but gobind does not generate the exported "Connect()" in A's proxy(java).

type B struct  {
    A
}

func NewB() *B{
return &B{}
}

type A struct {
}

func (a A) Connect() {

}

**Comment by hyangah** [comment] 2016-01-21 16:10
Duplicate of #11318.

Before it being fixed, a workaround is to embed the pointer type. 

type B struct {
  *A
}

**Closed by hyangah** 2016-01-21 16:10 UTC

**Comment by ttyh061** [comment] 2016-01-26 10:32
Hi hyangah:
Tried your workaround, but a another issue appeared:
It seems the embedded type should be located at the same package with B ?

error message: 
gomobile: type gaia/app.WSClient not defined in package client ("gaia/app/revenge/client")
type gaia/app.WSClient not defined in package client ("gaia/app/revenge/client")

Instead I could use another one workaround to solve this issue, although it is not so convenient.

type B struct {
 a A
}
