### ISSUE TITLE
cmd/go: unknown revision while using `go mod -init`

### ISSUE THREAD

**Issue by Juliens** [golang/go#26711] opened 2018-07-31 14:26 UTC
### What version of Go are you using (`go version`)?
go version go1.11beta2 linux/amd64

### Does this issue reproduce with the latest release?
:+1: 

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/juliens/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/juliens/dev/go"
GOPROXY=""
GORACE=""
GOROOT="/home/juliens/.gvm/gos/go1.11beta2"
GOTMPDIR=""
GOTOOLDIR="/home/juliens/.gvm/gos/go1.11beta2/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/juliens/myapp/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build973323575=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
`go mod -init` on a project with Gopkg.lock

### What did you expect to see?
Everything works fine

### What did you see instead?
A lots of error like this one:
```
go: converting Gopkg.lock: stat github.com/go-check/check@ca0bf163426aa183d03fd4949101785c0347f273: unknown revision ca0bf163426aa183d03fd4949101785c0347f273
```

After investigation, it may come from:
```
git fetch -f --depth=1 https://github.com/go-check/check ca0bf163426aa183d03fd4949101785c0347f273:refs/dummy
error: Server does not allow request for unadvertised object ca0bf163426aa183d03fd4949101785c0347f273
```

**Comment by oiooj** [comment] 2018-07-31 15:30
@Juliens Can you show your `Gopkg.lock` file?

**Comment by Juliens** [comment] 2018-07-31 15:39
@oiooj Sure
https://github.com/containous/traefik/blob/1d53077fc7a7dd24ac3bd825991ecafea31c3b41/Gopkg.lock

**Comment by oiooj** [comment] 2018-07-31 15:53
Duplicate of #24087, I will fix it ASAP, Thanks.

**Closed by oiooj** 2018-07-31 15:53 UTC
Labels: modules
