### ISSUE TITLE
time: Now doesn't update when timezone is changed

### ISSUE THREAD

**Issue by tommyblue** [golang/go#46417] opened 2021-05-27 13:59 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

it's the latest release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/tommyblue/src/go/bin"
GOCACHE="/home/tommyblue/.cache/go-build"
GOENV="/home/tommyblue/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/tommyblue/src/go/pkg/mod"
GOOS="linux"
GOPATH="/home/tommyblue/src/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/tommyblue/dev/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/tommyblue/dev/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2846216330=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Changing the system timezone with `timedatectl set-timezone <tz>` doesn't change the output of `time.Now()` until the go program is restarted.

To reproduce, run a simple program that prints `time.Now()`, like the one below, and change the system timezone while it is running.
The output doesn't get updated with the new time/timezone until the program is restarted

```package main

import (
        "fmt"
        "time"
)

func main() {
        for {
                fmt.Println(time.Now().Format(time.RFC3339))
                time.Sleep(1 * time.Second)
        }
}
```

### What did you expect to see?

The datetime should change to the new timezone

### What did you see instead?

The datetime remains the same until the program is restarted

**Comment by mknyszek** [comment] 2021-05-27 14:40
Interesting. Are other applications able to handle this on the fly? I genuinely don't know.

CC @rsc via https://dev.golang.org/owners

**Comment by tommyblue** [comment] 2021-05-27 15:01
Probably changing time zone is something that doesn't happen often, but I'm building a long-living app for an embedded system and users can change the timezone through the app itself (generally at first setup)

**Comment by seankhliao** [comment] 2021-05-27 16:35
Duplicate of #28020

**Closed by seankhliao** 2021-05-27 16:35 UTC
Labels: NeedsInvestigation
