### ISSUE TITLE
x/website: incorrect synopsis for index/suffixarray

### ISSUE THREAD

**Issue by afq984** [golang/go#45614] opened 2021-04-18 00:54 UTC
### What did you do?

Visit https://golang.org/pkg/index/ and https://golang.org/pkg

### What did you expect to see?

![image](https://user-images.githubusercontent.com/4318379/115128471-89fe5700-a010-11eb-9786-a827a5994a87.png)

### What did you see instead?
![image](https://user-images.githubusercontent.com/4318379/115128458-7c48d180-a010-11eb-8300-de1b9e746f3e.png)

Git bisect says https://go-review.googlesource.com/c/website/+/296378

**Comment by seankhliao** [comment] 2021-04-18 08:29
duplicate of #45042 ?

**Comment by afq984** [comment] 2021-04-18 08:47
@seankhliao oops, yes, they looks like the same problem

**Closed** 2021-04-18 09:15 UTC
Labels: NeedsInvestigation
