### ISSUE TITLE
x/pkgsite: "go to latest" points to a pseudo-version in a module package with semantic versions

### ISSUE THREAD

**Issue by seancfoley** [golang/go#53167] opened 2022-05-31 19:01 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br>
<pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOVERSION="go1.17.5"
</pre></details>

### What did you do?

If you go to my module on pkg.go.dev, https://pkg.go.dev/github.com/seancfoley/ipaddress-go then everything looks fine.

When you go to a subfolder https://pkg.go.dev/github.com/seancfoley/ipaddress-go/ipaddr the site thinks that a pseudo-version is the latest, not the correct version 1.2.0.  When you select the correct version ([https://pkg.go.dev/github.com/seancfoley/ipaddr...@v1.2.0/ipaddr](https://pkg.go.dev/github.com/seancfoley/ipaddress-go@v1.2.0/ipaddr)) there is a bright-red "go to latest" button to take you to a pseudo-version.

How did this happen you ask?

The go modules documentation was not entirely clear that you cannot use normal versioning numbering (eg v1.0.0) if you do not put the go.mod file at the root if the repository. So initially I had the go.mod in the package ipaddr. After a lot of trial and error I realized that to use normal semantic versioning I had to move the go.mod, so the go.mod is now placed it at the root of the repo.  

That left me with this problem.  I have tried many things but I cannot make that red button go away.  

I have tried all sorts of ways of retracting the pseudo-versions but nothing works.  I cannot retract using the new go mod in ipaddress-go, that does nothing.  I cannot retract using the old go mod in the sub-folder ipaddress-go/ipaddr because any retraction creates a new pseudo-version.  Creating proper semantic versions of ipaddress-go never gets rid of the pseudo-version either.

### What did you expect to see?

version 1.2.0 should be marked the latest

<img width="774" alt="Screen Shot 2022-05-31 at 2 52 05 PM" src="https://user-images.githubusercontent.com/19226957/171263922-3a39a76c-7364-41db-9881-2e278b8f6283.png">

### What did you see instead?

Version 0.0.0-...-eb05ef1 is marked the latest

<img width="717" alt="Screen Shot 2022-05-31 at 2 52 26 PM" src="https://user-images.githubusercontent.com/19226957/171263848-0ca548a9-46d5-45d6-813d-ace8f08e802e.png">

**Comment by bcmills** [comment] 2022-05-31 20:45
This looks like another instance of #39007.

https://proxy.golang.org/github.com/seancfoley/ipaddress-go/ipaddr/@latest reports the last version of the nested module that existed, before it was removed in https://github.com/seancfoley/ipaddress-go/commit/f8f610bf6d7db6400d996012d674dac19a254aa4. Since that module has the longer path, both `go get` and pkg.go.dev prefer to resolve the package from that module.

The short-term workaround is to restore the `go.mod` file in some commit, have it `retract` all versions of itself, and push and tag that commit with something like `ipaddr/v0.0.0-retracted`. Then the proxy will notice that version, and (at least in theory) pkg.go.dev should suppress the retracted module unless it is requested explicitly.

Longer-term, I'd still like the proxy to have a more ergonomic behavior for this sort of module-boundary change. 😞

**Comment by bcmills** [comment] 2022-05-31 20:45
Duplicate of #39007

**Closed by bcmills** 2022-05-31 20:45 UTC
Labels: pkgsite
