### ISSUE TITLE
cryto/x509 certificate verify issue.

### ISSUE THREAD

**Issue by jaskirat123** [golang/go#26689] opened 2018-07-30 11:13 UTC
go version go1.9.5 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/maro/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/11/38jcs4dx1g96_zdyxmyxyl3m0000gp/T/go-build065968844=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

i am implementing ssl in my server code.

here is sample code.

	config := &tls.Config{}

	// Load client cert
	cert, err := tls.LoadX509KeyPair("cert file", "key file")
	if err != nil {
		fmt.Println("Error! X509KeyPair:", err)
	}

	config.Certificates = []tls.Certificate{cert}

	// tcp to tls
	tlsConn := tls.Server(conn, config)
	defer closeTlsConn(tlsConn)

	// tls handshake
	err = tlsConn.Handshake()
	if err != nil {
		fmt.Println("Error! tls handshake:", err)
	}

  the above tls server is giving error with golang client
  **x509: certificate has expired or is not yet valid**

But, whereas same server with same certificate and key is working fine with ruby client.

i have gone through source code of x509 and diagnosis the error.
following code lines in verify method causing issue:

if now.Before(c.NotBefore) || now.After(c.NotAfter) {
		return CertificateInvalidError{c, Expired, ""}
	}

https://golang.org/src/crypto/x509/verify.go

i don't know how it is verifying the certificate.There is issue with time of certificate with golang client.

Could anyone please help me?

**Comment by ALTree** [comment] 2018-07-30 11:19
Well... what is the validity period of the certificate (`Not Before` and `Not After`)?

**Comment by jaskirat123** [comment] 2018-07-30 11:45
Hey @ALTree Thanks for quick reply
i have printed values for above
current time it is showing is 2018-07-30 07:41:10.077738782 -0400 EDT m=+0.013358320
Not Before: 2015-08-19 01:17:39 +0000 UTC
Not After: 2016-08-09 01:16:32 +0000 UTC

and Not After condition is getting true out of both.

**Comment by ALTree** [comment] 2018-07-30 11:51
The certificate is expired, since the current time is after the `NotAfter` timestamp. The Go package is working as intended, I don't think there's a bug here. 

I don't know why the certificate is accepted by the Ruby library you are using. It's possible that you configured it (on purpose, or by mistake) to skip validity verification.

Anyway, the Go project does not use its bug tracker for general discussion or asking questions. The Github bug tracker is only used for tracking bugs. This does not appear to be a Go bug, so I'm closing this issue.

If you want more help with your program, please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

**Closed by ALTree** 2018-07-30 11:51 UTC

**Comment by jaskirat123** [comment] 2018-07-31 10:08
@ALTree yes it was certificate problem.Now it's working fine with new certificates.
