### ISSUE TITLE
Extremely unclear how to enable/disable the go install cache

### ISSUE THREAD

**Issue by ORESoftware** [golang/go#38969] opened 2020-05-08 22:23 UTC
### What version of Go are you using (`go version`)?

<pre>
1.13, 1.14, latest
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alex/Library/Caches/go-build"
GOENV="/Users/alex/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/alex/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qh/l8tr6tfd3gv7fmdg0b5z0p340000gn/T/go-build623026823=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

Asked on SO, got no satisfactory answers.  I am looking for something like this:

```
go mod download  # 3 weeks ago
go install  --use-cache-even-if-its-very-old  --how-old='like-3-weeks-old'
```

As you can see from the question in the link on StackOverflow - I am running `go mod download` from a different folder (in /tmp/xyz) if that's kosher, I assume it is.  I want to make sure that `go install` is using the cache created by `go mod download` even if the cache is ancient (for example in use with a Docker cache layer).

I have this question on SO:
https://stackoverflow.com/questions/61688062/how-to-confirm-that-go-is-using-the-cache-created-by-go-mod-download?noredirect=1#comment109117142_61688062

**Comment by agnivade** [comment] 2020-05-09 12:41
>  I am running go mod download from a different folder (in /tmp/xyz) if that's kosher, I assume it is. 

It's not. In module mode, the go.mod file detected by the Go toolchain depends on where you are: https://golang.org/cmd/go/#hdr-The_go_mod_file.

From your SO question, you are mixing module mode with GOPATH mode. Module mode will download in the module cache, GOPATH mode will fill up the GOPATH.

I would suggest you to wait for some more time to let others answer your question properly, or feel free to ask in other forums.

I will close this as this is not a bug, and we don't use the issue tracker to track questions.

**Closed by agnivade** 2020-05-09 12:41 UTC
