### ISSUE TITLE
cmd/run: Can't interrupt go run

### ISSUE THREAD

**Issue by palsivertsen** [golang/go#58580] opened 2023-02-17 15:29 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pal/.cache/go-build"
GOENV="/home/pal/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pal/projects/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pal/projects/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1890082785=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.20.1 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.20.1
uname -sr: Linux 6.1.12-arch1-1
/usr/lib/libc.so.6: GNU C Library (GNU libc) stable release version 2.37.
</pre></details>

### What did you do?

I used the following example from [os/signal](https://pkg.go.dev/os/signal#example-Notify-AllSignals):
```go
package main

import (
	"fmt"
	"os"
	"os/signal"
)

func main() {
	// Set up channel on which to send signal notifications.
	// We must use a buffered channel or risk missing the signal
	// if we're not ready to receive when the signal is sent.
	c := make(chan os.Signal, 1)

	// Passing no signals to Notify means that
	// all signals will be sent to the channel.
	signal.Notify(c)

	// Block until any signal is received.
	s := <-c
	fmt.Println("Got signal:", s)
}
```

I ran the program using `go run ./main.go`. As expected it'll wait for any signal, print the first signal and then exit. No surprises here.

Then I tried to interrupt the program using the `kill` command:
![image](https://user-images.githubusercontent.com/11890143/219694354-7faedecc-c388-4953-815e-e16befb6d543.png)
This has no effect. If I send the kill signal, then the child process is orphaned:
![image](https://user-images.githubusercontent.com/11890143/219694539-2771779a-f48e-4f9a-9994-3c5c1d1b825a.png)

Interrupting the program using `CTRL^C` works as normal.

### What did you expect to see?

Interrupting `go run` should propagate the signal to the child process.

### What did you see instead?

`go run` ignores external(?) signals.

**Comment by vatine** [comment] 2023-02-17 15:39
I would not normally expect a program to propagate signals it receives to its children. The reason that the SIGINT triggered by Ctrl-C is sent to the child program in your case is because that signal is sent to the "process running in the foreground, attached to the terminal", which would not be go run, but the program started by go run.

**Comment by seankhliao** [comment] 2023-02-17 15:56
Duplicate of #40467

**Closed by seankhliao** 2023-02-17 15:56 UTC
