### ISSUE TITLE
making byte slice with int capacity is much more slower than const int capacity

### ISSUE THREAD

**Issue by ideawu** [golang/go#46950] opened 2021-06-28 07:30 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1488837135=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
$ cat b_test.go 

package t

import (
	"testing"
)

func Benchmark_make_var(b *testing.B) {
    var nn = 256
    for i := 0; i < b.N; i++ {
        s := make([]byte, 0, nn)
        _ = s
    }
}
func Benchmark_make_const(b *testing.B) {
    const nn = 256
    for i := 0; i < b.N; i++ {
        s := make([]byte, 0, nn)
        _ = s
    }
}

$ go test -bench Benchmark_make -run . -benchmem
goos: linux
goarch: amd64
pkg: bds_tool
cpu: Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz
Benchmark_make_var-40      	13915761	        79.40 ns/op	     256 B/op	       1 allocs/op
Benchmark_make_const-40    	1000000000	         0.4558 ns/op	       0 B/op	       0 allocs/op
PASS
```

### What did you expect to see?

I would expect both way to make byte slice has the same efficiency.

### What did you see instead?

Making a slice by passing capacity with a `int` variable is much slower than passing with a `const int`. There would be many cases that we would use `int` capacity instead of `const int`. For example, one may write

```
var nn int
if some < 64 {
    nn = 64
} else if some < 128 {
    nn = 128
} else {
    nn = 1024
}
buf := make([]byte, 0, nn)
```

instead of

```
var buf []byte
if some < 64 {
    buf = make([]byte, 0, 64)
} else if some < 128 {
    buf = make([]byte, 0, 128)
} else {
    buf = make([]byte, 0, 1024)
}
```

It would happen that the first way is lot more slower than the second way.

**Comment by davecheney** [comment] 2021-06-28 10:37
Two things

> Benchmark_make_const-40    	1000000000	         0.4558 ns/op	       0 B/op	       0 allocs/op

0.4ns per iteration at a few ghz is basically 2-3 instructions. Your benchmark has been completely optimised away; 

The reason why this can happen with a const initaliser is this permits the compiler to allocate the slice on the stack as its size is known (this is also theoretically possible using a variable, but that work remains un finished), after that, the compiler can tell you're not doing anything with the slice so it elides the creation and non use leaving you with an empty loop, which compilers and processors are _really_ good at optimising.

**Comment by mvdan** [comment] 2021-06-28 10:46
Adding to what @davecheney said, I'd use https://golang.org/wiki/Questions for asking about Go code that you think should be faster, and only raise an issue when you're pretty certain that you have found a specific Go bug or optimization that hasn't been brought up before.

**Comment by seankhliao** [comment] 2021-06-28 11:13
Closing as not a bug

**Closed by seankhliao** 2021-06-28 11:13 UTC
