### ISSUE TITLE
/usr/lib/golang/pkg/windows_amd64 missing and VSC cannot build properly

### ISSUE THREAD

**Issue by hunter86bg** [golang/go#26651] opened 2018-07-27 20:05 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.3 linux/amd64
golang-bin-1.10.3-1.fc28.x86_64

### Does this issue reproduce with the latest release?
Yes, current release is the latest release

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/snikolov/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/snikolov/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build687330301=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
Set variables for GOOS and GOARCH in Visual Studio Code for cross compiling:
-> "go.toolsEnvVars": {"GOOS":"windows","GOARCH": "amd64"}
and build on save 
->  go.buildOnSave
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
Open in Visual Studio Code "Hello World" and save to trigger a build job.
Errors detected:
go build errors: open /usr/lib/golang/pkg/windows_amd64/errors.a: permission denied
go build internal/race: open /usr/lib/golang/pkg/windows_amd64/internal/race.a: permission denied
go build runtime/internal/atomic: open /usr/lib/golang/pkg/windows_amd64/runtime/internal/atomic.a: permission denied
go build runtime/internal/sys: open /usr/lib/golang/pkg/windows_amd64/runtime/internal/sys.a: permission denied
go build sync/atomic: open /usr/lib/golang/pkg/windows_amd64/sync/atomic.a: permission denied
go build internal/cpu: open /usr/lib/golang/pkg/windows_amd64/internal/cpu.a: permission denied
go build internal/syscall/windows/sysdll: open /usr/lib/golang/pkg/windows_amd64/internal/syscall/windows/sysdll.a: permission denied
go build unicode/utf16: open /usr/lib/golang/pkg/windows_amd64/unicode/utf16.a: permission denied
go build unicode/utf8: open /usr/lib/golang/pkg/windows_amd64/unicode/utf8.a: permission denied
go build unicode: open /usr/lib/golang/pkg/windows_amd64/unicode.a: permission denied

Also reported in issue: https://github.com/Microsoft/vscode-go/issues/1808

### What did you expect to see?
/usr/lib/golang/pkg/windows_amd64 to exist.

### What did you see instead?
/usr/lib/golang/pkg/windows_amd64 missing

**Comment by agnivade** [comment] 2018-07-28 03:54
I am slightly puzzled. You are already on linux/amd64, and yet you are "cross-compiling" to linux/amd64 ?

From the errors, it seems like a permission issue. Are you sure the go binary has read/write permissions to /usr/lib/golang ?

**Comment by hunter86bg** [comment] 2018-07-28 05:38
I'm sorry for the confusion.
I'm coding on Fedora28 for windows x86_64 (and I've corrected the initial comment).

Actually the folder does not exist at all, and that's why I've opened this issue.

**Comment by hunter86bg** [comment] 2018-07-28 16:05
The problem is that the console commands work as usual (described in https://github.com/Microsoft/vscode-go/issues/1808) but VSC needs the dir in order to build on save.

**Comment by hunter86bg** [comment] 2018-07-28 17:39
If you need , I'm attaching strace for "go build" and "go build -i" .
[go-build-strace.zip](https://github.com/golang/go/files/2238172/go-build-strace.zip)
[go-build-strace-with-I.zip](https://github.com/golang/go/files/2238173/go-build-strace-with-I.zip)

**Comment by AlexRouSg** [comment] 2018-07-28 22:38
Dupe of #26071 

This is working as intended, you have a few choices on what to do.

- Get VS Code to stop using `-i`

- Don't cross compile in VS Code

- Run the build command as root with `-i` once to populate the folder `GOOS=windows GOARCH=amd64 go build -i` after which it should not be trying to write those files.

**Comment by agnivade** [comment] 2018-07-29 04:19
Thanks for providing with the console commands. Yes, if you are using `-i` to cross-compile, then you need to have write permissions to $GOROOT/pkg. Either have the permissions, or do not use `-i`.

Closing since this is working as intended.

**Closed by agnivade** 2018-07-29 04:19 UTC
