### ISSUE TITLE
cmd/vet: incorrectly errors when importing parameterized function in a test

### ISSUE THREAD

**Issue by jakecoffman** [golang/go#47915] opened 2021-08-23 14:17 UTC
### What version of Go are you using (`go version`)?

<pre>
$ gotip version
go version devel go1.18-4fbb5c8 Mon Aug 23 13:09:18 2021 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

No, using generics on gotip.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ gotip env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jake/Library/Caches/go-build"
GOENV="/Users/jake/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jake/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jake/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/jake/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/jake/sdk/gotip/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="devel go1.18-4fbb5c8 Mon Aug 23 13:09:18 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jake/personal/generics/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/25/cxtbvqr178x9rfg976_gqmxr0000gp/T/go-build766177970=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I created a repo here: https://github.com/jakecoffman/generics

Create a package `math` with `min.go` as follows:

```
package math

type comparable interface {
	~int
}

func Min[T comparable](a ...T) T {
	m := a[0]
	for _, v := range a {
		if m > v {
			m = v
		}
	}
	return m
}
```

Outside of package `math` create a test that imports the parameterized Min:

```
package main

import (
	"github.com/jakecoffman/generics/math"
	"testing"
)

func TestMath(t *testing.T) {
	a, b := 1, 2
	if math.Min(a, b) != 1 {
		t.Error(math.Min(a, b))
	}
}
```

Then run `gotip test ./...`.

### What did you expect to see?

A passing test

### What did you see instead?

```
vet: ./main.go:5:2: could not import github.com/jakecoffman/generics/math (cannot import "github.com/jakecoffman/generics/math" (unexpected parameterized function/method), possibly version skew - reinstall package)
```

It works outside of a test, or in a test in the same module as the definition of the parameterized function.

**Comment by timothy-king** [comment] 2021-08-31 18:03
The example reproduces. I am seeing the same failure on `gotip test ./...` from within `generics/`  after cloning https://github.com/jakecoffman/generics @ 9eb67dd.

```
$ gotip version
go version devel go1.18-144e0b1f6e2 Tue Aug 31 17:35:15 2021 +0000 linux/amd64
```

Observations:
* `$ gotip test ./math` passes. 
* `$ gotip test .` has the same problem.
* `$ gotip run main.go` runs and prints "OK!".
* `$ gotip vet ./math` passes.
* `$ gotip vet .` has the same problem.

Replacing min.go with a version without generics will pass `gotip test ./...`. Content:
```go
func Min(a ...int) int {
	m := a[0]
	for _, v := range a {
		if m > v {
			m = v
		}
	}
	return m
}
```
So it looks like this is specific to generics and blocks the test from passing.

**Comment by timothy-king** [comment] 2021-08-31 21:54
Looks like this is a duplicate of https://github.com/golang/go/issues/48101

**Closed** 2021-08-31 23:14 UTC
Labels: NeedsDecision, Analysis
