### ISSUE TITLE
gccgo-go vs. go discrepancy for eval order

### ISSUE THREAD

**Issue by ratnikov** [golang/go#24317] opened 2018-03-09 01:01 UTC
### What version of Go are you using (`go version`)?
$ gccgo-go version
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64

### Does this issue reproduce with the latest release?
It works with non-gcc go.

### What operating system and processor architecture are you using (`go env`)?
$ gccgo-go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr"
GOTOOLDIR="/usr/lib/gccgo/tool"
TERM="dumb"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CXX="g++"
CGO_ENABLED="1"

### What did you do?
https://play.golang.org/p/V4-aR5AR5N7

It works on playground, but with gccgo-go it errors out:
$ gccgo-go run repro.go
2018/03/08 19:56:50 Wrong value returned: []
exit status 1

### What did you expect to see?
All good!

### What did you see instead?
Wrong value returned: []

**Comment by randall77** [comment] 2018-03-09 01:08
This is probably a duplicate of #23188 .
We should consider all these order-of-evaluation issues together.
I'll close this, and if it doesn't get solved as part of the solution for #23188 we can reopen.

**Closed by randall77** 2018-03-09 01:08 UTC
