### ISSUE TITLE
net/http: Http error message

### ISSUE THREAD

**Issue by antichown** [golang/go#41406] opened 2020-09-15 16:40 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
 go version

go version go1.15.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

 go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/linux/.cache/go-build"
GOENV="/home/linux/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/linux/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/linux/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build818678076=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

although there is no error message code in the codes to write to the screen, it gives this error

2020/09/15 19:35:22 Unsolicited response received on idle HTTP channel starting with "\r\n"; err=<nil>
2020/09/15 19:35:24 Unsolicited response received on idle HTTP channel starting with "\r\n"; err=<nil>

the software works, but it constantly prints this error

**Comment by toothrot** [comment] 2020-09-15 19:56
Could you provide an example of the code that produced the error, preferably as a [Go playground](https://play.golang.org/) link?

**Comment by antichown** [comment] 2020-09-15 21:51
![testtttt](https://user-images.githubusercontent.com/4655942/93268702-53303c00-f7b6-11ea-8d64-37e5367c7a39.png)

it is difficult to find which one gives the problem because the site address from txt is too much, but I saw that it gives it on this site by debugging.

as you can see, the error message gives an nil answer, but it gives an error

**Comment by AlexanderYastrebov** [comment] 2021-10-16 16:21
Looks like duplicate of https://github.com/golang/go/issues/19895

**Comment by seankhliao** [comment] 2021-12-21 22:05
Duplicate of #19895

**Closed by seankhliao** 2021-12-21 22:05 UTC
Labels: WaitingForInfo, NeedsInvestigation
