### ISSUE TITLE
Go vet misses closure using variable from outer loop

### ISSUE THREAD

**Issue by dmowcomber** [golang/go#32876] opened 2019-07-01 19:01 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env |egrep 'GOOS|GOARCH'
GOARCH="amd64"
GOOS="darwin"
</pre></details>

### What did you do?

Normally `go vet` return an error if you have a loop with a goroutine function call with closure:
`./prog.go:17:23: loop variable i captured by func literal`
https://play.golang.org/p/PAg99GZMa7__8

But if you have nested loops with a closure that captures a variable from the outerloop and you have a goroutine inside an inner loop `go vet` will not return an error.
https://play.golang.org/p/zDsGfz0iESI

### What did you expect to see?

<pre>
./prog.go:16:22: loop variable i captured by func literal
Go vet exited.

10 10 10 10 10 10 10 10 10 10 
</pre>
`go vet` returned an error: `loop variable i captured by func literal`
https://play.golang.org/p/PAg99GZMa7__8

### What did you see instead?

<pre>
10 10 10 10 10 10 10 10 10 10 
</pre>
same results but no `go vet` error
https://play.golang.org/p/zDsGfz0iESI

**Comment by bcmills** [comment] 2019-07-01 20:33
Duplicate of #16520

**Closed by bcmills** 2019-07-01 20:33 UTC
