### ISSUE TITLE
cmd/go: go get @downgrade should log when dependencies are removed

### ISSUE THREAD

**Issue by misterpickypants** [golang/go#37764] opened 2020-03-09 21:08 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### What did you do?

I installed a binary via `go get` at an older version than the corresponding lib that I was using. This silently removed a seemingly unrelated dependency, cause a subsequent build of my package to fail because the dependency was automatically re-added, but at the latest version.

```
module myproject

go 1.14

require (
  github.com/some/lib v1.1.0   // depends on github.com/other/lib v1.5.0
  github.com/other/lib v1.5.0
  ...
)
```
Installing an old binary via `go get github.com/other/lib/cmd/binary v1.4.0` can remove the dependency on `github.com/some/lib` if there is no old version of `some/lib` that matches the `v1.4.0` target.

*The problem is that this removal is completely silent.*

A subsequent build of `myproject` will automatically re-add the dependency, but at the latest version.

### What did you expect to see?

I'd like a clear message indicating if seemingly unrelated dependencies are removed because no acceptable combination of versions was found.

**Comment by bcmills** [comment] 2020-03-09 21:10
Duplicate of #33284

**Comment by bcmills** [comment] 2020-03-09 21:10
(or at least a specific instance of it.)

**Closed by bcmills** 2020-03-09 21:10 UTC
