### ISSUE TITLE
cmd/go2go: generic types as return parameters breakages

### ISSUE THREAD

**Issue by carnott-snap** [golang/go#39674] opened 2020-06-18 02:13 UTC
### What did you do?
https://go2goplay.golang.org/p/5qj5r_lSwoK
https://go2goplay.golang.org/p/J9UMhLZJZyH

### What did you expect to see?
```
{true}
```

### What did you see instead?
```
prog.go2:16:67: expected operand, found 'return'
```
and
```
prog.go2:11:41: mixed named and unnamed function parameters (and 1 more errors)
```

### Did you find a workaround?
In both cases adding names to the parameters fixed things, so it seems like the parser is broken:

https://go2goplay.golang.org/p/5sJXISHuwAb
https://go2goplay.golang.org/p/9TgTCD5SLnZ

**Comment by martisch** [comment] 2020-06-18 04:45
Duplicate of #39655.

https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md#using-generic-types-as-unnamed-function-parameter-types

**Closed by martisch** 2020-06-18 04:45 UTC

**Comment by gertcuykens** [comment] 2020-06-18 06:10
Also Duplicate of https://github.com/golang/go/issues/39656

PS Because of how many people run into this, can there be at least one of them open to investigate if the compiler error message can be improved in all does cases?

**Comment by carnott-snap** [comment] 2020-06-20 18:12
There were two syntaxes that I came across that did not work. The second seems covered by #39656, but the first seems like a bug, since this fails (but only for closures):
```go
f := func(b bool) Box(string) { return Box(string){strconv.FormatBool(b)} }
```
