### ISSUE TITLE
x/pkgsite: is the initial parenthesis really necessary for left hand side menu?

### ISSUE THREAD

**Issue by pjebs** [golang/go#40744] opened 2020-08-13 02:01 UTC
![image](https://user-images.githubusercontent.com/5377970/90085993-aef14a80-dd5c-11ea-9edb-5cac0e88f72c.png)

**(o) XXXXX()**

**Comment by andybons** [comment] 2020-08-13 20:17
It’s important to be able to discern between a method and a function that returns that type.

https://pkg.go.dev/time?tab=doc#Date shows an example of this.

Is there an alternative you suggest?

**Comment by pjebs** [comment] 2020-08-13 21:34
What about an asterisk or italicized lower case c for constructors and nothing for everything else

**Comment by pjebs** [comment] 2020-08-13 21:36
Also worth a note: there seems to be far fewer constructors that methods.

**Comment by pjebs** [comment] 2020-08-14 03:25
![image](https://user-images.githubusercontent.com/5377970/90210576-a9b1ff80-de31-11ea-9282-fe0109cdcb98.png)

**Comment by andybons** [comment] 2020-08-18 21:48
Duplicate of #40612

**Closed by andybons** 2020-08-18 21:48 UTC
Labels: UX, WaitingForInfo, pkgsite

**Comment by pjebs** [comment] 2020-08-18 21:52
@andybons this issue is not even related to #40612   was it closed by mistake?

**Comment by andybons** [comment] 2020-08-19 18:37
@pjebs it concerns the design of the left-hand nav and the presentation of its contents, so I merged it into that issue.
