### ISSUE TITLE
cmd/asm: macro invocation cannot span more than one line

### ISSUE THREAD

**Issue by WojciechMula** [golang/go#54108] opened 2022-07-28 06:20 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.1 linux/amd64
</pre>

### What did you do?

I tried to assemble the following asm code with a macro:

```
#define TRIPLE_U64(name, x, y, z)          \
    DATA name<>+(0)<SB>, x                 \
    DATA name<>+(8)<SB>, y                 \
    DATA name<>+(16)<SB>, z                \
    GLOBAL name<>(SB), RODATA|NOPTR, 24

TRIPLE_U64(test,
    $1,  // first
    $2,  // second
    $3   // third
)
```

### What did you expect to see?

No errors.

### What did you see instead?

Error: `unterminated arg list invoking macro: TRIPLE_U64`

**Comment by cherrymui** [comment] 2022-07-28 13:59
The macro syntax the Go assembler supports is limited. It is intentional to not support all the syntax the C preprocessor. (And, if you run your example in the C preprocessor the result you get might not be what you expected.) Closing as working as intended. Thanks.

**Closed by cherrymui** 2022-07-28 13:59 UTC
Labels: compiler/runtime
