### ISSUE TITLE
x/tools/cmd/present: support sub-sections in slides

### ISSUE THREAD

**Issue by griesemer** [golang/go#11434] opened 2015-06-26 21:17 UTC
For the following input (bug.slide):
```
Title

* Subtitle

** foo
- abc

** bar
- abc
```
the 2nd page looks like this:

![screen shot 2015-06-26 at 2 15 20 pm](https://cloud.githubusercontent.com/assets/8528975/8387510/d01d6aec-1c0d-11e5-95d5-5996bcde1d0a.png)

That is, the subtitles are printed on top of each other. Generally, they don't seem to do what would be expected.

This is on tip, using Chrome (Version 42.0.2311.152 (64-bit)) on OS X Yosemite (Version 10.10.3 (14D136)).

**Comment by adg** [comment] 2015-06-29 01:09
Subtitles aren't supported in the slide output of present. They're for the blog and other mediums.

**Comment by adg** [comment] 2015-08-27 01:38
Dupe of #6846

**Closed by adg** 2015-08-27 01:38 UTC
