### ISSUE TITLE
go.mod: replace can cause to have multiple instances of same package

### ISSUE THREAD

**Issue by Pitasi** [golang/go#36498] opened 2020-01-10 16:42 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/antonio/.cache/go-build"
GOENV="/home/antonio/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/antonio/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/inited_twice/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build539111164=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Not sure if that's working as intended or it's a bug. My sample code can be found here: https://github.com/Pitasi/gomod-replace

### What did you expect to see?

```
init
main: 43
main: 43
```

### What did you see instead?
actual:
```
init
init
main: 43
main: 42
```

**Comment by bcmills** [comment] 2020-01-10 16:56
Please either write out the example code inline or link to a publicly-available repository.

**Comment by Pitasi** [comment] 2020-01-10 17:00
sure sorry, here you go https://github.com/Pitasi/gomod-replace

I slightly changed my code to simplify even more.
New expected output
```
init
main: 43
main: 43
```

actual:
```
init
init
main: 43
main: 42
```

**Comment by bcmills** [comment] 2020-01-10 17:06
Duplicate of #34417

**Closed by bcmills** 2020-01-10 17:06 UTC
Labels: WaitingForInfo, modules
