### ISSUE TITLE
x/crypto/acme/autocert: make hybrid ecc-rsa certificates possible

### ISSUE THREAD

**Issue by phuslu** [golang/go#23698] opened 2018-02-05 09:30 UTC
I manage to implement a go https server to support hybird ecc-rsa certificats. [1]
Here're my codes
```go
func (m *MyManager) GetCertificate(hello *tls.ClientHelloInfo) (*tls.Certificate, error) {
	if HasECCCiphers(hello) {
		return m.ecc.GetCertificate(hello)
	} else {
		return m.rsa.GetCertificate(hello)
	}
}

func (m *MyManager) HTTPHandler(fallback http.Handler) http.Handler {
	if m.ecc == nil {
		m.ecc = &autocert.Manager{
			Cache:      autocert.DirCache("ecc"),
			Prompt:     autocert.AcceptTOS,
			HostPolicy: m.HostPolicy,
			ForceRSA:   false,
		}
	}
	if m.rsa == nil {
		m.rsa = &autocert.Manager{
			Cache:      autocert.DirCache("rsa"),
			Prompt:     autocert.AcceptTOS,
			HostPolicy: m.HostPolicy,
			ForceRSA:   true,
		}
	}
	return m.ecc.HTTPHandler(m.rsa.HTTPHandler(fallback))
}
```
It does not work because of autocert http-01 HTTPHandler does not *fallback* as I expected.
A quick patch is
```patch
diff --git a/acme/autocert/autocert.go b/acme/autocert/autocert.go
index e7edb3029..b9bf0cd31 100644
--- a/acme/autocert/autocert.go
+++ b/acme/autocert/autocert.go
@@ -278,7 +278,7 @@ func (m *Manager) HTTPHandler(fallback http.Handler) http.Handler {
 		}
 		data, err := m.httpToken(ctx, r.URL.Path)
 		if err != nil {
-			http.Error(w, err.Error(), http.StatusNotFound)
+			fallback.ServeHTTP(w, r)
 			return
 		}
 		w.Write(data)
```
Is this requirement/change reasonable? Thought?

1. https://scotthelme.co.uk/hybrid-rsa-and-ecdsa-certificates-with-nginx/

**Comment by phuslu** [comment] 2018-02-05 09:35
a bit related to https://github.com/golang/go/issues/19265

**Comment by bradfitz** [comment] 2018-02-05 19:02
You kinda jumped to a solution without explaining the problem. I also don't see enough of your code to see how you're using your `MyManager` or how it's defined.

I suppose the subject is a reasonable problem statement ("make hybrid ecc-rsa certificates possible"), but if this is an important problem to solve (@agl, @x1ddos?), and we can detect it (e.g. your `HasECCCiphers`), then it seems like we'd just do it automatically without adding new API (like #19265) and without requiring the hoops you seem to be going through.

**Comment by agl** [comment] 2018-02-05 19:44
ECDSA certificates issued from an RSA CA are a reasonable thing to desire: the ECDSA operation is much faster.

Google's services, for example, often have both and select ECDSA when possible, and RSA as a fallback.

To do this, you would check the [`ClientHelloInfo`](https://godoc.org/crypto/tls#ClientHelloInfo) and use ECDSA certificates when the client offers ECDSA ciphersuites that are also in the server's config, supports the curve used by the certificate (almost always P-256), supported uncompressed points, and ECDSA signature schemes.

On niggle is that crypto/tls doesn't export its knowledge of ciphersuites, so the map of uint16 cipher suite ID to whether it's ECDSA would have to be maintained externally.

**Comment by FiloSottile** [comment] 2018-02-05 22:17
As far as I understand this issue is not about supporting ECDSA+RSA on the crypto/tls side (which is done as @agl suggests and partially hidden in `HasECCCiphers`), but about running multiple autocert.Manager simultaneously (in order to obtain the two certificates) by chaining their HTTPHandler.

The expectation is that it would work because of the fallback mechanism, but the outer HTTPHandler doesn't fallback if the path is `/.well-known/acme-challenge/`, even if it doesn't recognize the token, and returns 404 instead.

https://github.com/golang/crypto/blob/13931e22f9e72ea58bb73048bc752b48c6d4d4ac/acme/autocert/autocert.go#L281

I think the full solution is to check for the token first, fallback if not found, and then apply the host policy. Seems reasonable to me.

Title suggestion: "x/crypto/acme/autocert: support running multiple HTTPHandler"

**Comment by bradfitz** [comment] 2018-02-05 22:59
@FiloSottile, what I was trying to say was that if ECDSA+RSA is something that enough people want, we should just do it automatically, rather than make this bug about easing an obscure workaround for us not supporting their real need.

**Comment by FiloSottile** [comment] 2018-02-06 00:14
Oh I see. You're right, we can implement ECDSA+RSA without any API change since GetCertificate takes the ClientHelloInfo. However I think this will count double against the per-domain Let's Encrypt rate-limit, which is probably not what users want by default.

**Comment by x1ddos** [comment] 2018-02-07 10:44
It is reasonable to say this is a duplicate of #22066?

**Comment by bradfitz** [comment] 2018-02-07 16:37
@x1ddos, yes. I'll close this one.

**Closed by bradfitz** 2018-02-07 16:37 UTC
