### ISSUE TITLE
how to know whether struct method by reflect equal

### ISSUE THREAD

**Issue by guogeer** [golang/go#25778] opened 2018-06-07 09:34 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10.1 

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
test code below:
type Child struct{}

func (c *Child) Say() {
    fmt.Print("child say")
}

type Father struct {
    *Child
}

func (father *Father) Say() {
    fmt.Print("father say")
}

func main() {
    father := &Father{}
    say1 := reflect.ValueOf(father).Method(0)
    say2 := reflect.ValueOf(father.Child).Method(0)
    fmt.Println("struct method equal: ", say1.Pointer(), say2.Pointer())
    // how can i know than say1 is different from say2
    // i try say1.Pointer() == say2.Pointer(), but not ok
    // i know say1.Pointer() return methodValueCall 
}       
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
how can i know than say1 is different from say2

### What did you see instead?
i don't know how to do

**Comment by ALTree** [comment] 2018-06-07 09:43
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2018-06-07 09:43 UTC
