### ISSUE TITLE
x/tools/gopls: formatting adds terminal newlines

### ISSUE THREAD

**Issue by myitcv** [golang/go#35312] opened 2019-11-01 18:26 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +03bb3e9ad1 Wed Oct 16 06:29:51 2019 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20191101175824-a860bcda08c7
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.1.8-0.20191101175824-a860bcda08c7
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build529515694=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

With the following input:

```go
package main

func main() {
	println("Hello, world!")
}



  
  
```

and calling `Formatting`.

### What did you expect to see?

Edits that result in:

```go
package main

func main() {
	println("Hello, world!")
}
```

consistent with the results from `gofmt`

### What did you see instead?

Edits that result in:

```go
package main

func main() {
	println("Hello, world!")
}
  
```

This is because the following response was received:

```
gopls.Formatting() return; err: <nil>; res:
[]protocol.TextEdit{
    {
        Range: protocol.Range{
            Start: protocol.Position{Line:5, Character:0},
            End:   protocol.Position{Line:10, Character:0},
        },
        NewText: "",
    },
}
```

i.e. the start position is wrong. It should be: `protocol.Position{Line:4, Character:1}` 

---

cc @stamblerre @ianthehat

**Comment by stamblerre** [comment] 2019-11-01 18:42
@ianthehat: Do we always add a terminal newline to files? I thought that `gofmt` always did this but it seems it doesn't.

**Comment by ianthehat** [comment] 2019-11-01 19:48
gofmt would add the terminal newline
is this with go-diff or not?
the return looks correct to me, it is removing all the trailing lines, starting with the beginning of the first unwanted line and going to beyond the end of the file.

**Comment by myitcv** [comment] 2019-11-01 20:00
Thanks very much.

This is with `go-diff` (recently enabled by default).

Hmm it does look like something is wrong with either my understanding/`govim` here. Let me dig further (apologies @stamblerre, I was wrong on Slack too!)

**Comment by stamblerre** [comment] 2019-11-01 20:53
Closing as working as intended.

**Closed by stamblerre** 2019-11-01 20:53 UTC
Labels: NeedsInvestigation, Tools, gopls
