### ISSUE TITLE
"go mod tidy" does not work with UNIX soft links

### ISSUE THREAD

**Issue by JetSetIlly** [golang/go#58911] opened 2023-03-07 08:32 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.20.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
</pre></details>

### What did you do?

Running `go mod tidy` in a directory that is a soft-link does not work. Running `go mod tidy` from the real location does work. The only difference is the soft-link.

For example: If I have a project in `/home/me/source/myproject` and a softlink to that project:

<pre>
ln -s source/myproject mylink
</pre>

### What did you expect to see?

The results of `go mod tidy` as it finds the modules for the project

For example:

<pre>
go: finding module for package github.com/veandco/go-sdl2/sdl
go: finding module for package github.com/pkg/term/termios
go: finding module for package golang.org/x/image/draw
go: finding module for package golang.org/x/sys/unix
</pre>

### What did you see instead?

<pre>go: warning: "all" matched no packages</pre>

**Comment by seankhliao** [comment] 2023-03-07 08:39
Duplicate of #45609

**Closed by seankhliao** 2023-03-07 08:39 UTC
