### ISSUE TITLE
cmd/gc: assigned but not used checking is not strict enough

### ISSUE THREAD

**Issue by davecheney** [golang/go#11031] opened 2015-06-02 05:49 UTC
The following program, http://play.golang.org/p/92JZyQQ-Gr, fails because an `err` value is shadowed.

This error cropped up a few times in the standard library (and more times in user code). 

@robpike thinks the compiler should catch this.

Discussion: https://groups.google.com/forum/#!topic/golang-nuts/MdDLbvOjb4o

**Comment by griesemer** [comment] 2015-06-02 06:55
See also related issue #10989.

**Comment by griesemer** [comment] 2015-06-02 06:58
Note that the spec doesn't require the compiler to do any flow analysis for the "defined but not used" error of function-local variables. See #10989 for a discussion.

**Comment by robpike** [comment] 2015-06-02 14:00
Duplicate of #10989.

**Closed by robpike** 2015-06-02 14:00 UTC
