### ISSUE TITLE
proposal: gofmt: (QoL) filtering certain code patterns

### ISSUE THREAD

**Issue by RamennBowls** [golang/go#56859] opened 2022-11-20 14:08 UTC
Hi! I wanted to re-spark a feature that was requested 2+ years ago for gofmt. Issue #40028.

In response to what @ianlancetaylor mentioned in that issue, while I do agree 'eliminating bike shed' should be prioritized over personal formatting choices, there's been times where gofmt has left me and my team a little fustrated.

For instance our API _currently_ uses [Gin](https://github.com/gin-gonic/gin) (gin-gonic), and one of the ways we would like to attach subroutes is like so ...
```go
route = router.Group("/auth", captcha.Middleware()); {
    auth.RegisterRoutes(route.Group("/register"))
}
```
In this scenario, gofmt removes semicolons infavor of a new line. While this isn't inherently bad, that codeblock ends up looking like so ...
```go
route = router.Group("/auth", captcha.Middleware())
{
    auth.RegisterRoutes(route.Group("/register"))
}
```
Big whoop- it's just a new line what's the problem? Once you've got dozons of these it can really start to get a tad fustrating. If gofmt won't have a config, then I think **we could atleast benefit the option of ignoring certain code patterns (maybe using Regex).**

Lemme know your thoughts?

**Comment by seankhliao** [comment] 2022-11-20 14:21
Sorry, our decision stands.

Duplicate of #40028

**Closed by seankhliao** 2022-11-20 14:21 UTC
Labels: Proposal
