### ISSUE TITLE
not able to properly check "Invalid argument" errors from os.ReadFile

### ISSUE THREAD

**Issue by ghouscht** [golang/go#46849] opened 2021-06-21 12:55 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/tmp/go"
GOENV="/export/home/gostelit/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/work/go/pkg/mod"
GONOPROXY="*.pnet.ch"
GONOSUMDB="*.pnet.ch"
GOOS="linux"
GOPATH="/work/go"
GOPRIVATE="*.pnet.ch"
GOPROXY="https://proxy.golang.org"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3065707803=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
1. Create a brige interface called *test* with `sudo brctl addbr test`
2. Test if you can read the speed of this test bridge (should faild with `Invalid argument`:
```shell
cat /sys/class/net/test/speed
cat: /sys/class/net/test/speed: Invalid argument
```
3. Execute the following go program and notice that it outputs `this is a syscall.EINVAL error` and nothing more.

#### main.go
```golang
package main

import (
        "errors"
        "fmt"
        "io/fs"
        "os"
        "syscall"
)

func main() {
        _, err := os.ReadFile("/sys/class/net/test/speed")
        if err != nil {
                if errors.Is(err, os.ErrInvalid) {
                        fmt.Println("this is an os.ErrInvalid error")
                }

                if errors.Is(err, fs.ErrInvalid) {
                        fmt.Println("this is an fs.ErrInvalid error")
                }

                if errors.Is(err, syscall.EINVAL) {
                        fmt.Println("this is a syscall.EINVAL error")
                }
        }
}
```

### What did you expect to see?
According to the [syscall Errno docs](https://golang.org/pkg/syscall/#Errno):

>  Errno values can be tested against error values from the os package using errors.Is. For example:
```golang
_, _, err := syscall.Syscall(...)
if errors.Is(err, fs.ErrNotExist) ...
```

I did expect that this example program also prints the two other lines. Also the documentation is a bit misleading since it says "you can test against error values from the os package..." but uses the fs package in the example.

Furthermore https://golang.org/pkg/io/fs/#pkg-variables states:
> Generic file system errors. Errors returned by file systems can be tested against these errors using errors.Is. 

and thus I'd expect to be able to check this error also with `errors.Is(err,fs.ErrInvalid)`.

### What did you see instead?
The program does not print the following two lines:
- this is an os.ErrInvalid error
- this is an fs.ErrInvalid error

it only prints:
- this is a syscall.EINVAL error

Maybe this is just a misunderstanding from my side since I'm not a native English speaker. If so I think we should clarify this in the docs.

EDIT:
Related: https://github.com/golang/go/issues/37627 refers to https://github.com/golang/go/issues/30322 which had no progress for some time and is hard for me to relate to this issue.

**Comment by seankhliao** [comment] 2021-06-23 21:51
Duplicate of #30322

**Closed by seankhliao** 2021-06-23 21:51 UTC
