### ISSUE TITLE
cmd/compile: "internal compiler error: large ONEW with EscNone: new()"

### ISSUE THREAD

**Issue by AndrewWPhillips** [golang/go#39292] opened 2020-05-28 06:55 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 windows/amd64
</pre>

Also reproduced with:
go version devel +af2b592260 Wed Apr 22 14:12:34 2020 -0700 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Andrewp\AppData\Local\go-build
set GOENV=C:\Users\Andrewp\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\Go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=L:\TEMP\go-build975958338=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

Compiled this:

```
package main

type t struct {
	b [10000]int
}

func (t) f() {
}

func main() {
	x := t{}.f
	x()
}
```

### What did you expect to see?

$ go build

$

### What did you see instead?

$ go build
_/D_/Andrew/GoProjects/gocompilerbug
.\main.go:11:10: internal compiler error: large ONEW with EscNone: new()

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new

$

**Comment by ALTree** [comment] 2020-05-28 08:20
cc @mdempsky @dr2chase

**Comment by mdempsky** [comment] 2020-05-28 15:01
Interesting. Thanks for the report.

**Comment by ALTree** [comment] 2020-05-28 15:15
Fails since go1.5 (go1.4 is fine). Previously a variant with a slightly different reproducer was reported in #15733 and fixed in go1.8.

**Comment by cuonglm** [comment] 2020-05-28 17:08
It seems that because `t{}.f` does not escape, the struct generated to hold closure information is marked as does not escape, too.

When we initialized this struct fields in `anylit`,  we generated a `ONEW` node with `n.Esc` inherits from the closure, which is `EscNone`.

A potential fix can be:

```
diff --git a/src/cmd/compile/internal/gc/sinit.go b/src/cmd/compile/internal/gc/sinit.go
index f5d588e63b..e008829001 100644
--- a/src/cmd/compile/internal/gc/sinit.go
+++ b/src/cmd/compile/internal/gc/sinit.go
@@ -875,6 +875,9 @@ func anylit(n *Node, var_ *Node, init *Nodes) {
                        r.SetTypecheck(1)
                        r.Type = t
                        r.Esc = n.Esc
+                       if mustHeapAlloc(n) {
+                               r.Esc = EscHeap
+                       }
                }

                r = walkexpr(r, init)
```

**Closed** 2020-08-15 03:10 UTC
Labels: NeedsInvestigation
