### ISSUE TITLE
doc: correction go_mem.html

### ISSUE THREAD

**Issue by olegdunkan** [golang/go#10168] opened 2015-03-15 12:17 UTC
http://golang.org/ref/mem#tmp_7

There is code: 
```
var limit = make(chan int, 3)

func main() {
	for _, w := range work {
		go func() {
			limit <- 1
			w()
			<-limit
		}()
	}
	select{}
}
```
I think it will be better this one:

```
var limit = make(chan int, 3)

func main() {
	for _, w := range work {
                w:= w                                    //!!! it is the correction
		go func() {
			limit <- 1
			w()
			<-limit
		}()
	}
	select{}
}
```

**Comment by minux** [comment] 2015-03-15 22:18
Dupe of #9235.

**Closed by minux** 2015-03-15 22:18 UTC
