### ISSUE TITLE
os: ReadDir("\\tsclient\d\") fails with go1.21 on Windows

### ISSUE THREAD

**Issue by ThisIsN3w** [golang/go#62044] opened 2023-08-15 13:34 UTC
In 1.20, it can work.
but in 1.21,fail.

### What version of Go are you using (`go version`)?

<pre>
C:\Users\Administrator\Desktop>go version
go version go1.21.0 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.0
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\Administrator\Desktop\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build2292448789=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
```golang
package main

import (
	"log"
	"os"
)

func main() {
	dirs, err := os.ReadDir("\\\\tsclient\\d\\")
	if err != nil {
		log.Fatalln(err)
	}
	for _, dirName := range dirs {
		log.Println(dirName.Name())
	}
}

```

### What did you expect to see?

<pre>
C:\Users\Administrator\Desktop>test-1.20.exe
2023/08/15 20:37:14 $RECYCLE.BIN
2023/08/15 20:37:14 Backup
2023/08/15 20:37:14 BCompare
</pre>

### What did you see instead?
<pre>
C:\Users\Administrator\Desktop>test-1.21.exe
2023/08/15 21:34:21 GetFileInformationByHandleEx \\tsclient\d\: The parameter is incorrect.
</pre>

**Comment by bcmills** [comment] 2023-08-15 14:20
Duplicate of #61907

**Closed by bcmills** 2023-08-15 14:20 UTC
Labels: OS-Windows
