### ISSUE TITLE
Nil pointer to struct implementing error interface is nil, but error(x) == nil returns false

### ISSUE THREAD

**Issue by wallnutkraken** [golang/go#24947] opened 2018-04-19 12:02 UTC
### What version of Go are you using (`go version`)?
go version go1.9.4 linux/amd64

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gnugat/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build810068483=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?
https://play.golang.org/p/x5Ix8wmC0Oj

### What did you expect to see?
```
errImpl is nil
error(errImpl) is nil
```

### What did you see instead?
```
errImpl is nil
ErrImpl value: <nil>
```

**Comment by go101** [comment] 2018-04-19 12:08
This is not a bug. Please read https://go101.org/article/unofficial-faq.html#nil-equality for explanations.

**Comment by ALTree** [comment] 2018-04-19 12:39
Also [Why is my nil error value not equal to nil?](https://golang.org/doc/faq#nil_error)

Closing this, since it's not a bug.

**Closed by ALTree** 2018-04-19 12:39 UTC
