### ISSUE TITLE
log/slog: "[HandlerOptions.Level]" doc syntax not rendered correctly on pkgsite

### ISSUE THREAD

**Issue by willfaught** [golang/go#64485] opened 2023-11-30 22:48 UTC
### Go version

n/a

### What operating system and processor architecture are you using (`go env`)?

```shell
n/a
```

### What did you do?

went to https://pkg.go.dev/log/slog

### What did you expect to see?

hyperlink to HandlerOptions.Level section

### What did you see instead?

>The built-in handlers can be configured with the minimum level to output by setting [HandlerOptions.Level]. The [...]

<img width="995" alt="Screenshot 2023-11-30 at 2 47 08 PM" src="https://github.com/golang/go/assets/63830/6196af91-cc9d-4aec-84b2-f52b3b431fb2">

**Comment by seankhliao** [comment] 2023-11-30 23:04
Duplicate of #61394

**Closed by seankhliao** 2023-11-30 23:04 UTC
