### ISSUE TITLE
runtime: apparent deadlock in TestSignalM

### ISSUE THREAD

**Issue by bcmills** [golang/go#35276] opened 2019-10-31 15:14 UTC
From `darwin-386-10_14` (https://build.golang.org/log/b5777ae134f6711c97b26f42b83697bc014a335b):

```
panic: test timed out after 5m0s

[…]

goroutine 63722 [syscall, 4 minutes, locked to thread]:
runtime.notetsleepg(0x383998, 0x3b9aca00, 0x0, 0x489008)
	/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/runtime/lock_sema.go:286 +0x2e fp=0x11c0e798 sp=0x11c0e774 pc=0xad1e
runtime.WaitForSigusr1(0x11c0e7d4, 0x3b9aca00, 0x0, 0x11c0e7e0, 0x1c8001, 0x34dc8, 0x200534)
	/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/runtime/export_unix_test.go:47 +0x9d fp=0x11c0e7b8 sp=0x11c0e798 pc=0x56ddd
runtime_test.TestSignalM.func1(0x119a9680, 0x1146ca60, 0x1146ca68, 0x1146ca70)
	/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/runtime/crash_unix_test.go:321 +0x56 fp=0x11c0e7e0 sp=0x11c0e7b8 pc=0x17b3b6
runtime.goexit()
	/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/runtime/asm_386.s:1337 +0x1 fp=0x11c0e7e4 sp=0x11c0e7e0 pc=0x5c631
created by runtime_test.TestSignalM
	/var/folders/9w/4l2_g3kx01x199n37fbmv3s80000gn/T/workdir-host-darwin-10_14/go/src/runtime/crash_unix_test.go:319 +0xbd
```

CC @cherrymui @mknyszek

**Comment by bcmills** [comment] 2019-10-31 15:19
More instances:
* https://build.golang.org/log/3c6307d6502174ca376935f9235447170702a574
* https://build.golang.org/log/f454030f281d27c38d6c1e90e661e3c818ed4347
* https://build.golang.org/log/b234876e43252e8f47605b1c36b7d95f6b62fc93

**Comment by bcmills** [comment] 2019-10-31 16:57
`aix-ppc64`: https://build.golang.org/log/c08fa0c84940718bbce2c78324789e781e9a72bb

**Comment by aclements** [comment] 2019-11-07 10:56
This has happened a few times since "runtime: remove write barrier in WaitForSigusr1" landed, so that CL clearly didn't fix it (it was only a guess that it might).

**Comment by ianlancetaylor** [comment] 2019-11-08 02:43
[2019-10-29T14:22:15-a0c1e8d/darwin-386-10_14](https://build.golang.org/log/b234876e43252e8f47605b1c36b7d95f6b62fc93)
[2019-10-29T14:22:15-a0c1e8d/darwin-amd64-10_12](https://build.golang.org/log/f454030f281d27c38d6c1e90e661e3c818ed4347)
[2019-10-29T22:56:47-15ea61c/darwin-amd64-10_12](https://build.golang.org/log/3c6307d6502174ca376935f9235447170702a574)
[2019-10-30T14:51:03-cc4b824/darwin-386-10_14](https://build.golang.org/log/b5777ae134f6711c97b26f42b83697bc014a335b)
[2019-10-30T20:46:44-81a74b4/aix-ppc64](https://build.golang.org/log/c08fa0c84940718bbce2c78324789e781e9a72bb)
[2019-10-30T20:46:44-81a74b4/dragonfly-amd64](https://build.golang.org/log/a72dcb5b352890a57f928e25a32b2c6afc8426e4)
[2019-10-31T17:21:56-48c0cef/darwin-amd64-nocgo](https://build.golang.org/log/56a77d030c48673847a4c6440bea95983e659c05)
[2019-11-01T07:59:09-5b31021/dragonfly-amd64](https://build.golang.org/log/590275d81bd7656698c7dcb9a988380a529c8e90)
[2019-11-01T14:19:56-8405cd3/darwin-amd64-nocgo](https://build.golang.org/log/6403710047c37ec54176d8da64f184fb77baa2fa)
[2019-11-01T21:41:41-9bde9b4/darwin-386-10_14](https://build.golang.org/log/959491fea056cd3606f1b896dc818112b5958f1f)
[2019-11-02T03:00:20-1e4a358/darwin-arm64-corellium](https://build.golang.org/log/d9f5f8b7d8c5b9785ca6a9f7420c1f61d2ca7167)
[2019-11-02T05:36:43-971ec87/darwin-amd64-10_12](https://build.golang.org/log/9f952eec65fe4c0de31bdb1f19470aec4f637903)
[2019-11-02T15:46:47-dc0c23e/aix-ppc64](https://build.golang.org/log/5ab04bc5f3af71d0020b7699175baedd90f0bcb3)
[2019-11-02T21:51:09-61fa798/dragonfly-amd64](https://build.golang.org/log/270c938cb32d45774cc8b7b1c1d0465708dbfaee)
[2019-11-02T21:51:21-177a36a/darwin-amd64-10_14](https://build.golang.org/log/05b0876d23491096a93933d086c2249b2a74a139)
[2019-11-03T04:58:01-32190b0/darwin-amd64-10_14](https://build.golang.org/log/eeeab5ccd6530fe20db11bb515dbb1de413f8c3b)
[2019-11-03T05:01:00-4497d7e/darwin-amd64-10_12](https://build.golang.org/log/085f522dbb46a856dd8dd529933fcf9c374ed5de)
[2019-11-04T01:28:26-6b67f7d/darwin-amd64-10_14](https://build.golang.org/log/0dde57c38728be74c1f10b71c2095fd723b8b935)
[2019-11-04T21:30:29-5a7c571/darwin-386-10_14](https://build.golang.org/log/83dfa544e96092fc507ddf8001a04eabed1688b0)
[2019-11-04T23:16:09-2566e21/dragonfly-amd64](https://build.golang.org/log/6fb58e3ffe2df9ca570feaca00cddbda0c4cf30f)
[2019-11-05T02:54:42-0f992b9/darwin-386-10_14](https://build.golang.org/log/ec2f1b49748f920a38c6cce5d99d89422f411f6e)
[2019-11-05T16:31:48-414c1d4/dragonfly-amd64](https://build.golang.org/log/7589f2307b2b9f2134ff47cc777d7d6d732dc02e)
[2019-11-05T19:06:28-7e71c9c/aix-ppc64](https://build.golang.org/log/c25fdacd2c9c3817a352245ba3b316e673a5de2c)
[2019-11-05T19:06:28-7e71c9c/darwin-386-10_14](https://build.golang.org/log/0ed3353d7874af857ead056d62b12089ac4820e8)
[2019-11-05T19:06:28-7e71c9c/dragonfly-amd64](https://build.golang.org/log/25b360eae4aff1e481bd88756f5181807bddc7a1)
[2019-11-06T09:09:21-0ea7440/dragonfly-amd64](https://build.golang.org/log/5aedf19c06c00815b448e5816b5e861436550158)
[2019-11-06T09:09:59-0c5d545/dragonfly-amd64](https://build.golang.org/log/af3d419ed930e49e6e7c05df18763befd1c02999)
[2019-11-06T23:48:45-6ce4384/darwin-386-10_14](https://build.golang.org/log/f90bf20912804a6c5e69aa873e9da85c3e6b2a74)
[2019-11-07T06:58:44-f5949b6/darwin-amd64-nocgo](https://build.golang.org/log/9fcb98b1cf44bb856da42294756bb67b9216e009)
[2019-11-07T08:25:32-7a2baa9/darwin-amd64-10_14](https://build.golang.org/log/33f224ff2ef9b16b528568a09d680ff017aa73c8)
[2019-11-07T16:35:53-b3a3613/darwin-386-10_14](https://build.golang.org/log/e47e61367b0c1921db78a80fa3d540fbe2dbd280)
[2019-11-07T19:14:27-7331708/darwin-amd64-10_14](https://build.golang.org/log/96883d12b65214dbf102a397cc5cacae07cb263c)
[2019-11-07T19:18:59-a96cfa7/darwin-amd64-nocgo](https://build.golang.org/log/0be961e294b08bd59ffca33b9e32053444373fff)
[2019-11-07T21:59:16-4cde749/darwin-amd64-nocgo](https://build.golang.org/log/e8f4218aa12b4d31e5a1fa4450e1858891008107)
[2019-11-07T22:17:54-52d5e76/darwin-386-10_14](https://build.golang.org/log/390cc7727c4fa3f0913be4d4a7f60c9b77d9240d)
[2019-11-07T22:17:54-52d5e76/darwin-amd64-10_12](https://build.golang.org/log/7ddc0a62f62d3d38ef49f0f7a26a44ed02ab6e99)

**Comment by ianlancetaylor** [comment] 2019-11-08 02:46
The failures are only on Darwin, Dragonfly, and AIX.

**Comment by ianlancetaylor** [comment] 2019-11-08 03:29
OK, I think I see what the problem is, at least on Darwin.  We are calling `notewakeup` from a signal handler.  But on Darwin the note functions are not async-signal-safe.  We already had to work around this once before, for #31264.

**Closed** 2019-11-12 05:36 UTC
Labels: NeedsInvestigation, release-blocker
