### ISSUE TITLE
cmd/go: error installing gopls and multiple x/tools packages on arm

### ISSUE THREAD

**Issue by NerdsvilleCEO** [golang/go#35137] opened 2019-10-24 16:34 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.3 linux/arm
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build596311221=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
*Passing command*:
```
    GO111MODULE=on go get -buildmode=exe -ldflags '-s -w'   \
      golang.org/x/tools/gopls@latest
```

*Failing command*:
```
    GO111MODULE=on go get -buildmode=exe -ldflags '-s -w'   \
      golang.org/x/tools/gopls@latest                       \
      golang.org/x/tools/cmd/benchcmp # OR add any other x/tools package
```

### What did you expect to see?
Success for gopls even if other `x/tools` packages brought in

### What did you see instead?
```
pkg/mod/golang.org/x/tools/gopls@v0.1.7/main.go:20:41: not enough arguments in call to cmd.New
	have (string, string, nil)
	want (string, string, []string, func(*source.Options))
```

**Comment by stamblerre** [comment] 2019-10-24 16:39
Are you running this command inside of a module? Make sure to switch to a temporary directory before running the command.

**Comment by NerdsvilleCEO** [comment] 2019-10-24 16:43
Yes, I am running from a temp dir, it is an empty docker container based on `arm32v7/golang:latest`

**Comment by stamblerre** [comment] 2019-10-24 16:48
Could you try running with `-v` to get a bit more information? You could also try clearing the module cache and running the command again.

**Comment by NerdsvilleCEO** [comment] 2019-10-24 16:49
`-v` gives no additional information, I think the error is pretty clear, just haven't dug much more into it... I can look into this more if need be. I figure also, since I am making a new docker container, that shouldn't have any module cache

Thanks!

**Comment by stamblerre** [comment] 2019-10-24 16:58
Oh I'm sorry I misread your initial issue - I thought both of those commands were failing. 

I think I would expect this to fail. `gopls` is a sub-module of `x/tools`, and therefore `latest` depends on a specific version of `x/tools`. `golang.org/x/tools/cmd/benchcmp` is downloaded at `master`, however, causing the conflict.

I might be mistaken though -- @jayconrod: should this work?

**Comment by NerdsvilleCEO** [comment] 2019-10-24 16:59
@stamblerre that makes sense... one question I have is why would this work on amd64 and not arm?

**Comment by stamblerre** [comment] 2019-10-24 17:05
I was unable to get it to work on amd64, but I'm definitely not knowledgeable enough here to have useful insight. Probably best to wait for advice from the `go` command folks.

**Comment by NerdsvilleCEO** [comment] 2019-10-24 17:12
Oh, I know what the issue is, I had an old build for the `amd64` one that was cached... there have since been api changes, I think your original hunch was right, going to try that :)

**Comment by NerdsvilleCEO** [comment] 2019-10-24 17:25
Same issue with:
```
GO111MODULE=on go get -buildmode=exe -ldflags '-s -w'      \
>       golang.org/x/lint/golint                                 \
>       golang.org/x/tools@latest                                \
>       golang.org/x/tools/gopls@latest                          \
```

**Comment by jayconrod** [comment] 2019-10-24 17:53
Working as intended from the go command perspective: this command may not work in general. It's probably best to run one `go get` command per module.

This command requests the latest version of golang.org/x/tools/gopls (v0.1.7 as of now) built against the latest version of `golang.org/x/tools` (v0.0.0-20191024172055-b24f3822ec91), which is a separate module. gopls v0.1.7 depends on an internal package in x/tools, `golang.org/x/tools/internal/lsp/cmd`. There have been incompatible changes in the API of that internal package, so gopls v0.1.7 doesn't build. Presumably gopls at master works with those changes, but `v0.1.7` does not.

Another way to reproduce:

```
mkdir test
cd test
go mod init m
go get -d golang.org/x/tools/gopls
go get -d golang.org/x/tools
go build golang.org/x/tools/gopls
```

**Comment by stamblerre** [comment] 2019-11-01 18:31
Since it looks like this is intended behavior, I will close the issue.

**Closed by stamblerre** 2019-11-01 18:31 UTC
Labels: Tools, gopls
