### ISSUE TITLE
x/tools/internal/lsp: AutoCompletion Does Not Work Inside Goroutines 

### ISSUE THREAD

**Issue by marwan-at-work** [golang/go#30805] opened 2019-03-13 13:56 UTC
### Info
- Go version: 1.12 darwin
- Editor: VSCode
- gopls version: e65039

### reproduce

```bash
- mkdir temp
- cd temp
- go mod init temp
- touch main.go
```

inside main.go open VSCode and type the following main.go file

```golang
package main

import (
  "net/http"
)

func main() {
  go func() {
    http.
  }()
}
```

Note that because `http.` was typed inside the anonymous goroutine, nothing gets auto-completed. However, if you type `http.` outside of that goroutine, then things work well.

**Comment by anjmao** [comment] 2019-03-14 08:24
Note that it also doesn't work for anonymous func.

```go
func main() {
  fn := func() {
    http.<>
  }()
}
```

 It looks like a bug of astutil.PathEnclosingInterval method since for this case it returns *ast.BlockStmt with wrong inner nodes.

Example:
```go
package source

import (
  "net/http"
  "fmt"
)

func fn1() {
	go func() {
		http.<>
	}()
}

func fn2() {
	if 1 == 2 {
		fmt.Println("great")
	}
}
```

AST
```
[]ast.Node (len = 3) {
     1  .  0: *ast.BlockStmt {
     2  .  .  Lbrace: /go/src/golang.org/x/tools/internal/lsp/source/t.go:8:12
     3  .  .  List: []ast.Stmt (len = 3) {
     4  .  .  .  0: *ast.BadStmt {
     5  .  .  .  .  From: /go/src/golang.org/x/tools/internal/lsp/source/t.go:9:2
     6  .  .  .  .  To: /go/src/golang.org/x/tools/internal/lsp/source/t.go:9:4
     7  .  .  .  }
     8  .  .  .  1: *ast.ExprStmt {
     9  .  .  .  .  X: *ast.BadExpr {
    10  .  .  .  .  .  From: /go/src/golang.org/x/tools/internal/lsp/source/t.go:14:1
    11  .  .  .  .  .  To: /go/src/golang.org/x/tools/internal/lsp/source/t.go:14:13
    12  .  .  .  .  }
    13  .  .  .  }
    14  .  .  .  2: *ast.IfStmt {
    15  .  .  .  .  If: /go/src/golang.org/x/tools/internal/lsp/source/t.go:15:2
    16  .  .  .  .  Init: nil
    17  .  .  .  .  Cond: *ast.BinaryExpr {
    18  .  .  .  .  .  X: *ast.BasicLit {
    19  .  .  .  .  .  .  ValuePos: /go/src/golang.org/x/tools/internal/lsp/source/t.go:15:5
    20  .  .  .  .  .  .  Kind: INT
    21  .  .  .  .  .  .  Value: "1"
    22  .  .  .  .  .  }
    23  .  .  .  .  .  OpPos: /go/src/golang.org/x/tools/internal/lsp/source/t.go:15:7
    24  .  .  .  .  .  Op: ==
    25  .  .  .  .  .  Y: *ast.BasicLit {
    26  .  .  .  .  .  .  ValuePos: /go/src/golang.org/x/tools/internal/lsp/source/t.go:15:10
    27  .  .  .  .  .  .  Kind: INT
    28  .  .  .  .  .  .  Value: "2"
    29  .  .  .  .  .  }
    30  .  .  .  .  }
    31  .  .  .  .  Body: *ast.BlockStmt {
    32  .  .  .  .  .  Lbrace: /go/src/golang.org/x/tools/internal/lsp/source/t.go:15:12
```

**Comment by zmb3** [comment] 2019-03-15 00:26
Duplicate of #29313?

**Comment by bcmills** [comment] 2019-04-12 20:36
@stamblerre, is this a duplicate?

**Comment by stamblerre** [comment] 2019-05-15 17:42
I believe so. Closing in favor of that issue.

**Closed by stamblerre** 2019-05-15 17:42 UTC
Labels: NeedsInvestigation, gopls
