### ISSUE TITLE
runtime/trace: trace.Stop hangs indefinitely when built with faketime

### ISSUE THREAD

**Issue by Nasfame** [golang/go#60806] opened 2023-06-15 04:06 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.20.5
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

 Reproducer - https://go.dev/play/p/bFIsMzx0Vql 

### What did you expect to see?

I expected to see the contents of  binary-encoded trace file that contains the recorded execution trace data of your Go program.

```bash
go version go1.20.3
this function will be traced
go 1.20 traceA�������_�_�       _��Ef%
Not worker%GC (dedicated)%GC (fractional)%      GC (idle)�Q��   \�
Q�
  A����E
A�Ʉ�־�%runtime/trace.Start%(/usr/local/go/src/runtime/trace/trace.go%   main.main/workspaces/test/tmp/y.goÑ��������     �����%  runtime.traceGoSched%
"/usr/local/go/src/runtime/trace.go%
                                    runtime.StopTrace%
                                                      runtime/trace.Stopá��������
                                                                                 ֍�
�
 ���

��ţ
syscall.Write%)/usr/local/go/src/syscall/syscall_unix.go%internal/poll.ignoringEINTRIO%*/usr/local/go/src/internal/poll/fd_unix.go%internal/poll.(*FD).Write%os.(*File).write%"/usr/local/go/src/os/file_posix.go%os.(*File).Write%/usr/local/go/src/os/file.go%
                                                                                   fmt.Fprintln%sr/local/go/src/fmt/print.go%
                                                                                                                             fmt.Println%main.RunMyProgram�π�������

�ʞ�习�ֹ�������Ġ0�Ġ�԰��ɣ�"�É���������%runtime.runfinq%#/usr/local/go/src/runtime/mfinal.goÊ������������% runtime.startTheWorld%!runtime.startTheWorldGC%"runtime.StartTraceè��������ǿ� �       �!�     ���"
����}�%#
        runtime.mainÊ����������#�%$runtime.bgsweep%%%/usr/local/go/src/runtime/mgcsweep.goÊ�����������$%�%&runtime.bgscavenge%'(/usr/local/go/src/runtime/mgcscavenge.goÊ�����������&'�%(runtime/trace.Start.func1Ê��������£(�


```

### What did you see instead?

```bash
timeout running program
go version go1.20.5
this function will be traced
```

**Comment by rhysh** [comment] 2023-06-15 18:21
This looks to me like "runtime/trace package doesn't work on the Go Playground". Changing the output buffer doesn't improve things; with `trace.Start(io.Discard)`, the call to `trace.Stop` still hangs when run on the playground.

@mknyszek , is the `runtime/trace` package supposed to work on that platform? If not, maybe the body of `trace.Stop` on the playground could be replaced with a descriptive panic.

When I run the program locally and trim off the two text lines that the program writes, I get working output.

```
$ go1.20 version           
go version go1.20.5 darwin/arm64

$ go1.20 tool trace -d <(go1.20 run /tmp/bFIsMzx0Vql.go | sed 1,2d) 
2023/06/15 11:16:12 Parsing trace...
0 GoCreate p=1 g=0 off=54 g=1 stack=2
2752 GoCreate p=1 g=0 off=60 g=2 stack=3
2912 GoWaiting p=1 g=2 off=67 g=2
5584 GoCreate p=1 g=0 off=70 g=17 stack=4
5712 GoWaiting p=1 g=17 off=77 g=17
6032 GoCreate p=1 g=0 off=80 g=18 stack=5
6160 GoWaiting p=1 g=18 off=86 g=18
6448 GoCreate p=1 g=0 off=89 g=19 stack=6
6576 GoWaiting p=1 g=19 off=95 g=19
6672 ProcStart p=1 g=0 off=98 thread=0
6784 GoStart p=1 g=1 off=101 g=1 seq=0
8576 Gomaxprocs p=1 g=1 off=164 procs=8
19376 HeapAlloc p=1 g=1 off=168 mem=1695744
44672 GoCreate p=1 g=1 off=174 g=20 stack=8
47712 GoSysCall p=1 g=1 off=181
80336 ProcStart p=0 g=0 off=25 thread=2
98576 GoStart p=0 g=20 off=28 g=20 seq=1
175824 ProcStart p=2 g=0 off=199 thread=3
177616 ProcStop p=2 g=0 off=202
274240 HeapAlloc p=0 g=20 off=33 mem=1703936
275456 GoPreempt p=0 g=20 off=39
298336 ProcStop p=0 g=0 off=42
312544 GoSched p=1 g=1 off=185
```

A minimal reproducer: https://go.dev/play/p/Xd1HEre71Pj

```
package main

import (
	"io"
	"runtime/trace"
)

func main() {
	trace.Start(io.Discard)
	trace.Stop()
}
```

**Comment by mknyszek** [comment] 2023-06-15 19:07
I think it is just broken on the playground, probably because it's a faketime platform. I'm exactly not sure why it hangs, I would need to investigate that, but I would also expect any resulting trace to be broken. `trace.Start` probably just be a descriptive panic as you suggest when built with faketime.

**Comment by mknyszek** [comment] 2023-06-15 19:08
@Nasfame are you able to reproduce this locally, or just on the playground?

**Comment by Nasfame** [comment] 2023-06-15 19:43
It's working locally. But not in playground.

**Comment by Nasfame** [comment] 2023-06-15 20:42
@mknyszek 

> @Nasfame are you able to reproduce this locally, or just on the playground?

only on playground

**Comment by Nasfame** [comment] 2023-06-15 22:23
Found the issue - 

<img width="353" alt="image" src="https://github.com/golang/go/assets/24226219/9031acf9-652b-4609-ac45-9e56e311cb59">

the for loop will execute forever for build - faketime

<img width="683" alt="image" src="https://github.com/golang/go/assets/24226219/c7c8e6ca-f93d-4f58-8491-67010116da59">

**Comment by Nasfame** [comment] 2023-06-15 22:27
Here is the minimalistic reproducer

```bare2.go```
package main

import (
	"fmt"
	"log"
	"runtime"
)

func main() {
	if err := runtime.StartTrace(); err != nil {
		log.Fatal("failed to start trace")
	}

	fmt.Println("this will be traced")
	runtime.StopTrace()
	fmt.Println("doesn't panic")
}
```

```shell```
go build --tags faketime  bare2.go
./bare2
```

**Comment by mknyszek** [comment] 2023-06-16 00:23
@Nasfame Pff, yep. Thanks for looking into it. The classic "assume time progresses" issue when building with faketime. There were a couple other places that had the issue in the past.

At minimum, I think it's probably fine to let the trace function work don't loop if we built with faketime, like https://cs.opensource.google/go/go/+/master:src/runtime/mgcscavenge.go;l=630?q=mgcscavenge.go&ss=go%2Fgo and just let the trace be potentially broken.

**Comment by Nasfame** [comment] 2023-06-16 01:29
@mknyszek 

I think there is potential fix : 
```go
if trace.timeEnd>=trace.timeStart{}
```
If we can't do that due to performance or other issues - we can have build tags restricting !go:builds for `runtime/trace`.

Else: at least update documentations. for  `Stop()`

**Comment by mknyszek** [comment] 2023-06-30 16:42
This is now fixed. I'm not certain whether it's worth backporting; this has been broken for a very long time and there's a clear workaround (run the program outside of the playground; there's virtually no other use-case for faketime), so unfortunately it doesn't meet the criteria. At least future releases won't have this issue.

**Closed by mknyszek** 2023-06-30 16:42 UTC
Labels: NeedsInvestigation, compiler/runtime
