### ISSUE TITLE
Compiler doesn't dettect declaration in if,else statement

### ISSUE THREAD

**Issue by oktorok** [golang/go#31115] opened 2019-03-28 17:07 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> amd64 Xubuntu</summary><br><pre>
$ go env

</pre></details>

### What did you do?

https://play.golang.org/p/2hcuytluD-u

### What did you expect to see?
No errors when compiled

### What did you see instead?

undefined: b

**Comment by ALTree** [comment] 2019-03-28 17:28
This is working as intended. The variable `b` was declared inside the `if` and `else` block scopes, so it's not visible outside those blocks.

If you have other questions regarding scoping, please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2019-03-28 17:28 UTC
