### ISSUE TITLE
Loss of reference in for

### ISSUE THREAD

**Issue by flrossetto** [golang/go#32872] opened 2019-07-01 16:56 UTC
Running the following code

```go
package main

import (
	"fmt"
)

type A struct {
	Value string
}

func main() {
	var list = []A{
		A{Value: "A"},
		A{Value: "B"},
		A{Value: "C"},
		A{Value: "D"},
		A{Value: "E"},
	}
	var listString []*string
	for _, item := range list {
		listString = append(listString, &item.Value)
	}
	for i, item := range listString {
		fmt.Printf("%d: %s\n", i, *item)
	}
}
```
https://play.golang.org/p/r9sClnas97T

I'm having the following return
0: E
1: E
2: E
3: E
4: E

Is that correct?

**Comment by bcmills** [comment] 2019-07-01 16:59
Yes, unfortunately it's correct.

**Comment by bcmills** [comment] 2019-07-01 17:00
Duplicate of #16520

**Closed by bcmills** 2019-07-01 17:00 UTC

**Comment by av86743** [comment] 2019-07-01 17:29
This should work, if I am not mistaken:

```
 	var listString []*string
 	for k := range list {
 		listString = append(listString, &list[k].Value)
 	}
```

**Comment by av86743** [comment] 2019-07-01 19:23
Indeed, it is a little strange that `item` is not implemented simply as a binding of variable to `list[k]`, using  an equivalent of C++ reference.  I hit this wall when I tried to update `item`, expecting that this will actually affect corresponding `list[k]`.
