### ISSUE TITLE
x/tools/gopls: 30s delay before completion menu popups

### ISSUE THREAD

**Issue by netjune** [golang/go#38425] opened 2020-04-13 23:28 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, with 0.3.4 and 0.4.0.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jun/Library/Caches/go-build"
GOENV="/Users/jun/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jun/Projects/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jun/Projects/go/src/golang.org/x/tools/gopls/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yl/0xyrgw396fj89vd1n2vk649c0000gn/T/go-build696214569=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
1. open the example package of go-qt (https://github.com/therecipe/examples/tree/master/basic/qml)
2. open main.go, and type "core." at line 18 and then wait for the completion
3. after about 30s, the completion menu popups

### What did you expect to see?
the delay is less than 1s

### What did you see instead?
the delay is about 30s

**Comment by stamblerre** [comment] 2020-04-14 03:01
Thanks for the report!  I am able to reproduce the issue. We'll try to figure out what's going on here.

**Comment by heschik** [comment] 2020-05-28 17:28
I reproduced this. Profile shows heavy usage in PathEnclosingInterval, which I think is a known problem.

**Comment by heschik** [comment] 2020-06-16 01:36
Specifically, duplicate of #37450.

**Closed by heschik** 2020-06-16 01:36 UTC
Labels: Tools, gopls
