### ISSUE TITLE
cmd/cgo: FreeLibrary a go c-shared dll make app crash

### ISSUE THREAD

**Issue by nowind** [golang/go#32497] opened 2019-06-08 15:14 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 windows/386
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\nowind\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\tools\go\user
set GOPROXY=https://goproxy.io
set GORACE=
set GOROOT=E:\tools\go386
set GOTMPDIR=
set GOTOOLDIR=E:\tools\go386\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=sse2
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\now
ind\AppData\Local\Temp\go-build636168646=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?
dll.go:

```
package main

import (
	"C"
	"fmt"
)

//export SayHi
func SayHi() {
	fmt.Println("Hi, I'm go dll")
}

func main() {
}
```

dll.c

```
int main(int argc, char* argv[])
{
	HMODULE dll= ::LoadLibrary("dll.dll");
	if(dll==NULL)
	{
		printf("err!\n");
		return -1;
	}
       getchar();
	::FreeLibrary(dll);
        getchar();
	return 0;
}
```

### What did you see instead?

after call FreeLibrary ,app crash ,but no error messagebox

**Comment by beoran** [comment] 2019-06-12 06:23
You are not calling the Go SayHi function anywhere on the C side, that is probably why you don't see anything happen. You probably need to add something like `void SayHi(void) =  (GetProcAddress(dll, "SayHi")); SayHi();` before the FreeLibrary. Also, include Windows.h at the top of your C program to get the correct prototypes.

**Comment by mattn** [comment] 2019-08-08 07:33
dup https://github.com/golang/go/issues/11100

**Comment by Green7** [comment] 2019-11-02 15:45
I have this same problem. Golang based dll is used in installer app (on windows). When installer finishes, it releases all used libraries. Occasionally this causes panic in golang code (from the released library). In this case process exit code is changed and program ends with 0xC0000005 (reported by Windows as Integer value, so for example in .bat file errorlevel shows  -1073741819).
It's very confusing and it took me a long time to detect the problem because it doesn't happen every time. It's easy to repeat this error in c ++ code: all you nedd is call function from golang dll, next FreeLibrary and make short delay (Sleep(2000) is enough) before the program ends. 
Workaround: as suggested in # 11100, do not release the library. In my case I "lock" the library by an additional call to LoadLibrary from the library itself.

**Comment by jlevitt** [comment] 2022-04-26 01:19
I'm also seeing this issue trying to use a golang dll I wrote in Visual Studio 2017.

**Comment by funte** [comment] 2022-06-25 12:12
Same issue
![1](https://user-images.githubusercontent.com/9884836/175772979-67e598c9-daea-426c-a440-55fb03dbe243.png)

**Comment by seankhliao** [comment] 2023-01-02 13:35
Duplicate of #https://github.com/golang/go/issues/11100

**Closed by seankhliao** 2023-01-02 13:35 UTC
Labels: OS-Windows, NeedsInvestigation, compiler/runtime
