### ISSUE TITLE
runtime: TestSmhasherWindowed is still flaky on linux-386-longtest

### ISSUE THREAD

**Issue by bcmills** [golang/go#43130] opened 2020-12-11 02:39 UTC
[2020-12-10T22:58:49-6d3d3fb/linux-386-longtest](https://build.golang.org/log/5750dc9ccbde14acb96e92ecba6aa5a13d18c2f0)
```
##### GOMAXPROCS=2 runtime -cpu=1,2,4 -quick
--- FAIL: TestSmhasherWindowed (27.87s)
    hash_test.go:566: 32 bit keys
    hash_test.go:161: unexpected number of collisions: got=512 mean=0.499992 stddev=0.707101 threshold=156.565200
    hash_test.go:568: 64 bit keys
    hash_test.go:570: string keys
--- FAIL: TestSmhasherWindowed (26.69s)
    hash_test.go:566: 32 bit keys
    hash_test.go:161: unexpected number of collisions: got=512 mean=0.499992 stddev=0.707101 threshold=156.565200
    hash_test.go:568: 64 bit keys
    hash_test.go:570: string keys
--- FAIL: TestSmhasherWindowed (26.69s)
    hash_test.go:566: 32 bit keys
    hash_test.go:161: unexpected number of collisions: got=512 mean=0.499992 stddev=0.707101 threshold=156.565200
    hash_test.go:568: 64 bit keys
    hash_test.go:570: string keys
FAIL
FAIL	runtime	598.996s
```

[2020-10-26T21:47:49-36c5edd/linux-386-longtest](https://build.golang.org/log/02cd0210da985203ebd477cc274346b4d8f77da7)

```
--- FAIL: TestSmhasherWindowed (26.23s)
    hash_test.go:566: 32 bit keys
    hash_test.go:161: unexpected number of collisions: got=512 mean=0.499992 stddev=0.707101 threshold=156.565200
    hash_test.go:568: 64 bit keys
    hash_test.go:161: unexpected number of collisions: got=512 mean=0.499992 stddev=0.707101 threshold=156.565200
    hash_test.go:570: string keys
FAIL
FAIL	runtime	169.624s
```

See previously #39352.

I would guess that it's flaky on 32-bit ARM too, but we don't have a `longtest` builder for that configuration.

CC @randall77

**Comment by bcmills** [comment] 2021-01-25 14:41
[2021-01-22T23:03:58-25c39e4/linux-386-longtest](https://build.golang.org/log/8f105bb2b730b26157b93848b7f956c2b4bac718)
```
--- FAIL: TestSmhasherWindowed (26.54s)
    hash_test.go:566: 32 bit keys
    hash_test.go:568: 64 bit keys
    hash_test.go:570: string keys
    hash_test.go:161: unexpected number of collisions: got=514 mean=0.499992 stddev=0.707101 threshold=156.565200
    hash_test.go:161: unexpected number of collisions: got=256 mean=0.499992 stddev=0.707101 threshold=156.565200
FAIL
FAIL	runtime	182.398s
```

**Comment by bcmills** [comment] 2021-08-05 14:24
[2021-08-04T15:26:45-6e73886/linux-386-longtest](https://build.golang.org/log/5e5e874554a4b8d9588353fcd4f35e4a51bb3123)
[2021-02-25T19:57:49-6c3bcda/linux-386-longtest](https://build.golang.org/log/dd78bdee5982a90257711a2d95cc68fafdfde38d)
[2021-02-23T19:55:03-a671e33/linux-386-longtest](https://build.golang.org/log/ceaacfa6f54bf4256efe9d407f9df821bb6355f0)

**Comment by mengzhuo** [comment] 2022-01-06 06:33
@bcmills Is this still flaky after https://github.com/golang/go/commit/483533df9e35eea46747c5545307b230eca997b6 ? 

The order of cpuinit and alginit does matters.

**Comment by mengzhuo** [comment] 2022-01-07 07:34
Updates: I've run 32 bits SmhasherWindow for 4770 times (~24h) without failures...

**Comment by bcmills** [comment] 2022-01-20 02:43
Indeed, still failing about once a month. The more recent failures are back to 512 collisions each.

`greplogs --dashboard -md -l -e '(?ms)FAIL: TestSmhasherWindowed.*unexpected number of collisions' --since=2021-09-24`

[2022-01-19T20:54:49-1efc581/linux-386-longtest](https://build.golang.org/log/e9693aa427944023c1ffe336675b74a8a448a3d2)
[2021-12-19T20:16:45-87b2a54/linux-386-longtest](https://build.golang.org/log/b115f9304c10f9a35a35511626e4aaee5d014987)
[2021-11-15T21:22:17-e08aae2/linux-386-longtest](https://build.golang.org/log/f3fb721fa420fc1fb7865119c16efdd9fcbd4a82)
[2021-10-23T12:44:47-b0f7eb6/linux-386-longtest](https://build.golang.org/log/9468b6e05d0edb175a0ab196f755c2fd07a44c1b)

**Comment by mengzhuo** [comment] 2022-01-20 06:58
> Indeed, still failing about once a month (and that's including the lower rate of test runs due to the code freeze). The more recent failures are back to 512 collisions each.

Recently a new version of Smhasher is released with the ["bad seed" testcase](https://github.com/rurban/smhasher/blob/master/doc/wyhash32.txt), which wyhash is failed ( caused by multiply 0).
Maybe we can skip "bad seed" on 32 bit platforms and regain a "good seed" in the alginit procedure.

**Comment by bcmills** [comment] 2022-02-03 19:30
@mengzhuo, at the very least would it be useful to have the test log the seed(s) that produced the unexpected collision rate? That would help to verify that this test failure is due to the expected bad seeds.

**Comment by mengzhuo** [comment] 2022-02-08 09:25
@randall77 Keith,

This issue can be reproduce within 6000 times run on 64 bit keys SmhasherWindow test.

After I deleted these 4 lines, no more flaky (12K runs):

https://github.com/golang/go/blob/69e1711f287f5cd92296240f99d347edc23d40b7/src/runtime/alg.go#L325-L328

I think the OR itself cancel the randomness of last bit (always 1)

Then I tried XOR
```
hashkey[0] ^= 1
```
no more falky too.

**Comment by bcmills** [comment] 2022-03-30 20:02
`greplogs --dashboard -md -l -e 'FAIL: TestSmhasherWindowed' --since=2022-02-08`

[2022-03-21T18:58:42-79103fa/linux-386-longtest](https://build.golang.org/log/615badde6ef5d0c279f1393efa3c90ff5b9b970a)

**Comment by bcmills** [comment] 2022-04-22 14:51
`greplogs --dashboard -md -l -e 'FAIL: TestSmhasherWindowed' --since=2022-04-12`

[2022-04-21T23:45:36-67d6be1/linux-386-longtest](https://build.golang.org/log/6ae8d160ad8977be89e332c528122fe80d260cae)

**Comment by bcmills** [comment] 2022-04-22 14:53
@golang/runtime: this is a recurring failure on `linux/386`, which is a [first class port](https://go.dev/wiki/PortingPolicy#first-class-ports). Could someone take a look at this and either fix it (if feasible) or add a test skip (if this turns out not to be a priority)?

**Closed** 2022-04-27 00:11 UTC
Labels: Testing, NeedsInvestigation, release-blocker
