### ISSUE TITLE
go1.11 build shared and for to windows dll still not supported from year 2015 on win x64

### ISSUE THREAD

**Issue by ManPython** [golang/go#27922] opened 2018-09-28 14:08 UTC
This is still missed function in x64 amd windows system from 2015 y. Why?
https://github.com/golang/go/issues/11058
https://github.com/golang/go/issues/23052

http://blog.ralch.com/tutorial/golang-sharing-libraries/

**Comment by ianlancetaylor** [comment] 2018-09-28 14:13
The two issues you mention are closed.  What actual problem are you asking about?

**Comment by ManPython** [comment] 2018-09-28 14:19
About this: "-buildmode=c-shared not supported on windows/amd64" 
Both issues touching this.

**Comment by ianlancetaylor** [comment] 2018-09-28 14:22
I'm sorry, I don't understand.  Those issues are closed.  As of the 1.10 release, `-buildmode=c-shared` does work on windows/amd64.

**Comment by ManPython** [comment] 2018-09-28 14:28
Imposible. I checked now on v1.10 and unistaled this to updated to v1.11 and "-buildmode=c-shared not supported on windows/amd64". 
My OS W7x64 U Sp1

**Comment by AlexRouSg** [comment] 2018-09-28 14:47
What is the exact command you are trying to run and what is the exact output?
I just tested on windows 10 x64 and it works

**Comment by ManPython** [comment] 2018-09-28 17:38
I lost here. I rebot OS, and again unistaled go and instal v1.11
https://www.darkcoding.net/software/building-shared-libraries-in-go-part-1/

**When runing in bat**
E:\GO\go build -o libdoubler.so -buildmode=c-archive main.go
# runtime/cgo
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

E:\GO\go build -ldflags="-s -w" -buildmode=shared main.go
# runtime/cgo
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
 
E:\GO\go build -ldflags="-s -w" -buildmode=shared main.go
-buildmode=shared not supported on windows/amd64

E:\GO\go build -ldflags="-s -w" -buildmode=c-archive main.go
# runtime/cgo
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in


go install -buildmode=shared -linkshared std
-buildmode=shared not supported on windows/amd64

go install -buildmode=shared -linkshared main.go
-buildmode=shared not supported on windows/amd64

I have instaled: 
TDM-GCC-32
TDM-GCC-64
mingw-w64

**Comment by AlexRouSg** [comment] 2018-09-28 18:00
This is not a problem with Go, this is your environment not being configured correctly.

Please uninstall all mingw versions, restart, and reinstall **only** TDM-GCC-64 and make sure `Add to PATH` is selected
![image](https://user-images.githubusercontent.com/5820839/46225222-2f864800-c38b-11e8-911a-b77b27f284c4.png)
![image](https://user-images.githubusercontent.com/5820839/46225238-38771980-c38b-11e8-99f0-c54ae09229f3.png)
![image](https://user-images.githubusercontent.com/5820839/46225202-1da4a500-c38b-11e8-9ae6-aa84a58c51ca.png)

**Comment by katiehockman** [comment] 2018-09-28 19:17
@ManPython did this resolve your issue?

**Comment by ManPython** [comment] 2018-09-28 19:38
Now I have just TDM-GCC-64 and no changes around problem.

But checked cc1.exe by https://docs.microsoft.com/en-us/sysinternals/downloads/sigcheck

tdm-gcc-64\libexec\gcc\x86_64-w64-mingw32\5.1.0\cc1.exe:
        Verified:       Unsigned
        Link date:      10:58 2027-08-18
        Publisher:      n/a
        Company:        n/a
        Description:    n/a
        Product:        n/a
        Prod version:   n/a
        File version:   n/a
        **MachineType:    32-bit**

Soo? There is long time conflict? Coz TDM is not updated from 2015 on website.

**Comment by AlexRouSg** [comment] 2018-09-28 19:49
- From the desktop, right click the Computer icon.
- Choose Properties from the context menu.
- Click the Advanced system settings link.
- Click Environment Variables

![image](https://user-images.githubusercontent.com/5820839/46230175-58faa000-c39a-11e8-9238-6c0bdaf82a82.png)

If `C:\TDM-GCC-64\bin` or where you installed TDM is not in that string, add it by putting `;C:\WHERE IS TDM-GCC-64\bin` at the end. The `;` is important

**Comment by ManPython** [comment] 2018-09-28 20:05
Still not working.

C:\>gcc --version
gcc (MinGW.org GCC-6.3.0-1) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

tdm-gcc-64\bin\gcc.exe:
        Verified:       Unsigned
        Link date:      02:00 1970-01-01
        Publisher:      n/a
        Company:        n/a
        Description:    n/a
        Product:        n/a
        Prod version:   n/a
        File version:   n/a
        MachineType:    32-bit

**Comment by AlexRouSg** [comment] 2018-09-28 20:06
You still have multiple mingw installations. If you only had TDM it would've said `gcc.exe (tdm64-1) 5.1.0`

**Comment by ManPython** [comment] 2018-09-28 20:35
You was right. I do research with regedit i found minigw with other software. 
Now working c-shared, but.. just these function as bellow not

go build -o libdoubler.so -buildmode=shared main.go
-buildmode=shared not supported on windows/amd64

go build -o libdoubler.dll -buildmode=shared main.go
-buildmode=shared not supported on windows/amd64

**Comment by ManPython** [comment] 2018-09-28 20:50
So we can't produce .dll in win x64? Just .so?
Is this working on win 386 and go1.11.windows-386 this same (just .so?) ?

I changed topic to clarify situation.

**Comment by AlexRouSg** [comment] 2018-09-28 20:57
`buildmode=c-shared` creates a dll to be used in C programs. It is creating a `.so` cause you told it to name it `.so`, change the name to be `.dll`
`buildmode=shared` is to create a dll to be used in Go programs, it is not implemented for windows at all.

**Comment by AlexRouSg** [comment] 2018-09-28 21:02
Please direct further questions to one of the places listed in https://github.com/golang/go/wiki/Questions
The bug tracker is only used for bugs, and this is clearly not a bug or actionable report.

**Comment by ManPython** [comment] 2018-09-28 21:10
Ok. Just last one.
I created .dll but can't call this by ctypes in python this same as .so 

In dependency walker I don't see the function DoubleIt as normaly in other .dll's 
The .so is available to see functions
![so in dependecy](https://user-images.githubusercontent.com/25403861/46233630-add6f000-c373-11e8-918a-591356ea4005.png)

**Comment by ianlancetaylor** [comment] 2018-09-28 22:55
I'm closing this issue.  Please use a forum, where there will be more people who can help you.  See https://golang.org/wiki/Questions .  Thanks.

**Closed by ianlancetaylor** 2018-09-28 22:55 UTC
Labels: WaitingForInfo
