### ISSUE TITLE
proposal: x/tools/cmd/present: use embed the static assets

### ISSUE THREAD

**Issue by dolanor** [golang/go#55927] opened 2022-09-28 21:53 UTC
Currently, the present tool needs to be run from the `tools` repository to find the static assets path or you have to pass a `-base` flag to point where the static assets lie.

I believe `embed` really would improve user experience in that case. You can use present from any directory without the hassle of locating the `basePath` (which, with modules, is *hidden* in the `$GOPATH/pkg/mod/…` with a very long path).

**Comment by seankhliao** [comment] 2022-09-29 01:16
Duplicate of #43459

**Closed by seankhliao** 2022-09-29 01:16 UTC
Labels: Proposal
