### ISSUE TITLE
x/mobile/cmd/gomobile: init: "rename : access denied"

### ISSUE THREAD

**Issue by IniZio** [golang/go#13186] opened 2015-11-09 02:38 UTC
I used the command "gomobile init" , however it showed gomobile: rename C:\Users\username\Documents\GitHub\pkg\gomobile\work-006591391\openal\include\AL C:\Users\username\Documents\GitHub\pkg\gomobile\android-ndk-r10e\arm\sysroot\usr\include\AL: Access is denied." when C:\Users\username\Documents\GitHub\pkg\gomobile\work-006591391\openal\include\AL doesnt exist at all

**Comment by rakyll** [comment] 2015-11-13 21:11
I don't have access to a Windows machine. @hyangah, want to take a look when you have time?

**Comment by crawshaw** [comment] 2015-11-16 13:12
@IniZio I cannot reproduce this, running in either a cygwin bash shell or cmd.exe. Could you please provide:

- the output of ```go version```
- what value you have set for GOPATH
- the full output of ```gomobile init -x -v```

**Comment by atteka** [comment] 2016-09-01 10:58
I am seeing the same issue on Windows 10.

```
# go version                                                                                             
go version go1.6.3 windows/amd64           
``` 

```
# gomobile init -x -v                                                                                    
GOMOBILE=C:\Users\ansis\Go\pkg\gomobile                                                                                                          
rm -r -f "$GOMOBILE\android-ndk-r12b"                                                                                                            
mkdir -p $GOMOBILE\android-ndk-r12b                                                                                                              
WORK=C:\Users\ansis\Go\pkg\gomobile\work-565722299                                                                                               
mkdir -p $GOMOBILE\dl                                                                                                             
stat $GOMOBILE\dl\gomobile-ndk-r12b-windows-x86_64.tar.gz                                                                                        
tar xfz $GOMOBILE\dl\gomobile-ndk-r12b-windows-x86_64.tar.gz                                                                                     
mkdir -p $GOMOBILE\android-ndk-r12b\llvm                                                                                                         
mv $WORK\android-ndk-r12b\toolchains\llvm\prebuilt\windows-x86_64\lib64 $GOMOBILE\android-ndk-r12b\llvm\lib64                                    
rm -r -f "$GOMOBILE\android-ndk-r12b\llvm\lib64"                                                                                                 
mv $WORK\android-ndk-r12b\toolchains\llvm\prebuilt\windows-x86_64\bin $GOMOBILE\android-ndk-r12b\llvm\bin                                        
rm -r -f "$GOMOBILE\android-ndk-r12b\llvm\bin"                                                                                                   
mkdir -p $GOMOBILE\android-ndk-r12b\arm\sysroot                                                                                                  
mv $WORK\android-ndk-r12b\platforms\android-15\arch-arm\usr $GOMOBILE\android-ndk-r12b\arm\sysroot\usr                                           
rm -r -f "$GOMOBILE\android-ndk-r12b\arm\sysroot\usr"                                                                                            
mv $WORK\android-ndk-r12b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin $GOMOBILE\android-ndk-r12b\arm\bin                    
rm -r -f "$GOMOBILE\android-ndk-r12b\arm\bin"                                                                                                    
mv $WORK\android-ndk-r12b\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\lib $GOMOBILE\android-ndk-r12b\arm\lib                    
rm -r -f "$GOMOBILE\android-ndk-r12b\arm\lib"                                                                                                    
mkdir -p $GOMOBILE\android-ndk-r12b\arm\arm-linux-androideabi\bin                                                                                
ln -s $GOMOBILE\android-ndk-r12b\arm\bin\arm-linux-androideabi-ld.exe $GOMOBILE\android-ndk-r12b\arm\arm-linux-androideabi\bin\ld.exe            
ln -s $GOMOBILE\android-ndk-r12b\arm\bin\arm-linux-androideabi-as.exe $GOMOBILE\android-ndk-r12b\arm\arm-linux-androideabi\bin\as.exe            
ln -s $GOMOBILE\android-ndk-r12b\arm\bin\arm-linux-androideabi-nm.exe $GOMOBILE\android-ndk-r12b\arm\arm-linux-androideabi\bin\nm.exe            
ln -s $GOMOBILE\android-ndk-r12b\llvm\bin\clang.exe $GOMOBILE\android-ndk-r12b\arm\bin\arm-linux-androideabi-clang.exe                           
ln -s $GOMOBILE\android-ndk-r12b\llvm\bin\clang++.exe $GOMOBILE\android-ndk-r12b\arm\bin\arm-linux-androideabi-clang++.exe                       
ln -s $GOMOBILE\android-ndk-r12b\llvm\lib64 $GOMOBILE\android-ndk-r12b\arm\lib64                                                                 
mkdir -p $GOMOBILE\android-ndk-r12b\arm64\sysroot                                                                                                
mv $WORK\android-ndk-r12b\platforms\android-21\arch-arm64\usr $GOMOBILE\android-ndk-r12b\arm64\sysroot\usr                                       
rm -r -f "$GOMOBILE\android-ndk-r12b\arm64\sysroot\usr"                                                                                          
mv $WORK\android-ndk-r12b\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64\bin $GOMOBILE\android-ndk-r12b\arm64\bin                  
rm -r -f "$GOMOBILE\android-ndk-r12b\arm64\bin"                                                                                                  
rm -r -f "$WORK"                                                                                                                                 
gomobile: rename C:\Users\ansis\Go\pkg\gomobile\work-565722299\android-ndk-r12b\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64\bin 
C:\Users\ansis\Go\pkg\gomobile\android-ndk-r12b\arm64\bin: Access is denied. 
```

**Comment by eliasnaur** [comment] 2018-03-16 13:27
I'm closing this. Gomobile doesn't download the NDK anymore.

**Closed by eliasnaur** 2018-03-16 13:27 UTC
Labels: mobile
