### ISSUE TITLE
cmd/vet: structtag false positives about `json:"-,omitempty"` for unexported fields

### ISSUE THREAD

**Issue by dolmen** [golang/go#51298] opened 2022-02-21 14:00 UTC
`go vet -structtag` skips private fields with JSON tag `-`, but doesn't skip those with tag `-,omitempty`. This is inconsistent.

### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17.6
</pre>

### Does this issue reproduce with the latest release?

Yes, also with `go1.18beta2`.

### What did you do?

```go
package main

type X struct {
	a int `json:"-"`
	b int `json:"-"`
	c int `json:"-,omitempty"`
	d int `json:"-,omitempty"`
}

func main() {
}
```

### What did you see?

```console
$ go vet -structtag main.go
# command-line-arguments
./main.go:6:2: struct field c has json tag but is not exported
./main.go:7:2: struct field d repeats json tag "-" also at main.go:6
./main.go:7:2: struct field d has json tag but is not exported
```

### What did you expect to see?

No error.

If `a` and `b` are not reported, neither should `c` or `d`.

Or maybe the error should be about the presence of `omitempty`.

**Comment by timothy-king** [comment] 2022-02-22 03:57
My understanding is that the vet check is WAI.
```
c int `json:"-,omitempty"`
```
is naming the unexported field of X `c` as "-" within the json and adding the "omitempty" option to it. The same is then done with `d`. This also repeats a json name "-".

This is my reading of https://pkg.go.dev/encoding/json:

> The encoding of each struct field can be customized by the format string stored under the "json" key in the struct field's tag. The format string gives the name of the field, possibly followed by a comma-separated list of options. The name may be empty in order to specify options without overriding the default field name.

and

> As a special case, if the field tag is "-", the field is always omitted. Note that a field with name "-" can still be generated using the tag "-,".

Someone authoritative on "encoding/json" want to weight in?

If this is WAI, we might want to add additional checks so this case is easier to understand. Open to suggestions about how. (Complain about using "-" on "a" and "b" as they are unexported?) I think new checks would need a proposal.

**Comment by mengzhuo** [comment] 2022-02-22 04:19
cc owner @rsc https://dev.golang.org/owners

**Comment by guodongli-google** [comment] 2022-02-22 23:31
> is naming the unexported field of X `c` as "-" within the json and adding the "omitempty" option to it. The same is then done with `d`. This also repeats a json name "-".

Second this. "c" is interpreted as a json field with name "-" and an extra tag "omitempty"
```
  c int `json:"-,omitempty"`
```
In addition, using `json:"-,omitempty"` seems to be improper since "-" indicates to skip the field and "omitempty" indicates to skip the field when it is empty. It suffices to have only the "-". So this warning correctly reports something that shall be rectified.

**Comment by mengzhuo** [comment] 2022-03-08 08:42
I agree with @timothy-king,
 "-" is an valid field name according to the document which we should do a duplicate checks on.

https://pkg.go.dev/encoding/json@go1.17.8
```go
// Field appears in JSON as key "-".
Field int `json:"-,"``
```

Is it ok to close this issue?

**Comment by seankhliao** [comment] 2022-08-20 14:50
Looks like the consensus is working as intended

**Closed by seankhliao** 2022-08-20 14:50 UTC
Labels: NeedsFix
