### ISSUE TITLE
gccgo: internal compiler error with cyclic variable declaration (esoteric)

### ISSUE THREAD

**Issue by griesemer** [golang/go#25679] opened 2018-06-01 00:34 UTC
With
```
$ gccgo --version
gccgo (google-gccgo-257955) 8.0.1 20180223 (experimental)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
compiling the following program
```Go
$ cat x.go
package main

import "unsafe"
import "fmt"

var x [uintptr(unsafe.Sizeof(&x))]byte

func main() {
	fmt.Println(x)
}
```
leads to an internal compiler error:
```
$ gccgo x.go
gccgo: internal compiler error: Segmentation fault signal terminated program go1
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://go.ext.google.com/go/> for instructions.
```
Notably, the following variation introducing an intermediate alias type name:
```Go
$ cat x.go
package main

import "unsafe"
import "fmt"

var x T

type T = [uintptr(unsafe.Sizeof(&x))]byte

func main() {
	fmt.Println(x)
}
```
compiles and runs correctly:
```
$ gccgo x.go && a.out
[0 0 0 0 0 0 0 0]
```
(The same is true if the type declaration is a type definition of T).

cc: @thanm

**Comment by AlbinoGeek** [comment] 2018-06-01 01:51
Duplicate of #25680 , but with more information?

**Comment by deanveloper** [comment] 2018-06-01 16:26
As with #25680 this is not valid go for the same reason. `[uintptr(unsafe.Sizeof(&x))]byte` is not a valid type, as `uintptr(unsafe.Sizeof(&x))` is not a constant.

Or well, it shouldn't technically be. I'm not sure if the compiler inlines `unsafe.Sizeof`, in which case it may be considered a constant?

**Closed** 2018-06-04 19:09 UTC
Labels: NeedsInvestigation
