### ISSUE TITLE
cmd/cover: frequent timeouts on plan9-arm

### ISSUE THREAD

**Issue by bcmills** [golang/go#49337] opened 2021-11-04 02:59 UTC
`greplogs --dashboard -md -l -e '(?ms)\Aplan9.*panic: test timed out.*FAIL\s+cmd/cover'`

<details>

[2021-11-03T23:48:28-283373d/plan9-arm](https://build.golang.org/log/0d4ccf062af6ffa10f64c57b827b5a340ddf739f)
[2021-11-03T18:37:22-cfd016d/plan9-arm](https://build.golang.org/log/5c3f00e24bef11857c7bcf3f041300fdf6d3ece9)
[2021-11-03T15:59:11-5f0e5d2/plan9-arm](https://build.golang.org/log/4ec953a8a50a2dd847b5f793bdb4bd164cfb3f8b)
[2021-11-03T00:21:24-8f0ca7d/plan9-arm](https://build.golang.org/log/8a94d9c65f0bd85803b36b00ff2416f9d246997f)
[2021-11-02T19:37:42-1011e26/plan9-arm](https://build.golang.org/log/7ac2c697daa79e442bcdaeb43f883b5e48b5fc3f)
[2021-11-02T06:21:44-3ee426a/plan9-arm](https://build.golang.org/log/e034c632962d3bcd727b0bdc850441823f774bd4)
[2021-11-02T06:20:21-c1ea339/plan9-arm](https://build.golang.org/log/4790c7307a3c4467262802e674d1722f55f55ad4)
[2021-11-02T06:19:33-4633b2d/plan9-arm](https://build.golang.org/log/317fc95de31415b349a30f3c705c713ddbc231ee)
[2021-10-13T16:36:59-69041c7/plan9-arm](https://build.golang.org/log/ef7517682e02736318babd0c4a17cbf60932b992)
[2021-10-11T20:46:14-7023535/plan9-arm](https://build.golang.org/log/4d62f91f0d7ef89c08af5aa7b3fcec4080011309)
[2021-10-08T14:08:12-5b9206f/plan9-arm](https://build.golang.org/log/15e41aff1056376d41007885a76437b0f9528728)
[2021-10-05T23:58:29-ac60900/plan9-arm](https://build.golang.org/log/ef4b8952e8c4a3d1b25b9e1c9412309fe4a8b2dc)
[2021-10-05T20:52:58-0d6561b/plan9-arm](https://build.golang.org/log/af561b98a4245cc25911680bf2708545030210e4)
[2021-10-05T15:47:07-cfd74f7/plan9-arm](https://build.golang.org/log/400e2c9cfcab469755b5b1f86dd304b5685f2c68)
[2021-10-04T22:59:44-78c2529/plan9-arm](https://build.golang.org/log/15a0d20c4c04e8852a29c5ed35e7e51cc1cf9f34)
[2021-09-30T21:33:51-6a79f35/plan9-arm](https://build.golang.org/log/2eb2152472789114a0e50ede8f8305021ac78f93)
[2021-09-29T16:45:42-2fad7db/plan9-arm](https://build.golang.org/log/4dc6748cfc9cc7bbdf1450a42071c5c620b7c5b0)
[2021-09-29T13:53:55-e180e2c/plan9-arm](https://build.golang.org/log/2c63669381ac539305539c8b14212b6555c1ffc0)
[2021-09-28T17:18:36-ff7b041/plan9-arm](https://build.golang.org/log/d009c4f5155e5661b4623d27c799af572ddadf78)
[2021-09-20T18:31:54-6268468/plan9-arm](https://build.golang.org/log/2ffe8c240b9d792ebaccfa030d8b53633f8f38e4)
[2021-09-20T16:27:53-79159f2/plan9-arm](https://build.golang.org/log/1e5eec9882a369ecae0793c7625ff81839951c05)
[2021-09-20T16:20:33-2d9b486/plan9-arm](https://build.golang.org/log/d529a22ae3cfe4f1a2724b359dc6deaef49eb5ae)
[2021-09-20T00:13:47-a83a558/plan9-arm](https://build.golang.org/log/a778f1bda2df22127e1796f574f4398d5fc26b77)
[2021-09-16T19:38:19-bcdc61d/plan9-arm](https://build.golang.org/log/5c44cd91f6679fa0e04da225448d74565a847aa7)
[2021-09-15T20:29:43-03df68d/plan9-arm](https://build.golang.org/log/317818d56ede2746f4347a03dbc0d8482abcacc4)
[2021-09-15T03:29:44-3100f54/plan9-arm](https://build.golang.org/log/c2dc23973b1d9d2d56649743631e3bea7cb4700f)
[2021-09-15T03:29:41-b26d325/plan9-arm](https://build.golang.org/log/60e331ff098ea8dd1705dedc4f2c9fb977fa239f)
[2021-09-14T23:07:15-137543b/plan9-arm](https://build.golang.org/log/2fd36a3da9cb32a7991a4eb6c58e7847ccd7713c)
[2021-09-14T02:52:21-b8c802b/plan9-arm](https://build.golang.org/log/ddfcb6975da3636cf631ad46575f500e42aa1fe2)
[2021-09-13T17:56:18-bced369/plan9-arm](https://build.golang.org/log/809fec98c3ec5a66d37ae7b78fbdd053530e2c19)
[2021-09-12T16:46:58-ad97d20/plan9-arm](https://build.golang.org/log/e0f9f807217b614621375facf23e2fafec85b9d1)
[2021-09-10T17:11:39-5a4b9f9/plan9-arm](https://build.golang.org/log/de0d9e58072cf603f0f65815c069bc6fc8e61faa)
[2021-09-10T17:09:57-025308f/plan9-arm](https://build.golang.org/log/750ac261e92b1d13301ca9d020a14c322adf71d1)
[2021-09-10T16:51:52-5a94a90/plan9-arm](https://build.golang.org/log/71c0584997dac01930b5c39ef27bb4b65a08dfb5)
[2021-09-09T23:18:18-b32209d/plan9-arm](https://build.golang.org/log/35ffa80c9cde827d0e31bbcc714cf4782a35c063)
[2021-09-09T21:28:56-c981874/plan9-arm](https://build.golang.org/log/8d1d1cbc5a9569f1fd40ea21da3496512390dfa0)
[2021-09-08T00:34:17-bab79dd/plan9-arm](https://build.golang.org/log/8fbfc047363656f751336b11fae6cb4be333360b)
[2021-09-04T10:42:34-9cb5716/plan9-arm](https://build.golang.org/log/61bf4acb2a4673501cdaccd0a1365cc259bb1636)
[2021-09-02T19:33:52-58244ee/plan9-arm](https://build.golang.org/log/63ac6208e4b831567a0d8e65214238250f73de32)
[2021-09-01T07:10:24-717f337/plan9-arm](https://build.golang.org/log/f896247e4e547bcfe34cf3633bd018cd1a4f6a95)
[2021-09-01T00:37:23-36ac221/plan9-arm](https://build.golang.org/log/5fe596ad0a8b767b529c059b7b1173fcfae1eec3)
[2021-08-31T22:47:49-b2f09cd/plan9-arm](https://build.golang.org/log/ef2bba5d4a2d40a68ef4aea8ea50c24189836367)
[2021-08-31T16:20:54-605d1aa/plan9-arm](https://build.golang.org/log/6499fd1d1714360eb832ae6398071626898189a0)
[2021-08-28T18:48:37-f4cd001/plan9-arm](https://build.golang.org/log/6069588fbf69cbac846a78e5ba3f0b46da6705d8)
[2021-08-28T00:50:13-c81fa00/plan9-arm](https://build.golang.org/log/73d8a6fdc2c243d951e1d93a72a4d61f6e7f7db0)
[2021-08-27T18:01:06-94f2a03/plan9-arm](https://build.golang.org/log/e01858e2af2e323c24b135445a8fd4c1f3cd301e)
[2021-08-24T16:36:59-e679879/plan9-arm](https://build.golang.org/log/c8e1cfaba1978f8432472dc197208ffc9219d3c3)
[2021-08-24T16:36:55-b1cdf86/plan9-arm](https://build.golang.org/log/0b0f47a733f42503205d8a608d46d1ee6ae2363f)
[2021-08-24T16:36:48-1ff0554/plan9-arm](https://build.golang.org/log/4c65ff00b45ccc91dbe176b3662ac4e448b66575)
[2021-08-23T20:04:34-fa34678/plan9-arm](https://build.golang.org/log/776ac31c7fffb23575380617214a70fec7fc0440)
[2021-08-23T19:49:23-0a7f00a/plan9-arm](https://build.golang.org/log/66a94a630cb11ccde21011d122b039ed999585fa)
[2021-08-23T13:09:18-4fbb5c8/plan9-arm](https://build.golang.org/log/28f510694d3c7a329912aa5bf6b7aa3d0683a100)
[2021-08-23T13:07:43-9fe5c7f/plan9-arm](https://build.golang.org/log/3153a8552a2e7726b6370b552cffa3d521266d2e)
[2021-08-21T00:24:02-c991278/plan9-arm](https://build.golang.org/log/398d5bfda2935e0c807c666d57e3d90c04a8f992)
[2021-08-20T18:45:05-e49775e/plan9-arm](https://build.golang.org/log/81381525e79bde0be6902be7fd708b4c8875658a)
[2021-08-20T03:25:36-e9e0d1e/plan9-arm](https://build.golang.org/log/b8d36076aa3960b823bfc931f0433daf7305f9fc)
[2021-08-17T02:50:08-29ec74f/plan9-arm](https://build.golang.org/log/37a3b0040770597f15e1f1b261708def3be542e3)
[2021-08-16T20:23:26-a05a7d4/plan9-arm](https://build.golang.org/log/9b8ce5e020e2386cd489d79f89551a56dfa8d5c0)
[2021-08-16T18:45:07-ddffe30/plan9-arm](https://build.golang.org/log/036f66b060ca4ec88ae6abf70ce199577e46e4be)
[2021-08-16T14:26:59-11a43df/plan9-arm](https://build.golang.org/log/107c9bd7151f6e9da003d1cacb5e145d5084e85c)
[2021-08-16T13:38:44-11a1f37/plan9-arm](https://build.golang.org/log/2e29756b41f937a177ade9849d399bda67a1ecfd)
[2021-08-16T10:46:11-3d679c6/plan9-arm](https://build.golang.org/log/37bdf2bb5fd3a6e7fdd7a94b9863af9770026310)
[2021-08-15T19:56:18-717894c/plan9-arm](https://build.golang.org/log/da819c32fb14d0eeb50a291cf20cfc87b1fe0749)
[2021-08-15T00:19:34-1162aae/plan9-arm](https://build.golang.org/log/40adbff2f7fb7470e9c49b651f77ba945af02544)
[2021-07-22T19:26:40-798ec73/plan9-arm](https://build.golang.org/log/816c7f09659d7ebe4f7e86db86dd503835cfc5ea)
[2021-05-28T18:34:18-6f58088/plan9-arm](https://build.golang.org/log/d1f88856e7eb488538f7f70a8cf9b71d174b1f40)
[2021-05-27T21:41:58-193d514/plan9-arm](https://build.golang.org/log/323b5ae6bf37a5baf40454b5776318721c343cc3)
[2021-05-19T01:09:20-15a374d/plan9-arm](https://build.golang.org/log/34ea64dc937b93f90c0cdd3dc905572734edcdd6)
[2021-05-14T15:35:28-a938e52/plan9-arm](https://build.golang.org/log/0d42505eca1c049b5278308caa8c190e83a7ccb8)
[2021-05-10T17:21:32-d9e068d/plan9-arm](https://build.golang.org/log/1f8a89b4a385465a12ba6bb2360cdfc439dfcbe3)
[2021-05-08T03:27:59-b211fe0/plan9-arm](https://build.golang.org/log/6769347f8c87d037955d74f6f2e60db4fc736cf6)
[2021-05-07T21:35:41-f24eac4/plan9-arm](https://build.golang.org/log/f19a191d90a9f457be1fcf005d1a05ce14728967)
[2021-05-07T17:43:31-b44c78b/plan9-arm](https://build.golang.org/log/22e936cef931053276185f11f3932070ff8d08ab)
[2021-05-06T20:30:00-4dbad79/plan9-arm](https://build.golang.org/log/b7f58e9d2e4958afab70dfbd10cd1da60eb42a7c)
[2021-05-05T04:48:30-9e0facd/plan9-arm](https://build.golang.org/log/394f4b7593dfde18aa8a19c5dcaa1fbad3c359e9)
[2021-05-05T01:11:17-bb5e452/plan9-arm](https://build.golang.org/log/e6f24fe0a22d8b8e3ad7a6157d2fd1d7932d15be)
[2021-05-04T22:12:31-6a6aa32/plan9-arm](https://build.golang.org/log/e6deee35ca19c85baeffbc1e8a85795f40955a0f)
[2021-05-04T20:18:55-10a082a/plan9-arm](https://build.golang.org/log/8707929b01ad615dd7031b523fb45cbbf12ce849)
[2021-04-29T16:31:18-5a8435d/plan9-arm](https://build.golang.org/log/d456e59fcbeedd1c471a35ff16d5cb3b44c4e1f1)
[2021-04-28T20:36:50-fa6ed6e/plan9-arm](https://build.golang.org/log/5501e658ad7ad32cbcba4070311264c9a878dba7)
[2021-04-27T11:50:41-1eca6aa/plan9-arm](https://build.golang.org/log/dbbc2fc776dd2794ad3ef9a480e4e17d0bd95327)
[2021-04-23T13:48:10-bedfeed/plan9-arm](https://build.golang.org/log/8e5431441d17cf7ce0b88cd77b9508a3051c98c0)
[2021-04-16T16:40:34-acb189e/plan9-arm](https://build.golang.org/log/5138d82dcb499932daf5d6ee0478d1b954e4fa8e)
[2021-04-12T17:56:06-865d2bc/plan9-arm](https://build.golang.org/log/7cde045177400251a1bd7f0d18332b3d27ee7277)
[2021-04-11T20:41:32-0da9eff/plan9-arm](https://build.golang.org/log/3ab659b78854d2b873526724dcfc240a7e79d184)
[2021-04-09T13:19:10-dcc801e/plan9-arm](https://build.golang.org/log/762d8643c6ad6d5bb89ac94824b5444715597085)
[2021-04-08T20:26:47-a9e475a/plan9-arm](https://build.golang.org/log/8bb9254257f92aaa84f256114636e66dab3d85c2)
[2021-04-08T17:44:21-ca8540a/plan9-arm](https://build.golang.org/log/324728fb65de613a32d38d4b1fe5ad519c55608c)
[2021-04-07T06:53:34-5d5f779/plan9-arm](https://build.golang.org/log/38fd9ef67d4657221929f51adbbaed8b3f0efc82)
[2021-04-06T18:55:39-d57189e/plan9-arm](https://build.golang.org/log/f3fb87f127940ef18bdafe06769d612cb52f0583)
[2021-04-03T20:16:00-dac136f/plan9-arm](https://build.golang.org/log/fe4de1937bad1097dc6a3f0a6951006bbc3cec4d)
[2021-04-03T10:58:19-fe587ce/plan9-arm](https://build.golang.org/log/a0f34a80dcf70541904ff55cfc13d04a33d801ce)
[2021-04-03T01:45:06-a1e4657/plan9-arm](https://build.golang.org/log/ea5fd61c1d4cf68ac8769e97f171b18c604b6293)
[2021-04-02T21:59:37-2ebe77a/plan9-arm](https://build.golang.org/log/9a821dfc873b328b685d7f4304dc293649e5a5d5)
[2021-04-02T16:30:18-759116b/plan9-arm](https://build.golang.org/log/a4f4ef27ac82dacac37a7cf0ba87014a53d374bc)
[2021-04-01T05:43:24-e6ac2df/plan9-arm](https://build.golang.org/log/7dbe811ff93f86f12f674ac72c7e4cf3d3aab48c)
[2021-03-31T20:28:39-87c6fa4/plan9-arm](https://build.golang.org/log/9ff3dc3db13fd8955920b4c62bf303f90e9a59e0)
[2021-03-28T03:27:04-23ffb5b/plan9-arm](https://build.golang.org/log/7765450e4483c59f55f825dd14b0dcee9452005e)
[2021-03-25T04:11:06-607f999/plan9-arm](https://build.golang.org/log/4f21d35e847c4d0b1da7b76619252b9d95cc25b0)
[2021-03-24T05:15:53-2e94401/plan9-arm](https://build.golang.org/log/6ace89e7a224b87f2e491fdc92cbed380e790aa9)
[2021-03-20T17:08:03-e0fae78/plan9-arm](https://build.golang.org/log/287f29992144d2a9d56d4fe8c3a7f3fa5387563a)
[2021-03-18T16:51:22-6461d74/plan9-arm](https://build.golang.org/log/844741c85ab97e333f680ea122e841fd6296d4ea)
[2021-03-17T20:29:22-4313c28/plan9-arm](https://build.golang.org/log/5733184ba78254625fa8cf7d83c778c9140ff4fd)
[2021-03-16T19:23:36-d206ca5/plan9-arm](https://build.golang.org/log/b57dd0a097d142d9448bc176e3865ab65f87dd65)
[2021-03-15T17:35:11-0f4bb96/plan9-arm](https://build.golang.org/log/fea3c152e1c76044020b7fa941f1644c0e2c2799)
[2021-03-10T21:00:16-b7f0fb6/plan9-arm](https://build.golang.org/log/32edfb6f968a0aea829951e0de08acc14413cf0a)
[2021-03-05T18:46:43-9e6b1fc/plan9-arm](https://build.golang.org/log/2ac92135b81bdd475bdc3fc9b0284fc10b18d217)
[2021-03-05T17:46:57-67b9ecb/plan9-arm](https://build.golang.org/log/e1f100807b53e494eed3df7063e2b6f995a3a411)
[2021-01-27T18:21:21-ff9e836/plan9-arm](https://build.golang.org/log/a0dafa3ba987d0f98bdd4c6b55bca641c39a4b60)
[2020-04-30T01:17:47-4f7053c/plan9-arm](https://build.golang.org/log/addb13b988bc89e20ddf291908a17a1cb6b49e2e)
[2020-04-28T20:42:02-ca854f3/plan9-arm](https://build.golang.org/log/271f857a4eb9dd188ad56be07bcf2e9450c6b680)

</details>

@millerresearch, @0intro, @fhs: is there some change you can suggest to either the builder or the test to resolve this?

**Comment by millerresearch** [comment] 2021-11-04 10:33
> @millerresearch, @0intro, @fhs: is there some change you can suggest to either the builder or the test to resolve this?

This is a file locking bug in the plan 9 ramfs server (#48416). Today I've changed the builder configuration on plan9-arm to use the regular fossil filesystem for /tmp instead of ramfs, while we investigate this.

**Comment by millerresearch** [comment] 2022-07-17 09:30
Duplicate of #48416.

**Closed** 2022-07-17 09:30 UTC
Labels: OS-Plan9, NeedsInvestigation, compiler/runtime
