### ISSUE TITLE
Golang Proxy Cannot Retrieve golangci-lint

### ISSUE THREAD

**Issue by jaloren** [golang/go#34113] opened 2019-09-05 14:06 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Volumes/Repositories/go/bin"
GOCACHE="/Users/jlorenzini/Library/Caches/go-build"
GOENV="/Users/jlorenzini/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Volumes/Repositories/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jlorenzini/repos/dep/operator/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8w/7ndx_j6s36x9hm9dns67j21s3hynqn/T/go-build716492838=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Within the directory of a golang module, I ran the following command:

```
 go get github.com/golangci/golangci-lint@v1.17.1
```

### What did you expect to see?
That go get successfully downloaded golangci-lint and updated my go.mod with the appropriate requirements.

### What did you see instead?

```
go: finding github.com v1.17.1
go: finding github.com/golangci v1.17.1
verifying github.com/go-critic/go-critic@v0.0.0-20181204210945-1df300866540/go.mod: github.com/go-critic/go-critic@v0.0.0-20181204210945-1df300866540/go.mod: reading https://sum.golang.org/lookup/github.com/go-critic/go-critic@v0.0.0-20181204210945-1df300866540: 410 Gone
```

If I set the following environment variables, then the go get is successful.

```
export GOPROXY=direct GOSUMDB=off
```

**Comment by aofei** [comment] 2019-09-05 14:19
https://sum.golang.org/lookup/github.com/go-critic/go-critic@v0.0.0-20181204210945-1df300866540:

```
not found: github.com/go-critic/go-critic@v0.0.0-20181204210945-1df300866540: invalid pseudo-version: does not match version-control timestamp (2019-05-26T07:48:19Z)
```

This seems to be a tampered module version.

**Comment by aofei** [comment] 2019-09-05 14:25
The correct pseudo-version of https://github.com/go-critic/go-critic/commit/1df30086654074503eab008bdde4f3ce1921128d should be: `v0.0.0-20190526074819-1df300866540`.

You can submit an issue to [golangci/golangci-lint](github.com/golangci/golangci-lint) to have its author correct its `go.mod` file (and `go.sum` of course).

**Comment by hyangah** [comment] 2019-09-05 14:26
Thanks @aofei 

This is a duplicate of golangci/golangci-lint#652

**Closed** 2019-09-05 14:29 UTC
