### ISSUE TITLE
affected/package: httptest.NewRecorder() - TransferEncoding is nil

### ISSUE THREAD

**Issue by puppeteer701** [golang/go#56616] opened 2022-11-06 18:11 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.19.2
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/iva/.cache/go-build"
GOENV="/home/iva/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/iva/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/iva/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/nix/store/z99pbnhp88lfciv791fmi1283rv51qhz-go-1.19.2/share/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/nix/store/z99pbnhp88lfciv791fmi1283rv51qhz-go-1.19.2/share/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/iva/ManifoldFinance/http-tap-proxy/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3353252111=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I set a header `Transfer-Encoding: chunked` with response writer but when trying to read with the `httptest.ResponseRecorder` it is always nil. 

Code:
```
func TestNewProxyServerChunks(t *testing.T) {
    var (
        main = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
            // flusher, _ := w.(http.Flusher)
            // defer flusher.Flush()
            w.Header().Set("Transfer-Encoding", "chunked")
            w.Header().Set("Connection", "Keep-Alive")
            w.Header().Set("X-Content-Type-Options", "nosniff")

            w.WriteHeader(http.StatusOK)
            w.Write([]byte("some crazy text"))
        }))
        u, _  = url.Parse(main.URL)
        proxy = httputil.NewSingleHostReverseProxy(u)
    )

    defer main.Close()

    rr := httptest.NewRecorder()
    req := httptest.NewRequest(http.MethodGet, "/", nil)

    req.TransferEncoding = []string{"chunked"} // tried both ways, it does not work
    req.Header.Set("Transfer-Encoding", "chunked")

    proxy.ModifyResponse = func(resp *http.Response) error {
        // evaluating resp here returns correct TransferEncoding
        // resp.TransferEncoding = []string{"chunked"}
	return nil
    }
    proxy.ServeHTTP(rr, req)
    assert.Equal(t, http.StatusOK, rr.Code)
    a := rr.Result()

    assert.Equal(t, "chunked", a.TransferEncoding) // it is nil, no idea why
}
```

### What did you expect to see?
`responseRecorder.TransferEncoding = []string{"chunked"}`

### What did you see instead?
`responseRecorder.TransferEncoding = nil`

**Comment by seankhliao** [comment] 2022-11-06 19:51
transfer encoding is a hop by hop header.
the proxy is a hop.

closing as working as intended.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Closed by seankhliao** 2022-11-06 19:51 UTC

**Comment by puppeteer701** [comment] 2022-11-06 20:19
When doing the test with a curl I see in response the TransferEnoding is returned. Also, why then are other headers returned if the proxy is a hop?
