### ISSUE TITLE
proposal: go mod add search package

### ISSUE THREAD

**Issue by lucky51** [golang/go#51908] opened 2022-03-24 04:35 UTC
go mod add search package ,like [go.dev ](https://pkg.go.dev/)
```shell
go mod search xxx
```
![image](https://user-images.githubusercontent.com/27793729/159842903-fc8467bb-cf13-4d4a-8459-2548488ad971.png)

**Comment by seankhliao** [comment] 2022-03-24 09:33
Duplicate of #33203

**Closed by seankhliao** 2022-03-24 09:33 UTC
Labels: Proposal
