### ISSUE TITLE
Lack of generics is getting me mad

### ISSUE THREAD

**Issue by riwogo** [golang/go#19007] opened 2017-02-09 06:58 UTC
I know that many people posted this kind of issue but it really is getting me mad!:
Go is a great programming language and I love the simplicity of it but something is getting me mad and that is lack of generics in this language that probably caused lack of map(), reduce(), filter() and other functions that are needed for functional programming and are great tools for reducing code size and make code more clear. at least add these functions as built in functions in next versions or please add generics to this great language.

**Comment by dsnet** [comment] 2017-02-09 07:12
We understand that the lack of generics make certain use cases more painful and are aware of the issue. For now, I'm closing this as a duplicate of #15292

**Closed by dsnet** 2017-02-09 07:12 UTC

**Comment by pierrre** [comment] 2017-02-09 11:50
@riwogo http://www.thedotpost.com/2015/11/francesc-campoy-flores-functional-go
