### ISSUE TITLE
x/pkgsite: search no longer finds built-in modules

### ISSUE THREAD

**Issue by djmitche** [golang/go#47617] opened 2021-08-10 13:31 UTC
### What is the URL of the page with the issue?
 
https://pkg.go.dev/search?q=time
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
 
### Screenshot
 
<img width="927" alt="Screen Shot 2021-08-10 at 9 29 57 AM" src="https://user-images.githubusercontent.com/28673/128875714-d7929e94-4542-472b-8bb2-3a9c4ed468b5.png">
 
### What did you do?
 
 Searched for `time` 
 
### What did you expect to see?

https://pkg.go.dev/time should be the first result, or a least on the first page
 
I believe this worked correctly even a few days ago.

### What did you see instead?

Lots of other packages, many not even named `time`.

**Comment by seankhliao** [comment] 2021-08-10 13:57
Duplicate of #47555

**Closed by seankhliao** 2021-08-10 13:57 UTC
Labels: pkgsite
