### ISSUE TITLE
x/website: greetings.Hellos(names) invocation changed, but it's not highlighted

### ISSUE THREAD

**Issue by derrickstaten** [golang/go#46642] opened 2021-06-07 23:38 UTC
### Summary
On page https://golang.org/doc/tutorial/greetings-multiple-people, I'd expect the line `messages, err := greetings.Hellos(names)` to be bolded and in blue (i.e. rgb(0, 125, 156)), rather than in the default black font. This is because the function invocation `greetings.Hello` has been changed to `greetings.Hellos` in this step of the tutorial

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
It's a website formatting issue, not dependent on the go version

### What operating system and processor architecture are you using (`go env`)?

It's a website formatting issue, not dependent on the go version

### What did you do?

Visited https://golang.org/doc/tutorial/greetings-multiple-people and worked through the tutorial

### What did you expect to see?
The following bolded, with color blue (i.e. rgb(0, 125, 156))
<pre>
messages, err := greetings.Hellos(names)
</pre>

### What did you see instead?
The following in the normal formatting:
<pre>
messages, err := greetings.Hellos(names)
</pre>

**Comment by derrickstaten** [comment] 2021-06-07 23:40
Also, the line `fmt.Println(messages)` should be bolded and in blue as well

**Comment by ALTree** [comment] 2021-06-08 07:16
Note: this would be fixed by [cl 277454](https://go-review.googlesource.com/c/website/+/277454), currently under review (waiting for the author).

**Comment by dmitshur** [comment] 2021-06-08 20:02
Thanks for reporting. If I understand it correctly, this is a duplicate of #46416.

**Closed by dmitshur** 2021-06-08 20:02 UTC
Labels: NeedsFix
