### ISSUE TITLE
cmd/gc: converting len(slice) value to non-fitting numeric types should result in overflow error

### ISSUE THREAD

**Issue by nrvnrvn** [golang/go#33643] opened 2019-08-14 08:30 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
CC="clang"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_ENABLED="1"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
CXX="clang++"
GCCGO="gccgo"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/lol/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fq/v153jfj15jz73k94n8mzycl40000gn/T/go-build186400384=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOMOD="/mycoolproject/go.mod"
GOOS="darwin"
GOPATH="/Users/lol/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.7/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.7/libexec/pkg/tool/darwin_amd64"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?
https://play.golang.org/p/4RP50Tv00i8

### What did you expect to see?
https://play.golang.org/p/cvwZ7P8Fa_q

### What did you see instead?
overflowing value is converted to `0`

**Comment by zephyrtronium** [comment] 2019-08-14 15:08
This is closely related to #30613 and the various issues linked therefrom. That discussion might benefit from your use case for a checked uint8 type.

**Comment by andybons** [comment] 2019-08-15 17:03
@nrvnrvn are you expecting an error at compile time or runtime?

**Comment by nrvnrvn** [comment] 2019-08-15 17:57
Good question. I would expect a runtime error.

**Comment by andybons** [comment] 2019-08-15 18:15
At first this seems like a dupe of #31500. Would you agree?

**Comment by mvdan** [comment] 2021-06-15 11:44
The latest iteration on guarding against overflows is https://github.com/golang/go/issues/30209. I'd suggest to leave a comment there.

**Closed by mvdan** 2021-06-15 11:44 UTC
Labels: NeedsInvestigation, WaitingForInfo
