### ISSUE TITLE
cmd/compile: incorrect pluralization in error message

### ISSUE THREAD

**Issue by yurivish** [golang/go#45369] opened 2021-04-03 17:21 UTC
Go 1.16 produces incorrectly pluralized error message like this one:

```
assignment mismatch: 2 variables but r.Form.Get returns 1 values
```

The error is generated by this line:

https://github.com/golang/go/blob/c274a7c03be7b69d54d3307b954f6a0eb298c860/src/cmd/compile/internal/noder/noder.go#L440

which can be fixed by using a [plural](https://github.com/golang/go/blob/0265b6475f08f2c23a742132db87c357fcbfa458/src/cmd/compile/internal/typecheck/stmt.go#L221) function, e.g.:

https://github.com/golang/go/blob/0265b6475f08f2c23a742132db87c357fcbfa458/src/cmd/compile/internal/typecheck/stmt.go#L187

**Comment by ALTree** [comment] 2021-04-05 09:03
Please post a program that can be used to reproduce the issue. This seem another case of  #31099, which is fixed now on tip.

**Comment by yurivish** [comment] 2021-04-05 16:34
@ALTree 

Here's an example program (https://play.golang.org/p/pdxWzlrXTnj): 

```go
package main

func main() {
	a, b := 1 + 1
}
```

Apologies for not searching before filing this issue and thanks for the reference. Good to know it'll be fixed in the upcoming release!

**Comment by ALTree** [comment] 2021-04-05 16:55
Thanks for the reproducer. I can confirm that the issue is fixed on your example on tip:

```
$ gotip version
go version devel go1.17-7bfd681c2f Sun Apr 4 12:04:33 2021 +0000 linux/amd64

$ gotip build test.go

./test.go:4:7: assignment mismatch: 2 variables but 1 value
```

It seems that the error message is printed from
```
cmd/compile/internal/typecheck/stmt.go (line 187)
```

so we no longer execute the line with the bad pluralization in `noder.go` that you linked above. Still, that line does not pluralize correctly, and if some codepath ends up executing it we'll have a bad pluralization. Nothing urgent, but still.

cc @mdempsky.

**Comment by mdempsky** [comment] 2021-04-05 18:32
Those code paths won't be used anymore once we switch to the new typechecker, which is expected for Go 1.18 with generics and likely even in Go 1.17.

**Comment by ALTree** [comment] 2021-04-05 20:46
Thanks! Then we can close this, since no further action is needed to fix the issue, and on tip the correct message is already printed.

**Closed by ALTree** 2021-04-05 20:46 UTC
Labels: NeedsInvestigation
