### ISSUE TITLE
[BUG][go1.21.x] `fatal: morestack on g0`

### ISSUE THREAD

**Issue by valord577** [golang/go#63188] opened 2023-09-24 11:18 UTC
ref: https://github.com/fluent/fluent-bit-go/issues/71

go1.20.8 works fine.

**Comment by seankhliao** [comment] 2023-09-24 11:29
Duplicate of #62440

**Closed by seankhliao** 2023-09-24 11:29 UTC

**Comment by valord577** [comment] 2023-10-07 02:49
@seankhliao I followed [the issue](https://github.com/fluent/fluent-bit-go/issues/71) and tested it using golang:1.21.2-bullseye. Still this error: `fatal: morestack on g0`.
