### ISSUE TITLE
module: using replace caused the compiler to search for non-exist go.mod

### ISSUE THREAD

**Issue by xrfang** [golang/go#41793] opened 2020-10-05 14:04 UTC
# What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.15 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xrfang/.cache/go-build"
GOENV="/home/xrfang/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/xrfang/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xrfang/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build933985160=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

In order to debug problems in my package https://github.com/xrfang/hxdump,   I used replace in the go.mod file of a project:

`module bscli

go 1.14

replace github.com/xrfang/hxdump => /home/xrfang/git/hxdump

require (
	github.com/augustoroman/hexdump v0.0.0-20190827031536-6506f4163e93
	github.com/mdp/qrterminal v1.0.1
	github.com/xrfang/go-res v1.3.0
	github.com/xrfang/hxdump v0.0.0-20201005071519-c037229348d4
	gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
)
`

### What did you expect to see?

The project should be compiled without problem.

### What did you see instead?

`go: github.com/xrfang/hxdump@v0.0.0-20201005071519-c037229348d4: parsing ../../hxdump/go.mod: open /home/xrfang/git/hxdump/go.mod: no such file or directory`

The module is cached under: `/home/xrfang/go/pkg/mod/github.com/xrfang/hxdump@v0.0.0-20201005071519-c037229348d4
`, there is no `go.mod` in that directory.

**Comment by xrfang** [comment] 2020-10-05 14:30
I have done go clean -modcache -cache -testcache, no effect whatsoever.

**Comment by bcmills** [comment] 2020-10-05 14:47
A filesystem-local `replace` directive requires a `go.mod` file at the root of the replacement directory, even if one is not normally present for that module. That is to prevent accidentally writing a `replace` for individual packages within a module, which is not a supported operation.

To make this replacement work, you can do: `(cd /home/xrfang/git/hxdump && go mod init github.com/xrfang/hxdump)`.

CC @jayconrod @matloob

**Comment by bcmills** [comment] 2020-10-05 14:49
Duplicate of #30847

**Closed by bcmills** 2020-10-05 14:49 UTC

**Comment by xrfang** [comment] 2020-10-06 01:19
@bcmills I suggest that the team consider improve the error prompt.  Instead of:

`go: github.com/xrfang/hxdump@v0.0.0-20201005071519-c037229348d4: parsing ../../hxdump/go.mod: open /home/xrfang/git/hxdump/go.mod: no such file or directory`

How about:

`go: github.com/xrfang/hxdump@v0.0.0-20201005071519-c037229348d4: missing required go.mod under /home/xrfang/git/hxdump`
