### ISSUE TITLE
I try to compress .so with upx, but the call fails after compression.

### ISSUE THREAD

**Issue by sjn939394630** [golang/go#45250] opened 2021-03-26 09:33 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
  go version go1.15.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build875379680=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I try to compress .so with upx, but the call fails after compression.

I wrote a Golang file

> func ContextTest(ctx context.Context, myStruct2 *about_struct.MyStruct){
    msg := ctx.Value("myStruct")
    fmt.Println("request:",msg, myStruct2)
}

Then build it :

> go build -buildmode=plugin -ldflags="-w -s" soMain.go

Now the generated .so file can be used directly.

Then i want to compress it with UPX
upx version `upx 3.96`
> upx -9 soMain.so

An error is reported when calling the compressed .so file.

### What did you expect to see?
I want compress the .so file size

### What did you see instead?

> fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f6108581000 pc=0x7f6108580ddf]

> runtime stack:
runtime.throw(0x4d51dc, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:726 +0x4ac

> goroutine 1 [syscall]:
runtime.cgocall(0x4b49d0, 0xc000041c28, 0xc000010010)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000041bf8 sp=0xc000041bc0 pc=0x43921b
plugin._Cfunc_pluginOpen(0xc000070000, 0xc000010010, 0x0)
	_cgo_gotypes.go:79 +0x4e fp=0xc000041c28 sp=0xc000041bf8 pc=0x4b320e
plugin.open.func1(0xc000070000, 0x1001, 0x1001, 0xc000010010, 0x770620)
	/usr/local/go/src/plugin/plugin_dlopen.go:64 +0x71 fp=0xc000041c58 sp=0xc000041c28 pc=0x4b4431
plugin.open(0x4d040c, 0x9, 0x0, 0xc00002e718, 0x4b2a0b)
	/usr/local/go/src/plugin/plugin_dlopen.go:64 +0x345 fp=0xc000041ed0 sp=0xc000041c58 pc=0x4b3685
plugin.Open(...)
	/usr/local/go/src/plugin/plugin.go:32
main.main()
	/root/go/src/go_study/go_code/about_so/main.go:12 +0x48 fp=0xc000041f88 sp=0xc000041ed0 pc=0x4b46a8
runtime.main()
	/usr/local/go/src/runtime/proc.go:204 +0x209 fp=0xc000041fe0 sp=0xc000041f88 pc=0x469989
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000041fe8 sp=0xc000041fe0 pc=0x495d41

**Comment by seankhliao** [comment] 2021-03-26 18:47
sounds like a problem with upx ?

**Comment by seankhliao** [comment] 2021-03-26 21:56
Duplicate of #42238

**Closed by seankhliao** 2021-03-26 21:56 UTC
