### ISSUE TITLE
cmd/compile: bug in string comparison

### ISSUE THREAD

**Issue by dsymonds** [golang/go#24817] opened 2018-04-12 04:57 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.10.1 (playground). This also reproduces with `go version devel +b1335037fa Wed Mar 7 22:03:43 2018 +0000 linux/amd64`.

### Does this issue reproduce with the latest release?

It does in the playground.

### What did you do?

https://play.golang.org/p/qJc3MD8uB9j

```go
package main

import (
	"fmt"
)

func main() {
	s := "123"
	const t = "123"
	fmt.Println("" < s)
	fmt.Println("" < t)
}
```

### What did you expect to see?

The two string comparisons should be the same, yielding `true` and `true`.

### What did you see instead?

```
false
true
```

**Comment by dsymonds** [comment] 2018-04-12 05:01
It's still broken at head (`go version devel +2dfb423e6e Wed Apr 11 23:46:30 2018 +0000 linux/amd64`).

**Comment by dsymonds** [comment] 2018-04-12 05:04
Oddly, it is not a commutative bug. If the empty string is on the RHS then it is fine (https://play.golang.org/p/TULS3BC_uuY).

**Comment by dsnet** [comment] 2018-04-12 05:39
Interesting regressions from Go1.8.

Root causes: https://golang.org/cl/26758

\cc @josharian @bradfitz

**Comment by josharian** [comment] 2018-04-12 14:08
Nice find!

On my phone, but I believe the offending line is:

`r := nod(cmp, nod(OLEN, ncs, nil), nodintconst(int64(len(s))))`

Unlike = and !=, the order of args here matters for > and <. Oops.

This only happens for the empty string.

The cleanest fix is probably to rewrite >, <, >=, and <= for “” into !=, false, true, and == respectively. I’ll send a CL first chance I get.

**Comment by bradfitz** [comment] 2018-04-12 14:14
Ouch. This will need some backports too.

**Comment by josharian** [comment] 2018-04-12 19:39
For the record, the affected comparisons are:

```go
"" < s
"" <= s
"" > s
"" >= s
```

**Comment by josharian** [comment] 2018-04-12 19:39
Reopening for backport.

**Comment by andybons** [comment] 2018-04-18 17:53
@josharian can you open another issue on the 1.9.6 milestone per https://golang.org/wiki/MinorReleases?

(This process is new and will be communicated more widely very soon)

**Comment by josharian** [comment] 2018-04-18 17:55
We keep going back and forth on this. So now we're opening new issues again? Is there something special I'm supposed to put in the new issue?

**Comment by bradfitz** [comment] 2018-04-18 18:00
> We keep going back and forth on this. 

Yes, sorry. We know that, though. We tried both ways and like the first more.

> So now we're opening new issues again?

Yes.

**Comment by andybons** [comment] 2018-04-18 18:00
I'm sorry for the churn in process.

Per the Wiki doc listed above:

> As soon as an interested party thinks an issue should be considered for backport, they open one or two “child” issues titled like package: title [1.9 backport]. The issue should include a link to the original issue, the CLs that need to be cherry-picked, and a short rationale about why the backport might be needed. This will soon be automated via GopherBot but for now must be done manually.

**Comment by josharian** [comment] 2018-04-18 18:14
Glad to hear it is going to be automated.

**Comment by FiloSottile** [comment] 2018-04-23 23:55
Closing this in favor of the backport issues as it was fixed in master.

**Closed by FiloSottile** 2018-04-23 23:55 UTC
Labels: NeedsFix, release-blocker
