### ISSUE TITLE
x/tools/cmd/godoc: Unnecessary empty line in type description

### ISSUE THREAD

**Issue by Thomasdezeeuw** [golang/go#9868] opened 2015-02-13 16:22 UTC
On the following page http://golang.org/pkg/sync/#Pool an unnecessary empty line is added to the code. It's probably because it contains unexported fields an a new line before the public fields, but it would be nice if this empty is not shown. The same happens in the text version of the page: http://golang.org/pkg/sync/?m=text (manual scrolling required).

Continued from https://github.com/golang/gddo/issues/243.

**Comment by parkr** [comment] 2015-02-14 01:36
This is probably a godoc problem, actually. The code looks like this:

```go
type Pool struct {
    local     unsafe.Pointer // local fixed-size per-P pool, actual type is [P]poolLocal
    localSize uintptr        // size of the local array

    // New optionally specifies a function to generate
    // a value when Get would otherwise return nil.
    // It may not be changed concurrently with calls to Get.
    New func() interface{}
}
```

Godoc strips out the non-exported fields but doesn't trim the whitespace separating them.

**Comment by Thomasdezeeuw** [comment] 2015-02-14 02:49
That is what we found in the previous issue, as mentioned in https://github.com/golang/gddo/issues/243.

**Comment by griesemer** [comment] 2015-04-01 19:39
This is a known problem and non-trivial to fix in general (sometimes we want the whitespace) with the current library support. There may be simple heuristics that might fix the problem in most cases.

This is a non-urgent issue.

**Comment by agnivade** [comment] 2018-05-31 14:42
Duplicate of https://github.com/golang/go/issues/18264. This is a go/printer issue actually. Closing this since there has been more activity on that issue.

**Closed by agnivade** 2018-05-31 14:42 UTC
