### ISSUE TITLE
proxy.golang.org: Wrong version for FileTrove

### ISSUE THREAD

**Issue by steffenfritz** [golang/go#67763] opened 2024-06-01 14:53 UTC
pkg.go.dev shows version v1.0.0-DEV-9

Expected is version v1.0.0-DEV-16

https://pkg.go.dev/github.com/steffenfritz/FileTrove
https://github.com/steffenfritz/FileTrove

I am not sure why it is not updated.

**Comment by seankhliao** [comment] 2024-06-02 10:58
Go follows semver in parsing versions: https://semver.org/
Pre-release segments need to be separated by dots, otherwise it is treated as a single string.
`DEV-9` sorts later than `DEV-16`. To follow semver, you should be using `v1.0.0-DEV.9` and `v1.0.0-DEV.16`.

Closing as this is working as intended.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Closed by seankhliao** 2024-06-02 10:58 UTC
Labels: proxy.golang.org
