### ISSUE TITLE
test2json exit status 101

### ISSUE THREAD

**Issue by MWangxj** [golang/go#32719] opened 2019-06-21 02:19 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/usr/local/gopath/bin"
GOCACHE="/Users/apple/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/usr/local/gopath"
GOPROXY="https://goproxy.io"
GORACE=""
GOROOT="/usr/local/go1.12"
GOTMPDIR="/tmp"
GOTOOLDIR="/usr/local/go1.12/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build079743697=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
package test

import (
	"errors"
	"testing"
)

func TestError(t *testing.T)  {
	t.Log(errors.New("error").Error())
}
```

### What did you expect to see?

error

### What did you see instead?

GOROOT=/usr/local/go1.12 #gosetup
GOPATH=/usr/local/gopath #gosetup
/usr/local/go1.12/bin/go test -c -i -o /private/var/folders/vs/mtk659950d7f6j2g3p7ykyrw0000gn/T/___TestError_in_chogolix_test chogolix/test #gosetup
/usr/local/go1.12/bin/go tool test2json -t /private/var/folders/vs/mtk659950d7f6j2g3p7ykyrw0000gn/T/___TestError_in_chogolix_test -test.v -test.run ^TestError$ #gosetup
test2json: exit status 101

**Comment by agnivade** [comment] 2019-06-21 17:01
I am unable to reproduce this. 

```
$cat test/ll_test.go 
package test

import (
	"errors"
	"testing"
)

func TestError(t *testing.T) {
	t.Log(errors.New("error").Error())
}
$go test -c -i -o ./testbin ./test
$go tool test2json -t ./testbin -test.v -test.run ^TestError
{"Time":"2019-06-21T22:28:21.424586909+05:30","Action":"run","Test":"TestError"}
{"Time":"2019-06-21T22:28:21.424834259+05:30","Action":"output","Test":"TestError","Output":"=== RUN   TestError\n"}
{"Time":"2019-06-21T22:28:21.424863906+05:30","Action":"output","Test":"TestError","Output":"--- PASS: TestError (0.00s)\n"}
{"Time":"2019-06-21T22:28:21.424875616+05:30","Action":"output","Test":"TestError","Output":"    ll_test.go:9: error\n"}
{"Time":"2019-06-21T22:28:21.42488488+05:30","Action":"pass","Test":"TestError","Elapsed":0}
{"Time":"2019-06-21T22:28:21.424896513+05:30","Action":"output","Output":"PASS\n"}
{"Time":"2019-06-21T22:28:21.424930015+05:30","Action":"pass","Elapsed":0.001}
```

@MWangxj - Is `test2json: exit status 101` the only output that you get when you run the command ? I would expect atleast some json lines to be printed before the error.

**Comment by MWangxj** [comment] 2019-06-28 10:04
sorry too later for this.
the new project i test will NOT reproduce 
but the older project that will reproduce
hope someone like me

**Comment by MWangxj** [comment] 2019-06-28 10:14
> I am unable to reproduce this.
> 
> ```
> $cat test/ll_test.go 
> package test
> 
> import (
> 	"errors"
> 	"testing"
> )
> 
> func TestError(t *testing.T) {
> 	t.Log(errors.New("error").Error())
> }
> $go test -c -i -o ./testbin ./test
> $go tool test2json -t ./testbin -test.v -test.run ^TestError
> {"Time":"2019-06-21T22:28:21.424586909+05:30","Action":"run","Test":"TestError"}
> {"Time":"2019-06-21T22:28:21.424834259+05:30","Action":"output","Test":"TestError","Output":"=== RUN   TestError\n"}
> {"Time":"2019-06-21T22:28:21.424863906+05:30","Action":"output","Test":"TestError","Output":"--- PASS: TestError (0.00s)\n"}
> {"Time":"2019-06-21T22:28:21.424875616+05:30","Action":"output","Test":"TestError","Output":"    ll_test.go:9: error\n"}
> {"Time":"2019-06-21T22:28:21.42488488+05:30","Action":"pass","Test":"TestError","Elapsed":0}
> {"Time":"2019-06-21T22:28:21.424896513+05:30","Action":"output","Output":"PASS\n"}
> {"Time":"2019-06-21T22:28:21.424930015+05:30","Action":"pass","Elapsed":0.001}
> ```
> 
> @MWangxj - Is `test2json: exit status 101` the only output that you get when you run the command ? I would expect atleast some json lines to be printed before the error.

today i test it print ok on my terminal

**Comment by agnivade** [comment] 2019-06-28 12:08
Thanks for getting back @MWangxj. I will close this one since you cannot reproduce this any more. Please feel free to comment on the issue if you hit this again, along with concrete steps to reproduce it.

**Closed by agnivade** 2019-06-28 12:08 UTC
Labels: WaitingForInfo
