### ISSUE TITLE
cmd/go: prioritize local git config over global git config

### ISSUE THREAD

**Issue by johnrichardrinehart** [golang/go#46889] opened 2021-06-23 14:18 UTC
`go get` for private repos can configured to use `git://` protocol repo fetches instead of `https://` if `git` is configured at the global level as follows:

```bash
git config --global url."git@github.com:".insteadOf "https://github.com/"
```

as seen in https://gist.github.com/dmitshur/6927554

However, this only seems to work with `--global`. I only want to change this behavior on a per-repository basis, prioritizing `.git/config` (local) over `~/.gitconfig` or `~/.config/git/config` (global). There seems to have been another issue related to this that was frozen and closed due to inactivity: https://github.com/golang/go/issues/19127

Is there a good reason not to support this?

**Comment by seankhliao** [comment] 2021-06-23 15:22
Assuming module mode, if you look at what go does (use `-x`), it calls git from the context of the destination module cache directories not the local workspace, meaning to support this it would have to mess with git configs.
And since the module cache is shared for the whole machine it doesn't really make sense to do it per local workspace?

**Comment by bcmills** [comment] 2021-06-23 17:20
The Go module cache stores dependencies shared among all modules. Applying local git settings would potentially pollute the global cache with local credentials. (See previously #31256.)

**Comment by bcmills** [comment] 2021-06-23 17:35
Duplicate of #31256

**Closed by bcmills** 2021-06-23 17:35 UTC
Labels: FeatureRequest, NeedsDecision

**Comment by johnrichardrinehart** [comment] 2021-06-26 10:48
Okay, that makes sense. Sorry I didn't see #31256.  Thanks for linking it!
