### ISSUE TITLE
OS X gomobile init failed

### ISSUE THREAD

**Issue by 28240885** [golang/go#16080] opened 2016-06-16 08:47 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

**go version go1.6.2 darwin/amd64**

**Xcode Command Line Tools Info**

 $ xcode-select --install
    xcode-select: error: command line tools are already installed, use "Software Update" to install updates
  
  $ xcode-select -p
  **/Applications/Xcode.app/Contents/Developer**

2. What operating system and processor architecture are you using (`go env`)?

**GOARCH="amd64"
GOBIN="/usr/local/Cellar/go/1.6.2/libexec/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bob/mnt/goMobile"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.2/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"**

3. What did you do?

  $ go get golang.org/x/mobile/cmd/gomobile
  $ gomobile init

4. What did you expect to see?

5. What did you see instead?

golang.org/x/mobile/gl
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:18:13: error: static declaration of 'glUniformMatrix2x3fv' follows non-static declaration
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:2048:21: note: previous declaration is here
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:19:13: error: static declaration of 'glUniformMatrix3x2fv' follows non-static declaration
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:2049:21: note: previous declaration is here
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:20:13: error: static declaration of 'glUniformMatrix2x4fv' follows non-static declaration
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:2050:21: note: previous declaration is here
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:21:13: error: static declaration of 'glUniformMatrix4x2fv' follows non-static declaration
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:2051:21: note: previous declaration is here
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:22:13: error: static declaration of 'glUniformMatrix3x4fv' follows non-static declaration
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:2052:21: note: previous declaration is here
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:23:13: error: static declaration of 'glUniformMatrix4x3fv' follows non-static declaration
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:2053:21: note: previous declaration is here
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:24:13: error: static declaration of 'glBlitFramebuffer' follows non-static declaration
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:2304:21: note: previous declaration is here
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:25:13: error: static declaration of 'glUniform1ui' follows non-static declaration
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:2111:21: note: previous declaration is here
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:26:13: error: static declaration of 'glUniform2ui' follows non-static declaration
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:2112:21: note: previous declaration is here
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:27:13: error: static declaration of 'glUniform3ui' follows non-static declaration
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:2113:21: note: previous declaration is here
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:28:13: error: static declaration of 'glUniform4ui' follows non-static declaration
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:2114:21: note: previous declaration is here
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:29:13: error: static declaration of 'glUniform1uiv' follows non-static declaration
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:2115:21: note: previous declaration is here
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:30:13: error: static declaration of 'glUniform2uiv' follows non-static declaration
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:2116:21: note: previous declaration is here
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:31:13: error: static declaration of 'glUniform3uiv' follows non-static declaration
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:2117:21: note: previous declaration is here
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:32:13: error: static declaration of 'glUniform4uiv' follows non-static declaration
/System/Library/Frameworks/OpenGL.framework/Headers/gl3.h:2118:21: note: previous declaration is here
/Users/bob/mnt/goMobile/src/golang.org/x/mobile/gl/work.c:37:10: warning: 4 enumeration values not handled in switch: 'glfnUniform1uiv', 'glfnUniform2uiv', 'glfnUniform3uiv'... [-Wswitch]

**Comment by adg** [comment] 2016-06-16 10:51
Dupe of #16071?

**Closed** 2016-06-16 14:29 UTC
