### ISSUE TITLE
go/doc: doc.New returns wrong type for constant declaration

### ISSUE THREAD

**Issue by adonovan** [golang/go#16153] opened 2016-06-22 19:49 UTC
`doc.New` returns incorrect type information about the constant `Y` in this program:

```
package hello
const (
    x uint8 = 255
    Y = 256
)
```

Test case: https://play.golang.org/p/-2ZQcrQgCM

The cause is this heuristic code in `(*reader).readValue`:

```
        case decl.Tok == token.CONST:
            // no type is present but we have a constant declaration;
            // use the previous type name (w/o more type information
            // we cannot handle the case of unnamed variables with
            // initializer expressions except for some trivial cases)
            name = prev
```

Enabling the `doc.AllDecls` mode bit works around the problem in this particular example because `x` is unexported.

This bug is the underlying cause of godoc.org issue 409.
https://github.com/golang/gddo/issues/409

**Comment by dmitris** [comment] 2016-06-22 22:39
I digged a bit into the code and it seems the problem is (also?) in go/exports.go and the way type propagation is done in filterSpecList.

`filterSpecList` is called here:
https://github.com/golang/go/blob/master/src/go/doc/exports.go#L229

and defined in
https://github.com/golang/go/blob/master/src/go/doc/exports.go#L196

in filterSpecList, `if specType = nil && prevType != nil `, spec.Type is set from prevType with a `copyConstType` call just returns the previous Type's Name:
https://github.com/golang/go/blob/master/src/go/doc/exports.go#L203
https://github.codm/golang/go/blob/master/src/go/doc/exports.go#L176-183

and I believe this is how we end up with incorrect type information. 

Do we need that type propagation at all in the doc package for `const`s?  Or could we simply delete this block of code:
https://github.com/golang/go/blob/master/src/go/doc/exports.go#L197-215

I modified my test package to highlight the fact that the type propagation is not related to integers:
https://godoc.org/github.com/dmitris/mytest shows now:
```
const (
    ConstBad string = 256 // max uint8 + 1

    Bar uint8 = "bar"
)
```

**Comment by josharian** [comment] 2016-06-23 00:29
Related: #5397.

The right fix for this may be to rewrite the entire package to use go/types, now that go/types is in the stdlib. That's a fair amount of work, though.

**Comment by shurcooL** [comment] 2016-06-23 01:27
> The right fix for this may be to rewrite the entire package to use go/types, now that go/types is in the stdlib.

Right now, `go/doc` has a very distinguishable property that it can work on a single package without needing to look at any of its dependencies (in fact, they could be missing completely). Would that property be preserved if it's built on top of `go/types`? Would we want to preserve it?

There are certain things that `go/doc` cannot currently do because it requires knowing about dependencies (for example, listing all methods of a type, when some of the methods are coming from an embedded type which is defined in a dependency).

**Comment by adonovan** [comment] 2016-06-23 01:55
I agree with Dmitri: this package should not use `go/types`.   It's not clear to me that `go/doc` really belongs in the standard library at all.  It is primarily a collection of utility functions common to the increasing number of tools whose name is some variation of "godoc": golang.org/x/tools/cmd/godoc, go doc, http://godoc.org, and at least two more tools within Google.

**Comment by bradfitz** [comment] 2017-06-14 05:51
Punting to Go 1.10. Sorry. Any help wanted, though.

/cc @griesemer (in case you hadn't seen this one)

**Comment by griesemer** [comment] 2017-10-05 23:54
The bug is fairly simple: A previous constant type should only be used if there's no type *and* no value in a constant declaration. The existing code ignores values.

**Closed** 2017-10-09 18:01 UTC
Labels: early-in-cycle, NeedsFix
