### ISSUE TITLE
cmd/compile: SSA 2x compile-time regression on pathological file

### ISSUE THREAD

**Issue by rasky** [golang/go#14800] opened 2016-03-13 12:07 UTC
This file:
https://gist.github.com/rasky/0b36110ba703f73e9d64

is generated by stringer in a real project, and manually modified to make it self-contained (and anonymized).

Compilation time:

```
1.6:                 3.82 real         3.78 user         0.57 sys
tip w/o checks:      8.20 real         9.73 user         1.41 sys
tip:                14.42 real        16.06 user         1.45 sys
```

**Comment by minux** [comment] 2016-03-14 03:13
It's probably because we are generating (a lot of) code to
initialize the map, however, for such cases, it's possible that
we generate static data and use a loop to initialize the map.

**Comment by tzneal** [comment] 2016-03-15 01:18
The SSA backend performs common subexpression elimination much better than older versions of go. Can you check the resulting binary size? For example, I get a 62x smaller binary with tip with your example:

version|size
------|-----
1.5.2|20M
1.6|20M
tip|320k

**Comment by rasky** [comment] 2016-03-15 23:01
Compiling with today's tip, I not only confirm tzneal's numbers, but the compile-time regression seems gone (!). It's not even faster than 1.6 for me. @tzneal would you mind double checking before I close this bug?

**Comment by bradfitz** [comment] 2016-03-15 23:04
Fixed by 11a80860ada89b5ce8fc34ee2d91f73dfa89ab7b, dup of #14781 perhaps?

**Comment by bradfitz** [comment] 2016-03-15 23:04
Or the turning off of SSA consistency checks in 5305a329d8b6?

**Comment by tzneal** [comment] 2016-03-15 23:22
The original slowdown showed up even with check disabled, and I get the same results (slightly faster than 1.6 now), but the speedup doesn't appear to be related to @josharian's change.

**Comment by josharian** [comment] 2016-03-16 00:32
Anyone want to bisect?

**Comment by cespare** [comment] 2016-03-16 00:39
I'll bisect.

**Comment by cespare** [comment] 2016-03-16 01:23
I believe that 7c18f8cdc37600637f05f1e87799cb013ee85772 is the commit in question.

That said, I can't quite reproduce the timings that others have given here. The bad case isn't as bad, and tip is slower for me than 1.6.

| commit | build time |
|-----------|--------|
| 7bc40ff (go1.6) | 3.5s |
| 368507b (parent of 7c18f8c) | 6.7s |
| 5630cb7	(tip) | 4.4s |

(These are run with `-gcflags '-ssa=1 -d=ssa/check/off'` where appropriate. Numbers are average of 5 runs.)

So tip is still roughly 25% slower than 1.6 for me. I'm on linux/amd64.

**Comment by cespare** [comment] 2016-03-16 01:46
I also looked into which commits were responsible for the size reductions.

a0232ea0dddfcc0827fd4094cbf261d85f0ae8f2 reduced the size from 20M to 320K.

3648d2d4cd5dfe20fc25ebcf391176e65c056110 gave another 50% reduction to 164K.

Good work @josharian and @skohanim!

**Comment by randall77** [comment] 2016-04-29 05:09
Ok, not quite back to parity but pretty close.  The object size is way smaller which will probably speed up the linker enough to reach parity.  I'm going to close as "fixed enough".

**Closed by randall77** 2016-04-29 05:09 UTC
