### ISSUE TITLE
make the gc public

### ISSUE THREAD

**Issue by JAicewizard** [golang/go#32203] opened 2019-05-23 14:56 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.12.4

</pre>

### What did you do?

I try to compile go code at run-time(not performance critical) and right now have to assume that the go command is available and up-to-date.

### What did you expect to see?

I was hoping that there would be some kind of way to import the gc so I can compile the code from inside the program, eliminating the go dependency.

### What did you see instead?

The gc is not exported but instead inside a /internal making it impossible to import and use in other programs/code-bases.

**Comment by randall77** [comment] 2019-05-23 15:28
What are you going to do with the compiled code? You would still need a linker to make anything useful from the result. Do you want the linker also?

Does it need to handle cgo? Then we'd need gcc bundled somehow as well.

I'm not sure we want to do this. The interface for the compiler is complicated and it's not clear we want to freeze it, as we would need to do if we made it public in the stdlib.

**Comment by JAicewizard** [comment] 2019-05-23 16:08
I'm sorry I don't 100% understand the internals of go. maybe I should replace all "compile" with "build".
so I am looking for a public interface that build a go package into a binary just like go build. looking at the internal code this seemed to be handled by the gc package but I might have been mistaken.

**Comment by AlexRouSg** [comment] 2019-05-23 16:45
Have you considered just packaging go with your program? Or check if go is installed and is at least version x.y.z and if not, download and extract it?

Why must it be compiled into your program?

**Comment by JAicewizard** [comment] 2019-05-23 16:57
It doesn't have to, but it would be nice. The current setup works, but it would be nice to have an always working setup that doesn't come with a "what if".

**Comment by AlexRouSg** [comment] 2019-05-23 17:06
Can you give specific "what ifs" or cons for the alternative solutions I described earlier that doesn't apply to a package?

**Comment by JAicewizard** [comment] 2019-05-23 17:38
I realized that it would be little use in my case, since I would still need the standard library.
But I still think that it would be really cool(I cant immediately find a use-case) to have a simple API to compile X file with access to X libraries (like /go/src but then not necessarily with stdlib).
If you want you can close this

**Comment by agnivade** [comment] 2019-05-23 18:10
Duplicate of https://github.com/golang/go/issues/15108. Feel free to subscribe to that.

**Closed by agnivade** 2019-05-23 18:10 UTC
