### ISSUE TITLE
net: DNSError doesn't properly wrap context errors in lookup.go

### ISSUE THREAD

**Issue by AdminBenni** [golang/go#63727] opened 2023-10-25 14:26 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.21.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/benedikt/.cache/go-build'
GOENV='/home/benedikt/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/benedikt/go/pkg/mod'
GONOPROXY='[NOT IMPORTANT]'
GONOSUMDB='[NOT IMPORTANT]'
GOOS='linux'
GOPATH='/home/benedikt/go'
GOPRIVATE='[NOT IMPORTANT]'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/benedikt/sdk/go1.21.0'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/benedikt/sdk/go1.21.0/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='0'
GOMOD='[NOT IMPORTANT]'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build810391928=/tmp/go-build -gno-record-gcc-switches'
</pre></details>

### What did you do?

I am using [`go-amqp`](https://github.com/Azure/go-amqp). I dial (which calls `net`'s `Dialer.DialContext`) in a goroutine and then a situation happens in the main routine which causes me to cancel while dialing.

```go
// Main routine
ctx, cancel := context.WithCancel(context.Background())
go otherRoutine(ctx)
defer cancel()
```
```go
// Other routine
conn, err := amqp.Dial(ctx, endpoint, nil)
if err != nil {
    fmt.Println(errors.Is(err, context.Canceled))
}
```

### What did you expect to see?
true

### What did you see instead?
false

### Why this is happening
In `lookupIPAddr` in [`net/lookup.go`](https://github.com/golang/go/blob/f9a31cda3c8a92e81989af4167c9ae5bfbb8ea5e/src/net/lookup.go#L348) we see the following code.
```go
err := &DNSError{
    Err:       mapErr(ctxErr).Error(),
    Name:      host,
    IsTimeout: ctxErr == context.DeadlineExceeded,
}
...
return nil, err
```
Which of converts the error into a string without wrapping it properly.
`mapErr(ctxErr)` converts the error to an instance of `canceledError`, which is defined with the following comment.
```go
// canceledError lets us return the same error string we have always
// returned, while still being Is context.Canceled.
type canceledError struct{}
```
Which means that `canceledError` is even meant to be `Is` compatible with `context.Canceled`, which is immediately thrown away by calling `.Error()`.

### Proposed solution
`DNSError` should additionally store the original error and implement `Unwrap` so that `Is` can properly work to detect the error that spawned the `DNSError`.

**Comment by seankhliao** [comment] 2023-10-25 14:36
Duplicate of #63116

**Closed by seankhliao** 2023-10-25 14:36 UTC
