### ISSUE TITLE
x/website: /VERSION endpoint returns outdated information

### ISSUE THREAD

**Issue by jimen0** [golang/go#50114] opened 2021-12-12 14:46 UTC
### What version of Go are you using (`go version`)?

N/A

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

```console
$ curl 'https://go.dev/VERSION?m=text'
go1.17.4
```

### What did you expect to see?

`go1.17.5` since the current release per go.dev/dl is 1.17.5

### What did you see instead?

`go1.17.4`

Adding my request trace just in case it helps debugging this.

```http
x-cloud-trace-context: ee059a46e3120e5832ea0c9571613f8c
date: Sun, 12 Dec 2021 14:47:46 GMT
server: Google Frontend
content-length: 8
```

**Comment by amalmurali47** [comment] 2021-12-12 14:54
I can confirm the behaviour described here.

**Comment by seankhliao** [comment] 2021-12-12 15:03
Duplicate of #42744

**Closed by seankhliao** 2021-12-12 15:03 UTC
