### ISSUE TITLE
cmd/asm: K0 register not available to AVX-512 instructions?

### ISSUE THREAD

**Issue by rsc** [golang/go#29893] opened 2019-01-23 16:09 UTC
I expected that an instruction like:

	VPSHUFB	Z1, Z8, K0, Z8

would assemble. But it does not. (asm: invalid instruction).
If I change the mask to K1 then it does.

Am I confused about what mask registers are available
in the AVX-512 instruction set, or is the assembler confused?

/cc @Quasilyte @TocarIP

**Comment by TocarIP** [comment] 2019-01-23 17:08
k0 is a zero register, and avx512 doesn't allow k0 as mask (it has the same encoding as no-mask version).
Gnu as also rejects it:
```
build$ cat a.s
vpshufb   %zmm0,%zmm0,%zmm0{%k1}  #works
vpshufb   %zmm0,%zmm0,%zmm0{%k0}
build$ as a.s
a.s: Assembler messages:
a.s:2: Error: `%k0' can't be used for write mask
```

**Comment by FiloSottile** [comment] 2019-01-23 20:14
Closing as working as intended. Reopen and retitle if you want the assembler to print a more informative error.

**Closed by FiloSottile** 2019-01-23 20:14 UTC
