### ISSUE TITLE
bug: Building with faketime tag leads to apis getting stuck

### ISSUE THREAD

**Issue by PranshuSrivastava** [golang/go#67467] opened 2024-05-17 10:56 UTC
### Go version

go1.22.3 linux/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/home/pranshu.linux/.cache/go-build'
GOENV='/home/pranshu.linux/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/pranshu.linux/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/pranshu.linux/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_arm64'
GOVCS=''
GOVERSION='go1.22.3'
GCCGO='gccgo'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build876642711=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

So i have a simple gin api that logs in the user and issues it a jwt token, which it verifies on subsequent requests. I also have a bash script which first does a post request to the api to get the jwt token, and then makes another request with the token to verify its validity.  Here is the application and the bash script for your reference

```
package main

import (
    "net/http"
    "time"
    "fmt"

    "github.com/gin-gonic/gin"
    "github.com/dgrijalva/jwt-go"
)

var jwtKey = []byte("my_secret_key")

type Credentials struct {
    Username string `json:"username"`
    Password string `json:"password"`
}

type Claims struct {
    Username string `json:"username"`
    jwt.StandardClaims
}

func main() {
    r := gin.Default()

    r.POST("/login", login)
    r.GET("/verify", verifyJWT)

    r.Run(":8080")
}

func login(c *gin.Context) {
    fmt.Println("Got in login")
    var creds Credentials
    if err := c.BindJSON(&creds); err != nil {
        c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid request"})
        return
    }

    if creds.Username != "user" || creds.Password != "password" {
        c.JSON(http.StatusUnauthorized, gin.H{"error": "Invalid credentials"})
        return
    }

    expirationTime := time.Now().Add(2 * time.Second)
    claims := &Claims{
        Username: creds.Username,
        StandardClaims: jwt.StandardClaims{
            ExpiresAt: expirationTime.Unix(),
        },
    }

    token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
    tokenString, err := token.SignedString(jwtKey)
    if err != nil {
        c.JSON(http.StatusInternalServerError, gin.H{"error": "Could not generate token"})
        return
    }

    c.JSON(http.StatusOK, gin.H{"token": tokenString})
}

func verifyJWT(c *gin.Context) {
    tokenString := c.Request.Header.Get("Authorization")
    if tokenString == "" {
        c.JSON(http.StatusUnauthorized, gin.H{"error": "Token required"})
        return
    }

    claims := &Claims{}
    token, err := jwt.ParseWithClaims(tokenString, claims, func(token *jwt.Token) (interface{}, error) {
        return jwtKey, nil
    })

    if err != nil || !token.Valid {
        c.JSON(http.StatusUnauthorized, gin.H{"error": "Invalid token"})
        return
    }

    c.JSON(http.StatusOK, gin.H{"message": "Token is valid", "username": claims.Username})
}
```

The bash script
```bash
#!/bin/bash

# Login and get the token
response=$(curl -s -X POST http://localhost:8080/login \
-H "Content-Type: application/json" \
-d '{"username": "user", "password": "password"}')

token=$(echo $response | jq -r '.token')

# Verify the token
verify_response=$(curl -s -X GET http://localhost:8080/verify \
-H "Authorization: $token")

echo "Login Response: $response"
echo "Verify Response: $verify_response"
```

### What did you see happen?

So when i built the application without the faketime tag, it worked perfectly fine and the token got validated. But when i built the application using the faketime tag and ran the bash script, it got stuck and did not receive any response from the server.

I also tried to migrate the server from gin to http to verify if it is not a gin problem, but with http as well, it got stuck and did not give out any response. 

Also, i noticed that when i built it with the faketime flag it printed extra headers(which are present in the write function in the time_fake.go file) along with every log statement. You can find the screenshot below:
<img width="780" alt="image" src="https://github.com/golang/go/assets/37413698/16b72c30-2d52-4fcb-839e-fe392c7cd677">

### What did you expect to see?

I expected the api to work correctly even with the faketime tag and validate the token every time since the time was permanently set to 2009.

**Comment by seankhliao** [comment] 2024-05-17 11:03
please show the reproducer with standard http.

**Comment by PranshuSrivastava** [comment] 2024-05-17 12:15
@seankhliao Here it is:

```
package main

import (
    "encoding/json"
    "log"
    "net/http"
    "time"

    "github.com/dgrijalva/jwt-go"
)

var jwtKey = []byte("my_secret_key")

type Credentials struct {
    Username string `json:"username"`
    Password string `json:"password"`
}

type Claims struct {
    Username string `json:"username"`
    jwt.StandardClaims
}

func main() {
    http.HandleFunc("/login", login)
    http.HandleFunc("/verify", verifyJWT)

    log.Println("Server is starting on port 8080")
    if err := http.ListenAndServe(":8080", nil); err != nil {
        log.Fatalf("Failed to start server: %v", err)
    }
}

func login(w http.ResponseWriter, r *http.Request) {
    log.Println("Login endpoint hit")

    var creds Credentials
    err := json.NewDecoder(r.Body).Decode(&creds)
    if err != nil {
        log.Println("Error decoding JSON:", err)
        http.Error(w, "Invalid request", http.StatusBadRequest)
        return
    }

    if creds.Username != "user" || creds.Password != "password" {
        log.Println("Invalid credentials")
        http.Error(w, "Invalid credentials", http.StatusUnauthorized)
        return
    }

    expirationTime := time.Now().Add(5 * time.Minute)
    claims := &Claims{
        Username: creds.Username,
        StandardClaims: jwt.StandardClaims{
            ExpiresAt: expirationTime.Unix(),
        },
    }

    token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
    tokenString, err := token.SignedString(jwtKey)
    if err != nil {
        log.Println("Error generating token:", err)
        http.Error(w, "Could not generate token", http.StatusInternalServerError)
        return
    }

    log.Println("Token generated successfully:", tokenString)
    w.Header().Set("Content-Type", "application/json")
    json.NewEncoder(w).Encode(map[string]string{"token": tokenString})
}

func verifyJWT(w http.ResponseWriter, r *http.Request) {
    log.Println("Verify endpoint hit")

    tokenString := r.Header.Get("Authorization")
    if tokenString == "" {
        log.Println("Token required")
        http.Error(w, "Token required", http.StatusUnauthorized)
        return
    }

    claims := &Claims{}
    token, err := jwt.ParseWithClaims(tokenString, claims, func(token *jwt.Token) (interface{}, error) {
        return jwtKey, nil
    })

    if err != nil || !token.Valid {
        log.Println("Invalid token:", err)
        http.Error(w, "Invalid token", http.StatusUnauthorized)
        return
    }

    log.Println("Token verified successfully for user:", claims.Username)
    w.Header().Set("Content-Type", "application/json")
    json.NewEncoder(w).Encode(map[string]string{"message": "Token is valid", "username": claims.Username})
}
```
You can use this with the same bash script

**Comment by seankhliao** [comment] 2024-05-18 11:21
If I just run your example as is, the program deadlocks with all goroutines asleep (see also #50045)
If you have some other process in the background to keep the program running, faketime will also accelerate the passage of time, so by the time you try to test it externally with your bash script, more than 5 virtual minutes will have passed.

I'm closing this as working as intended for the uses of faketime (playground).

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Closed by seankhliao** 2024-05-18 11:21 UTC
Labels: WaitingForInfo
