### ISSUE TITLE
spec: package initialization issue

### ISSUE THREAD

**Issue by Happyholic1203** [golang/go#25474] opened 2018-05-21 03:40 UTC
The following piece of code produces different result from [SPEC](https://golang.org/ref/spec#Package_initialization)

```bash
$ cat main.go
package main

import "fmt"

var (
	a = c + b
	b = f()
	c = f()
	d = 3
)

func f() int {
	d++
	return d
}

func main() {
	fmt.Println(a, b, c, d)
}
$ go run main.go
9 5 4 5
```

Following the SPEC, `b` should be initialized before `c`, so instead of `9 5 4 5`, `9 4 5 5` is expected, according to the SPEC:

> ... package-level variables are initialized in declaration order but after any of the variables they depend on.

However, if we change `a = c + b` to `a = b + c`, then `b` is initialized before `c`.

So it seems like the order of presence precedes the order of declaration, deviating the SPEC.

go version: `1.10.2 darwin/amd64`

go env:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/user/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d3/8sk_rdjx1s703xh89gb4x38h0000gn/T/go-build710804438=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by meirf** [comment] 2018-05-21 05:10
I'm able to reproduce this going as far back as go1.7 on darwin/amd64 mac os 10.13.3 (Might also reproduce on earlier go versions but haven't tried older versions yet.)

2 points of clarification on the original post:

- The intended link was probably: https://golang.org/ref/spec#Package_initialization
- The code the OP includes is almost identical to the code at that ^ link

**Comment by Happyholic1203** [comment] 2018-05-21 05:33
The above 2 points of clarification are valid, thanks.
Sorry for the wrong URL.

**Comment by bcmills** [comment] 2018-05-21 16:49
Please use playground links when posting runnable code: https://play.golang.org/p/PzHf02Fah3q

**Comment by griesemer** [comment] 2018-05-21 16:52
Duplicate of #22326.

**Closed by griesemer** 2018-05-21 16:52 UTC
Labels: NeedsInvestigation
