### ISSUE TITLE
Proposal: add a flag to `go get` to respect replace directives

### ISSUE THREAD

**Issue by firelizzard18** [golang/go#47380] opened 2021-07-25 04:34 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="linux"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVERSION="go1.16.5"
GCCGO="gccgo"
</pre></details>

### Proposal

`go get <url>` does not respect `replace` directives in the top-level `go.mod` of `<url>`. #30354 has been referenced by nearly 40 issues in other repositories, many/most of which boil down to "this doesn't build because `replace` directives aren't respected by `go get <url>`. Clearly many people expect `replace` directives in a top level module to be respected when that top-level module is fetched with `go get`. So I propose to add a flag to `go get` to enable this behavior.

**Comment by seankhliao** [comment] 2021-07-25 09:32
Duplicate of #44840

**Closed by seankhliao** 2021-07-25 09:32 UTC
Labels: Proposal
