### ISSUE TITLE
image/jpeg: failure to decode image

### ISSUE THREAD

**Issue by subinwalter** [golang/go#15641] opened 2016-05-11 12:53 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6.2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
 GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/subin/godown/:/Users/subin/gocode/:/Users/subin/gothumbs/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
encoded and decoded an image using go's image library

[image link](http://a.ctimg.net/tKgQBM-TQw2lLz2oPhPZWA/flourless-fruit-tea-cake.jpg)

4. What did you expect to see?
properly encoded jpeg image

5. What did you see instead?
the encoded image was all green

**Comment by josharian** [comment] 2016-05-11 15:04
That image link doesn't work for me. Will you double-check it? Thanks.

**Comment by ALTree** [comment] 2016-05-11 15:51
He formatted it wrong but the link actually works:

http://a.ctimg.net/tKgQBM-TQw2lLz2oPhPZWA/flourless-fruit-tea-cake.jpg

**Comment by josharian** [comment] 2016-05-11 16:00
Ah, thanks. Not a regression from 1.6 to 1.7 so marking as 1.8 for now.

cc @nigeltao

**Comment by subinwalter** [comment] 2016-05-12 04:32
hi sorry about the whole image link thing, I hope I have  provided all the info reqired

**Comment by nigeltao** [comment] 2016-05-22 06:03
This looks like it's fixed in Go tip, which will become Go1.7 in a couple of months.

I suspect that this is a duplicate of #14522.

**Closed by nigeltao** 2016-05-22 06:03 UTC
