### ISSUE TITLE
Variable escapes to the heap when passed to sync/atomic function

### ISSUE THREAD

**Issue by davecheney** [golang/go#31509] opened 2019-04-17 06:02 UTC
### What version of Go are you using (`go version`)?

<pre>
% go version
go version devel +33e5da48d5 Wed Apr 17 00:05:41 2019 +0000 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

```go
package main

import (
        "sync/atomic"
)

// counter holds an atomically incrementing counter.
type counter uint64

func (c *counter) get() uint64 {
        return atomic.LoadUint64((*uint64)(c))
}
func (c *counter) inc() uint64 {
        return atomic.AddUint64((*uint64)(c), 1)
}
func (c *counter) reset() uint64 {
        return atomic.SwapUint64((*uint64)(c), 0)
}

func f() uint64 {
        var c counter
        c.inc()
        c.get()
        return c.reset()
}

func main() {
        f()
}
```

### What did you expect to see?

`c` does not escape the scope of `f()`

### What did you see instead?

```
./counter.go:10:7: leaking param: c
./counter.go:13:7: leaking param: c
./counter.go:16:7: leaking param: c
./counter.go:21:6: moved to heap: c
./counter.go:28:3: moved to heap: c
```

**Comment by randall77** [comment] 2019-04-17 12:52
We could fix this by annotating those functions as non-escaping.

Why is this an issue, though? There's no reason to be using atomic operations on the stack. That memory is not accessible by more than one thread. If anything, maybe this issue should be "replace sync/atomic operations on stack variables with regular loads and stores"? (Kinda half joking, but the motivation here escapes me.)

Is there a library or something that is using these operations, that you want to call using the address of a stack object? It's unclear to me from your example what that might be.

**Comment by davecheney** [comment] 2019-04-17 22:02
@randall77 thanks for your reply. This was an example intended to show to myself that mid stack inlining and atomic intrinsics reduce the final output of counter.inc (for example) to a locked xaddq. The only weird thing was the call to newobject to push c onto the heap. But you're right that theres no value in using atomics on stack variables; as you highlight, the memory is not shared with another thread.

Taking a trip through `sync/atomic` and `runtime/internal/atomic` it's a sea of forwarding assembly and annotations on functions that are overridden by intrinsics. Perhaps the fix is to add no escape to the Load* variants in `runtime/internal/atomic/atomic_amd64x.go` (maybe others)?

**Comment by agnivade** [comment] 2019-04-18 04:44
Dup of https://github.com/golang/go/issues/31509 ?

**Comment by cespare** [comment] 2019-04-18 07:56
> Dup of #31509 ?

That's this one.

**Comment by randall77** [comment] 2019-04-18 12:36
The routines in runtime/internal/atomic are already marked as `noescape`. I think to fix this we'd need `noescape` annotations in `sync/atomic/doc.go`. Those are the declarations used by escape analysis when using `sync/atomic`.

I'd still like to see a real-world case where this would be worth fixing.

**Comment by rsc** [comment] 2019-04-30 17:37
Duplicate of #16241.

**Closed by rsc** 2019-04-30 17:37 UTC
Labels: WaitingForInfo
