### ISSUE TITLE
x/website: needs redeploy after Go 1.15.5 release

### ISSUE THREAD

**Issue by cwimmer** [golang/go#42752] opened 2020-11-20 18:08 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

N/A.  This is a website issue

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/cwimmer/Library/Caches/go-build"
GOENV="/Users/cwimmer/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/cwimmer/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/cwimmer/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n7/ps6rjx6539z9zwgsv3rr13v00000gn/T/go-build252434228=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

N/A this is a website issue.

### What did you do?

curl -s https://golang.org/VERSION?m=text

### What did you expect to see?

go1.15.5

### What did you see instead?

go1.15.4

**Comment by dmitshur** [comment] 2020-11-20 18:18
Thanks for reporting. The website needs to be redeployed after the Go 1.15.5 release.

CC @katiehockman.

**Comment by AlexRouSg** [comment] 2020-11-20 19:57
Dupe of #42744

@cwimmer 
https://golang.org/dl/?mode=json is the proper way to get latest version.

**Comment by katiehockman** [comment] 2020-11-20 20:02
Thanks. I will take care of that now.

**Comment by dmitshur** [comment] 2020-11-20 20:04
Given that https://golang.org/doc/devel/release.html#go1.15 was updated to include full description of Go 1.15.5, I agree this can be closed as a duplicate of #42744.

Thanks @AlexRouSg.

**Closed by dmitshur** 2020-11-20 20:04 UTC
Labels: NeedsFix
