### ISSUE TITLE
time: LoadLocation is slow

### ISSUE THREAD

**Issue by zhexuany** [golang/go#26106] opened 2018-06-28 10:10 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.10
### Does this issue reproduce with the latest release?
Just benchmark `time.LocadLocation`. 

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zhexuany/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/zhexuany/repo/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t9/s5qvdzpx3h5g58xzpm5gn8l00000gn/T/go-build785631011=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
### What did you do?
Just benchmark `LoadLocation`, you will see the result. 
### What did you expect to see?

Each `LoadLocation` should be finished in a very reasonable time. 

### What did you see instead?
Each `LoadLocation` takes about 30us. It is huge. 

@ALTree Here is the issue. 
If `go` can do some kinda cache of location, that will be better. Right now, `LoadLocation` is relatively slow.

**Comment by cznic** [comment] 2018-06-28 11:04
> Just benchmark LoadLocation, you will see the result.

Please show the numbers for your or any other machine, thanks.

**Comment by zhexuany** [comment] 2018-06-28 11:12
```
goos: darwin
goarch: amd64
BenchmarkTimeLoadLocation-8   	  100000	     16873 ns/op	    2916 B/op	      10 allocs/op
```
Above is benchmark result and snippet I used is the following 
```
package main
import (
	"archive/zip"
	"log"
	"math/rand"
	"runtime"
	"testing"
	"time"
)

func init() {
	rand.Seed(time.Now().UnixNano())
}

var locationNames = loadLocationNames()


func BenchmarkTimeLoadLocation(b *testing.B) {
	sample := prepareSample(b.N, locationNames)

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		time.LoadLocation(sample[i])
	}
}

func loadLocationNames() []string {
	zoneinfo := runtime.GOROOT() + "/lib/time/zoneinfo.zip"

	r, err := zip.OpenReader(zoneinfo)
	if err != nil {
		log.Fatalf("Could not open zoneinfo.zip for reading: path '%s' error: '%v'", zoneinfo, err)
	}
	defer r.Close()

	var locs = []string{}

	for _, f := range r.File {
		if f == nil {
			log.Fatalf("zoneinfo.zip contained nil file pointer")
		}

		if f.FileHeader.FileInfo().IsDir() {
			continue
		}

		locs = append(locs, f.Name)
	}
	return locs
}

func prepareSample(n int, data []string) []string {
	dn := len(data)
	sample := make([]string, n)
	for i := 0; i < n; i++ {
		sample[i] = data[rand.Intn(dn)]
	}

	return sample
}
```

**Comment by meirf** [comment] 2018-06-29 05:07
```
$ go test -bench=BenchmarkTimeLoadLocation -benchmem -cpuprofile=cpu.out
$ go tool pprof cpu.out
(pprof) top10 -cum
...
      flat  flat%   sum%        cum   cum%
         0     0%     0%      1.65s 73.33%  time.readFile
     1.62s 72.00% 72.00%      1.62s 72.00%  syscall.Syscall
         0     0% 72.00%      1.61s 71.56%  testing.(*B).launch
         0     0% 72.00%      1.61s 71.56%  testing.(*B).runN
         0     0% 72.00%      1.61s 71.56%  time.LoadLocation
         0     0% 72.00%      1.61s 71.56%  time.loadLocation
         0     0% 72.00%      1.61s 71.56%  time.loadTzinfo
         0     0% 72.00%      1.61s 71.56%  time.loadTzinfoFromDirOrZip
         0     0% 72.00%      1.61s 71.56%  time_test.BenchmarkTimeLoadLocation
         0     0% 72.00%      1.28s 56.89%  syscall.Read
```

This is expected based on LoadLocation's godoc. Further, even if a user doesn't read the godoc, the usage of "Load" in the function name should make the disk reading less surprising. So I think we can agree that some slowness should be expected.

> If go can do some kinda cache of location, that will be better. Right now, LoadLocation is relatively slow.

I wonder if there is a precedent in the standard library for caching some like this. If not, maybe caching should be left to the user of library since caching is a nasty business: how many entries should be cached? should the number of entries in the cache be configurable? should there be an eviction policy or should items be cached forever? etc.

**Comment by agnivade** [comment] 2018-06-29 05:54
> I agree that LoadLocation itself should not do any caching.

Well, that is what this issue is about. For reference, this came from here - https://github.com/golang/go/issues/24844#issuecomment-400947901. @zhexuany is aware that `time.LoadLocation` looks in the filesystem, and wants the results to be cached in the standard library itself.

If the decision is that `LoadLocation` should not do any caching, then I believe this can be closed as working as intended.

**Comment by zhexuany** [comment] 2018-06-29 06:08
Yes. Our solution is wrap `time.LoadLocation` into a cache policy which improve the performance. The easiest cache policy is record appeared `time.Location` into a map in current instance. Is it more easier adding cache policy into standard lib and let user decide which one to use? It is just my naive thought. Any comments are welcome.

**Comment by ianlancetaylor** [comment] 2018-06-29 13:53
Caching `time.LoadLocation` in the standard library would be an unfortunate choice for programs that want to open a bunch of locations once.  Only the program can possibly know the appropriate caching to use for locations.  Adding a bunch of caching policies into the standard library significantly complicates the API and the implementation for a very small number of programs, and we would probably still miss important use cases.  Basically, caching is simple for the program and very hard, perhaps impossible, to do satisfactorily in the standard library.  Closing this issue as working as expected.

**Closed by ianlancetaylor** 2018-06-29 13:53 UTC
Labels: NeedsInvestigation, Performance
