### ISSUE TITLE
crypto/rsa: extend EncryptOAEP to accept a different maskgen hashing as parameter

### ISSUE THREAD

**Issue by ribeiroit** [golang/go#34233] opened 2019-09-11 12:05 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12.4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
</pre></details>

### What did you do?
Tried to use the rsa.EncryptOAEP function to generate a ciphertext to be opened by an Android Keystore.

### What did you expect to see?
https://play.golang.org/p/Ms7ocbI-IE1

### What did you see instead?
https://play.golang.org/p/BSnw2Q7ngNO

**Comment by mdempsky** [comment] 2019-09-11 17:45
Awesome:

> For Android Keystore, **SHA-1 is used for the MGF1 digest**, whereas for other Android cryptographic providers, the two digests are the same.

--https://developer.android.com/guide/topics/security/cryptography#oaep-mgf1-digest [emphasis added]

It seems like the easy solution here is to add a `MGF1Hash hash.Hash` field to `OAEPOptions`, and then fall back to `EncryptOAEP`'s `hash` parameter when it's nil.

/cc @agl @FiloSottile

**Comment by mdempsky** [comment] 2019-09-11 17:55
RFC 2437 theoretically allows maskGenFunc to not even be MGF1-based. So an alternative option here would be to add a `Mask func(out, seed []byte)` field to `OAEPOptions`.

This would probably merit exposing `mgf1XOR`.

**Comment by ribeiroit** [comment] 2019-09-11 17:59
Alright! 

I'd like to suggest this hypotesis as a valid implementation, but I've read that OAEPOptions was just related to decrypt function. 

So I changed my mind and I decided to add an optional parameter at the end of the function EncryptOEAP to be not confused.

As I'm new here, my question is that should I submit a PR with the resolution, or assume that you gonna fix that.

Thanks for the answer.

**Comment by mdempsky** [comment] 2019-09-11 18:04
> I'd like to suggest this hypotesis as a valid implementation, but I've read that OAEPOptions was just related to decrypt function.

Yes, you're right. Sorry, I didn't look closely enough at the API to see how `OAEPOptions` is actually used.

I think `OAEPOptions` will probably need to be extended, but then `EncryptOAEP` and `DecryptOAEP` *also* need variants that take the additional MGF parameter (either simply the underlying hash to use with MGF1, or a substitute for MGF1 entirely).

For backwards compatibility though, we can't add parameters to existing functions.

**Comment by FiloSottile** [comment] 2019-09-11 18:14
Duplicate of #19974

**Closed by FiloSottile** 2019-09-11 18:14 UTC
