### ISSUE TITLE
cmd/go: cannot vendor protoc-gen-go if not imported in module code import

### ISSUE THREAD

**Issue by codeliger** [golang/go#31239] opened 2019-04-03 20:26 UTC
**What version of protobuf and what language are you using?**
Version: v1.3.1

**What did you do?**

`go build -mod=vendor sourcefile.go`

**What did you expect to see?**
I expected my go.mod dependency of **github.com/golang/protobuf** to be included in the vendor folder, even though it doesnt exist as an import in any of my go files because i need the packages **proto** and **protoc-gen-go** for using protoc to generate .proto files.

I should be able to include a vendored dependency thats not imported by my go source code files to allow my dockerfile to build vendored **.proto** files without pregenerating them and commiting them to a repo. The reason for this is to ensure other users of my library do not ignore the **.proto** file and just use ***.pb.go** which could possibly be out of sync with its related **.proto**. If they have to use **protoc** everytime they pull my .proto file from my package then they are guarunteed to be in sync.

**What did you see instead?**

`/home/$USER/dev/go/src/github.com/username/modulename/vendor/github.com/golang/protobuf/proto no such file or directory`

**go.mod**

```
go 1.12

require (
	github.com/confluentinc/confluent-kafka-go v0.11.6
	github.com/go-redis/redis v6.15.2+incompatible
	github.com/golang/protobuf v1.3.1 // indirect
	github.com/onsi/ginkgo v1.8.0 // indirect
	github.com/onsi/gomega v1.5.0 // indirect
	github.com/pkg/errors v0.8.1 // indirect
	github.com/username/modulename v0.0.0-20190403143051-76fe0c9dbba9
	go.uber.org/zap v1.9.1
)

module github.com/username/modulename
```

Extra information:

Including this import `github.com/golang/protobuf/protoc-gen-go` in a empty go file called `tools.go` throws a go error saying that protoc-gen-go has a main method so its a compiled tool and not a shared library.

This prevents any type of import being allowed when trynig to vendor protoc code.

When using `-mod=vendor` the `mod.go` file is completely ignored so there is not even a way to put an indirect dependency in there.

The only option is to not use vendoring, and that requires me to put my gitlab https auth credentials directly in the docker file or environment variable so i can download gitlab dependencies which is not ideal.

**Comment by andybons** [comment] 2019-04-04 17:15
@bcmills @jayconrod

**Comment by bcmills** [comment] 2019-04-04 18:55
The model for `go:generate` is that you must check in the generated source code. Per https://blog.golang.org/generate:
> if the containing package is intended for import by `go get`, once the file is generated (and tested!) it must be checked into the source code repository to be available to clients.

If you check in the generated `.proto` files, then `go mod vendor` will copy in `github.com/golang/protobuf/proto`.

To ensure that the files remain in sync, you can write a unit-test that invokes `protoc` and compares the resulting files, or have the CI system re-run `go generate` and check for diffs.

**Comment by bcmills** [comment] 2019-04-04 18:57
See also the `// +build tools` idiom described in #25922.

**Comment by bcmills** [comment] 2019-04-04 18:57
Closing as a duplicate of #25922.

**Closed by bcmills** 2019-04-04 18:57 UTC
Labels: NeedsInvestigation, modules
