### ISSUE TITLE
fmt.Errorf: wrapping nil should return nil (improvement)

### ISSUE THREAD

**Issue by dronnix** [golang/go#49658] opened 2021-11-18 14:14 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dronnix/.cache/go-build"
GOENV="/home/dronnix/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dronnix/.gvm/pkgsets/go1.17.3/global/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dronnix/.gvm/pkgsets/go1.17.3/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/dronnix/.gvm/gos/go1.17.3"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/dronnix/.gvm/gos/go1.17.3/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2958798496=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
https://play.golang.org/p/wcUukYnblno

### What did you expect to see?
Success.

### What did you see instead?
Fail.

### Proposal:
Improve fmt.Errorf() to return nil, if it is called with %w formatter and nil argument as wrapping error. It is more comprehensive and allows to use  fmt.Errorf() in return statements. I will be happy to provide a patch.

**Comment by seankhliao** [comment] 2021-11-18 14:23
Duplicate of #38193

**Closed by seankhliao** 2021-11-18 14:23 UTC
