### ISSUE TITLE
https://golang.org/doc/tutorial/call-module-code

### ISSUE THREAD

**Issue by issa-muhannad** [golang/go#46785] opened 2021-06-16 17:08 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.16.5 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

Windows 8.1 Enterprise  x64

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I was following the tutorial: Call your code from another module. I followed every step carefully but got an error after executing step 5.1. editing the example.com/hello module. I received the error after executing this command $ go mod edit -replace=example.com/greetings=../greetings.

### What did you expect to see?
the expected result in the go.mod file in the hello directory:

module example.com/hello

go 1.16

replace example.com/greetings => ../greetings

### What did you see instead?
This error in the terminal:

go mod: -replace=example: need old[@v]=new[@w] (missing =)

P.s I was able to resolve this problem and get rid of the error by manually editing the go.mod file.

after this fix the code runs as expected.

**Comment by seankhliao** [comment] 2021-06-16 17:12
Duplicate of #44924

**Closed by seankhliao** 2021-06-16 17:12 UTC

**Comment by issa-muhannad** [comment] 2021-06-16 17:41
So it seems this is still a problem in power shell.
Got it. Thanks.
