### ISSUE TITLE
cmd/go: use go.mod to define the required version of Go

### ISSUE THREAD

**Issue by Kanshiroron** [golang/go#26499] opened 2018-07-20 09:31 UTC
Hello,

Looking at the `modules` features introduced in GoLang 1.11 ([proposal](https://github.com/golang/proposal/blob/master/design/24301-versioned-go.md)), I think we are missing the ability to fix the minimum GoLang version for the module.

Best regards,

**Comment by mvdan** [comment] 2018-07-20 09:43
You mean let modules specify the minimum Go version required to build them? Or perhaps to run them too?

Would this be just a major version like `1.9`, or a full version like `1.9.2`?

**Comment by mvdan** [comment] 2018-07-20 09:45
Also note that this is somewhat possible with build tags already, such as `// +build go1.9`. You can make it so that a package doesn't build with older versions, or even that it only builds with a particular major versison of Go like 1.10. This is what GopherJS does: https://github.com/gopherjs/gopherjs/blob/master/compiler/version_check.go

**Comment by Kanshiroron** [comment] 2018-07-20 10:07
Hello @mvdan 
I can't really tell the difference between the two (build and run) as I thought we didn't need Go to run compiled software. I think it would be a good idea to be able to fix a full version just in case your project needs a fix that has been implemented in a minor version.

**Comment by Kanshiroron** [comment] 2018-07-20 10:10
That's right it would actually be the same as `// +build go1.9` but managed at the module level, so it's easier to manage.

**Comment by adelowo** [comment] 2018-07-20 11:40
Wouldn't this lead to something like a version manager ?  (ala ruby version manager ) 👎

**Comment by rajender** [comment] 2018-07-20 11:55
Looks like this is duplicate of #23969.

**Comment by mvdan** [comment] 2018-07-20 12:00
You're right @rajender, thanks for noticing.

**Closed by mvdan** 2018-07-20 12:00 UTC
Labels: FeatureRequest, NeedsDecision, modules
