### ISSUE TITLE
builders: ios builder seems to be hung or missing in action

### ISSUE THREAD

**Issue by jeremyfaller** [golang/go#49565] opened 2021-11-12 21:08 UTC
The ios builder appears to be missing in action.

Per owners, pinging

@znly

Thanks.

**Comment by dmitshur** [comment] 2021-11-12 21:18
"znly" is a GitHub organization rather than a user, so CCing it may not generate notifications. Per the builder's [README](https://github.com/golang/build/tree/master/env/corellium) the contact is Steeve Morin.

I'll close this as a duplicate of #49048.

**Closed by dmitshur** 2021-11-12 21:18 UTC
Labels: Builders, NeedsInvestigation, mobile
