### ISSUE TITLE
net: LookupIPAddr returns incorrect error message when using custom resolver 

### ISSUE THREAD

**Issue by akaroot** [golang/go#52428] opened 2022-04-19 13:41 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.18.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="darwin"

</pre></details>

### What did you do?
Resolving an unexisting domain via a custom DNS server returns an error message with the host DNS server address instead of custom. 
When I tried to resolve the domain, that exists on my local network DNS server but doesn't exist on custom (external in my case), I got the same error. That's why I assume that go correctly uses custom DNS, but when it generates a message, it ignores configured resolver server

<pre>
package main

import (
	"context"
	"fmt"
	"net"
	"time"
)

func main() {
	resolver := &net.Resolver{
		PreferGo:     true,
		StrictErrors: true,
		Dial: func(ctx context.Context, network, address string) (net.Conn, error) {
			d := net.Dialer{
				Timeout: 3 * time.Second,
			}
			return d.DialContext(ctx, "udp", "1.1.1.1:53")
		},
	}
	addrs, err := resolver.LookupIPAddr(context.Background(), "fake.domain")
	if err != nil {
		panic(err)
	}

	fmt.Println(addrs)
}
</pre>

### What did you expect to see?
panic: lookup manager.pls.pbank.com.ua on 1.1.1.1:53: no such host

### What did you see instead?
panic: lookup manager.pls.pbank.com.ua on 192.168.1.1:53: no such host

**Comment by seankhliao** [comment] 2022-04-19 14:10
Duplicate of #43703

**Closed by seankhliao** 2022-04-19 14:10 UTC
