### ISSUE TITLE
x/pkgsite: github.com/vbsw/cmdl not found

### ISSUE THREAD

**Issue by vbsw** [golang/go#44256] opened 2021-02-14 12:02 UTC
### What is the URL of the page with the issue?
 https://github.com/golang/go/issues/new?title=x/pkgsite:&body=%3C!--Please+answer+these+questions+before+submitting+your+issue.+Thanks!--%3E+###+What+is+the+URL+of+the+page+with+the+issue?+++###+What+is+your+user+agent?+%3C!--+You+can+find+your+user+agent+here:https://www.whatismybrowser.com/detect/what-is-my-user-agent--%3E+++###+Screenshot+%3C!--Please+paste+a+screenshot+of+the+page.--%3E+++###+What+did+you+do?+%3C!--If+possible,+provide+a+recipe+for+reproducing+the+error.--%3E+++###+What+did+you+expect+to+see?+++###+What+did+you+see+instead?
  
### What is your user agent?
 Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.107 Safari/537.36
 
### Screenshot
-
 
### What did you do?
I created go package "github.com/vbsw/cmdl". The file go.mod was wrong. I deleted this package on github.com and created it again.
I call in my browser the page: https://pkg.go.dev/github.com/vbsw/cmdl

### What did you expect to see?
I expect to see the documentation for my package on https://pkg.go.dev/github.com/vbsw/cmdl
Like for my other package on gitLAB, see: https://pkg.go.dev/gitlab.com/vbsw/cmdl
 
### What did you see instead?
I see the error: "github.com/vbsw/cmdl" could not be found.

**Comment by jba** [comment] 2021-02-15 13:40
The problem is that once the Go module proxy learns about a version, it will never forget it. So the v1.0.0 that the proxy has is the old one, with the wrong go.mod. Just tag the current commit `v1.0.1` or anything over v1.0.0, then `go get` it, and it should be fine.

Closing, but reopen if the problem continues.

**Closed by jba** 2021-02-15 13:40 UTC
Labels: pkgsite
