### ISSUE TITLE
UDPConn.LocalAddr() returns a net.Addr that prints like a net.UDPAddr

### ISSUE THREAD

**Issue by rcaputo** [golang/go#53132] opened 2022-05-28 23:24 UTC
The following sample program is currently also available at https://go.dev/play/p/KX6uPkxjFy_w
```go
package main

import (
	"fmt"
	"net"
)

func main() {
	udpServerAddr, err := net.ResolveUDPAddr("udp", "127.0.0.1:0")
	if err != nil {
		panic(err)
	}
	udpServer, err := net.ListenUDP("udp", udpServerAddr)
	fmt.Printf("udpServer is a %T\n", udpServer)
	localAddr := udpServer.LocalAddr()
	fmt.Printf("localAddr is a %T, value %#v, string %s\n", localAddr, localAddr, localAddr)
	//fmt.Printf("localPort is %d\n", localAddr.Port)
}
```

fmt sees localAddr as a net.UDPAddr:
```
udpServer is a *net.UDPConn
localAddr is a *net.UDPAddr, value &net.UDPAddr{IP:net.IP{0x7f, 0x0, 0x0, 0x1}, Port:46866, Zone:""}, string 127.0.0.1:46866
```

Uncommenting line 19 breaks the program because localAddr is not what fmt says:
```
./prog.go:19:44: localAddr.Port undefined (type net.Addr has no field or method Port)
```

I hesitate reporting this.  So far the String() loophole on localAddr is the only way I've found to get the real port of a UDPConn that was bound to port 0:
```go
udpServerPort := netip.MustParseAddrPort(udpServer.LocalAddr().String()).Port()
```

**Comment by seankhliao** [comment] 2022-05-28 23:33
net.Addr is an interface that could have many concrete implementations, including net.UDPAddr. There are no requirements on the String() formatting.
If you want the port, type assert it.

closing as not a bug.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Closed by seankhliao** 2022-05-28 23:33 UTC
