### ISSUE TITLE
net/netip

### ISSUE THREAD

**Issue by gaissmai** [golang/go#53899] opened 2022-07-15 08:31 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gaissmai/.cache/go-build"
GOENV="/home/gaissmai/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/gaissmai/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/gaissmai/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib64/go/1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib64/go/1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1872475051=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.18.3 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.18.3
uname -sr: Linux 5.14.21-150400.22-default
LSB Version:    n/a
Distributor ID: openSUSE
Description:    openSUSE Leap 15.4
Release:        15.4
Codename:       n/a
/lib64/libc.so.6: GNU C Library (GNU libc) stable release version 2.31 (git 0a8262a1b2).
</pre></details>

### What did you do?

https://go.dev/play/p/VcQyBOfU2sV

### What did you expect to see?

panic

### What did you see instead?

the address string is parsed without error.

but see, RFC 5952  A Recommendation for IPv6 Address Text Representation

The address with mixed ':' and '.' is only allowed/recommended for addresses with well-known prefixes, see
RFC 5952, section 5 and RFC 4291, section 2.5.5

::ffff:0: is no well-known prefix

**Comment by seankhliao** [comment] 2022-07-15 08:43
From [RFC 5952 Section 5](https://datatracker.ietf.org/doc/html/rfc5952#section-5)
> For these addresses, mixed notation is
   RECOMMENDED if the following condition is met: the address can be
   distinguished as having IPv4 addresses embedded in the lower 32 bits
   solely from the address field through the use of a well-known prefix.
   Such prefixes are defined in [[RFC4291](https://datatracker.ietf.org/doc/html/rfc4291)] and [[RFC2765](https://datatracker.ietf.org/doc/html/rfc2765)] at the time of
   this writing.  

This is read as the mixed notation is recommended for addresses known to embed ipv4.

> If it is known by some external method that a given
   prefix is used to embed IPv4, it MAY be represented as mixed
   notation.

This is read as there are no limits on what may be considered a prefix for embedding ipv4.

Closing as working as intended.

**Closed by seankhliao** 2022-07-15 08:43 UTC
