### ISSUE TITLE
cmd/go: get fails to get a package when mod file has replace in a repo that imports packages from another go module in the same repository

### ISSUE THREAD

**Issue by dayadev** [golang/go#35693] opened 2019-11-19 15:06 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.4 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

yes it does

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_4/g37z5y0j0t7dppmsyxymdsx00000gn/T/go-build977671086=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
```

api
├── apiA
│   ├── apiA.go
│   └── go.mod
└── lib
    ├── go.mod
    └── lib.go
```
Here is my mod file contents

apiA mod contents
```

module api/apiA

replace api/lib => ../lib

require (
    github.com/fatih/structs v1.1.0 // indirect
    github.com/grpc-ecosystem/go-grpc-middleware v1.1.0 // indirect
    github.com/sirupsen/logrus v1.4.2
    api/lib v0.0.0-00010101000000-000000000000 // indirect
)
```
In the above mod file last line the the `require api v0.0.0-00010101000000-000000000000 `is actually generated for the module in lib directory

Everything works fine as the code builds and runs fine but when I try to get a package from github with

`go get github.com/spf13/viper@v1.5.0
`

### What did you expect to see?

expected to get the package and add it to go.mod file

### What did you see instead?

It throws below error

`go: malformed module path "api/lib": missing dot in first path element`

api/lib is referring to my module in lib directory and not sure why its making an http call to get api/lib though I used replace

**Comment by seankhliao** [comment] 2019-11-19 16:31
shouldn't the replacement path be `../lib`?

**Comment by dayadev** [comment] 2019-11-19 16:36
> shouldn't the replacement path be `../lib`?

Sure. Even if its so, that is not solving the issue that I am having

**Comment by seankhliao** [comment] 2019-11-19 16:51
based on the information you gave, your current setup (ignoring the go get) won't build because your replace points to some nonexistent directory

if you fix the replace it will build and will go get properly (reason being it needs the entire dependency tree for version selection)

**Comment by dayadev** [comment] 2019-11-19 16:54
> based on the information you gave, your current setup (ignoring the go get) won't build because your replace points to some nonexistent directory
> 
> if you fix the replace it will build and will go get properly (reason being it needs the entire dependency tree for version selection)

May I know why api/lib is  non existent directory ?

**Comment by seankhliao** [comment] 2019-11-19 16:58
your replace is `../api/lib` so go up from `api/libA` into `api`, go down into `api/api`, then down again into `api/api/lib` which doesn't exist in the directory structure you showed

**Comment by tmthrgd** [comment] 2019-11-19 17:03
This seems like a duplicate of #35273.

**Comment by dayadev** [comment] 2019-11-19 17:10
> your replace is `../api/lib` so go up from `api/libA` into `api`, go down into `api/api`, then down again into `api/api/lib` which doesn't exist in the directory structure you showed

Ah. I had to create an example as I cannot give away the structure I am actually using. but my local structure builds fine and go get fails at the last line of require section of go.mod

**Comment by toothrot** [comment] 2019-11-22 17:52
Hi @dayadev,

This sounds similar to #35273. What does the require statement in `api/apiA.go`? What does the package declaration at the top of `lib/lib.go` look like?

**Closed** 2019-12-22 18:04 UTC
Labels: NeedsInvestigation, WaitingForInfo
