### ISSUE TITLE
Standard MIDI library

### ISSUE THREAD

**Issue by mcandre** [golang/go#47860] opened 2021-08-21 00:30 UTC
Can we please get a standard API for MIDI operations? There are various libraries online, but they tend to focus on supporting just one or two platforms. Here is an opportunity for Go to provide a portable API.

Note that audio is broken out of the box in WSL. Some users are implementing intensive steps to work around this. Perhaps the `midi` library can report any runtime initialization errors, so that it works reasonably well, regardless of the user environment.

Citing good work so far for macOS and Linux targets:

https://gitlab.com/gomidi/midi

**Comment by ianlancetaylor** [comment] 2021-08-21 01:46
This is not something that is likely to go into the Go standard library, at least not any time soon.  This is something where we would normally expect third parties to take the lead.  https://golang.org/doc/faq#x_in_std

**Comment by zephyrtronium** [comment] 2021-08-21 01:58
Related: #18497

**Comment by mdlayher** [comment] 2021-08-21 14:56
I think it's reasonable to call this a duplicate of the above, so closing.

**Closed by mdlayher** 2021-08-21 14:56 UTC
