### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by dilei** [golang/go#51742] opened 2022-03-17 04:02 UTC
### What is the URL of the page with the issue?
 
 https://go.dev/doc/tutorial/workspaces
 
### Screenshot
 

 
 
![image](https://user-images.githubusercontent.com/6829655/158734536-e15a05ab-559b-4063-9713-0b35ce4734e3.png)

 
### What did you do?
 

 
 There are misspellings
 
### What did you expect to see?
 `go run example.com/hello`
 
 
### What did you see instead?

`go run example/hello`

**Comment by seankhliao** [comment] 2022-03-17 08:38
Duplicate of #51716

**Closed by seankhliao** 2022-03-17 08:38 UTC

**Comment by seankhliao** [comment] 2022-03-17 16:19
sorry, wrong copy/paste
