### ISSUE TITLE
x/build/cmd/release: Go 1.14 on macOS 10.11 emits "ld: warning: object file was built for newer OSX version (10.12) than being linked (10.11)"

### ISSUE THREAD

**Issue by einthusan** [golang/go#43546] opened 2021-01-06 17:07 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
This is the latest support for my OS `MacOSX 10.11.6 El Captain`

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/usr/local/gopath/bin"
GOCACHE="/Users/einthusan/Library/Caches/go-build"
GOENV="/Users/einthusan/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="github.com/paper"
GONOSUMDB="github.com/paper"
GOOS="darwin"
GOPATH="/usr/local/gopath"
GOPRIVATE="github.com/paper"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS=""
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cj/ymv0b8js49l90hc7v5txjqg80000gn/T/go-build172560090=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

go get Ebiten (2D Game Engine for Go) and run any of the examples.
```
go get github.com/hajimehoshi/ebiten
cd /usr/local/gopath/src/github.com/hajimehoshi/ebiten/examples/animation
go run main.go 
```
Additionally: I also tried my luck a second time with the flag `CGO_CFLAGS="-mmacosx-version-min=10.11"` but that didn't help either.

### What did you expect to see?

Game run as intended without any warning messages on terminal.

### What did you see instead?

Game did run as intended. But .... got the following messages on terminal.
```
# github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
# github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
# github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
ca.m:66:11: warning: instance method '-setMaximumDrawableCount:' not found (return type defaults to 'id') [-Wobjc-method-access]
/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:44:12: note: receiver is instance of class declared here
ca.m:85:35: warning: instance method '-setDisplaySyncEnabled:' not found (return type defaults to 'id') [-Wobjc-method-access]
/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:44:12: note: receiver is instance of class declared here
# github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal/ca
warning: unknown warning option '-Wno-unguarded-availability-new'; did you mean '-Wno-partial-availability'? [-Wunknown-warning-option]
# command-line-arguments
ld: warning: object file (/var/folders/cj/ymv0b8js49l90hc7v5txjqg80000gn/T/go-link-073558009/000014.o) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (/var/folders/cj/ymv0b8js49l90hc7v5txjqg80000gn/T/go-link-073558009/000015.o) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (/var/folders/cj/ymv0b8js49l90hc7v5txjqg80000gn/T/go-link-073558009/000016.o) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (/var/folders/cj/ymv0b8js49l90hc7v5txjqg80000gn/T/go-link-073558009/000017.o) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (/var/folders/cj/ymv0b8js49l90hc7v5txjqg80000gn/T/go-link-073558009/000018.o) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (/var/folders/cj/ymv0b8js49l90hc7v5txjqg80000gn/T/go-link-073558009/000037.o) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (/var/folders/cj/ymv0b8js49l90hc7v5txjqg80000gn/T/go-link-073558009/000038.o) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (/var/folders/cj/ymv0b8js49l90hc7v5txjqg80000gn/T/go-link-073558009/000039.o) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (/var/folders/cj/ymv0b8js49l90hc7v5txjqg80000gn/T/go-link-073558009/000040.o) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (/var/folders/cj/ymv0b8js49l90hc7v5txjqg80000gn/T/go-link-073558009/000041.o) was built for newer OSX version (10.12) than being linked (10.11)
ld: warning: object file (/var/folders/cj/ymv0b8js49l90hc7v5txjqg80000gn/T/go-link-073558009/000042.o) was built for newer OSX version (10.12) than being linked (10.11)
```

FYI: I had also mentioned this initially in this issue. I was asked to open a new issue.
https://github.com/golang/go/issues/36025

Edit: I managed to prevent these warnings from showing when I used a build flag to bypass "Metal" on OSX and use OpenGL. e.g. `go build -tags=ebitengl main.go`

**Comment by dmitshur** [comment] 2021-01-06 17:54
Thanks for reporting. To confirm, are those warnings reproducible for you, meaning they are emitted for each separate build operation?

As I said in https://github.com/golang/go/issues/36025#issuecomment-755412523, Go 1.14 should support macOS 10.11, so this is unexpected, and understanding why this happens can help us ensure it doesn't happen in future versions too.

CC @golang/release.

**Comment by einthusan** [comment] 2021-01-07 11:47
@dmitshur its definitely reproducible for every single build operation. As dependable as the sun! 😄

**Comment by Neal** [comment] 2021-01-11 03:49
I am experiencing the same issue as well and is reproducible for each build.

**Comment by dmitshur** [comment] 2021-01-21 23:00
@Neal The original issue was about Go 1.14 on macOS 10.11.6 El Captain. It looks like what you're running into may be similar or the same issue, but it's hard to be sure without more information. Can you please file a new issue and provide more information for how to reproduce it and include your `go env` input? I tried to reproduce it on macOS 11.1 (although with Go 1.16 beta) and 10.15, and couldn't reproduce it so far (CC @cagedmantis FYI, in case maybe you're able to reproduce it).

If it turns out it's the same issue, we can join them, but for now let's keep this issue focused on the original report. Thanks.

**Comment by soul-key** [comment] 2021-12-06 14:32
可以尝试删除gocache 目录下的东西（有些扩展是使用低版本构建的）
rm -rf   "gocache path"
通过 go env  可以获得gocache 的具体目录

**Comment by dmitshur** [comment] 2021-12-06 16:15
We haven't been able to find a way to reproduce this, and by now, Go 1.14 is unsupported, so I'll close this issue. If this problem occurs on supported releases of Go (1.17 and 1.16 at this time), please file a new bug report and provide detail. Thanks.

For asking questions, see https://go.dev/wiki/Questions.

**Closed by dmitshur** 2021-12-06 16:15 UTC
Labels: OS-Darwin, Builders, NeedsInvestigation

**Comment by lxytSL** [comment] 2021-12-09 08:14
Our problem is similar, but my **go test** only appears, and it appears again and again
