### ISSUE TITLE
spec: clarify redeclaration of result variables

### ISSUE THREAD

**Issue by jacobsa** [golang/go#9837] opened 2015-02-11 04:27 UTC
In the section on [short variable declarations][short-decls], the spec says:

> a short variable declaration may redeclare variables provided they were originally declared earlier in the same block with the same type

[Blocks][block] are defined as sequences of declarations and statements within matching brace brackets. Therefore my reading is that short variable declarations in a function body are _not_ in the same block as the declaration of result variables, although they are explicitly in the [scope][] of the latter.

But this program demonstrates that short variable declarations allow for assignment to result variables (i.e. redeclaring them) without introducing a new variable:

```Go
package main

import (
  "errors"
  "fmt"
) 

// Always returns an error.
func g() (interface{}, error) {
  return nil, errors.New("blah")
}

func f() (err error) {
  // Is 'err' new here, or does it assign to the result variable?
  foo, err := g()
  if err != nil {
    return err
  } 
  
  fmt.Println("Shouldn't get here. foo:", foo)
  return
} 

func main() {
  fmt.Println("Result:", f())
} 
```

The output on my system:

    % go version
    go version go1.4.1 darwin/amd64
    % go run *.go
    Result: blah

I imagine this is intended behavior. Perhaps the spec should be updated to specify that variables are redeclared if they were declared in an enclosing scope (not crossing the function body boundary?) rather than in an enclosing block.

[short-decls]: http://golang.org/ref/spec#Short_variable_declarations
[block]: http://golang.org/ref/spec#Blocks
[scope]: http://golang.org/ref/spec#Declarations_and_scope

**Comment by griesemer** [comment] 2015-02-11 05:12
It is indeed intended behavior.

But point taken - the spec does indeed talk about blocks here rather than scopes, and strictly speaking that is imprecise.

**Comment by jacobsa** [comment] 2015-02-11 22:10
To be clear, I'm not just trying to nitpick here. :-) I wasn't sure whether redeclaration was supposed to work in this context (I wanted it to, but needed to confirm). So I read the spec to find out, and got the wrong answer.

**Comment by griesemer** [comment] 2015-02-11 23:35
@jacobsa np - we do want to spec to be very clear w/o being pedantic, and in this case it can be misread so it should be fixed

**Closed** 2015-08-05 17:01 UTC
