### ISSUE TITLE
Nasty lack of compilation errors for http.Handler, http.HandlerFunc

### ISSUE THREAD

**Issue by ORESoftware** [golang/go#29354] opened 2018-12-20 06:34 UTC
##### What version of Go are you using (`go version`)?
go version go1.10.4 linux/amd64

#### Problem 
http.Handler / http.HandlerFunc types need be differentiated - things are compiling which shouldn't compile.

Say we have this func:

```golang
func AuthMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		next.ServeHTTP(w, r)
	})
}
```

the above will compile. _But so will this_:

```golang
func AuthMiddleware(next http.Handler) http.HandlerFunc {   // >>> HandlerFunc instead of Handler
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		next.ServeHTTP(w, r)
	})
}
```

_and so will this:_

```golang
func AuthMiddleware(next http.Handler) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {  // >>> did not wrap with http.HandlerFunc
		next.ServeHTTP(w, r)
	}
}
```

the problem is at runtime these 3 behave *very* differently, my question is - do people see this as a problem and can it be rectified. I am getting all sorts of runtime errors by accidentally mixing these 3 things and it's driving me a little insane.

**Comment by jimmyfrasche** [comment] 2018-12-20 07:14
Values of `http.HandlerFunc` satisfy the `http.Handler` interface, which is why the first example works.

The underlying type of `http.HandlerFunc` is `func(w http.ResponseWriter, r *http.Request)`. This is why examples 2 and 3 are equivalent.

You can write these examples with just variable assignment, which makes what's happening a bit clearer: https://play.golang.org/p/lGypXvNemVK

As for `http.HandlerFunc` and `http.Handler` behaving differently, the very short definition of `HandlerFunc` may enlighten: https://golang.org/src/net/http/server.go?s=59707:59754#L1950

It can be a bit confusing at first since there's quite a few concepts in the language at play simultaneously, but this is all working as intended, so I'm closing.

If you have thoughts about how the package should change in the future, #5465 is where that discussion is taking place.

**Closed by jimmyfrasche** 2018-12-20 07:14 UTC
