### ISSUE TITLE
Feature Request: Make 'go fmt' better by formatting function arguments as well

### ISSUE THREAD

**Issue by lansana** [golang/go#24261] opened 2018-03-05 23:59 UTC
When I run `go fmt <options>`, it would be nice if it formatted function arguments.

For example, here is an unformatted piece of code:

```go
type authService struct {
	Logger logger.ILogger
	Transactor repository.ITransactor
	UserRepository repository.IUserRepository
	PasswordRepository repository.IPasswordRepository
	UserPasswordRepository repository.IUserPasswordRepository
	TokenRepository repository.ITokenRepository
	UserTokenRepository repository.IUserTokenRepository
}

func NewAuthService(
	logger logger.ILogger,
	transactor repository.ITransactor,
	userRepo repository.IUserRepository,
	passwordRepo repository.IPasswordRepository,
	tokenRepo repository.ITokenRepository,
	userPasswordRepo repository.IUserPasswordRepository,
	userTokenRepo repository.IUserTokenRepository,
) IAuthService {
	return &authService{
		Logger: logger,
		Transactor: transactor,
		UserRepository: userRepo,
		PasswordRepository: passwordRepo,
		TokenRepository:  tokenRepo,
		UserPasswordRepository: userPasswordRepo,
		UserTokenRepository: userTokenRepo,
	}
}
```

When I go `go fmt`, it looks like this:

```go
type authService struct {
	Logger                 logger.ILogger
	Transactor             repository.ITransactor
	UserRepository         repository.IUserRepository
	PasswordRepository     repository.IPasswordRepository
	UserPasswordRepository repository.IUserPasswordRepository
	TokenRepository        repository.ITokenRepository
	UserTokenRepository    repository.IUserTokenRepository
}

func NewAuthService(
	logger logger.ILogger,
	transactor repository.ITransactor,
	userRepo repository.IUserRepository,
	passwordRepo repository.IPasswordRepository,
	tokenRepo repository.ITokenRepository,
	userPasswordRepo repository.IUserPasswordRepository,
	userTokenRepo repository.IUserTokenRepository,
) IAuthService {
	return &authService{
		Logger:                 logger,
		Transactor:             transactor,
		UserRepository:         userRepo,
		PasswordRepository:     passwordRepo,
		TokenRepository:        tokenRepo,
		UserPasswordRepository: userPasswordRepo,
		UserTokenRepository:    userTokenRepo,
	}
}
```

It would be nice if it could look like this:

```go
type authService struct {
	Logger                 logger.ILogger
	Transactor             repository.ITransactor
	UserRepository         repository.IUserRepository
	PasswordRepository     repository.IPasswordRepository
	UserPasswordRepository repository.IUserPasswordRepository
	TokenRepository        repository.ITokenRepository
	UserTokenRepository    repository.IUserTokenRepository
}

func NewAuthService(
	logger              logger.ILogger,
	transactor          repository.ITransactor,
	userRepo            repository.IUserRepository,
	passwordRepo        repository.IPasswordRepository,
	tokenRepo           repository.ITokenRepository,
	userPasswordRepo    repository.IUserPasswordRepository,
	userTokenRepo       repository.IUserTokenRepository,
) IAuthService {
	return &authService{
		Logger:                 logger,
		Transactor:             transactor,
		UserRepository:         userRepo,
		PasswordRepository:     passwordRepo,
		TokenRepository:        tokenRepo,
		UserPasswordRepository: userPasswordRepo,
		UserTokenRepository:    userTokenRepo,
	}
}
```

The difference is that in the last example, the `NewAuthService` arguments are aligned like vertically everything else.

I'd be happy to implement this if someone could lead me in the right direction (never coded in this codebase before).

**Comment by bradfitz** [comment] 2018-03-06 00:02
Sorry, gofmt is not soliciting change requests on its format at this time. Gofmt made a set of choices at one point, and everybody agrees to live with them, even if everybody might take issue with different individual choices. (as Rob says: https://www.youtube.com/watch?v=PAAkCSZUG1c&t=8m43s) For Go 2, @griesemer may trawl through the issue tracker for all old gofmt style request bugs.

Also I think this might be a duplicate of #24191

**Closed by bradfitz** 2018-03-06 00:02 UTC
