### ISSUE TITLE
Panic after runing

### ISSUE THREAD

**Issue by TSleepingCat** [golang/go#18620] opened 2017-01-11 21:43 UTC
# go version 
go1.7.4 windows/amd64
# go env:
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=
set GORACE=
set GOROOT=C:\Software\Go
set GOTOOLDIR=C:\Software\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
# Issue
a panic after `go run`:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x4010d0]

goroutine 1 [running]:
panic(0x4da280, 0xc04200a090)
        C:/Software/Go/src/runtime/panic.go:500 +0x1af
main.main()
        C:/Users/User/Desktop/Go/sockets/sockets.go:18 +0x90
exit status 2
```
# code
```
package main

import(
  "fmt"
  "net"
  "bufio"
)


const(
  socketAddress = "localhost"
  socketPort = "8303"
)

func main(){
  //Accept connections
  ln, _ := net.Listen("udp", "8303")
  conn, _ := ln.Accept()
  //Loop
  for{
    message, _ := bufio.NewReader(conn).ReadString('\n')
    fmt.Print(string(message))
  }
}
```

**Comment by davecheney** [comment] 2017-01-11 21:50
Check your errors, your listen call failed because you are missing a colon.

I'm going to close this as it is not a bug in Go.

**Closed by davecheney** 2017-01-11 21:50 UTC
