### ISSUE TITLE
x/crypto/ssh: session remains open if Close is called without sending data

### ISSUE THREAD

**Issue by ciys** [golang/go#31401] opened 2019-04-11 03:30 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.11.2
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
linux centos and windows
</pre></details>

### What did you do?
I create a new ssh client,dial and run is ok,but when i close the client i got the EOF error.
I set the debugMux is true to log the ssh detail and found that the server always send the `msgChannelClose` msg after the commond is successly run.
But the client only set `sentClose` true,not do anything.So when i call the close method it result an EOF error,but the client didnot send close msg to the server.And use the linux commond 

> lsof -c  process name

the ssh connection is still alive. It results after a long time ,my process cannot open any file because of "too many files".
I tried to notes the code `if ch.sentClose {
		ch.writeMu.Unlock()
		return io.EOF
	}`,and it can work.

### What did you expect to see?
Is that a bug?

**Comment by agnivade** [comment] 2019-04-11 04:00
@hanwen

**Comment by bcmills** [comment] 2019-04-11 21:44
> I create a new ssh client

How? (If you're having a problem with a specific package, please provide specific steps that we can follow exactly to reproduce the problem with that package.)

**Comment by ciys** [comment] 2019-04-12 01:08
@bcmills ，ok，like this:
```golang
import (
	"golang.org/x/crypto/ssh"
	"time"
	"net"
	"fmt"
)

func main() {
	sess, err := Sshconnect("xxx", "xxx", "170.0.44.1", 22, 10)
	fmt.Println("open :", err)
	err = sess.Run("pwd")
	fmt.Println("run :", err)
	err = sess.Close()
	fmt.Println("close :", err)
	time.Sleep(time.Minute)
}

func Sshconnect(user, password, host string, port int, timeout int) (*ssh.Session, error) {
	var (
		auth         []ssh.AuthMethod
		addr         string
		clientConfig *ssh.ClientConfig
		client       *ssh.Client
		session      *ssh.Session
		err          error
	)
	auth = make([]ssh.AuthMethod, 0)
	auth = append(auth, ssh.Password(password))
	clientConfig = &ssh.ClientConfig{
		User:    user,
		Auth:    auth,
		Timeout: time.Duration(timeout) * time.Second,
		HostKeyCallback: func(hostname string, remote net.Addr, key ssh.PublicKey) error {
			return nil
		},
	}
	// connet to ssh
	addr = fmt.Sprintf("%s:%d", host, port)
	if client, err = ssh.Dial("tcp", addr, clientConfig); err != nil {
		return nil, err
	}
	// create session
	if session, err = client.NewSession(); err != nil {
		return nil, err
	}
	return session, nil
}

**Comment by wiml** [comment] 2019-07-18 01:54
I think that this is probably not a bug, but is tangentially related to #32453 etc.

The error is returned because the session has already been closed (by `Run()`). The SSH connection leaks because it is never closed — the `client` object returned from `Dial()` is discarded, but *that's* the object that needs to be closed to clean up the underlying TCP connection.

(As an aside, this seems to be a subtle API to use correctly. The session can be closed asynchronously at any time by the other side, and so it's always possible for correctly-written code to get an `EOF` from `Close()`.)

For reference, turning on the `debugMux` prints:

```
2019/07/17 18:31:04 decoding(1): data packet - 21 bytes
2019/07/17 18:31:04 send(1): ssh.windowAdjustMsg{PeersID:0x0, AdditionalBytes:0xc}
2019/07/17 18:31:04 decoding(1): 96 &ssh.channelEOFMsg{PeersID:0x1} - 5 bytes
2019/07/17 18:31:04 decoding(1): 98 &ssh.channelRequestMsg{PeersID:0x1, Request:"exit-status", WantReply:false, RequestSpecificData:[]uint8{0x0, 0x0, 0x0, 0x0}} - 25 bytes
2019/07/17 18:31:04 decoding(1): 97 &ssh.channelCloseMsg{PeersID:0x1} - 5 bytes
2019/07/17 18:31:04 send(1): ssh.channelCloseMsg{PeersID:0x0}
run : <nil>
2019/07/17 18:31:04 send(1): ssh.channelCloseMsg{PeersID:0x0}
close : EOF
```

**Comment by ciys** [comment] 2019-08-12 07:23
@wiml yes，you are right. I tried to close the client not session, and there is no connection leak.Thank you for your reply!

**Closed** 2019-08-13 03:10 UTC
Labels: NeedsInvestigation
