### ISSUE TITLE
Multiple slice dimensions from a single make() call.

### ISSUE THREAD

**Issue by AnvilDev** [golang/go#24878] opened 2018-04-16 03:09 UTC
Why can't we declare the multiple dimensions of a multi-dimensional slice from a single make() call?

Isn't `squareMatrix := make([][]int, n, n)` far simpler than
```go
squareMatrix := make([][]int, n)
for row := range squareMatrix {
    squareMatrix[row] = make([]int, n)
}
```

Is there some underlying reason as to why this isn't done?

**Comment by agnivade** [comment] 2018-04-16 03:28
Hi,

This appears to be a question rather than a Go bug. We do not use the issue tracker for general discussions or questions like these.

You might want to take a look at 
- https://github.com/golang/go/issues/6282  
- https://golang.org/doc/effective_go.html#two_dimensional_slices

For further questions, please have a look at [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.

Closing since this is not a bug.

**Closed by agnivade** 2018-04-16 03:28 UTC
