### ISSUE TITLE
x/build: cmd/cl does not build

### ISSUE THREAD

**Issue by adams-sarah** [golang/go#21924] opened 2017-09-18 20:21 UTC
golang.org/x/build/cmd/cl does not build, as its import "golang.org/x/build/godash" does not exist.

remove it?

cc @bradfitz @andybons @quentinmit

**Comment by andybons** [comment] 2017-09-18 20:24
Dupe of #21216 

Someone is working on fixing it.

**Closed by andybons** 2017-09-18 20:24 UTC
Labels: Builders
