### ISSUE TITLE
x/tools/go/analysis/analysistest: problem with Requires and structtag.Analyzer

### ISSUE THREAD

**Issue by ccoVeille** [golang/go#52973] opened 2022-05-18 15:35 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.18.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes, I also tested in a docker instance with 1.18.2

<pre>
root@8fd7dc46af41:/wd# go version
go version go1.18.2 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/wd/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2693414172=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I worked on a branch available here

https://github.com/ccoVeille/tagliatelle/blob/golang-issue/

I'm trying to use an analyzer that requires on `structtag.Analyzer` to be validated
https://github.com/ccoVeille/tagliatelle/blob/golang-issue/tagliatelle.go

```go
func New(config Config) *analysis.Analyzer {
	return &analysis.Analyzer{
		Name: "tagliatelle",
		Doc:  "Checks the struct tags.",
		Run: func(pass *analysis.Pass) (interface{}, error) {
			// uncomment structAnalyser.Run to fix the issue
			// but we shouldn't call it here, as structtag.Analyzer is in the Requires
			// I checked Requires was run and found the issue, the issue is simply not reported
			//_, _ = structtag.Analyzer.Run(pass)

			if len(config.Rules) == 0 {
				return nil, nil
			}

			return run(pass, config)
		},
		Requires: []*analysis.Analyzer{
			structtag.Analyzer,
			inspect.Analyzer,
		},
	}
}
```
I'm launching the code via go test -v ./...

I added this to the tests 

https://github.com/ccoVeille/tagliatelle/blob/golang-issue/testdata/src/a/sample.go#L43-L52=

It's a struct that is not compatible with `reflect.StructTag`, I added to my testdata file, because I want to be able to detect such issue

```go
type MessedUpTags struct {
	// an invalid tag listed in the rule is supported.
	Bad string `json:"bad` // want "struct field tag `json:\"bad` not compatible with reflect.StructTag.Get: bad syntax for struct tag value"

	// an invalid tag not in the rule is supported.
	Whatever string `foo:whatever` // want "struct field tag `foo:whatever` not compatible with reflect.StructTag.Get: bad syntax for struct tag value"

	// a invalid tag supported by the rule, is not hidden by another broken tag
	Mixed string `json:"mixed" foo:mixed` // want "struct field tag `json:\"mixed\" foo:mixed` not compatible with reflect.StructTag.Get: bad syntax for struct tag value"
}
```

I expect the `Requires` code to stop the code and execution, but also to print the errors.

I checked the `structtag.Analyzer` is launch and report the issue, the issues are reported, so appended to a.diagnosis

https://cs.opensource.google/go/x/tools/+/master:go/analysis/internal/checker/checker.go;l=684?q=ImportObjectFact&ss=go%2Fx%2Ftools

But then, they are not available.

I tried to edit the golang code locally, but failed to find a solution, I think it's a bug.

I also checked I'm using the latest version go tools
https://github.com/ccoVeille/tagliatelle/blob/golang-issue/go.mod#L7=

### What did you expect to see?

I'm expecting the code to print the error returned by the `structtag.Analyzer`

<pre>
$ go test -v ./...
root@8fd7dc46af41:/wd# go test -v ./...
=== RUN   TestAnalyzer
    analysistest.go:512: a/sample.go:45: no diagnostic was reported matching "struct field tag `json:\"bad` not compatible with reflect.StructTag.Get: bad syntax for struct tag value"
    analysistest.go:512: a/sample.go:48: no diagnostic was reported matching "struct field tag `foo:whatever` not compatible with reflect.StructTag.Get: bad syntax for struct tag value"
    analysistest.go:512: a/sample.go:51: no diagnostic was reported matching "struct field tag `json:\"mixed\" foo:mixed` not compatible with reflect.StructTag.Get: bad syntax for struct tag value"
--- FAIL: TestAnalyzer (0.01s)
FAIL
FAIL	github.com/ldez/tagliatelle	0.014s
?   	github.com/ldez/tagliatelle/cmd/tagliatelle	[no test files]
FAIL
</pre>

### What did you see instead?

<pre>
root@8fd7dc46af41:/wd# go test -v ./...
=== RUN   TestAnalyzer
--- PASS: TestAnalyzer (0.01s)
PASS
ok  	github.com/ldez/tagliatelle	0.015s
?   	github.com/ldez/tagliatelle/cmd/tagliatelle	[no test files]
</pre>

**Comment by timothy-king** [comment] 2022-05-18 16:43
I believe this is a case of only root actions `(Analyzer, Package)` being reported. I am not seeing good documentation that this is the intended behavior but analysis is quite consistent about this:
  * https://cs.opensource.google/go/x/tools/+/master:go/analysis/internal/checker/checker.go;l=216 (this is what your test is doing)
  * https://cs.opensource.google/go/x/tools/+/master:go/analysis/internal/checker/checker.go;l=465
  * https://cs.opensource.google/go/x/tools/+/master:go/analysis/internal/checker/checker.go;l=491-505
  * https://cs.opensource.google/go/x/tools/+/master:go/analysis/unitchecker/unitchecker.go;l=375-382

Requires is really intended for communicating results not diagnostics.

You are requesting 1 root action `(tagliatelle.New(...), "a")`. The action the Requires creates for `(structtag.Analyzer, "a")` executes but generates no diagnostics.


So I believe this is WAI, but not very well documented. I am closing this as WAI. If you are not satisfied are 2 follow-ups folks can take:
1. file a proposal to change printing diagnostics for non-root actions. This change requires one IMO.
2. send a PR with suggested documentation improvements to clarify that only diagnostics for root actions are printed.

**Closed by timothy-king** 2022-05-18 16:43 UTC
Labels: Tools, Analysis

**Comment by ccoVeille** [comment] 2022-05-18 20:46
I checked, and you are right, it's a very common pattern. Also, almost no Analyzer returns results, so returning results might not be a good way to do it.

This is way above my understanding for now in "Golang internals", so I will pass. I'm not even sure what to suggest.

So I will simply consider calling the analyzer directly and not add it to Requires.

Thanks for your feedback, it helped me to go deeper in my understanding
