### ISSUE TITLE
encoding/json: json marshalling fails when tag contains `・`

### ISSUE THREAD

**Issue by Shion1305** [golang/go#68600] opened 2024-07-26 06:53 UTC
### Go version

go version go1.22.5 darwin/arm64

### Output of `go env` in your module/workspace:

```shell
Not related
```

### What did you do?

If you include `・` character in tag, `encoding/json` failes to marshal / unmarshal json properly.
```go
type TestStruct struct {
	TestFieldOK    string `json:"テスト"`
	TestFieldError string `json:"テスト・フィールド"`
}

func main() {
	data := []byte(`{"テスト":"value_ok","テスト・フィールド":"value_error"}`)
	target := TestStruct{}
	if err := json.Unmarshal(data, &target); err != nil {
		fmt.Println(err)
		return
	}
	fmt.Printf("Expected: %s\n", "{TestFieldOK:value_ok TestFieldError:value_error}")
	fmt.Printf("Actual:   %+v\n", target)

	data1 := TestStruct{
		TestFieldOK:    "value_ok",
		TestFieldError: "value_error",
	}
	result, err := json.Marshal(data1)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println()
	fmt.Printf("Expected: %s\n", `{"テスト":"value_ok","テスト・フィールド":"value_error"}`)
	fmt.Printf("Actual:   %s\n", string(result))
}
```
Result: https://go.dev/play/p/jqN3H-05YfL

### What did you see happen?

`encoding/json` failed to parse json properly, as you can see here: https://go.dev/play/p/jqN3H-05YfL
```
Expected: {TestFieldOK:value_ok TestFieldError:value_error}
Actual:   {TestFieldOK:value_ok TestFieldError:}

Expected: {"テスト":"value_ok","テスト・フィールド":"value_error"}
Actual:   {"テスト":"value_ok","TestFieldError":"value_error"}```

**Comment by Shion1305** [comment] 2024-07-26 08:32
I guess this issue is related to this https://github.com/golang/go/issues/22518
However I strongly suggest we should allow `・` in tag as it is one of commonly-used characters as other japanese standard characters.

**Comment by seankhliao** [comment] 2024-07-26 10:38
This is currently documented as https://pkg.go.dev/encoding/json#:~:text=The%20key%20name%20will%20be%20used%20if%20it%27s%20a%20non%2Dempty%20string%20consisting%20of%20only%20Unicode%20letters%2C%20digits%2C%20and%20ASCII%20punctuation%20except%20quotation%20marks%2C%20backslash%2C%20and%20comma.

> The key name will be used if it's a non-empty string consisting of only Unicode letters, digits, and ASCII punctuation except quotation marks, backslash, and comma.

**Comment by seankhliao** [comment] 2024-07-26 10:38
Duplicate of #22518

**Closed by seankhliao** 2024-07-26 10:38 UTC
