### ISSUE TITLE
x/tools/go/types: converts fp constant to string

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11353] opened 2015-06-23 11:51 UTC
Gc correctly rejects the following program:
```go
package n
func n(){_=string(0.)}
```
But gotype successfully compiles it. It must not. ```0.``` is an fp constant.
on commit e9a746de6e61b9b823a981843c0d98bc209eed2b

**Comment by griesemer** [comment] 2015-06-23 16:35
Duplicate of #11357

**Closed by griesemer** 2015-06-23 16:35 UTC
