### ISSUE TITLE
support

### ISSUE THREAD

**Issue by chawdamrunal** [golang/go#38960] opened 2020-05-08 17:27 UTC
every time install some go script always shows this kind of error

go/src/github.com/ndelphit/apkurlgrep/extractor/extractor.go:94:13: undefined: strings.ReplaceAll
.go/src/github.com/ndelphit/apkurlgrep/extractor/extractor.go:95:13: undefined: strings.ReplaceAll

**Comment by ALTree** [comment] 2020-05-08 17:30
It was introduced in go1.12, it's possible that you're using an older version.

Anyway the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-05-08 17:30 UTC
