### ISSUE TITLE
cmd/go: pseudo-versions for post-v1 commits use the wrong major version

### ISSUE THREAD

**Issue by hyangah** [golang/go#29262] opened 2018-12-14 16:45 UTC
Go version: 

`go version devel +976bab6003 Fri Dec 14 09:10:02 2018 +0000 darwin/amd64`

rsc.io/quote's latest released version is v1.5.2. 
But go chooses v0.0.0-... as the pseudo version selected when using the master branch.
 
<pre>
> go list -m -versions -json rsc.io/quote@master
go: finding rsc.io/quote master
{
	"Path": "rsc.io/quote",
	"Version": "v0.0.0-20180710144737-5d9f230bcfba",
	"Versions": [
		"v1.0.0",
		"v1.1.0",
		"v1.2.0",
		"v1.2.1",
		"v1.3.0",
		"v1.4.0",
		"v1.5.0",
		"v1.5.1",
		"v1.5.2",
		"v1.5.3-pre1"
	],
	"Time": "2018-07-10T14:47:37Z",
	"Dir": "/Users/hakim/go/pkg/mod/rsc.io/quote@v0.0.0-20180710144737-5d9f230bcfba",
	"GoMod": "/Users/hakim/go/pkg/mod/cache/download/rsc.io/quote/@v/v0.0.0-20180710144737-5d9f230bcfba.mod"
}
</pre>

Possibly related to #27171 but needs investigation.

@bcmills

**Comment by bcmills** [comment] 2019-01-17 14:55
Dup of #27171, but we should make sure the tests cover this case.

**Comment by bcmills** [comment] 2019-05-17 14:03
This might not be an exact duplicate of #27171, since it also interacts non-trivially with `v2` and `+incompatible`.

**Comment by bcmills** [comment] 2019-05-17 14:08
At current head:

```
$ go list -f '{{.Version}}' -m github.com/sylr/prometheus@v2.9.2+sylr.2
go: finding github.com/sylr/prometheus v2.9.2+sylr.2
v0.0.0-20190510132036-085fc219838d
```

It should instead be something like
```
v2.9.3-0.20190510132036-085fc219838d+incompatible
```

(CC @sylr)

**Comment by sylr** [comment] 2019-05-17 14:16
> It should instead be something like
>>v2.9.3-0.20190510132036-085fc219838d+incompatible

For readability it would be nice if the tag would be kept in the go.mod -> `v2.9.2+sylr.2+incompatible`

**Comment by bcmills** [comment] 2019-05-17 14:17
> For readability it would be nice if the tag would be kept in the go.mod

That's (an interesting special case of) #25898.

**Comment by thepudds** [comment] 2019-05-22 16:28
FWIW, from looking at this somewhat briefly (and hence might not be correct), it seems this issue is specific to a v2+ module and asking for a commit (current meaning of `@master` in this case) where the most recent semver tag at that commit is for a different major version than the major version in the `go get` request. I had a slightly longer write up in https://github.com/golang/go/issues/27171#issuecomment-470134255 (along with some links to the possibly corresponding code):

> In #29262, rsc.io/quote at master has two different major versions following the Major Subdirectory approach. It has a v1 module in the root of the repo, and a v3 module in a /v3 subdirectory. If you ask for go get rsc.io/quote@master, that is asking for v1 of rsc.io/quote, which is a valid request, but the most recent tag on master matching that glob pattern ends up being v3.0.0, which I think is what is returned by RecentTag. The v3 is not what is desired, and the caller gives up and falls back to a v0.0.0- pseudo version (probably [here](https://github.com/golang/go/blob/561923fa7a7d47bba99556aaa61e40dd38708773/src/cmd/go/internal/modfetch/coderepo.go#L233)). This could be viewed as a variation of 1., or could be viewed as a separate problem.

I suspect but have not confirmed that this particular problem pattern would not happen for someone following the "Major Branch" approach for a v2+ module with different branches for v1 vs v2 vs v3 with the appropriate semver tags on their respective branches.

CC @rogpeppe

**Comment by bcmills** [comment] 2019-06-11 19:20
> It should instead be something like
>
> ```
> v2.9.3-0.20190510132036-085fc219838d+incompatible
> ```

That commit actually has a `go.mod` file, and the module path it declares is `github.com/prometheus/prometheus`.

However, the `+incompatible` suffix is generally not allowed in conjunction with a `go.mod` file: the `+incompatible` suffix is intended only for projects predating modules, not as an ongoing bypass for versioned import paths. That probably means that we should use the highest tag matching the path (`v1.8.2`) as the base for the pseudo-version, rather than the `v2.[…]` tag with the `+incompatible` suffix.

It also means I need to find a different example for `+incompatible` pseudo-versions. 😞

**Closed** 2019-06-21 21:03 UTC
Labels: NeedsInvestigation, modules
