### ISSUE TITLE
x/tools/refactor/importgraph: frequent failures of TestBuild on linux-amd64-wsl

### ISSUE THREAD

**Issue by findleyr** [golang/go#47173] opened 2021-07-13 16:24 UTC
x/tools/refactor/importgraph.TestBuild is failing with high frequency on the linux-amd64-wsl builder.

Sample failure:
https://build.golang.org/log/738996dc665e3959c7d92a3bdf1a4424c5d5ce4c

```
--- FAIL: TestBuild (7.72s)
    graph_test.go:52: forward[importgraph][go/build] not found
    graph_test.go:55: reverse[go/build][importgraph] not found
    graph_test.go:52: forward[importgraph][testing] not found
    graph_test.go:55: reverse[testing][importgraph] not found
    graph_test.go:52: forward[importgraph][crypto/hmac] not found
    graph_test.go:55: reverse[crypto/hmac][importgraph] not found
    graph_test.go:80: intransitive: forward.Search(importgraph)[errors] not found
    graph_test.go:83: intransitive: reverse.Search(errors)[importgraph] not found
    graph_test.go:80: intransitive: forward.Search(importgraph)[reflect] not found
    graph_test.go:83: intransitive: reverse.Search(reflect)[importgraph] not found
    graph_test.go:80: intransitive: forward.Search(importgraph)[unsafe] not found
    graph_test.go:83: intransitive: reverse.Search(unsafe)[importgraph] not found
FAIL
FAIL	golang.org/x/tools/refactor/importgraph	7.762s
```

CC @golang/tools-team per OWNERS (I'm not sure who has context)

**Comment by bcmills** [comment] 2021-11-30 14:14
Duplicate of #37823

**Closed by bcmills** 2021-11-30 14:14 UTC
Labels: NeedsInvestigation, Tools
