### ISSUE TITLE
x/website: link to spec doesn't point to latest version

### ISSUE THREAD

**Issue by griesemer** [golang/go#50181] opened 2021-12-15 06:04 UTC
[https://go.dev/ref/spec](https://go.dev/ref/spec) doesn't point to the latest (in progress version of the spec). While incomplete, the latest version has significant sections on generics. The beta is out, we should update this ASAP.

I'd expect to see the content that we show here: [https://tip.golang.org/ref/spec](https://tip.golang.org/ref/spec).

**Comment by griesemer** [comment] 2021-12-15 19:00
Apparently we use the spec of the latest _released_ version here (which is the Go 1.17 spec). But given that we show the first [generics  tutorial](https://go.dev/doc/tutorial/generics) among the documentation, I think we should show the latest (in-progress) version of the spec as well. While the spec is incomplete, many new sections have been written which are complete and are relevant for understanding generics (e.g., new syntax, interfaces as type sets, and new rules for assignments and conversions).

**Comment by ianlancetaylor** [comment] 2021-12-15 20:47
I think for the next two months it's OK to point people to https://tip.golang.org/ref/spec.

**Comment by dmitshur** [comment] 2022-01-26 17:51
I agree with Ian, and think this is working as intended.
https://go.dev/ref/spec allows users to view the specification for the currently stable Go language version.
https://tip.golang.org/ref/spec allows previewing upcoming changes, which might be evolving.
When the final Go 1.18 is released, the content at https://tip.golang.org/ref/spec will become visible at https://go.dev/ref/spec. This happens as part of the release process, so there's nothing we need to do explicitly to make it happen.

I'll close this issue to help keep the list of 1.18 release-blocking issues actionable. @griesemer Please comment or re-open if you think there's something we need to do before 1.18 can be released.

**Closed by dmitshur** 2022-01-26 17:51 UTC
Labels: NeedsFix, release-blocker, Soon
