### ISSUE TITLE
Why can't some of my logs be output in goroutine?

### ISSUE THREAD

**Issue by TaoSunkist** [golang/go#24998] opened 2018-04-23 03:22 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version:go1.10 

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/Users/<user_name>/DevStation/hi_golang/bin"
GOCACHE="/Users/<user_name>/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/<user_name>/DevStation/hi_golang"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yh/tlxxvm450gzgv9yxbqtnqy5h0000gn/T/go-build971977641=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
```
package golang

import (
    "testing"
    "net"
    "time"
    "fmt"
    "log"
)

func TestTcp1(t *testing.T) {
    connFunc := func(conn net.Conn, err error) {
        defer conn.Close()
        time.Sleep(time.Second * 3)
        t.Log("t.Log: ", conn, err)
        fmt.Println("fmt.Println: ", conn, err)
        log.Println("log.Println: ", conn, err)
    }

    if tcpListener, err := net.ListenTCP("tcp", &net.TCPAddr{IP: net.ParseIP("127.0.0.1"), Port: 8000, Zone: ""}); err != nil {
            t.Error(err)
     } else {
            defer tcpListener.Close()
            for {
                go connFunc(tcpListener.Accept())
            }
    }
}

```

### What did you expect to see?
```
➜  golang go test -v -run Tcp1/                   
=== RUN   TestTcp1
fmt.Println:  &{{0xc4200bc100}} <nil>
2018/04/23 11:13:57 log.Println:  &{{0xc4200bc100}} <nil>
```

### What did you see instead?
```
➜  golang go test -v -run Tcp1/                   
=== RUN   TestTcp1
t.Log:  &{{0xc4200bc100}} <nil>
fmt.Println:  &{{0xc4200bc100}} <nil>
2018/04/23 11:13:57 log.Println:  &{{0xc4200bc100}} <nil>
```

Why t.Log() doesn't have any output during the process ?
Thank you for any help.

**Comment by agnivade** [comment] 2018-04-23 03:29
I think you mixed up the "What did you expect to see" vs "What did you see instead". Anyways, `t.Log()` won't output until the test is finished, which in your case, is never.

Also,  we do not use the issue tracker for general discussions or questions like these. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process. You might want to take a look at #24929.

For further questions, please have a look at Questions wiki page; it has a list of good places for asking questions.

Closing since this is not a bug.

**Closed by agnivade** 2018-04-23 03:29 UTC

**Comment by TaoSunkist** [comment] 2018-04-25 10:04
Sorry, I don't understand, why log.Println can be displayed normally, and t.log cannot. However, when I simply use goroutine and use t.log to display the log, this is feasible.

**Comment by TaoSunkist** [comment] 2018-04-25 10:05
Sorry, I don't understand, why log.Println can be displayed normally, and t.log cannot. However, when I simply use goroutine and use t.log to display the log, this is feasible.
