### ISSUE TITLE
io/fs.ValidPath: wrong output using backslash

### ISSUE THREAD

**Issue by MoadKey** [golang/go#52016] opened 2022-03-29 18:07 UTC
<pre>
$ go version
go version go1.17.5 windows/amd64
</pre>

<pre>
package main

import (
	"fmt"
	"io/fs"
)

func main() {
	fmt.Println(fs.ValidPath("\\ab\\ac\\ad"))   //true
	fmt.Println(fs.ValidPath("ab\\ac\\ad\\"))   //true
	fmt.Println(fs.ValidPath("..\\ab\\ac\\ad")) //true	
}
</pre>

After inspecting ValidPath function it look like there is no handling for backslash file path.

**Comment by seankhliao** [comment] 2022-03-29 18:24
> Note that paths are slash-separated on all systems, even Windows. Paths containing other characters such as backslash and colon are accepted as valid, but those characters must never be interpreted by an FS implementation as path element separators.

Closing as not a bug

**Closed by seankhliao** 2022-03-29 18:24 UTC

**Comment by MoadKey** [comment] 2022-03-30 09:44
The function return valid for fs no valid path? it really make no sense. 

Also there is misinformation, according [microsoft#canonicalize separators](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#canonicalize-separators)
<pre>
All forward slashes (/) are converted into the standard Windows separator, the back slash (\). If they are present, a series of slashes that follow the first two slashes are collapsed into a single slash.
</pre>

**Comment by ianlancetaylor** [comment] 2022-03-31 05:58
@MoadKey The io/fs package does not use backslash paths.  It only supports paths with forward slashes.  When using something like `os.DirFS` the `DirFS` type is responsible for handling any necessary slash translation.
