### ISSUE TITLE
encoding/json: unexpected result when json.Unmarshaling

### ISSUE THREAD

**Issue by AllenX2018** [golang/go#38126] opened 2020-03-28 02:17 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.1 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, it reproduces with the latest release.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
</pre></details>

### What did you do?
My struct has a `string` field with a `json:"string"` field tag. When this field contains escaped character, I get unexcepted result when doing roundtrip test.

```go
type T struct {
	F1 string `json:"F1,string"`
}

t := T {
	"aaa\tbbb",
}

b, _ := json.Marshal(t)
if err := json.Unmarshal(b, &t); err == nil {
	fmt.Printf("%+v\n", t)
}else {
	fmt.Println(err)
}
```

### What did you expect to see?
```
{F1:aaa	bbb}
```

### What did you see instead?
```
json: invalid use of ,string struct tag, trying to unmarshal "\"aaa\tbbb\"" into string
```

**Comment by mvdan** [comment] 2020-03-28 10:09
I've confirmed this is a duplicate of #38105. I'll close this issue to consolidate into the other one, but I'll add this as a test case.

**Closed by mvdan** 2020-03-28 10:10 UTC

**Comment by AllenX2018** [comment] 2020-03-30 02:44
It seems that [https://golang.org/cl/226218](https://golang.org/cl/226218) has fix this issue. However, I still have a question. 

```go
type T struct {
	F1 string `json:"F1,string"`
}

t := T {
	"aaa\tbbb",
}

b, _ := json.Marshal(t)
fmt.Println(string(b))
```

Before go 1.14, its output result is 
```
{"F1":"\"aaa\\tbbb\""}
```

Add after go 1.14, it changes to 
```
{"F1":"\"aaa\tbbb\""}
```

It seems this change is introduced by [this commit](https://github.com/golang/go/commit/0e015e20cfe7265635af605d274ff8dc2de5b3a2) but may I ask why you change the encode behavior for string type struct field with ",string" option like this? Which of them excatly match the godoc's description? 

> The "string" option signals that a field is stored as JSON inside a JSON-encoded string

**Comment by mvdan** [comment] 2020-03-30 15:40
You're right, @AllenX2018, something is up with this change in behavior. Can you please file a separate issue? I'm already investigating a fix, but it's good to have an issue to track the bug.

**Comment by AllenX2018** [comment] 2020-03-31 01:42
I've created #38173 for track
