### ISSUE TITLE
go.dev: README tables are not rendered properly (no lines visible, no space between columns)

### ISSUE THREAD

**Issue by fxamacker** [golang/go#37284] opened 2020-02-18 15:09 UTC
Markdown tables are not rendered properly.

* lines for columns and rows are not visible
* no extra space between columns makes each row look like it's only using one big column

Screenshots are from: https://github.com/fxamacker/cbor

### What did you expect to see? (github.com screenshot)
![image](https://user-images.githubusercontent.com/57072051/74747383-80bb0400-522c-11ea-8308-0b0eb3b19578.png)
### What did you see instead? (go.dev screenshot)
![image](https://user-images.githubusercontent.com/57072051/74747518-b19b3900-522c-11ea-808d-39a6d9edc1c5.png)

**Comment by x448** [comment] 2020-02-19 22:00
The table doesn't have pipes at the end of the table, but they're optional.  Another possibility is pipes not always having a space before/after it.  I didn't spot anything else that might cause different rendering between GitHub and go.dev.

[GitHub Help (about tables)](https://help.github.com/en/github/writing-on-github/organizing-information-with-tables) says,

> The pipes on either end of the table are optional.

I updated about a dozen tables and it got merged to fxamacker/cbor master branch.  Interestingly, GitHub "Preview changes" tab didn't show any changes but it showed up in the pull request.

If go.dev displayed tip on the master branch, we'd know if the problem is resolved without having to release a new version.

cc @julieqiu

**Comment by x448** [comment] 2020-02-23 21:45
@julieqiu @dmitshur

Please provide a status update because go.dev is taking someone's online portfolio/work, introducing severe formatting errors, and allowing potential employers to see it.

Here's the markdown code for the latest version of one of the tables.  The affected project has about 12 tables in the README and a release target of tomorrow morning (central time).

Thanks.

```
|     | fxamacker/cbor 2.1 | ugorji/go 1.1.7 |
| --- | ------------------ | --------------- |
| Encode CWT claims | 457 ns/op, 176 B/op, 2 allocs/op | 995 ns/op, 1424 B/op, 4 allocs/op | 
| Decode CWT claims | 796 ns/op, 176 B/op, 6 allocs/op | 1105 ns/op, 568 B/op, 6 allocs/op |
```

|     | fxamacker/cbor 2.1 | ugorji/go 1.1.7 |
| --- | ------------------ | --------------- |
| Encode CWT claims | 457 ns/op, 176 B/op, 2 allocs/op | 995 ns/op, 1424 B/op, 4 allocs/op | 
| Decode CWT claims | 796 ns/op, 176 B/op, 6 allocs/op | 1105 ns/op, 568 B/op, 6 allocs/op |

**Comment by julieqiu** [comment] 2020-02-24 16:23
@x448 we are working on a fix for this - I'll post on the issue once the change has been merged and deployed.

**Comment by andybons** [comment] 2020-02-27 16:25
> Please provide a status update because go.dev is taking someone's online portfolio/work, introducing severe formatting errors, and allowing potential employers to see it.

@x448 please be mindful that we take care to read each issue report and this all takes time. @julieqiu was already on the issue and pinging her in succession is not a recipe for getting a fix in more quickly. We appreciate the context of your reasoning but try to stay clear of anything that could be interpreted as a demand on people's time. Thanks.

**Comment by x448** [comment] 2020-02-28 05:20
> @x448 please be mindful that we take care to read and understand each issue report and this all takes time. [julieqiu] was already on the issue and pinging her in succession is not a recipe for getting a fix in more quickly. 

@andybons  please be mindful that you have access to more info than people outside the Go team.  

There was no indication julieqiu was aware of the issue when I pinged her.  

I did not ping julieqiu after she responded (about 6 days after the issue was opened).

When I pinged julieqiu and @dmitshur there was no indication anyone who was pinged received the ping.  I would not /cc dmitshur unless I thought the issue was important.

For context, we were up past midnight on Sunday mostly due to go.dev issues so being criticized about pinging julieqiu (esp. in a comment needlessly pinging her yet again) was unexpected. 

As of today, there's nobody assigned to this task on GitHub and I don't know if julieqiu was reassigned to other issues after her very much appreciated response about working on this.

Perhaps a more constructive response could've been to fill out the "__Assigned to__" on GitHub for various issues where people might be getting ready to ping Go team members.  The /cc alone doesn't work unless one of the recipients indicates publicly they got the message and is aware. It would've taken less time than the comment you edited twice and sent to me.

Thanks for understanding.  There's more context but my reply is already lengthy.  I found additional unreported bugs in go.dev but they're low priority (to me) compared to this issue and https://github.com/golang/go/issues/37394

**Comment by julieqiu** [comment] 2020-03-02 18:57
@x448 - this should now be fixed.

**Closed by julieqiu** 2020-03-02 18:57 UTC
Labels: NeedsInvestigation, go.dev
