### ISSUE TITLE
crypto/tls: no way to check if a connection uses x25519Kyber768Draft00

### ISSUE THREAD

**Issue by torntrousers** [golang/go#69241] opened 2024-09-04 04:29 UTC
### Go version

go1.23.0 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\tornt\AppData\Local\go-build
set GOENV=C:\Users\tornt\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\tornt\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\tornt\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.23.0
set GODEBUG=
set GOTELEMETRY=local
set GOTELEMETRYDIR=C:\Users\tornt\AppData\Roaming\go\telemetry
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\CQ\gopqc\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\tornt\AppData\Local\Temp\go-build1302039288=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

Trying the new x25519Kyber768Draft00 support from https://github.com/golang/go/issues/67061 that came out in go1.23 

### What did you see happen?

There is no way i can find to find if a TLS connection is using x25519Kyber768Draft00

### What did you expect to see?

Provide a way ? There is a very hacky approach in the curveID function here: https://forum.golangbridge.org/t/go-1-23-pqc-quantum-safe-tls/36126/2?u=torntrousers

**Comment by dmitshur** [comment] 2024-09-04 17:45
CC @FiloSottile, @golang/security.

**Comment by rolandshoemaker** [comment] 2024-09-04 18:17
Essentially a duplicate of https://go.dev/issue/67516, which is planned for 1.24.

**Comment by seankhliao** [comment] 2024-09-04 18:51
Duplicate of #67516

**Closed by seankhliao** 2024-09-04 18:51 UTC
Labels: NeedsInvestigation, FeatureRequest

**Comment by torntrousers** [comment] 2024-09-04 20:32
...hope the testingOnlyCurveID field will be maintained until 1.24 then :)

**Comment by rolandshoemaker** [comment] 2024-09-04 20:41
Yup, we have no plans to remove it, we use it in our own internal TLS testing currently.
