### ISSUE TITLE
encoding/gob: return error on NaN map keys

### ISSUE THREAD

**Issue by ek233** [golang/go#47475] opened 2021-07-30 14:16 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.16.5
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY="git.code.oa.com"
GONOSUMDB="git.code.oa.com"
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE="git.code.oa.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/data/git.code.oa.com/korzhao/mytest/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2378286668=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```go
package main

import (
	"bytes"
	"encoding/gob"
	"fmt"
	"math"
)

func main() {
	var m = map[float64]string{math.NaN(): "NaN"}

	var b bytes.Buffer
	enc := gob.NewEncoder(&b)
	err := enc.Encode(m)
	if err != nil {
		fmt.Println("error: ", err)
	} else {
		fmt.Println("no err")
	}
}

```

### What did you expect to see?
```
no err
```
### What did you see instead?
```
error:  gob: encodeReflectValue: nil element
```

**Comment by seankhliao** [comment] 2021-07-30 14:18
Duplicate of #24075

**Closed by seankhliao** 2021-07-30 14:18 UTC
