### ISSUE TITLE
proposal: encoding/json: mark field when struct decoding

### ISSUE THREAD

**Issue by Ccheers** [golang/go#54351] opened 2022-08-09 12:30 UTC
in this case the id field value is 5 , but the key "id" is match in better.
```go 
package main

import (
	"encoding/json"
	"log"
)

type Foo struct {
	ID uint `json:"id"`
}

const jsonStr = `{"id":2,"ID":5}`

func main() {
	a := &Foo{}
	b := make(map[string]interface{})
	json.Unmarshal([]byte(jsonStr), a)
	json.Unmarshal([]byte(jsonStr), &b)

	log.Println(a)
	// output &{5}

	log.Println(b)
	// output map[ID:5 id:2]
}
```

add a flag like "isMatched" when matched with nameIndex set the flag "true"

like this:

```go

type structFields struct {
	list      []field
	nameIndex map[string]int
}

// A field represents a single field found in a struct.
type field struct {
	...

        isMatched bool // add a flag when nameIndex matched
}
```

[https://github.com/golang/go/blob/master/src/encoding/json/decode.go#L702](https://github.com/golang/go/blob/master/src/encoding/json/decode.go#L702)
```go
	if i, ok := fields.nameIndex[string(key)]; ok {
		// Found an exact name match.
		f = &fields.list[i]
+               f.isMatched = true
	} else {
		// Fall back to the expensive case-insensitive
		// linear search.
		for i := range fields.list {
			ff := &fields.list[i]
+			if !ff.isMatched && ff.equalFold(ff.nameBytes, key) {
				f = ff
				break
			}
		}
	}
```

**Comment by seankhliao** [comment] 2022-08-09 14:14
Duplicate of #14750

**Closed by seankhliao** 2022-08-09 14:14 UTC
Labels: Proposal
