### ISSUE TITLE
Ignore _UnusedVar_ via compiler flag (reasonable use case provided)

### ISSUE THREAD

**Issue by ErnestoBorio** [golang/go#47385] opened 2021-07-25 14:21 UTC
### What did you do?

A possibly useful use case for declaring variables and _not using_ them in go.
I want to format a value to see it in the watches when debugging, my IDE (vscode) doesn't support changing the format of watches.

`xopcode := fmt.Sprintf("%X", opcode)`

I need to quickly see that value in hex format in the watches.

#### Note:
I guess you might have received this request lots of times, but an issue search for _UnusedVar_ or _declared but not used_ doesn't return anything useful.

### What version of Go are you using (`go version`)?

<pre>
go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/.../Library/Caches/go-build"
GOENV="/Users/.../Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/.../Source/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/.../Source/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/.../go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qq/hvxwwstd681cwpsrnn8cwm7w0000gn/T/go-build1882706383=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by fzipp** [comment] 2021-07-25 14:39
> I want to format a value to see it in the watches when debugging, my IDE (vscode) doesn't support changing the format of watches.
> 
> `xopcode := fmt.Sprintf("%X", opcode)`
> 
> I need to quickly see that value in hex format in the watches.

You can always turn an unused variable into a used variable by assigning it to `_`:

```
xopcode := fmt.Sprintf("%X", opcode)
_ = xopcode
```

Perhaps the VSCode debugger interface also has an "evaluate expression" functionality (I know GoLand has), so that you don't even have to assign it to a variable.

> I guess you might have received this request lots of times, but an issue search for UnusedVar or declared but not used doesn't return anything useful.

Yes, here are the previous discussions: #513, #958, #1085, #43729

**Comment by seankhliao** [comment] 2021-07-25 14:42
Duplicate of #43729

**Closed by seankhliao** 2021-07-25 14:42 UTC
