### ISSUE TITLE
cmd/compile: reflect.Type does not implement comparable

### ISSUE THREAD

**Issue by limpo1989** [golang/go#53249] opened 2022-06-06 13:59 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
et GO111MODULE=on
set GOARCH=amd64
set GOBIN=      
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\gomod\pkg\mod
set GONOPROXY=***
set GONOSUMDB=***
set GOOS=windows
set GOPATH=D:\gomod;C:\Users\Administrator\go
set GOPRIVATE=git.idianhun.com,git.dianhun.cn
set GOPROXY=https://goproxy.io,direct
set GOROOT=D:\Go
set GOSUMDB=off
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.18.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=*********\example\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build1029863356=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

https://go.dev/play/p/wSisCGgWwUg

```go
// You can edit this code!
// Click here and start typing.
package main

import (
	"fmt"
	"reflect"

	"golang.org/x/exp/maps"
)

func main() {
	var types = make(map[reflect.Type]int)
	fmt.Println(maps.Keys(types))
}
```

### What did you expect to see?
compiled successfully

### What did you see instead?
./prog.go:14:23: reflect.Type does not implement comparable

Go build failed.

**Comment by seankhliao** [comment] 2022-06-06 14:14
Duplicate of #52509 and others

**Closed by seankhliao** 2022-06-06 14:14 UTC
