### ISSUE TITLE
proposal: add "test" build constraint

### ISSUE THREAD

**Issue by mateusz834** [golang/go#53518] opened 2022-06-23 15:43 UTC
I tried to reduce heap allocations of an function that read from net.Conn interface.
```
func doSth(c net.Conn) error {
	buf := make([]byte, 512)
	c.Read(buf)
        //(...)
	return nil
}
```
```
./main.go:11:13: make([]byte, 512) escapes to heap
```
The problem turned out to be the net.Conn interface. Calls to any interface methods causes heap allocation of buf.

So I changed the net.Conn to *net.TCPConn and buf was stack allocated.
```
./main.go:11:13: make([]byte, 512) does not escape
```

But then the test build was failing (because it used a mocked net.Conn interface)
I've got an idea to use type aliases to fix that compilation error.

I created two files:
conn.go:
```
//go:build !test
package main

type connT = *net.TCPConn
```
connTest.go:
```
//go:build test
package main

type connT = net.Conn
```

changed the definition of the function to:
```
func doSth(c connT) error {
	buf := make([]byte, 512)
	c.Read(buf)
        //(...)
	return nil
}
```
And then I realized that the build constraint "test" does not exist.
So now I have to explicit type the "test" tag to the go test command:
```
go test -tags test .
```
Instead of:
``` 
go test .
 ```

Proposal: add "test" build constraint that will become active while running go test.

**Comment by seankhliao** [comment] 2022-06-23 15:49
Duplicate of #14668

**Closed by seankhliao** 2022-06-23 15:49 UTC
Labels: Proposal
