### ISSUE TITLE
x/tools/gopls: random cannot use X as X in value in argument Y

### ISSUE THREAD

**Issue by primalmotion** [golang/go#34584] opened 2019-09-28 01:34 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="off"
GOARCH="amd64"
GOBIN="/Users/tonio/Documents/Aporeto/workspace/code/go/bin"
GOCACHE="/Users/tonio/Library/Caches/go-build"
GOENV="/Users/tonio/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tonio/Documents/Aporeto/workspace/code/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hc/3p6xvgw97kl124_y5p18kk6m0000gn/T/go-build379134226=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Since a few upgrades from the gopls tip, I get random errors a bit everywhere looking like

```
cannot use 5 * time.Minute (constant 300000000000 of type time.Duration) as time.Duration value in argument to context.WithTimeout
```

```
cannot use Thing (type *Thing) as *Thing in argument to someFunc
```

### What did you expect to see?

Not that

### What did you see instead?

well, that

**Comment by karlc1** [comment] 2019-09-30 09:09
I get the same thing  occasionally. I remember that this same issue was present in the bingo language server like a year ago.

**Comment by sebsebmc** [comment] 2019-09-30 18:19
This may be related to https://github.com/golang/go/issues/34410

**Comment by zikaeroh** [comment] 2019-09-30 18:38
I've also been getting this, and have pinned my gopls to `v0.1.8-0.20190919223014-db1d4edb4685` in the meantime since I've found that to be before the breakage. Had been planning on doing a bisect, but it only comes up after some time (often when adding/removing packages) so haven't done it yet.

**Comment by stamblerre** [comment] 2019-10-03 19:28
Duplicate of https://github.com/golang/go/issues/34410

**Closed by stamblerre** 2019-10-03 19:28 UTC
Labels: Tools, gopls
