### ISSUE TITLE
sync/atomic: spurious "invalid recursive type" compilation error for `"sync/atomic".Pointer`

### ISSUE THREAD

**Issue by yuri-kilochek** [golang/go#57415] opened 2022-12-20 22:23 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/gobug/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1405439721=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Tried to `go build` the following:
```go
package bug

import "sync/atomic"

type node struct {
    next atomic.Pointer[node]
}
```
Not providing `go.dev/play` link because it's running `go1.19.2`, where the bug does not occur. 

### What did you expect to see?
It compiles without errors.

### What did you see instead?
```
go build
# bug
./bug.go:5:6: invalid recursive type node
	./bug.go:5:6: node refers to
	./bug.go:6:16: atomic.Pointer refers to
	./bug.go:5:6: node
```

**Comment by yuri-kilochek** [comment] 2022-12-20 22:26
Likely caused by https://github.com/golang/go/pull/56604/commits/7025ae027e0ae3a0441fb036b94e44500b41434d#diff-74356a5476466d442c2023f47d58e830715ba62eacd24b331200899a9cc3909cR45

**Comment by seankhliao** [comment] 2022-12-20 22:30
Duplicate of #57124

**Closed by seankhliao** 2022-12-20 22:30 UTC
Labels: compiler/runtime
