### ISSUE TITLE
crypto/rand: Read should not escape the input buffer

### ISSUE THREAD

**Issue by dsnet** [golang/go#67897] opened 2024-06-07 21:21 UTC
### Go version

go1.22

### Output of `go env` in your module/workspace:

```shell
n/a
```

### What did you do?

[Ran this benchmark](https://go.dev/play/p/zseu1uhvT8W):
```go
func Benchmark(b *testing.B) {
	b.ReportAllocs()
	for range b.N {
		sink = cryptoRandRead()
	}
}

//go:noinline
func cryptoRandRead() (out [8]byte) {
	rand.Read(out[:])
	return out
}
```

### What did you see happen?

```
Benchmark-24    	 1877874	       616.4 ns/op	       8 B/op	       1 allocs/op
```

### What did you expect to see?

```
Benchmark-24    	 1877874	       616.4 ns/op	       0 B/op	       0 allocs/op
```
The `Read` function is a static function. With some work to the underlying implementation (and avoid going through an `io.Reader`), we should be able to make it not escape the input.

Thus, you could do something like:
```go
var arr [32]byte
rand.Read(arr[:])
```
and know that it doesn't allocate.

**Comment by thepudds** [comment] 2024-06-08 00:05
See also #66779 and https://go.dev/cl/578516.

**Comment by rsc** [comment] 2024-06-08 03:02
Duplicate of #66779.

**Closed by rsc** 2024-06-08 03:02 UTC
Labels: Performance
