### ISSUE TITLE
x/tools/gopls: support setting imports LocalPrefix

### ISSUE THREAD

**Issue by Zariel** [golang/go#33667] opened 2019-08-15 12:01 UTC
Please answer these questions before submitting your issue. Thanks!

#### What did you do?
With vscode it is possible to set formatTool flags which for goimports allows configuring "-local" which sets LocalPrefix in the imports.ProcessEnv struct passed in to the Options when fixing imports.

It is not possible to configure the imports behaviour when using gopls

#### What did you expect to see?
Local imports sorted outside of standard library ones

#### What did you see instead?
Local imports mixed with standard library

#### System details

```
go version go1.12.8 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/chris/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/chris/dev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.8/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.8/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOROOT/bin/go version: go version go1.12.8 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.12.8
uname -v: Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87
lldb --version: lldb-1001.0.13.3
  Swift-5.0
```

**Comment by suzmue** [comment] 2019-08-15 13:59
Duplicate of #32049 

Feel free to reopen if you think this is a separate issue!

**Closed by suzmue** 2019-08-15 13:59 UTC
Labels: gopls
