### ISSUE TITLE
affected/package: encoding/json

### ISSUE THREAD

**Issue by madkins23** [golang/go#54609] opened 2022-08-22 21:54 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

AFAIK I'm using the latest release (or at least the latest snap release).

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/marc/go/bin"
GOCACHE="/home/marc/.cache/go-build"
GOENV="/home/marc/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/marc/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/marc/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/9952"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/9952/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3232480261=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Given a container struct with a map and an entity struct with custom `Marshaler` and `Unmarshaler` methods. The custom methods are defined using pointer references to the entity struct.

If the map values in the container struct are pointers to the entity struct everything works fine. If the map values are the actual entity structs then the `MarshalJSON` method isn't called.

Array values seem to work just fine with both pointers and objects.

https://go.dev/play/p/jNsHN9rKAZt

### What did you expect to see?

The map value cases for pointer and object should be the same.

### What did you see instead?

The Object case doesn't seem to call the custom `MarshalJSON` for map values that are objects, but it works for array values that are objects.

```
Ptr container:
  MarshalJSON()  'listed'->1
  MarshalJSON()  'mapped'->2
  UnmarshalJSON()  {"Text":"listed|1"}
  UnmarshalJSON()  {"Text":"mapped|2"}
! ptr == ptr2
  ptr1: {['listed'->1] map[ptrKey:'mapped'->2]}
  ptr2: {['listed'->1] map[ptrKey:'mapped'->2]}
Obj container:
  MarshalJSON()  'listed'->1
  UnmarshalJSON()  {"Text":"listed|1"}
  UnmarshalJSON()  {}
Error unmarshaling objContainer: wrong number of pieces: 1
* obj1 != obj2
  obj1: {[{listed 1}] map[objKey:{mapped 2}]}
  obj2: {[{listed 1}] map[]}
```

**Comment by seankhliao** [comment] 2022-08-22 22:40
`UnmarshalJSON` is defined on `*Example`, not `Example`, and map values are unaddressable.

Closing as working as intended.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Closed by seankhliao** 2022-08-22 22:40 UTC
