### ISSUE TITLE
sync/atomic: add `//go:noescape` to atomic functions accepting pointer

### ISSUE THREAD

**Issue by valyala** [golang/go#36651] opened 2020-01-20 12:48 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +cfe3cd903f Tue Jan 14 19:54:20 2020 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes, it is reproducible in `go1.13` and `go tip`.

### What did you do?

Run the following benchmark:

```go
func BenchmarkAtomicAddUint64(b *testing.B) {
        b.ReportAllocs()
        for i := 0; i < b.N; i++ {
                n := uint64(123)
                sink += atomic.AddUint64(&n, 1)
        }
}

var sink uint64
```

### What did you expect to see?
Zero memory allocations in the benchmark loop.

### What did you see instead?
A memory allocation. The following is the output from `go tool pprof --alloc_objects`:

```
  25919883   25919883 (flat, cum)   100% of Total
         .          .     10:)
         .          .     11:
         .          .     12:func BenchmarkAtomicAddUint64(b *testing.B) {
         .          .     13:	b.ReportAllocs()
         .          .     14:	for i := 0; i < b.N; i++ {
  25919883   25919883     15:		n := uint64(123)
         .          .     16:		sink += atomic.AddUint64(&n, 1)
         .          .     17:	}
         .          .     18:}
         .          .     19:
         .          .     20:var sink uint64
```

It looks like Go compiler thinks that args passed to `sync/atomic` functions may escape.

Possible solution is to add `//go:noescape` to these functions.

**Comment by randall77** [comment] 2020-01-20 17:52
Closing as duplicate of #16241

**Closed by randall77** 2020-01-20 17:52 UTC
