### ISSUE TITLE
go.dev: search for golang.org/x/tools/internal doesn't return packages beneath that import path

### ISSUE THREAD

**Issue by myitcv** [golang/go#36804] opened 2020-01-27 18:54 UTC
### What is the URL of the page with the issue?

https://pkg.go.dev/search?q=golang.org%2Fx%2Ftools%2Finternal

### What is your user agent?

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.66 Safari/537.36
</pre>

### Screenshot

<img width="1163" alt="Screen Shot 2020-01-27 at 18 53 20" src="https://user-images.githubusercontent.com/3374574/73204101-4fbc4780-4136-11ea-8fd2-4b5bbc2cbd06.png">

### What did you do?

Searched for `golang.org/x/tools/internal`

### What did you expect to see?

Results for `golang.org/x/tools/internal/...`

### What did you see instead?

Results for everything but `golang.org/x/tools/internal/...` :)

**Comment by julieqiu** [comment] 2020-01-28 19:06
Thanks for pointing this out! This seems like a bug - I'll look into it.

**Comment by julieqiu** [comment] 2020-01-29 14:38
Closing, as this is a duplicate of #36803  

Both are issues related to searching for a directory/module path, which should redirect you to the page for that path.

**Closed by julieqiu** 2020-01-29 14:38 UTC
Labels: NeedsFix, go.dev
