### ISSUE TITLE
`go mod why X`  installs X to go.mod?

### ISSUE THREAD

**Issue by ORESoftware** [golang/go#39082] opened 2020-05-14 23:11 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
More or less.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alex/Library/Caches/go-build"
GOENV="/Users/alex/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/alex/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/alex/go/src/github.com/channelmeter/cp-go-api/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qh/l8tr6tfd3gv7fmdg0b5z0p340000gn/T/go-build287184497=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I ran:

```
 go mod why github.com/DATA-DOG/go-sqlmock 
```

and it added that dep to my go.mod file. I didn't expect it to add it to the file, if it wasn't already there.

**Comment by mvdan** [comment] 2020-05-15 10:31
I think you wanted `go mod why -m` instead. `go mod why` works on packages, so if it's given a package that doesn't belong in any of the modules it knows about, it must then resolve that new module (thus adding it to `go.mod`).

**Comment by bcmills** [comment] 2020-05-18 15:37
Duplicate of #26977

**Closed by bcmills** 2020-05-18 15:37 UTC
Labels: modules
