### ISSUE TITLE
Please expose CLOCK_MONOTONIC or CLOCK_BOOTTIME

### ISSUE THREAD

**Issue by jech** [golang/go#17907] opened 2016-11-14 00:01 UTC
Using Go 1.7, I don't see a way to do the equivalent of `clock_gettime(CLOCK_MONOTONIC)`.  I haven't even found `clock_gettime` in the `syscall` package.  (FWIW, I need it in order to expire data items when they haven't been reflooded in a given interval.  Oh well, I guess I'll just restart my daemon whenever ntpd steps the time.)

It would be nice to have a portable interface to monotonic time.  IMHO, monotonic time should be exposed as returning  a value of type `time.Duration`, to make it clear that it is measured from an arbitrary origin.  Under Linux, I'd prefer it to expose `CLOCK_BOOTTIME` (which makes more sense for network applications, since it allows different peers to remain roughly in sync), but I can live with `CLOCK_MONOTONIC`.

**Comment by pquerna** [comment] 2016-11-14 05:48
Dupe of https://github.com/golang/go/issues/12914

You can also use `CLOCK_MONOTONIC` like this:
https://github.com/ScaleFT/monotime/blob/master/clock_unix.go#L15-L21

**Closed** 2016-11-14 06:18 UTC
