### ISSUE TITLE
x/website: Missing download for MacOS (Darwin) arm64

### ISSUE THREAD

**Issue by darrenparkinson** [golang/go#52323] opened 2022-04-13 08:20 UTC
### What is the URL of the page with the issue?
 
 https://go.dev/dl/
 
### What is your user agent?
 

 
 [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
### Screenshot
 

 
 
![image](https://user-images.githubusercontent.com/4262917/163132046-137ced3a-b95c-4c65-9a56-aa4d76cc399e.png)

 
### What did you do?
 

 
 I went to download Go 1.18 for MacOS
 
### What did you expect to see?
 
 A download of Go 1.18 available for MacOS 
 
### What did you see instead?

A download of Go 1.18 not available for Mac OS

**Comment by seankhliao** [comment] 2022-04-13 08:20
Duplicate of #52317

**Closed by seankhliao** 2022-04-13 08:20 UTC
