### ISSUE TITLE
template.ParseGlob if pattern  read /dev/* files  ，program will  hanged on and can  Dos attack

### ISSUE THREAD

**Issue by cor0ps** [golang/go#46837] opened 2021-06-20 11:48 UTC
What version of Go are you using (go version)?
mac os:
➜  ~ go version             
go version go1.16.5 darwin/amd64
linux os:
[root@VM-0-5-centos ~]# go version
go version go1.16 linux/amd64
Does this issue reproduce with the latest release?
go version go1.16.5 darwin/amd64

What operating system and processor architecture are you using (go env)?
go env Output
What did you do?

https://play.golang.org/p/dArYQMl7el6   Update code on  play and  Program exited: status 137.

mac os:

func main() {
	data := []byte("/\*d\*/*p")
	_, err := template.ParseGlob(string(data))
	if err != nil {
		fmt.Println(err)
	}

}
notice:

/\*d\*/*p  in mac os  match  /dev/io8logtemp  
linux os:

package main

import (
        "fmt"
        "html/template"
)

func main() {

        data := []byte("/dev/*6")

        _, err := template.ParseGlob(string(data))
        if err != nil {
                fmt.Println(err)
        }

}
/dev/*6 in linux os match many

[root@VM-0-5-centos cor0ps]# ls -al /dev/*6
crw--w---- 1 root tty 4,  16 Jun 11 11:57 /dev/tty16
crw--w---- 1 root tty 4,  26 Jun 11 11:57 /dev/tty26
crw--w---- 1 root tty 4,  36 Jun 11 11:57 /dev/tty36
crw--w---- 1 root tty 4,  46 Jun 11 11:57 /dev/tty46
crw--w---- 1 root tty 4,  56 Jun 11 11:57 /dev/tty56
crw--w---- 1 root tty 4,   6 Jun 11 11:57 /dev/tty6
crw-rw---- 1 root tty 7,  16 Jun 20 11:48 /dev/vcs16
crw-rw---- 1 root tty 7,  56 Jun 20 16:59 /dev/vcs56
crw-rw---- 1 root tty 7,   6 Jun 11 11:57 /dev/vcs6
crw-rw---- 1 root tty 7, 144 Jun 20 11:48 /dev/vcsa16
crw-rw---- 1 root tty 7, 184 Jun 20 16:59 /dev/vcsa56
crw-rw---- 1 root tty 7, 134 Jun 11 11:57 /dev/vcsa6
What did you expect to see?
程序死循环读取文件了，一直卡在读取文件了，就会造成dos攻击
Program loop read file, has been stuck in the read file, will cause DoS attack。

maybe i think reasons here:

/usr/local/go/src/html/template/template.go ---> readFileOS  --->os.ReadFile have  loop function 

What did you see instead?
i think ParseGlob should  check files  on host operating system's file system, and  I am  test  on   host operating system's file system  not  file system ,so  I  don not  need use  ParseFS。
// ParseFS is like ParseFiles or ParseGlob but reads from the file system fs
// instead of the host operating system's file system.

**Comment by nirui** [comment] 2021-06-20 14:05
I'm just a by stander here. But ... why you must read /dev? Because of the pattern `/*d*/*p`? Then why you want to use that pattern?

**Comment by cor0ps** [comment] 2021-06-20 14:42
[](url)

> I'm just a by stander here. But ... why you must read /dev? Because of the pattern `/*d*/*p`? Then why you want to use that pattern?



> I'm just a by stander here. But ... why you must read /dev? Because of the pattern `/*d*/*p`? Then why you want to use that pattern?

maybe I  fuzz files on  parseGlob() ，I  find  /*d*/*p pattern  matchs   /dev/* file  and read /dev/* exists file  will loop read always  and program  will   hanged on

**Comment by nirui** [comment] 2021-06-20 15:15
> I find /_d_/_p pattern matchs /dev/_ file and read /dev/* exists file will loop read always and program will hanged on

This can be separated in to two parts:

1. The word "Glob" in the function name `template.ParseGlob` actually means [Glob Pattern]. The `*` symbol _"matches any number of any characters **including none**"_. So `/*d*/` in your program means "as long as the name of the folder contains `d`", that includes `/dev`, of course.
    You can try run `ls /*d*/*p` on your computer, it should yield the same result. So I think the behavior is expected. (But I'm not the boss there, mind you :))
2. And about the looping read part: there are many "nasty" or "weird" things in `/dev`, (/dev/random, /dev/sda... to name a few) you probably don't want to read it directly.

So my question remains: Why you want to use that pattern?

[Glob Pattern]: https://en.wikipedia.org/wiki/Glob_%28programming%29#Syntax

**Comment by ianlancetaylor** [comment] 2021-06-20 19:25
Don't use `template.ParseGlob` with a string that is not under your control.  That's not what it's for.

I don't understand how this bug report could be fixed.  It seems equivalent to saying that it is buggy to call `os.Open("/dev/tty6").

**Comment by cor0ps** [comment] 2021-06-21 01:06
> > I find /_d_/_p pattern matchs /dev/_ file and read /dev/* exists file will loop read always and program will hanged on
> 
> This can be separated in to two parts:
> 
> 1. The word "Glob" in the function name `template.ParseGlob` actually means [Glob Pattern](https://en.wikipedia.org/wiki/Glob_%28programming%29#Syntax). The `*` symbol _"matches any number of any characters **including none**"_. So `/*d*/` in your program means "as long as the name of the folder contains `d`", that includes `/dev`, of course.
>    You can try run `ls /*d*/*p` on your computer, it should yield the same result. So I think the behavior is expected. (But I'm not the boss there, mind you :))
> 2. And about the looping read part: there are many "nasty" or "weird" things in `/dev`, (/dev/random, /dev/sda... to name a few) you probably don't want to read it directly.
> 
> So my question remains: Why you want to use that pattern?

You're right. If an external attacker can't query the host system with ls  -al , then we can only guess whether there is a file under / dev / * by using an expression. So / * d * / * p * is used. Similarly, the P letter can be replaced at will until it matches the existing file

**Comment by cor0ps** [comment] 2021-06-21 01:07
> Don't use `template.ParseGlob` with a string that is not under your control. That's not what it's for.
> 
> I don't understand how this bug report could be fixed. It seems equivalent to saying that it is buggy to call `os.Open("/dev/tty6").

maybe  you  said  right

**Comment by cor0ps** [comment] 2021-06-21 02:27
> Don't use `template.ParseGlob` with a string that is not under your control. That's not what it's for.
> 
> I don't understand how this bug report could be fixed. It seems equivalent to saying that it is buggy to call `os.Open("/dev/tty6").

https://play.golang.org/p/dArYQMl7el6   update code  on  play code  and you  can  watch  it

**Comment by cor0ps** [comment] 2021-06-21 02:30
https://play.golang.org/p/dArYQMl7el6                  Update code on https://play.golang.org/

**Comment by seankhliao** [comment] 2021-06-21 21:07
Closing as working as intended / dup of #46835

**Closed by seankhliao** 2021-06-21 21:07 UTC
