### ISSUE TITLE
Embedded generic types do not compile 

### ISSUE THREAD

**Issue by JeremyLoy** [golang/go#50731] opened 2022-01-21 06:40 UTC
### What version of Go are you using (`go version`)?

 Tip

### Does this issue reproduce with the latest release?

yes, the 1.18 beta

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

https://go.dev/play/p/qxuirmm7CCi?v=gotip

The example is copied directly from the proposal

https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md

### What did you expect to see?

It compiled and a generic locker type would be usable 

### What did you see instead?

“ embedded field type cannot be a (pointer to a) type parameter”

**Comment by seankhliao** [comment] 2022-01-21 06:54
Duplicate of #49030

**Closed by seankhliao** 2022-01-21 06:54 UTC
