### ISSUE TITLE
x/tools/gopls: add support for folding comment regions

### ISSUE THREAD

**Issue by codyoss** [golang/go#51364] opened 2022-02-25 16:21 UTC
### gopls version

golang.org/x/tools/gopls v0.7.5

### What did you do?

Wrote a program with comment regions

```go
package foo

//region foomethods

func Bar() string {
	return "Bar"
}

func Baz() string {
	return Baz""
}

//endregion foomethods
```

### What did you expect to see?

I expected to be able to collapse the regions
![Screen Shot 2022-02-25 at 9 16 38 AM](https://user-images.githubusercontent.com/6331106/155749556-8a293d72-e65e-4a2d-b2ec-4841fa9baea0.png)

![Screen Shot 2022-02-25 at 9 17 30 AM](https://user-images.githubusercontent.com/6331106/155749656-98a315eb-e52d-4115-9dbf-a6e4a29d02a6.png)

### What did you see instead?

No folding support by the language server.

![Screen Shot 2022-02-25 at 9 18 29 AM](https://user-images.githubusercontent.com/6331106/155749772-af72ecc8-3c85-4de5-ad06-f9dff5825b3f.png)

### Editor and settings

To get the desired effect I was able to switch `editor.foldingStrategy = "indentation"`. This does not seem ideal though as *I believe* this bypasses any special folding that the language server provides.

**Comment by findleyr** [comment] 2022-03-03 22:34
Thank you for the issue.

Is 'region' supported by other Go tools? Do you have a reference for how 'region' should behave?

Go source code is consumed by many tools, including other editors and pkg.go.dev. Adding comment annotations to control the behavior of any one tool is generally discouraged.

**Comment by codyoss** [comment] 2022-03-04 14:54
> Is 'region' supported by other Go tools?

No. But I don't think it makes sense in the context of other Go tooling. This is just an IDE code organization feature.

 > Do you have a reference for how 'region' should behave?

It should behave just like folding an if statement or a function. Here is VS Codes official docs and the syntax other language servers support for this feature: [folding](https://code.visualstudio.com/docs/editor/codebasics#_folding)

> Go source code is consumed by many tools, including other editors and pkg.go.dev.

These comments are not attached to any symbols so they would not show up in godoc.

> Adding comment annotations to control the behavior of any one tool is generally discouraged. 

I hear you, this is really one an editor feature. But I would say it is a common feature. So it really only makes context in of a language server.

**Comment by codyoss** [comment] 2022-03-04 14:55
Related, with maybe some extra info: https://github.com/microsoft/vscode/issues/91140

**Comment by hyangah** [comment] 2022-03-04 14:58
Duplicate of https://github.com/golang/vscode-go/issues/134

**Comment by findleyr** [comment] 2022-03-04 18:42
Closing in favor of the vscode issue.

**Closed by findleyr** 2022-03-04 18:42 UTC
Labels: WaitingForInfo, gopls, Tools
