### ISSUE TITLE
x/pkgsite: https://pkg.go.dev/github.com/hashicorp/mql

### ISSUE THREAD

**Issue by jimlambrt** [golang/go#62068] opened 2023-08-16 13:46 UTC
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/hashicorp/mql#pkg-functions

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15

### Screenshot

![image](https://github.com/golang/go/assets/16257483/ad1b231c-811e-48fa-be01-d34acfe0cbce)

![image](https://github.com/golang/go/assets/16257483/acb57b0e-ed0c-47e2-930d-ba865ead9698)

### What did you do?

I was trying to verify the godocs for the pkg and just navigated to: https://pkg.go.dev/github.com/hashicorp/mql#pkg-functions

### What did you expect to see?

I expected to see the `Parse(...)` function in the `Functions` section.

### What did you see instead?

`This section is empty.`

**Comment by seankhliao** [comment] 2023-08-16 14:06
Duplicate of #40223

**Closed by seankhliao** 2023-08-16 14:06 UTC
Labels: pkgsite
