### ISSUE TITLE
fmt: How can I empty input stream? The fmt.Scanf in a main cannot use more than 2 times, the second will appear to skip a need for input.

### ISSUE THREAD

**Issue by CodyGuo** [golang/go#13608] opened 2015-12-14 08:06 UTC
How can I empty input stream?

package main

import (
	"fmt"
)

func main() {
	var a int
	var f float32
	var str string

	fmt.Print("Please input : ")
	fmt.Scanf("%d %f %s", &a, &f, &str)
	fmt.Println("Output: ", a, f, str)

	fmt.Println("----------------------------")

	var sIP, sMac string
	fmt.Print("Please input: ")
	fmt.Scanf("%s %s", &sIP, &sMac)

	fmt.Println("Output: ", sIP, sMac)
}

OUTPUT：
Please input : 1 3.24 hello
Output:  1 3.24 hello
----------------------------
Please input: Output:

**Comment by davecheney** [comment] 2015-12-14 09:29
Duplicate of #13607.

Please do not ask questions on the issue tracker. The issue tracker is only for bugs.

Please see https://github.com/golang/go/wiki/Questions

**Closed by davecheney** 2015-12-14 09:29 UTC

**Comment by CodyGuo** [comment] 2015-12-14 10:10
I'm sorry, I don't have access to mailing lists and BBS address.

**Comment by davecheney** [comment] 2015-12-14 10:20
@CodyGuo I'm sorry to hear that. We cannot have a discussion on the issue tracker. I have heard there is a cn language mailing list, perhaps they can help. /cc @minux

**Comment by CodyGuo** [comment] 2015-12-14 11:31
Thank you, I found the solution.
/ / initialize the stdin
OS. Stdin = OS. NewFile (uintptr (syscall. Stdin), "/ dev/Stdin")
