### ISSUE TITLE
crypto/x509: add support for marshalling PKCS#8 private keys

### ISSUE THREAD

**Issue by AGWA** [golang/go#13487] opened 2015-12-04 21:00 UTC
crypto/x509 currently supports parsing PKCS#8 private keys with `ParsePKCS8PrivateKey` but doesn't provide a way to marshal them.  A corresponding `MarshalPKCS8PrivateKey` function would be handy.

**Comment by typeless** [comment] 2017-10-13 03:17
Duplicate of #19972?

**Comment by FiloSottile** [comment] 2018-02-10 02:40
Yep, duplicate of #19972 and fixed by 0a1a65c.

**Closed by FiloSottile** 2018-02-10 02:40 UTC
