### ISSUE TITLE
x/pkgsite: Jump to menu not popping up (on hotkey f) and not searching properly

### ISSUE THREAD

**Issue by gh4n** [golang/go#45462] opened 2021-04-09 02:30 UTC
### What is the URL of the page with the issue?
 https://pkg.go.dev/std

### What is your user agent?
 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36

 
 
### Screenshot
 https://user-images.githubusercontent.com/28796511/114119762-a292b100-992e-11eb-8b9b-48f8211a0a25.mp4

 
 
 
### What did you do?
Two separate things: see video above for screen recording
1.  Pressed `f` 
2. Manually clicked on and queried the `jump to` menu

 
 

### What did you expect to see?

1. Expected to see the `jump to` menu to popup
2. Expected to be navigated to the folder corresponding to my search term
 
 

### What did you see instead?
1. Page stayed static
2. Page stayed static

**Comment by jamalc** [comment] 2021-04-12 17:26
Duplicate of #44718

**Closed by jamalc** 2021-04-12 17:26 UTC
Labels: NeedsInvestigation, pkgsite
