### ISSUE TITLE
archive/tar: should treat empty tar files as invalid

### ISSUE THREAD

**Issue by tomfitzhenry** [golang/go#31012] opened 2019-03-23 04:49 UTC
### What version of Go are you using (`go version`)?
https://play.golang.org/

### What did you do?
https://play.golang.org/p/VeyYROaJQZu

### What did you expect to see?
An error to be printed, similar to how GNU tar produces an error when reading an empty file:
```shell
$ touch empty
$ tar --version
tar (GNU tar) 1.29
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
$ tar tf empty
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

### What did you see instead?
No error printed.

**Comment by dsnet** [comment] 2019-03-23 06:47
`tar` archives lack a unified formal specification of what the format actually is. Though the USTAR and PAX formats specify that an archive *should* end with 2 blocks of zeros, the reality is that this specification came after the world has been doing all sorts of weird things. Most parsers treat the last 2 blocks of zeros as optional for maximal compatibility. This even goes for GNU `tar`, which also treats those blocks as optional. It just so happens that GNU `tar` has a special case where they fail on zero blocks. On the other hand, BSD `tar` seems perfectly happy parsing an empty tar archive.

Personally, I think we should keep the current behavior since an empty file should be valid supposing the trailing 2 blocks of zeros is considered optional. Also, turning an empty file into an error now is likely to break people who have come to depend on this behavior.

**Comment by Gnouc** [comment] 2019-03-23 07:35
For other references, `perl` also treat empty file as valid:

```
perl -MArchive::Tar -e 'my $tar = Archive::Tar->new; $tar->read("./empty")'
```

**Comment by dsnet** [comment] 2019-08-05 17:22
I'm going to close this as working as intended:
1. Had we been implementing `archive/tar` from scratch perhaps we could have treated an empty file as invalid, but that has not be the case since Go 1.0. Changing it may break people relying on this property.
2. Many tar implementations also treat empty file as valid, so we are hardly the exception.

**Closed by dsnet** 2019-08-05 17:22 UTC
Labels: NeedsDecision
