### ISSUE TITLE
Can't load the package syscall/js

### ISSUE THREAD

**Issue by AchalaSB** [golang/go#27749] opened 2018-09-19 09:35 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.11 linux/amd64

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/achala/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/achala/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build813004705=/tmp/go-build -gno-record-gcc-switches"

### What did you do?
I'm running code in webserver but getting an error. 
Even though there is an package error, when I run 
```
GOOS=js GOARCH=wasm go build -o lib.wasm main.go 
```
the lib.wasm file created without any error. And port is opening but the program is not executing.
```
go get syscall/js
can't load package: package syscall/js: build constraints exclude all Go files in /usr/lib/go/src/syscall/js
```

**Comment by davecheney** [comment] 2018-09-19 09:38
go get syscall/js will fail for several reasons

1. it's part of the go distribution, so it cannot be go get'ed.
2. the second line is failing because you didn't say GOOS=js GOARCH=wasm go
get ... (but please don't do this, it won't work)

**Comment by AchalaSB** [comment] 2018-09-19 09:41
I have setted path
"go.testEnvVars": {
        "GOARCH":"wasm",
        "GOOS":"js",
    },
    "go.installDependenciesWhenBuilding": false,
}

**Comment by davecheney** [comment] 2018-09-19 09:49
Is it possible for you to provide more information about your setup sufficient that someone else can try to reproduce the problem you are having?

The more detail you can provide, the better the chances of understanding and reproducing the problem you are having.

**Comment by AchalaSB** [comment] 2018-09-19 09:55
Below is my code 
```
package main

import (
	"flag"
	"log"
	"net/http"
	"syscall/js"
)

var (
	listen = flag.String("listen", ":8080", "listen address")
	dir    = flag.String("dir", ".", "directory to serve")
)

func add(i []js.Value) {
	js.Global().Set("output", js.ValueOf(i[0].Int()+i[1].Int()))
	println(js.ValueOf(i[0].Int() + i[1].Int()).String())

}
func registerCallbacks() {
	js.Global().Set("add", js.NewCallback(add))

}

func main() {
	flag.Parse()
	log.Printf("listening on %q...", *listen)
	log.Fatal(http.ListenAndServe(*listen, http.FileServer(http.Dir(*dir))))
	c := make(chan struct{}, 0)

	println("WASM Go Initialized")
	// register functions
	registerCallbacks()
	<-c
}
```

**Comment by davecheney** [comment] 2018-09-19 10:05
How did you compile this? How did you execute this? What did you see when you did so? 

Please try to give as many details as possible as the wasm support in go 1.11 is very new and not a lot of people have experience with it.

**Comment by AchalaSB** [comment] 2018-09-19 10:08
> Here's code main.go
> 
> ```
> package main
> 
> import (
> 	"flag"
> 	"log"
> 	"net/http"
> 	"syscall/js"
> )
> 
> var (
> 	listen = flag.String("listen", ":8080", "listen address")
> 	dir    = flag.String("dir", ".", "directory to serve")
> )
> 
> func add(i []js.Value) {
> 	js.Global().Set("output", js.ValueOf(i[0].Int()+i[1].Int()))
> 	println(js.ValueOf(i[0].Int() + i[1].Int()).String())
> 
> }
> func registerCallbacks() {
> 	js.Global().Set("add", js.NewCallback(add))
> 
> }
> 
> func main() {
> 	flag.Parse()
> 	log.Printf("listening on %q...", *listen)
> 	log.Fatal(http.ListenAndServe(*listen, http.FileServer(http.Dir(*dir))))
> 	c := make(chan struct{}, 0)
> 
> 	println("WASM Go Initialized")
> 	// register functions
> 	registerCallbacks()
> 	<-c
> }
> ```

**Comment by davecheney** [comment] 2018-09-19 10:16
> Now I have run the the command go run main.go to execute it in server. But getting a package error

Can you please show the exact commands you and and the entire output you got when you ran those commands.

**Comment by AchalaSB** [comment] 2018-09-19 10:36
go run main.go
main.go:7:2: build constraints exclude all Go files in /usr/lib/go/src/syscall/js

**Comment by davecheney** [comment] 2018-09-19 10:41
Thank you. I will have to leave it here as I don’t have much experience with wasm.  

What I will suggest is you need to test the .wasm file you built in the previous step in a javascript environment, I’m guessing a browser. 

go run will not work because it cannot run wasm binaries directly, although it should give a better error than not being able to compile syscall/js because of an unsatisfied build constraint.

**Comment by agnivade** [comment] 2018-09-19 12:07
Yes, please write separate files for the http server and the wasm module. You cannot import "syscall/js" without GOOS=js/GOARCH=wasm, so your main.go cannot be used to serve the files _as well as_ be the wasm module.

For more details, please see this - https://github.com/golang/go/wiki/WebAssembly#example.

Or ask around in the [forums](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Closing since this is not a bug.

**Closed by agnivade** 2018-09-19 12:07 UTC

**Comment by go101** [comment] 2018-09-19 12:33
@AchalaSB have you set the GOROOT env var for earlier Go SDK versions? If true, unset it.

**Comment by AchalaSB** [comment] 2018-09-19 12:38
@agnivade I tried using separate file for wasm module and server. But thing is I cant use 2 different main package in Go right?? Even though I tried server is opened but its not executing my code

**Comment by AchalaSB** [comment] 2018-09-19 12:39
@go101 No I didnn't set GOROOT env

**Comment by go101** [comment] 2018-09-19 12:50
You don't need to maintain the http server code, please install `golf` instead:
```
go install github.com/tapirliu/golf
```

then run `golf` in the wasm folder to serve your static files.

**Comment by AchalaSB** [comment] 2018-09-19 12:55
go install github.com/tapirliu/golf
```
can't load package: package github.com/tapirliu/golf: cannot find package "github.com/tapirliu/golf" in any of:
        /usr/lib/go/src/github.com/tapirliu/golf (from $GOROOT)
        /home/achala/go/src/github.com/tapirliu/golf (from $GOPATH)
```

**Comment by agnivade** [comment] 2018-09-19 14:56
>  But thing is I cant use 2 different main package in Go right??

Yes you can. Please take this to the forums. https://github.com/golang/go/wiki/Questions

Thank you.
