### ISSUE TITLE
x/website: out of date requirements for macos

### ISSUE THREAD

**Issue by casatwy** [golang/go#68891] opened 2024-08-15 11:08 UTC
### What is the URL of the page with the issue?
 https://go.dev/dl/
 
 
### What is your user agent?
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 
### Screenshot

they are same packages.
 I downloaded the Apple X86-64 package, and failed to install golang in my Max OS X 10.15.7

<img width="472" alt="截屏2024-08-15 19 01 44" src="https://github.com/user-attachments/assets/8a71fca6-a967-4254-bd24-7170d7ce2516">

<br />

<img width="273" alt="截屏2024-08-15 19 03 06" src="https://github.com/user-attachments/assets/ee2f500f-a8e2-4361-b25f-56373d9a95ef">
 
### What did you do?
 try to install golang but failed.

### What did you expect to see?
download the right package to install golang in Mac OS X 10.15.7
 
 
 
### What did you see instead?
failed to install golang 1.23 with downloaded install package

**Comment by seankhliao** [comment] 2024-08-15 14:45
macos 11 is required, see #64207

**Comment by cagedmantis** [comment] 2024-08-15 14:50
As @seankhliao mentioned. macos 11 is required for Go 1.23. This is working as intended.

**Comment by cagedmantis** [comment] 2024-08-15 20:24
I closed this without the website being updated. Apologies for that.

**Closed** 2024-08-15 20:25 UTC
Labels: NeedsFix, website, FixPending
