### ISSUE TITLE
x/tools/gopls: show hex/binary literal with which a const was declared on mouse over

### ISSUE THREAD

**Issue by soypat** [golang/go#47453] opened 2021-07-29 00:42 UTC
### What did you do?

Mouse over a hex/binary notation integer 
```go
const hex, bin, oct = 0xe34e, 0b10101, 071

// Mouse over variable name `hex` or `bin` shows decimal representation
c := hex * bin
```

### What did you expect to see?
The literal used to declare the `const`. Usually when one declares a const in hex, binary or octal representation it carries with it a significance, to aid the reader of the code. If we wrote programs for machines `gofmt` would convert these literals to decimals or whatever the computer like. 

With the philosophy out of the way, I expected to see:
* `const hex untyped int = 0xe34e   (58190)`
*  `const bin untyped int = 0b10101  (21)`.

### What did you see instead?
The usual `gopls` help string of 
* `const hex untyped int = 58190`
*  `const bin untyped int = 21`.

**Comment by hyangah** [comment] 2021-07-29 18:32
Isn't it a duplicate of #45802? Can you please check if the fix in golang.org/x/tools/gopls@v0.7.1-pre.1 meets what you want?

**Comment by soypat** [comment] 2021-07-29 22:37
@hyangah negative. The issues are similar in nature though. I'm not asking for literal evaluation but rather that gopls show me how the author initialized a const integer since there are around 5 ways of initializing the same number and usually non-decimal form carries useful information about certain bits (i.e. bitfields, masks)

**Comment by soypat** [comment] 2023-03-19 23:03
Hey there! I'd like to bump this issue. This is something I regularly run into. I use Go for firmware/embedded systems and hexadecimals plague my code. It'd be really nice to get this mouse-over information

**Comment by soypat** [comment] 2023-03-19 23:06
I wonder, to me it would suffice if the decimal representation was shown next to a hexadecimal representation. This is similar to how `time.Duration` is displayed on mouse hover:
```go
const time.Millisecond time.Duration = 1000000 // 1ms
```

**Comment by findleyr** [comment] 2023-03-29 13:16
@ShoshinNikita first of all, I'm very sorry about https://go.dev/cl/381961, which appears to have gotten stuck in limbo.  If you would be interested in seeing this through, we would greatly appreciate the contribution. You can send the CL to me and I'll be sure to get it in expediently.

Yes, I had to refactor hover to disentangle the places where we depended on implicit relationships between packages or parsed files (so that we can break these relationships to improve gopls' scaling). I hope that it is easier to contribute to now, so please let me know if you find otherwise.

If you want to put the logic into the const block of objectString, that's OK. I'll eventually get around to that TODO. That TODO means this: objectString looks almost entirely like types.ObjectString, except when it doesn't: when the object is a const or when the type has inferred arguments (and the latter only occurs at one call site). It would be simpler to avoid the abstraction and just handle the special case(s) at the call site. Specifically, I think we'd just need to handle the const case in the one location where we format a general object string ([here](https://cs.opensource.google/go/x/tools/+/master:gopls/internal/lsp/source/hover.go;l=171?q=f:hover.go&ss=go%2Fx%2Ftools)).

But as I said, it would be fine if you just modify the const case of objectString.

**Comment by ShoshinNikita** [comment] 2023-03-30 20:54
@findleyr no problem. The original PR was too outdated. So, I decided to create a new one - https://go.dev/cl/480695

**Comment by soypat** [comment] 2023-03-31 02:20
Just curious: how would it render a constant made out of other constants and literals?

**Comment by ShoshinNikita** [comment] 2023-03-31 06:22
@soypat as it was declared:

```go
const shift untyped int = 64 - 11 - 1 // 52

const fracMask untyped int = 1<<shift - 1 // 4503599627370495
```

**Closed** 2023-04-05 17:49 UTC
Labels: help wanted, FeatureRequest, gopls, Tools
