### ISSUE TITLE
runtime: fail nicely on start-up on softfloat mips systems if binary built with GOMIPS=hardfloat (the default) 

### ISSUE THREAD

**Issue by dtodor** [golang/go#23614] opened 2018-01-30 10:09 UTC
We have a problem running a simple Go program on a MIPS target with the following FPU configuration:
```
CONFIG_MIPS_FPU_EMULATOR=n
CONFIG_CPU_R4K_FPU=y
```

On the same target with the CONFIG_MIPS_FPU_EMULATOR enabled, the program runs as expected. My understanding is that the latest release Go compiler only supports hard-float on MIPS, with soft-float implemented in go1.10RC1. Is this correct?

### What version of Go are you using (`go version`)?
The following Go versions have been tested:
go1.8.3
go1.9.3
go1.10RC1

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?
The program is built on OS X:

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/***/Development/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/49/p0474r8s3330n15jxw8n65fw0000gp/T/go-build208700080=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

The target is MIPS32 big endian (GRX550).

### What did you do?

Build and run the following sample program: https://play.golang.org/p/XHRe6Hv6Jeb

Build instructions:
```
GOOS=linux GOARCH=mips go build -a -o info
```

### What did you expect to see?
The output of the program, e.g.:

```
./info
GOOS: linux
GOARCH: mips
Compiler: gc
Version: go1.8.3
No. of CPU: 2
```

### What did you see instead?
The program immediately terminates:

```
./info
Segmentation fault
```

**Comment by vstefanovic** [comment] 2018-01-30 14:16
Looks like you're missing GOMIPS=softfloat. (Default is hardfloat.)

**Comment by cherrymui** [comment] 2018-01-30 19:57
I'm a little surprised that it is segmentation fault instead of illegal instruction.

Either way, I agree that it would be nice to print a nicer error message. On ARM, we do this by querying the HWCAP bits at startup, and see if the GOARM value is compatible with HWCAP. On MIPS, it seems no HWCAP bit for whether it has FPU. Is there something we can query without trapping?

**Comment by dtodor** [comment] 2018-01-30 21:11
I'm pretty sure we tested the GOMIPS=softfloat with the go1.10RC1 compiler without much success. We found the relevant information about the soft-float support on MIPS in this issue: #18162.

**Comment by crvv** [comment] 2018-01-31 02:35
I can't reproduce this issue.
If I build it with `GOMIPS=hardfloat`, it will fail with `Illegal instruction`, not `Segmentation fault`.

```
Linux LEDE 4.4.89 #0 Sat Sep 30 18:37:33 2017 mips GNU/Linux
Atheros AR9344 rev 2
MIPS 74Kc V4.12
```

**Comment by dtodor** [comment] 2018-01-31 08:34
OK, I can verify that ```GOMIPS=softfloat``` doesn't work on the target:

```
GOOS=linux GOARCH=mips GOMIPS=softfloat go1.10rc1 build -a
```

The result of executing the binary is again a segmentation fault. Our partners have built a kernel with ```CONFIG_MIPS_FPU_EMULATOR=y```, which results in binaries built with the 1.9.3 Go compiler without specifying ```GOMIPS``` to work without a problem. My guess is that there is a problem with the softfloat MIPS implementation in Go 1.10RC1.

**Comment by dtodor** [comment] 2018-01-31 11:55
A follow-up: we have compiled the sample project with a custom build of GCCGO. The binary still uses hard-float, but now we get the "correct" error message: ```Illegal instruction``` instead of ```Segmentation fault```.

**Comment by vstefanovic** [comment] 2018-01-31 21:28
I also cannot reproduce this - GOMIPS=softfloat is working, GOMIPS=hardfloat brings illegal instruction.
@dtodor, do you have any other info; can you catch the segfault with gdb?

**Comment by dtodor** [comment] 2018-02-01 08:10
We've attached a gdb to the target and run the program. Unfortunately, the debugger outputs:
```not in executable format: File format not recognized```

This probably means that the Go compiler cannot produce a valid executable for the target. This would explain the ```Segmentation fault```. Using the custom built GCCGO compiler, the debugger runs and catches the ```Illegal instruction```. Maybe the current firmware on the target is somehow "special". The weird thing is that enabling ```CONFIG_MIPS_FPU_EMULATOR ``` in the kernel solves the problem. This has been verified by our partners, who provide us with the firmware.

Unfortunately we have to flash the new firmware onto the device and thus cannot do any further testing of this issue.

**Comment by ianlancetaylor** [comment] 2018-07-09 23:50
As far as I can tell, only @dtodor was able to recreate the problem, and that is no longer possible.  So, closing.  Please comment if you disagree.

**Closed by ianlancetaylor** 2018-07-09 23:50 UTC
Labels: NeedsFix, help wanted
