### ISSUE TITLE
html/template: genereates broken result when there is JS string interpolation

### ISSUE THREAD

**Issue by wxiaoguang** [golang/go#55341] opened 2022-09-22 08:54 UTC
### What version of Go are you using (`go version`)?

Not only the latest one, I think it's an old bug.

<pre>
$ go version
go version go1.19.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

N/A

### What did you do?

https://go.dev/play/p/SyukPDzcZ6a

```
func main() {
	t := template.New("a")
	_, _ = t.Parse("<script>a=`//`</script>")
	w := &bytes.Buffer{}
	_ = t.Execute(w, nil)
	b, _ := io.ReadAll(w)
	println(string(b))
}
```

### What did you expect to see?

Correct result:

```
<script>a=`//`</script>
```

### What did you see instead?

Broken result:

```
<script>a=`</script>
```

**Comment by seankhliao** [comment] 2022-09-22 16:41
Duplicate of #9200

**Closed by seankhliao** 2022-09-22 16:41 UTC
