### ISSUE TITLE
Windows installer still using http://golang.org instead of https://go.dev

### ISSUE THREAD

**Issue by DevDengChao** [golang/go#60715] opened 2023-06-10 04:05 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.20.5
</pre>

### Does this issue reproduce with the latest release?

yes

![image](https://github.com/golang/go/assets/16363180/b603e1a7-de52-4eb7-bdd7-1cd9dbab7aaf)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
Not related.

### What did you do?

1. download a msi installer from https://go.dev/dl/
2. open the installer and you'll see it.

### What did you expect to see?

the website on the left should be https://go.dev

### What did you see instead?

As you can see above.

**Comment by dmitshur** [comment] 2023-06-10 06:11
Thanks for reporting. This is a duplicate of #57413.

**Closed by dmitshur** 2023-06-10 06:11 UTC
