### ISSUE TITLE
cmd/cgo: regression in Go1.12beta2 causes "unexpected semicolon, expecting expression" error

### ISSUE THREAD

**Issue by rjeczalik** [golang/go#30117] opened 2019-02-07 07:11 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12beta2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

No (tested `go version go1.11.5 darwin/amd64`).

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/rjeczalik/bin"
GOCACHE="/Users/rjeczalik/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Volumes/rjk.io/work"
GOPROXY=""
GORACE=""
GOROOT="/Users/rjeczalik/go"
GOTMPDIR=""
GOTOOLDIR="/Users/rjeczalik/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dl/s7jq4vyn7358p1mtsmn3bk5w0000gn/T/go-build100527020=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
$ cat main.go
```
```go
package main

// #include <CoreServices/CoreServices.h>
// typedef void (*CFRunLoopPerformCallBack)(void*);
// #cgo LDFLAGS: -framework CoreServices
import "C"

var eventloop = C.CFRunLoopSourceCreate(C.kCFAllocatorDefault, 0, &C.CFRunLoopSourceContext{
	perform: (C.CFRunLoopPerformCallBack)(nil),
})

func main() {}
```
```
go build
```

### What did you expect to see?

```
```

### What did you see instead?

```
# _/Users/rjeczalik/src/bug
./main.go:8:86: syntax error: unexpected semicolon, expecting expression
```

**Comment by odeke-em** [comment] 2019-02-07 08:01
Thank you for reporting this issue @rjeczalik!

I shall kindly page @ianlancetaylor.

**Comment by AlexRouSg** [comment] 2019-02-07 08:12
Lighter OS agnostic repo that I confirmed still happens on tip hash aa161ad17e65df8f615f25c5dca84e505a8c8315
```
package main

/*
typedef void (*CFRunLoopPerformCallBack)(void*);

typedef struct {
	CFRunLoopPerformCallBack perform;
}CFRunLoopSourceContext;

#define kCFAllocatorDefault 1

void CFRunLoopSourceCreate(int a, int b, CFRunLoopSourceContext* c) {}
*/
import "C"

var eventloop = C.CFRunLoopSourceCreate(C.kCFAllocatorDefault, 0, &C.CFRunLoopSourceContext{
	perform: (C.CFRunLoopPerformCallBack)(nil),
})

func main() {}

```

**Comment by ianlancetaylor** [comment] 2019-02-07 20:57
@AlexRouSg The updated version does build for me, and this looks like the same problem as #29781, which is fixed on tip.  Can you double check that you used the tip version of cgo?  Thanks.

**Comment by AlexRouSg** [comment] 2019-02-07 21:13
@ianlancetaylor yup did a fresh git clone and build with hash 7ccd3583eddcd79679fb29cfc83a6e6fb6973f1e

```
PS C:\Users\alexr\go\src\test> c:/Go-tip/bin/go.exe version
go version devel +7ccd3583ed Thu Feb 7 18:34:43 2019 +0000 windows/amd64
PS C:\Users\alexr\go\src\test> c:/Go-tip/bin/go.exe run .
# test
.\test.go:16:86: syntax error: unexpected semicolon, expecting expression
```

Not sure if it matters but I'm on windows amd64

**Comment by AlexRouSg** [comment] 2019-02-07 21:22
*facepalm* I forgot to set goroot

**Comment by ianlancetaylor** [comment] 2019-02-08 00:49
Thanks for testing.  I'm going to close this as fixed on tip.  Thanks for reporting the problem.

**Closed by ianlancetaylor** 2019-02-08 00:49 UTC
Labels: NeedsInvestigation
