### ISSUE TITLE
gccgo: go1: internal compiler error: in operator(), at go/gofrontend/dataflow.cc:225 with -fgo-optimize-allocs

### ISSUE THREAD

**Issue by laboger** [golang/go#12965] opened 2015-10-16 21:12 UTC
When building Docker with gccgo based on gcc trunk using the -fgo-optimize-allocs option, the compile fails with an internal compiler error.  Failure does not occur if the -fgo-optimize-allocs is not used.  Same failure happens if built on (f20 or rhel 6.6) x86 or (Ubuntu 14.10) ppc64le.  

Failure looks like this:
go1: internal compiler error: in operator(), at go/gofrontend/dataflow.cc:225
0x5d4d7f Dataflow::Compare_vars::operator()(Named_object const_, Named_object const_) const
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/dataflow.cc:225
0x5d52c2 std::_Rb_tree<Named_object*, std::pair<Named_object* const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >_>, std::_Select1st<std::pair<Named_object_ const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >_> >, Dataflow::Compare_vars, std::allocator<std::pair<Named_object_ const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >_> > >::_M_get_insert_unique_pos(Named_object_ const&)
    /usr/include/c++/4.8.3/bits/stl_tree.h:1324
0x5d52c2 std::_Rb_tree<Named_object*, std::pair<Named_object* const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >_>, std::_Select1st<std::pair<Named_object_ const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >_> >, Dataflow::Compare_vars, std::allocator<std::pair<Named_object_ const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >_> > >::_M_insert_unique(std::pair<Named_object_ const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >_> const&)
    /usr/include/c++/4.8.3/bits/stl_tree.h:1377
0x5d52c2 std::map<Named_object_, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >_, Dataflow::Compare_vars, std::allocator<std::pair<Named_object_ const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >_> > >::insert(std::pair<Named_object_ const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >_> const&)
    /usr/include/c++/4.8.3/bits/stl_map.h:595
0x5d52c2 Dataflow::add_ref(Named_object_, Statement_)
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/dataflow.cc:269
0x5d5420 Dataflow_traverse_expressions::expression(Expression__)
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/dataflow.cc:65
0x5e56bd Expression::traverse(Expression__, Traverse_)
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/expressions.cc:43
0x5f0708 Expression_list::traverse(Traverse_)
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/expressions.cc:14913
0x5f0759 Call_expression::do_traverse(Traverse_)
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/expressions.cc:8610
0x5d4c58 Dataflow_traverse_statements::statement(Block_, unsigned long_, Statement_)
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/dataflow.cc:187
0x652fe4 Statement::traverse(Block_, unsigned long_, Traverse_)
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/statements.cc:44
0x61738d Block::traverse(Traverse_)
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/gogo.cc:5821
0x61738d Block::traverse(Traverse_)
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/gogo.cc:5821
0x6175ce Function::traverse(Traverse_)
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/gogo.cc:4923
0x619e9e Bindings::traverse(Traverse_, bool)
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/gogo.cc:7604
0x61a171 Gogo::traverse(Traverse_)
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/gogo.cc:2519
0x5d4e58 Dataflow::initialize(Gogo_)
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/dataflow.cc:241
0x5d669c Build_connection_graphs
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/escape.cc:429
0x5d669c Gogo::build_connection_graphs()
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/escape.cc:1386
0x5d9aeb Gogo::optimize_allocations(char const**)
    /home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/escape.cc:1653
Please submit a full bug report,
......

Error occurs with Docker 1.6.2 and 1.9.0-dev.

I will provide information on a compile command that will reproduce the error but I am still working on that.

**Comment by laboger** [comment] 2015-10-21 12:51
Unfortunately this is not simple to reproduce.  It requires set up of the Docker build.  Do you want that information or is there some other way to provide the information you need to debug this?

**Comment by laboger** [comment] 2015-10-21 19:36
The same failure (with a slightly different stack at the bottom) occurs when building libgo if -fgo-optimize-allocs is used on x86 as well as ppc64le.

Checkout gcc trunk, build libgo adding the -fgo-optimize-allocs option.
Or, if gccgo from gcc trunk is already built, the compile command fails on x86 f20 distro like this:

cd src/libgo/go/compress/lzw
gccgo -c -o x.o reader.go writer.go -fgo-optimize-allocs
go1: internal compiler error: in operator(), at go/gofrontend/dataflow.cc:225
0x5d4d7f Dataflow::Compare_vars::operator()(Named_object const*, Named_object const*) const
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/dataflow.cc:225
0x5d52c2 std::_Rb_tree<Named_object*, std::pair<Named_object* const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >*>, std::_Select1st<std::pair<Named_object* const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >*> >, Dataflow::Compare_vars, std::allocator<std::pair<Named_object* const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >*> > >::_M_get_insert_unique_pos(Named_object* const&)
	/usr/include/c++/4.8.3/bits/stl_tree.h:1324
0x5d52c2 std::_Rb_tree<Named_object*, std::pair<Named_object* const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >*>, std::_Select1st<std::pair<Named_object* const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >*> >, Dataflow::Compare_vars, std::allocator<std::pair<Named_object* const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >*> > >::_M_insert_unique(std::pair<Named_object* const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >*> const&)
	/usr/include/c++/4.8.3/bits/stl_tree.h:1377
0x5d52c2 std::map<Named_object*, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >*, Dataflow::Compare_vars, std::allocator<std::pair<Named_object* const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >*> > >::insert(std::pair<Named_object* const, std::vector<Dataflow::Ref, std::allocator<Dataflow::Ref> >*> const&)
	/usr/include/c++/4.8.3/bits/stl_map.h:595
0x5d52c2 Dataflow::add_ref(Named_object*, Statement*)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/dataflow.cc:269
0x5d5420 Dataflow_traverse_expressions::expression(Expression**)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/dataflow.cc:65
0x5e56bd Expression::traverse(Expression**, Traverse*)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/expressions.cc:43
0x5f0708 Expression_list::traverse(Traverse*)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/expressions.cc:14913
0x5f0759 Call_expression::do_traverse(Traverse*)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/expressions.cc:8610
0x5d549e Dataflow_traverse_assignment::value(Expression**, bool, bool)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/dataflow.cc:142
0x650717 Assignment_statement::do_traverse_assignments(Traverse_assignments*)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/statements.cc:563
0x5d4c06 Dataflow_traverse_statements::statement(Block*, unsigned long*, Statement*)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/dataflow.cc:175
0x652fe4 Statement::traverse(Block*, unsigned long*, Traverse*)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/statements.cc:44
0x61738d Block::traverse(Traverse*)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/gogo.cc:5821
0x61738d Block::traverse(Traverse*)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/gogo.cc:5821
0x61738d Block::traverse(Traverse*)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/gogo.cc:5821
0x6175ce Function::traverse(Traverse*)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/gogo.cc:4923
0x619e9e Bindings::traverse(Traverse*, bool)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/gogo.cc:7604
0x61a171 Gogo::traverse(Traverse*)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/gogo.cc:2519
0x5d4e58 Dataflow::initialize(Gogo*)
	/home/boger/gccgo.work/trunk/bld/../src/gcc/go/gofrontend/dataflow.cc:241
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.

**Comment by paranoiacblack** [comment] 2015-10-22 21:48
Thanks for the extra information. I suppose I should say this is a long-standing problem I encountered when implementing escape analysis. The dataflow class was not being used previously, and I stole it for the purposes of escape analysis. The implementation is already not up-to-date and using it with escape analysis puts pressure on those fragile parts. I plan to clean up the majority of the escape analysis code to make it fit the code around it in the following months.

As an aside, is there a particular project that you need escape analysis in gccgo for (that you can mention)? If so, I'd like to work with you to make sure the implementation fits your needs. It is 100% untested in the wild and the results within the stdlib are inconclusive. I'd like those last two statements to be incorrect in the near future.

**Comment by laboger** [comment] 2015-10-23 12:38
This was mainly an experiment to see if this option worked and how much 
it helped when building Docker on ppc64le.

Thanks

**Comment by laboger** [comment] 2015-10-27 14:01
Thanks!  I'll try it.

**Comment by laboger** [comment] 2015-10-29 19:23
This change has fixed the build errors but there appear to be some runtime errors now, mainly SEGVs.  I am working on some other things right now but will work on reproducers and post them.

**Comment by paranoiacblack** [comment] 2015-10-29 19:35
That sounds correct. These runtime errors will be due to the analysis marking variables as non-escaping and using a stack address where there should have been a heap address. With the patch in mind, it is likely that there are two indistinguishable variables which should share the same escape information and it leads to one being marked as non-escaping incorrectly. If you find reproducers, it would be very useful in helping me fine-tune this algorithm and we can put them in the testsuite to check for future regressions. Thanks again.

**Comment by laboger** [comment] 2015-11-03 21:39
Here's one way I generated errors:

I applied your patch and also this patch to force escape analysis to always be enabled:

Index: gcc/go/gofrontend/escape.cc
===================================================================
--- gcc/go/gofrontend/escape.cc	(revision 229720)
+++ gcc/go/gofrontend/escape.cc	(working copy)
@@ -1640,7 +1640,7 @@
 void
 Gogo::optimize_allocations(const char** filenames)
 {
-  if (!::optimize_allocation_flag.is_enabled() || saw_errors())
+  if (saw_errors())
     return;
 
   // Build call graph for this program.

Then I built gccgo and ran the libgo testsuite.  The tests go/types and net/http fail if this flag is always enabled.

To run them all I did:
>make check-target-libgo

I did this experiment on x86.

**Comment by laboger** [comment] 2015-11-17 15:30
Is there any update on this?

**Comment by paranoiacblack** [comment] 2015-11-17 16:13
No official updates, just some experiments to fix this the right way. By traversing interesting statements such as function calls, assignments, declarations, etc, the connectivity of the objects in each function is easier to discover. The current approach looks at every variable and then uses the information gained from the dataflow analysis to similarly find calls, assignments, etc. It is also imprecise about field accesses which makes the analysis conservative in many places where it should not be.

Currently, I'm trying to get the analysis working without the current dataflow analysis. Afterwards, I will be focusing on the precision of the algorithm to make sure nothing in the stdlib fails.

**Comment by laboger** [comment] 2015-12-07 13:59
Anything new on this one?

**Comment by paranoiacblack** [comment] 2015-12-07 19:15
Yes. The current plans are to drop support for the current implementation of escape analysis in gccgo; instead, we will be implementing the algorithm expressed in the Go compiler (gc/esc.go). This implementation will not need the dataflow analysis, either, and that analysis will be removed from the compiler. This re-implementation will not added to the gofrontend source until it is verified to pass all stdlib tests to avoid situations like this in the future.

**Comment by laboger** [comment] 2015-12-09 11:43
Will this new implementation make it into gccgo so it can be part of the release for gcc 6.0?

**Comment by ianlancetaylor** [comment] 2015-12-09 19:20
We don't know.

**Comment by laboger** [comment] 2016-02-03 13:52
Any update on whether this might get into gcc 6?

**Comment by paranoiacblack** [comment] 2016-02-04 01:12
I'm going to say no. The implementation isn't close to being done. You can follow all the related changes from here: https://go-review.googlesource.com/#/c/18261/.

**Comment by laboger** [comment] 2016-09-06 16:31
I know there was work done on this and much of it merged upstream.  Is escape analysis enabled by default or does it require a flag?

**Comment by ianlancetaylor** [comment] 2016-09-07 17:29
There are no pending analysis escape analysis changes.  You still need to pass a flag (`-fgo-optimize-allocs`) to enable it.  It has not been seriously tested.  I hope to have time to do that before the GCC 7 release, and I would encourage you or anybody to try it our yourself and report bugs.

**Comment by ianlancetaylor** [comment] 2018-02-05 03:05
This is fixed now.

**Closed by ianlancetaylor** 2018-02-05 03:05 UTC
Labels: Thinking
