### ISSUE TITLE
runtime: special case timer channels

### ISSUE THREAD

**Issue by dvyukov** [golang/go#8898] opened 2014-10-07 13:45 UTC
<pre>Consider special-casing timer channels created with time.Ticker and time.After.
Namely, such chans need to contain next fire time and period. Then receive from such
looks like:

func chanrecv(c *Hchan) {
  ...
  if c.isTimeChan {
    for {
      next := c.nextTime
      if next == -1 {
        // already fired one-time timer
        blockForever()
      }
      newTime := -1
      if c.period != 0 {
        newTime = next + c.period
      }
      if CAS(&amp;c.nextTime, next, newTime) {
        wait := next - now
        if wait &gt; 0 {
          sleepFor(wait)
        }
        return
      }
    }
  }
  ...
}

This has several advantages:
1. No need to stop timers. If nobody waits on a timers, it's just a normal heap object
that can be garbage collected.
2. Faster operation for both blocking and non-blocking case.
3. Faster selects involving time chans.
4. Can combine time.Ticker/After into a single allocation.</pre>

**Comment by bradfitz** [comment] 2015-04-02 07:47
Comments about this bug are in https://go-review.googlesource.com/#/c/8356/

**Comment by rsc** [comment] 2016-03-18 20:10
I intend to look into this for Go 1.7. I've started work on a CL.

**Comment by dvyukov** [comment] 2016-03-18 20:50
Note there is a caveat: if we have code like:
```
t := time.NewTimer(time.Munute)
for {
  select {
  case <-t.C:
  case ...
  }
}
```
Currently we arm and install the timer once. If we special case timer channels, we will need to install and uninstall the timer for each select.
Or do you have some smart plan for this?

**Comment by quentinmit** [comment] 2016-09-30 21:00
@rsc is this going to make 1.8?

**Comment by gyf19** [comment] 2016-10-18 00:23
@dvyukov @rsc ping？

**Comment by rsc** [comment] 2016-10-20 13:23
Did not get to this.

**Comment by bcmills** [comment] 2016-11-07 22:14
> 1. No need to stop timers. If nobody waits on a timers, it's just a normal heap object
that can be garbage collected.

That seems like a disadvantage, not an advantage: it would encourage writing non-portable Go code (that is, programs which appear to work when using the `gc` compiler but leak memory when compiled with other implementations).

Unless you're proposing to make a corresponding language change, in which case this seems like it needs to be a full-fledged proposal.

> 4. Can combine time.Ticker/After into a single allocation.

There is a more general version of this optimization which we might want to consider anyway.  If we:
* have a struct with a pointer or reference-type field, and
* can detect at compile-time that the referent of that field never changes (because it is not exported and never reassigned in methods), and
* heuristically believe that the struct and referent always or almost always have the same lifetime (e.g. because the struct contains unexported fields, has only pointer methods, and is always returned by pointer),

then we can (and arguably should) combine the struct and the referent into a single allocation.

That optimization is more or less orthogonal to any special-casing for timer channels in `select`.

**Comment by rsc** [comment] 2023-07-23 20:15
This is now a duplicate of #61542.

**Closed by rsc** 2023-07-23 20:15 UTC
Labels: Performance, NeedsFix, FrozenDueToAge, early-in-cycle

**Comment by rsc** [comment] 2024-03-13 21:54
Submitted the CL! 
From "I intend to look into this for Go 1.7. I've started work on a CL." to submitted, just a smidge less than 8 years!
