### ISSUE TITLE
cmd/go: 1.18 fails when vendoring and main module replaces itself

### ISSUE THREAD

**Issue by zhsj** [golang/go#51285] opened 2022-02-20 19:49 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18rc1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/zhsj/.cache/go-build"
GOENV="/home/zhsj/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/zhsj/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/zhsj/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/lib/go-1.18"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18rc1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/zhsj/go/src/github.com/containerd/containerd/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2918392435=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

1. git clone https://github.com/containerd/containerd
2. run `go list` in root dir

### What did you expect to see?

Like go1.17, it succeeds with:

```
zhsj@debian:~/go/src/github.com/containerd/containerd$ /usr/lib/go-1.17/bin/go list
github.com/containerd/containerd
```

### What did you see instead?

```
zhsj@debian:~/go/src/github.com/containerd/containerd$ go list
go: inconsistent vendoring in /home/zhsj/go/src/github.com/containerd/containerd:
        github.com/containerd/containerd: is marked as replaced in vendor/modules.txt, but not replaced in go.mod

        To ignore the vendor directory, use -mod=readonly or -mod=mod.
        To sync the vendor directory, run:
                go mod vendor
```

**Comment by seankhliao** [comment] 2022-02-20 20:11
related #34417

simpler reproducer:
```
-- go.mod --
module go.seankhliao.com/testrepo-791

go 1.18

replace go.seankhliao.com/testrepo-791 => ./.empty

-- .empty/go.mod
module go.seankhliao.com/testrepo-791

go 1.18
```
results:
```
$ go list
no Go files in /home/arccy/tmp/testrepo-791

$ go mod vendor
go: warning: "all" matched no packages

$ go list      
go: inconsistent vendoring in /home/arccy/tmp/testrepo-791:
	go.seankhliao.com/testrepo-791: is marked as replaced in vendor/modules.txt, but not replaced in go.mod

	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor
```

cc @bcmills @matloob

**Comment by bcmills** [comment] 2022-02-22 16:38
Duplicate of #34417

**Closed by bcmills** 2022-02-22 16:38 UTC
Labels: NeedsInvestigation, GoCommand
