### ISSUE TITLE
bootstrap: cmd/dist/test.go prevents all.bash from suceeding on slow machines via fixed timeout

### ISSUE THREAD

**Issue by drhpc** [golang/go#50130] opened 2021-12-13 10:56 UTC
### What version of Go are you using (`go version`)?

1.17.4 (trying to build it)

### Does this issue reproduce with the latest release?

I checked the current source on github and the issue is still present.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.15"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.15/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build158095017=/tmp/go-build -gno-record-gcc-switches"
$ /root/inst/go-1.17.4/bin/go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/root/inst/go-1.17.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/inst/go-1.17.4/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build884916083=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I set up a Debian 11 vm using qemu without kvm, as this is an experiment in doing things without any special privileges. Host CPU is a Haswell Xeon (8 cores per socket in two sockets). This is slower than KVM, of  course.

In that Debian 11 VM, I tried to build go1.17.4 to be able to build the actual software I was interested in (since go1.15 wasn't enough for it). Since the tests would timeout due to the fixed value in cmd/dist/test.go, the build always failed. First with one core, then also with `-smp 4`.

```
set -e
wget https://go.dev/dl/go1.17.4.src.tar.gz
mkdir go-1.17.4
cd go-1.17.4
tar -xf ../go1.17.4.src.tar.gz
cd go
cd src
# do that to fix build
# perl -pi -e 's,timeoutSec := 180$,timeoutSec := 1800,' cmd/dist/test.go
GOROOT_FINAL=/root/inst/go-1.17.4 ./all.bash 2>&1 | tee build.log
cd ../..
mv go /root/inst/go-1.17.4
```
When I uncomment the perl one-liner, the build succeeds. Summing over all reported test runtimes yields 5652 seconds.

### What did you expect to see?

Finished build after running `./all.bash`.

### What did you see instead?

Test failures due to 9-minute timeout.

I think such a fixed arbitrary timeout in the code is a literal time bomb that one should avoid. Maybe it could be replaced by some very conservative heuristic. One also should be able to turn it off  — or rather, turn it _on_. This timeout looks like a QA measure for automatic builds, not something to ship to anyone just wanting a one-off build of golang.

**Comment by seankhliao** [comment] 2021-12-13 10:59
I believe that;s what the `GO_TEST_TIMEOUT_SCALE` setting is for

**Comment by drhpc** [comment] 2021-12-13 11:01
Can this disable it altogether?

**Comment by seankhliao** [comment] 2021-12-13 11:49
Duplicate of #19508

Timeouts are useful for catching no progress, it seems clear that if you want it to potentially run forever, just set the very high scale. Note, all `go test` invocations have timeouts too.

**Closed by seankhliao** 2021-12-13 11:49 UTC
