### ISSUE TITLE
cmd/compile: Go 1.20 recognizes `clear` built-in and panics

### ISSUE THREAD

**Issue by dominikh** [golang/go#61326] opened 2023-07-12 22:11 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
`go run` the following file:

```
package main

func main() {
	clear(([]int)(nil))
}
```

### What did you expect to see?
An error indicating that `clear` isn't defined, or that it needs Go 1.21

### What did you see instead?
```
./foo.go:3:6: internal compiler error: panic: interface conversion: interface is nil, not ir.Node
```

When building a package in a module, instead of specifying a file, Go correctly reports that `clear` needs Go 1.21 if the Go version in go.mod is set to 1.20.  However, if go.mod specifies 1.21, the same panic occurs.

**Comment by ianlancetaylor** [comment] 2023-07-12 23:02
CC @mdempsky

**Comment by mdempsky** [comment] 2023-07-12 23:15
Duplicate of #61074.

**Closed by mdempsky** 2023-07-12 23:15 UTC
Labels: compiler/runtime
