### ISSUE TITLE
Issue in switch statements

### ISSUE THREAD

**Issue by bigkraig** [golang/go#19665] opened 2017-03-23 01:17 UTC
### What version of Go are you using (`go version`)?
1.8

### What operating system and processor architecture are you using (`go env`)?
darwin/amd64

### What did you do?
https://play.golang.org/p/N7GpGDqxJL

Depending on the cases in my switch statement, I get different output.

### What did you expect to see?

```
First switch
m["key"] == "val"
m["key"] == "val"
Second switch
m["key"] == "val"
```

### What did you see instead?

```
First switch
m["key"] == "val"
m["key"] == ""
m["key"] == "val"
Second switch
m["key"] == "val"
```

**Comment by davecheney** [comment] 2017-03-23 01:23
This is working as intended, the reason you get this is
```
case m["key"] == "val":
fmt.Println(`m["key"] == "val"`)
fallthrough
case m["key"] == "":
fmt.Println(`m["key"] == ""`)
fallthrough
case m["key"] == "val":
fmt.Println(`m["key"] == "val"`)
```
When the first case fires, it prints, then falls through to the second
case, which prints, then falls through to the last case.

I'm going to close this issue as it is not a bug and we generally do not
encourage support questions in issues. Please see
https://github.com/golang/go/wiki/questions for some suggested place to ask
questions about writing Go code.

**Comment by bradfitz** [comment] 2017-03-23 01:23
Yes, that's working as intended, per the spec.

See
https://golang.org/ref/spec#Switch_statements
https://golang.org/ref/spec#Fallthrough_statements

For questions about Go, see https://golang.org/wiki/Questions.

**Closed by bradfitz** 2017-03-23 01:23 UTC
