### ISSUE TITLE
x/pkgsite: "Jump to" dialog doesn't show on click or with hotkey

### ISSUE THREAD

**Issue by mknyszek** [golang/go#49556] opened 2021-11-12 18:57 UTC
I accessed https://pkg.go.dev/golang.org/x/sys/unix and when I click on "Jump to" on the top left, nothing happens. Just to be completely unambiguous, I'm referring to the follow.

![3xT5xN4NTwcRK4o (1)](https://user-images.githubusercontent.com/1248668/141520252-78fee069-0cfc-44b0-bf51-2f4a7737b178.png)

Browser is `Google Chrome Version 95.0.4638.69 (Official Build) (x86_64)`, OS is `macOS 11.6`.

**Comment by jamalc** [comment] 2021-11-12 20:01
Duplicate of #49455

**Comment by mknyszek** [comment] 2021-11-12 20:38
I saw that, but felt it was different, because it doesn't seem to capture that just clicking also doesn't work. To be clear, I'm not pushing back, leaving this as a duplicate is fine with me.

**Comment by jamalc** [comment] 2021-11-12 21:01
That's fair, the other issue doesn't capture everything.

**Closed** 2022-01-13 15:06 UTC
Labels: NeedsInvestigation, pkgsite
