### ISSUE TITLE
cgo: exec C:\Program: exec: "C:\\Program": file does not exist

### ISSUE THREAD

**Issue by Ar37-rs** [golang/go#44013] opened 2021-01-30 15:30 UTC
building cgo/tdm-gcc windows-x64 no longer build:

go build -o main.exe main.go

code:

package main

//#cgo LDFLAGS: -L${SRCDIR}/target/debug
//#cgo LDFLAGS: -lgo_rs
//void rs_test();
import "C"

func main() {
	C.rs_test()
} 

gives an error:
# command-line-arguments
cgo: exec C:\Program: exec: "C:\\Program": file does not exist
go version: 1.15.7

**Comment by seankhliao** [comment] 2021-01-30 15:39
duplicate of #41400

**Closed by seankhliao** 2021-01-30 15:39 UTC

**Comment by Ar37-rs** [comment] 2021-01-30 15:50
fixed it myself after changing path, thanks.
