### ISSUE TITLE
runtime: workbuf is (not) empty on RISC-V

### ISSUE THREAD

**Issue by mknyszek** [golang/go#62099] opened 2023-08-17 16:14 UTC
```
#!watchflakes
post <- log ~ `workbuf is (not )?empty` && builder == "linux-riscv64-unmatched"
```

2023-07-31 18:05 linux-riscv64-unmatched go@789980ec ([log](https://build.golang.org/log/05f31f5cfd5d8244d4127c105d42fed90ce99fc3))
2023-08-01 17:41 linux-riscv64-unmatched net@8ffa475f go@fb6f38dd x/net/internal/timeseries [build] ([log](https://build.golang.org/log/4528bbe8a57649cd3ea28e9d8e4b129b98620696))
2023-08-07 00:28 linux-riscv64-unmatched go@41981930 path/filepath [build] ([log](https://build.golang.org/log/119a67d5a003c96573dd3c62cfa67e2691b9925c))
2023-08-08 21:20 linux-riscv64-unmatched go@fe1daf2e net/http_test [build] ([log](https://build.golang.org/log/d18e77d1ed60e6516fccd3a9eb090df5df546bb9))
2023-08-16 17:51 linux-riscv64-unmatched go@91bea5a2 go/types.TestStdFixed ([log](https://build.golang.org/log/35eae72f22dbfe92cbb07f685aacd53f105f0255))

CC @golang/riscv64

**Comment by bcmills** [comment] 2023-08-23 19:36
Duplicate of #62185

**Closed by bcmills** 2023-08-23 19:36 UTC
Labels: help wanted, NeedsInvestigation, arch-riscv, compiler/runtime
