### ISSUE TITLE
net/http: TestTransportHeadChunkedResponse flake

### ISSUE THREAD

**Issue by davecheney** [golang/go#11250] opened 2015-06-17 10:44 UTC
```
--- FAIL: TestTransportHeadChunkedResponse (0.01s)
	transport_test.go:611: ip/ports differed between head requests: "127.0.0.1:47607" vs "127.0.0.1:47608"
FAIL
FAIL	net/http	12.768s
```

http://build.golang.org/log/5f8b7215370338c03fbb75d43befedcbd95ed2c3

/cc @bradfitz @mikioh

**Comment by tolchz** [comment] 2015-06-17 14:48
Duplicate of #11122 

https://go-review.googlesource.com/#/c/11170/

**Closed** 2015-06-26 17:23 UTC
