### ISSUE TITLE
Can't compile go programs on solaris i386: undefined sigset

### ISSUE THREAD

**Issue by CaledoniaProject** [golang/go#18565] opened 2017-01-08 06:41 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.6.1 linux/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?

main.go

```
package main

import (
    "fmt"
)

func main () {
    fmt.Println ("Hello There!")
}
```

Solaris + i386 fails to compile?

```
%> GOOS=solaris GOARCH=386 go build
# runtime
/usr/lib/go-1.6/src/runtime/runtime2.go:287: undefined: sigset
```

**Comment by minux** [comment] 2017-01-08 06:56
Sorry, the Solaris port only supports amd64.

I believe Solaris itself only runs on amd64 nowadays,
so there is no reason for a solaris/i386 port.

**Comment by ianlancetaylor** [comment] 2017-01-08 07:05
Closing because this is not a bug as such.

**Comment by davecheney** [comment] 2017-01-08 07:06
The go tool should probably reject this combination. Possibly it already
does, can you please try again with 1.7.4 or the 1.8beta

**Closed by ianlancetaylor** 2017-01-08 07:05 UTC

**Comment by odeke-em** [comment] 2017-01-08 07:13
@davecheney yap it rejects that combination at least for go1.8
```shell
$ GOOS=solaris GOARCH=386 go build
cmd/go: unsupported GOOS/GOARCH pair solaris/386
$ go version
go version devel +8fa2344 Sat Jan 7 06:37:46 2017 +0000 darwin/amd64
```

**Comment by davecheney** [comment] 2017-01-08 07:14
Excellent. Nothing to do then.

**Comment by CaledoniaProject** [comment] 2017-01-08 08:29
So .. any plan to add support for i386 solaris?

**Comment by CaledoniaProject** [comment] 2017-01-08 08:31
@minux Actually there's lots of solaris 10 (i386) running. If I'm to build the runtime libraries for solaris i386, is there any guides?

**Comment by davecheney** [comment] 2017-01-08 08:31
There are no plans as Solaris is not supported on i386 any more.

**Comment by CaledoniaProject** [comment] 2017-01-08 08:43
Okay, Let's keep it closed then ... I'll rewrite the program with another programming language ..

**Comment by juaningan** [comment] 2017-01-26 18:38
Hi, I don't understand well. Illumos kernel or openindiana distribution has both 32-bit releases. I'm using it in some old hardware without problems.

**Comment by bradfitz** [comment] 2017-01-26 18:40
@juaningan, yes, but Go does not support Solaris/i386 and nobody has committed to working on it.
