### ISSUE TITLE
cmd/go: mod init has no version warnings

### ISSUE THREAD

**Issue by terinjokes** [golang/go#37635] opened 2020-03-03 19:53 UTC
### What version of Go are you using (`go version`)?

```
go version go1.14 linux/amd64
```

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/terin/.cache/go-build"
GOENV="/home/terin/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/terin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/go-mod-init-demo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build298501176=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I create a git repository where the latest tag is >= v2, then ran `go mod init`

```
$ git init

$ git commit --allow-empty -m "2.10.0: example release"

$ git remote add origin https://github.com/terinjokes/go-mod-init-demo.git

$ git tag -s v2.10.0

$ git describe
v2.10.0
```

### What did you expect to see?

A warning the the import path may be incompatible with Go modules. For example:

```
$ go mod init github.com/terinjokes/go-mod-init-demo
go: warning latest tag is v2.1.0, but module not have a /v2 path. This may prevent others from importing your module.
go: creating new go.mod: module github.com/terinjokes/go-mod-init-demo
```

The phrasing is just for an example. I recognize there may be several edge cases in accurately detecting the scenarios and intents of users, but I've seen many projects migrate from vendoring while already at a >= v2 release, and not realize they've made their project difficult to import.

### What did you see instead?

```
$ go mod init github.com/terinjokes/go-mod-init-demo
go: creating new go.mod: module github.com/terinjokes/go-mod-init-demo
```

**Comment by bcmills** [comment] 2020-03-03 20:33
Duplicate of #31549

**Closed by bcmills** 2020-03-03 20:33 UTC
Labels: GoCommand, modules
