### ISSUE TITLE
spec: Imprecise wording regarding assignments to variables of interface type

### ISSUE THREAD

**Issue by golang101** [golang/go#17991] opened 2016-11-20 09:01 UTC
In Go spec https://golang.org/ref/spec#Interface_types:

> ..., A variable of interface type can store a value of any type with a method set that is any superset of the interface. ...

Here, if the "any type" is an interface type, then it should be said as "... store a dynamic value ...".

**Comment by robpike** [comment] 2016-11-20 14:18
It's tricky, because there's a difference between "store" and "be assigned".

Perhaps it should be s/any/any non-interface/.

**Comment by griesemer** [comment] 2016-11-21 18:28
Duplicate of #5288.

**Closed by griesemer** 2016-11-21 18:28 UTC
