### ISSUE TITLE
x/tools/gopls: crash upon creating empty linked list

### ISSUE THREAD

**Issue by soypat** [golang/go#45510] opened 2021-04-11 22:07 UTC
Here's a hard one for you.

### What version of Gopls are you using ?

<pre>
$ gopls  version
golang.org/x/tools/gopls v0.6.9
    golang.org/x/tools/gopls@v0.6.9 h1:LBBcE2y3Tb4bp79JVLWCQBbvYCFEs5ADGWsQDoSLk1Q=
</pre>

### What did you do?

Create new program from scratch, write:
```go
type a *a
var x a = a{}
```
or 
```go
type a *a
var x a = x
```

### What did you expect to see?
gopls ask me why I would want to use this crazy datastructure

### What did you see instead?
gopls crashes

**Comment by AlexRouSg** [comment] 2021-04-11 22:12
I am unable to get any indication that gopls has crashed with the given examples.
Please provide the full file (examples are missing the package line at least) and what indicates that gopls has crashed.

**Comment by soypat** [comment] 2021-04-11 23:52
It is not a gopls bug then. I am testing on vscode and this exact same program causes vscode to hang while "Getting actions from 'Go'"

**Comment by AlexRouSg** [comment] 2021-04-12 00:00
I too am running vscode and got no such thing.

However what you are describing sounds a lot like vscode is still starting up, when you do a fresh launch of vscode it is known to sometimes take a while to startup all the plugins and related tools so if you do a edit and save too quickly then it has to wait for all of that to finish loading.

Try waiting a few minutes after oppening vscode and see if it still hangs.

**Comment by stamblerre** [comment] 2021-04-12 16:40
@soypat: Can you please share your Go version? This type of bug may have been fixed with later versions of Go.

**Comment by ShoshinNikita** [comment] 2021-04-12 17:33
I could reproduce this behavior:

```go
package main

type a *a

var x a = <> // try to complete

func main() {}
```

`gopls` doesn't crash but stops responding. It is caused by a loop in `golang.org/x/tools/internal/lsp/source.Deref()`:

```go
func Deref(typ types.Type) types.Type {
	for {
		p, ok := typ.Underlying().(*types.Pointer)
		if !ok {
			return typ
		}
		// log.Printf("current typ:            %#v\n", typ)
		// log.Printf("new typ (pointer elem): %#v\n", p.Elem())
		typ = p.Elem()
		time.Sleep(time.Second)
	}
}
```

`typ` is equal to `typ.Underlying().(*types.Pointer).Elem()`:

```
current typ:            &types.Named{info:0x2, obj:(*types.TypeName)(0xc005e04dc0), orig:(*types.Pointer)(0xc00559db60), underlying:(*types.Pointer)(0xc00559db60), methods:[]*types.Func(nil)}
new typ (pointer elem): &types.Named{info:0x2, obj:(*types.TypeName)(0xc005e04dc0), orig:(*types.Pointer)(0xc00559db60), underlying:(*types.Pointer)(0xc00559db60), methods:[]*types.Func(nil)}
```

So, this loop is infinite.

<details>
  <summary>Stack trace</summary>

  ```
  golang.org/x/tools/internal/lsp/source.Deref()
    github.com/golang/tools/internal/lsp/source/util.go:233

  golang.org/x/tools/internal/lsp/source/completion.(*completer).lexical()
    github.com/golang/tools/internal/lsp/source/completion/completion.go:1352

  golang.org/x/tools/internal/lsp/source/completion.(*completer).collectCompletions()
    github.com/golang/tools/internal/lsp/source/completion/completion.go:643

  golang.org/x/tools/internal/lsp/source/completion.Completion()
    github.com/golang/tools/internal/lsp/source/completion/completion.go:554 +0xe56
  ```
</details>

**Comment by AlexRouSg** [comment] 2021-04-12 17:41
Ok I can reproduce this now but the steps to reproduce wasn't clear.

First create a file and fill it with and save:
```
package main

type a *a

var x a = <> // try to complete

func main() {}
```

Next edit this line and save again:
`var x a = nil`

**Comment by soypat** [comment] 2021-04-12 18:12
Sorry. I'll make sure steps are clearer next time.

**Comment by stamblerre** [comment] 2021-04-12 21:45
Thanks for figuring out the cause of this bug, @ShoshinNikita! Do you want to send the CL to fix it or would you rather a member of the `gopls` team to take it on?

**Comment by ShoshinNikita** [comment] 2021-04-13 07:34
I would be happy to send a CL but I am not sure about the fix. Should we just return the current `typ` in such situations?

**Comment by stamblerre** [comment] 2021-04-13 18:09
Yeah I think that would work.

**Closed** 2021-04-14 19:51 UTC
Labels: Tools, WaitingForInfo, gopls, help wanted

**Comment by muirdm** [comment] 2021-04-15 17:51
I don't think this fix is sufficient for cyclic types like:

```
type (
	foo *bar
	bar *foo
)
```

**Comment by ShoshinNikita** [comment] 2021-04-15 19:25
Yeah, the current fix doesn't work for such cyclic types. I think we can use `map[types.Type]struct{}` with all previous underlying types to detect cycles.

**Comment by muirdm** [comment] 2021-04-15 20:41
One slight optimization is that you only have to worry about named pointer types (i.e. you only have to allocate/insert into your map when you see a named pointer type).
