### ISSUE TITLE
cmd/cover: Compilation error when using -covermode=atomic on a file without a newline at the end

### ISSUE THREAD

**Issue by jerbob92** [golang/go#59081] opened 2023-03-16 21:08 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jeroen/.cache/go-build"
GOENV="/home/jeroen/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jeroen/go/pkg/mod"
GONOPROXY="s"
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jeroen/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jeroen/Projects/OpenSource/go-pdfium/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1981126242=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Recently I started upgrading [go-pdfium](https://github.com/klippa-app/go-pdfium) to the latest version of pdfium (it's a CGO wrapper), I'm also upgrading to the latest Go in the test/coverage matrix.

When I completed the upgrades, I noticed that my `go test -coverprofile=coverage.out -covermode=atomic` command that generates the code coverage is broken in go 1.20, while it did work in 1.19. 

It resulted in the following error: https://github.com/klippa-app/go-pdfium/actions/runs/4441302163/jobs/7796211682

I later found out that this was related to the file not having a newline at the end, the following commit fixed it:
https://github.com/klippa-app/go-pdfium/commit/788fce4cacdf2876c261f38c47494fb9c3d68ef1

I don't really know how the file ended up in this state, but since it worked in 1.19, and go build/go test (with -coverprofile but without -covermode=atomic) did still work, I wanted to report it anyway, also because @bcmills said the `cover` implementation changed drastically in 1.20.

### What did you expect to see?
The result of the code coverage.

### What did you see instead?
Error: internal/implementation_cgo/fpdf_formfill_experimental.go:285:2: expected ';', found 'var'

**Comment by bcmills** [comment] 2023-03-16 21:20
(attn @thanm)

**Comment by thanm** [comment] 2023-03-27 16:48
@jerbob92 thanks for the report.

This issue looks to be a duplicate of #58370, now fix at tip (will be released as part of Go 1.21).

**Comment by thanm** [comment] 2023-03-27 16:48
Dup of #58370.

**Closed by thanm** 2023-03-27 16:48 UTC
Labels: NeedsInvestigation, compiler/runtime
