### ISSUE TITLE
cmd/go: improve support for using modules in offline mode

### ISSUE THREAD

**Issue by mvdan** [golang/go#49389] opened 2021-11-05 15:29 UTC
I was on a plane earlier this week, and not being able to use `go get` was unfortunate. Any queries like `go get some-dependency@latest` or `@master` always reach for the internet, failing immediately. Something akin to `go get some-dependency@latest-cached` would have been neat, because that dependency was many months out of date, and my cache had multiple newer tagged versions.

I ended up looking directly into my module download cache, finding the latest tagged version there, then using `go get some-dependency@v1.2.3`. Which worked, but it's also somewhat tedious, and I don't like having to peek at the local cache in this way to be able to use it.

I believe that we've talked about better offline support before, but I could not find a tracking issue for it.

cc @bcmills @matloob

**Comment by bcmills** [comment] 2021-11-05 18:42
Aha! I found the issue I thought I remembered for this.

**Comment by bcmills** [comment] 2021-11-05 18:42
Duplicate of #43646

**Closed by bcmills** 2021-11-05 18:42 UTC
Labels: NeedsInvestigation, GoCommand, modules

**Comment by mvdan** [comment] 2021-11-05 18:52
Ah, thanks!
