### ISSUE TITLE
go/doc: Some functions with type parameters omitted

### ISSUE THREAD

**Issue by muhlemmer** [golang/go#49477] opened 2021-11-09 14:50 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.18-b7529c3 Tue Nov 9 06:27:04 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

N/A

### What operating system and processor architecture are you using (`go env`)?

Custom VSCode devcontainer, Dockerfile based on `golang:latest`, but running a Go build of the latest `master` branch.

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vscode/.cache/go-build"
GOENV="/home/vscode/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/master/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/master/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.18-b7529c3 Tue Nov 9 06:27:04 2021 +0000"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/workspace/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3516386950=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Some functions that take type parameters, are ignored / not documented by `godoc` http server. Notably I found generic functions that return a value or slice of Type are omitted in the documentation output. While functions which receive an argument of a generic Type are represented in the documentation. 

I've created a small [Github repo](https://github.com/muhlemmer/godoc_generics_issue) to easily reproduce. It contains a `source.go` file with generic functions, and a Dockerfile that build the latest `golang/go:master` with `x/tools/cmd/godoc@master`:

1. `git clone https://github.com/muhlemmer/godoc_generics_issue.git`
2. `docker build -t ggi .`
3. `docker run -p 6060:6060 ggi`
4. Browse to http://localhost:6060/pkg/github.com/muhlemmer/godoc_generics_issue/

### What did you expect to see?

All exported functions, with or without type parameters to be documented.

### What did you see instead?

This function is documented:

```
func Print[T proto.Message](s []T) {
	for _, v := range s {
		fmt.Println(v)
	}
}
````

This functions are missing:

```
func Slice[T any]() []T {
	return nil
}

func Single[T any]() *T {
	return nil
}
```

**Comment by findleyr** [comment] 2021-11-09 19:05
CC @jba @ianthehat 

I will look into this to make sure it's not a bug with the standard library go/doc package, but x/tools/cmd/godoc itself is a relatively lower priority to update for generics than pkgsite (#48264), which also has a command to run locally.  With that said, it may be the case that this is an easy fix.

Assigning to myself for investigation.

**Comment by muhlemmer** [comment] 2021-11-10 11:19
When I run the `go doc -all` command, the output has the same functions missing in output:

```
package godoc_generics_issue // import "github.com/muhlemmer/godoc_generics_issue"


FUNCTIONS

func Print[T any](s []T)
    Print prints the elements of a slice. It should be possible to call this
    with any slice value.

```

So this might indeed be a `go/doc` library issue. Hope this helps your investigation.

**Comment by findleyr** [comment] 2021-11-10 15:57
@muhlemmer really appreciate your dilligence here.

It is indeed a go/doc issue: these functions are being interpreted as 'constructors' of the type parameter T (because from syntax alone, T looks like a defined type).

Fortunately we can work around this without type checking. Fix incoming.

**Closed** 2021-11-10 18:07 UTC
Labels: release-blocker, Tools
