### ISSUE TITLE
Golang major bug, make cache read data bug, 4096 bug!!!

### ISSUE THREAD

**Issue by jiexinren** [golang/go#51095] opened 2022-02-09 07:47 UTC
Golang major bug, make cache read data bug, 4096 bug!!!

https://blog.csdn.net/qq_30712797/article/details/122836082

**Comment by mvdan** [comment] 2022-02-09 08:31
You linked to something that's entirely in Chinese, which most of us can't read. You didn't provide enough details here either - note that we have a bug issue template for a reason. Closing for now, as there's nothing we can do here.

**Closed by mvdan** 2022-02-09 08:31 UTC

**Comment by erifan** [comment] 2022-02-09 08:37
I translated it into English in case it's really a bug. See https://go.dev/play/p/kTnyIb-ZCW0

**Comment by mvdan** [comment] 2022-02-09 08:42
It can be investigated if someone submits a bug report following the template, with a proper explanation of what goes wrong and how to reproduce it.

**Comment by erifan** [comment] 2022-02-09 09:02
@jiexinren This is not a bug, please refer to https://pkg.go.dev/bufio#Reader.Read, you need to check how much bytes the function actually read.

**Comment by HansVanHerwijnen** [comment] 2022-03-16 14:40
@erifan Although @seankhliao closed my topic (https://github.com/golang/go/issues/51703) as duplicate, checking the number of bytes will not work.
When you read past the end of the 4k buffer, the returned length will be the size of your buffer and err will be "nil". The missing bytes will be set to zero and the missing bytes will be delivered on the next read.
@seankhliao I think you where a little quick closing my topic as duplicate, flagging it as an extension to this one would be nicer as I provided code on how to reproduce the errornous behaviour of bufio.Read()
