### ISSUE TITLE
https://pkg.go.dev/golang.org/x/net/html Parse functions documented under Node

### ISSUE THREAD

**Issue by DonaldRich** [golang/go#65493] opened 2024-02-03 12:10 UTC
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/golang.org/x/net/html
 
### What is your user agent?
 
[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36]
 
 
### Screenshot
 
![image](https://github.com/golang/go/assets/1814029/ac12d883-81a5-49f1-882e-1130f3ea4057)
 
### What did you do?
 
Opened the page and searched for "Parse"
 
### What did you expect to see?
 
 I expected to see the Parse functions documented in the Functions section.
 
### What did you see instead?

The Parse functions are documented under the Node Type.

**Comment by seankhliao** [comment] 2024-02-03 12:26
Duplicate of #39813

**Closed by seankhliao** 2024-02-03 12:26 UTC
Labels: Documentation
