### ISSUE TITLE
testing/benchmarking: go test runs tests even if told not to do so

### ISSUE THREAD

**Issue by lukasmalkmus** [golang/go#23729] opened 2018-02-07 13:59 UTC
### What version of Go are you using (`go version`)?

go version go1.9.3 darwin/amd64

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/lukasmalkmus/Code/Go"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dy/s6dd70892l35f0444cwt96t40000gn/T/go-build175824991=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

I'm having this kind of directory structure:

```text
pkg
├── a
│   ├── a.go
│   └── a_test.go
└── b
       ├── b.go
       └── b_test.go
```

Each `_test.go` file contains benchmarks. I want to benchmark my code, but **not** test it. To benchmark a single package I run `go test -run=^$ -bench=. ./pkg/a`.

But I want to test all packages in `pkg/`, so I do `go test -run=^$ -bench=. ./pkg/...`

### What did you expect to see?

`go test` running the benchmarks of packages `a` and `b`.

### What did you see instead?

`go test` running the benchmarks **and** tests of packages `a` and `b`.

**Comment by agnivade** [comment] 2018-02-07 14:37
To clarify, you are not seeing the issue when you run benchmarks on a single package. But only when you test both `a` and `b`, you see this issue. Is that right ?

**Comment by lukasmalkmus** [comment] 2018-02-07 14:39
Yes, indeed.

**Comment by bradfitz** [comment] 2018-02-07 16:53
I can't reproduce with Go 1.9 or Go tip.

```
bradfitz@gdev:~/src$ GOROOT=$HOME/go1.9 go test -v -run=^$ -bench=. ./issue23729/...
goos: linux
goarch: amd64
pkg: issue23729/a
BenchmarkFoo-4          2000000000               0.40 ns/op
--- BENCH: BenchmarkFoo-4
        a_test.go:10: hi
        a_test.go:10: hi
        a_test.go:10: hi
        a_test.go:10: hi
        a_test.go:10: hi
        a_test.go:10: hi
PASS
ok      issue23729/a    0.845s
goos: linux
goarch: amd64
pkg: issue23729/b
BenchmarkFoo-4          2000000000               0.40 ns/op
--- BENCH: BenchmarkFoo-4
        b_test.go:10: hi
        b_test.go:10: hi
        b_test.go:10: hi
        b_test.go:10: hi
        b_test.go:10: hi
        b_test.go:10: hi
PASS
ok      issue23729/b    0.843s
bradfitz@gdev:~/src$ GOROOT=$HOME/go1.9 go test -v  -bench=. ./issue23729/...
=== RUN   TestFoo
--- PASS: TestFoo (0.00s)
        a_test.go:6: hi
goos: linux
goarch: amd64
pkg: issue23729/a
BenchmarkFoo-4          2000000000               0.40 ns/op
--- BENCH: BenchmarkFoo-4
        a_test.go:10: hi
        a_test.go:10: hi
        a_test.go:10: hi
        a_test.go:10: hi
        a_test.go:10: hi
        a_test.go:10: hi
PASS
ok      issue23729/a    0.837s
=== RUN   TestFoo
--- PASS: TestFoo (0.00s)
        b_test.go:6: hi
goos: linux
goarch: amd64
pkg: issue23729/b
BenchmarkFoo-4          2000000000               0.40 ns/op
--- BENCH: BenchmarkFoo-4
        b_test.go:10: hi
        b_test.go:10: hi
        b_test.go:10: hi
        b_test.go:10: hi
        b_test.go:10: hi
        b_test.go:10: hi
PASS
ok      issue23729/b    0.844s
```

Please supply more details. Can you put a repo on GitHub with files demonstrating the issue?

**Comment by lukasmalkmus** [comment] 2018-02-07 23:23
So... I can't reproduce it either with this simple setup: https://github.com/lukasmalkmus/issue23729

But it's definitely there. I have a private repo set up which has a `pkg` package with a few sub packages, just like the example repo I created. The command in question is `go test -run='^$' -bench=. ./pkg/...`. If I run it on my private repo I get this output:

```text
?       github.com/lukasmalkmus/gortys/pkg      [no test files]
PASS
ok      github.com/lukasmalkmus/gortys/pkg/config       0.016s
?       github.com/lukasmalkmus/gortys/pkg/grpc [no test files]
?       github.com/lukasmalkmus/gortys/pkg/http [no test files]
?       github.com/lukasmalkmus/gortys/pkg/log  [no test files]
?       github.com/lukasmalkmus/gortys/pkg/metrics      [no test files]
goos: darwin
goarch: amd64
pkg: github.com/lukasmalkmus/gortys/pkg/password
BenchmarkGenerate-4         1000           1268986 ns/op
BenchmarkCompare-4          1000           1263997 ns/op
PASS
ok      github.com/lukasmalkmus/gortys/pkg/password     2.851s
?       github.com/lukasmalkmus/gortys/pkg/pprof        [no test files]
PASS
ok      github.com/lukasmalkmus/gortys/pkg/status       0.027s
?       github.com/lukasmalkmus/gortys/pkg/version      [no test files]
```

So I will further investigate what is different in my "real world" project. Any clues what *might* go wrong? But I really checked twice, the issue is definitely present.

**Comment by davecheney** [comment] 2018-02-07 23:45
Running benchmarks for multiple packages will execute them concurrently, skewing your results.

**Comment by lukasmalkmus** [comment] 2018-02-07 23:55
Oh wow. Didn't know that. So I should consider this a bad practice and manually benchmark my packages one by one?

**Comment by ianlancetaylor** [comment] 2018-03-28 22:39
Doesn't seem to be anything to change here, so closing.

**Closed by ianlancetaylor** 2018-03-28 22:39 UTC
Labels: WaitingForInfo
