### ISSUE TITLE
time zones: getting time zone name and time zone numeric symbol mismatch.

### ISSUE THREAD

**Issue by sivansha** [golang/go#48180] opened 2021-09-03 18:06 UTC
### What version of Go are you using (`go version`)?
go1.13.1 linux/amd64
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
no idea

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Set time:
t , _ := time.Parse(time.RFC850, "Tuesday, 05-Apr-16 13:36:00 BST")
Print output:
2016-04-05 13:36:00 +0100 BST

However, this output was generated in time zone BST. 
Same code in another time zone gave: 
2016-04-05 13:36:00 +0000 BST 

Which should not be possible (BST defined as +0100)

https://play.golang.org/p/rvJbMLp3vsI

### What did you expect to see?
2016-04-05 13:36:00 +0100 BST

### What did you see instead?
2016-04-05 13:36:00 +0000 BST

**Comment by seankhliao** [comment] 2021-09-03 18:22
From https://pkg.go.dev/time#Parse
> If the zone abbreviation is unknown, Parse records the time as being in a fabricated location with the given zone abbreviation and a zero offset. This choice means that such a time can be parsed and reformatted with the same layout losslessly, but the exact instant used in the representation will differ by the actual zone offset. To avoid such problems, prefer time layouts that use a numeric zone offset, or use ParseInLocation.

From https://pkg.go.dev/time#ParseInLocation
> Second, when given a zone offset or abbreviation, Parse tries to match it against the Local location; ParseInLocation uses the given location.

Closing as this is working as intended

**Closed by seankhliao** 2021-09-03 18:22 UTC
