### ISSUE TITLE
x/website: /doc/tutorial/random-greeting mentions a non-existing init function

### ISSUE THREAD

**Issue by cajund** [golang/go#61195] opened 2023-07-06 14:42 UTC
### What is the URL of the page with the issue?
 
 https://go.dev/doc/tutorial/random-greeting
 
### What did you do?
 
On this page, there is a set of bullets, one being:

_Add an init function to seed the rand package with the current time. Go executes init functions automatically at program startup, after global variables have been initialized. For more about init functions, see [Effective Go](https://go.dev/doc/effective_go.html#init)._ 

However, there is no `init()` function in the example code.
 
### What did you expect to see?
 
Either the `init()` function in the code, or the removal of this bullet. An explanation as to how `rand` is seeded may help as it appears the rand.Seed()` function is depreciated.

Thanks!

**Comment by dmitshur** [comment] 2023-07-06 15:16
Thanks. Closing as a duplicate of #60627.

**Closed by dmitshur** 2023-07-06 15:16 UTC
Labels: website
