### ISSUE TITLE
go qml in go 1.8

### ISSUE THREAD

**Issue by m-ravandi** [golang/go#19924] opened 2017-04-11 11:16 UTC
- I want to work with go-qml in golang 1.8.
- You know training for it ?
- I use than this Training:
- https://github.com/chai2010/qml
- https://github.com/go-qml/qml
- But It did not work.
- My Qt is 5.7.
- thanks.

**Comment by ALTree** [comment] 2017-04-11 11:23
Hi,

the Go project does not use its bug tracker for general discussion or asking questions. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions.  Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2017-04-11 11:23 UTC
