### ISSUE TITLE
cmd/link: -buildmode=pie -linkshared generates large binaries

### ISSUE THREAD

**Issue by kiap** [golang/go#40416] opened 2020-07-26 18:31 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.15rc1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes 

This was working before on 1.14.6 and was working on every every version 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/src/.cache"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/usr/src/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/usr/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/src/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/src/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build647301757=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

go install -v -ldflags '-s -w' -gcflags '-trimpath /usr/src/go' -buildmode=shared -linkshared -pkgdir /usr/src/lib std

 
go install -v -ldflags '-s -w' -gcflags '-trimpath /usr/src/go' -buildmode=pie -linkshared -pkgdir /usr/src/lib prog

### What did you expect to see?

The binary should be linked correctly and builds linked to standard library

### What did you see instead?

static executable

**Comment by ianlancetaylor** [comment] 2020-07-26 20:18
CC @thanm @cherrymui @jeremyfaller

**Comment by ianlancetaylor** [comment] 2020-07-26 20:18
Marking as a release blocker for 1.15.  We should investigate this and decide whether it is a problem that needs to be addressed for 1.1.5

**Comment by cherrymui** [comment] 2020-07-27 02:41
Sorry, I cannot reproduce it on my machine:
```
$ go install -buildmode=shared -linkshared -pkgdir /tmp/lib std
$ go build -buildmode=pie -linkshared -pkgdir /tmp/lib hello.go 
$ file hello
hello: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=b2e8af86bc78040632dfe47c792077a16659905d, for GNU/Linux 3.2.0, not stripped
$ ldd hello | grep libstd
	libstd.so => /tmp/lib/libstd.so (0x00007ffa3ff33000)
```

The generated binary is dynamically linked and linked against libstd.so.

**Comment by kiap** [comment] 2020-07-27 08:28
Have you checked the executable file size?

despite ldd output,

When I build hello world shared linked with 1.14.6 the size is 19K
with 1.15rc1 it is 4.8M

It seems the file also contains statically linked modules

**Comment by aclements** [comment] 2020-07-27 14:37
@kiap , just the clarify, can you state the exact problem you're seeing more clearly? It's not clear from your original bug report. Is it specifically that the shared linkage executable is significantly larger than it used to be, indicating the linker included a lot of things it shouldn't have? Are you seeing problems besides the size? (When you say it "generates incorrect code", that suggests a crash or panic when you try to run it.)

**Comment by cherrymui** [comment] 2020-07-27 15:46
Thanks for the note about the size. It is not that we linked in a static copy, but we accidentally put a large number of symbols into the dynamic symbol table.

**Closed** 2020-07-27 16:06 UTC
Labels: NeedsInvestigation, release-blocker
