### ISSUE TITLE
cmd/go: clarify error from 'go install' when arguments have mismatched versions and paths

### ISSUE THREAD

**Issue by rittneje** [golang/go#51196] opened 2022-02-14 20:20 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.17.7
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
go install github.com/maxbrunsfeld/counterfeiter/v6@v6.4.1 golang.org/x/tools/cmd/goimports@v0.1.9
```

### What did you expect to see?

It should install both binaries without issue.

### What did you see instead?

> go install: golang.org/x/tools/cmd/goimports@v0.1.9: all arguments must have the same version (@v6.4.1) 

This used to work in the pre-mod days - I could install multiple unrelated binaries from local paths without issue. This seems like an arbitrary and unnecessary restriction. I shouldn't need to run the `go` command multiple times.

**Comment by dmitshur** [comment] 2022-02-15 19:43
Thanks for the report.

As far as I know this is working as intended, but one of @bcmills, @matloob, @jayconrod may have more up to date information, or link to a better existing source.

It's still possible to install arbitrary local commands with `go install cmd/a cmd/b` syntax as it was in GOPATH mode. The "@​version" syntax is new to module mode, and it has additional restrictions, documented at https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies:

> To eliminate ambiguity about which module versions are used in the build, the arguments must satisfy the following constraints:
> - All arguments must refer to packages in the same module at the same version.

Making it work for multiple modules at different versions was considered during the design of this feature, but it was decided that installing unrelated commands from different modules will need multiple `go install cmd@version` invocations. Note that it is possible to install multiple commands from a single module version in one invocation.

I'll close this because the go command is working as intended and documented, but feel free to reopen or comment if I've missed something.

**Comment by rittneje** [comment] 2022-02-15 23:37
@dmitshur Definitely I think the order of checks (same version and same module) should be reversed. Because right now the error message implies that if goimports and counterfeiter were coincidentally the same version then it would work, which makes it seem especially arbitrary.

**Comment by bcmills** [comment] 2022-02-15 23:56
Hrm. We can tell that the versions are different in this case without doing any lookups on the network or in the module cache. I suppose that we could technically prove that the two packages are from separate modules in this case too, but in general that's trickier if their paths overlap.

**Comment by rittneje** [comment] 2022-02-16 00:02
@bcmills Maybe as a simpler solution, the error can be changed to align with the statement from the docs: "all arguments must refer to packages in the same module at the same version".

**Closed** 2022-03-04 21:06 UTC
Labels: help wanted, NeedsFix, GoCommand
