### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by WillXu0313** [golang/go#70246] opened 2024-11-04 13:37 UTC
gopls version: v0.16.2/go1.22.5
gopls flags: 
update flags: proxy
extension version: 0.42.1
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Mon, 04 Nov 2024 13:36:08 GMT
restart history:
Mon, 04 Nov 2024 13:35:55 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 160,
    "TestdataFiles": 0,
    "GoFiles": 151,
    "ModFiles": 2,
    "Dirs": 14
  },
  "GOARCH": "amd64",
  "GOOS": "windows",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.5",
  "GoplsVersion": "v0.16.2",
  "InitialWorkspaceLoadDuration": "1.7283716s",
  "MemStats": {
    "HeapAlloc": 9840776,
    "HeapInUse": 17891328,
    "TotalAlloc": 231501952
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 624,
      "Largest": 210104,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.5",
        "AllPackages": {
          "Packages": 57,
          "LargestPackage": 148,
          "CompiledGoFiles": 621,
          "Modules": 1
        },
        "WorkspacePackages": {
          "Packages": 3,
          "LargestPackage": 140,
          "CompiledGoFiles": 142,
          "Modules": 1
        },
        "Diagnostics": 54
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2024-11-21 01:44
Duplicate of #68334. Please upgrade to Go 1.22.6 or later.

**Comment by WillXu0313** [comment] 2024-11-21 01:45
这是来自QQ邮箱的假期自动回复邮件。收到啦。

**Closed by findleyr** 2024-11-21 01:44 UTC
Labels: FrozenDueToAge, gopls, Tools
