### ISSUE TITLE
x/tools/cmd/gorename: doesn't update comments

### ISSUE THREAD

**Issue by sprt** [golang/go#14881] opened 2016-03-19 22:14 UTC
Let `foo.go` be:
```go
package main

// Foo does nothing.
func Foo() {}
```

Running `gorename -offset foo.go:#40 -to Bar` does update the function definition, but not the comment, as such:
```go
package main

// Foo does nothing.
func Bar() {}
```

This would be the desired output:
```go
package main

// Bar does nothing.
func Bar() {}
```

**Comment by dominikh** [comment] 2016-03-20 23:55
Duplicate of #13000

**Closed** 2016-03-21 00:50 UTC
