### ISSUE TITLE
runtime/pprof: TestMutexProfile flakiness

### ISSUE THREAD

**Issue by randall77** [golang/go#19139] opened 2017-02-17 06:42 UTC
On the builders, I see TestMutexProfile occasionally failing with
```
--- FAIL: TestMutexProfile (0.01s)
	pprof_test.go:532: expected 6 lines, got 3 "--- mutex:\ncycles/second=2362842166\nsampling period=1"
		--- mutex:
		cycles/second=2362842166
		sampling period=1
FAIL
FAIL	runtime/pprof	1.298s
```

Maybe freebsd only?

@pjweinb 

Some builder logs:
https://build.golang.org/log/c625cca078dac40bc5f1f50b62891c04b52308c5
https://build.golang.org/log/118de984fc0903fe93c3e677962cd7965637a2a3

**Comment by pjweinb** [comment] 2017-02-17 12:50
That's a remarkably uninformative error message, even if I wrote it. It
should include "expected to see evidence of a contended mutex, but didn't"

I'll try to figure out when this started and why.

**Comment by bradfitz** [comment] 2017-02-17 16:38
I also saw it on OpenBSD in #19146 (closed as dup of this).

**Comment by pjweinb** [comment] 2017-02-17 17:16
Is there some way of scanning the builder logs to find all the occurrences?


On Fri, Feb 17, 2017 at 11:39 AM, Brad Fitzpatrick <notifications@github.com

**Comment by ianlancetaylor** [comment] 2017-02-17 17:31
@aclements has a tool that scans the builder logs for test failures.

**Comment by aclements** [comment] 2017-02-17 17:38
`$ greplogs -dashboard -E "TestMutexProfile" -E "expected 6 lines" -l -md`
[2017-02-16T17:34:39-fc456c7/freebsd-386-gce101](https://build.golang.org/log/650f030384a8cd59590aa45a7ba4b45162ecf13c)
[2017-02-16T17:34:39-fc456c7/freebsd-amd64-race](https://build.golang.org/log/acda774eebe4d038055f9b18ef8b5fa7e65c2b8b)
[2017-02-16T17:52:15-990124d/linux-386](https://build.golang.org/log/c85606a6439012033aea7647cf65e7dfb99f565d)
[2017-02-16T21:54:59-661e217/freebsd-amd64-gce93](https://build.golang.org/log/118de984fc0903fe93c3e677962cd7965637a2a3)
[2017-02-16T21:54:59-661e217/linux-ppc64le-buildlet](https://build.golang.org/log/c5f1775d3d40fb1dd1d050b0f3cf6213d93510c3)
[2017-02-16T22:42:36-794f1eb/freebsd-amd64-race](https://build.golang.org/log/80a6635a54baaea90fac0f91d3aafa17b068e1b3)
[2017-02-17T06:16:44-708ba22/freebsd-amd64-gce93](https://build.golang.org/log/c625cca078dac40bc5f1f50b62891c04b52308c5)
[2017-02-17T14:36:27-79f6a5c/windows-386-gce](https://build.golang.org/log/4ef0671c856abe449ef7aa8d2e5d75ef844c6e14)

```
$ greplogs -dashboard -E "TestMutexProfile" -E "expected 6 lines" -l | findflakes -paths
First observed fc456c7 16 Feb 17:34 2017 (8 commits ago)
Last observed  79f6a5c 17 Feb 14:36 2017 (1 commits ago)
29% chance failure is still happening
71% failure probability (6 of 8 commits)
Likely culprits:
   71% fc456c7 cmd/compile/internal/gc: drop unused src.XPos params in SSA builder
   20% 58d7621 runtime: run mutexevent profiling without holding semaRoot lock
No known past failures
```

**Comment by pjweinb** [comment] 2017-02-17 17:46
Thank you. one suspects 58d7621 runtime: run mutexevent profiling without
holding semaRoot lock
.

**Comment by mdempsky** [comment] 2017-02-17 17:46
Seeing as it's also appearing on Linux and Windows, it appears OS agnostic.

**Comment by aclements** [comment] 2017-06-14 14:24
@pjweinb, any progress on this?

**Comment by aclements** [comment] 2017-06-14 14:40
> one suspects 58d7621 runtime: run mutexevent profiling without holding semaRoot lock

Never trust a commit that says "Clearly safe". :)

I've confirmed that I can reproduce this fairly easily on master (738739f565), but have been unable to reproduce it after locally reverting that change.

**Comment by aclements** [comment] 2017-06-14 14:58
Here's my hunch:

1. Let G1 be the test's main goroutine. It acquires `mu`, starts a new goroutine G2, and blocks on the second `mu.Lock()`.
2. G2 reaches the `mu.Unlock()`, which eventually calls `runtime.semrelease1`. Before recording the mutex event, `semrelease1` does `unlock(&root.lock)`.
3. We switch to G1, where the `mu.Lock()` is now allowed to proceed. The test returns from `blockMutex` and captures the mutex profile.
4. At some point in the future, G2 resumes and records its mutex event, but it's too late.

Some evidence that this is what's going on: If you add `defer runtime.GOMAXPROCS(runtime.GOMAXPROCS(1))` to the top of `TestMutexProfile`, the failure rate increases by a factor of 30. This could be because we can no longer complete G2 on a separate thread before G1 collects the profile. However, if you additionally add `runtime.Gosched()` to the end of `blockMutex` after it acquires the lock for the second time, the failure rate drops to 0. This could be because it's now forcing the scheduler to give G2 a change to finish up.

The good news is, if I'm right, this is purely a test bug.

**Closed** 2017-06-14 16:09 UTC
Labels: Testing
