### ISSUE TITLE
syscall: signal SIGURG(I/O condition) on go1.14.1, but no SIGURG signal before go 1.14 

### ISSUE THREAD

**Issue by yangwenmai** [golang/go#38290] opened 2020-04-07 13:18 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.14.1
1.13.8
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/maiyang/develop/goworkspace/bin"
GOCACHE="/Users/maiyang/Library/Caches/go-build"
GOENV="/Users/maiyang/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/maiyang/develop/goworkspace"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/maiyang/develop/go1.13.8"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/maiyang/develop/go1.13.8/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hy/qzqhs53939lg6b93mr419lnh0000gn/T/go-build297497902=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
	"os"
    "runtime"
	"os/signal"
	"syscall"
)

func main() {
	s := make(chan os.Signal, 1)
	signal.Notify(s)
	go func() {
		for {
		}
	}()
	for {
		switch signal := <-s; signal {
		case os.Interrupt, os.Kill, syscall.SIGABRT, syscall.SIGTERM:
			fmt.Println("stopped")
			return
			case syscall.SIGURG:
			 fmt.Println("sigurg")
			runtime.Gosched()
		default:
			fmt.Printf("unhandled signal: %v\n", signal)
		}
	}
}
```

### What did you expect to see?

Output:

```
sigurg
sigurg
sigurg
sigurg
sigurg
sigurg
...
```

### What did you see instead?

On go1.14.1 is output:

```
sigurg
sigurg
sigurg
sigurg
sigurg
sigurg
...
```

But on go1.13.8 is empty output.

Maybe we should keep the same with the old version(empty output)?

**Comment by OneOfOne** [comment] 2020-04-07 18:33
That's due to the new [https://go.googlesource.com/proposal/+/master/design/24543-non-cooperative-preemption.md](Non-cooperative goroutine preemption).

- #37942
- #24543

**Comment by andybons** [comment] 2020-04-07 20:51
Duplicate of #37942

**Closed by andybons** 2020-04-07 20:51 UTC

**Comment by yangwenmai** [comment] 2020-04-08 02:53
Thanks.
