### ISSUE TITLE
cmd/go: quick build flag that discards result

### ISSUE THREAD

**Issue by gsalgado** [golang/go#12359] opened 2015-08-27 14:06 UTC
I've been looking into ways of getting my builds (mostly for the benefit of tools like the syntastic vim plugin) under 1.5 to be as fast as in 1.4, and one of the tricks I've found to help is to pass -buildmode=archive. It works for go build, but not for go test, which gives me the following error:

```
$ go test -c -buildmode="archive" ./
# testmain
invalid value "" for flag -buildmode: invalid buildmode: ""
usage: link [options] main.o
  -B note
        add an ELF NT_GNU_BUILD_ID note when using ELF
[...]
```

**Comment by ianlancetaylor** [comment] 2015-08-27 14:24
We'll look into this, but the resolution might be that the go tool gives a better error message.  It's not clear that it makes sense to build a test as an archive file.

**Comment by minux** [comment] 2015-08-27 16:46
I don't think -buildmode=archive makes sense for go test. What are you
trying to achieve?

**Comment by gsalgado** [comment] 2015-08-27 16:52
Build test files without actually running the tests, just to check for
errors. This is what the syntastic plugin for vim does when you use it on a
_test.go file

**Comment by ianlancetaylor** [comment] 2015-08-27 17:00
You can build the test files just using "test -c".  I guess you are using the -buildmode=archive to skip the link step.  If this is a useful feature, I think it would make more sense to file a separate issue asking for a cmd/go option to just build, and discard the output, and not link.  This would be in effect a way to make sure that the files compile.

**Comment by minux** [comment] 2015-08-27 17:10
What if the test uses cgo and although the build step
succeeds, linking fails due to problems in cgo code?

If the problem is that linking Go program is slow, we
should address that instead.

**Comment by davecheney** [comment] 2015-08-28 00:32
You can build tests without running them like this.

go test -run=XXX ./...

**Comment by gsalgado** [comment] 2015-08-28 08:56
My main motivation is to be able to have something that runs real quick and reports errors when a developer saves a file they're editing. Ideally it should also report errors on other files within the same project, say, if I rename a function that is used somewhere else.

The reason why I started experimenting with -buildmode=archive is because in 1.5 builds became much slower; before 1.5, the hook was just doing a 'go test -c', which was fast enough in most cases.

If the check doesn't catch linking errors it's not a big deal, but yeah, it'd be nice if we could have 'go test -c' as fast as in pre-1.5 days

**Comment by josharian** [comment] 2017-01-30 21:00
If you just want to check that the code is syntactically correct and typechecks correctly, it will almost certainly be faster to use something go/types-based, such as [gotype](https://godoc.org/golang.org/x/tools/cmd/gotype) (although gotype [needs updating to use go/loader](https://github.com/golang/go/issues/14120#issuecomment-267883317)).

**Comment by myitcv** [comment] 2017-01-30 21:17
👍  to @josharian's suggestion

> (although gotype needs updating to use go/loader).

We currently work around this by running run the two-step process of `go install` on the transitive set of all dependencies (including test) for a package spec, then concurrently running `gotype -a` on each package in the package spec (although we did get bitten by https://github.com/golang/go/issues/18799).

**Comment by bradfitz** [comment] 2017-05-03 15:20
I'm going to close this. It sounds like gotype is the solution. Also, each compiler release since Go 1.5 has gotten faster, and Go 1.9 is faster than Go 1.8.

**Closed by bradfitz** 2017-05-03 15:20 UTC
Labels: NeedsFix

**Comment by josharian** [comment] 2017-05-03 15:25
Also, starting with Go 1.9, if you want to stick with cmd/compile and cmd/go, you can add `-gcflags="-dolinkobj=false"`, which will speed things up considerably.
