### ISSUE TITLE
why `break` and `continue` can follow with a tag name?

### ISSUE THREAD

**Issue by xlionet** [golang/go#36098] opened 2019-12-12 09:58 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yeah

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/didi/Library/Caches/go-build"
GOENV="/Users/didi/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY="git.xiaojukeji.com,go.intra.xiaojukeji.com"
GONOSUMDB="git.xiaojukeji.com,go.intra.xiaojukeji.com"
GOOS="darwin"
GOPATH="/Users/didi/go"
GOPRIVATE="git.xiaojukeji.com,go.intra.xiaojukeji.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/didi/workspace/go-dev/src/demo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2w/tt1p_4td3yq9xlbl7c2t4jn00000gn/T/go-build663163938=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.13.1 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.13.1
uname -v: Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64
ProductName:	Mac OS X
ProductVersion:	10.15.1
BuildVersion:	19B88
lldb --version: lldb-1100.0.30.6
Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)
</pre></details>

### What did you do?

```go
package main

import "fmt"

func main() {
	foo()
}

func foo() {

TAG:
	for i := 0; i < 3; i++ {
		fmt.Println("tag")
		if i == 2 {
			break TAG
		}
	}
}

```

### What did you expect to see?

just not pass when go build

### What did you see instead?
passed
### What is the problem?

`break TAG` is the same with `break`.  So, what`s the purpose of allowing a tag follow by it? I think that doing so violates the code's simplicity guidelines. And this is not allow in c/c++.

**Comment by ALTree** [comment] 2019-12-12 10:11
If you have nested loops that look like this:

```
TAG:
    for ( ... ) {
        for ( ... ) {
            if ( ... ) {    }
        }
    }
```

Inside the if, `break` will break out the inner loop, while `break TAG` will break out the outer loop. Without allowing the `break [ Label ] ` variant, you wouldn't be able to break out the outer loop.

See the Language Specification: https://golang.org/ref/spec#Break_statements

Closing here, since this is working as intended.

**Closed by ALTree** 2019-12-12 10:11 UTC

**Comment by xlionet** [comment] 2019-12-12 12:59
@ALTree nice to meet you again! I understand the use age of `break [label]`, but how about `continue [label]` which seems useless.

``` go
package main

import "fmt"

func main() {
	foo()
}

func foo() {

Tag:
	for i := 0; i < 4; i++ {
		for j := 0; j < 3; j++ {
			if i == 2 {
				continue Tag
			}
			fmt.Println(i, j)
		}
	}
}

```

**Comment by ALTree** [comment] 2019-12-12 13:10
@xlionet In your example are the same, but in other cases they are not:

```
main

import "fmt"

func main() {
	foo()
}

func foo() {

Tag:
	for i := 0; i < 4; i++ {
		for j := 0; j < 3; j++ {
			if j == 1 {
				continue Tag
			}
			fmt.Println(i, j)
		}
	}
}
```

`continue Tag` prints
```
0 0
1 0
2 0
3 0
```

while `continue` prints

```
0 0
0 2
1 0
1 2
2 0
2 2
3 0
3 2
```

**Comment by xlionet** [comment] 2019-12-12 13:18
@ALTree thank you very much, and i understand now!!!

**Comment by ALTree** [comment] 2019-12-12 13:26
@xlionet you are welcome. 

Please remember that we use the Github issue tracker exclusively for bugs in Go itself. If you have a question about the language, it's better to ask it in one of the places linked here: https://github.com/golang/go/wiki/Questions. If then it turns out you have found a bug in Go, you can open an issue here in Github.

**Comment by xlionet** [comment] 2019-12-13 02:21
@xlionet ok，i got it！
