### ISSUE TITLE
An ordinary operation causes the function `SetReadDeadline` to be invalid

### ISSUE THREAD

**Issue by Anveena** [golang/go#47050] opened 2021-07-04 10:32 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.16.5 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

I don't know...

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

https://play.golang.org/p/fqZEVw7akq1

### What did you expect to see?
I just thought about setting up the read buffer, and later found that "SetReadBuffer" was not as large as I designed, so I wanted to pass  ```syscall.GetsockoptInt(int(f.Fd()), syscall.SOL_SOCKET, syscall. SO_RCVBUF)``` Look at the actual value, but I found that after calling this function, the read timeout period set will no longer take effect

### What did you see instead?
```ReadFromUDP``` will never time out

**Comment by seankhliao** [comment] 2021-07-04 14:56
Duplicate of #28165

**Closed by seankhliao** 2021-07-04 14:56 UTC
