### ISSUE TITLE
Allow main() to return error

### ISSUE THREAD

**Issue by hayeah** [golang/go#34673] opened 2019-10-03 07:19 UTC
Right now the compiler reports an error if main() returns an error

```
sandbox/foobar/main.go:5:6: func main must have no arguments and no return values
```

A throwaway script typically uses a log.Fatalln to exit on error:

```go
func main() {
	err := doSomething()
	if err != nil {
		log.Fatalln(err)
	}

	err = doSomethingElse()
	if err != nil {
		log.Fatalln(err)
	}
}
```

It would be nice to just return the error, and get the same effect as calling log.Fatalln(err):

```go
func main() error {
	err := doSomething()
	if err != nil {
		return err
	}

	err = doSomethingElse()
	if err != nil {
		return err
	}

	return nil
}
```

**Comment by agnivade** [comment] 2019-10-03 07:39
You can do the same thing with 

```go
func main() {
  var err error
 defer func() {
   if err != nil {
    log.Fatalln(err)
   }
 }()
	err = doSomething()
	if err != nil {
		return
	}

	err = doSomethingElse()
	if err != nil {
		return
	}
}
```

Returning error from main sends something outside the programmer's control. You might want to control how/where the error is show.

**Comment by DisposaBoy** [comment] 2019-10-03 07:57
Don't use defer magic for this... just move the code into another function that returns an error:

	package main

	func main() {
		if err := run(); err != nil {
		}
	}

	func run() error {
		return nil
	}

**Comment by hayeah** [comment] 2019-10-03 08:08
actually maybe i'll leave this open. In fact, I personally do it the way @DisposaBoy suggested. In which case, `run` becomes another name for main()

**Comment by mvdan** [comment] 2019-10-03 10:15
Why a `log.Fatalln` and not something else? With what logger? What if the main function panics before returning?

I think this complicates the language (https://golang.org/ref/spec#Program_execution) for very little benefit - just saving yourself four lines of code.

**Comment by bcmills** [comment] 2019-10-03 12:52
This was proposed (and rejected) in #27328, and as far as I can tell this report does not add any new motivating data on top of that, so closing.

**Comment by bcmills** [comment] 2019-10-03 12:52
Duplicate of #27328

**Closed by bcmills** 2019-10-03 12:52 UTC
