### ISSUE TITLE
cmd/go: go generate fails silently when run on a package in a nested workspace module

### ISSUE THREAD

**Issue by findleyr** [golang/go#56098] opened 2022-10-07 19:13 UTC
I noticed the following while working on https://go.dev/cl/440181. I have a `go.work` file using both x/tools and x/tools/gopls. When running `go generate` on a package in x/tools/gopls, the command exits with status 0 without doing anything.

When run from the gopls module, the go generate command works as expected. This can be seen from the following shell history, where I start from a clean workspace (at patchset 2 of the above CL), make an arbitrary edit in one of the generated files, and run go generate expecting it to revert the diff.

```
$ git status
On branch accessdenied
Your branch is ahead of 'origin/master' by 1 commit.

nothing to commit, working tree clean
$ echo "// arbitrary edit" >> gopls/internal/robustio/robustio.go
$ git status
On branch accessdenied
Your branch is ahead of 'origin/master' by 1 commit.

Changes not staged for commit:
        modified:   gopls/internal/robustio/robustio.go

no changes added to commit
$ go generate ./gopls/internal/robustio
$ echo $?
0
$ git status
On branch accessdenied
Your branch is ahead of 'origin/master' by 1 commit.

Changes not staged for commit:
        modified:   gopls/internal/robustio/robustio.go

no changes added to commit
$ cd gopls && go generate ./internal/robustio
$ git status
On branch accessdenied
Your branch is ahead of 'origin/master' by 1 commit.

nothing to commit, working tree clean
```

**Comment by bcmills** [comment] 2022-10-07 21:48
Duplicate of #29751

**Comment by bcmills** [comment] 2022-10-07 21:49
Hmm, not quite a duplicate (because of workspace mode).

**Closed** 2024-01-29 19:39 UTC
Labels: NeedsInvestigation, GoCommand, modules

**Comment by matloob** [comment] 2024-01-29 19:46
@gopherbot please backport to 1.21 and 1.22. go generate doesn't work in workspace mode and it's a one-line fix
