### ISSUE TITLE
cmd/go/internal/get: enable Azure DevOps Git repos to go get

### ISSUE THREAD

**Issue by artbegolli** [golang/go#41030] opened 2020-08-25 16:58 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/abegolli/go/bin"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
</pre></details>

### What did you do?

Use `go get` to pull a repository in Azure DevOps without `.git` appended to the path

### What did you expect to see?

The repository stored in $GOPATH or path added to `go.mod`

### What did you see instead?

 ```
$ go get dev.azure.com/artbegolli/adogo/adogo
unrecognized import path "dev.azure.com/artbegolli/adogo/adogo": reading https://dev.azure.com/artbegolli/adogo/adogo?go-get=1: 203 Non-Authoritative Information
```

Azure DevOps repository clone paths do not include a `.git` suffix.

Microsoft outlines steps for `go get` command support in Azure DevOps repositories https://docs.microsoft.com/en-us/azure/devops/repos/git/go-get?view=azure-devops. Previous issues regarding `_git` in the path now have workarounds with the use of ssh paths.

The only outstanding problem is that of `.git` being required in your module path as Go treats ADO as a generic server here https://github.com/golang/go/blob/aae0b5b0b26bf4fd26cad0111535d703691a9083/src/cmd/go/internal/get/vcs.go#L1064 and expects clone paths to include a `.git` suffix.

**Comment by bcmills** [comment] 2020-08-25 17:30
Duplicate of #28236

**Closed by bcmills** 2020-08-25 17:30 UTC
