### ISSUE TITLE
proposal: slices: add transform

### ISSUE THREAD

**Issue by lasiar** [golang/go#67118] opened 2024-04-30 18:11 UTC
## Proposal Details

I propose the following:

```go
func Transform[S ~[]E, E any, T any](sl S, f func(E) T) []T {
	out := make([]T, len(sl))
	for i, t := range sl {
		out[i] = f(t)
	}

	return out
}
```
Something similar to the method from JS: [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map).

Using this code, you:
- never forget to pre-allocate the slice
- avoid code deduplication

### Sample code:
```go

type user struct {
    id int64
}

users := make([]user, 0)

...

sendByIDs(slices.Transform(users, func(u user) int64 {
    return u.id
}))
```

### Naming

I believe that the name "map" could be confusing and may be associated with the type.

**Comment by seankhliao** [comment] 2024-04-30 18:48
Duplicate of #58881

**Closed by seankhliao** 2024-04-30 18:48 UTC
Labels: Proposal
