### ISSUE TITLE
go/types/check.go: "package requires newer Go version" although Go should be up-to-date

### ISSUE THREAD

**Issue by pohly** [golang/go#67282] opened 2024-05-10 09:16 UTC
### Go version

go version go1.22.2 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/prow/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/prow/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org'
GOROOT='/home/prow/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/prow/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.2'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/prow/go/src/github.com/kubernetes-csi/csi-lib-utils/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1906945117=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

I am "go install"ing a [static analysis tool](https://github.com/kubernetes-sigs/logtools/tree/main/logcheck) in the Kubernetes CI environment. The tool then gets invoked for [csi-lib-utils](https://github.com/kubernetes-csi/csi-lib-utils) in [a PR](https://github.com/kubernetes-csi/csi-lib-utils/pull/168) which updates dependencies to Kubernetes 1.30, which brings in packages with a dependency on Go 1.22.

### What did you see happen?

When the static analysis tool has "go 1.20" in it's go.mod file, invoking it fails (from https://prow.k8s.io/log?container=test&id=1788858131263000576&job=pull-kubernetes-csi-csi-lib-utils):

```console
+ go install github.com/pohly/logtools/logcheck@dependency-update-fork-1.20
go: downloading github.com/pohly/logtools v0.0.0-20240508074535-63d1e9639914
go: downloading golang.org/x/tools v0.21.0
go: downloading golang.org/x/exp v0.0.0-20240506185415-9bf2ced13842
go: downloading golang.org/x/sync v0.7.0
go: downloading golang.org/x/mod v0.17.0
Verifing logcheck in /home/prow/go/src/github.com/kubernetes-csi/csi-lib-utils: /tmp/tmp.ZyqPi2bZ0Y/logcheck -check-contextual ./...
/home/prow/go/src/github.com/kubernetes-csi/csi-lib-utils/vendor/k8s.io/apimachinery/pkg/api/resource/amount.go:17:1: package requires newer Go version go1.22

/home/prow/go/src/github.com/kubernetes-csi/csi-lib-utils/vendor/k8s.io/apimachinery/pkg/api/resource/amount.go:17:1: package requires newer Go version go1.22
```

### What did you expect to see?

Should have worked because the Go version that was in PATH was recent enough.

Including the actual Go version would have been useful. I've been told [on Slack](https://gophers.slack.com/archives/C0VPK4Z5E/p1715179479764639?thread_ts=1715168983.104239&cid=C0VPK4Z5E)  by @timothy-king that this was already changed.

**Comment by pohly** [comment] 2024-05-10 09:28
### What did you see happen

When the static analysis tool has "go 1.22" in go.mod, building with 1.22.2 downloads 1.22.3 (from https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-lib-utils/168/pull-kubernetes-csi-csi-lib-utils/1788860954126061568/build-log.txt):

```console
+ go version
go version go1.22.2 linux/amd64
...
+ go install github.com/pohly/logtools/logcheck@dependency-update-fork-1.22
go: downloading github.com/pohly/logtools v0.0.0-20240508080454-537c42229236
go: github.com/pohly/logtools@v0.0.0-20240508080454-537c42229236 requires go >= 1.22; switching to go1.22.3
go: downloading go1.22.3 (linux/amd64)
go: downloading golang.org/x/tools v0.21.0
go: downloading golang.org/x/exp v0.0.0-20240506185415-9bf2ced13842
go: downloading golang.org/x/sync v0.7.0
go: downloading golang.org/x/mod v0.17.0
```

On the plus side, the analysis then worked.

### What did you expect to see?

The Go 1.22.2 from PATH should have been good enough. Downloading 1.22.3 causes additional network traffic.

That this solves the problem raises a question: do I need to do a new release of logcheck each time a new Go release comes out where I bump the Go version?

I expected that a user who needs the tool for a code base which depends on, say, Go 1.23 can simply build an existing logcheck release with that newer Go to make it work. Apparently that is not the case?

**Comment by pohly** [comment] 2024-05-10 09:38
Using "go 1.22.2" in go.mod led to the same result (from https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-lib-utils/168/pull-kubernetes-csi-csi-lib-utils/1788864329584480256/build-log.txt):

```console
+ go install github.com/pohly/logtools/logcheck@dependency-update-fork-1.22.2
go: downloading github.com/pohly/logtools v0.0.0-20240508115057-a7482e93ef7d
go: github.com/pohly/logtools@v0.0.0-20240508115057-a7482e93ef7d requires go >= 1.22.2; switching to go1.22.3
go: downloading go1.22.3 (linux/amd64)
go: downloading golang.org/x/tools v0.21.0
go: downloading golang.org/x/exp v0.0.0-20240506185415-9bf2ced13842
go: downloading golang.org/x/sync v0.7.0
go: downloading golang.org/x/mod v0.17.0
```

This makes even less sense because now the tool requires exactly the version of the local toolchain.

**Comment by pohly** [comment] 2024-05-10 09:50
I tried with `GOTOOLCHAIN=local go install ...`. That didn't work (from https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-lib-utils/168/pull-kubernetes-csi-csi-lib-utils/1788866768744222720/build-log.txt):

```console
+ go version
go version go1.22.2 linux/amd64
...
+ GOTOOLCHAIN=local
+ GOBIN=/tmp/tmp.FsDmM0x2vE
+ go install github.com/pohly/logtools/logcheck@dependency-update-fork-1.20
go: downloading github.com/pohly/logtools v0.0.0-20240508074535-63d1e9639914
go: downloading golang.org/x/exp v0.0.0-20240506185415-9bf2ced13842
go: downloading golang.org/x/tools v0.21.0
go: downloading golang.org/x/sync v0.7.0
go: downloading golang.org/x/mod v0.17.0
Verifing logcheck in /home/prow/go/src/github.com/kubernetes-csi/csi-lib-utils: /tmp/tmp.FsDmM0x2vE/logcheck -check-contextual ./...
/home/prow/go/src/github.com/kubernetes-csi/csi-lib-utils/vendor/k8s.io/apimachinery/pkg/api/resource/amount.go:17:1: package requires newer Go version go1.22
```

**Comment by cherrymui** [comment] 2024-05-10 21:31
Could you reproduce this on your local machine? I tried on my machine using go 1.22.2 to build github.com/pohly/logtools/logcheck@dependency-update-fork-1.20, -1.22, -1.22.2, and all succeeds without downloading a new Go toolchain. GOTOOLCHAIN=local works for me for all of them as well.

**Comment by seankhliao** [comment] 2024-05-11 09:33
Your CI's local toolchain is `1.21.5`
Your version checks are executed within a checkout of your codebase, so the version printed is after a version switch:
```
GOROOT='/home/prow/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64'
GOMOD='/home/prow/go/src/github.com/kubernetes-csi/csi-lib-utils/go.mod'
```

**Comment by pohly** [comment] 2024-05-13 15:27
> Could you reproduce this on your local machine?

No.

> Your CI's local toolchain is 1.21.5

Ah, I see. The `cd /tmp/tmp.t47x9PK9Lg` in https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-lib-utils/168/pull-kubernetes-csi-csi-lib-utils/1788860954126061568/build-log.txt came *after* `go version` and thus that wasn't actually the Go from PATH as I had thought. Well spotted!

So if the Go in PATH had indeed been 1.22.x, that one would have been used for everything and the go.mod "go 1.20" in the static analysis tool would have been fine, right?

**Comment by cherrymui** [comment] 2024-05-13 15:43
> So if the Go in PATH had indeed been 1.22.x, that one would have been used for everything and the go.mod "go 1.20" in the static analysis tool would have been fine, right?

If the go command is indeed 1.22.x, it should be used for building everything with a go.mod "go 1.20", "go 1.22", or "go 1.22.2", without downloading.

I'm not familiar with your static analysis tool, so I'm not sure. Now that you've spotted the problem, you could try it after fixing the issue, or simply locally with a Go 1.22 installation, and see if it works. Closing for now. Feel free to reopen if that is still an issue. Thanks.

**Closed by cherrymui** 2024-05-13 15:43 UTC
Labels: WaitingForInfo
