### ISSUE TITLE
cmd/compile: report variable declared but not used when only a field of a struct-typed variable is written to

### ISSUE THREAD

**Issue by qiangli** [golang/go#50778] opened 2022-01-24 17:51 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.16.7 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>
go env
</code> 
Output:
</summary>
<br>
<pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user/go/pkg/mod"
GONOPROXY="github.com/myurl/*"
GONOSUMDB="github.com/myurl/*"
GOOS="darwin"
GOPATH="/Users/user/go"
GOPRIVATE="github.com/myurl/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/user/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/user/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/user/bug/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2r/7l5dccss0y74mcl41nqbpyfm6h04p
</pre></details>

### What did you do?
It is desired that an error be reported  when running go vet/build with the following code:
```
package main

import (
	"net/url"
)

func main() {
	s := "https://example.com"
	myUrl, err := url.Parse(s)
	if err != nil {
		panic(err)
	}
        // myUrl is used but not really.
	myUrl.Scheme = "http"
}
```

### What did you expect to see?

myUrl declared but not used

### What did you see instead?

No error.

**Comment by seankhliao** [comment] 2022-01-24 17:57
Duplicate of #449

**Comment by mknyszek** [comment] 2022-01-24 17:57
I don't think that this is going to be possible to add now because it'll cause programs that previously compiled to no longer compile which breaks the Go 1 backwards compatibility promise.

**Comment by mknyszek** [comment] 2022-01-24 17:57
@seankhliao Good catch!

**Closed by seankhliao** 2022-01-24 17:57 UTC
Labels: NeedsInvestigation

**Comment by mknyszek** [comment] 2022-01-24 17:58
And yes, as the other bug says, a vet check is reasonable and won't break backwards compatibility.
