### ISSUE TITLE
stack trace pointed to an impossible place for a panic

### ISSUE THREAD

**Issue by kentquirk** [golang/go#17112] opened 2016-09-14 23:50 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.7.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/kquirk/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wf/zd6gy_wj4xqdgw1ws3c6gnk40000gp/T/go-build411429036=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?
_This can't run on playground because it imports "golang.org/x/net/html"._

Run the file bug.go (attached as part of gobug.zip). It panics with a stack trace (also attached) that points to line 94, which is a call to the free function `addSibling` with parameters of two non-nil pointers. I verified that both the pointers and the addSibling value were all non-nil. This appears to be an impossible panic.

Eventually, I was able to track the bug down to an attempt to dereference a nil pointer in the `addSibling` function itself. The stack trace was confused.

### What did you expect to see?
A stack trace that pointed to the actual location of the panic.

### What did you see instead?
A stack trace that pointed higher up the stack.

[gobug.zip](https://github.com/golang/go/files/473673/gobug.zip)

**Comment by dominikh** [comment] 2016-09-14 23:54
> ./bug.go:94: inlining call to addSibling

This is a duplicate of #10152

BTW: 
> This can't run on playground because it imports "golang.org/x/net/html".

You can still use the Playground for sharing code, even if it doesn't run on there.

**Comment by dsnet** [comment] 2016-09-14 23:56
Closing as duplicate.

**Closed by dsnet** 2016-09-14 23:56 UTC
