### ISSUE TITLE
cmd/go: 'go get' in a module with a higher go version may leave go.(mod|sum) in bad state

### ISSUE THREAD

**Issue by myitcv** [golang/go#50986] opened 2022-02-03 08:05 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.13 linux/arm64
</pre>

### Does this issue reproduce with the latest release?

The latest `go1.16` version, yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/myitcv/gostuff/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.16.13"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4113847066=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```
# git checkout
exec git init
exec git remote add origin https://github.com/govim/govim
exec git fetch origin 1da33d23886a18dd8280770dad0d3ae60e872e6a
exec git checkout FETCH_HEAD

# go version check
go version

# get new versions of tools and gopls
go get golang.org/x/tools/gopls@v0.0.0-20220131221016-263785d77403 golang.org/x/tools@v0.1.10-0.20220131221016-263785d77403

# try and tidy
go mod tidy

# go generate again
go generate . ./cmd/govim
```

The `go mod tidy` step fails with:

```
go mod tidy: go.mod file indicates go 1.17, but maximum supported version is 1.16
```

The `go generate` step fails with:

```
go: downloading gopkg.in/tomb.v2 v2.0.0-20161208151619-d5d1b5820637
go: downloading github.com/fsnotify/fsnotify v1.4.7
govim.go:21:2: missing go.sum entry for module providing package github.com/kr/pretty (imported by github.com/govim/govim); to add:
        go get github.com/govim/govim
internal/cmd/genconfig/genconfig.go:15:2: missing go.sum entry for module providing package github.com/rogpeppe/go-internal/semver (imported by github.com/govim/govim/internal/cmd/genconfig); to add:
        go get github.com/govim/govim/internal/cmd/genconfig
govim.go:26: running "go": exit status 1
../../internal/cmd/txtarutil/main.go:39:2: missing go.sum entry for module providing package github.com/rogpeppe/go-internal/txtar (imported by github.com/govim/govim/internal/cmd/txtarutil); to add:
        go get github.com/govim/govim/internal/cmd/txtarutil
cmd/govim/main_test.go:30: running "go": exit status 1
```

(which is odd because the main module is `github.com/govim/govim`)

### What did you expect to see?

It strikes me that the `go get` step should probably have failed in the first instance, because it couldn't make the necessary changes to `go.(mod|sum)` to leave both in a valid state.

### What did you see instead?

`go.(mod|sum)` in a bad state that can't be corrected.

**Comment by bcmills** [comment] 2022-02-03 16:38
Hmm, interesting. Yeah, it may be that `go get` itself should fail when the `go` version is higher than supported, since it doesn't in general know how to maintain invariants for higher versions.

(CC @matloob)

**Comment by thepudds** [comment] 2022-02-03 17:06
Is this a more specific instance of #50468?

(FWIW, I think I might have hit us too switching back and forth between Go 1.17 and tip).

**Comment by bcmills** [comment] 2022-02-03 20:49
Duplicate of #50468

**Closed by bcmills** 2022-02-03 20:49 UTC
Labels: Thinking, NeedsInvestigation, GoCommand, modules
