### ISSUE TITLE
go/compile: new variable is not assigned a new address?

### ISSUE THREAD

**Issue by zboya** [golang/go#44954] opened 2021-03-12 02:20 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
I have try many go version, include 1.10.2,1.15.3,1.15.5,1.16.2
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/boya/Library/Caches/go-build"
GOENV="/Users/boya/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/boya/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/boya/gopath"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/Users/boya/golang/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/Users/boya/golang/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/35/fxx5kbsd4pl8qck2vtf040740000gn/T/go-build932660400=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
```go
package main

import (
	"unsafe"
)

type puintptr uintptr

func (pp puintptr) ptr() *p { return (*p)(unsafe.Pointer(pp)) }

func (pp *puintptr) set(p *p) { *pp = puintptr(unsafe.Pointer(p)) }

type p struct {
	id   int
	link puintptr
}

var pidleList puintptr

func pidleput(_p_ *p) {
	_p_.link = pidleList
	pidleList.set(_p_)
}

func pidleget() *p {
	_p_ := pidleList.ptr()
	if _p_ != nil {
		pidleList = _p_.link
	}
	return _p_
}

func main() {
	// var tp *p
	for i := 0; i < 5; i++ {
		tp := &p{id: i}
		println("put p: ", i, tp)
		pidleput(tp)
	}
	println("")
	for i := 0; i < 5; i++ {
		tp := pidleget()
		x := tp
		println("get p: ", x.id, ",", x)
	}
}
```

### What did you expect to see?
```
put p:  0 0xc4200120c0
put p:  1 0xc4200120d0
put p:  2 0xc4200120e0
put p:  3 0xc4200120f0
put p:  4 0xc420012100

get p:  4 , 0xc420012100
get p:  3 , 0xc4200120f0
get p:  2 , 0xc4200120e0
get p:  1 , 0xc4200120d0
get p:  0 , 0xc4200120c0
```

### What did you see instead?
```
put p:  0 0xc00004c760
put p:  1 0xc00004c760
put p:  2 0xc00004c760
put p:  3 0xc00004c760
put p:  4 0xc00004c760

get p:  4 , 0xc00004c760
get p:  4 , 0xc00004c760
get p:  4 , 0xc00004c760
get p:  4 , 0xc00004c760
get p:  4 , 0xc00004c760
```

### more
use `1.15.3,1.15.5,1.16.2` version always print 
```
put p:  0 0xc00004c760
put p:  1 0xc00004c760
put p:  2 0xc00004c760
put p:  3 0xc00004c760
put p:  4 0xc00004c760

get p:  4 , 0xc00004c760
get p:  4 , 0xc00004c760
get p:  4 , 0xc00004c760
get p:  4 , 0xc00004c760
get p:  4 , 0xc00004c760
```

but in `1.10.2` version, it print
```
put p:  0 0xc4200120c0
put p:  1 0xc4200120d0
put p:  2 0xc4200120e0
put p:  3 0xc4200120f0
put p:  4 0xc420012100

get p:  4 , 0xc420012100
get p:  3 , 0xc4200120f0
get p:  2 , 0xc4200120e0
get p:  1 , 0xc4200120d0
get p:  0 , 0xc4200120c0
```

It seems than go always assigns the same address for `tp` var. so I print asm code.
`go1.10.2`
```
        0x0023 00035 (main.go:35)	JMP	88
	0x0025 00037 (main.go:35)	MOVQ	AX, "".i+24(SP)
	0x002a 00042 (main.go:36)	LEAQ	type."".p(SB), AX
	0x0031 00049 (main.go:36)	MOVQ	AX, (SP)
	0x0035 00053 (main.go:36)	PCDATA	$0, $0
	0x0035 00053 (main.go:36)	CALL	runtime.newobject(SB)
	0x003a 00058 (main.go:36)	MOVQ	8(SP), AX
	0x003f 00063 (main.go:36)	MOVQ	"".i+24(SP), CX
	0x0044 00068 (main.go:36)	MOVQ	CX, (AX)
	0x0047 00071 (main.go:38)	MOVQ	AX, (SP)
	0x004b 00075 (main.go:38)	PCDATA	$0, $0
	0x004b 00075 (main.go:38)	CALL	"".pidleput(SB)
	0x0050 00080 (main.go:38)	MOVQ	"".i+24(SP), AX
	0x0055 00085 (main.go:35)	INCQ	AX
	0x0058 00088 (main.go:35)	CMPQ	AX, $5
```

`go1.15.3`
```
	0x0023 00035 (main.go:35)	JMP	86
	0x0025 00037 (main.go:35)	MOVQ	AX, "".i+24(SP)
	0x002a 00042 (main.go:36)	XORPS	X0, X0
	0x002d 00045 (main.go:36)	MOVUPS	X0, ""..autotmp_6+40(SP)
	0x0032 00050 (main.go:36)	MOVQ	$0, ""..autotmp_6+48(SP)
	0x003b 00059 (main.go:36)	MOVQ	AX, ""..autotmp_6+40(SP)
	0x0040 00064 (main.go:38)	LEAQ	""..autotmp_6+40(SP), CX
	0x0045 00069 (main.go:38)	MOVQ	CX, (SP)
	0x0049 00073 (main.go:38)	PCDATA	$1, $0
	0x0049 00073 (main.go:38)	CALL	"".pidleput(SB)
	0x004e 00078 (main.go:35)	MOVQ	"".i+24(SP), AX
	0x0053 00083 (main.go:35)	INCQ	AX
	0x0056 00086 (main.go:35)	CMPQ	AX, $5
```

The compiler always allocates the same address for `tp` var.

**Comment by randall77** [comment] 2021-03-12 02:59
`tp` is now allocated on the stack instead of the heap. Because its lifetime is shorter than the loop, the compiler reuses the storage for each instance of `tp`.
Closing, as this is not a bug. Please reopen if you disagree.

**Closed by randall77** 2021-03-12 02:59 UTC

**Comment by randall77** [comment] 2021-03-12 03:01
Oh yes, and you're violating the [rules about `unsafe.Pointer` conversions](https://golang.org/pkg/unsafe/#Pointer), which is probably why the compiler thinks it can stack allocate correctly.
