### ISSUE TITLE
cmd/go: go.mod should codify dependencies in multi-module mode before tagging new module

### ISSUE THREAD

**Issue by jadekler** [golang/go#32344] opened 2019-05-30 23:53 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/deklerk/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/deklerk/workspace/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/tmp/google-cloud-go/logging/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qq/y4kgdzjn45v0vzhfp_1j79k800h16k/T/go-build294552016=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
cd /my-project
# already has a go.mod
cd subdir
go mod init
go mod tidy
```

(the subdir is https://github.com/googleapis/google-cloud-go/tree/master/logging)

### What did you expect to see?

A go.mod with all the `subdir` dependencies codified.

### What did you see instead?

```
module my-project/subdir

go 1.12
```

(actually, using real example, the module name is `cloud.google.com/go/logging`)

Why does `go mod tidy` not codify all the newly-carved-out module's dependencies? Similarly, `go mod graph` returns nothing:

```
deklerk at deklerk-macbookpro in /tmp/google-cloud-go/logging on master*
$ go mod graph
deklerk at deklerk-macbookpro in /tmp/google-cloud-go/logging on master*
```

I assume that once I publish a logging/v0.0.1, `go mod tidy` will magically begin working as expected...?

**Comment by thepudds** [comment] 2019-05-31 03:19
Hi @jadekler Maybe this is an incarnation of #27063?

Does `go build` error out, or complete successfully?

**Comment by bcmills** [comment] 2019-05-31 15:38
What do you mean by “codify”?

This is most definitely another instance of #27063:

```
~/src/cloud.google.com/go/logging$ gotip mod init
go: creating new go.mod: module cloud.google.com/go/logging

~/src/cloud.google.com/go/logging$ gotip mod tidy
go: finding google.golang.org/grpc v1.21.0
go: finding google.golang.org/genproto latest
go: downloading github.com/googleapis/gax-go v2.0.2+incompatible
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading google.golang.org/genproto v0.0.0-20190530194941-fb225487d101
go: downloading google.golang.org/grpc v1.21.0
go: extracting github.com/googleapis/gax-go/v2 v2.0.4
go: extracting github.com/googleapis/gax-go v2.0.2+incompatible
go: extracting google.golang.org/grpc v1.21.0
go: extracting google.golang.org/genproto v0.0.0-20190530194941-fb225487d101
go: finding cloud.google.com/go v0.39.0
go: downloading cloud.google.com/go v0.39.0
go: extracting cloud.google.com/go v0.39.0
go: downloading github.com/google/go-cmp v0.3.0
go: extracting github.com/google/go-cmp v0.3.0
go: finding go.opencensus.io v0.22.0
go: downloading go.opencensus.io v0.22.0
go: extracting go.opencensus.io v0.22.0
go: finding golang.org/x/oauth2 latest
go: finding google.golang.org/genproto v0.0.0-20190508193815-b515fa19cec8
go: finding golang.org/x/sys v0.0.0-20190502145724-3ef323f4f1fd
go: finding google.golang.org/genproto v0.0.0-20190425155659-357c62f0e4bb
go: finding golang.org/x/net v0.0.0-20190501004415-9ce7a6920f09

~/src/cloud.google.com/go/logging$ gotip list -m all
cloud.google.com/go/logging

~/src/cloud.google.com/go/logging$ gotip list all
go: finding golang.org/x/oauth2 latest
go: finding google.golang.org/genproto latest
can't load package: package cloud.google.com/go/logging: unknown import path "cloud.google.com/go/logging": ambiguous import: found cloud.google.com/go/logging in multiple modules:
        cloud.google.com/go/logging (/usr/local/google/home/bcmills/src/cloud.google.com/go/logging)
        cloud.google.com/go v0.39.0 (/usr/local/google/home/bcmills/pkg/mod/cloud.google.com/go@v0.39.0/logging)
can't load package: package cloud.google.com/go/logging/apiv2: unknown import path "cloud.google.com/go/logging/apiv2": ambiguous import: found cloud.google.com/go/logging/apiv2 in multiple modules:
        cloud.google.com/go/logging (/usr/local/google/home/bcmills/src/cloud.google.com/go/logging/apiv2)
        cloud.google.com/go v0.39.0 (/usr/local/google/home/bcmills/pkg/mod/cloud.google.com/go@v0.39.0/logging/apiv2)
can't load package: package cloud.google.com/go/logging/internal: unknown import path "cloud.google.com/go/logging/internal": ambiguous import: found cloud.google.com/go/logging/internal in multiple modules:
        cloud.google.com/go/logging (/usr/local/google/home/bcmills/src/cloud.google.com/go/logging/internal)
        cloud.google.com/go v0.39.0 (/usr/local/google/home/bcmills/pkg/mod/cloud.google.com/go@v0.39.0/logging/internal)
can't load package: package cloud.google.com/go/logging/internal/testing: unknown import path "cloud.google.com/go/logging/internal/testing": ambiguous import: found cloud.google.com/go/logging/internal/testing in multiple modules:
        cloud.google.com/go/logging (/usr/local/google/home/bcmills/src/cloud.google.com/go/logging/internal/testing)
        cloud.google.com/go v0.39.0 (/usr/local/google/home/bcmills/pkg/mod/cloud.google.com/go@v0.39.0/logging/internal/testing)
can't load package: package cloud.google.com/go/logging/logadmin: unknown import path "cloud.google.com/go/logging/logadmin": ambiguous import: found cloud.google.com/go/logging/logadmin in multiple modules:
        cloud.google.com/go/logging (/usr/local/google/home/bcmills/src/cloud.google.com/go/logging/logadmin)
        cloud.google.com/go v0.39.0 (/usr/local/google/home/bcmills/pkg/mod/cloud.google.com/go@v0.39.0/logging/logadmin)
```

**Comment by bcmills** [comment] 2019-05-31 15:38
Duplicate of #27063

**Closed by bcmills** 2019-05-31 15:38 UTC
Labels: modules

**Comment by jadekler** [comment] 2019-06-03 16:17
> What do you mean by “codify”?

Stick into the go.mod.

> ~/src/cloud.google.com/go/logging$ gotip mod tidy

Does this edit the go.mod?

**Comment by bcmills** [comment] 2019-06-03 17:04
> Does this edit the go.mod?

It does if there are no errors.

**Comment by jadekler** [comment] 2019-07-12 19:04
For posterity, from https://code-review.googlesource.com/c/gocloud/+/41530:

```
You can compute the rest of the dependencies by running `go mod edit -replace <parent>@<latest version>=./..; go mod tidy`.
```
