### ISSUE TITLE
Suggestion: increase non-blocking writing syntactic sugar

### ISSUE THREAD

**Issue by guonaihong** [golang/go#40777] opened 2020-08-14 04:50 UTC
## idea
There are too many codes in golang for Chan to write without blocking. Often write this code, the mood will be depressed

## current writing
```go
select {
    case m.err <- err:
    default:
}   

```

## hope, possible writing
```go
m.err <<- err
```

**Comment by davecheney** [comment] 2020-08-14 04:51
> m.err <<- err

**Comment by guonaihong** [comment] 2020-08-14 06:17
To make the Chan of go non blocking, you usually need to write the following code.
```go
package main

import (
        "errors"
        "fmt"
)

type message struct {
        err chan error //In concurrency, only the first error is saved
}

func newMessage() *message {
        return &message{err: make(chan error, 1)}
}

func (m *message) writeNoblockingError(err error) {
        select {
        case m.err <- err:
        default:
        }
}

func (m *message) readNoblockingError() error {
        select {
        case err := <-m.err:
                return err
        default:
        }
        return nil
}

func main() {
        m := newMessage()
        m.writeNoblockingError(errors.New("1. error"))
        fmt.Println(m.readNoblockingError())
        fmt.Println(m.readNoblockingError())
}

```

**Comment by guonaihong** [comment] 2020-08-14 06:22
If you have a short code, it can make things simple and interesting
```go
package main

import (
        "errors"
        "fmt"
)       

type message struct {
        err chan error //In concurrency, only the first error is saved
}       

func newMessage() *message {
        return &message{err: make(chan error, 1)}
}       

func main() {
        m := newMessage()
        m.err <<-errors.New("1. error"))
        fmt.Println(<<-m.err)
        fmt.Println(<<-m.err)
}   
```

**Comment by davecheney** [comment] 2020-08-14 06:29
Thank you for your sample code. I see that in this example this would reduce the need for a helper method to turn the receive into a non blocking receive. My next question will be -- does this help in real code? What is the value of doing a non blocking read? Yes it does not block the caller, but what does that permit the caller to do in a _real_ program?

If you could explain how your proposal would affect programs that use methods like `readNoblockingError()` that would be useful for me.

Thank you.

**Comment by networkimprov** [comment] 2020-08-14 17:56
@guonaihong I wouldn't invest time on this; the language avoids multiple ways to write things. See #33892.

The best you can do is write it on one line: `select { case c <- v: default: }`

**Comment by ianlancetaylor** [comment] 2020-08-14 18:58
I don't understand how it is possible to use a statement like `m.err <<-errors.New("1. error"))`.  In order to use a channel correctly you have to know whether the value is sent or not.

Similarly, for `<<-m.err`, you have to know whether a value was received.

As a historical note, before Go 1 you could write

```Go
    if c <- v {
        fmt.Println("sent value on channel")
    } else {
        fmt.Println("failed to send value on channel")
    }
```

But we removed that capability because it was unnecessary given the existence of the `select` statement.  https://go.googlesource.com/go/+/19d9a408451662d09b49fe3b0f1971728e28213f%5E%21/#F0

**Comment by davecheney** [comment] 2020-08-15 02:47
I echo @ianlancetaylor point. On paper it is possible to create a new syntax that makes a One line blocking receive into a non blocking one but this introduces another problem. Channel receive is an expression, it must return a value. In both the original example and your <<- syntax this “nothing was available” value was the zero value for the type. It seems to me that the caller would have to inspect this value to know “was a value received or not” and then you’re back to the same level of verbosity as previous, just one level of abstraction removed.

**Comment by go101** [comment] 2020-08-16 11:55
If the type of `m.err` is a comparable type, the `m.err <<- err` is a comparison expression.

**Comment by seankhliao** [comment] 2022-06-12 00:14
Duplicate of #34203

**Closed by seankhliao** 2022-06-12 00:14 UTC
Labels: WaitingForInfo
