### ISSUE TITLE
x/website: https://go.dev/doc/tutorial/random-greeting

### ISSUE THREAD

**Issue by timcondit** [golang/go#61942] opened 2023-08-10 18:41 UTC
### What is the URL of the page with the issue?
 
 https://go.dev/doc/tutorial/random-greeting
 
### What is your user agent?
 

 
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
 
### Screenshot
 

 
<img width="1171" alt="image" src="https://github.com/golang/go/assets/32091/5493ea17-38df-42cb-be7f-859572592320">
 
### What did you do?
 

 
 Work through the tutorial. 😄 
 
### What did you expect to see?
 
 All of this except the extraneous bullet point.
 
### What did you see instead?

No idea what this refers to:

>Add an init function to seed the rand package with the current time. Go executes init functions automatically at program startup, after global variables have been initialized. For more about init functions, see [Effective Go](https://go.dev/doc/effective_go.html#init).

**Comment by seankhliao** [comment] 2023-08-10 18:51
Duplicate of #60627

**Closed by seankhliao** 2023-08-10 18:51 UTC
Labels: website
