### ISSUE TITLE
PKIX module changes certificate DNs.

### ISSUE THREAD

**Issue by Steve973** [golang/go#57395] opened 2022-12-19 20:32 UTC
https://github.com/golang/go/blob/0b2ad1d815ea8967c49b32d848b2992d0c588d88/src/crypto/x509/pkix/pkix.go#L226

If I create an X509 certificate, and then pull out the subject DN, it looks like this:

C = XX, ST = Confusion, L = Somewhere, OU = first, OU = a002, OU = third, OU = b004, O = example, CN = chunkbox

Note that there are multiple values for OrganizationalUnit, but they are *separate RDNs*.

When I print what is returned from Caddy, which uses the go PKIX module, it looks like this:

CN=chunkbox,OU=first+OU=a002+OU=third+OU=b004,O=example,L=Somewhere,ST=Confusion,C=XX

The subject DN from the certificate is not equivalent to the subject DN that I get back from the PKIX module.

**Comment by seankhliao** [comment] 2022-12-19 20:52
Duplicate of #27401

**Closed by seankhliao** 2022-12-19 20:52 UTC

**Comment by Steve973** [comment] 2022-12-19 20:55
@seankhliao I realized that after filing this one.  That ticket is from back in 2018.  Are there plans to implement some kind of fix?
