### ISSUE TITLE
Segmentation violation while using html/template

### ISSUE THREAD

**Issue by qqshka** [golang/go#49955] opened 2021-12-03 15:25 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Seems so.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ubuntu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3534471074=/tmp/go-build -gno-record-gcc-switches"
GOROOT/bin/go version: go version go1.17.4 linux/amd64
GOROOT/bin/go tool compile -V: compile version go1.17.4
uname -sr: Linux 5.11.0-1020-aws
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
</pre></details>
### What did you do?

https://go.dev/play/p/6GSJPCvMHnn

Providing link to the playground just to share code, you can't really reproduce bug there, you have to run it locally since it uses fair amount of goroutines in order to crash.

### What did you see instead?
unexpected fault address 0x65bc376d
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x65bc376d pc=0x48173e]

**Comment by randall77** [comment] 2021-12-03 16:03
I can reproduce (at 1.17.2). Looks to be fixed at tip. I'll binary search to find out what fixed it.

Looks like general data corruption. I've seen one other failure mode, the GC complaining about a pointer to an unallocated span.

**Comment by randall77** [comment] 2021-12-03 18:26
Looks like it was fixed by https://go-review.googlesource.com/c/go/+/363358/

@cherrymui

**Comment by randall77** [comment] 2021-12-03 18:27
@gopherbot please open a backport issue for 1.17.

**Comment by randall77** [comment] 2021-12-03 18:51
Closing, as fixed at tip. Work will happen on #49961.

**Closed by randall77** 2021-12-03 18:51 UTC

**Comment by dmitshur** [comment] 2021-12-21 22:53
@randall77 Is the reason the backport request was made for 1.17 only because 1.16 doesn't have this problem?

**Comment by cherrymui** [comment] 2021-12-21 22:55
Yes, 1.16 doesn't have this problem. The bug was introduced when adding register ABI support (1.17).
