### ISSUE TITLE
x/tools/gopls: formatting repeats last characters of /**/ comments

### ISSUE THREAD

**Issue by mrg0lden** [golang/go#41128] opened 2020-08-29 16:36 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\MrGol\AppData\Local\go-build
set GOENV=C:\Users\MrGol\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\MrGol\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\MrGol\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\MrGol\AppData\Local\Temp\go-build760839506=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?
I'm using the latest version of Go's extension on vscode with gopls enabled.

Go's extension version: 0.16.1
<pre>
$ gopls version
golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=
</pre>
I also have `formatOnSave` enabled.

### NOTE: I'm aware of the issue #40355 but I'm not sure they're the same problem

<details><summary> for example, this code </summary>

```
package tables

/*
	Lorem ipsum dolor sit amet, consectetur adipiscing elit,
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in 
reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
pariatur. Excepteur sint occaecat cupidatat non proident, sunt in 
culpa qui officia deserunt mollit anim id est laborum.
*/

```
</details>

<details><summary>becomes like this </summary>

```
package tables

/*
	Lorem ipsum dolor sit amet, consectetur adipiscing elit,
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.
*/um.
*/
```
</details>

### What did you expect to see?
Not to have the last characters get repated

### What did you see instead?
Latest characters gets repeated annoyingly.

**Comment by stamblerre** [comment] 2020-08-29 17:12
Duplicate of https://github.com/golang/go/issues/41057

You can work around this for now by using LF line endings instead of CRLF -- you can toggle this setting in the bottom right corner of VS Code. `gofmt` always uses LF line endings, so this shouldn't cause any issues.

**Comment by stamblerre** [comment] 2020-08-29 17:13
Duplicate of https://github.com/golang/go/issues/41057

**Closed by stamblerre** 2020-08-29 17:12 UTC
Labels: Tools, gopls
