### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by samilamti** [golang/go#46830] opened 2021-06-19 20:50 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.16.5 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\thesc\AppData\Local\go-build
set GOENV=C:\Users\thesc\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\thesc\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\thesc\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.5
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\src\hello-go\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\thesc\AppData\Local\Temp\go-build3399508646=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Followed the example for calling [your code from another module](https://golang.org/doc/tutorial/call-module-code), step 5.1

### What did you expect to see?

A successful output.

### What did you see instead?

`go mod: -replace=example: need old[@v]=new[@w] (missing =)`

**Comment by samilamti** [comment] 2021-06-19 20:52
The solution seems to be to avoid the first `=`, i.e. `go mod edit -replace example.com/greetings=../greetings`. As this is a beginner tutorial, it's important to get the small details right as to not discourage new gophers.

**Comment by seankhliao** [comment] 2021-06-19 22:27
Duplicate of #44924

**Closed by seankhliao** 2021-06-19 22:27 UTC
