### ISSUE TITLE
runtime: Inconsistency Multiplication, Division, and Addition Result

### ISSUE THREAD

**Issue by gho1b** [golang/go#51031] opened 2022-02-06 00:07 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.6 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\user\AppData\Local\go-build
set GOENV=C:\Users\user\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\user\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\user\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.6
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\user\Documents\interview-codes\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\user\AppData\Local\Temp\go-build2510967983=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

<img width="444" alt="image" src="https://user-images.githubusercontent.com/10357982/152662018-27fa2597-0a95-4282-a806-fe44fa9c10c4.png">

### What did you expect to see?
I thought that `c` must be eqal to `d`

### What did you see instead?
In another case i get correct results just like this
<img width="569" alt="image" src="https://user-images.githubusercontent.com/10357982/152662831-b15f6112-9b57-4237-a811-af0b136269ed.png">

but the arithmetic give difference results by this formula
 
<img width="558" alt="image" src="https://user-images.githubusercontent.com/10357982/152662862-3c0dd080-7e7b-4045-bfc2-0f0f6239daa5.png">

I got same issue with division and addition
<img width="385" alt="image" src="https://user-images.githubusercontent.com/10357982/152662992-e3af3cfd-7174-4bbf-9674-8a75960e016c.png">

<img width="541" alt="image" src="https://user-images.githubusercontent.com/10357982/152663116-009f4d09-630b-4cce-94e4-38b08249a5b3.png">
<img width="544" alt="image" src="https://user-images.githubusercontent.com/10357982/152663142-29fdf21a-5bb8-47ee-9d8a-241b0e0d4cf8.png">

```
test codes

func c1() {
a	:=	0.61	*	275.0
b	:=	0.62	*	275.0
c	:=	0.63	*	275.0
d	:=	0.64	*	275.0
e	:=	0.65	*	275.0
f	:=	0.66	*	275.0
g	:=	0.67	*	275.0
h	:=	0.68	*	275.0
i	:=	0.69	*	275.0
fmt.Printf("%g\n%g\n%g\n%g\n%g\n%g\n%g\n%g\n%g\n", a, b, c, d, e, f, g, h, i)
}

func c2() {
z := 275.
a	:=	0.61	*	z
b	:=	0.62	*	z
c	:=	0.63	*	z
d	:=	0.64	*	z
e	:=	0.65	*	z
f	:=	0.66	*	z
g	:=	0.67	*	z
h	:=	0.68	*	z
i	:=	0.69	*	z
fmt.Printf("%g\n%g\n%g\n%g\n%g\n%g\n%g\n%g\n%g\n", a, b, c, d, e, f, g, h, i)				
}

func c3() {
	for i := 0; i < 10; i++ {
		a := float64(i)/100 + 0.5
		fmt.Printf("i = %d; a =  %g\n", i, a)
	}
}	

func c4() {
	z := 0.5
	a := 0.01 + z
	b := 0.02 + z
	c := 0.03 + z
	d := 0.04 + z
	e := 0.05 + z
	f := 0.06 + z
	g := 0.07 + z
	h := 0.08 + z
	i := 0.09 + z
	fmt.Printf("%g\n%g\n%g\n%g\n%g\n%g\n%g\n%g\n%g\n", a, b, c, d, e, f, g, h, i)
}

func c5() {
	a := 0.01 + 0.5
	b := 0.02 + 0.5
	c := 0.03 + 0.5
	d := 0.04 + 0.5
	e := 0.05 + 0.5
	f := 0.06 + 0.5
	g := 0.07 + 0.5
	h := 0.08 + 0.5
	i := 0.09 + 0.5
	fmt.Printf("%g\n%g\n%g\n%g\n%g\n%g\n%g\n%g\n%g\n", a, b, c, d, e, f, g, h, i)
}
```

**Comment by robpike** [comment] 2022-02-06 00:32
This is how floating-point calculations work on all computers vs. how constants work in Go. They do not behave the same.

Please read these two links:

https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html
https://go.dev/blog/constants

**Comment by ianlancetaylor** [comment] 2022-02-06 02:47
Please post plain text as plain text, not as images.  Images are difficult to read.  Thanks.

Closing this issue because it is not a bug in Go.  Please comment if you disagree.

**Closed by ianlancetaylor** 2022-02-06 02:47 UTC
