### ISSUE TITLE
cmd/compile: typebits.Set: invalid initial alignment: type Peer has alignment 8, but offset is 4

### ISSUE THREAD

**Issue by stv0g** [golang/go#54991] opened 2022-09-10 12:39 UTC
This is seems to be a regression of: https://github.com/golang/go/issues/54638

### What version of Go are you using (`go version`)?

<pre>
go version go1.19.1 linux/arm64
</pre>

### Does this issue reproduce with the latest release?

Not, tested.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/stv0g/.cache/go-build"
GOENV="/home/stv0g/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/stv0g/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/stv0g/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/stv0g/workspace/cunicu2/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3584615060=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```bash
git clone github.com/stv0g/cunicu
cd cunicu
GOARCH=arm go build ./cmd/cunicu
```

### What did you expect to see?

A successful build for 32-bit architectures.

### What did you see instead?

The following compiler error:

```
# github.com/stv0g/cunicu/pkg/feat/epdisc
<autogenerated>:1: internal compiler error: typebits.Set: invalid initial alignment: type Peer has alignment 8, but offset is 4

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

This issue has been observed for the following `GOARCH=arm, mips` and `GOOS=linux`
64-bit builds (`GOOS=arm64, amd64`) are successful.

**Comment by cuonglm** [comment] 2022-09-10 18:06
It seems to me that CL [425256](https://go-review.googlesource.com/c/go/+/425256) only handles local variables. While the problem in this issue is for arguments which are on stack.

**Comment by cuonglm** [comment] 2022-09-10 18:07
cc @cherrymui @randall77

**Comment by cuonglm** [comment] 2022-09-12 10:57
Minimal reproducer:

```
package p

import (
	"sync/atomic"
)

type I interface {
	M()
}

type S struct{}

func (S) M() {}

type T struct {
	I
	x atomic.Int64
}

func F() {
	t := T{I: S{}}
	t.M()
}
```

**Comment by cuonglm** [comment] 2022-09-13 15:30
Seems that we can't do the same trick with autotmp, the arguments frame offset is used to write function stack map, so it can't be fake.

**Comment by cuonglm** [comment] 2022-09-13 16:46
> I haven't looked into this issue. But I think CL 425256 should handle autotmp. I'll see what we missed.
> 
> 

Yeah, see my comment above.

This issue is about parameters which are on stack, specifically for the reproducer, it's .this receiver of wrapper method.

**Comment by randall77** [comment] 2022-09-15 03:04
Seems to be ok for 386, just not arm.
Looks like this is due to the fact that args start at offset 4 from SP. I'm not sure there's anything we can do here, we'd have to change the calling convention which would break existing arm assembly.
We could ignore this error in cases like this, I guess.
Or copy the arg off into an argtmp that is properly aligned in the prolog.
In any case it seems a very strange case. I don't see any reason to pass an atomic thing around as an argument.
Maybe the error could be better though? (Or as above, just make this not an error.)

**Comment by cuonglm** [comment] 2022-09-15 03:15
> In any case it seems a very strange case. I don't see any reason to pass an atomic thing around as an argument.

To be clear, it's not passing an atomic around, it's the `.this` receiver, which contains atomic thing:

 - `T` has alignment  8
 - `arm` has fixed frame offset 4
 - When calculating offset for `.this` receiver, which has type `T`, we use its offset minus fixed frame size, which is `8 - 4`

Previously, this can't happen because `T` would have alignment `4`, thus frame offset is `4 - 4`, which will satisfy the check.

Maybe for `typesbits.Set`, we should skip the check if `T` alignment is greater than ptr size?

**Comment by stv0g** [comment] 2022-09-15 07:08
Hi there 👋,

is there a chance to work around this bug in my current code?

> In any case it seems a very strange case. I don't see any reason to pass an atomic thing around as an argument.

This hints, that passing it around as a pointer would work?

**Comment by cuonglm** [comment] 2022-09-15 08:09
@stv0g one way to workaround is not using the embedded interface type, making it an explicit field instead. For example, for the reproducer above, you can do:

```
package p

import "sync/atomic"

type I interface {
	M()
}

type S struct{}

func (S) M() {}

type T struct {
	i I
	x atomic.Int64
}

func F() {
	t := T{i: S{}}
	t.i.M()
}
```

Notice `I` is changed from embedded field to `i I`. That way, the compiler won't have to generate the wrapper.

**Comment by randall77** [comment] 2022-09-15 13:48
> Maybe for typesbits.Set, we should skip the check if T alignment is greater than ptr size?

We don't want to do that always, as we do want to be able to align to 8 bytes on 4 byte platforms on the heap. But maybe for all arg/result bitmap generation, yes.

It is all kinda hacky however we handle it.

I was thinking that it wouldn't actually break the calling convention to align things more, as nothing is 8-byte aligned at the moment on arm. So we could pad somehow if we knew one of the args needed >4 byte alignment. But this is going to be a really rare case which makes it hard to ensure that we've got it right. I'm leaning towards just removing the check.

**Comment by cuonglm** [comment] 2022-09-17 12:59
@randall77 @cherrymui should we backport this?

**Comment by stv0g** [comment] 2022-09-19 09:07
> @randall77 @cherrymui should we backport this?

I would highly appreciate it as it breaks valid Go code in the current release.

**Comment by cuonglm** [comment] 2022-09-19 16:01
Reopen for considering backport discussion.

Kindly cc @randall77 @cherrymui

**Comment by cherrymui** [comment] 2022-09-19 16:41
SGTM for backporting.

@gopherbot please backport this to Go 1.19 . This causes valid program fail to compile.

**Comment by cherrymui** [comment] 2022-09-19 16:42
Closing this as it is fixed.

**Closed by cherrymui** 2022-09-19 16:42 UTC
Labels: NeedsFix, compiler/runtime
