### ISSUE TITLE
encoding/json: Unintuitive behavior when using custom UnmarshalText

### ISSUE THREAD

**Issue by glooms** [golang/go#38947] opened 2020-05-08 09:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, it even seems like it was introduced somewhere between `go1.13.9` and `go1.14.2`.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/qlik/.cache/go-build"
GOENV="/home/qlik/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/qlik/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/5646"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/snap/go/5646/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build785744259=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I was trying to Unmarshal a **JSON** body containing `\n` into a `map[String]string` where `String` is `TextUnmarshaler`:
```
type String string

func (s *String) UnmarshalText(text []byte) error {
	*s = String(text)
	return nil
}
```
JSON body:
```json
{
        "Pizza": "Pizza is yummy.\nIt is very yummy.",
        "Apple": "Apples are also yummy."
}
```

An example can be found here: https://play.golang.org/p/V7qY2khOcgH

Note, my key issue is the difference in behavior between the two maps in the playground example.

### What did you expect to see?
A normal map without escaped quotes. Which is the result of using a `map[string]string` instead of a `map[String]string`.

### What did you see instead?
Escaped quotes in the map keys. As if the key wasn't properly tokenized.

**Comment by mvdan** [comment] 2020-05-08 17:41
This sounds like a duplicate of https://github.com/golang/go/issues/38105, which has a fix in master that will be backported for 1.14.3.

**Comment by mvdan** [comment] 2020-05-09 11:33
I can confirm that the tests from https://play.golang.org/p/V7qY2khOcgH pass on master, so this is a duplicate of the issue above. Follow https://github.com/golang/go/issues/38106 for the backport to 1.14.3.

**Closed by mvdan** 2020-05-09 11:33 UTC
Labels: NeedsInvestigation

**Comment by glooms** [comment] 2020-05-10 15:09
Thanks @mvdan
