### ISSUE TITLE
proposal: - :  add a internal type `tuple`, for error checking.

### ISSUE THREAD

**Issue by zzztttkkk** [golang/go#57922] opened 2023-01-19 10:28 UTC
### Author background

- **Would you consider yourself a novice, intermediate, or experienced Go programmer?**

intermediate.

### Proposal

- **What is the proposed change?**

add a internal type `tuple`.
just the return type of function is a tuple, the go user can not create `tuple` in other way.
the compiler should auto generate two functions for each tuple type that contains an `error`.

```go
type TypeA tuple(int, error, error, int)

function (a TypeA) must() (int, int) {
   if a.1 != nul || a.2 != null {
       panic(errors.Merge(a.1, a.2))
   }
   return a.0, a.2
}

function (a TypeA) or(fn function ()(int, int)) (int, int) {
   if a.1 != nul || a.2 != null {
       return fn()
   }
   return a.0, a.2
}

type TypeB tuple(error)

function (b TypeB) must() {
    if b.0 != nil {
        panic(b.0)
    }
}

function (b TypeB) or(fn function () ) {
     if b.0 != nil {
        fn()
     }
}
```

- **Who does this proposal help, and why?**
```go

function add(a, b int) int {
    return a + b
}

type CustomError struct{}

function (ce CustomError) Error() string { return "" }

function (ce CustomError) must() { fmt.Println("0.0") }

function returnErrorPointer() *CustomError{ return nil }

function main(){
    // `(*os.File, error)` is an anonymous tuple. 
    f := os.Open("a.txt").must()
    
    // `error` equals to `(error)`
    f.Close().must()

    // `int` equals to `(int)`, but `(int)` not contains `error`.
    add(1, 2).must() // so this is not validation.

    returnErrorPointer().must() // this will call `(error).must`, not the `CustomError.must`
    ce := returnErrorPointer()
    if ce != nil {
        ce.must() // this will call `CustomError.must`
    }
}
```

- **Is this change backward compatible?**

no.

### Costs
- **How many tools (such as vet, gopls, gofmt, goimports, etc.) would be affected?**

`gopls`

- **What is the compile time cost?**

not much.

- **What is the run time cost?**

no.

- **Can you describe a possible implementation?**

...😶

**Comment by seankhliao** [comment] 2023-01-19 11:04
Duplicate of #32941

**Closed by seankhliao** 2023-01-19 11:04 UTC
Labels: Proposal
