### ISSUE TITLE
go test -run NotAValidTestName Passes

### ISSUE THREAD

**Issue by mibzman** [golang/go#18853] opened 2017-01-30 14:36 UTC
### What version of Go are you using (`go version`)?
`go1.7.1 linux/386`

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="386"
GOBIN="/home/mibzman/go/bin"
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mibzman/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_386"
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build831581489=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

### What did you do?
enter the command `go test -run NotAValidTestName` or any other test name that does not exist

### What did you expect to see?
either `test not found` or `FAIL`

### What did you see instead?
`PASS`

**Comment by minux** [comment] 2017-01-30 14:41
Running an empty set of tests is definitely a pass because nothing fails.

People frequently use -run XXX -bench . to only run the benchmarks, so if
we change the behavior of go test forum NotAValidTestName, this idiom won't
work anymore.

**Comment by evverx** [comment] 2017-01-30 15:20
duplicate of https://github.com/golang/go/issues/15211

**Closed** 2017-01-30 16:20 UTC
