### ISSUE TITLE
x/debug/internal/gocore: `TestVersions/goroot` persistently failing with go tip

### ISSUE THREAD

**Issue by bcmills** [golang/go#64059] opened 2023-11-10 15:02 UTC
Example:
https://build.golang.org/log/921d95ba40810cde564beec65d12b3714c642e57

Looks like it was fixed for a while as of https://go.dev/cl/540297, but broke again around https://go.dev/cl/538217.

(attn @mknyszek)

**Comment by mknyszek** [comment] 2023-11-10 15:25
This is a duplicate of #64049.

**Closed by mknyszek** 2023-11-10 15:25 UTC
Labels: NeedsFix, release-blocker, compiler/runtime

**Comment by mknyszek** [comment] 2023-11-10 15:27
And thanks! I copied over some of the additional context you added.
