### ISSUE TITLE
x/website: redirect wrongly to golang.google.cn

### ISSUE THREAD

**Issue by xxchan** [golang/go#47846] opened 2021-08-20 15:25 UTC
I was reading go blog: 

https://blog.golang.org/context 

Yesterday, it redirects https://golang.google.cn/context and shows: 
![image](https://user-images.githubusercontent.com/37948597/130255971-814b42c1-8a0c-4064-b776-162e4441ea05.png)

Similarly, report a website issue (https://golang.google.cn/issues/new?title=x/website:) redirects to https://golang.google.cn/issues/new?title=x/website: and show similar error.

And yesterday I found go.dev and blog https://go.dev/blog/context, it didn't redirect. 
But today it also redirects to https://golang.google.cn/blog/context

**Comment by mknyszek** [comment] 2021-08-20 15:39
Duplicate of #47808.

**Closed by mknyszek** 2021-08-20 15:39 UTC
