### ISSUE TITLE
x/mobile/cmd/gomobile: Cannot init gomobile

### ISSUE THREAD

**Issue by xsun2001** [golang/go#34671] opened 2019-10-03 04:45 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xsun2001/Library/Caches/go-build"
GOENV="/Users/xsun2001/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xsun2001/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pw/6r37xyv50fx7gwmpg0bz56mh0000gn/T/go-build107464107=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
$ go get golang.org/x/mobile/cmd/gomobile
package golang.org/x/mobile/cmd/gomobile: unrecognized import path "golang.org/x/mobile/cmd/gomobile" (https fetch: Get https://golang.org/x/mobile/cmd/gomobile?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

$  GO111MODULE=on GOPROXY=https://goproxy.io go get golang.org/x/mobile/cmd/gomobile
go: finding golang.org/x/mobile latest
go: downloading golang.org/x/mobile v0.0.0-20191002175909-6d0d39b2ca82
go: extracting golang.org/x/mobile v0.0.0-20191002175909-6d0d39b2ca82

$ gomobile init
gomobile: /usr/local/go/bin/go install golang.org/x/mobile/cmd/gobind failed: exit status 1
can't load package: package golang.org/x/mobile/cmd/gobind: cannot find package "golang.org/x/mobile/cmd/gobind" in any of:
	/usr/local/go/src/golang.org/x/mobile/cmd/gobind (from $GOROOT)
	/Users/xsun2001/go/src/golang.org/x/mobile/cmd/gobind (from $GOPATH)

$ GO111MODULE=on GOPROXY=https://goproxy.io gomobile init
gomobile: /usr/local/go/bin/go install golang.org/x/mobile/cmd/gobind failed: exit status 1
can't load package: package golang.org/x/mobile/cmd/gobind: cannot find package "golang.org/x/mobile/cmd/gobind" in any of:
	/usr/local/go/src/golang.org/x/mobile/cmd/gobind (from $GOROOT)
	/Users/xsun2001/go/src/golang.org/x/mobile/cmd/gobind (from $GOPATH)
```

### What did you expect to see?

`gomobile init` passes.

### What did you see instead?

Due to my poor network, I cannot directly call `go get` or I will get a timeout error. But when I use `goproxy.io` as my proxy, it seems that `gomobile` haven't been installed correctly. It said there wasn't `gobind` even I manually `go get` it. Sorry for my poor English.

**Comment by agnivade** [comment] 2019-10-03 14:43
gomobile does not work in module mode. I believe this is a duplicate of https://github.com/golang/go/issues/27234.

**Comment by andybons** [comment] 2019-10-03 15:46
Duplicate of #27234

**Closed by andybons** 2019-10-03 15:46 UTC
Labels: NeedsInvestigation, mobile
