### ISSUE TITLE
Revisit "cannot assign to struct field in map"

### ISSUE THREAD

**Issue by ivoras** [golang/go#53857] opened 2022-07-13 21:21 UTC
Since maps are not threadsafe, what is the current explanation for the defficiency of not allowing mutation of structs in a map, and can it be revisited?

Arrays work fine, and I'd like to understand what's preventing maps from working also. In both cases, the pointer to the struct is calculated at runtime, and then it seems like it should be straightforward from there? Surely the entry will not be moved in memory by hashmap rebalancing since 2 goroutines are not allowed to modify the map?

go 1.18

Code:

```
	m = map[int]S{}
	m[10] = S{s: "string", n: 5}
	m[10].Mutate()
	m[10].n++
```

Expected result: compiles

Result: fails to compile

A more self-contained example: https://go.dev/play/p/2KUrin-0EJM

**Comment by mvdan** [comment] 2022-07-13 22:05
Please note that you should fill https://github.com/golang/proposal/blob/master/go2-language-changes.md when proposing a language change.

**Comment by mvdan** [comment] 2022-07-13 22:05
Or, if this is a question, see https://golang.org/wiki/Questions.

**Comment by seankhliao** [comment] 2022-07-13 22:26
Duplicate of #3117

**Closed by seankhliao** 2022-07-13 22:26 UTC
Labels: WaitingForInfo
