### ISSUE TITLE
invalid syntax when checking equality with struct literal in if statement

### ISSUE THREAD

**Issue by rprtr258** [golang/go#62426] opened 2023-09-02 10:52 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 linux/amd64
</pre>

### What did you do?

```go
type S struct{}

s := S{}
if s == S{} {
  fmt.Println("equal")
}
```

### What did you expect to see?
Code compiles and checks for structs equality

### What did you see instead?
```
./prog.go:9:14: syntax error: unexpected { at end of statement
./prog.go:12:1: syntax error: non-declaration statement outside function body
```

It seems that parser sees above if statement like this:
```go
if s == S {
} { // unexpected '{' here
  fmt.Println("equal")
}
```

Though it is obviously invalid as `S` is not value to compare with `s`. As for me desired behavior is to interpret `S{}` as struct literal and code should compile.

**Comment by seankhliao** [comment] 2023-09-02 10:55
Duplicate of #9181

**Closed by seankhliao** 2023-09-02 10:55 UTC
