### ISSUE TITLE
x/net/html: wrong parse result for html with clauses inside table elements

### ISSUE THREAD

**Issue by jialiangs** [golang/go#48363] opened 2021-09-13 21:26 UTC
### What version of Go are you using (`go version`)?
1.15.4

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOARCH="amd64"

### What did you do?
```
func getHTMLBody(doc *html.Node) (*html.Node, error) {
	var b *html.Node
	var f func(*html.Node)
	f = func(n *html.Node) {
		if n.Type == html.ElementNode && n.Data == "body" {
			b = n
		}
		for c := n.FirstChild; c != nil; c = c.NextSibling {
			f(c)
		}
	}
	f(doc)
	if b != nil {
		return b, nil
	}
	return nil, nil
}

func renderHTMLBody(n *html.Node) string {
	var buf bytes.Buffer
	w := io.Writer(&buf)
	html.Render(w, n)
	return buf.String()
}

func Test(t *testing.T) {
	reqContents := "{{#if items}} <table><tbody> <tr><td><strong>header</strong></td></tr> {{#each items}} <tr><td>{{this.name}}</td></tr> {{/each}} </tbody></table> {{/if}}"

	html, _ := html.Parse(strings.NewReader(reqContents))
	body, _ := getHTMLBody(html)
	fmt.Println(renderHTMLBody(body))
}
```

### What did you expect to see?
```
{{#if items}} <table><tbody> <tr><td><strong>header</strong></td></tr> {{#each items}} <tr><td>{{this.name}}</td></tr> {{/each}} </tbody></table> {{/if}}
```

### What did you see instead?
The sequence of elements has been changed after parsing the HTML content. I tried the java HTML parser `jsoup`, it works as expected, so I guess there is an issue with the library `golang.org/x/net/html`.
```
<body>{{#if items}}  {{#each items}}  {{/each}} <table><tbody> <tr><td><strong>header</strong></td></tr><tr><td>{{this.name}}</td></tr></tbody></table> {{/if}}</body>
```

**Comment by seankhliao** [comment] 2021-09-15 16:30
Duplicate of #7232

**Comment by seankhliao** [comment] 2021-09-15 16:30
Note this is the same result as rendered by Chrome

**Closed by seankhliao** 2021-09-15 16:30 UTC

**Comment by jialiangs** [comment] 2021-09-15 17:02
@seankhliao thanks for your reply! Yes, the rendered results are the same by Chrome. But we need to use this `if-each` clause to automatically generate the table elements. Now since after parsing, the sequence of the elements has been changed, it can be used to automatically generate table elements anymore.
