### ISSUE TITLE
proposal: pointer: new package handling pointer

### ISSUE THREAD

**Issue by sivchari** [golang/go#66341] opened 2024-03-15 16:50 UTC
### Proposal Details

I propose pointer package that is handling pointer type. Especially, I want to add `pointer.To` that provides the pointer of type that function receives. I know unsafe package and it manage some function about pointer, but we can change to make the package invoke pointer package. And this API is accepted, we will be able to discuss the new API that is related with pointer based on it. And many developers use alike implementation (e.g. [ptr](https://pkg.go.dev/k8s.io/utils/ptr#To) that is provided by Kubernetes community). So I think it's time to integrate this function to Go.

**Comment by seankhliao** [comment] 2024-03-15 16:52
Duplicate of #64749

**Closed by seankhliao** 2024-03-15 16:52 UTC
Labels: Proposal
