### ISSUE TITLE
Golang index server returns a non-existent package version

### ISSUE THREAD

**Issue by yurivict** [golang/go#54515] opened 2022-08-18 03:41 UTC
Last version of ```github.com/shenwei356/kmcp``` is 0.8.3.1 but the index server returns 0.8.4...

```
{"Path":"github.com/shenwei356/kmcp","Version":"v0.8.4-0.20220816044600-3dc30b20c9cf","Timestamp":"2022-08-17T07:34:22.230705Z"}
```

### What version of Go are you using (`go version`)?

```go version go1.19 freebsd/amd64```

**Comment by seankhliao** [comment] 2022-08-18 07:31
go only uses semver (major.minor.patch-other)
any other format such as 4 dotted parts are converted to pseudoversions with the next patch version up and prerelease parts in.

see https://go.dev/ref/mod for details

closing as working as intended

**Closed by seankhliao** 2022-08-18 07:31 UTC
