### ISSUE TITLE
Confusing for these codes of interface implementation and calling.Someone please help.

### ISSUE THREAD

**Issue by zeerax25** [golang/go#28149] opened 2018-10-11 13:54 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

- go version go1.11 darwin/amd64

### Does this issue reproduce with the latest release?
- not testing

### What operating system and processor architecture are you using (`go env`)?

- not related

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

Code 1:
```
package main

import "fmt"

type myintf interface {
	GotU()
}

type esc struct {
	 i int
}

//func GotU(t esc);
func (e esc)GotU() {
	e.i = 10
}

func TestFunc(it myintf) string {
	it.GotU()
	return  "kk"
}

func main() {

	var test esc
	test.i = 9

	TestFunc(test)

	fmt.Println(test.i)

}
```

Code 2:
```
package main

import "fmt"

type myintf interface {
	GotU()
}

type esc struct {
	 i int
}

func (e esc)GotU() {
	e.i = 10
}

func TestFunc(it myintf) string {
	it.GotU()
	return  "kk"
}

func main() {

	var test esc
	test.i = 9

	TestFunc(test)

	fmt.Println(test.i)

}
```
Code 3:
```
package main

import "fmt"

type myintf interface {
	GotU()
}

type esc struct {
	 i int
}

func (e *esc)GotU() {
	e.i = 10
}

func TestFunc(it myintf) string {
	it.GotU()
	return  "kk"
}

func main() {

	var test esc
	test.i = 9

	TestFunc(test)

	fmt.Println(test.i)

}
```

### What did you expect to see?
- nothing to expect

### What did you see instead?
code 1 output: 9
code 2 output: 9
code 3 cannot be compiled due to a type mismatch
---
Since only ```func (e esc)GotU()``` implemented, why should both pieces of code work and deliver the same result?
It's kind of confusing for me to pass a pointer of struct to that function (TestFunc) to get the same answer.

**Comment by ALTree** [comment] 2018-10-11 14:04
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions about the language. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2018-10-11 14:04 UTC
