### ISSUE TITLE
image/jpeg: unsupported JPEG feature: luma/chroma subsampling ratio

### ISSUE THREAD

**Issue by benjiro29** [golang/go#62421] opened 2023-09-01 22:59 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.21.0 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='0'
GOMOD='/dev/null'
GOWORK='/root/Indribell/go.work'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2633292476=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

```Go
img, _, err = image.Decode(reader)
if err != nil {
	return Log.Error(err, `Decode`)
}
```

https://asuracomics.com/wp-content/uploads/2022/07/Untitled-1.jpg
https://asuracomics.com/wp-content/uploads/2021/12/heavenlydemoninstructor-1.jpg

### What did you expect to see?

No error

### What did you see instead?

unsupported JPEG feature: luma/chroma subsampling ratio)

While the images are displayed correctly in multiple programs, Go Image can simply not decode them without erroring out.

**Comment by ianlancetaylor** [comment] 2023-09-01 23:03
CC @nigeltao

**Comment by dmitshur** [comment] 2023-09-02 00:02
Issues #13614 and #2362 seem related.

**Comment by nigeltao** [comment] 2023-10-07 01:40
Those asuracomics.com links don't work for me, but I suspect that this is a duplicate of #2362.

In hindsight, the [image.YCbCrSubsampleRatio](https://github.com/golang/go/blob/6e8caefc19cae465444775f6cd107b138a26cce7/src/image/ycbcr.go#L11-L21) design, which only supports a fixed allow-list of luma/chroma subsampling ratios, was a mistake. But, due to Go 1 compatibility, fixing that is not going to be easy, per https://github.com/golang/go/issues/2362#issuecomment-66059399

**Closed by nigeltao** 2023-10-07 01:40 UTC
Labels: NeedsInvestigation, FeatureRequest

**Comment by nigeltao** [comment] 2023-10-07 01:41
Issue #13614 is unrelated, as it involves Go's JPEG *encoder*. This issue is about the *decoder*.

**Comment by benjiro29** [comment] 2023-10-07 08:55
> Those asuracomics.com links don't work for me, but I suspect that this is a duplicate of #2362.

Updated link that is working:

https://asuratoon.com/wp-content/uploads/2022/07/Untitled-1.jpg
https://asuratoon.com/wp-content/uploads/2021/12/heavenlydemoninstructor-1.jpg

**Comment by KevinColemanInc** [comment] 2024-01-23 04:25
@benjiro29 (or anyone else), is there a quick fix for this? My guess is to use a c-library to parse it, but i'd prefer a pure golang solution.

**Comment by benjiro29** [comment] 2024-01-23 22:25
> @benjiro29 (or anyone else), is there a quick fix for this? My guess is to use a c-library to parse it, but i'd prefer a pure golang solution.

There is zero solutions for this issue. I bypass it by simply not handling images that have this issue and keeping the original size (with consequences if its like a 8MB image that is now being displayed as a thumb image)...

As long as the attitude prevails of "we made a booboo by assuming nobody will run into this and now we fear fixing it because of backward compatibility" ... with that attitude, it will never get fixed. This issue is known for 13 years, ... 

You can not rely on other image handling libraries, as all fall back to Go its build in Image in some way. Tried a bunch, all had the same issue.

Your only option is to waste a tone of time by including a external library and going to cgo route or include a external program that you call for dealing with those images. Both are horrible solutions.  

So, do like the go dev's. ignore the issue by keeping the original image and let the dice roll.
