### ISSUE TITLE
cmd/internal: AVX2 instruction VPERMQ does not accept 8 bit constant

### ISSUE THREAD

**Issue by aead** [golang/go#24516] opened 2018-03-24 15:26 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.10 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/andreas/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/andreas/go"
GORACE=""
GOROOT="/home/andreas/.go/1.10"
GOTMPDIR=""
GOTOOLDIR="/home/andreas/.go/1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build007157077=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

```
TEXT ·foo(SB),4,$0-8
         VPERMQ $-40, Y0, Y0
         VPERMQ $216, Y0, Y0
         RET
```

### What did you expect to see?

Assembler should generate valid op-codes.

### What did you see instead?

Assembler fails with: 
`asm: invalid instruction: 00117 (foo_amd64.s:336) VPERMQ  $216, Y0, Y0`

### Background

Both instructions are semantically equal: `VPERMQ $-40, Y0, Y0 == VPERMQ $216, Y0, Y0`
It seems to be similar to #16499 since negative constants work and produce correct results.

/cc @TocarIP

**Comment by mvdan** [comment] 2018-03-24 19:46
Duplicate of #24378, which is already fixed in tip.

**Closed by mvdan** 2018-03-24 19:46 UTC
