### ISSUE TITLE
tls: failed to verify certificate: x509: “CloudFlare Origin Certificate” certificate is not standards compliant

### ISSUE THREAD

**Issue by hktalent** [golang/go#62361] opened 2023-08-30 00:33 UTC
macOS 13.5 (22G74)
$ go version
go version go1.20.7 darwin/amd64

···
$ go tool pprof -seconds=600 -http=:9999 https://127.0.0.1:8081/debug/pprof/heap
Fetching profile over HTTP from https://127.0.0.1:8081/debug/pprof/heap?seconds=600
Please wait... (10m0s)
https://127.0.0.1:8081/debug/pprof/heap: Get "https://127.0.0.1:8081/debug/pprof/heap?seconds=600": tls: failed to verify certificate: x509: “CloudFlare Origin Certificate” certificate is not standards compliant
failed to fetch any source profiles
···

But version 1.9 is correct

**Comment by seankhliao** [comment] 2023-08-30 07:34
Duplicate of #51991

**Closed by seankhliao** 2023-08-30 07:34 UTC
