### ISSUE TITLE
go/ast: End() for *BlockStmt incorrect when there is no closing brace

### ISSUE THREAD

**Issue by myitcv** [golang/go#33649] opened 2019-08-14 13:51 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +61bb56ad63 Mon Aug 12 23:12:29 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/playground/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build692430293=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
)

func main() {
	src := `package main

func main() {
`

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", src, parser.AllErrors)
	if f == nil {
		panic(err)
	}

	var tf *token.File
	fset.Iterate(func(f *token.File) bool {
		tf = f
		return true
	})

	fd := f.Decls[len(f.Decls)-1].(*ast.FuncDecl)

	fmt.Printf("tf.Base() + tf.Size(): %v\n", tf.Base()+tf.Size())
	fmt.Printf("fd.End(): %v\n", fd.End())
}
```

https://play.golang.org/p/A56nT3ypuyJ

### What did you expect to see?

```
tf.Base() + tf.Size(): 29
fd.End(): 29
```

### What did you see instead?

```
tf.Base() + tf.Size(): 29
fd.End(): 30
```

cc @griesemer 

FYI @rogpeppe @mvdan

**Comment by griesemer** [comment] 2019-08-14 16:48
Thanks for the nice test case. I looked at this a bit and it's not obviously clear (to me) what the correct solution is here. I suppose we don't want an `End()` position that is past the source's length. The problem is that the parser doesn't know what's going to happen with the position it collects: in this case it simply assumes the position of the (missing) `}` is at EOF, which is arguably a "correct" assumption. It's the `go/ast` which adds 1 (for the length of `}`) to that position. But the `go/ast` doesn't know that this is past EOF.

One way of handling this in the parser is to assume that the position of a missing token is the current position minus the length of the missing token - then, any correction made by the `go/ast` would be "correct". But that could also place a missing token before a preceding token, which may have other unexpected side-effects.

@myitcv What is the specific use case where this poses a problem? Perhaps this can help identifying a good solution.

**Comment by griesemer** [comment] 2019-08-14 17:04
Actually, the correct fix would probably be to not record a position for the closing `}` if it is missing. Then the `go/ast` could detect that and determine the `End()` of the `BlockStmt` as the end of the last statement inside.

The same problem affects a few other nodes as well.

**Comment by myitcv** [comment] 2019-08-14 17:59
> What is the specific use case where this poses a problem? Perhaps this can help identifying a good solution.

The use case is providing AST-oriented motions within an editor, in this case Vim using [`govim`](https://github.com/myitcv/govim). For example, the key combination `]]` is mapped to "move to the next `End()` (as in `go/ast.Node.End()`) of the `*ast.File`'s top level declarations." These motions obviously need to work in the case of incomplete files, i.e. with syntax errors. 

> Actually, the correct fix would probably be to not record a position for the closing } if it is missing. Then the go/ast could detect that and determine the End() of the BlockStmt as the end of the last statement inside.

Given the use case I've described, I agree this sounds correct.

**Closed** 2019-10-28 20:48 UTC
Labels: Thinking
