### ISSUE TITLE
x/tools/gopls: autocompletion overriding content

### ISSUE THREAD

**Issue by szmcdull** [golang/go#42634] opened 2020-11-13 06:04 UTC
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.15.3 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.51.1 e5a624b788d92b8d34d1392e4c4d9789406efe8f x64

- Check your installed extensions to get the version of the VS Code Go extension 
	- <Paste Go extension version here>
- Run `go env` to get the go development environment details
	- <Paste the output here>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
- "go.useLanguageServer": true,
- "go.buildTags": "debug",
- "go.lintTool": "golangci-lint",

### Describe the bug
When accepting auto-completion, the suggestion is replaced over the current word (including the part after the cursor). 
Other languages such as python or javascript will not replace the part after the cursor.

**Comment by muirdm** [comment] 2020-11-21 21:42
I think this is a dupe of #40871.

**Comment by stamblerre** [comment] 2020-11-21 22:55
Duplicate of https://github.com/golang/go/issues/40871

**Closed by stamblerre** 2020-11-21 22:55 UTC
Labels: Tools, gopls
