### ISSUE TITLE
the kind of using of "goto" is wrong ? why ?help!thanks!

### ISSUE THREAD

**Issue by AnkoGo** [golang/go#41069] opened 2020-08-27 09:53 UTC
I find this issues of "goto" ,this is my fault?
![image](https://user-images.githubusercontent.com/58206163/91425642-fcf26c00-e88d-11ea-9928-845c07a23818.png)

**Comment by ALTree** [comment] 2020-08-27 10:29
Yes, the code is wrong. The `goto` at line 28 causes the function to jump unconditionally to line 46, so the `return` you put on line 44 is always skipped (and does nothing). 

Please note that the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-08-27 10:29 UTC
