### ISSUE TITLE
x/tools/gopls: high CPU & memory for minutes in "Saving foo.go: Getting code actions from "Go" ..."

### ISSUE THREAD

**Issue by bradfitz** [golang/go#57707] opened 2023-01-09 19:51 UTC
### What version of Go are you using (`go version`)?

Go 1.19.4
gopls 0.11.0

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

darwin/arm64 Visual Studio Code => ssh to linux/amd64 

### What did you do?

I'm trying to become a Visual Studio Code + gopls user, trying to break my emacs habit. I use Visual Studio Code on a Mac over SSH to a Linux server, where gopls/etc runs remotely.

A good fraction of the time when I save in VS Code, I see:

<img width="473" alt="Screenshot 2023-01-09 at 11 44 22 AM" src="https://user-images.githubusercontent.com/2621/211395100-102225ab-e0fc-4e85-b327-4bb1cda19171.png">

For minutes.

Meanwhile, gopls is using 4-8 GB or more of memory and using tons of CPU.

`perf top` says:

<img width="1021" alt="Screenshot 2023-01-09 at 11 44 54 AM" src="https://user-images.githubusercontent.com/2621/211395262-7dee5507-0011-4862-b150-04f05a64f73b.png">

### What did you expect to see?

Faster, I guess.

### What did you see instead?

Slower than it seems it should be.

Is this a bug?

I don't know how to go about debugging gopls.

**Comment by renthraysk** [comment] 2023-01-09 22:35
Similar experience. Saving whilst not having a go.mod file present grinds to crawl.
I believe this is #56496 related.

**Comment by findleyr** [comment] 2023-01-12 14:39
Gopls is generally resource hungry on large (or even medium large) workspaces. Furthermore, it is sensitive to which directory you open.

Couple questions:
- Which directory do you open, relative to your go.mod files?
- How many files / packages do you have in your module / workspace?

From that profile, it looks like the typical parsing / typechecking / gc slowness, so I'm not sure there's a solution for you with the current execution model. The issue @renthraysk cited is a known problem related to scanning files, but that doesn't seem to be the cause of what you're experiencing.

@adonovan  and I are working to move gopls off of its monolithic build model, which should finally allow us to solve this category of problem.

**Comment by josharian** [comment] 2023-01-12 15:15
FWIW, in my experience, this can occur when gopls gets into a bad state. It is responsive (enough) working on a project, it gets unhappy, and then saving fails until you kill and restart it.

For others experiencing this, you can get past it in a pinch by using the VSCode command palette to do "Save without formatting". And then restarting. :/

**Comment by joel-rieke** [comment] 2023-01-26 17:09
I had something similar happen last weekend...  Gopls was going bonkers taking over cpu on my box.  I couldn't get back control of the UI and I made the mistake of hard rebooting in the middle (just trying to get my cpu back) which unfortunately bricked my harddrive and OS.  I'd had problems with this pet project in the past using gopls.  I think it may have had something to do with having a largish bound resource file (but not unreasonable) but that's only a wild guess because I can't repro due to bricking.

**Comment by findleyr** [comment] 2023-01-26 17:12
Oof, sorry about that @joel-rieke 

It sounds like there may be something we don't understand going on here, but we are in the process of making major changes to the way gopls executes (https://go.dev/issue/57987), and my hope is that it makes all of these problems go away.

**Comment by adonovan** [comment] 2023-05-10 19:31
@bradfitz, do try out gopls@master and tell us what you find. We're close to the v0.12.0 release, which should reduce stable state memory usage by 5-10x for large projects.

**Comment by pavlelee** [comment] 2023-05-13 12:27
@adonovan I still have this problem when I use the master, especially when I copy the code from other places and there are many errors in it, it will be very slow to save only when there are errors

**Comment by MadeBaruna** [comment] 2023-05-13 16:16
I have similar issue when opening and saving projects with VSCode thru SSH running Arch VM, cpu usage will skyrocket to 100%. Tried opening/saving the same project on the host (Windows) and another VM running Ubuntu, and it works fine. (project is very small with few files) any pointer how to debug this?

**Comment by adonovan** [comment] 2023-05-19 15:15
@findleyr This looks like an exact dup of the problems were were debugging yesterday due to VSCode's slow processing of glob patterns consisting of very long comma-separated lists of directories (see https://github.com/golang/go/issues/60089 and CL 496186), and perhaps also sequential execution of go mod tidy, and the fact that this is done even when the metadata hasn't changed.
(See also #59176, perhaps another dup.)

**Comment by findleyr** [comment] 2023-05-22 19:15
@adonovan let's close this after we cut the release candidate containing our fix. Then it will be easy for people to test, and comment if they can still reproduce the freezing.

I am 92% sure this is a dupe, and now fixed.

**Closed** 2023-05-25 13:31 UTC
Labels: gopls, Tools, gopls/performance

**Comment by Praveenrajmani** [comment] 2023-06-13 06:59
> go install golang.org/x/tools/gopls@v0.12.0-pre.3

**Comment by bradfitz** [comment] 2023-06-14 04:34
I don't want to jinx it, but so far so good! 🤞

**Comment by joshghent** [comment] 2023-11-10 09:50
Apologies for commenting on a closed issue, but I'm getting this same issue and it's completely crashing my macbook unless I kill the `go` or `gopls` process manually.
Loving learning Golang but this issue is a bit frustrating. Thanks in advance for looking at this issue.

Details:
`go version go1.21.4 darwin/arm64`
`M1 Pro 16GB - Ventura 13.6 (22G120)`

**Comment by findleyr** [comment] 2023-11-10 13:24
Hi @joshghent . Could you please open a new issue, filling out the gopls issue template?
https://github.com/golang/go/issues/new/choose

**Comment by joel-rieke** [comment] 2023-11-10 16:13
> Apologies for commenting on a closed issue, but I'm getting this same issue and it's completely crashing my macbook unless I kill the `go` or `gopls` process manually. Loving learning Golang but this issue is a bit frustrating. Thanks in advance for looking at this issue.
> 
> Details: `go version go1.21.4 darwin/arm64` `M1 Pro 16GB - Ventura 13.6 (22G120)`

Bummer... thought this was fixed... On linux it seems fine lately...  But haven't tried with latest go1.21.4  -- debugging the same project of mine that caused this behavior.

**Comment by joel-rieke** [comment] 2023-11-10 16:15
Is your gopls up to date?

**Comment by findleyr** [comment] 2023-11-10 16:15
It really should be better now: the code actions operation is now essentially a no-op, except for running `goimports`, which can sometimes hang (https://go.dev/issue/59216).
