### ISSUE TITLE
x/pkgsite: Go 1.18 packages with generics are not listed

### ISSUE THREAD

**Issue by gmlewis** [golang/go#50012] opened 2021-12-07 00:52 UTC
(I know that Go 1.18 hasn't been released yet, but thought it might be helpful to get a jump on this bug before its release.)
 
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/gmlewis/advent-of-code-2021@v0.0.6
 
 
### What is your user agent?
 
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
 
 
### Screenshot
 
![missing-go-1 18-packages](https://user-images.githubusercontent.com/6598971/144945710-12e5c977-c594-4ac2-b9a8-b24e37cfd21c.png)
 
### What did you do?
 
I requested that https://pkg.go.dev/github.com/gmlewis/advent-of-code-2021@v0.0.6 be generated.
 
 
### What did you expect to see?
 
I expected to also see the packages: `enum`, `maps`, and `stream` (in addition to the correctly-displayed `must`, `strfn`, and `test` packages).
 
### What did you see instead?

Only the packages without Go 1.18 generics are displayed: `must`, `strfn`, and `test`.

**Comment by fzipp** [comment] 2021-12-07 05:55
Duplicate of #48264

**Closed** 2021-12-07 07:38 UTC
Labels: pkgsite
