### ISSUE TITLE
misc/cgo/testcshared: sometimes stalls on windows-amd64-longtest builder in non-sharded longtest mode

### ISSUE THREAD

**Issue by dmitshur** [golang/go#39665] opened 2020-06-17 20:30 UTC
I've observed the following failure scenario while testing all.bash in non-sharded longtest mode via `x/build/cmd/release`. The build stalled on the `##### ../misc/cgo/testcshared` test and did not make progress for several hours:

```
[...]
PASS
scatter = 0000000000EDD070
sqrt is: 0
hello from C
ok  	misc/cgo/test	7.344s

##### ../misc/cgo/testgodefs
PASS

##### ../misc/cgo/testso
ok  	misc/cgo/testso	1.977s

##### ../misc/cgo/testsovar
ok  	misc/cgo/testsovar	2.309s

##### ../misc/cgo/testcarchive
PASS

##### ../misc/cgo/testcshared
```

I've observed this just twice, on the latest commit of `release-branch.go1.14`, and on a recent commit of `master` (to be 1.15), using the `windows-amd64-longtest` builder:

```
$ release -target=windows-amd64-longtest -watch -version go1.14beta2 -rev=e98cafae04b78f1e994d52ea66d228451c8e6f81
$ release -target=windows-amd64-longtest -watch -version go1.15beta2 -rev=dea6d928f6c293631ce93bd3a3bb8b4020188954
```

It didn't happen a second time, after I re-tried. I don't yet know how common of an occurrence this is.

This is the tracking issue to collect information and investigate.

/cc @cagedmantis @toothrot @andybons @ianlancetaylor @bcmills

**Comment by dmitshur** [comment] 2020-06-24 19:30
There may have been an occurrence of this exact problem or a similar problem in the SlowBot run of [CL 239738](https://golang.org/cl/239738) just [now](https://farmer.golang.org/temporarylogs?name=windows-amd64-2016&rev=faab201f9f528f7f2cb53420308f0e6fe34028c6&st=0xc00faebd40):

```
[...]
scatter = 0000000000569860
sqrt is: 0
hello from C
ok  	misc/cgo/test	16.696s

##### ../misc/cgo/testgodefs
PASS

##### ../misc/cgo/testso
ok  	misc/cgo/testso	1.981s

##### ../misc/cgo/testsovar
ok  	misc/cgo/testsovar	2.256s

##### ../misc/cgo/testcarchive
PASS


Error: runTests: dist test failed: all buildlets had network errors or timeouts, yet tests remain
```

**Comment by bcmills** [comment] 2020-11-18 15:44
It appears to stall in sharded mode too: I hit a repro in a SlowBot run for https://golang.org/cl/270979.

(https://farmer.golang.org/temporarylogs?name=windows-amd64-longtest&rev=0d99f70ecc63fdeab8675cdc9d07f957409c8bf0&st=0xc013702680)

**Comment by bcmills** [comment] 2020-11-18 15:45
Depending on how often this occurs, it might be a blocker for #42661. 😞

**Comment by bcmills** [comment] 2020-11-18 15:50
Hmm, I wonder if this is related to #39349‽

**Comment by bcmills** [comment] 2021-01-25 14:32
From [CL 285720](https://golang.org/cl/285720) 
(https://farmer.golang.org/temporarylogs?name=windows-amd64-2016&rev=26b0deca44e0cbf06661927dcd8b8546c5903aaf&st=0xc011c041a0):
```
  2021-01-25T14:15:33Z no_new_tests_remain 10.240.0.109:80
  2021-01-25T14:15:33Z closed_helper 10.240.0.109:80
  2021-01-25T14:16:03Z still_waiting_on_test testcshared
  2021-01-25T14:16:33Z still_waiting_on_test testcshared
  2021-01-25T14:17:03Z still_waiting_on_test testcshared
  2021-01-25T14:17:33Z still_waiting_on_test testcshared
  2021-01-25T14:18:03Z still_waiting_on_test testcshared
  2021-01-25T14:18:33Z still_waiting_on_test testcshared
  2021-01-25T14:19:03Z still_waiting_on_test testcshared
  2021-01-25T14:19:33Z still_waiting_on_test testcshared
  2021-01-25T14:20:03Z still_waiting_on_test testcshared
  2021-01-25T14:20:33Z still_waiting_on_test testcshared
  2021-01-25T14:21:03Z still_waiting_on_test testcshared
  2021-01-25T14:21:33Z still_waiting_on_test testcshared
  2021-01-25T14:22:03Z still_waiting_on_test testcshared
  2021-01-25T14:22:33Z still_waiting_on_test testcshared
  2021-01-25T14:23:03Z still_waiting_on_test testcshared
  2021-01-25T14:23:33Z still_waiting_on_test testcshared
  2021-01-25T14:24:03Z still_waiting_on_test testcshared
  2021-01-25T14:24:33Z still_waiting_on_test testcshared
  2021-01-25T14:25:03Z still_waiting_on_test testcshared
  2021-01-25T14:25:33Z still_waiting_on_test testcshared
  2021-01-25T14:26:03Z still_waiting_on_test testcshared
  2021-01-25T14:26:33Z still_waiting_on_test testcshared
  2021-01-25T14:27:03Z still_waiting_on_test testcshared
  2021-01-25T14:27:33Z still_waiting_on_test testcshared
  2021-01-25T14:28:03Z still_waiting_on_test testcshared
  2021-01-25T14:28:33Z still_waiting_on_test testcshared
  2021-01-25T14:29:03Z still_waiting_on_test testcshared
  2021-01-25T14:29:33Z still_waiting_on_test testcshared
  2021-01-25T14:30:03Z still_waiting_on_test testcshared
  2021-01-25T14:30:33Z still_waiting_on_test testcshared
  2021-01-25T14:31:03Z still_waiting_on_test testcshared
  2021-01-25T14:31:33Z still_waiting_on_test testcshared
  +12.0s (now)
```

**Comment by aclements** [comment] 2022-01-11 21:06
I have a theory about this. For most tests, the dist tool lets `go test` compile and run the test, but for testcshared, it separately compiles and runs the test binary. `go test` implements a backstop timeout in case the test binary wedges too hard to timeout itself, but dist does not implement this logic for test binaries it runs directly. Hence, if testcshared wedges, the builder itself will eventually timeout with no further output.

**Comment by bcmills** [comment] 2022-01-11 21:08
Still just `windows-amd64-2008`; curiously no new failures since October. 🤔

That suggests a possible connection to [CL 365994](https://go.dev/cl/365994) / #49457 (CC @ianlancetaylor, @bufflig, @cherrymui) — if `TestGo2C2Go` was the one timing out, then the timeouts would have stopped due to skipping that test.

`greplogs --dashboard -md -l -e '(?m)##### \.\./misc/cgo/testcshared.*\n\z' --since=2021-08-28`

[2021-10-26T14:24:17-283d8a3/windows-amd64-2008](https://build.golang.org/log/6954137baa9ee420482fd0617f7acd6d06a1c048)
[2021-10-14T07:18:59-1349c6e/windows-amd64-2008](https://build.golang.org/log/ae6a6ccc4345801dc4e067b7d476aa4475092601)
[2021-09-27T18:14:10-ecac351/windows-amd64-2008](https://build.golang.org/log/bbb9011114fc2a9d35b979797df5199706e8fb0e)
[2021-09-20T22:14:47-6e81f78/windows-amd64-2008](https://build.golang.org/log/591b6e34983df6230e6b8b6e00ff3125b9916fb3)
[2021-09-20T16:20:33-2d9b486/windows-amd64-2008](https://build.golang.org/log/50d7b3a6ed4f841d3701046effe762bc88e42859)
[2021-09-08T16:19:36-409434d/windows-amd64-2008](https://build.golang.org/log/0095a4f9cfb7d6e1d297f77c6dbbf8b1f284a638)
[2021-08-31T23:45:48-2d98a4b/windows-amd64-2008](https://build.golang.org/log/ac730c09fcc44f738373a3272d454e2bdac54862)
[2021-08-30T22:07:53-3342aa5/windows-amd64-2008](https://build.golang.org/log/5d6221c58294b438c360bfd94f6ccdcea405c7ce)

**Comment by cherrymui** [comment] 2022-01-11 23:41
It is possible that this is related to `TestGo2C2Go`. When I tried to reproduce #49457 I saw it sometimes hangs (https://github.com/golang/go/issues/49457#issuecomment-974520318). And the underlying issue of #49457 can definitely cause it to hang. As there is no new failures after that CL, I think the connection is very likely.

**Comment by bcmills** [comment] 2022-01-28 05:48
Still no more failures since Oct. 26. I'm calling this fixed by [CL 365994](https://go.dev/cl/365994).

`greplogs --dashboard -md -l -e '(?m)##### \.\./misc/cgo/testcshared.*\n\z' --since=2021-10-26`

[2021-10-26T14:24:17-283d8a3/windows-amd64-2008](https://build.golang.org/log/6954137baa9ee420482fd0617f7acd6d06a1c048)

**Closed** 2022-01-28 05:48 UTC
Labels: NeedsInvestigation
