### ISSUE TITLE
$ go run A.go  # command-line-arguments <autogenerated>:1:0: internal compiler error: exporter: unexpected type alias a in inlined function body

### ISSUE THREAD

**Issue by aqwsdfg** [golang/go#25145] opened 2018-04-28 07:21 UTC
A.go
```` golang
import "fmt"

type A struct {
        Str string
        i   int 
}
type a = A 
type B struct {
        a   
}

func NewB(str string, i int) *B {
        //var tmp = a{}
        //fmt.Println(tmp) // The two lines make it succ. why ?
        return &B{ 
                a: a{
                        Str: str,
                        i:   i,  
                },  
        }   
}

func main() {
        b := NewB("msg", 10) 
        fmt.Println(b)
}
`

> $ go run A.go 
> # command-line-arguments
> <autogenerated>:1:0: internal compiler error: exporter: unexpected type alias a in inlined function body
> Please file a bug report including a short program that triggers the error.

Add the twon lines, it run successly. why ?

``` golang
func NewB(str string, i int) *B {
        var tmp = a{}
        fmt.Println(tmp) // The two lines make it succ. why ?
        return &B{ 
                a: a{ // or a -> A, succ
                        Str: str,
                        i:   i,  
                },  
        }   
}
`
> $ go run A.go 
> { 0}
> &{{msg 10}}

**Comment by mvdan** [comment] 2018-04-28 07:26
Duplicate of #24857, already fixed in tip an the upcoming Go 1.11.

**Closed by mvdan** 2018-04-28 07:26 UTC
