### ISSUE TITLE
database/sql: func Open(driverName, dataSourceName string) doesn't return error.

### ISSUE THREAD

**Issue by hiromaily** [golang/go#15504] opened 2016-05-02 01:00 UTC
Why Open func doesn't return error?

```
func Open(driverName, dataSourceName string) (*DB, error) {
	driversMu.RLock()
	driveri, ok := drivers[driverName]
	driversMu.RUnlock()
	if !ok {
		return nil, fmt.Errorf("sql: unknown driver %q (forgotten import?)", driverName)
	}
	db := &DB{
		driver:   driveri,
		dsn:      dataSourceName,
		openerCh: make(chan struct{}, connectionRequestQueueSize),
		lastPut:  make(map[*driverConn]string),
	}
	go db.connectionOpener()
	return db, nil
}


```

Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.2

2. What operating system and processor architecture are you using (`go env`)?
amd64/darwin

3. What did you do?
Even though mysql server doesn't start, nothing error occur when I connect server using Open func of sql package.

```
func connection() (*sql.DB, error) {
	return sql.Open("mysql", getDsn())
}

db, err := connection()
if err != nil {
	panic(err.Error())
}
```
4. What did you expect to see?
I expected connection error.

5. What did you see instead?
I changed code to handle error as below.

```
func connection() (*sql.DB, error) {
	//return sql.Open("mysql", getDsn())
	db, _ := sql.Open("mysql", getDsn())
	return db, db.Ping()
}

```

**Comment by dominikh** [comment] 2016-05-02 01:01
Duplicate of #15502.

**Comment by hiromaily** [comment] 2016-05-02 01:05
I'm sorry. I didn't notice that issue.

**Closed** 2016-05-02 01:12 UTC

**Comment by hiromaily** [comment] 2016-05-02 01:14
I red previous issue #15502.
I understood why Open() func doesn't return error.
But I think Interface of Open() func don't have to have return of error.

If this func has interface of error, people would expect error. It makes people misleading.

**Comment by dominikh** [comment] 2016-05-02 01:19
1. The API cannot be changed. It needs to stay backwards compatible.
2. The function *can* return an error: when you provide an unknown driver name.

**Comment by hiromaily** [comment] 2016-05-02 01:22
I got it. Thanks.
