### ISSUE TITLE
context: BenchmarkWithTimeout/concurrency tests hang if -test.timeout=30m used on linux/{amd64,ppc64le,...}

### ISSUE THREAD

**Issue by laboger** [golang/go#42402] opened 2020-11-05 17:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +63fd764502 Wed Nov 4 23:24:22 2020 +0000 linux/ppc64le
go version devel +34c09695db Thu Nov 5 15:16:57 2020 +0000 linux/amd64
Hangs on both. Didn't try any others.
</pre>

### Does this issue reproduce with the latest release?
Does not hang in go 11.5.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
cd context
go test -test.bench=Timeout -test.timeout=30m -test.count=100

### What did you expect to see?
Benchmarks complete with benchmark timing output.

### What did you see instead?
One of the Timeout benchmarks hangs and the benchmarks do not finish.
go test -test.bench=Timeout -test.timeout=30m -test.count=100
goos: linux
goarch: ppc64le
pkg: context
BenchmarkWithTimeout/concurrency=40-16         	  317062	      3244 ns/op
BenchmarkWithTimeout/concurrency=40-16         	  318670	      3236 ns/op
BenchmarkWithTimeout/concurrency=40-16         	  383541	      3008 ns/op
BenchmarkWithTimeout/concurrency=40-16         	  372940	      3123 ns/op
BenchmarkWithTimeout/concurrency=40-16         	(stops here.... )
Same behavior on amd64.

Trying some earlier commits, I found one from early September that does not hang but more experiments needed.

**Comment by laboger** [comment] 2020-11-05 22:46
I got this test to hang on one system without setting the timeout option.

**Comment by erifan** [comment] 2020-11-06 01:00
This is just the same issue with https://github.com/golang/go/issues/42237

**Comment by dmitshur** [comment] 2020-11-11 16:11
Issue #42237 is about OpenBSD specifically, and it will be resolved with #42426.

Reopening this since this is about ppc64le, so it should be investigated separately, although it may be related in some way.

**Comment by bcmills** [comment] 2020-11-13 16:35
This probably has the same root cause as #42424.

**Comment by laboger** [comment] 2020-11-13 22:19
This is not happening for me with the latest master on ppc64le. 
My testing shows that it was fixed by CL 267257 and as you suspected that means it was probably introduced by CL 232298.

**Comment by bcmills** [comment] 2020-11-16 17:05
@laboger, thanks for verifying!

**Closed by bcmills** 2020-11-16 17:05 UTC
Labels: NeedsInvestigation
