### ISSUE TITLE
Compile fails when CC's path contains a space

### ISSUE THREAD

**Issue by jake-scott** [golang/go#44387] opened 2021-02-18 18:01 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version devel +609d82b289 Thu Feb 18 15:00:59 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jacob/.cache/go-build"
GOENV="/home/jacob/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jacob/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jacob/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,https://gocenter.io"
GOROOT="/home/jacob/src/github.com/golang/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/jacob/src/github.com/golang/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel +609d82b289 Thu Feb 18 15:00:59 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="/tmp/test bin/gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jacob/scratch/cgo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="bin/gcc -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2893382910=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
go build -buildmode=c-shared -o test.so

# runtime/cgo
cgo: exec /tmp/test: fork/exec /tmp/test: no such file or directory

### What did you expect to see?
The program should compile

### What did you see instead?
Go was unable to run the C compiler due to not handling the space in the directory name.

Of course this isn't usually an issue in Linux but on Windows, CC is very likely to be set to something starting with "C:\Program Files", and that blows up.

I see that the code uses Fields:

```
	if env := strings.Fields(cfg.Getenv("CC")); len(env) > 0 {
		cc = env[0]
	}
```

I think changing this to :
```
	if env := strings.TrimSpace(cfg.Getenv("CC")); len(env) > 0 {
		cc = env
	}
```

.. might work, but I'm not 100% certain what the goal of this was in the first place.  If it was just to remove leading and trailing space then TrimSpace might be better.

**Comment by seankhliao** [comment] 2021-02-18 18:10
Duplicate of #41400

**Closed by seankhliao** 2021-02-18 18:10 UTC
