### ISSUE TITLE
reflect: MapKeys on map returns the slice of all values from map, not keys

### ISSUE THREAD

**Issue by workanator** [golang/go#31617] opened 2019-04-22 19:53 UTC
Hello, when I do `reflect.ValueOf(m).MapKeys()` where `m` is a map I get the slice of values from the map, not keys. The same issue with `MapRange()`, returned iterator returns values disregarding what do you call, `Key()` or `Value()`. Is that the correct behaviour or is that a bug?

You can try that behaviour [here](https://play.golang.org/p/BL6zc7fFmUR). I suppose the output should contain `key1, two, sdkjf`.

I'm using the latest version of Go **1.12.3, linux/amd64**

My ENV is
```shell
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ME/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/devel/projects/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build558732631=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by seebs** [comment] 2019-04-22 20:56
try `for idx, value := range slice` instead of `for value := range slice`.

**Comment by dominikh** [comment] 2019-04-22 20:56
Closing, not a bug, just iterating over the slice incorrectly.

**Closed by dominikh** 2019-04-22 20:56 UTC

**Comment by workanator** [comment] 2019-04-23 08:18
Oh! So stupid mistake. They say do not work late at night. I do not listen...
Thank you guys for the help. And sorry for wasting your time.
