### ISSUE TITLE
text/template: missingkey=zero behaves different from html/template

### ISSUE THREAD

**Issue by lirtistan** [golang/go#70681] opened 2024-12-04 15:37 UTC
### Go version

go version go1.23.4 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/enrico/.cache/go-build'
GOENV='/home/enrico/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE='ebony.local'
GOMODCACHE='/home/enrico/.asdf/installs/golang/1.23.4/packages/pkg/mod'
GONOPROXY='ebony.local'
GONOSUMDB='ebony.local'
GOOS='linux'
GOPATH='/home/enrico/.asdf/installs/golang/1.23.4/packages'
GOPRIVATE='ebony.local'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/enrico/.asdf/installs/golang/1.23.4/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/enrico/.asdf/installs/golang/1.23.4/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.4'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/enrico/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/enrico/Projects/golang/active/web/chi-client/go.mod'
GOWORK='/home/enrico/Projects/golang/active/web/go.work'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1859946843=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

Parsing a template with help of `text/template`, but the `missingkey=zero` option behaves different from `html/template`.

A missing key in map[string]any is printed as `<no value>` which is different from what i expect if i render the template with `.Option("missingkey=zero")`.

`html/template` behaves correct.

See https://github.com/lirtistan/template_bug for a working example.

### What did you see happen?

With `text/template` i get the following result...

```
<div class="vstack">
    <p>Foo</p>
    <no value>
</div>
```

with `html/template` i get the correct result...

```
<div class="vstack">
    <p>Foo</p>

</div>
```

also see attached screenshots...

here with `text/template`...
![image](https://github.com/user-attachments/assets/3a1a89b4-bd58-4809-b033-5f93a6867a2e)

here with `html/template`...
![image](https://github.com/user-attachments/assets/bb402575-41c6-4b50-88a6-18544f925459)

### What did you expect to see?

An output without <no value>, like that html example below

```
<div class="hstack">
    <p>Foo</p>

</div>
```

**Comment by ldemailly** [comment] 2024-12-04 15:51
your playground link works fine, are you saying if you run that same code in your local machine the tt output is suddenly different? it seems your screenshot is a browser “view source” so you have more code involved? maybe a typo?

side note: you shouldn’t use text for html anyway?

**Comment by lirtistan** [comment] 2024-12-04 15:59
Hi,

here is thge code that is delivering the template result to my http handler...

```golang
//go:embed *.html js/* css/* views/* models/*
var assets embed.FS

func Deliver(w http.ResponseWriter, path string, data ...any) {
	content, err := assets.ReadFile(path)
	if err != nil {
		log.Error(err)
	} else {
		tpl, err2 := template.New(path).Option("missingkey=zero").Parse(string(content))
		if err2 != nil {
			log.Error(err2)
		}
		var arg any
		if len(data) > 0 {
			arg = data[0]
		}
		if ok := tpl.Execute(w, arg); ok != nil {
			log.Error(ok)
		}
	}
}
```

here is how i use it inside my handler...
```golang
func (route Route) Root(w http.ResponseWriter, r *http.Request) {
	assets.Deliver(w, "index.html", Map{})
}
```

**Comment by lirtistan** [comment] 2024-12-04 16:31
here is a example of what iam doin..

https://github.com/lirtistan/template_bug

**Comment by lirtistan** [comment] 2024-12-04 16:37
Spoiler it works as expected, so seems its my program which does wrong things, i don't understand right now. Sorry i close this issue for now and go for bug hunt.

**Comment by lirtistan** [comment] 2024-12-04 19:36
I found the issue. See my repo for a working example (i updated the code which reflects the current state, it shows the bug)...

https://github.com/lirtistan/template_bug

**Comment by seankhliao** [comment] 2024-12-04 19:42
Duplicate of #24963

**Closed by seankhliao** 2024-12-04 19:42 UTC
Labels: FrozenDueToAge
