### ISSUE TITLE
affected/package: html/template

### ISSUE THREAD

**Issue by mikeyoung3k** [golang/go#58031] opened 2023-01-26 16:48 UTC
### What version of Go are you using (`go version`)?

<pre>
1.19

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
Playground
</pre></details>

### What did you do?

Using template with Option `"missingkey=invalid"` and a map that is missing the required key.

```go
package main

import (
	"fmt"
	"html/template"
	"os"
)

func main() {
	tString := "Hi there {{.Name}}, you are {{.Age}} years old"
	v := make(map[string]any)
	v["Name"] = "Bob"
	//v["Age"] = 18


	tmpl, err := template.New("Test").Option("missingkey=invalid").Parse(tString)

	if err != nil {
		fmt.Println("Can't create template", err)
	}

	err = tmpl.Execute(os.Stdout, v)
	if err != nil {
		fmt.Println("Can't execute template", err)
	}
}
```

https://go.dev/play/p/r1qU5t-H-LM

### What did you expect to see?
`Hi there Bob, you are <no value> years old`
[As per docs](https://pkg.go.dev/text/template#Template.Option)

### What did you see instead?
`Hi there Bob, you are  years old`

**Comment by seankhliao** [comment] 2023-01-26 17:25
Duplicate of #54053

**Closed** 2023-01-26 17:25 UTC
