### ISSUE TITLE
x/mod/zip: TestVCS is failing on linux-amd64-longtest and linux-386-longtest sometimes

### ISSUE THREAD

**Issue by dmitshur** [golang/go#37182] opened 2020-02-12 03:18 UTC
Spotted at https://build.golang.org/?repo=golang.org%2fx%2fmod on the longtest builders.

```
--- FAIL: TestVCS (0.00s)
    --- FAIL: TestVCS/rsc.io_quote@v1.5.1 (31.75s)
        zip_test.go:944: fetch -f --depth=1 origin refs/tags/v1.5.1:refs/tags/v1.5.1: exit status 128
    --- FAIL: TestVCS/rsc.io_quote_v3@v3.0.0 (31.75s)
        zip_test.go:944: fetch -f --depth=1 origin refs/tags/v3.0.0:refs/tags/v3.0.0: exit status 128
    --- FAIL: TestVCS/rsc.io_quote@v1.1.0 (31.79s)
        zip_test.go:944: fetch -f --depth=1 origin refs/tags/v1.1.0:refs/tags/v1.1.0: exit status 128
FAIL
FAIL	golang.org/x/mod/zip	37.982s
```

I can't reproduce locally on macOS right now. Unsure if it was a temporary problem, Linux-specific, or if something about the builders is different. Needs investigation.

/cc @matloob @jayconrod @bcmills

**Comment by jayconrod** [comment] 2020-02-12 15:02
Thanks for reporting. I'll take a look.

This looks like a failure running `git fetch`, so it's likely a network or upstream issue. If that's the case, there may not be anything to do. It's important that the test covers fetching from real repositories, but unfortunately that implies a bit of flakiness.

**Comment by bcmills** [comment] 2020-02-12 15:25
#35515 might make it easier to spot a pattern and figure out whether the issue is upstream or in the test. (At the moment, `fetchlogs` is not very useful for the `x/` repos.)

**Comment by jayconrod** [comment] 2020-02-12 20:23
Can't reproduce. Pretty sure it's a network or upstream flake though.

The answer here is probably to pack up the repo in testdata, then do some git config magic so a fetch in another repository goes there. Only on the builders.

**Comment by jayconrod** [comment] 2020-05-01 15:25
This should have been fixed by [CL 228397](https://go-review.googlesource.com/c/mod/+/228397). Not seeing any failures since then.

**Closed by jayconrod** 2020-05-01 15:25 UTC
Labels: NeedsInvestigation, help wanted
