### ISSUE TITLE
x/tools/gopls/test, x/tools/internal/lsp: inscrutable test output on failure

### ISSUE THREAD

**Issue by bcmills** [golang/go#41717] opened 2020-09-30 20:48 UTC
### What version of Go are you using (`go version`)?

https://golang.org/cl/258298

### What did you do?

Run TryBots for `x/tools`.

### What did you expect to see?

All tests passing, or a test log with a clear indication of what actually went wrong (per http://golang.org/wiki/CodeReviewComments#useful-test-failures).

### What did you see instead?

https://storage.googleapis.com/go-build-log/624a58dc/linux-amd64_445ec507.log

which contains what appears to me as a wall of text followed by an otherwise-disconnected diff in an expected output count:

```
--- FAIL: TestCommandLine (31.97s)
    --- FAIL: TestCommandLine/Modules (16.61s)
        tests.go:884: test summary does not match:
            --- want
            +++ got
            @@ -7,7 +7,7 @@
             FuzzyCompletionsCount = 8
             RankedCompletionsCount = 157
             CaseSensitiveCompletionsCount = 4
            -DiagnosticsCount = 44
            +DiagnosticsCount = 43
             FoldingRangesCount = 2
             FormatCount = 6
             ImportCount = 8
FAIL
FAIL	golang.org/x/tools/gopls/test	32.066s
```

From that output, I have no idea which of the 44(!) expected diagnostics from the test was missing, or which line or source file was intended to produce that missing diagnostic.

**Comment by bcmills** [comment] 2020-09-30 20:50
CC @stamblerre @heschik @ianthehat

**Comment by findleyr** [comment] 2023-09-07 21:41
Closing as dupe of https://go.dev/issue/54845.

**Closed by findleyr** 2023-09-07 21:41 UTC
Labels: Testing, NeedsInvestigation, gopls, Tools
