### ISSUE TITLE
cmd/go: ldflags parameters not working when compiling from makefile on FreeBSD 11

### ISSUE THREAD

**Issue by libra9z** [golang/go#24310] opened 2018-03-08 09:01 UTC
When I use go version 1.9.4 ，Everything looks ok，but，when I upgrade to go 1.10，build Makefile，the ldflags did not take effect，My Makefile like：

####
```
BINARY= `basename \`pwd\``

VERSION=`git describe --tags|sed -e "s/\-/\./g"`
BUILD=`date +%FT%T%z`
COMMIT=`git rev-parse HEAD`
TARGETDIR=/home/health/bin
TAGS=-tags "reuseport quic kcp zookeeper etcd consul ping"

LDFLAGS_DEB=-ldflags "-X main.Version=${VERSION} -X main.Date=${BUILD} -X main.Commit=${COMMIT}"
LDFLAGS_REL=-ldflags "-s -w -X main.Version=${VERSION} -X main.Date=${BUILD} -X main.Commit=${COMMIT}"

deps:
	godep save


lrelease:
	env GOOS=linux GOARCH=amd64 godep go build ${TAGS} ${LDFLAGS_REL} -o ${BINARY}_linux_release
release:
	godep go build ${TAGS} ${LDFLAGS_REL} -o ${BINARY}
	env GOOS=linux GOARCH=amd64 godep go build ${TAGS} ${LDFLAGS_REL} -o ${BINARY}_linux_release

ldebug:
	env GOOS=linux GOARCH=amd64 godep go build ${TAGS} ${LDFLAGS_DEB} -o ${BINARY}_linux_debug

debug:
	godep go build ${TAGS} ${LDFLAGS_DEB} -o ${BINARY}
	env GOOS=linux GOARCH=amd64 godep go build ${TAGS} ${LDFLAGS_DEB} -o ${BINARY}_linux_debug

install:
	godep go install ${TAGS} ${LDFLAGS_REL}

fb:
	godep go build ${TAGS} ${LDFLAGS_DEB} -o ${BINARY}
	mv -f ${BINARY} ${TARGETDIR}

clean:
	if [ -f ${BINARY} ] ; then rm ${BINARY} ; fi
	if [ -f ${BINARY}_linux_* ] ; then rm ${BINARY}_linux_*; fi

.PHONY: clean install
```
The Makefile  result:
![image](https://user-images.githubusercontent.com/7529048/37141908-83c1f9cc-22f1-11e8-91cc-6a3b858398c4.png)

 but when I use command line ,the result is different
command line is：
```
godep go build -tags "reuseport quic kcp zookeeper etcd consul ping" -ldflags "-s -w -X main.Version=`git describe --tags|sed -e "s/\-/\./g"` -X main.Date=`date +%FT%T%z` -X main.Commit=`git rev-parse HEAD`" -o caresvc
```
the result is：
![image](https://user-images.githubusercontent.com/7529048/37142101-09602e5a-22f2-11e8-81c5-ada4ff56f4c8.png)

what is going wrong！！

```
### What operating system and processor architecture are you using (`go env`)?
FreeBSD 11.0
```

**Comment by davecheney** [comment] 2018-03-08 09:09
What is the problem you are reporting? In one sentence, what did you expect
to see with go 1.9.4, and what did you see with Go 1.10? What did you see
instead.

**Comment by libra9z** [comment] 2018-03-08 09:19
the problem is :  
in go1.10,  the "ldflag -s -w” is not take effect, target size is same with no “ldflags -s -w”

**Comment by davecheney** [comment] 2018-03-08 09:25
But you've also changed versions of the compiler, that will have an impact
on binary size.

**Comment by libra9z** [comment] 2018-03-08 09:41
when I use go1.10 build Makefile ,the DEBUG and RELEASE version
```
ldflags DEBUG version is 
-ldflags "-X main.Version=${VERSION} -X main.Date=${BUILD} -X main.Commit=${COMMIT}"
ldflags RELEASE version is 
-ldflags "-s -w -X main.Version=${VERSION} -X main.Date=${BUILD} -X main.Commit=${COMMIT}"
```
then DEBUG and RELEASE version of  target size is same
-rwxr-xr-x  1 eric  wheel  33991113  3  8 17:32 caresvc_linux_debug
-rwxr-xr-x  1 eric  wheel  33991113  3  8 17:32 caresvc_linux_release

when I use go1.9.4,  then same Makefile and DEBUG /RELEASE  

the Target size is different:
-rwxr-xr-x  1 eric  wheel  33023750  3  8 17:41 caresvc_linux_debug
-rwxr-xr-x  1 eric  wheel  21306240  3  8 17:39 caresvc_linux_release

**Comment by mvdan** [comment] 2018-03-08 10:24
This bug report is overly complex, and hard to reproduce. Please provide two simple commands that others can run to reproduce the problem - which I understand to be that `-ldflags "-w -s"` does not take effect.

**Comment by libra9z** [comment] 2018-03-08 10:49
the simple example for reproduce:
go file  hello.go
```
 package main
 import "fmt"

 func main(){
         fmt.Println("hello world")
 }
```
the Makefile is:
```
BINARY=`basename \`pwd\``

LDFLAGS_REL=-ldflags "-s -w" 

release:
        go build ${LDFLAGS_REL} -o ${BINARY}_release

debug:
        go build -o ${BINARY}_debug
install:
        go install ${LDFLAGS_REL}

clean:
        if [ -f ${BINARY} ] ; then rm ${BINARY} ; fi

.PHONY: clean install
```
build with go1.9.4,the target size is:
-rwxr-xr-x  1 eric  wheel  1829701  3  8 18:44 hello_debug
-rwxr-xr-x  1 eric  wheel  1207360  3  8 18:44 hello_release

build with go1.10 ,the target size is
-rwxr-xr-x  1 eric  wheel  1994552  3  8 18:45 hello_debug
-rwxr-xr-x  1 eric  wheel  1994552  3  8 18:45 hello_release

**Comment by ALTree** [comment] 2018-03-08 11:27
I cannot reproduce the issue with the makefile you provided on linux with go1.10:

```
$ go version
go version go1.10 linux/amd64

$ ls
hello.go  Makefile

$ make debug release
go build -o `basename \`pwd\``_debug
go build -ldflags "-s -w"  -o `basename \`pwd\``_release

$ ls -l
total 3180
-rw-r--r-- 1 alberto alberto      72 Mar  8 12:08 hello.go
-rw-r--r-- 1 alberto alberto     264 Mar  8 12:08 Makefile
-rwxr-xr-x 1 alberto alberto 2025142 Mar  8 12:09 temp_debug
-rwxr-xr-x 1 alberto alberto 1218304 Mar  8 12:09 temp_release
```

Considering you said that if you run `go build` from the terminal the issue disappears, I wonder if this is actually a bug in your system.

**Comment by libra9z** [comment] 2018-03-08 11:28
My system is FreeBSD 11.0,go version 
go version go1.10 freebsd/amd64

**Comment by ianlancetaylor** [comment] 2018-03-28 14:34
Note that in Go 1.10 `-ldflags` now takes a pattern argument, as documented at https://golang.org/doc/go1.10#build .  Perhaps that is the core of the problem here.  Perhaps you need to add `all=` to your `-ldflags` argument.

That said, I am also unable to reproduce this.

```
> cat Makefile
BINARY=`basename \`pwd\``

LDFLAGS_REL=-ldflags "-s -w" 

release:
	$(GO) build ${LDFLAGS_REL} -o ${BINARY}_release

debug:
	$(GO) build -o ${BINARY}_debug
install:
	$(GO) install ${LDFLAGS_REL}

clean:
	if [ -f ${BINARY} ] ; then rm ${BINARY} ; fi

.PHONY: clean install
> cat hello.go
package main

import "fmt"

func main() {
	fmt.Println("Hello, world")
}
> ~/go1.10/bin/go version
go version go1.10 linux/amd64
> ~/go1.9/bin/go version
go version go1.9.2 linux/amd64
> make GO=~/go1.10/bin/go release debug
/home/iant/go1.10/bin/go build -ldflags "-s -w"  -o `basename \`pwd\``_release
/home/iant/go1.10/bin/go build -o `basename \`pwd\``_debug
> ls -l
total 3180
-rwxr-x--- 1 iant primarygroup 2025142 Mar 28 07:31 hello_debug*
-rw-r----- 1 iant primarygroup      73 Mar 28 07:28 hello.go
-rwxr-x--- 1 iant primarygroup 1218304 Mar 28 07:31 hello_release*
-rw-r--r-- 1 iant primarygroup     272 Mar 28 07:31 Makefile
> rm hello_debug hello_release
> make GO=~/go1.9/bin/go release debug
/home/iant/go1.9/bin/go build -ldflags "-s -w"  -o `basename \`pwd\``_release
/home/iant/go1.9/bin/go build -o `basename \`pwd\``_debug
iant-glaptop5> ls -l
total 3028
-rwxr-x--- 1 iant primarygroup 1859967 Mar 28 07:32 hello_debug*
-rw-r----- 1 iant primarygroup      73 Mar 28 07:28 hello.go
-rwxr-x--- 1 iant primarygroup 1225312 Mar 28 07:32 hello_release*
-rw-r--r-- 1 iant primarygroup     272 Mar 28 07:31 Makefile
```

I'm going to close this.  Please comment if this is still a problem for you, and show a session like the above that demonstrates the problem.

**Closed by ianlancetaylor** 2018-03-28 14:34 UTC
Labels: NeedsInvestigation
