### ISSUE TITLE
x/pkgsite: https://pkg.go.dev/s/pkgsite-package-removal 404

### ISSUE THREAD

**Issue by jamesliu96** [golang/go#50289] opened 2021-12-21 08:48 UTC
### What is the URL of the page with the issue?
https://pkg.go.dev/s/pkgsite-package-removal

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Screenshot

![image](https://user-images.githubusercontent.com/2211002/146899641-929bc178-2c53-40f8-a18e-10e507f6246a.png)

### What did you do?

saw this link here (https://pkg.go.dev/about#removing-a-package) and clicked it

### What did you expect to see?
a valid page

### What did you see instead?
404 ![image](https://user-images.githubusercontent.com/2211002/146899641-929bc178-2c53-40f8-a18e-10e507f6246a.png)

**Comment by seankhliao** [comment] 2021-12-21 12:25
Duplicate of #50221

**Closed by seankhliao** 2021-12-21 12:25 UTC
Labels: pkgsite
