### ISSUE TITLE
cmd/get: falls back to HTTP

### ISSUE THREAD

**Issue by leif** [golang/go#10080] opened 2015-03-04 19:01 UTC
``go get`` is frequently used by users and developers on hostile networks (eg, the internet) to fetch and run code. Incredibly, when HTTPS connections fail (for instance because an attacker is denying access to HTTPS), ``go get`` falls back to HTTP.

Please remove support for plain HTTP, or refuse to use it without the user specifying explicitly that they want to make HTTP connections!

**Comment by cespare** [comment] 2015-03-04 19:06
Duplicate of #9637.

**Closed** 2015-03-04 19:10 UTC
