### ISSUE TITLE
strings.TrimRight unexpected output

### ISSUE THREAD

**Issue by lafh** [golang/go#41557] opened 2020-09-22 14:28 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

https://play.golang.org/p/N87az0K_2by

```
package main

import (
	"fmt"
	"strings"
)

func main() {
	fmt.Println(strings.TrimRight("abc@xx.com", "@xx.com"))

}

```

### What did you expect to see?

`abc`

### What did you see instead?

`ab`

**Comment by ALTree** [comment] 2020-09-22 14:39
In TrimRight, the second parameter is a cutset: `TrimRight(s string, cutset string)`, i.e. a set of individual characters to be trimmed.

Passing "@xx.com" doesn't mean "trim right at @xx.com", it means "trim all @ x, c, o, and m characters from the right". That's why your c gets trimmed, too.

Working as intended, closing this.

**Closed by ALTree** 2020-09-22 14:39 UTC

**Comment by ianlancetaylor** [comment] 2020-09-22 20:09
By the way, you might be looking for `strings.TrimSuffix`.
