### ISSUE TITLE
x/website: https://golang.org/doc/tutorial/greetings-multiple-people should highlight added code 

### ISSUE THREAD

**Issue by apuchitnis** [golang/go#49708] opened 2021-11-21 16:40 UTC
Specifically the following code under step 2 should be highlighted in blue: 
```
    // Request greeting messages for the names.
    messages, err := greetings.Hellos(names)
    if err != nil {
        log.Fatal(err)
    }
```

### Does this issue reproduce with the latest release?
Yes, https://golang.org/doc/tutorial/greetings-multiple-people as of today.

### What did you expect to see?
New code is highlighted.

### What did you see instead?
New code that isn't highlighted.

**Comment by seankhliao** [comment] 2021-11-21 16:45
Duplicate of #46416

**Closed by seankhliao** 2021-11-21 16:45 UTC
