### ISSUE TITLE
"go vet" needs a 'ignore this' mechanism

### ISSUE THREAD

**Issue by brianolson** [golang/go#18432] opened 2016-12-26 19:01 UTC
### What version of Go are you using (`go version`)?

go version go1.7.4 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bolson/psrc/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rh/3lrlb3dx2gj8s_5yyxb2vsyc0000gn/T/go-build257955075=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

### What did you do?

a.go:
`
package main

import "fmt"
import "os"

func main() {
	out := os.Stdout
	i := 1
	fmt.Fprint(out, "I am 100% sure what I'm doing here\n") // go vet ignore -- wouldn't it be nice if there were a directive to silence the `go vet` warning here?
}
`

### What did you expect to see?

`go vet` should be able to have no complaint about this file

### What did you see instead?

$ go vet
a.go:9: possible formatting directive in Fprint call
exit status 1

If this feature exists and is undocumented, it needs to be documented
https://golang.org/cmd/vet/
See also prior issue of excessive warnings like this
https://github.com/golang/go/issues/6407

**Comment by ALTree** [comment] 2016-12-26 19:08
This was discussed in #17058. Note that the introduction of a new directive/magic comment to be used to silence vet warnings was and unanimously rejected.

**Comment by robpike** [comment] 2016-12-26 20:24
Duplicate of #17058

**Closed by robpike** 2016-12-26 20:24 UTC
