### ISSUE TITLE
cmd/go: go mod tidy in workspace will err like: a.b.c/a: cannot find module providing package 

### ISSUE THREAD

**Issue by kirito41dd** [golang/go#55139] opened 2022-09-19 08:45 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOMOD="/Users/xxx/work/testwk/b/go.mod"
GOWORK="/Users/xxx/work/testwk/go.work"
</pre></details>

### What did you do?

i'm trying to use workspace, my work dir:
```
testwk/
    a/
        go.mod a.go
    b/
        go.mod main.go
    go.work
```
go.work:
```
go 1.18

use (
	./a
	./b
)
```

a/go.mod:
```
module a.b.c/a

go 1.18
```
a/a.go:
```
package a

var Version = "a"
```
b/go.mod:
```
module a.b.c/b

go 1.18
```
b/main.go:
```
package main

import (
	"a.b.c/a"
	"fmt"
)

func main() {
	fmt.Println(a.Version)
}
```
when i use go mod tidy in b/:
```
➜  b go mod tidy
go: finding module for package a.b.c/a
a.b.c/b imports
        a.b.c/a: cannot find module providing package a.b.c/a: unrecognized import path "a.b.c/a": https fetch: Get "https://a.b.c/a?go-get=1": dial tcp: lookup a.b.c: no such host
```
This seems to be a bug and should skip the `a.b.c/a` which in go.work.

**Comment by seankhliao** [comment] 2022-09-19 09:35
Duplicate of #50750

**Closed by seankhliao** 2022-09-19 09:35 UTC
