### ISSUE TITLE
cmd/go: run gives conflicting advice when using path@version syntax

### ISSUE THREAD

**Issue by davecheney** [golang/go#29415] opened 2018-12-25 22:04 UTC
### What version of Go are you using (`go version`)?

% go version
go version devel +97d5cb24b1 Sat Dec 22 09:37:04 2018 +0000 linux/amd64

### Does this issue reproduce with the latest release?

unknown

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
% go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dfc/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GOPROXY=""
GORACE=""
GOROOT="/home/dfc/go"
GOTMPDIR=""
GOTOOLDIR="/home/dfc/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build125128327=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Go 1.12beta1 (tip) does not permit @version syntax unless modules explicitly enabled, even if GOPATH is unset
```
% unset GOPATH && go run -v github.com/davecheney/httpstat@1.0.0
package github.com/davecheney/httpstat@1.1.0: cannot use path@version syntax in GOPATH mode
```

### What did you expect to see?

env GO111MODULE=on go run -v github.com/davecheney/httpstat@1.0.0

would download and build httpstat v1.0.0

### What did you see instead?

```
% unset GOPATH && env GO111MODULE=on go run -v github.com/davecheney/httpstat@1.0.0
missing $GOPATH
```

Running without modules enabled tells me I must enable modules even thought I don't have GOPATH set. Running _with_ modules enable tells me I must set GOPATH.

```
lucky(/tmp) % env GO111MODULE=on GOPATH=/tmp/ go run -v github.com/davecheney/httpstat@1.0.0
package github.com/davecheney/httpstat@1.0.0: can only use path@version syntax with 'go get'
```
Setting both tells me that this isn't supported.

a. Can `go run path@version` be supported? If not, why not?
b. Can the error messages be improved make it clearer sooner that the operation will not succeed once the correct permutation of environment variables is discovered.

**Comment by odeke-em** [comment] 2018-12-27 08:00
Thank you for this report @davecheney!

Kindly paging @bcmills @rsc.

**Comment by jadekler** [comment] 2019-01-04 23:08
Seems to not be working for me, either:

```
$ cd /tmp/whatever && unset GOPAHT && go get cloud.google.com/go@v0.30.0
go: cannot use path@version syntax in GOPATH mode
```

**Comment by ahmetb** [comment] 2019-01-04 23:14
Hit this as well in #29575. Closing that as duplicate.

**Comment by rsc** [comment] 2019-01-10 16:02
Only go get and module-manipulation commands take path@version.
go build, go run, etc do not.

**Comment by bcmills** [comment] 2019-01-30 18:48
@ahmetb, this issue is about the diagnostic messages. If `go get` is not actually behaving as documented, please file that as a separate issue.

That said, from the detail in #29575 it appears that you are, in fact, running in `GOPATH` mode.
Per https://golang.org/cmd/go/#hdr-Preliminary_module_support:
> If `GO111MODULE`=`auto` or is unset, then the `go` command enables or disables module support based on the current directory. Module support is enabled only when the current directory is outside `GOPATH/src` and itself contains a `go.mod` file or is below a directory containing a `go.mod` file.

**Comment by ahmetb** [comment] 2019-04-12 20:10
@bcmills I'm still seeing this despite I'm not running in GOPATH mode. `go get` or `go build` uses modules just fine when I don't specify a @version syntax.

Here's a minimal repro with go1.12

```
dir=$(mktemp -d)

cd $dir

# write a go.mod to indicate go111module=on
echo 'module foo' > go.mod
```

`go get module` syntax uses go.mod file:

```sh
# unset all env vars, with the exception of $HOME (mock it) and $PATH (inherit it)

env -i HOME="$PWD/mock-home" PATH="$PATH" go build -o ./httpstat github.com/davecheney/httpstat

    go: finding github.com/davecheney/httpstat v1.0.0
    go: downloading github.com/davecheney/httpstat v1.0.0
    go: extracting github.com/davecheney/httpstat v1.0.0
    ...
    (works)
```

`go get module@1.0.0` syntax is not working in the same setup:

```
env -i HOME="$PWD/mock-home" PATH="$PATH" go build -o ./httpstat github.com/davecheney/httpstat@1.0.0

can't load package: package github.com/davecheney/httpstat@1.0.0: can only use path@version syntax with 'go get'
```

Would you still suggest I'm in "`GOPATH` mode"?

**Comment by bcmills** [comment] 2019-04-12 20:15
@ahmetb, this issue is about the `go` command giving conflicting advice.

The advice from the commands you posted above does not conflict: it correctly indicates that, in module mode (which you are clearly in), you “can only use path@version syntax with 'go get'”.

**Comment by probonopd** [comment] 2019-11-02 07:38
Also running into

	imports github.com/diskfs/go-diskfs/filesystem@squashfs: cannot use path@version syntax in GOPATH mode

This is so annoying.

**Comment by smikulcik** [comment] 2019-11-25 18:15
From what I can tell, you just have to be in a package that has a go.mod file.  Then you can get a particular version.

**Comment by nivekastoreth** [comment] 2020-02-04 14:47
Thanks to @smikulcik's comment `go get` is at least minimally functional.

As someone who doesn't program in `go` and only uses it to install utilities written in go, it's extremely frustrating spending an hour trying to figure out how to install a simple application only to find out I have to pretend to be working on a project in order to install a version of a utility that's needed.

**Comment by AgrPriyank** [comment] 2020-02-14 10:26
> From what I can tell, you just have to be in a package that has a go.mod file. Then you can get a particular version.

As I understand it, path@version should be used in Golang specifically for version maintenance. Hence @smikulcik comment to run the command in directory with go.mod file makes sense. Go will try to download the repository to your src folder from Github and will try to maintain the version in the mod file.

**Comment by 13rac1** [comment] 2020-12-18 05:33
```
$ docker run -it golang:1.15-alpine
/go # echo $GOPATH
/go
/go # go run -v github.com/user/project@test
package github.com/user/project@test: can only use path@version syntax with 'go get'
/go # go install github.com/user/project@test
package github.com/user/project@test: can only use path@version syntax with 'go get'
/go # go get -u github.com/user/project@test
go: cannot use path@version syntax in GOPATH mode
/go # unset GOPATH
/go # echo $GOPATH

/go # go get -u github.com/user/project@test
go: cannot use path@version syntax in GOPATH mode <- I unset it! Yes, I know what the docs say, but still.
/go # export GO111MODULE=on
/ # go get -u github.com/user/project@test
go: downloading github.com/user/project v1.0.0-date-sha <- Should be test branch @latest, but that's separate.
```

@nivekastoreth FWIW I've written Go for the last five years and this is frustrating for me too.

These error messages are not helpful. Users should not need search the Internet for this error message to install an app from a git repository in an expected way. What steps can we take to make this _just_ work and fix this user/developer experience? The answer is not "RTFM" [Essays about Go mod version-specific pitfalls and workarounds shouldn't need exist](https://dev.to/maelvls/why-is-go111module-everywhere-and-everything-about-go-modules-24k#-raw-go111module-endraw-with-go-114). What can we do?

**Comment by lorenzogatti** [comment] 2020-12-26 16:12
Practical example: I want to use Go-jsonnet (https://github.com/google/go-jsonnet), and I need a feature (TOML output) that has been added later than the most recent label in the git repository. The official installation instructions are

go get github.com/google/go-jsonnet/cmd/jsonnet

which installs the last label. Game over for my TOML files.

Plausible workarounds are all ridiculous:

- I can wait and maybe, sooner or later, possibly even this winter, a new label will be made and afterwards 'go get -u github.com/google/go-jsonnet/cmd/jsonnet' will install a suitable version.
- I can figure out how to replace the globally installed jsonnet with a the result of compiling a current checkout of the go-jsonnet repository, as if I were actually developing go-jsonnet.
- I can attempt to find a silly incantation to convince 'go get' to do what I want. Probably impossible by design.

**Closed** 2021-01-08 20:22 UTC
Labels: GoCommand, NeedsInvestigation, modules
