### ISSUE TITLE
x/net: MacOS lookupIP resolves domains different if CGO_ENABLED flag used.

### ISSUE THREAD

**Issue by mhaley-tignis** [golang/go#51753] opened 2022-03-17 12:53 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mhaley/Library/Caches/go-build"
GOENV="/Users/mhaley/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mhaley/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mhaley/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mhaley/src/testArea/go-dns-resolution/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0m/1mkvkqj94hs89nrkz765217c0000gn/T/go-build3158196937=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

I ran a simple program building it with `CGO_ENABLED=1` and `CGO_ENABLED=0`

```
$ CGO_ENABLED=1 go build -o dns-testing
$ ./dns-testing
Could not get IPs: lookup does-not-exist: no such host
```

```
$ CGO_ENABLED=0 go build -o dns-testing
$ ./dns-testing                        
Could not get IPs: lookup does-not-exist on 192.168.0.1:53: no such host
```

https://go.dev/play/p/kxxT6pToEDC

### What did you expect to see?
 
I expected domain names to be resolved the same way in both cases.

### What did you see instead?

When `CGO_ENABLED=0` is set, the `/etc/resolver` config is ignored by the resolver.

**Comment by mhaley-tignis** [comment] 2022-03-17 12:56
> @mhaley-tignis This issue is really about behavior on Linux.  The resolver issues on macOS are quite different and are best handled elsewhere.  In general on macOS, as far as I know, there is no way to combine `CGO_ENABLED=0` and `/etc/resolver`.  You have to pick one or the other.
>
> _Originally posted by @ianlancetaylor in https://github.com/golang/go/issues/33019#issuecomment-1069628892_

@ianlancetaylor what did you mean by "best handled elsewhere"? Did you mean open a new ticket, or is there a different way to resolve domains on MacOS so that this problem is not encountered?

**Comment by seankhliao** [comment] 2022-03-17 13:04
Duplicate of #12524

**Closed by seankhliao** 2022-03-17 13:04 UTC

**Comment by ianlancetaylor** [comment] 2022-03-18 01:25
Yes, I meant a new issue.  But I see that @seankhliao correctly points out that there is already an issue for this.
