### ISSUE TITLE
flag: `flag.Parse()` seemingly doing nothing in Docker container

### ISSUE THREAD

**Issue by 5HT2** [golang/go#52212] opened 2022-04-07 15:23 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes. I can only reproduce this issue in the `golang:1.18.0` image (not `golang:1.18.0-alpine`).

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/taro-bot/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build624973754=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

Dockerfile: https://github.com/5HT2/taro-bot/blob/8c98aa5584f3e7e4d3fd3267284e12b6caa3090f/Dockerfile
main.go: https://github.com/5HT2/taro-bot/blob/8c98aa5584f3e7e4d3fd3267284e12b6caa3090f/main.go

I'm having an issue where none of my flags are being parsed. 

all i know is
- my os.Args flags DO exist and are being set correctly
- flag.Parsed is true
- flag.Parse() is being called
- printing one of the flags i've called yields the default value for the flag (not the value i've set / the value i can see in os.Args)

I know all this via printing the raw values in order to do some sort of debugging. I have no idea how to get around this or fix it, let alone where the bug stems from.

I *do* know that this does not happen on the `golang:1.18.0-alpine3.15` image. I cannot use this image because Alpine does not have the built-in gcc tools necessary to use `go build -buildmode=plugin`. This does happen on `golang.1.18.0` in my testing, which is Debian.

### What did you expect to see?

I expected my flags to be parsed.

### What did you see instead?

My flags are not parsed.

**Comment by 5HT2** [comment] 2022-04-07 15:28
I can put together a small sample project in just a second.

**Comment by 5HT2** [comment] 2022-04-07 15:55
Even stranger, values that aren't even set in my program flags show as non-default values, eg

```
Step 9/10 : RUN echo "$DEBUG"
---> Running in 23326207052b
false
Removing intermediate container 23326207052b
---> 7273b2a43c4c
Step 10/10 : CMD DEBUG="$DEBUG" TZ="$TZ" PLUGIN_DIR="/taro-bot/bin" /taro-bot/scripts/run.sh
```
`log.Printf("%v\n", *debugLog)` gives `true`, when the flag should default to false according to what I set.

**Comment by cherrymui** [comment] 2022-04-07 19:33
What is the output of the unexpected flag values with your example above? Does it need to use plugin to reproduce? Thanks.

**Comment by seankhliao** [comment] 2022-04-07 19:54
Duplicate of #36263

**Closed by seankhliao** 2022-04-07 19:54 UTC
Labels: NeedsInvestigation

**Comment by 5HT2** [comment] 2022-04-08 03:05
Oh, thank you, that solved it.
