### ISSUE TITLE
x/pkgsite: Functions grouped under type even though not methods

### ISSUE THREAD

**Issue by markuswustenberg** [golang/go#43115] opened 2020-12-10 13:42 UTC
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/maragudk/gomponents 
 
### What is your user agent?
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
  
### Screenshot

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/141763/101779224-455c2f80-3af5-11eb-8e10-8689c549c429.png">
 
### What did you do?
 
Just visited the page.
 
### What did you expect to see?
 
I expected to see package-level functions like `Attr` and `Map` (under `Node`) and `El` (under `NodeFunc`) listed as separate functions for the package. I would expect the functions with the receivers to be shown as methods, and the other functions shown under package-level functions.
 
### What did you see instead?

The functions are grouped with the methods of the types, even though they are not methods themselves, but just return the type.

**Comment by jamalc** [comment] 2020-12-10 16:44
Duplicate of #39813

**Closed by jamalc** 2020-12-10 16:44 UTC
Labels: pkgsite
