### ISSUE TITLE
runtime: crash at startTheWorldWithSema

### ISSUE THREAD

**Issue by thincal** [golang/go#17317] opened 2016-10-02 07:00 UTC
### What version of Go are you using (`go version`)?
1.7

### What operating system and processor architecture are you using (`go env`)?
ubuntu14.04

### What did you do?
I have a program written by Go, which is running to monitor the folder content and do something.
Normally it's working very well, but today I get a coredump file for this program.

### What did you see instead?

There is a crash happened:
```
Thread 1 (LWP 1274):
#0  runtime.raise () at /home/tools/go/src/runtime/sys_linux_arm.s:137
#1  0x0004d734 in runtime.dieFromSignal (sig=6) at /home/tools/go/src/runtime/signal1_unix.go:195
#2  0x0004d8d4 in runtime.crash () at /home/tools/go/src/runtime/signal1_unix.go:272
#3  0x00039238 in runtime.dopanic_m (gp=0x107010e0, pc=231208, sp=275958224) at /home/tools/go/src/runtime/panic.go:684
#4  0x0006ab60 in runtime.dopanic.func1 () at /home/tools/go/src/runtime/panic.go:553
#5  0x0006f0c4 in runtime.systemstack () at /home/tools/go/src/runtime/asm_arm.s:247
#6  0x0003d6a4 in runtime.startTheWorldWithSema () at /home/tools/go/src/runtime/proc.go:1036
#7  0x0003d728 in runtime.mstart () at /home/tools/go/src/runtime/proc.go:1096
#8  0x10700960 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

From the crash call stack, there isn't any info related with my program, could you help check is it a crash caused by the runtime ? many thanks.

**Comment by minux** [comment] 2016-10-02 07:33
Looks like it's crashed due to a panic, do you have the output
from stderr captured?

**Comment by thincal** [comment] 2016-10-02 15:29
it is from a core dump.

**Comment by thincal** [comment] 2016-10-02 15:34
Do you mean the panic is happened inside the runtime or the application code invoke the panic ? If it is the app code call the panic somewhere, there should show the function from app in this call stack, right?

Thanks.

**Comment by quentinmit** [comment] 2016-10-04 14:36
Unfortunately, the core dump does not contain enough information to know what caused the panic. It likely was caused by your application or a library it called, but we just don't know without seeing the output that was printed on stderr. Issue #16893 will add the panic logs to the core dump, so in the future we'll be able to tell you more.

Closing this issue since there isn't anything actionable we can do with this traceback.

**Closed by quentinmit** 2016-10-04 14:36 UTC
