### ISSUE TITLE
preprocessor MACRO support

### ISSUE THREAD

**Issue by andrewhodel** [golang/go#51357] opened 2022-02-25 01:10 UTC
If your program needs something from a specific version, there is no way to tell the user that their version is inadequate within the program.

There is also no way to allow it to still compile with an older version.

**Here's what C uses:**

## Conditional compilation

The directives `#if`, `#ifdef`, `#ifndef`, `#else`, `#elif` and `#endif`can be used for conditional compilation.

```
#if VERSION >= 2
  // code block for this version
#else
  // code block for older versions
#endif
```

An example is `net.conn.NetConn()` not existing until version 1.18 of Go.

**Comment by neetle** [comment] 2022-02-25 01:20
Would a build tag not be sufficient?

**Comment by davecheney** [comment] 2022-02-25 01:35
Duplicate of #35107

**Closed by davecheney** 2022-02-25 01:35 UTC

**Comment by andrewhodel** [comment] 2022-02-25 02:03
@neetle nope, it looks like they are just going to let them sit and die while people walk on in confusion about it.
