### ISSUE TITLE
net/mail: ReadMessage returns EOF in case of header-only messages.

### ISSUE THREAD

**Issue by 0xc0d** [golang/go#47897] opened 2021-08-22 22:52 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/user/sdk/go1.16"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/user/sdk/go1.16/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_r/pyfmdgr15fz3_x7hhfk7gb3r0000gp/T/go-build2586304111=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```go
package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"mime"
	"mime/multipart"
	"net/mail"
	"os"
	"strings"
)

var email = strings.NewReader(`From: <abusedesk@example.com>
Date: Thu, 8 Mar 2005 17:40:36 EDT
Subject: FW: Earn money
To: <abuse@example.net>
MIME-Version: 1.0
Content-Type: multipart/report; report-type=feedback-report;
	boundary="part1_13d.2e68ed54_boundary"

--part1_13d.2e68ed54_boundary
Content-Type: text/plain; charset="US-ASCII"
Content-Transfer-Encoding: 7bit

This is an email abuse report for an email message received from IP
192.0.2.1 on Thu, 8 Mar 2005 14:00:00 EDT.  For more information
about this format please see http://www.mipassoc.org/arf/.

--part1_13d.2e68ed54_boundary
Content-Type: message/feedback-report

Feedback-Type: abuse
User-Agent: SomeGenerator/1.0
Version: 1

--part1_13d.2e68ed54_boundary
Content-Type: message/rfc822
Content-Disposition: inline

Received: from mailserver.example.net
	(mailserver.example.net [192.0.2.1])
	by example.com with ESMTP id M63d4137594e46;
	Thu, 08 Mar 2005 14:00:00 -0400
From: <somespammer@example.net>
To: <Undisclosed Recipients>
Subject: Earn money
MIME-Version: 1.0
Content-type: text/plain
Message-ID: 8787KJKJ3K4J3K4J3K4J3.mail@example.net
Date: Thu, 02 Sep 2004 12:31:03 -0500

Spam Spam Spam
Spam Spam Spam
Spam Spam Spam
Spam Spam Spam

--part1_13d.2e68ed54_boundary--
`)

func main() {
	msg, err := mail.ReadMessage(email)
	if err != nil {
		log.Fatal(err)
	}
	_, params, err := mime.ParseMediaType(msg.Header.Get("Content-Type"))
	if err != nil {
		log.Fatal(err)
	}
	mr := multipart.NewReader(msg.Body, params["boundary"])
	for {
		part, err := mr.NextPart()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Fatal(err)
		}
		contentType := part.Header.Get("Content-Type")
		fmt.Printf("Content-Type: %v\n", contentType)

		b := new(bytes.Buffer)
		b.ReadFrom(part)
		fmt.Printf("Body: %q\n\n", b.String())


		switch {
		case strings.HasPrefix(contentType, "message"):
			msg, err = mail.ReadMessage(b)
			if err != nil {
				log.Println("error occurred:", err)
				break
			}
			io.Copy(os.Stdout, msg.Body)
		default:
			io.Copy(os.Stdout, b)
		}
		fmt.Println("-----------------------------")
	}
}
```

### What did you expect to see?

```
Content-Type: text/plain; charset="US-ASCII"
Body: "This is an email abuse report for an email message received from IP\n192.0.2.1 on Thu, 8 Mar 2005 14:00:00 EDT.  For more information\nabout this format please see http://www.mipassoc.org/arf/.\n"

This is an email abuse report for an email message received from IP
192.0.2.1 on Thu, 8 Mar 2005 14:00:00 EDT.  For more information
about this format please see http://www.mipassoc.org/arf/.
-----------------------------
Content-Type: message/feedback-report
Body: "Feedback-Type: abuse\nUser-Agent: SomeGenerator/1.0\nVersion: 1\n"

-----------------------------
Content-Type: message/rfc822
Body: "Received: from mailserver.example.net\n\t(mailserver.example.net [192.0.2.1])\n\tby example.com with ESMTP id M63d4137594e46;\n\tThu, 08 Mar 2005 14:00:00 -0400\nFrom: <somespammer@example.net>\nTo: <Undisclosed Recipients>\nSubject: Earn money\nMIME-Version: 1.0\nContent-type: text/plain\nMessage-ID: 8787KJKJ3K4J3K4J3K4J3.mail@example.net\nDate: Thu, 02 Sep 2004 12:31:03 -0500\n\nSpam Spam Spam\nSpam Spam Spam\nSpam Spam Spam\nSpam Spam Spam\n"

Spam Spam Spam
Spam Spam Spam
Spam Spam Spam
Spam Spam Spam
-----------------------------
```

### What did you see instead?

```
Content-Type: text/plain; charset="US-ASCII"
Body: "This is an email abuse report for an email message received from IP\n192.0.2.1 on Thu, 8 Mar 2005 14:00:00 EDT.  For more information\nabout this format please see http://www.mipassoc.org/arf/.\n"

This is an email abuse report for an email message received from IP
192.0.2.1 on Thu, 8 Mar 2005 14:00:00 EDT.  For more information
about this format please see http://www.mipassoc.org/arf/.
-----------------------------
Content-Type: message/feedback-report
Body: "Feedback-Type: abuse\nUser-Agent: SomeGenerator/1.0\nVersion: 1\n"

2021/08/23 00:47:39 error occurred: EOF
-----------------------------
Content-Type: message/rfc822
Body: "Received: from mailserver.example.net\n\t(mailserver.example.net [192.0.2.1])\n\tby example.com with ESMTP id M63d4137594e46;\n\tThu, 08 Mar 2005 14:00:00 -0400\nFrom: <somespammer@example.net>\nTo: <Undisclosed Recipients>\nSubject: Earn money\nMIME-Version: 1.0\nContent-type: text/plain\nMessage-ID: 8787KJKJ3K4J3K4J3K4J3.mail@example.net\nDate: Thu, 02 Sep 2004 12:31:03 -0500\n\nSpam Spam Spam\nSpam Spam Spam\nSpam Spam Spam\nSpam Spam Spam\n"

Spam Spam Spam
Spam Spam Spam
Spam Spam Spam
Spam Spam Spam
-----------------------------
```

Note that the example email is from [RFC 5965](https://datatracker.ietf.org/doc/html/rfc5965#appendix-B.1).

I belive the `ReadMessage` should also support header-only messages.

**Comment by seankhliao** [comment] 2021-08-23 10:48
cc @bradfitz

**Comment by dmitshur** [comment] 2021-11-29 21:54
This may be the same as issue #33823. If so, @0xc0d, would it work well to merge this report into that issue?

**Comment by 0xc0d** [comment] 2021-11-29 21:59
Yes it us the same issue, I have already opened a PR for that.
I guess we can merge this report safely. Thank you @dmitshur!

**Comment by seankhliao** [comment] 2022-07-13 21:05
Duplicate of #33823

**Closed by seankhliao** 2022-07-13 21:05 UTC
Labels: NeedsInvestigation
