### ISSUE TITLE
sort: sort.Slice more slower than sort.Sort

### ISSUE THREAD

**Issue by ipfans** [golang/go#22504] opened 2017-10-31 07:39 UTC
### What version of Go are you using (`go version`)?
1.9.2

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""

### What did you do?

```go
// example from sort.Sort

func BenchmarkSort(b *testing.B) {
	var people = []Person{
		{"Bob", 31},
		{"John", 42},
		{"Michael", 17},
		{"Jenny", 26},
	}
	for i := 0; i < b.N; i++ {
		sort.Sort(ByAge(people))
	}
}

func BenchmarkSortSlice(b *testing.B) {
	var people = []Person{
		{"Bob", 31},
		{"John", 42},
		{"Michael", 17},
		{"Jenny", 26},
	}
	for i := 0; i < b.N; i++ {
		sort.Slice(people, func(i int, j int) bool {
			return people[i].Age < people[j].Age
		})
	}
}
```

### What did you expect to see?
sort.Slice as fast as sort.Sort or a little slower than sort.Sort.

### What did you see instead?
sort.Sort about 2.6x faster than sort.Slice.

```
$ go test -bench .
goos: darwin
goarch: amd64
BenchmarkSort-4         20000000                82.4 ns/op
BenchmarkSortSlice-4    10000000               211 ns/op
PASS
```

**Comment by davecheney** [comment] 2017-10-31 07:46
`sort.Slice` uses reflection to avoid the moderate amount of boilerplate required for `sort.Sort`.

I'm going to close this issue as it not directly actionable. It is not a bug in the sort package (we don't expect `sort.Slice` to be as fast as `sort.Sort`) and there are other general bugs about the performance of the reflect package.

**Closed by davecheney** 2017-10-31 07:46 UTC

**Comment by bradfitz** [comment] 2017-10-31 17:14
Sometimes `sort.Slice` is actually faster, depending on the type of elements being sorted. But sometimes `sort.Sort` is faster.
