### ISSUE TITLE
generics: allow interface method to have type parameters

### ISSUE THREAD

**Issue by marmiha** [golang/go#63232] opened 2023-09-26 13:16 UTC
### Author Background

As an intermediate to experienced Go programmer with a background in other popular languages, I primarily use Go for backend development.

### Related proposals

Despite my efforts, I have been unable to find an open or closed issue related to this proposal.

### Proposal

In the current state of Go, when an interface is instantiated, it is necessary to specify the generic type of the interface. This means that once the interface is created, the types of the generics are bound and cannot be changed.

``` go
package main

type (
	User         struct{}
	Store[P any] interface {
		ExecTx(func() (P, error)) (P, error)
	}

	store struct {
	}
)

func (s *store) ExecTx(fn func() (*User, error)) (*User, error) {
	// quasi db transaction,
	user, err := fn()
	if err != nil {
		// rollback
		return nil, err
	}
	// commit
	return user, nil
}

// Here, the ExecTx will return (User, error)
func NewStore() Store[*User] {
	return &store{}
}

func main() {
	store := NewStore()
	// ExecTx will always return (*User, error)
	store.ExecTx(func() (*User, error) {
		// do something
		return &User{}, nil
	})
}

```
Proposal
There are instances, such as the one illustrated above, where it would be beneficial to have interfaces with functions that do not require the generic type to be specified at the time of creation. In the example provided, the `ExecTx `  function executes all the code contained within a database transaction, handles callbacks/rollbacks, and returns only the `*User` if everything is executed correctly. However, there may be situations where we want to return something else. It's worth noting that the transaction function would also accept a database parameter or a database querier to manipulate the database in a real-world scenario.

Currently, one way to achieve this is to create a separate generic function that is not a receiver but accepts the `store` as a parameter:

``` go
package main

type (
	User   struct{}
	Author struct{}
	Store  interface {
		ExecTx(func() error) error
	}

	store struct {
	}
)

func (s *store) ExecTx(fn func() error) error {
	// quasi db transaction,
	err := fn()
	if err != nil {
		// rollback
		return nil, err
	}
	// commit
	return nil
}

func ExecTxWithReturn[P any](store Store, fn func() (P, error)) (P, error) {
	var result P
	err := store.ExecTx(func() error {
		var err error
		result, err = fn()
		return err
	})
	return result, err
}

// Here, the ExecTx will return (User, error)
func NewStore() Store {
	return &store{}
}

func main() {
	store := NewStore()
	// ExecTx returns a User
	_, _ = ExecTxWithReturn[*User](store, func() (*User, error) {
		// db transaction
		return &User{}, nil
	})

	// ExecTx returns an Author
	_, _ = ExecTxWithReturn[*Author](store, func() (*Author, error) {
		// db transaction
		return &Author{}, nil
	})

}
```
In the above eample, the  `ExecTxWithReturn` can return multiple types, but it requires the `Store` interface to call the underlying `ExecTx`. Essentially it acts like a reciever function but with additional steps. It would be more efficient if we could specify generic functions for interfaces where the types can be specified at the time of the call, not at the time of creation. This would allow us to do something like this:

``` go
package main

type (
	User   struct{}
	Author struct{}
	Store  interface {
		ExecTx(func() error) error
		ExecTxWithReturn[P any](func() (P, error)) (P, error)
	}

	store struct {
	}
)

func (s *store) ExecTx(fn func() error) error {
	// quasi db transaction,
	err := fn()
	if err != nil {
		// rollback
		return nil, err
	}
	// commit
	return nil
}

func (store *store) ExecTxWithReturn[P any](fn func() (P, error)) (P, error) {
	var result P
	err := store.ExecTx(func() error {
		var err error
		result, err = fn()
		return err
	})
	return result, err
}

// Here, the ExecTx will return (User, error)
func NewStore() Store {
	return &store{}
}

func main() {
	store := NewStore()
	// ExecTx returns a User
	_, _ = store.ExecTxWithReturn[*User](store, func() (*User, error) {
		// db transaction
		return &User{}, nil
	})

	// ExecTx returns an Author
	_, _ = store.ExecTxWithReturn[*Author](store, func() (*Author, error) {
		// db transaction
		return &Author{}, nil
	})

}
```
This approach would enable us to bind types to functions rather than instances (assuming this is the correct terminology), eliminating the need for unnecessary global function definitions that serve the same purpose. I welcome any discussion on this topic.

**Comment by seankhliao** [comment] 2023-09-26 13:28
Duplicate of #49085

**Closed by seankhliao** 2023-09-26 13:28 UTC
Labels: LanguageChange, v2, Proposal
