### ISSUE TITLE
x/pkgsite: feature request golang packages registry api

### ISSUE THREAD

**Issue by mAmineChniti** [golang/go#69514] opened 2024-09-18 10:06 UTC
### What is the URL of the page with the issue?

**

### What is your user agent?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

### What did you do?

**

### What did you see happen?

**

### What did you expect to see?

i was wondering if its possible or if there already is an api for fetching information about golang packages, it'd be really useful in building stuff like nvim packages to fuzzy search and install golang packages, and many other uses

**Comment by seankhliao** [comment] 2024-09-18 13:04
Duplicate of #36785

**Closed by seankhliao** 2024-09-18 13:04 UTC
Labels: pkgsite

**Comment by mAmineChniti** [comment] 2024-09-18 13:09
@seankhliao the recommended api in #36785 doesn't support stuff like substring search and stuff like that, to look up a package you have to know its full name already, else you won't get any results
