### ISSUE TITLE
encoding/json: Unmarshal of "null" string into map will panic after assignment

### ISSUE THREAD

**Issue by vinceprignano** [golang/go#10411] opened 2015-04-10 11:48 UTC
```go
b := []byte(`null`)
m := map[string]interface{}{}
err := json.Unmarshal(b, &m)
if err != nil {
	fmt.Printf("Error: %s\n", err.Error())
}
fmt.Printf("Reading from map: %v\n\n", m["thiswontpanic"])
m["thiswillpanic"] = ":/"
```
> https://play.golang.org/p/6GgCp-aY4Y

I encountered this behavior in when trying to make requests from a Go consumer to a Go server and passing `nil` as request body. I would have expected `json.Unmarshal` to return an error in this case.

**Comment by bradfitz** [comment] 2015-04-10 12:30
This is working as intended. You're telling it to turn &m into null, and it is, and then you're assigning to a nil map.

`Unmarshal` will return an error if you try to unmarshal an integer or boolean, but null and a JSON object can both unmarshal into a map.

**Closed by bradfitz** 2015-04-10 12:30 UTC

**Comment by vinceprignano** [comment] 2015-04-10 12:34
@bradfitz OK so I guess if that's the intended behavior, why I can still read from the map and it doesn't panic?

**Comment by bradfitz** [comment] 2015-04-10 12:39
Because that's how the Go language works:

    http://golang.org/ref/spec#Map_types

It says `A nil map is equivalent to an empty map except that no elements may be added.`.

**Comment by vinceprignano** [comment] 2015-04-10 12:44
Oh okay good to know :) Thanks Brad.
