### ISSUE TITLE
proposal: go get command - remove 'https://' prefix from module name argument if present

### ISSUE THREAD

**Issue by a-h** [golang/go#61393] opened 2023-07-17 08:09 UTC
When I want to add a module from Github, I often copy/paste the URL from the address bar in the browser.

Modern browsers often only show the part of the URL that would be the Go module name.

![image](https://github.com/golang/go/assets/1029947/9cc361e1-072d-43fa-beb2-8aaef07bd595)

But when you copy the URL with Ctrl+A, Ctrl+C, you actually get https://github.com/aquilax/cooklang-go

When you paste this into the terminal to get the module as `go get https://github.com/aquilax/cooklang-go` you get an error:

```
go: malformed module path "https:/github.com/aquilax/cooklang-go": invalid char ':'
```

I know that what is really the substring after `https://`, but now I have to edit it in the terminal, or use a mouse to carefully select the part I want.

Could we assume that if you put in a URL instead of a module path (i.e. it has `https://` as a prefix), you don't want the `https://` bit, and get the command to automatically strip it?

**Comment by seankhliao** [comment] 2023-07-17 08:53
Duplicate of #12701

**Closed by seankhliao** 2023-07-17 08:53 UTC
Labels: Proposal
