### ISSUE TITLE
x/pkgsite: missing documentation headings/anchors

### ISSUE THREAD

**Issue by ribasushi** [golang/go#39529] opened 2020-06-11 16:29 UTC
### What is the URL of the page with the issue?
 
https://pkg.go.dev/github.com/mna/pigeon
 
 
### What is your user agent?
`N/A`
 
### Screenshot
`N/A`
 
### What did you do?
 `N/A` 
 
### What did you expect to see?
I was expecting `PEG syntax` to appear in the TOC on top, and to be linkable (with the ¶ appearing on hover). At present there is no way to replicate https://godoc.org/github.com/mna/pigeon#hdr-PEG_syntax via https://pkg.go.dev
 
### What did you see instead?
See above

**Comment by mvdan** [comment] 2020-06-15 15:48
Hm, I do see the ¶ link when hovering the heading:

![2020-06-15-16:46:57](https://user-images.githubusercontent.com/3576549/84678463-f3f92c00-af27-11ea-897b-425df5777cd9.png)

It takes me to https://pkg.go.dev/github.com/mna/pigeon?tab=doc#hdr-PEG_syntax, which looks correct.

But I can't find the heading in any index section, which I agree is unfortunate.

**Comment by julieqiu** [comment] 2020-06-15 18:20
Thanks for reporting @ribasushi, and for looking into this @mvdan! It does look like the anchor link for https://pkg.go.dev/github.com/mna/pigeon?tab=doc#hdr-PEG_syntax is working as intended, so going to close this issue.

For listing in the index section, this should be fixed by #38073.

**Closed by julieqiu** 2020-06-15 18:20 UTC
Labels: NeedsFix, go.dev, help wanted
