### ISSUE TITLE
x/tools/cmd/godoc: /share and /compile endpoints are hanging indefinitely

### ISSUE THREAD

**Issue by mabu** [golang/go#28816] opened 2018-11-15 20:48 UTC
Looks similar to #19433 and #19373: nothing happens after clicking "Share", and after some time an alert pops up with "Server error; try again.". Console says:

> Failed to load resource: the server responded with a status of 502

But it works if I change [this line](https://github.com/golang/tools/blob/f87c222f148786695d2ee5761b06751bb9211f61/godoc/static/playground.js#L468) to
`$.ajax("https://play.golang.org/share", {`

**Comment by agnivade** [comment] 2018-11-16 04:32
Possibly related to - https://github.com/golang/go/issues/28793

The request just remains hung. Curl command to reproduce - 

```
curl 'https://golang.org/share' -H 'Accept: */*' -H 'Referer: https://golang.org/pkg/bytes/' -H 'Origin: https://golang.org' -H 'X-Requested-With: XMLHttpRequest' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36' -H 'DNT: 1' -H 'Content-Type: text/plain; charset=UTF-8' --data-binary $'package main\n\nimport (\n\x09"bytes"\n\x09"fmt"\n)\n\nfunc main() {\n\x09fmt.Println(bytes.HasPrefix([]byte("Gopher"), []byte("Go")))\n\x09fmt.Println(bytes.HasPrefix([]byte("Gopher"), []byte("C")))\n\x09fmt.Println(bytes.HasPrefix([]byte("Gopher"), []byte("")))\n}\n' --compressed
```

/cc @broady @andybons

**Comment by broady** [comment] 2018-11-30 19:15
I had a fix sent for this, will follow up. httputil/reverseproxy is busted.

**Comment by andybons** [comment] 2018-11-30 19:22
Great. Thanks, @broady!

**Comment by andybons** [comment] 2018-12-03 22:10
Hey @broady any update?

**Comment by broady** [comment] 2018-12-06 04:57
Dupe of #28134.

**Closed by broady** 2018-12-06 04:57 UTC
Labels: NeedsFix, Soon
