### ISSUE TITLE
cmd/go: documentation for 'fmt' subcommand is not detected as a section

### ISSUE THREAD

**Issue by bcmills** [golang/go#27604] opened 2018-09-10 20:46 UTC
### What did you do?

https://golang.org/cmd/go/

### What did you expect to see?

Section headers for each subcommand

### What did you see instead?

![znjytnggikm](https://user-images.githubusercontent.com/5200974/45323403-ffc8ea80-b518-11e8-9ae2-e78d742a73f0.png)

**Comment by agnivade** [comment] 2018-09-11 03:53
Duplicate of https://github.com/golang/go/issues/27205#issuecomment-415903988. See Brad's comment.

Also - https://github.com/golang/go/issues/27334

Same reason why it's there on tip but not on golang.org.

**Closed by agnivade** 2018-09-11 03:53 UTC
Labels: Documentation, NeedsFix
