### ISSUE TITLE
x/pkgsite: Can't scroll down

### ISSUE THREAD

**Issue by elie-g** [golang/go#47450] opened 2021-07-28 23:02 UTC
### What is the URL of the page with the issue?

Any page of the [website](https://pkg.go.dev/).
 
 
### What is your user agent?

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.40 Safari/537.36
 
### Screenshot

![recorded-2021-07-28T18 45 56](https://user-images.githubusercontent.com/14944216/127406814-a2f046c6-21d7-43b5-aeec-23d02ae80108.gif) 
 
### What did you do?

Nothing?!
 
### What did you expect to see?

The page scrolling down normally.
 
### What did you see instead?

It keeps scrolling back to the top. I can't scroll down.

I tried to clear the page data (cookies, storage, etc.) and hard reload the page but it didn't fix the issue.

**Comment by DrunkenPoney** [comment] 2021-07-28 23:09
I noticed it happens only when the window width is >= 1280 px.

**Comment by cespare** [comment] 2021-07-29 00:24
Does the problem happen in an incognito window?

**Comment by DrunkenPoney** [comment] 2021-07-29 05:55
@cespare Yes it still does.

**Comment by jamalc** [comment] 2021-07-29 18:31
I can't reproduce this in Chrome/92.0.4515.107 on Debian Linux. What flavor of Linux are you running? Are you able to update Chrome to see if that solves the issue?

**Comment by DrunkenPoney** [comment] 2021-07-29 19:59
I just update to the latest version of Chrome (92.0.4515.107) but I still have the same issue.

I'm on Ubuntu 20.10 (Groovy).

**Comment by jamalc** [comment] 2021-07-29 22:38
I can't reproduce in Chrome 92.0.4515.107 on Ubuntu 20.10 either. I have few more ideas if you have the time:

- Does it happen in other web browsers on your system?
- Does it happen if you [disable JavaScript](https://developer.chrome.com/docs/devtools/javascript/disable/)?
- Are there any console errors after scrolling or when the page loads?
- Do you have more than one input device connected, for example both a mouse and trackpad?
- Can you think of any Chrome extensions you have installed that might contribute to issue? 

My best guess is that the code that handles scrolling nav items into view has a sneaky bug somewhere on pkgsite or in the actual Element.scrollIntoView() Web API.

**Comment by oandrew** [comment] 2021-07-29 23:17
I'm seeing the same issue on macOS 11.4 +  Chrome 92.0.4515.107 .



> * Does it happen in other web browsers on your system?

No issues with Safari or Firefox.

> * Does it happen if you [disable JavaScript](https://developer.chrome.com/docs/devtools/javascript/disable/)?

Doesn't happen with JavaScript disabled.

> * Are there any console errors after scrolling or when the page loads?

No console errors. 

> * Do you have more than one input device connected, for example both a mouse and trackpad?

External mouse/keyboard, but disconnecting them does not change anything. It happens when scrolling with keyboard (arrows or home/end) as well 

> * Can you think of any Chrome extensions you have installed that might contribute to issue?
It is happening even with `--disable-extensions` 


Also, as mentioned above, it happens only when browser window is >=1280px wide.

**Comment by jamalc** [comment] 2021-07-30 12:39
@oandrew would you mind also trying in an incognito window?

**Comment by jamalc** [comment] 2021-07-30 13:14
Let's try CL 338589 as a potential fix next after our next deploy on Monday.

**Comment by zhangyoufu** [comment] 2021-08-03 10:48
Still running into this issue. macOS + Chrome M92.

Single stepped to the following code:
```
  private observeTargets() {
    this.addObserver(treeitem => {
      this.expandTreeitem(treeitem);
      this.setSelected(treeitem);
      treeitem.el.scrollIntoView({ block: 'nearest' });
    });
```

**Comment by davidwalter0** [comment] 2021-08-03 13:54
with font size change it doesn't appear to be as much about window size as whether the left panel is visible 

When closed as below scrolling is effective
![image](https://user-images.githubusercontent.com/192699/128027394-a48c44bd-deeb-4f1f-98ef-aed9fe7ad56e.png)


With the left panel visible scrolling breaks, which sounds like it corresponds to the scroll code for short cuts as mentioned above

![image](https://user-images.githubusercontent.com/192699/128027667-21ca378f-fe05-4d6c-8204-0e1a9280a5c1.png)

**Comment by jamalc** [comment] 2021-08-03 15:32
Thanks for the additional context. I'm still unable to reproduce this behavior in Chrome/Safari/Firefox on MacOS or Chrome/Firefox on Ubuntu. We'll disable the feature while we're diagnosing the issue. Please add additional system information (OS, Processor, Input Devices, etc) if you're open to sharing.

**Comment by aluchianic** [comment] 2021-08-03 16:52
same bug for me, but only in `Chrome Version 92.0.4515.107 (Official Build) (x86_64)` in `Opera 77.0.4054.277` works fine. Bug starts when left navigation tab is opened.

Mac Pro (15-inch, 2019) 
Macos BigSur 11.2.3 
i7/6 core

**Comment by jamalc** [comment] 2022-01-12 22:57
Without consistent support for scrollIntoView across all browsers I think the solution for is to leave it disabled. I haven't seen any issues around the current behavior without scrollIntoView so I'll close this issue.

**Closed by jamalc** 2022-01-12 22:57 UTC
Labels: NeedsInvestigation, pkgsite
