### ISSUE TITLE
runtime: crash in checkdead

### ISSUE THREAD

**Issue by dadkins** [golang/go#9576] opened 2015-01-13 00:24 UTC
I had a Go 1.4 server crash out of the http.ListenAndServe loop. It's not a panic and not a log.Fatal! It looks like a runtime bug to me. I'm running on Mac OS X. I cannot reproduce it.

runtime: checkdead: find g 5 in status 1
fatal error: checkdead: runnable g

runtime stack:
runtime.throw(0x40589c)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/panic.go:491 +0xad
checkdead()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.c:2828 +0x287
mput(0x410ca0)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.c:3175 +0x47
stopm()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.c:1176 +0xea
findrunnable(0xc208012000)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.c:1487 +0x562
schedule()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.c:1575 +0x151
runtime.park_m(0xc22a7c4120)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.c:1654 +0x113
runtime.mcall(0x392d4)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:186 +0x5a

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc22c30a060, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc22c30a060, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc22c30a000, 0x0, 0x4b8b48, 0xc20802aa20)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803a020, 0x8a09e, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc20803a020, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc22c31a060, 0x1c6e0f0, 0xc20803a020, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc22c31a060, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0x2b22f0, 0x5, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1808 +0xba
main.main()
	/Users/dan/src/bitmoon/potus/main.go:50 +0x385

goroutine 5 [runnable]:
net.(*pollDesc).Wait(0xc22c30a140, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc22c30a140, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc22c30a0e0, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x4b8b48, 0xc22b98a310)
	/usr/local/Cellar/go/1.4/libexec/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20803a028, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc22c5aa0e8, 0xc20800f000, 0x1000, 0x1000, 0x5b, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc20801e4a0, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc22c31a120)
	/usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc22c31a120, 0xe9e0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc22c31a120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc20800ac00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc20800ac00, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc22c31a120, 0xc22c62d380, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc22c5aa0a0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc22c5aa0a0)
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.4/libexec/src/net/http/server.go:1751 +0x35e

**Comment by randall77** [comment] 2015-01-13 00:47
Looks like the scheduler is confused.  It tries to find a goroutine to work
on, can't find any, starts to shut down an M, and the deadlock detector
throws when it finds a runnable goroutine.
I think this might need a "goto top" in proc.c:1485.  It looks like the
scheduler doesn't try again to find work after threads are woken up due to
network activity.

**Comment by dvyukov** [comment] 2015-01-13 04:26
Keith, please describe the failure scenario that you see in more detail. I don't see how the crash can happen and why the goto is necessary.

**Comment by randall77** [comment] 2015-01-13 04:47
An M is in schedule, then calls findRunnable.  In proc.c:1467-1486, it
calls netpoll and finds some new work (some Gs).  It then calls pidleget,
but doesn't get a p.  It then calls injectglist on the work that it got.
That puts the runnable Gs on the global run queue.  It then falls through
to proc.c:1487 and calls stopm, which calls mput, which calls checkdead.
 checkdead sees a runnable G on the queue and barfs.

That's all hypothetical, of course.  Just a theory from dadkins' stack
trace and reading the code.

I think we just need to prevent the fallthrough in the case where we get
work.  We should go work on that work, not stop.  We're stopping because we
couldn't find a P, of course.  But if that's the case, then
stopm/mput/checkdead shouldn't barf if there are runnable Gs around, right?

**Comment by dvyukov** [comment] 2015-01-13 08:50
If there are no idle Ps, then there are Ms running them, so checkdead must return after the first check.
If some Ps become idle before injectglist, injectglist will do startm for these Ps, so checkdead must return after the first check again.
Can you describe the exact thread interleaving that leads to the crash?

**Comment by dvyukov** [comment] 2015-01-13 08:56
dadkins, does it reproduce it if you run it in a loop for an hour?

**Comment by dvyukov** [comment] 2015-01-13 09:20
What was the value of GOMAXPROCS?

**Comment by dadkins** [comment] 2015-01-13 15:54
Dmitry,

I did not set GOMAXPROCS, so I believe it was just one.

I've only seen this crash once, but I'll leave it running all day today and
see if anything happens.

-Dan

**Comment by dvyukov** [comment] 2015-01-13 16:14
You don't use cgo DNS resolver (-tags=netgo) and the crash happened right after start, right?

**Comment by dadkins** [comment] 2015-01-13 16:28
No, I don't. And the crash didn't happen after start. It had been running
for a while.

-Dan

**Comment by dvyukov** [comment] 2015-01-13 16:58
This is weird. Deadlock detection is disabled when cgo is used (because of extram's)... I don't see how thread counters can be corrupted either...

**Comment by dvyukov** [comment] 2015-01-13 16:59
>  It had been running for a while.

Are you sure?
The crash dump has only two goroutines with ids 1 and 5, so it seems that the app has just started and accepted its first connection.

**Comment by dadkins** [comment] 2015-01-13 18:36
I'm certain this didn't happen on startup. I don't think it crashed prior
to handling any requests, although I'm not completely certain. I believe
that the http server keeps the connection alive and accepts subsequent
requests on the same connection, which might explain the low goroutine
number.

What I had been doing yesterday when this struck was working on this
server, trying out various things, making changes to the code and bouncing
the server to try again. When I said it been up a while, I meant it did not
crash immediately.

Unfortunately (for this bug), I haven't seen the crash since.

-Dan

**Comment by rsc** [comment] 2015-01-14 04:55
In sysmon it says:

	// Need to decrement number of idle locked M's
	// (pretending that one more is running) before injectglist.
	// Otherwise it can lead to the following situation:
	// injectglist grabs all P's but before it starts M's to run the P's,
	// another M returns from syscall, finishes running its G,
	// observes that there is no work to do and no other running M's
	// and reports deadlock.
	incidlelocked(-1);
	injectglist(gp);
	incidlelocked(1);

At the bottom of findrunnable it says:

	// poll network
	if(runtime·xchg64(&runtime·sched.lastpoll, 0) != 0) {
		if(g->m->p)
			runtime·throw("findrunnable: netpoll with p");
		if(g->m->spinning)
			runtime·throw("findrunnable: netpoll with spinning");
		gp = runtime·netpoll(true);  // block until new work is available
		runtime·atomicstore64(&runtime·sched.lastpoll, runtime·nanotime());
		if(gp) {
			runtime·lock(&runtime·sched.lock);
			p = pidleget();
			runtime·unlock(&runtime·sched.lock);
			if(p) {
				acquirep(p);
				injectglist(gp->schedlink);
				runtime·casgstatus(gp, Gwaiting, Grunnable);
				return gp;
			}
			injectglist(gp);
		}
	}

It's worrying that the injectglist(gp) is not protected with the same kind of incidlelocked(-1)/incidlelocked(1). Maybe injectglist itself should do that. 

Given that sched.lock has been released since pidleget and that injectglist releases sched.lock before restarting any m's, it seems plausible that pidleget could return nil, some other m calls stoplockedm, which does pidleput(p) inside handoffp, then injectglist adds the gp's to the global queue and unlocks sched.lock, then the other m calls incidlelocked and finds the "deadlock", because the gp's are on the run queue but startm, which will call mget and do nmidle--, has not been called yet.

This is not what happened to Dan, since his deadlock was reported during findrunnable. But maybe it can happen with findrunnable too. (It's trickier there, because the checking of lastpoll means that if you try to make the "other m" run findrunnable, it ends up being the new network poller instead of getting all the way to stopm.)

**Comment by dvyukov** [comment] 2015-01-14 09:23
> It's worrying that the injectglist(gp) is not protected with the same kind of  incidlelocked(-1)/incidlelocked(1). Maybe injectglist itself should do that.

Deadlock detection is based on number of running *threads* (Ms). While a thread is in findrunnable is it running, so deadlock can't be reported. Sysmon is special, because it is not considered a running thread, and so it does that incidlelocked(-1)/incidlelocked(1).

>Given that sched.lock has been released since pidleget and that injectglist releases sched.lock before restarting any m's, it seems plausible that pidleget could return nil, some other m calls stoplockedm, which does pidleput(p) inside handoffp, then injectglist adds the gp's to the global queue and unlocks sched.lock, then the other m calls incidlelocked and finds the "deadlock", because the gp's are on the run queue but startm, which will call mget and do nmidle--, has not been called yet.

In this scenario deadlock won't be reported because while we are in injectglist the current thread is "running". When injectglist is called from findrunnable, the current thread is a normal M and it is "running" till stopm. When injectglist is called from sysmon, we do incidlelocked(-1)/incidlelocked(1).


What bothers me is that the program uses cgo, and when cgo is in use deadlocks should not be reported at all (due to extram's). So even the following program does not report deadlock:

func main() {
	net.Dial("tcp", "127.0.0.1:12345")
	select{}
}

The only way a deadlock can be reported is if thread counters gets corrupted (due to a data race or a missed increment/decrement). But I don't see how it can happen.

**Comment by rsc** [comment] 2015-01-14 18:54
Okay, thanks. This will have to wait for Go 1.4.2 since we have no idea what's going on.

**Comment by adg** [comment] 2015-02-17 03:03
Go 1.4.2 is imminent, so this will have to wait for 1.4.3.

**Comment by dsociative** [comment] 2015-04-21 20:05
I have the same story. See the log https://gist.github.com/dsociative/cdc90f0bd80c53517988
```go version go1.4.1 linux/amd64```

**Comment by davecheney** [comment] 2015-04-22 23:19
Please try go 1.4.2 and confirm if this is resolved.

**Comment by dsociative** [comment] 2015-04-23 17:41
OK, it may take a long time. After the error, I restarted the program and it works fine for 2 days.

**Comment by laboger** [comment] 2015-06-25 18:18
Hi, we have just started seeing this error with Docker latest when built with gccgo from the gcc5 branch, latest code.  We have seen it on ppc64le Ubuntu 14.04 and 14.10.  The information I received is that it also happens with gccgo when built for x86.

panics with the same checkdead message as above

Should we add information to this issue or create a new one?

Our stacks don't look the same as what's here, from the cases where we've seen it occur, there is always a stack with syscall.Exitsyscall at the top, like this (but not always from a signal):

goroutine 19 [runnable]:
syscall.Exitsyscall
	../../../src/libgo/runtime/proc.c:2122
os_signal.signal_recv
	../../../src/libgo/runtime/sigqueue.goc:110
signal.loop
	../../../src/libgo/go/os/signal/signal_unix.go:21
created by os_signal..import
	../../../src/libgo/go/os/signal/signal_unix.go:25

**Comment by josharian** [comment] 2015-06-25 18:35
@laboger please file a new issue. Thanks!

**Comment by ianlancetaylor** [comment] 2015-07-14 00:13
I can't tell if this is still a problem or not.  Is this still happening?

I'm changing the milestone to 1.5 since there won't be a 1.4.3.

**Comment by rsc** [comment] 2015-07-22 20:58
I'm going to close this as can't reproduce. If someone _can_ reproduce it, please file a new bug. Thanks.

**Closed by rsc** 2015-07-22 20:58 UTC
