### ISSUE TITLE
x/pkgsite: Syntax Highlight example blocks

### ISSUE THREAD

**Issue by Rhymond** [golang/go#52198] opened 2022-04-07 08:15 UTC
### What is the URL of the page with the issue?
Any page containing example block, e.g. https://pkg.go.dev/io#example-Copy

### What is your user agent?

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
```

### Screenshot

![image](https://user-images.githubusercontent.com/3577968/162151843-0716467b-6dd8-4d6b-8307-d5f96a7faed7.png)

### What did you do?

Open package documentation example

### What did you expect to see?

Syntax Highlighted code block. 

### What did you see instead?

A text blob without syntax highlight

**Comment by Rhymond** [comment] 2022-04-07 08:20
https://github.com/golang/go/issues/40952 describes similar issue, but with comment code blocks. As I understand correctly it is hard to recognise comment code blocks language, however `Example` blocks are always (?) written in Go and can be highlighted.

**Comment by hyangah** [comment] 2022-10-06 17:07
Duplicate of #56081

**Closed by hyangah** 2022-10-06 17:07 UTC
Labels: FeatureRequest, pkgsite
