### ISSUE TITLE
proxy.golang.org: sigs.k8s.io/structured-merge-diff shoud not have version "v4.2.2"

### ISSUE THREAD

**Issue by zhugefenghao** [golang/go#54190] opened 2022-08-02 05:12 UTC
I find the package "sigs.k8s.io/structured-merge-diff" with version "v4.2.2"(which is not available actually) is in proxy.golang.org, but it is not on [Github tags page](https://github.com/kubernetes-sigs/structured-merge-diff/tags) and this results in failure on building our project. We use v4.2.1 before, but now when we use `go get -u`, it will upgrade and cause some dependencies error. Could you please help look into this issue?

`curl https://proxy.golang.org/sigs.k8s.io/structured-merge-diff/v4/@v/list`
response:
v4.2.1
v4.1.2
**v4.2.2**
v4.0.2
v4.0.0
v4.1.1
v4.0.1
v4.1.0
v4.2.0
v4.0.3

Thank you in advance.

**Comment by seankhliao** [comment] 2022-08-02 08:01
the proxy is a permanent cache
see https://github.com/kubernetes-sigs/structured-merge-diff/pull/220#issuecomment-1201564367

Closing as working as intended

**Closed by seankhliao** 2022-08-02 08:01 UTC
Labels: proxy.golang.org
