### ISSUE TITLE
proposal: encoding/json: add interface for omitempty

### ISSUE THREAD

**Issue by MrTravisB** [golang/go#32675] opened 2019-06-18 23:03 UTC
It would be nice to be able to omit objects from encoding that are of some custom type. For instance

	type Name struct {
		First string `json:"first,omitempty"`
		Last string `json:"last,omitempty"`
	}

	type Person struct {
		Name Name `json:"name,omitempty"`
		Age int `json:"age"`
	}

	p := Person{
		Age: 42,
	}
	b, _ := json.Marshal(p)
	fmt.Println(string(b))

Ideally that would print 

    {"age":42}

but instead it prints

    {"name":{},"age":42}

What would be nice would be to have an interface, `json.Empty`, which could be used to determine if the value is empty or not.

	type Empty interface {
		IsEmpty() bool
	}

	func (n Name) IsEmpty() bool {
		return n.First == "" && n.Last == ""
	}

The check for this could then just be another case added to `json.isEmptyValue()`

	if emp, ok := v.Interface().(Empty); ok {
		return emp.IsEmpty()
	}

**Comment by agnivade** [comment] 2019-06-19 03:27
Duplicate of https://github.com/golang/go/issues/11939.

And I guess you already knew, but just wanted to put it out there - if you change `Name` to a pointer like 
```
Name *Name `json:"name,omitempty"`
```

`"name": {}` goes away.

**Closed by agnivade** 2019-06-19 03:27 UTC
Labels: Proposal
