### ISSUE TITLE
container/heap/example_pq_test

### ISSUE THREAD

**Issue by sowhyim** [golang/go#36522] opened 2020-01-13 09:40 UTC
item.index = -1 // for safety
I get this from PriorityQueue.Pop. But i don't know this is for what purpose?

**Comment by ALTree** [comment] 2020-01-13 10:07
My guess in that since `Item.index` is an internal detail (as the comment above says: "The index is needed by update and is maintained by the heap.Interface methods"), `Pop` sets it to something that is not a valid index before returning the item to avoid issues if the item is erroneously pushed again.

That said, the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-01-13 10:07 UTC
