### ISSUE TITLE
x/build: arm5spacemonkey: misc/cgo/stdio.test: permission denied opening file

### ISSUE THREAD

**Issue by onionjake** [golang/go#33058] opened 2019-07-11 14:49 UTC
Looking at the last 5 builds for `arm5spacemonkey` they all had this error:

```
##### ../misc/cgo/stdio
go test misc/cgo/stdio.test: open /home/builder/stage0scratch/workdir/go/misc/cgo/stdio/test.test: permission denied
2019/06/13 08:23:27 Failed: exit status 1
```

Is there anything we need to fix on the builder side?  We are happy to help out.

**Comment by onionjake** [comment] 2019-07-11 15:08
It looks like as of the 14th of May they were passing.

This was the last one to pass: https://go-review.googlesource.com/q/a75bfb05b30bdc1e3400024d1d29612349280174

Here was the first failure with the permission denied:
https://build.golang.org/log/6f8fe1c2934a29c29dbc748a05dd2dee2b17e3ee
https://go-review.googlesource.com/q/1e3ffb0c902fc282469e7748ce066ee9ea7a6580

Which seems unlikely to have caused the problem.

I suspect the problem commit was https://go-review.googlesource.com/c/go/+/163477

@bradfitz do you need me to investigate this further on the builders?

**Comment by bcmills** [comment] 2019-07-12 17:27
Duplicate of #32407

**Closed by bcmills** 2019-07-12 17:27 UTC
Labels: Builders
