### ISSUE TITLE
x/tools/gopls: prefer modules in `go.mod` when importing or ranking completion items

### ISSUE THREAD

**Issue by hyangah** [golang/go#38461] opened 2020-04-15 15:04 UTC
go version: 1.14
gopls version: 0.4.0

When there are multiple matching packages with similar APIs (e.g. v1 vs v2)
and users already specified the preference in their `go.mod`, I think, choosing 
the one listed in the `go.mod` makes more sense. 

----
Let's assume an incomplete go file:
```
$ cat main.go
package main

func main() {
        gax.Sleep(context.Background(), 1*time.Second)
}
```

When only one version exists in the module cache, everything works fine.
```
$ export GOPATH=`mktemp -d`
$ go get github.com/googleapis/gax-go/v2
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
...
$ gopls imports main.go
package main

import (
	"context"
	"time"

	"github.com/googleapis/gax-go/v2"
)
...
```

Let's add the version 1 in the module cache, but leave the original go.mod file untouched.
(So, only the v2 module is listed)

```
$ cp go.mod fake.mod
$ go get -modfile=fake.mod github.com/googleapis/gax-go
go: downloading github.com/googleapis/gax-go v1.0.3
...
$ gopls imports main.go
package main

import (
	"context"
	"time"

	"github.com/googleapis/gax-go"
)
...
```

Same idea can apply to the auto-completion. In the below image, the completion item lists include candidates from both v1 and v2. The VS Code UI is not great at telling where the candidate is from. The first `APICall` is from v1. 

<img width="890" alt="Screen Shot 2020-04-15 at 10 15 15 AM" src="https://user-images.githubusercontent.com/4999471/79352799-4ad28d00-7f08-11ea-9794-c8358682567b.png">

**Comment by heschik** [comment] 2020-04-29 21:10
Dupe of #38104, AFAICT. For what it's worth, because loaded packages are fully scanned and sorted, this is likely to be less of a problem in a real project rather than a trivial main program.

**Comment by hyangah** [comment] 2020-04-29 21:39
FYI - I filed this issue based on a real scenario - that involved an attempt to migrate a repo from v1 to v2 api.

**Comment by heschik** [comment] 2020-04-29 21:49
If you had only `v2` in the `go.mod`, then it should have been selected.

**Closed** 2020-05-27 17:51 UTC
Labels: Tools, gopls
