### ISSUE TITLE
cmd/compile: infer generic type based on the function return type

### ISSUE THREAD

**Issue by handsomefox** [golang/go#54791] opened 2022-08-31 11:13 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code></summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\hands\AppData\Local\go-build
set GOENV=C:\Users\hands\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\hands\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\hands\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\hands\AppData\Local\Temp\go-build3627023353=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

Wrote a generic struct and created a method that returns an empty instance of it.

```go
type Example[T any] struct{}

func Function() Example[int] {
	return Example{}
}
```

### What did you expect to see?

I expected the above code to infer generic type of `Example` based on the return type of the function and work.

### What did you see instead?

The code does not compile, with an error message: `cannot use generic type Example[T any] without instantiation`.

You have to explicitly change the function to look like:
```go
func Function() Example[int] {
	return Example[int]{}
}
```
to make it work.

**Comment by seankhliao** [comment] 2022-08-31 16:54
Duplicate of #51928

**Closed by seankhliao** 2022-08-31 16:54 UTC
Labels: compiler/runtime
