### ISSUE TITLE
cmd/compile: syntax error for valid type parameter list

### ISSUE THREAD

**Issue by go101** [golang/go#51488] opened 2022-03-04 20:43 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18rc1 linux/amd64
</pre>

### What did you do?

```Go
type foo[T *string,] struct{x T}      // okay
type bar[T *string|bool,] struct{x T} // syntax error: unexpected comma; expecting ]
```

### What did you expect to see?

compiles okay

### What did you see instead?

fails to compile

**Comment by ianlancetaylor** [comment] 2022-03-04 20:46
CC @griesemer

**Comment by ianlancetaylor** [comment] 2022-03-04 20:47
Thanks, we can address this for 1.19.

**Comment by go101** [comment] 2022-03-04 20:57
more forms:

```
type bar[T *string|bool] struct{x T}
type bar[T *[]int|bool] struct{x T}
```

**Comment by griesemer** [comment] 2022-03-04 21:16
We're aware of them, thanks. See #49482.

**Comment by go101** [comment] 2022-03-04 21:31
So this is covered in spec? 

```
package main

const T, int, bool = 1, 1, 2

type bar[T *int|bool] struct{}

func main() {
	var _ bar
}
```

But it looks this one is not covered in spec.
`*string` is also a type literal, but this line fails to compile.
Maybe it should always compile? Because `*string` may not be a constant,

```
type bar[T **string,] struct{} // *string (type) is not an expression
```

**Comment by go101** [comment] 2022-03-04 21:34
sorry, remove one `,` from the last comment.

**Comment by go101** [comment] 2022-03-05 02:14
Is it worth considering this case: https://github.com/golang/go/issues/6386#issuecomment-1059650945 ?

**Comment by go101** [comment] 2022-03-05 07:28
Not sure whether or not this is intended:

```Go
type C4[T ([]int)] struct{}      // compiles okay
type C5[T ([]int)|bool] struct{} // fails to compile
```

**Comment by go101** [comment] 2022-03-15 16:48
Luckily, `aConstString[i]` is not a constant.

```Go
const S = "abcde"
const int = 2
const N = S[2]*int // error

type _ [S[2]*int] struct{} // error
```

**Comment by griesemer** [comment] 2022-03-18 00:43
Closing as duplicate of #49482.

**Closed by griesemer** 2022-03-18 00:43 UTC
Labels: NeedsInvestigation
