### ISSUE TITLE
switch type does not work

### ISSUE THREAD

**Issue by elebore** [golang/go#13765] opened 2015-12-29 07:23 UTC
There are two files,main.go and main1.go

-------------------------content of main.go----------------------------------------
package main
import "code.google.com/p/go.net/websocket"
func main() {
websocketConn := websocket.Conn{}
TestFunc(&websocketConn)
}
----------------------------------end of main.go--------------------------------------------------
----------------------content of main1.go------------------------------------------
package main
import (
"fmt"
"net"
"reflect"
"golang.org/x/net/websocket"
)

func TestFunc(conn net.Conn) {
switch conn.(type) {
case *websocket.Conn:
fmt.Println("OK")
default:
fmt.Println("NOT")
}
}
----------------------------------------end of main1.go----------------------------------------------
We should get OK from console by running this program on windows 10 compiling with go 1.5.2,but I got NOT,when I moved TestFunc to file main.go,then I got OK

**Comment by davecheney** [comment] 2015-12-29 07:29
Duplicate of #13760. Please see https://golang.org/wiki/Questions if you'd like to discuss this further.

**Closed by davecheney** 2015-12-29 07:29 UTC
