### ISSUE TITLE
x/pkgsite: change stdlib's documentation source repo to GitHub?

### ISSUE THREAD

**Issue by aofei** [golang/go#44829] opened 2021-03-06 08:11 UTC
The current documentation source repo of the stdlib is https://go.googlesource.com/go, which is fine. But to be honest, when it comes to code browsing, I think Gitiles lacks some handy features compared to GitHub. Like better syntax highlighting, [code reference](https://docs.github.com/en/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet) and [code navigation](https://docs.github.com/en/github/managing-files-in-a-repository/navigating-code-on-github).

So, since the documentation source repo of most modules in [pkg.go.dev](https://pkg.go.dev) are on GitHub (including `golang.org/x/...`), maybe stdlib can do the same (for better code browsing).

Just a suggestion. 🙂

/cc @julieqiu

**Comment by fsouza** [comment] 2021-03-06 12:33
The stdlib is already on github. https://github.com/golang/go is a mirror of https://go.googlesource.com/go.

**Comment by aofei** [comment] 2021-03-06 12:41
@fsouza 

Sorry, that was not what I meant. I mean the documentation source. For example, the [`http.Request`](https://pkg.go.dev/net/http#Request)'s documentation source is currently https://go.googlesource.com/go/+/go1.16/src/net/http/request.go#102 instead of https://github.com/golang/go/blob/go1.16/src/net/http/request.go#L102.

**Comment by fsouza** [comment] 2021-03-06 12:42
@aofei ohh gotcha. Sorry for the confusion, my bad

**Comment by julieqiu** [comment] 2021-03-08 17:43
Closing this as a duplicate of #44832.

**Closed by julieqiu** 2021-03-08 17:43 UTC
Labels: NeedsInvestigation, pkgsite
