### ISSUE TITLE
x/tools/gopls: rebuilding golden tests fails

### ISSUE THREAD

**Issue by pjweinb** [golang/go#45272] opened 2021-03-28 12:15 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.16.2 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pjw/Library/Caches/go-build"
GOENV="/Users/pjw/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/pjw/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/pjw/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/72/mj6w6gyj5dn6yp_2_tlbdwym00052r/T/go-build679490406=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
Following the instructions in golang.org/x/tools/internal/lsp/tests/README.md, I executed
<pre>./internal/lsp/reset_golden.sh</pre>

### What did you expect to see?
i expected no changes

### What did you see instead?
<pre>
	deleted:    internal/lsp/analysis/fillreturns/testdata/src/a/a.go.golden
	deleted:    internal/lsp/analysis/nonewvars/testdata/src/a/a.go.golden
	deleted:    internal/lsp/analysis/noresultvalues/testdata/src/a/a.go.golden
	deleted:    internal/lsp/analysis/simplifycompositelit/testdata/src/a/a.go.golden
	deleted:    internal/lsp/analysis/simplifyrange/testdata/src/a/a.go.golden
	deleted:    internal/lsp/analysis/simplifyslice/testdata/src/a/a.go.golden
	modified:   internal/lsp/testdata/godef/b/h.go.golden
	modified:   internal/lsp/testdata/signature/signature.go.golden
	modified:   internal/lsp/testdata/signature/signature_test.go.golden
	modified:   internal/lsp/testdata/snippets/literal.go.golden
</pre>

Because of the deleted files the tests no longer pass. (The modified files don't affect test results.)

**Comment by ShoshinNikita** [comment] 2021-07-15 11:02
Analyzer tests don't support rebuilding .golden files. So, the script just deletes .golden files under `internal/lsp/analysis/`. There are two possible solutions:

1. Don't remove .golden files for analyzer tests

    ```diff
    #!/bin/bash

    - find ./internal/lsp/ -name *.golden -delete
    + find ./internal/lsp/testdata/ -name *.golden -delete
    go test ./internal/lsp/source -golden
    go test ./internal/lsp/ -golden
    go test ./internal/lsp/cmd -golden
    ```

2. Add support for rebuilding .golden files for analyzer tests

---

There's also a new issue with rebuilding .golden files. Commit golang/tools@4c651fc1fc751d8e42d6b4f099ee1b9df6404e07 added `summary_generics.txt.golden`. It is used when type parameters are [enabled](https://github.com/golang/tools/blob/4c651fc1fc751d8e42d6b4f099ee1b9df6404e07/internal/lsp/tests/tests.go#L48):

```go
var summaryFile = "summary.txt"

func init() {
	if typeparams.Enabled {
		summaryFile = "summary_generics.txt"
	}
}
```

The problem is that we can't rebuild `summary.txt.golden` and `summary_generics.txt.golden` at the same time:

| typeparams.Enabled | `summary.txt.golden` | `summary_generics.txt.golden` |
| ------------------ | -------------------- | ----------------------------- |
| false              | rebuilt              | removed                       |
| true               | removed              | rebuilt                       |

**Comment by findleyr** [comment] 2023-09-07 21:53
Closing as redundant with https://go.dev/issue/54845

**Closed by findleyr** 2023-09-07 21:53 UTC
Labels: Testing, gopls, Tools
