### ISSUE TITLE
proposal: x/crypto: Not all parameters of the argon 2 specification are included in spec

### ISSUE THREAD

**Issue by peter021** [golang/go#60179] opened 2023-05-13 19:18 UTC
The current interfaces are:
func IDKey(password, salt []byte, time, memory uint32, threads uint8, keyLen uint32) []byte
func Key(password, salt []byte, time, memory uint32, threads uint8, keyLen uint32) []byte

Parameters "Secret" and "Associated data" mentioned in the spec https://github.com/P-H-C/phc-winner-argon2/blob/master/argon2-specs.pdf are not listed in the above definition. 

Parameter secret is meant for creating application specific hashes.

Parameter "Associated data" is meant for a hash calculated on session specific data. A password and salt should for some use cases return different hashes based on agreed session specific data: A date value (new keys each day?); user data; direction data; protocol data; classifications data; filenames, and whatever both ends of the session agree on.

How do we get those important parameters included?

**Comment by seankhliao** [comment] 2023-05-13 20:19
Duplicate of #35481

**Closed by seankhliao** 2023-05-13 20:19 UTC
Labels: Proposal
