### ISSUE TITLE
x/website:  MISSING HIGHLIGHT @ https://go.dev/doc/tutorial/greetings-multiple-people

### ISSUE THREAD

**Issue by CharingJC** [golang/go#52782] opened 2022-05-09 04:20 UTC
### What is the URL of the page with the issue?
 https://go.dev/doc/tutorial/greetings-multiple-people
 
 
### What is your user agent?
 

 [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36 Edg/101.0.1210.39](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
### Screenshot
 

 
<img width="409" alt="image" src="https://user-images.githubusercontent.com/74894646/167339680-cd2f85d3-0b7d-4964-9a44-0aad6e58a5e5.png">

 
 
### What did you expect to see?
 
I am going for the missing highlight in the code example.
We have applied change to those marked lines, but no highlight has been marked yet
<img width="359" alt="image" src="https://user-images.githubusercontent.com/74894646/167339988-26d36fec-28be-406f-98f2-469b8e6fcf26.png">
Highly recommend to update the doc since tons of new users may get mis-lead and get an unexpected output with the current sample code

**Comment by seankhliao** [comment] 2022-05-09 07:46
Duplicate of #46416

**Closed by seankhliao** 2022-05-09 07:46 UTC
