### ISSUE TITLE
How to close http2 client connection?

### ISSUE THREAD

**Issue by hzxuzhonghu** [golang/go#25840] opened 2018-06-12 07:35 UTC
I want to close http2 connection when I do not receive any data on this connection.

I have no idea. But I do not want the useless hanging connection.

**Comment by ALTree** [comment] 2018-06-12 08:28
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2018-06-12 08:28 UTC
