### ISSUE TITLE
cmd/go: go build support for importing/linking additional packages

### ISSUE THREAD

**Issue by CAFxX** [golang/go#14088] opened 2016-01-25 12:29 UTC
I would love to be able to specify during go build/run additional packages to be imported. This would be mostly useful for those packages that are imported for their side effects.

As an example consider:

```
$ go build example.com/myapp -import github.com/go-sql-driver/mysql
```

This should have the same effect as adding the following import in the root package of myapp:

```
import _ "github.com/go-sql-driver/mysql"
```

Right now I'm using a [quick-and-dirty tool](https://github.com/CAFxX/pluggo/tree/master/cmd/multibuild) for this but I really can't help thinking this should be part of the go command. 

This would basically enable a very rudimental form of (compiler-mediated) DI.

**Comment by minux** [comment] 2016-01-25 12:54
What's wrong with putting the side effect import
statement into a source file?

Note that you can easily switch between sql database
drivers by having multiple files each with a different
build tag and import a different sql driver package.

**Comment by CAFxX** [comment] 2016-01-25 13:04
This assumes that the myapp author has either included all possible database/sql drivers, or that it provides a file for each database/sql driver with its own tag. Even just with SQL drivers  (https://github.com/golang/go/wiki/SQLDrivers lists more than 20) this becomes hard quickly: imagine what could happen with application modules or plugins. Moreover, if the myapp maintainer doesn't want to import a specific package, you need to patch manually every time you build/run.

Sure, the current state is not unbearable... it just feels like an unneeded hop to jump through.

**Comment by minux** [comment] 2016-01-25 13:12
Allowing -import at go build/install time will not solve the problem either.

Consider:
go install pkg -import xxx/sql-driver -import yyy/plugin1 -import
zzz/plugin2

as compared to adding (and checking into SCM) a new file to pkg with the
content:
package pkg
import (
   _ "xxx/sql-driver"
   _ "yyy/plugin1"
   _ "zzz/plugin2"
)

The proposed the solution might be convenient but will quickly grow into
maintenance problems (you can no longer reproduce the exact build
because you don't know the options used to build it and the command
is not checked into the repo.) Even build tags use should be minimized
for the same reason.

**Comment by CAFxX** [comment] 2016-01-25 13:27
The fact that the use of something should be minimized doesn't imply that that something is not useful if used properly. I'm not advocating abuse of the feature I'm proposing; I'm advocating that it would be useful in certain limited scenarios - similarly to build tags, the -X flag to `go tool link` and cgo (all things that make reproducing an exact build basically impossible).

**Comment by bcmills** [comment] 2019-01-23 18:11
This request is missing a key detail: when would the package initializers for the extra packages run? (_Before_ the initializers for the packages imported from `package main`, or _after_?)

At the moment, we have the nice property that package initializers run in a strict topological order.

**Comment by bcmills** [comment] 2019-01-23 18:21
Note that you can structure something more-or-less as @minux suggests using modules and `replace` directives.

`example.com/main/go.mod`:
```
module example.com/main

require example.com/inject v1.0.0
```

`example.com/main/main.go`:
```go
package main

import _ "example.com/inject"
[…]
```

`example.com/inject/go.mod`
```
module example.com/inject
[…]
```

`example.com/inject/inject.go`:
```go
package inject

import _ "github.com/go-sql-driver/mysql"
```

`my.localhost/go.mod`:
```
module my.localhost

require example.com/main v1.0.0

replace example.com/inject => ./inject
```

`my.localhost/inject/go.mod`:
```
module example.com/inject
[…]
```

`my.localhost/inject/inject.go`:
```go
package inject

import _ "my.localhost/sql-driver"
```

**Closed** 2019-02-23 18:30 UTC
Labels: FeatureRequest, NeedsDecision, WaitingForInfo
