### ISSUE TITLE
io: Document that io.ByteReader should return 0 when error is set.

### ISSUE THREAD

**Issue by smasher164** [golang/go#20825] opened 2017-06-28 04:49 UTC
Is there a situation in which an io.ByteReader will return a nonzero byte value along with io.EOF? Code that relies on this assumption expects that a zero-value is implicitly returned at the end of a file, for example in utf8 rune-handling code.

All public standard library implementations of ReadByte return 0 on EOF. Additionally, the documentation for io.Reader suggests that implementations return certain combinations of values in different situations, like (0, EOF) at the end of an input stream, and (0, nil) only when len(p) == 0. 

Seeing that io.ByteReader has consistent implementations across the standard library, can its documentation suggest that 0 be returned on EOF?

**Comment by bradfitz** [comment] 2017-06-28 04:59
Go convention is that for a function or method returning (T, error), T is not to be considered if the error != nil unless otherwise documented, and we try to only document the exceptions so the documentation doesn't turn into stutter everywhere.

But considering that io.Reader is such an exception and io.ByteReader looks similar in name, I could see the argument for calling out the behavior here explicitly.

**Comment by bradfitz** [comment] 2017-06-28 05:00
But we wouldn't document that the byte must be 0. Just that it's meaningless if error != nil.

**Comment by smasher164** [comment] 2017-06-28 05:43
That sounds reasonable, since callers can't assume anything about the return value in that case. Is it okay to submit a CL?

**Comment by bradfitz** [comment] 2017-06-28 05:46
Go for it. Note that document CLs are some of the pickiest reviews, so it might take a few rounds of wordsmithing until it matches Go doc style.

**Comment by dsnet** [comment] 2017-06-28 06:40
FYI, this is a duplicate of #11308.

**Comment by smasher164** [comment] 2017-06-28 07:16
Although CL mentioned in #11308 is well worded, this issue tries to make more of an implication. I think any possible confusion arises out of the fact that callers care about the value of the byte, not the error. Taking inspiration from math/big, one possibility is "The returned byte is valid but not defined if an error is reported."

**Closed** 2017-06-29 23:03 UTC
Labels: Documentation, NeedsFix
