### ISSUE TITLE
Proposal: Functions inside struct

### ISSUE THREAD

**Issue by ysaakpr** [golang/go#16547] opened 2016-07-30 09:05 UTC
Why golang not supporting functions inside a struct. If its a technical problem, why dont give class construct, which allows user to define functions inside the class, while compile time compiler can split it into outside if necessary.

```
type Object class{
    id       int
    name string

    func SomeOperations(){
    }
}
```

must be equivalent to 

```
type Object struct{
    id       int
    name string
}

func (self *Object)SomeOperations(){
}
```

I think its a unnecessary overhead to always type the stuct name whenever we need to right a function related to the struct. The problem is if I need to change the class name, and I am not using an IDE my life is hectic to refactor the code. This approach will give users from other OOP world to get adapted easily.

**Comment by ALTree** [comment] 2016-07-30 14:47
A similar proposal (and a few objections that are also applicable here) is at #16114

**Comment by dsnet** [comment] 2016-07-30 17:41
I'm going to close this as a duplicate of #16114, which is aiming to solve the issue at hand, which is the "unnecessary overhead to always type the [struct] name".

**Closed by dsnet** 2016-07-30 17:41 UTC
