### ISSUE TITLE
go vet 

### ISSUE THREAD

**Issue by georgettica** [golang/go#46946] opened 2021-06-27 11:11 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes, I guess 1.16.5 is quite latest

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
 go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rogreen/Library/Caches/go-build"
GOENV="/Users/rogreen/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/rogreen/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/rogreen/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/tmp/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c4/g61pspkn4xs4bbsn74j21gvc0000gp/T/go-build4249945016=/tmp/go-build -gno-record-gcc-switches -fno-common
</pre></details>

### What did you do?

https://play.golang.org/p/JXG1PlhSbeP

* run `go vet`

### What did you expect to see?

the vet to pass successfully

### What did you see instead?

vet: ./main.go:9:3: foo declared but not used

**Comment by seankhliao** [comment] 2021-06-27 14:16
vet flags variables which are only assigned to as unused

Closing as working as intended

**Closed by seankhliao** 2021-06-27 14:16 UTC

**Comment by georgettica** [comment] 2021-07-06 19:17
After re-looking on it, I see how I should rewrite my code for it to work more as intended

Thank you!
