### ISSUE TITLE
x/playground: add code highlighting

### ISSUE THREAD

**Issue by cn007b** [golang/go#28539] opened 2018-11-01 22:32 UTC
Is it possible to improve "Go Playground" code highlight?
And instead of black code have something like default github code highlight,
for example something like [this](https://github.com/golang/go/blob/master/src/fmt/format.go).

**Comment by mvdan** [comment] 2018-11-01 22:49
Duplicate of https://github.com/golang/go/issues/21123, which was already a duplicate of a golang-dev thread. I don't think anything has changed since.

**Comment by ALTree** [comment] 2018-11-02 13:49
@mvdan Note that at the end of that golang-nuts thread, Andew Gerrand wrote:

> For the record: Christoph Hack said he was going to prepare a change
to restore the more sophisticated editor to the playground. This would
include a syntax highlighting option that defaults to "off" (as per
the tour). If this change can be made without any regressions then it
will be accepted. 

This was back in 2012, but it appears that adding syntax colouring to the playground wasn't completely out of the question (in fact, Andrew explicitly said the change would be accepted). It is also still true that tour has a "Syntax on/off" button; so it wouldn't be that strange to add it to the playground.

The other linked issue (#21123) wasn't really resolved with a final decision, the OP just closed it because they were able to find a playground clone with syntax highlighting.

I think it would be nice to have a final and clear decision on this; for this reason I'm reopening this issue. 

cc @andybons

**Comment by mvdan** [comment] 2018-11-02 13:52
I hadn't noticed that; reopening for now is indeed a good idea.

**Comment by ysmolsky** [comment] 2018-11-02 16:55
Here we decided that syncing playground with a CodeMirror library (the one used by go-tour) is a no-go: https://github.com/golang/go/issues/18723. Andy suggested to move the tour to simpler library instead of adding sophisticated lib to the playground for the sake of syntax highlighting. 

My opinion echoes Andy. It should be solved by adding custom code that does what is required only, no bloat and slow rendering. It should not be done by including big libraries where we would use 1% of functionality.

**Comment by andybons** [comment] 2018-11-02 19:14
Agreed with @ysmolsky. As we converge the codebases, we don't want to regress syntax highlighting on the tour, so it should remain supported across the two tools. As long as it's lazy-loaded and not on by default I don't see an issue.

**Comment by andybons** [comment] 2018-11-02 19:15
Duplicate of #18723

**Closed by andybons** 2018-11-02 19:15 UTC
Labels: NeedsFix
