### ISSUE TITLE
Jumping Failed With Gopls

### ISSUE THREAD

**Issue by aigo-tech** [golang/go#35333] opened 2019-11-04 03:08 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
</pre></details>

### What did you do?

https://github.com/fatih/vim-go/issues/2558

### What did you see instead?
gopls can't support any go file with `import "C"`

**Comment by yueqianzhang** [comment] 2019-11-04 13:52
same problem

**Comment by stamblerre** [comment] 2019-11-04 19:13
This is a known issue. Please follow along on https://github.com/golang/go/issues/32898 for updates.

**Comment by stamblerre** [comment] 2019-11-04 19:14
Duplicate of https://github.com/golang/go/issues/32898

**Closed by stamblerre** 2019-11-04 19:14 UTC
