### ISSUE TITLE
hope go generics in 1.18(or later) support return type inference

### ISSUE THREAD

**Issue by LeGamerDc** [golang/go#49520] opened 2021-11-11 09:21 UTC
from [generics proposal](https://go.googlesource.com/proposal/+/refs/heads/master/design/), if i did not misunderstand, go generics won't support return type inference like this

```
func empty[T any]() T {
     return T{}
}
```

i hope this feature could be added to go generics, and if not, i want to know why

**Comment by seankhliao** [comment] 2021-11-11 11:05
Duplicate of #35966

**Closed by seankhliao** 2021-11-11 11:05 UTC
