### ISSUE TITLE
playground: "timeout running program"

### ISSUE THREAD

**Issue by Deleplace** [golang/go#44546] opened 2021-02-23 15:11 UTC
### What version of Go are you using (`go version`)?

"The playground uses the latest stable release of Go. The current version is go1.14.14."

I wasn't able to confirm this because https://play.golang.org/p/Ztyu2FJaajl says "timeout running program"

### Does this issue reproduce with the latest release?

Unknown. The statement in the Go Playground (About) seems outdated, today (2021-02-23) go1.14.14 is not the latest stable release of Go.

### What did you do?

Click the button "Run"

### What did you expect to see?

The output "Hello, playground", or any other output of the current program.

### What did you see instead?

timeout running program
Go build failed.

![image](https://user-images.githubusercontent.com/13508141/108863681-c05fbd00-75f1-11eb-8982-b159b6d13698.png)

**Comment by bcmills** [comment] 2021-02-23 15:13
CC @golang/release

**Comment by bcmills** [comment] 2021-02-23 15:16
Duplicate of #44537

**Closed by bcmills** 2021-02-23 15:16 UTC
Labels: NeedsInvestigation, Soon
