### ISSUE TITLE
runtime or cmd/compile: runtime:cpu124 test crash or stall when GO_GCFLAGS=-N -l

### ISSUE THREAD

**Issue by mikioh** [golang/go#15859] opened 2016-05-27 07:32 UTC
See https://build.golang.org/log/31b6cd65ea1aaaff0fef5061ae74ecf354fc52e9 (linux-amd64-noopt)
But it happens, and is easy to repro on other platforms when compiling with "-N -l" options.
```
##### GOMAXPROCS=2 runtime -cpu=1,2,4
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x44363c]

goroutine 58526 [running]:
runtime.throw(0x66323d, 0x2a)
	/tmp/workdir/go/src/runtime/panic.go:566 +0x95 fp=0xc420171d28 sp=0xc420171d08
runtime.sigpanic()
	/tmp/workdir/go/src/runtime/sigpanic_unix.go:12 +0x2cc fp=0xc420171d80 sp=0xc420171d28
runtime.stackcacherelease(0x7ffb828abd18, 0x41dd00)
	/tmp/workdir/go/src/runtime/stack.go:283 +0x8c fp=0xc420171dd0 sp=0xc420171d80
runtime.stackfree(0xc42028f800, 0xc42028ffe0, 0x800)
	/tmp/workdir/go/src/runtime/stack.go:447 +0x15f fp=0xc420171e28 sp=0xc420171dd0
runtime.shrinkstack(0xc4201b9380)
	/tmp/workdir/go/src/runtime/stack.go:1081 +0x71 fp=0xc420171e50 sp=0xc420171e28
runtime.markrootFreeGStacks()
	/tmp/workdir/go/src/runtime/mgcmark.go:286 +0x81 fp=0xc420171e88 sp=0xc420171e50
runtime.markroot(0xc42001c728, 0xc400000002)
	/tmp/workdir/go/src/runtime/mgcmark.go:177 +0x1ee fp=0xc420171f00 sp=0xc420171e88
runtime.gcDrain(0xc42001c728, 0x6)
	/tmp/workdir/go/src/runtime/mgcmark.go:956 +0xab fp=0xc420171f38 sp=0xc420171f00
runtime.gcBgMarkWorker(0xc42001b500)
	/tmp/workdir/go/src/runtime/mgc.go:1451 +0x4ad fp=0xc420171fa8 sp=0xc420171f38
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:2060 +0x1 fp=0xc420171fb0 sp=0xc420171fa8
created by runtime.gcBgMarkStartWorkers
	/tmp/workdir/go/src/runtime/mgc.go:1342 +0x98
```
/cc @aclements

**Comment by mikioh** [comment] 2016-05-27 07:56
Yup, it just started from the landing of https://go-review.googlesource.com/#/c/23391/, as the dashboard tells.

**Comment by aclements** [comment] 2016-05-27 14:41
Duplicate of #15853, which I'm looking at now. (The subject of that one is somewhat incorrect; I'll fix that.)

**Closed by aclements** 2016-05-27 14:41 UTC
