### ISSUE TITLE
x/sync/singleflight: hangs after the first panic

### ISSUE THREAD

**Issue by kirk91** [golang/go#41133] opened 2020-08-30 03:23 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kirk/Library/Caches/go-build"
GOENV="/Users/kirk/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="*.byted.org,*.everphoto.cn,git.smartisan.com"
GONOSUMDB="*.byted.org,*.everphoto.cn,git.smartisan.com"
GOOS="darwin"
GOPATH="/Users/kirk/go"
GOPRIVATE="*.byted.org,*.everphoto.cn,git.smartisan.com"
GOPROXY="https://go-mod-proxy.byted.org,https://goproxy.cn,https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3x/blq4wl4x6q512nmyr651qt_w0000gp/T/go-build088646219=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I use singleflight to do something like creating a singleton client, all subsequent calls hang after the first panic.

Here is the code:
```golang
package main

import (
	"flag"
	"fmt"
	"log"
	"net"
	"net/http"
	_ "net/http/pprof"

	"golang.org/x/sync/singleflight"
)

var (
	port = flag.Int("port", 8000, "listening port")
)

func main() {
	flag.Parse()
	addr := fmt.Sprintf("127.0.0.1:%d", *port)
	lis, err := net.Listen("tcp", addr)
	if err != nil {
		panic(err)
	}

	http.HandleFunc("/ping", handlePing)
	log.Println("Server is listening on:", addr)
	http.Serve(lis, nil)
}

var doSthGroup singleflight.Group

func handlePing(w http.ResponseWriter, r *http.Request) {
	doSthGroup.Do("", func() (interface{}, error) {
		// simulating panic
		panic("invalid memory address or nil pointer dereference")
	})

	w.WriteHeader(http.StatusOK)
	fmt.Fprintf(w, "pong")
}
```

Using `curl` do tests after starting the above program, all requests are timeout expect the first.

```shell
$ # timeout is one second
$ for (( i=0; i<20; i++)); do curl -m 1 http://localhost:8000/ping; done
curl: (52) Empty reply from server
curl: (28) Operation timed out after 1000 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1000 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1002 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1001 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1000 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1003 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1003 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1000 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1002 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1000 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1002 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1000 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1001 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1000 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1000 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1000 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1003 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1000 milliseconds with 0 bytes received
curl: (28) Operation timed out after 1001 milliseconds with 0 bytes received
```

And cloud sees there are 19 goroutines get stuck in `singleflight.(*Group).Do` through goroutine stack traces

```shell
$  curl "http://localhost:8000/debug/pprof/goroutine?debug=1"
goroutine profile: total 23
19 @ 0x10380a0 0x1048a40 0x1048a2b 0x1048692 0x1081474 0x1352aea 0x13536c5 0x12c3b04 0x12c5945 0x12c6e93 0x12c290c 0x1067431
#       0x1048691       sync.runtime_Semacquire+0x41                    /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/sema.go:56
#       0x1081473       sync.(*WaitGroup).Wait+0x63                     /usr/local/Cellar/go/1.14.2_1/libexec/src/sync/waitgroup.go:130
#       0x1352ae9       golang.org/x/sync/singleflight.(*Group).Do+0xa9 /Users/kirk/go/src/golang.org/x/sync/singleflight/singleflight.go:59
#       0x13536c4       main.handlePing+0x44                            /Users/kirk/sg_hang.go:34
#       0x12c3b03       net/http.HandlerFunc.ServeHTTP+0x43             /usr/local/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:2012
#       0x12c5944       net/http.(*ServeMux).ServeHTTP+0x1a4            /usr/local/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:2387
#       0x12c6e92       net/http.serverHandler.ServeHTTP+0xa2           /usr/local/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:2807
#       0x12c290b       net/http.(*conn).serve+0x86b                    /usr/local/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:1895
```

### What did you expect to see?

All requests fail immediately

### What did you see instead?

All requests are timeout expect the first

**Comment by dmitshur** [comment] 2020-09-01 00:47
Thanks for the report. It looks like it might be a duplicate of #33519. Is that your understanding too?

**Comment by kirk91** [comment] 2020-09-01 03:18
@dmitshur It should be, I am sorry missing it when raising the issue

**Comment by dmitshur** [comment] 2020-09-04 19:17
Thanks for confirming—that is quite okay. I'll close this in favor of that issue.

**Closed by dmitshur** 2020-09-04 19:17 UTC
Labels: NeedsInvestigation, WaitingForInfo
