### ISSUE TITLE
URL Query Delete not working

### ISSUE THREAD

**Issue by PumpkinSeed** [golang/go#18344] opened 2016-12-16 11:05 UTC
### What version of Go are you using (`go version`)?
go1.7.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
Fedora amd64

### What did you do?
I try to delete a param from url Query using the `r.URL.Query().Del("test")`

### What did you expect to see?
After when I print out, or want to use the `r.URL.Query()`, it's not contain the "test" parameter.

### What did you see instead?
It's still contain the "test" parameter.

I think the problem, but I am not sure there is the code, where the `Values` isn't a pointer ot there isn't return value, so it's just delete it on function scope. 

```
func (v Values) Del(key string) {
  delete(v, key)
}
```

**Comment by odeke-em** [comment] 2016-12-16 11:37
@PumpkinSeed invoking r.URL.Query() creates a new url.Values each time, that isn't the same from your last invocation. The problem is that you are not reusing the value that you are deleting from.
Here is something to show you that on their own values.Del actually does what it advertises
https://play.golang.org/p/X_hyS78LmY

The https://golang.org/pkg/net/url/#URL.Query docs say that it parses the raw query and returns the corresponding values, and doesn't make a promise about re-using the exact same values on every invocation
<img width="681" alt="screen shot 2016-12-16 at 3 31 34 am" src="https://cloud.githubusercontent.com/assets/4898263/21261445/4f0800bc-c340-11e6-98c5-7e029035ac3c.png">


Please retain a reference from the first invocation of r.URL.Query() and then use that same variable
and you'll get the intended behavior.

Closing this issue, working as intended, unless anyone thinks there is more we can do.

**Closed by odeke-em** 2016-12-16 11:37 UTC

**Comment by PumpkinSeed** [comment] 2016-12-29 08:49
Oh, ye I got it, thank you.
