### ISSUE TITLE
x/pkgsite: consistent slash to search

### ISSUE THREAD

**Issue by jakesyl** [golang/go#45268] opened 2021-03-28 04:01 UTC
Currently, slash to search doesn't work on the main page

What did you do?

I went to the main [page](http://go.dev/) and typed slash to search

What did you expect to see?

I expected a search prompt like on any other page, for example:

![netutils · pkg go dev](https://user-images.githubusercontent.com/6392429/112742102-68ea9f00-8f59-11eb-8ea0-4b9e82bbd6c0.gif)

What did you see instead?

No slash to search on the home page

![go dev](https://user-images.githubusercontent.com/6392429/112742108-7142da00-8f59-11eb-8f8d-941985b292df.gif)

**Comment by rsc** [comment] 2021-03-31 17:59
/cc @julieqiu 

This doesn't need to be in the proposal process. The website team can figure it out.

**Comment by julieqiu** [comment] 2021-05-07 16:25
Closing this as a duplicate of #42704.

**Closed by julieqiu** 2021-05-07 16:25 UTC
Labels: NeedsInvestigation, pkgsite
