### ISSUE TITLE
cmd/doc: -all flag misses exported variables of unexported types

### ISSUE THREAD

**Issue by dsnet** [golang/go#31067] opened 2019-03-27 01:29 UTC
Using `go1.12`

Consider the following snippet:
```go
package foo
var X x
type x struct{}
```

Invoking `go doc -all` prints:
```
package foo // import "."

```

Notice how `X` is missing? It should be shown. The problem is that the logic probably files the value under the `x` type, but since `x` is not shown, it gets swallowed.

**Comment by agnivade** [comment] 2019-03-27 03:30
Does `X` show up in `godoc` under ?m=all ?

**Comment by cespare** [comment] 2019-05-22 19:28
I think this is a reasonable issue regardless of the answer to @agnivade's question.

**Comment by agnivade** [comment] 2019-11-11 18:46
Looked into it. The difference lies in the code paths between `(*Package).packageDoc` and `(*Package).allDoc`. You will notice that it correctly gives the output if you give `go doc`, but fails to show the variable on `go doc -all`.

On an unrelated note, I noticed that 1.13 has a regression where the `-all` flag does not even print the package clause.

```
$cat kk.go 
package foo
var X x
type x struct{}

19:57:30-agniva-~/play/go/src/playtest$go doc -all

19:57:32-agniva-~/play/go/src/playtest$
```

But simply `go doc` does show the `var X x`.

```
$go doc 


package foo // import "playtest"

var X x
```

Offtopic: https://github.com/golang/go/commit/f736de04aa52d4889760ecfe4380da01aaf4758f introduced the regression. (@robpike). This happens because now the package clause gets printed on the first write to `pkg.buf`. That means nothing gets printed, if no writes happen. Not a big deal, but I guess it is technically a bug because if a file contains just the package clause, nothing gets printed. Whereas it should. I have a fix for this. Will send it shortly.

**Closed** 2019-11-12 04:10 UTC
Labels: NeedsInvestigation
