### ISSUE TITLE
encoding/json: invalid use of ,string struct tag, trying to unmarshal "" into int

### ISSUE THREAD

**Issue by hhniao** [golang/go#26800] opened 2018-08-04 06:22 UTC
https://play.golang.org/p/TabRbDnegfc
https://github.com/golang/go/issues/7046

### What version of Go are you using (`go version`)?
go version go1.10 windows/amd64

**Comment by erikdubbelboer** [comment] 2018-08-31 16:01
Doesn't it make sense that this is an error? You're telling it to decode a string into an integer but then don't provide a valid integer in the string.

**Comment by hhniao** [comment] 2018-09-11 03:10
@erikdubbelboer 
usualy, we received data from web frontend. 
for example, 
them have a select html code like this: 
`
    <select name="demo">
        <option value="">please select</option>
        <option value="1">option1</option>
        <option value="2">option2</option>
    </select>
`
as you know, "" == 0 is true on javascript.
some time, them submit json data like this: { "demo": ""}
or them submit form data like this demo=""
ignore form data at the moment.
let we take a look json data. it is an empty string in the json data.

the go code: 
`
    type Data struct {
        Demo int `json:",string"`
    }
`
zero value of string is "". so, in my opinion, received a zero value of string convert to json. must not get a error.

**Comment by hhniao** [comment] 2018-09-11 03:37
because we cant change code of frontend .
we just try to re-write backend using golang from php.

**Comment by erikdubbelboer** [comment] 2018-09-11 06:26
I don't think you not being able to fix your frontend means that the Go JSON parser should make exceptions for invalid JSON.

**Comment by hhniao** [comment] 2018-09-11 06:41
no, no, no. 
for JSON.  it is valid.
    {
        "demo": ""
    }
    {
        "demo": "0"
    }

and i think `json:",string"`. it is must able to parse a valid string. any string. empty also it is a string.

**Comment by erikdubbelboer** [comment] 2018-09-11 06:56
It's a valid string yes but not a valid number. What if it's `"a"` which is also a valid string, should it accept that as well? What should the value be then? `0`, or `10` or `...`?
I think it should produce an error with all strings that are not numbers, like it is now.

**Comment by hhniao** [comment] 2018-09-11 07:04
hmm, you are right. thought php can be parse empty string. but it is not standard or valid. for strict of standard, we must write "0" instead "".
thanks.

**Comment by hhniao** [comment] 2018-09-11 07:06
may i should close this issue?

**Comment by asiman161** [comment] 2019-03-26 20:40
I think that it should parse empty string as a default parameter (like nil)
If we got an empty string it means that it's default (default for string is ""). 
If we got a default string it means that we want to use default value for int, isn't it?

**Comment by bsbak** [comment] 2019-08-05 11:55
so?! Update i coming?! Working with not my api and cant improve it... plix add! or change `json:"field,string,omitempty"` to `json:"field,omitempty,string"` if field is empty just leave (,string tag didnt launched)...

**Comment by erikdubbelboer** [comment] 2019-08-05 14:12
@asiman161 then what if in Go I have a string but in my JSON I get `0` (not a string). Should it then also result in an empty string seeing as 0 is the default for numbers?

@bsbak I don't think the Go team will fix this as it's not a bug.
If you're working with a broken JSON API you should either ask them to fix their API, you should use [`json.RawMessage`](https://golang.org/pkg/encoding/json/#RawMessage) or you implement your own type that can be both a number and an empty string: https://play.golang.org/p/nWl2toE2RAE

**Comment by agnivade** [comment] 2019-10-22 07:18
The error message is there for a reason. Empty strings do not mean `0`. There are various ways you can fix this already mentioned above.
- Fix the frontend.
- Change the type to string, and then handle "" to 0 later in the code.
- Use a custom Unmarshaler.

Probably others that I can't think of now.

Closing as this is WAI.

/cc @mvdan if I missed something.

**Closed by agnivade** 2019-10-22 07:18 UTC
Labels: NeedsInvestigation
