### ISSUE TITLE
net/http: flaky TestTransportReuseConnection_Gzip_ContentLength

### ISSUE THREAD

**Issue by rsc** [golang/go#22212] opened 2017-10-11 15:00 UTC
trybot failure in a cmd/go CL. nothing i'm changing in cmd/go could cause this.
only happened in the race builder, so maybe scheduling-sensitive.

https://storage.googleapis.com/go-build-log/00c78809/linux-amd64-race_9ed057c7.log

```
--- FAIL: TestTransportReuseConnection_Gzip_ContentLength (0.19s)
	transport_test.go:3411: didn't reuse connection
FAIL
FAIL	net/http	7.526s
2017/10/11 05:02:11 Failed: exit status 1
```

**Comment by bradfitz** [comment] 2017-11-27 21:36
Unfortunately I've been unable to reproduce this (on linux-amd64 or linux-amd64-race), even with high `-count` values and various `-cpu`.

/cc @tombergan

**Comment by bradfitz** [comment] 2018-05-29 20:11
I just spent some time on this again and still can't reproduce. I also looked at the git history for clues, but nothing.

Closing for now until we see it again or have more clues.

**Closed by bradfitz** 2018-05-29 20:11 UTC
Labels: NeedsFix, Testing
