### ISSUE TITLE
x/text: gotext not compatible with Go-1.20.1

### ISSUE THREAD

**Issue by croessner** [golang/go#58751] opened 2023-02-27 09:24 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.20.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, the problem started by upgrading 1.19.x to 1.20.1

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/croessner/Library/Caches/go-build"
GOENV="/Users/croessner/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/croessner/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/croessner/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/croessner/GoLandProjects/authserv/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1p/ps03vl3150d7nsm9ynkxkbmc0000gn/T/go-build3048905333=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

After upgrading Go, I also did:

1. go get -u golang.org/x/text/cmd/gotext
2. go mod tidy
3. go mod vendor
4. Change into subfolder server, where the main go code lives.
5. Call go generate

### What did you expect to see?

As I added new strings, I expected to see that texts for German and French would be missing and that the catalog.go file should have been updated.

### What did you see instead?

<pre>
/usr/local/go/src/runtime/debuglog.go:296:20: StringData not declared by package unsafe
/usr/local/go/src/runtime/heapdump.go:159:37: StringData not declared by package unsafe
/usr/local/go/src/runtime/heapdump.go:202:32: StringData not declared by package unsafe
/usr/local/go/src/runtime/heapdump.go:204:32: StringData not declared by package unsafe
/usr/local/go/src/runtime/proc.go:658:16: String not declared by package unsafe
/usr/local/go/src/runtime/runtime.go:115:33: StringData not declared by package unsafe
/usr/local/go/src/runtime/string.go:105:17: String not declared by package unsafe
/usr/local/go/src/runtime/string.go:115:16: String not declared by package unsafe
/usr/local/go/src/runtime/string.go:121:39: StringData not declared by package unsafe
/usr/local/go/src/runtime/string.go:163:16: String not declared by package unsafe
/usr/local/go/src/runtime/string.go:268:16: String not declared by package unsafe
/usr/local/go/src/runtime/type.go:465:16: String not declared by package unsafe
/usr/local/go/src/runtime/type.go:474:16: String not declared by package unsafe
/usr/local/go/src/internal/reflectlite/type.go:346:16: String not declared by package unsafe
/usr/local/go/src/internal/reflectlite/type.go:355:16: String not declared by package unsafe
/usr/local/go/src/strings/builder.go:48:16: String not declared by package unsafe
/usr/local/go/src/strings/builder.go:48:30: SliceData not declared by package unsafe
/usr/local/go/src/strings/clone.go:27:16: String not declared by package unsafe
/usr/local/go/src/net/netip/netip.go:343:28: cannot convert slice (variable of type []byte) to [4]byte
/usr/local/go/src/net/netip/netip.go:345:30: cannot convert slice (variable of type []byte) to [16]byte
/usr/local/go/src/net/netip/netip.go:1013:27: cannot convert b (variable of type []byte) to [4]byte
/usr/local/go/src/net/netip/netip.go:1016:29: cannot convert b (variable of type []byte) to [16]byte
/usr/local/go/src/net/netip/netip.go:1019:29: cannot convert b[:16] (value of type []byte) to [16]byte
/usr/local/go/src/reflect/type.go:532:16: String not declared by package unsafe
/usr/local/go/src/reflect/type.go:541:16: String not declared by package unsafe
/usr/local/go/src/crypto/x509/internal/macos/corefoundation.go:65:29: SliceData not declared by package unsafe
/usr/local/go/src/crypto/x509/internal/macos/corefoundation.go:76:29: StringData not declared by package unsafe
/usr/local/go/src/os/file.go:246:27: StringData not declared by package unsafe
gotext: extract failed: : : couldn't load packages due to errors: reflect, os, internal/reflectlite and 4 more
hydra.go:3: running "gotext": exit status 1
</pre>

It seems that gotext needs updates for Go 1.20.x

**Comment by seankhliao** [comment] 2023-02-27 10:15
Duplicate of #58737

**Closed by seankhliao** 2023-02-27 10:15 UTC

**Comment by croessner** [comment] 2023-03-01 12:59
I followed the ticket #58737 , but the problem is _not_ solved!

I have updated all modules and the problem persists. Please re-open this issue.

**Comment by seankhliao** [comment] 2023-03-01 13:41
Please include a self contained reproducer for what you did, with specific versions ("updated" is also unclear).
Your original report says you ran "go generate" which is not very useful to us without your code.

**Comment by croessner** [comment] 2023-03-01 13:59
You can find my code at https://gitlab.roessner-net.de/croessner/authserv/-/tree/features

I have one file, which is in [server/hydra.go](https://gitlab.roessner-net.de/croessner/authserv/-/blob/features/server/hydra.go) that uses translations. There is also the go generate line:

//go:generate gotext -srclang=en update -out=catalog.go -lang=en,de,fr

When I run "go generate" in this folder, the errors appear as shown in this issue.

You can see the go.mod and go.sum and vendor files. It should have all latest versions. Does this help a little bit? :-)

**Comment by nikhilbhandari123** [comment] 2023-04-16 15:03
BTW, this is the example code I am using:
https://github.com/nikhilbhandari123/plugin-example

README has the steps to see the problem

**Comment by jeffphp** [comment] 2023-09-05 17:11
@croessner did you find any workaround. I'm using Go-1.21 (from 1.19) and I have the same exact problem.
