### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by sorenmogensen** [golang/go#54391] opened 2022-08-11 09:50 UTC
### What is the URL of the page with the issue?
 https://go.dev/tour/flowcontrol/10
 
 
### What is your user agent?
Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0

 
 
 
### Screenshot
 

![wrong_day](https://user-images.githubusercontent.com/18233054/184107548-a380946c-c598-44a1-b9de-3ad3555570a6.png)

 
 
### What did you do?
 

Ran the example - with added print statements to view the "today" variable 
 
 
### What did you expect to see?
As today is Thursday, I expected the script to say that Saturday is two days away. It didn't.
 
 
### What did you see instead?
The go.dev server seems to think today is Tuesday. That's going to be confusing to people trying to understand the script.

**Comment by seankhliao** [comment] 2022-08-11 10:30
time on the playground is fixed, it's described below in the limitations section

Closing as working as intended

**Closed by seankhliao** 2022-08-11 10:30 UTC
Labels: website
