### ISSUE TITLE
cmd/go: go install / go.mod / go:embed / build tags don't play well together.

### ISSUE THREAD

**Issue by james-lawrence** [golang/go#47109] opened 2021-07-09 15:21 UTC
have a program where I have three files:

workspace_16.go which contains // +build go1.16 and a go:embed
workspace_15.go // +build !go1.16
workspace.go

and a go.mod with 
go 1.14

```
cmd/bw/workspace_16.go:64:3: go:embed requires go1.16 or later (-lang was set to go1.14; check go.mod)
```

expect it to build properly.

**Comment by jayconrod** [comment] 2021-07-09 15:49
The `go` directive in `go.mod` is the problem here. It needs to be `go 1.16` or higher.

Closing since this seems like it's working as intended. Your `+build` tags look like they should work.

But #30791 is related. The `go` directive is not all that well-documented or understood.

**Closed by jayconrod** 2021-07-09 15:49 UTC

**Comment by james-lawrence** [comment] 2021-07-10 19:39
@jayconrod I believe you misunderstood the problem. it doesn't build, the source code with the build tags should build properly for both go 1.14, 1.15, and 1.16. 1.16 isn't the minimum version.

however it doesn't build properly.

**Comment by james-lawrence** [comment] 2021-07-10 20:14
@jayconrod nm then, I stand corrected. the error in CI was from an import that didn't get autoremoved during save. *sigh*
