### ISSUE TITLE
cmd/go: return current GOBIN when running "go env GOBIN"

### ISSUE THREAD

**Issue by leitzler** [golang/go#34522] opened 2019-09-25 10:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build575410569=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Run `go env GOBIN`

### What did you expect to see?
The current evaluated path to GOBIN.

It has bitten me a few times where I install tools with `go install` and then want to run them, without relying on having GOBIN in my path. I can't really see any reason why `go env GOBIN` shouldn't return the current one.

Also see @rsc comment in https://github.com/golang/go/issues/23439#issuecomment-433118300

### What did you see instead?
An empty line.

**Comment by leitzler** [comment] 2019-09-25 10:24
@gopherbot, please add label GoCommand

**Comment by mvdan** [comment] 2019-09-25 10:26
There's also `go list -f {{.Target}} path/to/main`, but that requires knowing the full package path (and resolving it!), and doesn't return the directory. The directory can be useful for many things, such as adding it to `PATH` in some environments.

**Comment by mvdan** [comment] 2019-09-25 11:53
Also note that some env vars like `go env GOPATH` and `go env GOCACHE` correctly return the default values when the user hasn't set one up. I'm not sure if there are any other flags that are inconsistent like `GOBIN`; after a quick scan I could only find `GOTMPDIR`, which might not have a static default value.

**Comment by bcmills** [comment] 2019-09-25 14:46
Duplicate of #23439

**Closed by bcmills** 2019-09-25 14:46 UTC
Labels: GoCommand, NeedsDecision
