### ISSUE TITLE
all: multiple packages fail go test when not in short mode

### ISSUE THREAD

**Issue by alexd765** [golang/go#24464] opened 2018-03-20 20:43 UTC
### What version of Go are you using (`go version`)?
go version devel +be371edd67 Tue Mar 20 19:38:06 2018 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
Test all packages via all.bash (in short mode) and then via go test ./... (not in short mode)

`~/gotip/src$ ./all.bash && go test ./...`

Inspired by #24436

### What did you expect to see?
All tests pass (in short mode)
All tests pass (not in short mode)

### What did you see instead?
All tests pass (in short mode)
Multiple packages fail go test (not in short mode)

FAIL	cmd/compile/internal/ssa (discussed here)
FAIL	cmd/doc (fixed in [cl 101836](https://golang.org/cl/101836))
FAIL	cmd/go (#24436)
FAIL	cmd/gofmt (#24472)
FAIL	go/types (fixed in [cl 101815](https://golang.org/cl/101815))
FAIL	net

Edit: i have added links to the fixes and other discussions so far

**Comment by andybons** [comment] 2018-03-20 21:53
@rsc

**Comment by ALTree** [comment] 2018-03-21 11:11
`go/types` failure fixed in 041c5d83486fce4a1c8b549a3c6f9c1951b0aea8.

**Comment by mvdan** [comment] 2018-03-21 12:27
The failure in `cmd/doc` is because it may fail depending on your GOPATH. For example:

```
$ go test
2018/03/21 12:26:36 no buildable Go source files in /home/mvdan/go/land/src/github.com/gopherjs/gopherjs/compiler/natives/src/crypto/rand
exit status 1
FAIL    cmd/doc 0.119s
[mvdan@carbon:5] [1] [/home/mvdan/tip/src/cmd/doc]
$ GOPATH= go test
PASS
ok      cmd/doc 1.857s
```

The tests should be made more robust. Will give it a go, but there are many ways to fix this.

**Comment by ALTree** [comment] 2018-03-21 13:05
The `cmd/gofmt` failure is caused by `gofmt` not being idempotent on certain programs. I opened #24472 about this, with a small reproducer.

**Comment by randall77** [comment] 2018-03-21 16:51
I can't get `cmd/compile/internal/ssa` to fail.
```
$ git checkout be371edd677abe6de310c9ffc225b9e8b052d2b8
$ ./make.bash
Building Go cmd/dist using /Users/khr/go1.4.
Building Go toolchain1 using /Users/khr/go1.4.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for darwin/amd64.
---
Installed Go for darwin/amd64 in /Users/khr/sandbox/readonly
Installed commands in /Users/khr/sandbox/readonly/bin
$ ../bin/go test cmd/compile/internal/ssa/...
ok  	cmd/compile/internal/ssa	71.866s
```
(same thing on linux)

**Comment by ALTree** [comment] 2018-03-21 16:55
I can (linux/amd64), here's the log:

```
--- FAIL: TestNexting (7.94s)
    --- FAIL: TestNexting/gdb-dbg-hist (2.37s)
    	debug_test.go:234: step/next histories differ, diff=
    		--- testdata/hist.gdb-dbg.nexts	2018-03-19 11:37:08.131407088 +0100
    		+++ /tmp/debug_test231459976/test-hist.gdb-dbg.nexts	2018-03-21 17:54:58.587602381 +0100
    		@@ -9,7 +9,7 @@
    		 61:		sink = dx + dy            //gdb-opt=(dx,dy)
    		 63:		hist := make([]int, 7)                                //gdb-opt=(dx/O,dy/O) // TODO sink is missing if this code is in 'test' instead of 'main'
    		 64:		var reader io.Reader = strings.NewReader(cannedInput) //gdb-dbg=(hist/A) // TODO cannedInput/A is missing if this code is in 'test' instead of 'main'
    		-hist =  []int = {0, 0, 0, 0, 0, 0, 0}
    		+hist = {array = <A>, len = 7, cap = 7}
    		 65:		if len(os.Args) > 1 {
    		 73:		scanner := bufio.NewScanner(reader)
    		 74:		for scanner.Scan() { //gdb-opt=(scanner/A)
    --- FAIL: TestNexting/gdb-opt-hist (0.95s)
    	debug_test.go:234: step/next histories differ, diff=
    		--- testdata/hist.gdb-opt.nexts	2018-03-19 11:37:08.139407145 +0100
    		+++ /tmp/debug_test577668668/test-hist.gdb-opt.nexts	2018-03-21 17:55:03.655623768 +0100
    		@@ -25,7 +25,7 @@
    		 76:			i, err := strconv.ParseInt(s, 10, 64)
    		 77:			if err != nil { //gdb-dbg=(i) //gdb-opt=(err,hist,i)
    		 err = {tab = 0x0, data = 0x0}
    		-hist =  []int = {0, 0, 0, 0, 0, 0, 0}
    		+hist = {array = 0xc00003be98, len = 7, cap = 7}
    		 i = 1
    		 81:			hist = ensure(int(i), hist)
    		 82:			hist[int(i)]++
    		@@ -35,7 +35,7 @@
    		 76:			i, err := strconv.ParseInt(s, 10, 64)
    		 77:			if err != nil { //gdb-dbg=(i) //gdb-opt=(err,hist,i)
    		 err = {tab = 0x0, data = 0x0}
    		-hist =  []int = {0, 1, 0, 0, 0, 0, 0}
    		+hist = {array = 0xc00003be98, len = 7, cap = 7}
    		 i = 1
    		 81:			hist = ensure(int(i), hist)
    		 82:			hist[int(i)]++
    		@@ -45,7 +45,7 @@
    		 76:			i, err := strconv.ParseInt(s, 10, 64)
    		 77:			if err != nil { //gdb-dbg=(i) //gdb-opt=(err,hist,i)
    		 err = {tab = 0x0, data = 0x0}
    		-hist =  []int = {0, 2, 0, 0, 0, 0, 0}
    		+hist = {array = 0xc00003be98, len = 7, cap = 7}
    		 i = 1
    		 81:			hist = ensure(int(i), hist)
    		 82:			hist[int(i)]++
    		@@ -55,7 +55,7 @@
    		 76:			i, err := strconv.ParseInt(s, 10, 64)
    		 77:			if err != nil { //gdb-dbg=(i) //gdb-opt=(err,hist,i)
    		 err = {tab = 0x0, data = 0x0}
    		-hist =  []int = {0, 3, 0, 0, 0, 0, 0}
    		+hist = {array = 0xc00003be98, len = 7, cap = 7}
    		 i = 2
    		 81:			hist = ensure(int(i), hist)
    		 82:			hist[int(i)]++
    		@@ -65,7 +65,7 @@
    		 76:			i, err := strconv.ParseInt(s, 10, 64)
    		 77:			if err != nil { //gdb-dbg=(i) //gdb-opt=(err,hist,i)
    		 err = {tab = 0x0, data = 0x0}
    		-hist =  []int = {0, 3, 1, 0, 0, 0, 0}
    		+hist = {array = 0xc00003be98, len = 7, cap = 7}
    		 i = 2
    		 81:			hist = ensure(int(i), hist)
    		 82:			hist[int(i)]++
    		@@ -75,7 +75,7 @@
    		 76:			i, err := strconv.ParseInt(s, 10, 64)
    		 77:			if err != nil { //gdb-dbg=(i) //gdb-opt=(err,hist,i)
    		 err = {tab = 0x0, data = 0x0}
    		-hist =  []int = {0, 3, 2, 0, 0, 0, 0}
    		+hist = {array = 0xc00003be98, len = 7, cap = 7}
    		 i = 2
    		 81:			hist = ensure(int(i), hist)
    		 82:			hist[int(i)]++
    		@@ -85,7 +85,7 @@
    		 76:			i, err := strconv.ParseInt(s, 10, 64)
    		 77:			if err != nil { //gdb-dbg=(i) //gdb-opt=(err,hist,i)
    		 err = {tab = 0x0, data = 0x0}
    		-hist =  []int = {0, 3, 3, 0, 0, 0, 0}
    		+hist = {array = 0xc00003be98, len = 7, cap = 7}
    		 i = 4
    		 81:			hist = ensure(int(i), hist)
    		 82:			hist[int(i)]++
    		@@ -95,7 +95,7 @@
    		 76:			i, err := strconv.ParseInt(s, 10, 64)
    		 77:			if err != nil { //gdb-dbg=(i) //gdb-opt=(err,hist,i)
    		 err = {tab = 0x0, data = 0x0}
    		-hist =  []int = {0, 3, 3, 0, 1, 0, 0}
    		+hist = {array = 0xc00003be98, len = 7, cap = 7}
    		 i = 4
    		 81:			hist = ensure(int(i), hist)
    		 82:			hist[int(i)]++
    		@@ -105,7 +105,7 @@
    		 76:			i, err := strconv.ParseInt(s, 10, 64)
    		 77:			if err != nil { //gdb-dbg=(i) //gdb-opt=(err,hist,i)
    		 err = {tab = 0x0, data = 0x0}
    		-hist =  []int = {0, 3, 3, 0, 2, 0, 0}
    		+hist = {array = 0xc00003be98, len = 7, cap = 7}
    		 i = 5
    		 81:			hist = ensure(int(i), hist)
    		 82:			hist[int(i)]++
FAIL
exit status 1
FAIL	cmd/compile/internal/ssa	93.549s
```

**Comment by randall77** [comment] 2018-03-21 17:44
Hmm, might be a gdb version issue.  I'm running 7.9.
@dr2chase

**Comment by mvdan** [comment] 2018-03-21 17:45
I get the same failure, gdb version 8.1.

**Comment by ALTree** [comment] 2018-03-21 17:47
My system comes with gdb 7.12

**Comment by dr2chase** [comment] 2018-03-21 18:35
Is that gdb version or presence/absence of Python scripts?
I'll try to figure this out, I could at least make it more picky about gdb version if that is the case.

**Comment by dr2chase** [comment] 2018-03-21 19:59
I have gdb versions 7.9 and 8.0.1, seems to work for me.
I will try to figure out how to install a version that triggers the wrong printing (which I have clearly seen in the past, because of the "/A" following hist).

I am not super-fluent in Python, but this from runtime-gdb.py seems semi-relevant:
```
class SliceTypePrinter:
	"Pretty print slices."

	pattern = re.compile(r'^struct \[\]')

	def __init__(self, val):
		self.val = val

	def display_hint(self):
		return 'array'

	def to_string(self):
		return str(self.val.type)[6:]  # skip 'struct '

	def children(self):
		sval = SliceValue(self.val)
		if sval.len > sval.cap:
			return
		for idx, item in enumerate(sval):
			yield ('[{0}]'.format(idx), item)
```

**Comment by alexd765** [comment] 2018-03-21 22:02
i have added links to the fixes and other discussions so far to the main post

**Comment by alexd765** [comment] 2018-03-21 22:06
cmd/compile/internal/ssa fails for me with gdb 8.0.1, so the gdb version doesn't seem to be the issue.

**Comment by josharian** [comment] 2018-03-22 22:30
The underlying problem here is #12508

**Comment by dr2chase** [comment] 2018-03-23 15:52
@alexd765 the SliceTypePrinter code is really old, so that's probably the same.
My Python versions are 2.7.14 and 2.7.13.  Yours?

**Comment by mvdan** [comment] 2018-03-23 16:28
@dr2chase I can reproduce it and I only have versions 2.7.14 and 3.6.4 installed. I'm running Arch Linux, so I would assume that any somewhat recent Linux system should have this test failure.

I tried playing with that runtime-gdb.py file, but not even emptying the file changes the behaviour of the test.

**Comment by alexd765** [comment] 2018-03-23 18:30
I am on Ubuntu 17.10 with python 2.7.14

**Comment by dr2chase** [comment] 2018-03-23 18:38
Except that I am failing to reproduce the bug on Linux....
I am learning a little Python.

**Comment by alexd765** [comment] 2018-03-23 19:29
@dr2chase I also started to look into this a little bit:

First observation: if i force the test to use delve with `~/gotip/src/cmd/compile/internal/ssa$ go test -d -v` it passes.

Then i saw that there is an option to regenerate the testdata with `~/gotip/src/cmd/compile/internal/ssa$ go test -u`. It changed some things in 2 testdata files and after that the tests are passing.

I can send the changes as a cl if that helps

**Comment by dr2chase** [comment] 2018-03-23 19:44
Mucking with the testdata files w/o understanding why we have this difference isn't going to help -- you'll break it for me, for example.

Also, I have several CLs stacked up that will mess with the testdata in a big way, alleged positive.  (If you actually look at what's recorded there, there's plenty of room for improvement.)

**Comment by dr2chase** [comment] 2018-03-23 21:19
Perhaps it is not autoloading runtime-gdb.py?
Are there any warnings at the beginning about auto-load and safe-path?

I definitely need to modify the test to be better about this.

**Comment by mvdan** [comment] 2018-03-27 15:12
@dr2chase all the `TestNexting` subtests are passing on my machine, so we can fairly safely assume that it's fixed for @alexd765 too :)

Out of the initial 5 issues, 3 have been fixed and 2 have been split into separate issues. So it seems like there's nothing else to do here. Thanks again @alexd765 for reporting them.

**Closed by mvdan** 2018-03-27 15:12 UTC
Labels: NeedsInvestigation, Testing

**Comment by dr2chase** [comment] 2018-03-27 15:37
Thanks for verifying. I wasn't 100% sure, but I was hopeful.

**Comment by alexd765** [comment] 2018-03-27 17:58
yeah i can confirm that `cmd/compile/internal/ssa` is fixed for me as well
