### ISSUE TITLE
cmd/compile: the "go tool compile -S -live=2 *.go" command failed

### ISSUE THREAD

**Issue by zhangfannie** [golang/go#39251] opened 2020-05-26 08:44 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +bcda68447b Mon May 25 21:01:14 2020 +0000 linux/arm64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/fanzha02/.cache/go-build"
GOENV="/home/fanzha02/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/fanzha02/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/fanzha02/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/fanzha02/work/go_project/gomain"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/fanzha02/work/go_project/gomain/pkg/tool/linux_arm64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build178004910=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

1. cat hello.go
```
package main
import "fmt"
func main() {
        fmt.Println("hello")
}
```
2. go tool compiler -S -live=2 hello.go

### What did you expect to see?

pass

### What did you see instead?
the command reports the error.

**Comment by zhangfannie** [comment] 2020-05-26 08:46
The command reports the following error and stack trace.
```
live=panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
cmd/compile/internal/gc.(*Liveness).printDebug(0x4000279600)
        /home/fanzha02/work/go_project/gomain/src/cmd/compile/internal/gc/plive.go:1450 +0xfec
cmd/compile/internal/gc.liveness(0x40002074a0, 0x4000278840, 0x4000478080, 0x0)
        /home/fanzha02/work/go_project/gomain/src/cmd/compile/internal/gc/plive.go:1593 +0x4ac
cmd/compile/internal/gc.genssa(0x4000278840, 0x4000478080)
        /home/fanzha02/work/go_project/gomain/src/cmd/compile/internal/gc/ssa.go:5939 +0x70
cmd/compile/internal/gc.compileSSA(0x40002782c0, 0x0)
        /home/fanzha02/work/go_project/gomain/src/cmd/compile/internal/gc/pgen.go:327 +0x3a0
cmd/compile/internal/gc.compile(0x40002782c0)
        /home/fanzha02/work/go_project/gomain/src/cmd/compile/internal/gc/pgen.go:275 +0x350
cmd/compile/internal/gc.funccompile(0x40002782c0)
        /home/fanzha02/work/go_project/gomain/src/cmd/compile/internal/gc/pgen.go:220 +0xc8
cmd/compile/internal/gc.Main(0x796a00)
        /home/fanzha02/work/go_project/gomain/src/cmd/compile/internal/gc/main.go:747 +0x36cc
main.main()
        /home/fanzha02/work/go_project/gomain/src/cmd/compile/main.go:52 +0xb8
```

**Comment by zhangfannie** [comment] 2020-05-26 08:53
The line 1450 of plive.go, the code is `regLive := lv.regMaps[pcdata.regMapIndex]`, because the len(lv.regMaps) is equal to 0， which leads to an error. 
But I found a comment  "Only when! Go115ReduceLiveness" next to this line of code, I don't know if there are any other conditions for using "-live = 2". Thank you.

**Comment by ALTree** [comment] 2020-05-26 10:01
This is a tip regression: Go1.14.2 does not crash.

**Comment by marigonzes** [comment] 2020-05-26 10:35
Took a shot at bisecting this. Commit 9d812cf seems to be the culprit.

**Comment by ALTree** [comment] 2020-05-26 10:42
cc @aclements @cherrymui

**Comment by ianlancetaylor** [comment] 2020-05-26 19:20
CC @dr2chase

**Comment by ianlancetaylor** [comment] 2020-05-26 19:21
Marking as release blocker since it is regression that causes a compiler crash.

**Comment by ianlancetaylor** [comment] 2020-05-26 19:21
Marking okay-after-beta1 since it is an unusual set of options.

**Closed** 2020-05-28 14:44 UTC
Labels: NeedsInvestigation, okay-after-beta1, release-blocker
