### ISSUE TITLE
Go test breaks on flags in go 1.13

### ISSUE THREAD

**Issue by mat285** [golang/go#34078] opened 2019-09-04 15:06 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/michaelt/Library/Caches/go-build"
GOENV="/Users/michaelt/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/michaelt/workspace/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/k5/mznl8tb12q953v9qmgbhw40m0000gn/T/go-build311187106=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
Run `go test` from within a package with test files

### What did you expect to see?
Expected the tests to run just as in version 1.12

### What did you see instead?
```
➜  core git:(master) go test
flag provided but not defined: -test.timeout
Usage of /var/folders/k5/mznl8tb12q953v9qmgbhw40m0000gn/T/go-build162470207/b001/core.test:
  -acceptance
    	If we should run acceptance tests
  -integration
    	If we should run integration tests
  -unit
    	If we should run unit tests
exit status 2
FAIL	example/pkg/core	0.025s
```

**Comment by cespare** [comment] 2019-09-04 15:30
Duplicate of #31859.

**Closed by cespare** 2019-09-04 15:30 UTC
