### ISSUE TITLE
proposal: go get should trim `https://` from package arguments affected/package: cmd/go

### ISSUE THREAD

**Issue by donatj** [golang/go#52220] opened 2022-04-07 19:07 UTC
### Proposal

`go get` should strip leading `https://` off package arguments automatically. 

That is to say if I for instance execute

```shell
$ go get https://github.com/shurcooL/githubv4
```

it should be smart enough to negotiate `https://github.com/shurcooL/githubv4` to `github.com/shurcooL/githubv4`, perhaps with a message informing the user it has done so.

### Rationale

This happens to me all the time:

I find the package I want to use on GitHub. I see the name of the package in the address bar presented without the protocol portion of the address (e.g. `https://`)

<img width="437" alt="image" src="https://user-images.githubusercontent.com/133747/162276347-5e441386-4094-456f-a576-f7eb9e39fa54.png">

I hit ⌘-L and select the address, still no visible protocol. ⌘-C to copy

<img width="437" alt="image" src="https://user-images.githubusercontent.com/133747/162275513-defea604-4b9a-4e2b-a544-e543b1691089.png">

Then I open my terminal and type `go get ` and hit ⌘-C and enter

<img width="600" alt="image" src="https://user-images.githubusercontent.com/133747/162276455-ca9ca056-942d-4053-a0ef-7d42b4ba521f.png">

I receive

> go: malformed module path "https:/github.com/shurcooL/githubv4": invalid char ':'

### Other notes

I concede this isn't a Go issue but rather a a Chrome issue, hiding the protocol from the user, or a personal issue given that my brain can't seem to remember I'm not copying what I see selected.

That said, I also suspect I can't be the only person who encounters this on a regular basis. I suspect handling it more gracefully would make the `go get` command just a little more friendly.

**Comment by seankhliao** [comment] 2022-04-07 19:09
Duplicate of #12701

**Closed by seankhliao** 2022-04-07 19:09 UTC
Labels: Proposal
