### ISSUE TITLE
cmd/go: performance regression after F_FULLFSYNC fcntl change on Darwin

### ISSUE THREAD

**Issue by mark-rushakoff** [golang/go#27415] opened 2018-08-31 15:09 UTC
I'm seeing a reliable ~3x slowdown with `go test -race` on a particular set of tests doing a lot of concurrent operations in several goroutines. I haven't yet spent the time to reduce the test case or to identify the go commit introducing the regression.

Tried with go 1.11:
```
$ go version; go env
go version go1.11 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mr/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mr/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ct/bl4_z3g51ks8239_r2k07v_40000gn/T/go-build102870134=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

and go tip:
```
$ gotip version; gotip env
go version devel +7c96f9b527 Fri Aug 31 02:14:24 2018 +0000 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mr/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mr/go"
GOPROXY=""
GORACE=""
GOROOT="/Users/mr/gotip/src/github.com/golang/go"
GOTMPDIR=""
GOTOOLDIR="/Users/mr/gotip/src/github.com/golang/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ct/bl4_z3g51ks8239_r2k07v_40000gn/T/go-build924877100=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

To reproduce:

```
go get github.com/influxdata/platform
cd $GOPATH/src/github.com/influxdata/platform
git checkout origin/test/taskservice
dep ensure -v -vendor-only
go test -race -count=5 ./task
```

(That branch will likely get rebased onto master in the near future, so I've got a fork at https://github.com/mark-rushakoff/platform/commit/a8269bc81cd6d477da8ebcddae8f37cfae40d44f with the commit as it is today.)

I'm consistently seeing times like:
```
$ go test -race -count=5 ./task
ok  	github.com/influxdata/platform/task	8.513s
$ gotip test -race -count=5 ./task
ok  	github.com/influxdata/platform/task	25.863s
```

For a small test suite that doesn't exercise concurrency, the slowdown is negligible:

```
$ go test -race -count=5 ./task/options/
ok  	github.com/influxdata/platform/task/options	1.602s
$ gotip test -race -count=5 ./task/options/
ok  	github.com/influxdata/platform/task/options	1.655s
```

I might spend some time bisecting go to identify where the slowdown was introduced, or I might take a look at trace output, but I wanted to file this issue in case anyone else had time and interest to look at it before I do.

**Comment by ALTree** [comment] 2018-08-31 15:17
It's not clear what version `go` is in your terminal. `gotip` is tip, ok, and it's affected... what's `go`?

**Comment by mark-rushakoff** [comment] 2018-08-31 15:46
I'm seeing an even more drastic slowdown without using -race:

```
bash-3.2$ go test  -count=5 ./task
ok  	github.com/influxdata/platform/task	1.845s
bash-3.2$ gotip test  -count=5 ./task
ok  	github.com/influxdata/platform/task	19.957s
bash-3.2$ go test  -count=5 ./task
ok  	github.com/influxdata/platform/task	1.841s
bash-3.2$ gotip test  -count=5 ./task
ok  	github.com/influxdata/platform/task	20.574s
```

**Comment by ALTree** [comment] 2018-08-31 15:48
That seems... extreme. Are you sure `gotip` is not rebuilding stuff? Can you put the test in a Benchmark? That would get rid of issues like that.

**Comment by mark-rushakoff** [comment] 2018-08-31 16:30
Okay, I bisected to find be10ad762289943638efb279fc7e04c73b8d7cee (`internal/poll: use F_FULLFSYNC fcntl for FD.Fsync on OS X`) was the first "bad" commit. 

The test suite in question is exercising some concurrent operations backed by a coreos/bbolt database. The commit message details look like the commit was a necessary change:

>    As reported in #26650 and also cautioned on the man page
>    for fsync on OS X, fsync doesn't properly flush content
>    to permanent storage, and might cause corruption of data if
>    the OS crashes or if the drive loses power. Thus it is recommended
>    to use the F_FULLFSYNC fcntl, which flushes all buffered data to
>    permanent storage and is important for applications such as
>    databases that require a strict ordering of writes.

Maybe this is just a necessary regression for file correctness on Darwin?

Here's the tail of my bisect run, if that's useful information:

```
bash-3.2$ gotip version; gotip test -count=5 ./task; gotip test -count=5 -race ./task
go version devel +37ea182660 Wed Aug 22 21:38:27 2018 +0000 darwin/amd64
ok  	github.com/influxdata/platform/task	1.693s
ok  	github.com/influxdata/platform/task	8.448s
bash-3.2$ gotip version; gotip test -count=5 ./task; gotip test -count=5 -race ./task
go version devel +37ea182660 Wed Aug 22 21:38:27 2018 +0000 darwin/amd64
ok  	github.com/influxdata/platform/task	1.976s
ok  	github.com/influxdata/platform/task	8.973s
bash-3.2$ gotip version; gotip test -count=5 ./task; gotip test -count=5 -race ./task
go version devel +ca8ba0675a Wed Aug 22 22:47:21 2018 +0000 darwin/amd64
ok  	github.com/influxdata/platform/task	20.477s
ok  	github.com/influxdata/platform/task	26.229s
bash-3.2$ gotip version; gotip test -count=5 ./task; gotip test -count=5 -race ./task
go version devel +ca8ba0675a Wed Aug 22 22:47:21 2018 +0000 darwin/amd64
ok  	github.com/influxdata/platform/task	21.889s
ok  	github.com/influxdata/platform/task	27.399s
bash-3.2$ gotip version; gotip test -count=5 ./task; gotip test -count=5 -race ./task
go version devel +be10ad7622 Wed Aug 22 22:26:40 2018 +0000 darwin/amd64
ok  	github.com/influxdata/platform/task	21.406s
ok  	github.com/influxdata/platform/task	26.720s
bash-3.2$ gotip version; gotip test -count=5 ./task; gotip test -count=5 -race ./task
go version devel +be10ad7622 Wed Aug 22 22:26:40 2018 +0000 darwin/amd64
ok  	github.com/influxdata/platform/task	21.632s
ok  	github.com/influxdata/platform/task	26.340s
bash-3.2$ gotip version; gotip test -count=5 ./task; gotip test -count=5 -race ./task
go version devel +ccb70bd19c Wed Aug 22 22:11:24 2018 +0000 darwin/amd64
ok  	github.com/influxdata/platform/task	1.786s
ok  	github.com/influxdata/platform/task	8.437s
bash-3.2$ gotip version; gotip test -count=5 ./task; gotip test -count=5 -race ./task
go version devel +ccb70bd19c Wed Aug 22 22:11:24 2018 +0000 darwin/amd64
ok  	github.com/influxdata/platform/task	1.821s
ok  	github.com/influxdata/platform/task	9.150s
```

/cc @odeke-em @ianlancetaylor

**Comment by odeke-em** [comment] 2018-09-02 23:07
Thank you for the investigation and report @mark-rushakoff!

In deed, the regression is present but for consistency and correctness to avoid data corruption, the change seems inevitable.

Could we please compare the speeds and throughput on Linux vs on OS X vs Windows?

**Comment by ianlancetaylor** [comment] 2018-09-03 23:50
On Darwin it seems clearly correct to use `F_FULLFSYNC`, and a reduction in speed of calls to the `Sync` method is an inevitable result.  This sounds like working as intended.  If you want to trade off data corruption for speed, don't call the `Sync` method.

**Comment by mark-rushakoff** [comment] 2018-09-03 23:59
That's fair @ianlancetaylor. I assume this performance change will surprise many other users; maybe this issue should be repurposed to track that the `F_FULLSYNC` change and its consequences are clearly documented in the Go1.12 release notes?

**Comment by alexbrainman** [comment] 2018-09-04 09:12
> Unfortunately I don't have a WIndows machine but I'll kindly page @alexbrainman to help with those benchmarks if available

I did not bother with the benchmarks, because

https://go-review.googlesource.com/c/go/+/130676

did not change any windows code. Please, let me know, if I am wrong.

Alex

**Comment by ianlancetaylor** [comment] 2018-09-07 11:08
I added a RELNOTES tag to the CL, so we will add something to the release notes.  Closing this issue.

**Closed by ianlancetaylor** 2018-09-07 11:08 UTC
Labels: NeedsInvestigation

**Comment by odeke-em** [comment] 2018-09-07 16:53
>did not change any windows code. Please, let me know, if I am wrong

@alexbrainman no, we meant to say just raw performance numbers regardless of the operating system, to compare with what OS X was seeing, for ballparking how OS X would be suffering. Anyways, no need for it anymore :)

>I added a RELNOTES tag to the CL, so we will add something to the release notes. Closing this issue.

Thank you Ian!
