### ISSUE TITLE
net/mail: fails to escape address

### ISSUE THREAD

**Issue by dvyukov** [golang/go#11294] opened 2015-06-19 13:03 UTC
The following program fails with the panic:
```go
package main

import (
	"fmt"
	"net/mail"
)

func main() {
	data := "=??Q? ?=<0@0>"
	addr, err := mail.ParseAddress(data)
	if err != nil {
		return
	}
	_, err = mail.ParseAddress(addr.String())
	if err != nil {
		fmt.Printf("failed to parse addr: %q -> %q\n", data, addr)
		panic(err)
	}
}
```
```
failed to parse addr: "=??Q? ?=<0@0>" -> "\"=??Q? ?=\" <0@0>"
panic: mail: missing word in phrase: charset not supported: ""
```

That name should have been escaped.

go version devel +514014c Thu Jun 18 15:54:35 2015 +0200 linux/amd64

**Comment by rsc** [comment] 2015-11-25 21:21
Dup of #11292.

**Comment by alexcesaro** [comment] 2015-12-02 22:51
@rsc This issue is not a duplicate of #11292 and this code still panics on tip.

I will have a look during Go 1.7 dev cycle.

**Comment by bradfitz** [comment] 2015-12-02 22:56
@alexcesaro, any chance you have time to look at this for 1.6 still? It would be nice to not have panics in code parsing random inputs.

**Comment by alexcesaro** [comment] 2015-12-02 23:04
It is Dmitry's snippet above that panics not the net/mail code.

Also it is not a regression, that bug was discovered before Go 1.5 and is probably there since the beginning.

**Comment by bradfitz** [comment] 2015-12-02 23:07
> It is Dmitry's snippet above that panics not the net/mail code.

Sorry, I'm always confused by the reports saying "this code panics" when the code is just doing `if err { panic }`

**Comment by alexcesaro** [comment] 2015-12-02 23:10
Yes sorry I wasn't clear :)

**Comment by rsc** [comment] 2015-12-03 00:37
The fix for #11292 should have fixed this. If not we need to add a
character or two to the base64 trigger the CL added.

Russ

**Comment by alexcesaro** [comment] 2015-12-03 08:25
I am on my phone but I don't think it is the same bug.

#11292 was an encoding issue. Here it is a parsing issue: the code thinks there is an encoded-word but it is not.

**Comment by rsc** [comment] 2015-12-03 14:58
The first parse succeeds. Maybe that's a mistake, yes. But either way the
resulting Addr - which could be created by direct field initialization
instead - should survive the round trip `mail.ParseAddress(addr.String())`.

**Closed** 2015-12-04 16:11 UTC
