### ISSUE TITLE
cmd/go: `go mod tidy` and `go mod download` don't agree on same go.sum file. 

### ISSUE THREAD

**Issue by c4milo** [golang/go#44441] opened 2021-02-19 23:31 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes 

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ ~/Downloads/go\ 2/bin/go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/caguilar/Library/Caches/go-build"
GOENV="/Users/caguilar/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/caguilar/go/pkg/mod"
GONOPROXY="slack-github.com"
GONOSUMDB="slack-github.com"
GOOS="darwin"
GOPATH="/Users/caguilar/go"
GOPRIVATE="slack-github.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/caguilar/Downloads/go 2"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/caguilar/Downloads/go 2/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/caguilar/src/goslackgo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sd/dhdfq5qx471__68g8fl9v_jh0000gp/T/go-build540412494=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
1. go mod tidy 
2. go mod download

### What did you expect to see?
I was expecting `go.sum` to not change.

### What did you see instead?
`go.sum` changed. This causes issues in our CI since we don't expect source files to be arbitrarily changed during CI.

**Comment by tmthrgd** [comment] 2021-02-20 02:10
This is a duplicate of #43994.

**Closed** 2021-02-20 07:15 UTC
