### ISSUE TITLE
compress/lzw: panic: index out of range in reader

### ISSUE THREAD

**Issue by zgrim** [golang/go#20597] opened 2017-06-07 08:22 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +90b39f33c4 Wed Jun 7 05:55:11 2017 +0000 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
linux amd64

### What did you do?

https://play.golang.org/p/54wxXb3tnW

### What did you expect to see? 

error in gif decoder or "ok\n"

### What did you see instead?

panic: runtime error: index out of range

goroutine 1 [running]:
compress/lzw.(*decoder).decode(0xc4200baa00)
        /home/zgrim/go1.9/src/compress/lzw/reader.go:178 +0x505
compress/lzw.(*decoder).Read(0xc4200baa00, 0xc4200e406f, 0x1fe8, 0x1fe8, 0x1003, 0x0, 0x0)
        /home/zgrim/go1.9/src/compress/lzw/reader.go:132 +0x2c
io.ReadAtLeast(0x7fa9a1bf4018, 0xc4200baa00, 0xc4200d6000, 0x10057, 0x10057, 0x10057, 0x44dac0, 0x7fa900000018, 0xc42004bbf8)
        /home/zgrim/go1.9/src/io/io.go:307 +0x86
io.ReadFull(0x7fa9a1bf4018, 0xc4200baa00, 0xc4200d6000, 0x10057, 0x10057, 0x40ce68, 0x4bbda0, 0x4c0e60)
        /home/zgrim/go1.9/src/io/io.go:325 +0x58
image/gif.readFull(0x7fa9a1bf4018, 0xc4200baa00, 0xc4200d6000, 0x10057, 0x10057, 0xc4200baa00, 0x0)
        /home/zgrim/go1.9/src/image/gif/reader.go:67 +0x5a
image/gif.(*decoder).decode(0xc420090000, 0x5453a0, 0xc42000c080, 0x0, 0x0, 0x0)
        /home/zgrim/go1.9/src/image/gif/reader.go:228 +0x313
image/gif.Decode(0x5453a0, 0xc42000c080, 0xc42000c080, 0x0, 0x0, 0xa2)
        /home/zgrim/go1.9/src/image/gif/reader.go:494 +0x5d
main.main()
        /tmp/lzw/t.go:21 +0x99
exit status 2

**Comment by davecheney** [comment] 2017-06-07 08:29
Thats, uh, an interesting image.

Smaller reproducer
```
package main

import (
        "fmt"
        "image/gif"
        "os"
)

func main() {

        // wget "http://cdn.wwwpromoter.com/4313aa528cc1ffcd148c2585e88f8946872a4f5ec1b35b5e5b4cf2da0ea26283bc443665c1812ae18e520ca365540e44_er.gif" -Ot.gif

        r, err := os.Open("./t.gif")
        if err != nil {
                panic(err)
        }
        _, err = gif.Decode(r)
        if err != nil {
                panic(err)
        }
        fmt.Println("ok")
}
```

**Comment by davecheney** [comment] 2017-06-07 08:36
Possibly caused by 642a1cc7563953bf2be39eca461325bfa9735cde 

Marking as Go 1.9 as this is a possible regression form 1.8

/cc @dsymonds

**Comment by dsymonds** [comment] 2017-06-07 08:39
@nigeltao would be the culprit if it's 642a1cc.

**Comment by davecheney** [comment] 2017-06-07 08:41
Indeed. Sorry for the incorrect attribution.

**Comment by dsymonds** [comment] 2017-06-07 08:47
Well, I carry some of the blame, since I reviewed his code. You would have thought I'd have learned by now...  ;-)

**Comment by zgrim** [comment] 2017-06-07 11:46
> Thats, uh, an interesting image.

Sorry, just boring data from the logs, but i should've picked a more decent one. :) So, here's another, from [`here`](http://images.3lift.com/3587713_a200.gif), if preferable.

**Comment by dgryski** [comment] 2017-06-07 15:16
The new image code should definitely be fuzzed.

**Closed** 2017-06-08 01:28 UTC
