### ISSUE TITLE
Compile with no garbage collection instead of GOGC=off

### ISSUE THREAD

**Issue by kolinfluence** [golang/go#60651] opened 2023-06-07 04:12 UTC
some of my programs are 100% zero memory allocated, no heap escape and no garbage generated.
so garbage collection is not needed.

possible to have a compiler option to disable doing any gc checks or whatsoever and just skip gc completely?
so as to have the optimum speed like rust / c compiled

**Comment by seankhliao** [comment] 2023-06-07 09:40
Duplicate of #39231

**Closed by seankhliao** 2023-06-07 09:40 UTC
Labels: Proposal
