### ISSUE TITLE
x/sys/windows/svc: Error 1053 could not start service when user assigned is not Local System Account or has no admin rights

### ISSUE THREAD

**Issue by coderars** [golang/go#45966] opened 2021-05-05 09:35 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.16.3 windows/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ARS\AppData\Local\go-build
set GOENV=C:\Users\ARS\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\ARS\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ARS\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\ARS\scoop\apps\go\current
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\ARS\scoop\apps\go\current\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ARS\AppData\Local\Temp\go-build2586798521=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

- Build the SVC example from `golang.org/x/sys`
- Install the service on Windows 10: `.\example.exe install`
- Open `services.msc`, find `my service`
- Start it as it is (using `Local System Account` by default) (starts normally, no error)
- Stop it
- Open its properties and switch to the `Log On` tab
- Assign a local user who is NOT a member of the Administrators group (has no admin rights). Check that he owns the `Log on as service` permission in `Local Security Policy`, but Windows will grant it automatically at this step if needed.
- Start the service (and observe the error 1053 popup message)

### What did you expect to see?

The example service `my service` to start normally.

### What did you see instead?

Windows popup error message: 
> Error 1053: could not start service: The service did not respond to the start or control request in a timely fashion.

also when starting from command line `.\example.exe start`:
> failed to start myservice: could not start service: The service did not respond to the start or control request in a timely fashion.

### My investigation (possible reason)

I'm not a go developer, but tried to build the svc example from some previous versions of `golang.org/x/sys` based on the commits history and tracked down that this issue may because this commit on Oct 8, 2020: [windows/svc: add IsWindowsService function](https://github.com/golang/sys/commit/280f808b4a5303f80a30dd9dc62f9a042d992ad0)

I assume because when building the svc example from one earlier state - right before that commit - this issue not exists, the service can start with my dedicated test user without any problem. 

### Real-world example of this issue (Gitea)

As I said I'm not a go developer (js actually), I am a user of a go project called [Gitea](https://github.com/go-gitea/), where me and many other users faced this problem with recent versions of Gitea and [reported this issue](https://github.com/go-gitea/gitea/issues/15454) first there. Gitea can be [installed](https://docs.gitea.io/en-us/windows-service/#register-as-a-windows-service) as a Windows service and it operated well for a long time. After our discussion, it became clear that the problem is independent of the Gitea code, so I was asked to report the issue here too.

### My OS version

Windows 10 Pro version 20H2 build 19042.964

**Comment by alexbrainman** [comment] 2021-05-09 09:00
@coderars thank you for reporting the problem.

I did not have time to investigate this properly, but https://github.com/go-gitea/gitea/pull/15762 looks like a good solution for the moment.

Alex

**Comment by networkimprov** [comment] 2021-05-16 18:06
@gopherbot add OS-Windows

**Comment by the-ress** [comment] 2021-12-15 20:21
this looks like a duplicate of #44921

**Comment by alexbrainman** [comment] 2021-12-31 06:53
> this looks like a duplicate of #44921

Agree.

Closing as a duplicate of #44921.

Alex

**Closed by alexbrainman** 2021-12-31 06:53 UTC
Labels: OS-Windows, NeedsInvestigation
