### ISSUE TITLE
database/sql: DB full resetterCh causes driver.ErrBadConn error

### ISSUE THREAD

**Issue by tuanpavn** [golang/go#31480] opened 2019-04-16 03:43 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"</summary><br><pre>
$ go env

</pre></details>

### What did you do?
I am doing stress test for mysql server using golang.
I create a sql.DB and set 

	db.SetMaxOpenConns(128)
	db.SetMaxIdleConns(32) 

Then I create 500 go-routines (500 clients) and send 1000000 queries to mysql server.
After I run the program, it sometimes pops up error "driver: bad connection" (`driver.ErrBadConn`).

I found that in sql.OpenDB, it creates a *sql.DB struct with: 
	resetterCh:   make(chan *driverConn, 50)

In `func (db *DB) putConn(dc *driverConn, err error, resetSession bool)`, if `db.resetterCh` is full, it marks connection as bad

	select {
	default:
		// If the resetterCh is blocking then mark the connection
		// as bad and continue on.
		dc.lastErr = driver.ErrBadConn
		dc.Unlock()
	case db.resetterCh <- dc:
	}
and if number of connections exceeds max connection, it reuses old connection which is marked as bad and return `driver.ErrBadConn`.

I can solve it by set max connection less than 50 (which is size of `db.resetterCh`).
Why did you hardcoded size of `db.resetterCh` to 50?
Should it be set to max connections?

https://play.golang.org/p/phUILuRV3hJ

**Comment by n-ozerov** [comment] 2019-04-26 21:29
experiencing same issue

**Comment by kardianos** [comment] 2019-04-26 21:53
I can see two solutions to this issue:
 * resize the resetter channel when the pool size is > 50
 * start to process the session reset synchronously. when the fixed size resetter is full.

I'll look into this more. I'm not ready for a final fix (the referenced CL isn't quite right I think). If someone wants to submit a CL in the next couple of days that would be great. We are really close to the 1.13 freeze.

**Comment by wekb** [comment] 2019-07-15 19:54
I think you'd need to do both. This is a bit of a black-box issue that sporadically effects production services—is there an ETA here, or would a submitted CL be processed fairly quickly? Thanks.

**Comment by kardianos** [comment] 2019-07-15 20:58
I think it is too late in the cycle to subit the CL, but if you want to, you could carry-pick the change locally and try it out.

**Comment by wekb** [comment] 2019-07-15 21:21
Would 1.12.x be game, or does the 1.13 freeze effect 1.12.x updates?

**Comment by kardianos** [comment] 2019-07-15 22:22
@bcmills I'm unsure on release policy. I don't think  1.12.x would be game and I believe 1.13 is too deeply frozen for this change. Can you provide feedback? Ping me on Hangouts or here if you need detail on exact scope of change, CL linked.

@wekb Can you help validate the linked CL?

**Comment by bcmills** [comment] 2019-07-16 16:30
@kardianos if the change is too invasive or subtle for 1.13 at this point, then it's almost certainly not a candidate for a 1.12 backport either, especially given that there is a workaround (namely, setting the connection limit ≤ 50).

**Comment by wekb** [comment] 2019-07-16 21:54
This would be a problem for larger services where 50 concurrent connections isn't adequate, however.

The CL builds and tests out on my end under pretty good stress. I patched 1.12.7 and the two behave the sameThat being said, I'm not able to reproduce the reported issue outside of prod. , but it would be difficult to deploy this in our production without a bit of a gamut of new Docker images, not to mention that we're trying to not have this issue effect us poorly again. :)

**Comment by wekb** [comment] 2019-07-17 23:31
I patched 1.12.7, and it builds and tests out on my end,

I put some fairly heavy load on both 1.12.7 and patched 1.12.7, basically the OP's 500-worker use case. I wasn't able to reproduce the issue locally, but both versions performed fine and comparably. The build-in go tests passed as well, obviously.

It would be difficult to deploy this in our production to reproduce the issue without undoing workaround code and gamut of new Docker images, not to mention that we're trying to not have this issue effect us poorly again. :)

All that said, the CL seems worthy, IMO.

**Comment by bcmills** [comment] 2019-09-11 19:35
@wekb, last I checked CL 174122 was awaiting a bit of rework to avoid blocking indefinitely in `ResetSession`.

When the fix is ready, I suspect it will not be eligible for backporting: to my knowledge it is not a regression, and there is a workaround today (setting `MaxOpenConns` ≤ 50).

**Comment by odeke-em** [comment] 2020-03-18 16:08
Reverting commit in CL https://go-review.googlesource.com/c/go/+/223958.

**Comment by odeke-em** [comment] 2020-03-31 21:21
Addressed by CLs https://go-review.googlesource.com/c/go/+/174122 and https://go-review.googlesource.com/c/go/+/223963.

**Closed by odeke-em** 2020-03-31 21:21 UTC
Labels: NeedsFix
