### ISSUE TITLE
proxy.golang.org: problem with some modules related to golang.org/x/

### ISSUE THREAD

**Issue by ldez** [golang/go#33513] opened 2019-08-07 08:15 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes with go1.12 latest

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ldez/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ldez/sources/go"
GOPROXY=""
GORACE=""
GOROOT="/home/ldez/.gvm/gos/go1.12.7"
GOTMPDIR=""
GOTOOLDIR="/home/ldez/.gvm/gos/go1.12.7/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ldez/sources/go/src/github.com/go-acme/lego/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build196235691=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

- clean the module cache
- clone https://github.com/ldez/lego/tree/feature/migrate-gomod (or https://github.com/go-acme/lego when branch will be merged)
- without `GOPROXY`
- `go mod tidy`
- then add `GOPROXY=https://proxy.golang.org`
- `go mod download`

### What did you expect to see?

No errors

### What did you see instead?

```
golang.org/x/time@v0.0.0-20190513212739-9d24e82272b4: unexpected status (https://proxy.golang.org/golang.org/x/time/@v/v0.0.0-20190513212739-9d24e82272b4.zip): 410 Gone
golang.org/x/lint@v0.0.0-20190511005446-959b441ac422: unexpected status (https://proxy.golang.org/golang.org/x/lint/@v/v0.0.0-20190511005446-959b441ac422.zip): 410 Gone
```

More information:

#### golang.org/x/time

```
golang.org/x/time v0.0.0-20190513212739-9d24e82272b4 h1:RMGusaKverhgGR5KBERIKiTyWoWHRd84GCtsNlvLvIo=
golang.org/x/time v0.0.0-20190513212739-9d24e82272b4/go.mod h1:tRJNPiyCQ0inRvYxbN9jk5I+vvW/OXSQhTDSoE431IQ=
```

```
golang.org/x/time@v0.0.0-20190513212739-9d24e82272b4: unexpected status (https://proxy.golang.org/golang.org/x/time/@v/v0.0.0-20190513212739-9d24e82272b4.zip): 410 Gone
```

- https://github.com/golang/time/commits/master
```
matloob committed on Feb 15
1 parent 85acf8d commit 9d24e82272b4f38b78bc8cff74fa936d31ccd8ef
```
- https://proxy.golang.org/golang.org/x/time/@v/v0.0.0-20190513212739-9d24e82272b4.info
```
not found: golang.org/x/time@v0.0.0-20190513212739-9d24e82272b4: invalid pseudo-version: does not match version-control timestamp (2019-03-08T20:28:27Z)
```
- https://proxy.golang.org/golang.org/x/time/@v/9d24e82272b4.info
```
{"Version":"v0.0.0-20190308202827-9d24e82272b4","Time":"2019-03-08T20:28:27Z"}
```
- https://github.com/search?q=golang.org%2Fx%2Ftime%40v0.0.0-20190513212739-9d24e82272b4&type=Code

#### golang.org/x/lint
```
golang.org/x/lint v0.0.0-20190409202823-959b441ac422/go.mod h1:6SW0HCj/g11FgYtHlgUYUwCkIfeOF89ocIRzGO/8vkc=
golang.org/x/lint v0.0.0-20190511005446-959b441ac422/go.mod h1:6SW0HCj/g11FgYtHlgUYUwCkIfeOF89ocIRzGO/8vkc=
```

```
golang.org/x/lint@v0.0.0-20190511005446-959b441ac422: unexpected status (https://proxy.golang.org/golang.org/x/lint/@v/v0.0.0-20190511005446-959b441ac422.zip): 410 Gone
```

- https://proxy.golang.org/golang.org/x/lint/@v/v0.0.0-20190511005446-959b441ac422.info
```
not found: golang.org/x/lint@v0.0.0-20190511005446-959b441ac422: invalid pseudo-version: does not match version-control timestamp (2019-04-09T20:28:23Z)
```
- https://proxy.golang.org/golang.org/x/lint/@v/959b441ac422.info
```json
{"Version":"v0.0.0-20190409202823-959b441ac422","Time":"2019-04-09T20:28:23Z"}
```

**Comment by marwan-at-work** [comment] 2019-08-07 15:29
Same thing is happening with Gizmo, if you follow the same steps from above and run `go mod tidy` inside github.com/nytimes/gizmo you'll get the following error: 

```
go: contrib.go.opencensus.io/exporter/ocagent@v0.4.6 requires
	github.com/census-instrumentation/opencensus-proto@v0.1.0-0.20181214143942-ba49f56771b8: reading https://proxy.golang.org/github.com/census-instrumentation/opencensus-proto/@v/v0.1.0-0.20181214143942-ba49f56771b8.mod: 410 Gone
```

I *think* this is related to the Proxy updating to Go1.13 and invalidating manually written pseudo versions, quote from the tooling mailing list: 

>Go 1.13 includes some changes to the go command which tighten up the validation of module versions. Now that we have upgraded proxy.golang.org to use the 1.13beta1 version of the go command, we will be invalidating old module versions that are currently being served from proxy.golang.org but are no longer valid in 1.13

**Comment by marwan-at-work** [comment] 2019-08-07 15:46
Following up a little more, I can see that `contrib.go.opencensus.io/exporter/ocagent@v0.4.6` has what I guess an incorrect pseudo version, and updating from `v0.4.6` to `v0.6.0` does solve the problem (see linked pr above ^)

**Comment by katiehockman** [comment] 2019-08-07 17:08
Yes, both of those versions for golang.org/x/lint and golang.org/x/time will now be invalid with 1.13 and will no longer be served from proxy.golang.org. This would have broken in direct-mode using 1.13 as well.

Try the suggestions that @marwan-at-work made, and I think that should solve the issues. Hopefully there aren't too many broken go.mod files in the wild, so once these get fixed, this problem shouldn't come up again. Thanks for reporting the issue.

**Comment by bcmills** [comment] 2019-08-07 17:35
Note that as a short-term workaround, you should be able to use a `replace` directive to target the corrected version. See https://tip.golang.org/doc/go1.13#version-validation.

**Comment by bcmills** [comment] 2019-08-07 19:05
Duplicate of #32805

**Closed by bcmills** 2019-08-07 19:05 UTC

**Comment by ldez** [comment] 2019-08-07 22:40
Thanks :heart:

**Comment by nono** [comment] 2019-08-20 10:05
> Hopefully there aren't too many broken go.mod files in the wild, so once these get fixed, this problem shouldn't come up again.

For the record, renovate creates PR with the bad pseudo-version: https://github.com/renovatebot/renovate/issues/4310. So, it may still come again.
