### ISSUE TITLE
proposal: cmd/go: warn if module uses features from next version of Go

### ISSUE THREAD

**Issue by Antonboom** [golang/go#67907] opened 2024-06-08 21:24 UTC
### Proposal Details

```go
// go.mod        
module test

go 1.20
```

```go
// main.go
package main

import (
    "fmt"
    "go/types"
)

func main() {
    fmt.Println(types.Unalias(nil))
}
```

```
$ go version
go version go1.22.2 darwin/arm64

$ go run main.go
<nil>
```

But! `types.Unalias` was appeared in [Go 1.22](https://tip.golang.org/doc/go1.22#minor_library_changes).

And any other module >= Go 1.20 can use module above as dependency (according to new [policy](https://tip.golang.org/doc/go1.21#tools)) but will receive compiler error like

```
main.go:9: undefined: types.Unalias
```

---

How can a developer check the version of your module to ensure that it does not contain features from the new toolchain (which may be installed as the latest version on the developer's machine)?

**Comment by seankhliao** [comment] 2024-06-08 21:39
Duplicate of #46136

**Closed by seankhliao** 2024-06-08 21:39 UTC
Labels: Proposal
