### ISSUE TITLE
cmd/go: retry some fetch failures

### ISSUE THREAD

**Issue by alevchuk** [golang/go#29345] opened 2018-12-19 18:58 UTC
<pre>
go version go1.11.2 linux/arm
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="arm"
GOBIN=""
GOCACHE="/home/lightning/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lightning/gocode"
GOPROXY=""
GORACE=""
GOROOT="/home/lightning/src/go"
GOTMPDIR=""
GOTOOLDIR="/home/lightning/src/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build269444191=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
GO111MODULE=on go get honnef.co/go/tools/cmd/staticcheck
```

### What did you expect to see?

Dependency should get installed. If there is a network timeout the build process should sleep and keep re-trying...

### What did you see instead?

```
go: finding github.com/mdlayher/genetlink v0.0.0-20180917171408-7615bc153978
go: finding github.com/mattn/go-xmlrpc v0.0.0-20180913190254-6e944673e4c0
go: finding github.com/mdlayher/wifi v0.0.0-20180727163819-efdf3f4195d9
go: finding github.com/prometheus/client_golang v0.9.1
go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: finding github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
go: finding github.com/lufia/iostat v0.0.0-20170605150913-9f7362b77ad3
go: finding github.com/godbus/dbus v4.1.0+incompatible
go: golang.org/x/tools@v0.0.0-20181218204010-d4971274fe38: unrecognized import path "golang.org/x/tools" (https fetch: Get https://golang.org/x/tools?go-get=1: net/http: TLS handshake timeout)
go: honnef.co/go/tools@v0.0.0-20180920025451-e3ad64cb4ed3: unrecognized import path "honnef.co/go/tools" (https fetch: Get https://honnef.co/go/tools?go-get=1: net/http: TLS handshake timeout)
go: finding github.com/prometheus/procfs v0.0.0-20181005140218-185b4288413d
...
```

Many downstream failures, e.g.:
```
monitoring@b4:~/gocode/src/github.com/prometheus/node_exporter $ make
>> checking code style
tmpModule=$(mktemp -d 2>&1) && \
mkdir -p ${tmpModule}/staticcheck && \
cd "${tmpModule}"/staticcheck && \
GO111MODULE=on go mod init example.com/staticcheck && \
GO111MODULE=on GOOS= GOARCH= go get -u honnef.co/go/tools/cmd/staticcheck@next && \
rm -rf ${tmpModule};
go: creating new go.mod: module example.com/staticcheck
go: finding honnef.co/go/tools/cmd/staticcheck next
go: finding honnef.co/go/tools/cmd next                                                                                                                                                            go: finding honnef.co/go/tools next
go: downloading honnef.co/go/tools v0.0.0-20181108184350-ae8f1f9103cc
go: finding github.com/BurntSushi/toml v0.3.1                                                                                                                                                      go: finding golang.org/x/tools/go/packages latest
go: finding golang.org/x/tools/go/ast/astutil latest
go: finding golang.org/x/tools/go/loader latest
go: finding golang.org/x/tools/go/types/typeutil latest
go: finding golang.org/x/tools/go latest
go: finding golang.org/x/tools/go/ast latest
go: finding golang.org/x/tools/go/types latest
go: finding golang.org/x/tools latest
go: downloading golang.org/x/tools v0.0.0-20181218204010-d4971274fe38
go: downloading github.com/BurntSushi/toml v0.3.1
build honnef.co/go/tools/cmd/staticcheck: cannot find module for path bufio
Makefile.common:201: recipe for target '/home/monitoring/gocode/bin/staticcheck' failed
make: *** [/home/monitoring/gocode/bin/staticcheck] Error 1
```

**Comment by bcmills** [comment] 2019-01-17 13:44
Duplicate of #28194.

**Closed by bcmills** 2019-01-17 13:44 UTC
Labels: FeatureRequest, GoCommand, NeedsInvestigation, modules
