### ISSUE TITLE
x/tools/cmd/oracle: provide/improve the functionality to describe the contents of a Go source file.

### ISSUE THREAD

**Issue by bruno-medeiros** [golang/go#11188] opened 2015-06-12 18:25 UTC
Hello. I'd like to have functionality in Go oracle that would provide a syntactic description (no semantics involved therefore) of the top-level elements of a Go source file (Functions, global vars, etc). This functionality would be used to implement an editor outline for an IDE (currently Goclipse), although it could have other uses.

This can be achieve already with the `describe` command invoked with a position on a package declaration, however this method has some limitations that could be improved upon:

* Need to find the offset of the package declaration package name. This is unnecessary. Only the source file name should be necessary in the `describe` command line arguments.
* It also requires a Go package specified in the command line. Again this is redundant, same reason as above.
* It requires that the Go source file be part of a Go workspace (that is, be part of GOPATH). This is also unnecessary since no semantic analysis is performed.

**Comment by alandonovan** [comment] 2016-02-10 18:11
This is out of scope for the oracle.  By design, the oracle answers questions about a single position within a source file.  What you need is a tool that inspects a source file and reports the positions of several entities within it.  You can do that using the `go/parser` and `go/ast` packages.

**Closed by alandonovan** 2016-02-10 18:11 UTC
