### ISSUE TITLE
x/build/cmd/gopherbot: don't fight humans

### ISSUE THREAD

**Issue by FiloSottile** [golang/go#24834] opened 2018-04-12 20:43 UTC
Gopherbot is supposed not to fight humans, but it happened in at least these two occasions recently:

* #24321 ignored a reopen
* #24597 ignored a unlabel

**Comment by FiloSottile** [comment] 2018-04-12 20:45
See also #21312

**Comment by mvdan** [comment] 2018-04-12 21:04
Maybe it needs to be taught the three laws of robotics.

**Comment by bradfitz** [comment] 2018-04-13 20:16
The WaitingForInfo bot waits for the OP to reply. So it looks like #24321 was working as designed, at least. Maybe the design is wrong.

I suppose #24597 could be fixed to permit non-Builder bugs with prefix x/build, but I don't see the point. Really, the "Builder" label means "things in the x/build repo", so I think it's fine as-is. But I'd prefer we just do #23223.

The #21312 documentation label one is a bug, though.

**Comment by bcmills** [comment] 2018-04-13 21:40
For the WaitingForInfo case, perhaps we should consider any comment followed by a reopening to be “more info”: we should only re-close the issue if it was reopened without comment.

**Comment by dmitshur** [comment] 2018-10-15 19:06
I'm going to fold this issue into #21312, since it's the same thing. I'll take its title since it's easer to find and more accurate.

**Closed by dmitshur** 2018-10-15 19:06 UTC
Labels: Builders, NeedsInvestigation
