### ISSUE TITLE
FAIL: TestSignalTrace

### ISSUE THREAD

**Issue by toralf** [golang/go#47264] opened 2021-07-17 14:02 UTC
dev-lang/go-1.16.6 

build host is a hardened Gentoo linux system [1]:
  Linux mr-fox 5.12.17 #16 SMP Wed Jul 14 18:03:13 CEST 2021 x86_64 AMD Ryzen 9 5950X 16-Core Processor AuthenticAMD GNU/Linux

Details off the failure are in https://bugs.gentoo.org/802429

[1] https://zwiebeltoralf.de/tinderbox.html

**Comment by seankhliao** [comment] 2021-07-17 14:45
Duplicate of #46736

**Closed by seankhliao** 2021-07-17 14:45 UTC
