### ISSUE TITLE
x/tools/gopls: automated issue report (crash) - many different random crash patterns

### ISSUE THREAD

**Issue by Airren** [golang/go#50433] opened 2021-12-21 01:44 UTC
gopls version: v0.7.4
gopls flags: 
update flags: proxy
extension version: 0.30.0
go version: 1.17.5
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Tue, 21 Dec 2021 01:44:03 GMT
restart history:
Tue, 21 Dec 2021 01:43:32 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2022-01-04 19:00
That "unbalanced scopes" error is particularly concerning for me, as it is possibly related to some parser refactoring I did for Go 1.17. But I've never seen it reported before, and I'm really surprised for it to be reported for the first time so long after go 1.17 came out.

It could be memory corruption, but I don't understand how it would manifest in this way.

@Airren is this reproducible on your end?

**Comment by findleyr** [comment] 2022-01-04 19:40
I stared at the "unbalanced scopes" issue in `go/parser/resolver.go` and don't know how it would be possible without corruption, though I of course could be missing something. Notably this appears to be happening in the go command, not directly within gopls.

**Comment by findleyr** [comment] 2022-01-11 14:12
I think without more information here we can't spend more time tracking this down. It seems to be a very broken machine (though in surprising ways). If this is reproducible we can perhaps understand it.

**Comment by suzmue** [comment] 2022-01-14 18:51
Closing. Please reopen if you are able to reproduce.

**Closed by suzmue** 2022-01-14 18:51 UTC
Labels: WaitingForInfo, gopls, Tools
