### ISSUE TITLE
cmd/compile: IncompatibleAssign spreading slice of interface compliant types into variadic function accepting interface

### ISSUE THREAD

**Issue by dillonstreator** [golang/go#62151] opened 2023-08-19 01:54 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 windows/amd64
</pre>

While this doesn't seem to be version-specific and appears to be an intentional design choice, it is unexpected behavior.

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\dillon\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\dillon\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.0
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
</pre></details>

### What did you do?

Spreading a slice of interface compliant types into a function expecting variadic interface parameter results in an unexpected `IncompatibleAssign`. Directly passing the interface compliant types to the function as comma separated arguments compiles fine.

https://go.dev/play/p/NP6-6rHauMC

### What did you expect to see?

No compilation error

### What did you see instead?

Compilation error
```sh
cannot use things (variable of type []thing) as []doer value in argument to doit
```

**Comment by dmitshur** [comment] 2023-08-19 04:39
What does the Go language specification say about this?

I expect this is working as intended, and the https://go.dev/doc/faq#convert_slice_with_same_underlying_type entry covers this situation.

Also see https://github.com/golang/go/issues/38385#issuecomment-612738618. I'll close it as a duplicate of that, but please comment if I missed something.

**Closed by dmitshur** 2023-08-19 04:39 UTC
Labels: NeedsInvestigation, compiler/runtime
