### ISSUE TITLE
Can we document net.Conn Write as being atomic?

### ISSUE THREAD

**Issue by eloff** [golang/go#46250] opened 2021-05-19 00:39 UTC
I answered this [stackoverflow question](https://stackoverflow.com/a/67595487/152580) about the atomicity of net.Conn Write.

It seems the implementation on both Unix and Windows is atomic in practice by acquiring a mutex around the OS write/send call(s).

One could possibly remove the mutex and thus allow writes to interleave - but that seems senseless and very likely will break real-world code at this point.

Not documenting that guarantee requires callers to maintain their own mutex around calls to write, and it is redundant and expensive to nest mutexes like that. Is it possible to document that interleaved writes are not permitted (i.e. that Write is atomic)?

One might argue the threadsafe guarantee for net.Conn already promises that - but it's ambiguous - it might just mean it doesn't crash.

**Comment by seankhliao** [comment] 2021-05-19 00:55
I think this is already covered by
> Multiple goroutines may invoke methods on a Conn simultaneously.

**Comment by davecheney** [comment] 2021-05-19 00:57
What’s the use case for having two goroutines writing to the same net.Conn concurrently?

**Comment by networkimprov** [comment] 2021-05-19 02:22
This has been discussed in a prior issue.

**Comment by seankhliao** [comment] 2021-05-19 07:11
Duplicate of #27203

**Closed by seankhliao** 2021-05-19 07:11 UTC
Labels: Documentation
