### ISSUE TITLE
net: after call of {TCP,UDP,IP,Unix}Conn/{TCP,Unix}Listener.File(), the deadline will be ineffective

### ISSUE THREAD

**Issue by goosman-lei** [golang/go#21862] opened 2017-09-13 14:55 UTC
https://github.com/golang/go/blob/c2f8ed267b3fdfd06ca1a50aaf405886e52a8122/src/net/fd_unix.go#L316

in the under demo code:
the first goroutine, listener is not call (*net.TCPListener).File(), it timeout with setDeadline() works fine

the second goroutine, listener call (*net.TCPListener).File(), after that, the timeout don't work

the third goroutine, listener call (*net.TCPListener).File(), but then set it to non-blocking mode, timeout works fine too

```go
package main

import (
    "fmt"
    "net"
    "sync"
    "syscall"
    "time"
)

func main() {
    wg := new(sync.WaitGroup)
    wg.Add(2)

    go func() {
        addr, _ := net.ResolveTCPAddr("tcp", ":2020")
        l, _ := net.ListenTCP("tcp", addr)
        for {
            l.SetDeadline(time.Now().Add(time.Second))
            c, err := l.AcceptTCP()
            if err != nil {
                if nErr, ok := err.(net.Error); ok && nErr.Timeout() {
                    fmt.Printf("server 1 timeout at: %s\n", time.Now())
                    continue
                }   
                fmt.Printf("server 1 error: %s\n", err)
                break
            }   
            fmt.Printf("server 1 accept from: %s %s\n", c.RemoteAddr().String(), time.Now())
        }   
        wg.Done()
    }() 
    go func() {
        addr, _ := net.ResolveTCPAddr("tcp", ":2021")
        l, _ := net.ListenTCP("tcp", addr)
        l.File()
        for {
            l.SetDeadline(time.Now().Add(time.Second))
            c, err := l.AcceptTCP()
            if err != nil {
                if nErr, ok := err.(net.Error); ok && nErr.Timeout() {
                    fmt.Printf("server 2 timeout at: %s\n", time.Now())
                    continue
                }   
                fmt.Printf("server 2 error: %s\n", err)
                break
            }   
            fmt.Printf("server 2 accept from: %s %s\n", c.RemoteAddr().String(), time.Now())
        }   
        wg.Done()
    }() 
    go func() {
        addr, _ := net.ResolveTCPAddr("tcp", ":2022")
        l, _ := net.ListenTCP("tcp", addr)
        f, _ := l.File()
        syscall.SetNonblock(int(f.Fd()), true)
        for {
            l.SetDeadline(time.Now().Add(time.Second))
            c, err := l.AcceptTCP()
            if err != nil {
                if nErr, ok := err.(net.Error); ok && nErr.Timeout() {
                    fmt.Printf("server 3 timeout at: %s\n", time.Now())
                    continue
                }   
                fmt.Printf("server 3 error: %s\n", err)
                break
            }   
            fmt.Printf("server 3 accept from: %s %s\n", c.RemoteAddr().String(), time.Now())
        }   
        wg.Done()
    }() 

    wg.Wait()
}
```

**Comment by ianlancetaylor** [comment] 2017-09-13 17:07
I assume you are running on a Unix system.

I don't see any way to fix this.  Do you have any suggestions?

**Comment by goosman-lei** [comment] 2017-09-19 07:19
I don't understand why here set fd to blocking mode. . 
In my opinion, whether set into blocking mode, should taken the control to user programmer

**Comment by bradfitz** [comment] 2017-11-28 02:34
Is this fixed by `(*TCPListener) SyscallConn() (syscall.RawConn, error)` in Go 1.10?

https://tip.golang.org/pkg/net/#TCPListener.SyscallConn

**Comment by crvv** [comment] 2017-11-30 05:24
> Is this fixed by (*TCPListener) SyscallConn() (syscall.RawConn, error) in Go 1.10?

The issue is the method `*(net.TCPListener).File` makes the deadline ineffective.
It can't be fixed by adding a new method. The method `File()` can still break the deadline.

`SyscallConn` can give me the fd without making the deadline ineffective.
So I think it's good enough if the behavior is documented clearly.

```
package main

import (
        "fmt"
        "net"
        "time"
)

func main() {
        addr, _ := net.ResolveTCPAddr("tcp", ":2022")
        l, _ := net.ListenTCP("tcp", addr)
        sc, _ := l.SyscallConn()
        sc.Control(func(fd uintptr) { println(fd) })
        for {
                l.SetDeadline(time.Now().Add(time.Second))
                c, err := l.AcceptTCP()
                if err != nil {
                        if nErr, ok := err.(net.Error); ok && nErr.Timeout() {
                                fmt.Printf("server 3 timeout at: %s\n", time.Now())
                                continue
                        }
                        fmt.Printf("server 3 error: %s\n", err)
                        break
                }
                fmt.Printf("server 3 accept from: %s %s\n", c.RemoteAddr().String(), time.Now())
        }
}
```

**Closed** 2017-12-08 19:46 UTC
Labels: Documentation, WaitingForInfo

**Comment by mikioh** [comment] 2018-04-20 03:45
Also see #24942.
