### ISSUE TITLE
Confirm the visibility of Method Sets

### ISSUE THREAD

**Issue by yangyuqian** [golang/go#16421] opened 2016-07-19 06:17 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yangyuqian/gopkg"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="0"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```
// main.go
package main

type A struct {}

func (A) F1(){}
func (*A) Fp1(){}

func main(){
  a := A{}
  a.Fp1()
}
```

4. What did you expect to see?

According the description in go spec:

>  The method set of any other type T consists of all methods declared with receiver type T. The method set of the corresponding pointer type *T is the set of all methods declared with receiver *T or T (that is, it also contains the method set of T).

I expect my example above to throw some exceptions or panics because I'm calling a method Fp1 defined on *A.

5. What did you see instead?

I can access A.Fp1 without errors.

**Comment by yangyuqian** [comment] 2016-07-19 06:23
In addition, when I try to access the A.Fp1 with reflection, it panics

```
package main

import (
	"reflect"
)

type A struct{}

func (A) F1() { println("A.F1") }
func (A) f1() { println("A.f1") }

func (*A) Fp1() { println("*A.Fp1") }
func (*A) fp1() { println("*A.fp1") }

func main() {
	a := A{}
	aa := &a
	println("---------- without reflection -----------------")
	a.Fp1()
	aa.Fp1()
	println("---------- with reflection -----------------")
	reflect.ValueOf(a).MethodByName("F1").Call(nil)
	reflect.ValueOf(a).MethodByName("Fp1").Call(nil)
}
```

Console output:
```
---------- without reflection -----------------
*A.Fp1
*A.Fp1
---------- with reflection -----------------
A.F1
panic: reflect: call of reflect.Value.Call on zero Value

goroutine 1 [running]:
panic(0x917c0, 0x82015a2a0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
reflect.flag.mustBe(0x0, 0x13)
        /usr/local/go/src/reflect/value.go:202 +0xa6
reflect.Value.Call(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:301 +0x48
main.main()
        /Users/yangyuqian/code/example-go/main.go:23 +0x255
exit status 2

```

**Comment by ianlancetaylor** [comment] 2016-07-19 06:27
We don't use the issue tracker for questions.  Please ask questions in  a forum instead; see https://golang.org/wiki/Questions .

In your first example `a.Fp1` works because the address of `a` is implicitly taken, making this identical to `(&a).Fp1`.  See https://golang.org/ref/spec#Calls : "If x is addressable and &x's method set contains m, x.m() is shorthand for (&x).m()."  This does not help with your second example, because this shorthand does not apply when using reflection.

Closing as this is not a bug.

**Closed by ianlancetaylor** 2016-07-19 06:27 UTC

**Comment by yangyuqian** [comment] 2016-07-19 06:32
I see, thanks for the quick response anyway.
