### ISSUE TITLE
encoding/gob decode []byte to multi struct types

### ISSUE THREAD

**Issue by Cas-pian** [golang/go#18683] opened 2017-01-17 09:30 UTC
I got two struct types encoded into bytes by gob, I want to decode the bytes into a specific struct, is it possible without try all struct types(maybe 3 or more struct types)?

 I want to decode bytes without specify which elem in mixedBytes is struct A, and which is struct B.
This is the playground url:  https://play.golang.org/p/F0Wp5eWdGu

Is is possible to implement it by a map or something like this?

```go
var typesMap = map[string]reflect.Value{
     "A": reflect.ValueOf(A{}),
     "B": reflect.ValueOf(B{}),
}
```

**Comment by ALTree** [comment] 2017-01-17 10:03
Hi,

the Go project does not use its bug tracker for general discussion or asking questions. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

The [Questions wiki page](https://github.com/golang/go/wiki/Questions) has a list of good places for asking questions. 

Closing this, since it's not a bug.

**Closed by ALTree** 2017-01-17 10:03 UTC
