### ISSUE TITLE
x/tools/gopls: panic in internal/lsp/debug

### ISSUE THREAD

**Issue by skoo87** [golang/go#53793] opened 2022-07-10 03:26 UTC
gopls version: v0.9.0 (go1.18.2)
gopls flags: 
update flags: proxy
extension version: 0.34.1
go version: 1.18.2
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Sun, 10 Jul 2022 03:26:23 GMT
restart history:
Sat, 09 Jul 2022 03:25:11 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x100bac188]

goroutine 4572 [running]:
golang.org/x/tools/internal/xcontext.detachedContext.Value(...)
	  xcontext.go:23
golang.org/x/tools/internal/lsp/debug.GetInstance({0x101579160%3F, 0x140054765d0%3F})
	  serve.go:361  0x44
golang.org/x/tools/internal/lsp/debug.makeGlobalExporter.func1({0x101579160, 0x140054765d0}, {{0xc0aaaf92c13c77a0, 0x8642f0be9, 0x101a7d780}, {{{0x101577e90, 0x14000032120}, 0xa, {0x101441860, 0x101166015}}, ...}, ...}, ...)
	  serve.go:571  0x58
golang.org/x/tools/internal/event/core.deliver({0x101579160, 0x140054765d0}, 0x140004f9260, {{0xc0aaaf92c13c77a0, 0x8642f0be9, 0x101a7d780}, {{{0x101577e90, 0x14000032120}, 0xa, {0x101441860, ...}}, ...}, ...})
	  export.go:45  0xac
golang.org/x/tools/internal/event/core.ExportPair({_, _}, {{0x0, 0x0, 0x0}, {{{0x101577e90, 0x14000032120}, 0xa, {0x101441860, 0x101166015}}, ...}, ...}, ...)
	  export.go:68  0xc4
golang.org/x/tools/internal/event.Start({0x101579160%3F, 0x140054765d0%3F}, {0x101166015%3F, 0x1400572e4e0%3F}, {0x14003087630%3F, 0x0%3F, 0x0%3F})
	  event.go:91  0x1e8
golang.org/x/tools/internal/jsonrpc2.(*conn).Notify(0x1400572e4e0%3F, {0x101579160, 0x140054765d0}, {0x101166015, 0xa}, {0x101424080%3F, 0x1400572e4e0%3F})
	  conn.go:85  0x258
golang.org/x/tools/internal/lsp/protocol.clientConn.Notify(...)
	  protocol.go:60
golang.org/x/tools/internal/lsp/protocol.(*clientDispatcher).Progress(0x101505c60%3F, {0x101579160%3F, 0x140054765d0%3F}, 0x14005989650%3F)
	  tsclient.go:168  0x4c
golang.org/x/tools/internal/lsp/progress.(*WorkDone).Report(0x1400021c8c0, {0x0%3F, 0x0%3F}, {0x14004a761e0, 0x18}, 0x0)
	  progress.go:188  0x2b8
golang.org/x/tools/internal/lsp/progress.(*WorkDoneWriter).Write(0x1400572e140%3F, {0x14003886000%3F, 0x18, 0x18%3F})
	  progress.go:268  0x60
io.(*multiWriter).Write(0x140027b0b70%3F, {0x14003886000, 0x18, 0x8000})
	  multi.go:60  0x90
io.copyBuffer({0x101572738, 0x14005892780}, {0x101572bd8, 0x140027b0b70}, {0x0, 0x0, 0x0})
	  io.go:428  0x1a8
io.Copy(...)
	  io.go:385
os/exec.(*Cmd).writerDescriptor.func1()
	  exec.go:311  0x48
os/exec.(*Cmd).Start.func1(0x10157fcc0%3F)
	  exec.go:441  0x30
created by os/exec.(*Cmd).Start
	  exec.go:440  0x5bc
[Error - 11:26:03 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment] 2022-07-14 14:55
Thanks for the report. This was a dupe of https://github.com/golang/go/issues/53781, which has been fixed in gopls@v0.9.1 released yesterday.

**Closed by findleyr** 2022-07-14 14:55 UTC
Labels: gopls, Tools
