### ISSUE TITLE
x/pkgsite: searching for standard packages should always come first

### ISSUE THREAD

**Issue by dsnet** [golang/go#54224] opened 2022-08-03 08:30 UTC
[Search for "path"](https://pkg.go.dev/search?q=path) provides the following results:
1. [path/filepath](https://pkg.go.dev/path/filepath)
2. [github.com/Masterminds/glide/path](https://pkg.go.dev/github.com/Masterminds/glide/path)
3. [golang.org/x/sys/execabs](https://pkg.go.dev/golang.org/x/sys/execabs)
4. [github.com/ipfs/go-path](https://pkg.go.dev/github.com/ipfs/go-path)
5. [github.com/arduino/go-paths-helper](https://pkg.go.dev/github.com/arduino/go-paths-helper)

Notice that [path](https://pkg.go.dev/path) is nowhere in the results?

**Comment by seankhliao** [comment] 2022-08-03 12:31
Duplicate of #41369

**Closed by seankhliao** 2022-08-03 12:31 UTC
Labels: pkgsite
