### ISSUE TITLE
x/playground: timeout compiling trivial code that imports net/http

### ISSUE THREAD

**Issue by 89z** [golang/go#44822] opened 2021-03-05 20:49 UTC
If I try to run the example here:

https://golang.org/pkg/net/http/httputil#DumpResponse

I get this:

~~~
timeout running go build

Go build failed.
~~~

Same result if using same code on the playground:

https://play.golang.org/p/nf79uLXs5-b

If I run locally, it works fine:

~~~
"HTTP/1.1 200 OK\r\nContent-Length: 76\r\nContent-Type: text/plain;
charset=utf-8\r\nDate: Wed, 19 Jul 1972 19:00:00 GMT\r\n\r\nGo is a
general-purpose language designed with systems programming in mind.\n"
~~~

**Comment by dmitshur** [comment] 2021-03-05 22:13
It seems to happen with an even simpler program that imports `net/http` for side-effects only. For example, I'm getting a "timeout running go build" when trying to run:

```Go
package main

import (
	_ "fmt"
	_ "net/http"
)

func main() {
	fmt.Println("output")
}
```

Instead of the expected build error like "./prog.go:8:2: undefined: fmt".

CC @golang/release.

**Comment by toothrot** [comment] 2021-03-08 18:30
It's possible that our changes in #44714 and #44389 caused longer compilation times due to differences in what is considered stale now. We might have to increase the compilation timeout to account for this.

**Comment by 89z** [comment] 2021-04-21 19:00
closing for lack of interest

**Comment by toothrot** [comment] 2021-04-22 14:54
I am going to re-open this. I want to fix it, but have been busy with other things.

**Comment by toothrot** [comment] 2021-04-22 14:56
@89z FYI, the linked snippet does pass for me after our changes, but still occasionally fails: https://play.golang.org/p/nf79uLXs5-b

Modules by default impacted our caching strategy for dependencies on the playground, and we've not figured out the best way to resolve that yet.

**Comment by awmyowin** [comment] 2021-04-29 22:46
> It's possible that our changes in #44714 and #44389 caused longer compilation times due to differences in what is considered stale now. We might have to increase the compilation timeout to account for this.

**Comment by 89z** [comment] 2021-05-27 01:06
closing for lack of interest

**Comment by 89z** [comment] 2021-07-23 15:28
I closed this for a reason. That reason, hasnt changed. Please open a new issue, if you feel so inclined.

**Comment by cespare** [comment] 2021-07-23 18:56
@89z seems like you identified a real problem which the team is putting real effort into fixing. Ongoing bugs should be tracked by open issues; therefore, I don't see why we should close this issue until the problem is fixed (which seems imminent). If you "lack interest" in this issue, you are welcome to just stop interacting with it.

Additionally, multiple merged and in-progress CLs already reference this issue number, so switching to a new issue now just makes the history harder to follow.

**Comment by 89z** [comment] 2021-07-23 19:05
@cespare OK fair enough. I respect you because of your comments on Go generics, so whatever you say.

**Comment by ianlancetaylor** [comment] 2021-07-23 19:06
@89z You should be able to click on the "Unsubscribe" button over on the right if you no longer care about this issue.  Thanks.

**Comment by toothrot** [comment] 2021-07-23 20:21
The playground should deploy shortly, and I'll update here after verifying this was fixed.

**Closed** 2021-07-23 20:20 UTC
Labels: NeedsInvestigation

**Comment by toothrot** [comment] 2021-07-23 20:47
It worked! Thanks for reporting @89z.
