### ISSUE TITLE
cmd/go: reuses cached build affected by -ldflags and -X

### ISSUE THREAD

**Issue by willfaught** [golang/go#18970] opened 2017-02-07 00:11 UTC
### What version of Go are you using (`go version`)?

```
go version go1.7.5 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/will.faught/Developer/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.5/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.5/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jt/c0hjffqj6gxbhy00gm0btzkr79h225/T/go-build129389905=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

### What did you do?

```sh
$ cd mymainpackage
$ go install -ldflags "-X github.com/foo/bar.Version=123"
$ mymainpackage --version # prints github.com/foo/bar.Version
123
$ go install -ldflags "-X github.com/foo/bar.Version=456" # 456 instead of 123
$ mymainpackage --version
```

### What did you expect to see?

```sh
456
```

### What did you see instead?

```sh
123
```

**Comment by davecheney** [comment] 2017-02-07 00:14
Use go install -v to check that the program is being rebuilt (or just check
the timestamps). My suspicion is the binary has not been rebuilt.

**Comment by minux** [comment] 2017-02-07 01:48
Solving this issue essentially requires that, either:
1. cmd/go saves a copy of the all linker command line flags in the binary,
or
2. always rebuild the binary.

I think neither is satisfactory.

**Comment by rakyll** [comment] 2017-02-07 19:37
Duplicate of https://github.com/golang/go/issues/18369.

**Closed by rakyll** 2017-02-07 19:37 UTC
