### ISSUE TITLE
go/doc: Mix of unexported and exported fields leads to spurious blank lines in godoc

### ISSUE THREAD

**Issue by alercah** [golang/go#20061] opened 2017-04-21 04:14 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
N/A (production version of godoc.org)

### What operating system and processor architecture are you using (`go env`)?
N/A

### What did you do?

My package's [City][https://github.com/alercah/wonderbot/blob/master/wonders/city.go#L19] struct contains a mix of exported and unexported fields, arranged logically rather than grouping the exported fields together.

In the [documentation][https://godoc.org/github.com/alercah/wonderbot/wonders#City], blank lines are generated in between exported fields when an unexported field intervenes.

Similarly, [Action][https://github.com/alercah/wonderbot/blob/master/wonders/action.go#L8] has one unexported field, at the beginning of the struct. The [documentation][https://godoc.org/github.com/alercah/wonderbot/wonders#Action] includes a blank line at the start of the struct.

### What did you expect to see?

There should be no blank lines in the godoc version of the struct. Alternatively, if this is a style rule, there should be a lint check for it

**Comment by dsnet** [comment] 2017-04-21 17:18
Thanks for filing. This is a dupe of #18264

**Closed by dsnet** 2017-04-21 17:18 UTC
