### ISSUE TITLE
groutine is not run with for block

### ISSUE THREAD

**Issue by HOTDARK** [golang/go#48415] opened 2021-09-16 07:57 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/code/go/pkg/mod"
GONOPROXY="git.ghostcloud.cn"
GONOSUMDB="git.ghostcloud.cn"
GOOS="linux"
GOPATH="/root/code/go"
GOPRIVATE="git.ghostcloud.cn"
GOPROXY="https://goproxy.cn"
GOROOT="/root/app/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/app/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3112287996=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
package main

import (
	"fmt"
	"time"
)

func main() {
	var count int16

	go func() {
		for {
			count = count + 1
		}
	}()

	time.Sleep(time.Second)
	fmt.Println(count)
}
```

### What did you expect to see?
i want variable count increase

### What did you see instead?
count is not change

**Comment by ALTree** [comment] 2021-09-16 09:11
You can't access a shared variable like that without locking, your program has a data race on `count`:

```
$ go run -race test.go

==================
WARNING: DATA RACE
Read at 0x00c0000160a8 by main goroutine:
  main.main()
      D:/users/f65362c/alberto/test.go:18 +0xa4

Previous write at 0x00c0000160a8 by goroutine 7:
  main.main.func1()
      D:/users/f65362c/alberto/test.go:13 +0x5a

Goroutine 7 (running) created at:
  main.main()
      D:/users/f65362c/alberto/test.go:11 +0x84
==================
22982
Found 1 data race(s)
exit status 66
```

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions) if you have further questions.

Closing here since this is not a bug in Go.

**Closed by ALTree** 2021-09-16 09:11 UTC

**Comment by PandyYang** [comment] 2021-09-16 09:19
when i add print sentence or some else like sleep 1 second, some thing changed. go routinue running and the var increase.
it means main preocess is finished? so it does't to run the single count++. 
```
func main() {
	var count uint8

	go func() {
		for {
			count = count + 1
			//time.Sleep(time.Second)
			//count = count + 1
			fmt.Println(count)
		}
	}()

	time.Sleep(time.Second)
	fmt.Println("------------------------")
	fmt.Println(count)
}
```

**Comment by ALTree** [comment] 2021-09-16 09:25
A Go program with a data race in it is not valid, and no amount of sleeping will fix that. The compile is allowed to assume no races, and it may not generate the code you're expecting.

Suggested reading: https://go.dev/blog/race-detector

**Comment by ianlancetaylor** [comment] 2021-09-16 18:09
In general Go programs do not behave well with busy loops.

That said, the way to write this kind of program is to use the sync/atomic package.
