### ISSUE TITLE
x/tools/cmd/gopls: no CheckPackageHandles for file

### ISSUE THREAD

**Issue by kevinburkemeter** [golang/go#35081] opened 2019-10-22 17:33 UTC
1. Compile Go at tip (51504f0a2d65a7f7fcf63c25c2cb306a6863d07d)
2. Compile x/tools at tip (0bb5a05de81d0029e2aac6a6c97b991de96bbf77). My x/tools lives in $GOPATH/src/golang.org/x/tools but I compiled by running `GO111MODULE=on go install -v ./...`.
3. Download github.com/jmhodges/justrun to `$GOPATH/src/github.com/jmhodges/justrun`
4. Open watch.go in vim and call `:GoDef` while the cursor is on `NewWatcher`.

If I have `GO111MODULE=on` for step 4 I get the definition, as expected - if it is off, I get "no CheckPackageHandles for file /path/to/watch.go."

I am also having trouble figuring out how to export logs, I can start vim-go with these settings:

```
let g:go_debug = ['lsp']
let g:go_debug_log_output = 'debugger,rpc'
```

but the window at the bottom with gopls log messages scrolls off of the right edge of my screen, and it's not clear if they are also being written to a log file somewhere.

**Comment by kevinburkemeter** [comment] 2019-10-22 17:35
Following the troubleshooting guide:

> For instance, :GoReportGitHubIssue in vim-go.

Running that command yields:

```
E492: Not an editor command: GoReportGithubIssue
```

**Comment by kevinburkemeter** [comment] 2019-10-22 17:35
Oh, ugh, I typed it as `GoReportGithubIssue` the first time.

**Comment by kevinburkemeter** [comment] 2019-10-22 17:36
```
</pre></details>
#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_list_type = 'quickfix'
g:go_fmt_autosave = 1
g:go_debug = ['lsp']
g:go_debug_log_output = 'debugger,rpc'
g:go_test_timeout = '2s'
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>
```

**Comment by stamblerre** [comment] 2019-10-22 19:08
Can you share the output of `gopls -rpc.trace -v check path/to/watch.go`?

**Comment by kevinburkemeter** [comment] 2019-10-22 19:24
https://gist.github.com/kevinburkemeter/482c46a6431d0cf26bde3af294f25b30

**Comment by kevinburkemeter** [comment] 2019-10-22 19:26
I'm realizing now that $GOPATH/src/github.com/fsnotify/fsnotify doesn't exist. I didn't previously notice this because I usually run justrun in projects that have vendored all dependencies.

Still, it seems like we could present a better error message here besides "no CheckPackageHandles."

**Comment by stamblerre** [comment] 2019-10-22 19:57
Did that error message come up when you tried to go to the definition of the unknown variable?

**Comment by kevinburkemeter** [comment] 2019-10-22 20:09
Yes - when I hovered over "NewWatcher" in watch.go and hit `:GoDef` in vim

**Comment by stamblerre** [comment] 2019-10-22 20:11
Did it say "no CheckPackageHandles" for the nonexistent package or for the entire package?

**Comment by kevinburkemeter** [comment] 2019-10-22 20:21
Here's what's in the vim log:

```
received: Content-Length: 327^M^@^M^@{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/10/22 13:21:21 18.838018ms for GOROOT=/Users/kevin/go GOPATH=/Users/kevin GO111MODULE=off PWD=/Users/kevin/src/github.com/jmhodges/justrun go \"env\
  8 received: Content-Length: 129256^M^@^M^@{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/10/22 13:21:21 129.449606ms for GOROOT=/Users/kevin/go GOPATH=/Users/kevin GO111MODULE=off PWD=/Users/kevin/src/github.com/jmhodges/justrun go \"
  7 received: Content-Length: 131^M^@^M^@{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/10/22 13:21:21 go/packages.Load\n\tpackages = 2"}}¬
  6 received: Content-Length: 391^M^@^M^@{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/10/22 13:21:21 go/packages.Load\n\tpackage = github.com/jmhodges/justrun\n\tfiles = [/Users/kevin/src/github.com/jmhodges/justrun/cmdwrap.go /Users/
  5 received: Content-Length: 452^M^@^M^@{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/10/22 13:21:21 go/packages.Load\n\tpackage = github.com/jmhodges/justrun\n\tfiles = [/Users/kevin/src/github.com/jmhodges/justrun/cmdwrap.go /Users/
  4 received: Content-Length: 129256^M^@^M^@{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/10/22 13:21:21 132.234713ms for GOROOT=/Users/kevin/go GOPATH=/Users/kevin GO111MODULE=off PWD=/Users/kevin/src/github.com/jmhodges/justrun go \"
  3 received: Content-Length: 131^M^@^M^@{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/10/22 13:21:21 go/packages.Load\n\tpackages = 2"}}¬
  2 received: Content-Length: 391^M^@^M^@{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/10/22 13:21:21 go/packages.Load\n\tpackage = github.com/jmhodges/justrun\n\tfiles = [/Users/kevin/src/github.com/jmhodges/justrun/cmdwrap.go /Users/
  1 received: Content-Length: 452^M^@^M^@{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2019/10/22 13:21:21 go/packages.Load\n\tpackage = github.com/jmhodges/justrun\n\tfiles = [/Users/kevin/src/github.com/jmhodges/justrun/cmdwrap.go /Users/
  0 received: Content-Length: 155^M^@^M^@{"jsonrpc":"2.0","error":{"code":0,"message":"no CheckPackageHandles for file:///Users/kevin/src/github.com/jmhodges/justrun/watch.go","data":null},"id":2}¬
```

**Comment by stamblerre** [comment] 2019-10-22 20:35
Ok, so I'm thinking that this sounds very similar to https://github.com/golang/go/issues/34012, in that an import failing to resolve causes all language features to fail. I will then close this as a duplicate.

**Comment by stamblerre** [comment] 2019-10-22 20:35
Duplicate of https://github.com/golang/go/issues/34012

**Closed by stamblerre** 2019-10-22 20:35 UTC
Labels: Tools, gopls

**Comment by kevinburkemeter** [comment] 2019-10-22 20:36
OK, thank you for investigating.
