### ISSUE TITLE
net/rpc: zero value not transmitted

### ISSUE THREAD

**Issue by jxq96** [golang/go#50075] opened 2021-12-09 17:35 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version 
go1.16.4 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/jxq/go/bin"
GOCACHE="/home/jxq/.cache/go-build"
GOENV="/home/jxq/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jxq/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jxq/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jxq/codes/learn/go-rpc-demo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4245741333=/tmp/go-build -gno-record-gcc-switches"</summary><br><pre>
$ go env
</pre></details>

### What did you do?

details are in my demo repo: https://github.com/jxq96/go-rpc-demo

### What did you expect to see?

details are in my demo repo: https://github.com/jxq96/go-rpc-demo

### What did you see instead?

details are in my demo repo: https://github.com/jxq96/go-rpc-demo

**Comment by seankhliao** [comment] 2021-12-09 17:45
Duplicate of #8997

**Closed by seankhliao** 2021-12-09 17:45 UTC
