### ISSUE TITLE
modules: go mod vendor does not fulfill all dependencies

### ISSUE THREAD

**Issue by swtch1** [golang/go#27006] opened 2018-08-15 19:06 UTC
### What version of Go are you using (`go version`)?
`go version devel +c882f4b Tue Aug 14 20:40:15 2018 +0000 linux/amd64`

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```bash
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/"
GOPROXY=""
GORACE=""
GOROOT="/root/go"
GOTMPDIR=""
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/code/pcf_config_generator/pcfconfgen/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build807523319=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?
```bash
$ cat vendor/github.com/prometheus/prometheus/discovery/azure/azure.go | grep /Azure/
        "github.com/Azure/azure-sdk-for-go/arm/compute"
        "github.com/Azure/azure-sdk-for-go/arm/network"
        "github.com/Azure/go-autorest/autorest/azure"
```
```
$ go mod tidy -v
Fetching https://k8s.io/client-go/pkg/api?go-get=1
Fetching https://k8s.io/client-go/pkg/api/v1?go-get=1
Fetching https://k8s.io/client-go/pkg/apis/extensions/v1beta1?go-get=1
Fetching https://labix.org/v2/mgo/bson?go-get=1
go: finding github.com/Azure/azure-sdk-for-go/arm/network latest
go: finding github.com/Azure/azure-sdk-for-go/arm/compute latest
go: finding github.com/Azure/azure-sdk-for-go/arm latest
Fetching https://github.com?go-get=1
Parsing meta tags from https://k8s.io/client-go/pkg/apis/extensions/v1beta1?go-get=1 (status code 200)
get "k8s.io/client-go/pkg/apis/extensions/v1beta1": found meta tag get.metaImport{Prefix:"k8s.io/client-go", VCS:"git", RepoRoot:"https://github.com/kubernetes/client-go"} at https://k8s.io/client-go/pkg/apis/extensions/v1beta1?go-get=1
get "k8s.io/client-go/pkg/apis/extensions/v1beta1": verifying non-authoritative meta tag
Fetching https://k8s.io/client-go?go-get=1
Parsing meta tags from https://k8s.io/client-go/pkg/api/v1?go-get=1 (status code 200)
get "k8s.io/client-go/pkg/api/v1": found meta tag get.metaImport{Prefix:"k8s.io/client-go", VCS:"git", RepoRoot:"https://github.com/kubernetes/client-go"} at https://k8s.io/client-go/pkg/api/v1?go-get=1
get "k8s.io/client-go/pkg/api/v1": verifying non-authoritative meta tag
Parsing meta tags from https://k8s.io/client-go/pkg/api?go-get=1 (status code 200)
get "k8s.io/client-go/pkg/api": found meta tag get.metaImport{Prefix:"k8s.io/client-go", VCS:"git", RepoRoot:"https://github.com/kubernetes/client-go"} at https://k8s.io/client-go/pkg/api?go-get=1
get "k8s.io/client-go/pkg/api": verifying non-authoritative meta tag
Parsing meta tags from https://k8s.io/client-go?go-get=1 (status code 200)
Parsing meta tags from https://github.com?go-get=1 (status code 200)
Parsing meta tags from https://labix.org/v2/mgo/bson?go-get=1 (status code 200)
get "labix.org/v2/mgo/bson": found meta tag get.metaImport{Prefix:"labix.org/v2/mgo", VCS:"bzr", RepoRoot:"https://launchpad.net/mgo/v2"} at https://labix.org/v2/mgo/bson?go-get=1
get "labix.org/v2/mgo/bson": verifying non-authoritative meta tag
Fetching https://labix.org/v2/mgo?go-get=1
go: finding k8s.io/client-go/pkg/api latest
go: finding k8s.io/client-go/pkg/apis/extensions/v1beta1 latest
Fetching https://k8s.io/client-go/pkg?go-get=1
Fetching https://k8s.io/client-go/pkg/apis/extensions?go-get=1
Parsing meta tags from https://k8s.io/client-go/pkg?go-get=1 (status code 200)
get "k8s.io/client-go/pkg": found meta tag get.metaImport{Prefix:"k8s.io/client-go", VCS:"git", RepoRoot:"https://github.com/kubernetes/client-go"} at https://k8s.io/client-go/pkg?go-get=1
get "k8s.io/client-go/pkg": verifying non-authoritative meta tag
go: finding k8s.io/client-go/pkg latest
Parsing meta tags from https://k8s.io/client-go/pkg/apis/extensions?go-get=1 (status code 200)
get "k8s.io/client-go/pkg/apis/extensions": found meta tag get.metaImport{Prefix:"k8s.io/client-go", VCS:"git", RepoRoot:"https://github.com/kubernetes/client-go"} at https://k8s.io/client-go/pkg/apis/extensions?go-get=1
get "k8s.io/client-go/pkg/apis/extensions": verifying non-authoritative meta tag
go: finding k8s.io/client-go/pkg/apis/extensions latest
Fetching https://k8s.io/client-go?go-get=1
Fetching https://k8s.io/client-go/pkg/apis?go-get=1
Parsing meta tags from https://k8s.io/client-go?go-get=1 (status code 200)
get "k8s.io/client-go": found meta tag get.metaImport{Prefix:"k8s.io/client-go", VCS:"git", RepoRoot:"https://github.com/kubernetes/client-go"} at https://k8s.io/client-go?go-get=1
Parsing meta tags from https://k8s.io/client-go/pkg/apis?go-get=1 (status code 200)
get "k8s.io/client-go/pkg/apis": found meta tag get.metaImport{Prefix:"k8s.io/client-go", VCS:"git", RepoRoot:"https://github.com/kubernetes/client-go"} at https://k8s.io/client-go/pkg/apis?go-get=1
get "k8s.io/client-go/pkg/apis": verifying non-authoritative meta tag
go: finding k8s.io/client-go/pkg/apis latest
Fetching https://k8s.io?go-get=1
Parsing meta tags from https://k8s.io?go-get=1 (status code 200)
Parsing meta tags from https://labix.org/v2/mgo?go-get=1 (status code 200)
Fetching https://labix.org/v2/mgo?go-get=1
Parsing meta tags from https://labix.org/v2/mgo?go-get=1 (status code 200)
get "labix.org/v2/mgo": found meta tag get.metaImport{Prefix:"labix.org/v2/mgo", VCS:"bzr", RepoRoot:"https://launchpad.net/mgo/v2"} at https://labix.org/v2/mgo?go-get=1
Fetching https://labix.org/v2?go-get=1
Parsing meta tags from https://labix.org/v2?go-get=1 (status code 404)
Fetching https://labix.org?go-get=1
Parsing meta tags from https://labix.org?go-get=1 (status code 200)
```
```bash
$ go mod vendor -v
Fetching https://k8s.io/client-go/pkg/apis/extensions/v1beta1?go-get=1
Fetching https://k8s.io/client-go/pkg/api?go-get=1
Fetching https://k8s.io/client-go/pkg/api/v1?go-get=1
go: finding github.com/Azure/azure-sdk-for-go/arm/network latest
go: finding github.com/Azure/azure-sdk-for-go/arm/compute latest
go: finding github.com/Azure/azure-sdk-for-go/arm latest
Fetching https://github.com?go-get=1
Parsing meta tags from https://k8s.io/client-go/pkg/apis/extensions/v1beta1?go-get=1 (status code 200)
get "k8s.io/client-go/pkg/apis/extensions/v1beta1": found meta tag get.metaImport{Prefix:"k8s.io/client-go", VCS:"git", RepoRoot:"https://github.com/kubernetes/client-go"} at https://k8s.io/client-go/pkg/apis/extensions/v1beta1?go-get=1
get "k8s.io/client-go/pkg/apis/extensions/v1beta1": verifying non-authoritative meta tag
Fetching https://k8s.io/client-go?go-get=1
Parsing meta tags from https://k8s.io/client-go/pkg/api/v1?go-get=1 (status code 200)
get "k8s.io/client-go/pkg/api/v1": found meta tag get.metaImport{Prefix:"k8s.io/client-go", VCS:"git", RepoRoot:"https://github.com/kubernetes/client-go"} at https://k8s.io/client-go/pkg/api/v1?go-get=1
get "k8s.io/client-go/pkg/api/v1": verifying non-authoritative meta tag
Parsing meta tags from https://k8s.io/client-go/pkg/api?go-get=1 (status code 200)
get "k8s.io/client-go/pkg/api": found meta tag get.metaImport{Prefix:"k8s.io/client-go", VCS:"git", RepoRoot:"https://github.com/kubernetes/client-go"} at https://k8s.io/client-go/pkg/api?go-get=1
get "k8s.io/client-go/pkg/api": verifying non-authoritative meta tag
Parsing meta tags from https://k8s.io/client-go?go-get=1 (status code 200)
Parsing meta tags from https://github.com?go-get=1 (status code 200)
go: finding k8s.io/client-go/pkg/apis/extensions/v1beta1 latest
go: finding k8s.io/client-go/pkg/api latest
Fetching https://k8s.io/client-go/pkg/apis/extensions?go-get=1
Fetching https://k8s.io/client-go/pkg?go-get=1
Parsing meta tags from https://k8s.io/client-go/pkg?go-get=1 (status code 200)
get "k8s.io/client-go/pkg": found meta tag get.metaImport{Prefix:"k8s.io/client-go", VCS:"git", RepoRoot:"https://github.com/kubernetes/client-go"} at https://k8s.io/client-go/pkg?go-get=1
get "k8s.io/client-go/pkg": verifying non-authoritative meta tag
go: finding k8s.io/client-go/pkg latest
Parsing meta tags from https://k8s.io/client-go/pkg/apis/extensions?go-get=1 (status code 200)
get "k8s.io/client-go/pkg/apis/extensions": found meta tag get.metaImport{Prefix:"k8s.io/client-go", VCS:"git", RepoRoot:"https://github.com/kubernetes/client-go"} at https://k8s.io/client-go/pkg/apis/extensions?go-get=1
get "k8s.io/client-go/pkg/apis/extensions": verifying non-authoritative meta tag
go: finding k8s.io/client-go/pkg/apis/extensions latest
Fetching https://k8s.io/client-go?go-get=1
Fetching https://k8s.io/client-go/pkg/apis?go-get=1
Parsing meta tags from https://k8s.io/client-go?go-get=1 (status code 200)
get "k8s.io/client-go": found meta tag get.metaImport{Prefix:"k8s.io/client-go", VCS:"git", RepoRoot:"https://github.com/kubernetes/client-go"} at https://k8s.io/client-go?go-get=1
Parsing meta tags from https://k8s.io/client-go/pkg/apis?go-get=1 (status code 200)
get "k8s.io/client-go/pkg/apis": found meta tag get.metaImport{Prefix:"k8s.io/client-go", VCS:"git", RepoRoot:"https://github.com/kubernetes/client-go"} at https://k8s.io/client-go/pkg/apis?go-get=1
get "k8s.io/client-go/pkg/apis": verifying non-authoritative meta tag
go: finding k8s.io/client-go/pkg/apis latest
Fetching https://k8s.io?go-get=1
Parsing meta tags from https://k8s.io?go-get=1 (status code 200)
# cloud.google.com/go v0.26.0
cloud.google.com/go/compute/metadata
# github.com/Azure/go-autorest v10.15.2+incompatible
github.com/Azure/go-autorest/autorest/azure
github.com/Azure/go-autorest/autorest
github.com/Azure/go-autorest/autorest/adal
github.com/Azure/go-autorest/logger
github.com/Azure/go-autorest/version
github.com/Azure/go-autorest/autorest/date
# github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
github.com/alecthomas/template
github.com/alecthomas/template/parse
# github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
github.com/alecthomas/units
# github.com/aws/aws-sdk-go v1.15.11
github.com/aws/aws-sdk-go/aws
github.com/aws/aws-sdk-go/aws/credentials
github.com/aws/aws-sdk-go/aws/credentials/stscreds
github.com/aws/aws-sdk-go/aws/ec2metadata
github.com/aws/aws-sdk-go/aws/session
github.com/aws/aws-sdk-go/service/ec2
github.com/aws/aws-sdk-go/aws/awserr
github.com/aws/aws-sdk-go/aws/endpoints
github.com/aws/aws-sdk-go/internal/sdkio
github.com/aws/aws-sdk-go/internal/shareddefaults
github.com/aws/aws-sdk-go/aws/client
github.com/aws/aws-sdk-go/service/sts
github.com/aws/aws-sdk-go/aws/client/metadata
github.com/aws/aws-sdk-go/aws/corehandlers
github.com/aws/aws-sdk-go/aws/request
github.com/aws/aws-sdk-go/internal/sdkuri
github.com/aws/aws-sdk-go/aws/csm
github.com/aws/aws-sdk-go/aws/defaults
github.com/aws/aws-sdk-go/aws/awsutil
github.com/aws/aws-sdk-go/aws/signer/v4
github.com/aws/aws-sdk-go/internal/sdkrand
github.com/aws/aws-sdk-go/private/protocol
github.com/aws/aws-sdk-go/private/protocol/ec2query
github.com/aws/aws-sdk-go/private/protocol/query
github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds
github.com/aws/aws-sdk-go/aws/credentials/endpointcreds
github.com/aws/aws-sdk-go/private/protocol/rest
github.com/aws/aws-sdk-go/private/protocol/query/queryutil
github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil
# github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
github.com/beorn7/perks/quantile
# github.com/cespare/xxhash v1.0.0
github.com/cespare/xxhash
# github.com/davecgh/go-spew v1.1.0
github.com/davecgh/go-spew/spew
# github.com/dgrijalva/jwt-go v3.2.0+incompatible
github.com/dgrijalva/jwt-go
# github.com/fsnotify/fsnotify v1.4.7
github.com/fsnotify/fsnotify
# github.com/ghodss/yaml v1.0.0
github.com/ghodss/yaml
# github.com/go-ini/ini v1.25.4
github.com/go-ini/ini
# github.com/go-kit/kit v0.7.0
github.com/go-kit/kit/log
github.com/go-kit/kit/log/level
# github.com/go-logfmt/logfmt v0.3.0
github.com/go-logfmt/logfmt
# github.com/go-stack/stack v1.7.0
github.com/go-stack/stack
# github.com/gogo/protobuf v1.1.1
github.com/gogo/protobuf/proto
github.com/gogo/protobuf/sortkeys
# github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
github.com/golang/glog
# github.com/golang/protobuf v1.1.0
github.com/golang/protobuf/proto
github.com/golang/protobuf/ptypes/any
github.com/golang/protobuf/ptypes
github.com/golang/protobuf/ptypes/duration
github.com/golang/protobuf/ptypes/timestamp
# github.com/google/btree v0.0.0-20180813153112-4030bb1f1f0c
github.com/google/btree
# github.com/google/gofuzz v0.0.0-20170612174753-24818f796faf
github.com/google/gofuzz
# github.com/googleapis/gnostic v0.2.0
github.com/googleapis/gnostic/OpenAPIv2
github.com/googleapis/gnostic/compiler
github.com/googleapis/gnostic/extensions
# github.com/gophercloud/gophercloud v0.0.0-20180814033650-69b1773a4cfb
github.com/gophercloud/gophercloud
github.com/gophercloud/gophercloud/openstack
github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/floatingips
github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/hypervisors
github.com/gophercloud/gophercloud/openstack/compute/v2/servers
github.com/gophercloud/gophercloud/pagination
github.com/gophercloud/gophercloud/openstack/identity/v2/tokens
github.com/gophercloud/gophercloud/openstack/identity/v3/tokens
github.com/gophercloud/gophercloud/openstack/utils
github.com/gophercloud/gophercloud/openstack/compute/v2/flavors
github.com/gophercloud/gophercloud/openstack/compute/v2/images
github.com/gophercloud/gophercloud/openstack/identity/v2/tenants
# github.com/gregjones/httpcache v0.0.0-20180305231024-9cad4c3443a7
github.com/gregjones/httpcache
github.com/gregjones/httpcache/diskcache
# github.com/hashicorp/consul v1.2.2
github.com/hashicorp/consul/api
# github.com/hashicorp/go-cleanhttp v0.0.0-20171218145408-d5fe4b57a186
github.com/hashicorp/go-cleanhttp
# github.com/hashicorp/go-rootcerts v0.0.0-20160503143440-6bb64b370b90
github.com/hashicorp/go-rootcerts
# github.com/hashicorp/golang-lru v0.0.0-20180201235237-0fb14efe8c47
github.com/hashicorp/golang-lru
github.com/hashicorp/golang-lru/simplelru
# github.com/hashicorp/hcl v0.0.0-20180404174102-ef8a98b0bbce
github.com/hashicorp/hcl
github.com/hashicorp/hcl/hcl/printer
github.com/hashicorp/hcl/hcl/ast
github.com/hashicorp/hcl/hcl/parser
github.com/hashicorp/hcl/hcl/token
github.com/hashicorp/hcl/json/parser
github.com/hashicorp/hcl/hcl/scanner
github.com/hashicorp/hcl/hcl/strconv
github.com/hashicorp/hcl/json/scanner
github.com/hashicorp/hcl/json/token
# github.com/hashicorp/serf v0.8.1
github.com/hashicorp/serf/coordinate
# github.com/jmespath/go-jmespath v0.0.0-20160202185014-0b12d6b521d8
github.com/jmespath/go-jmespath
# github.com/json-iterator/go v0.0.0-20180806060727-1624edc4454b
github.com/json-iterator/go
# github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515
github.com/kr/logfmt
# github.com/magiconair/properties v1.8.0
github.com/magiconair/properties
# github.com/matttproud/golang_protobuf_extensions v1.0.1
github.com/matttproud/golang_protobuf_extensions/pbutil
# github.com/miekg/dns v1.0.8
github.com/miekg/dns
# github.com/mitchellh/go-homedir v0.0.0-20180801233206-58046073cbff
github.com/mitchellh/go-homedir
# github.com/mitchellh/mapstructure v0.0.0-20180715050151-f15292f7a699
github.com/mitchellh/mapstructure
# github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
github.com/modern-go/concurrent
# github.com/modern-go/reflect2 v0.0.0-20180718012357-94122c33edd3
github.com/modern-go/reflect2
# github.com/mwitkow/go-conntrack v0.0.0-20161129095857-cc309e4a2223
github.com/mwitkow/go-conntrack
# github.com/nbio/st v0.0.0-20140626010706-e9e8d9816f32
github.com/nbio/st
# github.com/oklog/ulid v1.0.0
github.com/oklog/ulid
# github.com/opentracing/opentracing-go v1.0.2
github.com/opentracing/opentracing-go
github.com/opentracing/opentracing-go/log
# github.com/pelletier/go-toml v1.2.0
github.com/pelletier/go-toml
# github.com/peterbourgon/diskv v2.0.1+incompatible
github.com/peterbourgon/diskv
# github.com/pkg/errors v0.8.0
github.com/pkg/errors
# github.com/prometheus/client_golang v0.8.0
github.com/prometheus/client_golang/prometheus
# github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
github.com/prometheus/client_model/go
# github.com/prometheus/common v0.0.0-20180801064454-c7de2306084e
github.com/prometheus/common/model
github.com/prometheus/common/config
github.com/prometheus/common/expfmt
github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg
# github.com/prometheus/procfs v0.0.0-20180725123919-05ee40e3a273
github.com/prometheus/procfs
github.com/prometheus/procfs/nfs
github.com/prometheus/procfs/xfs
github.com/prometheus/procfs/internal/util
# github.com/prometheus/prometheus v2.3.2+incompatible
github.com/prometheus/prometheus/pkg/rulefmt
github.com/prometheus/prometheus/config
github.com/prometheus/prometheus/discovery/config
github.com/prometheus/prometheus/discovery/file
github.com/prometheus/prometheus/promql
github.com/prometheus/prometheus/discovery/azure
github.com/prometheus/prometheus/discovery/consul
github.com/prometheus/prometheus/discovery/dns
github.com/prometheus/prometheus/discovery/ec2
github.com/prometheus/prometheus/discovery/gce
github.com/prometheus/prometheus/discovery/kubernetes
github.com/prometheus/prometheus/discovery/marathon
github.com/prometheus/prometheus/discovery/openstack
github.com/prometheus/prometheus/discovery/targetgroup
github.com/prometheus/prometheus/discovery/triton
github.com/prometheus/prometheus/discovery/zookeeper
github.com/prometheus/prometheus/pkg/labels
github.com/prometheus/prometheus/pkg/textparse
github.com/prometheus/prometheus/pkg/timestamp
github.com/prometheus/prometheus/pkg/value
github.com/prometheus/prometheus/storage
github.com/prometheus/prometheus/util/stats
github.com/prometheus/prometheus/util/strutil
github.com/prometheus/prometheus/util/testutil
github.com/prometheus/prometheus/util/treecache
github.com/prometheus/prometheus/storage/tsdb
# github.com/prometheus/tsdb v0.0.0-20180807144027-eeb3a7435a75
github.com/prometheus/tsdb
github.com/prometheus/tsdb/labels
github.com/prometheus/tsdb/chunkenc
github.com/prometheus/tsdb/chunks
github.com/prometheus/tsdb/fileutil
github.com/prometheus/tsdb/index
github.com/prometheus/tsdb/wal
# github.com/samuel/go-zookeeper v0.0.0-20180130194729-c4fab1ac1bec
github.com/samuel/go-zookeeper/zk
# github.com/sirupsen/logrus v1.0.6
github.com/sirupsen/logrus
# github.com/spf13/afero v1.1.1
github.com/spf13/afero
github.com/spf13/afero/mem
# github.com/spf13/cast v1.2.0
github.com/spf13/cast
# github.com/spf13/jwalterweatherman v0.0.0-20180814060501-14d3d4c51834
github.com/spf13/jwalterweatherman
# github.com/spf13/pflag v1.0.2
github.com/spf13/pflag
# github.com/spf13/viper v1.1.0
github.com/spf13/viper
# golang.org/x/crypto v0.0.0-20180808211826-de0752318171
golang.org/x/crypto/ssh/terminal
golang.org/x/crypto/ed25519
golang.org/x/crypto/ed25519/internal/edwards25519
# golang.org/x/net v0.0.0-20180811021610-c39426892332
golang.org/x/net/trace
golang.org/x/net/context
golang.org/x/net/internal/timeseries
golang.org/x/net/ipv4
golang.org/x/net/ipv6
golang.org/x/net/context/ctxhttp
golang.org/x/net/http2
golang.org/x/net/bpf
golang.org/x/net/internal/iana
golang.org/x/net/internal/socket
golang.org/x/net/http/httpguts
golang.org/x/net/http2/hpack
golang.org/x/net/idna
# golang.org/x/oauth2 v0.0.0-20180724155351-3d292e4d0cdc
golang.org/x/oauth2
golang.org/x/oauth2/google
golang.org/x/oauth2/internal
golang.org/x/oauth2/jws
golang.org/x/oauth2/jwt
# golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
golang.org/x/sync/errgroup
# golang.org/x/sys v0.0.0-20180814072032-4e1fef560951
golang.org/x/sys/unix
golang.org/x/sys/windows
# golang.org/x/text v0.3.0
golang.org/x/text/transform
golang.org/x/text/unicode/norm
golang.org/x/text/secure/bidirule
golang.org/x/text/unicode/bidi
# golang.org/x/time v0.0.0-20180412165947-fbb02b2291d2
golang.org/x/time/rate
# google.golang.org/api v0.0.0-20180814000510-0e8d13b5c025
google.golang.org/api/compute/v1
google.golang.org/api/gensupport
google.golang.org/api/googleapi
google.golang.org/api/googleapi/internal/uritemplates
# google.golang.org/appengine v1.1.0
google.golang.org/appengine
google.golang.org/appengine/urlfetch
google.golang.org/appengine/internal
google.golang.org/appengine/internal/app_identity
google.golang.org/appengine/internal/modules
google.golang.org/appengine/internal/urlfetch
google.golang.org/appengine/internal/base
google.golang.org/appengine/internal/datastore
google.golang.org/appengine/internal/log
google.golang.org/appengine/internal/remote_api
# gopkg.in/alecthomas/kingpin.v2 v2.2.6
gopkg.in/alecthomas/kingpin.v2
# gopkg.in/fsnotify/fsnotify.v1 v1.4.7
gopkg.in/fsnotify/fsnotify.v1
# gopkg.in/inf.v0 v0.9.1
gopkg.in/inf.v0
# gopkg.in/yaml.v2 v2.2.1
gopkg.in/yaml.v2
# k8s.io/api v0.0.0-20180809133242-91bfdbcf0c2c
k8s.io/api/admissionregistration/v1alpha1
k8s.io/api/admissionregistration/v1beta1
k8s.io/api/apps/v1
k8s.io/api/apps/v1beta1
k8s.io/api/apps/v1beta2
k8s.io/api/authentication/v1
k8s.io/api/authentication/v1beta1
k8s.io/api/authorization/v1
k8s.io/api/authorization/v1beta1
k8s.io/api/autoscaling/v1
k8s.io/api/autoscaling/v2beta1
k8s.io/api/batch/v1
k8s.io/api/batch/v1beta1
k8s.io/api/batch/v2alpha1
k8s.io/api/certificates/v1beta1
k8s.io/api/core/v1
k8s.io/api/extensions/v1beta1
k8s.io/api/policy/v1beta1
k8s.io/api/events/v1beta1
k8s.io/api/networking/v1
k8s.io/api/rbac/v1
k8s.io/api/rbac/v1alpha1
k8s.io/api/rbac/v1beta1
k8s.io/api/scheduling/v1alpha1
k8s.io/api/scheduling/v1beta1
k8s.io/api/settings/v1alpha1
k8s.io/api/storage/v1
k8s.io/api/storage/v1alpha1
k8s.io/api/storage/v1beta1
# k8s.io/apimachinery v0.0.0-20180810004531-720795f37ef0
k8s.io/apimachinery/pkg/apis/meta/v1
k8s.io/apimachinery/pkg/runtime
k8s.io/apimachinery/pkg/watch
k8s.io/apimachinery/pkg/api/resource
k8s.io/apimachinery/pkg/conversion
k8s.io/apimachinery/pkg/fields
k8s.io/apimachinery/pkg/labels
k8s.io/apimachinery/pkg/runtime/schema
k8s.io/apimachinery/pkg/selection
k8s.io/apimachinery/pkg/types
k8s.io/apimachinery/pkg/util/intstr
k8s.io/apimachinery/pkg/util/runtime
k8s.io/apimachinery/pkg/conversion/queryparams
k8s.io/apimachinery/pkg/util/errors
k8s.io/apimachinery/pkg/util/json
k8s.io/apimachinery/pkg/util/naming
k8s.io/apimachinery/pkg/util/sets
k8s.io/apimachinery/pkg/util/net
k8s.io/apimachinery/pkg/util/wait
k8s.io/apimachinery/pkg/api/errors
k8s.io/apimachinery/pkg/runtime/serializer/streaming
k8s.io/apimachinery/pkg/api/meta
k8s.io/apimachinery/pkg/util/cache
k8s.io/apimachinery/pkg/util/clock
k8s.io/apimachinery/pkg/util/diff
k8s.io/apimachinery/third_party/forked/golang/reflect
k8s.io/apimachinery/pkg/util/validation
k8s.io/apimachinery/pkg/runtime/serializer
k8s.io/apimachinery/pkg/version
k8s.io/apimachinery/pkg/util/validation/field
k8s.io/apimachinery/pkg/apis/meta/v1beta1
k8s.io/apimachinery/pkg/apis/meta/internalversion
k8s.io/apimachinery/pkg/runtime/serializer/json
k8s.io/apimachinery/pkg/runtime/serializer/protobuf
k8s.io/apimachinery/pkg/runtime/serializer/recognizer
k8s.io/apimachinery/pkg/runtime/serializer/versioning
k8s.io/apimachinery/pkg/util/framer
k8s.io/apimachinery/pkg/util/yaml
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured
# k8s.io/client-go v8.0.0+incompatible
k8s.io/client-go/kubernetes
k8s.io/client-go/rest
k8s.io/client-go/tools/cache
k8s.io/client-go/util/workqueue
k8s.io/client-go/discovery
k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1
k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1
k8s.io/client-go/kubernetes/typed/apps/v1
k8s.io/client-go/kubernetes/typed/apps/v1beta1
k8s.io/client-go/kubernetes/typed/apps/v1beta2
k8s.io/client-go/kubernetes/typed/authentication/v1
k8s.io/client-go/kubernetes/typed/authentication/v1beta1
k8s.io/client-go/kubernetes/typed/authorization/v1
k8s.io/client-go/kubernetes/typed/authorization/v1beta1
k8s.io/client-go/kubernetes/typed/autoscaling/v1
k8s.io/client-go/kubernetes/typed/autoscaling/v2beta1
k8s.io/client-go/kubernetes/typed/batch/v1
k8s.io/client-go/kubernetes/typed/batch/v1beta1
k8s.io/client-go/kubernetes/typed/batch/v2alpha1
k8s.io/client-go/kubernetes/typed/certificates/v1beta1
k8s.io/client-go/kubernetes/typed/core/v1
k8s.io/client-go/kubernetes/typed/events/v1beta1
k8s.io/client-go/kubernetes/typed/extensions/v1beta1
k8s.io/client-go/kubernetes/typed/networking/v1
k8s.io/client-go/kubernetes/typed/policy/v1beta1
k8s.io/client-go/kubernetes/typed/rbac/v1
k8s.io/client-go/kubernetes/typed/rbac/v1alpha1
k8s.io/client-go/kubernetes/typed/rbac/v1beta1
k8s.io/client-go/kubernetes/typed/scheduling/v1alpha1
k8s.io/client-go/kubernetes/typed/scheduling/v1beta1
k8s.io/client-go/kubernetes/typed/settings/v1alpha1
k8s.io/client-go/kubernetes/typed/storage/v1
k8s.io/client-go/kubernetes/typed/storage/v1alpha1
k8s.io/client-go/kubernetes/typed/storage/v1beta1
k8s.io/client-go/util/flowcontrol
k8s.io/client-go/pkg/version
k8s.io/client-go/plugin/pkg/client/auth/exec
k8s.io/client-go/rest/watch
k8s.io/client-go/tools/clientcmd/api
k8s.io/client-go/tools/metrics
k8s.io/client-go/transport
k8s.io/client-go/util/cert
k8s.io/client-go/tools/pager
k8s.io/client-go/util/buffer
k8s.io/client-go/util/retry
k8s.io/client-go/kubernetes/scheme
k8s.io/client-go/tools/reference
k8s.io/client-go/util/integer
k8s.io/client-go/pkg/apis/clientauthentication
k8s.io/client-go/pkg/apis/clientauthentication/v1alpha1
k8s.io/client-go/pkg/apis/clientauthentication/v1beta1
k8s.io/client-go/util/connrotation
```
``` bash
$ ls -l vendor/github.com/Azure/
drwxr-xr-x 5 root root 66 Aug 15 14:56 go-autorest
```

### What did you expect to see?
I expected for the dependency "azure-sdk-for-go" to be fulfilled inside vendor/github.com/Azure/.

### What did you see instead?
Other dependencies are fulfilled correctly but this one is missing.

**Comment by thepudds** [comment] 2018-08-15 21:40
@gopherbot, please add label modules

**Comment by rsc** [comment] 2018-08-18 03:54
If those packages existed, go mod vendor would have copied them in.
The real problem is that vendor didn't report the problem.
That makes this a duplicate of #27063.

**Closed by rsc** 2018-08-18 03:54 UTC
Labels: modules
