### ISSUE TITLE
Xray proxy server that depends on x/sys does not work on OpenBSD 7.5

### ISSUE THREAD

**Issue by repliqa** [golang/go#66943] opened 2024-04-20 17:41 UTC
### Go version

go version go1.22.1 openbsd/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='openbsd'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='openbsd'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/openbsd_amd64'
GOVCS=''
GOVERSION='go1.22.1'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/tmp/tmp.9UGSLt9ROx/Xray-core-1.8.10/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build210144260=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

The issue is not directly related to the go language or x/sys library. But I've been told to raise the issue here by the developer of the software I'm having issues with on OpenBSD 7.5. If I'm breaking any rules then I apologize.

Context: https://github.com/XTLS/Xray-core/issues/3291

I want to setup a proxy server known as Xray that is built on top of v2ray and the projects use the go programming language. The proxy server worked perfectly on OpenBSD 7.4, but OpenBSD 7.5, it doesn't. There's a continuous stream of 35 Resource Temporary Unavailable in System Call. I mentioned this issue and an OpenBSD developer mentioned that "syscall() was removed, you now need to use the libc wrappers for the relevant functions. I see this is written in Go - if it's using an old x/sys then updating may help otherwise that may be complicated to change. ". Based on that info, I opened a github issue on the repository of the Xray project, which I have linked on the top. And the owner told me to open an issue here.

The software's binary could be downloaded directly from their github repo but I also built it from source on OpenBSD 7.5 to see if it changes anything.

### What did you see happen?

Here are the configuration files and logs if they are of any help:
Xray client and server configs: https://pastebin.com/hEwyUxbb
Xray access logs: https://pastebin.com/DNRYsMEL
Xray error logs: https://pastebin.com/nJyVAAdG

And as of the system calls of the program, there is a continuous stream of 35 Resource Temporarily Unavailable, with some 36 Operation now in progress and 65 No route to host.

### What did you expect to see?

I expect the proxy server to route the traffic between itself and the clients properly.

**Comment by seankhliao** [comment] 2024-04-20 17:53
Duplicate of #36435

**Closed by seankhliao** 2024-04-20 17:53 UTC

**Comment by 4a6f656c** [comment] 2024-04-29 14:27
> Duplicate of #36435

@seankhliao FWIW this is not related to #36435 - all OpenBSD ports (except for openbsd/mips64 - see #61546) have used libc based system calls for a very long time. This is more likely related to #63900.
