### ISSUE TITLE
cmd/compile compiler can't optimize calculations with constants

### ISSUE THREAD

**Issue by sgomenyuk** [golang/go#49495] opened 2021-11-10 08:55 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/sgomenyuk/Library/Caches/go-build"
GOENV="/Users/sgomenyuk/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/sgomenyuk/go/pkg/mod"
GONOPROXY="github.com/wheely"
GONOSUMDB="github.com/wheely"
GOOS="darwin"
GOPATH="/Users/sgomenyuk/go"
GOPRIVATE="github.com/wheely"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7z/rqjh1sgn60d42dqgtm9tbn_h0000gn/T/go-build1809031039=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I made a simple example
```
package main

import "fmt"

const P = 3.14

//nogo:nonoinline
func FuncWithConstants(x float64) float64 {
  return x * P / 180
}

func main() {
	a := FuncWithConstants(123.456)
	fmt.Printf("%v", a)
}
```
and compiled it with the following cmd to get ssa for `FuncWithConstants`
```
GOSSAFUNC=FuncWithConstants go tool compile a.go
```

### What did you see?
In resulted ssa representation(after opt phase) I see that the expression x * P / 180 is calculated with the following instructions:
```
b1:-
v1 (?) = InitMem <mem>
v6 (8) = Arg <float64> {x} (x[float64])
v9 (?) = Const64F <float64> [3.14]
v10 (+9) = Mul64F <float64> v6 v9
v11 (?) = Const64F <float64> [180]
v12 (9) = Div64F <float64> v10 v11
v13 (9) = MakeResult <float64,mem> v12 v1
v8 (?) = Const64 <int64> [0]
Ret v13 (+9)
name x[float64]: v6
```
First it multiplies x and constant P and then divides the result on constant 180

I gave a hint to the compiler replaced ` return x * P / 180` by `return x * (P / 180)` and in this case all constants were calculated and replaced by result and Div64F instruction was disappeared but parentheses are redundant in this expression

```
b1:-
v1 (?) = InitMem <mem>
v6 (8) = Arg <float64> {x} (x[float64])
v9 (?) = Const64F <float64> [0.017444444444444443]
v10 (+9) = Mul64F <float64> v6 v9
v11 (9) = MakeResult <float64,mem> v10 v1
v8 (?) = Const64 <int64> [0]
Ret v11 (+9)
name x[float64]: v6
```

### What did you expect to see?
I was wondering if it is possible to add some optimization to determine constant expression and reduce unnecessary instructions for such case

**Comment by hanchaoqun** [comment] 2021-11-10 10:19
Can be fixed by adding generic rewrite rules:
<pre>
// x * c / d => x * (c / d)
(Div(64|32)F <t> (Mul(64|32)F x (Const(64|32)F [c])) (Const(64|32)F [d])) && d != 0 && c/d == c/d => (Mul(64|32)F x (Const(64|32)F <t> [c/d]))
</pre>

**Comment by nanokatze** [comment] 2021-11-10 10:34
`x * P / 180` and `x * (P / 180)` produce different result for `x = math.MaxFloat64`, so this seems to be working as intended?

**Comment by sgomenyuk** [comment] 2021-11-10 13:06
so, looks like the reason of this behaviour is to corresponds to standard 😄 :
> Floating-point operations within a single expression are evaluated according to the associativity of the operators. Explicit parentheses affect the evaluation by overriding the default associativity. In the expression x + (y + z) the addition y + z is performed before adding x.

and compiler should support order of associative operation in this case and `x*P` shall be evaluated first for `x * P / 180`.

**Comment by randall77** [comment] 2021-11-10 15:53
This is intended. Not many optimizations are allowed for floating-point arithmetic. In particular, it isn't associative.

**Closed by randall77** 2021-11-10 15:53 UTC
