### ISSUE TITLE
net/http/httptest: make easier way to create Requests for testing

### ISSUE THREAD

**Issue by encryptio** [golang/go#14915] opened 2016-03-22 17:36 UTC
When `http.NewRequest` is called, it does not fill in `(http.Request).RequestURI`, but `http.Server` *does* fill in `(http.Request).RequestURI`, which has caused issues writing tests that use a `httptest.ResponseRecorder` instead of a `httptest.Server`.

A test case:

```
package issue

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestNewRequestRequestURI(t *testing.T) {
	var httpServerRequestURI string
	h := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		httpServerRequestURI = r.RequestURI
	})

	srv := httptest.NewServer(h)
	defer srv.Close()

	req, err := http.NewRequest("GET", srv.URL+"/path", nil)
	if err != nil {
		t.Fatal(err)
	}

	newRequestRequestURI := req.RequestURI

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()

	if newRequestRequestURI != httpServerRequestURI {
		t.Fatalf("NewRequest().RequestURI = %#v, but sending to server yielded %#v",
			newRequestRequestURI, httpServerRequestURI)
	}
}
```

Which yields:

```
--- FAIL: TestNewRequestRequestURI (0.00s)
	test_test.go:33: NewRequest().RequestURI = "", but sending to server yielded "/path"
FAIL
exit status 1
FAIL	issue	0.004s
```

On `go version go1.6 linux/amd64` and `go version devel +c12e1b0 Tue Mar 22 17:09:29 2016 +0000 linux/amd64`.

**Comment by minux** [comment] 2016-03-22 18:43
Working as intended (and documented).

The RequestURI field is not supposed to be set on client requests.
Quote https://golang.org/pkg/net/http/#Request:

        // RequestURI is the unmodified Request-URI of the
        // Request-Line (RFC 2616, Section 5.1) as sent by the client
        // to a server. Usually the URL field should be used instead.
        // It is an error to set this field in an HTTP client request.
        RequestURI string

And NewRequest is not designed to create server Requests:
Quote https://golang.org/pkg/net/http/#NewRequest

        NewRequest returns a Request suitable for use with Client.Do
        or Transport.RoundTrip. To create a request for use with testing
        a Server Handler use either ReadRequest or manually update the
        Request fields. See the Request type's documentation for the
        difference between inbound and outbound request fields.

**Comment by bradfitz** [comment] 2016-03-22 20:37
For Go 1.7, I do want to make a new httptest helper to make it easier to create a Request for testing, though. I think there's already an open bug, but just in case I'll re-open this one and assign it to me.

**Comment by cespare** [comment] 2016-03-22 20:49
@bradfitz #14199 is the existing issue. Probably okay to leave this one closed.

**Closed** 2016-03-22 23:31 UTC
