### ISSUE TITLE
crypto/x509 How to convert x509.Certificate to tls.Certificate and make a request with it.

### ISSUE THREAD

**Issue by HongyanShen** [golang/go#22317] opened 2017-10-18 04:55 UTC
I decode a .p12 file into an x509.Certificate with pkcs12 package, and then make a request like this:

```
func PostAsBytesWithCert(url, data, mime string, cert *x509.Certificate) ([]byte, error) {
	tlsConfig := &tls.Config{
		Certificates: []tls.Certificate{tls.Certificate{
			Certificate: [][]byte{cert.Raw},
		}},
	}

	tr := &http.Transport{TLSClientConfig: tlsConfig}
	client := &http.Client{Transport: tr}
	
	resp, err := client.Post(url, mime, strings.NewReader(data))
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	bytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	return bytes, nil
}
```

However, it run into an error: **tls: client certificate private key of type <nil> does not implement crypto.Signer**

**Comment by gbbr** [comment] 2017-10-18 07:57
These looks more like a question than a bug or proposal. You will have more luck getting answers in one of the sources listed here: https://golang.org/wiki/Questions
 
Unless I'm wrong, please consider closing this and posting your question there.

**Comment by ALTree** [comment] 2017-10-18 12:24
As noted above, the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Closing, since this is not a bug report.

**Closed by ALTree** 2017-10-18 12:24 UTC
