### ISSUE TITLE
x/tools/shadow: shadowing predefined identifiers is not detected?

### ISSUE THREAD

**Issue by leovct** [golang/go#56871] opened 2022-11-21 12:57 UTC
Hi, I'm currently reading the `Learning Go` book and I came across the `Shadowing variables` section where it's mentioned that the go tool `shadow` does not catch shadowing predefined identifiers. I wanted to know why it was not implemented and if that's something planned, how can I help :slight_smile:

Here's a simple example
```go
package main

import "fmt"

func main() {
    fmt.Println(true)
    true := "hey"
    fmt.Println(true)
}
```
```bash
$ go run main.go
true
hey // "true" identifier shadowed!

$ shadow main.go
// no errors detected :(
```

**Comment by seankhliao** [comment] 2022-11-21 13:34
Duplicate of #33567

**Closed by seankhliao** 2022-11-21 13:34 UTC
Labels: Tools
