### ISSUE TITLE
cmd/go: 1.16 changes 'go list -m all' behavior

### ISSUE THREAD

**Issue by qbit** [golang/go#44238] opened 2021-02-12 17:31 UTC
### What version of Go are you using (`go version`)?

`1.16rc1`

### Does this issue reproduce with the latest release?

In versions <= 1.15 one was able to download a packages `go.mod` file and use `go list -m all` to print a full set of dependencies. All `beta` and `rc` versions of 1.16 have suffered from this issue.

### What operating system and processor architecture are you using (`go env`)?

Confirmed on `darwin/arm64` and `openbsd/amd64,arm65`

### What did you do?

```
mkdir /tmp/test
cd /tmp/test
curl -o go.mod https://proxy.golang.org/suah.dev/protect/@v/v1.0.0.mod
go list -m all
```

### What did you expect to see?

```
qbit@tal[0]:/tmp/test$ go list -m all                                                         
suah.dev/protect
golang.org/x/sys v0.0.0-20200501145240-bc7a7d42d5c3
qbit@tal[0]:/tmp/test$ 

```

### What did you see instead?

```
qbit@plq[0]:/tmp/test% go list -m all
go: golang.org/x/sys@v0.0.0-20200501145240-bc7a7d42d5c3: missing go.sum entry; to add it:
	go mod download golang.org/x/sys
qbit@plq[1]:/tmp/test% 
```

Adding `-mod=mod` makes `go list -m all` produce the expected output.

**Comment by mvdan** [comment] 2021-02-12 17:47
I think this is because `go list -m all` in 1.16 roughly equals `go list -m -mod=readonly` in 1.15. An alternative to adding `-mod=mod` would be to run `go mod tidy` to ensure go.mod and go.sum aren't missing any lines.

**Comment by bcmills** [comment] 2021-02-12 18:11
This is an expected consequence of #40728.

There are several ways to mitigate it:
* In the steps to reproduce, copy the project's `go.sum` file _in addition to_ its `go.mod` file.
* Or, run `go mod download`, `go mod tidy`, or `go mod vendor` after copying in the `go.mod` file.
* Or, if you are copying the `go.mod` file in order to build some package, run `go get -d` on that package in order to fetch checksums for its dependencies.
* Or, pass `-mod=mod` explicitly to the `go list` command, to inform it that you really are ok with going out to the network to fetch checksums.

(CC @jayconrod @matloob)

**Comment by bcmills** [comment] 2021-02-12 18:17
@qbit: taking the above options into account, do you have a specific workflow that this workflow makes awkward or difficult?

(If so, we can look for other mitigations — or perhaps other changes to `-mod=readonly` mode, or better documentation — to address that workflow.)

**Comment by qbit** [comment] 2021-02-12 20:09
In my case adding `-mod=mod` seems to be the best approach. 

For context, this is for the OpenBSD [portgen](https://man.openbsd.org/portgen) utility, which builds a port (think software packaging) of go tools. I am using `go list -m all` to get a list of all dependencies for inclusion in a port's distribution file list (for example, here is the [distinfo](https://github.com/openbsd/ports/blob/master/security/age/distinfo) file for the [age port](https://github.com/openbsd/ports/tree/master/security/age)).

Thanks for the info!

**Comment by bcmills** [comment] 2021-02-12 20:12
Thanks! In that case, I'm going to close this as “worked as proposed in #40728”, but please do let us know if you run into other cases that can't easily be fixed.

**Closed by bcmills** 2021-02-12 20:12 UTC
Labels: NeedsInvestigation, WaitingForInfo, modules
