### ISSUE TITLE
embed: Files starting with : (double dots) are not embedded (undocumented behavior)

### ISSUE THREAD

**Issue by reddec** [golang/go#46199] opened 2021-05-17 10:39 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/baryshnikov/.cache/go-build"
GOENV="/home/baryshnikov/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/baryshnikov/Develop/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/baryshnikov/Develop/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go/latest"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/latest/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1338096382=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

[demo-fs.tar.gz](https://github.com/golang/go/files/6493199/demo-fs.tar.gz)
<details><summary>Source code (see attachment)

</summary><br>
<pre>
package main

import (
	"embed"
	"fmt"
	"os"
)

//go:embed assets
var assets embed.FS

func main() {
	files := []string{
		"assets/root.txt",
		"assets/:normal",
		"assets/:alsonormal/file2.txt",
	}

	// check in real file system
	for _, file := range files {
		_, err := os.Open(file)
		if err != nil {
			fmt.Println("[FAILED ] failed open", file, "in real file system:", err)
		} else {
			fmt.Println("[SUCCESS] open", file, "in real file system")
		}
	}

	// check in embedded
	for _, file := range files {
		_, err := assets.Open(file)
		if err != nil {
			fmt.Println("[FAILED ] failed open", file, "in embedded file system", ":", err)
		} else {
			fmt.Println("[SUCCESS] open", file, "in embedded file system")
		}
	}
}

</pre>
</details>

### What did you expect to see?

Embedded files with `:` in names were included.

(from demo)

```
[SUCCESS] open assets/root.txt in real file system
[SUCCESS] open assets/:normal in real file system
[SUCCESS] open assets/:alsonormal/file2.txt in real file system
[SUCCESS] open assets/root.txt in embedded file system
[SUCCESS] open assets/:normal in embedded file system
[SUCCESS] open assets/:alsonormal/file2.txt in embedded file system
```

### What did you see instead?

Embedded files with `:` in names  were not included.

(from demo)

```
[SUCCESS] open assets/root.txt in real file system
[SUCCESS] open assets/:normal in real file system
[SUCCESS] open assets/:alsonormal/file2.txt in real file system
[SUCCESS] open assets/root.txt in embedded file system
[FAILED ] failed open assets/:normal in embedded file system : open assets/:normal: file does not exist
[FAILED ] failed open assets/:alsonormal/file2.txt in embedded file system : open assets/:alsonormal/file2.txt: file does not exist
```

### Analysis

Likely related to  https://github.com/golang/go/issues/45447.
Embedded files names restriction should be relaxed and/or documented.

**Comment by jayconrod** [comment] 2021-05-17 14:22
Duplicate of #44486.

We do need to fix this though: documentation of the restrictions should be more prominent, and the diagnostics should be clearer.

**Closed by jayconrod** 2021-05-17 14:22 UTC
Labels: Documentation
