### ISSUE TITLE
net/http: deadlock in TestMissingStatusNoPanic on release-branch.go1.15 branch

### ISSUE THREAD

**Issue by cagedmantis** [golang/go#45358] opened 2021-04-02 17:48 UTC
[2505e26/windows-amd64-longtest](https://build.golang.org/log/2505e26cfbfd5808011657d74b1f4637583a236f)
[1035bb9/windows-amd64-longtest](https://build.golang.org/log/1035bb98e532395fabb222dfe17a32ab4f2a0a1f)
[b35c38a/windows-amd64-longtest](https://build.golang.org/log/b35c38acd33fc6a3054323198d9703ad4f555dcb)
[636a6d14/windows-amd64-longtest](https://build.golang.org/log/636a6d148b149f1072a0e705dbf5df99eba01b74)

May be related to ##42942

CC CC @alexbrainman @fraenkel @neild @bradfitz @golang/release

**Comment by fraenkel** [comment] 2021-04-03 03:00
@cagedmantis I think this is the wrong test. While the error occurs on TestCancelRquestWhenSharing after a few seconds, the moire obvious one is TestMissingStatusNoPanice which has been stuck for 14m.

```
goroutine 17971 [chan receive, 14 minutes]:
net/http_test.TestMissingStatusNoPanic(0xc00060e000)
	C:/workdir/go/src/net/http/transport_test.go:5320 +0x450
```

**Comment by bcmills** [comment] 2021-05-13 15:02
https://storage.googleapis.com/go-build-log/2ba9aff9/windows-amd64-longtest_d50badd6.log (a TryBot on [CL 319710](https://golang.org/cl/319710))

**Comment by bcmills** [comment] 2021-05-13 15:46
Also https://storage.googleapis.com/go-build-log/5200af43/windows-amd64-longtest_e8416262.log (a TryBot on CL 319709).

**Comment by fraenkel** [comment] 2021-05-13 15:51
All of the failures are due to TestMissingStatusNoPanic so far. My fix above will just expose the real issue which we currently aren't seeing.

**Comment by fraenkel** [comment] 2021-05-14 19:50
On the plus side, we now see the actual issue(s) in Go 1.15 failures.

**Comment by fraenkel** [comment] 2021-05-14 20:18
I see at least one of the issues and may be the actual problem....
Notice its all using the same port.

`TestTransportPersistConnReadLoopEOF` is failing but not sending a bogus conn to the connc channel.

**Comment by fraenkel** [comment] 2021-05-15 01:58
The above is incorrect, the testcase is fine.
The error being reported happens when the system is underload and usually out of resources. One can tweak the TCP settings to reduce the failure.

There is also this https://go.googlesource.com/benchmarks/+/refs/heads/master/http/http.go#42
I guess something got fixed/improved in 1.16+.

**Comment by dmitshur** [comment] 2021-06-02 01:37
GopherBot is a little eager (due to #29599 not being resolved yet).

**Comment by dmitshur** [comment] 2021-06-02 01:38
GopherBot is a little fiesty (due to #21312 not being resolved yet).

**Comment by neild** [comment] 2021-06-02 03:16
The root cause of the failures is port exhaustion, which hasn't been addressed, but the deadlock in `TestMissingStatusNoPanic` should be fixed.

I haven't been able to reproduce the port exhaustion failures manually after running `go test net` a number of times on a `windows-amd64-longtest` builder today. Possibly I'm not taking the right steps to reproduce the problem, or possibly whatever was causing that builder to run out of ports has been addressed. I'm going to tentatively assume the latter unless these failures show up again.

**Comment by fraenkel** [comment] 2021-06-02 03:29
I think it might be the combination of things. One test that didn't finish, holding up others than haven't done their cleanup.
It was a bit weird that it was only occurring in one release.

**Closed** 2021-08-04 18:13 UTC
Labels: NeedsFix, Testing
