### ISSUE TITLE
proposal: Hope to provide ` arrow functions` 'syntax

### ISSUE THREAD

**Issue by Lizhooh** [golang/go#21786] opened 2017-09-07 12:06 UTC
Hope to provide ` arrow functions` 'syntax.

How do you like it?

```go
add := func(a int, b int) int {
    return a + b
}

// arrow functions
add := (a int, b int) int => a + b
```

**Comment by davecheney** [comment] 2017-09-07 12:17
Thank you for raising this issue. This appears to be a duplicate of, or have a great deal of overlap with #21498. I am closing this issue as the other has more detail and more discussion.

**Closed by davecheney** 2017-09-07 12:17 UTC
Labels: Proposal
