### ISSUE TITLE
x/pkgsite: pkg.go.dev/std is unreachable from the homepage

### ISSUE THREAD

**Issue by coreyog** [golang/go#50099] opened 2021-12-10 21:37 UTC
### What is the URL of the page with the issue?

pkg.go.dev

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36

### Screenshot

![pkg go dev](https://user-images.githubusercontent.com/2836207/145642312-2cd9d425-9d87-4b8f-a61e-6d16e26de08e.png)

### What did you do?

Visited the page

### What did you expect to see?

A way to _browse_ the standard library. I learned most of what I know about the runtime, sync, mime, and other packages by perusing the documentation looking for packages I hadn't used before. I never would have been able to do that with the use case the website is focused on right now: finding what you're already looking for. I don't always know what I'm looking for. I love that this is one place for documentation, even non-standard libraries, but pkg.do.dev/std should be easily accessible from the homepage. I had to find it by searching for something I didn't want to find then clicking a breadcrumb that didn't seem related to the actions I took to get there. It was not beginner-friendly.

Maybe one of the hints under the search bar could have a link or a "What's in the standard library?" FAQ link that takes you to the page.

### What did you see instead?

A search bar that doesn't aid in discovery.

**Comment by seankhliao** [comment] 2021-12-10 22:08
Duplicate of #40785

**Closed by seankhliao** 2021-12-10 22:08 UTC
Labels: pkgsite
