### ISSUE TITLE
Order of tags 'json' and 'gorm' in struct changes marshalling output 

### ISSUE THREAD

**Issue by alextr98** [golang/go#49430] opened 2021-11-07 22:13 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code>$ go env
<pre>
 GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/emserver/.cache/go-build"
GOENV="/home/emserver/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/emserver/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/emserver/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/emserver/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2945837827=/tmp/go-build -gno-record-gcc-switches"</summary><br><pre>

</pre></details>

### What did you do?

package main

import (
        "encoding/json"
        "fmt"
        "gorm.io/gorm"
)

type Test struct {
        gorm.Model &#96;json:"-"&#96;
        JsonFirst     string &#96;json:",omitempty" ; gorm:"size:4"&#96;
        GormFirst     string &#96;gorm:"size:4" ; json:",omitempty"&#96;
}

func main() {
    var t1 Test
    s1,_ := json.Marshal(t1)
    fmt.Println(string(s1))   
}

### What did you expect to see?
{}

### What did you see instead?
{"GormFirst":""}

**Comment by dsnet** [comment] 2021-11-07 23:43
The cause of this is because the Go struct tag is an incorrect syntax.

Tags are supposed to be space separated, not semi-colon separated. As a result, the reflect package is unable to parse the next record.

See https://play.golang.org/p/OqA0_rTUrOy

**Comment by davecheney** [comment] 2021-11-08 00:12
```
(~/x) % go vet
# x.y.z
./t.go:11:2: struct field tag `json:",omitempty" ; gorm:"size:4"` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
./t.go:12:2: struct field tag `gorm:"size:4" ; json:",omitempty"` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
```
As per @dsnet's comment, closing as not a bug.

**Closed by davecheney** 2021-11-08 00:12 UTC
