### ISSUE TITLE
net/http: ReadRequest should reject requests with multiple Host headers

### ISSUE THREAD

**Issue by borncrusader** [golang/go#45463] opened 2021-04-09 03:14 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/<name>/go-workspace/bin"
GOCACHE="/Users/<name>/Library/Caches/go-build"
GOENV="/Users/<name>/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/<name>/go-workspace/pkg/mod"
GOOS="darwin"
GOPATH="/Users/<name>/go-workspace"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/<name>/.asdf/installs/golang/1.16/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/<name>/.asdf/installs/golang/1.16/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_z/0tl9x4tj43981q938qh7xqhw0000gp/T/go-build492873196=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

`http.ReadRequest` doesn't account for potentially multiple `Host` headers in the request. This is a snippet of the code to reproduce this issue - https://play.golang.org/p/vZ71i09DAHb

According to the HTTP Spec (https://tools.ietf.org/html/rfc7230#section-5.4),

> A server MUST respond with a 400 (Bad Request) status code to any
   HTTP/1.1 request message that lacks a Host header field and to any
   request message that contains more than one Host header field or a
   Host header field with an invalid field-value.

However, this is appropriately handled in https://github.com/golang/go/blob/master/src/net/http/server.go#L1007. But clients attempting to parse an HTTP request using `http.ReadRequest` have no means to detect the presence of multiple `Host` headers since the `Host` header is promoted to `http.Request.Host` and is not part of the `http.Request.Header` map.

### What did you expect to see?

Expect to have a means by which one can detect the presence of multiple `Host` headers in the HTTP request when using `http.ReadRequest`.

### What did you see instead?

The `http.Request` returned by the method does not have any indication to the presence of multiple `Host` headers. It also returns a `nil` error.

**Comment by davecheney** [comment] 2021-04-09 04:00
Does ReadRequest return an error if there are multiple Host headers in the request?

**Comment by davecheney** [comment] 2021-04-09 04:02
Thank you for your sample. Given that ReadRequest rejects the request, are you asking for the error to be changed to perhaps indicate the multiple header values presented?

Asked another way, if we changed http.Request to capture multiple Host headers, how would that change the program you are trying to write?

**Comment by borncrusader** [comment] 2021-04-09 05:12
@davecheney - it does not return an error when there are multiple `Host` headers present. The code sample's `err == nil` code runs.

The issue is it does not return an error nor reflect in the `req.Header` fields that there were multiple `Host` headers present.

**Comment by borncrusader** [comment] 2021-04-09 05:43
To answer your latter question, I want to be able to use the API to parse an incoming byte stream and return an error if it has multiple `Host` headers.

**Comment by davecheney** [comment] 2021-04-09 05:43
@borncrusader thank you for your reply. Given this is a violation of the RFC, maybe the best resolution of this issue is to make ReadRequest reject such requests.

**Comment by borncrusader** [comment] 2021-04-09 06:00
Thanks @davecheney for your prompt reply!

**Comment by borncrusader** [comment] 2021-04-19 18:12
Looks like https://github.com/golang/go/issues/45513 addresses this as well. I believe this will be considered for 1.16.4. Please correct me if I'm wrong, @davecheney

**Comment by networkimprov** [comment] 2021-05-15 21:29
Missed by triage?

cc @neild @fraenkel @empijei

**Comment by fraenkel** [comment] 2021-05-16 01:15
1.17 returns an error, `too many Host headers`
issue #45513

**Comment by dmitshur** [comment] 2021-05-21 23:31
I'll close this issue because it is a duplicate of issue #45513. Let's continue the conversation there.

**Closed by dmitshur** 2021-05-21 23:31 UTC
Labels: NeedsDecision
