### ISSUE TITLE
x/build: add a Windows ARM builder 

### ISSUE THREAD

**Issue by toothrot** [golang/go#47019] opened 2021-07-01 20:51 UTC
Our current builder (generously contributed by @zx2c4) is ready to be turned down. We need additional hardware to keep supporting this platform, and can re-use the infrastructure from #42604.

**Comment by bcmills** [comment] 2021-11-10 19:40
Do we have any actual ARM hardware that we could copy the image to in order to determine whether the problem is with the WIndows version or the QEMU host?

**Comment by zx2c4** [comment] 2021-11-10 20:24
> We're running into a 0xc000007b failure when attempting to run arm32 binaries in our arm64 windows installation. It could be either the version of windows we have installed,

The latest insider build has arm32 issues, fyi, so be sure to run ordinary stable.

Things seem fine on real hardware.

**Comment by toothrot** [comment] 2021-11-10 23:02
Unfortunately, I couldn't get the stable version to run on the VM instances we're using. As I mentioned on #49266, I'll try updating the builders in my free time this weekend.

I also couldn't reproduce on real hardware, but this seems related to the specific environment we're running on.

Do you know if Windows ARM32 will continue to be supported?

**Comment by zx2c4** [comment] 2021-11-10 23:12
The idea is to run the ARM64 build of Windows and test ARM32 inside of it. Microsoft still supports ARM32 for IoT. If you think there's a good argument for sunsetting ARM32 in Go, though, then I guess that'd be a proposal to make, and then we could get some definition on it that way.

**Comment by toothrot** [comment] 2021-11-23 15:44
We will be giving this another shot, as we're working on upgrading our windows builders this week. The holiday will slow things down a bit, but we're actually working on it.

As a bonus, @heschi is doing it, which means updates won't be blocked solely on my availability.

**Comment by zx2c4** [comment] 2021-11-25 12:26
In case it helps,

```
PS C:\go-src\src> $env:GOARCH='arm'
PS C:\go-src\src> $env:GOHOSTARCH='arm'
PS C:\go-src\src> $env:GOARM='7'
PS C:\go-src\src> $env:GOOS='windows'
PS C:\go-src\src> $env:GOROOT_BOOTSTRAP='C:\go-binary-arm64-release'
PS C:\go-src\src> .\all.bat
```

You'll need to download llvm and such for cgo, but the above should hopefully get you past the, "it doesn't work at all!" phase, as the above _does_ in fact work, and you can see ARM32 processes in the details view of task manager.

![Screenshot_20211125-005204](https://user-images.githubusercontent.com/10643/143326727-aa4e85af-a74c-4fda-bed3-84adea715a93.png)

**Comment by zx2c4** [comment] 2021-11-25 12:29
@dmitshur Can we make this issue a goal for before 1.18 beta1? That way we're certain to have the beta1 period to fix bugs that might have slipped in since we went builderless a long while back, and therefore don't regress for 1.18.0.

**Comment by heschi** [comment] 2021-12-06 23:11
I'm actively working in this area, but it's a very complicated situation and I'm not confident it'll be done before beta.

**Comment by zx2c4** [comment] 2021-12-06 23:50
Anything I can do to help? What sorts of complications are you facing?

**Comment by zx2c4** [comment] 2021-12-09 21:49
You might have luck running it under QEMU inside of Linux, on an AWS ARM instance. And then capping the number of CPUs to 4 or 8 or something smallish.

**Comment by heschi** [comment] 2021-12-09 22:00
Yeah, we've had some minimal success with that, but with anything more than 4 cores it greenscreens. Even with 4 I think we've seen some instability. See https://cs.opensource.google/go/x/build/+/master:env/windows-arm64/aws/.

**Comment by heschi** [comment] 2021-12-10 18:52
I was trying with 22504; given that we've seen the same failures with a 6-month build and a fresh one, I don't think there's much hope for stable to be better :(

**Comment by heschi** [comment] 2022-02-08 21:55
@zx2c4 I finally, finally got to work on this and immediately faceplanted. Running anything with `GOARCH=arm` gives me `This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.`

We're running the latest version of Windows 11, not IOT. I can't find a clear answer to whether that's supposed to support ARM32 binaries. Do you know what's going on here?

**Comment by heschi** [comment] 2022-03-17 17:38
@zx2c4 any ideas?

**Comment by dmitshur** [comment] 2024-07-31 22:32
This issue was tracking adding this builder to the coordinator, but that's replaced with LUCI now. Closing this in favor of #67308.

**Closed by dmitshur** 2024-07-31 22:32 UTC
Labels: OS-Windows, Builders, NeedsFix, new-builder
