### ISSUE TITLE
Run all tests for a Workspace with One command (Proposal)

### ISSUE THREAD

**Issue by zacharyjones123** [golang/go#51756] opened 2022-03-17 13:38 UTC
# Problem
I currently have a project with multiple modules. I'm using the new workspace feature in 1.18 and it works fantastically for getting dependencies and organizing my workflow better. One issue I'm having is actually testing all of the different modules at the same time.

### `go.work`
```go
go 1.18

use (
	./example
	./example/template
	./hello
	./hello/something
)
```
Given my current `go.work` above, I can test manually by running each of the `use` directories separately

### How I run tests manually
```go
go test ./example
go test ./example/template
go test ./hello
go test ./hello/something
```

# Proposed Solution
Have a  single command that will run all of the tests for your given workspace. 

There is currently a `-workfile` flag but I can't for the life of me find documentation or how to get that working. 

### My attempt at getting `-workfile` flag working
```bash
-  go-go-go git:(main) ✗ go test -workfile=go.work
no Go files in /Users/zachajon/Projects/delete_later/go-go-go
```

I'm completely open to all feedback and help that can be given! This is my first time posting an issue to an open source project like this and I'm nervous and super excited!!!

**Comment by seankhliao** [comment] 2022-03-17 16:01
Duplicate of #50745

**Closed by seankhliao** 2022-03-17 16:01 UTC
Labels: Proposal
