### ISSUE TITLE
big.Float end-to-end marshalling not working

### ISSUE THREAD

**Issue by adlrocha** [golang/go#45309] opened 2021-03-31 06:32 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/adlrocha/.cache/go-build"
GOENV="/home/adlrocha/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/adlrocha/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/adlrocha/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/adlrocha/Desktop/main/work/ProtocolLabs/repos/libp2p/go-smart-record/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1146977497=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I am trying to `Marshal` and `Unmarshal` a `big.Float`. As shown in the [playground example](https://play.golang.org/p/Rm3u03hyLGh), using `MarshalText` and `UnmarshalText` or even `SetString` doesn't result in the same Float representation.

### What did you expect to see?
Marshalling and unmarshalling the same float should result in equal Float representations.

### What did you see instead?
That both floats are not equal.

Thanks!

**Comment by seankhliao** [comment] 2021-03-31 07:16
[big.NewFloat](https://golang.org/pkg/math/big/#NewFloat):
> ... with precision 53 ...

[Float.UnmarshalText](https://golang.org/pkg/math/big/#Float.UnmarshalText):
> ...If z's precision is 0, it is changed to 64 ...

using 64 for both it roundtrips successfully: https://play.golang.org/p/zAeDtPC6Mp-

Closing as working as intended

**Closed by seankhliao** 2021-03-31 07:16 UTC
