### ISSUE TITLE
embed, cmd/go: add a way to exclude a file from embedding

### ISSUE THREAD

**Issue by carlmjohnson** [golang/go#42325] opened 2020-11-01 19:40 UTC
Problem: if you embed a directory, it may embed unwanted files from the directory.

Proposal: Comments with `//go:embed-exclude` apply a filter of files to exclude from the embed.

Example:

Given a directory with `static/a.txt` and `static/.dot`:

```
//go:embed static
//go:embed-exclude .*
var staticFiles embed.FS
```

will just embed `static/a.txt`.

Refs. #42321.

**Comment by carlmjohnson** [comment] 2020-11-01 19:41
_Originally posted by @SamWhited in https://github.com/golang/go/issues/42321#issuecomment-720139496_:

> I would actually like the ability of exluding specific files. even if we document dot file inclusion it would be good to have a way to ecxlude them, same as excluding something like assets.go would be nice.

I tentatively disagree. It seems to me that if you wanted to exclude certain files you shouldn't have selected those files in the first place using the glob.

I suspect allowing excluding individual files will end up with projects having giant lists of temp files to be excluded, one person excludes the `.swp` files that they accidentally included, then the next excludes the `.DS_Store` files their operating system included, then the next person excludes <your editor of choice's temp files>, etc. (rather like how we see projects with huge .gitignore files instead of people putting their specific editors in their user or system wide gitignore file).  Instead I'd suggest it's better to not use a glob or configure your build to check for files you don't want.

**Comment by carlmjohnson** [comment] 2020-11-01 19:45
> Instead I'd suggest it's better to not use a glob or configure your build to check for files you don't want.

That's a good suggestion, but I'm not sure it will work if someone has a difference between their build server and their testing server. The build server (possibly a laptop) might have extra files that don't exist on the testing server (for sake of argument, cloud CI), so the tests won't detect that the extra files have snuck in.

**Comment by SamWhited** [comment] 2020-11-01 19:47
> I'm not sure it will work if someone has a difference between their build server and their testing server

This also seems like a problem that the embed mechanism doesn't need to solve. If I have a difference between the source on my build and testing server I have a problem with my build and testing server, not with my Go code.

**Comment by andig** [comment] 2020-11-02 12:52
> I tentatively disagree. It seems to me that if you wanted to exclude certain files you shouldn't have selected those files in the first place using the glob.

I would disagree. Due to reasons discussed in https://github.com/golang/go/issues/41191 I could have `assets.go` in my dist folder. While I want to include the entire dist folder and not bother with specifying it type by type I'd still want to exclude the assets file.

**Comment by andig** [comment] 2020-11-02 12:53
As for syntax it might be more obvious to add an exclude switch to the `go:embed` directive rather than stacking directives.

**Comment by carlmjohnson** [comment] 2020-11-02 13:26
> As for syntax it might be more obvious to add an exclude switch to the `go:embed` directive rather than stacking directives.

I like that idea in theory but I don’t think it could be compatible with the existing glob format. Maybe I’m wrong though.

**Comment by rsc** [comment] 2020-11-04 18:48
Closing as a duplicate of #42328. Let's have the discussion there.

**Closed** 2020-11-04 18:48 UTC
Labels: NeedsInvestigation
