### ISSUE TITLE
x/tools/gopls: gopls fails to find a type definition

### ISSUE THREAD

**Issue by pjweinb** [golang/go#42585] opened 2020-11-13 15:40 UTC
at gopls tip (eeaa07dd), using vscode-insiders, open the x/tools repository
open internal/lsp/debug/serve.go
go to line 259: 	'return i.State.View(path.Base(r.URL.Path))'
hover over 'View' (it says that View() returns a *cache.View)
Ask for the type definition. (It says "No type definition found for 'View'")

The type definition is found in internal/lsp/cache/view.go

Both these files are in the same module (tools/go.mod)

**Comment by stamblerre** [comment] 2020-11-13 15:55
We don't offer type definitions for functions--"Go to definition" should still work though. I think  https://github.com/golang/go/issues/38589 might be relevant here?

**Comment by pjweinb** [comment] 2020-11-13 16:30
Perhaps the user's intent is unambiguous, and gopls should respond to that?

Failing that, perhaps a more user-friendly error message?

**Comment by stamblerre** [comment] 2020-11-13 16:49
Ok, I'll add your comment to https://github.com/golang/go/issues/38589, since this issue I think is a duplicate of that one.

**Closed by stamblerre** 2020-11-13 16:49 UTC
Labels: Tools, gopls
