### ISSUE TITLE
x/tools/gopls/internal/regtest/misc: TestSimultaneousEdits failure with "error(s) cleaning sandbox", unlinkat directory not empty

### ISSUE THREAD

**Issue by dmitshur** [golang/go#54277] opened 2022-08-04 23:06 UTC
```
[...]

1 @ 0x1068299 0x107d1a8 0x107a24b 0x10ab2b7 0x1160c8b 0x1160c7d 0x12a47e6 0x106be41
#	0x1068298	syscall.syscall6+0x98						/Users/gopher/workdir/go/src/runtime/sys_darwin.go:44
#	0x107d1a7	syscall.wait4+0x47						/Users/gopher/workdir/go/src/syscall/zsyscall_darwin_amd64.go:43
#	0x107a24a	syscall.Wait4+0x2a						/Users/gopher/workdir/go/src/syscall/syscall_bsd.go:144
#	0x10ab2b6	os.(*Process).wait+0x76						/Users/gopher/workdir/go/src/os/exec_unix.go:43
#	0x1160c8a	os.(*Process).Wait+0x4a						/Users/gopher/workdir/go/src/os/exec.go:132
#	0x1160c7c	os/exec.(*Cmd).Wait+0x3c					/Users/gopher/workdir/go/src/os/exec/exec.go:599
#	0x12a47e5	golang.org/x/tools/internal/gocommand.runCmdContext.func1+0x25	/Users/gopher/workdir/gopath/src/golang.org/x/tools/internal/gocommand/invoke.go:243

--- FAIL: TestSimultaneousEdits (0.76s)
    --- FAIL: TestSimultaneousEdits/default (0.76s)
        runner.go:369: closing the sandbox: error(s) cleaning sandbox: cleaning modcache: <nil>; removing files: unlinkat /Users/gopher/workdir/tmp/gopls-regtest-3738926842/TestSimultaneousEdits/default: directory not empty
FAIL
FAIL	golang.org/x/tools/gopls/internal/regtest/misc	47.972s
```

[2022-08-02T17:23:42-4d0b383-1b7e71e/darwin-amd64-nocgo](https://build.golang.org/log/f1e5f794c6590cf6ef6af5b32593bdb2dc4e691a)

**Comment by findleyr** [comment] 2022-08-05 13:13
Dupe of #54241.

**Closed by findleyr** 2022-08-05 13:13 UTC
Labels: NeedsInvestigation, gopls, Tools
