### ISSUE TITLE
net/http: Handler read doesn't error on context cancel

### ISSUE THREAD

**Issue by gaillard** [golang/go#20831] opened 2017-06-28 17:35 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.8

### What operating system and processor architecture are you using (`go env`)?
linux amd64

### What did you do?

```
package main

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"time"
)

func handle(w http.ResponseWriter, r *http.Request) {
	go func() {
		<-r.Context().Done()
		fmt.Println("HANDLER CTX, err:", r.Context().Err())
	}()

	_, pw := io.Pipe() //just to block the reading of r.Body
	fmt.Println("HANDLER BEFORE COPY()")
	_, err := io.Copy(pw, r.Body)
	fmt.Println("HANDLER AFTER COPY(), err:", err)
}

func serve() {
	if err := http.ListenAndServe(":8080", http.HandlerFunc(handle)); err != nil {
		panic(err)
	}
}

func main() {
	go serve()

	r, err := http.NewRequest(http.MethodPost, "http://127.0.0.1:8080", bytes.NewReader([]byte("hello")))
	if err != nil {
		panic(err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

	_, err = http.DefaultClient.Do(r.WithContext(ctx))
	if err != nil {
		fmt.Println("CLIENT DO(), err:", err)
	}
	time.Sleep(time.Second * 2)
}
```

### What did you expect to see?
The io.Copy unblock with an error.

### What did you see instead?
io.Copy never unblocks.

**Comment by bradfitz** [comment] 2017-06-28 17:38
This isn't a net/http issue.

The r.Body does fail on context cancel. The problem is that the write to your io.PipeWriter blocks forever.

If anything, this bug is that there's no way to create an io.Pipe pair with an associated context.

**Comment by bradfitz** [comment] 2017-06-28 17:40
I'm going to close this, since there's no demonstrated http bug here.

But feel free to file a feature request bug about adding context support to io.Pipe.

Let me know if I misunderstood this bug, though, and we can reopen.

**Closed by bradfitz** 2017-06-28 17:40 UTC

**Comment by gaillard** [comment] 2017-06-28 19:09
Ah I see thanks
So this does work which is closer to our case for anyone interested

```
package main

import (
	"context"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"time"
)

func handle(w http.ResponseWriter, r *http.Request) {
	go func() {
		<-r.Context().Done()
		fmt.Println("HANDLER CTX, err:", r.Context().Err())
	}()

	f, err := ioutil.TempFile("", "testing_")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	fmt.Println("HANDLER BEFORE COPY()")
	_, err = io.Copy(f, r.Body)
	fmt.Println("HANDLER AFTER COPY(), err:", err)
}

func serve() {
	if err := http.ListenAndServe(":8080", http.HandlerFunc(handle)); err != nil {
		panic(err)
	}
}

func main() {
	go serve()

	pr, pw := io.Pipe()
	go func() {
		for {
			_, err := pw.Write([]byte("hi"))
			if err == io.ErrClosedPipe {
				fmt.Println("pipe closed")
				return
			}
			if err != nil {
				panic(err)
			}
		}
	}()

	time.Sleep(time.Second)

	r, err := http.NewRequest(http.MethodPost, "http://127.0.0.1:8080", pr)
	if err != nil {
		panic(err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

	_, err = http.DefaultClient.Do(r.WithContext(ctx))
	if err != nil {
		fmt.Println("CLIENT DO(), err:", err)
	}
	time.Sleep(time.Second * 2)
}

```

**Comment by gaillard** [comment] 2017-06-28 20:01
This also works (http2), which the client doesn't seem to use without the line `http2.ConfigureTransport(tr)`

```
package main

import (
	"context"
	"crypto/tls"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"time"

	"golang.org/x/net/http2"
)

func handle(w http.ResponseWriter, r *http.Request) {
	fmt.Println(r.Proto)
	go func() {
		<-r.Context().Done()
		fmt.Println("HANDLER CTX, err:", r.Context().Err())
	}()

	f, err := ioutil.TempFile("", "testing_")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	fmt.Println("HANDLER BEFORE COPY()")
	_, err = io.Copy(f, r.Body)
	fmt.Println("HANDLER AFTER COPY(), err:", err)
}

func serve() {
	if err := http.ListenAndServeTLS(":443", "server.crt", "server.key", http.HandlerFunc(handle)); err != nil {
		panic(err)
	}
}

func main() {
	go serve()

	pr, pw := io.Pipe()
	go func() {
		for {
			_, err := pw.Write([]byte("hi"))
			if err == io.ErrClosedPipe {
				fmt.Println("pipe closed")
				return
			}
			if err != nil {
				panic(err)
			}
		}
	}()

	time.Sleep(time.Second)

	r, err := http.NewRequest(http.MethodPost, "https://localhost", pr)
	if err != nil {
		panic(err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

	tr := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}
	http2.ConfigureTransport(tr)
	client := &http.Client{Transport: tr}

	_, err = client.Do(r.WithContext(ctx))
	if err != nil {
		fmt.Println("CLIENT DO(), err:", err)
	}
	time.Sleep(time.Second * 2)
}

```
