### ISSUE TITLE
append() changes the element appended previously.

### ISSUE THREAD

**Issue by GingerMoon** [golang/go#33111] opened 2019-07-15 06:55 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
NA

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=amd64
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows

</pre></details>

### What did you do?

Sorry that I can't access play.golang.org.
[a_test.go.txt](https://github.com/golang/go/files/3391090/a_test.go.txt)
I want to append new elements, however, the later appended element can modify the element appended previously.

### What did you expect to see?

for i := 0; i < len(a1); i++ {
    for j := 0; j < len(a2); j++ {
        tmp := a2[j]
        tmp = append(tmp, a1[i])
        result = append(result, tmp)
    }
}

when i is 1, appending tmp should not change the element appended when i is 0

### What did you see instead?
when i is 1, appending tmp changes the element appended when i is 0

**Comment by ALTree** [comment] 2019-07-15 07:12
This is working as intended, and it's a consequence of the fact that slices are not arrays: they are *views*. See https://tour.golang.org/moretypes/7 and the following page:

> An array has a fixed size. **A slice**, on the other hand, **is a dynamically-sized, flexible view into the elements of an array.**

>  A slice does not store any data, **it just describes a section of an underlying array**.
> **Changing the elements of a slice modifies the corresponding elements of its underlying array**.
> **Other slices that share the same underlying array will see those changes**. 

If two slices share the same underlying array (even if the "views" they represents start at different offsets), changing the array using one slice will affect the other.

Closing here, since this is WAI.

**Closed by ALTree** 2019-07-15 07:12 UTC

**Comment by GingerMoon** [comment] 2019-07-15 09:09
I don't know the meaning of WAI. However, if you want to close the ticket, just close it. Nonsense doesn't make any sense.
Anyway, the scenario in the problem description is similar to the code below, but the behavior is different.  Are you able to explain?

func TestChan(t *testing.T) {
	a := [][]int{}
	a1 := []int{1}
	a = append(a, a1)

	a2 := a1
	a2 = append(a2, 2)
	a = append(a, a2)

	a3 := a1
	a3 = append(a3, 3)
	a = append(a, a3)
	fmt.Println(a) // [[1] [1 2] [1 3]] 
}

**Comment by randall77** [comment] 2019-07-15 13:54
WAI = "working as intended"

You should probably read https://blog.golang.org/go-slices-usage-and-internals if you haven't already.
Your last example makes sense if a1 has a capacity of 1. Then each append will allocate a new backing store.

If you allocated a1 with `a1 := make([]int, 1, 2); a1[0] = 1` (length=1, capacity=2) then you would see a different behavior.

**Comment by av86743** [comment] 2019-07-15 22:43
@GingerMoon 

The gist is that exact description of semantics of append in golang is hardly possible to describe in simple intuitive terms.  Instead, you are given a number of prescribed scenarios when append is - kind of - guaranteed to work according to some intuition (whatever that means.)

If you want to formalize semantics of append in golang, you need to consider linearity of underlying array stores for slices. This will give you sufficient condition(s) for append to behave the way you expect (which probably includes an intuition of "always copy, never destroy an original".)

**Comment by ianlancetaylor** [comment] 2019-07-15 22:52
To be clear, the behavior of `append` is specified exactly at https://golang.org/ref/spec#Appending_and_copying_slices :

> If the capacity of s is not large enough to fit the additional values, append allocates a new, sufficiently large underlying array that fits both the existing slice elements and the additional values. Otherwise, append re-uses the underlying array.

**Comment by av86743** [comment] 2019-07-15 23:16
I wonder how do you expect anyone to apply intuition of "If capacity ... is not large enough ..." by looking at the code.

**Comment by av86743** [comment] 2019-07-15 23:28
Earlier issue on the subject: https://github.com/golang/go/issues/32296 .  You can keep dismissing the problem, however this will not resolve it.

**Comment by ianlancetaylor** [comment] 2019-07-16 01:35
I'm sorry you are having trouble.  The language has worked this way from the start.  It is not something we can change now.

In general, we expect people to read https://blog.golang.org/slices.  There are simple idioms that permit correct use of `append`.

**Comment by av86743** [comment] 2019-07-16 05:25
> I'm sorry you are having trouble. 

In case this was addressed to myself: apparently, it is not me who is having trouble.  As it is not me who refuses to admit that implementation of append in golang is not agreeable with common intuition on how append should work (as this and earlier issues indicate), and who is not capable to explain how to reason about behavior of the code which uses append with such semantics.

**Comment by ianlancetaylor** [comment] 2019-07-16 13:59
@av86743 We've pointed you to various resources about how `append` works in Go.  Millions of programmers have been using it successfully for more than five years.  I encourage you to consider the possibility that although your initial assumptions about `append` did not match the language, it is nevertheless possible to use `append` correctly in a Go program.

**Comment by av86743** [comment] 2019-07-16 17:04
@ianlancetaylor 

> We've pointed you to various resources about how append works in Go ...

But did you notice that I did not ask you to? As I do not need any of these either.  I know how your software works, as well as how it does not work.  It is trivially open source, after all. 

> ... although your initial assumptions about `append` did not match the language ...

What "initial assumptions about `append`"?  I have no habit of making assumptions, when it comes to software like yours.  Your `append` is whatever it is, however logical or illogical you made it. I know how to use it because I know how it is - likely - implemented.  However, those "millions" who don't - well, those definitely will have problems with `append`.  Except that you wouldn't hear from most of those though - as they will "assume" that there is golang "bug" which they have to work around.

> ... it is nevertheless possible to use append correctly ...

Correctly by an accident.  After several trial-and-errors.  For the most of "millions".  This is how most of Google anything works, right?

**Comment by ianlancetaylor** [comment] 2019-07-16 17:29
We must agree to disagree.

You may find it more useful to continue this discussion on a forum; see https://golang.org/wiki/Questions.

**Comment by GingerMoon** [comment] 2019-09-02 02:08
@ALTree 
Really sorry that I misunderstood your reply "Closing here, since this is WAI.". 
Actually in my dictionary, WAI is "what an idiot"...
Apologies for my poor English...
