### ISSUE TITLE
runtime: runtime.Caller() => "<autogenerated>"

### ISSUE THREAD

**Issue by thockin** [golang/go#16723] opened 2016-08-16 07:01 UTC
I was playing with a method that wants to print the file:line of the caller.  `runtime.Caller(1)` seems like it should do the trick, but I get '<autogenerated>:2'.  If I call `runtime.Caller(2)` instead it seems to work, but I am reluctant to depend on that.

It looks like this has to do with being an interface method: https://play.golang.org/p/I5XPdWR_O0

Is there a generic way to get the actual caller, safely, in all cases?

---
1. What version of Go are you using (`go version`)?

go version go1.6.1 linux/amd64
1. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/thockin/src/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by rsc** [comment] 2016-11-11 15:48
The interface call calls a wrapper which calls the direct call. The wrapper is auto-generated. Whether you consider the wrapper the "actual caller" depends on your point of view I guess.

You can avoid the wrappers by defining the methods on *fooMether instead of fooMether.

https://play.golang.org/p/_9UqleNykz

I'm not sure what to do about this in the mean time. We'll have to look at callers again when we look at non-leaf inlining this winter. Maybe then would be a good time to revisit the behavior of runtime.Caller with respect to eliding autogenerated wrappers.

/cc @aclements

**Comment by aclements** [comment] 2017-06-14 13:16
Bumping to Go 1.10 since this isn't a regression and there's some concern that this may affect code that's already compensating for this. The general consensus is that this should be fixed, however, so that the traceback APIs reflect the programmer's model of the stack rather than the implementation's model (like how the skip parameter now expands out inlined frames to match the programmer's model).

Early in the 1.10 cycle we should put in something like the CLs I posted above.

**Closed** 2017-09-22 22:17 UTC
Labels: early-in-cycle, NeedsFix
