### ISSUE TITLE
cmd/doc: allow constructors to return error

### ISSUE THREAD

**Issue by rsc** [golang/go#27988] opened 2018-10-03 17:56 UTC
go doc os
should show Open under type File. It did in Go 1.10 but no longer does.

The recent CL that makes constructors have only one result is too aggressive.
Probably it should allow any number of additional results as long as they are not
types from the current package.

/cc @griesemer @agnivade

**Comment by agnivade** [comment] 2018-10-03 18:35
Duplicate of https://github.com/golang/go/issues/27928. I will take a look.

**Closed by agnivade** 2018-10-03 18:35 UTC
