### ISSUE TITLE
x/tools/cmd/goimports: bad sorting cannot be fixed completely

### ISSUE THREAD

**Issue by hidu** [golang/go#36140] opened 2019-12-14 13:15 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.13.4
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

I have some code with wrong import group,
this is the demo code:
```
package main

import (
	"fmt"

	"golang.org/x/tools/go/ast/astutil"
	
	"abc.com/a/d/dao"
	"abc.com/a/d/model"
	"golang.org/x/tools/go/ast/inspector"
	"strings"
)


type aliasA  = astutil.ApplyFunc
var aliasB   = dao.Table
var aliasC   = model.Redis
var aliasD   = inspector.AST

func main(){
	fmt.Println("hello")

	fmt.Println(strings.Join([]string{"hello","golang"}," "))
}
```

### What did you expect to see?
<pre>
$ goimports -local abc.com/a/d demo.go
</pre>

```
package main

import (
	"fmt"
	"strings" 

	"golang.org/x/tools/go/ast/astutil"
        "golang.org/x/tools/go/ast/inspector"

	"abc.com/a/d/dao"
	"abc.com/a/d/model"
)

type aliasA = astutil.ApplyFunc
var aliasB = dao.Table
var aliasC = model.Redis
var aliasD   = inspector.AST

func main() {
	fmt.Println("hello")
	fmt.Println(strings.Join([]string{"hello", "golang"}, " "))
}
```

### What did you see instead?
the `strings`  and `golang.org/x/tools/go/ast/inspector` are at the wrong group:
```
package main

import (
	"fmt"

	"golang.org/x/tools/go/ast/astutil"

	"strings"

	"golang.org/x/tools/go/ast/inspector"

	"abc.com/a/d/dao"
	"abc.com/a/d/model"
)

type aliasA = astutil.ApplyFunc
var aliasB = dao.Table
var aliasC = model.Redis
var aliasD   = inspector.AST

func main() {
	fmt.Println("hello")
	fmt.Println(strings.Join([]string{"hello", "golang"}, " "))
}
```

if the raw file's import section is like this, `goimports` can got the right code:
```
import (
	"fmt"
	"golang.org/x/tools/go/ast/astutil"
	"abc.com/a/d/dao"
	"abc.com/a/d/model"
	"golang.org/x/tools/go/ast/inspector"
	"strings"
)
```

**Comment by agnivade** [comment] 2019-12-14 16:14
I think this is intended. If your import crosses a newline boundary, it is considered in a separate group. @bradfitz @heschik can confirm.

**Comment by dmitshur** [comment] 2019-12-14 18:38
From what I know, the GoLand IDE does not use `goimports` directly; it implements its own internal version. If that's the case, in order to change the behavior of GoLand, this issue should be reported to their issue tracker or equivalent.

**Comment by hidu** [comment] 2019-12-15 00:14
For some reason，I have disabled the  sorting imports function on the GoLand IDE。
I don't think we need to worry about whether we use ide or not。
**We use this tool to fix the wrong group， don't we？**

**Comment by hidu** [comment] 2019-12-15 00:31
I have updated the issue，deleted description of IDE。
I just have some go files with wrong import group need fix。

**Comment by heschik** [comment] 2019-12-16 18:57
Duplicate of #20818.

**Closed by heschik** 2019-12-16 18:57 UTC
Labels: NeedsInvestigation, Tools
