### ISSUE TITLE
os/exec: StdinPipe on Windows is not successful

### ISSUE THREAD

**Issue by liwux** [golang/go#19452] opened 2017-03-08 06:36 UTC
Please answer these questions before submitting your issue. Thanks!

What version of Go are you using (go version)?

Go 1.8

My code:

```
package main
import (

	"os"
	"os/exec"
	"io"
)
func main() {
	command :="openconnect"
	param := []string{"https://192.168.0.100:1443","-u","test","--passwd-on-stdin"}
	cmd :=exec.Command(command,param...)
	cmd.Stdout = os.Stdout
	input, _ := cmd.StdinPipe()
	cmd.Start()
	io.WriteString(input,"123\n")
	cmd.Wait()
}
```

can not automatically standard input when the command starts.   

I changed a kind of writing  

the code 

```
package main

import (
	"fmt"
	"io"
	"log"
	"os/exec"
	"os"
)

func main() {
	command :="openconnect"
	param := []string{"https://192.168.0.100:1443","-u","test","--passwd-on-stdin"}
	cmd :=exec.Command(command,param...)
	stdin, err := cmd.StdinPipe()
	if err != nil {
		log.Fatal(err)
	}
	go func() {
		defer stdin.Close()
		io.WriteString(stdin, "123\n")
	}()
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err = cmd.Start(); err != nil { //Use start, not run
		fmt.Println("An error occured: ", err) //replace with logger, or anything you want
	}
	cmd.Wait()

}
```

The two are not successful  .
when I input "123" by Keyboard ,is ok.  
who can help me,thanks.

**Comment by mvdan** [comment] 2017-03-08 12:55
Did you find a specific bug in the standard library? If so, please provide a shorter piece of code to reproduce it.

Otherwise, please take it to https://github.com/golang/go/wiki/Questions as that's where you should go for chunks of code that don't work as you expected. It's likely an issue with your code.

**Comment by ianlancetaylor** [comment] 2017-03-08 14:33
You say "are not successful" but you don't say what happens.  What precisely happens?  Do you get an error?  Does the program misbehave in some way?

I don't understand your program: you call `StdinPipe` but you don't write anything to the pipe.  What are you really trying to do?

**Comment by liwux** [comment] 2017-03-09 02:11
@ianlancetaylor   I don't get any error , just don't write anything to the pipe 
What's the problem with this :
```
stdin, err := cmd.StdinPipe()
io.WriteString(stdin, "123\n")
```

**Comment by ianlancetaylor** [comment] 2017-03-09 05:34
I apologize, I did miss the fact that you do write to the pipe.

I tried running this variant of your program on GNU/Linux, and it printed `123`.  I do not know why your program is not working.  I don't know what the openconnect program is.

    package main

    import (
            "fmt"
            "io"
            "log"
            "os/exec"
            "os"
    )

    func main() {
            command :="cat"
            param := []string{}
            cmd :=exec.Command(command,param...)
            stdin, err := cmd.StdinPipe()
            if err != nil {
                    log.Fatal(err)
            }
            go func() {
                    defer stdin.Close()
                    io.WriteString(stdin, "123\n")
            }()
            cmd.Stdout = os.Stdout
            cmd.Stderr = os.Stderr
            if err = cmd.Start(); err != nil { //Use start, not run
                    fmt.Println("An error occured: ", err) //replace with logger, or anything you want
            }
            cmd.Wait()

    }

**Comment by ianlancetaylor** [comment] 2017-03-09 05:35
Two things you should certainly do are check the error return of `io.WriteString` and `cmd.Wait`.

**Comment by liwux** [comment] 2017-03-09 09:06
@ianlancetaylor     Run on GNU/Linux and OSX  and it printed 123  ,but run on windows it printed nothing

**Comment by liwux** [comment] 2017-03-09 09:10
@ianlancetaylor  thanks...
it may be the openconnect program's problem

**Comment by LEGOlord208** [comment] 2017-03-17 11:40
I'm an idiot, so don't trust anything I say.  
But maybe... just *maybe* it's because you need `\r\n` on Windows?

**Comment by bradfitz** [comment] 2017-03-21 05:25
I'm going to close this for now until there's evidence pointing at it being Go's problem.

Feel free to reopen if you have more info.

**Closed by bradfitz** 2017-03-21 05:25 UTC
Labels: WaitingForInfo
