### ISSUE TITLE
encoding/json: "string" option doesn't apply to *big.Int 

### ISSUE THREAD

**Issue by xoba** [golang/go#57970] opened 2023-01-24 10:58 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20rc3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mra/Library/Caches/go-build"
GOENV="/Users/mra/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mra/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mra/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/mra/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/mra/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20rc3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tj/h518gq8n7h1_8t28ql6lnnb40000gn/T/go-build3734188390=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

from https://pkg.go.dev/encoding/json (see quote below), i expected *big.Int to be quoted with the "string" tag option, since by any reasonable interpretation, *big.Int is an "integer". on the other hand, *big.Int does render as arbitrarily large integers in json anyway, but that introduces incompatibility with javascript which uses IEEE-754 floats. 

> The "string" option signals that a field is stored as JSON inside a JSON-encoded string. It applies only to fields of string, floating point, integer, or boolean types. This extra level of encoding is sometimes used when communicating with JavaScript programs

see https://go.dev/play/p/dDMU2qYMcqL for how encoding/json package
ignores "string" tag option for *big.Int.

### What did you expect to see?
{"Value":"2"}

### What did you see instead?
{"Value":2}

**Comment by seankhliao** [comment] 2023-01-24 12:04
Duplicate of #36099

**Closed by seankhliao** 2023-01-24 12:04 UTC
