### ISSUE TITLE
cmd/compile: binary.BigEndian.UintXX should compile to a load+bswap on amd64

### ISSUE THREAD

**Issue by rasky** [golang/go#17151] opened 2016-09-18 21:07 UTC
Given the existing pattern-matching for `binary.LittleEndian.UintXX` functions, the functionality could be extended to support also `binary.BigEndian`, by doing a straight load followed by a `BSWAP` instruction.

**Comment by dsnet** [comment] 2016-10-04 20:38
Possible duplicate of #14366.

**Comment by dsnet** [comment] 2016-10-04 20:54
Related to #16832

**Closed** 2017-02-14 22:18 UTC
Labels: Performance
