### ISSUE TITLE
cmd/go: cannot exclude version of module when it is the latest version

### ISSUE THREAD

**Issue by myitcv** [golang/go#27000] opened 2018-08-15 11:55 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.11rc1 linux/amd64
```

### Does this issue reproduce with the latest release?

Per above

### What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/tmp.MK5BVQAC8k/hello/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build937954680=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

This is based on the vgo tour, using `cmd/go` instead:

```
cd $(mktemp -d)
mkdir hello
cd hello
go mod init github.com/myitcv/hello

cat <<EOD > hello.go
package main

import (
        "fmt"
        "rsc.io/quote"
)

func main() {
        fmt.Println(quote.Hello())
}
EOD

go mod tidy
go list -m all

go get -u
go list -m all
```

Now let's assume we want to exclude `rsc.io/sampler@v1.99.99`:

```
go mod edit -exclude rsc.io/sampler@v1.99.99
```

Now we list the available versions:

```
$ go list -m -versions rsc.io/sampler
go: github.com/myitcv/hello() depends on excluded rsc.io/sampler(v1.99.99) with no newer version available
```

Hmm. No luck.

Ok, let's try to upgrade across the board:

```
$go get -u
go: github.com/myitcv/hello() depends on excluded rsc.io/sampler(v1.99.99) with no newer version available
```

Again, no luck.

Let's try and explicitly put ourselves onto `@latest` then rinse and repeat the above steps:

```
$ go mod edit -require rsc.io/sampler@latest
$ go list -m -versions rsc.io/sampler
go: github.com/myitcv/hello() depends on excluded rsc.io/sampler(v1.99.99) with no newer version available
$ go get -u
go: github.com/myitcv/hello() depends on excluded rsc.io/sampler(v1.99.99) with no newer version available
```

### What did you expect to see?

A working build with `rsc.io/sampler@v1.99.99` excluded.

### What did you see instead?

Per above; not able to effectively exclude `rsc.io/sampler@v1.99.99`.

Unless I'm missing something, this feels like a regression?

**/cc** @rsc @bcmills

**Comment by rsc** [comment] 2018-08-17 15:14
Duplicate of #26454. Leaving for Go 1.12.

**Closed by rsc** 2018-08-17 15:14 UTC
Labels: modules
