### ISSUE TITLE
net/url: URL.String() escapes Unicode domain

### ISSUE THREAD

**Issue by sollniss** [golang/go#65999] opened 2024-02-28 15:07 UTC
### Go version

go version go1.22.0 windows/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=
GOARCH=amd64
GOBIN=
GOCACHE=C:\Users\solln\AppData\Local\go-build
GOENV=C:\Users\solln\AppData\Roaming\go\env
GOEXE=.exe
GOEXPERIMENT=
GOFLAGS=
GOHOSTARCH=amd64
```

### What did you do?

https://go.dev/play/p/sDjQRu9ElyH

### What did you see happen?

`http://%E3%81%82%E3%81%84%E3%81%86.com/`

### What did you expect to see?

`http://あいう.com/`
or
`http://xn--l8jeg.com/`

**Comment by sollniss** [comment] 2024-02-28 15:13
Not sure if escaped by design, since there was no mention of it in https://github.com/golang/go/issues/30922.
However, the docs say "String reassembles the [URL] into a **valid** URL string" and escaped hostnames/domains are not RFC conform.

**Comment by cagedmantis** [comment] 2024-02-29 15:49
https://pkg.go.dev/net/url#URL.String States that "Any non-ASCII characters in host are escaped." This is working as intended.

I'm going to close this issue. Please feel free to reopen it if you believe this was closed in error.

**Closed by cagedmantis** 2024-02-29 15:49 UTC

**Comment by seankhliao** [comment] 2024-02-29 16:26
percent encoded hostnames are rfc conformant to https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2
