### ISSUE TITLE
x/pkgsite: license not detected for github.com/huifurepo/bspay-go-sdk

### ISSUE THREAD

**Issue by QuantumGhost** [golang/go#57570] opened 2023-01-04 09:56 UTC
### What is the URL of the page with the issue?

https://pkg.go.dev/github.com/huifurepo/bspay-go-sdk@v1.0.2/BsPaySdk

### What is your user agent?

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`

### Screenshot

<img width="1873" alt="image" src="https://user-images.githubusercontent.com/2939865/210529177-646f4e3a-d704-4f67-98cd-e7eb3eba1fb2.png">

### What did you do?

Open the [docs page for github.com/huifurepo/bspay-go-sdk](https://pkg.go.dev/github.com/huifurepo/bspay-go-sdk@v1.0.2/BsPaySdk)

### What did you expect to see?

github.com/huifurepo/bspay-go-sdk detected as MIT licensed, and pkg.go.dev show its docs.

### What did you see instead?

> Documentation not displayed due to license restrictions.
>
> See our [license policy](https://pkg.go.dev/license-policy).

**Comment by QuantumGhost** [comment] 2023-01-04 10:03
deps.dev also [detected its license correctly.](https://deps.dev/go/github.com%2Fhuifurepo%2Fbspay-go-sdk/v1.0.2)

**Comment by seankhliao** [comment] 2023-01-04 10:26
the tag for v1.0.2 was moved, the observed and cached commit can be seen at https://proxy.golang.org/github.com/huifurepo/bspay-go-sdk/@v/v1.0.2.info

at that point, there was no license file, and the proxy infrastructure doesn't support changing the contents of publicly known tags.

closing as working as intended.

**Closed by seankhliao** 2023-01-04 10:26 UTC
Labels: pkgsite

**Comment by QuantumGhost** [comment] 2023-01-05 07:05
Thanks~
