### ISSUE TITLE
cmd/go: "fmt" should support "-mod=vendor"

### ISSUE THREAD

**Issue by go101** [golang/go#34838] opened 2019-10-11 02:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
$ go fmt main.go
go: finding github.com/golang/glog latest
^C
$ go fmt -mod=vendor  main.go
flag provided but not defined: -mod
usage: go fmt [-n] [-x] [packages]
Run 'go help fmt' for details.
```

### What did you expect to see?

Doesn't connect network when run "go fmt", at least doesn't when use the "-mod=vendor" option.

### What did you see instead?

Either connects network or fails to run.

**Comment by bcmills** [comment] 2019-10-11 03:00
Duplicate of #27841

**Closed by bcmills** 2019-10-11 03:00 UTC
