### ISSUE TITLE
cmd/go: TestLocalImportsHard flaky on Windows?

### ISSUE THREAD

**Issue by bradfitz** [golang/go#17419] opened 2016-10-12 15:04 UTC
Saw flake in a trybot run on windows-386:

```
--- FAIL: TestLocalImportsHard (0.68s)
    go_test.go:244: running testgo [build -o ./hard.exe testdata\local\hard.go]
    go_test.go:151: remove ./hard.exe: The process cannot access the file because it is being used by another process.
FAIL
FAIL    cmd/go  62.506s
```

Related: #11217 ? Similar at least.

/cc @alexbrainman

**Comment by alexbrainman** [comment] 2016-10-13 05:47
> Related: #11217 ? Similar at least.

I do not see how this is similar to #11217. In #11217 different tests were creating executable with the same name, running it and deleting it. This is not happening here. Only TestLocalImportsHard creates ./hard.exe, runs it and deletes it.

I cannot reproduce it here, but I will keep looking into it.

Alex

**Comment by mattn** [comment] 2016-10-17 10:45
I'm not sure how trybot is working on gpc, when the tests got timeout, all of processes will be killed correctly?

**Comment by rsc** [comment] 2016-10-21 13:59
@mattn, @bradfitz can say for sure, but I believe we start a whole new Windows VM for each trybot run. There shouldn't be any previous runs involved.

@alexbrainman, it's not true that only TestLocalImportsHard creates hard.exe. So does TestBadImportsHard. They should run separately, and in any case, TestLocalImportsHard should be first, and TestBadImportsHard should not begin until the former is done. Regardless, I'll send a CL using different executable names. Then maybe we can close this until we see the flake again.

**Comment by bradfitz** [comment] 2016-10-22 01:00
> @mattn, @bradfitz can say for sure, but I believe we start a whole new Windows VM for each trybot run. There shouldn't be any previous runs involved.

Correct.

**Comment by alexbrainman** [comment] 2016-10-22 03:25
> @alexbrainman, it's not true that only TestLocalImportsHard creates hard.exe. So does TestBadImportsHard.

Perhaps I am mistaken, but TestBadImportsHard calls copyBad (before it gets around to create hard.exe), but copyBad never returns on windows - it calls t.Skipf.

Alex

**Comment by bradfitz** [comment] 2017-05-19 19:01
Just hit this again in https://storage.googleapis.com/go-build-log/d61981d9/windows-386-gce_1a546ff6.log

**Comment by rsc** [comment] 2017-06-23 00:31
Cannot reproduce with:

VM=$(gomote create windows-386-gce)
gomote push $VM
gomote run $VM go/src/make.bat
gomote run -path '$WORKDIR/go/bin,$PATH' $VM go/bin/go test -run=TestLocalImportsHard -count=100 cmd/go
gomote run -path '$WORKDIR/go/bin,$PATH' $VM go/bin/go test -timeout=20m -run=TestLocalImportsHard -v -count=1000 cmd/go

**Comment by bradfitz** [comment] 2017-07-12 21:49
Just got another:

https://storage.googleapis.com/go-build-log/c2e01024/windows-amd64-gce_7605eed0.log
```
--- FAIL: TestLocalImportsHard (0.45s)
	go_test.go:310: running testgo [build -o ./hard.exe testdata\local\hard.go]
	go_test.go:197: remove ./hard.exe: Access is denied.
FAIL
FAIL	cmd/go	95.629s
```

**Comment by mattn** [comment] 2017-07-13 02:17
Hmm, I ran this for 20 minutes. But it doesn't reproduced.
(FYI: I use symantec endpoint protection)

myexe.go
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	time.Sleep(time.Second)
	fmt.Println("ok")
}
```

test.go
```go
package main

import (
	"fmt"
	"log"
	"os"
	"os/exec"
)

func main() {
	for {
		b, err := exec.Command("go", "build", "-o", "myexe.exe", "myexe.go").Output()
		if err != nil {
			log.Fatal(err)
		}
		b, err = exec.Command("myexe.exe").Output()
		if err != nil {
			log.Fatal(err)
		}
		fmt.Print(string(b))
		err = os.Remove("myexe.exe")
		if err != nil {
			log.Fatal(err)
		}
	}
}
```

**Comment by rsc** [comment] 2017-12-01 01:47
No update since June when we could not reproduce the problem. Timed out.

(Starting to wonder about virus scanners.)

**Closed by rsc** 2017-12-01 01:47 UTC
Labels: HelpWanted, NeedsFix, OS-Windows, Testing
