### ISSUE TITLE
proposal: allow constants in struct tags

### ISSUE THREAD

**Issue by pengux** [golang/go#50463] opened 2022-01-06 10:08 UTC
### Author background

- **Would you consider yourself a novice, intermediate, or experienced Go programmer?**: Experienced
- **What other languages do you have experience with?**: PHP, JS, Dart

### Related proposals

- **Has this idea, or one like it, been proposed before?**: No
  - **If so, how does this proposal differ?**
- **Does this affect error handling?**: No
  - **If so, how does this differ from previous error handling proposals?**
- **Is this about generics?**: No
  - **If so, how does this relate to the accepted design and other generics proposals?**

### Proposal

- **What is the proposed change?**: To allow use of constants in struct tags
- **Who does this proposal help, and why?**: It helps developers to use same constant for key names, thus reducing risk of typo errors
- **Please describe as precisely as possible the change to the language.**: When defining a struct tag, allows for string concatenation with constant string values, for example:
```
const bar = "bar"
type Foo struct{
  Bar string `json:"`+bar+"`
}
```
- **What would change in the language spec?**: In the section about struct tags, it will need to be changed to allow for expressions which results in string literals
- **Please also describe the change informally, as in a class teaching Go.**: Allow usage of constant string in struct tags
- **Is this change backward compatible?**: Yes
  - Breaking the Go 1 compatibility guarantee is a large cost and requires a large benefit.
    Show example code before and after the change.
  - **Before**
  - **After**
- **Orthogonality: how does this change interact or overlap with existing features?**: It extends struct tags feature
- **Is the goal of this change a performance improvement?**: No
  - **If so, what quantifiable improvement should we expect?**
  - **How would we measure it?**

### Costs

- **Would this change make Go easier or harder to learn, and why?**: It should not affect the learning curve
- **What is the cost of this proposal? (Every language change has a cost).**: Expressions in struct tags would need to be evaluated at compile time.
- **How many tools (such as vet, gopls, gofmt, goimports, etc.) would be affected?**: gomodifytags would need to consider tags with expressions
- **What is the compile time cost?**: I don't know
- **What is the run time cost?**: Should not affect run time
- **Can you describe a possible implementation?**: for struct tags, evaluate it as a string literal expression
- **Do you have a prototype? (This is not required.)**: No

**Comment by seankhliao** [comment] 2022-01-06 15:55
Duplicate of #4740

**Closed by seankhliao** 2022-01-06 15:55 UTC
Labels: Proposal
