### ISSUE TITLE
tour: no editor window on concurrency/7

### ISSUE THREAD

**Issue by Darigaaz** [golang/go#11244] opened 2015-06-17 02:19 UTC
Context: /concurrency/7

Editor window is hidden and empty when I open this exercise

**Comment by Darigaaz** [comment] 2015-06-17 02:24
Context: /concurrency/8

On the next lessoni realize it should not be any editor on  /concurrency/7.
But it would be nice to have one with text "go to the next lesson. exercise will be there".

**Comment by adg** [comment] 2015-06-17 02:30
@campoy some people do find this confusing. I wonder if we should do anything or leave it working as intended?

**Comment by minux** [comment] 2015-06-17 02:54
See also #10983.

**Comment by campoy** [comment] 2015-07-28 04:37
A "continue description on next page" has been added, closing this bug and we'll see if someone reopens it.

**Closed by campoy** 2015-07-28 04:37 UTC
