### ISSUE TITLE
Map not panic

### ISSUE THREAD

**Issue by mumusa** [golang/go#31652] opened 2019-04-24 11:33 UTC
go version 1.11.4
mac version :10.13.6
vscode version : 2018.3 
```
type SpModel struct {
	Name string
}
func mapTest() {
	spMap := make(map[int64]*SpModel, 0)
	spList := make([]int64, 0)
	spList = append(spList, 11)

	for _, record := range spList {
		info := new(SpModel)
		info.Name = spMap[record].Name
	}
}
```
Debug mode
why not panic

**Comment by choleraehyq** [comment] 2019-04-24 12:41
Can't reproduce.
```
➜  test cat map.go
package main

type SpModel struct {
	Name string
}

func main() {
	spMap := make(map[int64]*SpModel, 0)
	spList := make([]int64, 0)
	spList = append(spList, 11)

	for _, record := range spList {
		info := new(SpModel)
		info.Name = spMap[record].Name
	}
}
➜  test go run map.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x104f729]

goroutine 1 [running]:
main.main()
	/Users/cholerae/Documents/test/map.go:14 +0xf9
exit status 2
```

**Comment by ericmdantas** [comment] 2019-04-24 13:00
Also panicking in https://play.golang.org/p/eG6z2Jsc1Lq.

**Comment by martisch** [comment] 2019-04-24 13:47
`info.Name` =  spMap[record].Name`
If record is not found in spMap then spMap[record] returns nil and referencing the field 'Name' on a nil pointer will give an error for a nil pointer dereference.

Closing this issue as working as intended.

Unlike many projects, the Go project does not currently use GitHub Issues for general discussion or asking questions. Please see https://github.com/golang/go/wiki/Questions for more information and links to lists and forums for asking questions related to go.

**Closed by martisch** 2019-04-24 13:47 UTC

**Comment by mumusa** [comment] 2019-04-25 01:32
> Can't reproduce.
> 
> ```
> ➜  test cat map.go
> package main
> 
> type SpModel struct {
> 	Name string
> }
> 
> func main() {
> 	spMap := make(map[int64]*SpModel, 0)
> 	spList := make([]int64, 0)
> 	spList = append(spList, 11)
> 
> 	for _, record := range spList {
> 		info := new(SpModel)
> 		info.Name = spMap[record].Name
> 	}
> }
> ➜  test go run map.go
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x104f729]
> 
> goroutine 1 [running]:
> main.main()
> 	/Users/cholerae/Documents/test/map.go:14 +0xf9
> exit status 2
> ```

you can try this

![WX20190425-093145](https://user-images.githubusercontent.com/13701882/56703783-fe150580-673c-11e9-8648-88737a89eb35.png)

**Comment by mumusa** [comment] 2019-04-25 01:39
> Also produces a panic here.
> 
> Closing this issue as working as intended.
> 
> Feel free to reopen with more information how to reproduce this especially if it still happens on another machine/environment or go1.12 and exact steps to reproduce.
> 
> Unlike many projects, the Go project does not currently use GitHub Issues for general discussion or asking questions. Please see https://github.com/golang/go/wiki/Questions for more information and links to lists and forums for asking questions related to go.

I know it panic when it build , but it show bad access when i debug 
![Uploading WX20190425-093546.png…]()

**Comment by mumusa** [comment] 2019-04-25 01:40
> Also produces a panic here.
> 
> Closing this issue as working as intended.
> 
> Feel free to reopen with more information how to reproduce this especially if it still happens on another machine/environment or go1.12 and exact steps to reproduce.
> 
> Unlike many projects, the Go project does not currently use GitHub Issues for general discussion or asking questions. Please see https://github.com/golang/go/wiki/Questions for more information and links to lists and forums for asking questions related to go.

I know it panic when it build , but it show bad access when i debug 

![WX20190425-093546](https://user-images.githubusercontent.com/13701882/56704025-294c2480-673e-11e9-9fa5-db78544e06ca.png)

**Comment by mumusa** [comment] 2019-04-25 01:41
> Also produces a panic here.
> 
> Closing this issue as working as intended.
> 
> Feel free to reopen with more information how to reproduce this especially if it still happens on another machine/environment or go1.12 and exact steps to reproduce.
> 
> Unlike many projects, the Go project does not currently use GitHub Issues for general discussion or asking questions. Please see https://github.com/golang/go/wiki/Questions for more information and links to lists and forums for asking questions related to go.

I know it panic when it build , but it show bad access when i debug 

![WX20190425-093546](https://user-images.githubusercontent.com/13701882/56704069-4b45a700-673e-11e9-8fe2-6ac672271cb7.png)

**Comment by martisch** [comment] 2019-04-25 04:45
That looks like stepping through the code with a debugger or having a break point set. Both is specific to the editor and/or debugger. Please try to reproduce with go tools only outside the IDE for further reports to go/issues as it does not seem to be problem with the go toolchain.

**Comment by mumusa** [comment] 2019-04-25 10:52
> That looks like stepping through the code with a debugger or having a break point set. Both is specific to the editor and/or debugger. Please try to reproduce with go tools only outside the IDE for further reports to go/issues as it does not seem to be problem with the go toolchain.

Thanks for the reply, I see
