### ISSUE TITLE
affected/package: go get panic when download my project

### ISSUE THREAD

**Issue by godcong** [golang/go#56763] opened 2022-11-16 14:56 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
I added "golang.org/x/exp/slog" in my project.
When I use go get to download this project at other project.
It returns this panic infomation:

```
panic: internal error: can't find reason for requirement on golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc00054ac60?, 0xc000894378?}, {0xc0001c13e0?, 0xc000417e10?}})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1760 +0x114
cmd/go/internal/modget.(*resolver).updateBuildList(0xc000564500, {0xb2e690, 0xc0001a0000}, {0x0, 0x0, 0x0})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x597
cmd/go/internal/modget.(*resolver).resolveQueries(0xc000564500, {0xb2e690, 0xc0001a0000}, {0xc0001b2048, 0x1, 0x472465?})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1243 +0x1e5
cmd/go/internal/modget.runGet({0xb2e690, 0xc0001a0000}, 0xc0001cc480?, {0xc00019c170, 0x1, 0x1})
        /usr/local/go/src/cmd/go/internal/modget/get.go:314 +0x40b
main.invoke(0xe28fa0, {0xc00019c160, 0x2, 0x2})
        /usr/local/go/src/cmd/go/main.go:225 +0x34e
main.main()
        /usr/local/go/src/cmd/go/main.go:179 +0x7d1
```

### What did you expect to see?
Fix and complete the update of my project

### What did you see instead?
Panic at go get last version

**Comment by seankhliao** [comment] 2022-11-16 15:12
can you provide a reproducer?

**Comment by bcmills** [comment] 2022-11-16 17:25
Duplicate of #56494

**Closed by bcmills** 2022-11-16 17:25 UTC
