### ISSUE TITLE
how to avoid sending dotfiles on a http response

### ISSUE THREAD

**Issue by deepnum** [golang/go#35649] opened 2019-11-17 11:59 UTC
Like files in a .git folder or a .filename

**Comment by deepnum** [comment] 2019-11-17 12:05
```
func containsDot(r *http.Request) {
}

```

**Comment by ALTree** [comment] 2019-11-17 13:03
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2019-11-17 13:03 UTC

**Comment by deepnum** [comment] 2019-11-17 13:44
@ALTree please give me an answer or a resource to learn

**Comment by ALTree** [comment] 2019-11-17 13:48
Here's a list of places were you can ask questions about Go: https://github.com/golang/go/wiki/Questions#asking-questions
