### ISSUE TITLE
x/tools/gopls: add configuration to ignore certain workspace folders

### ISSUE THREAD

**Issue by stamblerre** [golang/go#37697] opened 2020-03-05 18:29 UTC
The workspace load looks at all files in a directory, but it seems it's not correctly excluding ignored files. VS Code also allows the user to ignore files with the `"files.exclude"` setting, which the language client should probably handle in some way? But that needs to be confirmed.

See https://github.com/microsoft/vscode-go/issues/3036 for more context.

**Comment by apmckinlay** [comment] 2020-03-05 19:59
Would it make sense to ignore files and folders starting with '.' e.g. .git, .vscode, .history

Another possibility would be to respect .gitignore

**Comment by jniedrauer** [comment] 2020-03-06 23:38
This is a problem for more than just gopls. x/mod has a hardcoded module size limit, and there is no way to ignore files or directories at the same level as the go.mod file. Either .gitignore should be respected or go.mod needs an exclusion section.

**Comment by stamblerre** [comment] 2020-03-09 20:18
I know that https://github.com/golang/go/issues/37724 is tracking discussion of how files should be ignored by the `go` command, but we will definitely need a temporary work-around for `gopls`, since it will be a while before anything lands in the `go` command.

@heschik: Do you think that we can ignore files starting with `.` for type-checking/diagnostics as a work-around like @apmckinlay suggested?

**Comment by AndreasBackx** [comment] 2020-05-24 16:08
What about generated files? I am ignoring `.gql.go` files as that's the suffix I am using for files generated by [gqlgen](https://github.com/99designs/gqlgen) that I do not want to check in. I think some behaviour changed as VS Code with gopls seems to not use these files giving errors in these modules.

**Comment by heschik** [comment] 2020-05-26 18:31
@AndreasBackx I don't understand what that has to do with gopls. You may want to file a new issue, or at least explain exactly what you're looking for here.

**Comment by AndreasBackx** [comment] 2020-05-26 19:10
@heschik my apologies, I was trying to mention that there still is a use case for excluded files that gopls will most likely need to still keep track of. When using generated files, they might be ignored/excluded, but are still essential for gopls to work as desired.

**Comment by heschik** [comment] 2020-05-26 19:16
I see. Whatever is done for this will need to be in sync with the go command's behavior, so I don't think we'd be able to ignore individual files anyway. The vscode issue was for ignoring directories, which should be much more clear and not have the problems you're worried about.

**Comment by OneOfOne** [comment] 2020-08-06 01:13
I just got bit by this, one of my ignored folders have about 2 million auto generated files (not go files), but for some reason that pretty much kills gopls.

**Comment by ermik** [comment] 2020-08-28 15:27
Not all workspace folders can be assumed to be valid go module roots; I don't know if this is tracked in multi-module workspace issues but I just wanted to highlight it as explicit ignore setting for workspace folders is needed.

I noted how well `jest.disabledWorkspaceFolders` does it.

**Comment by stamblerre** [comment] 2020-09-09 02:57
I believe that some part of this may be handled by the multi-module workspace proposal, which will not search for modules in any folder that the `go` command would ignore. Also, we will allow users to specify their own workspace module through a `gopls.mod` file, so that might be one way of managing ignored folders.

I do like the idea of a "disableWorkspaceFolders" configuration, thanks for bring it up @ermik. Some users may just want a simple way of ignoring a single folder.

**Comment by heschik** [comment] 2020-09-09 19:36
It seems to me that the original problems reported on this issue are related to hidden directories, and I believe that was fixed as of https://golang.org/cl/239288. I'm going to close this issue. If you still have a problem, please open a new issue as usual and we'll take a look.

**Closed by heschik** 2020-09-09 19:36 UTC
Labels: NeedsInvestigation, Tools, gopls

**Comment by gonzojive** [comment] 2021-03-26 20:55
gopls is offering "import" autocomplete options for a bazel directory within my workspace (and go.mod directory) that's in my "files.exclude" list.

I'm experiencing https://github.com/microsoft/vscode-go/issues/3179 and guessing inclusion of bazel directories is causing gopls to slow down, but I haven't really diagnosed yet.

In any case, I can open a new bug for this as suggested above. The issue is identical, though, so please confirm a new issue is in order.

**Comment by stamblerre** [comment] 2021-03-29 18:51
In general, `gopls` doesn't really support Bazel well (https://github.com/golang/tools/blob/master/gopls/README.md#supported-go-versions-and-build-systems), so it's expected that you'd have see some odd behaviors. Folks are working on https://github.com/bazelbuild/rules_go/issues/512, which will enable us to improve support for Bazel in `gopls`.

**Comment by adam-azarchs** [comment] 2021-08-12 19:10
> Whatever is done for this will need to be in sync with the go command's behavior

The `go` command ignores symlinks (for a particularly pertinent example, `bazel-out`), but `gopls` does not.

**Comment by TobiaszCudnik** [comment] 2021-09-26 16:12
I can still see references to files under hidden dirs in the server log, eg
```
[Info  - 6:05:34 PM] 2021/09/26 18:05:34 reloadOrphanedFiles reloading
```
Lists all files from `.history`.

**Comment by gonzojive** [comment] 2021-10-03 17:51
It seems the proposal to add an ignore section to go.mod was rejected (chttps://github.com/golang/go/issues/37724), so perhaps a different mechanism is needed for go tools to ignore directories that exist during development but not release.

I'll file a bug for my specific issue.
