### ISSUE TITLE
x/tools/gopls: Error loading workspace: You are outside of a module and outside of $GOPATH/src

### ISSUE THREAD

**Issue by granzginz** [golang/go#45225] opened 2021-03-25 00:46 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

No

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Anjar\AppData\Local\go-build
set GOENV=C:\Users\Anjar\AppData\Roaming\go\env  
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Anjar\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Anjar\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.2
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Camp Latihan Pemrograman\Heroku\go-getting-started\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Anjar\AppData\Local\Temp\go-build3937432002=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you expect to see?

No error and import file using go get *depedency* found folder to $goroot or $gopath 

### What did you see instead?

Error on importing file

**Comment by stamblerre** [comment] 2021-03-30 17:58
Can you please share your `gopls` logs? Information on how to capture them can be found [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).

**Comment by granzginz** [comment] 2021-03-31 03:45
golang.org/x/tools/gopls v0.6.9
    golang.org/x/tools/gopls@v0.6.9 h1:LBBcE2y3Tb4bp79JVLWCQBbvYCFEs5ADGWsQDoSLk1Q=  
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.4 h1:L8R9j+yAqZuZjsqh/z+F1NCffTKKLShY6zXTItVIZ8M=  
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=  
    golang.org/x/mod@v0.4.1 h1:Kvvh58BN8Y9/lBi7hTekvtMpm07eUZ0ck5pRHpsMWrY=
    golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9 h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=
    golang.org/x/sys@v0.0.0-20210124154548-22da62e12c0c h1:VwygUrnw9jn88c4u8GD3rZQbqrP/tgas88tPUbBxQrk=
    golang.org/x/tools@v0.1.1-0.20210319172145-bda8f5cee399 h1:O5bm8buX/OaamnfcBrkjn0SPUIU30jFmaS8lP+ikkxs=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.1.1 h1:EVDuO03OCZwpV2t/tLLxPmPiomagMoBOgfPt0FM+4IY=
    mvdan.cc/gofumpt@v0.1.0 h1:hsVv+Y9UsZ/mFZTxJZuHVI6shSQCtzZ11h1JEFPAZLw=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

**Comment by stamblerre** [comment] 2021-03-31 04:33
Thanks for sharing that, but that's your `gopls version` output. I'm looking for the logs produced by `gopls` as it runs--https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information describes how to gather these logs. Thanks!

**Comment by Bittu0184** [comment] 2021-04-14 06:27
I am facing the same issue. Did you find the cause and solution?

**Comment by granzginz** [comment] 2021-04-14 07:25
I try to select a workplace and type code. on current folder.

**Comment by stamblerre** [comment] 2021-04-20 15:43
@granzginz, @Bittu0184: Please provide your `gopls` logs so that we can help investigate the issue. Information on how to capture them can be found [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).

**Comment by stamblerre** [comment] 2021-05-14 19:23
Closing, as there hasn't been any activity on this issue for a few weeks.

**Closed by stamblerre** 2021-05-14 19:23 UTC
Labels: Tools, WaitingForInfo, gopls
