### ISSUE TITLE
two-dimensional slice

### ISSUE THREAD

**Issue by 727023460** [golang/go#24619] opened 2018-03-31 08:40 UTC
my data of lenth is variable
how to insert data in  two-dimensional slice
I can't use append

**Comment by ALTree** [comment] 2018-03-31 08:54
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2018-03-31 08:54 UTC
