### ISSUE TITLE
 xml.Marshal Changed  string "\f/" to "�/"

### ISSUE THREAD

**Issue by yangzong18** [golang/go#55869] opened 2022-09-26 02:07 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by mengzhuo** [comment] 2022-09-26 06:15
Could you submit an example in https://go.dev/play?

**Comment by ZekeLu** [comment] 2022-09-26 06:32
Duplicate of #46048

**Closed** 2022-09-26 06:57 UTC
