### ISSUE TITLE
"golang.org/x/net/internal/iana" //use of internal package not allowed

### ISSUE THREAD

**Issue by godla** [golang/go#24061] opened 2018-02-23 09:59 UTC
Please answer these questions before submitting your issue. Thanks!

how to import "golang.org/x/net/internal/iana"
"golang.org/x/net/internal/iana" //use of internal package not allowed

### What version of Go are you using (`go version`)?
go1.9

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/mnt/hgfs/share/www/go"
GOTOOLDIR="/mnt/hgfs/share/www/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build545988488=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### What did you do?

how to import "golang.org/x/net/internal/iana"
"golang.org/x/net/internal/iana" //use of internal package not allowed

### What did you expect to see?
i need import "golang.org/x/net/internal/iana"

**Comment by ALTree** [comment] 2018-02-23 10:07
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2018-02-23 10:07 UTC
