### ISSUE TITLE
text/template: 'Break' on rande

### ISSUE THREAD

**Issue by igramnet** [golang/go#20523] opened 2017-05-29 07:01 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
0.21

### What operating system and processor architecture are you using (`go env`)?
Windows + Ubuntu

### What did you do?

Good afternoon. PHP has a loop
`If {$ i> 2} break;`
How to do this in hugo?

**Comment by ALTree** [comment] 2017-05-29 11:34
Hi,

the Go project does not use its bug tracker for general discussion or asking questions. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2017-05-29 11:34 UTC

**Comment by bep** [comment] 2017-05-29 20:55
This is a valid issue, however not perfectly formulated. 

I will try to rephrase:

This is currently not possible with the Go text templates:

```
{{ range $i, $e := .SomeSlice }}
{{ if gt $i 2 }}
{{ continue }}
{{ end }}
{{ end }}
```

The above example is fictional, of course, since the `continue` keyword does not exist in the Go template syntax, but it is common enough that people, well, just expect that it exists. 

So, this is a valid issue. Maybe not a bug, but it borders one. So, @ALTree you can reopen this or I will create a new one with a better description?

**Comment by ALTree** [comment] 2017-05-29 22:27
@bep it's a feature request then? It didn't look like one.

I'm not a `text/template` expert but if you think it's a reasonable request then sure. We could re-open this and edit the description but at this point it'll be cleaner to just open a new issue. Feel free. Thanks!
