### ISSUE TITLE
cmd/compile: inline multiplication corrupts an argument on arm

### ISSUE THREAD

**Issue by derfbn** [golang/go#28688] opened 2018-11-09 10:02 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.11.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fred/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/fred/workspace/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build795351668=/tmp/go-build -gno-record-gcc-switches"
</pre></details>
### What did you do?
<pre>
package main

import (
	"fmt"
)

func main() {
	id := 1
	a := float32(2.0)
	b := float32(5.0)
	testOut(id, a*b)
}

func testOut(id int, a float32) {
	fmt.Println(id, a)
}

$ env GOOS=linux GOARCH=arm go build -o test.arm7 main.go

running on raspberry pi 3 Model:B V:2 
Linux PiOne 4.14.79-1-ARCH #1 SMP Tue Nov 6 03:01:46 UTC 2018 armv7l GNU/Linux

$ ./test.arm7

</pre>

### What did you expect to see?
1 10

### What did you see instead?
1073741824 10

When I do the multiplication outside the function call testOut() I get output (1 10).
Only happens when I do cross compilation. 

When I cross compile and set GOARM=7, it works just fine.
env GOOS=linux GOARCH=arm GOARM=7 go build -o test.arm7 main.go

**Comment by mvdan** [comment] 2018-11-09 11:08
@derfbn does this occur with Go 1.10 or previous Go versions?

**Comment by mvdan** [comment] 2018-11-09 11:13
Tentatively marking as a release blocker for 1.12, until we're sure that this isn't important enough.

**Comment by derfbn** [comment] 2018-11-09 11:31
go version go1.10.5 linux/amd64
<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fred/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/fred/workspace/go"
GORACE=""
GOROOT="/home/fred/trash/gotest/go1.10.5/go"
GOTMPDIR=""
GOTOOLDIR="/home/fred/trash/gotest/go1.10.5/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build790837178=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

@mvdan does not occur on [Go 1.10.5](https://dl.google.com/go/go1.10.5.linux-amd64.tar.gz)

**Comment by ianlancetaylor** [comment] 2018-11-09 14:56
CC @randall77

**Comment by josharian** [comment] 2018-11-09 16:13
Seems like a backport candidate. Let's wait to see what the diagnosis is.

**Comment by milanknezevic** [comment] 2018-11-09 17:43
The issue can be reproduced on mips too.

**Comment by josharian** [comment] 2018-11-09 17:49
@gopherbot please open a backport tracking issue for 1.11. This is a compiler correctness bug.

**Comment by milanknezevic** [comment] 2018-11-13 15:45
Could this also be backported to 1.10 because it affects mips softfloat support which is added in 1.10.

**Comment by josharian** [comment] 2018-11-13 16:15
Sure. FYI, anyone can open a backport request.

@gopherbot please also open a backport tracking issue for 1.10. This is a compiler correctness bug.

**Comment by josharian** [comment] 2018-11-13 16:20
Hmm, gopherbot doesn't seem to be as speedy as I would expect. I wonder whether incrementally adding backport releases isn't well supported right now. @dmitshur?

**Comment by dmitshur** [comment] 2018-11-13 19:19
@josharian You're hitting the known issue #25574. Gopherbot already responded to a backport command earlier in this issue, so until #25574 is resolved, it never listens to follow up backport requests.

**Closed** 2018-11-14 18:53 UTC
Labels: NeedsInvestigation, release-blocker
