### ISSUE TITLE
about log.Errorf Printing pointer slice

### ISSUE THREAD

**Issue by imilli** [golang/go#48091] opened 2021-08-31 12:08 UTC
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.16.2 linux/amd64
</pre>

### What did you expect to see?

Can log.Errorf provide parameters like %*V, Convert pointer to value automatically when printing slice content if contains pointer , instead of traversing the slices to print by ourself.

**Comment by seankhliao** [comment] 2021-08-31 12:15
Duplicate of #28141

**Closed by seankhliao** 2021-08-31 12:15 UTC
