### ISSUE TITLE
Potential goroutine starvation

### ISSUE THREAD

**Issue by suoigwg** [golang/go#27512] opened 2018-09-05 14:22 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.11 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/Users/username/Library/Caches/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="darwin"
> GOOS="darwin"
> GOPATH="/Users/username//go"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
> GCCGO="gccgo"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vh/6m51srdn3ps28tc64qy1343h0000gp/T/go-build648130556=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you do?
// URLs provide a [uniform way to locate resources](https://adam.herokuapp.com/past/2010/3/30/urls_are_the_uniform_way_to_locate_resources/).
// Here's how to parse URLs in Go.
```

package main

import (
	"fmt"
	"log"
	"time"
)

var p  = fmt.Print

func printHi()  {
	for{
		log.Println("hi")
		time.Sleep(10*time.Second)
	}
}
func main() {
	go printHi()
	for{
		log.Println("hello")
	}
}

```

### What did you expect to see?
"Hi" got printed every few seconds. Seems printHi() never got a chance to run. Is this kind of a starvation? What should I do if I want printhi() to run every ten seconds or so?

### What did you see instead?
Only "hello" got printed

**Comment by suoigwg** [comment] 2018-09-05 14:39
tried
runtime.Gosched()
in main
Seems no luck

**Comment by bradfitz** [comment] 2018-09-05 14:50
Duplicate of #24543.

**Closed by bradfitz** 2018-09-05 14:50 UTC
