### ISSUE TITLE
go1.20: no docs for golang.org/x/crypto/x509roots/fallback

### ISSUE THREAD

**Issue by andig** [golang/go#58241] opened 2023-02-02 12:32 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/andig/Library/Caches/go-build"
GOENV="/Users/andig/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/andig/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/andig/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/andig/htdocs/evcc/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sv/rs_453y57xj86xsbz3kw1mbc0000gn/T/go-build1228287512=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.20 darwin/arm64
GOROOT/bin/go tool compile -V: compile version go1.20
uname -v: Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103
ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C65
lldb --version: lldb-1400.0.38.17
Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
</pre></details>

### What did you do?

https://go.dev/doc/go1.20 mentions https://pkg.go.dev/crypto/x509#SetFallbackRoots and links https://go.dev/pkg/golang.org/x/crypto/x509roots/fallback. The link is dead afaikt and looking at https://pkg.go.dev/crypto I cannot find any reference to `x509roots`.

### What did you expect to see?

Documentation for the https://go.dev/pkg/golang.org/x/crypto/x509roots/fallback package

### What did you see instead?

No docs.

**Comment by seankhliao** [comment] 2023-02-02 12:46
Duplicate of #57792

**Closed by seankhliao** 2023-02-02 12:46 UTC
Labels: Documentation

**Comment by andig** [comment] 2023-02-02 12:50
The duplicate is a proposal. This issue is referring to the current release notes. Seems these need be corrected if the new package is still in proposal phase?
