### ISSUE TITLE
net: AAAA DNS queries are made despite ip4 on LookupIP

### ISSUE THREAD

**Issue by melardev** [golang/go#44809] opened 2021-03-05 13:05 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.8 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/laro/.cache/go-build"
GOENV="/home/laro/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/laro/Desktop/SSDStorage/workspace/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/laro/Desktop/SSDStorage/workspace/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build927622048=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
**The following snippets may not run on golang playground, maybe they restrict network connections?**

I prepared the following snippet(https://play.golang.org/p/CTmnriuHXcU), run it with a network sniffer turned on, I used Wireshark with the filter "udp port 53" so I only capture DNS traffic.
There are two DNS queries being made, A, and AAA, this should not happen. I thought this may be reproducible on the default resolver too, so I prepared this other snipped(https://play.golang.org/p/6wIdTxjI4dd), it does not make the AAA DNS query, this shows it is a bug, because if it was by design then I would have expected both snippets to behave the same.

### What did you expect to see?
If I ask for an A DNS record, why am I making a query for AAA (ip6)?

### What did you see instead?
Two DNS queries, one for IP4(A) and other for IP6 (AAA).

**Comment by melardev** [comment] 2021-03-05 13:24
Maybe it would help you track this down, this is only reproducible if PreferGo is set to true, I don't see why this flag should determine what DNS requests should be sent. So the issue must be on cgLookupIp I guess?

**Comment by dmitshur** [comment] 2021-03-06 00:07
CC @bradfitz, @ianlancetaylor via [owners](https://dev.golang.org/owners).

**Comment by antong** [comment] 2021-08-25 05:46
I believe this is the same as #45024 (filed some days later), so fixed in Go 1.17.

**Comment by seankhliao** [comment] 2021-08-25 09:03
Duplicate of #45024

**Closed by seankhliao** 2021-08-25 09:03 UTC
Labels: NeedsInvestigation
