### ISSUE TITLE
sync/atomic: sequence of execution

### ISSUE THREAD

**Issue by Zh1Cheung** [golang/go#42917] opened 2020-12-01 01:40 UTC
For the official implementation of Go 1.15, the order between the variables of Load/Store using atomic can be guaranteed.

>Package atomic provides low-level atomic memory primitives useful for implementing synchronization algorithms.

>The load and store operations, implemented by the LoadT and StoreT functions, are the atomic equivalents of "return *addr" and "*addr = val".

```

func main() {
	var a, b int32 = 0, 0

	go func() {
		atomic.StoreInt32(&a, 1)
		atomic.StoreInt32(&b, 1)
	}()

	for atomic.LoadInt32(&b) == 0 {
		runtime.Gosched()
	}
	fmt.Println(atomic.LoadInt32(&a))

}

```
The printed result of a is always 1, but it is not reflected in the document.

**Comment by go101** [comment] 2020-12-01 13:59
see https://github.com/golang/go/issues/5045

**Comment by ianlancetaylor** [comment] 2020-12-02 16:18
Closing this issue as a duplicate of #5045.

**Closed by ianlancetaylor** 2020-12-02 16:18 UTC
