### ISSUE TITLE
x/playground: Signal 11 from untrusted code

### ISSUE THREAD

**Issue by bendory** [golang/go#24312] opened 2018-03-08 15:46 UTC
https://play.golang.org/p/K4d5dZA58K1 <-- Has a `** Signal 11 from untrusted code: pc=465c000898c0` provoked by line 24.

I initially thought it was the assignment to nil, but line 20 does the same and that line is fine.

### What version of Go are you using (`go version`)?
go1.10 (in the Go playground)

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
Go playground

### What did you do?
https://play.golang.org/p/K4d5dZA58K1 

### What did you expect to see?
I expected the program to print:

```
go1.10
returned that
```

### What did you see instead?

```
go1.10

** Signal 11 from untrusted code: pc=4f2f000898c0
```

**Comment by bcmills** [comment] 2018-03-08 18:09
The error message is definitely wrong, but you don't need all that machinery to reproduce it. Just calling a method on a nil interface will do:
https://play.golang.org/p/J3RPBVxZ8bf

**Comment by urld** [comment] 2018-03-08 18:17
Correct error message on linux:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4832af]

goroutine 1 [running]:
main.main()
	/home/david/go_ws/src/github.com/urld/foo/main.go:31 +0x2f
exit status 2
```

This is behaviour is caused by what defer does to named result parameters:

>  For instance, if the deferred function is a function literal and the surrounding function has named result parameters that are in scope within the literal, the deferred function may access and modify the result parameters before they are returned.
(https://golang.org/ref/spec#Defer_statements)

**Comment by andybons** [comment] 2018-03-08 18:22
Duplicate of #23836

**Closed** 2018-03-08 18:22 UTC
Labels: NeedsInvestigation
