### ISSUE TITLE
x/pkgsite: request for documentation for non-std modules responds with an error

### ISSUE THREAD

**Issue by bhcleek** [golang/go#51368] opened 2022-02-25 23:50 UTC
### What is the URL of the page with the issue?
Any module that does not have a dot in its name and is not part of the standard library.

### What is your user agent?

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
```

### What did you do?

1. Run a local pkgsite instance to serve documentation for a module that is only available internally and which does not have a `.` in its name.
2. Request the godoc for module's packages.

### What did you expect to see?

The godoc for the page.

### What did you see instead?

An error page.

The issue is caused by [`"github.com/golang/pkgsite/internal/frontend".serveDetails`](https://github.com/golang/pkgsite/blob/master/internal/frontend/details.go#L51-L73]), which calls [`"github.com/golang/pkgsite/internal/frontend".extractURLPathInfo`](https://github.com/golang/pkgsite/blob/master/internal/frontend/urlinfo.go#L55-L57) which in turn relies on [`"github.com/golang/pkgsite/internal/stdlib".Contains`](https://github.com/golang/pkgsite/blob/master/internal/stdlib/stdlib.go#L547-L554).

While I can understand the standard library taking precedence, it would be nice if `serveDetails` would fallback to checking the other modules so that modules which are internal to a company and not expected to be available publicly could have documentation served by pkgsite as well.

Unfortunately, updating the module name is a disruption that is not yet worth the trouble.

**Comment by jamalc** [comment] 2022-03-14 17:18
I understand the use case but I'm not sure this is something we would move forward with. Package names should always be globally unique and this namespace is reserved for the stdlib. Others might disagree. /cc @jba @julieqiu 

Would the replace directive be useful here in avoiding major disruption from a module name change?

**Comment by jba** [comment] 2022-03-14 17:29
I agree with Jamal.
If you don't want to change your package names, I'd suggest patching our code for your local deployment.

**Comment by seankhliao** [comment] 2022-08-26 14:43
> is this documented some place

That would be #32819

Closing as this isn't going to be supported

**Closed by seankhliao** 2022-08-26 14:43 UTC
Labels: NeedsInvestigation, pkgsite, pkgsite/cmd

**Comment by Sunshine40** [comment] 2022-12-11 18:44
@seankhliao The reasons for not lifting the ristrictions here is fair enough, but the error message returned should be revised.

The HTTP 424 _Failed Dependency_ along with the message "This page is not supported by this datasource." is exceptionally vague to use as a search engine keyword, and is actually misleading in this case.

As @julieqiu mentioned in #40371, pkgsite (run locally as a light-weight go doc visualizer for private repositories) can be used as an alternative to the godoc cmd which also serves http requests, so running into this problem isn't that rare.

After hours of digging into the source code of pkgsite, I was finally confirmed that the error page has nothing to do with the datasource choice (of not using postgresql). The error handling logic redirect every 404 _not found_ to this 424 _failed dependency_ if the datasource is not postgresql, which is actually counterintuitive as 404s are most certainly 404s.

To better explain: error handler tried to tell user that a 404 not found is due to local filesystem as datasource, mistaking the fact for the actual cause when 404 occured. This logic is flawed for queries that normally return 404s from a postgresql backed instance of pkgsite.

If someone made his first attempt to run pkgsite locally with a single-word named module, and ends up with the program producing "not supported by datasource" page for every url he could come up with, while developer mentioned only

> Search and other tabs on the package page are not supported in direct proxy mode.

he would expect the problem to be improper deployment, and head to the wrong direction. (I wasted hours ruling out the possibilities of "needing a postgresql server to fix", "undocumented dependency on linux environment while I run windows", "unknown problem connecting to database", "go for windows not recognizing user-scoped environment variables", definitely don't want to be repeated)

Limiting the "not supported by datasource" error page to search queries should help. And it would be nice to have a link guiding newcomers to the documentation about #32819
