### ISSUE TITLE
Proposal: Deadlock detection mode for the runtime

### ISSUE THREAD

**Issue by DemiMarie** [golang/go#18835] opened 2017-01-29 00:05 UTC
This is a proposal for a deadlock detection mode for the runtime.  In this mode, when the runtime detects that a goroutine is unreachable, it prints the goroutine's stack trace to stderr and then panics the goroutine.  If the panic is uncaught, the runtime will log the stack trace to stderr, but not kill the program (this is different from the normal case).

**Comment by minux** [comment] 2017-01-29 00:32
Possibly dup of #13759?

**Comment by rsc** [comment] 2017-01-30 20:50
Duplicate of #13759 (idea accepted but no clear implementation approach).

**Closed by rsc** 2017-01-30 20:50 UTC
