### ISSUE TITLE
bufio: Reading from stdin breaks arrow keys

### ISSUE THREAD

**Issue by mybearworld** [golang/go#70071] opened 2024-10-27 21:41 UTC
### Go version

go version go1.23.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/mybearworld/.cache/go-build'
GOENV='/home/mybearworld/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/mybearworld/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/mybearworld/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/mybearworld/.go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/mybearworld/.go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.0'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/mybearworld/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/mybearworld/playground/stdinbufio/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3760656799=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

main.go:
```go
package main

import (
        "bufio"
        "fmt"
        "os"
)

func main() {
        reader := bufio.NewReader(os.Stdin)
        s, err := reader.ReadString('\n')
        fmt.Println(s, err)
}
```

Keystrokes: Hello, world!<kbd>←</kbd> and mars

### What did you see happen?

```
Hello, world!^[[D and mars
Hello, world and mars
 <nil>
```

The arrow key is displayed as its code (^[[D) and deletes a character.

### What did you expect to see?

```
Hello, world and mars!
Hello, world and mars!
 <nil>
```

The arrow key acts as it normally does (moving a character back and displaying it as such).

**Comment by seankhliao** [comment] 2024-10-27 23:20
stdin is a raw input stream, the implementation of line editing through arrow keys or other control characters is left to applications/libraries.

Closing as working as intended.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Closed by seankhliao** 2024-10-27 23:20 UTC
