### ISSUE TITLE
x/crypto/ssh: stuck in Wait on more than one command

### ISSUE THREAD

**Issue by Dhvani248** [golang/go#44060] opened 2021-02-02 06:48 UTC
### What version of Go are you using (`go version`)?
<pre>
$ go version
go version go1.15.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dhvani/motadata_8/PluginEngineGolang/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dhvani/motadata_8/PluginEngineGolang"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/root/sdk/go1.15.5"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/root/sdk/go1.15.5/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build614479280=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
```go
package main

import (
	"bytes"
	"fmt"
	"github.com/ScriptRock/crypto/ssh"
	"time"
	"log"
)

func main() {

	credential := map[string]interface{}{
		"username": "xyz",
		"password": "xyz",
		"hostname": "xyz",
		"port": "22",
	}

	config := &ssh.ClientConfig{
		User: credential["username"].(string),
		Auth: []ssh.AuthMethod{
			ssh.Password(credential["password"].(string)),
		},
		HostKeyCallback: ssh.InsecureIgnoreHostKey(),
		Config: ssh.Config{
			Ciphers: ssh.AllSupportedCiphers(),
		},
	}

	client, err := ssh.Dial("tcp", credential["hostname"].(string)+":"+credential["port"].(string), config)
	if err != nil {
		log.Fatal(err)
	}
	defer client.Close()

	sess, err := client.NewSession()
	if err != nil {
		log.Fatal("Failed to create session: ", err)
	}
	defer sess.Close()

	stdin, err := sess.StdinPipe()
	if err != nil {
		log.Fatal(err)
	}

	var b bytes.Buffer
	sess.Stdout = &b
	sess.Stderr = &b

	err = sess.Shell()
	if err != nil {
		log.Fatal(err)
	}

	commands := []string{
		"cli",
		"show cli",
		"exit",
		"exit",
	}

	d := time.Now()

	for _, cmd := range commands {

		_, err = fmt.Fprintf(stdin, "%s\n", cmd)

		if err != nil {
			log.Fatal(err)
		}
	}

	err = sess.Wait()

	d = time.Now()

	fmt.Println(d)

	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(b.String())

}
```

### What did you expect to see?
I am trying to connect to juniper device and need to enter into cli mode so It should return output of following commands.

### What did you see instead?
This program get stucked while executing.

**Comment by davecheney** [comment] 2021-02-02 06:51
Please send SIGQUIT to your program and paste the entire output.  Thank you.

**Comment by seankhliao** [comment] 2021-02-02 07:14
have you tried looking at the output? eg. `sess.Stdout = os.Stdout` and `sess.Stderr = os.Stderr`

**Comment by Dhvani248** [comment] 2021-02-02 09:18
@seankhliao Thanks for your quick response. And yes i have tried this one.There is one solution which is putting sleep between execution of two different commands but i guess that is not good for the performance. I am attaching relative code for your reference.Please let me know if there is any other solution.

`package main

import (
	"bytes"
	"fmt"
	"github.com/ScriptRock/crypto/ssh"
	"time"
	"log"
)

func main() {

	credential := map[string]interface{}{
		"username": "xyz",
		"password": "xyz",
		"hostname": "xyz",
		"port": "22",
	}

	config := &ssh.ClientConfig{
		User: credential["username"].(string),
		Auth: []ssh.AuthMethod{
			ssh.Password(credential["password"].(string)),
		},
		HostKeyCallback: ssh.InsecureIgnoreHostKey(),
		Config: ssh.Config{
			Ciphers: ssh.AllSupportedCiphers(),
		},
	}

	client, err := ssh.Dial("tcp", credential["hostname"].(string)+":"+credential["port"].(string), config)
	if err != nil {
		log.Fatal(err)
	}
	defer client.Close()

	sess, err := client.NewSession()
	if err != nil {
		log.Fatal("Failed to create session: ", err)
	}
	defer sess.Close()

	stdin, err := sess.StdinPipe()
	if err != nil {
		log.Fatal(err)
	}

	var b bytes.Buffer
	sess.Stdout = &b
	sess.Stderr = &b

	err = sess.Shell()
	if err != nil {
		log.Fatal(err)
	}

	commands := []string{
		"cli",
		"show cli",
		"exit",
		"exit",
	}

	d := time.Now()

	for _, cmd := range commands {

		_, err = fmt.Fprintf(stdin, "%s\n", cmd)

		time.Sleep(10000000000)

		if err != nil {
			log.Fatal(err)
		}
	}

	err = sess.Wait()

	d = time.Now()

	fmt.Println(d)

	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(b.String())

}`

**Comment by seankhliao** [comment] 2021-02-02 09:31
so you just need to wait for the previous command to complete before sending more stuff to stdin (since the previous command may choose to read stdin)

closing as it's not a bug in `x/crypto/ssh`

**Closed by seankhliao** 2021-02-02 09:31 UTC
Labels: WaitingForInfo
