### ISSUE TITLE
When https://golang.org/pkg/plugin package supports windows and what is the alternative solution in windows now 

### ISSUE THREAD

**Issue by Durgababu** [golang/go#39373] opened 2020-06-03 07:30 UTC
### What version of Go are you using (`go version`)?

go 1.14.2

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

Windows 10
64-bit

### What did you expect to see?

When https://golang.org/pkg/plugin package supports windows and what is the alternative solution in windows now

**Comment by Durgababu** [comment] 2020-06-03 07:33
Hi 
I want to do some plug-gable framework around windows devices using golang code. For linux i heard that https://golang.org/pkg/plugin/ is option for it. What could be solution for windows developers. What exactey i need is i want to call some run time functions like we use c++ dll.

**Comment by davecheney** [comment] 2020-06-03 07:38
Thank you for raising this issue. Unlike many projects on GitHub, the Go project does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs and tracking proposals going through the Proposal Process.

Please see https://golang.org/wiki/Questions for good places to ask questions.

Duplicate of #19282

**Closed by davecheney** 2020-06-03 07:38 UTC
