### ISSUE TITLE
fmt.XprintY functions may leak the memory of variables

### ISSUE THREAD

**Issue by EddieIvan01** [golang/go#34721] opened 2019-10-06 15:19 UTC
### What version of Go are you using (`go version`)?

both Windows and Linux

<pre>
$ go version

go version go1.12.5 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\GoWorkplace\
set GOPROXY=https://goproxy.cn
set GORACE=
set GOROOT=E:\Golang
set GOTMPDIR=
set GOTOOLDIR=E:\Golang\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\

</pre></details>

### What did you do?

try to run following code (https://play.golang.org/p/tesupy4D1lu):

```go
package main

import (
    "bytes"
    "fmt"
    "io"
    "text/template"
)

type SecWriter struct {
    w io.Writer
}

var count = 0

func (s *SecWriter) Write(p []byte) (n int, err error) {
    fmt.Println(string(p), len(p), cap(p))
    count++

    // here
    tmp := fmt.Sprintf("info{%dSSSSSSSSSSSSSSSSSSSSSSSSSSS}", count)
    if tmp == ""{}

    s.w.Write(p[:64])
    return 64, nil
}

func index() {
    exp := "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA{{1}}"

    b := &bytes.Buffer{}
    s := &SecWriter{
        w: b,
    }


    t := template.Must(template.New("index").Parse(exp))
    t.Execute(s, nil)

    fmt.Println("buf: ", b.String())
}

func main() {
    index()
}
```

### What did you see instead?

the output:

```
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 64 64
1 1 128
buf:  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1nfo{1SSSSSSSSSSSSSSSSSSSSSSSSSSS}AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

the `SecWriter.Write` will be invoked twice, the `p []byte` are `"A"*64` and `{{1}}`

the local variable printed by fmt.Sprintf in the first invoke is leaked to the `p []byte`'s memory in the next invoke. And if I change fmt.Sprint instead of fmt.Printf to print into stdout, the variable will **also leaked**.

if I dont use fmt.XprintY, the leaking is not going to happen. like this:

```go
// here
tmp := "info{SSSSSSSSSSSSSSSSSSSSSSSSSSS}"
if tmp == "" {}
```

I think maybe it's related to how `fmt.printer.buf` is handled

**Comment by randall77** [comment] 2019-10-06 15:34
This line is incorrect:

>     s.w.Write(p[:64])

You're unconditionally slicing to length 64, even if the length of `p` was shorter. That lets you read data beyond the length of `p`, which isn't what you want (an `io.Writer` should only read between `0` and `len`, not between `len` and `cap`).

You'd want to do something more like:

```
	if len(p) > 64 {
		p = p[:64]
	}
	s.w.Write(p)
	return len(p), nil
```

We could restrict the capacity of the slice passed to `Write`, which would make your code panic instead of printing the wrong thing. But that's not common practice.

Closing as not a bug.

**Closed by randall77** 2019-10-06 15:34 UTC
