### ISSUE TITLE
gollvm: /usr/bin/ld.gold: error: linker does not include stack split support, on Aarch64

### ISSUE THREAD

**Issue by advancedwebdeveloper** [golang/go#45139] opened 2021-03-20 05:57 UTC
I was trying to compile https://github.com/containernetworking/plugins

> ~/plugins/plugins/meta/bandwidth$ go build -i -v -x
> WORK=/tmp/go-build4255351538
> go build: -i flag is deprecated
> mkdir -p $WORK/b001/
> cat >$WORK/b001/importcfg.link << 'EOF' # internal
> packagefile github.com/containernetworking/plugins/plugins/meta/bandwidth=/home/oceanfish81/.cache/go-build/fc/fc0a132c502f2e69d543cf2e4bddc433c674926e0bb4dcba2e7a0d8b1c91c5d8-d
> packagefile github.com/containernetworking/cni/pkg/skel=/home/oceanfish81/.cache/go-build/98/981934d80e051ef8ded36537ad8c11123b497a35717e04b7028fbf380a0e21cc-d
> packagefile github.com/containernetworking/cni/pkg/types=/home/oceanfish81/.cache/go-build/dd/dd68495fd39451463c3dcf3f1f8230fffef8f5038c85dde776209bc4ef9f91bc-d
> packagefile github.com/containernetworking/cni/pkg/types/100=/home/oceanfish81/.cache/go-build/fe/fe0a79bdf94970bedab696eabf5a128cab74ec5b0f0efeb5341e1848bc6ace16-d
> packagefile github.com/containernetworking/cni/pkg/version=/home/oceanfish81/.cache/go-build/2d/2ddbfec341d50fb66eb0bf470480d1dc5b036a4ed70e717ad0a840703eb36d85-d
> packagefile github.com/containernetworking/plugins/pkg/ip=/home/oceanfish81/.cache/go-build/c8/c83fb5ac3e74102adde67820924dc7d7a0fc6d187ef3c71bf0e38ff85fbb9bdd-d
> packagefile github.com/containernetworking/plugins/pkg/ns=/home/oceanfish81/.cache/go-build/90/90595ab437960c47daa434ae051be4449adb6919e83aca9c403a044b8335354e-d
> packagefile github.com/containernetworking/plugins/pkg/utils=/home/oceanfish81/.cache/go-build/2c/2c69eaa10ccdbe8fd188aed08ef42d5a7b7a1d8d36a1f84351a0e4d2e774fa3d-d
> packagefile github.com/containernetworking/plugins/pkg/utils/buildversion=/home/oceanfish81/.cache/go-build/8c/8c8bc70c0357b51e1fa2f2d7b72063257d5ed9cc0050950bd708dbd1b367af78-d
> packagefile github.com/vishvananda/netlink=/home/oceanfish81/.cache/go-build/79/7951a5e3cb7f6d215ece803e9ea9182f068ffc4a4b0c388d7974047b05bcf748-d
> packagefile github.com/containernetworking/cni/pkg/utils=/home/oceanfish81/.cache/go-build/ca/ca554ba2c60d639f2690ff01cc5358b5610dd900055998bb6549c41986c6e716-d
> packagefile github.com/containernetworking/cni/pkg/types/040=/home/oceanfish81/.cache/go-build/c5/c589cfd8a78219b52d5b0753ce80ee34fabbbe95f74e2253da64837c3693e389-d
> packagefile github.com/containernetworking/cni/pkg/types/internal=/home/oceanfish81/.cache/go-build/be/be5dd9f3b5fb671e51099d183d2d6ec022acdac593c3efa8e07b0fd8fc2055af-d
> packagefile github.com/containernetworking/cni/pkg/types/create=/home/oceanfish81/.cache/go-build/82/82ec0be7bae1b1725740cd62385a77b353520d5c3755bab2c62ff56eeac5fcd1-d
> packagefile github.com/containernetworking/plugins/pkg/utils/hwaddr=/home/oceanfish81/.cache/go-build/c2/c2069894d927cffa463b97e945a2c541b4040784c5c153fef9aba67ee4550101-d
> packagefile github.com/containernetworking/plugins/pkg/utils/sysctl=/home/oceanfish81/.cache/go-build/8f/8fe003213f0e4ae228247dd05d81f175e433f4c2fe12a119eea95dbeb2a28e23-d
> packagefile github.com/coreos/go-iptables/iptables=/home/oceanfish81/.cache/go-build/bf/bf8eeabcf8c8bde898dda9e7d85a61d153c039a4869f0d095d38ec4488b8afc5-d
> packagefile github.com/safchain/ethtool=/home/oceanfish81/.cache/go-build/0e/0e02f094438f54564c38904cdcc97ec81edc207b88384ccdca3882ce39556576-d
> packagefile golang.org/x/sys/unix=/home/oceanfish81/.cache/go-build/d4/d4acf5de6c3e955bddd8698d162522bffd451ffb837743e8f1961dae37c273a7-d
> packagefile github.com/vishvananda/netlink/nl=/home/oceanfish81/.cache/go-build/84/84860975306ccd8d3ae8a896e29f0d3cb9eac4473473b5351f87ba1edd18233c-d
> packagefile github.com/vishvananda/netns=/home/oceanfish81/.cache/go-build/fc/fc99b9456e8cf46a2962c5af2cee8afc1104b1845f63662597c200d63db049ee-d
> packagefile github.com/containernetworking/cni/pkg/types/020=/home/oceanfish81/.cache/go-build/ad/ad88aceb443ceaf3ade8d2fef1f6a5cd34f553d94a532bf4b026c4e365864f67-d
> packagefile golang.org/x/sys/internal/unsafeheader=/home/oceanfish81/.cache/go-build/8e/8efd968146d5aaed51238af4d9cc4fda3756febeef75b87e91ed0a3a41398a8b-d
> EOF
> mkdir -p $WORK/b001/exe/
> cd .
> /home/oceanfish81/gollvm_dist/bin/llvm-goc -o $WORK/b001/exe/a.out "-Wl,-(" -Wl,--whole-archive /home/oceanfish81/.cache/go-build/fc/fc0a132c502f2e69d543cf2e4bddc433c674926e0bb4dcba2e7a0d8b1c91c5d8-d /home/oceanfish81/.cache/go-build/98/981934d80e051ef8ded36537ad8c11123b497a35717e04b7028fbf380a0e21cc-d /home/oceanfish81/.cache/go-build/dd/dd68495fd39451463c3dcf3f1f8230fffef8f5038c85dde776209bc4ef9f91bc-d /home/oceanfish81/.cache/go-build/fe/fe0a79bdf94970bedab696eabf5a128cab74ec5b0f0efeb5341e1848bc6ace16-d /home/oceanfish81/.cache/go-build/2d/2ddbfec341d50fb66eb0bf470480d1dc5b036a4ed70e717ad0a840703eb36d85-d /home/oceanfish81/.cache/go-build/c8/c83fb5ac3e74102adde67820924dc7d7a0fc6d187ef3c71bf0e38ff85fbb9bdd-d /home/oceanfish81/.cache/go-build/90/90595ab437960c47daa434ae051be4449adb6919e83aca9c403a044b8335354e-d /home/oceanfish81/.cache/go-build/2c/2c69eaa10ccdbe8fd188aed08ef42d5a7b7a1d8d36a1f84351a0e4d2e774fa3d-d /home/oceanfish81/.cache/go-build/8c/8c8bc70c0357b51e1fa2f2d7b72063257d5ed9cc0050950bd708dbd1b367af78-d /home/oceanfish81/.cache/go-build/79/7951a5e3cb7f6d215ece803e9ea9182f068ffc4a4b0c388d7974047b05bcf748-d /home/oceanfish81/.cache/go-build/ca/ca554ba2c60d639f2690ff01cc5358b5610dd900055998bb6549c41986c6e716-d /home/oceanfish81/.cache/go-build/c5/c589cfd8a78219b52d5b0753ce80ee34fabbbe95f74e2253da64837c3693e389-d /home/oceanfish81/.cache/go-build/be/be5dd9f3b5fb671e51099d183d2d6ec022acdac593c3efa8e07b0fd8fc2055af-d /home/oceanfish81/.cache/go-build/82/82ec0be7bae1b1725740cd62385a77b353520d5c3755bab2c62ff56eeac5fcd1-d /home/oceanfish81/.cache/go-build/c2/c2069894d927cffa463b97e945a2c541b4040784c5c153fef9aba67ee4550101-d /home/oceanfish81/.cache/go-build/8f/8fe003213f0e4ae228247dd05d81f175e433f4c2fe12a119eea95dbeb2a28e23-d /home/oceanfish81/.cache/go-build/bf/bf8eeabcf8c8bde898dda9e7d85a61d153c039a4869f0d095d38ec4488b8afc5-d /home/oceanfish81/.cache/go-build/0e/0e02f094438f54564c38904cdcc97ec81edc207b88384ccdca3882ce39556576-d /home/oceanfish81/.cache/go-build/d4/d4acf5de6c3e955bddd8698d162522bffd451ffb837743e8f1961dae37c273a7-d /home/oceanfish81/.cache/go-build/84/84860975306ccd8d3ae8a896e29f0d3cb9eac4473473b5351f87ba1edd18233c-d /home/oceanfish81/.cache/go-build/fc/fc99b9456e8cf46a2962c5af2cee8afc1104b1845f63662597c200d63db049ee-d /home/oceanfish81/.cache/go-build/ad/ad88aceb443ceaf3ade8d2fef1f6a5cd34f553d94a532bf4b026c4e365864f67-d /home/oceanfish81/.cache/go-build/8e/8efd968146d5aaed51238af4d9cc4fda3756febeef75b87e91ed0a3a41398a8b-d -Wl,--no-whole-archive "-Wl,-)" -Wl,--build-id=0x7a6f7177485375645277387863573054384b57422f514e666c6667443543354b772d49337644704c752f613843576a62634c42516d5a3476596e376f58512f7a6f7177485375645277387863573054384b5742
> # github.com/containernetworking/plugins/plugins/meta/bandwidth
> **/usr/bin/ld.gold: error: linker does not include stack split support** required by /home/oceanfish81/.cache/go-build/d4/d4acf5de6c3e955bddd8698d162522bffd451ffb837743e8f1961dae37c273a7-d(gccgo_c.o)
>

**Comment by erifan** [comment] 2021-03-22 02:18
I think this is an issue of ld.gold rather than a problem with gollvm.

**Comment by thanm** [comment] 2021-03-22 11:39
Yes, as @erifan points out, the problem is with ld.gold.  The arm64 version of gold does not have support fixing up split-stack sequences, so this error is expected.

**Comment by cagedmantis** [comment] 2021-03-22 19:16
I'm closing this issue. Please feel free to re-open the issue if you feel like it's been closed in error.

**Closed by cagedmantis** 2021-03-22 19:16 UTC
