### ISSUE TITLE
cvs.ReadAll etc requires (Unix)LF

### ISSUE THREAD

**Issue by jeffreyhawkins** [golang/go#21811] opened 2017-09-08 17:58 UTC
### What version of Go are you using (`go version`)?
go version go1.9 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?

```
file, err := os.Open(path)
	if err != nil {
		panic(err)
	}
	defer file.Close()
	var contacts []Contact
	r := csv.NewReader(bufio.NewReader(file))
	for {
		line, error := r.Read()
		if error == io.EOF {
			break
		} else if error != nil {
			panic(error)
		}

		contacts = append(contacts, Contact{
			First:   line[0],
			Last:    line[1],
			Address: line[2],
			City:    line[3],
			State:   line[4],
			Zip:     line[5],
		})
	}
```

// Sample data to play with... save with carriage returns and run the above code.
First,Last,Address,City,State,Zip
One,,1313 Mocking Bird Lane,Hollywood,CA,90210
Two,,1313 Mocking Bird Lane,Hollywood,CA,90210
Three,,1313 Mocking Bird Lane,Hollywood,CA,90210
Four,,1313 Mocking Bird Lane,Hollywood,CA,90210
Five,,1313 Mocking Bird Lane,Hollywood,CA,90210
Six,,1313 Mocking Bird Lane,Hollywood,CA,90210

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
Should have all the lines of the CSV converted to a Contact

### What did you see instead?
Only the last line. If I save the csv file with unix line feed's LF then it works properly. By default, Excel on OSX saves the csv with a carriage return CR

**Comment by nussjustin** [comment] 2017-09-08 18:18
The encoding/csv package supports reading CSV files with \r\n for line endings as per RFC 4180 and also \n without \r for compatibility with the many CSV files out there that don't contain \r. From what I understand you only have \r and not \n in your files. This is unsupported since it's rare and basically no widely used OS (that is supported by go) today uses just \r as newline character. In fact saving a CSV file in Excel (newest version) on my MBP2016 with the newest macOS I get \n as expected, since this is the standard delimiter under macOS.

So unless I misunderstood your problem, I would say this is not a bug.

**Comment by jeffreyhawkins** [comment] 2017-09-08 18:31
Thanks for the quick response and thanks for the details... I'll try to determine how the \r found its way into the csv.

Thanks again!

**Comment by ianlancetaylor** [comment] 2017-09-08 22:13
Closing.  Please comment if you think this should not be closed.

**Closed by ianlancetaylor** 2017-09-08 22:13 UTC
