### ISSUE TITLE
cmd/go: fmt always attempts to update module cache

### ISSUE THREAD

**Issue by driusan** [golang/go#30577] opened 2019-03-04 17:43 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/driusan/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/driusan/go"
GOPROXY=""
GORACE=""
GOROOT="/home/driusan/go1.12"
GOTMPDIR=""
GOTOOLDIR="/home/driusan/go1.12/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/driusan/Code/tst/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build265641249=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Inside of a go module, run `go fmt -x`

### What did you expect to see?

Invocations of `gofmt` to format the code.

### What did you see instead?

Invocations of `git` to attempt to update the dependency modules. `go fmt` appears to always update imported modules with `git`, and does not have any way to only autoformat the local files.

Other `go` commands such as `build` or `install` can avoid the git overhead with `-mod vendor`, but `fmt` doesn't support the `-mod` argument. As a result packages which are fully vendored can be built, but not formatted without a working internet connection and/or git client.

**Comment by mvdan** [comment] 2019-03-05 13:44
/cc @bcmills for the modules question.

As an aside, have you considered using `gofmt` instead? It's a lower-level tool that works on files and directories; `go fmt` calls it under the hood. It doesn't understand package patterns like `./...` or `foo.com/bar`, but usually a developer is formatting code near the current directory.

This is not to say that `gofmt` is a better tool, but if you want to format files without ever touching the module cache, it seems like the right tool for you.

**Comment by bcmills** [comment] 2019-03-05 14:27
> fmt doesn't support the -mod argument

Yep. And that makes this a duplicate of #27841.

**Closed by bcmills** 2019-03-05 14:27 UTC
Labels: modules

**Comment by driusan** [comment] 2019-03-05 14:46
@mvdan I'm using `gofmt` on individual files by necessity for now (this came up in the context of trying to bootstrap go module's git requirements into github.com/driusan/dgit, so go's "git" invocations aren't reliable for me because what I'm trying to do is get them to be reliable..)

@bcmills sorry, I did a search but missed that one.
