### ISSUE TITLE
cmd/go: test / tool cover: uncomfortable colors on html page with coverage results

### ISSUE THREAD

**Issue by Azatik1000** [golang/go#37796] opened 2020-03-11 15:45 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code></summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/azat/.cache/go-build"
GOENV="/home/azat/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/azat/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build595258626=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
$ go get gopl.io/ch7/eval
$ go test -run=Coverage -coverprofile=c.out gopl.io/ch7/eval
$ go tool cover -html=c.out
</pre>

### What did you expect to see?
Distinguishable text on html page with cover info

### What did you see instead?
Uncomfortable color set. It is hard to read gray, green and red on black. Perfectly it would be cool to have color settings for cover tool.
![image](https://user-images.githubusercontent.com/16105335/76435071-9b197500-63c7-11ea-95c0-a41440bad076.png)

**Comment by toothrot** [comment] 2020-03-11 17:11
Thanks for filing. Closing this as a duplicate of #36685

**Closed by toothrot** 2020-03-11 17:11 UTC

**Comment by Azatik1000** [comment] 2020-03-11 18:17
#36685 is about accessibility for screen readers, not about look & feel.

**Comment by Azatik1000** [comment] 2020-03-11 18:18
> Thanks for filing. Closing this as a duplicate of #36685

#36685 is about accessibility for screen readers, not about look & feel.

**Comment by toothrot** [comment] 2020-03-11 19:03
The decision of what colors to use must be considered from an accessibility perspective, so I feel like #36685 is the most accurate issue to use for discussing this. Please let me know if that is not the case.

**Comment by birchb1024** [comment] 2020-11-23 06:18
Try this

`$ go tool cover -html=c.out | sed '/background/d' > c.html`
