### ISSUE TITLE
cmd/vet: errors printed twice

### ISSUE THREAD

**Issue by thaJeztah** [golang/go#26222] opened 2018-07-04 23:55 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

```
go version go1.11beta1 linux/amd64
```

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

```
Linux eb9a716da0da 4.9.87-linuxkit-aufs #1 SMP Fri Mar 16 18:16:33 UTC 2018 x86_64 GNU/Linux
```

### What did you do?

1. create a directory `foo`, and inside that directory, create a file named test.go:

```go
package test

type MyStruct struct {}
func test(mystructs []*MyStruct) *MyStruct {
	var foo *MyStruct
	for _, mystruct := range mystructs {
		foo := mystruct
	}
	return foo
}
```

2. Run `go vet .`

### What did you expect to see?

```bash
go vet --shadow .
# _/foo
./test.go:7:3: foo declared and not used
```

<details>
<summary>output of `go vet -n .` on Go 1.10.3</summary>

```bash
go vet -n .

#
# _/foo
#

mkdir -p $WORK/b001/
cat >$WORK/b001/importcfg << 'EOF' # internal
# import config
EOF
cd /foo
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/b001/_pkg_.a -trimpath $WORK/b001 -p _/foo -complete -buildid aXr0bcv5wH9Nf8pWdoRi/aXr0bcv5wH9Nf8pWdoRi -goversion go1.10.3 -D _/foo -importcfg $WORK/b001/importcfg -pack -c=4 ./test.go
/usr/local/go/pkg/tool/linux_amd64/buildid -w $WORK/b001/_pkg_.a # internal
cat >$WORK/b001/vet.cfg << 'EOF' # internal
{
	"Compiler": "gc",
	"Dir": "/foo",
	"GoFiles": [
		"/foo/test.go"
	],
	"ImportMap": {
		"fmt": "fmt"
	},
	"PackageFile": {
		"fmt": "/usr/local/go/pkg/linux_amd64/fmt.a"
	},
	"ImportPath": "_/foo",
	"SucceedOnTypecheckFailure": false
}
EOF
/usr/local/go/pkg/tool/linux_amd64/vet $WORK/b001/vet.cfg
```
</details>

### What did you see instead?

```bash
go vet .
# _/foo
./test.go:7:3: foo declared and not used
# _/foo
./test.go:7:3: foo declared but not used
vet: typecheck failures
```

<details>
<summary>output of `go vet -n .` on Go 1.11beta1</summary>

```bash
go vet -n .

#
# _/foo
#

mkdir -p $WORK/b001/
cat >$WORK/b001/importcfg << 'EOF' # internal
# import config
EOF
cd /foo
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/b001/_pkg_.a -trimpath $WORK/b001 -p _/foo -complete -buildid SnS1ot0kWnaJXBLTwvxT/SnS1ot0kWnaJXBLTwvxT -goversion go1.11beta1 -D _/foo -importcfg $WORK/b001/importcfg -pack -c=4 ./test.go
/usr/local/go/pkg/tool/linux_amd64/buildid -w $WORK/b001/_pkg_.a # internal
cat >$WORK/b001/vet.cfg << 'EOF' # internal
{
	"Compiler": "gc",
	"Dir": "/foo",
	"ImportPath": "_/foo",
	"GoFiles": [
		"/foo/test.go"
	],
	"ImportMap": {
		"fmt": "fmt"
	},
	"PackageFile": {
		"fmt": "/usr/local/go/pkg/linux_amd64/fmt.a"
	},
	"Standard": {
		"fmt": true
	},
	"PackageVetx": {},
	"VetxOnly": false,
	"VetxOutput": "$WORK/b001/vet.out",
	"SucceedOnTypecheckFailure": false
}
EOF
/usr/local/go/pkg/tool/linux_amd64/vet $WORK/b001/vet.cfg
```
</details>

This issue is currently breaking gometalinter; see https://github.com/alecthomas/gometalinter/pull/499

**Comment by agnivade** [comment] 2018-07-05 04:29
Likely a duplicate of https://github.com/golang/go/issues/26125

**Comment by robpike** [comment] 2018-07-05 05:59
Duplicat of #26125

**Closed by robpike** 2018-07-05 05:59 UTC
Labels: NeedsInvestigation

**Comment by thaJeztah** [comment] 2018-07-05 06:52
ah, thanks! subscribing to that one
