### ISSUE TITLE
Go 1.7beta1 all.bash build failure: TestPackageNotStaleWithTrailingSlash cmd/fix, cmd/go

### ISSUE THREAD

**Issue by ajstarks** [golang/go#15946] opened 2016-06-02 22:29 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.7beta1 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ajstarks/gowork"
GORACE=""
GOROOT="/Users/ajstarks/go"
GOTOOLDIR="/Users/ajstarks/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ly/55wr2yk15r5bzxvvxxknvfr00000gn/T/go-build772300902=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?

./all.bash

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

4. What did you expect to see?

All tests pass

5. What did you see instead?

ok  	cmd/fix	0.017s
--- FAIL: TestPackageNotStaleWithTrailingSlash (0.15s)
	go_test.go:244: running testgo [list -f {{.Stale}}:{{.StaleReason}} runtime]
	go_test.go:259: standard output:
	go_test.go:260: false:standard package in Go release distribution
		
	go_test.go:562: wrong reason for Stale=false: "standard package in Go release distribution", want ""
	go_test.go:244: running testgo [list -f {{.Stale}}:{{.StaleReason}} os]
	go_test.go:259: standard output:
	go_test.go:260: false:standard package in Go release distribution
		
	go_test.go:562: wrong reason for Stale=false: "standard package in Go release distribution", want ""
	go_test.go:244: running testgo [list -f {{.Stale}}:{{.StaleReason}} io]
	go_test.go:259: standard output:
	go_test.go:260: false:standard package in Go release distribution
		
	go_test.go:562: wrong reason for Stale=false: "standard package in Go release distribution", want ""
FAIL
FAIL	cmd/go	28.395s

**Comment by adg** [comment] 2016-06-03 00:25
Dupe of #15933

**Closed by adg** 2016-06-03 00:25 UTC
