### ISSUE TITLE
cmd/compile: unnecessary bounds check

### ISSUE THREAD

**Issue by gnojus** [golang/go#64902] opened 2023-12-30 14:03 UTC
go1.21.5 
```
package p

func f(i int) {
    var t [3]int
    if i >= 0 {
        _ = t[i%len(t)]
    }
}
```
https://godbolt.org/z/Tda3649sv

I would assume, since i is non negative, `i % len(t)` should always be in bounds? But the assembly contains a `panicIndex`.

**Comment by Jorropo** [comment] 2023-12-31 08:58
I'm pretty sure this is a duplicate of #63110

**Comment by mknyszek** [comment] 2024-01-10 21:45
Closing as a duplicate of #63110. In triage we think it's pretty close to a duplicate, anyway.

**Closed by mknyszek** 2024-01-10 21:45 UTC
Labels: Performance, NeedsInvestigation, compiler/runtime
