### ISSUE TITLE
clean.bash fails in master

### ISSUE THREAD

**Issue by tuxychandru** [golang/go#10995] opened 2015-05-30 06:35 UTC
`src/clean.bash` fails to set `$GOROOT` correctly in master because it does not export the environment variables.

Changing [this line][buggyLine] to `eval $(go tool dist env | sed 's/^/export /')`, should fix it.

[buggyLine]: https://github.com/golang/go/blob/0724e5cefe92f9f4fd52101e3a7a25299a2b7f63/src/clean.bash

**Comment by minux** [comment] 2015-05-30 06:37
Dupe of #10734.

**Closed** 2015-05-30 06:38 UTC
