### ISSUE TITLE
runtime: crash when trying go run or go build

### ISSUE THREAD

**Issue by clamb** [golang/go#37638] opened 2020-03-03 21:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/christophe/go/bin"
GOCACHE="/Users/christophe/Library/Caches/go-build"
GOENV="/Users/christophe/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/christophe/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/85/01ftf7594x1_01_ps0ypv76h0000gn/T/go-build353558395=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?

trying to run the smallest possible go program:

<pre>
package main

import "fmt"

func main() {
    fmt.Println("Hello!")
}
</pre>

### What did you expect to see?

Hello!

### What did you see instead?

 <pre>
$ go run main.go
SIGILL: illegal instruction
PC=0x1065ae0 m=8 sigcode=1

goroutine 1 [running]:
runtime.asyncPreempt()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc00027d790 sp=0xc00027d788 pc=0x1065ae0
bufio.(*Reader).ReadByte(0xc000507920, 0xc00060c120, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/bufio/bufio.go:246 +0x17 fp=0xc00027d7b0 sp=0xc00027d790 pc=0x1185557
go/build.(*importReader).readByte(0xc00027d868, 0x20)
	/usr/local/Cellar/go/1.14/libexec/src/go/build/read.go:42 +0x32 fp=0xc00027d818 sp=0xc00027d7b0 pc=0x1196a42
go/build.(*importReader).peekByte(0xc00027d868, 0x1, 0x22)
	/usr/local/Cellar/go/1.14/libexec/src/go/build/read.go:90 +0xcf fp=0xc00027d840 sp=0xc00027d818 pc=0x1196c7f
go/build.readImports(0x172c8e0, 0xc000199fe0, 0xc000199f00, 0x0, 0xc000199fe0, 0x0, 0x0, 0xc000507588, 0x1680dd8)
	/usr/local/Cellar/go/1.14/libexec/src/go/build/read.go:218 +0x141 fp=0xc00027d918 sp=0xc00027d840 pc=0x11978a1
go/build.(*Context).matchFile(0x1acf300, 0xc0001b9e60, 0x2d, 0xc0003193ee, 0xe, 0xc00027de80, 0xc000248ee0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.14/libexec/src/go/build/build.go:1343 +0x336 fp=0xc00027da08 sp=0xc00027d918 pc=0x1192c36
go/build.(*Context).Import(0x1acf300, 0xc00019f727, 0x7, 0xc000299c00, 0x3a, 0x4, 0x159e620, 0xc0002a2060, 0xc00027e178)
	/usr/local/Cellar/go/1.14/libexec/src/go/build/build.go:808 +0xf15 fp=0xc00027e0c0 sp=0xc00027da08 pc=0x118afe5
cmd/go/internal/load.loadPackageData.func2(0x1ace620, 0x1578460)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/load/pkg.go:740 +0x4ff fp=0xc00027e1a8 sp=0xc00027e0c0 pc=0x13ab22f
cmd/go/internal/par.(*Cache).Do(0x1ace620, 0x1578460, 0xc0002b4540, 0xc00027e3a8, 0x15d9920, 0xc0002a36e0)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/par/work.go:128 +0xf3 fp=0xc00027e208 sp=0xc00027e1a8 pc=0x138f803
cmd/go/internal/load.loadPackageData(0xc00019f727, 0x7, 0xc0001c18e1, 0x14, 0xc000299c00, 0x3a, 0x172d960, 0x21, 0xc00027e401, 0x1, ...)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/load/pkg.go:714 +0x4a9 fp=0xc00027e420 sp=0xc00027e208 pc=0x1398b59
cmd/go/internal/load.loadImport(0x0, 0xc00019f727, 0x7, 0xc000299c00, 0x3a, 0xc0001ad680, 0xc00027fac0, 0xc0002a35f0, 0x1, 0x1, ...)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/load/pkg.go:549 +0x14e fp=0xc00027e598 sp=0xc00027e420 pc=0x139725e
cmd/go/internal/load.LoadImport(0xc00019f727, 0x7, 0xc000299c00, 0x3a, 0xc0001ad680, 0xc00027fac0, 0xc0002a35f0, 0x1, 0x1, 0x1, ...)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/load/pkg.go:531 +0xaa fp=0xc00027e608 sp=0xc00027e598 pc=0x13970ea
cmd/go/internal/load.(*Package).load(0xc0001ad680, 0xc00027fac0, 0xc000248a80, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/load/pkg.go:1707 +0x1b2b fp=0xc00027e978 sp=0xc00027e608 pc=0x139e1fb
cmd/go/internal/load.loadImport(0x0, 0xc0001c18e1, 0x14, 0xc0001b95f0, 0x2c, 0xc0001ad200, 0xc00027fac0, 0xc0002a2540, 0x1, 0x1, ...)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/load/pkg.go:578 +0xef7 fp=0xc00027eaf0 sp=0xc00027e978 pc=0x1398007
cmd/go/internal/load.LoadImport(0xc0001c18e1, 0x14, 0xc0001b95f0, 0x2c, 0xc0001ad200, 0xc00027fac0, 0xc0002a2540, 0x1, 0x1, 0x1, ...)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/load/pkg.go:531 +0xaa fp=0xc00027eb60 sp=0xc00027eaf0 pc=0x13970ea
cmd/go/internal/load.(*Package).load(0xc0001ad200, 0xc00027fac0, 0xc000248380, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/load/pkg.go:1707 +0x1b2b fp=0xc00027eed0 sp=0xc00027eb60 pc=0x139e1fb
cmd/go/internal/load.loadImport(0x0, 0xc00019ea71, 0x6, 0xc0001b9050, 0x29, 0xc0001acd80, 0xc00027fac0, 0xc0001a0500, 0x2, 0x2, ...)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/load/pkg.go:578 +0xef7 fp=0xc00027f048 sp=0xc00027eed0 pc=0x1398007
cmd/go/internal/load.LoadImport(0xc00019ea71, 0x6, 0xc0001b9050, 0x29, 0xc0001acd80, 0xc00027fac0, 0xc0001a0500, 0x2, 0x2, 0x1, ...)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/load/pkg.go:531 +0xaa fp=0xc00027f0b8 sp=0xc00027f048 pc=0x13970ea
cmd/go/internal/load.(*Package).load(0xc0001acd80, 0xc00027fac0, 0xc000248000, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/load/pkg.go:1707 +0x1b2b fp=0xc00027f428 sp=0xc00027f0b8 pc=0x139e1fb
cmd/go/internal/load.loadImport(0x0, 0xc00019e8b7, 0x3, 0xc000196740, 0x35, 0xc0001ac900, 0xc00027fac0, 0xc000230780, 0x1, 0x1, ...)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/load/pkg.go:578 +0xef7 fp=0xc00027f5a0 sp=0xc00027f428 pc=0x1398007
cmd/go/internal/load.LoadImport(0xc00019e8b7, 0x3, 0xc000196740, 0x35, 0xc0001ac900, 0xc000243ac0, 0xc000230780, 0x1, 0x1, 0x1, ...)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/load/pkg.go:531 +0xaa fp=0xc00027f610 sp=0xc00027f5a0 pc=0x13970ea
cmd/go/internal/load.(*Package).load(0xc0001ac900, 0xc00027fac0, 0xc000217c00, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/load/pkg.go:1707 +0x1b2b fp=0xc00027f980 sp=0xc00027f610 pc=0x139e1fb
cmd/go/internal/load.GoFilesPackage(0xc0001821a0, 0x1, 0x1, 0x1)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/load/pkg.go:2230 +0x546 fp=0xc00027fc28 sp=0xc00027f980 pc=0x13a3446
cmd/go/internal/run.runRun(0x1ac4aa0, 0xc0001821a0, 0x1, 0x1)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/run/run.go:79 +0x17b fp=0xc00027fdc8 sp=0xc00027fc28 pc=0x1510ccb
main.main()
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/main.go:189 +0x569 fp=0xc00027ff88 sp=0xc00027fdc8 pc=0x1530109
runtime.main()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:203 +0x212 fp=0xc00027ffe0 sp=0xc00027ff88 pc=0x1036b12
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00027ffe8 sp=0xc00027ffe0 pc=0x1064271

goroutine 2 [force gc (idle)]:
runtime.gopark(0x1680bf0, 0x1ace230, 0x1411, 0x1)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:304 +0xe0 fp=0xc00004cfb0 sp=0xc00004cf90 pc=0x1036ef0
runtime.goparkunlock(...)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:310
runtime.forcegchelper()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:253 +0xb7 fp=0xc00004cfe0 sp=0xc00004cfb0 pc=0x1036da7
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00004cfe8 sp=0xc00004cfe0 pc=0x1064271
created by runtime.init.6
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:242 +0x35

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1680bf0, 0x1ace480, 0x140c, 0x1)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:304 +0xe0 fp=0xc00004d7a8 sp=0xc00004d788 pc=0x1036ef0
runtime.goparkunlock(...)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:310
runtime.bgsweep(0xc00007c000)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgcsweep.go:70 +0x9c fp=0xc00004d7d8 sp=0xc00004d7a8 pc=0x102422c
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00004d7e0 sp=0xc00004d7d8 pc=0x1064271
created by runtime.gcenable
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:214 +0x5c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x1680bf0, 0x1ace440, 0x140d, 0x1)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:304 +0xe0 fp=0xc00004df78 sp=0xc00004df58 pc=0x1036ef0
runtime.goparkunlock(...)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:310
runtime.bgscavenge(0xc00007c000)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgcscavenge.go:237 +0xd0 fp=0xc00004dfd8 sp=0xc00004df78 pc=0x1022820
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00004dfe0 sp=0xc00004dfd8 pc=0x1064271
created by runtime.gcenable
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:215 +0x7e

goroutine 18 [finalizer wait]:
runtime.gopark(0x1680bf0, 0x1afa338, 0x101410, 0x1)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:304 +0xe0 fp=0xc00004c758 sp=0xc00004c738 pc=0x1036ef0
runtime.goparkunlock(...)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:310
runtime.runfinq()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mfinal.go:175 +0xa3 fp=0xc00004c7e0 sp=0xc00004c758 pc=0x1019ec3
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00004c7e8 sp=0xc00004c7e0 pc=0x1064271
created by runtime.createfing
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mfinal.go:156 +0x61

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x1680a40, 0xc00008e000, 0x1418, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:304 +0xe0 fp=0xc000048760 sp=0xc000048740 pc=0x1036ef0
runtime.gcBgMarkWorker(0xc000034000)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1865 +0xff fp=0xc0000487d8 sp=0xc000048760 pc=0x101d87f
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000487e0 sp=0xc0000487d8 pc=0x1064271
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1813 +0x77

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x1680a40, 0xc00011a000, 0x1418, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:304 +0xe0 fp=0xc000048f60 sp=0xc000048f40 pc=0x1036ef0
runtime.gcBgMarkWorker(0xc000036800)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1865 +0xff fp=0xc000048fd8 sp=0xc000048f60 pc=0x101d87f
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000048fe0 sp=0xc000048fd8 pc=0x1064271
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1813 +0x77

goroutine 34 [GC worker (idle)]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:330 fp=0xc000120708 sp=0xc000120700 pc=0x1062180
runtime.gcMarkDone()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1441 +0xbb fp=0xc000120760 sp=0xc000120708 pc=0x101c95b
runtime.gcBgMarkWorker(0xc000039000)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1992 +0x29e fp=0xc0001207d8 sp=0xc000120760 pc=0x101da1e
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0001207e0 sp=0xc0001207d8 pc=0x1064271
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1813 +0x77

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x1680a40, 0xc000481c20, 0x1418, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:304 +0xe0 fp=0xc000049760 sp=0xc000049740 pc=0x1036ef0
runtime.gcBgMarkWorker(0xc00003b800)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1865 +0xff fp=0xc0000497d8 sp=0xc000049760 pc=0x101d87f
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000497e0 sp=0xc0000497d8 pc=0x1064271
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1813 +0x77

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x1680a40, 0xc00011a010, 0x1418, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:304 +0xe0 fp=0xc000049f60 sp=0xc000049f40 pc=0x1036ef0
runtime.gcBgMarkWorker(0xc00003e000)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1865 +0xff fp=0xc000049fd8 sp=0xc000049f60 pc=0x101d87f
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000049fe0 sp=0xc000049fd8 pc=0x1064271
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1813 +0x77

goroutine 50 [GC worker (idle)]:
runtime.gopark(0x1680a40, 0xc000481c30, 0x1418, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:304 +0xe0 fp=0xc00011c760 sp=0xc00011c740 pc=0x1036ef0
runtime.gcBgMarkWorker(0xc000040800)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1865 +0xff fp=0xc00011c7d8 sp=0xc00011c760 pc=0x101d87f
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00011c7e0 sp=0xc00011c7d8 pc=0x1064271
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1813 +0x77

goroutine 23 [semacquire]:
runtime.gopark(0x1680bf0, 0x1ad6de0, 0xc000681912, 0x4)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:304 +0xe0 fp=0xc00004a6a0 sp=0xc00004a680 pc=0x1036ef0
runtime.goparkunlock(...)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:310
runtime.semacquire1(0x1acfaf4, 0xc000600000, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/sema.go:144 +0x1c0 fp=0xc00004a708 sp=0xc00004a6a0 pc=0x1047120
runtime.semacquire(...)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/sema.go:95
runtime.gcMarkDone()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1425 +0x3e fp=0xc00004a760 sp=0xc00004a708 pc=0x101c8de
runtime.gcBgMarkWorker(0xc000043000)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1992 +0x29e fp=0xc00004a7d8 sp=0xc00004a760 pc=0x101da1e
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00004a7e0 sp=0xc00004a7d8 pc=0x1064271
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1813 +0x77

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x1680a40, 0xc00008e020, 0x1418, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:304 +0xe0 fp=0xc000120f60 sp=0xc000120f40 pc=0x1036ef0
runtime.gcBgMarkWorker(0xc000045800)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1865 +0xff fp=0xc000120fd8 sp=0xc000120f60 pc=0x101d87f
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000120fe0 sp=0xc000120fd8 pc=0x1064271
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.14/libexec/src/runtime/mgc.go:1813 +0x77

rax    0xc00027d868
rbx    0xc00027d868
rcx    0xc000000180
rdx    0x0
rdi    0xc00027d870
rsi    0x118
rbp    0xc00027d808
rsp    0xc00027d788
r8     0x119
r9     0xc000616000
r10    0x200
r11    0x0
r12    0x0
r13    0x40
r14    0x1
r15    0x20
rip    0x1065ae0
rflags 0x10206
cs     0x2b
fs     0x0
gs     0x0
</pre>

**Comment by mvdan** [comment] 2020-03-03 21:25
Duplicate of https://github.com/golang/go/issues/37459? The panic trace looks very similar. Please confirm what machine this is on.

/cc @randall77 @dmitshur

**Comment by randall77** [comment] 2020-03-03 21:26
If it is #37459 (which seems likely), it will be fixed in 1.14.1.

**Comment by clamb** [comment] 2020-03-03 21:32
Sorry, I should have spent more time trying to search for this issue before opening a new one. 

This is most likely the same problem: macOS High Sierra (10.13.6) with a late 2009 iMac (2.8 GHz Intel Core i7). 

You can close this issue.

**Comment by mvdan** [comment] 2020-03-03 21:34
Thanks!

**Closed by mvdan** 2020-03-03 21:34 UTC

**Comment by Shurikken** [comment] 2020-03-19 22:04
i have same probleme and i test go 1.14.1 but problem is same with mac os hight sierra 2009 10 13 6 
when i use hugo and every go command

`SIGILL: illegal instruction
PC=0x406a440 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc0000e5d98 sp=0xc0000e5d90 pc=0x406a440
github.com/alecthomas/chroma/styles.init()
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/alecthomas/chroma@v0.7.1/styles/autumn.go:8 +0x121f fp=0xc0000e5dd8 sp=0xc0000e5d98 pc=0x46dbfff
runtime.doInit(0x692bfa0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5414 +0x8a fp=0xc0000e5e08 sp=0xc0000e5dd8 pc=0x404547a
runtime.doInit(0x6934ea0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc0000e5e38 sp=0xc0000e5e08 pc=0x4045447
runtime.doInit(0x6933040)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc0000e5e68 sp=0xc0000e5e38 pc=0x4045447
runtime.doInit(0x6932fe0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc0000e5e98 sp=0xc0000e5e68 pc=0x4045447
runtime.doInit(0x693f940)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc0000e5ec8 sp=0xc0000e5e98 pc=0x4045447
runtime.doInit(0x6935ea0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc0000e5ef8 sp=0xc0000e5ec8 pc=0x4045447
runtime.doInit(0x6944280)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc0000e5f28 sp=0xc0000e5ef8 pc=0x4045447
runtime.doInit(0x69438e0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc0000e5f58 sp=0xc0000e5f28 pc=0x4045447
runtime.doInit(0x692b560)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc0000e5f88 sp=0xc0000e5f58 pc=0x4045447
runtime.main()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:190 +0x1ce fp=0xc0000e5fe0 sp=0xc0000e5f88 pc=0x403887e
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000e5fe8 sp=0xc0000e5fe0 pc=0x4068bc1

rax    0xc000515ce0
rbx    0x1f41
rcx    0x0
rdx    0x5caa4c0
rdi    0xc000515cf0
rsi    0x8
rbp    0xc0000e5dc8
rsp    0xc0000e5d90
r8     0xaa37c4b
r9     0x203000
r10    0xd0
r11    0xfa
r12    0xfa
r13    0xaaaa802aaaa00
r14    0x5c18dcc
r15    0x34
rip    0x406a440
rflags 0x10297
cs     0x2b
fs     0x0
gs     0x0`

**Comment by randall77** [comment] 2020-03-19 22:11
I don't think you're actually running 1.14.1 there. That still looks like a 1.14 trace.
Try running `go version` and see what it says.

**Comment by Shurikken** [comment] 2020-03-19 22:20
> Je ne pense pas que vous utilisez actuellement la version 1.14.1. Cela ressemble toujours à une trace 1.14.
> Essayez de courir `go version`et voyez ce qu'il dit.

go version go1.14.1 darwin/amd64

**Comment by dmitshur** [comment] 2020-03-19 23:16
@Shurikken Please open a new issue, with information how to reproduce this problem with Go 1.14.1, so we can investigate. Thank you.
