### ISSUE TITLE
gccgo:  go1: internal compiler error: in mangled_name, at go/gofrontend/names.cc:559

### ISSUE THREAD

**Issue by wmhrae** [golang/go#33783] opened 2019-08-22 08:48 UTC
#### 1: GCCGO

At command line I typed gccgo -v and it spits out 9.2.0 
```
PACKAGE NAME: gcc-9.2.0-x86_64-1 - date build and installed Aug 18
PACKAGE NAME: gcc-go-9.2.0-x86_64-1 - date build and installed Aug 18
PACKAGE NAME: gcc-g++-9.2.0-x86_64-1
PACKAGE NAME: gcc-gdc-9.2.0-x86_64-1
PACKAGE NAME: gcc-gfortran-9.2.0-x86_64-1
PACKAGE NAME: gcc-gnat-9.2.0-x86_64-1
PACKAGE NAME: gcc-objc-9.2.0-x86_64-1
```

#### 2: ENV

```
bash-5.0# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr"
GOTMPDIR=""
GOTOOLDIR="/usr/libexec/gcc/x86_64-slackware-linux/9.2.0"
GCCGO="/usr/bin/gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build262316847=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
bash-5.0#
```

#### 3: What did you do?

```
_/tmp/SBo/thrift-0.12.0/lib/go/thrift
go1: internal compiler error: in mangled_name, at go/gofrontend/names.cc:559
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[4]: *** [Makefile:826: all-local] Error 2
make[4]: Leaving directory '/tmp/SBo/thrift-0.12.0/lib/go'
make[3]: *** [Makefile:540: all-recursive] Error 1
make[3]: Leaving directory '/tmp/SBo/thrift-0.12.0/lib/go'
make[2]: *** [Makefile:582: all-recursive] Error 1
make[2]: Leaving directory '/tmp/SBo/thrift-0.12.0/lib'
make[1]: *** [Makefile:664: all-recursive] Error 1
make[1]: Leaving directory '/tmp/SBo/thrift-0.12.0'
make: *** [Makefile:578: all] Error 2
bash-5.0#
```

####  4: What did you expect to see?
PACKAGE NAME: thrift-0.12.0-x86_64-1

#### 5: What did you see instead?
go1: internal compiler error: in mangled_name, at go/gofrontend/names.cc:559

**Comment by ALTree** [comment] 2019-08-22 09:46
Thanks for the report. 

The "what did you do" section of your report does not show what you did. It just shows the result of the command (a compiler crash). I'm *guessing* you are building `github/apache/thrift` with gccgo, but please confirm this to facilitate the investigation of the issue. You should provide a list of steps (in the form of terminal commands) that can be used to reproduce the crash. Thanks.

**Comment by wmhrae** [comment] 2019-08-25 06:09
Yes I use github/apache/thrift with gccgo :+1: 
PACKAGE NAME: gcc-9.2.0-x86_64-1 - date build and installed Aug 18
PACKAGE NAME: gcc-go-9.2.0-x86_64-1 - date build and installed Aug 18

**Comment by thanm** [comment] 2019-10-23 12:20
Thanks for filing this bug. It looks as though it was discovered independently (see [issue 33871](https://github.com/golang/go/issues/33871) and Ian has submitted a fix.  With a tip version of gccgo I was able to successfully issue 

`go get github.com/apache/thrift/lib/go/thrift/...`

So I am going to assume that this fixes your issue.

**Comment by thanm** [comment] 2019-10-23 12:21
Duplicate of #33871

**Closed** 2019-10-23 12:21 UTC
Labels: NeedsInvestigation
