### ISSUE TITLE
proposal: Functional Go(built in support for lambda, foreach ,map , filter , map )

### ISSUE THREAD

**Issue by gitsupi** [golang/go#58443] opened 2023-02-09 19:12 UTC
proposal: Functional Go(built in support for lambda, foreach ,map , filter , map )

**Comment by seankhliao** [comment] 2023-02-09 19:22
Duplicate of #21498

**Closed by seankhliao** 2023-02-09 19:22 UTC
Labels: Proposal

**Comment by gitsupi** [comment] 2023-02-09 19:24
why not planned

**Comment by loveyandex** [comment] 2023-02-09 19:25
@seankhliao

**Comment by 4cq2** [comment] 2023-05-28 19:25
https://github.com/golang/go/issues/58014
