### ISSUE TITLE
runtime: Channel blocks with odd len

### ISSUE THREAD

**Issue by sv** [golang/go#12797] opened 2015-09-30 16:54 UTC
I am pushing few messages via channel from C library (code is here https://bitbucket.org/svidyuk/lbmgo)

After processing 1-100 messages(tried with GOGC=off as well) I see that incoming channel(https://bitbucket.org/svidyuk/lbmgo/src/a9618e6ee1cd94a5237b12d2a1043408562c8f32/lbm.go?at=master&fileviewer=file-view-default#lbm.go-28) length jumps to very large number 859531108376.

At his stage all following pushes of messages block indefinitely and no new incoming data is processed.

This is the case for both 1.4.2 and 1.5.0

Address of the incoming channel is always  the same.

Simple program that I use:
```
var bboChan chan *lbm.Message
var receiver *lbm.WildcardReceiver

func listenBBO() {
  for {
    msg := <-bboChan
    if msg.MsgType == lbm.MSG_DATA {
      glog.Infoln("message", msg)
    }
  }

}
func subscribeBBO() {
  glog.Infoln("Configuring LBM component")
  err := lbm.Config("test.xml")
  if err != nil {
    glog.Infoln("Failed to configure subscription. Using defaults", err)
  }
  glog.Infoln("Setting up new context")
  ctx, err := lbm.NewContext()
  if err != nil {
    glog.Infoln("Failed to create context", err)
    return
  }
  bboChan = make(chan *lbm.Message, 1000)
  receiver, err = ctx.NewWildcardReceiver("/test/.*", bboChan)
  if err != nil {
    glog.Infoln("Failed to subscribe to bbo")
    return
  }
  go listenBBO()
}

```

Stack trace once len(incoming) is very large looks like:
```
panic: test

goroutine 17 [running, locked to thread]:
bitbucket.org/svidyuk/lbmgo.lbm_receiver_callback(0x0, 0x7f61fc0d9270, 0xc8200be028, 0x0)
        /home/sergey/go/src/bitbucket.org/svidyuk/lbmgo/lbm.go:39 +0x3b6

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f621aba5d78, 0x72, 0xc820014190)
        /usr/lib/golang/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201da450, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201da450, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201da3f0, 0x0, 0x7f6218112430, 0xc8200bb240)
        /usr/lib/golang/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200be078, 0xc8200e5bd8, 0x0, 0x0)
        /usr/lib/golang/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc8200be078, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc8200b82a0, 0x7f62181123f8, 0xc8200be078, 0x0, 0x0)
        /usr/lib/golang/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc8200b82a0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc820104670, 0x6, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/server.go:1967 +0x8f
main.main()
        /home/sergey/go/src/posmanager/posmanager.go:358 +0x9e7

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xc945a0)
        /home/sergey/go/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/golang/glog.init.1
        /home/sergey/go/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 6 [syscall]:
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/lib/golang/src/os/signal/signal_unix.go:28 +0x37

goroutine 9 [chan receive]:
database/sql.(*DB).connectionOpener(0xc820017360)
        /usr/lib/golang/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
        /usr/lib/golang/src/database/sql/sql.go:481 +0x336

goroutine 11 [IO wait]:
net.runtime_pollWait(0x7f621aba5ef8, 0x72, 0xc820014190)
        /usr/lib/golang/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820102e60, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820102e60, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820102e00, 0xc820178000, 0x1000, 0x1000, 0x0, 0x7f621aba0050, 0xc820014190)
        /usr/lib/golang/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200580b0, 0xc820178000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc820022840)
        /usr/lib/golang/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820022840, 0xc8201d8bf0, 0x8, 0x8, 0x75bd20, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f621814e080, 0xc820022840, 0xc8201d8bf0, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/io/io.go:298 +0xe6
io.ReadFull(0x7f621814e080, 0xc820022840, 0xc8201d8bf0, 0x8, 0x8, 0x8, 0x0, 0x0)
        /usr/lib/golang/src/io/io.go:316 +0x62
encoding/binary.Read(0x7f621814e080, 0xc820022840, 0x7f621814e028, 0xcb96b0, 0x7e1120, 0xc8201d8b90, 0x0, 0x0)
        /usr/lib/golang/src/encoding/binary/binary.go:216 +0x1336
bitbucket.org/svidyuk/kdbgo.Decode(0xc820022840, 0x0, 0xc8201bdc18, 0x0, 0x0)
        /home/sergey/go/src/bitbucket.org/svidyuk/kdbgo/decode.go:128 +0x131
bitbucket.org/svidyuk/kdbgo.(*KDBConn).ReadMessage(0xc82000b140, 0x2, 0x2, 0x0, 0x0)
        /home/sergey/go/src/bitbucket.org/svidyuk/kdbgo/kdb.go:100 +0x33
main.connectKDB.func1(0xc82000b140, 0xc820017360)
        /home/sergey/go/src/posmanager/posmanager.go:109 +0xb66
created by main.connectKDB
        /home/sergey/go/src/posmanager/posmanager.go:138 +0x329

goroutine 19 [chan receive]:
main.listenBBO()
        /home/sergey/go/src/posmanager/lbm.go:19 +0x1e3
created by main.subscribeBBO
        /home/sergey/go/src/posmanager/lbm.go:58 +0x6b4

goroutine 34 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1

```

**Comment by ianlancetaylor** [comment] 2015-09-30 19:49
I don't see any calls to len in your sample code.

It sounds like your program calls C code.  The problem is almost certainly memory corruption caused by the C code.  You should also run your program under the race detector, to make sure that is not the problem.

If there is a problem in Go, then in order to fix it we will need to see a complete test case.

**Comment by sv** [comment] 2015-09-30 19:53
If I print len(incoming) before this line, I get huge number - https://bitbucket.org/svidyuk/lbmgo/src/a9618e6ee1cd94a5237b12d2a1043408562c8f32/lbm.go?at=master&fileviewer=file-view-default#lbm.go-35

I will try to run it with race detector and report back. Should I push pointers or entire messages to `incoming` chan?

**Comment by ianlancetaylor** [comment] 2015-09-30 20:00
You are passing pointers to C in a way that is most likely unsafe.  See issue #12416 .

In particular, what are you doing to ensure that the `incoming` channel is not garbage collected?

**Comment by sv** [comment] 2015-09-30 21:07
i have it as global in a sample above
```
var bboChan chan *lbm.Message
```

**Comment by sv** [comment] 2015-10-01 08:26
I ran it with race detector, but still end up with len(incoming) = 859530690592

**Comment by mwhudson** [comment] 2015-10-01 09:11
On 1 October 2015 at 21:27, Sergey Vidyuk <notifications@github.com> wrote:

> I ran it with race detector, but still end up with len(incoming) =
> 859530690592
>
That's almost certainly a heap pointer, fwiw.

**Comment by sv** [comment] 2015-10-01 09:49
fmt.Println(incoming) gives consistently same address. I will try to put channels that i pass to C code into map instead of having global and see if it makes any difference

**Comment by sv** [comment] 2015-10-01 10:10
same result. I have dependency on external library. I can provide binary and some of source code if needed. 

number that gets printed is 88 bytes further then address of the channel

**Comment by ianlancetaylor** [comment] 2015-10-01 15:11
This is pretty much what I would expect if the channel is getting garbage collected while the C code is holding on to the channel pointer.

As I said earlier, if there is a problem in Go, then in order to fix it we will need to see a complete test case.  So far I think it's very unlikely that this is a problem in Go.

**Comment by sv** [comment] 2015-10-01 15:43
How could it be fixed? It there any non trivial example of callback code?

Channel is global variable and should not be garbage collected.
Additionally it still breaks with GOGC=off

**Comment by ianlancetaylor** [comment] 2015-10-01 17:20
OK, so it is probably not GC.  Still, it sounds like the channel memory is getting corrupted.  If I had to solve this, I would probably run the program under the debugger, find the address of the length in the channel structure, set a watchpoint on that memory location, and see when it changes.

There are various examples of callbacks in the tree, for example in misc/cgo/test, but they are all fairly trivial.

**Comment by sv** [comment] 2015-10-08 17:20
```
func lbm_receiver_callback(rcv unsafe.Pointer, msg unsafe.Pointer, clientd unsafe.Pointer) int {
incoming := *(*chan *Message)(clientd)
fmt.Println(clientd, &incoming)
}
```
should i expect address of incoming and clientd to match? above prints different address for incoming each time.

**Comment by ianlancetaylor** [comment] 2015-10-08 17:30
In your code fragment, incoming is a new local variable.  Changing *clientd after the assignment will not affect incoming.  It would not make sense for &incoming to be the same as clientd.

**Comment by sv** [comment] 2015-10-08 20:28
Wrapping chan to struct before passing to C code allows resulting program to run for many minutes.
See change: https://bitbucket.org/svidyuk/lbmgo/commits/5060d1f97e80eac1a6d1ed03352ec9dd880c4fb2?at=master

Is it expected behaviour? I will do more testing tomorrow and see if error comes up again

**Comment by sv** [comment] 2015-10-14 14:37
This is working with the change specified in previous message. Should it be documented that you need to be careful when passing chan pointer to c code?

**Comment by ianlancetaylor** [comment] 2015-10-14 16:47
The only beneficial effect I see in your change is that putting the wrapper struct in a map ensures that it will not be garbage collected while executing C code.  I think if you do the same thing with the channel then your code will work without the wrapper struct.

However, none of this code will work if the proposal I've described in https://golang.org/issue/12416 is adopted.  That proposal will outlaw passing channel pointers to C at all.

Since you have your code working I'm going to close this issue.  Feel free to reopen if I misunderstand.

**Closed by ianlancetaylor** 2015-10-14 16:47 UTC
