### ISSUE TITLE
Unable to locate package golang-1.11-go

### ISSUE THREAD

**Issue by dys001** [golang/go#66307] opened 2024-03-14 07:04 UTC
Recently, there has been a version upgrade for golang. Could anyone experienced guide me on how to deploy a golang project with version 1.11? 
Below are the deployment commands and the error messages I encountered.

add-apt-repository ppa:longsleep/golang-backports 
apt-get install golang-1.11-go

Error:
E: Unable to locate package golang-1.11-go
E: Couldn't find any package by glob 'golang-1.11-go'
E: Couldn't find any package by regex 'golang-1.11-go'

![Uploading 截屏2024-03-14 14.54.42.png…]()

**Comment by dys001** [comment] 2024-03-14 07:05
<img width="1233" alt="截屏2024-03-14 14 54 42" src="https://github.com/golang/go/assets/74577977/b9c22afb-d580-460e-b61b-6997c2c8d076">

**Comment by ALTree** [comment] 2024-03-14 07:44
Go 1.11 is pretty old (released in 2018) and it's no longer supported. It looks like the PPA you are using doesn't package it. Anyway you should use a more recent and supported version (e.g. Go 1.22).

Closing here since this is not a bug in Go.

**Closed by ALTree** 2024-03-14 07:44 UTC
