### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by LarsenDR** [golang/go#48345] opened 2021-09-12 14:13 UTC
### What version of Go are you using (`go version`)? 
1.17.1

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?  
golang.org website issue

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?  

golang.org website in android 11 chrome browser produces a "hamburger" inset of a top bar.  
When clicked is does not produce the links in the desktop links.

### What did you expect to see?

I expected the "hamburger" to produce the links that are in the  desktop bar.

### What did you see instead?

No links

**Comment by seankhliao** [comment] 2021-09-12 14:57
Duplicate of #47862

**Closed by seankhliao** 2021-09-12 14:57 UTC
