### ISSUE TITLE
net/url: `QueryEscape` escapes its own escape characters

### ISSUE THREAD

**Issue by UndeadBaneGitHub** [golang/go#56503] opened 2022-10-31 23:53 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.19.2
</pre>

But really, affects 1.18 and other versions too

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?
It's universal anywhere, since it's a bug in logic implementation of internal `shouldEscape` method

### What did you do?

Playground link: https://go.dev/play/p/WXXx4EiSy_E

### What did you expect to see?

Already escaped string should not be escaped again (example behavior: Javascript `encodeURIComponent` method and similar)

### What did you see instead?

It gets escaped as many times as the method is called.

**Comment by seankhliao** [comment] 2022-11-01 00:02
The `+` sign carries semantic meaning within url query escaping, in general it won't be possible to know if it has been escaped before.

Closing as working as intended.

**Comment by UndeadBaneGitHub** [comment] 2022-11-01 00:03
It also escapes `%` sign as shown in the playground, it is _not_ working as intended.

**Closed by seankhliao** 2022-11-01 00:02 UTC

**Comment by ianlancetaylor** [comment] 2022-11-01 00:04
The JavaScript `encodeURIComponent` function also escapes a `%` character in its input string, encoding it as `%25`.

We aren't going to make any changes here.
