### ISSUE TITLE
cmd/compile: crash when masking len builtin with a const of same name

### ISSUE THREAD

**Issue by kwoodhouse93** [golang/go#30133] opened 2019-02-08 16:09 UTC
### What version of Go are you using (`go version`)?

> The playground uses the latest stable release of Go.
> The current version is go1.11.1. 

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Minimal example:
https://play.golang.org/p/zVHeuxQmSGD

### What did you expect to see?

A compiler error

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xb7c7ee]

goroutine 1 [running]:
cmd/compile/internal/gc.typecheck1(0xc00034e000, 0x1, 0xca41c5)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:1270 +0x3ece
cmd/compile/internal/gc.typecheck(0xc00034e000, 0x1, 0x3)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:238 +0x6ad
cmd/compile/internal/gc.typecheckslice(0xc0000705a0, 0x1, 0x1, 0x1)
	/usr/local/go/src/cmd/compile/internal/gc/typecheck.go:68 +0x50
cmd/compile/internal/gc.Main(0xcc2180)
	/usr/local/go/src/cmd/compile/internal/gc/main.go:518 +0x2059
main.main()
	/usr/local/go/src/cmd/compile/main.go:51 +0x96
```

**Comment by bmkessler** [comment] 2019-02-08 16:44
This may be a duplicate of https://github.com/golang/go/issues/27973

**Comment by randall77** [comment] 2019-02-08 16:48
This seems to be fixed at tip.
We could consider a backport to 1.11, but I'm inclined not to for this error, it's pretty obscure.

**Comment by ALTree** [comment] 2019-02-08 17:15
The fix was already backported to 1.11 (#27399). Please upgrade your 1.11 installation to the latest 1.11.5. 

Closing here.

**Closed by ALTree** 2019-02-08 17:15 UTC

**Comment by johanbrandhorst** [comment] 2019-02-08 17:18
Does this mean the playground is also running an old version of Go?

**Comment by ALTree** [comment] 2019-02-08 17:19
> Does this mean the playground is also running an old version of Go?

Yes: https://play.golang.org/p/1VcPUlPk_3

It's currently on 1.11.1.
