### ISSUE TITLE
go is not available on arm devices

### ISSUE THREAD

**Issue by wahyu6070** [golang/go#43436] opened 2020-12-30 17:56 UTC
why go is not available on arm devices

**Comment by ALTree** [comment] 2020-12-30 18:00
It is, both on arm and arm64: https://golang.org/dl/.

The Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-12-30 18:00 UTC
