### ISSUE TITLE
net/http: Transport.getConn is wasting one connection sometimes.

### ISSUE THREAD

**Issue by kassiansun** [golang/go#60111] opened 2023-05-10 14:23 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.4 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN="/Users/kassian/.cache/go-path/bin"
GOCACHE="/Users/kassian/Library/Caches/go-build"
GOENV="/Users/kassian/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/kassian/.cache/go-path/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/kassian/.cache/go-path"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/opt/homebrew/Cellar/go/1.20.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.20.4/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hk/t8qz75gn6299szmkb94z5ys00000gn/T/go-build874776608=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

We're connection to Elasticsearch from Go, and notice some `Connection reset` at the Elasticsearch side. After some investigations, it seems that `http.Transport.getConn` will try to get an idle connection from the pool (`queueForIdleConn`) and dial the remote host (`queueForDial`) at the same time. So if the request finished and `req.Context` cancelled before dial complete, the `addTLS` step will fail due to context cancelled. Is it possible to continue the dialing and TLS handshake so we can get an usable connection instead of aborting it?

### What did you expect to see?

If the `req.Context` finished before TLS handshake finish, the dialing connection will get closed.

### What did you see instead?

The dialing step can finish and the connection can be put into the idle pool.

**Comment by seankhliao** [comment] 2023-05-10 17:25
Duplicate of #50984

**Closed by seankhliao** 2023-05-10 17:25 UTC
