### ISSUE TITLE
x/pkgsite: Missing output in exec documentation

### ISSUE THREAD

**Issue by tlarnold10** [golang/go#64870] opened 2023-12-26 17:27 UTC
### What is the URL of the page with the issue?
 https://pkg.go.dev/os/exec
 
### What is your user agent?
[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
 
 
### Screenshot
![image](https://github.com/golang/go/assets/20311878/98f07803-14aa-4377-b907-774afd4691b8)

 
 
### What did you do?
Loaded page and scroll to examples.
 
### What did you expect to see?
 Sample output for any example code snippets that have output.
 
 
### What did you see instead?
No output for any examples on the page.

I am willing to fix this.

**Comment by seankhliao** [comment] 2023-12-26 19:13
Duplicate of #9679

**Closed by seankhliao** 2023-12-26 19:13 UTC
Labels: pkgsite
