### ISSUE TITLE
go:embed with /* path ignores subfolders that contain dot files

### ISSUE THREAD

**Issue by john8329** [golang/go#48888] opened 2021-10-09 11:19 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
See before

### What did you do?

* Create a directory named "files" with dot files (e.g. `.gitkeep`)
* Inside that directory, create a sub-directory containing a dot file **only**
* Embed the root directory with `//go:embed files/*`
* Try to compile

### What did you expect to see?
I expect that if I ask to embed all files, it reads them also in sub-directories rather than only at the root. Documentation about this seems a bit unclear.

### What did you see instead?
```
pattern files/*: cannot embed directory files/assets: contains no embeddable files
```

**Comment by seankhliao** [comment] 2021-10-09 11:24
Duplicate of #43854

**Closed by seankhliao** 2021-10-09 11:24 UTC
