### ISSUE TITLE
proposal: x/tools/go/packages: add Package.{IsNormal,IsTest,IsExternalTest} bool fields

### ISSUE THREAD

**Issue by willfaught** [golang/go#61250] opened 2023-07-09 22:29 UTC
packages.Load returns a slice of packages.Package, so if you want to single out one of these types of package, you have to iterate through all of them and look for signs that signal one type or another, basically the presence of a _test suffix in the package name and the presence of _test.go files. It would be nice for Load to have a way to explicitly tell you what sort of package it is.

Alternatively, add some kind of type enum field with normal, test, and external test values.

**Comment by seankhliao** [comment] 2023-07-09 22:35
Duplicate of #27910

**Closed by seankhliao** 2023-07-09 22:35 UTC
Labels: Proposal
