### ISSUE TITLE
cmd/compile/internal/types2: predeclared type "comparable" must not be visible before Go 1.18

### ISSUE THREAD

**Issue by mdempsky** [golang/go#46090] opened 2021-05-10 20:02 UTC
This package produces an "undefined: any" error when compiled with `go tool compile -G=1`:

```
package p
type _ any
```

but this package successfully type-checks (but fails later anyway when compiled with -G=3):

```
package p
type _ comparable
```

They both produce errors on go2goplay.golang.org.

/cc @griesemer @findleyr

**Comment by griesemer** [comment] 2021-06-29 01:04
I believe this is working as intended: `any` may only be used in constraint position (for now, eventually we may make it generally acceptable in place of `interface{}`). `comparable` is a predeclared interface type that may be used in types (incl. type declarations); but using a type that is (or embeds) `comparable` as type for an ordinary variable, or field results in an error.

**Comment by mdempsky** [comment] 2021-06-29 01:55
I think I'm inclined to agree. I'm not sure why I thought `type _ comparable` should have been invalid, except that go2go rejected it and I must have assumed go/types was actually rejecting it.

Looking more closely at the go2go error diagnostics, I suspect the error message is actually because go2go is generating invalid code in this case. (`undefined: comparable` looks like a cmd/compile error message, not a go/types one.)

**Comment by ianlancetaylor** [comment] 2021-06-29 16:43
In case it helps, go2go reports go/types errors with a prefix of "type checking failed for PACKAGE".  If you see that message, there is probably a problem with the code being translated.  If you don't see that message, it's probably a bug in go2go.

**Comment by mdempsky** [comment] 2021-06-29 17:42
@ianlancetaylor Thanks for the tip.

**Comment by griesemer** [comment] 2021-08-04 20:48
This was fixed by

https://golang.org/cl/331517 in `types2`
https://golang.org/cl/335032 in `go/types`

**Closed by griesemer** 2021-08-04 20:48 UTC
Labels: NeedsInvestigation
