### ISSUE TITLE
affected/package: all

### ISSUE THREAD

**Issue by karisawa** [golang/go#51159] opened 2022-02-12 03:29 UTC
### What version of Go are you using (`go version`)?

<pre>
go1.17.6
</pre>

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
plan9/amd64
</pre></details>

### What did you do?

package main
import(
	. "fmt"
)
func f(n,m int) bool{
	if n >= m {
		return false
	}
	return true
}

func main(){
	ok := true
	for k:=0;ok;k++ {
		//ok = f(k,3) // OK
		ok := f(k,3) // NG
		Println(k,ok)
	}
}

### What did you expect to see?
compile error

### What did you see instead?
compile is passed without error and the execution falls into endless loop

**Comment by beoran** [comment] 2022-02-12 04:44
This is not a bug but a feature. If you redeclare the variable ok in the block,  it shadows the higher level ok. Use the simple assignment in stead. Also see: https://rpeshkov.net/blog/golang-variable-shadowing/

**Comment by mdlayher** [comment] 2022-02-12 05:47
Closing per above.

**Closed by mdlayher** 2022-02-12 05:47 UTC
