### ISSUE TITLE
I always get the error "unencrypted connection"

### ISSUE THREAD

**Issue by alsmn** [golang/go#24459] opened 2018-03-20 10:18 UTC
my go versioin:1.10

my code:

func main() {
	m := gomail.NewMessage()
	m.SetHeader("From", "XX@XX.com")
	m.SetHeader("To", "XX@XX.com")
	m.SetAddressHeader("Cc", "XX@XX.com", "Dan")
	m.SetHeader("Subject", "Hello!")
	m.SetBody("text/html", "Hello <b>Bob</b> and <i>Cora</i>!")
	m.Attach("/Users/XX/Workspaces/Goland/New_Test_Pro/file1.txt")

	d := gomail.NewDialer("smtp.XX.com", 80, "XX@XX.com", "XXX")
	d.TLSConfig = &tls.Config{InsecureSkipVerify: true}
	if err := d.DialAndSend(m); err != nil {
		fmt.Println(err)
		panic(err)
	}
}

Thanks.

**Comment by ALTree** [comment] 2018-03-20 10:22
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2018-03-20 10:22 UTC

**Comment by alsmn** [comment] 2018-03-20 11:18
thanks
