### ISSUE TITLE
cmd/go: go clean -testcache fails if GOCACHE directory does not exist

### ISSUE THREAD

**Issue by mxk** [golang/go#29100] opened 2018-12-04 20:09 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes. It may be affected by #26794 for 1.12, but looking at the code, I think the bug is still there.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/Users/mxk/bin"
GOCACHE="/Users/mxk/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mxk/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xg/rnkm_hgs5298dsx212f1_y2c0000gp/T/go-build752263492=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```bash
cachedir=$(go env GOCACHE)
mv $cachedir $cachedir.old
go clean -testcache
mv $cachedir.old $cachedir
```

### What did you expect to see?

No errors and an exit code of 0.

### What did you see instead?

```
go clean -testcache: open /Users/mxk/Library/Caches/go-build/testexpire.txt: no such file or directory
exit code 1
```

The `-testcache` flag assumes that the cache directory exists. When that's not the case, there is nothing to clear, so the command should exit normally.

**Comment by bcmills** [comment] 2019-05-29 21:46
I believe this was fixed by #28680. Please reopen if you can still reproduce it at head.

```
example.com$ gotip env GOCACHE
/tmp/tmp.pCKjol3k6h

example.com$ rm -r $(gotip env GOCACHE)

example.com$ gotip clean -testcache
```

**Comment by MatthiasScholz** [comment] 2019-12-08 20:29
The issue does not seem to be fixed.

Running version:
- go version go1.13.5 linux/amd64

Gives the following error message:
```
go clean -testcache
go clean -testcache: open /.../.cache/go-build/testexpire.txt: no such file or directory
```

**Comment by ianlancetaylor** [comment] 2019-12-08 23:36
Yes, I can recreate this if I rename the entire cache directory as the first comment suggests.

**Comment by jespino** [comment] 2019-12-19 08:54
I can work on this.

I would like to confirm something. Is it, no fail and no warning, the expected behavior? Is it a correct assumption that is there is no `testexpire.txt` file, the test cache is already clean? Do we care about somebody accidentally removing the `.cache/go-build/testexpire.txt` file, but not the rest of the testcache?

**Comment by bcmills** [comment] 2019-12-19 14:35
@jespino, I think the error comes from here:
https://github.com/golang/go/blob/6145a80608087b309251b4edf1a612739331bdee/src/cmd/go/internal/clean/clean.go#L164

`lockedfile.Edit` creates the file if it does not already exist, so presumably the problem is that the _parent directory_ of the file does not yet exist. If the cache directory does not exist at all, then it is necessarily already clean.

(Actually, that makes the fix pretty trivial — simpler to mail a fix than to explain it here.)

**Closed** 2019-12-19 17:23 UTC
Labels: GoCommand, NeedsFix
