### ISSUE TITLE
doc/tutorial/call-module-code: recap the directory structure from the previous step?

### ISSUE THREAD

**Issue by bcetienne** [golang/go#41573] opened 2020-09-23 11:01 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.15.2 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/etienne/Library/Caches/go-build"
GOENV="/Users/etienne/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/etienne/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/etienne/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/etienne/Desktop/greetings/hello/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sb/6q_vnpy53xn95mr4kj7h9lvc0000gq/T/go-build921607341=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
I followed the guidelines for learning Go on the official website.
I first did this part which is not a problem (https://golang.org/doc/tutorial/create-module) but in the second part (https://golang.org/doc/tutorial/call-module-code), the `build` command from the _hello_ directory doesn't work.

I tried again just copying and pasting the provided code but nothing changes.

Here is my `go.mod` file in the _hello_ directory.
```
module hello

go 1.15

replace example.com/greetings => ../greetings
```

Here is my structure

![image](https://user-images.githubusercontent.com/20123945/94004312-c892a280-fd9c-11ea-9832-a32dc276d250.png)

### What did you expect to see?
<pre>

$ go build
go: found example.com/greetings in example.com/greetings v0.0.0-00010101000000-000000000000

</pre>

### What did you see instead?
<pre>

$ go build
hello.go:6:2: example.com/greetings@v0.0.0-00010101000000-000000000000: replacement directory ../greetings does not exist

</pre>

**Comment by seankhliao** [comment] 2020-09-23 12:20
going up from hello `../` you're in the greetings directory, then you try to go down a level into a directory that does not exist `greetings`

see https://github.com/golang/go/wiki/Questions for the appropriate places to ask questions

**Comment by bcmills** [comment] 2020-09-23 17:38
The `go` command is working as designed here, but that tutorial is fairly new — perhaps it could be adjusted to make this sort of mistake less likely.

(CC @stevetraut)

**Comment by stevetraut** [comment] 2020-09-23 17:44
Thanks, folks. I'll take a look.

**Comment by stevetraut** [comment] 2020-09-23 17:52
Hm. Step one in https://golang.org/doc/tutorial/call-module-code has the following, which is intended to cd up from where you were in the preceding topic (`greetings`) and create a `hello` directory at the same level as `greetings`. Maybe that first step needs to reestablish context from the preceding topic.

```
cd ..
mkdir hello
cd hello
```

**Comment by bcetienne** [comment] 2020-09-23 18:05
Hi everyone, thank you for taking the time to read my concern. 
For more precision, I really followed the tutorial step by step and I executed the `build` command from the _greetings/hello_ directory (the return I put in my original message), seeing that it didn't work I also tried (out of curiosity) from the root folder but as I imagined it didn't work any more.

I don't know if this helps you any more...

**Comment by SaltyCoco** [comment] 2021-02-15 04:37
This is an old issue however I had the same issue so here is what I found to be the answer.

You need to make a parent directory for both greetings and hello, like so;

![image](https://user-images.githubusercontent.com/31451104/107905689-836a3b00-6f0c-11eb-91c6-7cf45a188120.png)

I made a GreetingsProject folder and then had a hello folder and a greetings folder.  The "require" from the mod file in the file was auto generated by the command.  If you look at the replace you can see they are going up one directory to find a folder named greetings.

**Comment by stevetraut** [comment] 2021-02-16 13:31
So, to clarify, this statement from https://golang.org/doc/tutorial/call-module-code doesn't make it clear that you might be in the `greetings` folder?

"For example, **if your current directory in the command prompt is the greetings directory**, you could use the following commands:"

Could you suggest wording that might make it clear?

**Comment by hjctop1** [comment] 2021-02-18 07:17
@stevetraut 
hi, for go 1.16, i tried "https://golang.google.cn/doc/tutorial/call-module-code", got  same error
under hello dir, use "go mod tidy", then "go build"
this works for me, hope it works for you

**Comment by stevetraut** [comment] 2021-03-04 16:27
@hjctop1 @bcetienne See if the changes in this CL address your issues. They're due to be published before too long.

https://go-review.googlesource.com/c/website/+/297531/7/_content/doc/tutorial/call-module-code.html

**Comment by Nyamador** [comment] 2021-03-05 14:43
I'm using go 1.16 on linux . Running `go get example.com/greetings` with the replace directive (`example.com/greetings => ../greetings`) added in my go.mod file automatically added the require directive ( `require example.com/greetings v0.0.0-00010101000000-000000000000
`). I hope this helps 😄

**Comment by stevetraut** [comment] 2021-03-09 16:56
Fixed with a diagram here: https://golang.org/doc/tutorial/call-module-code

**Closed by stevetraut** 2021-03-09 16:56 UTC
Labels: Documentation, NeedsInvestigation
