### ISSUE TITLE
x/pkgsite:

### ISSUE THREAD

**Issue by aathan** [golang/go#54077] opened 2022-07-26 22:35 UTC
### What is the URL of the page with the issue?
 
 https://pkg.go.dev/contex
 
### What is your user agent?
 
Chrome
 
### Screenshot
 
<img width="963" alt="Screen Shot 2022-07-26 at 3 33 39 PM" src="https://user-images.githubusercontent.com/24279435/181123854-c16809b1-cfef-4a84-8ab5-201d8b030e0e.png"> 
 
 
### What did you do?
 Look for functions defined in context package
 
 
### What did you expect to see?
 functions like Background() and WithValue() listed along with the other functions
 
 
### What did you see instead?
functions like Background() and WithValue() listed under Types.

**Comment by seankhliao** [comment] 2022-07-26 22:50
Duplicate of #40223

**Closed by seankhliao** 2022-07-26 22:50 UTC
Labels: pkgsite
