### ISSUE TITLE
module metadata not included in test builds

### ISSUE THREAD

**Issue by frioux** [golang/go#37363] opened 2020-02-21 18:04 UTC
# What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.4
</pre>

### Does this issue reproduce with the latest release?

Yes (also tried with 1.14rc1)

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/frew/.cache/go-build"
GOENV="/home/frew/.config/go/env"
GOEXE=""
GOFLAGS="-mod=readonly"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/frew/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org"
GOROOT="/home/frew/sdk/go1.13.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/frew/sdk/go1.13.4/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/frew/code/zr0/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?

(you can check out `github.com/frioux/leatherman`, but really any test with a go.mod will work)

```
$ go test -o email.test ./internal/tool/email
ok      github.com/frioux/leatherman/internal/tool/email        0.003s
$ go version -m email.test

```

### What did you expect to see?

Something like:
```
email.test: go1.13.4
        path    github.com/frioux/leatherman
        mod     github.com/frioux/leatherman    v0.0.0-20200201061843-35acac218887      h1:D+FWNjx4onyAC5UOg0ZBEXZHOPRPihISt9ZiiwYcrrk=
        dep     github.com/BurntSushi/toml      v0.3.1  h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
        dep     github.com/PuerkitoBio/goquery  v1.5.0  h1:uGvmFXOA73IKluu/F84Xd1tt/z07GYm8X49XKHP7EJk=
        dep     github.com/andybalholm/cascadia v1.0.0  h1:hOCXnnZ5A+3eVDX8pvgl4kofXv2ELss0bKcqRySc45o=
        dep     github.com/frioux/yaml  v0.0.0-20191009230429-1d79e1a4120f      h1:vPrzBLZB9NBFMoydArwYLJMLJjv9YBwjORlyyVp+n2o=
        dep     github.com/fsnotify/fsnotify    v1.4.7  h1:IXs+QLmnXW2CcXuY+8Mzv/fWEsPGWxqefPtCP5CnV9I=
        dep     github.com/headzoo/surf v1.0.0  h1:d2h9ftKeQYj7tKqAjQtAA0lJVkO8cTxvzdXLynmNnHM=
        dep     github.com/icza/backscanner     v0.0.0-20180226082541-a77511ef4f0f      h1:EEBVjzvzsiUwgWio/3WB2kYx7DtC3QVJKuK6XejFghE=
        dep     github.com/mmcdole/gofeed       v1.0.0-beta2    h1:CjQ0ADhAwNSb08zknAkGOEYqr8zfZKfrzgk9BxpWP2E=
        dep     github.com/mmcdole/goxpp        v0.0.0-20181012175147-0068e33feabf      h1:sWGE2v+hO0Nd4yFU/S/mDBM5plIU8v/Qhfz41hkDIAI=
        dep     github.com/pierrec/lz4/v3       v3.2.1  h1:Tu06cJmyW3zvVIt4MSuxNpJnNSHBnwGkPXFyb3PVoYM=
        dep     golang.org/x/net        v0.0.0-20190827160401-ba9fcec4b297      h1:k7pJ2yAPLPgbskkFdhRCsA77k2fySZ1zf2zCjvQCiIM=
        dep     golang.org/x/sync       v0.0.0-20180314180146-1d60e4601c6f      h1:wMNYb4v58l5UBM7MYRLPG6ZhfOqbKu7X5eyFl8ZhKvA=
        dep     golang.org/x/sys        v0.0.0-20190904005037-43c01164e931      h1:+WYfosiOJzB4BjsISl1Rv4ZLUy+VYcF+u+0Y9jcerv8=
        dep     golang.org/x/text       v0.3.2  h1:tW2bmiBqwgJj/UpqtC8EpXEZVYOwU0yG4iWbprSVAcs=
```

### What did you see instead?

```
email.test: go1.13.4
```

I'm trying to debug why I'm hitting init issues in one test but not another, and thought the metadata would help me track down what's being built in.  I can probably use `-x` or something instead but this seems like a reasonable thing to support?

**Comment by bcmills** [comment] 2020-02-21 18:23
Duplicate of #33976

**Closed by bcmills** 2020-02-21 18:23 UTC
