### ISSUE TITLE
Fail to load package to pkg.go.dev after renaming repo

### ISSUE THREAD

**Issue by tchiunam** [golang/go#53411] opened 2022-06-16 17:01 UTC
### What is the URL of the page with the issue?
1. https://pkg.go.dev/github.com/tchiunam/axolgo-gcp
2. https://proxy.golang.org/github.com/tchiunam/axolgo-gcp/@latest
 
### What is your user agent?
`[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)`
 
### Screenshot
1. https://pkg.go.dev/github.com/tchiunam/axolgo-gcp is showing
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/16234776/174125026-08483074-e102-41fe-8485-da01c8e9e17f.png">
2. https://proxy.golang.org/github.com/tchiunam/axolgo-gcp/@latest is showing
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/16234776/174125103-1d528310-705e-4811-a9e1-52871ffb2796.png">

### What did you do?
1. Visit https://pkg.go.dev/github.com/tchiunam/axolgo-gcp
2. Click the request button
3. It shows that '"github.com/tchiunam/axolgo-gcp" could not be found.'
4. Visit https://proxy.golang.org/github.com/tchiunam/axolgo-gcp/@latest
5. Realize that I named the repo wrongly
6. Rename my repo from `github.com/tchiunam/axolotl-gcp` to `github.com/tchiunam/axolgo-gcp`
7. Re-visit https://pkg.go.dev/github.com/tchiunam/axolgo-gcp and https://proxy.golang.org/github.com/tchiunam/axolgo-gcp/@latest
8. Get the above errors
 
### What did you expect to see?
Expect to be able to load my packages in https://pkg.go.dev/github.com/tchiunam/axolgo-gcp page like https://pkg.go.dev/github.com/tchiunam/axolgo-lib, https://pkg.go.dev/github.com/tchiunam/axolgo-aws and https://pkg.go.dev/github.com/tchiunam/axolgo-cli

### What did you see instead?
Error '"github.com/tchiunam/axolgo-gcp" could not be found' and:
```
not found: module github.com/tchiunam/axolgo-gcp: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/4b37bb922b4518106b200fdaeacfa8d2724c2bbc443cbc6b75784d9f399eba51: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.```

**Comment by seankhliao** [comment] 2022-06-16 17:15
It's there now
Duplicate of #38065

**Closed by seankhliao** 2022-06-16 17:15 UTC
