### ISSUE TITLE
cmd/link:  executable contains the full path of GOROOT (even with -ldflags -w)

### ISSUE THREAD

**Issue by typeless** [golang/go#12770] opened 2015-09-28 05:23 UTC
``` bash
$ uname -a
Darwin users-MacBook-Air.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
$ go version
go version devel +c468957 Sun Sep 27 01:04:59 2015 +0000 darwin/amd64

# The only thing the program does is fmt.Print("Hello\n")
$ cd hello
$ go build -ldflags -w
$ hexdump -C hello | grep -c `basename $HOME`
58

**Comment by adg** [comment] 2015-09-28 05:30
It's the `GOROOT` (the path to your Go install), which just happens to be in `$HOME` on your system.

**Comment by typeless** [comment] 2015-09-28 06:58
Looks like these path strings reside in  __TEXT __gopclntab
```bash
otool -sv __TEXT __gopclntab hello
```

**Comment by minux** [comment] 2015-09-28 15:25
Those are for the filenames used in stack backtrace.

**Comment by minux** [comment] 2015-09-28 15:28
gopclntab maps pc ranges to source code lines.

**Comment by rakyll** [comment] 2015-09-28 16:53
Duplicate of https://github.com/golang/go/issues/3467.

**Closed by rakyll** 2015-09-28 16:53 UTC
