### ISSUE TITLE
cmd/compile: GO19CONCURRENTCOMPILATION not working as expected

### ISSUE THREAD

**Issue by nilslice** [golang/go#21236] opened 2017-07-31 15:35 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.9rc1

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What did you do?
```bash
time GO19CONCURRENTCOMPILATION=1 go1.9rc1 build ./*.go
```
vs.

```bash
time GO19CONCURRENTCOMPILATION=0 go1.9rc1 build ./*.go"
```

If possible, provide a recipe for reproducing the error.

This was tested with [github.com/ponzu-cms/ponzu](https://github.com/ponzu-cms/ponzu) by running:
```bash
$ go get github.com/ponzu-cms/ponzu/...
$ ponzu new github.com/nilslice/go19test
$ cd $GOPATH/src/github.com/nilslice/go19test
$ time GO19CONCURRENTCOMPILATION=0 ponzu build --gocmd=go1.9rc1
# (equal to: time GO19CONCURRENTCOMPILATION=0 go1.9rc1 build cmd/ponzu/*.go)
# vs.
$ time GO19CONCURRENTCOMPILATION=1 ponzu build --gocmd=go1.9rc1
# vs.
$ time ponzu build # with go 1.8.3
```

A link on play.golang.org is best.

### What did you expect to see?
I expected to see the build time / CPU usage change more dramatically when toggling concurrent compilation with the `GO19CONCURRENTCOMPILATION` var set/unset.

### What did you see instead?
```bash
# go 1.9 with concurrent compilation
time GO19CONCURRENTCOMPILATION=1 go1.9rc1 build -o ponzu-server cmd/ponzu/*.go
GO19CONCURRENTCOMPILATION=1 go1.9rc1 build -o ponzu-server cmd/ponzu/*.go  8.62s user 0.43s system 249% cpu 3.628 total
# ---

# go 1.9 without concurrent comilation
time GO19CONCURRENTCOMPILATION=0 go1.9rc1 build -o ponzu-server cmd/ponzu/*.go
GO19CONCURRENTCOMPILATION=0 go1.9rc1 build -o ponzu-server cmd/ponzu/*.go  8.80s user 0.51s system 245% cpu 3.787 total
# ---

# go 1.8.3
time ponzu build # with go1.8.3 linux/amd64                                        
ponzu build  17.48s user 0.96s system 278% cpu 6.630 total
```

It appears that there is no difference with or without GO19CONCURRENTCOMPILATION feature, ~~and after looking through [`go/internal/work/build.go`](https://github.com/golang/go/blob/9e859d5e9c7c093937c79f87c4b3328383320843/src/cmd/go/internal/work/build.go), it seems that the `-C or -c` flag is not defined, which the surrounding code suggests it would influence the parallel build. In fact, running the `build` command with either of these flags explicitly set causes a failure: `flag provided but not defined: -C` or `flag provided but not defined: -c`~~ (it's [here](https://github.com/golang/go/blob/f0cf740733b8cb53bc62e66f5e2a45385c06d726/src/cmd/compile/internal/gc/main.go#L191)... )

I may have this all wrong, and I couldn't create a more concurrent-happy build (so it may just be that parallel compilation doesn't help me much), but I thought I'd still report what I dug up!

**Comment by randall77** [comment] 2017-07-31 15:38
@josharian

**Comment by nilslice** [comment] 2017-07-31 15:51
I just realized the `-c` flag is nested in `-gcflags` , which my initial tests did not reflect.. here are the same ones under go1.9, still showing little or no difference among them.

```bash
time GO19CONCURRENTCOMPILATION=0 go1.9rc1 build -gcflags=-c=1 -o ponzu-server cmd/ponzu/*.go
GO19CONCURRENTCOMPILATION=0 go1.9rc1 build -gcflags=-c=1 -o ponzu-server   1.50s user 0.16s system 132% cpu 1.259 total

# ---

time GO19CONCURRENTCOMPILATION=1 go1.9rc1 build -gcflags=-c=1 -o ponzu-server cmd/ponzu/*.go
GO19CONCURRENTCOMPILATION=1 go1.9rc1 build -gcflags=-c=1 -o ponzu-server   1.48s user 0.19s system 132% cpu 1.255 total

# ---

time GO19CONCURRENTCOMPILATION=1 go1.9rc1 build -gcflags=-c=2 -o ponzu-server cmd/ponzu/*.go
GO19CONCURRENTCOMPILATION=1 go1.9rc1 build -gcflags=-c=2 -o ponzu-server   1.74s user 0.14s system 139% cpu 1.346 total

# ---

time GO19CONCURRENTCOMPILATION=1 go1.9rc1 build -gcflags=-c=4 -o ponzu-server cmd/ponzu/*.go
GO19CONCURRENTCOMPILATION=1 go1.9rc1 build -gcflags=-c=4 -o ponzu-server   1.71s user 0.19s system 113% cpu 1.680 total
```

**Comment by ianlancetaylor** [comment] 2017-07-31 23:27
Assigning to @josharian .  We can still get doc changes into 1.9 if appropriate.

**Comment by josharian** [comment] 2017-08-01 14:46
Thanks for the report.

I took a look at package `github.com/ponzu-cms/ponzu/cmd/ponzu`. Concurrent compilation is working as anticipated, and seems to have an impact in the 30-35% range. However, build time for this package is dominated the by linker, you so can't really tell. Try running:

```
$ cd $GOPATH/src/github.com/ponzu-cms/ponzu/cmd/ponzu
$ GO19CONCURRENTCOMPILATION=0 time go build -toolexec='time' -x
$ GO19CONCURRENTCOMPILATION=1 time go build -toolexec='time' -x
```

This will tell you the individual toolchain commands being run and time them individually, and then print an overall total. On my machine, I see concurrent compilation taking ~0.09s and non-concurrent compilation taking ~0.14s. Linking takes about 0.65s. There's another 0.25s spend in the `go` command itself and related overhead, like making directories and moving files around, for a total of ~1s. So the 0.05s (35%) that concurrent compilation buys here ends up being only 5% in the context of the complete build, in this particular case.

As for the place where "nBackendWorkers is set to 1", that's addressed in [change 41503](https://go-review.googlesource.com/c/41503/), which was intentionally held for 1.10. But it's not obvious to me that that is an important factor in this case. If you want to experiment, or if that change makes your life much better now, feel free to cherry-pick that change and rebuild the toolchain.

So I think everything is working as intended here. I don't see any obvious doc changes to make, although I'm open to suggestions.

For now, I'm going to close this, but will re-open if there's new information or suggestions.

**Closed by josharian** 2017-08-01 14:46 UTC

**Comment by nilslice** [comment] 2017-08-01 15:23
> -toolexec='time'

That's cool. Wasn't aware of this -- thanks for pointing it out. 

> As for the place where "nBackendWorkers is set to 1", that's addressed in change 41503, which was intentionally held for 1.10. But it's not obvious to me that that is an important factor in this case. If you want to experiment, or if that change makes your life much better now, feel free to cherry-pick that change and rebuild the toolchain.

I see -- thank you for pointing this out as well. I couldn't tell how much of each package could be compiled before the `nBackendWorkers` was reduced there, or if it was done prior to any compilation in some cases.

This was reported entirely out of experimentation, and I hope it didn't cause you many wasted cycles :grimacing: .. figured I would share what I was seeing before 1.9 hits master. The concurrent compilation is a great feature - thank you for your work on it!! If I have any doc suggestions pre 1.10, I will report back here.

**Comment by josharian** [comment] 2017-08-01 15:33
> I couldn't tell how much of each package could be compiled before the nBackendWorkers was reduced there

FWIW, this makes a noticeable difference in (generally autogenerated) packages that define thousands of types.

> figured I would share what I was seeing before 1.9 hits master.

Appreciated! Very glad you're kicking the tires.
