### ISSUE TITLE
all.bash: leaves $GOROOT/nonexistentpath behind

### ISSUE THREAD

**Issue by mikioh** [golang/go#30338] opened 2019-02-21 05:21 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +889aa5eb98
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

It happens on most of the supported platforms.
```
GOMOD=""
```

### What did you do?

Run all.bash at $GOROOT/src

### What did you expect to see?

The command "git status" reports "no untracked files"

### What did you see instead?

The command "git status" reports there's one untracked file:  $GOROOT/nonexistentpath

Fortunately, this doesn't happen with Go 1.12. Looks like the path comes from $GOPATH in run.bash.

**Comment by mvdan** [comment] 2019-02-21 08:54
Looks like the GOPATH line in run.bash has been there since 2a0d7e24aad70e01a5a301b7e5248fc9adfb0e26 in early 2017, so I'm not sure what could be causing this.

I think #30316 would have detected this. /cc @bcmills @bradfitz @dmitshur

**Comment by ianlancetaylor** [comment] 2019-02-22 00:15
I saw it a couple of times but I don't see it any more.

When I did it there was a single file there `nonexistentpath/pkg/mod/cache/lock`.

**Comment by mikioh** [comment] 2019-02-22 02:15
Sorry, I didn't mention important information: I didn't set GO111MODULE on both go1.12 and tip, that means GOMOD="", so cmd/go behaves as it wants.

**Comment by bcmills** [comment] 2019-02-22 13:40
I'm not sure what the cause of this is, but at least one of the changes in the stack for #30228 should fix it.

I'll revisit once that is resolved.

**Comment by dmitshur** [comment] 2019-02-22 18:24
Somewhat related issue: #30221.

**Comment by bcmills** [comment] 2019-03-14 18:23
This should be fixed now. Please reopen if you see it again.

**Closed by bcmills** 2019-03-14 18:23 UTC
Labels: NeedsInvestigation
