### ISSUE TITLE
cmd/compile: internal compiler error: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bytemare** [golang/go#54326] opened 2022-08-07 12:28 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?
Not sure that's relevant, as the bug occurs on different platforms, environments, and even CI.

### What did you do?

<pre>
$ go test
</pre>

### What did you expect to see?

Normal execution of the test.
<pre>
PASS
ok      test     0.003s
</pre>

### What did you see instead?
<pre>
# go-19-panic [go-19-panic.test]
<autogenerated>:1: internal compiler error: panic: runtime error: invalid memory address or nil pointer dereference

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
FAIL    go-19-panic [build failed]
</pre>

### More

I extracted code that reproduces this behavior here: https://github.com/bytemare/go-19-panic . It needs a test file to panic, so it does not reproduce on the playground: https://go.dev/play/p/WlCb-l0gd82

It used to work on Go 1.18. The repo I linked to runs [`go test` on 1.19 and 1.18](https://github.com/bytemare/go-19-panic/runs/7712637874?check_suite_focus=true), where it panics reliably on 1.19 but not 1.18.

**Comment by hopehook** [comment] 2022-08-07 12:58
I found that the test case can be passed by `go test -gcflags='-l'` test. (maybe the problem is caused by optimization of inlining)

**Comment by cuiweixie** [comment] 2022-08-07 13:55
➜  go-19-panic git:(main) go test -v
=== RUN   TestPoint_Decode
--- PASS: TestPoint_Decode (0.00s)
PASS
ok      go-19-panic     0.118s
➜  go-19-panic git:(main) go version
go version devel go1.20-0c4db1e347 Sat Aug 6 15:20:00 2022 +0000 darwin/arm64
master is ok now!

**Comment by cuonglm** [comment] 2022-08-17 17:01
Duplicated of https://github.com/golang/go/issues/53982, the fix was merged to master, and backported to go1.19

**Closed by cuonglm** 2022-08-17 17:01 UTC
Labels: NeedsInvestigation
