### ISSUE TITLE
proposal: Go 2: 

### ISSUE THREAD

**Issue by dmitryuck** [golang/go#54686] opened 2022-08-26 05:22 UTC
### Author background

- **Would you consider yourself a novice, intermediate, or experienced Go programmer?**
- I'm a novice
- **What other languages do you have experience with?**
- Js

### Related proposals

- **Has this idea, or one like it, been proposed before?**
- Not sure
  - **If so, how does this proposal differ?**
- **Does this affect error handling?**
- Yes
  - **If so, how does this differ from previous error handling proposals?**
- **Is this about generics?**
- No
  - **If so, how does this relate to the accepted design and other generics proposals?**

### Proposal

- **What is the proposed change?**
- Add a new way of error handling
- **Who does this proposal help, and why?**
- This adds a new convenient way of handling errors
- **Please describe as precisely as possible the change to the language.**
the error handles after the function call, block executes when error != nil

```
func MyFunc(arg1, arg2 any) error {
  // Function body

  return errors.New("Some error info")
}

in a place where we call this function

err := MyFunc(arg1, arg2) {
  // An error handling goes here
  Log(err)
}
```

similar to function with return value
```
  func MyFunc(arg1, arg2 any) any error {
    // Function body

    return nil errors.New("Some error info")
  }

  in a place where we call this function

  result, err := MyFunc(arg1, arg2) {
    // An error handling goes here
    Log(err)
  }
```

- **What would change in the language spec?**
- Adding a specific error handling mechanism: A curly braces after a function call
- **Please also describe the change informally, as in a class teaching Go.**
- Add a mechanism to handle any error in function like callback after a function call
- **Is this change backward compatible?**
- yes, compatible with G1
  - Breaking the Go 1 compatibility guarantee is a large cost and requires a large benefit.
    Show example code before and after the change.
  - **Before**
  - **After**
- **Orthogonality: how does this change interact or overlap with existing features?**
- No conflicts with existing code
- **Is the goal of this change a performance improvement?**
- No, more about convenience and elegance
  - **If so, what quantifiable improvement should we expect?**
  - **How would we measure it?**

### Costs

- **Would this change make Go easier or harder to learn, and why?**
- No effect
- **What is the cost of this proposal? (Every language change has a cost).**
- Don't know
- **How many tools (such as vet, gopls, gofmt, goimports, etc.) would be affected?**
- None
- **What is the compile time cost?**
- --
- **What is the run time cost?**
-  ---
- **Can you describe a possible implementation?**
- ----
- **Do you have a prototype? (This is not required.)**
- ----

**Comment by seankhliao** [comment] 2022-08-26 14:28
Duplicate of #41908

**Closed by seankhliao** 2022-08-26 14:28 UTC
Labels: Proposal
