### ISSUE TITLE
cmd/go: `go doc -all` does not print bugs

### ISSUE THREAD

**Issue by fluhus** [golang/go#60400] opened 2023-05-24 11:36 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/[redacted]/.cache/go-build"
GOENV="/home/[redacted]/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/[redacted]/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/[redacted]"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/[redacted]/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/[redacted]/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/[redacted]/src/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build857065236=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Source file:

`./hello/hello.go`

```go
// Example package.
package hello

// BUG(me): Example bug.
```

Run:

```
$ go doc ./hello
```

Output:

```
package hello // import "github.com/fluhus/[redacted]"

Example package.


BUG: Example bug.
```

Now with `-all`:

```
$ go doc -all ./hello
```

Output:

```
package hello // import "github.com/fluhus/[redacted]"

Example package.
```

### What did you expect to see?

I expected the bugs to stay when using `-all`. To me the flag implies "more information", so I didn't expect data to be omitted.

If this is working as intended, it would be helpful to mention what information gets omitted when using `-all` in the output of `go help doc`.

Thanks!

**Comment by seankhliao** [comment] 2023-05-24 11:47
Duplicate of #33970

**Closed by seankhliao** 2023-05-24 11:47 UTC
