### ISSUE TITLE
Load failed The specified module could not be found.

### ISSUE THREAD

**Issue by snyiu100** [golang/go#28551] opened 2018-11-02 10:17 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11 windows/386
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOARCH=386
set GOBIN=C:\go\bin
set GOCACHE=C:\Users\thinker\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\thinker\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set GCCGO=gccgo
set GO386=sse2
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessag
e-length=0 -fdebug-prefix-map=C:\Users\thinker\AppData\Local\Temp\go-build649790
602=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

Load failed The specified module could not be found.

**Comment by ianlancetaylor** [comment] 2018-11-02 12:52
What exactly did you do?  What exactly did you see?  What did you expect to happen instead?

**Comment by snyiu100** [comment] 2018-11-05 02:37
what I did just like this:
        h, err := syscall.LoadLibrary("add.dll")
	if err != nil {
		fmt.Println("Load failed", err.Error())
	}
	defer syscall.FreeLibrary(h)
	proc, err := syscall.GetProcAddress(h, "add")
"add.dll" is impl In c/c++ by myself.But When I run this project (beego project) it happended "Load failed The specified module could not be found."

**Comment by agnivade** [comment] 2018-11-05 04:00
Can you please provide us with a complete working code along with the required dll files so that we can reproduce this from our side ? Thank you.

**Comment by agnivade** [comment] 2018-11-05 09:33
Looks like this is resolved. Please close the issue if that is so.

**Closed** 2018-11-06 02:30 UTC
Labels: WaitingForInfo

**Comment by kolterr** [comment] 2019-09-12 03:22
> Thanks.
> finally, I found the reason, because of runtime library, some system librarys are missing; it is better to see which libraries are missing by errors.

Hi，I also encountered the same problem；Go version 1.13 windows/amd64;And what  system librarys should i need ? i'm looking forward to your reply,thx
