### ISSUE TITLE
getting error string instead of panic

### ISSUE THREAD

**Issue by gaplyk** [golang/go#32847] opened 2019-06-28 18:20 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12.5
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
i don't know environment behind playground.

### What did you do?
https://play.golang.org/p/jRplZeblynF

### What did you expect to see?
I expect to see panic as panic not as an error

### What did you see instead?
string error

**Comment by bcmills** [comment] 2019-06-28 18:59
Duplicate of #28150

**Closed by bcmills** 2019-06-28 18:59 UTC
