### ISSUE TITLE
A goroutine problem?

### ISSUE THREAD

**Issue by karta0807913** [golang/go#32513] opened 2019-06-10 05:05 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +323212b9e6 Sun Jun 9 16:23:11 2019 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build638392320=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I write code like this 
```
package main

import (
    "fmt"
    "time"
)

func say1() {
    fmt.Println("HI")
}

func main() {
    go say1()
    say1()
}
```

### What did you expect to see?
```
HI
HI
```

### What did you see instead?
```
HI
```

**Comment by jemygraw** [comment] 2019-06-10 05:42
It's not the problem of go routine. It's your understanding of the go routine. Try add a pause before the main routine exits to give the chance for your `go say1()` routine to be scheduled by CPU.

```
package main

import (
	"fmt"
	"time"
)

func say1() {
	fmt.Println("HI")
}

func main() {
	go say1()
	say1()
	<-time.After(time.Second)
}

```

**Comment by ALTree** [comment] 2019-06-10 06:41
As @jemygraw said, the issue is that the main goroutine won't wait for any other executing goroutine. When main is done, the program ends; even if there are other gourourines that are not done. 

Closing this issue, this this is WAI.

**Closed by ALTree** 2019-06-10 06:41 UTC
