### ISSUE TITLE
x/tools: fix mixed style of indentation in javascript files

### ISSUE THREAD

**Issue by ysmolsky** [golang/go#24933] opened 2018-04-18 18:05 UTC
While working in x/tool/... and x/playground with JS I have encountered mix of indentation, 2/4 spaces and tabs. It’s confusing to edit such files.  For example in emacs I have to constantly fight it by switching indent-mode.

I would like to fix this by agreeing to use tabs only (following go style) and fix all files to the unified format.

I am very eager to do this.

@andybons @bradfitz

**Comment by bradfitz** [comment] 2018-04-18 18:10
I have no opinions here.

**Comment by ysmolsky** [comment] 2018-04-18 18:17
cc @broady @campoy

**Comment by andybons** [comment] 2018-04-18 18:34
Duplicate of #21719

**Closed by andybons** 2018-04-18 18:34 UTC

**Comment by andybons** [comment] 2018-04-18 18:57
While I twitch when I see inconsistent formatting in a bunch of the JS/CSS/etc., reformatting everything without any logic changes is churn that negates the usefulness of git blame.

For _new_ files, I'm on board with using a standardized formatter so that we just don't need to worry about it (though honestly I wish we didn't have to install npm in order to get it).

That's what #21719 is about, but I'm not onboard with just fixing formatting for formatting's sake.

Unless I'm ignorant of some feature in git that allows you to avoid the scenario I describe above.

**Comment by ysmolsky** [comment] 2018-04-18 19:40
I see. I have completely forgot about git history. From that point of view it all makes sense. Thank you.

**Comment by carlmjohnson** [comment] 2018-04-18 20:17
Preserving Git blame is not a good enough reason to avoid standardizing formatting. Git blame inevitably gets confused by uninteresting changes like adding `,`. Breaking Git blame should be minimized but not outright avoided. When you're looking at Git blame, you always need to be prepared to dig deeper and go past the first superficial change to a line to find its real source deeper in history. A single formatting commit is easy enough to push past as long as one doesn't arbitrarily churn through formatting systems. Github now has a feature where you can hover next to a line to find prior changes, which makes it easy to daisy chain blame lookups to find the real source.

![screen shot 2018-04-18 at 4 17 07 pm](https://user-images.githubusercontent.com/222245/38955913-f9ab6ef0-4323-11e8-98b9-c7409edb59e0.png)
