### ISSUE TITLE
 how to assign task to specific thread?

### ISSUE THREAD

**Issue by HuanjunKong** [golang/go#19736] opened 2017-03-28 06:39 UTC
I have nearly implemented a face recognition Go server. My face recognition algorithm uses `caffe`, `caffe` is a thread-binding graphical library, that means I have to init and call algorithm in same thread, so I checked [LockOSThread()][1]. 

`LockOSThread` uses 1 thread, but my server owns 4 GPU.

In `C/C++`, I could create 4 threads, initialize algorithm in each thread, use `sem_wait` and `sem_post` to assign task, 1 thread use 1 GPU.

How to do the same thing in `Go`, how to tell my code this one uses thread0 and that one uses thread1 ?

  [1]: https://github.com/golang/go/wiki/LockOSThread

**Comment by ALTree** [comment] 2017-03-28 06:55
Hi,

the Go project does not use its bug tracker for general discussion or asking questions. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. 

Closing, since this is not a bug report.

**Closed by ALTree** 2017-03-28 06:55 UTC
