### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by seanthorpe** [golang/go#46168] opened 2021-05-14 13:56 UTC
### What version of Go are you using (`go version`)?
The LATEST

### Does this issue reproduce with the latest release?
Yes.  You made it the header of your website.

### What operating system and processor architecture are you using (`go env`)?
N/A

### What did you expect to see?
I visited https://golang.org expecting to find a Programming Language REFERENCE...

### What did you see instead?
I see a website header dealing with the political FEELINGS of a minority group within your organization.
"Black Lives Matter. Support the Equal Justice Initiative."

I expected to see a PROFESSIONAL Programming Language REFERENCE.
Not a POLITICAL PROPAGANDA statement that applies to the USA specifically and certainly NOT to a LARGE PORTION of the world.

Just because your company has a website, DOES NOT mean it should be used for POLITICAL PROPAGANDA.

**Comment by seankhliao** [comment] 2021-05-14 14:26
Duplicate of ##39850

**Closed by seankhliao** 2021-05-14 14:26 UTC
