### ISSUE TITLE
cmd/go: go mod vendor in empty new project produces confusing error message in 1.14

### ISSUE THREAD

**Issue by cocorambo** [golang/go#37464] opened 2020-02-26 10:28 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.14 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nmartin/.cache/go-build"
GOENV="/home/nmartin/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/nmartin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build614761053=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

<pre>
mkdir -p /tmp/go-vendor
cd /tmp/go-vendor
go mod init github.com/cocorambo/govendor
go get github.com/sirupsen/logrus
go mod vendor
</pre>

### What did you expect to see?

I expect go command to create vendor directory and modules.txt file

### What did you see instead?

<pre>
go mod vendor: open /tmp/go-vendor/vendor/modules.txt: no such file or directory
</pre>

**Comment by cocorambo** [comment] 2020-02-26 10:46
It finally works, I was missing to at least import module in a Go file

For example create a `main.go` with this content and it works
<pre>
package main

import (
	_ "github.com/sirupsen/logrus"
)
</pre>

So this is clearly not a bug but error message could be more appropriate I think

By running `go mod vendor` with no require in `go.mod` file, we get this message:
<pre>
go: no dependencies to vendor
</pre>

**Comment by bcmills** [comment] 2020-02-26 13:54
Duplicate of #36580

**Closed by bcmills** 2020-02-26 13:54 UTC
Labels: GoCommand, NeedsInvestigation, modules
