### ISSUE TITLE
x/pkgsite: symbol search does not return a publicly available symbol in results

### ISSUE THREAD

**Issue by ahmetb** [golang/go#49486] opened 2021-11-09 19:34 UTC
### What is your user agent?

Chrome for macOS.
 
### Screenshot
 
> 
![image](https://user-images.githubusercontent.com/159209/140992332-8c7cd154-7806-4c2a-a338-17cc2f213083.png)

### What did you do?
 
Symbol search for `OrderByT` keyword
 
### What did you expect to see?
 
 https://pkg.go.dev/github.com/ahmetb/go-linq/v3#Query.OrderByT
 
### What did you see instead?

No results found.

**Comment by julieqiu** [comment] 2021-11-09 19:51
This looks like a duplicate of #47841. We currently do not support searching by field of method names, but https://pkg.go.dev/search?q=Query.OrderByT+go-linq&m=symbol would return that symbol.

**Closed by julieqiu** 2021-11-09 19:51 UTC
Labels: pkgsite
