### ISSUE TITLE
feature request: go doc JSON output format for package outline in editors

### ISSUE THREAD

**Issue by marcelbeumer** [golang/go#60291] opened 2023-05-18 21:24 UTC
It would be great if `go doc` could provide the structure of en entire package in JSON format so editors can implement a package outline easily, like GoLand does or Vscode using https://github.com/766b/vscode-go-outliner.

It's not too hard to build yourself, but would be great to see standard built-in in the go toolchain.

**Comment by seankhliao** [comment] 2023-05-18 21:26
Duplicate of #34293

**Closed by seankhliao** 2023-05-18 21:26 UTC
Labels: pkgsite
