### ISSUE TITLE
Semantic versioning constraint errors, with the "dep" package, on Darwin/ARM64

### ISSUE THREAD

**Issue by vmlemon** [golang/go#45878] opened 2021-04-30 08:40 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.16beta1 darwin/arm64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/tyson/Library/Caches/go-build"
GOENV="/Users/tyson/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/tyson/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tyson/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16beta1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zq/4fmgrgv16fq9d_9jygw8ky4r0000gn/T/go-build2949034140=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Attempted to build the "dep" package (a dependency, for another project), under MacOS 11.2.3, on an ARM64 machine, with the latest beta version of Go.

### What did you expect to see?
I would expect this package to build, although I have never tested this platform/Go version combination. (I previously used the x86-64 version of Go, under Rosetta 2).

### What did you see instead?
```
tyson@Tysons-Air ~ % go get github.com/golang/dep/cmd/dep
# github.com/golang/dep/gps
go/pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:103:21: cannot use sv (type *semver.Version) as type semver.Version in field value
go/pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:122:16: invalid type assertion: c.(semver.Version) (non-interface type *semver.Constraints on left)
go/pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:149:4: undefined: semver.Constraint
```

**Comment by mvdan** [comment] 2021-04-30 08:55
That seems like a regular build error in the dep project. Is there a reason you're still using it? It has been deprecated and abandoned for two years now.

**Comment by vmlemon** [comment] 2021-04-30 09:00
> That seems like a regular build error in the dep project. Is there a reason you're still using it? It has been deprecated and abandoned for two years now.

Thanks. I didn't realise that it was deprecated - I'm new to working with Go, and it was a prerequisite, that was dragged in, whilst trying to bootstrap building https://github.com/lf-edge/eve's build tools, on the new M1 Macs. Is there's a suggested replacement for it?

**Comment by ALTree** [comment] 2021-04-30 09:00
It's the module system, see the dep deprecation notice in its readme:

https://github.com/golang/dep

**Comment by ALTree** [comment] 2021-04-30 10:13
The module system? It's actually very widely used at this point: https://blog.golang.org/survey2020-results#TOC_8.

**Comment by vmlemon** [comment] 2021-04-30 10:15
> The module system? It's actually very widely used at this point: https://blog.golang.org/survey2020-results#TOC_8.

Sorry, was referring to "Dep". :)

**Comment by ALTree** [comment] 2021-04-30 10:16
Yes, it's not surprising, it has been deprecated for a few years at this point.

I'm closing this issue then, since this is not a bug in Go.

**Closed by ALTree** 2021-04-30 10:16 UTC
