### ISSUE TITLE
cmd/go: malformed module path "xxxx/xxxx/uuid" missing dot in first path element when migrating from GOPATH based dep to go mod

### ISSUE THREAD

**Issue by AyushG3112** [golang/go#35020] opened 2019-10-20 13:30 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.3
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/ayush/projects/gojects/bin"
GOCACHE="/home/ayush/.cache/go-build"
GOENV="/home/ayush/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ayush/projects/gojects"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build570102704=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I had a folder structure as follows:
```
GOPATH
+---src
     +--- my-api-server
           +--- my-auth-server
                 +--- main.go
           +--- my-utils
                 +--- uuid
                       +--- uuid.go
```

`my-auth-server` uses `my-api-server/my-utils/uuid` as a depenency

Now, when I used the GOPATH based module system, this worked fine. But when using go modules, when I run `go run main.go` in `my-auth-server` it returned error:

``` console
build command-line-arguments: cannot load my-api-server/my-utils/uuid: malformed module path "my-api-server/my-utils/uuid": missing dot in first path element
```

### What did you expect to see?
My project should have been started successfully

### What did you see instead?
```
build command-line-arguments: cannot load my-api-server/my-utils/uuid: malformed module path "my-api-server/my-utils/uuid": missing dot in first path element
```

**Comment by AyushG3112** [comment] 2019-10-20 14:06
Also, I tried moving `my-utils` inside `my-auth-server`, but as a library, `my-utils` will be used in multiple places.


Now, `my-utils` also has a `go.mod`, but that contains a `module` declaration.
If I place it in `my-auth-server`, the module path becomes `my-api-server/my-auth-server/my-utils`


If I have 2 servers,

- `my-auth-server`
- `my-session-server`

I cannot place my-utils inside both because there can only be one `module` declaration per `go.mod`.

Any help in solving this would also be appreciated.

**Comment by dmitshur** [comment] 2019-10-21 16:01
There is currently a requirement that the module path must have a dot in the first path element.

> Any help in solving this would also be appreciated.

The only change you have to make is add a dot to the first element of the module path. If you don't intend to make the module available on the internet, you can use a reserved TLD like `.localhost` that signifies that. For example, the following module path would work:

```
my-api-server.localhost/my-utils/uuid
```

You may also find the https://blog.golang.org/migrating-to-go-modules blog post helpful.

/cc @jayconrod @bcmills

**Comment by bcmills** [comment] 2019-10-21 16:11
> The only change you have to make is add a dot to the first element of the module path.

Or, as an alternative, if both components are in the same version-control repo, you can place a single `go.mod` file at `GOPATH/src/my-api-server/go.mod` instead of splitting up the repo into smaller modules.

Or, you can use a `replace` directive to retarget the locations of the modules and avoid a remote lookup.

Regardless, the best approach is to choose a domain name or prefix under your control for the import path, as @dmitshur suggests. (See #32819.)

**Comment by bcmills** [comment] 2019-10-21 16:11
Duplicate of #32819

**Closed by bcmills** 2019-10-21 16:11 UTC
Labels: GoCommand, WaitingForInfo, modules
