### ISSUE TITLE
cmd/compile: internal compiler error: conflicting package heights 4 and 3 for path "sync"

### ISSUE THREAD

**Issue by xaionaro** [golang/go#44337] opened 2021-02-17 17:22 UTC
If I run a command without option `-race`
```
go/pkg/tool/linux_amd64/compile -p main -pack -trimpath /data/users/xaionaro/fbsource/fbcode -nolocalimports -buildid= -o buck-out/dev/gen/privatecore/firmware/analyzer/cmd/firmware-analyzer/firmware-analyzer.race#compile,platform007-clang/firmware-analyzer.race.a -I /data/users/xaionaro/fbsource/fbcode/buck-out/dev/bin/privatecore/firmware/analyzer/cmd/firmware-analyzer/__firmware-analyzer.race#compile,platform007-clang,symlink-tree__tree -complete /data/users/xaionaro/fbsource/fbcode/buck-out/dev/gen/privatecore/firmware/analyzer/cmd/firmware-analyzer/firmware-analyzer.race-go-build-info/firmware-analyzer.race-go-build-info.go /data/users/xaionaro/fbsource/fbcode/privatecore/firmware/analyzer/cmd/firmware-analyzer/main.go
```
it works.

If I add option `-race` it fails:
```
go/pkg/tool/linux_amd64/compile -p main -pack -trimpath /data/users/xaionaro/fbsource/fbcode -nolocalimports -race -buildid= -o buck-out/dev/gen/privatecore/firmware/analyzer/cmd/firmware-analyzer/firmware-analyzer.race#compile,platform007-clang/firmware-analyzer.race.a -I /data/users/xaionaro/fbsource/fbcode/buck-out/dev/bin/privatecore/firmware/analyzer/cmd/firmware-analyzer/__firmware-analyzer.race#compile,platform007-clang,symlink-tree__tree -complete /data/users/xaionaro/fbsource/fbcode/buck-out/dev/gen/privatecore/firmware/analyzer/cmd/firmware-analyzer/firmware-analyzer.race-go-build-info/firmware-analyzer.race-go-build-info.go /data/users/xaionaro/fbsource/fbcode/privatecore/firmware/analyzer/cmd/firmware-analyzer/main.go
/data/users/xaionaro/fbsource/fbcode/privatecore/firmware/analyzer/cmd/firmware-analyzer/main.go:11:2: internal compiler error: conflicting package heights 4 and 3 for path "sync"

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
```

Unfortunately I cannot share `main.go`, since it is under NDA. And if I try to minimize `main.go` (remove all NDA-code) then it stops failing.

```
$ go version
go version go1.15.2 linux/amd64
```

```
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/xaionaro/.local/bin"
GOCACHE="/home/xaionaro/.cache/go-build"
GOENV="/home/xaionaro/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/data/users/xaionaro/gopaths/gobuck/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/data/users/xaionaro/gopaths/gobuck:/data/users/xaionaro/gopaths/godeps:/home/xaionaro/fbcode-gen-go:/data/users/xaionaro/gopaths/gofbcode"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/data/users/xaionaro/gopaths/goroot"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/data/users/xaionaro/gopaths/goroot/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build350343079=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by ianlancetaylor** [comment] 2021-02-17 20:12
CC @griesemer @randall77

**Comment by ianlancetaylor** [comment] 2021-02-17 20:13
Does this happen when using `go build`?  Or does it only happen when invoking cmd/compile directly?  If the latter, why are you doing that?

**Comment by griesemer** [comment] 2021-02-17 20:23
cc @mdempsky (who implemented the package height mechanism)

**Comment by xaionaro** [comment] 2021-02-17 20:24
> Does this happen when using `go build`? Or does it only happen when invoking cmd/compile directly? If the latter, why are you doing that?

Command:
```
go/bin/go build -race -o 'buck-out/dev/gen/privatecore/firmware/analyzer/cmd/firmware-analyzer/firmware-analyzer.race#compile,platform007-clang/firmware-analyzer.race.a' -gcflags '-I /data/users/xaionaro/fbsource/fbcode/third-party-buck/platform007/tools/go/src/ -p main -pack -trimpath /data/users/xaionaro/fbsource/fbcode -nolocalimports -buildid= -I /data/users/xaionaro/fbsource/fbcode/buck-out/dev/bin/privatecore/firmware/analyzer/cmd/firmware-analyzer/__firmware-analyzer.race#compile,platform007-clang,symlink-tree__tree -complete' /data/users/xaionaro/fbsource/fbcode/privatecore/firmware/analyzer/cmd/firmware-analyzer/main.go
```
works.
```
[xaionaro@devvm018.cln0 ~/fbcode] ls -ld 'buck-out/dev/gen/privatecore/firmware/analyzer/cmd/firmware-analyzer/firmware-analyzer.race#compile,platform007-clang/firmware-analyzer.race.a'
-rwxr-xr-x 1 xaionaro users 56831949 Feb 17 12:24 buck-out/dev/gen/privatecore/firmware/analyzer/cmd/firmware-analyzer/firmware-analyzer.race#compile,platform007-clang/firmware-analyzer.race.a
```

**Comment by mdempsky** [comment] 2021-02-17 20:30
You need to either compile all packages with `-race` or none of them. Mixing packages with different compilation modes like this isn't supported.

The recommended way to use the race detector is to use `go build -race` or `go install -race`. If you're going to try to use `-gcflags=-race`, then you need to at least use `-gcflags=all=-race`, but I think there may also be linker flags that need to be passed too.

**Comment by xaionaro** [comment] 2021-02-17 20:31
> The recommended way to use the race detector is to use `go build -race` or `go install -race`. If you're going to try to use `-gcflags=-race`, then you need to at least use `-gcflags=all=-race`, but I think there may also be linker flags that need to be passed too.

OK, this makes sense. Thank you for the clarification!

**Comment by mdempsky** [comment] 2021-02-17 20:33
No problem. I'm going to close the issue because I think this is working as intended.

**Comment by xaionaro** [comment] 2021-02-17 20:33
> No problem. I'm going to close the issue because I think this is working as intended.

The only nitpicking here is: the error message is obscure.

**Closed by mdempsky** 2021-02-17 20:33 UTC
Labels: NeedsInvestigation, WaitingForInfo
