### ISSUE TITLE
cmd/go: doc doesn't show exported fields acquired by embedding non-exported types.

### ISSUE THREAD

**Issue by go101** [golang/go#27581] opened 2018-09-09 13:46 UTC
### What version of Go are you using (`go version`)?

go version go1.11 linux/amd64

### Does this issue reproduce with the latest release?

yes

### What did you do?

```golang
package foo

type t struct {
	X int
}

type Config struct {
	t
	Y int
}
```

```
$ go doc foo.Config
```

### What did you expect to see?

The current output is not bad, but not perfect.
The reason is the field `Config.X` is also exported, but it is not mentioned in the printed doc.
Users of the `foo` package must read code to know that the field `Config.X` is usable.

### What did you see instead?

```
package foo // import "foo"

type Config struct {
	Y int
	// Has unexported fields.
}
```

**Comment by agnivade** [comment] 2018-09-09 17:29
Duplicate of https://github.com/golang/go/issues/6600.

**Closed by agnivade** 2018-09-09 17:29 UTC
