### ISSUE TITLE
cmd/compile: invalid recursive type

### ISSUE THREAD

**Issue by QuantumGhost** [golang/go#27267] opened 2018-08-27 07:37 UTC
### What version of Go are you using (`go version`)?
go version go1.11 darwin/amd64

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/02/nfvdwz45077g85khfsv07khm0000gn/T/go-build787448559=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### What did you do?

https://play.golang.org/p/SMcx3vUC83W
Compile this code with Go 1.11 and Go 1.10.3 respectively.

### What did you expect to see?
Code compiles without any error with both Go 1.11 and Go 1.10.3.

### What did you see instead?
Go 1.11 failed to compile this code with the following error:
On my machine:
```
❯ go build recur.go
# command-line-arguments
./recur.go:10:6: invalid recursive type Executor
./recur.go:16:29: cannot use callback (type func(*Executor) error) as type Executor in field value
./recur.go:21:19: cannot call non-function e.callback (type Executor)
```

Go 1.10.3 succeeded without any issue.

**Comment by agnivade** [comment] 2018-08-27 08:56
Likely a duplicate of https://github.com/golang/go/issues/27232.

/cc @josharian @mdempsky

**Comment by josharian** [comment] 2018-08-27 14:09
> Likely a duplicate of #27232.

Indeed.

This and #27232 are more in the domain of @mdempsky or @griesemer than me. (And I also don't have much time at the moment, and these seem like important fixes that could use a prompt backport.)

**Comment by FiloSottile** [comment] 2018-08-30 21:16
(If this turns out NOT to be a duplicate of #27232, please open a separate backport issue.)

**Comment by griesemer** [comment] 2018-09-05 20:31
Simpler reproducer, with irrelevant details stripped:
```Go
package p

type F = func(E) // compiles if not type alias or moved below E struct

type E struct {
	f F
}

func f() {
	_ = E{func(E) {}}
}
```
This looks very much like a duplicate of #27232, though with different details. Leaving open until we know more.

**Comment by griesemer** [comment] 2018-10-29 23:20
Simpler reproducer:
```Go
package p

type P = *S

type S struct {
	p P
}
```
The problem appears to be an incorrectly built type data structure for S after type-checking, such that the type of S.p is S rather than *S. The consequence is the error when calling checkwidth.

**Comment by griesemer** [comment] 2018-10-31 19:50
Probably a duplicate of #25838. Leaving open for now.

**Closed** 2018-11-05 20:31 UTC
Labels: NeedsInvestigation, release-blocker
