### ISSUE TITLE
proposal: cmd/go: install: add environment variable setup for .zshrc

### ISSUE THREAD

**Issue by H0llyW00dzZ** [golang/go#66978] opened 2024-04-22 21:46 UTC
### Proposal Details

By default, the Go package for Darwin (macOS) AMD64, which can be downloaded from [go.dev/dl/go1.22.2.darwin-amd64.pkg](https://go.dev/dl/go1.22.2.darwin-amd64.pkg), does not configure environment variables automatically. Therefore, users must manually set up their environment after installation, especially when installing Go tools using `go install`. To set up your environment:

1. Open your terminal.
2. Edit the `.zshrc` file in your text editor. For instance, using `nano`:

   ```sh
   nano ~/.zshrc
   ```

3. Append the following line to the file:

   ```sh
   export PATH=$PATH:$(go env GOPATH)/bin
   ```

4. Save and exit the file. In `nano`, press `Ctrl + X`, then press `Y` to confirm, and `Enter` to save the changes.

5. Apply the changes to your current terminal session by executing:

   ```sh
   source ~/.zshrc
   ```

It would be more convenient if this configuration were included automatically during the installation process, eliminating the need for manual setup.

**Comment by H0llyW00dzZ** [comment] 2024-04-22 21:57
Ref: https://discussions.apple.com/thread/250911992?sortBy=best

**Comment by seankhliao** [comment] 2024-04-22 22:01
Duplicate of #39531

**Closed by seankhliao** 2024-04-22 22:01 UTC
Labels: Proposal
