### ISSUE TITLE
proposal: go xx in go.mod should lock go version ?

### ISSUE THREAD

**Issue by dfang** [golang/go#36175] opened 2019-12-17 04:20 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mj/Library/Caches/go-build"
GOENV="/Users/mj/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mj/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mj/src/JD/webhookd/webhookd/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xb/dsd0_2b92x7bsl92xlzj6fbm0000gn/T/go-build602873987=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

if an application writes in go 1.13,  there is a line `go 1.13` in go.mod,  you download it and run go run main.go, your current go version is go 1.12 or change it to go 1.12 via gvm, what would happen ?

it seems go xxx in go.mod does not lock go version like ruby bundler ?

### What did you expect to see?

prompt to install go1.12 or more documentation/details on this behavior ( when go run main.go works when use go module) 

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x154da3a]

```

**Comment by seankhliao** [comment] 2019-12-17 10:39
see also #30791

**Comment by bcmills** [comment] 2019-12-17 13:45
Duplicate of #30791

**Closed by bcmills** 2019-12-17 13:45 UTC
Labels: Proposal
