### ISSUE TITLE
x/tools/gopls: formatting with missing final line break clears last line

### ISSUE THREAD

**Issue by carlpett** [golang/go#33717] opened 2019-08-19 15:46 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, of gopls, at least.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cape/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/cape/dev"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/PATH-TO-MY-MODULE/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build692302619=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

Also, running in Sublime with LSP package, if relevant.

### What did you do?
Write code. Do not place final empty newline. Format.

```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, world")
} // No newline!
```

### What did you expect to see?
Newline added to the end of the file

```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, world")
} // Added newline!


```

### What did you see instead?
Last line cleared.

```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, world")
```

**Comment by ianthehat** [comment] 2019-08-19 16:42
This might be an issue with sublime, we have a test specifically for this case that passes, and I cannot reproduce in either VSCode or vim.
Can you try using gopls from the command line with `gopls format -w <filename>` and see if works normally, if so it is almost definitely a problem with the way sublime applies past end of file edits.

**Comment by carlpett** [comment] 2019-08-19 17:28
Yep, seems to be the case, commandline works. Is this something which I should report to Sublime or the LSP extension?

**Comment by ianthehat** [comment] 2019-08-19 17:32
Honestly I am not sure, I do not use/run/understand sublime. My guess would be the lsp extension as formatting and the application of edits should be a fundamental feature of lsp integration.
I am going to close this issue, please feel free to comment again if you need it re-opened or if sublime reports there is something we are doing wrong.

**Comment by haferburg** [comment] 2019-08-21 08:42
@ianthehat Hi there! Please have a look at https://github.com/tomv564/LSP/issues/690. We think that the server sends an invalid line number. In this example, the file has lines 0..8, and the server requests are for line 9/column 0.

**Comment by stamblerre** [comment] 2019-11-04 22:36
It looks like the upstream issue in the Sublime repository has been closed. @haferburg is this still an issue?

**Comment by haferburg** [comment] 2019-11-07 21:45
@stamblerre Yea, I think so https://github.com/tomv564/LSP/pull/717

**Comment by stamblerre** [comment] 2019-12-07 01:18
My apologies - the WaitingForInfo label should have been removed. I will try to investigate this soon.

**Comment by pjweinbgo** [comment] 2020-01-27 19:36
Why is this still open? In any case, it shouldn't be blocking 1.0.0

**Comment by stamblerre** [comment] 2020-01-28 05:37
I left it open because it seemed to still require investigation (https://github.com/golang/go/issues/33717#issuecomment-551279764). I'm trying to mark all issues that still need investigation as `gopls/v1.0.0`  to make sure that we at least take a look at them (and maybe decide they aren't actually `gopls/v1.0.0`).

**Comment by stamblerre** [comment] 2020-04-17 03:37
Looks like the upstream repository handled it (https://github.com/sublimelsp/LSP/pull/717), so I'm going to close this since all other clients have supported it. If it becomes an issue again, we can reassess.

**Closed by stamblerre** 2020-04-17 03:37 UTC
Labels: NeedsInvestigation, Tools, gopls
