### ISSUE TITLE
cmd/go: mod tidy replaces non-semver strings non-friendly ones

### ISSUE THREAD

**Issue by cpuguy83** [golang/go#32883] opened 2019-07-01 22:50 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="~/go/bin"
GOCACHE="/Users/cpuguy83/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/cpuguy83/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.6/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/cpuguy83/dev/vk/virtual-kubelet/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h0/019q23y92j58nhjw33nyjd1h0000gn/T/go-build763891092=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Run `go mod tidy` with custom/non-semver tags

### What did you expect to see?

Still be able to tell what tag was put there

### What did you see instead?

It replaces it with semi-gibberish.

Would be nice if it at least put the tag string in a comment.

**Comment by mvdan** [comment] 2019-07-02 06:35
Have you tried this with the 1.13 beta? Can you share a way to reproduce this issue, or at least show the before and after of `go.mod`?

**Comment by cpuguy83** [comment] 2019-07-02 16:13
Before:

```
module fake_module

go 1.12

require (
	github.com/gogo/protobuf v1.2.1 // indirect
	k8s.io/api kubernetes-1.13.7
	k8s.io/apimachinery v0.0.0-20190629125103-05b5762916b3 // indirect
)
```

After:

```
module fake_module

go 1.12

require (
	github.com/gogo/protobuf v1.2.1 // indirect
	k8s.io/api v0.0.0-20190222213804-5cb15d344471
	k8s.io/apimachinery v0.0.0-20190629125103-05b5762916b3 // indirect
)
```

See the k8s.io/api line.

**Comment by mvdan** [comment] 2019-07-02 16:19
I assume this is because it's not following the `vX.Y.Z` tag format. I'm on the phone at the moment, but I'm pretty sure the modules docs can tell you what the restrictions around tag names are.

**Comment by cpuguy83** [comment] 2019-07-02 16:22
Yes, that's exactly why. My point is that the replacement is unfriendly.
As I mentioned, it could at least put the replaced tag name in a comment, or even as an extension to the format itself.

**Comment by cpuguy83** [comment] 2019-07-02 16:22
Also yes, go1.13 behaves the same way as expected.

**Comment by thepudds** [comment] 2019-07-03 02:50
Some related discussion in #25898.

**Comment by thepudds** [comment] 2019-07-03 03:01
Also, a little more context on the current behavior is in https://golang.org/cmd/go/#hdr-Module_queries :

> A fully-specified semantic version, such as "v1.2.3", evaluates to that specific version.
> ...
> A revision identifier for the underlying source repository, such as a commit hash prefix, **revision tag**, or branch name, selects that specific code revision. If the revision is also tagged with a semantic version, the query evaluates to that semantic version. **Otherwise the query evaluates to a pseudo-version for the commit.**

... where the last sentence in that quote is what’s happening in your example I think.

**Comment by cpuguy83** [comment] 2019-07-03 17:05
Yes, I'm posting this issue because this is a poor user experience.

**Comment by bcmills** [comment] 2019-07-18 14:22
Duplicate of #25898

**Closed by bcmills** 2019-07-18 14:22 UTC
Labels: FeatureRequest, NeedsInvestigation, modules
