### ISSUE TITLE
time: i find some problems when using addDate to do date calculation

### ISSUE THREAD

**Issue by Gao-Vidor** [golang/go#66374] opened 2024-03-18 07:15 UTC
### Go version

go version go1.20.5 darwin/amd64

### `go env` :

```shell
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/Library/Caches/go-build"
GOENV="/Users/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
```

### What did i do?

package main

import (
	"fmt"
	"time"
)

func main() {
	d := time.Date(2023, 1, 30, 23, 0, 0, 0, time.Local)
	dd := d.AddDate(0, 1, 0)
	fmt.Println(dd)
}

### What did i see happen?

2023-03-02 23:00:00 +0000 UTC

### What did i expect to see?

In my intuitive understanding, I believe the output should be 2023-02-28 (9) 23:00:00 +0000 UTC

**Comment by ALTree** [comment] 2024-03-18 07:20
This is working as intended. From the [AddDate documentation](https://pkg.go.dev/time#Time.AddDate):

> AddDate normalizes its result in the same way that Date does, so, for example, adding one month to October 31 yields December 1, the normalized form for November 31. 

Closing here since this is not a bug.

**Closed by ALTree** 2024-03-18 07:20 UTC
