### ISSUE TITLE
net/http: connection reset by peer during "race" tests

### ISSUE THREAD

**Issue by rsc** [golang/go#17713] opened 2016-11-01 00:10 UTC
From a recent all.bash on macOS Sierra:

```
--- FAIL: TestTimeoutHandlerRaceHeader (0.01s)
	serve_test.go:1943: Get http://127.0.0.1:49639: dial tcp 127.0.0.1:49639: getsockopt: connection reset by peer
--- FAIL: TestServerEmptyBodyRace_h2 (0.11s)
	serve_test.go:3685: Get https://127.0.0.1:49765: read tcp 127.0.0.1:49766->127.0.0.1:49765: read: connection reset by peer
	serve_test.go:3698: handler ran 19 times; want 20
```

I see stuff like this with some regularity. Not sure if Sierra changed something or the test is buggy or both.

/cc @bradfitz

**Comment by bradfitz** [comment] 2016-11-10 05:22
Same comment here as https://github.com/golang/go/issues/17651#issuecomment-259577351

I ran all these tests in a loop on Sierra (on my home iMac 5K) and can't reproduce.

Closing for now. Please reopen if you see any flake, though. I'm not content with any test being flaky.

**Closed by bradfitz** 2016-11-10 05:22 UTC
Labels: NeedsInvestigation, Testing
