### ISSUE TITLE
x/net/ipv4: ParseHeader will yield incorrect values on certain OSes

### ISSUE THREAD

**Issue by pitust** [golang/go#53228] opened 2022-06-03 18:53 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18.3 darwin/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/pitust/Library/Caches/go-build"
GOENV="/Users/pitust/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/pitust/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/pitust/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.17.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.17.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/pitust/code/netroute2/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4y/_38brkys0wjgsnl5nfqnp13h0000gp/T/go-build860342338=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

I am attempting to parse IPv4 packets with ipv4.ParseHeader. I get the network packets from a `utun` device, which meets the requirement for ipv4.ParseHeader:
> The provided b must be in the format used by a raw IP socket on the local system.
However, two fields: TotalLen and FragOff are parsed incorrectly.

### What did you expect to see?
The TotalLen field being less than the size of the packet that was received.

### What did you see instead?
The TotalLen field was bigger than the (a) MTU (b) the size of the packet buffer (c) the packet that was read from the device, as the values have not been read in big endian.

**Comment by seankhliao** [comment] 2022-06-03 21:52
Duplicate of #32118

**Closed by seankhliao** 2022-06-03 21:52 UTC
