### ISSUE TITLE
html/template: Unexpected result

### ISSUE THREAD

**Issue by jmooring** [golang/go#58460] opened 2023-02-10 20:29 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.19.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jmooring/.cache/go-build"
GOENV="/home/jmooring/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jmooring/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jmooring/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/current"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/current/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/jmooring/code/go-sandbox/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2279415335=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

<https://go.dev/play/p/Nl4_5-ynidw?v=goprev>

### What did you expect to see?

```
<script>
let a = `/</`
let b = `//`
let c = `//`
</script>
```

### What did you see instead?

```
<script>
let a = `/</`
let b = `\//`
let c = `//`
</script>
```

**Comment by seankhliao** [comment] 2023-02-10 20:54
Duplicate of #9200

**Closed by seankhliao** 2023-02-10 20:54 UTC
