### ISSUE TITLE
runtime/cgo: Invalid parameter created and passed by cgo into cl:  invalid numeric argument '/Werror'

### ISSUE THREAD

**Issue by neutron-blast** [golang/go#64695] opened 2023-12-13 14:24 UTC
### Go version

go version go1.21.5 windows/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=cl
set CXX=cl
set CGO_ENABLED=1
set GOWORK=
set CGO_CFLAGS=-Wall /WX
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-Wall /WX
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=
```

### What did you do?

Installed go 1.21.5 using the msi installer: go1.21.5.windows-amd64.msi.
Then set CC=cl, set CC=cl inside a Developer Command Prompt for VS2022 -NOT powershell-.

main.go: 
package main

/*
##cgo LDFLAGS: -L${SRCDIR}/build/Release -lappemitterlib
#include "Emitter.hpp"
*/
import "C"

import "fmt"

func main() {
	// Call the C function
	C.MySingleton_myPublicMethod()

	fmt.Println("Called C++ function from Go")
}.

Tried to run this using go run main.go

### What did you expect to see?

Some random line printed by the c++ function.

Then
"Called C++ function from Go"

### What did you see instead?

# runtime/cgo
Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32824 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line error D8021 : invalid numeric argument '/Werror'

**Comment by mauri870** [comment] 2023-12-13 14:35
The compiler probably does not support -Werror, I'm not sure if we can do anything in this particular case.

cc @golang/runtime

**Comment by neutron-blast** [comment] 2023-12-13 14:49
You could fix the CC, CXX detection to generate proper Wflags depending on the compiler. Or, alternatively and easier, give the option for a full override of these parameters by the user. So that if you don't choose gcc, you can make it work on your own...

**Comment by bcmills** [comment] 2023-12-13 16:42
> Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32824 for x86

Go does not currently work with the Microsoft C toolchain; see #20982 and https://go.dev/wiki/cgo#windows.

**Comment by bcmills** [comment] 2023-12-13 16:43
Duplicate of #20982

**Closed by bcmills** 2023-12-13 16:43 UTC
Labels: OS-Windows, NeedsInvestigation, compiler/runtime
