### ISSUE TITLE
"/" route run twice!

### ISSUE THREAD

**Issue by mafrashteh** [golang/go#15662] opened 2016-05-12 11:23 UTC
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6.2-2

2. What operating system and processor architecture are you using (`go env`)?
arch linux/amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

> package main
> 
> import (
> 	"fmt"
> 	"net/http"
> )
> 
> func main() {
> 	http.HandleFunc("/", indexRoute)
> 	http.ListenAndServe(":8000", nil)
> }
> 
> func indexRoute(w http.ResponseWriter, r *http.Request) {
> 	fmt.Println("aa")
> }

I've checked another routes but they were OK (like "/about")

4. What did you expect to see?
"aa"

5. What did you see instead?
"aa"
"aa"

**Comment by davecheney** [comment] 2016-05-12 11:25
This is your browser hitting `/favicon.ico`. 

I am going to close this issue as it is not a bug. We don't use the issue tracker for asking questions , please see htttps://golang.org/wiki/Questions for questions.

**Closed by davecheney** 2016-05-12 11:25 UTC

**Comment by mafrashteh** [comment] 2016-05-12 11:29
Thank you
