### ISSUE TITLE
net/http: document that Server.Serve expects a hashable net.Listener (as a map key)

### ISSUE THREAD

**Issue by jdef** [golang/go#25487] opened 2018-05-22 03:57 UTC
### What version of Go are you using (`go version`)?
1.10

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vagrant/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vagrant/workspace-dss"
GORACE=""
GOROOT="/usr/local/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build230598238=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

I implemented `net.Listener` with a struct that defined a `func()` field. I passed this struct to `http.Server.Serve`. The code compiled just fine and panicked at run-time because my listener implementation couldn't be used as a hash key (see `trackListener` in the `http` package).

### What did you expect to see?

A working `http.Server`. Or else some documentation that clearly states the constraints for the kinds of listeners usable with `http.Server`.

### What did you see instead?

Panic at run-time.

**Comment by meirf** [comment] 2018-05-22 05:57
@jdef Thanks for your report. This is probably enough information to reproduce your issue, but it would be helpful if you had a snippet in the form of a https://play.golang.org link to save us time in reproducing and in guaranteeing we fix the exact issue.

**Comment by artyom** [comment] 2018-05-22 13:27
Duplicate of #24812 ?

**Comment by jdef** [comment] 2018-05-22 14:54
Yes, it's a duplicate. Thanks

**Comment by AlekSi** [comment] 2018-05-22 15:45
@jdef Can you please close it then?

**Comment by meirf** [comment] 2018-05-22 16:32
If this has already happened maybe this should stay open as a documentation
issue so we don’t get more issues like this.

**Comment by odeke-em** [comment] 2018-05-22 21:47
Great point @meirf!  Might you or anyone else here be interested in sending a CL?

**Comment by artyom** [comment] 2018-05-23 08:15
@meirf, @odeke-em looks like the linked issue already has this fixed, so we don’t need to change documentation.

**Comment by meirf** [comment] 2018-05-24 04:54
@artyom Yes, looks like a fix for this was merged as shown in the linked issue. Sorry for misleading.

@jdef A fix for this has been merged, though not yet in an official release.

@odeke-em please close when you have a chance.

**Closed** 2018-05-31 22:02 UTC
Labels: Documentation
