### ISSUE TITLE
Compilation hangs when building with debug flags

### ISSUE THREAD

**Issue by pokeroklife** [golang/go#35871] opened 2019-11-27 13:25 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sergey/.cache/go-build"
GOENV="/home/sergey/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/sergey/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/home/sergey/go/go1.13.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/sergey/go/go1.13.4/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/sergey/go/src/github.com/icamys/whois-parser/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build061612026=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do? What did you expect to see? What did you see instead?

I've created a separate repo with bug description and reproduction: 

https://github.com/pokeroklife/golang-debug-issue

**Comment by odeke-em** [comment] 2019-11-29 06:53
Thank you for filing this bug @pokeroklife and welcome to the Go project!

This bug is a duplicate of https://github.com/golang/go/issues/29144, please follow that bug instead which has some activity.

**Closed** 2019-11-29 06:53 UTC
