### ISSUE TITLE
x/website: SHA256 Checksum incorrect in Ubuntu

### ISSUE THREAD

**Issue by dmikester1** [golang/go#42796] opened 2020-11-24 04:50 UTC
### What version of Go are you using (`go version`)?

<pre>
trying to download go1.15.5.linux-amd64

</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)? 

<details><summary><code>go env</code> Output</summary><br><pre>
Ubuntu, 64 bit

</pre></details>

### What did you do?

Download the file with command `curl -O [file url]`

### What did you expect to see?
Same checksum as on the site: `9a58494e8da722c3aef248c9227b0e9c528c7318309827780f16220998180a0d`

### What did you see instead?
```
:~$ sha256sum go1.15.5.linux-amd64.tar.gz
2a862fbe29f35d8d24d68c8cf3f60c7cb0c3ac80a7875b8651e23c2fb5cb3d13  go1.15.5.linux-amd64.tar.gz
```

**Comment by dmitshur** [comment] 2020-11-24 05:00
Thanks for reporting, we'll take a look.

CC @golang/release.

**Comment by seankhliao** [comment] 2020-11-24 17:30
you need to follow redirects, the contents of your download is:

```
<a href="https://dl.google.com/go/go1.15.5.linux-amd64.tar.gz">Found</a>.
```

**Comment by cagedmantis** [comment] 2020-11-24 17:30
I've downloaded Go from`https://golang.org/dl/go1.15.5.linux-amd64.tar.gz` and have been unable to reproduce your results. 

```
shasum -a 256 ./go1.15.5.linux-amd64.tar.gz
9a58494e8da722c3aef248c9227b0e9c528c7318309827780f16220998180a0d  ./go1.15.5.linux-amd64.tar.gz
```

```
sha256sum ./go1.15.5.linux-amd64.tar.gz
9a58494e8da722c3aef248c9227b0e9c528c7318309827780f16220998180a0d  ./go1.15.5.linux-amd64.tar.gz
```

Where did you retrieve your file from?

**Comment by cagedmantis** [comment] 2020-11-24 17:35
I was able to reproduce your findings with @seankhliao comment. I'm going to close this issue since it is not an issue with the Go project. Please feel free to open it again if you believe otherwise.

**Closed by cagedmantis** 2020-11-24 17:35 UTC
Labels: NeedsInvestigation

**Comment by dmikester1** [comment] 2020-11-24 17:50
Yep, you were right @seankhliao !  Thanks for the quick replies!!
