### ISSUE TITLE
GOMAXPROCS not work

### ISSUE THREAD

**Issue by tinyRatP** [golang/go#42845] opened 2020-11-26 11:49 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xxx/.cache/go-build"
GOENV="/home/xx/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/xxx/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/xxx/.go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/xxx/gRPC-tutorial/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build338536254=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

My CPU nums:

```bash
$ echo "Threads/core: $(nproc --all)"
Threads/core: 4
```
[Go Playground](https://play.golang.org/p/pJJrsHD1b8H)

### What did you expect to see?

It should cost 6s.

### What did you see instead?

It cost 3s.

**Comment by go101** [comment] 2020-11-26 12:32
Why should it cost 6s?

The result should be unrelated to GOMAXPROCS.

**Comment by mpx** [comment] 2020-11-26 12:43
`GOMAXPROCS` limits the number of OS threads used to actively run Goroutines. The goroutines in your example spend almost all their time sleeping (not running) . `GOMAXPROCS` will make more of a difference if your workers are performing a fixed amount of heavy computation instead.

I'd recommend asking these questions on the Gopher Slack forum, or golang-nuts. This issue tracker is intended for developing the Go toolchains and related projects.

**Comment by ALTree** [comment] 2020-11-26 13:00
As it was pointed out, there's no reason to expect the program to take 6s: all the goroutines just sleep for 3s an then the program returns. GOMAXPROCS' value makes no difference here. Closing, since this is not a bug in Go.

**Closed by ALTree** 2020-11-26 13:00 UTC
