### ISSUE TITLE
x/website: Remove political noise

### ISSUE THREAD

**Issue by ross2084** [golang/go#47820] opened 2021-08-19 18:39 UTC
### What is the URL of the page with the issue?
 
 https://golang.org
 
### What is your user agent?
 

 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
 
 
### What did you do?
 
Load any page under golang.org.

 
 
 
### What did you expect to see?
 
A site free of political noise, increasing the apparent intelligence of the site.
 
### What did you see instead?

A banner of text, pointlessly and utterly unrelated to Go.

**Comment by seankhliao** [comment] 2021-08-19 19:04
Duplicate of #39850

**Closed by seankhliao** 2021-08-19 19:04 UTC
