### ISSUE TITLE
builders: linux-ppc64-buildlet is failing saying "Stale runtime.a"

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#19062] opened 2017-02-13 18:53 UTC
There have been several recent failures on linux-ppc64-buildlet in which the runtime package fails saying

    --- FAIL: TestCrashHandler (0.06s)
    	crash_test.go:171: Stale runtime.a. Run 'go install runtime'.

The error is repeated many times.

For example:
https://build.golang.org/log/3c1890fd20e980d864f36c0fa3eabbcd83d2d1f0
https://build.golang.org/log/e6dd0a7c7399a1858c20e64efbf79b82adf31992

This error is basically impossible as the runtime package was just built and installed, and can not be stale.  This suggests some sort of misconfiguration or disk error on the buildlet.

**Comment by ianlancetaylor** [comment] 2017-02-13 18:59
Also happening on linux-ppc64le-buildlet:
https://build.golang.org/log/8e0531dbb1211817f46f1b88c765731c4a27e04c
https://build.golang.org/log/3238a5ec0d5faa6e831951fa698c898001852ed4

CC @laboger

**Comment by bradfitz** [comment] 2017-02-13 19:01
I really don't want to debug this again on my own. I seem to recall fighting this with the Mac builders for a while to no avail. But the suspicion at the time was because the build was sharded and shipped around, I figured there was clock skew between the machines. But with ppc64 and ppc64le there's no sharding, so I have no clue what the problem is.

Can I just disable that stale check somehow?

**Comment by ianlancetaylor** [comment] 2017-02-13 19:22
The test would be easy to disable.  It's in `checkStaleRuntime` in runtime/crash_test.go.

I'll see if I can recreate it using gomote.

**Comment by laboger** [comment] 2017-02-13 19:41
I am not familiar with what can cause it to decide that a package is stale.  It might be helpful to have the error message in the test print out the contents of the 'out' variable and the staleReason.

**Comment by ianlancetaylor** [comment] 2017-02-13 19:43
I have not been able to recreate this using gomote.

**Comment by laboger** [comment] 2017-02-13 20:58
StaleReason is what I was hoping to see.

I'm trying to see if I can reproduce it somewhere.  There is a definite commit where it started happening recently.

**Comment by bradfitz** [comment] 2017-02-13 21:04
Oh, yes, it should be StaleReason.

**Comment by laboger** [comment] 2017-02-13 22:33
I'm not able to reproduce this so far.  What is the exact command or script that is used to invoke these builds?

**Comment by ianlancetaylor** [comment] 2017-02-14 00:12
OK, now that we print `StaleReason` I see this in https://build.golang.org/log/28884d904691d58ce1090a5904d78699572866c0:

    --- FAIL: TestCrashHandler (0.09s)
            crash_test.go:167: go list -f {{.Stale}} runtime:
                    true
            crash_test.go:172: go list -f {{.StaleReason}} runtime:
                    stale dependency
            crash_test.go:177: Stale runtime.a. Run 'go install runtime'.

**Comment by bradfitz** [comment] 2017-02-14 00:15
Now we just {{.StaleReasonReason}} and we'll have everything we need.

**Comment by laboger** [comment] 2017-02-14 15:27
I'll make a change so the stale reason contains information on what package dependency is stale.

**Comment by laboger** [comment] 2017-02-14 18:03
I made the change which I think will provide some good information for this and in the future if we see this again.  But from what we know now, runtime.a is not stale but one of the files it depends on is.  And I have not seen it on any other system so something must be flaky about the systems you are building on.  I have lost track of that information, can you send me information about the machines you are using for ppc64 builders and if I can get on and see what I can find out.

One possibility is that the packages are built in parallel and the dependent packages don't finish building until after runtime.a is finished.  I didn't really see anything that should enforce that build completion order?

**Comment by bradfitz** [comment] 2017-02-15 18:09
@rsc might be able to answer cmd/go parallelism questions.

**Comment by rsc** [comment] 2017-02-15 18:14
Please try

    go list -f '{{.ImportPath}} {{.StaleReason}}' runtime...

instead. runtime only has three dependencies: runtime/internal/atomic, runtime/internal/sys, and unsafe. It's not possible for unsafe to be out of date, so it must be one of the first two. 

Are there files changing in those directories after the build? 

runtime/internal/sys has some auto-generated files in it. Would they be regenerated for some reason?

**Comment by laboger** [comment] 2017-02-15 20:22
I'm not able to reproduce this on any other system, but I'm probably not building it the same way the builder does.

Would it be possible to get on a builder machine so I can look at the directories if they are still around?

**Comment by bradfitz** [comment] 2017-02-15 21:25
@laboger, sorry, I can't easily get you access. It also wouldn't really help as the directories are deleted after builds.

**Comment by laboger** [comment] 2017-02-15 21:37
OK, I see 3 builds in a row on ppc64 that are showing this:
stale dependency sys: newer source file /tmp/workdir/go/src/runtime/internal/sys/arch.go

Is there some way this file would get modified during the build?

**Comment by ianlancetaylor** [comment] 2017-02-15 22:23
Weird.  I don't know of any way that that file would be modified.

I note that arch.go is the first file in runtime/internal/sys when the names are sorted, so it seems conceivable that all the files in the directory have had their mtimes changed or truncated somehow and cmd/go is just reporting the first one.

**Comment by minux** [comment] 2017-02-15 22:36
on https://golang.org/cl/36944 I suggested to output precise modification
time of all relevant files if the test fails.
perhaps we can see something from the actual timestamp (e.g. only have
second precision?)

**Comment by ianlancetaylor** [comment] 2017-02-15 22:42
It's worth a try.

I note that even only having second precision should be OK.  The relevant code checks `fi.ModTime().After(built)`, where `built` is the time that the .a was built.  As far as I can see this test can only fail if the .a file appears to have been created before the source file.  And all the files involved are under /tmp.  It's hard to see how that could happen unless the system has gone mad.

**Comment by laboger** [comment] 2017-02-15 22:43
I noticed that the failures for ppc64le occur when there are 2 builds started at almost the same time.  Could there be some way that the directories or files from 2 separate builds are trying to write to the same directories?

I agree we could try Minux' idea but the one he suggested in the CL generates a lot of output.

**Comment by minux** [comment] 2017-02-15 23:05
We can use `stat --printf="%n %y\n" files` to generate one line per file.
(I tried to use %Y so that we can trivially sort the list with sort(1), but
that doesn't include sub-second precision.)

different builds shouldn't bump into each other with same $WORK, unless our
io/ioutil.TempDir is severely broken.

**Comment by ianlancetaylor** [comment] 2017-02-15 23:39
I note that the file is literally `/tmp/workdir/go/src/runtime/internal/sys/arch.go`, so the possibility of a file collision among different builds does not seem impossible.  Unless this is a VM spun up fresh for each new build, of course.

**Comment by bradfitz** [comment] 2017-02-15 23:43
It only does one build at a time.

But I can't get into them at the moment (not sure why) so I can't see what they're doing.

**Comment by quentinmit** [comment] 2017-02-16 01:10
Is there any possibility there are two buildlets running on the same
machine?

On Feb 15, 2017 18:43, "Brad Fitzpatrick" <notifications@github.com> wrote:

It only does one build at a time.

But I can't get into them at the moment (not sure why) so I can't see what
they're doing.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/golang/go/issues/19062#issuecomment-280179263>, or mute
the thread

**Comment by laboger** [comment] 2017-02-16 16:05
Yesterday on the Go build dashboard I saw more than one gopher icon in the ppc64le column at once.  I thought that meant multiple buildlets were running for ppc64le.

**Comment by bradfitz** [comment] 2017-02-16 16:15
There are 5 separate VMs.

On Feb 16, 2017 8:06 AM, "Lynn Boger" <notifications@github.com> wrote:

Yesterday on the Go build dashboard I saw more than one gopher icon in the
ppc64le column at once. I thought that meant multiple buildlets were
running for ppc64le.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/golang/go/issues/19062#issuecomment-280374039>, or mute
the thread

**Comment by bradfitz** [comment] 2017-02-16 23:12
> Is there any possibility there are two buildlets running on the same machine?

Not unless there's an amazing bug in systemd. I really doubt it.

**Comment by ceseo** [comment] 2017-02-17 00:55
Are the build directories located in a networked file system? I ran into similar problems with 'make' a long time ago due to NFS clock skew between my machine and the machine hosting the disks.

**Comment by bradfitz** [comment] 2017-02-17 02:16
@ceseo, no NFS. Some ext4 and mostly tmpfs.

**Comment by laboger** [comment] 2017-02-20 15:06
OK so either the time computation is wrong or the /tmp filesystem is showing the wrong times.

I can make the change to display the timestamps for the source files and .a files that appearing to be stale.  I can add Minux' suggestion from above to the test when it fails this way in crast_test.go.

Once we have more detail on what's wrong on the system you should open a ticket with OSU if you haven't already. They are aware there is a problem but need more detail to be able to help resolve it.  If you don't have information on opening a ticket I can send it to you.

**Comment by laboger** [comment] 2017-02-21 18:42
I have created CL 37332 with an update for runtime/crash_test.go to get timestamp information on the packages and source files.  I can display individual files OK, but I am stuck on how to display all source files in a directory.  I am using exec.Command to run the stat command as Minux suggests above.

Right now it displays this:
crash_test.go:175: /home/boger/golang/upstream/go/pkg/linux_ppc64le/runtime.a 2017-02-21 11:20:10.512000001 -0500
	crash_test.go:178: /home/boger/golang/upstream/go/pkg/linux_ppc64le/runtime/internal/sys.a 2017-02-21 11:20:08.252000001 -0500
	crash_test.go:181: /home/boger/golang/upstream/go/pkg/linux_ppc64le/runtime/internal/atomic.a 2017-02-21 11:20:08.268000001 -0500
	crash_test.go:184: /home/boger/golang/upstream/go/src/runtime/internal/sys/arch.go 2017-02-21 11:35:08.884000000 -0500

I'm not able to get the last output to show the dates on all the sources file in the directory.  If I try to pass in a string that ends in *.go I am getting this:

crash_test.go:184: stat: cannot stat "/home/boger/golang/upstream/go/src/runtime/internal/sys/*.go": No such file or directory

**Comment by bradfitz** [comment] 2017-02-21 21:58
*.go expansion is done by your shell. os/exec.Command passes arguments to programs directly. If you need shell expansion, you either need to do it yourself by hand, or call a shell to run the stat command indirectly instead, having the shell do your argument expansion.

**Comment by laboger** [comment] 2017-02-21 22:06
Ian suggested just doing ls -lR GOROOT in the CL.

BTW, is the ppc64 builder a power8 or power7?  I thought when you moved ppc64 to OSU it was using power8.

**Comment by bradfitz** [comment] 2017-02-21 22:09
ppc64:
```
$ cat /proc/cpuinfo 
processor	: 0
cpu		: POWER8E (raw), altivec supported
clock		: 3425.000000MHz
revision	: 2.1 (pvr 004b 0201)

processor	: 1
cpu		: POWER8E (raw), altivec supported
clock		: 3425.000000MHz
revision	: 2.1 (pvr 004b 0201)

timebase	: 512000000
platform	: pSeries
model		: IBM pSeries (emulated by qemu)
machine		: CHRP IBM pSeries (emulated by qemu)
```

ppc64le:
```
$ cat /proc/cpuinfo 
processor	: 0
cpu		: POWER8E (raw), altivec supported
clock		: 3425.000000MHz
revision	: 2.1 (pvr 004b 0201)

processor	: 1
cpu		: POWER8E (raw), altivec supported
clock		: 3425.000000MHz
revision	: 2.1 (pvr 004b 0201)

timebase	: 512000000
platform	: pSeries
model		: IBM pSeries (emulated by qemu)
machine		: CHRP IBM pSeries (emulated by qemu)
```

**Comment by laboger** [comment] 2017-02-21 22:12
This page still says power7 for ppc64.  https://github.com/golang/go/wiki/DashboardBuilders

**Comment by bradfitz** [comment] 2017-02-21 22:19
Fix it, then? It's a wiki. :)

**Comment by bradfitz** [comment] 2017-02-22 16:44
Some notes from the ppc64 hosts:

* they're KVM/qemu VMs inside some host OS
* the VMs aren't running NTP
* their system time is ~62 seconds behind my GCE development VM's time

Perhaps the buildlet writes all the files to disk on what the ppc VM considers to be the future?

**Comment by laboger** [comment] 2017-02-22 17:04
I submitted the change to display the timestamps.  The ppc64le and ppc64 builds started about the same time.

All the .go source files on both systems have the same time, with second precision.
-rw-r--r-- 1 root root  283 2017-02-22 16:34:14.000000000 +0000 arch.go
The directories, .a files, and binaries all have various times with subsecond precision.

/tmp/workdir/go/src/runtime/internal/sys:
		total 176
		-rw-r--r-- 1 root root  283 2017-02-22 16:34:14.000000000 +0000 arch.go
		-rw-r--r-- 1 root root  475 2017-02-22 16:34:14.000000000 +0000 arch_386.go
		-rw-r--r-- 1 root root  418 2017-02-22 16:34:14.000000000 +0000 arch_amd64.go
		-rw-r--r-- 1 root root  448 2017-02-22 16:34:14.000000000 +0000 arch_amd64p32.go
		-rw-r--r-- 1 root root  411 2017-02-22 16:34:14.000000000 +0000 arch_arm.go
		-rw-r--r-- 1 root root  413 2017-02-22 16:34:14.000000000 +0000 arch_arm64.go
		-rw-r--r-- 1 root root  412 2017-02-22 16:34:14.000000000 +0000 arch_mips.go
		-rw-r--r-- 1 root root  414 2017-02-22 16:34:14.000000000 +0000 arch_mips64.go
		-rw-r--r-- 1 root root  414 2017-02-22 16:34:14.000000000 +0000 arch_mips64le.go
		-rw-r--r-- 1 root root  412 2017-02-22 16:34:14.000000000 +0000 arch_mipsle.go
		-rw-r--r-- 1 root root  415 2017-02-22 16:34:14.000000000 +0000 arch_ppc64.go
		-rw-r--r-- 1 root root  415 2017-02-22 16:34:14.000000000 +0000 arch_ppc64le.go
		-rw-r--r-- 1 root root  413 2017-02-22 16:34:14.000000000 +0000 arch_s390x.go
		-rw-r--r-- 1 root root 2175 2017-02-22 16:34:14.000000000 +0000 gengoos.go
		-rw-r--r-- 1 root root 2161 2017-02-22 16:34:14.000000000 +0000 intrinsics.go
		-rw-r--r-- 1 root root  961 2017-02-22 16:34:14.000000000 +0000 intrinsics_386.s
		-rw-r--r-- 1 root root  304 2017-02-22 16:34:14.000000000 +0000 intrinsics_stubs.go
		-rw-r--r-- 1 root root  780 2017-02-22 16:34:14.000000000 +0000 intrinsics_test.go
		-rw-r--r-- 1 root root  532 2017-02-22 16:34:14.000000000 +0000 stubs.go

/tmp/workdir/go/pkg/linux_ppc64le/runtime/internal:
		total 16
		-rw-r--r-- 1 root root 7498 2017-02-22 16:32:28.428001496 +0000 atomic.a
		-rw-r--r-- 1 root root 5940 2017-02-22 16:32:28.416001496 +0000 sys.a

**Comment by bradfitz** [comment] 2017-02-22 19:20
I guess we should modify the buildlet to never write a file from a tarball newer than the system time, clamping the modtime at time.Now().

**Comment by bradfitz** [comment] 2017-02-23 22:31
build.golang.org looks happy. Closing.

**Closed by bradfitz** 2017-02-23 22:31 UTC
Labels: Builders, HelpWanted
