### ISSUE TITLE
cmd/compile: reports wrong line number when calling a method in multiple lines

### ISSUE THREAD

**Issue by yhuang0** [golang/go#22083] opened 2017-09-28 18:05 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.9

### Does this issue reproduce with the latest release?
Yes

### What did you do?
Use method to access array in struct.
https://play.golang.org/p/oJ_Uh9hGN0

### What did you expect to see?
I expected the error in the stack trace to point to line 16.

### What did you see instead?
Stack trace pointed to line 13 instead, the first invocation of Get()

**Comment by mvdan** [comment] 2017-09-28 18:35
Reproduces on master.

Here's an interesting twist: https://play.golang.org/p/8G8BxckMZq

It seems to use the first method call as the position, so in the case above it uses the first `GetB` call, not the first `GetA` call. Probably the compiler recording the line number incorrectly, perhaps because it reuses something between these calls?

/cc @mdempsky

**Comment by ianlancetaylor** [comment] 2017-10-02 22:09
An incorrect traceback can be very confusing, so marking this as a 1.9.1 candidate.

**Comment by randall77** [comment] 2017-10-03 15:58
Reopening for 1.9.1 (or 1.9.2?)

**Comment by rsc** [comment] 2017-10-13 18:44
This seems like a pretty subtle change. The win here is that some line numbers get fixed. Is that worth the risk? Should we just leave this for Go 1.10?

**Comment by randall77** [comment] 2017-10-13 19:54
It's not the end of the world if doesn't get in 1.9.  It's just backtrace line numbers, and needs a lot of things to happen to trigger it (inlining, bounds check fail or divide by zero, multiple identical call sites).

Two arguments in its favor:

- It is a regression from 1.8
- The fix is 2 lines

**Comment by rsc** [comment] 2017-10-13 20:24
The fix is 2 lines but it affects the generated code, right? Because panics that were merged now are not. That could in turn affect other optimizations and might stir other issues around, right?

**Comment by ianlancetaylor** [comment] 2017-10-13 20:40
I think this is fairly important for 1.9, actually.  The incorrect tracebacks have already led people to spend time poring over the wrong code.  When the stack trace points you directly at a specific line, it's hard to understand that the problem is actually at a completely different, possibly quite distant, line in the same function.

**Comment by randall77** [comment] 2017-10-13 20:51
@rsc Yes, it does affect the generated code.  I'm not particularly worried about not merging two calls that we used to merge.  That's the normal state, having unmergeable calls.  That path is very well exercised.

**Comment by rsc** [comment] 2017-10-14 00:20
CL 67632 OK for Go 1.9.2.

**Comment by rsc** [comment] 2017-10-26 21:09
go1.9.2 has been packaged and includes:

  - [CL 67632](https://golang.org/cl/67632) 

The release is posted at [golang.org/dl](https://golang.org/dl).

— golang.org/x/build/cmd/releasebot, Oct 26 21:09:19 UTC

**Closed by rsc** 2017-10-26 21:09 UTC
Labels: cherry-pick-approved
