### ISSUE TITLE
x/website: "Random greeting" tutorial says code should have "init" method but no "init" method in the code

### ISSUE THREAD

**Issue by pt7481** [golang/go#61140] opened 2023-07-02 00:30 UTC
### What is the URL of the page with the issue?
 
 https://go.dev/doc/tutorial/random-greeting
 
### What is your user agent?
 
[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)
 
### Screenshot

<img width="990" alt="Screen Shot 2023-07-01 at 5 27 20 PM" src="https://github.com/golang/go/assets/9630056/544bff0c-85e0-4511-a35f-663646cb6b01">
 
### What did you do?
 
Just load the page.
 
### What did you expect to see?
 
The tutorial says the greetings.go code should include an "init" method per the following bullet:
- "Add an init function to seed the rand package with the current time. Go executes init functions automatically at program startup, after global variables have been initialized. For more about init functions, see [Effective Go](https://go.dev/doc/effective_go.html#init)."

Given the above, I expected to see an "init" function in the greetings.go code.

### What did you see instead?

I did not see an "init" function in the greetings.go code.

**Comment by Nasfame** [comment] 2023-07-02 07:26
@pt7481  copy-paste code in code blocks. Don't upload screenshots of the code.

**Comment by Nasfame** [comment] 2023-07-02 07:37
<s>`rand.Seed(time.Now().UnixNano())` </s> has been deprecated since Go1.20.

**Comment by seankhliao** [comment] 2023-07-02 09:53
Duplicate of #60627

**Closed by seankhliao** 2023-07-02 09:53 UTC
Labels: website
