### ISSUE TITLE
tour: hyperlinks are not obvious

### ISSUE THREAD

**Issue by kingpong** [golang/go#13418] opened 2015-11-27 23:38 UTC
Context: http://127.0.0.1:3999/flowcontrol/13

Hi, just going through the Golang tour (very cool, btw) and was confused by the sentence "To learn more about defer statements read this blog post." because there was no link to a blog post. Then I realized that "blog post" was an undecorated link. It would be clearer if the link were underlined or somehow called out.

**Comment by ALTree** [comment] 2015-11-28 00:24
This is #13121 and #13122

**Comment by rakyll** [comment] 2015-11-28 18:03
Duplicate of https://github.com/golang/go/issues/13121.

**Closed by rakyll** 2015-11-28 18:03 UTC
