### ISSUE TITLE
cmd/go: "go get" doesn't work, but also doesn't produce errors

### ISSUE THREAD

**Issue by jmarlow4** [golang/go#44825] opened 2021-03-05 22:48 UTC
Every time I run "go get" it doesn't actually put the package into the src folder of my go path. I've tried reinstalling go from homebrew and still nothing.

### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jason/Library/Caches/go-build"
GOENV="/Users/jason/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jason/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jason/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What did you do?
Nothing... just coming back to try my hand at go development after a small hiatus.

### What did you expect to see?
When I run go get, it puts the package in my GOPATH src folder

### What did you see instead?
No package being downloaded to src

![image](https://user-images.githubusercontent.com/2195317/110182809-c06a7480-7dca-11eb-874a-fdec09f79bbc.png)

**Comment by dmitshur** [comment] 2021-03-05 23:47
> Nothing... just coming back to try my hand at go development after a small hiatus.

(Welcome back! 😄)

The go command is working as expected. Take a look at https://golang.org/doc/go1.16#go-command to understand the change you're seeing.

I'll close this since it's not a bug, but please feel free to use https://golang.org/wiki/Questions if you run into any questions.

**Closed by dmitshur** 2021-03-05 23:47 UTC
Labels: GoCommand

**Comment by icholy** [comment] 2021-03-05 23:48
See https://github.com/icholy/git-get

**Comment by sv-yaz-ist** [comment] 2021-03-08 15:46
> Every time I run "go get" it doesn't actually put the package into the src folder of my go path. I've tried reinstalling go from homebrew and still nothing.
> 
> ### What version of Go are you using (`go version`)?
> $ go version
> 1.16
> ### Does this issue reproduce with the latest release?
> Yes
> 
> ### What operating system and processor architecture are you using (`go env`)?
> `go env` Output
> ### What did you do?
> Nothing... just coming back to try my hand at go development after a small hiatus.
> 
> ### What did you expect to see?
> When I run go get, it puts the package in my GOPATH src folder
> 
> ### What did you see instead?
> No package being downloaded to src
> 
> ![image](https://user-images.githubusercontent.com/2195317/110182809-c06a7480-7dca-11eb-874a-fdec09f79bbc.png)

I have the same problem. How did you solve it?
