### ISSUE TITLE
unecpected error when using blank identifier

### ISSUE THREAD

**Issue by pierrec** [golang/go#20659] opened 2017-06-13 19:29 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version go1.8.3 darwin/amd64
Also tried on tip:
go version devel +b488073d51 Tue Jun 13 18:36:04 2017 +0000 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/pierrecurto/sandbox"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bw/wf4p9qr50pg23qb4py4028140000gp/T/go-build444531641=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

### What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.
https://play.golang.org/p/JFd-JYI86D

### What did you expect to see?
No error.

### What did you see instead?
main.go:10: cannot use _ as value

Note that if you replace the anonymous function with a declared one it compiles fine.
It also works fine if the blank identifier is replaced with a non blank one.

**Comment by griesemer** [comment] 2017-06-13 19:31
Closing as duplicate of #15481.

**Closed by griesemer** 2017-06-13 19:31 UTC
