### ISSUE TITLE
cmd/go: `go list -e -export -json -gcflags=-bogus math` prints to stderr

### ISSUE THREAD

**Issue by mdempsky** [golang/go#46817] opened 2021-06-18 07:50 UTC
https://tip.golang.org/cmd/go/#hdr-List_packages_or_modules says:

> The -e flag changes the handling of erroneous packages, those that cannot be found or are malformed. By default, the list command prints an error to standard error for each erroneous package and omits the packages from consideration during the usual printing. **With the -e flag, the list command never prints errors to standard error and instead processes the erroneous packages with the usual printing.** Erroneous packages will have a non-empty ImportPath and a non-nil Error field; other information may or may not be missing (zeroed).

However, at least some compiler errors still end up getting written to stderr. For example, `go list -e -export -json -gcflags=-bogus math >/dev/null` shows output for me.

/cc @rsc @bcmills @jayconrod

**Comment by wymli** [comment] 2021-07-22 05:59
`go get` prints to stderr too.
It's kind of strange.
For example, I have to use `update_msg=$(go get -u ${some_pkg} 2>&1)` to capture the output.

**Comment by dominikh** [comment] 2022-02-14 04:50
Other instances of output on stderr:

https://github.com/golang/go/issues/51180
https://github.com/golang/go/issues/50869
https://github.com/golang/go/issues/25842

**Comment by bcmills** [comment] 2022-09-30 20:27
Duplicate of #25842

**Closed by bcmills** 2022-09-30 20:27 UTC
Labels: NeedsFix
