### ISSUE TITLE
runtime: string too long on noopt build

### ISSUE THREAD

**Issue by bradfitz** [golang/go#9280] opened 2014-12-12 04:52 UTC
The linux builder with optimizations disabled is failing with:
[string too long]

![noopt](https://cloud.githubusercontent.com/assets/2621/5407293/dfcb7c4a-8216-11e4-859c-d4616640e0c8.png)

**Comment by rsc** [comment] 2015-04-10 19:08
We should fix the more general problem that -N doesn't pass all.bash.

**Comment by josharian** [comment] 2015-05-05 03:51
-N passes all.bash at tip.

**Comment by josharian** [comment] 2015-05-05 15:58
Left this running for a while locally and I can't reproduce. The builder is passing, and this was filed six months ago. Closing this until we see it again.

**Closed by josharian** 2015-05-05 15:58 UTC
