### ISSUE TITLE
incorrect musl interpreter/loader chosen when cross compiling with PIE

### ISSUE THREAD

**Issue by craftyguy** [golang/go#48204] opened 2021-09-05 23:07 UTC
### What version of Go are you using (`go version`)?

go version go1.16.7 linux/arm64

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

Alpine Linux, Edge

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/clayton/.cache/go-build"
GOENV="/home/clayton/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/clayton/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/clayton/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.16.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/foo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1367468762=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

```
$ cat main.go
package main

import "fmt"

func main() {
        fmt.Println("foo")
}

```

```
$ GOARCH=amd64 go build -buildmode=pie
```

### What did you expect to see?

exe using the correct loader for the taget arch

### What did you see instead?

```
$ file main
test: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-aarch64.so.1, Go BuildID=5pIV1wbPZ4pH6rm5vEN9/bGZw1QTL944QcT3btQaA/ziMAbLCwuKttrRi0Aq6r/C8Xufy3gwfIwLIPE6IQj, not stripped
```

Seems like the fix for https://github.com/golang/go/issues/45034 doesn't work when cross compiling, since the test there fails to use the cross compiler (?)

Note that the info here is from an arm64 system, but the same issue occurs on x86_64 when, e.g. `GOARCH=arm64` (it wrongly uses the path to a x86_64 loader)

**Comment by seankhliao** [comment] 2021-09-06 05:54
Duplicate of #47760

**Closed by seankhliao** 2021-09-06 05:54 UTC
