### ISSUE TITLE
golang.org/cl redirect leads to blank page for all CLs.

### ISSUE THREAD

**Issue by shurcooL** [golang/go#21240] opened 2017-07-31 18:51 UTC
I'm not sure if this is a temporary issue that's already being worked on (e.g. https://twitter.com/bradfitz/status/892055083092815874 aka #21237), or an unrelated legitimate issue. I'll report it so it can be triaged.

The following URL:

https://golang.org/cl/47352

Redirects to:

https://go-review.googlesource.com/c/gddo/%20/47352/

Which appears as a blank white page:

![image](https://user-images.githubusercontent.com/1924134/28792823-e3cf3d34-75fe-11e7-9738-29cec5519283.png)

Happens whether I'm logged in or in incognito window. I tried clearing all cache.

On the other hand, modifying the URL to:

https://go-review.googlesource.com/c/47352/

It works okay:

![image](https://user-images.githubusercontent.com/1924134/28792862-0b229534-75ff-11e7-90d1-5a9e3a62d230.png)

This seems to affect all CLs, not just gddo ones, as far as I can tell. E.g., https://golang.org/cl/50990 (main repo CL) and https://golang.org/cl/43812 (x/tools CL) are affected too.

I don't know if the issue is that the first URL should work, but doesn't, or that the golang.org/cl redirect should point to second URL directly. /cc @bradfitz

**Comment by dlsniper** [comment] 2017-07-31 18:53
duplicate of #21235 ?

**Comment by bradfitz** [comment] 2017-07-31 18:54
Yup.

**Comment by shurcooL** [comment] 2017-07-31 18:55
Yes, looks like a duplicate. I didn't find it because it's closed, but the issue isn't actually resolved yet. Maybe we should reopen it with an "external issue" label or something, and close when the actual issue is resolved (since it might take a few days)?

**Closed by bradfitz** 2017-07-31 18:54 UTC

**Comment by andybons** [comment] 2017-07-31 18:57
@broady is deploying soon

**Comment by broady** [comment] 2017-07-31 20:14
Deployed
