### ISSUE TITLE
x/crypto: crypto/ssh still uses insecure SHA1 by default, OpenSSH ending support soon

### ISSUE THREAD

**Issue by zrait** [golang/go#48216] opened 2021-09-06 19:27 UTC
The code in crypto/ssh/keys.go still uses insecure SHA1 signatures for RSA keys by default (unless the `SignWithAlgorithm` is called, but many codepaths such as `SignCert` will eventually call `Sign` which passes `""` to `SignWithAlgorithm`. OpenSSH is going to disable this signature scheme by default in the next release as noted [here](https://www.openssh.com/txt/release-8.7).

Since [OpenSSH 8.2](https://www.openssh.com/txt/release-8.2) `ssh-rsa` signatures have been disabled for certificate signatures and `ssh-keygen` has used `rsa-sha2-512` as the default for signing certificates.

I could submit a PR changing the signature function for RSA keys to be crypto.SHA512. 

I also think that it's probably worth updating the verification to disallow use of SHA1 verification by default.

**Comment by seankhliao** [comment] 2021-09-06 19:57
Duplicate of #37278

**Closed by seankhliao** 2021-09-06 19:57 UTC
