### ISSUE TITLE
x/tools/godoc: support multiple languages

### ISSUE THREAD

**Issue by dfang** [golang/go#32743] opened 2019-06-24 01:49 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### What did you expect to see?

currently when you write some comments in go code, godoc will generate a doc. this is very simple and straight.  but i think this is like ascii only for english speakers.

last weekend. a friend ask me for some go chinese documentation. i found there is no official documentations, there are translations, but it's complete, or maybe outdated.

for translations. one way is to for golang/go, translate in *.go source code. this is hard to keep up with upstream. another way is hacking godoc, add autoloading doc files like [this repo](https://github.com/golang-china/golangdoc) ....

this is not urgent but a nice to have feature. there are many more important things to do, but this should be taken it into consideration at least.

**Comment by agnivade** [comment] 2019-06-24 03:31
Can you explain what is "autoloading doc files" ? Your link does not work for me.

Are you suggesting that we should add translations for multiple languages, or just the ability for godoc to show comments from different languages ? How do you propose these new language strings be stored ?

**Comment by dfang** [comment] 2019-06-24 03:50
hi @agnivade,  updated the link. forgot to add https://

1. I don't know `autoloading doc files`,  just translated the term in description from the repo.  need to dig the source code.

2. adding ability for godoc to show comments from different languages is preferable, so both google and the community can do translations, and popular third party libs can benefit from that 

3. no idea, need more thinking :)

**Comment by beoran** [comment] 2019-06-27 06:41
This feature is important for teaching millions of non English speakers all around the world. Perhaps godoc could accept for every .go file there could be additional .go.doc files in a doc/<language code> subdirectory with the translations of the documentation for that language. The format could be something like the comments extracted from the normal go file, keyed by the first words.

**Comment by beoran** [comment] 2019-08-01 07:20
@agnivade Seeing the need for this felt by several of our users in China, as well as my own needs as a non native English speaker,  I think this issue should be given more priority. Currently it is too hard to use godoc to translate the Go documentation.

**Comment by agnivade** [comment] 2019-08-01 09:26
I am not exactly sure what you mean by "given more priority". This is an open issue and anybody is free to work on it. I am in no position to assign tasks to the Go team. But I will ping @dmitshur to check if this is something that can be brought in his radar.

On side note: https://github.com/golang/go/issues/22171 also tackles the `lang` attribute in the `html` tag.

**Comment by beoran** [comment] 2019-08-01 12:09
OK, thanks for notifying the right people and for the link.

**Comment by seankhliao** [comment] 2024-12-03 00:36
Duplicate of #57254

**Closed by seankhliao** 2024-12-03 00:36 UTC
Labels: NeedsInvestigation, FeatureRequest, FrozenDueToAge
