### ISSUE TITLE
cmd/gc: array slice return can produce wrong result

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#9537] opened 2015-01-08 21:39 UTC
In some circumstances, returning a slice of an array
can return erroneous results.

To reproduce the issue:

    go get github.com/rogpeppe/misc/bug/bug1
    bug1

I see
    failure: got 0200000000000000020000000000000018000000000000000000000000000000 want 0102030400000000000000000000000000000000000000000000000000000000

under go 1.3.3 and:

failure: got 00000000000000000000000000000000d838b409757f000008400308c2000000 want 0102030400000000000000000000000000000000000000000000000000000000

under go 1.4.

### package github.com/rogpeppe/misc/bug/bug1

	package main
	import (
		"fmt"
		"bytes"
		"github.com/rogpeppe/misc/bug/bug2"
	)
	
	type X struct {
		*bug2.X
	}
	
	type Intf interface {
		Get() []byte
	}
	
	func main() {
		x := &bug2.X{T: [32]byte{1,2,3,4}}
		var ix Intf = X{x}
		t1 := ix.Get()
		t2 := x.Get()
		if !bytes.Equal(t1, t2) {
			fmt.Printf("failure: got %x want %x", t1, t2)
		}
	}

### package github.com/rogpeppe/misc/bug/bug2/
	package bug2
	
	type X struct {
		T      [32]byte
	}
	
	func (x *X) Get() []byte {
		t := x.T
		return t[:]
	}

**Comment by minux** [comment] 2015-01-08 22:12
This bug seems to be introduced in the Go 1.1 development cycle.
Still bisecting.

**Comment by minux** [comment] 2015-01-08 22:21
It's introduced in this CL https://golang.org/cl/7214044.

**Comment by minux** [comment] 2015-01-08 22:24
Temporary workaround: -gcflags -l.

Because it's a not 1.4 regression, I think we don't need to fix it in 1.4.1
?

**Comment by bradfitz** [comment] 2015-01-08 22:26
Maybe. But it's also a pretty bad correctness bug and now that we know about it, it's pretty bad to keep shipping it. I'll let @rsc decide.

**Comment by ianlancetaylor** [comment] 2015-01-09 00:02
Let's see how invasive the patch is.

**Comment by minux** [comment] 2015-01-10 00:22
The problem is that the wrapper main.X.Get is allocating
t on stack, rather on heap, despite the fact that t obviously
escapes. (so the result of Get is a slice pointer to our own
stack. we can use this fact to corrupt the Go stack, and
even worse, violate the safety by overriding pointers on
stack to point to arbitrary locations, this is indeed a very
serious issue.) Simply put, I can use this bug to write a
pure Go function that turns an arbitrary uintptr to a pointer
without using unsafe or cgo. And you can also do arbitrary
pointer type conversion using reflect. (Because every
function/method declared in the same package will be in
xtop when doing escape analysis, I'm unable to write a
single package example, at least two packages are required
to trigger the bug.)

I played with this issue for quite some time and found no
simple and obviously safe solution than to disable the
inlining of wrappers. (one line change, remove inlcall(fn)
line in the genwrapper function in cmd/gc/subr.c)

When inlining is first introduced, we first do inlining and
then do escape analysis. This is the correct way.

As the backend will allocate any var not explicitly labeled
as escaped to heap on stack, it's utterly important to
run escape analysis on every function.

The CL (7214044) violates the order of inlining first and
escape analysis, and after its submission, we found #5056,
and this issue is actually another occurrence of #5056.

The fix to #5056 made the assumption that there is
escape analysis result on the copied nodes saved for
inlining.  this is true for the example program for #5056, but
unfortunately, not true for the example in this issue.

**Comment by minux** [comment] 2015-01-11 22:32
More preliminary results:

The reason the fix to #5056 doesn't fix this issue is that
the function comes from imported functions, so it's not
on xtop, but in importlist. And also, it doesn't have nbody,
as its body is saved in inl.

However, the imported functions are incomplete in that
they don't have PPARAMOUTs in their dcl list, so we can't
just call escapes(importlist). (After fixing the ONAME to be
OFUNCDCL).

We can't do escape analysis at genwrapper after inlcalls
either without changing the escape analysis code a lot.

For example, escape analysis makes the assumption that
it won't analyze functions that have already been analyzed,
but this isn't true here.

The escape analysis code can't handle temporary assignment
in ORETURN (it assumes every assignment in ORETURN is
to the PPARAMOUT). But it's possible here, as the bufio
package has this kind of RETURN node:
.   RETURN l(154) tc(1)
.   RETURN-list
.   .   AS l(154) tc(1)
.   .   .   NAME-bufio.autotmp_0041 u(1) a(1) l(154) x(0+0) class(PAUTO)
esc(N) tc(1) error
.   .   .   NAME-bufio.ErrNegativeCount u(1) a(1) l(25) x(0+0)
class(PEXTERN) tc(1) used(1) error

.   .   AS u(2) l(154) tc(1)
.   .   .   NAME-bufio.discarded u(1) a(1) g(1) l(152) x(16+0)
class(PPARAMOUT) f(1) tc(1) used(1) int
.   .   .   LITERAL-0 u(1) a(1) l(154) tc(1) int

.   .   AS u(2) l(154) tc(1)
.   .   .   NAME-bufio.err u(1) a(1) g(2) l(152) x(24+0) class(PPARAMOUT)
f(1) tc(1) used(1) error
.   .   .   NAME-bufio.autotmp_0041 u(1) a(1) l(154) x(0+0) class(PAUTO)
esc(N) tc(1) error

I haven't explored the possibilities of moving genwrappers
before the main escapes(xtop) yet. That should be the most
correct solution.

**Comment by rsc** [comment] 2015-01-14 03:43
This bug was present in Go 1.3 and the CL that introduced the bug is nearly two years old. That suggests that the failure conditions are rare enough that we can wait a bit longer to fix it. The CL that introduced the bug also shows actual library functions (sort.Strings) getting 30% faster, which is not something to roll back lightly.

I am not sure what you are saying about bufio exactly, but the code you found is in Brad's new method that didn't ship in 1.4.

If someone can show me a trivial fix that isn't "roll it back" we can consider it for Go 1.4.2. And unless Rog speaks up and argues that it's important to fix, we can leave it for Go 1.5.

**Comment by ianlancetaylor** [comment] 2015-01-21 00:01
Hacky workaround: https://go-review.googlesource.com/3081 .

**Comment by ianlancetaylor** [comment] 2015-01-21 07:10
This time for sure: https://go-review.googlesource.com/3092 .

**Closed** 2015-01-22 03:27 UTC
Labels: compiler-bug
