### ISSUE TITLE
net: TestLookupDotsWithRemoteSource failing with `lookup 8.8.8.8.in-addr.arpa. on 169.254.169.254:53: server misbehaving`

### ISSUE THREAD

**Issue by prattmic** [golang/go#64937] opened 2024-01-02 19:59 UTC
```
#!watchflakes
post <- pkg == "net" && test == "TestLookupDotsWithRemoteSource"
```

This test seems to be failing more-or-less continuously on various builders, though it does not reproduce locally for me.

e.g., https://ci.chromium.org/ui/p/golang/builders/try-workers/go1.21-linux-386-test_only/b8759984261243042673/test-results?sortby=&groupby=

```
=== RUN   TestLookupDotsWithRemoteSource
    lookup_test.go:666: LookupAddr(8.8.8.8): lookup 8.8.8.8.in-addr.arpa. on 169.254.169.254:53: server misbehaving (mode=go)
--- FAIL: TestLookupDotsWithRemoteSource (1.36s)
```

cc @neild @ianlancetaylor

**Comment by mateusz834** [comment] 2024-01-02 20:08
@prattmic https://github.com/golang/go/issues/27992#issuecomment-1872480413

**Comment by prattmic** [comment] 2024-01-02 20:12
@mateusz834 Ah, thanks for the pointer and for investigating this! It seems like this was an upstream DNS issue that is now fixed. I'm still seeing issues as recently as 15 minutes ago, but perhaps those will self-resolve as caches expire.

**Comment by bcmills** [comment] 2024-01-02 20:22
Yeah, this looks to me like a duplicate of #27992. The test is unfortunately _very_ non-hermetic.

**Comment by prattmic** [comment] 2024-01-02 20:27
Duplicate of https://github.com/golang/go/issues/27992.

**Comment by dmitshur** [comment] 2024-05-30 21:05
Closing as a duplicate of #27992 again, and taking it out of Test Flakes project so it doesn't get reopened.

**Closed by dmitshur** 2024-05-30 21:05 UTC
Labels: NeedsInvestigation, release-blocker
