### ISSUE TITLE
cmd/compile: internal compiler error: child dcl collision on symbol _geffa within

### ISSUE THREAD

**Issue by hnlq715** [golang/go#44448] opened 2021-02-20 10:29 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/liqi/.cache/go-build"
GOENV="/home/liqi/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/liqi/go/pkg/mod"
GONOPROXY="git.dz11.com"
GONOSUMDB="git.dz11.com"
GOOS="linux"
GOPATH="/home/liqi/go"
GOPRIVATE="git.dz11.com"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/home/liqi/workspace/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/home/liqi/workspace/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3432493516=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

go get github.com/unidoc/unidoc-examples/compress

### What did you expect to see?

no error

### What did you see instead?

```
# github.com/unidoc/unipdf/v3/model
<autogenerated>:1: internal compiler error: child dcl collision on symbol _geffa within "".(*PdfAppender).replaceObject


Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
```

**Comment by tmthrgd** [comment] 2021-02-20 10:48
This is a duplicate of #44378.

**Comment by ALTree** [comment] 2021-02-20 10:59
Closing as a dup of #44378.

**Closed by ALTree** 2021-02-20 10:59 UTC
