### ISSUE TITLE
cmd/go: Go builds C archives with absolute addressing on darwin/arm

### ISSUE THREAD

**Issue by swisspol** [golang/go#12681] opened 2015-09-18 21:10 UTC
> Go 1.5.1 on OS X 10.10.5 with Xcode 7

It appears Go builds c archives with absolute addressing, which makes Xcode unhappy when using the resulting static library in a project:
```
(null): PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in __cgoexp_45a75e65c81e_Test from build/iphoneos/main.a(go.o). To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie
```

I made a sample test project here: https://github.com/swisspol/Go-Bridge

**Comment by albertjin** [comment] 2015-09-20 07:02
I think it is the same issue for iOS built by gomobile.

**Comment by rakyll** [comment] 2015-09-21 22:01
This has been recently fixed via https://github.com/golang/go/issues/12590, will be available in Go 1.6.

**Comment by crawshaw** [comment] 2015-10-15 23:22
Hi @swisspol, I'm sorry I missed this issue. It is not the same as #12590. It is however closely related to #12896. I have a fix, but won't have access to the appropriate hardware to test it until tomorrow.

**Comment by rsc** [comment] 2015-11-05 01:15
ping @crawshaw

**Comment by crawshaw** [comment] 2015-11-05 14:30
To consolidate these, I'm marking this a duplicate of #12896.

darwin/arm64 is all PIC.
darwin/arm still has absolute text relocations, and probably will in 1.6

(I haven't managed to convince ld64 to make PC-relative relocations to .bss work.)

**Closed by crawshaw** 2015-11-05 14:30 UTC
