### ISSUE TITLE
encoding/json: Unmarshal. Expected type string -> found int.

### ISSUE THREAD

**Issue by eloyucu** [golang/go#26928] opened 2018-08-10 23:47 UTC
Hi everyone.

This issue is about the json package, concretely the Unmarshal function.

My version of go: 1.10.2 windows/amd and the go env is not relevant because it happens too on play.golang.org (see the link with the example here: https://play.golang.org/p/NGoR7Vs-VxX ).

The problem I am finding is that I am receiving a json that includes an array like this:

```
[
  {
    "key": "accept-encoding",
    "value": "gzip, deflate"
  },
  {
    "key": "content-length",
    "value": 1377
  }
]
```

My question is... why should `value` field be a interface type?? I mean... every number can be converted to string without any problem... so, why can´t I use string as type and the json decoder makes responsible to realize the conversion (if it is necessary)??

I have been diving a little on the code of the decode file, and... in this line:

https://github.com/golang/go/blob/5c11480631f5654e9e6937ff08c453660138c64d/src/encoding/json/decode.go#L984

removing the second condition of the if (`&& v.Type() == numberType`) works for me. I guess it is a security statement or maybe something important that I don´t understand. But... when does v.Type() will be different than v.Kind()?? or... when does the v.Kind() will be a string and the v.Type() a json.Number??

Thanks in advance.

PS: Finally I found this solution using `UnmarshalJSON` function: https://play.golang.org/p/egqc6KJK1-t but I would want to know the reason of the non-autoconversion.

**Comment by agnivade** [comment] 2018-08-11 04:16
Hi @eloyucu ,

This appears to be a question rather than a Go bug. We do not use the issue tracker for general discussions or questions like these. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please feel free to reach out to the forums in the [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.

Closing since this is not a bug.

**Closed by agnivade** 2018-08-11 04:16 UTC
