### ISSUE TITLE
os.Notify not work with kill command but with Ctrl+c on osx

### ISSUE THREAD

**Issue by xuxiangyang** [golang/go#15553] opened 2016-05-05 07:26 UTC
#Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

```
go version go1.6.2 darwin/amd64
```
2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xxy/Documents/go_project"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="0"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

I run the [gist](https://gist.github.com/reiki4040/be3705f307d3cd136e85) 
I press Control+c, output is `Warikomi`
Then I run the command ` kill -SIGINT $PID` (PID is the process pid),  no output

`kill -SIGTERM $PID ` the process ternimated

4. What did you expect to see?

when I run `kill -SIGTERM $PID`, it should output `Warikomi`

5. What did you see instead?

no output

**Comment by minux** [comment] 2016-05-05 07:34
Please show a standalone sample program and how to reproduce
the program (the kill command you use).

Also note that kill -9 (SIGKILL) can't be caught by processes.

**Comment by xuxiangyang** [comment] 2016-05-05 09:40
the code is
```
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"
)

func main() {
	signal_chan := make(chan os.Signal, 1)
	signal.Notify(signal_chan,
		syscall.SIGHUP,
		syscall.SIGINT,
		syscall.SIGTERM,
		syscall.SIGQUIT)

	exit_chan := make(chan int)
	go func() {
		for {
			s := <-signal_chan
			switch s {
			// kill -SIGHUP XXXX
			case syscall.SIGHUP:
				fmt.Println("hungup")
				
			// kill -SIGINT XXXX or Ctrl+c
			case syscall.SIGINT:
				fmt.Println("Warikomi")
				
			// kill -SIGTERM XXXX
			case syscall.SIGTERM:
				fmt.Println("force stop")
				exit_chan <- 0
				
			// kill -SIGQUIT XXXX
			case syscall.SIGQUIT:
				fmt.Println("stop and core dump")
				exit_chan <- 0
				
			default:
				fmt.Println("Unknown signal.")
				exit_chan <- 1
			}
		}
	}()

	code := <-exit_chan
	os.Exit(code)
}
```
run the code, and find the pid, such as 1992
command 

```
kill -SIGINT 1992
```

**Comment by minux** [comment] 2016-05-05 09:53
What do you expect and what did you get instead?

When running on my system and kill -SIGINT $PID, the program
prints "Warikomi" and continues running, which looks good to me.

**Comment by xuxiangyang** [comment] 2016-05-05 11:02
I expect to see that it print "Warikomi" but It do nothing~

**Comment by xuxiangyang** [comment] 2016-05-05 11:04
I use go run, it create to process like this
```
xxy             58193   0.0  0.0 573375368   1264 s015  S+    7:02PM   0:00.00 /var/folders/bt/wq6vgz511576mz4l7_4m075c0000gn/T/go-build247179261/command-line-arguments/_obj/exe/test
xxy             58162   0.0  0.1 573406976   9220 s015  S+    7:02PM   0:00.04 go run test.go
```

it not work when i  kill 58162 , but work if I kill 58193~

**Comment by ianlancetaylor** [comment] 2016-05-05 14:03
This is working as expected.  `go run` builds the Go program and then runs it in a subprocess.  If you use the `kill` command on the `go run` process, you are just killing that process.  `go run` is a convenience command; it's not intended to do things like catch signals and pass them on to the child process.  Use `go build` or `go install` and run the process directly.

I'm going to close this as expected.  Please feel free to reopen if you disagree.

**Closed by ianlancetaylor** 2016-05-05 14:03 UTC
