### ISSUE TITLE
os: nonzero exit status mishandled on OpenBSD before 009_exit syspatch

### ISSUE THREAD

**Issue by bcmills** [golang/go#42542] opened 2020-11-12 14:42 UTC
`cmd/go` calls `os.Exit` with a nonzero status code on failure:
https://github.com/golang/go/blob/0e953add9656c32a788e06438cd7b533e968b7f8/src/cmd/go/internal/base/base.go#L102

The `cmd/go` tests use `os/exec` to execute subprocesses, and check them for the expected exit status:
https://github.com/golang/go/blob/e75aef80ca3722684e707502c424c0fb28e8b1cc/src/cmd/go/script_test.go#L1183

Tests that expect nonzero exit status are failing frequently on the `openbsd-arm64-jsing` builder (CC @4a6f656c), which suggests that either `os.Exit` is not consistently causing the process to exit with the correct status, or `(*os.Process).Wait` is not consistently reporting the correct status.

It is not clear to me whether this is a bug in the Go standard library or the OpenBSD kernel.

<details>

[2020-11-12T10:22:50-d7974c3/openbsd-arm64-jsing](https://build.golang.org/log/52eb14acc7bb3a8557c910a48ddfc8ddcb5e23d3)
[2020-11-11T20:51:00-141fa33/openbsd-arm64-jsing](https://build.golang.org/log/9b99277352ca8a975b3cfbe7d57a4d3fda5e418d)
[2020-11-10T18:03:53-1948c00/openbsd-arm64-jsing](https://build.golang.org/log/81a54c39132819d35f96320fc689a8dea84435bf)
[2020-11-10T04:11:42-1642cd7/openbsd-arm64-jsing](https://build.golang.org/log/133b78009a803ffb2f2127166cea745778bd240f)
[2020-11-09T21:36:24-d361691/openbsd-arm64-jsing](https://build.golang.org/log/c23ebf5eca47ed3b81a7a12f91ab769960201f3a)
[2020-11-09T21:03:36-d495712/openbsd-arm64-jsing](https://build.golang.org/log/a1c7a68014cf25e93b13effd104dd9743b0f7ac6)
[2020-11-09T19:00:00-01cdd36/openbsd-arm64-jsing](https://build.golang.org/log/227378feab32ca16ee8bfc1b8cc0591efa1d309d)
[2020-11-09T17:38:50-a6462a6/openbsd-arm64-jsing](https://build.golang.org/log/094821fe8539680bb036a928db891185304ab2f9)
[2020-11-09T13:12:41-2231243/openbsd-arm64-jsing](https://build.golang.org/log/314cc7dcdcd29b6aa0aaabaae138f7f3bc41dc96)
[2020-11-07T16:59:55-5e371e0/openbsd-arm64-jsing](https://build.golang.org/log/951d4b5428fa4b4fc22bb1d3af61628f5e87f799)
[2020-11-07T03:52:47-d51ae66/openbsd-arm64-jsing](https://build.golang.org/log/1b4a9d6841be693350288fb28ccf5d6f218e53b5)
[2020-11-06T19:42:05-362d25f/openbsd-arm64-jsing](https://build.golang.org/log/7a56ba9b14b96f3872ee333e3ddb5e31f6c8f5fe)
[2020-11-06T15:33:23-d21af00/openbsd-arm64-jsing](https://build.golang.org/log/f9dba4ec24487ae78038284a2f3300cfb8f44569)
[2020-11-05T23:21:33-ecc3f51/openbsd-arm64-jsing](https://build.golang.org/log/54b08adb6ecddf90b18718fd3f01588ed12b86d9)
[2020-11-05T22:14:40-8e5778e/openbsd-arm64-jsing](https://build.golang.org/log/697bbdf4606a9796e30f3b1bb95fb5772226a9bf)
[2020-11-05T17:52:17-06538fa/openbsd-arm64-jsing](https://build.golang.org/log/d18d5f4ba6d6c310a247a737e16c761f1e79ffd8)
[2020-11-05T16:47:45-a19a4dc/openbsd-arm64-jsing](https://build.golang.org/log/1a4ff40ca73063ae177861b512f4ace070a21b85)
[2020-11-05T16:47:18-0c86172/openbsd-arm64-jsing](https://build.golang.org/log/17b722df92de112cc659333babde16f72aee8548)
[2020-11-05T16:46:56-04b5b4f/openbsd-arm64-jsing](https://build.golang.org/log/a34d5d496e028e73fb3b6265e53ef989d1c3d302)
[2020-11-05T16:43:34-40f0359/openbsd-arm64-jsing](https://build.golang.org/log/de978ce4791349f5b1335776c9b52125f3a31cbf)
[2020-11-05T16:20:01-8ab8125/openbsd-arm64-jsing](https://build.golang.org/log/b8fec8a0634abea2a313f4e8eef77ba3cd84b56a)
[2020-11-05T14:54:35-74ec40f/openbsd-arm64-jsing](https://build.golang.org/log/c6c623dafa3ab28d13d5a3e513646c6e8d4c07b9)
[2020-11-05T10:46:08-3510a1e/openbsd-arm64-jsing](https://build.golang.org/log/75f9f3a4b865c5de87987a0c34a7471768ccd018)
[2020-11-05T02:28:14-1e3b535/openbsd-arm64-jsing](https://build.golang.org/log/465809a6468cf86697155fa52a719b5e88c0ba78)
[2020-11-05T00:21:39-c018eec/openbsd-arm64-jsing](https://build.golang.org/log/51fcf47abfa8295606c5fd43bce02abda5f6e79e)
[2020-11-04T21:02:29-e4b4e4b/openbsd-arm64-jsing](https://build.golang.org/log/7382abe336a772204e30e5ea1eb872213b3706aa)
[2020-11-03T23:05:51-e1b305a/openbsd-arm64-jsing](https://build.golang.org/log/2ba992d9cc5f87793fba39dd10665f432ee3f30f)
[2020-11-03T21:43:30-da7aa86/openbsd-arm64-jsing](https://build.golang.org/log/a96385466b9d4f4cc14f8065b98748cb11527f2f)
[2020-11-03T01:27:45-cc0930c/openbsd-arm64-jsing](https://build.golang.org/log/4c59e9e6ca4b4bc311b0d048ba9f53f8fbbd74e0)
[2020-11-02T21:10:41-ac766e3/openbsd-arm64-jsing](https://build.golang.org/log/ebd8175e693cc87d0b84dcf5b6d106a038b8bb4b)
[2020-11-02T21:08:14-4fcb506/openbsd-arm64-jsing](https://build.golang.org/log/9c077b145302a4fdb0d01292fd1f79eaad72d492)
[2020-11-02T15:41:00-33d9251/openbsd-arm64-jsing](https://build.golang.org/log/6b3352b9fb8dbe69871acec8581b1998d1e0e825)
[2020-11-02T15:40:28-202aa08/openbsd-arm64-jsing](https://build.golang.org/log/7c96c680458c33ab7b06a6f5aad920d863cef7b8)
[2020-10-31T00:17:28-07e4f0f/openbsd-arm64-jsing](https://build.golang.org/log/7cc8b601d8d4c8bbb068eef0318bb50b35e1e037)
[2020-10-30T21:14:09-f96b62b/openbsd-arm64-jsing](https://build.golang.org/log/c4e0e1ba9fc15f7cb024da89f1b8beed6ac2cbf7)
[2020-10-29T19:06:32-5cc43c5/openbsd-arm64-jsing](https://build.golang.org/log/193577224e123281f2ee78c90aab69f39eaf7848)
[2020-10-29T01:50:09-308ec22/openbsd-arm64-jsing](https://build.golang.org/log/53e8c18de64fe9843ad44140ddb078cb3b9e6b73)
[2020-10-28T19:19:18-1090f09/openbsd-arm64-jsing](https://build.golang.org/log/cb67714e0fb9cd3b2b0cb35eb35749554be0050d)
[2020-10-28T17:10:08-642329f/openbsd-arm64-jsing](https://build.golang.org/log/2d75a28fa864541d8dbc8692f0018584ccd440d5)
[2020-10-28T05:02:44-150d244/openbsd-arm64-jsing](https://build.golang.org/log/e42a0879ffd28ec9decf2daa280b7aa54e730549)
[2020-10-17T19:22:49-30119bc/openbsd-arm64-jsing](https://build.golang.org/log/f7b8c7691588b1e73e66289ab93ef955213bb496)

</details>

**Comment by bcmills** [comment] 2020-11-12 14:43
@golang/release, you might consider marking this builder with a KnownIssue until this is resolved. Based on the status of #31656, it appears that this port is incomplete and not yet supported.

**Comment by 4a6f656c** [comment] 2020-11-12 18:32
> @golang/release, you might consider marking this builder with a KnownIssue until this is resolved. Based on the status of #31656, it appears that this port is incomplete and not yet supported.

FWIW the port is complete (has been for a long time) - the only reason it is not yet supported was due to the lack of a builder, which has now been addressed.

Re this specific issue, the failures are all `TestScript`... a couple of interesting things to note - firstly, this seems to have started when the builder was upgraded and some of the binaries were not (which I've just fixed). Having said that, I'm pretty sure that some of the `TestScript` tests are relying on the local Go binary (`/usr/local/go/bin/go` in this case), rather than the Go binary that has been built from source (probably not what we want):

```
$ kdump -HT | grep NAMI | grep bin/go 
 28299/455478  go.test  1605204346.818164 NAMI  "/usr/local/go/bin/go"
 29314/257479  go.test  1605204346.830077 NAMI  "/usr/local/go/bin/go"
 29314/257479  go       1605204346.875199 NAMI  "/usr/local/go/bin/go"
 53698/463669  go.test  1605204346.973705 NAMI  "/usr/local/go/bin/go"
 98216/426375  go.test  1605204347.116089 NAMI  "/usr/local/go/bin/go"
 59520/594260  go.test  1605204347.253691 NAMI  "/usr/local/go/bin/go"
...
 | | |-+= 60121 joel ./go.test -test.run=TestScript
 | | | |-+- 72510 joel /tmp/cmd-go-test-091599085/tmpdir936823144/testbin/go test -v multimain
 | | | | \--- 01312 joel (vet)
 | | | |-+- 26114 joel /tmp/cmd-go-test-091599085/tmpdir936823144/testbin/go build rsc.io/CGO
 | | | | \--- 51018 joel cc -I /tmp/cmd-go-test-091599085/tmpdir936823144/script-mod_case_cgo/gopath/pkg/mod/rsc.io/!c!g!o@v1.0.0 -fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/t
 | | | |--- 59076 joel /tmp/cmd-go-test-091599085/tmpdir936823144/testbin/go vet m/onlycgo
 | | | \-+- 30712 joel /tmp/cmd-go-test-091599085/tmpdir936823144/testbin/go install main_test
 | | |   \--- 38529 joel /usr/local/go/pkg/tool/openbsd_arm64/link -o /tmp/cmd-go-test-091599085/tmpdir936823144/script-test_main_archive/tmp/go-build539908792/b001/exe/a.out -importcfg /tmp/cmd-go-test-091599085/tmpdir93682314
```

If my suspicion is correct, this will clear as the next builds occur.

**Comment by 4a6f656c** [comment] 2020-11-13 14:02
Interesting - the OpenBSD 6.8 openbsd/386 and openbsd/amd64 new builders are showing the same symptoms, so this is presumably not openbsd/arm64 specific.

**Comment by 4a6f656c** [comment] 2020-11-16 16:04
I've confirmed that this is an issue with the OpenBSD kernel - a fix has been manually applied to the openbsd/arm64 builder and I'm hoping that a syspatch can be made available for it soon.

**Comment by 4a6f656c** [comment] 2020-12-10 15:32
@dmitshur OpenBSD have released an [errata](https://ftp.openbsd.org/pub/OpenBSD/patches/6.8/common/009_exit.patch.sig) for this issue - this should be picked up via syspatch if the OpenBSD 6.8 builder images are recreated.

**Comment by dmitshur** [comment] 2020-12-10 16:12
@4a6f656c Thank you for letting me know. I'll create new versions of the `openbsd-amd64-68` and `openbsd-386-68` images, and post an update in #35712.

**Comment by dmitshur** [comment] 2020-12-22 23:11
I understand this should be resolved via the 009_exit syspatch. Can this issue be closed, or is there more left to do here?

**Comment by 4a6f656c** [comment] 2021-01-22 19:15
> I understand this was determined to be an issue in the OpenBSD kernel, which should be resolved via the 009_exit syspatch. Can this issue be closed, or is there more left to do here?

@dmitshur - correct, as far as I'm concerned this can be closed.

**Closed** 2021-01-22 20:13 UTC
Labels: NeedsInvestigation, OS-OpenBSD

**Comment by dmitshur** [comment] 2021-01-22 20:15
Thank you for your work on this Joel, and Bryan for catching and reporting the issue.
