### ISSUE TITLE
cmd/compile: ICE on invalid conversion of untyped expression

### ISSUE THREAD

**Issue by mdempsky** [golang/go#33308] opened 2019-07-26 21:37 UTC
cmd/compile panics with an ICE on this (invalid) input:

```
package p

var v uint
var x = []byte((1 << v) + 1)
```

For comparison, go/types emits `cannot convert (1 << v) + 1 (untyped int value) to []byte`, while gccgo emits `invalid context-determined non-integer type for left operand of shift`.

Self-assigning for now since I'm working on [CL 187657](https://go-review.googlesource.com/c/go/+/187657), which doesn't currently fix this, but I expect can easily be made to.

**Comment by cuonglm** [comment] 2019-10-16 19:24
@mdempsky CL 187657 seems to fix this issue already, go tip now reports:

```
p.go:4:15: cannot convert 1 << v + 1 (type int) to type []byte
```

**Comment by mdempsky** [comment] 2019-10-16 22:22
@cuonglm Interesting, thanks for pointing that out.

**Comment by ALTree** [comment] 2020-07-20 11:24
Unless I've misunderstood the discussion above, it seems that this issue can be closed, since the crash on the reproducer is now fixed. @mdempsky is that correct?

**Comment by mdempsky** [comment] 2020-07-20 16:14
@ALTree I think so. A regress test would be good though.

**Closed** 2020-07-20 18:19 UTC
Labels: NeedsFix

**Comment by mdempsky** [comment] 2020-07-20 18:31
Oops, I thought tree was already unlocked for the next release cycle. I think a simple regress test should be fine though.
