### ISSUE TITLE
go/types: types.CheckExpr returns error when 'FuncType' ast.Expr has TypeParams

### ISSUE THREAD

**Issue by csgura** [golang/go#65898] opened 2024-02-23 07:57 UTC
### Go version

go1.22 

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/gura/Library/Caches/go-build'
GOENV='/Users/gura/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/gura/go/pkg/mod'
GONOPROXY='*.uangel.com'
GONOSUMDB='*.uangel.com'
GOOS='darwin'
GOPATH='/Users/gura/go'
GOPRIVATE='*.uangel.com'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.22.0/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.22.0/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/gura/git/fp/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/mr/dvhjg7zd4l125pln73bqyr400000gp/T/go-build857521387=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### What did you do?

https://go.dev/play/p/ZPv6Er1H6K3

### What did you see happen?

error 'undefined: A' is returned

### What did you expect to see?

In Go version 1.21, there were no errors

**Comment by prattmic** [comment] 2024-02-23 18:39
cc @griesemer @findleyr

**Comment by griesemer** [comment] 2024-02-23 19:05
Hm, this does indeed look like a regression.
More compact reproducer (may be used a test case in fix): https://go.dev/play/p/XZWMNTkAOHo

**Comment by griesemer** [comment] 2024-02-26 21:20
This is actually working as intended; the fact that the code worked for 1.21 was a bug in 1.21 which was fixed by [CL 544035](https://go.dev/cl/544035).

Evaluating the function type expression in your [code](https://go.dev/play/p/ZPv6Er1H6K3) (line 16) requires that the type parameters (here `A`) are in scope. They are not in scope at the start of the function type, but certainly after the function type. You can make your example work by changing the position provided in line 16 to the end position ([example](https://go.dev/play/p/G6kA2XTjVgh)). With that change, the example works and prints OK.

So not a release blocker and not a bug. Will close with a test case for future reference.

**Closed** 2024-02-26 21:32 UTC
Labels: NeedsInvestigation
