### ISSUE TITLE
x/pkgsite: examples should run using the same version as the docs

### ISSUE THREAD

**Issue by rogpeppe** [golang/go#50769] opened 2022-01-24 10:13 UTC
When running an example within a package, I just noticed that the example does not run using the version that's being shown in the doc page.

Here's a screenshot that demonstrates the issue. The example, which compiles fine, fails to run because it uses a feature of the API that's not in the "latest" tag (v0.0.9). ISTM that the playground code within a particular version should be pinned to exactly that version (v0.0.10-0.20220124095424-0da3c8f5f56c in this case). I saw this issue here: https://pkg.go.dev/github.com/rogpeppe/retry@v0.0.10-0.20220124095424-0da3c8f5f56c.

![image](https://user-images.githubusercontent.com/66491/150763260-4e10dc82-d7ac-48be-9a05-49e558e0681e.png)

**Comment by seankhliao** [comment] 2022-01-24 12:05
dup of #46689 ?

**Comment by rogpeppe** [comment] 2022-01-24 15:06
@seankhliao Thanks for bringing that issue up - I wasn't aware of it. Although it does seem to be the same underlying problem, I'd say that issue wasn't framed correctly. Pre-release version or not, I believe that any example should run in the context of the version that is being documented. Using the latest version is not appropriate for any version that isn't the latest version, and that applies doubly so when the major version is zero and backward compatibility is not guaranteed.

**Comment by jamalc** [comment] 2022-01-31 18:44
The playground supports specifying module versions with an inline mod file. See [this example](https://go.dev/play/p/MngRpSKACGX). Maybe for documentation pages we could place an inline mod file into each example.

**Comment by rogpeppe** [comment] 2022-02-01 10:05
@jamalc Yes, that's exactly the kind of thing I was thinking of.

**Comment by dle8** [comment] 2022-10-25 16:51
The problem is resolved in https://go.dev/cl/444455. Thanks @jamalc for the help!

**Closed by dle8** 2022-10-25 16:51 UTC
Labels: NeedsInvestigation, pkgsite
