### ISSUE TITLE
x/mobile: failed to pull the signing certificate to determine your team ID

### ISSUE THREAD

**Issue by pierrec** [golang/go#42743] opened 2020-11-20 09:52 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

gomobile build -target=ios -bundleid=XXX golang.org/x/mobile/example/basic

### What did you expect to see?

No output meaning that the app was built.

### What did you see instead?

gomobile: failed to pull the signing certificate to determine your team ID: exit status 44

**Comment by pierrec** [comment] 2020-11-20 09:53
https://go-review.googlesource.com/c/mobile/+/271926

**Comment by cagedmantis** [comment] 2020-12-07 15:46
Seems like a duplicate of #42615. I won't close it since it has an associated CL.

/cc @hyangah

**Comment by changkun** [comment] 2021-08-31 15:24
This should be fixed in [CL 346151](https://go-review.googlesource.com/c/mobile/+/346151). We may close it directly.

(Sorry for not referring to it directly in the CL.)

cc @dmitshur @hajimehoshi  @cagedmantis

**Comment by hajimehoshi** [comment] 2021-08-31 15:37
Thanks!

**Closed by hajimehoshi** 2021-08-31 15:37 UTC
Labels: NeedsInvestigation, mobile
