### ISSUE TITLE
cmd/gc: return result not visible in defer

### ISSUE THREAD

**Issue by rsc** [golang/go#9738] opened 2015-01-30 15:53 UTC
https://go-review.googlesource.com/#/c/3620/ should not be necessary, but it is.
I have been unable to reproduce with a smaller test case.

**Comment by minux** [comment] 2015-01-31 07:17
A simple demo: http://play.golang.org/p/TVi807H5e4
```
package main

type T struct{}

func F() (t *T) {
	defer func() {
		if t == nil {
			panic("t is nil!")
		}
	}()
	return &T{}
}

func main() {
	F()
}
```

This is most probably caused by the capture closure variable
by value CL.

**Comment by minux** [comment] 2015-01-31 07:55
A even simpler case:
```
package main

func F() (x int) {
        defer func() {
                if x != 42 {
                        println("BUG: x =", x)
                }
        }()
        return 42
}

func main() {
        F()
}
```

This is because the return statement doesn't mark the PARAMOUT
nodes as having been assigned to.

Sent https://golang.org/cl/3690.

**Closed** 2015-02-02 14:15 UTC
