### ISSUE TITLE
proxy.golang.org: problem with ppc64le builds while using docker/build-push-action

### ISSUE THREAD

**Issue by jauderho** [golang/go#50703] opened 2022-01-19 23:02 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

This problem applies only to ppc64le

</pre></details>

### What did you do?

While using the docker/build-push-action, I noticed that I am getting consistent but random errors while trying to build ppc64le images. I have my actions set up to build multi-platform builds but I only ever seem to get failures when trying to build ppc64le images. 

I have an issue on my dockerfiles repo tracking this: https://github.com/jauderho/dockerfiles/issues/69

For example, I try to build images for the following platforms:  linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/s390x,linux/ppc64le

linux/ppc64le is the only one that seems to consistently have errors. 

Example:
- https://github.com/jauderho/dockerfiles/runs/4856366355?check_suite_focus=true#step:8:1306

### What did you expect to see?

No errors

### What did you see instead?

See https://github.com/jauderho/dockerfiles/runs/4856366355?check_suite_focus=true#step:8:1306

Errors of the form `net/http: TLS handshake timeout`

Link to the build history: https://github.com/jauderho/dockerfiles/actions/workflows/fq.yml

If I rerun the GHA, sometimes it'll magically resolve itself. I'd like to be able to consistently build linux/ppc64le images.

**Comment by seankhliao** [comment] 2022-01-19 23:32
Duplicate of #50584

**Closed by seankhliao** 2022-01-19 23:32 UTC
