### ISSUE TITLE
Slow to build

### ISSUE THREAD

**Issue by anacrolix** [golang/go#12804] opened 2015-10-01 11:40 UTC
Builds are becoming relatively slow. Using go version go1.5.1 darwin/amd64, my build (presumably mostly link) time is:

real	0m2.879s
user	0m3.584s
sys	0m0.461s

For a very modest program. Building with -x shows that compile, and link are running only for the main package, which contains no fancy build directives.

I'm not sure how else to report this, but it is a concern that build times are inflating version over version.

**Comment by Thomasdezeeuw** [comment] 2015-10-01 12:04
It's a know issue from converting the compiler from C to Go code. See https://github.com/golang/go/issues/10765, https://github.com/golang/go/issues/10571.

**Comment by rakyll** [comment] 2015-10-01 14:28
Duplicate of https://github.com/golang/go/issues/10571.

**Closed by rakyll** 2015-10-01 14:28 UTC
