### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by kchristi111** [golang/go#63702] opened 2023-10-20 21:06 UTC
gopls version: v0.13.2 (go1.21.0 X:nocoverageredesign)
gopls flags: -logfile /home/user/gopls.log -rpc.trace
update flags: off
extension version: 0.39.1-upstream-0.1.9-uber
go version: 1.21.3
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Fri, 20 Oct 2023 21:05:59 GMT
restart history:
Fri, 20 Oct 2023 21:04:06 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbe72eb]

goroutine 8222 [running]:
golang.org/x/tools/gopls/internal/lsp/cache.localPackageKey({{0xc00336c380, 0x35}, {0xc0033611a0, 0x25}, {0xc00322dd90, 0xd}, {0xc00b0a7920, 0x3, 0x3}, {0xc00b0a7950, ...}, ...})
	  check.go:1402  0x6eb
golang.org/x/tools/gopls/internal/lsp/cache.(*packageHandleBuilder).buildPackageHandle(0xc00c787170, {0x11619a0, 0xc01167fae0}, 0xc011490820)
	  check.go:1090  0x2be
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).getPackageHandles.func2.1()
	  check.go:891  0xd7
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:75  0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 8155
	  errgroup.go:72  0x96
[Error - 9:05:49 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by adonovan** [comment] 2023-10-23 22:20
duplicate of https://github.com/golang/go/issues/63701

**Closed by adonovan** 2023-10-23 22:20 UTC
Labels: gopls, Tools

**Comment by findleyr** [comment] 2023-10-26 15:27
Hi, can you please report if you are using a GOPACKAGESDRIVER? (echo $GOPACKAGESDRIVER)?
