### ISSUE TITLE
proposal: spec: automatically instantiate generic field types that are already concrete types

### ISSUE THREAD

**Issue by Pedro-Pessoa** [golang/go#56726] opened 2022-11-14 11:48 UTC
Currently, when you have a generic field in a struct that has a generic, but already concrete, type, to instantiate that struct you need to explicitly tell the compiler the type.

Example:
```go
type Foo struct {
	Field Field[int]
}

type Field[T any] struct {
	Val T
}

func Bar() Foo {
	return Foo{
		Field: Field[int]{
			Val: 10,
		},
	}
}
```

I find `Field: Field[int]{...` to be redudant, because that Field can not be of any type but an int. 

I propose that this would become possible:
```go
type Foo struct {
	Field Field[int]
}

type Field[T any] struct {
	Val T
}

func Bar() Foo {
	return Foo{
		Field: Field{
			Val: 10,
		},
	}
}
```
Currently, this error out as `cannot use generic type Field[T any] without instantiation`.

**Comment by seankhliao** [comment] 2022-11-14 12:30
Duplicate of #50285

**Closed by seankhliao** 2022-11-14 12:30 UTC
Labels: Proposal
