### ISSUE TITLE
doc: link to SettingGOPATH wiki page now broken

### ISSUE THREAD

**Issue by coisnepe** [golang/go#22711] opened 2017-11-14 09:58 UTC
At `doc/install.html#225`, `https://golang.org/wiki/SettingGOPATH` should be `https://golang.org/wiki/Setting-GOPATH` (missing dash between _Setting_ and _GOPATH_

**Comment by ALTree** [comment] 2017-11-14 10:08
The problem is that [someone destroyed](https://github.com/golang/go/wiki/_compare/b94c66c2b994c10db5c39236808e3ae1aa61dc30...724a12719dd55ede0a32312bf96ecee7701171a2) the `SettingGOPATH` wiki page, which was empty (it just said to go to `Setting-GOPATH`) which I believe was left there to avoid breaking links (general policy is that we don't delete wiki page and/or page subsections that can be linked to to avoid breaking links).

**Comment by ALTree** [comment] 2017-11-14 10:29
I have sent [CL 77470](https://go-review.googlesource.com/c/go/+/77470) to fix the doc links to `SettingGOPATH`. Even if we decide to restore the wiki page, it's better to link directly to the real `Setting-GOPATH` in the docs, instead of linking to a page that will tell you to go to that other page.

**Comment by ianlancetaylor** [comment] 2017-11-14 14:54
The real page should never have been `Setting-GOPATH`.  I've renamed that page back to `SettingGOPATH`.

@inancgumus Why did you delete the `SettingGOPATH` page?

@headless32 Why did you replace the page with a meaningless one?

I'm starting to feel that we need code review on the wiki pages.

Anyhow, this issue is now fixed, so closing.

**Closed by ianlancetaylor** 2017-11-14 14:54 UTC
Labels: Documentation, NeedsFix

**Comment by ALTree** [comment] 2017-11-14 15:52
I think it was moved to "Setting-GOPATH" because it's rendered as "Setting GOPATH", which is the human-readable way to write it (space in the middle instead of using camelcase). See for example how this page's title is rendered: https://github.com/golang/go/wiki/Well-known-struct-tags

**Comment by ALTree** [comment] 2017-11-14 16:01
> I'm starting to feel that we need code review on the wiki pages.

Yeah looking at the history it seems like that page was deleted and then restored multiple times, this is really suboptimal..
