### ISSUE TITLE
net/http: flakes on dragonfly-amd64-622

### ISSUE THREAD

**Issue by heschi** [golang/go#54758] opened 2022-08-29 18:48 UTC
```
#!watchflakes
post <- pkg == "net/http" && builder == "dragonfly-amd64-622" && 
        test == "TestServerGracefulClose" && `connection reset by peer`
```

[2022-08-26T17:45:20-78aef56/dragonfly-amd64-622](https://build.golang.org/log/3b9b2be4a26e0ede27d260c663500e10b2cf273e)
[2022-08-26T17:43:59-6ba2674/dragonfly-amd64-622](https://build.golang.org/log/1e00398e7b6cf2942f748b319dc7eb67a8ce65f0)

@ianlancetaylor @neild @golang/dragonfly

**Comment by bcmills** [comment] 2022-08-29 20:10
[2022-08-26T17:45:20-78aef56/dragonfly-amd64-622](https://build.golang.org/log/3b9b2be4a26e0ede27d260c663500e10b2cf273e)
```
--- FAIL: TestServerGracefulClose (1.02s)
    serve_test.go:3152: ReadLine: read tcp 127.0.0.1:54115->127.0.0.1:61592: read: connection reset by peer
FAIL
```

Could be related to #36178?

**Comment by bcmills** [comment] 2022-08-29 20:12
[2022-08-26T17:43:59-6ba2674/dragonfly-amd64-622](https://build.golang.org/log/1e00398e7b6cf2942f748b319dc7eb67a8ce65f0)

```

--- FAIL: TestServerShutdown_h2 (1.12s)
    serve_test.go:5677: second request should fail. server should be shut down
FAIL
FAIL	net/http	11.649s
```

Failure mode looks a lot like #38305.

**Comment by bcmills** [comment] 2022-12-06 17:14
Duplicate of #57084

**Closed by bcmills** 2022-12-06 17:14 UTC
Labels: NeedsInvestigation
