### ISSUE TITLE
flag provided but not defined: -test.timeout

### ISSUE THREAD

**Issue by shawnps** [golang/go#33774] opened 2019-08-22 02:32 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13rc1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, on the release candidate but not on Go 1.12.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="darwin"
</pre></details>

### What did you do?

Wrote a small test for code which contains flags being parsed inside an `init` function. All the test does is `t.Skip()`.

`foo.go`:

```
package main

import (
	"flag"
	"fmt"
)

var foo string

func init() {

	flag.StringVar(&foo, "foo", "foo", "foo")
	flag.Parse()
}

func main() {
	fmt.Println("vim-go")
}
```

`foo_test.go`:

```
package main

import "testing"

func TestFoo(t *testing.T) {
	t.Skip()
}
```

### What did you expect to see?

No errors.

### What did you see instead?

```
➜  flag-test go test
flag provided but not defined: -test.timeout
Usage of /var/folders/c_/zhpj7wdd3dgb52c4zpy3vj840000gn/T/go-build238457999/b001/flag-test.test:
  -foo string
    	foo (default "foo")
exit status 2
FAIL	_/Users/shawn/flag-test	0.005s
```

**Comment by cespare** [comment] 2019-08-22 03:10
See the [Go 1.13 release notes](https://tip.golang.org/doc/go1.13#minor_library):

> Testing flags are now registered in the new Init function, which is invoked by the generated main function for the test. As a result, testing flags are now only registered when running a test binary, and packages that call flag.Parse during package initialization may cause tests to fail.

**Comment by bcmills** [comment] 2019-08-22 03:22
Duplicate of #31859

**Closed by bcmills** 2019-08-22 03:22 UTC
