### ISSUE TITLE
x/net/ipv6: TestIPPerInterfaceSinglePacketConnWithSingleGroupListener broken on freebsd-386 for Go 1.11

### ISSUE THREAD

**Issue by bradfitz** [golang/go#31221] opened 2019-04-03 04:32 UTC
TestIPPerInterfaceSinglePacketConnWithSingleGroupListener is broken on freebsd-386-* with Go 1.11:

https://build.golang.org/log/7c758c236a9eff9b87a8fc6adb6013af786c2eb7
```
--- FAIL: TestIPPerInterfaceSinglePacketConnWithSingleGroupListener (0.00s)
    multicastlistener_test.go:247: listen ip6:ipv6-icmp 0:fe:8000::%lo0: bind: can't assign requested address
FAIL
FAIL	golang.org/x/net/ipv6	0.019s
```

@mikioh, can you fix?

**Comment by mikioh** [comment] 2019-04-03 05:45
Dupe of #28826. Please backport the CLs to release-branch.go1.11 if necessary; I cannot make backport CLs.

PS:  freebsd-386 builders are actually freebsd-compat32 builders.

**Comment by mikioh** [comment] 2019-04-03 05:47
> Please backport the CLs

CL 139577 and CL 139917.

**Comment by bradfitz** [comment] 2019-04-03 14:52
Re-opening the bug, as this isn't fix. The build.golang.org dashboard is still red.

**Comment by bradfitz** [comment] 2019-04-04 03:38
That didn't seem to fix it.

**Comment by mikioh** [comment] 2019-04-04 04:07
As described in #28826, the dependency is: T depends on net-of-stdlib depends on vendored x/net/route-of-stdlib. Please re-vendor the x/net/route to the release-branch.go1.11 of stdlib.

**Comment by bradfitz** [comment] 2019-04-04 05:07
Did Go 1.11 really ship not passing its tests on x/net?

**Comment by mikioh** [comment] 2019-04-04 05:51
I'm not sure about {build,try}bot fleet configuration. FreeBSD 11.2 kernel was released in June 2018. Perhaps the fleet was not updated during the release (or another possibility could be that I forgot to sweep the health check of the fleet because we also had the football world cup games in June-July 2018. :)

**Closed** 2019-04-05 17:23 UTC
Labels: NeedsFix, OS-FreeBSD, Testing
