### ISSUE TITLE
go/types: rejects valid program involving interfaces and cycles

### ISSUE THREAD

**Issue by dominikh** [golang/go#21804] opened 2017-09-08 12:27 UTC
### What version of Go are you using (`go version`)?
go version devel +6b6b9f69fd Wed Aug 9 05:33:09 2017 +0000 linux/amd64
go version go1.9 linux/amd64
go version go1.8.3 linux/amd64

### Does this issue reproduce with the latest release?
Yes

### What did you do?
https://play.golang.org/p/Vne0Zww-Qf

### What did you expect to see?
`package gps ("qps") <nil>`

### What did you see instead?
`package gps ("qps") main.go:37:20: cannot use UnpairedVersion(nil) (value of type UnpairedVersion) as Constraint value in variable declaration: missing method copyTo`

The Go compiler accepts this code. The example is based on a (much, much larger) real code base (https://github.com/golang/dep/pull/1127)

/cc @griesemer

**Comment by jmank88** [comment] 2017-09-08 12:40
I'm unsure if this adds insight, but I was surprised that changing this signature from a method to a function matters:
```diff
-func (m *ConstraintMsg) asUnpairedVersion() UnpairedVersion {
+func asUnpairedVersion(m *ConstraintMsg) UnpairedVersion {
	return nil
}
```

**Comment by dominikh** [comment] 2017-10-23 04:52
Ping. Is there anybody familiar enough with go/types to look at this? /cc @griesemer

**Comment by griesemer** [comment] 2017-10-23 18:25
@dominikh I will need to look into this. Is this a blocker for you? It seems that there's a work-around (moving the type to the bottom of the file) that doesn't affect the semantics of the code.

**Comment by jmank88** [comment] 2017-10-23 18:38
The original dep issue is no longer a problem. I have not encountered any other instances in the wild.

**Comment by griesemer** [comment] 2017-10-23 18:45
Simplified reproducer:
```
package p

type _ interface{ m(B) }

type A interface{ a(D) }
type B interface{ A }
type C interface{ B }
type D interface{ C }

var _ A = C(nil)
```
gotype reports:
```
x.go:10:11: cannot use C(nil) (value of type C) as A value in variable declaration: missing method a
```

**Comment by griesemer** [comment] 2017-10-23 18:47
This is most likely a duplicate of #18395.

**Comment by dominikh** [comment] 2017-10-24 03:19
It's not a blocker per se. Telling users of static analysis tools to move their code around is a subpar experience, but the one occurrence in `dep` was the first and only time I actually ran into the problem in the real world, so it's not a high priority from my end.

Might be a duplicate, yeah.

**Comment by griesemer** [comment] 2017-10-24 05:32
@dominikh I'm not suggesting that moving the code around is a solution, it's a work-around. Knowing there is a work-around is useful for prioritizing an issue. Clearly we need to fix this, but there's a lot of other issues we need to fix as well...

**Comment by dominikh** [comment] 2017-10-24 05:57
@griesemer Right. We're in agreement.

**Comment by griesemer** [comment] 2017-11-21 06:14
Confirmed duplicate of #18395 by running with https://go-review.googlesource.com/c/go/+/78955 in debug mode.

**Closed by griesemer** 2017-11-21 06:14 UTC
Labels: NeedsFix
