### ISSUE TITLE
ioutil.TempFile return something which looks like a valid file when base dir does not exists.

### ISSUE THREAD

**Issue by adiroiban** [golang/go#21680] opened 2017-08-29 11:13 UTC
I might be doing something wrong, as this looks like very basic behaviour, still I could not find the error on my side.

### What version of Go are you using (`go version`)?

```
$ go version
go version go1.9 linux/amd64

```
but I have also found it on 1.8

### Does this issue reproduce with the latest release?

Yes.
I can also reproduce it on https://play.golang.org/p/IDMHXJFdMA

### What operating system and processor architecture are you using (`go env`)?

Linux on amd64

I can also reproduce it on Travis-CI

https://travis-ci.org/adiroiban/vbox-ec2-md/jobs/269533011#L430

### What did you do?

https://play.golang.org/p/IDMHXJFdMA

### What did you expect to see?

I was expecting to see a failure to open / create the file.

If the parent path exists, all is good and it fails to open it https://play.golang.org/p/ly0_Q1oUXl

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0xffffffff addr=0x0 pc=0xd9f86]
```

**Comment by davecheney** [comment] 2017-08-29 11:34
This is not a bug. The testify suite method `Nil` does not terminate the test in the presence of an error. Because processing is not terminated, execution proceeds to this line

https://github.com/adiroiban/vbox-ec2-md/commit/67ee8f8dc1a4326b79e0c58b9e46b233ee45bfaa#diff-53618cae32e23ae47e1c35f10da92654R53

Which panics because the contents of the other values returned from `ioutil.TempFile` are not defined and cannot be used in the presence of an error.

i am going to close this as it does not look like this is a bug in Go. Please reopen if you disagree.

**Closed by davecheney** 2017-08-29 11:34 UTC

**Comment by adiroiban** [comment] 2017-08-29 12:12
True. My bad. Much appreciated! Sorry for the noise.

**Comment by davecheney** [comment] 2017-08-29 12:15
It might be worth raising a bug on the testify project to use FailNow,
rather than Fail inside assert.Nil
