### ISSUE TITLE
http: unexpected behavior of http.Server with http.MaxBytesReader and streaming response

### ISSUE THREAD

**Issue by jerome-laforge** [golang/go#46826] opened 2021-06-19 05:18 UTC
initially on https://groups.google.com/g/golang-nuts/c/4RDmrEYJlYE

### What version of Go are you using (`go version`)?
```
$ go 1.16.5
```

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1908905363=/tmp/go-build -gno-record-gcc-switches"
```
### What did you do?
I have program with two variants.
The first program (https://play.golang.org/p/JRyrfOh9UZC):
- launch the http.Server, 
- limit body input (http.MaxBytesReader),
- read each line of jsonl input stream via json.Decode
- send it back to client

The second program (https://play.golang.org/p/WVDK4ivA-Yj) does almost the same things except it discards the response via io.Discard.

The request bodies can be find just below (please ungzip before) and they are sent with simple curl just below: 
- [body_3kB.jsonl.gz size of 3kB](https://github.com/golang/go/files/6680001/body_3kB.jsonl.gz) is sent by `curl -X POST 'http://127.0.0.1:8081'  --data-binary '@body_3kB.jsonl'`
- [body_4kB.jsonl.gz size of 4kB](https://github.com/golang/go/files/6680000/body_4kB.jsonl.gz) is sent by `curl -X POST 'http://127.0.0.1:8081'  --data-binary '@body_4kB.jsonl'`
`

### What did you expect to see?
I expect to see correct limiter behavior on the input request body stream regardless of: 
- the size body (lower or greater than 4kB, size of http chunk?)
- send the response back or not (the io.Discard)

### What did you see instead?
With [body_3kB.jsonl.gz](https://github.com/golang/go/files/6680001/body_3kB.jsonl.gz), both variant of program works as expected. You can change the max size for limiter `http.MaxBytesReader`. It limits correctly according max defined size. The behaviors of limiter and http.Server are correct.

With [body_4kB.jsonl.gz](https://github.com/golang/go/files/6680000/body_4kB.jsonl.gz), the [2nd program with io.Discard](https://play.golang.org/p/WVDK4ivA-Yj) works correctly.

With [body_4kB.jsonl.gz](https://github.com/golang/go/files/6680000/body_4kB.jsonl.gz), the [1st program that acctually sends response back](https://play.golang.org/p/WVDK4ivA-Yj) returns unexpected error (even if body is smaller than 5kB). Furthermore, json decoder always returns an error whatever the max size of http.MaxBytesReader (100kB, 1024kB ...).
The behavior is same with `io.NopCloser(io.LimitReader())` instead of `http.MaxBytesReader()`

**Comment by seankhliao** [comment] 2021-06-19 10:12
Duplicate of #15527

**Comment by seankhliao** [comment] 2021-06-19 10:13
Note this is unrelated to MaxBytesReader, only to writing a response

**Closed by seankhliao** 2021-06-19 10:12 UTC

**Comment by jerome-laforge** [comment] 2021-06-21 15:24
As workaround, I buffer the response until I read completely the request.
In order to limit the GC and consumption of resource, I recycle the the bytes.Buffer with sync.Pool that is in charge of create bytes.Buffer with initial capacity.
