### ISSUE TITLE
cmd/compile: Unable to apply type parameters to embed type

### ISSUE THREAD

**Issue by mattn** [golang/go#51810] opened 2022-03-19 11:17 UTC
Compiler can't apply type parameters to embed type in compisite literals.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel go1.19-9956a5423e Thu Mar 17 03:41:50 2022 +0000 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\mattn\AppData\Local\go-build
set GOENV=C:\Users\mattn\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\mattn\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\mattn\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\dev\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\dev\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=devel go1.19-9956a5423e Thu Mar 17 03:41:50 2022 +0000
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\mattn\go\src\github.com\mattn\go-tensorflow-realtime-object-detection\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\mattn\AppData\Local\Temp\go-build1850869103=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```go
package main

import (
	"fmt"
)

type Based[B any] struct {
	v1 B
}

type Derived[T, B any] struct {
	Based[B]
	v2 T
}

func main() {
	v := Derived[string, int]{
		Based: Based[int]{
			v1: 1,
		},
		v2: "abc",
	}
	fmt.Println(v.v1, v.v2)
}
```

https://play.golang.com/p/LXEpnd3fxBm

### What did you expect to see?

It is possible to omit `[int]` for inner literal.

```go
package main

import (
	"fmt"
)

type Based[B any] struct {
	v1 B
}

type Derived[T, B any] struct {
	Based[B]
	v2 T
}

func main() {
	v := Derived[string, int]{
		Based: Based {
			v1: 1,
		},
		v2: "abc",
	}
	fmt.Println(v.v1, v.v2)
}
```

### What did you see instead?

>./prog.go:18:10: cannot use generic type Based[B any] without instantiation

https://play.golang.com/p/AwgNEDDi7zT

If compile without type parameters, it pass to compile.

https://play.golang.com/p/8J8FAusLKe2

**Comment by nojus297** [comment] 2022-03-19 12:07
As far as I know, literals of parametrized structs do not infer type parameters. That is, even `_ = Based{ v1: 1 }` fails to compile with the same error message. However, `_ = Based[int]{ v1: 1 }` works, as does modified embed code: https://play.golang.com/p/LXEpnd3fxBm

**Comment by ianlancetaylor** [comment] 2022-03-19 13:37
https://go.dev/doc/faq#type_inference

Closing because this is not a bug.  There are a number of type inferences that we could add to the language.  We're not going to do any of them until we have more experience with generics.

**Closed by ianlancetaylor** 2022-03-19 13:37 UTC

**Comment by mattn** [comment] 2022-03-19 13:56
Thank you. BTW, Is it worth making proposal to name the instance-time type name like below?

```go
func main() {
	v := Derived[string, T int]{
		Based: Based[T] {
			v1: 1,
		},
		v2: "abc",
	}
	fmt.Println(v.v1, v.v2)
}
```

**Comment by ianlancetaylor** [comment] 2022-03-19 16:17
@mattn I don't think we're going to be considering refinements like giving a name to a type argument anytime soon.  We need more experience.
