### ISSUE TITLE
x/build: gopherbot closing backport issue prematurely

### ISSUE THREAD

**Issue by ianlancetaylor** [golang/go#42277] opened 2020-10-29 19:11 UTC
For some reason gopherbot decided to close issue #42138 prematurely.  It is a backport issue to 1.15.  I submitted part of the fix in https://golang.org/cl/264301.  That CL says "For #42138", not "Fixes".  But gopherbot closed the issue anyhow: https://github.com/golang/go/issues/42138#issuecomment-718958745.  When I reopened the issue, gopherbot closed it again.

CC @dmitshur @cagedmantis @toothrot

**Comment by dmitshur** [comment] 2020-10-29 20:13
This is is a known gopherbot issue tracked by #29599, which unfortunately no one had the bandwidth to fix yet. Closing as duplicate.

**Closed by dmitshur** 2020-10-29 20:13 UTC
Labels: Builders, NeedsInvestigation

**Comment by dmitshur** [comment] 2020-10-29 20:21
> When I reopened the issue, gopherbot closed it again.

This is a separate known [gopherbot issue](https://goissues.org/golang.org/x/build/cmd/gopherbot) tracked by #21312. It is caused by a limitation of maintner tracked by #28226.

**Comment by ianlancetaylor** [comment] 2020-10-29 23:32
Thanks.
