### ISSUE TITLE
atomic.CompareAndSwapInt64 in 386

### ISSUE THREAD

**Issue by johnzhd** [golang/go#23281] opened 2017-12-29 08:04 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?  

go version go1.9.2 windows/amd64  

### Does this issue reproduce with the latest release?  

I'm not sure.  

### What operating system and processor architecture are you using (`go env`)?  

```sh  

gox -osarch="windows/386" ./app  

```  

### What did you do?  

```golang  

type DStatus int64  
  
// ...  
  
p := (*int64)(&Status)
atomic.CompareAndSwapInt64(p, int64(DStatusSleep), int64(DStatusWaiting))

```

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

```error  
http: panic serving 127.0.0.1:62185: runtime error: invalid
memory address or nil pointer dereference
goroutine 4
```  

### What did you expect?

Move this error from running time to compile time.  
Find out special actions on 64bit ptr in 386 target, Then warning it and fail.   

Golang is great, and it save me lots of time.  
Thank you.

**Comment by davecheney** [comment] 2017-12-29 08:31
Duplicate of #599

**Closed** 2017-12-29 09:08 UTC
