### ISSUE TITLE
readSetCookies mistaken

### ISSUE THREAD

**Issue by leewithyuan** [golang/go#49979] opened 2021-12-04 10:02 UTC
go version go1.17.4 darwin/amd64

response:
```
HTTP/1.1 200 OK
Server: openresty
Date: Sat, 04 Dec 2021 09:43:16 GMT
Content-Type: application/json;charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: JSESSIONID=5112F040B44EC9C8B7D804B13C3825E8; Path=/; HttpOnly
Set-Cookie: auth3_id = BFC06142E5221E2D27BF1B8AF69EB62E56C1474386F5E0D9E097535A55F7CF4AC783A699CF63E2FB56AB149A3E1E9353;Path=/
```

output:
```
[JSESSIONID=D89EF117B8E9B952D4AD6AF8CB607656; Path=/; HttpOnly]
```

**Comment by seankhliao** [comment] 2021-12-04 10:17
From [RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265#section-4.1.1):

```
 set-cookie-header = "Set-Cookie:" SP set-cookie-string
 set-cookie-string = cookie-pair *( ";" SP cookie-av )
 cookie-pair       = cookie-name "=" cookie-value
 cookie-name       = token
 cookie-value      = *cookie-octet / ( DQUOTE *cookie-octet DQUOTE )
```

spaces are not allowed around the name and value

Closing as working as intended

**Closed by seankhliao** 2021-12-04 10:17 UTC
