### ISSUE TITLE
## Most recent release: v0.4.1.

### ISSUE THREAD

**Issue by yikeshome** [golang/go#39067] opened 2020-05-14 06:49 UTC
how to configure gopls on vscode, I want to forbidden gopls analyzers 

### v0.4.1

This release contains mostly stability improvements and smaller bug fixes. A list of all of the issues fixed in this release can be found in the [gopls/v0.4.1 milestone](https://github.com/golang/go/milestone/146?closed=1). A notable change is that type error analyzers (fillreturns, undeclaredname, unusedparams, nonewvars) are now on by default.

### v0.4.0
- Improved support for working with modules (@ridersofrohan). A detailed walk-through of the new features can be found [here](https://www.ardanlabs.com/blog/2020/04/modules-05-gopls-improvements.html). A quick summary:
  -  Use the `-modfile` flag to suggest which modules should be added/removed from the `go.mod` file, rather than editing it automatically. 
  - Suggest dependency upgrades in-editor and provide additional language features, such as formatting, for the `go.mod` file.
-  Inverse implementations (@muirdm). "Go to implementations" on a concrete type will show the interfaces it implements.
- Completion improvements (@muirdm). Specifically, improved completion for keywords. Also, offer `if err != nil { return err }` as a completion item.
- Jumping to definition on an import statement returns all files as definition locations (@danishprakash).
- Support for running `go generate` through the editor, via a code lens (@marwan-at-work).
- Command-line support for workspace symbols (@daisuzu).

#### Opt-in:
 - Code actions suggesting `gofmt -s`-style simplifications (@ridersofrohan). To get these on-save, add the following setting:

```json5
"[go]": {
	"editor.codeActionsOnSave": {
		"source.fixAll": true,
	}
}
```
 - Code actions suggesting fixes for type errors, such as missing return values ([goreturns](https://github.com/sqs/goreturns)-style), undeclared names, unused parameters, and assignment statements that should be converted from `:=` to `=` (@ridersofrohan). Add the following to your gopls settings to opt-in to these analyzers. In the future, they will be on by default and high-confidence suggested fixes may be applied on save. See additional documentation on analyzers [here](https://cs.opensource.google/go/tools/+/master:gopls/doc/analyzers.md).
```json5
"gopls": {
	"analyses": {
		"fillreturns": true,
                "undeclaredname": true,
                "unusedparams": true,
                "nonewvars": true,
	}
}
```

 - Further improvements in the support for multiple concurrent clients (@findleyr). See #34111 for all details. 

For a complete list of the issues resolved, see the [gopls/v0.4.0 milestone](https://github.com/golang/go/milestone/133?closed=1).

_Originally posted by @stamblerre in https://github.com/golang/go/issues/33030#issuecomment-510151934_

**Comment by ALTree** [comment] 2020-05-14 10:43
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-05-14 10:43 UTC
