### ISSUE TITLE
Writing to a string converted to byte slice results in a crash

### ISSUE THREAD

**Issue by Impyy** [golang/go#17993] opened 2016-11-20 19:53 UTC
### What version of Go are you using (`go version`)?
go version go1.7.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/alex/Go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="x86_64-pc-linux-gnu-gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build247198489=/tmp/go-build -gno-record-gcc-switches"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
```

### What did you do?
1. Obtain the underlying StringHeader of a string.
2. Create a SliceHeader based on the data inside the StringHeader.
3. Convert the SliceHeader to an actual slice and try to make changes to its contents.

Here's the code: https://play.golang.org/p/VjvJmdyITM

I understand that strings are supposed to be immutable, but I was surprised to see that the following works and doesn't crash: https://play.golang.org/p/rvO918QZPI

### What did you expect to see?
An empty string.

### What did you see instead?
A crash:
```
value: "secret"
unexpected fault address 0x4a60ea
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x4a60ea pc=0x45251f]

goroutine 1 [running]:
runtime.throw(0x4a601d, 0x5)
	/usr/lib/go/src/runtime/panic.go:566 +0x95 fp=0xc42003fe30 sp=0xc42003fe10
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc42003fe88 sp=0xc42003fe30
runtime.memmove(0x4a60ea, 0xc42000a338, 0x6)
	/usr/lib/go/src/runtime/memmove_amd64.s:155 +0x38f fp=0xc42003fe90 sp=0xc42003fe88
main.main()
	/tmp/tmp.f98qbdIq9T/main.go:13 +0x166 fp=0xc42003ff48 sp=0xc42003fe90
runtime.main()
	/usr/lib/go/src/runtime/proc.go:183 +0x1f4 fp=0xc42003ffa0 sp=0xc42003ff48
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42003ffa8 sp=0xc42003ffa0
exit status 2
```

**Comment by randall77** [comment] 2016-11-20 22:48
The backing store for strings is not guaranteed to be immutable.  Some implementations store the backing array for strings in read-only memory, but it isn't guaranteed.

In your second example you're overwriting 6 bytes of the string header with zeros.  I'm surprised that works at all.  (It doesn't on my machine, but it does on the playground.)  Don't do that.

This is all working as intended.  Closing.

**Closed by randall77** 2016-11-20 22:48 UTC

**Comment by Impyy** [comment] 2016-11-21 16:33
Ah. Thanks for clearing that up.
