### ISSUE TITLE
"go mod vendor" deletes vendor folder unexpectedly

### ISSUE THREAD

**Issue by fgergo** [golang/go#45355] opened 2021-04-02 13:40 UTC
$ go version
go version go1.16.3 windows/amd64

### Does this issue reproduce with the latest release?
yep

### What did you do?
c:\gosourcefiles>go mod vendor
go: no dependencies to vendor

### What did you expect to see?
No command should delete a directory complete with files without any warning!

### What did you see instead?
"go mod vendor" deleted the vendor directory containing go source and other files, without any warning or confirmation. That's more than surprising and it's just not polite.

c:\gosourcefiles\go.mod:
module p

go 1.16

Please don't close this issue with works_as_intended or similar comment, without pointing out a discussion or a design document.

**Comment by seankhliao** [comment] 2021-04-02 13:43
Duplicate of #44119

**Closed by seankhliao** 2021-04-02 13:43 UTC
