### ISSUE TITLE
net/http/server.go var pool in function newBufioWriterSize(io.Writer, int) *bufio.Writer Get return nil

### ISSUE THREAD

**Issue by wangsong93** [golang/go#39673] opened 2020-06-18 02:06 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.15beta1
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you expect to see?
Because there is no New function supplied for bufioWriter2kPool and bufioWriter4kPool, every time pool Get return nil.
`
func newBufioWriterSize(w io.Writer, size int) *bufio.Writer {

        pool := bufioWriterPool(size)  // should  delete or supply New func
        if pool != nil {
                if v := pool.Get(); v != nil {
                        bw := v.(*bufio.Writer)
                        bw.Reset(w)
                        return bw
                }
        }
        return bufio.NewWriterSize(w, size)
}
`

**Comment by andybons** [comment] 2020-06-18 05:43
Duplicate of #39648

Unless you have found a bug, please use one of the other forums mentioned in #39648 for asking a question instead of the issue tracker. Thanks.

**Closed by andybons** 2020-06-18 05:43 UTC

**Comment by davecheney** [comment] 2020-06-18 05:50
@wangsong93 the buffer pools are lazily initialised by filling the pool with entries in `putBufioWriter` rather than using a `New` function. This is because the `bufio.Writer`'s returned from the pool must be a specific size which is best handled in `newBufioWriterSize`
