### ISSUE TITLE
runtime:Test gopark and find the following problems(我测试gopark发现如下问题)

### ISSUE THREAD

**Issue by Jesgoal** [golang/go#53675] opened 2022-07-04 07:39 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

src/runtime/runtime_part.go

```
func park_m_test(gp *g) {
	_g_ := getg()

	if trace.enabled {
		traceGoPark(_g_.m.waittraceev, _g_.m.waittraceskip)
	}
	println("park_m_test0-->", getg(), gp.atomicstatus)
	casgstatus(gp, _Grunning, _Gwaiting)
	dropg()
	println("park_m_test1-->", getg(), gp.atomicstatus)
	if fn := _g_.m.waitunlockf; fn != nil {
		ok := fn(gp, _g_.m.waitlock)
		println("park_m_test2-->", getg(), gp.atomicstatus)
		_g_.m.waitunlockf = nil
		_g_.m.waitlock = nil
		if !ok {
			if trace.enabled {
				traceGoUnpark(gp, 2)
			}
			if gp.atomicstatus&(_Grunning|_Grunnable) != 0 {
				println("casgstatus: waiting for Gwaiting but is Grunnable")
			}
			casgstatus(gp, _Gwaiting, _Grunnable)
			execute(gp, true) // Schedule it back, never returns.
		}
	}
	println("park_m_test3-->", getg(), gp.atomicstatus)
	schedule()
}
func gopark_test(unlockf func(*g, unsafe.Pointer) bool, lock unsafe.Pointer, reason waitReason, traceEv byte, traceskip int) {
	if reason != waitReasonSleep {
		checkTimeouts() // timeouts may expire while two goroutines keep the scheduler busy
	}
	mp := acquirem()
	gp := mp.curg
	status := readgstatus(gp)
	if status != _Grunning && status != _Gscanrunning {
		throw("gopark: bad g status")
	}
	mp.waitlock = lock
	mp.waitunlockf = unlockf
	gp.waitreason = reason
	mp.waittraceev = traceEv
	mp.waittraceskip = traceskip
	releasem(mp)
	println("gopark_test0--??>", getg())
	// can't do anything that might move the G between Ms here.
	mcall(park_m_test)
	println("gopark_test0--??<", getg())
}

func wakeUpResetForSleep2(gp *g, f unsafe.Pointer) bool {
	println("--->1")
	usleep(1000)
	println("--->2")
	return false
}
func Gogopark(park bool, f func(gp unsafe.Pointer), gp unsafe.Pointer) {
	if park {
		gp = unsafe.Pointer(getg())
		f(gp)
		gopark_test(wakeUpResetForSleep2, gp, waitReasonSleep, traceEvGoSleep, 2)
		usleep(100)
	} else {
		println("--->3")
		goready((*g)(gp), 2)
		println("--->4")
	}

}```

main.go

```func main() {
//I don't know if the calling method of gopark is right, or my understanding
//Mainly my code uses gopark sleep and wakeup functions, and occasionally there are program exceptions
//The following code raises "bugs"
	runtime.Gogopark(true, func(gp unsafe.Pointer) {
		go runtime.Gogopark(false, nil, gp)
	}, nil)
	t := time.Now().Unix()
//Here is some code that is affected
	LogPrintln("Sleep in")
	time.Sleep(time.Second * 1000)
	LogPrintln("Sleep out", time.Now().Unix()-t)
}```

output:

gopark_test0--??> 0xc000040000
park_m_test0--> 0x13ff6b860 2
park_m_test1--> 0x13ff6b860 4
--->1
--->3
--->4
gopark_test0--??< 0xc000040000
--->2
park_m_test2--> 0x13ff6b860 2
casgstatus: waiting for Gwaiting but is Grunnable
Sleep in
Sleep out 0

**Comment by mengzhuo** [comment] 2022-07-04 08:46
What result you are expecting?

**Comment by Jesgoal** [comment] 2022-07-04 10:03
gopark and goready do not have synchronization locks, similar time.Sleep(time.Second * 1000) fails, casgstatus will randomly throw exceptions

**Comment by Jesgoal** [comment] 2022-07-04 10:10
Or goready wakes up the goroutine without checking that gopark is running, causing the goroutine state to be chaotic

**Comment by Jesgoal** [comment] 2022-07-04 10:26
I think adding a run queue to the goroutine structure, just adding a *nextcall pointer can avoid such problems and keep a thread operating this structure

**Comment by prattmic** [comment] 2022-08-05 19:13
`goready` requires that the G is in `_Gwaiting`, but you start a goroutine that potentially calls `goready` before the original goroutine gets to `gopark` to put the goroutine in `_Gwaiting`.

What are you actually trying to do?

**Comment by prattmic** [comment] 2022-08-05 19:19
I'm going to close this for now, as this seems to be about questions extending the runtime for some new functionality, not a bug in the runtime. If there is some functionality you are adding and need feedback, please open an issue about that functionality.

**Closed by prattmic** 2022-08-05 19:19 UTC
Labels: WaitingForInfo, compiler/runtime
