### ISSUE TITLE
cmd/compile: bad walkinrange rewrites on constant above 2**63

### ISSUE THREAD

**Issue by benshi001** [golang/go#27143] opened 2018-08-22 09:14 UTC
The below go code is rejected by go1.11.

	package main
	import "fmt"
	func main() {
		var c uint64
		fmt.Scanf("%d", &c)
		if 0xc00921f9f01b866e < c && c < 0xc00921ff2e48e8a7 {
			fmt.Println("AAAAAAAAAAA")
		} else {
			fmt.Println("BBBBBBBBBBB")
		}
	}

With error message

	# command-line-arguments
	./a.go:8:28: constant -4609115386278082961 overflows uint64

But this code is accepted by go1.6 and gccgo.

**Comment by benshi001** [comment] 2018-08-22 09:16
unit64's legal range should be 0000 0000 0000 0000 ~~ ffff ffff ffff ffff

Do I misunderstand something here?

**Comment by ALTree** [comment] 2018-08-22 09:36
The constant referenced in the error (`-4609115386278082961`) is given by 

```
0xc00921f9f01b866e - (2^64 - 1)         = 
0xc00921f9f01b866e - 0xffffffffffffffff = 
  -4609115386278082961
```

and any literal in the second comparison triggers the error, for example:

```
if 0xc00921f9f01b866e < c && c < 0 {
```

works too (but you *need* a second comparison: just the first doesn't error).

Some kind of comparison optimization gone wrong? (but the issue is still there even with `-N`).

**Comment by go101** [comment] 2018-08-22 09:43
Simplified version.

This works:
```golang
package main
func main() {
	var c uint64
	const x, y uint64 = 0xc00921f9f01b866e, 0xc00921ff2e48e8a7
	_ = c < y
	_ = c > x
}
```

This doesn't:
```golang
package main
func main() {
	var c uint64
	const x, y uint64 = 0xc00921f9f01b866e, 0xc00921ff2e48e8a7
	_ = c < y && c > x // constant -4609115386278082961 overflows uint64
}
```

**Comment by ALTree** [comment] 2018-08-22 10:57
First one works, the second errors:

```
_ = 0x7ffffffffffffff < c && c < 0x7ffffffffffffff+1
_ = 0x8000000000000000 < c && c < 0x8000000000000000+1
```

When `C >= 2**63` (like in the second line) the front-end rewrites the boolean expression into a single `LT`:

```
.   .   LT u(2) l(6) tc(1) bool
.   .   .   CONVNOP u(2) l(6) tc(1) uint64
.   .   .   .   SUB u(2) l(6) tc(1) uint64
.   .   .   .   .   NAME-p.c u(1) a(true) g(1) l(4) x(0+0) class(PAUTO) f(1) tc(1) assigned used(true) uint64
.   .   .   .   .   LITERAL--9223372036854775807 u(1) a(true) l(6) tc(1) uint64
.   .   .   LITERAL-0 u(1) a(true) l(6) tc(1) uint64
```
The rewrite introduces the bad const.

I suspect this may be an issue with `walkinrange` ([CL 27652](https://go-review.googlesource.com/c/go/+/27652)).

cc @josharian

**Comment by ALTree** [comment] 2018-08-22 12:08
`walkinrange` assumes in several places that `a.Int64( )` (where `a` is a `CTINT` `Node`) will succeed, but if `a` contains a const bigger than `2**63` the result is actually undefined (in practise, it'll return a negative number).

One nuclear option would be to just disable the range check optimization when `Int64( )` cannot be used reliably ([CL 130735](https://go-review.googlesource.com/c/go/+/130735)). Another option is to review and fix all `Int64` uses in `walkinrange`.

**Comment by josharian** [comment] 2018-08-25 06:47
I'm on the fence about whether this fix for this should be backported. Opinions?

**Comment by ALTree** [comment] 2018-08-25 15:00
It's the compiler rejecting valid code... even if it's not common to write expressions with integers over 2**63. IMO this should at least be considered for backporting, at least on 1.11.1

**Comment by ianlancetaylor** [comment] 2018-08-25 16:54
Certainly seems to qualify for a backport.

**Comment by josharian** [comment] 2018-08-26 21:15
> Certainly seems to qualify for a backport.

Yeah. My hesitation was only that this appears to have existed for many releases, and the symptom is a spurious compiler error (not bad code generation). Nevertheless, I agree.

@gopherbot please open backport tracking issues.

**Closed** 2018-08-26 21:52 UTC
Labels: NeedsFix, release-blocker
