### ISSUE TITLE
cmd/go: install "malformed file path" for source code filenames outside the Unicode BMP

### ISSUE THREAD

**Issue by nigeltao** [golang/go#50396] opened 2021-12-30 12:47 UTC
As reported at https://github.com/google/wuffs/issues/62#issuecomment-1002821964

```
$ go install github.com/google/wuffs@v0.3.0-beta.12
go: downloading github.com/google/wuffs v0.3.0-beta.12
go install: github.com/google/wuffs@v0.3.0-beta.12: create zip: test/data/non-ascii/😻.txt: malformed file path "test/data/non-ascii/😻.txt": invalid char '😻'
```

The github.com/google/wuffs repository indeed has a file named [test/data/non-ascii/😻.txt](https://github.com/google/wuffs/blob/v0.3.0-beta.12/test/data/non-ascii/%F0%9F%98%BB.txt) and e.g. `git clone` seems OK with it.

😻 is U+1F63B SMILING CAT FACE WITH HEART-SHAPED EYES (in UTF-8: [F0 9F 98 BB]), outside of the Unicode Basic Multilingual Plane (BMP).

If I'm reading the [ZIP specification](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) correctly, section "4.6.9 -Info-ZIP Unicode Path Extra Field (0x7075)" suggests that it's possible for ZIP files to contain (UTF-8 encoded) Unicode file names.

**Comment by ALTree** [comment] 2021-12-30 13:54
I think filenames of modules file have additional restrictions, not everything that is allowed by the zip specification can be a filename.

**Comment by seankhliao** [comment] 2021-12-30 13:57
Duplicate of #45549

**Closed by seankhliao** 2021-12-30 13:57 UTC

**Comment by catundercar** [comment] 2022-09-05 02:56
> I think the names of files in modules have additional restrictions, not everything that is permitted by the zip specification is allowed.
> 
> https://go.dev/ref/mod#zip-path-size-constraints
> 
> > File and directory names within a module may consist of Unicode letters, ASCII digits, the ASCII space character (U+0020), and the ASCII punctuation characters !#$%&()+,-.=@[]^_{}~.

Hello, I have a small question: If we do not check other files which do not affect compilation in the `module`, would it affect we get and use the `module`?
