### ISSUE TITLE
cmd/compile: bad reflect.StructField.PkgPath for embedding builtin types

### ISSUE THREAD

**Issue by mdempsky** [golang/go#21702] opened 2017-08-30 20:32 UTC
https://play.golang.org/p/FKRrIM2rDh

The PkgPath field for embedding the universal "error" type is being set to "go.builtin". It should be "main".

Related to #21696.

**Comment by mdempsky** [comment] 2017-08-30 20:34
Actually, this applies to all builtin types, not just error.

**Comment by dsnet** [comment] 2017-08-30 22:44
I think this is a duplicate of #21122

**Comment by mdempsky** [comment] 2017-08-30 22:47
@dsnet Certainly related at least. CL 60410 changes `S1.x`'s PkgPath from "" to "main".

**Comment by dsnet** [comment] 2017-08-30 23:15
Ah, you're right. Definitely related, but different. Lot's subtleties around StructField.PkgPath it seems...

**Closed** 2017-09-05 18:11 UTC
