### ISSUE TITLE
proposal: iter: add Map/Filter/Reduce functions

### ISSUE THREAD

**Issue by Manbeardo** [golang/go#70761] opened 2024-12-10 22:18 UTC
### Proposal Details

When Map, Filter, and Reduce were dropped from the `slices` proposal, the [summary of the reasoning](https://github.com/golang/go/discussions/47203#discussioncomment-1034432) was:

> probably better as part of a more comprehensive streams API somewhere else

Now that iterators are in the language, `iter` arguably *is* that comprehensive streams API. Maybe those functions would be at home in that package?

**Comment by jimmyfrasche** [comment] 2024-12-10 22:36
Duplicate of #61898 which plans to add them to x/exp/xiter first

**Closed by jimmyfrasche** 2024-12-10 22:36 UTC
Labels: Proposal
