### ISSUE TITLE
anic: runtime error: slice bounds out of range [:230812] with capacity 230807

### ISSUE THREAD

**Issue by continueJ** [golang/go#44878] opened 2021-03-09 08:32 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOHOSTARCH="amd64"
GOHOSTOS="linux"
</pre></details>

### What did you do?

```
// include wav file header
func (p *G711WavPayloader) Payload(wav_data []byte) (rtp_payload [][]byte) {
	start := 0
	for i := 36; i < len(wav_data); i++ { 
		if string(wav_data[i:i+4]) == "data" {
			start = i + 8
			break
		}
	}
	if start == 0 {
		fmt.Errorf("data ERROR")
		return rtp_payload
	}

	for index := start; index < len(wav_data); index += PCMAPayLoadLength {
		rtp_payload = append(rtp_payload, wav_data[index:index+PCMAPayLoadLength])
	}
	return rtp_payload
}
```

### What did you expect to see?

obtain the payload correctly

### What did you see instead?
anic: runtime error: slice bounds out of range [:230812] with capacity 230807

**Comment by AlexRouSg** [comment] 2021-03-09 08:46
Please explain why do you think this is a bug with Go and not a bug with your code.

**Comment by odeke-em** [comment] 2021-03-09 08:50
@continueJ thank you for filing this issue and welcome to the Go project!

You have a bug in your program because your end index is out of range of the length as the runtime panic shows. It is expected that for a slicing range
slice[low:high] that the following condition be satisfied:
0<=low<=high<=len(slice)


Please check the slice end index with
```go
end := index + PCMAPayLoadLength
if end > len(wav_data) {
   end = len(wav_data)
}
tp_payload = append(rtp_payload, wav_data[index:end])
}
```

I shall close this issue as I’ve provided a solution but please don’t hesitate to reach out and if you need to ask questions, please see these resources https://github.com/golang/go/wiki/Questions. Thank you for using Go!

**Closed** 2021-03-09 08:50 UTC
Labels: WaitingForInfo

**Comment by davecheney** [comment] 2021-03-09 09:08
> string(wav_data[i:i+4]) == "data" {

this line constructs a value four beyond I, without checking that it is bounded.

**Comment by continueJ** [comment] 2021-03-24 07:52
In version 14, this program can be executed correctly。This wav_data is a standard audio data for parsing。But In version 16，the returned variable rtp_payload seems that the maximum size is limited by default and leads to out of bounded
