### ISSUE TITLE
plugin: can't load same plugin using 2 different names

### ISSUE THREAD

**Issue by Wwwwwxh** [golang/go#47298] opened 2021-07-20 03:54 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.3 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wangxuhui/Library/Caches/go-build"
GOENV="/Users/wangxuhui/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/wangxuhui/go/pkg/mod"
GONOPROXY="github.com/bangwork/*"
GONOSUMDB="github.com/bangwork/*"
GOOS="darwin"
GOPATH="/Users/wangxuhui/go/"
GOPRIVATE="github.com/bangwork/*"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/q3/xc_0rmp5295bh2nmnmnq3gkc0000gn/T/go-build785620014=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

```
p.so
package main

import (
	"fmt"
)
var V int
func F() { fmt.Printf("Hello, number %d\n", V) }

Main program
package main

import (
	"plugin"
)

func main() {
	p, err := plugin.Open("./p1.so")
	if err != nil {
		panic(err)
	}
	p, err = plugin.Open("./p2.so")
	if err != nil {
		panic(err)
	}
	v, err := p.Lookup("V")
	if err != nil {
		panic(err)
	}
	f, err := p.Lookup("F")
	if err != nil {
		panic(err)
	}
	*v.(*int) = 7
	f.(func())() // prints "Hello, number 7"
}

go build -buildmode=plugin -o=../p1.so
go build -buildmode=plugin -o=../p2.so

```

### What did you expect to see?
Both plugins can be loaded
### What did you see instead?
panic: plugin.Open("./p2"): plugin already loaded

**Comment by randall77** [comment] 2021-07-20 06:23
I'm not sure why the plugin package is giving that error. I guess the question is: are they the same plugin, or not? It matters because we need to know whether to run the `init` function once, or twice, and (for plugins more complicated than this one) decide whether types declared in each plugin are identical or not. In this case it's not clear which choice should be made.

(The plugin package treats identity using filenames, so it thinks they are different plugins. But the runtime uses a content hash, by which the two plugins look identical.)

If you build the plugins as separate packages (i.e. don't list `.go` files on the command line, instead put them in separate directories and build the plugin using all the source in each directory), it shouldn't conflict.

@crawshaw

**Comment by Wwwwwxh** [comment] 2021-07-20 06:36
They are the same plugin

**Comment by Wwwwwxh** [comment] 2021-07-20 06:38
@randall77 They are the same plugin，I used the same file to build two so files The main program loads the two so files

**Comment by randall77** [comment] 2021-07-20 14:53
Right, but I guess my question is more philosophical. If you load `p1.so` into `p1` and `p2.so` into `p2`, then lookup `V` in each, what should this print: `println(v1.(*int) == v2.(*int))`? In other words, should those be the same `V`s, or different `V`s? My guess is it should print `false`, as you're loading different files, even if their contents are the same.
But what if `p2.so` is just a symlink to `p1.so`? Is that still "two different files"?
We do require that if you load `p1.so` twice, then it should print `true`.

**Comment by seankhliao** [comment] 2024-12-03 14:54
Duplicate of #29525

**Closed by seankhliao** 2024-12-03 14:54 UTC
Labels: NeedsInvestigation, compiler/runtime
