### ISSUE TITLE
cmd/go: how to use `go mod download` to download a module from http port 80 ?

### ISSUE THREAD

**Issue by m3ng9i** [golang/go#31741] opened 2019-04-29 14:17 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

I want to use `go mod download` command to download a private repository which is served at http port 80 (but not https port 443). The `go mod download` return an error:

```
    go: my-package.local/mypkg@v0.1.0: unrecognized import path "my-package.local/mypkg" (https fetch: Get https://my-package.local/mypkg?go-get=1: dial tcp <IP>:443: connect: connection refused)
    go: error loading module requirements
```

**Comment by ianlancetaylor** [comment] 2019-04-29 19:21
CC @bcmills 

Perhaps `go mod download` needs a `-insecure` flag.

**Comment by bcmills** [comment] 2019-04-29 20:52
See https://github.com/golang/go/issues/27332#issuecomment-450389460.

**Comment by bcmills** [comment] 2019-04-29 20:52
Duplicate of #27332

**Closed by bcmills** 2019-04-29 20:52 UTC
Labels: NeedsInvestigation, modules
