### ISSUE TITLE
x/pkgsite: <b> tags stripped from markdown 

### ISSUE THREAD

**Issue by lorypelli** [golang/go#68211] opened 2024-06-27 09:59 UTC
Hello, I'm having an issue on the page:
https://pkg.go.dev/github.com/lorypelli/cpkgs
My user agent is:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`
Screenshot:
![image](https://github.com/golang/go/assets/87276663/780ea6cc-a7b7-4797-92ff-412d62bc5b18)
Issue:
The uppercase words are also bolded, but it doesn't show here because bold of the <b> tag was removed

**Comment by seankhliao** [comment] 2024-06-27 10:25
you could consider using markdown's native `__text__` bolding

**Comment by lorypelli** [comment] 2024-06-27 10:58
> you could consider using markdown's native `__text__` bolding

You mean `**text**`
You are right, I forgot about this

**Comment by lorypelli** [comment] 2024-06-27 12:42
> you could consider using markdown's native `__text__` bolding

same issues happens with `em` but I used markdown `*` this time

**Comment by ansaba** [comment] 2024-06-27 19:36
cc: @jba

**Comment by findleyr** [comment] 2024-07-08 14:32
Closing as working as intended.

**Closed by findleyr** 2024-07-08 14:32 UTC
Labels: help wanted, pkgsite
