### ISSUE TITLE
tabwritter does not handle non-Latin "wide"  characters

### ISSUE THREAD

**Issue by ndeloof** [golang/go#51650] opened 2022-03-14 11:20 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.6 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?
docker/cli uses a [tabwritter](https://github.com/docker/cli/blob/master/cli/command/formatter/formatter.go#L74-L80) to render output as a table. This works fine until data to render uses non-Latin characters, as reported on https://github.com/docker/compose/issues/9172:

The root cause is that chinese characters display using more than just one ASCII slot (this is unrelated to the "fixed width" font being used). `tabwritter.updateWidth` counts runes being added to adjust column size, but _should_ also compute rune width as number of terminal columns, based on [wcwidth](https://www.man7.org/linux/man-pages/man3/wcwidth.3.html). Also see https://github.com/mattn/go-runewidth is a plain go implementation.

### What did you expect to see?

```
NAME                                         DESCRIPTION                                     STARS
gitlab/gitlab-ce                             GitLab Community Edition docker image based …   3518
twang2218/gitlab-ce-zh                       汉化的 GitLab 社区版 Docker Image                 254     
```

### What did you see instead?

```
NAME                                         DESCRIPTION                                     STARS
gitlab/gitlab-ce                             GitLab Community Edition docker image based …   3518
twang2218/gitlab-ce-zh                       汉化的 GitLab 社区版 Docker Image                     254     
```

**Comment by seankhliao** [comment] 2022-03-14 11:54
Duplicate of #8273

**Closed by seankhliao** 2022-03-14 11:54 UTC
