### ISSUE TITLE
malformed module path "xxx": missing dot in first path element - When path itself is missing

### ISSUE THREAD

**Issue by spekary** [golang/go#35343] opened 2019-11-04 15:57 UTC
Per issue #34184, this is a specific case that causes this error.

### What version of Go are you using (`go version`)?
<pre>
v1.13.4

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?
Mac OS 10.14.6

### What did you do?

I ran a test on code that had an import path like so:

```import mypath/dir/subdir```

This code is supposed to be run in a directory that has a go.mod file with a "replace" statement that directs "mypath" to a real directory on the computer, as in:

```replace mypath/dir/subdir => ../myproject```

However, I did not set that up yet in the go.mod file. Essentially this means that Go was trying to import a path that it could not resolve.

More specifically, here are reproducible steps:
1) Create a test directory
2) In the test directory, put the following files:

main.go:
```
package main
import "a/b/c"
```

go.mod:
```
module b
go 1.13
```

3) From the test directory, run ```go run main.go```

### What did you expect to see?

Since I like errors that offer solutions when available, I like this:

```malformed module path "a/b/c": Cannot resolve module path to a directory location.  Either install the module, or use a replace statement in a go.mod file to direct it to a location on your disk.```

### What did you see instead?

cannot load a/b/c: malformed module path "a/b/c": missing dot in first path element

**Comment by jayconrod** [comment] 2019-11-05 22:32
I believe this is a duplicate of #35273.

**Closed by jayconrod** 2019-11-05 22:32 UTC
Labels: NeedsInvestigation, modules

**Comment by bcmills** [comment] 2019-11-06 14:13
Duplicate of #35273
