### ISSUE TITLE
runtime: runtime:cpu124 test crash or stall when GO_GCFLAGS=-N -l

### ISSUE THREAD

**Issue by quentinmit** [golang/go#15853] opened 2016-05-26 22:19 UTC
Starting with @aclements CL 23391 ("runtime: pass gcWork to scanstack") yesterday, the runtime tests are consistently timing out on the linux-amd64-noopt builder. See e.g. https://build.golang.org/log/c70503b10af6b554372e2e11f257f7a0d8524678

It looks like these tests are running in anywhere from 10s to 100s on the other builders.

Austin, can you take a look at the traceback and see if this is an important regression for Go 1.7?

**Comment by aclements** [comment] 2016-05-27 14:24
Repro:

```
GO_GCFLAGS="-N -l" ./make.bash
GOMAXPROCS=2 go test runtime -cpu=1,2,4
```

It looks like it's usually not a timeout, but rather a segfault. (Which is good; that's probably easier. :)

**Comment by aclements** [comment] 2016-05-27 15:23
One definite problem is that markrootFreeGStacks calls shrinkstack on a preemptible, growable user stack, which means we may corrupt the internal stack allocation structures. The fix for this is trivial, but I'm working on confirming that this is in fact the root cause of this failure.

**Comment by aclements** [comment] 2016-05-27 15:45
I've confirmed that there's a stack growth happening in the middle of stackcacherelease when it calls lock, after it's already picked up the mcache. The stack growth also accesses the mcache, and intertwining the two operations corrupts the mcache. 3be48b4 triggered it because it grew the stack of markroot from 0x68 bytes to 0x70 bytes on the noopt builder, and markroot is on the path to the stackcacherelease when the growth happens (the added argument that grew the markroot stack frame isn't, but that's the noopt builder for you. :)

**Closed** 2016-05-27 17:53 UTC
Labels: NeedsInvestigation
