### ISSUE TITLE
net: TestReadFromTimeoutFluctuation and TestWriteTimeoutFluctuation trybot flake on OpenBSD

### ISSUE THREAD

**Issue by bradfitz** [golang/go#20838] opened 2017-06-28 22:01 UTC
Test flake on OpenBSD:

https://storage.googleapis.com/go-build-log/4f0cbd68/openbsd-amd64-60_a0ca068c.log
```
--- FAIL: TestReadFromTimeoutFluctuation (1.48s)
	timeout_test.go:727: ReadFrom took over 1s; expected 0.1s
--- FAIL: TestWriteTimeoutFluctuation (1.96s)
	timeout_test.go:769: Write took over 1s; expected 0.1s
FAIL
FAIL	net	33.085s
```

**Comment by geirskjo** [comment] 2017-08-16 11:17
I ran these tests on my OpenBSD system (6.1 GENERIC.MP#6 amd64) with Go version devel +a9257b6b69 Wed Aug 16 05:13:18 2017 +0000 openbsd/amd64 on a updated repo.

They did not fail. Anything I can do to help?

[net]$ go test -v -run TimeoutFluctuation -count 8 
=== RUN   TestReadTimeoutFluctuation
=== RUN   TestReadFromTimeoutFluctuation
=== RUN   TestWriteTimeoutFluctuation
--- PASS: TestReadTimeoutFluctuation (0.11s)
--- PASS: TestWriteTimeoutFluctuation (0.11s)
--- PASS: TestReadFromTimeoutFluctuation (0.11s)
=== RUN   TestReadTimeoutFluctuation
=== RUN   TestReadFromTimeoutFluctuation
=== RUN   TestWriteTimeoutFluctuation
--- PASS: TestReadTimeoutFluctuation (0.11s)
--- PASS: TestWriteTimeoutFluctuation (0.14s)
--- PASS: TestReadFromTimeoutFluctuation (0.12s)
=== RUN   TestReadTimeoutFluctuation
=== RUN   TestReadFromTimeoutFluctuation
=== RUN   TestWriteTimeoutFluctuation
--- PASS: TestReadTimeoutFluctuation (0.12s)
--- PASS: TestWriteTimeoutFluctuation (0.12s)
--- PASS: TestReadFromTimeoutFluctuation (0.12s)
=== RUN   TestReadTimeoutFluctuation
=== RUN   TestReadFromTimeoutFluctuation
=== RUN   TestWriteTimeoutFluctuation
--- PASS: TestReadTimeoutFluctuation (0.11s)
--- PASS: TestWriteTimeoutFluctuation (0.14s)
--- PASS: TestReadFromTimeoutFluctuation (0.12s)
=== RUN   TestReadTimeoutFluctuation
=== RUN   TestReadFromTimeoutFluctuation
=== RUN   TestWriteTimeoutFluctuation
--- PASS: TestReadTimeoutFluctuation (0.11s)
--- PASS: TestWriteTimeoutFluctuation (0.14s)
--- PASS: TestReadFromTimeoutFluctuation (0.12s)
=== RUN   TestReadTimeoutFluctuation
=== RUN   TestReadFromTimeoutFluctuation
=== RUN   TestWriteTimeoutFluctuation
--- PASS: TestReadTimeoutFluctuation (0.11s)
--- PASS: TestWriteTimeoutFluctuation (0.14s)
--- PASS: TestReadFromTimeoutFluctuation (0.12s)
=== RUN   TestReadTimeoutFluctuation
=== RUN   TestReadFromTimeoutFluctuation
=== RUN   TestWriteTimeoutFluctuation
--- PASS: TestReadTimeoutFluctuation (0.11s)
--- PASS: TestWriteTimeoutFluctuation (0.14s)
--- PASS: TestReadFromTimeoutFluctuation (0.12s)
=== RUN   TestReadTimeoutFluctuation
=== RUN   TestReadFromTimeoutFluctuation
=== RUN   TestWriteTimeoutFluctuation
--- PASS: TestReadTimeoutFluctuation (0.11s)
--- PASS: TestWriteTimeoutFluctuation (0.14s)
--- PASS: TestReadFromTimeoutFluctuation (0.12s)
PASS
Socket statistical information:
(inet4, stream, default): opened=32 connected=16 listened=16 accepted=0 closed=32 openfailed=0 connectfailed=16 listenfailed=0 acceptfailed=0 closefailed=0
(inet4, datagram, default): opened=16 connected=8 listened=0 accepted=0 closed=16 openfailed=0 connectfailed=0 listenfailed=0 acceptfailed=0 closefailed=0

ok      net     1.877s

**Comment by bcmills** [comment] 2021-01-22 14:43
Duplicate of #36108

**Closed by bcmills** 2021-01-22 14:43 UTC
Labels: NeedsFix, OS-OpenBSD, Testing, help wanted
