### ISSUE TITLE
Generics: Bug: Go compiler doesn't infer types correctly 

### ISSUE THREAD

**Issue by pjebs** [golang/go#55335] opened 2022-09-22 05:36 UTC
I am providing a code snippet that is almost the same. One works. One does not.

**This works:**

```go
package main

import ("fmt"; "strconv"; "golang.org/x/exp/constraints";)

var m = map[string]string{
	"AB": "ab",
}

type Z interface {
	constraints.Integer | string
}

func Func2[N Z](s string, defaultVal N) N {
	x, present := m[s]
	if !present {
		return defaultVal
	}

	switch any(defaultVal).(type) {
	case int:
		nn, _ := strconv.ParseInt(x, 10, 0)
		return N(nn)
	}
	return *new(N)
}

func main() {
	fmt.Println(Func2("ABC", 1))
}

```

The moment I add in the string case, it fails to compile:

**This fails to compile**

```go
package main

import ("fmt"; "strconv"; "golang.org/x/exp/constraints";)

var m = map[string]string{
	"AB": "ab",
}

type Z interface {
	constraints.Integer | string
}

func Func2[N Z](s string, defaultVal N) N {
	x, present := m[s]
	if !present {
		return defaultVal
	}

	switch any(defaultVal).(type) {
	case string:
		return N(x)
		//return x                               // doesn't work either
	case int:
		nn, _ := strconv.ParseInt(x, 10, 0)
		return N(nn)
	}
	return *new(N)
}

func main() {
	fmt.Println(Func2("ABC", 1))
}
```

See: https://go.dev/play/p/3sIQYjxqXL8

**I get the nonsensical error message:** `cannot convert string to int (in N)`

According to https://github.com/golang/go/issues/55329, my prima-facie belief is that this is intended behaviour.
If that is the case, I will recast the issue as a proposal because I think it should be supported.

**Comment by seankhliao** [comment] 2022-09-22 08:10
Duplicate of #45380

**Closed by seankhliao** 2022-09-22 08:10 UTC

**Comment by pjebs** [comment] 2022-09-22 10:26
Here is a work around:

```go
import "unsafe"
return *(*N)(unsafe.Pointer(&x))
```

**Comment by go101** [comment] 2022-09-23 02:35
The workaround changes the behavior the program.

The reason why the original program fails to compile is `string->Interger` conversions are not allowed in Go.

**Comment by pjebs** [comment] 2022-09-23 03:10
@go101 There is NO string -> integer conversions in the example.

**Comment by ianlancetaylor** [comment] 2022-09-23 03:19
> I get the nonsensical error message: cannot convert string to int (in N)

I think that you are assuming that the cases in the type switch are only compiled if the type argument matches the type switch case.  That is not how it works.  The entire type switch is compiled.  Your code includes the line `return N(x)`.  Here `x` is type `string`.  The only thing known about `N` is that is satisfies the constraint `Z`.  The conversion `N(x)` is only permitted if `string` may be converted to all of the types in the type set of `Z`.  One of the types in the type set of `Z` is `int`.  Go does not permit converting the type `string` to the type `int`.  Hence the error message.

**Comment by pjebs** [comment] 2022-09-23 03:26
@ianlancetaylor Is there anything wrong with the workaround I wrote above?

**Comment by ianlancetaylor** [comment] 2022-09-23 03:36
Using the unsafe package is never a good sign.  I think the code will work but it's awfully ugly.

**Comment by pjebs** [comment] 2022-09-23 03:39
What is the idiomatic way to achieve what I'm trying to do?

**Comment by ianlancetaylor** [comment] 2022-09-23 04:32
I'm not sure I understand what you are trying to do.  You are converting a string to a destination type, but you are using different code for each possible destination type?  That's basically what the flag package does, and it does it without generics by using a different support type for each possible destination type.  Or you could use reflection.  At first glance this doesn't seem like a good fit for generics.  If a substantial part of your function is a type switch where the cases are handled differently, generics doesn't seem like the natural choice.
