### ISSUE TITLE
proxy.golang.org: how to get rid of wrong version in the proxy

### ISSUE THREAD

**Issue by pstibrany** [golang/go#35418] opened 2019-11-07 09:22 UTC
We have accidentally pushed dummy tag v6.7.8 to our repository several months ago, and even though it has been removed since then, proxy still remembers it. Our project is at 0.4.0 at the moment. How can we get get rid of that dummy version from golang proxy? People trying to use our client library are getting old v6.7.8 now. (github.com/grafana/loki v6.7.8+incompatible)

https://proxy.golang.org suggests that we need to publish new version, but that will only be 0.5.0 or perhaps 1.0.0.

Thanks.

**Comment by bcmills** [comment] 2019-11-07 13:56
The unfortunate news is, there is no way in general to get rid of a valid version in the proxy.

The good news is, [CL 204440](https://golang.org/cl/204440) has landed for Go 1.14, so as long as your latest compatible tagged version has a `go.mod` file, users on 1.14 (once it is released) will pick up the correct version instead of the erroneous `+incompatible` one.

CC @katiehockman @heschik @hyangah

**Comment by bcmills** [comment] 2019-11-07 13:57
Duplicate of #34189

**Closed by bcmills** 2019-11-07 13:57 UTC
Labels: Unfortunate, modules

**Comment by pstibrany** [comment] 2019-11-07 19:29
I am trying to understand what can we do in this situation, except waiting for 1.14 and bumping version to v7. I guess we need to ask our users to use GOPROXY=direct when getting our module.

**Comment by heschik** [comment] 2019-11-07 19:35
`go get github.com/grafana/loki@v0` is a little better than that, at least.
