### ISSUE TITLE
Cross compilation from windows 10 to raspberry pi CGO_ENABLED = 1

### ISSUE THREAD

**Issue by guanicoe** [golang/go#45901] opened 2021-05-01 13:25 UTC
Hi, 

I wish to compile for a raspberry pi from my windows machine (much faster). 
Everything works if I use this command: 
`env GOOS=linux GOARCH=arm GOARM=5 go build src/*.go`

However, I am using `go-sqlite3` which apparently requires CGO_ENABLED = 1

` Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub `

When I change the compilation command  to `env GOOS=linux GOARCH=arm GOARM=5 CGO_ENABLED=1 go build src/*.go`
I get an error on windows

```
$ env GOOS=linux GOARCH=arm GOARM=5 CGO_ENABLED=1 go build src/*.go
# runtime/cgo
cgo: exec C:\Program: exec: "C:\\Program": file does not exist
```

This looks like a simple fix, but I'm now very conferable with cross compilation. I cannot find much online.

**Comment by ZekeLu** [comment] 2021-05-01 14:21
I think you need to install a gcc compiler and have it in your PATH environment variable. See the wiki for more information: https://github.com/golang/go/wiki/cgo#windows.

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Comment by seankhliao** [comment] 2021-05-01 15:39
Duplicate of #41400

**Closed by seankhliao** 2021-05-01 15:39 UTC

**Comment by guanicoe** [comment] 2021-05-01 19:05
I figured out my problem and also posted the answer here

https://stackoverflow.com/questions/67346813/cross-compilation-from-windows-10-to-raspberry-pi-cgo-enabled-
1/67349928#67349928
