### ISSUE TITLE
net/http: Add failsafe on status code 301 but response behaves as 200 status code

### ISSUE THREAD

**Issue by ronysandoval** [golang/go#50579] opened 2022-01-12 20:01 UTC
### What is the URL of the page with the issue?
https://httpbun.com/status/301

### What is your user agent?
Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0

### Screenshot

![image](https://user-images.githubusercontent.com/70396720/149211549-05a3e0bb-22c7-40aa-802d-8163ff1c9326.png)
![image](https://user-images.githubusercontent.com/70396720/149212744-27061239-f5db-41c7-bcc6-1209ac1b9c93.png)

### What did you do?

When you are doing a normal fetch and the response is 301 status code, there should be a fail-safe because some sites are throwing this but returning content and behaves like 200 response, this request keeps failing because they don't send Location header as a normal 301 response should do, the page also have content-type and content-length so maybe be validated by that headers.
This response works when doing curl or visiting from normal browser.

### What did you expect to see?
I expect to see the response like a normal fetch when page contains content-length and content-type but no Location header.

### What did you see instead?
I get an error message that says the following:
'301 response missing Location header'

**Comment by davecheney** [comment] 2022-01-12 21:37
Thank you for raising this issue. You mentioned that Is is related to the net/http package, but your issue report contains no go code. Would it be possible for you to provide a short, stand alone, runnable program that demonstrates the issue you are experiencing. Thank you.

**Comment by ronysandoval** [comment] 2022-01-12 21:58
You can get the code example from here: https://rafallorenz.com/go/customize-http-client/
but basically when the request is executed and this function is called 
*http.Client.Do(req) is where should go to do the normal fetch
having this on the library
func (c *Client) Do(req *Request) (*Response, error) {
	return c.do(req)
}
and that library is currently at /usr/lib/go/src/net/http/client.go

**Comment by seankhliao** [comment] 2022-01-12 22:24
Duplicate of #49281

**Closed by seankhliao** 2022-01-12 22:24 UTC
Labels: WaitingForInfo
