### ISSUE TITLE
x/website:

### ISSUE THREAD

**Issue by ragsna** [golang/go#44401] opened 2021-02-18 23:38 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.8 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes (latest website)

### What did you do?
On https://golang.org/doc/ clicked the link "Writing Web Applications"

### What did you expect to see?
Link should have opened

### What did you see instead?
Page https://golang.org/doc/articles/wiki/
Error message: "open REDACTED: file does not exist"

**Comment by seankhliao** [comment] 2021-02-19 07:38
Duplicate of #44314

**Closed by seankhliao** 2021-02-19 07:38 UTC
