### ISSUE TITLE
cmd/go: replace directive mutated when run go mod tidy

### ISSUE THREAD

**Issue by slinkydeveloper** [golang/go#40429] opened 2020-07-27 14:17 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/slinkydeveloper/.cache/go-build"
GOENV="/home/slinkydeveloper/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/slinkydeveloper/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build499797199=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I'm trying to test a personal fork of a dependency in a project, and i'm using the replace directive as follows:

```
knative.dev/pkg => github.com/slinkydeveloper/pkg serious_port_forwarding
```

For some reason, when i run `go mod tidy` to update the deps, the replace directive is mutated replacing it with the actual commit hash

```
knative.dev/pkg => github.com/slinkydeveloper/pkg v0.0.0-20200724072217-fc14798189e0
```

which means that every time i update my fork, i need to update the directive and retrigger the update with `go mod tidy` 

### What did you expect to see?

replace directive should not mutate. To be precise, I expect them to be immutable in all situations because they're hand made directives to instruct to tool where and which versions of the code to pick 

### What did you see instead?

replace directive mutates.

**Comment by bcmills** [comment] 2020-07-27 16:30
The `go.mod` file is intended to provide reproducible builds. A branch that may move is (by definition) not reproducible, so this is working as designed.

**Comment by bcmills** [comment] 2020-07-27 16:32
I think #32721 and #26964 would suffice to allow a `replace` directive to be upgraded following a branch.

**Comment by bcmills** [comment] 2020-07-27 16:33
Duplicate of #32721

**Closed by bcmills** 2020-07-27 16:33 UTC
Labels: modules
