### ISSUE TITLE
https://golang.org/pkg/ no longer lists packages in alphabetical order

### ISSUE THREAD

**Issue by ecc1** [golang/go#24622] opened 2018-03-31 16:28 UTC
There are now two alphabetical sublists ("archive".."unicode" and "bufio".."unsafe"). According to the Wayback Machine, this changed some time after March 26, 2018.

**Comment by AlexRouSg** [comment] 2018-03-31 16:42
dupe of #24601

**Comment by kardianos** [comment] 2018-03-31 16:56
Closed. Dup of #24601

**Closed by kardianos** 2018-03-31 16:56 UTC
