### ISSUE TITLE
x/tools/gopls: nil pointer dereference when opening new buffer (i.e. no file on disk)

### ISSUE THREAD

**Issue by myitcv** [golang/go#35994] opened 2019-12-05 13:53 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +acf3ff2e8a Tue Dec 3 17:35:06 2019 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20191205133340-d1f10d1c4e25
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.1.8-0.20191205133340-d1f10d1c4e25
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build453665783=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

In the context of a simple module, i.e. a `go.mod` that exists on disk:

```
module mod.com
```

Open Vim (using `govim`) as follows:

```
vim main.go
```

where `main.go` is a new buffer, i.e. no file exists on disk.

### What did you expect to see?

No error

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa87555]

goroutine 114 [running]:
golang.org/x/tools/internal/lsp/cache.(*snapshot).View(0x0, 0xc000684000, 0x498dbf)
   /home/myitcv/gostuff/pkg/mod/golang.org/x/tools@v0.0.0-20191205133340-d1f10d1c4e25/internal/lsp/cache/snapshot.go:61 +0x5
golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshot(0xc000231080, 0xd8ed60, 0x0)
   /home/myitcv/gostuff/pkg/mod/golang.org/x/tools@v0.0.0-20191205133340-d1f10d1c4e25/internal/lsp/diagnostics.go:20 +0x7d
created by golang.org/x/tools/internal/lsp.(*Server).addFolders
   /home/myitcv/gostuff/pkg/mod/golang.org/x/tools@v0.0.0-20191205133340-d1f10d1c4e25/internal/lsp/general.go:173 +0x600
```

---

cc @stamblerre

**Comment by stamblerre** [comment] 2019-12-06 20:19
Duplicate of https://github.com/golang/go/issues/36020

**Closed by stamblerre** 2019-12-06 20:19 UTC
Labels: NeedsInvestigation, Tools, gopls
