### ISSUE TITLE
runtime: android logging corruption on Android 5.1

### ISSUE THREAD

**Issue by crawshaw** [golang/go#12008] opened 2015-08-04 00:19 UTC
I was debugging over someone's shoulder today and their panic as written to logcat was corrupt:

```
W/logd    (26732): Dropped 6
?/o       (26732): unexpected fault address 0x0
W/logd    (26732): Dropped 6
?/o       (26732): fatal error: fault
W/logd    (26732): Dropped 6
?/o       (26732): [signal 0x7 code=0x1 addr=0x0 pc=0xa5b5cd30]
W/logd    (26732): Dropped 6
W/logd    (26732): Dropped 6
?/o       (26732): goroutine 32 [running]:
```

There may be a change the logdw format, or we may have always had it slightly wrong but it worked with older Android versions.

I see some suggestions on the internet that the wire format is the layout of ```struct logger_entry_v3```, which looks similar to but not the same as what we are writing:

https://android.googlesource.com/platform/system/core/+/master/include/log/logger.h

/cc @hyangah

**Comment by hyangah** [comment] 2015-08-04 02:23
I believe log_entry and (logger_entry_*) are for reading log data.
For writing this is the relevant part:
https://github.com/android/platform_system_core/blob/master/liblog/logd_write.c

Looking at the history, indeed there are some changes we have to pick up (those checked in after March).

**Comment by hyangah** [comment] 2015-08-04 02:26
BTW, for long term, we need to find a better solution. Currently we are relying on Android's private api (protocol between liblog and logger) which means it can break any time.

**Comment by crawshaw** [comment] 2015-08-05 01:19
Further investigation suggests this is a very isolated behavior. The exact device I saw it on was a T-Mobile Moto X (2nd gen) running Android 5.1.

I could not replicate the problem on a Nexus 7 (2nd gen) running Android 5.1.1.

**Comment by rsc** [comment] 2015-11-05 17:15
Seems like we can't do anything unless this can be reproduced.

**Closed by rsc** 2015-11-05 17:15 UTC
Labels: OS-Android

**Comment by xiam** [comment] 2015-11-20 03:59
Just in case you came here looking for the reason why Android Studio is full of "Dropped: 6" lines, try using "adb logcat" instead.
