### ISSUE TITLE
encoding/xml: different marshal behavior in the Go 1.21.6

### ISSUE THREAD

**Issue by picollomartin** [golang/go#65066] opened 2024-01-11 20:32 UTC
### Go version

go version go1.21.6 darwin/amd64

### Output of `go env` in your module/workspace:

```shell
N/A
```

### What did you do?

```golang
package main

import (
	"encoding/xml"
	"fmt"
)

func main() {
	type B struct {
		XMLName xml.Name
		ID      string `xml:"id"`
	}

	type A struct {
		XMLName xml.Name `xml:"http://example.com a"`
		B       B        `xml:"b"`
	}

	output, err := xml.Marshal(&A{B: B{ID: "1"}})
	if err != nil {
		fmt.Println(err)
	}

	fmt.Printf("output: %s", string(output))
}
```

Playground example [here](https://go.dev/play/p/14lC4kTikn3)

### What did you see happen?

Output in go 1.21.6

```
output: <a xmlns="http://example.com"><b xmlns=""><id>1</id></b></a>
```

### What did you expect to see?

Output in go 1.20

```
output: <a xmlns="http://example.com"><b><id>1</id></b></a>
```

It's similar to #61881, but this case it's like a bad use of XMLName tag, this break for us but can be fixed removing the XMLName tag not used, but previous versions simply ignored that

**Comment by seankhliao** [comment] 2024-01-11 21:12
Duplicate of #64166

**Closed by seankhliao** 2024-01-11 21:12 UTC
