### ISSUE TITLE
cmd/go: go module not forwarding credentials from .netrc to gitlab subgroups

### ISSUE THREAD

**Issue by tigrato** [golang/go#29888] opened 2019-01-23 11:48 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go 1.11.4

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tiago/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/tiago/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/tiago/go/src/gitlab.adinsertp.net/dai-platform/backend-services/media-cache/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mw/2d5q259n04s64_ylppwvmr9h0000gn/T/go-build740296391=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
Last Gitlab release (11.7) enabled go modules downloads for nested groups. It requires authentication for private groups/projects using .netrc file when requesting `?go-get=1` allowing gitlab to understand if the user has the correct access perms for the requested repo.
In case of valid credentials and perms the user should get a go import tag with the project that owns the requested repo.

My $HOME/.netrc file:
`
machine gitlab.mydomain.com login myuser password mysecrettocken
`

So I was trying to use `go get -v gitlab.mydomain.com/groupA/subGroupB/project/pkg`

### What did you expect to see?
I expected that `go get` was able to send the http credentials in .netrc and get the repo that owns the imported package and be able to download it.

### What did you see instead?
<details><summary><code>go get -v gitlab.mydomain.com/groupA/subGroupB/project/pkg</code> Output</summary><br><pre>
Fetching https://gitlab.mydomain.com/groupA/subgroupB/project/pkg?go-get=1
Parsing meta tags from https://gitlab.mydomain.com/groupA/subgroupB/project/pkg?go-get=1 (status code 200)
get "gitlab.mydomain.com/groupA/subgroupB/project": found meta tag get.metaImport{Prefix:"gitlab.mydomain.com/groupA/subgroupB", VCS:"git", RepoRoot:"https://gitlab.mydomain.com/groupA/subgroupB.git"} at https://gitlab.mydomain.com/groupA/subgroupB/project/pkg?go-get=1
get "gitlab.mydomain.com/groupA/subgroupB/project": verifying non-authoritative meta tag
Fetching https://gitlab.mydomain.com/groupA/subgroupB?go-get=1
Parsing meta tags from https://gitlab.mydomain.com/groupA/subgroupB?go-get=1 (status code 200)
Fetching https://gitlab.mydomain.com/groupA/subgroupB?go-get=1
Parsing meta tags from https://gitlab.mydomain.com/groupA/subgroupB?go-get=1 (status code 200)
get "gitlab.mydomain.com/groupA/subgroupB": found meta tag get.metaImport{Prefix:"gitlab.mydomain.com/groupA/subgroupB", VCS:"git", RepoRoot:"https://gitlab.mydomain.com/groupA/subgroupB.git"} at https://gitlab.mydomain.com/groupA/subgroupB?go-get=1
Fetching https://gitlab.mydomain.com/groupA?go-get=1
Parsing meta tags from https://gitlab.mydomain.com/groupA?go-get=1 (status code 200)
Fetching https://gitlab.mydomain.com?go-get=1
Parsing meta tags from https://gitlab.mydomain.com?go-get=1 (status code 200)
go get gitlab.mydomain.com/groupA/subgroupB/project: git ls-remote -q https://gitlab.mydomain.com/groupA/subgroupB.git in /xxx/go/pkg/mod/cache/vcs/5624e7b98ccb36067492e57ba75205fe3d693c9affee381093003e5268dbcaaf: exit status 128:
	remote: The project you were looking for could not be found.
	fatal: repository 'https://gitlab.mydomain.com/groupA/subgroupB.git/' not found
</pre></details>

Which fails because it didn't find the correct repository in gitlab.  Although if I run:
curl -n https://gitlab.mydomain.com/groupA/subGroupB/project/pkg?go-get=1`:

`<html><head><meta name="go-import" content="gitlab.mydomain.com/groupA/subGroupB/project git https://gitlab.mydomain.com/groupA/subGroupB/project.git" /></head></html>`
Which returns the correct repository path.

As far I can see, go get is not forwarding .netrc credentials when using subgroups.

**Comment by bcmills** [comment] 2019-01-24 12:10
Duplicate of #26232?

**Comment by vmatyusGitHub** [comment] 2019-02-06 11:51
I encounter the same problem. 
Is there a go command flag or environment setting that can enable the connection with `.netrc`?

In the `cmd\go\internal\web2\web.go` can be found implementation of sending a GET request with .netrc config. But I think they are not used during `go get` and `go build` commands.

**Comment by bcmills** [comment] 2019-02-07 19:18
No flag should be necessary. Is it possible that your `.netrc` file is not located in `$HOME/.netrc` (`%USERPROFILE%/_netrc` on Windows)?

**Comment by vmatyusGitHub** [comment] 2019-02-07 20:25
I tried out on Windows and on Linux. The `netrc` file was at the proper place in both cases.
With `curl -n` I could receive the correct git repoRoot.

**Comment by nilium** [comment] 2019-02-07 20:27
From what I can see, `go get` does not currently use the cmd/go/internal/web2 package that handles netrc loading -- only `go mod download` would (which works off a different protocol). So, that may explain why `go get -v ...` doesn't show it -- it's because it doesn't use netrc. Based on #26232, it seems like whether this will even be supported is still in planning.

**Comment by tigrato** [comment] 2019-02-12 22:09
> From what I can see, `go get` does not currently use the cmd/go/internal/web2 package that handles netrc loading -- only `go mod download` would (which has different response expectations than `go get`, I think?). So, that may explain why `go get -v ...` doesn't show it -- it's because it doesn't use netrc. Based on #26232, it seems like whether this will even be supported is still in planning.

In this case it is important to have .netrc support for the go get since we can clone the git repo using ssh/git credentials but we cannot discover the repo that owns the package without it.



> No flag should be necessary. Is it possible that your `.netrc` file is not located in `$HOME/.netrc` (`%USERPROFILE%/_netrc` on Windows)?
My `.netrc` is correctly located in `$HOME/.netrc` as you can see from the curl command with `-n`

**Comment by tigrato** [comment] 2019-02-16 15:23
@bcmills Some more information

Meta import tag request (...?go-get=1)  is done using function https://github.com/golang/go/blob/dca707b2a040642bb46aa4da4fb4eb6188cc2502/src/cmd/go/internal/get/vcs.go#L855-L886
Which relies on  `web.GetMayBeInsecure` function 
https://github.com/golang/go/blob/dca707b2a040642bb46aa4da4fb4eb6188cc2502/src/cmd/go/internal/web/http.go#L76-L119

This last  internally  uses the `http.DefaultClient` and does not have any type of authentication or `.netrc` parsing as happens in the web2 package.

**Comment by gabrielruiu** [comment] 2019-02-17 21:56
Ran into same problem which led me to this github issue. At this point it's a blocker and can't use private gitlab repositories as libraries for other go projects. Any workaround or fix will be greatly appreciated. I see this is tagged to be in Go `1.13`. If by chance it's possible, releasing it in Go `1.12` would greatly help.

**Comment by MeirionHughes** [comment] 2019-02-21 17:22
yeah I'm really struggling too - just moved from nodejs to go and this really is a pain point for me too (gitlab private nested packages). I kinda just want to pay for npm-like private repos and just have something that works off the bat.

**Comment by ByteFlinger** [comment] 2019-03-01 15:56
Same issue here with Go `1.12`

Works with curl

```bash
$ curl -k -n https://gitlab.com/group/subgroup/myrepo?go-get=1
<html><head><meta name="go-import" content="gitlab.com/group/subgroup/myrepo git https://gitlab.com/group/subgroup/myrepo.git" /></head></html>
```

But when I try Go get it fails

```bash
$ go get -v gitlab.com/group/subgroup/myrepo
Fetching https://gitlab.com/group/subgroup/myrepo?go-get=1
Parsing meta tags from https://gitlab.com/group/subgroup/myrepo?go-get=1 (status code 200)
get "gitlab.com/group/subgroup/myrepo": found meta tag get.metaImport{Prefix:"gitlab.com/group/subgroup", VCS:"git", RepoRoot:"https://gitlab.com/group/subgroup.git"} at https://gitlab.com/group/subgroup/myrepo?go-get=1
get "gitlab.com/group/subgroup/myrepo": verifying non-authoritative meta tag
Fetching https://gitlab.com/group/subgroup?go-get=1
Parsing meta tags from https://gitlab.com/group/subgroup?go-get=1 (status code 200)
Fetching https://gitlab.com/group/subgroup?go-get=1
Parsing meta tags from https://gitlab.com/group/subgroup?go-get=1 (status code 200)
get "gitlab.com/group/subgroup": found meta tag get.metaImport{Prefix:"gitlab.com/group/subgroup", VCS:"git", RepoRoot:"https://gitlab.com/group/subgroup.git"} at https://gitlab.com/group/subgroup?go-get=1
Fetching https://gitlab.com/group?go-get=1
Parsing meta tags from https://gitlab.com/group?go-get=1 (status code 200)
Fetching https://gitlab.com?go-get=1
Parsing meta tags from https://gitlab.com?go-get=1 (status code 200)
go get gitlab.com/group/subgroup/myrepo: git ls-remote -q https://gitlab.com/group/subgroup.git in /home/alethenorio/go/pkg/mod/cache/vcs/3e751597139208a6e518d0bd38652d0e04d1c2a63f7d667f6fb54374ccef23c7: exit status 128:
	remote: The project you were looking for could not be found.
	fatal: repository 'https://gitlab.com/group/subgroup.git/' not found
```

**Comment by thepudds** [comment] 2019-03-14 15:38
Would someone here who has experienced a problem on this issue be willing to open up a problem report on the GitLab side? Maybe it is a case of documentation being incorrect, or maybe there is a bug on the GitLab side, or maybe there is a bug on the `go` tool side... but one of the challenges is I would assume the core Go team are not expert GitLab users and hence it would likely be worthwhile to make sure someone from GitLab is also looking at this set of problem(s). Perhaps there is a workaround, for example, or other possible near-term solution...

**Comment by MeirionHughes** [comment] 2019-03-15 09:49
Its already documented that the issue is `go` does not authenticate when it tries to access `https://gitlab.com/my/private/repo` this in-turn means gitlab returns the incorrect `gitlab.com/my/repo.git` path _by design_ so as to not give away folder structure within a private organization. 

The following code comment documents this: 

```
# If a project is found and the user has access, we return the full project path
# If not, we return the first two components as if it were a simple `namespace/project` path,
# so that we don't reveal the existence of a nested project the user doesn't have access to.
# This means that for an unauthenticated request to `group/subgroup/project/subpackage`
# for a private `group/subgroup/project` with subpackage path `subpackage`, GitLab will respond
# as if the user is looking for project `group/subgroup`, with subpackage path `project/subpackage`.
# Since `go get` doesn't authenticate by default, this means that
# `go get gitlab.com/group/subgroup/project/subpackage` will not work for private projects.
# `go get gitlab.com/group/subgroup/project.git/subpackage` will work, since Go is smart enough
# to figure that out. `import 'gitlab.com/...'` behaves the same as `go get`.
```
https://gitlab.com/gitlab-org/gitlab-ce/issues/37832

Currently the only robust way I know of is to a) add a system ssh key pair that `git` will use and b) have `go mod` redirect the package to a full git path: i.e. ```
go.mod: 

module gitlab.com/my/private/group/foo

go 1.12

require (
	gitlab.com/my/private/group/bar v0.0.1
)

replace gitlab.com/my/private/group/bar => gitlab.com/my/private/group/bar.git v0.0.11

```

this allows the importing (within go) of `gitlab.com/my/private/group/bar` 

certainly works, but requires manually updating the go.mod file if you want to change versions

**Comment by thepudds** [comment] 2019-03-16 15:58
The original report here in https://github.com/golang/go/issues/29888#issue-402201904 says:
> As far I can see, go get is not forwarding .netrc credentials when using subgroups.

The issue one liner here currently reads "cmd/go: go module not forwarding credentials from .netrc to gitlab subgroups".

This issue on the gitlab side was opened a year ago, and is currently closed:
https://gitlab.com/gitlab-org/gitlab-ce/issues/37832

The [GitLab 11.7 release notes](https://about.gitlab.com/2019/01/22/gitlab-11-7-released/#support-for-private-go-packages-in-subgroups) from roughly 2 months ago say:

> Go packages hosted in GitLab can be installed using go get, however this was not supported for private projects in subgroups. Starting with GitLab 11.7, any project can be used as a Go package, including private projects in subgroups.
> 
> Private packages are supported by the go get command using a .netrc file, and using a personal access token in the password field.
> 
> Thank you MortyChoi for the contribution!

I was pointed to this particular #29888 issue here by someone who stated roughly that the support for private projects in subgroups released in GitLab 11.7 "doesn't work at all".

Part of what I am not following is:
1. Did GitLab release and announce a capability in GitLab 11.7 that states it supports private projects in subgroups with the `go` command using a .netrc file, but that new capability never worked end-to-end with the `go` command?
2. If using a .netrc for private projects in subgroups with GitLab 11.7+ does work in some cases, what are those cases? (For example, does a .netrc with private projects in subgroups with GitLab 11.7+ work as long as one does `go get gitlab.com/group/subgroup/project.git/subpackage` rather than `go get gitlab.com/group/subgroup/project/subpackage`?)

**Comment by tigrato** [comment] 2019-03-16 16:18
@thepudds 
1) yes, they released it without it ever worked for private repos. It is impossible because when go tries to discover the repo that owns the go package with `?go-get=1` request it does not forward the .netrc credentials. For this go uses a function that is part of `web` module and credentials are only supported in `web2` module as I have previously mentioned.

2) it only works if all paths (groups, subgroups and repos) are public and open access otherwise it will fail.

**Comment by thepudds** [comment] 2019-03-16 16:43
Thanks for the answers. It seems surprising given what their release notes say.

I guess I'll ask again if anyone here is willing or interested in opening up an issue on the GitLab side. It seems they should at least update their documentation or release notes.  It might also trigger a GitLab employee to show up here and comment further, which might help advance the resolution for this issue here.  (I am not a GitLab user, so I am probably not the best person to open an issue there).

**Closed** 2019-04-23 21:17 UTC
Labels: NeedsInvestigation, WaitingForInfo, modules
