### ISSUE TITLE
cmd/go:  invalid module: gopkg.in/inf.v0 should be .v0, not v1 (v1.9.1-gopkgin-v0.9.1)

### ISSUE THREAD

**Issue by krasi-georgiev** [golang/go#31253] opened 2019-04-04 10:21 UTC
go1.12.1 linux/amd64

```
go test github.com/jaegertracing/jaeger/plugin/storage/badger/dependencystore -run ^(TestDependencyReader)$ 

go: github.com/gocql/gocql@v0.0.0-20180506184654-181004e14a3f: parsing go.mod: go.mod:6: invalid module: gopkg.in/inf.v0 should be .v0, not v1 (v1.9.1-gopkgin-v0.9.1)
go: error loading module requirements
```

**Comment by andybons** [comment] 2019-04-04 16:56
@bcmills @jayconrod

**Comment by bcmills** [comment] 2019-04-04 17:58
I can reproduce the error; still investigating why it occurs. (I need to rebuild to pick up @jayconrod's new module-loader diagnostics!)

**Comment by bcmills** [comment] 2019-04-04 18:15
The error comes directly from an old version of `github.com/gocql/gocql` that does indeed specify an invalid version:
https://github.com/gocql/gocql/blob/611715ed8a5e3a3165dd2609e4e3c8ff7d0c774e/go.mod#L6

So the diagnostic message as reported is correct, and probably as precise as we can make it.

That version of `github.com/gocql/gocql` comes in by conversion of the existing `jaeger/Gopkg.lock`:
https://github.com/jaegertracing/jaeger/blob/7da22606eccbb4246f7cd2f3871ec6b491257b68/Gopkg.lock#L303

To fix `jaegertracing/jaeger`, it suffices to remove and re-resolve the `gocql` dependency:
```
jaeger$ go1.12.1 mod init github.com/jaegertracing/jaeger
go: creating new go.mod: module github.com/jaegertracing/jaeger
go: copying requirements from Gopkg.lock

jaeger$ go1.12.1 mod edit -droprequire=github.com/gocql/gocql

jaeger$ go1.12.1 mod tidy
go: finding github.com/onsi/ginkgo/extensions/table latest
go: finding github.com/prashantv/protectmem latest
go: finding github.com/streadway/quantile latest
go: finding github.com/bmizerany/perks/quantile latest
go: finding github.com/onsi/ginkgo/extensions latest
go: finding github.com/bmizerany/perks latest
go: finding github.com/gocql/gocql latest
go: finding github.com/bitly/go-hostpool latest
go: finding github.com/bmizerany/assert latest

jaeger$ go1.12.1 build ./...

jaeger$
```

This is somewhat related to #26454 and #30831, in that it should be possible to upgrade past the error (using `go get github.com/gocql/gocql@latest`) rather than removing and re-resolving the dependency. Today that does not work, because the error in resolving the initial `gopkg.in/inf.v0` causes the whole operation to fail before the upgrades are attempted.

**Comment by bcmills** [comment] 2019-04-04 18:16
Closing as a duplicate of #30831: the symptoms are a bit different, but the underlying pathology (having an existing bad dependency and not being able to upgrade out of it) will probably be fixed by the same set of changes.

**Closed by bcmills** 2019-04-04 18:16 UTC
Labels: NeedsInvestigation, modules
