### ISSUE TITLE
crypto/tls: set timeout so that Close does not block indefinitely

### ISSUE THREAD

**Issue by NWilson** [golang/go#31224] opened 2019-04-03 11:52 UTC
### What did you do?

Reading the documentation for `tls.Conn` (https://golang.org/pkg/crypto/tls/) the deadline behaviour is not clearly explained.

* It's not obvious that Read calls may block forever unless the _write_ deadline is set to a non-zero time. (This is because handshaking is done internally, which writes.) Since this is different to net.TLSConn, it should be called out.
* It's reasonable to understand that Handshake calls need to have both read and write deadline set... but could be called out explicitly.
* But the killer: calling Close on a tls.Conn risks blocking forever, unless the write deadline has been set! (It writes out a close alert.)

This last one is the worst. It would be very easy to have a defer'ed call to Close, and assume that it will always return promptly, when in fact it _may_ be possible for a malicious client to fill up the socket buffers with handshaking data, so that writing the close alert blocks (on an OS with tiny socket buffers?).

I have (or had) some code that does the following:

```
for {
  conn, _ := listener.Accept() // error handling omitted for clarity
  if tooManyConns() {
    conn.Close() // oops, may block!
    continue
  }
  go handleConn(conn)
}
```

I have now carefully gone and wrapped all calls to Close with a safeClose wrapper method that calls SetWriteDeadline first!

Perhaps Close should actually call SetWriteDeadline on the underlying connection with a sane value (eg `time.Now().Add(100*time.Millisecond)`) to ensure that no-one else is caught out.

Thankfully, http.conn.serve _does_ call SetWriteDeadline as soon as possible for TLS connections, and never sets a zero write deadline, so that code at least is safe, and can't call Close with a zero deadline.

### What did you expect to see?

More mention of what deadlines need to set, to prevent each method blocking.

**Comment by andybons** [comment] 2019-04-03 16:42
@FiloSottile

**Comment by networkimprov** [comment] 2019-04-05 19:03
Assuming the above points are all correct, A lot of folks use the tls API incorrectly. I have a TLS+TCP server that calls SetReadDeadline() and Close(). I don't recall mention of SetWriteDeadline() in any example code I read.

Maybe this calls for additional APIs, e.g. SetTLSReadDeadline() & CloseTLS()? Or a _go vet_ item?

**Comment by networkimprov** [comment] 2019-06-18 06:57
Ping @FiloSottile

**Comment by networkimprov** [comment] 2019-06-26 01:54
@andybons, could this be milestoned for 1.13 and made release-blocker?

Correct use of TLS is a security concern, and one of the suggested fixes is to change .Close() behavior.

**Comment by FiloSottile** [comment] 2019-06-26 03:26
I agree this needs addressing, but it does not warrant changing subtle behavior while in deep feature freeze. The only fix for Go 1.13 will be probably in documentation, and we can discuss in 1.14 with more flexibility.

**Comment by networkimprov** [comment] 2019-07-03 05:30
Thanks, happy to give feedback on the CL when ready...

**Comment by networkimprov** [comment] 2019-07-16 03:24
@FiloSottile, you tagged this for 1.13; it's now been re-tagged for 1.14. Was that a mistake?

**Comment by networkimprov** [comment] 2019-09-11 19:56
@FiloSottile we might want to tackle this one early in 1.14 cycle...

@gopherbot add release-blocker

**Comment by FiloSottile** [comment] 2019-10-01 18:56
I'm thinking of introducing a default deadline on the close notify send, and document in Read and Write, where they say they call Handshake, that that means they need both read and write deadlines.

**Comment by networkimprov** [comment] 2019-10-01 21:12
Re setting a default deadline, is there any conflict with http.Server/Client? See https://github.com/golang/go/issues/21133#issuecomment-317265922

**Comment by FiloSottile** [comment] 2019-10-01 21:41
Reusing a net.Conn after a tls.Close is _weird_ but I suppose not impossible? Sure, we can just reset it before leaving Close.

**Comment by networkimprov** [comment] 2019-10-01 22:04
Just wondering whether the implicit deadlines that http uses might conflict with an implicit deadline in tls.Close?

**Comment by FiloSottile** [comment] 2019-10-01 22:16
Ah, well by the time tls.Close is called it doesn't really matter, does it? We are tearing down, so we can just override them.

**Comment by networkimprov** [comment] 2019-10-01 22:28
@bradfitz any thoughts?

**Comment by bradfitz** [comment] 2019-10-02 14:52
I haven't looked into this issue, but from a quick skim of this thread, it does indeed seem like things are too complicated/surprising for users.

**Comment by networkimprov** [comment] 2019-10-02 15:08
@bradfitz any comment re a new implicit timer in tls.Close? Could that conflict with implicit timers in http?

**Comment by bradfitz** [comment] 2019-10-02 15:27
A new timer in tls.Close sounds good. If crypto/tls doesn't and net/http doesn't already(?), then it seems that net/http should work around any such blocking and close the underlying net.Conn directly. But it might be already. I'd have to go refresh my memory of the code.

In any case, crypto/tls doing it (regardless of whether a higher layer is also doing it) sounds good.

**Comment by ianlancetaylor** [comment] 2019-12-05 20:02
Looks like no change was made for 1.14, so retargeting for 1.15.  Also looks like the current thinking is to change the code, so dropping the documentation label.

**Comment by networkimprov** [comment] 2019-12-05 20:46
This issue entails both:
a docs fix re write deadlines (which should be made ASAP, hence the release-blocker), and
a change to .Close()

Could you put back 1.14 and release-blocker, and we'll change that after the docs fix lands?

**Comment by ianlancetaylor** [comment] 2019-12-06 05:25
If we change the `Close` method then we may not need a doc change.

But if anyone wants to send a doc change, go ahead.  We can always take doc changes even if the issue is targeted to a later release.

**Comment by networkimprov** [comment] 2019-12-06 06:21
@gopherbot add "help wanted"

**Comment by networkimprov** [comment] 2020-09-11 22:07
We have a new report of this: #41340

**Comment by networkimprov** [comment] 2020-10-17 20:23
Could we target this for 1.16?

**Comment by FiloSottile** [comment] 2020-10-20 16:23
The changes here are

* set a Deadline in Close of 5s before sending and trying to read the closeNotify
* call attention to the fact that Read?Write call Handshake so need both deadlines in their docs

**Comment by networkimprov** [comment] 2020-10-28 19:37
Could the docs also give guidance on the deadline durations for Read & Write?

**Comment by katiehockman** [comment] 2020-10-28 20:19
I think that can be in a separate issue/CL. If we were to provide guidance about an appropriate deadline, then that would be more appropriate in the godoc for `SetDeadline`, `SetReadDeadline`, and/or `SetWriteDeadline`, not in `Read` or `Write`.
We would also need to determine what a sensible deadline would be, or how to provide guidance for that.

**Comment by networkimprov** [comment] 2020-10-28 20:28
Since you have to set a write deadline on Read, and a read deadline on Write, it would be helpful to know if there's a minimum value necessary in TLS.

**Comment by katiehockman** [comment] 2020-11-06 15:19
Sure. Feel free to file another issue. That is out of scope for this one.

**Closed** 2020-11-07 02:13 UTC
Labels: NeedsInvestigation, help wanted

**Comment by kozlovic** [comment] 2021-03-04 00:55
@katiehockman @FiloSottile This is a bit unfortunate. I knew it could block, so I was setting my own deadline of 100ms (did not really care if the alert is sent or not, but I did not want it to block. With this change, my code now will block up to 5 seconds. Anything I can do to close the low level connection without blocking here?

**Comment by networkimprov** [comment] 2021-03-04 01:16
Can I ask what services or clients are stalling on close often enough to cause problems?

**Comment by kozlovic** [comment] 2021-03-04 01:21
@networkimprov This is in context of NATS Server. When a client is closed, I try to flush and close the connection. Because of TLS, I was setting a low deadline. I have a test that produced the condition that may cause the TLS close to stall and they started to fail, and I realize that this is because of Go overriding my own deadline: https://github.com/nats-io/nats-server/blob/f82ba22be252755aefbf33af8d66db8cf7421b53/server/client.go#L4352
Here is one of the test that checks for that: https://github.com/nats-io/nats-server/blob/f82ba22be252755aefbf33af8d66db8cf7421b53/server/routes_test.go#L1185

**Comment by networkimprov** [comment] 2021-03-04 03:02
Could you open a new issue to suggest that TLS close not override an existing deadline, or that a tls.Config field be added to let you specify the close deadline? And then mention that issue here. Thanks!

**Comment by networkimprov** [comment] 2021-03-17 23:44
Ping @kozlovic re new issue...

**Comment by kozlovic** [comment] 2021-03-22 16:27
@networkimprov Sorry for delay, took some time off. I created the issue https://github.com/golang/go/issues/45162.
