### ISSUE TITLE
cmd/go: ambiguous import with GOTOOLCHAIN set

### ISSUE THREAD

**Issue by jakecoffman** [golang/go#62282] opened 2023-08-25 14:22 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.21.0 linux/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_arm64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3084179035=/tmp/go-build -gno-record-gcc-switches'

</pre></details>

### What did you do?

Reproduces with this Dockerfile, just run `docker build .`

```dockerfile
FROM golang:1.21

ENV GOTOOLCHAIN=go1.20

RUN git clone https://github.com/M0NsTeRRR/alertmanager-webhook-free.git \
    && cd alertmanager-webhook-free \
    && go get github.com/prometheus/alertmanager@v0.26.0 \
    && go get
```

### What did you expect to see?

No errors

### What did you see instead?

The final `go get` fails with this error.

```
20.15 go: upgraded github.com/prometheus/alertmanager v0.25.0 => v0.26.0
20.35 alertmanager-webhook-free: ambiguous import: found package alertmanager-webhook-free in multiple modules:
20.35   alertmanager-webhook-free (/go/alertmanager-webhook-free)
20.35    (/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.20.linux-arm64/src/alertmanager-webhook-free)
```

It runs without error if I:
 - drop the `GOTOOLCHAIN`
 - use `FROM golang:1.20`
 - try the same steps on darwin

It seems the use of `GOTOOLCHAIN` is creating some kind of path confusion.

**Comment by bcmills** [comment] 2023-08-25 15:13
Duplicate of #61873

**Closed by bcmills** 2023-08-25 15:13 UTC
