### ISSUE TITLE
os/user: compiler warning from the getgrouplist call on darwin{386,amd64}

### ISSUE THREAD

**Issue by rakyll** [golang/go#14700] opened 2016-03-08 00:39 UTC
Seems like getgrouplist is slightly different on darwin.

```
$ man getgrouplist

GETGROUPLIST(3)          BSD Library Functions Manual          GETGROUPLIST(3)

NAME
     getgrouplist -- calculate partial group access list

LIBRARY
     Standard system libraries.

SYNOPSIS
     #include <unistd.h>

     int
     getgrouplist(const char *name, int basegid, int *groups, int *ngroups);
```

```
# os/user
os/user/lookup_unix.go:43:35: warning: passing 'gid_t *' (aka 'unsigned int *') to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/unistd.h:653:43: note: passing argument to parameter here
```

**Comment by josharian** [comment] 2016-03-08 00:42
Duplicate of #14696?

**Closed** 2016-03-08 00:43 UTC
