### ISSUE TITLE
typecast fails with embedded struct

### ISSUE THREAD

**Issue by zeitlinger** [golang/go#33781] opened 2019-08-22 07:29 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
The current version is go1.12.9.
</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

playground

### What did you do?

https://play.golang.org/p/PKug2ap98MI

### What did you expect to see?

Output is true

### What did you see instead?

Output is false

### Why is it considered a bug?

1. `st` implements `in` - I wasn't able to prove this is correct by the spec, but I think this is correct
2. the typecast fails only because the `st` is passed to `f` as an argument, rather than `st.in` (https://play.golang.org/p/J29wZCYw5LU shows this), but this shouldn't matter from the point of view of `f`.

**Comment by av86743** [comment] 2019-08-22 07:50
> ... but this shouldn't matter from the point of view of f.

You are wrong.  It does - as it should.  Typecast is applied to an instance of an actual type `st` which is exposed to implementation of `f` as `in`.

**Comment by ALTree** [comment] 2019-08-22 09:21
This is working as intended. The spec [says](https://golang.org/ref/spec#Type_assertions) (regarding type assertions):

> if T is not an interface type, x.(T) asserts that the dynamic type of x is identical to the type T.

In this case, the question is whether `st` ("the dynamic type of x") is *identical* to `impl` ("the type of T"). The answer is no. From the [Type definitions section](https://golang.org/ref/spec#Type_definitions) of the spec:

> A type definition creates a new, distinct type [...].

> The new type is called a defined type. **It is different from any other type, including the type it is created from.**

Since `st` and `impl` are defined types created by two distinct *type definitions*, they are different by construction, and a type assertion that tries to coerce one into the other must fail.

Closing here.

**Closed by ALTree** 2019-08-22 09:21 UTC

**Comment by zeitlinger** [comment] 2019-08-22 11:50
OK, it might not be a bug according to the specs - but maybe a reason to change the spec for Go2.

Upcast does not imply downcast (not symmetrical):
1. `st` can be assigned to `in` (upcast, line 22)
2. but this instance of `in` cannot be cast to `st` (downcast, line 26)

I don't know of any other language that has this behavior - so it's similar to other issues that might be revised in Go2 (e.g. re-using index variables in range).

**Comment by av86743** [comment] 2019-08-22 12:54
> 2. but this instance of `in` cannot be cast to `st` (downcast, line 26)

In your example, `in` can be cast to its actual type which is `*st` (see [playground](https://play.golang.org/p/9a1AhDpmPWr).)  Earlier I said that its actual type is `st` - my mistake.

**Comment by ALTree** [comment] 2019-08-22 13:41
I don't understand what you mean by "upcasting" and "downcasting". As far as I know, these terms only make sense in a language with a hierarchic class-based type system, with "up-" and "down-" referring to type casts that go in one direction or the other in the classes hierarchy. Go is not such a language.

Anyway, you write:

>  st can be assigned to in (upcast, line 22)
> but this instance of in cannot be cast to st (downcast, line 26)

But that's not what you're doing in your example... at line 26 you're trying to type-assert the argument to `(impl)`, and this fails for the reason I explained above:

```
func main() {
	f(st{in: impl{}})
}

func f(i in) {
	_ = i.(impl)
}
```
(Please note that I removed the `&` from the `st` literal). This gives:
```
panic: interface conversion: main.in is main.st, not main.impl
```
But if you want to type-assert i to `st` (what you refer to as "his instance of in cannot be cast to st"), you have to do this:

```
_ = i.(st)
```

which *does* work. So it appears to me that you *wanted* to do something reasonable (type-assert to `st`), but you type-asserted to `impl` by mistake).

**Comment by av86743** [comment] 2019-08-22 14:14
> ... but you type-asserted to `impl` by mistake.

Not by mistake, of course.  It was presumed to be a shortcut for
```
	_, ok := i.(*st).in.(impl)
```
because `i` is "already" declared as `in` (see [playground](https://play.golang.org/p/Z91wxBGpGvS).)  Naturally, golang does not support this.

**Comment by zeitlinger** [comment] 2019-08-22 14:15
Now I realize that I was wrong.

I think my confusion comes from the fact that `st` can be assigned to the `in` parameter of `f` -which led me to the wrong conclusion that passing `st` should behave identical as passing `st.in`.
I wonder if this a common pitfall - which would be an argument of disallowing this assignment.

**Comment by zeitlinger** [comment] 2019-08-23 06:22
Another way of expressing my concern is:
`st` behaves like `st.in` in every way - except type casting.
Why this exception?

On the other hand:
It's quite surprising that `i` can be cast to `st` - what is the use case for this?

**Comment by ALTree** [comment] 2019-08-23 08:54
We do not really use this bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions.
