### ISSUE TITLE
encoding/binary: fast-paths in Read and Write allocate despite attempted optimization

### ISSUE THREAD

**Issue by nvanbenschoten** [golang/go#27403] opened 2018-08-31 06:41 UTC
`encoding/binary.Read` and `encoding/binary.Write` both include an attempt to avoid heap allocations by pointing a slice at a stack allocated array with sufficient capacity to fit most basic types.

https://github.com/golang/go/blob/58e970ed79807fd9d2a29e1dcd4e44fa867b5540/src/encoding/binary/binary.go#L161-L170

https://github.com/golang/go/blob/58e970ed79807fd9d2a29e1dcd4e44fa867b5540/src/encoding/binary/binary.go#L260-L269

The "optimization" is fooling itself because the array escapes from the stack and is moved onto the heap anyway. This means that at best the optimization does nothing and at worst the optimization actually results in either an oversized allocation or an entirely unnecessary second allocation.

```
binary$ go build -gcflags='-m' 2>&1 | grep 'moved to heap'
./binary.go:164:7: moved to heap: b
./binary.go:263:7: moved to heap: b
```

The reason the array is moved to the heap is because escape analysis cannot prove that the slice pointing at it doesn't itself escape. This is the case because the slice is passed to the provided `ByteOrder` interface:

https://github.com/golang/go/blob/58e970ed79807fd9d2a29e1dcd4e44fa867b5540/src/encoding/binary/binary.go#L33-L39

Escape analysis can't prove that the slice won't escape when passed to an arbitrary interface implementation, even though it can and does know that the slice won't escape if passed to a `littleEndian` or `bigEndian`:

```
binary$ go build -gcflags='-m' 2>&1 | grep 'does not escape'
./binary.go:51:38: littleEndian.Uint16 b does not escape
./binary.go:56:43: littleEndian.PutUint16 b does not escape
./binary.go:62:38: littleEndian.Uint32 b does not escape
./binary.go:67:43: littleEndian.PutUint32 b does not escape
./binary.go:75:38: littleEndian.Uint64 b does not escape
./binary.go:81:43: littleEndian.PutUint64 b does not escape
./binary.go:99:35: bigEndian.Uint16 b does not escape
./binary.go:104:40: bigEndian.PutUint16 b does not escape
./binary.go:110:35: bigEndian.Uint32 b does not escape
./binary.go:115:40: bigEndian.PutUint32 b does not escape
./binary.go:123:35: bigEndian.Uint64 b does not escape
./binary.go:129:40: bigEndian.PutUint64 b does not escape
...
```

We could get tricky here and specialize the code for `LittleEndian` and `BigEndian` `ByteOrder`s so that when they are provided as the desired `order` the allocation is avoided, as the optimization
intended. However, this would result in a significant amount of code duplication in order to convince escape analysis that the array is safe to leave on the stack. In lieu of that, we should remove the "optimization" entirely because it's not doing any good.

**Comment by agnivade** [comment] 2018-08-31 08:38
@nvanbenschoten - For the record, it will be good to get your go version and go env info.

/cc @dr2chase @rasky

**Comment by rasky** [comment] 2018-08-31 09:15
AFAICT, Go interfaces as designed in Go 1 don't play well with escape analysis. Any object passed through them always escape, period, and there is no way for the Go compiler to fix this without a whole-program compilation which is unlikely to ever happen. 

In the specific case of `binary.Read`, we already noticed in another bug that that function should be forced inline most of the times (at least, anytime it is called with `data` being a concrete type) because most of its reflection logic could be scraped away by optimizers; it's really meta-programming, happening at runtime for no good reason. 

So I think this is a good use case for seeing if Go 2 generics can help design a new byteorder package that uses less runtime constructs (reflections and interfaces) and more compile time constructs, to avoid allocations and achieve more speed.

/cc @ianlancetaylor @rsc

**Comment by nvanbenschoten** [comment] 2018-08-31 15:51
Thanks for the responses. This was in go1.10, but like @rasky mentioned, it's a general problem with Go 1 and its interaction between interfaces and escape analysis. With the current design of `binary.ByteOrder`, this optimization was and is never going to work.

With that in mind, would you be open to me sending a pull request to rip out this attempted optimization?

> So I think this is a good use case for seeing if Go 2 generics can help design a new byteorder package that uses less runtime constructs (reflections and interfaces) and more compile time constructs, to avoid allocations and achieve more speed.

I completely agree and the most recent draft of generics is looking promising. Note though that this will require that generics be implemented at least in part using compile-time specialization, which it sounds like is still an open question.

**Comment by rasky** [comment] 2018-08-31 16:07
> Note though that this will require that generics be implemented at least in part using compile-time specialization, which it sounds like is still an open question.

Either that, or we must make sure the compiler is smart enough when instantiating a generic whose type is being used as part of a type switch (is that possible at all?) or a good subset of reflect calls that could get intrinsified.

**Comment by josharian** [comment] 2018-09-01 04:10
> include an attempt to avoid heap allocations

git blame suggests to me that this was not an optimization attempt but merely an oversight while the code grew: https://golang.org/cl/12694048

If simplifying the code doesn’t cause a performance regression (I don’t see why it would, but I am AFK), that would be a welcome change.

**Comment by josharian** [comment] 2018-09-01 04:12
Marking as suggested: the simplification appears straightforward, and the only other thing to do is confirm that there is no performance regression.

**Comment by iand** [comment] 2018-09-03 09:07
I did a little testing on this and found that the use of `io.ReadFull(r, bs)` moves b to the heap so the change may not be as simple as expected.

**Comment by josharian** [comment] 2018-09-04 01:28
@iand I'm not sure I follow. I tried it (CL 133135) and it appeared to work nicely. What am I missing?

**Comment by nvanbenschoten** [comment] 2018-09-04 03:30
@josharian CL 133135 is what I was expecting to be the outcome of this issue. Thanks for beating me to it 😃.

I assume @iand was attempting to specialize `Read` and `Write` for `bigEndian` and `littleEndian` `ByteOrder`s. In that case, he's correct that in passing the byte slice to the reader or writer we force it onto the heap, regardless of what tricks we pull with the `order` argument. Because if this, there's not much else we can do here.

**Comment by iand** [comment] 2018-09-04 07:41
@josharian I was looking into the original suggestion of specialising by Endian to reduce allocations. I didn't look at the fallback of simplifying and accepting that it allocates.

**Closed** 2018-09-04 14:53 UTC
Labels: NeedsFix, Performance, Suggested, help wanted

**Comment by josharian** [comment] 2018-09-04 14:54
Ah, I see. Thanks, @iand. And yes, if there’s any performance value in specialization it is more likely to come from Writers (particularly Writers that buffer).
