### ISSUE TITLE
<a id="c1"></a>Comment 1:

### ISSUE THREAD

**Issue by Cherrison** [golang/go#42294] opened 2020-10-30 11:04 UTC
why 64-bit atomic operation must make sure the
pointer address is aligned to 8-byte boundary?

<a id="c1"></a>Comment 1:

<pre>The caller of 64-bit atomic operation must make sure the
pointer address is aligned to 8-byte boundary.
<a href="http://play.golang.org/p/fRMRT2Jzsh">http://play.golang.org/p/fRMRT2Jzsh</a>
Quote BUGS section of docs for sync/atomic:
BUGS
   On x86-32, the 64-bit functions use instructions unavailable before the
   Pentium MMX. On both ARM and x86-32, it is the caller's responsibility to
   arrange for 64-bit alignment of 64-bit words accessed atomically. The
   first word in a global variable or in an allocated struct or slice can be
   relied upon to be 64-bit aligned.</pre>

_Status changed to **WorkingAsIntended**._

_Originally posted by @minux in https://github.com/golang/go/issues/5278#issuecomment-66078007_

**Comment by ALTree** [comment] 2020-10-30 11:31
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2020-10-30 11:31 UTC
