### ISSUE TITLE
cmd/compile: optimize append performance

### ISSUE THREAD

**Issue by dsnet** [golang/go#14758] opened 2016-03-10 20:50 UTC
Using `go devel +ed4a27a`

I ran the following benchmarks:

``` go
func BenchmarkFoo(b *testing.B) {
    a := make([]byte, 1000)
    b.SetBytes(int64(len(a)))

    for i := 0; i < b.N; i++ {
        var n int
        for j := 0; j < 1000; j++ {
            a[n] = byte(j)
            n++
        }
        a = a[:n]
    }
}

func BenchmarkBar(b *testing.B) {
    a := make([]byte, 1000)
    b.SetBytes(int64(len(a)))

    for i := 0; i < b.N; i++ {
        a = a[:0]
        for j := 0; j < 1000; j++ {
            a = append(a, byte(j))
        }
    }
}
```

Currently I see:

```
BenchmarkFoo-4   3000000           588 ns/op    1700.17 MB/s
BenchmarkBar-4   2000000           871 ns/op    1147.11 MB/s
```

I expect to see these two to perform about the same.

@klauspost

**Comment by bradfitz** [comment] 2016-03-10 21:01
Dup of #11419?

I'm not sure I'd expect them to be equal, though. append is a runtime call and will be more expensive than not making a call.

**Comment by martisch** [comment] 2016-03-10 21:06
similar to #14718
Here its slightly different in that the a have the same cap at the end. 
But the argument that one is a runtime call i would share and so they can never be equal. 
But maybe the gap can be narrowed...

**Comment by randall77** [comment] 2016-03-10 21:35
This is unrelated to either #11419 or #14718.  It should be fixable.

We inline the easy part of append in the compiler.  `a = append(a, b)` compiles to something like:
```
if len(a) == cap(a) {
  a = ...some runtime call...
}
a[len(a)] = b
len(a)++
```
The branch is predicted not taken (and will never be taken in this case), so the grow path is out-of-line.

The inner loop of BenchmarkFoo is:
```
	0x006b 00107 (/home/khr/go/issue14758.go:12)	CMPQ	BP, AX
	0x006e 00110 (/home/khr/go/issue14758.go:12)	JCC	$0, 173
	0x0070 00112 (/home/khr/go/issue14758.go:12)	MOVB	BPB, (BX)(BP*1)
	0x0074 00116 (/home/khr/go/issue14758.go:11)	INCQ	BP
	0x0077 00119 (/home/khr/go/issue14758.go:11)	CMPQ	BP, $1000
	0x007e 00126 (/home/khr/go/issue14758.go:11)	JLT	$0, 107
```
The inner loop of BenchmarkBar is:
```
	0x0083 00131 (/home/khr/go/issue14758.go:26)	LEAQ	1(BP), SI
	0x0087 00135 (/home/khr/go/issue14758.go:26)	MOVQ	SI, "".autotmp_0012+72(SP)
	0x008c 00140 (/home/khr/go/issue14758.go:26)	CMPQ	SI, AX
	0x008f 00143 (/home/khr/go/issue14758.go:26)	JGT	$0, 191
	0x0091 00145 (/home/khr/go/issue14758.go:26)	MOVB	$0, (DX)(BP*1)
	0x0095 00149 (/home/khr/go/issue14758.go:26)	MOVQ	SI, BP
	0x0098 00152 (/home/khr/go/issue14758.go:20)	MOVQ	BP, "".autotmp_0011+80(SP)
	0x009d 00157 (/home/khr/go/issue14758.go:25)	CMPQ	BP, $1000
	0x00a4 00164 (/home/khr/go/issue14758.go:25)	JLT	$0, 131
```
I suspect that most of the time is lost with the extra writes to those autotmp variables.  We might be able to lift those writes to after the loop, or get rid of them altogether.  David was thinking about this at some point.

@dr2chase

**Comment by dsnet** [comment] 2016-03-10 22:11
Just for context, this came up in [CL/20513](https://go-review.googlesource.com/#/c/20513/), and provided a very small performance boost of ~1% when the slice length was tracked manually.

This is not a priority, but a nice to have.

**Comment by ALTree** [comment] 2017-03-21 10:51
On tip (to-be-1.9) I see:

```
name   time/op
Foo-4   1.02µs ± 1%
Bar-4   1.02µs ± 0%

name   speed
Foo-4  977MB/s ± 1%
Bar-4  978MB/s ± 0%
```

I guess this is fixed, so I'm closing this issue.

**Comment by ALTree** [comment] 2017-03-21 11:08
Looks like actually is `BenchmarkFoo` that got slower on tip; so they're not the same (on tip) because Bar got faster, but because Foo got slower (resp. go1.8). Reopening (and sorry for the noise).

**Comment by randall77** [comment] 2017-03-21 20:39
The original bug was fixed recently with better spill code generation: https://go-review.googlesource.com/c/34822/
The regression from 1.8 is #15837

**Comment by bradfitz** [comment] 2017-03-21 20:53
@randall77, does that mean this bug should be closed, or ... ?

**Comment by randall77** [comment] 2017-03-21 21:00
Well, I suspect the regression is because of #15837.  Leave this open so I can double-check after I get a fix together for that issue.

**Closed** 2017-04-24 22:13 UTC
Labels: Performance
