### ISSUE TITLE
math.Mod seems to produce wrong output

### ISSUE THREAD

**Issue by burdiyan** [golang/go#34756] opened 2019-10-08 07:01 UTC
### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Printf("%.8f", math.Mod(10, 0.1))
}
```

https://play.golang.org/p/s725Z6unzo1

### What did you expect to see?

I expect `10 % 0.1` to return `0`, which is the result I get calculating modulo in a spreadsheet.

### What did you see instead?

I see `0.1`.

**Comment by ALTree** [comment] 2019-10-08 07:36
Thanks for reporting this.  `math.Mod` mirrors the [`fmod` C function in `math.h`](https://en.cppreference.com/w/c/numeric/math/fmod), which also returns 0.1 for fmod(10, 0.1). 

Your spreadsheet probably uses a different definition of floating point mod (AFAIK there are several different and conflicting definitions); but since the reference for us is the C stdlib one, 0.1 is correct and this is working as intended. 

Closing here.

**Closed by ALTree** 2019-10-08 07:36 UTC

**Comment by rsc** [comment] 2019-10-08 14:53
0.1 is not an exact floating point number.
It is really x = 0.1000000000000000055511151231257827021181583404541015625.
100 * x = 10.00000000000000055511151231257827021181583404541015625,
which is bigger than ten. So math.Mod returns
10.0 - 99 * x = 10.0 - 9.9000000000000005495603971894524875096976757049560546875
= .0999999999999994504396028105475124903023242950439453125,
which rounds to 0.1000000000000000055511151231257827021181583404541015625.

For more about floating point, see https://floating-point-gui.de/.
