### ISSUE TITLE
struct conversion, new fields, and incompatibility

### ISSUE THREAD

**Issue by carnott-snap** [golang/go#44893] opened 2021-03-09 20:22 UTC
### What version of Go are you using (`go version`)?
<pre>$ go version
go version go1.16 linux/amd64
</pre>
### Does this issue reproduce with the latest release?
yes
### What operating system and processor architecture are you using (`go env`)?
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/.local/share/umake/go/go-lang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/.local/share/umake/go/go-lang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g  "
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3311873374=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
When working with wire formats, serialisation, and external types, it is useful to change the struct tags:
https://play.golang.org/p/h6b6FmeDuaR
```go
package lib

type Struct struct{
	Field string
}
```
```go
package main

import (
	"encoding/json"
	"lib"
)

type Struct struct{
	Field string `json:"field"`
}

func main() {
	json.Marshal(Struct(lib.Struct{}))
}
```
But when the original struct has a field added, this breaks:
https://play.golang.org/p/VHmV9r2MxNt
```go
package lib

type Struct struct{
	Field string
	New bool
}
```
### What did you expect to see?
It seems like a foregone conclusion that we suggest against adding a struct field because it is a breaking change. That said, we probably do not want to restrict the ability to convert structs as it is really helpful, so I am not sure what is expected.
### What did you see instead?
```
./main.go:13:31: cannot convert lib.Struct{} (type lib.Struct) to type Struct
```

**Comment by 89z** [comment] 2021-03-09 20:36
Why are you Marshalling empty structs? Do you have an examples that arent pointless?

**Comment by carnott-snap** [comment] 2021-03-09 20:47
my example is simple, not pointless. it is assumed that the reader already understands why one would marshal structs or other cases where converting named types is useful.

**Comment by andig** [comment] 2021-03-09 22:56
Your structs have different memory layout, hence they are not compatible.

**Comment by carnott-snap** [comment] 2021-03-10 04:53
sorry, maybe I should have been more clear with my submission. I understand mechanically why this is breaking, my concern is that currently adding a field to a struct is defined as a semantically compatible change, despite the fact that it can break builds.

should we:
- treat adding a field to a struct like adding a method to an interface?
  - they both break some definition sites, but generally are fine at call sites
  - this can be worked around by requiring a private field/method be added
  - are defined as breaking changes
- we vet this use case, like unnamed struct initialisation, and effectively consider it apocrypha
- do nothing
- something else

**Comment by andig** [comment] 2021-03-10 06:28
If you're proposing specific changes you can probably turn this issue into a golang proposal, the process is documented. Personally, I'm not clear what you're asking. That's the way go works.

**Comment by mdlayher** [comment] 2021-03-11 16:49
I also believe this is working as intended, and since there isn't a concrete suggestion here, I'm going to close this issue. Please consider raising a discussion on the mailing list if you'd like to discuss this topic.

**Closed by mdlayher** 2021-03-11 16:49 UTC
