### ISSUE TITLE
"go mod tidy" command not working with utf-8 bom encoding

### ISSUE THREAD

**Issue by marunguy** [golang/go#44526] opened 2021-02-23 05:43 UTC
* test environment
  * go 1.16 windows 64bit
  * windows 10 64bit
* hello.go 
  * https://golang.org/doc/tutorial/getting-started#call
```go
package main

import "fmt"

import "rsc.io/quote"

func main() {
    fmt.Println(quote.Go())
}
```
* hello.go saved as "utf-8 bom" encoding using notepad++ 7.9.3 64bit
  * "go mod tidy" not working
```
D:\work\gotest\src>go mod tidy

D:\work\gotest\src>
```
* hello.go saved as "utf-8" encoding using notepad++ 7.9.3 64bit
  * "go mod tidy" working
```
D:\work\gotest\src>go mod tidy
go: finding module for package rsc.io/quote
go: downloading rsc.io/quote v1.5.2
go: found rsc.io/quote in rsc.io/quote v1.5.2
go: downloading rsc.io/sampler v1.3.0
go: downloading golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c
```

* "go run ." and "go build" working with "utf-8 bom" encoding
* hello.go 
  * https://golang.org/doc/tutorial/getting-started#code
  * saved as "utf-8 bom" encoding using notepad++ 7.9.3 64bit
```go
package main

import "fmt"

func main() {
    fmt.Println("Hello, World!")
}
```
```
D:\work\gotest\src>go run .
Hello, World!

D:\work\gotest\src>go build

D:\work\gotest\src>hello.exe
Hello, World!

D:\work\gotest\src>
```

**Comment by seankhliao** [comment] 2021-02-23 06:39
Duplicate of #35726

**Closed by seankhliao** 2021-02-23 06:39 UTC
