### ISSUE TITLE
x/sys zsyscall_darwin_arm64 being checked on Apple Silicon

### ISSUE THREAD

**Issue by reskin89** [golang/go#56553] opened 2022-11-03 18:28 UTC
Currently on an M1 Apple Silicon Macbook, when building a project that has `golang.org/x/sys/unix` it attempts to check zsyscall_darwin_arm64.go which seems to have invalid link names:

```bash
golang.org/x/sys/unix/zsyscall_darwin_arm64.go:28:3: //go:linkname must refer to declared function or variable
golang.org/x/sys/unix/zsyscall_darwin_arm64.go:43:3: //go:linkname must refer to declared function or variable
golang.org/x/sys/unix/zsyscall_darwin_arm64.go:59:3: //go:linkname must refer to declared function or variable
golang.org/x/sys/unix/zsyscall_darwin_arm64.go:75:3: //go:linkname must refer to declared function or variable
golang.org/x/sys/unix/zsyscall_darwin_arm64.go:90:3: //go:linkname must refer to declared function or variable
golang.org/x/sys/unix/zsyscall_darwin_arm64.go:105:3: //go:linkname must refer to declared function or variable
golang.org/x/sys/unix/zsyscall_darwin_arm64.go:121:3: //go:linkname must refer to declared function or variable
golang.org/x/sys/unix/zsyscall_darwin_arm64.go:136:3: //go:linkname must refer to declared function or variable
golang.org/x/sys/unix/zsyscall_darwin_arm64.go:151:3: //go:linkname must refer to declared function or variable
golang.org/x/sys/unix/zsyscall_darwin_arm64.go:166:3: //go:linkname must refer to declared function or variable
```

```bash
➜  go version
go version go1.19.3 darwin/arm64
```

**Comment by mdempsky** [comment] 2022-11-03 18:32
Duplicate of #55889.

As a workaround, you can run: `go get -u golang.org/x/sys/unix`

**Closed by mdempsky** 2022-11-03 18:32 UTC
