### ISSUE TITLE
x/tools/go/packages: data race in (*loader).refine

### ISSUE THREAD

**Issue by bradfitz** [golang/go#31749] opened 2019-04-29 20:56 UTC
https://storage.googleapis.com/go-build-log/2b8cbc38/linux-amd64-race_ad38befa.log

```
ok  	golang.org/x/tools/go/loader	31.561s
==================
WARNING: DATA RACE
Write at 0x00c0024e4480 by goroutine 1290:
  runtime.slicecopy()
      /workdir/go/src/runtime/slice.go:197 +0x0
  math/big.(*Rat).Float64()
      /workdir/go/src/math/big/nat.go:95 +0x1e1
  go/constant.Float64Val()
      /workdir/go/src/go/constant/value.go:554 +0x33c
  go/types.roundFloat64()
      /workdir/go/src/go/types/expr.go:175 +0x46
  go/types.representableConst()
      /workdir/go/src/go/types/expr.go:279 +0x89d
  go/types.(*Checker).representable()
      /workdir/go/src/go/types/expr.go:335 +0xb7
  go/types.(*Checker).convertUntyped()
      /workdir/go/src/go/types/expr.go:517 +0xe35
  go/types.(*Checker).binary()
      /workdir/go/src/go/types/expr.go:801 +0x229
  go/types.(*Checker).exprInternal()
      /workdir/go/src/go/types/expr.go:1504 +0x2d6f
  go/types.(*Checker).rawExpr()
      /workdir/go/src/go/types/expr.go:983 +0x91
  go/types.(*Checker).multiExpr()
      /workdir/go/src/go/types/expr.go:1600 +0x68
  go/types.(*Checker).initVars.func1()
      /workdir/go/src/go/types/assignments.go:209 +0xa3
  go/types.unpack()
      /workdir/go/src/go/types/call.go:181 +0xbb
  go/types.(*Checker).initVars()
      /workdir/go/src/go/types/assignments.go:209 +0xea
  go/types.(*Checker).shortVarDecl()
      /workdir/go/src/go/types/assignments.go:322 +0x3a8
  go/types.(*Checker).stmt()
      /workdir/go/src/go/types/stmt.go:398 +0x5986
  go/types.(*Checker).stmtList()
      /workdir/go/src/go/types/stmt.go:120 +0xee
  go/types.(*Checker).funcBody()
      /workdir/go/src/go/types/stmt.go:42 +0x36e
  go/types.(*Checker).funcDecl.func1()
      /workdir/go/src/go/types/decl.go:561 +0xee
  go/types.(*Checker).processDelayed()
      /workdir/go/src/go/types/resolver.go:615 +0x59
  go/types.(*Checker).checkFiles()
      /workdir/go/src/go/types/check.go:256 +0xc9
  golang.org/x/tools/go/packages.(*loader).loadPackage()
      /workdir/go/src/go/types/check.go:245 +0xca9
  golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
      /workdir/gopath/src/golang.org/x/tools/go/packages/packages.go:683 +0x258
  sync.(*Once).doSlow()
      /workdir/go/src/sync/once.go:52 +0xbf
  sync.(*Once).Do()
      /workdir/go/src/sync/once.go:43 +0x68
  golang.org/x/tools/go/packages.(*loader).loadRecursive()
      /workdir/gopath/src/golang.org/x/tools/go/packages/packages.go:670 +0x74
  golang.org/x/tools/go/packages.(*loader).refine.func2()
      /workdir/gopath/src/golang.org/x/tools/go/packages/packages.go:606 +0x42

Previous write at 0x00c0024e4480 by goroutine 235:
  [failed to restore the stack]

Goroutine 1290 (running) created at:
  golang.org/x/tools/go/packages.(*loader).refine()
      /workdir/gopath/src/golang.org/x/tools/go/packages/packages.go:605 +0x218f
  golang.org/x/tools/go/packages.Load()
      /workdir/gopath/src/golang.org/x/tools/go/packages/packages.go:224 +0x1b8
  golang.org/x/tools/go/packages_test.TestStdlibMetadata()
      /workdir/gopath/src/golang.org/x/tools/go/packages/stdlib_test.go:34 +0x1af
  testing.tRunner()
      /workdir/go/src/testing/testing.go:865 +0x162

Goroutine 235 (running) created at:
  golang.org/x/tools/go/packages.(*loader).refine()
      /workdir/gopath/src/golang.org/x/tools/go/packages/packages.go:605 +0x218f
  golang.org/x/tools/go/packages.Load()
      /workdir/gopath/src/golang.org/x/tools/go/packages/packages.go:224 +0x1b8
  golang.org/x/tools/go/packages_test.TestStdlibMetadata()
      /workdir/gopath/src/golang.org/x/tools/go/packages/stdlib_test.go:34 +0x1af
  testing.tRunner()
      /workdir/go/src/testing/testing.go:865 +0x162
==================
--- FAIL: TestStdlibMetadata (20.99s)
    stdlib_test.go:47: Loaded 199 packages
    stdlib_test.go:55: GOMAXPROCS:  4
    stdlib_test.go:56: Metadata:    20.339881289s
    stdlib_test.go:57: #MB:         273
    testing.go:809: race detected during execution of test
FAIL
FAIL	golang.org/x/tools/go/packages	30.525s
```

**Comment by dominikh** [comment] 2019-05-20 03:42
Simple reproducer:

```
package main

import (
	"golang.org/x/tools/go/packages"
)

func main() {
	cfg := &packages.Config{
		Mode: packages.LoadAllSyntax,
		Tests: true,
	}

	for {
		packages.Load(cfg, "sandbox/bar")
	}
}
```

Where `sandbox/bar` is a package in GOPATH, as follows:

```
$ cat bar.go
package pkg

import . "fmt"

var _ = Println

$ cat bar_test.go 
package pkg

import . "fmt"

var _ = Println
```

As far as I've been able to determine, the presence of dot imports as well as the presence of a test package are relevant. This looks like a proper bug in go/packages, not "just" an issue with its tests.

/cc @ianthehat and @matloob again, for good measure.

**Comment by bcmills** [comment] 2019-06-28 14:17
Here's another one:
https://build.golang.org/log/771a162eb38e5defcbe67e34b910a1e3a695be79

**Comment by bcmills** [comment] 2019-06-28 14:38
I'm not sure why this has the `Testing` label. This looks like a straight-up bug in `go/packages` — the race doesn't seem to be introduced by the test itself.

**Comment by bcmills** [comment] 2019-06-28 14:41
This looks like the same race that was reported in #30107.

**Comment by bcmills** [comment] 2019-08-29 18:04
https://build.golang.org/log/2c3d2505bf5145815ce4fc57a449c39a46a32cf2

**Comment by bcmills** [comment] 2019-08-30 17:30
https://build.golang.org/log/5b0f113bf6114088e575043c333165e97ee7c2bb

**Comment by bcmills** [comment] 2019-10-11 14:33
This is causing a lot of test failures in the TryBots for `x/tools` changes, and having racy code in a user-facing API like `go/packages` is very risky in the first place.

@ianthehat, @matloob: can someone prioritize a fix for this?

**Comment by bcmills** [comment] 2019-10-11 14:35
Some recent examples:
* https://storage.googleapis.com/go-build-log/03ef105d/linux-amd64-race_5947a7d5.log
* https://storage.googleapis.com/go-build-log/d0f10a6e/freebsd-amd64-12_0_2652cf0e.log (a crash in `refine`, presumably induced by this race?)
* https://storage.googleapis.com/go-build-log/d0f10a6e/linux-amd64-race_b8480f30.log
* https://storage.googleapis.com/go-build-log/46b75578/linux-amd64-race_2335ce7b.log

**Comment by matloob** [comment] 2019-10-11 19:18
Looking at this now

**Comment by matloob** [comment] 2019-10-11 22:30
It's not obvious to me what the issue is so I'm going to disable the tests on (tip, race) while I debug.

**Comment by rsc** [comment] 2019-10-15 15:33
The original race reported is #34919. I am not sure about the storage.googleapis.com links that Bryan posted - some of those look different.

**Comment by rsc** [comment] 2019-10-15 15:55
In the newer races Bryan posted, the three race detector failures are all #34921. The non-race panic about the algorithm going wrong could easily have been caused by those races too.

I think combined #34919 and #34921 explain all the failures in go/packages linked in this thread.

/cc @griesemer

**Comment by griesemer** [comment] 2019-10-18 03:06
Was closed by mistake, https://golang.org/cl/201838 mentioned #34921 by mistake.

Though now that #34921 and #34919 are fixed, this bug may have been fixed as well.

@matloob Could you look into this and see if you can still reproduce this issue (and if not, close it)? Thanks.

**Comment by bcmills** [comment] 2019-10-21 18:57
Still racy; filed #35049.

**Comment by bcmills** [comment] 2019-10-28 14:33
Seems to be fixed now. (At least, [CL 202538](https://golang.org/cl/202538]) passed in the TryBots.)

**Closed** 2019-10-28 14:34 UTC
Labels: NeedsInvestigation, Soon
