### ISSUE TITLE
encoding/json: UnmarshalTypeError is clobbered when using nested custom marshallers

### ISSUE THREAD

**Issue by firelizzard18** [golang/go#61337] opened 2023-07-13 17:19 UTC
### Summary

`(*encoding.json.decodeState).addErrorContext` sets UnmarshalTypeError's Field value based on the decode state's error context. However when a custom UnmarshalJSON implementation calls `json.Unmarshal`, this creates a new nested decode state with its own error context. When the nested unmarshal call returns an error, and that error is seen by the original decode state, the original decode state's error context's field stack is empty. Thus when the original decode state sets the error's Field value, it clobbers the field name from the nested call.

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="$HOME/.cache/go-build"
GOENV="$HOME/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="$HOME/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="$HOME/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build382302808=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

https://go.dev/play/p/Z1X4MEFdocS

```go
type Alpha struct {
	Beta Beta `json:"beta"`
}

type Beta struct {
	Field string `json:"field"`
}

func (a *Alpha) UnmarshalJSON(data []byte) error {
	type AlphaWrapper Alpha
	if err := json.Unmarshal(data, (*AlphaWrapper)(a)); err != nil {
		return err
	}
	// Do some extra work
	return nil
}

func (b *Beta) UnmarshalJSON(data []byte) error {
	type BetaWrapper Beta
	if err := json.Unmarshal(data, (*BetaWrapper)(b)); err != nil {
		return err
	}
	// Do some extra work
	return nil
}

func TestJsonBug(t *testing.T) {
	var a Alpha
	err := json.Unmarshal([]byte(`{ "beta": { "field": 1 } }`), &a)
	const expect = "json: cannot unmarshal number into Go struct field BetaWrapper.beta.field of type string"
	if err.Error() != expect {
		t.Fatalf("Bad error\nExpected: %s\nGot:      %s", expect, err.Error())
	}
}
```

### What did you expect to see?

`json: cannot unmarshal number into Go struct field BetaWrapper.beta.field of type string`

### What did you see instead?

`json: cannot unmarshal number into Go struct field AlphaWrapper.beta of type string`

**Comment by ayang64** [comment] 2023-07-13 17:53
You should probably update the What did you see instead? section with:

```
json: cannot unmarshal number into Go struct field AlphaWrapper.beta of type string
```

**Comment by cherrymui** [comment] 2023-07-14 18:40
cc @rsc @dsnet @bradfitz @mvdan

**Comment by seankhliao** [comment] 2023-07-19 06:55
Duplicate of #11858

**Closed by seankhliao** 2023-07-19 06:55 UTC
Labels: NeedsInvestigation
