### ISSUE TITLE
proposal: x/vgo: specify Go version required by module

### ISSUE THREAD

**Issue by dpinela** [golang/go#24714] opened 2018-04-05 20:33 UTC
While it probably shouldn't upgrade Go for you if you import something that requires a newer version, vgo could at least tell you right away about the incompatibility and which version you need to upgrade to, rather than you having to guess it from compile errors. I imagine this as just another dependency entry in the go.mod, like this: `require "go" v1.11.0`.

**Comment by jimmyfrasche** [comment] 2018-04-05 20:37
Duplicate of #23969

**Comment by ALTree** [comment] 2018-04-06 08:39
Yep, dup. Closing here in favour of the old thread.

**Closed by ALTree** 2018-04-06 08:39 UTC
Labels: Proposal
