### ISSUE TITLE
why this line don't need the defer?

### ISSUE THREAD

**Issue by chenyoufu** [golang/go#28305] opened 2018-10-22 07:03 UTC
https://github.com/golang/go/blob/3bf9b77c0c8f123728fcfc802599232e9bd95476/src/database/sql/sql.go#L2922

**Comment by cznic** [comment] 2018-10-22 09:04
Let me turn the question the other way around. Why that line should need a defer? I don't see any reason for that.

**Comment by go101** [comment] 2018-10-22 13:15
@chenyoufu
This doesn't look like an issue.
It would be better to ask such questions on https://groups.google.com/forum/#!forum/golang-nuts or https://www.reddit.com/r/golang/ 

For your question, if you want to use defer, then the code should be written like this:
```golang
func (rs *Rows) Scan(dest ...interface{}) error {
	func() {
		rs.closemu.RLock()
		rs.closemu.RUnlock()

		if rs.lasterr != nil && rs.lasterr != io.EOF {
			return rs.lasterr
		}
		if rs.closed {
			return errors.New("sql: Rows are closed")
		}
	}()
	...
```

**Comment by agnivade** [comment] 2018-10-22 15:29
Hi @chenyoufu 

As already pointed above, this appears to be a question rather than a Go bug. We do not use the issue tracker for general discussions or questions like these. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

For further questions, please have a look at [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.

Closing since this is not a bug.

**Closed by agnivade** 2018-10-22 15:29 UTC
