### ISSUE TITLE
cmd/go:  debug.BuildInfo doesn't include VCS info when cross-compiling [1.18rc1]

### ISSUE THREAD

**Issue by spyder-jeff** [golang/go#51264] opened 2022-02-18 20:13 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18rc1 linux/arm64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/vagrant/.cache/go-build"
GOENV="/home/vagrant/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/vagrant/go/pkg/mod"
GONOPROXY="*"
GONOSUMDB="*"
GOOS="linux"
GOPATH="/home/vagrant/go"
GOPRIVATE="*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go1.18rc1"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go1.18rc1/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.18rc1"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/vagrant/spyderbat/aws_terraform/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3002789791=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

building on arm64 for amd64:

```
	vcsrevision := "unknown"
	vcsdirty := ""
	vcstime := "unknown"

	if info, ok := debug.ReadBuildInfo(); ok {
		for _, v := range info.Settings {
			switch v.Key {
			case "vcs.revision":
				vcsrevision = v.Value
			case "vcs.modified":
				if v.Value == "true" {
					vcsdirty = " (dirty)"
				}
			case "vcs.time":
				vcstime = v.Value
			}
		}
	}
```

### What did you expect to see?

vcs info, when cross-compiling to AMD64

### What did you see instead?

"unknown"

(works when building for native arm64)

**Comment by dmitshur** [comment] 2022-02-18 21:05
CC @bcmills, @rsc.

**Comment by bcmills** [comment] 2022-02-22 22:15
I don't see anything in the `-buildvcs` implementation that would vary based on whether you are cross-compiling.
What were the exact commands that you ran for the two builds?

**Comment by spyder-jeff** [comment] 2022-02-23 00:18
I'm sorry, I'm dumb. It wasn't cross-compiling that was doing it, it was an artifact of the way the Makefile was written. It turns out that if you do `go build foo.go` instead of just `go build`, you don't get vcs info. Maybe that's expected? I hope not.

Sample project: https://github.com/jnoxon/vcspoc

**Comment by seankhliao** [comment] 2022-02-23 00:29
Duplicate of #51279

**Closed by seankhliao** 2022-02-23 00:29 UTC
Labels: WaitingForInfo, NeedsInvestigation
