### ISSUE TITLE
 http.Get do not redirect

### ISSUE THREAD

**Issue by solanu** [golang/go#45689] opened 2021-04-22 07:01 UTC
<pre>
$ go version
go version go1.16.3 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\aaa\AppData\Local\go-build
set GOENV=C:\Users\aaa\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\aaa\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\aaa\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\aaa\AppData\Local\Temp\go-build848562969=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

```
func Download(url, dir string) error {
    resp, err := http.Get(url)
    if err != nil {
        return err
    }
    defer resp.Body.Close()
    filename := filepath.Base(url)
    filepath := path.Join(dir, filename)
    out, err := os.Create(filepath)
    if err != nil {
        return err
    }
    defer out.Close()
    _, err = io.Copy(out, resp.Body)
    return err
}

url  := "https://prdownloads.sourceforge.net/expat/expat-2.2.10.tar.xz"
Download(url, ".")
```

### What did you expect to see?

I expect tar.xz content downloaded

### What did you see instead?

html content is downloaded because web has `<meta http-equiv="refresh" content="5; ...">` and http.Get do not redirect.

**Comment by seankhliao** [comment] 2021-04-22 07:05
`http-equiv` is part of `html` and not `http`. also the client cannot read the request body.

Closing as working as intended

**Closed by seankhliao** 2021-04-22 07:05 UTC
