### ISSUE TITLE
x/website:Is the document link wrong?

### ISSUE THREAD

**Issue by zh-five** [golang/go#50103] opened 2021-12-11 08:54 UTC
### What is the URL of the page with the issue?
 https://go.dev/learn/
 
 
### What is your user agent?
 

 I don't know
 
 
### Screenshot
 

 
![go_dev](https://user-images.githubusercontent.com/22364149/145670396-9befb815-6686-42d7-a731-4eee9860e440.png)

 
 
### What did you do?
 

Use Chrome to open https://go.dev/learn/
Click on the "Documentation" link
Open the new page address is https://go.dev/doc/install

 
 
### What did you expect to see?
 Open the new page address is https://go.dev/doc
 
 
### What did you see instead?
Open the new page address is https://go.dev/doc/install

**Comment by seankhliao** [comment] 2021-12-11 08:55
Duplicate of #49971

**Closed by seankhliao** 2021-12-11 08:55 UTC
Labels: Documentation
