### ISSUE TITLE
x/sys: started using unsafe.Slice, breaking build for AppEngine apps (still stuck on Go 1.16)

### ISSUE THREAD

**Issue by imax9000** [golang/go#56493] opened 2022-10-31 11:14 UTC
### What version of Go are you using (`go version`)?

1.16

### Does this issue reproduce with the latest release?

Latest available for App Engine - yes.

### What operating system and processor architecture are you using (`go env`)?

App Engine

### What did you do?

`gcloud app deploy` on an app that uses `google.golang.org/api`

### What did you expect to see?

Successful deployment

### What did you see instead?

```
ERROR: (gcloud.app.deploy) Error Response: [9] Cloud build 29375b3e-c5bc-4447-b3b9-1214df02306d status: FAILURE
# golang.org/x/sys/unix
../../google.go.gomod/gopath/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall.go:83:16: undefined: unsafe.Slice
../../google.go.gomod/gopath/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall_linux.go:2255:9: undefined: unsafe.Slice
../../google.go.gomod/gopath/pkg/mod/golang.org/x/sys@v0.1.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
../../google.go.gomod/gopath/pkg/mod/golang.org/x/sys@v0.1.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
note: module requires Go 1.17
```

**Comment by seankhliao** [comment] 2022-10-31 17:36
Please use an older version of x/sys that corresponds to that time period.
And file an issue with Google Cloud to update their runtimes.

The Go project has its own release cycle/support policy of the 2 most recent releases https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance

Closing as not a bug (for the Go project).

Unlike many projects, the Go project does not use GitHub Issues for general discussion or asking questions. GitHub Issues are used for tracking bugs and proposals only.

For questions please refer to https://github.com/golang/go/wiki/Questions

**Closed by seankhliao** 2022-10-31 17:36 UTC
