### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by SuperH-0630** [golang/go#56389] opened 2022-10-24 09:17 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.2 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\jimso\AppData\Local\go-build
set GOENV=C:\Users\jimso\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\jimso\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\jimso\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\jimso\tempconv\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\jimso\AppData\Local\Temp\go-build173486358=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

1. Create a go module to the git remote repository, push the tag v2.0.3, do not push the tag v2.0.4
2. The local project go.mod depends on the remote warehouse project v2.0.3, and the `go list` is normal.
3. The local project go.mod depends on the remote warehouse project v2.0.4, and `go list` reports an error.
4. Push v2.0.4 to the remote warehouse, and `go list` again to report an error.
5. Push v2.0.5 to the remote warehouse, go.mod depends on the remote warehouse project v2.0.5, and the go list is normal.

Error Log:
```
go: {{ my website }}/songzh/tempconv/v2@v2.0.4: verifying go.mod: {{ my website }}/songzh/tempconv/v2@v2.0.4/go.mod: reading https://goproxy.cn/sumdb/sum.golang.org/lookup/{{ my website }}/songzh/tempconv/v2@v2.0.4: 404 Not Found
	server response: not found: {{ my website }}/songzh/tempconv/v2@v2.0.4: invalid version: unknown revision v2.0.4
```

If `go mod tidy`, the same will happend.

### What did you expect to see?

The local project go.mod depends on the remote warehouse project v2.0.4, and the go list is normal.

### What did you see instead?

Error: unknown revision v2.0.4.

**Comment by seankhliao** [comment] 2022-10-24 11:58
Duplicate of #42809

**Closed by seankhliao** 2022-10-24 11:58 UTC
