### ISSUE TITLE
proposal: sorted map

### ISSUE THREAD

**Issue by rossb83** [golang/go#69433] opened 2024-09-12 22:41 UTC
### Proposal Details

The standard library should offer a `sorted_map` structure similar to other languages like c++ and java. This would make operations like sorted iteration, finding min, and finding max all efficient and convenient operations.

**Comment by jimmyfrasche** [comment] 2024-09-12 22:44
Duplicate of #60630

**Closed by jimmyfrasche** 2024-09-12 22:44 UTC
Labels: Proposal
