### ISSUE TITLE
sort.Search GuessingGame documentation example does not work

### ISSUE THREAD

**Issue by bobjalex** [golang/go#43612] opened 2021-01-09 20:20 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 windows/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\bobja\AppData\Local\go-build
set GOENV=C:\Users\bobja\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\GoLib\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\GoLib
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\bobja\AppData\Local\Temp\go-build702450142=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you expect to see?
Expected to play the game.

### What did you see instead?
Console prompting for an answer to its question asked 2 questions on same prompt line, making the game unusable.

Found and seemed to fix the problem in the example code: changed the fmt.Scanf("%s", &s) to fmt.Scanf("%s\n", &s).

**Comment by bobjalex** [comment] 2021-01-09 20:23
Sorry, the "What did you do>" question seemed to be unanswered. Answer is: Copied and ran the GuessingGame example from the sort.Search documentation.

**Comment by robpike** [comment] 2021-01-10 19:48
I tried this and it works fine as is, without the newline. We need more information.

**Comment by ALTree** [comment] 2021-01-10 19:52
The example also work for me on Linux, but... [#23562: Scanf works differently on Windows and Linux](https://github.com/golang/go/issues/23562), and OP is using Windows. Possible root cause? The example was written and never tested on Windows?

**Comment by bobjalex** [comment] 2021-01-11 06:50
Here's the output when I run the code as it appears in the documentation:

Pick an integer from 0 to 100.
Is your number <= 50? y
Is your number <= 25? Is your number <= 12?

I double checked that my source code is properly formatted with Unix line
endings.
When I run it with the \n fix I noted, it works as expected.

I can't try it on Linux -- no easy access to a Linux box.

Could you guys try it on Windows? That should put it to bed quickly. If it
fails the same as it does for me, it's probably a Scan bug. If not, well,
this is not of any consequence to me. Just letting you know of the behavior
I'm seeing...

**Comment by ALTree** [comment] 2021-01-11 07:56
I can confirm the issue is reproducible on Windows (using cmd). So yeah I think #23562 is indeed the root cause.

**Comment by ALTree** [comment] 2021-06-13 10:01
Closing as a dup of #23562.

**Closed by ALTree** 2021-06-13 10:01 UTC
Labels: Documentation, WaitingForInfo
