### ISSUE TITLE
x/tools/gopls: improve completion suggestions

### ISSUE THREAD

**Issue by urandom** [golang/go#37656] opened 2020-03-04 12:22 UTC
Hi,

This observation is from using gopls@0.3.3.

Suggestions for field values and function arguments aren't very useful.

If a completion is invoked for a field/func arg, logical suggestions such as empty-bodied functions (for func types), or map/array/struct composite literal expressions are never suggested. Instead, various variables, methods, functions, interfaces and base types that cannot possibly be used as values are suggested instead.

Some real examples:

`(*chi.Mux).Use(`|         <- expects varargs of `func(http.Handler) http.Handler`

I would expect the first (or at least the top 3) suggestion to be `func(http.Handler) { return nil }`. Instead, the second suggestion is for a `chi.Chain`, which has a type of `func (middlewares ...func(http.Handler) http.Handler) Middlewares`. In fact, only the first suggestion has the correct type. Everything else has a completely different type, including curious suggestions such as module paths and builtin functions and types for some reason.

Another example:

`(*mongo.Client).Database(`|          <- expects `string`

At the very least, I would expect an empty string as one of the top suggestions. Instead, the first suggestion is a function that returns a pointer to something, the second is also a function that accepts a pointer and returns another pointer, the third is a method, and the 4th is `nil`. Then I get various variables that are in scope but are not strings and I end up with the soup of builtins/module paths/interfaces and whatnot.

Returning some types or methods could be useful, because you can continue the expression to possibly get to the correct type. But they shouldn't be the first suggestions, and suggesting builtins or interfaces isn't helpful at all, because you cannot keep typing afterwards and end up with the needed type.

**Comment by stamblerre** [comment] 2020-03-04 14:44
Thank you for the report. Can you provide a link to the repo where you are seeing these issues? I appreciate the examples, but it is hard to understand them completely without the full context of the package.

**Comment by urandom** [comment] 2020-03-04 15:03
Really, any piece of code will illustrate the problem. consider for example trying to pass in a func literal to something that expects an http.HandlerFunc, or this example:
```
	type fT struct { 
		F []string
	}

	f := fT{F: 

```
here, you won't get a `[]string{}` as a completion suggestion.

But I built the original examples while working on https://github.com/globusdigital/feature-toggles (e.g.: https://github.com/globusdigital/feature-toggles/blob/master/storage/mongo.go#L85)

**Comment by stamblerre** [comment] 2020-03-04 19:02
Thanks for the link. We'll take a look.

/cc @muirdm

**Comment by muirdm** [comment] 2020-03-04 19:44
This is what I see (note the first two candidates):

![Screen Shot 2020-03-04 at 11 38 58 AM](https://user-images.githubusercontent.com/11356572/75916215-bf47e580-5e0c-11ea-8c98-1f7c00ab2740.png)

What editor are you using and what do you see as your candidates? I'm guessing the problem is that you don't have snippets enabled. We recently changed literal completions to require the client to support snippets.

For your original issue, there is another problem where literal completions don't work for variadic function args. I think we can fix that.

**Comment by muirdm** [comment] 2020-03-04 19:46
> At the very least, I would expect an empty string as one of the top suggestions.

The assumption is that typing the zero value for basic values is easy enough that you don't need a completion candidate.

**Comment by urandom** [comment] 2020-03-05 08:11
> The assumption is that typing the zero value for basic values is easy enough that you don't need a completion candidate.

For a string, yes. But for a struct, not so much. Unless that's also handled by these snippets you are talking about.

![Screenshot 2020-03-05 at 09 07 32](https://user-images.githubusercontent.com/7908/75960790-07284480-5ec1-11ea-80a2-48b3c6871015.png)

These are the suggestions if the field is a struct:
![Screenshot 2020-03-05 at 09 10 22](https://user-images.githubusercontent.com/7908/75960880-3343c580-5ec1-11ea-9f9e-73b36ccb0966.png)

The first one is ok, but that is as far as the usefulness of these suggestions go. None of the other are even remotely useful as a suggestion at that cursor position

**Comment by muirdm** [comment] 2020-03-05 16:30
Literal completions (e.g. `[]string{}` or `some.Struct{}`) require the client to have snippets supported/enabled. I would see if you can enable snippets in your client. You may have to install a separate package - I'm not too familiar with all the different Vim flavors/clients. You can ask on the #vim channel on [gophers slack ](https://invite.slack.golangbridge.org/).

@stamblerre we may want to reconsider disabling all literal completions when the client doesn't have snippets.

**Comment by urandom** [comment] 2020-03-05 17:40
@muirdm 
What about all the suggested completions (except the first two) from the second screenshot? I don't see any way how one can produce something of type `bT` with any of those suggestions

**Comment by stamblerre** [comment] 2020-03-05 18:02
> @stamblerre we may want to reconsider disabling all literal completions when the client doesn't have snippets.

@muirdm: I thought we had done that, or do you mean disabling the `nil` completion item in the first example?

> What about all the suggested completions (except the first two) from the second screenshot? I don't see any way how one can produce something of type `bT` with any of those suggestions

This falls in the same category of literal completions, which are disabled if snippets are not supported by the client. @muirdm: Do you think we can come up with some best-effort literal completions that work without snippets?

**Comment by muirdm** [comment] 2020-03-05 18:27
Literal completions already have non-snippet versions. We disabled them in https://go-review.googlesource.com/c/tools/+/216299, but there was some confusion in that decision (I had a [critical typo ](https://github.com/golang/go/issues/36655#issuecomment-576501870) in the related issue where I voted for the wrong change).

Regarding all the junk candidates that couldn't possibly be useful, I think we can start filtering some of them out. I can make a separate issue for that.

**Comment by stamblerre** [comment] 2020-03-05 18:35
Ah, I'm sorry I didn't realize that these were our non-snippet versions of the candidates. Maybe they could diverge further from the snippet versions like @myitcv suggested in the original bug (https://github.com/golang/go/issues/36655):

> What did you expect to see?

> ```&protocol.SignatureHelpParams```

> What did you see instead?

> ```&protocol.SignatureHelpParams{}```

**Comment by muirdm** [comment] 2020-03-05 18:44
Since the only issue is having to backtrack with the cursor, maybe we could do `&protocol.SignatureHelpParams{`. Optionally we could try to use an additional edit to place the closing curly after the cursor, as @myitcv originally suggested.

**Comment by stamblerre** [comment] 2020-03-05 18:53
Either works for me, though maybe we can start with just the opening brace if that's easier?

**Comment by myitcv** [comment] 2020-03-05 19:13
@muirdm 

> Optionally we could try to use an additional edit to place the closing curly after the cursor, as @myitcv originally suggested.

This would of course get my vote ;-)

**Comment by muirdm** [comment] 2020-03-06 00:36
I played around with the idea of emulating simple snippets using insert text and additional edits: https://go-review.googlesource.com/c/tools/+/222198

Honestly I don't think it is worth the extra code. I think we should either leave the current behavior and encourage people to use snippets, or revert to the previous behavior where, if you don't have snippets, you get `[]foo{}<>` inserted and have to move one character to the left if you want to put stuff in the literal. That is no more keypresses than completing to `[]foo` or `[]foo{` and having to type the curlie(s) yourself.

**Comment by myitcv** [comment] 2020-03-06 06:00
Thanks for putting together a CL, @muirdm.

> Honestly I don't think it is worth the extra code

Just to refresh on the reasons I think this is worthwhile:

* not all editors (read: at least Vim) have native snippet support, hence it relies on the user installing another plugin to add this support
* modal editors like Vim make the "just move the cursor one to the left" option really painful. This option also kind of defeats the point of LSP, because it feels like we're saying "we could do this on the server but you can just work around it". 

The code changes didn't look that invasive to my untrained eye?

**Comment by urandom** [comment] 2020-03-06 08:01
@muirdm 

tbh, i'm absolutely fine as a user if i just have to move the cursor back a character after insertion. it's an insignificant price to pay to get those suggestions back, at least until the time that neovim gets support for snippets.

**Comment by muirdm** [comment] 2020-03-06 15:43
> modal editors like Vim make the "just move the cursor one to the left" option really painful

Doesn't vim support the arrow keys these days? 😛 

I'd rather the server not jump through hoops if the user can just install another package and get a better/fancier experience anyway. I know you @myitcv (and your users, and maybe other vim users) don't have that option yet, so I leave it up to @stamblerre.

**Comment by stamblerre** [comment] 2020-03-06 18:26
I agree with @muirdm that the extra code isn't worth it (note that the CL is https://golang.org/cl/222198, not https://golang.org/cl/222199 in https://github.com/golang/go/issues/37656#issuecomment-595584410 above). Thank you for doing this work, though! I really appreciate the investigation. If it's possible to install a Vim plugin that supports snippets, I would suggest that as the way forward.

**Closed** 2020-03-27 01:00 UTC
Labels: Tools, WaitingForInfo, gopls

**Comment by urandom** [comment] 2020-03-30 19:28
@stamblerre
With this change, will gopls now suggest the literal completions even without snippet support?

**Comment by stamblerre** [comment] 2020-03-30 20:51
I don't believe so. I think we will stick to the approach @muirdm suggested in https://github.com/golang/go/issues/37656#issuecomment-595826663, which is to recommend that Vim users install another package that adds snippet support.
