### ISSUE TITLE
fmt.Printf("%v") panics when time.Month is embedded in a struct

### ISSUE THREAD

**Issue by jba** [golang/go#18479] opened 2016-12-30 22:58 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

1.7.4

### What operating system and processor architecture are you using (`go env`)?

playground

### What did you do?

https://play.golang.org/p/Zsst7dbgmd

### What did you expect to see?

valid output

### What did you see instead?

panic output

**Comment by cespare** [comment] 2016-12-30 23:02
This is just how `time.Month(0).String()` behaves; no need for struct embedding.

https://play.golang.org/p/0ycnF_0YBg

Perhaps time.Month.String should specially handle the zero value, though.

**Comment by robpike** [comment] 2016-12-30 23:02
This has nothing to do with Printf. A better recreation is here: https://play.golang.org/p/tvvroOOWZk

The problem is (was) that time.Month.String was panicking.

In any case it's fixed in 1.8.

**Comment by robpike** [comment] 2016-12-30 23:03
$ cat x.go
package main

import "time"

func main() {
	var m time.Month
	println(m.String())
}
$ go run x.go
%!Month(0)
$

**Closed by robpike** 2016-12-30 23:02 UTC
