### ISSUE TITLE
cmd/go: go get fails when directory command launched from gets deleted

### ISSUE THREAD

**Issue by abraithwaite** [golang/go#14093] opened 2016-01-26 00:57 UTC
```
$ cd /tmp
$ mkdir asdf
$ cd asdf
$ go get  github.com/influxdata/telegraf &
$ cd ../ && rmdir asdf
# cd .; git clone https://github.com/influxdb/influxdb /home/jessie/Projects/golang/src/github.com/influxdb/influxdb
Cloning into '/home/jessie/Projects/golang/src/github.com/influxdb/influxdb'...
fatal: Unable to read current working directory: No such file or directory
fatal: remote did not send all necessary objects
package github.com/influxdb/influxdb/models: exit status 128
# cd .; git clone https://github.com/stretchr/testify /home/jessie/Projects/golang/src/github.com/stretchr/testify
fatal: Could not get current working directory: No such file or directory
package github.com/stretchr/testify/mock: exit status 128
# cd .; git clone https://github.com/naoina/toml /home/jessie/Projects/golang/src/github.com/naoina/toml
fatal: Could not get current working directory: No such file or directory
package github.com/naoina/toml/ast: exit status 128
```
```
$ go version
go version go1.5.3 linux/amd64
```
Since the directory is not in the `$GOPATH/` tree, I did not expect any errors.  It's pretty minor but worth mentioning if others run into it.

**Comment by davecheney** [comment] 2016-01-26 01:04
You start go get in the background, then while it is running cd up one directory and delete the CWD that git (forked from go get) is running in.

I understand that go get will be checking out into a different location, but I don't think it is unreasonable for git to assume that it's cwd will remain valid while it's doing a checkout.

I don't believe that there is anything to fix in the go tool for the bug you've reported, but I get a feeling that this is a reproduction of a different issue that you're trying to solve. Can you explain more about how you discovered this issue.

**Comment by abraithwaite** [comment] 2016-01-26 01:14
Sure thing.  I accidentally cloned a repo to the wrong location instead of using go get and when I realized this, I used `go get` instead (in the repo I accidentally cloned) to fetch the repo into my `GOPATH`.  Meanwhile in another terminal I decided to clean up the mis-cloned repo, resulting in this error.

**Comment by rakyll** [comment] 2016-01-26 02:32
git is looking for the cwd in order to convert the relative paths to absolute. In the case of `go get`, we are already working with absolute paths. If the fix takes only setting an env variable such as GIT_DIR, we don't have to expose the reported limitation to the go-get users. Having said that, I haven't yet find a quick fix.

**Comment by davecheney** [comment] 2016-01-26 02:37
@rakyll go get forks git in the current working directory. It could equally fork git in `$GOPATH/src` or another location that _should_ exist.

Having said that, I'm unconvinced this is a bug or should be fixed. If you don't want git to complain that the working directory is missing, don't delete it behind git's back.

**Comment by rakyll** [comment] 2016-01-26 02:54
@davecheney  To be more clear, I don't understand why go get is cloning in the current directory. go get is a tool to download packages to a certain destination that is not tied to the cwd. I am not quite convinced the current case shouldn't be improved even though I'd say it is not critical enough to care.

**Comment by davecheney** [comment] 2016-01-26 03:01
Go get isn't cloning in the current directory, git is, because the go tool
didn't change the directory to anything else yet. I'm sure we can fix that.

**Comment by rakyll** [comment] 2016-01-26 03:15
> Go get isn't cloning in the current directory, git is,

Sorry for the implicit wording, this is what I meant above. I am talking about cd'ing into GOPATH (or setting an env variable if possible) to make git clone in a directory that makes sense.

**Comment by davecheney** [comment] 2016-01-26 03:18
Sounds good to me.

**Comment by quentinmit** [comment] 2016-10-06 18:49
I don't think it's worth putting a workaround in here; many Unix programs including "go get" become unhappy if their working directory goes away while they are running. "Don't do that."

**Closed by quentinmit** 2016-10-06 18:49 UTC
