### ISSUE TITLE
runtime: sporadic huge GC pause

### ISSUE THREAD

**Issue by funny-falcon** [golang/go#11694] opened 2015-07-13 14:30 UTC
This simple "single list" garbage producer sometimes encounts huge pauses:

````go
package main

import (
	"fmt"
	"time"
	"flag"
)

type list struct {
	next *list
}

func dojob(N int) {
	var prev, cur time.Time
	var first, last *list
	var n int
	prev = time.Now()
	for {
		var nuo list;
		if last != nil {
			last.next = &nuo
		}
		if first == nil {
			first = &nuo
		}
		last = &nuo
		n++
		if n >= N {
			first = first.next
			n--
		}
		cur = time.Now()
		diff := cur.Sub(prev)
		if diff > 10*time.Millisecond {
			fmt.Printf("%fms\n", diff.Seconds() *1000)
		}
		prev = cur
	}
}

var N = flag.Int("N", 10, "num in list")

func main() {
	flag.Parse()
	dojob(*N)
}
````
````
$ go version
go version devel +ca6ba49 Mon Jul 13 06:40:00 2015 +0000 linux/amd64
$ go run gc.go -N 10000000
10.942411ms
483.928657ms
50.785114ms
435.676484ms
413.611303ms
^Cexit status 2
$ go run gc.go -N 10000000
^Cexit status 2
$ go run gc.go -N 10000000
381.920956ms
11.483340ms
385.989617ms
````

**Comment by ianlancetaylor** [comment] 2015-07-13 14:43
Could this be the same as issue #10261 ?

**Comment by ianlancetaylor** [comment] 2015-07-13 14:43
CC @RLH @aclements

**Comment by aclements** [comment] 2015-07-13 15:12
According to @funny-falcon's go version, this includes the fix for #10261. Also, I can reproduce locally, and the bad GC is not marked as "(forced)" in the gctrace line:

    $ GODEBUG=gctrace=1 go run gc.go -N 10000000
    ...
    gc #31 @33.760s 26%: 0.25+0.32+0.003+18+823 ms clock, 1.0+0.32+0+0.97/841/18+3294 ms cpu, 148->149->77 MB, 152 MB goal, 4 P
    823.746607ms
    ...

**Comment by aclements** [comment] 2015-07-13 15:42
My guess is that we sometimes miss a large part of the list during concurrent mark and then spend a long time in mark termination tracing the huge list.

**Comment by RLH** [comment] 2015-07-13 17:35
I am seeing the loop in stopTheWorldWithSema which waits for the goroutine
to preempt looping a lot.
In one instance I saw it doing 2850 100 microsecond (285 ms) waits before
the preempt. The program
then reported a 485 ms pause.

**Comment by aclements** [comment] 2015-07-13 17:47
> I am seeing the loop in stopTheWorldWithSema which waits for the goroutine
> to preempt looping a lot.

Interesting. That's really surprising, since that loop is meant to handle the race where we mark a G for preemption, but then it gets scheduled out for another G (which we didn't mark for preemption) before it notices the preemption. But the user code here is all on the main G. Do you know what G is not being successfully preempted?

**Comment by aclements** [comment] 2015-07-13 17:48
(And is it perhaps in a system call?)

**Comment by funny-falcon** [comment] 2015-07-13 18:09
Interesting: with `GOMAXPROCS=1` it performs quite stable with maximum pause ~ 20ms

**Comment by mkevac** [comment] 2015-07-17 12:27
We also have one long GC a day. ![Screenshot](http://i.imgur.com/R1mvVVE.png)

**Comment by RLH** [comment] 2015-07-17 13:58
Thanks, I've been looking at this and for some reason we incorrectly
attempt to do a STW when one of the gc mark helpers is active and we have
no way to stop an active gc mark helper. It is clearly a bug that we need
to understand better. Once a day in production seems like a lot.

**Comment by RLH** [comment] 2015-07-17 19:28
Marko,
Is there any place in your code where you do a forced GC, ie call
runtime.GC()? That could explain the long GC. Perhaps you reboot daily and
as part of the initialization do a runtime.GC()?
- Rick

**Comment by mkevac** [comment] 2015-07-17 19:31
Sorry. We don't do runtime.GC() and uptime of this particular replica is 4d 9h 8m 9s.

**Comment by RLH** [comment] 2015-07-21 17:52
It appears that occasionally a pointer can hide from the GC during the the concurrent mark phase. This bench is particularly sensitive to such a lost pointer since in this program the pointer might be the only access to a large (10,000,000) object list.  The solution is to spend more effort ensuring that the concurrent mark phase has seen such objects.

**Comment by RLH** [comment] 2015-07-21 17:54
I didn't mean to close this. Sorry.

**Comment by funny-falcon** [comment] 2015-07-22 08:52
I tried to force "allocate as old" earlier by setting `gcBlackenPromptly` before concurrent mark event starts. It didn't help.
(I did split `gcBlackenPromptly` into two flags, introducing `gcBgmark1Done`).
(perhaps i've made a mistake somewhere).

**Comment by RLH** [comment] 2015-07-22 13:29
We are seeing the same thing here. Not allocating black (or "as old" as you
say) isn't the problem, the problem is that the mutator is hiding a pointer
from the GC long enough for the GC to make it to mark termination where it
finds the hidden pointer along with the large untraced list it is connected
to.

**Comment by jfbus** [comment] 2015-07-24 11:59
Similar problem on my side.

On a 4 core machine, I got random STW GC with GOMAXPROCS not set. With GOMAXPROCS set to 2, most GC are STW.

Using the same test code, without the Printf :

No GOMAXPROCS :
```
gc #10 @4.259s 31%: 0.20+0.21+0.001+877+0.68 ms clock, 0.81+0.21+0+265/877/6.8+2.7 ms cpu, 148->202->130 MB, 152 MB goal, 4 P
gc #11 @5.285s 30%: 0.24+0.24+0.002+869+0.72 ms clock, 0.98+0.24+0+257/869/7.2+2.8 ms cpu, 148->214->129 MB, 152 MB goal, 4 P
gc #12 @6.198s 35%: 0.79+0.25+0.002+118+331 ms clock, 2.3+0.25+0+343/449/119+995 ms cpu, 114->138->84 MB, 117 MB goal, 4 P
gc #13 @6.887s 33%: 0.23+0.27+0.001+419+0.48 ms clock, 0.93+0.27+0+128/419/1.8+1.9 ms cpu, 148->177->104 MB, 152 MB goal, 4 P
gc #14 @7.459s 33%: 0.26+0.28+0.002+875+0.57 ms clock, 1.0+0.28+0+266/875/8.2+2.2 ms cpu, 143->196->129 MB, 152 MB goal, 4 P
gc #15 @8.423s 33%: 0.21+0.27+0.002+466+0.72 ms clock, 0.87+0.27+0+262/466/238+2.9 ms cpu, 148->164->91 MB, 152 MB goal, 4 P
```

GOMAXPROCS=2 :

```
gc #10 @3.983s 51%: 0.18+0.16+0.003+770+0.26 ms clock, 0.37+0.16+0+731/36/20+0.53 ms cpu, 148->152->79 MB, 152 MB goal, 2 P
gc #11 @5.002s 55%: 0.18+0.22+0.003+95+742 ms clock, 0.36+0.22+0+22/54/40+1485 ms cpu, 148->155->82 MB, 152 MB goal, 2 P
gc #12 @6.075s 58%: 0.19+0.17+0.003+91+725 ms clock, 0.39+0.17+0+22/51/40+1450 ms cpu, 148->155->82 MB, 152 MB goal, 2 P
gc #13 @7.131s 58%: 0.21+0.23+0.001+37+412 ms clock, 0.43+0.23+0+5.4/17/20+824 ms cpu, 148->151->79 MB, 152 MB goal, 2 P
gc #14 @7.835s 60%: 0.20+0.16+0.003+31+776 ms clock, 0.40+0.16+0+9.8/11/20+1553 ms cpu, 148->150->78 MB, 152 MB goal, 2 P
gc #15 @8.907s 57%: 0.27+0.19+0.003+767+0.27 ms clock, 0.55+0.19+0+730/32/20+0.55 ms cpu, 148->152->79 MB, 152 MB goal, 2 P
```

**Closed** 2015-07-27 20:00 UTC

**Comment by funny-falcon** [comment] 2015-07-28 08:17
WOW!!!! IT IS REALLY GREAT!!!! maximum observed STW pause is 30ms now.

**Comment by RLH** [comment] 2015-07-28 14:12
16 hours and 51000+ GCs and we saw only two large pauses which is well
within 4 nines, so not bad, not critical, but worth noting.

One theory Austin and I have discussed is that the scheduler, dispose, and
write barriers can conspire to hide the a pointer from the GC.
If dispose has a partially full work buffer and places it on the partial
list but before the GC can grab and process it the scheduler runs a
mutator that grabs the same partially full work  buffer. This repeats until
we reach the mark termination phase where the GC finally
finds the pointer along with a lot of work to do.

One solution is to have dispose put the work buffer on the full list where
the write barrier will not ask for it until the GC empties it.


Snip and clip.
------- After 6 or so hours -------

gc 29868 @34053.633s 11%: 0.21+0.25+0.039+3.6+526 ms clock,
2.6+0.25+0+3.6/0.001/0.081+6323 ms cpu, 148->148->76 MB, 152 MB goal, 12 P

 SLOW --- 530.875781ms---
gc 29869 @34054.805s 11%: 0.21+0.30+0.005+511+1.0 ms clock,
2.5+0.30+0+1.2/1532/2.0+12 ms cpu, 148->150->78 MB, 152 MB goal, 12 P

------- and a few hours later -------

gc 37355 @42584.723s 11%: 0.21+0.22+0.046+12+854 ms clock,
2.6+0.22+0+1.9/1744/10+10253 ms cpu, 148->148->76 MB, 152 MB goal, 12 P

 SLOW --- 867.288968ms---
gc 37356 @42586.226s 11%: 0.24+0.31+0.001+512+0.77 ms clock,
2.9+0.31+0+1.3/1535/2.0+9.2 ms cpu, 148->150->78 MB, 152 MB goal, 12 P

**Comment by aclements** [comment] 2015-07-28 15:37
> 16 hours and 51000+ GCs and we saw only two large pauses which is well
> within 4 nines, so not bad, not critical, but worth noting.

Definitely not bad for a worst-case test program.

> One theory Austin and I have discussed is that the scheduler, dispose, and
> write barriers can conspire to hide the a pointer from the GC.
> If dispose has a partially full work buffer and places it on the partial
> list but before the GC can grab and process it the scheduler runs a
> mutator that grabs the same partially full work  buffer. This repeats until
> we reach the mark termination phase where the GC finally
> finds the pointer along with a lot of work to do.

The sequence that I'm envisioning is somewhat different. Initially, all workers are idle, there's only one workbuf, and it's on the partial list. 1) A write barrier grabs a partial buffer to add a pointer; 2) some worker or the scheduler wakes up; 3) the worker or scheduler sees that there are no workbufs on the global queues and there are no active workers and signals completion of mark 2; 4) the write barrier disposes its buffer, but we're already going in to mark termination.

> One solution is to have dispose put the work buffer on the full list where
> the write barrier will not ask for it until the GC empties it.

Note that this is equivalent to simply not using the work.partial list, since this is the only thing that puts buffers on the partial list. That isn't necessarily a bad thing, but it's not obvious to me what all of the consequences of that are.
