### ISSUE TITLE
x/tools/gopls: duplicate "undeclared name" errors following CL222237

### ISSUE THREAD

**Issue by myitcv** [golang/go#38136] opened 2020-03-28 20:33 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +2e918c3aab Tue Mar 17 06:38:32 2020 +0000 linux/amd64
$ go list -m golang.org/x/tools
golang.org/x/tools v0.0.0-20200328031815-3db5fc6bac03
$ go list -m golang.org/x/tools/gopls
golang.org/x/tools/gopls v0.1.8-0.20200328031815-3db5fc6bac03
</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myitcv/.cache/go-build"
GOENV="/home/myitcv/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myitcv/gostuff"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/myitcv/gos"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/myitcv/gos/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/myitcv/gostuff/src/github.com/myitcv/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build432849091=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

As pointed out by @findleyr in https://github.com/govim/govim/pull/832#issuecomment-605335928, we are seeing duplicate "undeclared name" errors from `gopls`, as highlighted by the following `govim` test.

```
# Test for duplicate undefined errors

# Ensure we have two warnings
vim ex 'e main.go'
vimexprwait warnings.golden GOVIMTest_getqflist()

# Now create a single error and verify we see only that
vim ex 'e other.go'
vim call append '[6,"asd"]'
vimexprwait errors.golden GOVIMTest_getqflist()

-- go.mod --
module mod.com

go 1.12
-- main.go --
package main

import "fmt"

func main() {
	fmt.Printf("%v")
}
-- other.go --
package main

import "fmt"

func foo() {
	fmt.Printf("%v")
}
-- warnings.golden --
[
  {
    "bufname": "main.go",
    "col": 2,
    "lnum": 6,
    "module": "",
    "nr": 0,
    "pattern": "",
    "text": "Printf format %v reads arg #1, but call has 0 args",
    "type": "",
    "valid": 1,
    "vcol": 0
  },
  {
    "bufname": "other.go",
    "col": 2,
    "lnum": 6,
    "module": "",
    "nr": 0,
    "pattern": "",
    "text": "Printf format %v reads arg #1, but call has 0 args",
    "type": "",
    "valid": 1,
    "vcol": 0
  }
]
-- errors.golden --
[
  {
    "bufname": "other.go",
    "col": 1,
    "lnum": 7,
    "module": "",
    "nr": 0,
    "pattern": "",
    "text": "undeclared name: asd",
    "type": "",
    "valid": 1,
    "vcol": 0
  }
]
```

The output from the test is:

```
        # Test for duplicate undefined errors (0.497s)
        > vim ex 'e main.go'
        > vimexprwait warnings.golden GOVIMTest_getqflist()
        # open other.go and add a broken statement to get an error that masks the warnings (4.956s)
        > vim ex 'e other.go'
        > vim call append '[6,"asd"]'
        [stdout]
        0
        > vimexprwait errors.golden GOVIMTest_getqflist()
        [stderr]
         [
           {
             "bufname": "other.go",
             "col": 1,
             "lnum": 7,
             "module": "",
             "nr": 0,
             "pattern": "",
             "text": "undeclared name: asd",
             "type": "",
             "valid": 1,
             "vcol": 0
        -  },
        -  {
        -    "bufname": "other.go",
        -    "col": 1,
        -    "lnum": 7,
        -    "module": "",
        -    "nr": 0,
        -    "pattern": "",
        -    "text": "undeclared name: asd",
        -    "type": "",
        -    "valid": 1,
        -    "vcol": 0
           }
         ]
        [exit status 1]
        FAIL: testdata/scenario_default/test.txt:9: unexpected command failure
```

### What did you expect to see?

The test passing

### What did you see instead?

The test failed, as above.

---

cc @stamblerre @ridersofrohan 

FYI @leitzler

**Comment by ridersofrohan** [comment] 2020-03-30 15:01
I can't seem to reproduce this using VSCode or running gopls tests. They only seem to return a single undeclared diagnostic. Are you able to see what the source of the diagnostic is (ex. "compiler", "undeclaredname",...)?

**Comment by myitcv** [comment] 2020-03-30 15:18
Apologies, I forgot to attach the `gopls` log. Here it is: [gopls.log](https://github.com/golang/go/files/4403738/gopls.log)

**Comment by ridersofrohan** [comment] 2020-03-30 16:21
@myitcv I created a test in https://golang.org/cl/226417 using Rob's regtest framework that does the same behavior as the vim test in question. It does not seem to be returning 2 diagnostics. From the `gopls` log you sent, it looks like the ranges are different. The way the new type error analyzers work is that there is a check to replace existing type errors with the analyzer error if they have the same range and message.

```
[Trace - 16:16:07.059 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///tmp/artefacts/govim/cmd/govim/scenario_default/script-signs_unload_load_buffer/other.go","version":2,"diagnostics":[{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":3}},"severity":1,"source":"compiler","message":"undeclared name: asd"},{"range":{"start":{"line":6,"character":0},"end":{"line":7,"character":0}},"severity":2,"source":"undeclaredname","message":"undeclared name: asd"}]}
```

@stamblerre is this a `gopls` thing?

cc @findleyr

**Comment by myitcv** [comment] 2020-03-30 16:26
@ridersofrohan - are the configurations identical, comparing your test with the `govim` test?

**Comment by stamblerre** [comment] 2020-03-30 17:27
@ridersofrohan: It looks like the ranges aren't the same for these errors - is that causing the problem, maybe?

**Comment by myitcv** [comment] 2020-04-02 17:01
What's the status here @stamblerre - did you close this by accident?

**Comment by stamblerre** [comment] 2020-04-02 17:01
Nope - the above CL fixes the test.

**Comment by myitcv** [comment] 2020-04-02 17:08
Ah sorry, I hadn't appreciated that. I saw:

```
Updates golang/go#38136
```

and assumed there were further CLs to follow.

**Comment by leitzler** [comment] 2020-04-02 17:11
Isn’t it easier to track progress if issues are closed after the CL is merged?

**Comment by stamblerre** [comment] 2020-04-02 17:13
Sorry about that, I had originally meant to leave this issue opened to track the follow-up CL I mentioned in the description, but then decided it wasn't worth leaving this open for that.

**Comment by myitcv** [comment] 2020-04-02 17:23
I see that https://go-review.googlesource.com/c/tools/+/226962 has actually fixed this. https://go-review.googlesource.com/c/tools/+/226777/ is not merged.

**Comment by stamblerre** [comment] 2020-04-03 15:46
Ah, ok since this is fixed I will close the issue. We'll re-enable these analyzers with `gopls/v0.5.0`, so we'll make sure not to break this test again with that release.

**Closed by stamblerre** 2020-04-03 15:46 UTC
Labels: NeedsInvestigation, Tools, gopls
