### ISSUE TITLE
proposal: Create standard option/maybe

### ISSUE THREAD

**Issue by FGasper** [golang/go#62482] opened 2023-09-06 16:50 UTC
(mo.Option)[https://github.com/samber/mo#optiont-any] is a useful implementation of the (Option type)[https://en.wikipedia.org/wiki/Option_type] in Go. It removes one use for nil pointers and thus reduces the potential for nil-dereference bugs.

Having this behaviour in Go’s standard library would amplify those benefits. I’m proposing that the standard library add a `maybe` package that implements the most useful bits of mo.Option, e.g.:
- `Some()`, `None()`, and `TupleToOption` functions
- `Get()`, `MustGet()`, `IsPresent()`
- `OrElse`, `OrEmpty`

Thank you for your consideration.

**Comment by seankhliao** [comment] 2023-09-06 17:53
Duplicate of #59202

**Closed by seankhliao** 2023-09-06 17:53 UTC
Labels: Proposal
