### ISSUE TITLE
net/http: TestTransportConcurrency crash

### ISSUE THREAD

**Issue by mikioh** [golang/go#15740] opened 2016-05-19 00:42 UTC
See https://build.golang.org/log/c6a86a0372c38c4287799eb323ce2a559a770315
```
ok  	net	1.862s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0xffffffff addr=0x0 pc=0xca834]

goroutine 5245 [running]:
panic(0x5504c0, 0x10e18030)
	/tmp/workdir/go/src/runtime/panic.go:500 +0x720
net/http.send(0x1187c200, 0xb51100, 0x12e7c420, 0x10e1a500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/tmp/workdir/go/src/net/http/client.go:243 +0x414
net/http.(*Client).send(0x11ccd080, 0x1187c200, 0x0, 0x0, 0x0, 0x0, 0x11fa2088, 0x0, 0x0, 0x2)
	/tmp/workdir/go/src/net/http/client.go:146 +0x1a0
net/http.(*Client).doFollowingRedirects(0x11ccd080, 0x1187c200, 0xa0f8b4, 0x24, 0x0, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/net/http/client.go:528 +0xd80
net/http.(*Client).Get(0x11ccd080, 0x12e160f0, 0x24, 0x5909ed, 0x7, 0x0, 0x0, 0x12cf1740)
	/tmp/workdir/go/src/net/http/client.go:418 +0xc0
net/http_test.TestTransportConcurrency.func3(0x11ffb600, 0x11ccd080, 0x11ffb5c0, 0x11acb080, 0x11fedf00, 0xa0f99c)
	/tmp/workdir/go/src/net/http/transport_test.go:1282 +0x140
created by net/http_test.TestTransportConcurrency
	/tmp/workdir/go/src/net/http/transport_test.go:1300 +0x500
FAIL	net/http	13.477s
```

**Comment by bradfitz** [comment] 2016-05-19 01:45
Is this reproducible? I've never seen this.

**Comment by bradfitz** [comment] 2016-05-20 22:24
I ran the test 500 times in both normal and race mode (which does random goroutine scheduling) and can't reproduce.

Closing until there's more to go on.

**Closed by bradfitz** 2016-05-20 22:24 UTC
