### ISSUE TITLE
parser: Incorrect type parsing of "chan <-chan"

### ISSUE THREAD

**Issue by klauspost** [golang/go#66336] opened 2024-03-15 13:54 UTC
### Go version

go version go1.22.1 windows/amd64

### Output of `go env` in your module/workspace:

```shell
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=e:\temp\gocache
set GOENV=C:\Users\klaus\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=e:\gopath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=e:\gopath
set GOPRIVATE=
set GOPROXY=https://goproxy.io,https://goproxy.dev,direct
set GOROOT=C:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.22.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=e:\temp\wintemp\go-build2794468500=/tmp/go-build -gno-record-gcc-switches
```

### What did you do?

Use the following code:

```
package main

func main() {
	var x chan <-chan interface{}
	var y <-chan interface{}
	y = <-x
	_ = y
}
```

Compile or run `go fmt`.

### What did you see happen?

Go incorrectly parses the first type definition as `var x chan<- chan interface{}` as can be seen by running it through `go fmt` which changes the type from the desired `chan <-chan interface{}`.

### What did you expect to see?

Code compiling & not being reformatted.

**Comment by zephyrtronium** [comment] 2024-03-15 14:13
https://go.dev/ref/spec#Channel_types states, "The `<-` operator associates with the leftmost `chan` possible," and provides example parses including `chan<- chan int    // same as chan<- (chan int)`. That is to say, `<-chan` is a sequence of two lexical tokens, despite the lack of space between.

**Comment by seankhliao** [comment] 2024-03-15 14:44
Closing as working as intended.

**Closed by seankhliao** 2024-03-15 14:44 UTC

**Comment by klauspost** [comment] 2024-03-15 14:53
So you must do `var x chan (<-chan interface{})` - wow...
