### ISSUE TITLE
math: `tan(math.Pi / 4)` returns different values on amd64 vs arm64

### ISSUE THREAD

**Issue by Defined2014** [golang/go#65337] opened 2024-01-29 04:29 UTC
### Go version

go version go1.21.5 darwin/arm64 and linux/amd64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/jasonmo/Library/Caches/go-build'
GOENV='/Users/jasonmo/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/jasonmo/go/pkg/mod'
GONOPROXY='github.com/pingcap/*'
GONOSUMDB='github.com/pingcap/*'
GOOS='darwin'
GOPATH='/Users/jasonmo/go'
GOPRIVATE='github.com/pingcap/*'
GOPROXY='https://goproxy.cn,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.5'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/jasonmo/github/tidb-x/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
```

### What did you do?

```
// You can edit this code!
// Click here and start typing.
package main

import (
	"fmt"
	"math"
)

func main() {
	b := math.Tan(math.Pi / 4)
	fmt.Println(b)
}
```

### What did you see happen?

On Arm64 env:
```
0.9999999999999998
```

On Amd64 env:
```
1
```

### What did you expect to see?

Results should be same and equal to 1.

**Comment by mauri870** [comment] 2024-01-29 09:43
That is to be expected, the language spec says that the results of floating point operations is platform dependent. 

The math package docs also state this at the very top.

**Comment by mauri870** [comment] 2024-01-29 09:43
Duplicate of https://github.com/golang/go/issues/18354

**Closed by mauri870** 2024-01-29 09:43 UTC
