### ISSUE TITLE
Division by constant floating point 0 should be permitted by the compiler or outlawed by the spec.

### ISSUE THREAD

**Issue by alercah** [golang/go#22591] opened 2017-11-05 21:37 UTC
See https://play.golang.org/p/jxi2L81R1j

This program is rejected as invalid by the compiler, because of a division by constant 0. This, however, does not match the spec: the language "If the divisor is a constant, it must not be zero." appears in the section on integer operations only, rather than for floating points. One or the other is wrong, then.

In light of the fact that division by floating-point 0 is not well-defined as yielding an infinite value, it may be desirable to ban this behaviour and direct users to math.Inf instead. See, however, #10006.

**Comment by griesemer** [comment] 2017-11-06 05:09
This is working as intended. This is not a "floating-point division" - it's a constant division of arbitrary precision numbers which is evaluated at compile-time. Division by zero is not permitted.

Note that https://play.golang.org/p/SF2MbYsxZ1 which is a float64 division by 0 is accepted and leads to a NaN.

Closing.

**Closed by griesemer** 2017-11-06 05:09 UTC

**Comment by griesemer** [comment] 2017-11-06 05:10
PS: See https://golang.org/ref/spec#Constant_expressions for the spec rule:
"The divisor of a constant division or remainder operation must not be zero". It has even an example that's basically this piece of code with different values.
