### ISSUE TITLE
cmd/compile: untyped arguments to `real` and `imag` converted to default type

### ISSUE THREAD

**Issue by momchil-velikov** [golang/go#15892] opened 2016-05-30 15:18 UTC
On 
go version devel +81a8f1a Mon May 30 05:24:16 2016 +0000 linux/amd64

the following program (https://play.golang.org/p/DbyUqeHamB), compiled with `go run real.go`

```go
package main
const A = real(1.1)
```

exits with error message
> /real.go:3: invalid argument 1.1 (type float64) for real

and behaves analogously with other kinds of untyped constants, passed as an argument
to `real` or `imag`.

The Go Language Specification seems to allow  any kind of
untyped numeric constant to be passed as an argument to `real` or `imag`.

https://golang.org/ref/spec#Complex_numbers

> For real and imag, the argument must be of complex type, and the return type is the corresponding
> floating-point type: float32 for a complex64 argument, and float64 for a complex128 argument. **If the
> argument evaluates to an untyped constant, it must be a number**, and the return value
> of the function is an untyped floating-point constant.

Both `gotypes` and `gccgo` accept the program without diagnostics.

**Comment by cznic** [comment] 2016-05-30 16:16
`1.1` is a `float64` untyped constant, not a typed or untyped `complex128` or (typed only) `complex64` constant, thus it is an invalid argument of the built int `real` function because

> For real and imag, the argument must be of **complex type**.

as you already quoted.

([Correct example](https://play.golang.org/p/crJxB_z9yJ))

**Comment by griesemer** [comment] 2016-05-30 16:32
Duplicate of #11946. Closing.

**Closed by griesemer** 2016-05-30 16:32 UTC
