### ISSUE TITLE
net: FileListener doesn't work on Plan 9

### ISSUE THREAD

**Issue by mikioh** [golang/go#10867] opened 2015-05-15 07:26 UTC
See https://storage.googleapis.com/go-build-log/a29b1dce/plan9-386-gcepartial_808d3016.log.

```
ok      mime/quotedprintable    0.164s
--- FAIL: TestFileListener (0.00s)
    file_test.go:168: file file+net /net/tcp/22/ctl: file does not represent a listener
FAIL
```

**Comment by bcmills** [comment] 2023-03-16 13:12
Duplicate of #29801

**Closed by bcmills** 2023-03-16 13:12 UTC
Labels: OS-Plan9
