### ISSUE TITLE
net/http/fs.go: dirList write hardcode about how to show the satic file list.

### ISSUE THREAD

**Issue by snowdream** [golang/go#60186] opened 2023-05-14 14:35 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.20.2 windows/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=D:\workspace\go\bin
set GOCACHE=C:\Users\snowdream\AppData\Local\go-build
set GOENV=C:\Users\snowdream\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\workspace\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\workspace\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.com.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.2
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\workspace\go\src\snowdream.tech\snowdream-server\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\SNOWDR~1\AppData\Local\Temp\go-build2673060699=/tmp/go-build -gno-record-gcc-switches

</pre></details>

### What did you do?

I Try to build a static file web server with gin framework.
https://gin-gonic.com/docs/examples/serving-static-files/
```
func main() {
	router := gin.Default()
	router.StaticFS("/more_static", http.Dir("my_file_system"))

	// Listen and serve on 0.0.0.0:8080
	router.Run(":8080")
}
```

I find that:

At last, net/http/fs.go: dirList  function is used to show the satic file list with hardcode.

https://github.com/golang/go/blob/master/src/net/http/fs.go#L153

```
w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprintf(w, "<pre>\n")
	for i, n := 0, dirs.len(); i < n; i++ {
		name := dirs.name(i)
		if dirs.isDir(i) {
			name += "/"
		}
		// name may contain '?' or '#', which must be escaped to remain
		// part of the URL path, and not indicate the start of a query
		// string or fragment.
		url := url.URL{Path: name}
		fmt.Fprintf(w, "<a href=\"%s\">%s</a>\n", url.String(), htmlReplacer.Replace(name))
	}
	fmt.Fprintf(w, "</pre>\n")
```
![微信图片_20230514223136](https://github.com/golang/go/assets/737958/ea3aef86-0496-42a4-b60f-b3c242b4b7ee)

### What did you expect to see?
I want to customize the page, as i will.

eg. Like Nginx with autoindex on.
![image](https://github.com/golang/go/assets/737958/b41358fa-fec5-4cc3-a287-b61a15289357)

### What did you see instead?

![微信图片_20230514223136](https://github.com/golang/go/assets/737958/ea3aef86-0496-42a4-b60f-b3c242b4b7ee)

**Comment by seankhliao** [comment] 2023-05-14 15:31
Duplicate of #29945

**Closed by seankhliao** 2023-05-14 15:31 UTC
