### ISSUE TITLE
[Bug report] Gomodule doesn't reconigze package

### ISSUE THREAD

**Issue by fwhezfwhez** [golang/go#45235] opened 2021-03-25 15:41 UTC
### What version of Go are you using (`go version`)?

go 1.12.17

### Does this issue reproduce with the latest release?

not tried yet

### What operating system and processor architecture are you using (`go env`)?
win 64

GO111MODULE=on
GOPROXY=https://goproxy.io

</pre></details>

### What did you do?

master branch
```go
git clone https://github.com/fwhezfwhez/model_convert.git

cd model_convert
go test -run ^TestGenerateWhere$
```

bad branch

```go
git clone https://github.com/fwhezfwhez/model_convert.git

cd model_convert

git fetch origin/bad
git checkout origin/bad

go test -run ^TestGenerateWhere$
```

### What did you expect to see?

bad branch should be as same as master branch
```
<just runable>
```

### What did you see instead?
bad branch
```
model_convert.go:13:2: unknown import path "github.com/go-sql-driver/mysql": cannot find package
model_convert.go:11:2: unknown import path "github.com/jinzhu/gorm": cannot find package
model_convert.go:15:2: unknown import path "github.com/jinzhu/gorm/dialects/postgres": cannot find package
model_convert.go:16:2: unknown import path "github.com/lib/pq": cannot find package
```

Here is the exact difference between them.

https://github.com/fwhezfwhez/model_convert/pull/3/files

**Comment by AlexRouSg** [comment] 2021-03-25 16:19
`1.12.17` is out of support, please try `1.16.2`

**Comment by seankhliao** [comment] 2021-03-25 16:40
Duplicate of #35726

**Closed by seankhliao** 2021-03-25 16:40 UTC
