### ISSUE TITLE
go tool trace not work

### ISSUE THREAD

**Issue by tiny1990** [golang/go#41291] opened 2020-09-09 13:35 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.13 linux/amd64
or
go version go1.14 
or
go version go1.15
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build933204170=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
```
wget -O trace.out  127.0.0.1:5555/debug/pprof/trace?seconds=5
# go tool trace trace.out
2020/09/09 21:31:18 Parsing trace...
failed to parse trace: no consistent ordering of events possible

# docker version
Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
```

### What did you expect to see?
2020/09/09 21:31:18 Parsing trace...
2019/12/17 10:19:28 Opening browser. Trace viewer is listening on http://127.0.0.1:42335

**Comment by tiny1990** [comment] 2020-09-09 13:38
I want to analyse dockerd, so  trace pragram is very imporant.
beacuse of the dockerd Goroutines is :  29003976

**Comment by tpaschalis** [comment] 2020-09-09 13:50
Hello, and thanks for opening this issue! The trace tool seems to be working correctly on my end with the latest release and Go tree.

The error that's produced comes from [this](https://github.com/golang/go/blob/50bd1c4d4eb4fac8ddeb5f063c099daccfb71b26/src/internal/trace/order.go#L53) function, which is responsible for ordering the trace events into a single consistent stream.

Can you provide more information on the code that's running to produce your trace, or a reproductible example?   
It might help to check whether #29707 is a dupe, a simple case of how you're closing your trace, or a new bug.

**Comment by tiny1990** [comment] 2020-09-09 13:58
@tpaschalis  thanks your reply.
sorry , i have no code, the `127.0.0.1:5555/debug/pprof/trace?seconds=5` is dockerd sock
or you can use `socat -d -d TCP-LISTEN:5555,fork,bind=0.0.0.0 UNIX:/var/run/docker.sock`  for test

**Comment by tpaschalis** [comment] 2020-09-09 16:57
I understand. The fact that the issue appears with CGO makes me think it's a dupe of #29707, since people are reporting reproducibility with CGO.

**Comment by tiny1990** [comment] 2020-09-09 17:04
thanks. so.  trace tool is not support cgo ?

**Comment by AlexRouSg** [comment] 2020-09-09 19:42
@tiny1990 It is not cgo, it's calling go code from threads not created by go. 
See the code in https://github.com/golang/go/issues/29707#issuecomment-489290457

**Comment by andybons** [comment] 2020-09-10 14:42
Duplicate of #29707

Feel free to comment or open a new issue if this is not the case.

**Closed by andybons** 2020-09-10 14:42 UTC
