### ISSUE TITLE
go/modules: how to import packages used by generators

### ISSUE THREAD

**Issue by aanm** [golang/go#27272] opened 2018-08-27 12:54 UTC
I couldn't find it elsewhere, is there an option in go modules similar to https://golang.github.io/dep/docs/Gopkg.toml.html#required?

**Comment by agnivade** [comment] 2018-08-27 15:02
Hi @aanm ,

This appears to be a question rather than a Go bug. We do not use the issue tracker for general discussions or questions like these. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

For further questions, please have a look at [Questions](https://github.com/golang/go/wiki/Questions) wiki page; it has a list of good places for asking questions.

Closing since this is not a bug.

**Closed by agnivade** 2018-08-27 15:02 UTC
