### ISSUE TITLE
x/tools/internal/lsp/regtest: "context deadline exceeded" in TestDiagnosticErrorInNewFile/forwarded

### ISSUE THREAD

**Issue by bcmills** [golang/go#38217] opened 2020-04-02 14:16 UTC
https://build.golang.org/log/5e788def16a08add4c80a64d8f88db4c604a655e

```
--- FAIL: TestDiagnosticErrorInNewFile (64.09s)
    --- FAIL: TestDiagnosticErrorInNewFile/forwarded (60.01s)
        diagnostics_test.go:64: waiting on [diagnostic in "broken.go" at {line:2, column:12} (location of "\"abc")]:
            err:context deadline exceeded
            diagnostics:
panic: Shutdown: context deadline exceeded [recovered]
	panic: Shutdown: context deadline exceeded

goroutine 9423 [running]:
testing.tRunner.func1.1(0xe748e0, 0xc00225b3c0)
	/tmp/workdir/go/src/testing/testing.go:941 +0x421
testing.tRunner.func1(0xc000fa66c0)
	/tmp/workdir/go/src/testing/testing.go:944 +0x600
panic(0xe748e0, 0xc00225b3c0)
	/tmp/workdir/go/src/runtime/panic.go:975 +0x3c2
golang.org/x/tools/internal/lsp/regtest.(*Runner).RunInMode.func1.1(0xc000fca7e0, 0x10e3100, 0xc000fca300)
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/regtest/env.go:182 +0xc1
runtime.Goexit()
	/tmp/workdir/go/src/runtime/panic.go:636 +0x104
testing.(*common).FailNow(0xc000fa66c0)
	/tmp/workdir/go/src/testing/testing.go:658 +0x5b
testing.(*common).Fatalf(0xc000fa66c0, 0xf929c2, 0x27, 0xc0038e5ba0, 0x3, 0x3)
	/tmp/workdir/go/src/testing/testing.go:725 +0x9e
golang.org/x/tools/internal/lsp/regtest.(*Env).Await(0xc000fca7e0, 0xc001ad70c0, 0x1, 0x1)
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/regtest/env.go:392 +0x6f2
golang.org/x/tools/internal/lsp/regtest.TestDiagnosticErrorInNewFile.func1(0xc000fca7e0)
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/regtest/diagnostics_test.go:64 +0x136
golang.org/x/tools/internal/lsp/regtest.(*Runner).RunInMode.func1(0xc000fa66c0)
	/tmp/workdir/gopath/src/golang.org/x/tools/internal/lsp/regtest/env.go:185 +0x398
testing.tRunner(0xc000fa66c0, 0xc002679950)
	/tmp/workdir/go/src/testing/testing.go:992 +0x1ec
created by testing.(*T).Run
	/tmp/workdir/go/src/testing/testing.go:1043 +0x661
FAIL	golang.org/x/tools/internal/lsp/regtest	118.918s
```

The failure mode looks similar to #37318 (CC @stamblerre @findleyr).

**Comment by findleyr** [comment] 2020-04-16 18:51
This might not be the same as #37318, so I'm leaving it open until I can confirm.

As with that bug, fixing this may be a slow process of elimination and adding additional instrumentation, until we find the root cause(s).  This process is currently ongoing.

The frequency of flakes is, in my opinion, not high enough yet to warrant disabling tests, given that these tests guard against specific regressions we'd like to avoid in the future.

**Comment by findleyr** [comment] 2020-06-18 19:43
I think I've categorized known flakes in #37318. Closing this to consolidate effort there.

**Closed by findleyr** 2020-06-18 19:43 UTC
Labels: NeedsInvestigation, Tools, gopls
