### ISSUE TITLE
x/pkgsite: move source links to GitHub

### ISSUE THREAD

**Issue by 1268** [golang/go#61617] opened 2023-07-27 18:04 UTC
this was previously discussed, but not in the scope of raw links.

### What is the URL of the page with the issue?

https://pkg.go.dev/fmt#Println

### What did you do?

I followed the link above to the linked source:

https://cs.opensource.google/go/go/+/go1.20.6:src/fmt/print.go

### What did you expect to see?

if I visit the same file on GitHub:

https://github.com/golang/go/blob/go1.20.6/src/fmt/print.go

a Raw link is available:

https://raw.githubusercontent.com/golang/go/go1.20.6/src/fmt/print.go

### What did you see instead?

I do not see any any such Raw link on `cs.opensource.google`.

**Comment by seankhliao** [comment] 2023-07-27 18:10
Duplicate of #44829

**Closed by seankhliao** 2023-07-27 18:10 UTC
Labels: pkgsite

**Comment by 1268** [comment] 2023-07-27 18:21
that was two years ago, and has no discussion of raw links.

thanks again for your valuable work on the issue tracker.
