### ISSUE TITLE
cmd/go: go tool needs to supply tls client cert when server requires mutual auth

### ISSUE THREAD

**Issue by tredeske** [golang/go#39261] opened 2020-05-26 21:03 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

go1.14.2 linux/amd64

</pre>

### Does this issue reproduce with the latest release?

Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

On a disconnected network, so cannot get all of these values.  But:

GOPROXY='direct'

</pre></details>

### What did you do?

With a go.mod file:

<pre>
module main

go 1.14

require gopkg.in/yaml.v2 v2.2.2

replace gopkg.in/yaml.v2 => private-git-server/go-yaml/yaml v2.0.0
</pre>

Then attempt to build: go build main.go

Results in this error:

<pre>
unrecognized import path "private-git-server/go-yaml/yaml": reading https://private-git-server/go-yaml/yaml?go-get=1: 400 Bad Request
</pre>

Using curl shows that a client tls cert is required by private-git-server, and not providing it results in the 400.

Attempted to mod .gitconfig to force use of ssh, but this http check is not governed by the git configuration.

There does not appear to be a way to supply a client tls cert to the go tool.

Using git, it is possible to clone the module to a local dir, then modify the go.mod to do a local replace instead:

<pre>
replace gopkg.in/yaml.v2 => ./yaml
</pre>

This works, but is not desirable.

### What did you expect to see?

Expected to have module pulled from the server.

### What did you see instead?

unrecognized import path "private-git-server/go-yaml/yaml": reading https://private-git-server/go-yaml/yaml?go-get=1: 400 Bad Request

**Comment by andybons** [comment] 2020-05-27 17:29
@bcmills @jayconrod @matloob

**Comment by bcmills** [comment] 2020-08-31 18:31
Duplicate of #30119

**Closed by bcmills** 2020-08-31 18:31 UTC
Labels: GoCommand, NeedsInvestigation
