### ISSUE TITLE
affected/package: go mod download

### ISSUE THREAD

**Issue by life-** [golang/go#53066] opened 2022-05-25 09:32 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.18 linux/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
</pre></details>
![image](https://user-images.githubusercontent.com/8157660/170227159-9ec60302-abbd-46b4-8117-9d6366bff8c7.png)
### What did you do?

```bash
mkdir -p $GOPATH/src/github.com/life-/gotest
cd $GOPATH/src/github.com/life-/gotest

go mod init
cat >> go.mod << EOF
require github.com/A/B/C v1.0.0
require github.com/A/D v1.1.0
EOF
```
When I use rsa private key for accessing this github.com/A repository.
**go mod download** works for github.com/A/D but does not work for github.com/A/B/C 

I got an error like this:
```text
go: github.com/A/B/C@v1.0.0: reading github.com/A/B/C/go.mod at revision C/v1.0.0: git ls-remote -q origin in /home/admin/go/pkg/mod/cache/vcs/09c7cba93e6a8142b59db141c9d98c817730d10a9fe5a873a6964a9c18ba51ad: exit status 128:
        remote: 
        remote: ========================================================================
        remote: 
        remote: The project you were looking for could not be found or you don't have permission to view it.
        remote: 
        remote: ========================================================================
        remote: 
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
```
Then I go to **/home/admin/go/pkg/mod/cache/vcs** directory,  
```bash
$ cd /home/admin/go/pkg/mod/cache/vcs
$ cat 09c7cba93e6a8142b59db141c9d98c817730d10a9fe5a873a6964a9c18ba51ad.info
github.com/A/B.git.   
```
github.com/A/B.git is a wrong repository, which is github.com/A/B/C.git

---
Then I remove ~/.ssh/id_rsa file, use .netrc file which contains deploy token. Everything works.  
The content of this file **/home/admin/go/pkg/mod/cache/vcs/*****.info**  is right, which is github.com/A/B/C.git

### What did you expect to see?
go mod download works for rsa privatekey

**Comment by seankhliao** [comment] 2022-05-25 09:42
how did you get a repository on github.com at A/B/C.git ?

**Comment by seankhliao** [comment] 2022-05-25 09:43
is D public?

**Comment by life-** [comment] 2022-05-25 09:49
Every repository is private. I use the private rsa key to get this repository. 

I set this in the global gitconfig file:
```text
[url "ssh://git@github.com/"]          
    insteadOf = https://github.com/
```

**Comment by mengzhuo** [comment] 2022-05-25 09:50
This is WIP

"github.com/" is a special prefix that only fetch repo instead of sub-diretory.

**Comment by life-** [comment] 2022-05-25 09:51
github.com is an example.  The real repository is a private gitlab repository. @mengzhuo

**Comment by seankhliao** [comment] 2022-05-25 10:09
We would appreciate accurate information in bug reports.
gitlab requires you to pass in http credentials (.netrc) to identify nested repositories (the https ?go-get=1 requests go issues)

Closing as working as intended

**Closed by seankhliao** 2022-05-25 10:09 UTC
