### ISSUE TITLE
encoding/json: Marshaler interface not producing "correct"/desired results

### ISSUE THREAD

**Issue by pjebs** [golang/go#24466] opened 2018-03-20 23:35 UTC
```

type AWorker struct {
	ID        string  `json:"id"`
	Name      *string `json:"name"`
	AvatarURL *string `json:"avatar_url"`
}

type ReqUser struct {
	ExpireAt *time.Time `json:"expire_at"`
	Status   string     `json:"status"`
	Notes    *string    `json:"notes"`
}

func (r ReqUser) MarshalJSON() ([]byte, error) {
	out := map[string]interface{}{}
	out["status"] = r.Status
	out["notes"] = r.Notes
	if r.ExpireAt != nil {
		out["expire_at"] = (*r.ExpireAt).Format("2006-01-02")
	}
	return json.Marshal(out)
}

type AUser struct {
	AWorker
	ReqUser
}

```

**Comment by pjebs** [comment] 2018-03-20 23:39
I want to `json/Marshall` a `[]AUser`.

When I remove `func (r ReqUser) MarshalJSON()`:

```
"users": [
    {
      "id": "PJ_WORKER1",
      "name": "PJ 1",
      "avatar_url": null,
      "expire_at": null,
      "status": "completed",
      "notes": null
    },
    {
      "id": "PJ_WORKER2",
      "name": "PJ 2",
      "avatar_url": null,
      "expire_at": "2020-12-31T00:00:00Z",
      "status": "incomplete",
      "notes": null
    },
    {
      "id": "PJ_WORKER3",
      "name": "PJ 3",
      "avatar_url": null,
      "expire_at": "2018-12-31T00:00:00Z",
      "status": "completed",
      "notes": "id looks fake"
    }
  ]
```

**Comment by pjebs** [comment] 2018-03-20 23:40
When I keep `func (r ReqUser) MarshalJSON()`:

```
"users": [
    {
      "expire_at": null,
      "notes": null,
      "status": "completed"
    },
    {
      "expire_at": "2020-12-31",
      "notes": null,
      "status": "incomplete"
    },
    {
      "expire_at": "2018-12-31",
      "notes": "id looks fake",
      "status": "completed"
    }
  ]
```

**Comment by pjebs** [comment] 2018-03-20 23:41
if this is **technically** correct behaviour, then perhaps for `Go2`, it should be changed to produce "desired" results.

**Comment by shurcooL** [comment] 2018-03-20 23:54
What are the desired or expected results?

**Comment by pjebs** [comment] 2018-03-21 00:44
`AUser` has 2 structs embedded. It should display json fields from `AWorker` and `ReqUser`, but for `ReqUser` it should produce the results from the `MarshalJSON()` function (i.e. the corrected date format)

**Comment by shurcooL** [comment] 2018-03-21 03:05
I see. Here's a runnable version on the playground: https://play.golang.org/p/FUBH0ZlswaL.

What's happening is `ReqUser` struct is being embedded into `AUser`, and as a result, `AUser` implements the `json.Marshaler` interface via `ReqUser.MarshalJSON` method. That way, all the `AWorker` fields get left out when `AUser` gets JSON marshaled.

It's working correctly given the rules of struct field embedding and `json.Marshaler` interface, but I can see how the two features are not interacting in an orthogonal and helpful way. I'm not sure how this can be improved.

**Comment by dsnet** [comment] 2018-03-21 05:29
Given a struct type `T` with an embedded type `R`, it is impossible to determine whether `T.Method` is actually explicitly defined on `T` or is forwarded from `R`. The forwarding of methods in addition to fields is not really a gotcha of the `json` package but embedding in general.

If your intention to to forward only the fields, but not the methods, you can do this:
```go
type aWorker AWorker
type reqUser ReqUser

type AUser struct {
	aWorker
	reqUser
}
```
Declaring `aWorker` and `reqUser` creates two new struct types that have the exact same layout as `AWorker` and `ReqUser`, but none of the methods.

I'm closing this as a duplicate of #22013.

**Closed by dsnet** 2018-03-21 05:29 UTC

**Comment by pjebs** [comment] 2018-03-21 05:40
@dsnet I require the methods to be attached, because `encoding/json` requires the custom `MarshalJSON()` function so I can modify the marshalled output.

**Comment by dsnet** [comment] 2018-03-21 05:44
What you want is currently not possible since you want to forward the fields of AWorker, but don't want to forward the methods. At the same time you don't want to remove the methods.

Either way, this is still a language issue with embedding and #22013 is the place to rethink embedding for Go2.

**Comment by dsnet** [comment] 2018-03-21 05:46
I should also note that this is related to #6213, which may be the reason why you are embedding in the first place.
