### ISSUE TITLE
go test with timeout doesn't print T.Error() messages

### ISSUE THREAD

**Issue by martin-juhlin** [golang/go#32757] opened 2019-06-24 21:21 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.5 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Probably

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/martin/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/martin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r2/nz7__kld2qq9w4dhg19fmx5h0000gn/T/go-build865892537=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Short version: Execute below program with: **go test -timeout 1s**
or with: **go test -v -timeout 1s**

I wrote a test case that got stuck somewhere and used the timeout command line feature to break it. The code is invoking T.Error during execution that contains information that is very helpful for debug what is wrong.

<pre>
package main

import (
	"testing"
	"time"
)

func TestThatDoesntWork(t *testing.T) {
	t.Error("an very important message that will help with debugging")
	time.Sleep(10 * time.Second)
}
</pre>

### What did you expect to see?
The message _"an very important message that will help with debugging"_ somewhere in the output.

### What did you see instead?
Just panic output from timeout.

<details><summary>Output:</summary><br>

```
$ go test -timeout 1s -v
=== RUN   TestThatDoesntWork
panic: test timed out after 1s

goroutine 35 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1334 +0xdf
created by time.goFunc
	/usr/local/go/src/time/sleep.go:169 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000c0100, 0x113b2da, 0x12, 0x1141ab8, 0x1069b76)
	/usr/local/go/src/testing/testing.go:917 +0x381
testing.runTests.func1(0xc0000c0000)
	/usr/local/go/src/testing/testing.go:1157 +0x78
testing.tRunner(0xc0000c0000, 0xc0000a9e30)
	/usr/local/go/src/testing/testing.go:865 +0xc0
testing.runTests(0xc00008c020, 0x122a290, 0x1, 0x1, 0x0)
	/usr/local/go/src/testing/testing.go:1155 +0x2a9
testing.(*M).Run(0xc0000b4000, 0x0)
	/usr/local/go/src/testing/testing.go:1072 +0x162
main.main()
	_testmain.go:42 +0x13e

goroutine 34 [sleep]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:307
time.Sleep(0x2540be400)
	/usr/local/go/src/runtime/time.go:105 +0x159
cronservice/tmp/testcase.TestThatDoesntWork(0xc0000c0100)
	/Users/martin/go/src/cronservice/tmp/testcase/foo_test.go:10 +0x7c
testing.tRunner(0xc0000c0100, 0x1141ab8)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a
exit status 2
FAIL	cronservice/tmp/testcase	1.012s
```

</details>

**Comment by agnivade** [comment] 2019-06-25 03:55
Yes, this is known. I am going to mark it as a duplicate of https://github.com/golang/go/issues/24929, which aims to fix this problem. Feel free to subscribe to that.

**Closed by agnivade** 2019-06-25 03:55 UTC
