### ISSUE TITLE
tour.golang.org : unreadable source code on phone

### ISSUE THREAD

**Issue by Konstantin8105** [golang/go#31134] opened 2019-03-29 09:44 UTC
### What did you do?

Open web page https://tour.golang.org/flowcontrol/8 on phone

![godoc](https://user-images.githubusercontent.com/16690032/55223821-1c601200-5220-11e9-98f6-9209ac9f626a.PNG)

### What did you expect to see?

readable source code.

**Comment by ALTree** [comment] 2019-03-29 11:12
Thanks for the report. 

This is golang/tour#295, reported in the tour issue tracker, so I'm closing this issue as a duplicate of that one.

**Closed by ALTree** 2019-03-29 11:12 UTC
