### ISSUE TITLE
x/tools/gopls: move signature on top of quick documention on hover

### ISSUE THREAD

**Issue by inliquid** [golang/go#33550] opened 2019-08-08 18:31 UTC
As a result of #32561 `gopls` now has additional config parameter, which allows to return full docs on hover. However atm this makes it less useful as every time documentation provided has some decent amount of text, it's only possible to see the signature after scrolling to the very bottom.
![изображение](https://user-images.githubusercontent.com/6797881/62728193-ce57e800-ba23-11e9-968a-2b5345c44124.png)

Please move signature above the documentation, as it was done previously in sourcegraph's language server, `bingo`, and as it's in the default `vscode-go` config with `godoc` or `gogetdoc`.

**Comment by stamblerre** [comment] 2019-08-08 20:50
I've just come to the realization that this is effectively a duplicate of https://github.com/golang/go/issues/33352. I think this needs a little more thought than my quick CL indicates. Both orderings are potentially valuable, and this issue has led me think that offering configurations might be a viable approach here. I will close this issue in favor of https://github.com/golang/go/issues/33352.

**Closed by stamblerre** 2019-08-08 20:50 UTC
Labels: Documentation, gopls

**Comment by inliquid** [comment] 2019-08-09 00:23
Sorry I don't understand, why don't just make it in same way, as it was done in all other versions listed above, (btw, including `Goland` quick documentation feature), signature at the top and the rest is scrollable documentation text?
For example here is how it looks like in VS Code when turning off `gopls` and with simple `godoc`:
![изображение](https://user-images.githubusercontent.com/6797881/62745638-a7fe7080-ba54-11e9-9d5a-d56955b55df8.png)
