### ISSUE TITLE
about using 'go mod graph'

### ISSUE THREAD

**Issue by zhanghe9702** [golang/go#47262] opened 2021-07-17 09:25 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
 devel go1.17-84c0e5d47f Wed Jun 2 00:36:24 2021 +0000 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/scrapy/.cache/go-build"
GOENV="/home/scrapy/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/scrapy/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/scrapy/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/home/scrapy/goroot"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/home/scrapy/goroot/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="devel go1.17-84c0e5d47f Wed Jun 2 00:36:24 2021 +0000"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/scrapy/go/src/istio/istio/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3500985597=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you expect to see?

add one cmd option, so we can see only top dependent module or direct dependent module? 

### What did you see instead?
current 'go mod graph'  isn't easy to lookup useful module dependency info.

**Comment by ALTree** [comment] 2021-07-17 11:17
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2021-07-17 11:17 UTC
