### ISSUE TITLE
x/website blog linking to other blog post with wrong path

### ISSUE THREAD

**Issue by maxstanley** [golang/go#47875] opened 2021-08-21 19:52 UTC
### What version of Go are you using (`go version`)?

n/a

### Does this issue reproduce with the latest release?

n/a

### What operating system and processor architecture are you using (`go env`)?

n/a

### What did you do?

Followed the " Pipelines and Cancelation" link on `https://go.dev/blog/context`

### What did you expect to see?

`https://go.dev/blog/pipelines` Go Concurrency Patterns: Pipelines and cancellation

### What did you see instead?

`https://go.dev/pipelines` stat go.dev/_content/pipelines: no such file or directory

### Fixing the issue

https://cs.opensource.google/go/x/website/+/master:go.dev/_content/blog/context.md;l=47?q=channel%20idiom%20in%20more%20detail.&ss=go%2Fx%2Fwebsite

Change this incorrect link `[Pipelines and Cancelation](/pipelines)` to `[Pipelines and Cancelation](/blog/pipelines)`

**Comment by seankhliao** [comment] 2021-08-21 19:54
Duplicate of #47861

**Closed by seankhliao** 2021-08-21 19:54 UTC
