### ISSUE TITLE
syscall/js: allow deletion of an object property

### ISSUE THREAD

**Issue by advanderveer** [golang/go#35227] opened 2019-10-29 07:57 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.13.3 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/adam/Library/Caches/go-build"
GOENV="/Users/adam/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/adam/Projects/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/adam/Projects/go/src/github.com/advanderveer/9d587b277/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8g/sd7s1zr94f948ds6_q0v3q180000gn/T/go-build209901922=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
I want to delete an js object property

### What did you expect to see?
```
js.Global().Del("foo")
```

### What did you see instead?
As far as i can tell there is no way to delete a property from a JS object, i tried setting it to nil or undefined but the key is still present:

```
js.Global().Set("__c", "foo")
js.Global().Set("__c", nil)
js.Global().Set("__c", js.Undefined())
println(js.Global().Call("hasOwnProperty", "__c").Bool()) //will be true
```

**Comment by tmthrgd** [comment] 2019-10-29 11:11
This is a duplicate of #33079 and is included at tip (go1.14): https://tip.golang.org/pkg/syscall/js/#Value.Delete.

**Comment by agnivade** [comment] 2019-10-29 17:01
Thanks @tmthrgd. Closing since it's already fixed.

**Closed by agnivade** 2019-10-29 17:01 UTC
