### ISSUE TITLE
cmd/link: undefined symbol when dynamically linking linux/arm64 -buildmode=shared

### ISSUE THREAD

**Issue by lennonchan** [golang/go#70222] opened 2024-11-06 13:01 UTC
### Go version

go1.22.1 linux/arm64

### Output of `go env` in your module/workspace:

```shell
GO111MODULE='off'
GOARCH='arm64'
GOBIN=''
GOCACHE='/usr1/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/opt/go_workpace/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/opt/go_workpace'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/root/go/'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/root/go/pkg/tool/linux_arm64'
GOVCS=''
GOVERSION='go1.22.1'
GCCGO='gccgo'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD=''
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3307636971=/tmp/go-build -gno-record-gcc-switches'
```

### What did you do?

```
package main

import "fmt"

func main() {
    fmt.Println("Hello, World!")
}

```
I'm trying to use the Golang/go linkshared feature on Linux/ARM64, Here is my command to run：
```
go version
go install -a -buildmode=shared -linkshared std
go build -a -linkshared -o main_shared main.go
./main_shared
```

### What did you see happen?

`./main_shared: symbol lookup error: /root/go/pkg/linux_arm64_dynlink/libstd.so: undefined symbol: __aarch64_ldadd8_acq_rel`

### What did you expect to see?

Output the expected string `Hello, World!`

**Comment by lennonchan** [comment] 2024-11-07 01:40
@ianlancetaylor thanks for your reply. I used this command `gcc --version`, it seems the GCC version is 7.3.0, and here is the output: 
```
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ianlancetaylor** [comment] 2024-11-07 04:35
That is rather old.  I don't know what the problem is, and I don't know whether this would help, but how difficult would it be for you to try a newer version of GCC?  The current release is GCC 14.2.

**Comment by ianlancetaylor** [comment] 2024-11-07 19:43
Sorry, it's not really feasible for us to maintain old versions of GCC to use to build those syso files.

That said, we should probably try to document which version we used.

In any case, this bug seems fixed, so closing.  Thanks for following up.

**Comment by ianlancetaylor** [comment] 2024-11-07 19:44
Oh, actually, we do document what we built the syso files with, in runtime/race/README.

**Closed by ianlancetaylor** 2024-11-07 19:43 UTC
Labels: WaitingForInfo, compiler/runtime

**Comment by randall77** [comment] 2024-11-07 20:03
> Oh, actually, we do document what we built the syso files with, in runtime/race/README.

We document the version of llvm that we get the race detector code from. But that's not the *compiler* that was used to build it. I don't think we record that anywhere.

**Comment by ianlancetaylor** [comment] 2024-11-07 23:14
Oh, bother.  Thanks.
