### ISSUE TITLE
x/pkgsite: border around examples after click

### ISSUE THREAD

**Issue by prattmic** [golang/go#43053] opened 2020-12-07 17:23 UTC
### What is the URL of the page with the issue?
 
https://pkg.go.dev/strings#TrimLeft (any page with examples)
 
### What is your user agent?
 

Mozilla/5.0 (X11; CrOS x86_64 13421.102.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.199 Safari/537.36
 
### Screenshot
 

 
 ![Screenshot 2020-12-07 at 12 20 30](https://user-images.githubusercontent.com/1293187/101383005-9c100200-3886-11eb-95d6-4481fb89af5f.png)
 
### What did you do?
 

 
1. Click "Example" to expand the example.
2. Click anywhere in the expanded view (the word "Code:", in the code/output box, or even the whitespace above the code box.)
 
### What did you expect to see?
 
Click (2) does nothing.
 
### What did you see instead?

Click (2) adds a black border around the example. Perhaps this is intentional? But it seems superfluous to me.

**Comment by prattmic** [comment] 2020-12-07 17:29
Ooo, this one is fun: https://pkg.go.dev/golang.org/x/net/ipv4#example-PacketConn-ServingOneShotMulticastDNS. The border around this example extends up through some of the text above the example:

![Screenshot 2020-12-07 at 12 29 43](https://user-images.githubusercontent.com/1293187/101384026-e47bef80-3887-11eb-9d76-9d55ab9ebda4.png)

**Comment by jamalc** [comment] 2020-12-07 19:02
Related to #42698

**Comment by julieqiu** [comment] 2020-12-21 20:38
Closing as a dupe of #42698.

**Closed by julieqiu** 2020-12-21 20:38 UTC
Labels: NeedsInvestigation, pkgsite
