### ISSUE TITLE
go mod vendor does not copy *.proto files to vendor directory

### ISSUE THREAD

**Issue by byungjoon72** [golang/go#39083] opened 2020-05-14 23:25 UTC
### What version of Go are you using (`go version`)?

1.12

### Does this issue reproduce with the latest release?

NA

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bjlee72/Library/Caches/go-build"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bjlee72/go:/Users/bjlee72/marvel2/go:/Users/bjlee72/marvel2/go/vendor"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/bjlee72/go/src/github.com/moloco/morse/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/q_/43p5tl0x18dcd7gjlx8s75km0000gn/T/go-build970157154=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What did you expect to see?

I wanted to see proto files copied under the vendor directory because I have to import the files in my *.profo files.

### What did you see instead?

No directory that have the proto files are copied.

**Comment by bcmills** [comment] 2020-05-15 15:25
See https://github.com/golang/go/issues/26366#issuecomment-405683150.

**Comment by bcmills** [comment] 2020-05-15 15:25
Duplicate of #26366

**Closed by bcmills** 2020-05-15 15:25 UTC
