### ISSUE TITLE
proxy.golang.org: License cannot be detected for github.com/vesoft-inc/nebula-go/v2

### ISSUE THREAD

**Issue by Aiee** [golang/go#47830] opened 2021-08-20 03:15 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.7 linux/amd64
</pre>

### What did you do?
visit https://pkg.go.dev/github.com/vesoft-inc/nebula-go/v2

When I first released the v2.5.0, I didn't put the LICENSE file in the root of the directory, and I ran `go get -u -v github.com/vesoft-inc/nebula-go/v2@v2.5.0` in another project to fetch the module, so a mirror was generated in the proxy.golang.org. When I realized the license was not detected(I didn't put the LICENSE file in the root of directory), I deleted the v2.5.0 release in github, added the license to the root, and re-released another v2.5.0 tag with the same tag name. When I check https://pkg.go.dev/github.com/vesoft-inc/nebula-go/v2, it still shows no license detected, and it is the old mirror being fetched when I run `go get -u -v github.com/vesoft-inc/nebula-go/v2@v2.5.0`.

### What did you expect to see?
Docs, License detected

### What did you see instead?
![Screen Shot 2021-08-20 at 11 07 53 AM](https://user-images.githubusercontent.com/18348405/130173055-e16361b6-90cc-4555-8614-e700f86c9e91.png)

**Comment by seankhliao** [comment] 2021-08-20 06:43
Once seen by the proxy, tags cannot be moved

Closing as working as intended

**Closed by seankhliao** 2021-08-20 06:43 UTC
