### ISSUE TITLE
x/tools/cmd/godoc: support exporting HTML documentation

### ISSUE THREAD

**Issue by akoserwal** [golang/go#39272] opened 2020-05-27 12:51 UTC
Is there a way to generate a godoc for a module/package or export the generated documentation in a static file format? 

Currently way of generating docs:
`godoc -http=:PORT` 

Can we add an export button mechanism to the page? That can export the document for the entire project.

**Comment by andybons** [comment] 2020-05-27 17:16
What is your use-case for this feature? Thanks.

**Comment by akoserwal** [comment] 2020-05-27 17:44
I am looking suitable way of generating go documents for Kubernetes Operators generated using operator-sdk or add go docs to a library as static formate.

**Comment by andybons** [comment] 2020-05-27 18:22
If you’re proposing adding a button (which seems to indicate that you’re not looking to automate it?), why not use the browser’s “Save page as” feature that will output static documentation for you?

**Comment by akoserwal** [comment] 2020-05-28 05:32
I am looking for an automated way. Something
` godoc project/module/file` with the export flag for providing file format. Similar `javadoc file_name or javadoc package_name` or a button on the main page of module/project which allows exporting the entire project pages.

**Comment by agnivade** [comment] 2020-05-28 09:46
Duplicate of https://github.com/golang/go/issues/2381.

**Closed** 2020-05-28 11:14 UTC
Labels: Documentation, Tools, WaitingForInfo
