### ISSUE TITLE
net/http: *Request.URL.Scheme returns an empty string.

### ISSUE THREAD

**Issue by li-jin-gou** [golang/go#57533] opened 2022-12-31 07:06 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

```go
package main

import (
	"github.com/gin-gonic/gin"
)

func main() {
	g := gin.Default()
	g.GET("/ping", func(c *gin.Context) {
		// Request   *http.Request
                // c.Request.URL.Scheme return an empty string instead of http.
		c.String(200, "Hello %s", c.Request.URL.Scheme)
	})
	g.Run(":8080")
}
```

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

I was using gin and found that http.Request.URL.Scheme was equal to "". Is this a normal behaviour? 

I see this issue https://github.com/golang/go/issues/28940 mentions a similar problem, and I'd like to make sure that the return of an empty string is the same for all go versions? And are there any plans to change it in Go2 in the future?

### What did you expect to see?
Many people think that Schema will return the Http/https 's schema but it is empty, is there any other way to replace it?

Best wish💕

**Comment by seankhliao** [comment] 2022-12-31 08:22
Duplicate of #28940

**Closed by seankhliao** 2022-12-31 08:22 UTC
