### ISSUE TITLE
x/image/font/opentype: Face isn't compliant with font.Face 

### ISSUE THREAD

**Issue by ShadiestGoat** [golang/go#58252] opened 2023-02-02 17:52 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/shady/.cache/go-build"
GOENV="/home/shady/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/shady/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/shady/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build457832407=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I created a new face from opentype. Then, I called Glyph() on a non existing character.

### What did you expect to see?

I expected it to return !ok, as stated in the `font.Face` documentation.

### What did you see instead?

It returns ok.

**Comment by mknyszek** [comment] 2023-02-02 17:58
I don't see an owner listed on https://dev.golang.org/owners, but most of the code seems to have been written by @nigeltao.

**Comment by ShadiestGoat** [comment] 2023-02-02 18:02
Hi! I proposed a small change [here](https://github.com/golang/image/pull/13) that should fix this issue.

**Comment by nigeltao** [comment] 2023-02-04 06:33
I'm tempted to close this as Working As Intended.

Glyph index 0 is a valid index, and by convention it's the `.notdef` glyph used for missing characters. See:

- https://learn.microsoft.com/en-us/typography/opentype/otspec170/recom#shape-of-notdef-glyph
- https://www.high-logic.com/fontcreator/manual11/recommendedglyphs.html

Calling `opentype.Face.Glyph` with a rune that isn't covered by the font face should therefore arguably return `ok == true` and this `.notdef` glyph (typically an empty rectangle). The Face _does_ contain a glyph for the rune argument. It just happens to be a fallback glyph.

There is a separate question of "if I have a string, what runes in it are covered by this Face (excluding `.notdef` glyphs)", but that is a much more complicated question, related to Harfbuzz-like layout and shaping and fontconfig-like font selection, and surely deserves separate API.

For example, [Han Unification](https://heistak.github.io/your-code-displays-japanese-wrong/) means that "does this Face have a non-zero glyph index for this rune" isn't sufficient to answer "is this the right font for this rune". At a minimum, this should probably involve some concept of the user's locale, but I don't think Go has a good cross-platform abstraction for this yet.

For example, Android's [minikin](https://android.googlesource.com/platform/frameworks/minikin/) library's author [said](https://raphlinus.github.io/text/2022/11/08/minikin.html) that:

> Much of the internal structure of Minikin is dedicated to itemization, which is done largely on the basis of the cmap coverage of the fonts in the fallback chain. Doing that query font-by-font for every character would be expensive, so there are fancy bitmap acceleration structures.

Again, font selection and coverage calculation is a bigger problem needing separate API.

**Comment by nigeltao** [comment] 2023-02-04 06:45
Consider the opentype [example_test.go](https://github.com/golang/image/blob/master/font/opentype/example_test.go) file, changing the "e" in the "jelly" string to a Unicode U+2603 Snowman, and running `go test`:

```diff
diff --git a/font/opentype/example_test.go b/font/opentype/example_test.go
index 4d7ee85..c8d522a 100644
--- a/font/opentype/example_test.go
+++ b/font/opentype/example_test.go
@@ -46,7 +46,7 @@ func ExampleNewFace() {
                Dot:  fixed.P(startingDotX, startingDotY),
        }
        fmt.Printf("The dot is at %v\n", d.Dot)
-       d.DrawString("jel")
+       d.DrawString("j\u2603l")
        fmt.Printf("The dot is at %v\n", d.Dot)
        d.Src = image.NewUniform(color.Gray{0x7F})
        d.DrawString("ly")
```

1. Without your patch, this draws something roughly like "j▯lly" with an empty rectangle.
2. With your patch, this draws "jlly" with nothing at all between the "j" and the "l".

I think (1) is the better output.

**Comment by ShadiestGoat** [comment] 2023-02-04 08:34
Hello! Thank you for your response. 
 
 > Glyph index 0 is a valid index, and by convention it's the .notdef glyph used for missing characters. See
 
 I agree! Glyph index 0 is a valid index, however, it implies that the glyph you are trying to draw isn't present. The fact that the .notdef is being returned should mean that ok == false, as stated in the font.Face documentation. 
 
 > It returns !ok if the face does not contain a glyph for r.
 
(Glyph, GlyphAdvance, GlyphBounds)

To me, this sounds like it must return an ok == false, and the .notdef glyph. After all, what is the point of the ok variable if not to determine that it is using a fallback glyph? The only other thing I see is for error handling, and to me, in an ideal world errors would mean itd draw the .notdef glyph. 

The benefit of this patch is that libraries like multiface could work properly. It would make users be able to use fallback glyphs without the need for called Index() ourselves.

> There is a separate question of "if I have a string, what runes in it are covered by this Face (excluding .notdef glyphs)", but that is a much more complicated question, related to Harfbuzz-like layout and shaping and fontconfig-like font selection, and surely deserves separate API.
> 
> For example, [Han Unification](https://heistak.github.io/your-code-displays-japanese-wrong/) means that "does this Face have a non-zero glyph index for this rune" isn't sufficient to answer "is this the right font for this rune". At a minimum, this should probably involve some concept of the user's locale, but I don't think Go has a good cross-platform abstraction for this yet.

There could be a separate structure and API for this, but I'm not sure to what extent that is relevant to the issue at hand.

I don't think this patch is significantly slower than before. It introduces 1-2 checks per function. The `index()` calls were already done before, it was just inline.

Regarding the `example_test.go`,  you are right. That test should output something like j▯lly. However, that sounds like an issue that should be fixed, rather than an issue that should be used to cancel this pr. I will look into how to fix this as soon as I can.

**Comment by ShadiestGoat** [comment] 2023-02-04 08:53
> Consider the opentype [example_test.go](https://github.com/golang/image/blob/master/font/opentype/example_test.go) file, changing the "e" in the "jelly" string to a Unicode U+2603 Snowman, and running `go test`:
> 
> ```diff
> diff --git a/font/opentype/example_test.go b/font/opentype/example_test.go
> index 4d7ee85..c8d522a 100644
> --- a/font/opentype/example_test.go
> +++ b/font/opentype/example_test.go
> @@ -46,7 +46,7 @@ func ExampleNewFace() {
>                 Dot:  fixed.P(startingDotX, startingDotY),
>         }
>         fmt.Printf("The dot is at %v\n", d.Dot)
> -       d.DrawString("jel")
> +       d.DrawString("j\u2603l")
>         fmt.Printf("The dot is at %v\n", d.Dot)
>         d.Src = image.NewUniform(color.Gray{0x7F})
>         d.DrawString("ly")
> ```
> 
>     1. Without your patch, this draws something roughly like "j▯lly" with an empty rectangle.
> 
>     2. With your patch, this draws "jlly" with nothing at all between the "j" and the "l".
> 
> 
> I think (1) is the better output.

This is an issue due to `image/font/font.go`,  `DrawString`,  `!ok` has a TODO and a continue. When the check is removed, it would still draw ▯. Its better not to do the check regardless, as for errors return a 0 advance, and .notdef values still return ▯.
I am however unsure of this. It sounds a bit out of scope, what do you think @nigeltao?

**Comment by ShadiestGoat** [comment] 2023-03-08 00:01
Hello, may I please get an update on this, @nigeltao?

**Closed** 2023-03-21 11:35 UTC
Labels: NeedsFix
