### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by MrSutra** [golang/go#63701] opened 2023-10-20 19:59 UTC
gopls version: v0.13.2 (go1.21.0)
gopls flags: -logfile /home/user/gopls.log -rpc.trace
update flags: off
extension version: 0.39.1-upstream-0.1.9-uber
go version: 1.21.3
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Fri, 20 Oct 2023 19:58:27 GMT
restart history:
Fri, 20 Oct 2023 17:50:42 GMT: activation (enabled: true)
Fri, 20 Oct 2023 19:57:05 GMT: manual (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Error while running `bazel run :e2e`on eatscouriercppplcpluscardunauthorized integration test.

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbe718b]

goroutine 1735 [running]:
golang.org/x/tools/gopls/internal/lsp/cache.localPackageKey({{0xc000dfc720, 0x26}, {0xc000d57425, 0xb}, {0xc000d57420, 0x5}, {0xc000b64b40, 0x2, 0x2}, {0xc000b64b60, ...}, ...})
	  check.go:1402  0x6eb
golang.org/x/tools/gopls/internal/lsp/cache.(*packageHandleBuilder).buildPackageHandle(0xc002c7d290, {0x1161940, 0xc0007d9540}, 0xc003839b80)
	  check.go:1090  0x2be
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).getPackageHandles.func2.1()
	  check.go:891  0xd7
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:75  0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1486
	  errgroup.go:72  0x96
[Error - 7:58:13 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by adonovan** [comment] 2023-10-23 22:20
duplicate of https://github.com/golang/go/issues/63701

**Closed** 2023-10-24 14:17 UTC
Labels: gopls, Tools

**Comment by findleyr** [comment] 2023-10-26 15:25
Hi, we just realized that you are probably using a GOPACKAGESDRIVER provided by Uber. Can you please confirm that this is the case? If so, we understand the breakage, and can fix it properly.

**Comment by adonovan** [comment] 2023-10-26 16:12
If that is indeed the cause, then it may also be a simple matter of updating your driver to avoid this issue. I assume you're using the Bazel driver, which was updated 2 months ago to set the necessary fields: https://github.com/bazelbuild/rules_go/commit/6e10f8c264e3577b0e2fb16cfd2d37cff05cdcfa

**Comment by findleyr** [comment] 2023-10-26 17:26
BTW, if folks at Uber are willing to share more about their custom environment, it might help us support it better (CC @kchristi111, who also encountered this issue while using extension version 0.39.1-upstream-0.1.9-uber). We'd be happy to connect.

**Comment by findleyr** [comment] 2023-10-26 21:23
This should be fixed in v0.14.1-pre.1 (on v0.14.0 there is a workspace error message instead of a panic).

```
go install golang.org/x/tools/gopls@v0.14.1-pre.1
```

Could anyone here please try that out to confirm? With your confirmation, we will release v0.14.1 tomorrow.

**Comment by JamyDev** [comment] 2023-12-19 03:21
Hey @findleyr, I'd love to share more about our setup. In this case we did just manually add the old sizes fields back with some bash-fu in our external driver. At the time of the change from Sizes to Arch/Compiler we were still stuck on 0.11.

**Comment by findleyr** [comment] 2023-12-19 14:29
Thanks, @JamyDev. Am I understanding correctly that you are now off of v0.11? Are you on v0.14.2?

**Comment by JamyDev** [comment] 2023-12-19 19:01
@findleyr we're in the process of upgrading.

**Comment by findleyr** [comment] 2023-12-19 19:21
@JamyDev I'd hope that you experience significantly decreased memory usage in recent versions. Please let us know if that's not the case, or any other issues you encounter.
