### ISSUE TITLE
net: Dialer.LocalAddr selecting wrong network-interface to send request via.

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [golang/go#57538] opened 2023-01-01 05:09 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.19.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/10008"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/10008/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/app/go/src/blaster/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2212035460=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

I have <b>wwan0</b> with src ip <b>100.99.192.214</b>:

<pre>
$ ip route show
default via 192.168.1.1 dev eno1 proto dhcp metric 100
default via 100.99.192.213 dev wwan0 proto static metric 700
100.99.192.212/30 dev wwan0 proto kernel scope link src <b>100.99.192.214</b> metric 700
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
192.168.1.0/24 dev eno1 proto kernel scope link src 192.168.1.211 metric 100
</pre>

When specifying this source ip as the LocalAddr in net.Dailer as this [https://go.dev/play/p/vRKTPQMnyHu](https://go.dev/play/p/vRKTPQMnyHu) still results in the request being made to eno1 interface and not wwan0 interface.

### What did you expect to see?
Using TCP dump I should see wwan0 for the request as such (via curl interface targeting `curl -v --interface wwan0 https://api.ipify.org`)
```05:03:00.131301 wwan0 Out IP 100.99.192.214.40804 > 173.231.16.76.443: Flags [S], seq 2925401696, win 65236, options [mss 1388,sackOK,TS val 251821070 ecr 0,nop,wscale 7], length 0```

### What did you see instead?
I see the request is routed to eno1 interface which src 100.99.192.214 is not associated with (see `ip route show` above:
```05:01:38.297518 eno1  Out IP 100.99.192.214.60759 > 173.231.16.76.443: Flags [S], seq 1998656637, win 64240, options [mss 1460,sackOK,TS val 251739236 ecr 0,nop,wscale 7], length 0```

Request times out as the src ip does not match the right interface.

**Comment by seankhliao** [comment] 2023-01-01 09:21
This is outside the control of Go. The program has bound to the correct source IP, it's then up to the kernel to route it, pointing to misconfiguration on your routing side.
Closing as not a bug in Go.

**Closed by seankhliao** 2023-01-01 09:21 UTC
