### ISSUE TITLE
Unused variables vs unused functions

### ISSUE THREAD

**Issue by huttarichard** [golang/go#26080] opened 2018-06-27 09:46 UTC
Just curious,

why compiler complains about unused variables but not about functions which are not exported?
If package has function which is not exported and function is not used anywhere (testing included) then it means this function is useless and therefore compiler should complain. Or am I wrong about this?

**Comment by ALTree** [comment] 2018-06-27 09:56
>  compiler complains about unused variables

Only inside function bodies. From the spec:

> A compiler may make it illegal to declare a variable inside a function body if the variable is never used. 

Unused variable and function declarations outside function bodies are both allowed. This compiles:

```
package p

var unusedV int = 42

func unusedF() int {
	return 42
}
```

So the compiler's behaviour is actually somewhat consistent. Unused vars inside a function are not allowed, while unused functions *inside a function* are not a problem because Go does not allow them (you can't nest `func` declarations).

That said, the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing, since this is not a bug.

**Closed by ALTree** 2018-06-27 09:56 UTC

**Comment by huttarichard** [comment] 2018-06-27 10:10
@ALTree thanks for reply. Since I started here, one follow up question. I can not wrap my head around why would non-exported unused variables outside of function body would not be treated same as those which are in function body. I was actually about to suggest this as improvement to linter.

**Comment by ALTree** [comment] 2018-06-28 08:30
@huttarichard I'm not sure why the Go designers choose to treat unused local variables differently from unexported unused package-level variables. I believe they may have been convinced that an unused function variable is more likely to be a programmer mistake than an unused package-level variable.

There's also another thing to consider: how annoying it may be to fix unused-variables errors when writing code. A function will always be contained in a single file, so if a code change causes a local variable to become unused you can always fix the error with a "local" modification (in the function you're working on).
Fixing unused package-level variable errors, OTOH, would be much more annoying because a package is often split into several files, so a file-local change that makes a package-level variable unused may force you to edit another, different file, where the variable is defined, to make the package compile.

Please direct any further question to the places I linked above. Closed issues are not actively monitored so when you comment on one it often happens that no-one even sees your message.
