### ISSUE TITLE
cmd/go: go mod gets dependency, which can not built, because needs newer go version

### ISSUE THREAD

**Issue by Ragnar-BY** [golang/go#46703] opened 2021-06-11 12:27 UTC
### What version of Go are you using (`go version`)?

<pre>
$go version go1.15.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
I don`t know

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY="git.dar.kz"
GONOSUMDB="git.dar.kz"
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE="git.dar.kz"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build726176060=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I have project which is built with go1.15 and use go modules
My project has labstack/echo as dependency
And after ```go mod tidy ```
 I have 
<details><summary><code></code> go.mod</summary><br><pre>
module myproject

go 1.15

require (
	...
	github.com/labstack/echo/v4 v4.3.0
	...
)

</pre></details>
But this version of labstack/echo is built with go1.16, and I get next error
<pre>
myproject imports
        github.com/labstack/echo/v4/middleware tested by
        github.com/labstack/echo/v4/middleware.test imports
        io/fs: package io/fs is not in GOROOT (/usr/local/go/src/io/fs)
myproject imports
        github.com/labstack/echo/v4/middleware tested by
        github.com/labstack/echo/v4/middleware.test imports
        testing/fstest: package testing/fstest is not in GOROOT (/usr/local/go/src/testing/fstest)

</pre>

### What did you expect to see?

I expect, that go mod will get version of modules, that can be built with same go version as mine

### What did you see instead?
I get module, that built with go1.16, but I need module for go1.15

I can fix it but changing go.mod file and downgrading version

**Comment by cherrymui** [comment] 2021-06-11 15:23
Does `github.com/labstack/echo/v4 v4.3.0` actually depends on Go 1.16? If so, I'm not sure there is anything we can do here.

cc @bcmills @jayconrod @matloob

**Comment by bcmills** [comment] 2021-06-11 15:57
@Ragnar-BY, upgrade to Go 1.15.10.

**Comment by bcmills** [comment] 2021-06-11 15:57
Duplicate of #44792

**Closed by bcmills** 2021-06-11 15:57 UTC
Labels: NeedsInvestigation
