### ISSUE TITLE
runtime: openbsd is spinning

### ISSUE THREAD

**Issue by bradfitz** [golang/go#11191] opened 2015-06-12 21:04 UTC
I keep finding finding openbsd builders (I think just 386?) spinning.

Mostly recently I found it spinning at 57f4b430 but it's been happening for a few weeks.

In particular, I think it's usually caused by one of the tests in the "test" directory. Shard 4/5 seems to trigger it:

```
$ go tool dist test --no-rebuild test:4_5
```

**Comment by rsc** [comment] 2015-07-21 00:36
Can you narrow it down?

Should we deprecate openbsd/386?

**Comment by bradfitz** [comment] 2015-07-21 00:38
I never investigated it more.

/cc @4a6f656c @mdempsky

**Comment by mdempsky** [comment] 2015-07-21 01:10
I suspect this was the same root cause as #11617.  When I was trying to repro that issue, I kept seeing cmd/link processes sporadically spin, but I haven't seen that happen again since cc8f544.

I'm optimistically closing, but please reopen (or file a new issue) if you see it happen again.

**Closed by mdempsky** 2015-07-21 01:10 UTC
