### ISSUE TITLE
socket operation on non-socket

### ISSUE THREAD

**Issue by wangzhipeng** [golang/go#32826] opened 2019-06-28 10:28 UTC
OS:ubuntu18.04

https://github.com/golang/go/blob/67f181bfd84dfd5942fe9a29d8a20c9ce5eb2fea/src/net/http/fcgi/child.go#L334

**Comment by av86743** [comment] 2019-06-28 10:33
https://github.com/golang/go/blob/67f181bfd84dfd5942fe9a29d8a20c9ce5eb2fea/src/net/http/fcgi/child.go#L329

**Comment by ianlancetaylor** [comment] 2019-06-28 13:37
I don't see a bug here, so closing.  If you still think there is a bug, please explain why.  Thanks.

**Closed by ianlancetaylor** 2019-06-28 13:37 UTC

**Comment by GwynethLlewelyn** [comment] 2020-06-06 14:45
I'm also using Ubuntu (albeit 16.04.6 LTS) and `nginx` — which, in turn, calls [fcgiwrap](https://www.nginx.com/resources/wiki/start/topics/examples/fcgiwrap/) via a Unix socket, [as in this classic example](http://www.dav-muz.net/blog/2013/09/how-to-use-go-and-fastcgi/). The wrapper is what actually calls the Go application. By default, it is supposed to `Serve` using `os.Stdin`, but, somehow, this fails. I've tried to bind `Serve` to other things, all of which will crash the application...

Note that the same code works well under Apache, and at least `perl` and `bash` scripts (I didn't test anything else) are correctly served from the `nginx` + `fcgiwrap` combination without a glitch.

What seems to be happening is that `os.Stdin`, _in this particular type of configuration_, is apparently 'not available' for some unknown reason (at least, unknown to me).

**Comment by davecheney** [comment] 2020-06-06 14:55
This issue was closed last year. To make sure your issue is triaged, can you please open a fresh issue, fill out the template, and include a runnable sample program that can be used to reproduce the problem you are having. 

Thank you.
