### ISSUE TITLE
cmd/compile: windows 386 compile crashes

### ISSUE THREAD

**Issue by brydavis** [golang/go#16674] opened 2016-08-11 16:51 UTC
1. What version of Go are you using (`go version`)? __1.6.3 x386__ (although no issue for older versions like 1.3.3 x386; no issues for 64-bit version of 1.6.3).  Unfortunately, circumstances require that I use 32-bit in order to connect to legacy database...
2. What operating system and processor architecture are you using (`go env`)?
    Windows 64, however I have to use x386 version of Go due to legacy database that is 32-bit

3. What did you do?
Tried to compile a simple program (like "hello world" simple).  Since I don't have admin rights on this machine, had to download / use binary Go compiler.  So, I have to build with a command like `c:\go\bin\go.exe build`.  This has worked with previous versions of Go.  Here's the error message I get when I try building :  `go build command-line-arguments: c:\go\pkg\tool\windows_386\compile.exe: exit status 1073741855`

4. What did you expect to see?
No error

5. What did you see instead?
Using version 1.6:
`go build command-line-arguments: c:\go\pkg\tool\windows_386\compile.exe: exit status 1073741855`

__Take away:__ There is some issue with Windows x386 version that did not exist previously.  Thanks!

**Comment by quentinmit** [comment] 2016-08-11 18:58
Can you try using the 64-bit compiler to make a 32-bit binary? Set the `GOARCH` environment variable to `386` before invoking go build.

Marking as Go1.8 since this is not a regression in 1.7.

**Comment by quentinmit** [comment] 2016-08-11 18:59
Also, can you please provide the complete output of the "go env" as the template requests? (Assuming that doesn't itself crash.) Thanks.

**Comment by brydavis** [comment] 2016-08-11 20:19
__SOLUTION__

`env GOARCH=386 \go\bin\go.exe build` or `env GOARCH=386 go build`

I tested by recompiling a database app with and without the `env GOARCH=386` prefix.  (Again, note that I need 32-bit app so it could connect to legacy database).  It worked with the prefix!  I was able to query the database (an old IBM product).

Thanks for the tip, @quentinmit.

**Comment by brydavis** [comment] 2016-08-11 20:19
Here's the `env` info too.

	set GOARCH=amd64
	set GOBIN=
	set GOEXE=.exe
	set GOHOSTARCH=amd64
	set GOHOSTOS=windows
	set GOOS=windows
	set GOPATH=
	set GORACE=
	set GOROOT=c:\go
	set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
	set GO15VENDOREXPERIMENT=1
	set CC=gcc
	set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
	set CXX=g++
	set CGO_ENABLED=1

**Comment by brydavis** [comment] 2016-08-11 20:21
Closing issue

**Comment by quentinmit** [comment] 2016-08-13 02:48
I'm glad the workaround worked for you, but we'd still like to find out if there is something wrong with the 386 Go binaries. Can you see if the 1.7rc6 386 binaries also crash on your machine?

**Comment by hirochachacha** [comment] 2016-08-14 15:07
What version of Windows are you using? I could not reproduce it on my Windows 10.

**Comment by brydavis** [comment] 2016-08-14 21:00
I'll test if 1.7rc6 works.  Might be midweek before I have chance.

Running on Windows 7.

**Comment by brydavis** [comment] 2016-08-15 17:15
Plot thickens...

I downloaded **1.7rc6 386** binaries and attempted to compile a couple programs (both simple and complex).  Here' s error message:

`go tool: no such tool "compile"`

Hope this helps.

**Comment by hirochachacha** [comment] 2016-08-15 17:51
I suspect that $GOROOT doesn't match newly installed location. 
Can you check output of `go env` is correct? If no, please set environmental variable manually, then retry it.

**Comment by brydavis** [comment] 2016-08-15 18:36
As previously stated, I do not have admin rights on this computer, unable to set system environments (aside from an annoying `%go%` user environment variable).  

I use binaries on this computer, thus building via `/go/bin/go.exe build`.  This works in all other circumstances, except for 386 compilers somewhere after version 1.3~.

Please see above for `go env` output.

**Comment by hirochachacha** [comment] 2016-08-15 19:23
Your `go env` is strange. If you use 386 version of Go, $GOARCH should be 386.
Are you sure you are using downloaded binary?

**Comment by brydavis** [comment] 2016-08-15 19:54
That's probably the output from the 64-bit binary (original issue was with 386; I'll change above comment when I have a chance).  Since I'm using binaries, `GOARCH` willl be whatever default is... For example, the binary for **1.7rc6 386** is `GOARCH=386`.

**Comment by hirochachacha** [comment] 2016-08-15 19:57
Did you extract zip file to C:\Go?

**Comment by brydavis** [comment] 2016-08-15 20:08
Yes, extracted from zip.

**Comment by hirochachacha** [comment] 2016-08-15 20:19
Are you using an unix-like shell?

**Comment by hirochachacha** [comment] 2016-08-15 20:21
(I can't see `env` command on my `cmd.exe`)

**Comment by brydavis** [comment] 2016-08-15 20:26
`env` works fine on both terminal apps I use (including `cmd.exe`)

**Comment by hirochachacha** [comment] 2016-08-15 20:30
Hmm, does $GOTOOLDIR exists? (e.g "C:\Go\pkg\tool\windows_386")

**Comment by brydavis** [comment] 2016-08-15 20:36
Yep, that folder exists

**Comment by hirochachacha** [comment] 2016-08-15 20:39
can you invoke compile.exe x.go in that directory? (x.go is your source code)

**Comment by brydavis** [comment] 2016-08-15 21:11
@hirochachacha, are you able to replicate the error messages?

**Comment by hirochachacha** [comment] 2016-08-16 00:41
I can replicate `go tool: no such tool "compile"` by setting wrong $GOROOT or $GOTOOLDIR.

I cannot replicate `go build command-line-arguments: c:\go\pkg\tool\windows_386\compile.exe: exit status 1073741855`. I want to know that If you  run `compile.exe` directly on Go 1.7, you will get same error as on Go 1.6.3.

Because two error messages indicate different issue.

**Closed** 2016-10-20 14:23 UTC
Labels: OS-Windows, WaitingForInfo
