### ISSUE TITLE
How is the real-time performance of the GMP model

### ISSUE THREAD

**Issue by 1511563371** [golang/go#66596] opened 2024-03-29 13:43 UTC
i want to kow the  real-time performance of the GMP model

**Comment by ALTree** [comment] 2024-03-29 13:52
Hi,

the Go project does not use its bug tracker for general discussion or asking questions about the language. The Github bug tracker is only used for tracking bugs and proposals going through the Proposal Process.

Please see the [Questions wiki page](https://github.com/golang/go/wiki/Questions); it has a list of good places for asking questions. Thanks!

Closing here, since this is not a bug.

**Closed by ALTree** 2024-03-29 13:52 UTC
