### ISSUE TITLE
runtime: nameOff 0x1359ea0 out of range 0xae3000 - 0xead27e

### ISSUE THREAD

**Issue by RO-29** [golang/go#35145] opened 2019-10-25 07:04 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.13.3
</pre>

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/developers/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build347085173=/tmp/go-build -gno-record-gcc-switch
</pre></details>

### What did you do?
Log the error
```func getHTTPServerRequest(myerr error) *http.Request {
    var werr interface {
        HTTPServerRequest() *http.Request
    }
    ok := errors.As(myerr, &werr)
    if ok {
        return werr.HTTPServerRequest()
    }
    return nil
}
```

### What did you expect to see?

Don't panic

### What did you see instead?

Code was panicking
```
runtime: nameOff 0x1359ea0 out of range 0xae3000 - 0xead27e
fatal error: runtime: name offset out of range
goroutine 39 [running]:
runtime.throw(0xc9b54b, 0x21)
/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0004c5a10 sp=0xc0004c59e0 pc=0x430f42
runtime.resolveNameOff(0xbb7460, 0x1359ea0, 0xb05eb4)
/usr/local/go/src/runtime/type.go:190 +0x2e7 fp=0xc0004c5a78 sp=0xc0004c5a10 pc=0x457c87
internal/reflectlite.resolveNameOff(0xbb7460, 0x1359ea0, 0xb05eb4)
/usr/local/go/src/runtime/runtime1.go:497 +0x33 fp=0xc0004c5aa0 sp=0xc0004c5a78 pc=0x4413f3
internal/reflectlite.(*rtype).nameOff(...)
/usr/local/go/src/internal/reflectlite/type.go:416
internal/reflectlite.implements(0xba38e0, 0xbb7460, 0x7f2354348b00)
/usr/local/go/src/internal/reflectlite/type.go:749 +0x4fa fp=0xc0004c5bd8 sp=0xc0004c5aa0 pc=0x469ffa
internal/reflectlite.(*rtype).AssignableTo(0xbb7460, 0xe818e0, 0xba38e0, 0x7f2354348b78)
/usr/local/go/src/internal/reflectlite/type.go:680 +0x81 fp=0xc0004c5c00 sp=0xc0004c5bd8 pc=0x469a91
errors.As(0xe66740, 0xc0002e3420, 0xb414e0, 0xc0002c68a0, 0xc0002c6890)
/usr/local/go/src/errors/wrap.go:80 +0x252 fp=0xc0004c5cc0 sp=0xc0004c5c00 pc=0x46d622
```

**Comment by randall77** [comment] 2019-10-25 16:23
Could you provide a complete program that demonstrates the error?

**Comment by pierrre** [comment] 2019-10-29 09:10
Hello !
(I'm working at the same company as @RO-29 , so I'm also trying to fix this issue)

> Could you provide a complete program that demonstrates the error?

It will be very difficult:
- it's a closed source application
- the code size is quite large
- it happened once on a server, and we can't reproduce the issue anymore

According to the other Github issues that match the search `fatal error: runtime: name offset out of range`, it seems related to a memory corruption.
We are not using the `unsafe` package anywhere in our application. (maybe a third party dependencies is doing it :man_shrugging: )

The code that triggered the error is
```go
    var werr interface {
        HTTPServerRequest() *http.Request
    }
    ok := errors.As(myerr, &werr)
    if ok {
        return werr.HTTPServerRequest()
    }
    return nil
```
We are trying to find the error in the chain that matches this interface.

Since we're not able to reproduce the error easily, should we close the Github issue ?

**Comment by ianlancetaylor** [comment] 2019-10-29 14:54
I agree that this looks like memory corruption.  If it happened exactly once and you can't reproduce it, then I don't think we'll be able to make progress.  So closing.  But please do comment if it happens again.  Thanks.

**Closed by ianlancetaylor** 2019-10-29 14:54 UTC
Labels: WaitingForInfo
