### ISSUE TITLE
go:generate incorrectly runs string consts.

### ISSUE THREAD

**Issue by james-lawrence** [golang/go#20954] opened 2017-07-08 16:59 UTC
version: go1.8.3 linux/amd64

```
package main

const example = `
//go:generate echo hello world
`
```

```
go generate .
hello world
```

**Comment by ALTree** [comment] 2017-07-08 17:04
Thanks for the report.

In `$ go generate -h`:

> [...]
Note that go generate does not parse the file, so lines that look
like directives in comments or multiline strings will be treated
as directives.
[...]

Closing this, since it's not a bug.

**Closed by ALTree** 2017-07-08 17:04 UTC

**Comment by james-lawrence** [comment] 2017-07-08 17:06
that might want to be re-evaluated. its odd and unexpected behaviour (even if documented). is there a reason for this choice?

**Comment by ALTree** [comment] 2017-07-08 17:14
I guess that one reason may be the fact that doing it this way does not require the tool to parse the file. The doc hints at this:

> Note that go generate does not parse the file

If you want to have a more authoritative answer, I think the right place to ask this is golang-dev: https://groups.google.com/forum/#!forum/golang-dev
