### ISSUE TITLE
exec.Command passes the binary name, not the absolute Path, as argv[0]

### ISSUE THREAD

**Issue by eloff** [golang/go#46458] opened 2021-05-30 18:28 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

That is the latest release

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/eloff/.cache/go-build"
GOENV="/home/eloff/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/eloff/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/eloff/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/eloff/projects/xxx/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1579395567=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

<pre>
cmd = exec.Command("psql", "host=127.0.0.1 user=xxx")
cmd.Env = append(cmd.Env, "PGPASSWORD="+conf.Password)

fmt.Println(cmd.Args)
fmt.Println(cmd.Path)
</pre>

### What did you expect to see?

<pre>
/usr/lib/postgresql/12/bin/psql
[/usr/lib/postgresql/12/bin/psql host=127.0.0.1 user=xxx]
</pre>

### What did you see instead?

<pre>
/usr/lib/postgresql/12/bin/psql
[psql host=127.0.0.1 user=xxx]
</pre>

I don't know if this is a bug. argv[0] can be any arbitrary name of the executable, it doesn't have to be the absolute path. However, psql at least expects it to be an absolute path and fails:

<pre>
could not find a "psql" to execute
psql: fatal: could not find own program executable
psql exited with code 1
</pre>

That leaves two questions:
1) Is it better to use the absolute path as argv[0]?
2) Can this be changed without breaking backwards compatibility?

If the answer to either of these questions is no, could we just document this behavior in the docs for Command? It's already documented that it will use LookPath, but not that it won't use that value as argv[0] - it uses the original value for name instead. That would have saved me a lot of effort.

The workaround here is simply to invoke LookPath first:

<pre>
path, err := exec.LookPath("psql")
cmd = exec.Command(path, "host=127.0.0.1 user=xxx")
</pre>

**Comment by seankhliao** [comment] 2021-05-30 18:35
Duplicate of #17536

and it is documented as:

> Args[0] is always name, not the possibly resolved Path.

**Closed by seankhliao** 2021-05-30 18:35 UTC

**Comment by eloff** [comment] 2021-05-30 18:39
Nevermind, I'm blind. It is indeed documented.
