### ISSUE TITLE
x/tools/gopls: changing build tags does not take effect without restarting the server

### ISSUE THREAD

**Issue by hyangah** [golang/go#43432] opened 2020-12-30 15:23 UTC
gopls version v0.6.1
go version 1.15.6

### How to repro

Open a folder with the following two go files 

```
$ cat main.go
package main

func main() {
        F()
}
$ cat tag.go
//+build tag1

package main

func F() {}
```

Gopls correctly shows the issue in both `main.go` and `tag.go` as expected. 

![Screen Shot 2020-12-30 at 10 16 13 AM](https://user-images.githubusercontent.com/4999471/103363305-c8cfc780-4a88-11eb-8fbb-fae257f4a999.png)

Now, remove `//+build tag1` from tag.go and save. 
The old diagnostic message in main.go lingers.

![Screen Shot 2020-12-30 at 10 16 44 AM](https://user-images.githubusercontent.com/4999471/103363339-e00eb500-4a88-11eb-93f1-afb05a86e80a.png)

What's more puzzling is:
When adding back `//+build tag1`, all the diagnostics disappear.

![Screen Shot 2020-12-30 at 10 20 34 AM](https://user-images.githubusercontent.com/4999471/103363354-eb61e080-4a88-11eb-9f21-ebad5ad6f351.png)

**Comment by stamblerre** [comment] 2020-12-30 15:47
This seems like at least a partial duplicate of #38732.

**Comment by hyangah** [comment] 2020-12-30 15:50
Hah! I filed the same issue. Feel free to close one of them. :-)

**Closed** 2020-12-30 15:56 UTC
Labels: Tools, gopls
