### ISSUE TITLE
x/pkgsite: pkgsite supports dark theme

### ISSUE THREAD

**Issue by oiooj** [golang/go#45699] opened 2021-04-22 14:13 UTC
What are the advantages of dark mode?

* It’s better for low-light settings
* There will be less ‘blue light’ emitted from your laptop – which can keep you awake if you use your laptop before you go to bed
* Can use less energy so your laptop battery will last longer
* Can potentially reduce eye strain and dry eyes in low-light conditions
* Some experts say dark mode can help people with light sensitivity or visual impairment.

So as a commonly used tool, pkgsite should support dark mode.

**Comment by jamalc** [comment] 2021-04-22 14:33
Duplicate of #36980

**Closed by jamalc** 2021-04-22 14:33 UTC
Labels: pkgsite
