### ISSUE TITLE
cmd/compile: duplicate anonymous interface declarations cause non-determinism

### ISSUE THREAD

**Issue by jellevandenhooff** [golang/go#30202] opened 2019-02-13 08:29 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go 1.11.5
</pre>

### Does this issue reproduce with the latest release?

This happens on both go 1.11.5 and go 1.12rc1

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jelle/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jelle/hack/backend/go"
GOPROXY=""
GORACE=""
GOROOT="/Users/jelle/hack/backend/opt/go1.11.5"
GOTMPDIR=""
GOTOOLDIR="/Users/jelle/hack/backend/opt/go1.11.5/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7n/4n_h9yg109b8kkpk1974y86h0000gp/T/go-build173276175=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

Similar to https://github.com/golang/go/issues/27013 but with the addition of concurrency, the go compiler produces a non-deterministic small.a output when running on the following minimized test program.

```go
package small

func A(x interface {
        X() int
}) int {
        return x.X()
}

func B(x interface {
        X() int
}) int {
        return x.X()
}
```

To demonstrate:

```shell
for i in {1..20}; do
  go tool compile -c 2 -p small -linkobj small.a small.go &&
  md5 small.a
done | sort | uniq -c
```

### What did you expect to see?

The go compiler produces the same output each time it is run, since it receives the same inputs.

The little script above should only see one hash from the 20 `small.a` files.

### What did you see instead?

The go compiler produces non-deterministic output

```
  12 MD5 (small.a) = bc3a55c714f25041576fe53690c16732
   8 MD5 (small.a) = fae691f5253d0dcb5991b1689c3c6006
```

### Notes

This issue is related to https://github.com/golang/go/issues/27013. The fix for that issue (https://go-review.googlesource.com/c/go/+/129515/) does not work for concurrent builds. It imposes an ordering
based on invocation order of addsignat in src/cmd/compile/internal/gc.go, but that invocation order is non-deterministic.

This problems occurs in the wild in https://github.com/gogo/protobuf/blob/master/types/duration_gogo.go.

**Comment by odeke-em** [comment] 2019-02-13 12:40
Thank you for reporting this issue @jellevandenhooff!

I shall page some folks about it @josharian @mdempsky @randall77

**Comment by jellevandenhooff** [comment] 2019-02-13 22:34
I have a bit of a dream as a follow-up... It would be fantastic if there was some job scraping Github for go packages, build them a couple times, and find packages exhibiting non-deterministic builds.

**Comment by josharian** [comment] 2019-02-13 22:50
I did that in Go 1.9, as part of thoroughly testing concurrent compilation. :)

**Comment by Gnouc** [comment] 2019-03-04 03:00
@josharian @mdempsky @randall77 sorry to bother you in this issue, but related to https://github.com/golang/go/issues/29612

Should 2 anonymous interface in different package go to the same bucket in itable?

**Comment by randall77** [comment] 2019-03-04 03:20
@Gnouc I'm not sure entirely what you are asking.

Are you talking about the runtime `itabTable` in `runtime/iface.go`?  I'm going to assume you are.

That table is a hash table. The general rule is that two equal keys *must* map to the same bucket. Different keys *should* map to different buckets, but they don't have to. Different keys mapping to the same bucket make the code slower, but not wrong.

So ideally two otherwise identical anonymous interfaces in different packages *should* map to different buckets, but they don't have to.  Looking at the code, it seems like they would map to the same bucket, as we use a hash of the string representation of the interface type.  Not ideal, but this case probably doesn't happen often enough to warrant doing anything about it.

**Comment by Gnouc** [comment] 2019-03-04 04:13
@randall77 Thanks for the information. Can you take a look at #29612 when you have time.

**Comment by josharian** [comment] 2019-05-11 16:31
Bisecting #31975, which is a duplicate of this issue, yielded https://go-review.googlesource.com/106796, which was the introduction of the indexed export format. Not a surprise, in retrospect, but good to confirm.

Of note: https://go-review.googlesource.com/c/go/+/170037 added anonymous interfaces to the standard library (`internal/oserror`), so this now directly causes toolstash-check to have spurious failures.

**Comment by andybons** [comment] 2019-05-16 18:21
@randall77 any updates on this?

**Comment by josharian** [comment] 2019-05-16 18:30
@andybons https://golang.org/cl/162240 needs finishing up

**Closed** 2019-07-02 13:53 UTC
Labels: NeedsFix, release-blocker
