### ISSUE TITLE
panic: reflect.Value.Convert: value of type unsafe.Pointer cannot be converted to

### ISSUE THREAD

**Issue by freboat** [golang/go#33610] opened 2019-08-12 23:18 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.11.5
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```
//make a complict map for a point is easy
func mkmapStatic(ptr *map[string]int) {
    *ptr = make(map[string]int)
    (*ptr)["abc"] = 5
    (*ptr)["ced"] = 6
    fmt.Println("ptr: ", len(*ptr))
}

//but how to make a dynamic map by reflect
//in: a in map intf,need to copy
//out: a map ponter to out obj
func mkmapDynamic(in interface{}, out unsafe.Pointer ) {
    
     vin := reflect.ValueOf(in)
     tin := reflect.TypeOf(in)
     
     vout := reflect.ValueOf(out)
     
     
     //here panic: reflect.Value.Convert: value of type unsafe.Pointer cannot be converted to type map[string]int
     //how to copy in data to out ?
     mptr := vout.Convert(reflect.PtrTo(tin)) 
}


func testmap() {
    var mpin, mpout map[string]int
    mkmapStatic(&mpin)
    
    mkmapDynamic(mpin, unsafe.Pointer(&mpout))
}
```

### What did you expect to see?

make a map by reflect.TypeOf,  and set it into a  unsafe.Pointer

### What did you see instead?

panic: reflect.Value.Convert: value of type unsafe.Pointer

**Comment by dmitshur** [comment] 2019-08-13 02:35
I see you've written some comments in the code, but can you please copy them to fill in the answers to the "What did you expect to see?" and "What did you see instead?" questions. That'll make it easier to understand where the problem is. Thanks.

**Comment by ianlancetaylor** [comment] 2019-08-17 22:55
My understanding is that this is intentional.  If the reflect package permitted this conversion it would permit unsafe pointer conversions in packages that do not import the "unsafe" package.  Closing the issue, but please comment if you disagree.

**Closed by ianlancetaylor** 2019-08-17 22:55 UTC
Labels: WaitingForInfo

**Comment by freboat** [comment] 2019-08-20 13:04
@ianlancetaylor , sorry i missed the discuss, 
it doesn't make sense as what you said, 

1. if  user converts a **unsafe.Pointer**  to   an concrete pointer directly,
of course  he  imported the unsafe object, and  kowns the risk.

2. if user converts it in a pkg,  that's  what reflect dos now(import unsafe, but do not export to end user), it is not a good reason.

**Comment by ianlancetaylor** [comment] 2019-08-20 13:34
The reflect package uses the unsafe package to provide safe operations.  It doesn't provide unsafe operations.
