### ISSUE TITLE
x/pkgsite: package removal request for github.com/scottfeldman/merle

### ISSUE THREAD

**Issue by scottfeldman** [golang/go#49975] opened 2021-12-04 02:33 UTC
### What is the path of the package that you would like to have removed?

github.com/scottfeldman/merle
 
### Are you the owner of this package?

Yes

### What is the reason that you could not retract this package instead?

I can't use the retract option.  On github, the project was renamed to github.com/scottfeldman/merle-orig.  A new project reused the github.com/scottfeldman/merle project name.  Pkg.dev.go has references to the old project.  I would like to have the current project on pkg.dev.go removed so I can add the new project.  

Thank you.

**Comment by jamalc** [comment] 2021-12-10 16:05
Duplicate of #49822

**Closed by jamalc** 2021-12-10 16:05 UTC
Labels: pkgsite
