### ISSUE TITLE
cmd/go: go get -u <respo>@<branch>  update latest code  a long time later

### ISSUE THREAD

**Issue by maomaoguo2017** [golang/go#42576] opened 2020-11-13 03:23 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.6 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/gattaca/Library/Caches/go-build"
GOENV="/Users/gattaca/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/gattaca/git/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/gattaca/git/test-go-mod2/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2j/qk1sjybs0_sf7gz030rkvm4h0000gn/T/go-build365705725=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

mod1 (main branch): github.com/maomaoguo2017/test-go-mod1
mod2 (main branch): github.com/maomaoguo2017/test-go-mod2
mod2 dependent mod1;

(mod2)  mod.go
```
module github.com/maomaoguo2017/test-go-mod2

go 1.14

require github.com/maomaoguo2017/test-go-mod1 v0.0.3-0.20201112113544-07b048dab095
```
step1: mod1  merge branch "dev" into main (bfaf841) or just pull(62acd45);
step2: into mod2 and input
```
go get -v -u github.com/maomaoguo2017/test-go-mod1@main
<nothing output>
```

i expect  mod1 version in go.mod of mod2 will update to latest but nothing to happen...

after "go get -u github.com/maomaoguo2017/test-go-mod1@main" 
(mod2) mod.go
```
module github.com/maomaoguo2017/test-go-mod2

go 1.14

require github.com/maomaoguo2017/test-go-mod1 v0.0.3-0.20201112113544-07b048dab095
```
![image](https://user-images.githubusercontent.com/34433498/98942350-d1942a80-2528-11eb-8baa-57b6554f7ebe.png)

and when i run same command a long time later, it's ok.
```
go get -v -u github.com/maomaoguo2017/test-go-mod1@main
go: github.com/maomaoguo2017/test-go-mod1 main => v0.0.3-0.20201112125147-62acd45a2f00
go: downloading github.com/maomaoguo2017/test-go-mod1 v0.0.3-0.20201112125147-62acd45a2f00
```

Why??

**Comment by bcmills** [comment] 2020-11-13 03:51
By default, the `go` command uses `GOPROXY="https://proxy.golang.org,direct"` (and note that line in the `go env` output you pasted).

`proxy.golang.org` has a fairly long cache TTL for the mapping of branch-names to commits.

**Comment by bcmills** [comment] 2020-11-13 03:55
Duplicate of #38065

**Closed by bcmills** 2020-11-13 03:55 UTC

**Comment by maomaoguo2017** [comment] 2020-11-13 03:57
> By default, the `go` command uses `GOPROXY="https://proxy.golang.org,direct"` (and note that line in the `go env` output you pasted).
> 
> `proxy.golang.org` has a fairly long cache TTL for the mapping of branch-names to commits.

OK, thanks for your time. ^_^

**Comment by maomaoguo2017** [comment] 2020-11-13 10:04
if respo is private 'go get [-u]' is ok, i guess private is auto use 'GOPROXY=direct'.

if respo is public of myself,  can use 'GOPROXY=direct' safety
```
GOPROXY=direct go get -u github.com/maomaoguo2017/test-go-mod1@main
```
