### ISSUE TITLE
Proposal: Json Field Naming strategy

### ISSUE THREAD

**Issue by ysaakpr** [golang/go#16543] opened 2016-07-29 20:30 UTC
Is it possible to have something similar like Jackson kind of configuration options in json library

1. Naming Strategy
2. Ignore null
3. Accept single value as array
4. Fail on unknown properties.
5. Map unknown properties in a known json to different section.

These all are very useful handy configuration when we deal with serializations and de-serializations.
Can we get this supports added to the existing json library.

**Comment by quentinmit** [comment] 2016-08-01 20:27
I think this is a dupe of #16426. You can already do 2 and 3 by implementing the Unmarshaler interface, and you can do 1 with struct tags. 4 and 5 are part of #16426.

**Closed by quentinmit** 2016-08-01 20:27 UTC
